### ISSUE TITLE
Data lost while another app call sr_module_change_subscribe

### ISSUE THREAD

**Issue by zzyyll2** [sysrepo/sysrepo#1003]
### How to submit issue
Please use this text as a template and replace text in the sections or remove
the entire section if that does not apply to your issue. For example in case of
question or feature request, just description with some example is probably
fine. Also remember to use github's markup form properly, especially in case of
output or code listing.

### Things you may try first
(put "x" in "[]" if you already tried following)
* [] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description
One session edit-config some data in running datastore,then start another app which calls sr_module_change_subscribe(module_name should be root name better),and then switch first session,
use get-config ,the data using edit-config lost.

### Steps to Reproduce
1. [First Step]
start netopeer2-cli,
edit-config --target running --config=some.xml
get-config --source running ,it's ok

2. [Second Step]
create an app, some codes like this
    int rc = sr_module_change_subscribe(srSession, "root", _module_change_clb, NULL, 0, SR_SUBSCR_CTX_REUSE, &subscription);
then build and run it.

3. [Third Step]
switch the session at first step 
get-config --source running ,it's not ok.
the data lost.

I looks like that sysrepod has reloaded the data of startup datastore.

**Expected behavior:**
 [What you expected to happen]

**Actual behavior:**
 [What actually happened]

### Versions
Please provide versions for software needed to reproduce the bug:
Sysrepo version: latest
libyang version: latest
netopeer2-server: latest

Thanks!

**Comment by michalvasko** [comment]
Hi,
this too little information for me to even try to reproduce the issue. The very first thing you have not mentioned is having some subscription for the module whose data you are modifying in the first step `edit-config` `some.xml`. Without the subscription the command fails and the configuration is not applied, naturally. So, do you have any subscription to the module in the first step?

Regards,
Michal

**Comment by zzyyll2** [comment]
Yang file like this:
module Root {
    namespace "urn:test:params:xml:ns:yang:Root";
    prefix Root;
    container Root {
        leaf f1 {
            type string;
        }
    }
}

some.xml like this:
<Root xmlns="urn:test:params:xml:ns:yang:Root">
    <f1>test</f1>
</Root>

There are two apps in my environment, all call sr_module_change_subscribe.
One app calls sr_module_change_subscribe(srSession, "Root ", appA_clb, NULL, 0, SR_SUBSCR_CTX_REUSE, &subscription).
Another app calls sr_module_change_subscribe(srSession, "Root ", appB_clb, NULL, 0, SR_SUBSCR_CTX_REUSE, &subscription);

Step:
1.Start sysrepod,netopeer2-server and my first app.

2.Use netopeer2-cli to import data
edit-config --target running --config=some.xml
then get-config --source running,result is 
Data
<Root xmlns="urn:test:params:xml:ns:yang:Root">
    <f1>test</f1>
</Root>

3.Now,start my second app,then swith to netopeer2-cli and get-config --source running,result is 
Data

The data of /Root:Root/f1 lost.

**Comment by michalvasko** [comment]
Hi,
you are right, this is the default behaviour and it seems it is a feature, not a bug. If you want different behaviour, use some [flags](http://www.sysrepo.org/static/doc/html/group__cl.html#gac91898627ad5aeb589e6a3993a697d14) for `sr_module_change_subscribe` call.

Regards,
Michal

**Comment by zzyyll2** [comment]
I will try it, thanks.

**Comment by zzyyll2** [comment]
I modified my code:
appA changed to:   sr_module_change_subscribe(srSession, "Root ", appA_clb, NULL, 0, SR_SUBSCR_CTX_REUSE, &subscription).
appB changed to:   sr_module_change_subscribe(srSession, "Root ", appB_clb, NULL, 0, SR_SUBSCR_APPLY_ONLY | SR_SUBSCR_NO_ABORT_FOR_REFUSED_CFG,
            &module_subs);

I test it that the data lost again.

**Comment by michalvasko** [comment]
Hi,
yes, that seems correct to me. Based on the description of the flags, I believe you want to include `SR_SUBSCR_PASSIVE` in the second subscription for the data not to be lost.

Regards,
Michal

**Comment by zzyyll2** [comment]
Yes,it works. Thanks.
