### ISSUE TITLE
Threading model of subscription

### ISSUE THREAD

**Issue by briancui** [sysrepo/sysrepo#1006]
Currently, It is always one thread to execute subscription callback on SysRep client, however for a complex application, we wanted to have multiple threads to serve many callbacks. Is it doable?

I found you used pthread_mutex_unlock(&sm_ctx->subscriptions_lock) currently to protect subscriptions data structure, I am wondering if we can use read-write lock instead, then multiple threads are able to execute callbacks.

Thoughts?  

Thanks,
Brian

**Comment by michalvasko** [comment]
Hi Brian,
you can try what you propose, should be easy. However, I doubt it will all work properly with just this simple change. There will most likely be some additional work required and while we may get to allow more subscription callbacks to run at the same time and generally enhance these mechanisms, it is currentyl not a priority.

Regards,
Michal

**Comment by briancui** [comment]
Hi Michal,

Thanks for your response.

I think you are right, the more I read the code, the more complex than I thought. 

Looks need to spawn multi-threads to execute cl_sm_conn_msg_process after read the message from SysRepo sever,  however, in this case, we still need to send notification ACK to SysRepo Server in sequence, my question is will this disordered ACK matter?

Another questions, now, looks many subscriptions share same one fd connection on module basis, I am also wondering why we don't create a fd for each subscription? in the case, we just need to poll fd set and easily to support multiple threads.

Since you mentioned about priority, may I know if there are any priority features under development?

Thanks,
Brian

**Comment by michalvasko** [comment]
Hi Brian,
I cannot help you much with this part of the code, it worked well enough (with some limitations you mentioned) and I have no deeper understanding of it. There are certainly several ways of enhancing it and what you propose seems a reasonable solution, not sure if the best.

*sysrepo* currently supports all main features that were planned. Suffering from problems with its development organization and unexpected changes, there is currently no one interested in actively developing *sysrepo* further so there are no additional features under development. However, *sysrepo* is being used so support is required and provided. That is the current situation, it may change in the future.

Regards,
Michal
