### ISSUE TITLE
What happens if something goes wrong when subscriber is processing the  SR_EV_APPLY event ?

### ISSUE THREAD

**Issue by rosy8** [sysrepo/sysrepo#1008]
Hi,

As per sysrepo,
    SR_EV_APPLY,   /**< Occurs just after the changes have been successfully committed to the datastore,
                        the subscriber is supposed to apply the changes now, but it cannot deny the changes in this
                        phase anymore (any returned errors are just logged and ignored). */

But what if something goes wrong while subscriber is processing the SR_EV_APPLY notification ?
As per the above description, any errors returned from subscriber are ignored .. If that is the case the data does not get discarded from running db ?

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
yes, exactly what you said according to description. The data does not get discarded no matter what at that phase. The logic is that you should check whether the change is valid in `SR_EV_VERIFY` phase. Nevertheless, there is always a time difference so this design is not foolproof.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

Got it. 
Thank you for replying .

Regards,
Rosy
