### ISSUE TITLE
find wrong op-data-subtree for augment module if the top augment node is config false

### ISSUE THREAD

**Issue by qmm161** [sysrepo/sysrepo#1011]
### Things you may try first
(put "x" in "[]" if you already tried following)
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description
sysrepo get wrong op-data-subtree in _sysrepo-module-dependencies.xml_ for augment module if the top augment node is config false, and when i exec get cmd from netopeer-cli later, the parent configuration data of the augment node is deleted.

### Steps to Reproduce
1. install an augment module with top node flaged as config false
2. exec get cmd from netopeer-cli , and first get the correct data
3. exec get cmd again, then configuration data in parent node of the augment node is missing

### Attachments
1. test root module
2. test augment module 
3. content in _sysrepo-module-dependencies.xml_
[attachment.zip](https://github.com/sysrepo/sysrepo/files/1546322/attachment.zip)

expected xpath of op-data-subtree is **/Root:Root/Aug:Aug** , not **/Root:Root**

**Comment by qmm161** [comment]
when md_traverse_schema_tree loop through the augment module,  parent node of Aug node expected to be NULL, but it's not. 
node = node->parent; /* should be NULL */ 

same conditon check error existed when md_traverse_schema_tree try to call md_add_subtree_ref for Aug node.

**Comment by ostack** [comment]
should we think about the parent's  config flag(LYS_CONFIG_R or LYS_CONFIG_W  ) when we  update parent PRIV flag (PRIV_OP_SUBTREE or PRIV_CFG_SUBTREE).
And i  want also to know why should we define PRIV flag instead of using libyang's config flag

 /* pass some feedback to the parent node */
            parent = sr_lys_node_get_data_parent(node, true);
            if ((LYS_CONFIG_R & node->flags) && parent) {
                parent->priv = (void *)((intptr_t)parent->priv | PRIV_OP_SUBTREE);
            }
            if ((LYS_CONFIG_W & node->flags) && parent) {
                parent->priv = (void *)((intptr_t)parent->priv | PRIV_CFG_SUBTREE);
            }

**Comment by michalvasko** [comment]
@qmm161 It should now be fixed in the `devel` branch. If you have any other problems, let us know.

@ostack I would advise against trying to understand the code, it took me a few hours and it is not too well-written, but seems to work.

Regards,
Michal

**Comment by ostack** [comment]
after merge the change, the model above can be loaded,bu if we define grouping  in the augment,it report error like:
`sh-4.2# sysrepoctl.sh -L 4 -i -g Aug.yang -S 
[DBG] [140601725264832] (sr_log_stderr:141) Setting log level for stderr logs to 4.
Installing a new module from file 'Aug.yang'...
Installing the YANG file to '/nfoam/etc/sysrepo/yang/Aug.yang'...
Resolving dependency: 'Aug' imports 'Root'...
Installing the YANG file to '/nfoam/etc/sysrepo/yang/Root.yang'...
sysrepoctl: /root/zhao/gerrit/nfoam/sysrepo/src/module_dependencies.c:1747: md_traverse_schema_tree: Assertion `(intptr_t)child->priv & 1' failed.
/usr/bin/sysrepoctl.sh: line 9:  2499 Aborted                 $_IN_DOCK_PREFIX/bin/sysrepoctl $@
sh-4.2# ls`


the model of aug like below:
`module Aug {
    namespace "urn:test:params:xml:ns:yang:ran:aug";
	prefix AG;

    import Root{
        prefix RT;
    }
	
	grouping GroupTest_List {
        list Group_List {
            key "id";
			leaf id{
				type string;
			}
			leaf name{
				type string;
			}
        }
    }
	
	grouping Aug_Ctr {
	    container Aug{     
            config false;        
            leaf name{ 
                type string; 
            }   

            leaf value{
                type string;
            }
			uses GroupTest_List;
        }
	}
	
    augment "/RT:Root" {
        uses Aug_Ctr;
    }
}

`
