### ISSUE TITLE
Errors were encountered during exporting if imported module is not explicitly installed.

### ISSUE THREAD

**Issue by antoninbas** [sysrepo/sysrepo#1015]
### Things you may try first
* [x] Did you check if this is a duplicate issue?
* [] Did you test it on the latest sysrepo devel branch?

I did not try the devel branch but I am using 0.7.2 and it seems nothing relevant went into the devel branch since that release.

### Description
When running `sysrepocfg -d running openconfig-interfaces -x`, I get the following error:
```
[ERR] Error by lyd_new_path: Failed to create node "type" as a child of "config".
Errors were encountered during exporting. Cancelling the operation.
```
I'm confused because I do not get any error when I use `sr_get_items_iter` and `sr_get_item_next` for XPath `"/openconfig-interfaces:interfaces//*"`.

These are my installed modules:
```
Module Name                   | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
iana-if-type                  | 2014-05-08 | Installed   |                     |             |                               |
ietf-interfaces               | 2014-05-08 | Imported    |                     |             |                               |
openconfig-interfaces         | 2017-07-14 | Installed   | root:root           | 666         |                               |
openconfig-yang-types         | 2017-07-30 | Imported    |                     |             |                               |
openconfig-extensions         | 2017-04-11 | Imported    |                     |             |                               |
openconfig-types              | 2017-08-16 | Imported    |                     |             |                               |
openconfig-platform           | 2016-12-22 | Installed   | root:root           | 666         |                               |
openconfig-platform-types     | 2017-08-16 | Imported    |                     |             |                               |
ietf-netconf-notifications    | 2012-02-06 | Installed   | root:root           | 666         |                               |
ietf-netconf                  | 2011-06-01 | Imported    |                     |             |                               |
ietf-netconf-acm              | 2012-02-22 | Imported    |                     |             |                               |
```

**The error goes away when I explicitly install ietf-interfaces but I'm trying to avoid doing that and I'm not sure that it should be required. I would expect `sysrepocfg -d running openconfig-interfaces -x` to work in the same way as `sr_get_items_iter` / `sr_get_item_next`**. Please correct me if my understanding is not correct.

Note that this only happens if the data tree is not empty. This is my data tree when I explicitly install ietf-interfaces and I run `sysrepocfg -d running openconfig-interfaces -x`:
```
<interfaces xmlns="http://openconfig.net/yang/interfaces">
  <interface>
    <name>veth0</name>
    <config>
      <name>veth0</name>
      <mtu>1500</mtu>
      <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
      <enabled>true</enabled>
    </config>
  </interface>
  <interface>
    <name>veth2</name>
    <config>
      <name>veth2</name>
      <mtu>1500</mtu>
      <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
      <enabled>true</enabled>
    </config>
  </interface>
</interfaces>
```

**Comment by michalvasko** [comment]
Hi,
I did not even managed to subscribe to `openconfig-interfaces` with the startup data you posted. The reason being that the node `type` has an invalid value. `ethernetCsmacd` has the base identity `interface-type`, which is in `ietf-interfaces`. However, that model is not implemented so no valid value can be set to the `type` node. It is the same problem you are having, you cannot avoid having `ietf-interfaces` implemented.

Regards,
Michal

**Comment by antoninbas** [comment]
Isn't `ethernetCsmacd` in `iana-if-type`?
I can do the following fine without having `ietf-interfaces` implemented, as long as `iana-if-type` is implemented (as shown in the `sysrepoctl -l` output above):
```
  {
    sr_val_t value = { 0 };
    value.type = SR_IDENTITYREF_T;
    value.data.string_val = const_cast<char *>("iana-if-type:ethernetCsmacd");
    std::string path = prefix + "/type";
    rc = sr_set_item(session, path.c_str(), &value, SR_EDIT_DEFAULT);
  }
```

Somehow it seems only `sysrepocfg` requires `ietf-interfaces` to be implemented, not the sysrepo client library.

That being said, it is not such a big deal for me to explicitly install `ietf-interfaces`, so maybe it is not worth investigating this.

**Comment by michalvasko** [comment]
Hi,
`ethernetCsmacd` is in `iana-if-type` but the identityref's base is `interfaces-type` which is in `ietf-interfaces`. That is the problem.

Regards,
Michal
