### ISSUE TITLE
"when condition not satisfied" error for operational state

### ISSUE THREAD

**Issue by antoninbas** [sysrepo/sysrepo#1018]
### Things you may try first
(put "x" in "[]" if you already tried following)
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description
I am using the openconfig-interfaces YANG model with the openconfig-if-ethernet augment (https://github.com/openconfig/public/blob/master/release/models/interfaces/openconfig-if-ethernet.yang).
Here is the augment statement in openconfig-if-ethernet:
```
  augment "/oc-if:interfaces/oc-if:interface" {
    description "Adds addtional Ethernet-specific configuration to
    interfaces model";

    uses ethernet-top {
      when "oc-if:state/oc-if:type = 'ift:ethernetCsmacd'" {
      description "Additional interface configuration parameters when
      the interface type is Ethernet";
      }
    }
  }
```
When I try to set a config leaf in the augment (for example `"/openconfig-interfaces:interfaces/interface[name='eth0']/openconfig-if-ethernet:ethernet/config/port-speed"`), I always get the following libyang error event when I subscribe an operational state provider for schema path `"/openconfig-interfaces:interfaces/interface/state/type"`:
```
[ERR] libyang error: When condition "openconfig-interfaces:state/openconfig-interfaces:type = 'iana-if-type:ethernetCsmacd'" not satisfied.
[ERR] Validation after merging failed
```

**Please see output of `sysrepocfg openconfig-interfaces -o -x` at the end which shows that my state provider works properly.**

### Steps to Reproduce
1. Install both openconfig YANG models
2. Create an interface
3. Write an operational state provider for `"/openconfig-interfaces:interfaces/interface/state/type"`
4. Try to set a config leaf which is added by the augment

I would be happy to provide some code if you think it would help troubleshoot.

**Expected behavior:**
 operation succeeds

**Actual behavior:**
libyang error in `sysrepod` output

### Versions
Please provide versions for software needed to reproduce the bug:
Sysrepo version: `sysrepod -v`: sysrepod - sysrepo daemon, version 0.7.2
libyang version: `yanglint -v`: yanglint 0.14.50

### Attachments
Please run sysrepo daemon in debug mode and write the logs to a file. For example:
`sysrepod -d -l 4 &> sysrepod.log`.

Output of `sysrepoctl -l`:
```
Sysrepo schema directory: /etc/sysrepo/yang/
Sysrepo data directory:   /etc/sysrepo/data/
(Do not alter contents of these directories manually)

Module Name                   | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
iana-if-type                  | 2014-05-08 | Installed   |                     |             |                               |
ietf-interfaces               | 2014-05-08 | Installed   | root:root           | 666         |                               |
openconfig-interfaces         | 2017-07-14 | Installed   | root:root           | 666         |                               |
openconfig-yang-types         | 2017-07-30 | Imported    |                     |             |                               |
openconfig-extensions         | 2017-04-11 | Imported    |                     |             |                               |
openconfig-types              | 2017-08-16 | Imported    |                     |             |                               |
openconfig-platform           | 2016-12-22 | Installed   | root:root           | 666         |                               |
openconfig-platform-types     | 2017-08-16 | Imported    |                     |             |                               |
ietf-netconf-notifications    | 2012-02-06 | Installed   | root:root           | 666         |                               |
ietf-netconf                  | 2011-06-01 | Imported    |                     |             |                               |
ietf-netconf-acm              | 2012-02-22 | Imported    |                     |             |                               |
openconfig-if-ethernet        | 2017-07-14 | Installed   |                     |             |                               |
```

Output of `sysrepocfg openconfig-interfaces -o -x`:
```
<interfaces xmlns="http://openconfig.net/yang/interfaces">
  <interface>
    <name>eth0</name>
    <config>
      <name>eth0</name>
      <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
    </config>
    <state>
      <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
    </state>
  </interface>
</interfaces>
```

Thanks!

**Comment by michalvasko** [comment]
Hi,
your state data seems fine but when I tried to display the module `openconfig-if-ethernet` in *yanglint* it correctly warned that the node `state` cannot be found. Specifically, the node is not accessible (as per [this section](https://tools.ietf.org/html/rfc7950#section-6.4.1), you cannot access state data from configuration data) meaning the condition will always be false.

Regards,
Michal

**Comment by antoninbas** [comment]
Thanks a lot @michalvasko. I was going to open an issue in the openconfig repo but there is already one: https://github.com/openconfig/public/issues/108. I should have checked there first.
