### ISSUE TITLE
sr_get_item timeout with long list

### ISSUE THREAD

**Issue by hoannd** [sysrepo/sysrepo#1022]
### Things you may try first
(put "x" in "[]" if you already tried following)
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description
I try sr_get_item_example with my startup configuration. The configuration contains some lists with so many items, e.g my http-filter-list has 4000 http-filter. I try the example with the xpath is "/spgwdp-configuration:configuration/pgw/http-filter-list/http-filter[name='f_l7_freecdn7']/domain-name". But timeout has expired.

### Steps to Reproduce
1. Start sysrepod
2. Start sysrepo-plugind
3. Start netopeer2-server
4. Run the example sr_get_item_example

**Expected behavior:**
 Value of item can be get

**Actual behavior:**
 Timeout, so there is no any config data returned

### Versions
Please provide versions for software needed to reproduce the bug:
Sysrepo version: `sysrepod -v`. sysrepod - sysrepo daemon, version 0.7.1
libyang version: `yanglint -v` yanglint 0.13.88
netopeer2-server: `netopeer2-server -V` (optional) netopeer2-server 0.4.4

### Attachments
Please run sysrepo daemon in debug mode and write the logs to a file. For example:
`sysrepod -d -l 4 &> sysrepod.log`.
[sysrepod.log](https://github.com/sysrepo/sysrepo/files/1599874/sysrepod.log)

Similarly, if Netopeer2 server is used, also provide us with its log:
`netopeer2-server -d -v3 &> netopeer2-server.log` (optional)
[netopeer2-server.log](https://github.com/sysrepo/sysrepo/files/1599873/netopeer2-server.log)

Installed modules: `sysrepoctl -l`
[sr_get_item_example.log](https://github.com/sysrepo/sysrepo/files/1599861/sr_get_item_example.log)

Content of datastore used: check files in  Sysrepo data directory (default `/etc/sysrepo/data`).

**Comment by michalvasko** [comment]
Hi,
it depends what timeout expires but you can adjust almost all of them before building. Look into `README` of *libnetconf2* and *sysrepo*, that is where you will find information about relevant timeouts and how to change them.

Regards,
Michal

**Comment by hoannd** [comment]
Many thanks Michal for quick response. The example work after I try to change REQUEST_TIMEOUT with cmake as your suggest (cmake -DREQUEST_TIMEOUT:INTEGER=100 ..) and then rebuild sysrepo.

But it takes about 80 seconds to get the result. This should be a very long period. Could you show me a way to improve this?

**Comment by michalvasko** [comment]
Hi,
do you mean to reduce the time your request takes? That would fall into the category of optimizations which is not really the current focus so you are on your own.

Regards,
Michal

**Comment by hoannd** [comment]
Yes, that is so long time for a acceptable response at cli site. So looking forward to the optimization on this. At this time I will try to limit number of items of a sr_get_items_iter to be a smaller number.

With default REQUEST_TIMEOUT (3 sec), could you tell me an estimated number of how many items in a get_item request?

**Comment by michalvasko** [comment]
Hi,
I don't know that, you will have to try it yourself. Maybe 500?

Regards,
Michal

**Comment by hoannd** [comment]
Thanks Michal. I will try it myself and get back after have the result.

**Comment by hoannd** [comment]
I have just tried sr_subtree_change_subscribe api with our config data. I also had to increase REQUEST_TIMEOUT (more than 100 seconds). It seems that subscrible operation need more time than get-item.

**Comment by michalvasko** [comment]
Not relevant anymore.
