### ISSUE TITLE
after copy_config from candidate to running failed, the candidate and running datastore have been swappwd. 

### ISSUE THREAD

**Issue by ustcpxy** [sysrepo/sysrepo#1026]
### Things you may try first
(put "x" in "[]" if you already tried following)
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description
after copy_config failed, the candidate and running datastore have been swappwd. 

### Steps to Reproduce
1. edit one item on candidate datastore
2. copy_config from candidate to running (let the copy_config operation failed)
3. get config on the item from running
4. get config on the item from candidate

**Expected behavior:**
3. the item value is from running
4. the item value is from candidate

**Actual behavior:**
3. the item value is from candidate
3. the item value is from ruuning

### Versions
Please provide versions for software needed to reproduce the bug:
Sysrepo version: latest devel
libyang version: latest devel
netopeer2-server: latest devel

**Comment by michalvasko** [comment]
Hi,
I will need a bit more details. How did you manage to make the copy-config fail? If you set the item with an invalid value, the edit itself should have failed.

Regards,
Michal

**Comment by ustcpxy** [comment]
Hi Michal,
Thanks for your reply. 

firstly, the item value which I set is correct. 
during DM_COMMIT_NOTIFY_VERIFY phase, the SR_EV_VERIFY event would be delivered to module change subscriber. 
I will let the module change callback return error to make the verify fail. finally, the copy-config would be failed.
