### ISSUE TITLE
a module "installed" in sysrepo is not "implemented" libyang?

### ISSUE THREAD

**Issue by jjin62** [sysrepo/sysrepo#1027]
### Things you may try first
(put "x" in "[]" if you already tried following)
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description
Set identity failed.
sysrepod log:
[ERR] (dm_ly_log_cb:1288) libyang error: Identity found, but in a non-implemented module "openconfig-optical-amplifier".
[ERR] (dm_ly_log_cb:1288) libyang error: Failed to resolve identityref "openconfig-optical-amplifier:EDFA".
[ERR] (dm_ly_log_cb:1288) libyang error: Failed to create node "type" as a child of "config".
[ERR] (rp_dt_set_item:431) Setting of item failed /org-openroadm-device:open-optical-device/optical-amplifier/amplifiers/amplifier[name='ab']/config/type 29
[ERR] (rp_dt_set_item_wrapper:596) Set item failed
[ERR] (rp_set_item_req_process:1202) Set item failed for '/org-openroadm-device:open-optical-device/optical-amplifier/amplifiers/amplifier[name='ab']/config/type', session id=1404300439.

sysrepoctl -l show that the module is installed:
openconfig-optical-amplifier  | 2017-06-15 | Installed   | jimmy:jimmy         | 666         |            

### Versions
Please provide versions for software needed to reproduce the bug:
Sysrepo version: sysrepo daemon, version 0.7.2
libyang version: yanglint 0.14.56

**Note: sysrepo 0.7.0 and libyang 0.13.43 has no this issue.**

**Comment by michalvasko** [comment]
Hi,
could you please post the full output of `sysrepoctl -l` and maybe also with the order of modules being installed (it may matter)? Then, what operation produced the error, simply setting the identity value to a node (either using edit-config and `netopeer2-server` or with `sysrepocfg`)?

Regards,
Michal

**Comment by jjin62** [comment]
Michal,
Thanks for the hint.  This happens when I use sysrepocfg to import a startup file. I did some testing and seems the module install order is the reason.
1) This issue happens when openconfig-optical-amplifier (where the identityref is defined) is installed before installing org-openroadm-device, which import openconfig-optical-amplifier. 
2) if the order is reversed, then it works.
3) when 1) happens, even I install openconfig-optical-amplifier again, it wouldn't fix the issue.

**Comment by jjin62** [comment]
another observation is that, this issue only happens when sysrepod is running. if sysrepod is not running, I can use sysrepocfg --import the startup file just fine.

**Comment by michalvasko** [comment]
Hi,
can you please provide `org-openroadm-device` model that imports `openconfig-optical-amplifier`? I have only found [one that doesn't](https://github.com/opendaylight/transportpce/blob/master/ordmodels/src/main/yang/org-openroadm-device.yang).

Regards,
Michal

**Comment by jjin62** [comment]
We did some customization to org-openroadm-device.yang. But issue is generic. I created an example to simplify the test.

openconfig-optical-amplifier.yang:
```
module openconfig-optical-amplifier {
  yang-version "1";
  namespace "http://openconfig.net/yang/optical-amplfier";

  prefix "oc-opt-amp";
  organization "OpenConfig working group";

  revision "2016-03-31" {
    description
      "Initial public release";
    reference "0.1.0";
  }
  identity OPTICAL_AMPLIFIER_TYPE {
    description
      "Type definition for different types of optical amplifiers";
  }
  identity EDFA {
    base OPTICAL_AMPLIFIER_TYPE;
    description
      "Erbium doped fiber amplifer (EDFA)";
  }
  identity FORWARD_RAMAN {
    base OPTICAL_AMPLIFIER_TYPE;
    description
      "Forward pumping Raman amplifier";
  }

  grouping optical-amplifier-config {
    description
      "Configuration data for optical amplifiers";

    leaf name {
      type string;
      description
        "User-defined name assigned to identify a specific amplifier
        in the device";
    }

    leaf type {
      type identityref {
        base OPTICAL_AMPLIFIER_TYPE;
      }
      description
        "Type of the amplifier";
    }

  }
  grouping optical-amplifier-top {
    description
      "Top-level grouping for optical amplifier data";

    container optical-amplifier {
      description
        "Enclosing container for amplifiers and supervisory channels";

      container amplifiers {
        description
          "Enclosing container for list of amplifiers";

        list amplifier {
          key "name";
          description
            "List of optical amplifiers present in the device";

          leaf name {
            type leafref {
              path "../config/name";
            }
            description
              "Reference to the name of the amplifier";
          }

          container config {
            description
              "Configuration data for the amplifier";

            uses optical-amplifier-config;
          }

        }
      }

    }
  }
  // data definition statements
  uses optical-amplifier-top;
}
```

oc-amp.yang:
```
module oc-amp {
  yang-version "1";
  namespace "http://oc.net/yang/amp";
  prefix "oc-amp";
  import openconfig-optical-amplifier { prefix oc-opt-amp; }

  container top {
     uses oc-opt-amp:optical-amplifier-top;
  }
}
```
oc-amp.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<top xmlns="http://oc.net/yang/amp">
    <optical-amplifier xmlns:oc="http://openconfig.net/yang/optical-amplfier">
        <amplifiers>
            <amplifier>
                <name>ab</name>
                <config>
                    <type>oc:EDFA</type>
                    <name>ab</name>
                </config>
            </amplifier>
        </amplifiers>
    </optical-amplifier>
</top>
```

**testing**
1) start sysrepod;
2) sysrepoctl --install --yang=openconfig-optical-amplifier.yang
3) sysrepoctl --install --yang=oc-amp.yang
4) sysrepocfg --import=oc-amp.xml --datastore=startup oc-amp
[ERR] (cl_request_process:562) Error by processing of the set-item request (session id=1247671725): Invalid argument.
[ERR] (sr_set_item:1844) Error by processing of the request.
[ERR] (srcfg_convert_lydiff_created:713) Error returned from sr_set_item: Invalid argument.
Errors were encountered during importing. Cancelling the operation.

sysrepod error:
[ERR] (dm_ly_log_cb:1288) libyang error: Identity found, but in a non-implemented module "openconfig-optical-amplifier".
[ERR] (dm_ly_log_cb:1288) libyang error: Failed to resolve identityref "openconfig-optical-amplifier:EDFA".
[ERR] (dm_ly_log_cb:1288) libyang error: Failed to create node "type" as a child of "config".
[ERR] (rp_dt_set_item:431) Setting of item failed /oc-amp:top/optical-amplifier/amplifiers/amplifier[name='ab']/config/type 29
[ERR] (rp_dt_set_item_wrapper:596) Set item failed
[ERR] (rp_set_item_req_process:1202) Set item failed for '/oc-amp:top/optical-amplifier/amplifiers/amplifier[name='ab']/config/type', session id=1247671725.

**observations:**
a) if don't start sysrepod (skip step1). it works
b) reverse 2) and 3), it works.
c) after error, do 2) again, still error.

**Comment by michalvasko** [comment]
Hi,
I tried the steps on my machine and in a virtual Ubuntu 16.04.3, worked in both cases. You probably have some left-over old version of either *libyang* or *sysrepo* so please correctly remove them and try to reinstall. Then try again, it should work.

Regards,
Michal

**Comment by jjin62** [comment]
Yes, it is my environment issue. Sorry for the false alarm.
