### ISSUE TITLE
after commit candidate, the candidate datastore can not be locked.

### ISSUE THREAD

**Issue by ustcpxy** [sysrepo/sysrepo#1028]
### Things you may try first
(put "x" in "[]" if you already tried following)
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description
edit candidate, the operation is successful.
then lock candidate, netconf client will receive an error reply. the error message is: `Module has been modified, it can not be locked. Discard or commit changes`
ok, commit candidate. the operation is successful. 
then lock it again. it is still can not be locked. (netconf client still received the same error reply)

**Expected behavior:**
after commit candidate, the candidate can be locked.

**Actual behavior:**
the candidate can not be locked.

### Versions
Please provide versions for software needed to reproduce the bug:
Sysrepo version: latest devel
libyang version: latest devel
netopeer2-server: latest devel

**Comment by michalvasko** [comment]
Hi,
I have tried this and it worked for me. I will probably need some previous commands, best would be all the commands you executed on that session until the error so I can replicate it.

Regards,
Michal

**Comment by ustcpxy** [comment]
Hi Michal,
I try it again with the latest devel 84bb982d87294117fb507eed9da7ea0e79773043 and it works fine.
Thanks.
