### ISSUE TITLE
Question: can I skip the commit-write stage?

### ISSUE THREAD

**Issue by ustcpxy** [sysrepo/sysrepo#1031]
during committing operation, it would write the whole data tree to module running file.
while my system have huge running data, it would take much time to write file even if I edit only one item.

I'm aware that the .running files do not need. please refer to the issue #966 
so can I skip the writing files steps during committing operation?
the modified code like below:

```diff
diff --git a/src/rp_dt_edit.c b/src/rp_dt_edit.c
index e4d03e18..8c56453b 100644
--- a/src/rp_dt_edit.c
+++ b/src/rp_dt_edit.c
@@ -904,6 +904,7 @@ rp_dt_commit(rp_ctx_t *rp_ctx, rp_session_t *session, dm_commit_context_t **c_ct
             *c_ctx = commit_ctx;
             return SR_ERR_OK;
         case DM_COMMIT_WRITE:
+#if 0
             rc = dm_commit_writelock_fds(session->dm_session, commit_ctx);
             if (SR_ERR_OK == rc ) {
                 rc = dm_commit_write_files(session->dm_session, commit_ctx);
@@ -920,6 +921,7 @@ rp_dt_commit(rp_ctx_t *rp_ctx, rp_session_t *session, dm_commit_context_t **c_ct
                     rc = rp_dt_reload_nacm(rp_ctx);
                 }
             }
+#endif
             state = DM_COMMIT_NOTIFY_APPLY;
             break;
         case DM_COMMIT_NOTIFY_APPLY:


```

**Comment by michalvasko** [comment]
Hi,
in theory and based on my knowledge, the only consequence of this change would be that any changes in the `running` datastore by a session would be visible only in that session. Meaning if you start the first and only session, never terminating it, only after you are completely done working with `sysrepo`, it could work.

However, as soon as you modify the running configuration in one session and make any changes in another, I think it will all break. Callbacks will be called for changes that were already performed and other invalid behaviour may occur. Also, if you are using `netopeer2-server`, you cannot do this as it uses several internal sessions before any NETCONF client even connects.

Also, as said at the beginning, this is only what I think. I have never tried it and it is possible this change will break something else so you will be on your own debugging it in that case. It would be a waste of time for me.

Regards,
Michal

**Comment by ustcpxy** [comment]
Hi Michal,
I understand. Thanks. 
yes, I use the `netopeer2-server` as the NETCONF server. and after changing it, I can not get anything running config.
