### ISSUE TITLE
Oder of processing

### ISSUE THREAD

**Issue by rosy8** [sysrepo/sysrepo#1034]
Hi Michal,

Please correct me if I am wrong..
 edit-config -> commit
   1)Process SR_EV_VERIFY
    2)Verify Successful ..then Process SR_EV_APPLY...
So while still in this phase..if we triggered a new commit request, then the new config data will get added to the candidate db..but its not going to process it until  it gets the response for the 1st edit config operation.

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
it is really important here to distinguish between NETCONF (netopeer2-server) commit and sysrepo commit, they are quite different operations. Actually, we wanted to rename sysrepo commit to apply_changes but decided against it in the end to keep the API.

So, NETCONF edit-config actually calls sysrepo set functions and finishes with a sysrepo commit (apply the session changes and write them into the actual datastore). Those callbacks with SR_EV_VERIFY and SR_EV_APPLY are called on sysrepo commit. Knowing this, please ask again and be more specific.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

Thanks for replying back.
Suppose sysrepo is in the middle of applying config ( event SR_EV_APPLY has been triggered and yang module callback handler has also started its processing but it has not completed yet or return any response yet for event SR_EV_APPLY) and then another commit event gets initiated on the Netconf (netopeer2-server). So what will be the  behavior in that scenario ? 

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
I have never experienced this situation so I cannot say for sure but I think there will be some locks locked to prevent simultaneous changes to one module in a datastore meaning the first commit will first be finished and then the second one will be applied. You can try it out, should not be too difficult.

Regards,
Michal
