### ISSUE TITLE
Enabling of dependent features does not work (2)

### ISSUE THREAD

**Issue by frimpler** [sysrepo/sysrepo#1061]
Hi,

please have a look at this commit <https://github.com/frimpler/sysrepo/commit/f83bcf182298cd5337b40c2f33e68b555a5ae116>
It contains a test case + four yang modules which trigger an issues when enabling dependent featues. This problem has already been addressed by pull request https://github.com/sysrepo/sysrepo/pull/1043. Unfortunately, this test case didn't address all variants of feature dependencies, For this reason we have enhanced the test. Please have also a look at our proposed solution.

Description:
-------------
When dependent features are enabled and the corresponding persist data shall be applied the persist data of all features they depend on must be applied before to avoid the error "Feature XXX is disabled by its 1. if-feature condition". The proposed solution (https://github.com/frimpler/sysrepo/commit/c3e1e1ce1ada9cab55559c1a70b03e040ccee149) in sysrepo's data_manager.c processes all imported modules recursively by the function dm_apply_persist_data_for_model_imports() before the actual module is processed.

Regards,
Peter+Frank

**Comment by michalvasko** [comment]
Hi Peter and Frank,
your use-case seems valid and the solution is nice, so please create a pull request and if the tests pass, it can probably be merged, thanks!

Regards,
Michal
