### ISSUE TITLE
sysrepocfg failed to install

### ISSUE THREAD

**Issue by shifa23** [sysrepo/sysrepo#1063]
Hi,
I am getting the following error while performing the make command for sysrepo..

```
libsysrepo.so.0.7.3: undefined reference to `ly_path_data2schema'
libsysrepo.so.0.7.3: undefined reference to `ly_ctx_internal_modules_count'
collect2: error: ld returned 1 exit status
src/CMakeFiles/sysrepocfg.dir/build.make:100: recipe for target 'src/sysrepocfg' failed
make[2]: [src/sysrepocfg] Error 1
CMakeFiles/Makefile2:248: recipe for target 'src/CMakeFiles/sysrepocfg.dir/all' failed
make[1]: [src/CMakeFiles/sysrepocfg.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: [all] Error 2"
```

I have installed the libyang from the latest release, please let me know how to over come this issue.

Thanks in advance

**Comment by michalvasko** [comment]
Hi,
try the command `# ldconfig -p | grep libyang` and remove all the libraries except the most recent one (or delete them all and reinstall libyang). Most likely the libyang actually being loaded is some old version.

Regards,
Michal

**Comment by shifa23** [comment]
Hi Michal,
Thanks for your suggestion and I have done things as per your suggestions but still I'm getting the same error. 
**"[ 19%] Linking C executable sysrepocfg
libsysrepo.so.0.7.3: undefined reference to `ly_path_data2schema'
libsysrepo.so.0.7.3: undefined reference to `ly_ctx_internal_modules_count'
collect2: error: ld returned 1 exit status
src/CMakeFiles/sysrepocfg.dir/build.make:100: recipe for target 'src/sysrepocfg' failed
make[2]: *** [src/sysrepocfg] Error 1
CMakeFiles/Makefile2:248: recipe for target 'src/CMakeFiles/sysrepocfg.dir/all' failed
make[1]: *** [src/CMakeFiles/sysrepocfg.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2"**
I think there is some error due to this "**src/CMakeFiles/sysrepocfg.dir/build.make:100: recipe for target 'src/sysrepocfg' failed**" or in libsysrepo.so, please let me know how to resolve this.

Thanks in advance

**Comment by michalvasko** [comment]
Hi,
what I would like to start with is that this is basically a Linux problem, not sysrepo-specific, so you should be able to find solutions online. However, it cannot really be anything else than some library version mix-up. So, remove all the installed *libyang* and *libsysrepo* versions, remove all the generated build files (usually the contents of `build` directory, if you created it and built it there), and compile/install it all again. I cannot help you more.

Regards,
Michal
