### ISSUE TITLE
Query on sr_commit 

### ISSUE THREAD

**Issue by rosy8** [sysrepo/sysrepo#1065]
Hi Michal,

After getting SR_EV_VERIFY and SR_EV_APPLY events  , for one scenario sr_commit() fails with the error message (Requested resource is already locked). 
As per my understanding, when do sr_commit(), then sysrepo must have acquired the lock internally right ?
Or even if if could  not acquire the lock then it should throw the error at the beginning itself..
Why I do get this error message after getting the SR_EV_VERIFY events etc..?

Please let me know if I am missing something here.

Thanks in advance.
Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
I would say that something is wrong but I will not know unless you describe the scenario in more detail  and I can reproduce it.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

It was a mistake from my side.
Thanks for replying back.

Regards,
Rosy
