### ISSUE TITLE
Question about the removal of containers and lists

### ISSUE THREAD

**Issue by rwestphal** [sysrepo/sysrepo#1066]
Hi,

I've noticed that every time a container is deleted from the running datastore, sysrepo notifies my application about the removal of all child nodes of the container besides the container itself.

Example: after removing the `/frr:ripd/instance/networks` container, my application is notified about the removal of the following nodes:
```
/frr:ripd/instance/networks/network[prefix='10.0.1.0/24']/prefix
/frr:ripd/instance/networks/network[prefix='10.0.1.0/24']
/frr:ripd/instance/networks
/frr:ripd/instance/networks/network[prefix='10.0.2.0/24']/prefix
/frr:ripd/instance/networks/network[prefix='10.0.2.0/24']
```

Is there a way to change this behavior such that my application is notified only about the removal of the parent container or list?

**Comment by michalvasko** [comment]
Hi,
no, there is not, but nothing prevents you from ignoring the removals that do not interest you.

Regards,
Michal

**Comment by rwestphal** [comment]
Ok. Yeah, it's not a big deal. The only problem is that it can be expensive to process the removal of a large list (1000+ elements) if we have to process the removal of each element one by one. Ideally I'd like to have the ability to remove the entire list in a single callback for performance reasons. But for now this is only a hypothetical problem for me so I'll close this issue.

**Comment by michalvasko** [comment]
Hi,
I understand your problem but what would be your solution? Generic enough not to cause problems for use-cases where you want to be notified about all the changes. But like I said, you can very easily ignore your callback calls with XPath/operations that does not interest you.

Regards,
Michal

**Comment by rwestphal** [comment]
I think the easiest way to support this behavior without affecting other users would be to add a new flag in the `sr_subscr_flag_e` enumeration, something like `SR_SUBSCR_DELETE_NO_CHILDREN`. What do you think? I'm fine if you think this is too specific and not worth implementing, but if you decide to implement something like that it would be very much appreciated from my side :)

**Comment by michalvasko** [comment]
Hi,
I guess you said it, it is too specific and not worth implementing, the logic inside *sysrepo* would not be as simple as it seems if we were to support this. Sorry.

Regards,
Michal

**Comment by rwestphal** [comment]
No problem, it's something that is really easy to workaround on the application side. Thanks for you attention :)
