### ISSUE TITLE
Receiving notifications about own changes in the running datastore

### ISSUE THREAD

**Issue by rwestphal** [sysrepo/sysrepo#1067]
Hi,

I have an application that subscribes to sysrepo to be notified about changes in the running datastore. The same application also implements a CLI that can change the running configuration using functions like `sr_set_item()`, `sr_delete_item()` and `sr_commit()`. I realized that every time I change the running configuration using the CLI, the application receives a notification from sysrepo about the change (via the callback function of `sr_module_change_subscribe()`). Since the configuration change was already processed in the application, the notification received from sysrepo is redundant and could be avoided. With that said, is there a way to ignore configuration changes that were performed by the own application?

Thanks,
Renato.

**Comment by michalvasko** [comment]
Hi Renato,
your best bet is to somehow redesign your application so that it does not need to do this. If it was possible to change configuration without the callbacks being called, it would go against the whole principle of sysrepo. What if there are other applications subscribed to the nodes you want to silently change?

Regards,
Michal

**Comment by rwestphal** [comment]
> What if there are other applications subscribed to the nodes you want to silently change?

My idea is that sysrepo would skip only the process that originated the configuration change when sending the notifications to the subscribers. Other subscribing applications would still be notified, except the one that commited the changes.

I'm aware this is a corner-case scenario so please feel free to ignore this issue.

> If it was possible to change configuration without the callbacks being called, it would go against the whole principle of sysrepo.

Yes, I know what I'm doing sounds weird but I need to keep our "legacy" CLI for backward compatibility. I'm working on a new northbound architecture for the FRR routing stack and our goal is to support both sysrepo and confd integration through the mechanism of plugins. However we have the requirement that it should also be possible to run FRR without any of these plugins. In any case the plan is to use _libyang_ to manage the configuration of FRR. The idea is that, regardless of what's being used (e.g. sysrepo, confd, legacy CLI), the same CRUD callbacks should be called to perform the required configuration changes.

I'll close this issue since I can workaround this problem in the application side.
