### ISSUE TITLE
How to use leaf-ref to state info in notifications?

### ISSUE THREAD

**Issue by igortern** [sysrepo/sysrepo#1068]
There are standard YANG models that use leaf-ref to state data in notifications. For example, ietf-hardware.yang defines notification hardware-state-oper-enabled which refers to 
```yang
    leaf name {
      type leafref {
        path "/hardware-state/component/name";
      }
    }
    leaf admin-state {
      type leafref {
        path "/hardware-state/component/state/admin-state";
      }
```
etc.

The question is how to generate such notification. 
Attempt to send hardware-state-oper-enabled notification with leafs "name" and "admin-state" produces the following logs
```
[ERR] (dm_ly_log_cb:1288) libyang error: Invalid value "/ietf-hardware:hardware-state/component[name='xpon-olt']/state/admin-state" in "admin-state" element.
[ERR] (dm_ly_log_cb:1288) libyang error: Invalid value "/ietf-hardware:hardware-state/component[name='xpon-olt']/state/admin-state" in "admin-state" element.
[ERR] (dm_ly_log_cb:1288) libyang error: Failed to create node "admin-state" as a child of "hardware-state-oper-enabled".
[ERR] (dm_sr_val_node_to_ly_datatree:5864) Unable to add new data tree node '/ietf-hardware:hardware-state-oper-enabled/admin-state': Failed to create node "admin-state" as a child of "hardware-state-oper-enabled"..
[ERR] (dm_validate_procedure:6242) Error by converting sysrepo values/trees to libyang data tree.
[ERR] (rp_event_notif_req_process:3057) Validation of an event notification (/ietf-hardware:hardware-state-oper-enabled) message failed.
```
Tested with sysrepo
sysrepod - sysrepo daemon, version 0.7.3
netopeer2-server 0.4.13
yanglint 0.14.50

I guess there should be a way to let sysrepo know the relevant state data, so that it can recognize the leaf-refs, but couldn't find how to do it.

Could you please advice?

Thanks a lot in advance.

Igor Ternovsky

Could you please advice how to pass the state info to sysrepo prior t

**Comment by michalvasko** [comment]
Hi Igor,
based on the error message, I would say your value really is wrong. You are not supposed to put the path into the value, the path is already in the schema. You should put the actual `admin-state` value of the referenced leaf. Try that and get back to us.

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,

Thank you for quick reply. Setting references to the actual values of the references leafs doesn't work either (that't actually was the initial implementation). The log in this case is

[ERR] (dm_ly_log_cb:1288) libyang error: Leafref "/hardware-state/component/name" of value "xpon-olt" points to a non-existing leaf.
[ERR] (dm_ly_log_cb:1288) libyang error: Leafref "/hardware-state/component/state/admin-state" of value "unlocked" points to a non-existing leaf.
[ERR] (dm_validate_procedure_content:6117) hardware-state-oper-enabled content validation failed: Leafref "/hardware-state/component/state/admin-state" of value "unlocked" points to a non-existing leaf.
[ERR] (dm_validate_procedure:6247) Procedure validation failed.
[ERR] (rp_event_notif_req_process:3057) Validation of an event notification (/ietf-hardware:hardware-state-oper-enabled) message failed.

Regards,
Igor

**Comment by michalvasko** [comment]
Hi Igor,
okay, now the error makes sense. So, what *sysrepo* branch are you using? Also, have you subscribed to providing this particular state data and do they include the node `/hardware-state/component/name` with value `xpon-olt`?

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,
- I'm using release sysrepo-0.7.3. Please let me know if you want me to try with some other branch.
- Subscribed to path "/ietf-hardware:hardware-state/component". Below is partial output of netopeer2-cli/GET"
<hardware-state xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware">
  <component>
    <name>xpon-olt</name>
    <class xmlns:ianahw="urn:ietf:params:xml:ns:yang:iana-hardware">ianahw:chassis</class>
    <state>
      <admin-state>unlocked</admin-state>
      <oper-state>enabled</oper-state>
    </state>
  </component>
- Note the the full syrepo log includes also some warnings. Don't know if they are related. Full log is below.
WRN] (cm_subscr_conn_create:1408) Unable to connect to subscriber socket=/tmp/sysrepo-subscriptions/ietf-netconf-notifications/31432.htFL1y.sock: No such file or directory
[WRN] (cm_subscr_conn_create:1408) Unable to connect to subscriber socket=/tmp/sysrepo-subscriptions/ietf-netconf-notifications/31432.htFL1y.sock: No such file or directory
[ERR] (dm_ly_log_cb:1288) libyang error: Leafref "/hardware-state/component/name" of value "xpon-olt" points to a non-existing leaf.
[ERR] (dm_ly_log_cb:1288) libyang error: Leafref "/hardware-state/component/state/admin-state" of value "unlocked" points to a non-existing leaf.
[ERR] (dm_validate_procedure_content:6117) hardware-state-oper-enabled content validation failed: Leafref "/hardware-state/component/state/admin-state" of value "unlocked" points to a non-existing leaf.
[ERR] (dm_validate_procedure:6247) Procedure validation failed.
[ERR] (rp_event_notif_req_process:3057) Validation of an event notification (/ietf-hardware:hardware-state-oper-enabled) message failed.

Thanks
-Igor

**Comment by igortern** [comment]
﻿Hi Michal,



The previous reply ended up garbled. Trying again

   - I'm using release sysrepo-0.7.3. Please let me know if you want me to
   try with some other branch.
   - Subscribed to path "/ietf-hardware:hardware-state/component". Below is
   partial output of netopeer2-cli/GET"

<hardware-state xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware">

  <component>

    <name>xpon-olt</name>

    <class
xmlns:ianahw="urn:ietf:params:xml:ns:yang:iana-hardware">ianahw:chassis</class>

    <state>

      <admin-state>unlocked</admin-state>

      <oper-state>enabled</oper-state>

    </state>

  </component>



﻿Note the the full syrepo log includes also some warnings. Don't know if
they are related. Full log is below.



WRN] (cm_subscr_conn_create:1408) Unable to connect to subscriber
socket=/tmp/sysrepo-subscriptions/ietf-netconf-notifications/31432.htFL1y.sock:
No such file or directory

[WRN] (cm_subscr_conn_create:1408) Unable to connect to subscriber
socket=/tmp/sysrepo-subscriptions/ietf-netconf-notifications/31432.htFL1y.sock:
No such file or directory

[ERR] (dm_ly_log_cb:1288) libyang error: Leafref
"/hardware-state/component/name" of value "xpon-olt" points to a
non-existing leaf.

[ERR] (dm_ly_log_cb:1288) libyang error: Leafref
"/hardware-state/component/state/admin-state" of value "unlocked" points to
a non-existing leaf.

[ERR] (dm_validate_procedure_content:6117) hardware-state-oper-enabled
content validation failed: Leafref
"/hardware-state/component/state/admin-state" of value "unlocked" points to
a non-existing leaf.

[ERR] (dm_validate_procedure:6247) Procedure validation failed.

[ERR] (rp_event_notif_req_process:3057) Validation of an event notification
(/ietf-hardware:hardware-state-oper-enabled) message failed.



Thanks

-Igor



*From:* Michal Vasko [mailto:notifications@github.com]
*Sent:* Saturday, March 3, 2018 12:21 AM
*To:* sysrepo/sysrepo
*Cc:* Igor Ternovsky; Author
*Subject:* Re: [sysrepo/sysrepo] How to use leaf-ref to state info in
notifications? (#1068)



Hi Igor,
okay, now the error makes sense. So, what *sysrepo* branch are you using?
Also, have you subscribed to providing this particular state data and do
they include the node /hardware-state/component/name with value xpon-olt?

Regards,
Michal

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sysrepo/sysrepo/issues/1068#issuecomment-369918936>,
or mute
the thread

**Comment by michalvasko** [comment]
Hi Igor,
just letting you know that this use-case really is not covered at all so it will take some time to fix.

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,



Thank you for letting me know. I’m happy to be a beta tester when you get
to implementing this feature.



Regards,

Igor



*From:* Michal Vasko [mailto:notifications@github.com]
*Sent:* Tuesday, March 6, 2018 1:50 AM
*To:* sysrepo/sysrepo
*Cc:* Igor Ternovsky; Author
*Subject:* Re: [sysrepo/sysrepo] How to use leaf-ref to state info in
notifications? (#1068)



Hi Igor,
just letting you know that this use-case really is not covered at all so it
will take some time to fix.

Regards,
Michal

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sysrepo/sysrepo/issues/1068#issuecomment-370442946>,
or mute
the thread
