### ISSUE TITLE
"validation of ops with state data dependencies" causes unexpected ops callbacks

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#1074]
Commit 65146ae4 triggers retrieval of all ops data when I emit a notification. That's wrong, because the ops callbacks perform expensive HW access on our devices.

Here's how [our model](https://github.com/jktjkt/czechlight-yang-models/blob/master/czechlight-roadm-v2.yang) looks like:
```
module: czechlight-roadm-v2
  +--rw roadm
     +--rw channel-plan
     |  +--rw channel* [center-frequency]
     |     +--rw center-frequency          decimal64
     |     +--rw channel-width             decimal64
     |     +--ro approximate-wavelength    decimal64
     +--rw configuration
     |  +--rw channel* [center-frequency]
     |     +--rw center-frequency    -> ../../../channel-plan/channel/center-frequency
     |     +--rw mode                pass-mode
     |     +--rw voa-attenuation     attenuation
     |     +--rw description?        string
     |     +--rw min-level-input!
     |        +--rw critical-level         measured-power
     |        +--rw critical-hysteresis?   power-hysteresis <1.0>
     +--ro optical-power
     |  +--ro channel* [center-frequency]
     |     +--ro center-frequency     -> ../../../channel-plan/channel/center-frequency
     |     +--ro input                measured-power
     |     +--ro drop                 measured-power
     |     +--ro output               measured-power
     |     +--ro input-signal-lost    boolean
     +--ro aggregate-power
        +--ro input     measured-power
        +--ro output    measured-power

  notifications:
    +---n input-signal-lost
    |  +--ro center-frequency    -> /roadm/channel-plan/channel/center-frequency
    +---n input-signal-restored
       +--ro center-frequency    -> /roadm/channel-plan/channel/center-frequency
```
When we emit a `/czechlight-roadm-v2:input-signal-lost` notification, sysrepo calls our callbacks for retrieving some operational data even though no ops data are actually referenced from the notification.

We cannot afford that because some of the ops callbacks retrieve their data by talking directly to a custom HW, and this HW takes several seconds to respond. Doing that completely destroys latency of notifications for me. Previously, I was happy to get a NETCONF-level response time between 300 and 600ms, for example (HW event -> NETCONF notification -> NETCONF client responding with an edit-config -> HW action).

Commit a736b09d appears to work as expected.

**Comment by michalvasko** [comment]
Hi Jan,
yeah, this was expected because sysrepo does not differentiate between configuration data dependencies and state data dependencies so both are retrieved now to be sure the required data is available.

There are several levels of optimization possible, but I guess just distinguishing between state and configuration data will be enough for now and should solve your problem.

Regards,
Michal

**Comment by jktjkt** [comment]
Yes, that's essentially how sysrepo behaved prior to 65146ae, and that has worked well for us.

**Comment by michalvasko** [comment]
Could you please try the pull request? You will also need to update *libyang*, thanks.

**Comment by jktjkt** [comment]
Yup, it restores the original behavior for me. Thanks.
