### ISSUE TITLE
module->op_data_subtrees contains config (rw) nodes for bbf-vdsl module.

### ISSUE THREAD

**Issue by darshana-jk** [sysrepo/sysrepo#1086]
### Things you may try first
(put "x" in "[]" if you already tried following)
* [X] Did you check if this is a duplicate issue?
* [X] Did you test it on the latest sysrepo devel branch?

### Description
Sysrepo rp_dt_xpath_requests_state_data() try to validate xpaths leading to config (rw) nodes as state data providers and fails with "Unable to find schema node for /bbf-vdsl:vdsl/quality/re-initialization-policy-profile/... (it may be disabled)" when the above nodes are rw yang leafs.
 
### Steps to Reproduce
1. Build the latest packages (Disable sysrepo examples build).
2. Use the [data.tar.gz](https://github.com/sysrepo/sysrepo/files/1832412/data.tar.gz), run the load-data.sh to install yangs and startup data.
3. start sysrepod, netopeer2-server
4. Connect to  netopeer2-server using netopeer2-cli
5 run a full get command.
6.Result:
```
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="6">
  <rpc-error>
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-message xml:lang="en">np2srv_sr_get_items_iter failed (sysrepo: Request contains unknown element).</error-message>
  </rpc-error>
</rpc-reply>
```
**Expected behavior:**
 The get shouldn't atleast fail.

**Actual behavior:**
See step 6.

### Versions
```
Git repo libyang
commit 7e5d4b684f69745af6be620cda051e432d8bd2a7
Author: PavolVican <xvican01@stud.fit.vutbr.cz>
Date:   Tue Mar 20 17:32:43 2018 +0100

    VERSION bump to version 0.15.67
Git repo libnetconf2
commit 323dff2aad2ab446d4002448575de1fbbc35a5d6
Author: Radek Krejci <rkrejci@cesnet.cz>
Date:   Tue Mar 20 15:37:18 2018 +0100

    VERSION bump version to 0.11.22
Git repo sysrepo
commit c5e7744fafc46d538799b31c0e21c0a34cbf5036
Merge: 9daa31f 3ba1104
Author: Michal Vasko <mvasko@cesnet.cz>
Date:   Mon Mar 19 10:48:30 2018 +0100

    Merge pull request #1084 from michalvasko/devel
    
    Added libSysrepo-cpp.pc.in for pkg-config
Git repo Netopeer2
commit 19f8347a902514a3d5154c76397b111652017cb5
Author: Michal Vasko <mvasko@cesnet.cz>
Date:   Fri Mar 9 15:41:36 2018 +0100

    cli VERSION bump to version 2.0.43

```
### Debug info
The get items request running datastore, for xpath: /bbf-vdsl:*// comes in to sysrepo, and passed to ```rp_dt_xpath_requests_state_data()```
Here, the 
/bbf-vdsl:vdsl/quality/re-initialization-policy-profile/downstream/reinit-time-threshold
/bbf-vdsl:vdsl/quality/re-initialization-policy-profile/upstream/reinit-time-threshold
Nodes are identified as state data nodes - but they are actually read/write ones. The ```rp_dt_validate_node_xpath()``` is called for each of above xpaths, it returns error. This makes the `rc` variable to have an error value when exiting the function ```rp_dt_xpath_requests_state_data()``` causing the failure. I think the root cause here is the above two (this only happens for the above two xpaths out of so many other xpaths in bbf-vdsl module) xpaths are wrongly marked as state data. 

```
[INF] (rp_dt_get_values_wrapper_with_opts:1346) Get items request running datastore, xpath: /bbf-vdsl:*//., offset: 0, limit: 100
[DBG] (dm_get_data_info_internal:2689) Module bbf-vdsl already loaded
[ERR] (rp_dt_xpath_requests_state_data:692) ------------- xpath '/bbf-vdsl:*//.'-----------------
[ERR] (rp_dt_xpath_requests_state_data:732) 	subtree node xpath '/bbf-vdsl:vdsl/quality/re-initialization-policy-profile/downstream/reinit-time-threshold'
[WRN] (rp_dt_xpath_requests_state_data:736) Unable to find schema node for /bbf-vdsl:vdsl/quality/re-initialization-policy-profile/downstream/reinit-time-threshold (it may be disabled)
[ERR] (rp_dt_xpath_requests_state_data:732) 	subtree node xpath '/bbf-vdsl:vdsl/quality/re-initialization-policy-profile/upstream/reinit-time-threshold'
[WRN] (rp_dt_xpath_requests_state_data:736) Unable to find schema node for /bbf-vdsl:vdsl/quality/re-initialization-policy-profile/upstream/reinit-time-threshold (it may be disabled)
[DBG] (rp_dt_xpath_requests_state_data:767) 0 subtrees of state data will be attempted to load in order to resolve /bbf-vdsl:*//.
[ERR] (rp_dt_prepare_data:1226) rp_dt_xpath_requests_state_data failed
[ERR] (rp_dt_get_values_wrapper_with_opts:1359) rp_dt_prepare_data failed
[ERR] (rp_get_items_req_process:830) Get items failed for '/bbf-vdsl:*//.', session id=694872073.
[DBG] (sr_cbuff_enqueue:516) Circular buffer enqueue to position=12, current count=1.
[DBG] (rp_worker_thread_execute:3808) Thread id=140019592570624 will wait.
[DBG] (cm_msg_enqueue_cb:1791) New message enqueued into CM message queue.
[DBG] (sr_cbuff_dequeue:532) Circular buffer dequeue, new buffer head=13, count=0.
[DBG] (cm_conn_out_buff_flush:508) Sending 24 bytes of data.
[DBG] (cm_conn_out_buff_flush:514) 24 bytes of data sent.

```

Thanks!
Darshana.

**Comment by michalvasko** [comment]
Hi Darshana,
sorry about this, the situation is handled correctly except the return value `rc` was not being cleared, so I added that in the pull request.

Regards,
Michal

**Comment by darshana-jk** [comment]
Hi Michal,

Thanks for the fix. This will work for my case.
I'm still wondering though, how did the xpaths
```
/bbf-vdsl:vdsl/quality/re-initialization-policy-profile/downstream/reinit-time-threshold
/bbf-vdsl:vdsl/quality/re-initialization-policy-profile/upstream/reinit-time-threshold
```
ended up in ```module->op_data_subtrees```

Regards,
Darshana.

**Comment by michalvasko** [comment]
Well, because they are state data subtrees :) Look at the tree output, if using interactive `yanglint`, do not forget to enable the feature `re-initialization-policy`.

Regards,
Michal

**Comment by darshana-jk** [comment]
Hi Michal,

Sorry, probably I'm missing something.
If you see : [bbf-vdsl-full.tree](https://github.com/BroadbandForum/yang/blob/master/standard/interface/docs/bbf-vdsl-full.tree)

```
       |  +--rw re-initialization-policy-profile* [name] {re-initialization-policy}?
       |  |  +--rw name          bbf-yang:string-ascii64
       |  |  +--rw downstream
       |  |  |  +--rw ripolicy?                uint8
       **|  |  |  +--rw reinit-time-threshold?   uint8**
       |  |  +--rw upstream
       |  |     +--rw ripolicy?                uint8
       **|  |     +--rw reinit-time-threshold?   uint8**
```
Being rw parameter means it should come from a running data store, not from a data provider. I don't have re-initialization-policy enabled in my repository so this tree is not effective.

**Comment by michalvasko** [comment]
Just generate the tree output for the models you sent me or simply look into `bbf-vdsl-re-initialization-policy-profile-body.yang` line `126`. They have not updated their tree output.

Regards,
Michal

**Comment by darshana-jk** [comment]
Ok. Sorry about the confusion.
Thanks.
Darshana.
