### ISSUE TITLE
Not able to configure the attributes inside 'choice'

### ISSUE THREAD

**Issue by hari-at-git** [sysrepo/sysrepo#1094]
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description
I have imported the the attached yang module (ietf-access-control-list@2018-03-03.txt) in sysrepo.
When I tried to configure the <destination-ipv4-network> and <source-ipv4-network> with below xml content , sysrepo does not configure those attributes

**Yang file:**
[ietf-access-control-list@2018-03-03.txt](https://github.com/sysrepo/sysrepo/files/1867935/ietf-access-control-list.2018-03-03.txt)

Command used: 
 **sysrepocfg --import=myconf.xml --datastore=running ietf-access-control-list**

**XML file content :**
[config.txt](https://github.com/sysrepo/sysrepo/files/1867932/config.txt)

**Output of application:**

application does not display ip addresses  that were configured using xml file.

**./application_changes_example ietf-access-control-list**

/ietf-access-control-list:access-lists/attachment-points (container)
/ietf-access-control-list:access-lists/acl[name='sample-ipv4-acl'] (list instance)
/ietf-access-control-list:access-lists/acl[name='sample-ipv4-acl']/name = sample-ipv4-acl
/ietf-access-control-list:access-lists/acl[name='sample-ipv4-acl']/aces (container)
/ietf-access-control-list:access-lists/acl[name='sample-ipv4-acl']/aces/ace[name='rule1'] (list instance)
/ietf-access-control-list:access-lists/acl[name='sample-ipv4-acl']/aces/ace[name='rule1']/name = rule1
/ietf-access-control-list:access-lists/acl[name='sample-ipv4-acl']/aces/ace[name='rule1']/actions (container)
/ietf-access-control-list:access-lists/acl[name='sample-ipv4-acl']/aces/ace[name='rule1']/actions/forwarding = drop
/ietf-access-control-list:access-lists/acl[name='sample-ipv4-acl']/aces/ace[name='rule1']/actions/logging = log-none [default]
/ietf-access-control-list:access-lists/acl[name='sample-ipv4-acl']/aces/ace[name='rule1']/matches (container)

**Output of sysrepocfg --editor:**

Even the attributes are missing in the datastore

sysrepocfg --editor=vim  ietf-access-control-list

output attached:
[config_output.txt](https://github.com/sysrepo/sysrepo/files/1867934/config_output.txt)

### Steps to Reproduce
1. To Install schema into sysrepo
sysrepoctl -i --yang  "ietf-packet-fields@2018-03-03.yang"

2. To subscribe to a modules
./application_changes_example <module name>

3. To import modules config
sysrepocfg --import=****.xml --datastore=startup ietf-access-control-list

4. To edit config
sysrepocfg --editor=vim  ietf-access-control-list

**Expected behavior:**
<destination-ipv4-network> and <source-ipv4-network> to be configured with the data specified in xml file

**Actual behavior:**
<destination-ipv4-network> and <source-ipv4-network> not configured with the data specified in xml file

Thanks!
Hari

**Comment by rkrejci** [comment]
Hi, there is a when condition on the `ipv4` container which requires `acl`'s `type` leaf to be set to identity `acl:ipv4-acl-type` (or a derived one). And since the `type` leaf is not present in your config.xml, the container may be removed due to this condition. Another possibility is that the container is also under `match-on`ipv4` if-feature, so you are supposed to have this schema feature enabled via sysrepo (check `sysrepoctl -l` output).
