### ISSUE TITLE
Request: ability to provide operational data using raw strings for all types

### ISSUE THREAD

**Issue by rwestphal** [sysrepo/sysrepo#1095]
I know this request is a bit odd but please let me explain why I'd want such a thing :)

I'm working on an open-source program that needs to be integrated with multiple northbound agents, including sysrepo (confd is the other one at the moment). The challenging thing is that sysrepo and confd store YANG data values using different representations (e.g. sysrepo stores enums using strings whereas confd stores enums using integers). I need to abstract these differences so I can write generic code in my program, which will allow users to choose whatever northbound plugin they want (sysrepo, confd, etc).

The way I found to solve this problem is to convert everything I receive from sysrepo/confd to raw strings and then parse these strings myself with the help of libyang. This is certainly not very efficient but it solves the problem in an elegant and reliable way. This however is only part of the problem. I also need to send YANG data values to sysrepo/confd to provide state data. With the current sysrepo API, I need to use `sr_new_values()` and fill the values using their sysrepo representation (e.g. for an `uint32` set `value.type` to `SR_INT32_T` and fill `value.uint32_val` manually).

Wouldn't it be possible to create a higher-level function that only accepts an XPath and a string value and then figures out things by itself (returning an error when necessary)? I'm thinking about something like `sr_val_set_from_string()`. I can workaround this problem by writing some conversion functions in my program, but if possible I'd prefer to have sysrepo to do this for me. I think other users could benefit from this API in the future as well, but I'll understand if providing such an API is not possible.

Note: I tried `sr_val_set_str_data()` but it only works for string types (bits, enum, string, etc).

Regards,
Renato.

**Comment by rkrejci** [comment]
I like the idea (but I'm not promising when it will be implemented).

**Comment by michalvasko** [comment]
*libyang* API solves this.
