### ISSUE TITLE
How to delete a node in leaf-list 

### ISSUE THREAD

**Issue by KingOfOplex** [sysrepo/sysrepo#1096]
The XML of leaf-list is like this:
[user-name] test1 [/user-name]
[user-name] test2 [/user-name]

I use sr_delete_item to delete the node "test2" with XPath /user-name[user-name='test2'].
But the sysrepo reports error as: No nodes to be deleted with strict option.
It seems that the XPath I use is something wrong. 
I wonder how to delete a node in leaf-list by specifying XPath.

**Comment by rkrejci** [comment]
Hi, try `/user-name[.='test2']`. Actually I would also expect that the namespace will be needed, so better `/modulename:user-name[.='test2']`.

**Comment by KingOfOplex** [comment]
It is OK.Thanks very much.
