### ISSUE TITLE
sysrepoctl crashing while module installation

### ISSUE THREAD

**Issue by Ravi-t** [sysrepo/sysrepo#1102]
I am trying to use nacm in my yang files, but while installing the sysrepoctl crashes.

My leaf node looks as below, all works fine if nacm line is removed but as soon as I add the nacm line the sysrepoctl crashes.

leaf mbuf_mempool_size {
                **nacm:default-deny-write;**
	    		type uint64;
		    	default 8192;
   		}	

[root@localhost yang_files]#sysrepoctl --install --yang=./node_moduleconfig.yang 
Installing a new module from file './node_moduleconfig.yang'...
[ERR] (srctl_ly_log_cb:500) libyang: Invalid keyword "nacm:default-deny-write".
[ERR] (srctl_ly_log_cb:500) libyang: Module "node_moduleconfig" parsing failed.
Segmentation fault (core dumped)

[root@localhost yang_files]# sysrepoctl --version
sysrepoctl - sysrepo control tool, version 0.7.3

[root@localhost yang_files]# sysrepoctl -l
Sysrepo schema directory: /root/NETCONF/sysrepo/build/repository/yang/
Sysrepo data directory:   /root/NETCONF/sysrepo/build/repository/data/
(Do not alter contents of these directories manually)

Module Name                   | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
example-module                |            | Installed   | root:root           | 666         |                               |
test-module                   |            | Installed   | root:root           | 666         |                               |
referenced-data               |            | Installed   | root:root           | 666         |                               |
small-module                  |            | Installed   | root:root           | 666         |                               |
info-module                   |            | Installed   |                     |             |                               |
module-a                      | 2016-02-10 | Installed   | root:root           | 666         |  sub-a-one sub-a-two          |
module-b                      | 2016-02-05 | Installed   | root:root           | 666         |                               |
module-a                      | 2016-02-02 | Imported    |                     |             |  sub-a-one sub-a-two          |
ietf-interfaces               | 2014-05-08 | Installed   | root:root           | 666         |                               |
iana-if-type                  | 2014-05-08 | Installed   |                     |             |                               |
ietf-ip                       | 2014-06-16 | Installed   |                     |             |                               |
state-module                  | 2016-07-01 | Installed   | root:root           | 666         |                               |
top-level-mandatory           |            | Installed   | root:root           | 666         |                               |
cross-module                  |            | Installed   | root:root           | 666         |                               |
turing-machine                | 2013-12-27 | Installed   | root:root           | 666         |                               |
ietf-netconf-notifications    | 2012-02-06 | Installed   | root:root           | 666         |                               |
ietf-netconf                  | 2011-06-01 | Imported    |                     |             |                               |
**ietf-netconf-acm              | 2012-02-22 | Imported    |                     |             |                               |**
nc-notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |
notifications                 | 2008-07-14 | Installed   | root:root           | 666         |                               |
servers                       |            | Installed   | root:root           | 666         |                               |
swig-test-cpp-changes         | 2017-03-09 | Installed   | root:root           | 666         |                               |
swig-test-cpp-operations      | 2017-03-09 | Installed   | root:root           | 666         |   

Please help to resolve the issue.
The basic requirement that I have here is to use ietf-netconf-acm models in my node yang models.

Thanks

**Comment by Ravi-t** [comment]
The crash is not happening if I change the ordering of statement as below:
leaf mbuf_mempool_size {
    type uint64;
    nacm:default-deny-write;
    default 8192;
}

although, its still not working
Getting below error

[root@localhost yang_files]# sysrepoctl --install --yang=./node_moduleconfig.yang 
Installing a new module from file './node_moduleconfig.yang'...
[ERR] (srctl_ly_log_cb:500) libyang: Invalid keyword "nacm:default-deny-write".
[ERR] (srctl_ly_log_cb:500) libyang: Module "node_moduleconfig" parsing failed.
Error: Unable to load the module by libyang.
Install operation failed.

**Comment by Ravi-t** [comment]
I also tried to import acm in my submodule but its failing, please let me know how to import ietf-netconf-acm module

[root@localhost yang_files]# sysrepoctl --install --yang=./node_moduleconfig.yang 
Installing a new module from file './node_moduleconfig.yang'...
[ERR] (srctl_ly_log_cb:500) libyang: Data model "ietf-netconf-acm" not found.
[ERR] (srctl_ly_log_cb:500) libyang: Importing "ietf-netconf-acm" module into "node_dpdkconfig" failed.
[ERR] (srctl_ly_log_cb:500) libyang: Submodule "node_dpdkconfig" parsing failed.
[ERR] (srctl_ly_log_cb:500) libyang: Invalid value "node_dpdkconfig" of "include".
[ERR] (srctl_ly_log_cb:500) libyang: Including "node_dpdkconfig" module into "node_moduleconfig" failed.
[ERR] (srctl_ly_log_cb:500) libyang: Module "node_moduleconfig" parsing failed.
Error: Unable to load the module by libyang.
Install operation failed.

**Comment by michalvasko** [comment]
Hi,
why did you close the issue, did you solve this problem?

Anyway, you tried to use `nacm:default-deny-write` in your module without importing `ietf-netconf-acm`? That could not have worked, obviously, but it should not cause `sysrepoctl` to crash, it did not in my case. What branch of *sysrepo* are you using? Having imported `ietf-netconf-acm`, it must also be accessible when installing your module `node_moduleconfig`. So, either put it next to it in the same directory or add another option for `sysrepoctl`, `-s` followed by the directory with the import modules or `-S` if all import modules are already installed.

Regards,
Michal

**Comment by Ravi-t** [comment]
Thanks for the information Michal.

I closed the issue because I was able to get around with it by reordering my statements, but I agree that sysrepoctl should never crash even if statements are given in wrong order. I did a git clone on March 26 and I believe that I cloned it from master branch.  

[root@localhost sysrepo]# sysrepod -v
sysrepod - sysrepo daemon, version 0.7.3

FYI, I have written a code generator to auto generate the C callback functions for all the leaf nodes and auto subscribe to any changes in running data stores, please let me know if I can publish that on git hub so that other people can also make use of it if needed. 

FYI, I am using NETCONF/SYSREPO for managing the configuration of my node, config wise all is working well, though I got a crash in NETCONF server and fixed it, now **I am focusing on restricting the access for configuration (read/writes) via NETCONF CLI to certain users only and that too for certain leaf nodes, can you please provide a reference or some example to manage access permissions, also are there any audit logs that are saved by sysrepo to figure out which client modified the configuration and at what time.**

**Comment by michalvasko** [comment]
Please use `devel` branch (of all the libraries and applications) and if you encounter an issues there, I will be happy to fix them, otherwise it can be a waste of time.

As for NACM, you should find all the required information in the RFC [here](https://tools.ietf.org/html/rfc6536). There are no logs like that but you can simply write a logger yourself. `sysrepo` generates `netconf-config-change` notifications (from `ietf-netconf-notifications`) which include all the information you need. Actually, these notifications are stored and always accessible with the `replay` feature so all the information should be there, just in a different format.

Regards,
Michal

**Comment by Ravi-t** [comment]
Hi Michal,

I used the devel branch and was able to reproduce the core, though this time it happened if I write an invalid keyword, instead of writing "default-deny-write", I wrote "deny-all-write"

[root@cloud yang_files]# sysrepoctl --install --yang=node_moduleconfig.yang -s /root/NETCONF/Netopeer2/modules/
Installing a new module from file 'node_moduleconfig.yang'...
[ERR] (srctl_ly_log_cb:506) libyang: Invalid keyword "nacm:deny-all-write".
[ERR] (srctl_ly_log_cb:506) libyang: Module "node_moduleconfig" parsing failed.
Segmentation fault (core dumped)

Regards,
Ravi

**Comment by michalvasko** [comment]
Hi Ravi,
I have just tried to load such model and it did not crash, just printed the error. Did you use current `devel`?

Regards,
Michal

**Comment by Ravi-t** [comment]
Hi Michal,

Yes, I am using the current devel branch. I cloned it 15 days back.

Regards,
Ravi
