### ISSUE TITLE
sysrepoctl crashing while compilation of sysrepo - issue is intermittent

### ISSUE THREAD

**Issue by Ravi-t** [sysrepo/sysrepo#1104]
[ 90%] Building CXX object swig/CMakeFiles/Sysrepo-cpp.dir/cpp/src/Internal.cpp.o
Linking CXX shared library libSysrepo-cpp.so
Installing a new module from file '/home/ravi/NETCONF/sysrepo/swig/cpp/tests/yang/swig-test-cpp-changes@2017-03-09.yang'...
Installing the YANG file to '/home/ravi/NETCONF/sysrepo/build/repository/yang/swig-test-cpp-changes@2017-03-09.yang'...
Installing data files for module 'swig-test-cpp-changes'...
[ERR] (sr_set_data_file_permissions:2306) Unable to execute chmod on '/tmp/sysrepo-subscriptions/swig-test-cpp-changes/': Operation not permitted.
[ERR] (srctl_update_socket_dir_permissions:398) Unable to set socket directory permissions for '/tmp/sysrepo-subscriptions/swig-test-cpp-changes/'.
Error: Unable to update socket directory permissions for module 'swig-test-cpp-changes'.
Installation of data files cancelled for module 'swig-test-cpp-changes', reverting...
**Deleted the data files for module 'swig-test-cpp-changes'.
/bin/sh: line 1: 74522 Segmentation fault      (core dumped) ../src/sysrepoctl --install --yang=/home/ravi/NETCONF/sysrepo/swig/cpp/tests/yang/swig-test-cpp-changes@2017-03-09.yang**
make[2]: *** [swig/libSysrepo-cpp.so.0.7.3] Error 139
make[1]: *** [swig/CMakeFiles/Sysrepo-cpp.dir/all] Error 2
make: *** [all] Error 2

**Comment by michalvasko** [comment]
Hi,
it seems you need to compile it on your system having `root` access, change permissions of your `/tmp` directory, or define `SUBSCRIPTIONS_SOCKET_DIR` to some path you have access to.

Regards,
Michal
