### ISSUE TITLE
sysrepoctl assertion failure while installing module with augmented empty container 

### ISSUE THREAD

**Issue by aweast** [sysrepo/sysrepo#1106]
### First items attempted
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?
* [x] Did you test it on the latest sysrepo devel branch and the latest libyang devel branch?

### Description
Installing a YANG module with sysrepoctl results in a failure due to an assertion if an otherwise empty container has children added  by augmentation.  The following YANG module exhibits the issue.

```YANG
module test-ds0 {
  namespace "urn:ietf:params:xml:ns:yang:ietf-interfaces:test-ds0";
  prefix ds0;

  import ietf-interfaces {
    prefix if;
  }

  augment "/if:interfaces-state/if:interface" {
      container foo {
          presence "This is a presence node";
          description
            "Container-specific state data.";
      }
  }

  augment "/if:interfaces-state/if:interface/foo" {
      leaf permit-foo-management {
          config false;
          type boolean;
          default "true";
          description
            "If true, permit foo management.";
      }
  }
}
```

The install command and output can be seen below.
```console
root@host:/# sysrepoctl --install --yang=/path/to/yang/models/ds0.yang --owner=root:root --permissions=666
Installing a new module from file 'models/test-ds0.yang'...
Installing the YANG file to '/opt/dev/sysrepo/cmake-build-debug/repository/yang/test-ds0.yang'...
Resolving dependency: 'test-ds0' imports 'ietf-interfaces'...
Installing the YANG file to '/opt/dev/sysrepo/cmake-build-debug/repository/yang/ietf-interfaces@2014-05-08.yang'...
sysrepoctl: /opt/dev/sysrepo/src/module_dependencies.c:1747: md_traverse_schema_tree: Assertion `!(child->nodetype & (LYS_CONTAINER | LYS_LIST)) || (intptr_t)child->priv & PRIV_OP_SUBTREE' failed.
Aborted (core dumped)
```

**Expected behavior:**
The module should install successfully.

**Actual behavior:**
Installing the module results in an assertion failure in  [module_dependencies.c#1747](https://github.com/sysrepo/sysrepo/blob/c4fc434f0640905a3b4e3378151d2c399fba945a/src/module_dependencies.c#L1747)

### Versions
Versions used to reproduce the bug:
Sysrepo version: sysrepod - sysrepo daemon, version 0.7.3
Sysrepoctl version: sysrepoctl - sysrepo control tool, version 0.7.3
libyang version: yanglint 0.15.92

### Additional information
This was introduced in the recent fix for issue [#1011](https://github.com/sysrepo/sysrepo/issues/1011 "find wrong op-data-subtree for augment module if the top augment node is config false"). The assertion occurs in [module_dependencies.c#1747](https://github.com/sysrepo/sysrepo/blob/c4fc434f0640905a3b4e3378151d2c399fba945a/src/module_dependencies.c#L1747).

**Comment by michalvasko** [comment]
Not relevant anymore.
