### ISSUE TITLE
Compilation Issue 

### ISSUE THREAD

**Issue by shubhtrix** [sysrepo/sysrepo#1108]
Greetings!!!

I'm trying to compile sysrepo, having error during compilation.... Please see the error below.. Please help on this ....
SYSTEM : Ubuntu 18.04 
REQUIREMETN FOR : Netopeer2 
STEPS FOLLOWED : 
Step 1. Cloned with git repository.
Step 2. mkdir build; cd build 
Step 3. cmake ../ (Everything worked up-to this point with python 3.5.6 and lua5.1-dev)
             No problem with make-file configuration.
Step 4. make (Not able to compile. Please have a look at given ERROR)

```
[ 90%] Linking CXX executable cpp_application_example
[ 90%] Built target cpp_application_example
[ 91%] Building CXX object swig/python3/CMakeFiles/_libsysrepoPython3.dir/libsysrepoPython3PYTHON_wrap.cxx.o
[ 92%] Linking CXX shared module _libsysrepoPython3.so
/usr/bin/x86_64-linux-gnu-ld: /usr/local/lib/libpython3.6m.a(ceval.o): relocation R_X86_64_PC32 against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC
/usr/bin/x86_64-linux-gnu-ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
swig/python3/CMakeFiles/_libsysrepoPython3.dir/build.make:110: recipe for target 'swig/python3/_libsysrepoPython3.so' failed
make[2]: *** [swig/python3/_libsysrepoPython3.so] Error 1
CMakeFiles/Makefile2:2446: recipe for target 'swig/python3/CMakeFiles/_libsysrepoPython3.dir/all' failed
make[1]: *** [swig/python3/CMakeFiles/_libsysrepoPython3.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```
So, i also tried with `cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS=-fPIC -DCMAKE_INSTALL_PREFIX:PATH=/usr ..`

Still the problem persists.... And after this I also tried with CMakeCache.txt and made changes to 
`CMAKE_CXX_FLAGS:STRING=-fPIC` but nothing happened..

Need help with the same. Thanks in advance.

Regards,
SHUBH

**Comment by michalvasko** [comment]
Hi Shubh,
that is quite a weird error. I have tried compiling python3 bindings on Ubuntu 16.04 and had no issues. Maybe try updating `swig`, what version are you using? I really don't know.

Regards,
Michal

**Comment by shubhtrix** [comment]
Hello @michalvasko 
Thanks for your reply, ya i tried some different variations of dependencies and it compiled on Ubuntu 18.04. don't remember all now.

But thanks a lot for your help and advice.
Have a great day!!!
