### ISSUE TITLE
sysrepo commit time increase

### ISSUE THREAD

**Issue by chunlovemail** [sysrepo/sysrepo#1110]
### Things you may try first
(put "x" in "[]" if you already tried following)
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description
Using sysrepo's test-module, create sr_loop_set_decimal64.c file. Then decimal64 type data is repeated write to test-module.startup.
The test results follows:
1. The commit execution time is about 50ms when the program starts running.
2. As the number of commit increases, the commit time also increases. At the time of commit to 1200, the commit time is 640ms.
3. When commit time reaches 640ms, will return to 100ms

### Steps to Reproduce
1. connect sysrepo
`sr_connect("test_module_app_1", SR_CONN_DEFAULT, &conn);`
2. start session with SR_DS_STARTUP
`sr_session_start(conn, SR_DS_STARTUP, SR_SESS_DEFAULT, &sess);`
3. write data to /test-module:main/dec64 repeatedly, then record the time of sr_set_item and sr_commit.
`while (true)  {

        gettimeofday(&tv1, NULL);
        value.type = SR_DECIMAL64_T;
        value.data.decimal64_val = f;
        rc = sr_set_item(sess, "/test-module:main/dec64", &value, SR_EDIT_DEFAULT);
        if (SR_ERR_OK != rc) {
            goto cleanup;
        }
        gettimeofday(&tv2, NULL);
        rc = sr_commit(sess);
        if (SR_ERR_OK != rc) {
            goto cleanup;
        }
        gettimeofday(&tv3, NULL);
        printf("Commit %.0f succ, sr_set_item: %ldms, commit: %ldms, total: %ldms\n", 
            f++, 
            tv2.tv_sec * 1000 + tv2.tv_usec/1000 - (tv1.tv_sec * 1000 + tv1.tv_usec/1000),
            tv3.tv_sec * 1000 + tv3.tv_usec/1000 - (tv2.tv_sec * 1000 + tv2.tv_usec/1000),
            tv3.tv_sec * 1000 + tv3.tv_usec/1000 - (tv1.tv_sec * 1000 + tv1.tv_usec/1000));
    }`

**Expected behavior:**
The execution time of sr_set_item function should be nearly the same.
The execution time of sr_commit function should be nearly the same.

**Actual behavior:**
1.As the number of commit increases, the execution time of sr_set_item increases, from 50ms to 670ms.
2.When the commit number increases to nearly 1235, the execution time of sr_set_item returns to 35ms.
The log is as shown below:
_Commit 1 succ, sr_set_item: 18ms, commit: 32ms, total: 50ms
Commit 2 succ, sr_set_item: 61ms, commit: 48ms, total: 109ms
Commit 3 succ, sr_set_item: 51ms, commit: 33ms, total: 84ms
Commit 4 succ, sr_set_item: 51ms, commit: 41ms, total: 92ms
Commit 5 succ, sr_set_item: 61ms, commit: 39ms, total: 100ms
...
Commit 1228 succ, sr_set_item: 622ms, commit: 45ms, total: 667ms
Commit 1229 succ, sr_set_item: 626ms, commit: 41ms, total: 667ms
Commit 1230 succ, sr_set_item: 633ms, commit: 34ms, total: 667ms
Commit 1231 succ, sr_set_item: 594ms, commit: 32ms, total: 626ms
Commit 1232 succ, sr_set_item: 610ms, commit: 32ms, total: 642ms
Commit 1233 succ, sr_set_item: 35ms, commit: 32ms, total: 67ms
Commit 1234 succ, sr_set_item: 35ms, commit: 32ms, total: 67ms
Commit 1235 succ, sr_set_item: 35ms, commit: 32ms, total: 67ms_

I  fell strange about the sr_set_item time:
1. Why it increases with the commit number?
2. Why it returns to 50ms when the commit number increase to 1232

### Versions
_sysrepod -v
sysrepod - sysrepo daemon, version 0.7.2
yanglint -v
yanglint 0.14.68_

### Attachments
[sr_loop_set_decimal64_startup.zip](https://github.com/sysrepo/sysrepo/files/1973560/sr_loop_set_decimal64_startup.zip)

Thanks!

**Comment by chunlovemail** [comment]
I had notice that the STORE_CONFIG_CHANGE_NOTIF in CMakeList.txt is set 1, so sysrepo will store notification in xml.  This slows down the commit process.
And the NOTIF_TIME_WINDOW  is 10, means that every 10 min, sysrepo will write notification information to a new file. Then the commit time returns to 50ms.

So i can set STORE_CONFIG_CHANGE_NOTIF to 0, then the store notification function is blocked.

**Comment by michalvasko** [comment]
Hi,
please disable these notification for now if you do not need them. We are planning to fix them later but there are currently other priorities, sorry. Similar request was made in #735, so closing this as a duplicate.

Regards,
Michal
