### ISSUE TITLE
Cannot configure identityrefs with derived identity in separate model under certain circumstances

### ISSUE THREAD

**Issue by alangefe** [sysrepo/sysrepo#1111]
### Description
The following model graph is used to exhibit the problem:

```
      +-------------+
      |             |
      | id-ref-base |          +------------------+
      |             |          |                  |
      +----+-----+--+          | id-def-extension |
           ^     ^             |                  |
           .     | Augment     +------+--------+--+
           .     |                    |        .
           .     |                    |        .
    Extend .     |                    |        .
           .     |            Import  |        . Extend
           .     |                    |        .
           .     |                    v        v
       +---+-----+--+   Import      +-+--------+--+
       |            +-------------->+             |
       | id-ref-aug |               | id-def-base |
       |            +<..............+             |
       +------------+    Extend     +-------------+
```

If the model installation order is:

 1. `id-ref-base`
 2. `id-ref-aug`
 3. `id-def-base`
 4. `id-def-extension`

then a dependency will be left out of the graph and the user will be unable to configure the identity defined in `id-def-extension`.

The source of the problem is that a consumer of an identity (i.e., a module with an identityref) only adds the source of that identity module as an extension to itself when that source is marked as 'implemented'. However, this causes that dependency to be lost, as it won't be regenerated when the source of the identity is later installed with sysrepoctl.

We've written a unit test that demonstrates the problem. See `set_item_id_ref()` in https://github.com/alangefe/sysrepo/commit/5577960d27dfb18d19c28c20fb64711bb76cb57c.

### Proposed solution

We've implemented a proposed solution in the same commit referenced above. Our solution is to allow identityrefs to be added as extend dependencies even if the source module hasn't yet been implemented. The identity can then be used once the source of the identity is installed.

An alternative implementation to this could be to regenerate the identityref module when the identity source module is installed. However this seems like it would introduce quite a bit more complexity into the installation process.

**Comment by michalvasko** [comment]
Hi,
thanks for the tests but I do not think we can merge your implemented solution. If the dependency is added, the model with the identity is loaded into *libyang* context of the other models as implemented meaning the identity can be used in data. That is contrary to YANG specification.

So, we will have to go with your other proposed solution even though it adds some complexity as the whole schema tree must be traversed again. Will you please create a pull request only with the new tests? Meanwhile, I will fix the problem. Thanks.

Regards,
Michal

**Comment by michalvasko** [comment]
So, I have explored the problem a bit and have come up with possible solution but I would like your input on whether you think it will cover all the cases or would even work. Pseudocode:

```
if (module implemented from imported) && (has identity definition) {
  go through module->inv_deps imports and call md_traverse_schema_tree() for each
}
```
To be more efficient, it is useless to perform all that is in `md_traverse_schema_tree()` so I would limit it to looking for `identityrefs`. Sounds fine?

Regards,
Michal

**Comment by michalvasko** [comment]
Hi Andrew,
the issue should now be resolved, the code was actually there, it needed but some fine-tuning to cover additional cases.

Regards,
Michal
