### ISSUE TITLE
Is there any way to encrypt node value in callback funtion of sr_XXX_change_subscribe?

### ISSUE THREAD

**Issue by guangjung** [sysrepo/sysrepo#1115]
### Description
Is there any way to encrypt node value in callback funtion of sr_XXX_change_subscribe？
### Steps to Reproduce
For example,  how to encrypt /ietf-system:system/authentication/user[name="TestUser"]/password?
1. excute the following edit-config by netopeer2-cli. Note: password node is in clear-text
```xml
<nc:edit-config>
  <nc:target><nc:running/></nc:target>
  <nc:config>
    <system xmlns="urn:ietf:params:xml:ns:yang:ietf-system">
      <authentication>
        <user>
          <name>TestUser</name>
          <password>$0$welcome</password>
        </user>
      </authentication>
    </system>
  </nc:config>
</nc:edit-config>
```
2.  sr_module_change_subscribe in server will receive changed **password** node in clear-text. How to replace it with encrypted values (ex,sha256, md5, sha512) and save it to the running datastore /etc/sysrepo/data/ietf-system.running.  

**Expected behavior:**
Hope that there is a way to replace the node value with new value before commiting to running datastore and save it to running datastore.

Node: password node is  encrypted by sha256.
```xml
<system xmlns="urn:ietf:params:xml:ns:yang:ietf-system">
  <radius>
    <options>
      <timeout>5</timeout>
      <attempts>2</attempts>
    </options>
  </radius>
  <authentication>
    <user>
      <name>TestUser</name>
      <password>$5$salt123456789012$Hs7VVd/6OVTxURkAHK0C62q7vQwBnGFzTzphMKrmhb0</password>
    </user>
  </authentication>
  <contact>xxx@xxx.com</contact>
  <hostname>hostname</hostname>
  <location>us</location>
</system>
```

Thanks!

**Comment by jwwilcox** [comment]
That does mean it's not currently possible to implement the semantics required by the [iana-crypt-hash](https://tools.ietf.org/html/rfc7317#section-5) module:

```
          The '$0$' prefix signals that the value is clear text.  When
          such a value is received by the server, a hash value is
          calculated, and the string '$<id>$<salt>$' or
          $<id>$<parameter>$<salt>$ is prepended to the result.  This
          value is stored in the configuration data store.
```

Also most security guidelines strongly recommend against storing plain text passwords unless it's absolutely required.

**Comment by michalvasko** [comment]
Yes, I do not think it is possible. The security guidelines are, of course, correct but running configuration often contains sensitive information and so only `root` should have access to some parts of it. So it all comes down to `root` being able to see the password for certain short period of time, which I think is acceptable.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi,
this is actually already possible but the solution is not that elegant. Look [here](http://www.sysrepo.org/static/doc/html/subscribtions.html#callbacks) for details on how to implement it.

Regards,
Michal
