### ISSUE TITLE
sysrepoctl error while installing module with a submodule containing a leafref

### ISSUE THREAD

**Issue by aweast** [sysrepo/sysrepo#1116]
### Things you may try first
(put "x" in "[]" if you already tried following)
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description
Installing a yang model with submodules can fail if one of the submodules contains a LeafRef referring to an external module that is not yet installed. The ordering of include statements can cause the installation to fail or succeed.

In the attached modules, module `mws-main-module` includes two submodules `mws-main-submodule1` and `mws-main-submodule2`. Both `mws-main-submodule1` and `mws-main-submodule2` augment `/mws-main-module:main`. `mws-main-submodule2` imports `mws-other-module` and uses a leafref type that references `/mws-other-module:foo/mws-other-module:bar`. If `mws-main-module` includes `mws-main-submodule1` before `mws-main-submodule2`, installation will fail. On the other hand, if `mws-main-module` includes `mws-main-submodule2` before `mws-main-submodule1`, or model `mws-other-module` is loaded beforehand, installation will succeed.

```
      +--------------+    Include    +--------------+
      |              |-------------->|              |
      |  mws-main-   |               |  mws-main-   |
      |   module     |<--------------|  submodule1  |
      +--------------+    Augment    +--------------+
          |      ^
 Include  |      |  Augment
          v      |
      +--------------+    Import     +--------------+
      |              |-------------->|              |
      |  mws-main-   |               |  mws-other-  |
      |  submodule2  |-------------->|    module    |
      +--------------+    Leafref    +--------------+
                           XPATH
```

The install command and output can be seen below:

```console
# sysrepoctl --install --yang mws-main-module.yang 
Installing a new module from file 'mws-main-module.yang'...
Installing the YANG file to '/path/to/yang/repo/repository/yang/mws-main-module.yang'...
Resolving dependency: 'mws-main-module' includes 'mws-main-submodule1'...
Installing the YANG file to '/path/to/yang/repo/repository/yang/mws-main-submodule1.yang'...
Resolving dependency: 'mws-main-module' includes 'mws-main-submodule2'...
Installing the YANG file to '/path/to/yang/repo/repository/yang/mws-main-submodule2.yang'...
Resolving dependency: 'mws-main-submodule2' imports 'mws-other-module'...
Installing the YANG file to '/path/to/yang/repo/repository/yang/mws-other-module.yang'...
[ERR] (md_get_module_info:1337) Module 'mws-other-module@<latest>' is not present in the dependency graph.
[ERR] (md_collect_data_dependencies:1389) Failed to get the module schema based on the prefix.
Error: Unable to insert the module into the dependency graph.
Reverting the install operation...
Deleted the schema file '/path/to/yang/repo/repository/yang/mws-main-module.yang'.
Install operation failed.
```

However, if the two include statements in `mws-main-module` are reversed, the command succeeds:

```console
# sysrepoctl --install --yang mws-main-module.yang 
Installing a new module from file 'mws-main-module.yang'...
Installing the YANG file to '/path/to/yang/repo/repository/yang/mws-main-module.yang'...
Resolving dependency: 'mws-main-module' includes 'mws-main-submodule2'...
Installing the YANG file to '/path/to/yang/repo/repository/yang/mws-main-submodule2.yang'...
Resolving dependency: 'mws-main-submodule2' imports 'mws-other-module'...
Installing the YANG file to '/path/to/yang/repo/repository/yang/mws-other-module.yang'...
Resolving dependency: 'mws-main-module' includes 'mws-main-submodule1'...
Installing the YANG file to '/path/to/yang/repo/repository/yang/mws-main-submodule1.yang'...
Installing data files for module 'mws-main-module'...
Notifying sysrepo about the change...
Install operation completed successfully.
```

**Expected behavior:**
The module should install successfully regardless of the order of include statements.

**Actual behavior:**
The module cannot be installed because the external module cannot be added to the dependency graph when include statements are used in a specific order.

### Versions
Please provide versions for software needed to reproduce the bug:
Sysrepo version: `sysrepod - sysrepo daemon, version 0.7.3`
libyang version: `yanglint 0.15.92`

### Attachments
Attached are four basic yang models that demonstrate the problem.

[yang_models.zip](https://github.com/sysrepo/sysrepo/files/1984507/yang_models.zip)

**Comment by michalvasko** [comment]
Hi,
referenced pull request should fix this.

Regards,
Michal
