### ISSUE TITLE
datastore snapshots

### ISSUE THREAD

**Issue by rkrejci** [sysrepo/sysrepo#1117]
* [x] Did you check if this is a duplicate issue?

### Description
Time to time the configuration content can get into a weird state when it is valid but not working and the most simple way to fix it is to revert it back to some working state. I know that there is `startup` datastore that could work this way. However, for better granularity, it would be great to ba able to create (running) datastore snapshots.

In some case, sysrepo already splits the complex change of data into a list of transactions which can be reverted. Instead of having such a list only for changes between `sr_commit()`, it could be stored externally also for chnages between somehow spacified states of the datastore - snapshots. When needed, the second state (the current) could be reverted back to the previous (specified) snapshot.

**Comment by michalvasko** [comment]
Such functionality should probably be left for the specific datastore, once custom ones will be supported.
