### ISSUE TITLE
sysrepocfg error using config false in a YANG file

### ISSUE THREAD

**Issue by lrodrin** [sysrepo/sysrepo#1127]
Hi,

I have a YANG file installed in sysrepo that contains:

```
namespace "urn:node-topology";

container node {
    config false;
    uses node;
  } 
```

How put the startup/running configuration using sysrepocfg? 

Without config false, the command  sysrepocfg --import=myconfig.xml node-topology works. But, with config false doesn't work. 

A simple myconfig.xml:

```
<node xmlns="urn:node-topology">
    <node-id>127.0.0.1</node-id>
    <port>
        <port-id>0</port-id>
    </port>
</node>
```

Thank you,
Laura.

**Comment by michalvasko** [comment]
Hi Laura,
then it works as it should. You see, **configuration** (config `true`) data are stored in a datastore and altered based on client requests. However, **state** (config `false`) data are not stored anywhere. To be always up-to-date, they are requested from applications whenever a client ask for them. So, you need to subscribe for providing this data (using `sr_dp_get_items_subscribe()`) instead of setting them permanently.

Regards,
Michal

**Comment by lrodrin** [comment]
Thank you so much Michal! 

I did not remember the oper_data_example.c.

Regards,
Laura.

**Comment by BoyuanYan** [comment]
Hi Michal @michalvasko,
    If there is a boolean value that indicates whether a specific component exists in a node, we are willing to set it as "config false". Because this state is operational and shouldn't be changed by the client. In this case, how could I insert such a value into sysrepocfg datastore?

Thanks,
Boyuan

**Comment by michalvasko** [comment]
Hi Boyuan,
I believe the answer is already in this thread, but to briefly repeat, *state* data are not permanently stored in the datastore, they are always requested from a client that subscribed to providing them using `sr_dp_get_items_subscribe()`.

Regards,
Michal

**Comment by BoyuanYan** [comment]
Sorry about that. I thought `sr_dp_get_items_subscribe()` is the method used by netconf client to subscribe something from netconf server. I find the demo \:
https://github.com/sysrepo/sysrepo/blob/37840cda654853eb11b350bcef3b835523b3ad88/examples/oper_data_example.c#L105
Thanks very much.
