### ISSUE TITLE
cmake error for the sysrepo

### ISSUE THREAD

**Issue by darcyllingyan** [sysrepo/sysrepo#1143]
Hi, when I build the sysrepo, it always reports the following error, can someone help to give a solution? I have really spent lots of time and couldn't resolve it. Thanks very much in advance. The CMakeError.log and CmakeOutput.log is below.
[CMakeError.log](https://github.com/sysrepo/sysrepo/files/2038222/CMakeError.log)
[CMakeOutput.log](https://github.com/sysrepo/sysrepo/files/2038223/CMakeOutput.log)

bash-4.2# cmake -DCMAKE_BUILD_TYPE=Debug ..
-- Preparing systemwide build of sysrepo v. 0.7.3
-- sysrepo repository location: /etc/sysrepo
-- Could NOT find ev (missing:  EV_LIBRARY EV_INCLUDE_DIR) 
-- Could NOT find avl (missing:  AVL_LIBRARY AVL_INCLUDE_DIR) 
-- libredblack will be used for binary tree manipulations.
-- Example code and YANG models will be built and installed.
-- CMocka found, tests are enabled.
-- Test repostory location differs to system repository location, some tests will be disabled.
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Lua version 5.1 was selected
-- Could NOT find Lua51 (missing:  LUA_INCLUDE_DIR) 
CMake Warning at swig/CMakeLists.txt:23 (message):
  Did not found Lua version 5.1

-- Sysrepo supports Lua 5.1, Lua 5.2 and Lua 5.3
-- Python version 2 was selected
-- Could NOT find PythonLibs (missing:  PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (Required is at least version "2")
CMake Warning at swig/CMakeLists.txt:50 (message):
  Did not found Python version 2.x

-- Sysrepo supports Python 2.x and Python 3.x
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
EV_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/centos/sysrepo-master/src
   used as include directory in directory /home/centos/sysrepo-master/src
   used as include directory in directory /home/centos/sysrepo-master/src
   used as include directory in directory /home/centos/sysrepo-master/src
   used as include directory in directory /home/centos/sysrepo-master/src
   used as include directory in directory /home/centos/sysrepo-master/src
   used as include directory in directory /home/centos/sysrepo-master/src
   used as include directory in directory /home/centos/sysrepo-master/src
   used as include directory in directory /home/centos/sysrepo-master/src
   used as include directory in directory /home/centos/sysrepo-master/examples
   used as include directory in directory /home/centos/sysrepo-master/examples
   used as include directory in directory /home/centos/sysrepo-master/examples
   used as include directory in directory /home/centos/sysrepo-master/examples
   used as include directory in directory /home/centos/sysrepo-master/examples
   used as include directory in directory /home/centos/sysrepo-master/examples
   used as include directory in directory /home/centos/sysrepo-master/examples
   used as include directory in directory /home/centos/sysrepo-master/examples
   used as include directory in directory /home/centos/sysrepo-master/examples
   used as include directory in directory /home/centos/sysrepo-master/examples
   used as include directory in directory /home/centos/sysrepo-master/examples
   used as include directory in directory /home/centos/sysrepo-master/examples
   used as include directory in directory /home/centos/sysrepo-master/examples
   used as include directory in directory /home/centos/sysrepo-master/examples
   used as include directory in directory /home/centos/sysrepo-master/examples
   used as include directory in directory /home/centos/sysrepo-master/examples
   used as include directory in directory /home/centos/sysrepo-master/examples
   used as include directory in directory /home/centos/sysrepo-master/examples/plugins
   used as include directory in directory /home/centos/sysrepo-master/examples/plugins
   used as include directory in directory /home/centos/sysrepo-master/tests
   used as include directory in directory /home/centos/sysrepo-master/tests
   used as include directory in directory /home/centos/sysrepo-master/tests
   used as include directory in directory /home/centos/sysrepo-master/tests
   used as include directory in directory /home/centos/sysrepo-master/tests
   used as include directory in directory /home/centos/sysrepo-master/tests
   used as include directory in directory /home/centos/sysrepo-master/tests
   used as include directory in directory /home/centos/sysrepo-master/tests
   used as include directory in directory /home/centos/sysrepo-master/tests
   used as include directory in directory /home/centos/sysrepo-master/tests
   used as include directory in directory /home/centos/sysrepo-master/tests
   used as include directory in directory /home/centos/sysrepo-master/tests
   used as include directory in directory /home/centos/sysrepo-master/tests
   used as include directory in directory /home/centos/sysrepo-master/tests
   used as include directory in directory /home/centos/sysrepo-master/tests
   used as include directory in directory /home/centos/sysrepo-master/tests
   used as include directory in directory /home/centos/sysrepo-master/tests
   used as include directory in directory /home/centos/sysrepo-master/tests
   used as include directory in directory /home/centos/sysrepo-master/tests
   used as include directory in directory /home/centos/sysrepo-master/swig
   used as include directory in directory /home/centos/sysrepo-master/swig/cpp/examples
   used as include directory in directory /home/centos/sysrepo-master/swig/cpp/examples
   used as include directory in directory /home/centos/sysrepo-master/swig/cpp/examples
   used as include directory in directory /home/centos/sysrepo-master/swig/cpp/examples
   used as include directory in directory /home/centos/sysrepo-master/swig/cpp/examples
   used as include directory in directory /home/centos/sysrepo-master/swig/cpp/examples
   used as include directory in directory /home/centos/sysrepo-master/swig/cpp/examples
   used as include directory in directory /home/centos/sysrepo-master/swig/cpp/examples
EV_LIBRARY (ADVANCED)
    linked by target "sysrepo-plugind" in directory /home/centos/sysrepo-master/src
    linked by target "sysrepo_a" in directory /home/centos/sysrepo-master/src
    linked by target "sysrepo" in directory /home/centos/sysrepo-master/src

-- Configuring incomplete, errors occurred!
See also "/home/centos/sysrepo-master/build/CMakeFiles/CMakeOutput.log".
See also "/home/centos/sysrepo-master/build/CMakeFiles/CMakeError.log".

**Comment by michalvasko** [comment]
Hi,
the important line is
```
-- Could NOT find ev (missing: EV_LIBRARY EV_INCLUDE_DIR)
```
meaning you are missing `libev`. So, just install `libev-devel` package (likely provided for your system) and you should be fine.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
Really thanks very much! The issue is resolved now. I just install libev but libev-devel.
