### ISSUE TITLE
The sysrepoctl install can't parse the pattern format, such as pattern "[a-zA-Z0-9\*#\.,\-'!$()&%/_ ]*";

### ISSUE THREAD

**Issue by darcyllingyan** [sysrepo/sysrepo#1144]
Hi,
I have several questions about the sysrepo, 
1. I have 270 yang files, can sysrepoctl install the yang module with a folder input but the yang file? With this I can install all the yang files once.
2.  I can't subscribe my yang module:
bash-4.2# /home/centos/sysrepo-master/build/examples/application_example zfffil

 ========== READING STARTUP CONFIG zfffil: ==========

Error by sr_module_change_subscribe: The operation failed

3. The sysrepocfg command usage is equal to the edit-config in netconf client, right?
4. When I install the yang module with pattern format, such as pattern "[a-zA-Z0-9\*#\.,\-'!$()&%/_ ]*"; It always reports "Invalid keyword "[a-zA-Z0-9\*#\.,\-'!$()&%/_ ]*""." The sysrepoctl can't parse the regular expression? For example:
bash-4.2# sysrepoctl --install --yang=zf1fil.yang
Installing a new module from file 'zf1fil.yang'...
[ERR] libyang: Invalid keyword "(ldap://)(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}"".
[ERR] libyang: Module "base-types" parsing failed.
[ERR] libyang: Importing "base-types" module into "zf1fil" failed.
[ERR] libyang: Module "zf1fil" parsing failed.
Error: Unable to load the module by libyang.
Install operation failed.
The yang file is:
[zf1fil-yang.txt](https://github.com/sysrepo/sysrepo/files/2043864/zf1fil-yang.txt)

5.  I can't sysrepocfg XML to sysrepo and don't know why, can you help to give a solution? 
zfffil-xml.txt is the XML and zfffil-yang.txt is the yang file.
[zfffil-xml.txt](https://github.com/sysrepo/sysrepo/files/2043450/zfffil-xml.txt)
[zfffil-yang.txt](https://github.com/sysrepo/sysrepo/files/2043451/zfffil-yang.txt)
The error is:
bash-4.2# sysrepocfg --import=pljoma/zfffil.xml --format=xml --datastore=startup zfffil 
bash-4.2# sysrepocfg --import=pljoma/zfffil.xml --format=xml --datastore=startup zfffil -l 4
[DBG] Setting log level for stderr logs to 4.
[DBG] Connecting to Sysrepo Engine.
[DBG] Connecting to socket=/var/run/sysrepod.sock
[INF] Connected to daemon Sysrepo Engine at socket=/var/run/sysrepod.sock
[DBG] Sending version-verify request.
[DBG] version-verify request sent, waiting for response.
[DBG] version-verify response received, processing.
[DBG] Sending session-start request.
[DBG] session-start request sent, waiting for response.
[DBG] session-start response received, processing.
[DBG] Loading module schema: '/etc/sysrepo/yang/zfffil@2017-01-15.yang'.
[DBG] Sending discard-changes request.
[DBG] discard-changes request sent, waiting for response.
[DBG] discard-changes response received, processing.
[DBG] Sending get-items request.
[DBG] get-items request sent, waiting for response.
[DBG] get-items response received, processing.
[DBG] No items found for xpath '/zfffil:*//.'
[DBG] <LYD_DIFF_CREATED> parent: (null), new node: /nokia-tas-structure:session-control
[DBG] Sending set-item request.
[DBG] set-item request sent, waiting for response.
[DBG] set-item response received, processing.
[ERR] Error by processing of the set-item request (session id=375629608): Invalid expression..
[ERR] Error by processing of the request.
[ERR] Error returned from sr_set_item: Request contains unknown element.
Errors were encountered during importing. Cancelling the operation.
[DBG] Sending session-stop request.
[DBG] session-stop request sent, waiting for response.
[DBG] session-stop response received, processing.

With the edit-config, the same error is:
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        path:     /nokia-tas-structure:session-control/digit-analysis/digit-analysis-result/zfffil:sla-parameter-sets/sla-parameter-set[parameter-set-name='paramset2']
        message:  Invalid expression.

**Comment by michalvasko** [comment]
Hi,
please try to retry these operations in `devel` and then come back. But, I can answer some questions:

1. `sysrepoctl` does not allow what you want and I am not sure whether it is needed. You can write a simple script that will perform what you described.

3. It depends which command, but generally speaking it should.

4. Please provide the module with the error, `base-types`. Nevertheless, the problem will likely be an invalid double-quoted string so the fix would be to delimit the pattern in `'` instead of `"`.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
Thanks for the response!
Yes, after changed all the " to ', the Yang parse successfully.

Thanks
Darcy
