### ISSUE TITLE
I can't import the XML file after I install the YANG, but after I uninstall the module and re-import the XML, it succeed

### ISSUE THREAD

**Issue by darcyllingyan** [sysrepo/sysrepo#1145]
Hi,
1. I install the yang to sysrepo and it is successfull.
bash-4.2# sysrepoctl --install --yang=jomayang/access-network-voip-cap-list-table.yang
Installing a new module from file 'jomayang/access-network-voip-cap-list-table.yang'...
Installing the YANG file to '/etc/sysrepo/yang/access-network-voip-cap-list-table@2017-01-15.yang'...
Resolving dependency: 'access-network-voip-cap-list-table' imports 'nokia-tas-structure'...
Installing the YANG file to '/etc/sysrepo/yang/nokia-tas-structure@2017-01-15.yang'...
Resolving dependency: 'nokia-tas-structure' imports 'nokia-extensions'...
Installing the YANG file to '/etc/sysrepo/yang/nokia-extensions@2017-01-15.yang'...
Resolving dependency: 'access-network-voip-cap-list-table' imports 'nokia-extensions'...
Installing the YANG file to '/etc/sysrepo/yang/nokia-extensions@2017-01-15.yang'...
Skipping installation of data files for module 'access-network-voip-cap-list-table'...
Resolving dependency: 'access-network-voip-cap-list-table' imports 'nokia-tas-structure'...
Installing data files for module 'nokia-tas-structure'...
Resolving dependency: 'nokia-tas-structure' imports 'nokia-extensions'...
Skipping installation of data files for module 'nokia-extensions'...
Resolving dependency: 'access-network-voip-cap-list-table' imports 'nokia-extensions'...
Skipping installation of data files for module 'nokia-extensions'...
Notifying sysrepo about the change...
Install operation completed successfully.

2. I import the xml data, it reports error and shows unknown element.
bash-4.2# sysrepocfg --import=pljoma-joma-xml/pljoma/access-network-voip-cap-list-table-successful.xml access-network-voip-cap-list-table --datastore=running
Cannot operate on the running datastore for 'access-network-voip-cap-list-table' as there are no active subscriptions for it.
Canceling the operation.
bash-4.2# sysrepocfg --import=pljoma-joma-xml/pljoma/access-network-voip-cap-list-table-successful.xml access-network-voip-cap-list-table --datastore=startup
[ERR] Error by processing of the set-item request (session id=537466554): Invalid expression..
[ERR] Error by processing of the request.
[ERR] Error returned from sr_set_item: Request contains unknown element.
Errors were encountered during importing. Cancelling the operation.

3. I uninstall the module 
bash-4.2# sysrepoctl --uninstall --module=access-network-voip-cap-list-table --revision=2017-01-15
Uninstalling the module access-network-voip-cap-list-table...
Deleted the schema file '/etc/sysrepo/yang/access-network-voip-cap-list-table@2017-01-15.yang'.
Deleted the data files for module 'access-network-voip-cap-list-table'.
Uninstall operation completed successfully.

4. I install again
bash-4.2# sysrepoctl --install --yang=jomayang/access-network-voip-cap-list-table.yang
Installing a new module from file 'jomayang/access-network-voip-cap-list-table.yang'...
Installing the YANG file to '/etc/sysrepo/yang/access-network-voip-cap-list-table@2017-01-15.yang'...
Resolving dependency: 'access-network-voip-cap-list-table' imports 'nokia-tas-structure'...
Installing the YANG file to '/etc/sysrepo/yang/nokia-tas-structure@2017-01-15.yang'...
Resolving dependency: 'nokia-tas-structure' imports 'nokia-extensions'...
Installing the YANG file to '/etc/sysrepo/yang/nokia-extensions@2017-01-15.yang'...
Resolving dependency: 'access-network-voip-cap-list-table' imports 'nokia-extensions'...
Installing the YANG file to '/etc/sysrepo/yang/nokia-extensions@2017-01-15.yang'...
Skipping installation of data files for module 'access-network-voip-cap-list-table'...
Resolving dependency: 'access-network-voip-cap-list-table' imports 'nokia-tas-structure'...
Installing data files for module 'nokia-tas-structure'...
Resolving dependency: 'nokia-tas-structure' imports 'nokia-extensions'...
Skipping installation of data files for module 'nokia-extensions'...
Resolving dependency: 'access-network-voip-cap-list-table' imports 'nokia-extensions'...
Skipping installation of data files for module 'nokia-extensions'...
Notifying sysrepo about the change...
Install operation completed successfully.

5. I import the XML data again, it is successful. Suppose it should be invalid and the first time I import data it should be successful, right?
bash-4.2# sysrepocfg --import=pljoma-joma-xml/pljoma/access-network-voip-cap-list-table-successful.xml access-network-voip-cap-list-table --datastore=startup
The new configuration was successfully applied.

**Comment by michalvasko** [comment]
Hi,
please, like in other cases, try it again with `devel`. I think it may be fixed despite not knowing what the exact problem is.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
You mean I could download the sysrepo from devel branch and install again to try again?

But when I operate the examples stored in sysrepo example, it works well and don't need to uninstall.
bash-4.2# sysrepocfg --import=turing-machine.test turing-machine --datastore=running
The new configuration was successfully applied.

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
exactly that, properly remove the current version of *sysrepo* and install it again from `devel`. The command you mentioned should not succeed because like it said before, there are no active subscriptions to the model, so `running` is not enabled. Retry it in `devel`, then I will investigate more.

Regards,
Michal

**Comment by darcyllingyan** [comment]
HI Michal,
When I install the sysrepo-devel, it reports the following error:
bash-4.2# make
[  1%] Building C object src/CMakeFiles/COMMON.dir/common/sr_utils.c.o
/home/centos/sysrepo-devel/src/common/sr_utils.c: In function ‘sr_subtree_to_dt’:
/home/centos/sysrepo-devel/src/common/sr_utils.c:1864:21: error: too many arguments to function ‘ly_errmsg’
                     SR_LOG_ERR("Failed to create tree root node (leaf) ('%s'): %s", xpath, ly_errmsg(ly_ctx));
                     ^
In file included from /home/centos/sysrepo-devel/src/common/sr_utils.c:38:0:
/usr/local/include/libyang/libyang.h:1877:13: note: declared here
 const char *ly_errmsg(void);
In file included from /home/centos/sysrepo-devel/src/common/sr_utils.c:38:0:
/usr/local/include/libyang/libyang.h:1877:13: note: declared here
 const char *ly_errmsg(void);
             ^
/home/centos/sysrepo-devel/src/common/sr_utils.c:1871:21: error: too many arguments to function ‘ly_errmsg’
                     SR_LOG_ERR("Unable to add leaf node (named '%s'): %s", sr_tree->name, ly_errmsg(ly_ctx));
                     ^
In file included from /home/centos/sysrepo-devel/src/common/sr_utils.c:38:0:
/usr/local/include/libyang/libyang.h:1877:13: note: declared here
 const char *ly_errmsg(void);
             ^
/home/centos/sysrepo-devel/src/common/sr_utils.c: At top level:
cc1: warning: unrecognized command line option "-Wno-language-extension-token" [enabled by default]
make[2]: *** [src/CMakeFiles/COMMON.dir/common/sr_utils.c.o] Error 1
make[1]: *** [src/CMakeFiles/COMMON.dir/all] Error 2
make: *** [all] Error 2


Whether it means I need to re-install the libyang and use the devel branch?

Thanks
Darcy

**Comment by swathins079** [comment]
Hi,

Try updating libyang to latest devel as sysrepo uses libyang.

Regards,
Swathin

**Comment by michalvasko** [comment]
Hi Darcy,
like @swathins079 said, if you use `devel` of *sysrepo*, you must also use `devel` of all the other libraries, which is only *libyang* in this case (but if you also use *netopeer2*, it would additionally be *libnetconf2*).

Regards,
Michal
