### ISSUE TITLE
The subscribe requested schema model is not known, I have sysrepoctl --uninstall and sysrepoctl --install but it still doesn't work

### ISSUE THREAD

**Issue by darcyllingyan** [sysrepo/sysrepo#1146]
Hi,
I install the yang module access-network-voip-cap-list-table but I can't subscribe 
bash-4.2# /home/centos/sysrepo-master/build/examples/application_changes_example access-network-voip-cap-list-table
Application will watch for changes in access-network-voip-cap-list-table

 ========== READING STARTUP CONFIG: ==========

Error by sr_module_change_subscribe: Requested schema model is not known

**Comment by michalvasko** [comment]
Please provide output of `sysrepoctl -l`, I should know more after that.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi,
based on this output (empty content of `Data Owner` and `Permissions` columns of `access-network-voip-cap-list-table`) the model you are trying to subscribe does not have any data. If there are some augments in the model, you should subscribe to the augment target model instead.

Regards,
Michal
