### ISSUE TITLE
Insufficient documentation for enabling NACM

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#1150]
While working on #1149 , I stumbled upon failures in the NACM-related tests. These tests appear to require a [special set of filesystem ACLs](https://github.com/sysrepo/sysrepo/blob/master/deploy/travis/install-test-users.sh#L26-L29).

Can you please confirm whether some fancy permissions or ACLs are needed for a regular user? Should I set the Unix permissions and/or ACLs on the `/etc/sysrepo` somehow?

**Comment by michalvasko** [comment]
Hi,
normally, you do not need anything, this script is executed only for `nacm_cl_test`. If these commands are not executed and the users created, this test is skipped.

Regards,
Michal

**Comment by jktjkt** [comment]
Thanks.
