### ISSUE TITLE
no return SR_ERR_OK in module_change_cb. but execute commint using netopeer2-cli,the result is OK

### ISSUE THREAD

**Issue by zhuminghui** [sysrepo/sysrepo#1153]
Python App:
```
def module_change_cb(sess, module_name, event, private_ctx):
    try:
        print "\n\n ========== Notification " + ev_to_str(event) + " =============================================\n"
        if (sr.SR_EV_APPLY == event):
            change_path = "/" + module_name + ":*"
            it = sess.get_changes_iter(change_path);
            while True:
                change = sess.get_change_next(it)
                if change == None:
                    break
                print_change(change.oper(), change.old_val(), change.new_val())
            print_current_config(sess, module_name);
            **return sr.SR_ERR_OPERATION_FAILED**

   
    except Exception as e:
        print e

    return sr.SR_ERR_OK

......

subscribe.module_change_subscribe(module_name, module_change_cb)
...
```
use netopeer2-cli:
> edit-config --target candidate --def merge --error rollback --config
OK
> commit
OK

I think execute commit,the resut is not OK!

**Comment by michalvasko** [comment]
Hi,
are you using `master` sysrepo? As far as I know this was the behaviour in `master` but I have changed in `devel` so that the error is passed to the client (it may not work perfectly, though).

Regards,
Michal

**Comment by zhuminghui** [comment]
Yes,I use the master sysrepo and Netopeer2.
sysrepo:
`commit c4fc434f0640905a3b4e3378151d2c399fba945a
Merge: 36bb10f eaf40e9
Author: Michal Vasko <mvasko@cesnet.cz>
Date:   Mon Mar 19 10:29:02 2018 +0100

    Merge pull request #1083 from andrei-pavel/master
    
    added libSysrepo-cpp.pc.in for pkg-config`

Netopeer2:
`commit 917eb39a7ec08099808e0ad52d4d77b37dcdaaa7
Author: Michal Vasko <mvasko@cesnet.cz>
Date:   Thu Mar 29 09:31:40 2018 +0200

    cli VERSION bump to version 2.0.44`

**Comment by michalvasko** [comment]
Hi,
so to fix your problem you can either switch to `devel` or wait for its merge into `master` (should not take too long now).

Regards,
Michal

**Comment by zhuminghui** [comment]
Thank you.I will try it.
