### ISSUE TITLE
Unknown element "nacm".

### ISSUE THREAD

**Issue by sheetaljoshi** [sysrepo/sysrepo#1155]
### Description
I have compiled sysrepo to include NACM module -DENABLE_NACM:BOOL=ON, but when I try to run sample groups creation via edit config as specified in RFC https://tools.ietf.org/html/rfc6536 it gives below error 
> edit-config --target=running --config=/root/groups.xml
ERROR
	type:     protocol
	tag:      unknown-element
	severity: error
	message:  Unknown element "nacm".
	bad-elem #1:

### Steps to Reproduce
1. Compiled and running sysrepo and netopeer on a VM using the same compile recipes mentioned in Dockerfile
2. sysrepoctl shows below output
```console
Module Name                   | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
ietf-netconf-notifications    | 2012-02-06 | Installed   | root:root           | 666         |                               |
ietf-netconf                  | 2011-06-01 | Imported    |                     |             |                               |
ietf-netconf-acm              | 2012-02-22 | Imported    |                     |             |                               |
nc-notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |
notifications                 | 2008-07-14 | Installed   | root:root           | 666         |                               |
turing-machine                | 2013-12-27 | Installed   | root:root           | 666         |                               |
iana-if-type                  | 2014-05-08 | Installed   |                     |             |                               |
ietf-interfaces               | 2014-05-08 | Installed   | root:root           | 666         |                               |
ietf-ip                       | 2014-06-16 | Installed   |                     |             |                               |
```
3. Trying to use netopeer2-cli to run edit-config as below
```console
edit-config --target=running --config=/root/groups.xml
```
4. groups.xml as below
```console
<nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
     <groups>
       <group>
         <name>admin</name>
         <user-name>admin</user-name>
         <user-name>andy</user-name>
       </group>

       <group>
         <name>limited</name>
         <user-name>wilma</user-name>
         <user-name>bam-bam</user-name>
       </group>

       <group>
         <name>guest</name>
         <user-name>guest</user-name>
         <user-name>guest@example.com</user-name>
       </group>
     </groups>
</nacm>
```

5. However the server log shows below warning
```console
2018-06-04 14:04:03,289 INFO spawned: 'sysrepod' with pid 22432
2018-06-04 14:04:03,290 INFO spawned: 'sysrepo-plugind' with pid 22433
2018-06-04 14:04:03,292 INFO spawned: 'netopeer2-server' with pid 22434
2018-06-04 14:04:03,314 DEBG 'sysrepod' stdout output:
[WRN] (pm_add_subscription:1126) Unable to delete existing rpc subscriptions.

2018-06-04 14:04:03,318 DEBG 'sysrepod' stdout output:
[WRN] (pm_add_subscription:1126) Unable to delete existing rpc subscriptions.

2018-06-04 14:04:03,322 DEBG 'sysrepod' stdout output:
[WRN] (dm_apply_persist_data_for_model:826) Persist file for module ietf-netconf-acm does not exist.
```

Thanks!

**Comment by michalvasko** [comment]
Hi,
you do not have `ietf-netconf-acm` installed, only imported. `# make install` should do the trick.

Regards,
Michal

**Comment by sheetaljoshi** [comment]
Hi,

I was using the steps from [Dockerfile](https://github.com/sysrepo/sysrepo/blob/master/deploy/docker/sysrepo-netopeer2/platforms/Dockerfile.ubuntu) to compile and install sysrepo and netopeer. I did include -DENABLE_NACM:BOOL=ON -DNACM_RECOVERY_UID:INTEGER=0 during cmake of sysrepo, but if you observe Dockerfile.ubuntu we do recompile of sysrepo to install lua and python bindings. And these steps override the original flags used during sysrepo compile originally. And thats what was causing to not enable nacm. I did include these flags at every sysrepo recompile and that retained the flags and compiled sysrepo ok. Thanks for the response.

Thanks,
Sheetal

**Comment by michalvasko** [comment]
Hi Sheetal,
it seems to me this could be handled better but I do not maintain the docker image, what do you think @mislavn ?

Regards,
Michal

**Comment by mislavn** [comment]
Hi,

the Dockerfiles with language bindngs were made just for demonstrating how to install the language bindings on various platforms but I guess people are using them directly so I'll make a PR and update the Dockerfiles.

Regards,
Mislav
