### ISSUE TITLE
Getting  operational data of interface-state/system-state(or any other oper data) is coming as null in first attempt 

### ISSUE THREAD

**Issue by senrajib** [sysrepo/sysrepo#1160]
Getting  operational data of interface-state/system-state is coming as null in first attempt . It takes more than one retry to get full oper data.
### Steps to Reproduce
1. Send request from client as below

`
<get> <filter xmlns:ns0="urn:ietf:params:xml:ns:netconf:base:1.0" ns0:type="subtree"> 
<system-state xmlns="urn:ietf:params:xml:ns:yang:ietf-system"/> 
</filter> </get>
`

2.  In first and 2nd attempt we get  reply as in below attached

[Sysrepo_operdata_reply.txt](https://github.com/sysrepo/sysrepo/files/2075619/Sysrepo_operdata_reply.txt)

3. Likewise it takes atleast 4-5 attempts to get full oper data.

**Expected behavior:**
complete oper data should be returned in first attempt.

**Actual behavior:**
It takes atleast 4-5 attempts to get full oper data.

### Attachments
[Sysrepo.log_1st_Attempt.log](https://github.com/sysrepo/sysrepo/files/2075593/Sysrepo.log_1st_Attempt.log)
[Sysrepo.log_2nd_attempt.log](https://github.com/sysrepo/sysrepo/files/2075594/Sysrepo.log_2nd_attempt.log)

Thanks!

**Comment by michalvasko** [comment]
Hi,
what application provides the operational data, can you share it please?

Regards,
Michal

**Comment by senrajib** [comment]
Hi Michal,
Its and application written by us . It registers data provider callback like below
sr_dp_get_items_subscribe(session, "/ietf-system:system-state", data_provider_system_cb, NULL,SR_SUBSCR_DEFAULT, &subscription);

when we try getting oper data from Netconf client(MG Soft) , data_provider_system_cb callbak is supposed to fill all the system related info and send to the client. 

However observation we are making is , after system comes up , the very first attempt to get oper data is resulting in above reply.

**Comment by michalvasko** [comment]
Did you read [this](http://www.sysrepo.org/static/doc/html/subscribtions.html#data_providers) DOC section and follow it? I would have to know what data you return for what XPaths to be able to investigate more but it really looks to me as a problem with not returning enough nodes in your callback.

Regards,
Michal

**Comment by senrajib** [comment]
Hi Michal
This issue is about very first(after system comes up) get attempt  of oper data returning nothing. But registered callback sr_dp_get_items_subscribe is hit .
Subsequent get operations start returning oper data.

Thanks
Rajib

**Comment by senrajib** [comment]
Hi Michal ,
'TIme out' logs are seen during very first attempt (after system recovers from reboot) to fetch oper data. There after we see no time out logs . Yes i shall check  increasing  OPER_DATA_PROVIDE_TIMEOUT value , but surprisingly  later attempts don't result in time outs.

Thanks
Rajib

**Comment by michalvasko** [comment]
Hi Rajib,
that is quite strange but since I have absolutely no information to go on, I cannot help you.

Regards,
Michal

**Comment by senrajib** [comment]
Hi Michal ,
'TIme out' logs  seen during very first attempt (after system recovers from reboot) to fetch oper data seem logical . Increasing OPER_DATA_PROVIDE_TIMEOUT value didn't help . 

1. It appears from above logs that during very first attempt (after system recovers from reboot) to fetch oper data only four times data-provider request were sent and data-provider response received unlike 17 times during 2nd attemt

	Line 73: Jun  1 15:30:09 MaestrOS sysrepod[7105]: [DBG] Sending a data-provide request to '/var/run/sysrepo-subscriptions/ietf-system/7187.4NFaey.sock'.
	Line 100: Jun  1 15:30:09 MaestrOS sysrepod[7105]: [DBG] Sending a data-provide request to '/var/run/sysrepo-subscriptions/ietf-system/7187.4NFaey.sock'.
	Line 125: Jun  1 15:30:09 MaestrOS sysrepod[7105]: [DBG] Sending a data-provide request to '/var/run/sysrepo-subscriptions/ietf-system/7187.4NFaey.sock'.
	Line 132: Jun  1 15:30:09 MaestrOS sysrepod[7105]: [DBG] Sending a data-provide request to '/var/run/sysrepo-subscriptions/ietf-system/7187.4NFaey.sock'.

2. And this is happening probably because subscriptions for subtree node were only found for these four only

	Line 68: Jun  1 15:30:09 MaestrOS sysrepod[7105]: [DBG] Found match for system-state with depth 0 index 0
	Line 92: Jun  1 15:30:09 MaestrOS sysrepod[7105]: [DBG] Found match for platform with depth 1 index 0
	Line 113: Jun  1 15:30:09 MaestrOS sysrepod[7105]: [DBG] Found match for clock with depth 1 index 0
	Line 117: Jun  1 15:30:09 MaestrOS sysrepod[7105]: [DBG] Found match for system-info with depth 1 index 0

3. Looks like as per sysrepo design subscription data are cached and during very first query cache miss is observed . Later cached.

Jun  1 15:30:09 MaestrOS sysrepod[7105]: [DBG] Caching 1 subscriptions from 'ietf-system' persist file.
Jun  1 15:30:09 MaestrOS sysrepod[7105]: [DBG] Returning 1 subscriptions found in 'ietf-system' persist file.

Would you please  confirm if this is sysrepo designed and expected behavior ?

Thanks
Rajib

**Comment by michalvasko** [comment]
Hi Rajib,
yes, there is some cache used but it definitely should not affect the behaviour, the initial timeout does not seem logical to me. If you cannot publish your operational data callback, maybe you could only sent it to me privately so I can take a look?

Regards,
Michal

**Comment by michalvasko** [comment]
Based on all the information in this thread it seems there is some incomplete subscription stored in the cache that is used the first time, but I will know more once I can replicate the problem myself.

Regards,
Michal

**Comment by michalvasko** [comment]
Yes, it is.

**Comment by senrajib** [comment]
Hi Michal
Details asked have been sent to your above mail id .

Thanks
Rajib

**Comment by michalvasko** [comment]
Will be solved privately.
