### ISSUE TITLE
Sysrepo validation error with multiple leafrefs across augments

### ISSUE THREAD

**Issue by aweast** [sysrepo/sysrepo#1164]
### First items attempted
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?
* [x] Did you test it on the latest sysrepo devel branch and the latest libyang devel branch?

### Description
We have a specific set of yang models that always present validation errors when we attempt an edit-config through netopeer2. I have included the simplest example that demonstrates the problem below. The following graphic shows the basic relationship between the modules.

```
 ______________
|              |
|  mainmodule  |
|______________|
        |
        |  import / use leafref type
        v
 ______________                _______________
|              |   augment    |               |
|  augmentone  |------------->|  augmentbase  |
|______________|              |_______________|
        |                              ^
        |                              | augment
        |                              |
        |  import /             _______________
        |  use leafref type    |               |
        ---------------------->|  augmenttwo   |
                               |_______________|
```

Our `mainmodule` imports `augmentone` and uses a leafref typedef defined in `augmentone` that references a node within `augmentone`. As you can see in our simple rpc below, we do not attempt to modify the leaf that uses the imported type.

The `augmentone` module imports `augmenttwo` and uses a leafref typedef defined in `augmenttwo` that references to a node within `augmenttwo`. 

Both `augmentone` and `augmenttwo` define augments to the `base-container` in the `augmentbase` module. This appears to be somewhat important. We found this issue does not occur if the `augmentone` and `augmenttwo` modules have their own top-level containers instead of augments.

The `augmenttwo` module also has a container named `random` within the augment. If `augmentwo`'s augment does not contain a container, the error does not occur.

```YANG
module mainmodule {
    namespace "test:mainmodule";
    prefix main;
    
    import augmentone {
        prefix aone;
    }

    container main {
        leaf main-leaf {
            type string;
        }

        leaf leaf-ref {
            type aone:onetyperef;
        }
    }
}
```
```YANG
module augmentbase {
    namespace "test:augmentbase";
    prefix abase;

    container base-container {
        leaf base-leaf {
            type string;
        }
    }
}
```
```YANG
module augmentone {
    namespace "test:augmentone";
    prefix aone;

    import augmentbase {
       prefix abase;
    }

    import augmenttwo {
        prefix atwo;
    }

    typedef onetyperef {
        type leafref {
            path "/abase:base-container/aone:one-leaf";
        }
    }

    augment "/abase:base-container" {
        leaf one-leaf {
            type string;
        }

        leaf one-leaf-ref {
            type atwo:twotyperef;
        }
    }
}
```
```YANG
module augmenttwo {
    namespace "test:augmenttwo";
    prefix atwo;

    import augmentbase {
        prefix abase;
    }

    typedef twotyperef {
        type leafref {
            path "/abase:base-container/atwo:two-leaf";
        }
    }

    augment "/abase:base-container" {
        leaf two-leaf {
            type string;
        }

        container random {
            description "This will cause it to fail";
        }
    }
}
```

In the following configuration, we only set the `main-leaf` leaf in `mainmodule`. We do not touch the leaf with the leafref into `augmentone`.
```XML
<main xmlns="test:mainmodule">
    <main-leaf>test</main-leaf>
</main>
```

To test this issue, we used the application_changes_example program included with sysrepo to watch the `mainmodule` module. The netopeer2-cli output can be seen below:
```console
> edit-config --target running --config=path/to/configs/mainmodule.rpc
ERROR
    type:     application
    tag:      operation-failed
    severity: error
    message:  Validation failed: Sysrepo-internal error
```
We have attached the syslog output from the edit-config operation. This part seems the most interesting:
```console
sysrepod[9011]: [DBG] (rp_dt_commit:858) Commit (4/10): replay of operation succeeded
sysrepod[9011]: [DBG] (ac_set_identity:155) Switching identity to UID='0' and GID='0' (username: root).
sysrepod[9011]: [DBG] (ac_set_identity:155) Switching identity to UID='0' and GID='0' (username: root).
sysrepod[9011]: [DBG] (dm_load_data_tree_file:1211) Loaded module augmentbase: mtime sec=1528396835 nsec=493678910
sysrepod[9011]: [DBG] (dm_load_data_tree_file:1295) Usage count augmentbase incremented (value=9)
sysrepod[9011]: [INF] (dm_load_data_tree_file:1301) Data file /path/to/yang/repository/data/augmentbase.running loaded successfully
sysrepod[9011]: [DBG] (dm_get_data_info_internal:2842) Module augmentbase has been loaded
sysrepod[9011]: [ERR] (dm_ly_log_cb:1425) libyang error: Target context does not contain schema node for the data node being duplicated (augmenttwo:random).
sysrepod[9011]: [ERR] (dm_append_data_tree:1981) Failed to merge augmentbase data tree
sysrepod[9011]: [ERR] (dm_load_dependant_data:2061) Failed to append data tree augmentbase
sysrepod[9011]: [ERR] (dm_validate_data_info:2678) Loading dependant modules failed for mainmodule
sysrepod[9011]: [ERR] (rp_dt_commit:864) Validation after merging failed
```

This is the relevant portion of the sysrepoctl --list output:
```
Module Name                | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
mainmodule                 |            | Installed   | developer:developer | 666         |                               |
augmentone                 |            | Implemented |                     |             |                               |
augmentbase                |            | Implemented | developer:developer | 666         |                               |
augmenttwo                 |            | Imported    |                     |             |                               |
```

**Expected behavior:**
The included edit-config command should succeed.

**Actual behavior:**
An internal sysrepo validation error prevents the edit-config from succeeding.

### Versions
Please provide versions for software needed to reproduce the bug:
Sysrepo version: sysrepod - sysrepo daemon, version 0.7.4
Sysrepoctl version: sysrepoctl - sysrepo control tool, version 0.7.4
libyang version: yanglint 0.15.120

### Additional information
The main error happens a few times during the netopeer2 edit-config process. During the sysrepo commit process, it appears to occur during step 5/10 in `rp_dt_commit`. During the validation process, sysrepo appends dependent data trees into the main schema's ly_ctx. In the `dm_append_data_tree` function, `dm_get_data_info_internal` is used to get the `dm_data_info_t` for `augmentbase`. Following the struct members for the `di` variable, we can see the `random` container. However, the target ly_ctx does not have the schema for the `random` container.

### Attachments
[leafref_issue_syslog.txt](https://github.com/sysrepo/sysrepo/files/2082026/leafref_issue_syslog.txt)

**Comment by aweast** [comment]
@michalvasko, unfortunately, we don't have a good solution to this problem right now.  Any ideas ?

**Comment by michalvasko** [comment]
Hi,
it took me some time to find the problem and even more to fix it but it should work now with the most recent *libyang*. I also added tests with the models you posted here.

Regards,
Michal
