### ISSUE TITLE
parsing choice leaves in ietf-ip.yang

### ISSUE THREAD

**Issue by gimli2** [sysrepo/sysrepo#1165]
### Description
In ietf-ip.yang there is an option in leaf address to define prefix-length or netmask. When man use a netmask, the sysrepo raised "Unknown element" error. The used version of ietf-ip YANG model is revision from 2018-02-22 [ietf-ip@2018-02-22](https://github.com/YangModels/yang/blob/master/standard/ietf/RFC/ietf-ip%402018-02-22.yang).

### Steps to Reproduce
1. Prepare minimal data to example.json:
```
{
  "ietf-interfaces:interfaces": {
    "interface": [
      {
        "name": "eth0",
        "description": "Ethernet 0",
        "type": "iana-if-type:ethernetCsmacd",
        "enabled": true,
        "ietf-ip:ipv4": {
          "enabled": true,
          "mtu": 1500,
          "address": [
            {
              "ip": "192.168.2.100",
              "prefix-length": 24
            }
          ]
        }
      }
    ]
  }
}
```

And import it to datastore:
> sysrepocfg --import example.json --format=json ietf-interfaces --datastore=startup

2. Start manually editing the running datastore:
> sysrepocfg --editor=mcedit --format=json ietf-interfaces --datastore=startup

And remove whole leaf: "prefix-length" with value 24, save and exit - the behaviour is expected yet:
```
[ERR] (srcfg_import_datastore:822) Input data are not valid: Mandatory choice "subnet" missing a case branch.
(/ietf-interfaces:interfaces/interface[name='eth0']/ietf-ip:ipv4/address[ip='192.168.2.100'])
Unable to apply the changes. Would you like to continue editing the configuration? [y/n]`
```

Add leaf "netmask" with invalid empty value "" to propper place - the behaviour is stil expected yet:
```
[ERR] (srcfg_import_datastore:801) Unable to parse the input data: Value "" does not satisfy the constraint "(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])" (range, length, or pattern).
(/ietf-interfaces:interfaces/interface[name='eth0']/ietf-ip:ipv4/address[ip='192.168.2.100']/netmask)
Unable to apply the changes. Would you like to continue editing the configuration? [y/n]
```

and now go to fill a valid mask value: "255.255.255.0" - the sysrepo complains on unknown element:
```
[ERR] (sr_commit:2095) Commit operation failed with 1 error(s).
[ERR] (srcfg_import_datastore:912) Error returned from sr_commit:
Validation of the changes failed.
[ERR] (srcfg_import_datastore:915) /ietf-interfaces:interfaces/interface[name='eth0']/ietf-ip:ipv4/address[ip='192.168.2.100']/netmask : Unknown element "netmask".
Unable to apply the changes. Would you like to continue editing the configuration? [y/n]
```

**Expected behavior:**
Add valid netmask to datatree.

**Actual behavior:**
Fails with following error:

```
[ERR] (sr_commit:2095) Commit operation failed with 1 error(s).
[ERR] (srcfg_import_datastore:912) Error returned from sr_commit: Validation of the changes failed. 
[ERR] (srcfg_import_datastore:915) /ietf-interfaces:interfaces/interface[name='eth0']/ietf-ip:ipv4/address[ip='192.168.2.100']/netmask : Unknown element "netmask".
```

### Versions
Sysrepo version: 0.7.3
libyang version: 0.14.80

### Attachments
Sysrepod log:
[sysrepod.log](https://github.com/sysrepo/sysrepo/files/2090365/sysrepod.log)

Installed modules:
[sysrepoctl-list.txt](https://github.com/sysrepo/sysrepo/files/2090341/sysrepoctl-list.txt)

**Comment by michalvasko** [comment]
Hi,
the reason is simple, you do not have `ietf-ip` feature `ipv4-non-contiguous-netmasks` enabled. Do that and it will work. Also, please use the current *sysrepo* version, it is 0.7.4 (`master` is fine).

Regards,
Michal

**Comment by gimli2** [comment]
Hups, my blindness, thank you for suggestion with. Closing issue.
