### ISSUE TITLE
when yang change, how to merge old datastore  to new 

### ISSUE THREAD

**Issue by leimgitub** [sysrepo/sysrepo#1170]
for example :
In version 0.02, I add a new leaf **net_mask** in yang-model.
When I in 0.02, back to 0.01, the sysrepocfg will fail to import xml datastore. 
 
Does anyone has a better way to deal with this?
Or do I need write a application to make right xml to matching yang-model?

Regards,

**Comment by michalvasko** [comment]
Hi,
I can only refer you to [this section](https://tools.ietf.org/html/rfc7950#section-11) which talks about proper model updating. But generally speaking, in the case you mentioned there is nothing better to do than remove the leaf manually.

Regards,
Michal

**Comment by leimgitub** [comment]
Thank.
I think maybe I can do this to deal with version downgrade.
I make a key value file.
Key is xpath.  After sysrepo import yang,  just need follow key value file, write to sysrepo. If write fail, it's ok, just ignore it.
