### ISSUE TITLE
Resolve identityref failed when evaluating notification

### ISSUE THREAD

**Issue by pfeige** [sysrepo/sysrepo#1175]
Hi,

with the modified testcase in this commit https://github.com/frimpler/sysrepo/commit/aafdc6b92b84b98749af9fce7092bba15b880d48 an issue resolving identityrefs is shown.

### Description

A notification shall be defined in a module (A) using a grouping from a module (B) which refers to a base identity from a module (C) which is derived in a module (D). When such a notification is actually sent using the derived identity from module (D), this identityref cannot be resolved when validating it with _dm_validate_procedure()_ because the libyang context of module (A) does not contain the module (D).

(A) id-ref-hello
(B) id-ref-hello-cont
(C) id-def-base
(D) id-def-extended

### Proposed Solution

The proposed solution https://github.com/frimpler/sysrepo/commit/7e773de87ac1789a061d2c3726462a7bf5c3231b provides the module callback function of the _data_manager.c_ in _dm_validate_procedure()_ before calling libyang from within _dm_sr_val_node_to_ly_datatree()_.

Regards,
Peter

**Comment by michalvasko** [comment]
Hi Peter,
you are right and if you create a pull request with the fix and the test, I will merge it. Thanks.

Regards,
Michal
