### ISSUE TITLE
sysrepoctl assert when installing module that imports a model with an augment within a uses statement and there is at least one additional augment

### ISSUE THREAD

**Issue by aweast** [sysrepo/sysrepo#1178]
### First items attempted
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?
* [x] Did you test it on the latest sysrepo devel branch and the latest libyang devel branch?

### Description
This is a follow-up to issue #1173. It appears that sysrepoctl fails to install a module when there is an augment within a uses and more than 1 additional augment within the same module. While debugging, it looks like the augment within the uses may cause the module to be prematurely marked as implemented. When the second top-level augment is processed, the module is already marked as implemented, and the augment does not receive a target. This causes an assert during the install process.

The issue does not appear if there is only one top-level augment in the module.

```YANG
module installme {
    namespace "test:installme";
    prefix im;

    import aug {
        prefix a;
    }
}
```
```YANG
module aug {
    namespace "test:aug";
    prefix a;

    import base {
        prefix ba;
    }

    grouping groupone {
        container grouponecont {

        }
    }

    augment "/ba:main/ba:second/ba:third" {
        description "First top-level augment in module";

        uses groupone {
            augment "grouponecont" {
                leaf groupleaf {
                    type string;
                }
            }
        }
    }

    augment "/ba:main/ba:second/ba:third" {
        description "Second top-level augment in module";
        
        leaf augleaftwo {
            type string;
        }
    }
}
```
```YANG
module base {
    namespace "test:base";
    prefix ba;

    container main {
        config false;
    }

    augment "/ba:main" {
        container second {
            list third {
                key name;
                leaf name {
                    type string;
                }
            }
        }
    }
}
```

The install command and output can be seen below.
```console
$ sysrepoctl --install --yang yang_files/installme.yang 
Installing a new module from file 'yang_files/installme.yang'...
sysrepoctl: /srcfiles/libyang/src/tree_schema.c:4009: apply_aug: Assertion `augment->target && (augment->flags & LYS_NOTAPPLIED)' failed.
Aborted (core dumped)

```

**Expected behavior:**
The module should install successfully.

**Actual behavior:**
Installing the module hits an assert message.

### Versions
Please provide versions for software needed to reproduce the bug:
Sysrepo version: sysrepod - sysrepo daemon, version 0.7.4
Sysrepoctl version: sysrepoctl - sysrepo control tool, version 0.7.4
libyang version: yanglint 0.15.124

NOTE: This is using libyang with pull request https://github.com/CESNET/libyang/pull/525 as of commit 368fd58.

**Comment by aweast** [comment]
@michalvasko, this is why I previously had the `aug->target` check in https://github.com/CESNET/libyang/pull/525

**Comment by michalvasko** [comment]
Okay, I will take a look and you can disregard my comment on your previous pull request.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi,
it should be fixed now but there were obviously some more complex cases such as this one not handled properly in *libyang*, so thanks for testing it. I have also added a test with these modules.

Just a note for future, it would be better if you created these as *libyang* issues (if you see from the output that it clearly is a problem in *libyang*) but it does not matter that much.

Regards,
Michal
