### ISSUE TITLE
Failed to save event notification

### ISSUE THREAD

**Issue by rosy8** [sysrepo/sysrepo#1179]
Hi,

Sometimes I am getting the following  sysrepo error message..(Failed to acquire tmp ly_ctx /Failed to save event notification) etc..
 
Apr 27 15:17:44 MaestrOS netopeer2-server[27665]: Session 2: thread 0 event new RPC.
Apr 27 15:17:44 MaestrOS sysrepod[27348]: [INF] Unlock datastore request
Apr 27 15:17:44 MaestrOS sysrepod[27348]: [INF] Dropping session id=1655061669.
Apr 27 15:17:44 MaestrOS sysrepod[27348]: [INF] Commit id 26953004 received all notifications
Apr 27 15:17:44 MaestrOS sysrepod[27348]: [INF] Unlock datastore request
Apr 27 15:17:44 MaestrOS sysrepod[27348]: [INF] Data file /etc/sysrepo/data/ietf-netconf-notifications.running is empty
Apr 27 15:17:44 MaestrOS sysrepod[27348]: [ERR] Failed to load module ietf-netconf-notifications
<b>Apr 27 15:17:44 MaestrOS sysrepod[27348]: [ERR] Failed to acquire tmp ly_ctx </b>
<b>Apr 27 15:17:44 MaestrOS sysrepod[27348]: [ERR] Failed print config-change notif to string </b>
<b>Apr 27 15:17:44 MaestrOS sysrepod[27348]: [ERR] Failed to save event notification </b>
Apr 27 15:17:44 MaestrOS sysrepod[27348]: [INF] Unlock datastore request
<b>Apr 27 15:17:44 MaestrOS sysrepod[27348]: [WRN] Error by processing of the message: Sysrepo-internal error. </b>
Apr 27 15:17:44 MaestrOS sysrepod[27348]: [INF] Data file /etc/sysrepo/data/xxx-config.running loaded successfully
Apr 27 15:17:44 MaestrOS sysrepod[27348]: [INF] Data file /etc/sysrepo/data/ietf-interfaces.running loaded successfully
Apr 27 15:17:44 MaestrOS sysrepod[27348]: [INF] New session created successfully, real user=root, effective user=(null), session id=1058622841.

Would you please let me know why getting so.

Regard's
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
the problem is one ERR before:
```
Apr 27 15:17:44 MaestrOS sysrepod[27348]: [ERR] Failed to load module ietf-netconf-notifications
```
Without reproducing it I don't really know what may be the cause. The model fails to be parsed, but that is not possible if nothing changed since when it was added into *sysrepo* the first time. Did you maybe manually move some files in sysrepo repository or modify its internal dependency file? I cannot think of any other reason.

Regards,
Michal
