### ISSUE TITLE
sysrepoctl change operation doesn't work with -m option

### ISSUE THREAD

**Issue by gitter-runner** [sysrepo/sysrepo#1180]
Hello,
I encountered a minor error which might be a bug.
As a root user, changing a module's attributes via sysrepoctl fails when I use the -m option with =.  When I leave =, the operation works. I tried out some other formats with the options and they all worked, see some examples below.

How to reproduce :

> sysrepoctl --change -m=ietf-netconf-notifications --permissions=644
> _**Changing ownership/permissions of the module '=ietf-netconf-notifications'.**
> chmod: cannot access '/etc/sysrepo/data/=ietf-netconf-notifications.startup': No such file or directory
> chmod: cannot access '/etc/sysrepo/data/=ietf-netconf-notifications.running': No such file or directory
> chmod: cannot access '/etc/sysrepo/data/=ietf-netconf-notifications.startup.lock': No such file or directory
> chmod: cannot access '/etc/sysrepo/data/=ietf-netconf-notifications.running.lock': No such file or directory
> chmod: cannot access '/etc/sysrepo/data/=ietf-netconf-notifications.persist': No such file or directory
> Error: Unable to change permissions to '644' for module '=ietf-netconf-notifications'.
> Operation was cancelled._

With --module option :

> sysrepoctl --change --module=ietf-netconf-notifications --permissions=644
> _**Changing ownership/permissions of the module 'ietf-netconf-notifications'.**
> Operation completed successfully._

With -m but without = :

> root@xubuntu12-VirtualBox:/home/xubuntu12# sysrepoctl --change -m ietf-interfaces -p=644
> _**Changing ownership/permissions of the module 'ietf-interfaces'.**
> Operation completed successfully._

I used master versions, with debug mode.
Libyang 0.15.123
Libnetconf2 0.11.37
Sysrepo 0.7.4
Netopeer2-server 0.5.24

Best regards,
Tamas

**Comment by michalvasko** [comment]
Hi Tamas,
that can be considered a feature of `getopt_long(3)`, nothing we can do about it.

Regards,
Michal
