### ISSUE TITLE
'Leafref points to a non-existent leaf' error when leaf is in a separate modules augment and referencing leaf in base module

### ISSUE THREAD

**Issue by aweast** [sysrepo/sysrepo#1183]
### Things you may try first
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description
When setting a leaf in an augment that is in a separate module than the container being augmented, and the leaf is a leafref type referencing a leaf in the base module, we receive a leafref error saying the leafref is non-existant. The value for the leaf being referenced is correctly shown in the get-config. 

base.yang
```YANG
module base {
    namespace "test:base";
    prefix ba;

    import augmented {
        prefix ag;
    }

    container profile {
        leaf name {
            type string;
        }
    }

    typedef profile-ref {
        type leafref {
            path "/ba:profile/ba:name";
        }
    }

    augment "/ag:item" {
        leaf profile-name {
            type profile-ref;
        }
    }
}
```

augmented.yang
```YANG
module augmented {

  namespace "test:augmented";
  prefix ag;

  container item {
    leaf foo {
      type string;
    }
  }
}
```

profile.rpc
```XML
<profile xmlns="test:base">
    <name>profile</name>
</profile>
```

augmented.rpc
```XML
<item xmlns="test:augmented">
    <foo>foo</foo>
    <profile-name xmlns="test:base">profile</profile-name>
</item>
```

This is the message received:
```
> edit-config --target=running --config=augmented.rpc
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        path:     /augmented:item/base:profile-name
        message:  Leafref "/base:profile/base:name" of value "profile" points to a non-existing leaf.
```

### Steps to Reproduce
1. Install base.yang with sysrepoctl
2. Run an edit-config with profile.rpc in netopeer2-cli
3. Run an edit-config with augmented.rpc in netopeer2-cli

**Expected behavior:**
edit-config should pass and data should appear in the datastore

**Actual behavior:**
edit-config fails with error shown above.

### Versions
Sysrepo version: `0.7.4` 
libyang version: `0.15.129`
netopeer2-server: `0.5.24`

**Comment by michalvasko** [comment]
Hi Adam,
sorry for not looking into this but I do not have time right now. I should manage it by Friday latest.

Regards,
Michal
