### ISSUE TITLE
Multiple client subscribing for module changes 

### ISSUE THREAD

**Issue by przemekr** [sysrepo/sysrepo#1185]
### Things you may try first
(put "x" in "[]" if you already tried following)
* [x] Did you check if this is a duplicate issue?
* [] Did you test it on the latest sysrepo devel branch?

### Description
Hi, I have several programs making subscription for a module changes. When the this is done at the same time an error 'Requested resource is already locked' is returned. 

### Steps to Reproduce
tested with sysrepo release 7.2 and 7.4, the issue can be reproduced starting several instances of the example applications:

 for i in $(seq 3); do ./swig/cpp/examples/cpp_application_changes_example & done
[31] 3593
[32] 3599
[33] 3602

 ========== READING STARTUP CONFIG: ==========
*Requested resource is already locked*
 ========== READING STARTUP CONFIG: ==========
 ========== STARTUP CONFIG APPLIED AS RUNNING ==========
 ========== STARTUP CONFIG APPLIED AS RUNNING ==========

**Expected behavior:**
All subscription should be successful and the concurrent access resolved by the sysrepo daemon. 

**Actual behavior:**
Some of the client get an error back. Multiple errors messages printed in the sysrepo daemon log (see attachment)

### Versions
Please provide versions for software needed to reproduce the bug:
Sysrepo version: `sysrepod -v`.
libyang version: `yanglint -v`
sysrepod - sysrepo daemon, version 0.7.4
yanglint 0.15.120
[sysrepod.log](https://github.com/sysrepo/sysrepo/files/2114420/sysrepod.log)

**Comment by michalvasko** [comment]
Hi,
they are just examples so do not expect too much. In these cases you should simply try again a bit later (if you receive `Resource already locked` error) and it should work. Perhaps the waiting could be added into *libsysrepo* itself, but this way you have more control over what is happening.

Regards,
Michal

**Comment by przemekr** [comment]
well, yes, I try to handle the error/exception in my application and re-try, however I am bit concerned about the errors printed by sysrepo daemon.

Also wouldn't it be better/faster to make the sysrepo server serialize the request which require exclusive access to datastore/model?

**Comment by michalvasko** [comment]
Hi,
I have examined this problem more and based on that I say that no, it seems it would not be better or faster, sorry. But, it may be improved in future.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi,
do you really mind those errors that much? If so, you can time those subscriptions so they do not block each other.

The model is blocked also when manipulating its data (but mostly only on commit, when the data is actually written).

Regards,
Michal

**Comment by przemekr** [comment]
Yes, I would prefer not to get any ERR messages in the system log files, during the normal operation. Having several sysrepo clients in the system will lead to some error severity messages at every system startup (which leads to 'ignore any errors reported by sysrepo' attitude). 

I did start the application with a 2s delay, but this will not scale up (image a system with 100 sysrepo clients).

**Comment by michalvasko** [comment]
Hi,
the messages have their purpose, otherwise you would know what is happening exactly. If you do not want them, you can always disable logging or define your own callback with whatever filtering you want.

Regards,
Michal
