### ISSUE TITLE
persistent timeout in call home scenarios (libnetconf2)

### ISSUE THREAD

**Issue by frimpler** [sysrepo/sysrepo#1188]
### Description
If you try to apply a call home configuration for multiple netconf clients which are not yet available (or due to network problems not reachable), the first 3-4 edit-configs do not show any problem (at the command line), but afterwards, no further client/endpoint can be added and the rpc reply gives time-out as reason. At this point the behaviour starts to become persistent, which means, not further client/endpoint can be added.

### Root Cause
This behaviour is caused by 
1. blocking connect calls, of course, plus...
2. writer starvation in connection with pthread_rwlock (readers are unfortunately preferred over writers!)
Btw.: that the first 3-4 edit-configs seem to work, does not be reflected the internal thread status, because the configuration call back for the second edit-config hangs on the rwlock, trying to "write".

### Details
"server_opts.ch_client_lock" is implemented as pthread_rwlock. The threads for the pending connects "read" the lock (for a "unspecified" time - as long as the connect blocks), but the configuration change call backs always want to "write" the lock, of course. 

### Possible Solution
please have a look at https://github.com/frimpler/libnetconf2/commit/08d0d4d6e9fa60ea1ba0ef17327b3f65e3004b28. This implementation does two things:
- introduction of a connect timeout in order to reduce the blocking time on call home sockets by "lock -readers" (I introduced 5sec for them)
- apply a non-portable attribute to the rwlock in order to avoid writer starvation.

### Drawbacks
From my point of view the possible solution has 3 drawbacks.
- after 5 seconds, the socket will be closed on the server host which might be a problem in slow networks
- the introduction of the connect timeout did show problems with IPv6 and has therefore be limited to IPv4 (I'm not sure, whether it worked for IPv6 before, at all(?))
- the prevention of writer-starvation is only possible using a non-portable attribute.

**Comment by michalvasko** [comment]
Hi Frank,
it makes sense, I have never encountered this problem testing on `localhost`, of course. Regarding your solution
 - Why is the issue in *sysrepo*? Never mind now, but please create issue in the correct projects next time.
 - For slow networks the timeout could be adjustable, so if you make it into a cmake variable, it should be fine.
 - What problems exactly for IPv6? I have connected over IPv6 before if that is what you are asking.
 - We have used the same attribute in *netopeer2* server and made it conditional in case the system does not support it. You can do the same.

Thanks for looking into it, anyway.

Regards,
Michal

**Comment by frimpler** [comment]
Hi Michal,
regarding the timeout value: I don't think, that someone should be bothered to set a timeout from outside (CMAKE variable) which has been introduced for internal reasons (blocking timeout) - there's anyway almost no range for it: less than 5 seconds would probably cause problems in the network and higher values might bring commit timers etc. to expiration. The better, but more complex solution would be, to store waiting sockets per endpoint. This is quite better from the networking perspective (you don't open a new socket for every 5 sec) and would be my choice.
Concerning IPv6 problems: I didn't dig deeper when I had to notice, that in the new non-blocking implementation the call of getaddrinfo() with AF_UNSPEC produced an IPv6 resource first, which in turn let the netopeer2-cli (ssh) connection fail. Therefore I decided to restrict it to AF_INET, which worked for my test (and our applications). I'm not sure, what is really required here.

Regards,
Frank

**Comment by michalvasko** [comment]
Hi Frank,
I know that IPv6 resources are put first but what is the problem with that? If it is configured properly, it will connect on IPv6, why not? You should find out why it is not working for you because if the TPC/IP connection is not established, another resource is used. Anyway, I cannot just disable IPv6 this way.

Regards,
Michal
