### ISSUE TITLE
Multiple SR_EV_VERIFY /SR_EV_APPLY for a single commit followed by "Requested resource is already locked" error

### ISSUE THREAD

**Issue by rosy8** [sysrepo/sysrepo#1189]
Hi,

Getting multiple SR_EV_VERIFY /SR_EV_APPLY for a single commit.

This looks quite strange to me.. Do feel its related to 
 https://github.com/sysrepo/sysrepo/issues/1133  . <b> (No NP commit context) </b>

 By looking at the log...what i hv observed  that for <b> ONE sr_commit </b> getting 
<b>TWO </b> times SR_EV_VERIFY  and SR_EV_APPLY  events  for the <b>same subscribed module.</b>

(<b> Note : NOT ALWAYS .. But SOMETIMES  </b> )

====>><b> sr_commit triggered.. </b>

===>><b>Module1</b> : Event[SR_EV_VERIFY]:return SR_ERR_OK   
          ( Hv not received the SR_EV_APPLY for this module yet.. and later do get SR_EV_ABORT event)

<b>Jun 20 12:32:26 sysrepod[17604]: [WRN] No NP commit context for commit ID 1865048665. </b>

===>><b> Module2 </b>: Event[SR_EV_VERIFY]:return SR_ERR_OK  <b> ==>> 1st time </b>
===>><b> Module2 </b>: Event[SR_EV_APPLY]:return SR_ERR_OK

............

Jun 20 12:35:31 netopeer2-server[17843]: Unlocking datastore candidate by session 50 failed (lock is not active).
===>><b> Module2</b> : Event[SR_EV_VERIFY]:return SR_ERR_OK  <b> ==>> 2nd time </b>
===>> <b>Module2 </b>: Event[SR_EV_APPLY]:return SR_ERR_OK

Jun 20 12:35:33 sysrepod[17604]: [ERR] Failed to lock ietf-interfaces in running ds
Jun 20 12:35:33 sysrepod[17604]: [ERR] Module ietf-interfaces can not be locked
Jun 20 12:35:33 sysrepod[17604]: [ERR] Loading of modified models failed
Jun 20 12:35:33 netopeer2-server[17843]: Error by processing of the commit request (session id=2009526864): <b>Requested resource is already locked.</b>  
Jun 20 12:35:33 netopeer2-server[17843]: Error by processing of commit request.
Jun 20 12:35:33 sysrepod[17604]: [ERR] Failed to lock ietf-interfaces in running ds
Jun 20 12:35:33 sysrepod[17604]: [ERR] Module ietf-interfaces can not be locked
Jun 20 12:35:33 sysrepod[17604]: [ERR] Loading of modified models failed
Jun 20 12:35:33 netopeer2-server[17843]: Error by processing of the commit request (session id=2009526864):<b> Requested resource is already locked.</b>
Jun 20 12:35:33 netopeer2-server[17843]: Error by processing of commit request.
......

<b>Jun 20 12:49:06 sysrepod[17604]: [ERR] Commit timeout for commit id=1865048665.
=======>>> sr_commit: FAILED  </b>
===>><b>Module1 </b>: Event[SR_EV_VERIFY]:return SR_ERR_OK  event ==<b> SR_EV_ABORT</b>

Not sure on what conditions its behaving like this..
Would appreciate if you could help me in someway.

Regard's
Rosy

**Comment by rosy8** [comment]
Hi Michal,

Any comment on this issue ..?

Regard's
Rosy

**Comment by vishalwc** [comment]
Observed the issue again  with same debug sequence as mentioned above

**Comment by rosy8** [comment]
Hi Michal,

Thank you very much for replying back.

Yeah..its difficult to reproduce the same scenario..
But there are multiple scenario which is causing in <b> "Requested resource is already locked" error.<b>

This scenario is different than the one which I had posted earlier but finally I am getting the same 
"Resource Locked error".
In this case I have not received multiple SR_EV_VERIFY/SR_EV_APPLY events .. rather  donot get the SR_EV_APPLY  after e returning  OK for event  SR_EV_VERIFY as shown below..

Which is later causing "resource locked" issue as show below..
=====================================================

 07:08:14  ** Module1_callback Notification verify 
 07:08:14  Event[verify]:return SR_ERR_OK
 07:08:14  sysrepod[2669]: [WRN] No NP commit context for commit ID 496891905.

                ======>>>>> Did not received the SR_EV_APPLY reply yet for Module1.

===>> Since user has already received reply "OK" for the  event "SR_EV_VERIFY" 
It triggers the 2nd commit  and from sysrepo we receives also the SR_EV_VERIFY/SR_EV_APPLY events
as shown below.....				

 07:08:20 ** Module2_callback Notification verify 
 07:08:20 Event[verify]:return SR_ERR_OK
 07:08:20 ** Module2_callback Notification apply 
 07:08:20 Event[apply]:return SR_ERR_OK

....
======>>>>> But  Did not received the SR_EV_APPLY reply yet for <b> Module1 </b> yet.

 07:08:26  sysrepod[2669]: [ERR] Failed to lock Module1 in running ds
 07:08:26  sysrepod[2669]: [ERR] Module Module1 can not be locked
 07:08:26  sysrepod[2669]: [ERR] Loading of modified models failed
 07:08:26  netopeer2-server[3232]: Error by processing of the commit request (session id=1092391360): <b>Requested resource is already locked </b>
 07:08:26  netopeer2-server[3232]: Error by processing of commit request.

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
I do not really have much to tell you, there are obviously some synchronization problems in *sysrepo*, but these are difficult to debug and there are currently other things we are working on. For now I can only suggest to retry the commit after you receive this error.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

Yeah do agree with you that therse is some synchronization/timing issue in sysrepo code.

Following is my understanding by looking at the code in which case it will fail to send the SR_EV_APPLY event even if subscriber has already returned OK for the SR_EV_VERIFY event..

 when sysrepo state machine is in "DM_COMMIT_NOTIFY_VERIFY" state, it sends the SR_EV_VERIFY events to the subscribed modules  and moves to a new state "DM_COMMIT_WAIT_FOR_NOTIFICATIONS" where it waits for the response from all the subscribed modules.

Once its gets the SR_ERR_OK response from all the subscribed modules, it moves to the next state "DM_COMMIT_WRITE" and then to the "DM_COMMIT_NOTIFY_APPLY" where it will again send SR_EV_APPLY events to its subscribed modules.

But in between  DM_COMMIT_NOTIFY_VERIFY and DM_COMMIT_WAIT_FOR_NOTIFICATIONS states, it does many other operations. (ex Creating a new NP commit context )

===>> Failure case (In case of edit-config in a single module)

1) DM_COMMIT_NOTIFY_VERIFY
It does send the SR_VERIFY notification to the subscribed module

But before the state machine moves to the DM_COMMIT_WAIT_FOR_NOTIFICATIONS  state, the response for the SR_EV_VERIFY from the subscriber is being received.
So to process further, sysrepo tries to get the commit context . (But in the failure case..by this time the commit context would not have been created)

So based on this the state machine does not move forward and hence it does not send the SR_EV_APPLY event.

[DBG] Processing commit request.
[DBG] Commit (1/10): process started
[DBG] Validation succeeded for 'ietf-interfaces' module
[DBG] Commit (2/10): validation succeeded
[DBG] Module 'ietf-interfaces' persist file version matches with cached value (1535694492718950608).
[DBG] Returning 0 subscriptions from 'ietf-interfaces' persist file cache.
[DBG] Module 'ietf-interfaces' persist file version matches with cached value (1535694492718950608).
[DBG] Returning 1 subscriptions from 'ietf-interfaces' persist file cache.
[DBG] Commit: In the session there are 1 / 3 modified models
[DBG] Commit (3/10): all modified models loaded successfully
[DBG] Commit (4/10): replay of operation succeeded
[DBG] Validation succeeded for 'ietf-interfaces' module
[DBG] Commit (5/10): merged models validation succeeded
[DBG] Commit (6/10): write access granted by NACM
[DBG] Sending verify notifications about the changes made in running datastore...
                                                              =>>Would hv got the OK resp for verify
[WRN] No NP commit context for commit ID 1511602950.  
[DBG] Thread id=140737316480768 will wait.
[DBG] Creating a new NP commit context for commit ID 1511602950.  
                                                              ==>still in DM_COMMIT_NOTIFY_VERIFY state
[DBG] Circular buffer enqueue to position=2, current count=1.
[DBG] New message enqueued into CM message queue.
[DBG] Circular buffer dequeue, new buffer head=3, count=0.
[DBG] Scheduling a delayed request for 1000.000000 seconds.
[DBG] Set up commit timeout for commit id=1511602950.
[DBG] Commit (7/10): verify phase done

        ==>> Moved to DM_COMMIT_WAIT_FOR_NOTIFICATIONS state..but it has already got the response from verifiers and it could not move forward because many required conditions does not get satisfied at that time. (ex -commit context was missing )

[DBG] Commit 1511602950 processing paused waiting for replies from verifiers
[DBG] Request paused, waiting for verifiers

 
Please let me know if I am missing something here.

Regards,
Rosy

**Comment by rosy8** [comment]
Hi Michal,

The best way to reproduce this issue is if you could send the reply for the  event SR_EV_VERIFY quickly. 
(But again it does not happen always )

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
what you are saying makes sense and I think you may find the exact problem (possibly with my help). So, based on what you said the problem is in `dm_commit_notify` called on `rp_dt_edit.c:905`. But looking at the function, the first step is preparing the diff (loop at line `5049`), then storing the commit context (line `5138`), and finally sending the notifications (`SR_EV_VERIFY` events) in a loop (line `5153`.

Seems to me the commit context is stored **before** any event is sent to a subscriber so it should be always found when needed, am I missing something?

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

As per my knowledge, I could see It creates the commit context inside func "np_commit_notif_cnt_increment" .

dm_commit_notify
        --------------------->>np_subscription_notify
                                                             -----------------------> np_commit_notif_cnt_incremennt.

state : DM_COMMIT_NOTIFY_VERIFY
=========>> Inside dm_commit_notify to process event(verify)
Sending verify notifications about the changes made in running datastore...
ms->difflist->type[d_cnt] : 4:
Match found !!


np_subscription_notify : event(0) commit ID 1890428272.
Sending module-change notification to '/var/run/sysrepo-subscriptions/XXX-config/3243.q6chOV.sock' @ 1165231074.
cm_session_start_internal : Starting a new session, options=1024.
New session created successfully, real user=root, effective user=(null), session id=821687495.
XXX_callback Notification verify 

np_commit_notif_cnt_increment:  commit ID 1890428272.
np_commit_ctx_find: Did not find commit context for commit Id 1890428272.
np_commit_notif_cnt_increment: Creating a new NP commit context for commit ID 1890428272.
....

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
you are right, I did not look into the functions themselves. I have tried to fix it by creating the context first in the referenced pull request, can you please try it out? Thanks.

Regards,
Michal
