### ISSUE TITLE
sysrepoctl module install with multiple search-dir doesn't work

### ISSUE THREAD

**Issue by vhuertas** [sysrepo/sysrepo#1196]
### How to submit issue
Please use this text as a template and replace text in the sections or remove
the entire section if that does not apply to your issue. For example in case of
question or feature request, just description with some example is probably
fine. Also remember to use github's markup form properly, especially in case of
output or code listing.

### Things you may try first
(put "x" in "[]" if you already tried following)
* [] Did you check if this is a duplicate issue?
* [] Did you test it on the latest sysrepo devel branch?

### Description
I try to install an openconfig yang module with multiples dependencies located in several directories. But it doesn't work at all. 

Thanks for your attention
Regards,

### Steps to Reproduce
1. [First Step]
I tried to issue this command:

### # sysrepoctl --install --yang=openconfig-interfaces.yang --search-dir=/home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/openconfig /home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/openconfig/interfaces /home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/openconfig/types /home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/openconfig/vlan /home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/ietf /home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/ietf/0.1.3/
/home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/ietf/0.1.5/

But it returns an error telling this:

[ERR] libyang: Opening file "openconfig-interfaces.yang" failed (No such file or directory).
Error: Unable to load the module by libyang.
Install operation failed.

2. [Second Step]

Then if I issue this command:
### # sysrepoctl --install --yang=/home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/openconfig/interfaces/openconfig-interfaces.yang --search-dir=/home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/openconfig /home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/openconfig/interfaces /home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/openconfig/types /home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/openconfig/vlan /home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/ietf /home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/ietf/0.1.3/ /home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/ietf/0.1.5/

Then it seems that the yang file is found. However it gives and error telling that the first imported module cannot be found.

The paths included are correct so I cannot understand why it does not locate the dependencies...

**Expected behavior:**
I was expecting to install openconfig-interfaces.yang and all its dependencies

**Actual behavior:**
 [What actually happened]

### Versions
Please provide versions for software needed to reproduce the bug:

sysrepoctl -v 0.7.4
yanglint -v 0.15.131

### Attachments
Please run sysrepo daemon in debug mode and write the logs to a file. For example:
`sysrepod -d -l 4 &> sysrepod.log`.

Similarly, if Netopeer2 server is used, also provide us with its log:
`netopeer2-server -d -v3 &> netopeer2-server.log` (optional)

You're also welcomed to provide us with any other data you think may be useful.
For example:
Installed modules: `sysrepoctl -l`
Content of datastore used: check files in  Sysrepo data directory (default `/etc/sysrepo/data`).

Thanks!

**Comment by michalvasko** [comment]
Hi,
`sysrepoctl` help says that you can specify the search dir multiple times so that is what you should do.
```
sysrepoctl --search-dir /search/dir/one --search-dir /search/dir/two --search-dir /search/dir/three
```

Regards,
Michal

**Comment by vhuertas** [comment]
Understood,

I thought that the --search-dir must be placed once and not all the times. If you could update the help text with an example it would be useful for a better understanding.

Thanks a lot. I will try it!

**Comment by michalvasko** [comment]
Hi,
I think the text is quite clear for people familiar with command-line arguments so it should be fine. You now also know the correct format so it can stay as it is.

Regards,
Michal

**Comment by vhuertas** [comment]
All right,

BTW, I have issued the modified command with no success. I paste the output...

root@cuda1:/home/cuda1/git/Netopeer2/server/build> sysrepoctl --install --yang openconfig-interfaces.yang --search-dir /home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/openconfig/interfaces/ --search-dir /home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/openconfig/ --search-dir /home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/openconfig/types/ --search-dir /home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/openconfig/vlan/ --search-dir /home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/ietf --search-dir /home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/ietf/0.1.3/ --search-dir /home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/ietf/0.1.5/
Installing a new module from file 'openconfig-interfaces.yang'...
[ERR] libyang: Opening file "openconfig-interfaces.yang" failed (No such file or directory).
Error: Unable to load the module by libyang.
Install operation failed.

It seems that the --search-dir is not being taken into account in order to find openconfig-interfaces.yang file...

Any idea of what I am missing?

Regards,

**Comment by michalvasko** [comment]
Yes, the `--yang` parameter is expected to be a full path to the installed schema. Search dirs are there only for imports.

Regards,
Michal

**Comment by vhuertas** [comment]
New update:
After issuing a small modification of the command it seems to work. The modification is that the path of the openconfig-interfaces.yang explicit path must be indicated in the "--yang" parameter. 

root@cuda1:/home/cuda1/git/Netopeer2/server/build> sysrepoctl --install --yang /home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/openconfig/interfaces/openconfig-interfaces.yang --search-dir /home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/openconfig/interfaces/ --search-dir /home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/openconfig/ --search-dir /home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/openconfig/types/ --search-dir /home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/openconfig/vlan/ --search-dir /home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/ietf --search-dir /home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/ietf/0.1.3/ --search-dir /home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/ietf/0.1.5/
Installing a new module from file '/home/cuda1/git/netconfQoSE/netconfQoSE/profiles/bundles/yang/openconfig/interfaces/openconfig-interfaces.yang'...
Installing the YANG file to '/etc/sysrepo/yang/openconfig-interfaces@2018-04-24.yang'...
Resolving dependency: 'openconfig-interfaces' imports 'ietf-interfaces'...
Installing the YANG file to '/etc/sysrepo/yang/ietf-interfaces@2014-05-08.yang'...
Resolving dependency: 'openconfig-interfaces' imports 'openconfig-yang-types'...
Installing the YANG file to '/etc/sysrepo/yang/openconfig-yang-types@2018-04-24.yang'...
Resolving dependency: 'openconfig-yang-types' imports 'openconfig-extensions'...
Installing the YANG file to '/etc/sysrepo/yang/openconfig-extensions@2017-04-11.yang'...
Resolving dependency: 'openconfig-interfaces' imports 'openconfig-types'...
Installing the YANG file to '/etc/sysrepo/yang/openconfig-types@2018-05-05.yang'...
Resolving dependency: 'openconfig-types' imports 'openconfig-extensions'...
Installing the YANG file to '/etc/sysrepo/yang/openconfig-extensions@2017-04-11.yang'...
Resolving dependency: 'openconfig-interfaces' imports 'openconfig-extensions'...
Installing the YANG file to '/etc/sysrepo/yang/openconfig-extensions@2017-04-11.yang'...
Installing data files for module 'openconfig-interfaces'...
Resolving dependency: 'openconfig-interfaces' imports 'ietf-interfaces'...
Skipping installation of data files for module 'ietf-interfaces'...
Resolving dependency: 'openconfig-interfaces' imports 'openconfig-yang-types'...
Skipping installation of data files for module 'openconfig-yang-types'...
Resolving dependency: 'openconfig-yang-types' imports 'openconfig-extensions'...
Skipping installation of data files for module 'openconfig-extensions'...
Resolving dependency: 'openconfig-interfaces' imports 'openconfig-types'...
Skipping installation of data files for module 'openconfig-types'...
Resolving dependency: 'openconfig-types' imports 'openconfig-extensions'...
Skipping installation of data files for module 'openconfig-extensions'...
Resolving dependency: 'openconfig-interfaces' imports 'openconfig-extensions'...
Skipping installation of data files for module 'openconfig-extensions'...
Notifying sysrepo about the change...
Install operation completed successfully.

However this is what "help" says regarding the search-dir.

-s, --search-dir       Directory to search for included/imported modules. **Defaults to the directory with the YANG file being installed**. (--install operation).
                         Can be specified multiple times.

It is not true that the search-dir sets the defaults to the directory where to find the yang file. This is only seems apply for the imported modules inside the main yang module. Am I right?

Regards,

**Comment by michalvasko** [comment]
You are reading information that is not there. Directory to search for included/imported modules defaults to the directory with the YANG file being installed. It does not say anything about the YANG file being installed itself. It must have the full path specified.

Regards,
Michal

**Comment by vhuertas** [comment]
OK,
I missunderstood the text then. Sorry for the inconvenience and thanks for your quick answer.

Regards,
