### ISSUE TITLE
Issue with sysrepo python API - error with dp_get_items_subscribe

### ISSUE THREAD

**Issue by abubakarmuqaddas** [sysrepo/sysrepo#1200]
Hi,

I am using the oven.yang model as an example to learn sysrepo. However I am using a custom python script, using the python API of sysrepo instead of the 'c' code for the oven example. I am using the docker sysrepo-netopeer2 image. I am having some issues 

Steps:

1. Installed the yang model: oven.yang using:
`sysrepoctl --install --yang=oven.yang`
2. Next, ran the python script to connect to sysrepo. This script is attached (script.txt).
```
root@f1926a3ef0f1:/workspace/server# python3 daemon2.py
```
3. Then, I followed the tutorial on [this page ](http://www.sysrepo.org/static/doc/html/start_page.html), to execute NETCONF commands using the netopeer2-cli:
```
root@f1926a3ef0f1:/workspace# netopeer2-cli
> connect --login=netop
Interactive SSH Authentication
Type your password:
Password:
>
```
4. I execute the following command to update 
`> get --filter-xpath /oven:*`

    This terminates the python script and gives the following error:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Python callback dp_get_items failed.
```
Please inform how this error can be avoided.
[oven.yang.txt](https://github.com/sysrepo/sysrepo/files/2155771/oven.yang.txt)
[script.txt](https://github.com/sysrepo/sysrepo/files/2155893/script.txt)

**Comment by mislavn** [comment]
Hi @abubakarmuqaddas ,

currently the documentation for language bindings is a bit lacking, we are working on it.

To fix your issue, change the oven_state_cb to:
```
def oven_state_cb(xpath, holder, private_ctx):
    print("\n\n ========== OVEN State queried ==========")
    values = holder.allocate(2)
    values.val(0).set('/oven:oven-state/temperature', 3, sr.SR_UINT8_T)
    values.val(1).set("/oven:oven-state/food-inside", True, sr.SR_BOOL_T)
    return sr.SR_ERR_OK
```

Regards,
Mislav

**Comment by abubakarmuqaddas** [comment]
Hi Mislav,

Thanks! It works fine now.

Regards,
Abubakar

**Comment by allena29** [comment]
** this comment is just anyone else arriving here from google ** 
I'm using sysrepo tag 0.7.7

Although this issue is closed I found that there are extra arguments passed into to oven_state_cb()

The following shows the extra things as:
  /oven:*//.
  None

 79 def oven_state_cb(xpath, holder, private_ctx, *args):
 80     print("\n\n ========== OVEN State queried ==========")
 81     for x in args:
 82         print(x)
