### ISSUE TITLE
The netopeer2-server can't startup, and seems it's caused by the sysrepod

### ISSUE THREAD

**Issue by darcyllingyan** [sysrepo/sysrepo#1202]
Hi,
I just install the sysrepo, netopeer2, libyang, libnetconf2 from devel branch.
The netopeer2-server can't be startup, after use the debug mode, following errors are reported for the netopeer2-server and sysrepod.

[root@cnet-netconf-c libyang]# netopeer2-server -d -v 3
VERBOSE: (sr_connect:435) Connected to daemon Sysrepo Engine at socket=/tmp/sysrepod.sock
VERBOSE: Netopeer2 connected to sysrepod.
VERBOSE: Plugin "/usr/local/lib64/libyang/extensions/libyang_ext_test.so" successfully loaded.
VERBOSE: Plugin "/usr/local/lib64/libyang/extensions/yangdata.so" successfully loaded.
VERBOSE: Plugin "/usr/local/lib64/libyang/extensions/nacm.so" successfully loaded.
VERBOSE: Plugin "/usr/local/lib64/libyang/extensions/metadata.so" successfully loaded.
VERBOSE: Plugin "/usr/local/lib64/libyang/user_types/user_date_and_time.so" successfully loaded.
VERBOSE: Reading module "ietf-yang-metadata".
VERBOSE: Module "ietf-yang-metadata@2016-08-05" successfully parsed as implemented.
VERBOSE: Reading module "yang".
VERBOSE: Resolving "yang" unresolved schema nodes and their constraints...
VERBOSE: All "yang" schema nodes and constraints resolved.
VERBOSE: Module "yang@2017-02-20" successfully parsed as implemented.
VERBOSE: Reading module "ietf-inet-types".
VERBOSE: Resolving derived type "union" failed, it will be attempted later.
VERBOSE: Resolving derived type "union" failed, it will be attempted later.
VERBOSE: Resolving derived type "union" failed, it will be attempted later.
VERBOSE: Resolving derived type "union" failed, it will be attempted later.
VERBOSE: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
VERBOSE: All "ietf-inet-types" schema nodes and constraints resolved.
VERBOSE: Module "ietf-inet-types@2013-07-15" successfully parsed as implemented.
VERBOSE: Reading module "ietf-yang-types".
VERBOSE: Module "ietf-yang-types@2013-07-15" successfully parsed as implemented.
VERBOSE: Reading module "ietf-datastores".
VERBOSE: Module "ietf-datastores@2017-08-17" successfully parsed as implemented.
VERBOSE: Reading module "ietf-yang-library".
VERBOSE: Module "ietf-yang-library@2018-01-17" successfully parsed as implemented.
VERBOSE: Loading schema "swig-test-cpp-changes@2017-03-09" from sysrepo.
VERBOSE: Reading module "swig-test-cpp-changes".
VERBOSE: Module "swig-test-cpp-changes@2017-03-09" successfully parsed as implemented.
VERBOSE: Loading schema "swig-test-cpp-operations@2017-03-09" from sysrepo.
VERBOSE: Reading module "swig-test-cpp-operations".
VERBOSE: Module "swig-test-cpp-operations@2017-03-09" successfully parsed as implemented.
VERBOSE: Loading schema "md_test_module-A" from sysrepo.
ERROR: (cl_message_recv:211) Sysrepo server disconnected.
ERROR: (cl_request_process:512) Unable to receive the message with response (session id=1799477158, operation=get-schema).
ERROR: (sr_get_schema:835) Error by processing of the request.
ERROR: (cl_message_send:170) Error by sending of the message: Broken pipe.
ERROR: (cl_request_process:501) Unable to send the message with request (session id=1799477158, operation=session-check).
ERROR: (sr_session_check:647) Error by processing of the request.
ERROR: (cl_message_send:170) Error by sending of the message: Broken pipe.
ERROR: (cl_request_process:501) Unable to send the message with request (session id=1799477158, operation=unsubscribe).
ERROR: (cl_subscription_close:233) Error by processing of the request.
ERROR: (sr_unsubscribe:2845) Error by closing of the subscription: The peer disconnected.
ERROR: (cl_message_send:170) Error by sending of the message: Broken pipe.
ERROR: (cl_request_process:501) Unable to send the message with request (session id=1799477158, operation=unsubscribe).
ERROR: (cl_subscription_close:233) Error by processing of the request.
VERBOSE: (cl_sm_cleanup:1796) Client Subscription Manager successfully destroyed.
ERROR: (sr_unsubscribe:2845) Error by closing of the subscription: The peer disconnected.
VERBOSE: (sr_connect:402) Sysrepo daemon has been started.
ERROR: nc_ps_get_session: invalid argument (ps).
ERROR: (cl_message_send:170) Error by sending of the message: Bad file descriptor.
ERROR: (cl_request_process:501) Unable to send the message with request (session id=16130160, operation=get-schema).

With the sysrepod reports the following error:
[root@cnet-netconf-c sysrepo]# sysrepod -d -l3
[INF] (dm_init:2224) Initializing Data Manager, schema_search_dir=/root/sysrepo/build/repository/yang/, data_search_dir=/root/sysrepo/build/repository/data/
[INF] (main:133) Sysrepo daemon initialized successfully.
[INF] (sm_session_create:474) New session created successfully, real user=root, effective user=(null), session id=1799477158.
[INF] (dm_get_schema:3312) Get schema 'swig-test-cpp-changes', revision: '2017-03-09', submodule: '(null)', submodule revision: '(null)'
[INF] (dm_get_schema:3312) Get schema 'swig-test-cpp-operations', revision: '2017-03-09', submodule: '(null)', submodule revision: '(null)'
[INF] (dm_get_schema:3312) Get schema 'md_test_module-A', revision: '(null)', submodule: '(null)', submodule revision: '(null)'
[ERR] (dm_ly_log_cb:1571) libyang error: Opening file "/root/sysrepo/build/repository/yang/md_test_module-A.yang" failed (No such file or directory).
[WRN] (dm_load_schema_file:1099) Unable to parse a schema file: /root/sysrepo/build/repository/yang/md_test_module-A.yang
Segmentation fault

I can't find the file /root/sysrepo/build/repository/yang/md_test_module-A.yang, whether there is some problem about my installation?

The sysrepo version:
[root@cnet-netconf-c sysrepo]# sysrepod -v
sysrepod - sysrepo daemon, version 0.7.4

netopeer2 version"
[root@cnet-netconf-c sysrepo]# netopeer2-server -V
netopeer2-server 0.5.27
compile time: Jul  2 2018, 06:12:27

libyang version:
[root@cnet-netconf-c sysrepo]# yanglint -v
yanglint 0.15.136

Thanks!
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
there most certainly is a problem with your installation, it got corrupted somehow. Best would be to remove the whole `/root/sysrepo/build/*` and then compile and install it again.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Michal,
Thanks very much for the quick response! after compile and install it again, the issue is solved.
But when I connect to the netopeer2-server with netopeer2-cli, it reports the error "ERROR: Module "ietf-netconf-acm@2018-02-14" is supposed to be imported, but no other module imports it.", after check the similar issue #291,  I willdownload the newest netopeer2-server version for the "server TEST update nacm module" and re-connect again. Thanks!

[root@cnet-netconf-c ~]# netopeer2-cli
> version
Netopeer2 CLI 2.0.48
Compile time: Jul  3 2018, 09:22:53
> connect
Interactive SSH Authentication
Type your password:
Password: 
nc ERROR: Module "ietf-netconf-acm@2018-02-14" is supposed to be imported, but no other module imports it.
cmd_connect: Connecting to the localhost:830 as user "root" failed.

Thanks
Darcy

**Comment by darcyllingyan** [comment]
Hi Michal,
Yeah, thanks for the support. Now the issue is fixed.

Thanks
Darcy
