### ISSUE TITLE
candidate and startup datastore capabilities

### ISSUE THREAD

**Issue by feldi59** [sysrepo/sysrepo#1204]
Hi developers,

some (more and more) of our customers are asking for Netconf/Yang support.
We  think about using your excellent implemention within our existing projects.

Our current projects use SNMP, Web and proprietary CLI interfaces for network configuration and management.
Within our software there is currently no concept for the startup and candidate datastores.
There is just the running datastore and a factory-reset datastore.

so we have some questions (hope its the right place here ...)

- is it possible to disable the candidate and startup capability features ?

- is there a way to get callback notifications if anyone wants to write to the startup datastore ?
There must be a way besides the constraints defined in yang to reject entries directly made to the startup datastore. 

I have read your sysrepo User and Developer Guides, but i did only find callbacks for the running datastore (using subscriptions). Or what do i understand wrong ?

Many thanks for your reply in advance and best regards
Martin

**Comment by michalvasko** [comment]
Hi,
it is not possible to disable neither `candidate` nor `startup`. However, you do not need to worry about `candidate`, it is basically just a *sysrepo* (NETCONF) feature not connected to any sysrepo applications, it is completely transparent for them.

Not supporting `startup` is more difficult. Unfortunately, it is not possible to define callbacks for `startup` or reject those configuration changes (we were thinking about it, we will see what can be done in future). But, one solution would be for the `startup` datastore to always mirror `running`. In specific terms, call `copy-config` from `running` to `startup` on every configuration change.

Regards,
Michal
