### ISSUE TITLE
Issue with event notifications using sysrepo Python API

### ISSUE THREAD

**Issue by abubakarmuqaddas** [sysrepo/sysrepo#1205]
Hi,

I am using the oven.yang model as an example to learn sysrepo, with a python script using the python API of sysrepo. I am using the docker sysrepo-netopeer2 image. I am having issue with generating event notifications from the script:

Steps:

1. Installed the yang model: oven.yang using:
`sysrepoctl --install --yang=oven.yang`
2. Next, ran the python script to connect to sysrepo. This script is attached (script.txt).
```
root@f1926a3ef0f1:/workspace/server# python3 daemon2.py
```
3. Then, I followed the tutorial on [this page ](http://www.sysrepo.org/static/doc/html/start_page.html), to execute NETCONF commands using the netopeer2-cli:
```
root@f1926a3ef0f1:/workspace# netopeer2-cli
> connect --login=netop
Interactive SSH Authentication
Type your password:
Password:
>
```
4. I execute the following command to subscribe to the notification
```
> subscribe --filter-xpath /oven:oven-ready
OK
```
5. Then I edit the running config with the following call:
`edit-config --target running --config`
and insert the content:
```
<oven xmlns="urn:sysrepo:oven">
    <turned-on>true</turned-on>
    <temperature>200</temperature>
</oven>
```
6. This function `module_change_cb` generates the event notification. However there is an error with the inputs of the the function:
```
Wrong number or type of arguments for overloaded function 'Session_event_notif_send'.
  Possible C/C++ prototypes are:
    Session::event_notif_send(char const *,std::shared_ptr< Vals >,sr_ev_notif_flag_t const)
    Session::event_notif_send(char const *,std::shared_ptr< Vals >)
    Session::event_notif_send(char const *,std::shared_ptr< Trees >,sr_ev_notif_flag_t const)
    Session::event_notif_send(char const *,std::shared_ptr< Trees >)
```
I think the following call seems correct:
`sess.event_notif_send(sess, "/oven:oven-ready", None, 0, sr.SR_EV_NOTIF_DEFAULT)`

Please inform what can be the issue.

[oven.yang.txt](https://github.com/sysrepo/sysrepo/files/2155771/oven.yang.txt)
[script.txt](https://github.com/sysrepo/sysrepo/files/2159509/script.txt)

**Comment by mislavn** [comment]
Hi,

replace
```
sess.event_notif_send(sess, "/oven:oven-ready", None, 0, sr.SR_EV_NOTIF_DEFAULT)
```

with:

```
values = sr.Vals(0)
sess.event_notif_send("/oven:oven-ready", values, sr.SR_EV_NOTIF_DEFAULT)
```

SWIG generates the Python bindings based on C++ bindings, so until the documentation is done I would advise you to take a look at the C++ headers and examples.

```
    void event_notif_send(const char *xpath, S_Vals values, const sr_ev_notif_flag_t options = SR_EV_NOTIF_DEFAULT);
    void event_notif_send(const char *xpath, S_Trees trees, const sr_ev_notif_flag_t options = SR_EV_NOTIF_DEFAULT);
```

**Comment by abubakarmuqaddas** [comment]
Hi Mislav,

Thanks, it works.

Regards
Abubakar
