### ISSUE TITLE
Cannot subscribe to RPCs

### ISSUE THREAD

**Issue by rjarry** [sysrepo/sysrepo#1208]
Hi,

I get an error when subscribing to rpc invocations (RPC_SUBS).

```
root@localhost:~# sysrepoctl -i --yang=example.yang
```

```c
res = sr_rpc_subscribe(session, "/example:do-it", cb, priv, opts, &subs);
```

```
Jul 04 13:39:15 ubuntu1604 sysrepod[8295]: [ERR] Cannot copy module 'example', it is not enabled.
Jul 04 13:39:15 ubuntu1604 sysrepod[8295]: [ERR] Unable to enable the module in the running datastore.
```

Here is the YANG module:

```
module example {
  rpc do-it {
    input {
      leaf args {
        type string;
      }
    }
    output {
      leaf result {
        type int8;
      }
    }
  }
}
```

After looking at the code, it seems that sysrepo is considering that a yang module that has no data nodes, cannot be "enabled".

If I add a dummy data node in the module, it goes a bit further but I get another error:

```
Jul 04 15:18:59 ubuntu1604 sysrepod[8288]: [ERR] libyang error: When condition "../type = 'module-change' or ../type = 'subtree-change' or ../type = 'dp-get-items'" not satisfied.
Jul 04 15:18:59 ubuntu1604 sysrepod[8288]: [ERR] Parsing persist data from file '/etc/sysrepo/data/example.persist' failed: When condition "../type = 'module-change' or ../type = 'subtree-change' or ../type = 'dp-get-items'" not satisfied.
Jul 04 15:18:59 ubuntu1604 sysrepod[8288]: [ERR] Unable to load persist data tree for module 'example'.
Jul 04 15:18:59 ubuntu1604 sysrepod[8288]: [ERR] Unable to save the subscription into persistent data file.
```

I looked in the file, I have the subscription registered:

```xml
<module xmlns="urn:ietf:params:xml:ns:yang:sysrepo-persistent-data">
  <name>example</name>
  <subscriptions>
    <subscription>
      <type>rpc</type>
      <destination-address>/var/run/sysrepo-subscriptions/example/8306.example.18580.sock</destination-address>
      <destination-id>18580</destination-id>
      <enable-running/>
      <xpath>/example:do-it</xpath>
      <api-variant>values</api-variant>
    </subscription>
  </subscriptions>
</module>
```

I don't know if the `sysrepo-persistent-data.yang` model is incorrect or if `<enable-running/>` should not be here.

**Comment by michalvasko** [comment]
Hi,
I have successfully subscribed to an RPC in a model without any other data nodes, just that RPC. It should work, so you can try to reinstall sysrepo or at least the model `example` and retry the subscription. Also, I remember fixing this issue quite a long time ago so always make sure you have up-to-date software.

Regards,
Michal

**Comment by rjarry** [comment]
Hi,

Ok sorry, I thought a simple example would be enough. Our setup uses a base module which is "augmented" by other modules, but the "root" module of our data tree remains the base module. All other modules only define data nodes inside `agument` statements. 

If I define rpcs in these other modules, I cannot subsribe to them because sysrepo gives this error:

```
Jul 04 13:39:15 ubuntu1604 sysrepod[8295]: [ERR] Cannot copy module 'my-other-module', it is not enabled.
Jul 04 13:39:15 ubuntu1604 sysrepod[8295]: [ERR] Unable to enable the module in the running datastore.
```

When I define rpcs in the root module that defines data nodes, it works well.

I am unfortunately not able to share the details of these modules here but I can send them to you via email if you want.

**Comment by michalvasko** [comment]
Hi,
then please send them to me because I have tried it with
```yang
module main {
    namespace "test:main";
    prefix mn;

    container maincont {
        leaf ref {
            type string;
        }
    }
}
```
and
```yang
module aug {
    namespace "test:aug";
    prefix ag;

    import main {
        prefix mn;
    }

    augment "/mn:maincont" {
        leaf augleaf {
            type string;
        }
    }

    rpc rpc5;
}
```
and I successfully subscribed to `rpc5`.

Regards,
Michal
