### ISSUE TITLE
C++: unexpected error of regex pattern in mac_address leaf in openconfig-if-ethernet

### ISSUE THREAD

**Issue by vhuertas** [sysrepo/sysrepo#1220]
### How to submit issue
Please use this text as a template and replace text in the sections or remove
the entire section if that does not apply to your issue. For example in case of
question or feature request, just description with some example is probably
fine. Also remember to use github's markup form properly, especially in case of
output or code listing.

### Things you may try first
(put "x" in "[]" if you already tried following)
* [] Did you check if this is a duplicate issue?
* [] Did you test it on the latest sysrepo devel branch?

### Description
I have successfully installed openconfig-interface yang models with all the imports using sysrepoctl. I run sysrepod as well as netopeer2-server and everything seems to go perfect.  However, I'm stuck in an apparently strange  issue. 
I am developing an application that must initialize the datastore with the ethernet interfaces that automatically detects at starting up. As the datastore is empty, I tried to initialize it using sr_set_item_str function.
Everything seems to go well (all leaves are apparently correctly initialized as the returned value of such function is always SR_ERR_OK) until I try to set the value of mac_address. According to this leaf (imported from openconfig-yang-types), there is a pattern regex expression that must be fulfilled: 

typedef mac-address {
    type string {
      pattern '^[0-9a-fA-F]{2}(:[0-9a-fA-F]{2}){5}$';
    }
    description
      "An IEEE 802 MAC address";
  }

Then, when I try to set the string with a MAC address like this: "D0:53:49:53:32:EB", the sysrepod traces show an error telling that, according to libyang, the patern is not fulfilled.

I have checked it manually using on-line regex validators and the MAC address is matched. So I Assume that everything is OK.

What is happening here? Any idea why such a simple regex expression is not being fulfilled? Is it a sysrepo issue or a libyang issue?

Thanks

### Steps to Reproduce
1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:**
 To initialize mac_address with a string like "D0:53:49:53:32:EB" using sr_set_items_str.

**Actual behavior:**
An regex pattern error is given.

### Versions
 I git-cloned (master), correctlyl built  sysrepo, netopeer2-server and libyang about 15 days ago so I assume that the software versions are quite new.

### Attachments
Please run sysrepo daemon in debug mode and write the logs to a file. For example:
`sysrepod -d -l 4 &> sysrepod.log`.

Similarly, if Netopeer2 server is used, also provide us with its log:
`netopeer2-server -d -v3 &> netopeer2-server.log` (optional)

You're also welcomed to provide us with any other data you think may be useful.
For example:
Installed modules: `sysrepoctl -l`
Content of datastore used: check files in  Sysrepo data directory (default `/etc/sysrepo/data`).

Thanks!

**Comment by michalvasko** [comment]
Hi,
to answer you formally, the pattern is wrong because it expects a '$' at the end of every value that should match (`$` is a normal character as seen [here](https://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#regexs)). To actually explain the problem, just look at the **note** at the beginning of the text I referenced. In YANG, you do not need to anchor strings as they are by default. So, the pattern should be without `^` and `$` to be fully correct.

Also, to test regexes you can use `yangre`, a small utility shipped with *libyang*. If you do `yangre -f re` with `re` file content
```
'^[0-9a-fA-F]{2}(:[0-9a-fA-F]{2}){5}$'

D0:53:49:53:32:EB

```
it will not match. However, if you add `$` at the end of the value, it will.

Regards,
Michal

**Comment by vhuertas** [comment]
Thanks for your quick answer.
So there are two options to solve this issue:

1. modify the openconfig-yang-types.yang file to remove the $ character in the 'pattern'. Then reinstall all the openconfig yang modules using sysrepoctl (and cross fingers that everything works well)

2. insert in the mac-addr string the $ and take it into account in order to remove it whenever I want to use the data of the leaf and avoid misunderstandings.

Anyway, it is a pitty that some openconfig models shows such an incompatibility with some yang tools like libyang. I hope it is solved someday.

Regards,

**Comment by michalvasko** [comment]
Yeah, that would be the solution but I would definitely go for 1. You can report this as a bug to them, if no one has already, which may speed up fixing it.

Regards,
Michal

**Comment by vhuertas** [comment]
Thanks Michal!
