### ISSUE TITLE
when uninstall a mod, netopeer2-server crash!

### ISSUE THREAD

**Issue by zjbdamo** [sysrepo/sysrepo#1230]
### Things you may try first
(put "x" in "[]" if you already tried following)
* [X] Did you check if this is a duplicate issue?
* [X] Did you test it on the latest sysrepo devel branch?

### Description
if mod-b import mod-a and only install mod-b,the mod-a will automatically installed and marked IMPORT by netopeer2-server. when uninstall mod-b. the mod-a is also uninstalled by server.but sysrepo will notify mod-a is uninstalled. so server crash.
reference to  https://github.com/sysrepo/sysrepo/pull/1229  and https://github.com/CESNET/Netopeer2/pull/294 

i change the notify code(function rp_module_install_req_process) this will reduce some unwanted notify. but there are many test case code(cl_test.c) need change,so the PR is refused. i have not many time to change the test case code and i have not the complete test environment to verify the test case change .  so i create this issue to report this problem.

### Steps to Reproduce
1. install mod-b
2. uninstall mod-b

**Actual behavior:**
netpeer2-svr crash!

### Versions
sysrepod - sysrepo daemon, version 0.7.3
yanglint 0.14.78

**Comment by michalvasko** [comment]
Hi,
based on my understanding it works with the latest *netopeer2-server*, right? I have committed a fix. Please, use latest `master` or  `devel` branches, your versions are old.

Regards,
Michal
