### ISSUE TITLE
sr_dp_get_items_subscribe callback for "/ietf-interfaces:interfaces-state/interface" doesn't provide the name of the interfaces

### ISSUE THREAD

**Issue by vhuertas** [sysrepo/sysrepo#1231]
### How to submit issue
Please use this text as a template and replace text in the sections or remove
the entire section if that does not apply to your issue. For example in case of
question or feature request, just description with some example is probably
fine. Also remember to use github's markup form properly, especially in case of
output or code listing.

### Things you may try first
(put "x" in "[]" if you already tried following)
* [X] Did you check if this is a duplicate issue?
* [] Did you test it on the latest sysrepo devel branch?

### Description
I have developed a C++ application where I subscribe to the ietf-interfaces yand module using the sr_dp_get_items_subscribe function.

When I run the following netopeer2-cli command:
```
get --filter-xpath=/ietf-interfaces:interfaces-state/interface[name='eth0']/*
```

the callback function is called. However the xpath returned is: 
"/ietf-interfaces:interfaces-state/interface"

Even when I run the netopeer2-cli command:
```
get --filter-subtree=/tmp/ethfilter.xml
```

where the ethfilter.xml has the following content:
```xml
<interfaces-state xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interface>
    <name>eth0</name>
  </interface>
  <interface>
    <name>eth1</name>
  </interface>
</interfaces-state>
```
The callback function is called two times but each of them the xpath given as parameter is;
"/ietf-interfaces:interfaces-state/interface"

So it is not possible to know for which interfaces the operation state is being requested.
The running config has two interfaces configured: eth0 and eth1 . That is, the configured tree is "/ietf-interfaces:interfaces/interface".

The "/ietf-interfaces:interfaces-state/interface", as it is supposed to be requested by demand and cannot be configured ("config=false") it is empty in the datastore.

### Steps to Reproduce
1. run the C++ application with a simple sr_dp_get_items_subscribe use case is being tested. The xpath filter to subscribe is "/ietf-interfaces:interfaces-state/interface"
2. run the netopeer2-cli command get --filter-xpath=/ietf-interfaces:interfaces-state/interface[name='eth0']/*
3. print the xpath received by the function called back.

**Expected behavior:**
The xpath returned should indicate the name of the interface from which we want to retrieve the state.

**Actual behavior:**
 [What actually happened]
the xpath returned is always the same : "/ietf-interfaces:interfaces-state/interface"

### Versions
Please provide versions for software needed to reproduce the bug:
Sysrepo version: 0.7.4.
libyang version: 0.15.131
netopeer2-server: 0.5.27

### Attachments
Sysrepod logs when issuing the netopeer2-cli command: get --filter-xpath=/ietf-interfaces:interfaces-state/interface[name='eth0']/*
```
DBG] Sending 144 bytes of data.
[DBG] 144 bytes of data sent.
[DBG] Circular buffer dequeue, new buffer head=0, count=0.
[DBG] Scheduling a delayed request for 2.000000 seconds.
[DBG] fd 12 readable (revents 1)
[DBG] 71 bytes of data received on fd 12
[DBG] fd 12 would block
[DBG] New message of size 67 bytes received.
[DBG] Circular buffer enqueue to position=5, current count=1.
[DBG] Threads: active=0/4, 1 requests in queue
[DBG] Thread id=139698841478912 signaled.
[DBG] Circular buffer dequeue, new buffer head=6, count=0.
[DBG] Data provide response received, waiting for 0 more data providers.
[DBG] Module ietf-interfaces already loaded
[DBG] Found match for statistics with depth 1 index 0
[DBG] Found match for ipv4 with depth 1 index 0
[DBG] Found match for ipv6 with depth 1 index 0
[DBG] All data from data providers has been received session id = 1145631721, re-enqueue the request id = 95
[DBG] Circular buffer enqueue to position=6, current count=1.
[DBG] Threads: active=1/4, 1 requests in queue
[DBG] Circular buffer dequeue, new buffer head=7, count=0.
[DBG] Processing get_items request.
[INF] Get items request running datastore, xpath: /ietf-interfaces:interfaces-state/interface[name='eth0']/*//., offset: 0, limit: 100
[DBG] Session id = 1145631721 data loaded, continue processing
[DBG] Module ietf-interfaces already loaded
[DBG] Get_nodes opts with args: /ietf-interfaces:interfaces-state/interface[name='eth0']/*//. 100 0
[DBG] Circular buffer enqueue to position=0, current count=1.
[DBG] Thread id=139698841478912 will wait.
[DBG] New message enqueued into CM message queue.
[DBG] Circular buffer dequeue, new buffer head=1, count=0.
[DBG] Sending 27 bytes of data.
[DBG] 27 bytes of data sent.
[DBG] Circular buffer enqueue to position=7, current count=1.
[DBG] Threads: active=0/4, 1 requests in queue
[DBG] Delayed request sent to the Request Processor.
[DBG] Thread id=139698849871616 signaled.
[DBG] Circular buffer dequeue, new buffer head=8, count=0.
[DBG] Processing oper-data-timeout request.
[DBG] Thread id=139698849871616 will wait.
```

Thanks!

**Comment by vhuertas** [comment]
Sorry, I include the content of the ethfilter.xml as in the previous post was not displayed:
 ```
<interfaces-state` xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
 <interface>
    <name>eth0</name>
  </interface>
  <interface>
    <name>eth1</name>
  </interface>
</interfaces-state>
```

**Comment by michalvasko** [comment]
Hi,
this is more of a feature than a bug, look at the [docs](http://www.sysrepo.org/static/doc/html/subscribtions.html#stateDataStructure). Also, it sort-of duplicates #885.

Regards,
Michal

**Comment by jjin62** [comment]
this commit should be helpful??
https://github.com/sysrepo/sysrepo/commit/9ca3462440cc6c419105743d97637c0011141570
