### ISSUE TITLE
Getting SR_ERR_OK for verify/apply event after the rpc error reply "Timeout has expired"  for a commit operation

### ISSUE THREAD

**Issue by rosy8** [sysrepo/sysrepo#1232]
Hi Michal,

In one of the config commit, netopeer server is replying error messge "Timeout has expired" / Error by processing of the commit.  But  after that in the debuglog I still get  SR_ERR_OK for  SR_EV_VERIFY  and SR_EV_APPLY events as shown below..

<b>RPC-Messges:-</b>

`<?xml version="1.0" encoding="UTF-8"?><rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="2"><commit/></rpc>`

```
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="2">
<rpc-error>
<error-type>application</error-type>
<error-tag>operation-failed</error-tag>
<error-severity>error</error-severity>
<b><error-message xml:lang="en">Timeout has expired</error-message></b>
</rpc-error></rpc-reply>
```

<b>Snippet of log message -</b>

Module_callback Notification SR_EV_VERIFY 
................                                     
<b> netopeer2-server[6799]: While waiting for a response, timeout has expired.  </b>
 netopeer2-server[6799]: Unable to receive the message with response (session id=1167836292, operation=commit).
<b> netopeer2-server[6799]: Error by processing of commit request.</b>
....
<b> But after the timeout error message, I  still do get  SR_ERR_OK for both verify and apply events as shown below ..</b>
       
Module_callback Event == SR_EV_VERIFY :  return SR_ERR_OK
Module_callback Event == SR_EV_APPLY :  return SR_ERR_OK

<b> ====>> And later do get Malformed message as shown below. </b>
..............
netopeer2-server[6799]: Malformed message with response received (session id=1167836292, operation=delete-item).  
netopeer2-server[6799]: Error by processing of the request.

If there is error in the processing of the commit then why sysrepo still continues to processes the events..?
Would appreciate if you could suggest me how to avoid this issue ..
Thanks in advance.

Regards,
Rosy

**Comment by rosy8** [comment]
Hi,

By looking at the sysrepo code..what I could see that..

sr_commit{

  ===>>
     /* send the request and receive the response */
    rc = cl_request_process(session, msg_req, &msg_resp, NULL, SR__OPERATION__COMMIT);
    if ((SR_ERR_OK != rc) && (SR_ERR_OPERATION_FAILED != rc) && (SR_ERR_VALIDATION_FAILED != rc) &&
        (SR_ERR_UNAUTHORIZED != rc)) {
        <b>SR_LOG_ERR_MSG("Error by processing of commit request."); </b>
        goto cleanup;
    }
}

Inside function cl_request_process(),
--rpc req msg is sent and it waits for the response from sysrepo.. then..

  /* receive the response */
    rc = cl_message_recv(session->conn_ctx, msg_resp, sr_mem_resp);
    if (SR_ERR_OK != rc) {
       <b> SR_LOG_ERR("Unable to receive the message with response (session id=%"PRIu32", operation=%s).",</b>
                session->id, sr_gpb_operation_name(msg_req->request->operation));
        pthread_mutex_unlock(&session->conn_ctx->lock);
        return rc;
    }
===>>
Inside  cl_message_recv ()
{
.........
            if (EAGAIN == errno || EWOULDBLOCK == errno) {
              <b>  SR_LOG_ERR_MSG("While waiting for a response, timeout has expired."); </b>
                return SR_ERR_TIME_OUT;
            }

....
}

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
it seems you have quite a long commit, what are the changes in it? The simple solution is to increase commit timeout (`-DREQUEST_TIMEOUT=15` is 15 seconds by default) but there may be a better way because a commit should not take that long.

Regards,
Michal
