### ISSUE TITLE
Error executing cmake - SYSREPO installation

### ISSUE THREAD

**Issue by ManuVarela** [sysrepo/sysrepo#1235]
hi

When I try to execute the CMAKE command to install SYSREPO, it doesn't finish properly its execution and I get some errors related to some 
[CMakeError.log](https://github.com/sysrepo/sysrepo/files/2213115/CMakeError.log)
[CMakeOutput.log](https://github.com/sysrepo/sysrepo/files/2213116/CMakeOutput.log)

functions CMAKE is not able to find.

PFA the log files.

Could you please help me?

Thanks in advance,
Regards

**Comment by michalvasko** [comment]
Hi,
I see no fatal error, the missing functions are not mandatory so compilation should work. If it does not, can you please provide the standard output of `cmake`? Not these verbose logs.

Regards,
Michal
