### ISSUE TITLE
Query:  Rollback of configurations stored at Sysrepo on failure while applying configuration at application 

### ISSUE THREAD

**Issue by ykumar-rb** [sysrepo/sysrepo#1239]
### Description
Way to auto-rollback configurations stored in sysrepo database if application failed to apply the configurations received as part of model change events

#### Problem Statement

 In case model change events received to application loaded the model. Assume application failed to apply the configuration due to certain internal application error.
1. How application can trigger auto-rollback implicitly to clear the non-applied configuration from Sysrepo database?.
2. Then application can use event notification mechanism to notify user about auto-rollback performed due to failure in applying configuration.

     **Note:** Point-1 is unknown/query.  Though, I have achieved Point-2

Thanks!

**Comment by michalvasko** [comment]
Hi,
by a design decision this is not possible. After you return `0` for `SR_EV_VERIFY` you cannot refuse the changes and must apply them in `SR_EV_APPLY`. We know there are corner cases when you may need to refuse the changes in apply phase but these are simply not covered by *sysrepo*.

Regards,
Michal

**Comment by ykumar-rb** [comment]
Thanks for quick response.  If we think rollback in perspective of application, we need such mechanism to rollout the stored configuration at Sysrepo Database. I was curious if you have any thoughts around it with minimal feature enhancement at Sysrepo.

**Comment by michalvasko** [comment]
Technically, nothing prevents you from setting the old value back, for *sysrepo* it will be a standard configuration change and you can ignore it in your callback. However, as simple as it may seem, I think the implementation would not be simple at all so you must decide whether it is worth it to add this feature or rather to try to make sure you do not need to do this and perform all possible checks during the verify phase.

Regards,
Michal

**Comment by ykumar-rb** [comment]
Yeah to summarise above points. We can do these:
1. Add all relevant checks at verification phase.
2. If still configuration seems OK and model change event reaches application. In case of application internal failure , optionally ignore all the config changes received and trigger manual rollback(edit config with old values) at Sysrepo through netconf client(netopeer-cli etc) . This will revert back content of Sysrepo database.

I was trying to avoid Step-2 . So had a point of having auto-rollback through application itself. But seems to be tricky.

**Comment by michalvasko** [comment]
Step 2 is somewhat simpler, you trigger manual rollback by directly calling *libsysrepo* `sr_set_item()` functions, you can completely avoid *netopeer2-server* and all of NETCONF.

Regards,
Michal

**Comment by ykumar-rb** [comment]
Yeah indeed. Thanks for responses.

**Comment by ykumar-rb** [comment]
One more query on Solution suggested on Step-2:  
During Edit Config APPLY Phase,  In case of failure, we want to trigger explicit rollback( resetting old values) through application. 
But application has to ignore this change events received. Is there any valid identifier on basis of that we can ignore this callback. 
Or Is there any way to just reset Sysrepo Database with oldValues without getting callback.

**Comment by michalvasko** [comment]
Hi,
it should be possible to set the old value without triggering a callback if you set the value from the callback (read a critical [note](http://www.sysrepo.org/static/doc/html/subscribtions.html#callbacks)).

Regards,
Michal

**Comment by ykumar-rb** [comment]
Hi Michal,

Thanks again for adding more information.
The issue is if callback is called, Application will end up processing as Request either like Delete/Update , which can mess up system or end up doing unnecessary extra processing. This will be handled though based on proper error handling at application. But normally, application is not expected to design in this fashion.

In my case,  worker thread(who writes for rollback can be different thread) and there are other thread/s who subscribed for getting change notification.  I need to just figure it out some way to understand the callback received is due to rollback and it should be simply ignored.

I am looking at finding Sysrepo capabilities , which can be identifier for change events (generically) to identify rollback case.

Regards,
Y.

**Comment by michalvasko** [comment]
Hi,
I have nothing else to help you more. Like I said, the implementation of something like this will not be pretty because you are "hacking" *sysrepo* into supporting a use-case it does not.

Regards,
Michal

**Comment by ykumar-rb** [comment]
Thanks! No problem
