### ISSUE TITLE
Segmentation fault in sr_comit() at client_library.c:2077

### ISSUE THREAD

**Issue by zoltan-balogh-eth** [sysrepo/sysrepo#1245]
### Description
I'm doing concurrent access tests. I create several threads in my test application to set/commit values in the running datastore. In case the number of threads is high, sysrepod cannot handle all the requests, there are ERR messages like below in its log:

[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=1069631731.
[WRN] (np_commit_notification_ack:1555) No NP commit context for commit ID 1255883763.
[ERR] (rp_check_notif_session:124) Get commit context failed
[ERR] (rp_get_items_req_process:808) Check notif session failed
[WRN] (np_commit_notification_ack:1555) No NP commit context for commit ID 2118144397.
[ERR] (rp_check_notif_session:124) Get commit context failed
[ERR] (rp_get_items_req_process:808) Check notif session failed
[WRN] (np_commit_notification_ack:1555) No NP commit context for commit ID 2105307067.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=596461506.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=163870847.
[ERR] (np_commit_notifications_complete:1610) Commit timeout for commit id=553853183.

In addition the test application crashes. According to gdb, the segfault happens in sr_commit() at client_library.c:2077 where SR_LOG_ERR is called.

       /* send the request and receive the response */
       rc = cl_request_process(session, msg_req, &msg_resp, NULL, SR__OPERATION__COMMIT);
       commit_resp = msg_resp->response->commit_resp;
       if (rc != SR_ERR_OK) {
        SR_LOG_ERR("Commit operation failed with %zu error(s).", commit_resp->n_errors);

           /* store commit errors within the session */
           if (commit_resp->n_errors > 0) {
               cl_session_set_errors(session, commit_resp->errors, commit_resp->n_errors);
           }
       }

It seems, `msg_resp->response->commit_resp` is **NULL**. So accessing `commit_resp->n_errors` leads to segfault.

### Versions
Sysrepo version: 0.7.4
libyang version: 0.15.146

I built sysrepo on this commit:
$ git show 
commit 66971af07c47164622bb9fda8fae4bdf2b9a08fb (HEAD -> devel)
Merge: e788ae95 88e8ccf3
Author: Mislav Novakovic <mislav.novakovic@gmail.com>
Date:   Wed Jul 11 17:04:15 2018 +0200

    Merge pull request #1226 from sartura/swig_refactor
    
    Swig refactor

**Comment by michalvasko** [comment]
Hi,
it should no longer crash. However, regarding the timeouts, fixing those would likely require significant changes so I will keep it for later as an enhancement.

Regards,
Michal

**Comment by michalvasko** [comment]
Not relevant anymore.
