### ISSUE TITLE
Query: SSH decoded packets from/to server

### ISSUE THREAD

**Issue by feldi59** [sysrepo/sysrepo#1249]
Hi,

is there any simple way to view decoded SSH packets going from netconf client to server and reverse ?

Martin

**Comment by michalvasko** [comment]
Hi Martin,
you can see NETCONF messages (if that is what you mean) if you turn on debugging. In `netopeer2-cli` it is simply `verb debug` and in `netopeer2-server` it should be parameter `-c MSG`.

Regards,
Michal
