### ISSUE TITLE
sysrepocfg --set  expect all list indexes to be quoted.

### ISSUE THREAD

**Issue by przemekr** [sysrepo/sysrepo#1250]
### Things you may try first
(put "x" in "[]" if you already tried following)
* [x] Did you check if this is a duplicate issue?
* [] Did you test it on the latest sysrepo devel branch?

### Description
setting a value in sysrepo requires all list parameters to be quoted (ie. '[idx="0"]') even the list indexes are integers. 

### Steps to Reproduce
$ sysrepocfg --set '/test:container/list[idx=0]/leaf' --set-value=1 --datastore startup
[ERR] (cl_request_process:562) Error by processing of the set-item-str request (session id=1195311050): Invalid argument.
[ERR] (sr_set_item_str:1901) Error by processing of the request.
Error by sr_set_item_str: Operation not permitted for /test:container/list[idx=0]/leaf
Error by srcfg_write_xpath_value: Operation not permitted for /test:container/list[idx=0]/leaf
Errors were encountered during importing. Cancelling the operation.

$ sysrepocfg --set '/test:container/list[idx="0"]/leaf' --set-value=1 --datastore startup
The new configuration was successfully applied.

Where module is something like:
module test {
...
container container {
    list list {
        max-elements 3;
        key "idx"; 
        leaf idx { type uint16; description "List index"; }
        leaf leaf { type uint16; }
    }
}

**Expected behavior:**
xpath for the set and get operation should be consistent.  Quoting integer values shouldn't be required. 

**Actual behavior:**

### Versions
sysrepod - sysrepo daemon, version 0.7.2
yanglint 0.14.50

### Attachments
Jul 31 15:27:32 cocoplum sysrepod[24175]: [INF] (sm_session_create:470) New session created successfully, real user=streif-user, effective user=(null), session id=311075461.
Jul 31 15:27:32 cocoplum sysrepod[24175]: [INF] (rp_dt_get_values_wrapper_with_opts:1351) Get items request startup datastore, xpath: /test:*//., offset: 0, limit: 100
Jul 31 15:27:32 cocoplum sysrepod[24175]: [INF] (dm_load_data_tree_file:1164) Data file /etc/sysrepo/data/eNB.startup loaded successfully
Jul 31 15:27:32 cocoplum sysrepod[24175]: [INF] (rp_dt_get_values_wrapper_with_opts:1351) Get items request startup datastore, xpath: /test:*//., offset: 100, limit: 100
Jul 31 15:27:32 cocoplum sysrepod[24175]: [INF] (rp_dt_get_values_wrapper_with_opts:1351) Get items request startup datastore, xpath: /test:*//., offset: 200, limit: 100
Jul 31 15:27:32 cocoplum sysrepod[24175]: [INF] (rp_dt_get_values_wrapper_with_opts:1351) Get items request startup datastore, xpath: /test:*//., offset: 300, limit: 100
Jul 31 15:27:32 cocoplum sysrepod[24175]: [INF] (rp_dt_get_values_wrapper_with_opts:1351) Get items request startup datastore, xpath: /test:*//., offset: 400, limit: 100
Jul 31 15:27:32 cocoplum sysrepod[24175]: [INF] (rp_dt_get_values_wrapper_with_opts:1351) Get items request startup datastore, xpath: /test:*//., offset: 500, limit: 100
Jul 31 15:27:32 cocoplum sysrepod[24175]: [INF] (rp_dt_get_values_wrapper_with_opts:1351) Get items request startup datastore, xpath: /test:*//., offset: 600, limit: 100
Jul 31 15:27:32 cocoplum sysrepod[24175]: [INF] (rp_dt_get_values_wrapper_with_opts:1351) Get items request startup datastore, xpath: /test:*//., offset: 700, limit: 100
Jul 31 15:27:32 cocoplum sysrepod[24175]: [INF] (rp_dt_get_values_wrapper_with_opts:1351) Get items request startup datastore, xpath: /test:*//., offset: 800, limit: 100
Jul 31 15:27:32 cocoplum sysrepod[24175]: [INF] (rp_dt_get_values_wrapper_with_opts:1351) Get items request startup datastore, xpath: /test:*//., offset: 900, limit: 100
Jul 31 15:27:32 cocoplum sysrepod[24175]: [INF] (rp_dt_get_values_wrapper_with_opts:1351) Get items request startup datastore, xpath: /test:*//., offset: 1000, limit: 100
Jul 31 15:27:32 cocoplum sysrepod[24175]: [INF] (rp_dt_get_values_wrapper_with_opts:1351) Get items request startup datastore, xpath: /test:*//., offset: 1100, limit: 100
Jul 31 15:27:32 cocoplum sysrepod[24175]: [INF] (rp_dt_get_values_wrapper_with_opts:1351) Get items request startup datastore, xpath: /test:*//., offset: 1200, limit: 100
Jul 31 15:27:32 cocoplum sysrepod[24175]: [INF] (rp_dt_get_values_wrapper_with_opts:1351) Get items request startup datastore, xpath: /test:*//., offset: 1300, limit: 100
Jul 31 15:27:32 cocoplum sysrepod[24175]: [INF] (rp_dt_get_values_wrapper_with_opts:1351) Get items request startup datastore, xpath: /test:*//., offset: 1400, limit: 100
Jul 31 15:27:32 cocoplum sysrepod[24175]: [INF] (rp_dt_get_values_wrapper_with_opts:1351) Get items request startup datastore, xpath: /test:*//., offset: 1500, limit: 100
Jul 31 15:27:32 cocoplum sysrepod[24175]: [INF] (rp_dt_get_values_wrapper_with_opts:1351) Get items request startup datastore, xpath: /test:*//., offset: 1600, limit: 100
Jul 31 15:27:32 cocoplum sysrepod[24175]: [INF] (rp_dt_get_values_wrapper_with_opts:1351) Get items request startup datastore, xpath: /test:*//., offset: 1700, limit: 100
Jul 31 15:27:32 cocoplum sysrepod[24175]: [INF] (rp_dt_get_values_wrapper_with_opts:1351) Get items request startup datastore, xpath: /test:*//., offset: 1800, limit: 100
Jul 31 15:27:32 cocoplum sysrepod[24175]: [INF] (rp_dt_get_values_wrapper_with_opts:1351) Get items request startup datastore, xpath: /test:*//., offset: 1900, limit: 100
Jul 31 15:27:32 cocoplum sysrepod[24175]: [INF] (rp_dt_get_values_wrapper_with_opts:1351) Get items request startup datastore, xpath: /test:*//., offset: 1913, limit: 100
Jul 31 15:27:32 cocoplum sysrepod[24175]: [INF] (rp_dt_set_item_wrapper:580) Set item request startup datastore, xpath: /test:container/list[idx="0"]/leaf
Jul 31 15:27:32 cocoplum sysrepod[24175]: [ERR] (dm_ly_log_cb:1288) libyang error: Unexpected character(s) '0' ("0]/leaf").
Jul 31 15:27:32 cocoplum sysrepod[24175]: [ERR] (rp_dt_set_item:431) Setting of item failed /test:container/list[idx=0]/leaf 68
Jul 31 15:27:32 cocoplum sysrepod[24175]: [ERR] (rp_dt_set_item_wrapper:596) Set item failed
Jul 31 15:27:32 cocoplum sysrepod[24175]: [ERR] (rp_set_item_str_req_process:1257) Set item failed for '/test:container/list[idx=0]/leaf', session id=311075461.
Jul 31 15:27:32 cocoplum sysrepod[24175]: [INF] (dm_unlock_datastore:1502) Unlock datastore request
Jul 31 15:27:32 cocoplum sysrepod[24175]: [INF] (sm_session_drop:487) Dropping session id=311075461.
Jul 31 15:27:32 cocoplum sysrepod[24175]: [INF] (cm_conn_close:408) Closing the connection 0x109fe60.
streif-user@cocoplum:~$ sysrepocfg --set '/test:container/list[idx=0]/leaf' --set-value=1 --datastore startup
[ERR] (cl_request_process:562) Error by processing of the set-item-str request (session id=1195311050): Invalid argument.

Thanks!

**Comment by michalvasko** [comment]
Hi,
*sysrepo* is actually limited by *libyang* in this case. It technically parses an `instance-identifier` (uses the same functions) and so the [value must be delimited with quotes](https://tools.ietf.org/html/rfc7950#page-205). I am sorry for any inconvenience, but is it really a problem? I do not see any nice way of changing it.

Regards,
Michal
