### ISSUE TITLE
Provide a --root or --installroot command line argument for sysrepocfg and sysrepocfg

### ISSUE THREAD

**Issue by krobbins** [sysrepo/sysrepo#1252]
I use Yocto Linux to build embedded Linux distributions. When building the root file system on a build host, I would like to be able to use `sysrepoctl` to install YANG modules and `sysrepocfg` to load default configurations from XML files. But, neither of these commands provide a command line argument to specify the root path. So, I have to delay installing YANG modules and loading default configurations until the first boot on the target hardware.

Please consider providing a `--root` or `--installroot` command line argument, so that the repository in the target root file system can be manipulated from a build host.

**Comment by jktjkt** [comment]
We're using Buildroot internally, and we faced a similar problem as we're building on x86_64 and targeting ARM. A solution which works for us is to build sysrepo twice. The first build is for the *host*, the second one is for the *target*, and both share the target's staging area for `/etc/sysrepo`, the repository location. After that, one still needs to clean up the full paths which are embedded in the repo. Check the [build recipes](https://gerrit.cesnet.cz/plugins/gitiles/github/buildroot/buildroot/+/d289a657cf1a26694053e41cb35cd1a28f3f3bdb/package/sysrepo/sysrepo.mk), I'll upstream them once the required changes which are already in sysrepo/netopeer2's devel branches hit a release.
