### ISSUE TITLE
Callbacks to action subscriptions within a list do not respect list key

### ISSUE THREAD

**Issue by KyleGG** [sysrepo/sysrepo#1255]
### Description
Given two applications each subscribed to an action at a different key value within a list, 
When an action is received for a particular key value, 
The first application to subscribe to the action regardless of the key value receives the callback. 

Using a module containing loosely as follows:

```
    container a {
        list b {
            key "c";
            leaf c {
                type string;
            }
            action d {
                 input {
                     leaf e {
                         type string;
                     }
                 }
            }
        }
    }
```

### Steps to Reproduce
1. Create two applications that subscribe to actions in different list elements
2. Send an action with the key value of the second application to start 
3. See which application got the callback.

**Expected behavior:**
Actions are tied to nodes in the tree. If application A subscribes to action element at key C, it should not receive callbacks for action element at key D which is subscribed to by Application B.

**Actual behavior:**
Application A received an action intended for Application B. Application B didn't get anything. 

### Versions
Please provide versions for software needed to reproduce the bug:
Sysrepo version: `sysrepod -v`. - sysrepod - sysrepo daemon, version 0.7.4
libyang version: `yanglint -v` - yanglint 0.15.120
netopeer2-server: `netopeer2-server -V` (optional) - netopeer2-server 0.5.22

### Attachments
Can write up a set of sample applications if this behaviour is seen as a bug.

**Comment by michalvasko** [comment]
Hi,
unfortunately, this is a feature, not a bug. If you look at documentation of `sr_action_subscribe()`, you will see that `xpath` argument is described as Schema Path. That means among other things that you should not include any predicates or values, you are targetting a schema node, not a data node. So, what you would like to do is not supported.

Regards,
Michal

**Comment by KyleGG** [comment]
Thanks Michal.

If this is not supported I will find another way to get the behaviour I am looking for (edit-config). 

Question though: I am only moderately familiar with then YANG RFC, but It feels odd that actions can be instanced within a list in yang but not subscribed to per instance. It makes me wonder if the current action implementation is RFC compliant.

**Comment by KyleGG** [comment]
Very reasonable. Cheers!

**Comment by KyleGG** [comment]
I went and referred to the RFC, and read the following:

7.15.  The "action" Statement

   The "action" statement is used to define an operation connected to a
   **specific** container or  **list data node**.

This goes directly against what you said

>  you will see that xpath argument is described as Schema Path. That means among other things that you should not include any predicates or values, **you are targetting** a schema node, **not a data node**. 

The current implementation does not support subscriptions to data nodes and thus is not RFC compliant. Can you please set this as a bug?

**Comment by michalvasko** [comment]
Hi,
I believe the most important thing is being able to perform an `action` tied to a specific `container` or `list` instance, which you are. If you really want to continue this pointless debate then I can argument that RFC does not say a thing about subscriptions, so to what *sysrepo* subscribes is its own business. It is a particular implementation that allows you to perform what the RFC requires meaning it is RFC compliant. Anyway, I can set whatever labels you want, it would not get fixed anytime soon or not at all.

Regards,
Michal

**Comment by KyleGG** [comment]
Michal, 

Would you be willing to bring in a merge request of this functionality if an acceptable implementation was given?

I feel quite strongly that the use case above should be supported given how the yang RFC describes actions. The bug I see is that an application can receive a callback when an action comes in through net conf for a different list key than the one subscribed with. The second bug being applications don't always receive callbacks for an action they are uniquely subscribed to.  

Cheers,

Kyle

**Comment by michalvasko** [comment]
Fixed.
