### ISSUE TITLE
Query: Debug sysrepo plugin daemon with eclipse

### ISSUE THREAD

**Issue by feldi59** [sysrepo/sysrepo#1256]
Hi,

we plan to use the plugin interface within our C/C++ project, because we already have an existing infrastructure including flat data storage in one config file (using google protobuf).

My problem is i never have debugged a shared library or a plugin with eclipse CDT (running on a xubuntu 64bit PC).

Can you give me some hints how to manage that task ?

Best regards
Martin

**Comment by michalvasko** [comment]
Hi Martin,
even though your query has little connection with *sysrepo*, I will reply. As long as you compile *sysrepo* with debugging symbols, it works just as if it was not a shared library. The same principle is used when you have several source code files for one binary application (which is practically always).

Regards,
Michal
