### ISSUE TITLE
sysrepo build process

### ISSUE THREAD

**Issue by feldi59** [sysrepo/sysrepo#1257]
When i build sysrepo 

i prepare the make files with cmake:
change to sysrepo directory
`mkdir build`
`cd build`
`cmake ..`

OK

then i execute: 
`make`
`sudo make install`

OK

now i want to execute make again and it fails with access rights violation
because the "make install" sets some files access rights to root 

_cp: cannot create regular file '/home/necxe/netconf_yang/sysrepo/build/repository/yang/internal/sysrepo-persistent-data.yang': Permission denied_

Is that a desired behaviour ?

My problem is i want to change something at the turing-machine for tests then rebuild and debug it.

Best regards
Martin

**Comment by michalvasko** [comment]
Hi Martin,
I would not exactly call it a desired behaviour, but that is the way it is. To successfully run make again, just remove all contents of `build` directory and recompile it all.

Regards,
Michal
