### ISSUE TITLE
Config error with multiple daemons subscribed to same tree (callback not called)

### ISSUE THREAD

**Issue by kpbarrett** [sysrepo/sysrepo#1259]
### Things you may try first
(put "x" in "[]" if you already tried following)
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description
In a scenario where client A is subscribed to module X, with running config active: If client B subscribes to the same module, startup-config is copied to running-config with no subscription notification sent to daemon A.

### Steps to Reproduce
in window 1:
$ application_example turing-machine

in window 2:
$ sysrepocfg --set "/turing-machine:turing-machine/transition-function/delta[label='final step']/input/state" -w 1234
 -- confirm value is received by application in window 1

in window 3:
$ application_example turing-machine
  -- confirm no notification sent to application in window 1

in window 2:
$ sysrepocfg --get "/turing-machine:turing-machine/transition-function/delta[label='final step']/input/state" --format=xml
  -- confirm value is changed back to that in startup-config

**Expected behavior:**
Expect a subscription notification to be sent to the original subscriber

**Actual behavior:**
No notification sent

### Versions
Please provide versions for software needed to reproduce the bug:
Sysrepo version: devel branch tip c91f059
libyang version: yanglint 0.15.120

### Attachments
[sysrepod.log](https://github.com/sysrepo/sysrepo/files/2276220/sysrepod.log)

**Comment by michalvasko** [comment]
Hi,
what notification did you exactly expect to receive for application in window 1? You can only receive events `SR_EV_VERIFY, `SR_EV_APPLY`, `SR_EV_ABORT`, and `SR_EV_ENABLED`.

Regards,
Michal

**Comment by kpbarrett** [comment]
I expected the application in window 1 to participate in a running-config update the same way that it would if a <copy-config> from startup to running were executed, since that is essentially what is happening when the application in window 3 creates its module subscription.

After modifying the example application a number of ways (using SR_SUBSCR_DEFAULT | SR_SUBSCR_EV_ENABLED, subscribing to netconf-config-change event, periodically calling sr_session_refresh()) I am unable to have my application be notified when its running-config is overwritten in this way -- I can only poll for the changes. Am I doing this correctly?

Alternatively, is there a way to create a subscription which does not do a startup-to-running copy, but which copies from an existing running config?

Thanks --
  - Kevin

**Comment by michalvasko** [comment]
Hi Kevin,
when the first subscription to a model is performed, the model is `ENABLED` (and also `startup` of this model is copied into `running`). It stays enabled as long as there is at least one subscriptions to it. But if there are more subscriptions, the model simply stays enabled and no configuration copying is performed, is your experience different? Are you sure the configuration is overwritten? It should not be.

Regards,
Michal

**Comment by kpbarrett** [comment]
Indeed, that is the behavior I'm seeing. The example application is below. To verify, open two terminals. Start sysrepod, then run in terminal 1:

```
$ ./a.out turing-machine
```

Verify the application periodically prints the value '3'.
In terminal 2, run:

```
$ sysrepocfg --set "/turing-machine:turing-machine/transition-function/delta[label='final step']/input/state" -w 1234
```
Verify the app in terminal 1 prints the new value '1234'.

Then in terminal 2, run:
```
$ ./a.out turing-machine
```

The app in terminal 1 goes back to printing '3' with no notification received.

**Example Application:**
```
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <signal.h>
#include <inttypes.h>

#include "sysrepo.h"
#include "sysrepo/values.h"

volatile int exit_application = 0;
volatile int cmd_refresh = 0;

#define XPATH_MAX_LEN 100

static void
event_notif_cb(const sr_ev_notif_type_t notif_type, const char *xpath, const sr_val_t *values, const size_t value_cnt,
       time_t timestamp, void *private_ctx)
{
    /* print notification */
    printf("\n\n ========== RECEIVED EVENT NOTIFICATION ======%s\n\n", ctime(&timestamp));
    printf(">>> Notification content:\n\n");
    for (size_t i = 0; i < value_cnt; ++i) {
        sr_print_val(values+i);
    }
    printf("\n");
    cmd_refresh = 1;

    /**
     * Here you would normally handle the notification.
     */

    /**
     * Do not deallocate the notification content!
     * Values will get freed automatically by sysrepo.
     */
}

static void
print_current_config(sr_session_ctx_t *session, const char *module_name)
{
    sr_val_t *values = NULL;
    size_t count = 0;
    int rc = SR_ERR_OK;
    char xpath[XPATH_MAX_LEN] = {0};
    snprintf(xpath, XPATH_MAX_LEN, "/%s:*//.", module_name);

    rc = sr_get_items(session, xpath, &values, &count);
    if (SR_ERR_OK != rc) {
        printf("Error by sr_get_items: %s", sr_strerror(rc));
        return;
    }
    for (size_t i = 0; i < count; i++){
        sr_print_val(&values[i]);
    }
    sr_free_values(values, count);
}

static int
module_change_cb(sr_session_ctx_t *session, const char *module_name, sr_notif_event_t event, void *private_ctx)
{
    printf("\n\n ========== EVENT TYPE %d ==========\n\n", event);

    if (event == SR_EV_APPLY) {
        printf("\n\n ========== CONFIG CHANGED, CURRENT RUNNING CONFIG %s: ==========\n\n", module_name);
        print_current_config(session, module_name);
    }

    return SR_ERR_OK;
}

static void
sigint_handler(int signum)
{
    exit_application = 1;
}

int
main(int argc, char **argv)
{
    sr_conn_ctx_t *connection = NULL;
    sr_session_ctx_t *session = NULL;
    sr_subscription_ctx_t *subscription = NULL;
    int rc = SR_ERR_OK;

    if (argc == 1) {
        fprintf(stderr, "No modules specified.\n");
        return 1;
    }

    /* connect to sysrepo */
    rc = sr_connect("example_application", SR_CONN_DEFAULT, &connection);
    if (SR_ERR_OK != rc) {
        fprintf(stderr, "Error by sr_connect: %s\n", sr_strerror(rc));
        goto cleanup;
    }

    /* start session */
    rc = sr_session_start(connection, SR_DS_RUNNING, SR_SESS_DEFAULT, &session);
    if (SR_ERR_OK != rc) {
        fprintf(stderr, "Error by sr_session_start: %s\n", sr_strerror(rc));
        goto cleanup;
    }

    for (int i = 1; i < argc; ++i) {
        /* subscribe for changes in running config */
        rc = sr_module_change_subscribe(session, argv[i], module_change_cb, NULL,
                0, SR_SUBSCR_CTX_REUSE | SR_SUBSCR_EV_ENABLED, &subscription);
        if (SR_ERR_OK != rc) {
            fprintf(stderr, "Error by sr_module_change_subscribe: %s\n", sr_strerror(rc));
            goto cleanup;
        }

        printf("\n\n ========== SUBSCRIBE TO MODULE: %s ==========\n\n", argv[i]);
    }

    rc = sr_event_notif_subscribe(session, "/ietf-netconf-notifications:netconf-config-change", event_notif_cb, NULL,
            SR_SUBSCR_DEFAULT, &subscription);
    if (SR_ERR_OK != rc) {
        fprintf(stderr, "Error by sr_event_notif_subscribe: %s\n", sr_strerror(rc));
        goto cleanup;
    }

    printf("\n\n ========== SUBSCRIBED FOR EVENT NOTIFICATION ==========\n\n");

    /* loop until ctrl-c is pressed / SIGINT is received */
    signal(SIGINT, sigint_handler);
    signal(SIGPIPE, SIG_IGN);
    while (!exit_application) {
        sleep(2);  /* or do some more useful work... */

        if (cmd_refresh)
        {
            cmd_refresh = 0;
            printf("Refresh session...\n");
            sr_session_refresh(session);
        }

        /* start session for reading out the value */
        sr_session_ctx_t *newsess;
        rc = sr_session_start(connection, SR_DS_RUNNING, SR_SESS_DEFAULT, &newsess);
        if (SR_ERR_OK != rc) {
            goto cleanup;
        }

        sr_val_t *value = NULL;
        rc = sr_get_item(newsess, "/turing-machine:turing-machine/transition-function/delta[label='final step']/input/state", &value);
        sr_session_stop(newsess);
        if (SR_ERR_OK != rc) {
            fprintf(stderr, "Failed to read value: %s\n", sr_strerror(rc));
        }
        else
        {
            printf("Got value... ");
            char valstr[1000];
            rc = sr_val_to_buff(value, valstr, sizeof(valstr));
            if (rc == 0)
            {
                printf("Failed to convert value to string\n");
            }
            else
            {
                printf("%s\n", valstr);
            }
            sr_free_val(value);
        }

    }

    printf("Application exit requested, exiting.\n");

cleanup:
    if (NULL != subscription) {
        sr_unsubscribe(session, subscription);
    }
    if (NULL != session) {
        sr_session_stop(session);
    }
    if (NULL != connection) {
        sr_disconnect(connection);
    }
    return rc;
}

```

Thanks,
  -- Kevin

**Comment by michalvasko** [comment]
Hi Kevin,
you are right, I guess I have never tried this scenario and it seems to be an oversight. The quick fix is to use `SR_SUBSCR_PASSIVE` in one subscription and then no copying should be performed. In the meantime I will implement a proper fix.

Regards,
Michal

**Comment by michalvasko** [comment]
Okay, should now work properly in `devel` (the module is not copied during the second subscription).

Regards,
Michal
