### ISSUE TITLE
Problems with union of leafrefs type

### ISSUE THREAD

**Issue by samuel-gauthier** [sysrepo/sysrepo#1260]
### Things you may try first
(put "x" in "[]" if you already tried following)
* [X] Did you check if this is a duplicate issue?
* [X] Did you test it on the latest sysrepo devel branch?

### Description
Using a union of two leafrefs as type for a leaf does not seem to work when sysrepo receives state for it.

### Steps to Reproduce
1. Start sysrepo docker
docker run sysrepo/sysrepo-netopeer2:latest

2. Install this yang file inside

```
module main {
  yang-version "1.1";
  namespace "uri:main";
  prefix "main";

  container state {
    config false;
    container pool1 {
      leaf name {
        type string;
      }
    }
    container pool2 {
      leaf name {
        type string;
      }
    }
    container object {
      leaf-list pool {
        type union {
          type leafref {
            path "../../pool1/name";
          }
          type leafref {
            path "../../pool2/name";
          }
        }
      }
    }
  }
}

```
3. Patch the examples/oper_data_example.c file with attached patch
cd /opt/dev/sysrepo
patch -p1 < patch

4. Rebuild
cd /opt/dev/sysrepo/build
make

5. Run oper_data_example
 /opt/dev/sysrepo/build/examples/oper_data_example &
 /opt/dev/sysrepo/build/examples/oper_data_example req

6. Check sysrepo logs
[ERR] (sr_libyang_leaf_copy_value:1198) Can not copy value of union 'pool'
[ERR] (rp_dt_get_value_from_node:111) Copying of value failed
[ERR] (rp_dt_get_values_from_nodes:163) Getting value from node pool failed
[ERR] (rp_dt_get_values_wrapper_with_opts:1382) Copying values from nodes failed for xpath '/main:state//.'
[ERR] (rp_get_items_req_process:830) Get items failed for '/main:state//.', session id=12700097.

**Expected behavior:**
I expected that sysrepo would resolve the union type, and that it would accept the state sent by oper_data_example, and transmit it during the request.

### Versions
I used today's docker image : sysrepo/sysrepo-netopeer2:latest

### Additional notes
I am not sure if it helps, but we also get errors in libyang when validating our data in a configuration for a similar yang model. Or maybe it is just another problem of the same kind in libyang ?
ERR ly Unable to determine the type of value "test" from union type "union" prior to validation

**Comment by samuel-gauthier** [comment]
Better with the actual patch... 
[patch.txt](https://github.com/sysrepo/sysrepo/files/2277594/patch.txt)

**Comment by michalvasko** [comment]
Hi Samuel,
it works just fine with the current `devel` so I suggest you use that one. *docker* images may be nice, but they are rarely completely up-to-date.

Regards,
Michal

**Comment by samuel-gauthier** [comment]
Good to know, I will check with devel next time, sorry about that. Thanks a lot Michal!
