### ISSUE TITLE
Empty container erroneously present in get-config response when lyb file format is used

### ISSUE THREAD

**Issue by alangefe** [sysrepo/sysrepo#1272]
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description
When the ietf-snmp model is loaded with none of its features enabled and with the default configuration, an empty container will be present in `get-config` responses.

This behavior was introduced in the implementation of the new `lyb` file format. If `FILE_FORMAT_EXT` is set to its old default of `xml`, the empty container will not be present.

### Steps to Reproduce
1. Install the ietf-snmp model, and be sure its eleven submodules are available in the search directory. These models are available in [RFC 7407](https://tools.ietf.org/html/rfc7407).

2. It is not necessary to enable any of the ietf-snmp features or to configure anything in this module. I replicated the issue with all of the features disabled.

3. Send an unfiltered get-config request to the server and obtain the results.

**Expected behavior:**
No containers from the ietf-snmp module should be present in the get-config response.

**Actual behavior:**
An empty container will be erroneously present in the get-config response:

```
<snmp xmlns="urn:ietf:params:xml:ns:yang:ietf-snmp"/>
```

### Versions
sysrepo 0.7.4 (the latest devel)
libyang 0.16.9 (the latest devel)
netopeer2 0.6.8 (the latest devel-server)

**Comment by michalvasko** [comment]
Hi,
I have tried installing `ietf-snmp` model from libyang test models and then execute `get-config` using *netopeer2-cli*. I have received an empty data in the CLI. Can you please share some additional details so I can reproduce it? Thanks.

Regards,
Michal

**Comment by alangefe** [comment]
You can observe the empty `<snmp>` container in our netopeer2 integration tests here:
* https://github.com/ADTRAN/netopeer2-integration-tests
* [Travis CI](https://travis-ci.org/ADTRAN/netopeer2-integration-tests/builds/420255141#L7325)

The specific test that demonstrates the issue is [`test_snippet`](https://github.com/ADTRAN/netopeer2-integration-tests/blob/master/tests/test_snippet.py#L17). Before proceeding to its actual edit-config snippet, the test first asserts that the running configuration is clean. When `FILE_FORMAT_EXT` is `lyb`, the initial running configuration is not clean, because of the empty `<snmp>` container. If we switch `FILE_FORMAT_EXT` back to `xml`, the test case passes.

I haven't been able to craft a mocka test in _libyang_ or _netopeer2_ that demonstrates the failure in a similar way. This is probably because I am not fully simulating some behavior that is present when the whole stack is integrated together. For example, I'm not sure that the _netopeer2_ `get` mocka tests use the LYB functionality.

**Comment by alangefe** [comment]
This was fixed in https://github.com/CESNET/libyang/commit/dd96229022af69604e742f159bc258329fca4310, included in libyang 0.16.30.
