### ISSUE TITLE
Subscription priorities

### ISSUE THREAD

**Issue by gitter-runner** [sysrepo/sysrepo#1280]
I have issues with subscription priorities.

1. Priorities are not handled properly across modules.

There was already a feature request for it:
[https://github.com/sysrepo/sysrepo/issues/727](https://github.com/sysrepo/sysrepo/issues/727)

Is it planned to fix the order across modules in the near future?

2. Priorities across applications

I have a scenario when two applications subscribe for the same subtree with different priorities:
- application A subscribes for subtree with priotity 10
- application B subscribes for subtree with priotity 9

In this case there is no guarantee that change callback in B is called after the callback in A is executed.
Is there any plan to make priorities work across applications?

Tried on latest release and devel branches.

Best regards.

**Comment by michalvasko** [comment]
Hi,
we will support this use-case in the new sysrepo, it would require significant changes in the current one anyway. So, when will this actually be supported we do not know, definitely at least several months from now.

Regards,
Michal

**Comment by michalvasko** [comment]
Fixed.
