### ISSUE TITLE
Value doesn't conform to schema expected

### ISSUE THREAD

**Issue by rosy8** [sysrepo/sysrepo#1289]
Hi Michal,

I am trying  to do set the node <b> ( xpath: /ietf-system:system/location) </b>through sr_set_item(..)
But while doing so I am getting the following error with the latest library..

<b>Code-  devel branch </b>

sysrepo log
-----------------
[DBG] Processing set_item request.
<b>[INF] Set item request running datastore, xpath: /ietf-system:system/location </b>
[DBG] Module ietf-system already loaded
<b>[ERR] Value doesn't conform to schema expected 18 instead of 17 </b>
[ERR] Value doesn't conform to schema node location
[ERR] Copy new value to string failed
<b>[ERR] Set item failed</b>
[ERR] Set item failed for '/ietf-system:system/location', session id=355484943.
[DBG] Circular buffer enqueue to position=9, current count=1.

yang
-----
In the ietf-system, location is defined as string type ..
    leaf location {
     <b> type string;  </b>
      description
        "The system location.
    ....
 }

Code
------
    value.type = SR_STRING_T;
    value.data.string_val = (char *)name;
    rc = sr_set_item(session, "/ietf-system:system/location", &value, SR_EDIT_DEFAULT);
    if (SR_ERR_OK != rc) {
    <b>  log( "Error %s", sr_strerror(rc));  ==>Getting "Error  Invalid argument" </b>
    }

Am I missing something here ?

Regards
Rosy

**Comment by rosy8** [comment]
Hi Michal,

I did git pull for all the libs..(sysrepo/libyang/libnetconf/netopeer2).
But now while doing make install on sysrepo I am getting the following error..

-- Exec: <dev-dir>/sysrepo/build/src/sysrepoctl --install --yang=<dev-dir>/sysrepo/yang/ietf-netconf-notifications.yang --permissions=666
[ERR] libyang: Invalid magic number "0x000100".
<b>[ERR] Unable to parse sysrepo-module-dependencies.lyb data file: (null) </b>
Error: Failed to initialize module dependencies context.
CMake Error at cmake_install.cmake:139 (message):
  Error: 1

Regards
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
the original error is a strange one and it seems to be some library versions incompatibility. Anyway, the build error is due to a different LYB file format, just remove the whole repository and it will work. It is best to always clear it when compiling (especially after updating a library dependency) so that all files are created anew.

Regards,
Michal
