### ISSUE TITLE
Unable to parse sysrepo-module-dependencies.lyb

### ISSUE THREAD

**Issue by rosy8** [sysrepo/sysrepo#1291]
Hi Michal,

I did git pull for all the libs..(sysrepo/libyang/libnetconf/netopeer2).
 While doing make install for  sysrepo I am getting the following error..

-- Exec: /sysrepo/build/src/sysrepoctl --install --yang=/sysrepo/yang/ietf-netconf-notifications.yang --permissions=666
[ERR] libyang: Invalid magic number "0x000100".
<b>[ERR] Unable to parse sysrepo-module-dependencies.lyb data file: (null) </b>
Error: Failed to initialize module dependencies context.
CMake Error at cmake_install.cmake:139 (message):
Error: 1

<b> sysrepo code -  devel branch </b>
Please let me know if I am missing something here.

Regards
Rosy

**Comment by michalvasko** [comment]
Replied in #1289.
