### ISSUE TITLE
Connect Error

### ISSUE THREAD

**Issue by ParkDerkYoul** [sysrepo/sysrepo#1292]
Hi.
I have a problem when I try to notification.
If I connect client the following error occurs.

ERROR: (cl_request_process:543) Error by processing of the event-notification request (session id=640056867): Operation not supported.
ERROR: (sr_event_notif_send:3606) Error by processing of the request.
ERROR: np2srv_sr_event_notif_send failed (sysrepo: Operation not supported).

Thanks.

**Comment by michalvasko** [comment]
Hi,
I will need much more information to have any chance of helping you. Can you post the model with the notification? Can you include output of `sysrepoctl -l`? How exactly are you sending it, can you share a code snippet?

Regards,
Michal

**Comment by ParkDerkYoul** [comment]
Hi,
I resolved. It was a configuration issue on my server.
Thanks.
