### ISSUE TITLE
protobuf-c support

### ISSUE THREAD

**Issue by smalls12** [sysrepo/sysrepo#1297]
I couldn't find any documentation that explicitly stated which version of protobuf-c to use (might exists, just couldn't find it).

I found this ( #824 ) which highlights that Travis is pulling down the tarball of protobuf-c v1.2.1. I assume that means that you officially support sysrepo with protobuf-c v1.2.1 (confirm/deny). 

Any plans on upgrading to protobuf-c v1.3.0+ ?

Thanks! :)

**Comment by michalvasko** [comment]
Hi,
it should not matter much which version you use, it should work with quite old ones. The reason for *travis-ci* for using these specific versions is that in the past it was not possible to compile current version of *protobuf* with current version of *protobuf-c* for some time. To avoid similar situations, we are using a stable release.

Regards,
Michal

**Comment by smalls12** [comment]
Alright thanks Michal.
