### ISSUE TITLE
Two issues want to confirm about the running datastore subscribe and read/write

### ISSUE THREAD

**Issue by darcyllingyan** [sysrepo/sysrepo#1300]
Hi,
As we know, to support running datastore read/write, the application needs to subscribe for notifications about the changes made in the datastore.

But for one case that I have hundreds of modules and need read/write for those modules in the running datastore, it's not convenient to subscribe each module before operate the running datastore.

So I write a shell script, the function includes the following aspects:
1. Install the yang files
2. Subscribe the yang modules (use the command ```application_example $module``` )

There two issues I want to confirm: 
1. Whether there are some potential problems or notices if I use the shell script to subscribe multiple modules once? Or there are other methods?
2. The running datastore are not persistent and will be lost after system restarts, now the only easier solution is to do a copy-config from running datastore to startup datastore, right?

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
your issues

 1. I think it should work using such a script but there is, of course, another method as such a script can be used only for testing, nothing else. Normally, you would write your own client(s) that would not just subscribe to a model but also apply the performed changes to the device/daemon/whatever.

 2. Yes, for `running` changes to be persistent, a copy-config to `startup` must be performed.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
Thanks very much for the response! I will have a try about the subscribe script.

Thanks
Darcy

**Comment by darcyllingyan** [comment]
Hi Michal,
Focus on the topic, I have another two questions:

1. You said 

> "I think it should work using such a script but there is, of course, another method as such a script can be used only for testing, nothing else. Normally, you would write your own client(s) that would not just subscribe to a model but also apply the performed changes to the device/daemon/whatever.", 

now in fact I only want to get/edit the Running datastore, whether there is a easy way for me to subscribe once and needn't to subscribe all the modules. If yes, whether there is some API as I didn't find one.

2.  Now the sysrepo, netopeer2-server could only be ran as "root" permission, right?
I need to use one netconf client to connect the netopeer2-server/sysrepo, which acted as the netconf server.
When I start the netopeer2-server/sysrepo with root permission, I'm not clear what the function of setting the permissions and owner? Seems now even if I set the owner as others, such as netconf:netconf, it doesn't affect the usage.
```sysrepoctl --install --yang=demo-yang/t1.yang --permissions=666 --owner=netconf:netconf```

**Comment by michalvasko** [comment]
Hi Darcy,

1. I have no solution for you, there is no API you could use. You must subscribe to all the modules separately.

2. Nope, both must be started with `root` permissions.

3. It should affect the usage but only at the user end. If you connect to *netopeer2-server* (using *netopeer2-cli*) as `test` user, for example, you should not have access to a module installed with `--owner=netconf:netconf`.

4. Naturally, `sr_unsubscribe()`. You should write your own application/modify the examples if you do not want to be limited by them.

5. By checking the return value of `sr_*_subscribe()`.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
Thanks very much for the response!
For question1 and 4:

> I have no solution for you, there is no API you could use. You must subscribe to all the modules separately.

> Naturally, sr_unsubscribe(). You should write your own application/modify the examples if you do not want to be limited by them.

If I have many modules need to be subscribed, when use the client library to subscribe, seems one subscribe is a process, if I write the application for sr_unssubscribe, how to determine the specified  subscription for each module?
After check the code, only find the ```pm_get_subscriptions`` using for notification subscription, do you have any suggestions?

```
#ps -ef|grep application_example
root      1789 22197  0 14:08 pts/19   00:00:00 /usr/bin/application_example t2
root      4634     1  0 Nov04 ?        00:00:01 /usr/bin/application_example t1
...
```

For question 5:

> By checking the return value of sr_*_subscribe().

As now I want to run some command in shell script to subscribe many modules,  such as the ```application_example $module```,  
1) Maybe I could write a API just to check the subscribe status.
2) If I don't check from code, whether there is some other way, for example, check the filesize of /sysrepo/data/.persist, /sysrepo/data/.running.


Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
if you insist on still using `application_example`, you should know that it supports an arbitrary number of models as parameters, it will subscribe to all of them meaning you can run it as
```
application example t1 t2 ...
```

It will quit if any one of the subscriptions fails. If you then send `SIGTERM` to it (press `Ctrl + C` if run in a terminal), it will unsubscribe from all the modules. If you want to check subscription status from some other application, you can only do so by looking into the persist files (not really an "official" solution but should work).

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
Thanks very much for the response!
In order to operate the running datastore:
    1. I have to subscribe all the modules, in order to subscribe the module
                1). Suppose the application_example is enough, so apply the performed changes to the device/daemon/whatever isn't needed, right?
                2). Or I need to improve something, as after check the application_example.c, it's simple and only has the subscribe function, but seems it's enough to finish the final purpose of  operating the running datastore.
Not sure my understanding is right.

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
yes, if you do not want the configuration changes actually applied to any device and just make the modules *enabled*, you can use `application_example` ( 1) ).

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
Thanks for the resonse!
But another question:

> It should affect the usage but only at the user end. If you connect to netopeer2-server (using netopeer2-cli) as test user, for example, you should not have access to a module installed with --owner=netconf:netconf.

I did a test about this case:
1. I install the ```normal``` module with netconf:netconf
```
# sysrepoctl -l
Sysrepo schema directory: /etc/sysrepo/yang/
Sysrepo data directory:   /etc/sysrepo/data/
(Do not alter contents of these directories manually)

Module Name                | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
ietf-netconf-notifications | 2012-02-06 | Installed   | root:root           | 666         |                               |
ietf-netconf               | 2011-06-01 | Installed   | root:root           | 666         |                               | writable-running candidate rollback-on-error validate startup xpath
ietf-netconf-acm           | 2018-02-14 | Imported    |                     |             |                               |
nc-notifications           | 2008-07-14 | Installed   | root:root           | 666         |                               |
notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |
ietf-netconf-with-defaults | 2011-06-01 | Installed   |                     |             |                               |
ietf-netconf-monitoring    | 2010-10-04 | Installed   | root:root           | 666         |                               |
ietf-yang-library          | 2018-01-17 | Installed   | root:root           | 666         |                               |
ietf-datastores            | 2017-08-17 | Imported    |                     |             |                               |
ietf-x509-cert-to-name     | 2014-12-10 | Installed   |                     |             |                               |
ietf-keystore              | 2016-10-31 | Installed   | root:root           | 666         |                               |
ietf-netconf-server        | 2016-11-02 | Installed   | root:root           | 666         |                               | listen ssh-listen tls-listen call-home ssh-call-home tls-call-home
ietf-ssh-server            | 2016-11-02 | Imported    |                     |             |                               |
ietf-tls-server            | 2016-11-02 | Imported    |                     |             |                               |
ietf-system                | 2014-08-06 | Installed   | root:root           | 666         |                               | authentication local-users
iana-crypt-hash            | 2014-08-06 | Imported    |                     |             |                               |
normal                     |            | Installed   | netconf:netconf     | 666         |                               |
t2                         |            | Installed   | netconf:netconf     | 666         |                               |
t1                         |            | Installed   |                     |             |                               |

```
2. I want to edit the ```normal``` module, the xml is:
```
# cat /root/test/source/script/demo-data/normal.xml
<users xmlns="http://qingdao_cnet.com/ns/normal/example">
    <user>
        <name>darcy</name>
        <number>1</number>
        <role>aaa</role>
    </user>
    <user>
        <name>hunter</name>
        <number>3</number>
        <role>ddd</role>
    </user>
    <user>
        <name>jerry</name>
        <number>4</number>
        <role>bbb</role>
    </user>
  </users>
```

3. I connect the netopeer2-server with ```cnet:cnet```, but I edit it successfully?
```
> connect --host 10.75.123.183 --port 830 --login cnet
cnet@10.75.123.183 password: 
Interactive SSH Authentication
Type your password:
Password: 
> edit-config --target running --config=/root/test/source/script/demo-data/normal.xml
OK
```
Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
that is quite expected since you have permissions `666` for all the modules effectively making access control transparent.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
Yes, thanks!
It works well.

Thanks
Darcy
