### ISSUE TITLE
Inconsistent escaping of list key XPaths

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#1304]
List keys cannot contain signle and double quote at the same time.

Given the following model:
```yang
module bug-xpath-escapes {
  namespace "urn:example:sysrepo:bug-xpath-escapes";
  prefix "bxe";
  revision 2018-09-12;

  list L {
    key "k";
    leaf k {
      type string;
    }
  }
}
```
I can correctly import this JSON file:
```javascript
{"bug-xpath-escapes:L": [
  {"k": "1"},
  {"k": "\""},
  {"k": "\\"},
  {"k": "'"}
  ]
}
```
Even printing it afterwords works as expected:
```
$ sysrepocfg -d startup -f json bug-xpath-escapes -x
{
  "bug-xpath-escapes:L": [
    {
      "k": "1"
    },
    {
      "k": "\""
    },
    {
      "k": "\\"
    },
    {
      "k": "'"
    }
  ]
}
```
This file, however, cannot be imported:
```javascript
{"bug-xpath-escapes:L": [
  {"k": "1"},
  {"k": "\""},
  {"k": "\\"},
  {"k": "'"},
  {"k": "\"'"}
  ]
}
```
```
[ERR] (rp_dt_set_item:330) Requested node is not valid /bug-xpath-escapes:L[k=""'"]
[ERR] (rp_dt_set_item_wrapper:597) Set item failed
[ERR] (rp_set_item_req_process:1203) Set item failed for '/bug-xpath-escapes:L[k=""'"]', session id=1125495860.
[ERR] (cl_request_process:543) Error by processing of the set-item request (session id=1125495860): Invalid expression..
[ERR] (sr_set_item:1832) Error by processing of the request.
[ERR] (srcfg_convert_lydiff_created:722) Error returned from sr_set_item: Invalid argument.
Errors were encountered during importing. Cancelling the operation.
```

I realize that YANG uses XPath 1.0 which [doesn't support escaping both in the same literal](https://www.w3.org/TR/1999/REC-xpath-19991116/#exprlex), but this case should still be handled gracefully. Either:

- return an error stating that this is explicitly forbidden due to XPath 1.0 deficiency
- use [XPath 2.0 escaping](https://www.w3.org/TR/xpath20/#terminal-symbols) by doubling double quotes in double-quoted string, or doubling apostrophes in apostrophed string

**Comment by michalvasko** [comment]
Hi,
I think the current error is fine, do you really think a change is necessary? Also, using XPath 2.0 escaping would noit be compliant to the YANG specification, so that is not a solution.

Regards,
Michal

**Comment by jktjkt** [comment]
What I dislike about the current approach is its lack of robustness. The code first creates a garbled XPath expression which is then passed into an unrelated code which then detects unbalanced quotes and starts complaining. It looks to me that one could craft a malicious XPath and maybe trick the processor into handling it. Even if that is not the case (perhaps there will always be an unmatched quote at some point in the generated XPath, for example), I think that it would be better to sanitize the data prior to attempting to call `set_item`.

In case of this particular bugreport (`sysrepocfg -f json --import`), something reads the incoming JSON data and creates an XPath for calling `set_path`. I think that it will be better if this XPath-creating code errors out when it encounters a value which cannot be safely serialized into an XPath. A similar fix should then be implemented for any other input formats if the code path is different (XML imports, Netopeer2-server's interaction, etc).

**Comment by michalvasko** [comment]
Hi,
generally speaking, XPath expressions in *sysrepo* are not too robust. That is just another thing I would like to address in the new *sysrepo* but it would be too much work to rewrite it all in the current one for little gain.

Regards,
Michal
