### ISSUE TITLE
src/parser_lyb.c:66: lyb_read: Assertion `lybs->written[i] <= LYB_SIZE_MAX' failed

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#1306]
I'm on latest devel of libyang+sysrepo. On a 32-bit ARM, data import via `sysrepocfg` results in an apprently corrupted LYB file and an error message given in subject. When I transfer that file into my x86_64 system, I'm getting the same error when I try to dump it via `sysrepocfg --datastore=startup --format=json --export mymodule`.

The modules are work-in-progress, but I can share them with you privately if you'd like me to.

**Comment by jktjkt** [comment]
This was apparently a result of using older data file with another version of the schema, sorry for noise. I will have to improve the upgrade process...

**Comment by jktjkt** [comment]
This was apparently a result of using older data file with another version of the schema, sorry for noise. I will have to improve the upgrade process...

**Comment by michalvasko** [comment]
Hi,
such a situation should be detected as long as you change the revision of the module so I am guessing you did not. But if so, then I would like to debug it if possible.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
I have set of yang files and a script to install them using syrepoctl in a loop. while installing all of them in a loop getting this error. Same script worked on 0.7.4. Issue seen after migrating to latest version of libyang and sysrepo. Could you please help me understand the problem.
