### ISSUE TITLE
Dynamic data query from netopeer2-cli

### ISSUE THREAD

**Issue by ajayinnovative2** [sysrepo/sysrepo#1307]
I am trying to get live data on netopeer2-cli such as stats (RX and TX packet) of interface. As
per my knowledge whenever we perform get operation, RPC request goes and queries data-store. Since we do-not store ietf-interfaces state specific data in sysrepo data-store. We can-not get it on cli. 

Do we have any provision or example to get such data on CLI. Help would be appreciable.

Regards,
Ajay

**Comment by michalvasko** [comment]
Hi Ajay,
these data must be provided by an application and you should be able to learn everything you need in the [documentation](http://www.sysrepo.org/static/doc/html/subscribtions.html#data_providers).

Regards,
Michal
