### ISSUE TITLE
question about ietf-netconf-notifications:netconf-config-change notification 

### ISSUE THREAD

**Issue by vincentLzq** [sysrepo/sysrepo#1308]
(This is a question, a request for discussion)

Hi,

I have a question about ietf-netconf-notifications:netconf-config-change notification  session-id leaf 
in rfc6470. 
```yang
leaf session-id {
         type nc:session-id-or-zero-type;
         mandatory true;
         description
           "Identifier of the session.
            A NETCONF session MUST be identified by a non-zero value.
            A non-NETCONF session MAY be identified by the value zero.";
       }
```
I assume it should fill into a netconf session, if I send a edit-config with netconf session-id 10, then notification session-id caused by this edit-config should be 10,
but go through the cdoe, it's set to rp_session_t id, does it use to ommunicate between Request Processor and Connection Manager ?
```C
int
rp_generate_config_change_notification(rp_ctx_t *rp_ctx, rp_session_t *session, sr_list_t *diff_lists) {
    CHECK_NULL_ARG3(rp_ctx, session, diff_lists);
    ......

    values[0].type = SR_UINT32_T;
    values[0].data.uint32_val = session->id;
```
please correct me if I make a mistake, thank a lot.

Thanks

**Comment by michalvasko** [comment]
Hi,
*sysrepo* does not know anything about any NETCONF sessions so it cannot fill in the correct session ID. It seems that sysrepo session ID is used instead, is that a problem?

Regards,
Michal

**Comment by vincentLzq** [comment]
Hi Michal,

thanks your comment, but from rfc6470 description for session-id, seems it should fill in NETCONF session, I just want to confirm it.
leaf session-id {
         type nc:session-id-or-zero-type;
         mandatory true;
         description
           "Identifier of the session.
            A NETCONF session MUST be identified by a non-zero value.
            A non-NETCONF session MAY be identified by the value zero.";
       }

**Comment by michalvasko** [comment]
Hi,
I have just confirmed it is **NOT** a NETCONF session. What does the RFC says about that?
> A non-NETCONF session MAY be identified by the value zero.

In our case, it is not, like I said.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi,
it would be filled by the actual NETCONF session if possible but it is not in the current design of *sysrepo*. There are only *sysrepo* sessions in sysrepo, no NETCONF sessions, so it does not know whether the change actually originated from a NETCONF session or not.

Regards,
Michal

**Comment by michalvasko** [comment]
Fixed.
