### ISSUE TITLE
Why does sysrepoctl install order matter in latest sysrepo version(s)?

### ISSUE THREAD

**Issue by antoninbas** [sysrepo/sysrepo#1314]
### Things you may try first
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description
I was using version 0.7.2 until recently when I updated to 0.7.5 to pick-up some bug fix. I usually install iana-if-type *before* openconfig-interfaces. Unfortunately, after updating sysrepo (and libyang), I now get the following error:
```
libyang[1]: Identity found, but in a non-implemented module "iana-if-type".
libyang[1]: Failed to resolve identityref "iana-if-type:ethernetCsmacd". (path: /openconfig-interfaces:type)
libyang[1]: Previous warning generated by XPath subexpression[29] "openconfig-interfaces:type = 'iana-if-type:ethernetCsmacd'".
```
If I switch the installation order (iana-if-type *after* openconfig-interfaces), then everything works fine. Note that I did clean up my old libyang and sysrepo versions before updating. I also confirmed that this is happening with `devel` versions.

I'd like to know why the installation order matters now and how to determine what is the "correct" order for sysrepo.

Thanks!

**Comment by antoninbas** [comment]
Actually the premise of my question is wrong. I realized that this has nothing to do with the order in which I install the YANG modules. Instead the outcome depends on whether the daemon is used or not. With sysrepod, I get the libyang error and without it everything works fine.

So it seems very similar to https://github.com/sysrepo/sysrepo/issues/1027, except in my case I don't see how it can be caused by an environment error since I run everything in a "fresh" docker (and therefore there is no old libyang / sysrepo version installed).

**Comment by antoninbas** [comment]
Final update to clarify:
- the libyang error message only seems to depend on whether sysrepod is running or not
- despite the error message, I am able to run my application as usual, so it seems pretty harmless
Sorry for the misleading name of the issue

**Comment by michalvasko** [comment]
Hi,
in short, just ignore the message. To explain a bit, when you are installing a new module, a separate libyang context is used to verify that the module is fine and can be loaded. And it can happen that some imported models required to be implemented are just imported in this phase. As long as you have the model in question (`iana-if-type`) **implemented** in the output of `sysrepoctl -l`, you are fine.

Regards,
Michal

**Comment by antoninbas** [comment]
Thanks for confirming that this is harmless and for the explanation!
