### ISSUE TITLE
error when building latest sysrepo

### ISSUE THREAD

**Issue by yuliya2017** [sysrepo/sysrepo#1315]
Hi all,

I am trying to build sysrepo this morning and this is the error I am seeing during the cmake -DCMAKE_BUILD_TYPE=Debug ..
 step:
```
[ 62%] Linking C executable common_test
[ERR] (srctl_ly_log_cb:506) libyang: Invalid date "2017-02-20", valid date in format "YYYY-MM-DD" expected.
[ERR] (srctl_ly_log_cb:506) libyang: Module "yang" parsing failed.
Error: Unable to initialize libyang context.
tests/CMakeFiles/common_test.dir/build.make:108: recipe for target 'tests/common_test' failed
make[2]: *** [tests/common_test] Error 1
make[2]: *** Deleting file 'tests/common_test'
CMakeFiles/Makefile2:1921: recipe for target 'tests/CMakeFiles/common_test.dir/all' failed
make[1]: *** [tests/CMakeFiles/common_test.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```
I have lost my old vm and trying to rebuild now, so  all the packages and dependencies are of the latest versions available. 

I have also found this issue[(https://github.com/CESNET/libyang/issues/504] and tried to use this approach to solve the problem but it didn't help.
Would be very grateful for any help or suggestions.

Kind Regards, 
Yuliya

**Comment by yuliya2017** [comment]
I found the problem. It was `tzdata `package so just had to remove it with `apt-get remove tzdata` and all installation completed fine.

**Comment by michalvasko** [comment]
Hi,
this seems to be a consequence of another libyang [issue](https://github.com/CESNET/libyang/issues/632) so I will close this one as a duplicate.

Regards,
Michal
