### ISSUE TITLE
Found out which modules have been subscribed to

### ISSUE THREAD

**Issue by syyyr** [sysrepo/sysrepo#1316]
Hello, I'm using the client library functions like Session::set_item to make changes to a sysrepo datastore. Making changes to a module isn't possible if there isn't an app subscribed to these changes. I'd like to know if it is possible to find out if any application is subscribed to changes (on a specific module for example).

cc @jktjkt

**Comment by jktjkt** [comment]
@michalvasko , is there a way to find out which subtrees/xpaths/modules are open for modifications when talking to sysrepo?

**Comment by michalvasko** [comment]
Hi,
no, this information is not exposed.

Regards,
Michal

**Comment by jktjkt** [comment]
Hi Michal, to provide some context here -- this is needed for a CLI running on our devices, and therefore it is a pretty important peace of functionality for me. Can you please come up with perhaps a bit hackish way of retrieving that information? I guess that Vasek or me are OK with contributing a sysrepo patch if it is what it takes -- we just need to know where to look for that piece of information.

**Comment by jktjkt** [comment]
Thanks, I'll look into the persistence manager and see if I can export that functionality. I'll ping you when I'm lost :).
