### ISSUE TITLE
src/parser_lyb.c:66: lyb_read: Assertion `lybs->written[i] <= LYB_SIZE_MAX' failed

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1317]
Similar to issue #1306 

Unable to open that issue so creating new one.

I have set of yang files and a script to install them using syrepoctl in a loop. while installing all of them in a loop getting this error. Same script worked on 0.7.4. Issue seen after migrating to latest version of libyang and sysrepo. Could you please help me understand the problem.

To reinstall from scratch i tried to uninstall all yangs, its also failing with same abort. My system went in a state where i am unable to install or uninstall any yang files.

**Comment by michalvasko** [comment]
Hi,
it seems that something went wrong during an update (if you had an older version of *libyang* or some other library, very likely) so I suggest you completely reinstall *libyang*, *sysrepo*, *libnetconf2*, and *netopeer2*. You must do the uninstallation manually, so remove all the libraries (paths can be found in the output of `ldconfig -p`) and remove the whole sysrepo repository (first 2 lines in the output of `sysrepoctl -l`). If the problem persists, please provide the modules you tried to install.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

I am using only sysrepocfg for data import and merge.

So is there a way to smooth upgrade the old startup data if they are in xml format? Without deleting everything.

**Comment by michalvasko** [comment]
Hi,
what do you mean they are in XML format? The abort could have occurred only when parsing LYB data and all the sysrepo files have one format. But to answer, `sysrpeocfg` should be able to handle any data format (XML, JSON, LYB) no matter what the internal sysrepo format is, so yes, just backup the XML data and, once reinstalled, import it normally.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

When I am using old version of sysrepo by default all data files in /etc/sysrepo/data are in xml format. When I am upgrading to newer sysrepo where default data file format is LYB.

You suggested to remove /etc/sysrepo/data and /etc/sysrepo/yang folders for upgrading to newer versions. 

Is it possible to migrate without deleting these folders. As these folders hold persistent data which user needs until he changes it. Some what automatic update the data without deleting and Importing after update.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
you have 2 options. We have no script for any automatic migration, but you can easily write one yourself. Just export the current XML data and after update, import them again using `sysrepocfg`, 2 commands for each module.

Or, you can simply set the internal format back to XML in the recent *sysrepo* simply by specifying `-DFILE_FORMAT_EXT=xml` as a *cmake* parameter.

Regards,
Michal
