### ISSUE TITLE
sysrepoctl -l and netopeer2-server issues after sysrepod started

### ISSUE THREAD

**Issue by katdiam** [sysrepo/sysrepo#1319]
sysrepo from devel branch,  tried master branch,  same issue.
 $ sysrepod -v
sysrepod - sysrepo daemon, version 0.7.5

Before sysrepod daemon started:
/usr/bin/sysrepoctl -l
Sysrepo schema directory: /etc/sysrepo/yang/
Sysrepo data directory:   /etc/sysrepo/data/
(Do not alter contents of these directories manually)

Module Name                | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
ietf-netconf-notifications | 2012-02-06 | Installed   | root:root           | 666         |                               |
ietf-netconf               | 2011-06-01 | Imported    |                     |             |                               |
ietf-netconf-acm           | 2018-02-14 | Imported    |                     |             |                               |
nc-notifications           | 2008-07-14 | Installed   | root:root           | 666         |                               |
notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |

start sysrepod:
=======

sudo /usr/bin/sysrepod -d -l 4 &
[1] 28658
pmao@server03:~/netopeer2/sysrepo/build$ [DBG] (sr_log_stderr:141) Setting log level for stderr logs to 4.
[DBG] (cm_init:1904) Connection Manager init started.
[DBG] (sr_cbuff_init:457) Initiating circular buffer for 10 elements.
[DBG] (sm_init:287) Session Manager initialized successfully, ctx=0x16f0230.
[DBG] (cm_server_init:151) Initializing sysrepo server at socket=/var/run/sysrepod.sock
[DBG] (rp_init:3939) Request Processor init started.
[DBG] (sr_cbuff_init:457) Initiating circular buffer for 10 elements.
[DBG] (sr_cbuff_enqueue:516) Circular buffer enqueue to position=0, current count=1.
[DBG] (np_setup_notif_store_cleanup_timer:726) Notification store cleanup timer set up for 600 seconds.
[DBG] (np_init:809) Notification Processor initialized successfully.
[INF] (dm_init:2270) Initializing Data Manager, schema_search_dir=/etc/sysrepo/yang/, data_search_dir=/etc/sysrepo/data/
[DBG] (rp_worker_thread_execute:3748) Starting worker thread id=139690899560192.
[DBG] (rp_worker_thread_execute:3748) Starting worker thread id=139690882774784.
[DBG] (rp_worker_thread_execute:3810) Thread id=139690882774784 will wait.
[DBG] (cm_init:1963) Connection Manager initialized successfully.
[INF] (main:133) Sysrepo daemon initialized successfully.
[DBG] (cm_event_loop:1872) Starting CM event loop.
[DBG] (rp_worker_thread_execute:3748) Starting worker thread id=139690891167488.
[DBG] (rp_worker_thread_execute:3810) Thread id=139690891167488 will wait.
[DBG] (rp_worker_thread_execute:3810) Thread id=139690899560192 will wait.
[DBG] (rp_worker_thread_execute:3748) Starting worker thread id=139690874382080.
[DBG] (rp_worker_thread_execute:3810) Thread id=139690874382080 will wait.
[DBG] (cm_msg_enqueue_cb:1791) New message enqueued into CM message queue.
[DBG] (sr_cbuff_dequeue:532) Circular buffer dequeue, new buffer head=1, count=0.
[DBG] (cm_delayed_msg_process:323) Scheduling a delayed request for 600.000000 seconds.

After sysrepod daemon started:

/usr/bin/sysrepoctl -l
Sysrepo schema directory: /etc/sysrepo/yang/
Sysrepo data directory:   /etc/sysrepo/data/
(Do not alter contents of these directories manually)
[DBG] (cm_server_watcher_cb:1306) New client connection on fd 6
[DBG] (sm_connection_start:356) New connection started successfully, fd=6, conn ctx=0x1765390.
[DBG] (cm_conn_read_cb:1179) fd 6 readable (revents 1)
[DBG] (cm_conn_buffer_expand:476) Input buffer for fd=6 expanded to 1024 bytes.
[DBG] (cm_conn_read_cb:1192) 28 bytes of data received on fd 6
[DBG] (cm_conn_read_cb:1202) fd 6 would block
[DBG] (cm_conn_in_buff_process:1132) New message of size 24 bytes received.
[ERR] (cl_message_recv:211) Sysrepo server disconnected.
[ERR] (cl_version_verify:448) Unable to receive the message with response (operation=version-verify).
Error: The peer disconnected

sudo netopeer2-server -d -v4 &
[1] 28667
 VERBOSE: (sr_connect:402) Sysrepo daemon has been started.
ERROR: (cl_message_recv:211) Sysrepo server disconnected.
ERROR: (cl_version_verify:448) Unable to receive the message with response (operation=version-verify).
ERROR: Connecting to sysrepo failed (The peer disconnected).
ERROR: Server init failed.

[1]+  Exit 1                  sudo netopeer2-server -d -v4

[4]   Exit 139                sudo /usr/bin/sysrepod -d -l 4

/usr/bin/sysrepoctl -l
Sysrepo schema directory: /etc/sysrepo/yang/
Sysrepo data directory:   /etc/sysrepo/data/
(Do not alter contents of these directories manually)
Segmentation fault (core dumped)

**Comment by michalvasko** [comment]
Hi,
not much to go on but I think this will simply be some kind of version incompatibility, so a proper library reinstallation should fix it. First remove all the current libraries (libyang, libnetconf2, libsysrepo), remove *sysrepo* repository and then install it all again.

Regards,
Michal
