### ISSUE TITLE
assert during dm_get_schema from multiple threads

### ISSUE THREAD

**Issue by anoopbv** [sysrepo/sysrepo#1323]
libyang assert is seen in function lys_disable_deviations(struct lys_module *module) for below line of code if multiple threads are invoking (dm_get_schema->lys_print_mem) for same module simultaneously. First thread executing this logic sets the value of deviated to 2.

        assert(module->deviated == 1); // within lys_disable_deviations

Please check and let me know if the read lock must be replaced with write lock @ below location before invoking lys_print_mem() function.

https://github.com/sysrepo/sysrepo/blob/master/src/data_manager.c#L3408

Thanks!

**Comment by michalvasko** [comment]
Hi,
you are right, even printers are not thread safe, I will create a pull request changing that lock to a write lock.

Regards,
Michal

**Comment by anoopbv** [comment]
ok, thank you.

Regards,
Anoop.bv
