### ISSUE TITLE
Want to confirm whether it's OK to ignore the "libstdc++.so.6(GLIBCXX_3.4.21)(64bit) is needed" dependency when installing the sysrepo

### ISSUE THREAD

**Issue by darcyllingyan** [sysrepo/sysrepo#1328]
Hi,

**Background:**
My environment is Centos7.5, the default gcc version is 4.8.5, the default clang version also has one crash bug. In order to install the sysrepo, I need to upgrade the gcc or clang.
Now I didn't find the way to upgrade the gcc with RPM package, and I only could use the manual way "make, make install" to upgrade it.
With the manual upgrade way, it doesn't impact the sysrepo compile and install, but when make the sysrepo as a RPM package and install the RPM package, the error "libstdc++.so.6(GLIBCXX_3.4.21)(64bit) is needed" is always reported.

**The temporary way** 
When installing the sysrepo RPM package,  add the --nodeps option, it could be installed successfully, seems there is no impact on sysrepo usage when I startup the sysrepo.
I want to double confirm whethe it's OK for me to ignore the dependency?
```
#rpm -ivh cnet-c-sysrepo-0.1.0-18.11.x86_64.rpm 
error: Failed dependencies:
        libstdc++.so.6(GLIBCXX_3.4.21)(64bit) is needed by cnet-c-sysrepo-0.1.0-18.11.x86_64

# rpm -ivh cnet-c-sysrepo-0.1.0-18.11.x86_64.rpm --nodeps
Preparing...                          ################################# [100%]
Updating / installing...
   1:cnet-c-sysrepo-0.1.0-18.11       ################################# [100%]
```

Thanks
Darcy

**Comment by mislavn** [comment]
Hi @darcyllingyan ,

the `libstdc++.so.6(GLIBCXX_3.4.21)(64bit) is needed` dependency is needed for C++ and SWIG bindings, so if you don't use them you can ignore the warning.

You can disable the language bindings with `cmake -DGEN_LANGUAGE_BINDINGS=OFF ..` in sysrepo.

**Comment by jktjkt** [comment]
On RHEL and CentOS, the easiest way of getting a newer compiler is via devtoolset, see https://access.redhat.com/documentation/en-us/red_hat_developer_toolset/7/html/7.0_release_notes/ .

**Comment by darcyllingyan** [comment]
Hi Jktjkt,
Thanks very much for the response!
Yes, now I use the developer_toolset to get the newer compiler, but the developer_toolset doesn't contain the libstdc++.so library.
So I need to set -DGEN_LANGUAGE_BINDINGS=OFF to avoid the dependency error.

Thanks
Darcy

**Comment by jktjkt** [comment]
> Yes, now I use the developer_toolset to get the newer compiler, but the developer_toolset doesn't contain the libstdc++.so library.

It does, you just have to install a corresponding package *and* ensure that correct library paths are searched because it gets installed under `/opt`.

**Comment by darcyllingyan** [comment]
@jktjkt ,
Thanks for the response!

Yes, I use ```cmake -DCMAKE_C_COMPILER=/opt/rh/devtoolset-4/root/usr/bin/gcc``` to search the correct library path.

Thanks
Darcy

**Comment by jktjkt** [comment]
Just overriding a compiler in this way is not enough, as you just found out. That is where the linker error comes from. A correct and documented way is to run your build underneath a special environment, i.e., `scl enable devtoolset-7 /path/to/your/build/runner.sh`.

Alternatively, simply sourcing an appropriate env file might do the trick, too:

```bash
source /opt/rh/devtoolset-7/enable
```

**Comment by darcyllingyan** [comment]
@jktjkt ,
Thanks very much for the response!
After ```scl enable devtoolset```, the devtoolset compile environment takes effect, After There is no dependency error now even I don't set add the ```-DGEN_LANGUAGE_BINDINGS=OFF``` now, really help me a lot!  

I will have a further study about  the ```devtoolset``` usage.

Thanks
Darcy
