### ISSUE TITLE
Add a callback before do the edit-config, want to confirm whether the place I add the callback is right

### ISSUE THREAD

**Issue by darcyllingyan** [sysrepo/sysrepo#1329]
The callback request:
1. When doing the edit-config or commit operation(i.e., before the data is written to running datastore), need to add a new callback function to do a seperate datastore validation, the callback function input parameter is the datastore.
2. I want to add the callback function to ```Netopeer2/main.c```:
``` 
void server_init(void)
{
    ...
    snode = ly_ctx_get_node(np2srv.ly_ctx, NULL, "/ietf-netconf:edit-config", 0);  //get the datastore
    new_added_callback(snode, op_editconfig);
    ...
}
```
3. In the new_added_callback function, I just do some validation for the datastore, after the check is OK, call the edit-config operation.

Whether it's right or there is some other better way?

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi,
it should work and there is, generally, no better way. Just perhaps you can do it the other way around, put your callback into the netopeer2 one, somewhere around `op_editconfig.c:315` so you can use the parsed parameters and do not have to parse them yourself.

Regards,
Michal

**Comment by jktjkt** [comment]
Can you perhaps use the [`SR_EV_VERIFY`](http://www.sysrepo.org/static/doc/html/group__cl.html#gga94740180bfd5e1761cccc8e6485eee68acefd1079184ed6d5391264181f72c70e) in your subscriber which handles data modification?

**Comment by darcyllingyan** [comment]
@jktjkt , @michalvasko ,
Thanks very much for the suggestions!
Now I'm trying the first way(i.e. add the callback in server_init), I will try the other ways later.

I have a question,  I'm not sure how to get the whole data in the datastore. I thought ```snode = ly_ctx_get_node(np2srv.ly_ctx, NULL, "/ietf-netconf:edit-config", 0); ``` is the function to get the datastore, but seems it isn't.
After check the data, I only find some functions to get one module in the datastore, can you give some points, thanks! Besides, if there is one ```print function``` to print the whole datastore? Thanks!

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
`ly_ctx_get_node()` will just return a schema node, there is not even any data. And no, there is no function to get the whole datastore or print it. To do that, you would have to retrieve the data for each datastore separately and then merge them together.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
Thanks for the response! I got it.
Seems it's better for me to add my callback to op_editconfig, in which the parameters are parsed. 

As the needed parameter for me now is the **payload data for the rpc request**, so the variable **config**  below is the parsed payload data, right?

```
nodeset = lyd_find_path(rpc, "/ietf-netconf:edit-config/config");
...
config = lyd_parse_mem(np2srv.ly_ctx, any->value.str, LYD_XML, LYD_OPT_EDIT | LYD_OPT_STRICT);
```

Thanks
Darcy

**Comment by darcyllingyan** [comment]
Hi Michal,
Thanks for the response!
Sorry for disturbing again as I'm always confused with the callback function usage.

My process for my callback is:
```
The callback function returns true case: 
receive rpc edit-config/copy-config/commit request  --->  my callback(check the payload data, if callback function returns true) ---> edit-config ---> write the data to datastore

The callback function returns false case: 
receive rpc edit-config/copy-config/commit request  --->  my callback(check the payload data, if callback function returns false) 
```

As my callback function is triggered before the data is written to running datastore, seems there is no need to add one callback function if it is in the op_editconfig.c but just a normal function calling, right?

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
I am sorry but I do not understand the question. It seems you want to check the payload of an RPC and abort the RPC in case you do not like the payload. Then all you need to do is return from the *netopeer2* callback sooner without calling any *sysrepo* functions, in that case no changes will be actually made. Is that what you were asking?

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal，
Yes, that is my request.
In order to meet the request, I'm not clear whether or not to add one callback function.

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
I still do not know what you want, add one callback function where? Instead of some *netopeer2-server* RPC callback or inside one? What exactly are you trying to achieve? If I already understood your question in my previous reply then I think I have also answered there.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
Why the ```op_editconfig``` isn't called, now I just add a ```fprintf``` in the ```op_editconfig``` function, why it isn't called when I do the edit-config from the netopeer2-cli? How to trigger the function?
```
struct nc_server_reply *
op_editconfig(struct lyd_node *rpc, struct nc_session *ncs)
{
fprintf(stdout, "lingyan db test");
...
}
```

**Comment by darcyllingyan** [comment]
Hi Michal,
Sorry to reopen the question again as I'm also still confusing about the response!

> I still do not know what you want, add one callback function where? Instead of some netopeer2-server RPC callback or inside one? What exactly are you trying to achieve? If I already understood your question in my previous reply then I think I have also answered there.

**The request is:**
**Register a callback function, when the netconf-client sends an edit-config operation(or other operations which has impact on the running datastore), the registered callback will be invoked.**

**Now my solution is:**
1. Add one API interface in op_editconfig.c
```
struct nc_server_reply *
op_editconfig(struct lyd_node *rpc, struct nc_session *ncs)
...
/* config */
    nodeset = lyd_find_path(rpc, "/ietf-netconf:edit-config/config");

/*get the config*/
...
lyd_print_mem(&str, config, LYD_XML, LYP_WITHSIBLINGS | LYP_FORMAT);
    DBG("EDIT_CONFIG: ds %d, defop %s, testopt %d, config:\n%s", sessions->srs, defop2str(defop), testopt, str);
    free(str);
    str = NULL;

  //Add one API interface op_cm_validate(config), the parameter is config
    if (op_cm_validate(config) !=0 ){
        ERR("The payload data check failed!");
        goto cleanup;
    }
...
}

```
2. Add the same API interface in op_copyconfig.c
```
struct nc_server_reply *
op_copyconfig(struct lyd_node *rpc, struct nc_session *ncs)
{
/*get the parsed payload data*/
if (op_cm_validate(config) !=0 ){
        ERR("The payload data check failed!");
        goto finish;
        }
}
```

3. The implementation of ```op_cm_validate(config) ``` is a c file.
```
# cat op_cm_validate.c 

#define _GNU_SOURCE
#include <assert.h>
#include <errno.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "log.h"

int
op_cm_validate(struct lyd_node *config){
        if(config == NULL) {
           return -1;
        }
        VRB("Do the check about the payload data \n");
       
        return 0;
}

```

3. My method is very simple and the new added function op_cm_validate will be called for the edit-config operation and copy-config operation(when the copy-config source is config file), not sure my solution is OK for the request?

Thanks
Darcy

**Comment by darcyllingyan** [comment]
Hi Michal,
Thanks very much for the response! I understood.
Thanks
Darcy
