### ISSUE TITLE
Getting a list of uncommited changes

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#1330]
Is it feasible to retrieve a set of "pending" changes, i.e., changes performed by calls to `sr_set_value` etc which have not been committed yet to the target datastore (via `sr_commit`)?

@syyyr already checked that `sr_get_changes_iter` works as documented :), only providing the diff from  modification-callback session, but a functionality like this would be nice to have for a local CLI.

How hard is this going to be?

**Comment by michalvasko** [comment]
Hi Jan,
in this case you have only the first solution from #1316, creating an API that would expose internal information. The operations (sort of like `diff`) are retrieved by function `data_manager.c:dm_get_session_operations():2011`. For an actual diff you would have to retrieve the current configuration and `lyd_diff()` it manually with the data tree returned in the structure by `data_manager.c:dm_get_data_info():3043`.

Regards,
Michal
