### ISSUE TITLE
If define the module name as ietf-yang-types, the module can't be imported by other modules

### ISSUE THREAD

**Issue by darcyllingyan** [sysrepo/sysrepo#1332]
Hi,
Not sure whether there are some restrictions about the module naming rule. When I use the module name as ietf-yang-types, it can't be imported successfully by other modules.
For example:
1. The yang t1.yang:
```
[root@netcon-test ~]$ # cat t1.yang
module t1 {
  namespace "http://qingdao_cnet.com/ns/example/users";
  prefix users;
  import ietf-yang-types{prefix "t2";}
  container users {
    list user {
      key name;
      leaf name {
        type string;
      }
      leaf password {
        type string;
        mandatory true;
      }
      leaf role {
        type string{
          length 1..15;
          pattern '[\p{IsBasicLatin}]+';
        }
        mandatory true;
      }
      leaf time {
        type t2:date-and-time;
     }
    }
  }
}
```
2. The ietf-yang-types.yang and t2.yang:
```
# cat ietf-yang-types.yang 
module ietf-yang-types {
  namespace "urn:ietf:params:xml:ns:yang:ietf-yang-ty";
  prefix "t2";
  typedef date-and-time {
    type string {
      pattern '\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?'
            + '(Z|[\+\-]\d{2}:\d{2})';
    }
}
}

# cat t2.yang 
module t2 {
  namespace "urn:ietf:params:xml:ns:yang:ietf-yang-ty";
  prefix "t2";
  typedef date-and-time {
    type string {
      pattern '\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?'
            + '(Z|[\+\-]\d{2}:\d{2})';
    }
}
}

```
3. The t1.xml is:
```
# cat t1.xml
<users xmlns="http://qingdao_cnet.com/ns/example/users">
    <user>
        <name>ssss</name>
        <password>1111</password>
        <role>aaa</role>
        <time>1985-04-12T23:20:50.52Z</time>
    </user>
    <user>
        <name>hunter</name>
        <password>3333</password>
        <role>aaa</role>
         <time>2000-04-12T23:20:50.52Z</time>
    </user>
    <user>
        <name>jerry</name>
        <password>4444</password>
        <role>ccc</role>
        <time>2002-04-12T23:20:50.52Z</time>
    </user>
  </users>
```
4. When I install the t1.yang, the ietf-yang-types can't be imported:
```
#  sysrepoctl --install --yang=t1.yang --owner=root:root --permissions=666
Installing a new module from file 't1.yang'...
Installing the YANG file to '/etc/sysrepo/yang/t1.yang'...
Installing data files for module 't1'...
Notifying sysrepo about the change...
Install operation completed successfully.

# sysrepocfg --merge=t1.xml --format=xml t1 --datastore=startup
[ERR] Unable to parse the input data: Failed to store value "1985-04-12T23:20:50.52Z" of user type "date-and-time". ((null))
Errors were encountered during importing. Cancelling the operation.
```
5. If I change the ietf-yang-types to t2, the module could be imported successfully:
```
# sysrepoctl --install --yang=t1.yang --owner=root:root --permissions=666
Installing a new module from file 't1.yang'...
Installing the YANG file to '/etc/sysrepo/yang/t1.yang'...
Resolving dependency: 't1' imports 't2'...
Installing the YANG file to '/etc/sysrepo/yang/t2.yang'...
Installing data files for module 't1'...
Resolving dependency: 't1' imports 't2'...
Skipping installation of data files for module 't2'...
Notifying sysrepo about the change...
Install operation completed successfully.

# sysrepocfg --merge=t1.xml --format=xml t1 --datastore=startup
The new configuration was successfully applied.
```

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
this behavior is expected because by default, there already is a module name `ietf-yang-types` in every libyang context, so in your case it got imported instead of the one you wrote yourself. If you want to import your model, you can do so if you specify its revision and then import this specific revision of `ietf-yang-types`.

However, it is important to note that module collision names are **strongly** discouraged because they can cause a lot of problems. You should name your module some other way, which would even fix this issue.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
Thanks for your response! I will rename the module ```ietf-yang-types ``` to other names to avoid the collision.

I have another question, the```ietf-interfaces@2014-05-08``` module with  is also installed in the libyang context, if I want to install one ```ietf-interfaces@2017-01-15``` module, I need to uninstall ```ietf-interfaces@2014-05-08```,  I want to confirm whether it's OK to update the pre-installed yang file?

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
`ietf-interfaces` is not installed in *libyang* context by default, it is only installed in *sysrepo* by default (if you enable tests). Best is to disable tests if you do not want them and it will not get installed. Also, you can simply uninstall it using `sysrepoctl` but that will break many tests, so do not run them afterwards.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
Thanks very much Michal.
I will disable tests.

Thanks
Darcy
