### ISSUE TITLE
the wait time may be incorrect if the system changed by ntp or gps,as we used CLOCK_REALTIME in function dm_wait_for_commit_context_to_be_empty

### ISSUE THREAD

**Issue by ZhaoGuangYue1986** [sysrepo/sysrepo#1335]
the wait time may be incorrect if the system changed by ntp or gps,as we used CLOCK_REALTIME in function dm_wait_for_commit_context_to_be_empty.

For example, if the time changed to 13:35:35 from 15:35:35 the thread may be wait 2 hours and 30 second, is it right?

**Comment by michalvasko** [comment]
Hi,
it is fine, same reasoning as in [another issue](https://github.com/CESNET/libnetconf2/issues/108).

Regards,
Michal
