### ISSUE TITLE
Question - Is there any other way to set instead of leaf units?

### ISSUE THREAD

**Issue by min9kyu-park** [sysrepo/sysrepo#1336]
Hi, 
I am reviewing code and testing to understand the architecture and the operating of sysrepo.
When i check, sysrepo seems to support only leaf units for setting data, right?

If so, if there are a lot of data to set, sysrepo will be busy to process frequently occurring messages in leaf units.
If i want to set a list, is there any other way to set at once?

Thanks,
Mr.Park

**Comment by michalvasko** [comment]
Hi,
no, in the current sysrepo you must create list entries one-by-one. However, in the new sysrepo generation (that we are currently working on) these small edits will perform much less work so creating it this way should not be a problem. Additionally, there will be a way of creating a bunch of lists (even with leaves or whatever) in one API call for the best efficiency if desired.

Regards,
Michal

**Comment by min9kyu-park** [comment]
Thank you for your reply.

Can i know about the schedule of the new sysrepo generation?
And Could you describe more detail about new sysrepo generation?

**Comment by michalvasko** [comment]
Hi,
by the end of the year we would like to have the first functioning version of the new sysrepo with some of the more advanced features missing. I cannot tell you exactly when it will go public but my estimate is at least several more months after that.

Regarding the changes compared to the current sysrepo, I can summarize them shortly. Our main focus was to make it more simple, reliable, efficient, and small. That means, in specific terms, that we decided to not have any central daemon and it will just be a library. Another important change is that we are using shared memory for communication between sysrepo clients for better scaling when there are many clients (subscribers). Also, the API will not change in principle, mostly just some minor refactoring.

Regards,
Michal

**Comment by michalvasko** [comment]
New *sysrepo* released.
