### ISSUE TITLE
Notification query

### ISSUE THREAD

**Issue by rosy8** [sysrepo/sysrepo#1340]
Hi Michal,

I am trying to generate an event notification.
The event gets saved properly in the  corresponding xml file (/etc/sysrepo/data/notification/...)
However notification is not received on the client (MgSoft browser).
 By looking at the debuglog, what i am finding the subscription list as NULL.

Mar 13 20:19:31  sysrepod[2671]: [WRN]  subscription List NULL notification
 (Function - rp_event_notif_req_process ).
Would appreciate if you could let me know what could be possible reason for this.

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
I would need to know much more to help you. Mainly, how did you subscribe to receive notifications? Directly to `sysrepod` or to `netopeer2-server`?

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

Thank you for reverting back.
This was because of some issue in my code base..
Its working fine now..
Thank you.

Regard's
-Rosy
