### ISSUE TITLE
different subscriptions in one daemon process are executed serially

### ISSUE THREAD

**Issue by chunlovemail** [sysrepo/sysrepo#1341]
### Things you may try first
(put "x" in "[]" if you already tried following)
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description
Different subscriptions in one daemon process are executed serially.
`subtree_change_subscribe_callback`, `rpc_subscribe_callback`, `dp_get_items_subscribe_callback` are excuted serially, even they are in different module(means different namespace)

### Steps to Reproduce
1. Run a daemon process, call `sr_subtree_change_subscribe` to register config change, call `sr_rpc_subscribe` to register rpc. Note that they are in different module
2. Sleep 5 seconds in subtree_change_callback
3. Run a client to set value and commit
4. Run another client to send rpc

**Expected behavior:**
RPC and set operation are executed in parallel. 
From the sysrepo `cl_subscription_manager.c` function` cl_sm_get_server_ctx()`, we can see that different module-name, the subscription has different fd in client process(daemon/application).
It means that the `subtree-change-subscription` and `rpc-subscription` has different fd.

**Actual behavior:**
The `rpc-callback` waits the` subtree-change-callback` execution.
They are executed serially

**Code**
From the log in` sr_daemon_main_log.txt`(in attachment) , wo know that when daemon process `exexutes cl_sm_fd_read_cb()`, it cannot read another `fd`. So the msg in Daemon process are in serial. 
Is that a functional limitation by `EVENT_LOOP`? 

### Versions
```
chuny@SHASTA-2:~/shasta/apps_pub/sysrepo/tests/yang$ sysrepod -v
sysrepod - sysrepo daemon, version 0.7.4
```

### Attachments
[attachments.zip](https://github.com/sysrepo/sysrepo/files/2546804/attachments.zip)

1.test-module.yang (subtree-change)
2.test-module-1.yang (rpc)
3.sr_daemon_main.c
4.sr_set_decimal64.c
5.sr_rpc_test.c
6.sr_daemon_main_log.txt

Thanks!

**Comment by michalvasko** [comment]
Hi,
AFAIK this is a *sysrepo* limitation of strictly having only 1 thread for each client. Anyway, we are currently working on a new *sysrepo* that will support (almost) arbitrary thread configuration, so the current *sysrepo* will not be improved as it will become obsolete (in around half a year).

Regards,
Michal

**Comment by chunlovemail** [comment]
Hi Michal,
    Another question, is the new `sysrepo` API same as the old?
    When transplant the old `sysrepo` to the new `sysrepo`, how is the impact?
    As I know, the difference between the `netopeer` and `netopper2` is large.

Regards
chuny

**Comment by chunlovemail** [comment]
Hi Michal,

    I got it, thank u very much ^_^

Regards,
Chuny
