### ISSUE TITLE
Question - Migration regarding yang module changes

### ISSUE THREAD

**Issue by min9kyu-park** [sysrepo/sysrepo#1342]
Hi,
I wonder how sysrepo performs operations related to migration when the yang model is changed.

For example, there are yang module and persistent data in N version. and i want to modify yang module at N+1 version.
How can i migrate N data to N+1 data?

**Comment by michalvasko** [comment]
Hi,
there is no direct support for this so you should export the existing data, remove the model, install the updated one and then import the data back. However, if there are some incompatible changes and the import fails, you will have to edit the data manually first.

Regards,
Michal

**Comment by michalvasko** [comment]
Supported now.
