### ISSUE TITLE
Question - Validation check during change data.

### ISSUE THREAD

**Issue by min9kyu-park** [sysrepo/sysrepo#1343]
Hi,
Does sysrepo support validation check during changing data?
For example...

The A application want to write leaf_A. but The B application want to abort this transaction becuase of some reason like the status of system.

Is there any way to do this?

**Comment by jktjkt** [comment]
Adding to what @michalvasko said, this will also bring one small behavior change. This will also open the `leaf_A` for modifications even when the "real listener", the `A` application, is not running for some reason.

**Comment by charach** [comment]
Hi jktjkt.
I'm sorry , but i can't understand the meaning of 'open'.
Would you explain more detail? 

Thanks you.

**Comment by michalvasko** [comment]
Hi,
what @jktjkt meant was that `leaf_A` will be *enabled*. sysrepo differentiates between *disabled* and *enabled* data. They are disabled by default and cannot be written to in the `running` datastore. If there is a subscription for them, they become enabled and can be written to.

Regards,
Michal
