### ISSUE TITLE
Sysrepocfg --get error

### ISSUE THREAD

**Issue by charach** [sysrepo/sysrepo#1345]
when i use this command.

root@root : sysrepocfg --get xx-xx-xx --format=json
sysrepocfg: Module 'x-xx-xx' is not installed.

I found that sysrepocfg --get delete first character of module name.

if i use xxx-xx-xx then 
Cannot operate on the running datastore for 'xx-xx-xx' as there are no active subscriptions for it.
Canceling the operation.

I think sysrepocfg --get have a error to get a string from user.

Thanks you

**Comment by michalvasko** [comment]
Hi,
the *sysrepocfg* help says you are supposed to specify XPath as the parameter of `get`, just `<module-name>` is not an XPath.

Regards,
Michal
