### ISSUE TITLE
Failed to resolve identityref defined in different module

### ISSUE THREAD

**Issue by GuoyouZhang** [sysrepo/sysrepo#1346]
i see there are some old issue similar to this, but looks the issue is still existing.

[test.zip](https://github.com/sysrepo/sysrepo/files/2562816/test.zip)

 sysrepocfg --import=addif.xml ietf-interfaces  // this success

sysrepocfg --import=fail.xml ietf-microwave-radio-link
[ERR] Unable to parse the input data: Failed to resolve identityref "carrier-termination". (/ietf-interfaces:interfaces/interface[name='CT-1-1-1']/type)
Errors were encountered during importing. Cancelling the operation.

and i already installed related model in to sysrepo:

sysrepoctl -l
...
iana-if-type               | 2015-06-12 | Installed   |                     |             |                               |
ietf-microwave-types       | 2018-10-03 | Installed   |                     |             |                               |
ietf-microwave-radio-link  | 2018-10-03 | Installed   | root:root           | 666         |

**Comment by michalvasko** [comment]
Hi,
try to change line
```xml
<type xmlns:mw-types="urn:ietf:params:xml:ns:yang:ietf-microwave-types">carrier-termination</type>
```
to
```xml
<type xmlns:mw-types="urn:ietf:params:xml:ns:yang:ietf-microwave-types">mw-types:carrier-termination</type>
```

Regards,
Michal
