### ISSUE TITLE
When don't install the swig, the sysrepo build error

### ISSUE THREAD

**Issue by darcyllingyan** [sysrepo/sysrepo#1348]
Hi,
In the sysrepo INSTALL.md, it shows the SWIG is optional. But when I pull the newest sysrepo code and build, it always reports the Swig is missing and after I install it, the sysrepo building passed.
Whether the Swig is mandatory now?

```
(Optional) Bindings for other languages:
Swig must be installed. Bindigs are generated during make phase.

Python bindings require python-dev to be installed.
Lua bindings require lua5.2 to be installed.
```

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
try running `cmake` with `-DGEN_LANGUAGE_BINDINGS=OFF`.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
Thanks, it works!

Thanks
Darcy
