### ISSUE TITLE
[Query] How to get callbacks invoked startup data.

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1350]
HI,

When I subscribe for any module Startup data will be copied to running. Is there a way to get this whole configuration to subscriber callbacks.

Saved configuration gets copied to running after reboot but that wont be applied to system as no subscriber getting called.

Please help.

Thanks!
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
use `SR_SUBSCR_EV_ENABLED ` flag for the subscription.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thank you very much for the quick reply.

With this flag does `get_changes` API gives whole changes as ADDED?

Thanks,
Sriram.K

**Comment by sriramkandukuri** [comment]
Thank you very much
