### ISSUE TITLE
The usage of presence container

### ISSUE THREAD

**Issue by charach** [sysrepo/sysrepo#1353]
Hi, 

The meaning of the presence container is "presence" statement (see Section 7.5.5) is used to give
   semantics to the existence of the container in the data tree." at RFC6020.

I want to know the different of "presence container" and "non-presence container" at sysrepo.

Thanks you.

**Comment by michalvasko** [comment]
Hi,
all the differences are explained in the YANG 1.1 [RFC 7950](https://tools.ietf.org/html/rfc7950). In specific terms, you cannot create NP (non-presence) container while creating P (presence) container works just fine as the former has no semantic meaning and the latter has. Also, NP container exists implicitly if its data schema parent exists, which is not true for P containers.

Regards,
Michal
