### ISSUE TITLE
The naming rule of sr_conn_ctx_t

### ISSUE THREAD

**Issue by charach** [sysrepo/sysrepo#1359]
What is the rule for naming sr_conn_ctx_t in " sysrepo/src/clientlib/cl_common.c"?

at cl_common.c:cl_conn_add_session(sr_conn_ctx_t *connection, sr_session_ctx_t *session)

used connection ,

but cl_common.c:cl_conn_msg_buf_expand(sr_conn_ctx_t *conn_ctx, size_t required_size)

used conn_ctx.

Is there any reason for naming for variable?

If you want to change it, than i want to change the name of variable in sysrepo.

Thanks you

**Comment by michalvasko** [comment]
Hi,
I do not think there is any special reason for the different names other than it was possibly named by 2 people. Anyway, they are all internal functions, what do you care how they are named?

Regards,
Michal
