### ISSUE TITLE
Limit callback reister

### ISSUE THREAD

**Issue by ParkDerkYoul** [sysrepo/sysrepo#1360]
Hi,

I saw that netconf1 had a restriction on the registration of the callback.
    " src/datastore.c : 3694
      #define MAPPING_SIZE 26+1 /* # of letters used as prefixes + terminating item */ "
However, I can not find anything that is limited by sysrepo.
Is sysrepo limited in the number of callback registration?

**Comment by michalvasko** [comment]
Hi,
I do not know about any such limitation, why are you asking?

Regards,
Michal

**Comment by ParkDerkYoul** [comment]
Hi, Michal.

I wanted to use a lot of callbacks, but Netconf1 were limit.
So, I am about to change Netconf1 to Netconf 2.
I needed confirmation.

thanks.
