### ISSUE TITLE
The "must" check issue when the number of ENUM is big

### ISSUE THREAD

**Issue by darcyllingyan** [sysrepo/sysrepo#1363]
Hi,
I met a strange issue about the ```must``` check with a big number of ENUM, below is the example:
1. 
Below are three yang files, the test2.yang imports charg-types.yang, the charg-types.yang imports cha-extensions.yang.

[test2.yang.txt](https://github.com/sysrepo/sysrepo/files/2602761/test2.yang.txt)
[cha-extensions.yang.txt](https://github.com/sysrepo/sysrepo/files/2602762/cha-extensions.yang.txt)
[charg-types.yang.txt](https://github.com/sysrepo/sysrepo/files/2602763/charg-types.yang.txt)

2. Below is the XML file:
```
# cat test2.xml
<test2 xmlns="http://qingdao_cnet.com/ns/test2/example">
    <user>
        <name>darcy</name>
        <field-name>nokia-extension</field-name>
        <format-line>in_data_type=word_c|in_length=2|out_data_type=word_c|out_length=2|field_id=2C|field_offset=1</format-line>
        <identifier>1</identifier>
    </user>
</test2>
```
3. Install the three yang files and connect to netopeer2-server with netopeer2-cli, the ```edit-config``` is OK, but the get-config reports error, after check the sysrepod log, it reports the error-message in must check.
```
[ERR] libyang error: Must condition "(../field-name = 'nokia-extension' and ../format-line) or (../field-name != 'nokia-extension' and not(../format-line))" not satisfied.
[ERR] libyang error: yyyFormat-line parameter is mandatory if the cdr field is 'nokia-extension' otherwise it is prohibited.
```
The expected result is:
get-config is OK.

The netopeer2-cli process:
```
> get-config --source running
DATA
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <listen>
    <endpoint>
      <name>all-interfaces</name>
      <ssh>
        <address>0.0.0.0</address>
        <port>830</port>
        <host-keys>
          <host-key>
            <name>imported SSH key</name>
            <public-key>ssh_host_rsa_key</public-key>
          </host-key>
        </host-keys>
      </ssh>
    </endpoint>
  </listen>
</netconf-server>

> edit-config --target running --config=/root/test/test2.xml
OK
> get-config --source running
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  np2srv_sr_get_items_iter failed (sysrepo: Sysrepo-internal error).
```

note: When I decrease the number of ENUM in charg-type.yang, the get-config is OK, I'm not sure whether there is number limination.

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
so I have finally found the problem, just a stupid mistake of mine (the referenced commit).

However, I have also committed a fix for the models you provided for these issues, we had a limitation of 256 extension instances for a node, there were more. So, it should work fine now and it is very likely your other crashes while loading these models were caused by this. You can try again and hopefully nothing will crash anymore.

Regards,
Michal

**Comment by michalvasko** [comment]
Actually, increasing extension instance size changed libyang ABI so I have reverted this change back. I think it may not even be required because your use-case does not really make sense. You instantiated the same extension 261-times in one node (the type). What would make sense is to instantiate it once for every `enum` value. Is this intentional or not?

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
Really thanks very much for the effort.
You mean it isn't the issue of the number of ```enumeration```, but the number of the extension for one node?

> What would make sense is to instantiate it once for every enum value.

You mean it's better to define 261 extension for the 261 ```enum``` value? For example, now we instantiated the same extension ``` cha-ext:cdr-field-parameters``` for different ```enum``` :
```
            enum conn-duration-ten-ms;
            cha-ext:cdr-field-parameters "conn-duration-ten-ms,byte_c,4,001f";
            enum dialogue-type;
            cha-ext:cdr-field-parameters "dialogue-type,byte_c,1,0020";
```
It's better for us to instantiate different extensions for every ```enum```, or other ways to instantiate once?:
```
            enum conn-duration-ten-ms;
            cha-ext:cdr-field-parameters1 "conn-duration-ten-ms,byte_c,4,001f";
            enum dialogue-type;
            cha-ext:cdr-field-parameters2 "dialogue-type,byte_c,1,0020";
```



Thanks
Darcy

**Comment by darcyllingyan** [comment]
Hi Michal,
Thanks very much for the detailed response, I understand now.

Thanks
Darcy

**Comment by michalvasko** [comment]
Okay, so I take it you do not need the support for more than 256 extensions in one YANG statement.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Yes, I will try the below format, if it's OK, I will use the format to avoid the issue.
```
type enumeration {
    enum conn-duration-ten-ms {
        cha-ext:cdr-field-parameters "conn-duration-ten-ms,byte_c,4,001f";
    }
    enum dialogue-type {
        cha-ext:cdr-field-parameters "dialogue-type,byte_c,1,0020";
    }
}
```
