### ISSUE TITLE
Want to confirm the release of sysrepo

### ISSUE THREAD

**Issue by darcyllingyan** [sysrepo/sysrepo#1364]
Hi Michal,

> I would just like to add that we are happy about any contribution, mainly in testing, writing new test cases, or even creating pull requests with patches for existing bugs. However, I would like to ask you to wait with helping us with sysrepo because we are currently working on a new sysrepo version that will significantly differ from the current one (but mainly internally, API will stay more-or-less the same) so there is not much use working on the current sysrepo.

You said there will be a new sysrepo version which will signaificantly differ from the current one, now the release version is ```Version 0.7.6```,  which isn't the same with the current devel branch, right?

when will you publish the new version?
What are the most signaificantly changes in the new version for users' usage?
Whether the changes impact the connection and communication with Netopeer2?

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
there are a few changes in the sysrepo `devel` but they are not too significant and the version is the same for now, `0.7.6`.

We want to have the new sysrepo completely ready in Q2 2019 (with all the features of the current sysrepo). API will not change much so the most significant changes will be no central `sysrepod` daemon, it will be just a client library, probably no dependencies except for *libyang*, and all the communication between processes (clients) will occur using shared memory. Also, we are hoping for less memory usage and higher performance.

*netopeer2* will, naturally, be affected in the way how it uses the *sysrepo* library. However, the NETCONF end will not change, so for the user there will be no difference (*netopeer2-cli* will not change at all).

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
I have another question about the sysrepod, libyang, libnetconf, Netopeer2 release.
Now, the sysrepo has change the version from 0.7.6 to 0.7.7
The Netopeer2-server has changed from v0.6-r1 tp 0.7-r1.
libyang and libnetconf didn't change the release number.
after check the release from:
https://github.com/CESNET/Netopeer2/releases
https://github.com/sysrepo/sysrepo/releases
https://github.com/CESNET/libyang/releases
https://github.com/CESNET/libnetconf2/releases

After compared, though the libyang and libnetconf2 didn't change the release number, but there are many gaps between devel-branch and the source code in ```version 0.16 - release 2``` and ```version 0.12 - release 1```.

Whether the ```version 0.16 - release 2``` and ```version 0.12 - release 1``` will get the newest code change from devel-branch?

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
we wanted to make only *sysrepo* release but there was an API change so the latest release of *netopeer2-server* would not be compatible and hence we had to release it too. To answer you, we are not planning a release of *libnetconf2* nor *libyang* in the next days.

Generally, you can follow 3 patterns of using all this software. For least updating you can always take the latest release and the libraries/applications will be compatible. If you always want to have all the bugfixes, you should use `master` branches and they will be compatible. Finally, if you want to always be completely up-to-date, you can use `devel` branches that may or may not even have some API or simply some additional changes compared to `master`. They, again, will be compatible with each other.

Regards,
Michal
