### ISSUE TITLE
NACM: No "access-denied" error-tag.

### ISSUE THREAD

**Issue by frimpler** [sysrepo/sysrepo#1372]
### Overview
The subject in the headline refers to RFC8341, ch.3.4.3. and 3.4.4. and applies usually to the whole stack with netopeer2-server, sysrepo, etc. (reason for putting it here is a test case I wrote for sysrepo, reproducing the initial problem). This report addresses two apparent problems:
    - multiple and misleading error-messages in rpc-reply
    - wrong error-tag in rpc-reply

### Scenario
If a unprivileged user session (NACM enabled) tries to create a leaf in ietf-system (and nothing else), misleading and multiple error messages are returned to the netconf client in rpc-reply message.
The "access-denied" tag is missing, instead, "operation-failed" is returned. 
#### The misleading message is:
"User 'sysrepo-user1' was blocked from creating the node '/ietf-netconf-acm:nacm' by NACM"
#### The second (correct) message is:
"User 'sysrepo-user1' was blocked from creating the node '/ietf-system:system/dns-resolver"

### Pre-Analysis
Please check this commit: https://github.com/ADTRAN/sysrepo/commit/a197852289adee6ab428ea4e9fc899415ba2d78d). The test case shows a good (ietf-interfaces) and bad case (ietf-system). In the good-case scenario, only one correct message will be produced. In the bad-case scenario, the ones mentioned above.
Even though,  ietf-system leaves have been "touched", only, the lyd_validate-process adds an empty nacm container to the data-tree. This container is responsible for the wrong error message.

### Review 
This behaviour has initially been seen as reason for not sending the correct error-tag. But reviewing the netopeer2-server code causes doubts, that the tag will be send at all:
#### Reason:
The error-tag will be created only, if sr_set_item returns SR_ERR_UNAUTHORIZED. But all what I've seen, was, that SR_ERR_UNAUTHORIZED will be returned by sr_commit, usually. But sr_commit's return value will not be used to generate the error-tag.

Regards,
Frank

**Comment by michalvasko** [comment]
Hi,
I have made a mistake when referencing the specific commits, but if you update *netopeer2* and use latest *sysrepo* `devel`, it should behave correctly.

Regards,
Michal
