### ISSUE TITLE
rhel 7

### ISSUE THREAD

**Issue by lunne** [sysrepo/sysrepo#1375]
### How to submit issue
Please use this text as a template and replace text in the sections or remove
the entire section if that does not apply to your issue. For example in case of
question or feature request, just description with some example is probably
fine. Also remember to use github's markup form properly, especially in case of
output or code listing.

### Things you may try first
(put "x" in "[]" if you already tried following)
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?
That branch did not start at all.

### Description
libyang fails to open yang files when installed on RHEL7. 
```
sysrepod[49780]: [ERR] libyang error: Opening file "/root/kea/src/kea/src/lib/yang/models/kea-dhcp4-server.yang" failed (No such file or directory).
sysrepod[49780]: [ERR] Unable to parse '/root/kea/src/kea/src/lib/yang/models/kea-dhcp4-server.yang' schema file: Opening file "/root/kea/src/kea/src/lib/yang/models/kea-dhcp4-server.yang" failed (No such file or directory).
sysrepod[49780]: [ERR] Failed to insert module into the dependency graph
kernel: traps: sysrepoctl[70438] general protection ip:7fea3920407b sp:7fffacbdb468 error:0 in libc-2.17.so[7fea390c6000+1c2000]
```

### Steps to Reproduce
1. Clean RHEL7
2. Install all dependencies 
3. scl enable devtoolset-7 bash
3 install new swig from source and not from yum as the version is faulty
4. install sysrepo  0.7.6 / 0.7.7 
5. load any yang modell

**Expected behavior:**
Expected to load the yang models into sysrepo and see then with sysrepoctl -l

**Actual behavior:**
Error, fails to load file
restarts sysrepod and the yang model is loaded.

### Versions
Please provide versions for software needed to reproduce the bug:
Sysrepo version: `sysrepod -v`.
sysrepod - sysrepo daemon, version 0.7.7
libyang version: `yanglint -v`
yanglint 0.16.52
netopeer2-server: `netopeer2-server -V` (optional)

### Attachments
Please run sysrepo daemon in debug mode and write the logs to a file. For example:
`sysrepod -d -l 4 &> sysrepod.log`.

Similarly, if Netopeer2 server is used, also provide us with its log:
`netopeer2-server -d -v3 &> netopeer2-server.log` (optional)

You're also welcomed to provide us with any other data you think may be useful.
For example:
Installed modules: `sysrepoctl -l`
Content of datastore used: check files in  Sysrepo data directory (default `/etc/sysrepo/data`).

selinux is set to disabled
all other security is disabled

Thanks!

**Comment by michalvasko** [comment]
Hi,
I have just tried it and the only problem I had was with an old installation with a different install prefix that was constantly being used. After I fully uninstalled it (you say you start with a clean system so this cannot be your problem) it all worked exactly as expected.

So, how are you exactly installing *sysrepo*, with what parameters? Then, can you please post output of `# ldconfig -p | grep libsysrepo`? Thanks.

Regards,
Michal

**Comment by lunne** [comment]
Hi,
Tried on two clean installations and the same problem. 
```
       libsysrepo.so.0.7 (libc6,x86-64) => /usr/local/lib64/libsysrepo.so.0.7
        libsysrepo.so (libc6,x86-64) => /usr/local/lib64/libsysrepo.so
```
and libyang
```
       libyang.so.0.16 (libc6,x86-64) => /usr/local/lib64/libyang.so.0.16
        libyang.so (libc6,x86-64) => /usr/local/lib64/libyang.so
```

I have installed with 
`cmake -DCMAKE_BUILD_TYPE=Debug -DGEN_LANGUAGE_BINDINGS=ON -DGEN_CPP_BINDINGS=ON -DGEN_PYTHON_BINDINGS=OFF -DGEN_LUA_BINDINGS=OFF -DENABLE_TESTS=OFF ..
`
also tried with BUILD_TYPE=Release

**Comment by michalvasko** [comment]
Okay, so what is exactly the scenario? You have installed *sysrepo*, have `sysrepod` running and then you try to install a new model which causes `sysrepod` to crash with the output in your first post? And if you then restart `sysrepod` it works fine?

Regards,
Michal

**Comment by lunne** [comment]
It does not crash, it is not able to load the yang models and says the file does not exist. Sysrepod is still running but if i do sysrepoctl -l the yang models is not loaded.

If i restart it the yang-model is loaded but I have not verified the function of it. going to install netopeer and try functionality now.

**Comment by lunne** [comment]
This i solved. If I skip running sysrepo from systemctl it works. Kind of weird that I did not test this but.. anyhow.
I have been using your systemctl service found at:  sysrepo/deploy/systemd/sysrepod.service

If i comment out the Private/Protect parts it works.

```
[Unit]
Description=Sysrepo YANG configuration storage and management
After=syslog.target network.target

[Service]
Type=forking
ExecStart=/usr/bin/sysrepod
PIDFile=/var/run/sysrepod.pid
#PrivateTmp=yes
#PrivateDevices=yes
#ProtectSystem=yes
#ProtectHome=yes
#SystemCallArchitectures=native

[Install]
WantedBy=multi-user.target
```

**Comment by michalvasko** [comment]
Hi,
so it works for you now, good. Thanks for letting us know what the problem was.

Regards,
Michal
