### ISSUE TITLE
Question: SSH connection timeout

### ISSUE THREAD

**Issue by darcyllingyan** [sysrepo/sysrepo#1378]
Hi,
I have a question about the connection timeout setting, when the netopeer2-cli connects to the netopeer2-server, what is the timeout value?
After check the code,  in ```libnetconf2/python/rpc.c```, whether the variable is the connection timeout values? 
```
#define TIMEOUT_RECV 10000 /* 10 second */
```

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
yes, that is an example of a timeout passed directly as a parameter to an API function. If the expected event (in this case a reply) does not happen after this time is elapsed, the function returns with a timeout error. However, there are several other various timeouts that are used in some other situations.

Regards,
Michal
