### ISSUE TITLE
Question: the Rollback support issue

### ISSUE THREAD

**Issue by darcyllingyan** [sysrepo/sysrepo#1379]
Hi,
For the sysrepo&netopeer2, it doesn't support the rollback and cancel-commit now, right?
Is there any plan to implement it? 

Thanks
Darcy

**Comment by darcyllingyan** [comment]
Hi Michal,
Thanks for the confirmation.
 Because I saw one TODO list, with the item 1  I thought the rollback isn't supported:
https://github.com/sysrepo/sysrepo/wiki/TODO-List

"-- 1. Confirmed commit / rollback support
Add support for rollback of committed changes. See https://tools.ietf.org/html/rfc6241#section-8.4":

If it supports, how shall I operate as after check the netopeer2-cli command list, there is no command line which is used to do the rollback or there is some guide for me to refer to? Thanks!
```
> help
Available commands:
  auth            Manage SSH authentication options
  knownhosts      Manage the user knownhosts file
  cert            Manage trusted or your own certificates
  crl             Manage Certificate Revocation List directory
  outputformat    Set the output format of all the data
  searchpath      Set the search path for models
  verb            Change verbosity
  version         Print Netopeer2 CLI version
  disconnect      Disconnect from a NETCONF server
  status          Display information about the current NETCONF session
  connect         Connect to a NETCONF server
  listen          Wait for a Call Home connection from a NETCONF server
  quit            Quit the program
  help            Display commands description
  editor          Set the text editor for working with XML data
  cancel-commit   ietf-netconf <cancel-commit> operation
  commit          ietf-netconf <commit> operation
  copy-config     ietf-netconf <copy-config> operation
  delete-config   ietf-netconf <delete-config> operation
  discard-changes ietf-netconf <discard-changes> operation
  edit-config     ietf-netconf <edit-config> operation
  get             ietf-netconf <get> operation
  get-config      ietf-netconf <get-config> operation
  kill-session    ietf-netconf <kill-session> operation
  lock            ietf-netconf <lock> operation
  unlock          ietf-netconf <unlock> operation
  validate        ietf-netconf <validate> operation
  subscribe       notifications <create-subscription> operation
  get-schema      ietf-netconf-monitoring <get-schema> operation
  user-rpc        Send your own content in an RPC envelope (for DEBUG purposes)
  timed           Time all the commands (that communicate with a server) from issuing a RPC to getting a reply
  ?               Display commands description
  exit            Quit the program
```

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
what exactly did you mean by `rollback`? There is such operation defined anywhere so you simply meant `<cancel-commit>`? The capability `confirmed-commit` is not supported so neither is anything that [section](https://tools.ietf.org/html/rfc6241#section-8.4). What I meant by `rollback` was restoring previous state after an error during `<commit>` processing.

Also, you can see `<cancel-commit>` in *netopeer2-cli* help because if it communicates with a server that supports it, so does our CLI. However, *netopeer2-server* does not (if you try to execute it while connected to *netopeer2-server* you should be informed about this).

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,

I thought the rollback means backup the configuration data for one state, and then restore to that specified state when rollback. I know your meaning of rollback is the "rollback-on-error" based on the netconf standard.  

Thanks
Darcy
