### ISSUE TITLE
Question: RPC output with list having no key.

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1380]
After executing RPC action, I am getting RPC output in xml format as below

```
<a>
    <b>x1</b>
    <c>1</c>
</a>
<a>
    <b>x2</b>
    <c>2</c>
</a>
```

where its yang as below

```
output {
    list a {
        leaf b;
        leaf c;
    }
}
```

How can i convert this XML to value list and give back to sysrepo.

**Comment by michalvasko** [comment]
Hi,
I would have to know much more about your situation to help. You have a *sysrepo* client that subscribed to handling a particular RPC with `sr_rpc_subscribe()` and in the callback `sr_rpc_cb()` you get the answer from some other application in the form of the XML you presented? And you are asking how to transform that XML into `sr_val_t **output` and `size_t *output_cnt` output parameters of the callback?

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Yes exactly.

**Comment by michalvasko** [comment]
Hi,
you can take a look at function from [this header](http://www.sysrepo.org/static/doc/html/values_8h.html), they may be of some use. But you can always create those structures manually, they have public definitions.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Instead of creating `sr_val_t **` is there a way to build these values using libyang xml parse APIs?

**Comment by sriramkandukuri** [comment]
Hi Michal,

Sorry for opening this after long time.

As suggested by you I have used APIs from `values.h`

`sr_val_t **` with count 6 constructed with below details for above mentioned xml.

```
xpath : rpc/a type : SR_LIST_T
xpath : rpc/a/b val : x1
xpath : rpc/a/c val : 1
xpath : rpc/a type : SR_LIST_T
xpath : rpc/a/b val : x2
xpath : rpc/a/c val : 2
```
after returning these `sr_val_t ** , count` to sysrepo below data occured.

```
<a>
    <b>x1</b>
</a>
<a>
    <c>1</c>
</a>
<a>
    <b>x2</b>
</a>
<a>
    <c>2</c>
</a>
```
where below one is expected
```
<a>
    <b>x1</b>
    <c>1</c>
</a>
<a>
    <b>x2</b>
    <c>2</c>
</a>
```

Could you please help me to what wrong I am doing while constructing `sr_val_t **`

**Comment by michalvasko** [comment]
Hi,
I can only guess that your YANG has `list a` with key `leaf b` and another normal leaf `leaf c`. You should have then used XPath with all keys specified whenever you were addressing a list instance. Meaning, using your example:
```
xpath : rpc/a[b='x1'] type : SR_LIST_T
xpath : rpc/a[b='x1']/b val : x1
xpath : rpc/a[b='x1']/c val : 1
xpath : rpc/a[b='x2'] type : SR_LIST_T
xpath : rpc/a[b='x2']/b val : x2
xpath : rpc/a[b='x2']/c val : 2
```

If `c` is also key, you need to specify a similar second predicate for all instances, I hope you understand.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Actually there is no key specified in the list. If key is specified data looks good.
Is there a way for populating list without key.

Thanks,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
I could have read that in the issue name, sorry. Anyway, I do not think this use-case is supported. You can try subscribing to the RPC using `sr_rpc_subscribe_tree` and then reply with a sysrepo data tree, which has exact relations between nodes so it could work.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thank you, will give it a try.

**Comment by sriramkandukuri** [comment]
As of now key is mandatory for rpc output lists
