### ISSUE TITLE
How to build sysrepo example oven plugin for openWrt 

### ISSUE THREAD

**Issue by nic1225** [sysrepo/sysrepo#1381]
hi.
@mislavn
From [sysrepo  doc](http://www.sysrepo.org/static/doc/html/start_page.html)  , I see the following description: "The model and full plugin source can be found in sysrepo/examples/plugins. Once Sysrepo is built, the oven shared library is stored in examples/plugins".

but when sysrepo  compiled, no liboven.so generated. I want to do some plugins this way in openWrt system , and how to build example oven shared library.

Thanks!

**Comment by sriramkandukuri** [comment]
Hi,
If you using below makefile.
https://github.com/openwrt/packages/tree/master/net/sysrepo

Please remove 
`-DBUILD_EXAMPLES:BOOL=FALSE \`
line from `CMAKE_OPTIONS` variable in Makefile.

-Sriram.K

**Comment by mislavn** [comment]
Hi,

also you will need to copy the oven YANG file and install it. When making changes to sysrepo ( plugin or YANG model) restart sysrepo with /etc/init.d/sysrepo restart.

Regards,
Mislav

**Comment by nic1225** [comment]
Hi
when i input command 

> make package/tcpdump/clean 
make package/tcpdump/prepare 
make package/tcpdump/configure 

error occurs as following. The same thing happens when I clean up and recompile all.

> mkdir -p /home/nick/work/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.6
(cd /home/nick/work/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.6; CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/nick/work/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.6:sysrepo-0.7.6 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/nick/work/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.6:sysrepo-0.7.6 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " LDFLAGS="-L/home/nick/work/openwrt/staging_dir/target-x86_64_musl/usr/lib -L/home/nick/work/openwrt/staging_dir/target-x86_64_musl/lib -L/home/nick/work/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/usr/lib -L/home/nick/work/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/lib -znow -zrelro " cmake -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_VERSION=1 -DCMAKE_SYSTEM_PROCESSOR=x86_64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS_RELEASE="-DNDEBUG" -DCMAKE_CXX_FLAGS_RELEASE="-DNDEBUG" -DCMAKE_C_COMPILER="/home/nick/work/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/bin/x86_64-openwrt-linux-musl-gcc" -DCMAKE_C_COMPILER_ARG1="" -DCMAKE_CXX_COMPILER="/home/nick/work/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/bin/x86_64-openwrt-linux-musl-g++" -DCMAKE_CXX_COMPILER_ARG1="" -DCMAKE_ASM_COMPILER="/home/nick/work/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/bin/x86_64-openwrt-linux-musl-gcc" -DCMAKE_ASM_COMPILER_ARG1="" -DCMAKE_EXE_LINKER_FLAGS:STRING="-L/home/nick/work/openwrt/staging_dir/target-x86_64_musl/usr/lib -L/home/nick/work/openwrt/staging_dir/target-x86_64_musl/lib -L/home/nick/work/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/usr/lib -L/home/nick/work/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/lib -znow -zrelro" -DCMAKE_MODULE_LINKER_FLAGS:STRING="-L/home/nick/work/openwrt/staging_dir/target-x86_64_musl/usr/lib -L/home/nick/work/openwrt/staging_dir/target-x86_64_musl/lib -L/home/nick/work/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/usr/lib -L/home/nick/work/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/lib -znow -zrelro -Wl,-Bsymbolic-functions" -DCMAKE_SHARED_LINKER_FLAGS:STRING="-L/home/nick/work/openwrt/staging_dir/target-x86_64_musl/usr/lib -L/home/nick/work/openwrt/staging_dir/target-x86_64_musl/lib -L/home/nick/work/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/usr/lib -L/home/nick/work/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/lib -znow -zrelro -Wl,-Bsymbolic-functions" -DCMAKE_AR="/home/nick/work/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/bin/x86_64-openwrt-linux-musl-gcc-ar" -DCMAKE_NM="/home/nick/work/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/bin/x86_64-openwrt-linux-musl-gcc-nm" -DCMAKE_RANLIB="/home/nick/work/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl/bin/x86_64-openwrt-linux-musl-gcc-ranlib" -DCMAKE_FIND_ROOT_PATH="/home/nick/work/openwrt/staging_dir/target-x86_64_musl/usr;/home/nick/work/openwrt/staging_dir/toolchain-x86_64_gcc-7.3.0_musl" -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=BOTH -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_STRIP=: -DCMAKE_INSTALL_PREFIX=/usr -DDL_LIBRARY=/home/nick/work/openwrt/staging_dir/target-x86_64_musl -DCMAKE_PREFIX_PATH=/home/nick/work/openwrt/staging_dir/target-x86_64_musl -DCMAKE_SKIP_RPATH=TRUE -DCMAKE_BUILD_TYPE:STRING=Release -DUSE_AVL_LIB:BOOL=FALSE -DENABLE_TESTS:BOOL=FALSE  /home/nick/work/openwrt/build_dir/target-x86_64_musl/sysrepo-0.7.6 )
**-- Preparing systemwide build of sysrepo v. 0.7.6
-- sysrepo repository location: /etc/sysrepo
-- Could NOT find avl (missing: AVL_LIBRARY AVL_INCLUDE_DIR) 
-- libredblack will be used for binary tree manipulations.
-- Example code and YANG models will be built and installed.
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)** 
CMake Error at /home/nick/work/openwrt/staging_dir/host/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR) (Required is at
  least version "3.0.12")
Call Stack (most recent call first):
  /home/nick/work/openwrt/staging_dir/host/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /home/nick/work/openwrt/staging_dir/host/share/cmake-3.12/Modules/FindSWIG.cmake:63 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  swig/CMakeLists.txt:9 (find_package)

Thanks!

**Comment by nic1225** [comment]
hi.
    And another openWrt project that could have been compiled normally was not compiled properly because of the same problem. i think command "make package/sysrepo/clean" must clear some configuration of the linux host system.

Thanks!
