### ISSUE TITLE
sysrepoctl --install  oven.yang unsuccessful

### ISSUE THREAD

**Issue by nic1225** [sysrepo/sysrepo#1385]
hi.

I am trying to install sysrepo-0.7.7\examples\plugins\oven.yang and have encountered the following problems:

    root@OpenWrt:/etc/sysrepo/yang# sysrepoctl --install --yang=/etc/sysrepo/yang/oven.yang -p 644
    Installing a new module from file '/etc/sysrepo/yang/oven.yang'...
    Installing the YANG file to '/etc/sysrepo/yang/oven@2018-01-19.yang'...
    sh: install: not found
    Error: Unable to install the YANG file to '/etc/sysrepo/yang/oven@2018-01-19.yang'.
    Installation of schema files cancelled for module 'oven', reverting...
    Reverting the install operation...
    Deleted the schema file '/etc/sysrepo/yang/oven@2018-01-19.yang'.
    Install operation failed.

thanks!

**Comment by sriramkandukuri** [comment]
`sh: install: not found`

Looks like your system dont have `install` command.

If you are using ubuntu please install it using "sudo apt-get install coreutils"

If you are using Busybox on openwrt then you need to enable this "install" utility in openwrt Busybox config.

**Comment by nic1225** [comment]
hi. 
thank you for reply.  other yang files can install ok as following, so i think it might be other problem.

    root@OpenWrt:/etc/sysrepo/yang# sysrepoctl --install --yang=/etc/sysrepo/yang/nc-notifications@2008-07-14.yang -p 644
    Installing a new module from file '/etc/sysrepo/yang/nc-notifications@2008-07-14.yang'...
    Schema of the module nc-notifications is already installed, skipping...
    Resolving dependency: 'nc-notifications' imports 'notifications'...
    Schema of the module notifications is already installed, skipping...
    Installing data files for module 'nc-notifications'...
    Resolving dependency: 'nc-notifications' imports 'notifications'...
    Skipping installation of data files for module 'notifications'...
    Notifying sysrepo about the change...
    Install operation completed successfully.

**Comment by nic1225** [comment]
Hi,michalvasko

thank you for  your reply. In fact ,I did the same initialization as second installation when the system started, in file openwrt/feeds/packages/net/sysrepo/files/libsysrepo.default,as following:

	match=$(sysrepoctl -l | grep "oven ")
	if [ ! "$match" ]; then
		sysrepoctl --install --yang=/etc/sysrepo/yang/oven.yang -p 666
	fi

	match=$(sysrepoctl -l | grep "ietf-netconf ")
	if [ ! "$match" ]; then
		sysrepoctl --install --yang=/etc/sysrepo/yang/ietf-netconf@2011-06-01.yang -p 600
	fi
**but , only ietf-netconf installed ,no oven.yang**

	root@OpenWrt:~# sysrepoctl -l
   
    Module Name                | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
    -----------------------------------------------------------------------------------------------------------------------------------------------
    notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |
    nc-notifications           | 2008-07-14 | Installed   | root:root           | 644         |                               |
    ietf-netconf-acm           | 2018-02-14 | Installed   | root:root           | 644         |                               |
    ietf-netconf-notifications | 2012-02-06 | Installed   | root:root           | 600         |                               |
    ietf-netconf               | 2011-06-01 | Implemented | root:root           | 600         |                               | writable-running candidate rollback-on-error validate startup xpath url
    ietf-keystore              | 2016-10-31 | Installed   | root:root           | 600         |                               |
    ietf-ssh-server            | 2016-11-02 | Installed   |                     |             |                               |
    ietf-tls-server            | 2016-11-02 | Installed   |                     |             |                               |
    iana-crypt-hash            | 2014-08-06 | Installed   |                     |             |                               |
    ietf-x509-cert-to-name     | 2014-12-10 | Installed   |                     |             |                               |
    ietf-netconf-server        | 2016-11-02 | Installed   | root:root           | 600         |                               | listen ssh-listen tls-listen call-home ssh-call-home tls-call-home
    ietf-netconf-monitoring    | 2010-10-04 | Installed   | root:root           | 600         |                               |
    ietf-netconf-with-defaults | 2011-06-01 | Installed   |                     |             |                               |
    ietf-system                | 2014-08-06 | Installed   | root:root           | 600         |                               | authentication local-users
    ietf-datastores            | 2017-08-17 | Installed   |                     |             |                               |
    ietf-yang-library          | 2018-01-17 | Installed   | root:root           | 600         |                               |

**Comment by nic1225** [comment]
Hi,@michalvasko

I did another test. I cleared setup notifications@2008-07-14.yang from the boot configuration, show sysrepoctl -l with no notifications install. Then I manually installed notifications  and it worked, as following.

    root@OpenWrt:~# sysrepoctl -l
    Sysrepo schema directory: /etc/sysrepo/yang/
    Sysrepo data directory:   /etc/sysrepo/data/
    (Do not alter contents of these directories manually)
    
    Module Name                | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
    -----------------------------------------------------------------------------------------------------------------------------------------------
    ietf-netconf-acm           | 2018-02-14 | Installed   | root:root           | 644         |                               |
    ietf-netconf-notifications | 2012-02-06 | Installed   | root:root           | 600         |                               |
    ietf-netconf               | 2011-06-01 | Implemented | root:root           | 600         |                               | writable-running candidate rollback-on-error validate startup xpath url
    ietf-keystore              | 2016-10-31 | Installed   | root:root           | 600         |                               |
    ietf-ssh-server            | 2016-11-02 | Installed   |                     |             |                               |
    ietf-tls-server            | 2016-11-02 | Installed   |                     |             |                               |
    iana-crypt-hash            | 2014-08-06 | Installed   |                     |             |                               |
    ietf-x509-cert-to-name     | 2014-12-10 | Installed   |                     |             |                               |
    ietf-netconf-server        | 2016-11-02 | Installed   | root:root           | 600         |                               | listen ssh-listen tls-listen call-home ssh-call-home tls-call-home
    ietf-netconf-monitoring    | 2010-10-04 | Installed   | root:root           | 600         |                               |
    ietf-netconf-with-defaults | 2011-06-01 | Installed   |                     |             |                               |
    ietf-system                | 2014-08-06 | Installed   | root:root           | 600         |                               | authentication local-users
    ietf-datastores            | 2017-08-17 | Installed   |                     |             |                               |
    ietf-yang-library          | 2018-01-17 | Installed   | root:root           | 600         |                               |

    root@OpenWrt:~# 
    root@OpenWrt:~# sysrepoctl --install --yang=/etc/sysrepo/yang/notifications@2008-07-14.yang -p 666
    Installing a new module from file '/etc/sysrepo/yang/notifications@2008-07-14.yang'...
    Schema of the module notifications is already installed, skipping...
    Installing data files for module 'notifications'...
    Notifying sysrepo about the change...
    Install operation completed successfully.
    root@OpenWrt:~# 
    root@OpenWrt:~# 
    root@OpenWrt:~# sysrepoctl -l
    Sysrepo schema directory: /etc/sysrepo/yang/
    Sysrepo data directory:   /etc/sysrepo/data/
    (Do not alter contents of these directories manually)
    
    Module Name                | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
    -----------------------------------------------------------------------------------------------------------------------------------------------
    ietf-netconf-acm           | 2018-02-14 | Installed   | root:root           | 644         |                               |
    ietf-netconf-notifications | 2012-02-06 | Installed   | root:root           | 600         |                               |
    ietf-netconf               | 2011-06-01 | Implemented | root:root           | 600         |                               | writable-running candidate rollback-on-error validate startup xpath url
    ietf-keystore              | 2016-10-31 | Installed   | root:root           | 600         |                               |
    ietf-ssh-server            | 2016-11-02 | Installed   |                     |             |                               |
    ietf-tls-server            | 2016-11-02 | Installed   |                     |             |                               |
    iana-crypt-hash            | 2014-08-06 | Installed   |                     |             |                               |
    ietf-x509-cert-to-name     | 2014-12-10 | Installed   |                     |             |                               |
    ietf-netconf-server        | 2016-11-02 | Installed   | root:root           | 600         |                               | listen ssh-listen tls-listen call-home ssh-call-home tls-call-home
    ietf-netconf-monitoring    | 2010-10-04 | Installed   | root:root           | 600         |                               |
    ietf-netconf-with-defaults | 2011-06-01 | Installed   |                     |             |                               |
    ietf-system                | 2014-08-06 | Installed   | root:root           | 600         |                               | authentication local-users
    ietf-datastores            | 2017-08-17 | Installed   |                     |             |                               |
    ietf-yang-library          | 2018-01-17 | Installed   | root:root           | 600         |                               |
    notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |
    
    root@OpenWrt:~#

**Comment by nic1225** [comment]
hi @sriramkandukuri , @michalvasko:
when i enable "install" utility in openwrt Busybox config,it worked well.
thank you!
