### ISSUE TITLE
Sysrepo cfg with -n option and json format throwing error for unknown element.

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1386]
Hi,

I have data files with similar data in xml and json formats. Each have one unknown element(which not present in yang data model).

I have given -n option to sysrepocfg to ignore unknown elements in data file.
This works fine when the file is xml.

Where as it is throwing error if the file format is json.

**Comment by sriramkandukuri** [comment]
Thank you Michal.

**Comment by michalvasko** [comment]
Supported now.
