### ISSUE TITLE
Centos 7 sysrepo install

### ISSUE THREAD

**Issue by jdtinsley88** [sysrepo/sysrepo#1390]
I am trying to install sysrepo on Centos 7 so that I can install netconf & yang.  I have built sysrepo from source, but failing on the make portion.  The only documentation I have found so far is for debian and any other type of linux...but none for Centos.

**Comment by mislavn** [comment]
What's the error message?

**Comment by jdtinsley88** [comment]
43%] Building C object tests/CMakeFiles/test_lyb.dir/data/test_lyb.c.o

/root/libyang-0.16-r2/tests/data/test_lyb.c: In function ‘check_data_tree_next’:

/root/libyang-0.16-r2/tests/data/test_lyb.c:44:9: warning: implicit declaration of function ‘_Generic’ [-Wimplicit-function-declaration]

         LY_TREE_DFS_END(*start, *next, *elem);

         ^

In file included from /root/libyang-0.16-r2/build/src/libyang.h:40:0,

                 from /root/libyang-0.16-r2/tests/data/test_lyb.c:23:

/root/libyang-0.16-r2/src/tree_schema.h:180:27: error: expected expression before ‘struct’

     if (_Generic(*(ELEM), struct lyd_node: 1, default: 0)) {                  \

                           ^

/root/libyang-0.16-r2/tests/data/test_lyb.c:44:9: note: in expansion of macro ‘LY_TREE_DFS_END’

         LY_TREE_DFS_END(*start, *next, *elem);

         ^

/root/libyang-0.16-r2/src/tree_schema.h:187:34: error: expected expression before ‘struct’

     } else if (_Generic(*(ELEM), struct lys_node: 1, default: 0)) {           \

                                  ^

/root/libyang-0.16-r2/tests/data/test_lyb.c:44:9: note: in expansion of macro ‘LY_TREE_DFS_END’

         LY_TREE_DFS_END(*start, *next, *elem);

         ^

/root/libyang-0.16-r2/src/tree_schema.h:209:31: error: expected expression before ‘struct’

         if (_Generic(*(ELEM), struct lys_node: 1, default: 0)                \

                               ^

/root/libyang-0.16-r2/tests/data/test_lyb.c:44:9: note: in expansion of macro ‘LY_TREE_DFS_END’

         LY_TREE_DFS_END(*start, *next, *elem);

         ^

/root/libyang-0.16-r2/src/tree_schema.h:216:31: error: expected expression before ‘struct’

         if (_Generic(*(ELEM), struct lys_node: 1, default: 0)) {              \

                               ^

/root/libyang-0.16-r2/tests/data/test_lyb.c:44:9: note: in expansion of macro ‘LY_TREE_DFS_END’

         LY_TREE_DFS_END(*start, *next, *elem);

         ^

make[2]: *** [tests/CMakeFiles/test_lyb.dir/data/test_lyb.c.o] Error 1

make[1]: *** [tests/CMakeFiles/test_lyb.dir/all] Error 2

make: *** [all] Error 2

**Comment by mislavn** [comment]
What compiler are you using?

**Comment by jdtinsley88** [comment]
What command will get me the info you need??

**Comment by mislavn** [comment]
The issue is probably an old compiler:

`_Generic ( controlling-expression , association-list )		(since C11)`

**Comment by mislavn** [comment]
Please give me the output of `gcc --version`

**Comment by jdtinsley88** [comment]
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)

 

Yep, I need 4.9.  I am googling for installation info on gcc 4.9 on Centos 7 but not finding anything clear.

**Comment by jdtinsley88** [comment]
On this webpage at the bottom worked for me.  However, I did not do the update-alternatives commands.

 

https://stackoverflow.com/questions/47175706/how-to-install-gcc-4-9-2-on-rhel-7-4

**Comment by jdtinsley88** [comment]
Here is the output from make -j4  where I am getting an error–

 

make[5]: Entering directory `/root/kea-1.5.0/src/bin/dhcp4'

Making all in .

make[6]: Entering directory `/root/kea-1.5.0/src/bin/dhcp4'

  CXXLD    kea-dhcp4

./.libs/libdhcp4.a(dhcp4_parser.o): In function `isc::dhcp::Dhcp4Parser::parse()':

/root/kea-1.5.0/src/bin/dhcp4/dhcp4_parser.yy:2074: undefined reference to `operator delete(void*, unsigned long)'

/root/kea-1.5.0/src/bin/dhcp4/dhcp4_parser.yy:278: undefined reference to `operator delete(void*, unsigned long)'

/root/kea-1.5.0/src/bin/dhcp4/dhcp4_parser.yy:279: undefined reference to `operator delete(void*, unsigned long)'

/root/kea-1.5.0/src/bin/dhcp4/dhcp4_parser.yy:601: undefined reference to `operator delete(void*, unsigned long)'

/root/kea-1.5.0/src/bin/dhcp4/dhcp4_parser.yy:1984: undefined reference to `operator delete(void*, unsigned long)'

./.libs/libdhcp4.a(dhcp4_parser.o):/root/kea-1.5.0/src/bin/dhcp4/dhcp4_parser.yy:1687: more undefined references to `operator delete(void*, unsigned long)' follow

../../../src/lib/cc/.libs/libkea-cc.so: undefined reference to `std::runtime_error::runtime_error(char const*)'

../../../src/lib/dhcpsrv/.libs/libkea-dhcpsrv.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'

collect2: error: ld returned 1 exit status

make[6]: *** [kea-dhcp4] Error 1

make[6]: Leaving directory `/root/kea-1.5.0/src/bin/dhcp4'

make[5]: *** [all-recursive] Error 1

make[5]: Leaving directory `/root/kea-1.5.0/src/bin/dhcp4'

make[4]: *** [all] Error 2

make[4]: Leaving directory `/root/kea-1.5.0/src/bin/dhcp4'

make[3]: *** [all-recursive] Error 1

make[3]: Leaving directory `/root/kea-1.5.0/src/bin'

make[2]: *** [all-recursive] Error 1

make[2]: Leaving directory `/root/kea-1.5.0/src'

make[1]: *** [all-recursive] Error 1

make[1]: Leaving directory `/root/kea-1.5.0'

make: *** [all] Error 2

**Comment by michalvasko** [comment]
Fixed.
