### ISSUE TITLE
float type defined in YANG file, what kind of the operational type return? 

### ISSUE THREAD

**Issue by foolloow** [sysrepo/sysrepo#1391]
### Description
I write a function to return data to sysrepo.
The leaf type is float and this is no include in sysrepo, the yang installed correctly.
But i return the decimal64 or string type not correct, so what type i should use to get right respond?

**Expected behavior:**
get rpc return the data

**Actual behavior:**
no float data returns

Thanks!

**Comment by michalvasko** [comment]
Hi,
`float` type is not a basic YANG type. It could be a derived type so find the original type and use that one.

Regards,
Michal

**Comment by foolloow** [comment]
Thanks a lot.

**Comment by mashemat** [comment]
Hello, 

Can you please provide an example with float data type in yang. I mean how we can it be derived?

Kind Regards,

**Comment by michalvasko** [comment]
Hi,
I you do not need to derive anything, there is simply no `float` in YANG. You should use the `decimal64` type instead.

Regards,
Michal

**Comment by mashemat** [comment]
Thanks Michal.

**Comment by mashemat** [comment]
typedef float {
         type decimal64 {
             fraction-digits 2;
         }
     }
input
{
           leaf test {
                description "testing float.";
                type float;
                default -1;
            }
}

I receive an Error that Invalid value "-1".

**Comment by michalvasko** [comment]
Hi,
I have just tested loading such a module and saw no error.

Regards,
Michal

**Comment by mashemat** [comment]
You are right Michal. Now, I figured out the problem was somewhere else in my model.

Thanks,

**Comment by mashemat** [comment]
Hi all, 
I defined an operational element in the yang model (config false) and the corresponding callback through the sr_dp_get_items_subscribe.  How can I receive data from netopeer2-cli. I try with user-rpc but I receive this ERR

ly ERROR: Unknown element "action". 
cli_send_recv: Failed to send the RPC.

Do I receive this because it is not essentially an rpc? if yes how can I receive the value of this element.

Thanks,

**Comment by michalvasko** [comment]
Hi,
I do not know what YANG module you are using so I cannot help you. Anyway, the answer to your question can likely be found [here](https://tools.ietf.org/html/rfc7950#section-7.15).

Regards,
Michal

**Comment by mashemat** [comment]
Thanks Michal.
