### ISSUE TITLE
edit-config --target running: The node is not enabled in running datastore

### ISSUE THREAD

**Issue by nic1225** [sysrepo/sysrepo#1395]
hi,
 I tested the sysrepo example by using "oper_data_example.c" and file ietf-interfaces.yang . when loading running datastore with the example XML file  ietf-interfaces.data.xml  , the following error occur:

    > edit-config --target running --config=/etc/sysrepo/yang/ietf-interfaces.data.xml
    ERROR
            type:     application
            tag:      operation-failed
            severity: error
            path:     /ietf-interfaces:interfaces/interface[name='eth0']
            message:  The node is not enabled in running datastore
 **1) root@OpenWrt:/etc/sysrepo# sysrepoctl -l**

    Sysrepo schema directory: /etc/sysrepo/yang/
    Sysrepo data directory:   /etc/sysrepo/data/
    (Do not alter contents of these directories manually)
    
    Module Name                | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
    -----------------------------------------------------------------------------------------------------------------------------------------------
    notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |
    nc-notifications           | 2008-07-14 | Installed   | root:root           | 666         |                               |
    ietf-netconf-acm           | 2018-02-14 | Installed   | root:root           | 644         |                               |
    ietf-netconf-notifications | 2012-02-06 | Installed   | root:root           | 600         |                               |
    ietf-netconf               | 2011-06-01 | Implemented | root:root           | 600         |                               | writable-running candidate rollback-on-error validate startup xpath url
    qos                        | 2018-12-19 | Installed   | root:root           | 666         |                               |
    oven                       | 2018-01-19 | Installed   | root:root           | 666         |                               |
    iana-if-type               | 2014-05-08 | Installed   |                     |             |                               |
    ietf-interfaces            | 2014-05-08 | Implemented | root:root           | 666         |                               |
    ietf-ip                    | 2014-06-16 | Installed   |                     |             |                               |
    ietf-yang-types            | 2013-07-15 | Installed   |                     |             |                               |
    ietf-keystore              | 2016-10-31 | Installed   | root:root           | 600         |                               |
    ietf-ssh-server            | 2016-11-02 | Installed   |                     |             |                               |
    ietf-tls-server            | 2016-11-02 | Installed   |                     |             |                               |
    iana-crypt-hash            | 2014-08-06 | Installed   |                     |             |                               |
    ietf-x509-cert-to-name     | 2014-12-10 | Installed   |                     |             |                               |
    ietf-netconf-server        | 2016-11-02 | Installed   | root:root           | 600         |                               | listen ssh-listen tls-listen call-home ssh-call-home tls-call-home
    ietf-netconf-monitoring    | 2010-10-04 | Installed   | root:root           | 600         |                               |
    ietf-netconf-with-defaults | 2011-06-01 | Installed   |                     |             |                               |
    ietf-system                | 2014-08-06 | Installed   | root:root           | 600         |                               | authentication local-users
    ietf-datastores            | 2017-08-17 | Installed   |                     |             |                               |
    ietf-yang-library          | 2018-01-17 | Installed   | root:root           | 600         |                               |

**2) candidate datastore can be modified, but cannot commit .**

    > edit-config --target candidate --config=/etc/sysrepo/yang/ietf-interfaces.data.xml
    OK
    > commit 
    ERROR
            type:     application
            tag:      operation-failed
            severity: error
            message:  There is a not enabled node in ietf-interfaces module, it can not be committed to the running

**3) Data can be written to config date through the oper_data_example program .**

        sr_val_set_xpath(&v[0], "/ietf-interfaces:interfaces-state/interface[name='eth0']/type");
        sr_val_set_str_data(&v[0], SR_IDENTITYREF_T, "ethernetCsmacd");

        sr_val_set_xpath(&v[1], "/ietf-interfaces:interfaces-state/interface[name='eth0']/oper-status");
        sr_val_set_str_data(&v[1], SR_ENUM_T, "down");

        sr_val_set_xpath(&v[2], "/ietf-interfaces:interfaces-state/interface[name='eth1']/type");
        sr_val_set_str_data(&v[2], SR_IDENTITYREF_T, "iana-if-type:ethernetCsmacd");

        sr_val_set_xpath(&v[3], "/ietf-interfaces:interfaces-state/interface[name='eth1']/oper-status");
        sr_val_set_str_data(&v[3], SR_ENUM_T, "up");

View the data being written

    > get --filter-xpath /ietf-interfaces:*
    DATA
    <interfaces-state xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
      <interface>
        <name>eth0</name>
        <oper-status>down</oper-status>
      </interface>
      <interface>
        <name>eth1</name>
        <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
        <oper-status>up</oper-status>
      </interface>
    </interfaces-state>

**Comment by jktjkt** [comment]
I think that this works as exepcted. Sysrepo rejects edits to subtrees of the `running` datastore when there is no subscriber for the target subtree. When you register something to be "handling modifications" of the path that you're trying to modify, stuff will start working.

**Comment by michalvasko** [comment]
Hi,
what @jktjkt wrote is correct, I will just add a reference to the [documentation](http://www.sysrepo.org/static/doc/html/ds_page.html#rds) with some more details.

Regards,
Michal

**Comment by adamzyg** [comment]
Hi michalvasko, how to query which subtree of module subscribe?

**Comment by michalvasko** [comment]
Hi,
I am sorry but I do not understand what you are asking. How to query what subtrees of a module are subscribed? If so, then this information is not available in API.

Regards,
Michal

**Comment by ankit-ka** [comment]
Hi Michal,

If I have a datastore where I have installed a module, and if I want to change the data content related to that module, is there a way I can "subscribe" to that module or some node/subtree of that module so that the edit-config operations on that module is allowed (instead of getting rejected due to the error indicating that the node is not enabled)? Please suggest a way. 

Thanks!

**Comment by michalvasko** [comment]
Hi,
yes, there is and this is actually one of the primary functions of *sysrepo* meaning you should probably read the documentation before continuing to work with *sysrepo* to learn about its basic features. To answer you, the simplest way of subscribing to a module is using `application_example` or `application_changes_example` and use the module name as the parameter.

Regards,
Michal

**Comment by ankit-ka** [comment]
> 
> 
> Hi,
> yes, there is and this is actually one of the primary functions of _sysrepo_ meaning you should probably read the documentation before continuing to work with _sysrepo_ to learn about its basic features. To answer you, the simplest way of subscribing to a module is using `application_example` or `application_changes_example` and use the module name as the parameter.
> 
> Regards,
> Michal

Thanks Michal. Yes I realized later and did use the application_changes_example binary to test my application. Regarding the documentation on sysrepo, unfortunately the current docs do not highlight the presence of these utility tools. May be they can be listed there for easy reference. 

Appreciate your response to my query!

Regards
Ankit

**Comment by eli-halych** [comment]
@ankit-ka How did you run the application_changes_example binary to test the application?  I am having troubles with subscribing while also using Netopeer2-cli that uses sysrepo
