### ISSUE TITLE
Datastore files at multiple directory locations?

### ISSUE THREAD

**Issue by dwdrajesh** [sysrepo/sysrepo#1397]
Is it possible to specify sysrepo to use different directories for different yang modules? There is a build time value "REPOSITORY_LOCATION" that is by default /etc/sysrepo. The yang modules are copied to /etc/sysrepo/yang and the datastores to /etc/sysrepo/data.
If, lets say we have heirarchical modules in the system and we want the datastore files for different modules to be placed in different directories, is it possible to configure that at build time or at run time ?
Thanks

**Comment by michalvasko** [comment]
Hi,
no, this is not possible to configure at all.

Regards,
Michal
