### ISSUE TITLE
how to disable auto copy startup to running  datastore?

### ISSUE THREAD

**Issue by TiejunShuang** [sysrepo/sysrepo#1417]
Hi,
I wanna disable the default copy from startup to running datastore when register a module change subscribe.  How can i do it?

Thanks!
Tiejun

**Comment by michalvasko** [comment]
Hi Tiejun,
look at the [documentation](http://www.sysrepo.org/static/doc/html/group__cl.html#gac91898627ad5aeb589e6a3993a697d14), `SR_SUBSRC_PASSIVE` should achieve what you want. However, if there are no other subscribers, this module will not become enabled and hence will not allow any changes to its data. There is no other way, it cannot be simply disabled and I think that is correct.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi,
if you want to change the code, then removing the whole `if` at `notification_processor.c:1042` should do what you want, I think.

Regards,
Michal

**Comment by jktjkt** [comment]
@TiejunShuang , I wonder what you are trying to achieve here. The semantics appear to match the NETCONF RFC which is pretty clear in the meaning of these two datastores -- the `running` should indeed be initialized to whatever was in `startup` when the system boots.

On the other hand, if you just do not want your callbacks to be invoked during this "initial copy" -- are you aware of [`SR_EV_ENABLED`](http://www.sysrepo.org/static/doc/html/group__cl.html#gga94740180bfd5e1761cccc8e6485eee68a11b3249384640ee1795f861657a952fb)?

**Comment by TiejunShuang** [comment]
@michalvasko thanks , I'll try it.
@jktjkt In our system, the netconf controller will auto config all data, eg. there are 10 items need set to device.  if the device reboot after the item 5 is set and without copy configure from running to startup. At that time, the running and the startup is different and the device date match with running data store. After the device come back. Device data mismatch with data store and controller send data from item 6. 
Our solution is that only use one data store. maybe we can copy running to startup before netconf. 

Regards,
Teijun

**Comment by michalvasko** [comment]
Hi Tiejun,
I do not think you can in any way do the copy before *sysrepo*, it will ignore whatever is in the `running` when doing the copy.

Regards,
Michal

**Comment by TiejunShuang** [comment]
Hi Michal,
Do you mean I can get the data which in running data store when I getting SR_EV_ENABLED ?

Regards,
Tiejun

**Comment by michalvasko** [comment]
No, in `SR_EV_ENABLED` you should always get all the `startup` data without regard for `running` data, they are being replaced.

**Comment by jktjkt** [comment]
@TiejunShuang , my suggestion is to align your architecture with semantics of the NETCONF protocol. Check the [vocabulary](https://tools.ietf.org/html/rfc6241#section-1.1).

For example, if you wanted your devices to always start in an empty state, then do not provision anything in the `startup` datastore. Your device will then boot in whatever "blank", "no configuration present" state, and you can have your controller somehow provision the data to the `running` datastore. You will still have to somehow detect your devices' reboots etc.

It might not be completely clear what you actually want to achieve, though.
