### ISSUE TITLE
received a <notification> but session is not subscribed

### ISSUE THREAD

**Issue by wmakuch** [sysrepo/sysrepo#1418]
Hello Michal!

I am interested of receiving notifications after subscribe on RPC.
When I use netopeer2-cli, command:
`> subscribe --filter-xpath /turing-machine:paused`
works ok. However, instead of using that command with any parameters, I would rather use:
`> user-rpc --content subscription.xml`
Content of `subscription.xml` is:
```
<create-subscription xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
  <stream>NETCONF</stream>
  <filter xmlns:tm="http://example.net/turing-machine" type="xpath" select="/tm:paused"/>
</create-subscription>

```
The problem is - after send such RPC, I recevice message:
`> OK`
but any notifications sent from rpc_example makes _netopeer2-cli_ error:
```
nc ERROR: Session 1: received a <notification> but session is not subscribed.
cli_send_recv: Failed to receive a reply.
```

Is it possible, this could be bug in _netopeer2-server_?

Best Regards,
Wojciech Makuch

**Comment by michalvasko** [comment]
Hi,
this is expected because *libnetconf2* uses a separate thread for receiving notifications. If you do not use the `subscribe` command the CLI thinks it is some custom RPC and does not let *libnetconf2* know the session should be listened on for notifications, hence the error. Why would you not use the `subscribe` command?

Regards,
Michal

**Comment by wmakuch** [comment]
Hi,
Thanks for quick response!
RFC describes `<create-subscription>` as any other RPC, so I assumed my application may also make operations like subscription by sending RPC.

Best Regards,
Wojciech Makuch

**Comment by michalvasko** [comment]
Hi Wojciech,
**your** application may send all RPCs as generic ones but then **your** application will have to let *libnetconf2* know it should listen for notifications in case the generic RPC was `<create-subscription>`. CLI does not do this.

Regards,
Michal
