### ISSUE TITLE
the "values" content got by sr_get_items is NULL

### ISSUE THREAD

**Issue by TonyMcKnight22** [sysrepo/sysrepo#1419]
* [X] Did you check if this is a duplicate issue?
* [X] Did you test it on the latest sysrepo devel branch?

### Description
After invoking sr_get_items, the "values" content can not be got and it is NULL.

**Expected behavior:**
The "values" content can be got after invoking sr_get_items.

### Versions
Sysrepo version: 0.7.7.

### Fixing Proposal
    diff --git a/src/clientlib/client_library.c b/src/clientlib/client_library.c
    index 09476e29..1f1001d8 100644
    --- a/src/clientlib/client_library.c
    +++ b/src/clientlib/client_library.c
    @@ -967,6 +967,7 @@ sr_get_items(sr_session_ctx_t *session, const char *xpath, sr_val_t **values, si
     {
         Sr__Msg *msg_req = NULL, *msg_resp = NULL;
         sr_mem_ctx_t *sr_mem = NULL;
    +    sr_val_t *p_values = NULL;
         int rc = SR_ERR_OK;
     
         CHECK_NULL_ARG5(session, session->conn_ctx, xpath, values, value_cnt);
    @@ -993,8 +994,9 @@ sr_get_items(sr_session_ctx_t *session, const char *xpath, sr_val_t **values, si
     
         /* copy the content of gpb values to sr_val_t */
         rc = sr_values_gpb_to_sr((sr_mem_ctx_t *)msg_resp->_sysrepo_mem_ctx, msg_resp->response->get_items_resp->values,
    -                             msg_resp->response->get_items_resp->n_values, values, value_cnt);
    +                             msg_resp->response->get_items_resp->n_values, &p_values, value_cnt);
         CHECK_RC_MSG_GOTO(rc, cleanup, "Error by copying the values from GPB.");
    +    *values = p_values;
     
     cleanup:
         if (NULL != msg_req) {

**Comment by michalvasko** [comment]
Hi,
okay, just create a pull request and it can be merged.

Regards,
Michal

**Comment by TonyMcKnight22** [comment]
Hi Michal,

So you will do the merge, right?
I don't  have the permission to do it.

Best Regards,
Tao Wang

**Comment by michalvasko** [comment]
Hi Tao,
I will once you create a pull request, this is just an issue. I could apply the patch you provided and create the pull request myself but if you do it, it would save me some work. Thanks.

Regards,
Michal
