### ISSUE TITLE
Unexpected dp_get_items callbacks

### ISSUE THREAD

**Issue by gunterw** [sysrepo/sysrepo#1421]
### Description
I'm getting a lot of unexpected dp_get_items callbacks that I think are caused by augments.
I've looked at the previous bugs written up on this topic, but I think this is different.

### Steps to Reproduce
I would like to add a test case to the cl_state_data_test with augmentation but unfortunately I'm not familiar enough with the C API to get it working.

I think if an augment like the one show below was incorporated into the test cases 
the problem would most likely occur.

```
module state-module-augment {
   namespace "ns:yang:state-module-augment";
   prefix sma;

   import state-module { prefix "sm"; revision-date "2016-07-01"; }

   organization "example-organization";
   description "Test module with augmented state data";
   contact "example@example.org";

   revision 2019-02-01 {
       description "Intial revision";
       reference "www.sysrepo.org";
   }

   augment "/sm:bus"
   {
      description "Augmented bus";

      list wheels {
          key number;
          leaf number {
             type int32;
          }
          leaf type {
             type string;
          }
      }
   }
}
```

**Expected behavior:**
Receive only expected dp_get_items callbacks

**Actual behavior:**
Receive many unexpected callbacks

Here's an example of a version/software client request, generating a dp_get_items callback with an 
xpath for ntp being sent to a subscription for pki-certificate, all 3 completely unrelated to each other!!

```
dp_get_items:              xpath=/ietf-system:system-state/sys-ntp:ntp
dp_get_items:     original_xpath=/ietf-system:system-state/sys-hardware:version/software//.
dp_get_items: subscription_xpath=/ietf-system:system-state/sys-tls:pki-certificate

```
### Versions
Latest devel branch

**Comment by michalvasko** [comment]
Hi,
I tried with the models from your output and my callback got only asked for `/ietf-system:system-state/sys-tls:pki-certificate` when getting data `/ietf-system:system-state/sys-hardware:version/software//.` However, my was a minimal testing scenario so it is not that surprising.

If you could provide all the required information about an invalid use-case (all the modules, what you are subscribed to, what data you asked for, ...) so I can reproduce it, only then I can attempt to fix it. I just want to warn you that state data callbacks are not that efficient and it is possible this is intentional.

Regards,
Michal

**Comment by gunterw** [comment]
Hi Michal,
Unfortunately my setup is a bit complicated and would be to difficult to reproduce, so...

If you could send me the changes to add the augmented model into the test suite,
I think I can take it from there to try and produce a test case failure that you could look into.

Also, if you could point me to the location(s) in the sysrepo code that "decide"
who to callback that would be helpful.

Thanks,
Gunter

-----Original Message-----

**Comment by gunterw** [comment]
FYI - I think I found the function for deciding which subscriptions get a  callback...

rp_dt_find_subscription_covering_subtree

I will try to debug in my environment to narrow down the problem.

**Comment by michalvasko** [comment]
Hi Gunter,
as for your first request, just put the module file into `sysrepo/tests/yang/` and add its installation somewhere into `sysrepo/tests/CMakeLists.txt:176`.

Regards,
Michal

**Comment by gunterw** [comment]
Looks like augmentation is not the issue. Below is a filtered set of debug messages that shows a request for ".../version/firmware". I was expecting only this "matching" request to be sent
```
[DBG] (rp_dt_send_request_to_dp_subscription:1015) Sending request for state data: /ietf-system:system-state/sys-hardware:version
```
instead of sending out a request to all currently registered subscriptions as show below
```
[INF] (rp_dt_get_values_wrapper_with_opts:1350) Get items request running datastore, xpath: /ietf-system:system-state/sys-hardware:version/firmware//., offset: 0, limit: 100
[DBG] (dm_get_data_info_internal:2987) Module ietf-system already loaded
[DBG] (rp_dt_xpath_requests_state_data:763) State data in subtree /ietf-system:system-state requested.
[DBG] (rp_dt_xpath_requests_state_data:771) 1 subtrees of state data will be attempted to load in order to resolve /ietf-system:system-state/sys-hardware:version/firmware//.
[DBG] (pm_module_data_version_changed:583) Module 'ietf-system' persist file version matches with cached value (1549291713685797387).
[DBG] (pm_get_subscriptions:1310) Returning 22 subscriptions from 'ietf-system' persist file cache.
[DBG] (rp_dt_send_first_set_of_dp_requests:1073) Subscription covering subtree not found, looking for a subscription covering at least part of subtree /ietf-system:system-state
[DBG] (rp_dt_send_request_to_dp_subscription:1015) Sending request for state data: /ietf-system:system-state/platform
[DBG] (rp_dt_send_request_to_dp_subscription:1015) Sending request for state data: /ietf-system:system-state/sys-hardware:alarms/alarm
[DBG] (rp_dt_send_request_to_dp_subscription:1015) Sending request for state data: /ietf-system:system-state/sys-hardware:events/event
[DBG] (rp_dt_send_request_to_dp_subscription:1015) Sending request for state data: /ietf-system:system-state/sys-hardware:version
[DBG] (rp_dt_send_request_to_dp_subscription:1015) Sending request for state data: /ietf-system:system-state/sys-chassis:chassis
[DBG] (rp_dt_send_request_to_dp_subscription:1015) Sending request for state data: /ietf-system:system-state/sys-hardware:inventory/system
[DBG] (rp_dt_send_request_to_dp_subscription:1015) Sending request for state data: /ietf-system:system-state/sys-hardware:inventory/card
.....
```
Is this expected behavior?
Thanks.

**Comment by gunterw** [comment]
OK. Thanks for the info.
