### ISSUE TITLE
Separate startup config directory for embedded system support

### ISSUE THREAD

**Issue by gunterw** [sysrepo/sysrepo#1425]
This is an enchancement request to store all files related to startup config (ie. *.startup, etc.) in a separate directory with the ability to configure the location of this directory at build time.This would allow me to easily store startup config files in a persisted location on my embedded system.  Here's a template for the new build macros

CMakeLists.txt
```
set(STARTUP_DATA_SEARCH_DIR "${REPOSITORY_LOC}/data/startup")
```

src/common/sr_constants.h.in
```
/** Path to the directory with startup data files. */
#define SR_STARTUP_DATA_SEARCH_DIR "@STARTUP_DATA_SEARCH_DIR@"
```
If backward compatibility is an issue, the default value for SR_STARTUP_DATA_SEARCH_DIR could
be /etc/sysrepo/data since I would change it to somewhere completely different in my build anyway.

**Comment by michalvasko** [comment]
Hi,
I do not see any problem with such a change, do you want to create a pull request? It is not a big change so I can merge it without one.

Regards,
Michal

**Comment by gunterw** [comment]
I'm confused.... The changes I've shown above only describe how to configure things as an end user, not the actual code to make it work. I can create a pull request just for these changes, but someone else would do the rest of the work?  FYI - I did take a quick look at doing this myself, but it went into parts of the code I have not spent the time to get familiar with yet.

**Comment by michalvasko** [comment]
Hi,
I have not said that you will not need to add additional changes. Never mind, I will make the change.

Regards,
Michal

**Comment by jktjkt** [comment]
This is an interesting proposal which will help us as well, especially if the YANG models are moved, too. What I think makes sense are three places for three classes of data:

- One for the persistent information which should be preserved across reboots, but which does **not** change that often. Examples: the `startup` DS, the list of installed YANG models, and state of enabled YANG features.
- One for the `running` DS
- Notifications

Right now we are doing something similar to placing `/etc` on an `overlayfs` backed by `tmpfs`. We are handling persistency of the `startup` DS by an `inotify-wait` which is continuously copying stuff to our persistent flash partition. If there's a change which splits this into two/three subdirectories, we will be able to get rid of some of that custom tooling.

**Comment by gunterw** [comment]
I don't know enough about how things work under the hood to suggest which direction to take, so any approach that allows me to build sysrepo with separate locations for persistent and volatile data works for me.

**Comment by michalvasko** [comment]
Hi,
I have briefly looked at what code changes would be required by splitting `DATA_SEARCH_DIR` into `STARTUP_DATA_SEARCH_DIR` and `RUNNING_DATA_SEARCH_DIR` and they are way too many. I understand this would be useful for embedded systems, but it is not critical and unless you can provide a functioning pull request (reserve several hours for the work, if not days), I will not waste my time on this. Sorry.

Regards,
Michal

**Comment by gunterw** [comment]
Understood, I had also taken a look and came to a similar conclusion, which is why I asked for someone else to do it :-) I will leave this issue open for now in case someone wants to take it up.

**Comment by gunterw** [comment]
Here's an improvement to the @jktjkt script to detect startup file changes and persist them. This can be used instead of the proposed enhancement. It has a 5 second de-bounce for persisting files and guarantees that you will not miss any *.startup file changes. There was a chance in the original script that a change would be missed while you were copying files.

```
#!/bin/bash
mkdir -p /persistent-storage/etc/sysrepo/data/
inotifywait -e CLOSE_WRITE /etc/sysrepo/data/*.startup -m | {
  needsCopy=0
  while true ; do
    read -t 5 line && needsCopy=1 || {
      test "$needsCopy" = "0" && continue
      needsCopy=0
     cp -a /etc/sysrepo/data/*.startup /persistent-storage/etc/sysrepo/data/
    }
  done < /dev/stdin ;
}
```

**Comment by gunterw** [comment]
Was there ever a consensus on whether *.persist files and/or /etc/sysrepo/data/internal/sysrepo-module-dependencies.xml needed to be persisted as well?

**Comment by michalvasko** [comment]
Fixed.
