### ISSUE TITLE
ietf-network plugin throwing gpb type mismatch for SR_STRING_T and SR_ENUM_T

### ISSUE THREAD

**Issue by ajayinnovative2** [sysrepo/sysrepo#1428]
I wrote library with sysrepo plugin approach for handling operational data.
I am using sr_val_set_xpath followed by sr_val_set_str_data in which it expects type. 
As oper-status in ietf-interfaces is enum type i am passing SR_ENUM_T, but when i send netconf request, i get  below error on sudo sysrepo-plugind -l 4 -d

[ERR] Type can not be mapped to gpb type '/ietf-interfaces:interfaces-state/interface[name='lo']/oper-status' type 0
[ERR] Setting type in gpb failed for xpath '/ietf-interfaces:interfaces-state/interface[name='lo']/oper-status'
[ERR] Unable to duplicate sr_val_t to GPB.
[ERR] Error by copying output values to GPB.
[DBG] Sending 77 bytes of data.
[DBG] 77 bytes of data sent.

The same type of log comes when i try to use SR_STRING_T, its only passing for SR_IDENTITYREF_T. 
I need an urgent attention from the forum. 

I am using sysrepo 0.7.7 version from its master.

sysrepoctl -l output

Module Name                | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
ietf-netconf-notifications | 2012-02-06 | Installed   | root:root           | 666         |                               |
ietf-netconf               | 2011-06-01 | Installed   | root:root           | 666         |                               | writable-running candidate rollback-on-error validate startup xpath
ietf-netconf-acm           | 2018-02-14 | Imported    |                     |             |                               |
nc-notifications           | 2008-07-14 | Installed   | root:root           | 666         |                               |
notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |
turing-machine             | 2013-12-27 | Installed   | root:root           | 666         |                               |
iana-if-type               | 2014-05-08 | Installed   |                     |             |                               |
ietf-interfaces            | 2014-05-08 | Installed   | root:root           | 666         |                               |
ietf-ip                    | 2014-06-16 | Installed   |                     |             |                               |
ietf-netconf-with-defaults | 2011-06-01 | Installed   |                     |             |                               |
ietf-netconf-monitoring    | 2010-10-04 | Installed   | root:root           | 666         |                               |
ietf-yang-library          | 2018-01-17 | Installed   | root:root           | 666         |                               |
ietf-datastores            | 2017-08-17 | Imported    |                     |             |                               |
ietf-yang-types            | 2013-07-15 | Installed   |                     |             |                               |

netopeer2-cli 
get --filter-xpath "/ietf-interfaces:interfaces-state/interface//*"

Thanks!

**Comment by michalvasko** [comment]
Hi,
could you maybe share the code of your plugin, at least the full creation of these values? Also, have you tried using `valgrind`, for example? I have not seen such an error before.

Regards,
Michal

**Comment by ajayinnovative2** [comment]
static int
data_provider_cb(const char *xpath, sr_val_t **values, size_t *values_cnt, void *private_ctx)
{
    sr_val_t *v = NULL;
    sr_xpath_ctx_t xp_ctx = {0};
    int rc = SR_ERR_OK;
    int err;

    struct nl_sock *p_nl_sock = NULL;
    struct nl_cache *link_cache = NULL;
    struct nl_cache *addr_cache = NULL;

    struct rtnl_addr *p_rtnl_addr = NULL;
    struct nl_addr *p_nl_addr = NULL;
    struct nl_link *p_nl_link = NULL;

    struct rtnl_link *p_rtnl_link = NULL;
    struct rtnl_addr *addr = NULL;
    
    unsigned int value;    
    struct nl_addr *local_addr = NULL;
    
    char *pchLinkName = NULL;
    char *pchLinkAddr = NULL;

    sr_xpath_ctx_t state = {0};
    char *int_name = NULL;
    char interface_name[20] = {0};
    char *res = NULL;
    int i=0;
 
    res = sr_xpath_next_node(xpath, &state);
    if(res) {
      if(!strcmp(res, "interfaces-state")) {
	 int_name = sr_xpath_key_value(NULL, "interface", "name", &state);
	 sr_xpath_recover(&state);
	    if(int_name) {
              for(i=0;int_name[i]!='\'';i++) {
                interface_name[i] = int_name[i];
  	          }
            interface_name[i] = '\0';

            pchLinkAddr = calloc(1, 40);
            p_nl_sock = nl_socket_alloc();
            if (!p_nl_sock) {
              LOG_MESSAGE(ERR, STD_ERR, "Could not allocate netlink socket.");
              exit(ENOMEM);
            }

            addr = rtnl_addr_alloc();
            if(addr == NULL) {
               LOG_MESSAGE(ERR, STD_ERR, "addr alloc");
               return 1;
            }
    
            // Connect to socket
            if(err = nl_connect(p_nl_sock, NETLINK_ROUTE)) {
               LOG_MESSAGE(ERR, STD_ERR, "netlink error: %s", nl_geterror(err));
               p_nl_sock = NULL;
               exit(err);
            }

            err = rtnl_link_alloc_cache(p_nl_sock, AF_UNSPEC, &link_cache);
            if (0 != err) {
               /* error */
               LOG_MESSAGE(ERR, STD_ERR,"rtnl_link_alloc_cache failed: %s", nl_geterror(err));
               return(EXIT_FAILURE);
            }
 
            err = rtnl_addr_alloc_cache(p_nl_sock, &addr_cache);
            if (0 != err) {
               /* error */
               LOG_MESSAGE(ERR, STD_ERR, "rtnl_addr_alloc_cache failed: %s", nl_geterror(err));
               return(EXIT_FAILURE);
            }
            p_rtnl_link = rtnl_link_get_by_name(link_cache, interface_name);
            if (NULL == p_rtnl_link) {
              /* error */
              LOG_MESSAGE(ERR, STD_ERR, "rtnl_link_get_by_name");
              return(EXIT_FAILURE);
            }
	  }
       }
    }
    LOG_MESSAGE(INFO, STD_OUT, "Data for '%s' requested.", xpath);
    if (sr_xpath_node_name_eq(xpath, "interface")) {
	int count;
	count = get_interface_count();
	rc = sr_new_values(count*4, &v);
        if (SR_ERR_OK != rc) {
            LOG_MESSAGE(ERR, STD_ERR, "sr_new_values error");
            return rc;
        }
        struct ifaddrs *addrs,*tmp = NULL;
        getifaddrs(&addrs);
        tmp = addrs;
        int i = 0;
        while (tmp) {
           if (tmp->ifa_addr && tmp->ifa_addr->sa_family == AF_PACKET) {
             char xpath_int_type[PATH_MAX] = {0};
	         char xpath_int_oprstatus[PATH_MAX] = {0};
             char xpath_phys_addr[PATH_MAX] = {0};
             char xpath_int_name[PATH_MAX] = {0};

	         snprintf(xpath_int_type, PATH_MAX, XPATH_INTERFACE_TYPE, tmp->ifa_name);
	         snprintf(xpath_int_oprstatus, PATH_MAX, XPATH_INTERFACE_OPER_STATUS, tmp->ifa_name);
	         pchLinkAddr = calloc(1, 40);
	         if (!pchLinkAddr) {
	            LOG_MESSAGE(ERR, STD_ERR, "Could not allocate pchLinkAddr.");
	            exit(ENOMEM);
	         }
             p_nl_sock = nl_socket_alloc();
             if (!p_nl_sock) {
              LOG_MESSAGE(ERR, STD_ERR, "Could not allocate netlink socket.");
              exit(ENOMEM);
             }

             addr = rtnl_addr_alloc();
             if(addr == NULL) {
               LOG_MESSAGE(ERR, STD_ERR, "addr alloc");
               return 1;
             }
             // Connect to socket
             if(err = nl_connect(p_nl_sock, NETLINK_ROUTE)) {
               LOG_MESSAGE(ERR, STD_ERR,"netlink error: %s\n", nl_geterror(err));
               p_nl_sock = NULL;
               exit(err);
             }

             err = rtnl_link_alloc_cache(p_nl_sock, AF_UNSPEC, &link_cache);
             if (0 != err) {
               LOG_MESSAGE(ERR, STD_ERR, "rtnl_link_alloc_cache failed: %s\n", nl_geterror(err));
               return(EXIT_FAILURE);
             }
 
             err = rtnl_addr_alloc_cache(p_nl_sock, &addr_cache);
             if (0 != err) {
               LOG_MESSAGE(ERR, STD_ERR,"rtnl_addr_alloc_cache failed: %s\n", nl_geterror(err));
               return(EXIT_FAILURE);
             }

             p_rtnl_link = rtnl_link_get_by_name(link_cache, tmp->ifa_name);
             if (NULL == p_rtnl_link) {
               LOG_MESSAGE(ERR, STD_ERR, "rtnl_link_get_by_name");
               return(EXIT_FAILURE);
             }

	         // MAC Addr
             p_nl_addr = rtnl_link_get_addr(p_rtnl_link);
             if (NULL == p_nl_addr) {
               LOG_MESSAGE(ERR, STD_ERR, "rtnl_link_get_addr");
               return(EXIT_FAILURE);
             }

             pchLinkAddr = nl_addr2str(p_nl_addr, pchLinkAddr, 20);
             if (NULL == pchLinkAddr) {
               LOG_MESSAGE(ERR, STD_ERR,"rtnl_link_get_name");
               return(EXIT_FAILURE);
             }
             snprintf(xpath_int_name, PATH_MAX, XPATH_INT_NAME, tmp->ifa_name);
	         LOG_MESSAGE(INFO, STD_OUT, "%s\n", tmp->ifa_name);
	     
	         sr_val_set_xpath(&v[i], xpath_int_name);
             sr_val_set_str_data(&v[i], SR_STRING_T, tmp->ifa_name);
             
	         snprintf(xpath_phys_addr, PATH_MAX, XPATH_PHYS_ADDR, tmp->ifa_name);
	         sr_val_set_xpath(&v[++i], xpath_phys_addr);
             sr_val_set_str_data(&v[i], SR_STRING_T, pchLinkAddr);
			
			 sr_val_set_xpath(&v[++i], xpath_int_type);
             sr_val_set_str_data(&v[i], SR_IDENTITYREF_T, "ethernetCsmacd");
			 
             //IMPORTANT: For getting get response for stats, oper-stats should be up, Make a note
             char oper_status = rtnl_link_get_operstate(p_rtnl_link);
             LOG_MESSAGE(INFO, STD_OUT, "oper_status: %d %s\n", oper_status, operStatus[oper_status]);
             sr_val_set_xpath(&v[++i], xpath_int_oprstatus);
             //sr_val_set_str_data(&v[i], SR_ENUM_T, "up");
             sr_val_set_str_data(&v[i], SR_ENUM_T, operStatus[oper_status]);
	     
	         ++i;
	         nl_close(p_nl_sock);
             nl_socket_free(p_nl_sock);
             free(pchLinkAddr);
          }
          tmp = tmp->ifa_next;
        }
        freeifaddrs(addrs);

        *values = v;
        *values_cnt = count*4;
    } else if (sr_xpath_node_name_eq(xpath, "statistics")) {
        /* allocate space for data to return */
        rc = sr_new_values(7, &v);
        if (SR_ERR_OK != rc) {
            return rc;
        }
	    sr_val_build_xpath(&v[0], "%s/%s", xpath, "discontinuity-time");
        
	    if (0 == strcmp(sr_xpath_key_value((char*)xpath, "interface", "name", &xp_ctx), interface_name)) {
            sr_val_set_str_data(&v[0], SR_STRING_T, "1987-08-31T17:00:30.44Z");
        } else {
            sr_val_set_str_data(&v[0], SR_STRING_T, "2016-10-06T15:12:50.52Z");
        }
        sr_xpath_recover(&xp_ctx); /* Modified const string! - let's recover it */
        
	    sr_val_build_xpath(&v[1], "%s/%s", xpath, "in-octets");
	    uint64_t linkStat = rtnl_link_get_stat(p_rtnl_link, RTNL_LINK_RX_PACKETS);
        LOG_MESSAGE(INFO, STD_OUT, "RX Packets: %" PRIu64 , linkStat);
        if (0 == strcmp(sr_xpath_key_value((char*)xpath, "interface", "name", &xp_ctx), interface_name)) {
		   v[1].type = SR_UINT64_T;
		   v[1].data.uint64_val = linkStat;
        } else {
  		   v[1].type = SR_UINT64_T;
  		   v[1].data.uint64_val = linkStat;
        }
        sr_xpath_recover(&xp_ctx); /* Modified const string! - let's recover it */
   
	    sr_val_build_xpath(&v[2], "%s/%s", xpath, "out-octets");
	    linkStat = rtnl_link_get_stat(p_rtnl_link, RTNL_LINK_TX_PACKETS);
        LOG_MESSAGE(INFO, STD_OUT, "TX Packets: %" PRIu64 , linkStat);
        if (0 == strcmp(sr_xpath_key_value((char*)xpath, "interface", "name", &xp_ctx), interface_name)) {
		   v[2].type = SR_UINT64_T;
		   v[2].data.uint64_val = linkStat;
        } else {
  		   v[2].type = SR_UINT64_T;
  		   v[2].data.uint64_val = linkStat;
        }
        sr_xpath_recover(&xp_ctx); /* we modified const string! - let's recover it */
	    uint32_t ulinkStat;
	    sr_val_build_xpath(&v[3], "%s/%s", xpath, "in-errors");
	    ulinkStat = rtnl_link_get_stat(p_rtnl_link, RTNL_LINK_RX_ERRORS);
        if (0 == strcmp(sr_xpath_key_value((char*)xpath, "interface", "name", &xp_ctx), interface_name)) {
		   v[3].type = SR_UINT32_T;
		   v[3].data.uint64_val = ulinkStat;
        } else {
  		   v[3].type = SR_UINT32_T;
  		   v[3].data.uint64_val = ulinkStat;
        }
        sr_xpath_recover(&xp_ctx); /* we modified const string! - let's recover it */
 
	    sr_val_build_xpath(&v[4], "%s/%s", xpath, "out-errors");
	    ulinkStat = rtnl_link_get_stat(p_rtnl_link, RTNL_LINK_TX_ERRORS);
        if (0 == strcmp(sr_xpath_key_value((char*)xpath, "interface", "name", &xp_ctx), interface_name)) {
		   v[4].type = SR_UINT32_T;
		   v[4].data.uint64_val = ulinkStat;
        } else {
  		   v[4].type = SR_UINT32_T;
  		   v[4].data.uint64_val = ulinkStat;
        }
        sr_xpath_recover(&xp_ctx); /* we modified const string! - let's recover it */

	    sr_val_build_xpath(&v[5], "%s/%s", xpath, "in-discards");
	    ulinkStat = rtnl_link_get_stat(p_rtnl_link, RTNL_LINK_RX_DROPPED);
        if (0 == strcmp(sr_xpath_key_value((char*)xpath, "interface", "name", &xp_ctx), interface_name)) {
		   v[5].type = SR_UINT32_T;
		   v[5].data.uint64_val = ulinkStat;
        } else {
  		   v[5].type = SR_UINT32_T;
  		   v[5].data.uint64_val = ulinkStat;
        }
        sr_xpath_recover(&xp_ctx); /* we modified const string! - let's recover it */
	
	    sr_val_build_xpath(&v[6], "%s/%s", xpath, "out-discards");
	    ulinkStat = rtnl_link_get_stat(p_rtnl_link, RTNL_LINK_TX_DROPPED);
        if (0 == strcmp(sr_xpath_key_value((char*)xpath, "interface", "name", &xp_ctx), interface_name)) {
		   v[6].type = SR_UINT32_T;
		   v[6].data.uint64_val = ulinkStat;
        } else {
  		   v[6].type = SR_UINT32_T;
  		   v[6].data.uint64_val = ulinkStat;
        }
        sr_xpath_recover(&xp_ctx); /* we modified const string! - let's recover it */

        *values = v;
        *values_cnt = 7;
    } else {
        *values = NULL;
        values_cnt = 0;
    }
    
    if(int_name) {
      nl_close(p_nl_sock);
      nl_socket_free(p_nl_sock);
      free(pchLinkAddr);
    }
    return SR_ERR_OK;
}

int
sr_plugin_init_cb(sr_session_ctx_t *session, void **private_ctx)
{
    int rc;
    /* remember the session of interface plugin */
    sess = session;

    /* subscribe as state data provider for the interface state data */
    rc = sr_dp_get_items_subscribe(session, "/ietf-interfaces:interfaces-state", data_provider_cb, NULL, SR_SUBSCR_CTX_REUSE, &subscription);
    if (rc != SR_ERR_OK) {
        goto error;
    }

    /* sysrepo/plugins.h provides an interface for logging */
    SRP_LOG_DBG_MSG("INTERFACE: Interface stats plugin initialized successfully.");
    return SR_ERR_OK;

error:
    SRP_LOG_ERR("INTERFACE: Interface stats plugin initialization failed: %s.", sr_strerror(rc));
    sr_unsubscribe(session, subscription);
    return rc;
}

void
sr_plugin_cleanup_cb(sr_session_ctx_t *session, void *private_ctx)
{
    /* nothing to cleanup except freeing the subscriptions */
    sr_unsubscribe(session, subscription);
    SRP_LOG_DBG_MSG("INTERFACE: Interface stats plugin cleanup finished.");
}

**Comment by michalvasko** [comment]
Hi,
it seems fine to me and the only thing that makes sense to me would be that either `sr_val_set_xpath()` or `sr_val_set_str_data()` fail for whatever reason, so please try to add return value check.

Regards,
Michal

**Comment by ajayinnovative2** [comment]
sr_val_set_xpath and sr_val_set_str_data should return 0 for success. 
But oper-status which is SR_ENUM_T is failing for sr_val_set_str_data and returning 1.

**Comment by ajayinnovative2** [comment]
sr_val_set_xpath and sr_val_set_str_data is returning 0 for SR_IDENTITYREF_T

**Comment by ajayinnovative2** [comment]
Two questions:
1. The reason of sr_val_set_str_data failure for specific SR types. 
2. I see whenever it fails, we try to free values and val_cnt using sr_free_values. But we can-not afford to fail sr set apis. We might not get data if it fails. But why for few ONLY?

**Comment by michalvasko** [comment]
Hi,
looking at the code this would mean you are setting `type` to be something other than `SR_BINARY_T`, `SR_BITS_T`, `SR_ENUM_T`, `SR_IDENTITYREF_T`, `SR_INSTANCEID_T`, or `SR_STRING_T`. But, since you are using `SR_ENUM_T`, I can only assume the code I am looking at is **not** executed in your case.

In other words, your binary is actually linked against some really old (more than a year or even 2, probably) *libsysrepo* that defines a different enum. That does seem odd to me but I really cannot think of any other reason you can be getting `SR_ERR_INVAL_ARG` from `sr_val_set_str_data()`. So, what is the output of `ldconfig -p | grep libsysrepo`? And of `ldd <path-to-the-plugin-SO> | grep libsysrepo`?

Anyway, you can easily check what exactly is the problem with a debugger, the function code is trivial.

Regards,
Michal

**Comment by ajayinnovative2** [comment]
ldconfig -p | grep libsysrepo
libsysrepo.so.0.7 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libsysrepo.so.0.7
libsysrepo.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libsysrepo.so

ldd /usr/lib/x86_64-linux-gnu/sysrepo/plugins/libnw_stats.so.0.0.0 | grep libsysrepo
-> no oputput

**Comment by ajayinnovative2** [comment]
Sorry i was not linking sysrepo in my auto makefile, after adding this is the output, but i am having same issue.

ldconfig -p | grep libsysrepo
libsysrepo.so.0.7 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libsysrepo.so.0.7
libsysrepo.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libsysrepo.so

ldd /usr/lib/x86_64-linux-gnu/sysrepo/plugins/libnw_stats.so.0.0.0 | grep libsysrepo
libsysrepo.so.0.7 => /usr/lib/x86_64-linux-gnu/libsysrepo.so.0.7 (0x00007f0c7ea46000)

**Comment by michalvasko** [comment]
Okay, that is quite confusing and even though your last output is fine (the libraries match), I still stand by what I said. If you want to find the cause of the problem, I can now suggest only the debugger I mentioned before. Use it to look into that `sr_val_set_str_data()` function call and you should see that the input type is not `SR_ENUM_T` even though that is what you used as the parameter.

Other than that, it should help if you completely remove *sysrepo* (`# make uninstall`), clear all build files (of *sysrepo*, your plugin), compile and reinstall *sysrepo*, and then compile and reinstall your plugin. I can only blame some compilation or linking issue, it also depends how exactly are you compiling the plugin, but you should be doing something similar to what is in `sysrepo/examples/plugins/CMakeLists.txt`.

Regards,
Michal

**Comment by michalvasko** [comment]
Not relevant anymore.
