### ISSUE TITLE
Passive subtree subscriptions don't receive ENABLED callbacks

### ISSUE THREAD

**Issue by gunterw** [sysrepo/sysrepo#1431]
If you modify the cl_notifications_test as shown below you can see that passive subtree subscriptions do not receive ENABLED startup-config callbacks.

```
diff --git a/tests/cl_notifications_test.c b/tests/cl_notifications_test.c
index 0e65678a..ab41f3f0 100644
--- a/tests/cl_notifications_test.c
+++ b/tests/cl_notifications_test.c
@@ -2190,8 +2190,12 @@ cl_subtree_enabled_notifications(void **state)
     assert_int_equal(rc, SR_ERR_OK);
 
     pthread_mutex_lock(&changes.mutex);
+    rc = sr_module_change_subscribe(session, "/test-module:main", list_changes_cb, &changes,
+            0, SR_SUBSCR_DEFAULT, &subscription);
+    assert_int_equal(rc, SR_ERR_OK);
+
     rc = sr_subtree_change_subscribe(session, "/test-module:main", list_changes_cb, &changes,
-            0, SR_SUBSCR_DEFAULT | SR_SUBSCR_EV_ENABLED, &subscription);
+            0, SR_SUBSCR_PASSIVE | SR_SUBSCR_EV_ENABLED, &subscription);
     assert_int_equal(rc, SR_ERR_OK);
 
     sr_clock_get_time(CLOCK_REALTIME, &ts);
```

Here's the error output from the test run with the changes above
```
[  ERROR   ] --- 0xa != 0
[   LINE   ] --- /opt/home/gunter/working-copy/sysrepo.github/tests/cl_notifications_test.c:2195: error: Failure!
[  FAILED  ] cl_subtree_enabled_notifications
[ RUN      ] cl_multiple_enabled_notifications
```

**Comment by michalvasko** [comment]
Hi,
your patch is severely lacking and the error you got is not relevant at all but with some additional changes I reproduced the situation you mentioned. However, it seems this behavior is intentional and you can never get `SR_EV_ENABLED` notifications on passive subscriptions. I have at least updated documentation to mention this shortcoming.

Regards,
Michal

**Comment by gunterw** [comment]
OK, can you elaborate on the reasoning for passive subscriptions NOT getting ENABLED callbacks?
It's obviously something that I think would be useful :-)

**Comment by michalvasko** [comment]
Currently, the notification is generated **only for the subscription** causing the data to be enabled (the `if` at `notification_processor.c:1042`), if any. I am not sure how difficult would be to change this but after my previous experiences, I would be rather pessimistic. You are welcome to change it yourself, though. It works fine in the new sysrepo (the whole enabled data mechanism is different), which is not that far from release now.

Regards,
Michal

**Comment by gunterw** [comment]
Got it. Thanks
