### ISSUE TITLE
Can sysrepo be transplanted in PowerPC environment？

### ISSUE THREAD

**Issue by foolloow** [sysrepo/sysrepo#1432]
I need to transplated the code in a device using PowerPC64 environment.

The library dependency is complex, although most libs are source code, cross-compile them is OK，but i'm not sure if all the libs can be cross-compiled.
So i want to ask if someone use sysrepo in PowerPC64 environment and it works well?

**Comment by mislavn** [comment]
Hi,

I started working on something similar, where I cross compiled for ARM in docker, packaged the binaries/libraries and run sysrepo on the targeted ARM device.

https://github.com/sartura/sr_uci/tree/master/docker/cross_compiling

The dockerfiles and bash scripts are still rough around the edges.t

For cross compiling I'm using dockcross and they have PowerPC but when I replaced `dockcross/linux-armv7` with `dockcross/linux-ppc64le` the docker build breaks on libpcre. Currently I don't have to take a closer look why it breaks.

From the dockerfiles you can see what are the dependencies and how to cross compile it. Also when cross compiling sysrepo I would advise you to provide the x86 version of `protoc`, `sysrepoctl` and `sysrepocfg`.

Second option is to use OpenWrt for cross compiling, they support PowerPC and they have sysrepo packages mainlined.

**Comment by foolloow** [comment]
"Also when cross compiling sysrepo I would advise you to provide the x86 version of protoc, sysrepoctl and sysrepocfg."
Is there any obstacles to build ppc64's protoc,sysrepoctl and sysrepocfg?

**Comment by mislavn** [comment]
No, you will compile the ppc64 version of sysrepoctl/sysrepocfg but you will need the x86 for installing YANG models. You have two approaches:
Disable https://github.com/sysrepo/sysrepo/blob/master/CMakeLists.txt#L43 and run sysrepoctl and sysrepocfg commands at first boot on the ppc64 or at compile time provide path to sysrepoctl/sysrepoctfg x86 version at install time and copy the /etc/sysrepo/ folder to the ppc64.

Also you will need the x86 version of protoc to generate the C code at compile time, https://github.com/sysrepo/sysrepo/blob/master/src/CMakeLists.txt#L24 .
