### ISSUE TITLE
does sysrepo or libyang support annotation to hide internal yang module

### ISSUE THREAD

**Issue by GuoyouZhang** [sysrepo/sysrepo#1434]
I want to define some yang file for internal usage only . and i don't want to expose such yang module to NBI. could sysrepo hide this yang model for me?

Thanks!

**Comment by michalvasko** [comment]
Hi,
I do not think this is possible and I am also wondering why would you want to do this. If the module cannot be modified/subscribed to, what is its purpose?

Regards,
Michal

**Comment by GuoyouZhang** [comment]
just want to simplify the internal implementation by reuse the sysrepo as the central way of ipc

**Comment by michalvasko** [comment]
I see. Well, it is not possible with the current *sysrepo*.

Regards,
Michal
