### ISSUE TITLE
Feature request: add sysrepo-netopeer2 arm64(aarch64) docker image 

### ISSUE THREAD

**Issue by zhabba** [sysrepo/sysrepo#1437]
### Description
sysrepo-netopeer2 image supports only amd64 architecture

**Expected behavior:**
sysrepo-netopeer2 image for arm64 exists

**Actual behavior:**
sysrepo-netopeer2 image for arm64 doesn't exist

Thanks!

**Comment by allena29** [comment]
With this docker file I have run sysrepo/netopeer2 on a raspberry pi based around debian sid
https://raw.githubusercontent.com/allena29/brewerslabng/87f5c86a90ba06733a36ce6efae27c04ee69174d/Documentation/netopeer2/Dockerfile

There's a slightly updated Dockerfile based around ubuntu cosmic.
https://raw.githubusercontent.com/allena29/brewerslabng/b87a6379e1a4c5a0807b6dd5d3b26a60502d9a2e/Documentation/netopeer2/Dockerfile

What I've found (but not narrowed down too much) is that subscribing to operdata with the later versions of libyang/libnetconf/sysrepo/netopeer using python 3 bindings segfaults... where as the older dockerfile does not.

Need to do some more digging but even without a docker image provided things compile and run on arm.
