### ISSUE TITLE
Multiple subscribers to the same node doesn't work

### ISSUE THREAD

**Issue by gunterw** [sysrepo/sysrepo#1438]
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description
I have multiple data subscribers in different processes subscribing to the same "interface" node.
Our system has multiple slots, there is a separate process and "interface" node data subscription for each slot. I would like each data subscriber/process to only handle the interfaces for that slot (ie the 
only difference in the callback xpaths between each data subscriber/process are the key values) 

When our system is setup and running I get the top level "interface" node data subscription callbacks correctly from the **rp_dt_send_first_set_of_dp_requests** function for each separate data subscriber/process. The problem is the follow on/nested callbacks from the **rp_data_provide_request_nested** function only generate callbacks to one of the subscribers.

### Versions
Latest development branch

**Comment by michalvasko** [comment]
Hi,
I am not sure exactly where the problem is but *sysrepo* does not support subscriptions to specific data instances (in other words, support for predicates in subscriptions) so that will be ultimately the reason it does not work.

However, note that the new *sysrepo* will support this.

Regards,
Michal

**Comment by gunterw** [comment]
I subscribe to the same exact xpath in each process without predicates. When the top level callback occurs in each process, it has the predicates/keys in the callback xpath and I look at this info to determine if I should respond or not. If the predicate/key matches my slot I respond if it doesn't I ignore. This works as expected for the first round of callbacks, but when the nested callbacks occur only one of the subscribers gets called.

**Comment by gunterw** [comment]
BTW - what is the time frame for the new sysrepo?

**Comment by michalvasko** [comment]
Oh, then it probably should work. Can you please post the XPaths you are subscribing to, the change you make, and which callbacks/how many times are called?

New *sysrepo* should be completely finished (with compatible *netopeer2*) by the end of Q2. As for *sysrepo* itself, a documented and reasonably tested first version should be available by the end of this month.

Regards,
Michal

**Comment by gunterw** [comment]
It is a data subscription, so I don't make any explicit changes to cause the callback, it just occurs when any client requests the data. I think it might be easier if I modified a unit test to have two subscribers to the same xpath and get it to fail so you can debug, could you suggest which test to try and modify?

**Comment by michalvasko** [comment]
So you have data-provide subscriptions. Then, again, I do not think nested subscribers are supported. But I can take a look tomorrow.

Also, again, new *sysrepo* supports this (nested subscriptions + separate callbacks for specific instances).

Regards,
Michal

**Comment by gunterw** [comment]
Not nested subscribers, I only subscribe to a single node. It is the nested data provider **callbacks** to fill in the details of the children under the subscribed node that does not work.

I will either provide the data requested above or modify a unit test to show the issue, it will take a bit.

**Comment by KyleGG** [comment]
> Hi,
> I am not sure exactly where the problem is but _sysrepo_ does not support subscriptions to specific data instances (in other words, support for predicates in subscriptions) so that will be ultimately the reason it does not work.
> 
> However, note that the new _sysrepo_ will support this.
> 
> Regards,
> Michal

Hi Michal. 

Is this a real thing? 

In regards to https://github.com/sysrepo/sysrepo/issues/1255

Absolutely legendary if the above issue (1255) is addressed with the subscription change.  Could you elaborate on when this new sysrepo may come around?

**Comment by michalvasko** [comment]
Hi,
I will have to disappoint you because what I meant are **configuration data** subscriptions, not **action** subscriptions, those work the same way. However, it may not be that difficult to also support this and I guess it makes sense.

New *sysrepo* with *netopeer2* is planned for the end of Q2. Whether it will already have this feature I cannot say (meaning these specific action subscriptions, specific data subscriptions are already implemented).

Regards,
Michal

**Comment by KyleGG** [comment]
Apologies for derailing this thread. Would a similar paradigm be considered for state data providers as well?

I'm thinking of the use case of a module with N data providers providing state data for N list elements. 

I've already gotten this to *work* with the current implementation using a tailored schema, and multiple providers. Namely container a { config false; list b { leaf data } }. Likely a result of: [sr_dp_get_items_cb documentation](http://www.sysrepo.org/static/doc/html/group__cl.html#ga90a9faf255eabbe363b248a8951f6f27). 

With a subscription to a list element
> provider must return all leaves (except for keys!) and leaf-lists values within **all instances of the list**
And with a container subscription 
> Nested lists and containers should not be provided - sysrepo will **ask for them in subsequent calls**.

Using some questionable subscriptions this results in being able to have N providers provide state data for list elements, and sysrepo will call the providers and rebuild the tree on the return. Though i'm getting the idea this is not officially supported and is currently questionable behavior. 

Cheers,

Kyle

**Comment by michalvasko** [comment]
Hi Kyle,
yeah, in the new *sysrepo* it is already officially supported for state data subscriptions, as well.

Regards,
Michal
