### ISSUE TITLE
The Memory and CPU usage of sysrepo

### ISSUE THREAD

**Issue by darcyllingyan** [sysrepo/sysrepo#1439]
Hi,
Whether there is memry size restriction when using the sysrepo as the Netconf Datastore.
Now in a 8G Virtual Machine, only after loading 300 hundred yang files, the memory usage is 25.16%, which means it needs 2G memory to startup the sysrepo.

Do you have any sugggestons about it?
```
# pidstat -r 2 5 -p 3794 -u |tee sysrepo.log
Linux 3.10.0-862.14.4.el7.x86_64 (henry-deploy-test)    03/06/2019      _x86_64_        (4 CPU)

07:54:29 AM   UID       PID    %usr %system  %guest    %CPU   CPU  Command
07:54:31 AM     0      3794    0.00    0.00    0.00    0.00     1  sysrepod

07:54:29 AM   UID       PID  minflt/s  majflt/s     VSZ    RSS   %MEM  Command
07:54:31 AM     0      3794      0.00      0.00 2199104 2014900  25.16  sysrepod
```
Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
you mean you have loaded 300 YANG models? That is quite a lot but as for the current *sysrepo* there is not much you can do about it. Once the new *sysrepo* is out, you can check how much memory it will need and we can also think about some optimizations.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi  Michal,
Thanks for the response!
Yes, I load 300 YANG models.

1. > That is quite a lot but as for the current sysrepo there is not much you can do about it.
You mean there is no way to check how much memory the sysrepo should use at least to startup it.

2. 

> Once the new sysrepo is out, 
As you said before, the new sysrepo will be out in June, right?

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi,

> You mean there is no way to check how much memory the sysrepo should use at least to startup it.
What do you mean? Based on your measurements it needs 2GB with 300 models, there is nothing more I can add.

> As you said before, the new sysrepo will be out in June, right?
Yes, by then the whole suite (*sysrepo* and *netopeer2*) should be released but *sysrepo* by itself should be finished by the end of this month, so if you are fine with testing just that, you can try it then.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
Thanks for the reponse. I got it.

Thanks
Darcy
