### ISSUE TITLE
In sysrepo - 0.7.4, rpc_example.py gives: Python callback rpc_cb failed.

### ISSUE THREAD

**Issue by rajgau11** [sysrepo/sysrepo#1441]
Hi

Using version 0.7.4
Tried example rpc_example.py at following path:
sysrepo/swig/python3/examples 

It gives following output:

reje@pica:~/sysrepo/swig/python3/examples$ python3 rpc_example.py

 ========== SUBSCRIBE TO RPC CALL ==========

 ========== START RPC CALL ==========

 ========== RPC CALLED ==========
/test-module:activate-software-image/image-name   =  acmefw-2.3
/test-module:activate-software-image/location   =  /
terminate called after throwing an instance of 'std::runtime_error'
  what():  Python callback rpc_cb failed.

Aborted (core dumped)

Earlier I also changed:
out_vals = subscribe.rpc_send("/test-module:activate-software-image", in_vals);
to
out_vals = sess.rpc_send("/test-module:activate-software-image", in_vals);

Please help me with this?

* [x] Did you check if this is a duplicate issue? - I did see some changes performed regarding rpc_example, but it did not show changes done for this.
* [No] Did you test it on the latest sysrepo devel branch?

### Versions
Please provide versions for software needed to reproduce the bug:
Sysrepo version: `sysrepod -v`. => [sysrepod - sysrepo daemon, version 0.7.4 ]
libyang version: `yanglint -v` => [yanglint 0.15.166]
netopeer2-server: `netopeer2-server -V` (optional) [netopeer2-server 0.5.31]

Thanks
raje

**Comment by rajgau11** [comment]
Hello Sir

One more request to you.
You may say, that this issue is fixed in some later version and very true, this is how development progresses.
But I have a bigger problem. My current sysrepod, netopeer2-server, libyang, etc are all part of a extensive implementation where complete build environment has already been setup and we are stablizing that, fixing system issues, adding up enhancements, new features.

At this point taking out old version and bringing in new version and start up whole bundle of unit tests and send it to system test division again, will ask for more time. It may go worse if some issue comes up because of new environment changes.

Our dev is changing from C to python, due to faster development cycles and lesser bug fixing cycles.

As part of small enhancement I am asked to write some RPCs and then this problem came up.

This is my request, if possible, and if it is not much effort on your part, please suggest some patch or changes with which I can move ahead.

But if you suggest that there have been some changes which are important and I should have a newer version. I will do bring this out at our sync up meeting and mark it with dev at my end.

Thanks
raje

**Comment by mislavn** [comment]
Hi Raje,

we made some big changes in C++/SWIG/Python between the sysrepo versions 0.7.4 and 0.7.7 and I would strongly suggest to use the latest version 0.7.7 not because it solves this issue but because we made a lot of changes and fixes and it's not possible to backport all of them to the older sysrepo version.

Regards,
Mislav
