### ISSUE TITLE
How to find which external user caused a SysRepo call to southbound application

### ISSUE THREAD

**Issue by achrc** [sysrepo/sysrepo#1445]
### Description
I am developing a southbound application which implements a set of yang modules accessible via the NetConf Server (netopeer2). One of these yang modules requires that I know the name of the external user which connected via SSH to the NetConf Server, and following that called an RPC in this particular module.

I cannot find anyware in the code or in the documentation how to retrieve that particular information via SysRepo function calls.

I have tried looking into sr_session_get_id() - but that only returns the internal SysRepo session ID for my southbound session, not the external session ID used by NetConf Server. Otherwise I could have retrieved /ietf-netconf-monitoring:netconf-state/sessions/session[session-id='<ID>']/username from the NetConf server to get the username.

Is there any way to retrieve this information via SysRepo?
How does a southbound session know which of many outside external users is the originator of a given edit-config, RPC call or get-item request?

Best Regards
Anne

**Comment by michalvasko** [comment]
Hi Anne,
unfortunately, this is not possible in the current *sysrepo*.

However, it will be possible to read NETCONF session ID and username (only with `root` access) directly from *sysrepo* session in the new version. It is planned to be released with updated *netopeer2* by the end of Q2.

Regards,
Michal

**Comment by achrc** [comment]
Hi Michal,

Thanks for your information. Looking forward to this new feature.

Best Regards
Anne

**Comment by jabilmplane** [comment]
Have the same issue with latest code stable version.
```
commit 84ca8d6aacab2fc435b7332c4d26012115bc8509 (HEAD -> master, tag: v2.1.64, origin/master, origin/HEAD)
Author: Michal Vasko <mvasko@cesnet.cz>
Date:   Fri May 6 10:56:29 2022 +0200

    VERSION bump to version 2.1.64

```
I used to call sr_session_get_nc_id but it's gone after I updated the code.
Is there any possibility to get username of RPC originator?

**Comment by michalvasko** [comment]
Yes, read the server [README](https://github.com/CESNET/netopeer2/#sysrepo-callbacks).

**Comment by geovivek** [comment]
Hi Jabil,

how did you use sr_session_get_orig_data API to get the user name of current user who established the netconf session
