### ISSUE TITLE
dp_get_items called once per each leafref in a list

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#1447]
My YANG model contains a top-level list which is `config: false` (it's called `channel-power` in the tree below). Keys of this list refer to keys within a `config: true` list (`/channel-plan/channel/name` below). When a `dp_get_items` callback gets invoked, it actually gets called *N+1* times:

- once for the list
- once per each of *N* items in the other list
```
module: czechlight-roadm-device
  +--rw channel-plan
  |  +--rw channel* [name]
  |     +--rw name               string
  |     +--rw lower-frequency    opendevice-types:dwdm-frequency-mhz
  |     +--rw upper-frequency    opendevice-types:dwdm-frequency-mhz
  |
  | // some irrelevant data were omitted here
  |
  +--ro channel-power* [channel]
  |  +--ro channel    -> /channel-plan/channel/name
  |  +--ro power* [location]
  |     +--ro location         string
  |     +--ro optical-power    opendevice-types:optical-power-dBm
  +--ro aggregate-power* [location]
     +--ro location         string
     +--ro optical-power    opendevice-types:optical-power-dBm
```
Here's a typical log of `dp_get_items`:
```
dp_get_items: XPath /czechlight-roadm-device:channel-power req 104 orig-XPath /czechlight-roadm-device:channel-power//.
dp_get_items: XPath /czechlight-roadm-device:channel-power[channel='C-band (OCM)']/power req 104 orig-XPath /czechlight-roadm-device:channel-power//.
dp_get_items: XPath /czechlight-roadm-device:channel-power[channel='C-band']/power req 104 orig-XPath /czechlight-roadm-device:channel-power//.
dp_get_items: XPath /czechlight-roadm-device:channel-power[channel='C26 (100GHz)']/power req 104 orig-XPath /czechlight-roadm-device:channel-power//.
dp_get_items: XPath /czechlight-roadm-device:channel-power[channel='C27 (100GHz)']/power req 104 orig-XPath /czechlight-roadm-device:channel-power//.
dp_get_items: XPath /czechlight-roadm-device:channel-power[channel='C28 (100GHz)']/power req 104 orig-XPath /czechlight-roadm-device:channel-power//.
dp_get_items: XPath /czechlight-roadm-device:channel-power[channel='C29 (100GHz)']/power req 104 orig-XPath /czechlight-roadm-device:channel-power//.
dp_get_items: XPath /czechlight-roadm-device:channel-power[channel='C30 (100GHz)']/power req 104 orig-XPath /czechlight-roadm-device:channel-power//.
dp_get_items: XPath /czechlight-roadm-device:channel-power[channel='C31 (100GHz)']/power req 104 orig-XPath /czechlight-roadm-device:channel-power//.
dp_get_items: XPath /czechlight-roadm-device:channel-power[channel='C32 (100GHz)']/power req 104 orig-XPath /czechlight-roadm-device:channel-power//.
dp_get_items: XPath /czechlight-roadm-device:channel-power[channel='C33 (100GHz)']/power req 104 orig-XPath /czechlight-roadm-device:channel-power//.
dp_get_items: XPath /czechlight-roadm-device:channel-power[channel='C34 (50GHz)']/power req 104 orig-XPath /czechlight-roadm-device:channel-power//.
dp_get_items: XPath /czechlight-roadm-device:channel-power[channel='C35 (100GHz)']/power req 104 orig-XPath /czechlight-roadm-device:channel-power//.
dp_get_items: XPath /czechlight-roadm-device:channel-power[channel='C54 (100GHz)']/power req 104 orig-XPath /czechlight-roadm-device:channel-power//.
dp_get_items: XPath /czechlight-roadm-device:channel-power[channel='C55 (100GHz)']/power req 104 orig-XPath /czechlight-roadm-device:channel-power//.
dp_get_items: XPath /czechlight-roadm-device:channel-power[channel='C55 (50GHz)']/power req 104 orig-XPath /czechlight-roadm-device:channel-power//.
```
This behavior is very different from invocation on another top-level list (`/aggregate-power`) whose keys are not leaves. In that case sysrepo of course cannot possibly know all these list values, and therefore it simply invokes my callback once:
```
dp_get_items: XPath /czechlight-roadm-device:aggregate-power req 105 orig-XPath /czechlight-roadm-device:aggregate-power//.
```
Is this difference intentional, or is that considered a bug?

This is on last week's `devel` of everything I believe.

**Comment by michalvasko** [comment]
Hi,
maybe I am overlooking something but it seems to me it is working exactly as [documented](http://www.sysrepo.org/static/doc/html/subscribtions.html#stateDataStructure). The difference should be due to the fact that `channel-power` has a nested list `power`. `aggregate-power` does not have any list or container descendant (something that could have further descendants).

Regards,
Michal

**Comment by jktjkt** [comment]
Ah, thanks, you're right, I missed that. Right now it is quite handy that this stuff works when the first callback returns also content of the nested lists (that these data are not discarded).

Thanks for clarifying once again.

**Comment by myonlystarWang** [comment]
> Hi, maybe I am overlooking something but it seems to me it is working exactly as [documented](http://www.sysrepo.org/static/doc/html/subscribtions.html#stateDataStructure). The difference should be due to the fact that `channel-power` has a nested list `power`. `aggregate-power` does not have any list or container descendant (something that could have more descendants).

Hi @michalvasko ,
    Sorry to bother you but could you please provide the new link above? (When I clicked on it, the link was no longer available)
    I have encountered the problem that the YANG model has nested lists. I want to subscribe to each leaf change in the nested list, and I am looking for the relevant solution.

**Comment by michalvasko** [comment]
[Here](https://netopeer.liberouter.org/doc/sysrepo/master/html/), linked in *sysrepo* README badges.

**Comment by myonlystarWang** [comment]
> [Here](https://netopeer.liberouter.org/doc/sysrepo/master/html/), linked in _sysrepo_ README badges.
Thank you for your reply. It's very kind of you！
