### ISSUE TITLE
sysrepo: sr_get_item return err ipaddr

### ISSUE THREAD

**Issue by nic1225** [sysrepo/sysrepo#1448]
hi
 ### I used sysrepo-0.7.7, test wih yang file like this:

    container interfaces {
      description
        "Interface configuration parameters.";
      list interface {
        key "name";
        description          "The list of configured interfaces on the device.";
		  
        leaf name {
          type string;
          description
            "The name of the interface.";
        }
        leaf ip {
          type inet:ipv4-prefix;
          description
            "The IPv4 address with prefix on the interface.";
        }
      }  // list interface
    }  // container interfaces

### and C code like this:

    sr_module_change_subscribe(session, "dev-monitor", sysrepo_interfaces_changes_cb, NULL, 0, SR_SUBSCR_DEFAULT, &subscription);
    int sysrepo_interfaces_changes_cb(sr_session_ctx_t *session, const char *module_name, sr_notif_event_t ev, void *private_ctx)
    {
        ...
        rc = sr_get_item(session, "/dev-monitor:interfaces/interface[name='br-lan']/ip", &val);
        if (rc == SR_ERR_OK) 
        {
            printf("00 buff = %s \n",val->data.string_val);
        }
        sr_free_val(val);
    
        return SR_ERR_OK;
    }
### when i modify databuff use: edit-config --target running --config
	
    <interfaces xmlns="urn:sysrepo:dev-monitor">
      <interface>
        <name>br-lan</name>
        <ip>192.168.2.4/16</ip>
      </interface>
    </interfaces>

### console print  like this:
    00 buff = 255.255.0.0/16 
###  I think it should be like this
    00 buff = 192.168.2.4/16

**Comment by michalvasko** [comment]
Hi,
the output is actually transformed exactly as [specified](https://github.com/YangModels/yang/blob/master/vendor/cisco/xr/534/ietf-inet-types.yang#L299). Server must always respond with canonical values.

Just a note, if you want to store both IPv4 address and its prefix, there is no standard type for this, they are stored separately (hence this issue).

Regards,
Michal
