### ISSUE TITLE
when get call state timeout, cannot get data except restart sysrepod 

### ISSUE THREAD

**Issue by TiejunShuang** [sysrepo/sysrepo#1449]
### Things you may try first
(put "x" in "[]" if you already tried following)
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description
[Description of the bug or feature]

### Steps to Reproduce
In our stress test. We send the get rpc continuous from controller.  After we got error log: 
"sysrepod[1320]: [ERR] (rp_handle_get_call_state:690) Time out waiting for operational data expired before all responses have been received, session id = 105483332, req = 8616" .
After that we cannot get the state data except restart sysrepod.  But get the configure data is ok and get data by sr_get_items() is ok. 
How can we get this status, if we can get it. We can restart the sysrepod. 

### Versions
Please provide versions for software needed to reproduce the bug:
Sysrepo version: 0.77.
libyang version: 0.16.52
netopeer2-server: 0.7

Thanks!
Tiejun

**Comment by TiejunShuang** [comment]
[message.txt](https://github.com/sysrepo/sysrepo/files/2990568/message.txt)

**Comment by michalvasko** [comment]
Hi,
I am currently busy with new *sysrepo* which is of a higher priority. Nevertheless, even after a timeout it should continue to work normally but, you generally should not get any timeouts. So, my suggestion is to increase the timeout. I may look at this later but there is a real chance fixing this would require too much time to be even worth it, in which case it will not be fixed.

Regards,
Michal

**Comment by TiejunShuang** [comment]
Hi Michal ,
Thanks for your comment.  I want to find out the root cause of the time out, in fact I have set OPER_DATA_PROVIDE_TIMEOUT to 20 sec. But timeout happened sometimes, and the data provider only spend about 3-10 sec.  I find that the time for get data from controller is from 3 sec to over 20 sec(timeout),  any suggestion to debug?

Thanks,
Tiejun

**Comment by michalvasko** [comment]
Hi,
then I cannot really help you, I do not know why there would be such differences and why would the timeout be shortened.

Regards,
Michal

**Comment by TiejunShuang** [comment]
Hi Michal,
Would you please tell me which function is for parse regular expression. I want to modify it to check the last $.
Thanks,
Tiejun

**Comment by michalvasko** [comment]
Hi Tiejun,
I am not sure what is it you want to do but all patterns are processed by *libyang*, `parser.c:lyp_check_pattern()`.

Regards,
Michal
