### ISSUE TITLE
why "There is a not enabled node in ietf-system module, it can not be committed to the running" occured when I try to call "sr_set_item" in running datastore? 

### ISSUE THREAD

**Issue by shubengang** [sysrepo/sysrepo#1453]
yang file:
```yang
module ietf-system {
                                  container system {
                                          leaf contact {
                                          }
                                          leaf hostname{
                                          }
                                          leaf location{
                                          }
                                          container test1 {
                                          }
                                          container test2 {
                                          }
                                          ….
                                    }
 }
```
subscribe as bellow:
```C
sr_subtree_change_subscribe(xxx1, xxx2,  "/ietf-system:system/test1",  xxxn);
```
when i use sr_set_item to set one node in test1,error occured :
```
There is a not enabled node in ietf-system module, it can not be committed to the running
```
,but when subscribe is as bellow,that is ok:
```C
sr_subtree_change_subscribe(xxx1, xxx2,  "/ietf-system:system",  xxxn);
```
or
```C
sr_module_change_subscribe(xxx1, xxx2,  "/ietf-system",  xxxn);
```
Both of the above subscribe are OK，Why can not use the first method as bellow：
```C
sr_subtree_change_subscribe(xxx1, xxx2,  "/ietf-system:system/test1",  xxxn)
```

**Comment by michalvasko** [comment]
Hi,
I am not sure why would it not work for you, I have tried to use testing module `test-module`, in which I subscribed to `/test-module:university/classes`. I tried to then create a `class` using this `<edit-config>`:
```xml
<university xmlns="urn:ietf:params:xml:ns:yang:test-module">
  <classes>
    <class>
      <title>class1</title>
    </class>
  </classes>
</university>
```
and it worked exactly as expected.

Regards,
Michal

**Comment by shubengang** [comment]
Hi,
Thank you for your reply!
for your yang file, you can add another container(another_container) under university,for example:
<university xmlns="urn:ietf:params:xml:ns:yang:test-module">
  <classes>
    <class>
      <title>class1</title>
    </class>
  </classes>
  **<another_container>
    <example>
      <value>5</value>
    </example>
</another_container>**
</university>
then,you only subscribed to /test-module:university/classes, not  subscribed to another_container,so when you set item at title of clsass, error occured,it shows to me that:another_container is not enable.

i trace the code,in func rp_dt_enable_xpath,i find the container of classes is enabled as DM_NODE_ENABLED_WITH_CHILDREN, university is enabled as DM_NODE_ENABLED,another_container is not enabled.then ,when i set item,in func dm_has_not_enabled_nodes, the func dm_is_node_enabled_with_children for parameter container of university return false,because the container of university set to DM_NODE_ENABLED when subscribed, not DM_NODE_ENABLED_WITH_CHILDREN. so it will  add all nodes of university to list, include another_container. then judge whether the nodes of list are enabled,but another_container is not enabled,so error occured.

**Comment by shubengang** [comment]
sorry,the yang file displays incomplete at previous. the correct yang as follows：
<university xmlns="urn:ietf:params:xml:ns:yang:test-module">
  <classes>
    <class>
      <title>class1</title>
    </class>
  </classes>
  <another_container>
    <example>
      <value>5</value>
    </example>
</another_container>
</university>

thanks!

**Comment by shubengang** [comment]
sorry,the xml displays incomplete previous,the Correct  yang as bellow:

module test-module {
    container university {
          container classes {
                            }
          container another_container {
                            }                 
    }
}

thanks!

**Comment by michalvasko** [comment]
Hi,
so having the module in your last post, you subscribed to `/test-module:university/classes` and when you modified `/test-module:university/another_container` you got an error that it is not enabled? In that case it behaves correctly, `another_container` really is not enabled (there is no callback handling it or any of its children). Why would you think it should not behave this way?

Regards,
Michal

**Comment by shubengang** [comment]
hi, 
i subscribed to /test-module:university/classes, then i modify  /test-module:university/classes,not another_container,in this case,errors occured,it says another_container not enabled.so i think when i subscribed to /test-module:university/classes, i should be able to modify /test-module:university/classes,error should not occur.

thanks.

**Comment by michalvasko** [comment]
Hi,
this is getting confusing, please specify the exact use-case in the same way, if the following one is not correct.

YANG:
```yang
module test-module {
    namespace "urn:t";
    prefix t;
    container university {
          container classes {
          }
          container another_container {
          }                 
    }
}
```
Subscription XPath:
```
/test-module:university/classes
```
Edit config:
```xml
<university xmlns="urn:t">
    <another_container/>
</university>
```

I tried this, *netopeer2* responded with OK.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi,
this is getting confusing, please specify the exact use-case in the same way, if the following one is not correct.

YANG:
```yang
module test-module {
    namespace "urn:t";
    prefix t;
    container university {
        container classes {
            leaf l1 {
              type string;
            }
        }
        container another_container {
            leaf l2 {
              type string;
            }
        }
    }
}
```
Subscription XPath:
```
/test-module:university/classes
```
Edit config:
```xml
<university xmlns="urn:t">
    <classes>
      <l1>aa</l1>
    </classes>
</university>
```

I tried this, *netopeer2* responded with OK.

Regards,
Michal

**Comment by shubengang** [comment]
Hi.
The use case is similar to yours.but what I did was modify it,not create it, the original xml is like this:
<university xmlns="urn:t">
    <classes>
      <l1>aa</l1>
    </classes>
     <another_container>
      <l2>bb</l2>
    </another_container>
</university>
then call the func like this : sr_subtree_change_subscribe(pstSess,  “/test-module:university/classes“, pfCb, NULL, 0, SR_SUBSCR_CTX_REUSE | SR_SUBSCR_NO_ABORT_FOR_REFUSED_CFG, &(m_astSubCtx[m_uiSubCnt].pstSubCtx)) to subscribe.
at last,
Edit config: <l1>aa</l1>  modify to  <l1>cc</l1>,the error occures.it shows to me : 
[DBG] Found not enabled node another_container in module test-module
[ERR] There is a not enabled node in test-module module, it can not be committed to the running.
my sysrepo version is 0.7.6.

thanks.

**Comment by michalvasko** [comment]
Hi,
meaning:

Current config:
```xml
<university xmlns="urn:t">
    <classes>
      <l1>aa</l1>
    </classes>
     <another_container>
      <l2>bb</l2>
    </another_container>
</university>
```
Subscription:
```
/test-module:university/classes
```
Edit config:
```xml
<university xmlns="urn:t">
    <classes>
      <l1>cc</l1>
    </classes>
     <another_container>
      <l2>bb</l2>
    </another_container>
</university>
```

And you get an error saying that `another_container` is disabled? If this is finally your use-case then it is expected because of how *netopeer2-server* and *sysrepo* communicate. *netopeer2-server* does not know that `another_container` is actually not being changed so it tries to set it, but *sysrepo* correctly refuses it. It may not work perfectly, but I think this problem occurs mostly due to wrong `edit-config`.

Regards,
Michal

**Comment by shubengang** [comment]
Hi,
yes,the error log says that the another_container is disabled,and my finally use-case is exactly like this.but i did not use the tool of netopeer2-server,i do that like this:
1.in my init code the  sr_subtree_change_subscribe was called.
2.in my cli code the  sr_set_item was called, then the sr_commit was called at last.
i just use the sysrepo's api to operate it.

thanks.

**Comment by michalvasko** [comment]
Hi,
I really do not understand why could you not have said this in the initial description of the issue and save me all the replies. Now, please, can you EXACTLY specify what is it that you are doing?

YANG:
```yang
module test-module {
    namespace "urn:t";
    prefix t;
    container university {
        container classes {
            leaf l1 {
              type string;
            }
        }
        container another_container {
            leaf l2 {
              type string;
            }
        }
    }
}
```
Current config (retrieved from `sr_get_*` functions):
```xml
<university xmlns="urn:t">
    <classes>
      <l1>aa</l1>
    </classes>
    <another_container>
      <l2>bb</l2>
    </another_container>
</university>
```
Subtree subscription:
```
/test-module:university/classes
```
Then you call:
```C
sr_set_item_str(session, "/test-module:university/classes/l1", "cc", 0);
sr_set_item_str(session, "/test-module:university/classes/l2", "bb", 0);
sr_commit(session);
```

Resulting in the error that `another_container` is not enabled? Please, specify your code in this way. I will not reply until then, there are better things for me to do.

Regards,
Michal

**Comment by shubengang** [comment]
Hi,
I think I found out the reason for the error.if i modiy the original xml to like this:
```
<university xmlns="urn:t">
    <classes>
      <l1>cc</l1>
    </classes>
</university>
```
that is delete the bellow:
```
     <another_container>
      <l2>bb</l2>
    </another_container>
```
The error did not occur.
it means that if i don't subscribe to the path, the startup xml should not be include the value of the path.
Is that so?

thanks.

**Comment by michalvasko** [comment]
Look, you continue to add and change details of your issue so I give up trying to help you. If it works for you now, great.

Regards,
Michal
