### ISSUE TITLE
sysrepocfg edit running target lost some configuration

### ISSUE THREAD

**Issue by nic1225** [sysrepo/sysrepo#1454]
hi，
   ###  The default loads the following configuration,This will prompt the device to listen on port 830
    <netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
      <listen>
        <endpoint>
          <name>test_ssh_listen_endpt</name>
          <ssh>
            <address>::</address>
            <port>830</port>
            <host-keys>
              <host-key>
                <name>test_ssh_listen_key</name>
                <public-key>ssh_host_rsa_key</public-key>
              </host-key>
            </host-keys>
          </ssh>
        </endpoint>
      </listen>
    </netconf-server>    
    
 ###  when I use command "sysrepocfg -f xml -d running -i /usr/share/netopeer2-server/ssh_callhome.xml ietf-netconf-server" add the following  configuration.   Port 830 listening disabled.
    <netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
      <call-home>
        <netconf-client>
          <name>test_ssh_ch_client</name>
          <ssh>
            <endpoints>
              <endpoint>
                <name>test_ssh_ch_endpt</name>
                <address>127.0.0.1</address>
                <port>4334</port>
              </endpoint>
            </endpoints>
            <host-keys>
              <host-key>
                <name>test_ssh_callhome_key</name>
                <public-key>ssh_host_rsa_key</public-key>
              </host-key>
            </host-keys>
          </ssh>
          <connection-type>
            <persistent/>
          </connection-type>
        </netconf-client>
      </call-home>
    </netconf-server>

 ###  but when i enter in netopeer2-cli mode,and use command "edit-config --target running --config=/usr/share/netopeer2-server/ssh_callhome.xml" add the same configuration , Port 830 listening work well.

 ###  So if I want to use the sysrepocfg  command, I need to write the above two XML files together to make the listener port 830 work with the callhome function.

Thanks!

**Comment by michalvasko** [comment]
Hi,
you should use `-m` instead of `-i`, then it will work as you expect it to.

Regards,
Michal
