### ISSUE TITLE
[Query] Multiple operational data get requests seen after sending whole tree

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1459]
Hi,

I am trying to implement operational data for say ietf-interfaces.

I am registering data provider callback for main `interfaces-state` container which returns values and count.
After sending whole content with available data, some interfaces doesn't have some stats in internal containers for an interface eg. no ipv4 address for an interface.

In this case even we sent whole data to sysrepo, I have seen multiple data requests for these no data nodes.

Is there a way to block these further requests or a way to inform sysrepo that there is no further data?

**Comment by michalvasko** [comment]
Hi,
it seems to me you are not familiar with the details of how state data are provided in *sysrepo*. Please, take a look [here](http://www.sysrepo.org/static/doc/html/subscribtions.html#data_providers) and you should understand why it behaves the way it does. If not, feel free to ask again.

Regards,
Michal
