### ISSUE TITLE
How to know which data node(s) has been changed?

### ISSUE THREAD

**Issue by yunyuaner** [sysrepo/sysrepo#146]
When subscribed module change event fired, how to know specificity which data node has been changed?

Thanks/Jia

**Comment by rastislavszabo** [comment]
Hi Jia,

it is a feature that we are just working on and should be ready in a few weeks. You can have a look at the API in *devel* branch, it contains the `sr_get_changes_iter` and `sr_get_change_next` functions aimed for this purpose:

https://github.com/sysrepo/sysrepo/blob/devel/inc/sysrepo.h#L1032-L1065

If you want to be informed about the progress, you can subscribe to our mailing lists:

http://lists.sysrepo.org/listinfo
