### ISSUE TITLE
C++ bindings without swig

### ISSUE THREAD

**Issue by YohanPipereau** [sysrepo/sysrepo#1460]
Hi,

In sysrepo/swig/CMakeLists.txt, on master branch and devel branch there is "find_package(SWIG 3.0.12 REQUIRED)", would that be possible to remove the REQUIRED flags for the find_package in order to be able to generate cpp bindings without installing swig ?

Indeed, the REQUIRED flag causes the compilation to fail if cmake variable SWIG_FOUND is false so you can not do something like:
`cmake -DGEN_LANGUAGE_BINDINGS=ON -DGEN_CPP_BINDINGS=ON -DGEN_{JAVA,LUA,PYTHON}_BINDINGS=OFF `

**Comment by michalvasko** [comment]
Hi,
you are right, it should work like that now in `devel`.

Regards,
Michal
