### ISSUE TITLE
Is there any API to convert data received from edit-config in sysrepo to xml 

### ISSUE THREAD

**Issue by Akijdarvajkar** [sysrepo/sysrepo#1465]
Description
Is there any API to convert data received from edit-config in sysrepo to XML format 

Thanks!

**Comment by michalvasko** [comment]
Hi,
there is no direct API but it is not that difficult to convert *sysrepo* values to *libyang* data tree first (using `lyd_new_path()`) and then print this data tree to XML.

Regards,
Michal

**Comment by Akijdarvajkar** [comment]
Thanks

**Comment by Akijdarvajkar** [comment]
How to change netopeer2  username and password?

**Comment by michalvasko** [comment]
Hi,
kind of unrelated but *netopeer2* uses login credentials from your local system configuration meaning the users you have configured locally.

Regards,
Michal

**Comment by Akijdarvajkar** [comment]
Hi,
But it is taking netconf/netconf as username/password.
Thanks,
Akkij

**Comment by michalvasko** [comment]
Hi,
that means you have `netconf` user with password `netconf` configured on your system.

Regards,
Michal

**Comment by Akijdarvajkar** [comment]
Hi,
I am getting Unknown element "root1" (/) while adding configuration for mymodule.yang .
even namespace is also the same for <root1 xmlns ="urn:mymoduel:1.0"> in yang file.


Thanks,
Akkij

**Comment by michalvasko** [comment]
Hi,
do you have the module installed (listed in `sysrepoctl -l`)? If so, please attach it here.

Regards,
Michal

**Comment by Akijdarvajkar** [comment]
Hi,
The problem was the module was read-only after setting config to true it worked.
Thanks,
Akkij

**Comment by Akijdarvajkar** [comment]
Hi,

I am trying to subscribe to  /notifications:create-subscription  using rpc_subscribe api  `subscribe.rpc_subscribe("/notifications:create-subscription",test_rpc_cb)` but  test_rpc_cb is not getting after creating subscription using netopeer2-cli.

Thanks,
Akkij

**Comment by michalvasko** [comment]
Hi Akkij,
this RPC and almost all RPCs from `ietf-netconf` are handled directly by *netopeer2-server* so they are not passed to *sysrepo*. It is best to write your own RPC definition and test with that. Or are you trying to achieve something specific?

Regards,
Michal

**Comment by Akijdarvajkar** [comment]
Hi,
Is there any way to convert lyd_node to sr_val_u using python API. I am getting lyd_node after parse_data_fd below is code.
`module = ctx.load_module("oven", None)
        root = ctx.parse_data_fd(fd, ly.LYD_XML, ly.LYD_OPT_NOSIBLINGS | ly.LYD_OPT_STRICT | ly.LYD_OPT_GET)
`
Thanks,
Akkij

**Comment by michalvasko** [comment]
Hi Akkij,
there is no python API or even C API to do that, it must be done manually. But, you can reuse the implementation in [netopeer2-server](https://github.com/CESNET/Netopeer2/blob/master/server/operations.c#L1914) if you want. Also, with the next generation *sysrepo* you can always work only with *libyang* data trees (`struct lyd_node`) so it will no longer be needed to do any conversion.

Regards,
Michal

**Comment by Akijdarvajkar** [comment]
Thanks,

**Comment by Akijdarvajkar** [comment]
Hi,
some time in python subscribe call `(subscribe.dp_get_items_subscribe("/oven:oven-state",dhcp_state_cb,None, sr.SR_SUBSCR_CTX_REUSE))` is not working.There are no logs also.I tried c example it is working fine.

Thanks
Akkij
