### ISSUE TITLE
Sysrepo Api to lock DB

### ISSUE THREAD

**Issue by rosy8** [sysrepo/sysrepo#1467]
Hi Michal,

 sr_lock_datastore(sr_session_ctx_t *session)  can be used to take the lock of the sysrepo db. However it locks the datastore to which the session is tied to .

Is there any api  which i can use  to lock a specific DB. 
For example :-
sr_lock_db(session, "SR_DS_CANDIDATE");  

Thank you in advance.

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
no, but you can always create a session, lock the particular datastore, and then stop the session.

Also, I have noted your use-case (I think it was you) of wanting to do some proprietary locking on NETCONF `<lock>` and `<unlock>` RPCs and I want to support it, most likely, in the new *netopeer2* once the new *sysrepo* is finished.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

Thank you for replying.

The issue is I need to do so (locking a particular datastore ) through code. (i.e Not by using some netconf client). 

Regarding "proprietary locking on NETCONF <lock> and <unlock> RPCs",  Yes I had mentioned about that. Thank you for working on it.

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,

> The issue is I need to do so (locking a particular datastore ) through code. (i.e Not by using some netconf client).

That is what I meant, create a *sysrepo* session, call `sr_lock_datastore()` and stop the *sysrepo* session.

> Regarding "proprietary locking on NETCONF and RPCs", Yes I had mentioned about that. Thank you for working on it.

I just thought the issue were related, if not, then never mind.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

Thank you Michal. Got it.  It was helpful.
Had never seen that portion of the code.

Yes the issue is related but had to fix this asap. So had to use some other tricks :).
But please add that changes, that will be helpful .

Regards,
Rosy

**Comment by rosy8** [comment]
Hi Michal,

Thank you for replying. It was helpful.
But did not understand why you say stopping the session. As per my knowledge stopping the sysrepo session will unlock the db.
Please let me know if I am missing something.

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
you are right, sorry, you need to have the session running while you want the lock to be held.

Regards,
Michal

**Comment by roycyt** [comment]
Hi Michal,

> Also, I have noted your use-case (I think it was you) of wanting to do some proprietary locking on NETCONF <lock> and <unlock> RPCs and I want to support it, most likely, in the new netopeer2 once the new sysrepo is finished.

Do you have more information to share about the *new sysrepo*? It was mentioned at [Netopeer2](https://github.com/CESNET/Netopeer2/issues/371#issuecomment-449361669) too.

**Comment by michalvasko** [comment]
Hi,
what information do you have in mind? It is currently being tested and documented having all core (and even some additional) features implemented. I would like to start new *netopeer2-server*, which will work with the new *sysrepo*, implementation soon.

Regards,
Michal

**Comment by roycyt** [comment]
Hi Michal,

Quote from https://github.com/CESNET/Netopeer2/issues/371#issuecomment-449361669

> I would suggest you wait for the new sysrepo that should be released in about half a year and which should have no dependencies and be much smaller/simpler overall.

I am interested in:

1. What do you mean by "no dependencies" and "much smaller/simpler overall"?
1. Are those improvements already in the devel branch?

**Comment by michalvasko** [comment]
Hi,

1. By no dependencies I mean that he new *sysrepo* requires only *libyang*, while the current one also needs *libev*, *libredblack*/*libavl*, Google Protocol Buffers, and *protobuf-c*. It is simpler because many unnecessary features were removed (such as `sysrepod`) and others were simplified with no impact on their functionality (actually, it often added to it). It is even smaller, its source has around 800 kB while the current sysrepo has 2.1 MB.
2. It is a complete rewrite from scratch and if you want to take a look, it can be found in [my fork](https://github.com/michalvasko/sysrepo/tree/sysrepo2) of sysrepo in the branch `sysrepo2`. But like I said, it is still a work-in-progress.

Regards,
Michal

**Comment by roycyt** [comment]
Hi Michal,

> It is simpler because many unnecessary features were removed (such as sysrepod) and others were simplified with no impact on their functionality (actually, it often added to it).

Regarding the unnecessary features, do you mean that the sysrepo-plugind will be removed? 

I just checked the sysrepo2 fork and did not see the sysrepo-plugind implementation.

**Comment by michalvasko** [comment]
Hi,
I meant `sysrepod`, not `sysrepo-plugind` but you are right, it is not there for now. I will add it there before release as it is work for a day at most, no worries.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

With respect to your   earlier comment 
_**_"Also, I have noted your use-case (I think it was you) of wanting to do some proprietary locking on NETCONF <lock> and <unlock> RPCs and I want to support it, most likely, in the new netopeer2 once the new sysrepo is finished."_**_

Would you please let me know by when(approximate timeline) this support will be available ?

Thank you in advance.

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
that is quite hard to say, anything from a month to several of them.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

Is the  proprietary locking on NETCONF and RPCs is done ?

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
actually, it is finished in `devel` of *sysrepo*. Specifically, you are able to subscribe to any standard NETCONF RPC (`<lock>`) and whenever *netopeer2* executes it, you will be notified. What is more, you even have the option to return an error and then *netopeer2* locking callback will not be called. Is that all you required?

Regards,
Michal
