### ISSUE TITLE
Is there a way to hide internal schema?

### ISSUE THREAD

**Issue by chunlovemail** [sysrepo/sysrepo#1468]
Hi,
    I had install internal.yang and import internal.xml as device internal use. I don't want them shown to user.
    When I send NETCONF GET command, it will show the internal.yang has been installed.
    Is there a way to hide the internal.yang that customer can not know?

Thanks!
Chuny

**Comment by michalvasko** [comment]
Hi Chuny,
no, this is generally not possible but you should be able to get the functionality you want by configuring [NACM](http://www.sysrepo.org/static/doc/html/ac_page.html#nacm) correctly.

Regards,
Michal

**Comment by chunlovemail** [comment]
Hi Michal,
    Thanks!

Chuny
