### ISSUE TITLE
Error installing new revision of model

### ISSUE THREAD

**Issue by jimenaCabrejas** [sysrepo/sysrepo#1470]
### Things you may try first
(put "x" in "[]" if you already tried following)
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description
Hi,

I’m trying to install the yang model ietf-interfaces@2018-02.20.yang but I get an error saying that this module is already implemented in a previous revision. 
Is there a way to update or upgrade a module to a newer revision? Or I must uninstall the old module and all its dependencies and then install the new revision? 

### Steps to Reproduce
1. Download yang module:
https://github.com/YangModels/yang/blob/master/standard/ietf/RFC/ietf-interfaces%402018-02-20.yang

2. Install
`sysrepoctl -i --yang=/home/jimena/yangModels/ietf-interfaces@2018-02-20.yang --owner=jimena:jimena --permissions=666`

**Expected behavior:**
The module is installed.

**Actual behavior:**
```
Installing a new module from file '/home/jimena/yangModels/ietf-interfaces@2018-02-20.yang'...
Installing the YANG file to '/home/jimena/sysrepo/build/repository/yang/ietf-interfaces@2018-02-20.yang'...
[ERR] (md_insert_lys_module:1935) Module 'ietf-interfaces' is already implemented in revision '2014-05-08'.
Error: Unable to insert the module into the dependency graph.
Reverting the install operation...
Deleted the schema file '/home/jimena/sysrepo/build/repository/yang/ietf-interfaces@2018-02-20.yang'.
Install operation failed.

```

### Versions
Please provide versions for software needed to reproduce the bug:
Sysrepo version: 0.7.7
libyang version: 1.1.3
netopeer2-server: 0.7.10

Thanks!
Jimena

**Comment by michalvasko** [comment]
Hi,
no, you have to uninstall the old module and only then you can install the new one.

Just a note, the new sysrepo will support module update preserving the data.

Regards,
Michal

**Comment by jimenaCabrejas** [comment]
All right!!

Thank you so much for your prompt reply!

Regards,
Jimena
