### ISSUE TITLE
[Query] State data subscription for a grouping in another module

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1471]
Hi
I have a sample yang as below
```
module b {
  namespace b;
  grouping B {
    container bc{
      config false;
      leafs
      .
      .
      .
    }
  }
}
```
Another yang model importing b

```
module a {
  namespace a;
  import b{prefix b;}
  container ac{
    config false;
    leafs
    .
    .
    .
  }
  uses b:B;
}
```

In my plugin I am registering different data provider callbacks for xpath `/a:ac` and xpath `/a:bc`

While trying to get the data from above xpaths using `sysrepocfg`  command, 
Request for `/a:ac` giving all data as expected.
Where as for `/a:bc` call back is not getting called.

Is the xpath I am registering is correct?
Please help me to understand the issue.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
there was a bug, it should work properly now.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thank you for the update.
Will verify and let you know.
