### ISSUE TITLE
memory safety for S_Val within an S_Change in the shared_ptr memory model

### ISSUE THREAD

**Issue by andrei-pavel** [sysrepo/sysrepo#1478]
### Things you may try first
(put "x" in "[]" if you already tried following)
* [X] Did you check if this is a duplicate issue?
* [X] Did you test it on the latest sysrepo devel branch?

### Description
This issue does have a workaround so you could categorize it as minor.
I'm a developer using the post 0.7.5 version of Sysrepo with `shared_ptr` versions of C++ Lua binding types, specifically 0.7.7.
I have a use case for saving changes for later use meaning:
```cpp
    std::string model("whatever");
    S_Iter_Change iter(sess->get_changes_iter(model.c_str()));
    std::vector<std::tuple<S_Val, S_Val>> changes;

    while (true) {
        S_Change change(sess->get_change_next(iter));
        changes.push_back({change->old_val(), change->new_val()});
   }
``` 
I've excluded error checks and exception catches for simplicity.
When `S_Change` exits scope, it's destructor is called which frees the values even though I saved a `shared_ptr` to it's values saved in my `vector`.
```cpp
Change::~Change() {
    if (_new)
        sr_free_val(_new);
    if (_old)
        sr_free_val(_old);
}
```
It does not result in a double free, because the deleter of `S_Val` checks if the value is null first. It does result in segmentation fault on my system.
The workaround is I now store `S_Change` instead of `S_Val` and that works perfectly.
However one should not be forced to do so.
It is against the common belief that storing something under a `shared_ptr` provides memory safety for all objects contained and composed under it.
A simple, but maybe not so elegant fix (?) would be to add `#ifndef SWIGLUA` in the destructor.
```cpp
Change::~Change() {
#ifndef SWIGLUA
    if (_new)
        sr_free_val(_new);
    if (_old)
        sr_free_val(_old);
#endif
}
```
And this would have to be repeated for every object that has other composed objects that can be used independently with a `shared_ptr`.

**Expected behavior:**
 Memory is not corrupted.

**Actual behavior:**
 Memory is corrupted.

### Versions
sysrepod - sysrepo daemon, version 0.7.7

Thank you!

**Comment by michalvasko** [comment]
Hi,
LUA bindings were removed in `devel` branch and will not be in the next release so I am not sure there is any point in fixing them.

Regards,
Michal

**Comment by andrei-pavel** [comment]
Hello,

I'm terribly sorry, I meant the C++ swig bindings.

I mentioned `#ifndef SWIGLUA` because I thought that is how you determine to use raw pointers vs `shared_ptr`. But I realize that is specific to Lua which makes the fix above incorrect.

Since you still use `shared_ptr`, the issue still stands.
Since you only use `shared_ptr` now, the fix is as simple as:
```cpp
Change::~Change() = default;
```
I'll write a unit test that proves this in maximum three weeks time, maybe earlier.

If you want to replicate, you can put the first C++ code snippet above in a module-change-subscribe callback, optionally do some memory allocations and write to that memory to incentivize the SIGSEGV, and then try to access the xpath of a value in a change in the `changes` vector, you should get it.

Regards,
Andrei

**Comment by andrei-pavel** [comment]
Here is a demo of the segmentation fault in the form of a subscriber rather than a unit test. It was easier for me to write it this way.
https://github.com/andrei-pavel/sysrepo-example

**Steps to reproduce**:
1. Make sure installing a new model as `root` is not a problem for you. If it is, modify in `Makefile`.
2. Make sure installing a model named `model` is not a problem for you. If it is, modify in `Makefile` and in `main.cpp`.
3. Adjust the paths to your `libredblack`, `libyang`, `sysrepo` in `Makefile`. If left unmodified, they will be sought in `/opt`.
4. Run `make` with the user owning the model.

**Expected behavior**:
Changes are printed every two seconds.

**Actual behavior**:
Segmentation fault because changes had been freed even though `shared_ptr` still points to it.

Fix and explanation from above are still accurate.

**Comment by michalvasko** [comment]
Hi,
right, thanks, so will you please create a pull request to *sysrepo* `devel`? Easiest that way.

Regards,
Michal
