### ISSUE TITLE
How to use feature_enable python api to enable feature for any module?.

### ISSUE THREAD

**Issue by Akijdarvajkar** [sysrepo/sysrepo#1480]
Thanks!
Akkij

**Comment by michalvasko** [comment]
Hi,
feature manipulation is not available in any API. You have to use `sysrepoctl` for that.

Regards,
Michal

**Comment by Akijdarvajkar** [comment]
Hi ,
How to sync sysrepodb to netopeer2-server?

Thanks,
Akkij

**Comment by michalvasko** [comment]
Hi,
if you mean after you use `sysrepoctl` to enable a feature, then it will happen automatically. However, existing *netopeer2* sessions cababilities will not change, you need to create a new session to use the updated context.

Regards,
Michal

**Comment by Akijdarvajkar** [comment]
Hi,
If  I'm changing the callhome configuration using `sysrepocfg -evim -fxml -dstartup ietf-netconf-server`
Then it is not reflecting in netopeer2-server. I verified using `netopeer2-cli get` command.

Thanks,
Akkij

**Comment by michalvasko** [comment]
Hi,
`get` retrieves `running` and state data, with the `sysrepocfg` command you have modified `startup` data.

Regards,
Michal

**Comment by Akijdarvajkar** [comment]
Thanks,

**Comment by Akijdarvajkar** [comment]
Hi ,
I have written code to set the name to netconf -client for ietf-netconf-server.

` v = sr.Val("test_ssh_ch_client",sr.SR_LIST_T)`

    `session.set_item("/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/name",v)`

I am getting below error:
`Invalid argument`


Thanks,
Akkij
