### ISSUE TITLE
Yang version 1.1 capabilities

### ISSUE THREAD

**Issue by navya46** [sysrepo/sysrepo#1483]
Hi,
 I have installed a yang-version 1.1 model.With the sysrepo version 0.7.3 capabilities are getting exchanged in <hello> message but not with the latest sysrepo version 0.7.7 .From RFC7950 i got to know that Yang 1.1 model doesn't list the capabilities in the <hello> message .Is there any way to retrieve the capabilities in the sysrepo version 0.7.7?

Below is the xml which i used to retrieve the capabilities.
[capabilities.txt](https://github.com/sysrepo/sysrepo/files/3136867/capabilities.txt)

Thanks,
Navya

**Comment by michalvasko** [comment]
Hi Navya,
after connecting (sending the `hello` message), you should retrieve [ietf-yang-library](https://github.com/CESNET/libyang/blob/master/models/ietf-yang-library%402018-01-17.yang) data to get the full set of supported modules. For example, using `get` with XPath filter `/ietf-yang-library:yang-library`.

Regards,
Michal

**Comment by navya46** [comment]
Hi Michal,
 I have used get with XPath filter but even then same thing is happening i wasn't able to retrieve capabilities with the sysrepo latest version .

I have attached yang and output of get in the latest and older sysrepo version.
Yang which i have used:
[sample_yang.txt](https://github.com/sysrepo/sysrepo/files/3151947/sample_yang.txt)
output of get on latest sysrepo version:
[get_latest_version.txt](https://github.com/sysrepo/sysrepo/files/3151963/get_latest_version.txt)
output of get on older sysrepo version:
[get-old-version.txt](https://github.com/sysrepo/sysrepo/files/3151965/get-old-version.txt)

Thanks,
Navya

**Comment by michalvasko** [comment]
Hi Navya,
the "get" output you posted is not a reply to a `<get>` RPC but a reply to `<hello>` message. You want to retrieve some **YANG data**, not **capabilities**.

Regards,
Michal

**Comment by navya46** [comment]
Hi Michal,
It worked able to retrieve all supported modules

Thanks,
Navya
