### ISSUE TITLE
Question - how to read the current configuration/state data from the device

### ISSUE THREAD

**Issue by Dedis23** [sysrepo/sysrepo#1487]
Hello,
I have a question regarding the initialization of the plugin.
My goal is to retrieve the current configuration and state of the device at the moment the plugin is loaded and to load it to the running db.
And so later it could be adjusted via edit-config requests or read via get state requests.
I would like to know what API does sysrepo give to get this functionality as well as guidance as to what is the right way to implement this.

Thanks in advance,
Dedi

**Comment by michalvasko** [comment]
Hi Dedi,
based on what you wrote I am going to assume you are implementing a *sysrepo* plugin. Then, you should set the current device configuration in `sr_plugin_init_cb`. Do that for `SR_DS_RUNNING` using `sr_set_item_str` followed by `sr_commit`, for example. If you subscribe to configuration changes (that handle changes made by `edit-config`) after that, you should get the functionality you need.

Regards,
Michal

**Comment by Dedis23** [comment]
Hey Michal, thanks for the answer.

What I did was this:
Within the `sr_plugin_init_cb`  I used the function `sr_module_change_subscribe` and registered a callback with the flags:
`SR_SUBSCR_EV_ENABLED` and `SR_SUBSCR_APPLY_ONLY`.

When the plugin is initialized then the event input of the callback function: `sr_notif_event_t event`
is `SR_SUBSCR_EV_ENABLED` and I thought that this is the place to read the configuration from the device.
However, after I closed my plugin and sysrepod (killed all the related processes),
And then I turned them on again, the event will not trigger again after the subscription in `sr_plugin_init_cb`.

I am trying to understand why the event does not trigger every time the plugin is initialized.
because as I mentioned, I did kill the process.
Is there some sort of persistent memory that is used here?
Also is this the right place to load the configuration from the device?

Thanks in advance,
Dedi

**Comment by michalvasko** [comment]
Hi Dedi,
that all seems fine and should work. Are you sure you killed all the processes? Both *sysrepo-plugind* and *sysrepod* run as daemons unless `-d` parameter is used, so you should double-check it using a process explorer. I am not sure why else would it now work.

Regards,
Michal

**Comment by Dedis23** [comment]
Thanks for the answers, I will recheck.
