### ISSUE TITLE
Two questions want to confirm about the supported YANG version and memory usage

### ISSUE THREAD

**Issue by darcyllingyan** [sysrepo/sysrepo#1490]
Hi,
In the libyang README, it shows ```Current implementation covers YANG 1.0 (RFC 6020) as well as YANG 1.1 (RFC 7950).```.
And in sysrepo README, it shows "YANG 1.1 support".
When I install the yang file with the YANG 1.0 supported pattern for the single quote and double quote.
Use the below yang as example, with the pattern like below, the libyang will report error as the pattern format, when I change the double quote to single quote, it works well.

```
# cat normal.yang 
module normal {
  namespace "http://qingdao_cnet.com/ns/normal/example";
  prefix users;

  container users {
    list user {
      key name;
      leaf name {
        type string;
      }
      leaf type {
        type string {
            length "0..29";
            pattern "[a-zA-Z0-9\*#\.,\-!$()&%/_ ]*";
         }  
      }
    }
  }
}

# sysrepoctl --install --yang=normal.yang --permission=666 --owner=root:root
Installing a new module from file 'normal.yang'...
[ERR] libyang: Encountered invalid character sequence "\*#\.,\-!$".
[ERR] libyang: Module "normal" parsing failed.
Error: Unable to load the module by libyang.
Install operation failed.
```

```
# cat normalab.yang 
module abnormal {
  namespace "http://qingdao_cnet.com/ns/normalab/example";
  prefix ab;

  container users {
    list user {
      key name;
      leaf name {
        type string;
      }
      leaf type {
        type string {
            length "0..29";
            pattern '[a-zA-Z0-9\*#\.,\-!$()&%/_ ]*';
         }  
      }
    }
  }
}

# sysrepoctl --install --yang=normalab.yang --permission=666 --owner=root:root
Installing a new module from file 'abnormal.yang'...
Installing the YANG file to '/etc/sysrepo/yang/abnormal.yang'...
Installing data files for module 'abnormal'...
Notifying sysrepo about the change...
Install operation completed successfully.
```

So my question is:
1.  Based on the [RFC7950 1.1](https://tools.ietf.org/html/rfc7950#section-1.1) and [6.3](https://tools.ietf.org/html/rfc7950#section-6.1.3) , YANG 1.1 should report error with the above example pattern but YANG 1.0 shouldn't report.
So whether it means for some incompatible changes, libyang only support YANG 1.1?

2. I have another question about the memory usage, when installing many YANG files, the installing process will consume much virtual memory and real memory and will not released untill stop the sysrepo, when handling the edit-config/get-config, the memory consumation is much less even for huge XML files, so I want to know the where the code is used for allocating the memory when installing YANG files.  Thanks.

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,

1. Yes, YANG 1.1 should definitely report an error because it is explicitly stated. However, what should happen for YANG 1.0? The [old RFC](https://tools.ietf.org/html/rfc6020#section-6.1.3) says that "backslash introduces a special character, which depends on the next character" and there is an enumeration of the characters that can follow. It says nothing about cases when the character is different, so how exactly should `\*` be interpreted? It is not specified meaning it is implementation-dependent, our implementation reacts with an error. I think such a behavior is perfectly consistent with this RFC.

   The way we were implementing YANG 1.1 support was often changing the behavior to YANG 1.1 because the standard often only defines some not explicitly covered cases in YANG 1.0 so there is no point in implementing 2 different solutions. 

2. This may be a side-effect of the custom memory management *sysrepo* uses (which can be turned off before compilation). The simplest solution is to not have *sysrepod* running when installing new modules or you can try turning it off.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
Thanks very much for the detailed response.
1. For the YANG version issue, I know the libyang implementation intention. Thanks.

2. For the memory usage issue:
    1) I tried the method with not having the sysrepod running when installing new modules, after 
        finished installing modules, I need to startup the sysrepod and netopeer2-server to do edit-config, 
        when starting the sysrepod/netopeer2-server(All the modules will be loaded), the sysrepo memory 
        usage is also in a sustained growth and even more than having the sysrepod running when install 
        new modules. So the 
    2) I'm not clear the way you said about turn the custom memory management off, I didn't find in 
        INSTALL guide, can you show me the method? Thanks.

Thanks
Darcy

**Comment by smalls12** [comment]
When you build via cmake set the cmake variable for custom memory management off.

 cmake -DUSE_SR_MEM_MGMT=0 ..

**Comment by darcyllingyan** [comment]
Hi @smalls12 , 
Thanks for the respons.

Hi Michal, @smalls12 ,
After I turn the custom memory management off. the memory usage is still huge.
1. Below is the memory usage when I install modules **without** sysrepod running.  When starting the sysrepod/netopeer2-server(All the modules will be loaded) to do the edit-config, the sysrepo memory usage, it uses 39.3%.
usage
```
# ps -ef|grep sysrepo
root      4081     1 83 01:52 ?        00:03:25 sysrepod
root      4350  4101  0 01:56 pts/1    00:00:00 grep --color=auto sysrepo
# top -p 4081
top - 01:56:50 up 20 days, 42 min,  2 users,  load average: 0.55, 0.51, 0.29
Tasks:   1 total,   0 running,   1 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  8008856 total,  2330008 free,  3361488 used,  2317360 buff/cache 
KiB Swap:        0 total,        0 free,        0 used.  4264864 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                  
 4081 root      20   0 3328016   3.0g   2668 S   0.0 39.3   3:25.24 sysrepod
```
2. Below is the memory usage when I install the modules with sysrepod running. The memory usage is 27.4% 
```
# ps -ef|grep sysrepo
root      6284     1 16 02:01 ?        00:03:58 sysrepod
root      9234  4101  0 02:25 pts/1    00:00:00 grep --color=auto sysrepo
[root@henry-deploy ~]# top -p 6284
top - 02:25:26 up 20 days,  1:11,  3 users,  load average: 0.02, 0.43, 0.59
Tasks:   1 total,   0 running,   1 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.1 us,  0.5 sy,  0.0 ni, 99.4 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  8008856 total,  3271580 free,  2411844 used,  2325432 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  5208184 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                  
 6284 root      20   0 2431940   2.1g   2852 S   0.0 27.4   3:58.89 sysrepod
```

I have turn the custom memory management off for the above two methods and seems it doesn't reduce any memory.

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
those are really huge numbers, how many models and how large do you have installed, exactly?

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
There are about 320 modules, it's just a example and I just want to check the CPU/memory/disk IO usage for sysrepo.
For the testing result:
1.  Seems the bottleneck is the module installation which consumes too much memory, each new module will consume some memory.
2. I compare the testing result with ConfD, which really has a big difference as below, but for the XML edit-config operation, the memory usage is similar.
```
   The confd:
   average real memory usage: 108M
   average virtual memory usage: 1.1G

   The cnet-c:
    average real memory usage: 3G
    average virtual memory usage: 3.04G
```
3. For the disk I/O pwrite, the confD is about 20kib/s but the sysrepo is 0.6Mib/s, whether it maybe the sysrepo has less disk fragmentation and will have a higher disk I/O?

**Comment by michalvasko** [comment]
Hi,
I see, 320 is quite a lot. Using 3 GB of memory is a lot, I agree, but we will not be optimizing it as the focus is currently on the new *sysrepo*. Once its is out, you can test it there and then we can think about some improvements, if they are needed.

3. It is possible *confD* has a more intelligent database than just a file for each module data so it can optimize writing persistent changes and do not rewrite data that were not changed.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
1. OK, I got it. I will use the new sysrepo once is out to check the performance. Thanks.
But can you show the function which is used to allocate memory when installing modules, the ```md_init``` in ```module_dependencies.c```?
2.  You mean the sysrepo will rewrite data that were not changed which may lead to a higher CPU/disk IO? Below is the pwrite result, do you have any comments why the disk writes increase with time?
![2019-05-13_test](https://user-images.githubusercontent.com/35722818/57604439-c14b6a00-7596-11e9-9e15-abf617bec0a1.jpg)

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
1. `md_init()` just initializes the module-dependencies context, `md_insert_module()` is the one that installs new modules. You would have to use some profiling tool to get the specific function (that is called by `md_insert_module()`) that allocates the memory, I do not know.

2. If this is the graph from installing the modules then it makes sense because of what I said before. You first install the module, so the persistent data are written with 1 module installed. You install another one, they are updated with 2 modules installed (twice the data) and so on.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
1. Thanks for the response, I got it.
2. No, the above App Disk Write(pwrite) graph is from the XML operation(edit-config) to the running datastore. I write 800 XML files to the running datastore based on the YANG modules, above is the XML edit-config graph.

Below is the module installation graph.
![2019-05-13_test1](https://user-images.githubusercontent.com/35722818/57606484-8dbf0e80-759b-11e9-99e6-a9f216884861.jpg)

**Comment by darcyllingyan** [comment]
Hi Michal,

> You first install the module, so the persistent data are written with 1 module installed. You install another one, they are updated with 2 modules installed (twice the data) and so on.

I have one issue about the configuration data merge, every time when merge a new XML file(belong to one module) to the running datastore, whether it will affect other module's configuration data(rewrite )?
For the below example, when write the XML file1, the configuration datastore will contain data about XML file1, when write the XML file 2, the ```a-list``` isn't changed, whether it will rewrite?
1. root.yang
```
module root {
        namespace "http://test/root";
        prefix root;
        container ph {
                list a-list {
                        key "x";
                        leaf x {
                                type uint8;
                        }
                }
        }
}
```
2. child1.yang
```
module child1 {
        namespace "http://test/child1";
        prefix child1;
        import root { prefix root;}
        augment "/root:ph" {
                container inner1 {
                  list b-list1 {
                    key p1;
                        leaf p1 {
                                type uint8;
                        }
                        leaf q {
                           type string
                           } 
                        }
                }
            }
        }
}
```
3. XML file1
```
<ph xmlns="http://test/root">
        <a-list>
            <x>3</x>
        </a-list>
        <a-list>
            <x>1</x>
        </a-list>
        <inner1 xmlns="http://test/child1">
            <b-list1>
                    <p1>5</p1>
                     <q>5</q>
                </b-list1>
        </inner1>
</ph>
```
4. XML file 2
```
<ph xmlns="http://test/root">
        <a-list>
            <x>3</x>
        </a-list>
        <a-list>
            <x>1</x>
        </a-list>
        <inner1 xmlns="http://test/child1">
            <b-list1>
                    <p1>5</p1>
                     <q>4</q>
                </b-list1>
        </inner1>
</ph>
```

**Comment by michalvasko** [comment]
Hi,
generally, *sysrepo* divides all data into modules and handles (modifies) each of them separately. However, in this case you have only one module, strictly speaking (augments are added to the target module), so yes, when you use `XML file 1`, the whole *root* data are rewritten and again when you use `XML file 2`.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Thanks very much Michal, I got it.
