### ISSUE TITLE
Unable to send ietf-alarm notification

### ISSUE THREAD

**Issue by navya46** [sysrepo/sysrepo#1491]
Hi
**Description**
We're unable to send ietf-alarm notifications. sr_event_notif_send returns The peer disconnected error.

**This is what we're trying to send:**
send alarm
    /ietf-alarms:alarm-notification/resource = sampleAlarm
     /ietf-alarms:alarm-notification/alarm-type-id = example-alarms:ex1Alarm
    /ietf-alarms:alarm-notification/alarm-type-qualifier = examplealarm
    /ietf-alarms:alarm-notification/time = 2019-03-10T03:05:00+00:00
    /ietf-alarms:alarm-notification/perceived-severity = minor
    /ietf-alarms:alarm-notification/alarm-text = some text
    /ietf-alarms:alarm-notification/example-alarms:event-id = f0
also_send_ietf_alarm: The peer disconnected

I've attached the yangs and the alarm.c source code in the zip for reference.
[alarms.zip](https://github.com/sysrepo/sysrepo/files/3166196/alarms.zip)

**Steps to Reproduce**
1. Compile alarm.c (preferably as another example in sysrepo).
2. Make sure to install yangs and
3. Start sysrepod and sysrepo-plugind and netopeer2-server.
4.Run ncclient program given in the zip file to receive notification.
5.Run alarm executable on the same system where others are running.

**Expected behavior:**
We expect to see that  alarm notification is received by the ncclient and generation of xml.

**Actual Behaviour:**
Instead of sending alarm notification .when the sr_event_notif_send callback gets hit sysrepod reports seg fault.
**Below are the logs attached for sysrepod**

[DBG] Starting a new session, options=0.
[INF] New session created successfully, real user=root, effective user=(null), session id=70815353.
[DBG] Initiating circular buffer for 2 elements.
[DBG] RP session start, session id=70815353.
[DBG] Sending 33 bytes of data.
[DBG] 33 bytes of data sent.
[DBG] fd 12 readable (revents 1)
[DBG] 559 bytes of data received on fd 12
[DBG] Input buffer for fd=12 expanded to 2048 bytes.
[DBG] fd 12 would block
[DBG] New message of size 555 bytes received.
[DBG] Circular buffer enqueue to position=9, current count=1.
[DBG] Threads: active=0/4, 1 requests in queue
[DBG] Thread id=140200657757952 signaled.
[DBG] Circular buffer dequeue, new buffer head=0, count=0.
[DBG] Processing event notification request (/ietf-alarms:alarm-notification).
[DBG] Switching identity to UID='0' and GID='0' (username: root).
[DBG] Loaded module ietf-alarms: mtime sec=1557471834 nsec=36000000
[DBG] Usage count ietf-alarms incremented (value=1)
[INF] Data file /etc/sysrepo/data/ietf-alarms.running loaded successfully
[DBG] Module ietf-alarms has been loaded
Segmentation fault (core dumped)

Also no XML is generated in (/etc/sysrepo/data/notifications/ietf-alarms).

### ### 
NOTE:
Without augment in example-alarms.yang i was able to receive the notifications and the xml was successfully generated .

Is there any other way to send alarm notification with augment .

Thanks,
Navya

**Comment by michalvasko** [comment]
Hi Navya,
I have tried your use case but with having *netopeer2-cli* instead of your *disp_notification.py* as the notification listener (should not make a difference) and it worked flawlessly. What version are you using? I tested with latest `devel` of *sysrepo*.

Regards,
Michal

**Comment by navya46** [comment]
Hi Michal,
I have used Sysrepo 0.7.7 release version. In my case whenever i run the alarm executable there was a seg-fault on sysrepo.

Thanks,
Navya

**Comment by michalvasko** [comment]
Hi,
you are right, I have tried it with the current `master` and got a crash. So, please use `devel` branch for now (until next release).

Regards,
Michal

**Comment by navya46** [comment]
Hi,
Thanks Michal .I have tried with devel branch and it worked.

**Comment by Julian-younger** [comment]
@navya46 I used function sr_dup_values to copy alarm data，it worked fine so far.

**Comment by selvaitech** [comment]
Hi @michalvasko Can you please confirm if the itef-alarm notification issue has a fix in the latest release version ?

We are using the latest tag and we need to send ietf-alarm notification from netopeer2 simulator?

REPOSITORY                               TAG                     IMAGE ID            CREATED             SIZE
sysrepo/sysrepo-netopeer2                latest                  a681e454dcef        2 weeks ago         666MB

Can you please advice?

**Comment by michalvasko** [comment]
Hi,
based on the information in this thread it should work fine with the latest release 0.7.8.

Regards,
Michal

**Comment by selvaitech** [comment]
@navya46, (Run alarm executable on the same system where others are running) : i am not sure how to run this. Can you please let me know how to run the step-5?

I am new to netopeer simulator, and would like to simulate itef-alarms from netopeer2 simulator.
