### ISSUE TITLE
One question to confirm about the xPath

### ISSUE THREAD

**Issue by darcyllingyan** [sysrepo/sysrepo#1492]
Hi,
Based on the RFC6241 section-8.9, the XPath expression refers to [xpath guide](https://www.w3.org/TR/1999/REC-xpath-19991116/), whether the sysrepo supports all the xpath and if there is some tests to prove or compliance report?

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
supported XPaths are described [here](http://www.sysrepo.org/static/doc/html/xp_page.html). As for some formal compliance information, there is none. Generally, *sysrepo* uses *libyang* XPath implementation that should support [almost full specification](https://github.com/CESNET/libyang/blob/master/src/xpath.h). However, *sysrepo* itself has significant limitations so it is best to stick to the paths mentioned in its documentation. The new *sysrepo* should have no such limitations and where it makes sense (getting data) it should rely strictly on *libyang* hence supporting all it supports.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
Thanks very much for the information, I see.

Thanks
Darcy
