### ISSUE TITLE
subscribe.event_notif_subscribe() python api generates core dump with Segmentation fault

### ISSUE THREAD

**Issue by RPML** [sysrepo/sysrepo#1493]
Description
I am trying to write a sample python application which should get notification whenever netconf session starts and session closes.

Everytime a nc session is established and closed my application generates core dump. 
I am using python api event_notif_subscribe().
This api generates core dump when session-start and session-close notifications are received.

Note: the same application I wrote in c works fine. Only python application has issue.

Expected behavior:
To receive notifications whenever session is established and session closes.

Actual behavior:
core dump is generated with segmentation fault

Versions

Sysrepo version:  sysrepod - sysrepo daemon, version 0.7.7
libyang version: yanglint 1.1.12
netopeer2-server: netopeer2-server 0.7.11

application code:
```python
#!/usr/bin/env python
from __future__ import print_function
import sysrepo as sr
import sys

NC_NOTIFICATIONS_START_XPATH = "/ietf-netconf-notifications:netconf-session-start"
NC_NOTIFICATIONS_END_XPATH = "/ietf-netconf-notifications:netconf-session-end"

def event_test_cb( event, xpath, in_vals, cnt, timestamp, private_ctx):
    try:
        print (" ========== event cb CALLED ==========")
        return

        if (in_vals == None):
            return

        for n in range(in_vals.val_cnt()):
            print (in_vals.val(n).to_string(),end='')


    except Exception as e:
        print (e)

try:
    # connect to sysrepo
    conn = sr.Connection("example_application")

    # start session
    sess = sr.Session(conn)

    # subscribe for changes in running config */
    subscribe = sr.Subscribe(sess)

    print ("\n ========== SUBSCRIBE TO event_notif_subscribe ==========")
    subscribe.event_notif_subscribe(NC_NOTIFICATIONS_START_XPATH, event_test_cb, None, sr.SR_SUBSCR_DEFAULT)
    subscribe.event_notif_subscribe(NC_NOTIFICATIONS_END_XPATH, event_test_cb, None, sr.SR_SUBSCR_DEFAULT)

    sr.global_loop();
```
----
output of execution:
```
python NotificationSubscriber.py

 ========== SUBSCRIBE TO event_notif_subscribe ==========


Segmentation fault (core dumped)
```

BT of coredump attached.
---
modules installed:
```
sysrepoctl -l|grep ietf-netconf-notifications
ietf-netconf-notifications | 2012-02-06 | Installed   | root:root           | 666         |                               |
```
Thanks!
[BT of stack trace.txt](https://github.com/sysrepo/sysrepo/files/3186697/BT.of.stack.trace.txt)

**Comment by RPML** [comment]
Description
I am trying to write a sample python application which should get notification whenever netconf session starts and session closes.

Everytime a nc session is established and closed my application generates core dump. 
I am using python api event_notif_subscribe().
This api generates core dump when session-start and session-close notifications are received.

Note: the same application I wrote in c works fine. Only python application has issue.

Expected behavior:
To receive notifications whenever session is established and session closes.

Actual behavior:
core dump is generated with segmentation fault

Versions

Sysrepo version:  sysrepod - sysrepo daemon, version 0.7.7
libyang version: yanglint 1.1.12
netopeer2-server: netopeer2-server 0.7.11

application code:
#!/usr/bin/env python
from __future__ import print_function
import sysrepo as sr
import sys

NC_NOTIFICATIONS_START_XPATH = "/ietf-netconf-notifications:netconf-session-start"
NC_NOTIFICATIONS_END_XPATH = "/ietf-netconf-notifications:netconf-session-end"

#def event_test_cb( event, xpath, in_vals, cnt, timestamp, private_ctx):
def event_test_cb(xpath, in_vals, holder, private_ctx):
    try:
        print (" ========== event cb CALLED ==========")
        return

        if (in_vals == None):
            return

        for n in range(in_vals.val_cnt()):
            print (in_vals.val(n).to_string(),end='')


    except Exception as e:
        print (e)

try:
    # connect to sysrepo
    conn = sr.Connection("example_application")

    # start session
    sess = sr.Session(conn)

    # subscribe for changes in running config */
    subscribe = sr.Subscribe(sess)

    print ("\n ========== SUBSCRIBE TO event_notif_subscribe ==========")
    subscribe.event_notif_subscribe(NC_NOTIFICATIONS_START_XPATH, event_test_cb, None, sr.SR_SUBSCR_DEFAULT)
    subscribe.event_notif_subscribe(NC_NOTIFICATIONS_END_XPATH, event_test_cb, None, sr.SR_SUBSCR_DEFAULT)

    sr.global_loop();

----
output of execution:
python NotificationSubscriber.py

 ========== SUBSCRIBE TO event_notif_subscribe ==========


Segmentation fault (core dumped)

---
modules installed:
sysrepoctl -l|grep ietf-netconf-notifications
ietf-netconf-notifications | 2012-02-06 | Installed   | root:root           | 666         |                               |

Thanks!

**Comment by RPML** [comment]
The same has been tested with python3 but still the same results.

**Comment by planetofsound** [comment]
I have seen exactly the same problem with event_notif_subscribe() in python. I also have other similar cases with different sysrepo python functions that work fine on a PC but bomb out with segmentation fault when cross-compiled for an embedded board. In all cases the equivalent C code works fine. There do seem to be problems with the Python language binding.

**Comment by RPML** [comment]
Hi,

Could anyone comment whether is there any problem in the way the python api is used or there is bug in the api itself ? 
Also is there any workaround to get the requirement working ?

**Comment by smalls12** [comment]
Are you able to prove if any of the other callbacks are working for you?

Can you just make some blank callbacks that return 0 to test them out?

**Comment by planetofsound** [comment]
We can resolve the event_notif_subscribe() python problem with the attached patch to the python binding code. We are still looking into some other python issues.

[sysrepo_patch.txt](https://github.com/sysrepo/sysrepo/files/3198483/sysrepo_patch.txt)

**Comment by RPML** [comment]
> Are you able to prove if any of the other callbacks are working for you?
> 
> Can you just make some blank callbacks that return 0 to test them out?

As I have already mentioned, similar callback in C is working fine. So the problem seems to be with this python api only

**Comment by RPML** [comment]
> We can resolve the event_notif_subscribe() python problem with the attached patch to the python binding code. We are still looking into some other python issues.
> 
> [sysrepo_patch.txt](https://github.com/sysrepo/sysrepo/files/3198483/sysrepo_patch.txt)

Are you sure that just with this patch the codedump issue is resolved? and the callback works fine?

**Comment by planetofsound** [comment]
It works for me with the patch using this example, it correctly displays the event data.

`
def event_callback(xpath, in_vals, timestamp, private_ctx):
    print('event_callback', xpath, timestamp, private_ctx)
    for index in range(in_vals.val_cnt()):
        print(in_vals.val(index).to_string())
`

**Comment by smalls12** [comment]
@RPML I meant in python.

Goodluck.

**Comment by maggie450** [comment]
On 32-bit target hardware there conflict in the python callback bindings when 64-bit arguments are specified as 'l' (means long) in the Py_BuildValue.  The PyEval_CallObject gets out of step processing its arguments and a crash results.  The workaround is to downcast the 64-bit argument to long.  Suggested patch attached.
[sysrepo-python-binding.txt](https://github.com/sysrepo/sysrepo/files/3372754/sysrepo-python-binding.txt)

**Comment by michalvasko** [comment]
Hi,
thanks for the patch, will get merged.

Regards,
Michal
