### ISSUE TITLE
One question about the sysrepo plugin

### ISSUE THREAD

**Issue by darcyllingyan** [sysrepo/sysrepo#1495]
Hi,
Now the configuation data and state data is stored in sysrepo, if I want to use some other external db, such as Redis to store the data, whether should use the ```sysrepo-plugin``` ?
Based on below description, we could write a new plugin as an interface between sysrepo and other external db, i.e., serialize the sysrepo db content into Redis? Not sure whether my understanding is right, Thanks for correcting.

> There are some use-cases for YANG-based configuration of services, that do not run as userspace daemons and therefore cannot use sysrepo as the primary configuration store. There are also some daemons that simply cannot be natively integrated with sysrepo for whatever reason. For cases like these, we allow developers to write a plugin that would act as an interface between sysrepo and the legacy configuration store of the application/service (e.g. a flat configuration file, or the /proc filesystem).

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
there is no strict difference between writing a normal *sysrepo* plugin and just "an interface between *sysrepo* and external database", it is only about the implementation. The theoretical difference between these approaches is simply that for the former case your plugin translates *sysrepo* configuration changes into the managed device changes (in the most extreme way by writing into its HW) whereas for the latter case they are translated simply to the changes in the external database (which are then normally again applied on the device). Do you understand or need more detailed explanation?

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
Thanks veru much for the response. The plugin and the interface goals are similar and both can realize the request to write data to other external db.
If now I want to use the sysrepo plugin, I still have some questions need to be confirmed. Thanks.
1. Use the keystore plugin as the example, if I want to store the key information to other external db(such as Redis or Vault), now the process of sysrepo-plugin is:
```
connect sysrepo and start one session  ------>  load and init the plugin  -------> opening subscriptions to data modules of interest
```
1. I'm not sure how to associate the sysrepo with other external db, whether there is API to do it? 
2. > simply translates sysrepo configuration changes into the managed device changes
Whether there is API supported to copy all the configuration data to the external db?

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
I think you are complicating it. What you do is simply write into the external DB using whatever API the DB provides in the sysrepo configuration change callback. This way you are just passing the changes further instead of applying them. To copy (apply) all configuration data to the DB, you can, for example, use the [SR_SUBSCR_EV_ENABLED](http://www.sysrepo.org/static/doc/html/group__cl.html#ggac91898627ad5aeb589e6a3993a697d14abca56afa7a1d4f6c01e5e34305762c4e) flag when subscribing.

Regards,
Michal

**Comment by gavin09** [comment]
Hi Michal,

I have a similar question. I have my own config database which has verify ability. Other UIs directly access my own config database. 

I'm looking for a way to
* get running & startup config from that database
* at the verify stage, ask for my own config database
* at the apply stage, apply to my own config database

 Is there a proper subscription option for my case?

Thanks,
Gavin

**Comment by michalvasko** [comment]
Hi Gavin,
you simply need to keep the 2 versions of data consistent.

To get configuration, just use *sysrepo* (data content must be the same if it works properly). When verifying, make your callback to whatever verification it needs to such as communicating with your DB. The same goes for apply, write it into your DB at that stage.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
Thanks very much for your response.

> What you do is simply write into the external DB using whatever API the DB provides in the sysrepo configuration change callback. This way you are just passing the changes further instead of applying them. To copy (apply) all configuration data to the DB, you can, for example, use the SR_SUBSCR_EV_ENABLED flag when subscribing.

Based on your above response, I have several items to be verified:
1. In the sysrepo configuration callback(such as ```sr_module_change_subscribe```), I could use the ```sr_get_changes_iter``` to get the configuration changes to apply to the external db, right?

2. After try the ```SR_SUBSCR_EV_ENABLED```, it will trigger ```SR_EV_ENABLED```, ```SR_EV_VERIFY``` and ```SR_EV_APPLY``` events, I don't understand whether there is any effect of the ```SR_EV_ENABLED```(May be it's just a notification that the startup db is copied to the running db?), so I think ```SR_SUBSCR_DEFAULT``` can be used either, right?

3. I need to keep two versions configuration data(external db and sysrepo), right? Whether there is possibility to only apply data to the external db? 
   If no, whether the two versions **configuration data consistent**  could be kept?

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
1. Of course, you can always use `sr_get_changes_iter` in configuration change callbacks.
2. When using `SR_SUBSCR_EV_ENABLED`, it should trigger additionally only `SR_EV_ENABLED` compared to `SR_SUBSCR_DEFAULT` so it is up to you whether you want to use it. Yes, it notifies about the data being copied from `startup` to `running`.
3. Having a separate copy of the data is a problematic use-case that is not really supported. You should try to keep the data consistent but it can be quite difficult to achieve in some cases.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
Thanks very much for the response.
Just want to confirm item 3.

> Having a separate copy of the data is a problematic use-case that is not really supported. You should try to keep the data consistent but it can be quite difficult to achieve in some cases.

You mean:
1) If I want to have one external db, the sysrepo and external db should coexist, right? 
    And as the data cinsistent issue, having one external db seems isn't fully supported, right?

**Comment by michalvasko** [comment]
Hi Darcy,
yes, for it to work correctly the data should always be the same in the external DB and *sysrepo*. It is not that difficult to set the new changes in *sysrepo* callback into the external DB, so any change in *sysrepo* is propagated into external DB. However, it is difficult the other way around, because even if you somehow copy all the changes in the external DB into *sysrepo*, when applying them the callbacks would want to apply them into the external DB again (the starting premise).

Regards,
Michal

**Comment by darcyllingyan** [comment]
Michal, 
Thanks very much. I got it.
