### ISSUE TITLE
Question - problem with making subscriptions with a specific model

### ISSUE THREAD

**Issue by Dedis23** [sysrepo/sysrepo#1496]
Hello,

The model I am using is microwave-model - ONF TR-532
[https://github.com/OpenNetworkingFoundation/5G-xHaul/blob/master/models/yang/microwave-model.yang](url)

I would like to have the following functionality:
1. subscribe for changes (everything that is without config false)
in this model, it is in:
`mw-air-interface-pac` (which is a list) and then there is a container called `air-interface-configuration.`

2. subscribe as state data provider for the following containers:
they are also all within `mw-air-interface-pac`  (which is a list)
* `air-interface-capability`
* `air-interface-status`
* `air-interface-current-problems`
* `air-interface-current-performance`
* `air-interface-current-performances`

My main problem is that all these containers are within a list, it seems like the xPath that I write when I am calling the function to subscribe is not correct.

I would like to know what is the correct xPath that I should write in the following functions
1. `sr_module_change_subscribe` for the configuration changes
2. `sr_dp_get_items_subscribe` for the state data provider
3. `sr_get_items_iter` to iterate all the nodes in air-interface-configuration so I can read the current configuration from the device and load it to sysrepo running DB.

In the past I worked with a different model, one where everything is within a container and so I didn't have any problems. here in this case, it is a list that has containers so I am probably writing the xPath wrong.

I tried this xPath string with the function `sr_get_items_iter` in order to read all the leaves configurations, the returned value was Operation succeeded however I had nothing to iterate on so this is probably incorrect:
`sr_get_items_iter(session, "/microwave-model:mw-air-interface-pac[layer-protocol=\"1\"]/air-interface-configuration//*",
     &iter);`

- I should point out that I did not find any example in the sysrepo documentation that has a list which is within a top level in the model without it being wrapped within a container.

Thanks in advance,
Dedi

**Comment by michalvasko** [comment]
Hi Dedi,
firstly, `/microwave-model:mw-air-interface-pac[layer-protocol=\"1\"]/air-interface-configuration//*` seems fine to me. At the moment you called it, did you have any `mw-air-interface-pac` instances in the datastore? Was there one with `layer-protocol` value `1`?

As for the rest
1. That should be quite straightforward, just call `sr_module_change_subscribe()` with module name `microwave-model`.
2. The best thing is to subscribe to each container separately such as calling `sr_dp_get_items_subscribe()` with `/microwave-model:mw-air-interface-pac/air-interface-capability`.
3. To get all the nodes in a module, you can use `/microwave-model:*//.` for `sr_get_items_iter()`.

Regards,
Michal

**Comment by Dedis23** [comment]
Hi Michal
Thank you very much for your answer.

> At the moment you called it, did you have any mw-air-interface-pac instances in the datastore? Was there one with layer-protocol value 1?

No, I did not have.
basically, what I want is to be able to read the air-interface-configuration from the yang model (without knowing the actual leaves on it) do you know how can I do that?

> The best thing is to subscribe to each container separately such as calling sr_dp_get_items_subscribe() with /microwave-model:mw-air-interface-pac/air-interface-capability.

I did try that, however it does not work, the callback function is never called when a client make a get request.

> To get all the nodes in a module, you can use /microwave-model:*//. for sr_get_items_iter().

I try that, it doesn't seem give any of the leaves that are within the `mw-air-interface-pac`.

Thanks,
Dedi

**Comment by Dedis23** [comment]
After looking at the model again, I want to explain better what I want:

I would like to be able to read all the nodes within:
`grouping air-interface-status-g`

Is this possible? as this is not a container.

**Comment by michalvasko** [comment]
Hi,
> I would like to be able to read all the nodes within:
> grouping air-interface-configuration-g

You cannot directly do that (`grouping` is just a schema construct, not a data one) but since it is used on a container, you can simply get the container `air-interface-configuration`.

As for your previous reply, you are saying you are unable to get any data whatsoever but that you do not have any instances of `mw-air-interface-pac` configured. Then what exactly are you trying to get if there is nothing to get? You cannot get just the state leaves or anything else if their parent does not exist first.

Regards,
Michal

**Comment by Dedis23** [comment]
Hi,
I guess I did not understand this fully.
can you guide me as to how to create an instance of `mw-air-interface-pac` within the running DB?
Thanks

**Comment by michalvasko** [comment]
Hi,
the simplest way is using `sysrepocfg -evim -fxml microwave-model` and writing some XML data such as
```xml
<mw-air-interface-pac xmlns="urn:onf:params:xml:ns:yang:microwave-model">
  <layer-protocol>0<layer-protocol>
</mw-air-interface-pac>
<mw-air-interface-pac xmlns="urn:onf:params:xml:ns:yang:microwave-model">
  <layer-protocol>1<layer-protocol>
</mw-air-interface-pac>
```
Note that you need to put the namespace on every top-level node, which are list instances in this case, so each one must have it. Also, just adding this configuration into *sysrepo* will fail validation (you can try it) because there will be missing leafref targets (`layer-protcol` is a leafref). So just create the targets in the `core-model` data and it should validate.

Regards,
Michal

**Comment by Dedis23** [comment]
Hey thanks for the answers.
As you said, I do need to create the targets in the core-model data.
However, I am facing some problems with it.
Do you know if there is a simple way to create the core-model data with everything set to default except the `uuid` (layer-protocol)?
Thanks

**Comment by michalvasko** [comment]
Hi,
I was hoping you would figure that on your own, these issues are not here to go through basics of *sysrepo*. Just use `sysrepocfg -evim -fxml core-model` again, but you also need to subscribe to its running data for it to work, `examples/application_example core-model microwave-model` it can subscribe to any number of models. For `sysrepocfg` you can use this XML
```xml
<network-element xmlns="urn:onf:params:xml:ns:yang:core-model">
  <ltp>
    <uuid>id0</uuid>
    <lp>
      <uuid>0</uuid>
    </lp>
    <lp>
      <uuid>1</uuid>
    </lp>
  </ltp>
</network-element>
```
for instance, to work with my previous examples (there could be some minor mistakes, I have not tested it).

Regards,
Michal

**Comment by Dedis23** [comment]
Thank you very much. I managed to get it work.
One last question please, is there an API to load the XML data and not by using sysrepocfg?
Thanks in advance,
Dedi
