### ISSUE TITLE
inconsistent xpath parsing

### ISSUE THREAD

**Issue by gitter-runner** [sysrepo/sysrepo#1497]
Hi!

I'm writing a test application which subscribes for the ietf-system current-datetime oper data. Now, after changing the code a little bit I realized that getting the current- datetime wasn't working anymore. Nor getting any oper data in fact.

The change was, that while constructing the XPath I now print the module name of every node before its name. E.g.,

BEFORE: /ietf-system:system-state/clock/current-datetime
AFTER:  /ietf-system:system-state/ietf-system:clock/ietf-system:current-datetime

sysrepo says the following:

Error: Item not found (1)
% ERROR Unknown error

If I manually get the BEFORE version it works. Config data also works.
The sysrepo version is 0.7.7

Thanks!

**Comment by michalvasko** [comment]
Hi,
it is not inconsistent, you are supposed to use [Data Path](http://www.sysrepo.org/static/doc/html/xp_page.html#data). There is a link to JSON instance-identifier definition, which forbids the other format so it behaves as it should.

Regards,
Michal

**Comment by gitter-runner** [comment]
Thanks! I guess I just thought that always explicitly stating the module name is the most obvious solution. Is there a reason it worked for config data?

Regards

**Comment by michalvasko** [comment]
Well, that is an inconsistency :) As long as what should work really works, there is no problem. The rest may or may not work regarding these paths, it depends on what functions were internally used.

Regards,
Michal

**Comment by gitter-runner** [comment]
Thanks for the help and info!
