### ISSUE TITLE
Write sr_node_t back to datastore

### ISSUE THREAD

**Issue by knoll01** [sysrepo/sysrepo#1500]
I am using sysrepo 0.7.7 and am new to the API. I am able to use sr_get_subtree() to obtain an sr_node_t from the datastore. I am also able to modify the value, if desired, using set() or set_str_data().

Once the sr_node_t is modified as desired,  I would like to write it back into the datastore, but I cannot quite figure out how to accomplish this.

Even better, i would like to be able to create an sr_node_t tree structure from scratch (sr_new_tree, for example), add children and write it into the datastore.

Is this possible? If so, how?

**Comment by michalvasko** [comment]
Hi,
I am not sure why this would be a problem, there are not that many functions in *sysrepo*. To write a `sr_val_t`, just use [sr_set_item()](http://www.sysrepo.org/static/doc/html/group__cl.html#ga8aa733782a1e7d5412cf2bb85ec35355) followed by [sr_commit()](http://www.sysrepo.org/static/doc/html/group__cl.html#ga032ce4dc5810ad2e72501f2975e5737e). To create new values, you can do so without any special functions or use some of those found [here](http://www.sysrepo.org/static/doc/html/values_8h.html) for convenience.

Regards,
Michal

**Comment by knoll01** [comment]
Writing an sr_val_t using sr_set_item is not a problem.  I am trying to write an sr_node_t ( a tree ).

Are you suggesting that sr_node_t can be cast to an sr_val_t? If this is possible, it isn't quite clear.

**Comment by michalvasko** [comment]
Hi,
sorry, I read too hastily. Yeah, there is no way of writing a whole tree of `sr_node_t`, it is best to avoid it in the current *sysrepo* anyway. However, this is possible in the new *sysrepo*, so if you wait around a month and a few weeks, it will work. Sorry.

Regards,
Michal

**Comment by knoll01** [comment]
I look forward to this feature in the upcoming release. Meanwhile I will implement without it.

**Comment by michalvasko** [comment]
Fixed.
