### ISSUE TITLE
Can I get the set of keys for a list?

### ISSUE THREAD

**Issue by andrei-pavel** [sysrepo/sysrepo#1503]
This is a question rather than an issue.

I'm using the C++ Sysrepo client library and I need a way to determine the set of keys for a list which is found at a specific xpath. Something like a function `std::vector<std::string> getKeysOfList(std::string const& xpath);`

So for a model looking like so:
```
          list subscribers {
            key "subscriber";

            leaf subscriber {
              type uint32;
            }

            leaf subscriber-id {
              type string;
            }
          }
```
I would get `[ "subscriber" ]`.

Is there any way in the current Sysrepo implementation to achieve this?

I've done some digging and the only thing I found was `lys_is_key()` in libyang which maybe could be used for implementing such a function. Do you think it could? If so, I might try to implement it.

**Comment by michalvasko** [comment]
Hi,
yeah, you will have to implement this. I do not know C++ bindings specifics, but you should be able to use a function for each step. So, first you find the list schema node and then you simply return its first `key_size` children (keys are always first).

Regards,
Michal

**Comment by andrei-pavel** [comment]
Thank you for your answer.
It just so happens that I no longer have a need for this and so will not implement it right now.
