### ISSUE TITLE
Python language extensions callback crash

### ISSUE THREAD

**Issue by knoll01** [sysrepo/sysrepo#1506]
I am attempting to write a Python application to watch for module changes using sr.module_change_subscribe() very similar to the python_application_example.py and python_application_changes_example.py.

The difference is that I have created a new class (SrHandle) to manage all interaction with sysrepo.

I am able to run my app and it waits for a change to occur in the subscribed module. However, most often the app will crash (SIGSEGV) when attempting to execute the callback.

This crash does not occur with the python_application_example.py and python_application_changes_example.py applications.

I'm not fluent with SWIG, so this could be me misunderstanding the limitations of it.

```
import sysrepo as sr
import logging
import uuid
import time
logger = logging.getLogger('main')

def module_change_cb(sess, module_name, event, private_ctx):
    logger.info("========== CONFIG HAS CHANGED ==========")
    return sr.SR_ERR_OK

class SrHandle(object):
    def __init__(self):
        self.__module_name = 'my-module'

        self.__uuid = uuid.uuid4()
        try:
            self.__connection = sr.Connection(self.__uuid.get_hex())
        except Exception as e:
            logger.error('Unable to get connection to sysrepo %s', e)
        try:
            self.__session = sr.Session(self.__connection, sr.SR_DS_RUNNING)
        except Exception as e:
            logger.error('Unable to get session to sysrepo %s', e)
        try:
            self.__subscription = sr.Subscribe(self.__session)
        except Exception as e:
            logger.error("Unable to subscribed to sysrepo %s", e)

    def set_cb(self):
        self.__subscription.module_change_subscribe(self.__module_name, self.module_change_cb, None, 0,
                                                    sr.SR_SUBSCR_DEFAULT | sr.SR_SUBSCR_APPLY_ONLY)


def main():

    mod_change_sr_handle = SrHandle('RUNNING')

    try:
        while True:
            time.sleep(5)
    except KeyboardInterrupt:
        logger.info('main Exiting')


if __name__ == "__main__":
    main()
```

**Comment by smalls12** [comment]
Can you change the subscription from this

```
self.__subscription.module_change_subscribe(
    self.__module_name,
    self.module_change_cb,
    None,
    0,
    sr.SR_SUBSCR_DEFAULT | sr.SR_SUBSCR_APPLY_ONLY
    )
```

to this

```
self.__subscription.module_change_subscribe(
    self.__module_name,
    module_change_cb,
    None,
    0,
    sr.SR_SUBSCR_DEFAULT | sr.SR_SUBSCR_APPLY_ONLY
    )
```

**Comment by knoll01** [comment]
I tried the suggested change and got the same behavior (segmentation fault).

Further experimentation shows that if I replace 

    try:
        while True:
            time.sleep(5)
    except KeyboardInterrupt:
        logger.info('main Exiting')

with

sr.global_loop()

I don't get the crash. 

With time.sleep(), the crash is almost always occurring inside the sleep cycle. It seems to me that there are some missing protections between the sysrepo C-based functions and the Python interpreter.

I also tried threading.Event.wait() and the app still crashes with a segmentation fault.

**Comment by smalls12** [comment]
I haven't looked, but sr.global_loop() likely provides safe interaction with the global interface lock within python.

Is it acceptable for your use case to use that instead?

**Comment by knoll01** [comment]
sr.global_loop is simply a while/sleep loop in the C code, so there's no need to coordinate with the GIL.

I can use sr.global_loop if necessary. 

sr.global_loop blocks Python threads, so this will cause me to have to execute multiple processes (vs. threads) if I have one or more tasks to run while simultaneously waiting for callbacks. I haven't tried, but I think this will also prevent me from dispatching to a thread from inside a callback.

I did run into a case that caused a segmentation fault even while using sr.global_loop. Unfortunately, I didn't note the conditions, so I'll have to reproduce it.

**Comment by smalls12** [comment]
I also went and looked at sysrepo.i and yea just a loop itself.

Unfortunately swig isn't the most popular option when it comes to producing python bindings; doing my own research and the popular options.

While that loop isn't doing anything in particular, coordinating with the gil is very much happening somewhere under the covers since sysrepo is producing as python calls them "alien threads".

Alien threads on their own need to manually coordinate with the gil. If they don't, the common side effect is a set fault.

There have been some other issues raised recently as well on this.

**Comment by smalls12** [comment]
Another issue that was raised which seems similar https://github.com/sysrepo/sysrepo/issues/1493

**Comment by smalls12** [comment]
For reference, can you just post which versions of software you're using ?

**Comment by knoll01** [comment]
sysrepo 0.7.7, Python 2.7.15rc1, Ubuntu 18.04.2 LTS

**Comment by knoll01** [comment]
I noticed #1493, also. I don't think the suggested patch is applicable, though.

**Comment by smalls12** [comment]
I can only apply a minimal set of tools to assist when it comes to SWIG; my experience is with other tools.

Are you able to try this in python3 ?

Also, could you put ```import threading``` at the top as well ?

Some posts have hinted that this could help.

**Comment by knoll01** [comment]
It seems that treatment on the GIL is the culprit. As an experiment I patched the mod_change_subscribe callback wrapper in sysrepo/swig/python/sysrepo.i.

This seems to have stopped the segmentation fault. Patch below.

If this *is* the correct fix, it should be applied to all the callback wrappers in that source file.

*** sysrepo.i	2019-06-02 13:15:08.503050320 +0000
--- sysrepo.i.org	2019-06-02 13:53:36.327050320 +0000
***************
*** 68,75 ****
      int module_change_subscribe(sr_session_ctx_t *session, const char *module_name, sr_notif_event_t event, \
                                   PyObject *private_ctx) {
          PyObject *arglist;
-         PyGILState_STATE gstate;
-         gstate = PyGILState_Ensure();
  
          sysrepo::Session *sess = (sysrepo::Session *)new sysrepo::Session(session);
          std::shared_ptr<sysrepo::Session> *shared_sess = sess ? new std::shared_ptr<sysrepo::Session>(sess) : 0;
--- 68,73 ----
***************
*** 90,96 ****
              Py_DECREF(result);
              return ret;
          }
-         PyGILState_Release(gstate);
      }
  
      int subtree_change(sr_session_ctx_t *session, const char *xpath, sr_notif_event_t event,\
--- 88,93 ----

**Comment by knoll01** [comment]
BTW - import threading did not help... in fact, that's what put me onto this problem... 

My first attempts were single-threaded (basically modifications on the example scripts). 

I want to have a threaded implementation and, originally, I thought the Python threading was causing the problem.

**Comment by smalls12** [comment]
That seems in line with the gil management I have done myself.

Side note: Could we change that function to ```module_change``` instead of` ```module_change_subscribe```. At first I thought you were updating the subscribe functions,

You might also want to look at Saving/Restoring the gil on calls like get_item/get_items where the callback is also within the same context and shares the gil with the original caller.

Other than that, maybe someone from the dev team can comment further. They probably know more about SWIG.

Glad you are able to get something going though. :)

**Comment by knoll01** [comment]
module_change_subscribe is the proper name assigned by sysrepo. It is a wrapper for the module_change_subscribe() function in the C API, so I wouldn't change it.

I'll look at those other functions. I suspect you are correct that they need similar treatment with GIL.

Thanks for the help.

**Comment by smalls12** [comment]
The function you changed is currently called ```module_change_subscribe```.
However it is not wrapping the subscribe call for a module change, it is wrapping the callback for a module change.
The wrapping of the module change subscribe is https://github.com/sysrepo/sysrepo/blob/master/swig/python/sysrepo.i#L412
The other methods in the class for example are ```subtree_change```, ```rpc_cb```, ```dp_get_items```.
None of which perform a subscribe call.

I realize this is not part of your proposed solution, just trying to do some cleanup on the current source as it stand right now.

**Comment by knoll01** [comment]
Ah, yeah. I caught what you were suggesting just as I saw your reply here. Yeah, I'll change it to align to the rest.

**Comment by knoll01** [comment]
Here's my final patch. It seems to be working.

[sysrepo.i.diff.txt](https://github.com/sysrepo/sysrepo/files/3245185/sysrepo.i.diff.txt)

**Comment by smalls12** [comment]
Are you able to make the changes against this issue on the dev branch?
It looks like quite a bit has changed and the review process is a bit easier through the gui.

**Comment by knoll01** [comment]
As I've explored this more and deeper, I've found that there are significant changes to be made to make the Python extensions usable in a multi-threading environment.  I don't have the expertise to dive in that deep, so I've moved off on a different path.

I had to make more changes to get the callbacks to work and that's where I stopped. I will try to submit changes against the dev.

attached is the diff for those that want it before I submit to dev.

[sysrepo.i.diff.txt](https://github.com/sysrepo/sysrepo/files/3262018/sysrepo.i.diff.txt)

**Comment by maggie450** [comment]
The swig -python command line needs -threads to enable python multi-threading support.  The -threads option defines macros and smart classes for obtaining and releasing GIL.  With -threads swig automatically wraps C++ calls with release/obtain GIL.  Callback methods still need GIL support to be added manually in the swig interface file in class Wrap_cb.  Just include 
```
#if defined(SWIG_PYTHON_THREADS)
      SWIG_Python_Thread_Block safety;
#endif
```
at the beginning of each method.
Suggested patch attached
[sysrepo_python_threading.txt](https://github.com/sysrepo/sysrepo/files/3372579/sysrepo_python_threading.txt)

This fixes the callback crashes and also fixes an issue with sr.global_loop() locking threads.  Not sure if there is any performance overhead.

**Comment by knoll01** [comment]
I'll give this a try. 
Is the resulting code output effectively the same as my changes?

Also, to avoid confusion, i suggest that the callback functions be renamed (as I did in my diff) to XXXX_cb.

For example, the original sysrepo.i names the callback function as module_change_subscribe, but that is also the name of the function that configures the callback.

Configure the callback with...

`    void module_change_subscribe(const char *module_name, PyObject *callback, PyObject *private_ctx = nullptr, uint32_t priority = 0, sr_subscr_options_t opts = SUBSCR_DEFAULT)
`

and the actual callback function is wrapped in ...

`int module_change_subscribe(sr_session_ctx_t *session, const char *module_name, sr_notif_event_t event, PyObject *private_ctx)
` 
I suggest the callback wrapper be:

`int module_change_cb(sr_session_ctx_t *session, const char *module_name, sr_notif_event_t event, \
                                  PyObject *private_ctx)
`

**Comment by maggie450** [comment]
The use of the smart class SWIG_Python_Thread_Block is safer because there is no risk of forgetting the PyGILState_Release on one of the callback error exits.  The -threads option also adds code to release the GIL when entering C++ code and ensure on exit.

**Comment by michalvasko** [comment]
Hi,
thanks a lot, will be merged.

Regards,
Michal
