### ISSUE TITLE
Sysrepo does not accept identityref type leafs when subscribed application provides the string value

### ISSUE THREAD

**Issue by vhuertas** [sysrepo/sysrepo#1507]
### Things you may try first
(put "x" in "[]" if you already tried following)
* [] Did you check if this is a duplicate issue?
* [] Did you test it on the latest sysrepo devel branch?

### Description
When I try to provide from my C++ application the 'address-family' leaf value within this xpath (see below) in the ietf-routing module the sysrepo reports an error that may cause that the NETCONF client do not retrieve anything from the 'get' rpc :

/ietf-routing:routing-state/routing-instance[name='default-rt']/ribs/rib[name='ipv4-master']/address-family

### Steps to Reproduce
1. send a NETCONF edit config rpc like this on the ietf-routing (using Netopeer-cli)
edit-config --target running --config=/home/cuda1/route_prot.xml

The content of the xml file is:
```
<routing xmlns="urn:ietf:params:xml:ns:yang:ietf-routing">
    <routing-instance>
        <name>default-rt</name>
        <type>default-routing-instance</type>
        <routing-protocols>
            <routing-protocol>
                <type>direct</type>
                <name>direct1</name>
            </routing-protocol>
            <routing-protocol>
                <type>static</type>
                <name>static1</name>
            </routing-protocol>
        </routing-protocols>
        <ribs>
            <rib>
                <name>ipv4-master</name>
                <address-family>ipv4</address-family>
                <description>bla bla</description>
            </rib>
        </ribs>
    </routing-instance>
</routing>

```

2. using NETCONF cli send the request: 
get-config --source running --filter-xpath=/ietf-routing:routing.

The result is this:

```
DATA
<routing xmlns="urn:ietf:params:xml:ns:yang:ietf-routing">
  <routing-instance>
    <name>default-rt</name>
    <type>default-routing-instance</type>
    <routing-protocols>
      <routing-protocol>
        <type>direct</type>
        <name>direct1</name>
      </routing-protocol>
      <routing-protocol>
        <type>static</type>
        <name>static1</name>
      </routing-protocol>
    </routing-protocols>
    <ribs>
      <rib>
        <name>ipv4-master</name>
        <address-family>ipv4</address-family>
        <description>bla bla</description>
      </rib>
    </ribs>
  </routing-instance>
</routing>
```

3. Using Netopeer CLI issue the command:
get --filter-xpath=/ietf-routing:routing-state/*

The returned data is:
```
DATA
<routing-state xmlns="urn:ietf:params:xml:ns:yang:ietf-routing">
  <routing-instance>
    <name>default-rt</name>
    <type>default-routing-instance</type>
  </routing-instance>
</routing-state>
```

Although the ribs state data is provided from the C++ application, the identityref value for "address-family" provided has been the string "ietf-routing:ipv4" in one test and "ipv4" in other test just to check if the sysrepo reacts in a different way but it always complains about the value provided (see logs below).

**Expected behavior:**
 That the 'address-family' value is successfully provided

**Actual behavior:**
This error is reported:
```
[DBG] Received value from data provider for xpath '/ietf-routing:routing-state/routing-instance[name='default-rt']/ribs/rib[name='ipv4-master']/address-family'.
[DBG] Module ietf-routing already loaded
[ERR] Value doesn't conform to schema expected 12 instead of 18
[ERR] Value doesn't conform to schema node address-family
[ERR] Copy new value to string failed
[WRN] Failed to set operational data for xpath '/ietf-routing:routing-state/routing-instance[name='default-rt']/ribs/rib[name='ipv4-master']/address-family'.
```

### Versions
Please provide versions for software needed to reproduce the bug:
Sysrepo version: 0.7.7 (devel branch)
libyang version: 1.1.14
netopeer2-server: 0.7.11

I don't know why the provision of identityref type leafs are so problematic. It is a nighmare. I'm completely stuck in this point for days. Any help is really appreciated.
The only conclusion I can reach is that the tested sysrepo version (see above) has a bug.

Do you agree?

Thanks!

**Comment by michalvasko** [comment]
Hi,
can you please share just the code for creating the value you return and it fails with the error?

Regards,
Michal

**Comment by vhuertas** [comment]
Dear Michal,

I have found out what was happening. It was my mistake. When providing the value I did it with the SR__STRING_T instead of SR_IDENTITYREF_T.

Now the data is provided correctly.

I proceed to close the issue then.

Regards,
