### ISSUE TITLE
Starting a session MUST authenticate against /etc/passwd

### ISSUE THREAD

**Issue by YohanPipereau** [sysrepo/sysrepo#1508]
### Description / What I am trying to do

I am using sysrepo compiled with NACM support. I am developping a GNMI server on top of sysrepo. My gNMI server is working, I implemented Authentication with Username/password and Mutual TLS, now I would like to have authorization by leveraging the existing NACM implementation.

For Access Control, I need an identity based on the preivous authentication step:

* Identity for a User/Pass authentication is __username__
* Identity for a MUTUAL TLS authentication is __x509 common name__

### My problem

Because `sr_start_user_session` needs to authenticate against `/etc/passwd`, I can not pass the identity of a user which is not existing on the machine to benefit from NACM implementation.
Is there a way to skip this checkings against /etc/passwd ?

/etc/passwd is check here: https://github.com/sysrepo/sysrepo/blob/devel/src/cm_session_manager.c#L405

### Versions

Sysrepo version: devel & 0.7.7
libyang version: 1.1.21

### My code:

The last commit from the branch authorization is how I tested to authenticate a non existing UNIX user:

https://github.com/YohanPipereau/sysrepo-gnxi/tree/authorization

Would a Pull Request to skip this authentication be welcome ?

Thanks!

**Comment by rkrejci** [comment]
I'm afraid that authentication is strictly connected with the local users. NACM is actually kind of additional authentication mechanism in sysrepo (and it is not included in sysrepo2), the basic authentication method is a classic user/group file access mechanism with the schema-based granularity.

We're open to discuss how to improve the authentication/authorisation mechanism, but I'm not sure that just skipping it solves the problem.

**Comment by YohanPipereau** [comment]
From my understanding, NACM is rather an __authorization__ than an authentication mechanism.

You have two authorization mechanism implemented in sysrepo as you said:

* __NACM__ which is kind of RBAC (Role Based Access Control)
* __UNIX file permissions__ which is DAC (Discretionary Access Control)

I think you did right for sysrepo2, NACM should not be part of the datastore for security reasons. Maybe it should be a lightweight application intercepting calls made to sysrepo. 

For me authentication should be done at interface level (netopeer2) not at datastore level. It will provide you with an identity (Common Name for Mutual TLS or username for User/pass authentication).
If you want to have other interfaces than NETCONF supported (RESTCONF and gNMI), you must allow sr_session_start_user() to take an identity which is not a registered UNIX user or maybe have another function for these interfaces like sr_session_start_identity().

A few questions about sysrepo2:

* Is sysrepo2 a separate project ?
* Is there a way to get access to sysrepo2 __API__ yet? 
* Is sysrepo2 API backward compatible with sysrepo and is it going to have C++ bindings ?
* Will sysrepo2 be NMDA (RFC 8342) compatible ?

**Comment by rkrejci** [comment]
>A few questions about sysrepo2:
>
>Is sysrepo2 a separate project ?

no, despite it is currently only in a [forked sysrepo repository](https://github.com/michalvasko/sysrepo/tree/sysrepo2), we plan to merge it here (into a standalone branch) soon (July). The current sysrepo will be still supported for some time (at least a year after official moving to sysrepo2).

>Is there a way to get access to sysrepo2 API yet?

check [this repo](https://github.com/michalvasko/sysrepo/tree/sysrepo2), but not sure how far is Michal currently with documentation.

>Is sysrepo2 API backward compatible with sysrepo and is it going to have C++ bindings ?

not fully, but it is supposed to be very similar, and yes, but we didn't even started to work on it.

>Will sysrepo2 be NMDA (RFC 8342) compatible ?

yes

**Comment by michalvasko** [comment]
Hi,
@YohanPipereau I believe your use-case should work for the new *sysrepo* in its current state, so please wait until it is released and let us know if it does work. Thanks.

Regards,
Michal

**Comment by YohanPipereau** [comment]
Hi @michalvasko ,

Thanks for the update, I can't wait.
Keep up the good work with version 2.

Yohan
