### ISSUE TITLE
can i write database without  trigger callback function?

### ISSUE THREAD

**Issue by zyboy2000** [sysrepo/sysrepo#1509]
### Things you may try first
(put "x" in "[]" if you already tried following)
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description
i want write database without tirgger callback function.  i has a CLI interface, expect  set is successful, then write the database

**Comment by rkrejci** [comment]
I'm not sure I understand the use case correctly, but if you want just to store the configuration data in the sysrepo, you ca use `sr_set_item()` function (or others - see http://www.sysrepo.org/static/doc/html/group__cl.html) to manipulate with the datastore context. This is actually what [Netopeer2](https://github.com/CESNET/Netopeer2) does when applying NETCONF requests.

**Comment by michalvasko** [comment]
Hi,
you cannot change *sysrepo* data without triggering the corresponding callbacks, such functionality would violate its basic principles.

Regards,
Michal
