### ISSUE TITLE
One question about the sysrepo callback

### ISSUE THREAD

**Issue by darcyllingyan** [sysrepo/sysrepo#1511]
Hi,
Now I want to use the ```SR_EV_VERIFY``` in my subscriber to verify whether the payload data is right before commit the data to database.
For example, in the ```module_change_cb```, when getting the payload data from the request, seems the ```sr_get_items``` and ```sr_get_subtree``` both can implement it, if I want to do additional check, whether the ```sr_get_items```  or ```sr_get_subtree``` is better to be passed as the parameter?
```
printf("\n\n ========== Notification  %s =============================================", ev_to_str(event));
    if (SR_EV_VERIFY == event) {
        rc = sr_get_items(session, change_path, &values,&count);
        flag=additional_check(values); // pass the parameters and do additional check
        //rc = sr_get_subtree(session, change_path, SR_GET_SUBTREE_DEFAULT, &subtree);
       /// flag=additional_check(subtree); // pass the parameters and do additional check
    }
```

Thanks
Darcy

**Comment by rkrejci** [comment]
Hi, I believe that the changed data should be provided as a parameter to your callback. And, as in case of `sr_get_*()`, there are 2 variants of the callback/subscription according to what format of the data you want to receive (` sr_event_notif_subscribe` and ` sr_event_notif_subscribe_tree`). It is just up to you which format you prefer.

One note to your `additional_check()` - in case of passing `sr_item_value`, you should probably pass also the count.

**Comment by darcyllingyan** [comment]
Hi @rkrejci ,
Thanks very much for the response.
You mean both the ```sr_get_items``` and ```sr_get_subtree``` can be used to get the payload data for the edit-config request, right?
After print the ```values``` got in the ```sr_get_items``` and ```sr_get_subtree```, only the format is different.

Thanks
Darcy

**Comment by rkrejci** [comment]
No, with `sr_get_*()` you are able to get data from the datastore. The data connected with the `SR_EV_VERIFY` event should be available as `values` parameters of `sr_event_notif_cb` or as `trees` parameters of `sr_event_notif_tree_cb`. Or where do you have the code related to the `SR_EV_VERIFY`?

**Comment by darcyllingyan** [comment]
Hi @rkrejci ,
Thanks very much for the reponse, but I'm sorry I still don't understand. You mean the sr_get_* will get data from datastore but from the payload data in the edit-config  request?

Below is my code:
1. I modified the ```sysrepo/examples/application_changes_example.c``` as below and add the ```SR_EV_VERIFY``` in the ```module_change_cb```:

Below is the process:
    1）In the main() function, it calls the sr_module_change_subscribe, in its parameters, the module_change_cb is passed.
```
    rc = sr_module_change_subscribe(session, argv[i], module_change_cb, NULL,
            0, SR_SUBSCR_DEFAULT, &subscription);
```
    2) In the module_change_cb， add the ```additional_check()``` in the ```SR_EV_VERIFY``` event, the parameters for the function are got from the sr_get_*, if the ```addition_check()``` returns non-zero value, just return ```SR_ERR_VALIDATION_FAILED``` and when do the edit-config, the configuration data in the request won't be written to the database.

```
static int
module_change_cb(sr_session_ctx_t *session, const char *module_name, sr_notif_event_t event, void *private_ctx)
{
    sr_change_iter_t *it = NULL;
    int rc = SR_ERR_OK;
    sr_change_oper_t oper;

    char change_path[XPATH_MAX_LEN] = {0,};
    snprintf(change_path, XPATH_MAX_LEN, "/%s:*", module_name);
    sr_val_t *values = NULL;
    size_t count = 0;

    if (SR_EV_VERIFY == event) {
        rc = sr_get_items(session, change_path, &values,&count);
       if (additional_check(values, count) != 0){
            return SR_ERR_VALIDATION_FAILED;
          }
    }

    printf("\n\n ========== CHANGES: =============================================\n\n");

cleanup:
    sr_free_change_iter(it);

    return SR_ERR_OK;
}

```
3. With the above function,
If users want to modify the running datastore, need to use  the application_change_example to subscribe, every time users want to do the edit-config, the above ```module_change_cb``` will be called.

Thanks
Darcy

**Comment by rkrejci** [comment]
According to the description of `SR_EV_VERIFY`, it occurs just BEFORE the changes are committed to the datastore, so with the `sr_get_items` used for your `additional_check()`, you are getting configuration data BEFORE the edit-config request. So, if you want to validate changes by the `additional_check()`, you actually just validate the current running.

Within this subscription, you will probably need to use `sr_get_changes_iter()` and `sr_get_changes_next()`.

Anyway, just trying to run your code (or the original example) will be for sure more clear than describing it here ;) Instead of `additional_check()`, just try to print the values and you will see if you are printing edit-config or the original running configuration of the subscribed module.

**Comment by darcyllingyan** [comment]
Hi @rkrejci ,
Thanks very much, I know what your mean now.
1. Initially the database is empty, so the ```sr_get_*```'s values are the same with edit-config request payload data, so I thought the ```sr_get_*``` could meet my request, after print the values again, the ```sr_get_*``` will get data per module, including the data from original datastore and edit-config payload request data, it couldn't meet my request, I just need to transfer the edit-config payload data to ```additional_check()```.

2. The ```sr_get_changes_iter() ```and ```sr_get_changes_next()``` also don't meet my request as it only get the changed data but the payload data in the edit-config request.

3. Do you have any suggestions about how to get the payload data in the edit-config request?

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
from the *sysrepo* point-of-view, there are no "payload data", there are only the changes. I am planning to allow to add some custom callbacks to *netopeer2* so that even the standard RPCs can be handled in some custom way, so that may be the solution for you, but it is just a vague idea for now.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
You mean the current sysrepo/netopeer doesn't have the callback to get the ```payload data```, in the next release of netopeer2, you will add some custom callbacks to support it, right?

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
yes, that is the plan. But it may be not available right after the release.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
Thanks for the response, I got it.

Thanks
Darcy
