### ISSUE TITLE
get items subscribe routine cannot be called when the item is added by augment augment

### ISSUE THREAD

**Issue by TiejunShuang** [sysrepo/sysrepo#1512]
Hi,
There is a get item callback cannot be called issue, reproduce step as follow:

**1. install yang which in the augment.tar.gz**

  There are two augment items in openconfig-if-ip.yang, 

_augment 1_ 
```
  augment "/oc-if:interfaces/oc-if:interface/oc-if:subinterfaces/" +
    "oc-if:subinterface" {
    description
      "IPv4 address family configuration for
      interfaces";

    uses ipv4-top;
  }
```

 _augment 2_
```
// VRRP for IPv4 interfaces
  augment "/oc-if:interfaces/oc-if:interface/oc-if:subinterfaces/" +
    "oc-if:subinterface/oc-ip:ipv4/oc-ip:addresses/oc-ip:address" {

    description
      "Additional IP addr family configuration for
      interfaces";

    uses ip-vrrp-top;
  }
```
**2. subscribe the get and the change**
```
    /* subscribe for providing operational data */
    rc = sr_dp_get_items_subscribe(session, "/openconfig-interfaces:interfaces/interface/subinterfaces/subinterface/openconfig-if-ip:ipv4/openconfig-if-ip:addresses/openconfig-if-ip:address/openconfig-if-ip:state", system_state_provider_cb, NULL,
            SR_SUBSCR_DEFAULT, &subscription);
    if (SR_ERR_OK != rc) {
        fprintf(stderr, "%s %d: Error by sr_dp_get_items_subscribe: %s\n", __func__,__LINE__,sr_strerror(rc));
        goto cleanup;
    }

    rc = sr_subtree_change_subscribe(session, "/openconfig-interfaces:interfaces/interface/subinterfaces/subinterface/openconfig-if-ip:ipv4/openconfig-if-ip:addresses/openconfig-if-ip:address/openconfig-if-ip:config", subtree_change_cb, NULL,
            0, SR_SUBSCR_DEFAULT, &subscription);
    if (SR_ERR_OK != rc) {
        fprintf(stderr, "Error by sr_subtree_change_subscribe: %s\n", sr_strerror(rc));
        goto cleanup;
    }
```
**3. send set item from controller**
  We can see subtree change callback function be called.

**4. send get tiem from controller**
  The get callback function **cannot** be called.

**5. remove follow _augment 2_ from openconfig-if-ip.yang**
 Remove follow lines:
```
  // VRRP for IPv4 interfaces
  augment "/oc-if:interfaces/oc-if:interface/oc-if:subinterfaces/" +
    "oc-if:subinterface/oc-ip:ipv4/oc-ip:addresses/oc-ip:address" {

    description
      "Additional IP addr family configuration for
      interfaces";

    uses ip-vrrp-top;
  }
```
**6. send get tiem from controller again**
  The get callback function **cann** be called.

**question:**

Is the reason of get item callback cannot be called that augment 2 add container to another augment container? 

[augment.tar.gz](https://github.com/sysrepo/sysrepo/files/3271226/augment.tar.gz)

Thanks!
Tiejun

**Comment by michalvasko** [comment]
Hi,
can you maybe add some details? I am interested only in the non-working scenario, I need to reproduce it. Do you have some data in *sysrepo*? What do you mean exactly by "callback function cannot be called"?

Regards,
Michal

**Comment by TiejunShuang** [comment]
Hi Michal,
Thanks for reply.
callback function cannot be called means that I subscribe a get callback by
 "
rc = sr_dp_get_items_subscribe(session, "/openconfig-interfaces:interfaces/interface/subinterfaces/subinterface/openconfig-if-ip:ipv4/openconfig-if-ip:addresses/openconfig-if-ip:address/openconfig-if-ip:state", system_state_provider_cb, NULL,
            SR_SUBSCR_DEFAULT, &subscription);"

in callback function  system_state_provider_cb() only print a message "get info".   
after send get rpc from controller , I didn't see the message "get info".

The log is:
 Jun  6 16:09:12 accelink daemon.debug sysrepod[1320]: [DBG] (rp_dt_xpath_requests_state_data:769) **0** subtrees of state data will be attempted to load in order to resolve /openconfig-interfaces:interfaces/interface/subinterfaces/subinterface/openconfig-if-ip:ipv4/addresses/a
Jun  6 16:09:12 accelink daemon.debug sysrepod[1320]: [DBG] (rp_dt_prepare_data:1231) No state state data provider is asked for data because of xpath /openconfig-interfaces:interfaces/interface/subinterfaces/subinterface/openconfig-if-ip:ipv4/addresses/address/state//.

in the openconfig-interfaces.persist file:
    <subscription>
      <type>dp-get-items</type>
      <destination-address>/tmp/sysrepo-subscriptions/openconfig-interfaces/1260.jQXTYU.sock</destination-address>
      <destination-id>1468434245</destination-id>
      <enable-running/>
      <xpath>/openconfig-interfaces:interfaces/interface/subinterfaces/subinterface/openconfig-if-ip:ipv4/openconfig-if-ip:addresses/openconfig-if-ip:address/openconfig-if-ip:state</xpath>
    </subscription>

I try to find the reason of  the get callback cannot be called, because it works well before. 
I found after remove follow augment sentences from openconfig-if-ip.yang, the get callback can be called -- I can see "get info" message .
  **// VRRP for IPv4 interfaces
  augment "/oc-if:interfaces/oc-if:interface/oc-if:subinterfaces/" +
    "oc-if:subinterface/oc-ip:ipv4/oc-ip:addresses/oc-ip:address" {

    description
      "Additional IP addr family configuration for
      interfaces";

    uses ip-vrrp-top;
  }**

This augment add item to "/oc-if:interfaces/oc-if:interface/oc-if:subinterfaces/" +
    "oc-if:subinterface/oc-ip:ipv4/oc-ip:addresses/oc-ip:address" and I subscribe the same xpath.

BTW:
 The set callback works well for the xpath "/openconfig-interfaces:interfaces/interface/subinterfaces/subinterface/openconfig-if-ip:ipv4/openconfig-if-ip:addresses/openconfig-if-ip:address/openconfig-if-ip:config" all the time.

Regards,
Tiejun

**Comment by michalvasko** [comment]
Hi,
the state data subtrees were not collected properly, they should be now, please try again.

Regards,
Michal

**Comment by TiejunShuang** [comment]
Hi Michal，
I have test the change, the issue be fixed. thanks.

Regards,
Tiejun
