### ISSUE TITLE
Question: how to provide a list with no keys

### ISSUE THREAD

**Issue by vhuertas** [sysrepo/sysrepo#1513]
Hi,
Imagine that I have implemented the ietf-routing module in a C++ application and from netopeer-cli a get command is issued to see all the routing-state data structure:

get --filter-xpath=/ietf-routing:routing-state/*

When it is time to provide the data in the xpath: ietf-routing:routing-state/routing-instance[name='default-rt']/ribs/rib[name='ipv4-master']/routes/route

I have tried to provide this key-less list using sr_val_set_xpath() and sr_val_set_str_data() and providing leaf by leaf the elements of a single route but the result obtained is not what it is expected:

```
<routing-state xmlns="urn:ietf:params:xml:ns:yang:ietf-routing">
  <routing-instance>
    <name>default-rt</name>
    <type>default-routing-instance</type>
    <ribs>
      <rib>
        <name>ipv4-master</name>
        <routes>
          <route>
            <route-preference>0</route-preference>
          </route>
          <route>
            <source-protocol>static</source-protocol>
          </route>
          <route>
            <destination-prefix xmlns="urn:ietf:params:xml:ns:yang:ietf-ipv4-unicast-routing">1.1.1.0/24</destination-prefix>
          </route>
        </routes>
      </rib>
    </ribs>
  </routing-instance>
</routing-state>

```
Every single parameter is taken as a separate route.
Is it possible with sysrepo to provide such route list in order to make it look like this?

```
<routing-state xmlns="urn:ietf:params:xml:ns:yang:ietf-routing">
  <routing-instance>
    <name>default-rt</name>
    <type>default-routing-instance</type>
    <ribs>
      <rib>
        <name>ipv4-master</name>
        <routes>
          <route>
            <route-preference>0</route-preference>
            <source-protocol>static</source-protocol>
            <destination-prefix xmlns="urn:ietf:params:xml:ns:yang:ietf-ipv4-unicast-routing">1.1.1.0/24</destination-prefix>
          </route>
        </routes>
      </rib>
    </ribs>
  </routing-instance>
</routing-state>
```
Thanks a lot for your attention,

**Comment by michalvasko** [comment]
Hi,
I am sorry but to my knowledge key-less state lists are not supported by the current *sysrepo*, you will have to wait for the new one.

Regards,
Michal

**Comment by vhuertas** [comment]
Ok Michal,

Thank you for your answer. I will wait for the next generation of _sysrepo_. It will be _sysrepo2_? Will this  be backwards compatible with the C++ library of _sysrepo_?

Regards,

**Comment by michalvasko** [comment]
Hi,
the branch is named `sysrepo2` but the project name will remain *sysrepo*. It will most likely will not be fully backwards compatible, some minor adjustments will have to be made.

Regards,
Michal

**Comment by vhuertas** [comment]
OK MIchal,
I guess that the sysrepo2 branch is still under development and I will wait till it is more consolidated. 
Will the sysrepo issues solution be integrated into the sysrepo2 branch?

Do you agree in closing this issue then? It is up to you.

Thanks again for your quick answer.

**Comment by iGovindY** [comment]
Hi @michalvasko 

are key-less state lists supported now with latest 1.4.x sysrepo?

we tried `sr_set_item_str` API call for each leaf under a key-less list 
than once sr_apply_changes for commiting changes.

But this created entries for each leaf of key-less list.

Thanks
Govind

**Comment by michalvasko** [comment]
Yes, they should be supported in all *sysrepo* versions 1.x but you must create the instances using the right xpath. Look in #2192.
