### ISSUE TITLE
One question about the mandatory usage

### ISSUE THREAD

**Issue by darcyllingyan** [sysrepo/sysrepo#1514]
Hi,
I have a question about the mandatory usage, use below example to show it.
1. The YANG files:
```
# cat leaflist-element.yang 
module leaflist-element {
        yang-version 1.1;
        namespace "http://test/leaflist/element";
        prefix leaflist-element;

        container aa {
                leaf ip-type {
                     type string;
                }
                leaf-list ipv4-remote-end-points-rec {
                        min-elements 1;
                        max-elements 10;
                        type string;
                }            
        }

}
```
```
# cat test-list-key.yang
module test-list-key {
        namespace "http://test/list/key";
        prefix list-key;
        container cc {
                list multikey {
                        key "a b";
                        leaf a {
                                type string;
                        }
                        leaf b {
                                type string;
                        }
                }
        }
}

```
2. The XML file:
```
# cat list-key.xml
<cc xmlns="http://test/list/key">
        <multikey>
                <a>1</a>
                <b>2</b>
        </multikey>
</cc>

#netconf-console --port=830 --edit-config list-key.xml
<?xml version="1.0"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <ok/>
</rpc-reply>

#netconf-console  --port=830  --get-config
<?xml version="1.0"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <cc xmlns="http://test/list/key">
      <multikey>
        <a>1</a>
        <b>2</b>
      </multikey>
    </cc>
  </data>
</rpc-reply>
```

3. My question is, when ```edit-config``` the ```list-key.xml```, whether the error-message ```missing mandatory container /aa:``` should be reported.
Now the sysrepo wont't reported the error and response OK, I think if the ```leaf-list ipv4-remote-end-points-rec``` has a ```when check and the when check is false```, the error-message won't be reported, if there isn't any ```when/if-feature```, I think the error-message should be reported.
Not sure whether my understanding is right.

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
so, you are simply talking about having a module with empty data being invalid? That is a bit tricky use-case (the new *sysrepo* does not even allow installing such a module and I have not figured out a solution for this yet). As long as the module is not being changed, it will not be validated (having a `when` causes it to have dependencies) so that is the reason it works. Anyway, the current behavior will stay for this version of *sysrepo* and I will figure out something proper for the new one.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
Thanks for the response.

> so, you are simply talking about having a module with empty data being invalid? 
Yes, I think the mandatory module with empty should be invalid.

> the new sysrepo does not even allow installing such a module and I have not figured out a solution for this yet
Seems the confD works like this: the mandatory module isn't allowed to install.

> As long as the module is not being changed, it will not be validated
You mean if the mandatory module isn't exist in the database, the initil writing should response OK and won't do any validation?  No matter it has ```when``` or not.
If the database has mandatory module and ```when``` check, if the existed module is being changed, the validation will be triggered, not sure whether my understanding is right.

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
regarding data, every module data is stored separately and loaded/validated only when necessary. So, you are able to install a module with empty data even if it is not valid, that is the behavior of the current *sysrepo*. And as long as you modify only other modules, everything will work fine. However, as soon as the data of the module with mandatory top-level elements is needed, you will suddenly get the error during validation. Now I hope you understand why.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi MIchal,
Thanks very much for the detailed response, I understand now.

Thanks
Darcy
