### ISSUE TITLE
Please add a dependency on bash

### ISSUE THREAD

**Issue by fxdupont** [sysrepo/sysrepo#1515]
bash should be added in the dependency list because it is used by make install (occurs in CMakeLists.txt).

Note that some systems, e.g. my FreeBSD 12.0 VM, have no bash by default. Of course installing it was enough to get `make install` to work well.

I leave the choice to you between only updating the doc or adding a check in cmake config file.

**Comment by michalvasko** [comment]
Hi,
done.

Regards,
Michal
