### ISSUE TITLE
[Query] : Are LYB files cross platform compatible?

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1518]
Hi,

Are the LYB files installed on x86_64 device directly portable to other devices like 32 bit x86 or 32bit arm devices?

If YES is there any tool which can convert XML configuration to LYB format without importing locally?

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
I would hope they are, using the current *libyang* and you can let us know, if not. You can use `yanglint` to convert the data format (`data -t config -o output.lyb -f xml input.xml`).

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thank you for the information.

By basic tests LYB files are working across platforms. Will let you know if we face any issues.

We are using a bit old version of libyang and that doesn't support `-f lyb` so couldn't test this right now.

Is there any way we can start sysrepo with data and yang files preinstalled in /etc/sysrepo(in rootfs) and without internal data file.
Our goal is to reduce the time taking for yang installations using `sysrepoctl` and default configurations using `sysrepocfg`

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
the internal sysrepo data file is necessary but you can have models preinstalled. Just install them once and if you then backup the repository and replace an empty repository of a new sysrepo installation with the backed up one, it should work (strictly speaking, only the internal data file `repository/data/internal` and YANG modules `repository/yang` need to be backed up). To keep startup configuration, also back up all `repository/data/*.startup` files.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Is there a way to backup enabled features? If I backed up *.persist files we are observing some errors.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
right, because the subscriptions are stored in those files, as well. However, *sysrepo* should handle non-existing subscriptions that are stored in these files without problems, so if those are the only errors you see, I would not worry about it.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

We are observing below errors and I thought these are related to persist files correct me if I am wrong.

Sysrepo
```
[ERR] Module <module1> not found in provided context
[ERR] Failed to apply persist data for module nxpsbr-syslog
[ERR] Failed to apply persist data
[ERR] Get module failed for <module2>
``
netopeer2-server
``
Error by processing of the get-schema request (session id=214940935): Requested schema model is not known.
Error by processing of the request.
np2srv_sr_get_schema failed (sysrepo: Requested schema model is not known).`
```
The `<modules>` mentioned doesnt containe any data containing nodes or features. But why these are coming as errors.

**Comment by michalvasko** [comment]
Hi,
then you are either doing something wrong when restoring a repository backup or it really cannot be performed so simply (but I see no reason why it should not). I cannot think of a legit reason why a module whose information is stored in the persist files would suddenly fail to be found.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

As you said earlier to backup only `*startup` files I have backed up only startup files and yang directory to backup.

For maintaining features persistently tried to back up `*persist` files too.

In both cases we observed above mentioned errors.

**Comment by michalvasko** [comment]
Hi,
I have also specifically mentioned `repository/data/internal`, did you back up that, too?

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Yes backed up internal folder in both cases.

**Comment by michalvasko** [comment]
Hi,
then I don't know what the problem could be. But this is not an official feature and I would much rather focus on finishing the new *sysrepo* so I cannot help you it seems, sorry.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

After some debugging came to know that backed up repo not working properly if there are any `deviations` for other modules.

Starting running data subscriptions showing above mentioned errors. And it looks like dm context is some how corrupting due to this.

If I backed up repo without any deviation modules everything looks fine.

Could you suggest in which area I can look for possible corruption?

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
I cannot really think of a reason why `deviations` should cause such problems so I am sorry, I have no advice to give you.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

The scenario as below. 
```
mod a {
  container ac {
    list acl {
    }
  }
}
mod dev {
  import a {prefix a;}
  deviation a:ac/a:acl {
    deviate add {
      max-elements 2;
    }
  }
}
mod b {
  import a {prefix a;}
  augment /a:ac/a:acl {
    container bc {
      list bcl {
      }
    }
  }
}
```

When there are `deviation` and `augment` for same node in different modules then there is a possible corruption happening in `dm_ctx` or `libyang context` (AFAIK both are same internally please correct me)

If I imported `mod b` to `mod dev` then corruption not happening.

As you said you are busy with new sysrepo implementation, Could you please help me with some pointers to look in code for further debugging,

Thanks & Regards,
Sriram.K
