### ISSUE TITLE
Adding floating point status values (DECIMAL64) to sysrepo from Python

### ISSUE THREAD

**Issue by haxgit** [sysrepo/sysrepo#1519]
### Description
I have some floating point status values I wish to add to the sysrepo database.

This requires my own private YANG model, but I will also need to populate
floating point values to standard YANG models.

I am using Python 2 to populate the sysrepo database.

I have tried using the Python float value type and the sysrepo DECIMAL64 value type.

A partial workaround is to treat the floating point values as strings in my own private YANG model.

However, this is not ideal, and will not work for standard YANG models that use, for example, the DECIMAL64 YANG type.

**Actual behavior:**
With a Python float value type and the sysrepo DECIMAL64 value type,
I get a NotImplementedError exception from sysrepo.py:
Wrong number or type of arguments for overloaded function "Val_set".

Some C/C++ prototypes are listed for sysrepo::Val::set(),
namely covering char const *, bool, double, int64_t.

### Versions
$ sysrepod -v
sysrepod - sysrepo daemon, version 0.7.7
$ yanglint -v
yanglint 1.1.16

**Comment by haxgit** [comment]
I have since discovered it was a coding error on my part.

The issue was that sysrepo::Val::set() and the corresponding Python binding use a variable number of arguments. In the DECIMAL64 case, the value type argument sr_type_t is not used.

However, could the API design be improved so that the number of arguments is fixed? This would make it easier to use and less error prone.

**Comment by michalvasko** [comment]
Hi,
we would prefer not to change the current *sysrepo* API, so it will stay the way it is. We will try to improve it for the new *sysrepo*.

Regards,
Michal
