### ISSUE TITLE
YANG date type without time

### ISSUE THREAD

**Issue by haxgit** [sysrepo/sysrepo#1523]
### Description
Is there any standard YANG date type that can be used without specifying a time?

I know there is a date-and-time type in the ietf-yang-types YANG module, but it
does not appear this can be used with just a date.

For this date-and-time type, is the only workaround to give a dummy time
for every date, e.g. HHMMSS=000000 ?

I know I can just store the date as a string type, but this would not have
the in-built validation.

For info, note the operation of the Linux date command, 
which can limit the precision:

linux$ date -Iseconds
2019-06-18T13:49:26+01:00
linux$ date -Idate
2019-06-18

**Comment by michalvasko** [comment]
Hi,
I am afraid there is no simple solution. Best you can do is to define a custom type, create your own user type plugin, and reuse the function from the in-build user type plugin for the value validation.

Regards,
Michal
