### ISSUE TITLE
RPC subscription not work with x-path /ietf-netconf:copy-config

### ISSUE THREAD

**Issue by molyland** [sysrepo/sysrepo#1529]
I implemented two rpc subscription, 

sr_subscription_ctx_t *subscr = NULL;

// first
sr_rpc_subscribe(session, "/my-module:exec-cmd", RpcCallback, this, SR_SUBSCR_DEFAULT, &subscr);

// second
sr_rpc_subscribe(session, "/ietf-netconf:copy-config", RpcCallback, this, SR_SUBSCR_DEFAULT, &subscr);

I test with two xml by netopeer2-cli:

// first
\<exec-cmd xmlns="http://example.com/ns/yang/my-module"\>
    \<commandType>test</commandType\>
\</exec-cmd\>

user-rpc --content /home/user/test_rpc_call_1.xml

// second
\<copy-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"\>
   \<target\>
        \<startup/\>
    \</target\>
    \<source\>
        \<running/\>
    \</source\>
\</copy-config\>

user-rpc --content /home/user/test_rpc_call_2.xml

In the first case I see the log of callback (RpcCallback), in second case callback not called correctly

**Comment by michalvasko** [comment]
Hi,
all the supported `ietf-netconf` RPCs are handled directly by *netopeer2-server*, they are not sent to *sysrepo*. Even if they were, you cannot have 2 subscriptions to a single RPC, so your subscription would fail.

Regards,
Michal

**Comment by michalvasko** [comment]
Supported in the new *sysrepo*.
