### ISSUE TITLE
Segmentation fault in sr_copy_config

### ISSUE THREAD

**Issue by gitter-runner** [sysrepo/sysrepo#1531]
Hi,

sr_copy_config() causes segfault in the application when the client is unable to send message to the daemon.

The problematic part:

```
    /* send the request and receive the response */
    rc = cl_request_process(session, msg_req, &msg_resp, NULL, SR__OPERATION__COPY_CONFIG);
    copy_config_resp = msg_resp->response->copy_config_resp;
```

When cl_request_process is unable to send message msg_resp remains NULL and null pointer dereference will happen at the second line.

According to logs message sending failed because the connection was closed by sysrepod:

```
sysrepod[2662]: [ERR] Unable to find session context for session id=1423311428 (conn=0x372658).
sysrepod[2662]: [WRN] Error by processing of the message: Sysrepo-internal error
sysrepod[2662]: [ERR] Error by processing of the message.
sysrepod[2662]: [WRN] Error by processing of the input buffer of fd=38, closing the connection.
```

Do you have any idea what can cause similar issue?

Sysrepo version: 0.7.7

Regards

**Comment by michalvasko** [comment]
Hi,
I don't know what can cause *sysrepod* not to find a session context, it seems to be quite a serious error, though. Unless you have some other details, I do not think I can help much.

Regards,
Michal
