### ISSUE TITLE
sr_realloc_values doesn't support shrinking value array

### ISSUE THREAD

**Issue by igortern** [sysrepo/sysrepo#1532]
Hi,

It is useful for error handling to be able to not only extend value array by sr_realloc_values, but also shrink it.
sr_realloc_values() function looks already implemented with both extending and shrinking in mind. However, there is a bug that prevents using this function for shrinking.
the following line (values.c:205) is unconditional. It should be under (if new_value_cnt > old_value_cnt)

    /* zero the new memory */
    memset(values + old_value_cnt, 0, (new_value_cnt - old_value_cnt) * sizeof *values);

Regards,
Igor

**Comment by michalvasko** [comment]
Hi Igor,
I committed the change you mentioned, thanks.

Regards,
Michal

**Comment by igortern** [comment]
Thanks Michal
