### ISSUE TITLE
Always call module_change_cb when enabling a module, even when there are no values to copy

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#1534]
Would it be possible to always call the user's `module_change_cb` when registered with `SR_SUBSCR_EV_ENABLED` even if there are no data to apply (an empty data store), please?

Here's my use case -- we're launching our application code with systemd, and we're notifying the init manager about the service's startup progress. Upon boot, a HW watchdog gets started, and unless all services report "hey, I'm up and running" within a timeout, the whole system gets shot into the head and rebooted (perhaps to a previous system image). And to make sure that everything works, I'm marking my application code as "up and running" only after the initial copy (`startup` -> `running`) has happened, i.e., once the first call to `module_change_cb` with `SR_EV_ENABLED` is just about to return.

This works well as long as there are any data in the `startup` DS. If the DS doesn't contain anything, then my app won't mark itself as "100% up". I could hack around this with a default leaf I suppose, but I would prefer to receive a dummy "no-changes" event instead.

**Comment by michalvasko** [comment]
Hi,
I understand your use-case and it seems useful. However, it is a small change of the behavior so I would prefer to add it only to the new sysrepo (whose release will be very soon), the old sysrepo will keep the current behavior.

Regards,
Michal

**Comment by michalvasko** [comment]
Supported now.
