### ISSUE TITLE
does sysrepo suppport path in nacm rule

### ISSUE THREAD

**Issue by GuoyouZhang** [sysrepo/sysrepo#1535]
looks like sysrepo doenst support path in nacm, following are the test i did:

cat ietf-system.xml (the web cannot show my xml in read mode, but if you modify it you will see the xml)
```xml
<nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
  <rule-list>
    <name>permit-ietf-system</name>
    <group>*</group>
    <rule>
      <name>permit-read-current-datetime</name>
      <path xmlns:sys="urn:ietf:params:xml:ns:yang:ietf-system">/sys:system-state/sys:clock/sys:current-datetime</path>
      <access-operations>read</access-operations>
      <action>permit</action>
      <comment>
        Permit reading the current datetime for all users.
      </comment>
    </rule>
  </rule-list>
</nacm>
```
```
root@eguoyzh_A:/opt/xf/yang/nacm# sysrepocfg --import=ietf-system.xml ietf-netconf-acm
[ERR] Unable to parse the input data: Invalid value "/sys:system-state/sys:clock/sys:current-datetime" in "path" element. (/ietf-netconf-acm:nacm/rule-list[name='permit-ietf-system']/rule[name='permit-read-current-datetime']/path)
Errors were encountered during importing. Cancelling the operation.
```
could you share any example with path in nacm rule?   Thanks!

**Comment by michalvasko** [comment]
Hi,
I am not sure what `ietf-netconf-acm` revision are you using but there is a [different one](https://github.com/sysrepo/sysrepo/blob/master/yang/ietf-netconf-acm%402018-02-14.yang) (with no `path` node) in *sysrepo*. If you follow that schema correctly, it should work.

Regards,
Michal

**Comment by GuoyouZhang** [comment]
yes, we do use ietf-netconf-acm@2018-02-14.yang, just cannot find suitable example for path in nacm rule.
could you share some example with path in rule in xml format?  thanks!

**Comment by michalvasko** [comment]
Hi,
sorry, I mistakenly thought that your data is wrong, it is not (provided you have `ietf-system` model loaded in *sysrepo*). So yes, importing the data using *sysrepocfg* does not work because this required model is not loaded. However, you can use *netopeer2-server* and *netopeer2-cli* so set it, that works fine. As *sysrepocfg* is mostly a helper tool and is not meant to cover every use-case, I think it is fine the way it is.

Regards,
Michal

**Comment by GuoyouZhang** [comment]
thanks for the information! not fully understand the "this required model is not loaded",  did you mean i should load some other module than ietf-system and ietf-netconf-acm? 
in my case i don't want user to modify the acm rules over netconf interface.  so I'm think is their any other way that i can import the nacm rule. e.g. write a app like your test code https://github.com/sysrepo/sysrepo/blob/master/tests/nacm_test.c.   or use netopeer2 to import nacm rule and generate startup file, then copy the startup file to my target host.  do you think will that be possible?

**Comment by michalvasko** [comment]
Hi,
the simplest way is to use `sysrepocfg`. Just run
```
# sysrepocfg --editor=vim --datastore startup --format xml ietf-netconf-acm
```
and edit the configuration.

Regards,
Michal

**Comment by GuoyouZhang** [comment]
but i want to use script to support automation. so i have to find some workaround anyway.

**Comment by michalvasko** [comment]
Hi,
sorry about my previous reply, I suggested what you originally tried and it did not work. As the compensation I have modified `sysrepocfg` so that it now should support your use-case (current `master`), so please try it.

Regards,
Michal

**Comment by GuoyouZhang** [comment]
Hi Michal,
thanks a lot!

it does work for import:)  
but doesn't work for export:

 sysrepocfg --export=./acm.xml ietf-netconf-acm
[ERR] Unable to print the data: Print error (No such file or directory).
Errors were encountered during exporting. Cancelling the operation.
