### ISSUE TITLE
State data provider callback doesn't request certain augmented leaves

### ISSUE THREAD

**Issue by huw305** [sysrepo/sysrepo#1536]
### Description
The yang model and its augmentation is as below:
mytest.yang =>
```
module mytest 
{
  namespace "urn:sysrepo:mytest";
  prefix mt;
  container test-state 
  {
    list test-case
    {
      key name;
      leaf name 
      {
        type string;
      }
      leaf result 
      {
        type uint32;
        config false;
      }
    }
  }
}
```

mytest-augment.yang =>
```
module mytest-augment 
{
  namespace "urn:sysrepo:mytest-augment";
  prefix "mta";
  import mytest 
  {
    prefix mt;
  }
  augment "/mt:test-state/mt:test-case" 
  {
    when "mt:name = 'two'";
      leaf circle 
      {
        type uint32;
        config false;
      }
      leaf rectangle 
      {
        type uint32;
        config false;
      }
      leaf triangle 
      {
        type uint32;
        config false;
      }
  }
  augment "/mt:test-state/mt:test-case" 
  {
    when "mt:name = 'one'";
      leaf red 
      {
        type uint32;
        config false;
      }
      leaf green 
      {
        type uint32;
        config false;
      }
      leaf yellow 
      {
        type uint32;
        config false;
      }
  }
}
```

Print result of Yanglint:
```
module: mytest
  +--rw test-state
     +--rw test-case* [name]
        +--rw name                        string
        +--ro result?                     uint32
        +--ro mytest-augment:circle?      uint32
        +--ro mytest-augment:rectangle?   uint32
        +--ro mytest-augment:triangle?    uint32
        +--ro mytest-augment:red?         uint32
        +--ro mytest-augment:green?       uint32
        +--ro mytest-augment:yellow?      uint32
```

The below xml file is imported by sysrepocfg to create three instances for the list "test-case", with the key name "one", "two" and "three":
```
<test-state xmlns="urn:sysrepo:mytest">
  <test-case>
    <name>one</name>
  </test-case>
  <test-case>
    <name>two</name>
  </test-case>
  <test-case>
    <name>three</name>
  </test-case>
</test-state>
```

The state data provider is subscribed by:
```
sr_dp_get_items_subscribe(session, "/mytest:test-state", test_state_cb, NULL, SR_SUBSCR_CTX_REUSE, &subscription);
```

And the state data provider callback is:
```
test_state_cb(const char *xpath, sr_val_t **values, size_t *values_cnt, uint64_t request_id, const char *original_xpath, void *private_ctx)
{
    SRP_LOG_WRN("Mytest state callback: xpath=%s", xpath);
}
```

Usually the state data provider callback will be called multiple times, each time the input parameter “xpath” will contain one leaf that the sysrepo wants to read. But from the sysrepo logs I can see some augmented leaves are never requested by the data provider callback. 
In "mytest-augment.yang", the first augmentation is completely ignored which has 3 leaves "circle", "rectangle" and "triangle". The second augmentation has 3 leaves "red", "green" and "yellow", but only the first leaf "red" is requested.

The sysrepo logs =>
```
May 16 10:19:07 sysrepod[1069]: [INF] Refresh session request running datastore
May 16 10:19:07 sysrepod[1069]: [INF] No operation has been performed on this session so far
May 16 10:19:07 sysrepod[1069]: [INF] Get items request running datastore, xpath: /mytest:*//., offset: 0, limit: 100
May 16 10:19:07 sysrepod[1069]: [INF] Data file /etc/sysrepo/data/ietf-yang-library.running is empty
May 16 10:19:07 sysrepod[1069]: [INF] Data file /etc/sysrepo/data/mytest.running loaded successfully
May 16 10:19:07 sysrepo-sysrepo-plugind[1075]: [WRN] (test_state_cb:44) Mytest state callback: xpath=/mytest:test-state/test-case[name='one']/result
May 16 10:19:07 sysrepo-sysrepo-plugind[1075]: [WRN] (test_state_cb:44) Mytest state callback: xpath=/mytest:test-state/test-case[name='two']/result
May 16 10:19:07 sysrepo-sysrepo-plugind[1075]: [WRN] (test_state_cb:44) Mytest state callback: xpath=/mytest:test-state/test-case[name='three']/result
May 16 10:19:07 sysrepo-sysrepo-plugind[1075]: [WRN] (test_state_cb:44) Mytest state callback: xpath=/mytest:test-state/test-case[name='one']/mytest-augment:red
May 16 10:19:07 sysrepo-sysrepo-plugind[1075]: [WRN] (test_state_cb:44) Mytest state callback: xpath=/mytest:test-state/test-case[name='two']/mytest-augment:red
May 16 10:19:07 sysrepo-sysrepo-plugind[1075]: [WRN] (test_state_cb:44) Mytest state callback: xpath=/mytest:test-state/test-case[name='three']/mytest-augment:red
May 16 10:19:07 sysrepod[1069]: [INF] Get items request running datastore, xpath: /mytest:*//., offset: 0, limit: 100
May 16 10:19:07 sysrepod[1069]: [INF] Get items request running datastore, xpath: /mytest:*//., offset: 13, limit: 100
May 16 10:19:19 netopeer2-server[1078]: SSH key exchange timeout.
```

### Steps to Reproduce
1. Install yang models:
sysrepoctl --install --yang=/etc/sysrepo/yang/mytest.yang --permissions=666
sysrepoctl --install --yang=/etc/sysrepo/yang/mytest-augment.yang --permissions=666
2. Import configuration file:
sysrepocfg --import=/etc/sysrepo/xml/mytest.xml --datastore=startup mytest
3. Start netopeer2 server and client:
/etc/init.d/netopeer2-server start
netopeer2-cli
4. Connect to the server and send the "get" message:
get --filter-xpath /mytest:*

**Expected behavior:**
```
> get --filter-xpath /mytest:*
DATA
<test-state xmlns="urn:sysrepo:mytest">
  <test-case>
    <name>one</name>
    <result>1001</result>
    <red xmlns="urn:sysrepo:mytest-augment">10001</red>
    <green xmlns="urn:sysrepo:mytest-augment">10001</red>
    <yellow xmlns="urn:sysrepo:mytest-augment">10001</red>
  </test-case>
  <test-case>
    <name>two</name>
    <result>2001</result>
    <circle xmlns="urn:sysrepo:mytest-augment">20001</red>
    <rectangle xmlns="urn:sysrepo:mytest-augment">20001</red>
    <triangle xmlns="urn:sysrepo:mytest-augment">20001</red>
  </test-case>
  <test-case>
    <name>three</name>
    <result>3001</result>
  </test-case>
</test-state>
```

**Actual behavior:**
```
> get --filter-xpath /mytest:*
DATA
<test-state xmlns="urn:sysrepo:mytest">
  <test-case>
    <name>one</name>
    <result>1001</result>
    <red xmlns="urn:sysrepo:mytest-augment">10001</red>
  </test-case>
  <test-case>
    <name>two</name>
    <result>2001</result>
    <red xmlns="urn:sysrepo:mytest-augment">20001</red>
  </test-case>
  <test-case>
    <name>three</name>
    <result>3001</result>
    <red xmlns="urn:sysrepo:mytest-augment">30001</red>
  </test-case>
</test-state>
```

### Versions
sysrepod - sysrepo daemon, version 0.7.7
yanglint 0.16.132
netopeer2-server 0.7.10

### Attachments
[mytest.zip](https://github.com/sysrepo/sysrepo/files/3367314/mytest.zip)

Thanks!

**Comment by michalvasko** [comment]
Hi,
I have verified that this issue is present in the current *sysrepo* and the problem is in collecting the state data subtrees for the module `mytest-augment` augments. However, this functionality is implemented in a very confusing and complex way and I have already fixed several corner cases where it did not work correctly. It would most likely take me significant time to fix your use-case and make sure all the previous ones still work correctly and there is not much point, anyway.

So, it should work fine in the new *sysrepo* (that will soon be available) and I will not fix this in the old one, sorry.

Regards,
Michal

**Comment by huw305** [comment]
Hi Michal,

Thanks for your feedback.
Could you tell when the new sysrepo will be available?

Thanks,
Huw

**Comment by michalvasko** [comment]
Hi Huw,
new *sysrepo* should be made officially public today or tomorrow.

Regards,
Michal

**Comment by yinoncoh** [comment]
I simulated the same scenario described here by Huw, using the latest code from GIT, and I got the same results as reported by Huw.
Is there a plan to fix it?

Thanks,
Yinon

**Comment by michalvasko** [comment]
What version of *sysrepo* have you used exactly?

**Comment by yinoncoh** [comment]
Hi Michal,
I compiled the latest from master (commit 8afd2e05cbc84ae16717d2718ff433c636673d7d).
VERSION 1.4.70 
SOVERSION 5.5.12

Thanks,
Yinon

**Comment by michalvasko** [comment]
Okay, could you please share some output, the used YANG/data files, and anything else for reproducing it?

**Comment by yinoncoh** [comment]
Actually I used the same YANG/DATA files from this case, but during reproducing it again I realized that I may had wrong conclusions.
Please ignore it for now.

Thanks,
Yinon
