### ISSUE TITLE
sysrepocfg --export doesn't sort data according to list keys

### ISSUE THREAD

**Issue by martintelco** [sysrepo/sysrepo#1541]
When dumping configuration with sysrepocfg --export ,we expect that lists will be ordered by key, as defined in the Yang. Instead, they are exported in the order configuration was added.
Maybe problem is that internally sysrepo doesn't sort the data properly.

How to recreate.
Lets assume following datamodel (napalm-star-wars.yang):
```yang
   container universe {
        list individual {
            // identify each individual by using the name as key
            key "id";
            // each individual will have the elements defined in the grouping
            uses personal-data;
        }
    }
```
We install the module and import data:
```
 # sysrepod -v
sysrepod - sysrepo daemon, version 0.7.7
# sysrepoctl --install --yang=napalm-star-wars.yang --permissions=666
Installing a new module from file '/root/napalm-star-wars.yang'...
Installing the YANG file to '/etc/sysrepo/yang/napalm-star-wars@2018-08-22.yang'...
Installing data files for module 'napalm-star-wars'...
Notifying sysrepo about the change...
Install operation completed successfully.
# sysrepocfg --merge=dump_file.xml --format=xml --datastore=startup napalm-star-wars
The new configuration was successfully applied.
```
The file add rows in list with unsorted keys - 30,15,10,90. 
Lets see what was added:
```
# sysrepocfg --export=/export --datastore=startup napalm-star-wars -f xml
The configuration was successfully exported.
# cat /export
<universe xmlns="urn:napalm-star-wars">
  <individual>
    <id>15</id>
    <name>name15</name>
  </individual>
  <individual>
    <id>30</id>
    <name>name30</name>
  </individual>
  <individual>
    <id>10</id>
    <name>name1</name>
  </individual>
  <individual>
    <id>90</id>
    <name>name90</name>
  </individual>
</universe>
```

The expected result would be to see list items sorted: 10,15,30,90.

[model.zip](https://github.com/sysrepo/sysrepo/files/3378244/model.zip)

**Comment by michalvasko** [comment]
Hi,
> lists will be ordered by key, as defined in the Yang

What do you mean by this, can you reference any text talking about some ordering? Unless you have `user-ordered` list, the order is not significant, can be arbitrary, and that is why *sysrepo* does not change it.

Regards,
Michal

**Comment by martintelco** [comment]
Hi Michal,

As RFC6020 [specifies](https://tools.ietf.org/html/rfc6020#section-7.7.5.1), default behavior should be ordered-by system, and I would expect that data should be ordered by the key.

Thanks.

**Comment by michalvasko** [comment]
Hi,
we have not really taken that paragraph into consideration, for some reason. It is not strictly required, so we do conform to the RFC, but a recommendation should not be ignored. So, we will add sorting into the new *libyang* and once it is used in *sysrepo*, it will support it. That will take, however, at least half a year, maybe more. Sorry.

Regards,
Michal

**Comment by martintelco** [comment]
Hi Michal,

Great, Thanks.
martin.

**Comment by michalvasko** [comment]
Took significantly longer but is supported in current `devel` version of libyang/sysrepo.
