### ISSUE TITLE
Question: How to return a special error info for set item 

### ISSUE THREAD

**Issue by TiejunShuang** [sysrepo/sysrepo#1542]
Hi,
   We want return some special (or custom define info) to controller when set item verify fail.  Any suggest  for it?  Does add the info to sr_errlist[] ? 

Thanks!
Tiejun

**Comment by michalvasko** [comment]
Hi Tiejun,
you should be able to use [sr_set_error()](http://www.sysrepo.org/static/doc/html/group__cl.html#ga678318adce7d37a19f31b22845dc077e) for this purpose, in the verifying callback.

Regards,
Michal

**Comment by TiejunShuang** [comment]
Hi Michal,
Thanks a lot. I'll try it.

Regards,
Tiejun
