### ISSUE TITLE
When and how to use locks?

### ISSUE THREAD

**Issue by knoll01** [sysrepo/sysrepo#1543]
It is unclear to me when I should use lock_datastore() and/or lock_module().

I am currently using lock_module when my application needs to update the running datastore for my module. 
However, I've noticed that this has some odd interaction with subtree_change_subscribe (and potentially others). I can't quite figure out all the specific sequences that work/don't work, but as an example:

1. Start connection, session
2. Activate a subscription via subtree_change_subscribe
3. Wait..
4. Some event internal to my software occurs that wants to make a change in the subtree
5. Obtain lock via lock_module
6. Attempt unsubscribe() - fails
7. unlock_module()
8. unsubscribe() successful.

Another example involves attempting a commit() in a sequence similar to above. In this case, the commit() doesn't fail, but the changed/created data fails to show up in get_item() calls.

There are some other sequences, but I haven't catalogued them.

Is there anything that describes the correct use, sequences, and the interaction of (un)lock, (un)subscribe, and commit()?

**Comment by michalvasko** [comment]
Hi,
any locking (`lock_datastore()` or `lock_module()`) is mostly to support NETCONF `<lock>` operation, during basic *sysrepo* use it is rarely needed so I think you can just skip it. It is used to prevent other clients from changing the datastore between your `sr_set_*()` calls and `sr_commit()`.

Other than that, there is no documentation of locking interacting with other functions (except with other [sr_lock_datastore()](http://www.sysrepo.org/static/doc/html/group__cl.html#ga575a1d85697026cc9f914d5bd13ec87a)). Ideally, sequences such as yours should work but locks are a bit messy so it is always best to `unlock` module/datastore as soon as possible, before calling other unrelated functions.

Regards,
Michal

**Comment by knoll01** [comment]
Thanks for the information. If I find more patterns where the locking causes issues, I'll report them.
