### ISSUE TITLE
state data provider produces duplicate callbacks in a list

### ISSUE THREAD

**Issue by ranje93** [sysrepo/sysrepo#1544]
Hello,
The model I am using is microwave-model:
[https://github.com/OpenNetworkingFoundation/5G-xHaul/blob/master/models/yang/microwave-model.yang](url)
within the `mw-air-interface-pac` object there is a container `air-interface-current-performance`.
I have in the database two instances of the `mw-air-interface-pac`.
I understand that I should not return any lists or containers from the first callback as there will be subsequent callbacks that will ask for them.
These are the callbacks that I am getting:

1.
xpath:
`/microwave-model:mw-air-interface-pac[layer-protocol='268451969-MWPS-LP']/air-interface-current-performance`
2.
xpath:
`/microwave-model:mw-air-interface-pac[layer-protocol='268451970-MWPS-LP']/air-interface-current-performance`
3.
xpath:
`/microwave-model:mw-air-interface-pac[layer-protocol='268451969-MWPS-LP']/air-interface-current-performance/current-performance-data-list`
4.
xpath:
`/microwave-model:mw-air-interface-pac[layer-protocol='268451970-MWPS-LP']/air-interface-current-performance/current-performance-data-list`
5.
xpath:
`/microwave-model:mw-air-interface-pac[layer-protocol='268451969-MWPS-LP']/air-interface-current-performance/current-performance-data-list[scanner-id='0']/performance-data`
6.
xpath:
`/microwave-model:mw-air-interface-pac[layer-protocol='268451969-MWPS-LP']/air-interface-current-performance/current-performance-data-list[scanner-id='0']/performance-data`
7.
xpath:
`/microwave-model:mw-air-interface-pac[layer-protocol='268451970-MWPS-LP']/air-interface-current-performance/current-performance-data-list[scanner-id='0']/performance-data`

In the first two callbacks I return nothing as there are no leaves to return within the container.
In callback 3 and 4 I create list (with key=0) for every `mw-air-interface-pac` instance.
then 5 and 6 suppose to be callbacks about the container `performance-data` within the list `current-performance-data-list`.

However, for some reason I get a duplicate callbacks as number 6 is just like 5.
then callback 7 which is for the other `mw-air-interface` instance acts normally without duplicate.
This also causes the data that is returned to be wrong.
Any ideas on what causing this behaviour?

Thanks

**Comment by michalvasko** [comment]
Hi,
what *sysrepo* and *libyang* versions are you using? I have tested it with the latest release and it worked fine. I started with those 2 instances of `mw-air-interface-pac` in the `running` datastore. Then having subscribed to providing `/microwave-model:mw-air-interface-pac/air-interface-current-performance` I requested `/microwave-model:*//.` from *sysrepo*. My callbacks called were
```
Data for '/microwave-model:mw-air-interface-pac[layer-protocol='268451969-MWPS-LP']/air-interface-current-performance' requested.
Data for '/microwave-model:mw-air-interface-pac[layer-protocol='268451970-MWPS-LP']/air-interface-current-performance' requested.
Data for '/microwave-model:mw-air-interface-pac[layer-protocol='268451969-MWPS-LP']/air-interface-current-performance/current-performance-data-list' requested.
Data for '/microwave-model:mw-air-interface-pac[layer-protocol='268451970-MWPS-LP']/air-interface-current-performance/current-performance-data-list' requested.
Data for '/microwave-model:mw-air-interface-pac[layer-protocol='268451969-MWPS-LP']/air-interface-current-performance/current-performance-data-list[scanner-id='0']/performance-data' requested.
Data for '/microwave-model:mw-air-interface-pac[layer-protocol='268451970-MWPS-LP']/air-interface-current-performance/current-performance-data-list[scanner-id='0']/performance-data' requested.
Data for '/microwave-model:mw-air-interface-pac[layer-protocol='268451969-MWPS-LP']/air-interface-current-performance/current-performance-data-list[scanner-id='0']/performance-data/time-x-states-list' requested.
Data for '/microwave-model:mw-air-interface-pac[layer-protocol='268451970-MWPS-LP']/air-interface-current-performance/current-performance-data-list[scanner-id='0']/performance-data/time-x-states-list' requested.
```
Obviously, I also created one `current-performance-data-list` instance for each `mw-air-interface-pac` in the state callback.

Regards,
Michal

**Comment by ranje93** [comment]
Currently I am using 0.16.108. I am going to upgrade right now and retry.

Just to be sure about the usage, when you say:
> Obviously, I also created one current-performance-data-list instance for each mw-air-interface-pac in the state callback. > 

Do you mean that you created an instance of the current-performance-data-list (with key = 0) within the two callbacks number 3 and 4.

> Data for '/microwave-model:mw-air-interface-pac[layer-protocol='268451969-MWPS-LP']/air-interface-current-performance/current-performance-data-list' requested.
> 
one list created here for `268451969-MWPS-LP`

> Data for '/microwave-model:mw-air-interface-pac[layer-protocol='268451970-MWPS-LP']/air-interface-current-performance/current-performance-data-list' requested.
> 
one list created here for `268451970-MWPS-LP`
Am I right?
Thanks

**Comment by michalvasko** [comment]
Hi,
you are right. It should be obvious from my callback no. 5, 6, 7, 8. They would not be called unless the `current-performance-data-list` instances existed.

Regards,
Michal
