### ISSUE TITLE
Unable to sh: install not found for new yang models

### ISSUE THREAD

**Issue by cclark1974** [sysrepo/sysrepo#1545]
Im running sysrepo on top of a OpenWRT VM on openstack and Im encountering the following error.  I am able to successfully remove modules, just not install them.

root@OpenWrt:~/tmp# sysrepoctl -l
Sysrepo schema directory: /etc/sysrepo/yang/
Sysrepo data directory:   /etc/sysrepo/data/
(Do not alter contents of these directories manually)

Module Name                | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |
nc-notifications           | 2008-07-14 | Installed   | root:root           | 666         |                               |
ietf-netconf-acm           | 2018-02-14 | Installed   | root:root           | 644         |                               |
ietf-netconf-notifications | 2012-02-06 | Installed   | root:root           | 600         |                               |
ietf-netconf               | 2011-06-01 | Implemented | root:root           | 600         |                               | writable-running candidate rollback-on-error validate startup xpath url
ietf-keystore              | 2016-10-31 | Installed   | root:root           | 600         |                               |
ietf-ssh-server            | 2016-11-02 | Installed   |                     |             |                               |
ietf-tls-server            | 2016-11-02 | Installed   |                     |             |                               |
iana-crypt-hash            | 2014-08-06 | Installed   |                     |             |                               |
ietf-x509-cert-to-name     | 2014-12-10 | Installed   |                     |             |                               |
ietf-netconf-server        | 2016-11-02 | Installed   | root:root           | 600         |                               | listen ssh-listen tls-listen call-home ssh-call-home tls-call-home
ietf-netconf-monitoring    | 2010-10-04 | Installed   | root:root           | 600         |                               |
ietf-netconf-with-defaults | 2011-06-01 | Installed   |                     |             |                               |
ietf-system                | 2014-08-06 | Installed   | root:root           | 600         |                               | authentication local-users
ietf-datastores            | 2017-08-17 | Installed   |                     |             |                               |
ietf-yang-library          | 2018-01-17 | Installed   | root:root           | 600         |                               |

root@OpenWrt:~/tmp# 

root@OpenWrt:~/tmp# sysrepoctl -i --yang=test-common.yang -p 666 -o root:root -s /etc/sysrepo/yang
Installing a new module from file 'test-common.yang'...
Installing the YANG file to '/etc/sysrepo/yang/test-common@2016-06-01.yang'...
sh: install: not found
Error: Unable to install the YANG file to '/etc/sysrepo/yang/test-common@2016-06-01.yang'.
Installation of schema files cancelled for module 'test-common', reverting...
Reverting the install operation...
Deleted the schema file '/etc/sysrepo/yang/test-common@2016-06-01.yang'.
Install operation failed.
root@OpenWrt:~/tmp# 

root@OpenWrt:~/tmp# sysrepoctl -v
sysrepoctl - sysrepo control tool, version 0.7.7

**Comment by michalvasko** [comment]
Hi,
you are missing the `install(1)` utility, it should work fine after installing it.

Regards,
Michal

**Comment by cclark1974** [comment]
Is there an additional install Im missing with opkg install?

**Comment by michalvasko** [comment]
Hi,
I believe you simple need to have [this](https://openwrt.org/packages/pkgdata/coreutils-install) package installed.

Regards,
Michal

**Comment by cclark1974** [comment]
That worked! Thanks

**Comment by cclark1974** [comment]
Netopeer2-server? Do you know if I can get this in the following repo:
/releases/18.06.4/packages/i386_pentium4/packages: ?

I only see netopeer2-keystore

Thanks
Charles

**Comment by michalvasko** [comment]
Hi Charles,
if you are talking about OpenWRT packages, the previous maintainer is no longer working on this project, so the packages are not kept up-to-date. It seems there are some more recent scripts [here](https://github.com/openwrt/packages/tree/master/net/Netopeer2), maybe you can use that.

Regards,
Michal

**Comment by cclark1974** [comment]
How do I run opkg install using that location? Do I add it as a repo?

**Comment by cclark1974** [comment]
Im currently running a VM, how do I build netopeer2-server on the VM?

Thanks,
Charles
