### ISSUE TITLE
Sysrepo slows almost exponentially when writing large number of entries to candidate store 

### ISSUE THREAD

**Issue by agva123** [sysrepo/sysrepo#1546]
Environment: Ubuntu 18.04 VM, latest tool chain (libyang, libnetconf2, sysrepo, netopeer2)
Test: writing > 1000 of new test config data to candidate store. Write is from netopeer2-cli by loading xml file with >1000 repetitive instances, with the following CLI command:
> edit-config --target candidate --config=/develop/atest-1000.xml

Behavior: sysrepo responds relatively fast with ~first 300 records and then speed of response continues to drop. The processing speed may depends on the processing power of my VM, however I should not expect an exponential growth of the response time. 
Below is the detail of the measured performance of edit-config (50-200 response time is from timed measurement on the cli, >200 response time is measured by a stopwatch: 
number of records              response time
50                               0.389s
100                             1.521s
200                             10.57s
300                             30s
500                             2m 19.17s
1000                           15m 39s
2000                           49m

Content of the test xml:
```xml
<test-container xmlns="http://test.com/yang/">
    <test-id>1</test-id>
    <test-name>1</test-name>
    <test-location>test</test-location>
</test-container>
```
(and they repeat, say, 1000 times)

I'd appreciate if someone could shed some light on it. Thanks.

**Comment by michalvasko** [comment]
Hi,
could you please provide a bit more information so that I can try it? The testing YANG model and a file with at least 2 "records", please? Then how exactly did you test it, send `edit-config` with 50 records to an empty `candidate`, then 100 records to an empty `candidate` and so on or the previously added values remained in between the tests?

Regards,
Michal

**Comment by agva123** [comment]
Hi Michal,

Attached are the test yang model and xml script. To show the effect I increased the # of entries to 2000.

[Test YANG model schema](https://github.com/agva123/test/blob/master/a-test.yang)
[Test XML script](https://github.com/agva123/test/blob/master/atest-2000.xml)

**Comment by agva123** [comment]
And command for the test is:

edit-config --target candidate --config=/test/atest-2000.xml

**Comment by michalvasko** [comment]
Hi,
I do not positively know why it takes exponentially longer, it is probably due to validating the whole `candidate` datastore on every edit, which performed for each container. But the actual reason for this performance is the unfortunate architecture of the current *sysrepo* and *netopeer2*. We wanted to fix that in the new *sysrepo* so I used this chance to benchmark your use-case on both versions. For measuring time I have used *netopeer2-cli* `timed` command, it was meant for exactly these cases so you can use it, too.

Results for the current (`master`) *sysrepo* and *netopeer2*:
```
> edit-config --target candidate --config=../../../sysrepo/atest-100.xml
OK
mono  0m0,219s
> edit-config --target candidate --config=../../../sysrepo/atest-200.xml
OK
mono  0m1,092s
> edit-config --target candidate --config=../../../sysrepo/atest-500.xml
OK
mono  0m17,462s
> edit-config --target candidate --config=../../../sysrepo/atest-1000.xml
OK
mono  2m6,316s
```
I did not feel like waiting half an hour for those 2000 items.
Results for *sysrepo* from `devel` with *netopeer2* from `devel-server`:
```
> edit-config --target candidate --config=../../../sysrepo/atest-100.xml
OK
mono  0m0,017s
> edit-config --target candidate --config=../../../sysrepo/atest-200.xml
OK
mono  0m0,018s
> edit-config --target candidate --config=../../../sysrepo/atest-500.xml
OK
mono  0m0,029s
> edit-config --target candidate --config=../../../sysrepo/atest-1000.xml
OK
mono  0m0,048s
> edit-config --target candidate --config=../../../sysrepo/atest-2000.xml
OK
mono  0m0,096s
```
You can try it yourself.

Regards,
Michal

**Comment by agva123** [comment]
Thanks Michal. I tried to compile netopeer2 devel-server, however it did not compile with the devel branch of sysrepo - quite a few build breaks...any idea how to get around it to check the performance? Thanks!

**Comment by michalvasko** [comment]
Hi,
have you also used *libnetconf2* `devel`?

Regards,
Michal

**Comment by agva123** [comment]
hi Michal,
I switched to libnetconf2 devel, however sysrepo only partially builds - it does not build "sysrepod" after the make, but utilities like sysrepoctl, sysrepocfg etc are built. Yet if I attempt to use sysrepoctl to list installed models, it always cause segmentation fault with non-root user, but lists ok with sudo. Furthermore, if I use sysrepoctl to install the test model it always segmentation fault.  Also, default repository somehow always points to sysrepo/build/repository instead of /etc/sysrepo. 

So, I think somehow there are compatibility issues between the devel- branches of sysrepo/libnetconf2/libyang, but I just do not know what the issues are. Could you give a little more hint on that? Thanks!

**Comment by michalvasko** [comment]
Hi,
thanks for trying the `devel`, there were not many users before you so some problems are expected. Now, there is **no** `sysrepod`so it is only natural it does not build. Also, if you have used the same `cmake` variable as for the old *sysrepo*, it was most likely wrong, it is `REPO_PATH` now. When you run a clean run of `cmake`, all the paths are written to output, you just need to check them.

Fixing all that, `sysrepoctl` should not crash no matter what. Have you installed the new *sysrepo*? You can try running `# make sr_clean` and then executing `sysrepoctl` again. Or, are you able to use `valgrind`/`gdb` to examine the crash?

Regards,
Michal

**Comment by agva123** [comment]
Thanks Michal. If it does not build sysrepod then how should I run sysrepo, using that from the master build? I'm sort of confused. Thanks again for the clarification.

**Comment by michalvasko** [comment]
Hi,
I would probably first suggest to `make doc` of the `devel` *sysrepo* and look briefly through it. The new *sysrepo* has many new features, one being that it does not have a daemon. For you the whole difference is that you do not have to start `sysrepod`, you simply run your applications. In other words, the new *sysrepo* has only the "library mode" of the old one.

Regards,
Michal

**Comment by TiejunShuang** [comment]
Hi Michal,
I met the same issue. So I want try your devel branch. Is it depend on libyang main brand or devel branch or libyang2 branch? does download Libnetconf2 and netopeer main branch is ok?
BTW, how to clone devel branch? the URL in devel branch is same with main branch. 

Regards,
Tiejun

**Comment by michalvasko** [comment]
Hi Tiejun,
you need  current *libyang* `master`/`devel`, *sysrepo* `devel`, *libnetconf2* `devel`, and *netopeer2* `devel-server`. You clone a specific branch by adding `-b <branch>` to `git clone`. Or, you simply change the branch once you clone the repository. All of this can easily be learnt by a quick search.

Regards,
Michal

**Comment by brchiu** [comment]
hi, @michalvasko , I follow your instruction to use ` libyang master/devel, sysrepo devel, libnetconf2 devel, and netopeer2 devel-server`. 

In addition to https://github.com/sysrepo/sysrepo/issues/1605, I got the following error message during install netopeer2-server and netopeer2-server can not launch with similar error message :
```
$ sudo make install
[ 77%] Built target serverobj
[100%] Built target netopeer2-server
Install the project...
-- Install configuration: "debug"
-- Installing: /usr/local/bin/netopeer2-server
-- Set runtime path of "/usr/local/bin/netopeer2-server" to ""
-- Installing sysrepo modules...
libyang[0]: Module "ietf-netconf" in another revision already implemented.
libyang[0]: Module "ietf-netconf-with-defaults" parsing failed.
sysrepoctl error: Failed to connect (libyang error)
-- Generating a new RSA host key "genkey"...
libyang[0]: Module "ietf-netconf" in another revision already implemented.
libyang[0]: Module "ietf-netconf-with-defaults" parsing failed.
sysrepocfg error: Failed to connect (libyang error)
-- Merging default server listen configuration...
libyang[0]: Module "ietf-netconf" in another revision already implemented.
libyang[0]: Module "ietf-netconf-with-defaults" parsing failed.
sysrepocfg error: Failed to connect (libyang error)
```

libyang master/devel :  https://github.com/CESNET/libyang/commit/52bfda13f630ef70cd4a3e72ca55e6ef8d8ad867
libnetconf2 devel : https://github.com/CESNET/libnetconf2/commit/cd21513c89d3b8b16b53826bccd60983256abf22
sysrepo devel : https://github.com/sysrepo/sysrepo/commit/999f7ededc2cb569f72e8361bdc36e989b9131e1
Netopeer2 devel-server : https://github.com/CESNET/Netopeer2/commit/512d310ea853359e5ffff8c2039148a11a7bb951
