### ISSUE TITLE
Commit phase Verify done -> Write failed -> No error

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1547]
Hi,

Observed one issue while debugging #1518.

In Commit phases it is successfull upto verify phase(7/10) and failed to write data to files(8/10).

Even then the control goes to APPLY_NOTIFY(9/10) and sysrepocfg shows the new configuration applied successfully message.

If data is verified successfully it should not fail to write to files. In my scenario write is failing due to invalid pointer in leafref->target

Thanks & Regards,
Sriram.K

**Comment by sriramkandukuri** [comment]
Hi Michal,

It is pointing to some random memory and the datatype is getting invalid value and printer_xml fails with internal error.

This is not observed when I disable some deviation. This deviation node is nowhere related to the module or leafref.

I am unsuccessfull in trying to reproduce this simply.

**Comment by michalvasko** [comment]
Hi,
you can send the files to my email (in my profile) but you can also try to use the new *sysrepo* from `devel` branch, it could work there.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Due to changes in APIs(as per CHANGES doc) we cannot use new sysrepo(devel) directly. We are mostly dependent on sr_get_items_[iter/next] APIs

I have sent you mail with data and steps which causing the error. 

I am using below packages
sysrepo->master
libyang->master

**Comment by michalvasko** [comment]
Hi,
I will take a look at what you sent me but regarding the new *sysrepo*, why can't you simply use `sr_get_data()` (new function retrieving *libyang* data trees) and get everything at once?

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Untill we added deviations to our system everything is stable. Suggested changes to use new functions takes huge porting efforts based on our usage of existing functions. Porting is not yet planned.

So moving to new sysrepo may take some time from our side.

**Comment by michalvasko** [comment]
Hi,
if you use the latest *libyang*, it should work.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Will try and let you know the status.
