### ISSUE TITLE
Iterating tree fails with SR_GET_SUBTREE_ITERATIVE and data provider.

### ISSUE THREAD

**Issue by iljatab** [sysrepo/sysrepo#1548]
* [x] Did you check if this is a duplicate issue?
* [ ] Did you test it on the latest sysrepo devel branch?

### Description
Iterating tree fails with SR_GET_SUBTREE_ITERATIVE and SR_SESS_DEFAULT.
1. Connection created with SR_CONN_DAEMON_REQUIRED.
2. Session opened with SR_DS_RUNNING, SR_SESS_DEFAULT.
3. Tree requested with:
sr_get_subtree(sess), xpath, SR_GET_SUBTREE_ITERATIVE, &tree);

**Expected behavior:**
Navigating tree with sr_node_get_child() and sr_node_get_next_sibling() expected to work.

**Actual behavior:**
Looks like only first chunk of data (part of tree) is received and this partial tree looks OK.
When sr_node_get_child() and sr_node_get_next_sibling() try loading more chunks it fails with errors:
Jul 20 15:54:17 a20 a20 err sysrepod[830]: [ERR] libyang error: Schema node not found.
Jul 20 15:54:17 a20 a20 err sysrepod[830]: [ERR] Failed to get the set of tree roots for xpath /openconfig-interfaces:interfaces/interface[41]
Jul 20 15:54:17 a20 a20 err sysrepod[830]: [ERR] Failed to get the set of tree roots matching xpath /openconfig-interfaces:interfaces/interface[41]
Jul 20 15:54:17 a20 a20 err sysrepod[830]: [ERR] rp_dt_xpath_requests_state_data failed
Jul 20 15:54:17 a20 a20 err sysrepod[830]: [ERR] rp_dt_prepare_data failed Invalid argument
Jul 20 15:54:17 a20 a20 err sysrepod[830]: [ERR] Get subtree chunk failed for '/openconfig-interfaces:interfaces/interface[41]', session id=1637456266.

However iterating the tree works OK with either:
- session created with SR_SESS_CONFIG_ONLY
or
- sr_get_subtree() called with SR_GET_SUBTREE_DEFAULT

### Versions
sysrepod - sysrepo daemon, version 0.7.7
yanglint 0.16.105

**Comment by michalvasko** [comment]
Hi,
except for the invalid assert (referenced) I have not encountered any problems when trying some `ietf-interfaces` requests of state data. You will have to specify exactly what your data are, your subscriptions, the state data you return, and the subtree request so that I can reproduce it and then fix it.

Regards,
Michal

**Comment by iljatab** [comment]
Switching to new sysrepo...
