### ISSUE TITLE
Usefulness of SR_SUBSCR_CTX_REUSE

### ISSUE THREAD

**Issue by knoll01** [sysrepo/sysrepo#1549]
I've read the documentation for SR_SUBSCR_CTX_REUSE  and examined the oven example to better understand what this option does. It's still not entirely clear to me what its purpose is.

Does SR_SUBSCR_CTX_REUSE simply allow the user to setup multiple subscriptions on the same session and unsubscribe from them with a single unsubscribe() call? 
Is there more to it? 
Are there any other benefits? 
Does it affect the session that is provided when the callback is called?

**Comment by michalvasko** [comment]
Hi,
there really is not much to this option, mostly just to allow to have one or a few subscription structures even if you have hundreds of subscriptions. But it does affect unsubscribing, you can only do that on all the subscriptions in one subscription structure.

Also, this option is more important in the new *sysrepo*, in which one subscription can only be handled by one thread, generally speaking.

Regards,
Michal

**Comment by knoll01** [comment]
Thanks for the explanation. This is very helpful.
