### ISSUE TITLE
sr_set_error() has no effect in RPC callback

### ISSUE THREAD

**Issue by iljatab** [sysrepo/sysrepo#1553]
### Things you may try first
(put "x" in "[]" if you already tried following)
* [x] Did you check if this is a duplicate issue?
* [] Did you test it on the latest sysrepo devel branch?

### Description
Cannot set a user-defined error message in RPC callback.
Callback installed by sr_rpc_subscribe().
Error set inside RPC callback by sr_set_error().
Callback returns an SR_ERR_* value.

**Expected behavior:**
Error message visible in netopeer2-cli client.

**Actual behavior:**
Error message in netopeer2-cli client is always a standard one, corresponding to  SR_ERR_* value returned by RPC callback.

### Versions
sysrepod - sysrepo daemon, version 0.7.8
yanglint 1.1.30
libyang version: `yanglint -v`
netopeer2-server 0.7.10

**Comment by michalvasko** [comment]
Hi,
that is how it works in the current *sysrepo* and it will not be changed. The specific errors are printed only in *sysrepo*, not in the NETCONF server/client. It should, however, work the way you expect in the new *sysrepo* in `devel`.

Regards,
Michal

**Comment by iljatab** [comment]
Ok, thanks, understood.
