### ISSUE TITLE
Does sysrepo support additional validation before writing config to running data store?

### ISSUE THREAD

**Issue by agva123** [sysrepo/sysrepo#1554]
The current sequence of the end-config is like the following:
1. client send edit-config with new configuration to running data store
2. the input xml is validated successfully against YANG schema
3. the new configuration is writting to data store
4. Backend agent is called to process the configuration request. Additional validation is performed in this step, which may find the configuration to be infeasible.

How should I do if I wish to ensure that both YANG validation (step 2) and backend agent validation (step 4) are successful before writing and saving the configurations into the running data store? In other words, I would like to not save any configuration and return error during edit-config if the validations fail.

Thank you.

**Comment by michalvasko** [comment]
Hi,
the sequence you mentioned is incorrect.
1. NETCONF client sends an `edit-config`,
2. NETCONF server receives it and transforms it into *sysrepo* CRUD operations and then calls `sr_commit()`,
3. *sysrepo* will now call all matching subscription callbacks with `SR_EV_VERIFY` event. That gives the callbacks opportunity to perform some additional validation and they can refuse the changes at this stage. If they do, the whole commit fails, which in effect causes the `edit-config` to fail.
4. If all the callbacks return success from `SR_EV_VERIFY` event, the configuration changes are written into the persistent datastore and are visible for other session.
5. Lastly, another event `SR_EV_APPLY` is generated for the same set of callbacks when they are notified that all the callbacks passed the previous verify event and the changes were written, so they can now apply the change to the device/whatever, for example. The callbacks do not have the option to fail at this stage anymore.

Now it should be clear to you.

Regards,
Michal

**Comment by chaitu-tk** [comment]
Hi, 

Sorry for jumping in, but I have a question in this area. If the new config `SR_EV_VERIFY` is failed, then during the processing of `SR_EV_ABORT` if I do a `sr_get_items` I am still getting the new config, but I am expecting `sr_get_items` should return the RUNNING datastore config (session is for RUNNING datastore), right? (or) Should we use `sr_get_changes` and process based on `oper`?

**Comment by michalvasko** [comment]
Hi,
yes, the anticipated use-case was using `sr_get_changes` and processing these changes. It is possible `sr_get_items` still returns the aborted values now but it should not be the case in the new *sysrepo*.

Regards,
Michal

**Comment by chaitu-tk** [comment]
Thanks. Processing `sr_get_changes` is tricky esp with handling `OP_DELETED` as the respective C structures should be reset to defaults. Having `sr_get_items` return is the easiest way. And by new sysrepo are we talking next release? or sysrepo2?

**Comment by michalvasko** [comment]
Hi,
new *sysrepo* is the version from *sysrepo2* branch.

Regards,
Michal

**Comment by chaitu-tk** [comment]
I only see a `devel` branch, can you please point me the branch? and probable release date, if any. This helps in evaluating the effort to parse `sr_get_changes`.

**Comment by michalvasko** [comment]
Hi,
sorry, the branch `sysrepo2` was merged into `devel`. The new *sysrepo* will be released once there is a reasonable chance it is fairly stable and robust. Since it is technically a completely new software, it will take some time. You can help by testing it but it will most likely not be released this year, anyway.

Regards,
Michal

**Comment by chaitu-tk** [comment]
Okay, got it, will try to use `devel` and see if it works. Thanks.
