### ISSUE TITLE
Installation issues with PREFIX and REPOSITORY_LOC

### ISSUE THREAD

**Issue by chaitu-tk** [sysrepo/sysrepo#1555]
It's almost similar to https://github.com/CESNET/Netopeer2/issues/320 

### Description
I am trying to prepare a Debian package of sysrepo using fpm, but need all the necessary files in a single folder for that, but having trouble esp. with the 2 options.

-DCMAKE_INSTALL_PREFIX:PATH=./install_dir 
-DREPOSITORY_LOC:PATH=./install_dir/etc/sysrepo

cmake creates `REPOSITORY_LOC` by prefixing it with `CMAKE_INSTALL_PREFIX` but while installing `sysrepoctl` searches only in `REPOSITORY_LOC`, the only way this could be solved is by using below values

-DCMAKE_INSTALL_PREFIX:PATH=./ 
-DREPOSITORY_LOC:PATH=./install_dir/etc/sysrepo

But with this, the files are in different directories. Manually moving the dirs to `REPOSITORY_LOC` path works, but is there any way to do it by default.

BTW, I am using `-DGEN_LANGUAGE_BINDINGS:BOOL=FALSE` as it causes more install issues.

**Comment by michalvasko** [comment]
Hi,
I, just like in the referenced issue, cannot really help you because I know little about building packages. Maybe @jktjkt can provide a quick assistance.

Regards,
Michal

**Comment by chaitu-tk** [comment]
Hi Michal,

Thanks. It's more about the mismatch b/w the 2 options (creation is done with the prefix, the lookup is done without it) mentioned above not really packaging.
