### ISSUE TITLE
"Alignment trap" error on sysrepoctl command

### ISSUE THREAD

**Issue by huw305** [sysrepo/sysrepo#1556]
### Description
I'm trying to setup new sysrepo 1.0 environment (latest devel branch) on an ARM Cortex A9 platform, in which the OS is Yocto Linux.
Sometimes (quite often) sysrepoctl command will generate "Alignment trap" error like below:
`[  258.692240] Alignment trap: sysrepoctl (1236) PC=0xb6f2b724 Instr=0xe9820012 Address=0xb6f801c9 FSR 0x811`

But the sysrepoctl command can finish its job as expected, even when there's alignment error.
By adding debug printings into the sysrepo code, the alignment trap happened in the function sr_connect() -> sr_shmmain_shm_add() -> sr_shmmain_shm_add_modules(), and the misaligned Address=0xb6f801c9 is inside the ext SHM memory.
Please have a look, thanks.

### Steps to Reproduce
1. "sysrepoctl -l" after datastore changes, like install a yang model, enable feature for a yang model, etc

### Versions
Sysrepo version: libsysrepo.so.1.0.6
libyang version: libyang.so.1.1.36

Thanks!

**Comment by huw305** [comment]
Netopeer2-server will be affected too.
The server can be started but I can always see "Alignment trap" error.
If I use netopeer2-cli to connect to the server, the connection will be refused and the server will be terminated.
From the logs the failure happened when the server tries to connect to the sysrepo in function server_init().

netopeer2-cli
> connect
nc ERROR: Unable to connect to localhost:830 (Connection refused).
cmd_connect: Connecting to the localhost:830 as user "root" failed.

Server logs:
```
Jul 25 07:16:25 netopeer2-server[1046]: Locking a mutex failed (▒▒▒8VضxA^K: sr_shmmain_lock_remap).
Jul 25 07:16:25 netopeer2-server[1046]: Connecting to sysrepo failed (Timeout expired).
Jul 25 07:16:25 netopeer2-server[1046]: Server init failed.
Jul 25 07:16:25 netopeer2-server[1046]: Server terminated.
```
Server and client version:
netopeer2-server 1.0.1
Netopeer2 CLI 2.0.52

**Comment by jktjkt** [comment]
Does it happen when you rebuild sysrepo with `-DUSE_SR_MEM_MGMT=OFF`? If it starts working, then you're hitting #947 .

**Comment by huw305** [comment]
Yes I noticed #947 and tried this build option, but it has no effect.
The sysrepo devel branch uses a different memory management, so this build option has been removed.

**Comment by michalvasko** [comment]
Hi,
yes, the ext SHM is used for storing various changing data, which are simply copied one after another, without any alignment. I will try to come up with a solution so that these data are aligned, but it will take some time.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi,
all the strings now should be properly aligned, which should cause all other structures not to become misaligned. Please, verify that it works.

Regards,
Michal

**Comment by huw305** [comment]
Hi Michal, thanks a lot for providing the fix. I made a try and the "alignment trap" issue is gone.
However after updating to the latest sysrepo-devel,, the netopeer2 server will always crash when netopeer2-cli connects to the server.

I opened a ticket at:
https://github.com/CESNET/Netopeer2/issues/456

**Comment by michalvasko** [comment]
Hi,
try again now.

Regards,
Michal

**Comment by huw305** [comment]
It works now, thanks for your help!
