### ISSUE TITLE
xpath for key name to get state

### ISSUE THREAD

**Issue by zyboy2000** [sysrepo/sysrepo#1557]
### How to submit issue
Please use this text as a template and replace text in the sections or remove
the entire section if that does not apply to your issue. For example in case of
question or feature request, just description with some example is probably
fine. Also remember to use github's markup form properly, especially in case of
output or code listing.

### Things you may try first
(put "x" in "[]" if you already tried following)
* [X] Did you check if this is a duplicate issue?
* [X] Did you test it on the latest sysrepo devel branch?

### Description
When I get the list information under a single key by using the XPath RPC with key name, sysrepod triggers the callback function for each key.

For example, we have a key, index, can take 100 values. There are two lists under index: config and state. We use the XPath RPC with “[key = ‘index1’]” to get the config and state information of index1. Then sysprepod triggers a callback function of index1 to index100, and finally returns the data of index1. This process took a long time. Could it trigger callback only once when we specify xpath?

### Steps to Reproduce
1.get rpc command with xpath “[key = ‘index1’]”

**Expected behavior:**
 it trigger callback only once when we specify xpath

**Actual behavior:**
 it trigger all callbacks  when we specify xpath and take so long time

### Versions
Please provide versions for software needed to reproduce the bug:
Sysrepo version: 0.7.8
libyang version: 1.0-r2

Thanks!

**Comment by michalvasko** [comment]
Hi,
you can, to certain extent, implement this yourself by looking at the `original_xpath` in the callback. Generally, it is really challenging to implement such a functionality, so it is not supported for now.

Regards,
Michal

**Comment by michalvasko** [comment]
To this limited extent supported.
