### ISSUE TITLE
sysrepocfg cannot export nacm rule with path

### ISSUE THREAD

**Issue by GuoyouZhang** [sysrepo/sysrepo#1559]
Hi,
because  this (https://github.com/sysrepo/sysrepo/issues/1535) was closed, but it still have some issue based on my test. see the link for the detail. so i open a new ticket to trace it.

thanks!

**Comment by michalvasko** [comment]
Hi,
you did not have to open a new issue, but it does not matter. I have tried export NACM running configuration and it worked just fine. Can you be more specific about your use-case?

Regards,
Michal

**Comment by GuoyouZhang** [comment]
Hi Michal,

Here is the detail steps i have done:

# sysrepocfg --merge=ietf-interfaces.xml -f xml ietf-netconf-acm
The new configuration was successfully applied.
#
# sysrepocfg --export=nacm.xml ietf-netconf-acm
[ERR] Unable to print the data: Print error (No such file or directory).
Errors were encountered during exporting. Cancelling the operation.
# cat ietf-interfaces.xml
<nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
  <rule-list>
    <name>deny-ietf-interfaces</name>
    <group>*</group>
    <rule>
      <name>deny-create-ietf-interfaces</name>
      <module-name>ietf-interfaces</module-name>
      <path xmlns:if="urn:ietf:params:xml:ns:yang:ietf-interfaces">/if:interfaces/if:interface</path>
      <access-operations>create</access-operations>
      <action>deny</action>
      <comment>deny the edit-config operation for creation.</comment>
    </rule>
</rule-list>
</nacm>

**Comment by michalvasko** [comment]
Hi,
it works perfectly fine in my case so there is likely something wrong with your installation. Try to uninstall the whole sysrepo (`make uninstall_with_repo`) and then reinstall again. The error does not really make sense, anyway, so I cannot think of any other reason for it.

Regards,
Michal
