### ISSUE TITLE
 recipe for target 'all' failed

### ISSUE THREAD

**Issue by ligang626** [sysrepo/sysrepo#1562]
[ 17%] Built target COMMON
[ 19%] Building C object src/CMakeFiles/SR_ENGINE.dir/data_manager.c.o
/opt/raymax/git/sysrepo/src/data_manager.c: In function ‘dm_validate_data_info’:
/opt/raymax/git/sysrepo/src/data_manager.c:2872:65: error: ‘LYD_OPT_NOAUTODEL’ undeclared (first use in this function)
             if (0 != lyd_validate(&info->node, LYD_OPT_STRICT | LYD_OPT_NOAUTODEL | LYD_OPT_CONFIG, info->schema->ly_ctx)) {
                                                                 ^
/opt/raymax/git/sysrepo/src/data_manager.c:2872:65: note: each undeclared identifier is reported only once for each function it appears in
/opt/raymax/git/sysrepo/src/data_manager.c: In function ‘dm_validate_procedure_content’:
/opt/raymax/git/sysrepo/src/data_manager.c:6437:43: error: ‘LYD_OPT_NOAUTODEL’ undeclared (first use in this function)
     validation_options = LYD_OPT_STRICT | LYD_OPT_NOAUTODEL;
                                           ^
/opt/raymax/git/sysrepo/src/data_manager.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-language-extension-token’
src/CMakeFiles/SR_ENGINE.dir/build.make:278: recipe for target 'src/CMakeFiles/SR_ENGINE.dir/data_manager.c.o' failed
make[2]: *** [src/CMakeFiles/SR_ENGINE.dir/data_manager.c.o] Error 1
CMakeFiles/Makefile2:101: recipe for target 'src/CMakeFiles/SR_ENGINE.dir/all' failed
make[1]: *** [src/CMakeFiles/SR_ENGINE.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by michalvasko** [comment]
Hi,
please update your installed *libyang* version.

Regards,
Michal
