### ISSUE TITLE
[New-Sysrepo] [sysrepoctl] Installing yang files with Mandatory leaf in highlevel aborting sysrepoctl

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1564]
Hi,

Example yang file a.yang installation aborting.

```
module a {
    prefix a;
    namespace a;
    container a {
        leaf enabled {
            mandatory true;
            type boolean;
        }
    }
}
```

Logs 

```
# sysrepoctl --install a.yang -v 4
[INF]: [/opt/dev/sysrepo/src/shm_main.c 1161] Libyang internal module "yang" was installed.
[INF]: [/opt/dev/sysrepo/src/common.c 1179] Module file "ietf-yang-library@2019-01-04" installed.
[INF]: [/opt/dev/sysrepo/src/shm_main.c 1161] Libyang internal module "ietf-yang-library" was installed.
[INF]: [/opt/dev/sysrepo/src/common.c 1179] Module file "ietf-netconf@2011-06-01" installed.
[INF]: [/opt/dev/sysrepo/src/common.c 1179] Module file "ietf-netconf-with-defaults@2011-06-01" installed.
[INF]: [/opt/dev/sysrepo/src/shm_main.c 1185] Sysrepo internal module "ietf-netconf-with-defaults" was installed.
[INF]: [/opt/dev/sysrepo/src/shm_main.c 1190] Sysrepo internal dependency module "ietf-netconf" was installed.
[INF]: [/opt/dev/sysrepo/src/common.c 1179] Module file "ietf-netconf-notifications@2012-02-06" installed.
[INF]: [/opt/dev/sysrepo/src/shm_main.c 1204] Sysrepo internal module "ietf-netconf-notifications" was installed.
[INF]: Datastore copied from <startup> to <running>.
libyang[0]: Missing required element "enabled" in "a". (path: /a:a)
sysrepoctl: /opt/dev/sysrepo/src/log.c:226: sr_errinfo_new_ly: Assertion `e' failed.
Aborted (core dumped)
```
Abort is not expected. And data validation happening at the time of module installation.

**Comment by sriramkandukuri** [comment]
Hi,

After this issue and #1563 , no further `sysrepoctl` commands working untill we do `make sr_clean`

**Comment by michalvasko** [comment]
Hi,
I have tried it with the current *sysrepo* version 1.1.1 and there was no abort, could you try again? Also, the module will fail to be installed because empty data are not valid. Unless there is an actual released module that was written this way, we will keep it this way because it is not that simple to fix. The old *sysrepo* allowed this but it caused lots of internal issues and workarounds were required.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Yes the error is observed due to my local changes. I have changed libyang log option from store to log while trying to enable debug logs from libyang. That caused the abort.

Regarding failed installation.
This is due to data files being created while installation. And there is no data in those files for any leafs except the default ones. Mandatory and default cannot coexist for a leaf. Is there a way to fix this in yang module. Or we have to make all leafs to default?

This error occurs for any mandatory leaf while installation. What could be done for such models.

Thanks & Regards.
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
yes, that is what I meant, modules with invalid empty configuration (in other words with some top-level mandatory nodes or mandatory nodes in top-level non-presence containers) cannot be installed, for now. Do you have such modules that are actually used or you have written one like that only for testing?

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Yes we have such module being used.  Will try to change it and let you know.

**Comment by sriramkandukuri** [comment]
Hi Michal,

Changed module not to contain any high level mandatory leafs in any  high level containers. With this change sysrepoctl not showing any error while installation.

Thanks & Regards.
Sriram.K
