### ISSUE TITLE
[New-Sysrepo] [API sr_get_item] Returns SR_ERR_OK when no data

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1574]
Hi,

sr_get_item API returns SR_ERR_OK when there is no data. As this API is intended to get only one value and if that node doesn't exist it is expected to get SR_ERR_NOT_FOUND.

In old sysrepo this API returns SR_ERR_NOT_FOUND, Is it possible to keep it that way which also gives backward compatibility.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
no problem, fixed.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

I dint see any commit in`devel` branch for this change. Could you please share the commit id to get this change.

Thanks & Regards
Sriram.K

**Comment by michalvasko** [comment]
I have just forgotten to push it, sorry.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
This fix working. Thank you.
