### ISSUE TITLE
[New-Sysrepo] [sysrepocfg] Commads failing with space after options

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1575]
HI,

sysrepocfg commands failing if we pass space between command and arguments.

Example:
```
sysrepocfg -I./test.xml -m ietf-interfaces -f xml -v 4
```
Above command executes successfully.

```
sysrepocfg -I ./test.xml -m ietf-interfaces -f xml -v 4
```
Above command fails saying `Redundant parameters (./test.xml)`
Same behavior observed for all arguments.

Thanks & Regards
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
that is the behavior of `getopt_long()` (that the parameter is not interpreted as the optional `-I` parameter), nothing we can do about it.

Regards,
Michal
