### ISSUE TITLE
Is there no way of distinguishing between a leaf list Val and a leaf Val? :(

### ISSUE THREAD

**Issue by andrei-pavel** [sysrepo/sysrepo#1578]
Question is generic - it seems to me like there's no way to do this in any scenario in a C++ Sysrepo subscriber. And I kind of needed this... :(
But to provide specifics, when using the `Session::get_changes_iter` & `Session::get_change_next` interface calls, I get SR_STRING_T for leaf-list values that follow this piece of YANG model:
```
    leaf-list subnets {
        type string;
    }
```
and no `S_Val` for the underlying elements. Or the other way around if you like... I get one `S_Val` for two elements. Is this behavior deliberate?

**Expected behavior:**
Maybe two `S_Val`s just like in a non-leaf list, but unlike it they would have the same xpath. Something like:
```
/a/b/c (leaf-list instance)
/a/b/c = "hello"
```

**Actual behavior:**
```
/a/b/c = "hello"
```

### Versions
netopeer2-server 0.7.13
sysrepod - sysrepo daemon, version 0.7.8
yanglint 1.1.36

### Attachments
This is a piece of log from my program that logs the changes.
```
2019-08-13 14:44:14.284 DEBUG configuration changed: created: /model:config/xpath[id='1'] (list instance)
2019-08-13 14:44:14.284 DEBUG configuration changed: created: /model:config/xpath[id='1']/id = 1
2019-08-13 14:44:14.284 DEBUG configuration changed: created: /model:config/xpath[id='1']/subnets = 2e8b:f54:f9:100::/56
2019-08-13 14:44:14.284 DEBUG configuration changed: created: /model:config/xpath[id='2'] (list instance)
2019-08-13 14:44:14.284 DEBUG configuration changed: created: /model:config/xpath[id='2']/id = 2
2019-08-13 14:44:14.284 DEBUG configuration changed: created: /model:config/xpath[id='2']/subnets = 2e8b:f54:f9:200::/56
```

* [X] Did you check if this is a duplicate issue?
* [ ] Did you test it on the latest sysrepo devel branch?

**Comment by andrei-pavel** [comment]
The logic seems to be:
```
if empty leaf list {
    notify SR_EMPTY_LEAF_T
} else {
    for each leaf {
        notify SR_STRING_T
    }
}
```

Another behavior that would help my cause could be:
```
notify SR_EMPTY_LEAF_T
for each leaf {
    notify SR_STRING_T
}
```

**Comment by andrei-pavel** [comment]
Actually the two proposed behaviors are identical, just differently presented.

**Comment by michalvasko** [comment]
Hi,
no, `sr_val_t` does not make a difference between *leaf* and *leaf-list*. The only way to learn that, I think, is to use the XPath in the value to get the node from a *libyang* context and learn the type from the schema node. This problem is fixed when using the new tree API in the new *sysrepo* because it returns *libyang* data trees directly, but there are no C++ bindings yet, so you cannot use it, sorry.

Regards,
Michal
