### ISSUE TITLE
sr_delete_item failed to delete the interface IP address in running datastore

### ISSUE THREAD

**Issue by nic1225** [sysrepo/sysrepo#1579]
hi.
ietf-interfaces running datastore has 2 IP address, I want to delete one of them, and the error occured as follows:

    sysrepod[1368]: [ERR] Commit timeout for commit id=273517995.
    sysrepo-sysrepo-plugind[1378]: [ERR] Error by processing of the commit request (session id=1787242662): Timeout has expired.
    sysrepo-sysrepo-plugind[1378]: [ERR] Commit operation failed with 0 error(s).
    sysrepo-sysrepo-plugind[1378]: [WRN] (ietf_ip_dhcp_client_if_ip_addr_sr_node_del:675) Error by sr_commit: Timeout has expired
                                               xpath: /ietf-interfaces:interfaces/interface[name='TenGigabitEthernet8/0/1']/ietf-ip:ipv4/address[ip='111.2.0.0']

my code as follows:

    /* connect to sysrepo */
    rc = sr_connect(app_name, SR_CONN_DEFAULT, &conn);
    if (SR_ERR_OK != rc) {
        CHECK_ZERO_ERR_GOTO_MSG(rc, clean, "connecting to sysrepod failed");
    }

    /* start session */
    rc = sr_session_start(conn, SR_DS_RUNNING, SR_SESS_DEFAULT, &sess);
    if (SR_ERR_OK != rc) {
        CHECK_ZERO_ERR_GOTO_MSG(rc, clean, "session start failed");
    }
    
    rc = sr_delete_item(sess, dhcp_client_if_ip_addr_item_xpath, SR_EDIT_DEFAULT);
    if (SR_ERR_OK != rc) {
       CHECK_ZERO_ERR_GOTO(rc, clean, "del dhcp client interface ip address sysrepo node failed for: %s, rc = %d", (char *)if_name, rc);
    }

    /* commit the changes */
    rc = sr_commit(sess);
    if (SR_ERR_OK != rc) {
        SRP_LOG_WRN("Error by sr_commit: %s\n xpath: %s\n", sr_strerror(rc), dhcp_client_if_ip_addr_item_xpath);
    }

running datastore as follows:

    <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
      <interface>
        <name>TenGigabitEthernet8/0/1</name>
        <description>TenGigabitEthernet8/0/1</description>
        <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
        <enabled>true</enabled>
        <ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip">
          <address>
            <ip>111.2.0.0</ip>
            <prefix-length>24</prefix-length>
          </address>
          <address>
            <ip>113.3.0.0</ip>
            <prefix-length>24</prefix-length>
          </address>
        </ipv4>
      </interface>
    </interfaces>

Sincerely,
nick

**Comment by michalvasko** [comment]
Hi Nick,
it seems to me your running data subscriber have simply timed out, what is subscribed to *ietf-interfaces* data?

Regards,
Michal

**Comment by nic1225** [comment]
Hi   Michal

Thanks for your reply,here are all ietf-interfaces's subscriptions in my code：

    rc = sr_subtree_change_subscribe(session, "/ietf-interfaces:interfaces/interface",
                                     ietf_interface_change_cb, g_vapi_ctx_instance, 0, SR_SUBSCR_CTX_REUSE | SR_SUBSCR_EV_ENABLED, subscription);

    rc = sr_subtree_change_subscribe(session, "/ietf-interfaces:interfaces/interface/v3po:ipsec",
                                     v3po_ipsec_interfaces_interface_ipsec_cb, g_vapi_ctx_instance, 99, SR_SUBSCR_CTX_REUSE | SR_SUBSCR_EV_ENABLED, subscription);

    rc = sr_subtree_change_subscribe(session, "/ietf-interfaces:interfaces/interface/v3po:loopback",
                                     ietf_interface_loopback_change_cb, g_vapi_ctx_instance, 95, SR_SUBSCR_CTX_REUSE | SR_SUBSCR_EV_ENABLED, subscription);

    rc = sr_subtree_change_subscribe(session, "/ietf-interfaces:interfaces/interface/ietf-ip:ipv4/address",
                                     ietf_interface_ipv46_address_change_cb, g_vapi_ctx_instance, 92, SR_SUBSCR_CTX_REUSE | SR_SUBSCR_EV_ENABLED, subscription);
 
    rc = sr_subtree_change_subscribe(session, "/ietf-interfaces:interfaces/interface/enabled",
                                     ietf_interface_enable_disable_cb, g_vapi_ctx_instance, 88, SR_SUBSCR_CTX_REUSE | SR_SUBSCR_EV_ENABLED, subscription);
  
    rc = sr_subtree_change_subscribe(session, "/ietf-interfaces:interfaces/interface/ietf-ip:ipv6/address",
                                     ietf_interface_ipv46_address_change_cb, g_vapi_ctx_instance, 91, SR_SUBSCR_CTX_REUSE | SR_SUBSCR_EV_ENABLED, subscription);
  
    rc = sr_subtree_change_subscribe(session, "/ietf-interfaces:interfaces/interface/ietf-ip:ipv4/mtu",
            ietf_interface_ipv46_mtu_change_cb, g_vapi_ctx_instance, 90, SR_SUBSCR_CTX_REUSE | SR_SUBSCR_EV_ENABLED, subscription);
  
    rc = sr_subtree_change_subscribe(session, "/ietf-interfaces:interfaces/interface/ietf-ip:ipv6/mtu",
            ietf_interface_ipv46_mtu_change_cb, g_vapi_ctx_instance, 89, SR_SUBSCR_CTX_REUSE | SR_SUBSCR_EV_ENABLED, subscription);

    rc = sr_dp_get_items_subscribe(session, "/ietf-interfaces:interfaces-state/interface",
                                   ietf_interface_state_cb, g_vapi_ctx_instance, /*SR_SUBSCR_DEFAULT*/ SR_SUBSCR_CTX_REUSE, subscription);

    rc = sr_subtree_change_subscribe(session, "/ietf-interfaces:interfaces/interface/v3po:routing",
                                 ietf_interface_vrf_change_cb, g_vapi_ctx_instance, 95, SR_SUBSCR_CTX_REUSE | SR_SUBSCR_EV_ENABLED, subscription);

    rc = sr_subtree_change_subscribe(session, "/ietf-interfaces:interfaces/interface/v3po:unnumbered",
                                   ietf_interface_unnumbered_change_cb, g_vapi_ctx_instance, 95, SR_SUBSCR_CTX_REUSE | SR_SUBSCR_EV_ENABLED, subscription);

in addition ，the IP address to be deleted is added  through the following methods, which can be successful, but there are some errors in log, I'm not sure if it has any impact on the delete operation above.

    value.type = SR_UINT8_T;
    value.data.uint8_val = prefix_len;
    rc = sr_set_item(sess, "/ietf-interfaces:interfaces/interface[name='TenGigabitEthernet8/0/1']/ietf-ip:ipv4/address[ip='111.2.0.0']", &value, SR_EDIT_DEFAULT);
    rc = sr_commit(sess);

errors as follows:

	sysrepod[9242]: [ERR] Failed to copy ns
	sysrepod[9242]: [ERR] Failed print config-change notif to string
	sysrepod[9242]: [ERR] Failed to save event notification
	sysrepod[9242]: [WRN] Error by processing of the message: Sysrepo-internal error.

Sincerely,
nick

**Comment by michalvasko** [comment]
Hi Nick,
the errors show you have something wrong with your installation, which may very well cause the original problem as well. My suggestion is to completely uninstall your *sysrepo* installation (`# make uninstall_with_repo`, check that there are no leftover `libsysrepo.so` or `/etc/sysrepo`, remove they if there are) and install it again.

Regards,
Michal
