### ISSUE TITLE
New sysrepo: sr_oper_get_items_subscribe doesn't work when the xpath is for a read-write container

### ISSUE THREAD

**Issue by huw305** [sysrepo/sysrepo#1580]
### Description
The yang model is as below. The container is read-write but includes a state data leaf.
```
module mytest 
{
  namespace "urn:sysrepo:mytest";
  prefix mt;
  container test-state 
  {
    list test-case
    {
      key name;
      leaf name 
      {
        type string;
      }
      leaf result 
      {
        type uint32;
        config false;
      }
    }
  }
}
```
The below xml file is imported by sysrepocfg to create three instances for the list "test-case", with the key name "one", "two" and "three":
```
<test-state xmlns="urn:sysrepo:mytest">
  <test-case>
    <name>one</name>
  </test-case>
  <test-case>
    <name>two</name>
  </test-case>
  <test-case>
    <name>three</name>
  </test-case>
</test-state>
```
The state data provider callback is subscribed by:
`sr_oper_get_items_subscribe(session, "mytest", "/mytest:test-state", mytest_state_cb, NULL, 0, &subscription);`

My test result shows the subscribed function "mytest_state_cb" is never called on a "get" command. The log is as below:
```
Aug  2 04:10:36 netopeer2-server[1075]: Resolving unresolved data nodes and their constraints...
Aug  2 04:10:36 netopeer2-server[1075]: All data nodes and constraints resolved.
Aug  2 04:10:36 netopeer2-server[1075]: Session 6 (user "root") created.
Aug  2 04:10:36 netopeer2-server[1075]: Resolving unresolved data nodes and their constraints...
Aug  2 04:10:36 netopeer2-server[1075]: All data nodes and constraints resolved.
Aug  2 04:10:36 netopeer2-server[1075]: Published event "rpc" with ID 2 priority 0 for 1 subscribers.
Aug  2 04:10:36 netopeer2-server[1075]: Processing "/ietf-netconf:get" "rpc" event with ID 2 priority 0 (remaining 1 subscribers).
Aug  2 04:10:36 netopeer2-server[1075]: Finished processing "rpc" event with ID 2 priority 0 (remaining 0 subscribers).
Aug  2 04:10:36 netopeer2-server[1075]: Event "rpc" with ID 2 priority 0 succeeded.
Aug  2 04:10:36 netopeer2-server[1075]: Resolving unresolved data nodes and their constraints...
Aug  2 04:10:36 netopeer2-server[1075]: All data nodes and constraints resolved.
Aug  2 04:10:36 netopeer2-server[1075]: Session 1: thread 0 event new RPC.
```

### Steps to Reproduce
1. sysrepoctl -i /var/tmp/mytest.yang
2. sysrepocfg --import=/var/tmp/mytest.xml -d startup -m mytest
3. Start netopeer2-server and netopeer2-cli, and send: get --filter-xpath /mytest:*

### Versions
netopeer2-server 1.0.1
libsysrepo.so.1.0.6
libyang.so.1.1.36

### Attachments
[https://github.com/sysrepo/sysrepo/files/3367314/mytest.zip
](url)

Thanks!

**Comment by huw305** [comment]
I tried to debug the code and here're some findings:
1. In function sr_module_oper_data_update @ modinfo.c, when processing the command "get --filter-xpath /mytest:*" I'm seeing the variable "sub_type" is SR_OPER_SUB_CONFIG thus the function sr_xpath_oper_data_append will not be called to request state data from the listen thread.
```
            else if ((shm_msub->sub_type == SR_OPER_SUB_MIXED) || (shm_msub->sub_type == SR_OPER_SUB_STATE)) {
                /* ds == SR_DS_STATE, we want only state data */
                if ((err_info = sr_xpath_oper_data_append(mod->ly_mod, xpath, sid, shm_msub->evpipe_num, NULL, 1, data,
                            cb_error_info))) {
                    return err_info;
                }
            }
```
2. In function sr_oper_get_items_subscribe @ sysrepo.c, when the xpath "/mytest:test-state" is subscribed, the variable "sub_type" is set to SR_OPER_SUB_CONFIG but it should be SR_OPER_SUB_MIXED because this subscribed container includes both read and write leaves.

**Comment by michalvasko** [comment]
Hi,
sorry for not replying sooner, I was away.

Anyway, I have tried it with the latest version and the callback was called, so it should be fixed now.

Regards,
Michal

**Comment by huw305** [comment]
Hi Michal, I tested your latest code, yes it solved my problem but I found:
1. if the subscribed xpath is "/mytest:test-state", the callback will be called.
2. if the subscribed xpath is "/mytest:test-state/test-case", the callback will NOT be called.

**Comment by michalvasko** [comment]
Hi,
you are right and now it should work properly.

Regards,
Michal

**Comment by huw305** [comment]
Thanks Michal, I confirm the problem has been fixed.

**Comment by blithe2015** [comment]
libsysrepo.so.5.5.12

**Comment by blithe2015** [comment]
I encountered the same problem.

version:
libyang.so.1.9.2
libsysrepo.so.5.5.12

yang tree:

module: cucc-sdwan-device-oper
  +--rw device-oper
     +--rw device-logic-id?           string
     +--rw build?                     string
     +--rw device-info-status
     |  +--rw rack?               uint8
     |  +--rw uuid?               string
     |  +--rw snid?               string
     |  +--rw device-type?        string
     |  +--rw device-model?       string
     |  +--rw mac-address?        string
     |  +--rw kernel-version?     string
     |  +--rw hardware-version?   string
     |  +--rw software-version?   string
     |  +--rw manufacturer?       string
     |  +--rw cpu-info?           string
     |  +--rw memory?             string
     |  +--rw pair-code?          string
     +--rw ports-info
     |  +--rw ports-info* [port-name]
     |     +--rw port-name      string
     |     +--rw description?   string
     |     +--rw port-type?     string
     |     +--rw enabled?       boolean
     |     +--rw run-status?    boolean
     |     +--rw ipv4* [ip]
     |        +--rw ip     inet:ipv4-address-no-zone
     |        +--rw mtu?   uint16

subscribe fun:

sr_oper_get_items_subscribe(session, "cucc-sdwan-device-oper", "cucc-sdwan-device-oper:device-oper/*",
											 sdwan_deviceinfo_get_cb, NULL, SR_SUBSCR_CTX_REUSE, &subscription);

**Comment by michalvasko** [comment]
You are using obsolete *libyang*/*sysrepo* versions that are no longer supported so I cannot help you, sorry.
