### ISSUE TITLE
libyang version

### ISSUE THREAD

**Issue by navya46** [sysrepo/sysrepo#1582]
Hi,
   Can u please suggest minimal libyang version used by Sysrepo. Because with 0.16.133 version it is working fine and if i use 0.16.105 then Sysrepo is getting crashed.

Below are the logs attached when sysrepo is started in daemon mode:
[DBG] Setting log level for stderr logs to 4.
[DBG] Connection Manager init started.
[DBG] Initiating circular buffer for 10 elements.
[DBG] Session Manager initialized successfully, ctx=0x5589f31ef480.
[DBG] Initializing sysrepo server at socket=/var/run/sysrepod.sock
[DBG] Request Processor init started.
[DBG] Initiating circular buffer for 10 elements.
[DBG] Circular buffer enqueue to position=0, current count=1.
[DBG] Notification store cleanup timer set up for 600 seconds.
[DBG] Notification Processor initialized successfully.
[INF] Initializing Data Manager, schema_search_dir=/etc/sysrepo/yang/, data_search_dir=/etc/sysrepo/data/
Segmentation fault (core dumped)

Thanks,
Navya

**Comment by michalvasko** [comment]
Hi Navya,
I do not know what specific change not included in `0.16.105` is causing the crash. Since this is not a generic issue with *libyang* I do not see the point of going through the versions and checking them individually, you can do that, too. Sorry.

Regards,
Michal
