### ISSUE TITLE
Question regarding augmentation in a state data provider callback

### ISSUE THREAD

**Issue by ranje93** [sysrepo/sysrepo#1583]
Hello,
So I have a scenario where in a data provider callback I am also returning some augmented leaves.
Currently, the client will get the augmented leaves even if he doesn't have the augmented module. So whenever it requests the original module, he will still get the augmented module.
Is there a way to implement a functionality where the client will receive the leaves which are relevant to him only?
Thanks in advance

**Comment by michalvasko** [comment]
Hi,
*sysrepo* does not know what schemas does a client support, it only has its own set of supported schemas and behaves accordingly. So, I am afraid what you want to achieve is not possible.

Regards,
Michal
