### ISSUE TITLE
Filling up startup datastore

### ISSUE THREAD

**Issue by Roky7250** [sysrepo/sysrepo#1585]
Hi, I'm new to sysrepo.
My question is: How to fill up startup datastore using functions from Tree Manipulation Utilities, before copy config from startup to running datastore is applied? I want to collect data from system using my own function for it, create tree using Tree Manipulation Utilities and then write that tree to startup datastore.

I'm currently filling up startup datastore using sysrepocfg:
sysrepocfg --import=test.xml --format=xml ietf-interfaces

Thanks in advance

**Comment by michalvasko** [comment]
Hi,
generally, it should work the other way around. Meaning that the `startup` configuration should be applied to the system. It makes sense to set `startup` configuration according to the system only once, after installing your device *sysrepo* handler/plugin. At that time you can do so either by standard `sr_set_item()` calls on `startup` datastore or use `sysrepocfg` just the way you did.

Regards,
Michal
