### ISSUE TITLE
Single configuration callback for multiple modules

### ISSUE THREAD

**Issue by rwestphal** [sysrepo/sysrepo#1586]
Hi all,

I've noticed that, when using NETCONF to edit configuration data from multiple modules at the same time, Sysrepo delivers the changes separately to the subscribing application. Example: `SR_EV_VERIFY` module A + `SR_EV_VERIFY` module B + `SR_EV_APPLY` module A + `SR_EV_APPLY` module B. From my perspective this behavior makes sense, considering that different calls to `sr_module_change_subscribe()` can pass different configuration callbacks.

Unfortunately, however, this behavior is a problem for application, which is also aware of configuration transactions (and Sysrepo support is implemented as a plugin). As such, all configuration changes from all modules need to be processed together (preferably in a single callback).

One way I think this could be implemented is by providing an alternate version of `sr_module_change_subscribe()` that accepts an array of module names, and all modules would share the same configuration callback. Do you think it would be possible to provide an API like this? If it can be made available in the new Sysrepo that would be a good reason for us (FRR) to migrate to it.

If you have other ideas on how to solve this problem that would be welcome as well!

Best Regards,
Renato.

**Comment by michalvasko** [comment]
Hi Renato,
both the old and new *sysrepo* were designed to have all modules (and their data) stored and handled separately for better efficiency. This feature significantly affected the whole *sysrepo* and its API so I am not sure it will be that easy to implement what you are asking for.

So it is not viable for a single callback to be set for both modules, which will then be called twice, once for each module?

Regards,
Michal
