### ISSUE TITLE
New Sysrepo: Missing SWIG (Python Bindings)

### ISSUE THREAD

**Issue by frimpler** [sysrepo/sysrepo#1590]
Hi,

apparently, the **swig** directory (and therefore the support of language bindings) is no longer available (or only temporarily unavailable?) in the devel branch.

Please give us an hint, what we could expect or should do in order to keep our existing python implementations after changing to the new design of sysrepo. 

Maybe some words about it in https://github.com/sysrepo/sysrepo/blob/devel/CHANGES could help, too.

Regards,
Frank

**Comment by rkrejci** [comment]
Hi Frank, Python 3 (and C++) bindings is planned, but probably not via SWIG. Currently we are deciding which technology/tool will be used to wrap the C library. We expect it at the end of this year.

**Comment by michalvasko** [comment]
Fixed.
