### ISSUE TITLE
Python callback dp_get_items failed with runtime error

### ISSUE THREAD

**Issue by Krushkov** [sysrepo/sysrepo#1591]
* [x] Did you check if this is a duplicate issue?
* [ ] Did you test it on the latest sysrepo devel branch?

### Description
When attempting to get operational data from config false container using a provider and requester provider crashes with runtime_error and requester gets Nonetype object.
From provider's console:
 ========== READING STARTUP CONFIG: ==========
 ========== STARTUP CONFIG APPLIED AS RUNNING ==========
terminate called after throwing an instance of 'std::runtime_error'
  what():  Python callback dp_get_items failed.
Aborted (core dumped)

### Steps to Reproduce
1. Fresh install on latest version of sysrepo
2. Run my_example.py script as provider (./my_example.py)
I used the ietf-interfaces module and "/ietf-interfaces:interfaces-state//*" as example xpath.
3. Run my_example.py script as requester(./my_example.py  ietf-interfaces  "/ietf-interfaces:interfaces-state//*" 
4. runtime_error

**Expected behavior:**
 Get actual operational state data from ietf-interfaces:ietf-interfaces-state

**Actual behavior:**
Crashes and doesn't execute the callback method. 

### Versions
Sysrepo version: version 0.7.8.
libyang version: yanglint 1.1.41
netopeer2-server: None

I used the oper_data_example.c example to understand how the code works
Then I modified one of the python examples to do almost exactly what oper_data_example does.
When using oper_data_example 
I changed the .c file
then I did make and make install
and run oper_data_example twice 
one for the provider with no params 
and one for the requester for any params. 
Then I received all the ietf-interfaces:interfaces-state data

Doing the same with my python code results in the runtime_error.   

### Attachments
sysrepod.log
[sysrepod.log](https://github.com/sysrepo/sysrepo/files/3569330/sysrepod.log)

my_example.py - the script in txt
[my_example.py.txt](https://github.com/sysrepo/sysrepo/files/3569378/my_example.py.txt)

oper_data_example.c text copy of the example I modified a little to first test how the cb method works
[oper_data_example.c.txt](https://github.com/sysrepo/sysrepo/files/3569348/oper_data_example.c.txt)

**Comment by Krushkov** [comment]
@michalvasko Is anyone going to look into this issue ?

**Comment by michalvasko** [comment]
Hi,
sorry for not replying but it is up to @lperkov to help you, if he can. I am not able to provide much support with the Python bindings.

Regards,
Michal

**Comment by Krushkov** [comment]
We found the problem. It was in our code when transitioning from python2 to python3.
