### ISSUE TITLE
[New-Sysrepo][sysrepocfg,sysrepoctl] Commands crash when invalid parameters given

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1594]
Hi,

In `sysrepoctl` and `sysrepocfg` commands giving any unknown parameters causing the crash

eg.
```
sysrepoctl --version
sysrepocfg --version
```
In both executables termination of `options[]` array with `NULL` data is missing. Please fix.

Ref:https://linux.die.net/man/3/getopt_long

Will it be possible to add a parameter to print sysrepo library/.so version using both commands?

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
I have added the features you requested.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thank you issue fixed and new features working fine.
