### ISSUE TITLE
two question about sysrepo callback timeout 

### ISSUE THREAD

**Issue by nic1225** [sysrepo/sysrepo#1595]
hi.
    We enable a timed polling task in the sysrep-plugin, which can cause sysrepo callback timeout problems if the task runs just in time to block the sysrepo callback.Is there any solution as follows.

  If there is an API_1 in sysrepo that determines whether the currently running code is in the callback context, such as `bool in_sysrepo_callback_context()`, the task calls this function first, and if it return true, waits for a while before executing.

  There is also an API_2 (such as `lock_sysrepo_callback()` and `unlock_sysrepo_callback()`) to block callback occurrences for a while. For example, in my polling task run, the blocking sysrepo callback  `lock_sysrepo_callback() ` is called first, and the blocking rollback function `unlock_sysrepo_callback()`  is turned off after the task completes.

Thanks!
Nick

**Comment by michalvasko** [comment]
Hi Nick,
are you talking about the old (`master`) *sysrepo*? If so, then there are many problems with its thread mechanism but they will not be fixed.

Regards,
Michal

**Comment by nic1225** [comment]
Hi michalvasko:

   Which is old (master) sysrepo?  We are using release version 0.7.7.
     
Thanks!
Nick

**Comment by michalvasko** [comment]
Hi Nick,
yes, *sysrepo* version 0.7.8 or lower is the old *sysrepo* (found in `master` branch). The new *sysrepo* is in `devel` (version 1.0 and higher).

Regards,
Michal

**Comment by nic1225** [comment]
Hi michalvasko:
      
         Is there a release version of the new sysrepo devel version？Or when there will be a release one

Thanks!
Nick

**Comment by michalvasko** [comment]
Hi Nick,
there is no release version of the new *sysrepo* and I cannot tell you yet when will be. It is ready but there are no language bindings for now and we have not decided whether we want to release it without them or not, we are currently assessing how much time it would take to write them.

Regards,
Michal

**Comment by nic1225** [comment]
hi,Michal：
    when using  new sysrepo devel, which version of netopeer2-server should be match, netopeer2 v0.7-r2 is ok?

Thanks!
Nick

**Comment by michalvasko** [comment]
Hi Nick,
nope, if using *sysrepo* `devel`, you need *libnetconf2* `devel` and *netopeer2* `devel-server`. You can use either `master` or `devel` of *libyang*, there is no difference there.

Regards,
Michal
