### ISSUE TITLE
Question regarding data provider callback performance

### ISSUE THREAD

**Issue by ranje93** [sysrepo/sysrepo#1596]
Hi,
I would like to increase the performance in a data provider callback.
the model is: `microwave-model`
link: 

> https://github.com/OpenNetworkingFoundation/5G-xHaul/blob/master/models/yang/microwave-model.yang

What I want to return is:
The container `air-interface-historical-performances` with `95` lists of `historical-performance-data-list`, within the list I don't use all the attributes, only about `10 `of them are returned.
 and I do all this for 2 `mw-air-interface-pac` objects
So this is roughly `~1900 `entries that needs to be returned.

This overall time that it took the machine was about `~40` seconds.
From what I measured, most of the code that I wrote to get the data takes around `3-4` seconds, and all the rest of the time is for the internal work of sysrepo as well as netopeer2-server.

My question is, does sysrepo use the disk when it handles data provider callbacks? and if so, is it possible to use RAM only?
Also, is there any advice to increase the performance overall?

Thanks in advance

**Comment by michalvasko** [comment]
Hi,
if you have any performance problems, use the new *sysrepo* from `devel` branch (requires `devel` of *libnetconf2* and *netopeer2*). The current `master` *sysrepo* will not be improved anymore.

Regards,
Michal
