### ISSUE TITLE
New Sysrepo: Issues with the installation of sub-modules 

### ISSUE THREAD

**Issue by frimpler** [sysrepo/sysrepo#1599]
Hi Michal & Radek

The installation of a simple yang module, which includes a sub-module seems to put sysrepo's tooling into a strange state. The installation itself shows no (visible) issues. But the invocation of sysrepoctl -l does not reliably work, anymore, afterwards.

Here the yang modules I played with:

```
module fri-ques {

   namespace "urn:fri:ques";
   prefix iq;

   include fri-que-ifcs;
}

submodule fri-que-ifcs {
  belongs-to fri-ques {
    prefix iq;
  }

  container ques {
    list que {
      key que-num;
      leaf que-num {
        type int8;
      }
    }
  }
}

```

> 1.) invocation from somewhere: sysrepoctl -l seems not to work, anymore.

> sysrepoctl -v 4 -i /git/yang/fri-ques.yang -s /git/yang
> [INF]: Libyang internal module "yang" was installed.
> [INF]: Module file "ietf-yang-library@2019-01-04" installed.
> [INF]: Libyang internal module "ietf-yang-library" was installed.
> [INF]: Module file "ietf-netconf@2011-06-01" installed.
> [INF]: Module file "ietf-netconf-with-defaults@2011-06-01" installed.
> [INF]: Sysrepo internal module "ietf-netconf-with-defaults" was installed.
> [INF]: Sysrepo internal dependency module "ietf-netconf" was installed.
> [INF]: Module file "ietf-netconf-notifications@2012-02-06" installed.
> [INF]: Sysrepo internal module "ietf-netconf-notifications" was installed.
> [INF]: Module file "fri-ques" installed.
> [INF]: Module "fri-ques" was installed.
> sysrepoctl -l
> libyang[0]: Data model "fri-que-ifcs" not found.
> libyang[0]: Invalid value "fri-que-ifcs" of "include".
> libyang[0]: Including "fri-que-ifcs" module into "fri-ques" failed.
> libyang[0]: Module "fri-ques" parsing failed.
> sysrepoctl error: Failed to connect (libyang error)
> 

> 2.) invocation from inside the schema file's directory: sysrepoctl -l seems still to work (but changing the directory brings the same errors as above)
> sysrepoctl -v 4 -i fri-ques.yang
> [INF]: Libyang internal module "yang" was installed.
> [INF]: Module file "ietf-yang-library@2019-01-04" installed.
> [INF]: Libyang internal module "ietf-yang-library" was installed.
> [INF]: Module file "ietf-netconf@2011-06-01" installed.
> [INF]: Module file "ietf-netconf-with-defaults@2011-06-01" installed.
> [INF]: Sysrepo internal module "ietf-netconf-with-defaults" was installed.
> [INF]: Sysrepo internal dependency module "ietf-netconf" was installed.
> [INF]: Module file "ietf-netconf-notifications@2012-02-06" installed.
> [INF]: Sysrepo internal module "ietf-netconf-notifications" was installed.
> [INF]: Module file "fri-ques" installed.
> [INF]: Module "fri-ques" was installed.
> sysrepoctl -l
```
Sysrepo repository: /bld/sysrepo/repository

Module Name                | Revision   | Flags | Owner            | Permissions | Submodules    | Features
-----------------------------------------------------------------------------------------------------------
fri-ques                   |            | I     | frimpler:nogroup | 600         |  fri-que-ifcs |
ietf-netconf               | 2011-06-01 | I     | frimpler:nogroup | 600         |               |
ietf-netconf-notifications | 2012-02-06 | I     | frimpler:nogroup | 600         |               |
ietf-netconf-with-defaults | 2011-06-01 | I     | frimpler:nogroup | 600         |               |
ietf-yang-library          | 2019-01-04 | I     | frimpler:nogroup | 600         |               |
yang                       | 2017-02-20 | I     | frimpler:nogroup | 600         |               |
```

It seems, after installing the module+sub-module, sysrepoctl -l "works" only when being invoked from inside the schema file's directory. What concerns me further is, that I don't see the yang file for the sub-module installed under /bld/sysrepo/repository/yang. So therefore I suspect a "real" installation problem and not only a "show" issue!

Btw.: that's the commit I see: cfec80a3

Regards,
Frank

**Comment by michalvasko** [comment]
Hi Frank,
submodules were not being stored at all, please try again now.

Regards,
Michal

**Comment by frimpler** [comment]
Hi Michal,

looks good. 

Thanks!
