### ISSUE TITLE
[nacm] callbacks are not invoked for ietf-netconf-acm module after booting

### ISSUE THREAD

**Issue by veereshsaj** [sysrepo/sysrepo#1602]
Hi,

when I subscribe for ietf-netconf-acm changes, the configuration is copied from startup to running but callbacks are not invoked for the first time. 
And when I unsubscribe the module and subscribe back, then only the callbacks are being invoked.
[ I have verified that the SR_SUBSCR_EV_ENABLED flag is used to reflect the configuration changes to subscribers.]
 
Could you please look into the issue.

Thanks & Regards,
Veeresh

**Comment by michalvasko** [comment]
Hi Veeresh,
I am sorry, but we support the old *sysrepo* only in the form of (simple) bug fixes. This is a behavior change, so it will not be changed.

Regards,
Michal
