### ISSUE TITLE
ietf-interfaces wrong data type in startup

### ISSUE THREAD

**Issue by maksimvuleta** [sysrepo/sysrepo#1604]
I have a function to fill up xml file and import this file as ietf-interfaces yang module startup.
My issue is related to filling up ietf-interfaces/interface/type node.

The list interface is created successfully with the key node name. 
The value of node type in my xml file is set like <type>ianaift:ethernetCsmacd</type>.
The same value worked with my transapi module, and does not work for sysrepo-plugin.

Here is the list of imported and installed plugins:
devel@ubuntu:~/smb_share/sysrepo-plugins-work/ietf-interfaces-yang-module/build$ sudo sysrepoctl --list
Sysrepo schema directory: /etc/sysrepo/yang/
Sysrepo data directory:   /etc/sysrepo/data/
(Do not alter contents of these directories manually)

Module Name                | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
ietf-netconf-notifications | 2012-02-06 | Installed   | root:root           | 666         |                               |
ietf-netconf               | 2011-06-01 | Installed   | root:root           | 666         |                               | writable-running candidate rollback-on-error validate startup xpath
ietf-netconf-acm           | 2018-02-14 | Imported    |                     |             |                               |
nc-notifications           | 2008-07-14 | Installed   | root:root           | 666         |                               |
notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |
ieee802-dot1q-types        | 2018-03-07 | Imported    |                     |             |                               |
ietf-netconf-with-defaults | 2011-06-01 | Installed   |                     |             |                               |
ietf-netconf-monitoring    | 2010-10-04 | Installed   | root:root           | 666         |                               |
ietf-yang-library          | 2019-01-04 | Installed   | root:root           | 666         |                               |
ietf-datastores            | 2017-08-17 | Imported    |                     |             |                               |
ietf-x509-cert-to-name     | 2014-12-10 | Installed   |                     |             |                               |
ietf-keystore              | 2016-10-31 | Installed   | root:root           | 666         |                               |
iana-if-type               | 2017-01-19 | Installed   |                     |             |                               |
ietf-interfaces            | 2018-02-20 | Installed   | root:root           | 666         |                               |

When I start the sysrepo-plugin, the error is: 
libyang[0]: Failed to resolve identityref "ianaift:ethernetCsmacd". (path: /ietf-interfaces:interfaces/interface[name='lo']/type)

**Comment by maksimvuleta** [comment]
If I do it like this:
node = lyd_new_leaf(parent, module, "type", "iana-if-type:ethernetCsmacd");
Still does not work, the same error.

I am not sure did I understand correctly?

**Comment by michalvasko** [comment]
Hi,
yes, that must work as long as you have `iana-if-type` module loaded and implemented in the *libyang* context of `parent`/`module`.

Regards,
Michal

**Comment by maksimvuleta** [comment]
Thank you for fast responses.
It works now, I did not have iana-if-type module loaded. 
When I add the ` ly_ctx_load_module(ctx, "iana-if-type", NULL)` to my code, everything work.
