### ISSUE TITLE
Timeout issue on RPC

### ISSUE THREAD

**Issue by v-chanikya** [sysrepo/sysrepo#1609]
Hi Michal,

## Issue
I have a couple of RPC which take greater than 5 min and there are others which take less thank 2 min.
When I invoked these (>5min) RPC's through netconf client, the netconf server is returning with the error message timeout has expired, but my RPC is still running on the system.
I went through the code and found that an timeout option is set on the socket  /var/run/sysrepo.sock in client library  to a value in SR_REQUEST_TIMEOUT which is defaulted to 120 sec. 
I would like to how to address this issue without changing the SR_REQUEST_TIMEOUT as most of the other RPC's and config execute with in that time.

## Feature request:
I would like to have a configurable timeout parameters for each RPC during subscription.

## version
sysrepo: 0.7.8

Thanks

**Comment by michalvasko** [comment]
Hi,
we do not accept feature requests for the old *sysrepo* anymore. Anyway, why don't you simply increase the `REQUEST_TIMEOUT`, it matters not that other RPCs will be finished much sooner.

Regards,
Michal

**Comment by v-chanikya** [comment]
Hi,
I am assuming that the timeout is in place to safeguard (the person invoking the RPC) against the failures in RPC callbacks or in sysrepo. In that case I cannot increase the timeout to 10 min as it will be applied globally and the user would not know if the RPC succeeded or failed until 10 min have elapsed. So I cannot change request timeout.

Could you suggest any way I can over come the above scenario.

Also can this feature request be added to the latest sysrepo.

Thanks,
Chanikya

**Comment by michalvasko** [comment]
Hi Chanikya,
in that case no, I do not think there is a way how to achieve what you want in the old *sysrepo*. As for the new one, I will think about adding a customized timeout for every RPC sent.

Regards,
Michal
