### ISSUE TITLE
make fails with PROTOBUFC_PROTOC_EXECUTABLE-NOTFOUND: command not found

### ISSUE THREAD

**Issue by iGovindY** [sysrepo/sysrepo#1610]
* [x] Did you check if this is a duplicate issue?

### Description
make fails with below prints.
/bin/sh: PROTOBUFC_PROTOC_EXECUTABLE-NOTFOUND: command not found

### Steps to Reproduce
1. cd build
2. cmake -DEV_LIBRARY=/usr/lib64/libev.so.4 -DEV_INCLUDE_DIR=/usr/include -DPROTOBUF-C_LIBRARY=/usr/lib64/lib64/libprotobuf-c.so.1 -DPROTOBUF-C_INCLUDE_DIR=/usr/include -DPYTHON_LIBRARIES=/usr/lib64/libpython2.7.so.1.0 -DPYTHON_INCLUDE_DIRS=/usr/include -DCMAKE_BUILD_TYPE=Debug ..
3. make
[  0%] Running C protocol buffer compiler on /home/sysrepo/src/sysrepo.proto
/bin/sh: PROTOBUFC_PROTOC_EXECUTABLE-NOTFOUND: command not found
make[2]: *** [src/common/sysrepo.pb-c.c] Error 127
make[1]: *** [src/CMakeFiles/COMMON.dir/all] Error 2
make: *** [all] Error 2

### Versions
yanglint 1.1.52

**Comment by michalvasko** [comment]
Hi,
if you are specifying the paths manually, you are missing one. In my case it would be `-DPROTOBUFC_PROTOC_EXECUTABLE=/usr/bin/protoc-c`.

Regards,
Michal

**Comment by iGovindY** [comment]
Hi Michal,

Thanks for your reply.
Now make is not able to find protobuf-c/protobuf-c.h
and fails with below prints.
build]# `make`
[  1%] Building C object src/CMakeFiles/COMMON.dir/common/sysrepo.pb-c.c.o
In file included from /home<XYZ>sysrepo/build/src/common/sysrepo.pb-c.c:9:0:
/home<XYZ>sysrepo/build/src/common/sysrepo.pb-c.h:7:35: fatal error: protobuf-c/protobuf-c.h: No such file or directory
 #include <protobuf-c/protobuf-c.h>
                                   ^
compilation terminated.
make[2]: *** [src/CMakeFiles/COMMON.dir/common/sysrepo.pb-c.c.o] Error 1
make[1]: *** [src/CMakeFiles/COMMON.dir/all] Error 2
make: *** [all] Error 2


build]# `protoc-c --version`
protobuf-c 1.0.2
libprotoc 2.5.0

**Comment by michalvasko** [comment]
Hi,
it is because you are not defining `PROTOBUF-C_INCLUDE_DIR` properly. Why are you even setting all those paths manually? Still, if you do, it is your responsibility to set them correctly. Obviously, (based on the error) you need to find the directory with `protobuf-c/protobuf-c.h` and it is not `/usr/include`. If you cannot find it that means you do not have `protobuf-c` installed properly.

Regards,
Michal

**Comment by iGovindY** [comment]
Thank Michal for the help.

protobuf-c installation had some issues.
It was not placing protobuf-c.h at all.
