### ISSUE TITLE
Handling callbacks from the application's main thread using Python APIs

### ISSUE THREAD

**Issue by matth65** [sysrepo/sysrepo#1611]
Hello,

Syrepo provides sr_fd_watcher_xyz() and local_fd_watcher 'C' APIs for processing callbacks from the application's main thread, rather than processing callbacks from a Sysrepo thread. I looked at the documentation and Sysrepo.py, but it is not clear to me how this would be done using the Python APIs provided by Sysrepo.

Is there a way to process Sysrepo callbacks from the application's main thread using the Python APIs?

**Comment by michalvasko** [comment]
Hi,
I do not know much about the Python bindings, but looking at `sysrepo/swig/python/examples/python_application_example.py` and the function call `sr.global_loop()`, I think it works the way you want it to by default.

Regards,
Michal
