### ISSUE TITLE
Seg fault caused by illegal read in history memory in Docker image

### ISSUE THREAD

**Issue by XXAmethystXX** [sysrepo/sysrepo#1613]
Hello!
In the latest sysrepo-netopeer2 Docker image from Docker hub, running netopeer2-cli causes a segmentation fault.
I have checked the latest version of Netopee2 and found that the problem has been fixed (see patch https://github.com/CESNET/Netopeer2/commit/04659bb26d328de55d49ece5aa59af7c4ea65320).

Would it be possible to update the Docker image to include this patched version?

Thanks!

**Comment by lpaulic** [comment]
Hello @XXAmethystXX, 

I have updated the https://hub.docker.com/r/sartura/sysrepo-netopeer2 docker image. It now includes the patch  https://github.com/CESNET/Netopeer2/commit/04659bb26d328de55d49ece5aa59af7c4ea65320

If there is still an issue please let me know.

Regards.

**Comment by XXAmethystXX** [comment]
What about this other one?

https://hub.docker.com/r/sysrepo/sysrepo-netopeer2/

**Comment by lpaulic** [comment]
Hello @XXAmethystXX,

Thank you for pointing the Docker image out. It should be updated now. I have updated the latest tag only for now.

If there aren't any more issues please do tell so I cam close this issue.

Regards.

**Comment by XXAmethystXX** [comment]
Hello @lpaulic,

Thank you for updating the Docker image.
I am experiencing a different problem now, not sure if it's related, but it was not happening with the old image.
Now, when I run the container with `docker run -it --name sysrepo -p 830:830 --rm sysrepo/sysrepo-netopeer2:latest`, I get this output:

> 2019-09-30 07:29:44,648 CRIT Supervisor running as root (no user in config file)
> 2019-09-30 07:29:44,649 INFO supervisord started with pid 1
> 2019-09-30 07:29:45,651 INFO spawned: 'sysrepod' with pid 8
> 2019-09-30 07:29:45,653 INFO spawned: 'sysrepo-plugind' with pid 9
> 2019-09-30 07:29:45,654 INFO spawned: 'netopeer2-server' with pid 10
> 2019-09-30 07:29:45,661 DEBG 'sysrepod' stdout output:
> [WRN] Unable to acquire the lock on fd 6: 
> [ERR] Unable to lock sysrepo-module-dependencies.lyb data file.
> 
> 2019-09-30 07:29:45,661 DEBG 'sysrepod' stdout output:
> [ERR] Failed to initialize Module Dependencies context.
> [ERR] Data Manager initialization failed.
> 
> 2019-09-30 07:29:45,662 DEBG 'sysrepod' stdout output:
> [ERR] Cannot initialize Request Processor.
> 
> 2019-09-30 07:29:45,662 DEBG 'netopeer2-server' stdout output:
> [ERR]: Connecting to sysrepo failed (The peer disconnected).
> [ERR]: Server init failed.
> [ERR]: nc_ps_session_count: invalid argument (ps).
> 
> 2019-09-30 07:29:45,662 DEBG 'sysrepod' stdout output:
> [ERR] Unable to initialize Connection Manager: Sysrepo-internal error.
> 
> 2019-09-30 07:29:45,662 DEBG fd 6 closed, stopped monitoring <POutputDispatcher at 139989740278488 for <Subprocess at 139989740279352 with name sysrepod in state STARTING> (stdout)>
> 2019-09-30 07:29:45,662 INFO exited: sysrepod (exit status 1; not expected)
> 2019-09-30 07:29:45,662 DEBG fd 13 closed, stopped monitoring <POutputDispatcher at 139989740170920 for <Subprocess at 139989740278632 with name netopeer2-server in state STARTING> (stdout)>
> 2019-09-30 07:29:45,662 INFO exited: netopeer2-server (exit status 1; not expected)
> 2019-09-30 07:29:45,662 DEBG received SIGCLD indicating a child quit
> 2019-09-30 07:29:45,662 DEBG 'sysrepo-plugind' stdout output:
> [ERR] Error by receiving of the message: .
> [ERR] Unable to receive the message with response (operation=version-verify).
> [ERR] Unable to connect to sysrepod: The peer disconnected
> 
> 2019-09-30 07:29:45,662 DEBG fd 9 closed, stopped monitoring <POutputDispatcher at 139989740278920 for <Subprocess at 139989740279208 with name sysrepo-plugind in state STARTING> (stdout)>
> 2019-09-30 07:29:45,662 INFO exited: sysrepo-plugind (exit status 1; not expected)
> 2019-09-30 07:29:45,662 DEBG received SIGCLD indicating a child quit
> 2019-09-30 07:29:46,665 INFO spawned: 'sysrepod' with pid 11
> 2019-09-30 07:29:46,666 INFO spawned: 'sysrepo-plugind' with pid 12
> 2019-09-30 07:29:46,667 INFO spawned: 'netopeer2-server' with pid 13
> 2019-09-30 07:29:46,675 DEBG 'sysrepod' stdout output:
> [WRN] Unable to acquire the lock on fd 6: 
> [ERR] Unable to lock sysrepo-module-dependencies.lyb data file.
> 
> 2019-09-30 07:29:46,675 DEBG 'sysrepod' stdout output:
> [ERR] Failed to initialize Module Dependencies context.
> [ERR] Data Manager initialization failed.
> 
> 2019-09-30 07:29:46,675 DEBG 'sysrepod' stdout output:
> [ERR] Cannot initialize Request Processor.
> 
> 2019-09-30 07:29:46,675 DEBG 'sysrepo-plugind' stdout output:
> [ERR] Error by receiving of the message: .
> [ERR] Unable to receive the message with response (operation=version-verify).
> [ERR] Unable to connect to sysrepod: The peer disconnected
> 
> 2019-09-30 07:29:46,675 DEBG 'sysrepod' stdout output:
> [ERR] Unable to initialize Connection Manager: Sysrepo-internal error.
> 
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 81, in emit
>     self.stream.write(msg)
> IOError: [Errno 4] Interrupted system call
> 2019-09-30 07:29:46,676 DEBG 'netopeer2-server' stdout output:
> [ERR]: Connecting to sysrepo failed (The peer disconnected).
> [ERR]: Server init failed.
> [ERR]: nc_ps_session_count: invalid argument (ps).
> 
> 2019-09-30 07:29:46,676 DEBG fd 6 closed, stopped monitoring <POutputDispatcher at 139989740714536 for <Subprocess at 139989740279352 with name sysrepod in state STARTING> (stdout)>
> 2019-09-30 07:29:46,676 INFO exited: sysrepod (exit status 1; not expected)
> 2019-09-30 07:29:46,676 INFO exited: sysrepo-plugind (exit status 1; not expected)
> 2019-09-30 07:29:46,676 DEBG fd 14 closed, stopped monitoring <POutputDispatcher at 139989740278344 for <Subprocess at 139989740278632 with name netopeer2-server in state STARTING> (stdout)>
> 2019-09-30 07:29:46,676 INFO exited: netopeer2-server (exit status 1; not expected)
> 2019-09-30 07:29:46,676 DEBG received SIGCLD indicating a child quit
> 2019-09-30 07:29:48,679 INFO spawned: 'sysrepod' with pid 14
> 2019-09-30 07:29:48,681 INFO spawned: 'sysrepo-plugind' with pid 15
> 2019-09-30 07:29:48,682 INFO spawned: 'netopeer2-server' with pid 16
> 2019-09-30 07:29:48,684 DEBG 'sysrepo-plugind' stdout output:
> [ERR] Sysrepo daemon not detected while library mode disallowed.
> [ERR] Unable to connect to sysrepod: The peer disconnected
> 
> 2019-09-30 07:29:48,684 DEBG fd 9 closed, stopped monitoring <POutputDispatcher at 139989739893824 for <Subprocess at 139989740279208 with name sysrepo-plugind in state STARTING> (stdout)>
> 2019-09-30 07:29:48,684 INFO exited: sysrepo-plugind (exit status 1; not expected)
> 2019-09-30 07:29:48,684 DEBG received SIGCLD indicating a child quit
> 2019-09-30 07:29:48,691 DEBG 'sysrepod' stdout output:
> [WRN] Unable to acquire the lock on fd 6: 
> [ERR] Unable to lock sysrepo-module-dependencies.lyb data file.
> 
> 2019-09-30 07:29:48,691 DEBG 'sysrepod' stdout output:
> [ERR] Failed to initialize Module Dependencies context.
> [ERR] Data Manager initialization failed.
> 
> 2019-09-30 07:29:48,692 DEBG 'sysrepod' stdout output:
> [ERR] Cannot initialize Request Processor.
> 
> 2019-09-30 07:29:48,692 DEBG 'netopeer2-server' stdout output:
> [ERR]: Connecting to sysrepo failed (The peer disconnected).
> [ERR]: Server init failed.
> 
> 2019-09-30 07:29:48,692 DEBG 'sysrepod' stdout output:
> [ERR] Unable to initialize Connection Manager: Sysrepo-internal error.
> 
> 2019-09-30 07:29:48,692 DEBG 'netopeer2-server' stdout output:
> [ERR]: nc_ps_session_count: invalid argument (ps).
> 
> 2019-09-30 07:29:48,692 DEBG fd 6 closed, stopped monitoring <POutputDispatcher at 139989740714536 for <Subprocess at 139989740279352 with name sysrepod in state STARTING> (stdout)>
> 2019-09-30 07:29:48,692 INFO exited: sysrepod (exit status 1; not expected)
> 2019-09-30 07:29:48,692 DEBG fd 13 closed, stopped monitoring <POutputDispatcher at 139989740278488 for <Subprocess at 139989740278632 with name netopeer2-server in state STARTING> (stdout)>
> 2019-09-30 07:29:48,692 INFO exited: netopeer2-server (exit status 1; not expected)
> 2019-09-30 07:29:48,692 DEBG received SIGCLD indicating a child quit
> 2019-09-30 07:29:51,697 INFO spawned: 'sysrepod' with pid 17
> 2019-09-30 07:29:51,699 INFO spawned: 'sysrepo-plugind' with pid 18
> 2019-09-30 07:29:51,700 INFO spawned: 'netopeer2-server' with pid 19
> 2019-09-30 07:29:51,711 DEBG 'sysrepod' stdout output:
> [WRN] Unable to acquire the lock on fd 6: 
> [ERR] Unable to lock sysrepo-module-dependencies.lyb data file.
> [ERR] Failed to initialize Module Dependencies context.
> [ERR] Data Manager initialization failed.
> 
> 2019-09-30 07:29:51,712 DEBG 'sysrepo-plugind' stdout output:
> [ERR] Error by receiving of the message: .
> [ERR] Unable to receive the message with response (operation=version-verify).
> [ERR] Unable to connect to sysrepod: The peer disconnected
> 
> 2019-09-30 07:29:51,712 DEBG 'netopeer2-server' stdout output:
> [ERR]: Connecting to sysrepo failed (The peer disconnected).
> [ERR]: Server init failed.
> [ERR]: nc_ps_session_count: invalid argument (ps).
> 
> 2019-09-30 07:29:51,712 DEBG 'sysrepod' stdout output:
> [ERR] Cannot initialize Request Processor.
> [ERR] Unable to initialize Connection Manager: Sysrepo-internal error.
> 
> 2019-09-30 07:29:51,712 DEBG fd 6 closed, stopped monitoring <POutputDispatcher at 139989740714320 for <Subprocess at 139989740279352 with name sysrepod in state STARTING> (stdout)>
> 2019-09-30 07:29:51,713 INFO exited: sysrepod (exit status 1; not expected)
> 2019-09-30 07:29:51,713 DEBG fd 10 closed, stopped monitoring <POutputDispatcher at 139989740278488 for <Subprocess at 139989740279208 with name sysrepo-plugind in state STARTING> (stdout)>
> 2019-09-30 07:29:51,713 INFO exited: sysrepo-plugind (exit status 1; not expected)
> 2019-09-30 07:29:51,713 DEBG fd 14 closed, stopped monitoring <POutputDispatcher at 139989740278056 for <Subprocess at 139989740278632 with name netopeer2-server in state STARTING> (stdout)>
> 2019-09-30 07:29:51,713 INFO exited: netopeer2-server (exit status 1; not expected)
> 2019-09-30 07:29:51,713 DEBG received SIGCLD indicating a child quit
> 2019-09-30 07:29:51,713 INFO gave up: sysrepod entered FATAL state, too many start retries too quickly
> 2019-09-30 07:29:51,713 INFO gave up: sysrepo-plugind entered FATAL state, too many start retries too quickly
> 2019-09-30 07:29:51,713 INFO gave up: netopeer2-server entered FATAL state, too many start retries too quickly


This is what I get with the old image instead (which seems fine):

> 2019-09-30 07:30:35,689 CRIT Supervisor running as root (no user in config file)
> 2019-09-30 07:30:35,691 INFO supervisord started with pid 1
> 2019-09-30 07:30:36,693 INFO spawned: 'sysrepod' with pid 8
> 2019-09-30 07:30:36,694 INFO spawned: 'sysrepo-plugind' with pid 9
> 2019-09-30 07:30:36,695 INFO spawned: 'netopeer2-server' with pid 10
> 2019-09-30 07:30:36,717 DEBG 'sysrepod' stdout output:
> [WRN] Unable to delete existing rpc subscriptions.
> 
> 2019-09-30 07:30:36,720 DEBG 'sysrepod' stdout output:
> [WRN] Unable to delete existing rpc subscriptions.
> 
> 2019-09-30 07:30:36,723 DEBG 'sysrepo-plugind' stdout output:
> current turing-machine configuration:
> /turing-machine:turing-machine/transition-function/delta[label='left summand'] (list instance)
> /turing-machine:turing-machine/transition-function/delta[label='left summand']/label = left summand
> /turing-machine:turing-machine/transition-function/delta[label='left summand']/input (container)
> /turing-machine:turing-machine/transition-function/delta[label='left summand']/input/state = 0
> /turing-machine:turing-machine/transition-function/delta[label='left summand']/input/symbol = 1
> /turing-machine:turing-machine/transition-function/delta[label='left summand']/output (container)
> /turing-machine:turing-machine/transition-function/delta[label='left summand']/output/head-move = right [default]
> /turing-machine:turing-machine/transition-function/delta[label='separator'] (list instance)
> /turing-machine:turing-machine/transition-function/delta[label='separator']/label = separator
> /turing-machine:turing-machine/transition-function/delta[label='separator']/input (container)
> /turing-machine:turing-machine/transition-function/delta[label='separator']/input/state = 0
> /turing-machine:turing-machine/transition-function/delta[label='separator']/input/symbol = 0
> /turing-machine:turing-machine/transition-function/delta[label='separator']/output (container)
> /turing-machine:turing-machine/transition-function/delta[label='separator']/output/state = 1
> /turing-machine:turing-machine/transition-function/delta[label='separator']/output/symbol = 1
> /turing-machine:turing-machine/transition-function/delta[label='separator']/output/head-move = right [default]
> /turing-machine:turing-machine/transition-function/delta[label='right summand'] (list instance)
> /turing-machine:turing-machine/transition-function/delta[label='right summand']/label = right summand
> /turing-machine:turing-machine/transition-function/delta[label='right summand']/input (container)
> /turing-machine:turing-machine/transition-function/delta[label='right summand']/input/state = 1
> /turing-machine:turing-machine/transition-function/delta[label='right summand']/input/symbol = 1
> /turing-machine:turing-machine/transition-function/delta[label='right summand']/output (container)
> /turing-machine:turing-machine/transition-function/delta[label='right summand']/output/head-move = right [default]
> /turing-machine:turing-machine/transition-function/delta[label='right end'] (list instance)
> /turing-machine:turing-machine/transition-function/delta[label='right end']/label = right end
> /turing-machine:turing-machine/transition-function/delta[label='right end']/input (container)
> /turing-machine:turing-machine/transition-function/delta[label='right end']/input/state = 1
> /turing-machine:turing-machine/transition-function/delta[label='right end']/input/symbol = 
> /turing-machine:turing-machine/transition-function/delta[label='right end']/output (container)
> /turing-machine:turing-machine/transition-function/delta[label='right end']/output/state = 2
> /turing-machine:turing-machine/transition-function/delta[label='right end']/output/head-move = left
> /turing-machine:turing-machine/transition-function/delta[label='write separator'] (list instance)
> /turing-machine:turing-machine/transition-function/delta[label='write separator']/label = write separator
> /turing-machine:turing-machine/transition-function/delta[label='write separator']/input (container)
> /turing-machine:turing-machine/transition-function/delta[label='write separator']/input/state = 2
> /turing-machine:turing-machine/transition-function/delta[label='write separator']/input/symbol = 1
> /turing-machine:turing-machine/transition-function/delta[label='write separator']/output (container)
> /turing-machine:turing-machine/transition-function/delta[label='write separator']/output/state = 3
> /turing-machine:turing-machine/transition-function/delta[label='write separator']/output/symbol = 0
> /turing-machine:turing-machine/transition-function/delta[label='write separator']/output/head-move = left
> /turing-machine:turing-machine/transition-function/delta[label='go home'] (list instance)
> /turing-machine:turing-machine/transition-function/de
> 2019-09-30 07:30:36,734 DEBG 'sysrepod' stdout output:
> [WRN] Persist file for module ietf-netconf-acm does not exist.
> 
> 2019-09-30 07:30:36,741 DEBG 'sysrepod' stdout output:
> [WRN] Persist file for module ietf-netconf-acm does not exist.
> 
> 2019-09-30 07:30:36,743 DEBG 'sysrepod' stdout output:
> [WRN] Unable to delete existing action subscriptions.
> 
> 2019-09-30 07:30:36,746 DEBG 'sysrepod' stdout output:
> [WRN] Persist file for module ietf-netconf-acm does not exist.
> [WRN] Persist file for module ietf-netconf-acm does not exist.
> 
> 2019-09-30 07:30:36,748 DEBG 'sysrepod' stdout output:
> [WRN] Unable to delete existing action subscriptions.
> 
> 2019-09-30 07:30:36,796 DEBG 'sysrepod' stdout output:
> [WRN] Persist file for module ietf-netconf-acm does not exist.
> 
> 2019-09-30 07:30:37,797 INFO success: sysrepod entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2019-09-30 07:30:37,798 INFO success: sysrepo-plugind entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2019-09-30 07:30:37,798 INFO success: netopeer2-server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)


Any suggestion on what the problem might be would be greatly appreciated.

Regards.
