### ISSUE TITLE
Default value get and get-config support

### ISSUE THREAD

**Issue by iGovindY** [sysrepo/sysrepo#1622]
Hi,

Does sysrepo support default values get or get-config for an attribute?

From my understanding, currently 
Let's say there are 5 attributes in a module, and we 3 of them have a default value.
I did edit-config for 2 attributes, in get-config reply, I am not getting attributes with default value for which no edit-config has happened.

Is sysrepo not aware of default values of params?

Thanks.

**Comment by michalvasko** [comment]
Hi,
yes, *sysrepo* should fully support default values. I am not sure what exactly is your use-case but default values should be treated as set to the default value. So, if you set them to the same value as the default one, there is no change.

Regards,
Michal

**Comment by iGovindY** [comment]
Thanks Michal for answering my queries.

In the Meantime I found [RFC 6243](https://tools.ietf.org/html/rfc6243).
Looks still few RFC left to read. :)

Thanks
Govind.
