### ISSUE TITLE
Selective persistance to startup support

### ISSUE THREAD

**Issue by iGovindY** [sysrepo/sysrepo#1623]
Hi,

can we ask sysrepo not to persist a few specific params?

for example, I have a few params which are consumed only once by the application.
I don't want them to be in startup datastore so that on bootup of device it doesn't get restored to application.

Can we do it with the current version of sysrepo?

Thanks.

**Comment by michalvasko** [comment]
Hi,
what you want to do is not officially supported (by YANG or any other connected technology, to my knowledge). But what can simply do is not copy these parameters into `startup`, they are not copied there automatically. Is that a problem?

Regards,
Michal

**Comment by iGovindY** [comment]
Hi Michal,

I understand that it is not officially supported.
As per my understanding, copy-config doesn't do a selective copy for particular parameters.

What exactly do you mean by below? how do you propose to not copy these parameters to startup using copy-config?
> But what can simply do is not copy these parameters into `startup`, they are not copied there automatically.

Thanks
Govind.

**Comment by michalvasko** [comment]
Hi Govind,
you are right, it needs a bit of creativity but the simplest way would probably be to just copy everything to `startup` and then remove these parameters, one-by-one.

Regards,
Michal
