### ISSUE TITLE
Query: how can application know end of transaction.

### ISSUE THREAD

**Issue by iGovindY** [sysrepo/sysrepo#1624]
Hi,

To understand this let me give one example.
client did:
  1. edit-config on `candidate `of module1
  2. edit-config on `candidate `of module2
  3. edit-config on `candidate `of module3
  4. commit
on commit `candidate `data will be copied to `running` and subscribed callbacks will be called for each module.

Now my question is how do the application will know when it has to start to actually use and act on the changes?
Is there a way for application to know that this transaction has ended and now the system/device can be brought up?

**Comment by michalvasko** [comment]
Hi,
I do not exactly understand what it is you want to do but when the changes are being applied, they are first called with `SR_EV_VERIFY` and then `SR_EV_APPLY` events. On the second event the changes are already stored in the datastore so the transaction has ended.

Regards,
Michal

**Comment by iGovindY** [comment]
ok, let me explain further.

As per my understanding, on commit:
1. callback_function1 will be called with `SR_EV_VERIFY` for module1
 callback_function1 will be called with `SR_EV_APPLY` for module1

2. callback_function2 will be called with `SR_EV_VERIFY` for module2
 callback_function2 will be called with `SR_EV_APPLY` for module2

3. callback_function3 will be called with `SR_EV_VERIFY` for module3
callback_function3 will be called with `SR_EV_APPLY` for module3

But from an application point of view, how can application know the end of all callbacks.
so that the device can actually consume and bring up the system.

thanks
Govind.

**Comment by michalvasko** [comment]
Hi Govind,
there is nothing more for your application to learn all the modules changes were applied. It was expected an application will react to changes in a single module.

Regards,
Michal

**Comment by iGovindY** [comment]
Hi Michal,

Let me try to take NETCONF protocol procedure.

As per NETCONF, following happens (if we are supporting Candidate Datastore)

1.	Edit-config (on say module 1)
2.	Edit-config (on say module 2)
3.	Edit-config (on say module 3)
4.	Commit

So as per NETCONF, “commit” RPC would indicate end of transaction and hence application can use this as a trigger to go and start applying the new configurations.

But with sysrepo, what is the equivalent of “commit” here? How does the application know that there are not more edits coming, and it can go and start using the new set of configurations?

**Comment by michalvasko** [comment]
Hi Govind,
like I said, there is no such notification. What there is, instead, is that *application knows that there are no more edits coming* **for the particular module**. Also, there should be no *trigger to go and start applying new configurations*. An application should have its callbacks registered on configuration changes that interest it and apply the changes in those callbacks, that is exactly the primary intended use-case.

Note that while *sysrepo* is paired with *netopeer2* NETCONF server, *sysrepo* itself is not bound by any NETCONF standards, it must only provide API so that *netopeer2* can be compliant.

Regards,
Michal
