### ISSUE TITLE
action in a config false list not working

### ISSUE THREAD

**Issue by gitter-runner** [sysrepo/sysrepo#1625]
Hi,
I've found an issue in sysrepo. Action in a config false list is not working, the relevant callback isn't called. I've added a simple action to the netconf-monitoring-model. Log and versions below.
```
sysrepod[2461]: [ERR] libyang error: Invalid arguments (lyd_find_path()).
sysrepod[2461]: [ERR] Action xpath validation failed ('/ietf-netconf-monitoring:netconf-state/sessions/session[session-id='1']/test'): the target node is not present in the data tree.
sysrepod[2461]: [ERR] Validation of an Action (/ietf-netconf-monitoring:netconf-state/sessions/session[session-id='1']/test) message failed. 
```

Versions:
libyang: 1.0.46
sysrepo: 0.7.8

Regards

**Comment by michalvasko** [comment]
Hi,
yes, it seems you have found yet another use-case that was completely omitted in the old *sysrepo*. Do you need it working? It should be supported in the new *sysrepo* and I do not think it worth adding it to the old one.

Regards,
Michal

**Comment by andrei-pavel** [comment]
Hello,

I can't find information on the new sysrepo, Is it already released? How do I know if I'm running the old or the new?

Regards,
Andrei

**Comment by michalvasko** [comment]
Hi Andrei,
no, it was not released yet but it should be soon (a few weeks). It can currently be found in `devel` and you distinguish between them by version, the old *sysrepo* is v0.7.x (0.7.8 latest) and the new one is v1.x (1.2.5 latest).

Regards,
Michal

**Comment by gitter-runner** [comment]
Hi Michal,
Is this feature already supported by the new sysrepo or when is it planned?

Regards

**Comment by michalvasko** [comment]
Hi,
it is fully supported in the new *sysrepo*.

Regards,
Michal

**Comment by gitter-runner** [comment]
Hi Michal,
Thanks for the info!
