### ISSUE TITLE
Whether need to restart the sysrepo when add new yang module or update the yang module

### ISSUE THREAD

**Issue by darcyllingyan** [sysrepo/sysrepo#1633]
Hi,
I just want to confirm, for the netopeer2-sysrepo, if I add new YANG module or update the existed YANG module, whether need to restart the sysrepo?

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
are you talking about the new *sysrepo*? Because you cannot really update a YANG module in the old one. If so, the bevhaviour is documented [here](https://github.com/sysrepo/sysrepo/blob/devel/doc/schema.dox). In short, if you are the only running *sysrepo* client, you just need to disconnect and then connect again to *sysrepo*, that is when these changes should be applied.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
Thanks for the response.
For the new sysrepo, 
1. you mean the newest version in devel branch? I'm using the Version 0.7.8 released on 10 Jul.
2. 

> you just need to disconnect and then connect again to sysrepo 

You mean just disconnect and connect to sysrepo with netopeer2-cli or restart the netopeer2-server to connect the sysrepo? 

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi,
okay, you are talking about the old *sysrepo*. Then what do you mean by updating a module? And no, after installing a new module you should not need to restart *sysrepo*.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
Thanks for the response.
For "updating a module" I mean change the installed YANG module( such as change the leaf name, change the type).

1. Now I have downloaded the new sysrepo, seems there is no sysrepod process now and the usage has changed a lot, but the guide isn't updated now, right?

2. For the new sysrepo, if I want to update a YANG module in the old one, you said  `you just need to disconnect and then connect again to sysrepo`, what do you mean? You mean if I use netopeer2-server, I need to disconnect the connection between netopeer2-server and sysrepo and reconnect, right?

**Comment by michalvasko** [comment]
Hi Darcy,
then I did not know that the old *sysrepo* supported updating a module directly, you have to uninstall the old module and install the updated one, to my knowledge.

1. There is no `sysrepod` process but I would like to think the usage has not changed much. What guide are you referring to? First, look in the README, all the API changes compared to the old *sysrepo* should be mentioned there. Then generate documentation (`make doc`) and go through it, there is a main general page with basic information about the new *sysrepo* and then links to other specific sections. You should find there all the information you need.

2. This is mentioned in the documentation. It is no longer possible to change YANG context while there are some running *sysrepo* clients (for good reasons, there are many cases when even adding a new module can break applications working with some installed modules). Again, please read the documentation and come back if you have any questions.

Regards,
Michal
