### ISSUE TITLE
Returning data from RPC: very slow operation on lists with 5k+ items

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#1635]
I have the following RPC which essentially returns two lists, each indexed by `uint64` and containing a `decimal64` with `fraction-digits 5`. When my RPC code returns these two lists with about 5000 items in each, it is super-slow -- about 15 seconds per each RPC invocation. Given that the device is physically capable of returning these data in less than 300ms, I would like to have this roughly 100× improved :).

Here's the relevant part of the YANG tree:
```
  rpcs:
    +---x full-spectrum-scan
       +---- output
          +--ro common-in
          |  +--ro spectrum* [frequency]
          |     +--ro frequency    opendevice-types:dwdm-frequency-mhz
          |     +--ro power        opendevice-types:optical-power-dBm
          +--ro common-out
             +--ro spectrum* [frequency]
                +--ro frequency    opendevice-types:dwdm-frequency-mhz
                +--ro power        opendevice-types:optical-power-dBm
```
My code is feeding these data into sysrepo via the C++ bindings, using the `Vals_Holder` class with sufficient preallocation. This code can surely be optimized, but it is not a bottleneck. The XPaths that I'm using "crete list instances implicitly", i.e., for each resulting frequency, I essentially do one `set` with an XPath such as `set("common-in/spectrum[frequency='123456789']/power", -54.32)`:
```c++
::sysrepo::S_Vals_Holder vals; // this one was actually obtained from sysrepo

auto out = vals->allocate(readValues.size());
for (auto i = 0; i < data.size(); ++i) {
    out->val(i)->set(data[i].xpath, std::get<double>(data[i].value);
}
```
A high-level profile shows that about 91% of time is spent in `lyd_new_path` as called via `dm_sr_val_node_to_ly_datatree`. Within `ly_new_path`, about 64% of total time is spent in `lyd_schema_sort`.

Here's a high-level flamegraph of execution. At the bottom is the timeline; I think green == idle, orange == executing. Notice how two sysrepo threads run one after each other:

![image](https://user-images.githubusercontent.com/2631925/66547119-0bc51880-eb2e-11e9-9789-8a4aa021603d.png)

Let's zoom in to the "first" of these two threads, the one which handles data from the application (thread 206 in the above picture):

![image](https://user-images.githubusercontent.com/2631925/66547553-05836c00-eb2f-11e9-841a-4c17140af511.png)

And the other thread, the one which handles communication with the code from which I'm triggering the RPC:

![image](https://user-images.githubusercontent.com/2631925/66547598-1c29c300-eb2f-11e9-9c5f-1820be28d3ef.png)

This code is trivial, it's really just this:
```c++
for (int i = 0; i < 10; ++i) {
    std::cerr << "RPC..." << std::endl;
    auto res = session->rpc_send("/czechlight-roadm-device:full-spectrum-scan", std::make_shared<sysrepo::Vals>());
    std::cerr << " #" << i << ": got " << res->val_cnt() << " items" << std::endl;
}
```
I might be able to simplify the YANG tree (e.g., only returning a `leaf-list` of actual samples if that helps). Will that help? How do I actually return a `leaf-list`? Should I be doing some other thing for returning lists with, say, roughly 5k items?

I suspect that the suggestion might be "just use new sysrepo", but I cannot do that right now (we're using, among other things, a custom eventloop implementation with libev and `sr_fd_*`, and I believe that this will take a substantial time to debug with newer sysrepo). Besides, the profiling clearly shows that the bottleneck is in libyang.

**Comment by michalvasko** [comment]
Hi,
guess what? Use the new *sysrepo* :)

Seriously though, there is nothing we can do about all those `lyd_new_path()` calls and they were one of the primary reasons for writing the new *sysrepo*. It allows to directly work with *libyang* data trees (which is somewhat clunky in C++, but possible) and all these calls would be skipped. Moreover, you using a custom event loop should be no problem and it may actually be easier to implement in the new *sysrepo*. You have no fd_watcher but just a file descriptor which you can use in `select()` or `poll()`, see [docs](https://github.com/sysrepo/sysrepo/blob/devel/doc/subs.dox#L8).

I am afraid this is your only chance of optimizing this.

Regards,
Michal

**Comment by jktjkt** [comment]
Is it required to call `lyd_schema_sort` once for each insertion, though? I'm asking because the docs give me the impression that this should only happen once, at the end.

**Comment by michalvasko** [comment]
Hi,
no, it is not needed to be called for every insertion. However, `lyd_new_path()` is unable to know which is the last, that is why it is called on every call.

Regards,
Michal
