### ISSUE TITLE
Question related to running datastore refresh

### ISSUE THREAD

**Issue by Roky7250** [sysrepo/sysrepo#1639]
Hy, i new to sysrepo, I have question related to refreshing running datastore.
Im am developing ieee802-dot1q-bridge module and I need to do next thing.
This is my startup configuration that will be loaded in running datastore:

```
<bridges xmlns="urn:ieee:std:802.1Q:yang:ieee802-dot1q-bridge">
    <bridge>
      <name>deipbrid</name>
      <address>00-80-82-57-e5-40</address>
      <bridge-type>customer-vlan-bridge</bridge-type>
      <component>
        <name>deipbrid</name>
        <id>1</id>
        <type>c-vlan-component</type>
        <address>00-80-82-57-e5-40</address>
        <traffic-class-enabled>true</traffic-class-enabled>
      </component>
    </bridge>
  </bridges>
```

Now, when I send edit-config request to edit address inside bridge, callback in charge of bridge address will be called, and address on system will be changed inside callback.

Edit-config request:

```
<bridges xmlns="urn:ieee:std:802.1Q:yang:ieee802-dot1q-bridge">
    <bridge>
      <name>deipbrid</name>
      <address>00-80-82-57-e5-55</address>
      <bridge-type>customer-vlan-bridge</bridge-type>
      <component>
        <name>deipbrid</name>
        <id>1</id>
        <type>c-vlan-component</type>
        <address>00-80-82-57-e5-40</address>
        <traffic-class-enabled>true</traffic-class-enabled>
      </component>
    </bridge>
  </bridges>
```
Thing that I want to do is to refresh address inside list component with the bridge address, so after I send get-config request, I get this configuration:

```
<bridges xmlns="urn:ieee:std:802.1Q:yang:ieee802-dot1q-bridge">
    <bridge>
      <name>deipbrid</name>
      <address>00-80-82-57-e5-55</address>
      <bridge-type>customer-vlan-bridge</bridge-type>
      <component>
        <name>deipbrid</name>
        <id>1</id>
        <type>c-vlan-component</type>
        <address>00-80-82-57-e5-55</address>
        <traffic-class-enabled>true</traffic-class-enabled>
      </component>
    </bridge>
  </bridges>
```
I read #1626 issue where you mentioned SR_EV_UPDATE on devel branch.
But I want to know is there a way to do it on sysrepo from master branch.
I tried to use **sr_set_item** function inside callback for bridge address to set component address to the same value as bridge, but I get this output:

```
[DBG] Sending set-item request.
[DBG] set-item request sent, waiting for response.
[ERR] While waiting for a response, timeout has expired.
[ERR] Unable to receive the message with response (session id=489274352, operation=set-item).
[ERR] Error by processing of the request.
```
I have need to do it inside other modules to, because if I change one value with edit-config request, others need to be refreshed also. Also I don't want to change yang modules.

Best regards

**Comment by michalvasko** [comment]
Hi,
I believe it should work the way you did but you must call `sr_set_item()` in another thread.

Regards,
Michal

**Comment by jktjkt** [comment]
Would it work for you to delegate this to the client? I.e., subscribe to also handle `SR_EV_VERIFY`, check whether both addresses are the same, and reject configuration when they do not match, setting an appropriate error message.

Because what you're proposing is essentially a silent configuration change, behavior that is different from what the YANG module documents...

**Comment by Roky7250** [comment]
The client that is using netopeer2 is "stupid" and does not take care of address inside list component,  so I have to do reload for him. 
I understand that this silent configuration is different from what the YANG module documents, but I need to do it like this.

Michal could you point me how to implement that "another" thread, that will do the refresh?

After I do the refresh of address inside list component, that needs to be committed  to the session that I am using inside module plugin. 

So for example if I call **sr_get_item** with 
**"/ieee802-dot1q-bridge:bridges/bridge[name='deipbrid']/component[name='deipbrid']/address"** xpath in  another callback, I get this address : 
**00-80-82-57-e5-55** (same as bridge address).

Thanks in advance, Regards.

**Comment by michalvasko** [comment]
Hi,
what I meant was an actual thread, just create a thread in the callback and execute `sr_set_item()` there. It should work that way, I think. You may have to call `sr_session_refresh()` on other sessions to see this change.

Regards,
Michal

**Comment by Roky7250** [comment]
Hi, I did like you said.
This is the simple callback for bridge address:
```
static int
address_cb(sr_session_ctx_t *session, const char *xpath, sr_notif_event_t event, void *private_ctx)
{
    int rc, do_rc;
    sr_change_oper_t op = {0};
    sr_xpath_ctx_t st = {0};
    sr_change_iter_t* iter = NULL;
    sr_val_t* old_value = NULL;
    sr_val_t* new_value = NULL;

    pthread_t thread;

    SRP_LOG_DBG(DBG_MSG_FUN_CALLED_STR, __func__);

    rc = sr_get_changes_iter(session, xpath, &iter);
    if(SR_ERR_OK != rc)
    {
    	return rc;
    }
    do{
    	do_rc = sr_get_change_next(session, iter, &op, &old_value, &new_value);
	    if((op == SR_OP_MODIFIED))
	    {
	         printf("\n");
		 printf("###################### Edit config data: %s ######################\n", new_value->data.string_val);
		 printf("\n");

	         rc = pthread_create((pthread_t *)&thread, NULL, address_thread, session);
		 if (rc != 0)
		 {
			printf("\n");
			printf("###################### pthread_create FAILED! ######################\n");
			printf("\n");
			return SR_ERR_OPERATION_FAILED;
		 }

		 rc = pthread_join(thread, NULL);
		 if (rc != 0)
		 {
			printf("\n");
			printf("###################### pthread_join FAILED! ######################\n");
			printf("\n");
			return SR_ERR_OPERATION_FAILED;
		}
	    }
    } while(SR_ERR_OK == do_rc);

    sr_free_val(old_value);
    sr_free_val(new_value);
    sr_free_change_iter(iter);

    return SR_ERR_OK;
}
```

This is thread: 
```
void *address_thread(void *ses)
{

	sr_session_ctx_t *session = (sr_session_ctx_t*)ses;
	sr_val_t *bridge_address = NULL;
	sr_val_t component_address = {0};

	printf("\n");
	printf("############### address_thread ################\n");
	printf("\n");

	rc = sr_get_item(session, "/ieee802-dot1q-bridge:bridges/bridge[name='deipbrid']/address", &bridge_address);
	if (SR_ERR_OK != rc)
	{
		printf("\n");
		printf("############### sr_get_item FAILED: %s ################\n", sr_strerror(rc));
		printf("\n");
		return NULL;
	}

	printf("\n");
	printf("############### bridge address value: %s ################\n", bridge_address->data.string_val);
	printf("\n");

	component_address.type = SR_STRING_T;
	component_address.data.string_val = "00-80-82-57-e5-55";

	rc = sr_set_item(session, "/ieee802-dot1q-bridge:bridges/bridge[name='deipbrid']/component[name='deipbrid']/address", &component_address, SR_EDIT_DEFAULT);
	if(SR_ERR_OK  != rc)
	{
		printf("\n");
		printf("############### sr_set_item FAILED: %s ################\n", sr_strerror(rc));
		printf("\n");
    	        return NULL;
	}

       return NULL;
}
```

In thread I printed bridge address first. Also I hard-coded  component address just to test this.
Output is:

```
[DBG] Sending set-item request.
[DBG] set-item request sent, waiting for response.
[ERR] While waiting for a response, timeout has expired.
[ERR] Unable to receive the message with response (session id=2006336941, operation=set-item).
[ERR] Error by processing of the request.
```
**sr_set_item** fails, and i get this:

`############### sr_set_item FAILED: Timeout has expired ################`


Thanks in advance. Regards

**Comment by michalvasko** [comment]
Hi,
I seem to remember someone successfully changing a value this way but I may be wrong or they did something differently. The last thing you can try is to create another session and call `sr_set_item()` with that one. If that does not work, you cannot do this directly in the callback.

It is possible to do it outside, just remember that you need to change the value and once you return from the callback, change it. This solution is, however, impractical and will probably be subjected to various data races based on what you said.

Regards,
Michal

**Comment by Roky7250** [comment]
Hi, I tried with new session and it works.
I opened a new sesssion inside callback, that is connected to running datastore, called sr_set_item and after that I commited it to to session that  I opened. Everything went well and changes where applied to running datastore. When I send get-config request changes are there.

After commit I called **sr_session_refresh** for **sesssion** that I get as an argument od callback, because I want to refresh configuration data cached within the **session** and start operating on fresh data loaded from the running datastore. 

**sr_session_refresh(session)** returns **Operation succeeded**. After that I called **sr_get_item** to get the value that I changed in running datastore. Problem is the value did not changed, the old value remained inside **session**.

Is there any way to refresh **session** that I am getting in callback, so that change is seen within the it?

Thanks in advance, Regards

**Comment by michalvasko** [comment]
Hi,
short answer, no, it is not possible. To elaborate, the change you make when the callback is called is only session-exclusive until it is committed (meaning until all the callbacks are processed).

Regards,
Michal

**Comment by maksimvuleta** [comment]
@michalvasko do you plan do add feature do the sysrepo to refresh the session as it is described in the comment above?

**Comment by michalvasko** [comment]
Hi,
certainly not, it would go against the basic principles *sysrepo* was build on. Specifically, every session first prepares some changes that are not visible for any other sessions (not committed) and after calling `sr_commit()` these changes are persistent and visible for all sessions (committed).

Use the new *sysrepo* from `devel` if you require this feature.

Regards,
Michal

**Comment by maksimvuleta** [comment]
I installed the sysrepo from devel branch, but now there is the problem with Netopeer2? 
Which branch of Netopeer2 do you recommend?

**Comment by maksimvuleta** [comment]
Which branches for libnetconf2, libyang, Netopeer2,... do you recommend to install with the latest sysrepo devel branch?

**Comment by michalvasko** [comment]
Hi,
for *sysrepo* `devel` you need *libnetconf2* `devel` and *netopeer2* `devel-server` for now. You can use *libyang* from `master`, `devel`, or even the latest release should work.

Regards,
Michal
