### ISSUE TITLE
sysrepo cross compile, [make install] failed in second build

### ISSUE THREAD

**Issue by Arvliu** [sysrepo/sysrepo#1644]
@jkt@flaska.net

Followed INSTALL.md in link https://github.com/sysrepo/sysrepo/blob/master/INSTALL.md

->The first build is for the host architecture, but it is configured to use a REPOSITORY_LOC pointing to /etc/sysrepo in target's rootfs. 

->The second build then targets the actual target architecture as usual, but this time it's configured with CALL_SYSREPOCTL_BIN=path/to/host/sysrepoctl and CALL_SYSREPOCFG_BIN=..., respectively. 

My first build(local building) is completed( cmake, make, make install are all ok).
But the second build(cross-compiling for ARM): cmake ok, make ok, make install failed.

The error logs are as below:
[ 95%] Built target cpp_get_items_iter_example
[ 97%] Built target cpp_delete_item_example
[100%] Built target cpp_application_example
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /etc/sysrepo
-- Up-to-date: /etc/sysrepo/yang/
-- Up-to-date: /etc/sysrepo/data/
-- Up-to-date: /etc/sysrepo/data/internal/
-- Up-to-date: /var/run/sysrepo-subscriptions
-- Installing: /liu_newGcc/sysrepo_arm/sysrepo_second/lib/sysrepo/plugins
-- Up-to-date: /etc/sysrepo/yang/internal/sysrepo-persistent-data.yang
-- Up-to-date: /etc/sysrepo/yang/internal/sysrepo-module-dependencies.yang
-- Up-to-date: /etc/sysrepo/yang/internal/sysrepo-notification-store.yang
-- Installing: /liu_newGcc/sysrepo_arm/sysrepo_second/lib/pkgconfig/libsysrepo.pc
-- Installing: /liu_newGcc/sysrepo_arm/sysrepo_second/share/man/man1/sysrepoctl.1
-- Installing: /liu_newGcc/sysrepo_arm/sysrepo_second/share/man/man1/sysrepocfg.1
-- Exec: /liu_newGcc/sysrepo_arm/sysrepo_local/bin/sysrepoctl --install --yang=/netconf_arm/sysrepo/yang/ietf-netconf-notifications.yang --permissions=666
/liu_newGcc/sysrepo_arm/sysrepo_local/bin/sysrepoctl: error while loading shared libraries: libyang.so.1: wrong ELF class: ELFCLASS32
CMake Error at cmake_install.cmake:144 (message):
  Error: 127

Makefile:73: recipe for target 'install' failed
make: *** [install] Error 1

==========And, the content of CMakeError.log :===============
Determining if the function getpeereid exists failed with the following output:
Change Dir: /netconf_arm/sysrepo/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_68ff6/fast"
/usr/bin/make -f CMakeFiles/cmTC_68ff6.dir/build.make CMakeFiles/cmTC_68ff6.dir/build
make[1]: Entering directory '/netconf_arm/sysrepo/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_68ff6.dir/CheckFunctionExists.c.o
/usr/linux-devkit/bin/arm-linux-gnueabihf-gcc -D_GNU_SOURCE  -Wall -Wpedantic -std=gnu11 -Wno-language-extension-token -Wno-strict-aliasing -DCHECK_FUNCTION_EXISTS=getpeereid   -o CMakeFiles/cmTC_68ff6.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.10/Modules/CheckFunctionExists.c
Linking C executable cmTC_68ff6
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_68ff6.dir/link.txt --verbose=1
/usr/linux-devkit/bin/arm-linux-gnueabihf-gcc  -Wall -Wpedantic -std=gnu11 -Wno-language-extension-token -Wno-strict-aliasing -DCHECK_FUNCTION_EXISTS=getpeereid    -rdynamic CMakeFiles/cmTC_68ff6.dir/CheckFunctionExists.c.o  -o cmTC_68ff6 -lpthread 
/usr/linux-devkit/bin/../lib/gcc/arm-linux-gnueabihf/8.3.0/../../../../arm-linux-gnueabihf/bin/ld: CMakeFiles/cmTC_68ff6.dir/CheckFunctionExists.c.o: in function `main':
CheckFunctionExists.c:(.text+0x14): undefined reference to `getpeereid'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_68ff6.dir/build.make:97: recipe for target 'cmTC_68ff6' failed
make[1]: *** [cmTC_68ff6] Error 1
make[1]: Leaving directory '/netconf_arm/sysrepo/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_68ff6/fast' failed
make: *** [cmTC_68ff6/fast] Error 2

Determining if the function getpeerucred exists failed with the following output:
Change Dir: /netconf_arm/sysrepo/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_a9ede/fast"
/usr/bin/make -f CMakeFiles/cmTC_a9ede.dir/build.make CMakeFiles/cmTC_a9ede.dir/build
make[1]: Entering directory '/netconf_arm/sysrepo/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_a9ede.dir/CheckFunctionExists.c.o
/usr/linux-devkit/bin/arm-linux-gnueabihf-gcc -D_GNU_SOURCE  -Wall -Wpedantic -std=gnu11 -Wno-language-extension-token -Wno-strict-aliasing -DCHECK_FUNCTION_EXISTS=getpeerucred   -o CMakeFiles/cmTC_a9ede.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.10/Modules/CheckFunctionExists.c
Linking C executable cmTC_a9ede
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a9ede.dir/link.txt --verbose=1
/usr/linux-devkit/bin/arm-linux-gnueabihf-gcc  -Wall -Wpedantic -std=gnu11 -Wno-language-extension-token -Wno-strict-aliasing -DCHECK_FUNCTION_EXISTS=getpeerucred    -rdynamic CMakeFiles/cmTC_a9ede.dir/CheckFunctionExists.c.o  -o cmTC_a9ede -lpthread 
/usr/linux-devkit/bin/../lib/gcc/arm-linux-gnueabihf/8.3.0/../../../../arm-linux-gnueabihf/bin/ld: CMakeFiles/cmTC_a9ede.dir/CheckFunctionExists.c.o: in function `main':
CheckFunctionExists.c:(.text+0x14): undefined reference to `getpeerucred'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_a9ede.dir/build.make:97: recipe for target 'cmTC_a9ede' failed
make[1]: *** [cmTC_a9ede] Error 1
make[1]: Leaving directory '/netconf_arm/sysrepo/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_a9ede/fast' failed
make: *** [cmTC_a9ede/fast] Error 2

Determining if files ucred.h exist failed with the following output:
Change Dir: /netconf_arm/sysrepo/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_90cc4/fast"
/usr/bin/make -f CMakeFiles/cmTC_90cc4.dir/build.make CMakeFiles/cmTC_90cc4.dir/build
make[1]: Entering directory '/netconf_arm/sysrepo/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_90cc4.dir/CheckIncludeFiles.c.o
/usr/linux-devkit/bin/arm-linux-gnueabihf-gcc -D_GNU_SOURCE  -Wall -Wpedantic -std=gnu11 -Wno-language-extension-token -Wno-strict-aliasing    -o CMakeFiles/cmTC_90cc4.dir/CheckIncludeFiles.c.o   -c /netconf_arm/sysrepo/build/CMakeFiles/CMakeTmp/CheckIncludeFiles.c
/netconf_arm/sysrepo/build/CMakeFiles/CMakeTmp/CheckIncludeFiles.c:2:10: fatal error: ucred.h: No such file or directory
 #include <ucred.h>
          ^~~~~~~~~
compilation terminated.
CMakeFiles/cmTC_90cc4.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_90cc4.dir/CheckIncludeFiles.c.o' failed
make[1]: *** [CMakeFiles/cmTC_90cc4.dir/CheckIncludeFiles.c.o] Error 1
make[1]: Leaving directory '/netconf_arm/sysrepo/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_90cc4/fast' failed
make: *** [cmTC_90cc4/fast] Error 2

Source:
/* */
#include <ucred.h>

int main(void){return 0;}

**Comment by jktjkt** [comment]
It seems that your first build have not produced a usable `sysrepoctl` binary. That binary cannot be run because the linker complains about library architecture mismatch. I cannot help you any further apart from strongly suggesting to use a real tool for setting up the cross-build environment -- such as Buildroot, Yocto/OpenEmbedded, etc.
