### ISSUE TITLE
Running datastore persists across sysrepod restarts and notifies subscriber?

### ISSUE THREAD

**Issue by andrei-pavel** [sysrepo/sysrepo#1645]
It's possibly a silly question. Thank you for taking time if you view this.

Using the latest versions except the changes from today in libyang and sysrepo.

I have the following workflow:
1. I start a sysrepo subscriber alongside sysrepod.
2. I insert and commit some data into the running datastore successfully.
3. I then restart sysrepod and the subscriber.
4. Without taking any action on the running datastore, I get notified through the module change callback about the previous data being inserted as if it is new.

I would like to suppress the behavior in number 4. Is it normal? If it is, is there any way it can be disabled?

I was under the impression that the running datastore is not persistent across sysrepod restarts. How does that data persist?

Tried debugging this, but without much helpful information about where it is coming from:

The file descriptor is:
```
p w->fd
$2 = 38
```

Which points to:
```
/proc/17317/fd/38 -> socket:[1233185]
```

Which is:
```
1233185 /tmp/sysrepo-subscriptions/test-model/17317.hf0o9B.sock type=STREAM
```

**Comment by michalvasko** [comment]
Hi,
could you maybe add some details of your use-case? At what moment are you notified about the previous data being inserted? I do that almost every day (set some running data, restart *sysrepod* and the subscriber, and expect the running data to be lost) without any issues.

**Comment by andrei-pavel** [comment]
Hi,

This was a bug in my subscriber.

Was persisting data in an auxiliary external datastore and was recovering it and pushing it to the running sysrepo datastore on startup. This is useful to me only in some cases. Now I clear the external datastore in the other cases.

Sorry, thank you!
