### ISSUE TITLE
New sysrepo: subscribe command returns error

### ISSUE THREAD

**Issue by huw305** [sysrepo/sysrepo#1646]
### Description
With the latest devel branch code, I'm seeing all the subscribe commands except the first one will return error as below:
```
> subscribe --filter-xpath /nc-notifications:notificationComplete
OK
> subscribe --filter-xpath /oven:oven-ready
OK
nc ERROR: Session 1: separate notification thread is already running.
cmd_subscribe: Failed to create notification thread.
```
### Versions
netopeer2-server 1.0.11
libsysrepo.so.3.0.6
libyang.so.1.2.5
libnetconf2.so.1.0.7

**Comment by michalvasko** [comment]
Hi,
please try it again with the latest *netopeer2-cli*.

Regards,
Michal

**Comment by huw305** [comment]
Thanks Michal, I confirm the issue has been fixed.
