### ISSUE TITLE
Query: which DB is used by sysrepo for datastore?

### ISSUE THREAD

**Issue by iGovindY** [sysrepo/sysrepo#1649]
What is the DB based on?
We want to know how it will perform when too much data is to be read from DB.
Are there any stats related to the bulk read? any benchmarking?

**Comment by michalvasko** [comment]
Hi,
*sysrepo* uses files and yes, the performance degrades significantly for large data sets. Just one of the reasons we developed the new *sysrepo*. We did perform some benchmarks comparing them.

![sysrepo_perf](https://user-images.githubusercontent.com/12510224/67293288-8144c780-f4e4-11e9-9355-d1e36b208f6b.png)

Regards,
Michal

**Comment by iGovindY** [comment]
Hi Michal,

Thanks for the clarification.
Here what exactly do you mean by old and new sysrepo, can you specify version numbers of both?

**Comment by michalvasko** [comment]
Hi,
old *sysrepo* is v0.7.x (latest 0.7.8) and the new *sysrepo* is v1.0 and later (latest 1.2.6) currently found only in `devel` branch.

Regards,
Michal

**Comment by iGovindY** [comment]
Hi Michal,

What are timelines for releasing new _sysrepo_?
if not soon is it safe to start using from `devel ` branch?
Also will there be any change in APIs towards application?

thanks
Govind.

**Comment by michalvasko** [comment]
Hi,
we are hoping it will be released sometime next week, should not be much later no matter what. It is perfectly safe to use it. There are API changes, most are just in parameters, the general principles were kept from the old *sysrepo*. There is a file documenting the changes and there also is full documentation, which I strongly recommend you read.

Regards,
Michal
