### ISSUE TITLE
[Question] how to properly send a notification with operational (state) data

### ISSUE THREAD

**Issue by kramarz89** [sysrepo/sysrepo#1650]
Hi,

This is something very similar to #1068  
I want to achieve similar thing, but encountering the exact same problem.
I am trying to send the following notification 

```
notification tx-array-carriers-state-change {
    description
      "Notification used to inform about state change of tx-array-carriers";
    list tx-array-carriers{
      key name;
      description "notification of state change for tx-array-carriers";

      leaf name{
        type leafref{
          path "/user-plane-configuration/tx-array-carriers/name";
        }
        description
          "name of tx-array-carriers is notified at state change";
      }
      leaf state{
        type leafref{
          path "/user-plane-configuration/tx-array-carriers/state";
        }
      description
        "state of tx-array-carriers is notified at state change";
      }
    }
  }
```
There is an `<active>` leaf that I monitor with `subtree_change` in the tx-array-carriers list and when it changes, I want to change the operational data correspondingly (<state> leaf for tx-array-carrier - config false), so in the `subtree_change_cb` i would call `sr_get_items` to trigger the `dp_get_items_cb` that will correctly set the operational data (state) depending on what the `<active>` leaf was, and then send a notification about the state change. - thats what I want to achieve in the end.

To try to work it out, I wanted to test it with a bit easier scenario and send a notification whenever i netopeer2-cli/GET the operational data.
I subscribed to `/xran-uplane-conf:user-plane-configuration/tx-array-carriers/state`

```
rc = sr_dp_get_items_subscribe(session, "/xran-uplane-conf:user-plane-configuration/tx-array-carriers/state", dp_get_items_cb, NULL, SR_SUBSCR_DEFAULT, &subscription);
```

doing netopeer2-cli/GET returns the data correctly, i set the <state> to READY in the callback:

```
<user-plane-configuration xmlns="urn:xran:uplane-conf:1.1">
  <tx-array-carriers>
    <name>tac_0_0</name>
    <absolute-frequency-center>2256665</absolute-frequency-center>
    <center-of-channel-bandwidth>38650000000</center-of-channel-bandwidth>
    <channel-bandwidth>100000000</channel-bandwidth>
    <power>0.0</power>
    <fft-size>1024</fft-size>
    <downlink-radio-frame-offset>0</downlink-radio-frame-offset>
    <downlink-sfn-offset>0</downlink-sfn-offset>
    <default-scs>KHZ_120</default-scs>
    <scs-specific-config>
      <scs>KHZ_120</scs>
      <offset-to-absolute-frequency-center>-792</offset-to-absolute-frequency-center>
      <number-of-prbs>66</number-of-prbs>
    </scs-specific-config>
    <cp-length>34</cp-length>
    **<state>READY</state>**
  </tx-array-carriers>
</user-plane-configuration>
```

Then in the same callback I setup the data for the notification, and start another thread (inside `dp_get_items_cb`) to send the notification, however I get the same error as in the referenced issue:

```
[2019-10-22 11:44:15.533784] erisim sysrepod[1370]: [ERR] (dm_ly_log_cb:1617) libyang error: Leafref "/user-plane-configuration/tx-array-carriers/state" of value "READY" points to a non-existing leaf.
[2019-10-22 11:44:15.533838] erisim sysrepod[1370]: [ERR] (dm_ly_log_cb:1617) libyang error: Leafref "/user-plane-configuration/tx-array-carriers/state" of value "READY" points to a non-existing leaf.
[2019-10-22 11:44:15.534020] erisim sysrepod[1370]: [ERR] (dm_validate_procedure_content:6643) tx-array-carriers-state-change content validation failed: Leafref "/user-plane-configuration/tx-array-carriers/state" of value "READY" points to a non-existing leaf.
[2019-10-22 11:44:15.534043] erisim sysrepod[1370]: [ERR] (dm_validate_procedure:6790) Procedure validation failed.
[2019-10-22 11:44:15.534066] erisim sysrepod[1370]: [ERR] (rp_event_notif_req_process:3094) Validation of an event notification (/xran-uplane-conf:tx-array-carriers-state-change) message failed.
```

What am I missing?

BR,
Adam

**Comment by michalvasko** [comment]
Hi Adam,
if I understand it correctly, int the callback that is providing the state data you are sending a notification that needs the same state data for validation? Even if it was somehow supported, *sysrepo* would always request the state data for validation, which would produce another notification sent, indefinitely. I am afraid you have far exceeded the possibilities of the old *sysrepo*.

Actually, I am currently working for adding support for subscribing to operational (state) data changes in the new *sysrepo*.

Regards,
Michal

**Comment by kramarz89** [comment]
Hi Michal,

Something like that :)

Unless you have a better idea how to accomplish this, because I thought that the only moment I can "modify" the operational data is in the `dp_get_items_cb` callback ?

Because I am trying to simulate something that is not physically there, meaning I have to "edit" the operational data somehow by hand in the application, unless there are other ways?

When the <active> (configuration data) leaf changes to ACTIVE (by the client with edit-config), I want to modify the <state> (operational data) to READY for example. And then i want to notify the client about the <state> change in the notification.

BR,
Adam

**Comment by michalvasko** [comment]
> Unless you have a better idea how to accomplish this, because I thought that the only moment I can "modify" the operational data is in the dp_get_items_cb callback ?

That is correct. The only solution I can think of is not to use `leafrefs` in the notification but simple leaves. It will just not be guaranteed that they really correspond to the state data values but that is the responsibility of your application.

Regards,
Michal

**Comment by kramarz89** [comment]
Hi Michal,

That was the way to go, The application has to take care of making sure the values are correct. 

Thanks!

**Comment by guoqi78** [comment]
![1728531944104](https://github.com/user-attachments/assets/dad646c8-491a-430f-affc-95ad14496bb5)

**Comment by guoqi78** [comment]
[state_update_failed.txt](https://github.com/user-attachments/files/17321523/state_update_failed.txt)
