### ISSUE TITLE
Query: can we replace AF_UNIX to AF_INET between sysrepo and application?

### ISSUE THREAD

**Issue by iGovindY** [sysrepo/sysrepo#1651]
As per [Issue: 359](https://github.com/sysrepo/sysrepo/issues/359) sysrepo only supports Unix Domain socket between sysrepo and application.

Since we need Applications from a different nodes to register and subscribe to a model with sysrepod, we are planning to give a try using INET sockets instead of the UNIX domain socket.

Do you foresee any issue with the above approach?

Thanks
Govind

**Comment by michalvasko** [comment]
Hi,
I think it should make no difference whatsoever.

Regards,
Michal

**Comment by Prasannareddy1** [comment]
In this case, what would be the impact on "no-single-point-of-failure design". As sysrepo client is on different node.

**Comment by michalvasko** [comment]
Well, there will be additional communication over network so, naturally, if that fails, *sysrepo* will produce some errors (possibly fatal ones). But that is your responsibility when implementing this change, it will not make a difference for *sysrepo* itself, whether it communicates over a UNIX socket or an INET one.

Regards,
Michal
