### ISSUE TITLE
Unable to build cpp bindings without sysrepo installed

### ISSUE THREAD

**Issue by pieterlexis** [sysrepo/sysrepo#1653]
### Things you may try first
(put "x" in "[]" if you already tried following)
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description
When creating the cpp bindings from the devel branch, the compiler throws an error because some *.cpp files expect some includes to live in `sysrepo/`. However if the system does not have sysrepo already installed, this include fails:

```
/tmp/tmp.P3zaylR5b9/sysrepo/swig/cpp/src/Struct.cpp:34:10: fatal error: sysrepo/utils/values.h: No such file or directory
   34 | #include "sysrepo/utils/values.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
```

As a work-around building in 2 stages (sysrepo first, then bindings) works, but it not really nice :).

### Steps to Reproduce
Without sysrepo installed on the system:

```bash
git clone --branch devel https://github.com/sysrepo/sysrepo.git
cd sysrepo
mkdir build; cd build
cmake \
    -DCMAKE_BUILD_TYPE=Debug \
    -DCMAKE_INSTALL_PREFIX=$HOME/.local/opt/sysrepo \
    -DREPOSITORY_LOC=$HOME/.local/opt/sysrepo/etc/sysrepo \
    -DREPO_PATH=$HOME/.local/opt/sysrepo/etc/sysrepo \
    -DGEN_CPP_BINDINGS=1 \
    -Wno-dev \
    ..
make install
```

**Expected behavior:**
Sysrepo and the cpp bindings+lib are built correctly.

**Actual behavior:**
Compilation fails with

```
/tmp/tmp.P3zaylR5b9/sysrepo/swig/cpp/src/Struct.cpp:34:10: fatal error: sysrepo/utils/values.h: No such file or directory
   34 | #include "sysrepo/utils/values.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
```

### Versions
Please provide versions for software needed to reproduce the bug:
Sysrepo version: `devel` (4b7914d7).
libyang version: `1.0-r4`

**Comment by michalvasko** [comment]
Hi,
you are right, sorry about that, should work now.

Regards,
Michal

**Comment by pieterlexis** [comment]
Fixed some time ago btw
