### ISSUE TITLE
Query: does the new sysrepo work with Netpeer2?

### ISSUE THREAD

**Issue by shenchsh** [sysrepo/sysrepo#1654]
Hi,

Thanks for providing the latest sysrepo.

I am wondering does the new sysrepo in branch `devel` work with the Netpeer2 server from master branch of `CESNET/Netopeer2`?

Thanks!

**Comment by michalvasko** [comment]
Hi,
no, to run *sysrepo* `devel` you need *libnetconf2* `devel` and *netopeer2* `devel-server`.

Regards,
Michal

**Comment by shenchsh** [comment]
Got it, thanks!
