### ISSUE TITLE
Question related to operation inside callback

### ISSUE THREAD

**Issue by Roky7250** [sysrepo/sysrepo#1655]
Hi, I have question related to operation that happened inside callback.

This is my startup configuration:
```
<bridges xmlns="urn:ieee:std:802.1Q:yang:ieee802-dot1q-bridge">
    <bridge>
      <name>deipbrid</name>
      <address>00-80-82-57-e5-40</address>
      <bridge-type>customer-vlan-bridge</bridge-type>
      <component>
        <name>deipbrid</name>
        <id>1</id>
        <type>c-vlan-component</type>
        <address>00-80-82-57-e5-40</address>
        <traffic-class-enabled>true</traffic-class-enabled>
      </component>
    </bridge>
  </bridges>
```
In **sr_plugin_init_cb** I subscribed for next changes:

```
rc = sr_subtree_change_subscribe(session, "/ieee802-dot1q-bridge:bridges/bridge", list_cb, NULL, 0,
SR_SUBSCR_DEFAULT, &subscription);

rc = sr_subtree_change_subscribe(session, "/ieee802-dot1q-bridge:bridges/bridge/component/type", type_cb, NULL, 1,
SR_SUBSCR_DEFAULT, &subscription);
```
**list_cb** and **type_cb** are same and the look like this:

```
static int
list_cb(sr_session_ctx_t *session, const char *xpath, sr_notif_event_t event, void *private_ctx)
{

    int rc;
    sr_change_oper_t op = {0};
    sr_change_iter_t* iter = NULL;
    sr_val_t* old_value = NULL;
    sr_val_t* new_value = NULL;
    sr_val_t* node = NULL;

    rc = sr_get_changes_iter(session, xpath, &iter);

    if(SR_ERR_OK != rc)
    {
    	return rc;
    }

    while(SR_ERR_OK == sr_get_change_next(session, iter, &op, &old_value, &new_value))
    {
        printf("\n");
        printf("Operation: %d\n", op);
        printf("\n");

    	node = (op == SR_OP_DELETED) ? old_value : new_value;
	
	printf("\n");
        printf("Xpath: %s\n", node->xpath);
        printf("\n");

      }

    sr_free_val(old_value);
    sr_free_val(new_value);
    sr_free_val(node);
    sr_free_change_iter(iter);

    return rc;
}
```
When I send edit config request with this configuration:
```
<bridges xmlns="urn:ieee:std:802.1Q:yang:ieee802-dot1q-bridge">
    <bridge>
      <name>deipbrid</name>
      <address>00-80-82-57-e5-40</address>
      <bridge-type>customer-vlan-bridge</bridge-type>
      <component>
        <name>deipbrid</name>
        <id>1</id>
        <type>s-vlan-component</type>
        <address>00-80-82-57-e5-40</address>
        <traffic-class-enabled>true</traffic-class-enabled>
      </component>
    </bridge>
  </bridges>
```
where **type** inside list component is changed, both callback will be triggered and output inside both callbacks will be same:

```
Operation: 1

Xpath: /ieee802-dot1q-bridge:bridges/bridge[name='deipbrid']/component[name='deipbrid']/type
```

Here I can see that **SR_OP_MODIFIED** operation happened for leaf type.
On netopeer1 callback for list bridge would be triggered with CHAIN operation and callback for leaf type would triggered with MODIFIED operation, correct be if I am wrong.

My question is: How can I know what actually happened for **entry** of list bridge inside callback that manages changes for that list, not operation made on an specific item?

Thanks in advance.
Best regards.

**Comment by michalvasko** [comment]
Hi,
let me start by saying that you are always subscribing for **subtree** changes (as the name implies) so a node is changed whenever the node or any of its descendants are changed. But, you should be able to get only changes on specific nodes. The problem is that the xpath you are using for `sr_get_changes_iter()` gets **subtree changes**, not node changes, again. This behavior was changed in the new *sysrepo* and I believe this particular use-case would work as expected there. It will not be changed in the old *sysrepo*.

Regards,
Michal

**Comment by Roky7250** [comment]
Thank you, you have helped me a lot.
Best regards
