### ISSUE TITLE
Query regarding module subscription callback

### ISSUE THREAD

**Issue by udaykumar84** [sysrepo/sysrepo#1656]
Hi All,
Have a query related to callback function. 
We can subscribe to a yang module using the subscription option. This has a callback function which would be called whenever there is a change in the running dataset. 

This would return the change in a string format. Even if we want to read the running config it would return in a string format.

1) Is there any alternative way to get the data from the sysrepo db apart from string format like json or xml ??

2) Is there a library  to deparse the string based on yang model ?? 

There are no sample example in the sysrepo examples or test for the same.
It would be very helpful if anyone has a suggestion for the same.

Thanks,
Uday

**Comment by michalvasko** [comment]
Hi Uday,

1. There is not. However, a new *sysrepo* version will be released soon (matter of weeks), whose primary data output format are [libyang](https://github.com/cesnet/libyang) data trees.
2. Yes, *libyang*.

Regards,
Michal

**Comment by udaykumar84** [comment]
Hi Michal,
Thanks a lot for the answer & the suggestion.

Thanks,
Uday
