### ISSUE TITLE
Memory leak in python SWIG callback (dp_get_items etc)

### ISSUE THREAD

**Issue by maggie450** [sysrepo/sysrepo#1657]
### Things you may try first
(put "x" in "[]" if you already tried following)
* [x] Did you check if this is a duplicate issue?
* [] Did you test it on the latest sysrepo devel branch?

### Description
Python process that subscribes dp_get_items will slowly increase memory use as callbacks are triggered

### Steps to Reproduce
1. Subscribe to dp_get_items in one python process
2. Call get_item in another process
3. Monitor memory use in first process

**Expected behavior:**
 Memory use remains constants

**Actual behavior:**
 Memory use slowly increases

### Versions
Sysrepo version: 0.7.7

### Analysis
In swig interface file sysrepo.i method
```
int dp_get_items(const char *xpath, sr_val_t **values, size_t *values_cnt, uint64_t request_id, const char *original_xpath, PyObject *private_ctx)
```
calls SWIG_NewPointerObj with last parameter SWIG_POINTER_DISOWN
but SWIG_POINTER_DISOWN is a constant associated with pointer conversions not with pointer create
```
/* Flags for pointer conversions */
#define SWIG_POINTER_DISOWN        0x1
#define SWIG_CAST_NEW_MEMORY       0x2

/* Flags for new pointer objects */
#define SWIG_POINTER_OWN           0x1
```
since the value of the last parameter is 0x1, this means that SWIG_NewPointerObj is actually being called with SWIG_POINTER_OWN?

This means it is necessary to decrement the object reference after the python callback has returned?
```
Py_DECREF(arglist);
Py_DECREF(out); //object no longer needed?
```
Similarly for the other callback methods

### Attachments (suggested patch)

[sysrepo-python-cbmemleak.txt](https://github.com/sysrepo/sysrepo/files/3797839/sysrepo-python-cbmemleak.txt)

**Comment by michalvasko** [comment]
Hi,
it seems fine to me so you can provide a pull request.

Regards,
Michal
