### ISSUE TITLE
 [sysrepo-devel] undefined symbol: sr_ll_stderr

### ISSUE THREAD

**Issue by mashemat** [sysrepo/sysrepo#1661]
Hello,

I am trying to compile and run my old sysrepo plugin (0.7.8) with the new version (devel). But when I run sysrepo-plugind, it fails with the following error:

undefined symbol: sr_ll_stderr

 Could you please help me on this?

Thanks,

**Comment by michalvasko** [comment]
Hi,
looking at the old *sysrepo*, it should be the current `stderr` log level. However, it is in an [internal section](https://github.com/sysrepo/sysrepo/blob/master/inc/sysrepo/plugins.h#L70) so you should not have used the value in your plugin. Anyway, do you really need to read the log level in your application? I guess a getter can be added but I am not sure it is of much use.

Regards,
Michal

**Comment by mashemat** [comment]
I used SRP_LOG_ERR and SRP_LOG_DBG to debug the plugin at run time. As I understood I should remove them. Am I right?

Thanks,

**Comment by michalvasko** [comment]
Ah, no, these macros should work just fine (defined at the end of `sysrepo.h`). But there is no such variable in the new *sysrepo* (`sr_ll_stderr`), so I think you are doing something wrong. Are you sure you are including/linking the new *sysrepo*?

Regards,
Michal

**Comment by mashemat** [comment]
Just to be sure: I  compile and install libyang, libnetconf, sysrepo, and Netopeer2 all in devel branch. Then, I try to compile my  plugin with this new sysrepo. 

I noticed I have SRP_LOG_DBG_MSG that does not exist anymore and it should be changed with SRP_LOG_DBGMSG. Am I right? Modifying this let me to run sysrepo-plugind. However, still I could not connect to VPP successfully.

**Comment by michalvasko** [comment]
Hi,
yes, I think that was the only change (`DBG_MSG` -> `DBGMSG` and similar for other log levels). And what exactly are you doing? I would suggest to completely uninstall the old *sysrepo* (`make uninstall_with_repo`), install the new one, and try to compile and install your plugins. If they compile, they should work.

Regards,
Michal

**Comment by mashemat** [comment]
Hi, 

Actually, I tried to install all from scratch on new machine. But when I run the sysrepo-plugind -d -v 4. I receive the following error:

[INF]: Applying scheduled changes.
[INF]: Scheduled changes applied.
[INF]: Datastore copied from <startup> to <running>.
[INF]: Session 1 (user "root") created.
[DBG]: plugin: *connected ok
[ERR]: mkfifo() failed (File exists).
[ERR]: Locking a mutex failed (sr_shmmain_lock_remap: Connection timed out).
Segmentation fault

I am sure there is not concurrent sysrepo-plugind and there is not old version.

Thanks,
Masoud

**Comment by michalvasko** [comment]
Hi Masoud,
okay, you may have discovered a problem. So, you install new *sysrepo* and just run *sysrepo-plugind* with your plugin? What is the initialization code of the plugin (that prints the connected message)?

**Comment by mashemat** [comment]
Thanks Michal for your reply. My initial just try to connect to VPP through vapi_connect (an VPP VAPI).

My general question is:  is devel branch stable to be used now? Maybe I am doing something wrong. Once I see it is OK, then nothing work. In my case, sysrepoctl once work once crash with the error for example like:

[ERR]: Module "ietf-netconf-acm" was not found in sysrepo.
sysrepoctl error: Failed to list modules (Item not found)

Moreover, I could not run Netopeer2 in devel branch properly as well. 

Thanks,
Masoud

**Comment by michalvasko** [comment]
Hi Masoud,
I am not sure I can help you more. `devel` is quite stable and successfully tested by several people, we are just working on Python bindings (only tests are left to be written) and when they are finished, it will be merged to `master` and released. You seeing such critical errors points to some incompatibilities in the libraries/binaries you are using, some old versions perhaps.

You should definitely first try installing new *sysrepo* and then installing and executing the new *netopeer2-server* from `devel-server`, it must all be performed successfully.

Regards,
Michal

**Comment by mashemat** [comment]
Thanks, Michal for explanation. I guess my main problem was that I did not run ldconfig, as you mentioned in the documentation. Seems now is Ok for me. 

Thanks,
Masoud
