### ISSUE TITLE
sysrepo exiting by sending SIGBUS error

### ISSUE THREAD

**Issue by gurugod** [sysrepo/sysrepo#1662]
Hello everyone,
 I got one corefile from sysrepo with SIGBUS error

back trace of corefile is as follows :
#0  0x00007fb2e68cb346 in lyxml_parse_elem (ctx=0x7fb2dc11a090, data=0x7fb2e7c18826 "", len=0x7fb2e3d4e5ec,
    parent=0x7fb2dc2137d0, options=1) at /home/nigama/CU_DU/platform/build/staging/du/x86/libyang.08_20_2018/src/xml.c:881
#1  0x00007fb2e68cbfb5 in lyxml_parse_elem (ctx=0x7fb2dc11a090, data=0x7fb2e7c18694 "", len=0x7fb2e3d4e6ac,
    parent=0x7fb2dc216860, options=1) at /home/nigama/CU_DU/platform/build/staging/du/x86/libyang.08_20_2018/src/xml.c:1047
#2  0x00007fb2e68cbfb5 in lyxml_parse_elem (ctx=0x7fb2dc11a090, data=0x7fb2e7c10000 "", len=0x7fb2e3d4e75c, parent=0x0, options=1)
    at /home/nigama/CU_DU/platform/build/staging/du/x86/libyang.08_20_2018/src/xml.c:1047
#3  0x00007fb2e68cc55a in lyxml_parse_mem (ctx=0x7fb2dc11a090, data=0x7fb2e7c10000 "", options=1)
    at /home/nigama/CU_DU/platform/build/staging/du/x86/libyang.08_20_2018/src/xml.c:1184
#4  0x00007fb2e693c2a8 in lyd_parse_ (ctx=0x7fb2dc11a090, rpc_act=0x0, data=0x7fb2e7c10000 "", format=LYD_XML, options=74240,
    data_tree=0x0, yang_data_name=0x0) at /home/nigama/CU_DU/platform/build/staging/du/x86/libyang.08_20_2018/src/tree_data.c:914
#5  0x00007fb2e693c6b5 in lyd_parse_data_ (ctx=0x7fb2dc11a090, data=0x7fb2e7c10000 "", format=LYD_XML, options=74240,
    ap=0x7fb2e3d4e8c0) at /home/nigama/CU_DU/platform/build/staging/du/x86/libyang.08_20_2018/src/tree_data.c:993
#6  0x00007fb2e693c851 in lyd_parse_fd_ (ctx=0x7fb2dc11a090, fd=59, format=LYD_XML, options=74240, ap=0x7fb2e3d4e8c0)
    at /home/nigama/CU_DU/platform/build/staging/du/x86/libyang.08_20_2018/src/tree_data.c:1028
#7  0x00007fb2e693c91c in lyd_parse_fd (ctx=0x7fb2dc11a090, fd=59, format=LYD_XML, options=74240)
    at /home/nigama/CU_DU/platform/build/staging/du/x86/libyang.08_20_2018/src/tree_data.c:1042
#8  0x00007fb2e76dfdc9 in dm_load_data_tree_file (dm_ctx=0x1b986f0, fd=59,
    data_filename=0x7fb2dc1f4fd0 "/opt/mavenir/mnxt/etc/sysrepo/data/mavenir-events.startup", schema_info=0x7fb2dc100570,
    data_info=0x7fb2e3d4eb48) at /home/nigama/CU_DU/platform/build/staging/du/x86/sysrepo-0.7.4/src/data_manager.c:1271
#9  0x00007fb2e76e0c98 in dm_load_data_tree (dm_ctx=0x1b986f0, dm_session_ctx=0x1c02230, schema_info=0x7fb2dc100570,
    ds=SR_DS_STARTUP, data_info=0x7fb2e3d4eb48)
    at /home/nigama/CU_DU/platform/build/staging/du/x86/sysrepo-0.7.4/src/data_manager.c:1397
#10 0x00007fb2e76ee2bb in dm_get_data_info_internal (dm_ctx=0x1b986f0, dm_session_ctx=0x1c02230,
    module_name=0x7fb2dc215020 "mavenir-events", skip_validation=false, must_be_freed=0x0, info=0x7fb2e3d4ec40)
    at /home/nigama/CU_DU/platform/build/staging/du/x86/sysrepo-0.7.4/src/data_manager.c:2940
#11 0x00007fb2e76eeab6 in dm_get_data_info (dm_ctx=0x1b986f0, dm_session_ctx=0x1c02230,
    module_name=0x7fb2dc215020 "mavenir-events", info=0x7fb2e3d4ec40)
    at /home/nigama/CU_DU/platform/build/staging/du/x86/sysrepo-0.7.4/src/data_manager.c:2982
#12 0x00007fb2e770ef6a in dm_parse_event_notif (rp_ctx=0x1b509b0, session=0x1c0bd30, sr_mem=0x0, notification=0x7fb2dc2096b0,
    api_variant=SR_API_VALUES) at /home/nigama/CU_DU/platform/build/staging/du/x86/sysrepo-0.7.4/src/data_manager.c:6732
#13 0x00007fb2e7724baf in np_get_event_notifications (np_ctx=0x1b50c10, rp_session=0x1c0bd30, xpath=0x0, start_time=1572551715,
    stop_time=0, api_variant=SR_API_VALUES, notifications=0x7fb2e3d4fdb0)
    at /home/nigama/CU_DU/platform/build/staging/du/x86/sysrepo-0.7.4/src/notification_processor.c:1863
#14 0x00007fb2e76aa1fc in rp_event_notif_replay_req_process (rp_ctx=0x1b509b0, session=0x1c0bd30, msg=0x1c207a0)
    at /home/nigama/CU_DU/platform/build/staging/du/x86/sysrepo-0.7.4/src/request_processor.c:3457
#15 0x00007fb2e76aba83 in rp_req_dispatch (rp_ctx=0x1b509b0, session=0x1c0bd30, msg=0x1c207a0, skip_msg_cleanup=0x7fb2e3d4febb)
    at /home/nigama/CU_DU/platform/build/staging/du/x86/sysrepo-0.7.4/src/request_processor.c:3700
#16 0x00007fb2e76acc98 in rp_msg_dispatch (rp_ctx=0x1b509b0, session=0x1c0bd30, msg=0x1c207a0)
    at /home/nigama/CU_DU/platform/build/staging/du/x86/sysrepo-0.7.4/src/request_processor.c:3844
#17 0x00007fb2e76ad5fa in rp_worker_thread_execute (rp_ctx_p=0x1b509b0)
    at /home/nigama/CU_DU/platform/build/staging/du/x86/sysrepo-0.7.4/src/request_processor.c:3945
#18 0x00007fb2e73ede25 in start_thread () from /lib64/libpthread.so.0
#19 0x00007fb2e65c6bad in clone () from /lib64/libc.so.6

I wanted to know why it crashing in opensource library. Do anyone know about it ?

**Comment by michalvasko** [comment]
Hi,
what version of *libyang* are you using?

Regards,
Michal

**Comment by gurugod** [comment]
hi ,
we have cloned it on 20-08_2018
It is in between r0.15-r1 to r0.16-r1

Thanks,
Gaurav.

**Comment by michalvasko** [comment]
Hi Gaurav,
then I would suggest to use the latest version 1.0.87 (or at least the latest release). Let us know if you reproduce the problem with that version, then we can take a closer look.

Regards,
Michal
