### ISSUE TITLE
Query: how to subscribe to x-path /ietf-netconf:edit-config RPC?

### ISSUE THREAD

**Issue by mabukar** [sysrepo/sysrepo#1666]
Hello!

Would it be possible for sysrepo applications to subscribe to ietf-netconf:edit-config RPC (or all the other supported ietf-netconf RPCs)? If not then what would be the preferred way for sysrepo applications to handle such RPC requests, and how the application would be able to differentiate the operation-types (create, delete, etc. of managed objects) in the edit-config RPC?

Thanks,
Abukar

**Comment by michalvasko** [comment]
Hi Abukar,
firstly, I am not sure you fully understand the basic *sysrepo* functionality. What it does is basically transform every `<edit-config>` that is received from NETCONF to small individual changes that your application gets when it [subscribes](http://www.sysrepo.org/static/doc/html/group__cl.html#ga35341cf4bf9584127f7c5a79405a878f) to them. So all of what you wrote you want to do is done for you by *sysrepo* and there should not be a need to handle NETCONF `<edit-config>`s yourself.

However, there are special cases when standard NETCONF RPCs need to partly be processed by applications so the new *sysrepo* and *netopeer2* allow several subscribers to a single RPC to cover these cases. But like I said, these are rather exotic use-cases and the one you described seems to actually be the most common one that does not require this mechanism and should use the standard one.

Regards,
Michal

**Comment by mabukar** [comment]
Hi Michal,

Thanks for the clarification, clearly I misunderstood sysrepo functionality. 

In fact, once I subscribed to module changes, my application managed to get all the changes (<edit-confi>: create/modify/replace) received from NETCONF correctly.

Thanks a lot once again for you prompt response!

Regards,
Abukar
