### ISSUE TITLE
[Query] whether the callbacks can be called according to the order of dependencies

### ISSUE THREAD

**Issue by adamzyg** [sysrepo/sysrepo#1667]
Suppose there are 3 modules A/B/C subscribed by three different callbacks. And B dependent A, C dependent B. We have the full netconf context, which send by edit-config, whether the callbacks can be called according by the order: A-callback then B-callback then C-callback？

**Comment by michalvasko** [comment]
Hi,
no, the order across modules cannot be defined.

Regards,
Michal

**Comment by adamzyg** [comment]
OK, thanks. I get it, yang just define data logical relations, can not define the configuration sequence.
