### ISSUE TITLE
some question About "*.persist" file: when and how create it? is there any example on the context format ?

### ISSUE THREAD

**Issue by ZhaoGuangYue** [sysrepo/sysrepo#167]
some question About "*.persist" file: 
1. when and how create it? 
2.is there any example on the context format ?

**Comment by rastislavszabo** [comment]
Hi,
"*.persist" files are internal, created automatically by sysrepo:

a) by --install or --init operation when using sysrepoctl
b) if not already exist, automatically created by sysrepo engine when there is a need for it

**Users must not touch these files.** 

If you are just curious: they contain list of enabled YANG features and list of active subscriptions. Here is the data model: https://github.com/sysrepo/sysrepo/blob/master/yang/sysrepo-persistent-data.yang

**Comment by ZhaoGuangYue** [comment]
dear sir/madam
when i use --install to add model to sysrepo,i found the model's persist file is empty,is this right?

my model is like 

module TopModule {
  namespace "urn:ietf:params:xml:ns:yang:zte";
  prefix TopModule;
  
  container AAA {
    leaf testenum{
	  type enumeration{
	    enum enum-eee;
		enum enum-fff;
	  }
	}
	
    leaf aaa {
      type int32;
      default 100;
    }
    container BBB {
      leaf bbb {
        type int32;
      }
      container CCC {
        leaf ccc {
          type int32;
          default 300;
        }
      }
    }
  }
}

**Comment by rastislavszabo** [comment]
Yes, while you don't have any active subscriptions there (please refer to sysrepo API calls with _subscribe suffix), then it's empty.
