### ISSUE TITLE
[New sysrepo] operational data

### ISSUE THREAD

**Issue by mashemat** [sysrepo/sysrepo#1671]
Hi, 

I had a call back for **sr_oper_get_items_subscribe** as following in previous sysrepo:

```
rc = sr_new_values(2, &vals);
cntrl=0;

sr_val_build_xpath(&vals[cntrl], "%s[faceid='%d']/intfc", "/test:state/faces/face",1);
vals[cntrl].type = SR_UINT32_T;
vals[cntrl].data.uint32_val = 12;

cntrl++;

sr_val_build_xpath(&vals[cntrl], "%s[faceid='%d']/intfc", "/test:state/faces/face",2);
cntrl++;
vals[cntrl].type = SR_UINT32_T;
vals[cntrl].data.uint32_val = 10;

*values = vals;
*values_cnt = 2;
```

Here it is the yang model:

```
module test {

 grouping face-stats {
    list face{

        key faceid;

        leaf faceid {
                type uint32;
            }
        leaf intfc {
                type uint32;
            }

     }
 }
}

container state {
    config false;
    container faces{
        uses face-stats;
    }
}
```

I am not sure how I can convert it to the new sysrepo version. Can you please help me on this?

I see the the call back is changed and now I should use  **lyd_new_path**.

Thanks,
Masoud

**Comment by michalvasko** [comment]
Hi,
it also depends on the path you are using to subscribe, these callbacks now have much more options so you need to be more careful. But in your case you can subscribe to `/test:state`, which means you are providing this container and all the data descendants. Your callback:
```C
struct ly_ctx *ly_ctx = sr_get_context(sr_session_get_connection(session));

*parent = lyd_new_path(NULL, ly_ctx, "/test:state/faces/face[faceid='1']/intfc", "12", 0, 0);
lyd_new_path(*parent, NULL, "/test:state/faces/face[faceid='2']/intfc", "10", 0, 0);
```
You should check return values, naturally. Also, to understand why all the parameters are the way they are, look into *libyang* documentation. You should have basic knowledge of it, anyway.

Regards,
Michal

**Comment by mashemat** [comment]
Thanks Michal. It works for me and subscribes the state data but I have one issue. Actually, from netopeer-cli with **get** I could get the whole schema previously but now even my state data is subscribed successfully it does not return any schema (i.e., state part). Does any modification in **get** or I may have problem in subscription in your opinion?

Thanks,
Masoud

**Comment by michalvasko** [comment]
Hi,
there can be several reasons why the data are (correctly) not returned, but I would need all the details to determine that. Can you provide the schema, the configuration data at the moment of sending `<get>`, the oper subscription callback and subscribed path (if they differ from what I posted)?

Regards,
Michal

**Comment by mashemat** [comment]
Hi Michal, thanks for your reply.  This is my subscription function:

```
 rc = sr_oper_get_items_subscribe(session, "test","/test:test-state",
                                test_state_faces_cb, NULL, SR_SUBSCR_DEFAULT,
                                subscription);
```

This is the callback:

```
 static int hicn_state_faces_cb(sr_session_ctx_t *session, const char *module_name, const char *path, const char *request_xpath, uint32_t request_id, struct lyd_node **parent, void *private_data) {

SRP_LOG_DBGMSG("Start callback \n");

char buf[20]; 
sr_val_t *vals;
rc = sr_new_values(2, &vals);
struct ly_ctx *ly_ctx = sr_get_context(sr_session_get_connection(session));


cntrl=0;

sr_val_build_xpath(&vals[cntrl], "%s[faceid='%d']/intfc", "/test:state/faces/face",1);
vals[cntrl].type = SR_UINT32_T;
vals[cntrl].data.uint32_val = 12;
memset(buf, 0x00, 20);
sprintf( buf,"%u", 12);
*parent = lyd_new_path(NULL, ly_ctx, vals[cntrl].xpath, buf, 0, 0);

cntrl++;

sr_val_build_xpath(&vals[cntrl], "%s[faceid='%d']/intfc", "/test:state/faces/face",2);
vals[cntrl].type = SR_UINT32_T;
vals[cntrl].data.uint32_val = 10;
memset(buf, 0x00, 20);
sprintf( buf,"%u", 10);
lyd_new_path(*parent, NULL, vals[cntrl].xpath, buf, 0, 0);

return SR_ERR_OK;

}
```

Actually, the plugin successfully initialized and seems it subscribed successfully. But when I use **get** in  netopeer-cli to receive the state data it does not call the callback function (since I don't see my print "start callback" ). 

Actually, I have one general question as well. When sysrepo-plugind crashes by any mistake for example I made wrong subscription or etc., I can not run it again, it gives me the error "Locking a mutex failed". Forcefully, I reboot my system to make it work.


Thanks,
Masoud

**Comment by michalvasko** [comment]
Hi Masoud,
what *sysrepo* version are you using? I think you may be affected by a serious bug that i fixed in 1.3.6.

As for the crash, you do not need to reboot your system, just call `make sr_clean` and it will reset all *sysrepo* shared memory as if after a reboot. I am planning to fix this problem so that even if an application crashes, you can continue to work normally but I keep working on other things. It will be handled soon.

Regards,
Michal

**Comment by mashemat** [comment]
I am using version 1.3.2 as reported "sysrepo-plugind - sysrepo plugin daemon, compiled with libsysrepo v1.3.2 (SO v4.0.2)". It seems I am using outdated version. I need to clone the new version then.

Thanks,
Masoud

**Comment by mashemat** [comment]
Hi Michal,

Actually, to migrate to the new sysrepo version. I am debugging my plugin but the point is that for every crash in my plugin even if I use ```make sr_clean``` I can not run it again. Actually, not the sysrepo but the netopeer-server. Sometimes I need to reinstall all from scratch. could you please let me know I am doing wrong or this is  missing in sysrepo?

Thanks,
Masoud

**Comment by michalvasko** [comment]
Hi,
yes, after each crash I did
```
sysrepo> make sr_clean
netopeer2-server> make install
```
when I was debugging because cleaning *sysrepo* removes all the installed modules that the server needs. I will add some *sysrepo* handling in case of crashes but I am yet to see whether (almost) all cases can be covered or not.

Regards,
Michal

**Comment by mashemat** [comment]
Hi Michal, 

Thanks for all your help! I almost upgrade my old plugin to the new version of Sysrepo. My Sysrepo version is  ```v1.3.10 (SO v4.0.10)```. The only problem that I have and I could not resolve is that by the same procedure I sent (https://github.com/sysrepo/sysrepo/issues/1671#issuecomment-553330870),  I always get the last node not the list of them from the netopper-cli through ```get```. Do you have any idea where would be the problem?

Thanks,
Masoud

**Comment by mashemat** [comment]
The problem solved with removing ```the sr_get_context``` and use the parent directly with the callback!

Thanks,
Masoud

**Comment by michalvasko** [comment]
Hi Masoud,
not sure I would have helped but as you can see it is important to be familiar with *libyang* API since it is now used directly in *sysrepo* API so at least always read the documentation.

Regards,
Michal

**Comment by mashemat** [comment]
Thanks Michal, but the little issue that I have is SR_PLUGINS_DIR for devel branch. I need to set it manually. Is there any way that I avoid it?

Thanks,

**Comment by michalvasko** [comment]
I do not understand why you have to set it manually. If you want it not to be the default then you do have to set it manually and I do not see a way of avoiding it.

Regards,
Michal

**Comment by mashemat** [comment]
My bad! I saw it is replaced by SRPD_PLUGINS_PATH in devel.

Thanks,
Masoud
