### ISSUE TITLE
Is there any APIs for subscribing file callbacks like netopeer?

### ISSUE THREAD

**Issue by Xiaolin-He** [sysrepo/sysrepo#1678]
### Things you may try first
(put "x" in "[]" if you already tried following)
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description
I want to monitor the change of some normal files that contain configuration information in my sysrepo-plugin. In netopeer, I can use transapi_file_callbacks. But in sysrepo, I have not find a similar API.
So, I want to know if there have such API in sysrepo?

Thanks!

**Comment by michalvasko** [comment]
Hi,
no, there is not a similar API, you would have to implement such a callback yourself (not too much work I think). But there is a possibility it will be added later.

Regards,
Michal

**Comment by Xiaolin-He** [comment]
Hi Michal, 
Got it. Thanks for your quick reply.

Best Regards,
Xiaolin He
