### ISSUE TITLE
sysrepo install with CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by mashemat** [sysrepo/sysrepo#1679]
Hi,

I am going to install sysrepo (old version 0.7.8) with all its dependencies in a single folder. I use the following for each:
```
git clone https://github.com/sysrepo/sysrepo.git
mkdir -p sysrepo/build  
pushd sysrepo/build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/test/sysretest  ..
make -j 4 install && popd 
```
Then, I totally remove the source folders (sysrepo as above example).
Actually, my problem is when I try to run sysrepod, I recieve the following error: 

```
[DBG] Setting log level for stderr logs to 4.
[DBG] Connection Manager init started.
[DBG] Initiating circular buffer for 10 elements.
[DBG] Session Manager initialized successfully, ctx=0x564346d35480.
[DBG] Initializing sysrepo server at socket=/var/run/sysrepod.sock
[DBG] Request Processor init started.
[DBG] Initiating circular buffer for 10 elements.
libyang[0]: Unable to use search directory "/etc/sysrepo/yang/internal/" (No such file or directory)
[ERR] libyang initialization failed
[DBG] Notification Processor cleanup requested.
[ERR] Notification Processor initialization failed.
[DBG] Notification Processor cleanup requested.
[ERR] Cannot initialize Request Processor.
[DBG] Request Processor cleanup started, requesting cancel of each worker thread.
[DBG] Request Processor cleanup finished.
[DBG] Session Manager cleanup requested, ctx=0x564346d35480.
[INF] Connection Manager successfully destroyed.
[ERR] Unable to initialize Connection Manager: Initialization failed.
[INF] Connection Manager successfully destroyed.
[INF] Sysrepo daemon terminated.
```

I am not sure how can I solve this issue? Actually, I dot know is there any option to set during build to set this PATH (/etc/sysrepo/yang/internal/)?  

Thanks,
Masoud

**Comment by mashemat** [comment]
I would raise one more question then. Just as a workaround, I tried to copy all the yang models from another installed sysrepo to /etc/sysrepo/yang/internal/. When I go forward, I face that netopeer2-server complains as follows:

```
ERROR: Module "ietf-netconf" feature "writable-running" not enabled in sysrepo. 
```
I saw another thread about this problem (https://github.com/CESNET/Netopeer2/issues/330), and the answer was reinstalling the netopper2-server. Does any other solution for doing that?

Thanks,

**Comment by michalvasko** [comment]
Hi Masoud,
I am trying to help anyone with any issues as best I can and maybe that is why I quickly get frustrated with people that make no effort to resolve their problems and just expect me to do everything for them. Maybe I am being unfair to you but we will see.

I have tried the commands from your first post and the last step finished with a message
```
Install the project...
-- Install configuration: "Release"
-- Installing: /etc/sysrepo
CMake Error at cmake_install.cmake:49 (file):
  file INSTALL cannot make directory "/etc/sysrepo": Permission denied


make: *** [Makefile:86: install] Error 1
```
which is not surprising. When I executed the same command as `root`, it installed and worked just fine. And yes, you can change your repository location by defining a var for cmake
```
cmake -DREPOSITORY_LOC=/etc/sysrepo ..
```

As for your other question I am not sure what exactly you expect. All the commands executed when installing *netopeer2-server* must be executed for it to work properly, otherwise they would not be there. If you at least looked into its `CMakeLists.txt` you would see that there actually is a nice script prepared in case `make install` cannot be executed for whatever reason. So, execute the script with the correct parameters and then the server will start correctly.

Regards,
Michal

**Comment by mashemat** [comment]
Hi Michal,

Actually, what I report maybe useful for someone, recently I post multiple questions, anyway, I appreciate your prompt answers. Something that I am going to do would be interesting since there is not a package for sysrepo. I tried to make my question in short. Basically, I am going to create a docker image with all sysrepo requirement from source. But since the size of docker image becomes big (i.e, almost 800MB) I was going to remove the build folders and just keep the output. So, my first question is basically part of my docker file, so I didn't faced permission denied. 

Here it is my dockerfile (minimal):

```
FROM ubuntu:18.04 as intermediate

WORKDIR /home/test/sysrebuild

RUN mkdir /home/test/sysretest

git clone https://github.com/sysrepo/sysrepo.git
mkdir -p sysrepo/build  
pushd sysrepo/build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/test/sysretest  -DREPOSITORY_LOC=/home/test/sysretest ..
make -j 4 install && popd 

FROM ubuntu:18.04
COPY --from=intermediate /home/test/sysretest /home/test/sysretest
```

"REPOSITORY_LOC" helped me to solve the first problem but I could not make netopeer2-server to run. Actually, I faced the following error:

```
[ERR]: Module "ietf-netconf" not implemented in sysrepo.
[ERR]: Server init failed.
[INF]: Client Subscription Manager successfully destroyed.
[ERR]: nc_ps_session_count: invalid argument (ps).
```
 I see the "ietf-netconf" is "imported" when I run sysrepoctl --list but not "installed:. I am not sure how to install all in one folder.

Thanks,
Masoud

**Comment by michalvasko** [comment]
Hi,
okay and what commands do you use for *netopeer2* installation? That is the problem here.

Regards,
Michal

**Comment by mashemat** [comment]
Thanks Michal. I used the same as sysrepo:

```
git clone https://github.com/CESNET/Netopeer2                                              
mkdir -p Netopeer2/server/build                                                            
pushd Netopeer2/server/build &&  cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/test/sysretest  ..
make -j 4 install && popd
```
Thanks,
Masoud

**Comment by michalvasko** [comment]
Hi,
I am not sure why it does not work that way, it should install everything that is needed. You can take a look at [these](https://github.com/sysrepo/sysrepo/tree/master/deploy/docker) docker files, they should be working. These images are also available [online](https://hub.docker.com/u/sysrepo).

Regards,
Michal

**Comment by mashemat** [comment]
Hi, 

Thanks Michal for your reply. I saw these docker files. Just to know, are the master always stable?

Thanks,
Masoud

**Comment by michalvasko** [comment]
Hi Masoud,
yes, `master` can have non-compatible changes only when `devel` is merged and a new release is made.

Regards,
Michal
