### ISSUE TITLE
subscription listener thread exits when sr_process_events() fails

### ISSUE THREAD

**Issue by barbarost** [sysrepo/sysrepo#1680]
When `sr_process_events()` returns error (e.g. RPC callback times out etc.), subscription listener thread exits, making next RPCs, module change callbacks not to be handled. In that case, should the subscription listener thread continue working?

Thanks!

**Comment by michalvasko** [comment]
Hi,
I am not sure what the correct behavior would be. I think the thread should continue as long as there is no *sysrepo* error. Callback timeout (or any other callback error) is caused (if there is no bug) by the user, so this error is ignored and the thread continues, but no other. This should be the current behavior.

Regards,
Michal

**Comment by barbarost** [comment]
Hi Michal,

If I'm not wrong `sr_process_events()` returns `SR_ERR_INTERNAL` in case of callback timeout.

Regards,
Barbaros

**Comment by barbarost** [comment]
Thank you!
