### ISSUE TITLE
make install failed in Fedora and Centos

### ISSUE THREAD

**Issue by tonyguo-spirent** [sysrepo/sysrepo#1683]
Hi,
When I tried to install sysrepo, it failed on make install, the issue is the same both in Fedora 30 and Centos, following are screen dumps
*********************************************************
- Installing: /home/work/netopeer2/sysrepo/build/repository/data/internal/
-- Installing: /tmp/sysrepo-subscriptions
-- Installing: /usr/local/lib64/sysrepo/plugins
-- Installing: /home/work/netopeer2/sysrepo/build/repository/yang/internal/sysrepo-persistent-data.yang
-- Installing: /home/work/netopeer2/sysrepo/build/repository/yang/internal/sysrepo-module-dependencies.yang
-- Installing: /home/work/netopeer2/sysrepo/build/repository/yang/internal/sysrepo-notification-store.yang
-- Installing: /usr/local/lib64/pkgconfig/libsysrepo.pc
-- Installing: /usr/local/share/man/man1/sysrepoctl.1
-- Installing: /usr/local/share/man/man1/sysrepocfg.1
-- Exec: /home/work/netopeer2/sysrepo/build/src/sysrepoctl --install --yang=/home/work/netopeer2/sysrepo/yang/ietf-netconf-notifications.yang --permissions=666
[ERR] (srctl_ly_log_cb:506) libyang: Regular expression "(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\p{N}\p{L}]+)?" is not valid ("p{N}\p{L}]+)?)$": support for \P, \p, and \X has not been compiled).
[ERR] (srctl_ly_log_cb:506) libyang: Module "ietf-inet-types" parsing failed.
Error: Unable to initialize libyang context.
CMake Error at cmake_install.cmake:139 (message):
  Error: 1
***************************************************
all codes are the latest, what steps am I wrong or what should I do ?  thanks very much.

**Comment by michalvasko** [comment]
Hi,
it seems you have a version of *libpcre* that does not support those expressions mentioned in the error. You will probably have to download and compile it manually with the correct set of options.

Regards,
Michal

**Comment by tonyguo-spirent** [comment]
solved, thanks very much.
