### ISSUE TITLE
New sysrepo: notification with choice statement can't be generated

### ISSUE THREAD

**Issue by huw305** [sysrepo/sysrepo#1685]
### Description
Hello, I'm facing a problem that a notification can't be reported due to leaves under the choice statement. My yang model is as below:
```
 module: mytest
  +--rw test-state
     +--rw test-case* [name]
        +--rw name      string
        +--ro result*
           +--ro x?   uint32
           +--ro y?   uint32
           +--ro z?   uint32

  notifications:
    +---n test-done
    |  +--ro test-result* [name]
    |     +--ro name         -> /test-state/test-case/name
    |     +--ro pass?        boolean
    |     +--ro (element)?
    |        +--:(X)
    |        |  +--ro x?   uint32
    |        +--:(Y)
    |        |  +--ro y?   uint32
    |        +--:(Z)
    |           +--ro z?   uint32
    +---n test-fail
```
The configuration xml is:
```
<test-state xmlns="urn:sysrepo:mytest">
  <test-case>
    <name>one</name>
  </test-case>
  <test-case>
    <name>two</name>
  </test-case>
  <test-case>
    <name>three</name>
  </test-case>
</test-state>
```
My user code to generate the notification:
```
static void prepare_notification_data()
{
	sr_val_t *vals;
	size_t vals_cnt;
	char node_path[256];
	const char *fmt = "/mytest:test-done/test-result[name='%s']/%s";

	vals_cnt = 2;
	if (sr_new_values(vals_cnt, &vals) != SR_ERR_OK) {
		return;
	}

	sprintf(node_path, fmt, "one", "pass");
	sr_val_set_xpath(&vals[0], node_path);
	vals[0].type = SR_BOOL_T;
	vals[0].data.bool_val = true;

	sprintf(node_path, fmt, "one", "x");
	sr_val_set_xpath(&vals[1], node_path);
	vals[1].type = SR_UINT32_T;
	vals[1].data.uint32_val = 101;

	sr_event_notif_send(sess, "/mytest:test-done", vals, vals_cnt);
}
```

**Expected behavior:**
```
notification (2019-11-07T09:40:00Z)
<test-done xmlns="urn:sysrepo:mytest">
  <test-result>
    <name>one</name>
    <pass>true</pass>
    <x>101</x>
  </test-result>
</test-done>
```

**Actual behavior:**
The notification is not reported, and the logs contains nothing.

### Versions
libyang.so.1.3.6
libsysrepo.so.4.0.10
libnetconf2.so.1.1.0
netopeer2-server 1.1.1

### Attachments
[mytest@2019-11-21.zip](https://github.com/sysrepo/sysrepo/files/3873278/mytest%402019-11-21.zip)

Thanks!

**Comment by michalvasko** [comment]
Hi,
I have tried and it worked just fine. Firstly, you should check return value of `sr_event_notif_send()` because it likely failed and it should also print why, if you have logging set properly.

Now, it most likely failed because it did not pass validation. Specifically, the leafref target was not found. The problem here is that you need to have an application subscribed to *running* data of `mytest` for these data to appear in the **operational** datastore, because the notification is validated against that one.

Regards,
Michal

**Comment by huw305** [comment]
Hi Michal,
Thanks for your quick reply.
In my example the leafref points to configuration data so it can be resolved in any case.
```
> get --filter-xpath /mytest:*
DATA
<test-state xmlns="urn:sysrepo:mytest">
  <test-case>
    <name>one</name>
  </test-case>
  <test-case>
    <name>two</name>
  </test-case>
  <test-case>
    <name>three</name>
  </test-case>
</test-state>
```
You're correct that my issue is not caused by choice statement but due to the leafref can't be resolved. 
I added a subscription to "mytest" operational data, and tried to reply some state data in the subscribed callback, after that the notification can be reported.
However, if I do nothing in the subscribed callback (empty function), the notification validation failed again because the unresolved leafref.
The log is as below:
```
Nov  7 13:06:56 sysrepo-plugind[1096]: [INF] Published event "operational" with ID 7.
Nov  7 13:06:56 sysrepo-plugind[1096]: [INF] Processing "operational" "mytest" event with ID 7.
Nov  7 13:06:56 sysrepo-plugind[1096]: [WRN] mytest state callback: mod=mytest, path=/mytest:test-state
Nov  7 13:06:56 sysrepo-plugind[1096]: [INF] Finished processing "operational" event with ID 7.
Nov  7 13:06:56 sysrepo-plugind[1096]: [INF] Event "operational" with ID 7 succeeded.
Nov  7 13:06:56 sysrepo-plugind[1096]: [ERR] Leafref "/test-state/test-case/name" of value "one" points to a non-existing leaf.
Nov  7 13:06:56 sysrepo-plugind[1096]: [ERR] Leafref "/test-state/test-case/name" of value "two" points to a non-existing leaf.
Nov  7 13:06:56 sysrepo-plugind[1096]: [ERR] Leafref "/test-state/test-case/name" of value "three" points to a non-existing leaf.
Nov  7 13:06:56 sysrepo-plugind[1096]: [ERR] Notification validation failed.
Nov  7 13:06:56 sysrepo-plugind[1096]: [ERR] sr_event_notif_send failed, rc=12 (Validation failed).
```
So if a yang model has no operational data but contains only configuration data, and referenced by a leafref in a notification, what should we do in such a case?

Thanks,
Huwei

**Comment by michalvasko** [comment]
Hi,
you still do not understand. Please, firstly familiarize yourself with the definition of [operational](https://tools.ietf.org/html/rfc8342#section-5.3) datastore, it is much more complex than just returning state data. Then, go through the [documentation](https://github.com/sysrepo/sysrepo/blob/devel/doc/subs.dox#L89) on this subject (better to generate it locally). If you still have any questions, let us know.

Regards,
Michal

**Comment by huw305** [comment]
Thanks for the information.
So, in my case the user code will have to provide the configuration data (leafref target) in the subscribed operational data callback. Otherwise the notification validation cannot find it.
Am I right?

**Comment by michalvasko** [comment]
Hi,
strictly speaking, you simply need to make the `operational` datastore contain the leafref target. The simplest way of getting something to be a part of this datastore is to make it **in-use**. In *sysrepo*, you just have to subscribe to some `running` configuration data. This is just like the enabled-data-principle in the old *sysrepo*, it is just standardized in NMDA.

Regards,
Michal
