### ISSUE TITLE
Sysrepo DB read at runtime

### ISSUE THREAD

**Issue by masif-cs** [sysrepo/sysrepo#1686]
Hi,

I want to know is it possible to read sysrepo DB during runtime? For example if an application registers what is the api exposed by sysrepo to playback all DB data related to module subscribed by application?

**Comment by michalvasko** [comment]
Hi,
firstly, are you talking about the new *sysrepo*? Only then we can talk about changing something.

So, what exactly do you mean by sysrepo DB? Currently, there are 2 ways of getting state information of *sysrepo*. You can get the *libyang* context from any `connection` and then call `ly_ctx_info()`. That will get you all the YANG-related information of the installed and imported modules. The other function `sr_get_module_info()`, which is directly provided by *sysrepo*, provides some additional information that you can see processed in the output of `sysrepoctl -l`.

It would be quite simple to add any other data to the returned data tree of the latter function. What information would you be interested in?

Regards,
Michal

**Comment by masif-cs** [comment]
Hi,

Yes I am talking about the new sysrepo from devel branch.
What we want to achieve is application running in different container than sysrepo and still able to get the configuration. Old sysrepo gave the flexibility to use INET so we were able to achieve it, but now with SHM we cant go across containers. So we are writing an application which will be present inside the same container as sysrepo and will register all modules. But now when actual application sitting in different container registers we want to playback data related to those modules.

Is there an api which can give data for specific module/container?

**Comment by michalvasko** [comment]
So you are talking about getting configuration data remotely? Okay, you do not want to use NETCONF but I already told you that you do not need any specific sysrepo API. You just want to have a remote *sysrepo* client.

My idea is to implement a daemon that would call standard *sysrepo* API calls on one end and enable executing them remotely using the other end, by whatever protocol you want. This may not be that simple for all the functionality, but definitely fine for just getting some data.

Regards,
Michal

**Comment by meghna-doshi** [comment]
Hi Michal,
I have attached one figure which gives the use case we are talking about.
So here one "Application" is interested in getting the value of M1/container1/container2/leaf a.
We have our ConfigMgr which has subscribed to sysrepo for module M1.
So now how can the ConfigMgr get the value of "leaf a" from sysrepo running datastore?

Regards,
Meghna

![sysrepo-config](https://user-images.githubusercontent.com/57518465/69714136-e450fc00-112b-11ea-8ec9-791060764c39.gif)

**Comment by michalvasko** [comment]
Hi,
I do not think I understand yet. I need to know what exactly are the interfaces between each component.

*Netopeer* and *sysrepo* are linked together, so I am going to say they have `local sysrepo` interface. The same probably goes for *ConfigMgr*, or is this supposed to be the `remote sysrepo` interface? How *ConfigMgr* and *Application* communicate is probably not important but I cannot be sure. It seems it is just delegating requests, so it can be any `proprietary` protocol, local or remote.

Regards,
Michal

**Comment by meghna-doshi** [comment]
Hi Michal,
As you mentioned, i dont think it is relevant what is interface between Application and ConfigMgr but for your information, it is some proprietary interface.
Since sysrepo has all the configuration values, if runtime, due to some reason, application wants to get value of a particular attribute, then how can we get from sysrepo.

Regards,
Meghna

**Comment by michalvasko** [comment]
Hi Meghna,
you did not clarify much. If *ConfigMgr* on the same machine as *SYSREPO*? If it is, it just calls its API functions to get whatever values it needs. If it is not then this is the place where the new remote *sysrepo* daemon would be, delegating the API calls. But I am not sure what you expect from me, this is not supported currently and will not be anytime soon so you would be on your own.

Regards,
Michal

**Comment by meghna-doshi** [comment]
Hi Michal,
ConfigMgr is in same process as sysrepo. So what API are you referring to here for getting data from sysrepo? Can you please tell us this API.

Regards,
Meghna

**Comment by michalvasko** [comment]
Hi,
I am confused now, these are among the most basic API functions *sysrepo* has. They are all in the [header](https://github.com/sysrepo/sysrepo/blob/devel/src/sysrepo). For example, simple `sr_get_item()` or the most versatile `sr_get_data()`.

Regards,
Michal

**Comment by meghna-doshi** [comment]
Hi Michal,
Oh ok, we started exploring sysrepo recently so were not aware or maybe overlooked these APIs. 
Got it now, will explore and get back if required.

Thanks,
Meghna

**Comment by michalvasko** [comment]
Hi,
in that case you should start by generating the documentation with `make doc` and read through that.

Regards,
Michal
