### ISSUE TITLE
Action NACM Path not working

### ISSUE THREAD

**Issue by gitter-runner** [sysrepo/sysrepo#1688]
Hi!
When using default deny exec rule in NACM, and specifically want to permit the execution of an augmented action using its path, it throws the following error:

```
<?xml version="1.0" encoding="utf-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="17">
  <rpc-error>
    <error-type>protocol</error-type>
    <error-tag>access-denied</error-tag>
    <error-severity>error</error-severity>
    <error-message xml:lang="en">Operation succeeded</error-message>
  </rpc-error>
</rpc-reply>
```

Here's the request:

```
<?xml version="1.0" encoding="utf-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"
     xmlns:yang-1_1="urn:ietf:params:xml:ns:yang:1"
     message-id="1">
  <action xmlns="urn:ietf:params:xml:ns:yang:1">
    <advanced xmlns="urn:com:test">
      <nacm_check xmlns="urn:com:test3"/>
    </advanced>
  </action>
</rpc>
```

I know NACM will be removed from sysrepo2, but until there's no release, I'd prefer to use the original version.

I attached an NACM configuration and the related models (plus a test source file that does the subscriptions).

[nacm_check.zip](https://github.com/sysrepo/sysrepo/files/3901044/nacm_check.zip)

Thanks!

**Comment by michalvasko** [comment]
Hi,
I have taken a look since you provided all the files for reproducing it but now I almost regret it. Actions were deliberately treated as RPCs (there was even a test for that), not as actions. So, it should be fixed now.

Regards,
Michal
