### ISSUE TITLE
[new sysrepo] change iter for list, unable to get parent

### ISSUE THREAD

**Issue by pieterlexis** [sysrepo/sysrepo#1689]
### Things you may try first
(put "x" in "[]" if you already tried following)
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description
I'm using the C++ wrapper, so the examples are in c++.

This might be me holding sysrepo incorrectly, but assume I have the following list:

```yang
[..]
list a {
  key "k";
  leaf k {
    type string;
  }
  leaf v {
    type string;
  }
}
[..]
```

And I have a module_change callback for the module. When I add or remove an entry from the list, I get the full path like this:
```cpp
int MyCB::module_change(sysrepo::S_Session session, const char* module_name,
  const char* xpath, sr_event_t event,
  uint32_t request_id, void* private_data) {
  auto iter = session->get_changes_iter("/module:foo/a");
  auto change = session->get_change_tree_next(iter);

  while (change != nullptr && change->node() != nullptr) {
      cout<<"Node is at /module:foo"<< change->node()->path()<<endl;
     change = session->get_change_tree_next(iter);
  }    
}
```

As `change->node()->path()` contains '/a[k="key_val"]'.

When I *modify* `v` without removing the whole list-node, I can retrieve the modified node like this:

```cpp
  auto iter = session->get_changes_iter("/module:foo/a/*");
  auto change = session->get_change_tree_next(iter);
```

This will gives me the `v` node, if I call `parent()`, it yields a nullptr.

So my question is, how can I get the parent node, or the `k` node when only `v` is changed?

### Versions
Please provide versions for software needed to reproduce the bug:
Sysrepo version: `sysrepocfg - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.3.12 (SO v4.1.0)`
libyang version: `yanglint 1.3.7`

**Comment by michalvasko** [comment]
Hi Pieter,
not sure what was I thinking when I wrote the `Change::node()`, it was creating a disconnected node, which was the problem (it has also caused you needing to prepend `/module:foo` to the path). Please update *sysrepo*, should be fixed.

Regards,
Michal

**Comment by pieterlexis** [comment]
That indeed fixes it. Suddenly things like `find_path()` also work. Would you mind bumping the VERSION so I can set the dependency correctly?

**Comment by michalvasko** [comment]
Hi,
well, we did not want to have too many versions so the C++ bindings have their own but only SO version, which I have bumped. Is that not enough? The main version was meant to be for the C library only.

Regards,
Michal

**Comment by pieterlexis** [comment]
Hi,

My build-system uses pkg-config to find the dependency. Which is 1.3.X (VERSION) in the .pc file for the cpp-bindings. But for now I can wait until a newer version is released, just by being careful with how I release the sysrepo dependency :).

**Comment by michalvasko** [comment]
Alright, there is no harm in bumping the minor version anyway. Done.

Regards,
Michal
