### ISSUE TITLE
why "node is not enabled in running datastore" occured when I try to call "sr_set_item" in running datastore? And how can I enable it?

### ISSUE THREAD

**Issue by fanchanghu** [sysrepo/sysrepo#169]
**log:**
netopeer2-server[17710]: EDIT_CONFIG: leaf /mytest:b/x, operation 1
netopeer2-server[17710]: EDIT_CONFIG: type string (10), value x1
netopeer2-server[17710]: (cl_request_process:401) Sending set-item request.
netopeer2-server[17710]: (cl_request_process:423) set-item request sent, waiting for response.
netopeer2-server[17710]: (cm_conn_read_cb:877) fd 8 readable
netopeer2-server[17710]: (cm_conn_read_cb:890) 47 bytes of data received on fd 8
netopeer2-server[17710]: (cm_conn_read_cb:900) fd 8 would block
netopeer2-server[17710]: (cm_conn_in_buff_process:829) New message of size 43 bytes received.
netopeer2-server[17710]: (sr_cbuff_enqueue:291) Circular buffer enqueue to position=2, current count=1.
netopeer2-server[17710]: (rp_worker_thread_execute:1367) Thread id=140321709696768 signaled.
netopeer2-server[17710]: (sr_cbuff_dequeue:307) Circular buffer dequeue, new buffer head=3, count=0.
netopeer2-server[17710]: (rp_set_item_req_process:381) Processing set_item request.
netopeer2-server[17710]: (dm_load_data_tree_file:407) Loaded module mytest: mtime sec=1464933133 nsec=334644600
netopeer2-server[17710]: (dm_load_data_tree_file:441) Data file /root/swapkvm/fch/z-conf/sysrepo/build/repository/data/mytest.running loaded successfully
netopeer2-server[17710]: (dm_get_data_info:1357) Module mytest has been loaded
netopeer2-server[17710]: (rp_dt_set_item:313) The node is not enabled in running datastore /mytest:b/x
netopeer2-server[17710]: (rp_dt_set_item_wrapper:543) Set item failed
netopeer2-server[17710]: (rp_set_item_req_process:413) Set item failed for '/mytest:b/x', session id=1138069209.

**my yang model:**
module mytest{
  namespace "http://www.mytest.com/";
  prefix "mytest";

  container b{
    leaf x{
      type string;
    }
    leaf y{
      type string;
    }
    leaf z{
      type string;
    }
  }
}

**Comment by lukasmacko** [comment]
While there is no application subscribed for changes made in a module, sysrepo assummes that application configured by the module is either not running or it's not able to modify its running configuration (only its startup configuration, can be edited). In this case model is not enabled in running data store.

Data stores are explained in more detail [here](http://www.sysrepo.org/static/doc/html/ds_page.html)

To enable module an application must be subscribed for the changes. 

For the testing purposes you can use `application_example` binary from the latest master. It subscribes and enables the module specified by the first argument. You can find it in examples directory.

**Comment by fanchanghu** [comment]
Thank you for your reply. And I think I have got it now. But it seems that you push some git conflict flag like "<<<<<<< HEAD" to the file application_example.c. ^_^
