### ISSUE TITLE
question: sysrepo reorders events in edit-config transaction

### ISSUE THREAD

**Issue by igortern** [sysrepo/sysrepo#1693]
Hi,
It appears that sysrepo sometimes reorder events comparing with the order changes appear in edit-config transaction. Is it intentional and is there a way to prevent it?
I tried to subscribe to all subtrees with SR_SUBSCR_CTX_REUSE flag, but it didn't help.
In the following edit config there are 2 "sub-transactions":
1) longish subgroup operating on if:interfaces/if:interface/... It creates an interface network1.201.201
2) subgroup operating on bbf-l2-fwd:forwarders/forwarder, whereas forwarder refers to the interface created in #1 above. 
SR event log in the application shows that SR_EV_VERIFY event is delivered for subgroup #2 first and then #1. It causes problem because interface referred in #2 doesn't exist yet causing validation failure. Is there any way to disable this reordering?

### Versions
sysrepod - sysrepo daemon, version 0.7.8
yanglint 1.2.2
netopeer2-server 0.7.12

Thanks,
Igor Ternovsky

[edit-config.txt](https://github.com/sysrepo/sysrepo/files/3919880/edit-config.txt)

**Comment by igortern** [comment]
Clarification: there are multiple subscriptions, but all subscriptions are done in the context of the same session.

**Comment by michalvasko** [comment]
Hi,
any data changes (commits) are always applied separately for each module. So, if you want to check in a callback on `SR_EV_VERIFY` event of one module that some change also happened in another module, that is not possible.

It should work for `SR_EV_APPLY` event. Also, any dependencies across modules can, naturally, be specified directly in the YANG modules, they will be checked automatically. Is that not possible? I think supporting this would not be too difficult in the new *sysrepo*, but it will definitely not be changed for the one you are using.

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,

Unfortunately YANG models are standard and outside my control. Is it
possible to force dependency using sysrepo?
Basically, I have a single edit config modifying 2 objects in different
modules.
module2.object2 refers to module1.object1 that is modified earlier in the
same edit-config.
Part of module2.object2 validation is checking module1.object1
configuration and it fails because of reorder.

Thanks,
Igor


edit-config

**Comment by igortern** [comment]
Hi Michal,

What kind of dependencies did you have in mind when said "dependencies across modules can, naturally, be specified directly in the YANG modules"? 
I'd like to try it.

Thanks,
Igor

**Comment by michalvasko** [comment]
Hi Igor,
firstly, it seems the new *sysrepo* already does support your use-case and you should see all the changes applied when you ask for data in any callback.

For your other question it really depends on what you want, YANG allows many forms of dependencies. If you require specifically for some leaf to exist with a value, [leafref](https://tools.ietf.org/html/rfc7950#section-9.9) is probably the way to go. If your dependency is a more generic one, [must](https://tools.ietf.org/html/rfc7950#section-7.5.3) or even [when](https://tools.ietf.org/html/rfc7950#section-7.21.5) can describe almost any restriction you can think of.

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,

In my case underlying hardware API doesn't support independent validation
(without applying). Since return code in sysrepo apply callback is ignored,
I'm forced to do validate + apply in sysrepo's validate callback.
Unfortunately, as you pointed out earlier, sysrepo invokes validate
callbacks of different modules in arbitrary order, not the order they
appear in edit-config. So far I haven't found any workaround except for
splitting edit-config in 2 requests, but in practice it is outside my
control.

Thanks,
Igor

**Comment by michalvasko** [comment]
Hi,
I am not sure I understand. It seems you can modify the YANG modules so you can put any restrictions of your hardware directly into the modules (using the statements I have mentioned before) and then you do not have to verify anything in your callbacks. *sysrepo* will make sure the constraints are fulfilled.

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,

There are complex restrictions related to internal resources availability
that can't be verified at YANG level.
The fact that validation callbacks are called in wrong order causes
validation failures.
Ideally would be to be able to force sysrepo generate events in the same
order they appear in edit-config.
Alternatively would be good if priority specified at callback registration
time applied to all events across modules.

Thanks,
Igor

**Comment by michalvasko** [comment]
Hi,
okay, so modifying YANGs is out of the question. Like I said, the new *sysrepo* still uses its internal order of applying edits on different modules but when you request any data in any callback, you will get the data as they will be after the commit succeeds meaning with all edits on all modules applied. That should allow you to verify anything you need, right?

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,
I'll ask customer to split their edit-config in 2 for now. Do you think it
would be possible to add some option in the new sysrepo to make sure that
callbacks are called in the same order changes appear in edit-config,
regardless of modules?
Thanks,
Igor

**Comment by michalvasko** [comment]
Hi,
I will think about whether this ordering could be improved and somehow specified. To begin with, there is the issue of defining priorities of all the callbacks versus your request, the order of edits in the edit-config. But making priorities hold across modules (meaning call one callback from the first module, then another callback from the second module, and then another from the first module) would be quite a lot of additional work and I do not really see the point so what you propose may be fine.

Regards,
Michal

**Comment by michalvasko** [comment]
Okay, it should be applied in the order of the changes (edit-config) themselves (in the new *sysrepo*).

Regards,
Michal

**Comment by igortern** [comment]
Thanks Michal!
