### ISSUE TITLE
Callbacks and threading model for new sysrepo

### ISSUE THREAD

**Issue by iGovindY** [sysrepo/sysrepo#1694]
Documentation of new sysrepo(devel) doesn't talk much about callbacks and threading.

Can you please add more elaboration to the documentation regarding threads. 
What I want to know is, will be there be a single thread for all subscriptions or one thread per subscription?
Does `SR_SUBSCR_CTX_REUSE` play any role in the number of thread created for multiple subscriptions?

**Comment by michalvasko** [comment]
Hi,
I beg to disagree, everything you are asking is documented in detail, please start [here] and then use the links.

Regards,
Michal

**Comment by iGovindY** [comment]
Hi @michalvasko 

Looks you forgot to add link.

**Comment by michalvasko** [comment]
Sorry.

**Comment by iGovindY** [comment]
Adding below for others to know,

Sysrepo provides both ways i.e

-  to have one thread for all subscriptions by an application.
-  to have one thread per subscription.

It is controlled using SR_SUBSCR_CTX_REUSE flag in subscribe API.
