### ISSUE TITLE
sr_get_schema submodule revision

### ISSUE THREAD

**Issue by syyyr** [sysrepo/sysrepo#1695]
### Description
Hello, I have a question about `sr_get_schema`. If it is called with a non-null `submodule_name` argument, which revision of the submodule does it return? The one specified in the main schema? Or does it return the newest version?

Thanks.

### Versions
Sysrepo version: sysrepod - sysrepo daemon, version 0.7.8
libyang version: yanglint 1.3.6

**Comment by michalvasko** [comment]
Hi,
it all depends on the arguments. If the main module is specified, then the submodule from that module is returned. If it is not, then the latest revision found is returned.

Regards,
Michal

**Comment by syyyr** [comment]
Okay, thank you for the answer.
