### ISSUE TITLE
How to upgrade sysrepo from 1.3.7 to 1.3.17 properly

### ISSUE THREAD

**Issue by shenchsh** [sysrepo/sysrepo#1699]
Hi,

I am using the new sysrepo but when I tried to upgrade to version 1.3.17 from 1.3.7, I got
`[ERR]: Invalid context for LYB data parsing, missing module "sysrepo@2019-10-25".
sysrepoctl error: Failed to connect (libyang error)`

So I am wondering what's the proper way to upgrade sysrepo without losing the data?

Thanks,
Chanson

**Comment by michalvasko** [comment]
Hi,
sorry about that, please update *libyang* (`devel` branch) and *sysrepo*, it should work fine then.

Regards,
Michal

**Comment by shenchsh** [comment]
Thanks
