### ISSUE TITLE
Sysrepo Compilation Failing-undefined reference to _assert_true

### ISSUE THREAD

**Issue by akshatagage51** [sysrepo/sysrepo#1701]
Hi,
I am trying to install sysrepo on ubuntu 18.04.
I have cloned the latest sysrepo repository and followed the steps provided in install.md.
Installed following packages,
libxml2, libxml2-dev, libxml2-utils, libxml2-dbg, liburcu-dev, libjson0, libuv1-dev, libuv1, nasm, libnuma-dev, python, yasm, gcc, make, cmake, bison, flex, valgrind, python-dev, lua5.2, libev-dev, libavl-dev, libprotobuf-c-dev, protobuf-c-compiler, swig, build-essential, libpcre3-dev.

Cmocks version : libcmocka.so.0.7.0

Getting following error on make:

_system_helper.c:(.text+0x5d1): undefined reference to _assert_true' CMakeFiles/HELPERS.dir/helpers/system_helper.c.o: In function assert_null_bt':
system_helper.c:(.text+0x61e): undefined reference to _assert_true' CMakeFiles/HELPERS.dir/helpers/system_helper.c.o: In function assert_true_bt':
system_helper.c:(.text+0x657): undefined reference to _assert_true' CMakeFiles/HELPERS.dir/helpers/system_helper.c.o: In function assert_false_bt':
system_helper.c:(.text+0x697): undefined reference to _assert_true' CMakeFiles/HELPERS.dir/helpers/system_helper.c.o: In function assert_string_equal_bt':
system_helper.c:(.text+0x6df): undefined reference to _assert_string_equal' CMakeFiles/HELPERS.dir/helpers/system_helper.c.o: In function assert_int_equal_bt':
system_helper.c:(.text+0x71e): undefined reference to _assert_int_equal' CMakeFiles/HELPERS.dir/helpers/system_helper.c.o: In function assert_int_not_equal_bt':
system_helper.c:(.text+0x8ef): undefined reference to _assert_int_not_equal' CMakeFiles/HELPERS.dir/helpers/nacm_module_helper.c.o: In function new_nacm_config':
nacm_module_helper.c:(.text+0x32): undefined reference to _assert_true' nacm_module_helper.c:(.text+0x5e): undefined reference to _assert_true'
nacm_module_helper.c:(.text+0x8a): undefined reference to _assert_true' CMakeFiles/HELPERS.dir/helpers/nacm_module_helper.c.o: In function save_nacm_config':
nacm_module_helper.c:(.text+0xc9): undefined reference to _assert_int_equal' CMakeFiles/HELPERS.dir/helpers/nacm_module_helper.c.o: In function enable_nacm_config':
nacm_module_helper.c:(.text+0x184): undefined reference to _assert_true' CMakeFiles/HELPERS.dir/helpers/nacm_module_helper.c.o: In function set_nacm_read_dflt':
nacm_module_helper.c:(.text+0x1e2): undefined reference to _assert_true' CMakeFiles/HELPERS.dir/helpers/nacm_module_helper.c.o: In function set_nacm_write_dflt':
nacm_module_helper.c:(.text+0x242): undefined reference to _assert_true' CMakeFiles/HELPERS.dir/helpers/nacm_module_helper.c.o: In function set_nacm_exec_dflt':
nacm_module_helper.c:(.text+0x2a2): undefined reference to _assert_true' CMakeFiles/HELPERS.dir/helpers/nacm_module_helper.c.o: In function enable_nacm_ext_groups':
nacm_module_helper.c:(.text+0x314): undefined reference to _assert_true' CMakeFiles/HELPERS.dir/helpers/nacm_module_helper.c.o:nacm_module_helper.c:(.text+0x3c6): more undefined references to _assert_true' follow
CMakeFiles/HELPERS.dir/helpers/nacm_module_helper.c.o: In function save_nacm_config': nacm_module_helper.c:(.text+0xf5): undefined reference to assert_int_equal'
collect2: error: ld returned 1 exit status
tests/CMakeFiles/values_test.dir/build.make:107: recipe for target 'tests/values_test' failed
make[2]: *** [tests/values_test] Error 1
CMakeFiles/Makefile2:1401: recipe for target 'tests/CMakeFiles/values_test.dir/all' failed
make[1]: *** [tests/CMakeFiles/values_test.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

### Steps to Reproduce
$ cd sysrepo
$ mkdir build; cd build
$ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
$ make

### Versions
Versions for software needed to reproduce the bug:
Sysrepo version: sysrepod - sysrepo daemon, version 0.7.8
libyang version: yanglint SO 1.4.1
netopeer2-server: netopeer2-server 0.7.16

Is there any other library missing?
can you provide some solution?

Thanks!
Akshata

**Comment by michalvasko** [comment]
Hi,
all the required libraries should be detected by CMake but in your case `cmocka` does not seem to be linked properly. However, you have selected `Release` build type so I am not sure why the tests are even build. Still, looking in the `CMakeLists.txt` this should not happen. So, can you post the clean output of cmake? Having empty `build` directory.

Regards,
Michal

**Comment by andywalshe** [comment]
Seeing same issue here in fresh Ubuntu 18.04 vm.
After installing all required libraries and running 'make' the errors start:
...
Scanning dependencies of target md_test
[ 43%] Building C object tests/CMakeFiles/md_test.dir/md_test.c.o
[ 44%] Linking C executable md_test
CMakeFiles/md_test.dir/md_test.c.o: In function `md_test_init_and_destroy':
/home/ubuntu/sysrepo/tests/md_test.c:676: undefined reference to `_assert_int_equal'
/home/ubuntu/sysrepo/tests/md_test.c:677: undefined reference to `_assert_true'
/home/ubuntu/sysrepo/tests/md_test.c:678: undefined reference to `_assert_int_equal'
...

Output from cmake:
ubuntu@build:~/sysrepo/build$ cmake -DCMAKE_BUILD_TYPE=Debug ..
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Preparing developer's build of sysrepo v. 0.7.8
-- sysrepo repository location: /home/ubuntu/sysrepo/build/repository
-- Found ev: /usr/lib/x86_64-linux-gnu/libev.so  
-- Found yang: /usr/local/lib/libyang.so  
-- Found protobuf-c: /usr/lib/x86_64-linux-gnu/libprotobuf-c.so  
-- Found avl: /usr/lib/libavl.so  
-- Could NOT find redblack (missing: REDBLACK_LIBRARY REDBLACK_INCLUDE_DIR) 
-- libavl will be used for binary tree manipulations.
-- Looking for stdatomic.h
-- Looking for stdatomic.h - found
-- Looking for pthread_rwlockattr_setkind_np
-- Looking for pthread_rwlockattr_setkind_np - found
-- Looking for getpeereid
-- Looking for getpeereid - not found
-- Looking for getpeerucred
-- Looking for getpeerucred - not found
-- Looking for include file ucred.h
-- Looking for include file ucred.h - not found
-- Looking for pthread_mutex_timedlock
-- Looking for pthread_mutex_timedlock - found
-- Looking for setfsuid
-- Looking for setfsuid - found
-- Looking for fsetxattr
-- Looking for fsetxattr - found
-- Looking for mkstemps
-- Looking for mkstemps - found
-- Performing Test HAVE_STAT_ST_MTIM
-- Performing Test HAVE_STAT_ST_MTIM - Success
-- Looking for F_OFD_SETLKW
-- Looking for F_OFD_SETLKW - found
-- Example code and YANG models will be built and installed.
-- CMocka found, tests are enabled.
-- Looking for include file regex.h
-- Looking for include file regex.h - found
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Found SWIG: /usr/bin/swig3.0 (found suitable version "3.0.12", minimum required is "3.0.12") 
-- Python version 2 was selected
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.15+", minimum required is "2") 
-- Found PythonInterp: /usr/bin/python2.7 (found version "2.7.15") 
-- Found SWIG: /usr/bin/swig3.0 (found suitable version "3.0.12", minimum required is "3.0.5") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/sysrepo/build

CMocka installed fine:
ubuntu@build:~/cmocka/build$ cat install_manifest.txt 
/usr/local/lib/pkgconfig/cmocka.pc
/usr/local/lib/cmake/cmocka/cmocka-config-version.cmake
/usr/local/include/cmocka.h
/usr/local/include/cmocka_pbc.h
/usr/local/lib/libcmocka.so.0.7.0
/usr/local/lib/libcmocka.so.0
/usr/local/lib/libcmocka.so
/usr/local/lib/cmake/cmocka/cmocka-config.cmake
/usr/local/lib/cmake/cmocka/cmocka-config-debug.cmake

Thanks,
Andy

**Comment by michalvasko** [comment]
Hi,
so you have installed cmocka from source? I am using Ubuntu 18.04 for testing and I had no problem there but I have just installed the package `libcmocka-dev`. Could you please try doing the same?

Regards,
Michal

**Comment by andywalshe** [comment]
Thanks Michal, installation of package `libmocka-dev` has sorted the issues I was seeing. Header files `cmocka.h` and `cmocka_pbc.h` are placed into `/usr/include` using package instead of `/usr/local/include` now.
Regards,
Andy

**Comment by michalvasko** [comment]
Hi Andy,
headers should not have been the problem but rather the library itself, whose path was for some reason not correctly detected when using it compiled from source. But at least it works for you now.

Regards,
Michal
