### ISSUE TITLE
[New-sysrepo] "fake" session for testing?

### ISSUE THREAD

**Issue by pieterlexis** [sysrepo/sysrepo#1705]
To run unit-tests in my own application, I need a sysrepo session to return some (valid) data from a `Session::get_subtree``. I would like the unit tests to _not_ interfere with the existing datastores on the machine.

Is it possible to create a 'fake' Session that would return the things I need. Alternatively, a secondary Datastore (e.g. not in /dev/shm but in $PWD) selectable when creating a connection could work as well.

Is this something that already exists, or could be considered for inclusion?

**Comment by michalvasko** [comment]
Hi,
you would have to define how do you expect this fake session to differ from a standard one. If it is only for getting data then I do not see a reason why you could not use a standard session, the only global effect it has are some read locks I would say (but I would have to look into the code to say for certain).

Regards,
Michal
