### ISSUE TITLE
[new sysrepo] Action not working in augment

### ISSUE THREAD

**Issue by gitter-runner** [sysrepo/sysrepo#1706]
Hi,

Sysrepo throws an internal error when trying to invoke an action of an augment.
I've used the following model which augments interface-action@2019-12-11.yang:

```
module interface-action {
    yang-version 1.1;
    namespace "urn:n:if-action";
    prefix ifaction;

    import ietf-interfaces { prefix if; reference "RFC 8343"; }

    organization
        "N";

    revision 2019-12-11 {
      description
        "Initial version";
    }

    augment "/if:interfaces/if:interface" {
        description
                "Add test action to interfaces.";
        action test {
            description "Test action";
        }
    }
}
```

I can subscribe successfully for a list instance, but invoking the action fails on it:

```
$ ./rpc_subscribe_example "/ietf-interfaces:interfaces/interface[name='eth0']/interface-action:test" &
 Application will subscribe to "/ietf-interfaces:interfaces/interface[name='eth0']/interface-action:test" RPC.



 ========== LISTENING FOR RPC ==========


$ ./rpc_send_example "/ietf-interfaces:interfaces/interface[name='eth0']/interface-action:test"
Application will send RPC "/ietf-interfaces:interfaces/interface[name='eth0']/interface-action:test".

[ERR]: Internal error (/opt/dev/sysrepo/src/shm_mod.c:307).
```

sysrepo version: 1.3.20
libyang version: 1.0.106

Thanks!

**Comment by michalvasko** [comment]
Hi,
I have just pushed a (major) *sysrepo* update, which also happen to include a fix for your issue. So, just pull the latest version. However, you will probably have some problems executing the action successfully using those simple examples, just be aware of [this](https://tools.ietf.org/html/rfc8342#section-6.2) requirement.

Regards,
Michal
