### ISSUE TITLE
rp_init function ignores user-defined sysrepo rtepository location

### ISSUE THREAD

**Issue by igortern** [sysrepo/sysrepo#1707]
Although it is possible to specify sysrepo repository location using hidden '-0' parameter in sysrepoctl and sysrepod executables, this setting doesn't apply 'accross the board'. 
request_processor.c:rp_init() uses build-time constants SR_INTERNAL_SCHEMA_SEARCH_DIR, 
SR_DATA_SEARCH_DIR, SR_SCHEMA_SEARCH_DIR, SR_DATA_SEARCH_DIR;

It is important to be able to specify sysrepo repository location at run time when cross-compiling sysrepo. In this case repository location on the target machine doesn't match location on the build machine. Currently sysrepoctl honours '-0' option for --install operation, but not for --feature-enable.

Regards,
Igor

**Comment by michalvasko** [comment]
Hi Igor,
this parameter is "hidden" for a good reason. You should not need it to cross-compile *sysrepo*. There should be some issues with information about this; after a quick search I have found only #1644 but there should be more.

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,

It is possible to find a workaround so that native and cross sysrepo builds
both point to the same location. However, I believe it is quite
inconvenient. In my case, the repository should be located in /etc/sysrepo
on the target machine, but I don't have write permissions to this directory
on the build machine. I can come up with some trick to work around this,
but having the ability to specify repository location at run time is a good
feature to have IMO.

Thanks,
Igor

**Comment by michalvasko** [comment]
Hi Igor,
nevertheless, you should now be using the new *sysrepo* 1.x, which should be much easier to cross-compile (there is no after-install script needed).

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,

Good idea. I'll try the new sysrepo. Does the same ease of cross
compilation (ie, no post-install scripts) apply to other components, such
as netopeer2-server?
Otherwise, I'll run into the same problem when cross-compiling netopeer2
and using sysrepoctl that was built natively.

Thanks,
Igor

**Comment by michalvasko** [comment]
Hi Igor,
unfortunately, no. But you can define `SYSREPO_REPOSITORY_PATH` and all *sysrepo* applications (including `sysrepoctl` and `sysrepocfg`) will use this path for the repository.

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,

SYSREPO_REPOSITORY_PATH env variable didn't work in the old sysrepoctl for
''--feature-enable" operation, because "request_processor.c:rp_init"
function ignored this setting.
If it is fixed in the new sysrepo - it is perfect.
I'll give it a try.

Thanks,
Igor
