### ISSUE TITLE
can't build examples & tests with custom libyang installation directory

### ISSUE THREAD

**Issue by andrei-pavel** [sysrepo/sysrepo#1712]
Hello,
One way I compile the new sysrepo is:
```
    cmake .. \
      -DCMAKE_BUILD_TYPE=Debug \
      -DCMAKE_C_COMPILER=clang \
      -DCMAKE_CXX_COMPILER=clang++ \
      -DCMAKE_C_FLAGS='-coverage -Wall' \
      -DCMAKE_INSTALL_PREFIX=/opt/sysrepo \
      -DCMAKE_PREFIX_PATH=/opt \
      -DGEN_CPP_BINDINGS=ON \
      -DGEN_LANGUAGE_BINDINGS=ON \
      -DGEN_PYTHON_BINDINGS=ON \
      -DLIBYANG_CPP_INCLUDE_DIR=/opt/libyang/include \
      -DLIBYANG_CPP_LIBRARY=/opt/libyang/lib/libyang-cpp.so \
      -DLIBYANG_INCLUDE_DIR=/opt/libyang/include \
      -DLIBYANG_LIBRARY=/opt/libyang/lib/libyang.so \
      -DREPOSITORY_LOC=/opt/sysrepo-repository \
      -DBUILD_EXAMPLES=OFF \
      -DENABLE_TESTS=OFF \
```
Issue 1. Notice I have language bindings turned on. This is not something I explicitly want to enable, but is required in order to generate the C++ bindings. Otherwise I don't get my `libSysrepo-cpp.so`. It feels like enabling C++ bindings should enable language bindings by default?!

Issue 2. Notice I have a custom `libyang` installation location which is important to me.
Notice I have examples and tests turned off. If I turn them on, I get
```
/usr/bin/ld: cannot find -lyang
```
When linking binaries from the examples directory or from the tests directory.
For some reason for those directories, it only looks in the default library paths instead of the one I gave during cmake.

Could you look please into these?

Thank you,
Andrei

**Comment by andrei-pavel** [comment]
Maybe unrelated,

In `CMakeModules/FindYANG.cmake`
Is this piece of code intended?
```
  if ()
    set(LIBYANG_FOUND TRUE)
  else ()
    set(LIBYANG_FOUND FALSE)
  endif ()
```

**Comment by andrei-pavel** [comment]
`REPOSITORY_LOC` seems to be ignored.

**Comment by michalvasko** [comment]
Hi,
1. The idea is that all language bindings are off by default. If you enable them, C++ and python bindings are both generated by default, so you do not have to define `-DGEN_CPP_BINDINGS=ON` and `-DGEN_PYTHON_BINDINGS=ON`.
2. Should be fixed now.
3. libyang module if - probably not intentional, fixed.
4. `REPOSITORY_LOC` was renamed to `REPO_PATH`.

Regards,
Michal

**Comment by andrei-pavel** [comment]
Thanks!
