### ISSUE TITLE
sysrepo does not create /etc/sysrepo dirctory

### ISSUE THREAD

**Issue by ankit-ka** [sysrepo/sysrepo#1713]
Hi, 

I have noticed that the latest version of sysrepo is not creating the directories /etc/sysrepo and the subdirectories /etc/sysrepo/yang and /etc/sysrepo/data. As a result the yang data modules are not available to sysrepoctl and sysrepocfg. 

This issue is seen after I installed the latest version of sysrepo and Netopeer2 (after 13-Dec-2019).

**Comment by michalvasko** [comment]
Hi,
can you be more specific about what does not work? Yes, the directory is not created during installation because it is always checked that it exist when a new connection is being created.

Regards,
Michal
