### ISSUE TITLE
ietf-interfaces not in netoconf capabilities

### ISSUE THREAD

**Issue by maksimvuleta** [sysrepo/sysrepo#1714]
I had install ietf-interfaces.yang and ietf--routing.yang module like this:
_sysrepoctl --install --yang ietf-interfaces.yang --permissions=666 -L
sysrepoctl --install --yang ietf-routing.yang --permissions=666 -L_

These modules now are in the list:
_sysrepoctl --list
ietf-interfaces            | 2018-02-20 | Installed   | root:root           | 666         |                               |
ietf-routing               | 2018-03-13 | Installed   | root:root           | 666         |                               |_

The sysrepo-plugind is successfully started with:
_sysrepo-plugind -d -D -l4_

And netopeer2-server too:
_netopeer2-server -d -v9
[INF]: Loading schema "ietf-interfaces@2018-02-20" from sysrepo.
[INF]: Reading module "ietf-interfaces".
[INF]: Module "ietf-interfaces@2018-02-20" successfully parsed as implemented.
[INF]: Loading schema "ietf-routing@2018-03-13" from sysrepo.
[INF]: Reading module "ietf-routing".
[INF]: Resolving "ietf-routing" unresolved schema nodes and their constraints...
[INF]: All "ietf-routing" schema nodes and constraints resolved.
[INF]: Module "ietf-routing@2018-03-13" successfully parsed as implemented._

When I run netopeer2-cli and do get, her is the result:

  _<capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
    <capability>urn:ietf:params:netconf:base:1.1</capability>
    <capability>urn:ietf:params:netconf:capability:writable-running:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:validate:1.1</capability>
    <capability>urn:ietf:params:netconf:capability:startup:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:url:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:xpath:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:with-defaults:1.0?basic-mode=explicit&amp;also-supported=report-all,report-all-tagged,trim,explicit</capability>
    <capability>urn:ietf:params:netconf:capability:notification:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:interleave:1.0</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-yang-metadata?module=ietf-yang-metadata&amp;revision=2016-08-05</capability>
    <capability>urn:ietf:params:xml:ns:yang:1?module=yang&amp;revision=2017-02-20</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-inet-types?module=ietf-inet-types&amp;revision=2013-07-15</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-yang-types?module=ietf-yang-types&amp;revision=2013-07-15</capability>
    <capability>urn:ietf:params:netconf:capability:yang-library:1.0?revision=2018-01-17&amp;module-set-id=34</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-acm?module=ietf-netconf-acm&amp;revision=2018-02-14</capability>
    <capability>urn:ietf:params:xml:ns:netconf:base:1.0?module=ietf-netconf&amp;revision=2011-06-01&amp;features=writable-running,candidate,rollback-on-error,validate,startup,url,xpath</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-notifications?module=ietf-netconf-notifications&amp;revision=2012-02-06</capability>
    <capability>urn:ietf:params:xml:ns:netconf:notification:1.0?module=notifications&amp;revision=2008-07-14</capability>
    <capability>urn:ietf:params:xml:ns:netmod:notification?module=nc-notifications&amp;revision=2008-07-14</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-yang-smiv2?module=ietf-yang-smiv2&amp;revision=2012-06-22</capability>
    <capability>urn:ietf:params:xml:ns:yang:smiv2:SNMPv2-TC?module=SNMPv2-TC</capability>
    <capability>urn:ietf:params:xml:ns:yang:smiv2:ieee802-dot1q-fqtss?module=ieee802-dot1q-fqtss&amp;revision=2014-12-15</capability>
    <capability>urn:tttech:bu-industrial:yang:sysrepo-module-versions?module=sysrepo-module-versions&amp;revision=2019-09-26</capability>
    <capability>urn:ietf:params:xml:ns:yang:smiv2:IEEE8021-TC-MIB?module=ieee8021-tc&amp;revision=2013-02-05</capability>
    <capability>urn:ietf:params:xml:ns:yang:smiv2:IANAifType-MIB?module=IANAifType-MIB&amp;revision=2014-07-03</capability>
    <capability>urn:ietf:params:xml:ns:yang:smiv2:IF-MIB?module=IF-MIB&amp;revision=2000-06-14</capability>
    <capability>urn:ietf:params:xml:ns:yang:smiv2:BRIDGE-MIB?module=BRIDGE-MIB&amp;revision=2005-09-19</capability>
    <capability>urn:ietf:params:xml:ns:yang:smiv2:snmp-framework-mib?module=snmp-framework-mib&amp;revision=2002-10-14</capability>
    <capability>urn:ietf:params:xml:ns:yang:smiv2:ieee8021-mstp?module=ieee8021-mstp&amp;revision=2012-08-10</capability>
    <capability>urn:ietf:params:xml:ns:yang:iana-crypt-hash?module=iana-crypt-hash&amp;revision=2014-08-06</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-x509-cert-to-name?module=ietf-x509-cert-to-name&amp;revision=2014-12-10</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-system?module=ietf-system&amp;revision=2014-08-06&amp;features=authentication,local-users</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults?module=ietf-netconf-with-defaults&amp;revision=2011-06-01</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring?module=ietf-netconf-monitoring&amp;revision=2010-10-04</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-routing?module=ietf-routing&amp;revision=2018-03-13</capability>
  </capabilities>_

There is no ietf-interfaces in capabilties, only ietf-routing is there.

**Comment by michalvasko** [comment]
Hi,
that is actually quite weird because I would expect even `ietf-routing` not to show up but it depends on the exact module you have used. YANG 1.1 modules are not in the capabilities but in [ietf-yang-library data instead](https://tools.ietf.org/html/rfc7950#section-5.6.4).

Regards,
Michal

**Comment by maksimvuleta** [comment]
Yes,
My module is yang 1.1. 

Thank you for fast response.

Best Regards,
Maksim.
