### ISSUE TITLE
Sysrepod command not found

### ISSUE THREAD

**Issue by ChinmayaAgarwal** [sysrepo/sysrepo#1715]
I've cloned and installed sysrepo and it got installed successfully with no error. But, when i am executing "sysrepod" to start sysrepo, it shows me "command not found error". 
As sysrepod command is not found, I am not able to run sysrepo and on running netopeer2 server, it terminates abruptly showing the below logs
[INF]: LY: All "ietf-sr-policy" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-sr-policy@2019-11-04" successfully parsed as implemented.
[INF]: LY: Module "ietf-sr-policy-types@2019-11-04" now implemented.
[INF]: SR: No scheduled changes.
[ERR]: SR: Locking a mutex failed (sr_shmmain_lock_remap: Connection timed out).
[ERR]: NP: Connecting to sysrepo failed (Timeout expired).
[ERR]: NP: Server init failed.
[INF]: NP: Server terminated.
I wasn't facing this issue till friday (13th December, 2019) but after that this issue is coming repeatedly.
Kindly suggest what could have gone wrong?

**Comment by ChinmayaAgarwal** [comment]
As sysrepod command is not found, I am not able to run sysrepo and on running netopeer2 server, it terminates abruptly showing the below logs 
[INF]: LY: All "ietf-sr-policy" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-sr-policy@2019-11-04" successfully parsed as implemented.
[INF]: LY: Module "ietf-sr-policy-types@2019-11-04" now implemented.
[INF]: SR: No scheduled changes.
[ERR]: SR: Locking a mutex failed (sr_shmmain_lock_remap: Connection timed out).
[ERR]: NP: Connecting to sysrepo failed (Timeout expired).
[ERR]: NP: Server init failed.
[INF]: NP: Server terminated.

**Comment by michalvasko** [comment]
Hi,
you may have some stale connections after crashed clients. You can check that with `sysrepoctl -C`. If there are some, you can try to recover them with `sysrepoctl -R` but it does not work in every case. Then you must reset the shared memory with `make shm_clean`.

As for `sysrepod` existence, please refer to [documentation](http://www.sysrepo.org/static/doc/html/index.html#principles).

Regards,
Michal

**Comment by Ramanpreet19** [comment]
Hey @ChinmayaAgarwal, 

I am also facing the same issue. How you debugged this issue. 

Thanks, 
Raman
