### ISSUE TITLE
Cannot find 'oven-state'

### ISSUE THREAD

**Issue by psch-k** [sysrepo/sysrepo#1716]
Hi,
I'm just switching to the new sysrepo / new netopeer2 etc. Installations seem to be ok, but one of my regression tests (using the oven example) fails:
After serving the oven via netopeer2-cli / -server (turning on the oven, inserting food, waiting for the ready-notification), I do a "get --filter-xpath /oven:*"
The OLD sysrepo (upto v0.7.8) gave this output:
```
DATA
<oven xmlns="urn:sysrepo:oven">
  <turned-on>true</turned-on>
  <temperature>200</temperature>
</oven>
<oven-state xmlns="urn:sysrepo:oven">
  <temperature>200</temperature>
  <food-inside>false</food-inside>
</oven-state>
```
The NEW sysrepo omits the <oven-state ... </oven-state> container completely. Thus, I cannot check whether food is still inside ...
Even if I do  a global 'get --out ex.xml', there is no <oven-state> in it.

Any idea, what's going wrong? There are neither errors nor even warnings in the sysrepo-plugind and betopeer2-server logs.

Checked with the latest tagged versions  as well with the actual master-branch:
Tagged versions:
  libyang: v1.0.109
  libnetconf2: v1.1.3
  sysrepo: v1.3.21
  Netopeer2: v1.1.1
Commit IDs of master branch:
  libyang: 402ab07a, Fri Dec 13 14:23:19 2019 +0100 (same as tagged version)
  libnetconf2: 73bbfab9, Fri Dec 13 15:20:48 2019 +0100 (same as tagged version)
  sysrepo: 70454826, Mon Dec 16 14:52:33 2019 +0100
  Netopeer2: 2c9a7c63, Fri Dec 13 15:33:29 2019 +0100 (same as tagged version)

Kind regards,
Peter

**Comment by michalvasko** [comment]
Hi Peter,
yes, there was a problem with returning state data, please try the latest `devel`.

Regards,
Michal

**Comment by psch-k** [comment]
Hi,
I retried it with the latest devel branch of sysrepo; this wasn't enough, nothing changed. Switching also libyang as well as libnetconf2 to their devel branches solved this issue, I can now check via netconf whether my food is still in the oven ...
Thanks, Michal!
Kind Regards,
Peter

**Comment by michalvasko** [comment]
Hi,
there are very few and only irrelevant changes in the other `devel` branches so I think you have fixed it by reinstalling `liboven.so` while updating. I may have mentioned that the problem was specifically in the oven plugin, not in *sysrepo*.

Regards,
Michal

**Comment by psch-k** [comment]
Hi,
I just rechecked what I've done and I noticed, that my test of using the devel branch of sysrepo and the latest tagged versions of the others was incorrect: After checking out the devel branch of sysrepo, I checked out v1.3.21 of sysrepo ... thanks to too much copy & paste ... B-///
Therefore, I recall my statement, that I had to use also the development branches of the others. Sorry about that, I apologize.
Kind Regards,
Peter
