### ISSUE TITLE
Connecting to sysrepo without datastore 

### ISSUE THREAD

**Issue by vishalearnz** [sysrepo/sysrepo#1718]
Hi ,
 
Is it possible to use our own db instead of datastore of sysrepo ?
I have my own db which gets updated by various channel at runtime , it can send data either from its own db or from other sources without even updating its own database . 
So I need to know , if I can connect Netopeer and sysrepo but not use the existing datastore.
If its possible , can you help me with the api's of sysrepo which will help me connecting my own db.

Thanks & Regards,
Vishal

**Comment by michalvasko** [comment]
Hi,
no, currently this is not possible. But we may implement custom datastore support next year, it is not decided yet.

Regards,
Michal

**Comment by vishalearnz** [comment]
ok thanks for the response . Closing the issue
