### ISSUE TITLE
sysrepo-plugind does not start due to missing PLUGINS_PATH

### ISSUE THREAD

**Issue by hthiery** [sysrepo/sysrepo#1719]
sysrepo-plugind fails with the following error:

`sysrepo-plugind error: Opening "<MY_SYSROOT_PATH>/lib/sysrepo/plugins" directory failed (No such file or directory).`

I see that the PLUGINS_PATH is not created during install step. Is this a known behavior? Do we have to create this package outside of the build/install step?

**Comment by michalvasko** [comment]
Hi,
I am not sure whether to bother fixing this. The directory does not exist -> there is no plugin -> why start *sysrepo-plguind*? When you install a plugin, you must put it into the correct path so you will also create the directory.

Regards,
Michal

**Comment by hthiery** [comment]
hmm ... ok I understand. I just want to create a buildroot package with that. This includes an init script that tries to start the sysrepo-plugind but fails because the directory is not there.

I dont know if it is ok to have a failing init during startup?

What do you think?

**Comment by michalvasko** [comment]
Okay, *sysrepo-plugind* creates it now if it does not exist.

Regards,
Michal

**Comment by hthiery** [comment]
ok .. thank you.

**Comment by hthiery** [comment]
Unfortunately the patch does not work because it does not create the directory recursivly.

**Comment by michalvasko** [comment]
Right, sorry, not sure why I thought it is recursive.

Regards,
Michal
