### ISSUE TITLE
is it possible to create multible datastore sets?

### ISSUE THREAD

**Issue by tonyguo-spirent** [sysrepo/sysrepo#1721]
Hi, I wanna know if it's possible to create multible datastore sets by changing sysrepo code? for example, I want to create 100 sets of datastores, each set includes running, startup and candidate datastore. if possible, is it easy for changing the code?

**Comment by michalvasko** [comment]
Hi,
well, *sysrepo* is written in C so everything is possible technically. However, I think you are underestimating the complexity of your modification. For starters, how would you know what datastore instance should every edit, get, or subscription use? YANG defines one global datastore and that is what *sysrepo* will always officially support.

Regards,
Michal

**Comment by tonyguo-spirent** [comment]
we can let different port map different datastore set, thus will be much easy. thanks very much

**Comment by michalvasko** [comment]
It is up to you, of course, what modifications you will do but *sysrepo* itself has no remote interface so this solution does not really apply. But like I said, I will leave you to it.

Regards,
Michal
