### ISSUE TITLE
Loading tree from xml file question

### ISSUE THREAD

**Issue by Roky7250** [sysrepo/sysrepo#1722]
Hi, I have question related to loading tree from xml file.
I created test yang module which is the whole config false. 
I created xml file based on that yang file and it contains filled containers, lists and leafs.

Now, I want to load that xml file as tree, so I can use it inside program and iterate true it, print node name, value and so on. I tried to use **lyd_parse_fd** function, but I did not manage to do it.
I did not manage to load tree and iterate true it using pointers to next, prev, child and so on.

Can you please point to how to do it if it is possible?

On netopeer1 I used **xmlReadFile** and **xmlDocGetRootElement** functions that worked fine.

Thanks in advance
Best Regards

**Comment by michalvasko** [comment]
Hi,
I am sorry you did not manage to do it but I assure you it is possible. If you have a file, the easiest is to use `lyd_parse_file()`. You are saying you have only state data so you should use `LYD_OPT_DATA` flag for parsing. Additionally, if there are some mandatory configuration nodes that you want to intentionally leave out, you can add `LYD_OPT_TRUSTED` flag to prevent *libyang* from complaining.

Regards,
Michal

**Comment by Roky7250** [comment]
Hi, this is my test code:

```
int fd = -1;

struct lyd_node *root = NULL;
struct ly_ctx *ctx = NULL;

ctx = ly_ctx_new("PATH_TO_YANG_FILE", 0);

if (!ctx) {
    printf("\n\n ctx is NULL \n\n");
}
else
    printf("\n\n ctx != NULL \n\n");


fd = open("TEST_FILE_PATH", O_RDONLY);

if (-1 == fd)
{
    printf("\n\n Unable to open the startup datastore file for test module! \n\n");
    close(fd);
}
else
    printf("\n\n File opened! \n\n");


root = lyd_parse_fd(ctx, fd, LYD_XML, LYD_OPT_DATA | LYD_OPT_TRUSTED);

if (root)
{
    printf("\n\n %s \n\n", root->attr->name);

    if(root->child)
    {
        printf("\n\n %s \n\n", root->child->attr->name);
    }
}
else
    printf("\n\n root is NULL! \n\n");

if (root)
    lyd_free(root);
if (ctx)
    ly_ctx_destroy(ctx, NULL);
if (fd > 0)
    close(fd);
```

I'm getting segmentation fault, inside  **printf("\n\n %s \n\n", root->attr->name);**.
Can you please take a look of code and see where my mistake is.
Maybe I do not understang how this struct attr is used.

Thanks in advance
Best regards

**Comment by michalvasko** [comment]
Hi,
you do not have the correct context. If you have a simple YANG module instead of
```C
ctx = ly_ctx_new(PATH_TO_YANG_FILE, 0);
```
you should do something like this
```C
ctx = ly_ctx_new(NULL, 0);
mod = lys_parse_path(ctx, PATH_TO_YANG_FILE, LYS_YANG);
```
and then check that `mod` is non-null.

Regards,
Michal

**Comment by Roky7250** [comment]
Thank you for advice, it worked. Later I tried this combination and it also worked:

```
ctx = ly_ctx_new(PATH_TO_YANG_FILE, 0);
module = ly_ctx_load_module(ctx, SR_TEST_MODULE_NAME_STR, NULL);
root = lyd_parse_fd(ctx, fd, LYD_XML, LYD_OPT_DATA | LYD_OPT_TRUSTED);
```
Thanks again, regards.
