### ISSUE TITLE
[New sysrepo query]: Installing YANG schema dynamically

### ISSUE THREAD

**Issue by mabukar** [sysrepo/sysrepo#1723]
Is dynamic installation of YANG schema files with "sysrepoctl -i" supported in the new design? Or are all YANG schemes required to be pre-installed before starting Netopeet2 server and any other Sysrepo applications?

**Comment by michalvasko** [comment]
Hi,
to answer, "dynamic installation of YANG schemas" is supported only partially and yes, it is best to install all modules before running *netopeer2* or any other *sysrepo* applications. You can find more information in the [documentation](http://www.sysrepo.org/static/doc/html/schema.html).

Regards,
Michal

**Comment by sriramkandukuri** [comment]
The working [link](https://netopeer.liberouter.org/doc/sysrepo/devel/schema.html)
