### ISSUE TITLE
build the examples ERROR

### ISSUE THREAD

**Issue by dwbxm** [sysrepo/sysrepo#1725]
Hi,
When I build the examples, ERROR is output.
cd /root/sysrepo/examples
mkdir build;cd build
cmake ..
make 

Then , ERROR is output:

**Scanning dependencies of target oper_data_example
[ 72%] Building C object CMakeFiles/oper_data_example.dir/oper_data_example.c.o
[ 77%] Linking C executable oper_data_example
/usr/bin/ld: CMakeFiles/oper_data_example.dir/oper_data_example.c.o: undefined reference to symbol 'lyd_new_path'
//usr/lib64/libyang.so.1: 无法添加符号: DSO missing from command line
collect2: 错误：ld 返回 1
make[2]: *** [CMakeFiles/oper_data_example.dir/build.make:84：oper_data_example] 错误 1
make[1]: *** [CMakeFiles/Makefile2:290：CMakeFiles/oper_data_example.dir/all] 错误 2
make: *** [Makefile:84：all] 错误 2**

But I execute the following operation, the error is not output.
cd /root/sysrepo/
mkdir build;cd build
cmake ..
make 

Then I found the oper_data_example in the directory of build/examples/ .

The solution of the problem is this:
Add that in /root/sysrepo/examples/CMakeLists.txt

**target_link_libraries(${app_name} sysrepo yang)**.

**Comment by michalvasko** [comment]
Hi,
are you using the latest (`1.3.27`) *sysrepo*? I have made some fixes in how some things were linked. Your fix should not be needed because `sysrepo` is linked with `yang` and this dependency is [transitive](https://cmake.org/cmake/help/v3.0/command/target_link_libraries.html) so it should be enough to link the examples with `sysrepo`.

Regards,
Michal

**Comment by bbergquist0930** [comment]
This error still exists with the latest build off the 'devel' branch on Ubuntu 18.04

I cloned and built and installed the latest on the development branch of

- libyang
- sysrepo

Here is what I get when I try to build the examples

```
 61%] Building C object CMakeFiles/sr_get_items_example.dir/sr_get_items_example.c.o
[ 66%] Linking C executable sr_get_items_example
[ 66%] Built target sr_get_items_example
Scanning dependencies of target oper_data_example
[ 72%] Building C object CMakeFiles/oper_data_example.dir/oper_data_example.c.o
[ 77%] Linking C executable oper_data_example
/usr/bin/ld: CMakeFiles/oper_data_example.dir/oper_data_example.c.o: undefined reference to symbol 'lyd_new_path'
//usr/local/lib/libyang.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/oper_data_example.dir/build.make:94: recipe for target 'oper_data_example' failed
make[2]: *** [oper_data_example] Error 1
CMakeFiles/Makefile2:289: recipe for target 'CMakeFiles/oper_data_example.dir/all' failed
make[1]: *** [CMakeFiles/oper_data_example.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
brett@brett-Precision-7740:~/git/netconf/sysrepo/examples/build$ 
```
The '//usr/local/lib/libyang.so.1' looks suspicious with the '//' in the path.  I have not figured that out yet.

**Comment by bbergquist0930** [comment]
The linked version of libsysrepo looks like it has the correct library dependencies listed 

```
brett@brett-Precision-7740:~/git/netconf/sysrepo/examples/build$ ldd /usr/local/lib/libsysrepo.so.5.2.5 
	linux-vdso.so.1 (0x00007ffc919ed000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f4090491000)
	libyang.so.1 => /usr/local/lib/libyang.so.1 (0x00007f4090147000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f408ff28000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f408fb37000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f408f933000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f408f6c1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4090900000)
```

**Comment by michalvasko** [comment]
Hi,
can you please try adding `${LIBYANG_LIBRARIES}` [here](https://github.com/sysrepo/sysrepo/blob/master/examples/CMakeLists.txt#L12)? But I am obviously missing something because I do not understand why it fails to be linked. But it does not happen on all the platforms it seems.

Regards,
Michal

**Comment by bbergquist0930** [comment]
I rebuilt the latest version today on the `devel` branch and wanted to test a theory on this.  I actually cleaned out all of libyang, libnetconf2, netopeer2-{server,cli}, and sysrepo, and rebuilt everything.  This time after building and installing libyang I ran `ldconfig`.  When I built the sysrepo examples I did not make the above change and it built without the change.  

So like you, I see it can work.  I believe it will work if `ldconfig` is run after libyang is installed and before building the examples.  If I get a chance today, I will repeat this same process two more times, to get a reproducible test case, once without running `ldconfig` and once with `ldconfig` and observe the result and report back here.

**Comment by Reshad-Rahman** [comment]
I ran into the same error. I tried running ldconfig before building the examples but that didn't help. The diff above helped.
`
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
`

**Comment by michalvasko** [comment]
Are you by any chance building the examples separately? You are supposed to configure only the main `CMakeLists.txt`, all the others are used recursively.

**Comment by Reshad-Rahman** [comment]
> Are you by any chance building the examples separately? You are supposed to configure only the main `CMakeLists.txt`, all the others are used recursively.

Yes I was trying to build the examples separately. I did that, from what I recall, because I couldn't get the examples to build while using the main CMakeLists.txt. Let me try that again.
