### ISSUE TITLE
sysrepo fails to handle union datatype

### ISSUE THREAD

**Issue by iGovindY** [sysrepo/sysrepo#1727]
#### Steps:
1. added below leaf in oven module under container oven.

```
leaf u {
      type union {
        type uint8;
        type string;
      }
 }

```

2. subscribe using 
`./application_changes_example oven `

 3. edit-config with below
```
<oven xmlns="urn:sysrepo:oven2" >
     <u>27</u>
</oven>
```

4. Getting below error
 ```
========== LISTENING FOR CHANGES ==========

[ERR]: Internal error (/home/airvana/govind/newNETCONF/sysrepo/src/shm_sub.c:1883).

```

**Without subscribing edit-config works fine.**
though after that, subscribing to oven module throws error.

**Comment by michalvasko** [comment]
Hi,
I have failed to reproduce this with the latest *sysrepo* `devel` and your lines do not match so please update it (and *libyang* if you do not have the latest version), clear it (`make sr_clean`) and try again.

Regards,
Michal
