### ISSUE TITLE
Cannot create list item with sr_set_item() with NULL value

### ISSUE THREAD

**Issue by iljatab** [sysrepo/sysrepo#1733]
sysrepocfg - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.3.30 (SO v4.1.17)

The sr_set_item() call does not accept NULL for "value" argument.
This used to work with old sysrepo.
Documentation for new sysrepo also states
    "To create a list use xpath with key values included and pass NULL as value argument."

Instead sr_set_item() returns "Invalid arguments for function "sr_set_item".

IMHO the issue looks obvious from implementation at sysrepo.c:1950:

```
API int
sr_set_item(sr_session_ctx_t *session, const char *path, const sr_val_t *value, const sr_edit_options_t opts)
{
    sr_error_info_t *err_info = NULL;
    char str[22], *str_val;

    SR_CHECK_ARG_APIRET(!session || !value || (!path && !value->xpath), session, err_info);

    str_val = sr_val_sr2ly_str(session->conn->ly_ctx, value, str);
    if (!path) {
        path = value->xpath;
    }

    /* API function */
    return sr_set_item_str(session, path, str_val, value->origin, opts);
}
```

SR_CHECK_ARG_APIRET() explicitly disallows value == NULL.

**Comment by michalvasko** [comment]
Hi,
right, it should work properly now.

Regards,
Michal

**Comment by iljatab** [comment]
Looks better, thanks!
