### ISSUE TITLE
Cannot create Val with decimal64

### ISSUE THREAD

**Issue by andrei-pavel** [sysrepo/sysrepo#1734]
Hello,

I've modified the model in my sysrepo example to include a SR_DECIMAL64_T in develop branch https://github.com/andrei-pavel/sysrepo-example/tree/develop (commit be14c3c92960ed06ec60f93e27322f8c8145c2ec).

If I run the steps, I get:
```
libyang[0]: Invalid arguments (ly_ctx_get_node()).
libyang[0]: Invalid value "" in "floating" element. (path: /model:config/le_list[name='whatever']/contained/floating)
libyang[0]: Failed to create node "floating" as a child of "contained". (path: /model:config/le_list[name='whatever']/contained/floating)
terminate called after throwing an instance of 'sysrepo::sysrepo_exception'
  what():  Invalid argument
```

The problems seems to be with creating the `Val(13.37)` or any other floating-point value. Can you replicate this? I couldn't find an example or a unit test that deals with decimals.

Thanks,
Andrei

**Comment by andrei-pavel** [comment]
If I modify the `decimal64` to `int64`, it works well.

**Comment by andrei-pavel** [comment]
Tried both master and devel branches.

**Comment by michalvasko** [comment]
Hi,
it should work now. But why are you not using `sr_set_item_str()`? It would save you the trouble of having to create a value structure.

Regards,
Michal

**Comment by andrei-pavel** [comment]
Hello,

Works, thank you, I will take a look at `sr_set_item_str()` at a later time.

Best Regards,
Andrei

**Comment by andrei-pavel** [comment]
Well, actually for that particular case in the sysrepo-example, now I get:
```
Invalid value "13.369999999999999218" in "floating" element.
```
when passing `13.37` as value.

But it works with my other application.

**Comment by andrei-pavel** [comment]
Just to clarify, `13.37` is passed from inside the application.

**Comment by michalvasko** [comment]
Hi,
maybe you pass `13.37` from the application, but `sr_val_t` `decimal64_val` is a `double`, which obviously stores this value as `13.369999999999999218`. Nothing I can do to fix this, it will work just fine if you use `sr_set_item_str()` like I advised before.

It is a simplification, just replace
```C++
session->set_item("/model:config/le_list[name='whatever']/contained/floating",
                        std::make_shared<Val>(13.37));
```
with
```C++
session->set_item_str("/model:config/le_list[name='whatever']/contained/floating",
                        "13.37");
```

Regards,
Michal

**Comment by andrei-pavel** [comment]
And then it gets converted to the appropriate type in libyang's `lyp_parse_value`, that's awesome.

Tried your suggestion and now I get
```
libyang[0]: Invalid value "13.37" in "floating" element. (path: /model:config/le_list[name='whatever']/contained/floating)
```

Tried "13,37" since I thought it might get influenced by locale, but that didn't work either.
"13" doesn't work either.

Can you look at the current master of `sysrepo-example`? Am I doing something wrong?

This is low priority for me.

**Comment by michalvasko** [comment]
Hi,
that is just a *libyang* error and it is correct, in the model the value has `range` `0 .. 1` so none of those values are valid.

Regards,
Michal
