### ISSUE TITLE
[New sysrepo] multiple search directories not supported

### ISSUE THREAD

**Issue by jjin62** [sysrepo/sysrepo#1738]
**Old sysrepo** 
(sysrepoctl) support multiple search-dir=<dir1> search-dir=<dir2>.

**new sysrepo**
if provided with more than one search dir
_sysrepoctl error: Search dir already specified_

**Comment by michalvasko** [comment]
Hi,
you are right, but now that these functions are in API, it would have to be changed in order to add support for multiple search directories. Once there is some other API change, I will also implement this one.

Regards,
Michal

**Comment by jjin62** [comment]
Can we support --search-dir=dir1:dir2:dir3, same as linux PATH string? So no need to changer_sr_install_module API, but calling ly_ctx_set_searchdir multiple times in sr_parse_module()??

**Comment by michalvasko** [comment]
Hi,
right, sounds good. Should work this way now and `sysrepoctl` has an updated parameter.

Regards,
Michal

**Comment by jjin62** [comment]
Thanks Michal for your quick response.
