### ISSUE TITLE
link error of cross comple  within examples

### ISSUE THREAD

**Issue by Jamwe** [sysrepo/sysrepo#1739]
when porting to arm-linux-gcc, I get this error, but libyang is installed already.

[ 56%] Linking C executable oper_data_example
/>>arm-linux-gcc toolchain<</arm-broadcom-linux-gnueabi/bin/ld: cannot find -lyang
collect2: error: ld returned 1 exit status
make[2]: *** [examples/oper_data_example] Error 1
make[1]: *** [examples/CMakeFiles/oper_data_example.dir/all] Error 2
make: *** [all] Error 2

Finally, I modify  sysrepo/examples/CMakeLists.txt  line 12 from "target_link_libraries(${app_name} sysrepo yang)"  to "target_link_libraries(${app_name} sysrepo ${LIBYANG_LIBRARIES})".  
ld now works well.  But i'm poor of cmake,  know nothing of this syntax.

**Comment by michalvasko** [comment]
Hi,
if you use the current `devel` it should be fixed there. It is not even needed to link *libyang* to the examples separately because *sysrepo* is already linked with it, it is transitive.

Regards,
Michal

**Comment by Jamwe** [comment]
Thanks for explanation. The version I use is the release, now it's linked correctly.
