### ISSUE TITLE
The output of "sysrepoctl -l" is  empty

### ISSUE THREAD

**Issue by Arvliu** [sysrepo/sysrepo#1741]
Hi,
I downgraded the sysrepo from 0.7.8 to 0.7.4.  After cross-compilation and ransplanted to ARM,
"sysrepod" is run ok, but output of "sysrepoctl -l" is empty.
Sysrepo schema directory: /etc/sysrepo/yang/
Sysrepo data directory:   /etc/sysrepo/data/
(Do not alter contents of these directories manually)

Module Name| Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------

Could you help to  solve this issue? Thanks in advance.

**Comment by michalvasko** [comment]
Hi,
I have no idea what the problem may be, it is impossible to know from this information. Anyway, trying to solve issues with downgrading is quite an odd thing to do and seems like a waste of time.

Regards,
Michal
