### ISSUE TITLE
[new sysrepo] can not uninstall a module 

### ISSUE THREAD

**Issue by jjin62** [sysrepo/sysrepo#1742]
**version**
latest devel
$ sysrepoctl -V
sysrepocfg - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.3.37 (SO v4.1.23)

sysrepoctl -l
Sysrepo repository: /home/jimmy/shasta/apps_pub/sysrepo/build/repository

Module Name                | Revision   | Flags | Owner       | Permissions | Submodules | Features
ietf-netconf               | 2011-06-01 | I     | jimmy:jimmy | 666         |            |         
ietf-netconf-notifications | 2012-02-06 | I     | jimmy:jimmy | 666         |            |         
ietf-netconf-with-defaults | 2011-06-01 | I     | jimmy:jimmy | 666         |            |         
ietf-origin                | 2018-02-14 | I     | jimmy:jimmy | 666         |            |         
ietf-yang-library          | 2019-01-04 | I     | jimmy:jimmy | 666         |            |         
yang                       | 2017-02-20 | I     | jimmy:jimmy | 666         |            |         

Flags meaning: I - Installed/i - Imported; R - Replay support; N - New/X - Removed/U - Updated; F - Feature changes

**uninstall ietf-netconf**

$ sysrepoctl -u ietf-netconf
jimmy@grpc-vm:~/shasta/yang-model/oplink/device$ sysrepoctl -l
Sysrepo repository: /home/jimmy/shasta/apps_pub/sysrepo/build/repository

Module Name                | Revision   | Flags | Owner       | Permissions | Submodules | Features
ietf-netconf               | 2011-06-01 **| I R   |** jimmy:jimmy | 666         |            |         
ietf-netconf-notifications | 2012-02-06 | I     | jimmy:jimmy | 666         |            |         
ietf-netconf-with-defaults | 2011-06-01 | I     | jimmy:jimmy | 666         |            |         
ietf-origin                | 2018-02-14 | I     | jimmy:jimmy | 666         |            |         
ietf-yang-library          | 2019-01-04 | I     | jimmy:jimmy | 666         |            |         
yang                       | 2017-02-20 | I     | jimmy:jimmy | 666         |            |         

Flags meaning: I - Installed/i - Imported; R - Replay support; N - New/X - Removed/U - Updated; F - Feature changes

ietf-netconf still show up, and the flag change from I to R
same behavior if I try to uninstall other modules.

how do I remove a module completely?

**Comment by michalvasko** [comment]
Hi,
actually, if you execute those commands with `-v3`m you would know why they are not uninstalled. If you remove all the modules that depend on each other, it actually is possible. However, this is not correct because if you remove these internal modules, you will get random validation errors so I have forbidden this. Anyway, why did you want to uninstall `ietf-netconf`?

Regards,
Michal

**Comment by jjin62** [comment]
Michal,
I use ietf-netconf just to try the uninstall feature. So I turn on -v3 during uninstall:

sysrepoctl -u <module-name> -v3
[INFO]: Applying scheduled changes
[INFO]: No scheduled changes
[INFO]: Module "<module-name>" scheduled for deletion.

the flag change from I to R for <module-name> when I do sysrepoctl -l.
Seems this is a new behavior in new sysrepo, can you have any description about this?

thanks,
Jimmy

**Comment by michalvasko** [comment]
Hi Jimmy,
yes, there is new behavior and it is described in the [documentation](http://www.sysrepo.org/static/doc/html/schema.html).

Regards,
Michal

**Comment by jjin62** [comment]
thanks.
