### ISSUE TITLE
sr_get_items option to get only config data 

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1745]
Hi,

I observed that `sr_get_items` call also searching for oper data.
Is there any option to get items using `sr_get_items` which return only config data, only oper data or both.
This will increase performance for any programs using `sr_get_items` for fetching only config data.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
the `item` getter variants were kept mostly for backwards compatibility and simple use-cases. If you care about the performance, you should always use only *libyang* function variants, which are also much more versatile. Generally, you should need only `sr_get_data()` for getting data, all other functions are just specializations. This function also allows to filter out state data or even more granular data filtering that should cover all the use-cases.

This way there is also some additional motivation to use `sr_get_data` so I do not think these options should be added to any other function.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thank you for explanation. Actually our code is extensively using `sr_get_item(s)` and completely depends on API around `sr_val_t`. Will try to use `sr_get_data` in a wrapper function as per our need.

Thanks &  Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
my point was that you should use only *libyang* trees, not writing a wrapper around them and still use `sr_val_t`. Fine, this change is trivial in the code but it requires an API change so I will implement it (add `sr_get_data` options to `sr_get_items`) before the next release (no idea when that will be, hopefully soon, like several weeks).

Regards,
Michal
