### ISSUE TITLE
sr_delete_item() doesn't delete leaf-list

### ISSUE THREAD

**Issue by iljatab** [sysrepo/sysrepo#1747]
Hello,

It looks like sr_delete_item(sess, "/module:path/to/leaf-list", SR_EDIT_DEFAULT) does not delete the "leaf-list".
In this case "/module:path/to/leaf-list" is an xpath to a leaf-list element which currently holds some data (one element or more).

The sr_delete_item() returns SR_ERR_OK but nothing gets deleted.

This used to work in sysrepo 0.7.x, we have lot of code relying on complete leaf-list deletion.

I don't provide here a separate code sample, however our tests that used to work with sysrepo 0.7.x fail now in such cases.

Could you please check?
Is this how sysrepo is supposed to work now?

Ilja.

**Comment by michalvasko** [comment]
Hi Ilja,
okay, I wanted to add support for this for quite some time but was postponing it because it was not that trivial. But, it should work now, the way you would expect. Note that I had to also make a change in *libyang*, so you will to update it, too. If you don't, *sysrepo* will newly refuse to compile.

Regards,
Michal

**Comment by andrei-pavel** [comment]
Hi Michal,

It can't find libyang for me.
```
CMake Error at CMakeLists.txt:204 (file):
  file failed to open for reading (No such file or directory):

    /home/andrei.pavel@ad.qualitance.com/work/qualitance/terastream/sysrepo/LY_HEADER_PATH-NOTFOUND/libyang/libyang.h


-- Libyang SO version  found
CMake Error at CMakeLists.txt:209 (message):
  Libyang version too old, please update to at least 1.0.119 (SO 1.5.14)
```

```
$ readlink -f /opt/libyang/lib/libyang.so
/opt/libyang/lib/libyang.so.1.5.14
```

I'm building with:
```
      -DLIBYANG_CPP_INCLUDE_DIR=/opt/libyang/include        \
      -DLIBYANG_CPP_LIBRARY=/opt/libyang/lib/libyang-cpp.so \
      -DLIBYANG_INCLUDE_DIR=/opt/libyang/include            \
      -DLIBYANG_LIBRARY=/opt/libyang/lib/libyang.so         \
```

**Comment by michalvasko** [comment]
Hi,
okay, sorry about that, can you please try again now?

Regards,
Michal

**Comment by andrei-pavel** [comment]
:+1: works :muscle: thanks! :pray:

**Comment by iljatab** [comment]
Thanks, looks working!
