### ISSUE TITLE
sr_get_items from change callback fails with internal error. 

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1749]
Hi,

If a leaf got changed and getting the same leaf using `sr_get_items` from callback fails with Internal error.

```
Internal error edit_diff.c:2616.
```
Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
could you please provide some information for reproducing it? Thanks.

Regards,
Michal

**Comment by michalvasko** [comment]
Okay, should be fixed now.

Regards,
Michal
