### ISSUE TITLE
is it possible to make sysrepo support more than 4 datastores?

### ISSUE THREAD

**Issue by tonyguo-spirent** [sysrepo/sysrepo#1752]
I want to make sysrepo support more than 4 datastores besides running startup, candidate, operational. I want to get confirm that it is  easily to extend it.  Am I right? thanks very much

**Comment by michalvasko** [comment]
Hi,
no, these datastores are mostly hard-coded and adding others would require significant changes in the code so I would not call that easy. What datastore do you want to add, anyway?

Regards,
Michal

**Comment by tonyguo-spirent** [comment]
Hi, Michal, thanks for your quick respose. I want to add 4*N datastores for running,startup, candidate and operational.  Because I want to make several netconf server instances( assume it's N) worked in one process with different listening ports, each instance has individual 4 datastores. I want to find a way to make minium change for sysrepo and netopeer server, but it's very diffcult for me. Do you have any idea on it?

**Comment by michalvasko** [comment]
Hi,
*sysrepo* was designed as a centralized datastore on the system, there are not meant to be more instances. But whatever changes you make is up to you and I would say the easiest way may be not to have more datastores but more *sysrepo* installations that would be independent of each other and every *netopeer2-server* would work with its instance. Just my guess, though.

Regards,
Michal

**Comment by tonyguo-spirent** [comment]
Hi, Michal
Thanks so much that you give me a very good piece of advice. but can you tell me how to make sysrepo with more installations?

**Comment by michalvasko** [comment]
Hi,
in general, you must make all the files/shared memory isolated from each other. But you are on your own in this, do not expect me to tell you exactly what you need to do.

Regards,
Michal

**Comment by tonyguo-spirent** [comment]
OK, I know it, thanks very much
