### ISSUE TITLE
Question related to subscribe request for state callback

### ISSUE THREAD

**Issue by Roky7250** [sysrepo/sysrepo#1754]
Hi, I am using **0.7.7** version of sysrepo.
I have two test modules with names : **original_test.yang** and **augment_test.yang**.

Module **augment_test.yang** is augment of **original_test.yang** module.
Inside **augment_test.yang** there is one container with two leafs. Whole container is config false.
In **sr_plugin_init_cb** function I subscribed on augment module to fill up container.
xpath inside **sr_dp_get_items_subscribe** function is correct and subscribe request passed after sysrepo-plugind is booted.
Function **sr_dp_get_items_subscribe** returns SR_ERR_OK.
Both modules are instaled and they are visible with **sysrepoctl -l** command.
Module **augment_test.yang** is not restricted by any conditions or features.

Problem is when I am calling **get** request on netopeer2-cli, callback that fills up container inside augment module is never called.

Can you please give me a suggestion what can I do to find out what the problem is?

Thanks in advance.
Best regards

**Comment by michalvasko** [comment]
Hi,
I am not sure I can help much as the version you are using is really old (even 0.7.8 is ancient) and quite possibly there was a bug that was fixed. You can check the log to see whether any relevant bugfixes were made, maybe you can even search `augment`. Other than that, the only problem I can think of is that all the parents of the container you subscribed to to provide do not exist and hence even that container cannot.

Regards,
Michal
