### ISSUE TITLE
sr_get_change_next() reports unmodified leafs SR_OP_MODIFIED

### ISSUE THREAD

**Issue by iljatab** [sysrepo/sysrepo#1756]
$ sysrepoctl --version
sysrepocfg - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.3.46 (SO v4.2.4)

$ yanglint --version
yanglint SO 1.5.14

$ netopeer2-server -V
netopeer2-server 1.1.1

Hi Michal,

We are migrating from sysrepo 0.7.x and got an issue with sr_get_change_next().

Changes are iterated inside a callback, registered by sr_module_change_subscribe().

Below description is based on openconfig-interfaces.yang model.

We observe changes for one example leaf:
```
/openconfig-interfaces:interfaces/interface/subinterfaces/subinterface/openconfig-if-ip:ipv4/config/dhcp-client [default]
```

1. Create an interface:
================
```
<interfaces xmlns="http://openconfig.net/yang/interfaces">
  <interface>
    <name>dummy7</name>
    <config>
      <name>dummy7</name>
      <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:softwareLoopback</type>
    </config>
    <subinterfaces>
      <subinterface>
        <index>0</index>
        <config>
          <index>0</index>
        </config>
      </subinterface>
    </subinterfaces>
  </interface>
</interfaces>
```
In the callback sr_get_change_next() gives us change:

```
operation: SR_OP_CREATED
old value: (null)
new value: /openconfig-interfaces:interfaces/interface[name='dummy7']/subinterfaces/subinterface[index='0']/openconfig-if-ip:ipv4/config/dhcp-client = false [default]
```
Looks very reasonable and same way as in sysrepo 0.7.x.

2. Add interface details.
```
<interfaces xmlns="http://openconfig.net/yang/interfaces" 
            xmlns:oc-ip="http://openconfig.net/yang/interfaces/ip">
  <interface>
    <name>dummy7</name>
    <config>
      <name>dummy7</name>
      <description>First dummy interface</description>
      <enabled>true</enabled>
    </config>
    <subinterfaces>
      <subinterface>
        <index>0</index>
        <config>
          <index>0</index>
        </config>
        <oc-ip:ipv4>
          <oc-ip:addresses>
            <oc-ip:address>
              <oc-ip:ip>1.2.3.4</ip>
              <oc-ip:config>
                <oc-ip:ip>1.2.3.4</ip>
                <oc-ip:prefix-length>32</prefix-length>
              </config>
            </address>
          </addresses>
        </ipv4>
      </subinterface>
    </subinterfaces>
  </interface>
</interfaces>
```
As expected, in the callback we don't get any changes for .../dhcp-client leaf,

3. Delete  interface details:
```
<interfaces xmlns="http://openconfig.net/yang/interfaces"  
            xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0"
            xmlns:oc-ip="http://openconfig.net/yang/interfaces/ip">
  <interface>
    <name>dummy7</name>
    <config>
      <name>dummy7</name>
      <description xc:operation="delete"></description>
      <enabled>false</enabled>
    </config>
    <subinterfaces>
      <subinterface>
        <index>0</index>
        <config>
          <index>0</index>
        </config>
        <oc-ip:ipv4 xc:operation="delete"></ipv4>
      </subinterface>
    </subinterfaces>
  </interface>
</interfaces>
```

In the callback sr_get_change_next() gives us change:

```
operation: SR_OP_MODIFIED
old value: /openconfig-interfaces:interfaces/interface[name='dummy7']/subinterfaces/subinterface[index='0']/openconfig-if-ip:ipv4/config/dhcp-client = false
new value: /openconfig-interfaces:interfaces/interface[name='dummy7']/subinterfaces/subinterface[index='0']/openconfig-if-ip:ipv4/config/dhcp-client = false [default]
```
This looks line a bug, IMHO.
For some reason sysrepo "forgot" that .../dhcp-client leaf had default value.
So the leaf really is "changing" (false [default] ---> false [default]), meaning _no_ change should be reported
But sysrepo reports the change as (false) ---> false [default]).

This is different from sysrepo 0.7.x.
Also such behavior very significantly increases the number of "changes" that application has to process.
And the application cannot really trust operation == SR_OP_MODIFIED and has to compare old value and new value to figure out of the change was real.

Could you please take a look, would it be possible to fix?

Thanks!

Ilja.

**Comment by iljatab** [comment]
Hi Michal,

Sorry, could you comment on this ticket?
Is this now expected behavior or there will be a fix available?
Just to understand what should I do further.

Ilja.

**Comment by michalvasko** [comment]
Hi Ilja,
there is too much work, that is why I have not responded. I still have not managed to reproduce this with some simple modules but I have committed the fix, so it should work now. I will add such a test case soon, hopefully.

Regards,
Michal

**Comment by iljatab** [comment]
Hi Michal,

Thanks you very much again!

Ilja.

**Comment by michalvasko** [comment]
Even a test for this use-case now included.

Regards,
Michal
