### ISSUE TITLE
sysrepoctl command output shows sysrepocfg

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1760]
Hi,

sysrepoctl shows sysrepocfg in output as below.
Looks like small typo in sysrepoctl source.

```
sysrepoctl --version
sysrepocfg - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.3.48 (SO v4.2.6)
```

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
right, fixed.

Regards,
Michal
