### ISSUE TITLE
State Data failed to trigger callback function

### ISSUE THREAD

**Issue by xxyy0906** [sysrepo/sysrepo#1762]
Description
The yang model :
```yang
module interfaces-list-test1 {
  namespace "interfaces-list-test1";
  prefix interfaces-list-test1;
  import basetype {
        prefix basetype;
  }
        grouping group
        {

                leaf l3_if_count {
                  type basetype:INT32;
                  config false;  
                }
              leaf desc {
                 type basetype:TXT;
               } 
    
        }
        uses group;
 }
```
The state data provider is subscribed by：
```C
rc = sr_dp_get_items_subscribe(session, "/interfaces-list-test1:l3_if_count", test_config_false_state_cb, NULL, SR_SUBSCR_CTX_REUSE, &subscription);
```
netopper-cli：
```
get --filter-xpath /interfaces-list-test1:*
```
phenomenon：
No callback triggered "test_config_false_state_cb"

Versions
sysrepod - sysrepo daemon, version 0.7.7

Thanks!

**Comment by xxyy0906** [comment]
I have now determined that if Container  is used to include leaf, the callback function can be successfully triggered, but why must Container  be used?

**Comment by michalvasko** [comment]
Hi,
I am sorry, but you are using the old *sysrepo* version and support for that one has quite a low priority. Since I am not even managing to do the tasks with a high priority, I am not able to help you. I can only say that it would almost certainly work with the current version 1.x.

Regards,
Michal
