### ISSUE TITLE
Module change subscription callback not working

### ISSUE THREAD

**Issue by avinashtiwaskar** [sysrepo/sysrepo#1764]
Hi, I have created an application in which I tried to subscribe for module change using 
rc = sr_module_change_subscribe(session, modules[i], module_change_cb, NULL,
             0, SR_SUBSCR_DEFAULT, &subscription[i]);
This successfully subscribes and for any change in module data using sysrepocfg or netopeer2-cli, module_change_cb() call back is called twice with two different events SR_EV_VERIFY and SR_EV_APPLY. Everything fine till this point.

Now, I hooked the sysrepo client APIs to connect to sysrepo server from SNMP module, so that if I try to set any data store value from SNMP client, it should update sysrepo datastore. I am following the sequence of operations as : 
sr_connect()
sr_session_start()
sr_set_item_str(), and at last
sr_get_item()

I am able to modify the running config and read it back using get API. Since, I could see the data store is updated with a new value, I expect the subscription call back function should get triggered in this case i.e. module_change_cb(), which was subscribed from another application. However, this is the issue that I am facing. My subscribed function is not called. 

1. What is going wrong here?
2. How, my implementation to set new data in data store is different from sysrepocfg or netopeer2-cli?
3. Do, I need to subscribe with any other subscription option?

Appreciate any response in this regard.
Please let me know if you need any more detail to get me the answers for my queries.

Thanks.

**Comment by sriramkandukuri** [comment]
Hi,

I think you missed to call `sr_apply_changes()` after `sr_set_item_str()`
Please refer to `sr_set_item_example.c` in sysrepo source code.

Thanks & Regards,
Sriram.K

**Comment by avinashtiwaskar** [comment]
Thanks Sriram. I didn't use sr_apply_changes() in my other app also. But I am able to get the control to my callback function when I change data through sysrepocfg or netopeer2-cli. Its only when I change the data from SNMP client, I dont get the callback function called.

But, As you said, I'll try to use sr_apply_changes() in snmp agent code.

Regards,
Avinash

**Comment by sriramkandukuri** [comment]
Hi,

After all changes done in a session one should call `sr_apply_changes` to validate and reflect them in datastore.

Thanks & Regards,
Sriram.K

**Comment by avinashtiwaskar** [comment]
NOTE: Just now I found that sr_apply_changes() is not valid in code version 0.7.6 or older. I am using older version of sysrepo and hence I need to fix the issue that version only - Any other clue?

Thanks,
Avinash

**Comment by sriramkandukuri** [comment]
Hi,

In older version you need to you `sr_commit` Refer to examples of old version.
Same [example ](https://github.com/sysrepo/sysrepo/blob/legacy/examples/sr_set_item_example.c#L69)can be refered in old version too.

Thanks & Regards,
Sriram.K

**Comment by avinashtiwaskar** [comment]
Thank you very much Sriram. Yes, I used sr_commit() in the code section which i hooked into SNMP agent and now it is triggering the subscribed callback function in my app. 

However, I would like to know what is the difference in using and not using sr_commit(). I didnt use this API in my application code, still it works as expected. But for the new code hooked to SNMP agent, why sr_commit() is required. Can you please explain?

Thank you very much,
Avinash

**Comment by michalvasko** [comment]
Hi Avinash,
when you do not call `sr_commit()`, the changes are kept only for your session. Meaning that whatever data set/get operations you do with the session, you will see the changes, but other session will not and neither will they be stored persistently. So they get lost after you terminate your session. By calling commit the data are validated, any subscribers notified about data changes, and finally written into the datastore for other sessions to see. Usually, you first prepare several changes in your session and then "apply" them all with the commit. Because you generally do not want many commits, it is an expensive operation.

Regards,
Michal

**Comment by avinashtiwaskar** [comment]
Thanks you Michal for very nice explaination. I appreciate. I'll implement the same in my application too.

Regards,
Avinash

**Comment by deepthib29** [comment]
Michal, we are using below function
sr_module_change_subscribe(session_running, NTS_NF_ORAN_DU_MODULE, NTS_NF_ORAN_DU_SUBSCRIPTION_STREAMS_SCHEMA_XPATH, subscription_streams_change_cb, NULL, 0, SR_SUBSCR_CTX_REUSE, &session_subscription)

subscription_streams_change_cb function is not getting called.. please let me know why?
what could be the issue?
