### ISSUE TITLE
[new sysrepo] Invalid values on big endian

### ISSUE THREAD

**Issue by gitter-runner** [sysrepo/sysrepo#1769]
Hi,
_sr_val_sr2ly_str()_ function converts _SR_[U]INT8_T_ and _SR_[U]INT16_T_ types improperly on 32 bit big-endian PowerPC system.
Therefore _sr_set_item()_ tries to set invalid values with this types.

I attached a simple example that fails to set uint16 value to "10":

```
# ./sr_set_uint
[ERR]: Invalid value "655360" in "scalar16" element. (path: /test:basics/scalar16)
[ERR]: Failed to create node "scalar16" as a child of "basics". (path: /test:basics/scalar16)
[ERR]: Invalid datastore edit.
```

sysrepo version: 1.3.48
libyang version: 1.0.119

Thanks!

**Comment by michalvasko** [comment]
Hi,
of course it is invalid... Should work properly now.

Regards,
Michal
