### ISSUE TITLE
sysrepocfg export with single leaf not working

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1774]
Hi,

With below steps I am unable to get single leaf from sysrepocfg export

```
sysrepoctl -i a.yang
application_changes_example a &
sysrepocfg --import=a.xml -m a
```
any of below commands not giving any output
```
sysrepocfg --export -x /a:ac1/acl1[acs1='sriram3997']/acs1  -f xml -t 60
sysrepocfg --export -x /a:ac1/a:acl1[a:acs1='sriram3997']/a:acs1  -f xml -t 60
sysrepocfg --export -x /a:ac1/a:acl1[a:acs1='sriram3997']/*  -f xml -t 60
```
[config.tar.gz](https://github.com/sysrepo/sysrepo/files/4096585/config.tar.gz)

Thanks & Regards,
Sriram.K

**Comment by sriramkandukuri** [comment]
Hi Michal,

Yes, but there should be some error shown to user. empty output means no data.
An error when xpath is incorrect is will be very helpful.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
unfortunately, the XPath is correct to the point it is actually checked. If you use this XPath
```
/a:ac1/acl1[acs1=sriram3997]/acs1
```
*libyang* thinks you are looking for an `acl1` instance whose children `acs1` and `sriram3997` values match. It, obviously, finds no such match. And it does not check whether `sriram3997` child is even defined in schema. This is connected to the fact that it should not be checked for XPaths found in YANG modules. Sorry, but I do not think there is any way I can improve this. Perhaps I could output the exact XPath that is used but that could interfere with some scripts printing out additional output.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thank you for the information.

Thanks & Regards,
Sriram.K
