### ISSUE TITLE
[legacy] Feature activation does not work in some cases

### ISSUE THREAD

**Issue by samuel-gauthier** [sysrepo/sysrepo#1776]
Hi,

We are trying to integrate features in our yang model, and when we try to enable a feature, sysrepo refuses the configurations.

I used the following versions:
- libyang  commit 7ff21306787e2d506f3f0a7341c9904a3dfd5740
- sysrepo commit 7960e5d3925fbeb180fffd77562e8f1817949c44

To reproduce:
1) upload the four following files to the tested target and remove the txt suffix (I had to suffix with .txt because github refuses to upload files otherwise)
[feature1.yang](https://github.com/sysrepo/sysrepo/files/4098689/feature1.yang.txt)
[root.conf](https://github.com/sysrepo/sysrepo/files/4098690/root.conf.txt)
[root.yang](https://github.com/sysrepo/sysrepo/files/4098691/root.yang.txt)
[system.yang](https://github.com/sysrepo/sysrepo/files/4098692/system.yang.txt)

2) Run the following commands:
> 
> sysrepoctl -i --yang=root.yang
> sysrepoctl -i --yang=system.yang
> sysrepoctl -i --yang=feature1.yang
> sysrepoctl --feature-enable=feature1 --module=root
> 

3) Apply root.conf configuration, I get the following error:
> $ sysrepocfg -d startup  -i root.conf -f json root
> [ERR] Commit operation failed with 1 error(s).                                                                                                                                                                                                 
> [ERR] Error returned from sr_commit: Validation of the changes failed.                                                                                                                                                                         
> [ERR] (null) : Validation failed: Sysrepo-internal error
> Errors were encountered during importing. Cancelling the operation.
> root@ubuntu1804hwe:~/sysrepo/build# journalctl -a -f
> -- Logs begin at Thu 2019-10-24 16:17:09 CEST. --
> Jan 22 18:06:23 ubuntu1804hwe sysrepod[3774]: [WRN] Persist file for module ietf-netconf-acm does not exist.
> Jan 22 18:06:23 ubuntu1804hwe sysrepod[3774]: [WRN] File '/etc/sysrepo/data/system.startup' cannot be found.
> Jan 22 18:06:23 ubuntu1804hwe sysrepod[3774]: [WRN] Data file '/etc/sysrepo/data/system.startup' not found, considering as authorized.
> Jan 22 18:06:23 ubuntu1804hwe sysrepod[3774]: [ERR] libyang error: Node already exists.
> Jan 22 18:06:23 ubuntu1804hwe sysrepod[3774]: [WRN] Error by adding new notification entry /sysrepo-notification-store:notifications/notification[xpath='/ietf-netconf-notifications:netconf-capability-change'][generated-time='2020-01-22T18$
> 06:23+01:00'][logged-time='3352455721']: Node already exists..
> Jan 22 18:06:30 ubuntu1804hwe sysrepod[3774]: [ERR] libyang error: Target context does not contain schema node for the data node being duplicated (feature1:test).
> Jan 22 18:06:30 ubuntu1804hwe sysrepod[3774]: [ERR] Failed to duplicate root data tree into another context
> Jan 22 18:06:30 ubuntu1804hwe sysrepod[3774]: [ERR] Failed to append data tree root
> Jan 22 18:06:30 ubuntu1804hwe sysrepod[3774]: [ERR] Loading dependant modules failed for feature1
> Jan 22 18:06:30 ubuntu1804hwe sysrepod[3774]: [ERR] Validation after merging failed
> 

Notes:

- Restarting sysrepo allows to commit the configuration without error, but in an environment with daemons subscribed to sysrepo, restarting sysrepo is not working well (netopeer for instance will not like it and has to be restarted as well).

- If I change the type of the test leaf in feature1.yang test rpc from a leafref to a string, the configuration commit works, but I have no idea why...

I know that the legacy sysrepo is not a priority right now for you guys, but I still hope someone can help. We do plan to upgrade in the coming months, but for now, I am stuck.... I tried to debug myself without luck for now.

Thanks in advance,
Samuel

**Comment by michalvasko** [comment]
Hi Samuel,
since you asked so nicely I did take a look but the fix took me more time than I thought. Anyway, it should work with in the latest `legacy` branch.

Regards,
Michal

**Comment by samuel-gauthier** [comment]
Thanks a lot for this Michal, I really appreciate it. It works perfectly.

Regards,
Samuel
