### ISSUE TITLE
sr_get_items fails when changing data from one case to other

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1777]
HI,

Apply given patch in tarball to application_changes_example for enabling printing data in `SR_EV_CHANGE`
Please find below steps
```
sysrepoctl -i a.yang
application_changes_example a &
sysrepocfg --import=a1.xml -m a
sysrepocfg --import=a2.xml -m a
```
Which causes error while getting data from callback.

```
[ERR]: Data for more than one case branch of "acl1ch1" choice present. (path: /a:ac1/acl1[acs1='sriram1']/acl1ch1cs1lf1)
[ERR]: Insert request refers node (/a:ac1/acl1[acs1='sriram1']/acl1ch1cs1lf1) that is going to be auto-deleted. (path: /a:ac1/acl1[acs1='sriram1']/acl1ch1cs1lf1)
```
[config.tar.gz](https://github.com/sysrepo/sysrepo/files/4102105/config.tar.gz)

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
right, this test case was missing for `sr_replace_config()`, added and it should work now.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thank you for the fix.

Thanks & Regards,
Sriram.K
