### ISSUE TITLE
sysrepoctl inoperable after feature enabling

### ISSUE THREAD

**Issue by frimpler** [sysrepo/sysrepo#1778]
Hi Michal,
please consider the test-module. It has dependent features. If you install it and try to enable a feature which needs its parent feature enabled, sysrepoctl becomes inoperable.

```
module dd {

  namespace "urn:fri:params:xml:ns:yang:dd";
  prefix dd;

  description
    "This is a module used for feature enabling test.";

  feature dd0 {
    description
      "Feature dd0.";
  }

  feature dd1 {
    if-feature dd0;
    description
      "Feature dd1.";
  }

  feature dd2 {
    if-feature dd1;
    description
      "Feature dd2.";
  }

  container container_dd0 {
    description
      "Container dd0";

    leaf name_dd0 {
      if-feature dd0;
      type string;
    }

    leaf name_dd1 {
      if-feature dd1;
      type string;
    }

    leaf name_dd2 {
      if-feature dd2;
      type string;
    }
  }
}
```

```
/git/sysrepo # sysrepoctl -v 4 -i ../yang/dd.yang -s ../yang/
[INF]: Applying scheduled changes.
[INF]: No scheduled changes.
[INF]: Module "dd" scheduled for installation.
/git/sysrepo # sysrepoctl -v 4 --enable-feature dd0 -c dd
[INF]: Applying scheduled changes.
[INF]: No scheduled changes.
[INF]: Module "dd" feature "dd0" enabling scheduled.
/git/sysrepo # sysrepoctl -l
Sysrepo repository: /bld/sysrepo/repository

Module Name                | Revision   | Flags | Owner            | Permissions | Submodules | Features
--------------------------------------------------------------------------------------------------------
dd                         |            | I     | frimpler:nogroup | 600         |            | dd0
ietf-netconf               | 2011-06-01 | I     | frimpler:nogroup | 600         |            |
ietf-netconf-notifications | 2012-02-06 | I     | frimpler:nogroup | 600         |            |
ietf-netconf-with-defaults | 2011-06-01 | I     | frimpler:nogroup | 600         |            |
ietf-origin                | 2018-02-14 | I     | frimpler:nogroup | 600         |            |
ietf-yang-library          | 2019-01-04 | I     | frimpler:nogroup | 600         |            |
yang                       | 2017-02-20 | I     | frimpler:nogroup | 600         |            |

Flags meaning: I - Installed/i - Imported; R - Replay support; N - New/X - Removed/U - Updated; F - Feature changes

/git/sysrepo # sysrepoctl -v 4 --enable-feature dd2 -c dd
[INF]: Applying scheduled changes.
[INF]: No scheduled changes.
[INF]: Module "dd" feature "dd2" enabling scheduled.
/git/sysrepo # sysrepoctl -l
[ERR]: Feature "dd2" is disabled by its 1. if-feature condition.
sysrepoctl error: Failed to connect (libyang error)
/git/sysrepo # sysrepoctl -C
0
```
Regards,
Frank

**Comment by michalvasko** [comment]
Hi Frank,
right, I have forgotten to test `feature` with `if-feature`. Test case added and it should work now.

Regards,
Michal

**Comment by frimpler** [comment]
Hi again,
it doesn't fail on the "Failed to connect" issue, anymore. So I'm almost lucky with it :-). 
But now, imagine, you've realized, that it isn't possible to set dd2 feature because it depends on dd1 and try to enable dd1. This is not possible, the workflow and what happens is really strange - I'd say. Please have a look at the attached file. It starts with an already enabled dd0, as you can see. 
 
[issue_1778.txt](https://github.com/sysrepo/sysrepo/files/4103883/issue_1778.txt)

**Comment by michalvasko** [comment]
Hi,
please try it again. This feature stuff is much more complicated than I thought, I have spent almost the whole day on it. But, I have added some tests that should cover enabling and disabling of features with some if-features. I was not sure how to implement disabling features because *libyang* disables dependent features implicitly but I thought that could be a bit unexpected, so in *sysrepo* this is checked and not allowed.

Regards,
Michal

**Comment by frimpler** [comment]
Hi Michal,
I did a quick check using sysrepoctl -l and I'm in general ok with it, even if sysrepoctl does not always show what really happend with the features. The "Feature change flag" is is only a hint, that something might be hidden. Maybe someday this should be improved, but for the moment I guess the issue as addressed is solved. 
Thanks,
Frank

**Comment by michalvasko** [comment]
Hi,
yeah, I attempted to improve that some time ago only to be left with a huge unintelligible table as the output of `sysrepoctl -l`. That is why I decided to simply use a flag. You should know what changes are you doing.

Regards,
Michal
