### ISSUE TITLE
QUERY  sr_get_data on startup

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1779]
Hi,

I am subscribing for several modules. Can i get data using `sr_get_data` for once till all the modules get enabled, or should i get data for every ENABLE event?

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
more explanation will be given in the other issue #1781, but you can call `sr_get_data()` whenever you want and you will get the current data.

Regards,
Michal
