### ISSUE TITLE
sr_get_data fails with invalid argument error

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1780]
Hi,

When calling `sr_get_data` from subscriber process, I am getting above mentioned error as I am calling with NO_STATE option.

If it is expected behavior, can I expect no operational data in result data tree if no option given to `sr_get_data` API.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
my guess is that you are calling `sr_get_data` on a session that has `SR_DS_RUNNING` datastore set. For any other datastore than `SR_DS_OPERATIONAL` no flags make sense.

In your case, there will never be any state data in `running` datastore, so you should no use the flag. I think you still do not fully understand the new `running` and `operational` datastore purposes and you should [read](https://tools.ietf.org/html/rfc8342) about them.

Regards,
Michal
