### ISSUE TITLE
sysrepo-plugind boot is too slow

### ISSUE THREAD

**Issue by maksimvuleta** [sysrepo/sysrepo#1783]
We have installed sysrepo and netopeer2-server with 5-6 our sysrepo-plugins implemented and installed.
Our system is booting the sysrepod, sysrepod-plugind and netopeer2-server automatically.
After these processes are boot we are able to read and edit data with netopeer2-cli and it seems to work fine.

The problem is that somehow the netopee2-server is up and we connect to it from netopeer2-cli but sysrepo-plugind is still not finished with the initialization. If I do the 'get' from netopeer2-cli I will get the uncomplete data. It is necessary to wait to get complete data.

So, the question is can netopeer2-server wait until sysrepo-plugind boot is completely finished? And how to do that?

**Comment by michalvasko** [comment]
Hi,
you have to use some features of the daemon that starts *netopeer2-server* and *sysrepo-plugind*, for one to wait for the other in some way.

Regards,
Michal

**Comment by maksimvuleta** [comment]
Where I can found the features and how to enable them?

**Comment by michalvasko** [comment]
> Our system is booting the sysrepod, sysrepod-plugind and netopeer2-server automatically.

I do not know, depends on what is used for this purpose.

Regards,
Michal

**Comment by maksimvuleta** [comment]
OK.
I thought there is a feature in sysrepo-plugind or netopeer2-server which can be enabled and then they will be waiting for each other to start. 

Thanks. 
Regards,
Maksim.
