### ISSUE TITLE
Unknown model subscription

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1784]
Hi,

When I am subscribing to unknown model, in old sysrepo returned error used to be `SR_ERR_UNKNOWN_MODEL` where as in new sysrepo its returning `SR_ERR_NOT_FOUND`.

Is it expected ?

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
yes, it is intentional because it seemed to be the other error is redundant and communicates the same information in this case. I wanted to remove these unused errors but it seems I have forgotten. Will fix it on the next release.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thank you for the confirmation

Thanks & Regards,
Sriram.K
