### ISSUE TITLE
sr_get_data fails with node to insert not found error

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1787]
Hi,

After updating to new APIs for `lyd_find_*` sysrepo API `sr_get_data` failing with error `Node <node name> instance to insert next to not found`

Looks like the issue is while finding a node with leafref in other modules.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
you have provided very little information, could you please add some? At least something like calling `sr_get_data()` on `SR_EV_CHANGE` event when there is a leafref modified pointing to some other module, best with even more specific details.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

I will mail you regarding details.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
okay, it should be properly fixed, test included.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thank you its working

Thanks & Regards,
Sriram.K
