### ISSUE TITLE
sysrepo erorrs in syslog after reboot

### ISSUE THREAD

**Issue by maksimvuleta** [sysrepo/sysrepo#1788]
After reboot my system I got a lot of errors like these:
_Jan 16 15:27:15 de-eval-board sysrepod[**8591**]: [WRN] Error by processing of the message: The item expected to exist is missing.
Jan 16 15:27:15 de-eval-board sysrepod[8591]: [ERR] Unable to modify persist data tree.
Jan 16 15:27:15 de-eval-board sysrepod[8591]: [ERR] Unable to remove subscriptions for destination '/var/run/sysrepo-subscriptions/ietf-ptp/**7670**.cSFfJa.sock' from 'ietf-ptp'._

This sequence of messages is repeating a lot of time for all modules.
As I understand, the bold value of **7670** represents the old PID of sysrepod, so the new sysrepod (PID **8591**) tries to remove the old subscription which is already removed when we kill sysrepod while a reboot. 

The same is when I manually kill the sysrepod process and start it again manually.

**Comment by michalvasko** [comment]
Hi,
you can safely ignore these errors as far as I know. If you want to get rid of them, switch to using the current *sysrepo* 1.3.x.

Regards,
Michal
