### ISSUE TITLE
Errors after sysrepo reboot

### ISSUE THREAD

**Issue by Roky7250** [sysrepo/sysrepo#1791]
Hi, I have system that is booting sysrepo-plugind, sysrepod and netoopeer2-server automatically.

After rebooting system I am getting this errors related to sysrepod:

sysrepod[1301]: [ERR] libyang error: Invalid context for LYB data parsing, missing module "sysrepo-persistent-data@2000-03-30".
sysrepod[1301]: [ERR] Parsing persist data from file '/etc/sysrepo/data/ietf-yang-library.persist' failed: Invalid context for LYB data parsing, missing module "sysrepo-persistent-data@2000-03-30".
sysrepod[1301]: [ERR] Unable to load persist data tree for module 'ietf-yang-library'.

Error related to netopeer2-server:

netopeer2-server[1363]: Subscribing for providing "Sysrepo-internal error" state data failed (@^RԶT^RԶh^RԶx^RԶ�^RԶ�^RԶ�^RԶ�^RԶ�^RԶ�^RԶ^P^SԶ4^SԶX^SԶ|^SԶ�^SԶ�^SԶ�^SԶ�^SԶ^D^TԶ,^TԶ@^TԶd^TԶ).
netopeer2-server[1363]: Server init failed.

After this server, sysrepod and sysrepo-plugind init fails.

What makes this happen?

Thanks in advance,
Best regards

**Comment by michalvasko** [comment]
Hi,
that is quite strange, I have no idea why you do not have the module loaded in the context. Did you perhaps modify `sysrepod` or its persistent files manually yourself? Something is really wrong but all I can suggest is to clear the whole repository (best with `make uninstall_with_repo`) and then install *sysrepo* again.

Regards,
Michal

**Comment by Roky7250** [comment]
This happened after reboot a couple of times.
Unfortunately, I can't tell what sequence of steps have led to this situation.

As I understood inside the module **.persist** file are located features that are enabled for that module and subscriptions related to config and state (callbacks) data that we subscribe inside **sr_plugin_init_cb** function.

Can you tell me why this **.persist** file is important?
What can happen if I clean that file after I stop sysrepod and sysrepo-plugind and start them again?

Thanks in advance,
Best regards

**Comment by michalvasko** [comment]
Hi,
well, you will lose all the persist information about that module which includes enabled features but also current subscriptions. But I noticed that the revision of that module is an incorrect one so there is probably something really wrong. Hard to guess what, though.

Regards,
Michal

**Comment by Roky7250** [comment]
Hi, so basically I can clean that file after I stop sysrepod and sysrepo-plugind, enable features that I am using inside module again using sysrepoctl and run the sysrepod and sysrepo-plugind again.

It should not affect the work of  sysrepod and sysrepo-plugind?

I am asking this because I had few errors inside daemon.log file which I managed to get rid of stopping sysrepod and sysrepo-plugind, cleaning persist file of desired module, enabling required features and run sysrepod and sysrepo-plugind again. 

It did not affect the work of sysrepod and sysrepo-plugind.
Everything worked fine after that and there was no errors.

For example I get rid of error for ietf-interfcaes module:
[ERR] Unable to remove subscriptions for destination '/var/run/sysrepo-subscriptions/ietf-interfaces/2168.cSFfJa.sock' from 'ietf-interfaces'.

Thanks in advance,
Best regards

**Comment by michalvasko** [comment]
Hi,
> Hi, so basically I can clean that file after I stop sysrepod and sysrepo-plugind, enable features that I am using inside module again using sysrepoctl and run the sysrepod and sysrepo-plugind again.

I believe so. If you remove the file completely, there may be an error displayed but I think you discovered this and hence you wrote clean, not remove.

Regards,
Michal
