### ISSUE TITLE
sysrepo get_schema errors when doing install-uninstall-install

### ISSUE THREAD

**Issue by syyyr** [sysrepo/sysrepo#1792]
Hello,

I found an issue with sysrepo (and netopeer) when trying to install, uninstall and again install a schema.
This is my schema (it imports another schema):
```yang
module example-schema {
    prefix aha;
    namespace "http://example.com";

    import other-module {
        prefix other;
    }

    augment "/other:parking-lot" {
        list cars {
            key 'id';
            leaf id {
                type int32;
            }
        }
    }
}
```
```yang
module other-module {
    prefix aha;
    namespace "http://other.com";

    container parking-lot;

}
```
Say I have both of these in the current directory. When I run sysrepo and then do:
```
$ sysrepoctl --install --yang=example-schema.yang 
$ sysrepoctl --uninstall --module=example-schema
$ sysrepoctl --install --yang=example-schema.yang 
```
everything goes well. However, when I run sysrepo and then run netopeer server I get some errors about sysrepo not being able to give the `other-module` schema to netopeer, even though `sysrepoctl -l` shows that they are in fact there (I can see the files in the repository directory too). When I restart both daemons, everything works correctly. I created a simple program, that tries to get the imported module, but it just crashes with an exception:
```cpp
#include <sysrepo-cpp/Session.hpp>
int main(int argc, char* argv[])
{
    auto conn = std::make_shared<sysrepo::Connection>("example");
    auto sess = std::make_shared<sysrepo::Session>(conn);
    sess->get_schema("other-module", nullptr, nullptr, SR_SCHEMA_YANG);
    return 0;
}
```
output:
```
$ ./a.out 
terminate called after throwing an instance of 'sysrepo::sysrepo_exception'
  what():  Requested schema model is not known
Aborted (core dumped)
```
When both daemons are restarted, it doesn't crash anymore. So, the bug is only present when doing the install-uninstall-install thing while the daemons are running.
sysrepo version: sysrepod - sysrepo daemon, version 0.7.9
netopeer version: netopeer2-server 0.7.17

Here are logs with the errors from both sysrepo and netopeer:
[sysrepo.log](https://github.com/sysrepo/sysrepo/files/4127712/sysrepo.log)
[netopeer.log](https://github.com/sysrepo/sysrepo/files/4127714/netopeer.log)

**Comment by michalvasko** [comment]
Hi,
I have briefly tried it and it worked fine so you will have to specify your exact use-case, what you wrote is quite confusing.

This is what I tried, run `sysrepod`, install-uninstall-install the module, run `netopeer2-server`, it started just fine. You need to be exact as to when you have daemons running/restart them and what steps you do in between.

Regards,
Michal

**Comment by syyyr** [comment]
Sorry, I made a mistake. The steps to reproduce are:
1. run `sysrepod`
2. run `netopeer2-server`
3. do the install-uninstall-install step
4. both `sysrepod` and `netopeer2-server` give errors

**Comment by michalvasko** [comment]
Hi,
okay, I reproduced it but it seems this is intentional. From your log
```
[INF] (dm_get_schema:3368) Get schema 'other-module', revision: '(null)', submodule: '(null)', submodule revision: '(null)'
[DBG] (dm_get_module_internal:3098) Module other-module has been uninstalled
[ERR] (dm_get_schema:3419) Get module failed for other-module
```
it seems this simply is not supported.

Regards,
Michal

**Comment by syyyr** [comment]
Sorry, I don't understand. What is not supported? Installing, uninstalling and then installing a module? I tried the same thing with another module that doesn't import anything and it seems to work. Is it not supported only if the installed module imports something?

**Comment by michalvasko** [comment]
Hi,
sorry, but I am not sure, I did not write that code. If it works in some other cases, then only some special ones are not supported. You can also try installing (and uninstalling) `other-module` before `example-module`, separately.

Regards,
Michal

**Comment by syyyr** [comment]
I solved the issue by installing (and uninstalling) the schema only once. Thanks for the answer.
