### ISSUE TITLE
[Query]: How to adjust callback event processing timeout?

### ISSUE THREAD

**Issue by mabukar** [sysrepo/sysrepo#1794]
Hi,

My Sysrepo application callback function takes sometime (up to 15 sec) to process the events during SR_EV_CHANGE phase because it needs to communicate with other entities running on different pods.

So how can I adjust/increase the default timeout, which seems to be quite short?

This is the error print from Netconf client:
**netconf rpc [error] 'Callback event processing timed out.'**

Thanks!

**Comment by michalvasko** [comment]
Hi,
what exactly is your setup? You have *netopeer2* with *sysrepo* and connecting to it with a NETCONF client? In that case this error should be seen in *netopeer2-server* output.

Regards,
Michal

**Comment by mabukar** [comment]
@michalvasko, Yes that is exactly my setup and the below error is visible in netopeer-server's logs.

**_2020-01-30 11:50:25,168 DEBG 'netopeer2-server' stdout output:
[ERR]: NP: Failed to send an RPC (User callback failed).

2020-01-30 11:50:25,169 DEBG 'netopeer2-server' stdout output:
[ERR]: LN: Session 1: reading from the SSH channel failed (Socket error: disconnected)_.**

Any idea/suggestion how to solve this issue?

**Comment by michalvasko** [comment]
Hi,
right, unfortunately, the `<edit-config>` RPC, which is technically time-outing, does not have a customizable timeout so I do not know about any generic solution. However, you can locally change *netopeer2-server* and [set some higher timeout](https://github.com/CESNET/Netopeer2/blob/devel-server/server/netconf.c#L247) (in seconds) for `sr_apply_changes()`. The default is [5000 ms](https://github.com/sysrepo/sysrepo/blob/devel/src/common.h.in#L158).

Regards,
Michal

**Comment by mabukar** [comment]
@michalvasko, Sure, I can modified the code locally and increase the timeout to 20 seconds for now.

But it would be really good to be able to adjust timeout value during compilation via CMake.

**Comment by michalvasko** [comment]
Hi,
okay, should now be possible (https://github.com/CESNET/Netopeer2/commit/48169aa9ac52036316df8b142c5bb9da813eb919).

Regards,
Michal

**Comment by mabukar** [comment]
@michalvasko, thanks. I will try that tomorrow and keep you updated!

**Comment by mabukar** [comment]
Hi Michal,

Tried and working. Thanks!

**Comment by michalvasko** [comment]
Hi,
just to note that the parameter name has changed to `DATA_CHANGE_TIMEOUT` and is now applied for any data changes. That also includes `<commit>` or other RPCs.

Regards,
Michal
