### ISSUE TITLE
sysrepo-plugind boot fails

### ISSUE THREAD

**Issue by Roky7250** [sysrepo/sysrepo#1798]
Hi, I am using sysrepo from devel branch.

I installed my module to sysrepo and run sysrepo-plugind.
I am getting this error when it boots:

```
[INF]: Scheduled changes not applied because of other existing connections.
[WRN]: Cleaning up after a non-existent sysrepo client with PID 14629.
[DBG]: #SHM before defrag
sysrepo-plugind: /home/devel/smb_share/sysrepo/src/shm_main.c:384: sr_shmmain_ext_print: Assertion `*((size_t *)ext_shm_addr) == wasted' failed.
Aborted
```

Can you tell me what is the problem?

Note: libyang and libnetconf2 are from devel branch. Netopeer2 is from devel-server branch.

Thanks in advance 
Best regards

**Comment by michalvasko** [comment]
Hi,
what version are you using exactly?

Regards,
Michal

**Comment by Roky7250** [comment]
Hi, I forgot to paste it.
sysrepo version is: 

`sysrepo-plugind - sysrepo plugin daemon, compiled with libsysrepo v1.4.0 (SO v5.0.0)`

netopeer2 version is:

`netopeer2-server 1.1.5`

Thanks in advance
Best regards

**Comment by michalvasko** [comment]
Hi,
okay, then this is potentially a serious problem. Do you perhaps have a certain way of reproducing this, starting with a clean SHM (`make shm_clean`)?

Regards,
Michal

**Comment by Roky7250** [comment]
Hi, I noticed that this happens if I subscribe multiple times to **sr_oper_get_items_subscribe**.
In my case it is five.

After I did **sudo make shm_clean** and run sysrepo-plugind output was:

```
[WRN]: Removing event pipe "sr_evpipe112" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe37" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe38" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe32" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe160" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe177" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe60" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe48" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe114" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe162" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe163" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe62" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe51" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe201" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe61" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe203" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe42" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe173" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe52" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe56" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe57" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe161" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe53" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe55" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe208" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe199" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe111" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe116" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe159" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe105" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe210" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe47" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe43" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe115" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe198" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe178" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe167" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe45" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe122" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe118" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe157" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe119" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe200" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe66" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe35" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe65" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe50" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe59" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe158" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe168" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe176" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe107" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe120" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe33" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe207" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe171" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe110" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe109" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe31" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe121" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe170" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe165" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe106" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe46" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe113" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe108" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe164" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe202" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe117" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe41" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe172" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe58" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe211" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe36" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe44" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe209" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe197" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe39" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe49" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe205" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe34" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe212" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe64" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe155" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe156" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe166" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe175" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe204" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe206" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe169" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe54" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe63" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe174" after a crashed subscription.
[WRN]: Removing event pipe "sr_evpipe40" after a crashed subscription.
[INF]: Applying scheduled changes.
[INF]: No scheduled changes.
[INF]: Datastore copied from <startup> to <running>.
[INF]: Session 1 (user "root") created.
[DBG]: plugin: DEBUG: sr_plugin_init_cb(): is called.
sysrepo-plugind: /home/devel/smb_share/sysrepo/src/sysrepo.c:4617: sr_oper_get_items_subscribe: Assertion `(elem->flags & LYS_CONFIG_MASK) == LYS_CONFIG_W' failed.
Aborted
```

After this I commented out some of subscribes for state data.
I left three subscriptions.
sysrepo-plugind  boot up well.

Thanks in advance
Best regards

**Comment by michalvasko** [comment]
Hi,
if you could maybe provide the module you are subscribing to and the `path` of the subscription(s) that causes this assert, please?

Regards,
Michal

**Comment by Roky7250** [comment]
Hi, I did a further investigation and noticed that this happens when I subscribe for state data for list that is config true but has some leafs inside that are config false.
To be precise I am subscribing to ieee802-dot1ab-lldp module:
```
rc = sr_oper_get_items_subscribe(session, ieee802-dot1ab-lldp, "/ieee802-dot1ab-lldp:lldp/port",
		lldp_list_port_data_cb, NULL, SR_SUBSCR_DEFAULT , &subscription);
if (rc != SR_ERR_OK) {
	break;
}
```
Here is module: [ieee802-dot1ab-lldp](https://github.com/YangModels/yang/blob/master/standard/ieee/draft/802.1/ABcu/ieee802-dot1ab-lldp.yang) .

On older version of sysrepo I could subscribe to list that is config true using **sr_dp_get_items_subscribe**. Callback would be triggered for every leaf and container inside that list that is config false.
Could this be issue in new version, that is that I can not subscribe to list that is config true using **sr_oper_get_items_subscribe**?

**Comment by michalvasko** [comment]
Hi,
okay, it should be fixed now, it was an unrelated problem to what you have mentioned. However, even though subscribing to `config true` nodes is supported, now you actually subscribe to providing even the configuration nodes. More information in the documentation (which you have to generate yourself, tomorrow it should be again available online).

Regards,
Michal

**Comment by Roky7250** [comment]
Hi, one question related to state data.
I am currently subscribed for:

```
rc = sr_oper_get_items_subscribe(session, "ieee802-dot1ab-lldp", "/ieee802-dot1ab-lldp:lldp",
		lldp_state_data_cb, NULL, SR_SUBSCR_DEFAULT , &subscription);
if (rc != SR_ERR_OK) {
	break;
```
Now I want to fiil up container **local-system-data** inside **lldp_state_data_cb**.

My question is, how do I create cintainer **local-system-data** so after creating him I can
use:

lyd_new_path(*parent, NULL, "/ieee802-dot1ab-lldp:lldp/local-system-data/port-id", tmp_value, 0, 0)

to create other leafs?

Note: Commit [b4bd684](https://github.com/sysrepo/sysrepo/commit/b4bd684a1725206b02c4df3966dda640fbfdb966) for now fixed my error from above.

Best regards

**Comment by michalvasko** [comment]
Hi,
`lyd_new_path()` create whatever nodes do not exist on the path to the final node that is supposed to be created, so you do not have to worry about that. But to answer you, you can simply create the container with
```C
lyd_new_path(*parent, NULL, "/ieee802-dot1ab-lldp:lldp/local-system-data", NULL, 0, 0);
```
However, you have subscribed to a top-level node! You must be careful because in that case the parent passed to callback is NULL (`*parent == NULL`) since there is no parent. So, your first call must assign this parent. Also, in that case (since you will not be providing the parent) you must provide the second parameter, which is *libyang* context, but you can easily get it from the connection. So, the final call should be
```C
*parent = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(session)), "/ieee802-dot1ab-lldp:lldp/local-system-data/port-id", tmp_value, 0, 0);
```
The rest of data should then just append to the existing data by the call you mentioned.

Regards,
Michal

**Comment by Roky7250** [comment]
Hi, one more question.

This is my startup:

```
<lldp xmlns="urn:ieee:std:802.1AB:yang:ieee802-dot1ab-lldp">
  <tx-credit-max>5</tx-credit-max>
  <tx-fast-init>4</tx-fast-init>
  <notification-interval>30</notification-interval>
  <port>
    <name>ens33</name>
    <dest-mac-address>00-0c-29-4d-62-70</dest-mac-address>
  </port>
  <port>
    <name>eth0</name>
    <dest-mac-address>2a-13-1a-f2-c6-1c</dest-mac-address>
  </port>
</lldp>
```

I am subscribed for:

```
rc = sr_oper_get_items_subscribe(session, "ieee802-dot1ab-lldp", "/ieee802-dot1ab-lldp:lldp/port",lldp_state_data_cb, NULL, SR_SUBSCR_DEFAULT , &subscription);
if (rc != SR_ERR_OK) {
	break;
}
```

Now in this case my parent inside callback will be different from NULL and it will be lldp container.
Now inside that callback I want to add leafs **port-id** and **port-desc**. Those leafs are state data inside list port. Obviously the list with key values already exists inside running datastore. I just need to 
expand entries (eht0 and ens33) inside that list with port-id and port-desc.

How can I do it?

I tried some combinations using **lyd_new_path** but I failed to do it.

Sorry if this is solution for this is visible using your comment from above, but I can not see it.

Thanks in advance
Best regards

**Comment by Roky7250** [comment]
Thank you very much.

Best regards

**Comment by michalvasko** [comment]
Hi,
well, this is all *libyang* API stuff that you should be familiar with when working with *sysrepo* 1.x and that you __must__ be familiar with if having operational subscriptions. But I will help you this time.

Your callback will be called for every `port` instance with the path you subscribed to. You will likely want to know what the instance is in every callback call. To learn the string value of the key `name` use
```C
((struct lyd_node_leaf_list *)((*parent)->child))->value_str
```
Now you can simply append the leaves with their specific values (no return value checking, which you should perform)
```C
lyd_new_path(*parent, NULL, "port-id", "<port-id-val>", 0, 0);
lyd_new_path(*parent, NULL, "port-desc", "<port-desc-val>", 0, 0);
```
Note that the path used in `lyd_new_path()` was a relative one in this case. If you start the path without `/`, it means the context node is the anchor and you are creating its descendants.

You can achieve the same thing using the other *libyang* API, which is much simpler but sufficient for simple child creation
```C
lyd_new_leaf(*parent, NULL, "port-id", "<port-id-val>");
lyd_new_leaf(*parent, NULL, "port-desc", "<port-desc-val>");
```
In this case `port-id` is not a path but simply the descendant name.

Regards,
Michal

**Comment by michalvasko** [comment]
Seems I have been a bit slow and you figured it out, good for you.
