### ISSUE TITLE
Client application validation callback.

### ISSUE THREAD

**Issue by serega911** [sysrepo/sysrepo#1800]
Hi all.

In the file [application_changes_example.c](https://github.com/sysrepo/sysrepo/blob/master/examples/application_changes_example.c), module_change_cb may receive only 3 events: SR_EV_CHANGE, SR_EV_DONE or SR_EV_ABORT.

I expected it to receive something like SR_EV_VALIDATE before SR_EV_CHANGE is received.
But there is no such option there...

Also I tried to use sr_set_diff_check_callback but it is not called:
```
static int validateCB(sr_session_ctx_t *session, const struct lyd_node *diff)
{
    std::cout << "Validation called" << std::endl;
    return SR_ERR_OPERATION_FAILED;
}

int main()
{
....
        sr_set_diff_check_callback(m_connection, validateCB);
...
}
```

**Is there any way to receive "VALIDATION" event?**

**Comment by michalvasko** [comment]
Hi,
do not be confused by the new event names, they were simply [renamed](https://github.com/sysrepo/sysrepo/blob/master/CHANGES#L7) to be more generic. This is exactly the reason for the change, you have learned from the old *sysrepo* that you should first validate the change and then apply it. Yes, it is often true but there are many cases when you want to do something different for the events.

Regards,
Michal

**Comment by serega911** [comment]
Thanks, got it!
