### ISSUE TITLE
Confusing error in sr_set_item_str when ietf-origin.yang is not installed

### ISSUE THREAD

**Issue by pieterlexis** [sysrepo/sysrepo#1801]
Hi!

When calling `sr_set_item_str` when the ietf-origin YANG model is not installed. Sysrepo sets the following error in the session:

```
Attribute prefix does not match any implemented schema in the context.
```

While going through the libyang source code, I found this error exists twice in `lyd_insert_attr`. But it did not help me to understand what was going on. Comparing the output of `sysrepoctl -l` between a 'working' and 'broken' machine revealed the ietf-origin module was not installed. Installing this made the error go away.

Please consider setting an error in the session like "is the ietf-origin module installed?").

Thanks!

Using sysrepo 1.3.21 and libyang 1.0.109

**Comment by michalvasko** [comment]
Hi,
that is understandable but please update *sysrepo* (to the latest release or the current `devel`), it should no longer be allowed to uninstall internal modules precisely because of errors like these.

Regards,
Michal

**Comment by pieterlexis** [comment]
If you say this issue is fixed by the next version, this is good enough for me :). I'll try to update my devenv later and report back

**Comment by pieterlexis** [comment]
I indeed see these modules 'installed' in `sysrepoctl -l` on the devel branch.
