### ISSUE TITLE
Sending error to netopeer cli

### ISSUE THREAD

**Issue by Roky7250** [sysrepo/sysrepo#1803]
Hi, I am using sysrepo from master branch, 1.4.2.
Also I am using latest libyang, libnetconf2 and Netopeer2 from master branches.

I subscribed for config data changes using:

```
rc = sr_module_change_subscribe(session, "ieee802-dot1ab-lldp", "/ieee802-dot1ab-lldp:lldp/port",
		lldp_test_cb, NULL, 0, SR_SUBSCR_DEFAULT, &subscription);
if (rc != SR_ERR_OK) {
	break;
}
```
Inside **lldp_test_cb** I am using **sr_set_error** function.
Inside that callback I am using **sr_get_change_next** function to iterate trough changes and for example if SR_OP_DELETED operation happened I want to send message to client.
I am doing it like this:
```
sr_set_error(session, xpath, "Delete operation not supported!");
return SR_ERR_OPERATION_FAILED;
```
On client side (like on old sysrepo version) I should get something like this:

```
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        path:     /ieee802-dot1ab-lldp:lldp/port
        message:  Delete operation not supported!
```
But now I am getting this error on client side:

```
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  Internal error (/home/devel/smb_share/sysrepo/src/shm_sub.c:1108).

>
```
Am I doing it wrong?
I did it like this in older version of sysrepo, only arguments of **sr_set_error** function where different.

Thanks in advance
Best regards

**Comment by michalvasko** [comment]
Hi,
there is something wrong in *sysrepo*, you should never see an internal error. However, there are some basic test cases for user callback error meaning your use-case is a more complex one. To reproduce it I will need all the information about subscribers on this module. So, how many subscribers there are for the module (best would be to include this source code if you can)? What datastore did you try it with? Do you set the error for the `SR_EV_CHANGE` event? What is the change that is being processed, does it include changes in more modules?

Regards,
Michal

**Comment by Roky7250** [comment]
Hi,
I installed new sysrepo and message from above **Internal error (/home/devel/smb_share/sysrepo/src/shm_sub.c:1108).** is not present anymore.
But still I did not managed to set proper error message inside callback using **sr_set_error** function.

I am doing it like this inside callback: 
```
    while(SR_ERR_OK == sr_get_change_next(session, iter, &op, &old_value, &new_value))
    {
	    if(op == SR_OP_DELETED)
	    {
	    	sr_set_error(session, xpath, "Delete operation not supported!");
	    	return SR_ERR_OPERATION_FAILED;
	    }
    }
```
On client side I am getting this message: 
```
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  Callback event "rpc" with ID 2 processing timed out.
```

I looked your examples in sysrepo:

```
        sr_set_error(session, "/path/to/a/node", "Custom user callback error.");
        ret = SR_ERR_UNSUPPORTED;
```
Can you tell me what am I doing wrong?

Note: event inisde callback is SR_EV_CHANGE.

Best regards

**Comment by michalvasko** [comment]
Hi,
I have just tested this and it works perfectly. In your case the problem simply will be that before your custom error is actually returned, the callback times out. I cannot tell you the reason, that is up to you, but you can also try simply increasing the timeout (*netopeer2-server* `DATA_CHANGE_TIMEOUT` compile-time variable).

Regards,
Michal

**Comment by Roky7250** [comment]
Thanks for advice.

Regards
