### ISSUE TITLE
[new sysrepo] Cannot provide operational leaf-list of leafref

### ISSUE THREAD

**Issue by gitter-runner** [sysrepo/sysrepo#1806]
Greetings,
I use the _ietf-hardware@2018-03-13.yang_ model with the following startup config data:

```
<hardware xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware">
  <component>
    <name>HW1</name>
    <class xmlns:ianahw="urn:ietf:params:xml:ns:yang:iana-hardware">ianahw:container</class>
  </component>
  <component>
    <name>HW2</name>
    <class xmlns:ianahw="urn:ietf:params:xml:ns:yang:iana-hardware">ianahw:module</class>
    <parent>HW1</parent>
    <parent-rel-pos>1</parent-rel-pos>
  </component>
</hardware>
```

I try to implement an operational data provider for contains-child which looks like this:

```
leaf-list contains-child {
      type leafref {
      path "../../component/name";
      }
      config false;
      description
      "The name of the contained component.";
      reference
      "RFC 6933: Entity MIB (Version 4) - entPhysicalChildIndex";
    }
```

When I get data from the operational datastore I get the following error:

```
$ sr_get_items_example /ietf-hardware:hardware//. operational
Application will get "/ietf-hardware:hardware//." from "operational" datastore.
[ERR]: Leafref "../../component/name" of value "HW2" points to a non-existing leaf. (path: /ietf-hardware:hardware/component[name='HW1']/contains-child[.='HW2'])
```

I attached the modified example that subscribes for the model.
In old sysrepo (0.7.x) it worked by providing the same data on the old API.

sysrepo version: 1.4.3
libyang version: 1.0.131

[reprod_c.txt](https://github.com/sysrepo/sysrepo/files/4165224/reprod_c.txt)

Thanks!

**Comment by michalvasko** [comment]
Hi,
you are right, despite quite a difficult setup you have done everything correctly and the value should be valid. There was a minor bug, which should be fixed now and a test also included. Just note the fix commit is b7d553dd4e733e8881197181f2b57911f671ba60, it seems I have incorrectly rebased a commit.

Regards,
Michal
