### ISSUE TITLE
Question about the way sysrepo presents xpath in events

### ISSUE THREAD

**Issue by igortern** [sysrepo/sysrepo#1807]
Hi,
The new sysrepo presents xpath in events differently than the old one did. I'm not sure that it is the intent and is not going to change, would appreciate if you can confirm.

Configuration in RPC looks like this:
```xml
<bbf-lt:link-table>
       <bbf-lt:from-interface>ani-user2</bbf-lt:from-interface>
       <bbf-lt:to-interface>vani-user2</bbf-lt:to-interface>
</bbf-lt:link-table>
```
Both from-interface and to-interface above are of type type if:interface-ref

When iterating in the relevant callback using sr_get_change_next, the new value returned for "to-interface" node looks like this.
```
(gdb) p *sr_new_val
$20 = {xpath = 0x7fffdc007560 "/bbf-link-table:link-table/link-table[from-interface='ani-user2']/to-interface[.='vani-user2']", type = SR_STRING_T, dflt = 0x0, origin = 0x0, data = {
    binary_val = 0x7fffdc00bf10 "vani-user2", bits_val = 0x7fffdc00bf10 "vani-user2", bool_val = 0x10, decimal64_val = 6.9533259696857678e-310, enum_val = 0x7fffdc00bf10 "vani-user2", 
    identityref_val = 0x7fffdc00bf10 "vani-user2", instanceid_val = 0x7fffdc00bf10 "vani-user2", int8_val = 0x10, int16_val = 0xbf10, int32_val = 0xdc00bf10, int64_val = 0x7fffdc00bf10, 
    string_val = 0x7fffdc00bf10 "vani-user2", uint8_val = 0x10, uint16_val = 0xbf10, uint32_val = 0xdc00bf10, uint64_val = 0x7fffdc00bf10, anyxml_val = 0x7fffdc00bf10 "vani-user2", 
    anydata_val = 0x7fffdc00bf10 "vani-user2"}}
```
That is, vani-user2 appears twice - in the xpath and in the value. In the old sysrepo it appeared only once in the value. Is this new presentation intentional?

Thanks,
Igor

**Comment by michalvasko** [comment]
Hi,
I am not sure now whether this was intentional but it was included in the tests. Anyway, for keeping compatibility it is probably better to not put the value in the xpath, so I have changed it.

Regards,
Michal

**Comment by igortern** [comment]
Great, thanks.

Regards,
Igor
