### ISSUE TITLE
Internal error (../sysrepo/src/common.c:1101)

### ISSUE THREAD

**Issue by berstrob** [sysrepo/sysrepo#1808]
Hello again. Still playing with "openconfig-system:system" and a recent devel version.

I tried to implement a method to "refresh" the server-state-callbacks  :
openconfig-system:system/dns/servers/server[address:'8.8.8.8']/state
openconfig-system:system/dns/servers/server[address:'8.8.8.9']/state
openconfig-system:system/ntp/servers/server[address:'8.8.8.8']/state
.
.
.
After adding/removing one of them i do call my funtion(simplyfied) ;

```
static sr_subscription_ctx_t *serverstatecallback;


int refresh_state(sr_session_ctx_t *session) {
   int opt=SR_SUBSCR_DEFAULT
   DBG("pointer before: %p", (void *) serverstatecallback );
   sr_unsubscribe(serverstatecallback) 
   for (int i=0;i<servercount;i++) {
      sr_oper_get_items_subscribe(session,"openconfig-system",server[i].path,openconfig_server_cb,NULL,opt, &serverstatecallback);
       opt=SR_SUBSCR_CTX_REUSE;
    }
   DBG("pointer after: %p", (void *) serverstatecallback );
}

```

If i do it at initialisation time it works as planed: multiple calls with differnt amounts(or the same) one after another (and do result in the same pointer every time, for one run).  

If i try to do the same in a sr_config_change_callback , it works the first callback (with the pointer i had from init), but i get a new pointer every time (just to test i called it mutiple times in one callback, it worked and gave me a new pointer once per call of my funktion) .

After that in a second sr_config_change_callback (same function, just another add/del, switching the order does not matter), i get the "Internal error (../sysrepo/src/common.c:1101)"  with the last pointer from the call before, and if i ignore that i get a duplication error trying to add the first servercallback (and they callbacks do not work after that: timeout). 

Did i understand something wrong and should I implement it differently (like just adding new ones, letting the deleted unchanged,what will happen to them then?), or is that a bug?

**Comment by michalvasko** [comment]
Hi,
I think your use-case is a really bad one but please provide more details first to know for sure. Firstly, what subscriptions are there on `serverstatecallback`? Then, could you paste the debug output with your messages? IT should be clear from the other messages what is happening, when are you in the callback.

Regards,
Michal

**Comment by berstrob** [comment]
Hello,
on  `serverstatecallback` there are only those for the servers, i did make another for all the other callbacks. Events are start(1),  add one (2) , show all (1), remove one (3)

(i have added a lot more debug stuff from my testing program, if i need to remove it just say so, but it maybe usefull)

[programoutput.log](https://github.com/sysrepo/sysrepo/files/4170127/programoutput.log)

[sysrepo.log](https://github.com/sysrepo/sysrepo/files/4170128/sysrepo.log)

**Comment by berstrob** [comment]
After some thinking : the other thing i could do to make it work would be a new separate subscription for each serverstate, but that seems like way more resources used.

**Comment by michalvasko** [comment]
Hi,
I was referring to these outputs
```C
DBG("pointer before: %p", (void *) serverstatecallback );
DBG("pointer after: %p", (void *) serverstatecallback );
```
and I could not find them in the logs you provided. Generally, they did not help me. So, do you think I could reproduce it simply, based on some exact steps you provide?

> After some thinking : the other thing i could do to make it work would be a new separate subscription for each serverstate, but that seems like way more resources used.

I suppose you could do this. There are not much more resources used except that for every subscription a separate thread is created by default.

Regards,
Michal

**Comment by berstrob** [comment]
Hello, 
they are in the file  `programoutput.log` : 

before = ` run openconfig_system_do_variable_subs, ... `
after =  `finish openconfig_system_do_variable_subs, ...` 

 i did simplified it for my example code, between those are the path added for each call.

I will try to write a  small codesnippet for you to run (without all the extra stuff). 

Regards,
Bernd

**Comment by michalvasko** [comment]
Hi,
I see, but if you could provide something simple, that would be best.

Regards,
Michal

**Comment by berstrob** [comment]
so i wrote a simpel plugin (oven+my stuff).  add/delete  servers (or just change the config) a few times and it crashes.
you will need the openconfig-system.yang


[main.txt](https://github.com/sysrepo/sysrepo/files/4181179/main.txt)

**Comment by michalvasko** [comment]
Hi,
good that you provided that example, I do not think I would have figured this out otherwise. But it is quite simple, in the callbacks you are subscribing with the implicit callback session that is just temporary and cannot be used for this purpose. It was not mentioned anywhere, but now the subscription will simply fail. Actually, I made a similar mistake in one of the tests.

I have also tried your example with `sess` instead of `session` and it worked fine. Just a final note, I have no idea what you are trying to achieve by "refreshing" subscriptions.

Regards,
Michal

**Comment by berstrob** [comment]
Hi,

ok now it all makes sense, thanks for the explanation. 

My goal was : since those servers could be added and delete at runtime , to always  only have the right data_subscriptions , with a matching "path" set so answering the state call would be easy, since every call would only be used once.

In the meantime i switched to the gerneric dataproviders (without the name in path), more work at the callback site but i got it to work (i think :) ), for usermanagment i already planed on that anyway 

Now i just have to get the passwords ******.

Regards,
Bernd
