### ISSUE TITLE
sysrepo running datastore empty

### ISSUE THREAD

**Issue by maksimvuleta** [sysrepo/sysrepo#1810]
On the sysrepo version 0.7.7 we had a function like _fill_startup()_ which will open the module_name.startup and fill it with proper data. This _fill_startup()_ is called in the _sr_plugin_init_cb_ function. After the startup is filled up, the _sr_module_change_subscribe_ function is called and so on. This startup is copied to the running, and everything was fine. 

Now, with version 1.4.2, we used rthe same principle and it does not work. The running datastore is empty. I assumed that startup is copied to the running before our _fill_startup()_ . 

Am I right?

Is there any solution to fill the startup with _sr_plugin_init_cb or _sr_module_change_subscribe_?

**Comment by michalvasko** [comment]
Hi,
right, this now functions quite differently because of the [operational](https://netopeer.liberouter.org/doc/sysrepo/master/index.html#datastores) datastore. All the information is there. However, you setting `startup` before meant that you basically did not want to support this datastore and you always set exactly what you wanted to have initially in the `running` datastore. If this is really what you want, I think you can simply change your function from `fill_startup()` to `fill_running()` and you will get the same functionality.

Regards,
Michal

**Comment by maksimvuleta** [comment]
Hi,

As I understood,  it is allowed to manually open and modified the _/dev/shm/sr_ieee8021-mstp.runnin_g ?

Thanks for the idea.

If we will need to store the startup configuration for some further purpose, we will have a separate application do get the startup configuration and store it somewhere. We can just import this startup is the case we need it. 

Best regards,
Maksim.

**Comment by michalvasko** [comment]
Hi,
okay, i should have added more information because **manually editing any files is not supported** and *sysrepo* may break, it is an undefined behavior you are responsible for. The situation was the same with the old *sysrepo*, just because it may have seemed like it worked does not mean you were allowed to do it. But why not use API function `sr_replace_config()`? That is what I meant except I left it out for some reason.

Regards,
Michal

**Comment by maksimvuleta** [comment]
I do it like this in the fill_datastore function:
1. Create struct lyd_node *root for some module, and fill it with my propoer data.
2. sr_session_switch_ds(session, SR_DS_STARTUP)
3. sr_replace_config(session, "module-name", root, 0, 0)
4. sr_session_switch_ds(session, SR_DS_RUNNING)
5. sr_copy_config(session, "module-name", SR_DS_STARTUP, 0, 0)

If I have only one module installed, it works fine.
When there is more than one module installed, the sysrepo-plugind boot fails on second module. The first module initialize successfully but sysrepo-plugind fails to initialize the second module. 

Am I doing something wrong? Should I close/stop the session in the fill_datastore function after the manipulation of datastores?

**Comment by michalvasko** [comment]
Hi,
that seems to me is the correct procedure, what exactly is the problem in the second module, can you provide some error output?

Regards,
Michal

**Comment by maksimvuleta** [comment]
Hi,
It is behaving strangely.
After the first boot of my controlled device, everything seems to work fine.
After I reboot the device, I got an error like this:

> Feb 25 15:29:20 de-eval-board sysrepo-plugind[1290]: [INF] ieee8021-mstp plugin initialized successfully.
> Feb 25 15:29:20 de-eval-board sysrepo-plugind[1290]: [ERR] ietf-interfaces plugin initialization failed: Internal error.
> Feb 25 15:29:20 de-eval-board sysrepo-plugind[1290]: [ERR] Plugin initialization failed (Internal error).
> Feb 25 15:29:22 de-eval-board netopeer2-server[1418]: Connecting to sysrepo failed (Timeout expired).
> Feb 25 15:29:22 de-eval-board netopeer2-server[1418]: Server init failed.

Then I do shm clean, reboot device and initialization of ietf-interfaces plugin passed, but it fails on some other plugin initialization.
Then I try to run sysrepo-plugind manually and a got the segmentation fault error. The log is attached 
[sysrepo-plugind.log](https://github.com/sysrepo/sysrepo/files/4250878/sysrepo-plugind.log)

**Comment by maksimvuleta** [comment]
Then I do clean up the shm again and start sysrepo-plugind manually and it seems to work fine with all my plugins installed.

**Comment by michalvasko** [comment]
Hi,
I am not sure I can help you here because these messages
```
Feb 25 15:29:20 de-eval-board sysrepo-plugind[1290]: [INF] ieee8021-mstp plugin initialized successfully.
Feb 25 15:29:20 de-eval-board sysrepo-plugind[1290]: [ERR] ietf-interfaces plugin initialization failed: Internal error.
```
are yours. Only this one
```
Feb 25 15:29:20 de-eval-board sysrepo-plugind[1290]: [ERR] Plugin initialization failed (Internal error).
```
is printed by `sysrepo-plugind` itself. Meaning, the reason for the internal error is in your initialization callback.

Regards,
Michal

**Comment by maksimvuleta** [comment]
Did you look at the sysrepo-plugind.log from my last comment. 
What this means?

> 003248-013504 [ 10256]: (wasted 10256)
> 013504-013532 [    28]: connections (1)
> 013532-014252 [   720]: conn mods lock (30, conn 0x1cbc1d8)
> 
> Segmentation fault

**Comment by michalvasko** [comment]
HI,
I did see it, it probably means that the *sysrepo* SHM is corrupted. The reason for this will most likely be the internal error in your initialization callback. That is why I asked you to check what causes it and best to provide some more output of that internal error. Without that I have absolutely nothing to go on.

Regards,
Michal

**Comment by maksimvuleta** [comment]
Hi,
It is strange that every time I run a device, the different module plugin fails. 
When I installed just one module plugin (it is no matter which one) on my device, everything works fine. 
I will try to provide some better log for you.

You did not have any issue with multiple plugins installed on the sysrepo?

**Comment by michalvasko** [comment]
Hi,
it worked fine but I have not tested `sysrepo-plugind` much because there is not much to test anyway. It is just a simple wrapper. Anyway, I would say it does not matter which plugin fails, it should be enough to get the log of any *sysrepo* function failure.

Regards,
Michal

**Comment by maksimvuleta** [comment]
Hi,
The issue was not with my plugins. It was a problem with my build setup. The sysrepo-plugind was booting up before the sysrepoctl and sysrepocfg finished all requested operations.
Sorry for bothering you. 

Now, I have another question.
How to increase a timeout for the **_get_** operation from netopeer2-cli?
When I try to **_get_** the complete data from my device I got the message:

> Callback event "rpc" with ID 7 processing timed out.

NOTE:
I had already set the **DATA_CHANGE_TIMEOUT** to **10** and **DATA_CHANGE_WAIT** to **ON** value in Neopteer2 server CMakeLists.txt file.

**Comment by michalvasko** [comment]
Hi,
please update *netopeer2* and change the option `RPC_TIMEOUT`.

Regards,
Michal

**Comment by maksimvuleta** [comment]
OK.

Is this latest server version 1.1.14 compatible with sysrepo 1.4.2 master version?

Best regards,
Maksim.

**Comment by michalvasko** [comment]
Hi,
it is always best to use the same branches of *sysrepo* and *netopeer2* but looking briefly at the changes, it should work.

Regards,
Michal

**Comment by maksimvuleta** [comment]
Ok,
Thanks a lot for the answers and inforamtions.

Best regards,
Maksim.
