### ISSUE TITLE
sysrepoctl inoperable due to conflicting revisions

### ISSUE THREAD

**Issue by frimpler** [sysrepo/sysrepo#1814]
Hi Michal,

I'm trying to get modules required by Netopeer2 installed using sysrepoctl. One problem seems to be, that sysrepo has ietf-netconf pre-installed in a different revision than required by Netopeer2. At least that's how it looks like. But the main issue is, that sysrepoctl becomes inoperable, if ietf-netconf-nmda will be tried to get installed.

(Apart from that, do you have a suggestion how to recover - I assume - the SHM in such a case and get sysrepoctl working again. Because currently I have to restart everything, whenever I run in such an issue.)

Regards,
Frank

```
/git/sysrepo # sysrepoctl -l
Sysrepo repository: /bld/sysrepo/repository

Module Name                | Revision   | Flags | Owner            | Permissions | Submodules | Features
--------------------------------------------------------------------------------------------------------
ietf-datastores            | 2017-08-17 | i     |                  |             |            |
ietf-inet-types            | 2013-07-15 | i     |                  |             |            |
ietf-netconf               | 2011-06-01 | I     | frimpler:nogroup | 666         |            |
ietf-netconf-notifications | 2012-02-06 | I     | frimpler:nogroup | 666         |            |
ietf-netconf-with-defaults | 2011-06-01 | I     | frimpler:nogroup | 666         |            |
ietf-origin                | 2018-02-14 | I     | frimpler:nogroup | 666         |            |
ietf-yang-library          | 2019-01-04 | I     | frimpler:nogroup | 666         |            |
ietf-yang-metadata         | 2016-08-05 | i     |                  |             |            |
ietf-yang-types            | 2013-07-15 | i     |                  |             |            |
yang                       | 2017-02-20 | I     | frimpler:nogroup | 666         |            |

Flags meaning: I - Installed/i - Imported; R - Replay support; N - New/X - Removed/U - Updated; F - Feature changes

/git/sysrepo # sysrepoctl -v 4 -i ../yang/ietf-netconf-nmda\@2019-01-07.yang -s ../yang/repo
[INF]: Applying scheduled changes.
[INF]: No scheduled changes.
[INF]: Module "ietf-netconf-nmda" scheduled for installation.
[INF]: File "ietf-netconf@2013-09-29.yang" was installed.
[INF]: File "ietf-netconf-acm@2018-02-14.yang" was installed.
/git/sysrepo # sysrepoctl -l
[ERR]: Module "ietf-netconf" in another revision already implemented.
[ERR]: Module "ietf-netconf-with-defaults" parsing failed.
sysrepoctl error: Failed to connect (libyang error)
```

**Comment by michalvasko** [comment]
Hi Frank,
right, you manage to find still new ways how to break *sysrepo*. But now it should be properly detected and refused. You must update modules separately if you want to implement a newer revision.

Regards,
Michal

**Comment by frimpler** [comment]
Hi Michal,

thanks for the fix. I can confirm, that sysrepoctl remains operable with it. So good so far, but there is a catch-22, now (and was before). As I wrote, I'm trying to integrate the module revisions of Netopeer2. As soon as ietf-netconf@2013-09-29 is in the seach-path (what it is for Netopeer2), the installation of ietf-netconf-nmda will be refused. And it's impossible to uninstall the older revision of ietf-netconf:  [ERR]: Internal module "ietf-netconf" cannot be uninstalled. 
I worked around it, by omitting the --search-dirs parameter. But I can't tell up to now, if this will cause issues in Netopeer2 operations.
However, I guess, the quickest way is to upgrade sysrepo to the same revision.

Best regards and have a nice weekend,
Frank

**Comment by michalvasko** [comment]
Hi Frank,
I am not sure what are you trying to do. *netopeer2-server* installs itself correctly by [updating](https://github.com/CESNET/Netopeer2/blob/master/server/setup.sh#L18) the module.

Regards,
Michal

**Comment by frimpler** [comment]
Hi Michal,

Ok, I have to admit, that I didn't realize, there's a new switch -U. Thanks for pointing at it. I simply used the old way (by simply replacing the old switches with the new ones in our existing scripts) and that way the ietf-netconf.yang "upgrade" was kind of omitted and it caused the issue as above

Regards,
Frank
