### ISSUE TITLE
SR_ERR_TIME_OUT expired 

### ISSUE THREAD

**Issue by gurugod** [sysrepo/sysrepo#1816]
hi folks,
      While execution of my code I got error message of SR_ERR_TIME_OUT. I did quite search in code. But I didn't understand condition for time out . Only statement I got is "If the response contains too many elements time out may be exceeded, SR_ERR_TIME_OUT" .Can anyone help me out with what is Time_out condition  ? and when it will occur ?

Thanks,
Gaurav J.

**Comment by michalvasko** [comment]
Hi,
could you please provide some output of at least say which function printed this/returned this error?

Regards,
Michal

**Comment by gurugod** [comment]
hi,
     Function name is sr_set_item()

Thanks,
Gaurav J.

**Comment by michalvasko** [comment]
Hi,
I do not see any way how `sr_set_item()` can return `SR_ERR_TIME_OUT` so without more information I am not able to help you.

Regards,
Michal

**Comment by gurugod** [comment]
hi michal,
         Thanks for replying. I am unable to create that scenario. Can you just tell me what time_out condition in ER_SRR_TIME_OUT actually does for my understanding ? If next time I face any error, so then I will able to understand it by myself.

**Comment by michalvasko** [comment]
Hi,
well, I am not sure what to tell you, it simply means that a timeout was elapsed before an operation was successful. It is generally either a lock time out or a callback timeout but none of these occur for `sr_set_item()` therefore I do not think this function could have returned it.

Regards,
Michal
