### ISSUE TITLE
Need to confrigure GUI to netopeer2 sever.

### ISSUE THREAD

**Issue by Akhil-123456789** [sysrepo/sysrepo#1817]
Hi,
Can any one suggest me which GUI i need configure for Netopeer2 sever of below links.

https://github.com/CESNET/liberouter-gui
https://github.com/CESNET/Netopeer2GUI/
https://github.com/CESNET/Netopeer-GUI

In all the above links so many lib file and dependence are present.If somebody know about it.kindly help me with correct link i need to use and also documentation for how to install it.

**Comment by rkrejci** [comment]
Hi,
- **Netopeer-GUI** - old, deprecated, not maintained version, do not use it, we should probably somehow archive and hide it.
- **liberouter-gui** - generic GUI framework containing features like user management or overall configuration. Itself it does not contain anything useful for end-users, but our project-specific GUIs are deployed as modules to liberouter-gui
- **Netopeeer2GUI** - most recent GUI, implemented as a plugin into liberouter-gui. It utilizes libnetconf2 and libyang to communicate with NETCONF devices. There is a development version (it is based on Angular6) as well as a compiled server ready to deploy. 

So I recommend trying Netopeer2GUI. Unfortunately, there is currently no one who would actively develop and maintain the project, so it is more an example of what can be done.

**Comment by Akhil-123456789** [comment]
Only installing Netopeeer2GUI will I be able to configure Netopeer2 device?
where can I find correct procedure to install it?

can you please share the correct link to install the Netopeer2GUI.

**Comment by jktjkt** [comment]
You can use any other NETCONF client, too. There are some proprietary GUI clients and some open source CLI ones.

**Comment by rkrejci** [comment]
ad install procedure - you can see [several Vagrant files available](https://github.com/CESNET/Netopeer2GUI/blob/master/vagrant/Ubuntu-release/Vagrantfile) for the steps needed to install and run the gui
