### ISSUE TITLE
How to create new instances in sysrepo datastore

### ISSUE THREAD

**Issue by tiago-vieira99** [sysrepo/sysrepo#1820]
Hi!

One question about an issue I am facing with sysrepo:

If I have this configuration in the sysrepo datastore:

```
<bbf-xpongemtcont:xpongemtcont xmlns:bbf-xpongemtcont="urn:bbf:yang:bbf-xpongemtcont">
		   <bbf-xpongemtcont:traffic-descriptor-profiles>
			  <bbf-xpongemtcont:traffic-descriptor-profile>
				 <bbf-xpongemtcont:name>TDP0</bbf-xpongemtcont:name>
				 <bbf-xpongemtcont:assured-bandwidth>10000000</bbf-xpongemtcont:assured-bandwidth>
				 <bbf-xpongemtcont:fixed-bandwidth>10000000</bbf-xpongemtcont:fixed-bandwidth>
				 <bbf-xpongemtcont:maximum-bandwidth>30000000</bbf-xpongemtcont:maximum-bandwidth>
			  </bbf-xpongemtcont:traffic-descriptor-profile>			  
			  <bbf-xpongemtcont:traffic-descriptor-profile>
				 <bbf-xpongemtcont:name>TDP1</bbf-xpongemtcont:name>
				 <bbf-xpongemtcont:assured-bandwidth>10000000</bbf-xpongemtcont:assured-bandwidth>
				 <bbf-xpongemtcont:maximum-bandwidth>30000000</bbf-xpongemtcont:maximum-bandwidth>
			  </bbf-xpongemtcont:traffic-descriptor-profile>			  
			  
			  <bbf-xpongemtcont:traffic-descriptor-profile>
				 <bbf-xpongemtcont:name>TDP2</bbf-xpongemtcont:name>
				 <bbf-xpongemtcont:assured-bandwidth>10000000</bbf-xpongemtcont:assured-bandwidth>
				 <bbf-xpongemtcont:fixed-bandwidth>20000000</bbf-xpongemtcont:fixed-bandwidth>
				 <bbf-xpongemtcont:maximum-bandwidth>30000000</bbf-xpongemtcont:maximum-bandwidth>
			  </bbf-xpongemtcont:traffic-descriptor-profile>
			  
		   </bbf-xpongemtcont:traffic-descriptor-profiles>
</bbf-xpongemtcont:xpongemtcont>
```

How can I properly create a new instance and then set new items to it using sysrepo funtions?

Thanks for your attention.

Regards,
Tiago

**Comment by tiago-vieira99** [comment]
Thank you so much for your quick answer!

It worked perfectly, I was complicating too much. Thank you a lot.

Best Regards,
Tiago

**Comment by tiago-vieira99** [comment]
Hello michalvasko!

I was trying to get all the items after the node 'TDP1' for example, and I was using this xpath:

/bbf-xpongemtcont:xpongemtcont/traffic-descriptor-profiles/traffic-descriptor-profile[name='TDP1']/following-sibling::*

It happens that sysrepo cannot resolve this expression.


Do you have any suggestion to get all the nodes after a specific one?


Regards,
Tiago

**Comment by michalvasko** [comment]
Hi Tiago,
yes, the cause of this is that *libyang* does not support axes at all because we considered it not to be worth all the effort. Also, it should always be possible to write these expressions without the use of axes albeit perhaps not that nicely. In this case I think you could use
```
/bbf-xpongemtcont:xpongemtcont/traffic-descriptor-profiles/traffic-descriptor-profile[position() > ../traffic-description-profile[name='TDP1']/position()]
```
but I have not tested this.

Regards,
Michal

**Comment by tiago-vieira99** [comment]
Thanks for your answer @michalvasko ! 

That xpath didn't work. Do you know any way to iteratively get N nodes of sysrepo?

Regards,
Tiago

**Comment by michalvasko** [comment]
Hi,
no iterations are supported. You can only use the `position()` predicate and compare it with a number.

Regards,
Michal
