### ISSUE TITLE
Cannot get oper data: Internal error (.../src/shm_sub.c:2198).

### ISSUE THREAD

**Issue by iljatab** [sysrepo/sysrepo#1821]
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.9 (SO v5.0.9)
yanglint SO 1.6.9
netopeer2-server 1.1.12

Hello,

We just upgraded sysrepo from 1.3.62 to 1.4.9 )together with other components) and oper data handler for openconfig-interfaces stopped working.

The sr_oper_get_items_subscribe() is called with the following "path" arguments:
```
                       {"/openconfig-interfaces:interfaces/interface/state"},
                       {"/openconfig-interfaces:interfaces/interface/state/counters"},
                       {"/openconfig-interfaces:interfaces/interface/subinterfaces/subinterface/state"},
                       {"/openconfig-interfaces:interfaces/interface/subinterfaces/subinterface/state/adva-dnos-ac:counters"},
                       {"/openconfig-interfaces:interfaces/interface/openconfig-if-ethernet:ethernet/openconfig-if-ethernet:state"},
                       {"/openconfig-interfaces:interfaces/interface/openconfig-if-ethernet:ethernet/openconfig-if-ethernet:state/counters"},
                       {"/openconfig-interfaces:interfaces/interface/openconfig-if-aggregate:aggregation/openconfig-if-aggregate:state"},
                       {"/openconfig-interfaces:interfaces/interface/subinterfaces/subinterface/openconfig-vlan:vlan/openconfig-vlan:state"},
                       {"/openconfig-interfaces:interfaces/interface/subinterfaces/subinterface/openconfig-if-ip:ipv4/openconfig-if-ip:state"},
                       {"/openconfig-interfaces:interfaces/interface/subinterfaces/subinterface/openconfig-if-ip:ipv6/openconfig-if-ip:state"},
                       {"/openconfig-interfaces:interfaces/interface/subinterfaces/subinterface/openconfig-if-ip:ipv4/openconfig-if-ip:addresses/openconfig-if-ip:address/openconfig-if-ip:state" },
                       {"/openconfig-interfaces:interfaces/interface/subinterfaces/subinterface/openconfig-if-ip:ipv6/openconfig-if-ip:addresses/openconfig-if-ip:address/openconfig-if-ip:state" } 
```
The sr_oper_get_items_subscribe() reports no errors.

The netopeer2-cli output:
```
> get --filter-xpath /openconfig-interfaces:interfaces
cli_send_recv: Timeout for receiving a reply expired.
>
```

Our application callback, registered with sr_oper_get_items_subscribe() is not called at all.
Instead sysrepo reports error:
```
Internal error (/usr/src/debug/sysrepo/1.4.9+gitAUTOINC+fefcbbcced-r0/git/src/shm_sub.c:2198).
```

The same app worked OK before upgrade.

Do you have any idea what could be wrong?
Are there any API changes between upgrade that we missed to apply?

Thanks!

Ilja.

**Comment by iljatab** [comment]
The same issue happens in other YANG models where the "config no" leaf or container is part of configurable list.

Otherwise, if "config no" data is not part of configurable list, things wok OK.

Ilja.

**Comment by michalvasko** [comment]
Hi Ilja,
I am not sure what the problem may be, but if you update *sysrepo*, you should see some actual error before the internal one. Please paste that one here.

Regards,
Michal

**Comment by iljatab** [comment]
Hi Michal,

Thanks for reply!

After sysrepo upgrade to v1.4.10 (SO v5.0.10):

First I did get-config for one interface:
```
> get-config --filter-xpath /openconfig-interfaces:interfaces/interface[name='eth-1/0/1'] --source running
DATA
<interfaces xmlns="http://openconfig.net/yang/interfaces">
  <interface>
    <name>eth-1/0/1</name>
    <config>
      <name>eth-1/0/1</name>
      <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
      <enabled>false</enabled>
    </config>
  </interface>
</interfaces>
>
```

Looks pretty OK.

Now get command:
```
> get --filter-xpath /openconfig-interfaces:interfaces/interface[name='eth-1/0/1']
cli_send_recv: Timeout for receiving a reply expired.
> 
```

And the error message are:
```
Leafref "../config/name" of value "eth-1/0/1" points to a non-existing leaf.
Internal error (/usr/src/debug/sysrepo/1.4.10+gitAUTOINC+8515142160-r0/git/src/shm_sub.c:2200).
```

The message about missing leafref doesn't look correct - as we can see from get-config the interface name looks OK under .../interface/name and .../interface/config/name (the first one one is a leafref to second).

Could you please check?

Ilja.

**Comment by michalvasko** [comment]
Hi,
right, it should be fixed now.

Regards,
Michal

**Comment by iljatab** [comment]
Looks working, thanks!
