### ISSUE TITLE
Want to replace a key value in list

### ISSUE THREAD

**Issue by avinashtiwaskar** [sysrepo/sysrepo#1822]
Hi,

I have  multiple lists in my YANG model. For some reason, I want a feature to update key value for a particular list. When I try to use sr_set_item(), it throws an error that I am trying  to update a key parameter. 
I have checked from sysrepocgf, we can update the complete config if we pass xml config as and argument. Internally, it might be doing something to change the content of list key.
Also, from netopeer2-cli, to replace any content, we can send delete command followed by add a new config. This will replace existing data in list.

Is there any way to replace the key value of a particular list programatically? Any help would be appreciated.

Thanks,
Avinash

**Comment by michalvasko** [comment]
Hi,
technically, you can never change key value, it is forbidden (no way to do it) by NETCONF. You can only create or remove whole list instances. That is what is effectively done by `sysrepocfg` or `netopeer2-cli` and that is what you also need to do by `sr_set_item()`.

Regards,
Michal
