### ISSUE TITLE
Sysrepo-Netopeer2-Libyang-Libnetconf instalation question.

### ISSUE THREAD

**Issue by serega911** [sysrepo/sysrepo#1823]
Hi.

I'm going to try porting CESNET Netconf solution to arm-based network device.
I'm newcomer at this field, so I apologize for trivial questions.

So, my questions are:
1. **Is it possible to build it with cross-compiler?**
2. After binaries and libraries are compiled, it seems that I have to copy them somewhere (for example /usr/bin) and do some extra stuff. **What exactly I have to do? Is there some script to do that?**

Thanks in advance,
    Sergii.

**Comment by jktjkt** [comment]
We're doing this, and we're using [buildroot](https://buildroot.org/downloads/manual/manual.html) for this purpose. The installation is non-trivial, so my advise is to avoid reinventing the wheel and just use some of the existing examples. Here are [our modifications and packages](https://gerrit.cesnet.cz/plugins/gitiles/github/buildroot/buildroot/+log/refs/heads/cesnet/2020-01-17). We're using the legacy branches while upstream Buildroot's `master` has moved to the "new sysrepo".

**Comment by schaveyt** [comment]
@jktjkt 

Help! We were able to get buildroot to compile kernel for these packages, however when we go to build the root filesystem via buildroot....it fails on the step for the _device_table.txt.

It would appear that lines 9 thru 15 in the [netopeer2-keystored.mk](https://gerrit.cesnet.cz/plugins/gitiles/github/buildroot/buildroot/+/refs/heads/cesnet/2020-01-17/package/netopeer2-keystored/netopeer2-keystored.mk) are trying to setup permissions for:

- /etc/sysrepo/data/ietf-keystore.persist
- /etc/sysrepo/data/ietf-keystore.running 
- /etc/sysrepo/data/ietf-keystore.running.lock 
- /etc/sysrepo/data/ietf-keystore.startup
- /etc/sysrepo/data/ietf-keystore.startup.lock

Unfortunately, our buildroot/output/target/etc/sysrepo/ contains no files. Only 'data' and 'yang' folders.

Double-checking things earlier in the build, the netopeer2-keystored does install that ietf-keystore..sorta:

~~~bash
[7m>>> netopeer2-keystored v0.7-r2 Installing to target[27m
PATH="buildroot/output/host/bin:buildroot/output/host/sbin:output/host/usr/bin:buildroot/output/host/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java"  /usr/bin/make -j4  DESTDIR=/usr/project/build/XLDK/buildroot/output/target install/fast -C buildroot/output/build/netopeer2-keystored-v0.7-r2/keystored
make[1]: Entering directory 'buildroot/output/build/netopeer2-keystored-v0.7-r2/keystored'
Install the project...
-- Install configuration: "Release"
-- Installing: buildroot/output/target/usr/lib/pkgconfig/keystored.pc
-- Installing: buildroot/output/target/etc/keystored/keys
- Module ietf-x509-cert-to-name already installed.
- Module ietf-keystore already installed.
- Some ietf-keystore configuration set, skipping stock key configuration import.
-- Installing: buildroot/output/target/usr/lib/sysrepo/plugins/libkeystored.so
~~~

So we cannot figure out we don't see those ietf_keystore files to make the permission statements happy.

**Comment by serega911** [comment]
@jktjkt, I have successfuly compiled it with bitbake, thanks for your help.
@schaveyt, please, close this ticket after you recieve your answer.

**Comment by schaveyt** [comment]
Will do. Hoping that @jktjkt sees this.
