### ISSUE TITLE
Issues with when condition

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1824]
Hi,

I have patched application changes example to subscribe for multiple modules.
I am getting some issues with `when` validation. Please correct my understanding if I miss some thing.

**a.yang**
```
module a {
    prefix a;
    namespace a;

    container ac{
        leaf al{
            type string;
        }
    }
}
```

**b.yang**
```
module b {
    prefix b;
    namespace b;
    import a{prefix a;}

    augment '/a:ac' {
        when "starts-with(al,'sri')";
        container baugac{
            leaf bl{
                type string;
            }
        }
    }
}
```

**steps**
```
sysrepoctl -i a.yang
sysrepoctl -i b.yang
```

**PART 1 No application changes example running**
Without starting `application changes example` importing below xml is successful even I have not provided `-n` to parse strictly. As it doesnt satisfy WHEN condition and I am expecting some error.

**1.xml**
```
<ac xmlns="a">
    <al>ri</al>
    <baugac xmlns="b">
        <bl>sri</bl>
    </baugac>
</ac>
```
After importing I have tried to export and below is output.
```
<ac xmlns="a">
  <al>ri</al>
</ac>
```
Which looks valid but node is autodeleted without any information to user.

**PART 2 With application changes example running**
Run application changes example to listen for both modules.
```
sysrepo/build/examples/application_changes_example a b &
```
Now importing same xml gives `Internal error` in callback as below.

```
$ sysrepocfg --import=1.xml -f xml -v3
[INF]: [139895063422720] [/opt/samba/skandukuri/sriram/new/sysrepo/src/sysrepo.c 195] Scheduled changes not applied because of other existing connections.
[INF]: [139895063422720] [/opt/samba/skandukuri/sriram/new/sysrepo/src/sysrepo.c 549] Session 3 (user "skandukuri") created.
[INF]: [139895063422720] [/opt/samba/skandukuri/sriram/new/sysrepo/src/shm_sub.c 301] Published event "change" with ID 1 priority 0 for 1 subscribers.
[INF]: [140262272239360] [/opt/samba/skandukuri/sriram/new/sysrepo/src/shm_sub.c 1937] Processing "a" "change" event with ID 1 priority 0 (remaining 1 subscribers).


 ========== EVENT change CHANGES: ====================================

CREATED: /a:ac (container)
CREATED: /a:ac/al = ri
DELETED: /a:ac/b:baugac/bl = sri

 ========== END OF CHANGES =======================================

 ========== CONFIG HAS CHANGED, CURRENT RUNNING CONFIG: ==========

[ERR]: Internal error (/opt/samba/skandukuri/sriram/new/sysrepo/src/edit_diff.c:2574).
[INF]: [140262272239360] [/opt/samba/skandukuri/sriram/new/sysrepo/src/shm_sub.c 1833] Finished processing "change" event (callback fail) with ID 1 priority 0 (remaining 1 subscribers).
[ERR]: Validation failed
[WRN]: [139895063422720] [/opt/samba/skandukuri/sriram/new/sysrepo/src/shm_sub.c 832] Event "change" with ID 1 priority 0 failed (Validation failed).
sysrepocfg error: Replace config failed (User callback failed)
```

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
there was a minor problem with diff and auto-deleted nodes, it should work properly now. As for `sysrepocfg` auto-deleting nodes instead of reporting errors, consider it a feature. Generally, this is a much more complex problem that we originally thought and hence *libyang* is not able to properly handle all the cases (specifically, distinguish correctly situations when auto-delete should happen and when not) and will never be. It will be fixed in the new *libyang* and then eventually even in *sysrepocfg*. But *sysrepo* itself should work correctly meaning if you set these changes using `sr_set_item()` and then apply then, a validation error is generated.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Thank you its working
