### ISSUE TITLE
How to get the correct XPath from the state data(config false leaf) in the callback function

### ISSUE THREAD

**Issue by xxyy0906** [sysrepo/sysrepo#1825]
Hi:
    Description:
    
    1.
    oper_data_example examples /examples:*

    2.
    netopper-cli ---->get

    3.
    printf request_xpath = /*

    4. 
    *parent = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(session)), 
    "/examples:stats/counter", "852", 0, 0);
     lyd_new_path(*parent, NULL, "/examples:stats/counter2", "1052", 0, 0);

    5.
    I need to 
    dp_get_items_cb(sr_session_ctx_t *session, const char *module_name, const char *xpath, const char *request_xpath,uint32_t request_id, struct lyd_node **parent, void *private_data)
    get xpath used for replace “/examples:stats/counter”and“/examples:stats/counter2”
    How to operate？

 Versions
 version v1.4.2 (SO v5.0.2)

Thanks!

**Comment by xxyy0906** [comment]
Hi:
Can I only fill in fixed XPath without proper API?
Thanks!

**Comment by michalvasko** [comment]
Hi,
I am sorry but even though I tried, I have not understood at all what it is that you are asking. Please, try again and do not worry about formatting (even though it is [not that hard](https://guides.github.com/features/mastering-markdown/)), I can see the actual text and will format it easily for you.

Regards,
Michal

**Comment by xxyy0906** [comment]
Hi,
I want to get the xpath string format given by the dp_get_items_cb function using the API. What should I do？

**Comment by michalvasko** [comment]
Hi,
I am still not sure whether I am missing something but try looking at `xpath` instead of `request_xpath`, you will see there the exact XPath that was used when subscribing with `sr_oper_get_items_subscribe()`.

Regards,
Michal

**Comment by xxyy0906** [comment]
Hi,
If I use / module: * in the subscription function, then I can't get the exact xpath in the callback function，In fact, what I want is the exact XPath returned by the recursion in sr_dp_get_items_subscribe in sysrepo v0.7. Has this version been cancelled

**Comment by michalvasko** [comment]
Hi,
okay, I finally understand. The operational data subscriptions work completely differently in the new *sysrepo* and you need to forget about the old one. There is no recursion (for a single subscription, anyway), you are always supposed to directly return **all the children** of the parent you subscribed to. You need to learn the details yourself, from the [docs](https://netopeer.liberouter.org/doc/sysrepo/master/subs.html#oper_subs) or [examples](https://github.com/sysrepo/sysrepo/blob/master/examples/oper_data_example.c). But for great majority of use-cases, you should be fine with simply using `lyd_new_path()` to create all the nodes.

As for *sysrepo* 0.7.x, it was not cancelled (I wish it was possible) but simply became obsolete and hence is not really supported anymore. But you can still find it in `legacy` branches.

Regards,
Michal

**Comment by xxyy0906** [comment]
ok, thank you very much!
