### ISSUE TITLE
[new sysrepo] Errors on sr_oper_get_items_subscribe and sr_rpc_subscribe

### ISSUE THREAD

**Issue by gitter-runner** [sysrepo/sysrepo#1827]
Hello,
I have multiple applications handling different lists. Some of them register callbacks for operational data and action of list instances. Sometimes I experience crash and timeout issues in _sr_oper_get_items_subscribe()_ and _sr_rpc_subscribe()_ functions when trying to register these callbacks.

To be able to reproduce it easily I created a simple stress test application. The test creates instances in a list and registers oper data and action callbacks for them. Each test process uses a dedicated but very similar yang models.

When I run a single test process it runs without errors but when two or more instances are running concurrently they fail in a short time, for example:

```
$ ./test 1 &
[1] 30415
Application will test list at "/test1:c1/l1".
Waiting for SIGUSR1

$ ./test 2 &
[2] 30423
$ Application will test list at "/test2:c2/l2".
Waiting for SIGUSR1

$ killall -USR1 test

 ========== CREATING LIST INSTANCES ==========
 ========== CREATING LIST INSTANCES ==========

$ *** Segmentation fault
```

Backtrace:
```
/lib/libsysrepo.so.5(+0x1c11c)[0x7fdde555311c]
/lib/libsysrepo.so.5(+0x3f351)[0x7fdde5576351]
/lib/libsysrepo.so.5(sr_oper_get_items_subscribe+0x2b6)[0x7fdde55492d3]
./test(+0x11df)[0x56258955f1df]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7fdde5167b97]
./test(+0xc6a)[0x56258955ec6a]

[1]-  Segmentation fault      ./test 1

$ [ERR]: Locking a mutex failed (_sr_rpc_subscribe: Connection timed out).
sr_oper_get_items_subscribe failed, rc=13

[2]+  Aborted                 ./test 2
```

[test.zip](https://github.com/sysrepo/sysrepo/files/4225297/test.zip)

sysrepo version: 1.4.9
libyang version: 1.0.132
test environment: Ubuntu 18.04.4 (x86_64)

Thanks!

**Comment by michalvasko** [comment]
Hi,
yeah, I was mostly focused on having several threads in a *sysrepo* app than on several *sysrepo* processes so there was wrong lock order that lead to invalid shared memory access. It took me a while because I have revised all the locks and added a multi-process test, but it should work now.

Regards,
Michal
