### ISSUE TITLE
Failed to get item using sr_get_item function

### ISSUE THREAD

**Issue by Roky7250** [sysrepo/sysrepo#1828]
Hi, I am using sysrepo version 1.4.2.

I am subscribed to leaf:
```
	rc = sr_module_change_subscribe(session, "ietf-interfaces", "/ietf-interfaces:interfaces/interface/ieee802-ethernet-interface:ethernet/speed", test_cb, NULL, 0,
			SR_SUBSCR_DEFAULT, &subscription);
```

Inside **test_cb** I am iterating true changes:

```
    while(SR_ERR_OK == sr_get_change_next(session, iter, &op, &old_value, &new_value))
    {
         if(op == SR_OP_CREATED)
          {
        		if (SR_ERR_OK != sr_get_item(session, "/ietf-interfaces:interfaces/interface[name='CE1']/ieee802-ethernet-interface:ethernet/duplex", 0, &tmp))
        		{
        			printf(" Failed to get item!");
        		}
          }
    }
```

My startup and running configuration is:

```
<config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interface>
    <name>CE1</name>
    <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
    <enabled>true</enabled>
    <ethernet xmlns="urn:ieee:std:802.3:yang:ieee802-ethernet-interface">
      <auto-negotiation>
        <enable>true</enable>
      </auto-negotiation>
    </ethernet>
  </interface>
</interfaces>
</config>
```
Configuration does not contain leafs duplex and speed. 
I am sending edit-config request with leafs speed and duplex added:

```
<config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interface>
    <name>CE1</name>
    <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
    <enabled>true</enabled>
    <ethernet xmlns="urn:ieee:std:802.3:yang:ieee802-ethernet-interface">
      <auto-negotiation>
        <enable>true</enable>
      </auto-negotiation>
      <duplex>full</duplex>
      <speed>1.000</speed>
    </ethernet>
  </interface>
</interfaces>
</config>
```
Now inside this callback who is going to be triggered for speed I wan to get leaf duplex.
But function does not return SR_ERR_OK. I am failing to get leaf duplex.
I am getting this message:

`[ERR]: No data found for "/ietf-interfaces:interfaces/interface[name='CE1']/ie                                                                                             ee802-ethernet-interface:ethernet/duplex".`

I was able to do this on sysrepo version 0.7.7.

Can you tell me what can be a problem?

Best regards

**Comment by michalvasko** [comment]
Hi,
this was actually a feature but I suppose it makes sense to change it so that want you wanted works just fine. The problem was that you said you are interested only in the changes of `speed` so no other changes were given to your callback and when you retrieved some data, only the requested changes could be applied. But like I said, I have changed it.

Regards,
Michal

**Comment by Roky7250** [comment]
Hi, I just want to get duplex value, because i need duplex value inside callback for speed to be able to set the speed.

So is this feature enabled now?
Now I can get duplex value inside callback for speed?

Best regards

**Comment by michalvasko** [comment]
Hi,
it will be merged into `master` on the next release, not sure when that will be, sorry. From several weeks to a few months.

Regards,
Michal
