### ISSUE TITLE
Unable to retrieve all the leaf node data which are requested in get xml

### ISSUE THREAD

**Issue by navya46** [sysrepo/sysrepo#1829]
Hi
Description
We're unable to get all the leaf node's data from a list, if more than one leaf node(key) is specified in get xml.
We have tried the following ways  to retrieve operational data of ietf-interfaces
Executed oper_data_example.c example and tried to retrieve interface data in the below formats
case 1:
By specifying only container name ,We were able to retrieve both the interface related information
[get_xml_and_rpc_output_based_on_container_name.txt](https://github.com/sysrepo/sysrepo/files/4234357/get_xml_and_rpc_output_based_on_container_name.txt)

Case 2:

By specifying only one leaf name in a container,able to retrieve the information related to the interface specified in the get xml.
[get_xml_and_rpc_output_with_one_interface_name_inside_container.txt](https://github.com/sysrepo/sysrepo/files/4234358/get_xml_and_rpc_output_with_one_interface_name_inside_container.txt)

Case 3:
Unable to retrieve respective interface related information when i tried to execute get request which includes two interfaces names.
[get_xml_and_rpc_output_with_two_interfaces.txt](https://github.com/sysrepo/sysrepo/files/4234368/get_xml_and_rpc_output_with_two_interfaces.txt)

NOTE: Case1 and case2 are working as expected,we have a issue with Case3.
Is there any other way to retrieve multiple leaf node's data as specified in a container

Thanks,
Navya.

**Comment by michalvasko** [comment]
Hi Navya,
`oper_data_example` in current *sysrepo* version is not using `ietf-interfaces`, what version are you using?

Regards,
Michal

**Comment by Sneha-star** [comment]
How to fetch/iterate through all the data using sysrepo API when we have a multilevel list and more than one list are present in each level?

sr_get_subtree returns only one list.
Is there any api through which the fetched data can be dumped?

**Comment by michalvasko** [comment]
Hi,
if you want to get all list instances, you can always use `sr_get_data`, which is the most versatile function. Also, these functions return *libyang* data tree, so you must use its API to work with these data. To dump, for example, you can use `lyd_print_file()`. Just get familiar with *libyang* API, there are lots of functions for data trees.

Regards,
Michal

**Comment by Sneha-star** [comment]
What would be the equivalent API in case of  python?

I am looking for something like below in case of python..

=====================================================
   ret = sr_get_data(sess, "/defaults:*", 0, 0, 0, &data);
    assert_int_equal(ret, SR_ERR_OK);

    assert_string_equal(data->schema->name, "l1");
    ret = lyd_print_mem(&str1, data, LYD_XML, LYP_WITHSIBLINGS | LYP_WD_IMPL_TAG);
==================================================

**Comment by michalvasko** [comment]
Maybe @lpaulic can help?

**Comment by Sneha-star** [comment]
If you are comfortable with cpp, then would appreciate if you could point me to some examples..where the multilevel list hierarchy are fetched and parsed (both config data and state data)

For example:
container abc
      list list1
            leaf a(key)
             leaf b
              list 2
                  leaf c(key)
                  leaf d

**Comment by Sneha-star** [comment]
@lpaulic - I would appreciate if you could give some pointer incase of python .

**Comment by michalvasko** [comment]
Hi,
as for C++, i can refer [this example](https://github.com/CESNET/libyang/blob/master/swig/cpp/examples/process_tree.cpp). But to get the full idea of what you can do, you must go through the [API](https://github.com/CESNET/libyang/blob/master/swig/cpp/src/Tree_Data.hpp).

Also, Python should actually be very similar, the APi is directly generated from C++. I was mistaken in my initial reply because you were asking only about *libyang* API, not *sysrepo*. So, there is not "item count", you have retrieved a data tree so you must treat it as one. It has a root (or several ones), each with its own children and so on, recursively.

Regards,
Michal

**Comment by Sneha-star** [comment]
Thank you.

**Comment by Sneha-star** [comment]
Hi Michal,

Where I can get the python equivalent api  for  "lyd_print_mem" ?

**Comment by michalvasko** [comment]
HI,
you must look into the Python module file, obviously. The whole API is in there. After compilation, you can find it in `build/swig/python/yang.py`.

Regards,
Michal

**Comment by Sneha-star** [comment]
Hi Michal,

How can I contact to @lpaulic  ?

**Comment by Sneha-star** [comment]
"lyd_print_mem" is a libyang cpp function.
I was looking for something like that in Python

**Comment by michalvasko** [comment]
Hi,
actually, there is no need to contact anyone else. I mistakenly thought you are asking about *sysrepo* Python API but this is a *libyang* API question and I have already answered you.

You will find everything in the mentioned Python module file. `lyd_print_mem` is not C++ function, but a C function. C++ function (method) is `Data_Node::print_mem()`. In Python it is the same because it is auto-generated from C++, just open `yang.py` and search for `print_mem`.

Regards,
Michal

**Comment by Sneha-star** [comment]
Hi Michal,

Thank you.
Using this I was able to proceed.

One more query do finding "session.get_subtree", works fine (returns all the desccendants node as per the xpath) but while using "libyang::S_Data_Node get_data" with max_depth "0", it does not give all the data.  Same thing works fine in case of C.

#subtreeData= session.get_subtree(<xpath1>) ==> works fine
getData = session.get_data(<xapath1>) ==> Does not return all the descendants data
                                                               ==> session pointing to running db in both cases

Am i missing something?

**Comment by michalvasko** [comment]
Hi,
so you are saying `get_data()` works fine in C but not in Python? In that case, again, @lpaulic may help because I am responsible only for C and C++ API.

Regards,
Michal

**Comment by lpaulic** [comment]
Hi @Sneha-star,

How exactly are you calling the `get_data()` function. Have you tried sending values the max_depth argument and the timeout argument.

Regards,
Luka
