### ISSUE TITLE
It seems that we do not support 'leafref' in module now?

### ISSUE THREAD

**Issue by fanchanghu** [sysrepo/sysrepo#183]
**My module like this:**
module mytest2{
  namespace "http://www.mytest2.com/";
  prefix "mytest2";

  container a{
    leaf x{
      type string;
    }
    leaf y{
      type leafref{
	    path "/a/x";
	  }
    }
  }
}

**Comment by rastislavszabo** [comment]
Hi,

not yet, but we are already working on it. Currently there are some issues in libyang that need to be resolved before we enable support for leafrefs, see: CESNET/libyang#78

**Comment by rastislavszabo** [comment]
fix merged to master branch
