### ISSUE TITLE
no expected operational data callback

### ISSUE THREAD

**Issue by anaire** [sysrepo/sysrepo#1830]
# yanglint --version
yanglint SO 1.6.9

# sysrepoctl --version
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.9 (SO v5.0.9)

The operational data callback function is not being called by sysrepo, though properly registered for the state leaf. For the isolation of a problem we are not using our application in the test, but the oper_data_example.c, as is from the sysrepo.

The YANG we are using in the test:
```
module our-test-module {

  namespace "urn:ietf:params:xml:ns:yang:100";

  prefix "our-test";

  organization
    "CoffeeShop";

  contact
    "For technical support, please contact your service channel";

  description
    "Definitions for our test configuration.";

  revision "2020-02-21" {
    description
      "Integrating to our test models.";
  }

  container test_objects {
    container config-our-test {
      list our-test {
        key "t-name";

        description
          "Test configuration.";

        leaf t-name {
          type string;
          description "Test name";
        }

        leaf t-state {
          config false;
          type boolean;
        }

      } // our-test list
  
    } // config-our-test

  } // test_objects

}
```
The YANG module contains the list "our-test". The list items consist of both configuration data
("t-name") and state data ("t-state"). Prior to operational subscription we ensure that the list is not empty by configuring some "t-names". Then we do the operational subscription to the state leaf
"t-state". After further requesting the state data for the "t-state" via netopeer2-cli, the do not observe the expected callback call, registered by oper_data_example.c.

Test steps:
1. Register YANG
```
sysrepoctl -v2 -i our-test.yang
```
2. Import the configuration
```xml
<test_objects xmlns="urn:ietf:params:xml:ns:yang:100">
  <config-our-test>
    <our-test>
      <t-name>test0</t-name>
    </our-test>
    <our-test>
      <t-name>test1</t-name>
    </our-test>
    <our-test>
      <t-name>test2</t-name>
    </our-test>
  </config-our-test>
</test_objects>
```
```
sysrepocfg --import=./test.xml -f xml -m our-test-module
```
3. Register for operational data
```
oper_data_example our-test-module /our-test-module:test_objects/config-our-test/our-test/t-state
```
4. Request the operational data
```
> get --filter-xpath /our-test-module:test_objects/config-our-test/our-test/t-state
DATA

>
```
The operational data callback was not called in this case.
Please elaborate, I am not able to find the reason of such behavior by reading the docs.

**Comment by michalvasko** [comment]
Hi,
it took me a while to understand the problem further proving it is quite complicated but it actually is [documented](https://netopeer.liberouter.org/doc/sysrepo/master/subs.html#oper_subs), the very first bullet. The parent must exists in the **operational**, it your case it exists only in the running. To make it exist in the operational, you can, for example, run
```
application_changes_example our-test-module
```
Also, I have somewhat improved the docs so that it is clear.

Regards,
Michal
