### ISSUE TITLE
There is a bug in sysrepo

### ISSUE THREAD

**Issue by MickAbson** [sysrepo/sysrepo#1831]
Details are as follows：

First, I swear all the 'sysrepo '' Yang ''netconf''netopeer2''... 'have been installed correctly.
Then I started 'netopeer-server' and 'netopeer-cli'. I performed the 'listen' operation on the client side and successfully established a connection.
Next I start the example of 'sysrepo', cpp_rpc_example:
`srbn@ubtVM:~/sysrepo-master/build/bindings/cpp/examples$ sudo ./cpp_rpc_example Application will make an rpc call in test-examples

 ========== SUBSCRIBE TO RPC CALL ==========

 ========== START RPC CALL ==========

 ========== RPC CALLED ==========

/test-examples:activate-software-image/image-name = acmefw-2.3
/test-examples:activate-software-image/location = /root/

 ========== PRINT RETURN VALUE ==========

/test-examples:activate-software-image/status = The image acmefw-2.3 is being installed.
/test-examples:activate-software-image/version = 2.3
/test-examples:activate-software-image/location = /root/
/test-examples:activate-software-image/init-log (container)

 ========== SUBSCRIBE TO RPC TREE CALL ==========

 ========== START RPC TREE CALL ==========

 ========== RPC CALLED ==========

/test-examples:activate-software-image/image-name = acmefw-2.3
/test-examples:activate-software-image/location = /root/

 ========== RPC TREE CALLED ==========

<activate-software-image xmlns="example:test-examples">
  <image-name>acmefw-2.3</image-name>
  <location>/root/</location>
</activate-software-image>

 ========== PRINT RETURN VALUE ==========

<activate-software-image xmlns="example:test-examples">
  <status>The image acmefw-2.3 is being installed.</status>
  <version>2.3</version>
  <location>/root/</location>
</activate-software-image>

 ========== END PROGRAM ==========

`
You can see that "cpp_rpc_example" works fine, and it works fine when I run it over and over again.

Now, the point is, when I run "cpp_rpc_example" after" netopeer-cli "has subscribed to all the notifications, the connection timeout occurs when I run" cpp_rpc_example" multiple times. The operation is as follows:
`> subscribe --filter-xpath /*
OK
> 
`

`srbn@ubtVM:~/sysrepo-master/build/bindings/cpp/examples$ sudo ./cpp_rpc_example Application will make an rpc call in test-examples

 ========== SUBSCRIBE TO RPC CALL ==========

^[[ASegmentation fault

srbn@ubtVM:~/sysrepo-master/build/bindings/cpp/examples$ sudo ./cpp_rpc_example Application will make an rpc call in test-examples
Timeout expired
`
Conclusion: after the "netopeer-cli" "subscribe" action, the application starts repeatedly, causing the sysrepo connection to time out

Hope to solve。

**Comment by MickAbson** [comment]
@mwalle 
Test platform: 18.04.1-Ubuntu x86_64
Sysrepo version: libsysrepo v1.3.21 (SO v4.1.8)
Netopeer version: netopeer2 1.1.1
Libyang version: 1.5.5

**Comment by michalvasko** [comment]
Hi,
I have tried it with the latest `devel` (1.4.12) and it worked fine. So, please update your *sysrepo*, I think the latest release 1.4.2 should also work.

Regards,
Michal
