### ISSUE TITLE
can't to generate starup file

### ISSUE THREAD

**Issue by xxyy0906** [sysrepo/sysrepo#1832]
hi,
description:
sysrecoctl shows that the import was successful, but it was not.can not to generate starup file
[test.zip](https://github.com/sysrepo/sysrepo/files/4244318/test.zip)
1.sysrepoctl -i acc-devm.yang -v3
[INF]: Applying scheduled changes.
[INF]: No scheduled changes.
[INF]: Module "acc-devm" scheduled for installation.

2 sysrepoctl -l

Module Name                | Revision   | Flags | Owner       | Permissions | Submodules | Features                                                               
------------------------------------------------------------------------------------------------------------------------------------------------------------------
acc-devm                   |            |  N    |             |             |            |                                                                        
iana-crypt-hash            | 2014-08-06 | i     |             |             |            |                                                                        
ietf-crypto-types          | 2019-07-02 | I     | root:root   | 600         |            |                                                                        
ietf-datastores            | 2017-08-17 | I     | root:root   | 666         |            |                                                                        
ietf-inet-types            | 2013-07-15 | i     |             |             |            |                                                                        
ietf-keystore              | 2019-07-02 | I     | root:root   | 600         |            | keystore-supported                                                     
ietf-netconf               | 2013-09-29 | I     | linux:linux | 666         |            | writable-running candidate rollback-on-error validate startup url xpath
ietf-netconf-acm           | 2018-02-14 | I     | root:root   | 600         |            |                                                                        
ietf-netconf-monitoring    | 2010-10-04 | I     | linux:linux | 600         |            |                                                                        
ietf-netconf-nmda          | 2019-01-07 | I     | root:root   | 600         |            | origin with-defaults                                                   
ietf-netconf-notifications | 2012-02-06 | I     | linux:linux | 666         |            |                                                                        
ietf-netconf-server        | 2019-07-02 | I     | root:root   | 600         |            | ssh-listen tls-listen ssh-call-home tls-call-home                      
ietf-netconf-with-defaults | 2011-06-01 | I     | linux:linux | 666         |            |                                                                        
ietf-origin                | 2018-02-14 | I     | linux:linux | 666         |            |                                                                        
ietf-ssh-common            | 2019-07-02 | i     |             |             |            |                                                                        
ietf-ssh-server            | 2019-07-02 | I     | root:root   | 600         |            | local-client-auth-supported                                            
ietf-tcp-client            | 2019-07-02 | i     |             |             |            |                                                                        
ietf-tcp-common            | 2019-07-02 | I     | root:root   | 600         |            | keepalives-supported                                                   
ietf-tcp-server            | 2019-07-02 | i     |             |             |            |                                                                        
ietf-tls-common            | 2019-07-02 | i     |             |             |            |                                                                        
ietf-tls-server            | 2019-07-02 | I     | root:root   | 600         |            | local-client-auth-supported                                            
ietf-truststore            | 2019-07-02 | I     | root:root   | 600         |            | truststore-supported x509-certificates                                 
ietf-x509-cert-to-name     | 2014-12-10 | I     | root:root   | 600         |            |                                                                        
ietf-yang-library          | 2019-01-04 | I     | linux:linux | 666         |            |                                                                        
ietf-yang-metadata         | 2016-08-05 | i     |             |             |            |                                                                        
ietf-yang-types            | 2013-07-15 | i     |             |             |            |                                                                        
nc-notifications           | 2008-07-14 | I     | linux:linux | 600         |            |                                                                        
notifications              | 2008-07-14 | I     | linux:linux | 600         |            |             

                                                           
yang                       | 2017-02-20 | I     | linux:linux | 666         |            |   

3.cd /etc/sysrepo/data
   can not find acc-devm .startup

what is the cause of this，thank！

**Comment by michalvasko** [comment]
Hi,
you see the `N` flag in the output. it means it was not installed. If you run `sysrepoctl -l -v3`, for example, you will also learn the reason.

Regards,
Michal

**Comment by xxyy0906** [comment]
The error I know is that I can't find the startup of the module after restart. You can try it. Yang file is in test.zip, or you can tell me where to view the log.thank you very much indeed！

**Comment by michalvasko** [comment]
Hi,
fine, I have tried it myself even though I have told you precisely what you need to do. So, this is how your output of `sysrepoctl -l -v3` would look like:
```
[INF]: Applying scheduled changes.
[INF]: No scheduled changes.
[INF]: Module "acc-devm" scheduled for installation.
[INF]: File "acc-yang-types@2019-02-13.yang" was installed.
[INF]: Applying scheduled changes.
[WRN]: Missing required element "name" in "me". (path: /acc-devm:me)
[WRN]: Failed to apply some changes, leaving all changes scheduled.
```
followed by the installed modules that you have seen. You now see that you are trying to install a module that has mandatory top-level nodes meaning its data cannot be empty, they are invalid. For this reason *sysrepo* does not allow you to install it this way. However, you can additionally provide some startup data to make this module valid and so it can be installed. This feature is available in `sysrepocfg` using the command `--new-data`. That is all I will tell you. It is obvious you are new to all this but you must learn to figure things on your own.

Regards,
Michal

**Comment by xxyy0906** [comment]
Thank you very much for your guidance. In fact, I have thought that using sysrecocfg tool is import, but my code is not updated, and there is no --new-data function. This is my question. Thank you again for your guidance! Best wishes to you!

**Comment by xxyy0906** [comment]
Hi,
I'm very sorry to continue to disturb you, but I seem to have encountered an unsolvable problem.
Based on the above operations, I imported XML using sysrecocfg,
log:
sr_lydmods_sched_update_data: Assertion `!(*ly_errno_glob_address())' failed.
[ERR]: Locking a mutex failed (sr_conn_lydmods_ctx_update: Connection timed out).
sysrepoctl error: Failed to connect (Timeout expired),

So I need your help. Is it my operation problem?
Here are my steps:
1.I added the following definitions in acc-devm.yang because I'm not sure if there's an error in my Yang file for identityref because I can't import them when I use them.
identity test{
        base acc-type:layer-protocol-name;
        description "";
    }
2.sudo sysrepocfg -W acc-devm-startup.xml -m acc-devm -f xml -v3
acc-devm-startup.xml:
me xmlns="urn:ccsa:yang:acc-devm">
    <name>test_name</name>
	<ip-address>192.168.1.1</ip-address>
	<mask>255.255.255.0</mask>
	<ntp-enable>false</ntp-enable>
	<gate-way1>192.168.0.1</gate-way1>
</me>
<ptps xmlns="urn:ccsa:yang:acc-devm">
	<ptp>
		<name>test_name_ptps</name>
		<state-pac>
			<admin-state>disabled</admin-state>
		</state-pac>
		<layer-protocol-name>test</layer-protocol-name>
		
		<interface-type>UNI</interface-type>
		<optical-power-pac>
			<output-power>2</output-power>
		</optical-power-pac>
	</ptp>
</ptps>
<eqs xmlns="urn:ccsa:yang:acc-devm">
	<eq>
		<name>test_name_eqs</name>
	</eq>
</eqs>
3.The above errors will occur.
I am really a novice, but I have to learn to grow up, hope to get your understanding!

Thanks

**Comment by michalvasko** [comment]
Hi,
I did not manage to reproduce your problem but I did notice one minor problem that I have fixed. So, please update *sysrepo*, run `make sr_clean`, install your module `acc-devm`, set up startup data, and then run `sysrepoctl -l -v3`, for example. If then the module is not successfully installed, please post the output with each of these steps performed.

Regards,
Michal

**Comment by xxyy0906** [comment]
Hi,
This modification solved my problem，Thanks!
