### ISSUE TITLE
Inconsistency with deviations

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1833]
Hi,

I am trying to validate a `leaf` with a pattern using deviations. 
If invalid string is given `sysrepocfg` works fine if no subscriber exist.
If any subscriber exist validation fails randomly without proper error message.

Expecting to fail in any scenario, please correct me if I am missing something.

steps
```
sysrepoctl -i a.yang
sysrepoctl -i adev.yang
sysrepocfg --import=a.xml -f xml -v3
```

Fails randomly with subscriber
```
~/data/sriram/new/sysrepo/build/examples/application_changes_example a &
sysrepocfg --import=a.xml -f xml -v4
```
**adev.yang**
```
module adev {
    namespace adev;
    prefix adev;
    import a{prefix a;}

    deviation /a:ac/a:al/a:all {
        deviate replace {
            type string {
                pattern '[a-zA-Z0-9_]+';
            }
        }
    }
}
```
**a.xml**
```
<ac xmlns="a">
    <al>
        <all>sriram-adf</all>
    </al>
    <al>
        <all>sriram-afdf</all>
    </al>
</ac>

```
**a.yang**
```
module a {
    prefix a;
    namespace a;

    container ac{
        list al {
            key all;
            leaf all{
                type string;
            }
        }
    }
}
```

**Comment by michalvasko** [comment]
Hi,
okay, now you should get an error already in `sysrepocfg`. *libyang* behavior was adjusted and should now be similar to the new *libyang*. But there was not really any other way to check these value constraints.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Thank you its working.
