### ISSUE TITLE
sysrepod: command not found

### ISSUE THREAD

**Issue by Ramanpreet19** [sysrepo/sysrepo#1836]
Hello, 

I have installed sysrepo and libyang on ubuntu by using the following command line. 

mkdir build; cd ./build; cmake ..; make; sudo make install 

Both the libraries are installed successfully in /usr/local/lib/ folder. 

**Installed library versions:-** 
1. libyang.so.1.6.7
2. libsysrepo v1.4.2 (SO v5.0.2)

I am trying to run sysrepo daemon using by using command sysrepod and getting the error 
**sysrepod: command not found**

sysrepoctl is giving following output:- 
sysrepoctl  -l 
Sysrepo repository: /etc/sysrepo

Module Name                | Revision   | Flags | Owner     | Permissions | Submodules | Features
-------------------------------------------------------------------------------------------------
ietf-datastores            | 2017-08-17 | i     |           |             |            |         
ietf-inet-types            | 2013-07-15 | i     |           |             |            |         
ietf-netconf               | 2011-06-01 | I     | root:root | 666         |            |         
ietf-netconf-notifications | 2012-02-06 | I     | root:root | 666         |            |         
ietf-netconf-with-defaults | 2011-06-01 | I     | root:root | 666         |            |         
ietf-origin                | 2018-02-14 | I     | root:root | 666         |            |         
ietf-yang-library          | 2019-01-04 | I     | root:root | 666         |            |         
ietf-yang-metadata         | 2016-08-05 | i     |           |             |            |         
ietf-yang-types            | 2013-07-15 | i     |           |             |            |         
yang                       | 2017-02-20 | I     | root:root | 666         |            |         

Flags meaning: I - Installed/i - Imported; R - Replay support; N - New/X - Removed/U - Updated; F - Feature changes

Could you please help me with debug of this?

Thanks, 
Raman

**Comment by smalls12** [comment]
There is no sysrepod executable anymore.

sysrepo runs in library mode now and will launch everything it needs when a client starts.

**Comment by michalvasko** [comment]
Hi,
please read the [documentation](https://netopeer.liberouter.org/doc/sysrepo/master/), *sysrepo* has undergone a major update.

Regards,
Michal

**Comment by Ramanpreet19** [comment]
@smalls12 @michalvasko  Thanks a lot for your response. This has provided me clarification.
