### ISSUE TITLE
Sysrepo Error

### ISSUE THREAD

**Issue by ghost** [sysrepo/sysrepo#1842]
Hi,

I am getting the following error while subscribing for a oper table.
I would appreciate if someone can guide me.
Data provider subscription for "xxx-state" on "/xxx-state:x-state" already exists.

Can not we subscribe to the same(oper/state) model twice?

**Comment by michalvasko** [comment]
Hi,
no, you cannot subscribe more times to provide the same subtree. By subscribing you are saying that those data represent the state of your application and you will provide them, it does not make sense for more applications. How is *sysrepo* supposed to determine data from which subscriber to use? Still, data from subscriber would be overwritten meaning completely redundant.

Regards,
Michal

**Comment by Sneha-star** [comment]
Thank you for your quick response.
