### ISSUE TITLE
Question related to timeout inside callback

### ISSUE THREAD

**Issue by Roky7250** [sysrepo/sysrepo#1844]
Hi, I am using latest sysrepo from master branch.

I have a callback for leaf address inside my test module.
Inside callback for that leaf I have function that sets address value on system, but that function is slow, so this happens:

`[ERR]: Unable to finish processing event "change" with ID 1 priority 0 (timeout                                                                                              probably).`

Callback fails for SR_EV_CHANGE  event.

After that callback is triggered with SR_EV_ABORT event.

netopeer2-cli:

```
        type:     application
        tag:      operation-failed
        severity: error
        message:  Callback event "change" with ID 1 processing timed out.
```

My question is how can I increase time of callback execution, so my function can set address without timeout happening?

Do I need to change some kind of variable during netopeer2 installation?
Maybe server does not wait response of edit-config enough? 

I tried to change DATA_CHANGE_TIMEOUT from 0 do 10, but it did not helped.

Best regards

**Comment by michalvasko** [comment]
Hi,
you should first update *netopeer2* to the latest `devel` (1.1.15). Then try to increase the timeout and you should get an error that you also need to increase `RPC_TIMEOUT`. If you do both, it should work.

Regards,
Michal
