### ISSUE TITLE
Callback issue 

### ISSUE THREAD

**Issue by ghost** [sysrepo/sysrepo#1845]
Hi Michal,

I have two sysrepo sessions sessions pointing to the same sysrepo datastore.
yang-module-1 
yang-module-2(augmented from yang-module-1)
session1:

1) start session with ds SR_DS_CANDIDATE
2) edit config on "yang-module-2" related data.
3) commit -> sr_apply_changes->sr_copy_config
   3.1) sr_copy_config(sessionCtx , NULL, SR_DS_CANDIDATE, SR_DS_RUNNING, SR_COPY_CONFIG_TIMEOUT_MS);

session2: 

module subscribed with "yang-module-2" (with session ds : -SR_DS_RUNNING)

But session2  module callbacks (For yang-module-2) are not getting hit when commit is triggered.
Please let me know why so ?

**Comment by michalvasko** [comment]
Hi,
I would have to see the actual modules but be aware that if a module augments another one, its data belong to the augment target module. The top-level data defined in a module belong to that module, with any augments on them. Meaning you may have to subscribe for `yang-module-1` changes instead.

Regards,
Michal

**Comment by Sneha-star** [comment]
Thank you.
