### ISSUE TITLE
Unknown module problem

### ISSUE THREAD

**Issue by Roky7250** [sysrepo/sysrepo#1847]
Hi, I am using netopeer2 server and cli from devel branch.
I installed two modules: ieee802-dot1q-bridge.yang and ieee802-dot1ab-lldp.yang.
I have plugins for both modules.
sysrepo-plugind boot up fine, with both plugins successfully  initialized.
server boots up fine without any errors. 
Both of module are  successfully paressed (netopeer2-server INF-o messages).
When I send get-config  and get request for ieee802-dot1q-bridge module I get correct data.
When  I send get-config  and get request for  ieee802-dot1ab-lldp module i get this error:

```
ly ERROR: Module name "ieee802-dot1ab-lldp" refers to an unknown module.
cli_send_recv: Failed to send RPC.
```

Note: Both of modules are installed to sysrepo and when I do sysrepoctl --list, they are there.

Can you tell me what can be a problem?

Best regards

**Comment by Roky7250** [comment]
When I switch to master branch of netopeer2, ieee802-dot1ab-lldp module is installed, get and get-config are working for ieee802-dot1ab-lldp module.

Reason why I switched to devel branch is timeout that we discussed on issue: 
[#1844](https://github.com/sysrepo/sysrepo/issues/1844).

**Comment by michalvasko** [comment]
Hi,
can you please paste the output of `sysrepoctl -l`?

Regards,
Michal

**Comment by Roky7250** [comment]
Hi,
output is inside this file. 
[sysrepoctl_ouput.txt](https://github.com/sysrepo/sysrepo/files/4297760/sysrepoctl_ouput.txt)

Best regards

**Comment by Roky7250** [comment]
Hi, i did it like this:

`> get --filter-xpath /ieee802-dot1ab-lldp:*
ly ERROR: Module name "ieee802-dot1ab-lldp" refers to an unknown module.
cli_send_recv: Failed to send the RPC.
`

ieee802-dot1ab-lldp.yang module imports:

  /*** LINKAGE (IMPORTS / INCLUDES) ***/
  import ieee802-dot1ab-types       { prefix "lldp-types"; }
  import ietf-routing               { prefix "rt"; }
  import ietf-yang-types            { prefix "yang"; }
  import ietf-interfaces            { prefix "if"; }
  import ieee802-dot1q-bridge       { prefix "dot1q"; }
  import ieee802-types              { prefix "ieee"; }
  import iana-if-type               { prefix "ianaift"; }

Modules: 

[modules.zip](https://github.com/sysrepo/sysrepo/files/4297793/modules.zip)

Best regards

**Comment by michalvasko** [comment]
Hi,
my `sysrepoctl -l` output
```
Module Name                | Revision   | Flags | Owner       | Permissions | Submodules | Features                                                               
------------------------------------------------------------------------------------------------------------------------------------------------------------------
iana-crypt-hash            | 2014-08-06 | i     |             |             |            |                                                                        
iana-if-type               | 2017-01-19 | i     |             |             |            |                                                                        
ieee802-dot1ab-lldp        | 2018-11-11 | I     | vasko:users | 600         |            |                                                                        
ieee802-dot1ab-types       | 2018-10-02 | i     |             |             |            |                                                                        
ieee802-dot1q-bridge       | 2018-03-07 | I     | vasko:users | 600         |            |                                                                        
ieee802-dot1q-types        | 2018-03-07 | i     |             |             |            |                                                                        
ieee802-types              | 2018-03-07 | i     |             |             |            |                                                                        
ietf-crypto-types          | 2019-07-02 | I     | vasko:users | 600         |            |                                                                        
ietf-datastores            | 2017-08-17 | I     | vasko:users | 666         |            |                                                                        
ietf-inet-types            | 2013-07-15 | i     |             |             |            |                                                                        
ietf-interfaces            | 2018-02-20 | I     | vasko:users | 600         |            |                                                                        
ietf-keystore              | 2019-07-02 | I     | vasko:users | 600         |            | keystore-supported                                                     
ietf-netconf               | 2013-09-29 | I     | vasko:users | 666         |            | writable-running candidate rollback-on-error validate startup url xpath
ietf-netconf-acm           | 2018-02-14 | I     | vasko:users | 600         |            |                                                                        
ietf-netconf-monitoring    | 2010-10-04 | I     | vasko:users | 600         |            |                                                                        
ietf-netconf-nmda          | 2019-01-07 | I     | vasko:users | 600         |            | origin with-defaults                                                   
ietf-netconf-notifications | 2012-02-06 | I     | vasko:users | 666         |            |                                                                        
ietf-netconf-server        | 2019-07-02 | I     | vasko:users | 600         |            | ssh-listen tls-listen ssh-call-home tls-call-home                      
ietf-netconf-with-defaults | 2011-06-01 | I     | vasko:users | 666         |            |                                                                        
ietf-origin                | 2018-02-14 | I     | vasko:users | 666         |            |                                                                        
ietf-routing               | 2018-03-13 | i     |             |             |            |                                                                        
ietf-ssh-common            | 2019-07-02 | i     |             |             |            |                                                                        
ietf-ssh-server            | 2019-07-02 | I     | vasko:users | 600         |            | local-client-auth-supported                                            
ietf-tcp-client            | 2019-07-02 | i     |             |             |            |                                                                        
ietf-tcp-common            | 2019-07-02 | I     | vasko:users | 600         |            | keepalives-supported                                                   
ietf-tcp-server            | 2019-07-02 | i     |             |             |            |                                                                        
ietf-tls-common            | 2019-07-02 | i     |             |             |            |                                                                        
ietf-tls-server            | 2019-07-02 | I     | vasko:users | 600         |            | local-client-auth-supported                                            
ietf-truststore            | 2019-07-02 | I     | vasko:users | 600         |            | truststore-supported x509-certificates                                 
ietf-x509-cert-to-name     | 2014-12-10 | I     | vasko:users | 600         |            |                                                                        
ietf-yang-library          | 2019-01-04 | I     | vasko:users | 666         |            |                                                                        
ietf-yang-metadata         | 2016-08-05 | i     |             |             |            |                                                                        
ietf-yang-types            | 2013-07-15 | i     |             |             |            |                                                                        
nc-notifications           | 2008-07-14 | I     | vasko:users | 600         |            |                                                                        
notifications              | 2008-07-14 | I     | vasko:users | 600         |            |                                                                        
yang                       | 2017-02-20 | I     | vasko:users | 666         |            |
```

Having no data set, *netopeer2-cli* output
```
> get-config --source running --filter-xpath /ieee802-dot1q-bridge:*
DATA

> get-config --source running --filter-xpath /ieee802-dot1ab-lldp:*
DATA

> 
```

My first guess would be some library incompatibilities. So, please remove all installed libraries (*libyang*, *libnetconf2*, and *libsysrepo*) and recompile and install them from `devel`. Then also recompile *netopeer2* and try it again.

Regards,
Michal

**Comment by Roky7250** [comment]
Hi, I found the problem.

When I commented out  **yang-version 1.1;** inside yang module everything worked fine.
I had problem from above with every module that was installed and implemented.

Bet regards.

**Comment by michalvasko** [comment]
Hi,
okay, but I believe the cause is still what I mentioned before because this means that the client does not load any YANG 1.1 modules. If you are fine with that, okay, but before you raise any other issue I will expect you to have this working. It is a critical problem.

Regards,
Michal

**Comment by vladique00** [comment]
Hi, Michal.
I have the same problem.
I am using netopeer2-server/sysrepo/libnetconf2/libyang from devel branch. Attempts to **get**  did not give me operational data of my plugin.
When I came across this issue, I deleted the line 
> yang-version 1.1;

 from my model and will be able to successfully retrieve the data.

**Comment by vladique00** [comment]
Hi, Michal.
I have the same problem.
I am using netopeer2-server/sysrepo/libnetconf2/libyang from devel branch. Attempts to **get** did not give me operational data of my plugin.
When I came across this issue, I deleted the line

    yang-version 1.1;

from my model and will be able to successfully retrieve the data.

**Comment by michalvasko** [comment]
Hi,
okay, could you please look into it more? Such as, does
```
get-config --source running --filter-xpath /<your-module>:*
```
work? Also, please enable verbose logging (`verb verbose`) in *netopeer2-cli* before connecting and then connect. You should see information about every schema that is being parsed, so it would be best if you paste it here and also mention what model you are having problems with. Thanks.

Regards,
Michal

**Comment by vladique00** [comment]
[container.txt](https://github.com/sysrepo/sysrepo/files/4491408/container.txt)
[netopeer2-cli.txt](https://github.com/sysrepo/sysrepo/files/4491409/netopeer2-cli.txt)
[model.txt](https://github.com/sysrepo/sysrepo/files/4491424/model.txt)

**Comment by michalvasko** [comment]
Hi,
okay, I see that you are using an ancient *libssh* version 0.7.0, what are the versions of your *libnetconf2*, *netopeer2*, *sysrepo*, *libyang*?

Regards,
Michal

**Comment by vladique00** [comment]
Actual on April 15th.
![Снимок экрана от 2020-04-17 12-47-22](https://user-images.githubusercontent.com/19613864/79545249-d172a000-80a9-11ea-89f3-f9aae5191961.png)
Problem in libssh?

**Comment by michalvasko** [comment]
Okay, *libssh* version should not cause any problems as long as you can connect. Seeing as you are using the latest `devel` versions and the `<hello>` message looks okay, I do not understand why `yang-library` data are not retrieved. Because that is the reason why your YANG 1.1 modules are not loaded. Anyway, I have added new verbose messages into *libnetconf2*, which could provide more information. So, please pull it, try again, and post the output of *netopeer2-cli* again.

Regards,
Michal

**Comment by vladique00** [comment]
[netopeer2-cli.txt](https://github.com/sysrepo/sysrepo/files/4491924/netopeer2-cli.txt)

**Comment by vladique00** [comment]
I suppose the problem is that I missed updating my local netopeer2-cli. The incompatibility of netopeer2-cli with new versions of libraries is a bit unobvious.
Sorry for the time taken.
Best regards.

**Comment by michalvasko** [comment]
I am not sure what exactly you mean but I do not see the messages in your output so your CLI is definitely not using latest *libnetconf2* `devel`.

Regards,
Michal
