### ISSUE TITLE
questions about the use of identityref

### ISSUE THREAD

**Issue by xxyy0906** [sysrepo/sysrepo#1851]
Hi;
regarding the use of identity, I don't know how to give xml data. can you tell me how to do it, thank you!
1. sysrepoctl -i ietf-yang-types.yang -v3
   sysrepoctl -i acc-yang-types.yang -v3
   sysrepoctl -i ietf-inet-types.yang -v3
   sysrepoctl -i acc-devm.yang -v3

2.  sysrepoctl -l -v3
    [INF]: Applying scheduled changes.
    [WRN]: Missing required element "name" in "me". (path: /acc-devm:me)
    [WRN]: Failed to apply some changes, leaving all changes scheduled.

3. sysrepocfg -W acc-devm-startup.xml -m acc-devm -f xml
ERR]: Identity found, but in a non-implemented module "acc-yang-types".
[ERR]: Failed to resolve identityref "acc-yang-types:layer-protocol-name". (path: /acc-devm:ptps/ptp[name='test_name_ptps']/layer-protocol-name)
sysrepocfg error: Install module data failed (libyang error)

I want to know how the layer-protocol-name data can make yang file import successful through xml，thank you!
here is the attachment:
[test.zip](https://github.com/sysrepo/sysrepo/files/4305771/test.zip)

[acc-devm-startup.txt](https://github.com/sysrepo/sysrepo/files/4305795/acc-devm-startup.txt)

**Comment by michalvasko** [comment]
Hi,
please pull the latest *libyang* and *sysrepo*. There was a problem in *sysrepo*, which should be fixed. However, your startup data are not valid and I have improved *libyang* message so that you should understand why it is invalid.

Regards,
Michal

**Comment by xxyy0906** [comment]
Thank you  for your prompt reply, I will continue to operate after the update.

**Comment by xxyy0906** [comment]
Hi,
Sorry, I only updated sysrepo.c, but now make error,do you need to update other codes(only common.h)?
log:
/home/linux/sysrepo-1.4.2/src/sysrepo.c:4764:5: error: too few arguments to function ‘sr_shmmain_unlock’
     sr_shmmain_unlock(conn, SR_LOCK_WRITE, 1, __func__);
     ^
In file included from /home/linux/sysrepo-1.4.2/build/common.h:245:0,
                 from /home/linux/sysrepo-1.4.2/src/sysrepo.c:22:
/home/linux/sysrepo-1.4.2/src/shm.h:522:6: note: declared here
 void sr_shmmain_unlock(sr_conn_ctx_t *conn, sr_lock_mode_t mode, int remap, int lydmods, const char *func);
      ^
make[2]: *** [CMakeFiles/srobj.dir/src/sysrepo.c.o] Error 1
make[1]: *** [CMakeFiles/srobj.dir/all] Error 2
make: *** [all] Error 2

**Comment by michalvasko** [comment]
Hi,
if you want to use the fix, you need to switch to `devel`. Best is to download *libyang*, *sysrepo*, *libnetconf2*, and *netopeer2* from `devel`, compile, and reinstall. By picking files or even changes you will only end up with incompatible mess. I will not provide any support then.

Regards,
Michal

**Comment by xxyy0906** [comment]
Hi:
I'm very sorry, I updated the code that you said. Although this modification solves some problems, but my problem still exists, and I don't know what caused it. I hope you can help me a little.

 1. sysrepoctl -i acc-otn.yang

2. sudo sysrepoctl -l -v3
   [WRN]: Schema node "acc-yang-types:ODU" not found (acc-devm:layer-protocol-name = acc-yang-types:ODU) with context node "/acc-devm:ptps/ptp".
[WRN]: Schema node "acc-yang-types:ODU" not found (acc-devm:layer-protocol-name = acc-yang-types:ODU) with context node "/acc-devm:ctps/ctp".
[WRN]: Missing required element "name" in "me". (path: /acc-devm:me)
[WRN]: Failed to apply some changes, leaving all changes scheduled.

3. sudo sysrepocfg -W acc-devm-startup.xml -m acc-otn -f xml
    **sysrepocfg: /home/linux/cxt_netconf/sysrepo-devel/src/log.c:214: sr_errinfo_new_ly: Assertion `e' failed.**
this is xml:
<me xmlns="urn:ccsa:yang:acc-devm">

    <name>test_name</name>
	<ip-address>192.168.1.1</ip-address>
	<mask>255.255.255.0</mask>
	<ntp-enable>false</ntp-enable>
	<gate-way1>192.168.0.1</gate-way1>

</me>
<ptps xmlns="urn:ccsa:yang:acc-devm">

	<ptp>
		<name>test_name_ptps</name>
		<state-pac>
			<admin-state>disabled</admin-state>
		</state-pac>

		<layer-protocol-name xmlns:acc-otn="urn:ccsa:yang:acc-otn">acc-otn:ODU</layer-protocol-name>

		<interface-type>UNI</interface-type>	
		<optical-power-pac>
			<output-power>2</output-power>
		</optical-power-pac>
	</ptp>

</ptps>
<ctps xmlns="urn:ccsa:yang:acc-devm">

	<ctp>
		<name>test_name_ctp</name>
		<state-pac>
			<admin-state>disabled</admin-state>
		</state-pac>

		<layer-protocol-name xmlns:acc-otn="urn:ccsa:yang:acc-otn">acc-otn:ODU</layer-protocol-name>
	</ctp>

</ctps>
<eqs xmlns="urn:ccsa:yang:acc-devm">

	<eq>
		<name>test_name_eqs</name>
	</eq>

</eqs>

thanks!

**Comment by michalvasko** [comment]
Hi,
please update *sysrepo* and you should no longer get an assert, I would not be able to come up with these use-cases even if I wanted to. Anyway, if you have several modules that need some startup data, you must install them one-by-one. So this will not work and now properly print an error.

Regards,
Michal

**Comment by xxyy0906** [comment]
Hi:
I very much agree with the phrase " Anyway, if you have several modules that need some startup data, you must install them one-by-one",But even if I follow these steps, I still encounter some problems,However, I don't know if it is the problem of yang or the problem of xml.But I think it is a problem of when and agument in sysrepo.Can you perform the following steps?My ultimate goal is to import the yang file and it works.

there are 3 modules:
--test-types.yang
module test-types {
  namespace "http://www.example.net/test-types";
  prefix test-types;

  identity layer-protocol-name {
        description "";
    }
}
--test.yang
module test {
  namespace "http://www.example.net/test";
  prefix test;
  import test-types { 
		prefix "test-types"; 
	}
	container haha{
	 	leaf layer-protocol-name {
		        mandatory true;
		        type identityref {
		            base test-types:layer-protocol-name;
		        }
		        description "";
		    }
	}
}
--test-my.yang
module test-my {
  namespace "http://www.example.net/test-my";
  prefix test-my;

  import test-types { 
		prefix "test-types"; 
	}
  import test { 
		prefix "test"; 
	}

	identity desc {
        base test-types:layer-protocol-name;
        description "";
    }
	
	augment "/test:haha" {
        when "test:layer-protocol-name = test-types:desc";
        container desc-pac {
            leaf ts-detail {
                type string;
                description "none";
            }
        }
    }
}

1. I want to import test-my.yang,so execute sysrepoctl -i test-my.yang
  sysrepoctl -l -v3
  [INF]: Applying scheduled changes.
[WRN]: Schema node "test-types:desc" not found (test:layer-protocol-name = test-types:desc) with context node "/test:haha".
[WRN]: Missing required element "layer-protocol-name" in "test". (path: /)
[WRN]: Failed to apply some changes, leaving all changes scheduled.

2. Encountered the above problem, I think he needs to import test.yang first,so
    sysrepoctl -u test-my
    sysrepoctl -i test.yang
    sysrepoctl -l -v3
    [INF]: Applying scheduled changes.
    [WRN]: Missing required element "layer-protocol-name" in "haha". (path: /test:haha)
    [WRN]: Failed to apply some changes, leaving all changes scheduled.

3. I think test.yang needs startup data,so
    (1)sysrepocfg -W test.xml -m test -f xml
    [ERR]: Identityref value is not derived from all its bases. (path: /test:haha/layer-protocol-name)
    [ERR]: Failed to resolve identityref "test-types:layer-protocol-name". (path: /test:haha/layer-protocol-name)
sysrepocfg error: Install module data failed (libyang error)
   test.xml:
   `<haha xmlns="http://www.example.net/test">
	<layer-protocol-name xmlns:x="http://www.example.net/test-types">x:layer-protocol-name</layer-protocol-name>
</haha>`
   (2)sysrepocfg -W test.xml -m test -f xml
   [ERR]: Invalid value "x:desc" in "layer-protocol-name" element. (path: /test:haha/layer-protocol- 
   name)
   sysrepocfg error: Install module data failed (libyang error)
   test.xml:
   `<haha xmlns="http://www.example.net/test">
	<layer-protocol-name xmlns:x="http://www.example.net/test-my">x:desc</layer-protocol-name>
</haha>`
  I don't know how to fill in the startup data here.I think this should be caused by interdependence, but I don't know how to solve it,hope you can give me some help, very thanks!

**Comment by michalvasko** [comment]
Hi,
you have not updated *libyang* like I told you to so you did not get the nicer warning. These messages
```
sysrepocfg -W test.xml -m test -f xml
[ERR]: Identityref value is not derived from all its bases. (path: /test:haha/layer-protocol-name)
[ERR]: Failed to resolve identityref "test-types:layer-protocol-name". (path: /test:haha/layer-protocol-name)
sysrepocfg error: Install module data failed (libyang error)
```
tell you that `test-types:layer-protocol-name` is not derived from the base of the mandatory leaf `layer-protocol-name`, it is the base itself. That is not a [valid value](https://tools.ietf.org/html/rfc7950#section-9.10.2). You must have a derived identity first such as this
```yang
module test-types {
  namespace "http://www.example.net/test-types";
  prefix test-types;

  identity layer-protocol-name {
        description "";
    }
  identity protocol2 {
    base layer-protocol-name;
  }
}
```
and then you can use these data
```xml
<haha xmlns="http://www.example.net/test">
  <layer-protocol-name xmlns:x="http://www.example.net/test-types">x:protocol2</layer-protocol-name>
</haha>
```

**Comment by xxyy0906** [comment]
Hi Michal:
Thank you for your reply, I have the following 2 questions about this:
1.Do you think my identity definition in the test-types.yang is flawed?
2.I understand what you mean, but I want to use the desc data in test-my.yang in layer-protocol-name in test.yang. Is this possible?

thanks!

**Comment by michalvasko** [comment]
Hi,
sorry, I have missed that you have a derived identity in the other module. Again, a use-case I would not even dream about but fine, with some adjustments I succeeded to install all the modules. So, please pull latest `devel` and perform the following commands, it should install then.
```
sysrepoctl -v3 -a -i test-types.yang
sysrepoctl -v3 -i test.yang
sysrepoctl -v3 -i test-my.yang
sysrepocfg -W test.xml -f xml -m test -v3
sysrepoctl -v3 -l
```

Regards,
Michal

**Comment by xxyy0906** [comment]
Hi Michal:
I'm sure I have updated the latest code, but I still seem to have a problem,
**1.uninstall module:**
    sysrepoctl -u test-types
    sysrepoctl -u test
    sysrepoctl -u test-my
**2.install module:**
   sysrepoctl -v3 -a -i test-types.yang
   [INF]: Applying scheduled changes.
   [INF]: No scheduled changes.
   [INF]: Module "test-types" scheduled for installation.
   [INF]: Applying scheduled changes.
   [INF]: File "test-types.yang" was installed.
   [INF]: Module "test-types" was installed.
   [INF]: Scheduled changes applied.

   sysrepoctl -v3 -i test.yang
   [INF]: Applying scheduled changes.
   [INF]: No scheduled changes.
   [INF]: Module "test" scheduled for installation.

   sysrepoctl -v3 -i test-my.yang
   [INF]: Applying scheduled changes.
   [WRN]: Missing required element "layer-protocol-name" in "haha". (path: /test:haha)
   [WRN]: Failed to apply some changes, leaving all changes scheduled.
   [INF]: Module "test-my" scheduled for installation.

   sysrepocfg -W test.xml -f xml -m test -v3
   **[INF]: Applying scheduled changes.
   [WRN]: Schema node "test-types:desc" not found (test:layer-protocol-name = test-types:desc) with context node "/test:haha".
   [WRN]: Missing required element "layer-protocol-name" in "test". (path: /)
   [WRN]: Failed to apply some changes, leaving all changes scheduled.
   [INF]: Session 16 (user "root") created.
   [ERR]: Only data for the module "test" can be set.
   sysrepocfg error: Install module data failed (Operation not supported)**

**3.version**
   sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.23 (SO v5.1.8)
   sysrepocfg - sysrepo configuration manipulation tool, compiled with libsysrepo v1.4.23 (SO v5.1.8)
   netopeer2-server 1.1.15

  Is it because of the " [ERR]: Only data for the module "test" can be set."caused by the last install test-my.yang？

thanks!

**Comment by michalvasko** [comment]
Hi,
it was one last stupid mistake on my part, should work now. This test also included.

Regards,
Michal

**Comment by xxyy0906** [comment]
Hi Michal:
Thank you for your modification, it has solved my problem.test module can already install,But if there are 2 such use cases, it still seems a bit problematic.It directly caused my other module to fail to install.
Based on the test module(test.yang), I redefined a similar module.
--test-types1.yang
module test-types1 {
  namespace "http://www.example.net/test-types1";
  prefix test-types1;
  identity layer-protocol-name1 {
        description "";
    }
}
--test1.yang
module test1 {
  namespace "http://www.example.net/test1";
  prefix test1;
  import test-types1 { 
		prefix "test-types1"; 
	}
	container haha1{
	 	leaf layer-protocol-name1 {
		        mandatory true;
		        type identityref {
		            base test-types1:layer-protocol-name1;
		        }
		        description "";
		    }
	}
}
--test-my1.yang
module test-my1 {
  namespace "http://www.example.net/test-my1";
  prefix test-my1;

  import test-types1 { 
		prefix "test-types1"; 
	}
  import test1 { 
		prefix "test1"; 
	}

	identity desc1 {
        base test-types1:layer-protocol-name1;
        description "";
    }
	
	augment "/test1:haha1" {
        when "test1:layer-protocol-name1 = test-types1:desc1";
        container desc-pac1 {
            leaf ts-detail1 {
                type string;
                description "none";
            }
        }
    }
}
--test1.xml
`<haha1 xmlns="http://www.example.net/test1">
  <layer-protocol-name1 xmlns:x="http://www.example.net/test-my1">x:desc1</layer-protocol-name1>
</haha1>`

1. successfully install test module
    sysrepoctl -v3 -a -i test-types.yang
    sysrepoctl -v3 -i test.yang
    sysrepoctl -v3 -i test-my.yang
    sysrepocfg -W test.xml -f xml -m test -v3
    sysrepoctl -v3 -l
    [INF]: Applying scheduled changes.
    [INF]: Module "test" will be installed as "test-my" module dependency.
    [INF]: File "test-my.yang" was installed.
    [INF]: Module "test-my" was installed.
    [INF]: Dependency module "test" was installed.
    [INF]: Scheduled changes applied.
    
    netopeer2-server -d -v1
    [WRN]: LY: Schema node "test-types:desc" not found (test:layer-protocol-name = test-types:desc) with context node "/test:haha".

2. install test1 module (test-types1.yang + test1.yang +test-my1.yang)
   **sysrepoctl -v3 -a -i test-types1.yang**
   [INF]: Applying scheduled changes.
   [INF]: No scheduled changes.
   [INF]: Module "test-types1" scheduled for installation.
   [INF]: Applying scheduled changes.
   [INF]: File "test-types1.yang" was installed. 
   [INF]: Module "test-types1" was installed.
   [INF]: Scheduled changes applied.

  **sysrepoctl -v3 -i test1.yang**
  [INF]: Applying scheduled changes.
  [INF]: No scheduled changes.
  [INF]: Module "test1" scheduled for installation.

   **sysrepoctl -v3 -i test-my1.yang**
   [INF]: Applying scheduled changes.
   [WRN]: Schema node "test-types:desc" not found (test:layer-protocol-name = test-types:desc) with context node "/test:haha".
   [WRN]: Missing required element "layer-protocol-name1" in "haha1". (path: /test1:haha1)
   [WRN]: Failed to apply some changes, leaving all changes scheduled.
   [INF]: Module "test-my1" scheduled for installation.
   [INF]: File "test1.yang" was installed.

   **sudo sysrepocfg -W test1.xml -f xml -m test1 -v3**
   [INF]: Applying scheduled changes.
   [WRN]: Schema node "test-types:desc" not found (test:layer-protocol-name = test-types:desc) with context node "/test:haha".
   [WRN]: Schema node "test-types1:desc1" not found (test1:layer-protocol-name1 = test-types1:desc1) with context node "/test1:haha1".
   [WRN]: Missing required element "layer-protocol-name1" in "test1". (path: /)
   [WRN]: Failed to apply some changes, leaving all changes scheduled.
   [INF]: Session 9 (user "root") created.
   [WRN]: Schema node "test-types:desc" not found (test:layer-protocol-name = test-types:desc) with context node "/test:haha".
   [WRN]: Schema node "test-types1:desc1" not found (test1:layer-protocol-name1 = test-types1:desc1) with context node "/test1:haha1".
    **[ERR]: Missing required element "layer-protocol-name" in "test". (path: /)
sysrepocfg error: Install module data failed (libyang error)**

   **sysrepoctl -v3 -l**
   [INF]: Applying scheduled changes.
   [WRN]: Schema node "test-types:desc" not found (test:layer-protocol-name = test-types:desc) with context node "/test:haha".
   [WRN]: Schema node "test-types1:desc1" not found (test1:layer-protocol-name1 = test-types1:desc1) with context node "/test1:haha1".
   [WRN]: Missing required element "layer-protocol-name1" in "test1". (path: /)
   [WRN]: Failed to apply some changes, leaving all changes scheduled.
   
   Module                Flags
   test-my1               N
   test-types1            I                                                              
   test1                      N 

   **netopeer2-server -d -v1**
   [WRN]: LY: Schema node "test-types:desc" not found (test:layer-protocol-name = test-types:desc) with context node "/test:haha".
   [WRN]: LY: Schema node "test-types1:desc1" not found (test1:layer-protocol-name1 = test-types1:desc1) with context node "/test1:haha1".
   [WRN]: LY: Schema node "test-types:desc" not found (test:layer-protocol-name = test-types:desc) with context node "/test:haha".
   [ERR]: LY: Missing required element "layer-protocol-name1" in "test1". (/)
   [WRN]: SR: Missing required element "layer-protocol-name1" in "test1".
   [WRN]: SR: Failed to apply some changes, leaving all changes scheduled.
   [WRN]: LY: Schema node "test-types:desc" not found (test:layer-protocol-name = test-types:desc) with context node "/test:haha".

    What I want to express is that if there are multiple such models, an error will occur and the second module will fail to install successfully.

thanks!

**Comment by michalvasko** [comment]
Okay, one more change was required. Try it now, hopefully it was the last one.

Regards,
Michal

**Comment by xxyy0906** [comment]
Hi Michal:
I'm very much obliged to you.I can now successfully install the module.I have another question for you:
netopeer2-server -d -v1
[WRN]: LY: Schema node "test-types:desc" not found (test:layer-protocol-name = test-types:desc) with context node "/test:haha".
[WRN]: LY: Schema node "test-types1:desc1" not found (test1:layer-protocol-name1 = test-types1:desc1) with context node "/test1:haha1".

1. Will these warnings affect the operation of sysrepo, and I think start-up.xml data will eliminate these warnings.
2. How to eliminate these warnings, is it through api of sysrepo create these node and give these node xpath data.

thanks!

**Comment by michalvasko** [comment]
Hi,
1. Yes, they will affect `sysrepo`. They are strictly schema warnings meaning whatever data you set does not matter. When you see similar warnings is means that an XPath expression cannot even be resolved on schema meaning it will never be true on data -> it will always evaluate to false, which you probably do not want.
2. You can eliminate them by fixing the schema. This is the fixed one
```yang
module test-my1 {
  namespace "http://www.example.net/test-my1";
  prefix test-my1;

  import test-types1 {
		prefix "test-types1";
	}
  import test1 {
		prefix "test1";
	}

	identity desc1 {
        base test-types1:layer-protocol-name1;
        description "";
    }

	augment "/test1:haha1" {
        when "test1:layer-protocol-name1 = 'test-my1:desc1'";
        container desc-pac1 {
            leaf ts-detail1 {
                type string;
                description "none";
            }
        }
    }
}
```

Regards,
Michal

**Comment by xxyy0906** [comment]
Hi Michal:
First of all, I am very sure that the method you told me is effective and has solved some of my problems, but if there are multiple **when** and **agument**, netopper-server still has some warnings, but I am not sure if these warnings will affect use of sysrepo,hope to get your help.
there are 3 modules:
--**test-types2.yang**
    module test-types2 {
  namespace "http://www.example.net/test-types2";
  prefix test-types2;
  identity layer-protocol-name2 {
        description "";
    }
}
--**test2.yang**
module test2 {
  namespace "http://www.example.net/test2";
  prefix test2;
  import test-types2 { 
		prefix "test-types2"; 
	}
	container haha2{
	 	leaf layer-protocol-name2 {
		        mandatory true;
		        type identityref {
		            base test-types2:layer-protocol-name2;
		        }
		        description "";
		    }
	}
	
	container haha3{
	 	leaf layer-protocol-name3 {
		        mandatory true;
		        type identityref {
		            base test-types2:layer-protocol-name2;
		        }
		        description "";
		    }
	}
}
--**test-my2.yang**
module test-my2 {
  namespace "http://www.example.net/test-my2";
  prefix test-my2;

  import test-types2 { 
		prefix "test-types2"; 
	}
  import test2 { 
		prefix "test2"; 
	}

	identity desc2 {
        base test-types2:layer-protocol-name2;
        description "";
    }
	
	augment "/test2:haha2" {
        when "test2:layer-protocol-name2 = 'test-types2:desc2'";
        container desc-pac2 {
            leaf ts-detail2 {
                type string;
                description "none";
            }
        }
    }

	augment "/test2:haha3" {
        when "test2:layer-protocol-name3 = 'test-types2:desc2'";
        container desc-pac3 {
            leaf ts-detail3 {
                type string;
                description "none";
            }
        }
    }
}
--**test2.xml**
`<haha2 xmlns="http://www.example.net/test2">
  <layer-protocol-name2 xmlns:x="http://www.example.net/test-my2">x:desc2</layer-protocol-name2>
</haha2>
<haha3 xmlns="http://www.example.net/test2">
  <layer-protocol-name3 xmlns:x="http://www.example.net/test-my2">x:desc2</layer-protocol-name3>
</haha3>`

1. install modules
    sysrepoctl -v3 -a -i test-types2.yang
    sysrepoctl -v3 -i test2.yang
    sysrepoctl -v3 -i test-my2.yang
    sudo sysrepocfg -W test2.xml -f xml -m test2 -v3
    These are as normal as before;

2. here is the warning from netopper-server
    netopeer2-server -d -v1
    [WRN]: LY: Identityref value is not derived from all its bases. (/test2:layer-protocol-name2)
    [WRN]: LY: Failed to resolve identityref "test-types2:desc2". (/test2:layer-protocol-name2)
    [WRN]: LY: Previous warning generated by XPath subexpression[0] "test2:layer-protocol-name2 = 'test-types2:desc2'".
    [WRN]: LY: Identityref value is not derived from all its bases. (/test2:layer-protocol-name3)
    [WRN]: LY: Failed to resolve identityref "test-types2:desc2". (/test2:layer-protocol-name3)
    [WRN]: LY: Previous warning generated by XPath subexpression[0] "test2:layer-protocol-name3 = 'test-types2:desc2'".

3. I want to know if these warnings will affect the use of sysrepo, and if so, how should I resolve the warnings.

thanks!

**Comment by michalvasko** [comment]
Hi,
only warnings generated by *sysrepo* when the modules are actually being installed should be 100% reliable. Any other ones, especially by *netopeer2-server*, can be false positives, such as these ones. The cause is the order in which the modules are loaded and how current *libyang* works. Will be solved by the new *libyang* once we finish and integrate it, still a long way to go.

Regards,
Michal

**Comment by xxyy0906** [comment]
Hi Michal:
    Thank you very much for your help, thank you again!
thanks!

**Comment by xxyy0906** [comment]
Hi Michal:
  Sorry I reopened the issue because I may still not be able to operate normally.My problem now is that the warnings based on the above steps seem to affect my data manipulation on this yang file.So I may need your help.
   

1. **install modules**
    sysrepoctl -v3 -a -i test-types2.yang
    sysrepoctl -v3 -i test2.yang
    sysrepoctl -v3 -i test-my2.yang
    sudo sysrepocfg -W test2.xml -f xml -m test2 -v3

2. **netopeer2-server -d -v1**
    [WRN]: LY: Identityref value is not derived from all its bases. (/test2:layer-protocol-name2)
    [WRN]: LY: Failed to resolve identityref "test-types2:desc2". (/test2:layer-protocol-name2)
    [WRN]: LY: Previous warning generated by XPath subexpression[0] "test2:layer-protocol-name2 = 'test-types2:desc2'".
    [WRN]: LY: Identityref value is not derived from all its bases. (/test2:layer-protocol-name3)
    [WRN]: LY: Failed to resolve identityref "test-types2:desc2". (/test2:layer-protocol-name3)
    [WRN]: LY: Previous warning generated by XPath subexpression[0] "test2:layer-protocol-name3 = 'test-types2:desc2'".

3. **netopper-cli + connect**
    **log:**
     ly WARNING: Identityref value is not derived from all its bases. (/test2:layer-protocol-name2)
     ly WARNING: Failed to resolve identityref "test-types2:desc2". (/test2:layer-protocol-name2)
     ly WARNING: Previous warning generated by XPath subexpression[0] "test2:layer-protocol-name2 = 'test-types2:desc2'".
     ly WARNING: Identityref value is not derived from all its bases. (/test2:layer-protocol-name3)
     ly WARNING: Failed to resolve identityref "test-types2:desc2". (/test2:layer-protocol-name3)

      **get --filter-xpath /test2:***
      DATA
    ```xml
   <haha2 xmlns="http://www.example.net/test2">
   <layer-protocol-name2 xmlns:test-my2="http://www.example.net/test-my2">test-my2:desc2</layer-protocol-name2>
   </haha2>
   <haha3 xmlns="http://www.example.net/test2">
   <layer-protocol-name3 xmlns:test-my2="http://www.example.net/test-my2">test-my2:desc2</layer-protocol-name3>
   </haha3>
```

4. Now i want to write data by netopper-cli,write data for
   when "test2:layer-protocol-name2 = 'test-types2:desc2'";
        container desc-pac2 
            leaf ts-detail2

   edit-config --target running --config=/home/linux/test2-edit.xml
   
   netopper-cli log:
    ERROR
	type:     application
	tag:      operation-failed
	severity: error
	path:     /test2:haha2/test-my2:desc-pac2
	message:  When condition "test2:layer-protocol-name2 = 'test-types2:desc2'" not satisfied.

   netopper-server log:
    [ERR]: LY: When condition "test2:layer-protocol-name2 = 'test-types2:desc2'" not satisfied. 
    (/test2:haha2/test-my2:desc-pac2)
    [ERR]: SR: When condition "test2:layer-protocol-name2 = 'test-types2:desc2'" not satisfied.
    [ERR]: SR: Validation failed.
    [ERR]: SR: When condition "test2:layer-protocol-name2 = 'test-types2:desc2'" not satisfied.
    [WRN]: SR: Event "rpc" with ID 1 priority 0 failed (Validation failed).
    [ERR]: NP: Failed to send an RPC (User callback failed).

    test2-edit.xml:
     ```xml
   <haha2 xmlns="http://www.example.net/test2">
	<desc-pac2 xmlns="http://www.example.net/test-my2">
		<ts-detail2 xmlns="http://www.example.net/test-my2">test-ts-detail2</ts-detail2>
	</desc-pac2>
   </haha2>
   ```

5. I think maybe the node does not exist, so do the following,
    (1)application_changes_example test2
    log:
     Application will watch for changes in "test2".

     ========== READING RUNNING CONFIG: ==========

    /test2:haha2 (container)
    /test2:haha2/layer-protocol-name2 = test-my2:desc2
    /test2:haha3 (container)
    /test2:haha3/layer-protocol-name3 = test-my2:desc2


     ========== LISTENING FOR CHANGES ==========

   (2)I try to set the data to /test2:haha2/layer-protocol-name2 so,
    sr_set_item_example /test2:haha2/layer-protocol-name2 desc2
    log:
    [WRN]: Schema node "test-types:desc" not found (test:layer-protocol-name = test-types:desc) with context node "/test:haha".
    [WRN]: Identityref value is not derived from all its bases. (path: /test2:layer-protocol-name2)
    [WRN]: Failed to resolve identityref "test-types2:desc2". (path: /test2:layer-protocol-name2)
    [WRN]: Previous warning generated by XPath subexpression[0] "test2:layer-protocol-name2 = 'test-types2:desc2'".
    [WRN]: Identityref value is not derived from all its bases. (path: /test2:layer-protocol-name3)
    [WRN]: Failed to resolve identityref "test-types2:desc2". (path: /test2:layer-protocol-name3)
    [WRN]: Previous warning generated by XPath subexpression[0] "test2:layer-protocol-name3 = 'test-types2:desc2'".
    **[ERR]: Identityref value is not derived from all its bases. (path: /test2:haha2/layer-protocol-name2)
    [ERR]: Failed to resolve identityref "desc2". (path: /test2:haha2/layer-protocol-name2)
    [ERR]: Failed to create node "layer-protocol-name2" as a child of "haha2". (path: /test2:haha2/layer-protocol-name2)
    [ERR]: Invalid datastore edit.**
    (3)I try to set the data directly to 
        when "test2:layer-protocol-name2 = 'test-types2:desc2'";
        container desc-pac2 
            leaf ts-detail2
    **sr_set_item_example /test2:haha2/test-my2:desc-pac2/ts-detail2  test-data**
    log:
    Application will set "/test2:haha2/test-my2:desc-pac2/ts-detail2" to "test-data".
    [WRN]: Schema node "test-types:desc" not found (test:layer-protocol-name = test-types:desc) with context node "/test:haha".
    [WRN]: Identityref value is not derived from all its bases. (path: /test2:layer-protocol-name2)
    [WRN]: Failed to resolve identityref "test-types2:desc2". (path: /test2:layer-protocol-name2)
    [WRN]: Previous warning generated by XPath subexpression[0] "test2:layer-protocol-name2 = 'test-types2:desc2'".
    [WRN]: Identityref value is not derived from all its bases. (path: /test2:layer-protocol-name3)
    [WRN]: Failed to resolve identityref "test-types2:desc2". (path: /test2:layer-protocol-name3)
    [WRN]: Previous warning generated by XPath subexpression[0] "test2:layer-protocol-name3 = 'test-types2:desc2'".
    **[ERR]: When condition "test2:layer-protocol-name2 = 'test-types2:desc2'" not satisfied. (path: /test2:haha2/test-my2:desc-pac2)
    [ERR]: Validation failed.**

    Finally, I would like to ask you:
    1. Is there a problem with my operation.
    2. How should I set up such data.

thanks!

**Comment by michalvasko** [comment]
Hi,
okay, even I have not noticed it but the warning is correct, you need to change the condition to
```yang
when "test2:layer-protocol-name2 = 'test-my2:desc2'";
```
The `desc2` identity had a wrong prefix.

Regards,
Michal

**Comment by xxyy0906** [comment]
Hi Michal:
    Should I modify test-my2.yang?But identity is defined in test-types2.And I don't think there is any significant problem with my yang file.
thanks!

**Comment by michalvasko** [comment]
Yes, you should modify your YANG file and there is a significant problem with the `when` condition, like I said. The identity `desc2` is defined in the module `test-my2`. It does not matter where its base identity is defined.

Regards,
Michal

**Comment by xxyy0906** [comment]
Hi Michal:
    Thank you very much for your help, the modification is effective. From your professional point of view, is a definition like mine error or not commonly used?
    I checked the RFC, but I didn't find what I wanted.
    https://tools.ietf.org/html/rfc7950(7.21.5.  The "when" Statement)

**Comment by michalvasko** [comment]
Hi,
you simply made a mistake, no mystery there. The [when](https://tools.ietf.org/html/rfc7950#section-7.21.5) section simply extends the general [XPath](https://tools.ietf.org/html/rfc7950#section-6.4) section. The [first](https://tools.ietf.org/html/rfc7950#section-6.4.1) section talks about how prefixes and namespaces are resolved. [Identityref value](https://tools.ietf.org/html/rfc7950#section-9.10.3) (which is what you have used in the expression) is represented as qualified names based on XML definitions. [XML specs](https://www.w3.org/TR/2009/REC-xml-names-20091208/#ns-qualnames) say that qualified names with a prefix use the namespace prefix they belong to. I am not sure what else to reference that you may have missed but I would say it is quite obvious. If you want to use identity value with a prefix, it must be the prefix of the module it was defined in.

Regards,
Michal

**Comment by xxyy0906** [comment]
Hi Michal:
    Ok, fully understand what you mean, thank you very much, thank you again!
thanks!
