### ISSUE TITLE
[new sysrepo] Wrong libyang context in yang-library callback

### ISSUE THREAD

**Issue by gitter-runner** [sysrepo/sysrepo#1852]
Hi!

When I tried to create my own callback for _ietf-yang-library_, I realized that the latest sysrepo automatically returns its own reply for the GET RPC called on _/ietf-yang-library:yang-library_.

My problem with that, is that my server uses a different libyang context than the sysrepo's. The XML which the callback returns seems to be merged (or overwritten?) by the result of the _ly_ctx_info()_ called by sysrepo.

I think it might be related to this commit: 
https://github.com/sysrepo/sysrepo/commit/fb0d3438826395188f2698713c72a7a927072c61

Can I overwrite this behavior? I don't want to advertise every module.

Versions:
sysrepo: 1.4.9
libyang:  1.0.132
libnetconf2: 1.1.11 

Thanks!

**Comment by michalvasko** [comment]
Hi,
I wrote it so that you should be able to overwrite it easily. What is your `ietf-yang-library` operational subscription?

Regards,
Michal

**Comment by gitter-runner** [comment]
Hi,
I use the _sr_oper_get_items_subscribe()_ function to subscribe for the "_/ietf-yang-library:yang-library_" XPath.

The callback itself can be even a simple return NULL; the returned XML will still be the complete module-set.

Or you meant something else?

Thanks!

**Comment by michalvasko** [comment]
Hi,
right, it worked a bit differently than I thought. So, it should work now, I have added a similar test, and improved the documentation. But I have failed to reference this issue, the commit is https://github.com/sysrepo/sysrepo/commit/ac0142f95200a71366f917aacef3881241d2c801.

Regards,
Michal

**Comment by gitter-runner** [comment]
Thanks for the help, it works right, now!
