### ISSUE TITLE
Fetch data

### ISSUE THREAD

**Issue by Sneha-star** [sysrepo/sysrepo#1855]
sr_get_subtree or sr_get_data both does not return the default values.
My application requirement is to post all the datas.
Is there any way to fetch all using sysrepo api ?

**Comment by michalvasko** [comment]
Hi,
how do you know it does not return default data? Did you print them or traverse them?

Regards,
Michal

**Comment by Sneha-star** [comment]
Yes..I dumped the retrieved data using "print_mem" .

**Comment by michalvasko** [comment]
Then just use the correct print flags and the defaults will be printed.

Regards,
Michal

**Comment by Sneha-star** [comment]
Thank you Michal

**Comment by Sneha-star** [comment]
Hi Michal,

By using the print flags, I was able to get all the nodes..
But in this case, i lose the lyd_node* info.
How can I get both ?

**Comment by michalvasko** [comment]
Hi,
I do not understand what you are saying at all, please be more specific. How can you lose data by printing them differently?

Regards,
Michal

**Comment by Sneha-star** [comment]
I mean, by printing I get in string format . But I wanted the lyd_node* info also .

**Comment by michalvasko** [comment]
I am still lost. You get some `struct lyd_node *data` by calling `sr_get_data()`. In these data there is all the information you can possibly want (including the "info" if you are referring to the schema node type `info` structure). You then print the data to string by calling `lyd_print_mem()`. What is the problem?

Regards,
Michal
