### ISSUE TITLE
DB Content

### ISSUE THREAD

**Issue by Sneha-star** [sysrepo/sysrepo#1858]
Hi Michal,

Is there any api to  find out the delta changes between 2 Dbs. (ex. Candidate and Running).

**Comment by michalvasko** [comment]
Hi,
you can easily use *libyang* for that. Call `sr_get_data()` with the same arguments on both datastores and then call `lyd_diff()` in the retrieved data.

Regards,
Michal

**Comment by Sneha-star** [comment]
Thank you Michal.

**Comment by Sneha-star** [comment]
Hi Michal,

Is there any way to know whether Candidate Db has changed data or not. (i.e before doing sr_apply_changes call) ?

**Comment by michalvasko** [comment]
Hi,
you should be able to learn this by executing `sr_lock()` on `candidate`. If it is modified, the lock will fail (a requirement of NETCONF). Just note that `sr_apply_changes()` only applies the prepared changes in a session to the particular datastore. If you want to do NETCONF `<commit>`, you must call `sr_copy_config()` from `candidate` to `running`.

Regards,
Michal

**Comment by Sneha-star** [comment]
Hi Michal,

The case is in the same session, suppose I would like to know if the data is dirty.

**Comment by michalvasko** [comment]
Hi,
please be more exact then. What you want to know is whether the changes made in a session are some actual data changes? Meaning, for example, that if a leaf has value 'a' and you set it to 'a', then there is still no data change. In this case you can just do what I said before, use this session to get `running` data, then to get `candidate` data and then make a *libyang* diff on them.

However, this solution can be quite costly for large data so if you do care about that, you should avoid making these redundant changes and keep track of the actual changes.

Regards,
Michal

**Comment by Sneha-star** [comment]
For example..
Meaning, for example, that if a leaf has value 'a' and then it got set it to 'b', 
Or a new list/container/leaf is created..

Any change in the new session with respect to the earlier committed session.

**Comment by michalvasko** [comment]
Okay, so what you need to know is simply whether there are any prepared changes in a session? That is always known internally so a simple checker could be added into API. But first I need to know what exactly you need and I still do not, please be more clear.

Regards,
Michal

**Comment by Sneha-star** [comment]
Yes..Michal. 
Thats what we want. (To check if any prepared changes are there)

**Comment by michalvasko** [comment]
HI,
okay, so you want a function `int sr_has_changes(sr_session_ctx_t *session)` that will simply tell you whether there are some prepared (non-applied) changes on a session and its datastore, right? Just making sure before adding a new function and increasing *sysrepo* SO minor version.

Regards,
Michal

**Comment by Sneha-star** [comment]
Yes Michal.
Thank you.

**Comment by michalvasko** [comment]
Okay, added.

Regards,
Michal
