### ISSUE TITLE
oper subscription

### ISSUE THREAD

**Issue by Sneha-star** [sysrepo/sysrepo#1859]
Hi Michal

while subscribing for oper data I am getting the Missing module error as shown below.
```
[ERR]: Missing module name.
Exception: libyang error
Traceback (most recent call last):
  File "test.py", line 136, in <module>
    None, sysrepo.SR_SUBSCR_DEFAULT);
  File "/usr/lib/python3.6/site-packages/sysrepo.py", line 3006, in oper_get_items_subscribe
    return _sysrepo.Subscribe_oper_get_items_subscribe(self, *args)
RuntimeError: libyang error
```
However sysrepoctl -l list the given module.
```
  subscription = suboper.oper_get_items_subscribe("module-1", "module-1:state-1",   oper_cb, None, sysrepo.SR_SUBSCR_DEFAULT);
```
I am not getting how can I debug this..and why I am getting missing module error.
Any pointer would be helpful.

**Comment by michalvasko** [comment]
Hi,
could you please try it again with the latest `devel`? The commit bd643472c0a8a306b7102ac42c78b7fc0491ae47 may have fixed this.

Regards,
Michal

**Comment by Sneha-star** [comment]
I will check.
But what was the issue ?

**Comment by michalvasko** [comment]
That commit fixed the generic callback prototype (removed one argument) so it may have caused some argument ordering error. I don't know much about Python, but that was a serious error, so just please try it.

Regards,
Michal

**Comment by Sneha-star** [comment]
It worked.

Thank you.

**Comment by Sneha-star** [comment]
Hi Michal,

One more query, 
Now callback is getting called and I am filling the data too.
But in the get_call I am not getting any data.

        print ("\n Oper callabck \n")
        parent.reset(sysrepo.Data_Node(ctx, "/module-1:state-1", None, sysrepo.LYD_ANYDATA_CONSTSTRING, 0))
        st= sysrepo.Data_Node(parent, mod, "list-1")
.......

**Comment by michalvasko** [comment]
Hi,
you are not getting any data in the operational callback? That is expected, you are supposed to provide these data, why should you get any? If there were any previously, they were deleted.

Regards,
Michal

**Comment by Sneha-star** [comment]
I am providing the data.. when the callback is hit as a part of get operation.

print ("\n Oper callabck \n")
    parent.reset(sysrepo.Data_Node(ctx, "/module-1:state-1", None, sysrepo.LYD_ANYDATA_CONSTSTRING, 0))
    st= sysrepo.Data_Node(parent, mod, "list-1")

However, i do not see that get reflected in the show output.

**Comment by michalvasko** [comment]
Hi,
so your callback is getting called but the data are not seen in the output of `get` operation? Are they present if you run this?
```
sysrepocfg -d operational -m module-1 -X
```

Regards,
Michal

**Comment by Sneha-star** [comment]
yes..its there

**Comment by Sneha-star** [comment]
Am I missing something while retrieving ?

**Comment by michalvasko** [comment]
Hi,
I am not sure what the problem may be. Are you also using the latest `devel` of *libnetconf2* and *netopeer2*?

Regards,
Michal

**Comment by Sneha-star** [comment]
I am using sysrepo/libyang  api only

**Comment by michalvasko** [comment]
Okay, then I am not getting what the issue is. You said you do not see some data in the output and then that they are in `sysrepocfg` output. Please explain the problem exactly.

Regards,
Michal

**Comment by Sneha-star** [comment]
Steps:
1)Subscribe for oper module (Successful)
2) Add data (Successful)
3) sysrepocfg dumps data correctly
4) but get_data/get_subtree does returns empty data.

**Comment by michalvasko** [comment]
I see but it does not really make sense. Are you sure you have set `operational` datastore for the session when calling `sr_get_data()`? Because that is exactly what `sysrepocfg` does.

Regards,
Michal

**Comment by Sneha-star** [comment]
Yes

**Comment by michalvasko** [comment]
Look, I am getting tired of this. If you are telling me that after you have the callback set and subscribed, you call
```
sysrepocfg -d operational -m module-1 -X
```
and the data is there but if you yourself in an application call
```C
sr_get_data(session, "/module-1:*", 0, 0, &data);
```
with `session` having `SR_DS_OPERATIONAL` set you do not get the data then I simply do not believe you. Look for yourself, this is exactly what [sysrepocfg does](https://github.com/sysrepo/sysrepo/blob/master/src/executables/sysrepocfg.c#L300).

Regards,
Michal

**Comment by Sneha-star** [comment]
Ok Michal.
I may be missing something.
Will check.
