### ISSUE TITLE
there is no fail when using sysrepoctl with 'sysrepoctl -i ' to  install two different  modules with the same namespace 

### ISSUE THREAD

**Issue by fredgan** [sysrepo/sysrepo#1861]
Hi,
   I have two different modules with the  same namespace (`eg:mod1.yang,mod2.yang`),I install the two modules with the tool sysrepoctl with the command `sysrepoctl -i mod1.yang(mod2.yang)`.there are no  fails or  errors when I install the second module(mod2.yang),in fact, it should not success because libyang does not support this scene.but it is failure when I install mod2.yang with  the command `sysrepoctl -a -i mod2.yang`, meanwhile ,once it fails,all operations of tools(sysrepoctl,sysrepcfg) will be failed  with the same error `[ERR]: Two different modules ("mod1" and "mod2") have the same namespace "urn:test" `,then , I wan to  continue using tools normally,I need to `make sr_clean` first,repeat all the previous operations again ,but this is no what I want.
so my questions:
1. whether the tool sysrepoctl with the the parameter `'-a'` or not,installing module with command `'sysrepoctl -i'` which is the same as `'sysrepoctl -a  -i '`,the implementation is the same ,is it ok?

2. in order not to  affect other normal operations with tools,whether to consider supporting failed rollback proceesing?
 
the modules have the same namespace(`urn:test`),as follows:
 ```
   mod1.yang :

  module mod1 {
  namespace "urn:test";
  prefix m1;

  leaf l {
    type string;
  }
}

 mod2.yang :
  module mod2 {
  namespace "urn:test";

  prefix m2;
  leaf l {
    type string;
  }
}
```

install two modules with `sysrepo -i `:

```
root@oss-0007:/data/sysrepo/build# ./sysrepoctl -i ./module_yang/mod1.yang
root@oss-0007:/data/sysrepo/buildd# ./sysrepoctl -i ./module_yang/mod2.yang
root@oss-0007:/data/sysrepo/build# ./sysrepoctl -l
[ERR]: Two different modules ("mod1" and "mod2") have the same namespace "urn:test".
[ERR]: Module "mod2" parsing failed.
sysrepoctl error: Failed to connect (libyang error)
root@oss-0007:/data/sysrepo/build# make sr_clean
Built target shm_clean
Built target sr_clean
root@oss-0007:/data/sysrepo/build# ./sysrepoctl -l
Sysrepo repository: /data/sysrepo/build/repository

Module Name                | Revision   | Flags | Owner     | Permissions | Submodules | Features
-------------------------------------------------------------------------------------------------
ietf-datastores            | 2017-08-17 | i     |           |             |            |

```

install two modules with `sysrepo -a -i  `:

```
root@oss-0007:/data/sysrepo/build# ./sysrepoctl -a -i ./module_yang/mod1.yang
root@oss-0007:/data/sysrepo/build# ./sysrepoctl -a -i ./module_yang/mod2.yang
[ERR]: Two different modules ("mod1" and "mod2") have the same namespace "urn:test".
[ERR]: Module "mod2" parsing failed.
sysrepoctl error: Failed to apply changes (libyang error)
root@oss-0007:/data/sysrepo/build# ./sysrepoctl -l
[ERR]: Two different modules ("mod1" and "mod2") have the same namespace "urn:test".
[ERR]: Module "mod2" parsing failed.
sysrepoctl error: Failed to connect (libyang error)
root@oss-0007:/data/sysrepo/build# make sr_clean
Built target shm_clean
Built target sr_clean
root@oss-0007:/data/sysrepo/build# ./sysrepoctl -l
Sysrepo repository: /data/sysrepo/buil/build/repository

Module Name                | Revision   | Flags | Owner     | Permissions | Submodules | Features
-------------------------------------------------------------------------------------------------
ietf-datastores            | 2017-08-17 | i     |           |             |            |
```

**Comment by michalvasko** [comment]
Hi,
all the mechanisms are already implemented, I just did not think there was a situation when the module would fail to be installed despite succeeding to be loaded before. So, it should be fixed now.

Regards,
Michal

**Comment by fredgan** [comment]
it works now,thanks
