### ISSUE TITLE
COMMIT_VERIFY_TIMEOUT in sysrepo-1.4.2

### ISSUE THREAD

**Issue by qjwu888** [sysrepo/sysrepo#1862]
Hi Michal,

WHere can to change COMMIT_VERIFY_TIMEOUT in sysrepo-1.4.2, What is the default value？In my testing, found the following error.

daemon.err netopeer2-server[5212]: Callback event "rpc" with ID 885 processing timed out.
daemon.err netopeer2-server[5212]: Failed to send an RPC (User callback failed).
daemon.err netopeer2-server[5212]: Callback event "rpc" with ID 885 processing timed out.
daemon.err netopeer2-server[5212]: Failed to send an RPC (User callback failed).
daemon.err netopeer2-server[5212]: Locking subscription of "gwtt-ietf-ipsec" failed, previous event "done" with ID 363 was not processed.
daemon.err netopeer2-server[5212]: Unable to finish processing event "rpc" with ID 885 priority 0 (timeout probably).
daemon.err netopeer2-server[5212]: Module "yang" is already locked by this session 14 (NC SID 1).
daemon.err netopeer2-server[5212]: Requested resource already locked
daemon.err netopeer2-server[5212]: Failed to send an RPC (User callback failed).

**Comment by michalvasko** [comment]
Hi,
if you have problems with *netopeer2* timeouts, you must switch to `devel`. The changes there are required. Then just adjust its compile-time timeouts.

Regards,
Michal

**Comment by qjwu888** [comment]
Hi Michal,
Now I use Netopeer2-devel-server.
Your mean let me change to sysrepo-devel version ?

**Comment by michalvasko** [comment]
Then just adjust `DATA_CHANGE_TIMEOUT` and `RPC_TIMEOUT` of *netopeer2*. However, in that case you should also be using *sysrepo* `devel` because we do not guarantee compatibility of `devel` with `master` and vice versa between all the projects.

Regards,
Michal

**Comment by qjwu888** [comment]
Hi Michal, 
For gwtt-ietf-ipsec module,There are two subscribe ,Offen found the following timeout error in LTE network.
To fix ,only change  DATA_CHANGE_TIMEOUT and RPC_TIMEOUT of netopeer2,ok ?

rc = sr_module_change_subscribe(session, "gwtt-ietf-ipsec", "/gwtt-ietf-ipsec:ikev2", ike_subtree_change_cb, *private_ctx,0, SR_SUBSCR_DEFAULT, &ipsec_plugin->subscription);
rc = sr_module_change_subscribe(session, "gwtt-ietf-ipsec", "/gwtt-ietf-ipsec:ipsec/proposal/ipsec-proposal", ipsec_subtree_change_cb, *private_ctx,0, SR_SUBSCR_CTX_REUSE, &ipsec_plugin->subscription);

netopeer2-server[5228]: Callback event "rpc" with ID 435 processing timed out.
netopeer2-server[5228]: Failed to send an RPC (User callback failed).
netopeer2-server[5228]: Callback event "rpc" with ID 435 processing timed out.
netopeer2-server[5228]: Failed to send an RPC (User callback failed).
netopeer2-server[5228]: Locking subscription of "gwtt-ietf-ipsec" failed, previous event "done" with ID 163 was not processed.
netopeer2-server[5228]: Unable to finish processing event "rpc" with ID 435 priority 0 (timeout probably).
netopeer2-server[5228]: Module "yang" is already locked by this session 14 (NC SID 1).
netopeer2-server[5228]: Requested resource already locked
netopeer2-server[5228]: Failed to send an RPC (User callback failed).

**Comment by michalvasko** [comment]
Hi,
I do not understand, obviously the default timeout is not enough so you should increase it.

Regards,
Michal

**Comment by qjwu888** [comment]
Hi Michal,
Thanks for your reply,now work fine .
