### ISSUE TITLE
Query : Operational data subscription

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1863]
Hi,

Could you please help me how to give xpath for operational data subscription.

If I am subscribing with `/ietf-interfaces:interfaces-state` and requesting data from client using `/ietf-interfaces:interfaces-state` everything works fine.

But if I want to get data with xpaths having various filters as below.
```
/ietf-interfaces:interfaces-state/interface[name='eth1']/*
/ietf-interfaces:interfaces-state/interface/name
/ietf-interfaces:interfaces-state/interface/rx-stats
```
Which xpath I need to use for subscribing to sysrepo?

I tried to subscribe with `/ietf-interfaces:interfaces-state//*` and I am getting libyang error.
Please correct me if I am missing something.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
well, it is up to you. The simplest way is to keep using `/ietf-interfaces:interfaces-state`, the specific data will then be filtered out. But if you want *sysrepo* to do some filtering beforehand and not call callbacks for data that are not needed you can use more specific subscriptions. Which exactly is up to you, there are no restrictions.

Also, I tried your XPath `/ietf-interfaces:interfaces-state//*` and it worked just fine, what was the problem? But using recursive selection (which includes `//`) is redundant, you are always subscribing for providing subtrees (with all their descendants).

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Sorry for delayed reply.

I am able to successfully subscribe with `/ietf-interfaces:interfaces-state//*`. But getting filtered values with below xpaths is not working. I am getting empty data.

```
/ietf-interfaces:interfaces-state/interface[name='eth1']/*
/ietf-interfaces:interfaces-state/interface/name
/ietf-interfaces:interfaces-state/interface/rx-stats
```
Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
not sure what the problem is, how did you test it? I have modified `oper_data_example` callback:
```C
static int
dp_get_items_cb(sr_session_ctx_t *session, const char *module_name, const char *xpath, const char *request_xpath,
        uint32_t request_id, struct lyd_node **parent, void *private_data)
{
    (void)session;
    (void)request_xpath;
    (void)request_id;
    (void)private_data;

    printf("\n\n ========== DATA FOR \"%s\" \"%s\" REQUESTED =======================\n\n", module_name, xpath);

    if (!strcmp(module_name, "examples") && !strcmp(xpath, "/examples:stats")) {
        *parent = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(session)), "/examples:stats/counter", "852", 0, 0);
        lyd_new_path(*parent, NULL, "/examples:stats/counter2", "1052", 0, 0);
    } else if (!strcmp(module_name, "ietf-interfaces") && !strcmp(xpath, "/ietf-interfaces:interfaces-state")) {
        *parent = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(session)), "/ietf-interfaces:interfaces-state", NULL, 0, 0);
        lyd_new_path(*parent, NULL, "/ietf-interfaces:interfaces-state/interface[name='eth0']/type", "iana-if-type:ethernetCsmacd", 0, 0);
        lyd_new_path(*parent, NULL, "/ietf-interfaces:interfaces-state/interface[name='eth1']/type", "iana-if-type:ethernetCsmacd", 0, 0);
    }

    return SR_ERR_OK;
}
```
executed it and then called `sysrepocfg` export:
```
vasko@linux-ln0o:~/Documents/sysrepo/build> ./sysrepocfg -d operational -x "/ietf-interfaces:interfaces-state/interface[name='eth1']/*" -X
<interfaces-state xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interface>
    <name>eth1</name>
    <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
  </interface>
</interfaces-state>
vasko@linux-ln0o:~/Documents/sysrepo/build> ./sysrepocfg -d operational -x "/ietf-interfaces:interfaces-state/interface/name" -X
<interfaces-state xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interface>
    <name>eth0</name>
  </interface>
  <interface>
    <name>eth1</name>
  </interface>
</interfaces-state>
```
It worked flawlessly. If you have also used `sysrepocfg`, did you enclose the XPath in quotes?

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Looks like there is an issue in my code, Sorry for wasting your time.

Thanks & Regards,
Sriram.K
