### ISSUE TITLE
[new sysrepo] Oper data missing from output of sysrepocfg export

### ISSUE THREAD

**Issue by gitter-runner** [sysrepo/sysrepo#1865]
Hi,
I tried to export the operational datastore into xml using the following command:

`sysrepocfg –export=test.xml -d operational -m ietf-interfaces`

The test.xml contains the pushed operational data, but all data provided by the callback (registered by _sr_oper_get_items_subscribe_) is missing.

Thanks!

**Comment by fredgan** [comment]
what version are you using? can you please provide detail operation steps and using module？

**Comment by michalvasko** [comment]
Hi,
please answer what @fredgan asked and add details about what are the exact data you are providing (push and pull subscription) and the xpath you have used.

Regards,
Michal

**Comment by GuoyouZhang** [comment]
i meet the issue in the latest devel branch

**Comment by gitter-runner** [comment]
Sorry, it was my fault in xpath handling of oper data callback.
On sysrepo level it works as expected on the latest devel version, so the issue can be closed.

Tanks!
