### ISSUE TITLE
Is embedded notification supported?

### ISSUE THREAD

**Issue by igortern** [sysrepo/sysrepo#1866]
Hello,
Prereqs: sysrepo,notopeer2,libyang,libnetconf from devel. 

I'm trying to emit a remote-endpoint-status-change notification that is embedded in a list in a container.
The code calls 

`sr_event_notif_send(session, "/bbf-polt-vomci:remote-nf-settings/nf-server/server-parameters/listen/listen-endpoint[name='server-ep1']/remote-endpoint-status-change", values, 3);
`
whereas 
`value[0].xpath="/bbf-polt-vomci:remote-nf-settings/nf-server/server-parameters/listen/listen-endpoint[name='server-ep1']/remote-endpoint-status-change/remote-endpoint";
value[0].data.string_val="vomci1";
`
etc.

sr_event_notif_send() returns success.

netopeer2-cli (in verbose mode) prints

`<notification xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0"><eventTime>2020-03-18T01:38:58Z</eventTime><remote-endpoint-status-change xmlns="urn:bbf:yang:bbf-polt-vomci"><remote-endpoint>vomci1</remote-endpoint><connected>true</connected><remote-endpoint-state-last-change>2020-03-18T12:38:58Z</remote-endpoint-state-last-change></remote-endpoint-status-change></notification>
`

That is, xpath base of remote-endpoint-status-change is stripped. In result, both netopeer2-cli and netopeer2-server correctly report an error:

```
ly ERROR: Unknown element "remote-endpoint-status-change". (/)
nc ERROR: Session 1: failed to parse a new notification.

```
 Are notifications embedded in containers & lists supported? If yes, could you advise how to emit this notification?

Regards,
Igor

See attached yang models.

[wt-451-models.zip](https://github.com/sysrepo/sysrepo/files/4346557/wt-451-models.zip)

**Comment by michalvasko** [comment]
Hi,
please try again with the latest *netopeer2*, there was a minor mistake of mine causing this problem.

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,
It works now. Thanks for the quick fix.
Regards,
Igor
