### ISSUE TITLE
Query : Is there any API to set lyd_node directly

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1867]
Hi,

Is there any API fo `sr_set_item` like functionality by taking `lyd_node` ?

I have a list of nodes received from `lyd_diff` in which I have to perform some actions and decide whether to delete, create, or merge those nodes. And I cannot apply that diff directly. 
Looking for better approach to pass `lyd_node` to `sr_set*` APIs.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
yes, you can use `sr_edit_batch()` with a data tree created from the diff. But it will take some considerable work although you can use *sysrepo* code. `modinfo.c:sr_modinfo_replace()` performs this exactly.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thank you very much for the code pointer.

Is it possible to change `sr_val_ly2sr, sr2ly*` functions to APIs. These are really handy functions for easy migration of applications from old sysrepo to new.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
so what exactly do you need? There are the 2 functions you added, `sr_tree_to_val()` and `sr_tree_to_values()`.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

I have added functions to get `sr_val_t` values from a given libyang data tree.

Use case 1:
There can be a case to convert single `lyd_node` to `sr_val_t`,  For this exposing `sr_val_ly2sr` helps.

Use case 2:
Regarding the suggested approach to create an edit, 
`sr_diff_ly2sr` is not API and it internally uses many sysrepo non API functions. So that I have to copy lot of code.
If we have this function as API it will be very helpfull.

Hope I am clear, please correct me if I missed something.

Thanks & Regards,
Sriram.K

**Comment by sriramkandukuri** [comment]
Hi Michal,

Please find the pull request for the API requested. And provide your review.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
I have not yet agreed with adding anything into *sysrepo*. And I am leaning towards refusing this, to me your use-case seems too specific. There is no problem with you including this code in your project. Also, it is possible the diff in new *libyang* will use another format making this function obsolete.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thank you for clarification.
