### ISSUE TITLE
File based configuration of sysrepo

### ISSUE THREAD

**Issue by meghna-doshi** [sysrepo/sysrepo#1870]
Hi,
We have a use case where once we bring up CU using NETCONF Client, we need to export the configurations done via NETCONF to a file and then bring up another CU using this file instead of NETCONF.
Does sysrepo provide any feature like this, where configuration can be:
1. exported to a file (in some format) by sysrepo
2. import the file by sysrepo running on another server.

Regards,
Meghna

**Comment by michalvasko** [comment]
Hi,
it is all supported but you need to use *libyang* API as well. `sysrepocfg` implements this as well ([export](https://github.com/sysrepo/sysrepo/blob/master/src/executables/sysrepocfg.c#L300) and [import](https://github.com/sysrepo/sysrepo/blob/master/src/executables/sysrepocfg.c#L278)).

Regards,
Michal

**Comment by meghna-doshi** [comment]
Hi Michal,
Thanks for the info, will try and see.

Regards,
Meghna
