### ISSUE TITLE
Populate dp_get_items for list without leafs (except keys)

### ISSUE THREAD

**Issue by io2357911** [sysrepo/sysrepo#1872]
Hello! I try to fill the following example yang model: 
```
module foo-module {
    namespace "http://foo-module";
    prefix foo-module;

    container foo {
        config false;

        container c1 {
            list l1 {
                key "key";
                leaf key {
                    type string;
                    mandatory true;
                }

                list sl1 {
                    key "key";
                    leaf key {
                        type string;
                        mandatory true;
                    }
                }
            }
        }
    }
}
```

Inside dp_get_items callback I receive:
```
xpath /foo-module:foo
xpath /foo-module:foo/c1
xpath /foo-module:foo/c1/l1
```

According to the docs I need to return all leafs except keys. But in the example only child list sl1 exists for list l1. The question is how to notify sysrepo about child list container sl1?

P.S.
This issue appeared when I tried to populate openroadm cituit pack holder capability model with contents. supported-circuit-pack list has only two keys and child list. 
```
     |  |  +--ro org-openroadm-pluggable-optics-holder-capability:pluggable-optics-holder-capability
     |  |     +--ro org-openroadm-pluggable-optics-holder-capability:supported-circuit-pack* [supported-circuit-pack-type supported-pluggable-id-type]
     |  |        +--ro org-openroadm-pluggable-optics-holder-capability:supported-circuit-pack-type    string
     |  |        +--ro org-openroadm-pluggable-optics-holder-capability:supported-pluggable-id-type    identityref
     |  |        +--ro org-openroadm-pluggable-optics-holder-capability:ports* [port-name]
```

**Comment by michalvasko** [comment]
Hi,
well, you should do precisely what is documented, not return __keys__ but it says nothing about __lists__, which you can return. So, when the callback is called for `/foo-module:foo/c1/l1`, you should return `/foo-module:foo/c1/l1/sl1[key='val']`. Also, you should no longer be using this old *sysrepo* version but the current one 1.x instead.

Regards,
Michal

**Comment by io2357911** [comment]
Thank you for the reply. It works fine now. There were a little misunderstanding. I guess it may be a good idea to provide additional examples in description.

**Comment by michalvasko** [comment]
Hi,
an even better idea is to use the current *sysrepo* where this mechanism is no longer.

Regards,
Michal
