### ISSUE TITLE
Setting data error when output contains mandatory true in RPC

### ISSUE THREAD

**Issue by xxyy0906** [sysrepo/sysrepo#1874]
Hi:
   I set the value of output in the rpc callback function and found that the output contains mandatory true data setting error, so,my purpose is to set data successfully.
    This is a yang module:
    -rpc_examples.yang
 ```yang
   module rpc_examples {
    yang-version 1.1;
    namespace "urn:rpc_examples";
    prefix rpc_examples;

    rpc rpc1 {
        input {
            leaf l1 {
                type string;
            }
	    leaf l2 {
                type string;
            }
        }

        output {
            leaf l3 {
                type uint16;
            }
            leaf l4 {
                mandatory true;
                type uint16;
            }
        }
    }
}
```
1. sysrepoctl -i rpc_examples.yang

2. rpc code(test_rpc_output_mandatory_true.c)
    Run executable:./test_rpc_output_mandatory_true /rpc_examples:rpc1
    `rc = sr_rpc_subscribe(session, "/rpc_examples:rpc1", rpc_cb, NULL, 0, 0, &subscription);`
```code
static int
rpc_cb(sr_session_ctx_t *session, const char *path, const sr_val_t *input, const size_t input_cnt,
        sr_event_t event, uint32_t request_id, sr_val_t **output, size_t *output_cnt, void *private_data)
{
    size_t i;

    (void)session;
    (void)event;
    (void)request_id;
    (void)private_data;

    printf("\n\n ========== RPC \"%s\" RECEIVED: =======================\n\n", path);
    for (i = 0; i < input_cnt; ++i) {
        print_val(&input[i]);
    }

    if (!strcmp(path, "/rpc_examples:rpc1")) {
        /* generate some output */
        *output = malloc(sizeof **output);
        *output_cnt = 2;

        (*output)[0].xpath = strdup("/rpc_examples:rpc1/l3");
        (*output)[0].type = SR_UINT16_T;
        (*output)[0].dflt = 0;
        (*output)[0].data.uint16_val = 3333;
	
	(*output)[1].xpath = strdup("/rpc_examples:rpc1/l4");
        (*output)[1].type = SR_UINT16_T;
        (*output)[1].dflt = 0;
        (*output)[1].data.uint16_val = 4444;
    }

    return SR_ERR_OK;
}
```

3. netopeer2-server -d -v1
    netopeer2-cli
    user-rpc --content /home/linux/rpc.xml (Trigger callback function)
    rpc.xml:
```xml
    <rpc1 xmlns="urn:rpc_examples">
	<l1>test1</l1>
	<l2>test2</l2>
    </rpc1>
```
netopeer2-cli log:
    cli_send_recv: Timeout for receiving a reply expired.
netopeer2-server log:
    [ERR]: NP: Failed to send an RPC (Operation not supported).
    [ERR]: SR: Callback event "rpc" with ID 1 processing timed out.
    [WRN]: SR: Event "rpc" with ID 1 priority 0 failed (Timeout expired).
    [ERR]: NP: Failed to send an RPC (User callback failed).
    **netopeer2-server: /home/linux/sysrepo-devel/src/shm_main.c:388: sr_shmmain_ext_print: Assertion `*((size_t *)ext_shm_addr) == wasted' failed.**

rpc code log:
    Application will subscribe to "/rpc_examples:rpc1" RPC.
 ========== LISTENING FOR RPC ==========
 ========== RPC "/rpc_examples:rpc1" RECEIVED: =======================

/rpc_examples:rpc1/l1 = test1
/rpc_examples:rpc1/l2 = test2
 **Error in `./test_rpc_output_mandatory_true': munmap_chunk(): invalid pointer: 0x00007fbfa40008f0** 
[test_rpc_output_config_false.txt](https://github.com/sysrepo/sysrepo/files/4379019/test_rpc_output_config_false.txt)

thanks!

**Comment by michalvasko** [comment]
Hi,
the whole problem is caused by your mistake, just change
```C
*output = malloc(sizeof **output);
```
to
```C
*output = calloc(2, sizeof **output);
```
and it will work. However, even after your callback crashes *netopeer2* should continue to work normally. This use-case has caused a bug to manifest, which should be fixed now.

Regards,
Michal

**Comment by xxyy0906** [comment]
Hi,
Sorry, I didn't expect such a low-level error, I will carefully review some of my questions in the future.

thanks!
