### ISSUE TITLE
[new sysrepo] Invalid first magic number byte "0x00"

### ISSUE THREAD

**Issue by gitter-runner** [sysrepo/sysrepo#1875]
Hi,
I have a stress test application that creates instances in a list, registers oper data and action callbacks for them, read data and invokes actions.
When I run three instances of them one of them fails:

```
$ ./test 1 &
$ ./test 2 &
$ ./test 3 &
killall -USR1 test

[ERR]: Invalid first magic number byte "0x00".
[ERR]: Failed to parse returned "operational" data.

```

All applications handle a dedicated instance set in a common list.
I attached the test application source.

[testc.txt](https://github.com/sysrepo/sysrepo/files/4374860/testc.txt)
[test1@2020-02-20yang.txt](https://github.com/sysrepo/sysrepo/files/4374873/test1%402020-02-20yang.txt)

libyang version: 1.0.146
sysrepo version: 1.4.26

Thanks!

**Comment by michalvasko** [comment]
Hi,
right, there was a data race when locks were being downgraded with no other thread expected to get the lock. Should be fixed, I had the 3 applications running for several minutes until a timeout occurred.

Regards,
Michal

**Comment by gitter-runner** [comment]
Thanks for the fix, it works!
