### ISSUE TITLE
Leafref problem

### ISSUE THREAD

**Issue by MickAbson** [sysrepo/sysrepo#1876]
Hi,
I failed to return data on the sysrepo API "oper_get_items". The application's callback function executes without error. But the server displays the following error and exits:
`[ERR]: LY: Leafref "/ietf-interfaces:interfaces/ietf-interfaces:interface/ietf-interfaces:name" of value "eth0" points to a non-existing leaf. (/o-ran-dhcp:dhcp/interfaces[interface='eth0']/interface)
[ERR]: SR: Leafref "/ietf-interfaces:interfaces/ietf-interfaces:interface/ietf-interfaces:name" of value "eth0" points to a non-existing leaf.
[ERR]: SR: Failed to parse returned "operational" data.
Segmentation fault`

Then the client is as follows：
`
> get --filter-xpath /o-ran-dhcp:*
nc ERROR: Session 1: SSH channel poll error (Socket error: disconnected).
cli_send_recv: Failed to receive a reply.
> `
How to solve this problem?

My code in the application is as follows：
![code](https://user-images.githubusercontent.com/49752884/77498058-b6858500-6e89-11ea-9dc8-dfead12f0e34.gif)

The model installed in sysrepo is as follows:
`
[root@rc224 /]# sysrepoctl -l
Sysrepo repository: /etc/sysrepo

Module Name                | Revision   | Flags | Owner     | Permissions | Submodules | Features                                                               
----------------------------------------------------------------------------------------------------------------------------------------------------------------
iana-crypt-hash            | 2014-08-06 | i     |           |             |            |                                                                        
iana-hardware              | 2018-03-13 | i     |           |             |            |                                                                        
iana-if-type               | 2017-01-19 | I     | root:root | 600         |            |                                                                        
ietf-crypto-types          | 2019-07-02 | I     | root:root | 600         |            |                                                                        
ietf-datastores            | 2017-08-17 | I     | root:root | 600         |            |                                                                        
ietf-dhcpv6-types          | 2018-01-30 | i     |           |             |            |                                                                        
ietf-hardware              | 2018-03-13 | I     | root:root | 600         |            |                                                                        
ietf-inet-types            | 2013-07-15 | i     |           |             |            |                                                                        
ietf-interfaces            | 2018-02-20 | I     | root:root | 600         |            | if-mib                                                                 
ietf-keystore              | 2019-07-02 | I     | root:root | 600         |            | keystore-supported                                                     
ietf-netconf               | 2013-09-29 | I     | root:root | 600         |            | writable-running candidate rollback-on-error validate startup url xpath
ietf-netconf-acm           | 2018-02-14 | I     | root:root | 600         |            |                                                                        
ietf-netconf-monitoring    | 2010-10-04 | I     | root:root | 600         |            |                                                                        
ietf-netconf-nmda          | 2019-01-07 | I     | root:root | 600         |            | origin with-defaults                                                   
ietf-netconf-notifications | 2012-02-06 | I     | root:root | 600         |            |                                                                        
ietf-netconf-server        | 2019-07-02 | I     | root:root | 600         |            | ssh-listen tls-listen ssh-call-home tls-call-home                      
ietf-netconf-with-defaults | 2011-06-01 | I     | root:root | 600         |            |                                                                        
ietf-origin                | 2018-02-14 | I     | root:root | 600         |            |                                                                        
ietf-ssh-common            | 2019-07-02 | i     |           |             |            |                                                                        
ietf-ssh-server            | 2019-07-02 | I     | root:root | 600         |            | local-client-auth-supported                                            
ietf-tcp-client            | 2019-07-02 | i     |           |             |            |                                                                        
ietf-tcp-common            | 2019-07-02 | I     | root:root | 600         |            | keepalives-supported                                                   
ietf-tcp-server            | 2019-07-02 | i     |           |             |            |                                                                        
ietf-tls-common            | 2019-07-02 | i     |           |             |            |                                                                        
ietf-tls-server            | 2019-07-02 | I     | root:root | 600         |            | local-client-auth-supported                                            
ietf-truststore            | 2019-07-02 | I     | root:root | 600         |            | truststore-supported x509-certificates                                 
ietf-x509-cert-to-name     | 2014-12-10 | I     | root:root | 600         |            |                                                                        
ietf-yang-library          | 2019-01-04 | I     | root:root | 600         |            |                                                                        
ietf-yang-metadata         | 2016-08-05 | i     |           |             |            |                                                                        
ietf-yang-types            | 2013-07-15 | I     | root:root | 600         |            |                                                                        
nc-notifications           | 2008-07-14 | I     | root:root | 600         |            |                                                                        
notifications              | 2008-07-14 | I     | root:root | 600         |            |                                                                        
o-ran-compression-factors  | 2019-07-03 | I     | root:root | 600         |            |                                                                        
o-ran-delay-management     | 2019-07-03 | I     | root:root | 600         |            | ADAPTIVE-RU-PROFILE                                                    
o-ran-dhcp                 | 2019-07-03 | I     | root:root | 600         |            |                                                                        
o-ran-file-management      | 2019-07-03 | I     | root:root | 600         |            |                                                                        
o-ran-hardware             | 2019-07-03 | I     | root:root | 600         |            |                                                                        
o-ran-laa-operations       | 2019-07-03 | I     | root:root | 600         |            |                                                                        
o-ran-module-cap           | 2019-07-03 | I     | root:root | 600         |            | LAA                                                                    
o-ran-operations           | 2019-07-03 | I     | root:root | 600         |            |                                                                        
o-ran-software-management  | 2019-07-03 | I     | root:root | 600         |            |                                                                        
om-offline-data-management | 2020-03-06 | I     | root:root | 600         |            |                                                                        
om-offline-data-test       | 2019-03-04 | I     | root:root | 600         |            |                                                                        
test-examples              |            | I     | root:root | 600         |            |                                                                        
yang                       | 2017-02-20 | I     | root:root | 600         |            |                                                                        

Flags meaning: I - Installed/i - Imported; R - Replay support; N - New/X - Removed/U - Updated; F - Feature changes`

The relevant model is as follows:
[yang-module.zip](https://github.com/sysrepo/sysrepo/files/4378813/yang-module.zip)

Test platform:
[root@rc224 /]# uname -a
Linux rc224 4.9.78-ltsi #5 SMP Fri Aug 23 10:31:51 CST 2019 armv7l GNU/Linux

version of sysrepo ,yang and netopper2:
`[root@rc224 /]# netopeer2-server -V
netopeer2-server 1.1.7
compile time: Feb 27 2020, 19:02:56

[root@rc224 /]# sysrepoctl -V
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.2 (SO v5.0.2)

[root@rc224 /dev/shm/bin]# ./yangre -v
yangre 1.6.7`

Regards,
Fizz

**Comment by michalvasko** [comment]
Hi,
right, this bug should be fixed in *sysrepo* 1.4.5 and higher.

Regards,
Michal
