### ISSUE TITLE
lock error

### ISSUE THREAD

**Issue by lin13051275755** [sysrepo/sysrepo#1878]
![image](https://user-images.githubusercontent.com/50852871/77630934-d2228580-6f86-11ea-8bef-284070f95ad8.png)
here why not  unlock

**Comment by michalvasko** [comment]
Hi,
right, the missing unlocks were added, thanks.

Regards,
Michal

**Comment by lin13051275755** [comment]
yes;
sr_shmsub_change_notify_change_update and sr_shmsub_oper_notify; 
has same error：cleanup_wrunlock ond  cleanup_rdunlock

**Comment by michalvasko** [comment]
Okay, those were added, too.

Regards,
Michal
