### ISSUE TITLE
Leaf not found when sending notify data containing leafref

### ISSUE THREAD

**Issue by xxyy0906** [sysrepo/sysrepo#1879]
Hi:
    When I tested the notification, I found that when the notification contains the leafref definition, the notification still cannot be sent even if there is data in the path.My purpose is to be able to send notifications successfully.
    Here are 2 yang modules:
    ---test-module.yang
```yang
    module test-module {
    yang-version 1.1;
	namespace "urn:test-module";
    prefix test-module;
	
	container tests {
        list test {
            key 'name';
            min-elements 1;
            leaf name {
                type string{
                length "1..64";
                }
            }
		leaf type {
                type string{
                length "1..64";
                }
            } 
        }
    }
}
```
 ---notify-leafref-test.yang
```yang
module notify-leafref-test {
    namespace "urn:notify-leafref-test";
    prefix notify-leafref-test;

    import test-module {
        prefix test-module;
    }

    notification notification-examples {
        container c {
		leaf c-id {
            	type uint16;
        	}
            leaf c-name {
		type leafref {
		    path '/test-module:tests/test-module:test/test-module:name';
		}
	    }
        }
    }
}
```

1. install yang module
    sysrrpoctl -i test-module.yang
    sysrepocfg -W test-module.xml -m test-module -f xml
    sysrrpoctl -i notify-leafref-test.yang
---test-module.xml:
```xml
<tests xmlns="urn:test-module">
    <test>
        <name>test-name</name>
        <type>test-type</type>
    </test>
</tests>
```

2. run netopeer2-server and netopeer2-cli
    In netopeer2-cli:
        > get --filter-xpath /test-module:*
        DATA
```xml
<tests xmlns="urn:test-module">
  <test>
    <name>test-name</name>
    <type>test-type</type>
  </test>
</tests>
```
Now find data in **path '/test-module:tests/test-module:test/test-module:name';**
Subscribe to it now through netopeer2-cli:
    > subscribe --filter-xpath /notify-leafref-test:notification-examples
OK

3. Send notification(notify-leafref-test_send.c)
```code
        sr_val_t *notif1 = NULL;
	sr_val_t values[2];
	memset(values,0,sizeof(values));

	values[0].xpath = strdup("/notify-leafref-test:notification-examples/c/c-id");
	values[0].type = SR_UINT16_T;
	values[0].data.uint16_val = 1;

	values[1].xpath = strdup("/notify-leafref-test:notification-examples/c/c-name");
	values[1].type = SR_STRING_T;
	values[1].data.string_val = strdup("test-name");
	
	rc = sr_dup_values(values, 2, &notif1);
	rc = sr_event_notif_send(session, "/notify-leafref-test:notification-examples", notif1, 2);
```
error log:
**[ERR]: Leafref "/test-module:tests/test-module:test/test-module:name" of value "test-name" points to a non-existing leaf. (path: /notify-leafref-test:notification-examples/c/c-name)
[ERR]: Notification validation failed.**
[notify-leafref-test_send.txt](https://github.com/sysrepo/sysrepo/files/4391747/notify-leafref-test_send.txt)

thanks!

**Comment by xxyy0906** [comment]
Hi:
    I tried again, added the module subscription function of path in leafref, and now it can be sent successfully;code:
```code
sr_val_t *notif1 = NULL;
sr_val_t values[2];
memset(values,0,sizeof(values));

values[0].xpath = strdup("/notify-leafref-test:notification-examples/c/c-id");
values[0].type = SR_UINT16_T;
values[0].data.uint16_val = 1;

values[1].xpath = strdup("/notify-leafref-test:notification-examples/c/c-name");
values[1].type = SR_STRING_T;
values[1].data.string_val = strdup("test-name");	
**rc = sr_module_change_subscribe(session, "test-module", NULL, module_change_acc_devm_cb, NULL, 0, 0, &subscr);**	
rc = sr_dup_values(values, 2, &notif1);
rc = sr_event_notif_send(session, "/notify-leafref-test:notification-examples", notif1, 2);
```
Is my operation correct?

thanks!

**Comment by michalvasko** [comment]
Hi,
for testing purposes it is fine, I suppose. But in an actual application the value should really be [in-use](https://tools.ietf.org/html/rfc8342#section-5.3).

Regards,
Michal

**Comment by xxyy0906** [comment]
Hi:
    I'm sorry I don't quite understand what you mean, do you mean that the above problems will not occur in actual use?But my test above can't send notify without adding subscription function.

thanks!

**Comment by michalvasko** [comment]
Hi,
what I mean is that you were not able to send the notification because the leafref value was missing from your `operational` datastore so you simply created a subscription for its target before sending the notification. In other words, you treated it as a formal requirement so you "hacked" it just so that it does what you want. Like I said, this is fine for some test use-cases.

But the requirement is not just a formal one but a part of NMDA that tries to model real systems and their configuration. Ideally, you should fully conform to the specification, which says that you cannot send a notification with a leafref to a value that is not included in a device configuration/state data. To understand what I am talking about you need to be familiar with the [NMDA RFC](https://tools.ietf.org/html/rfc8342) that I referenced.

Regards,
Michal

**Comment by xxyy0906** [comment]
Hi:
Can i understand it like this?
1.You mean notify is not allowed to send leafref to the device?
2.Obviously the leafref value, I wrote to the big sysrepo database through test-module.xml.

thanks!

**Comment by michalvasko** [comment]
It is possible you have it correctly but I am not able to tell from the small application you posted. Anyway, I am sorry but I do not have time to continue explaining this to you. Maybe I should not even have attempted to, never mind.

Regards,
Michal

**Comment by xxyy0906** [comment]
Hi,
    I'm sorry to disturb you. I write the leafref data through 'sysrepocfg -W test-module.xml -m test-module -f xml'. I used 'get --filter-xpath /test-module:*' to get the data. I think leafref should have data at this time, so I sent a notif. I hope you can test it when you have time This use case.Sorry again.
 
thanks!

**Comment by xxyy0906** [comment]
Hi,
I apologize for the stupid behavior that caused you trouble,I don't think I fully understand  NMDA RFC and my operation is actually wrong,Causes the above problem because the operational data does not exist,I think I should subscribe to the running data so that the operational data exists, and then send a notification.sorry again.

thanks!

**Comment by michalvasko** [comment]
Okay, that is what I meant. Subscribing to the running data because you actually use them and not just because you want them in `operational` so that you can send the notification.

Regards,
Michal
