### ISSUE TITLE
Follow up on Data migration

### ISSUE THREAD

**Issue by jjin62** [sysrepo/sysrepo#1881]
Hi,
I looked https://github.com/sysrepo/sysrepo/issues/1342
it says migration is supported now. Can you provide some descriptions on how to handler in these scenarios? 
- a new node is added in new yang model (this seems fine)
- a node is removed  in new yang model (old data import would fail)
- change yang structure  in new yang model (old data import would fail)

thanks,
Jimmy

**Comment by michalvasko** [comment]
Hi Jimmy,
it was implemented as pragmatically as possible. Meaning whatever data of the module you currently have are taken and tried to be loaded with the updated module. If it succeeds, the whole module update succeeds. That means that even if you remove a node or completely change part of the module, as long as you do not have these data set, the update will succeed. The only formal requirement is the new module having a newer revision than the old one.

Regards,
Michal

**Comment by jjin62** [comment]
Thanks Michael for the info.
