### ISSUE TITLE
Failing commit RPC

### ISSUE THREAD

**Issue by ChinmayaAgarwal** [sysrepo/sysrepo#1882]
If we have an application subscribing to a sysrepo module. If "edit-config" is executed followed by "commit" and if any error occurs in the application, is it possible to show that error as rpc error reply on netconf client?

**Comment by michalvasko** [comment]
Hi,
yes, using `sr_set_error()` you should be able to return an error, which is passed to the NETCONF client in case the request came from one.

Regards,
Michal
