### ISSUE TITLE
Is there a tool to generate c file from yang file？

### ISSUE THREAD

**Issue by li9270** [sysrepo/sysrepo#1883]
Hello, I see the example of oven.yang and oven.c .
If I write a example.yang, need I write example.c by myself? I remember the netopeer1 have a lnctool to gegerate c file, and then add rpc function. Is there similar tool in netopeer2?
Thanks a lot!

**Comment by ZhaoGuangYue1986** [comment]
libyang就是将yang模型转换成c结构的

**Comment by li9270** [comment]
谢谢，我先了解下libyang

**Comment by michalvasko** [comment]
Hi,
there is no such tool because *sysrepo* applications do not require specific function names or anything similar.

Regards,
Michal

**Comment by li9270** [comment]
Thank you!
