### ISSUE TITLE
always while 1；

### ISSUE THREAD

**Issue by lin13051275755** [sysrepo/sysrepo#1885]
![image](https://user-images.githubusercontent.com/50852871/78128480-99802180-7448-11ea-8776-a8c2e7fa28f2.png)
when a node have some mode；mode commit not one by one  in order；then whileing

**Comment by michalvasko** [comment]
Hi,
I do not understand what is your issue with the code. The top-level nodes in diff should be ordered and all the changes of one module follow after each other.

Regards,
Michal
