### ISSUE TITLE
checkout return vlaue

### ISSUE THREAD

**Issue by lin13051275755** [sysrepo/sysrepo#1886]
![image](https://user-images.githubusercontent.com/50852871/78135141-f7fecd00-7453-11ea-92f0-2345bee51c23.png)
![image](https://user-images.githubusercontent.com/50852871/78135212-1a90e600-7454-11ea-9014-ded0025ac059.png)

checkout return vlaue or not；（enabled_change_cb）

**Comment by michalvasko** [comment]
Hi,
I do not understand what you are saying, sorry.

Regards,
Michal
