### ISSUE TITLE
edit-config on leaf-list with default values not working

### ISSUE THREAD

**Issue by meghna-doshi** [sysrepo/sysrepo#1887]
Hi,
edit-config for addition of an entry to leaf-list is failing
Using sysrepo devel version 1.4.27.

```
<oven xmlns="urn:sysrepo:oven_leafref"
        xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0"
        xc:operation="merge">
    <oven_range>10</oven_range>
</oven>

```

Yang module snippet:
```
container oven {
        description "Configuration container of the oven.";

        leaf turned_on {
            description "Main switch determining whether the oven is on or off.";
            type boolean;
            default false;
        }

        leaf temperature {
            description "Slider for configuring the desired temperature.";
            type oven_temperature;
            default 0;
        }

        leaf model_ref {
                description "reference to the model instance";
                type leafref {
                        path "/oven_model:model/oven_model:name";
                        }
        }
        leaf-list oven_range {
                type uint32;
                default 1;
                default 2;
                default 3;
        }
}
```

Give following error at sysrepo:
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[INF]: NP: edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
[INF]: SR: No datastore changes to apply.
[INF]: SR: Finished processing "rpc" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 1 priority 0 succeeded.
[INF]: NP: Session 2: thread 4 event new RPC.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Session 14 (user "root") created.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 2 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 2 priority 0 (remaining 1 subscribers).
[INF]: NP: edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
[ERR]: LY: Insert request refers node (/oven_leafref:oven/oven_range[.='3']) that is going to be auto-deleted.
[ERR]: SR: Insert request refers node (/oven_leafref:oven/oven_range[.='3']) that is going to be auto-deleted.
[ERR]: SR: Applying operation "merge" failed.
[INF]: SR: Finished processing "rpc" event (callback fail) with ID 2 priority 0 (remaining 1 subscribers).

> [ERR]: SR: Insert request refers node (/oven_leafref:oven/oven_range[.='3']) that is going to be auto-deleted.

[WRN]: SR: Event "rpc" with ID 2 priority 0 failed (libyang error).
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 2: thread 1 event new RPC.
[INF]: NP: Session 2: thread 1 event reply error.

**Comment by michalvasko** [comment]
Hi,
okay, should work now.

Regards,
Michal

**Comment by meghna-doshi** [comment]
Hi Michal,
Yes it working fine now.
Thanks.
Regards,
Meghna
