### ISSUE TITLE
libyang error with sr_move_item()

### ISSUE THREAD

**Issue by gitter-runner** [sysrepo/sysrepo#1888]
Hi!

I had an issue with sysrepo, when I used the _sr_move_item()_ function. I just wanted to move an item before another item, but there was a libyang error ("_Node already exists._").

(Seems like _lyd_new_path()_ wasn't called with the _LYD_PATH_OPT_UPDATE_ flag?)

Could someone please check if it's working, or the issue was on my end?
It should be easily reproducible with any list, but if you need help, I can provide a YANG module and the XMLs.

libsysrepo version: 5.1.11
libyang version: 1.6.22

Thanks!

**Comment by michalvasko** [comment]
Hi,
please post the exact edit commands because this may be a feature rather than a bug.

Regards,
Michal

**Comment by gitter-runner** [comment]
The YANG file:

[test_yang.txt](https://github.com/sysrepo/sysrepo/files/4416259/test_yang.txt)


The first XML adds 3 items:

```
<?xml version="1.0" encoding="utf-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="">
  <edit-config>
    <target>
      <running/>
    </target>
      <nc:config xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
        <t:basics xmlns:t="urn:com:test">
            <t:books>
                <t:title>A</t:title>
            </t:books>
            <t:books>
                <t:title>B</t:title>
            </t:books>
            <t:books>
                <t:title>D</t:title>
            </t:books>
        </t:basics>
    </nc:config>
  </edit-config>
</rpc>
```

The second one inserts another item:

```
<?xml version="1.0" encoding="utf-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="">
  <edit-config>
    <target>
      <running/>
    </target>
      <nc:config xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
        <t:basics xmlns:t="urn:com:test">
            <t:books xmlns:yg="urn:ietf:params:xml:ns:yang:1"
                yg:insert="before" yg:key="[title='D']">
                <t:title>C</t:title>
            </t:books>
        </t:basics>
    </nc:config>
  </edit-config>
</rpc>
```

And the server calls sr_move_item() like this:
`sr_move_item(session, "/test:basics/books[title='C']", SR_MOVE_BEFORE, "[title='D']", nullptr, nullptr, 0); `

**Comment by michalvasko** [comment]
Hi,
I have sent these 2 edit-configs to the *netopeer2-server* and it worked exactly as expected so you must be doing something differently.

Regards,
Michal

**Comment by gitter-runner** [comment]
Hi,
Netopeer doesn't use sr_move_item(), but I wrote a simple test application that demonstrates the issue better. I attached the source.

[test_1888_c.txt](https://github.com/sysrepo/sysrepo/files/4425500/test_1888_c.txt)

Thanks!

**Comment by michalvasko** [comment]
Hi,
right, then it is like I said, it is a feature. Very briefly, all the changes are concatenated into one "edit" data tree and you are trying to change one node twice (create and then move), hence the error. If you still want to do this in a single edit, use `SR_EDIT_ISOLATE` flag for the move edit.

Regards,
Michal
