### ISSUE TITLE
Docker image update to latest release

### ISSUE THREAD

**Issue by XXAmethystXX** [sysrepo/sysrepo#1889]
Hi!

The sysrepo-netopeer2 docker image is not updated with the latest release (1.4.2).
Would it be possible to bump it?
I'm referring to this image on the Docker hub: https://hub.docker.com/r/sysrepo/sysrepo-netopeer2

Thank you.

**Comment by michalvasko** [comment]
Hi,
the image is maintained by @lpaulic.

Regards,
Michal

**Comment by lpaulic** [comment]
Hi,
I have updated the image [https://hub.docker.com/r/sysrepo/sysrepo-netopeer2](https://hub.docker.com/r/sysrepo/sysrepo-netopeer2) to the latest release on the sysrepo master branch.

Regards,
Luka

**Comment by hayashi-leo** [comment]
Hi Luka,

I got an error from docker build while using [https://hub.docker.com/r/sysrepo/sysrepo-netopeer2/dockerfile](url) to build image of most recent release (beyond Apr 2nd build).

The error states CMake looks for LibSSH 0.7.1, but the version it pull previously is 0.7.0.

CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LibSSH: Found unsuitable version "0.7.0", but required is at
  least "0.7.1" (found /usr/include)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
  CMakeModules/FindLibSSH.cmake:113 (find_package_handle_standard_args)
  CMakeLists.txt:153 (find_package)

-- Configuring incomplete, errors occurred!
See also "/opt/dev/libnetconf2/build/CMakeFiles/CMakeOutput.log".
See also "/opt/dev/libnetconf2/build/CMakeFiles/CMakeError.log".
The command '/bin/sh -c git clone -b devel https://github.com/CESNET/libnetconf2.git &&       cd libnetconf2 && mkdir build && cd build &&       git checkout devel &&       cmake -DCMAKE_BUIL
D_TYPE:String="Debug" -DENABLE_BUILD_TESTS=OFF .. &&       make -j2 &&       make install &&       ldconfig' returned a non-zero code: 1

Should I use [https://github.com/sysrepo/sysrepo/blob/master/deploy/docker/sysrepo-netopeer2/Dockerfile](url) instead?

Thanks,

Leo;

**Comment by lpaulic** [comment]
Hi @XXAmethystXX,
I would suggest that you use the Dockerfile provided in the sysrepo repository in the deploy/docker/sysrepo-netopeer2 directory.
The one on the DockerHub is outdated. I have submitted a pull request that with the updates of the Dockerfile and Dockerfile.devel files and the above mentioned error should be resolved now.

After the pull request is resolved and the changes are merged I will update the docker image on DockerHub so it contains the newest release of sysrepo and netopeer2

Best regards,
Luka

**Comment by XXAmethystXX** [comment]
Thank you @lpaulic!

Best regards.
