### ISSUE TITLE
Set using Data_Node

### ISSUE THREAD

**Issue by ghost** [sysrepo/sysrepo#1890]
While setting the notifications, I am getting the following error..
Unfortunate Exception: Failed to find "notifications" as a sibling to "<module-name>group_xyz".
Not sure how its finding the group name as a sibling to the notifications.

YANG:
```
module: module1
  augment /module2:inner-container:
    +--rw cont1  
       + cont2 =======> This is present as part of a group.
  notifications:
    +---n notif-ovn	
```   
Code:       
```
        context = session.get_context()
        mod = context.get_module(module)     
        parent = sysrepo.Data_Node(None,mod, "notifications")
        notif = sysrepo.Data_Node(parent, mod, "notif-ovn", "abc")
```
How to fill the data in this case ?

**Comment by michalvasko** [comment]
Hi,
I believe you misunderstood the `tree` output. It is divided into categories, first is data, then other like *rpcs* or *notifications* follow, they are not actual nodes in the module. Meaning you should be fine with just
```C++
notif = sysrepo.Data_Node(nullptr, mod, "notif-ovn", nullptr);
```
You cannot set a value to the notification itself either, only to its descendants as long as it has any with values (leaves or leaf-lists).

Regards,
Michal

**Comment by Sneha-star** [comment]
Hi Michal.

Thank you.
