### ISSUE TITLE
python API doc

### ISSUE THREAD

**Issue by change-my-username** [sysrepo/sysrepo#1892]
Is there any python API (bindings) documentation for sysrepo? I found nothing(( Could you help me please

**Comment by michalvasko** [comment]
Hi,
there is a documentation (which are simply links to C functions) but it was not generated. It should be now and you can directly browse it [here](https://netopeer.liberouter.org/doc/sysrepo/devel/group__classes.html).

Regards,
Michal

**Comment by change-my-username** [comment]
Thanks a lot!
