### ISSUE TITLE
Configuration import from get-config xml causes invalid data

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1893]
Hi, 

Due to any NACM rule if some data is not present in get config output.

Import it back to system causing deletion of nodes or some times causes errors saying mandatory nodes are being deleted.

Is there any way to handle this?

Merging may not be an option, as there is a chance of user changes some data and wants to revert to backed up data.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
I am not sure what to tell you, I think this is simply a feature and this behavior is generally desired. I think you will have to make sure you get the whole configuration if you plan to import it later.

Regards,
Michal
