### ISSUE TITLE
support old glibc

### ISSUE THREAD

**Issue by MruRhe** [sysrepo/sysrepo#1894]
Dear sysrepo team,

I would like to build and link sysrepo (Linking C executable sysrepocfg) on an old system with no support for:

sysrepo/src/executables/sysrepocfg.c:267: undefined reference to `mkstemps'

configured with:

export CMAKE_PREFIX_PATH=/xyz/libyang/build/inst/usr/

DIR=$(pwd)/inst
mkdir -p $DIR
export DESTDIR=$DIR
cmake   -DCMAKE_INSTALL_PREFIX="/usr" \
        -DPLUGINS_PATH=$DIR/usr/sysrepo/plugins \
        -DCMAKE_VERBOSE_MAKEFILE=TRUE \
        ../

Thx in advance for an implementation/workaround of the mkstemps function!

**Comment by michalvasko** [comment]
Hi,
please try it now, `mkstemp` should be used instead if `mkstemps` is not available.

Regards,
Michal

**Comment by MruRhe** [comment]
Thx a lot the build works without errors now!
