### ISSUE TITLE
sysrepo support on QNX platform

### ISSUE THREAD

**Issue by apropp-molex** [sysrepo/sysrepo#1898]
Hi,

I'd like to port sysrepo over to QNX. Below I've summarized the issues in no particular order. Let me know if you want more details for any of these issues. Aside from issue 4, I can submit patches for the rest. If you do want patches, how would you want them divided?

1. Linking `librt` is not necessary on QNX, see `target_link_libraries(sysrepo rt)` in `CMakeLists.txt`.
2. Linking `libdl` is not necessary on QNX, see `target_link_libraries(sysrepo-plugind sysrepo dl)` in `CMakeLists.txt`.
3. Some C files which have functions such as sleep, strdup and others require the feature test macro `#define _XOPEN_SOURCE 500` to be compiled correctly, since the `-std=c99` flag is used. The `__QNXNTO__` can be used to recognize the qcc compiler specifically. The files are: `application_changes_example.c`, `notif_subscribe_example.c`, `oper_data_example.c`, `rpc_subscribe_example.c`, `oven.c`, `sysrepo-plugind.c`, `sysrepoctl.c` and `sysrepocfg.c`.
4. `strndup`, `vdprintf`, `asprintf` and `vasprintf` aren't provided in QNX. Would it be possible to provide a `compat.c` similar to this [commit](https://github.com/CESNET/libyang/commit/0c5ec1bf4a0c7c49afe4f8b32951b105130c8177) in libyang? The affected files outside of the immediate src directory are: all in `src/executables` and `application_changes.c`.
5.  `vfork` called in `sysrepocfg.c` is defined in `#include <process.h>` on QNX.
6. On Linux `time_t` is defined as a `long int`. On QNX, it's defined as a `unsigned int`. Other than a couple of warnings at compile time, do you think this will affect anything?

**Comment by michalvasko** [comment]
Hi,
my feedback:
1. Okay, put it in to a patch, simple enough.
2. Should now be fixed and linked in a portable way.
3. I have found no requirements for `sleep()` and have added the macro for files with `strdup()`. Not sure what else should be required.
4. Done.
5. I have removed this call as its use is rather discouraged.
6. Please provide the corresponding errors and I think it can be fixed quite easily. Or simply put it into the patch.

Please, provide a pull request with additional changes and we can discuss them then.

Regards,
Michal

**Comment by apropp-molex** [comment]
Hi Michal,

Pertaining to issue 6, I've copy-pasted the warnings below:
```sh
/home/molex/sysrepo_qnx/src/lyd_mods.c: In function 'sr_lydmods_update_replay_support':
/home/molex/sysrepo_qnx/src/lyd_mods.c:2737:22: warning: format '%ld' expects argument of type 'long int', but argument 3 has type 'time_t {aka unsigned int}' [-Wformat=]
         sprintf(buf, "%ld", from_ts);

[ 27%] Building C object CMakeFiles/srobj.dir/src/shm_sub.c.o
/home/molex/sysrepo_qnx/src/shm_sub.c: In function 'sr_shmsub_notif_listen_module_get_stop_time_in':
/home/molex/sysrepo_qnx/src/shm_sub.c:2833:37: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
     if ((next_stop_time - cur_time) < 0) {
                                     ^
```

**Comment by michalvasko** [comment]
Okay, the warnings should be fixed (and the second one was an actual error).

Regards,
Michal

**Comment by apropp-molex** [comment]
Hi Michal,

Sorry for the delay. I've created a PR for the librt issue. Let me know your thoughts.
Anyways there's an `asprintf` call in `application_changes_example.c` that is implicitly defined even with the compat object.
With regards to `sleep`, it's feature flag in QNX is `__EXT_POSIX1_198808`. In turn, this feature flag can be activated by one of `_QNX_SOURCE`, `_POSIX_SOURCE`, `_XOPEN_SOURCE` (any value) or `_POSIX_C_SOURCE`. Their documentation isn't exactly clear on this. Had to poke around a few header files. I imagine this due to excessive POSIX compliance. Do you have a preference as to which of the four feature flags to use?
Again thanks for your efforts so far.

**Comment by apropp-molex** [comment]
Hi Michal,

I just realized one more issue. However it's more generic to 32-bit systems. In `edit_diff.c`, a warning is raised about using a uint64 as a pointer (which could lead to issues in a 32-bit system). Thoughts?

```sh
[ 15%] Building C object CMakeFiles/srobj.dir/src/edit_diff.c.o
/home/molex/sysrepo_qnx/src/edit_diff.c: In function 'sr_diff_find_oper':
/home/molex/sysrepo_qnx/src/edit_diff.c:2080:29: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
                 *conn_ptr = (void *)conn_attr->value.uint64;
```

**Comment by michalvasko** [comment]
Hi,
as for the first problem, maybe it would be best to include `_QNX_SOURCE` so that it is obvious it is the requirement of only that platform.

For the second one, I wanted to fix it but somehow forgotten about it, so please try it now, whether the warning disappeared.

Regards,
Michal

**Comment by apropp-molex** [comment]
Hi Michal,

Added the `_QNX_SOURCE` feature flags for sleep in the above PR.
The warning seems to have disappeared. Thanks for the fix.

**Comment by apropp-molex** [comment]
Closing this issue off as sysrepo built successfully for QNX. Thanks for your help!

**Comment by linepi** [comment]
Thanks
