### ISSUE TITLE
Data dump

### ISSUE THREAD

**Issue by ghost** [sysrepo/sysrepo#1900]
Hi Michal,
```C
notif_cb(...)
{
    lyd_node_leaf_list *notifNodes = (struct lyd_node_leaf_list *)notif;
    char *data = NULL;
    if(notifNodes != NULL)
    {
        lyd_print_mem(&data,notif,LYD_JSON, 0x01 |0x20);     
    }
}
```
Can i dump notification data like this ? It does not dump the data even if i was filling it up.
 "lyd_node_leaf_list" data type needs to be changed ?

**Comment by michalvasko** [comment]
Hi,
I do not see any problem so I am not sure why this would not work (except why are you using flags as numbers?). You get an empty (`NULL`) string?

Regards,
Michal

**Comment by Sneha-star** [comment]
Yes Michal. ..print( "notification data %s", data) does not print  any thing.

**Comment by michalvasko** [comment]
What do you mean filling it up? You made it seem like you are in a notification callback where you only read the notification. You create it before you send it with `sr_event_notif_send()` or `sr_event_notif_send_tree()`.

Regards,
Michal

**Comment by Sneha-star** [comment]
Yes..I meant while creating if I am not doing properly or something like that.
Since you also mention that it should dump the data. But I am not getting any string.
So wanted to know where it has gone wrong.

**Comment by michalvasko** [comment]
Well, I cannot really help you without reproducing it or at least having some more information. Can you post the code that creates the notification and sends it?

Regards,
Michal

**Comment by Sneha-star** [comment]
Hi Michal. Sure.
I had filled like this..
        ctx = session.get_context()
        parent = sysrepo.Data_Node(ctx, notif_xpath , None, sysrepo.LYD_ANYDATA_CONSTSTRING, 0)
        name = sysrepo.Data_Node(parent, mod, "app-name", "test")
        alias = sysrepo.Data_Node(parent, mod, "alias-name", "alias-test")
        ....
		..
	session.event_notif_send(parent)

**Comment by Sneha-star** [comment]
Just like we use sysrepocfg to dump data, what I can use for dumping the filled notification ?

**Comment by michalvasko** [comment]
Hi,
you can try
```C++
auto str = parent.print_mem(LYD_JSON, LYP_FORMAT);
```
before sending the notification, it should print it.

Regards,
Michal
