### ISSUE TITLE
Build issue during cmake configuration

### ISSUE THREAD

**Issue by igortern** [sysrepo/sysrepo#1901]
Hi,

sysrepo configuration now fails as below.

Regards,
Igor

CMake Warning (dev) at CMakeLists.txt:288 (message):
  Doxygen: to generate UML diagrams please install graphviz
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
CMake Error at CMakeLists.txt:176 (add_library):
  OBJECT library "srobj" contains:

    compat.c.o

  but may contain only sources that compile, header files, and other files
  that would not affect linking of a normal library.

CMake Error at CMakeLists.txt:176 (add_library):
  Only executables and non-OBJECT libraries may reference target objects.

-- Generating done
-- Build files have been written to: /home/igort/Perforce/OLT/aspen/main/build/host-sim/third_party/sysrepo/sysrepo-devel/build
third_party/sysrepo/CMakeFiles/sysrepo_1.4.2.dir/build.make:60: recipe for target 'third_party/sysrepo/.sysrepo_1.4.2_installed' failed
make[3]: *** [third_party/sysrepo/.sysrepo_1.4.2_installed] Error 1

**Comment by michalvasko** [comment]
Hi,
okay, please try it now. But I am going blind here because for some reason it all works with my `cmake` 3.17.0.

Regards,
Michal

**Comment by igortern** [comment]
Yep. Works now with cmake 3.9.6.
Thanks.
Regards,
Igor
