### ISSUE TITLE
using sysrepo python API without sudo

### ISSUE THREAD

**Issue by change-my-username** [sysrepo/sysrepo#1902]
I have error in my code here:

subscribe.module_change_subscribe(module_name, module_change_cb, None, private_data, 1, sr.SR_SUBSCR_DONE_ONLY)

Error is: System function call failed
But when I running this python script with sudo this error does not occur

Is there way to use it without sudo or I do smth wrong?

**Comment by michalvasko** [comment]
Hi,
well, the access right are always enforced. As [documented](https://netopeer.liberouter.org/doc/sysrepo/master/group__change__subs__api.html#ga9fc19731882299fe1864ccc20b9bd842), you need WRITE access to the module. You can check the permissions of every module by `sysrepoctl -l`.

Regards,
Michal

**Comment by change-my-username** [comment]
Hi Michal
Thanks for quick reply!
sysrepoctl -l says:

my_module |    |  I  |  celeno:celeno  |  666  |    |  

my_module is module that I pass to module_change_subscribe
The 666 permission provides write access to all

**Comment by michalvasko** [comment]
Okay, that seems fine so the problem with be with accessing something else but it is impossible to find out what based on that error. Are you not able to get a better message? It is generated in C and I would think it is passed to Python.

Regards,
Michal

**Comment by change-my-username** [comment]
I've set 
sr.Logs().set_stderr(4)
And I got
[ERR]: mkfifo() failed (Permission denied).
System function call failed

**Comment by michalvasko** [comment]
Then you do not have write access to the repository (the path to it is printed during `cmake` of *sysrepo*). By default you should have except maybe in some older version, what *sysrepo* version are you using?

Regards,
Michal

**Comment by change-my-username** [comment]
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.2 (SO v5.0.2)

**Comment by michalvasko** [comment]
Hi,
yes, it would point to your logged user not having access to the repository. You should know where that is so you can check it. When it is created by *sysrepo*, `777` should be set meaning all the permissions for all users.

Regards,
Michal

**Comment by change-my-username** [comment]
Well, It worked for me. chmod 777 -R sysrepo/
Thanks for your help Michal. 
Closing issue
