### ISSUE TITLE
Failed to open shared memory (Too many open files)

### ISSUE THREAD

**Issue by gitter-runner** [sysrepo/sysrepo#1903]
Hi,
I have an embedded system using new _sysrepo_. There are some lists (i.e. _ietf-interfaces_) which are handled by multiple applications,
therefore oper data callbacks are registered per instance using data xpath.

When I have many instances I run out of open file limit:

`[ERR] Failed to open shared memory (Too many open files).`

and the _sr_oper_get_items_subscribe()_ function returns System function call failed (3) error.

I figured out that there are many open files for oper data callbacks that causes the error:

```
$ ls -l /proc/`pidof app1`/fd
...
lrwx------ 1 user group 64 Apr    8 17:36 24 -> /dev/shm/srsub_ietf-interfaces.oper.932d670f
lrwx------ 1 user group 64 Apr    8 17:36 25 -> /dev/shm/srsub_ietf-interfaces.oper.96ebe9f7
lrwx------ 1 user group 64 Apr    8 17:36 26 -> /dev/shm/srsub_ietf-interfaces.oper.73ae3902
lrwx------ 1 user group 64 Apr    8 17:37 27 -> /dev/shm/srsub_ietf-interfaces.oper.f6978053
lrwx------ 1 user group 64 Apr    8 17:37 28 -> /dev/shm/srsub_ietf-interfaces.oper.d00d203c
lrwx------ 1 user group 64 Apr    8 17:37 29 -> /dev/shm/srsub_ietf-interfaces.oper.0cb0805f
...
```
Can you help me how can I solve it without increasing the open file limit?

Thanks!

**Comment by michalvasko** [comment]
Hi,
firstly, what limit are you reaching, the open files of a single process? But you are mentioning operational subscriptions, which require one segment for every subscription. Seeing as you have them all for a single module then only one subscription is required (as long as all the data are in one subtree, which is the case for `ietf-interfaces`). So, assuming you are providing only state data, just subscribe to `/ietf-interfaces:interfaces-state` and return all the data at once. You can still have it divided into separate functions. The only negative consequence of this solution should be that *sysrepo* will not be able to filter out certain callbacks based on the requested XPath.

Regards,
Michal

**Comment by gitter-runner** [comment]
Hi,
I have config false leaves under /ietf-interfaces:interfaces/interface, many of them comes from standard models therefore I cannot move them to /ietf-interfaces:interfaces-state.
I cannot register one callback per instance here because it contains config true nodes as well.

I reach the per process limit which is 1024 by default.

Thanks!

**Comment by michalvasko** [comment]
Okay, so what are all those 1024 file descriptors? You still must have close to 1000 individual operational subscriptions, are you sure there are none which could be grouped into a single subscription? Meaning they are part of the same state subtree. If not then I am sorry but there is nothing I can do to fix this. The subscriptions for one module could only use a single SHM file segment but that would needlessly limit concurrency.

Regards,
Michal
