### ISSUE TITLE
Question on evolution of leaf-list predicate in Change objects

### ISSUE THREAD

**Issue by andrei-pavel** [sysrepo/sysrepo#1905]
Hello,

I appreciate any answer.

I have a subscriber which records changes logged over the update callback.
It's important to the subscriber to know precisely what the leaves' data types are because it interacts with data from other sources and the data types need to match.
Changed leaf-lists are being reported by my custom parser as being the underlying type e.g. string.
Because of this, I end up with a single value at that location instead of a leaf-list.
Before, I was relying on a hardcoded list of xpaths that were of leaf-list types to detect this and I was comparing each changed xpath to all of these, it was not pretty.
But... code that I've modified on the 19th of December 2019 suggests that detecting if a node is a leaf-list or a string could be done by inspecting the xpath and checking if the xpath had a predicate with a dot i.e. `.` as key.
This is backed up by current tests that have xpaths like this `"/test:cont/ll2[.='1']"`.
But... Using devel version of sysrepo seems to not yield these type of xpaths while master does.
Will this be changed in the future master version of sysrepo?

Thank you,
Andrei

**Comment by michalvasko** [comment]
Hi Andrei,
you are right, this was changed based on a request because the legacy *sysrepo* did not use any predicates for `leaf-list`. So, if you need this information, simply use the `*_tree()` API variants that provide all the information about the values and you will have no problem.

Regards,
Michal

**Comment by andrei-pavel** [comment]
Well, requester of this change, if you're reading this, I will let you know that quality progress and backwards compatibility often come in conflict. Is it really worth sacrificing the former? Moreover after the latter has already been compromised?

Michal, I'm looking at the `*_tree()` API and it looks like I need to switch from using `Change` objects to `Tree_Change` objects. If so, I would also have access to the `Data_Node` object. Am I on the right path?

From then on, as a checklist for myself, I would need to retrieve:
- operation
- old value
- new value
- value xpaths
- value types with differentiation between leaf and leaf-list

**Comment by michalvasko** [comment]
Hi,
my strategy was to keep full backwards compatibility where it was possible and in this case I simply did not realize that the predicate was not there before. Also, especially for cases where you have the option to use the new *libyang* tree-based API, you should simply always do that because it is better in every way except being a bit more complex to use (as an unavoidable consequence of providing much more information).

So you are right, you use `Tree_Change` objects and then work with *libyang* `Data_Tree` objects. But, your code overall should not really need to change much to retrieve the same information and getting the new values from `Data_Tree` objects is the most difficult task I think.

Regards,
Michal

**Comment by andrei-pavel** [comment]
Hello,
I'm in the process of migrating, code is in place, but I've hit a snag. Unto an empty configuration, I'm inserting a configuration with 311 leaves out of which 9 are logged succesfully, all lists except for one which is a top-level leaf. The top-level leaf is inserted from the ongoing session through code, that might be relevant.
In total I get 304 `!change->node()->attr()` and 313 `!change->prev_value()` null check errors. I assumed that's how I get new value and old value. The `!change->prev_value()` might be correct because previous configuration was empty, but should I not always have `change->node()->attr()`?
Best Regards!

**Comment by michalvasko** [comment]
Hi,
why exactly are you checking `node()->attr()`? Yes, in most cases there will be some attributes because that is how meta information is stored but the `Change` class has methods (getters) for all the relevant values so that is all you should be using.

Regards,
Michal

**Comment by andrei-pavel** [comment]
`change` in this case is of type `S_Tree_Change`.
The reasoning was that I switch from `Change` objects to `Tree_Change` objects so that I am able to check if the node is a leaf-list. Indeed I found that I am able to check through `change->node()->schema()->nodetype() == LYS_LEAFLIST`. I found no getters in `Tree_Change` so I went on digging.
I though about running `Iter_Change` and `Tree_Iter_Change` simultaneously, but I'm afraid they will get desynchronized/skewed.
These are problems I started having after the removal of differential dotted-key leaf-list xpaths. :(

**Comment by michalvasko** [comment]
Hi,
right, I meant `Tree_Change` class, not `Change`.

But I am still not sure what the problem is. You pasted the code for checking the leaf type, it is correct. And to get its value (valid only for `LYS_LEAF` and `LYS_LEAFLIST`), do
```C++
libyang::Data_Node_Leaf_List node(change->node());
cout << node.value_str();
```
You must use *libyang* API, which is, unfortunately, quite clunky. But we are active working on improving it. It will take some time, though.

Regards,
Michal

**Comment by andrei-pavel** [comment]
Hi,

- That cast is not at all obvious.
- The equivalent C++ code that I expected:
```
        if (libyang::S_Data_Node_Anydata anydata_node =
                dynamic_pointer_cast<libyang::Data_Node_Anydata>(node)) {
            value_ = std::make_shared<sysrepo::Val>(anydata_node->value().str, type);
        } else if (libyang::S_Data_Node_Leaf_List leaf_list_node =
                       dynamic_pointer_cast<libyang::Data_Node_Leaf_List>(node)) {
            value_ = std::make_shared<sysrepo::Val>(leaf_list_node->value_str(), type);
        }
```
does not work, none of the if branches get entered ever, suggesting the Data_Node was not initialized with either Anydata or Leaf_List. Please put this issue in your backlog.
- So I switch to type-unsafe C libyang API and I write
```
        if (is_leaf_list_) {
            value_ = std::make_shared<sysrepo::Val>(
                ((lyd_node_leaf_list*)node->lyd_node)->value_str, type);
        } else {
            value_ = std::make_shared<sysrepo::Val>(
                ((lyd_node_anydata*)node->lyd_node)->value.str, type);
        }
```
but `node is a private member`
- So I switch to internal use type-unsafe C libyang API and I write
```
        if (is_leaf_list_) {
            value_ = std::make_shared<sysrepo::Val>(
                ((lyd_node_leaf_list*)node->C_lyd_node())->value_str, type);
        } else {
            value_ = std::make_shared<sysrepo::Val>(
                ((lyd_node_anydata*)node->C_lyd_node())->value.str, type);
        }
```
and it works
- But before this I also need to get the type so I write
```
    if (is_leaf_list) {
        return convert(((lyd_node_leaf_list*)node->C_lyd_node())->value_type);
    } else {
        return convert(((lyd_node_anydata*)node->C_lyd_node())->value_type);
    }
```
and for the first encountered node which is a boolean leaf, I get `LYD_ANYDATA_CONSTSTRING`. It's not helpful.

So what do I do now? I can't ignore the type and use `sr_set_item_str()` as you have suggested to me in the past. I need the type to convert to another data structure before `sr_set`ing.

This is how I did it before:
```
 static std::array<std::regex, 6> leaf_list_xpaths{                                                                                                            
     std::regex("/+masters\\[.*\\]/+shards\\[.*\\]/+shard-config/+Dhcp[4|6]/+hooks-libraries\\[.*\\]/+"                                                        
                ".*parameters/+config/+classification-group/+encoded-options"),                                                                                
     std::regex("/+masters\\[.*\\]/+shards\\[.*\\]/+shard-config/+Dhcp[4|6]/+hooks-libraries\\[.*\\]/+"                                                        
                ".*parameters/+config/+lawful-interception-classes"),                                                                                          
     std::regex("/+masters\\[.*\\]/+shards\\[.*\\]/+shard-config/+Dhcp[4|6]/+hooks-libraries\\[.*\\]/+"                                                        
                ".*parameters/+config/+library-classes"),                                                                                                      
     std::regex("/+masters\\[.*\\]/+shards\\[.*\\]/+shard-config/+Dhcp[4|6]/+hooks-libraries\\[.*\\]/+"                                                        
                ".*parameters/+config/+network-topology/+zones\\[.*\\]/+allocation-group/+groups\\[.*\\]/+"                                                    
                "encoded-options"),                                                                                                                            
     std::regex("/+masters\\[.*\\]/+shards\\[.*\\]/+shard-config/+Dhcp[4|6]/+hooks-libraries\\[.*\\]/+"                                                        
                ".*parameters/+config/+network-topology/+zones\\[.*\\]/+routers\\[.*\\]/+ports\\[.*\\]/+"                                                      
                "user-ports\\[.*\\]/+subnets"),                                                                                                                
     std::regex("/+masters\\[.*\\]/+shards\\[.*\\]/+master-config\\[.*\\]/+server-config/+Dhcp[4|6]/+"                                                         
                "interfaces-config/+interfaces")}; 
```
a list of regexes that match xpaths of all leaf-lists in my models
And for each and every changed node I compare it's xpath to each and every regex in the list to see if it's a leaf-list.
Could use some guidance, otherwise I will fall back to it.

Best Regards!

**Comment by andrei-pavel** [comment]
Hi,

So apparently `anydata` is a special YANG statement, not a generic node that holds anything, so then how do I get value and type for non-leaf-lists?

Regards!

**Comment by michalvasko** [comment]
Hi,
I have never said the cast was obvious, that is why I included it in my reply and it is also in [one](https://github.com/CESNET/libyang/blob/master/swig/cpp/examples/process_tree.cpp#L79) of the examples.

Now, I still do not really understand the problem you are having. My understanding is that you are simply trying to read the basic information from every node returned by `change->node()`. In that case you should simply follow the leaf example. I would expect a `switch` statement on `change->node()->schema()->nodetype()`. In each branch you should cast the node into the appropriate specific node such as
```C++
switch (change->node()->schema()->nodetype()) {
case LYS_LEAF:
case LYS_LEAFLIST:
  libyang::Data_Node_Leaf_List node(change->node());
  break;
case LYS_ANYXML:
case LYS_ANYDATA:
  libyang::Data_Node_Anydata node(change->node());
  break;
case LYS_LIST:
case LYS_CONTAINER:
  libyang::Data_Node node(change->node());
  break;
}
```
and then simply use the methods (mostly getters) of those classes to get what you need. All the information should be available this way. These casts are also mentioned in the C headers ([here](https://github.com/CESNET/libyang/blob/master/src/tree_data.h#L208) and [here](https://github.com/CESNET/libyang/blob/master/src/tree_data.h#L271)) but I understand it may not be that easy to find. So, this example code should basically be all that you need.

Regards,
Michal

**Comment by andrei-pavel** [comment]
Hi,
Has syntax returned to the dotted-key xpath? I see `interfaces-config/interfaces[.='ens4/2003::']` in my logs.
Regards!

**Comment by michalvasko** [comment]
Hi,
you mean whether leaf-lists have their values in a predicate in `sr_val_t` `xpath`? No, they do not so I am not sure what you mean.

Regards,
Michal

**Comment by andrei-pavel** [comment]
Hi,
leaf-lists don't have their values in a `sr_val_t` xpath predicate, but they do in a `lyd_node` xpath predicate. This is inconsistent, but I guess it's useful for you somewhere along the way.
We are currently using both for different modules, that's why I got confused, but will migrate to `lyd_node` for all modules in the future.
If this is not what you are experiencing or if you plan to change this, let me know. You know my stance, I prefer the value in the predicate.

**Comment by andrei-pavel** [comment]
Thank you for the help! I was able to detect leaf-lists through the libyang API and even more so in two ways, not only one.

Kind regards!

**Comment by michalvasko** [comment]
> leaf-lists don't have their values in a sr_val_t xpath predicate, but they do in a lyd_node xpath predicate

I believe we have already discussed this, the whole reason being backwards compatibility with legacy *sysrepo* to make the transition easier (so that you can still use `sr_val_t` in most cases and expect the same values).

Regards,
Michal
