### ISSUE TITLE
Cannot propagate error with sr_set_error()

### ISSUE THREAD

**Issue by iljatab** [sysrepo/sysrepo#1906]
$ yanglint --version
yanglint SO 1.7.0

$ sysrepoctl --version
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.33 (SO v5.3.0)

$ netopeer2-server -V
netopeer2-server 1.1.19
compile time: Apr  8 2020, 10:42:58

Hi,

It looks like the thing, used to work earlier, stopped working now.

We have a configuration callback, installed by sr_module_change_subscribe().
The callback, in case of application-specific error condition, sets a custom error like:
```
static int config_change_cb(sr_session_ctx_t* sess, const char* mod, const char *path,
                            sr_event_t ev,  uint32_t req_id, void* ctx)
{
  ...
    sr_set_error(sess, nullptr, "%s", msg);
    return SR_ERR_INTERNAL;
  ...
}
```

However in netopeer2-cli we cannot see the custom error message.
Instead a generic error is always displayed:

```
> edit-config --target candidate --config=./sample.xml
OK
> commit 
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  User callback failed

>
```

I remember this worked fine, maybe with sysrepo 0.7.x, maybe already with 1.x.
Did we miss something or is it a bug?
Maybe we have to return not SR_ERR_INTERNAL but some other value (which one)?

Ilja.

**Comment by michalvasko** [comment]
Hi Ilja,
it worked only for `edit-config` and a minor fix was needed for it to also work for `commit`, so please update *netopeer2* and try again. Should work now.

Regards,
Michal

**Comment by iljatab** [comment]
Thanks, looks working!
