### ISSUE TITLE
Setting a leafref with sysrepocfg set on an empty datastore fails.

### ISSUE THREAD

**Issue by nehajoy** [sysrepo/sysrepo#1908]
Hi,

I was trying to set a leafref using sysrepocfg set function. But this fails on an empty datastore whereas it works on datastore with valid configuration data. 

**Description**
I have two yang models "test1.yang" and "test2.yang", the second model test2.yang has one leafref that points to a leaf in the first yang model test1.yang.

~ # cat /tmp/test1.yang 
```yang
module test1 {
yang-version 1;
namespace "urn:ietf:params:xml:ns:yang:test1";
prefix test1;

organization
"XXX, Inc.";
contact
"XXX";
description
"Test1 Yang File";

revision 2020-04-03 {
description
"Initial Revision.";
}

leaf leaf1 {
type string;
description
"leaf1";
}

leaf leaf2 {
type string;
description
"leaf2";
}
}
```
~ # cat /tmp/test2.yang 
```yang
module test2 {
yang-version 1;
namespace "urn:ietf:params:xml:ns:yang:test2";
prefix test2;

import test1 {
prefix test1;
revision-date 2020-04-03;
}

organization
"XXX, Inc.";
contact
"XXX";
description
"Test2 Yang File";

revision 2020-04-03 {
description
"Initial Revision.";
}
container container1 {
description
"container1";
leaf leaf1 {
type leafref {
path "/test1:leaf1";
}
description
"leafref leaf";
}
}
}
```
First I tried to set the leaf in test1.yang. 
```
~ # sysrepocfg --set='/test1:leaf1' --set-value=abc --datastore=startup test1
The new configuration was successfully applied.
~ # cat /tmp/run/sysrepo/data/test1.startup
<leaf1 xmlns="urn:ietf:params:xml:ns:yang:test1">abc</leaf1>
```
Then I tried to set the leafref in test2.yang. The following error message was shown and configuration was not set.
```
~ # sysrepocfg --set='/test2:container1/leaf1' --set-value=abc --datastore=startup test2
Errors were encountered during importing. Cancelling the operation.
```
I tried to import a configuration with sysrepocfg import function. This works fine.
```
~ # cat config.xml 
<container1 xmlns="urn:ietf:params:xml:ns:yang:test2">
<leaf1>abc</leaf1>
</container1>
~ # 
~ # sysrepocfg --import=config.xml --format=xml --datastore=startup test2
The new configuration was successfully applied.
~ # cat /tmp/run/sysrepo/data/test2.startup
<container1 xmlns="urn:ietf:params:xml:ns:yang:test2">
  <leaf1>abc</leaf1>
</container1>
```
**Versions**
sysrepo-0.7.7

Regards,
Neha

**Comment by michalvasko** [comment]
Hi Neha,
it seems there is a problem with the set operation and you managed to work around it by using import, which worked correctly. As the *sysrepo* you are using is deprecated, I will not be fixing it, sorry.

Regards,
Michal

**Comment by nehajoy** [comment]
Thanks for replying. Need your help on another issue.

When I try to configure a value that does not exist in test1.yang, following error is shown.
`~ # sysrepocfg --set='/test2:container1/leaf1' --set-value=new --datastore=startup test2
[ERR] Commit operation failed with 1 error(s).
[ERR] Error returned from sr_commit: Validation of the changes failed.
[ERR] /test2:container1/leaf1 : Leafref "/test1:leaf1" of value "new" points to a non-existing leaf.`

This is expected result. But when I try to delete the existing value in test1.yang, similar error is shown.

`~ # sysrepocfg --del='/test1:leaf1' --datastore=startup test1
[ERR] Commit operation failed with 1 error(s).
[ERR] Leafref "/test1:leaf1" of value "abc" points to a non-existing leaf..
Unable to commit. Canceling the operation.
`

This error seems misleading. I would prefer a more meaningful error message to be shown when trying to delete the referred node. Is that possible ?

**Comment by michalvasko** [comment]
Hi Neha,
based on the errors it seems to me it is correct. You probably have `/test2:container1/leaf1` with value `abc`, which is a leafref to `/test1:leaf1` with the same value `abc`, so it is valid. In the first case you are trying to change `/test2:container1/leaf1` value to `new`, but that fails because there is no such target with the same value, what the error says exactly. In the second case you are trying to delete `/test1:leaf1` and you get another error, that the original `/test2:container1/leaf1` with the value `abc` now has no target. So you are prevented from making those changes because they would make the datastore invalid. That is the correct functionality.

Regards,
Michal

**Comment by nehajoy** [comment]
Thanks Michal.

Suppose I have one more yang with a leafref pointing to /test1:leaf1. When I try to delete the referenced node, the following error will be shown twice if both the referencing nodes have values in them.

`[ERR] Leafref "/test1:leaf1" of value "abc" points to a non-existing leaf.`

So if value has been set for only one referencing node, how can I understand which leafref is preventing the delete operation.

Thanks,
Neha

**Comment by michalvasko** [comment]
Hi Neha,
*libyang* should also provide information about the data note with the problem so that should identify it. However, it seems the legacy `sysrepocfg` does not print it so I can only suggest you use the current *sysrepo* and its tools, they should also print the path.

Regards,
Michal
