### ISSUE TITLE
Configuration callback: SR_OP_CREATED with default

### ISSUE THREAD

**Issue by iljatab** [sysrepo/sysrepo#1911]
$ yanglint --version
yanglint SO 1.7.0

$ sysrepoctl --version
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.33 (SO v5.3.0)

$ netopeer2-server -V
netopeer2-server 1.1.19
compile time: Apr 8 2020, 10:42:58

Hi,

It looks there is an issue that possibly could (or could not) be related to an already closed ticket:
"1756 sr_get_change_next() reports unmodified leafs SR_OP_MODIFIED"

Attached is a simplified YANG model - test-example.yang.
It has a top-level container with a list inside (likely not important) and a leaf ("tunnel-mac") with a default value.

At the start of the test there is **no** configuration data for test-example in sysrepo database.

Then we apply a configuration xml with data, **completely unrelated** to the test-example model. Say, we apply a configuration for openconfig-interfaces model:

```
[test-example.yang.gz](https://github.com/sysrepo/sysrepo/files/4468953/test-example.yang.gz)


> edit-config --target candidate --config=add-one-interface.xml
OK
> commit
...
```

Our callback for openconfig-interfaces gets called just fine.

However surprisingly also the callback for test-example gets called.
Iterating over changes in test-example (in the callback) we get following entries:

```
SR_OP_CREATED /test-example:test-example-object (container)
SR_OP_CREATED /test-example:test-example-object/tunnel-mac = 01:00:0C:CD:CD:D0 [default]
```
This doesn't look expected and breaks the application logic :-(

Note that we have a lot of leaves in many YANG models with default values and they work OK. However this is the only model which has a leaf with a default directly inside the top-level container. Maybe this makes a difference.

Could you please check?

Ilja.

**Comment by iljatab** [comment]
[test-example.yang.gz](https://github.com/sysrepo/sysrepo/files/4468957/test-example.yang.gz)

**Comment by iljatab** [comment]
Fixed in application.

**Comment by michalvasko** [comment]
Hi,
so it was a problem in your app and not in *sysrepo*, right?

Regards,
Michal

**Comment by iljatab** [comment]
Hi,

Yes, we handled this issue in our app code.
However I am not sure if this is or is not expected behavior of sysrepo.

From one side it is strange to get a callback call for a yang model that is
unrelated to edited data.

From other side it happens only on first edit-config/commit - maybe at that
point sysrepo creates the top-level container with a default leaf value.
In that case it looks reasonable.

BRGDS,

Ilja.

**Comment by michalvasko** [comment]
Hi Ilja,
okay, then I would say this is not supposed to happen based on your description, the default values should have been already created before. It would be best if I could reproduce it but maybe some additional information will be enough. What exactly is your setup? What modules do you have installed (`sysrpeoctl -l`), what subscriptions (exact XPaths), what data set?

Regards,
Michal

**Comment by iljatab** [comment]
Hi Michal,

Please find attached the "sysrepoctl -l" output.
The system starts with an empty startup configuration database (except for
netconf configuration itself).
The YANG model in question is attached.
Subscription done like:
    sr_module_change_subscribe(sess, "adva-dnos-l2cp", nullptr,
config_change_cb, 0, SR_SUBSCR_CTX_REUSE, &sub);
If needed I can reproduce the issue.

BRGDS,
Ilja.

On Tue, 14 Apr 2020 at 15:57, Michal Vasko <notifications@github.com> wrote:

> Hi Ilja,
> okay, then I would say this is not supposed to happen based on your
> description, the default values should have been already created before. It
> would be best if I could reproduce it but maybe some additional information
> will be enough. What exactly is your setup? What modules do you have
> installed (sysrpeoctl -l), what subscriptions (exact XPaths), what data
> set?
>
> Regards,
> Michal
>
>

Sysrepo repository: /etc/sysrepo

Module Name                       | Revision   | Flags | Owner     | Permissions | Submodules                                                                                                                       | Features                                                               
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
adva-dnos-ac                      | 2019-03-05 | I     | root:root | 600         |                                                                                                                                  |                                                                        
adva-dnos-ac-oam                  | 2019-09-05 | I     | root:root | 600         |                                                                                                                                  |                                                                        
adva-dnos-dummy                   | 2019-03-05 | I     | root:root | 600         |                                                                                                                                  |                                                                        
adva-dnos-elan                    | 2019-07-30 | I     | root:root | 600         |                                                                                                                                  |                                                                        
adva-dnos-eline                   | 2019-07-30 | I     | root:root | 600         |                                                                                                                                  |                                                                        
adva-dnos-extensions              | 2019-02-25 | i     |           |             |                                                                                                                                  |                                                                        
adva-dnos-hqos                    | 2019-07-15 | I     | root:root | 600         |                                                                                                                                  |                                                                        
adva-dnos-inet                    | 2019-03-05 | I     | root:root | 600         |                                                                                                                                  |                                                                        
adva-dnos-l2cp                    | 2019-07-15 | I     | root:root | 600         |                                                                                                                                  |                                                                        
adva-dnos-lags                    | 2019-03-03 | I     | root:root | 600         |                                                                                                                                  |                                                                        
adva-dnos-mpls-path               | 2019-07-22 | I     | root:root | 600         |                                                                                                                                  |                                                                        
adva-dnos-mpls-tunnel             | 2019-07-22 | I     | root:root | 600         |                                                                                                                                  |                                                                        
adva-dnos-mvlans                  | 2019-03-05 | I     | root:root | 600         |                                                                                                                                  |                                                                        
adva-dnos-network-instance        | 2019-09-17 | I     | root:root | 600         |                                                                                                                                  |                                                                        
adva-dnos-oam                     | 2019-09-05 | I     | root:root | 600         |                                                                                                                                  |                                                                        
adva-dnos-oc-interfaces           | 2019-03-28 | I     | root:root | 600         |                                                                                                                                  |                                                                        
adva-dnos-oob                     | 2019-03-05 | I     | root:root | 600         |                                                                                                                                  |                                                                        
adva-dnos-platform                | 2019-02-19 | I     | root:root | 600         |                                                                                                                                  |                                                                        
adva-dnos-pm                      | 2019-07-31 | I     | root:root | 600         |                                                                                                                                  |                                                                        
adva-dnos-ports                   | 2019-02-27 | I     | root:root | 600         |                                                                                                                                  |                                                                        
adva-dnos-routing-policy          | 2019-10-09 | I     | root:root | 600         |                                                                                                                                  |                                                                        
adva-dnos-sfp                     | 2019-08-19 | I     | root:root | 600         |                                                                                                                                  |                                                                        
adva-dnos-sys                     | 2019-07-25 | I     | root:root | 600         |                                                                                                                                  |                                                                        
adva-dnos-tag-manipulation        | 2019-07-08 | I     | root:root | 600         |                                                                                                                                  |                                                                        
adva-dnos-types                   | 2019-02-25 | i     |           |             |                                                                                                                                  |                                                                        
adva-dnos-vlans                   | 2019-03-05 | I     | root:root | 600         |                                                                                                                                  |                                                                        
bgp                               | 2015-12-02 | I     | root:root | 600         |                                                                                                                                  |                                                                        
ethernet-segment                  | 2017-03-16 | i     |           |             |                                                                                                                                  |                                                                        
iana-crypt-hash                   | 2014-08-06 | i     |           |             |                                                                                                                                  |                                                                        
iana-if-type                      | 2017-01-19 | I     | root:root | 600         |                                                                                                                                  |                                                                        
ieee802-dot1q-types               | 2016-09-22 | i     |           |             |                                                                                                                                  |                                                                        
ieee802-types                     | 2016-07-24 | i     |           |             |                                                                                                                                  |                                                                        
ietf-crypto-types                 | 2019-07-02 | I     | root:root | 600         |                                                                                                                                  |                                                                        
ietf-datastores                   | 2017-08-17 | I     | root:root | 666         |                                                                                                                                  |                                                                        
ietf-inet-types                   | 2013-07-15 | i     |           |             |                                                                                                                                  |                                                                        
ietf-interfaces                   | 2018-02-20 | I     | root:root | 600         |                                                                                                                                  |                                                                        
ietf-keystore                     | 2019-07-02 | I     | root:root | 600         |                                                                                                                                  | keystore-supported                                                     
ietf-netconf                      | 2013-09-29 | I     | root:root | 666         |                                                                                                                                  | writable-running candidate rollback-on-error validate startup url xpath
ietf-netconf-acm                  | 2018-02-14 | I     | root:root | 600         |                                                                                                                                  |                                                                        
ietf-netconf-monitoring           | 2010-10-04 | I     | root:root | 600         |                                                                                                                                  |                                                                        
ietf-netconf-nmda                 | 2019-01-07 | I     | root:root | 600         |                                                                                                                                  | origin with-defaults                                                   
ietf-netconf-notifications        | 2012-02-06 | I     | root:root | 666         |                                                                                                                                  |                                                                        
ietf-netconf-server               | 2019-07-02 | I     | root:root | 600         |                                                                                                                                  | ssh-listen tls-listen ssh-call-home tls-call-home                      
ietf-netconf-with-defaults        | 2011-06-01 | I     | root:root | 666         |                                                                                                                                  |                                                                        
ietf-origin                       | 2018-02-14 | I     | root:root | 666         |                                                                                                                                  |                                                                        
ietf-ssh-common                   | 2019-07-02 | i     |           |             |                                                                                                                                  |                                                                        
ietf-ssh-server                   | 2019-07-02 | I     | root:root | 600         |                                                                                                                                  | local-client-auth-supported                                            
ietf-tcp-client                   | 2019-07-02 | i     |           |             |                                                                                                                                  |                                                                        
ietf-tcp-common                   | 2019-07-02 | I     | root:root | 600         |                                                                                                                                  | keepalives-supported                                                   
ietf-tcp-server                   | 2019-07-02 | i     |           |             |                                                                                                                                  |                                                                        
ietf-tls-common                   | 2019-07-02 | i     |           |             |                                                                                                                                  |                                                                        
ietf-tls-server                   | 2019-07-02 | I     | root:root | 600         |                                                                                                                                  | local-client-auth-supported                                            
ietf-truststore                   | 2019-07-02 | I     | root:root | 600         |                                                                                                                                  | truststore-supported x509-certificates                                 
ietf-x509-cert-to-name            | 2014-12-10 | I     | root:root | 600         |                                                                                                                                  |                                                                        
ietf-yang-library                 | 2019-01-04 | I     | root:root | 666         |                                                                                                                                  |                                                                        
ietf-yang-metadata                | 2016-08-05 | i     |           |             |                                                                                                                                  |                                                                        
ietf-yang-types                   | 2013-07-15 | i     |           |             |                                                                                                                                  |                                                                        
interface                         | 2017-09-27 | I     | root:root | 600         |                                                                                                                                  |                                                                        
interfaces                        | 2015-10-09 | i     |           |             |                                                                                                                                  |                                                                        
isis                              | 2015-12-22 | I     | root:root | 600         |                                                                                                                                  |                                                                        
ldp                               | 2015-12-23 | I     | root:root | 600         |                                                                                                                                  |                                                                        
lfa                               | 2017-03-28 | i     |           |             |                                                                                                                                  |                                                                        
metaswitch-custom-yang-types      | 2018-03-09 | i     |           |             |                                                                                                                                  |                                                                        
metaswitch-features               | 2019-04-01 | i     |           |             |                                                                                                                                  |                                                                        
metaswitch-mpls                   | 2019-06-06 | I     | root:root | 600         |                                                                                                                                  |                                                                        
metaswitch-yang-types             | 2015-10-29 | i     |           |             |                                                                                                                                  |                                                                        
nc-notifications                  | 2008-07-14 | I     | root:root | 600         |                                                                                                                                  |                                                                        
notifications                     | 2008-07-14 | I     | root:root | 600         |                                                                                                                                  |                                                                        
openconfig-acl                    | 2018-11-21 | I     | root:root | 600         |                                                                                                                                  |                                                                        
openconfig-aft                    | 2019-08-01 | i     |           |             |                                                                                                                                  |                                                                        
openconfig-alarm-types            | 2018-11-21 | i     |           |             |                                                                                                                                  |                                                                        
openconfig-bgp                    | 2019-05-28 | i     |           |             |                                                                                                                                  |                                                                        
openconfig-bgp-policy             | 2019-02-01 | I     | root:root | 600         |                                                                                                                                  |                                                                        
openconfig-bgp-types              | 2018-11-21 | i     |           |             |                                                                                                                                  |                                                                        
openconfig-extensions             | 2018-10-17 | i     |           |             |                                                                                                                                  |                                                                        
openconfig-if-aggregate           | 2019-04-16 | I     | root:root | 600         |                                                                                                                                  |                                                                        
openconfig-if-ethernet            | 2019-04-16 | I     | root:root | 600         |                                                                                                                                  |                                                                        
openconfig-if-ethernet-ext        | 2018-11-21 | I     | root:root | 600         |                                                                                                                                  |                                                                        
openconfig-if-ip                  | 2019-01-08 | I     | root:root | 600         |                                                                                                                                  |                                                                        
openconfig-if-types               | 2018-11-21 | i     |           |             |                                                                                                                                  |                                                                        
openconfig-igmp                   | 2019-07-09 | i     |           |             |                                                                                                                                  |                                                                        
openconfig-igmp-types             | 2018-11-21 | i     |           |             |                                                                                                                                  |                                                                        
openconfig-inet-types             | 2019-04-25 | i     |           |             |                                                                                                                                  |                                                                        
openconfig-interfaces             | 2019-07-10 | I     | root:root | 600         |                                                                                                                                  |                                                                        
openconfig-isis                   | 2018-11-21 | i     |           |             |                                                                                                                                  |                                                                        
openconfig-isis-types             | 2018-11-21 | i     |           |             |                                                                                                                                  |                                                                        
openconfig-local-routing          | 2018-11-21 | i     |           |             |                                                                                                                                  |                                                                        
openconfig-mpls                   | 2019-03-26 | i     |           |             |                                                                                                                                  |                                                                        
openconfig-mpls-ldp               | 2019-07-09 | i     |           |             |                                                                                                                                  |                                                                        
openconfig-mpls-rsvp              | 2018-11-21 | i     |           |             |                                                                                                                                  |                                                                        
openconfig-mpls-types             | 2019-03-26 | i     |           |             |                                                                                                                                  |                                                                        
openconfig-network-instance       | 2019-05-14 | I     | root:root | 600         | openconfig-network-instance-l2                                                                                                   |                                                                        
openconfig-network-instance-l3    | 2018-11-21 | i     |           |             |                                                                                                                                  |                                                                        
openconfig-network-instance-types | 2018-11-21 | I     | root:root | 600         |                                                                                                                                  |                                                                        
openconfig-ospfv2                 | 2019-07-09 | I     | root:root | 600         | openconfig-ospfv2-global openconfig-ospfv2-area openconfig-ospfv2-area-interface openconfig-ospfv2-lsdb openconfig-ospfv2-common |                                                                        
openconfig-packet-match           | 2018-11-21 | i     |           |             |                                                                                                                                  |                                                                        
openconfig-packet-match-types     | 2018-11-21 | i     |           |             |                                                                                                                                  |                                                                        
openconfig-pim                    | 2019-07-09 | i     |           |             |                                                                                                                                  |                                                                        
openconfig-pim-types              | 2018-11-21 | i     |           |             |                                                                                                                                  |                                                                        
openconfig-platform               | 2019-04-16 | I     | root:root | 600         |                                                                                                                                  |                                                                        
openconfig-platform-cpu           | 2018-11-21 | I     | root:root | 600         |                                                                                                                                  |                                                                        
openconfig-platform-psu           | 2018-11-21 | I     | root:root | 600         |                                                                                                                                  |                                                                        
openconfig-platform-types         | 2019-06-03 | i     |           |             |                                                                                                                                  |                                                                        
openconfig-policy-forwarding      | 2018-11-21 | i     |           |             |                                                                                                                                  |                                                                        
openconfig-policy-types           | 2018-11-21 | i     |           |             |                                                                                                                                  |                                                                        
openconfig-rib-bgp                | 2019-04-25 | i     |           |             |                                                                                                                                  |                                                                        
openconfig-routing-policy         | 2018-11-21 | I     | root:root | 600         |                                                                                                                                  |                                                                        
openconfig-segment-routing        | 2018-11-21 | i     |           |             |                                                                                                                                  |                                                                        
openconfig-types                  | 2019-04-16 | i     |           |             |                                                                                                                                  |                                                                        
openconfig-vlan                   | 2019-04-16 | I     | root:root | 600         |                                                                                                                                  |                                                                        
openconfig-vlan-types             | 2019-01-31 | I     | root:root | 600         |                                                                                                                                  |                                                                        
openconfig-yang-types             | 2018-11-21 | i     |           |             |                                                                                                                                  |                                                                        
ospf-common                       | 2015-11-06 | i     |           |             |                                                                                                                                  |                                                                        
ospfv2                            | 2015-11-05 | I     | root:root | 600         |                                                                                                                                  |                                                                        
qos                               | 2018-03-03 | I     | root:root | 600         |                                                                                                                                  |                                                                        
redist                            | 2016-02-08 | i     |           |             |                                                                                                                                  |                                                                        
rip                               | 2016-09-09 | I     | root:root | 600         |                                                                                                                                  |                                                                        
routing                           | 2015-12-14 | I     | root:root | 600         |                                                                                                                                  |                                                                        
rsvp-te                           | 2017-03-07 | I     | root:root | 600         |                                                                                                                                  |                                                                        
user-extensions                   | 2016-02-17 | i     |           |             |                                                                                                                                  |                                                                        
yang                              | 2017-02-20 | I     | root:root | 666         |                                                                                                                                  |                                                                        

Flags meaning: I - Installed/i - Imported; R - Replay support; N - New/X - Removed/U - Updated; F - Feature changes

**Comment by iljatab** [comment]
[sysrepoctl-l.txt](https://github.com/sysrepo/sysrepo/files/4491675/sysrepoctl-l.txt)

[adva-dnos-l2cp.yang.gz](https://github.com/sysrepo/sysrepo/files/4491677/adva-dnos-l2cp.yang.gz)

**Comment by michalvasko** [comment]
Hi,
I tried to reproduce it with the information you have provided but your setup is complex so, as expected, I failed. I think it is a bug so I would like to fix it but I am not sure how to learn more about the use-case. Could you maybe try executing some commands before modifying `candidate` and calling `commit`? These, for example
```
get-config --source candidate
get-config --source running
```
Also, please run `netopeer2-server` with parameters `-d -v3` so that all verbose messages are seen and please post (attach) that too. Thanks. Finally, does the problem also occurs when you call simply
```
> edit-config --target running --config=add-one-interface.xml
```

Regards,
Michal

**Comment by iljatab** [comment]
Here we go:

Attached is logs.tar.gz with:
```
logs/running.txt :    get-config --source running
logs/candidate.txt :    get-config --source candidate
logs/netopeer2-server.log :    netopeer2-server with parameters -d -v3
logs/d.xml - xml :    file used for edit-config --target candidate --config=d.xml
```
After `commit` the following elements read from iterator:
```
op: created
old: (null)
new: /adva-dnos-l2cp:l2cp-profile-object (container)

op: created
old: (null)
new: /adva-dnos-l2cp:l2cp-profile-object/tunnel-mac = 01:00:0C:CD:CD:D0 [default]
```

About `--target running`:
When doing `> edit-config --target running --config=d.xml` ther is no issue.
**However** if immediately after `edit-config --target running` I do `commit`, again I get the same strange changes!

[logs.tar.gz](https://github.com/sysrepo/sysrepo/files/4493530/logs.tar.gz)

Ilja.

**Comment by michalvasko** [comment]
Hi Ilja,
thanks for all the logs and while they did not really help directly, I at least learned that you are also using NACM so the use-case may even be more complicated. I think there are now 2 ways how I can continue.

One option is for you to also upload all the YANG modules you are using (if you are allowed) meaning all files in your `repository/yang` so that I can install them (using a script if you have some) and then try to reproduce it again having similar environment than you. But it would still be likely that I will not succeed, there are just too many details I may miss.

Second option would be, depending on the development environment you are using, for you to set up a machine that I can connect to and easily reproduce this issue. If this was possible, I can use my SSH key to connect (can be found [here](https://github.com/michalvasko.keys)).

Regards,
Michal

**Comment by iljatab** [comment]
Hi Michal,

I will check what can be done on our side and let you know.

I got also another, maybe unrelated question.
In you response you mentioned that "I at least learned that you are also using NACM".
Actually I was forced to use NACM, sysrepo docs say I just must use it.
So is there any way to avoid NACM usage?

Ilja.

**Comment by michalvasko** [comment]
Hi Ilja,
well, I do not think it says that you must use it anywhere (if you are referring to the README). The problem is explained there and the conclusion I tried to convey is that you most certainly should use NACM in deployment. But as for testing, you can simply disable it in the configuration or log to the server as `root`, which is what I usually do. 

Regards,
Michal

**Comment by nkzhyb** [comment]
> Hi Ilja,
> well, I do not think it says that you must use it anywhere (if you are referring to the README). The problem is explained there and the conclusion I tried to convey is that you most certainly should use NACM in deployment. But as for testing, you can simply disable it in the configuration or log to the server as `root`, which is what I usually do.
> 
> Regards,
> Michal

HI michalvasko :
     Is there a conclusion to this issue, maybe I meet the same issue，using sysrepo 1.4.70
     Other configurations cb will be called with default value, when edit configuration in the same top-level container. thanks in advance!
 
plugin:A change detected in '/ietf-interfaces:interfaces/interface[name='loop25']/ietf-ip:ipv4/address[ip='70.3.4.253']/prefix-length', op=0
plugin: A change detected in '/ietf-interfaces:interfaces/interface[name='loop25']/v3po:routing', op=0
plugin: A change detected in '/ietf-interfaces:interfaces/interface[name='loop25']/interface-l2-classify:l2-input-classify', op=0
...
...

thanks!

**Comment by michalvasko** [comment]
Hi,
based on what you said I am not able to determine whether it is a bug in your case or not. But if you are creating a new `/ietf-interfaces:interfaces/interface` instance, it is expected that also any default values of this list are created for the new instance.

**Comment by nkzhyb** [comment]
> Hi,
> based on what you said I am not able to determine whether it is a bug in your case or not. But if you are creating a new `/ietf-interfaces:interfaces/interface` instance, it is expected that also any default values of this list are created for the new instance.

Hi, michalvasko:

    When I use xml string to create an interface and configure ip, Other leaf container in the same top-level container will also be called, but there is no default value defined in XML file，it seems to not be expected.  xml string and Yang file is as follow。
    Could you please check, thanks!

<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
<interface>
    <name>loop25</name>
    <type xmlns:x="urn:opendaylight:params:xml:ns:yang:v3po">x:loopback</type>
    <enabled>true</enabled>
    <loopback xmlns="urn:opendaylight:params:xml:ns:yang:v3po">
        <mac>00:50:56:95:e3:d3</mac>
        <instance>25</instance>
    </loopback>
    <ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip"> 
      <address>
        <ip>10.23.3.24</ip>
        <prefix-length>24</prefix-length>
      </address>
    </ipv4>
</interface>
</interfaces>

plugin: A change detected in '/ietf-interfaces:interfaces/interface[name='loop25']/ietf-ip:ipv4/address[ip='10.23.3.24']', op=0
plugin: A change detected in '/ietf-interfaces:interfaces/interface[name='loop25']/ietfip:ipv4/address[ip='10.23.3.24']/ip', op=0
plugin: A change detected in '/ietf-interfaces:interfaces/interface[name='loop25']/v3po:routing', op=0
plugin: A change detected in '/ietf-interfaces:interfaces/interface[name='loop25']/v3po:unnumbered', op=0
plugin: A change detected in '/ietf-interfaces:interfaces/interface[name='loop25']/interface-policer:policer', op=0

Yang files defined as follows：
ietf-interface.xml
  container interfaces {
    description
      "Interface configuration parameters.";
    list interface {
      key "name";
      leaf name {
        type string;
      }
      leaf type {
        type identityref {
          base interface-type;
        }
        mandatory true;
      }
      leaf enabled {
        type boolean;
        default "true";
      }
  }

v3po.xml
  grouping unnumbered-attributes {
     leaf interface-name {
        type if:interface-ref;
        description "Intf-name for unnumbered funcation";
     }
  }
  grouping routing-base-attributes {
    leaf ipv4-vrf-id {
      type fib-management:fib-table-list-ref;
    }
  }
  augment /if:interfaces/if:interface {
    container loopback {
      presence "Presence of this container indicates loopback nature of the interface";
      when "../if:type = 'v3po:loopback'";
      uses loopback-interface-base-attributes;
    }
    container routing {
      uses routing-base-attributes;
    }
    container unnumbered {
          uses unnumbered-attributes;
    }
  }

**Comment by michalvasko** [comment]
Hi,
yes, this is expected. The non-presence containers are treated mostly as default values by *libyang*, that is why you see them being created. If you do not want this behavior, add `presence` for the containers.

**Comment by nkzhyb** [comment]
> Hi,
> yes, this is expected. The non-presence containers are treated mostly as default values by _libyang_, that is why you see them being created. If you do not want this behavior, add `presence` for the containers.

HI,

Okay, thanks very much!
