### ISSUE TITLE
user ordered leaf-list with defaults not deleting default when user configures values

### ISSUE THREAD

**Issue by meghna-doshi** [sysrepo/sysrepo#1912]
Hi,
Snippet of yang module:

```
container oven {
     leaf-list oven_range {
                type uint32;
                ordered-by user;
                default 1;
                default 2;
                default 3;
        }
       
}
```

When edit-config done:

```
<oven xmlns="urn:sysrepo:oven_leafref" 
        xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0"
        xc:operation="merge" 
        xmlns:yang="urn:ietf:params:xml:ns:yang:1" >
    <oven_range>50</oven_range>
</oven>
```

without user ordered-by:
```

DELETED: /oven_leafref:oven/oven_range : [datatype : 20]= 1 [default]
DELETED: /oven_leafref:oven/oven_range : [datatype : 20]= 2 [default]
DELETED: /oven_leafref:oven/oven_range : [datatype : 20]= 3 [default]
CREATED: /oven_leafref:oven/oven_range : [datatype : 20]= 50
```

with user ordered-by:

`CREATED: /oven_leafref:oven/oven_range : [datatype : 20]= 50`

Dont get deletion for default entries, though deletion comes if "ordered-by user" is removed.
Is this behaviour as expected?

Regards,
Meghna

**Comment by michalvasko** [comment]
Hi,
this behavior was expected, kind-of, because I knew about this and wanted to implement it later. But, since you asked, it should now be fixed so you can try again with the latest *sysrepo*.

Regards,
Michal

**Comment by meghna-doshi** [comment]
Hi Michal,
Thanks, will try and get back.

Regards,
Meghna
