### ISSUE TITLE
leaf list ordered-by user implementation

### ISSUE THREAD

**Issue by meghna-doshi** [sysrepo/sysrepo#1913]
Hi,
We are trying to use user ordered list:
1. Snippet of yang:

```
container oven {
     leaf-list oven_range {
                type uint32;
                ordered-by user;
                default 1;
                default 2;
                default 3;
        }
       
}
```

2. edit-config given:
```
<oven xmlns="urn:sysrepo:oven_leafref"
        xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0"
        xc:operation="merge"
        xmlns:yang="urn:ietf:params:xml:ns:yang:1" >
    <oven_range>50</oven_range>
    <oven_range>70</oven_range>
    <oven_range>80</oven_range>
</oven>
```
 
3. followed by another edit-config:
```
<oven xmlns="urn:sysrepo:oven_leafref"
        xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0"
        xmlns:yang="urn:ietf:params:xml:ns:yang:1">
    <oven_range xc:operation="merge" yang:insert="after" yang:value="50">10</oven_range>
</oven>

```

4. Though sysrepo has values properly stored:
```
/oven_leafref:oven : [datatype : 2](container)
/oven_leafref:oven/turned_on : [datatype : 8]= false [default]
/oven_leafref:oven/temperature : [datatype : 18]= 0 [default]
/oven_leafref:oven/ipaddr_leaf : [datatype : 17]= ipv4addr [default]
/oven_leafref:oven/inside_oven : [datatype : 2](container)
/oven_leafref:oven/oven_range[.='50'] : [datatype : 20]= 50
/oven_leafref:oven/oven_range[.='10'] : [datatype : 20]= 10
/oven_leafref:oven/oven_range[.='70'] : [datatype : 20]= 70
/oven_leafref:oven/oven_range[.='80'] : [datatype : 20]= 80
```

5. as part of edit-config in step 3 above, application got only following information, then how will application insert the value after 50?

`CREATED: /oven_leafref:oven/oven_range : [datatype : 20]= 10`

Regards,
Meghna

**Comment by michalvasko** [comment]
Hi,
what information are you exactly printing? The previous item should be also returned by the change iterator, it just seems you are ignoring it. Look into the documentation for details.

Regards,
Michal

**Comment by meghna-doshi** [comment]
Hi Michal,
1. Sysrepo subscription done:
`rc = sr_module_change_subscribe(session, modname[i], xpath, module_change_cb, NULL, 0, SR_SUBSCR_ENABLED, &subscription);`

2. edit-config given:
```
<oven xmlns="urn:sysrepo:oven_leafref"
        xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0"
        xmlns:yang="urn:ietf:params:xml:ns:yang:1">
    <oven_range xc:operation="merge" yang:insert="after" yang:value="50">10</oven_range>
</oven>

```

3. In module_change_cb, the following loop (refer the examples/application_changes_example.c)

 ```
while ((rc = sr_get_change_next(session, it, &oper, &old_value, &new_value)) == SR_ERR_OK) {
        print_change(oper, old_value, new_value);
```
4. Loop runs for 1 time only, and print_change (..) function o/p as follows:

`CREATED: /oven_leafref:oven/oven_range : [datatype : 20]= 10`

So the query was how does application know that 10 is to be inserted after 50? 
I hope i have made myself clear now.

Regards,
Meghna

**Comment by michalvasko** [comment]
Hi Meghna,
you just confirmed what I assumed so I can only repeat my answer, with more details. Your `print_change` function likely has a switch/if to only print `new_value` in case `oper` is `SR_OP_CREATED`. However, in case of user-ordered (leaf-)lists the `old_value` is [also relevant](https://netopeer.liberouter.org/doc/sysrepo/master/group__change__subs__api.html#ga927f648013da7e15bc521d17b58fb707). You may consider using [sr_get_change_tree_next](https://netopeer.liberouter.org/doc/sysrepo/master/group__change__subs__api.html#gaa80d8ca05c67eba9d794b129422e8294) because it has more explicit parameters and you can easily learn when you are processing a user-ordered (leaf-)list.

Regards,
Michal
