### ISSUE TITLE
startup to running copy

### ISSUE THREAD

**Issue by maksimvuleta** [sysrepo/sysrepo#1918]
I noticed that startup datastore is copied to running before my module is initialized. 
At which point it is done?
After installing the module? 
After sr_plugin_init_cb is called?
During the sr_module_change_subscribe?

I have a module change subscribe in my implementation like this:
    	rc = sr_module_change_subscribe(session, "my-module", NULL,
    			module_change_cb, NULL, 1, SR_SUBSCR_ENABLED | SR_SUBSCR_DONE_ONLY, &subscription);

The function module_change_cb just returns SR_ERR_OK.

The issue is when current startup and running are different and I start sysrepo-plugind.
It just copied startup to running without any callback for config data triggered. 

How to disable the startup to running copy?
Or how to enable to trigger my callbacks for config data?

**Comment by michalvasko** [comment]
Hi,
information about when datastore are being copied is in the [documentation](https://netopeer.liberouter.org/doc/sysrepo/master/index.html#datastores) and it is none of the choices you mentioned.

When you start `sysrepo-plugind`, no implicit datastore copying should take place. Also, you should get `SR_EV_DONE` event with the current `running` data because you used the flags `SR_SUBSCR_ENABLED | SR_SUBSCR_DONE_ONLY`.

Regards,
Michal

**Comment by maksimvuleta** [comment]
Thanks,
I saw that startup is copied to running when the first Sysrepo connection (shared memory) is created after system boot.

Can I disable this somehow?

**Comment by michalvasko** [comment]
You cannot disable it, why do you want to do it anyway? I think it would break the `startup` and `running` datastore functionality.

Regards,
Michal

**Comment by maksimvuleta** [comment]
I need it in cases where I have content of startup is different than the content running.
In cases like this, after the systems reboot, the startup will be copied to running and they will be the same. 
The running will be updated with changes from startup, but that changed values will not represent the real values of the system data. 
If my callback is triggered I will get the correct data at the running and the system data will the same as in startup/running.

**Comment by Roky7250** [comment]
Hi, I am interested in this problem also.
Lets say I have this **startup** configuration for lldp module:

```
<lldp xmlns="urn:ieee:std:802.1AB:yang:ieee802-dot1ab-lldp">
  <message-fast-tx>1</message-fast-tx>
  <message-tx-hold-multiplier>5</message-tx-hold-multiplier>
  <message-tx-interval>40</message-tx-interval>
  <reinit-delay>2</reinit-delay>
  <tx-credit-max>5</tx-credit-max>
  <tx-fast-init>4</tx-fast-init>
  <notification-interval>30</notification-interval>
</lldp>
```

My **running** configuration is :
```
<lldp xmlns="urn:ieee:std:802.1AB:yang:ieee802-dot1ab-lldp">
  <message-fast-tx>1</message-fast-tx>
  <message-tx-hold-multiplier>4</message-tx-hold-multiplier>
  <message-tx-interval>30</message-tx-interval>
  <reinit-delay>2</reinit-delay>
  <tx-credit-max>5</tx-credit-max>
  <tx-fast-init>4</tx-fast-init>
  <notification-interval>30</notification-interval>
</lldp>
```
So these two are my current configurations inside sysrepo.
After this I reboot my device, so sysrepo-plugind will be rebooted also.
So according to my last running configuration, values of message-tx-hold-multiplier and message-tx-interval where 4 and 30. Also these two values are going to be default one after device is rebooted. So device after reboot will have  message-tx-hold-multiplier=4 and message-tx-interval=30.
But I want to apply my startup configuration on device as soon as sysrepo-plugind is booted, so after daemon is booted i want to have this inside running:
```
<lldp xmlns="urn:ieee:std:802.1AB:yang:ieee802-dot1ab-lldp">
  <message-fast-tx>1</message-fast-tx>
  <message-tx-hold-multiplier>5</message-tx-hold-multiplier>
  <message-tx-interval>40</message-tx-interval>
  <reinit-delay>2</reinit-delay>
  <tx-credit-max>5</tx-credit-max>
  <tx-fast-init>4</tx-fast-init>
  <notification-interval>30</notification-interval>
</lldp>
```
and also on system. That means that I will have message-tx-hold-multiplier=5 and message-tx-interval=40 on my device.

So all I want to do is to trigger callbacks when sysrepo-plugind is booting to apply my startup configuration on my device and also copy config from startup to running,
I that case I will have consistent state on my device. Running and startup will be the same and startup configuration will be applied to device.

My question is: how to trigger callbacks so startup configuration is applied when sysrepo-plugind is booting?

Regards

**Comment by michalvasko** [comment]
Hi,
I can only repeat what I said, simply use `SR_SUBSCR_ENABLED` as the subscribe flag and you will immediately get the `running` configuration (which is simply a copy of `startup` at that point) as created changes into the callback.

Regards,
Michal

**Comment by Roky7250** [comment]
It is working. Thank you very much for your patience.

Regards

**Comment by maksimvuleta** [comment]
Thank you Michal for help.

Best regards,
Maksim.
