### ISSUE TITLE
sysrepoctl link failure

### ISSUE THREAD

**Issue by igortern** [sysrepo/sysrepo#1919]
Hi,

sysrepoctl build started failing 
09:01:55  Scanning dependencies of target sysrepoctl
09:01:55  [ 75%] Building C object CMakeFiles/sysrepoctl.dir/src/executables/sysrepoctl.c.o
09:01:55  [ 80%] Linking C executable sysrepoctl
09:01:55  libsysrepo.so.5.3.6: undefined reference to `shm_unlink'
09:01:55  libsysrepo.so.5.3.6: undefined reference to `shm_open'
09:01:55  collect2: error: ld returned 1 exit status
09:01:55  make[10]: *** [sysrepoctl] Err

Regards,
Igor

**Comment by michalvasko** [comment]
Hi Igor,
what platform are you on?

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,

linux. The problem disappeared when I reversed the latest change in CMakeLists.txt (with find_library(rt)). I haven't investigated why find_library didn't work.

Regards,
Igor

**Comment by michalvasko** [comment]
Hi Igor,
I figured that is the problem and I also am wondering why the library did not got found. Please try to find out what the problem is so that I can improve the search, if possible. Otherwise I am not able to help you.

Regards,
Michal

**Comment by igortern** [comment]
I made some changes in build infrastructure outside sysrepo and that fixed the problem. Not sure what caused the problem in the first place, but since no one else  is seeing it, I'm closing the ticket.
Regards,
Igor
