### ISSUE TITLE
Change the format of data files in /etc/sysrepo/data

### ISSUE THREAD

**Issue by rjarry** [sysrepo/sysrepo#1924]
Hello,

The cmake [FILE_FORMAT_EXT](https://github.com/sysrepo/sysrepo/blob/legacy/CMakeLists.txt#L208) build option is not available anymore. Could it be possible to add a build option to choose the format of the data files in the `master` and `devel` branches?

Thanks in advance.

**Comment by michalvasko** [comment]
Hi,
well, *sysrepo* 1.x was redesigned while having performance in mind from the beginning and so LYB files are always used as they are much faster to load/store than the other text formats. Generally, you have no reason to look into those files anyway, they should completely be managed by *sysrepo* so the only valid use-case is, again, development. And for that you can use *yanglint* without much trouble, it can print the files in XML or JSON format.

Regards,
Michal

**Comment by rjarry** [comment]
I understand. We'll try to manage with yanglint.
