### ISSUE TITLE
Ordering of multiple lists with same parent

### ISSUE THREAD

**Issue by XXAmethystXX** [sysrepo/sysrepo#1925]
Hello,

I apologize in advance if this is the wrong place or if my question is too broad.
I am using sysrepo 0.7.8 inside a kubernetes container, where I install some third-party yang modules. Two of these modules consists of a list element augmenting the same parent element.
I send `get-config` and `edit-config` requests using Opendaylight 0.10.1 (in another kubernetes container).
The way my application works is that the elements belonging to the two lists are created in a "mixed" order, going back and forth between the lists. So I get something like this as a result:

```
<TopElement xmlns="top-element">
	<id>1</id>
        ...
	<ParentElement xmlns="parent-element">
		<id>1</id>
                ...
		<ChildElement1 xmlns="child-element1">
			<id>ZC3pbHlUEeqYOuokZV802w</id>
			<attributes>
				...
			</attributes>
		</ChildElement1>
		<ChildElement1 xmlns="child-element1">
			<id>Z91zImnlUEeqYOuokZV802w</id>
			<attributes>
				...
			</attributes>
		</ChildElement1>
		<ChildElement2 xmlns="child-element2">
			<id>aDhggHlUEeqYOuokZV802w</id>
			<attributes>
				...
			</attributes>
		</ChildElement2>
		<ChildElement1 xmlns="child-element1">
			<id>bE90SjHlUEeqYOuokZV802w</id>
			<attributes>
				...
			</attributes>
		</ChildElement1>
                <ChildElement2 xmlns="child-element2">
			<id>bXP7UnlUEeqYOuokZV802w</id>
			<attributes>
				...
			</attributes>
		</ChildElement2>
	</ParentElement>
</TopElement>
```

The mixed lists seem to not sit well with Opendaylight, so I wonder if this ordering is expected behavior or if there is something else here.
I had the opportunity to test the same modules and configuration with Tailf's ConfD and found out that it behaves differently, keeping the lists grouped (and ordered by key, although this is of secondary importance to me). Would the same behavior be possible in sysrepo?

And more generally, is there no rule on how to treat multiple same-level lists? I couldn't find any info about this specific case, so any idea or suggestion would be very valuable.

Thank you.

**Comment by michalvasko** [comment]
Hi,
as for *sysrepo* 0.7.8, nothing will change, unfortunately, because it is obsolete and its development is finished. As for the current *sysrepo*, I think this makes sense and so it will be implemented (I have written it down) although I am not able to tell you when. As for a rule how this should be treated, it actually is [specified](https://tools.ietf.org/html/rfc7950#section-7.8.5) and is implementation dependent. So any Opendaylight SW should be able to handle it.

Regards,
Michal

**Comment by XXAmethystXX** [comment]
Hi Michal,

Thank you for your clarification! You are absolutely right about the specification, I totally missed that.

Best regards.
