### ISSUE TITLE
Proposal: "more pythonic" bindings

### ISSUE THREAD

**Issue by sinill57** [sysrepo/sysrepo#1926]
While implementing some python callbacks using sysrepo bindings, I've made a few tweaks for easier use. I could make a pull request, but SWIG is not my strong point, so I just post them here for discussion:

- We could extract data from `sr.Val` class as a corresponding Python type directly 
```
yang_types = {
    sr.SR_BOOL_T:      sr.Data.get_bool,
    sr.SR_DECIMAL64_T: sr.Data.get_decimal64,
    sr.SR_ENUM_T:      sr.Data.get_enum,
    sr.SR_INT8_T:      sr.Data.get_int8,
    sr.SR_INT16_T:     sr.Data.get_int16,
    sr.SR_INT32_T:     sr.Data.get_int32,
    sr.SR_INT64_T:     sr.Data.get_int64,
    sr.SR_STRING_T:    sr.Data.get_string,
    sr.SR_UINT8_T:     sr.Data.get_uint8,
    sr.SR_UINT16_T:    sr.Data.get_uint16,
    sr.SR_UINT32_T:    sr.Data.get_uint32,
    sr.SR_UINT64_T:    sr.Data.get_uint64
}

class Val(_object):
    def pdata(self)
        return yang_types[self.type()](self.data())
```
such a method would remove a lot of boilerplate code

- Make a "Pythonic" iterator for changes
```
class Session(_object):
    def get_changes(self, change_path):
        it = self.get_changes_iter(change_path)
        while True:
            change = self.get_change_next(it)
            if change is None:
                break
            yield change
```
then in callbacks we can write a simple for-loop
```
for change in sess.get_changes(change_path):
     ...
```

- Add indexing support to `sr.Vals` and other such classes. It is a straightforward mapping, i.e. `__len__() -> val_cnt()` and `__getitem__(idx) -> val(idx)`. However, to use it in for-loops, `__getitem__` has to return `IndexError`, but `val` returns `SystemError`

**Comment by rkrejci** [comment]
Hi, we actually would like to replace SWIG-generated python bindings with a manually written version using c-extension. The reason is to make the interface more "Pythonic" and @Akhady was supposed to work on it. Unfortunately, he doesn't seem to be active regarding this task, so we probably will reassign the task.

I would like to ask you to any ideas regarding the Pythonic API here (as you actually did). So, please, do not hesitate (you or anyone else) to add any idea here and I promise that we will consider it.

**Comment by sinill57** [comment]
Hi Radek,

I've only used the `sr_val_t` and change subscriptions API yet. With the above changes, my python script looks much better already. Think there is more to be done regarding the `lyd_node` API (my first attempt on using them in python just made SEGFAULTs on any call :\ ).

Also, I would suggest putting `subscribe.unsubscribe()` and `sess.session_stop()` into corresponding class destructors: if the script terminates before calling them (or an exception is caught) sysrepo itself breaks because the session still hangs open.

**Comment by rjarry** [comment]
@rkrejci I have written [CFFI](https://cffi.readthedocs.io/en/latest/) bindings for [libyang](https://github.com/rjarry/libyang-cffi) which we use extensively for our projects. SWIG had too much drawbacks. CFFI allows better integration with the python ecosystem (virtualenv, pip, etc.).

Following this, I am integrating the new sysrepo API and I have written a CFFI binding for it (again no SWIG).

These bindings are incomplete and under development but I would be glad to share them (and maybe integrate them into sysrepo and libyang if possible).

Note : the sysrepo bindings are [asyncio](https://docs.python.org/3/library/asyncio.html)-compatible.

**Comment by michalvasko** [comment]
Hi,
thanks for the offer but our goal was to both make the bindings more natural to use and to get rid of swig dependency. I would like to avoid requiring another one.

Regards,
Michal

**Comment by rjarry** [comment]
Hi Michal,

I only used CFFI as a convenience. The same result should be achievable without it, albeit with more work.

In any case, if the "pythonic" API seems OK to you, I could have a look to get rid of CFFI.

**Comment by rkrejci** [comment]
That would be great. We were also looking for some solution which would allow to "connect" libyang and sysrepo bindings - some of the sysrepo functions provide or require libyang data. We do not want to "create" libyang objects again "manually" in sysrepo bindings (duplicate code from the libyang bindings), instead we want to work with the data via libyang bindings. The only way we were able to do this was using pure Python's C-extension.

**Comment by rjarry** [comment]
Hi Radek,

I have managed to do that. The libyang objects returned by libsysrepo.so, can be fed directly to the CFFI binding I made for libyang.so. A simple cast is required: https://github.com/rjarry/libyang-cffi/blob/master/libyang/data.py#L164

Also, libyang objects generated from python, can be fed back to libsysrepo.so (casting the other way around).

If you are interested in all this, I can start cleaning the libsysrepo CFFI bindings I am working on and show you what it looks like.

In any case, if we are talking about integrating this into libyang/sysrepo, it would require some work. More work if you want to get rid of CFFI since it takes care of most of the boilerplate needed to map C objects to python objects (and back).

Please let me know what you think.

Cheers,

**Comment by rjarry** [comment]
I forgot to mention. One upside in using CFFI instead of manually written python C extensions is [pypy support](https://www.pypy.org/) directly out of the box.

**Comment by sinill57** [comment]
Hi Radek,

Instead of writing a separate binding for Python, why not reuse the C++ bindings? Both languages are OOP, so they should be quite similar in terms of the class implementations. Then use e.g. [pybind11](https://pybind11.readthedocs.io/en/stable/index.html) to convert it to Python.
I see following pros of such implementation:

- You need to maintain only one handwritten binding (the C++ one)
- The boilerplate C++ code involved is really simple ([example](https://pybind11.readthedocs.io/en/stable/classes.html#creating-bindings-for-a-custom-type))
- You can maintain a separate module for libyang, using those classes for sysrepo ([example](https://pybind11.readthedocs.io/en/stable/advanced/classes.html#module-local-class-bindings))
- Python-only methods (__getitem__, __enter__, __iter__, etc.) can be easily implemented in the binding with lambda functions ([example](https://github.com/pybind/pybind11/blob/stable/tests/test_sequences_and_iterators.cpp))

**Comment by rjarry** [comment]
@rkrejci,

The bindings I am working on are still under development but here is a bit of dummy example code:

```python3
# server
import asyncio
import signal
import libyang
import libsysrepo

async def module_change_cb(xpath, event, config, changes, private_data):
    if event != libsysrepo.Event.DONE:
        return
    hostname = config['config']['hostname']
    proc = await asyncio.create_subprocess_exec(
        ['hostnamectl', 'set-hostname', hostname])
    await proc.wait()

stop_event = asyncio.Event()
loop = asyncio.get_event_loop()
loop.add_signal_handler(signal.SIGTERM, stop_event.set)
loop.add_signal_handler(signal.SIGINT, stop_event.set)
loop.add_signal_handler(signal.SIGQUIT, stop_event.set)

with libsysrepo.Connection() as conn:
    with conn.start_session() as sess:
        sess.subscribe_module_change(
            'mymodule', '/mymodule:config/hostname', module_change_cb)
        loop.run_until_complete(stop_event.wait())
```

```pycon
# client
>>> import libyang
>>> import libsysrepo
>>> with libsysrepo.Connection() as conn:
>>>     with conn.start_session(libsysrepo.Datastore.RUNNING) as sess:
>>>         config = sess.get_subtree_dict('/mymodule:config')
>>>         print('==== current config ====')
>>>         print(config)
>>>         config['config']['hostname'] = 'foobar'
>>>         dnode = libyang.dict_to_dnode(config, conn.get_ly_ctx().get_module('mymodule'))
>>>         sess.replace_config(dnode)
>>>         config = sess.get_subtree_dict('/mymodule:config')
>>>         print('==== updated config ====')
>>>         print(config)
...
==== current config ====
{'config': {'hostname': 'localhost'}}
==== updated config ===='
{'config': {'hostname': 'foobar'}}
```
