### ISSUE TITLE
Can I control loading order of multi plugins ?

### ISSUE THREAD

**Issue by gaoxf323** [sysrepo/sysrepo#1930]
Hi,

Now i  add five new plugins, what i should do if i want to load these plugins in the order i set when sysrepo start ? 

Regards

**Comment by michalvasko** [comment]
Hi,
this is not really possible but could be achieved quite easily if you make them look like a single plugin for *sysrepo-plugind*. In this one plugin init function you can call the other init functions in whatever order you want.

Regards,
Michal

**Comment by gaoxf323** [comment]
Hi Michal,
thanks for your help.

Regards,
gaoxf
