### ISSUE TITLE
How to delete running configuration for a single module?

### ISSUE THREAD

**Issue by matth65** [sysrepo/sysrepo#1934]
Have have a couple of questions related to deleting configuration for a specific module.

1) Does Sysrepo have a method to delete/remove all running configuration for a specific module? For example, is there a way to reinitialize /dev/shm/sr_mymod.running back to a clean, default state?

$ ls -lha /dev/shm/sr_mymod*
-rw-rw-rw- 1 root root    7 Apr 21 18:05 /dev/shm/sr_mymod.operational
-rw-rw-rw- 1 root root 211K Apr 21 18:05 /dev/shm/sr_mymod.running

2) Does Sysrepo have any shortcuts for deleting all elements of a list?

**Comment by michalvasko** [comment]
Hi,
you are asking about *sysrepo* and there both operations are possible and simple.

1. You can use `sysrepocfg -C running -d startup -m mymod`. Or the corresponding API function [sr_copy_config()](https://netopeer.liberouter.org/doc/sysrepo/master/group__edit__data__api.html#gadffb2f55f24a44730c359f2fdabe6ade).
2. This is natively supported by [sr_delete_item()](https://netopeer.liberouter.org/doc/sysrepo/master/group__edit__data__api.html#ga7b0e53979b363dd9dfb33d3af64f28d9), details in the docs.

Regards,
Michal

**Comment by matth65** [comment]
Great. Thank you for the quick reply.
