### ISSUE TITLE
Yang leaf node data type decima64, RPC returns failure

### ISSUE THREAD

**Issue by lzx296828759** [sysrepo/sysrepo#1936]
Hi，
I get a problem When I use RPC command to access sysrepo server. If there is decima64 type in the leaf node of Yang file, the following error will be reported. If the decimal64 type leaf is blocked, other types such as string, uint16, uint32, Uint64 and enum can return normally.

sysrepo - v0.7.8
netopeer - v0.7.12

The client MG-SOFT NetConf Browser 2018b RPC command is as follows:
rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1"
oc-otdr:update-baseline xmlns:oc-otdr="http://openconfig.net/yang/otdr"
oc-otdr:name  OTDR-1-2-1  /oc-otdr:name
oc-otdr:scan-time  2020-04-20T18:06:40Z+08:00  oc-otdr:scan-time
/oc-otdr:update-baseline
/rpc

The client  MG-SOFT NetConf Browser 2018b RPC command returns the following results:
rpc -reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="5"
rpc-error
error-type protocol /error-type
error-tag bad-element /error-tag
error-severity error  /error-severity
error-message xml:lang=”en” Failed to create node “length” as a child of ”event”.  /error-message
error-info 
bad-element  /openconfig-optical-time-domain-reflectometer:update-baseline/events/event[index=’1’]/length   /bad-element
/error-info
/rpc-error
/rpc-reply

Sysrepo server log:
```
Apr 21 09:59:33 accelink daemon.err netopeer2-server[2637]: Schema node not found. (/openconfig-optical-time-domain-reflectometer:update-baseline/events)
Apr 21 09:59:33 accelink daemon.err netopeer2-server[2637]: Invalid value "" in "length" element. (/openconfig-optical-time-domain-reflectometer:update-baseline/events/event[index='1']/length)
Apr 21 09:59:33 accelink daemon.err netopeer2-server[2637]: Failed to create node "length" as a child of "event". (/openconfig-optical-time-domain-reflectometer:update-baseline/events/event[index='1']/length)
```

My server some code as follow:
```C
    char MyPath[NC_XPATH_LEN]={0};
    uint32 outItemNum = itemNum;
    *output_cnt = outItemNum;
    rc = sr_new_values( outItemNum, output);
    int i = 0;
    strncpy(MyPath, "/openconfig-optical-time-domain-reflectometer:update-baseline",  
                 NC_XPATH_LEN);
    snprintf(OutXpath, NC_XPATH_LEN, "%s/%s", MyPath, "message");
    rc = sr_val_set_xpath( &(*output)[i], OutXpath);
    sr_val_set_str_data( &(*output)[i], SR_STRING_T, rpcOutput.message);
    i++;
	
   snprintf(xpathPrefix, NC_XPATH_LEN, "%s/%s", MyPath, "scanning-profile");
   snprintf(OutXpath, NC_XPATH_LEN, "%s/%s", xpathPrefix, "distance-range");
   rc = sr_val_set_xpath( &(*output)[i], OutXpath);
   (*output)[i].type = SR_UINT32_T;
   (*output)[i].data.uint32_val = pTmp->distance_range;
   i++;

   snprintf(xpathPrefix, NC_XPATH_LEN, "%s/%s", MyPath, "events");
   snprintf(OutXpath, NC_XPATH_LEN, "%s/%s", xpathPrefix, "scan-time");
   rc = sr_val_set_xpath( &(*output)[i], OutXpath);
   sr_val_set_str_data( &(*output)[i], SR_STRING_T, pTmp->scan_time);
   i++;

  snprintf(xpathPrefix, NC_XPATH_LEN, "%s/%s[index='%d']", MyPath, "events/event", pEventList->index); 
  snprintf(OutXpath, NC_XPATH_LEN, "%s/%s", xpathPrefix, "index");
  rc = sr_val_set_xpath( &(*output)[i], OutXpath);
  (*output)[i].type = SR_UINT16_T;
  (*output)[i].data.uint16_val = pEventList->index;
  i++; 

  snprintf(OutXpath, NC_XPATH_LEN, "%s/%s", xpathPrefix, "type");
  rc = sr_val_set_xpath( &(*output)[i], OutXpath);
  sr_val_set_str_data( &(*output)[i], SR_ENUM_T, pEventList->type);
  i++;

  snprintf(OutXpath, NC_XPATH_LEN, "%s/%s", xpathPrefix, "length");
  rc = sr_val_set_xpath( &(*output)[i], OutXpath);
  (*output)[i].type = SR_DECIMAL64_T;
  (*output)[i].data.decimal64_val = pEventList->length;
  i++;
  
  snprintf(OutXpath, NC_XPATH_LEN, "%s/%s", xpathPrefix, "loss");
  rc = sr_val_set_xpath( &(*output)[i], OutXpath);
  (*output)[i].type = SR_DECIMAL64_T;
  (*output)[i].data.decimal64_val = pEventList->loss;
  i++;
```

I look forward to your reply，thanks !

**Comment by michalvasko** [comment]
Hi,
it is difficult for me to help you without seeing the module and being able to reproduce it but if you could do some basic debugging yourself, the issue may be found quickly with my help. Also, the *sysrepo* and *netopeer2* you are using are deprecated so I would prefer not to spend much of my time on them.

Regards,
Michal

**Comment by lzx296828759** [comment]
Hi Michal，
  Thank you for your reply， the added module is as follows:
       
      leaf length {
          type decimal64 {
            fraction-digits 2;
          }
          units "km";
          description
            "Event distance or fiber section length in km";
        }

RPC test return errors:
 <error-message xml:lang=”en”>  Failed to create node “length” as a child of ”event”.</error-message>
<bad-element> /openconfig-optical-time-domain-reflectometer:update-baseline/events/event[index=’1’]/length  </bad-element>

If I  change type of length to uint32 or string, RPC test returned successfully,
example:
        leaf length {
          type uint32;
          units "km";
          description
            "Event distance or fiber section length in km";
        }

I look forward to your help.

Best Regard,
Liu,
Thanks.
