### ISSUE TITLE
Query on operational datastore

### ISSUE THREAD

**Issue by meghna-doshi** [sysrepo/sysrepo#1937]
Hi,
sysrepo from devel branch (version 1.4.38)
As per RFC 8342, operational datastore is
```
"The datastore schema for <operational> MUST be a superset of the
   combined datastore schema used in all configuration datastores,
   except that configuration data nodes supported in a configuration
   datastore MAY be omitted from <operational> if a server is not able
   to accurately report them."
```
We did following trial:

1. yang module snippet:

```
container oven {
        description "Configuration container of the oven.";

        leaf turned_on {
            description "Main switch determining whether the oven is on or off.";
            type boolean;
            default false;
        }

        leaf temperature {
            description "Slider for configuring the desired temperature.";
            type uint32;
            default 0;
        }
        leaf range {
           type uint32;
           config false;
       }

```

2. edit-config on running datastore :
```
<oven xmlns="urn:sysrepo:oven_leafref">
    <temperature>100</temperature>
    <turned_on> true </turned_on>
</oven>
```

3. From application, set temperature in operational datastore, to value 200.

4. Now did get-data on operational datastore:
```
<oven xmlns="urn:sysrepo:oven_leafref">
    <temperature>200</temperature>
</oven>
```
5. So the query is that operational datastore returned only the value which was set in it, but did not return the value of turned_on. 
Is this expected behaviour? Should it not return the RW values set via edit-config on running datastore also?

Regards,
Meghna

**Comment by michalvasko** [comment]
Hi,
yes, it should as long as those configured values are __in-use__. More about how this concept is implemented in *sysrepo* is in the [docs](https://netopeer.liberouter.org/doc/sysrepo/master/index.html#oper_ds).

Regards,
Michal

**Comment by meghna-doshi** [comment]
Hi Michal,
Ok checked the documents, and i see the following: 
```
any subscribed running data (in-use concept) will appear in operational datastore;
...
...
Note that these data are always appended to in-use running data. That means, for instance, that no state data can exist if their configuration parent does not exist. A consequence of this is that whenever in-use running data change, the stored operational changes (push method) are also adjusted and any invalid data (one without parents) are removed.
```

So i am deducing the following:
1. running data goes to operational also.
2. application can override data in operational data store (both config true and config false )

Let me know if my deduction is correct, then i will ask further.

Regards,
Meghna

**Comment by michalvasko** [comment]
Hi,
1. Yes, but only __subscribed__ running data.
2. Yes.

Regards,
Michal

**Comment by meghna-doshi** [comment]
Hi Michal,
For your reply in 1:
Yes, but only subscribed running data.

What does this mean? I mean what is meant by "subscribed running data"?
Application has done modify subscription in my current example.

Regards,
Meghna

**Comment by michalvasko** [comment]
Hi,
I was hoping it was obvious, but subscribed running data means only the data that are covered by a `sr_module_change_subscribe()` call on a session with `SR_DS_RUNNING`. "covered by" means that if you do not set any `xpath`, all the data of the module are covered and when you set some `xpath`, only data matching the xpath are covered.

Regards,
Michal

**Comment by meghna-doshi** [comment]
Hi Michal,
Thanks, yes it works as expected when we do sr_module_change_subscribe().
One more query on this:
1. Application has done get subscription on operational db (using sr_oper_get_items_subscribe (....)
2. Application has set values in operational DB (using sr_set_item_str () and sr_apply_changes () )
3. Now get-data is called on operational DB.

So in this case:
1. if application does not return value in the get callback, then will the value be picked from operational DB (if the value is set in operational DB)?

Regards,
Meghna

**Comment by michalvasko** [comment]
Hi,
I think you can find the answer in the [docs](https://netopeer.liberouter.org/doc/sysrepo/master/index.html#oper_data). Specifically, all the data are used and conflicts resolved the way described.

Regards,
Michal

**Comment by meghna-doshi** [comment]
Hi Michal,
Thanks for pointing to the document. After going through it, we interpret that both pull and push coexist.
So will try to put the exact scenario:

0. Subscribe for module_change in the "oven" model
./application_changes_example oven

1. // set temperature to 13
> edit-config --target running --config
OK


2. > get-data --datastore operational --filter-xpath /oven:* 
DATA
<oven xmlns="urn:sysrepo:oven">
<temperature>13</temperature>
</oven>

3. do a sr_oper_get_items_subscribe for model oven in another process:
./oper_data_example oven /oven:*
Application will provide data "/oven:*" of "oven".


4. > get-data --datastore operational --filter-xpath /oven:* 
DATA
 
So now the query is, if both push and pull are supported, then why no data was returned in step 4 above.

Regards,
Meghna

**Comment by michalvasko** [comment]
Hi,
I will walk you through what happened when you executed `get-data` on `operational` datastore.

1. First the enabled `running` data are built. That leaves you with the `temperature` `13` since you set that value manually and are subscribed to it using the `application_changes_example`.
2. As documented, now `push` operational data would be applied but you have set none, so nothing changes.
3. Lastly, any `pull` operational data are retrieved. You have subscribed for providing all the top-level nodes of the `oven` module. So, your callback is called and it is supposed to replace the data it subscribed to. You do not create any data in the callback, so they are effectively removed.
4. These data are returned and that is why you see no data.

I believe you missed the exact behavior of `pull` subscription callbacks but it is also [documented](https://netopeer.liberouter.org/doc/sysrepo/devel/group__oper__subs__api.html#ga2915a5b53a6495ca246c44f7aae58ed5) (only in `devel` for now). You can also change this behavior so that any existing data are not removed by using `SR_SUBSCR_OPER_MERGE` flag when subscribing (it is not yet in the generated documentation for some reason).

Regards,
Michal

**Comment by meghna-doshi** [comment]
Hi Michal,
One new query on operational DB.
One simplified example:
1. Edit-config : set leaf-list value a,b
2. Application: set leaf-list value c,d
3. So then get-data on operational should return : a,b,c,d (this is what our experiments are also showing) or should it return only c,d.

Regards,
Meghna

**Comment by michalvasko** [comment]
Hi,
again, as mentioned in documentation, all the operational data are merged so the results you are seeing are correct (provided that you are subscribed to the set `running` data).

Regards,
Michal

**Comment by meghna-doshi** [comment]
Hi Michal,
Is this behaviour (of merging data from operational and running) in accordance with RFC 8342?
We are bit confused on this, what is expected behaviour from RFC 8342.

Regards,
Meghna

**Comment by michalvasko** [comment]
Hi Meghna,
I believe NMDA defines the theoretical concepts and what we were discussing here is the actual implementation in *sysrepo*. In short, __in-use__ concept is when a subscriber `running` configuration also appears in the `operational` datastore. Operational subscriptions (whether push or pull) are simply a way of providing state data by the application, not really connected to NMDA. But, when used for configuration data, they implement a somewhat extended __missing resources__ concept, when `running` configuration is not applied not just because of missing resources but for any reason so it does not appear or is changed in the `operational` datastore.

Regards,
Michal

**Comment by meghna-doshi** [comment]
Hi Michal,
Ok got it.
So how to implement this "missing configuration" i.e something which is present in running but not in operational datastore.
What application should so that it is not shown in operational datastore? 
Delete such configuration from operational datastore?

Regards,
Meghna

**Comment by michalvasko** [comment]
Hi,
like I said, you are free to decide the exact details but you should, generally, use the behavior that for whatever data you subscribe with an operational subscription, it is deleted (and stays that way if you do not add any new data in the callback).

Regards,
Michal

**Comment by meghna-doshi** [comment]
Hi Michal,
Further on this one more query.
Following is our understanding of sysrepo behaviour with respect to operational DS:
1. edit-config done on running.
2. no applications subscribes for sr_oper_get_items_subscribe ()
3. whatever edit-config done in step 1, reflects in operational DS also.

So now we want to somehow achieve a case where:
1. no application does sr_oper_get_items_subscribe but application sets value in operational DS.
2. when edit-config on running datastore comes, sysrepo should not reflect that change in operational DS.
3. so ideally operational DS always has values which are set by application and not done via edit-config RPC.
Is there a way to achieve this?

Regards,
Meghna

**Comment by michalvasko** [comment]
Hi,
for your first 3 bullets, they are correct __only__ as long as there is a `running` data subscriber. Otherwise the `operational` datastore stays empty.

Regarding your use-case, that is exactly how *push* operational data work. And it should behave the way you expect as long as you have no `running` data subscribers. If you do, then be aware that they may affect the stored *push* data (details in [docs](https://netopeer.liberouter.org/doc/sysrepo/master/index.html#oper_data)).

Regards,
Michal

**Comment by meghna-doshi** [comment]
Hi Michal,
Ok understood, but our requirement is to have a running datastore changes subscriber also.
So with that, i assume that any change done via edit-config on running ds will get into operational ds.
So now can you please help us figure out how to do the following (same as asked above)
1. no application does sr_oper_get_items_subscribe but application sets value in operational DS.
2. when edit-config on running datastore comes, sysrepo should not reflect that change in operational DS.
3. so ideally operational DS always has values which are set by application and not done via edit-config RPC.

Assume that point 2 is not possible, then is there a way that when application does sr_set_item or sr_set_item_str, it can tell replace existing data or something like this.
I hope i have made my query clear.

Regards,
Meghna

**Comment by michalvasko** [comment]
Hi,
then you cannot use *push* operational data because they can always be influenced by changes in the running datastore if there are subscriptions for them. But *pull* operational subscriptions do precisely this. They remove (by default) any data you have subscribed for and you are free to add whatever data you want. If you want to keep using *push* data then what you are asking is indirectly possible but would be quite complex and I advise against that. Naturally, you can subscribe to running data changes and then always analyze whether the changes will impact your *push* data but like I said, this is difficult to do and you would be duplicating internal functionality to some extent.

Regards,
Michal

**Comment by ishidawataru** [comment]
Hi @michalvasko 

I have a similar use case.
I'd like to keep a **pushed** operational data intact when I delete a corresponding item in the running ds.
In my case,  calling a pull callback takes time so I want to use only pushed data ( by using `SR_OPER_NO_SUBS` ) when I'm not interested in the pulled data.

Is it impossible to add this feature to sysrepo?

> Naturally, you can subscribe to running data changes and then always analyze whether the changes will impact your push data but like I said, this is difficult to do and you would be duplicating internal functionality to some extent.

Does this mean I can push the deleted item again in oper ds in the change callback of running ds?

---

Below is the simplified version of the application. 

#### YANG model

```yang
module test {
  yang-version 1.1;
  namespace "http://example.com";
  prefix test;

  container test {
    leaf name {
        type string;
    }
  }
}
```

#### server

```python
import sysrepo
import logging
import asyncio
import signal

logger = logging.getLogger(__name__)

class Server(object):
    def __init__(self):
        self.conn = sysrepo.SysrepoConnection()
        self.sess = self.conn.start_session()

    async def oper_cb(self, sess, xpath, req_xpath, parent, priv):
        print(xpath, req_xpath)

    async def change_cb(self, event, req_id, changes, priv):
        print(event, req_id, changes, priv)


    def stop(self):
        self.sess.stop()
        self.conn.disconnect()

    async def start(self):

        self.sess.switch_datastore('operational')

        self.sess.set_item("/test:test/name", "hello")

        self.sess.apply_changes()

        self.sess.switch_datastore('running')

        # passing None to the 2nd argument to enable layering the running datastore
        # as the bottom layer of the operational datastore
        self.sess.subscribe_module_change('test', None, self.change_cb, asyncio_register=True)

        # passing oper_merge=True to enable pull/push information layering
        self.sess.subscribe_oper_data_request('test', '/test:*', self.oper_cb, oper_merge=True, asyncio_register=True)

        return []

def main():
    async def _main():
        loop = asyncio.get_event_loop()
        stop_event = asyncio.Event()
        loop.add_signal_handler(signal.SIGINT, stop_event.set)
        loop.add_signal_handler(signal.SIGTERM, stop_event.set)

        server = Server()

        try:
            tasks = await server.start()
            tasks.append(stop_event.wait())
            done, pending = await asyncio.wait(tasks, return_when=asyncio.FIRST_COMPLETED)
            logger.debug(f"done: {done}, pending: {pending}")
            for task in done:
                e = task.exception()
                if e:
                    raise e
        finally:
            server.stop()

    asyncio.run(_main())

if __name__ == '__main__':
    main()
```

#### client

```python
import sysrepo

with sysrepo.SysrepoConnection() as conn:
    with conn.start_session() as sess:
        sess.switch_datastore('operational')
        print("initial operational ds:", sess.get_data("/test:*"))

        sess.switch_datastore('running')
        print("initial running ds:", sess.get_data("/test:*"))

    with conn.start_session() as sess:
        sess.switch_datastore('running')
        sess.set_item("/test:test/name", "hello")
        sess.apply_changes()
        print("set an item in running ds")

    with conn.start_session() as sess:
        sess.switch_datastore('operational')
        print("operational ds:", sess.get_data("/test:*", no_subs=True))
        sess.switch_datastore('running')
        print("running ds:", sess.get_data("/test:*"))

    with conn.start_session() as sess:
        sess.switch_datastore('running')
        sess.delete_item("/test:test/name")
        sess.apply_changes()
        print("delete an item in running ds")

    with conn.start_session() as sess:
        sess.switch_datastore('operational')
        print("operational ds:", sess.get_data("/test:*"))
        sess.switch_datastore('running')
        print("running ds:", sess.get_data("/test:*"))
```

#### output

```bash
$ python3 client.py
initial operational ds: {'test': {'name': 'hello'}}
initial running ds: {}
set an item in running ds
operational ds: {'test': {'name': 'hello'}}
running ds: {'test': {'name': 'hello'}}
delete an item in running ds
operational ds: {} # I want to see  {'test': {'name': 'hello'}} here
running ds: {}
```

**Comment by ishidawataru** [comment]
Thanks a lot. I managed to work around this by re-populating the oper ds in the change callback of running ds.
I'll remove the workaround once the feature is implemented in sysrepo.

**Comment by michalvasko** [comment]
Yes. The whole mechanism was completely changed, in any case.
