### ISSUE TITLE
Prevent config changes when no subscribers

### ISSUE THREAD

**Issue by matth65** [sysrepo/sysrepo#1938]
Hello,

I have a plugin 'myplugin' that subscribes to changes in module 'mymodule' as the data "owner". If I run Netopeer2 with 'myplugin' stopped, Netopeer2 allows changes to 'mymodule'. In this scenario, there are no applications listening to changes for 'mymodule'.  

Is there a way to configure a module or sysrepo to prevent changes to a module when there are no data "owner" subscribers (e.g., return an error if there are no subscribers)?

Regards,
Matt

**Comment by michalvasko** [comment]
Hi Matt,
you are probably trying to get the same behavior as was in the legacy *sysrepo* but it does not matter even if not. The point is that with the implementation of NMDA, a module configuration without subscribers is represented as non-present in the `operational` datastore. Generally, there is no reason to forbid access to the configuration for any other reasons than actual access rights. So I am afraid this is not possible.

Regards,
Michal

**Comment by matth65** [comment]
Hi Michal,

Thank you for information and the quick response.

Regards,
Matt
