### ISSUE TITLE
Missing required element "denied-operations" in "nacm".

### ISSUE THREAD

**Issue by kramarz89** [sysrepo/sysrepo#1939]
Hi Michal,

As you suggested in other [issue](https://github.com/sysrepo/sysrepo/issues/1933) to use [this](https://netopeer.liberouter.org/doc/sysrepo/master/edit_data.html) and the Edit API
I've followed, and working with `config false` data, I've tried to set the data using 
`sr_edit_batch(session, data, "merge");`
while the data is prepared using libyang to parse from a simple xml file:

`data = lyd_parse_path((struct ly_ctx *)sr_get_context(connection), xml_full_path, LYD_XML, LYD_OPT_DATA_NO_YANGLIB);`

However the `data` is empty so I've checked last error from libyang and get the following:
```
[INF]: plugin: ****** libyang error: Missing required element "denied-operations" in "nacm".
```
And my nacm configuration is false:
```
<nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
  <enable-nacm>false</enable-nacm>
  <write-default>permit</write-default>
</nacm>
```

So from what I understood, it shouldn't be enforced?
Where is the problem?

BR,
Adam

**Comment by michalvasko** [comment]
Hi Adam,
firstly, editing config false (operational) data this way is possible but you should be aware of what exactly you [are doing](https://netopeer.liberouter.org/doc/sysrepo/master/index.html#oper_data). I assumed you wanted to edit configuration data.

Now, I also see that you opted for the most versatile but also most complex option of using `sr_edit_batch()`. That is alright and you correctly figured the easiest way of getting the input for that is parsing some XML/JSON edit data using *libyang*.

However, it seems you do not fully understand the distinction when using *libyang* API versus *sysrepo* API. When you call `lyd_parse_path()`, the input data are simply parsed and validated according to the context and the resulting data tree is returned. What I am trying to say is that your comment
> So from what I understood, it shouldn't be enforced?

does not make sense. *libyang* is not validating your *sysrepo* datastore but simply the data you passed as input and it enforces all the rules defined by YANG 1.1. To keep this short, you do not really require *libyang* validation at this point because *sysrepo* will then correctly validate everything before finally applying this configuration. So, the correct (close enough) and simple solution is probably to use additional `LYD_OPT_TRUSTED` flag when parsing the data. You can read what it does yourself and you will not even need `LYD_OPT_DATA_NO_YANGLIB` then.

Regards,
Michal

**Comment by kramarz89** [comment]
Awesome, thank you Michal for the explanation, totally makes sense. And yes, I wish for the nodes to be `config false` so it's not something editable by `edit-config` rpcs, but be there and loaded at my application startup, taken from the xml.


As for

> Now, I also see that you opted for the most versatile but also most complex option of using sr_edit_batch(). That is alright and you correctly figured the easiest way of getting the input for that is parsing some XML/JSON edit data using libyang.

Can you suggest more elegant or simpler method (as opposing to what I figured out :))to work with data that I wish to have stored in xml files in simple form?
By simple form I mean only like this, without the additional missing ietf-yang-library elements:
```
<sim xmlns="urn:sim:1.0">
    <specification>
        <id>1</id>
        <major>1</major>
        <minor>1</minor>
        <micro>1</micro>
    </specification>
    <compliance>
        <iana-enterprise-number>1</iana-enterprise-number>
        <device-id>1</device-id>
        <version>
            <major>1</major>
            <minor>1</minor>
            <micro>1</micro>
        </version>
    </compliance>
</sim>
```


I've tried your suggestion, but this time, i get this:

```
root@sim:~# ./versioning
[DBG]: plugin: ****** connecting. ******
[INF]: Applying scheduled changes.
[INF]: No scheduled changes.
[DBG]: plugin: ****** rc = Operation succeeded. ******
[DBG]: plugin: ****** session start. ******
[INF]: Session 16 (user "root") created.
[DBG]: plugin: ****** rc = Operation succeeded. ******
[DBG]: plugin: ****** trying to install module data. ******
[DBG]: plugin: ****** rc = Operation succeeded. ******
[DBG]: plugin: ****** trying to apply changes. ******
[ERR]: Data of internal module "sysrepo" cannot be modified. (path: /sysrepo:sysrepo-modules)
[DBG]: plugin: ****** rc = -1217044961. ******

```

The code:

```C
 SRP_LOG_DBGMSG("****** connecting. ******");
    rc = sr_connect(0, &connection);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }
    SRP_LOG_DBG("****** rc = %s. ******", sr_strerror(rc));

    /* start session */
    SRP_LOG_DBGMSG("****** session start. ******");
    rc = sr_session_start(connection, SR_DS_RUNNING, &session); // SR_DS_OPERATIONAL gives same result
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }
    SRP_LOG_DBG("****** rc = %s. ******", sr_strerror(rc));

    /* setup data for the module */

    struct lyd_node* data;
    data = lyd_parse_path((struct ly_ctx *)sr_get_context(connection), xml_full_path, LYD_XML, LYD_OPT_TRUSTED);
    if (data != NULL)
    {
        SRP_LOG_DBGMSG("****** trying to install module data. ******");
        rc = sr_edit_batch(session, data, "merge");
        SRP_LOG_DBG("****** rc = %s. ******", sr_strerror(rc));
    }
    else
    {
        SRP_LOG_DBG("****** data is NULL, so file is empty? path to file: %s. ******", xml_full_path);
        SRP_LOG_DBG("****** libyang error: %s", ly_errmsg((struct ly_ctx *)sr_get_context(connection)));
    }

    SRP_LOG_DBGMSG("****** trying to apply changes. ******");
    rc = sr_apply_changes(session, 0, 0);
    SRP_LOG_DBG("****** rc = %d. ******", sr_strerror(rc));

    /* loop until ctrl-c is pressed / SIGINT is received */
    signal(SIGINT, sigint_handler);
    signal(SIGPIPE, SIG_IGN);
    while (!exit_application) {
        ;
    }
```


BR,
Adam

**Comment by michalvasko** [comment]
Hi Adam,
well, if you want to have the `edit` input as a XML data, this is the way to do it and there is no other choice.

And I had a feeling I was forgetting something and the error you got was that. When parsing the edit, you must use 2 flags `LYD_OPT_EDIT | LYD_OPT_TRUSTED`. I do not want to go into details as for the exact reason. Suffice to say it is a problem of the *libyang* API and the one we already have implemented in the new *libyang* version solves this.

Regards,
Michal

**Comment by kramarz89** [comment]
Hi Michal,

I am affraid that doesnt work either,

```

[DBG]: plugin: ****** connecting. ******
[INF]: Applying scheduled changes.
[INF]: No scheduled changes.
[DBG]: plugin: ****** rc = Operation succeeded. ******
[DBG]: plugin: ****** session start. ******
[INF]: Session 23 (user "root") created.
[DBG]: plugin: ****** rc = Operation succeeded. ******
[DBG]: plugin: ****** libyang error: Unknown element "sim".
[DBG]: plugin: ****** trying to apply changes. ******
[DBG]: plugin: ****** rc = -1217241712. ******
```
Please remember sim is `config false` container 

BR,
Adam

**Comment by michalvasko** [comment]
Hi Adam,
right, so then your use-case is simply not covered by *libyang* at all, unfortunately. Then, if you insist of having the edit as XML data, keep using only the trusted flag and then modify the parsed data. Specifically, you should remove all the top-level default values (containers) that were added by *libyang*. If you do not want to keep any of them (meaning delete some nodes instead of adding them) you can do simply
```C
LY_TREE_FOR_SAFE(data, next, elem) {
  if (elem->dflt) {
    lyd_free(elem);
  }
}
```

Regards,
Michal

**Comment by kramarz89** [comment]
Hi Michal,

Thank you for your support. Had to update everything to latest, netopeer/libnetconf as well since started getting some strange errors ;-)
However after all everything works as expected, doing get from the client properly returns the data :) thanks!

So, since my case is "unusuall" so a more proper way of working in case of other models that have both operational and configuration data, is to:

- setup one session and connection to `SR_DS_OPERATIONAL` and the operational data callbacks (`sr_oper_get_items_cb`) for the `config false` nodes.

- And setup another session and connection for the `SR_DS_RUNNING` to work with the configuration data in such models and those data I can set normally with my presented methodm using xml parsing and `sr_batch_edit`.

Is that correct way? :)

BR,
Adam

**Comment by kramarz89** [comment]
Also while at it, is there a way for the logs to show the actual application name together with method and line, instead of `plugin:` ?

like this:

`[DBG]: versioning (main:83): ****** trying to install module data. ******`
instead of 
`[DBG]: plugin: ****** trying to apply changes. ******`

BR,
Adam

**Comment by michalvasko** [comment]
Hi Adam,
as for the operational data, yeah, I suppose [pull subscriptions](https://netopeer.liberouter.org/doc/sysrepo/master/index.html#oper_data) are more common.

But the "unusual" is not that you edit data (whether operational or configuration) but how you do it. It is much easier to use `sr_edit_item_str()` (and other similar functions). A trivial [example](https://github.com/sysrepo/sysrepo/blob/master/examples/sr_set_item_example.c) is included.

Finally, as for plugin logging, it is just basic so it does not support printing any additional information by default. But you can improve it with minimal effort, just write your own logging macro and use `__FILE__` and `__LINE__` compiler macros.

Regards,
Michal

**Comment by kramarz89** [comment]
Thanks :)
