### ISSUE TITLE
bug in application_changes_example

### ISSUE THREAD

**Issue by iGovindY** [sysrepo/sysrepo#1940]
In application_changes_example.c file

```
rc = sr_get_changes_iter(session, "//." , &it);
```
doesn't fetch all changes, if edit-config is having two entries for top level List in a yang module.
It only gives 1 entry changes.

I think working second argument is : ```/module_name:*//."```.

Also, not sure why ```/module_name:*``` doesn't give all changes, It used to work with older sysrepo.

**you can test with example like below.**
```
module: _3gpp-common-managed-element
  +--rw ManagedElement* [id]
     +--rw id

```

**Comment by michalvasko** [comment]
Hi,
please update *liybang*, the xpath should actually work. As for why `/module_name:*` does not work, look [here](https://github.com/sysrepo/sysrepo/blob/master/CHANGES#L2).

Regards,
Michal
