### ISSUE TITLE
ABORT hangs untill timeout for netopeer subscription modules

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1941]
Hi,

We have some configuration management RPCs which are used for fetching remote netconf configuration files and apply that to sysrepo.

Configuration like:
- There are some changes in netopeer subscribed modules (ietf-keystore, ietf-netconf-acm or ietf-netconf-server)
- Invalid configuration in other module, which causes callback failure. Not libyang validation failure.

When a subscriber callback fails then abort is published to first netopeer subscriber module and it hangs there till timeout.

The same configuration works fine(whole config fails and returns expected error) if applied using netconf editconfig rpc.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
I would have to reproduce it to have any chance of fixing it because it seems like a complex use-case. Also, you are saying it works with standard `edit-config` so I am not sure there really is a problem and just an expected dead lock of your operations.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

I dont know inner details, so could you please explain how below things work,
When `ietf-netconf-server` configured from rpc (this rpc is running as sysrepo plugin)...
1. Do Netopeer2 server handle changes it susbscribed to or waits for rpc execution to complete?
2. What will Netopeer2 server do if ABORT comes for same configuration?

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
thinking about this gave me an idea for a new test and sure enough, it failed the way you described it. So, please try the latest *sysrepo*, there is a good chance it was fixed.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thank you for the fix. Usecase working now.

Thanks & Regards,
Sriram.K
