### ISSUE TITLE
Question/understanding sr_set_item_str with order-by user leaf-list

### ISSUE THREAD

**Issue by bbergquist0930** [sysrepo/sysrepo#1942]
Environment:

- libyang - branch `devel` pulled and rebuilt today 2020-04-24
- libnetconf2 - branch `devel` pulled and rebuilt today 2020-04-24
- sysrepo - branch `devel` pulled and rebuilt today 2020-04-24
- netopeer2 - branch 'devel-server` pulled and rebuild today 2020-04-24

I added the `ll` to the examples.yang module 
```
    container cont {
        leaf l {
            type string;
        }
       leaf-list ll {
            ordered-by user;
            type string;
       }
    }
```

I ran 
```
sudo ./application_changes_example examples /examples:cont/ll
```
to see the change callback and the changed data.  I then ran 
```
brett@brett-Precision-7740:~/git/netconf/sysrepo/build/examples$ sudo ./sr_set_item_example /examples:cont/ll foo
Application will set "/examples:cont/ll" to "foo".
brett@brett-Precision-7740:~/git/netconf/sysrepo/build/examples$ sudo ./sr_set_item_example /examples:cont/ll bar
Application will set "/examples:cont/ll" to "bar".
brett@brett-Precision-7740:~/git/netconf/sysrepo/build/examples$ sudo ./sr_set_item_example /examples:cont/ll baz
Application will set "/examples:cont/ll" to "baz".
```
This correctly update the `ll` leaf list
```
brett@brett-Precision-7740:~/git/netconf/sysrepo/build/examples$ sudo sysrepocfg -X -d running -m examples
<cont xmlns="urn:examples">
  <ll>foo</ll>
  <ll>bar</ll>
  <ll>baz</ll>
</cont>
brett@brett-Precision-7740:~/git/netconf/sysrepo/build/examples$ 
```
I wonder how one can insert an element into a specific position with `sr_set_item_str` or for `sr_set_item` for that matter.  I looked at the `test` directory.   I also wondered how an item could be updated.  

I see code like this in the tests 
```
    ret = sr_set_item_str(sess, "/test:ll1[.='30052']", NULL, NULL, 0);
```
but have no idea what that is supposed to do. 

So is it possible to update a ordered-by user leaf-list or add to an ordered-by user leaf-list into a specific position (ie before/after some existing item)?

I do know that it can be moved using something like 
```
    ret = sr_move_item(st->sess, "/test:ll1[.='-3']", SR_MOVE_FIRST, NULL, NULL, NULL, 0);
```

Also, just for information, I tried this under the (wrong) assumption that it would update an item replacing the item with the one specified

```
brett@brett-Precision-7740:~/git/netconf/sysrepo/build/examples$ sudo ./sr_set_item_example /examples:cont/ll[.=\'bar\'] xyzzy
Application will set "/examples:cont/ll[.='bar']" to "xyzzy".
```
This said it was going to do something and no error occurred but also no callback was invoked and the datastore was not updated.

**Comment by michalvasko** [comment]
Hi,
you could actually have used `sr_move_item()` for creating the nodes (at specific position) as well but it was not documented and was also missing support for the flags other edit functions use. Should be corrected now.

Regards,
Michal

**Comment by bbergquist0930** [comment]
That make sense.  Thank you for taking the time to look at this.
