### ISSUE TITLE
Failed to open shared memory (Function not implemented).

### ISSUE THREAD

**Issue by Julian-younger** [sysrepo/sysrepo#1947]
hi,Michal，
I have an embedded system using new sysrepo. And  failed to open shared memory (Function not implemented).
> [ERR]: SR: Failed to open shared memory (Function not implemented).
[ERR]: NP: Connecting to sysrepo failed (System function call failed).
[ERR]: NP: Server init failed.
[INF]: NP: Server terminated.

I find that  the embedded system can not use shm_open/shm_unlink function(maybe we use jffs2 filesystem),So I used  open/unlink to instead of it,and the same time I changed all the path to /dev/shm，it seems work well so far. 
AM I right？Does this solution be well？Thanks！

**Comment by michalvasko** [comment]
Hi,
well, whether you use shared memory files or normal ones, the interfaces should be exactly the same. So I would expect the only difference being the performance and it should work correctly.

Regards,
Michal

**Comment by Julian-younger** [comment]
I will get it.Thanks a lot.
