### ISSUE TITLE
Internal error (/path/to/sysrepo/src/shm_sub.c:1109)

### ISSUE THREAD

**Issue by Roky7250** [sysrepo/sysrepo#1949]
Hi, I am using sysrepo from master branch.
I am currently working on ietf-interfaces yang module.
Inside my source code for ietf-interfaces i have callback:

```
int not_supported(sr_session_ctx_t *session, const char *module_name, const char *xpath, sr_event_t event, uint32_t request_id, void *private_data)
{
	(void)module_name;
	(void)event;
	(void)request_id;
	(void)private_data;
	int rc;
    sr_change_oper_t op = {0};
    sr_change_iter_t* iter = NULL;
    sr_val_t* old_value = NULL;
    sr_val_t* new_value = NULL;

    rc = sr_get_changes_iter(session, xpath, &iter);
    if(SR_ERR_OK != rc)
    {
    	return rc;
    }
    while(SR_ERR_OK == sr_get_change_next(session, iter, &op, &old_value, &new_value))
    {
	    if((op == SR_OP_MODIFIED))
	    {
			SRP_LOG_ERR("Modifications not supported for %s", xpath);
	    	sr_set_error(session, xpath, "Modifications not supported for %s", xpath);
	    	return SR_ERR_OPERATION_FAILED;
	    }
    }

    sr_free_val(old_value);
    sr_free_val(new_value);
    sr_free_change_iter(iter);

    return SR_ERR_OK;
}
```
I am subscribed  on this callback like this:

```
		rc = sr_module_change_subscribe(session, "ietf-interfaces", "/ietf-interfaces:interfaces/interface/ieee802-dot1q-bridge:bridge-port/ieee802-dot1q-bridge:component-name",
				not_supported, NULL, 2, SR_SUBSCR_DEFAULT, &subscription);
		if(SR_ERR_OK != rc) break;
```

Also inside my code I have other callbacks that are setting other leafs inside module.
I use this callback to disable modifications for some of the leafs from configuration.
Problem is next, after I trigger not_supported callback I get correct error message on client side (that modification of that leaf is not supported), but on sysrepo-plugind I get error message :

`[ERR]: Internal error (/path/to/sysrepo/src/shm_sub.c:1109)`

After this I try to set some other leaf, whose modification is supported, but i get this on client side :

```
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  Callback event "change" with ID 2 processing timed out.
```
sysrepo-plugind stops on processing "change" event and after that it triggers callbacks with "abort" event.
After this no further edit-config rpc's are processed because of a timeout.
I tried to change callbacks priorities but it did not helped.
Also I tested code using devel branch but i had same problem.

Can you tell me what can be a problem?

Maybe this is related to https://github.com/sysrepo/sysrepo/issues/1927 issue.

Thanks in advance
Regards

**Comment by michalvasko** [comment]
Hi,
I can only ask you for the same as in #1927, the steps/data to reproduce the issue on `devel`. Including all the subscriptions you have (the relevant ones required to reproduce this).

Regards,
Michal

**Comment by Roky7250** [comment]
Hi, I attached dummy code for ietf-interfaces that causes this behavior (subscriptions relevant ones required to reproduce this). I also attached dummy configurations to reproduce this.
Tested on devel branch.
Steps to reproduce this are next:

**1 step**:
After installing plugin connect to netopeer2-cli and send start_config.xml.
you should get OK after edit-config.

**2 step**:
Send fail_config.xml using edit-config request. Using this config not_supported callback is going to be triggered and you should get this message on client side:
```
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        path:     /ietf-interfaces:interfaces/interface/ieee802-dot1q-bridge:bridge-port/ieee802-dot1q-bridge:enable-ingress-filtering
        message:  Modifications are not supported for /ietf-interfaces:interfaces/interface/ieee802-dot1q-bridge:bridge-port/ieee802-dot1q-bridge:enable-ingress-filtering
```
On sysrepo-plugind you should get comething like this:
```
[INF]: Processing "ietf-interfaces" "change" event with ID 2 priority 2 (remaining 12 subscribers).
[INF]: Processing "ietf-interfaces" "change" event with ID 2 priority 2 (remaining 12 subscribers).
[DBG]: plugin: not_supported is called.
[ERR]: plugin: Modifications are not supported for /ietf-interfaces:interfaces/interface/ieee802-dot1q-bridge:bridge-port/ieee802-dot1q-bridge:enable-ingress-filtering
[INF]: Processing "ietf-interfaces" "change" event with ID 2 priority 2 (remaining 12 subscribers).
[ERR]: Internal error (/home/devel/smb_share/sysrepo/src/shm_sub.c:1990).
[ERR]: Internal error (/home/devel/smb_share/sysrepo/src/shm_sub.c:1990).
[ERR]: Internal error (/home/devel/smb_share/sysrepo/src/shm_sub.c:1990).
[ERR]: Internal error (/home/devel/smb_share/sysrepo/src/shm_sub.c:1990).
[INF]: Finished processing "change" event with ID 2 priority 2 (remaining 11 subscribers).
[INF]: Finished processing "change" event with ID 2 priority 2 (remaining 10 subscribers).
[ERR]: Internal error (/home/devel/smb_share/sysrepo/src/shm_sub.c:1990).
[ERR]: Internal error (/home/devel/smb_share/sysrepo/src/shm_sub.c:1990).
[ERR]: Internal error (/home/devel/smb_share/sysrepo/src/shm_sub.c:1990).
[ERR]: Internal error (/home/devel/smb_share/sysrepo/src/shm_sub.c:1990).
[ERR]: Internal error (/home/devel/smb_share/sysrepo/src/shm_sub.c:1990).
[INF]: Finished processing "change" event (callback fail) with ID 2 priority 2 (remaining 10 subscribers).
[INF]: Processing "ietf-interfaces" "abort" event with ID 2 priority 2 (remaining 2 subscribers).
[INF]: Finished processing "abort" event with ID 2 priority 2 (remaining 1 subscribers).
[INF]: Processing "ietf-interfaces" "abort" event with ID 2 priority 2 (remaining 1 subscribers).
[INF]: Finished processing "abort" event with ID 2 priority 2 (remaining 0 subscribers).
```

**3 step**:
After this send timeout_config.xml using edit-config request. This configuration should pass because only leaf pvid is changed, but timeout happens. On client side you should get:
```
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  Callback event "change" with ID 3 processing timed out.
```

[dummy_code.zip](https://github.com/sysrepo/sysrepo/files/4544139/dummy_code.zip)


Thanks in advance
Regards

**Comment by michalvasko** [comment]
Could you also please include the modules (mainly *ieee802-dot1q-bridge* and *ieee802-dot1q-types*)? When I tried it with the ones I downloaded, I got
```
[ERR]: LY: Unknown element "priority0". (/ietf-interfaces:interfaces/interface[name='sw0p1']/ieee802-dot1q-bridge:bridge-port/traffic-class)
```
and it was correct, there is not such node defined right under the `traffic-class` container.

Regards,
Michal

**Comment by maksimvuleta** [comment]
ietf-interfaces, ieee802-dot1q-bridge and ieee802-dot1q-types included in the zip.
[yang.zip](https://github.com/sysrepo/sysrepo/files/4544582/yang.zip)

BR,
Maksim.

**Comment by maksimvuleta** [comment]
@michalvasko any news about this issue?
Are these sent modules helpful?
Do you need more data or something?

BR,
Maksim.

**Comment by michalvasko** [comment]
Hi Maksim,
no, I have successfully reproduced it, thanks for all the required input. It took me until today to fix this because while your issue itself was trivial (only READ lock held when WRITE lock was needed), another issue manifested. Basically, the subscribers did not always expect that some other subscriber may fail while they are processing an event and did not react appropriately and even produced some other (harmless) internal errors.

Now it should all be fixed and even the informational messages improved so that you can always see what was the situation when subscribers processed an event even though it is not important for general use. So, please try ti now.

Regards,
Michal

**Comment by maksimvuleta** [comment]
@michalvasko it works as expected now. 
Thank you for the fast fix. 

On some issue, I saw your comment that you are expecting to do the next master release maybe this week. Is it still the case?

Best regards,
Maksim.

**Comment by michalvasko** [comment]
Hi Maksim,
it got a bit complicated just like always so the current plan is to make the release in the beginning of the next week.

Regards,
Michal
