### ISSUE TITLE
question about changing permissions in the function sr_chmodown

### ISSUE THREAD

**Issue by fredgan** [sysrepo/sysrepo#1950]
Hi Michal,

the param ` mode_t perm`,its value between 00666 and 00777, such as 00777,00677,00667 and so on, I think these values are handled in the same way as its values which are less than 00666,is it better to modify  `if (perm > 00666 ) ` to `if (perm >00777)`  and the error message?

the code is as follows:
https://github.com/sysrepo/sysrepo/blob/a36b40df9ffcf63e07184ca72f8111da240faa58/src/common.c#L1766-L1784

**Comment by michalvasko** [comment]
Hi,
I am not sure I understand you point. The code looks this way because *sysrepo* does not use execute permissions for anything so they cannot be set. The reason mostly being that the startup data files that these permissions are set for are definitely not executable files.

Regards,
Michal

**Comment by fredgan** [comment]
Hi Michal,
Well, I reword it.

If I have a file `A` with permission: 00667 and another file `B` with permission 00467

A will report error: `"Only read and write permissions can be set."`
B will report error: `"Setting execute permissions has no effect."`

But as I see it, the two files should report the same error type because they are both executable files.

So I think why not change the if condition from `>00666` to > `00777`

Maybe I understand wrong.

**Comment by michalvasko** [comment]
Oh, I see. Okay, I have changed it but like you said, it definitely was not a big problem.

Regards,
Michal
