### ISSUE TITLE
Failed to uninstall a yang module

### ISSUE THREAD

**Issue by wjn111** [sysrepo/sysrepo#1952]
Hi,
The modules I have installed are as follows:
root@OpenWrt:~# sysrepoctl -l
Sysrepo schema directory: /etc/sysrepo/yang/
Sysrepo data directory:   /etc/sysrepo/data/
(Do not alter contents of these directories manually)

Module Name                  | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
ietf-keystore                | 2016-10-31 | Installed   | root:root           | 600         |                               |
ietf-ssh-server              | 2016-11-02 | Installed   |                     |             |                               |
ietf-tls-server              | 2016-11-02 | Installed   |                     |             |                               |
iana-crypt-hash              | 2014-08-06 | Installed   |                     |             |                               |
ietf-x509-cert-to-name       | 2014-12-10 | Installed   |                     |             |                               |
ietf-netconf-server          | 2016-11-02 | Installed   | root:root           | 600         |                               | listen ssh-listen tls-listen call-home ssh-call-home tls-call-home
ietf-netconf-monitoring      | 2010-10-04 | Installed   | root:root           | 600         |                               |
ietf-netconf-with-defaults   | 2011-06-01 | Installed   |                     |             |                               |
ietf-netconf                 | 2011-06-01 | Implemented | root:root           | 600         |                               | writable-running candidate rollback-on-error validate startup url xpath
ietf-netconf-acm             | 2018-02-14 | Imported    |                     |             |                               |
ietf-system                  | 2014-08-06 | Installed   | root:root           | 600         |                               | authentication local-users
ietf-datastores              | 2017-08-17 | Installed   |                     |             |                               |
ietf-yang-library            | 2018-01-17 | Installed   | root:root           | 600         |                               |
notifications                | 2008-07-14 | Installed   | root:root           | 666         |                               |
nc-notifications             | 2008-07-14 | Installed   | root:root           | 666         |                               |
ietf-netconf-notifications   | 2012-02-06 | Installed   | root:root           | 666         |                               |
cesnet-system-authentication | 2016-06-11 | Installed   |                     |             |                               |
cesnet-wireless              | 2016-02-02 | Installed   |                     |             |                               |
ietf-interfaces              | 2018-02-20 | Implemented | root:root           | 666         |                               |
cesnet-dhcp                  | 2016-02-02 | Installed   |                     |             |                               |
ietf-ip                      | 2018-02-22 | Implemented |                     |             |                               |

But when I uninstalled a yang module named cesnet-dhcp ,  I am getting the following errors :
root@OpenWrt:~# sysrepoctl --uninstall --module=cesnet-dhcp --revision=2016-02-02
Uninstalling the module cesnet-dhcp...
Error: Timeout has expired
Module can not be uninstalled because it is being used.
Uninstall operation failed.

But I didn't start netopeer2-server. Can you please help me resolving this issue.

**Comment by michalvasko** [comment]
Hi,
based on the error, it seems there is some client using the module. Maybe `sysrepod` itself or `sysrepo-plugind`? I am not able to really help you.

Note that you should be using the current *sysrepo* version (1.x) by now and not this obsolete one as our support for it has mostly finished.

Regards,
Michal

**Comment by wjn111** [comment]
Thank you very much for your reply. I found the problem. It's because sysrepo starts itself when I start openwrt. But I cannot kill them.

root@OpenWrt:/# ps | grep sysrepo
 2283 root      4960 S    /bin/sysrepod -d -l 0
 2284 root      3740 S    /bin/sysrepo-plugind -d -l 0
 6706 root      1040 R    grep sysrepo
root@OpenWrt:/# kill -9 2283
root@OpenWrt:/# kill -9 2284
root@OpenWrt:/# ps | grep sysrepo
 6758 root      4844 S    /bin/sysrepod -d -l 0
 6775 root      3740 S    /bin/sysrepo-plugind -d -l 0
 6779 root      1040 S    grep sysrepo

The contents of /etc/init.d/sysrepo are as follows:
#!/bin/sh /etc/rc.common

START=60
STOP=10

USE_PROCD=1
PROG_DAEMON=/bin/sysrepod
PROG_PLUGIN=/bin/sysrepo-plugind

start_service() {
    procd_open_instance
    procd_set_param command ${PROG_DAEMON}
    procd_append_param command -d -l 0
    procd_set_param respawn
    procd_close_instance

    procd_open_instance
    procd_set_param command ${PROG_PLUGIN}
    procd_append_param command -d -l 0
    procd_set_param respawn
    procd_close_instance
}

stop_service()
{
    kill -9 `ps | grep netopeer2-server | grep -v grep | awk '{print $1}'` >/dev/null 2>&1
    service_stop ${PROG_PLUGIN}
    service_stop ${PROG_DAEMON}
    rm -rf /var/run/sysrepo-subscriptions/*
}

How can I stop sysrepo?

**Comment by wjn111** [comment]
When I delete the /etc/init.d/sysrepo,  I solved the problem. Thank you.

**Comment by michalvasko** [comment]
Hi,
generally you simply send `SIGTERM` to `sysrepod` and it will terminate. Unless, of course, some daemon will not not start it again. In this case you should be fine with something like `service sysrepo stop` but I am not sure it will work on OpenWRT as well.

Regards,
Michal
