### ISSUE TITLE
Question related to NACM authorization failed

### ISSUE THREAD

**Issue by Roky7250** [sysrepo/sysrepo#1956]
Hi, I am using sysrepo, libyang, Netopeer2 and libnetconf2 from devel branch.
I installed ieee802-dot1ab-lldp yang module and also necessary ones for it.
After I perform edit-config request i get this message: 

ERROR
        type:     protocol
        tag:      access-denied
        severity: error
        path:     /ieee802-dot1ab-lldp:lldp/message-tx-interval
        message:  Access to the data model "ieee802-dot1ab-lldp" is denied because "devel" NACM authorization failed.

>

Can you tell me what I did wrong?
Thanks in advance
Regards

**Comment by michalvasko** [comment]
Hi,
actually, you did not do anything wrong, you have just not read the server [README](https://github.com/CESNET/Netopeer2/blob/devel-server/server/README.md#nacm). So, to fix this, you need to configure NACM of the server (meaning set some configuration for `ietf-netconf-acm` module). That can simply be disabling NACM altogether, which is fine for development, but should be never done for any kind of deployment.

Regards,
Michal

**Comment by Roky7250** [comment]
Hi, I managed to solve this problem last time, after changing permission to my 
/etc/sysrepo/ and /etc/sysrepo/data directories.

I have this problem now with newest devel versions of Netopeer2, sysrepo, libyang and libnetconf2.
Can you please help me with this.
I tried to set some ietf-netconf-acm configuration but it did not helped.
Every time i get error: " Access to the data model "ietf-netconf-acm" is denied because "devel" NACM authorization failed."

Can you please past some configuration that should pass, so I can send it?

Thanks in advance
Regards

**Comment by michalvasko** [comment]
Hi,
well, this is not really a problem of NACM. You see, you are trying to modify the NACM configuration itself, which is already enabled and using default values. Those include deny for all writes and that should be the error you are seeing. So, you must use the special "recovery" user that can access any modules no matter what (you can set this user UID for *neotpeer2* as `NACM_RECOVERY_UID`) and that is `root` by default, naturally. Once you write the new NACM configuration with `root`, it should immediately take effect.

Regards,
Michal

**Comment by mentalibor** [comment]
Hi, @Roky7250 !

I have the same problem and it appears that I managed to solve it. 

Check the last message in the following issue:

> [](https://github.com/CESNET/netopeer2/issues/658)

BR, 
Dalibor
