### ISSUE TITLE
sysrepo control publishing installed modules in NETCONF hello message

### ISSUE THREAD

**Issue by meghna-doshi** [sysrepo/sysrepo#1959]
Hi,
We have a requirement where:
1. We want to install yang modules say module1 and module2, with sysrepo, in netconf-server (using netopeer2-server)
2. In the hello exchange with NETCONF Client, dont want to publish module2.

How to control this?

Regards,
Meghna

**Comment by michalvasko** [comment]
Hi,
unfortunately, this is not supported as no such special hidden modules are defined for YANG/NETCONF. But if you are willing to change the code of *libnetconf2* or *netopeer2* you are using, there are several fairly simple ways of achieving this.

Regards,
Michal

**Comment by meghna-doshi** [comment]
Hi Michal,
Ok will you be able to help us with these changes. 
Can you guide us what needs to be done for this.

Regards,
Meghna

**Comment by michalvasko** [comment]
Hi,
okay, so with as fewer and as simpler changes as possible, I would look at `server_init()` function of *netopeer2*. The *libyang* context is first retrieved from the *sysrepo* connection [here](https://github.com/CESNET/Netopeer2/blob/devel-server/server/main.c#L625) and then used in `nc_server_init()` [here](https://github.com/CESNET/Netopeer2/blob/devel-server/server/main.c#L646). The modules in this context in effect determine how exactly will the hello message look like. While you must not modify the *libyang* context itself, you can simply create another context and load into it only modules from the *sysrepo* context that you want to be supported by NETCONF. But note that you will then have to destroy this new context manually after calling [nc_server_destroy()](https://github.com/CESNET/Netopeer2/blob/devel-server/server/main.c#L1301).

Just a note on "copying" modules from the *sysrepo* context into your new one. What should be possible is to simply look at the `filepath` in each `struct lys_module *module` and load that file as a module.

Regards,
Michal
