### ISSUE TITLE
Leaf values, equal to default, are not returned.

### ISSUE THREAD

**Issue by iljatab** [sysrepo/sysrepo#1961]
$ yanglint --version 
yanglint SO 1.7.9 

$ sysrepoctl --version 
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.54 (SO 
v5.4.13) 

$ netopeer2-server -V 
netopeer2-server 1.1.25 

Hi Michal,

I just upgraded all components to the above mentioned versions and found some (possible) regression.

Now `netopeer2-cli get-config` does **not** return leaf value, which is equal to default  value of this leaf but was set explicitly.
I mean, we do in our app `sr_set_item_str(sess,  leaf_xpath, "true", ...)` and `true` is a default value (in YANG model) for `leaf_xpath`.
And netopeer2-cli won't return `true` (unless we specify `--defaults report-all`, of course).
So sysrepo (or libyang?) considers the value as default value.

I definitely remember it was mentioned in the docs that if leaf value is set, it is not considered to be a default even if the values equals to the default one.
Hmmm... here it is in `struct sr_val_s::dflt` description:
`Flag for node with default value (applicable only for leaves). It is set to TRUE only if the value was implicitly set by the datastore as per module schema. Explicitly set/modified data element (through the sysrepo API) always has this flag unset regardless of the entered value. `

With that we got ~100 of our automated tests broken :-(

Also I am not sure what sr_get_value() will return now.

So is this an expected behavior now or is it a bug?

Ilja.

**Comment by michalvasko** [comment]
Hi Ilja,
I was significantly refactoring default values recently but was sure there were tests for use-cases such as yours, turns out there were not... Anyway, there are now and it should also work correctly again, sorry.

Regards,
Michal

**Comment by iljatab** [comment]
Thanks, looks working!
