### ISSUE TITLE
Unknown libyang error.

### ISSUE THREAD

**Issue by Roky7250** [sysrepo/sysrepo#1965]
Hi, I am using sysrepo, netopeer2, libyang and libnetconf2 from devel branches.
I was investigating SR_SUBSCR_UPDATE flag when subscribing a callback.

Few months ago, I created this issue https://github.com/sysrepo/sysrepo/issues/1639.
I solved this using thread, because SR_SUBSCR_UPDATE flag did not existed on master branch.
Now devel branch has it.
Basically now I want to remove this thread and solve this problem using SR_EV_UPDATE inside callback. Now am doing it inside ietf-interface module.

First I load configuration that contains speed and duplex (start_config).
After that I send configuration in which speed is deleted (fail_config).
My requirement: If someone deletes speed from configurations, duplex should be deleted also.
My code should also remove duplex leaf inside callback for speed.

Also code works other way around, if someone deletes duplex from configuration then
callback on duplex should delete speed from configuration.
I read sysrepo.h file related to SR_SUBSCR_UPDATE, so based on that, callbacks on speed and duplex have different priorities.

Steps to reproduce are:

**1 step:** 
After installing plugin connect to netopeer2-cli and send start_config.xml.
you should get OK after edit-config.

**2 step:**
Send fail_config.xml using edit-config request. Using this config speed_cb callback is going to be triggered and you should get this message on client side:
```
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  Unknown libyang error.

>
```

On sysrepo-plugind side there is log:
```
[INF]: Processing "ietf-interfaces" "update" event with ID 2 priority 4 (remaining 1 subscribers).
[DBG]: plugin: speed_cb is called.
[INF]: Successful processing of "update" event with ID 2 priority 4 (remaining 0 subscribers).
[INF]: Processing "ietf-interfaces" "update" event with ID 2 priority 3 (remaining 1 subscribers).
[INF]: Successful processing of "update" event with ID 2 priority 3 (remaining 0 subscribers).
```
On netopeer2-server there are error messages:
```
[ERR]: LY: Invalid arguments (lyd_insert_after()).
[ERR]: SR: Unknown libyang error.
[INF]: SR: Failed processing of "rpc" event with ID 2 priority 0 (remaining 1 su                                                                                             bscribers).
[ERR]: SR: Unknown libyang error.
[WRN]: SR: Event "rpc" with ID 2 priority 0 failed (libyang error).
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 1: thread 3 event new RPC.
[INF]: NP: Session 1: thread 3 event reply error.
```
I attached dummy code that creates this error.
[dummy-code.zip](https://github.com/sysrepo/sysrepo/files/4580420/dummy-code.zip)

NOTE: If I comment out for example callback on leaf duplex, code works fine.
Callback on speed will be triggered and duplex will be removed also.

NOTE: If I leave callback on duplex, but subscribe to it using SR_SUBSCR_DEFAULT flag, code works fine. Callback on speed will be triggered and duplex will be removed also.

NOTE: I am using combination of SR_SUBSCR_ENABLED | SR_SUBSCR_UPDATE flags when subscribing to speed and duplex callback, because my real code needs to apply startup configuration, meaning set speed and duplex values from startup to my device.

Point is, I need both of this callback to operate with SR_SUBSCR_UPDATE event.
My question is, am I doing something wrong, meaning am I violating concept of sysrepo, or should this work?

Thanks in advance
Regards

**Comment by michalvasko** [comment]
Hi,
okay, please try again now, should work. It was just a not covered case caused by lack of tests for this feature so I have added yours.

Regards,
Michal

**Comment by Roky7250** [comment]
Hi, I am having problem compiling everything.
When I do "make" for netopeer2 server I am getting this:
```
/home/devel/smb_share/Netopeer2/server/netconf.c: In function ‘np2srv_rpc_editconfig_cb’:
/home/devel/smb_share/Netopeer2/server/netconf.c:232:14: error: too few arguments to function ‘sr_validate’
         rc = sr_validate(session, 0);
              ^
In file included from /home/devel/smb_share/Netopeer2/server/netconf.c:26:0:
/usr/local/include/sysrepo.h:961:5: note: declared here
 int sr_validate(sr_session_ctx_t *session, const char *module_name, uint32_t timeout_ms);
     ^
/home/devel/smb_share/Netopeer2/server/netconf.c: In function ‘np2srv_rpc_validate_cb’:
/home/devel/smb_share/Netopeer2/server/netconf.c:619:14: error: too few arguments to function ‘sr_validate’
         rc = sr_validate(session, 0);
              ^
In file included from /home/devel/smb_share/Netopeer2/server/netconf.c:26:0:
/usr/local/include/sysrepo.h:961:5: note: declared here
 int sr_validate(sr_session_ctx_t *session, const char *module_name, uint32_t timeout_ms);
     ^
CMakeFiles/serverobj.dir/build.make:86: recipe for target 'CMakeFiles/serverobj.dir/netconf.c.o' failed
make[2]: *** [CMakeFiles/serverobj.dir/netconf.c.o] Error 1
CMakeFiles/Makefile2:137: recipe for target 'CMakeFiles/serverobj.dir/all' failed
make[1]: *** [CMakeFiles/serverobj.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

```
I am using:
1. sysrepo from devel branch, commit 70eadec1d5dadbf199045c2fa14f04fcc45fd576
2. Netopeer2 from devel-server branch, commit 83012918f76a966591bbdce4c27277c86aade469
3. libyang from devel branch, commit 0599d13c142854215139580ba778ff2cbd23eb53
4. libnetconf2 from devel branch, commit adbf015c5992389b0c535105df55fbbf3f58d9b6

Regards

**Comment by michalvasko** [comment]
Hi,
right, sorry about the chaos but there really was no way of avoiding it. Please switch to `devel` branch for `netopeer2` and use that one instead of `devel-server` from now. After some time `devel-server` will be removed as it is obsolete and *neotpeer2* now follows the same organization as other projects and so even the `branch` name is now the same.

Regards,
Michal

**Comment by Roky7250** [comment]
Hi, I switched to devel branch for Netopeer2. Installation went ok, but now I am getting this error after I try connect to localhost:
```
ly ERROR: Unable to use search directory "/usr/local/share/yang/modules" (No such file or directory)
nc ERROR: Loading base NETCONF schema failed.
cmd_connect: Connecting to the localhost:830 as user "devel" failed.
```
Regards

**Comment by michalvasko** [comment]
Hi,
sorry, my fault, please update *libnetconf2* and it should work again without errors.

Regards,
Michal
