### ISSUE TITLE
Question: how is "sysrepocfg -w" supposed to be used

### ISSUE THREAD

**Issue by bbergquist0930** [sysrepo/sysrepo#1966]
There is not really much documentation on this option or an example that I can find.  Is this the correct mechanism to use to load initial configuration into the "startup" datastore?  The online help says
```
Set the configuration from a file as the initial one for a new module only scheduled
                               to be installed
```
What I find is that if I have no sysrepo connections, then of course the module will be installed.  Is this option only useful when the module cannot be installed because of existing connections?

I guess I just don't understand how this option is supposed to be used and in what context.

**Comment by bbergquist0930** [comment]
So I guess it is to support what this is testing in the test cases
```
    /* no startup data set so it should fail and remain scheduled */
    ret = sr_install_module(st->conn, TESTS_DIR "/files/mandatory.yang", TESTS_DIR "/files", NULL, 0);
    assert_int_equal(ret, SR_ERR_EXISTS);

    /* set startup data */
    ret = sr_install_module_data(st->conn, "mandatory", data, NULL, LYD_XML);
    assert_int_equal(ret, SR_ERR_OK);

    /* apply scheduled changes */
    sr_disconnect(st->conn);
    st->conn = NULL;
    ret = sr_connection_count(&conn_count);
    assert_int_equal(ret, SR_ERR_OK);
    assert_int_equal(conn_count, 0);
    ret = sr_connect(0, &st->conn);
    assert_int_equal(ret, SR_ERR_OK);
```
From that I guess:

- for a module that cannot be loaded with an empty configuration (ie. mandatory YANG leafs), use `sysrepoctl --install <module-path>` and then use `sysrepocfg -w <data-file-path>` to provide the initial configuration
- for a module that can be loaded with an empty configuration, use `sysrepoctl --install <module-path>` and then use `sysrepocfg --import <import-file-path> -m <module-name>` or `sysrepocfg --edit=<edit-file-path>`

Does that sound correct?

**Comment by michalvasko** [comment]
Hi,
if you update to the latest `devel`, you will see the [description](https://github.com/sysrepo/sysrepo/blob/devel/src/executables/sysrepocfg.c#L76) was somewhat improved. However, full explanation should always be found in the corresponding API [function](https://github.com/sysrepo/sysrepo/blob/devel/src/sysrepo.h#L469). `sysrepocfg` is just a simple tool providing interface for the API in the command line.

So, you are right about the usage. The whole point of this is to make sure the datastore is never invalid.

Regards,
Michal

**Comment by bbergquist0930** [comment]
Thanks Michal.  My confusion came from the "new module only scheduled to be installed".   My testing has been with YANG modules that are installed right away when no connections exist.  I did not test with a mandatory node and note that the module was only scheduled to be installed (N flag from sysrepoctl).

I sort of wish that this function be part of sysrepoctl instead of sysrepocfg.  To me it is related to the installation of a module and the module cannot be fully installed without this functionality.  So this way one could do something like

sysrepoctl --install <module-path> --init <initial-data-path>

and have everything to install a module and its initial data, if any, in one fell swoop.

I do appreciate your time to answer back, however!

**Comment by michalvasko** [comment]
Hi,
I understand that and I actually wanted to include it in *sysrepoctl* but I did not when I saw that I would have to add several new parameters, which already were in *sysrepocfg*. But such an `--init` parameter is not really desirable, you should set `startup` data using *sysrepocfg* after the module is installed, if you can.

Regards,
Michal
