### ISSUE TITLE
Clear specific modules in operational datastore with sysrepo API

### ISSUE THREAD

**Issue by lswanderleygit** [sysrepo/sysrepo#1968]
Using the method delete_item() - using Python bindings - from Sysrepo api is possible clean specific modules from datastores Running and Candidate, but this method doesn't work to datastore Operational. Is there any way to clean modules of operational datastore without restart listeners? Or any method to clean un datastore?.

**Comment by michalvasko** [comment]
Hi,
what exactly do you mean by "clear operational datastore"? While `running` or `candidate` are writable configuration datastores, `operational` is a read-only datastore and you modify its contents only indirectly using `running` change subscription, `operational` subscriptions, or pushing some operational data (the last can be considered direct but is quite specific).

Regards,
Michal

**Comment by lswanderleygit** [comment]
I mean a way to clean up the Operational datastore or a specific module. The delete_items(path_module) function does not work for the Operational datastore, but it works for Candidate and Running.
