### ISSUE TITLE
Not getting changes if default leafs configured

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1973]
Hi,

On sysrepo and libyang latest devel branch observing new issue which used to work earlier.
I am using sysrepocfg to configure a module.
If I configure a leaf with its default value then that leaf is not present in changes.
These default leafs are mostly `augmented` defaults.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
I believe this was fixed by f4712da78b568e2d1662bce1fe63292b3d8610ca, what version are you using?

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

This is the issue in all latest devel.
```
yanglint --version;sysrepocfg --version                                                                                                                                                                                                                                                                                                                                   
yanglint SO 1.7.11                                                                                                                                                                                                                                                                                                                                                          
sysrepocfg - sysrepo configuration manipulation tool, compiled with libsysrepo v1.4.59 (SO v5.5.1)
```

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
you will have to provide a specific example because I have tried it with the `defaults` module in tests, when I set `/cont/interval` to `30`, `sysrepocfg` correctly printed it whereas it did not before.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Actually `sysrepocfg` works fine.
The issue is with `sr_get_module_change_` callbacks not receiving changes if I configured some leaf with its default value.

I am trying to reproduce the scenario with minimal examples, will share them soon.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
oh, then it is intentional, *sysrepo* changes `dflt` flags transparently. Meaning your callbacks are called only when a value actually changes, why would you care that its default state was changed?

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thank you for the information,

I hope default leafs of global containers will be provided to subscribers in `SR_EV_ENABLED` as `CREATED`. Correct me if I am wrong. And no data will be provided untill value changes.

But in earlier commits it used to work even `dflt` flag change.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
you described how it meant to work all along, if you got a callback change only for `dflt` flag changes, then it was wrong. I seem to remember that it really worked this way in very early versions of *sysrepo* 1.x but after someone pointed it out, I immediately changed it, it made no sense.

Regards,
Michal
