### ISSUE TITLE
Question related to default values

### ISSUE THREAD

**Issue by Roky7250** [sysrepo/sysrepo#1976]
Hi, I am using sysrepo, libnetconf2, libyang and Netopeer2 from devel branches.
I have question related to default values of leafs inside yang.

For example lets use ietf-interfaces yang module.
I am subscribed to callbacks for this module with SR_SUBSCR_ENABLED flag.
I am applying startup configuration to device when sysrepo-plugind is booting.
I have callback on leaf enable inside list interface.

My startup configuration is:
```
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interface>
    <name>lo</name>
    <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
    <enabled>true</enabled>
  </interface>
  <interface>
    <name>eth0</name>
    <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
  </interface>

...
  </interfaces>
```
Interface "eth0" does not contain leaf enabled, but its default value inside yang is "true".
So when sysrepo-plugind is booting, callback for leaf enabled for interface eth0 will be triggered with ADD operation and its value will be "true", so my callback will try to enable this interface, but my tool does not support it.

So my question is, how to disable this. How to disable this default values to affect my startup configuration, because in my startup for interface "eth0" I do not have leaf enabled?

Can I turn of this option somehow?

Thanks in advance
Regards

**Comment by michalvasko** [comment]
Hi,
I am not really sure what is it you are trying to do but you can always ignore any `default` values because they have the `dflt` flag set. I would not advise it, though.

Regards,
Michal

**Comment by Roky7250** [comment]
Thanks for you comment, it solved my problem.

Regards
