### ISSUE TITLE
[Queries] Sysrepo behavior when configuration xml has multiple modules data

### ISSUE THREAD

**Issue by sriramkandukuri** [sysrepo/sysrepo#1977]
Hi,

Lets say there are 5 modules in system `a...e`

And below xml

```xml
<a> //data// </a>
<c> //data// </c>
<e></e>
```

1. Does importing this xml deletes data of `b,d,e` or only `e` ?
a. if it deletes modules which are not present is there a way to avoid such behavior?
2. Does merging this xml deletes `e` ?
3. Is there a way to merge/import data of multiple modules from single data file or lyd_tree without deleting the modules data which are not present in file or tree?

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
the XML example is quite vague so I will answer as if module `a` had all data in a container named `a` and similarly for the rest of the modules.

1. It effectively deletes data of `b`, `d`, and `e` (based on the initial assumption). Think `copy-config` behavior. You can avoid this by using `edit-config` instead with `replace` as the default operation when speaking in NETCONF terms. As for sysrepo, you can achieve this also by not using import `-I` but merge `-E` operation of *sysrepocfg* instead.
2. No, it depends on the type of `e`. If it is a non-presence container like I assumed at the beginning, only all its descendants are removed so only the NP container is left. But that has no meaning and it behaves as an empty configuration. But if `e` is a leaf, it would set that leaf to a string of length 0 (which may be valid).
3. I think I have already answered.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thank you for the confirmation.
If I merged data using `-E` sysrepo tries to merge the existing module data with data given in xml file right? Or will it import at the module level.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Wen in doubt, the [source code](https://github.com/sysrepo/sysrepo/blob/master/src/executables/sysrepocfg.c#L370) can always provide all the information. But it is the former.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Thank you for the information.

Thanks & Regards,
Sriram.K
