### ISSUE TITLE
Query on SR_EDIT_ISOLATE

### ISSUE THREAD

**Issue by rosy8** [sysrepo/sysrepo#1979]
Hi Michal,

As per the new sysrepo doc,

SR_EDIT_ISOLATE --- Create new operation separately, independent of all the previous operations. Since all the operations are concatenated into one edit tree, it may happen that 2 incompatible operations are set and an error is observed. This flag can in those cases be used. 

In our framework, user has the flexibility to configure/change parameters before triggering commit.
For the set operation, we have used sr_set_item_str with edit flag SR_EDIT_ISOLATE as shown below.

sr_set_item_str(session_context, path, value, "", SR_EDIT_ISOLATE);

It works perfectly fine in a normal case scenario, however, if a user enters invalid parameters in the config tree, then all the previously configured parameters are found to get erased (This includes even the deletion of already configured mandatory parameters).

 [ERR] Value "3640" does not satisfy the constraint "1..3600" (range, length, or pattern).
 [ERR] Failed to create node "leaf_abc" as a child of "XYZ".
 [ERR] Invalid datastore edit.

I would appreciate it if you could give some input on how to handle this scenario as this leads to further validation failures.(For example- Deletion of already configured mandatory parameters )

Thank you in advance.

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
this feature was not really finished properly, which should be now. Specifically, you can easily determine when the whole edit was cleared or not based on the error. Also, in most cases it should not be the case and when you use the `SR_EDIT_ISOLATE` flag, it will never happen. That should solve your problems.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

Ohh.  Thank you for addressing the issue quickly.
Basically it should clear only the node where validation fails .
Will test and update you.

Regards,
Rosy

**Comment by rosy8** [comment]
Hi Michal,

I did one round of testing and do find the issue to be resolved.
Thank you.

Regards,
Rosy
