### ISSUE TITLE
Permission issue with Read-Only User

### ISSUE THREAD

**Issue by paddyvgc** [sysrepo/sysrepo#1982]
I am trying to access data from a yang file which has permission of 664 . 
For root users - read/write access and for other non-root users - read-only access.
I am using two user accounts here , root (read/write access )and Jon (read-only access).
When I try to access yang status data (dp_get_items_susbscribe) from user  Jon , it is throwing below error:

daemon.err sysrepod[3062]: [ERR] Insufficient permissions to access persist data file 'xx.yang'.
daemon.err sysrepod[3062]: [ERR] Unable to load persist data tree for module 'xx' Operation not authorized.

This is expected as Jon doesn't have write access to the file.

When I try to access yang status data from root , it is showing data properly. 
While a show status is done from root user and after that show status is executed from user Jon , status data is shown properly for user Jon instead of showing 'Operation not authorised' .

It seems like  dp_get_items_subscribe is retaining the previous subscription of user root and showing data for user Jon instead of blocking.
Is the behaviour I'm seeing a sysrepo bug, or have I misunderstood something about how the access controls should work?

Versions:
sysrepo = 0.7.7

**Comment by michalvasko** [comment]
Hi,
I do not really understand the problem, you are seeing status data for the read-only user? But he has read access so it seems correct to me. Anyway, you are using a really old version so in any problems I can only suggest you use at least *sysrepo* 0.7.8 or 0.7.9 if not the current release 1.4.x.

Regards,
Michal

**Comment by paddyvgc** [comment]
Hi Michal,
Thanks for the response.

Here am trying to get the operational data of an xpath via sr_dp_get_items_subscribe.
So for operation data first set_item will be called then get_item.
So here in my case If am directly going to get the operational data from User Jon , Operation not authorised will come which is expected only.
But if I try to get operational data from Jon after tying from root it is working without showing Operation not authorised. The issue seems to be like sr_dp_get_items_subscribe retains the previous session details of user root .
Am using the option SR_SUBSCR_PASSIVE for dp_get_items_subscribe.
I just want to confirm whether this an issue with the version am using.
Hope am clear now.
Please let me know if further details needed.

**Comment by michalvasko** [comment]
Hi,
there is some caching used in the legacy *sysrepo* and it is quite possible it is also (incorrectly) used here (it would explain the behavior if I understood it correctly) so it can be considered a feature.


Regards,
Michal

**Comment by paddyvgc** [comment]
Hi Michal,
So if this issue is due to caching problem , is it because of my incorrect usage or is this an issue with legacy sysrepo?
If it's an issue , do we have any patch for the same.

Could you please clarify?

**Comment by michalvasko** [comment]
Hi,
if I am right it is simply the legacy *sysrepo* feature, not caused by anything you did wrong. And in that case it works this way up to *sysrepo* 0.7.9, which is the latest legacy release. It should work properly in the current *sysrepo* and if not, I would fix it. That is not going to happen to the *sysrepo* you are using because its support has mostly ended.

Regards,
Michal

**Comment by paddyvgc** [comment]
Thanks Michal.
