### ISSUE TITLE
One question about the sysrepo callback

### ISSUE THREAD

**Issue by achudejiejie** [sysrepo/sysrepo#1984]
Hi,
Now I want to I want to get the modified data in the callback function of my subscription.
1.`mod_name = "rules";
    xpath = "/rules:rules";
    SR_CONFIG_SUBSCR(mod_name, xpath, np2srv_idle_test_cb);`
2.`> edit-config --target running --config=/home/fred/test/rule_cfg.xml
OK`
In np2srv_idle_test_cb, I can't get the data I modified through sr_get_items, sr_get_changes_iter, sr_get_change_tree_next.
What interface can I use to get the data I need?

Regards,
Fred

**Comment by michalvasko** [comment]
Hi,
what *sysrepo* version are you using? You may be experiencing a major bug that was fixed by 7aeace4b88a4d7bf5c94c38af58b5b395af9543c.

Regards,
Michal

**Comment by achudejiejie** [comment]
Hi,
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.59 (SO v5.5.1)
The version I used has fixed the problem you said.
What I want to get is the modified node data, for example:
<rules xmlns="urn:rules">
  <rule>
    <customer_id>1</customer_id>
    <sip>"1.1.1.1"</sip>
    <dip>"2.2.2.2"</dip>
  </rule>
</rules>
After modification：
<rules xmlns="urn:rules">
  <rule>
    <customer_id>1</customer_id>
    <sip>"3.3.3.3"</sip>
    <dip>"2.2.2.2"</dip>
  </rule>
</rules>
The data I want to get is the value of sip changed from 1.1.1.1 to 3.3.3.3.
But I don't know how to get it

Regards,
Fred

**Comment by achudejiejie** [comment]
Add xml content：
`<rules xmlns="urn:rules">
  <rule>
    <customer_id>1</customer_id>
    <sip>"1.3.3.3"</sip>
    <dip>"2.2.2.2"</dip>
  </rule>
</rules>`

**Comment by michalvasko** [comment]
Hi,
I do not think I fully understand, you should simply get the changes in the callback. What exactly is the problem with those?

Regards,
Michal

**Comment by achudejiejie** [comment]
Thanks Michal! This problem has been solved
