### ISSUE TITLE
knowing a module is installed or not

### ISSUE THREAD

**Issue by ghost** [sysrepo/sysrepo#1987]
Hi Michal,

Is there any api which i can use to know a specific module has been installed or not. i meant something other than sysrepoctl, where i can specify the  module name and can find out its installation status.

**Comment by michalvasko** [comment]
Hi,
there are actually 3 ways you can do this. The simplest one is probably to get the context from a connection (`sr_get_context`) and then examine it (`ly_ctx_get_module`). If the module is present **and** implemented, it is installed.

Or you can use data from `sysrepo` internal private module (`sr_get_module_info`, this is how `sysrepoctl` does it) or `sysrepo-monitoring` internal public module (simply calling `sr_get_data` on `operational` filtering only this module data). If you find an entry for the module, it is installed.

Regards,
Michal

**Comment by Sneha-star** [comment]
Thank you Michal.
