### ISSUE TITLE
Permission change in sysrepo "*.persist" file

### ISSUE THREAD

**Issue by paddyvgc** [sysrepo/sysrepo#1988]
Hi,

When I install a yang , I could see below sysrepo related files are created which includes persist file too.

-rw-------    1 root     config            May 20 05:26 paddy-check.persist
-rw-------    1 root     config            May 20 05:26 paddy-check.running
-rw-------    1 root     config            May 20 05:26 paddy-check.running.lock
-rw-------    1 root     config            May 20 05:26 paddy-check.startup
-rw-------    1 root     config            May 20 05:26 paddy-check.startup.lock

Whatever permission I am giving while installing the yang is the same to all the files created.
Is it possible to change the permission of persist file alone?
Will it have any impact?

Thanks

**Comment by michalvasko** [comment]
Hi,
my guess would be that you can change this, if you really need to and it should be fine. However, I am not certain and will not waste time making sure because that *sysrepo* is deprecated.

Regards,
Michal
