### ISSUE TITLE
"config false" lefref value is returned even if there is no referenced node

### ISSUE THREAD

**Issue by jabilmplane** [sysrepo/sysrepo#1989]
Hi. 

I'm playing with leafrefs. Seems I have found an issue.
Probably it is somehow connected to the following issuses:
https://github.com/sysrepo/sysrepo/issues/1806
https://github.com/sysrepo/sysrepo/issues/1876

**In the YANG model there is state leaf-list of leafrefs to the config data:**
test@test-VirtualBox:~$ cat jabil-yang-leaf-list.yang 
```
module jabil-yang-leaf-list {
        yang-version 1.1;
        namespace "urn:jabil:yang-leaf-list:1.0";
        prefix "jabil-yang-leaf-list";

        organization "Jabil";
        contact "www.jabil.com";
        description "Module to test the leaf-list statement";

        container root {
                list list1 {
                        key "name";
                        leaf name {
                                type string;
                        }
                }
                leaf-list values-ref {
                        config false;
                        type leafref {
                                path "../list1/name";
                        }
                }
        }
}
```

**Simple application to reply state data is:**
```
#include <stdio.h>
#include <string.h>
#include <signal.h>
#include <unistd.h>
#include <pthread.h>
#include "sysrepo.h"

volatile int exit_application = 0;
sr_conn_ctx_t *connection = NULL;

static int
module_state_cb(sr_session_ctx_t *session, const char *module_name, const char *xpath, const char *request_xpath,
uint32_t request_id, struct lyd_node **parent, void *private_data)
{
    printf("State datat requested.\n");
    *parent = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(session)),
                           "/jabil-yang-leaf-list:root/values-ref", (void *)"name1",
                           LYD_ANYDATA_CONSTSTRING, 0);
    lyd_new_path(*parent, sr_get_context(sr_session_get_connection(session)),
                           "/jabil-yang-leaf-list:root/values-ref", (void *)"name2",
                           LYD_ANYDATA_CONSTSTRING, 0);
    return SR_ERR_OK;
}

static void
sigint_handler(int signum)
{
    (void)signum;
     exit_application = 1;
}

int main(int argc, char **argv)
{
    sr_session_ctx_t *session = NULL;
    sr_subscription_ctx_t *subscription = NULL;
    int rc = SR_ERR_OK;

    sr_log_stderr(SR_LL_WRN);

    if ((rc = sr_connect(0, &connection)) == SR_ERR_OK &&
        (rc = sr_session_start(connection, SR_DS_RUNNING, &session)) == SR_ERR_OK &&
        (rc = sr_oper_get_items_subscribe(session, "jabil-yang-leaf-list", "/jabil-yang-leaf-list:root/values-ref",
                 module_state_cb, NULL, 0, &subscription)) == SR_ERR_OK)
    {
        signal(SIGINT, sigint_handler);
        signal(SIGPIPE, SIG_IGN);
        while (!exit_application)
        {
            sleep(1000);
        }
        printf("Application exit requested, exiting.\n");
    }
    sr_disconnect(connection);
    return rc ? EXIT_FAILURE : EXIT_SUCCESS;
}
```

**Now, I'm trying to get state data when there is nothing in list1. In this case I expect error to be returned, but it returns some valeus:**
```
> get --filter-xpath /jabil-yang-leaf-list:root
DATA
<root xmlns="urn:jabil:yang-leaf-list:1.0">
  <values-ref>name1</values-ref>
  <values-ref>name2</values-ref>
</root>
```

Thanks in advance!

**Comment by michalvasko** [comment]
Hi,
well, nothing requires that a reply to `get` is valid (it cannot really be if you use filters, for example), so that is fine. Moving to *sysrepo*, its `operational` datastore can be invalid according to NMDA specs and `config false` nodes are always part of this datastore. If you executed `sr_validate` on the `operational` datastore, you should get the error you expect. However, there is no way how to do this using existing apps (RPC `validate` is pre-NMDA so it does not support `operational` and this function is not exposed in `sysrepocfg`, could be easily added, though).

Regards,
Michal

**Comment by jabilmplane** [comment]
@michalvasko, thanks for the reply.

But, in this case, what is the difference between leaf and leafref?

https://tools.ietf.org/html/rfc7950#section-9.9 says that:
"If the "require-instance" property (Section 9.9.3) is "true", there
   MUST exist a node in the data tree, or a node with a default value in
   use (see Sections 7.6.1 and 7.7.2), of the referred schema tree leaf
   or leaf-list node with the same value as the leafref value in a valid
   data tree.
"
require-instance is true by default.


Thanks for your help!

**Comment by michalvasko** [comment]
Hi,
`operational` datastore has its own [rules](https://tools.ietf.org/html/rfc8342#page-15). While `leafref` or `require-instance` is not explicitly mentioned, I do believe it is a semantic constraint and it fits the "remnant configuration" use-case. The difference between a leaf of some type and a `leafref` to that type in this case is that when you manually call validation and the target does not exist, an error is returned only for the latter case.

Regards,
Michal
