### ISSUE TITLE
Question regarding actions

### ISSUE THREAD

**Issue by matth65** [sysrepo/sysrepo#1991]
Hello,

I have a question regarding the callbacks for YANG 1.1 actions that are nested under list entries. 

Suppose I have the following YANG model with a 'pause' action nested under list node 'my_entry'. 

```
container my_list {
    list my_entry {
        key name;
        leaf name {
            type string;
        }
        leaf device-id {
            type uint16;
            mandatory true;
        }
        action pause {
            description
                "Pause my_entry.";
        }
    }
}
```

My application subscribes to and receives a callback when I issue the following RPC.

```
<rpc >
  <action>
    <my_list>
      <my_entry>
      <name>my_name</name>
        <pause/>
      </my_entry>
    </my_list>
  </action>
</rpc>
```

My application receives the callback, but I'm not sure how to retrieve the list entry's key `<name>` from the callback. I believe the legacy Sysrepo provided it as part of the xpath parameter (e.g. /my_list/my_entry['name=my_name]/pause.

Note, this application is using Python bindings.

Regards,
Matt

**Comment by michalvasko** [comment]
Hi Matt,
I believe you can get a similar XPath if you call `path()` on a data node, could be the action directly. You are getting the data as a tree so you can manually examine the parents and look at the list keys. Also, you can keep using the `sr_val_t` callback variant if you want to and there the values will be in the same format as in the legacy *sysrepo*.

Regards,
Michal

**Comment by matth65** [comment]
Hi Michal,

I believe I am using the legacy sr_val_t version of the API. Please see below.

However, with the legacy sysrepo, the key was provided as part of the xpath parameter in the action callback. I was able to extract the key from the xpath parameter. The new version of sysrepo passes the op_path (simple operation path identifying the RPC/action) instead of the actual client's request_xpath which would include the key. 

I'm not sure how to extract the key from the parameters provided to the action callback with the new version of sysrepo. It seems like I would need both the op_path and the request_xpath like we have for operational callbacks. Then I could extract the key from request_xpath.

```
sr_conn = sr.Connection(sr.SR_CONN_DEFAULT)
sr_sess = sr.Session(sr_conn)
sr_rpc_sub = sr.Subscribe(sr_sess)
sr_rpc_sub.rpc_subscribe(xpath, sr_action_cb, None, 0, sr.SR_SUBSCR_DEFAULT|sr.SR_SUBSCR_CTX_REUSE)

def sr_action_cb(session, xpath, input, event, request_id, output, private_data):
    DEBUG("=== enter: sr_action_cb ===")

    # How do I get the list entry key from these parameters?
```

Regards,
Matt

**Comment by michalvasko** [comment]
Hi Matt,
ah, right, I seem not to have thought this through. Well, one solution is to use the tree API. The full action path should also be found in all of the input parameters. But the problem remains for action without input parameters. So, I could simply change the `op_path` for this callback back to `xpath`, which will be the full action XPath. It would allow for backwards compatibility with legacy *sysrepo* and require no NBC changes, what do you think? Nested notifications have the same problem so I would change those, too.

Regards,
Michal

**Comment by matth65** [comment]
Hi Michal,

I think changing op_path back to xpath would be fine. I'll also look at using the tree API.

Regards,
Matt

**Comment by michalvasko** [comment]
Okay, should now work like I described.

Regards,
Michal
