### ISSUE TITLE
Does sysrepo support duplicate checking of configuration data?

### ISSUE THREAD

**Issue by achudejiejie** [sysrepo/sysrepo#1993]
Hi ,

I want to check if my data is duplicated when edit-config the configuration data.
for example:
yang module

```
module rules {
  namespace "urn:rules";
  prefix fred;

  container rules {
      list rule {
      key "id";
      leaf id {
        type int8;
      }

      leaf sip {
        type string;
      }

      leaf dip {
        type string;
      }
    }
  }
}
```

xml
```
<rules xmlns="urn:rules" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" xc:operation="replace">
  <rule>
    <id>6</id>
    <sip>"1.1.1.1"</sip>
    <dip>"2.2.2.2"</dip>
  </rule>
  <rule>
    <id>7</id>
    <sip>"1.1.1.1"</sip>
    <dip>"2.2.2.2"</dip>
  </rule>
</rules>
```
sip and dip with id 7 are the same as sip and dip with id 8
Can sysrepo detect data duplication and give errors or warning?

Regards
Fred

**Comment by michalvasko** [comment]
Hi,
general YANG validation is of the main features so this is supported, naturally. Any YANG restrictions violation should be detected and properly reported. But note that not all the datastores must be valid so for some (`candidate`, `operational`) you would see the error only after manually validating them (by calling `sr_validate()`).

Regards,
Michal

**Comment by achudejiejie** [comment]
Hi, 
I am not sure whether my description is accurate.
Previous xml:
```
<rules xmlns="urn:rules" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" xc:operation="replace">
  <rule>
    <id>6</id>
    <sip>"1.1.1.1"</sip>
    <dip>"2.2.2.2"</dip>
  </rule>
</rules>
```
Modified xml:
```
<rules xmlns="urn:rules" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" xc:operation="replace">
  <rule>
    <id>6</id>
    <sip>"1.1.1.1"</sip>
    <dip>"2.2.2.2"</dip>
  </rule>
  <rule>
    <id>7</id>
    <sip>"1.1.1.1"</sip>
    <dip>"2.2.2.2"</dip>
  </rule>
</rules>
```
```
> edit-config --target running --config=/home/fred/test/rule_cfg.xml
OK
```
What I returned is still OK. How can I return an error?

Regards
Fred

**Comment by michalvasko** [comment]
Hi Fred,
oh, your description was accurate, I was just too hasty to reply. But I think you want to use the [unique](https://tools.ietf.org/html/rfc7950#section-7.8.3) YANG statement. If you do, *sysrepo* will enforce the constraint automatically.

Regards,
Michal

**Comment by achudejiejie** [comment]
Thank you very much Michal, this solves my problem perfectly!
