### ISSUE TITLE
Copy to running db failed

### ISSUE THREAD

**Issue by ghost** [sysrepo/sysrepo#1994]
Hi Michal,

While doing a testing, i got error that copy to running db failed . 
The reason was that the pipe(sr_evpipe) to write was not there.

In what all scenario the pipe is created? In the code I do see its being created for connection/subscription . But in box sometimes i do see the pipe and sometimes i donot see its being created.

Sometimes i do see, pipe not being available but still commit works fine. 
Appreciate if you could help me understand it.

**Comment by michalvasko** [comment]
Hi,
I have not encountered this and I assume you are doing something you should not be (manually moving/deleting some files). There is a pipe created for each subscriptions, that is all.

Regards,
Michal

**Comment by Sneha-star** [comment]
Hi Michal,

May be I would have deleted.
Will check that. So I should always see the pipe right once I do a connection/subscription?
Surprised why I don't see that but still, how things work fine.

**Comment by michalvasko** [comment]
The pipe is used for notifying the subscription there are new events. If it does not exist, the subscription cannot be notified, it is as simple as that.

Regards,
Michal
