### ISSUE TITLE
[new sysrepo devel]the yang contains identityref, install fail

### ISSUE THREAD

**Issue by xxyy0906** [sysrepo/sysrepo#1997]
Hi michalvasko,
    I now update sysrepo to the latest version of devel and found that the yang file cannot be imported. I hope you can give some suggestions.
    The following is a record of previous resolutions:
    (Since it is too long, I do n’t think I should reopen it)
    https://github.com/sysrepo/sysrepo/issues/1851
    Here are the steps to reproduce:

**1. sysrepoctl -v3 -a -i test-types.yang**
log:
 [INF]: Scheduled changes not applied because of other existing connections.
 [WRN]: Cleaning up after a non-existent sysrepo client with PID 7044.
        [INF]: Ext SHM was defragmented and 7632 B were saved.
        [INF]: Applying scheduled changes.
        [INF]: No scheduled changes.
        [INF]: Module "test-types" scheduled for installation.
        [INF]: Applying scheduled changes.
        [INF]: File "test-types.yang" was installed.
        [INF]: Module "test-types" was installed.
        [INF]: Scheduled changes applied.

 **2.sysrepoctl -v3 -i test.yang**
    log:
        [INF]: Applying scheduled changes.
        [INF]: No scheduled changes.
        [INF]: Module "test" scheduled for installation

  **3.sysrepoctl -v3 -i test-my.yang**
    log:
[INF]: Applying scheduled changes.
[WRN]: Missing required element "layer-protocol-name" in "haha". (path: /test:haha)
[WRN]: Failed to apply some changes, leaving all changes scheduled.
[ERR]: Data model "test" not found.
[ERR]: Importing "test" module into "test-my" failed.
[ERR]: Module "test-my" parsing failed.
sysrepoctl error: Failed to install module "test-my.yang" (libyang error)
        
   **4.sysrepocfg -W test.xml -f xml -m test -v3**
log:
[INF]: Applying scheduled changes.
[WRN]: Missing required element "layer-protocol-name" in "haha". (path: /test:haha)
[WRN]: Failed to apply some changes, leaving all changes scheduled.
[INF]: Session 18 (user "root") created.
[ERR]: Invalid value "x:desc" in "layer-protocol-name" element. (path: /test:haha/layer-protocol-name)
sysrepocfg error: Install module data failed (libyang error)

   **5.sysrepoctl -v3 -l**
log:
[INF]: Applying scheduled changes.
[WRN]: Missing required element "layer-protocol-name" in "haha". (path: /test:haha)
[WRN]: Failed to apply some changes, leaving all changes scheduled.
test                      N                                                                 
test-types              I 

   **6.version**
sysrepoctl -V
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.61 (SO v5.5.3)
sysrepocfg -V
sysrepocfg - sysrepo configuration manipulation tool, compiled with libsysrepo v1.4.61 (SO v5.5.3)
netopeer2-server -V
netopeer2-server 1.1.32

thanks!

this is testcase:
[yang-test.zip](https://github.com/sysrepo/sysrepo/files/4667865/yang-test.zip)

**Comment by michalvasko** [comment]
Hi,
these steps work fine but you must solve the error in step 3. It is possible this was changed, but the problem is simply that when *libyang* is loading `test-my.yang`, it cannot find `test.yang` that it imports (despite being in the same directory). Whenever there are imports you must always specify the search directory explicitly (add `-s .` in your case). It may seem redundant but it is not so when you have a complicated YANG hierarchy and want to make sure the right modules are imported.

Regards,
Michal

**Comment by xxyy0906** [comment]
Hi,
    Thank you for your suggestion, it works!
thanks!
