### ISSUE TITLE
Question about sr_subscr_options_t in sr_oper_get_items_subscribe

### ISSUE THREAD

**Issue by xxyy0906** [sysrepo/sysrepo#1999]
Hi michalvasko,
    I did a test,Added the following code in the main of oper_data_example.c
```code
    rc = sr_oper_get_items_subscribe(session, "test", "/test:test-oper", dp_get_items_cb, NULL, SR_SUBSCR_CTX_REUSE, &subscription);
    rc = sr_oper_get_items_subscribe(session, "test", "/test:test-oper", dp_get_items_cb_1, NULL, SR_SUBSCR_CTX_REUSE, &subscription);
```
 In fact, my purpose is to subscribe successfully and call back successfully,Because in my model, the container test-oper is a list, the source of the list data is not in one place, so I want to subscribe multiple times for an xpath,But the following error appears:
```
    [ERR]: Data provider subscription for "test" on "/test:test-oper" already exists.
```
I have tried to change sr_subscr_options_t, but still can not get the expected effect, what should I do,of course I am reading the manual now.

thanks!

**Comment by michalvasko** [comment]
Hi,
no special flags will help you in this case, you simply cannot subscribe to exact same `xpath` twice. But it is never a problem, you can easily subscribe once with a callback that will then call your other two callbacks, for example.

Regards,
Michal

**Comment by xxyy0906** [comment]
Hi michalvasko,
Thank you for your prompt reply, how can I complete 2 callbacks in "you can easily subscribe once with a callback that will then call your other two callbacks".

thanks!

**Comment by michalvasko** [comment]
Hi,
well, instead of
```C
rc = sr_oper_get_items_subscribe(session, "test", "/test:test-oper", dp_get_items_cb, NULL, SR_SUBSCR_CTX_REUSE, &subscription);
    rc = sr_oper_get_items_subscribe(session, "test", "/test:test-oper", dp_get_items_cb_1, NULL, SR_SUBSCR_CTX_REUSE, &subscription);
```
do
```C
int
dp_get_items_cb_both()
{
  dp_get_items_cb();
  dp_get_items_cb_1();
}

rc = sr_oper_get_items_subscribe(session, "test", "/test:test-oper", dp_get_items_cb_both, NULL, SR_SUBSCR_CTX_REUSE, &subscription);
```
That is all I meant. Of course, you will have to make sure the resulting data after both callbacks but based on what you said, you should be able to simply merge all data into the `parent` and have it working.

Regards,
Michal
