### ISSUE TITLE
Query on sysrepocfg import

### ISSUE THREAD

**Issue by nehajoy** [sysrepo/sysrepo#2001]
Hi,

I am using sysrepo version 0.7.7. I have the following yang model.

```
module test1 {
yang-version 1;
namespace "urn:ietf:params:xml:ns:yang:test1";
prefix test1;

organization
"XXX, Inc.";
contact
"XXX";
description
"Test1 Yang File";

revision 2020-04-03 {
description
"Initial Revision.";
}

leaf leaf1 {
type string;
default "leaf1";
description
"leaf1";
}

leaf leaf2 {
type string;
when "../leaf1 = 'leaf123'";
default "leaf2";
description
"leaf2";
}
}
```

Default configuration to be imported is given below
`<leaf1 xmlns="urn:ietf:params:xml:ns:yang:test1">leaf1</leaf1>`

I have set value 'leaf123' for leaf1. When trying to import the default configuration I am getting error that "The item expected to exist is missing". This is because it is trying to delete /test1:leaf2 which actually does not exist in sysrepo.

After investigating the sysrepo code sysrepocfg.c, srcfg_import_datastore function calls the following function 
```
static int
srcfg_convert_lydiff_deleted(const char *xpath)
{
    CHECK_NULL_ARG(xpath);
    int rc = sr_delete_item(srcfg_session, xpath, SR_EDIT_STRICT);
    if (SR_ERR_OK != rc) {
        SR_LOG_ERR("Error returned from sr_delete_item: %s.", sr_strerror(rc));
    }
    return rc;
}
```
Changing the SR_EDIT_STRICT flag to SR_EDIT_DEFAULT solves the issue. I wanted to know whether this change would cause any other issues.

Thanks,
Neha

**Comment by michalvasko** [comment]
Hi Neha,
I do not know and I do not really care, but my guess is that it should be fine. The *sysrepo* you are using is obsolete so we will not be doing any fixes ourselves.

Regards,
Michal
