### ISSUE TITLE
query: enum integer value in callback?

### ISSUE THREAD

**Issue by iGovindY** [sysrepo/sysrepo#2003]
is there a way to get associated integer value with the assigned name for the enum in sysrepo change callback?
in below case, for **EnumLeaf** if **Val2** is set than _"2"_

```
typedef EnumTypeWithValue{
                type enumeration {
                        enum Val1{
                                value 1;
                        }
                        enum Val2{
                                value 2;
                        }
                }
        }
--------------------
          leaf EnumLeaf{
                        type EnumTypeWithValue;
                }
```

**Comment by michalvasko** [comment]
Hi,
there sure is, using *libyang*. It is simpler if you are using *sysrepo* `tree` API but is possible even with `sr_val_t` API, which one are you using?

Regards,
Michal

**Comment by iGovindY** [comment]
I am using cpp `class Val` which actually stores type `sr_val_t`

**Comment by michalvasko** [comment]
Hi,
okay, these are the steps
```C++
libyang::Val val;

/* get xpath */
char *xpath = val->xpath();

/* get context */
libyang::S_Context ctx = session->get_context();

/* get schema node */
libyang::S_Schema_Node snode = ctx->get_node(nullptr, xpath);

/* you know it is leaf, cast it */
libyang::Schema_Node_Leaf sleaf(snode);

/* get enum vector */
std::vector<S_Type_Enum> enm_vec = sleaf.type()->info()->enums()->enm();

/* now you need to find the item with matching name() and then you can get its value() */
```
I have not tried it so there may be some typos and memory leaks but you should get the idea. Note that if you used `tree` API, it would be on 2 lines with one cast and no loops.

Regards,
Michal

**Comment by iGovindY** [comment]
tried using above suggestion:
`enm_vec` **size** is coming **0**.

added below code in print_change() in file cpp_application_changes_example.cpp
```
if (nullptr != change->new_val()) {
           if(change->new_val()->type() == SR_ENUM_T)
           {
                   cout <<"ENUM: ";
                   cout << change->new_val()->to_string();
                   libyang::S_Context ctx = sess->get_context();
                   libyang::S_Schema_Node snode = ctx->get_node(nullptr, change->new_val()->xpath());

                   /* you know it is leaf, cast it */
                   libyang::Schema_Node_Leaf sleaf(snode);

                   /* get enum vector */
                   std::vector<std::shared_ptr<libyang::Type_Enum> > enm_vec = sleaf.type()->info()->enums()->enm();
                   cout<< "vectorSize: "<<enm_vec.size() <<endl;
                   for(auto a = enm_vec.begin(); a != enm_vec.end(); a++)
                  {
                   printf("\nEnum Name :: Value \n");

                        cout<< (*a)->name() <<" :: "<<(*a)->value() <<endl;
                }
           }
        }
```

Also, do you think `value` should be added directly in the `sr_val_t` if the type is ENUM
reason being mostly backend app will be interested in the value rather than name?

**Comment by michalvasko** [comment]
Hi,
right, in the example you provided the type is derived, so you will probably have to find the original type first using `type()->der()`.

As for your request to change `sr_val_t` to include `value` instead of the `name`, that would be a NBC change and one also breaking the compatibility with the legacy version `sr_val_t`, so it will not be implemented. You are supposed to use the `tree` API if you require more information than what is provided in that structure.

Regards,
Michal

**Comment by iGovindY** [comment]
I will try the suggested change.

Also, can you tell specifically which `tree` API are you talking about?

Thanks
Govind.

**Comment by michalvasko** [comment]
Hi,
I mean using `get_change_tree_next()` instead of `get_change_next()`.

Regards,
Michal

**Comment by iGovindY** [comment]
Hi Michal,

as suggested it works for typedef enum
**changed** code to 
std::vector<S_Type_Enum> enm_vec = sleaf.type()**->der()->type()**->info()->enums()->enm();

---
what should be the code for enum leaf as below? which is not derived I guess.
```
leaf EnumLeafNotTypeDef{
	type enumeration {
		enum Val10{
				value 10;
		}
		enum Val12{
				value 12;
		}
	}
}
```

I tried below change, but for above leaf also, `sleaf.type()->der()` is not NULL
```
if (sleaf.type()->der() == nullptr)
{
 // Not derived, so use  sleaf.type()->info()
}
else
{
// Derived, so use  sleaf.type()->der()->type()->info()
}
```
Also, other than above two what variations can exist while handling enums,
Sorry for troubling you, I am not well versed with internal schema structures

Thanks
Govind.

**Comment by michalvasko** [comment]
Hi,
you should be able to check `type()->der()->module()`. If it is `NULL`, it is not derived. Or use the `tree` API to save yourself all these troubles.

Regards,
Michal

**Comment by iGovindY** [comment]
okay, I will try this.

also If I use `tree API, get_change_tree_next()`
I understand that, this is a new API, and their are not much example for utilizing this API in callback even in test/

So how do I get the required information?

**Comment by michalvasko** [comment]
Hi,
if you know *libyang* API (which you had a chance to try just now) you should have no problems with it. Also, just look at the provided methods, there are not that many in *sysrepo*. As for *libyang*, that is quite extensive, but you may simply look at [an example](https://github.com/sysrepo/sysrepo/blob/master/bindings/cpp/examples/cpp_get_data_example.cpp) that shows how to get the most important information from a data node.

Regards,
Michal

**Comment by iGovindY** [comment]
okay understood.
actually I am on libsysrepo v1.4.38, which doesn't have this example.
Thanks for pointing to this example.

As you said before. 
>It is simpler if you are using sysrepo tree API 

how to get integer value for enum using tree API?

**Comment by michalvasko** [comment]
Hi,
something like this
```C++
sysrepo::S_Tree_Change change;
libyang::S_Data_Node node = change->node();
if (node->schema()->nodetype() == LYS_LEAF) {
  libyang::Data_Node_Leaf_List leaf(node);
  if (leaf.value_type() == LY_TYPE_ENUM) {
    int32_t enum_value = leaf.value()->enm()->value();
  }
}
```
Again, I have not actually tried it so it may not compile but the idea should be obvious. Also, for the last time, please look at the *libyang* API yourself, it should not be that hard to figure out what methods to use to get some information. I will not provide you with examples for everything, I do not have the time for that. All I do is open the class headers and look for the methods, I am not very familiar with the C++ API.

Regards,
Michal
