### ISSUE TITLE
CallBack is not working registered using sr_module_change_subscribe

### ISSUE THREAD

**Issue by Vdm1994** [sysrepo/sysrepo#2009]
Hi I am using following version:
libyang: v1.0.130
sysrepo: v1.4.2
libnetconf2: v1.1.7
netopeer2: v1.1.7

Issue: CB function not getting hit
Code Snippet:
        rc := C.sr_module_change_subscribe(n.session, module, nil,  C.sr_module_change_cb(C.module_change_cb), nil, 0, 0, &n.subscription)

If any pointers how to debug this, it will help

module is perfect as per yang module defined. also rc is not failing while registering CB

I am not getting how this issue can be debuged

**Comment by michalvasko** [comment]
Hi,
not sure but you should use at least the latest release, the version you are using is fairly old. I seem to remember there were even some minor Python fixes that may be relevant here.

Regards,
Michal

**Comment by Vdm1994** [comment]
Hi I compiled with the latest releases now, not able to send edit-config, which was earlier working,

<?xml version='1.0' encoding='UTF-8'?>
<nc:rpc-error xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <nc:error-type>protocol</nc:error-type>
  <nc:error-tag>access-denied</nc:error-tag>
  <nc:error-severity>error</nc:error-severity>
  <nc:error-path>/ietf-netconf:config</nc:error-path>
  <nc:error-message xml:lang="en">**Access to the data model "ietf-netconf" is denied because "netconf" NACM authorization failed.**</nc:error-message>

I am new to sysrepo, so please pardon silly mistakes, need your help on this.

**Comment by michalvasko** [comment]
Hi,
please refer to *netopeer2* [README](https://github.com/CESNET/netopeer2/blob/master/README.md#nacm) for more information.

Regards,
Michal
