### ISSUE TITLE
Question about concurrent edit-config on the same data model

### ISSUE THREAD

**Issue by gabilm** [sysrepo/sysrepo#2011]
Hi, 

Let’s suppose the netopeer-server node has a model m, and from the netopeer-cli the client send a huge number of sequential edit-configs, over m, in order to modify the running datastore (over the same NETCONF/SSH session).

From our local tests we have noticed that these edit-config are processed in sequential order, so the second edit-config is not processed until the first one is completed.
It is an implementation-dependent feature? or could the node be configure to threat these edit-config in parallel?

Thanks in advance and best regards, Gabi.

**Comment by michalvasko** [comment]
Hi,
it is [explicitly specified](https://tools.ietf.org/html/rfc6241#section-4.5). However, this is a NETCONF requirement (so *netopeer2* must conform to it) so *sysrepo* is not strictly bound by that. And it does allow concurrent edit on 2 different modules as long as they do not depend on each other.

But you are asking about parallel processing of edits on one module. I am not sure what exactly your use-case is but it is not even theoretically possible. If 2 changes of one node arrive, one of them will leave the datastore in its final state, there is no concurrency possible. If you are talking only about changes in different data nodes of one module, then that may be possible. However, tracking all the inter-module dependencies is an extremely complex task and that is why we have limited the granularity to modules (which was complicated enough).

Having said all that, I believe the implementation is good as it is, allowing more than enough concurrency. But you may be using NETCONF incorrectly as there are quite a lot of options so a better one may be possible. Sending many small `<edit-config>` RPCs on `running` is definitely not a good idea and should be avoided.

Regards,
Michal

**Comment by gabilm** [comment]
Hi Michal.
Thank you for you quick response.

Ok, I didn't notice the note in RFC6241. The response is clear, we have avoid sending many small edit-config.
