### ISSUE TITLE
request for further info - change in xpath used in callbacks (vs 0.7.7)

### ISSUE THREAD

**Issue by johnbeckettn2e** [sysrepo/sysrepo#2017]
Hi,

I've noticed that when handling callbacks such as module_change the format of the xpath used has changed from `xpath = '/' + module + ':*' to 'xpath = '/' + module + ':*//.'

From the libyang documentation this appears to be 
get all top-level nodes of the module-name
/module-name:*

get all the descendants of container (excluding container)
/module-name:container//*

From the description I would expect the matching xpath lists to be identical except the top level container to be missing in the newer form.

However when I try the older form with sysrepo 1.4.66 I do not get the list of changes.

What am I missing?

Regards,
    John

**Comment by michalvasko** [comment]
Hi John,
you are missing the information from the [CHANGES](https://github.com/sysrepo/sysrepo/blob/master/CHANGES#L2), not sure what else to add.

Regards,
Michal

**Comment by johnbeckettn2e** [comment]
@michalvasko - thankyou
