### ISSUE TITLE
sysrepocfg shell should support subscriptions 

### ISSUE THREAD

**Issue by goldenspider** [sysrepo/sysrepo#202]
sudo sysrepocfg  --import=./test.xml --format=xml --datastore=running test 
Cannot operate on the running datastore as there are no active subscriptions.
Cancelling the operation.

--sub Like this srcfg_test_subscribe("test").  
sudo sysrepocfg **--sub** --import=./test.xml --format=xml --datastore=running test
The new configuration was successfully applied.

sudo sysrepocfg **--sub** --import=./test.xml --format=xml --datastore=running -p test
The new configuration was successfully applied.

**Comment by lukasmacko** [comment]
Hi,

The function `srcfg_test_subscribe` you pointed at is a part of a unit test. It simulates the application and actually does nothing with the confiugration changes it is listening to. This is valid behavior only for tesing purposes.

In a real use case a subscription is crated by a running application which is configured. The application is notified about the changes made in its configuration and is supposed to apply them. If the application is not running or it is not subscribed, it means that it can not reflect the changes made in its running configurations. Thus, you can edit only it's startup configuration.

Regards,
Lukas

_More about running datastore and creating subscriptions for testing purposes can be found [here](http://www.sysrepo.org/static/doc/html/ds_page.html) and [here](https://github.com/sysrepo/sysrepo/blob/master/INSTALL.md#subscribing-to-running-datastore)_

**Comment by goldenspider** [comment]
Well, agree with you.

**Comment by rastislavszabo** [comment]
Hi,
you can subscribe to our devel mailing list which is a better place for general discussions/proposals like this (not all sysrepo project members check the issues on GitHub): http://lists.sysrepo.org/listinfo
