### ISSUE TITLE
./netopeer2-server -d ? Module "ietf-netconf" feature "writable-running" not enabled in sysrepo.

### ISSUE THREAD

**Issue by kuailedeluojie-sudo** [sysrepo/sysrepo#2022]
![image](https://user-images.githubusercontent.com/60098441/84648608-d764f000-af37-11ea-9d9e-54f7fb426361.png)
[ERR]: NP: Module "ietf-netconf" feature "writable-running" not enabled in sysrepo.
[ERR]: NP: Server init failed.

**Comment by michalvasko** [comment]
Duplicate of cesnet/netopeer2#652
