### ISSUE TITLE
sr_oper_get_items_subscribe for leaf

### ISSUE THREAD

**Issue by iGovindY** [sysrepo/sysrepo#2023]
Hi,

query is regarding sr_oper_get_items_subscribe( )
we want to subscribe for a read-only leaf x under List L.
`/my_module:L[key]/x`

We are not aware of all the instances of List L in the callback, 
how do we subscribe for leaf x without keys? and form get-reply for every List instance?

Will the callback be called with `**parent` as per with all key instances?

**Comment by michalvasko** [comment]
Hi,
simply put, whatever XPath you use when subscribing, its last node is trimmed and the result is used in `lyd_find_path()` (standard XPath selection). The callback is then called for all the selected nodes.

So, if you subscribe with `/my_module:L/x`, `/my_module:L` will select all the list instances and call your callback for each. If you use `/my_module:L[key='1']/x` it will be called only once and only if a list with `key` value `1` exists. You may even use `/my_module:L[key<'20']/x` and then this callback will be called for every instance up to key value '19`. You should get the idea now.

Regards,
Michal

**Comment by iGovindY** [comment]
Hi Michal,

`/my_module:L/x` works as you said, 
I was subscribing with `/my_module:L[key]/x`, this doesn't work.

Thanks
Govind.

**Comment by iGovindY** [comment]
Wanted to know why 
` /my_module:L[key]/x `
doesn't work?

**Comment by michalvasko** [comment]
Hi,
actually, I do not know. It should work the same way and I have just tried it. Whether I subscribed to `/ietf-interfaces:interfaces/interface/enabled` or `/ietf-interfaces:interfaces/interface[name]/enabled`, the behavior was exactly the same (tested with `oper_data_example`).

Regards,
Michal

**Comment by iGovindY** [comment]
Thanks, somehow it is working now for me also.

Not sure what was the issue before.
