### ISSUE TITLE
feature dependencies across modules cause sr_connect() to fail

### ISSUE THREAD

**Issue by pfeige** [sysrepo/sysrepo#2029]
Hi,

suppose we have a module MA wich defines a feature FA depending on a feature FB defined in an imported module MB and the features are enabled the following way (like when using sysrepoctl)

```
connect; enable feature MB:FB; /*MB:FB scheduled*/ disconnect;
connect; /*MB:FB applied*/ enable feature MA:FA; /*MA:FA scheduled*/ disconnect;
connect; /*MA:FA applied*/ disconnect;
connect; /*failed*/
```
                                                                                                                                          
From now on all calls of sr_connect() will fail due to the following. When the modules are loaded into the context and MA is processed first, the enabling of FA fails because module MB with its feature FB has not been processed yet. The test https://github.com/ADTRAN/sysrepo/commit/a45381f7f7f28c5732d530297abc66d5526124b6 shows this situation. I put it into a separate file and placed it behind all other tests because after running it all other tests would fail too.

My proposed solution is to omit the checks for feature dependencies when modules are just loaded again. I think, in these cases the dependency checks have already been done and it is not really necessary to repeat them. The proposed changes were done in sysrepo https://github.com/ADTRAN/sysrepo/commit/60af0442f0c98b1030dcf09d586e1a60846326c1 and in libyang https://github.com/ADTRAN/libyang/commit/5c743d299944278cd813c5c911e0d122624c9f26.

Best Regards,
Peter

**Comment by michalvasko** [comment]
Hi Peter,
thanks for the nice test and a solution. I have decided to solve it in a similar but a bit more tidy way. However, feel free to provide the test as a pull request and a part of `test_modules` since you already made the effort of writing it.

Regards,
Michal

**Comment by pfeige** [comment]
Hi Michal,

here is the PR https://github.com/sysrepo/sysrepo/pull/2040 .

Regards,
Peter

**Comment by michalvasko** [comment]
Okay, thanks, merged.

Regards,
Michal
