### ISSUE TITLE
Sysrepo replace config does not work with leafrefs

### ISSUE THREAD

**Issue by IvanAguiar** [sysrepo/sysrepo#2031]
Hello,

I'd like to validate the following behavior:

1- Datastore correctly populated with leafrefs to other modules;
2- Mount a data node to the module (sr.Data_Node by the python binding);
3- Do a sr_replace_config to the module with the entire data;

I get a libyang error informing that I'm pointing to a non-existing leafref, and cannot replace the entire module and an assertion error;
>python: /libyang/src/tree_data.c:6189: _lyd_free_node: Assertion `0' failed.

I'm using the release:
> Netopeer2 - v1.1.27 
> Sysrepo - v1.4.58

Do you know why this error is occurring, and how can I fix it?
Additionally, how the replace_config must work?

BR,

**Comment by michalvasko** [comment]
Hi,
I would need to reproduce this but you using Python bindings complicates things. You can also try running this with `valgrind` and it may provide enough information.

Regards,
Michal
