### ISSUE TITLE
is there any API for application to know what all notifications that are subscribed by netconf client.

### ISSUE THREAD

**Issue by iGovindY** [sysrepo/sysrepo#2032]
Hi,

as per my understanding, 
currently, there are two types of notification API

1. **sr_event_notif_subscribe***:  for subscribing a notification like subscribe command on netopeer2-cli

2. **sr_event_notif_send*** to trigger a notification which will go to Netconf client or an application which subscribed using sr_event_notif_subscribe*

What I am looking for is:
Is there any API for the application to know what all notifications that are subscribed by Netconf client? or some way we could achieve this?

Thanks
Govind.

**Comment by michalvasko** [comment]
Hi Govind,
try retrieving `operational` data from the `sysrepo-monitoring` internal module, with some processing you should get the information you need.

Regards,
Michal

**Comment by iGovindY** [comment]
couldn't find `sysrepo-monitoring` module in sysrepo code

```
sysrepoctl -V
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.38 (SO v5.3.5)
```

is this newly added ?

**Comment by michalvasko** [comment]
Hi,
yes, it is fairly new but if you are using `devel`, you should update it regularly or use `master`. If you do, you should have the module available.

Regards,
Michal
