### ISSUE TITLE
Shared mutex dead lock

### ISSUE THREAD

**Issue by rjarry** [sysrepo/sysrepo#2033]
Hi Michal,

We frequently encounter a dead lock with the main mutex. It seems there are cases where it is not properly released by the application that acquired it. Causing all further attempts to acquire it to fail since the application has exited and will never be able to release it. Since it is a shared pthread mutex, the OS (in our case, Linux) has no chance to cleanup and release it. Basically, all sysrepo applications are "frozen" and cannot perform anything. The only way to recover is to `SIGKILL` all these applications and purge all the shared memory files (not far from rebooting the system).

I have spent a lot of time trying to debug the issue but to no avail. Somehow, I managed to reproduce the bug (almost every time) without all our environment which allows me to submit this issue :)

Here are the versions I am using:

Libyang: 1.0.180
Sysrepo: 1.4.67

Build both projects with default options and apply the following patch to sysrepo to add code to reproduce the issue:

```bash
cd $path_to_sysrepo
curl https://gist.githubusercontent.com/rjarry/a19629ae41668a46d44566b4ea16e0d4/raw/47fc7e4e3b7e553f5d6ea223048a1b08ac47d4c7/mutex-bug.patch | git am
cd mutex-bug
make   # takes quite some time as there are a lot of YANG modules to install
bash -x test.sh
```

Wait a few seconds and then hit `ctrl-c`. You should get:

```
...
++ sysrepoctl -C
0
++ sysrepoctl -l
[ERR]: Locking a mutex failed (sr_connect: Connection timed out).
sysrepoctl error: Failed to connect (Timeout expired)
```

As you can see, no sysrepo applications are running but the mutex cannot be acquired anymore.

The problem does not appear every time. It seems to depend when `ctrl-c` is hit. Also, it is very hard to reproduce with only a few 
YANG modules installed. This is why we install 300 dummy modules in the `Makefile`. Only the first two are actually used by the applications.

Thanks a lot in advance for your help!

**Comment by rjarry** [comment]
In my opinion, this is a critical issue.

Ideally, if one shared mutex has been acquired by an application which died without releasing it (it can happen for many reasons, segmentation fault, bug in sysrepo, `SIGKILL` while in sysrepo code, etc.), there should be an automatic way of recovering from this.

This could be an interesting lead: https://stackoverflow.com/questions/30770236/pthread-process-shared-mutex-deadlock However I'm not sure this is POSIX compliant.

**Comment by rjarry** [comment]
If I understood properly, we would need a pthread rwlock with the same "robust" feature. But that does not exist (yet?).

https://stackoverflow.com/questions/51956715/robust-rwlock-in-posix

Maybe this can be implemented "manually" by storing the PIDs of readers in the shared memory and cleaning up when readers die without releasing the lock.

**Comment by michalvasko** [comment]
Hi Robin,
firstly, am I correct to say that the test may be interrupted at any point so even during `sysrepocfg` execution? Please answer that and then we can discuss it further but you could have saved yourself the trouble because I have read all about robust mutexes and have actually implemented robust rwlocks and used them in *sysrepo*.

Regards,
Michal

**Comment by rjarry** [comment]
Hi Michal,

> firstly, am I correct to say that the test may be interrupted at any point so even during sysrepocfg execution? Please answer that and then we can discuss it further

Yes, it can happen when any application (including `sysrepocfg`) executing any sysrepo function is terminated without the chance to release any locks it may have acquired (read or write locks).

It seems like when there are a lot of YANG modules installed, `sr_connect` takes a while to parse them all and build the libyang context for the connection. And this is done while the main write lock is acquired. If the application is interrupted during that, all the sysrepo applications are toasted. In any case, it can also happen (although less likely) when there are only a few YANG modules installed. I my opinion, the library should be resilient to such issues.

> you could have saved yourself the trouble because I have read all about robust mutexes and have actually implemented robust rwlocks and used them in sysrepo.

I did not see any reference to robust pthread mutexes in the source code (current devel version 1.4.68). I may have missed something. I tried to implement a draft solution but it is rather complex. I'm sure you'll make something better that I can.

**Comment by michalvasko** [comment]
Hi Robin,
you see, I did not really consider the situation when an app is suddenly terminated as valid so the whole [recovery](https://netopeer.liberouter.org/doc/sysrepo/master/index.html#recovery) mechanism is used only for module locks. The goal is described in the docs and it was meant to recover only when an app terminates (crashes) in its own code, not in *sysrepo* code, which should work correctly.

But I suppose sending `SIGKILL` to an application cannot be forbidden or even power outages so I should extend this mechanism to cover all the cases. Like I said, the locks and all the required information is already stored but this requires to make it completely independent of all the other shared memory so it will not be simple. Once I have some time I will take a look.

Regards,
Michal

**Comment by rjarry** [comment]
Hi Michal,

did you have some time to think about this issue? Is there anything I can do to help?

I wonder if the SHMs could be redesigned to be crash resilient while ensuring data integrity and consistency:

- Duplicate all SHMs to use two segments: "active" and "staging". The current active segment would be indicated via an index.
- Use robust pthread mutexes to ensure recovery is possible.
- When a process acquires a write lock, it only writes in the "staging" segment. First by copying the current "active" segment into it.
- Just before releasing the lock, it switches the index to change "staging" and "active" segments. Even if the process crashes after switching the index but before unlocking, the SHM is not corrupted.
- If another process acquires the lock with `EOWNERDEAD`, it can display a warning and move on with its life.

These are only high level ideas and my knowledge of sysrepo code base is very limited. It may not be applicable due to constraints that I am not aware of. However, if possible, it would make the whole system resilient to any crash.

Thoughts?

**Comment by michalvasko** [comment]
Hi Robin,
robust mutexes will most likely be used at least in one instance and using backup SHM segments is one of the possible solutions. The plan is to have this implemented by the end of this year and I may even start working on it quite soon, in a matter of days. There were other tasks I was busy with.

**Comment by rjarry** [comment]
Ok thanks for the update. I can help testing in our environment if you want.

**Comment by rjarry** [comment]
I have tested version 1.4.104 and it fixes this bug.

More specifically in commits https://github.com/sysrepo/sysrepo/commit/bd05ce31841ab80dd4b194110fb5f8cfeab4f096, https://github.com/sysrepo/sysrepo/commit/406ad49edd6c08b0c417c2d4b50d296044254b68 and https://github.com/sysrepo/sysrepo/commit/032c07b58c567b4772ceba752907337dd1e75d48.

Thanks Michal :+1:
