### ISSUE TITLE
libyang dictionary leak on operational callback

### ISSUE THREAD

**Issue by dumitrupaul** [sysrepo/sysrepo#2036]
Hello,

I am trying to use the CPP-wrapped operational data callback and in doing so I am getting libyang dictionary leaks when the program ends:

    libyang[1]: String "123" not freed from the dictionary, refcount 1
    libyang[1]: String "1" not freed from the dictionary, refcount 2
    libyang[1]: String "1234" not freed from the dictionary, refcount 1
```
struct OperationalCallback : public sysrepo::Callback {
    int oper_get_items(sysrepo::S_Session session,
                          const char* module_name,
                          const char* path,
                          const char* request_xpath,
                          uint32_t /* request_id */,
                          libyang::S_Data_Node& parent,
                          void* /* private_data */) override {

        string const tested_path("/ietf-dhcpv6-server:dhcpv6-server/network-ranges/network-range"
                "[network-range-id='1']/address-pools/address-pool[pool-id='1']");

        if (request_xpath == tested_path) {
            string const total_count_path(tested_path + "/active-leases/total-count");
            string const alloc_count_path(tested_path + "/active-leases/allocated-count");

            parent = parent->new_path(session->get_context(), total_count_path.c_str(), "123",
                              LYD_ANYDATA_CONSTSTRING, 0);
            parent->new_path(session->get_context(), alloc_count_path.c_str(),
                              "1234", LYD_ANYDATA_CONSTSTRING, 0);

            parent = parent->find_path(path)->data().front();
        }

        return SR_ERR_OK;
    }
};
```
The above code is a snippet which provides the data successfully, but manages to leak data in the dictionary. My first guess is that I may not be using the new_path function for setting the parent correctly, please tell me if this is not the right way of doing it.
Also I'm subscribing to the root node of the module which is `dhcpv6-server`.

Thanks in advance,
Paul.

**Comment by michalvasko** [comment]
Hi Paul,
I have not tested it but I think if you look at the [example](https://github.com/sysrepo/sysrepo/blob/master/bindings/cpp/examples/cpp_oper_data_example.cpp#L46), you should be able to fix this.

Regards,
Michal

**Comment by dumitrupaul** [comment]
Hello Michal,

Following the example indeed creating every child starting from the root node works without any dictionary leaks, but I wanted to steer away from that way of setting the data because of the number of allocations done and also the lines of code necessary for a deep data-tree.
For this reason I am trying to use the libyang's default mechanism of `lyd_new_path` which is `the whole path to the target node is created (with any missing parents) if necessary.` and setting the data by having the complete xpaths.
I hope you understand my reasoning of using `new_path()`'s xpath variant.

Regards,
Paul.

**Comment by michalvasko** [comment]
Hi Paul,
that is not a problem. To be specific, you should be fine with using `reset()` for the first node returned by `new_path()` and then simply connect other nodes. Not resetting the pointer should cause the memory leaks, not you using a different API.

Regards,
Michal

**Comment by dumitrupaul** [comment]
Hello Michal,

You are right, the leak was happening because I was using `operator=` and sharing the ownership.

Thank you for the help,
Paul.
