### ISSUE TITLE
can not find sysrepod?

### ISSUE THREAD

**Issue by OlympusHo** [sysrepo/sysrepo#2038]
Hi,
I have build the newest sysrepo:I found sysrepocfg,sysrepoctl,libsysrepo.so,but i can not found sysrepod?
and i know sysrepod was removed:"major design changes (most importantly, no sysrepod)."
how can i start sysrepod?

log:
sysrepoctl -V:
libsysrepo v1.4.66

**Comment by fredgan** [comment]
Hi,

No sysrepod, so you needn't start sysrepod.

It is complemented by using shared memory in new sysrepo.  There is no daemon process.

**Comment by OlympusHo** [comment]
Hi fredgan :
thanks for your reply!
but i run netopeer2-server -d -v 3,it said Connecting to sysrepo failed (Internal error):

[WRN]: LY: Failed to open libyang extensions plugins directory "/home/ubuntu/heaolin/install/lib/libyang1/extensions" (No such file or directory).
[WRN]: LY: Failed to open libyang user types plugins directory "/home/ubuntu/heaolin/install/lib/libyang1/user_types" (No such file or directory).
[INF]: LY: Reading module "ietf-yang-metadata".
[INF]: LY: Module "ietf-yang-metadata@2016-08-05" successfully parsed as implemented.
[INF]: LY: Reading module "yang".
[ERR]: LY: Invalid keyword "type" as a child to "annotation". (/)
[ERR]: LY: Module "yang" parsing failed.
[ERR]: SR: Failed to create a new libyang context.
[ERR]: NP: Connecting to sysrepo failed (Internal error).
[ERR]: NP: Server init failed.
[INF]: NP: Server terminated.

**Comment by fredgan** [comment]
Maybe you need to install libyang first, then sysrepo、libnetconf2、Netopeer2

**Comment by OlympusHo** [comment]
> 
> 
> Maybe you need to install libyang first, then sysrepo、libnetconf2、Netopeer2

i had installed libyang sysrepo libnetconf2 Netopeer2-server, i created the dir /home/ubuntu/heaolin/install/lib/libyang1/extensions & /home/ubuntu/heaolin/install/lib/libyang1/user_types,and move .so to the two dir.then run netopeer2-server -d -v 3,the log :
/home/ubuntu/heaolin/install/lib/libyang1/extensions# netopeer2-server  
[INF]: LY: Plugin "/home/ubuntu/heaolin/install/lib/libyang1/extensions/metadata.so" successfully loaded.
[INF]: LY: Plugin "/home/ubuntu/heaolin/install/lib/libyang1/extensions/nacm.so" successfully loaded.
[INF]: LY: Plugin "/home/ubuntu/heaolin/install/lib/libyang1/extensions/yangdata.so" successfully loaded.
[INF]: LY: Plugin "/home/ubuntu/heaolin/install/lib/libyang1/user_types/user_inet_types.so" successfully loaded.
[INF]: LY: Plugin "/home/ubuntu/heaolin/install/lib/libyang1/user_types/user_yang_types.so" successfully loaded.
[INF]: LY: Reading module "ietf-yang-metadata".
[INF]: LY: Module "ietf-yang-metadata@2016-08-05" successfully parsed as implemented.
[INF]: LY: Reading module "yang".
[INF]: LY: Resolving "yang" unresolved schema nodes and their constraints...
[INF]: LY: All "yang" schema nodes and constraints resolved.
[INF]: LY: Module "yang@2017-02-20" successfully parsed as implemented.
[INF]: LY: Reading module "ietf-inet-types".
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-inet-types" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-inet-types@2013-07-15" successfully parsed as implemented.
[INF]: LY: Reading module "ietf-yang-types".
[INF]: LY: Module "ietf-yang-types@2013-07-15" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-yang-types" in /opt/sysrepo/my_sysrepo/yang.
[INF]: LY: Resolving "sysrepo" unresolved schema nodes and their constraints...
[INF]: LY: All "sysrepo" schema nodes and constraints resolved.
[INF]: LY: Module "sysrepo@2020-01-15" successfully parsed as implemented.
[INF]: SR: Libyang internal module "yang" was installed.
[INF]: LY: Module "ietf-datastores@2018-02-14" successfully parsed as implemented.
[INF]: SR: File "ietf-datastores@2018-02-14.yang" was installed.
[INF]: SR: Sysrepo internal dependency module "ietf-datastores" was installed.
[INF]: LY: Searching for "ietf-inet-types" in /opt/sysrepo/my_sysrepo/yang.
[INF]: LY: Searching for "ietf-datastores" in /opt/sysrepo/my_sysrepo/yang.
[INF]: LY: Loading schema from "/opt/sysrepo/my_sysrepo/yang/ietf-datastores@2018-02-14.yang" file.
[INF]: LY: Module "ietf-datastores@2018-02-14" already in context.
[INF]: LY: Module "ietf-datastores@2018-02-14" successfully parsed as implemented.
[WRN]: LY: Missing status in deprecated subtree (/ietf-yang-library:{grouping}[module-list]/{grouping}[schema-leaf]/schema), inheriting.
[INF]: LY: Module "ietf-yang-library@2019-01-04" successfully parsed as implemented.
[INF]: SR: File "ietf-yang-library@2019-01-04.yang" was installed.
[INF]: SR: Sysrepo internal module "ietf-yang-library" was installed.
[INF]: LY: Resolving "sysrepo-monitoring" unresolved schema nodes and their constraints...
[INF]: LY: All "sysrepo-monitoring" schema nodes and constraints resolved.
[INF]: LY: Module "sysrepo-monitoring@2020-04-17" successfully parsed as implemented.
[INF]: SR: File "sysrepo-monitoring@2020-04-17.yang" was installed.
[INF]: SR: Sysrepo internal module "sysrepo-monitoring" was installed.
[INF]: LY: Module "ietf-netconf@2011-06-01" successfully parsed as implemented.
[INF]: SR: File "ietf-netconf@2011-06-01.yang" was installed.
[INF]: SR: Sysrepo internal dependency module "ietf-netconf" was installed.
[INF]: LY: Searching for "ietf-netconf" in /opt/sysrepo/my_sysrepo/yang.
[INF]: LY: Loading schema from "/opt/sysrepo/my_sysrepo/yang/ietf-netconf@2011-06-01.yang" file.
[INF]: LY: Module "ietf-netconf@2011-06-01" already in context.
[INF]: LY: Module "ietf-netconf@2011-06-01" successfully parsed as implemented.
[INF]: LY: Module "ietf-netconf-with-defaults@2011-06-01" successfully parsed as implemented.
[INF]: SR: File "ietf-netconf-with-defaults@2011-06-01.yang" was installed.
[INF]: SR: Sysrepo internal module "ietf-netconf-with-defaults" was installed.
[INF]: LY: Resolving "ietf-netconf-notifications" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-netconf-notifications" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-netconf-notifications@2012-02-06" successfully parsed as implemented.
[INF]: SR: File "ietf-netconf-notifications@2012-02-06.yang" was installed.
[INF]: SR: Sysrepo internal module "ietf-netconf-notifications" was installed.
[INF]: LY: Searching for "ietf-yang-metadata" in /opt/sysrepo/my_sysrepo/yang.
[INF]: LY: Resolving "ietf-origin" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-origin" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-origin@2018-02-14" successfully parsed as implemented.
[INF]: SR: File "ietf-origin@2018-02-14.yang" was installed.
[INF]: SR: Sysrepo internal module "ietf-origin" was installed.
[INF]: SR: Datastore copied from <startup> to <running>.
[INF]: SR: Session 1 (user "root") created.
[ERR]: NP: Module "ietf-netconf" feature "writable-running" not enabled in sysrepo.
[ERR]: NP: Server init failed.
[INF]: NP: Server terminated.

**Comment by OlympusHo** [comment]
i run the setup.sh merge_hostkey.sh merge_config.sh ,  netopeer2-server works !
thanks for your help!

**Comment by michalvasko** [comment]
Like it was said, `make install` of *netopeer2* executes these scripts, so that is all that you should have done.

Regards,
Michal
