### ISSUE TITLE
something error with using api sr_module_change_subscribe and sr_get_change_next

### ISSUE THREAD

**Issue by nic1225** [sysrepo/sysrepo#2043]
hi,

I used sysrepo version 1.4.66, I can't get all the changes in subtree.I don't know what the problem is.
 ietf-interfaces startup database like this:

    <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
    
      <interface>
        <name>loop0</name>
        <description>loop0</description>
        <type xmlns:v3po="urn:opendaylight:params:xml:ns:yang:v3po">v3po:loopback</type>
        <loopback xmlns="urn:opendaylight:params:xml:ns:yang:v3po">
          <mac>00:50:56:34:49:e1</mac>
          <instance>0</instance>
        </loopback>
      </interface>
    
    </interfaces>

My code is as follows:

    static int
    ietf_interface_loopback_change_cb(sr_session_ctx_t *session, const char *module_name, const char *xpath, sr_event_t event, u32 request_id, void *private_ctx)
    {
    	... ...
    	
        SRP_LOG_DBG("[ietf_Interfaces]:Into ietf_interface_loopback_change_cb for = %s", xpath);
    
        /* get changes iterator */
        rc = sr_get_changes_iter(session, xpath, &iter);
    
        
        SRP_LOG_DBG("00 op_rc = %d,  event = %d ", op_rc, event);
    
        /* iterate over all changes */
        while ((SR_ERR_OK == op_rc || event == SR_EV_ABORT) &&
               (SR_ERR_OK == (rc = sr_get_change_next(session, iter, &op, &old_val, &new_val)))) 
       {
            value = NULL == new_val ? old_val : new_val;
            SRP_LOG_DBG("A change detected in '%s', op=%d", value->xpath, op);
            SRP_LOG_DBG("interface name = %s, op = %d, val->type = %d", sc_vpp_if_name, op, value->type);

            ....
        }
        
        SRP_LOG_DBG("out loop: rc = %d, xpath=%s ", rc, new_val->xpath);
    
    	... ...
    }
	
	
    rc = sr_module_change_subscribe(session, "ietf-interfaces","/ietf-interfaces:interfaces/interface/v3po:loopback",
                    ietf_interface_loopback_change_cb, g_vapi_ctx_instance, 95, SR_SUBSCR_CTX_REUSE | SR_SUBSCR_ENABLED, subscription);

When "sysrepo-plugin-d-v4" is executed, the relevant debug information is displayed:
	
    [DBG]: plugin: [ietf_Interfaces]:Into ietf_interface_loopback_change_cb for = /ietf-interfaces:interfaces/interface/v3po:loopback
    [DBG]: plugin: 00 op_rc = 0,  event = 4 
    [DBG]: plugin: A change detected in '/ietf-interfaces:interfaces/interface[name='loop0']/v3po:loopback', op=0
    [DBG]: plugin: interface name = loop0, op = 0, val->type = 3
    [DBG]: plugin: out loop: rc = 5, xpath=/ietf-interfaces:interfaces/interface[name='loop0']/v3po:loopback 

But previously, sysrepo version 0.7.7 and with api sr_subtree_change_subscribe,  I can get the information I want, like:

    [DBG] (ietf_interface_loopback_change_cb:1761) A change detected in '/ietf-interfaces:interfaces/interface[name='loop0']/v3po:loopback', op=0
    [DBG] (ietf_interface_loopback_change_cb:1767) interface name = loop0, op = 0, val->type = 4
    [DBG] (ietf_interface_loopback_change_cb:1761) A change detected in '/ietf-interfaces:interfaces/interface[name='loop0']/v3po:loopback/mac', op=0
    [DBG] (ietf_interface_loopback_change_cb:1767) interface name = loop0, op = 0, val->type = 18
    [DBG] (ietf_interface_loopback_change_cb:1805) SR_OP_CREATED loopback mac = 0:50:56:34:49:e1
    [DBG] (ietf_interface_loopback_change_cb:1761) A change detected in '/ietf-interfaces:interfaces/interface[name='loop0']/v3po:loopback/instance', op=0
    [DBG] (ietf_interface_loopback_change_cb:1767) interface name = loop0, op = 0, val->type = 21

**Comment by michalvasko** [comment]
Hi,
please look at [CHANGES](https://github.com/sysrepo/sysrepo/blob/master/CHANGES).

Regards,
Michal

**Comment by nic1225** [comment]
Hi, Michal:

Thanks for your reply.
 I see "`- sr_get_changes_iter() xpath parameter changed - it now properly selects changes based on the XPath, not subtrees`" and I know why it is.   For the scenario I mentioned above, could you give me some advice or sample code that I can refer to.

Regards,
Nick.

**Comment by michalvasko** [comment]
Hi Nick,
well, just select all the changes. Specifically, do not call `sr_get_changes_iter()` directly with `xpath` but concatenate `//.` to it first.

Regards,
Michal

**Comment by nic1225** [comment]
Hi, Michal:
    It worked, Thanks again.

Regards,
Nick
