### ISSUE TITLE
Sysrepo configuration data does not take effect, how to make it effective

### ISSUE THREAD

**Issue by ellen0719** [sysrepo/sysrepo#2044]
hi,all.

 I used to upgrade to 1.4.58 with 0.7.7， now i use 1.4.58.
   After I modify the configuration data and import it with sysrecocfg, the data will not take effect. I need to restart the system to take effect. I want to know how the data storage mechanism in the new version of sysrepo can take effect in the configuration I modified. I modified SSH_ callhome.xml In the configuration. Other configuration data should be similar

    thanks!

**Comment by michalvasko** [comment]
Hi,
please paste the command you used for editing the data and why you think it did not take effect because in all likelihood it did but your expectations are incorrect in some way.

Regards,
Michal
