### ISSUE TITLE
sysrepoctl executed by 'root' failed 

### ISSUE THREAD

**Issue by ryanking8215** [sysrepo/sysrepo#2045]
sysrepo version: 1.4.66
system: ubuntu 20.04 LTS

I built and installed sysrepo by using a normal user, and used `-DREPO_PATH` to change the sysrepo path. Executing sysrepoctl by normal user  is ok, but using 'root' it got error.

```
sudo sysrepoctl -l 
```

go errors:
```
[ERR]: Failed to open ext shared memory (Permission denied).
sysrepoctl error: Failed to connect (System function call failed)
```

I have no idea why root user gets error.

**Comment by michalvasko** [comment]
Hi,
the problem is tracked in https://github.com/CESNET/netopeer2/issues/621. I have no idea why it does not work, either.

Regards,
Michal

**Comment by ryanking8215** [comment]
Hi, I have solved my problem. I put the libyang1 to the customized path, which causes the issue, even customized path is added to the LD_LIBRARY_PATH. 

After I moved the libyang1 to the /usr/local/lib, the problem disappeared.
