### ISSUE TITLE
Python Bindings : Xpath_Ctx - Not working

### ISSUE THREAD

**Issue by chaichairiko** [sysrepo/sysrepo#2048]
Hi,
I tried to use xpath according to the documenation: https://netopeer.liberouter.org/doc/sysrepo/master/group__utils__xpath.html#ga744f2deb49dfe26eeadbf95eb5fedfaa

```python
path = new_val.xpath()
>>> path
"/ietf-netconf-server:netconf-server/listen/endpoint[name='default-ssh']/ssh/tcp-server-parameters/local-address"

import sysrepo as sr
ctx = sr.Xpath_Ctx()
>>> ctx.next_node(xpath)
'netconf-server'
>>> ctx.next_node(xpath)
'netconf-server'
```

If I understand correctly, `ctx` should keep the current state and work through to the next node, otherwise I have no way to traverse the xpath. That is, on the second call I would expect `'listen'` and so on

**Comment by michalvasko** [comment]
Hi,
I think there may be a problem with how Python manages the context, I seem to remember some recent similar issue. But maybe @borna-blazevic can help you as he is the (sort-of) author of these bindings.

Regards,
Michal
