### ISSUE TITLE
sysrepo: version 0.7.4 cross compile failed

### ISSUE THREAD

**Issue by Arvliu** [sysrepo/sysrepo#2049]
hi,

I am using sysrepo: version 0.7.4, and need to cross compile it use aarch64-linux-gnu-gcc for ARM arch64.

Before this, i had successed corss compiled sysrepo-0.7.4 for ARM arch32. And, I use the same method for cross-compiling ARM arch64. But i met some issue as below:
1.gcc compiling (local compile) is ok;
2.cross compile is failed:
1)camke is ok using the command as below:
cmake -DCMAKE_INSTALL_PREFIX=/drgfly/netopeer2_server/sysrepo -DREPOSITORY_LOC=/etc/sysrepo -DCMAKE_BUILD_TYPE=Release .. -DCMAKE_C_COMPILER=/usr/gcc-arm-8.2-2019.01-x86_64-aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=/usr/gcc-arm-8.2-2019.01-x86_64-aarch64-linux-gnu/bin/aarch64-linux-gnu-g++ -DUSE_SR_MEM_MGMT=OFF -DCALL_SYSREPOCTL_BIN=/drgfly/SourceCode/sysrepo_local/build/src/sysrepoctl -DCALL_SYSREPOCFG_BIN=/drgfly/SourceCode/sysrepo_local/build/src/sysrepocfg -DYANG_INCLUDE_DIR=/drgfly/netopeer2_server/libyang/include -DYANG_LIBRARY="/drgfly/netopeer2_server/libyang/lib/libyang.so" -DREDBLACK_INCLUDE_DIR=/drgfly/lib/libredblack/include -DREDBLACK_LIBRARY="/drgfly/lib/libredblack/lib/libredblack.so" -DPROTOBUF-C_INCLUDE_DIR=/drgfly/lib/protobuf-c/include -DPROTOBUF-C_LIBRARY="/drgfly/lib/protobuf-c/lib/libprotobuf-c.so" -DEV_INCLUDE_DIR=/drgfly/lib/libev/include -DEV_LIBRARY="/drgfly/lib/libev/lib/libev.so" -DCMAKE_EXE_LINKER_FLAGS="/drgfly/lib/libpcre/lib/libpcre.so.1"

2)make is failed
[ 72%] Linking C executable common_test
/bin/sh: ../src/sysrepoctl: cannot execute binary file: Exec format error
tests/CMakeFiles/common_test.dir/build.make:108: recipe for target 'tests/common_test' failed
make[2]: *** [tests/common_test] Error 126
make[2]: *** Deleting file 'tests/common_test'
CMakeFiles/Makefile2:1608: recipe for target 'tests/CMakeFiles/common_test.dir/all' failed
make[1]: *** [tests/CMakeFiles/common_test.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

Can you help to solve this issue? Thanks.

**Comment by fei15115** [comment]
Hi,Arvliu:
I got same error as you.Could you tell me how can you sovle this issue?

**Comment by NTUGY** [comment]
Hi,Arvliu:
I also got the same error.I can not solve it.Could you help me?Thank you so much

**Comment by jktjkt** [comment]
Your build is trying to execute your target's `sysrepoctl` on your build host. You have to build sysrepo twice, the first time natively for the host, the second time via the cross-compiler for your target, and the second time you configure with a parameter asking the build to use the host's `sysrepocfg`, `sysrepoctl`, etc. Cross-compiling is complex, and I strongly suggest using a proper tool such as Buildroot which [has sysrepo already packaged for you](https://github.com/buildroot/buildroot/tree/master/package/sysrepo/).
