### ISSUE TITLE
Guidelines for validation flags in sr_oper_get_items_cb

### ISSUE THREAD

**Issue by rjarry** [sysrepo/sysrepo#2050]
Hi Michal,

I am having issues with calling `lyd_validate()` in operational data callbacks. I looked at examples from Netopeer2 and the examples folder but none of them call `lyd_validate()` is that on purpose? Is the returned data validated by sysrepo anyway?

For now, I use `LYD_OPT_DATA | LYD_OPT_DATA_NO_YANGLIB` in the new sysrepo python bindings:

https://github.com/sysrepo/sysrepo-python/blob/v0.1.2/sysrepo/subscription.py#L344-L346

But I get a lot of errors about missing required elements (the unit tests are working fine, but I get these errors in a real production environment with complex YANG modules):

```
validation failed: Missing required element "denied-operations" in "nacm".
```

Which seems related to the `ietf-netconf-acm` module which I am not subscribed for nor am returning any data related to.

I tried to use the `LYD_OPT_GET` flag instead, but it does not work properly. It seems like some data elements are stripped before returning to the client. What would you advise to do?

**Comment by rjarry** [comment]
Note that when I do not call `lyd_validate()`, it works properly.

**Comment by michalvasko** [comment]
Hi Robin,
yes, `operational` may be invalid as per the [NMDA RFC](https://tools.ietf.org/html/rfc8342#page-15). Also, without going into details, you should simply skip the validation while *sysrepo* is using *libyang* version 1. Once the migration is finished, some validation function may be used, we will see.

Regards,
Michal

**Comment by rjarry** [comment]
Ok thanks, I'll remove validation of operational data.

Would you also advise not validating RPC output?

**Comment by michalvasko** [comment]
Hi,
firstly, it is the same as RPC input. They both must be validated but with all the required data available (which can be up to the whole `operational` datastore). I do not think you have to do this in the bindings, just use the same options as the C code does for parsing any data.

Regards,
Michal

**Comment by rjarry** [comment]
Ok that will make things simpler for me  :)

Thanks Michal
