### ISSUE TITLE
【INSTALL YANG FILE ERR】(sysrepo1.4.0)  INF is :Scheduled changes not applied because of other existing connections.

### ISSUE THREAD

**Issue by CartYuyDgs** [sysrepo/sysrepo#2053]
install:
      root@gpn-000C29C37C06:/etc/sysrepo/yang# sysrepoctl -i yuyyang.yang -v3
      [INF]: Scheduled changes not applied because of other existing connections.
      [INF]: Module "yuyyang" scheduled for installation

result:
      root@gpn-000C29C37C06:/etc/sysrepo/yang# sysrepoctl -l -v3
[INF]: Scheduled changes not applied because of other existing connections.
Sysrepo repository: /etc/sysrepo

Module Name                | Revision   | Flags | Owner     | Permissions | Submodules | Features                                                               
----------------------------------------------------------------------------------------------------------------------------------------------------------------                                                                   
yuyyang                    |            |  N    |           |             |            | 

help!!!
thanks

**Comment by fredgan** [comment]
Hi,
I think the tips is obvious. Please close other existing connections to the sysrepo, then you can install the model.

**Comment by michalvasko** [comment]
Hi,
some more information is in the [docs](https://netopeer.liberouter.org/doc/sysrepo/master/conn_sess.html).

Regards,
Michal

**Comment by CartYuyDgs** [comment]
thanks you 

> Hi,
> some more information is in the [docs](https://netopeer.liberouter.org/doc/sysrepo/master/conn_sess.html).
> 
> Regards,
> Michal
