### ISSUE TITLE
multiple notification clubbing

### ISSUE THREAD

**Issue by iGovindY** [sysrepo/sysrepo#2054]
Hi,

Is below possible?
Collate multiple notifications and trigger once.

Like we do for set with `set_item*` and `apply_changes` API.

Thanks
Govind.

**Comment by michalvasko** [comment]
Hi,
no, there is no batch sending of notifications because there is no point in that, the callbacks must be triggered for each notification anyway.

Regards,
Michal

**Comment by iGovindY** [comment]
Okay, Thanks for the info.
One more query, 
`sr_event_notif_send_tree` or `event_notif_send` API exits successfully only after notification is delivered to client(s).
Or it just set the notification in sysrepo and exits, then in some other thread context notification will be delivered to client.

Basically query is, are these API synchronous or asynchronous?

Thanks
Govind.

**Comment by michalvasko** [comment]
Hi,
no, notifications were kept strictly asynchronous (unlike data changes). I have noticed this inconsistency but did not think it a problem then. Do you have a use-case when you really need to be certain that the sent notification was processed before continuing?

Regards,
Michal
