### ISSUE TITLE
[ERR]: stat() failed (No such file or directory).

### ISSUE THREAD

**Issue by kuailedeluojie-sudo** [sysrepo/sysrepo#2058]
This problem occurred when running sysrepo plugin on my embedded device: [err]: stat() failed (no such file or directory). How can I solve it?
![image](https://user-images.githubusercontent.com/60098441/87891482-a6af3380-ca6c-11ea-9d5a-f53309cc6698.png)

**Comment by michalvasko** [comment]
Hi,
this seems like some basic and unexpected problem, can you provide more errors? Should be printed if you run *sysrepo-plugind* with `-v2`.

Regards,
Michal

**Comment by kuailedeluojie-sudo** [comment]
HI,
Thank you for your reply. I'm working on embedded device development, which seems normal at present.

"[root@M28x opt]# wr sysrepo-plugind -d -v 4
[INF]: Applying scheduled changes.
[INF]: No scheduled changes.
[INF]: Session 1 (user "root") created."

**Comment by kuailedeluojie-sudo** [comment]
[root@M28x opt]# wr netopeer2-server -d -v 4
[ERR]: NP: Internal error (/home/mo/share/netconf2_new/netopeer2/src/main.c:635)
[INF]: LY: Plugin "/home/mo/share/netconf2_new/libyang/_install/lib/libyang1/extensions/metadata.so" successfully loaded.
[INF]: LY: Plugin "/home/mo/share/netconf2_new/libyang/_install/lib/libyang1/extensions/yangdata.so" successfully loaded.
[INF]: LY: Plugin "/home/mo/share/netconf2_new/libyang/_install/lib/libyang1/extensions/nacm.so" successfully loaded.
[INF]: LY: Plugin "/home/mo/share/netconf2_new/libyang/_install/lib/libyang1/user_types/user_yang_types.so" successfully loaded.
[INF]: LY: Plugin "/home/mo/share/netconf2_new/libyang/_install/lib/libyang1/user_types/user_inet_types.so" successfully loaded.
[INF]: LY: Reading module "ietf-yang-metadata".
[INF]: LY: Module "ietf-yang-metadata@2016-08-05" successfully parsed as implemented.
[INF]: LY: Reading module "yang".
[INF]: LY: Resolving "yang" unresolved schema nodes and their constraints...
[INF]: LY: All "yang" schema nodes and constraints resolved.
[INF]: LY: Module "yang@2017-02-20" successfully parsed as implemented.
[INF]: LY: Reading module "ietf-inet-types".
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-inet-types" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-inet-types@2013-07-15" successfully parsed as implemented.
[INF]: LY: Reading module "ietf-yang-types".
[INF]: LY: Module "ietf-yang-types@2013-07-15" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-yang-types" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Resolving "sysrepo" unresolved schema nodes and their constraints...
[INF]: LY: All "sysrepo" schema nodes and constraints resolved.
[INF]: LY: Module "sysrepo@2020-01-15" successfully parsed as implemented.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Scheduled changes not applied because of other existing connections.
[INF]: LY: Searching for "ietf-datastores" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-datastores@2018-02-14.yang" file.
[INF]: LY: Module "ietf-datastores@2018-02-14" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-yang-library" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-yang-library@2019-01-04.yang" file.
[INF]: LY: Searching for "ietf-inet-types" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Searching for "ietf-datastores" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-datastores@2018-02-14.yang" file.
[INF]: LY: Module "ietf-yang-library@2019-01-04" successfully parsed as implemented.
[INF]: LY: Searching for "sysrepo-monitoring" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/sysrepo-monitoring@2020-04-17.yang" file.
[INF]: LY: Resolving "sysrepo-monitoring" unresolved schema nodes and their constraints...
[INF]: LY: All "sysrepo-monitoring" schema nodes and constraints resolved.
[INF]: LY: Module "sysrepo-monitoring@2020-04-17" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-netconf-with-defaults" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-netconf-with-defaults@2011-06-01.yang" file.
[INF]: LY: Searching for "ietf-netconf" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-netconf@2013-09-29.yang" file.
[INF]: LY: Searching for "ietf-netconf-acm" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-netconf-acm@2018-02-14.yang" file.
[INF]: LY: Module "ietf-netconf-acm@2018-02-14" successfully parsed as imported.
[INF]: LY: Module "ietf-netconf@2013-09-29" successfully parsed as imported.
[INF]: LY: Resolving "ietf-netconf-with-defaults" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-netconf-with-defaults" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-netconf-with-defaults@2011-06-01" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-netconf-notifications" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-netconf-notifications@2012-02-06.yang" file.
[INF]: LY: Resolving "ietf-netconf-notifications" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-netconf-notifications" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-netconf-notifications@2012-02-06" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-origin" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-origin@2018-02-14.yang" file.
[INF]: LY: Searching for "ietf-yang-metadata" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Resolving "ietf-origin" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-origin" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-origin@2018-02-14" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-netconf-monitoring" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-netconf-monitoring@2010-10-04.yang" file.
[INF]: LY: Module "ietf-netconf-monitoring@2010-10-04" successfully parsed as implemented.
[INF]: LY: Searching for "nc-notifications" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/nc-notifications@2008-07-14.yang" file.
[INF]: LY: Searching for "notifications" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/notifications@2008-07-14.yang" file.
[INF]: LY: Module "notifications@2008-07-14" successfully parsed as imported.
[INF]: LY: Module "nc-notifications@2008-07-14" successfully parsed as implemented.
[INF]: LY: Module "notifications@2008-07-14" now implemented.
[INF]: LY: Searching for "ietf-tcp-common" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-tcp-common@2019-07-02.yang" file.
[INF]: LY: Module "ietf-tcp-common@2019-07-02" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-netconf-server" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-netconf-server@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-x509-cert-to-name" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-x509-cert-to-name@2014-12-10.yang" file.
[INF]: LY: Module "ietf-x509-cert-to-name@2014-12-10" successfully parsed as imported.
[INF]: LY: Searching for "ietf-tcp-client" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-tcp-client@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-tcp-common" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-tcp-common@2019-07-02.yang" file.
[INF]: LY: Module "ietf-tcp-client@2019-07-02" successfully parsed as imported.
[INF]: LY: Searching for "ietf-tcp-server" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-tcp-server@2019-07-02.yang" file.
[INF]: LY: Module "ietf-tcp-server@2019-07-02" successfully parsed as imported.
[INF]: LY: Searching for "ietf-ssh-server" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-ssh-server@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-ssh-common" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-ssh-common@2019-07-02.yang" file.
[INF]: LY: Module "ietf-ssh-common@2019-07-02" successfully parsed as imported.
[INF]: LY: Searching for "ietf-keystore" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-keystore@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-crypto-types" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-crypto-types@2019-07-02.yang" file.
[INF]: LY: Module "ietf-crypto-types@2019-07-02" successfully parsed as imported.
[INF]: LY: Resolving "ietf-keystore" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-keystore" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-keystore@2019-07-02" successfully parsed as imported.
[INF]: LY: Searching for "iana-crypt-hash" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/iana-crypt-hash@2014-08-06.yang" file.
[INF]: LY: Module "iana-crypt-hash@2014-08-06" successfully parsed as imported.
[INF]: LY: Module "ietf-ssh-server@2019-07-02" successfully parsed as imported.
[INF]: LY: Searching for "ietf-tls-server" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-tls-server@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-tls-common" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-tls-common@2019-07-02.yang" file.
[INF]: LY: Module "ietf-tls-common@2019-07-02" successfully parsed as imported.
[INF]: LY: Searching for "ietf-truststore" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-truststore@2019-07-02.yang" file.
[INF]: LY: Module "ietf-truststore@2019-07-02" successfully parsed as imported.
[INF]: LY: Module "ietf-tls-server@2019-07-02" successfully parsed as imported.
[INF]: LY: Resolving "ietf-netconf-server" unresolved schema nodes and their constraints...
[WRN]: LY: Identity found, but in a non-implemented module "ietf-x509-cert-to-name".
[WRN]: LY: Failed to resolve identityref "ietf-x509-cert-to-name:specified". (/ietf-netconf-server:map-type)
[WRN]: LY: Previous warning generated by XPath subexpression[3] "map-type = 'ietf-x509-cert-to-name:specified'".
[WRN]: LY: Identity found, but in a non-implemented module "ietf-x509-cert-to-name".
[WRN]: LY: Failed to resolve identityref "ietf-x509-cert-to-name:specified". (/ietf-netconf-server:map-type)
[WRN]: LY: Previous warning generated by XPath subexpression[3] "map-type = 'ietf-x509-cert-to-name:specified'".
[INF]: LY: All "ietf-netconf-server" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-netconf-server@2019-07-02" successfully parsed as implemented.
[INF]: LY: Module "ietf-x509-cert-to-name@2014-12-10" now implemented.
[INF]: LY: Module "ietf-ssh-server@2019-07-02" now implemented.
[INF]: LY: Module "ietf-crypto-types@2019-07-02" now implemented.
[INF]: LY: Module "ietf-netconf-acm@2018-02-14" now implemented.
[INF]: LY: Module "ietf-tls-server@2019-07-02" now implemented.
[INF]: LY: Searching for "ietf-netconf-nmda" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-netconf-nmda@2019-01-07.yang" file.
[INF]: LY: Searching for "ietf-origin" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-origin@2018-02-14.yang" file.
[INF]: LY: Searching for "ietf-netconf-with-defaults" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-netconf-with-defaults@2011-06-01.yang" file.
[INF]: LY: Resolving "ietf-netconf-nmda" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-netconf-nmda" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-netconf-nmda@2019-01-07" successfully parsed as implemented.
[ERR]: NP: Internal error (/home/mo/share/netconf2_new/netopeer2/src/main.c:641)
[ERR]: NP: Internal error (/home/mo/share/netconf2_new/netopeer2/src/main.c:643)
[INF]: SR: Session 2 (user "root") created.
[ERR]: NP: Internal error (/home/mo/share/netconf2_new/netopeer2/src/main.c:669)
[ERR]: NP: Internal error (/home/mo/share/netconf2_new/netopeer2/src/main.c:672)
[ERR]: NP: Internal error (/home/mo/share/netconf2_new/netopeer2/src/main.c:675)
[ERR]: NP: Internal error (/home/mo/share/netconf2_new/netopeer2/src/main.c:679)
[ERR]: NP: Internal error (/home/mo/share/netconf2_new/netopeer2/src/main.c:684)
[ERR]: NP: Internal error (/home/mo/share/netconf2_new/netopeer2/src/main.c:687)
[ERR]: NP: Internal error (/home/mo/share/netconf2_new/netopeer2/src/main.c:691)
[ERR]: NP: Internal error (/home/mo/share/netconf2_new/netopeer2/src/main.c:695)
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Ext SHM was defragmented and 4272 B were saved.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-keystore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-truststore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
The above is the information printed by the running software ”netopeer2-server -d -v 4“.

netopeer2-cli 
> connect 
nc ERROR: Unable to translate the host address (Temporary failure in name resolution).
nc ERROR: Unable to connect to localhost:830 (No such process).
cmd_connect: Connecting to the localhost:830 as user "root" failed.

Is not running those scripts in the embedded device cause this?

**Comment by michalvasko** [comment]
Please use the latest release of *netopeer2* or the version in `devel`, the error lines do not match.

Regards,
Michal

**Comment by kuailedeluojie-sudo** [comment]
> Please use the latest release of _netopeer2_ or the version in `devel`, the error lines do not match.
> 
> Regards,
> Michal

The error line is that I added the print information myself. Now when I use netopeer2-cli software, I can't connect to the server. I think it's related to the script running when make install.

**Comment by kuailedeluojie-sudo** [comment]
When I execute the command 
export  SYSREPOCFG=/opt/all/sysrepo/bin/sysrepocfg
wr $SYSREPOCFG -X -x "/ietf-keystore:keystore/asymmetric-keys/asymmetric-key[name='genkey']/name"
Will prompt
[ERR]: Failed to open "/sr_yang.operational" (No such file or directory).
![image](https://user-images.githubusercontent.com/60098441/88609000-a68ae580-d0b5-11ea-8e82-c10e349156c8.png)
What is the cause?

**Comment by michalvasko** [comment]
That is a problem on your platform only, I am sorry but I will not waste my time debugging that. Install it normally and figure out yourself what steps you need to take to make it work in your specific case.

Regards,
Michal

**Comment by kuailedeluojie-sudo** [comment]
> That is a problem on your platform only, I am sorry but I will not waste my time debugging that. Install it normally and figure out yourself what steps you need to take to make it work in your specific case.
> 
> Regards,
> Michal

thank you! I want to know what version of librb is? I want to add this library to solve this problem by cross compiling.

**Comment by michalvasko** [comment]
Hi,
I do not know what `librb` is and it is not used in our projects. I do not think I can help you any more.

Regards,
Michal

**Comment by kuailedeluojie-sudo** [comment]
> Hi,
> I do not know what `librb` is and it is not used in our projects. I do not think I can help you any more.
> 
> Regards,
> Michal

thank you! The first time I encounter this problem, I don't know how to start, right! I would like to know how to create those shared memory files in the /dev/shm  directory when using the make install command after netoper2 is successfully compiled.

**Comment by kuailedeluojie-sudo** [comment]
> They are created automatically during `make install` of _netopeer2_.

thank you!
`[INF]: LN: Listening on 0.0.0.0:830 for SSH connections.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Ext SHM was defragmented and 4260 B were saved.`
Run the "netopeer2-server -d -v 4" command to print the above information, Netoper2-cli uses connect to prompt:
![image](https://user-images.githubusercontent.com/60098441/89024414-a7db3d00-d357-11ea-9c20-906dae5e215d.png)

what is the cause?

**Comment by michalvasko** [comment]
Hi,
I have idea, it is the first time I see it but it is not a *netopeer2*/*libnetconf2* problem. Maybe you have something wrong with your IPv4 stack? I really don't know.

Regards,
Michal

**Comment by kuailedeluojie-sudo** [comment]
> Hi,
> I have idea, it is the first time I see it but it is not a _netopeer2_/_libnetconf2_ problem. Maybe you have something wrong with your IPv4 stack? I really don't know.
> 
> However, you may try to specify the hostname (`--host`) explicitly, `localhost` is used by default. You can try `127.0.0.1`, for example.
> 
> Regards,
> Michal

That's OK. Thank you very much! I'll try.

**Comment by kuailedeluojie-sudo** [comment]
> > Hi,
> > I have idea, it is the first time I see it but it is not a _netopeer2_/_libnetconf2_ problem. Maybe you have something wrong with your IPv4 stack? I really don't know.
> > However, you may try to specify the hostname (`--host`) explicitly, `localhost` is used by default. You can try `127.0.0.1`, for example.
> > Regards,
> > Michal
> 
> That's OK. Thank you very much! I'll try.

![image](https://user-images.githubusercontent.com/60098441/89026153-c131b880-d35a-11ea-9768-e3023ad107b8.png)

**Comment by michalvasko** [comment]
Um, please try to be more self-sufficient. What I meant was using `connect --host 127.0.01`. Use  `connect -h` to see all the options.

**Comment by kuailedeluojie-sudo** [comment]
> 嗯，请尝试更加自给自足。我的意思是使用`connect --host 127.0.0.1`。使用   `connect -h`到看到所有的选项。



> Um, please try to be more self-sufficient. What I meant was using `connect --host 127.0.0.1`. Use  `connect -h` to see all the options.

OK!

**Comment by kuailedeluojie-sudo** [comment]
> Um, please try to be more self-sufficient. What I meant was using `connect --host 127.0.0.1`. Use  `connect -h` to see all the options.

![image](https://user-images.githubusercontent.com/60098441/89092022-d0f3e000-d3e0-11ea-8485-17b5138f9fda.png)
This is part of the information for running "netopeer2-server -d -v 4".

**Comment by michalvasko** [comment]
Hi,
okay, that is the expected output and it means the server is listening. What is the problem?

Regards,
Michal

**Comment by kuailedeluojie-sudo** [comment]
HI,
I know that this is normal printing information. According to the normal process, I can connect to the netoper2-server normally when I use netoper2-cli. Because netoper2-server has opened port 830 for SSH, but when I scan the IP address with nmap, I found that port 830 is not open, so I mentioned this problem.

**Comment by michalvasko** [comment]
Hi,
well, if the server printed it is listening, it should be. Otherwise, it must have been blocked by some other component somewhere such as firewall or something like that. I am not able to help you more.

Regards,
Michal

**Comment by kuailedeluojie-sudo** [comment]
![image](https://user-images.githubusercontent.com/60098441/89259296-9ac29480-d65c-11ea-8cf1-dc425cadaf15.png)

![image](https://user-images.githubusercontent.com/60098441/89259450-ec6b1f00-d65c-11ea-9664-d178e28a02ac.png)
Hi，
I modified the code of netoper2 server. Now port 830 should be open and can be connected normally. However, when I connect with netopeer2 cli, this prompt message appears.
![image](https://user-images.githubusercontent.com/60098441/89259577-2b997000-d65d-11ea-94f4-81288006fc1e.png)

**Comment by michalvasko** [comment]
Hi,
as soon as you start modifying the code it is mostly impossible for me to help. This error seems to be a result of that because I have never seen it before and it looks quite strange.

Regards,
Michal

**Comment by kuailedeluojie-sudo** [comment]
Hi,
![image](https://user-images.githubusercontent.com/60098441/89268562-496dd180-d66b-11ea-90cd-f5468b155d1a.png)

I just changed this code.

**Comment by michalvasko** [comment]
Okay but I still do not know what the error means. The only suspicious thing I see is you using *libssh* 0.8.90, which is manually compiled code from `master` in git. That is always dangerous and I would suggest you to use *libssh* 0.9.2, which may also solve this problem.

Regards,
Michal

**Comment by kuailedeluojie-sudo** [comment]
Hi,
![image](https://user-images.githubusercontent.com/60098441/89364869-0ca2e880-d706-11ea-8c63-6dfdb1649134.png)
![image](https://user-images.githubusercontent.com/60098441/89364884-14628d00-d706-11ea-9e0d-0d3ef375d01d.png)
When I use netoper2 cli to connect to the netoper2 server on another embedded device, I will prompt this message. How can I solve this problem?

**Comment by michalvasko** [comment]
Hi,
based on the log, you have simply failed to authenticate as `root` meaning you have used an incorrect password.

Regards,
Michal

**Comment by kuailedeluojie-sudo** [comment]
Hi,
![image](https://user-images.githubusercontent.com/60098441/89383615-610e8e00-d72f-11ea-94f7-7b13aca69348.png)
Maybe it's really the question you're talking about.

**Comment by kuailedeluojie-sudo** [comment]
Hi,
![image](https://user-images.githubusercontent.com/60098441/89513992-da79af80-d807-11ea-85b3-dba5cb86c23b.png)
I changed the version of libssh (0.92). However, the problem still exists. The first time I contacted netoper2 software, as you said, it was a password verification problem. I used SSH to connect to port 22 of this machine. The password is correct. Does root user of netoper2 server have a separate password?
![image](https://user-images.githubusercontent.com/60098441/89514381-5aa01500-d808-11ea-94ec-ceacb6ab6988.png)
![image](https://user-images.githubusercontent.com/60098441/89514398-62f85000-d808-11ea-8aa8-3f2ded430ad0.png)

**Comment by michalvasko** [comment]
Then I can only suggest you debug this yourself and learn why the passwords do not match. I am not able to reproduce this or help you in any way, it is specific to your system.

Regards,
Michal

**Comment by kuailedeluojie-sudo** [comment]
Hello! Excuse me, I found it“ Dockfile.devel ”File, and then through "docker build - t net." on Ubuntu 18.04, when you want to create a docker file, you encounter the following problems. Is there a good solution?
![image](https://user-images.githubusercontent.com/60098441/89629027-b97c9180-d8cf-11ea-9686-9fc9117890f1.png)

**Comment by michalvasko** [comment]
Hi,
on Ubuntu 18.04 there should be *libssh* 0.8.0, I have just checked.

Regards,
Michal
