### ISSUE TITLE
Invalid context for LYB data parsing

### ISSUE THREAD

**Issue by nic1225** [sysrepo/sysrepo#2059]
hi, 
I use libyang-1.0.184 & sysrepo-1.4.70.
as long as I install `ietf-keystore`, this problem will occur when I install any other Yang files.

    [root@localhost modules]# sysrepoctl -a -i  ietf-crypto-types@2019-07-02.yang -p 600 -o root -g root -v2
    [root@localhost modules]# sysrepoctl -a -i  ietf-keystore@2019-07-02.yang -p 600 -o root -g root -v2
    [root@localhost modules]# sysrepoctl -a -i  ietf-truststore@2019-07-02.yang -p 600 -o root -g root -v2
    [ERR]: Invalid context for LYB data parsing, missing module "ietf-keystore@2016-10-31".
    [ERR]: Failed to update data for the new context.
    sysrepoctl error: Failed to apply changes (Operation failed)

` ietf-ip` file also has same feature with yang file `ietf-keystore`.

    [root@localhost yang]# sysrepoctl -a -i  ietf-ip@2017-12-16.yang -p 600 -o root -g root -v2
    [root@localhost yang]# sysrepoctl -a -i  ietf-inet-types@2013-07-15.yang -p 600 -o root -g root -v2
    [ERR]: Invalid context for LYB data parsing, missing module "ietf-ip@2014-06-16".
    [ERR]: Failed to update data for the new context.
    sysrepoctl error: Failed to apply changes (Operation failed)

thanks
Nick.

**Comment by michalvasko** [comment]
Hi Nick,
you have some chaos in the used module revisions. Did you update *sysrepo* recently? Did you install any modules/data before installing these modules?

Regards,
Michal

**Comment by nic1225** [comment]
Hi Michal,
thanks. I cleared yang modules before uninstalling the old version sysrepo(0.7.7), and the problem was solved.
