### ISSUE TITLE
in my test i only found he first time model change notify MSG on the sr client log, and the follow-up notify MSG seems can not receive,is any one can do me a favor,thanks a lot.

### ISSUE THREAD

**Issue by ZhaoGuangYue** [sysrepo/sysrepo#206]
in my test  i only found he first time model change notify MSG on the sr client log, and the follow-up notify MSG seems can not receive,is any one can do me a favor,thanks a lot.

===first time model change log ===

netopeer2-server[14610]: (rp_dt_commit:697) Commit (3/7): all modified models loaded successfully
netopeer2-server[14610]: (rp_dt_commit:706) Commit (4/7): replay of operation succeeded
netopeer2-server[14610]: (rp_dt_commit:715) Commit (5/7): merged models validation succeeded
netopeer2-server[14610]: (rp_dt_commit:720) Commit (6/7): data write succeeded
netopeer2-server[14610]: (dm_commit_notify:2488) Sending notifications about the changes made in running datastore...
**netopeer2-server[14610]: (_np_subscription_notify:751_) Sending module-change notification to '/tmp/sysrepo-subscriptions/ManagedElement/14610.x02Lih.sock' @ 1843744969.
netopeer2-server[14610]: (_cl_sm_notif_process:556_) Received a notification for subscription id=1843744969 (source address='/tmp/sysrepo-local-14610.sock').**
netopeer2-server[14610]: (sm_session_create:467) New session created successfully, real user=root, effective user=(null), session id=665374554.
netopeer2-server[14610]: (cl_sm_notif_process:609) Calling module-change callback for subscription id=1843744969.
netopeer2-server[14610]: *** Handle change of module ManagedElement ... ***
netopeer2-server[14610]: (dm_unlock_datastore:786) Unlock datastore request
netopeer2-server[14610]: (rp_dt_commit:741) Commit (7/7): finished successfully
netopeer2-server[14610]: EDIT-CONFIG: done.

===second time model change log  === --can not see the _cl_sm_notif_process receive msg

netopeer2-server[14610]: (rp_dt_commit:697) Commit (3/7): all modified models loaded successfully
netopeer2-server[14610]: (rp_dt_commit:706) Commit (4/7): replay of operation succeeded
netopeer2-server[14610]: (rp_dt_commit:715) Commit (5/7): merged models validation succeeded
netopeer2-server[14610]: (rp_dt_commit:720) Commit (6/7): data write succeeded
netopeer2-server[14610]: (dm_commit_notify:2488) Sending notifications about the changes made in running datastore...
**netopeer2-server[14610]: (_np_subscription_notify:751_) Sending module-change notification to '/tmp/sysrepo-subscriptions/ManagedElement/14610.x02Lih.sock' @ 1843744969.**
netopeer2-server[14610]: (dm_unlock_datastore:786) Unlock datastore request
netopeer2-server[14610]: (rp_dt_commit:741) Commit (7/7): finished successfully
netopeer2-server[14610]: EDIT-CONFIG: done.

**Comment by rastislavszabo** [comment]
Hi,

we would need some more information to be able to help you:

What application has subscribed for changes in ManagedElement? What API call has been used? Are you sure that in the moment of the second change, the subscribed application was still running?

Could you please isolate the issue to some minimalistic unit-test code, so that we can reporoduce it?

Thanks,
Rastislav
