### ISSUE TITLE
Question: are change subscription callbacks serialized to handle multiple change initiators

### ISSUE THREAD

**Issue by bbergquist0930** [sysrepo/sysrepo#2061]
If there are multiple change initiators that happen to make changes to data that is handled by a change subscription callback, are the callbacks serialized?  The callback could have state that is not conducive to multiple access.  While one could have private state through the "private data" that is provided with the callback, I am wondering if that state has to handle concurrent callbacks.

**Comment by michalvasko** [comment]
Hi,
are you talking about `SR_EV_CHANGE` or `SR_EV_UPDATE` callback event? You can change data only in the latter case and subscribing for that event does not support having more callbacks on one module with the same priority, meaning the callbacks are always serialized.

Regards,
Michal

**Comment by bbergquist0930** [comment]
I was thinking more of I have 2 or more Netopeer-cli client that are accessing sysrepo through the Netopeer2-server and they perform a change to the same data at the same time.  Some resources are being allocated during the validate phase to handle the requests that are then processed and released during the commit phase or released in the abort phase.

So if these multiple clients attempt to change the data at the same time, I was wondering about sysrepo traversing those phases and if they were serialized such that client 1 would see phases validate/commit and then client 2 see validate/commit or could it be seen as client 1 validate, client 2 validate, client 2 commit, client 1 commit.

Note that I know about locking the datastore and handling the issue at that level, I am more looking at from an internal point of view from maintaining state across the phases (ie if a global construct like a list were being used, it might be corrupted by multiple access).

I do appreciate you taking the time to answer.

**Comment by michalvasko** [comment]
Hi,
okay, *sysrepo* operates with data on the level of modules. Meaning if there is at least one module that is modified by 2 edits, these edits are always serialized. So, using your words, if the same data are being modified, the second request is postponed until the first request is finished.

Regards,
Michal
