### ISSUE TITLE
"config false" causes "libyang: Unknown element"

### ISSUE THREAD

**Issue by pkokkinos** [sysrepo/sysrepo#2064]
Hi,

I use the containerized sysrepo https://hub.docker.com/r/sysrepo/sysrepo-netopeer2/

I install a yang file (sysrepotctl --install file.yang), restart the container and then I import an initial configuration (sysrepocfg --import=file.xml -m module_name  -d startup).

When I use "config false" directive, e.g.

container ha {
    		config false;
                uses generic_profile; 
}

then the import operation returns the msg "sysrepocfg error: libyang: Unknown element "ha"."

When config is true or not config cmd is used then the import is performed succesfully.

Any ideas?

Thank you.

**Comment by michalvasko** [comment]
Hi,
*sysrepocfg* `import` operation is only for configuration data, hence the error. How to set (provide) state (operational) data is mentioned in the [docs](https://netopeer.liberouter.org/doc/sysrepo/master/index.html#oper_data).

Regards,
Michal

**Comment by pkokkinos** [comment]
Thank you
