### ISSUE TITLE
How to use sr_set_item_str to create a libyang tree?

### ISSUE THREAD

**Issue by fxie00** [sysrepo/sysrepo#2065]
Hi,

Is it possible to create a libyang tree by calling sr_set_item_str multiple times? For example,
```C
lyd_node *tmp_node;
char *lyd_node_path, *lyd_attr_val;

LY_TREE_DFS_BEGIN(root, next, cur) {
        tmp_node = (struct lyd_node *)cur;
        if ((tmp_node)->schema->nodetype &
            (LYS_LEAF | LYS_LEAFLIST | LYS_ANYDATA))
        {
            lyd_node_path = lyd_path(tmp_node);
            lyd_attr_val = tmp_node->attr->value_str;

            sr_ret = sr_set_item_str(sr_sess, lyd_node_path, lyd_attr_val,
                                     origin, opts);
        }
LY_TREE_DFS_END(node, next, cur)}
```
Here, I assume that:
0. Given a lyd_node (root), which may be a tree with containers and lists as its children;
1. sr_set_item_str recursively create all missing nodes (containers and lists) along the path to the leaves. Thus, we only need to call sr_set_item_str call leaves, leaf lists and anydata;
2. For each lyd_node in the tree, we can use lyd_path to construct a path required by sr_set_item_str;
3. For a leaf lyd_node, we can use lyd_node->attr->value_str as the "value" parameter in sr_set_item_str.

Thanks in advance for any help!

Best regards,
Feng Xie

**Comment by michalvasko** [comment]
Hi,
yes, this seems okay to me. However, this use-case seems like a good candidate for using `sr_edit_batch()`. Just put `root` as the edit, use `merge` as the default operation and you should get the same result (depending on the used `opts`) without any loops.

Regards,
Michal

**Comment by fxie00** [comment]
Hi Michal,

Thanks a lot for the quick response. I evaluated both sr_set_item_str and sr_edit_batch. However, there is a statement in the manual for sr_edit_batch, "Edit content, similar semantics to NETCONF <edit-config> content". Does it mean that the second parameter "struct lyd_node *edit" needs to be constructed in a specific way? Can you please provide an example of using sr_edit_batch, especially constructing "struct lyd_node *edit"?

Best regards,
Feng

**Comment by michalvasko** [comment]
Hi Feng,
all that refers to is that the parameter must be a `edit-config` [config](https://tools.ietf.org/html/rfc6241#page-40). A standard data tree is also a valid `config`, with the default operation on all the nodes. One of `sr_edit_batch()` parameters is the default operation and if you use `merge`, you should get the behavior you want.

To answer, all that is specific about this data tree is that it uses any `operation` metadata on the nodes to override any parent/default operation. Also, the data tree may not be valid, just like for standard `edit-config`. 

Regards,
Michal
