### ISSUE TITLE
How to get the value of input from the callback function of sr_rpc_subscribe_tree

### ISSUE THREAD

**Issue by xxyy0906** [sysrepo/sysrepo#2066]
Hi michalvasko;
    When I subscribe using the sr_rpc_subscribe_tree function, I cannot get the xpath and value of the input as accurately as the callback function of sr_rpc_subscribe. I have tried to use API
```code
 int sr_tree_to_values(const struct lyd_node *data, const char *xpath, sr_val_t **values, size_t *value_cnt), 
```
but it doesn't work. Is there an api that can convert struct lyd_node ***output** to sr_val_t ****output**?
note:
rc = **sr_rpc_subscribe**(session, "/acc-test:get-test-data", rpc_cb_get_test_data, NULL, 0, 0, &subscription);
rc = **sr_rpc_subscribe_tree**(session, "/acc-test:get-test-data",  rpc_cb_get_test_data_tree, NULL, 0, 0, &subscription);

static int
**rpc_cb_get_test_data**(sr_session_ctx_t *session, const char *path, const sr_val_t *input, const size_t input_cnt,
        sr_event_t event, uint32_t request_id, sr_val_t ****output**, size_t *output_cnt, void *private_data)
{}
static int
**rpc_cb_get_test_data_tree**(sr_session_ctx_t *session, const char *xpath, const struct lyd_node *input, sr_event_t event,
        uint32_t request_id, struct lyd_node ***output**, void *private_data)
{}
My ultimate goal is to get the xpath and value of input and the number of inputs like the callback function of sr_rpc_subscribe.

Thank!

**Comment by michalvasko** [comment]
Hi,
why do you then use `sr_rpc_subscribe_tree()` if you want `sr_val_t`? The only difference compared to `sr_rpc_subscribe()` is the format of data so I am confused. In any case, `sr_tree_to_values()` is meant for data but I do not see any reason why it should not work in this case, too, provided that you used a correct `xpath` (that selects all the nodes).

Regards,
Michal

**Comment by xxyy0906** [comment]
Hi michalvasko,
    1.The reason why I use sr_rpc_subscribe_tree is that there is a decimal64 type in my output value, so it may be better to use sr_rpc_subscribe_tree to write the value using str.
    2.I re-tested that when using sr_tree_to_values in the callback function of sr_rpc_subscribe_tree, an error occurred,
```code
rpc_cb_get_test_data_tree(sr_session_ctx_t *session, const char *xpath, const struct lyd_node *input, sr_event_t event,
uint32_t request_id, struct lyd_node *output, void *private_data)
{
    struct lyd_node *node;

    (void)session;
    (void)event;
    (void)request_id;
    (void)private_data;
    sr_val_t *values;
    size_t value_cnt;

    if(input == NULL)
	printf("######input == NULL\n");    
    sr_tree_to_values(input, "/acc-performance:*", &values,&value_cnt);
        
    return SR_ERR_OK;
}
log:[ERR]: Internal error (/home/buildenv/3rd/cxt_netconf_new_dev/sysrepo-devel/src/common.c:2936).
```
```xml
input xml:
<get-data xmlns="urn:ccsa:yang:test">
        <start-time>1970-01-01T00:05:00Z</start-time>
        <end-time>1970-01-01T00:06:00Z</end-time>
</get-data>
```
3.How to get the input value in xml and xpath in struct lyd_node *output,thanks!
Thanks!

**Comment by michalvasko** [comment]
Hi,
could you please update *sysrepo* to the current `devel` so that my lines match?

Regards,
Michal

**Comment by xxyy0906** [comment]
Hi michalvasko,
    Below is my version, for your reference;
    sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.61 (SO v5.5.3)
    netopeer2-server 1.1.32
    I will also update to the latest branch for testing,thanks!
Thanks!

**Comment by michalvasko** [comment]
Hi,
okay, please do the update and post updated result. The problem may have even been fixed already.

Regards,
Michal

**Comment by xxyy0906** [comment]
Hi michalvasko,
    I used the latest devel branch and found that this problem still exists, please try it, thank you!
    premise:
    1. An rpc with input and output
    2. Use rpc_cb_get_test_data_tree to subscribe and use the cli command user-rpc --content to trigger the callback
    3. Get the input value and xpath in the callback function of rpc_cb_get_test_data_tree

    sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.70 (SO v5.5.12)
    netopeer2-server 1.1.39
    compile time: Jul 27 2020, 20:47:40

**Comment by michalvasko** [comment]
Hi,
could you please paste the updated output (internal errors) so that I do not have to reproduce it myself? Once the lines match, I should be able to fix it. Thanks.

Regards,
Michal

**Comment by xxyy0906** [comment]
Hi,
    I just got an internal error,
```code
[ERR]: Internal error (/home/sysrepo-devel/src/common.c:3045).
``` 
Thanks!

**Comment by xxyy0906** [comment]
Hi michalvasko,
    I borrowed your sample code to describe the problem I encountered. The following are the steps I reproduced. You can see if there is a problem with my operation, thanks.
    1.yang:examples.yang
```yang
module examples {
    namespace "urn:examples";
    prefix e;

    container cont {
        leaf l {
            type string;
        }
    }

    container stats {
        config false;
        leaf counter {
            type uint64;
        }

        leaf counter2 {
            type uint64;
        }
    }

    rpc oper {
        input {
            leaf arg {
                type string;
            }
        }

        output {
            leaf ret {
                type int64;
            }
        }
    }

    notification notif {
        leaf val {
            type decimal64 {
                fraction-digits 2;
            }
        }
    }
}

```
    2.rpc-input.xml
```xml
<oper xmlns="urn:examples">
  <arg>input_value</arg>
</oper>
```
3.code:
[rpc_subscribe_example_tree_test.txt](https://github.com/sysrepo/sysrepo/files/4985510/rpc_subscribe_example_tree_test.txt)
Thanks!

**Comment by michalvasko** [comment]
Hi,
okay, should work now without the error but it was just a minor problem and could actually have been ignored. You need to specify the correct XPath for `sr_tree_to_values()`, such as `//*` that will select the whole subtree, not just the top-level element.

Regards,
Michal

**Comment by xxyy0906** [comment]
Hi michalvasko,
    it works now,But I have a question, fill in xpath //* can be accurately obtained, but fill in xpath /examples:oper can not accurately obtain the value and xpath, why?Thanks a lot.
Thanks!

**Comment by michalvasko** [comment]
Well, in short, because that is how XPath works. `/examples:oper` selects just the root RPC element (which actually has no representation in `sr_val_t`, that was the bug) while `//*` selects the root with all the children.

Regards,
Michal
