### ISSUE TITLE
Has the policy for datastore "candidate" implementation changed?

### ISSUE THREAD

**Issue by boboob** [sysrepo/sysrepo#2068]
micalvasko says that "candidate datastore is **no longer shared between sessions**...". https://github.com/sysrepo/sysrepo/issues/1029#issuecomment-357236794

In version 0.7.x, I tested, it was not shared.
(Perhaps candidate might have been shared between different session in the past.)

However, the latest sysrepo again shares candidates between different sessions.

https://github.com/sysrepo/sysrepo/issues/1721#issuecomment-567830552
"YANG defines **one global datastore** and that is what sysrepo will always officially support." 
https://github.com/sysrepo/sysrepo/issues/1752#issuecomment-574539415
"sysrepo was designed as **a centralized datastore** on the system..." 

I can't understand sysrepo's datastore implementation policy, especially candidate.
what is the difference between shared datastore, one global datastore and centralized datastore?

Thanks.

**Comment by michalvasko** [comment]
Hi,
well, *sysrepo* 0.7.x does not share the `candidate` datastore meaning every session has its own copy. Whereas *sysrepo* 1.x supports only a single `candidate` datastore that is shared between all the sessions. Refer to [docs](https://netopeer.liberouter.org/doc/sysrepo/master/index.html#datastores) for more information.

Regards,
Michal

**Comment by boboob** [comment]
Thanks michalvasko.
