### ISSUE TITLE
Question related to "must" condition inside container, when container is used as operand?

### ISSUE THREAD

**Issue by Roky7250** [sysrepo/sysrepo#2069]
Hi, I have yang module that contains these two containers:

```
      container test1 {
        must "(. <= ../test2)" {
          error-message "test1 must not be greater than test2";
        }
        description
          "Empty.";
        leaf num {
          type uint32;
          description
            "Numerator.";
        }
        leaf denom {
          type uint32 {
            range "1..4294967295";
          }
          description
            "Denominator.";
        }
      }
      container test2 {
        description
          "Empty.";
        leaf num {
          type uint32;
          description
            "Numerator.";
        }
        leaf denom {
          type uint32 {
            range "1..4294967295";
          }
          description
            "Denominator.";
        }
      }
```
Problem is next. Even though I put the same values inside leafs inside these two containers "must" condition is never satisfied 
It fails again with error message:
`[ERR]: Must condition "(. <= ../test2)" not satisfied...`

I expect that condition will not be satisfied in this case:
```
            <test1>
              <num>1</num>
              <denum>1000</denum>
            </test1>

            <test2>
              <num>1</num>
              <denum>10</denum>
            </test2>
```
Because even though test2 rational number is grater that test1 rational number, denum value od test1 is grater that denum value of test2 so condition fails.

What  I need here is two container that will represent rational numbers.
I want to create "must" condition so when I fill up container test1, rational number that it will represent can only be less than or equal to rational number that container test2 represents.

Can you help me here?
Is it possible to create condition like that using yang statements, or I need to do it inside code. For example when test1 container is filled up I need to check if that rational number is less than or equal to rational number that container test2 represents?

Thanks in advance
Regards

**Comment by michalvasko** [comment]
Hi,
comparing the containers themselves is not the right approach, they themselves have no meaning. The easiest would probably be to write `must` where you compare `num` and `denom` separately, that logic must be explicit.

Regards,
Michal

**Comment by Roky7250** [comment]
Hi, is ti even possible to compare two containers in sysrepo?

If it is, in that case will leafs of container be compared separately?
In this case:

```
           <test1>
              <num>1</num>
              <denum>1000</denum>
            </test1>

            <test2>
              <num>1</num>
              <denum>10</denum>
            </test2>
```
will must statement `must "(. <= ../test2)"` compare num of test1 with num of test2, and denum of test1 with denum of test2?

Regards

**Comment by michalvasko** [comment]
Hi,
do what I said, do not compare the containers but their leaves instead. But you can compare both leaves in a single `must` such as
```
must "(./num <= ../test2/num) and (./denum <= ../test2/denum)";
```

Regards,
Michal

**Comment by Roky7250** [comment]
Thank you, I created 2 must conditions for each leaf. I forgot that it can be combined inside one `must ` condition.

Regards
