### ISSUE TITLE
Store configuration for multiple devices into the same sysrepo datastore

### ISSUE THREAD

**Issue by gkatsikas** [sysrepo/sysrepo#2071]
Hi,

What is the best way to keep data for multiple network devices (of the same YANG model) into sysrepo?
Can we use the same datastore to store data for multiple devices (e.g., using a YANG list of device models) or should we assume one sysrepo instance per device?

**Comment by michalvasko** [comment]
Hi,
> Can we use the same datastore to store data for multiple devices (e.g., using a YANG list of device models)

definitely this approach because

> should we assume one sysrepo instance per device

this one is not even possible.

Regards,
Michal

**Comment by gkatsikas** [comment]
Thanks!
The latter is possible only if we use multiple servers/VMs, each one running one sysrepo instance, but this approach does not 
really  scale well with increasing number of devices.
