### ISSUE TITLE
container and python bindings

### ISSUE THREAD

**Issue by pkokkinos** [sysrepo/sysrepo#2073]
Hi,

I am using the containerized version of sysrepo through a google instance and I am trying to use python bindings.

I have tried various things but I failed...

Using directly the sysrepo/sysrepo-netopeer2:latest image, it seems that the python bindings are not compiled (sysrepo module not found). 
I tried to compile again sysrepo using the -DGEN_LANGUAGE_BINDINGS=ON but various issues arise when i try to install the required libyang-cpp-dev

I also tried to use the Dockerfiles from the github and build my own image setting again the -DGEN_LANGUAGE_BINDINGS=ON flag . Then another issue appears during the image building "Could NOT find LibSSH: Found unsuitable version "0.7.0", but required is at  least "0.7.1" (found /usr/include)"

Any ideas?

Thank you,
Panagiotis

**Comment by michalvasko** [comment]
Hi,
well, you did not specify what "various issues" are so I am not able to help you. But seeing that you are using a distribution with *libssh* 0.7.0 is not a good sign, that one is ancient. So, the other problems may easily have the same cause, an obsolete Linux distribution, you should use something recent.

Regards,
Michal

**Comment by pkokkinos** [comment]
Hi,

I think it is ok now.

I have updated the dockerfile to get the latest libssh, enable the binding flags in the libyang (-DGEN_LANGUAGE_BINDINGS=ON -DGEN_CPP_BINDINGS=ON) and sysrepo (-DGEN_LANGUAGE_BINDINGS=ON) and added some more packages (python3-dev).

In this way I get a container where python bindings work.

As mentioned in the inital msg I use a google instance for running docker, that uses only ChromiumOS. Perhaps this was causing the libssh issue.

Thank you,
Panagiotis
