### ISSUE TITLE
ssh key exchange error

### ISSUE THREAD

**Issue by zyboy2000** [sysrepo/sysrepo#2074]
SSH key exchange error (kex error : no match for method server host key algo: server [rsa-sha2-512,rsa-sha2-256], client [ssh-rsa,ssh-dss]).

After install , i use netconfbrower to connect it, printf such error,how to solve it? thanks!

**Comment by michalvasko** [comment]
Hi,
this is a generic SSH issue and can be solved in number of ways. To fix it on the server side, you should allow more key algorithms. That is, specifically, a *libssh* problem, but I believe if you modify the system SSH server config file (should be in `/etc/ssh/`) correctly, it should solve the issue.

Regards,
Michal

**Comment by Jakob933** [comment]
We are facing the same issue trying to access netopeer server trough a client in Java. We get the error message `java.lang.IllegalStateException: Unable to negotiate key exchange for server host key algorithms (client: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,ssh-rsa,ssh-dss / server: rsa-sha2-512,rsa-sha2-256)` .  What is confusing for us, if we run `ssh -Q key` it already returns much more key algorithms including the ones we need. So what do we need to change here? Are there any additional restrictions that not all key algorithms can be used to access netopeer server?

**Comment by michalvasko** [comment]
Well, the easiest solution would probably be to configure your Java client to accept the algorithms of the keys presented by the server. How to do that is specific for your client, I cannot help you with that.
