### ISSUE TITLE
Netopeer2-server failing 

### ISSUE THREAD

**Issue by rosy8** [sysrepo/sysrepo#2075]
Hi Michal,

We have 2 different sets of Netconf libs for 2 different processes.
Process1 uses set1 (sysrepo/libyang ) libs and have old yang files. ( No netopeer2/libnetconf are used for this set)

Shared memroy location -/dev/shm/sysrepo

**### /usr/local/XXX/bin/sysrepoctl -l
Sysrepo repository: /path1/sysrepo**

Module Name                | Revision   | Flags | Owner     | Permissions | Submodules | Features

ietf-datastores            | 2018-02-14 | I     | root:root | 666         |            |         
ietf-inet-types            | 2013-07-15 | i     |           |             |            |         
ietf-netconf               | 2011-06-01 | I     | root:root | 666         |            |         
ietf-netconf-notifications | 2012-02-06 | I     | root:root | 666         |            |         
ietf-netconf-with-defaults | 2011-06-01 | I     | root:root | 666         |            |         
ietf-origin                | 2018-02-14 | I     | root:root | 666         |            |         
ietf-yang-library          | 2019-01-04 | I     | root:root | 666         |            |         
ietf-yang-metadata         | 2016-08-05 | i     |           |             |            |         
ietf-yang-types            | 2013-07-15 | i     |           |             |            |         
sysrepo-monitoring         | 2020-04-17 | I     | root:root | 600         |            |         
yang                       | 2017-02-20 | I     | root:root | 666         |            |         

Process2 uses set2 libs(Built with libyang/sysrepo/libnetcon2/netopeer2).
The shared memory location (/dev/shm) is different from the 1st set .

**### The libs/bin path location and yang repositories locations for both sets have been specified differently.** 
 
However, netopeer2-server failed to start as shown below.

[INF]: LY: Plugin "/usr/lib64/libyang1/extensions/metadata.so" successfully loaded.
[INF]: LY: Plugin "/usr/lib64/libyang1/extensions/nacm.so" successfully loaded.
[INF]: LY: Plugin "/usr/lib64/libyang1/user_types/user_inet_types.so" successfully loaded.
[WRN]: LY: Processing "yangdata" user type plugin failed, wrong API version - 1 expected, 0 found.
[INF]: LY: Reading module "ietf-yang-metadata".
[INF]: LY: Module "ietf-yang-metadata@2016-08-05" successfully parsed as implemented.
[INF]: LY: Reading module "yang".
[INF]: LY: Resolving "yang" unresolved schema nodes and their constraints...
[INF]: LY: All "yang" schema nodes and constraints resolved.
[INF]: LY: Module "yang@2017-02-20" successfully parsed as implemented.
[INF]: LY: Reading module "ietf-inet-types".
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-inet-types" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-inet-types@2013-07-15" successfully parsed as implemented.
[INF]: LY: Reading module "ietf-yang-types".
[INF]: LY: Module "ietf-yang-types@2013-07-15" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-yang-types" in /opt/dev/sysrepo/build/repository/yang.
[INF]: LY: Resolving "sysrepo" unresolved schema nodes and their constraints...
[INF]: LY: All "sysrepo" schema nodes and constraints resolved.
[INF]: LY: Module "sysrepo@2020-01-15" successfully parsed as implemented.
[INF]: SR: Libyang internal module "yang" was installed.
[INF]: LY: Module "ietf-datastores@2018-02-14" successfully parsed as implemented.
[INF]: SR: File "ietf-datastores@2018-02-14.yang" was installed.
[INF]: SR: Sysrepo internal dependency module "ietf-datastores" was installed.
[INF]: LY: Searching for "ietf-inet-types" in /opt/dev/sysrepo/build/repository/yang.
[INF]: LY: Searching for "ietf-datastores" in /opt/dev/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/opt/dev/sysrepo/build/repository/yang/ietf-datastores@2018-02-14.yang" file.
[INF]: LY: Module "ietf-datastores@2018-02-14" already in context.
[INF]: LY: Module "ietf-datastores@2018-02-14" successfully parsed as implemented.
[WRN]: LY: Missing status in deprecated subtree (/ietf-yang-library:{grouping}[module-list]/{grouping}[schema-leaf]/schema), inheriting.
[INF]: LY: Module "ietf-yang-library@2019-01-04" successfully parsed as implemented.
[INF]: SR: File "ietf-yang-library@2019-01-04.yang" was installed.
[INF]: SR: Sysrepo internal module "ietf-yang-library" was installed.
[INF]: LY: Resolving "sysrepo-monitoring" unresolved schema nodes and their constraints...
[INF]: LY: All "sysrepo-monitoring" schema nodes and constraints resolved.
[INF]: LY: Module "sysrepo-monitoring@2020-04-17" successfully parsed as implemented.
[INF]: SR: File "sysrepo-monitoring@2020-04-17.yang" was installed.
[INF]: SR: Sysrepo internal module "sysrepo-monitoring" was installed.
[INF]: LY: Module "ietf-netconf@2011-06-01" successfully parsed as implemented.
[INF]: SR: File "ietf-netconf@2011-06-01.yang" was installed.
[INF]: SR: Sysrepo internal dependency module "ietf-netconf" was installed.
[INF]: LY: Searching for "ietf-netconf" in /opt/dev/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/opt/dev/sysrepo/build/repository/yang/ietf-netconf@2011-06-01.yang" file.
[INF]: LY: Module "ietf-netconf@2011-06-01" already in context.
[INF]: LY: Module "ietf-netconf@2011-06-01" successfully parsed as implemented.
[INF]: LY: Module "ietf-netconf-with-defaults@2011-06-01" successfully parsed as implemented.
[INF]: SR: File "ietf-netconf-with-defaults@2011-06-01.yang" was installed.
[INF]: SR: Sysrepo internal module "ietf-netconf-with-defaults" was installed.
[INF]: LY: Resolving "ietf-netconf-notifications" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-netconf-notifications" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-netconf-notifications@2012-02-06" successfully parsed as implemented.
[INF]: SR: File "ietf-netconf-notifications@2012-02-06.yang" was installed.
[INF]: SR: Sysrepo internal module "ietf-netconf-notifications" was installed.
[INF]: LY: Searching for "ietf-yang-metadata" in /opt/dev/sysrepo/build/repository/yang.
[INF]: LY: Resolving "ietf-origin" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-origin" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-origin@2018-02-14" successfully parsed as implemented.
[INF]: SR: File "ietf-origin@2018-02-14.yang" was installed.
[INF]: SR: Sysrepo internal module "ietf-origin" was installed.
[INF]: SR: Datastore copied from <startup> to <running>.
[INF]: SR: Session 1 (user "root") created.
**[ERR]: NP: Module "ietf-netconf" feature "writable-running" not enabled in sysrepo.**
[ERR]: NP: Server init failed.
[INF]: NP: Server terminated.

### **It's expected to fail as the yang modules listed have an older version.**  **However, not getting why its not listing the newer YANG version.**

 **/usr/bin/sysrepoctl -l
Sysrepo repository: /path2/sysrepo**

Module Name                | Revision   | Flags | Owner     | Permissions | Submodules | Features

ietf-datastores            | 2018-02-14 | I     | root:root | 666         |            |         
ietf-inet-types            | 2013-07-15 | i     |           |             |            |         
ietf-netconf               | 2011-06-01 | I     | root:root | 666         |            |         
ietf-netconf-notifications | 2012-02-06 | I     | root:root | 666         |            |         
ietf-netconf-with-defaults | 2011-06-01 | I     | root:root | 666         |            |         
ietf-origin                | 2018-02-14 | I     | root:root | 666         |            |         
ietf-yang-library          | 2019-01-04 | I     | root:root | 666         |            |         
ietf-yang-metadata         | 2016-08-05 | i     |           |             |            |         
ietf-yang-types            | 2013-07-15 | i     |           |             |            |         
sysrepo-monitoring         | 2020-04-17 | I     | root:root | 600         |            |         
yang                       | 2017-02-20 | I     | root:root | 666         |            |         

### **Everything works perfectly fine with the same set of libs (set2) when I execute on a  standalone container**

[root@1e46c866007f netconf_build]# /usr/bin/sysrepoctl -l
Sysrepo repository: /opt/dev/sysrepo/build/repository

Module Name                | Revision   | Flags | Owner     | Permissions | Submodules | Features                                                               

iana-crypt-hash            | 2014-08-06 | i     |           |             |            |                                                                        
ietf-crypto-types          | 2019-07-02 | I     | root:root | 600         |            |                                                                        
ietf-datastores            | 2018-02-14 | I     | root:root | 666         |            |                                                                        
ietf-inet-types            | 2013-07-15 | i     |           |             |            |                                                                        
ietf-keystore              | 2019-07-02 | I     | root:root | 600         |            | keystore-supported                                                     
ietf-netconf               | 2013-09-29 | I     | root:root | 600         |            | writable-running candidate rollback-on-error validate startup url xpath
ietf-netconf-acm           | 2018-02-14 | I     | root:root | 600         |            |                                                                        
ietf-netconf-monitoring    | 2010-10-04 | I     | root:root | 600         |            |                                                                        
ietf-netconf-nmda          | 2019-01-07 | I     | root:root | 600         |            | origin with-defaults                                                   
ietf-netconf-notifications | 2012-02-06 | I     | root:root | 666         |            |                                                                        
ietf-netconf-server        | 2019-07-02 | I     | root:root | 600         |            | ssh-listen tls-listen ssh-call-home tls-call-home                      
ietf-netconf-with-defaults | 2011-06-01 | I     | root:root | 666         |            |                                                                        
ietf-origin                | 2018-02-14 | I     | root:root | 666         |            |                                                                        
ietf-ssh-common            | 2019-07-02 | i     |           |             |            |                                                                        
ietf-ssh-server            | 2019-07-02 | I     | root:root | 600         |            | local-client-auth-supported                                            
ietf-tcp-client            | 2019-07-02 | i     |           |             |            |                                                                        
ietf-tcp-common            | 2019-07-02 | I     | root:root | 600         |            | keepalives-supported                                                   
ietf-tcp-server            | 2019-07-02 | i     |           |             |            |                                                                        
ietf-tls-common            | 2019-07-02 | i     |           |             |            |                                                                        
ietf-tls-server            | 2019-07-02 | I     | root:root | 600         |            | local-client-auth-supported                                            
ietf-truststore            | 2019-07-02 | I     | root:root | 600         |            | truststore-supported x509-certificates                                 
ietf-x509-cert-to-name     | 2014-12-10 | I     | root:root | 600         |            |                                                                        
ietf-yang-library          | 2019-01-04 | I     | root:root | 666         |            |                                                                        
ietf-yang-metadata         | 2016-08-05 | i     |           |             |            |                                                                        
ietf-yang-types            | 2013-07-15 | i     |           |             |            |                                                                        
nc-notifications           | 2008-07-14 | I     | root:root | 600         |            |                                                                        
notifications              | 2008-07-14 | I     | root:root | 600         |            |                                                                        
sysrepo-monitoring         | 2020-04-17 | I     | root:root | 600         |            |                                                                        
yang                       | 2017-02-20 | I     | root:root | 666         |            |                                                                        

Flags meaning: I - Installed/i - Imported; R - Replay support; N - New/X - Removed/U - Updated; F - Feature changes
Features: ! - Means that the feature is effectively disabled because of its false if-feature(s)

All the bins point to the right libs/locations. The repository location is also pointing to the expected location but listed yang files are not proper (Expectation: It should list the yangs which getting listed above in case of the standalone container). 

Suspect some issues at my end but not getting what is that I am missing.
Would appreciate it if you could guide me in this regard.

Thank you in advance.

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
firstly, how did you get the SHM path `/dev/shm/sysrepo`? That is not possible by defining `SYSREPO_SHM_PREFIX` to `/sysrepo` because it should print an error that there can be no `/`.

Other than that I do not think I can help you much, using that prefix multiple *sysrepo* instances should now work but it must be quite chaotic, to always get the environment right depending on which instance you want to work with. So I think somewhere there is your problem.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

Than you for your reply.
firstly, how did you get the SHM path /dev/shm/sysrepo?  
     --> This has been done programmatically by changing the  "SR_SHM_DIR_DEFAULT" value in common.h.in.
/** where SHM files are stored */
#define SR_SHM_DIR_DEFAULT "/dev/shm/sysrepo"

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
well, there you have it. You cannot simply change `/dev/shm` to something else, this path is used only when reading the SHM files, it is not used when they are __created__ because that is performed using `shm_open(3)`, which always uses the path and it cannot be changed.

Regards,
Michal
