### ISSUE TITLE
Internal error after failed sr_apply_changes

### ISSUE THREAD

**Issue by gitter-runner** [sysrepo/sysrepo#2078]
Hi,
I experienced an internal error in _sr_session_stop()_ after failed _sr_apply_changes()_ function call:

```
[ERR] Module "ietf-interfaces" is being used by session 6 (NC SID 4).
[ERR] Internal error (/opt/dev/sysrepo/src/shm_mod.c:640).
```

According to my investigation it happened as follows:
- in _sr_shmmod_modinfo_rdlock_upgrade()_: another thread acquires a read lock between _sr_rwunlock()_ and _sr_shmmod_lock()_ (shm_mod.c:508)
- lock is not released within 2 second and timeout happens
- _shm_lock->write_locked_ is cleared, s_hm_lock->sid_ is not

sysrepo version: 1.4.73
libyang version: 1.0.186

Thanks!

**Comment by michalvasko** [comment]
Hi,
I think you are right, fixed.

Regards,
Michal

**Comment by gitter-runner** [comment]
Thanks for the fix, it worked!
