### ISSUE TITLE
Query of sysrepo persistance.

### ISSUE THREAD

**Issue by iGovindY** [sysrepo/sysrepo#2079]
Hi 

I have two queries:
- how to set the path of persistence at run time?
   We want to configure this info at runtime, if the application using sysrepo, runs in a Kubernetes environment, where persistence storage is decided when a pod comes up, Is there a way to configure sysrepo persistence path at that time?

- what format the datastore is stored?
   this info we need for use cases like encryption of persisted data.

Thanks
 Govind.

**Comment by michalvasko** [comment]
Hi,
I am not sure what exactly "persistence" is supposed to mean but if you refer to all the persistent (not lost after reboot) state of *sysrepo*, it is in the repository. You can adjust this path in run-time with an [environment variable](https://github.com/sysrepo/sysrepo#used-run-time-enviromental-variables). As for the format, all the data are stored in *libyang* LYB files.

Regards,
Michal

**Comment by mdoshi-com** [comment]
Hi Michal,
We want to secure the datastore which sysrepo maintains (running, candidate, startup). We see that currently it is maintained in the form of files where i guess as you said data is stored in libyang LYB format.

So to make this secure, so that any hacker cannot access the files and read it (since libyang LYB format is well defined format), does sysrepo has any option to make this whole storage secure so that even if someone accesses these files, he cannot be able to decrypt the data.

Regards,
Meghna

**Comment by michalvasko** [comment]
That is currently not possible, but may be in the future. Now the security is provided by file system permissions that are used by *sysrepo*.

**Comment by mdoshi-com** [comment]
Hi Michal,
Ok thanks.
Can you point me the file, from where are read/writes to various datastore is done (startup, running, candidate).

Regards,
Meghna

**Comment by michalvasko** [comment]
Well, the low-level functions are [sr_module_file_data_append](https://github.com/sysrepo/sysrepo/blob/master/src/common.c#L4014) for reading data and [sr_module_file_data_set](https://github.com/sysrepo/sysrepo/blob/master/src/common.c#L4090) for writing data, which should be used on all such occasions. But there may be some other [specialized access](https://github.com/sysrepo/sysrepo/blob/master/src/common.c#L4014) to the files.

**Comment by mdoshi-com** [comment]
Hi Michal,
Ok thanks.
One more query, you said that
`the security is provided by file system permissions that are used by sysrepo.`
So how are we able to set the username/password for the files in sysrepo.

Regards,
Meghna

**Comment by michalvasko** [comment]
> So how are we able to set the username/password for the files in sysrepo.

That is not how file system permissions work. Just like for normal files, you set the owner/permissions for a file and based on the current user, the system lets you access the file or not. You can see/change owner/permissions for *sysrepo* files with `sysrepoctl`.
