### ISSUE TITLE
sysrepocfg version 0.3.0 import error messages

### ISSUE THREAD

**Issue by jjin62** [sysrepo/sysrepo#208]
When importing startup config, I saw the following:

sysrepocfg --import=com-att-device-internal-startup.xml --datastore=startup com-att-device-internal
[ERR] (srcfg_ly_log_cb:84) libyang: Module "module-a" in another revision already implemented.
[ERR] (srcfg_ly_log_cb:84) libyang: Module "module-a" parsing failed.
[ERR] (srcfg_ly_log_cb:84) libyang: Invalid keyword "submodule".
[ERR] (srcfg_ly_log_cb:84) libyang: Module parsing failed.
[ERR] (srcfg_ly_log_cb:84) libyang: Invalid keyword "submodule".
[ERR] (srcfg_ly_log_cb:84) libyang: Module parsing failed.
[ERR] (srcfg_ly_log_cb:84) libyang: Invalid keyword "submodule".
[ERR] (srcfg_ly_log_cb:84) libyang: Module parsing failed.
[ERR] (sr_commit:1111) Error by processing of commit request.
[ERR] (srcfg_import_datastore:663) Error returned from sr_commit: Validation of the changes failed.
Errors were encountered during importing. Cancelling the operation.

It seems that the validation of the input data has failed. It also turns out that after the recent changes made in sysrepocfg the actual validation problems are not printed out, so this error log is not really helpful in narrowing down the exact places in the input data where the conformance with the schema is broken.

**Comment by jjin62** [comment]
Hi Milan,
The Validation error above seems due to a regression bug in sr_commit, not in my data. I tried your set example and it failed as well. This used to work fine. Please see the following:

jimmy@sdn-VirtualBox:~/datastore/sysrepo/build/examples$ ./sr_set_item_example 
[DBG] (sr_log_stderr:125) Setting log level for stderr logs to 4.
[DBG] (sr_connect:293) Connecting to Sysrepo Engine.
[DBG] (cl_socket_connect:357) Connecting to socket=/tmp/sysrepod.sock
[INF] (sr_connect:345) Connected to daemon Sysrepo Engine at socket=/tmp/sysrepod.sock
[DBG] (cl_request_process:401) Sending session-start request.
[DBG] (cl_request_process:423) session-start request sent, waiting for response.
[DBG] (cl_request_process:445) session-start response received, processing.
[DBG] (cl_request_process:401) Sending set-item request.
[DBG] (cl_request_process:423) set-item request sent, waiting for response.
[DBG] (cl_request_process:445) set-item response received, processing.
[DBG] (cl_request_process:401) Sending commit request.
[DBG] (cl_request_process:423) commit request sent, waiting for response.
[DBG] (cl_request_process:445) commit response received, processing.
[ERR] (sr_commit:1053) Error by processing of commit request.
Error by sr_commit: Validation of the changes failed
[DBG] (cl_request_process:401) Sending session-stop request.
[DBG] (cl_request_process:423) session-stop request sent, waiting for response.
[DBG] (cl_request_process:445) session-stop response received, processing.

**Comment by jjin62** [comment]
this is from the latest code:
jimmy@sdn-VirtualBox:~/sysrepo/build/examples$ ./sr_set_item_example 
[DBG] (sr_log_stderr:146) Setting log level for stderr logs to 4.
[DBG] (sr_connect:351) Connecting to Sysrepo Engine.
[DBG] (cl_socket_connect:357) Connecting to socket=/tmp/sysrepod.sock
[INF] (sr_connect:403) Connected to daemon Sysrepo Engine at socket=/tmp/sysrepod.sock
[DBG] (cl_request_process:401) Sending session-start request.
[DBG] (cl_request_process:423) session-start request sent, waiting for response.
[DBG] (cl_request_process:445) session-start response received, processing.
[DBG] (cl_request_process:401) Sending set-item request.
[DBG] (cl_request_process:423) set-item request sent, waiting for response.
[DBG] (cl_request_process:445) set-item response received, processing.
[DBG] (cl_request_process:401) Sending commit request.
[DBG] (cl_request_process:423) commit request sent, waiting for response.
[DBG] (cl_request_process:445) commit response received, processing.
[ERR] (sr_commit:1111) Error by processing of commit request.
Error by sr_commit: Validation of the changes failed
[DBG] (cl_request_process:401) Sending session-stop request.
[DBG] (cl_request_process:423) session-stop request sent, waiting for response.
[DBG] (cl_request_process:445) session-stop response received, processing.

**Comment by milanlenco** [comment]
Hi Jimmy,

Could you please re-try the same using the latest code from the devel branch (and re-started daemon). Unfortunately, we couldn't reproduce the issue ourselves. In case the problem still exists, could you please provide us the content of `com-att-device-internal` module schema file as well as data that you are trying to import?

Thank you,
Milan

**Comment by jjin62** [comment]
Hi Milan,
I will try it can let you know.
thanks,
Jimmy

**Comment by jjin62** [comment]
I tested with devl branch and found some issues and will submit them seperately. Close this for now
