### ISSUE TITLE
Ubuntu 20.04 LTS permission denied error

### ISSUE THREAD

**Issue by michalvasko** [sysrepo/sysrepo#2080]
On Ubuntu 20.04, there is an error with yet unknown cause tracked in cesnet/netopeer2#621. In *sysrepo* it manifests in `permission denied` errors on most operations even when using the `root` user. The only solution we can suggest right now is not to use this distribution.

**Comment by gunterw** [comment]
Any updates on this issue? 
I would like to move to 20.04, but require sysrepo2, so currently in a holding pattern.

**Comment by michalvasko** [comment]
There are links to all the bug reports we did in the linked `netopeer2` issue. Sadly, there still was no real answer and there is nothing more we can do. If you can make someone from Ubuntu take an interest in the issue, it would help a great deal.

**Comment by jktjkt** [comment]
This is not a Ubuntu-specific issue. It's caused by recent enough kernel (4.19+) and systemd (>= 241). The `/dev/shm` directory has the sticky bit set, [this kernel patch](https://lwn.net/Articles/748141/) added support for the `fs.protected_regular` sysctl knob, and this knob in turn [gets enabled via `systemd`](https://github.com/systemd/systemd/commit/2732587540035227fe59e4b64b60127352611b35). As a result, one cannot use `O_CREAT` on "somebody else's files" on those world-writable sticky directories.

I'll follow up on a random kernel mailing list to find out if this is the expected behavior here (my personal opinion is "WTF?").

**Comment by michalvasko** [comment]
Um, okay, thanks for learning more about this and keep us posted. Also, it seems I am using kernel `5.8.15` and systemd `246`, everything is working fine.

**Comment by jktjkt** [comment]
How does the output of `sysctl fs.protected_regular` look for you? If it returns `1`, you "should" have problems. If it's at `0`, then this security mechanism is not used, and it should indeed work fine.

**Comment by michalvasko** [comment]
Okay, it is `0` so I am wondering whether it is the default or it is set some other way.

**Comment by jktjkt** [comment]
Looks like Ubuntu might have [reverted to the older behavior](https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1845637). But from that bugreport it seems that they might be willing to implement the new defaults via the `kernel` package anyway in future -- I don't know.

**Comment by michalvasko** [comment]
The config files on OpenSUSE are provided by special `aaa_base` package so that is probably not helpful. However, I have not found `fs.protected_regular` option set in any of those config files meaning it should be set to the default value.

**Comment by gkatsikas** [comment]
Hi,

I also experience this issue with a fresh Ubuntu 20.04.01 installation:

[ERR]: Failed to open "/dev/shm/..." (Permission denied).
[ERR]: Failed to update data for the new context.

Any news on that?

**Comment by maksimvuleta** [comment]
Which is the latest Ubuntu and Kernel version you recommend to use for sysrepo/netopeer2 staff?

**Comment by michalvasko** [comment]
Ubuntu 18.04 should work fine but I cannot pinpoint a specific kernel version.

As for the issue itself, we did what we could ([ref](https://github.com/CESNET/netopeer2/issues/621#issuecomment-668238367)) but seems there is little interest from the people that could actually affect this. So, not much more we can do.

**Comment by maksimvuleta** [comment]
> 
> 
> Ubuntu 18.04 should work fine but I cannot pinpoint a specific kernel version.
> 
> As for the issue itself, we did what we could ([ref](https://github.com/CESNET/netopeer2/issues/621#issuecomment-668238367)) but seems there is little interest from the people that could actually affect this. So, not much more we can do.

Thank you for fast answer.

**Comment by gunterw** [comment]
Isn't setting 'sysctl fs.protected_regular=0' an acceptable workaround for now in 20.04?

or to persist through reboots, something like this

echo "fs.protected_regular = 0" > /etc/sysctl.d/60-disable-fs-protected-regular

**Comment by michalvasko** [comment]
Yes, based on what was written here it should work.

**Comment by maksimvuleta** [comment]
> Isn't setting 'sysctl fs.protected_regular=0' an acceptable workaround for now in 20.04?

I tried this and it works with the latest master revisions of libyang, libnetconf2, sysrepo, Netopeer2... 

Thanks!

**Comment by xbourdeau** [comment]
`sysctl fs.protected_regular=0` is not applied after a reboot if it's set in `/etc/sysctl.con`. I've created a service to reload sysctl at a late stage
```
[Unit]
Description=Apply sysctl tardily

[Service]
User=root
Group=root
Restart=no
ExecStart=sysctl -p
RemainAfterExit=no

[Install]
WantedBy=multi-user.target
```
Not a perfect solution but at least if working

**Comment by sesame0224** [comment]
Excuse me, what is the service you create? I don't know how to use it and I don't know what it ([Unit] Description=...) means.

I want you to answer if you like.

> `sysctl fs.protected_regular=0` is not applied after a reboot if it's set in `/etc/sysctl.conf`. I've created a service to reload sysctl at a late stage
> 
> ```
> [Unit]
> Description=Apply sysctl tardily
> 
> [Service]
> User=root
> Group=root
> Restart=no
> ExecStart=sysctl -p
> RemainAfterExit=no
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> Not a perfect solution but at least it's working

**Comment by xbourdeau** [comment]
> Excuse me, what is the service you create? I don't know how to use it and I don't know what it ([Unit] Description=...) represent.
> 
> I want you to answer if you like.
> 
> > `sysctl fs.protected_regular=0` is not applied after a reboot if it's set in `/etc/sysctl.conf`. I've created a service to reload sysctl at a late stage
> > ```
> > [Unit]
> > Description=Apply sysctl tardily
> > 
> > [Service]
> > User=root
> > Group=root
> > Restart=no
> > ExecStart=sysctl -p
> > RemainAfterExit=no
> > 
> > [Install]
> > WantedBy=multi-user.target
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Not a perfect solution but at least it's working

I've created a service for systemd. Just create file like `/etc/systemd/system/sysctl-reload.service` with text above. 
Then reload the daemon list so systemd will find the new service file, and enable/start it, watch the journal entries...
```
sudo systemctl daemon-reload
sudo systemctl enable sysctl-reload.service
sudo systemctl start sysctl-reload
sudo systemctl status sysctl-reload
sudo journalctl --unit=sysctl-reload
```

**Comment by nagstaku** [comment]
> Isn't setting 'sysctl fs.protected_regular=0' an acceptable workaround for now in 20.04?
> 
> or to persist through reboots, something like this
> 
> echo "fs.protected_regular = 0" > /etc/sysctl.d/60-disable-fs-protected-regular

FYI, this was almost good for me, just have to append ".conf" to the file name for it to be picked up on 20.04.6

echo "fs.protected_regular = 0" > /etc/sysctl.d/60-disable-fs-protected-regular.conf

(found this information in /etc/sysctl.d/README.sysctl )
