### ISSUE TITLE
sysrepo can still write to running datastore without any subscriptions.

### ISSUE THREAD

**Issue by ryanking8215** [sysrepo/sysrepo#2081]
Hi,
     

I import the custom yang file, and generate an data file for edit-config later, use netopeer2-server and cli to test, and not running my application, so there is no subscription of 'my-config' module.

When netopeer2-cli commits finally, netopeer2-server  prints:
```
[INF]: SR: There are no subscribers for changes of the module "my-config" in running DS.
[INF]: SR: Successful processing of "rpc" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 1 priority 0 succeeded.
[INF]: NP: Session 1: thread 3 event new RPC.
```
No error reports, then I use sysrepocfg to export the module data and find the data is what netopeer2-cli commits. 

Is this a normal behavior or an issue? I remember the legacy version (0.x) will report an error if there is no subscription.
If this is an issue, how to fix it?  

Thanks!

ps: sysrepo version is v1.4.66, and netopeer2 version is v1.1.34.

**Comment by ryanking8215** [comment]
I read the source code of sysrepo.

I found that 'sr_shmsub_change_notify_change' check whether there is subscriptions for 'change' and 'done', if there are no ones and DS is running, it prints the information, but no error generate.

then 'sr_modinfo_data_store' will be invoked, which will really store the data.

**Comment by michalvasko** [comment]
Hi,
yeah, this is intentional because *sysrepo* 1.x replaced the old "enabled-data" concept with the standardized NMDA and [operational datastore](https://netopeer.liberouter.org/doc/sysrepo/master/index.html#oper_ds).

Regards,
Michal

**Comment by ryanking8215** [comment]
Then I have a problem if this is intentional.

I use callhome feature.
if netopeer2-server connect to the client by callhome, the client (which is a controller actually) will send the configuration to it.
my application start to run, may has loaded the data from startup DS, but hasn't subscribed for changing yet. And the data will save to running DS, but my application doesn't know, which make the data loss in this turn.

Because callhome by netopeer2-server and subscribed for changing by application are asynchronous. It is like multi threads problem.

I have't found the way to protect it not happened.
Very appreciate that if you can give some advice.

**Comment by michalvasko** [comment]
Hi,
when your application is executed, it should simply subscribe normally to `running` datastore with `SR_SUBSCR_ENABLED`. Then, if it is executed before the new controller configuration is applied, it will simply configure itself based on the current configuration and once the controller sends the new one, your application is already subscribed and will get the changes. In case it subscribes after the controller configuration is applied, your application will get the updated configuration on the first configuration change.

Regards,
Michal

**Comment by ryanking8215** [comment]
Thanks, I will try it. 
Before that I still have some question.

1. If data can be saved without subscription, how to verify the data?  Even data has been verified by the yang model already, but it may be invalid by application logic. This is why we subscribe to running DS with SR_SUBSCR_DEFAULT, which will trigger SR_EV_CHANGE event for application to verify the data before save to DS. 

2. SR_SUBSCR_ENABLED seems not to trigger SR_EV_CHANGE. "opts is bitwise OR-ed value", So is it possible that subscribe with "SR_SUBSRC_ENABLED | SR_SUBSCR_DEFAULT"?

**Comment by michalvasko** [comment]
Hi,
1. Yeah, what can happen is that there could be some `running` data set that are invalid for your specific application. This use-case is covered only by you returning an error in the callback when you get the data on `SR_EV_ENABLED` when you first subscribe.
2. Generally speaking, you should be able to handle `SR_SUBSCR_ENABLED` in the very same way as `SR_EV_CHANGE`, the meaning is almost the same. The event is different just so that you do have the option to do some specific work on this event, you are not forced to.

Regards,
Michal

**Comment by ryanking8215** [comment]
Hi,
    I tried the "SR_SUBSCR_ENABLED" options, and could get the data from startup. Thanks, it worked.
    
     But after that I met another problem. I reset everything, install yang model again, so there is no data in both startup DS and running DS this round, and run my application, it can still read data from sysrepo, and the value is not zero,  which make me confused. 
   I use 'sysrepocfg -X -d [running, startup] -m my-module' to export the data, it is empty.

**Comment by michalvasko** [comment]
Hi,
yes, you will always get default values, which you can distinguish by them having `dflt` set to `1`. However, there is no reason to treat them specially except for print. When applying configuration, they are always present and should be applied.

Regards,
Michal

**Comment by ryanking8215** [comment]
Hi,
     Thanks, I have noticed the dlft of sr_val_t. 
But where does the default value come from?  I never edit startup or running datastore.

**Comment by michalvasko** [comment]
Hi,
there is some [reading](https://tools.ietf.org/html/rfc6243) for you on this topic.

Regards,
Michal

**Comment by ryanking8215** [comment]
Hi,
       Thanks, I have no questions, I think the issue can be closed.
