### ISSUE TITLE
Internal error when trying to push operational data

### ISSUE THREAD

**Issue by gitter-runner** [sysrepo/sysrepo#2082]
Hi,

I have the following yang models installed:

_ietf-interfaces@2018-02-20_ with _if-mib_ feature enabled
_iana-if-type@2018-07-03_
_ietf-microwave-types@2018-10-03_
_ietf-microwave-radio-link@2018-10-03_

When I try to push if-index leaves I get an internal error for the second _sr_apply_changes()_:

```
[ERR]: Internal error (/opt/dev/sysrepo/src/edit_diff.c:2096).
[ERR]: Applying operation "create" failed.
```

Another issue is that there are containers from radio link models in ethernet interface instances:

```
$ sysrepocfg -d operational -m ietf-interfaces -X
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interface>
    <name>eth0</name>
    <description>Test interface 0</description>
    <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
    <if-index>100</if-index>
    <atpc xmlns="urn:ietf:params:xml:ns:yang:ietf-microwave-radio-link"/>
    <adaptive xmlns="urn:ietf:params:xml:ns:yang:ietf-microwave-radio-link"/>
  </interface>
  <interface>
    <name>eth1</name>
    <description>Test interface 1</description>
    <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
    <atpc xmlns="urn:ietf:params:xml:ns:yang:ietf-microwave-radio-link"/>
    <adaptive xmlns="urn:ietf:params:xml:ns:yang:ietf-microwave-radio-link"/>
  </interface>
</interfaces>

```
I attached a simple application to reproduce the issues.
[test_c.txt](https://github.com/sysrepo/sysrepo/files/5028926/test_c.txt)

I haven't met this issue on 1.4.70.

libyang version: 1.0.185
sysrepo version: 1.4.74

Thanks!

**Comment by michalvasko** [comment]
Hi,
actually, I believe this bug has always been present, it just did not manifest before my latest changes. The cause is the never-ending problems with non-presence containers and them supposedly not carrying any meaning versus actually having some meaning. Once I solved the issue with them, the internal error went away so I assumed that was the root cause. However, they may still be something wrong, in which case please report it. Thanks.

Regards,
Michal

**Comment by gitter-runner** [comment]
Hi,
Thanks for the quick fix.
Now the stored oper data works fine, but I still see containers from _ietf-microwave-radio-link_ when I get the ethernet interfaces.

sysrepo version: 1.4.75
libyang version: 1.0.187

**Comment by michalvasko** [comment]
Hi,
right, they are just leftovers caused by the previous bug. Reset *sysrepo* by `make sr_clean` (or simply reinstall the `ietf-interfaces` module) and it should work fine.

Regards,
Michal

**Comment by gitter-runner** [comment]
Hi,
The result seems to be correct when I use _sysrepocfg_, but if I get the interfaces on sysrepo API the radio link containers are still present:


```
$ sr_get_items_example /ietf-interfaces:interfaces//. operational
Application will get "/ietf-interfaces:interfaces//." from "operational" datastore.

/ietf-interfaces:interfaces (container)
/ietf-interfaces:interfaces/interface[name='eth0'] (list instance)
/ietf-interfaces:interfaces/interface[name='eth0']/name = eth0
/ietf-interfaces:interfaces/interface[name='eth0']/description = Test interface 0
/ietf-interfaces:interfaces/interface[name='eth0']/type = iana-if-type:ethernetCsmacd
/ietf-interfaces:interfaces/interface[name='eth0']/enabled = true [default]
/ietf-interfaces:interfaces/interface[name='eth0']/statistics (container)
/ietf-interfaces:interfaces/interface[name='eth0']/ietf-microwave-radio-link:capabilities (container)
/ietf-interfaces:interfaces/interface[name='eth0']/ietf-microwave-radio-link:error-performance-statistics (container)
/ietf-interfaces:interfaces/interface[name='eth0']/ietf-microwave-radio-link:radio-performance-statistics (container)
/ietf-interfaces:interfaces/interface[name='eth1'] (list instance)
/ietf-interfaces:interfaces/interface[name='eth1']/name = eth1
/ietf-interfaces:interfaces/interface[name='eth1']/description = Test interface 1
/ietf-interfaces:interfaces/interface[name='eth1']/type = iana-if-type:ethernetCsmacd
/ietf-interfaces:interfaces/interface[name='eth1']/enabled = true [default]
/ietf-interfaces:interfaces/interface[name='eth1']/statistics (container)
/ietf-interfaces:interfaces/interface[name='eth1']/ietf-microwave-radio-link:capabilities (container)
/ietf-interfaces:interfaces/interface[name='eth1']/ietf-microwave-radio-link:error-performance-statistics (container)
/ietf-interfaces:interfaces/interface[name='eth1']/ietf-microwave-radio-link:radio-performance-statistics (container)
```

**Comment by michalvasko** [comment]
Hi,
the existence of these containers is intentional, it is a *libyang* feature, not a bug. They are hidden by default for all prints and you can easily find these empty non-presence containers because they have their `dflt` flag set.

Regards,
Michal

**Comment by gitter-runner** [comment]
Hi,
These containers come from an augment with the following condition (_ietf-microwave-radio-link_):
```

augment "/if:interfaces/if:interface" {
    when "derived-from-or-self(if:type,"
       + "'mw-types:carrier-termination')";

```
This when condition is not true for the interfaces with type _iana-if-type:ethernetCsmacd_.
In sysrepo version 1.4.70 these containers were not present in get results.
Is this changed behavior intentional?

**Comment by michalvasko** [comment]
Hi,
I see, the behavior change is not really intentional but an expected result of intentional changes. Specifically, the `operational` datastore is not validated so these containers do not get deleted. I agree this is a bit unfortunate but I do not think there is a simple solution. Ideally, these containers should be `presence` to avoid these kinds of problems.

Regards,
Michal
