### ISSUE TITLE
CDATA XML parsing 

### ISSUE THREAD

**Issue by jeffreymarius** [sysrepo/sysrepo#2083]
Hi,  The rich set of sysrepo APIs helps to obtain the necessary items using XPath. Thank You for this.
But my clarification is, Is there any APIs that we can use to parse the CDATA within an XML. I am planning nesting an XML confgs in CDATA but currently when I reference it I get the output (unprintable).

```
$ ./a.out /nrm:ME/Function[id='0']/DataContainer[id='0']/Data
The value of /nrm:ME/Function[id='0']/DataContainer[id='0']/Data  xpath is (unprintable)
```

My XML format is something like this:
```
      <DataContainer>
        <id>0</id>
        <Data><![CDATA[
		   <dvs xmlns="urn:dovi:jen:co:dvs-li">
		     <Config>
			   <id>0</id>
               <numOut>2</numOut>
               <maxIn>2</maxIn>
               <maxAttempt>5</maxAttempt>
		     </Config>
		   </dvs>
        ]]></Data>
```

I even tried referencing the CDATA xml namespace as such "/nrm:ME/Function[id='0']/DataContainer[id='0']/Data/dvs-li:dvs/Config/id" but this is not correct which I understood later after reading about CDATA. But I am just curious if by any means Sysrepo APIs have support for this. Also, if there is any heads up u can give me on this it would be great. Thank You.

**Comment by michalvasko** [comment]
Hi,
`CDATA` is not supported at all but what exactly do you want to use it for?

Regards,
Michal

**Comment by jeffreymarius** [comment]
Well just an attempt to try to include one module in another module as CDATA. I know this is absurd but just want to try and see.
I have however restructured the configuration without CDATA.
Thanks for your help :)

**Comment by michalvasko** [comment]
Hi,
I think you can use `anydata` YANG statement for this purpose instead.

Regards,
Michal
