### ISSUE TITLE
How to construct an xPATH for a container with multiple mandatory/key elements?

### ISSUE THREAD

**Issue by fxie00** [sysrepo/sysrepo#2084]
Hi,

I am using sr_set_item_example to set a leaf element, c, in a container, which has two mandatory elements, a and b. My question is that how to construct a valid xpath for such a leaf element?

The yang model hierary is:
```yang
module A {
....
   container B {
        ......
        container C {
             .....
             leaf E {
                    mandatory true;
                    type iana:ipv4-address; 
             }
             leaf F {
                    mandatory true;
                    type ieee:mac-address; 
             }

             ...........

             container G {
                   list H {
                        key "I"
                   
                        leaf I {
                            .....
                        }

                        leaf J {
                            .....
                        }
                 }
            }
      }
   }
}
```        
First, I tried "/A:B/C[E='10.0.0.1'][F='ff-ff-ff-ff-ff-ff']/G/H[I='5']/J" for leaf element J, but sysrepo complains that "[" is not recognized. Then, I tried to create container C first by 

$ sr_set_item_example /A:B/C/E "10.0.0.1"

Sysrepo complains that the other mandatory element F is not set. So how to specify an xPATH for a container/list with multiple mandatory elements/keys? Thanks.

Best regards,
Feng

**Comment by michalvasko** [comment]
Hi,
as the name implies, `sr_set_item_example` is just an example and actually cannot be used for this use-case because you need to create both leaves and apply them at the same time, otherwise the result would be invalid data. So, if you do that, you should have no problems. The example allows applying changes only one-by-one.

Regards,
Michal

**Comment by fxie00** [comment]
Hi Michal,

Thanks again for the quick response. I now understand that sr_set_item_example can't be used for this use case. On the other hand, is it possible to construct an xPATH with multiple mandatory/key elements in general?

To follow your suggestion of creating both leaves and apply them at the same time, is it possible to use sr_set_item_str? This API still requires an xPATH as the second input parameter. Then, we will face the above issue of how to construct an xPATH.

Best regards,
Feng

**Comment by michalvasko** [comment]
Hi Feng,
you cannot construct a single path for this, only simple ones are accepted that create only individual nodes, optionally with some parents. For this use-case you need to call `sr_set_item_str()` twice and only then call `sr_apply_changes()`. That is actually the intended use.

Regards,
Michal

**Comment by fxie00** [comment]
Hi Michal,

Thanks a lot for your response. After my last question was sent, I tried another sysrepo API, sr_edit_batch for the same use case. My understanding is that sr_edit_batch should allow me to create multiple mandatory elements/keys altogether. The following is what I did by following a test function in sysrepo:

struct lyd_node *new_node = NULL;
struct lyd_ctx *yang_ctx;

char *str = 
     "<B xmlns=\"xml_name_space_of_module_A\">"
          "<C>"
              "<E xmlns=\"urn:ietf:params:xml:ns:yang:ietf-inet-types\">30.0.0.1</E>"
             "<F xmlns=\"urn:ieee:std:802.1Q:yang:ieee802-types\">ff-ff-ff-ff-ff-ff</F>"
          "</C>"
      "</B>"

...........
/* retrieve yang_ctx from the connection ctx by using sr_get_context */
new_node = lyd_parse_mem(yang_ctx, str, LYD_XML, LYD_OPT_CONFIG | LYD_OPT_STRICT);
...........

However, new_node was NULL after calling lyd_parse_mem. There was no error returned from lyd_parse_mem. Did I make any mistake in constructing xml string (str)? Thanks!

Feng

**Comment by michalvasko** [comment]
Hi,
firstly, I believe you switching to `sr_edit_batch()` before having `sr_set_item_str()` figured out is a really bad decision as the former is more advanced and harder to make work correctly. Generally, there is no real need to use `sr_edit_batch()` except for some specific use-cases. But suit yourself, just do not expect me to explain every little detail to you, I do not have time for that.

So, parsing those XML data is actually only *libyang* problem and I cannot help you with it unless I see the modules whose data you are parsing. Also, if it returned `NULL`, I am pretty sure there must have been some error, which you should read from the context.

Regards,
Michal

**Comment by fxie00** [comment]
Hi Michal,

Thank you for the always help. Apologize for bothering you with libyang issues. 

We are evaluating Sysrepo and its APIs. We already got sr_set_item_str figured out. More specifically, we can call sr_set_item_str multiple times for different leaf elements and commit changes altogether with one sr_apply_changes.

We are also interested in sr_edit_batch very much, which seems to be able to create/update an entire tree with one call. I tried two different approaches:

#1 With an xPATH, I can use lyd_new_path to generate a lyd_node. It is then passed to sr_edit_batch to update Sysrepo. However, if I  call sr_edit_batch twice for two different leaf nodes. The second sr_edit_batch call fails with an error message of " [ERR]: There are already some session changes."  I searched the web but could not figure out the reason.

#2 Create an xml string with multiple elements. It is passed to lyd_parse_mem to generate a lyd_node. It will be passed to sr_edit_batch to update sysrepo. However, we are blocked on the lyd_parse_mem. To figure out the correct xml format, I followed several examples in the sysrepo test examples but none of them works. I will try to contact libyang forum for some help.

Thanks again for the help!

Best regards,
Feng

**Comment by fxie00** [comment]
Hi Michal,

Just figured out the correct xml format for using lyd_parse_mem and sr_edit_batch. Thanks.

Best regards,
Feng

**Comment by michalvasko** [comment]
Hi,
`sr_edit_batch()` does not support multiple batches, as you found out. You must call `sr_apply_changes()` for each batch. Just one of the reason why I said it is better to avoid it because it most use-cases it is not needed.

Regards,
Michal
