### ISSUE TITLE
Killing callbacks caused "[ERR]: Locking a mutex failed"

### ISSUE THREAD

**Issue by JonathanZailer** [sysrepo/sysrepo#2085]
Hey,

I have a process with 2 callbacks (of module change and RPC - subscribe_module_change, subscribe_rpc_call)
After running 2 processes of the same code I killed the processes.
As a result, I couldn't run the callbacks anymore -> I got timeout.
When running sysrepo cmds like   "sysrepoctl -l" I got:
```[ERR]: Locking a mutex failed (sr_connect: Connection timed out).
sysrepoctl error: Failed to connect (Timeout expired)
```

sysrepo vesion: 
```
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.70 (SO v5.5.12)
```

Is this a bug? 

Thanks for your help,

Jonathan

**Comment by JonathanZailer** [comment]
Already an issue is open about that:
https://github.com/sysrepo/sysrepo/issues/2033

**Comment by michalvasko** [comment]
Hi,
yes, that is the same problem and like I replied there, it is now on my TODO list. However, it will not be a simple change and I am still working on things with higher priority so I do not know when this will be implemented. I would hope in a month or so.

Regards,
Michal
