### ISSUE TITLE
Question: change notification of operational data(config false)

### ISSUE THREAD

**Issue by mookhone** [sysrepo/sysrepo#2087]
Hi,

I'd like to receive change notification if operational data(config false) is changed.

When I checked guide document, it seems to provide notification only for config data(config true).

How can I get change notification for operational data?

**Comment by michalvasko** [comment]
Hi,
well, you can subscribe to *push* operational data changes, but not for *pull*. More in the [docs](https://netopeer.liberouter.org/doc/sysrepo/master/index.html#oper_data). Just be aware that this is advanced and complex functionality so it may not always work as you expect it to unless you understand it well.

Regards,
Michal

**Comment by mookhone** [comment]
I didn't understand well about push and pull. 
 If you let me know the API, I will look for the reference.

**Comment by michalvasko** [comment]
Hi,
that is what I referenced the documentation for, so that you understand it. Did you read it? Did you read the linked pages? What exactly did you not understand?

Regards,
Michal

**Comment by mookhone** [comment]
Hi,

**Comment by mookhone** [comment]
Thank you for your quick reply.
I read all the links you told me. 
However, I did not understand the difference between push method and pull method. 
And I do not know how to use each method at code level.
It would be helpful to understand if you give an sample code for example.

Regards,
Mr.Park

**Comment by michalvasko** [comment]
Hi,
I believe you should be able to use both methods in the code based on the docs. The paragraph about the *pull* method references `operational subscriptions`, which reference `Operational Data Subscription API`. The other paragraph about the *push* method references `editing data` (the link `set normally`), which reference `Editing Data API`. So you have 2 APIs for both methods. Where exactly did you get lost?

Also, there technically are code examples for both APIs. But I suppose having an explicit example setting operational data using both methods would be helpful so I will add it, but not right now.

Regards,
Michal

**Comment by mookhone** [comment]
Hi,
Thank you for your advise.
I'll be waiting for you.

Regards,
Mr.Park

**Comment by michalvasko** [comment]
Fine, I have committed a functioning example so the difference in API should be obvious. Other differences should already be documented.

Regards,
Michal

**Comment by mookhone** [comment]
I understand all because of the sample code you informed me.
Thank you!!.
