### ISSUE TITLE
ietf-netconf-server operational datastore get/set fails.

### ISSUE THREAD

**Issue by iGovindY** [sysrepo/sysrepo#2088]
get and set gives error for `ietf-netconf-server ` module `operational `datastore

```
sysrepocfg -d operational -m ietf-netconf-server -X
[ERR]: Internal error
sysrepocfg error: Getting data failed (User callback failed)
[root@kubernetes-master bin]# sysrepocfg -d running -m ietf-netconf-server -X
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <listen>
    <endpoint>
      <name>default-ssh</name>
      <ssh>
        <tcp-server-parameters>
          <local-address>10.XX.XX.15</local-address>
          <keepalives>
            <idle-time>1</idle-time>
            <max-probes>10</max-probes>
            <probe-interval>5</probe-interval>
          </keepalives>
        </tcp-server-parameters>
        <ssh-server-parameters>
          <server-identity>
            <host-key>
              <name>default-key</name>
              <public-key>
                <keystore-reference>genkey</keystore-reference>
              </public-key>
            </host-key>
          </server-identity>
          <client-authentication>
            <supported-authentication-methods>
              <publickey/>
              <passsword/>
              <other>interactive</other>
            </supported-authentication-methods>
            <users/>
          </client-authentication>
        </ssh-server-parameters>
      </ssh>
    </endpoint>
  </listen>
</netconf-server>
[root@kubernetes-master bin]#
```

**Comment by iGovindY** [comment]
Basically What I wanted to verify that, if We change netconf server IP config in Operational DS then will Netopeer server starts using IP from Operational DS instead of IP in running DS.

We have a case where a POD( Netopeer+sysrepo+BackendApp) comes up and gets a new IP, so we wanted IP config not to be used every time instead BackendApp finds the new IP and configure it.

**Comment by michalvasko** [comment]
Hi,
so I assume you tried to export `operational` config while *netopeer2-server* was running, otherwise you should not get any data. However, when I tried that, it worked without any problems (*netopeer2-server* version 1.1.40) and the correct `operational` was printed without any internal error. So, did you change *netopeer2* code or added some `operational` callbacks for `ietf-netconf-server` data? You must have, otherwise it does not make sense. And the problem is there, not in *netopeer2*.

Regards,
Michal

**Comment by iGovindY** [comment]
Yes I am doing it when netopeer2-server is running.
my netopeer2 version is 1.1.21.

Neither I have changed netopeer2 code nor I have any callbacks registered for `ietf-netconf-server`  data.

**Comment by michalvasko** [comment]
Hi,
okay, can you please post the output of *netopeer2*? It should have printed a detailed message.

Regards,
Michal

**Comment by iGovindY** [comment]
Here are Netopeer2 prints 

```
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: There is no leafref "/ietf-keystore:keystore/ietf-keystore:asymmetric-keys/ietf-keystore:asymmetric-key/ietf-keystore:name" with the value "genkey", but it is not required.
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: LN: Listening on 10.53.203.15:830 for SSH connections.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Ext SHM was defragmented and 4248 B were saved.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Ext SHM was defragmented and 4224 B were saved.
[INF]: SR: Triggering "ietf-keystore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-truststore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Processing "operational" "ietf-netconf-server" event with ID 1.
[ERR]: NP: Opening "Not a directory" authorized key file failed (n).
[INF]: SR: Finished processing "operational" event (callback fail) with ID 1.
```

**Comment by michalvasko** [comment]
Please pull *netopeer2* `devel` and try again, the error should now be printed properly. Then you should be able to find the actual problem.

**Comment by iGovindY** [comment]
for pull netopeer2, I need to do same for all dependent libs (sysrepo, libnetconf, libyang), which will take some time for us.

Will netopeer use _operational ds config_ of `ietf-netconf-server` or always _running ds config_?

**Comment by michalvasko** [comment]
`operational` datastore should work fine. The problem in this case seems to be that some user on your system does not have the file `%HOME_DIR%/.ssh/authorized_keys` created. That is covered but my guess is that not just the file is missing but probably also some of the directories, hence the error. But I need to know some details (which directories exactly do not exist and whether it is a valid situation) to properly fix it. With my latest change, you should see the exact path that was being opened and failed.

**Comment by iGovindY** [comment]
update to latest versions will take some, I think it is planned by next week.
Once we do that, I will update you on this.

In theory, If I change operational ds config of `ietf-netconf-server` Netopeer server will start listening to config from operational datastore, please confirm yes or no.
```
<ssh>
        <tcp-server-parameters>
          <local-address>10.XX.XX.15</local-address>
          <keepalives>
            <idle-time>1</idle-time>
            <max-probes>10</max-probes>
            <probe-interval>5</probe-interval>
          </keepalives>
        </tcp-server-parameters>
````

Thanks

**Comment by michalvasko** [comment]
Hi,
please be more exact and do not mix `operational` and `config`, I do not understand what you are saying. If you change `ietf-netconf-server` `running` configuration, the server will reconfigure itself accordingly, of course. It has nothing to do with `operational`.

**Comment by michalvasko** [comment]
Fine, now it should be silently handled (if you update *netopeer2* with `devel`).
