### ISSUE TITLE
sysrepocfg reload all the modules when import a startup file

### ISSUE THREAD

**Issue by jjin62** [sysrepo/sysrepo#209]
When importing startup config, I saw the following:

sysrepocfg --import=com-att-device-internal-startup.xml --datastore=startup com-att-device-internal
[ERR] (srcfg_ly_log_cb:84) libyang: Module "module-a" in another revision already implemented.
[ERR] (srcfg_ly_log_cb:84) libyang: Module "module-a" parsing failed.
[ERR] (srcfg_ly_log_cb:84) libyang: Invalid keyword "submodule".
[ERR] (srcfg_ly_log_cb:84) libyang: Module parsing failed.
[ERR] (srcfg_ly_log_cb:84) libyang: Invalid keyword "submodule".
[ERR] (srcfg_ly_log_cb:84) libyang: Module parsing failed.
[ERR] (srcfg_ly_log_cb:84) libyang: Invalid keyword "submodule".
[ERR] (srcfg_ly_log_cb:84) libyang: Module parsing failed.
[ERR] (sr_commit:1111) Error by processing of commit request.
[ERR] (srcfg_import_datastore:663) Error returned from sr_commit: Validation of the changes failed.
Errors were encountered during importing. Cancelling the operation.

The first 8 errors are unrelated to the actual issue behind the failed import. At the moment, sysrepocfg loads all yang files in the repository, including submodules, which is not correct (and also not optimal) and libyang reports this in multiple errors.

**Comment by milanlenco** [comment]
Hi Jimmy,
the issue with extra errors is now resolved in the devel branch. If you still see some error messages when using sysrepocfg which shouldn't be there, please let me know.
Thanks,
Milan
