### ISSUE TITLE
Callback event "rpc" with ID 1 processing timed out

### ISSUE THREAD

**Issue by zyboy2000** [sysrepo/sysrepo#2090]
when I creat many list(676) config node for test , I use netconf client to get data , netconf server prints "Callback event "rpc" with ID 1 processing timed out" error,and it crashes, I modify SR_RPC_CB_TIMEOUT  30000, but the problem remains.  How to solve it,thanks!

**Comment by michalvasko** [comment]
Hi,
this is a *netopeer2* issue, you need to adjust its [timeouts](https://github.com/CESNET/netopeer2/blob/devel/CMakeLists.txt#L50).

**Comment by zyboy2000** [comment]
netopeer?or libnetconf2?   I can not find ......I find READ_INACTIVE_TIMOUT in libnetconf2 Cmakelists.txt, the default value is 20 s, it is already big number.
 Have you test large data ? Thanks

**Comment by michalvasko** [comment]
Please click the link I provided in my reply, that is what you need to adjust.
