### ISSUE TITLE
Query: establish call-home connection need check the ".ssh/authorized_keys" on netconf server side, are there any mechanisms to append the public key of call-home node automatically?

### ISSUE THREAD

**Issue by adamzyg** [sysrepo/sysrepo#2092]
The problem as described in the title, how to append the public key to the authorized_keys of netconf server side from call-home node?

**Comment by michalvasko** [comment]
It is not possible. An existing mechanism of authorized SSH keys was reused so it is assumed you will add keys there using the same mechanism. Once `ietf-netconf-server` and other connected YANG modules are finally finished and implemented in *netopeer2*, this will likely be possible.

**Comment by adamzyg** [comment]
OK, I see. thank you @michalvasko .
I think call-home node need implement a mechanism to release the key.
