### ISSUE TITLE
Performance issuses for sysrepo

### ISSUE THREAD

**Issue by zyboy2000** [sysrepo/sysrepo#2093]
I update the newest program and  test get command  for the list with one key (a total of 676) , It takes 28 seconds to get back data,  in the same test (sysrepo0.7.8), It takes more than 10 seconds ?   why is old code faster than new code ? Thanks

model name      : Intel(R) Xeon(R) CPU E5-2609 v4 @ 1.70GHz
stepping        : 1
microcode       : 0xb00002e
cpu MHz         : 1698.033
cache size      : 20480 KB
physical id     : 0
siblings        : 1
core id         : 0

**Comment by michalvasko** [comment]
Hi,
firstly, it really is possible that `<get>` was faster in the old *sysrepo* than the new one because it is now more complex (because NMDA and `operational` datastore are supported).

Still, I believe it could be easily improved because operational subscriptions are also much more complex now and allow many ways of implementing the same functionality with various performance. But you have not provided any details or code so I cannot help you this way.

Finally, we are still working on *sysrepo* and currently it is performance. Once we finish *libyang* version 2 and fully integrate it into *sysrepo*, the difference should be noticeable.

**Comment by zyboy2000** [comment]
i import  a  xml  to sysrepo(sysrepocfg --import=openconfig-platform.xml --module openconfig-platform --datastore running) . such as  (676 componet ,  name is key)  ,and get slowly.

<components xmlns="http://openconfig.net/yang/platform">
    <component>
      <name>AA</name>
      <config>
        <name>AA</name>      
      </config>
    </component>
    <component>
      <name>AB</name>
      <config>
        <name>AB</name>          
      </config>
    </component>
    <component>
      <name>AC</name>
      <config>
        <name>AC</name> 
      </config>
    </component>
    .............
    ..............
    .............
   <component>
      <name>YY</name>
      <config>
        <name>YY</name> 
      </config>
    </component>
</components> 

code
void make_componet(struct lyd_node *root, char *compname)
{
    struct lyd_node *temp,*temp2;
	char aliasname[256];
	char xpath[256];

	snprintf(xpath,sizeof(xpath),"/openconfig-platform:components/openconfig-platform:component[name='%s']",compname);

	//printf("xpath=%s\n",xpath);
	
	temp=lyd_new_path(root, NULL, xpath, NULL, 0, 0);
	temp2 = lyd_new(temp,NULL,"state");
	lyd_new_leaf(temp2,NULL,"name",compname);
	snprintf(aliasname,sizeof(aliasname),"hello%s",compname);
	lyd_new_leaf(temp2,NULL,"alias-name",aliasname);
	
}
void  testget(struct lyd_node *root)
{
   char str1;
   char str2;
   char str3[64];
   
   for(str1='A';str1<='Z';str1++)
   {
	for(str2='A';str2<='Z';str2++)
   		{
          snprintf(str3,sizeof(str3),"%c%c",str1,str2);
		  make_componet(root,str3);
   		}
   	}
}
get_test_cb(sr_session_ctx_t *session, const char *module_name, const char *xpath, const char *request_xpath,
        uint32_t request_id, struct lyd_node **parent, void *private_data)
{
    (void)session;
    (void)request_xpath;
    (void)request_id;
    (void)private_data;
	
    struct ly_ctx *ly_ctx;
	struct lyd_node *root,*component,*state,*temp,*temp2;

    printf("\n\n ========== DATA FOR \"%s\" \"%s\" REQUESTED =======================\n\n", module_name, xpath);
    ly_ctx = (struct ly_ctx *)sr_get_context(snetconfserv.sr_conn);

    *parent = lyd_new_path(NULL, ly_ctx, "/openconfig-platform:components", NULL, 0, 0);

	testget(*parent);
	
	return SR_ERR_OK;	
}

int
main(int argc, char **argv)
{
    sr_conn_ctx_t *connection = NULL;
    sr_session_ctx_t *session = NULL;
    sr_subscription_ctx_t *subscription = NULL;
    int rc = SR_ERR_OK;
    const char *mod_name, *path1,*path2;

   
    mod_name = "openconfig-platform";
    path = "/openconfig-platform:components";


    printf("Application will provide data \"%s\" of \"%s\".\n\n", path1, mod_name);

    /* turn logging on */
    sr_log_stderr(SR_LL_WRN);

    /* connect to sysrepo */
    rc = sr_connect(0, &snetconfserv.sr_conn);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }

    /* start session */
    rc = sr_session_start(snetconfserv.sr_conn, SR_DS_RUNNING, &snetconfserv.sr_sess);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }

    /* subscribe for providing the operational data */
	rc = sr_oper_get_items_subscribe(snetconfserv.sr_sess, mod_name, path, get_test_cb, NULL, SR_SUBSCR_DEFAULT, &snetconfserv.sr_data_sub);
    if (rc != SR_ERR_OK) {
		printf("rc=%d(error)\n",rc);
        goto cleanup;
    }

	rc = sr_module_change_subscribe(snetconfserv.sr_sess, mod_name, path, module_change_cb, NULL, 0, 0, &snetconfserv.sr_data_sub);
	 if (rc != SR_ERR_OK) {
	 	printf("rc=%d(error)\n",rc);
        goto cleanup;
    }
    printf("\n\n ========== LISTENING FOR REQUESTS ==========\n\n");

    /* loop until ctrl-c is pressed / SIGINT is received */
    signal(SIGINT, sigint_handler);
    signal(SIGPIPE, SIG_IGN);
    while (!exit_application) {
        sleep(1000);
    }

    printf("Application exit requested, exiting.\n");

cleanup:
    sr_disconnect(connection);
    return rc ? EXIT_FAILURE : EXIT_SUCCESS;
}

**Comment by zyboy2000** [comment]
<components xmlns="http://openconfig.net/yang/platform">
    <component>
      <name>AA</name>
      <config>
        <name>AA</name>      
      </config>
    </component>
    <component>
      <name>AB</name>
      <config>
        <name>AB</name>          
      </config>
    </component>
    <component>
      <name>AC</name>
      <config>
        <name>AC</name> 
      </config>
    </component>
    .............
    ..............
    .............
   <component>
      <name>YY</name>
      <config>
        <name>YY</name> 
      </config>
    </component>
</components>

**Comment by zyboy2000** [comment]
`<components xmlns="http://openconfig.net/yang/platform">
    <component>
      <name>AA</name>
      <config>
        <name>AA</name>      
      </config>
    </component>
    <component>
      <name>AB</name>
      <config>
        <name>AB</name>          
      </config>
    </component>
    <component>
      <name>AC</name>
      <config>
        <name>AC</name> 
      </config>
    </component>
    .............
    ..............
    .............
   <component>
      <name>YY</name>
      <config>
        <name>YY</name> 
      </config>
    </component>
</components>`

**Comment by zyboy2000** [comment]
`<components xmlns="http://openconfig.net/yang/platform">
    <component>
      <name>AA</name>
      <config>
        <name>AA</name>      
      </config>
    </component>
    <component>
      <name>AB</name>
      <config>
        <name>AB</name>          
      </config>
    </component>
    <component>
      <name>AC</name>
      <config>
        <name>AC</name> 
      </config>
    </component>
    .............
    ..............
    .............
   <component>
      <name>YY</name>
      <config>
        <name>YY</name> 
      </config>
    </component>
</components>`

After 28 seconds to get callback printf data,  printf("\n\n ========== DATA FOR \"%s\" \"%s\" REQUESTED =======================\n\n", module_name, xpath);

**Comment by michalvasko** [comment]
Okay, please try to execute `<get-data>` on `operational` instead of `<get>` and report the result. I will then try it myself if needed.

**Comment by zyboy2000** [comment]
It also take 28 seconds (by send get-data command), printf "There is no leafref "../config/name" with the value "AA", but it is not required." ,but i import xml include "AA"

[INF]: SR: Published event "rpc" "/ietf-netconf:get" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:get" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "operational" "/openconfig-platform:components" with ID 1.
[INF]: SR: Event "operational" with ID 1 succeeded.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: There is no leafref "../config/name" with the value "AA", but it is not required.
[INF]: LY: There is no leafref "../config/name" with the value "AB", but it is not required.
[INF]: LY: There is no leafref "../config/name" with the value "AC", but it is not required.

**Comment by michalvasko** [comment]
Hi,
I have tried it with your example after I did some changes so it can be compiled. Using *netopeer2-cli* I measured get
```
mono  0m0.131s
```
I do have a standard x86_64 processor but I am still pretty sure the reason for the bad performance in your case is not the code you posted so I cannot help you. However, I did try it with the latest `devel` *sysrepo*/*netopeer2* and there are some changes in *sysrepo* that may affect `operational` subscription performance quite a lot, so you may try to update it.

[test.tar.gz](https://github.com/sysrepo/sysrepo/files/5094776/test.tar.gz)

**Comment by zyboy2000** [comment]
[openconfig-platform.zip](https://github.com/sysrepo/sysrepo/files/5097349/openconfig-platform.zip)
do  you import  config data before read ? firt I import "openconfig-platform.xml" (it has large config data) ,after that , i send get command;

**Comment by zyboy2000** [comment]
or you can sr_set_item_str , config data,  and after that,  test 
`/**
 * @file sr_set_item_example.c
 * @author Michal Vasko <mvasko@cesnet.cz>
 * @brief example of an application that sets a value
 *
 * @copyright
 * Copyright (c) 2019 CESNET, z.s.p.o.
 *
 * This source code is licensed under BSD 3-Clause License (the "License").
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://opensource.org/licenses/BSD-3-Clause
 */
#define _GNU_SOURCE

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <signal.h>
#include <inttypes.h>

#include "sysrepo.h"

int
main(int argc, char **argv)
{
    sr_conn_ctx_t *connection = NULL;
    sr_session_ctx_t *session = NULL;
    int rc = SR_ERR_OK;
    const char *xpath, *value;


    /* turn logging on */
    sr_log_stderr(SR_LL_WRN);

    /* connect to sysrepo */
    rc = sr_connect(0, &connection);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }

    /* start session */
    rc = sr_session_start(connection, SR_DS_RUNNING, &session);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }
	
   char str1;
   char str2;
   char path1[256];
   char value1[256];
   
   for(str1='A';str1<='Z';str1++)
   {
	for(str2='A';str2<='Z';str2++)
   		{
          snprintf(path1,sizeof(path1),"/openconfig-platform:components/component[name='%c%c']/config/name",str1,str2);
		  snprintf(value1, sizeof(value1),"%c%c",str1,str2);
		  printf("Application will set \"%s\" to \"%s\".\n", path1, value1);
		  rc = sr_set_item_str(session, path1, value1, NULL, 0);
          if (rc != SR_ERR_OK) 
		  {
              goto cleanup;
           }
		  
   		}
   	}

    /* set the value */
  

    /* apply the change */
    rc = sr_apply_changes(session, 0, 0);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }

cleanup:
    sr_disconnect(connection);
    return rc ? EXIT_FAILURE : EXIT_SUCCESS;
}

`

**Comment by michalvasko** [comment]
Hi,
right, importing data is slower in the new *sysrepo* because of lacking *libyang* API. However, we are working on resolving these issues by moving *sysrepo* to *libyang* version 2 so please wait until then. First such *sysrepo* should be available in a few months at most.

**Comment by karthikpally** [comment]
Hi Michal,

is this issue fixed in the latest Netopeer2 versions?
  if Yes, could you please share the fixed version details?

Thank you.

Regards,
Karthik

**Comment by michalvasko** [comment]
Yes, it should be fixed and what details are you looking for exactly? It should be commit https://github.com/CESNET/netopeer2/commit/a217dc201f3f2cbb87cff3d84a0daa5767de22be.
