### ISSUE TITLE
[ERR]: Failed to update data for the new context.

### ISSUE THREAD

**Issue by kuailedeluojie-sudo** [sysrepo/sysrepo#2094]
Hi,
I use "sysrecoctl - I" oven.yang ”After that, restart the machine and run "sysrepo-plugind" to report this problem. How can I solve it?
By the way, is liboven not added to the specified path.

I follow this link.

[sysrepo:plugin example](https://netopeer.liberouter.org/doc/sysrepo/master/example.html)

**Comment by michalvasko** [comment]
Hi,
please run `sysrepo-plugind -d -v3` instead to actually see the problem, the error you provided is too generic.

**Comment by kuailedeluojie-sudo** [comment]
Hello, because of the first contact with "netoper2 server", I want to know the relationship between this software and Yang file, so as to facilitate the development of the software I want.
Now we have this problem again. I don't know how to solve it.
![image](https://user-images.githubusercontent.com/60098441/90460832-57c1f000-e137-11ea-942d-0d154ab1d219.png)

**Comment by michalvasko** [comment]
Hi,
you keep having the same problem over and over again so I do not know what else to tell you. However, I have no internal error on `main.c:718` so you must have some outdated *netopeer2* version.

**Comment by kuailedeluojie-sudo** [comment]
Hello! Because I am not familiar with the software, I used to add "EINT;" to the program, and then let it print, so as to detect its running process. Therefore, the version has not changed.

**Comment by michalvasko** [comment]
Okay, but I have replied to you at least 2 or 3 times as to what
```
[ERR]: NP: Module "ietf-netconf" feature "writable-running" not enabled in sysrepo.
```
means, I will not repeat myself more times.

**Comment by kuailedeluojie-sudo** [comment]
![image](https://user-images.githubusercontent.com/60098441/90604720-d9954480-e22f-11ea-818a-cc870a42e058.png)
Thank you for your kind reply! This is a screenshot after I run the "WR sysrepo-plugin -d -v 4" instruction, and I still don't know what the problem is, where "wr" equals "sudo"。
This is the printout of netoper2-server.

`[INF]: LY: Plugin "/opt/libyang/lib/libyang1/extensions/metadata.so" successfully loaded.
[INF]: LY: Plugin "/opt/libyang/lib/libyang1/extensions/yangdata.so" successfully loaded.
[INF]: LY: Plugin "/opt/libyang/lib/libyang1/extensions/nacm.so" successfully loaded.
[INF]: LY: Plugin "/opt/libyang/lib/libyang1/user_types/user_yang_types.so" successfully loaded.
[INF]: LY: Plugin "/opt/libyang/lib/libyang1/user_types/user_inet_types.so" successfully loaded.
[INF]: LY: Reading module "ietf-yang-metadata".
[INF]: LY: Module "ietf-yang-metadata@2016-08-05" successfully parsed as implemented.
[INF]: LY: Reading module "yang".
[INF]: LY: Resolving "yang" unresolved schema nodes and their constraints...
[INF]: LY: All "yang" schema nodes and constraints resolved.
[INF]: LY: Module "yang@2017-02-20" successfully parsed as implemented.
[INF]: LY: Reading module "ietf-inet-types".
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-inet-types" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-inet-types@2013-07-15" successfully parsed as implemented.
[INF]: LY: Reading module "ietf-yang-types".
[INF]: LY: Module "ietf-yang-types@2013-07-15" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-yang-types" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Resolving "sysrepo" unresolved schema nodes and their constraints...
[INF]: LY: All "sysrepo" schema nodes and constraints resolved.
[INF]: LY: Module "sysrepo@2020-01-15" successfully parsed as implemented.
[INF]: SR: Scheduled changes not applied because of other existing connections.
[INF]: LY: Searching for "ietf-datastores" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-datastores@2018-02-14.yang" file.
[INF]: LY: Module "ietf-datastores@2018-02-14" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-yang-library" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-yang-library@2019-01-04.yang" file.
[INF]: LY: Searching for "ietf-inet-types" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Searching for "ietf-datastores" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-datastores@2018-02-14.yang" file.
[INF]: LY: Module "ietf-yang-library@2019-01-04" successfully parsed as implemented.
[INF]: LY: Searching for "sysrepo-monitoring" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/sysrepo-monitoring@2020-04-17.yang" file.
[INF]: LY: Resolving "sysrepo-monitoring" unresolved schema nodes and their constraints...
[INF]: LY: All "sysrepo-monitoring" schema nodes and constraints resolved.
[INF]: LY: Module "sysrepo-monitoring@2020-04-17" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-netconf" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-netconf@2011-06-01.yang" file.
[INF]: LY: Module "ietf-netconf@2011-06-01" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-netconf-with-defaults" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-netconf-with-defaults@2011-06-01.yang" file.
[INF]: LY: Searching for "ietf-netconf" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-netconf@2011-06-01.yang" file.
[INF]: LY: Module "ietf-netconf-with-defaults@2011-06-01" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-netconf-notifications" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-netconf-notifications@2012-02-06.yang" file.
[INF]: LY: Resolving "ietf-netconf-notifications" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-netconf-notifications" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-netconf-notifications@2012-02-06" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-origin" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/mo/share/netconf2_new/sysrepo/build/repository/yang/ietf-origin@2018-02-14.yang" file.
[INF]: LY: Searching for "ietf-yang-metadata" in /home/mo/share/netconf2_new/sysrepo/build/repository/yang.
[INF]: LY: Resolving "ietf-origin" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-origin" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-origin@2018-02-14" successfully parsed as implemented.
[INF]: SR: Session 2 (user "root") created.
[ERR]: NP: Module "ietf-netconf" feature "writable-running" not enabled in sysrepo.
[ERR]: NP: Server init failed.
[INF]: NP: Server terminated.`

**Comment by michalvasko** [comment]
Okay, this is the last time I reply to this issue, I will completely **IGNORE** it from now on. You have not executed *netopeer2* install scripts on the system. They are executed as part of `# make install` of *netopeer2* but (in case of cross-compilation, for example) can also be executed separately and are found in https://github.com/CESNET/netopeer2/tree/master/scripts.

**Comment by kuailedeluojie-sudo** [comment]
Thank you very much for your help in my development process!!!!
