### ISSUE TITLE
Sysrepo shared memory across containers

### ISSUE THREAD

**Issue by meghna-doshi** [sysrepo/sysrepo#2096]
Hi,
We have a deployment case where we have to run the solution in a virtual environment such that:
1. netopeer2-server runs in one container
2. application (which has sysrepo library) runs in another container.

Do you foresee any issue with such a configuration, especially with respect to shared memory used between 1 and 2.
Any other limitations?

Regards,
Meghna

**Comment by michalvasko** [comment]
Hi,
since *netopeer2* and and *applications* use *sysrepo* (so shared memory) for communication, I do foresee issues with this. Specifically, it can never work unless you somehow snychronize the SHM files across the containers.

**Comment by mdoshi-com** [comment]
Hi Michal,
We have made /dev/shm common for all containers i.e all containers access the same /dev/shm.
But still we are facing some issue, when application calls subscribe:
`m_Subscribe->module_change_subscribe`

this call never returns. Dont see any logs, may be we have not enabled sysrepo logs properly. We did following to enable logs:
`log.set_syslog("ConfigMgrApp", SR_LL_DBG);`

Let me know if you can point us to some place to debug this.

Regards,
Meghna

**Comment by michalvasko** [comment]
Well, it should always return eventually as there should a timeout be used. If it does not, there is something really wrong (perhaps caused by your specific setup) and I cannot really help you. You must find the reason yourself and then maybe I can help further.

**Comment by kobi-ca** [comment]
@meghna-doshi  - did you manage to make it work? I have the same use case.
