### ISSUE TITLE
sysrepo set_item uint16 taking 65536 as 0

### ISSUE THREAD

**Issue by paddyvgc** [sysrepo/sysrepo#2100]
I have defined yang leaf of type uint16. 
when I try to set the value 65536 to the leaf usng sysrepo set_item , the value is getting set as 0.
As the range of uint16 is 0 to 65535 , I expect it should reject the value greater than 65535 but its not happening.
Please let me know is there any conversion happening internally. 

Thanks in advance

**Comment by michalvasko** [comment]
Hi,
this is a problem in your application and there is nothing *sysrepo* can do to handle it. It takes `sr_val_t` as the argument and uses `uint16` member of its value that is of type `uint16_t`. when you set `65536` into this member, there was an overflow and `0` was stored instead. *sysrepo* sees the `0` and sets it correctly. If you want the overflow to be detected, use `sr_set_item_str()`, which takes the input value in string and actually checks for similar invalid conditions.

**Comment by paddyvgc** [comment]
Thanks Michal
