### ISSUE TITLE
Event notification nested under operational data

### ISSUE THREAD

**Issue by matth65** [sysrepo/sysrepo#2101]
Hello,

I'm having an issue sending an event notification defined for a node nested under an operational data node (e.g., /ietf-interfaces/interfaces-state). When sr_event_notif_send() is called to send the event, sysrepo is reporting the error shown below. I'm not quite sure what sysrepo is expecting based on this error. I'm not using the 'push' model for operational data. Instead the application is handling the 'pull' model by subscribing to get_items for interfaces-state. Perhaps I'm building the notification incorrectly. I'm using sysrepo version v1.4.58.

[ERR]: Nested operation "state-change" data parent does not exist in the operational datastore. (path: /ietf-interfaces:interfaces-state/interface[name='test.1']/my-test-module:my-test-interface)

The YANG model is an augmentation of interfaces-state and defined as follows:
```
    augment '/if:interfaces-state/if:interface' {
        description
        "Augments interfaces-state with nodes relative to my test module.";

        container my-test-interface {
            description
            "My test state.";

            leaf state {
                type string;
                description
                "A string that represents the current state.";
            }

            notification state-change {
                description
                    "A state change notification.";
                leaf state {
                    type string;
                    description
                    "A string that represents the current state.";
                }
            }
        }
    }
```

When I query interfaces-state with `<get>`, I can see that interface 'test.1' exists. Also, `<my-test-interface>` is also returned in the `<get>` response.

```
<?xml version="1.0" encoding="utf-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="155">
  <get>
    <filter type="subtree">
      <if:interfaces-state xmlns:if="urn:ietf:params:xml:ns:yang:ietf-interfaces"/>
    </filter>
  </get>
</rpc>

<?xml version="1.0" encoding="utf-8"?>
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <interfaces-state xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
    <interface>
      <name>test.1</name>
      <type xmlns:my-test-module="urn:my:yang:my-test-module">my-test-module:my-test-interface</type>
      <oper-status>up</oper-status>
      <last-change>2020-08-18T18:53:37.690399Z</last-change>
      <phys-address>00:11:22:33:44:55</phys-address>
      <speed>10000000000</speed>
      <my-test-interface xmlns="urn:my:yang:my-test-module">
        <state>A</state>
      </my-test-interface>
    </interface>
  </interfaces-state>
</data>
```

I'm using the Python API to generate the notification as follows.

```
    sr_ctx = sr_sess.get_context()
    sr_mod = sr_ctx.get_module("ietf-interfaces")
    sr_parent = sr.Data_Node(sr_ctx, '/ietf-interfaces:interfaces-state', None, sr.LYD_ANYDATA_CONSTSTRING, 0)
    # Create a interface node
    interface_node = sr.Data_Node(sr_parent, sr_mod, "interface")
    # name
    sr.Data_Node(interface_node, sr_mod, "name", if_name)
    # type
    sr.Data_Node(interface_node, sr_mod, "type", "my-test-module:my-test-interface")
    # Insert the my-test-interface:state-change notification
    my_test_mod = sr_ctx.get_module("my-test-module")
    my_test_node = sr.Data_Node(interface_node, my_test_mod, "my-test-interface")
    # state-change
    state_change_node = sr.Data_Node(my_test_node, my_test_mod, "state-change")
    # state
    sr.Data_Node(state_change_node, my_test_mod, "state", interface['state'])
    sr_sess.event_notif_send(sr_parent)
```

I created an example YANG module and associated python handler code to reproduce the issue. I've attached the YANG and .py to to the issue.

[send_notification_issue.zip](https://github.com/sysrepo/sysrepo/files/5092348/send_notification_issue.zip)

You can use the following steps to recreate the issue:

1) Install my-test-module.yang using sysrepoctl.

2) Run the python code that listens for changes, handles operational get requests, and generates notifications.

python3 ./my_test_module.py

3) Create a test interface with 'send-notifications' set to true, which will trigger sending event notifications using sysrepo.

```
<?xml version="1.0" encoding="utf-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="34566754">
   <edit-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
      <target>
         <running/>
      </target>
      <config>
        <if:interfaces xmlns:if="urn:ietf:params:xml:ns:yang:ietf-interfaces">
          <if:interface nc:operation="merge" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
              <if:name>test.1</if:name>
              <if:type xmlns:my-ift="urn:my:yang:my-test-module">my-ift:my-test-interface</if:type>
              <my-test-interface xmlns="urn:my:yang:my-test-module">
                <send-notifications>true</send-notifications>
              </my-test-interface>
          </if:interface>
        </if:interfaces>
      </config>
   </edit-config>
</rpc>
```

Regards,
Matt

**Comment by matth65** [comment]
Note that if I move the notification outside the operational data to the root, I'm able generate the notification and the client receives it as expected.

**Modified example YANG:**
```
module my-test-module {
    yang-version 1.1;
    namespace "urn:my:yang:my-test-module";
    prefix "my-test-module";
    import ietf-interfaces {
        prefix if;
    }
    organization "My Test YANG Module.";
    contact
        "My Test YANG Module.
         ";
    description
        "My Test YANG Module.";
    revision 2020-08-18 {
        reference "My Test YANG Module.";
    }

    notification my-test-module-event {
        description
            "A state change notification.";
        leaf state {
            type string;
            description
            "A string that represents the current state.";
        }
    }
}
```

**Python code that sends the event:**

```
sr_ctx = sr_sess.get_context()
sr_mod = sr_ctx.get_module("my-test-module")
sr_parent = sr.Data_Node(sr_ctx, '/my-test-module:my-test-module-event', None, sr.LYD_ANYDATA_CONSTSTRING, 0)
# state
sr.Data_Node(sr_parent, sr_mod, "state", interface['state'])
sr_sess.event_notif_send(sr_parent)
```

**Notification received by client:**

```
<?xml version="1.0" encoding="utf-8"?>
<notification xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
  <eventTime>2020-08-18T23:41:24Z</eventTime>
  <my-test-module-event xmlns="urn:my:yang:my-test-module">
    <state>A</state>
  </my-test-module-event>
</notification>
```

Regards,
Matt

**Comment by michalvasko** [comment]
Hi Matt,
you have not really provided a fully working example that I could just execute so I am sorry, but I do not have time to play around with the Python bindings, I do not have much experience with those. However, the error refers to [this](https://tools.ietf.org/html/rfc8342#section-6.2) specification section. To check whether something exists in the operational datastore, either use NETCONF `<get-data>` on `operational` instead of `<get>` or even `sysrepocfg -X -d operational -m ietf-interfaces`.

**Comment by matth65** [comment]
Hi Michal,

I'm sorry that the python example didn't work for you. I'm not sure what is missing from my example. 

The notification is nested under a 'config = False' tree ietf-interfaces:interfaces-state, so there is no configuration in the tree - everything is config = False. My example does not push or explicitly write anything to the operational datastore. However, when I query the operational datastore, I _do_ see the `<my-test-interface>` node that the ERR is complaining about in the `<get-data>` and `sysrepocfg` response. See below. These are filled in by get_items callbacks from the my_test_module.py application.

Is sr_event_notif_send() expecting the interface-state to be 'pushed' to the operational datastore? I'm not pushing any 'config = False' data to the operational datastore. 

If sr_event_notif_send() requires data from interfaces-state, I would expect my get_items callbacks to be called to collect whatever operational data is required to send the notification. 

Here are the results from <get-data>:

```
echo -e "connect\nget-data --datastore operational\nquit" | /opt/tibit/netconf/bin/netopeer2-cli
...
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interface>
    <name>test.1</name>
    <type xmlns:my-test-module="urn:my:yang:my-test-module">my-test-module:my-test-interface</type>
    <oper-status>up</oper-status>
    <last-change>2020-08-19T12:39:16.050612Z</last-change>
    <phys-address>00:11:22:33:44:55</phys-address>
    <speed>10000000000</speed>
  </interface>
</interfaces>
<interfaces-state xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interface>
    <name>test.1</name>
    <type xmlns:my-test-module="urn:my:yang:my-test-module">my-test-module:my-test-interface</type>
    <oper-status>up</oper-status>
    <last-change>2020-08-19T12:39:16.051097Z</last-change>
    <phys-address>00:11:22:33:44:55</phys-address>
    <speed>10000000000</speed>
    <my-test-interface xmlns="urn:my:yang:my-test-module">
      <state>A</state>
    </my-test-interface>
  </interface>
</interfaces-state>
```


Here are the results sysrepocfg:

```
$ sudo /opt/tibit/netconf/bin/sysrepocfg -X -d operational -m ietf-interfaces
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interface>
    <name>test.1</name>
    <type xmlns:my-test-module="urn:my:yang:my-test-module">my-test-module:my-test-interface</type>
    <oper-status>up</oper-status>
    <last-change>2020-08-19T12:26:10.525226Z</last-change>
    <phys-address>00:11:22:33:44:55</phys-address>
    <speed>10000000000</speed>
  </interface>
</interfaces>
<interfaces-state xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interface>
    <name>test.1</name>
    <type xmlns:my-test-module="urn:my:yang:my-test-module">my-test-module:my-test-interface</type>
    <oper-status>up</oper-status>
    <last-change>2020-08-19T12:26:10.525708Z</last-change>
    <phys-address>00:11:22:33:44:55</phys-address>
    <speed>10000000000</speed>
    <my-test-interface xmlns="urn:my:yang:my-test-module">
      <state>A</state>
    </my-test-interface>
  </interface>
</interfaces-state>
```

Regards,
Matt

**Comment by michalvasko** [comment]
Maybe there is something wrong in the bindings but this is what I did.
1. Apply this small patch to *sysrepo*
```patch
diff --git a/examples/oper_data_example.c b/examples/oper_data_example.c
index 0be5241a..51008512 100644
--- a/examples/oper_data_example.c
+++ b/examples/oper_data_example.c
@@ -39,9 +39,10 @@ dp_get_items_cb(sr_session_ctx_t *session, const char *module_name, const char *
 
     printf("\n\n ========== DATA FOR \"%s\" \"%s\" REQUESTED =======================\n\n", module_name, xpath);
 
-    if (!strcmp(module_name, "examples") && !strcmp(xpath, "/examples:stats")) {
-        *parent = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(session)), "/examples:stats/counter", "852", 0, 0);
-        lyd_new_path(*parent, NULL, "/examples:stats/counter2", "1052", 0, 0);
+    if (!strcmp(module_name, "ietf-interfaces") && !strcmp(xpath, "/ietf-interfaces:interfaces-state")) {
+        *parent = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(session)), "/ietf-interfaces:interfaces-state",
+                               NULL, 0, 0);
+        lyd_new_path(*parent, NULL, "/ietf-interfaces:interfaces-state/interface[name='test.1']/oper-status", "up", 0, 0);
     }
 
     return SR_ERR_OK;
```
2. Install the modules `ietf-interfaces` and `my-test-module`.
3. Execute in order, in separate terminals
  - `examples/oper_data_example ietf-interfaces /ietf-interfaces:interfaces-state`
  - `examples/notif_subscribe_example ietf-interfaces`
  - `examples/notif_send_example "/ietf-interfaces:interfaces-state/interface[name='test.1']/my-test-module:my-test-interface/state-change"`
4. Notification was sent successfully and the subscribe application printed
```
========== NOTIFICATION "/ietf-interfaces:interfaces-state/interface[name='test.1']/my-test-module:my-test-interface/state-change" RECEIVED =======================
```

But if you have the data in the `operational` datastore (it seems you have based on the output you provided), there is not much to do wrong anymore. Also, I have used the current `devel` of *sysrepo* and it is possible there was a problem that was fixed.

**Comment by matth65** [comment]
Hi Michal,

Ok thank you for the update. I'll retry with devel version.

Thank you very much,
Matt
