### ISSUE TITLE
Unable to import modules

### ISSUE THREAD

**Issue by igortern** [sysrepo/sysrepo#2102]
Hi,
After upgrading to sysrepo 1.4.70 importing models into sysrepo repository fails. The same models bundle was imported using the previous sysrepo release without any problem. 
sysrepoctl reports error 
[ERR]: Module "bbf-l2-forwarding" was not found in sysrepo.
although  this module was imported by 1 of the previous commands.

sysrepoctl -l | grep bbf-l2-forwarding
bbf-l2-forwarding                 |            |  N    |                   |             |            |   

Attached are:
1) import log, including all commands
2) yang models

Could you advise?

Thanks,
Igor

[sysrepo_log.txt](https://github.com/sysrepo/sysrepo/files/5100102/sysrepo_log.txt)
[yang-models.tar.gz](https://github.com/sysrepo/sysrepo/files/5100103/yang-models.tar.gz)

**Comment by michalvasko** [comment]
Hi,
in the `sysrepoctl` output you see that the module has `N` flag meaning it was not installed successfully. You can learn the reason if you run `sysrepoctl -l -v3`, for example.

**Comment by igortern** [comment]
Hi,

I'm not sure how to deal with it, this problem doesn't allow me to upgrade to the latest version. 

sysrepoctl command that installed bbf-l2-forwarding.yang didn't report any errors. 

fs/bin/sysrepoctl --install yang-models/OB-BAA-standard-olt-adapter/yang/bbf-l2-forwarding.yang --search-dirs yang-models/OB-BAA-standard-olt-adapter/yang:yang-models/TR-451/standard:yang-models/TR-451/common:yang-models/TR-451/types

fs/bin/sysrepoctl --change bbf-l2-forwarding --enable-feature forwarding-databases --enable-feature shared-forwarding-databases --enable-feature mac-learning --enable-feature split-horizon-profiles
[ERR]: Module "bbf-l2-forwarding" was not found in sysrepo.

sysrepoctl -l -v3 reported some warning, but not in bbf-l2-forwarding

_it942490@igor-mint:13:43:04:~/Perforce/OLT/aspen/main$ fs/bin/sysrepoctl -l -v3
[INF]: Applying scheduled changes.
[WRN]: Cannot check leafref "/bbf-qos-traffic-mngt:tm-profiles/bbf-qos-traffic-mngt:bac-entry/bbf-qos-traffic-mngt:name" if-feature consistency because of an unresolved augment. (path: /bbf-qos-traffic-mngt:{augment}[/ietf-interfaces:interfaces/ietf-interfaces:interface])
[WRN]: Cannot check leafref "/bbf-qos-traffic-mngt:tm-profiles/bbf-qos-traffic-mngt:tc-id-2-queue-id-mapping-profile/bbf-qos-traffic-mngt:name" if-feature consistency because of an unresolved augment. (path: /bbf-qos-traffic-mngt:{augment}[/ietf-interfaces:interfaces/ietf-interfaces:interface])
[WRN]: Module "bbf-qos-traffic-mngt" parsing failed.
[WRN]: Importing "bbf-qos-traffic-mngt" module into "bbf-qos-shaping" failed.
[WRN]: Module "bbf-qos-shaping" parsing failed.
[WRN]: Installing module "bbf-qos-shaping" failed.
[WRN]: Failed to apply some changes, leaving all changes scheduled.
[INF]: Datastore copied from <startup> to <running>.
Sysrepo repository: build/host-sim-oss/fs/bin/../sysrepo_

**Comment by michalvasko** [comment]
Hi,
in any case, this is the problem that is blocking the installation of any other modules. But this cannot be because you updated *sysrepo*, it is strictly within the functionality of *libyang*. So, either you updated that and there is a regression bug or you have updated the modules and `bbf-qos-traffic-mngt` is now wrong.

**Comment by igortern** [comment]
that is correct. I updated netopeer2 to 1.1.39 and sysrepo, libyang and libnetconf2 to the versions recommended for this netopeer2 version. The yang models were not updated. I still haven't verified the error manually, but suspect that the models are correct. Those are standard models and someone would've seen the problem there.

**Comment by michalvasko** [comment]
Hi,
right, it was a regression bug, sorry. Should work correctly using the latest `devel` of *libyang*.

**Comment by igortern** [comment]
Thanks!
