### ISSUE TITLE
sr_module_change_subscribe(): Operation not authorized

### ISSUE THREAD

**Issue by nic1225** [sysrepo/sysrepo#2103]
hi.

When I tried to upgrade FRR's sysrepo to 1.4.70, Here is the code for the subscription

    static void frr_sr_subscribe_config(struct yang_module *module)
    {
    	int ret;
    	char xpath[XPATH_MAXLEN] = {0};
        
    	snprintf(xpath, sizeof(xpath), "/%s:*", module->name);
    	flog_warn(EC_LIB_LIBSYSREPO, "sr_module_change_subscribe, module: %s, xpath=%s",module->name, xpath);
        
    	ret = sr_module_change_subscribe(session, module->name, xpath, frr_sr_config_change_cb, NULL, 0, SR_SUBSCR_ENABLED, &module->sr_subscription);
    	if (ret != SR_ERR_OK)
    		flog_err(EC_LIB_LIBSYSREPO, "sr_module_change_subscribe(): %s", sr_strerror(ret));
    }

I encountered the following problems：

    2020/08/20 12:48:12 warnings: BGP: [EC 100663349] sr_module_change_subscribe, module: ctcc-bgpd, xpath=/ctcc-bgpd:*
    2020/08/20 12:48:12 errors: BGP: [EC 100663349] sr_module_change_subscribe(): Operation not authorized

I use permission 666 to install the Yang file, but after installation it shows 600

    sysrepoctl -a -i  ctcc-bgpd.yang  -p 666 -o root -g root -v2
    [root@localhost modules]# sysrepoctl -l |grep ctcc-bgpd  
    ctcc-bgpd                        | 2020-07-06 | I     | root:root    | 600         |            |

thanks
Nick

**Comment by michalvasko** [comment]
Hi Nick,
this is quite strange and definitely cannot be replicated on all systems (the permission problem). I am not even sure how to proceed, what platform are you on? The permissions are set using `chmod(2)` (`common.c:sr_chmodown()`) and an error should be handled properly.

**Comment by nic1225** [comment]
Hi Michal,

platform is  CentOS 7.5 on VirtualBox，The following is the execution environment in which I execute GDB and enter function `sr_module_change_subscribe`.  It's transferred to `sr_perm_check ` and it's coming back directly.

    (gdb) s
    sr_module_change_subscribe (session=0xcb0560, module_name=0x4cede0 "ctcc-bgpd", xpath=xpath@entry=0x7fffffffe310 "/ctcc-bgpd:*", 
        callback=callback@entry=0x7ffff4064270 <frr_sr_config_change_cb>, private_data=private_data@entry=0x0, priority=priority@entry=0, opts=opts@entry=16, 
        subscription=subscription@entry=0x7e2210) at /usr/src/debug/sysrepo-master/src/sysrepo.c:3398
    3398    {
    (gdb) n
    3407        SR_CHECK_ARG_APIRET(!session || SR_IS_EVENT_SESS(session) || !module_name || !callback
    (gdb) 
    3399        sr_error_info_t *err_info = NULL;
    (gdb) 
    3407        SR_CHECK_ARG_APIRET(!session || SR_IS_EVENT_SESS(session) || !module_name || !callback
    (gdb) 
    3410        if ((opts & SR_SUBSCR_CTX_REUSE) && !*subscription) {
    (gdb) 
    3415        conn = session->conn;
    (gdb) 
    3420        ly_mod = ly_ctx_get_module(conn->ly_ctx, module_name, NULL, 1);
    3415        conn = session->conn;
    (gdb) 
    3420        ly_mod = ly_ctx_get_module(conn->ly_ctx, module_name, NULL, 1);
    (gdb) 
    3421        if (!ly_mod) {
    (gdb) p *ly_mod
    $8 = {
      ctx = 0xb8b8e0, 
      name = 0xbb4e10 "ctcc-bgpd", 
      prefix = 0xcb15d0 "ctcc-bgp", 
      dsc = 0xcb73a0 "This module defines a model for managing FRR bgp daemon.", 
      ref = 0x0, 
      org = 0xcb1940 "Develop bgp for Free Range Routing.", 
      contact = 0xcb3cc0 "Ctcc Develop Users Alex xu.", 
      filepath = 0xcaef90 "/etc/sysrepo/yang/ctcc-bgpd@2020-07-06.yang", 
      type = 0 '\000', 
      version = 2 '\002', 
      deviated = 0 '\000', 
      disabled = 0 '\000', 
      implemented = 1 '\001', 
      latest_revision = 0 '\000', 
      padding1 = 0 '\000', 
      padding2 = "\000", 
      rev_size = 1 '\001', 
      imp_size = 2 '\002', 
      inc_size = 0 '\000', 
      ident_size = 3, 
      tpdf_size = 0, 
      features_size = 0 '\000', 
      augment_size = 0 '\000', 
      deviation_size = 0 '\000', 
      extensions_size = 0 '\000', 
      ext_size = 0 '\000', 
      rev = 0xcab0a0, 
      imp = 0xcaa880, 
      inc = 0x0, 
      tpdf = 0x0, 
      ident = 0xcab0d0, 
      features = 0x0, 
      augment = 0x0, 
      deviation = 0x0, 
      extensions = 0x0, 
      ext = 0x0, 
      data = 0xcab3c0, 
      ns = 0xca9570 "http://ctyum.com/ns/yang/bgpd"
    }
    (gdb) n
    3427        if ((err_info = sr_perm_check(module_name, (opts & SR_SUBSCR_PASSIVE) ? 0 : 1, NULL))) {
    (gdb) n
    3441            return sr_api_ret(session, err_info);
    (gdb) n
    3507    }

thanks
Nick

**Comment by michalvasko** [comment]
Hi,
okay, great that you have `gdb` available. Please execute `sysrepoctl -a -i  ctcc-bgpd.yang  -p 666 -o root -g root -v2` with `gdb` and look at the function `sr_chmodown()` and its calls of `chmod(2)`. It should change the permissions on some files so check what exactly it does (it seems it is not working). Thanks.

**Comment by nic1225** [comment]
Hi,
I tried to install Yang files directly, GDB didn't get the desired result.

    [root@localhost ~]# gdb /usr/bin/sysrepoctl
    GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-114.el7
    Copyright (C) 2013 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
    and "show warranty" for details.
    This GDB was configured as "x86_64-redhat-linux-gnu".
    For bug reporting instructions, please see:
    <http://www.gnu.org/software/gdb/bugs/>...
    Reading symbols from /usr/bin/sysrepoctl...Reading symbols from /usr/lib/debug/usr/bin/sysrepoctl.debug...done.
    done.
    (gdb) set args  -a -i ctcc-bgpd.yang  -p 666 -o root -g root -v2
    (gdb) b sr_chmodown
    Function "sr_chmodown" not defined.
    Make breakpoint pending on future shared library load? (y or [n]) y
    Breakpoint 1 (sr_chmodown) pending.
    (gdb) run
    Starting program: /usr/bin/sysrepoctl -a -i ctcc-bgpd.yang  -p 666 -o root -g root -v2
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib64/libthread_db.so.1".
    sysrepoctl error: Cannot apply changes because of existing connections
    [Inferior 1 (process 1403) exited with code 01]
    Missing separate debuginfos, use: debuginfo-install glibc-2.17-222.el7.x86_64 pcre-8.32-17.el7.x86_64
    (gdb) 

After trying the above operation, print   `sysrepoctl error: Cannot apply changes because of existing connections`, and in view `sysrepoctl -l`, the display is as follows with Flags N

    [root@localhost ~]# sysrepoctl -l | grep bgp
    ctcc-bgpd                        |            |  N    |              |             |            |    


thanks
Nick

**Comment by michalvasko** [comment]
Hi,
well, you need to not have any *sysrepo* applications running when installing new modules. So terminate them all (including *netopeer2*) and try again.

**Comment by nic1225** [comment]
Hi,
I think sysrecoctl understands - P 666 as octal

    [root@localhost ~]# ll /etc/sysrepo/data/ | grep bgp
    -rw-rw-rw- 1 root root       0 Aug 19 07:33 ctcc-bgpd.persist
    -rw-rw-rw- 1 root root       0 Aug 19 07:33 ctcc-bgpd.running
    [root@localhost ~]# gdb /usr/bin/sysrepoctl
    GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-114.el7
    Copyright (C) 2013 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
    and "show warranty" for details.
    This GDB was configured as "x86_64-redhat-linux-gnu".
    For bug reporting instructions, please see:
    <http://www.gnu.org/software/gdb/bugs/>...
    Reading symbols from /usr/bin/sysrepoctl...Reading symbols from /usr/lib/debug/usr/bin/sysrepoctl.debug...done.
    done.
    (gdb) set args  -a -i ctcc-bgpd.yang  -p 666 -o root -g root -v2
    (gdb) b sr_chmodown
    Function "sr_chmodown" not defined.
    Make breakpoint pending on future shared library load? (y or [n]) y
    Breakpoint 1 (sr_chmodown) pending.
    (gdb) run
    Starting program: /usr/bin/sysrepoctl -a -i ctcc-bgpd.yang  -p 666 -o root -g root -v2
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib64/libthread_db.so.1".
    
    Breakpoint 1, sr_chmodown (path=0x60a5b0 "/etc/sysrepo/data/ctcc-bgpd.startup", owner=owner@entry=0x7fffffffe864 "root", 
        group=group@entry=0x7fffffffe86c "root", perm=perm@entry=438) at /usr/src/debug/sysrepo-master/src/common.c:1837
    1837    {
    Missing separate debuginfos, use: debuginfo-install glibc-2.17-222.el7.x86_64 pcre-8.32-17.el7.x86_64
    (gdb) p perm
    $1 = 438
    (gdb) n
    1845        if ((int)perm != -1) {
    (gdb) 
    1837    {
    (gdb) 
    1838        sr_error_info_t *err_info = NULL;
    (gdb) 
    1840        uid_t uid = -1;
    (gdb) 
    1841        gid_t gid = -1;
    (gdb) 
    1845        if ((int)perm != -1) {
    (gdb) 
    1846            if (perm > 00777) {
    (gdb) 
    1849            } else if (perm & 00111) {
    (gdb) 
    1856        if (owner && (err_info = sr_get_pwd(&uid, (char **)&owner))) {
    (gdb) 
    1861        if (group && (err_info = sr_get_grp(&gid, (char **)&group))) {
    (gdb) 
    1866        if (chown(path, uid, gid) == -1) {
    (gdb) 
    1877        if (((int)perm != -1) && (chmod(path, perm) == -1)) {
    (gdb) 
    1887        return NULL;
    (gdb) p path
    $2 = 0x60a5b0 "/etc/sysrepo/data/ctcc-bgpd.startup"
    (gdb) p perm
    $3 = 438
    (gdb) 

thanks
Nick

**Comment by michalvasko** [comment]
Hi Nick,
of course, the `mode` should be in octal if you look at `chmod(2)`. Bear in mind that this is the first issue with these permissions so it is unlikely the problem would be this basic (and generic).

**Comment by nic1225** [comment]
Hi Michal
I found that FRR was not running as root, which caused the problem. another problem was found after the modification.
When the database changes, the callback function `frr_sr_config_change_cb `will not be executed, Here is the code


    static int frr_sr_config_change_cb(sr_session_ctx_t *session, const char *module_name, const char *xpath, sr_event_t sr_ev, uint32_t request_id, void *private_data)
    {
        flog_warn(EC_LIB_LIBSYSREPO, "frr_sr_config_change_cb, module: %s, xpath=%s,sr_ev=%d",module_name, xpath, sr_ev);
        ... ...
    }
    
    
    static void frr_sr_subscribe_config(struct yang_module *module)
    {
    	int ret;
    	char xpath[XPATH_MAXLEN] = {0};
        
    	snprintf(xpath, sizeof(xpath), "/%s:*//.", module->name);
    	flog_warn(EC_LIB_LIBSYSREPO, "sr_module_change_subscribe, module: %s, xpath=%s",module->name, xpath);

    	ret = sr_module_change_subscribe(session, module->name, xpath, frr_sr_config_change_cb, NULL, 0, SR_SUBSCR_ENABLED,	&module->sr_subscription);
    }

Only when the FRR process starts, the callback has been executed twice

	2020/08/26 17:16:11 warnings: BGP: [EC 100663349] sr_module_change_subscribe, module: ctcc-bgpd, xpath=/ctcc-bgpd:*//.
	2020/08/26 17:16:11 warnings: BGP: [EC 100663349] frr_sr_config_change_cb, module: ctcc-bgpd, xpath=/ctcc-bgpd:*//.,sr_ev=4
	2020/08/26 17:16:11 warnings: BGP: [EC 100663349] frr_sr_config_change_cb, module: ctcc-bgpd, xpath=/ctcc-bgpd:*//.,sr_ev=2

by netopeer2-cli , I can see that the configuration has been issued, but it has not been configured to FRR by callback

    > get --filter-xpath /ctcc-bgpd:*
    DATA
    <bgpd xmlns="http://ctyum.com/ns/yang/bgpd">
      <bgp>
        <local-as>200</local-as>
        <vrf>24</vrf>
        <route-id>75.39.24.33</route-id>
        <neighbors>
          <neighbor>
            <remote-address>100.43.23.34</remote-address>
            <remote-as>200</remote-as>
            <ebgp-multihop>5</ebgp-multihop>
            <afi-safis>
              <afi-safi>
                <afi-safi-name>ipv4-unicast</afi-safi-name>
                <ipv4-unicast>
                  <route-reflector-client>true</route-reflector-client>
                  <next-hop-force>true</next-hop-force>
                  <next-hop-self>false</next-hop-self>
                </ipv4-unicast>
              </afi-safi>
            </afi-safis>
          </neighbor>
        </neighbors>
        <ipv4-unicast>
          <network>10.0.0.0/16</network>
          <network>20.0.0.0/24</network>
        </ipv4-unicast>
      </bgp>
    </bgpd>

by gdb  I found thread sr_shmsub_listen_thread was not generated，But the function call is normal，`sr_module_change_subscribe `-> `sr_subs_new`
