### ISSUE TITLE
Cannot get data from Python operational data provider

### ISSUE THREAD

**Issue by jctransition** [sysrepo/sysrepo#2107]
Hello,

I am using SWIG python bindings have been unable to provide operational data from a callback.  I have tried many of the available ways to create or insert a Data_Node for the container identified in `path` and for each of the leaf nodes in that container.  Those steps appear to work, and the resulting subtree looks correct and validates successfully.  After calling `validate()`, my callback returns `sr.SR_ERR_OK`.  But then I always get a libyang error: `libyang[0]: Invalid arguments (lyd_dup_to_ctx())` and the client receives either no data or an empty set.

I have studied Sysrepo and Libyang issues for anything relevant but still have not figured out what is wrong.  I would appreciate any help you can provide.

* sysrepocfg - sysrepo configuration manipulation tool, compiled with libsysrepo v1.4.2 (SO v5.0.2)
* yanglint SO 1.6.7

---

I am able to set and get config data.  For example, here is a dump of data I set in `ietf-system:system`:

```pycon
$ sudo sysrepocfg -X -f json -m ietf-system
{
  "ietf-system:system": {
    "hostname": "mysystem",
    "location": "",
    "contact": ""
  }
}
```

But I cannot get operational data from that same module, even though my data provider is running and seems to set a valid subtree:

```pycon
$ sudo sysrepocfg -X -f json -d operational -m ietf-system
{

}
```

Here is my standalone python module for the `/ietf-system:system-state` operational data provider (callback and subscription).  (I've omitted most LOGGER statements omitted for brevity.)  It follows the python operational data example very closely.  I have also tried many variants, and the result is always the same.

```python3
$ cat system_state_data_provider.py 
#!/usr/bin/python

import logging

from netconf.sysrepo.build.bindings.python import sysrepo as sr
from netconf.libyang.build.swig.python import yang


LOG_FMT = (
    '[%(asctime)s] %(levelname)s [%(name)s.%(funcName)s:%(lineno)d -- %(threadName)s] %(message)s')
logging.basicConfig(format=LOG_FMT, level=logging.INFO)
LOGGER = logging.getLogger('SYSTEM_STATE_DATA')

SYS_STATE_MODULE = 'ietf-system'
SYS_STATE_SUBTREE = '/ietf-system:system-state'


def system_state_oper_subtree_cb(session, module_name, path, request_path, request_id, parent,
                                 private_data):
    """ Operational data provider callback for ietf-system:system-state subtree. """

    status = sr.SR_ERR_INTERNAL

    try:
        ctx = session.get_context()
        mod = ctx.get_module(module_name)

        state_node = sr.Data_Node(parent, mod, 'system-state')
        plat_node = sr.Data_Node(state_node, mod, 'platform')
        os_node = sr.Data_Node(plat_node, mod, 'os-name', 'OpenWRT')
        os_rls_node = sr.Data_Node(plat_node, mod, 'os-release', '19.07')
        os_ver_node = sr.Data_Node(plat_node, mod, 'os-version', 'v19.07.03')
        mach_node = sr.Data_Node(plat_node, mod, 'machine', 'ARM')

        # Shows expected subtree as set above.
        LOGGER.info('state_node {} = \n{}'.format(
            state_node, state_node.print_mem(yang.LYD_JSON, 0x27)))

        # Shows parent is still an empty container.
        LOGGER.info('parent {} = \n{}'.format(
            parent, parent.print_mem(yang.LYD_JSON, 0x27)))

        validate_opts = yang.LYD_OPT_DATA_NO_YANGLIB | yang.LYD_OPT_NOSIBLINGS
        result = parent.validate(validate_opts, state_node)
        # result = state_node.validate(validate_opts, ctx)
        LOGGER.info('validation returned: {}'.format(result))

        if result == 0:
            status = sr.SR_ERR_OK

    except Exception as excp:  # pylint: disable=general_except
        print(excp)

    finally:
        return status


def sys_state_subscribe(subscr: sr.Subscribe):
    """
    Subscribe to sysrepo in order to bind the system-state operational data callback method.
    """
    opts = sr.SR_SUBSCR_CTX_REUSE
    subscr.oper_get_items_subscribe(SYS_STATE_MODULE, SYS_STATE_SUBTREE,
                                    system_state_oper_subtree_cb, None, opts)


conn = sr.Connection(sr.SR_CONN_DEFAULT)
sess = sr.Session(conn)
sess.session_switch_ds(sr.SR_DS_OPERATIONAL)
subscr = sr.Subscribe(sess)

sys_state_subscribe(subscr)

sr.global_loop()

subscr.unsubscribe()
sess.session_stop()
```

And here is the log trace produced by the data provider:

```pycon
$ python3 -u -m system_state_data_provider
[2020-08-26 15:47:34,702] INFO [SYSTEM_STATE_DATA.sys_state_subscribe:85 -- MainThread] Subscribed system-state operational callback.
[2020-08-26 15:47:53,466] INFO [SYSTEM_STATE_DATA.system_state_oper_subtree_cb:21 -- Dummy-1] parent IN: <netconf.libyang.build.swig.python.yang.Data_Node; proxy of <Swig Object of type 'std::shared_ptr< libyang::Data_Node > *' at 0x7fdfa3087600> >
[2020-08-26 15:47:53,466] INFO [SYSTEM_STATE_DATA.system_state_oper_subtree_cb:22 -- Dummy-1] path: /ietf-system:system-state, request_path: /ietf-system:*
[2020-08-26 15:47:53,466] INFO [SYSTEM_STATE_DATA.system_state_oper_subtree_cb:30 -- Dummy-1] Using datastore: 3
[2020-08-26 15:47:53,466] INFO [SYSTEM_STATE_DATA.system_state_oper_subtree_cb:31 -- Dummy-1] Module ietf-system is implemented: 1
[2020-08-26 15:47:53,467] INFO [SYSTEM_STATE_DATA.system_state_oper_subtree_cb:36 -- Dummy-1] Added: <netconf.sysrepo.build.bindings.python.sysrepo.Data_Node; proxy of <Swig Object of type 'std::shared_ptr< libyang::Data_Node > *' at 0x7fdfa3096360> > with path: /ietf-system:system-state
[2020-08-26 15:47:53,467] INFO [SYSTEM_STATE_DATA.system_state_oper_subtree_cb:39 -- Dummy-1] Added: /ietf-system:system-state/platform
[2020-08-26 15:47:53,467] INFO [SYSTEM_STATE_DATA.system_state_oper_subtree_cb:42 -- Dummy-1] Added: /ietf-system:system-state/platform/os-name
[2020-08-26 15:47:53,467] INFO [SYSTEM_STATE_DATA.system_state_oper_subtree_cb:45 -- Dummy-1] Added: /ietf-system:system-state/platform/os-release
[2020-08-26 15:47:53,467] INFO [SYSTEM_STATE_DATA.system_state_oper_subtree_cb:48 -- Dummy-1] Added: /ietf-system:system-state/platform/os-version
[2020-08-26 15:47:53,467] INFO [SYSTEM_STATE_DATA.system_state_oper_subtree_cb:51 -- Dummy-1] Added: /ietf-system:system-state/platform/machine

[2020-08-26 15:47:53,467] INFO [SYSTEM_STATE_DATA.system_state_oper_subtree_cb:55 -- Dummy-1] state_node <netconf.sysrepo.build.bindings.python.sysrepo.Data_Node; proxy of <Swig Object of type 'std::shared_ptr< libyang::Data_Node > *' at 0x7fdfa3096360> > = 
{
  "ietf-system:system-state": {
    "platform": {
      "os-name": "OpenWRT",
      "os-release": "19.07",
      "os-version": "v19.07.03",
      "machine": "ARM"
    }
  }
}

[2020-08-26 15:47:53,467] INFO [SYSTEM_STATE_DATA.system_state_oper_subtree_cb:59 -- Dummy-1] parent <netconf.libyang.build.swig.python.yang.Data_Node; proxy of <Swig Object of type 'std::shared_ptr< libyang::Data_Node > *' at 0x7fdfa3087600> > = 
{
}

[2020-08-26 15:47:53,467] INFO [SYSTEM_STATE_DATA.system_state_oper_subtree_cb:63 -- Dummy-1] validation returned: 0
[2020-08-26 15:47:53,467] INFO [SYSTEM_STATE_DATA.system_state_oper_subtree_cb:73 -- Dummy-1] Returning status: 0
libyang[0]: Invalid arguments (lyd_dup_to_ctx()).
```

I have tried reassigning `parent` to the newly created and populated container node, but still get the same result.  (Not sure if parent is mutable.)

I am able to get operational data from `ietf-netconf-monitoring`, using the built-in data provider, `netconf_monitoring.c`:

```pycon
$ sudo sysrepocfg -X -f json -d operational
{
  "ietf-netconf-monitoring:netconf-state": {
    "statistics": {
      "in-bad-hellos": 0,
      "in-sessions": 0,
      "dropped-sessions": 0,
      "in-rpcs": 0,
      "in-bad-rpcs": 0,
      "out-rpc-errors": 0,
      "out-notifications": 0
    }
  }
}
```

So, that tells me operational flows are working, and that my problem is either in the python bindings or in my data provider code.

As already mentioned, I have studied Sysrepo and Libyang issues for anything relevant but still have not figured out what is wrong.  I would appreciate any help you can provide!

Regards,
John

**Comment by rjarry** [comment]
Hi John,

I don't know if the SWIG bindings are actively maintained.

Maybe you could try to use the new CFFI bindings: https://github.com/sysrepo/sysrepo-python which I know are working properly. I am aware that it is a completely different API, though.

Let me know if it addresses your problem.

**Comment by jctransition** [comment]
Thanks.  I was aware of the new approach, but didn't know if the new CFFI bindings were ready to use yet.  I will study that repository and see what I can do.

Regards,
John

**Comment by michalvasko** [comment]
Hi John,
firstly, you should definitely update *sysrepo* (and *libyang*) to the latest release, the version you are using is quite old and there were many issues fixed since than.

**Comment by jctransition** [comment]
Thanks Michal.  It is a challenge when upgrading libraries and packages to find newer versions that are compatible with our OpenWRT target.  The effort often grows beyond just the few packages that we actually want to upgrade.

Meanwhile, I have tested the libyang pull request by @johnbeckettn2e (https://github.com/CESNET/libyang/pull/1182 ), which adds the missing `Data_Node.reset` method, and added a call to that method on the parent node in my operational data callback.  That solved my problem.

What threw me off is there are two callbacks in the python operational data example.  cb1 is subscribed and calls `parent. reset()`, which doesn't work without the new patch.  cb2 is simpler, but not subscribed.  It led me to think that the `reset()` wasn't needed.  Now I know it is.

**Comment by michalvasko** [comment]
Glad you fixed the problem. And I see now that you are on OpenWRT. While I understand it is much more difficult to update versions there, you must also understand that I am not able to provide relevant support unless you are using the latest versions.
