### ISSUE TITLE
file descriptor sr_evpipe disappear

### ISSUE THREAD

**Issue by nic1225** [sysrepo/sysrepo#2113]
hi,

When debugging [FRR ](https://github.com/FRRouting/frr/blob/master/lib/northbound_sysrepo.c)with the latest version of sysrepo, I encountered a situation where sr_evpipe2 disappeared.FRR uses its own thread to rotate changes in sysrepo. The subscription code is as follows:

    static void frr_sr_subscribe_config(struct yang_module *module)
    {
    	int ret;
    
    	ret = sr_module_change_subscribe(
    		session, module->name, NULL, frr_sr_config_change_cb, NULL, 0,
    		SR_SUBSCR_DEFAULT | SR_SUBSCR_ENABLED | SR_SUBSCR_NO_THREAD,
    		&module->sr_subscription);
        ... ...
    }

The situation of sr_evpipe after subscription is as follows，sr_evpipe1  belongs to sysrepo-plugind， sr_evpipe2  belongs to frr(bgpd)， 

    [root@localhost ~]# cd /etc/sysrepo/
    [root@localhost sysrepo]# ll
    total 20
    drwxrwxrwx 3 root root 8192 Aug 28 14:44 data
    drwxr-xr-x 2 root root 4096 Aug 28 03:15 initdata
    prw--w--w- 1 root root    0 Aug 31 01:18 sr_evpipe1
    prw--w--w- 1 frr  frr     0 Aug 31 01:18 sr_evpipe2
    -rw-rw-rw- 1 root root    0 Aug 28 11:02 sr_main_lock
    drwxrwxrwx 2 root root 4096 Aug 28 14:44 yang
    
    [root@localhost sysrepo]# lsof sr_evpipe1
    COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
    sysrepo-p 1170 root    8u  FIFO  253,0      0t0 33598353 sr_evpipe1
    [root@localhost sysrepo]# 
    [root@localhost sysrepo]# lsof sr_evpipe2
    COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
    bgpd    1295  frr   14u  FIFO  253,0      0t0 33598356 sr_evpipe2
    [root@localhost sysrepo]# 

Use the following command to do any operation on the FRR module，the configuration can be return successfully,  but its FD sr_evpipe2 will disappear, also /dev/shm/srsub_ctcc-bgpd.running.

    sysrepocfg --edit=vi --lock -d running -f xml  -m ctcc-bgpd
      
    <bgpd xmlns="http://ctyum.com/ns/yang/bgpd">
      <bgp>
        <local-as>200</local-as>
        <vrf>24</vrf>
        <route-id>75.39.24.33</route-id>
    
        <ipv4-unicast>
          <network>10.0.0.0/16</network>
          <network>20.0.0.0/24</network>
        </ipv4-unicast>
      </bgp>
    </bgpd>   

The results are as follows

    [root@localhost sysrepo]# ll
    total 20
    drwxrwxrwx 3 root root 8192 Aug 28 14:44 data
    drwxr-xr-x 2 root root 4096 Aug 28 03:15 initdata
    prw--w--w- 1 root root    0 Aug 31 01:18 sr_evpipe1
    -rw-rw-rw- 1 root root    0 Aug 28 11:02 sr_main_lock
    drwxrwxrwx 2 root root 4096 Aug 28 14:44 yang
    [root@localhost sysrepo]# pidof bgpd
    1293
    [root@localhost sysrepo]# ll /proc/1293/fd
    total 0
    lr-x------ 1 root root 64 Aug 31 09:22 0 -> /dev/null
    lr-x------ 1 root root 64 Aug 31 09:22 1 -> /dev/null
    l-wx------ 1 root root 64 Aug 31 09:22 10 -> pipe:[19068]
    lrwx------ 1 root root 64 Aug 31 09:22 11 -> /etc/sysrepo/sr_main_lock
    lrwx------ 1 root root 64 Aug 31 09:22 12 -> /dev/shm/sr_main
    lrwx------ 1 root root 64 Aug 31 09:22 13 -> /dev/shm/sr_ext
    lrwx------ 1 root root 64 Aug 31 09:22 14 -> /etc/sysrepo/sr_evpipe2 (deleted)                <---------------here
    lrwx------ 1 root root 64 Aug 31 09:22 15 -> /dev/shm/srsub_ctcc-bgpd.running (deleted)       <---------------here
    lrwx------ 1 root root 64 Aug 31 09:22 16 -> /run/frr/bgpd.pid
    lrwx------ 1 root root 64 Aug 31 09:22 17 -> socket:[19106]
    lr-x------ 1 root root 64 Aug 31 09:22 18 -> pipe:[19098]
    l-wx------ 1 root root 64 Aug 31 09:22 19 -> pipe:[19098]
    lr-x------ 1 root root 64 Aug 31 09:22 2 -> /dev/null
    lrwx------ 1 root root 64 Aug 31 09:22 20 -> socket:[19102]
    lrwx------ 1 root root 64 Aug 31 09:22 21 -> socket:[19103]
    lrwx------ 1 root root 64 Aug 31 09:22 22 -> socket:[19104]
    lrwx------ 1 root root 64 Aug 31 09:22 3 -> socket:[19062]
    lr-x------ 1 root root 64 Aug 31 09:22 4 -> pipe:[19063]
    l-wx------ 1 root root 64 Aug 31 09:22 5 -> pipe:[19063]
    lr-x------ 1 root root 64 Aug 31 09:22 6 -> net:[4026531956]
    lr-x------ 1 root root 64 Aug 31 09:22 7 -> pipe:[19067]
    l-wx------ 1 root root 64 Aug 31 09:22 8 -> pipe:[19067]
    lr-x------ 1 root root 64 Aug 31 09:22 9 -> pipe:[19068]
    [root@localhost sysrepo]# 

Why did sr_evpipe2 disappear, or how can I know where it disappeared

thanks
Nick

**Comment by michalvasko** [comment]
Hi Nick,
I cannot help you based on this information, I do not know why would both the FD and running file disappear. Can you maybe provide verbose output of *sysrepo* for the FRR process? Also, what does *sysrepo-plugind* have to do with this problem, is it handling some other plugins/data?

**Comment by nic1225** [comment]
hi,Michal
I added a log to FRR, and sysrepo logs are printed only when the frr process is started, as shown below. When the configuration is issued and the FD is lost, there is no log output

    call sr_connect(SR_CONN_DEFAULT, &connection);
        Aug 31 07:10:21 localhost.localdomain bgpd[1329]: Scheduled changes not applied because of other existing connections.
        Aug 31 07:10:21 localhost.localdomain bgpd[1329]: Failed to check existence of process with PID 1169 (Operation not permitted).
		
	call sr_session_start(connection, SR_DS_RUNNING, &session);
        Aug 31 07:10:21 localhost.localdomain bgpd[1329]: Session 13 (user "frr") created.

	call  sr_module_change_subscribe
        Aug 31 07:10:21 localhost.localdomain bgpd[1329]: Triggering "ctcc-bgpd" "enabled" event on enabled data.
        Aug 31 07:10:21 localhost.localdomain bgpd[1329]: Triggering "ctcc-bgpd" "done" event on enabled data.
        Aug 31 07:10:21 localhost.localdomain bgpd[1329]: Session 14 (user "frr") created.
        Aug 31 07:10:21 localhost.localdomain bgpd[1329]: No datastore changes to apply.
        Aug 31 07:10:21 localhost.localdomain bgpd[1329]: Failed to check existence of process with PID 1169 (Operation not permitted).
   
 sysrepo-plugind and FRR happen to be used in both our projects, and there was no business connection between them before. But what I don't understand is that from the printed log, why do it check sysrepo-plugind when starting FRR

thanks
Nick

**Comment by nic1225** [comment]
hi,Michal
The following is the log output when FRR is only started. FD will disappear after configuration, and there will be no sysrepo log when it disappears

    Aug 31 11:19:34 localhost.localdomain bgpd[1215]: Applying scheduled changes.
    Aug 31 11:19:34 localhost.localdomain bgpd[1215]: No scheduled changes.
    Aug 31 11:19:34 localhost.localdomain bgpd[1215]: Datastore copied from <startup> to <running>.

    Aug 31 11:19:34 localhost.localdomain bgpd[1215]: Session 1 (user "root") created.

    Aug 31 11:19:34 localhost.localdomain bgpd[1215]: Triggering "ctcc-bgpd" "enabled" event on enabled data.
    Aug 31 11:19:34 localhost.localdomain bgpd[1215]: Triggering "ctcc-bgpd" "done" event on enabled data.
    Aug 31 11:19:34 localhost.localdomain bgpd[1215]: Session 2 (user "root") created.
    Aug 31 11:19:34 localhost.localdomain bgpd[1215]: No datastore changes to apply.

thanks
Nick

**Comment by michalvasko** [comment]
Hi Nick,
I have briefly looked into the code and `running` file is removed only for YANG modules that were uninstalled, in no other case. As for the pipes, they are removed when the subscription that created it is stopped. I am not sure how to help you exactly but I would suspect the cause is outside of *sysrepo*.

Lastly, the output
```
Aug 31 07:10:21 localhost.localdomain bgpd[1329]: Failed to check existence of process with PID 1169 (Operation not permitted).
```
is seen because every new connection always check the existence of the processes of all the other connections for recovery. In case it is not authorized to do so, it assumes the process still exists so you can ignore these.

**Comment by nic1225** [comment]
hi,Michal

What is the operation of the subscription you mentioned above stopped. I printed the sr_subscription variable in GDB before and after the pipe fd disappeared and found no change. Is there any way to know where pipe fd disappeared so that I can find the problem through the call stack of GDB.

    (gdb) p*sr_subscription
    $4 = {
      conn = 0x24574d0, 
      evpipe_num = 2, 
      evpipe = 14, 
      thread_running = 0, 
      tid = 0, 
      subs_lock = {
        __data = {
          __lock = 0, 
          __count = 0, 
          __owner = 0, 
          __nusers = 0, 
          __kind = 0, 
          __spins = 0, 
          __elision = 0, 
          __list = {
            __prev = 0x0, 
            __next = 0x0
          }
        }, 
        __size = '\000' <repeats 39 times>, 
        __align = 0
      }, 
      change_subs = 0x264e0e0, 
      change_sub_count = 1, 
      oper_subs = 0x0, 
      oper_sub_count = 0, 
      notif_subs = 0x0, 
      notif_sub_count = 0, 
      rpc_subs = 0x0, 
      rpc_sub_count = 0
    }

thanks
Nick

**Comment by nic1225** [comment]
hi,Michal
Today, I tried to leave only one subscription, delete all other operations, and still use sysrepo's own callback thread. The relevant codes are as follows

    static int frr_sr_config_change_cb(sr_session_ctx_t *session, const char *module_name, const char *xpath, sr_event_t sr_ev, uint32_t request_id, void *private_data)
    {
    	return SR_ERR_OK;
    }
    static void frr_sr_subscribe_config(struct yang_module *module)
    {
    	int ret;
    	char xpath[XPATH_MAXLEN] = {0};
        
    	snprintf(xpath, sizeof(xpath), "/%s:*//.", module->name);
    
    	ret = sr_module_change_subscribe(session, module->name, xpath, frr_sr_config_change_cb, NULL, 0, SR_SUBSCR_ENABLED,&module->sr_subscription);
    }
    
    static int frr_sr_init(void)
    {
    	struct yang_module *module = &yang_modules;
    	int ret;
        
    	ret = sr_connect(SR_CONN_DEFAULT, &connection);
    	ret = sr_session_start(connection, SR_DS_RUNNING, &session);
    	frr_sr_subscribe_config(module);
	return 0;
    }

Then operate the startup database with the following command, and the pipe still disappears

     sysrepocfg --edit=vi  -d startup -f xml  -m ctcc-bgpd

The sysrepo module is loaded into FRR as a dynamic library.


thanks
Nick

**Comment by michalvasko** [comment]
Since I have no way of reproducing this, I do not think I can help much. If you think `sysrepocfg` is to blame, you can try to run it with `strace(1)` and you should see it when the pipe is being deleted.

**Comment by nic1225** [comment]
hi,Michal
Using the following command, I get the location of pipe deletion. You can help me to have a look，Would you help to see the cause of the problem

    strace -tt -f  -o /root/strace2.log sysrepocfg --edit=vi --lock -d running -f xml  -m ctcc-bgpd

In line 5027, you can see the deletion of the pipe

    1565  01:51:29.188752 unlink("/dev/shm/srsub_ctcc-bgpd.running") = 0
    1565  01:51:29.188792 unlink("/etc/sysrepo/sr_evpipe2") = 0

starce info as follow:
[strace2.log](https://github.com/sysrepo/sysrepo/files/5165721/strace2.log)

**Comment by nic1225** [comment]
hi,Michal

When configuring sysrepo, it is necessary to verify whether the subscribed thread is still alive. If the thread does not exist, the pipe FIFO file will be deleted. Therefore, it is necessary to ensure that the subscription operation is performed in the survivable thread. the following is the system call procedure to execute _sysrepocfg_ :



    1565  01:51:29.188460 kill(1171, 0)     = 0
    1565  01:51:29.188487 kill(1548, 0)     = -1 ESRCH (No such process)
    1565  01:51:29.188554 open("/dev/shm/sr_ctcc-bgpd.operational", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = 6
    1565  01:51:29.188591 fstat(6, {st_mode=S_IFREG|0666, st_size=7, ...}) = 0
    1565  01:51:29.188622 mmap(NULL, 8, PROT_READ|PROT_WRITE, MAP_PRIVATE, 6, 0) = 0x7f0c58f5f000
    1565  01:51:29.188683 munmap(0x7f0c58f5f000, 8) = 0
    1565  01:51:29.188719 close(6)          = 0
    1565  01:51:29.188752 unlink("/dev/shm/srsub_ctcc-bgpd.running") = 0
    1565  01:51:29.188792 unlink("/etc/sysrepo/sr_evpipe2") = 0

thanks
Nick
