### ISSUE TITLE
How to sync data to sysrepo running ?

### ISSUE THREAD

**Issue by qjwu888** [sysrepo/sysrepo#2120]
Hi Michal,
Now my device work fine with callhome mode.
ODL controller changes sysrepo running, callback exec to set device.

But another question, if my device use sysrepo-plugind to load every module, and init data to running ， 
 enable sr_module_change_subscribe 、sr_oper_get_items_subscribe to wait setting ,and getting.
 Then  if someone don't use ODL controller, and use other cmdline or other Web UI to set this device, how to sync these data to sysrepo running? ODL controller don't know thiese data.

Could you give me some idea, Thansk!

**Comment by michalvasko** [comment]
Hi,
there is no clean and simple solution to the problem of having the same configuration data in several places currently. We have it planned and it should be implemented in Q4 if everything goes well.

**Comment by ydong08** [comment]
Hi Michal,
this issue(#2120) is marked 'completed',however,i not find any modification about that after checking both master and devel branches.Could you give me any hints? Thank you!

**Comment by michalvasko** [comment]
I closed it mostly because of long inactivity but the solution I talked about is implemented. However, it entails writing your own custom datastore plugin that would in effect work directly with data stored wherever the CMD line stores them, the standard storage. That way you will not have to worry about any data inconsistency because they would always be stored in one place only.

**Comment by ydong08** [comment]
Thanks for your answer. 
I am confused with that cmdline may works on redies, but sysrepo works on libyang LYB files, datastore medium are different, how to ensure my own custom datastore sysrepo plugin work in one place?
Could you help to clarify the details? is there related example code in sysrepo/tests or sysrepo/examples?

**Comment by michalvasko** [comment]
> but sysrepo works on libyang LYB files

The point of the custom datastore plugin is to allow to change how exactly are the data stored meaning there will be no LYB files. There is some basic information in the [docs](https://netopeer.liberouter.org/doc/sysrepo/master/html/sr_plugins.html) and as an example you can look at the [LYB file](https://github.com/sysrepo/sysrepo/blob/master/src/plugins/ds_lyb.c) plugin, even that is implemented as a datastore plugin. But note that, depending on what features you want your datastore to support (caching, backup, ...), implementing a datastore plugin is not trivial.

**Comment by ydong08** [comment]
Got it, thank you very much!
