### ISSUE TITLE
Netopeer2 Tool installation feasibilty on ARM processor

### ISSUE THREAD

**Issue by aswin19996** [sysrepo/sysrepo#2125]
Hi I am posting this issue to understand if the Netopeer2 tool along with its pre-requisites such as Libyang, Libnetconf2 and Sysrepo are feasible to be built and installed on an ARM processor 

This ARM processor belongs to the evaluation board from Xilinx - ZCU102, and other notable specifications are DD4 DIMM processor.

Hoping for a response.

**Comment by aswin19996** [comment]
Thanks For the response, Michal.
The OS which i am targeting to use is PetaLinux on ZCU102. Is Netopeer2 and its other required repositories compatible with this OS specifically?

If Yes,
Considering the fact of successfully booting up the ZCU102 Evaluation board with Petalinux OS, will i be still able to do a git clone operations for the essential repositories of Netopeer2 from its terminal ?

**Comment by michalvasko** [comment]
Hi,
I cannot tell you whether all the required features are available on PetaLinux. However, only POSIX should be needed, even any GNU extensions that are needed have been implemented manually for cases when they are not on the system.
