### ISSUE TITLE
[cl_sm_fd_read_data]recv return error cause connection close

### ISSUE THREAD

**Issue by fei15115** [sysrepo/sysrepo#2126]
Hi
I have use **sr_dp_get_items_subscribe** to subscribe and set the callback function.But when the device run for 1 day or more.I use "get  --filter-xpath " to get the DATA and the return is  NULL.I find some error messages before I send the command.

error messages form the last normal "GET":
**[ERR] Error by reading data on fd 31: Connection reset by peer.
[ERR] State data arrived after timeout expiration or session id=1005259568 is invalid (msg=65, session->req=0).
[ERR] State data arrived after timeout expiration or session id=1005259568 is invalid (msg=65, session->req=0).
[ERR] State data arrived after timeout expiration or session id=1005259568 is invalid (msg=65, session->req=0).
[ERR] State data arrived after timeout expiration or session id=1005259568 is invalid (msg=65, session->req=0).**
When I get again,return nothing and I get this output below:
**VERBOSE: Resolving unresolved data nodes and their constraints...
VERBOSE: All data nodes and constraints resolved.
VERBOSE: Resolving unresolved data nodes and their constraints...
VERBOSE: All data nodes and constraints resolved.
VERBOSE: Session 1: thread 1 event new RPC.**

Maybe the error output from here:(/src/clientlib/cl_subscription_manager.c *1229)
![image](https://user-images.githubusercontent.com/37013076/92103137-1b1e1600-ee12-11ea-81e2-77a41a54fb71.png)

The function "recv" return error,and "close_requested" is true,and close the connection.
Could you give me some addvice why "recv" return error and connection close?

**Versions**
       sysrepo:       version 0.7.4
       Netopeer2:  version 0.5.22

**Comment by michalvasko** [comment]
Hi,
I cannot really help since you are using deprecated legacy versions of *sysrepo* and *netopeer2*. But most likely the timeout for your callback to provide the state data elapsed.

**Comment by fei15115** [comment]
Thanks for your reply.
Can I just ignore it and not to set the "close_requested" to true?
or if this happened then exit the process?
Is their some way I can find this happened on my app process?

**Comment by michalvasko** [comment]
I do not think this is what you want to do but perhaps it will work. To learn why your app is timing out, I would start by putting some messages into your callbacks when they are called/when they return and set *sysrepo* verbosity in them.
