### ISSUE TITLE
Q: SR_EV_UPDATE and validation

### ISSUE THREAD

**Issue by iljatab** [sysrepo/sysrepo#2128]
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.71 (SO v5.5.13)

Hi,

This is just a question about SR_EV_UPDATE usage and data validation.

Say, we have two YANG models:
  openconfig-interfaces.yang
  some-model.yang

Objects in some-model.yang reference interfaces in openconfig-interfaces.yang by using `leafref` to `/openconfig-interfaces:interfaces/interface/name`.
Now the user is going to delete an interface instance from openconfig-interfaces.
If at that moment there are references to this interface from some-model.yang then sysrepo will not allow such operation.

I was under impression that SR_EV_UPDATE will allow to "fix" such situation.
Like code for SR_EV_UPDATE is able to, say, delete objects from some-model that referenced the deleted interface and then sysrepo will validate the total transaction as OK.

However it doesn't look like that. The SR_EV_UPDATE event is not generated at all, sysrepo still reports:
```
Leafref "/openconfig-interfaces:interfaces/openconfig-interfaces:interface/openconfig-interfaces:name" of value "eth-1/0/1.1" points to a non-existing leaf.
```
To be sure that we are regestrring correctly for SR_EV_UPDATE I also tested the case when there are no dependent objects in some-model. In that case SR_EV_UPDATE is generated and callback called.

Could you please clarify if/how SR_EV_UPDATE can be used to adjust dependencies before sysrepo validates the whole change-diff?

Ilja.

**Comment by michalvasko** [comment]
Hi,
no, `SR_EV_UPDATE` is not meant for such a use-case. You are trying to bypass YANG rules by wanting to hide the problem from the user, you are not supposed to do that and the user should be made aware that his change is invalid. If this was not the intention of the YANG module, the leafref would have `require-instance` set to `false`.

**Comment by iljatab** [comment]
Hi Michal,

Thanks for reply!

I am not sure why do you consider this question as "trying to bypass YANG rules and hide the problem from the user".

Look, say there is an interface eth-1/0/1.1, configured in openconfig-interfaces.
On top of this interface there may be a lot of other configurations on L2 and L3 levels (routing protocols, mpls, QoS etc...).
These features are configured in several different YANG models using leafref to interface name.

Now, when the user deletes the interface eth-1/0/1.1, it means that his intention is to completely delete all interface-related stuff from all relevant models.
The user likely doesn't want to manually delete interface-related configuration from numerous models one by one.

So I was under impression that SR_EV_UPDATE will allow to do additional changes to the datastore (like delete related objects) and only after that the transaction validation takes place.

But OK, if it is not designed to work that way...

Ilja.

**Comment by michalvasko** [comment]
Hi,
like I said, the intention was that the user really must manually delete all the other configuration that becomes invalid (so that they are aware of what exactly they are changing). However, in case this is too complicated, the module should have used some mechanisms to simplify it (the aforementioned `require-instance false` or even `when` conditions, which actually implement the auto-deletion you wanted to do using the update event).
