### ISSUE TITLE
Connecting to sysrepo failed (Timeout expired)

### ISSUE THREAD

**Issue by CmeRR4** [sysrepo/sysrepo#2129]
I'm using sysrepo and netopeer from master branches 
> sysrepoctl -V
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.70 (SO v5.5.12)

> netopeer2-server -V
netopeer2-server 1.1.39
compile time: Sep  2 2020, 14:30:31

After the netopeer2-server crashed, I cannot use it and start it back, Nor I cannot use sysrepoctl:

`~$ sysrepoctl -l
[ERR]: Waiting on a conditional variable failed (sr_connect: Connection timed out).
sysrepoctl error: Failed to connect (Timeout expired)`

or netopeer2:

`[ERR]: LN: Session 7: SSH channel unexpected EOF.
netopeer2-server: /home/john/swdev/sysrepo/src/shm_mod.c:494: sr_shmmod_modinfo_rdlock_upgrade: Assertion shm_lock->write_locked failed.
Aborted

$ sudo netopeer2-server -d -u john
[ERR]: NP: Connecting to sysrepo failed (Timeout expired).
[ERR]: NP: Server init failed.`

I am not reporting the crash here, I just want to know how I can restart the netopeer server again after the crash.

I checked and there is no any sysrepo nor netopeer processes running in my system after the crash.

Thanks

**Comment by CmeRR4** [comment]
I could fix the problem by restarting the system.

So, any time the netopeer2 server is exiting unexpectedly I have to restart the whole system?

Or there are some other ways to quickly resolve the bad state and star the server again?

**Comment by michalvasko** [comment]
Hi,
you can use `make shm_clean` target of *sysrepo* with the exact same effect.

**Comment by aswin19996** [comment]
Thanks Michal, it worked.
