### ISSUE TITLE
Query: how to replace the part config of one module by sysrepocfg, not merging

### ISSUE THREAD

**Issue by adamzyg** [sysrepo/sysrepo#2131]
for example, module A has a and b container. 
firstly, I edit the part config belonging to container a:
```shell
sysrepocfg --edit=A-a.xml -d running -f xml -m A -v2
```
then, edit the part config belonging to containner b:
```shell
sysrepocfg --edit=A-b.xml -d running -f xml -m A -v2
```
now i wanna to replace the A-b.xml to A-b1.xml, if i use the command:
```shell
sysrepocfg --edit=A-b1.xml -d running -f xml -m A -v2
```
the config of b container is the result of merging A-b and A-b1, so how to replace the old A-b to A-b1 but not modify the A-a using `sysrepocfg`?

**Comment by michalvasko** [comment]
Hi,
you want to perform `import`, so just use `--import` instead of `--edit`.

**Comment by adamzyg** [comment]
Sorry, i made a mistake.
Module A has `container a` and `list b`. Current config of  list b is A-b.xml, I wanna replace the current config of list b with A-b1.xml and keep the config of container a. Which command can be executed to get this result?

**Comment by michalvasko** [comment]
Hi,
it seems you need a more complex operation than *sysrepocfg* can provide directly. I suppose what you could do is to import your `A-b1.xml` into `candidate`, export only the data you want to use from it (list b) into a file, and then merge this file.

**Comment by adamzyg** [comment]
OK，i see.
closed.
