### ISSUE TITLE
Query: How to get a list instance of the key whose data values change?

### ISSUE THREAD

**Issue by rinkalbhatia06** [sysrepo/sysrepo#2135]
**Yang Model**
module wlm-rx-power {
    namespace "urn:sysrepo:wlm-rx-power";
    prefix wlmrxpow;

    container wlmdetails{
    	list wlmdetail{
    		key "rackId subRackId cardId cardType cardSubType portId";
	    	leaf rackId{
	    		type uint8;
	    	}

	    	leaf subRackId{
	    		type uint8;
	    	}

	    	leaf cardId{
	    		type uint8;
	    	}

	    	leaf cardType{
	    		type uint8;
	    	}

	    	leaf cardSubType{
	    		type uint8;
	    	}

	    	leaf portId{
	    		type uint8;
	    	}

	    	leaf waveCode{
	    		type uint8;
	    	}

	    	leaf direction{
	    		type uint8;
	    	}

	    	leaf rxPower{
	         type decimal64{
	         	fraction-digits 2;
	         }
	    	}

	    	leaf losState{
	    		type uint8;
	    	}
    	}
    }
}

**XML**
![Screenshot from 2020-09-09 14-04-35](https://user-images.githubusercontent.com/69560210/92574736-1be8f900-f2a5-11ea-848d-f2fbae1e141d.png)

If losState of the key (rackId = 6, subRackId = 1, cardId = 2, cardType = 53, cardSubType = 0, portId = 1) changes from value=2 to value=1, How can I get  all the values for the key (rackId = 6, subRackId = 1, cardId = 2, cardType = 53, cardSubType = 0, portId = 1)?

**Comment by michalvasko** [comment]
You have not provided any details but, in general, you should subscribe to the list changes (`sr_module_change_subscribe`) and then you will get notified on every change. You can even use `application_changes_example` to always print the change.

**Comment by rinkalbhatia06** [comment]
Hi Michal,
I did the same, by application change i got what parameter(difference. i.e losState changed from 2 to 1) is changed but i want all entries of the list,whose parameter is modified ...i want all the detail of the key (rackId = 6, subRackId = 1, cardId = 2, cardType = 53, cardSubType = 0, portId = 1) .i.e its wavecode,rxPower,direction.

**Comment by michalvasko** [comment]
Maybe it would be best if you pasted the output you got and the one you would like to get because I still do not understand what exactly you want. But all the information is there, it just may not be printed the way you expect.

**Comment by rinkalbhatia06** [comment]
I am getting this output on lostState value change:
![image](https://user-images.githubusercontent.com/69560210/92680421-6c656280-f348-11ea-8de1-53a14a5478d6.png)

But I want :
![image](https://user-images.githubusercontent.com/69560210/92680512-a3d40f00-f348-11ea-83c7-841af36227d7.png)

**Comment by michalvasko** [comment]
Hi,
I still do not know whether you want all the key values in the change (`sr_get_change_next()`) or in the config (`sr_get_items()`) but it does matter that much. In both cases you should probably use the `_tree` variants of both functions. They return *libyang* data node structures that are more suitable for further processing (there are many handy function in *libyang* API). If you do that, you will always get the full tree for each change/data node with all the parents that you can examine.

However, in case of changes you would not get all the values for a list instances, only the ones that were changed and all the keys. So, you would need to call `sr_get_data()`, for example, to get the non-modified children of a list.

**Comment by rydy** [comment]
> However, in case of changes you would not get all the values for a list instances, only the ones that were changed and all the keys. So, you would need to call `sr_get_data()`, for example, to get the non-modified children of a list.

If the key value has not changed, how can I get the corresponding key value by changing the value?

**Comment by michalvasko** [comment]
I do not understand the question at all.

**Comment by rydy** [comment]
> > However, in case of changes you would not get all the values for a list instances, only the ones that were changed and all the keys. So, you would need to call `sr_get_data()`, for example, to get the non-modified children of a list.
> 
> If the key value has not changed, how can I get the corresponding key value by changing the value?



> I do not understand the question at all.


as follow,

example yang model:

### module example {
	namespace "example:1.0";
	list students {
        key key_id;
      leaf key_id {
        type string;
        description
          "Unique key_id of students object.";
      }
	  leaf name {
        type string;
      }
	  leaf age {
        type int16;
      }
    }
}

example xml:
```
<example xmlns="example:1.0">
	<students>
		<key_id>0</key_id>
		<name>jack</name>
		<age>21</age>
	<students>
	<students>
		<key_id>1</key_id>
		<name>mary</name>
		<age>23</age>
	<students>
<example>
```

If only the value of the age field changes in the sample model, and use 'sr_get_change_next' to get the changed value. Using 'sr_get_data' will get all the values, I just need to get the key_id for the changed age field. how can get the key_id field corresponding to the age field?

**Comment by michalvasko** [comment]
Let us say that (to conform to the module you posted)
```xml
<students xmlns="example:1.0">
  <key_id>0</key_id>
  <name>jack</name>
  <age>21</age>
</students>
<students xmlns="example:1.0">
  <key_id>1</key_id>
  <name>mary</name>
  <age>23</age>
</students>
```
changed into
```xml
<students xmlns="example:1.0">
  <key_id>0</key_id>
  <name>jack</name>
  <age>40</age>
</students>
<students xmlns="example:1.0">
  <key_id>1</key_id>
  <name>mary</name>
  <age>23</age>
</students>
```

If you then use `sr_get_change_next()`, you will get `new_value->xpath` with `/example:students[key_id='0']/age`. The `key_id` value is in the `xpath`. If you use `sr_get_change_tree_next()`, you will get `node->parent->child` as `struct lyd_node_leaf_list *` with value `0`.

**Comment by rydy** [comment]
> Let us say that (to conform to the module you posted)
> 
> ```
> <students xmlns="example:1.0">
>   <key_id>0</key_id>
>   <name>jack</name>
>   <age>21</age>
> </students>
> <students xmlns="example:1.0">
>   <key_id>1</key_id>
>   <name>mary</name>
>   <age>23</age>
> </students>
> ```
> 
> changed into
> 
> ```
> <students xmlns="example:1.0">
>   <key_id>0</key_id>
>   <name>jack</name>
>   <age>40</age>
> </students>
> <students xmlns="example:1.0">
>   <key_id>1</key_id>
>   <name>mary</name>
>   <age>23</age>
> </students>
> ```
> 
> If you then use `sr_get_change_next()`, you will get `new_value->xpath` with `/example:students[key_id='0']/age`. The `key_id` value is in the `xpath`. If you use `sr_get_change_tree_next()`, you will get `node->parent->child` as `struct lyd_node_leaf_list *` with value `0`.

Use 'sr_get_items/' to get its associated nodes based on 'key_id = 0', I know the way. I think it's a little bit tedious, ls there any other way?

**Comment by michalvasko** [comment]
Yes, if you do not want to handle xpath strings, you can use `sr_get_change_tree_next()`, just like I mentioned. Did you even read my whole reply?

**Comment by rydy** [comment]
> Yes, if you do not want to handle xpath strings, you can use `sr_get_change_tree_next()`, just like I mentioned. Did you even read my whole reply?

i see, thank you for your help.

**Comment by myonlystarWang** [comment]
> Let us say that (to conform to the module you posted)
> 
> ```
> <students xmlns="example:1.0">
>   <key_id>0</key_id>
>   <name>jack</name>
>   <age>21</age>
> </students>
> <students xmlns="example:1.0">
>   <key_id>1</key_id>
>   <name>mary</name>
>   <age>23</age>
> </students>
> ```
> 
> changed into
> 
> ```
> <students xmlns="example:1.0">
>   <key_id>0</key_id>
>   <name>jack</name>
>   <age>40</age>
> </students>
> <students xmlns="example:1.0">
>   <key_id>1</key_id>
>   <name>mary</name>
>   <age>23</age>
> </students>
> ```
> 
> If you then use `sr_get_change_next()`, you will get `new_value->xpath` with `/example:students[key_id='0']/age`. The `key_id` value is in the `xpath`. If you use `sr_get_change_tree_next()`, you will get `node->parent->child` as `struct lyd_node_leaf_list *` with value `0`.

Hi michal,
    Is it true that `sr_get_change_next()` and `sr_get_change_tree_next()` provide the same functionality but just the different return value?(one is sr_val_t **new_value,another is lyd_node **node)
    If I need to subscribe a list in yang module,it may be better to use sr_get_change_tree_next() in order to get the key value more conveniently,right?

**Comment by michalvasko** [comment]
Yes, both assumptions are correct.
