### ISSUE TITLE
Getting error in running sr_set_item_example

### ISSUE THREAD

**Issue by rinkalbhatia06** [sysrepo/sysrepo#2137]
**Yang Model**
module wlm-rx-power {
    namespace "urn:sysrepo:wlm-rx-power";
    prefix wlmrxpow;

    container wlmdetails{
    	list wlmdetail{
    		key "rackId subRackId cardId cardType cardSubType portId";
	    	leaf rackId{
	    		type uint8;
	    	}

	    	leaf subRackId{
	    		type uint8;
	    	}

	    	leaf cardId{
	    		type uint8;
	    	}

	    	leaf cardType{
	    		type uint8;
	    	}

	    	leaf cardSubType{
	    		type uint8;
	    	}

	    	leaf portId{
	    		type uint8;
	    	}

	    	leaf waveCode{
	    		type uint8;
	    	}

	    	leaf direction{
	    		type uint8;
	    	}

	    	leaf rxPower{
	         type decimal64{
	         	fraction-digits 2;
	         }
	    	}

	    	leaf losState{
	    		type uint8;
	    	}
    	}
    }
}

**XML**
![Screenshot from 2020-09-09 14-04-35](https://user-images.githubusercontent.com/69560210/92584295-17c2d880-f2b1-11ea-87f5-112aa79d1c6f.png)

Getting error in running this:
sudo ./sr_set_item_example /wlm-rx-power:wlmdetails/wlmdetail[rackId='6'subRackId='1'][cardId='2'][cardType='53'][cardSubType='0'][portId='1']/direction 9

Application will set "/wlm-rx-power:wlmdetails/wlmdetail[rackId=6subRackId=1][cardId=2][cardType=53][cardSubType=0][portId=1]/direction" to "9".
[ERR]: Unexpected character(s) '6' ("6subRackId=1][cardId=2][cardType=53][cardSubType=0][portId=1]/direction").
[ERR]: Invalid datastore edit.

**Comment by michalvasko** [comment]
Hi,
you must pay attention to the output, that is what is there for
```
Application will set "/wlm-rx-power:wlmdetails/wlmdetail[rackId=6subRackId=1][cardId=2][cardType=53][cardSubType=0][portId=1]/direction" to "9".
```
Firstly, you probably wanted to use `...wlmdetail[rackId='6'][subRackId='1']...`. Secondly, as you can see, all the `'` were removed by the shell. To keep them, you must enclose the whole xpath argument in `"`.

**Comment by rinkalbhatia06** [comment]
Hi Michal,
Thank you so much, 
sudo ./sr_set_item_example "/wlm-rx-power:wlmdetails/wlmdetail[rackId='6'][subRackId='1'][cardId='2'][cardType='53'][cardSubType='0'][portId='1']/direction" 9

This command solved the issue.
