### ISSUE TITLE
Query: A question about function ‘’sr_shmmain_ext_get_size_main_shm‘’？

### ISSUE THREAD

**Issue by Julian-younger** [sysrepo/sysrepo#2140]
hi,michalvasko,
   I have a question about function ‘’sr_shmmain_ext_get_size_main_shm‘’ is that when you calculate the lengths of change_subs using the 'sub_count',And when calculate the lengths of oper and notif using the 'oper_subs' and 'notif_subs',why not sub_counts? what are the differences?Thanks a lot!
```C
static size_t
sr_shmmain_ext_get_size_main_shm(sr_shm_t *shm_main, char *ext_shm_addr)
{
        ..............
    /* existing module subscriptions */
    SR_SHM_MOD_FOR(shm_main->addr, shm_main->size, shm_mod) {
        /* change subscriptions */
        for (i = 0; i < SR_DS_COUNT; ++i) {
            change_subs = (sr_mod_change_sub_t *)(ext_shm_addr + shm_mod->change_sub[i].subs);
            for (j = 0; j < shm_mod->change_sub[i].sub_count; ++j) {
                if (change_subs[j].xpath) {
                    shm_size += sr_strshmlen(ext_shm_addr + change_subs[j].xpath);
                }
            }
            **shm_size += SR_SHM_SIZE(shm_mod->change_sub[i].sub_count * sizeof *change_subs);**
        }

        /* oper subscriptions */
        oper_subs = (sr_mod_oper_sub_t *)(ext_shm_addr + shm_mod->oper_subs);
        for (i = 0; i < shm_mod->oper_sub_count; ++i) {
            assert(oper_subs[i].xpath);
            shm_size += sr_strshmlen(ext_shm_addr + oper_subs[i].xpath);
        }
        **shm_size += SR_SHM_SIZE(shm_mod->oper_subs * sizeof *oper_subs);**

        /* notif subscriptions */
        **shm_size += SR_SHM_SIZE(shm_mod->notif_subs * sizeof(sr_mod_notif_sub_t));**
    }

    return shm_size;
}
```

**Comment by michalvasko** [comment]
Hi,
I think it was a bug but since, in general, more memory was being allocated, it did not manifest. Thanks, fixed.

**Comment by Julian-younger** [comment]
OK，Thinks a lot! 
I have another question for main_shm and ext_shm:
I have found so many functions,such as sr_shmmod_notif_subscription_add,sr_shmmod_oper_subscription_add  call the function sr_shmrealloc_add, how to keep pace with different type data，such as change,oper,notif  in the ext_shm?

**Comment by michalvasko** [comment]
Well, structures in SHM are a mess but I tried my best to make it as concise as I can. The current state is pretty good in my experience, it was worse. Still, it certainly takes time for someone else to understand it all, not sure what else to tell you. Maybe one thing, always pay attention to the second word in every function, it should group similar functions together and tell you what the functions primarily work with. Example, `sr_shmmod_*_add()` will be adding something to a `sr_mod_t` structure in the shared memory.

**Comment by Julian-younger** [comment]
Well,I get it,And another  question is that the function  sr_shmrealloc_add  adds  memory at the end of ext_shm ,when the end memory is over SR_SHM_WASTED_MAX_MEM ,and then copy to the front of ext_shm, am I right？

**Comment by michalvasko** [comment]
Yes, `sr_shmrealloc_add` add new memory at the end and usually a hole is created this way. Once the sum of these holes (wasted memory) reaches a constant, it is defragmented.

**Comment by Julian-younger** [comment]
Thanks for your replies!
