### ISSUE TITLE
Running datastore persistence

### ISSUE THREAD

**Issue by mdoshi-com** [sysrepo/sysrepo#2144]
Hi,
As per NETCONF RFC (https://tools.ietf.org/html/rfc8342#section-5.1.3):
1. running datastore can be persisted
2. running datastore can be loaded on device bootup, if device does not support separate startup datastore.

Can you please help us figure out how these two functionalities can be achieved in sysrepo.
Do we have to enable some flag/configuration setting in sysrepo for this.

**Comment by michalvasko** [comment]
Hi,
unfortunately, *sysrepo* does not support these features of `running`. However, you should be able to achieve this by mirroring `startup` and `running`, for example. Meaning calling `sr_copy_config()` on every running/startup change.

**Comment by iGovindY** [comment]
Hi Michal,

I think this what you meant,
To have a `sr_copy_config()` call in `MyCallback::module_change() ` method when the event is `DONE`.
this will happen in the context of the callback thread, right?

I think with the above approach, failure cases will also be handled.

Thanks
Govind.

**Comment by michalvasko** [comment]
Yes, that should work. In case of failure, no data change will occur so nothing needs to be done.

**Comment by iGovindY** [comment]
yes that's why the check for the event as DONE

Thanks a lot.

**Comment by mdoshi-com** [comment]
Hi Michal,
One small query on this, so as per the suggestion we should make changes like:

1. In function module_change (), add **sr_copy_config** after sr_get_change_next ():

```
while ((rc = sr_get_change_next(session, it, &oper, &old_value, &new_value)) == SR_ERR_OK) {

       // handle the changes.
    }

    if (event == SR_EV_DONE) 
       
        sr_copy_config(session_running, module_name, SR_DS_RUNNING, 0, 0);

```

Is there any lock or other issue which might be seen in calling sr_copy_config (running to startup) inside the module_change callback itself.

Regards,
Meghna

**Comment by michalvasko** [comment]
I think it should generally work. But you may want to avoid calling `sr_apply_changes` or `sr_copy_config` with `wait` set to `1` meaning the operation will always return before the `DONE` callback is processed. It probably should work anyway, just take much longer, but the complexity of all this is just too high to say for certain.

**Comment by mdoshi-com** [comment]
Hi Michal,
Sorry got bit confused here.
What do you mean by 
"meaning the operation will always return before the DONE callback is processed", 

the code snippet i sent above is all inside module_change callback itself, so what is this DONE callback?

Regards,
Meghna

**Comment by michalvasko** [comment]
Sorry for being vague, I thought you would understand. I meant `module_change` callback with `SR_EV_DONE` event.

**Comment by mdoshi-com** [comment]
Hi Michal,
So just to confirm, the sequence of events is:
1. module_change is called with event SR_EV_DONE.
2. as part of processing (1), inside module_change function, once we finish with sr_get_change_next, we do the following:
```
if (event == SR_EV_DONE) 
        sr_copy_config(session_running, module_name, SR_DS_RUNNING, 0, 0);
```
3. So this means we are calling sr_copy_config in the context of handling SR_EV_DONE event.

So calling for sr_copy_confing while handling SR_EV_DONE event is ok. Is this understanding correct.

Regards,
Meghna

**Comment by michalvasko** [comment]
For the first 3 bullets, you understand it correctly, that is what I meant. However, it is still possible I may be missing something because the complexity of these operations are just too large.

> sr_copy_config waits for all SR_EV_CHANGE events to finish, so this implies that if we call sr_copy_config for event SR_EV_DONE, then by this time running datastore would already have the changes which the callback is reporting. So calling sr_copy_config to copy from running to startup, wont miss any change.

Correct.

> we would use value = 0 for both timeout_ms and wait attributes.

That is the safe thing to do, I believe.

> We restart sysrepo

That is not really possible, it is a library. Do you mean *netopeer2*? If so, then it does not remove the `running` datastore files, they are actually never manually removed. The fact that all SHM files are always removed on system restart is used and so when they are missing, they are created with the content of `startup`.

**Comment by mdoshi-com** [comment]
Hi Michal,
Thanks for the details. Understood.
But some queries on this persistence part, will first explain our system behaviour (lets assume a node reboot case for now so that all non persisted volumes would get cleared)
1. /etc/sysrepo : this is persist across reboots
2. /dev/shm : this is not persisted across reboots.

So with this configuration, if we reboot the node, then since startup and running datastores are all kept under /etc/sysrepo, what would happen? 
1. will sysrepo wipe out running datastore files.
2. or running datastore is not kept under /etc/sysrepo at all?

Regards,
Meghna

**Comment by michalvasko** [comment]
> running datastore is not kept under /etc/sysrepo at all?

This one is correct.

**Comment by mdoshi-com** [comment]
Hi Michal,
Oh ok. So just to summarize:
1.startup datastore is kept in /etc/sysrepo (essentially path which is set in SYSREPO_REPOSITORY_PATH)
2. All other datastore (like running, candidate etc) and the shared memory files are kept in /dev/shm.

Is this understanding correct?
Also, one confirmation, other that startup datastore related files, no other files are kept in /etc/sysrepo path (i.e SYSREPO_REPOSITORY_PATH).  Is this correct?

Regards,
Meghna

**Comment by michalvasko** [comment]
These are the paths printed by `cmake`:
```
-- Sysrepo repository: /home/vasko/Documents/sysrepo/build/repository
-- Startup data path:  /home/vasko/Documents/sysrepo/build/repository/data
-- Notification path:  /home/vasko/Documents/sysrepo/build/repository/data/notif
-- YANG module path:   /home/vasko/Documents/sysrepo/build/repository/yang
-- SRPD plugins path:  /usr/local/lib64/sysrepo/plugins
```
You can ignore the last one, all the others should answer your question. And yes, all the rest (such as running, candidate, or operational datastore) is stored as a SHM segment.

**Comment by mdoshi-com** [comment]
Hi Michal,
Thanks. 
So in the above case, SYSREPO_REPOSITORY_PATH = /home/vasko/Documents/, is this right?

Regards,
Meghna

**Comment by michalvasko** [comment]
No, `SYSREPO_REPOSITORY_PATH` is an environment variable that can override the configured repository path. In the presented case, `/home/vasko/Documents/sysrepo/build/repository` is the configured one, obviously.

**Comment by mdoshi-com** [comment]
Hi Michal,
Oh ok. 
So you mean to say all the above paths change if SYSREPO_REPOSITORY_PATH is changed from what is set in cmake.
Is this understanding correct.
If yes, then i have few queries, except for Startup data path, i dont understand what the other paths are and why these need to be persisted:
-- Sysrepo repository: 
-- Notification path:  
-- YANG module path:  

Is YANG module path, the path where yangs from netopeer2/modules/ are copied. 

Regards,
Meghna

**Comment by michalvasko** [comment]
> So you mean to say all the above paths change if SYSREPO_REPOSITORY_PATH is changed from what is set in cmake.
Is this understanding correct.

Yes.

> -- Sysrepo repository:

This is simply the prefix for all the persistent data so they are clearly organized, just some internal stuff is stored there (file locks, for example).

> -- Notification path:

Directory for the stored notifications for replay.

> -- YANG module path:

All the installed YANG modules, *sysrepo* keeps its own copy that you should not touch.

**Comment by mdoshi-com** [comment]
Hi Michal,
To verify that only startup datastore persists, i tried following trials:
1. Configure some data in running datastore using edit-config via netopeer2-client.
2. Stop all processes, and did remove as follows:
```
rm -rf /dev/shm/sr_*
rm -rf /dev/shm/srsub_*

```
3. restart all process (netopeer2-cli, netopeer2-server, ComApp :this is our application binary).
4. Connect from netopeer2-cli and did get as follows.

> get-config  --source running --filter-xpath /_3gpp-common-managed-element:*
```
DATA
<ManagedElement xmlns="urn:3gpp:sa5:_3gpp-common-managed-element">
  <id>MEid</id>
  <attributes>
    <priorityLabel>1</priorityLabel>
  </attributes>
  <GNBDUFunction xmlns="urn:3gpp:sa5:_3gpp-nr-nrm-gnbdufunction">
    <id>GNBDUid</id>
    <attributes>
      <priorityLabel>2</priorityLabel>
      <gNBId>3</gNBId>
      <gNBIdLength>25</gNBIdLength>
      <gNBDUId>400</gNBDUId>
      <resourceType>resourceType</resourceType>
    </attributes>
  </GNBDUFunction>
</ManagedElement>

```

 I see the configuration done in step 1 above, is still present. Is there some directory/file cleanup which i missed to simulate a node restart behaviour?

**Comment by michalvasko** [comment]
Hi,
what you are seeing is probably the `startup` datastore that has been copied into `running`. More info [here](https://netopeer.liberouter.org/doc/sysrepo/master/html/index.html#datastores).

**Comment by mdoshi-com** [comment]
Yes Michal, that is right.
But my understanding is that, after doing these steps (3, 4 in above mail)

3. delete-config --target startup from netopeer2-cli.

4. Stop all processes, and did remove as follows:

```
rm -rf /dev/shm/sr_*
rm -rf /dev/shm/srsub_*
```

it should have simulated the following use case:
1. startup deletion and
2. node restart

But why is startup still remaining? Step 3 should have cleared startup, or am i misunderstanding something here.

Regards,
Meghna

**Comment by michalvasko** [comment]
Sorry, I read it too hastily and skipped the `delete-config` call. So I tried to reproduce it this way but did not, the config remained deleted. Please, provide a simple reproducible example, otherwise I am not able to help you.

**Comment by mdoshi-com** [comment]
Hi Michal,
So in summary, if we do following (assuming we have put some data in startup via copy-config of running to startup):

1. delete-config --target startup from netopeer2-cli.

2. rm -rf /dev/shm/sr_*
rm -rf /dev/shm/srsub_*

3. restart netopeer2-server, sample application.

If you do just these steps, do you see startup datastore getting deleted?

Regards,
Meghna

**Comment by mdoshi-com** [comment]
Hi Michal,
Were you able to check with above steps if startup is getting deleted or not.

Regards,
Meghna

**Comment by michalvasko** [comment]
Having just installed *netopeer2*:
```
> ls -l repository/data/
total 92
-rw------- 1 vasko users    7 dec  4 10:03 ietf-crypto-types.startup
-rw-rw-rw- 1 vasko users    7 dec  4 10:03 ietf-datastores.startup
-rw------- 1 vasko users 2204 dec  4 10:03 ietf-keystore.startup
-rw------- 1 vasko users   85 dec  4 10:03 ietf-netconf-acm.startup
-rw------- 1 vasko users    7 dec  4 10:03 ietf-netconf-monitoring.startup
-rw------- 1 vasko users    7 dec  4 10:03 ietf-netconf-nmda.startup
-rw-rw-rw- 1 vasko users    7 dec  4 10:03 ietf-netconf-notifications.startup
-rw------- 1 vasko users  221 dec  4 10:03 ietf-netconf-server.startup
-rw------- 1 vasko users    7 dec  4 10:03 ietf-netconf.startup
-rw-rw-rw- 1 vasko users    7 dec  4 10:03 ietf-netconf-with-defaults.startup
-rw-rw-rw- 1 vasko users    7 dec  4 10:03 ietf-origin.startup
-rw------- 1 vasko users    7 dec  4 10:03 ietf-ssh-server.startup
-rw------- 1 vasko users    7 dec  4 10:03 ietf-tcp-common.startup
-rw------- 1 vasko users    7 dec  4 10:03 ietf-tls-server.startup
-rw------- 1 vasko users   49 dec  4 10:03 ietf-truststore.startup
-rw------- 1 vasko users    7 dec  4 10:03 ietf-x509-cert-to-name.startup
-rw-rw-rw- 1 vasko users    7 dec  4 10:03 ietf-yang-library.startup
-rw------- 1 vasko users    7 dec  4 10:03 nc-notifications.startup
drwxrwxrwx 2 vasko users 4096 dec  4 09:21 notif
-rw------- 1 vasko users    7 dec  4 10:03 notifications.startup
-rw------- 1 vasko users    7 dec  4 10:03 sysrepo-monitoring.startup
-rw-rw-rw- 1 vasko users 3372 dec  4 10:03 sysrepo.startup
-rw-rw-rw- 1 vasko users    7 dec  4 10:03 yang.startup
```
After having executed `delete-config --target startup`:
```
> ls -l repository/data/
total 92
-rw------- 1 vasko users    7 dec  4 10:03 ietf-crypto-types.startup
-rw-rw-rw- 1 vasko users    7 dec  4 10:03 ietf-datastores.startup
-rw------- 1 vasko users   53 dec  4 10:04 ietf-keystore.startup
-rw------- 1 vasko users   85 dec  4 10:04 ietf-netconf-acm.startup
-rw------- 1 vasko users    7 dec  4 10:03 ietf-netconf-monitoring.startup
-rw------- 1 vasko users    7 dec  4 10:03 ietf-netconf-nmda.startup
-rw-rw-rw- 1 vasko users    7 dec  4 10:03 ietf-netconf-notifications.startup
-rw------- 1 vasko users   57 dec  4 10:04 ietf-netconf-server.startup
-rw------- 1 vasko users    7 dec  4 10:03 ietf-netconf.startup
-rw-rw-rw- 1 vasko users    7 dec  4 10:03 ietf-netconf-with-defaults.startup
-rw-rw-rw- 1 vasko users    7 dec  4 10:03 ietf-origin.startup
-rw------- 1 vasko users    7 dec  4 10:03 ietf-ssh-server.startup
-rw------- 1 vasko users    7 dec  4 10:03 ietf-tcp-common.startup
-rw------- 1 vasko users    7 dec  4 10:03 ietf-tls-server.startup
-rw------- 1 vasko users   49 dec  4 10:04 ietf-truststore.startup
-rw------- 1 vasko users    7 dec  4 10:03 ietf-x509-cert-to-name.startup
-rw-rw-rw- 1 vasko users    7 dec  4 10:03 ietf-yang-library.startup
-rw------- 1 vasko users    7 dec  4 10:03 nc-notifications.startup
drwxrwxrwx 2 vasko users 4096 dec  4 09:21 notif
-rw------- 1 vasko users    7 dec  4 10:03 notifications.startup
-rw------- 1 vasko users    7 dec  4 10:03 sysrepo-monitoring.startup
-rw-rw-rw- 1 vasko users 3372 dec  4 10:03 sysrepo.startup
-rw-rw-rw- 1 vasko users    7 dec  4 10:03 yang.startup
```
The files got only smaller because there are still some default values stored, nothing else though.

**Comment by mdoshi-com** [comment]
Hi Michal,
Ok so are you saying we have to install latest netopeer2.
Currently we are using (as per netopeer2/CMakeLists)
NP2SRV_VERSION 1.1.43

Regards,
Meghna

**Comment by michalvasko** [comment]
I do not know why it does not work but I have provided some steps that you can try and verify whether they work for you or not. I do not think the problem is in *netopeer2* version.
