### ISSUE TITLE
Query: How to find the parent of node that got changed

### ISSUE THREAD

**Issue by mdivyamohan** [sysrepo/sysrepo#2145]
For example, consider `module_change_cb` for ietf-interface yang.

I subscribed to changes of complete subtree as:
`sr_get_changes_iter(session, "/ietf-interfaces:*//.", &iter);`

I initially created 6 interfaces eth1..6 in data store.
Then through edit-config, I modified field `enabled` of interface `eth6`.

```
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
        <interface>
                <name>eth6</name>
                <enabled>false</enabled>
```

In the callback, when I print the modified tree using `sr_get_change_tree_next`, I get only the information specific to field `enabled`. 
Changed tree content (in json format):
``` 
{
  "ietf-interfaces:enabled": false,
  "@ietf-interfaces:enabled": {
    "ietf-netconf:operation":"replace",
    "sysrepo:orig-value":"true"
  }
}
```

How do I fetch the parent from this `lyd_node`? I am trying to find the parent node, and from there find the key attribute `name`.

I want to subscribe for changes of complete subtree, but need to be able to find the context of change, i.e parent node.

**Comment by michalvasko** [comment]
Hi,
the parent should be normally accessible using `node->parent`, `node` being the out parameter of `sr_get_change_tree_next()`.
