### ISSUE TITLE
Performance benchmark

### ISSUE THREAD

**Issue by fxie00** [sysrepo/sysrepo#2146]
Hi,

We try to collect some performance benchmark of using sysrepo, including memory (physical memory mainly but may include VSZ too), CPU usage and processing time for typical operations. Are there any reports/reference in this area? If not, we plan to use a simple program (such as the examples in sysrepo) to access sysrepo and some standard tools such as top, gprof  to measure some performance parameters. However, such an approach may report overall memory usage, which includes other components such as libc, etc.. Are there any knobs (in sysrepo) or better approaches to collect performance data directly related to sysrepo?

Another question is for sr_main and sr_ext, which are the two shared memory segments created by sysrepo. Are they used for some common structures such as connections, sessions and registration? How about model-related data? Are they stored in the corresponding .running and .operation shared memory segments? Are there tools/knobs to report itemized memory usage in sysrepo? Thanks.

Best regards,
Feng Xie

**Comment by michalvasko** [comment]
Hi,
the only benchmarking we have done so far is using the `measure_performance` utility in tests. However, that measures only the time of some common operations, not memory. For that you have to use some tools as you have mentioned.

If you want to count even the shared memory segments then yes, you must also look at `sr_main` and `sr_ext`, they are used for all the structures shared between all the *sysrepo* applications including connections, sessions, or subscriptions. There are also separate SHM segments for non-persistent data of every module. Lastly, all persistent data are stored in `repository/data` (by default).
