### ISSUE TITLE
Query: regrading clarification on sysrepo features and errors

### ISSUE THREAD

**Issue by shilin-si** [sysrepo/sysrepo#2147]
Hi
I am facing some issues with some sysrepo features and need some clarification if possible
1) On sysrepo documentation there is 3 events named SR_EV_CHANGE/SR_EV_ABORT and SR_EV_DONE but I am not able to get SR_EV_ABORT. Is there any way to obtain this error session in order to take care rollback?
2) There is an option rollback-on-error on cli messages is there any implementation available on sysrepo for that?
3) Any suggestion in order to to trigger callback application for rollback procedure
4) "sr_session_get_user" this API returns NULL on NETCONF session and working in local sysrepo changes.

**Comment by michalvasko** [comment]
Hi,
1. Yes, you should get this event if a callback is called successfully first but some later one (which is part of the same edit-config) fails, so the first one needs to abort its applied changes.
2. Yes, you should simply implement handling of `SR_EV_ABORT` in your callbacks.
3. See 1.
4. That may be possible and you should use `nc_session_get_username()` for *libnetconf2* NETCONF sessions.

**Comment by robbynet** [comment]
Hello,
From my understanding, only NETCONF Server linked with libnetconf2 and having initialized a special poll session structure for libnetconf2 can use such nc_session_get_username(). 
But for a simple application only linked to libsysrepo to support a couple of RPC and operational data wants to know as well this NETCONF username, as such application does not have access to poll session structure then only libsysrepo could provide the answer. So it seems that sr_session_get_user remains the only way for such simple application to knows the  NETCONF username, isn't it ?

**Comment by michalvasko** [comment]
Yes, if you need to learn about the NETCONF session in a *sysrepo* application callback, you can currently use `sr_session_get_nc_id()` to get the NETCONF session ID and then pair it with a NETCONF session. I have adding also the username there in my TODO, not sure when I will get to it.

**Comment by shilin-si** [comment]
Thanks for the reply
regarding query 1,2,3
I have done SR_EV_ABORT handling . But its not triggering
1. I have manually returned SR_ERR_UNSUPPORTED on SR_EV_CHANGE and SR_EV_DONE none of them trigger SR_EV_ABORT
2. Also tried <error-option>rollback-on-error</error-option> from client edit-config RPC . This method also not working
Can you please provide more clarity on this

**Comment by michalvasko** [comment]
I will try to explain in more detail but I have already said everything. The general principle is that **only** a callback that returned `SR_ERR_OK` will later be called with `SR_EV_DONE` or `SR_EV_ABORT`. The consequence is that you can test it only if you have at least 2 callbacks triggered by a single data change. If you then return `SR_ERR_UNSUPPORTED` from the **second** callback, after the first one succeeded, it will now be called with `SR_EV_ABORT`.

The reason for this is that if a callback failed and it would get called with `SR_EV_ABORT`, you would not be able to distinguish between it being fully applied before or not.

**Comment by shilin-si** [comment]
Hi thanks for the reply
I have done
step1: 2 changes in single edit-config rpc on same module
step2: "sr_get_change_next" succeeded for first change and return SR_ERR_UNSUPPORTED for second change on the event SR_EV_CHANGE
step3; Event after including <error-option>rollback-on-error</error-option> on rpc SR_EV_ABORT not detecting

**Comment by michalvasko** [comment]
You still do not understand, I am talking about 2 **callbacks called**, not calling `sr_get_change_next` twice in one callback.

**Comment by shilin-si** [comment]
Hi 
Got it ..
thanks for the reply

Now SR_EV_ABORT is triggering with and without _rollback-on-error_ on edit-config. Is there any difference while rpc with _rollback-on-error_ as error option.

**Comment by michalvasko** [comment]
Hi,
actually, the `error-option` of `edit-config` is ignored and always set to `rollback-on-error`, the server should inform about this. But you still can get whatever behavior you want (rollback, stop, or continue) depending on your change callbacks and how they react to the abort event.

**Comment by shilin-si** [comment]
ok thank you..
