### ISSUE TITLE
Query: how plugin can advertise features from a yang model

### ISSUE THREAD

**Issue by mdivyamohan** [sysrepo/sysrepo#2150]
Hi,

I am trying to implement a plugin that will be ran by sysrepo-plugind, to handle a specific yang model.
In yang model, there is a feature defined, which is hardware specific.

From my plugin, how can I advertise whether the hardware supports this feature or not?
Is this to be done by invoking `sr_enable_module_feature` or `sr_disable_module_feature` from plugin initialization callback?

**Comment by michalvasko** [comment]
Hi,
yes, that seems to me is the correct solution. You can then easily learn whether the feature is enabled in any other code (callback) in your plugin and in any other *sysrepo* applications.
