### ISSUE TITLE
Installation of module not working

### ISSUE THREAD

**Issue by Jakob933** [sysrepo/sysrepo#2152]
Hi,

we were working with the docker image sysrepo/sysrepo-netopeer2:iop without problems but with the latest version we are running in some issues. 

When we are trying to install a module with `sysrepoctl -v3 -a -i /etc/sysrepo/data/pg.yang` error message `sysrepoctl error: Cannot apply changes because of existing connections` appears. How can we remove the connections or how can we install the module correctly? Based on other tickets the tags `-v3 -a -i` seemed the best option for us because otherwise the installation is just scheduled but not applied.

P.s.: Some colleagues used to work with sysrepo/sysrepo-netopeer2:iop version but this doesn't seem to exist anymore?

Thanks for your help and sorry for the beginner questions, we are newbies in this project.

**Comment by michalvasko** [comment]
Hi,
you most likely have *netopeer2-server* running (which always has a *sysrepo* connection) so simply stop it, install the module, and then start it again.

**Comment by Jakob933** [comment]
Thanks for the answer Michal but how can i stop it? I just started the docker via `docker run -d --name test-netconf -p 830:830 -p 6513:6513 sysrepo/sysrepo-netopeer2:latest` and entered the container to install the module.

**Comment by michalvasko** [comment]
Just send `SIGINT` to the process using `kill`, find its PID using `ps`, for example.

**Comment by eli-halych** [comment]
There is an issue related with the installation of a module in the :latest version of the container.

Based on what's available on the web and in the :legacy version of the container, we'd install the module like this:
`sysrepoctl -i -g /path/pg.yang`

And then the module is installed if we check in `sysrepoctl -l`

But in the :latest this way has problems:
1. Flag `-g` gives `sysrepoctl error: Redundant parameters /path/pg.yang`
2. Removing `-g` succeeds, however when checking with `sysrepoctl -l` the model is not installed, it is just N(New) `sample-plugin  | 2016-09-18 | N |` . The module is apparently scheduled for installation. When the container is restarted manually with `docker restart CONTAINER_ID`, the plugin is installed.

Can you @michalvasko  please help to understand what causes the module to get installed only after the container is restarted and not right after sysrepo -i is ran?

**Comment by michalvasko** [comment]
Hi,
this information is available [here](https://netopeer.liberouter.org/doc/sysrepo/master/schema.html). Other than that I suggest you also use `-v3` parameter for all *sysrepoctl* calls so that you see what is happening and why it is happening. Also, you may want to use `-a` parameter.

**Comment by Jakob933** [comment]
Thanks Michal, installation is now working after restarting container. Last thing, when we apply config file with `edit-config --target running --config=/etc/sysrepo/yang/pg-data.xml` we run into an issue `message:  Access to the data model "sample-plugin" is denied because "netconf" NACM authorization failed.` Any hint to solve this?

**Comment by michalvasko** [comment]
You will find a hint [here](https://github.com/CESNET/Netopeer2/#nacm). For more details you should look into [ietf-netconf-acm](https://github.com/CESNET/netopeer2/blob/master/modules/ietf-netconf-acm%402018-02-14.yang) YANG module directly.

**Comment by Jakob933** [comment]
Thanks Michal, it worked. Just needed to login as root. Issue is solved, ill close the ticket.
