### ISSUE TITLE
oper data callback arguments

### ISSUE THREAD

**Issue by syyyr** [sysrepo/sysrepo#2153]
Hi, I have a question about how I should work with operational data callbacks. Consider this example:
```cpp
#include <unistd.h>
#include <iostream>
#include <sysrepo-cpp/Session.hpp>

struct MyCallback : public sysrepo::Callback {

    int oper_get_items(sysrepo::S_Session session, const char *module_name, const char *path, const char *request_xpath,
            uint32_t request_id, libyang::S_Data_Node &parent, void *private_data)
    {
        std::cerr << "path" << " = " << path << "\n";
        if (request_xpath) {
            std::cerr << "request_xpath" << " = " << request_xpath << "\n";
        }
        return SR_ERR_OK;
    }
};

int main(int argc, char* argv[])
{
    sr_log_stderr(SR_LL_INF);
    auto conn = std::make_shared<sysrepo::Connection>();
    auto sess = std::make_shared<sysrepo::Session>(conn, SR_DS_OPERATIONAL);
    auto sub = std::make_shared<sysrepo::Subscribe>(sess);
    auto cb = std::make_shared<MyCallback>();
    sub->oper_get_items_subscribe("oven", "/oven:oven", cb);

    auto data = sess->get_data("/oven:oven/temperature");
    return 0;
}
```
```yang
module oven {
    yang-version 1.1;
    prefix aha;
    namespace "http://example.com";

    container oven {
        config false;
        leaf temperature {
            type int32;
            config false;
        }
        leaf power {
            type int32;
            config false;
        }
    }
}
```
The documentation says that the `xpath` argument:
1) is the same as the one I used for subscribing
2) identifies which subtree I should provide

So that means I have no idea what the user wants from that argument I can look at what the `request_path` contains, but that path could contain preprocessed stuff like `/oven:oven/temperature//.`, so no use of that either (and it could also be NULL). Does this mean that I should always provide everything I have inside this subtree?
Side note: Legacy sysrepo worked a little differently, the callback was called multiple times with all of the subtrees that the user ordered.

**Comment by michalvasko** [comment]
Hi,
yes, in general you should always provide all the data that you subscribed for. `request_xpath` is there only for possible optimizations, so you can skip some data if you know they are not necessary but as you said, it may often be too complex to process the path.

Also, you are right that it is different from the old *sysrepo*, which usually caused the callback to be called way too many times, hence this change. However, nothing prevents you from emulating the exact same behavior by subscribing to each subtree separately and providing the data for each level individually. In that case *sysrepo* will not call some callbacks if it was able to decide that their data would get filtered out anyway. But as I said before, it is a really complex task so it works only for simpler paths.

**Comment by syyyr** [comment]
Hi,
okay then. I'll stick to providing all data.

One more question: in the old sysrepo, when you subscribed with dp_get_items, the callback would be called only for state data. But now, the callback is called oper_get_items and is called for every get_items on the operational datastore, so state and also enabled config nodes. Is it possible for the callback to be only callled for state data?

**Comment by michalvasko** [comment]
Well, it is always called for whatever you subscribed for, you can always subscribe only to the state data subtrees (albeit you may need to subscribe to several subtrees instead of one). You can also use [SR_SUBSCR_OPER_MERGE](https://netopeer.liberouter.org/doc/sysrepo/master/group__subs__api.html#ggac91898627ad5aeb589e6a3993a697d14ad8c77539582e1de78f57e256299ea138) and provide only state data, then only those will be merged and you will get the behavior you want.

**Comment by jktjkt** [comment]
Ah, I thought that `SR_SUBSCR_OPER_MERGE` is somehow related to push subscriptions (keeping some data within sysrepo in between these callbacks).

**Comment by michalvasko** [comment]
Hm, not sure why the confusion, it is a subscription flag so it can only be used for pull subscriptions. But if you have an idea how to improve the docs, let me know.

**Comment by syyyr** [comment]
Okay, SR_SUBSCR_OPER_MERGE works for me, thanks.
