### ISSUE TITLE
Subscribing to /ietf-netconf:close-session

### ISSUE THREAD

**Issue by matkocc** [sysrepo/sysrepo#2156]
Hi,
    I am using sysrepo 0.7.8 and want to know if I can subscribe to close-session rpc from ietf-netconf module? If not, can you suggest any way to make sysrepo know if netconf session(s) is (are) closed by close-session rpc and, in general, is there a way for sysrepo to be aware of netconf session(s) status? 
Thanks,
    Matko

**Comment by michalvasko** [comment]
Hi,
you cannot subscribe to `close-session` RPC but you can subscribe to `netconf-session-end` notification instead. Should get you the same behavior including cases when the session is not closed by `close-session` but even `kill-session` or some errors.

**Comment by matkocc** [comment]
Hi Michal,

    I noticed that sometimes netopeer server didn't send netconf-session-end notification when session goes down and session isn't removed from /ietf-netconf-monitoring:netconf-state/sessions/session as well.
I also tried it on newer sysrepo (v1.4.70) and netopeer server (1.1.39) and same problem occured. Should I open a new issue for the new netopeer2-server/sysrepo ?

Thanks,
    Matko

**Comment by michalvasko** [comment]
Yes, if the notification was not generated in the current *sysrepo*/*netopeer2*, please create an issue with a detailed description of the use-case.
