### ISSUE TITLE
Question on supplying leafref in a notification

### ISSUE THREAD

**Issue by bbergquist0930** [sysrepo/sysrepo#2157]
I sent email to "sysrepo-devel@sysrepo.org" but did not see a response but it may have been filtered out on my end, so I am reposting this here.

I have this YANG module (fragment) 
```yang
    list ports {
        key "port-id";    
        description "Configuration and status data for physical ports";
   

        leaf port-id {     
            type identityref {
                base canoga-tsx-types:canoga-tsx-port-id;
            }
            description "Port id";   
        }                 
   
        leaf admin-state { 
            type canoga-tsx-types:enable-disable;
            description "Administrative state of the port";
        }

        leaf link-state {  
           config false;
           type enumeration {        
                enum "Down";
                enum "Up";
           }               
           description "Operational State of the Link";
        }                      
...
    notification port-state-change {
        description       
        "The operational link state of the port has changed.";     
        leaf port-id {
             type leafref {
                 path "/canoga-tsx-ports:ports/port-id";
             }                                                         
        }
        leaf link-state {
             type leafref {
                 path "/canoga-tsx-ports:ports/link-state";
             }                                           
        }    
        leaf admin-state {           
             type leafref {
                 path "/canoga-tsx-ports:ports/admin-state";
             }                 
        }                 
    }                         
```
Using the 'sr_event_notif_send' API, what data type is used for the value and is the value the complete path to the referenced leaf? I see how not to do it in the "test_notif.c" file "test_simple", where there is an assertion that the leafref value for "/ops:notif3/list2[k='k']/l14" is poiting to a non-existing leaf, but there seems to be no example or test where it is pointing to an existing leaf. Also the test is referring to a scalar and not a list item. So what would change if the leafref is a list item as in my case?

I am getting an error

libyang[0]: Leafref "/canoga-tsx-ports:ports/port-id" of value "canoga-tsx-types:port-1" points to a non-existing leaf. (path: /canoga-tsx-ports:port-state-change/port-id)"

**Comment by michalvasko** [comment]
Hi,
your leafref still points to a leaf, it does not matter that it is in a list. The problem here is exactly what the message says, the lefref target does not exist. An instance if the list with `port-id` with the specific value must exist in the `operational` datastore for the validation to pass. How to get data there is written [here](https://netopeer.liberouter.org/doc/sysrepo/master/index.html#oper_ds). To check that the data are really there you can use `sysrepocfg -d operational -X`.

**Comment by koala027** [comment]
Hi michalvasko, since we encounter the same issue in our project, is there any examples for our reference? thanks a lot.

btw, the port-id is rw type (config data), how to write those rw types data into operatioal datastore? thanks a lot

**Comment by michalvasko** [comment]
Look into the documentation I posted in my previous reply, you will find all the relevant information there. There are some examples in the repository, I trust that you are able to find them but they are rather simple so probably not too useful for this case.
