### ISSUE TITLE
higher-layer-if and lower-layer-if

### ISSUE THREAD

**Issue by som-1981** [sysrepo/sysrepo#2158]
Hello,
I was checking on higher-layer-if and lower-layer-if in ietf-interfaces.yang. But these are marked as "config false".
Wanted to understand where would the values be populated.
Thanks,
Som

**Comment by michalvasko** [comment]
Hi,
these data appear only in the `operational` datastore. How to get them there is explained [here](https://netopeer.liberouter.org/doc/sysrepo/master/index.html#oper_data).
