### ISSUE TITLE
Unsubscribe or Session Stop possibly not working 

### ISSUE THREAD

**Issue by esend7881** [sysrepo/sysrepo#2160]
## Issue & Details

I am running the global loop very similar to the [example here](https://github.com/sysrepo/sysrepo/blob/v1.4.70/bindings/python/examples/python_application_changes_example.py#L127 ) however I notice that when I restart the python application, sysrepo and/or netopeer stops working.

The way I get around it is by running `make sr_clean` in sysrepo/build and `make clean && make install` in netopeer2/build. After doing that, everything goes back to normal. 

My `netopeer2-server -v 2 -d` log looks like this:

> [INF]: SR: Published event "rpc" "/ietf-netconf:edit-config" with ID 1 priority 0 for 2 subscribers.
> [ERR]: SR: Callback event "rpc" with ID 1 processing timed out.
> [WRN]: SR: Event "rpc" with ID 1 priority 0 failed (Timeout expired).
> [ERR]: NP: Failed to send an RPC (User callback failed).
> [INF]: NP: Session 2: thread 2 event new RPC.
> [INF]: NP: Session 2: thread 2 event reply error.
> [INF]: LY: Resolving unresolved data nodes and their constraints...
> [INF]: LY: All data nodes and constraints resolved.
> [INF]: LY: Resolving unresolved data nodes and their constraints...
> [INF]: LY: All data nodes and constraints resolved.
> [INF]: SR: Published event "rpc" "/ietf-netconf:edit-config" with ID 2 priority 0 for 1 subscribers.
> [ERR]: SR: Opening "/opt/sysrepo/build/repository/sr_evpipe3" for writing failed (No such file or directory).
> [ERR]: NP: Failed to send an RPC (System function call failed).

Above that, no where in the log does it talk of errors.

I would hope that the following code would allow me to gracefully exit from python's sysrepo connection and then re-establish without having to mess with `make clean` and what-not.

```
        subscribe.unsubscribe()
        sess.session_stop()
```

## Environment:

- sysrepo 1.4.70
  - compiled with `cmake -DGEN_LANGUAGE_BINDINGS=ON ..`
- netopeer2 1.1.39 
  - compiled with `cmake -DSYSREPO_TIMEOUT=119 -DRPC_TIMEOUT=120 ..`
- libyang 1.0.184 
  - compiled with `cmake -DGEN_LANGUAGE_BINDINGS=ON ..`
- CentOS 7
- python 2.7.5/3.6.8

**Comment by michalvasko** [comment]
Well, it seems you have set a callback for `edit-config` but you are not calling its handler. I do not see much into the Python bindings but I believe you are supposed to go into the global loop to handle any subscriptions.

**Comment by esend7881** [comment]
I don't see any action inside the global loop in the example python files
provided.

Do you know of an example you could link me to that shows it done right?

**Comment by michalvasko** [comment]
[This](https://github.com/sysrepo/sysrepo/blob/master/bindings/python/examples/python_application_example.py#L78) is all I meant.
