### ISSUE TITLE
[HELP!] leaf node miss when sending a notification by sr_event_notif_send

### ISSUE THREAD

**Issue by UCNTFME** [sysrepo/sysrepo#2161]
I have a example code like below:
![image](https://user-images.githubusercontent.com/39721431/94262254-c4fe4780-ff65-11ea-9fac-96574f8a871a.png)
and the yang module defined here:

![image](https://user-images.githubusercontent.com/39721431/94262300-d8a9ae00-ff65-11ea-913c-d1d8c23f1bb5.png)

but the notification received at client side is like :
```
<notification xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
<eventTime>2020-09-25T11:26:43Z</eventTime>
<alarm xmlns="http://www.something.com/yzrt/yzmm/notifications">
<code>0x11100010</code>
</alarm>
</notification>
```

---------------------
you can find the **module** leaf node is missed 
is my code wrong? thanks a lot, can anybody help me on this?

**Comment by michalvasko** [comment]
Hi,
instead of
```C
leaf[0].type = SR_STRING_T;
```
you should have
```C
leaf[0].type = SR_ENUM_T;
```

**Comment by UCNTFME** [comment]
thank you,
but still have the issue..
is there any example code for this API?

**Comment by UCNTFME** [comment]
fix!
by adding **memset** line for leaf buffer.
```
...
 sr_val_t leaf[2];
 memset(leaf, 0, sizeof(leaf));
...
```
thank you..
