### ISSUE TITLE
Question: libyang2 support

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2162]
Hi,

I saw initial commits for libyang2 support in sysrepo (libyang2 branch). Do you have any estimation when will sysrepo use libyang2 on the devel branch?

Thanks

**Comment by michalvasko** [comment]
Hi,
the idea is to have *libyang2* with a high quality codebase and that is dragging for much longer than we expected so I am not sure when that will be finished. *sysrepo* migration should not take too long after that. I hope it will be migrated in a month at the latest.

**Comment by awesomenode** [comment]
Thanks for the info. Is this page reflects the status of libyang2? https://github.com/CESNET/libyang/milestone/1

**Comment by michalvasko** [comment]
Well, to some extent but not all the refactoring tasks were added there.
