### ISSUE TITLE
Delay in netopeer server sending rpc reply 

### ISSUE THREAD

**Issue by kresosi** [sysrepo/sysrepo#2167]
Hello,
I'm currently using netopeer2 server 0.7.12 and sometimes I experience a delay (10+ seconds) between sending a rpc and receiving reply to it. Is it possible for netopeer server to delay the processing of rpc requests for any reason? And also, is it possible to enable any additional traces on netopeer server to see when exactly the rpc request was received?

Thanks in advance,
Kresimir

**Comment by michalvasko** [comment]
Hi,
sorry, you are using the `legacy` version of *netopeer2* and we no longer provide support for it so I cannot help you.
