### ISSUE TITLE
Netconf notification replay support

### ISSUE THREAD

**Issue by mdoshi-com** [sysrepo/sysrepo#2168]
Hi,
Is netconf notification replay support provided by sysrepo?
If yes then for how long the notifications are queued in sysrepo?

Regards,
Meghna

**Comment by michalvasko** [comment]
Hi Meghna,
the replay support is provide per-module and it is off by default for all modules. You can enable it using `sysrepoctl` and you can see its current state in `sysrepoctl -l`, the `R` flag. Any stored notifications are kept permanently in a designated directory (can be changed and is printed during `cmake`). There is no clean-up mechanism implemented and there will be none in the near future. But it should not be too difficult to write your own script or something that will rotate the stored notifications if needed.

**Comment by mdoshi-com** [comment]
Hi Michal,
Ok thanks, we will explore and get back in case of any further queries.
Thanks.

Regards,
Meghna

**Comment by meghna-doshi** [comment]
Hi Michal,
One information, you mentioned earlier that adding a script to rotate notification is a feasible thing to do.
Can you provide any sample for this (rotation of notifications).

Regards,
Meghna

**Comment by michalvasko** [comment]
I cannot provide any sample as for it to work correctly you would need to implement quite a lot of new features. I have shared my thoughts in #2365.
