### ISSUE TITLE
shm_clean target ignores SYSREPO_SHM_PREFIX

### ISSUE THREAD

**Issue by igortern** [sysrepo/sysrepo#2173]
Hi,
shm_clean targets deletes /dev/shm/sr_*, ignore the configurable prefix
Regards,
Igor

**Comment by michalvasko** [comment]
Hi,
yeah, that is mostly intentional and I failed to add support for the environment variables anyway. They are just `cmake` custom targets, they do not mix well with the environment. But they should at least inform about what they are doing now.

**Comment by igortern** [comment]
Hi Michal,
it is possible to support env variables in custom targets using $$. ie, something like 
test "$$SYSREPO_SHM_PREFIX" != "" && rm -fr /dev/shm/$$SYSREPO_SHM_PREFIX* || rm -fr /dev/shm/sr_*
Anyway, if it is intentional, I'm closing the ticket
Thanks,
Igor
