### ISSUE TITLE
Parallel subscription not working in old version of sysrepo

### ISSUE THREAD

**Issue by paddyvgc** [sysrepo/sysrepo#2175]
Hi ,
I need to confirm one behaviour seen in old version of sysrepo.

I am doing dp_get_items_subscribe and module_change_cb on an yang module in a single thread.
So when I configure a leaf in the yang module , module_change_cb is called and at the same time when I go for a dp_get_items_subscribe  it will work only after finishing the module_change_cb. So the observation is like for the same yang module parallel subscription of module_change_cb and dp_get_items_subscribe will not work . Is this the same behaviour in latest sysrepo ?

Could you please confirm.

Thanks in advance,

**Comment by michalvasko** [comment]
Hi,
yes, this is one of the limitations of the `legacy` *sysrepo*, the current version supports proper concurrency and calling callbacks in parallel (if possible).
