### ISSUE TITLE
 sr_modinfo_edit_apply: Assertion `mod->state & MOD_INFO_REQ' failed.

### ISSUE THREAD

**Issue by Julian-younger** [sysrepo/sysrepo#2179]
Hi Michal,
   I want to delete mod1's data with  mod2's data deletion,but get a crash.
   I have two mods register using sr_module_change_subscribe function,like this:
   sr_module_change_subscribe(sess, mod_name, xpath, mod1_cb, NULL, priority, SR_SUBSCR_CTX_REUSE, &sub)，
   sr_module_change_subscribe(sess, mod_name, xpath, mod2_cb, NULL, priority, SR_SUBSCR_UPDATE|SR_SUBSCR_CTX_REUSE, &sub)，
in the function of mod2_cb, I  delete item of mod1's item using sr_delete_item, But when delete mod2's data ,I get the error like this:
 **sr_modinfo_edit_apply: Assertion `mod->state & MOD_INFO_REQ' failed.**

And I can delete the two separately. Could you give me some clues ?thanks!

**Comment by Julian-younger** [comment]
1.sysrepo-1.4.58       2.netopeer2-1.1.27      3.libyang-1.0.167    4.libnetconf2-1.1.24

**Comment by michalvasko** [comment]
Hi,
so what you are doing is that when a change of `mod2` is being processed, your callback with `SR_EV_UPDATE` is called and in this callback you delete some data of `mod1` (another module)?

**Comment by Julian-younger** [comment]
Thinks for reply!
I found a issue what I want to represent,like issuse #1899 
My original requirements is that I have many YANG modules (I can not change them ), I must use edit-config action to delete modules A  (Just have modules's XML),and then delete modules B,C,D with modules A;
And I can not finish this task just like issuse #1899 ,Could you give me some clues ?thanks!

**Comment by michalvasko** [comment]
What you can always do is wait until `SR_EV_DONE` event and them just issue a standard edit (`sr_delete_item`s followed by `sr_apply_changes`). But I am not sure what to do about your current use-case, it is not a problem to fix this assert but I believe it should not be supported because in a callback for a module you are meant to work only with data of that particular module.

**Comment by Julian-younger** [comment]
yes. I had tried to put a hook in the standard edit for particular module,using sr_delete_items followed by sr_apply_changes, it looks like work well so far,thanks a lot!
