### ISSUE TITLE
Is it possible to assign a binary/hexadecimal value as a configuration to a leaf with a "uint16 type" in a yang module?

### ISSUE THREAD

**Issue by aswin19996** [sysrepo/sysrepo#2180]
Following is an example of yang module leaf to which i am trying to configure a hexadecimal/binary value:

> leaf o-du-port-bitmask {
>       type uint16;
>       mandatory true;
>       description
>         "mask for eaxc-id bits used to encode O-DU Port ID";
>     }

The configuration ends in a error if i configure it in either of the ways:

`<o-du-port-bitmask>0xF000</o-du-port-bitmask>` (hexadecimal) 
or
`<o-du-port-bitmask>1111000000000000</o-du-port-bitmask>` (binary)

But if i convert these values to base10 (decimal) like: `<o-du-port-bitmask>61440</o-du-port-bitmask>`, there are no issues. 
Since i am trying to instantiate with the values as provided by O-RAN standards, is there any way to provide a binary/ hexadecimal values to a leaf with uint16 data type?

Thanks.

**Comment by michalvasko** [comment]
Only hexadecimal or octal notation can be used in YANG default values, otherwise only decimal ([ref](https://tools.ietf.org/html/rfc7950#section-9.2.1)).

**Comment by aswin19996** [comment]
Thanks Michal for the reply, 
So, after referring to the link specified i configure the value as follows:

`<o-du-port-bitmask>0xf000</o-du-port-bitmask>`

And i am getting an error like:

> ERROR
> 	type:     application
> 	tag:      operation-failed
> 	severity: error
> 	path:     /o-ran-uplane-conf:user-plane-configuration/low-level-tx-endpoints[name='txendpoint1']/e-axcid/o-du-port-bitmask
> 	message:  Invalid value "0xf000" in "o-du-port-bitmask" element.

I assume, is there any issues with representing the hexa value i.e., the '0x' ?

**Comment by michalvasko** [comment]
Like I told you before and as is written in the RFC, you cannot put hex numbers in the **XML configuration** file. You can only put them as default values directly in **YANG modules**.

**Comment by aswin19996** [comment]
Thanks Michal, 
So in a XML configuration file i will encode it in decimal value: `<o-du-port-bitmask>61440</o-du-port-bitmask>`
Since it is a bitmask value, the value seems bizarre, so is there any other way to represent this bitmask value in binary, especially in a configuration file?

**Comment by michalvasko** [comment]
There is no other if the type used is `uint16`. But if you used the specialized [bits](https://tools.ietf.org/html/rfc7950#section-9.7.2) type, you would specify the value as set bit names.

**Comment by aswin19996** [comment]
Thanks Michal
