### ISSUE TITLE
How do know the siblings of changing data nodes？

### ISSUE THREAD

**Issue by rydy** [sysrepo/sysrepo#2181]
Hi Michal,
    sr_get_change_next or sr_get_change_tree_next can only get the changed data nodes, I want to get its related data sibling nodes（no change）, what should I do?  
Refer to this link :https://github.com/sysrepo/sysrepo/issues/2135
thanks.

**Comment by michalvasko** [comment]
Like I wrote in the issue, you can use any getter function such as `sr_get_data()`.

**Comment by rydy** [comment]
ok. thanks.

**Comment by rydy** [comment]
> Like I wrote in the issue, you can use any getter function such as `sr_get_data()`.

I have one more question，How do  convert lyd_node to sr_val_t?

**Comment by michalvasko** [comment]
You can use `sr_tree_to_values` (in separate `values.h` header) or directly use `sr_get_items`. You can use any getter, like I said.

**Comment by rydy** [comment]
> You can use `sr_tree_to_values` (in separate `values.h` header) or directly use `sr_get_items`. You can use any getter, like I said.

i got it, thanks.
