### ISSUE TITLE
[ERR]: SR: Waiting on a conditional variable failed (sr_connect: Connection timed out)

### ISSUE THREAD

**Issue by aswin19996** [sysrepo/sysrepo#2187]
The Netopeer2-server upon restarting, throws this error message.

> [ERR]: SR: Waiting on a conditional variable failed (sr_connect: Connection timed out).
> [ERR]: NP: Connecting to sysrepo failed (Timeout expired).
> [ERR]: NP: Server init failed.
> [INF]: NP: Server terminated.

1. An attempt to fix this with `make shm_clean` command at sysrepo-master/build/ path prompts:

> make: /snap/cmake/549/bin/cmake: Command not found
> Makefile:989: recipe for target 'cmake_check_build_system' failed
> make: *** [cmake_check_build_system] Error 127

2. Also that, the `sysrepoctl -l` command , prompts with:

> [ERR]: Waiting on a conditional variable failed (sr_connect: Connection timed out).
> sysrepoctl error: Failed to connect (Timeout expired)

Any fixes for this , would be of great help.

Thanks.

**Comment by michalvasko** [comment]
Hi,
you have probably terminated the server with a SIGKILL, which is not supported yet. And it breaks the whole *sysrepo*. You can use `make sr_clean` to fix, `shm_clean` is only in `devel` for now.

**Comment by aswin19996** [comment]
shm_clean used to work, and off late it isn't working in my case.

And I have imported a set of O-RAN yang modules, and also have made some configurations to it. So if i use the sr_clean, will it take off all the configurations made and the modules imported?

**Comment by aswin19996** [comment]
Trying out with `make sr_clean` at /sysrepo-master/build path prompts the same error:

> make: /snap/cmake/549/bin/cmake: Command not found
> Makefile:989: recipe for target 'cmake_check_build_system' failed
> make: *** [cmake_check_build_system] Error 127

**Comment by michalvasko** [comment]
Oh, never mind, `shm_clean` should work just fine, except you have something wrong with your `cmake`, I cannot help you with that as I have never seen it. I suggest you rerun `cmake` after first removing all its files (clear the `build` directory).

**Comment by aswin19996** [comment]
Yet again the same issue persists even after clearing the build directory and re-creating it with the cmake steps.
After Clearing the building directory, i typed the following commands:

> mkdir build
> cd build
> cmake -D CMAKE_BUILD_TYPE:String="Release" ..
> make
> sudo make install

Should i try re-installing the sysrepo again?

**Comment by michalvasko** [comment]
No, I do not think that would help. Like I said, there is something wrong with your build environment, try searching for a solution, I am not able to help you with that.

**Comment by esend7881** [comment]
@michalvasko I just ran across this error in my testing. I am installing `sysrepo` via RPMs. How can I run this equivalent command if I don't have the source code folder available to run `shm_clean`?

**Comment by michalvasko** [comment]
Just do `# rm -rf /dev/shm/sr_*` and `# rm -rf /dev/shm/srsub_*`.

**Comment by jktjkt** [comment]
Just wanted to report here that we're getting this error, too. For us, the following scenario reliably reproduces it:

- start several services at once (see https://github.com/sysrepo/sysrepo/issues/2289),
- watch a connection for our "main" YANG module segfault via sysrepo, with an active subscription for modification,
- let systemd restart our service without purging the SHM
- stuff "works", as in "it can register for modifications" and "it can push ops data" or "it can register for a pull ops callback", but any attempt to modify the `running` DS of a module which was handled by a crashed subscription results in a timeout

**Comment by michalvasko** [comment]
Please try again with the latest `devel`. If reproducible/some other error occurs, I would try to fix it.
