### ISSUE TITLE
Q: Validate whole change set?

### ISSUE THREAD

**Issue by iljatab** [sysrepo/sysrepo#2188]
Hi Michal,

I'd like to ask for a suggestion.

Our application keeps many `sr_module_change_subscribe` subscriptions to different modules.

On SR_EV_CHANGE events every module callback validates changes, related to that module, and applies those on SR_EV_DONE.
So far so good.

However now I am adapting the app for a new use case where full validation cannot be done by each module separately.
Another, "global" validation step is required after all modules have processed their SR_EV_CHANGE events
.
Doing such validation in first SR_EV_DONE is not an option because changes cannot be rejected at that point.

So my questions is - is there any way from the configuration change callback to understand that "this is the last module's SR_EV_CHANGE event, after that only SR_EV_DONE will follow"?
In that case I could do global validation in this last SR_EV_CHANGE call and have an option to reject the changes.

Or maybe there is some hook/callback, unrelated to particular module, that is called after all SR_EV_CHANGE events but before SR_EV_DONE, and which can reject the changes?

Any your suggestions would be very helpful!

Ilja.

**Comment by michalvasko** [comment]
Hi,
well, *sysrepo* is strictly divided based on modules because it is efficient and they should follow the real devices they are managing, anyway. If that is not true in your case, there are no additional mechanisms you could use. Can you maybe share some more details about your use-case?

**Comment by iljatab** [comment]
Thanks for reply!

You are right, ideally modules should follow the real device internals.
However, users may prefer same YANG models used for different devices - this naturally make integration on user side easier.
So we end up using models that are quite different from underlying devices, say openconfig.

In this particular case there are two obstacles:

1. The different features of device should be programmed in a particular order.
This is OK by itself - during SR_EV_CHANGE we learn all changes in all modules and SR_EV_DONE can adjust actual programming order, taking inter-module dependencies into account.

2. We cannot fully validate the changes before trying to apply those.
Some errors can be detected only by doing the actual device programming.
Duplicating exactly same logic in the sysrepo callbacks is not always realistic or possible at all.

So given above items we have to:
(1) Run all SR_EV_CHANGE to compose a complete "device programming plan".
(2) Apply the plan to the device but still be able to reject the changes in case some programming step fails.
This means we cannot run step (2) in SR_EV_DONE.

Actually I came so far to two possible solutions:

1. Move our current SR_EV_CHANGE event callbacks to become SR_EV_UPDATE event callbacks.
Then on first SR_EV_CHANGE event we are already ready to program the device but still can reject changes.

or

2. Add a simple implementation of SR_EV_UPDATE event handler that will track the last module for which SR_EV_UPDATE was called before proceeding to calling SR_EV_CHANGE.
Then same last module's SR_EV_CHANGE handler can trigger device programming.
Of course this solution assumes that SR_EV_UPDATE and SR_EV_CHANGE events are called for modules in the same order.

What do you think, could it work?

Ilja.

**Comment by michalvasko** [comment]
What you are describing should work, I think, as a way of hacking it to make it work. When thinking about this problem in connection with the migration of *sysrepo* to new *libyang* version, general module priorities could be added to fix this. Would that help you or you need to get those priorities dynamically based on the changes?

**Comment by iljatab** [comment]
Thanks!

Yes, option (2) looks working OK so far for us and was trivial to implement.

I have still to think about priorities and how to do it in a generic way...
