### ISSUE TITLE
 'when' condition in rpc input

### ISSUE THREAD

**Issue by Julian-younger** [sysrepo/sysrepo#2189]
hi，michal，
    I have met a YANG file which has 'when' condition in rpc input,And  when the input service-type is EPL,and I got some error,Could you have some ideas?Thanks.
```yang
rpc create-eth-connection {
  input {
    leaf service-type {
      mandatory true;
      type acc-devm:service-type;
    }
    container eth-uni {
      leaf uni-ptp-name {
        type string;
      }
      container vlan-spec {
        when "../../service-type = 'EVPL'";
        leaf-list vlan-id {
          type uint64 {
            range "1..4094";
	  }
	}
	description "";
      }		
    }
  }
```

when I use the xml  followup,I get the wrong result,"ly ERROR: When condition "../../service-type = 'EVPL'" not satisfied. (create-eth-connection/eth-uni/vlan-spec)"

```XML
<create-eth-connection>
  <service-type>EPL</service-type>
  <eth-uni>
    <uni-ptp-name>port1</uni-ptp-name>
  </eth-uni>
</create-eth-connection>
```

when I use the xml  followup,the result is OK.

```XML
<create-eth-connection>
  <service-type>EVPL</service-type>
  <eth-uni>
    <uni-ptp-name>port1</uni-ptp-name>
  </eth-uni>
  <vlan-id> 100 </vlan-id>
</create-eth-connection>
```

ADD+++
When I use a 3rd netconf cli to connect netopeer2 server,the two XMLs work well, Does netopeer2 cli do some strict check?

**Comment by michalvasko** [comment]
Hi,
I do not understand what is the issue here. If you break the `when` condition, you get the correct error because the condition must be satisfied.

**Comment by Julian-younger** [comment]
Sorry for the wrong xml,the First one  keep the same,the second one is here. There is no container vlan-spec in the first one. In my opinion,the first one can't meet the condition  **when "../../service-type = 'EVPL'";**,so can get correct result as the same with the second,I am right?

```
<create-eth-connection>
  <service-type>EVPL</service-type>
  <eth-uni>
    <uni-ptp-name>port1</uni-ptp-name>
  </eth-uni>
<vlan-spec>
  <vlan-id> 100 </vlan-id>
  </vlan-spec>
</create-eth-connection>
```

**Comment by michalvasko** [comment]
Oh, I see what the problem is now. There is a problem in the YANG 1.1 specification regarding non-presence containers and their existence. Specifically, it is not clear when they do exist and when don't. In *libyang*, we treat them as special default values and they exist whenever their **parent exists**, in this case `eth-uni`. That is why the when is evaluated even if you do not explicitly create the container.

The most correct solution for this problem is to make the `vlan-spec` container presence. Then it will have to be created explicitly and will not be created otherwise.

**Comment by Julian-younger** [comment]
Can I understand that like this, When I use service-type = 'EPL', I also should put the  vlan-spec container and its child nodes here? But I cannot change the XML myself ,Has any workarounds for this problem?

```
<create-eth-connection>
  <service-type>**EPL**</service-type>
  <eth-uni>
    <uni-ptp-name>port1</uni-ptp-name>
  </eth-uni>
**<vlan-spec>
  <vlan-id> 100 </vlan-id>
  </vlan-spec>**
</create-eth-connection>
```

**Comment by michalvasko** [comment]
Well, this XML
```xml
<create-eth-connection>
  <service-type>EVPL</service-type>
  <eth-uni>
    <uni-ptp-name>port1</uni-ptp-name>
  </eth-uni>
  <vlan-id> 100 </vlan-id>
</create-eth-connection>
```
is definitely not valid and there is no workaround. Just that depending on the exact situation (and *libyang* parsing options used), the `vlan-id` node may be simply ignored or cause a parsing error.

**Comment by Julian-younger** [comment]
> Well, this XML
> 
> ```
> <create-eth-connection>
>   <service-type>EVPL</service-type>
>   <eth-uni>
>     <uni-ptp-name>port1</uni-ptp-name>
>   </eth-uni>
>   <vlan-id> 100 </vlan-id>
> </create-eth-connection>
> ```
> 
> is definitely not valid and there is no workaround. Just that depending on the exact situation (and _libyang_ parsing options used), the `vlan-id` node may be simply ignored or cause a parsing error.

Yes,the xml your quote is not valid. Here is the right one which I put in my later reply, **service-type = 'EVPL',**,  this one can work well.
```
<create-eth-connection>
  <service-type>EVPL</service-type>
  <eth-uni>
    <uni-ptp-name>port1</uni-ptp-name>
  </eth-uni>
<vlan-spec>
  <vlan-id> 100 </vlan-id>
  </vlan-spec>
</create-eth-connection>
```
My problem is that when I use the service-type = 'EPL', I get the error using the XML which I cannot give the container  vlan-spec and its child nodes like this:
<create-eth-connection>
  <service-type>EPL</service-type>
  <eth-uni>
    <uni-ptp-name>port1</uni-ptp-name>
  </eth-uni>
</create-eth-connection>

**Comment by michalvasko** [comment]
Okay, then like I said, the solution is to change `vlan-spec` to presence container (new *libyang* version will do that automatically). If you cannot change the YANG then I have no other advice for you, unfortunately.

**Comment by Julian-younger** [comment]
Ok, I get it.

I found a description in RFC7950,how to understand this?

7.14.2.  The "input" Statement

   The "input" statement, which is optional, is used to define input
   parameters to the operation.  It does not take an argument.  The
   substatements to "input" define nodes under the operation's input
   node.
  ........
   **If any node has a "when" statement that would evaluate to "false",
   then this node MUST NOT be present in the input tree.**

**Comment by michalvasko** [comment]
Like I said, it is not clear (not specified) when a non-presence container is present. Read the rest of my previous reply for more details.

**Comment by Julian-younger** [comment]
OK，I'll try to make some effort  to change YANG  or XML. Thanks for your great patience.
