### ISSUE TITLE
list without key entry

### ISSUE THREAD

**Issue by ani22del** [sysrepo/sysrepo#2192]
Hi Team,

I have a yang model of this format.

```yang
module test {
	namespace "urn:test";
	prefix f;

	grouping some-group {
		description
			"test grouping";
		leaf a {
			type uint16;
		}
		leaf b {
			type string {
				length "1..255";
			}
			mandatory true;
			description
				"list b";
		}
		list c {
			leaf name {
				type string {
					length "1..255";
				}
				mandatory true;
			}
			min-elements 1;
			max-elements 100;
		}
		leaf d {
			type string;
			mandatory true;
		}
	}

	container state {
		list state-info {
			uses some-group;
		}
		config false;
	}
}
```

And I am using operational callback example  oper_data_example.c code to get data for this yang. The list in this entry has no key element entry.
This is my code structure

```C
static int dp_get_items_cb(sr_session_ctx_t *session, const char *module_name, const char *xpath, const char *request_xpath,
		uint32_t request_id, struct lyd_node **parent, void *private_data)
{
	(void)session;
	(void)request_xpath;
	(void)request_id;
	(void)private_data;
    	sr_val_t *values = NULL;
	int rc;
	size_t count = 0;

	printf("\n\n ========== DATA FOR \"%s\" \"%s\" REQUESTED =======================\n\n", module_name, xpath);


	*parent = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(session)), "/test:state/state-info/a", "1", 0, 0);
	lyd_new_path(*parent, NULL, "/test:state/state-info/b", "2", 0, 0);
	lyd_new_path(*parent, NULL, "/test:state/state-info/c/name", "name1", 0, 0);
	lyd_new_path(*parent, NULL, "/test:state/state-info/c/name", "name2", 0, 0);
	lyd_new_path(*parent, NULL, "/test:state/state-info/c/name", "name2", 0, 0);
	lyd_new_path(*parent, NULL, "/test:state/state-info/d", "5", 0, 0);



	return SR_ERR_OK;
}

```

Whenever I am trying to get data from the netopeer-cli using the command:
get --filter-xpath /test:state//*
I am getting data in this xml format:

![Screenshot from 2020-10-24 15-21-14](https://user-images.githubusercontent.com/45091180/97078850-caa28800-160c-11eb-8350-3fc9ce6f5e51.png)

Whereas I am expecting data of this format:
![Screenshot from 2020-10-24 15-11-53](https://user-images.githubusercontent.com/45091180/97078816-7a2b2a80-160c-11eb-9a70-3584ae544140.png)

As there is no key element for the list file I am unable to understand how to get entry in the desired format. 
Also I have read on some sysrepo github issues that sysrepo does not support "list with no key" format.
Please help me out to debug this issue

**Comment by michalvasko** [comment]
When creating instances of a key-less key, you should always use the instance position (instead of key values).
```C
*parent = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(session)), "/test:state/state-info[1]/a", "1", 0, 0);
lyd_new_path(*parent, NULL, "/test:state/state-info[1]/b", "2", 0, 0);
lyd_new_path(*parent, NULL, "/test:state/state-info[1]/c/name", "name1", 0, 0);
lyd_new_path(*parent, NULL, "/test:state/state-info[1]/c/name", "name2", 0, 0);
lyd_new_path(*parent, NULL, "/test:state/state-info[1]/c/name", "name2", 0, 0);
lyd_new_path(*parent, NULL, "/test:state/state-info[1]/d", "5", 0, 0);
```

**Comment by adamzyg** [comment]
I also have the same question, now I see. Thanks @michalvasko.

**Comment by k7k** [comment]
Hi @michalvasko 

I have two queries as below. For ease of understanding examples were given with above test yang reference only.

1. After using instance position for key-less list instance creation below xpath output is creating each leaf as an entry under list.

![image](https://user-images.githubusercontent.com/6839529/98817124-a8539b80-244f-11eb-91e9-7d4008585aec.png)

where as output format for xpath "get --filter-xpath /test:state/state-info[1]" is as expected. Could you please help to get proper format output for "get --filter-xpath /test:state/state-info/*" xpath as well.

2. From the above output we can see, another entry of a list is not shown in output if a leaf "name-value" pair is same as other entry. Though list entries are on different index it is not showing.

    lyd_new_path(*parent, NULL, "/test:state/state-info[1]/c[1]/name", "name11", 0, 0);
    lyd_new_path(*parent, NULL, "/test:state/state-info[1]/c[2]/name", "name11", 0, 0);
    lyd_new_path(*parent, NULL, "/test:state/state-info[1]/c[3]/name", "name22", 0, 0);

Regards,
Kavitha

**Comment by michalvasko** [comment]
Please go through the issue #2210 carefully and try to understand it all. If you then still have any questions, feel free to ask.
