### ISSUE TITLE
Send notification with sysrepo version 0.7.7

### ISSUE THREAD

**Issue by SilviaFc** [sysrepo/sysrepo#2194]
Hi,
I have installed the version 0.7.7 of sysrepo.
I have to send a notification to a client that has subscribed that when a specific parameter of my configuration changes.
In the last version I saw that there is an example (notif_send_example.c) but I cannot compile it with my version. Moreover, I cannot find any documentation related to this version.

Does someone have an example or suggestions?
Thanks
Silvia

**Comment by michalvasko** [comment]
Even this legacy version has its documentation and you can generate it with the standard `make doc` command. You must have `doxygen` installed.
