### ISSUE TITLE
Unable to set list item of a tree

### ISSUE THREAD

**Issue by jeffreymarius** [sysrepo/sysrepo#2197]
Hi,

This is the XML configuration I am using - 
```
<sync xmlns="urn:o-ran-sync">
  <ptp-config>
    <domain-number>12</domain-number>
    <accepted-clock-classes>
      <clock-classes>2</clock-classes>
    </accepted-clock-classes>
    <accepted-clock-classes>
      <clock-classes>3</clock-classes>
    </accepted-clock-classes>
    <ptp-profile>G_8275_1</ptp-profile>
    <g-8275-1-config>
      <multicast-mac-address>NONFORWARDABLE</multicast-mac-address>
      <delay-asymmetry>9</delay-asymmetry>
    </g-8275-1-config>
    <g-8275-2-config>
      <local-ip-port>eth0</local-ip-port>
      <master-ip-configuration>
        <local-priority>1</local-priority>
        <ip-address>192.168.0.2</ip-address>
      </master-ip-configuration>
      <log-inter-sync-period>-1</log-inter-sync-period>
      <log-inter-announce-period>0</log-inter-announce-period>
    </g-8275-2-config>
  </ptp-config>
</sync>
```

I am able to set the separate leaf within the containers but however, I am having issue when I am setting the parameters of the list. Now according to the Yang model, the list "accepted-clock-classes" and "master-ip-configuration" are Read-Write and also all the leafs under them are "Read-Write". However, when I try setting the leaf within the list I am getting errors. I am actually using the /example sr_set_item binary we receive with the Sysrepo code.

First I try to get the tree, in order to know the correct xpath,
./sr_get_items_example /o-ran-sync:sync/ptp-config/accepted-clock-classes/clock-classes
Application will get "/o-ran-sync:sync/ptp-config/accepted-clock-classes/clock-classes" from "running" datastore.
/o-ran-sync:sync/ptp-config/accepted-clock-classes[clock-classes='2']/clock-classes = 2
/o-ran-sync:sync/ptp-config/accepted-clock-classes[clock-classes='3']/clock-classes = 3

And then using the same xpath of Get filter I try to set ,
./sr_set_item_example /o-ran-sync:sync/ptp-config/accepted-clock-classes[clock-classes='2'] 1
Application will set "/o-ran-sync:sync/ptp-config/accepted-clock-classes[clock-classes=2]" to "1".
[ERR]: Unexpected character(s) '2' ("2]").
[ERR]: Invalid datastore edit.

./sr_set_item_example /o-ran-sync:sync/ptp-config/g-8275-2-config/master-ip-configuration[local-priority='1']/ip-address 192.168.0.1
Application will set "/o-ran-sync:sync/ptp-config/g-8275-2-config/master-ip-configuration[local-priority='1']/ip-address" to "192.168.0.1".
[ERR]: Invalid arguments - list without keys (lyd_find_sibling()).

I have tried some combination with the "Key" fields but no luck. It seems I am not able to set the list items programatically.

Please let me know if I am using wrong xfilter path for setting.
Your help is highly appreciated.

**Comment by michalvasko** [comment]
In the first case, the app output gives away the problem
```
./sr_set_item_example /o-ran-sync:sync/ptp-config/accepted-clock-classes[clock-classes='2'] 1
Application will set "/o-ran-sync:sync/ptp-config/accepted-clock-classes[clock-classes=2]" to "1".
```
specifically `clock-classes=2`, the `'` were lost in shell processing. Enclose the whole XPath in `"` to fix.

In the second case this seems to be fine (reason being unknown to me) but there is some other problem that I am not sure about. I would need to know what keys does `master-ip-configuration` list have.

**Comment by jeffreymarius** [comment]
Wow..thanks Michal. Its the quotes `"` issue only. Its working now. I am able to set for `accepted-clock-classes and the master-ip-configuraion` as well.

./sr_set_item_example "/syn_module:sync/ptp-config/g-8275-2-config/master-ip-configuration[local-priority='1']/local-priority" 1
Application will set "/syn_module:sync/ptp-config/g-8275-2-config/master-ip-configuration[local-priority='1']/local-priority" to "1"

./sr_set_item_example "/syn_module:sync/ptp-config/accepted-clock-classes[clock-classes='200']/clock-classes" 200
Application will set "/syn_module:sync/ptp-config/accepted-clock-classes[clock-classes='200']/clock-classes" to "200"
