### ISSUE TITLE
when subscribe for the notification, Callback to be not called for the delivery of a notification.

### ISSUE THREAD

**Issue by panniruram** [sysrepo/sysrepo#2198]
Hi,

When trying to subscribe the notification, callback will not be called. but subscription was succeed.
Please help what is the issue, why not able to call callback when notify subscription. 

sample plugin:
```C
sr_plugin_init_cb(sr_session_ctx_t *session, void **private_data)
{
 rc = sr_event_notif_subscribe(session, "o-ran-supervision", "/o-ran-supervision:supervision-notification", 0, 0, notif_cb, NULL, 0, &subscription);
    if (rc != SR_ERR_OK) {
        goto error;
    }
}

static void
notif_cb(sr_session_ctx_t *session, const sr_ev_notif_type_t notif_type, const char *path, const sr_val_t *values, const size_t values_cnt, time_t timestamp, void *private_data)
{
    SRP_LOG_DBGMSG("SUPERVISION: notif_cb entring.....");
}
```
Above notify_cb not hitting.
netopeer2-cli:
```
> subscribe --filter-xpath /o-ran-supervision:supervision-notification
OK
> 
```
Yang:
```yang
module o-ran-supervision {
 notification supervision-notification {
    description
      "Notification to indicate that NETCONF management interface is up
      and also indicate the values of the timers for this NETCONF session";

  }
}
```

**Comment by michalvasko** [comment]
Hi,
that all seems fine, you have only subscribed to the notifications this way, so your callback will be called every time the notification is received. You can simply send it using `notif_send_example` app from the examples.

**Comment by panniruram** [comment]
@michalvasko  Thanks for the quick reply.

i have one more query regarding "sr_event_notif_send".
1. How to get event notify subscription list(Any event notif has subscribed). Do we have any API to get notify subscribe list ?
2. How to avoid below log(when there is no notify subscribers).
    [INF]: "There are no subscribers for "o-ran-supervision" notifications."

 rc = sr_event_notif_send(sess, "/o-ran-supervision:supervision-notification", NULL, 0);
                if (rc != SR_ERR_OK)
                {
                    SRP_LOG_ERR("SUPERVISION:  notification generation failed: %s.", sr_strerror(rc));
                }

Above code will start during the "sr_plugin_init_cb" function part of thread.

**Comment by michalvasko** [comment]
1. You can see them in the data of an internal module. Try `sysrepocfg -X -m sysrepo-monitoring -d operational`. Note that since the data include some sensitive information, access to them is quite restricted by default.
2. Well, you must subscribe to the notification before you send it with `sr_event_notif_subscribe` or `sr_event_notif_subscribe`.

**Comment by panniruram** [comment]
@michalvasko ,  we need subscriber list before sending "sr_event_notif_send" if any one subscribed or not. 
                           sr_event_notif_subscribe not handling part of my implementation. but should know the subscriber list before sending. if any event subscribed then only we will send notif otherwise don't want to send notif.    
   if there is no subscribe also send is happening "sr_event_notif_send" and getting below log message. so want avoid below log message such scenarios.
 "[INF]: There are no subscribers for "o-ran-supervision" notifications."
 
do we have any API "sr_notif_find_subscriber" like to get subscriber list which is not exposed.

**Comment by michalvasko** [comment]
> if any event subscribed then only we will send notif otherwise don't want to send notif.

That is not really the intended use and I have no idea why the INF message matters so much to you but you can check the subscribers, if you really want to. I have mentioned a simple way of getting and printing the `sysrepo-monitoring` data using *sysrepocfg*. You can do the same in API by calling `sr_get_data("/sysrepo-monitoring:sysrepo-state")` and then inspecting them for the information you want.

**Comment by panniruram** [comment]
@michalvasko 

Not able to get notif subscriber list
rc = sr_get_data(sess, "/o-ran-supervision:supervision-notification", 0, 0, 0, &data);
SRP_LOG_ERR("SUPERVISION:  DATA****: %s.", data);

output:
[ERR]: plugin: SUPERVISION:  DATA****: (null).     always

Yang:  
module o-ran-supervision {
 notification supervision-notification {
    description
      "Notification to indicate that NETCONF management interface is up
      and also indicate the values of the timers for this NETCONF session";

  }
}

**Comment by michalvasko** [comment]
I told you the command to use, the xpath should be `/sysrepo-monitoring:sysrepo-state`. Those are metadata that have information about current subscriptions, among other things.
