### ISSUE TITLE
libpcre.so.3 for sysrepo

### ISSUE THREAD

**Issue by mdoshi-com** [sysrepo/sysrepo#2203]
Hi,
I have a unbuntu server :
`5.4.0-52-generic #57~18.04.1-Ubuntu SMP Thu Oct 15 14:04:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

when i try to run sysrepoctl, following error comes, though ./lib/x86_64-linux-gnu/libpcre.so.3 is present. How can i change sysrepo to use libpcre.so.3 instead of libpcre.so.1

`/usr/local/bin/sysrepoctl: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory`

Regards,
Meghna

**Comment by michalvasko** [comment]
*libcpre* is searched for during `cmake` of *libyang* so whatever was found them will be used for all the other projects. Also, I am not able to say for certain based on SO names, but *libyang* still requires the original PCRE, not PCRE2, which may be the difference.

**Comment by rkrejci** [comment]
Try to update the linker's cache: `sudo /sbin/ldconfig -v`

**Comment by mdoshi-com** [comment]
Hi,
Thanks, will try this and also understood that this is done during cmake time.

Regards,
Meghna
