### ISSUE TITLE
SR_EDIT_STRICT: new leaf-list element in an existing list

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2204]
Hi,

We have an issue when deleting the leaf-list then adding a new leaf-list element under an already existing list (sr_set_item with SR_EDIT_STRICT). We get the error that the node for the list to be created already exists which is true. But the leaf-list element does not exist.

Model example:
list some-list {
  key "some-key";
  
  leaf some-key {
    type string; // e.g.
  }

  leaf-list some-leaf-list {
    type string; // e.g.
  }
}

The error:
Node "some-list" to be created already exists.
Applying operation "create" failed.

sysrepo version: 1.4.88
libyang version: 1.0.202

Is this intentional?

Thanks

**Comment by michalvasko** [comment]
Yes, there are some limits imposed because of how this is implemented. You should always be able to use `SR_EDIT_ISOLATE` in these cases.

**Comment by awesomenode** [comment]
Thanks for the quick reply it worked. :)
