### ISSUE TITLE
Building RPMs and installing them - Problems

### ISSUE THREAD

**Issue by esend7881** [sysrepo/sysrepo#2208]
## Issue & Details

I am developing a netconf client/server system with sysrepo, libyang (as well as libnetconf2 and netopeer2) but I am having some issues installing the RPMs. 

Before diving into my issue, I should note: **my goal is just to install libyang, sysrepo (and eventually libnetconf/netopeer2) as RPMs instead of compilation. If there is a guide to doing this, that may help answer my question. But for now, I am trying to create the RPMs manually.**

Here are the steps I follow:

### Step 1 - Build Libyang and create RPMs

Here is my code which builds it out:
```
git clone https://github.com/CESNET/libyang --branch v1.0.184 --depth 1 --single-branch /opt/libyang
mkdir -p /opt/libyang/build
cd /opt/libyang/build
cmake -DGEN_LANGUAGE_BINDINGS=ON .. && make && make install

/opt/libyang/build/build-packages/local-rpm.sh 
```
This returns successfully and produces:
```
# ll /opt/libyang/build/rpms/RPMS/x86_64/ -lah
total 6.1M
drwxr-xr-x. 2 root root 4.0K Nov  4 13:49 .
drwxr-xr-x. 3 root root   20 Nov  4 13:49 ..
-rw-r--r--. 1 root root 409K Nov  4 13:49 libyang1-1.0.184-0.x86_64.rpm
-rw-r--r--. 1 root root 5.1M Nov  4 13:49 libyang1-debuginfo-1.0.184-0.x86_64.rpm
-rw-r--r--. 1 root root  64K Nov  4 13:49 libyang-cpp1-1.0.184-0.x86_64.rpm
-rw-r--r--. 1 root root  16K Nov  4 13:49 libyang-cpp-devel-1.0.184-0.x86_64.rpm
-rw-r--r--. 1 root root  92K Nov  4 13:49 libyang-devel-1.0.184-0.x86_64.rpm
-rw-r--r--. 1 root root  42K Nov  4 13:49 libyang-tools-1.0.184-0.x86_64.rpm
-rw-r--r--. 1 root root 481K Nov  4 13:49 python3-yang1-1.0.184-0.x86_64.rpm
```

### Step 2 - Build out sysrepo and create RPMs:
```
git clone https://github.com/sysrepo/sysrepo.git --branch v1.4.70 --depth 1 --single-branch /opt/sysrepo
mkdir -p /opt/sysrepo/build
cd /opt/sysrepo/build
cmake -DGEN_LANGUAGE_BINDINGS=ON -DCMAKE_BUILD_TYPE:String="Release" .. && make && make install
```
Next I plan to run `/opt/sysrepo/build/build-packages/local-rpm.sh` however, when I do the script complains about not finding libyang (even though I already build it out). So I am doing a `yum localinstall` of the RPMs produced above:
```
yum -y localinstall /opt/libyang/build/rpms/RPMS/x86_64/libyang1-1.0.184-0.x86_64.rpm
yum -y localinstall /opt/libyang/build/rpms/RPMS/x86_64/libyang-devel-1.0.184-0.x86_64.rpm
yum -y localinstall /opt/libyang/build/rpms/RPMS/x86_64/libyang-cpp1-1.0.184-0.x86_64.rpm
yum -y localinstall /opt/libyang/build/rpms/RPMS/x86_64/libyang-cpp-devel-1.0.184-0.x86_64.rpm
yum -y localinstall /opt/libyang/build/rpms/RPMS/x86_64/python3-yang1-1.0.184-0.x86_64.rpm
```
But, I still get an error when running this:
```
/opt/sysrepo/build/build-packages/local-rpm.sh
###
error: Failed build dependencies:
        python3-yang >= 1.0.182 is needed by sysrepo-1.4.70-0.x86_64
        swig >= 3.0.12 is needed by sysrepo-1.4.70-0.x86_64
```
I know I installed `python3-yang` from the libyang rpm folder and my version of swig is 3.0.12 exactly on the machine, so in the `local-rpm.sh` file, I change the `rpmbuild` command by adding in  `--nodeps` argument:  

```rpmbuild --ba rpms/SPECS/sysrepo.spec --define "%_topdir /opt/sysrepo/build/rpms" --nodeps```

With the new argument added:
```
/opt/sysrepo/build/build-packages/local-rpm.sh
### 
+ umask 022
+ cd /opt/sysrepo/build/rpms/BUILD
+ cd sysrepo-master
+ /usr/bin/rm -rf /opt/sysrepo/build/rpms/BUILDROOT/sysrepo-1.4.70-0.x86_64
+ exit 0
```
This appears to work!

### Step 3 - In a new VM, Only install the RPMs. 

In a new VM, I want to take those created RPM files and install libyang and sysrepo. In the production system, we can't have `make`, `cmake`, and `gcc` type programs installed. 
```
yum -y localinstall /libyang-rpms/libyang1-1.0.184-0.x86_64.rpm
yum -y localinstall /libyang-rpms/libyang-devel-1.0.184-0.x86_64.rpm
yum -y localinstall /libyang-rpms/libyang-cpp1-1.0.184-0.x86_64.rpm
yum -y localinstall /libyang-rpms/libyang-cpp-devel-1.0.184-0.x86_64.rpm
yum -y localinstall /libyang-rpms/python3-yang1-1.0.184-0.x86_64.rpm
yum -y localinstall /libyang-rpms/libyang1-debuginfo-1.0.184-0.x86_64.rpm
yum -y localinstall /libyang-rpms/libyang-tools-1.0.184-0.x86_64.rpm

### All the above do install successfully, however all of the following fail:
yum -y localinstall /sysrepo-rpms/sysrepo-1.4.70-0.x86_64.rpm
yum -y localinstall /sysrepo-rpms/sysrepo-devel-1.4.70-0.x86_64.rpm
yum -y localinstall /sysrepo-rpms/sysrepo-cpp-1.4.70-0.x86_64.rpm
yum -y localinstall /sysrepo-rpms/sysrepo-cpp-devel-1.4.70-0.x86_64.rpm
yum -y localinstall /sysrepo-rpms/python3-sysrepo-1.4.70-0.x86_64.rpm
```
**Each one gives an error like:**
```
Error: Package: sysrepo-1.4.70-0.x86_64 (/sysrepo-1.4.70-0.x86_64)
           Requires: libyang >= 1.0.182
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

Even when I try `--skip-broken` it doesn't work. 
```
yum -y localinstall /vagrant/sysrepo-rpms/sysrepo-1.4.70-0.x86_64.rpm --skip-broken
Packages skipped because of dependency problems:
    sysrepo-1.4.70-0.x86_64 from /sysrepo-1.4.70-0.x86_64
```

So this is where I am stuck. I can create the RPMs but the sysrepo RPMs are not able to install. It seems sysrepo's install cannot detect that libyang >= 1.0.182 has been installed. In fact I am installing libyang 1.0.184. Maybe it has to do with the `--nodeps` argument added to the `rpmbuild` call? 

Beyond this, I can tell you that when I compile these programs manually, they do work so I know this is possible.

Another way to ask the question is: **how do you properly product the libyang, sysrepo (and eventually libnetconf2) rpms and ensure they install with no errors?** If I have the answer to that question, the above is irrelevant. 

## Environment:

- sysrepo 1.4.70
- libyang 1.0.184 
- CentOS 7
- python 2.7.5/3.6.8

**Comment by michalvasko** [comment]
Hi,
firstly, do you really need to build your own packages? They can be downloaded from links in README of each project, or you can find them all [here](https://download.opensuse.org/repositories/home:/liberouter/).

But as for the errors, it is possible there is a problem with package names because they were changed fairly recently. I will look at that before the next release.

**Comment by psch-k** [comment]
Hi,
just a hint: The package name of libyang is 'libyang**1**' (since July 15th, 2020, therefore valid for version 1.0.184).
The package name change from 'libyang' into 'libyang1' was populated into sysrepo on July 29th, 2020 . The sysrepo version 1.4.70 was tagged a week before this, on July 21st, 2020, so this version doesn't know about this name change and consequently checks for the old package name 'libyang'.
If you use the devel branch of sysrepo (or at least commitID fd05fbf64b85fa8b3ecb2ee91a1993a458514c17), you should be fine.
Kind Regards,
Peter

**Comment by esend7881** [comment]
> Hi,
> just a hint: The package name of libyang is 'libyang**1**' (since July 15th, 2020, therefore valid for version 1.0.184).
> The package name change from 'libyang' into 'libyang1' was populated into sysrepo on July 29th, 2020 . The sysrepo version 1.4.70 was tagged a week before this, on July 21st, 2020, so this version doesn't know about this name change and consequently checks for the old package name 'libyang'.
> If you use the devel branch of sysrepo (or at least commitID fd05fbf64b85fa8b3ecb2ee91a1993a458514c17), you should be fine.
> Kind Regards,
> Peter

Hi @psch-k
I wonder if you could help my new problem described here https://github.com/CESNET/netopeer2/issues/784#issuecomment-752744671
