### ISSUE TITLE
require-instance statement clarification

### ISSUE THREAD

**Issue by som-1981** [sysrepo/sysrepo#2209]
Hello,
I read through the yang documentation to understand more on "require-instance" statement. But did not understand completely. Can someone help in understanding this from below example.
For example:
```yang
leaf scheme {
      type enumeration {
        enum A {
              description
                "A scheme";
            }
        enum B {
              description
                "B scheme";
        }
      }
      config false;

      description
        "Type of duplex scheme that is supported";
    }
   
 leaf rw-scheme {
      type leafref {
        path "../../carriers[name=current()/../name]" + "/scheme";
        require-instance false;
      }
      description
        "Config true type of scheme.";
    }
```
What is the need of defining scheme as ro and rw. The scheme is "read-only" why should there be a provision to read-write given?

Thanks

**Comment by michalvasko** [comment]
Hi,
I cannot tell you the exact intention of whoever wrote this YANG snippet, you better ask them. But, it can possibly be a pre-[NMDA](https://tools.ietf.org/html/rfc8342) module that tries to express a `scheme` actually used by the device (the `config` `false` value) and then the configured value (`rw-scheme`). These may differ in some cases.
