### ISSUE TITLE
multi subscription in a yang module but can not get change data in one

### ISSUE THREAD

**Issue by myonlystarWang** [sysrepo/sysrepo#2211]
Hi Michal,
     I have met a problem which seems a little strange.I have a yang module like below:
```
module test{
    namespace "urn:hysatcom:params:xml:ns:yang:test";
	prefix test;
	
	revision 2020-09-01 {
		description
		    "initial create";
	}

	typedef my-decimal {
         type decimal64 {
             fraction-digits 16;
          }
       }
	 
	container config {
		config true;
					
		leaf a {
			type uint8 {
				range "1..15";
			}
		}
		
		leaf b {
			type my-decimal;
		}	

		list c{
			key "d";
						
			leaf d {
				type uint8 {
					range "1..3";
				}
			}
			
			leaf e {
				type my-decimal;
			}		
		}	//c
	} //container config 
```
（I am sorry that I do not known how to display in the correct format above）

Then I subsrcibe the container first use:
```
 sr_module_change_subscribe(session, "test", "/test:config", container_change_cb, NULL, 0,\
            SR_SUBSCR_ENABLED | SR_SUBSCR_DONE_ONLY, &subscription);
```

secondly,I subscribe the list use:
```
sr_module_change_subscribe(session, "test", "/test:config/c", list_change_cb, NULL, 0,\
            SR_SUBSCR_ENABLED | SR_SUBSCR_DONE_ONLY | SR_SUBSCR_CTX_REUSE, &subscription);
```

**Note that I have used the same "subscription",and the same session, of course.**

Next,I start the application and **receive the both container and list EVENT done CHANGES** which I determined    from log file.

Next,When I modify/delete/create the list data of d and e,I find that the callback of **list c** can be triggered, but no data can be retrieved when I use `sr_get_changes_iter(pstSession, "//." , &pstIt);`.

The callback of **container config** can be normal triggered at the same time, and of course I can retrieve the change data of **list c**,but I do not want to do this in my scenario.

So I tried the following code:
```
sr_module_change_subscribe(session, "test", "/test:config/c", list_change_cb, NULL, 0,\
            SR_SUBSCR_ENABLED |  SR_SUBSCR_CTX_REUSE, &subscription);
```
deleted the `SR_SUBSCR_DONE_ONLY `，then I can retrieve the change data of **list c** from the **EVENT change CHANGES** in callback,but still no data was retrieved from the **EVENT done CHANGES**.

Is that expected right? 
By the way, I know I can resolve this by  separating the **list c** to a individual container,so that I can subsribe the **container config** and **list c** independently.

BR,
Wang

**Comment by michalvasko** [comment]
Hi,
so what you are essentially saying is that you use the same `xpath` but get different changes for `SR_EV_CHANGE` and `SR_EV_DONE` events? If that is true, it is definitely a bug. What *sysrepo* version are you using?

**Comment by myonlystarWang** [comment]
Hi michal,
The xpath of the two subscriptions is not same,one is /test:config for container,the other is /test:config/c for list.
The xpath I used to retrieve data in callback is the input param of the callback, and of course they are the same with the xpath when I use the change subscribed API
The sysrepo version is 0.7.7.......emm,I remember I had update the version to 1.4.58 already:(

**Comment by michalvasko** [comment]
I was actually referring to the last bit that you wrote and `xpath` parameter of `sr_get_changes_iter`. In any case, if you are using *sysrepo* 0.7.7 then I cannot help you.

**Comment by myonlystarWang** [comment]
Sorry,my fault.The version is 1.4.58.
I got the 0.7.7 by using *sysrepod -v *not correct.

**Comment by michalvasko** [comment]
Um, that does not really sound correct. You should probably fully uninstall the old version first to avoid any problems. Also, if it is not a problem, you should update *sysrepo* to the current `devel` version and try to reproduce the problem again. If you succeed, please post the exact steps to reproduce it.

**Comment by myonlystarWang** [comment]
ok,I will do what you said above and comment here then

**Comment by myonlystarWang** [comment]
Hi Michal,
    I did this below when I was about to change the version to devel.
    1. change the` list c `subscription to another local variable `sr_subscription_ctx_t* listSubscription`
```
sr_module_change_subscribe(session, "test", "/test:config/c", list_change_cb, NULL, 0,\
            SR_SUBSCR_ENABLED | SR_SUBSCR_DONE_ONLY, &listSubscription);
```
2. re-compile the application and  re-run
3. modify the value of **e** or **d** in **list c** from the webpage(which I make myself), it works fine.I can get the right and different changes for` SR_EV_DONE` events which I determined from the log tail.

So can I think of it this way because different subscriptions lead to different results??
Of course different container use only one subscription by using `SR_SUBSCR_CTX_REUSE `should work fine, but it seems not work when I use only one subscription for different list or leaf in one container.
Although the problem can be solved, can you help me explain the principle?

BR,
Wang

**Comment by michalvasko** [comment]
Hi,
it should not make a difference whether you have all subscriptions in a single structure or separate ones, it definitely should not affect the changes you get. If it does, it is a bug. That is why I told you to update it because the bug may have been solved. Otherwise I would attempt to fix it but for that I need all the steps and data required for reproducing it.

**Comment by myonlystarWang** [comment]
Hi michal,
     I reinstalled a new vm with Ubuntu18.04 and installed the latest `sysrepo-devel`、`netopeer2-devel` for reproducing the problem.I just test several cases below:
1. A simple test case:   
    I install the yang module which I mentioned this issue and add **list c** subscription in app_change_example.c,then run app_change_example,modify the **leaf d** value of **list c** from webpage,it works fine.

2. **BUT** the problem still exist in my engineering code.(I'm sure my engineering code is no different than app_change_example. They are all the one connection and one session, two subscription and one for container one for list in the container)
Limited by the project development schedule,I have not collect the log yet.I'll sort it out in detail in the future

3. Then I just delete the `SR_SUBSCR_CTX_REUSE` option from `sr_module_change_subscribe`’s input param ,It works just fine. So I'm going to use it that way for now. 

**Note**： In all of the above scenarios，the subscriptions ptr which is the input of `sr_module_change_subscribe` are the same one variable as **container config**‘s subscription.

**Comment by michalvasko** [comment]
Do I understand it correctly that it works exactly as expected when you use `application_changes_example` but not if you use your own application? In that case there will be some minor difference that is causing the problem. Perhaps the `xpath` parameter used for `sr_get_changes_iter()`.

**Comment by myonlystarWang** [comment]
Yes,it is true what you understand.
I am trying to find the differences between two code.
I think there are something wrong in my code and it should also work fine with sysrepo version 1.4.58.

**Comment by myonlystarWang** [comment]
It's been a while.In the scenario on this issue, my goal is to subscribe to two different members of a module at the same time,such as leaf `a` and list `c`.So I used the same subscription pointer and the flag `SR_SUBSCR_CTX_REUSE` before,but my current solution is to use them separately as below code:
```
unsigned int module_subscribe_func(sr_session_ctx_t *session, sr_subscription_ctx_t **subscription)
{
    int iRet = SR_ERR_OK;
    sr_subscription_ctx_t *pstSubscription = NULL;

    /* subscribe leaf a */
    iRet = sr_module_change_subscribe(session, "test", "/test:muxAlg0Cfg", leaf_a_config_change_cb, NULL, 0,\
            SR_SUBSCR_ENABLED | SR_SUBSCR_DONE_ONLY, subscription);
    if (iRet != 0) {
        goto error;
    }
  
    /* subscribe list c */
    iRet = sr_module_change_subscribe(session, "test", "/test:vipAlg0Cfg", list_c_config_change_cb, NULL, 0,\
            SR_SUBSCR_ENABLED | SR_SUBSCR_DONE_ONLY , &pstSubscription);
    if (iRet != 0) {
        goto error;
    }

    /* sysrepo/plugins.h provides an interface for logging */
    return SR_ERR_OK;

error:
    return iRet;
}
```
It works well,so I was wondering what's the right way to use it?

**Comment by michalvasko** [comment]
Yes, this is fine. You have 2 subscription structures and each of them has its own thread. If you used `SR_SUBSCR_CTX_REUSE` with a single subscription structure, you would have only 1 thread handling both subscriptions. I believe this is also written somewhere in the docs.

**Comment by myonlystarWang** [comment]
yes,I had read the description of `SR_SUBSCR_CTX_REUSE` in the [website](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__subs__api.html#ggac91898627ad5aeb589e6a3993a697d14a08c075b76b8299ea4b4ed0fbbcb5b9ae) .
Thank you for your explanation and clarification,michal!
This issue can be closed.
