### ISSUE TITLE
Callback class of sysrepo

### ISSUE THREAD

**Issue by mdoshi-com** [sysrepo/sysrepo#2214]
Hi,
Earlier there was a Callback defined in bindings/cpp/src/Session.hpp file.
Looks in latest devel version (libsysrepo v1.4.89 (SO v5.6.5) ) this class is not defined.

We were using this class to register all callbacks with sysrepo, so now can you tell what is the replacement.

Regards,
Meghna

**Comment by michalvasko** [comment]
Yes, the class was removed for the sake of a cleaner solution. Just look at [an example](https://github.com/sysrepo/sysrepo/blob/devel/bindings/cpp/examples/cpp_application_example.cpp#L81) and it should be easy to update your code.
