### ISSUE TITLE
how to construct xpath for multiple key for read only yang data?

### ISSUE THREAD

**Issue by koala027** [sysrepo/sysrepo#2219]
Hi michalvasko,

Recently, I use sysrepo and libyang in my project,  the YANG moudle contain two keys, and the yang module is config false(state data)
as below, the interface-name and port-number are key.
//****************************************************************************************
  +--rw port-transceivers
     +--rw port-transceiver-data* [interface-name port-number]
        +--rw interface-name                     -> /if:interfaces/interface/name
        +--rw port-number                        -> /if:interfaces/interface[if:name = current()/../interface-name]/o-ran-int:port-reference/port-number
        +--rw name?                              string
        +--ro present                            boolean
        +--ro vendor-id?                         string
        +--ro vendor-part?                       string
        +--ro vendor-rev?                        string

//****************************************************************************************

I register a hook callback, sr_oper_get_items_subscribe to raise those state data

 *parent = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(session))
               , "/o-ran-transceiver:port-transceivers/port-transceiver-data[interface-named='x'][port-number='0']/vendor-id", "rru", 0, 0);

lyd_new_path used to construct the xml node, but it always error raised, tell me the '['
**List key not found or on incorrect position ("interface-named='x'][port-number='0']**

michalvasko, could you tell me how to  componse this xpath for sr_oper_get_items_subscribe?  thanks very much

**Comment by koala027** [comment]
Sorry forget one thing,  ("interface-named='x'][port-number='0'] has been defined in referenced YANG modle data.

//****************************************************************************************
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interface>
    **<name>x</name>**
    ........
    <port-reference xmlns="urn:o-ran:interfaces:1.0">
      <port-name>xx.1x</port-name>
      **<port-number>0</port-number>**
    </port-reference>
  </interface>
</interfaces>

//****************************************************************************************

**Comment by michalvasko** [comment]
I guess `interface-named` should be `interface-name`, right?

**Comment by Elijah123-a** [comment]
I just ran into the same error, but I used Sr_ rpc_ The subscribe function is used to output nodes，

**Comment by phuong-dut-es** [comment]
> I just ran into the same error, but I used Sr_ rpc_ The subscribe function is used to output nodes，

Me too. Did you try to get data ? because those data is read-write so i think i can config to sysrepo by sysrepocfg, then get with netopeer2. I try but it failed
