### ISSUE TITLE
Question related to: "ncclient timed out while waiting for an RPC reply"

### ISSUE THREAD

**Issue by Roky7250** [sysrepo/sysrepo#2220]
Hi, I am using latest versions of sysrepo, netopeer2, libyang and libnetconf from master branches.

I developed a few modules inside sysrepo for setting and getting some information on a network device.
So, when I execute get request (entire get configuration) it takes about  4 seconds to get data.

I created a python script whose task is to create 10 threads (using one process) that will use python3 ncclient to connect to the device, execute get request, and disconnect from the device. 
For example threads will use this function:

```
def get_data(filter, thread_num):
    while True:
        #connect to the device usgin manager.connect
        #execute get
        #disconnect from device
```

Variables that are changed compared to the original version inside netopeer2-server and libnetconf2 are:

```
THREAD_COUNT = 12 // netopeer2-server CMakeList.txt (increased)
RPC_TIMEOUT = 66 // netopeer2-server CMakeList.txt (increased)
DATA_CHANGE_WAIT = yes // netopeer2-server CMakeList.txt (changed from NO to YES)

MAX_PSPOLL_THREAD_COUNT = 15 //libnetconf2 CMakeLists.txt  (increased)
```

Problem is that everything works fine for 20 min, after that script crashes with an error message:
`error=ncclient timed out while waiting for an rpc reply., session_id=3276`

When I increase ncclient timeout inside manager.connect from the 30s to 80s it works for 60 min and then crashes again.

The point here is that I want to enable my modules inside sysrepo to work with a testing script with 10 threads without any problems, meaning that the script that does get requests with 10 threads doesn't crash.
**I want to know the desired values of timeouts for which script will work fine, so I can say ok, for this parameters my modules with 10 testing threads will work fine.**

My question is next, do I need to increase the timeout of ncclient more, or I need to increase some of the timeouts inside CMakeList.txt files of netopeer2-server, libnetconf2, or sysrepo?
What can cause this problem?

Thanks in advance
Regards

**Comment by jktjkt** [comment]
> I developed a few modules inside sysrepo for setting and getting some information on a network device.
> So, when I execute get request (entire get configuration) it takes about 4 seconds to get data.

I'm assuming that you're connecting via NETCONF, not directly to sysrepo. Is that correct? What operation takes these 4s -- is that a [`<get>`](https://tools.ietf.org/html/rfc6241#section-7.7), or a [`<get-config>`](https://tools.ietf.org/html/rfc6241#section-7.1)? What [datastore](https://tools.ietf.org/html/rfc8342) are you querying? Are your requests hitting any callbacks that actually provide on-demand data back to sysrepo?

> Problem is that everything works fine for 20 min, after that script crashes with an error message:
> `error=ncclient timed out while waiting for an rpc reply., session_id=3276`
> 
> When I increase ncclient timeout inside manager.connect from the 30s to 80s it works for 60 min and then crashes again.

It would be nice to see the server-side logs, and also to get a trace of what exactly is going on in other threads when your request times out. That would require you to use a debugger.

> My question is next, do I need to increase the timeout of ncclient more, or I need to increase some of the timeouts inside CMakeList.txt files of netopeer2-server, libnetconf2, or sysrepo?
> What can cause this problem?

In my opinion, response times such as 10s (or longer) indicate that there's a real bug somewhere. Using even longer timeouts would be only papering over the root cause.

**Comment by Roky7250** [comment]
Hi

1) Yes I am connecting to the neropeer2-server via NETCONF.
I am executing **get** request, gathering both state and config data from device for all modules.
I am querying running datastore and my requests are hitting callback for state data inside my implemented modules.
Those callbacks are actually gathering data from the device.

2) on netopeer2-server I get this message:
```
[INF]: LY: All data nodes and constraints resolved.
[2020/11/16 10:46:58.253654, 1] ssh_socket_exception_callback:[INF]: SR: Published event "rpc" "/ietf-netconf:get" with ID 92 priority 0 for 1 subscribers.
  Socket exception callback: 1 (0)
[2020/11/16 10:46:58.254804, 1] ssh_socket_exception_callback:  Socket error: disconnected
[ERR]: LN: Session 91: SSH channel write failed.
[ERR]: LN: Session 91: communication socket unexpectedly closed.
[ERR]: LN: Session 91: failed to write reply (error).
[INF]: NP: Session 91: thread 1 event new RPC.
[INF]: NP: Session 91: thread 1 event session terminated.
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-end).
[INF]: SR: Processing "/ietf-netconf:get" "rpc" event with ID 92 priority 0 (remaining 1 subscribers).
[INF]: SR: Published event "operational" "/ieee8021-mstp:ieee8021-mstp" with ID 92.
[INF]: SR: Event "operational" with ID 92 succeeded.
[INF]: SR: Successful processing of "rpc" event with ID 92 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 92 priority 0 succeeded.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[2020/11/16 10:46:59.502326, 1] ssh_socket_exception_callback:  Socket exception callback: 1 (0)
[2020/11/16 10:46:59.502439, 1] ssh_socket_exception_callback:  Socket error: disconnected
[ERR]: LN: Session 92: SSH channel write failed.
[ERR]: LN: Session 92: communication socket unexpectedly closed.
[ERR]: LN: Session 92: failed to write reply (error).
[INF]: NP: Session 92: thread 8 event new RPC.
[INF]: NP: Session 92: thread 8 event session terminated.
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-end).
```


3) There are no bugs inside callbacks inside sysrepo modules. It takes 4s because I am gathering a big amount of data.
Also, my get functions for gathering state data are using a lot of parsing functions to extract desired data, and also a tool that I am using for getting data that will be parsed is not so fast. So that's why it takes so much time.
I don't have any error messages on sysrepo side (sysrepo log).

Regards

**Comment by jktjkt** [comment]
When happens when you move sysrepo out of the picture and start executing your callbacks parallel from several threads? Does the execution time grow in a similar manner? If so, then the bug is not in sysrepo, but in your callbacks. If not, then there's more things to investigate.

**Comment by Roky7250** [comment]
Hi, I did something else.
I have one really fast module, in which **get** request takes from 0.03-0.1 seconds (measured with netopeer2-cli).
When I start my test script with 10 threads in python, that is doing **get** request but only for this module (using filter, to filter get for only this module) everything works fine. The script does not crash with error message related to ncclient timeout.
It works a few hours without crashing.

So I took that module and inserted sleep() inside the callback that is gathering state data.
After that my **get** request for that module lasted about 1.8 seconds.
So **get** request was increased from 0.03-0.1 seconds to 1.80-1.85 seconds.

Then I started my testing script with 10 threads and script crashed after few minutes with error message:
`error=ncclient timed out while waiting for an rpc reply., session_id=3287` same as above.

On netopeer2-server side I got the same error messages as above.
On sysrepo side, everything is clean, there are no error messages inside the log file.

So, I think this is related to the time of **get** request is taking.
When **get** time is around 1.5 seconds and if I have more than 6 threads script will crash every time.

Maybe I can create some dummy module inside which I will have state callback that will create a few hardcoded state leafs and inside which I will have a sleep() so **get** request takes about 1.8 seconds.
Then I will test that module using my python script (that uses ncclient). If the same thing happens (ncclient timeout) with multiple threads then I can attach that dummy module so you can test it.

Regards
