### ISSUE TITLE
 Question: Is it possible to have yang data tree without root container?

### ISSUE THREAD

**Issue by maksimvuleta** [sysrepo/sysrepo#2221]
Is it possible that YANG starts with the list as a root, not with the root container?

For example like this:
```yang
module example-module {
namespace "example-module";
prefix exm;
list example-module-list {
key "index";
leaf index {
type uint32;
description
"Index.";
}
....
}
```
If it is possible, how to implement this in sysrepo?

**Comment by michalvasko** [comment]
Yes, generally it is fine and should work correctly. However, if you create many instances of such a list, be prepared for major performance degradation because most *libyang* optimizations are based on a hash table of all the children stored in a parent node. Since you have no parent in this case, the optimizations are not used. Such data can also be quite messy in XML format.

**Comment by maksimvuleta** [comment]
The question is also related to how to create the data tree without root?
I want to create the data tree and replace the running configuration with the created data tree using the  sr_replace_config.

Is it even possible with no root defined?

**Comment by michalvasko** [comment]
Sure, there is no problem there, what exactly do you need helping with? You create it the same way, basically. It is not a problem to have 2 root containers in YANG data, for example, you will simply have many list instances.

**Comment by maksimvuleta** [comment]
I create the _root1 = lyd_new_path(...)_ and add new child nodes to this root1.
Then I use the _sr_replace_config(session, "example-module", root1, 0, 0))_.

How to add the second root2 into the example-module in this session?

**Comment by michalvasko** [comment]
By appending the other "root" to the first one. Either by using `lyd_new_path` again with the second argument being the previous root or manually by calling `lyd_insert_sibling`.

**Comment by maksimvuleta** [comment]
Thanks a lot!

It works in both ways.

**Comment by maksimvuleta** [comment]
I succeeded to fill the startup and running configuration without the root container and everything seemed to work fine. 
Then I subscribed to the example-module-list/index like this:
`rc = sr_module_change_subscribe(session, "example-module", "/example-module:example-module-list/index", example_list_cb, NULL, 1, SR_SUBSCR_ENABLED, &subscription);`

The example_list_cb looks like this:
```
static int
example_list_cb(sr_session_ctx_t *session, const char *module_name, const char *xpath, sr_event_t event, uint32_t request_id, void *private_data)
{
	(void)module_name;
	(void)request_id;
	(void)private_data;
	int rc = SR_ERR_OK;
	sr_change_oper_t op = {0};
	sr_change_iter_t* iter = NULL;
	sr_val_t* old_value = NULL;
	sr_val_t* new_value = NULL;

	SRP_LOG_DBG("######## Example list callback called with event: '%d'", event);

	rc = sr_get_changes_iter(session, xpath, &iter);
	if(SR_ERR_OK != rc)
	{
		return rc;
	}

	while(SR_ERR_OK == sr_get_change_next(session, iter, &op, &old_value, &new_value))
	{
		SRP_LOG_DBG("######## Example list callback operation: '%d'", op);
	}

	sr_free_val(old_value);
	sr_free_val(new_value);
	sr_free_change_iter(iter);
	iter = NULL;

	return SR_ERR_OK;
}
```

By default, I have a configuration like this:
```
<config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<example-module-list xmlns="uri:example-module">
  <index>1</index>
</example-module-list>
<example-module-list xmlns="uri:example-module">
  <index>2</index>
</example-module-list>
</config>
```

When I try to add a new entry with the netopeer2-cli edit config command everything works fine and the entry is added and the callback function example_list_cb is triggered.  

The issue is with removing one of the entries. 
When I do this:
`edit-config --target running --defop replace --config=example.xml`
Where example.xml content is:
```
<config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<example-module-list xmlns="uri:example-module">
  <index>1</index>
</example-module-list>
</config>
```

The callback function is not triggered and nothing happens on the sysrepo-plugind side. The netopeer2-server log is like this: 

```
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" "/ietf-netconf:edit-config" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[INF]: NP: edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
[INF]: SR: No datastore changes to apply.
[INF]: SR: Successful processing of "rpc" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 1 priority 0 succeeded.
[INF]: NP: Session 1: thread 3 event new RPC.
```

When I do the get-config request there are still two entries in the configuration, like it was the default. 
```
<config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<example-module-list xmlns="uri:example-module">
  <index>1</index>
</example-module-list>
<example-module-list xmlns="uri:example-module">
  <index>2</index>
</example-module-list>
</config>
```
The entry was not removed from the configuration and the callback was not triggered also.

**Comment by michalvasko** [comment]
This is correct according to the [specs](https://tools.ietf.org/html/rfc6241#page-38), only the configuration in the config is affected. NETCONF works more in the way of step-by-step changes rather than setting it to a specific config. You can delete the second instance with
```xml
<example-module-list xmlns="uri:example-module" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" xc:operation="delete">
  <index>2</index>
</example-module-list>
```
The default operation can be anything because it is overridden by the explicit `delete` operation.

**Comment by maksimvuleta** [comment]
Thank you for your explanation.
