### ISSUE TITLE
How to know if a datastore is locked in other session?

### ISSUE THREAD

**Issue by IvanAguiar** [sysrepo/sysrepo#2223]
Hi Michal, I hope you're doing well.

I'd like to know how to get the datastore locking status using python binding.

The scenario is:
- Run the netopeer + python bindings
- Use a 3rd client to connect (Like MG_Soft netconf)
- Lock the datastore using the client
- Try to replace config from binding to a locked datastore.

There is a function ( sr_get_lock() ) that returns the locking status but only returns True when called from the same session, but I need to get from a different one.

When we try try to replace config from binding to a locked datastore, sysrepo crashes.

SO                     Ubuntu 16.04
SYSREPO           v1.4.70
NETOPEER2       v1.1.39
LIB_YANG          v1.0.184

Thank you for your help.

**Comment by michalvasko** [comment]
> There is a function ( sr_get_lock() ) that returns the locking status but only returns True when called from the same session, but I need to get from a different one.

If this is true then there is something really wrong, the locking state is global.

> When we try try to replace config from binding to a locked datastore, sysrepo crashes.

This, again, should not happen, obviously. Hard to say what the problem can be. Whether you have some version incompatibility (several versions of a library installed and being used) or there really is a problem in *sysrepo*.

**Comment by IvanAguiar** [comment]
Only the version provided before. We built a docker container with netopeer2 stack and python bindings and just it.

**Comment by IvanAguiar** [comment]
I observed now that there is a log when I do the following in python: `conn.get_lock(sr.SR_DS_CANDIDATE)`

```
<Swig Object of type 'std::tuple< int,uint32_t,uint32_t,time_t > *' at 0x7f2238ad11e0>
swig/python detected a memory leak of type 'std::tuple< int,uint32_t,uint32_t,time_t > *', no destructor found.
```

**Comment by michalvasko** [comment]
That is definitely wrong but the cause is still not clear. What docker image script did you use? Also, I do not know much about these bindings, maybe @lpaulic can help? Or can notify someone who can.
