### ISSUE TITLE
Question related to config data inside state callback?

### ISSUE THREAD

**Issue by Roky7250** [sysrepo/sysrepo#2224]
Hi, I am having a problem getting config data inside state callback using **sr_get_items** function.
The function fails for some reason.

Is this even possible, by that, I mean getting some part of the configuration inside the state callback using **sr_get_items** function?

Regards

**Comment by michalvasko** [comment]
Yes, in general this should be possible but there may be at least one problem I can immediately think of. If you are getting `operational` data that are being retrieved by your callback, you will get either a deadlock or infinite recursion, not sure which one.

**Comment by Roky7250** [comment]
Hi, well you guessed it.

My situation is next. This is state of my container in RUNNING datastore (get-config request returns this):
```
        <test-container>
          <test-list>
            <index>1000</index>
          </test-list>
          <test-list>
            <index>2000</index>
          </test-list>
        </test-container>
```

Now list "test-list" has one more leaf called "value". That leaf is config false.
Inside my callback for test-container for state data, I need to get all test-list entries, so I can go one entry by one and call mu get function (this function uses index values from test-list) for leaf **value**, so I can fill it up in state configuration.

Configuration after a get request should look like this:
```
        <test-container>
          <test-list>
            <index>1000</index>
            <value>tmx</value>
          </test-list>
          <test-list>
            <index>2000</index>
            <value>dnx</value>
          </test-list>
        </test-container>
```

So in my state callback, I need to iterate through test-list entries (trough indexes of entries) and call my get function that takes as argument **index** of the **test-list** and returns the **value** for that index.

Can you purpose some kind of solution for this?

Regards

**Comment by michalvasko** [comment]
I can think of 2, the more complex one is you using `sr_get_data()` instead with `SR_OPER_NO_SUBS` flag that will prevent your callback to be called again. Or you can simply switch the datastore to `running` that will achieve basically the same (unless you have some push operational data set).
