### ISSUE TITLE
No document link mentioned in earlier bugs opening, Need some offline user/developer's guide

### ISSUE THREAD

**Issue by ankit7gup** [sysrepo/sysrepo#2225]
Hi Michal, I have started using Sysepo recently, with prior understanding of netconf and confd. To better understand the APIs, Is there any offline developer's guide or document to refer.
Secondly, the earlier threads I am referring to on github, shows page not found. In case you can help with it.

Thanks!

Regards,
Ankit

**Comment by michalvasko** [comment]
Documentation hosting has moved not that long ago to [here](https://netopeer.liberouter.org/doc/sysrepo/master/html/). There is also a new additional [doc](https://github.com/sysrepo/sysrepo/blob/devel/plugin_dev_doc.md) with some useful information to get started.

**Comment by ankit7gup** [comment]
Hi Michal, 
Thanks for the quick response, I find one limitation in the search for this documentation, i.e. You can only search from starting of the API and not from middle. In case any suggestion on this, it would be of great help. Thanks!

**Comment by michalvasko** [comment]
The final documentation format is up to `doxygen`. But the API is not that large so I think it is fine. I cannot help you, in any case.

**Comment by ankit7gup** [comment]
Thanks Michal for the info.
