### ISSUE TITLE
modifying & deleting an entry in key-less list

### ISSUE THREAD

**Issue by kavk7** [sysrepo/sysrepo#2227]
Hi Team,

we try to modify the key-less list entry as below but instead of modifying existing entry it is creating a new entry.
Could you please help in modifying key-less list.

steps:
added below set of entries to operational DB using "sr_set_item_str" API then doing "sr_apply_changes" for committing changes. Input format is "\<xpath-to-set\> \<value-to-set\>"

====Add entry to key-less list====
 
_/o-ran-fm:active-alarm-list/active-alarms[1]/fault-id 123
/o-ran-fm:active-alarm-list/active-alarms[1]/fault-source abc
/o-ran-fm:active-alarm-list/active-alarms[1]/**fault-severity MAJOR**
/o-ran-fm:active-alarm-list/active-alarms[1]/event-time 2020-09-11T00:01:00Z_

====get output====

\>get-data --datastore operational --filter-xpath /o-ran-fm:active-alarm-list
![image](https://user-images.githubusercontent.com/75008096/100196229-9af1e300-2f1e-11eb-9ed1-e3af6e4ef3ca.png)

===Modify the existing entry in key-less list====
_/o-ran-fm:active-alarm-list/active-alarms[1]/fault-id 123
/o-ran-fm:active-alarm-list/active-alarms[1]/fault-source abc
/o-ran-fm:active-alarm-list/active-alarms[1]/**fault-severity MINOR**
/o-ran-fm:active-alarm-list/active-alarms[1]/event-time 2020-09-11T00:01:00Z_

====get output====

\>get-data --datastore operational --filter-xpath /o-ran-fm:active-alarm-list
![image](https://user-images.githubusercontent.com/75008096/100196507-f58b3f00-2f1e-11eb-96a5-a8514c70333a.png)

**expected output was:**
![image](https://user-images.githubusercontent.com/75008096/100196564-08057880-2f1f-11eb-9d70-937e7cb12e5a.png)

yang reference is o-ran-fm.yang and attached the same.
[o-ran-fm.txt](https://github.com/sysrepo/sysrepo/files/5595137/o-ran-fm.txt)
 

Thank you.

**Comment by michalvasko** [comment]
Do I understand it correctly that you are trying to modify the existing key-less instance (in `running`?) by push `operational` subscriptions?

**Comment by kavk7** [comment]
Hi Michal,

No, not running data store. we added the entry in operation data store and tried modifying it using sr_set_item_str API and committed changes using "sr_apply_changes" API.

Also, when we tried deleting an entry from key-less list in operation data store using "sr_delete_item" API with xpath as "/o-ran-fm:active-alarm-list/active-alarms[1]", It is not getting deleted.

**Comment by michalvasko** [comment]
Okay, you are correct, this is not supported because NETCONF `edit-config` does not support it (editing state data in general). This would need to be implemented specially but we just do not have the resources for such minor features. Please use pull operational data subscriptions until then, they should work much better because they allow editing data directly, not using an `edit-config` and a diff.

**Comment by kavk7** [comment]
okay. so, you mean push based state data set doesn't work in general ? or specific to key-less list only ?

**Comment by michalvasko** [comment]
No, only key-less lists, the rest should be fine.

**Comment by kavk7** [comment]
Okay, Thank you Michal.

**Comment by chendrashekarp** [comment]
HI michal,
what about delete operation in the above mentioned way. 
"deleting an entry from key-less list in operation data store using "sr_delete_item" API with xpath as "/o-ran-fm:active-alarm-list/active-alarms[1]", It is not getting deleted" will this work ?

**Comment by chendrashekarp** [comment]
Hi @kavk7 ,
how did you implemented this fault management section ,
if the delete and set is not working on key-less list? 
any help will be appreciated.
thank you

**Comment by chendrashekarp** [comment]
can i change of a key-less list data using the xpath as "/o-ran-fm:active-alarm-list/active-alarms[1]/fault-id" , using pull ? 
or i can simply use sr_set_item ?

**Comment by michalvasko** [comment]
You do not change operational data by pull method using an XPath, you directly create/modify the data tree. If you want to use the push method (`sr_set_item`) for key-less lists, you must use *sysrepo* v2.

**Comment by chendrashekarp** [comment]
Hi @michalvasko ,
can you please give update about deleting key-less list instance in operational data using `sr_oper_delete_item_str`
trying to delete `/o-ran-fm:active-alarm-list/active-alarms[1]`. it is not getting deleted.

**Comment by michalvasko** [comment]
Please stop mixing all the questions of your issues into all the other issues, it is chaotic and the post in the issues became irrelevant.

**Comment by mpmkp2020** [comment]
Hi @michalvasko,

Is there any way to update existing element in key-less list using xml (or rpc `edit-config --config target running`). When I am try to update existing element, it is adding new element into the list rather than updating the existing element.

Example xml:
=========
```
<md-data-definitions xmlns="urn:o-ran:lbm:1.0">
  <maintenance-domain>
    <id>1</id>
    <name>MD_NAME</name>
    <md-level>5</md-level>
    <maintenance-association>
      <id>1</id>
      <name>MA_NAME</name>
      <component-list>
        <component-id>4</component-id>
        <name>COMP_LIST_NAME</name>
        <vid>3</vid>                      // This is key-less list
        <remote-meps>1</remote-meps>
        <maintenance-association-end-point>
          <mep-identifier>1</mep-identifier>
          <interface>eth0</interface>
          <primary-vid>3</primary-vid>
          <administrative-state>true</administrative-state>
        </maintenance-association-end-point>
      </component-list>
    </maintenance-association>
  </maintenance-domain>
</md-data-definitions>
```

Yang tree:
=======
```
root@user:/home/user/oran_yang_model# pyang -f tree o-ran-lbm.yang
module: o-ran-lbm
  +--rw md-data-definitions
     +--rw maintenance-domain* [id]
        +--rw id                         string
        +--rw name?                      string
        +--rw md-level?                  md-level-type
        +--rw maintenance-association* [id]
           +--rw id                string
           +--rw name?             string
           +--rw component-list* [component-id]
              +--rw component-id                         uint32
              +--rw name?                                string
              +--rw vid*                                 -> /if:interfaces/interface/o-ran-int:vlan-id
              +--rw remote-meps*                         mep-id-type
              +--rw maintenance-association-end-point* [mep-identifier]
                 +--rw mep-identifier          mep-id-type
                 +--rw interface               -> /if:interfaces/interface/name
                 +--rw primary-vid             -> /if:interfaces/interface/o-ran-int:vlan-id
                 +--rw administrative-state    boolean
                 +--ro mac-address?            -> /if:interfaces/interface/o-ran-int:mac-address
                 +--ro loopback
                    +--ro replies-transmitted    yang:counter32
root@user:/home/user/oran_yang_model#
```


Thank you.

**Comment by chendrashekarp** [comment]
Hi @mpmkp2020, `edit-config --config target running --defop replace` use this option

**Comment by mpmkp2020** [comment]
@chendrashekarp, I want to update specific element in the list but don't want to loose any existing data.

**Comment by chendrashekarp** [comment]
in this case, you can use `positional predicate`.

**Comment by mpmkp2020** [comment]
@chendrashekarp, can you be specific if how to use `positional predicate` in xml?

**Comment by mpmkp2020** [comment]
@michalvasko, please help !

**Comment by michalvasko** [comment]
Firstly, `vid` is not a key-less list but normal leaf-list. You cannot "modify" those, you can only delete and/or create some instances, in a single edit-config if you want. You can learn more about [operations](https://datatracker.ietf.org/doc/html/rfc6241#section-7.2) (which you need to use) in the NETCONF spec.
