### ISSUE TITLE
sysrepo/libyang: 'when' condition validation relative to incorrect xpath

### ISSUE THREAD

**Issue by igortern** [sysrepo/sysrepo#2229]
Hi,

The following error appears when using devel. The same test works with the latest release.

Prereqs: 
- sysrepo,libyang, netopeer2, libnetconf from devel on November 26
- sysrepo datastore is attached

Attempt to send  `/ietf-interfaces:interfaces-state/interface[name='channeltermination.1']/bbf-xpon:channel-termination/bbf-xpon-onu-state:onu-presence-state-change` notification
fails. The same notification can be sent without problem when using the latest release versions. It appears that 'when' condition is validated relative to incorrect path
**/ietf-interfaces:interfaces-state/interface[name='channeltermination.1']/bbf-xpon:channel-termination/bbf-xpon-onu-state:onu-presence-state-change**
instead of
**/ietf-interfaces:interfaces-state/interface[name='channeltermination.1']/bbf-xpon:channel-termination**
see in bbf-xpon-onu-state.yang
```
libyang[0]: Irresolvable when condition "derived-from-or-self(/ietf-interfaces:interfaces/ietf-interfaces:interface[ietf-interfaces:name=current()/../ietf-interfaces:name]/bbf-xpon:channel-termination/bbf-xpon:location, 'bbf-xpon-types:inside-olt')". (path: /ietf-interfaces:interfaces-state/interface[name='channeltermination.1']/bbf-xpon:channel-termination/bbf-xpon-onu-state:onu-presence-state-change)
[3313643: E SYSREPO             ] Irresolvable when condition "derived-from-or-self(/ietf-interfaces:interfaces/ietf-interfaces:interface[ietf-interfaces:name=current()/../ietf-interfaces:name]/bbf-xpon:channel-termination/bbf-xpon:location, 'bbf-xpon-types:inside-olt')".
[3313643: E SYSREPO             ] Notification validation failed.
```
Regards,
Igor
[sysrepo.zip](https://github.com/sysrepo/sysrepo/files/5600441/sysrepo.zip)

**Comment by michalvasko** [comment]
Thanks for providing your repo but it is not enough, because to send the nested notification it needs the data parents to exist in the operational datastore. Could you please also provide those data? Simply a step-by-step guide for reproducing it without me needing to write any data myself. It should be easy for you and save me a lot of time because the modules are quite compilcated.

**Comment by igortern** [comment]
The attached netopeer2-cli script creates the relevant data nodes
[1.1-add-interfaces-olt.txt](https://github.com/sysrepo/sysrepo/files/5605230/1.1-add-interfaces-olt.txt)

**Comment by michalvasko** [comment]
Okay, I managed to set it all correctly but the notification was sent (and received successfully). The following was my setup.

1. Use the repository you provided.
2. Import the data you provided into `running` datastore.
3. `application_changes_example ietf-interfaces` (to make the data also present in `operational`).
4. `oper_data_example ietf-interfaces /ietf-interfaces:interfaces-state` with a patch (to create notification parents in `operational`)
```patch
diff --git a/examples/oper_data_example.c b/examples/oper_data_example.c
index 0be5241a..6a52c0c9 100644
--- a/examples/oper_data_example.c
+++ b/examples/oper_data_example.c
@@ -42,6 +42,8 @@ dp_get_items_cb(sr_session_ctx_t *session, const char *module_name, const char *
     if (!strcmp(module_name, "examples") && !strcmp(xpath, "/examples:stats")) {
         *parent = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(session)), "/examples:stats/counter", "852", 0, 0);
         lyd_new_path(*parent, NULL, "/examples:stats/counter2", "1052", 0, 0);
+    } else if (!strcmp(module_name, "ietf-interfaces")) {
+        *parent = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(session)), "/ietf-interfaces:interfaces-state/interface[name='channeltermination.1']/bbf-xpon:channel-termination", NULL, 0, 0);
     }
 
     return SR_ERR_OK;
```
5. `examples/notif_subscribe_example ietf-interfaces` (to receive the notification)
6. `examples/notif_send_example "/ietf-interfaces:interfaces-state/interface[name='channeltermination.1']/bbf-xpon:channel-termination/bbf-xpon-onu-state:onu-presence-state-change"` (send the notification)

The notification was sent successfully after all these steps so you will have to provide similar detailed steps to reproduce the problem or I will not be able to help you.

**Comment by igortern** [comment]
Hi Michal,
Your sequence generates the same error on my setup (see below). The difference in results might be because we use different compilers. I use gcc-9 which generated a number of warnings, some of them are very suspicious. I filed an issue in libyang, there are warnings in other packages as well.
Regards,
Igor

**Test1: oper_data_example.c patched as described in your post. In this case 'when' condition is not satisfied and the error message below is correct.**

4)  ./build/host-sim/third_party/sysrepo/sysrepo-devel/build/examples/oper_data_example ietf-interfaces /ietf-interfaces:interfaces-state
Application will provide data "/ietf-interfaces:interfaces-state" of "ietf-interfaces".
 ========== LISTENING FOR REQUESTS ==========
 ========== DATA FOR "ietf-interfaces" "/ietf-interfaces:interfaces-state" REQUESTED =======================

5) ./build/host-sim/third_party/sysrepo/sysrepo-devel/build/examples/notif_send_example "/ietf-interfaces:interfaces-state/interface[name='channeltermination.1']/bbf-xpon:channel-termination/bbf-xpon-onu-state:onu-presence-state-change"
Application will send notification "/ietf-interfaces:interfaces-state/interface[name='channeltermination.1']/bbf-xpon:channel-termination/bbf-xpon-onu-state:onu-presence-state-change".

[WRN]: Identityref value is not derived from all its bases. (path: /ietf-interfaces:type)
[WRN]: Failed to resolve identityref "iana-if-type:ghn". (path: /ietf-interfaces:type)
[WRN]: Previous warning generated by XPath subexpression[0] "ietf-interfaces:type = 'iana-if-type:ghn'".
[WRN]: Identityref value is not derived from all its bases. (path: /ietf-interfaces:type)
[WRN]: Failed to resolve identityref "iana-if-type:ghn". (path: /ietf-interfaces:type)
[WRN]: Previous warning generated by XPath subexpression[0] "ietf-interfaces:type = 'iana-if-type:ghn'".
[WRN]: Failed to resolve identityref "bbf-availability:unknown". (path: /bbf-vdsl:tag)
[WRN]: Previous warning generated by XPath subexpression[7] "tag='bbf-availability:unknown'".
[WRN]: Failed to resolve identityref "bbf-availability:unknown". (path: /bbf-vdsl:tag)
[WRN]: Previous warning generated by XPath subexpression[46] "tag='bbf-availability:unknown'".
[WRN]: Failed to resolve identityref "bbf-availability:unknown". (path: /bbf-fast:tag)
[WRN]: Previous warning generated by XPath subexpression[7] "tag='bbf-availability:unknown'".
[WRN]: Failed to resolve identityref "bbf-availability:unknown". (path: /bbf-fast:tag)
[WRN]: Previous warning generated by XPath subexpression[46] "tag='bbf-availability:unknown'".
[ERR]: When condition "derived-from-or-self(/ietf-interfaces:interfaces/ietf-interfaces:interface[ietf-interfaces:name=current()/../ietf-interfaces:name]/bbf-xpon:channel-termination/bbf-xpon:location, 'bbf-xpon-types:inside-olt')" not satisfied. (path: /ietf-interfaces:interfaces-state/interface[name='channeltermination.1']/bbf-xpon:channel-termination/bbf-xpon-onu-state:onu-presence-state-change)
[ERR]: Notification validation failed.

**Test2: oper_data_example.c patched to produce the 'location' leaf**
        // *parent = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(session)),
        //     "/ietf-interfaces:interfaces-state/interface[name='channeltermination.1']/bbf-xpon:channel-termination", NULL, 0, 0);
        *parent = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(session)),
            "/ietf-interfaces:interfaces-state/interface[name='channeltermination.1']/bbf-xpon:channel-termination/location", "bbf-xpon-types:inside-olt", 0, 0);

In this case notif_send_example generates the exact same error as my setup
it942490@igor-mint:10:29:31:~/Perforce/OLT/aspen/main$ ./build/host-sim/third_party/sysrepo/sysrepo-devel/build/examples/notif_send_example "/ietf-interfaces:interfaces-state/interface[name='channeltermination.1']/bbf-xpon:channel-termination/bbf-xpon-onu-state:onu-presence-state-change"
Application will send notification "/ietf-interfaces:interfaces-state/interface[name='channeltermination.1']/bbf-xpon:channel-termination/bbf-xpon-onu-state:onu-presence-state-change".

[WRN]: Identityref value is not derived from all its bases. (path: /ietf-interfaces:type)
[WRN]: Failed to resolve identityref "iana-if-type:ghn". (path: /ietf-interfaces:type)
[WRN]: Previous warning generated by XPath subexpression[0] "ietf-interfaces:type = 'iana-if-type:ghn'".
[WRN]: Identityref value is not derived from all its bases. (path: /ietf-interfaces:type)
[WRN]: Failed to resolve identityref "iana-if-type:ghn". (path: /ietf-interfaces:type)
[WRN]: Previous warning generated by XPath subexpression[0] "ietf-interfaces:type = 'iana-if-type:ghn'".
[WRN]: Failed to resolve identityref "bbf-availability:unknown". (path: /bbf-vdsl:tag)
[WRN]: Previous warning generated by XPath subexpression[7] "tag='bbf-availability:unknown'".
[WRN]: Failed to resolve identityref "bbf-availability:unknown". (path: /bbf-vdsl:tag)
[WRN]: Previous warning generated by XPath subexpression[46] "tag='bbf-availability:unknown'".
[WRN]: Failed to resolve identityref "bbf-availability:unknown". (path: /bbf-fast:tag)
[WRN]: Previous warning generated by XPath subexpression[7] "tag='bbf-availability:unknown'".
[WRN]: Failed to resolve identityref "bbf-availability:unknown". (path: /bbf-fast:tag)
[WRN]: Previous warning generated by XPath subexpression[46] "tag='bbf-availability:unknown'".
[ERR]: Irresolvable when condition "derived-from-or-self(/ietf-interfaces:interfaces/ietf-interfaces:interface[ietf-interfaces:name=current()/../ietf-interfaces:name]/bbf-xpon:channel-termination/bbf-xpon:location, 'bbf-xpon-types:inside-olt')". (path: /ietf-interfaces:interfaces-state/interface[name='channeltermination.1']/bbf-xpon:channel-termination/bbf-xpon-onu-state:onu-presence-state-change)
[ERR]: Notification validation failed.

**Comment by michalvasko** [comment]
Before I retry this on Ubuntu 18 (because it works on my OpenSUSE Tumbleweed like I said), please post the output of `# ldconfig -p | grep libyang` and then `ls -l | grep libyang` on the directory with the library to make sure you are using a recent version.

**Comment by igortern** [comment]
it942490@igor-mint:18:39:12:~/Perforce/OLT/aspen/main$ sudo ldconfig | grep libyang
it942490@igor-mint:18:39:20:~/Perforce/OLT/aspen/main$ cd build/host-sim/fs/lib
it942490@igor-mint:18:39:28:~/Perforce/OLT/aspen/main/build/host-sim/fs/lib$ ls -l | grep libyang
drwxr-xr-x 4 it942490 it942490     4096 Nov 26 14:02 libyang
lrwxrwxrwx 1 it942490 it942490       12 Nov 26 14:02 libyang.so -> libyang.so.1
lrwxrwxrwx 1 it942490 it942490       17 Dec  2 09:24 libyang.so.1 -> libyang.so.1.9.21
-rw-r--r-- 1 it942490 it942490  4065304 Dec  2 09:23 libyang.so.1.9.21

**Comment by michalvasko** [comment]
I wrote `# ldconfig -p | grep libyang` which must print something, otherwise *libyang* could not be loaded by any binary.

**Comment by michalvasko** [comment]
You keep changing what I tell you to do and then nothing works.

> Test2: oper_data_example.c patched to produce the 'location' leaf
// *parent = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(session)),
// "/ietf-interfaces:interfaces-state/interface[name='channeltermination.1']/bbf-xpon:channel-termination", NULL, 0, 0);
*parent = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(session)),
"/ietf-interfaces:interfaces-state/interface[name='channeltermination.1']/bbf-xpon:channel-termination/location", "bbf-xpon-types:inside-olt", 0, 0);

This is wrong, you are creating the leaf in `/ietf-interfaces:interfaces-state/...` but the `augment` `when` needs it in `/ietf-interfaces:interfaces/...`. That is why I had also `application_changes_example` running because it causes the data in `running` to appear in `operational`, that is what is needed here.

I have wasted enough time on this (it works fine on fresh Ubuntu 18) so unless you provide a correct way of reproducing it, I am not able to help you.

**Comment by igortern** [comment]
I found a way to reproduce and thanks to your help found a workaround.

The problem manifests if subscription in #3 in your list is done with xpath.
That is
3. application_changes_example ietf-interfaces
works
any of the following causes "[ERR]: Irresolvable when condition" when sending a notification.
3. 
application_changes_example ietf-interfaces /ietf-interfaces:interfaces
application_changes_example ietf-interfaces /ietf-interfaces:interfaces/.
application_changes_example ietf-interfaces /ietf-interfaces:interfaces//.
application_changes_example ietf-interfaces /ietf-interfaces:interfaces/*

In this particular case I can subscribe without the xpath, so there is an easy workaround 

Regards,
Igor

**Comment by igortern** [comment]
Note that when subscription is done without xpath, sr_get_changes_iter()/sr_get_next_change() produce an empty list. Below is output of 
"application_changes_example ietf-interfaces"
which was started BEFORE interface configuration was copied into the running datastore. Notice that there is nothing between "EVENT CHANGES" and "EVENT end of changes" prints

it942490@igor-mint:14:46:01:~/Perforce/OLT/aspen/main$ SYSREPO_REPOSITORY_PATH=build/host-sim/fs/sysrepo ./build/host-sim/third_party/sysrepo/sysrepo-devel/build/examples/application_changes_example ietf-interfaces 
Application will watch for changes in "ietf-interfaces".

 ========== READING RUNNING CONFIG: ==========

/ietf-interfaces:interfaces (container)


 ========== LISTENING FOR CHANGES ==========




 ========== EVENT change CHANGES: ====================================


 ========== END OF CHANGES =======================================

 ========== EVENT done CHANGES: ====================================


 ========== END OF CHANGES =======================================

 ========== CONFIG HAS CHANGED, CURRENT RUNNING CONFIG: ==========

/ietf-interfaces:interfaces (container)
/ietf-interfaces:interfaces/interface[name='channelgroup.1'] (list instance)
/ietf-interfaces:interfaces/interface[name='channelgroup.1']/name = channelgroup.1
/ietf-interfaces:interfaces/interface[name='channelgroup.1']/type = bbf-xpon-if-type:channel-group
/ietf-interfaces:interfaces/interface[name='channelgroup.1']/enabled = true
/ietf-interfaces:interfaces/interface[name='channelgroup.1']/bbf-qos-traffic-mngt:tm-root (container)
/ietf-interfaces:interfaces/interface[name='channelgroup.1']/bbf-interfaces-performance-management:performance (container)
/ietf-interfaces:interfaces/interface[name='channelgroup.1']/bbf-interfaces-performance-management:performance/enable = false [default]
/ietf-interfaces:interfaces/interface[name='channelgroup.1']/bbf-xpon:channel-group (container)
/ietf-interfaces:interfaces/interface[name='channelgroup.1']/bbf-xpon:channel-group/polling-period = 100
/ietf-interfaces:interfaces/interface[name='channelgroup.1']/bbf-xpon:channel-group/raman-mitigation = raman-none
/ietf-interfaces:interfaces/interface[name='channelgroup.1']/bbf-xpon:channel-group/system-id = 00000
/ietf-interfaces:interfaces/interface[name='channelgroup.1']/bbf-xpon:channel-group/pon-pools (container)
/ietf-interfaces:interfaces/interface[name='channelgroup.1']/bbf-xpon:channel-group/pon-pools/pon-pool[name='pool1'] (list instance)
/ietf-interfaces:interfaces/interface[name='channelgroup.1']/bbf-xpon:channel-group/pon-pools/pon-pool[name='pool1']/name = pool1
/ietf-interfaces:interfaces/interface[name='channelgroup.1']/bbf-xpon:channel-group/pon-pools/pon-pool[name='pool1']/channel-termination-ref = channeltermination.1
/ietf-interfaces:interfaces/interface[name='channelpartition.1'] (list instance)
/ietf-interfaces:interfaces/interface[name='channelpartition.1']/name = channelpartition.1
/ietf-interfaces:interfaces/interface[name='channelpartition.1']/type = bbf-xpon-if-type:channel-partition
/ietf-interfaces:interfaces/interface[name='channelpartition.1']/enabled = true
/ietf-interfaces:interfaces/interface[name='channelpartition.1']/bbf-qos-traffic-mngt:tm-root (container)
/ietf-interfaces:interfaces/interface[name='channelpartition.1']/bbf-interfaces-performance-management:performance (container)
/ietf-interfaces:interfaces/interface[name='channelpartition.1']/bbf-interfaces-performance-management:performance/enable = false [default]
/ietf-interfaces:interfaces/interface[name='channelpartition.1']/bbf-xpon:channel-partition (container)
/ietf-interfaces:interfaces/interface[name='channelpartition.1']/bbf-xpon:channel-partition/channel-group-ref = channelgroup.1
/ietf-interfaces:interfaces/interface[name='channelpartition.1']/bbf-xpon:channel-partition/channel-partition-index = 0
/ietf-interfaces:interfaces/interface[name='channelpartition.1']/bbf-xpon:channel-partition/closest-onu-distance = 0
/ietf-interfaces:interfaces/interface[name='channelpartition.1']/bbf-xpon:channel-partition/maximum-differential-xpon-distance = 20
/ietf-interfaces:interfaces/interface[name='channelpartition.1']/bbf-xpon:channel-partition/authentication-method = serial-number
/ietf-interfaces:interfaces/interface[name='channelpartition.1']/bbf-xpon:channel-partition/downstream-fec = true [default]
/ietf-interfaces:interfaces/interface[name='channelpartition.1']/bbf-xpon:channel-partition/multicast-aes-indicator = false [default]
/ietf-interfaces:interfaces/interface[name='channelpair.1'] (list instance)
/ietf-interfaces:interfaces/interface[name='channelpair.1']/name = channelpair.1
/ietf-interfaces:interfaces/interface[name='channelpair.1']/type = bbf-xpon-if-type:channel-pair
/ietf-interfaces:interfaces/interface[name='channelpair.1']/enabled = true
/ietf-interfaces:interfaces/interface[name='channelpair.1']/bbf-qos-traffic-mngt:tm-root (container)
/ietf-interfaces:interfaces/interface[name='channelpair.1']/bbf-interfaces-performance-management:performance (container)
/ietf-interfaces:interfaces/interface[name='channelpair.1']/bbf-interfaces-performance-management:performance/enable = false [default]
/ietf-interfaces:interfaces/interface[name='channelpair.1']/bbf-xpon:channel-pair (container)
/ietf-interfaces:interfaces/interface[name='channelpair.1']/bbf-xpon:channel-pair/channel-partition-ref = channelpartition.1
/ietf-interfaces:interfaces/interface[name='channelpair.1']/bbf-xpon:channel-pair/channel-group-ref = channelgroup.1
/ietf-interfaces:interfaces/interface[name='channelpair.1']/bbf-xpon:channel-pair/wavelength-prof-ref = wavelengthprofile.A
/ietf-interfaces:interfaces/interface[name='channelpair.1']/bbf-xpon:channel-pair/channel-pair-type = bbf-xpon-types:xgs
/ietf-interfaces:interfaces/interface[name='channeltermination.1'] (list instance)
/ietf-interfaces:interfaces/interface[name='channeltermination.1']/name = channeltermination.1
/ietf-interfaces:interfaces/interface[name='channeltermination.1']/type = bbf-xpon-if-type:channel-termination
/ietf-interfaces:interfaces/interface[name='channeltermination.1']/enabled = true
/ietf-interfaces:interfaces/interface[name='channeltermination.1']/bbf-interface-port-reference:port-layer-if = PORT2
/ietf-interfaces:interfaces/interface[name='channeltermination.1']/bbf-qos-traffic-mngt:tm-root (container)
/ietf-interfaces:interfaces/interface[name='channeltermination.1']/bbf-interfaces-performance-management:performance (container)
/ietf-interfaces:interfaces/interface[name='channeltermination.1']/bbf-interfaces-performance-management:performance/enable = false [default]
/ietf-interfaces:interfaces/interface[name='channeltermination.1']/bbf-xpon:channel-termination (container)
/ietf-interfaces:interfaces/interface[name='channeltermination.1']/bbf-xpon:channel-termination/channel-pair-ref = channelpair.1
/ietf-interfaces:interfaces/interface[name='channeltermination.1']/bbf-xpon:channel-termination/channel-termination-type = bbf-xpon-types:xgs
/ietf-interfaces:interfaces/interface[name='channeltermination.1']/bbf-xpon:channel-termination/xgs-pon-id = 0
/ietf-interfaces:interfaces/interface[name='channeltermination.1']/bbf-xpon:channel-termination/location = bbf-xpon-types:inside-olt
/ietf-interfaces:interfaces/interface[name='channeltermination.1']/bbf-xpon:channel-termination/bbf-xpon-onu-state:notifiable-onu-presence-states[.='bbf-xpon-onu-types:onu-present-and-on-intended-channel-termination'] = bbf-xpon-onu-types:onu-present-and-on-intended-channel-termination
/ietf-interfaces:interfaces/interface[name='channeltermination.1']/bbf-xpon:channel-termination/bbf-xpon-onu-state:notifiable-onu-presence-states[.='bbf-xpon-onu-types:onu-present-and-v-ani-known-and-o5-failed'] = bbf-xpon-onu-types:onu-present-and-v-ani-known-and-o5-failed
/ietf-interfaces:interfaces/interface[name='channeltermination.1']/bbf-xpon:channel-termination/ber-calc-period = 10 [default]
/ietf-interfaces:interfaces/interface[name='uplink.1'] (list instance)
/ietf-interfaces:interfaces/interface[name='uplink.1']/name = uplink.1
/ietf-interfaces:interfaces/interface[name='uplink.1']/type = iana-if-type:ethernetCsmacd
/ietf-interfaces:interfaces/interface[name='uplink.1']/enabled = true [default]
/ietf-interfaces:interfaces/interface[name='uplink.1']/bbf-qos-traffic-mngt:tm-root (container)
/ietf-interfaces:interfaces/interface[name='uplink.1']/bbf-interfaces-performance-management:performance (container)
/ietf-interfaces:interfaces/interface[name='uplink.1']/bbf-interfaces-performance-management:performance/enable = false [default]
/ietf-interfaces:interfaces/interface[name='uplink.1']/ieee802-dot1x:pae (container)
/ietf-interfaces:interfaces/interface[name='uplink.1']/ieee802-dot1x:pae/port-capabilities (container)
/ietf-interfaces:interfaces/interface[name='uplink.1']/ieee802-dot1x:pae/logon-nid (container)
/ietf-interfaces:interfaces/interface[name='uplink.1']/ieee802-dot1x:pae/logon-process (container)
/ietf-interfaces:interfaces/interface[name='uplink.1']/ieee802-dot1x:pae/logon-process/logon = false [default]
/ietf-interfaces:interfaces/interface[name='uplink.1']/bbf-l2-forwarding:mac-learning (container)
/ietf-interfaces:interfaces/interface[name='uplink.1']/bbf-l2-forwarding:mac-learning/max-number-mac-addresses = 4294967295 [default]
/ietf-interfaces:interfaces/interface[name='uplink.1']/bbf-l2-forwarding:mac-learning/number-committed-mac-addresses = 1 [default]
/ietf-interfaces:interfaces/interface[name='uplink.1']/bbf-l2-forwarding:mac-learning/mac-learning-enable = true [default]
/ietf-interfaces:interfaces/interface[name='uplink.1']/bbf-l2-forwarding:mac-learning/mac-learning-failure-action = forward [default]
/ietf-interfaces:interfaces/interface[name='uplink.1']/bbf-interface-usage:interface-usage (container)

**Comment by michalvasko** [comment]
Thank you for finally providing steps to reproduce it, it should now be fixed. The other problem with no module changes as well.

**Comment by igortern** [comment]
Great. Thanks Michal!
