### ISSUE TITLE
startup datastore not updated when leaf with default value deleted

### ISSUE THREAD

**Issue by mdoshi-com** [sysrepo/sysrepo#2230]
Hi,
Use case as follows:
1. configure data in running datastore (via netopeer2-client)
2. applications does m_startupDBSession->copy_config(SR_DS_RUNNING, NULL , 0, 0); to store data in startup also.
3. delete a leaf of the configuration, done in step 1, from the running datastore

```
<ManagedElement xmlns="urn:3gpp:sa5:_3gpp-common-managed-element" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" >
  <id>MEid</id>
  <attributes>
    <priorityLabel>1</priorityLabel>
  </attributes>
  <GNBDUFunction xmlns="urn:3gpp:sa5:_3gpp-nr-nrm-gnbdufunction">
    <id>GNBDUid</id>
          <NRCellDU  xmlns="urn:3gpp:sa5:_3gpp-nr-nrm-nrcelldu" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
                <id>nrcellduid</id>
                <attributes>
                        <administrativeState xc:operation="delete">UNLOCKED</administrativeState>
                </attributes>
        </NRCellDU>
  </GNBDUFunction>
</ManagedElement>

```

4. the leaf deleted has default value in yang, snippet:
leaf administrativeState  {
      description "Administrative state of the NRCellDU. Indicates the
        permission to use or prohibition against using the cell, imposed
       through the OAM services.";
      type types3gpp:AdministrativeState;
      default LOCKED;
   }

5. applications does m_startupDBSession->copy_config(SR_DS_RUNNING, NULL , 0, 0); to again update deletion in startup also.

6. get-data done from netopeer2-client
`get-data  --datastore startup --filter-xpath  /_3gpp-common-managed-element:* --defaults report-all`

"administrativeState" leaf was not at all present in the get-data reply.

Our understanding was that since leaf is deleted and the leaf has default value, startup datastore would show that leaf in the get-data reply, with default value LOCKED.

Is this an issue or our interpretation is not proper.

Regards,
Meghna

**Comment by mdoshi-com** [comment]
Hi,
Able to check this?

Regards,
Meghna

**Comment by michalvasko** [comment]
Right, please update *netopeer2* and try again, it should work now.
