### ISSUE TITLE
How to purge the changes in session object

### ISSUE THREAD

**Issue by kavk7** [sysrepo/sysrepo#2234]
Hi Team,

How to purge the changes in the session object on sr_apply_changes API failure.

say, we want to re-use the Session object as below,
1.  sess = std::make_shared<sysrepo::Session>(conn,SR_DS_RUNNING);
2. Perform sr_delete_item (sess, "ABC/leaf-1") returns success and 
     "sr_apply_changes (sess)" fails.
3. Now do,  sr_delete_item(sess, "ABC/leaf-2") returns success and 
     "sr_apply_changes(sess)" succeeds.
 
output: ABC/leaf-1 & ABC/leaf-2 gets deleted.
expected output: ABC/leaf-2 to be deleted but not ABC/leaf-1.

So, here how to purge the changes in session object on sr_apply_changes API fails.

Thank you.

**Comment by michalvasko** [comment]
Use [sr_discard_changes()](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__edit__data__api.html#gaa9ed91647148a45a03b22a7ca6f9e552).

**Comment by kavk7** [comment]
Thank you Michal.
