### ISSUE TITLE
My edit-config delete operation RPC callback has an error, but the rollback fails

### ISSUE THREAD

**Issue by esend7881** [sysrepo/sysrepo#2236]
I am testing delete operations with edit-config (for reference, I overcame this [issue here](https://github.com/CESNET/netopeer2/issues/772)) and I am testing for failure. 

Specifically I am testing an edit-config rpc for deletion of an element, but I am injecting an error in the loop to ensure that if a problem arises in the underlying logic of the system, I don't want the config to actually get deleted. 

On the python side, here is snippets of my code:
```.python
conn = sr.Connection(sr.SR_CONN_DEFAULT)
sess = sr.Session(conn)
subscribe = sr.Subscribe(sess)
subscribe.rpc_subscribe("/ietf-netconf:edit-config", rpc_cb, None)
sr.global_loop()
```
And the callback:

```.python
def rpc_cb(sess, xpath, vals, event_id, request_id, vals_holder, private_data):
   sess.set_error("Config was not processed: " + msg_back, xpath)
   return sr.SR_ERR_EXISTS
```

And the edit-config xml is:
```.xml
<?xml version="1.0" encoding="utf-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="2">
	<edit-config xmlns='urn:ietf:params:xml:ns:netconf:base:1.0'>
		<target><running/></target>
		<config xmlns:xc='urn:ietf:params:xml:ns:netconf:base:1.0'>
			<MyModel xmlns='urn:com:tug:mymodel'>
				<Elem1>
					<Elem2 xc:operation='delete'>
						<id>114</id>
					</Elem2>
				</Elem1>
			</MyModel>
		</config>
	</edit-config>
</rpc>]]>]]>
```

My expectation is returning sr.SR_ERR___ will tell sysrepo to abort or rollback changes. In fact, netopeer2-server's log seems so say that the `delete` failed:

> netopeer2-server[704]: Published event "rpc" "/ietf-netconf:edit-config" with ID 38 priority 0 for 2 subscribers.
> netopeer2-server[704]: Processing "/ietf-netconf:edit-config" "rpc" event with ID 38 priority 0 (remaining 2 subscribers).
> netopeer2-server[704]: edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
> netopeer2-server[704]: There are no subscribers for changes of the module "MyModule" in running DS.
> netopeer2-server[704]: Event "rpc" with ID 38 priority 0 failed (Item already exists).
> netopeer2-server[704]: Published event "abort" "/ietf-netconf:edit-config" with ID 38 priority 0 for 1 subscribers.
> netopeer2-server[704]: Failed to send an RPC (User callback failed).
> netopeer2-server[704]: Session 42: thread 3 event new RPC.
> netopeer2-server[704]: Session 42: thread 3 event reply error.
> netopeer2-server[704]: Processing "/ietf-netconf:edit-config" "abort" event with ID 38 priority 0 (remaining 1 subscribers).
> netopeer2-server[704]: edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
> netopeer2-server[704]: Node "Elem2" to be deleted does not exist.
> netopeer2-server[704]: Applying operation "delete" failed.
> netopeer2-server[704]: Successful processing of "abort" event with ID 38 priority 0 (remaining 0 subscribers).
>

However, when I run my `get-config` the element is gone! So sysrepo is still performing the deletion without a proper abort/rollback.

(For the record, for non-delete operations -- i.e., normal edit-configs -- errors do result in an abort and the new elements don't end up in sysrepo)

- sysrepo 1.4.70
  - compiled with `cmake -DGEN_LANGUAGE_BINDINGS=ON ..`
- netopeer2 1.1.39 
  - compiled with `cmake -DSYSREPO_TIMEOUT=119 -DRPC_TIMEOUT=120 ..`
- libyang 1.0.184 
  - compiled with `cmake -DGEN_LANGUAGE_BINDINGS=ON ..`
- CentOS 7
- python 2.7.5/3.6.8

**Comment by michalvasko** [comment]
Right, I think you are affected by a bug fixed in 134ae643d3afa13867c1fd748a72514edc3a6c4b. If you use the current `devel`, you should see an error when subscribing because you have used the same priority as the *netopeer2* callback, that causes the problem. Also, support for rollback for `edit-config` is well supported by default in *sysrepo* so you should not do it the way you do. When the changes are being applied, all the callbacks for each small change can fail that will cause the whole edit-config to abort and roll back to the previous state. That offers much more options that your solution.

**Comment by esend7881** [comment]
> Right, I think you are affected by a bug fixed in [134ae64](https://github.com/sysrepo/sysrepo/commit/134ae643d3afa13867c1fd748a72514edc3a6c4b). If you use the current `devel`, you should see an error when subscribing because you have used the same priority as the _netopeer2_ callback, that causes the problem. Also, support for rollback for `edit-config` is well supported by default in _sysrepo_ so you should not do it the way you do. When the changes are being applied, all the callbacks for each small change can fail that will cause the whole edit-config to abort and roll back to the previous state. That offers much more options that your solution.

My intention is to have that rollback occur. What step am I missing?

**Comment by michalvasko** [comment]
You are not supposed to subscribe to `edit-config` RPC but instead to `MyModel` (in your example) module data changes. Then, when your callback is called on the edit-config you simply return an error value. The rest is handled by *sysrepo*.

**Comment by esend7881** [comment]
> You are not supposed to subscribe to `edit-config` RPC but instead to `MyModel` (in your example) module data changes. Then, when your callback is called on the edit-config you simply return an error value. The rest is handled by _sysrepo_.

Interesting -- well I do find that subscribing to the edit-config RPC works perfectly. I do recall trying to subscribe to `MyModel` and finding problems with it. Maybe I should try again.

Is there an example out there of subscribing to `MyModel` such that edit-config events against `MyModel` fire the callback? Does that example include operations such as delete?

**Comment by michalvasko** [comment]
Yes, it includes all the operations and you can easily test changing the configuration and looking at the changes with `sysrepo/examples/application_changes_example`.

**Comment by esend7881** [comment]
> Yes, it includes all the operations and you can easily test changing the configuration and looking at the changes with `sysrepo/examples/application_changes_example`.

And it works fully in v1.4.70? For now, we are using only that version until a tech refresh.

**Comment by michalvasko** [comment]
This feature is the basis of *sysrepo*, it should be working with the very first release 1.x.
