### ISSUE TITLE
IP Address and Port specification for sr_connect() and FD for Polling mechanism

### ISSUE THREAD

**Issue by ankit7gup** [sysrepo/sysrepo#2237]
Hi Michal, 

I am writing an application using sysrepo to replace existing confd application code. I expect to have minimum rework, I need below information if you can provide. 

1. In the application, we want to use a specific IP address and Port number that application can connect to(Same shall be used in Server side for listening as well).
2. Is there any File Descriptor involved in sysrepo that can be used for the polling mechanism in sysyrepo as well.

Thanks in Advance!

Regards,
Ankit

**Comment by michalvasko** [comment]
We should first clear up some confusion because *sysrepo* is strictly local application and it does not listen on any IP or port. It is only if *netopeer2* is also installed that the listening interface is provided. So, can you please specify again what it is you want to achieve?

**Comment by ankit7gup** [comment]
HI Michal, Netopeer-2 is also installed here. I expect the application to talk to Server using a particular IP, Similar to what we have in confd. May be you can provide more info on how this can be done along with netopeer2.

Thanks for the quick response everytime.

**Comment by michalvasko** [comment]
Okay, you can connect to *netopeer2* remotely or locally and use NETCONF over TCP/IP. Or you can "connect" locally to *sysrepo* and use its API directly while also possibly `poll(3)` for any new events. What exactly do you need help with?

**Comment by ankit7gup** [comment]
So, The end goal is to have 2 Netconf servers running on one linux server and 2 set of applications able to differentiate which server they want to connect to, and 
Server A-------App1
Server B-------App2
I was assuming this differentiation to be done on the basis of IP Address and Port for both servers and applications.

Is it something possible in the current implementation?

**Comment by michalvasko** [comment]
You cannot have 2 Netconf servers running on one machine with independent datastores. But I am wondering whether you really need it? The server can listen on as many interfaces as you want.

**Comment by ankit7gup** [comment]
Ok, Thanks Michal for the response. I ight come back to you on this with more info later.

Regarding the second query for poll(). It seems like no FD is there in connection/session context. So, how can the polling API be utilized?

Thanks!

**Comment by michalvasko** [comment]
Info in the [docs](https://netopeer.liberouter.org/doc/sysrepo/master/html/subs.html).

**Comment by ankit7gup** [comment]
Got it! Thanks!

Now coming back to original query related to IP address and PORT No.

QUERY 1: It is our internal yang schema differentiation, that has given us the need of having 2 servers running on same server.

Parent --> has Common parameters and APP A  child and 
Parent --> has common parameters and APP B child
So we are looking for two different servers ;;;; Since the data model is not combined for some internal reasons as
Parent --> common params, APP A and APP B.

QUERY 2: Secondly, In case of cloud systems, when running different PODs for Server and Sysrepo Application(s), how can the applications connect with the server and communicate.

**Comment by michalvasko** [comment]
1) So you have several YANG modules? You can install all of them in one *sysrepo* or what is the problem? Then each APP can only work with the data it wants to, do not have to be all.
2) The final architecture is to great extent up to you. But I think you are still mixing thing up, that is why I have significant problems understanding you. Like I said, you **cannot** have *sysrepo* application on one machine and *sysrepo* itself (the server technically) on another, it works strictly locally. What you can have is *netopeer2* (with *sysrepo*) on one machine and a NETCONF client (*netopeer2-cli*) on another, connected to each other.

**Comment by ankit7gup** [comment]
For first point, We have some internal reasons, due to which we need two servers. [This we will see if we can resolve for our yang schemas].

The second point I consider to be a valid scenario, considering CONFD as a reference, as it applies to our use case as well. 
Can you please suggest if not present currently, then is there any plan in the future to have such functionality, where we can have sysrepo server and sysrepo application working on different machines or in two different containers(for cloud based systems). 
Thanks!

**Comment by michalvasko** [comment]
I do not know basically anything about ConfD and is not a reference for me anyway, so it is redundant to mention it. However, there is an ongoing effort by @imiller0 to enable having separate instances of *sysrepo* in containers. I have merged 2 pull requests of his but I am not sure how far it still is from being functioning, maybe he can tell you more.

**Comment by ankit7gup** [comment]
Thanks for the info Michal. Also apologies for mentioning confd in this context.
Appreciate your help and support always!

**Comment by imiller0** [comment]
The work I've been adding allows access to a _single_ sysrepo instance but from multiple containers running on the same system.  Likely not much help here if multiple/independent instances are required.

**Comment by myonlystarWang** [comment]
> The work I've been adding allows access to a _single_ sysrepo instance but from multiple containers running on the same system. Likely not much help here if multiple/independent instances are required.

Could you please paste the link of this pull request here?
I'm kind of interested in this feature,thanks.

**Comment by michalvasko** [comment]
Here it is https://github.com/sysrepo/sysrepo/pull/2218

**Comment by myonlystarWang** [comment]
> Here it is #2218

Thanks very much for it, michal.
