### ISSUE TITLE
Regex suggestions for change values?

### ISSUE THREAD

**Issue by esend7881** [sysrepo/sysrepo#2238]
(This is semi in reference to #2236)
I noticed when parsing through changes in the module subscription, the lines come out in a format like this:

```
/MyModel:Elem1/Elem2/Elem3[id='12345'] (list instance)
```

I'm just curious if there is a good regex out there you use to parse though the elements of that string? If not regex, a function that can explode that into a list?

**Comment by michalvasko** [comment]
> a function that can explode that into a list?

I do not know what you mean by this. There are some helper functions in `sysrepo/xpath.h` that may help. Also, like always, you do not have to have the data represented in this format and use `_tree` function variants instead, which is preferred anyway.

**Comment by esend7881** [comment]
> > a function that can explode that into a list?
> 
> I do not know what you mean by this. There are some helper functions in `sysrepo/xpath.h` that may help. Also, like always, you do not have to have the data represented in this format and use `_tree` function variants instead, which is preferred anyway.

I was looking through the API and the various sysrepo classes, such as `S_Val` and `S_Data` and its not clear which one has a `_tree` format. Is there an example of how to work with the data in a tree format from within Python?

**Comment by esend7881** [comment]
Is it possible to get the config in a json format?

**Comment by michalvasko** [comment]
> I was looking through the API and the various sysrepo classes, such as S_Val and S_Data and its not clear which one has a _tree format.

[This one](https://netopeer.liberouter.org/doc/sysrepo/master/html/classsysrepo_1_1_session.html#ab12d524734055947a65ca8144a152a20).

> Is it possible to get the config in a json format?

You can get the config in the tree format which is generic and can be printed into XML or JSON, if you wish.

**Comment by esend7881** [comment]
I think I found out how to get the config in an XML format. I wanted to show you what I came up with and see if it aligned with your advice. It namely evolved around the `print_mem` function:
```.python
it = sess.get_changes_iter(change_path)
change = sess.get_change_tree_next(it)
node = change.node()
#Loop until we get the highest parent... So I only look at the first change and just climb to the highest parent and that's it. 
#The highest parent should have all my wanted changes/new items with in.
while node.parent() is not None: node = node.parent()
xml_config = node.print_mem(yang.LYD_XML, yang.LYP_NETCONF | yang.LYP_WITHSIBLINGS | yang.LYP_FORMAT)
```
This returns something along the line of: 

```.xml
<MyModel xmlns="urn:com:tug:mymodel-full" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:sr="http://www.sysrepo.org/yang/sysrepo" sr:operation="none">
  <Elem1 sr:operation="none">
    <Elem2 nc:operation="create">
      <id>105</id>
      <priority nc:operation="create">2</priority>
      <name nc:operation="create">name</name>
      <match nc:operation="create">
        <in-port nc:operation="create">4</in-port>
      </match>
      <action nc:operation="create">
        <order>0</order>
        <output-action nc:operation="create">
          <output-node-connector nc:operation="create">1</output-node-connector>
          <max-length nc:operation="create">60</max-length>
        </output-action>
      </action>
    </Elem2>
  </Elem1>
</MyModel>
```

It looks like `nc:operation` and `sr:operation` get injected to each element. I am also looping to get the highest parent of the first change with the intent that it will include the entire config submitted via the `edit-config` command

**Comment by michalvasko** [comment]
You were talking about config, these are changes you are printing. It can work, I suppose, but the tree you print for all the changes will always be the same this way.
