### ISSUE TITLE
sr_lyd_node2sr_val() does not provide values for anyxml and anydata

### ISSUE THREAD

**Issue by pfeige** [sysrepo/sysrepo#2240]
The function sr_lyd_node2sr_val() in sysrepo.c does not provide value strings for nodes of the type LYS_ANYXML and LYS_ANYDATA. The corresponding struct members data.anyxml_val and data.anydata_val remain NULL.

**Comment by michalvasko** [comment]
Could you point me to the actual function in the current code? I did not manage to find it and both `anydata` and `anyxml` should be handled correctly.

**Comment by pfeige** [comment]
It is sysrepo.c:3645. Only the type is set, not the data value.

    case LYS_ANYXML:
        sr_val->type = SR_ANYXML_T;
        break;
    case LYS_ANYDATA:
        sr_val->type = SR_ANYDATA_T;
        break;

**Comment by michalvasko** [comment]
Eh, you even mentioned it before, I just automatically went on my assumption that the code will not be duplicated and looked into `common.c`, sorry. Anyway, the code is duplicate because of lacking *libyang* API, sadly, so I simply copied the functionality over, should work now.

**Comment by pfeige** [comment]
Thanks!
