### ISSUE TITLE
Performance issue with lots of edits

### ISSUE THREAD

**Issue by choppsv1** [sysrepo/sysrepo#2242]
I'm looking at using sysrepo (well more generally YANG) as a way to standardize API access to various databases (e.g., RIB, TEDB, policy, etc).

I've identified a few performance issues with the latest sysrepo. I'm curious if these are known and if there are any plans to address them... (filing separate issues for each)

One issue is applying changes always rewrites the entire shared memory file representing the datastore. This makes many small non-batched changes very expensive, as well as seeming very inefficient for large datastores.

**Comment by michalvasko** [comment]
Yes, you are completely right because while the used datastore is completely generic, it is very inefficient. We are planning to address this by implementing a custom datastore mechanism in Q1/Q2 next year probably that will allow changing the datastore for an arbitrary one using plugins. That should allow using some kind of database instead which should most likely be still completely generic but with much better performance.

**Comment by choppsv1** [comment]
@michalvasko this is very interesting news given my current context of looking at this. In particular I am looking at using sysrepo/YANG to model and implement APIs to various databases. One of the things I looked at was the oper subscriptions that currently exist (but are not sufficient). I did this b/c the way I envision this working best is to have the given DB (e.g., a RIB manager) actually hold the "datastore" state, and then clients (e.g., OSPF) could pull from, push to, and subscribe to changes using sysrepo/YANG from that DB. In light of what you say above the RIB manager in this case could implement the datastore plugin and the clients would interact normally with sysrepo. 

What is the granularity of the backend datastore plugin API you are planning for in Q1/Q2? It would be good if multiple simultaneous backend datastore plugins were supported, at least in my case, as I could then implement the above with it. That is, in my system I would have multiple DB managers in different processes serving the datastore data. So perhaps on a module basis? It might also work to support sets of datastores (so startup, running and operational become classes of instances  of datastores (instead of a single set of them) and multiple backends could register their own set of datastores. The latter might be easier to implement than per module, although it would mean clients might have to maintain multiple connections/contexts when they are interested in multiple DBs (and thus sets of datastores).

**Comment by michalvasko** [comment]
Yes, your idea is correct and should be allowed with the custom datastore.

I cannot really tell you much details, it is just a plan for now. But the idea was to keep the data separated by modules with allowing each module to use its own datastore implementation.
