### ISSUE TITLE
Previous event "done" with ID was not processed

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2243]
Hi,

I met the issue again when sysrepo gets into faulty state and all **sr_apply_changes** attempt will result in similar error:

`Locking subscription of "ietf-interfaces" failed, previous event "done" with ID 1 was not processed.`

I figured out that it happens when a new config change callback is registered before DONE events are processed for a running **sr_apply_changes**, and value of **multi_sub_shm->subscriber_count** gets faulty:

`Successful processing of "done" event with ID 1 priority 0 (remaining 4294967295 subscribers).`

After it all **sr_apply_changes** attempts will fail in ietf-interfaces.

I created example applications and script for it:
[timeout_error.zip](https://github.com/sysrepo/sysrepo/files/5644088/timeout_error.zip)

```
./script.sh
***** Starting subscribe
[INF]: Applying scheduled changes.
[INF]: No scheduled changes.
[INF]: Datastore copied from <startup> to <running>.
[INF]: Session 1 (user "devuser") created.
[INF]: There are no subscribers for changes of the module "ietf-interfaces" in running DS.
sr_apply_changes OK
***** Change eth0 interface
[INF]: Scheduled changes not applied because of other existing connections.
[INF]: Session 2 (user "devuser") created.
sr_apply_changes...
[INF]: Published event "done" "ietf-interfaces" with ID 1 priority 0 for 1 subscribers.
[ERR]: Callback event "done" with ID 1 processing timed out.
sr_apply_changes OK
sr_module_change_subscribe OK
[INF]: Processing "ietf-interfaces" "done" event with ID 1 priority 0 (remaining 1 subscribers).
[INF]: Successful processing of "done" event with ID 1 priority 0 (remaining 4294967295 subscribers).

***** Try to change eth1 interface
[INF]: Scheduled changes not applied because of other existing connections.
[INF]: Session 3 (user "devuser") created.
sr_apply_changes...
[ERR]: Locking subscription of "ietf-interfaces" failed, previous event "done" with ID 1 was not processed.
sr_apply_changes error, rc=13

```
sysrepo version: 1.4.92
libyang version: 1.0.20

Thanks!

**Comment by michalvasko** [comment]
Right, it should be fixed but these use-cases are borderline valid. On one hand, we do want to make *sysrepo* as robust as possible so thanks you for providing a nice example for reproducing the issue. But on the other hand, as soon as any event times out, it is no longer a valid use-case and it should never happen in production-like environment.

**Comment by awesomenode** [comment]
I cannot reproduce it anymore, thanks!
