### ISSUE TITLE
sr_validate with callbacks

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2245]
Hi,

I have callback based validation implemented in **SR_SUBSCR_UPDATE** event handlers.
I need to use **sr_validate**() with full validation including the callbacks, but currently it provides only YANG validation.
Is it possible to add validation support with callbacks?

Thanks!

**Comment by michalvasko** [comment]
No, that is not supported because the callbacks are called only for some actual changes, there would be none in this case.

**Comment by awesomenode** [comment]
Thank you for the answer, I managed to solve it on application level.
