### ISSUE TITLE
netopeer2-cli is unable to parse embedded notification

### ISSUE THREAD

**Issue by igortern** [sysrepo/sysrepo#2246]
Hi,

Perquisites: notopeer2, sysrepo, libyang, libnetconf from devel, pulled on Dec 7
sysrepo repository, data as per https://github.com/sysrepo/sysrepo/issues/2229

- Execute steps 1-5 described in https://github.com/sysrepo/sysrepo/issues/2229#issuecomment-736535570
- Subscribe to notifications in netopeer2-cli
- Execute step 6 from the comment above

notif_subscribe_example prints the received notification, as it should
 ========== NOTIFICATION "/ietf-interfaces:interfaces-state/interface[name='channeltermination.1']/bbf-xpon:channel-termination/bbf-xpon-onu-state:onu-presence-state-change" RECEIVED =======================

netopeer2-cli prints the following message:

\> verb 2
\> 
nc VERBOSE: Session 1: received message:
`<notification xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0"><eventTime>2020-12-07T00:38:22Z</eventTime><interfaces-state xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces"><interface><name>channeltermination.1</name><channel-termination xmlns="urn:bbf:yang:bbf-xpon"><onu-presence-state-change xmlns="urn:bbf:yang:bbf-xpon-onu-state"/></channel-termination></interface></interfaces-state></notification>
`
\> 
ly VERBOSE: Resolving unresolved data nodes and their constraints...
\> 
**nc ERROR: Session 1: failed to parse a new notification.**

**Comment by michalvasko** [comment]
Okay, if you pull latest *libnetconf2*, it should work.

**Comment by igortern** [comment]
It works now. Thanks!
