### ISSUE TITLE
ietf-interface not working after installing ieee802-dot1ab-lldp

### ISSUE THREAD

**Issue by Maku-chan** [sysrepo/sysrepo#2248]
Hello,

I installed the ieee802-dot1ab-lldp yang model in the sysrepo. In the installation the ietf-interfaces yang model was required so I provided it but it seems it installed the ietf-interfaces again and now it is not working any more.
The list of installed models are mentioned below.
ietf-netconf-notifications | 2012-02-06 | Installed   | root:root           | 777         |                               |
ietf-netconf               | 2011-06-01 | Installed   | root:root           | 777         |                               | writable-running candidate rollback-on-error validate startup xpath
ietf-netconf-acm           | 2018-02-14 | Imported    |                     |             |                               |
nc-notifications           | 2008-07-14 | Installed   | root:root           | 777         |                               |
notifications              | 2008-07-14 | Installed   | root:root           | 777         |                               |
ietf-x509-cert-to-name     | 2014-12-10 | Installed   |                     |             |                               |
ietf-keystore              | 2016-10-31 | Installed   | root:root           | 777         |                               |
ietf-netconf-with-defaults | 2011-06-01 | Installed   |                     |             |                               |
ietf-netconf-monitoring    | 2010-10-04 | Installed   | root:root           | 777         |                               |
ietf-yang-library          | 2018-01-17 | Installed   | root:root           | 777         |                               |
ietf-datastores            | 2017-08-17 | Imported    |                     |             |                               |
ietf-netconf-server        | 2016-11-02 | Installed   | root:root           | 777         |                               | listen ssh-listen tls-listen call-home ssh-call-home tls-call-home
ietf-ssh-server            | 2016-11-02 | Imported    |                     |             |                               |
ietf-tls-server            | 2016-11-02 | Imported    |                     |             |                               |
ietf-system                | 2014-08-06 | Installed   | root:root           | 777         |                               | authentication local-users
iana-crypt-hash            | 2014-08-06 | Imported    |                     |             |                               |
ietf-interfaces            | 2018-02-20 | Installed   | root:root           | 777         |                               |
iana-if-type               | 2014-05-08 | Installed   |                     |             |                               |
ieee802-dot1q-types        | 2018-03-07 | Installed   |                     |             |                               |
ieee802-dot1q-preemption   | 2018-09-10 | Installed   |                     |             |                               |
ieee802-dot1q-sched        | 2018-09-10 | Installed   |                     |             |                               | scheduled-traffic
ieee802-types              | 2018-03-07 | Installed   |                     |             |                               |
ieee802-dot1q-bridge       | 2018-03-07 | Installed   | root:root           | 777         |                               |
ietf-netconf-time          | 2016-01-26 | Installed   | root:root           | 777         |                               |
ieee802-dot1ab-types       | 2018-10-02 | Installed   |                     |             |                               |
ieee802-dot1ab-lldp        | 2020-10-23 | Installed   | root:root           | 777         |                               |
ietf-routing               | 2018-03-13 | Imported    |                     |             |                               |

**Comment by Maku-chan** [comment]
It seems that the installed model is not enabled. How can it be enabled ?

Traceback (most recent call last):
  File "/home/maku-chan/Master-Thesis/netconf_time_capability.py", line 86, in <module>
    device.commit()
  File "/home/maku-chan/.local/lib/python3.8/site-packages/ncclient/manager.py", line 226, in execute
    return cls(self._session,
  File "/home/maku-chan/.local/lib/python3.8/site-packages/ncclient/operations/edit.py", line 164, in request
    return self._request(node)
  File "/home/maku-chan/.local/lib/python3.8/site-packages/ncclient/operations/rpc.py", line 360, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: There is a not enabled node in ietf-interfaces module, it can not be committed to the running

**Comment by Maku-chan** [comment]
I changed the version of the sysrepo and netopeer2-server and installed the yangs with the below mentioned command
sudo sysrepoctl -v3 -a -i ieee802-dot1q-bridge@2018-03-07.yang -o root -g root -p 666

But now when I use the ncclient there is no error at the client side and i get the following logs from the netopee2-server. But these logs also dont show any error.
[INF]: LN: Accepted a connection on 0.0.0.0:830.
[INF]: SR: Session 40 (user "root") created.
[2016/02/11 18:38:46.659516, 1] ssh_server_connection_callback:  SSH client banner: SSH-2.0-paramiko_2.7.2
[2016/02/11 18:38:46.659572, 1] ssh_analyze_banner:  Analyzing banner: SSH-2.0-paramiko_2.7.2
[INF]: LN: Received an SSH message "request-service" of subtype "ssh-userauth".
[INF]: LN: Received an SSH message "request-auth" of subtype "password".
[INF]: LN: User "soc-e" authenticated.
[INF]: LN: Received an SSH message "request-channel-open" of subtype "session".
[INF]: LN: Received an SSH message "request-channel" of subtype "subsystem".
[INF]: SR: Session 41 (user "root") created.
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-start).
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" "/ietf-netconf:edit-config" with ID 2 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 2 priority 0 (remaining 1 subscribers).
[INF]: SR: No datastore changes to apply.
[INF]: SR: Successful processing of "rpc" event with ID 2 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 2 priority 0 succeeded.
[INF]: NP: Session 2: thread 2 event new RPC.
[2016/02/11 18:38:47.272553, 1] ssh_socket_exception_callback:  Socket exception callback: 1 (0)
[2016/02/11 18:38:47.272613, 1] ssh_socket_exception_callback:  Socket error: disconnected
[ERR]: LN: Session 2: SSH channel poll error (Socket error: disconnected).
[INF]: NP: Session 2: thread 2 event session terminated.
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-end).
[INF]: LN: Accepted a connection on 0.0.0.0:830.
[INF]: SR: Session 42 (user "root") created.
[2016/02/11 18:39:46.096221, 1] ssh_server_connection_callback:  SSH client banner: SSH-2.0-paramiko_2.7.2
[2016/02/11 18:39:46.096267, 1] ssh_analyze_banner:  Analyzing banner: SSH-2.0-paramiko_2.7.2
[INF]: LN: Received an SSH message "request-service" of subtype "ssh-userauth".
[INF]: LN: Received an SSH message "request-auth" of subtype "password".
[INF]: LN: User "soc-e" authenticated.
[INF]: LN: Received an SSH message "request-channel-open" of subtype "session".
[INF]: LN: Received an SSH message "request-channel" of subtype "subsystem".
[INF]: SR: Session 43 (user "root") created.
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-start).
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" "/ietf-netconf:get" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:get" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[INF]: SR: Successful processing of "rpc" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 1 priority 0 succeeded.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: NP: Session 3: thread 3 event new RPC.
[2016/02/11 18:39:46.715060, 1] ssh_socket_exception_callback:  Socket exception callback: 1 (0)
[2016/02/11 18:39:46.715148, 1] ssh_socket_exception_callback:  Socket error: disconnected
[ERR]: LN: Session 3: SSH channel poll error (Socket error: disconnected).
[INF]: NP: Session 3: thread 3 event session terminated.
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-end).

Now the problem is I dont see a running datastore in the sysrepo/data folder and when i use the get config i receive the send configuration but this configuration is not applied to the device.

/sysrepo/data 

iana-if-type.startup              ieee802-dot1q-types.startup  ietf-interfaces.startup          ietf-netconf-nmda.startup           ietf-netconf-with-defaults.startup  ietf-tls-server.startup         nc-notifications.startup    sysrepo.startup
ieee802-dot1q-bridge.startup      ieee802-types.startup        ietf-keystore.startup            ietf-netconf-notifications.startup  ietf-origin.startup                 ietf-truststore.startup         notif                       yang.startup
ieee802-dot1q-preemption.startup  ietf-crypto-types.startup    ietf-netconf-acm.startup         ietf-netconf-server.startup         ietf-ssh-server.startup             ietf-x509-cert-to-name.startup  notifications.startup
ieee802-dot1q-sched.startup       ietf-datastores.startup      ietf-netconf-monitoring.startup  ietf-netconf.startup                ietf-tcp-common.startup             ietf-yang-library.startup       sysrepo-monitoring.startup

**Comment by michalvasko** [comment]
It seems your `ncclient` disconnected for some reason, I cannot help you with that, there is no *netopeer2-server* error that I could help with.

**Comment by Maku-chan** [comment]
I just have one more question is that how can we apply the installed models so that the models can be configured in running datastore without running the application_example script each time.

**Comment by michalvasko** [comment]
That is not possible in legacy *sysrepo* (version 0.7.x), it is its feature. It is possible natively for the current *sysrepo* 1.x.

**Comment by Maku-chan** [comment]
Thanks a lot. Is there any option through which I can check the running configuration data in the legacy sysrepo version. I tried to access the .running file but the complete configuration is not visible and I can't check if the configuration has been applied.

**Comment by michalvasko** [comment]
That should actually be similar, just use `sysrepocfg`.

**Comment by Maku-chan** [comment]
Thanks. I was thinking of making a script to push the configuration using ncclient and get the running configuration and verify it. Is it possible to do that with sysrepocfg ?

**Comment by michalvasko** [comment]
Yes, just look at `sysrepocfg --help`. Use either `import` or `merge` operation to set the configuration, `export` to get it.
