### ISSUE TITLE
Running data Tree issue on Device Reboot

### ISSUE THREAD

**Issue by ChinmayaAgarwal** [sysrepo/sysrepo#2249]
Hi,

I have an application that subscribes to sysrepo running data tree, running as a service. When we execute an edit-config and then do a get-config we can see the latest configuration on running data tree. But when we reboot the machine and netopeer2, sysrepo and the application comes up after that, we see that running data gets cleared sometimes and sometimes the configuration is retained in it. We have executed multiple runs for this and we see this random behaviour. Can anyone please suggest what could be the reason for this random behaviour and what is expected on machine reboot from data tree point of view?

Thanks and Regards,
Chinmaya Agarwal.

**Comment by michalvasko** [comment]
Well, it definitely should not be random (an I do not think it is). The `startup` configuration is expected to be in `running` after reboot under any circumstances.

**Comment by myonlystarWang** [comment]
@ChinmayaAgarwal Did you copy the `running `database to the `startup `database after each `edit-config` operation?
