### ISSUE TITLE
Identiy leaf-list in examples/application_changes_example.c

### ISSUE THREAD

**Issue by ankit7gup** [sysrepo/sysrepo#2250]
Hi Michal,

Is there any way to identify if it is a leaf-list instance similar to what we have for LIST and other data types.

APIs used for data retrieval are:
sr_get_changes_iter()
sr_get_change_next()

I need this information to create a dynamic map of data. As a leaf-list can have multiple nodes, shall need to identify that as a separate entity.

Thanks!

**Comment by michalvasko** [comment]
To learn "specific leaf-list instance" just look into its value. It is not in the xpath because of backwards compatibility with the legacy *sysrepo*. You can also take look at the preferred format of changes using `sr_get_change_tree_next()`.
