### ISSUE TITLE
Can it directly return an "INTEGER" value  when we use "sr_get_items" interface  to obtain an "enum" type from yang sysrepo?

### ISSUE THREAD

**Issue by itercheng** [sysrepo/sysrepo#2251]
Hello 
there is a new proposal. can we get an "INTEGER" type value when we use "sr_get_items" to obtain "enum" type from yang sysrepo? please refer to following example:

1 first we configure following yang into sysrepo data:

leaf  eventType
{
     type enumeration 
     {
           enum "COMMUNICATIONS_ALARM" 
            {
                value 2;
            }
            enum "QUALITY_OF_SERVICE_ALARM"
            {
                value 3;
            }
            enum "PROCESSING_ERROR_ALARM"
            {
                value 4;
            }
            enum "EQUIPMENT_ALARM"
            {
                value 5;
            }
            enum "ENVIRONMENTAL_ALARM"
            {
                value 6;
            }
    }
}

2  The "eventType" should be stored in sysrepo data with "INTEGER" type, examples  "COMMUNICATIONS_ALARM"  is "2" , right? so we should get 2 but not be "COMMUNICATIONS_ALARM" when we use "sr_get_items" to access to sysrepo?  however  we actually get a "COMMUNICATIONS_ALARM" when operating sysrepo.  please correct me if i am wrong.  if not.  Could you optimize this function ?  please feel free to contact me if you need more information.   Thank you in advance.

**Comment by michalvasko** [comment]
You can easily learn the integer value of a specific enum value if you use `sr_get_data()` instead. To get it from `sr_val_t` is a really convoluted task despite still being possible.

**Comment by itercheng** [comment]
Thank you quick reply. But there are some difference between "sr_get_data" and sr_get_items", we can get " sr_val_t" struct  by callback  sr_get_items, then we can get enum's string value from "sr_val_t", however the API "sr_get_data" will get struct "lyd_node **data",  I can't find enum value from this struct.  please forgive me that I actually  wonder how to get enum value from this struct (lyd_node) and this API you mentioned last. Do you have good idea?   it is better if you can give me some examples. Thank you very much. Please feel free to contact me if you need more information.

**Comment by michalvasko** [comment]
`struct lyd_node` is a *libyang* structure so that is where you need to look. It provides all the possible information about a value. This specific one you can get the following way.
```C
struct lyd_node *node;
if (node->schema->nodetype & (LYS_LEAF | LYS_LEAFLIST)) {
  int value = ((struct lyd_node_leaf_list *)node)->value.enm->value;
}
```

**Comment by itercheng** [comment]
Really thank you for specific example, i tried to use it in our code.  despite  sr_get_data() return okay and return node is also not NULL, the node->schema->nodetype is shown as "1" so that it can't satisfy this "if" sentence. "1" means it is a "container" according to source code as below, right?   but actually we give a leaf xpath.  Do you know why this condition occurs ? thank you in advance. sorry to continue  question.



typedef enum lys_nodetype {
    LYS_UNKNOWN = 0x0000,        /**< uninitialized unknown statement node */
    LYS_CONTAINER = 0x0001,      /**< container statement node */
    LYS_CHOICE = 0x0002,         /**< choice statement node */
    LYS_LEAF = 0x0004,           /**< leaf statement node */
    LYS_LEAFLIST = 0x0008,       /**< leaf-list statement node */
    LYS_LIST = 0x0010,           /**< list statement node */
    LYS_ANYXML = 0x0020,         /**< anyxml statement node */
    LYS_CASE = 0x0040,           /**< case statement node */
    LYS_NOTIF = 0x0080,          /**< notification statement node */
    LYS_RPC = 0x0100,            /**< rpc statement node */
    LYS_INPUT = 0x0200,          /**< input statement node */
    LYS_OUTPUT = 0x0400,         /**< output statement node */
    LYS_GROUPING = 0x0800,       /**< grouping statement node */
    LYS_USES = 0x1000,           /**< uses statement node */
    LYS_AUGMENT = 0x2000,        /**< augment statement node */
    LYS_ACTION = 0x4000,         /**< action statement node */
    LYS_ANYDATA = 0x8020,        /**< anydata statement node, in tests it can be used for both #LYS_ANYXML and #LYS_ANYDATA */
    LYS_EXT = 0x10000            /**< complex extension instance, ::lys_ext_instance_complex */
} LYS_NODE;

**Comment by michalvasko** [comment]
Right, that is caused by somewhat different functionality of `sr_get_data()` (and all the getters returning `struct lyd_node *`). They always return subtrees, pointing at the top-level element of the subtree. For example, if you request `/module:cont/leaf`, you will get
```
module:cont  <-- your pointer
     |
   leaf
```
so you must actually get to the requested node. The easiest way is calling `lyd_find_path()` on the returned data with the same `xpath`, that will always return the selected node. Or you can traverse the tree manually if it is simple enough.

**Comment by itercheng** [comment]
Good news, we have tested our codes with above function you mentioned, the result is completely successful.  thank you again. now i will close this ticket.
