### ISSUE TITLE
How to know if notifications in the Yang model have been subscribed?

### ISSUE THREAD

**Issue by rydy** [sysrepo/sysrepo#2256]
Hi,
    I have a question, I How to know if any subscribers have subscribed to the notification events in the YANG model?
thanks.

**Comment by michalvasko** [comment]
If you really need this information, it can be found in the `operational` data of `sysrepo-monitoring` module but `root` access is required by default to get them (since they include information about all the *sysrepo* connections and subscriptions).

**Comment by rydy** [comment]
> If you really need this information, it can be found in the `operational` data of `sysrepo-monitoring` module but `root` access is required by default to get them (since they include information about all the _sysrepo_ connections and subscriptions).

i got it, thanks
