### ISSUE TITLE
Subscribing to model and getting changes -- can I also get non-changed data?

### ISSUE THREAD

**Issue by esend7881** [sysrepo/sysrepo#2257]
My goal in this issue is, when submitting an edit-config to my module and there are redundant, unchanged elements in the new config, I need those unchanged elements to be listed.

### Details:
I am subscribing to changes to a model in my sysrepo data store

```.python
it = sess.get_changes_iter(change_path)
change = sess.get_change_tree_next(it)
```

And as I iterate through the changes, I notice that it simply doesn't show elements that were not changes. I.e., it shows me:

- Created elements
- Deleted elements
- Moved elements
- Modified elements

But actually, if there was a way to have it also display leafs/configuration elements that were not modified. I.e., elements that exist in the config but weren't touched.

I know this may seem odd, but I actually need it to maintain consistency between different components in our system. For example

#### Config I send in via edit-config
```.xml
<?xml version="1.0" encoding="UTF-8"?>
<MyModel xmlns="urn:com:mymodel">
   <Elem1>
     <Elem2>
         <id>101</id>
		 <!-- These item is changed -->
         <priority>3</priority>
         <name>10dot0SubnetToPort234_ip</name>
		 
		 <!-- becuase the 'type' element below is changed, this match is given xc:operation='none' -->
         <match>
            <in-port>1</in-port>
            <ethernet-match>
               <ethernet-type>
				  <!-- These element has changed and is noted as xc:operation='replace' -->
                  <type>0x0800</type>
               </ethernet-type>
            </ethernet-match>
         </match>
		 
		 <!-- action order # 0,1 are unchanged, but need to be listed here redundantly -->
         <action>
            <order>0</order>
            <set-dl-dst-action>
               <address>00:00:00:aa:00:54</address>
            </set-dl-dst-action>
         </action>
         <action>
            <order>1</order>
            <set-nw-dst-action>
               <ipv4-address>10.0.1.10/32</ipv4-address>
            </set-nw-dst-action>
         </action>
		 <!-- End Unchanged -->
		 
		 <!-- There is a change within this element -->
         <action>
            <order>2</order>
            <output-action>
               <output-node-connector>99999</output-node-connector>
               <max-length>99999</max-length>
            </output-action>
         </action>
		 <!-- End Change on order #2 -->
		 
		 <!-- These action elements are deleted ( commented out here and show up as such as an nc:operation="delete")
         <action>
            <order>10</order>
            <set-nw-dst-action>
               <ipv4-address>10.0.6.10/32</ipv4-address>
            </set-nw-dst-action>
         </action>
         <action>
            <order>11</order>
            <output-action>
               <output-node-connector>4</output-node-connector>
               <max-length>60</max-length>
            </output-action>
         </action>
		 <!-- End Modified elements section -->
      </Elem2>
   </Elem1>
</MyModel>
```

In the above example, you can see I am 
- Deleting element `action` with order 10 and 11 
- Modifying action-order 2
- Modifying an element within the Match section 
- However, there are orders 0-1 that were untouched. 
  - I need to be able to see those `action` elements listed an have `nc:operation` of `none` or something to that effect.  
  - Is that possible?

#### The corresponding tree that I pick up in my subscribe loop:
```.xml
<MyModel xmlns="urn:com:mymodel" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:sr="http://www.sysrepo.org/yang/sysrepo" sr:operation="none">
  <Elem1 sr:operation="none">
    <Elem2 sr:operation="none">
      <id>101</id>
	  
	  <!-- Here are the deleted actions -->
      <action nc:operation="delete">
        <order>10</order>
        <set-nw-dst-action>
          <ipv4-address>10.0.6.10/32</ipv4-address>
        </set-nw-dst-action>
      </action>
      <action nc:operation="delete">
        <order>11</order>
        <output-action>
          <output-node-connector>4</output-node-connector>
          <max-length>60</max-length>
        </output-action>
      </action>
	  
	  <!-- modified priority -->
      <priority nc:operation="replace" sr:orig-value="3">9</priority>
	  
	  <!-- These match section is listed because the 'type' got changed -->
      <match sr:operation="none">
        <ethernet-match sr:operation="none">
          <ethernet-type sr:operation="none">
            <type nc:operation="replace" sr:orig-value="0x0800">0x0806</type>
          </ethernet-type>
        </ethernet-match>
      </match>
	  
	  <!-- Order #2 listed here as its element was changed -->
      <action sr:operation="none">
        <order>2</order>
        <output-action sr:operation="none">
          <output-node-connector nc:operation="replace" sr:orig-value="2">99999</output-node-connector>
          <max-length nc:operation="replace" sr:orig-value="60">99999</max-length>
        </output-action>
      </action>
	  
	  <!-- **** But, I need action-order elements for 0-1 also listed, but with operation='none' *** -->
	  
	  
	  <!-- **** Somehow, I need to see  action-order listed here like this ***
	  
      <action sr:operation="none">
        <order>0</order>
        <set-dl-dst-action sr:operation="none">
          <address nc:operation="none">00:00:00:aa:00:54</address>
        </set-dl-dst-action>
      </action>
      <action sr:operation="none">
        <order>1</order>
        <set-nw-dst-action sr:operation="none">
          <ipv4-address nc:operation="none">10.0.1.10/32</ipv4-address>
        </set-nw-dst-action>
      </action>
	  
	  <!-- END Section of elements I need listed but w/ nc:operation='none' -->
    </Elem2>
  </Elem1>
</MyModel>
```

**Everything about the above change set is good, except action-order 0-1 are not listed at all (I manually pasted in what it should look like at the end and commented it out). I am hoping to somehow see it get listed as `operation="none"`**

Also, I know there is a way to get the items in the config via `session.get_data(xpath)` however that gives me the config but doesn't tell me any information about what is modified, untouched, created, etc. 

I suppose I could look into a way to merge data from `.get_items()` and `.get_change_tree_next()` however it would be very good if I can just use `.get_change_tree_next`, climb up the data structure with the `.parent()` method and then see overall what data is `untouched`, `modified`, `created`, and `deleted`

- sysrepo 1.4.70
  - compiled with `cmake -DGEN_LANGUAGE_BINDINGS=ON ..`
- netopeer2 1.1.39 
  - compiled with `cmake -DSYSREPO_TIMEOUT=119 -DRPC_TIMEOUT=120 ..`
- libyang 1.0.184 
  - compiled with `cmake -DGEN_LANGUAGE_BINDINGS=ON ..`
- CentOS 7
- python 2.7.5/3.6.8

Update:
Updated the clarity of the question more.

**Comment by michalvasko** [comment]
Firstly, you are working with **changes** so you cannot expect all the data to be present. It would also significantly reduce performance if the whole datastore was being sent every time and, generally, there is no reason to do so.

So, you are left with some custom solution of yours. Merging of some kind may be possible, not sure.

**Comment by esend7881** [comment]
> Firstly, you are working with **changes** so you cannot expect all the data to be present. It would also significantly reduce performance if the whole datastore was being sent every time and, generally, there is no reason to do so.
> 
> So, you are left with some custom solution of yours. Merging of some kind may be possible, not sure.

That makes sense. My question was a bit of a Hail Mary, I had my doubts it was possible. In some ways, writing the question out helped me more in just making sense of the problem.

Ultimately, our sysrepo config system is updating an internal Opendaylight config and I am finding modifying the opendaylight config is not PATCH based normally, it is PUT based (entire config is swapped). There is a PATCH method there but it appears to not be documents. Are you at all familiar with Opendaylight's PATCH based config modification functionality?

**Comment by michalvasko** [comment]
I cannot help you with Opendaylight in any way. But if you are able to set the configuration, you can do that as well. In the callback simply call `sr_get_data()` and you have the new config.
