### ISSUE TITLE
Queries on sysrepocfg behaviour on startupdb 

### ISSUE THREAD

**Issue by iGovindY** [sysrepo/sysrepo#2262]
Questions are in the end.

Steps followed are below

ManagedElement is a List with id as a key and min-elements and max-elements as 1.

**content of file**
```
[root@kubernetes-master DU]# cat MEEntry.xml 
<ManagedElement xmlns="urn:3gpp:sa5:_3gpp-common-managed-element" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
 <id>1</id>
 <attributes>
  <userLabel>ME</userLabel>
  <priorityLabel>0</priorityLabel>
 </attributes>
</ManagedElement>
```
**1. performed below to set in startup DB**

```
[root@kubernetes-master DU]# sysrepocfg --edit=MEEntry.xml -d startup -f xml -m _3gpp-common-managed-element -v4
| INFO | SR stderr | sysrepocfg | Applying scheduled changes. |
| WARNING | SR stderr | sysrepocfg | Too few "ManagedElement" elements. |
| WARNING | SR stderr | sysrepocfg | Failed to apply some changes, leaving all changes scheduled. |
| INFO | SR stderr | sysrepocfg | Session 4 (user "root") created. |

```
**2. Check startupDB and running**
```
[root@kubernetes-master DU]# sysrepocfg -X -m _3gpp-common-managed-element -e report-all -d running
[root@kubernetes-master DU]# sysrepocfg -X -m _3gpp-common-managed-element -e report-all -d startup
<ManagedElement xmlns="urn:3gpp:sa5:_3gpp-common-managed-element">
  <id>1</id>
  <attributes>
    <userLabel>ME</userLabel>
    <priorityLabel>0</priorityLabel>
  </attributes>
</ManagedElement>

```
**3. Copy to running**
below command is doing a copy-config from startup to running, right?
```
[root@kubernetes-master DU]# sysrepocfg -C startup -m _3gpp-common-managed-element -v4
| INFO | SR stderr | sysrepocfg | Applying scheduled changes. |
| WARNING | SR stderr | sysrepocfg | Too few "ManagedElement" elements. |
| WARNING | SR stderr | sysrepocfg | Failed to apply some changes, leaving all changes scheduled. |
| INFO | SR stderr | sysrepocfg | Session 7 (user "root") created. |
| INFO | SR stderr | sysrepocfg | There are no subscribers for changes of the module "_3gpp-common-managed-element" in running DS. |

```
**4. Check startupDB and running again**

```
[root@kubernetes-master DU]# sysrepocfg -X -m _3gpp-common-managed-element -e report-all -d running
<ManagedElement xmlns="urn:3gpp:sa5:_3gpp-common-managed-element">
  <id>1</id>
  <attributes>
    <userLabel>ME</userLabel>
  </attributes>
</ManagedElement>
[root@kubernetes-master DU]# sysrepocfg -X -m _3gpp-common-managed-element -e report-all -d startup
<ManagedElement xmlns="urn:3gpp:sa5:_3gpp-common-managed-element">
  <id>1</id>
  <attributes>
    <userLabel>ME</userLabel>
  </attributes>
</ManagedElement>
[root@kubernetes-master DU]#
```

I have two question:

- why sysrepo gives below warning even though set to startup db worked?
  `| WARNING | SR stderr | sysrepocfg | Too few "ManagedElement" elements. |`
   `| WARNING | SR stderr | sysrepocfg | Failed to apply some changes, leaving all changes scheduled. |`
   
- why db startup content got changed just after **step 3**, i.e copy from startup to running?
   `<priorityLabel>0</priorityLabel>` is missing in startupdb

Also if MEEntry.xml content is pushed via an edit-config from netopeer-cli on running db, no warning prints were seen by netopeer2-server

**Comment by michalvasko** [comment]
- the errors you see are caused by some module that is constantly failing to be installed, would be my guess. Just execute `sysrepoctl -l` and if you see a module with `N`, that is the one.
- I do not know why would a node disappear after copy-config, it is most likely a bug. But I cannot say for certain until I reproduce it.

**Comment by mdoshi-com** [comment]
Hi Michal,
Actually we are seeing some error in module installation itself.
I am updating on behalf of Govind. So first can you help us figure out why this error is happening.

1. Install the modules:
```
sysrepoctl -i _3gpp-common-managed-function.yang  -e MeasurementsUnderManagedFunction -v4
sysrepoctl -i commscope_3gpp-nr-nrm-nrcelldu.yang  -v4
```

2. getting following error:

```
WARNING | SR stderr | sysrepocfg | Too few "ManagedElement" elements. |
| WARNING | SR stderr | sysrepocfg | Failed to apply some changes, leaving all changes scheduled. |
| WARNING | SR stderr | sysrepocfg | Too few "ManagedElement" elements. |
| WARNING | SR stderr | sysrepocfg | Failed to apply some changes, leaving all changes scheduled. |
```

This error is coming after we added the following (in commscope_3gpp-nr-nrm-nrcelldu.yang):


```
deviation "/me3gpp:ManagedElement" {
          deviate add {
                  min-elements 1;
                  max-elements 1;
          }
  }
```

Yang files zip attached.

Regards,
Meghna
[yang-files.zip](https://github.com/sysrepo/sysrepo/files/5715110/yang-files.zip)

**Comment by michalvasko** [comment]
by that deviation you making the `ManagedElement` mandatory. More about that in [here](https://github.com/sysrepo/sysrepo/issues/1815#issuecomment-586331789), for example.

**Comment by mdoshi-com** [comment]
Hi Michal,
Ok so we have to use --new-data option in sysrepocfg.
I couldnt understand what to give in the file which is expected by this "new-data" option.
Can you give sample may be using our yang itself.

Regards,
Meghna

**Comment by michalvasko** [comment]
Just some valid data, what do you not know exactly? The one you used before should do
```xml
<ManagedElement xmlns="urn:3gpp:sa5:_3gpp-common-managed-element">
  <id>1</id>
  <attributes>
    <userLabel>ME</userLabel>
  </attributes>
</ManagedElement>
```

**Comment by mdoshi-com** [comment]
Hi Michal,
I think i lost you here.
I want to do following two actions:

1. install yang:
`sysrepoctl -i commscope_3gpp-nr-nrm-nrcelldu.yang  -v4`

2. make entry in startup datastore (with your suggestion i tried following):
sysrepocfg --new-data=MEEntry.xml -d startup -f xml -m _3gpp-common-managed-element -v4

But as expected both 1 and 2 give error like:

```
| INFO | SR stderr | sysrepocfg | Applying scheduled changes. |
| WARNING | SR stderr | sysrepocfg | Too few "ManagedElement" elements. |
| WARNING | SR stderr | sysrepocfg | Failed to apply some changes, leaving all changes scheduled. |
```

So what i still couldnt get is how to make both the above steps success?

Regards,
Meghna

**Comment by michalvasko** [comment]
Okay, I suppose I have to add some details. What you first need to understand is how these context changes are applied. Whenever you want to do any context change such as adding, removing a module, change module features and so on, all of these changes are only **scheduled** to be performed. The reason for this is that you cannot change context during normal operation of *sysrepo* because it may be used by some applications. So, instead, whenever a new connection is created and there are no other connections, all the scheduled changes tried to be applied. With this information the output should make more sense.

Having said that, it is quite possible that when you create any new connection now (execute any `sysrepoctl` or `sysrepocfg` command), it will finally work because the last command you used is the one I told you to use (but you can skip `-d` param, these data will be set for both `startup` and `running` datastores). It has still printed the errors because **before** it could use the data file you are providing, it had to create a connection. When it did, all the scheduled changes, again, tried to be applied, unsuccessfully.

**Comment by iGovindY** [comment]
Okay, so here is what we understood.

yang install will result in scheduled for installation as top level is mandatory due to min-elements as 1.
But as soon as we configure top-level with one entry using --new-data option, it will apply the scheduled yang as installed.

Thanks for the help.
Govind.
