### ISSUE TITLE
sysrepoctl -u does not remove imported YANG files from repository

### ISSUE THREAD

**Issue by peckato1** [sysrepo/sysrepo#2263]
Hello,

yesterday I stumbled upon a weird behaviour when uninstalling models from repository using `sysrepoctl`.
We run Sysrepo with `ietf-hardware-state` YANG model (Implemented). It has a dependency on `ietf-hardware` model (imported). 
When I uninstall the Implemented `ietf-hardware-state` model, `sysrepoctl` reports both `ietf-hardware` and `ietf-hardware-state` modules are gone (as expected) but only `ietf-hardware-state` YANG file gets deleted from Sysrepo's YANG repository. The `ietf-hardware` model (imported dependency) does not get deleted. See example below.

I'm not sure if this is a bug or feature.

```sh
# cwd is sysrepo repository

$ sysrepoctl -l | grep hardware | cut -d"|" -f1-3
iana-hardware             | 2018-03-13 | I
ietf-hardware             | 2018-03-13 | i
ietf-hardware-state       | 2018-03-13 | I

$ ls *hardware*
iana-hardware@2018-03-13.yang  ietf-hardware-state@2018-03-13.yang  ietf-hardware@2018-03-13.yang

$ sysrepoctl -u ietf-hardware-state --apply

$ sysrepoctl -l | grep hardware | cut -d"|" -f1-3
iana-hardware             | 2018-03-13 | I

$ ls *hardware*
iana-hardware@2018-03-13.yang  ietf-hardware@2018-03-13.yang
```

**Comment by michalvasko** [comment]
What *sysrepo* version are you using?

**Comment by peckato1** [comment]
Sorry about that :(
```
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.88 (SO v5.6.4)
```
specifically commit ed2150b7d2b63f5b71a3fd46f72f7df839a404d4

**Comment by michalvasko** [comment]
Right, it seems it is a feature because it is not completely trivial to find all such imported-only modules (not wanting it to have performance impact). It should not matter, though, the module will simply not be used. I will add it to my TODO list and implement it once I have some time for such minor improvements.

**Comment by peckato1** [comment]
Thanks!

**Comment by michalvasko** [comment]
Should now be supported.
