### ISSUE TITLE
Query: When will you release new versions of sysrepo/netopeer2/libyang/libnetconf2?

### ISSUE THREAD

**Issue by starx1000** [sysrepo/sysrepo#2264]
hi,
   Looks like last release is  " Version 1.4.70 on Jul 21"

  Five months since then and I found some issues which fixed already in devel branch , 
   what is your plan to merge devel to master and release new versions?
   Thanks very much. 

  We are now building new packages through  master branch..

**Comment by michalvasko** [comment]
Right, sorry about that. The current plan is to make a new release during January.

**Comment by starx1000** [comment]
OK, thanks.
