### ISSUE TITLE
sr_oper_get_items_subscribe filtering data

### ISSUE THREAD

**Issue by matkocc** [sysrepo/sysrepo#2266]
Hi,
    I have an question regarding sr_oper_get_items_subscribe().

I am subscribing like this:

        rc = sr_oper_get_items_subscribe(session,
                                    "ietf-interfaces",
                                    "/ietf-interfaces:interfaces",
                                    oper_cb,
                                    NULL,
                                    SR_SUBSCR_CTX_REUSE,
                                    &subscription);

When I am "getting filter-ed data" ( with eg. get --filter-xpath "/ietf-interfaces:interfaces/interface[name='m-vlan0']"  ) in netopeer2-cli, server side successfully returns filtered data, even though I appended whole interfaces data tree to *parent node.

    > get --filter-xpath "/ietf-interfaces:interfaces/interface[name='m-vlan0']"
    DATA
    <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
      <interface>
        <name>m-vlan0</name>
        <higher-layer-if>mplane-ip</higher-layer-if>
        <lower-layer-if>fheth0</lower-layer-if>
      </interface>
    </interfaces>
    
    >

I am courious if this is valid sysrepo behaviour, ie. should sysrepo filter data "under the hood" like now or we should append *parent node with requested data tree only in our callback (for example data tree with interface with 'm-vlan0' name only)?

Thanks in advance,
    Matko

**Comment by michalvasko** [comment]
> I am courious if this is valid sysrepo behaviour, ie. should sysrepo filter data "under the hood" like now or we should append *parent node with requested data tree only in our callback (for example data tree with interface with 'm-vlan0' name only)?

You see, it is up to you, the result should always be correct. You simply have the option to not return redundant data as an optimization of your plugin based on the `request_xpath`. But it may be more difficult than you think, the used XPath can be complex, with predicates and various operators.

**Comment by matkocc** [comment]
I think I asked question in wrong way. I have a list of interfaces (interface with 'm-vlan0' name is among them). When filtering with get --filter-xpath I requested interface with name  'm-vlan0' and sysrepo returned that one only even though I didn't filter it in my callback. As you can see my callback above, I parsed whole xml with all the interfaces and appended data to parent and sysrepo returned only interface with requested name. My question is if this is "bug or the feature" , ie.  should sysrepo filter it as it did in my case or we should do it in callback?

Tis is my xml:

      <?xml version="1.0"?>
      <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
    <interface>
      <name>fheth0</name>
      <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
      <oper-status>up</oper-status>
      <phys-address>38:af:d7:e9:fa:83</phys-address>
      <higher-layer-if>m-vlan0</higher-layer-if>
      <higher-layer-if>uc-vlan0</higher-layer-if>
      <speed>${ORUSIM_IFACE_SPEED}</speed>
      <statistics>
        <discontinuity-time>2000-01-01T00:00:00+00:00</discontinuity-time>
        <in-octets>0</in-octets>
        <in-unicast-pkts>0</in-unicast-pkts>
        <in-broadcast-pkts>0</in-broadcast-pkts>
        <in-multicast-pkts>0</in-multicast-pkts>
        <in-discards>0</in-discards>
        <in-errors>0</in-errors>
        <in-unknown-protos>0</in-unknown-protos>
        <out-octets>0</out-octets>
        <out-unicast-pkts>0</out-unicast-pkts>
        <out-broadcast-pkts>0</out-broadcast-pkts>
        <out-multicast-pkts>0</out-multicast-pkts>
        <out-discards>0</out-discards>
        <out-errors>0</out-errors>
      </statistics>
      <vlan-tagging xmlns="urn:o-ran:interfaces:1.0">true</vlan-tagging>
      <class-of-service xmlns="urn:o-ran:interfaces:1.0">
        <u-plane-marking>7</u-plane-marking>
        <c-plane-marking>7</c-plane-marking>
        <m-plane-marking>2</m-plane-marking>
      </class-of-service>
      <mac-address xmlns="urn:o-ran:interfaces:1.0">08:00:27:8a:93:1d</mac-address>
      <port-reference xmlns="urn:o-ran:interfaces:1.0">
        <port-name>hw-fhport0</port-name>
        <port-number>0</port-number>
      </port-reference>
    </interface>
    <interface>
      <name>m-vlan0</name>
      <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:l2vlan</type>
      <oper-status>up</oper-status>
      <higher-layer-if>mplane-ip</higher-layer-if>
      <lower-layer-if>fheth0</lower-layer-if>
      <statistics>
        <discontinuity-time>2000-01-01T00:00:00+00:00</discontinuity-time>
        <in-octets>0</in-octets>
        <in-unicast-pkts>0</in-unicast-pkts>
        <in-broadcast-pkts>0</in-broadcast-pkts>
        <in-multicast-pkts>0</in-multicast-pkts>
        <in-discards>0</in-discards>
        <in-errors>0</in-errors>
        <in-unknown-protos>0</in-unknown-protos>
        <out-octets>0</out-octets>
        <out-unicast-pkts>0</out-unicast-pkts>
        <out-broadcast-pkts>0</out-broadcast-pkts>
        <out-multicast-pkts>0</out-multicast-pkts>
        <out-discards>0</out-discards>
        <out-errors>0</out-errors>
      </statistics>
      <vlan-id xmlns="urn:o-ran:interfaces:1.0">10</vlan-id>
      <port-reference xmlns="urn:o-ran:interfaces:1.0">
        <port-name>hw-fhport0</port-name>
        <port-number>0</port-number>
      </port-reference>
    </interface>
    <interface>
      <name>mplane-ip</name>
      <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ip</type>
      <oper-status>up</oper-status>
      <lower-layer-if>m-vlan0</lower-layer-if>
      <statistics>
        <discontinuity-time>2000-01-01T00:00:00+00:00</discontinuity-time>
      </statistics>
      <ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip">
        <enabled>true</enabled>
        <forwarding>false</forwarding>
        <address>
          <ip>192.168.56.102</ip>
          <prefix-length>20</prefix-length>
          <origin>dhcp</origin>
        </address>
        <diffserv-markings xmlns="urn:o-ran:interfaces:1.0">
          <u-plane-marking>46</u-plane-marking>
          <c-plane-marking>46</c-plane-marking>
          <s-plane-marking>46</s-plane-marking>
          <other-marking>0</other-marking>
        </diffserv-markings>
        <m-plane-marking xmlns="urn:o-ran:interfaces:1.0">18</m-plane-marking>
      </ipv4>
    </interface>
    <interface>
      <name>uc-vlan0</name>
      <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:l2vlan</type>
      <oper-status>up</oper-status>
      <lower-layer-if>fheth0</lower-layer-if>
      <statistics>
        <discontinuity-time>2000-01-01T00:00:00+00:00</discontinuity-time>
        <in-octets>0</in-octets>
        <in-unicast-pkts>0</in-unicast-pkts>
        <in-broadcast-pkts>0</in-broadcast-pkts>
        <in-multicast-pkts>0</in-multicast-pkts>
        <in-discards>0</in-discards>
        <in-errors>0</in-errors>
        <in-unknown-protos>0</in-unknown-protos>
        <out-octets>0</out-octets>
        <out-unicast-pkts>0</out-unicast-pkts>
        <out-broadcast-pkts>0</out-broadcast-pkts>
        <out-multicast-pkts>0</out-multicast-pkts>
        <out-discards>0</out-discards>
        <out-errors>0</out-errors>
      </statistics>
      <base-interface xmlns="urn:o-ran:interfaces:1.0">fheth0</base-interface>
      <vlan-id xmlns="urn:o-ran:interfaces:1.0">3</vlan-id>
      <mac-address xmlns="urn:o-ran:interfaces:1.0">38:af:d7:e9:fa:83</mac-address>
    </interface>
  </interfaces>

**Comment by michalvasko** [comment]
No, you asked correctly and I can only answer as I did. *sysrepo* will **always** filter the data correctly and return only requested nodes. However, in case you do the filtering in your callback already (to save yourself some work), there will be **nothing left to filter out**, in effect. That is why I said it is up to you.

**Comment by matkocc** [comment]
I got it. I just have one more question. Is there a way for this callback to return also the configuration data ? It returns only config false data right now.
Thanks,
    Matko

**Comment by michalvasko** [comment]
Yes, you can return configuration data as well. Then you can decide what to do with any existing `running` configuration data using [this](https://netopeer.liberouter.org/doc/sysrepo/devel/html/group__subs__api.html#ggac91898627ad5aeb589e6a3993a697d14ad8c77539582e1de78f57e256299ea138) flag.

**Comment by matkocc** [comment]
Hi, I used SR_SUBSCR_OPER_MERGE option in sr_oper_get_items_subscribe() function, but callback is still returning state data only. What do I need to do in callback to tell him to return cpnfiguration data too ?
Thanks,
    Matko

**Comment by matkocc** [comment]
I have one more question.  As you can see above, in my operational callback I read data directly from xml, parsed it and appended it to *parent. How should I provide data when get-config is sent from client. Somehow I have to import data from xml to sysrepo to be able for sysrepo to return it to client when get-config arrives. Is it correct to do it with sr_install_module_data() in every application for every module or there is better way to do it ?
Thanks,
Matko

**Comment by michalvasko** [comment]
Okay, I think you do not really understand what you are doing. Please, read the [docs](https://netopeer.liberouter.org/doc/sysrepo/master/html/) carefully first. You should learn all the basics there and also how to set the data. Generally speaking, you want to set configuration data with `sr_set_*()` and `sr_apply_changes()` calls and state data with `sr_oper_get_items_subscribe()`. There are some more advanced features (such as providing even configuration data in the oper data callback) but I do not think you are there just yet.

**Comment by matkocc** [comment]
OK, thanks, but thing is that I have all the data in one xml. 
At startup I read ip and mac adresses and update xml with those data.

Next step in app is to set the data from xml. As you can see in model, my data (list od imterfaces) is configurational with some "state" nodes, and my question is how to setup it. 

I was investigating a bit and found 2 ways to setup configuration data and wondering is it right way:

1st way) 
           1.1) parse my xml with lyd_parse_path(), 
           1.2) prepare data to be applied with sr_edit_batch() 
           1.3) apply changes with sr_apply_changes()

question: Do I really have to remove state nodes from xml or use some special option for sr_edit_batch to ignore it or remove from returned data tree since I am having errors on "config false" data when applying changes. (Or I have to remove it by
myself somehow before applying changes).

2nd way) using sr_set_item_str(), but since I have whole xml I will have to call as many sr_set_item_str functions as there are values in my xml (correct me if I am wrong).

Regarding state data, I am setting it using sr_oper_get_items_subscribe(), in it's callback in a way from first message. You can see
that there  I read data from the same xml I am using to setup configuration data and that's way I would like not to remove
state nodes from xml. But, if I have to remove them, can you suggest a way to provide it in callback?

You can find xml and model in previous messages.

Any help will be much appreciated,
    Matko

**Comment by jktjkt** [comment]
I do not understand why your custom code is managing the data in an external XML file. That's what sysrepo is doing "behind the scenes"; you can push YANG data in there, and it will validate the data and call your callbacks as the data are changing. There are APIs provided for modifying the data, and there's code for providing a NETCONF interface on top of that. The last comment reads to me as if you were building code which partially replaces sysrepo features with bespoke libyang code. Perhaps it would be best to provide some more context about the end result that you're hoping to achieve here?

**Comment by wangshdong** [comment]
I want to know how to get the configuration data of subscription? Using nc_ rpc_get function or nc_ rpc_ getconfig function?

**Comment by michalvasko** [comment]
Like I said before, you should read the documentation and perhaps go through the examples, you seem to be asking the wrong questions, or you are not adding enough details.

> The RPC is sent successfully, but the subscription function will not be called

That is just it, there is no "subscription function" that should be called for a `get-config`, you are simply retrieving configuration data that are stored in *sysrepo*.
