### ISSUE TITLE
unique not enforced by Sysrepo?

### ISSUE THREAD

**Issue by Reshad-Rahman** [sysrepo/sysrepo#2268]
I was trying a very simple example YANG model to get to learn/evaluate Sysrepo. I have a list of interfaces keyed by name and an optional "id" which is tagged as unique. Accidentally I wasn't changing the "id" and Sysrepo allowed all interfaces to have same non-unique "id". Interestingly when I tried the data obtained by sysrepocfg with yanglint, yanglint correctly found the issue. I made sure I uninstalled and re-installed the ex-interface module via sysrepoctl.

![Screen Shot 2020-12-24 at 4 35 02 PM](https://user-images.githubusercontent.com/5272591/103106730-00142380-4606-11eb-9810-61777770ae02.png)
![Screen Shot 2020-12-24 at 4 10 20 PM](https://user-images.githubusercontent.com/5272591/103106732-030f1400-4606-11eb-952b-0fbb3b287a98.png)

**Comment by michalvasko** [comment]
Hm, that is quite strange, could you please provide steps and all the files (YANG + data) to reproduce this?

**Comment by Reshad-Rahman** [comment]
I agree it's quite strange, it is possible I am goofing up somehow. 

Window 1:
```
vagrant@debian10:~/dev/sysrepo/build$ examples/sr_set_interface_example 10 
Num interfaces: 10
Created 10 interfaces
Wrote hw_index/sw_index for 10 interfaces
Sleeping for 30 mins....

```
Window 2:
```
vagrant@debian10:~/dev/sysrepo/examples/build$ sysrepocfg -X -x "/ex-interface:interfaces" -d operational 
<interfaces xmlns="http://www.reshad.com/yang/ex-interface">
  <interface>
    <name>eth0</name>
    <hw_index>1</hw_index>
    <sw_index>0</sw_index>
  </interface>
  <interface>
    <name>eth1</name>
    <hw_index>1</hw_index>
    <sw_index>1</sw_index>
  </interface>
  <interface>
    <name>eth2</name>
    <hw_index>1</hw_index>
    <sw_index>2</sw_index>
  </interface>
  <interface>
    <name>eth3</name>
    <hw_index>1</hw_index>
    <sw_index>3</sw_index>
  </interface>
  <interface>
    <name>eth4</name>
    <hw_index>1</hw_index>
    <sw_index>4</sw_index>
  </interface>
  <interface>
    <name>eth5</name>
    <hw_index>1</hw_index>
    <sw_index>5</sw_index>
  </interface>
  <interface>
    <name>eth6</name>
    <hw_index>1</hw_index>
    <sw_index>6</sw_index>
  </interface>
  <interface>
    <name>eth7</name>
    <hw_index>1</hw_index>
    <sw_index>7</sw_index>
  </interface>
  <interface>
    <name>eth8</name>
    <hw_index>1</hw_index>
    <sw_index>8</sw_index>
  </interface>
  <interface>
    <name>eth9</name>
    <hw_index>1</hw_index>
    <sw_index>9</sw_index>
  </interface>
</interfaces>
vagrant@debian10:~/dev/sysrepo/examples/build$ sysrepocfg -X -x "/ex-interface:interfaces" -d operational > ../ex-interface-oper-data2.xml 
vagrant@debian10:~/dev/sysrepo/examples/build$ yanglint
> add ../ex-interface.yang
> data ../ex-interface-oper-data2.xml 
libyang[0]: Unique data leaf(s) "hw_index" not satisfied in "/ex-interface:interfaces/interface[name='eth1']" and "/ex-interface:interfaces/interface[name='eth0']". (path: /ex-interface:interfaces/interface[name='eth0'])
Failed to parse data.
> 

```

Zip file with .c, .xml and .yang below:
[c_xml_yang.zip](https://github.com/sysrepo/sysrepo/files/5766304/c_xml_yang.zip)

**Comment by michalvasko** [comment]
Right, NMDA specifies that the operational datastore may not be [valid](https://tools.ietf.org/html/rfc8342#section-5.3.1) at all times. There is not much choice of implementing this but now validating this datastore at all, hence unique not being enforced, among other constraints,

**Comment by Reshad-Rahman** [comment]
Are you saying that unique is not enforced at all for operational datastore?

I changed the nodes to config true and I see the same issue in running datastore.

```
$ sysrepocfg -X -x "/ex-interface:interfaces" -d running
<interfaces xmlns="http://www.reshad.com/yang/ex-interface">
  <interface>
    <name>eth0</name>
    <hw_index>1</hw_index>
    <sw_index>0</sw_index>
  </interface>
  <interface>
    <name>eth1</name>
    <hw_index>1</hw_index>
    <sw_index>1</sw_index>
  </interface>
  <interface>
    <name>eth2</name>
    <hw_index>1</hw_index>
    <sw_index>2</sw_index>
  </interface>
  <interface>
    <name>eth3</name>
    <hw_index>1</hw_index>
    <sw_index>3</sw_index>
  </interface>
  <interface>
    <name>eth4</name>
    <hw_index>1</hw_index>
    <sw_index>4</sw_index>
  </interface>
  <interface>
    <name>eth5</name>
    <hw_index>1</hw_index>
    <sw_index>5</sw_index>
  </interface>
  <interface>
    <name>eth6</name>
    <hw_index>1</hw_index>
    <sw_index>6</sw_index>
  </interface>
  <interface>
    <name>eth7</name>
    <hw_index>1</hw_index>
    <sw_index>7</sw_index>
  </interface>
  <interface>
    <name>eth8</name>
    <hw_index>1</hw_index>
    <sw_index>8</sw_index>
  </interface>
  <interface>
    <name>eth9</name>
    <hw_index>1</hw_index>
    <sw_index>9</sw_index>
  </interface>
</interfaces>
```

**Comment by michalvasko** [comment]
Um, how did you manage to set `config false` data for `running` datastore? That is the problem, not that they are not unique.

**Comment by Reshad-Rahman** [comment]
> Um, how did you manage to set `config false` data for `running` datastore? That is the problem, not that they are not unique.

I changed ex-interface.yang so that all nodes are config true.

**Comment by michalvasko** [comment]
Okay, you are right, they can be imported by *sysrepocfg* because it parses them with `LYD_OPT_TRUSTED` and then *libyang* validation considers them valid even when validating them in *sysrepo*. This is one of many reasons why we are working on *sysrepo* using *libyang* version 2, using the current *libyang* it is not possible to implement correctly for all the cases so there is nothing we can do about this right now.

**Comment by Reshad-Rahman** [comment]
Thank you Michal. Will the new version of _sysrepo_ using _libyang_ version 2 address this?

**Comment by michalvasko** [comment]
Yes, it is already working correctly there.

**Comment by Reshad-Rahman** [comment]
I tried _libyang2_ branch and this works fine in _running_ datastore but not in _operational_ datastore. There was a comment made above that based on [RFC8342-section5.3.1](https://tools.ietf.org/html/rfc8342#section-5.3.1), it's expected that the _operational_ datastore is not always valid. While I understand how this can happen when changes are being made to `config true` nodes, in my example `hw_index` is `config false`. So I don't fully understand why this enforcement of `unique` data nodes can not be made in _operational_ datastore.

**Comment by michalvasko** [comment]
Because, in theory, your device may just be changing its state and temporarily break the `unique` constraint. That is what the NMDA RFC mentions and allows. However, validating state nodes is sort-of redundant in any case because they are always generated by an application. So it is its responsibility to generate valid nodes (unless it is in the special state mentioned at the beginning).

**Comment by Reshad-Rahman** [comment]
I agree with the comment that it is the application's responsibility to generate valid nodes and having sysrepo validate state nodes can be viewed as redundant (performance hit). But in the context of only state data changing, even then I don't think the `unique` constraint should be temporarily broken (transactions can be used to avoid this). But it's possible I'm thinking only of simple cases.

**Comment by michalvasko** [comment]
The NMDA specifies `unique` can be broken, that is all that matters here, we are fully compliant with it.

**Comment by michalvasko** [comment]
Yes, that is intentional. Note that you can always use `<validate>` to learn whether the datastore is valid or not.

**Comment by nickbroon** [comment]
Similarly, are must/when constraints enforced on the input/out nodes of RPC definitions? Or, as they reference operational datastore data, are these constraints also ignored by sysrepo?

eg, in something like:

```
rpc install-image {
    input {
      leaf name {
        description "The name of the downloaded image to install";
        type leafref {
          path "/image:downloaded-images/downloaded-image/name";
        }
        must "deref(current())/../status = 'downloaded' and not(/image:installed-images/installed-image[deref(current())/../version])";
      }
    }
    output {
      leaf status {
        description "If the installation was successful or not";
        type installation-status;
      }
      leaf failure-reason {
        when "../status = 'failed'";
        description "The reason that the installation failed";
        type installation-failure-reason;
      }
    }
  }
```

**Comment by michalvasko** [comment]
Referencing `operational` is fine, it is specified only for the datastore itself that it may be invalid.

**Comment by nickbroon** [comment]
ok, thanks for the clarification. So just to confirm, sysrepo will enforce the rpc when/must constraints on rpc?

**Comment by michalvasko** [comment]
Yes, that was clearly implied.
