### ISSUE TITLE
is there a API to check the given xpath exist in sysrepo?  

### ISSUE THREAD

**Issue by itercheng** [sysrepo/sysrepo#2269]
dear sysrepo expert:

examples a xpath:  /module/container/list/leaf.   firstly i want to check  whether "/module/container" exist in sysrepo, if not exist, i will not check and traverse it's children path. so i want to know whether there is a API to finish this function? please feel free to let me know if you need more details.

**Comment by michalvasko** [comment]
Just use some simple getter (such as `sr_get_item()`) to retrieve the value, you can easily check that there is none.

**Comment by itercheng** [comment]
understand your means. actually we don't want to judge whether a value is exist by sr_get_item.   only want to check whether this container xpath of this leaf  exist in sysrepo? such as /module/container/list/leaf1, /module/container/list/leaf2, and /module/container/list/leaf3, if /module/container xpath didn't exist in sysrepo. it will not be  necessary to traverse it's leaf so that save many times. so i wonder that is there a API to judge XPATH(include container, list. leaf) exist in sysrepo?  thank you in advance

**Comment by michalvasko** [comment]
Okay, to be more explicit, no, there is no specific API to check node existence as it would be mostly redundant. Instead, use `sr_get_item()` (it is the most efficient getter) to retrieve the value and if it fails (not found error) you know the value does not exist.

**Comment by czxkgxy** [comment]
Now sysrepo is very powerful. Maybe there is an API to check the existence of nodes, which will greatly reduce the number of database reading, because many data are optional in actual operation, just like "choice" in Yang.

**Comment by czxkgxy** [comment]
Now sysrepo is very powerful. Maybe there is an API to check the existence of nodes, which will greatly reduce the number of database reading, because many data are optional in actual operation, just like "choice" in Yang.

**Comment by michalvasko** [comment]
Well, third time is the charm, so once again, use `sr_get_item()`. The performance difference between a special function for just checking a node existence and this one would be minimal.

**Comment by itercheng** [comment]
all right. i will use it to accomplish our function. thank you very much.
