### ISSUE TITLE
module.startup file becomes all zero data after power off

### ISSUE THREAD

**Issue by ryanking8215** [sysrepo/sysrepo#2270]
I have ported new sysrepo to a embedded system which is a  device with ARM cpu, openwrt sytem, and F2FS filesystem.

After writing data to my module (through netopeer2-server, edit-config, commit, copy-config), then power off the device immediately, the module startup file will be all zero data after  power up, and sysrepo  reports `Invalid first magic number byte "0x00"`.

I understand that power off will make filesystem lost data, but I don't know why sysrepo file becomes all zero data rather than keeping old data, which makes the sysrepo broken.

**Comment by michalvasko** [comment]
I believe this is a problem of your platform/filesystem, nothing to do with *sysrepo*. You can change the repository path in case the default one is not suitable.
