### ISSUE TITLE
cannot specify error-tag 

### ISSUE THREAD

**Issue by DineshReddyK** [sysrepo/sysrepo#2271]
Hi,
For edit-config request, we would like to specify the error-tags mentioned in [RFC6241](https://tools.ietf.org/html/rfc6241#appendix-A)

But, if we use `sr_set_error` API, it can only give `operation-failed`.
How can I set error tag like, `invalid-value` , `access-denied` etc.?

**Comment by michalvasko** [comment]
Right, that is not supported currently. But it will be, eventually, once I get to it but since it is just a minor improvement and I am swamped with other more important tasks, it may take some time.
