### ISSUE TITLE
A question：an empty value and  config false nodes in edit config，how can I ignore it？

### ISSUE THREAD

**Issue by Julian-younger** [sysrepo/sysrepo#2272]
hi,michal,
   An empty value and  config false nodes in edit config，how can I ignore it？Now I can get some checking error,sometimes I can not change the XML,I just want to ignore it,any good solutions?

```
> 
> <edit-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
>   <target>
>     <running/>
>   </target>
>   <config>
>     <test xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
>       <name/>                              //string node
>       <uid> test</uid>                //config false
>       <ver>3</ver>                    // the value i want to edit
>     </test>
>   </config>
> </edit-config>
```

**Comment by michalvasko** [comment]
I do not think you can do this without editing *netopeer2* code. This simply is not supported since it is not compliant with NETCONF `edit-config` RPC.

**Comment by Julian-younger** [comment]
I get it，Thanks！
