### ISSUE TITLE
Performance of sr_get_item() v/s sr_get_items()

### ISSUE THREAD

**Issue by Reshad-Rahman** [sysrepo/sysrepo#2275]
I am using the example provided for issue #2268 (see c_xml_yang.zip in that issue), only change is that all nodes are config true. I have an interface list keyed on name (string), hw_index is an int (unique) and sw_index is also an int.

I have modified sr_get_items_example.c: an extra optional parameter can be set to "single" to call sr_get_item() instead of sr_get_items(). Using sr_get_item() or sr_get_items() for a specific name, hw_index or sw_index takes approximately the same amount of time: 

1. ~500msec with 100K interfaces
2. ~50msec with 10K interfaces
3. ~5msec with 1K interfaces

Some observations/questions:

1. I was expecting sr_get_item() to be faster when using the name (list key). I can understand why sr_get_items() would be O(n) but sr_get_item() should ideally not be O(n) when using the key as input.
2. For lists, do the get_item(s) functions search linearly or are there hash tables for keys and unique attributes? And does this depend on RUNNING vs OPERATIONAL? From cursory look at the code, sr_modinfo_get_filter() calls lyd_find_xpath() which does linear search.

```
vagrant@debian10:~/dev/sysrepo/build$ git branch
* devel
  master
vagrant@debian10:~/dev/sysrepo/build$ sysrepocfg --version
sysrepocfg - sysrepo configuration manipulation tool, compiled with libsysrepo v1.4.96 (SO v5.6.12)

vagrant@debian10:~/dev/sysrepo/build$ yanglint --version
yanglint SO 1.9.22
vagrant@debian10:~/dev/sysrepo/build$
```

**Comment by michalvasko** [comment]
In both 1) and 2) all the instances must be checked linearly, that is why the performance is the same. XPath filtering is quite difficult to optimize.

However, there were optimizations performed in *libyang* version 2 so you should notice the difference there. There is still the problem of inefficient datastore that we also plan to work on this year. In general, it is pointless to test performance of *sysrepo* with *libyang* version 1 because no optimizations will be implemented.

**Comment by Reshad-Rahman** [comment]
Thank You Michal. I understand that XPath filtering is difficult to optimize.  
I'll do my tests with _sysrepo_ using _libyang_ version 2. So will the performance  of get_item() be better (eventually?) than get_items() when using list key or unique data node?

**Comment by michalvasko** [comment]
The performance of `sr_get_item()` and `sr_get_items()` is the same, generally speaking. Of course, the more nodes you select, the (somewhat) slower it will be and you cannot get more nodes in `sr_get_item()`. But if you select a single node, the performance must be the same.

**Comment by Reshad-Rahman** [comment]
For lists, will the performance be the same when using the following in the XPath/Path i.e. is it a linear search in all cases below:

- List key (name in my example)
- Unique node (hw_index in my example)
- Non-unique node (state in my example)

**Comment by michalvasko** [comment]
This is how it works in *libyang* version 2. Whenever you have some XPath, every node in the path is found in `O(1)` as long as it is uniquely identified. Meaning for lists there must be all its keys and for leaf-lists their value. Otherwise all the siblings must be searched in `O(n)`.

So, if you have `/ex-interface:interfaces/interface[name='eth0']/name`, that will be `O(1)`. But `/ex-interface:interfaces/interface/name` will take `O(n)`, `n` is number of `interface` instances. The same goes for `/ex-interface:interfaces/interface[name='eth0']/hw_index` and `/ex-interface:interfaces/interface/hw_index` or any other leaf. If there are 2 lists in the XPath, they both must be specified with all their keys to get constant complexity. If a leaf-list is at the end, you specify it as `.../leaf-list[.='value']`. Note that the predicates must look exactly this way, otherwise the optimization will not recognize it and general XPath evaluation is used that traverses all the nodes.

**Comment by Reshad-Rahman** [comment]
Excellent, let me try it out. Thanks again Michal.

**Comment by Reshad-Rahman** [comment]
I redid the tests with the `libyang2` branch and the results are similar to the results I obtained using the `devel` branch.  One difference is that now using `name` (the list key) is a bit faster than using `hw_index` or `sw_index`. For example, with 100K interfaces:
Using` /ex-interface:interfaces/interface[name=\'eth99999\'] ` takes ~400 ms, but using `hw_index=99999` or `sw_index=99999` takes ~550 ms. 


```
vagrant@libyang2-vm:~/dev/sysrepo-libyang2-Jan6/build$ git log
commit eccf402f362891e60fa6b8f9bb33f522476dfc14 (HEAD -> libyang2, origin/libyang2)
Author: Michal Vasko <mvasko@cesnet.cz>
Date:   Tue Aug 11 13:45:45 2020 +0200

    sysrepo REFACTOR initial libyang2 support

commit b4f08a4aad8e2a871623d9ce99c129904727de3d
Author: Michal Vasko <mvasko@cesnet.cz>
Date:   Fri Dec 11 11:59:08 2020 +0100

    build BUGFIX valgrind environment vars name typo

vagrant@libyang2-vm:~/dev/libyang2/build$ git log 
commit ddace2cb5bc1a33fb31105da8c5a91664117b780 (HEAD -> libyang2, origin/libyang2)
Author: Radek Krejci <rkrejci@cesnet.cz>
Date:   Fri Jan 8 11:30:56 2021 +0100

    libyang REFACTOR avoid connection between context and log location storage
    
    libyang works strictly with a single context now, so it is not necessary
    to connect the log location information with a specific context. It also
    clarifies what to do when the context is not available in the function
    but still a location information in an error message could be useful.


```

**Comment by michalvasko** [comment]
Right, I would say it makes sense. Generally, evaluation of predicates (except those special ones) is quite slow. It is quite possible its complexity is quadratic so using completely redundant predicates the way you did is definitely not advised. Also note that most of the time spent of these functions (except for the slowest cases) is by parsing the datastore before it can be filtered. You can try using `SR_CONN_CACHE_RUNNING` for the `connection` you are using, that should ged rid of it, except for the first get on a module data.

**Comment by Reshad-Rahman** [comment]
Is O(n) expected when doing get_item() using the key? It looks their is some linear search going on. Is this because of the check for multiple subtrees?

I was hoping to have a version of get_item() which isn't linear (I know there is max of 1 subtree if all the keys are provided, no * in the path and the path refers to a leaf node). I acknowledge that XPath filtering is not straight-forward, so optimally handling this specific case with generic code which handles all cases can be a problem.

Also I'm happy to see that get_item(s) using the key is faster than using another leaf node. Is this because lookup using the key is optimized?

**Comment by michalvasko** [comment]
Like I said before, the time taken by these calls is generally split into parsing data and filtering them, the former can often take much more time, actually. And yes, if using the specific predicates (such as all keys for lists), the filtering should be optimized to `O(1)`. But the parsing should always be `O(n)`.

**Comment by Reshad-Rahman** [comment]
Got it.

**Comment by huangyl-git** [comment]
why now I usr sr_get_item API  to get one leaf data，the time needs 650ms, all configs number is only 0.5k subinterface.
 libyang ver : 2.1.148
sysrepo ver : 2.2.150

**Comment by michalvasko** [comment]
I can only suggest using running cache (`sr_connect()` flag `SR_CONN_CACHE_RUNNING`) to avoid repeated data parsing.

**Comment by huangyl-git** [comment]
> I can only suggest using running cache (`sr_connect()` flag `SR_CONN_CACHE_RUNNING`) to avoid repeated data parsing.

I use running cache (sr_connect() flag SR_CONN_CACHE_RUNNING), but First data reading after connection takes 600ms，and the seond,third,..., reading data in same connection takes 1ms.

**Comment by michalvasko** [comment]
Yes, that means it works exactly as it should.
