### ISSUE TITLE
edit_diff.c:2954: sr_ly_val_diff_merge: Assertion

### ISSUE THREAD

**Issue by robbynet** [sysrepo/sysrepo#2279]
Hello,
configuration depends on libyang (v1.0.184) and sysrepo (v1.4.70).
We are used to perform the following command on O-RAN v3.0 ( set of 33 yang modules ): 
sysrepocfg --verbosity 3 --edit=toto.xml --datastore=candidate --format=xml
Without any issue

Moving to O-RAN v4.0 ( diffuse change in different modules ) without changing anything to toto.xml and without changing libyang/syrepo we have the following Abort of cmd sysrepocfg : 
sysrepocfg: /opt/dev/sysrepo/src/edit_diff.c:2954: sr_ly_val_diff_merge: Assertion `set && (set->number == 1)' failed.
Aborted

Issue seems very closed to #1967 
Note : Base on discussions from this previous issue #1967, and trying to run same command with running db leads to the same issue : 
sysrepocfg --verbosity 3 --edit=toto.xml --format=xml
sysrepocfg: /opt/dev/sysrepo/src/edit_diff.c:2954: sr_ly_val_diff_merge: Assertion `set && (set->number == 1)' failed.
Aborted

**Comment by michalvasko** [comment]
Could you please supply all the YANG modules, data files, and steps to reproduce this? An assert should never fail so this should be fixed, not sure if it is related to any other issue.

**Comment by robbynet** [comment]
Hi,
Thanks for your support, before going deeper, I propose to wait for next sysrepo delivery and checked if issue is already here.
Christian.

**Comment by robbynet** [comment]
Scenario above rechecked with [version 1.1.53](https://github.com/CESNET/netopeer2/releases/tag/v1.1.53).
Quit same issue faced with this new release, traces of the crash of sysrepocfg are the following : 
sysrepocfg: /opt/dev/sysrepo/src/edit_diff.c:3024: sr_ly_val_diff_merge: Assertion `set && (set->number == 1)' failed.
/opt/dev/script/provisionning.sh: line 10:   400 Aborted                 
(core dumped) sysrepocfg --verbosity 3 --edit=/opt/dev/xml/uplane.xml --datastore=candidate --format=xml
Note : Got information that O-RAN Yang modules can only be shared via connection on https://www.o-ran.org/
Regards.
Christian.

**Comment by michalvasko** [comment]
Okay, that is definitely interesting and I really am not able to help you without the modules. If you cannot even send them to me privately, you can only try to write your own modules that will reproduce this. Otherwise I cannot help you.
