### ISSUE TITLE
module installation fails with failed to apply change

### ISSUE THREAD

**Issue by zain4681** [sysrepo/sysrepo#2281]
Hi,

i have a module o-ran-software-management which has dependency on o-ran-hadrware and ietf-hardware modules. as part of installation of o-ran-mplane-int.yang it automatically installed its dependencymodule which is ietf-hardware module.
now after this when we try to install o-ran-software-management module we are getting below error. we were assuming that dependency on o-ran-hardware should get resolved automatically and that module also should get installed.

$  sysrepoctl -a -i /usr/share/yang/modules/netopeer2/o-ran-mplane-int.yang -s /usr/share/yang/modules/netopeer2:/usr/share/yang/modules/additional_modules/ -p 600 -o _test-g _test -v4
[INF]: Applying scheduled changes.
[INF]: No scheduled changes.
[INF]: Module "o-ran-mplane-int" scheduled for installation.
[INF]: File "ietf-interfaces@2018-02-20.yang" was installed.
[INF]: File "o-ran-interfaces@2020-04-17.yang" was installed.
[INF]: File "iana-if-type@2017-01-19.yang" was installed.
[INF]: File "ietf-ip@2018-02-22.yang" was installed.
[INF]: File "ietf-hardware@2018-03-13.yang" was installed.
[INF]: File "iana-hardware@2018-03-13.yang" was installed.
[INF]: Applying scheduled changes.
[INF]: File "o-ran-mplane-int@2019-07-03.yang" was installed.
[INF]: Module "o-ran-mplane-int" was installed.
[INF]: Dependency module "ietf-interfaces" was installed.
[INF]: Dependency module "o-ran-interfaces" was installed.
[INF]: Dependency module "ietf-ip" was installed.
[INF]: Dependency module "ietf-hardware" was installed.
[INF]: Scheduled changes applied.

$ sysrepoctl -a -i /usr/share/yang/modules/netopeer2/o-ran-software-management.yang -s /usr/share/yang/modules/netopeer2:/usr/share/yang/modules/additional_modules/ -p 600 -o _test -g _test -v4
[INF]: Applying scheduled changes.
[INF]: No scheduled changes.
[INF]: Module "o-ran-software-management" scheduled for installation.
[INF]: File "o-ran-hardware@2020-04-17.yang" was installed.
[INF]: File "o-ran-file-management@2019-07-03.yang" was installed.
[INF]: Applying scheduled changes.
[WRN]: Identity found, but in a non-implemented module "ietf-x509-cert-to-name".
[WRN]: Failed to resolve identityref "ietf-x509-cert-to-name:specified". (path: /ietf-netconf-server:map-type)
[WRN]: Previous warning generated by XPath subexpression[3] "map-type = 'ietf-x509-cert-to-name:specified'".
[WRN]: Identity found, but in a non-implemented module "ietf-x509-cert-to-name".
[WRN]: Failed to resolve identityref "ietf-x509-cert-to-name:specified". (path: /ietf-netconf-server:map-type)
[WRN]: Previous warning generated by XPath subexpression[3] "map-type = 'ietf-x509-cert-to-name:specified'".
[WRN]: No resolvents found for leafref "/ietf-hardware:hardware/ietf-hardware:component/ietf-hardware:state/o-ran-hardware:availability-state". (path: /ietf-hardware:hardware-state-oper-enabled/o-ran-hardware:availability-state)
[WRN]: No resolvents found for leafref "/ietf-hardware:hardware/ietf-hardware:component/ietf-hardware:state/o-ran-hardware:availability-state". (path: /ietf-hardware:hardware-state-oper-disabled/o-ran-hardware:availability-state)
[WRN]: Module "o-ran-hardware" parsing failed.
[WRN]: Importing "o-ran-hardware" module into "o-ran-software-management" failed.
[WRN]: Module "o-ran-software-management" parsing failed.
[WRN]: Installing module "o-ran-software-management" failed.
[WRN]: Failed to apply some changes, leaving all changes scheduled.
[ERR]: Applying scheduled changes failed.
sysrepoctl error: Failed to apply changes (Operation failed)

could you please help us here. 

same thing works if i install o-ran-hardware module manually before installing o-ran-software-management. please note that o-ran-hardware auguments ietf-hardware.

 sysrepoctl -a -i /usr/share/yang/modules/netopeer2/o-ran-hardware.yang -s /usr/share/yang/modules/netopeer2:/usr/share/yang/modules/additional_modules/ -p 600 -o _test -g _test -v4
[INF]: Applying scheduled changes.
[INF]: No scheduled changes.
[INF]: Module "o-ran-hardware" scheduled for installation.
[INF]: Applying scheduled changes.
[INF]: File "o-ran-hardware@2020-04-17.yang" was installed.
[INF]: Module "o-ran-hardware" was installed.
[INF]: Scheduled changes applied.

 sysrepoctl -a -i /usr/share/yang/modules/netopeer2/o-ran-software-management.yang -s /usr/share/yang/modules/netopeer2 -p 600 -o _test -g _test -v4
[INF]: Applying scheduled changes.
[INF]: No scheduled changes.
[INF]: Module "o-ran-software-management" scheduled for installation.
[INF]: File "o-ran-file-management@2019-07-03.yang" was installed.
[INF]: Applying scheduled changes.
[INF]: File "o-ran-software-management@2019-07-03.yang" was installed.
[INF]: Module "o-ran-software-management" was installed.
[INF]: Scheduled changes applied.

it will be good if we get to know how dependency is resolved and modules get imported or installed automatically?

**Comment by jktjkt** [comment]
You have to stop all applications that are using sysrepo when trying to add/modify modules (actually, when trying to apply these "scheduled changes" that get scheduled when you try to install/uninstall/change a module).

**Comment by zain4681** [comment]
none of the application is using it.
the use case is as follows, feature is enabled and then data was added in sysrepo related to it.
on next system restart/upgrade feature needs to be disabled so when that was attempted since data is already referred in sysrepo db other modules we are getting this error.  one possible solution could be to delete the references and then disable feature.
is there any other option to solve this issue?

**Comment by michalvasko** [comment]
Please attach all the modules needed for reproducing this.
