### ISSUE TITLE
sysrepoctl installing some modules automatically and some importing when one module is being installed

### ISSUE THREAD

**Issue by zain4681** [sysrepo/sysrepo#2282]
Hi,

i would like to know based on what sysrepoctl installs certain modules and certain modules just import.

for example i m installing ietf-netconf-server it internally installs 'ietf-keystore' and 'ietf-truststore' modules and imports 'ietf-ssh-common': ['2019-07-02','ietf-ssh-server','ietf-tcp-client','ietf-tcp-common','ietf-tcp-server','ietf-tls-common','ietf-tls-server' etc modules. 

could you please help us to know how does it decide when to install and when to just import.

--

--

**Comment by michalvasko** [comment]
This is left up to *libyang*, which follows [the specification](https://tools.ietf.org/html/rfc7950#section-5.6.5). Additionally, what is mentioned there is also true for `deviation` but it is only implied in the text, not specified directly for some reason.
