### ISSUE TITLE
sr_get_items not working for config false with union operator in operational datastore

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2283]
Hi,

I would like to use union operator in **sr_get_items**().
It works fine with config data:
 
```
$ sr_get_items_example "/ietf-interfaces:interfaces/interface[name='eth0']/description | /ietf-interfaces:interfaces/interface[name='eth0']/type" operational
Application will get "/ietf-interfaces:interfaces/interface[name='eth0']/description | /ietf-interfaces:interfaces/interface[name='eth0']/type" from "operational" datastore.
 
/ietf-interfaces:interfaces/interface[name='eth0']/description = Ethernet
/ietf-interfaces:interfaces/interface[name='eth0']/type = iana-if-type:ethernetCsmacd
```
 
But when I try to get _'config false'_ leaves it returns an empty result set:
 
```
$ sr_get_items_example "/ietf-interfaces:interfaces/interface[name='eth0']/admin-status | /ietf-interfaces:interfaces/interface[name='eth0']/oper-status" operational
Application will get "/ietf-interfaces:interfaces/interface[name='eth0']/admin-status | /ietf-interfaces:interfaces/interface[name='eth0']/oper-status" from "operational" datastore.
```
 
while the leaves are returned properly without union operator:
 
```
$ ./sr_get_items_example "/ietf-interfaces:interfaces/interface[name='eth0']/admin-status" operational
Application will get "/ietf-interfaces:interfaces/interface[name='eth0']/admin-status" from "operational" datastore.
 
/ietf-interfaces:interfaces/interface[name='eth0']/admin-status = up
 
$ sr_get_items_example "/ietf-interfaces:interfaces/interface[name='eth0']/oper-status" operational
Application will get "/ietf-interfaces:interfaces/interface[name='eth0']/oper-status" from "operational" datastore.
 
/ietf-interfaces:interfaces/interface[name='eth0']/oper-status = down
```
 
I attached the example application for reproduction.
[test.zip](https://github.com/sysrepo/sysrepo/files/5797148/test.zip)

sysrepo version: 1.4.96
libyang version: 1.0.205

Thanks!

**Comment by jktjkt** [comment]
You're connecting to the `running` datastore. Sysrepo is NMDA-aware, which means that operational (`config: false`) data are only available via the [`operational` datastore](https://tools.ietf.org/html/rfc8342#section-5.3).

**Comment by awesomenode** [comment]
I changed the example to switch to operational datastore before sr_oper_get_items_subscribe() operations, but the behavior remained the same.
[test.zip](https://github.com/sysrepo/sysrepo/files/5801095/test.zip)

**Comment by jktjkt** [comment]
Yup, confirming, I'm seeing the same behavior.

**Comment by michalvasko** [comment]
Right, union was not handled when getting `operational` data, should be now.
