### ISSUE TITLE
error: 'sr_fd_change_t' has not been declared

### ISSUE THREAD

**Issue by gurugod** [sysrepo/sysrepo#2286]
hi ,
I was using sysrepo-0.7.4 before . Now I am moving sysrepo to sysrepo-1.4.70.
Similarly i will upgrade Netopeer and Libnetconf .
In previous version I could see a structure in inc/sysrepo.h
```
typedef struct sr_fd_change_s {
    int fd;                 /**< File descriptor whose monitored state should be changed. */
    int events;             /**< Monitoring events tied to the change (or-ed value of ::sr_fd_event_t). */
    sr_fd_action_t action;  /**< Action that is supposed to be performed by application-local file descriptor watcher. */
} sr_fd_change_t;
```
but in new sysrepo version sysrepo-1.4.70 it is not available.
I just wanted to know Is sysrepo-1.4.70  doing file descriptor monitoring or not ?or there are some changes in APIs and structure ?
Can you help me here ?
Thanks in advance .

**Comment by jktjkt** [comment]
Yes, this API got reworked. It is now a bit easier to work with (IMHO), and there's now a 1:1 mapping between the opened pipes that your event loop has to monitor and active `sr_subscription_ctx_t` instances.

If you're using C C, see `sr_get_event_pipe` and `sr_process_events`. If you happen to use C++, you can use these bindings like this:
```c++
class EventLoop {
    void registerSysrepoFd(int fd, const std::function<void()>& sub) {
        // You have to implement this one. Your event loop must invoke `sub` when there's any IO event on `fd`.
    }
    void unregisterSysrepoFd(int fd) {
        // you have to implement this one as well
    }
};

EventLoop eventLoop;
auto subscription = std::make_shared<::sysrepo::Subscribe>(session,
        [] (auto fd, auto sub) { eventLoop.registerSysrepoFd(fd, sub); },
        [] (auto fd) { eventLoop.unregisterSysrepoFd(fd); });
```

**Comment by gurugod** [comment]
thanks jan for quick resolution. We will try this new APIs and get it done.
Thanks a lot.
