### ISSUE TITLE
close-session call back not works in the sysrepod plugin

### ISSUE THREAD

**Issue by panniruram** [sysrepo/sysrepo#2290]
Hi @michalvasko,

**For the cleaning of data and other things in the POD, we want to handle the close-session RPC in the sysrepo plugin.**
      Immediately stop sending the notifications and other responses if any.

But whenever we try to subscribe and send close-session RPC from the user(netopeer2-cli) callback of the close session not executing.
```C
rc = sr_rpc_subscribe(session, "/ietf-netconf:close-session", close_sess_cb, (void *)session, 0, SR_SUBSCR_DEFAULT, &subscription);
    if (SR_ERR_OK != rc) {
        SRP_LOG_ERR("Error by sr_rpc_subscribe: %s\n", sr_strerror(rc));
    }

static int
close_sess_cb(sr_session_ctx_t *session, const char *xpath, const sr_val_t *input, const size_t input_cnt, sr_event_t event, uint32_t request_id, sr_val_t **output, size_t *output_cnt, void *private_data)
{
    int rc = SR_ERR_OK;

      SRP_LOG_DBGMSG("Recvd close-session RPC.");
  /* ........
   ............
   */
 return rc;
}
```
netopeer2-cli: user-rpc(succeed)
```xml
<close-session xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
</close-session>
```
After came to know that, these RPC handled only in libnetcof2 and says 
  /* leave close-session RPC empty, libnetconf2 will use its callback */

So, How to handle the close-session RPC in sysrepo plugin when comes from the client(last sudo user sends the rpc for “close-session”)  ?
Please suggest if any other way to handle.

Thanks

**Comment by michalvasko** [comment]
You are right, subscribing directly to `close-session` has no effect but it is handled directly, not through *sysrepo*. What about subscribing to the `netconf-session-end` notification instead? Should get you the same functionality.

**Comment by panniruram** [comment]
@michalvasko  Thanks for the suggestions.

Have one more query, 
Subscribed for the "sr_event_notif_subscribe_tree" and callback works when start new session and close-session as well as.
  rc = sr_event_notif_subscribe_tree(session, "ietf-netconf-notifications", "/ietf-netconf-notifications:netconf-session-start", 0, 0, session_start_callback, NULL, SR_EV_NOTIF_REPLAY, &subscription);
       
rc = sr_event_notif_subscribe_tree(session, "ietf-netconf-notifications", "/ietf-netconf-notifications:netconf-session-end", 0, 0, notif_callback, NULL,  SR_SUBSCR_CTX_REUSE, &subscription);

But when trying to access the session details. its not working as per accepted. Below session ID always print as 0. we need these session details(like session id, Username etc..).  Could you please help me what's wrong with the shared code. And let us know if have any alternate solutions to get the session id and username for the close-session.

static void
notif_callback(sr_session_ctx_t *session, const sr_ev_notif_type_t notif_type, const struct lyd_node *notif, time_t timestamp, void *private_data)
{
    int nc_id = sr_session_get_nc_id(session);
        **SRP_LOG_ERR("Sessions id:%d", nc_id);**
}

**Comment by michalvasko** [comment]
Please do not ask the same question twice, I do see it no matter where you write it I just do not have the time to immediately (currently not even within days, often) to respond.
