### ISSUE TITLE
Fail to retrieve state data from augments with same target node

### ISSUE THREAD

**Issue by Terry0109** [sysrepo/sysrepo#2291]
Hi，

Recently I encountered an issue when using V0.7.8 sysrepo. Reproducing steps are as follows:

**1. Relative yang files.**
ietf-hardware.yang and o-ran-hardware.yang. There are two augments with the same target node in o-ran-hardware.yang: 

**Augment 1:**

      augment "/hw:hardware/hw:component" {
        when "derived-from-or-self(hw:class, 'o-ran-hw:O-RAN-RADIO')";
        description "New O-RAN parameters for o-ran hardware";
    
        container label-content {
          config false;
          description
            "Which set of attributes are printed on the Radio Unit's label";
          leaf model-name {
            type boolean;
            description
              "indicates whether model-name is included on the equipment's label";
          }
          leaf serial-number {
            type boolean;
            description
              "indicates whether serial number is included on the equipment's label";
          }
          // add in other leafs according to manufacturer feedback on labels
        }
        leaf product-code {
          type string;
          config false;
          mandatory true;
          description
            "O-RAN term that is distinct from model-name in ietf-hardware.";
        }
        leaf energy-saving-enabled {
          if-feature "ENERGYSAVING";
          type boolean;
          config true;
          default false;
          description
            "This parameter can enable O-RAN unit to be switched to energy
             saving mode.
             TRUE indicates to switch the energy saving mode.
             FALSE indicates to cancel the energy saving mode.
             At the energy saving mode, all power of whole O-RAN unit becomes
             lowest level whereas M-plane is still available";
        }
      }

**Augment 2:**

       augment "/hw:hardware/hw:component" {
        when "derived-from-or-self(hw:class, 'o-ran-hw:O-RAN-RADIO') or
        derived-from-or-self(hw:class, 'ianahw:port')";
        description "New O-RAN parameters for o-ran naming";
        leaf o-ran-name {
          type leafref {
            path "/hw:hardware/hw:component/hw:name";
          }
          must "re-match(current(),'[a-zA-Z0-9][a-zA-Z0-9\\.\\-_]{0,253}[a-zA-Z0-9]')" {
            error-message "Name must match pattern and length.";
          }
          mandatory true;
          description
            "O-RAN name needed to bind and match with the name of hw element,
            to be compliant with O-RAN naming convention.";
        }
      }

**2. Subscribe for providing state data.**

**3. Get state data with the xpath /ietf-hardware:hardware/component**
All  nodes work well except for state data from augment 1. When getting them, the sysrepod will prompt:

        “0 subtrees of state data will be attempted to load in order to resolve” in function rp_dt_xpath_requests_state_data.
        “No state state data provider is asked for data because of xpath” in function rp_dt_prepare_data. 

Checking the internal file "sysrepo-module-dependencies.lyb", actually it doesn't include these nodes from augment 1 .

**4. Add some debugging statements to troubleshoot in the function md_traverse_schema_tree.**

      static int
      md_traverse_schema_tree(md_ctx_t *md_ctx, md_module_t *module, struct lys_node *root, sr_list_t *being_parsed)
      {
          int rc = SR_ERR_OK;
          struct lys_node *node = NULL, *child = NULL, *parent = NULL, *iter = NULL;
          const struct lys_module *main_module_schema = NULL;
          md_module_t *dest_module = NULL;
          bool process_children = true;
          const char *when = NULL, *xpath = NULL;
          struct lys_restr *must = NULL;
          size_t must_size = 0;
          bool backtracking = false;
          bool augment = false;
          CHECK_NULL_ARG(md_ctx);
 	      
      
          if (NULL == root) {
              return SR_ERR_OK;
          }
      
          augment = (root->nodetype == LYS_AUGMENT ? true : false);
      
          main_module_schema = lys_node_module(root);
      
          printf("\r\n##########[md_traverse_schema_tree0]module:%s      root:%s  main_module_schema:%s\r\n", module->name, root->name,main_module_schema->name);
	      
          dest_module = (augment ? md_get_destination_module(md_ctx, being_parsed, root) : module);
          if (NULL == dest_module) {
              /* shouldn't happen as all imports are already processed */
              SR_LOG_ERR_MSG("Failed to obtain the destination module of a schema node.");
              return SR_ERR_INTERNAL;
          }
         printf("##########[md_traverse_schema_tree1]dest_module:%s\r\n", dest_module->name);
          /* schema traversal (non-recursive DFS post-order on each root) */
          do {
              node = root;	       
             printf("##########[md_traverse_schema_tree_do]node:%s\r\n", node->name);	 
                ………………………………………………………………
                  /* must */
                  for (size_t i = 0; NULL != must && i < must_size; ++i) {
                      rc = md_collect_data_dependencies(md_ctx, must[i].expr, dest_module, module, being_parsed, node, LYXP_MUST);
                      if (SR_ERR_OK != rc) {
                          return rc;
                      }
                  }
      
                  /* operational data subtrees */
            //! @cond doxygen_suppress
            #define PRIV_OP_SUBTREE  1
            #define PRIV_CFG_SUBTREE 2
            //! @endcond
                  rc = SR_ERR_OK;
                  printf("##########[md_traverse_schema_tree2]node:%s      module:%s\r\n", node->name, node->module->name);
                  ………………………………………………………………

**5. Some troubleshooting information when installing the module o-ran-hardware.yang:**
       Obviously it's a problem that aument 1 includes "o-ran-name" node.

        ##########[md_traverse_schema_tree0]module:o-ran-hardware      root:/ietf-hardware:hardware/ietf-hardware:component  main_module_schema:o-ran-hardware
        ##########[md_traverse_schema_tree1]dest_module:ietf-hardware
        ##########[md_traverse_schema_tree_do]node:/ietf-hardware:hardware/ietf-hardware:component
        ##########[md_traverse_schema_tree2]node:model-name      module:o-ran-hardware
        ##########[md_traverse_schema_tree2]node:serial-number      module:o-ran-hardware
        ##########[md_traverse_schema_tree2]node:label-content      module:o-ran-hardware
        ##########[md_traverse_schema_tree2]node:product-code      module:o-ran-hardware
        ##########[md_traverse_schema_tree2]node:energy-saving-enabled      module:o-ran-hardware
        ##########[md_traverse_schema_tree2]node:o-ran-name module:o-ran-hardware
        
        ##########[md_traverse_schema_tree0]module:o-ran-hardware      root:/ietf-hardware:hardware/ietf-hardware:component  main_module_schema:o-ran-hardware
        ##########[md_traverse_schema_tree1]dest_module:ietf-hardware
        ##########[md_traverse_schema_tree_do]node:/ietf-hardware:hardware/ietf-hardware:component
        ##########[md_traverse_schema_tree2]node:o-ran-name      module:o-ran-hardware
        ##########[md_traverse_schema_tree2]node:/ietf-hardware:hardware/ietf-hardware:component      module:o-ran-hardware

**6. If Removing augment 2 or switching their location in o-ran-hardware.yang, the issue will disappear after reinstalling it.**

I think there are some problems to deal with augment nodes that have same target node. Could you give me some suggestions? Any help is appreciated.

[yang.zip](https://github.com/sysrepo/sysrepo/files/5859479/yang.zip)

**Comment by michalvasko** [comment]
I am sorry, this seems like way too much work to even reproduce and since *sysrepo* 0.7.8 is long obsolete, I will not be fixing this.

**Comment by Terry0109** [comment]
Hello Michalvasko, thank you for your reply! I'm afraid that this obsolete version may have some other issues or unsupported features. In your view, is it necessary for me to update the sysrepo to the latest version?

**Comment by michalvasko** [comment]
Well, if it did not have other issues and unsupported features there would not be a new version, obviously. We are keeping this `legacy` *sysrepo* only for users that were already using it before the new *sysrepo* and it works for them. As soon as you require support because something does not work, you must always use the latest version. That is only natural, because in all other cases the issue you are having could have already been fixed.
