### ISSUE TITLE
Are nodes sorted according to the schema when using `sr_get_data`?

### ISSUE THREAD

**Issue by syyyr** [sysrepo/sysrepo#2292]
Hi,
if I have this kind of program:
```cpp
...
auto data = session->get_data("/my-module:cont");
for (const auto node : data->tree_dfs()) {
    std::cout << node->path() << "\n";
}
...
```
what will be the order of the nodes I get from `tree_dfs`? If I have this schema:
```yang
module my-module {
    yang-version 1.1;
    namespace "http://example.com";
    prefix my-mod;
    container cont {
        leaf a {
            type string;
        }

        leaf b {
            type string;
        }
    }
}
```
and both `a` and `b` exist in the datastore, will I always get leaf `a` followed by `b`? If yes, can you guarantee that (by writing it somewhere in the documentation)? If not, can I solve this by using `lyd_schema_sort`?

Thanks.

**Comment by michalvasko** [comment]
No, there are no guarantees in the order of the data nodes and yes, you can use `lyd_schema_sort` to get the order. Once *sysrepo* uses *libyang* version 2, this sorting will be guaranteed.

**Comment by syyyr** [comment]
Okay, thanks.
