### ISSUE TITLE
Can sysrepo keep an empty container?

### ISSUE THREAD

**Issue by agva123** [sysrepo/sysrepo#2296]
Hi, I observed an issue for old version of sysrepod.

If I have a container with a list as its only child:

container parent
{
  container foo {
      list bar
      {
          ....
      }
  }
}

Then, when the last element of the list bar is deleted then the container foo is also deleted from sysrepo. This is a behavior I observed with an old version of sysrepod 0.7.8. 

Questions:
 1. Is this behavior still the same on the newer sysrepod version?
 2. Is there a way for sysrepod to keep that empty container instance without purging it from the store?

Thank!

**Comment by michalvasko** [comment]
1. Yes, the behavior is the same. However, it is not exactly the one you describe.
2. Yes, it keeps it by default.

To explain, for all YANG-related work *libyang* is used, so this is strictly up to that. *libyang* actually always has NP containers created but they do not show when printing the data (unless you specify some flags). So it really depends on what you want to do exactly.
