### ISSUE TITLE
edit-config with operation="delete" failed in master branch

### ISSUE THREAD

**Issue by ankit7gup** [sysrepo/sysrepo#2297]
Hi Michal,

 I am using the netopeer-cli's edit-config operation with input xml having **operation="delete"**. In netopeer server logs, I get the below errors.

_[INF]: SR: Published event "rpc" "/ietf-netconf:edit-config" with ID 2 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 2 priority 0 (remaining 1 subscribers).
[INF]: NP: edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
netopeer2-server: /home/ankit/sysrepo/src/edit_diff.c:746: sr_diff_add_attrs: Assertion `sr_ly_is_userord(diff_node)' failed._
 

I can see some similar issue mentioned and fix available for devel branch with commit "ac9de6e ". Can you please confirm if the issue is same? If yes, What commits I need to take over master branch for this to work.
I tried cherry-pick only this commit over master, but after resolving conflicts it didn't worked and got compilation errors.

Please suggest. Thanks!

Regards,
Ankit

**Comment by michalvasko** [comment]
Please pull the current `master`, it is the new release that I am in the process of finishing (but the code is final). Then you do not have to cherry-pick anything.

**Comment by ankit7gup** [comment]
Thanks Michal!

**Comment by ankit7gup** [comment]
Hi Michal, 
Taken the latest pull for libyang, libnetconf2, sysrepo and netopeer2. On starting the netopeer-server getting core generated. Attaching the log file for the same.

[logs.txt](https://github.com/sysrepo/sysrepo/files/5886632/logs.txt)

**Comment by michalvasko** [comment]
Okay, that is quite interesting but I would still first make sure your SHM is simply not corrupted from running previous *sysrepo* version. Please run `make shm_clean` or even better `make sr_clean` (then you will have to install *netopeer2* again) and try executing the server again.

**Comment by ankit7gup** [comment]
I have tried the above mentioned steps as well, but still the output is same. 


[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
netopeer2-server: /home/ankit/sysrepo/src/shm_ext.c:298: sr_shmext_print: Assertion `items[i].size == ((items[i].size) + ((~(items[i].size) + 1) & ((sizeof(void *)) - 1)))' failed.
Aborted (core dumped)

**Comment by michalvasko** [comment]
Fair enough. What platform are you on exactly? Is it 32b or 64b?

**Comment by ankit7gup** [comment]
It is 64 bit centos.

**Comment by michalvasko** [comment]
Okay, I would like to avoid having to install this distribution in VM, so I will ask you to provide some more output with some code changes.

Please change `SR_SHM_WASTED_MAX_MEM` (`common.h.in:167`) to `0`, recompile, and reinstall *sysrepo*. Then run `netopeer2-server -d -c SYSREPO` and post the output here.

**Comment by ankit7gup** [comment]
Tried the changes, same error; Attaching logs.
[logs_new.txt](https://github.com/sysrepo/sysrepo/files/5893168/logs_new.txt)

**Comment by michalvasko** [comment]
Okay, it seems that did not help. So, please pull the current *sysrepo* `devel` (you can discard those changes), run `make shm_clean`, and try again. Paste the output here (it should crash again but hopefully print something useful before).

Also, I am sure the previous version works fine, there were major changes in the SHM structures, which cause this problem. But please, help us fix this problem instead of reverting to the old version.

**Comment by ankit7gup** [comment]
Please find the netopeer-server logs attached for sysrepo from devel branch.

[logs_new.txt](https://github.com/sysrepo/sysrepo/files/5893437/logs_new.txt)

**Comment by michalvasko** [comment]
Okay, please pull the latest *sysrepo* `devel`, run `make shm_clean`, and try again.

**Comment by ankit7gup** [comment]
It worked this time with devel changes. Logs attached.
Thanks for the immediate fix.
[logs_new.txt](https://github.com/sysrepo/sysrepo/files/5894014/logs_new.txt)

**Comment by michalvasko** [comment]
Great, thanks for testing it. In the release target I think it am quite sure it would have worked anyway (if the assert was simply ignored) but definitely better this way. It was about memory alignment.

**Comment by ankit7gup** [comment]
Hi Michal, 
Continuing with the latest sysrepo/netopeer2 tests, I am facing a weird issue, Using the same set of yang modules and xml configuration for edit-config as used in previous versions, I am getting below error in netopeer-cli.

> edit-config --target running --config=data.xml --defop replace
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  Callback event "rpc" with ID 1 processing timed out.

I tried adding rpc-timeout as well, still same error. However same config works fine for the older version. Attaching netopeer-server logs for the reference.

[server_logs.txt](https://github.com/sysrepo/sysrepo/files/5902655/server_logs.txt)

Please let me know, if I am doing something wrong or else something needs to be fixed. Thanks for the help!

**Comment by michalvasko** [comment]
Yes, there were certain changes but I did not want to change the API so there are some useless parameters. One of the is `wait` for `sr_apply_changes()` because now the call always waits for complete event processing, `SR_EV_DONE` including. My guess is that you were using `0` (and still are, except it is ignored) for this parameter before. The logs show that while the event timeout elapsed, later the event did finish successfully, so the only problem seems to be a short timeout. Try specifying some higher one for *netopeer2-server*, the `-t` parameter.

**Comment by ankit7gup** [comment]
It worked by adding timeout in server. Thanks!

**Comment by ankit7gup** [comment]
Hi Michal,

Now the server is working fine and accepting edit-config successfully.
But now coming to the original question. Giving configuration with operation="delete" is still failing.

At netopeer-server getting below errors:

[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" "/ietf-netconf:edit-config" with ID 2 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 2 priority 0 (remaining 1 subscribers).
[INF]: NP: edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
netopeer2-server: /home/ankit/sysrepo/src/edit_diff.c:745: sr_diff_add_attrs: Assertion `sr_ly_is_userord(diff_node)' failed.
Aborted (core dumped)

Regards,
Ankit

**Comment by michalvasko** [comment]
Okay, can you please provide the necessary YANG modules, data, and steps to reproduce it? I will also be able to add it to the tests then.

**Comment by ankit7gup** [comment]
Sharing the following:
1. yang modules
2.  input xml files
3.  sequence of loading modules and features enabled
4. commands used in netopeer-cli

[github_2297.zip](https://github.com/sysrepo/sysrepo/files/5903815/github_2297.zip)

**Comment by michalvasko** [comment]
Okay, should work now.

**Comment by ankit7gup** [comment]
Thanks Michal! Will check and update.

**Comment by ankit7gup** [comment]
Yes it worked now, with the fixes. Thanks for the prompt response and fixes!
