### ISSUE TITLE
Only error params are returned during configuration is possible?

### ISSUE THREAD

**Issue by myonlystarWang** [sysrepo/sysrepo#2299]
Hi michal,
     I have a question.Consider the following YANG model:

```
module bm{
    namespace "urn:com:params:xml:ns:yang:bm";
	prefix bm;
	description
		"bm yang module";
	
	revision 2020-12-30 {
		description
		    "initial create";
	}

	typedef my-decimal {
         type decimal64 {
             fraction-digits 16;
         }
     }
 
	container a{
		config true;
		
		leaf b{
			type uint16 {
				range "1..1000";
			}	
		}
		
		leaf c{
			type uint16 {
				range "1..1000";
			}
		}			
		
		leaf d {
			type my-decimal ;		
		}
		
		list e{
			key "f";
							
			leaf f{
				type uint8;
			}		
			
			leaf g{
				type uint32;
			}	
		}	//list e
	} //container a
} //module bm
```
I use the _NETCONF_ client for data configuration of the device which deployed _netopeer2_ and _sysrepo_.For example the json data as following:
```
{
  "bm:a": {
    "bm:b": "100",
    "bm:c": "100",
    "bm:d": "0.4",
    "bm:e": [
      {
        "bm:f": "1",
        "bm:g": "1000"
      }
    ]
  }
}
```
What I want to ask is if the device fails to execute one of the parameters(for example leaf **d** ) while performing the configuration,can only return failure in _sysrepo_ callback and will ?And all those successful configurations must be rolled back(for example leaf **b c** had been configured successfully).
Is there a way to return only misconfigured parameters to _sysrepo_ and also notified to _NETCONF_ client?

BR,
wang

**Comment by michalvasko** [comment]
What is want is something between `continue-on-error` and `rollback-on-error`, nothing like that is supported. An edit is treated as a transaction, either it succeeds or not.

**Comment by myonlystarWang** [comment]
Okay, I get it.
`Continuing the error` is not good for data consistency, So I understand that the application should still `rollback-on-error` and data reconfiguration is performed after client decision analysis will be better.

**Comment by michalvasko** [comment]
*sysrepo* should be quite helpful with all of this. What you need to do is handle both `SR_EV_CHANGE` and `SR_EV_ABORT` events in your callbacks. You can generally just apply the changes in both cases because `SR_EV_ABORT` event has reversed changes compared to `SR_EV_CHANGE`, so by applying them you roll them back.

**Comment by myonlystarWang** [comment]
Great, I did forget about the SR_EV_ABORT event, which can be used for rolling back.
I'll test that later.
Thanks very much,michal.

**Comment by myonlystarWang** [comment]
Hi michal,
     I tried to roll the configuration parameters back by using the `SR_EV_ABORT `event, but it failed.
     I used my own app and the application_example demo，the result is the same.
      I try two input param of `SR_SUBSCR `as below, but I can not recieve the abort message and rollback param.
```
sr_module_change_subscribe(session, mod_name, xpath, module_change_cb, NULL, 0, SR_SUBSCR_DEFAULT, &subscription);
sr_module_change_subscribe(session, mod_name, xpath, module_change_cb, NULL, 0, SR_SUBSCR_ENABLED, &subscription);
```
Did I make a mistake?Please help me at your convenience. Thank you.

BR,
wang

**Comment by michalvasko** [comment]
There do not have to be 2 apps but there must be at least 2 subscriptions. It is the obvious consequence of the bold note in the [docs](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__change__subs__api.html#ggaf5289764c79d867bab642997c23b355aa6a7bc850ab09aeb7385a0e10f2391d3f).

**Comment by myonlystarWang** [comment]
Hi michal,
    Thanks for the refer link.But there is only one subscription in my own app ,which calls the `sr_module_change_subscribe` interface and distributes the configuration to other applications,It's like a network management agent.
    So when my netconf client send the latest configuration to netopeer2-server and the applications return config error,how could my own app rollback the configuration data? Should I run a new daemon which call the same subscription ?

**Comment by michalvasko** [comment]
Look at it another way. Let's say your callback is applying the configuration on 10 devices and it fails on the 5th one. You would then get the abort event that is telling you to revert all the changes, for all the 10 devices. That is obviously wrong. So, abort event is generated **only for callbacks that succeeded**. Because then the full change should be reverted and the mentioned problem is not present.

It makes no sense for a single callback because in those cases you can perform a rollback on your own, having the information what parts exactly were applied (and should be reverted) and what were not (which should just be ignored).

**Comment by myonlystarWang** [comment]
OK, I see what you mean.That should be correct.
I will perform a rollback on my own app when callback error occurred,by using two configuration structures to reverse.
Thank you for this meaningful suggestions, michal!
