### ISSUE TITLE
sr_event_notif_send_tree() invoking state cbs for notification after subscription for t/rx-array-carriers-state-change

### ISSUE THREAD

**Issue by sandhyak88** [sysrepo/sysrepo#2300]
https://github.com/visiontrail/pyang_parser/blob/0c1382971ebeec22ab8b338a8e179fe9d71c9ecf/oran_yang/RUSpecificModels/Operations/o-ran-uplane-conf.tree#L199 

We are trying to get notification for rx-array-carriers-state-change and tx-array-carriers-state-change. We are using sr_event_notif_send_tree() which is called from a thread(thread invoked from sr_plugin_init_cb) for that.

We also tried to create node with lyd_new_path , lyd_new for rx-array-carriers and lyd_new_leaf for name and state(state is a leafref)(context,session are created newly for this thread).

Notifications are coming correctly but only after invoking all the state cbs from sr_oper_get_items_subscribe() when we try to schedule notification(strange).

Any idea on why state cbs are called when notification is invoked with a leafref?

**Comment by jktjkt** [comment]
The documentation for [`sr_event_notif_send_tree`](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__notif__subs__api.html#gab7a7f76598e9525785d97b25b5311fb8) says that the notifications are validated against the operational tree. If parts of the operational tree are supplied on demand (such as via [`sr_oper_get_items_subscribe`](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__oper__subs__api.html#ga2915a5b53a6495ca246c44f7aae58ed5)), then it means that your callbacks will be invoked when you're sending your notification.
