### ISSUE TITLE
Running without PTHREAD_PROCESS_SHARED?

### ISSUE THREAD

**Issue by frenym2021** [sysrepo/sysrepo#2301]
Investigating to use sysrepo on a NetBSD system together with netopeer to get netconf. However this old BSD where pthreds lack support for process shared cond/mutex. 

Save rewriting pthread library to support process shared mutexes, any hints on how this is used by sysrepo? Is it part of core functionality or is it some specific functionality that depend on the inter-process mutex/cond?

**Comment by michalvasko** [comment]
It seems that this feature was included already in POSIX.1-2001, so your system must really be old. *sysrepo* will not work without this feature, almost all the process synchronization is implemented using standard mutexes and conditions with this flag.
