### ISSUE TITLE
Python bindings and unsubscribe - still enabled?

### ISSUE THREAD

**Issue by esend7881** [sysrepo/sysrepo#2307]
#### Link to example code that still references unsubscribe:
https://github.com/sysrepo/sysrepo/blob/458634640501ae272692ad5ceb8085d33f38ae91/bindings/python/examples/python_application_changes_example.py#L129

#### Syslog
```.log
Feb  2 13:58:25 rmbn sysrepo_ws: subscribe.unsubscribe()
Feb  2 13:58:25 rmbn sysrepo_ws: File "/usr/lib64/python3.6/site-packages/sysrepo.py", line 2958, in <lambda>
Feb  2 13:58:25 rmbn sysrepo_ws: __getattr__ = lambda self, name: _swig_getattr(self, Subscribe, name)
Feb  2 13:58:25 rmbn sysrepo_ws: File "/usr/lib64/python3.6/site-packages/sysrepo.py", line 80, in _swig_getattr
Feb  2 13:58:25 rmbn sysrepo_ws: raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
Feb  2 13:58:25 rmbn sysrepo_ws: AttributeError: 'Subscribe' object has no attribute 'unsubscribe'
```

#### My code:

```.python
def fire_up_sysrepo_loop(module_name):
    try:
        conn = sr.Connection(sr.SR_CONN_DEFAULT)
        sess = sr.Session(conn)
        subscribe = sr.Subscribe(sess)
        logging.info("Starting subscribe loop for module: %s", module_name)
        subscribe.module_change_subscribe(module_name, rmbn_change_cb, None)
        sr.global_loop()
        logging.info("Sysrepo loop exit requested, exiting.")
        subscribe.unsubscribe() #<-- This line fails
        sess.session_stop()
        logging.info("Sysrepo Session Stopped Properly")
    except Exception:
        logging.error(traceback.format_exc())
```

Using sysrepo 1.4.104

**Comment by michalvasko** [comment]
Okay, I believe these calls can simply be removed and the C++ destructor will be used. Neither `session_stop()` should be needed but it can be called with no harm.

**Comment by esend7881** [comment]
> Okay, I believe these calls can simply be removed and the C++ destructor will be used. Neither `session_stop()` should be needed but it can be called with no harm.

Thanks for the info. It could be worth keeping the unsubscribe function in there but marking it deprecated with a log statement (not actually doing any work though), so that legacy code doesn't break.
