### ISSUE TITLE
netopeer2 : make install failed [ Shared memory version mismatch (2, expected 5), remove the SHM to fix.]

### ISSUE THREAD

**Issue by biranchi1186** [sysrepo/sysrepo#2308]
Hi,
While doing make install I am facing shared memory version mismatch error like I mentioned in title. 

Please suggest what I have missed or need to do to resolve this.

Steps followed:
          1. Already downloaded and installed libssh, libyang, libnetconf2, sysrepo as per guidelines provided.
          2. For netopeer2, Have done "cmake", "make" and "make install"
          3. During "make install" I am facing this shared memory version mismatch error/
        
Detailed log :
=============
Install the project...
-- Install configuration: "debug"
-- Up-to-date: /usr/local/share/yang/modules/netopeer2
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-tcp-client@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-tcp-common@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-truststore@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-crypto-types@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-tls-common@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf@2013-09-29.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf-server@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/iana-crypt-hash@2014-08-06.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-tcp-server@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf-acm@2018-02-14.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf-nmda@2019-01-07.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-ssh-server@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-keystore@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf-monitoring@2010-10-04.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-x509-cert-to-name@2014-12-10.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-ssh-common@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-datastores@2017-08-17.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/nc-notifications@2008-07-14.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-tls-server@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/notifications@2008-07-14.yang
-- Installing: /usr/local/bin/netopeer2-server
-- Set runtime path of "/usr/local/bin/netopeer2-server" to ""
-- Installing missing sysrepo modules...
mesg: ttyname failed: Inappropriate ioctl for device
[ERR]: Shared memory version mismatch (2, expected 5), remove the SHM to fix.
sysrepoctl error: Failed to connect (Operation not supported)
[ERR]: Shared memory version mismatch (2, expected 5), remove the SHM to fix.
sysrepoctl error: Failed to connect (Operation not supported)
CMake Error at cmake_install.cmake:81 (message):
   scripts/setup.sh failed: 1

Makefile:73: recipe for target 'install' failed

=============

**Comment by michalvasko** [comment]
This happens if you are updating *sysrepo* and there were some changes in the shared memory structures, there is no upgrade procedure implemented (would be mostly wasted effort). The simplest way to fix, is reboot your machine. The fastest to run `make shm_clean`.

**Comment by biranchi1186** [comment]
Thank you.. 
My problem is fixed.
