### ISSUE TITLE
Failed to resolve identityref issue coming while sending notification

### ISSUE THREAD

**Issue by Neeraj0019** [sysrepo/sysrepo#2309]
Hi,
As part of o-ran-performance-management yang model we have leafref element pointing to" /hw:hardware/hw:component/hw:class".

list epe-measurement-result {
      key "object-unit-id";
      config false;
      leaf object-unit-id {
        type leafref {
          path "/hw:hardware/hw:component/hw:class";
        }

        description
          "the hardware component type is used for the object-unit-id for the
           EPE measurements. For example, the object-unit-id will be set to
           or-hw:O-RAN-RADIO if the measurement applies to the complete O-RU
           self-contained sub-system.

           Other hardware-classes include: or-hw:O-RU-POWER-AMPLIFIER,
           ianahw:power-supply, ianahw:fan, ianahw:cpu";
      }

And we have o-ran-hardware yang model augmenting ietf-hardware model with adding new class as O-RAN-RADIO.

When we wre trying to fill the object-unit-id leafref in o-ran-performance-management it fails with below error.

[ERR]: Failed to resolve identityref "o-ran-hw:O-RAN-RADIO". (path: /o-ran-performance-man                                             agement:object-unit-id)
[ERR]: Missing required element "object-unit-id" in "epe-measurement-result". (path: /o-ra                                             n-performance-management:measurement-result-stats/epe-stats/epe-measurement-result)
[ERR]: Notification validation failed.

Can you please let me know how to properly set this leafreaf value?

Br,
Neeraj

**Comment by michalvasko** [comment]
I assume `o-ran-hw` is a prefix of a module. *libyang* does not know how to interpret this prefix, it does not have to be unique. Instead, it expects module name because that must be unique.

**Comment by Neeraj0019** [comment]
Hi,
we have tried with o-ran-hardware:O-RAN-RADIO also. but gets below error:
[ERR]: Leafref "/ietf-hardware:hardware/ietf-hardware:component/ietf-hardware:class" of value "o-ran-hardware:O-RAN-RADIO" points to a non-existing leaf. (path: /o-ran-performance-management:measurement-result-stats/epe-stats/epe-measurement-result[object-unit-id='o-ran-hardware:O-RAN-RADIO']/object-unit-id)
[ERR]: Notification validation failed.

Br,
Neeraj

**Comment by Neeraj0019** [comment]
Hi,
Found one ticket where its mentioned that we should not use leafref in notifications. Is this still valid and not supported?

https://github.com/sysrepo/sysrepo/issues/1650

Br,
Neeraj

**Comment by Neeraj0019** [comment]
Hi Michalvasko ,
Find one similar issue and seems its the same issue which i am facing, but document reference given is not accessible now.

https://github.com/CESNET/netopeer2/issues/661

The leafref data is available in startup and running datastore. How to make this data available as part of operational datastore also?

Currently we use sr_oper_get_items_subscribe(session, HW_MODULE_NAME, HW_STATE_XP, hw_state_cb, NULL, SR_SUBSCR_CTX_REUSE, &hwsubscription) call and return only state data, rest all data(including leafref) is available in sysrepo.

Br,
Neeraj

**Comment by michalvasko** [comment]
So till I got to your issue, you almost found a solution. Look [here](https://netopeer.liberouter.org/doc/sysrepo/master/html/index.html#oper_ds) for a way of getting your `running` data to `operational`, the first method.

**Comment by Neeraj0019** [comment]
Hi Michalvasko,
Looks like we are still facing same issue. I will try to explain what i have tried and what i am trying to achieve.

1. We have o-ran-hardware yang model which augments ietf-hardware yang model by adding one more enum value for one of the leaf parameter(class) defined in ietf-hardware with value O-RAN-RADIO. And its stored as below in startup and running datastore.
<hardware xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware">
  <component>
    <name>O-RU</name>
    **<class xmlns:o-ran-hw="urn:o-ran:hardware:1.0">o-ran-hw:O-RAN-RADIO</class**>

2. As class is config data, it was not coming in operational datastore by default, so i have used SR_SUBSCR_OPER_MERGE option while using callback "sr_oper_get_items_subscribe" for ietf-hardware yang models plugin implementation.
3. After using SR_SUBSCR_OPER_MERGE option i can see that class parameter visible in operational data store, verified using below command:
> get-data --datastore operational --filter-xpath "/ietf-hardware:*"
DATA
<hardware xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware">
  <component>
    <name>O-RU</name>
    <class xmlns:o-ran-hw="urn:o-ran:hardware:1.0">o-ran-hw:O-RAN-RADIO</class>

4. Now we have o-ran-performance-management yang model which imports ietf-hardware yang model and have a leafref as part of Notification as:
list epe-measurement-result {
key "object-unit-id";
config false;
leaf object-unit-id {
type leafref {
path "/hw:hardware/hw:component/hw:class";
}

5. But when we are preparing the notification we get below error:
[ERR]: Failed to resolve identityref "o-ran-hw:O-RAN-RADIO". (path: /o-ran-perfo                                                                                                             rmance-management:object-unit-id)
[ERR]: Missing required element "object-unit-id" in "epe-measurement-result". (p                                                                                                             ath: /o-ran-performance-management:measurement-result-stats/epe-stats/epe-measur                                                                                                             ement-result)
[ERR]: Notification validation failed.

In the first error line not sure why path says "/o-ran-performance-management:object-unit-id " as we are trying to fill the leafref at the path shown in next line.

6. if we try to use leafref to other leaf(other then class) of ietf-hardware (Ex: name shown in step 1 and 3)  notification works.

So not getting why using class as leaf ref fails.

Also as suggested by you earlier if we try to use model name in class value(o-ran-hardware:O-RAN-Radio instead of o-ran-hw:O-RAN-RADIO), we get below error while adding data for ietf-hardware in startup datastore.

[ERR]: unlink() failed (Permission denied).
sysrepocfg error: libyang: Invalid value "o-ran-hardware:O-RAN-RADIO" in "class" element.
sysrepocfg error: Data parsing failed


Br,
Neeraj

**Comment by michalvasko** [comment]
> ERR]: unlink() failed (Permission denied).
sysrepocfg error: libyang: Invalid value "o-ran-hardware:O-RAN-RADIO" in "class" element.
sysrepocfg error: Data parsing failed

This I do not understand at all (why is the error mentioning `class` element, my suggestion was to use it for `object-unit-id`).

Other than that I am not sure I can help without reproducing it (which seems would take considerable time so I would avoid that, too, if possible). If you are sure the target node is in the operational datastore (simple `sysrepocfg -X -d operational -m o-ran-hardware` should be enough to make sure of this) then please post the exact command (with the exact input) you are using to send the notification, with its full output (using `-v3` for either `sysrepocfg` or `netopeer2-server`, whichever you are using).

**Comment by Neeraj0019** [comment]
Hi,

We tried now with object-unit-id as o-ran-hardware:O-RAN-RADIO + data available in operational datastore and seems things are working now and we are able to receive notification as shown below:

`<measurement-result-stats xmlns="urn:o-ran:performance-management:1.0">
  <epe-stats>
    <start-time>2021-02-05T16:10:00.049337Z</start-time>
    <end-time>2021-02-05T16:15:00.049337Z</end-time>
    <epe-measurement-result>
      <object-unit-id xmlns:o-ran-hw="urn:o-ran:hardware:1.0">o-ran-hw:O-RAN-RADIO</object-unit-id>
      <min>8.0</min>
      <max>7.0</max>
      <average>8.0</average>
    </epe-measurement-result>
  </epe-stats>
</measurement-result-stats>`

Just for understanding purpose i have below doubts:

1.  ietf-hardware data has class value using prefix as o-ran-hw:O-RAN-RADIO, but we are giving object-unit-id as o-ran-hardware:O-RAN-RADIO, how does the validation succeeds now but not earlier? Even in notification we have value of object-unit-id coming as o-ran-hw:O-RAN-RADIO and not as o-ran-hardware:O-RAN-RADIO which we give during notification preparation. 

2. As o-ran-hardware augments ietf-hardware, i am not sure if o-ran-hardware will have any data on its own.

`sysrepocfg -X -d operational -m o-ran-hardware
[ERR]: No data in module "o-ran-hardware".
sysrepocfg error: Getting data failed (Invalid argument)`

But ietf-hardware shows proper o/p.

`<hardware xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware">
  <component>
    <name>O-RU</name>
    <class xmlns:o-ran-hw="urn:o-ran:hardware:1.0">o-ran-hw:O-RAN-RADIO</class>
    <parent-rel-pos>0</parent-rel-pos>`

Br,
Neeraj

**Comment by michalvasko** [comment]
1. That is why I asked you to mention exactly how you are preparing the notification, which would still be helpful. Because you must look at it this way, in the XML format you see prefix `o-ran-hw`, which then defined as XML namespace `urn:o-ran:hardware:1.0`. So, it is unambiguous and it is precisely specified to what namespace/module the prefixed value belongs, this works for any XML input. However, if you try to send a notification with `sr_event_notif_send()` and define one `sr_val_t` value as `o-ran-hw:O-RAN-RADIO`, what exactly is `o-ran-hw` supposed to reference, where is a binding of this prefix to a specific module/namespace? There is none, it is limited strictly to the XML format.

   Every YANG module is uniquely identifier by its namespace or name. So you could, theoretically use either of those instead. However, since module names are generally much shorter than namespaces, we opted for the name. Note that similar problem occurs with `sr_event_notif_send_tree()`, when creating the notification data tree, if you used that one. But, you could create this tree by simply parsing an XML file, in which case you could use an XML prefix, if correctly defined in the XML input.

2. Fair enough, it was just a suggestion without me knowing the exact hierarchy of your modules, `ietf-hardware` is the right module name to use.

**Comment by Neeraj0019** [comment]
Hi,
Thanks a lot for the help. One last clarification of the operational data.

When i use SR_SUBSCR_OPER_MERGE option while using callback "sr_oper_get_items_subscribe" i get all the config data (which is added to startup and running db using sysrepocfg edit command) and state data(which is filled inside the plugin).

Additionally we get some leafs which has default value defined in the yang model but not explicitly returned by the plugin or stored in sysrepo DB by using sysrepocfg commands. Is this expected behaviour? and is this valid for both config and state data which has default value defined in yang model for example as shown below?

` leaf dying-gasp-support {
      type boolean;
      config false;
      default false;
      description
        "indicates whether the O-RU supports the dying gasp
        capability";
    }`

And we don't have any way to exclude them?

Br,
Neeraj

**Comment by michalvasko** [comment]
> Is this expected behaviour?

Yes, that is how default values are defined.

> and is this valid for both config and state data which has default value defined

No, state data defaults should not be added implicitly.

> And we don't have any way to exclude them?

You do but I do not think you can use `SR_SUBSCR_OPER_MERGE` in this case. You would have to provide the configuration data, too, just without the default values. That way you explicitly let *sysrepo* know that they are actually not "in-use" and should not be reported in the operational datastore.

**Comment by Neeraj0019** [comment]
Hi,
But i see that state data having default is added implicitly to both operational and running datastore when i used SR_SUBSCR_OPER_MERGE option.

We have below leaf "dying-gasp-support" in o-ran-hardware which comes automatically in operational now.

`leaf dying-gasp-support { type boolean; config false; default false; description "indicates whether the O-RU supports the dying gasp capability"; }`

Br,
Neeraj

**Comment by michalvasko** [comment]
I am not sure what the problem is, I tried to reproduce it in a test but it worked just as expected. Please specify exactly what the scenario is or better yet, modify the test so that it reproduces the problem.

**Comment by Neeraj0019** [comment]
Hi,
Based on your last comment i was checking behaviour of state data which has default values defined in the yang model. 

Below are the steps:
Note: plugin doesn't fill anything explicitly for state data(dying-gasp-support) having default value.
1. We have o-ran-hardware model which augments ietf-hardware model and defines below state date with default value as false:
`leaf dying-gasp-support { type boolean; config false; default false; description "indicates whether the O-RU supports the dying gasp capability"; }`

2. When plugin uses sr_oper_get_items_subscribe cb with only SR_SUBSCR_CTX_REUSE flag, operational data doesn't include augmented state data((dying-gasp-support) leaf) having default value.
3. When plugin uses sr_oper_get_items_subscribe cb with flag as "SR_SUBSCR_OPER_MERGE|SR_SUBSCR_CTX_REUSE" , operational data includes state data((dying-gasp-support) leaf) with default as false.

So wanted to check if this is valid? or state data should not come to operational datastore even with MERGE option if plugin is not filling any value for the leaf.

Br,
Neeraj

**Comment by michalvasko** [comment]
I have forgotten you are using the previous *sysrepo* release, which may easily be the problem. So, please switch to `devel` branch (for all the projects) and try to reproduce it then. Otherwise there is a possibility it was fixed already and I just do not have the time to risk that.

**Comment by Neeraj0019** [comment]
Hi,
So you mean that libsysrepo v1.4.70 (SO v5.5.12) is old and we need to try with devel branch?

Br,
Neeraj

**Comment by michalvasko** [comment]
Yes, that is what I am saying. At the very least, you should be using the latest release if you expect any support, which is 1.4.104. But you can use `devel` instead, there will be another release soon because the last one has some serious bugs. They you can use it again as a stable version.

**Comment by Neeraj0019** [comment]
Ok, thanks a lot for your support. I will close this ticket.
