### ISSUE TITLE
Segmentation fault in sr_errinfo_new

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2310]
Hi,

When there is an **sr_get_items()** call with invalid xpath (for example "name()//."), there can be a segfault in **sr_errinfo_new()**, invoked by **SR_ERRINFO_MEM** macro.
The value of idx will be -1, and the expression `(*err_info)->err[idx].message` will result in invalid memory access.

Backtrace:
```
<log_cb invoked with invalid message pointer>
sr_errinfo_new (err_info=err_info@entry=0x7fffeccab140, err_code=err_code@entry=SR_ERR_NOMEM, xpath=xpath@entry=0x0, 
    format=format@entry=0x0) at /opt/dev/sysrepo/src/log.c:204
sr_modinfo_get_filter (mod_info=mod_info@entry=0x7fffeccab1c0, xpath=xpath@entry=0x7fffeccabe30 "name()//.", 
    session=session@entry=0x6130000504c0, result=result@entry=0x7fffeccab1a8) at /opt/dev/sysrepo/src/modinfo.c:2236
sr_get_items (session=0x6130000504c0, xpath=0x7fffeccabe30 "name()//.", timeout_ms=30000, opts=<optimized out>, 
    values=0x7fffeccab480, value_cnt=0x7fffeccab440) at /opt/dev/sysrepo/src/sysrepo.c:1388
```

sysrepo version: 1.4.108
libyang version: 1.0.216

Thanks!

**Comment by michalvasko** [comment]
Good catch, there were several weird things in the code to fix. Should work now and print the intended (although perhaps a bit cryptic) *libyang* message.

**Comment by awesomenode** [comment]
It returns an error as expected on the latest version.
Thanks!
