### ISSUE TITLE
How to configure netopeer2-server for connection

### ISSUE THREAD

**Issue by biranchi1186** [sysrepo/sysrepo#2313]
In my VM, netopeer2-server is working well as  expected for SSH connection.
If I want to go ahead for TLS connection what must I have to configure for netopeer2-server .
As I can see the default port for TLS is 6513.
 
Can somebody guide my how to make netopeer2-server to listen on TLS port ?

**Comment by michalvasko** [comment]
Look into [example configuration](https://github.com/CESNET/netopeer2/tree/master/example_configuration) for all the module configuration needed to connect using TLS. You should then be able to adjust it accordingly. For explanation of all the values look at the YANG modules.
