### ISSUE TITLE
Multi-session access to sysrepo questions.

### ISSUE THREAD

**Issue by rydy** [sysrepo/sysrepo#2315]
Hi Michal,
    For centos, I used the latest devel branch  for testing, I found with multiple sessions accessing the sysrepo.
    When a session is accessing the operational sysrepo database (simulation: data was obtained successfully after 10s block), as follows:
```
[root@centos7_8 baicells-gps-management-accCard]# sysrepocfg --export --format xml --datastore operational --module baicells-gps-management-accCard --timeout 30 -v 3
[INF]: Scheduled changes not applied because of other existing connections.
[INF]: Connection 421 created.
[INF]: Session 432 (user "root", CID 421) created.
[INF]: Published event "operational" "/baicells-gps-management-accCard:gps" with ID 18.

block 10s 

[INF]: Event "operational" with ID 18 succeeded.
<gps xmlns="urn:baicells:baicells-gps-management-accCard:1.0">
  <software-version>1.0</software-version>
  <hardware-version>2.0</hardware-version>
</gps>
[root@centos7_8 baicells-gps-management-accCard]#
```
A timeout error occurred when the previous session was blocked and another session was created for access(edit/rpc/get).  as follows:
```
[root@centos7_8 baicells-carrier-management]# sysrepocfg --export --format xml --datastore running --module baicells-carrier-management  -v 3
[INF]: Scheduled changes not applied because of other existing connections.
[INF]: Connection 427 created.
[INF]: Session 438 (user "root", CID 427) created.
<carriers xmlns="urn:baicells:baicells-carrier-management:1.0">
  <array-antennas>
    <id>0</id>
    <array-carriers>
      <id>0</id>
      <standard>NR</standard>
      <subframe-assignment>SA1</subframe-assignment>
      <special-subframe-pattern>SPP7</special-subframe-pattern>
      <frequency-center>3630000</frequency-center>
      <bandwidth>1000</bandwidth>
      <power>10</power>
    </array-carriers>
  </array-antennas>
  <array-antennas>
    <id>1</id>
    <array-carriers>
      <id>0</id>
      <standard>NR</standard>
      <subframe-assignment>SA1</subframe-assignment>
      <special-subframe-pattern>SPP7</special-subframe-pattern>
      <frequency-center>3630000</frequency-center>
      <bandwidth>1000</bandwidth>
      <power>10</power>
    </array-carriers>
  </array-antennas>
</carriers>
[ERR]: Waiting on a conditional variable failed (sr_shmmod_lock: Connection timed out).
[ERR]: Module "baicells-gps-management-accCard" is being used by session 437 (NC SID 0).
```
I think there is a problem with multi-session access to sysrepo, which should not be blocked and should be concurrent.

Best regards,
Reid

**Comment by michalvasko** [comment]
Okay, I have reproduced the issue and the problem is not with getting data (as you can see, the data were printed) but with calling `sr_disconnect` at the end of *sysrepocfg*. So, it actually works correctly (it should be safe to just ignore this timeout error) and it should be fixed (as a side-effect) once a planned change is implemented so there is nothing to fix right now. If you want to avoid this timeout, do not use *sysrepocfg* but instead some client of your own that will not create and terminate a connection for every command.

**Comment by rydy** [comment]
I am now using two Netopeer2-CLI clients to simulate the blocking problem with this behavior. I do not understand why it is blocking.

The netopeer2-cli_1 log
```
# netopeer2-cli
connect --host=172.19.1.172
Interactive SSH Authentication
Type your password:
Password: 
> 
> 
> 
> get-data --datastore operational --filter-xpath /baicells-gps-management-accCard:gps/* --rpc-timeout 20

block 10s

DATA
<gps xmlns="urn:baicells:baicells-gps-management-accCard:1.0">
  <software-version>1.0</software-version>
  <hardware-version>2.0</hardware-version>
</gps>

> 
```

The netopeer2-cli_2 log
```
# netopeer2-cli
connect --host=172.19.1.172
Interactive SSH Authentication
Type your password:
Password: 
> 
> 
> get-data --datastore operational --filter-xpath /baicells-carrier-management:carriers/* --rpc-timeout 20

//Wait for another client block to complete

DATA
<carriers xmlns="urn:baicells:baicells-carrier-management:1.0">
  <array-antennas>
    <id>0</id>
    <array-carriers>
      <id>0</id>
      <state>DISABLED</state>
      <standard>NR</standard>
      <direction>UL</direction>
      <subframe-assignment>SA1</subframe-assignment>
      <special-subframe-pattern>SPP7</special-subframe-pattern>
      <frequency-center>263000</frequency-center>
      <bandwidth>10000</bandwidth>
      <power>10</power>
    </array-carriers>
    <array-carriers>
      <id>1</id>
      <state>DISABLED</state>
      <standard>NR</standard>
      <direction>UL</direction>
      <subframe-assignment>SA1</subframe-assignment>
      <special-subframe-pattern>SPP7</special-subframe-pattern>
      <frequency-center>263001</frequency-center>
      <bandwidth>10001</bandwidth>
      <power>11</power>
    </array-carriers>
  </array-antennas>
</carriers>

> 
```

Shouldn't the netopeer2-cli_2 block waiting for another client(netopeer2-cli_1) to do something?

**Comment by michalvasko** [comment]
In this case the problem will be the `get-data` RPC. In *sysrepo* architecture the execution of a single RPC is serialized. It makes sense in general but yes, there are some RPCs such as this that could be executed concurrently, it is not supported currently.

**Comment by rydy** [comment]
> In this case the problem will be the `get-data` RPC. In _sysrepo_ architecture the execution of a single RPC is serialized. It makes sense in general but yes, there are some RPCs such as this that could be executed concurrently, it is not supported currently.

Does only ‘get-data' not support concurrency?

**Comment by michalvasko** [comment]
No, like I wrote, none of the *netopeer2* RPCs support concurrency (meaning executing a particular RPC concurrently, different RPCs should work fine) because they are limited by *sysrepo* architecture, which does not allow it.

**Comment by rydy** [comment]
> No, like I wrote, none of the _netopeer2_ RPCs support concurrency (meaning executing a particular RPC concurrently, different RPCs should work fine) because they are limited by _sysrepo_ architecture, which does not allow it.

I got it, thanks.
