### ISSUE TITLE
Failed to commit (Malformed message).

### ISSUE THREAD

**Issue by gurugod** [sysrepo/sysrepo#2316]
hi folks ,
I am facing one issue in sysrepo.
```
Feb: 9: 7:40:01:446621|debug|25613|sysrepo/sysrepoDbOperation.cpp|757|writeOperDataXml():xpath :/mavenir-stats:stats/intervals/interval[start-time='2021-02-09 07:40:00']/end-time
Feb: 9: 7:40:01:446690|debug|25613|sysrepo/sysrepoDbOperation.cpp|830|writeOperDataXml():string :2021-02-09 07:45:00
Feb: 9: 7:40:01:447072|warn|25613|sysrepo/sysrepoDbOperation.cpp|853|writeOperDataXml():Failed to commit (Malformed message).

Feb: 9: 7:40:01:447144|warn|25613|sysrepo/sysrepoDbOperation.cpp|855|writeOperDataXml():Failed to set value[2021-02-09 07:45:00] for xpath[/mavenir-stats:stats/intervals/interval[start-time='2021-02-09 07:40:00']/end-time]
```
I am using valid xml content to write into sysrepo.
sometimes it is writing successfuly, sometimes it is not writing and throwing malformed error .
sysrepo versions -  sysrepo-0.7.4.
netopeer version - Netopeer2-0.5-r1
libnetconf version - libnetconf2-0.11-r1.

can you please help me to identify the the signature "malformed message" ?.

Thanks in advance,
Gaurav J.

**Comment by michalvasko** [comment]
Sorry, you are using an extremely old *sysrepo* version so I cannot help you.

**Comment by gurugod** [comment]
hi michalvasko,
   Thank you very much for quick reply 
  I can completely understand your concern . Can you just give me any lead  on malformed message message ?
  What could be the reason , we are upgrading sysrepo in background.
 

Thanks,
Gaurav J.

**Comment by michalvasko** [comment]
It means that the message is not valid according to NETCONF, I cannot tell you more.

**Comment by gurugod** [comment]
thank you michal. we try to resolve.
