### ISSUE TITLE
sysrepo Assertion in /sysrepo/src/shm_ext.c:298

### ISSUE THREAD

**Issue by gcp85163** [sysrepo/sysrepo#2317]
sysrepo version: v1.4.104

Linux env:
Linux c7077d889ad7 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Log:
netopeer2-server: /home/sysrepo/src/shm_ext.c:298: sr_shmext_print: Assertion `items[i].size == ((items[i].size) + ((~(items[i].size) + 1) & ((sizeof(void *)) - 1)))' failed.

analysis：
Should be  byte alignment problem.
items[i].size is 4, SR_SHM_SIZE(items[i].size) is 8. 
use define ATOMIC_T uint32_t. (Change to uint64_t, this issue is gone).

**Comment by michalvasko** [comment]
Should be fixed already in `devel`.

**Comment by gcp85163** [comment]
Could you tell me what's your plan in next release time？

Thank you

**Comment by michalvasko** [comment]
The original plan was to make a new bugfix release soon after the last one but there are still some things left to fix. Should not take more than a couple of weeks.
