### ISSUE TITLE
Segmentation fault in sr_rwunlock

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2318]
Hi,

I have segmentation faults on a PowerPC based system in **sr_rwunlock()**:
 
```
sr_rwunlock()                  common.c:3241
sr_shmsub_oper_notify()        shm_sub.c:1374
sr_xpath_oper_data_get()       modinfo.c:586
sr_module_oper_data_update()   modinfo.c:754
sr_modinfo_add_modules()       modinfo.c:1899
sr_get_item()
```
 
According to my investigation the segmentation fault is caused by remapping **sub_shm** to another address in **sr_shmsub_oper_notify()**.
This works on x86_64, but remapping a locked mutex (which is shared and robust) will cause segmentation fault on PowerPC when we try to unlock it.
 
sysrepo version: 1.4.109
libyang version: 1.0.218

Thanks!

**Comment by jktjkt** [comment]
Reported for a 32-bit ARM at #2312.

**Comment by michalvasko** [comment]
Yes, please it again now, the problem was most likely the same.
