### ISSUE TITLE
Loading of yang module failed

### ISSUE THREAD

**Issue by ankit7gup** [sysrepo/sysrepo#2320]
HI Michal,
I am loading a yang module for o-ran. While loading I am getting below errors, even though pyang is able to validate the module.

##############################################
sysrepoctl -i o-ran-usermgmt.yang -a -v 4
[INF]: Applying scheduled changes.
[INF]: No scheduled changes.
[INF]: Connection 89 created.
[INF]: Module "o-ran-usermgmt" scheduled for installation.
[INF]: Applying scheduled changes.
[WRN]: Node "stream" type is changing the "require-instance" property, which is discouraged.
[WRN]: Must condition "user/enabled='true'" not satisfied. (path: /o-ran-usermgmt:users)
[WRN]: At least one account needs to be enabled. (path: /o-ran-usermgmt:users)
[WRN]: Failed to apply some changes, leaving all changes scheduled.
[ERR]: Applying scheduled changes failed.
sysrepoctl error: Failed to apply changes (Operation failed)

#####################Pyang output############################

pyang -f tree o-ran-usermgmt.yang
module: o-ran-usermgmt
+--rw users
+--rw user* [name]
+--rw name nacm:user-name-type
+--rw account-type? enumeration
+--rw password? password-type
+--rw enabled? boolean

rpcs:
+---x chg-password
+---w input
| +---w currentPassword password-type
| +---w newPassword password-type
| +---w newPasswordConfirm password-type
+--ro output
+--ro status status-output
+--ro status-message? string
#############################################################

Attaching the module for reference.

[o-ran-usermgmt.txt](https://github.com/sysrepo/sysrepo/files/5970181/o-ran-usermgmt.txt)

 
Another failure I am getting for the attached file, same is being validated by pyang as well.

[o-ran-uplane-conf.txt](https://github.com/sysrepo/sysrepo/files/5970183/o-ran-uplane-conf.txt)

pyang o-ran-uplane-conf.yang -p ../radio/:../operations/:../interfaces/:../../common_models/interfaces/

sysrepoctl -i o-ran-uplane-conf.yang -e EAXC-GAIN-CORRECTION -e TX-REFERENCE-LEVEL -a -v3 -s ../../imported_models/.
[INF]: Applying scheduled changes.
[INF]: No scheduled changes.
[INF]: Connection 153 created.
[WRN]: Schema node "ietf-hardware:class" not found (derived-from-or-self(deref(current())/../ietf-hardware:class) with context node "/ietf-interfaces:interfaces/interface/o-ran-interfaces:port-reference/o-ran-interfaces:port-name".
[WRN]: Argument #1 of xpath_derived_from_or_self not a node-set as expected.
[WRN]: Previous warning generated by XPath function "derived-from-or-self(deref(current())/../ietf-hardware:class, 'iana-hardware:port')".
[WRN]: Missing status in deprecated subtree (/o-ran-uplane-conf:{grouping}[uplane-conf-group]/tx-array-carriers/lte-tdd-frame/subframe-assignment), inheriting.
[WRN]: Missing status in deprecated subtree (/o-ran-uplane-conf:{grouping}[uplane-conf-group]/tx-array-carriers/lte-tdd-frame/special-subframe-pattern), inheriting.
[ERR]: Leafref is not conditional based on "CONFIGURABLE-TDD-PATTERN-SUPPORTED" feature as its target. (path: /o-ran-uplane-conf:user-plane-configuration/low-level-tx-endpoints/configurable-tdd-pattern-supported)
[ERR]: Leafref is not conditional based on "PRACH-STATIC-CONFIGURATION-SUPPORTED" feature as its target. (path: /o-ran-uplane-conf:user-plane-configuration/low-level-rx-endpoints/static-prach-configuration)
[ERR]: Leafref is not conditional based on "SRS-STATIC-CONFIGURATION-SUPPORTED" feature as its target. (path: /o-ran-uplane-conf:user-plane-configuration/low-level-rx-endpoints/static-srs-configuration)
[ERR]: Leafref is not conditional based on "CONFIGURABLE-TDD-PATTERN-SUPPORTED" feature as its target. (path: /o-ran-uplane-conf:user-plane-configuration/low-level-rx-endpoints/configurable-tdd-pattern-supported)
[ERR]: Module "o-ran-uplane-conf" parsing failed.
sysrepoctl error: Failed to install module "o-ran-uplane-conf.yang" (libyang error)

P.S. Yang module we cannot modify.

Kindly suggest.

Regards,
Ankit

**Comment by michalvasko** [comment]
The first problem with `o-ran-usermgmt` is not a YANG module problem but a YANG data one, *sysrepo* refuses to install the module because it would make the datastore invalid. You must set some initial valid data for it before it can be installed (using `sysrepocfg -W <data-file> -m o-ran-usermgmt`, for example).

As for the second problem, I cannot verify whether the error is valid or it is a bug unless you provide the module with all its imports so that I can try to load it with *libyang*. But I would guess the error is valid, passing *pyang* validation does not guarantee a valid YANG module.

**Comment by ankit7gup** [comment]
Hi Michal, Regarding the first yang module's error, yes It works post applying some default data via the mentioned command. 
Regarding the second file's issue, sharing all the yang modules being used. Kindly help with the way to proceed with that.

[yang_load.zip](https://github.com/sysrepo/sysrepo/files/5994897/yang_load.zip)

Thanks!

**Comment by michalvasko** [comment]
I have only looked at the first error, which seems valid to me and should include all the information for anyone to check it. I can only reference the text that the YANG module breaks making it invalid, last paragraph in the [leafref](https://tools.ietf.org/html/rfc7950#section-9.9) section.

**Comment by ankit7gup** [comment]
Thanks Michal, I have added the leafref's if-feature condition and it worked.

**Comment by chendrashekarp** [comment]
> Thanks Michal, I have added the leafref's if-feature condition and it worked.
Hi ankit7gup ,
can you please explain or attach what modification you done exactly

thanks in advance

**Comment by ankit7gup** [comment]
Hi Chandrashekhar, 
I had enabled the if-feature while loading the yang module using command "sysrepoctl -i <module_name> -e <feature name> -a"
If  any condition is present for a leafref, same has to be there in leafref and leaf which it is referring to..
So, Added the if-feature to respective place.

**Comment by chendrashekarp** [comment]
can you please share the updates yang model
