### ISSUE TITLE
Assertion "Invalid arguments" when calling ly_ctx_get_module()

### ISSUE THREAD

**Issue by pfeige** [sysrepo/sysrepo#2324]
When checking data dependencies in [sr_shmmod_instid_deps_data()](https://github.com/sysrepo/sysrepo/blob/db1bf9126330af138b33855e2277ecaf28770e23/src/shm_mod.c#L241) I've got an "Invalid arguments" assertion in ly_ctx_get_module() because the actual parameter mod_name is NULL, This mod_name is extracted from the value of a leaf which is assumed to be an instance-id which is given as xpath value starting with a module prefix. In my case the leaf is of type union and besides of an instance-id it can be also an object identifier, a UUID or simply a string. So, it seems to be not always possible to detect a module name. As workaround I checked whether mod_name is NULL and if so a continue is done. May be you see a better idea how to handle this.

**Comment by michalvasko** [comment]
Right, a proper solution would probably be to check whether the value is really an instance-identifier. By inserting the following code after the line `237` (after the assert):
```C
if (((struct lyd_node_leaf_list *)set->set.d[j])->value_type != LY_TYPE_INST) {
    continue;
}
```
Could you please test that it works for you?

**Comment by pfeige** [comment]
This fix works fine for me. Thanks!

**Comment by michalvasko** [comment]
Great, committed.
