### ISSUE TITLE
error Opening "/etc/sysrepo/sr_evpipe28" for writing failed (No such device or address).

### ISSUE THREAD

**Issue by shaista-dev** [sysrepo/sysrepo#2325]
On running env, when can this file get deleted on its own

**Comment by michalvasko** [comment]
It should not get deleted, this error is most likely caused by a bug. Can you write the steps to reproduce the problem? With any required YANG modules/data, of course.

**Comment by shaista-dev** [comment]
error Opening "/etc/sysrepo/sr_evpipe28" is observed in logs after codenomicon netconf suite had been executed. No specific YANG modules/data is installed or handled.

**Comment by michalvasko** [comment]
I do not think I can help since I have absolutely no idea what you are talking about. I have already written what I need from you.

**Comment by shaista-dev** [comment]
Test procedure:

After starting codenomicon netconf security suite, as part of INTEROPERABILITY check, initially in hello.close module, within first 3 secs itself , this error opening /etc/sysrepo/sr_evpipe28 is observed. 

Test env:
As part of supervision plugin, after call home procedure , we initiate supervision notification towards ODU, which failed as mentioned in below logs and at ODU side, watchdog.reset happens after timeout, sending of this also failed, as socket between test env and ODU for disconnected.

 logs:

2021-02-11 18:21:06,583 INFO success: netopeer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-02-11 18:21:08,969 DEBG 'sysrepoplugind' stdout output:
[INF]: Published event "notif" "o-ran-supervision" with ID 301 priority 0 for 2 subscribers.
[ERR]: Opening "/etc/sysrepo/sr_evpipe28" for writing failed (No such device or address).
[ERR]: plugin: SUPERVISION: notification generation failed: System function call failed.

ODU  logs:

user-rpc --content watchdog-reset.xml
DATA
next-update-at xmlns="urn:o-ran:supervision:1.0"2021-02-11T18:21:08Z/next-update-at

nc ERROR: Session 2: SSH channel poll error (Socket error: disconnected).


Regarding codenomicon netconf secutity suite more details can we found below-
https://github.com/Codenomicon
Synopsys Ltd. - Download Arena (https://www.codenomicon.com/arena/)
NETCONF Test Suite 2.4.0

**Comment by michalvasko** [comment]
I am sorry but I do not think we will be able to try and reproduce this anytime soon. It is too complex and would take too much time. However, an issue with similar error #2354 was recently fixed so it may have been related.
