### ISSUE TITLE
More subtrees match error

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2328]
Hi,

I encountered similar error printouts when tried to get data from running datastore with _sr_get_item()_ call:
`More subtrees match "/ietf-interfaces:interfaces/interface[name="eth0"]/description".`

According to the source code it is possible when `mod_cache->data` contains data for **ietf-interfaces** multiple times, because
the shared memory file (**sr_ietf-interfaces.running**) contained no duplicates, and _SR_CONN_CACHE_RUNNING_ is enabled on the connection.

I have found a race condition that can cause similar duplicated data in the cache.
When _sr_modcache_module_running_update()_ function is called concurrently on multiple threads (with _read_locked_=0),
the following part will run without holding the mod_cache lock:

```
    /* find the module in the cache */
    for (i = 0; i < mod_cache->mod_count; ++i) {
        if (mod->ly_mod == mod_cache->mods[i].ly_mod) {
            break;
        }
    }
```

When the module is not found in the cache, they will all add it to `mod_cache->data`.

sysrepo version: 1.4.113

Thanks!

**Comment by michalvasko** [comment]
Should no longer happen although the whole cache could use some improvements.
