### ISSUE TITLE
an "U" is displayed on flags location during executing "sysrepoctl -l" after updating a yang file 

### ISSUE THREAD

**Issue by itercheng** [sysrepo/sysrepo#2331]
Dear sysrepo expert:

firstly I update a yang file by using "sysrepoctl -U ****.yang" command,  the result can be executed successfully, i see  'U ' and 'I'  flags when checking whether this yang is already valid by using "sysrepoctl -l". but "Revision" field still be previous  time that also means this yang is not updated and invalid. do you know  why occur this condition?

Module Name                    | Revision              | Flags      | Owner     | Permissions | Submodules | Features
-----------------------------------------------------------------------------------------------------
_3gpp_common_ep_rp       | 2018-07-31        | I    U        | root:root | 600             |            |

**Comment by michalvasko** [comment]
I do not know but `sysrepoctl` (for example) can tell you, just use `-v3`, so `sysrepoctl -l -v3` should work.

**Comment by itercheng** [comment]
okay. thanks
