### ISSUE TITLE
Module "ietf-netconf" in another revision already implemented.

### ISSUE THREAD

**Issue by azcomgit** [sysrepo/sysrepo#2334]
I'm trying to update ietf-netconf module, after the following operation the sysrepo repository is in error. 

- sudo sysrepoctl -i ../../models/ietf-netconf-acm@2018-02-14.yang
- sudo sysrepoctl -U ../../models/ietf-netconf@2013-09-29.yang
- sudo sysrepoctl -U ../../models/ietf-netconf@2011-06-01.yang

Now the sysrepoctl response always with 
```
[ERR]: Module "ietf-netconf" in another revision already implemented.
[ERR]: Module "ietf-netconf-with-defaults" parsing failed.
sysrepoctl error: Failed to connect (libyang error)
```
for any operation.

The only two ways I've found to restore the repositories are:

- restore the sysrepo.startup file with previous one
- reset the repository with the "make uninstall_with_repo"

**Comment by michalvasko** [comment]
Okay, this was allowed because I though it does no harm. I thought wrong.
