### ISSUE TITLE
sr_rpc_subscribe_tree api fails with "Invalid argument" error when try to give x-path as "/notifications:create-subscription"

### ISSUE THREAD

**Issue by Neeraj0019** [sysrepo/sysrepo#2335]
Hi,
I am trying to test few cases with latest released sysrepo version(1.4.104) but one of the use case which was working in older sysrepo seems to be failing.

We have a plugin written for o-ran-supervision module in c++ which subscribes for another modules rpc as below.

X-path used is "/notifications:create-subscription"

 rc = sr_rpc_subscribe_tree(session, xpath, create_subscription_cb, NULL, 0, SR_SUBSCR_DEFAULT, &supSubscrn);

i see below error in sysrepo plugind logs:

[ERR]: RPC subscription for "/notifications:create-subscription" with priority 0                                                                                                                      already exists.
[ERR]: plugin: SUPERVISION: Supervision plugin initialization failed: Invalid ar                                                                                                                     gument.
[ERR]: plugin: Plugin initialization failed (Invalid argument).

Is their anything wrong in this?

Attaching notifications module schema here:

> get-schema  -m notifications
MODULE
module notifications {
  namespace "urn:ietf:params:xml:ns:netconf:notification:1.0";
  prefix ncEvent;

  import ietf-yang-types {
    prefix yang;
  }

  organization
    "IETF NETCONF WG";
  contact
    "netconf@ops.ietf.org";
  description
    "Conversion of the 'ncEvent' XSD in the
     NETCONF Notifications RFC.";
  reference
    "RFC 5277.";

  revision 2008-07-14 {
    description
      "RFC 5277 version.";
  }

  typedef streamNameType {
    type string;
    description
      "The name of an event stream.";
  }

  rpc create-subscription {
    description
      "The command to create a notification subscription. It
       takes as argument the name of the notification stream
       and filter. Both of those options limit the content of
       the subscription. In addition, there are two time-related
       parameters, startTime and stopTime, which can be used to
       select the time interval of interest to the notification
       replay feature.";
    input {
      leaf stream {
        type streamNameType;
        default "NETCONF";
        description
          "An optional parameter that indicates which stream of events
           is of interest. If not present, then events in the default
           NETCONF stream will be sent.";
      }

      anyxml filter {
        description
          "An optional parameter that indicates which subset of all
           possible events is of interest. The format of this
           parameter is the same as that of the filter parameter
           in the NETCONF protocol operations. If not present,
           all events not precluded by other parameters will
           be sent.";
      }

      leaf startTime {
        type yang:date-and-time;
        description
          "A parameter used to trigger the replay feature and
           indicates that the replay should start at the time
           specified. If start time is not present, this is not a
           replay subscription.";
      }

      leaf stopTime {
        type yang:date-and-time;
        description
          "An optional parameter used with the optional replay
           feature to indicate the newest notifications of
           interest. If stop time is not present, the notifications
           will continue until the subscription is terminated.
           Must be used with startTime.";
      }
    }
  }
}

Br,
Neeraj

**Comment by Neeraj0019** [comment]
Hi,
seems changing the priority during subscribe works.

rc = sr_rpc_subscribe_tree(session, xpath, create_subscription_cb, NULL, 1, SR_SUBSCR_DEFAULT, &supSubscrn);

Is there any change in this behaviour between 1.4.104 and 1.4.70 ?

Br.
Neeraj

**Comment by michalvasko** [comment]
Yes, this was a bugfix mostly, having 2 RPC subscriptions with the same priority was not working even before (in some cases) but was incorrectly allowed.
