### ISSUE TITLE
User's application may lost data at startup.

### ISSUE THREAD

**Issue by ryanking8215** [sysrepo/sysrepo#2336]
It appears in sysrepo version '1.4.66'. Now the source code in mater is changed, I don't know whether it appears or not.

I used sysrepo v1.4.66 about half year ago. I found sometimes my application's data  is not same with the data in sysrepo datastore after application starts up.  

Here is my sence:
1.  'callhome' feature is enabled in netopeer2-server, once the netopeer2-server connects to the controller, controller will send data to it, if application is subscribed, it will got callback, otherwise the data will be saved to sysrepo directly. 
2. When the application startup, it tries to load data from sysrepo and subscribe the data change. (Subscribe with  `SR_SUBSCR_ENABLED` flag.)
3. But these two behavior are in different services(netopeer2-server and my application.). It is totally asynchronous.

I read the source code of sysrepo v1.4.66. I think I find the lock issue. Here is the sample of code:

subscribe function:  sr_module_change_subscribe() sysrepo.c: 3337
```
    /* call the callback with the current running configuration so that it is properly applied */
    if ((session->ds == SR_DS_RUNNING) && (opts & SR_SUBSCR_ENABLED)) {
        /* do not hold write lock here, would block callback from calling API functions (we are only reading running data anyway) */
        if ((err_info = sr_module_change_subscribe_running_enable(session, ly_mod, xpath, callback, private_data, opts))) {
            return sr_api_ret(session, err_info);
        }
    }

    /* SHM LOCK (writing into subscriptions) */
    if ((err_info = sr_shmmain_lock_remap(conn, SR_LOCK_WRITE, 1, __func__))) {
        return sr_api_ret(session, err_info);
    }

    /* add subscription into structure and create separate specific SHM segment */
    if ((err_info = sr_sub_change_add(session, module_name, xpath, callback, private_data, priority, sub_opts,
            *subscription))) {
        goto error_unlock_unsub_unmod;
    }

    /* SHM UNLOCK */
    sr_shmmain_unlock(conn, SR_LOCK_WRITE, 1, __func__);
```

code in `sr_module_change_subscribe_running_enable`
```
    /* MODULES READ LOCK */
    if ((err_info = sr_shmmod_modinfo_rdlock(&mod_info, 0, session->sid))) {
        sr_modinfo_free(&mod_info);
        return err_info;
    }

 // load data here
   .... 

    /* MODULES UNLOCK */
    sr_shmmod_modinfo_unlock(&mod_info, 0);
```

code about 'sr_apply_changes'
```
    /* SHM LOCK (reading subscriptions) */
    if ((err_info = sr_shmmain_lock_remap(session->conn, SR_LOCK_READ, 0, __func__))) {
        return sr_api_ret(session, err_info);
    }

    /* MODULES READ LOCK (but setting flag for guaranteed later upgrade success) */
    if ((err_info = sr_shmmod_modinfo_rdlock(&mod_info, 1, session->sid))) {
        goto cleanup_mods_unlock;
    }

   // apply changes here
   ....

       sr_shmmod_modinfo_unlock(&mod_info, 1);
       sr_shmmain_unlock(session->conn, SR_LOCK_READ, 0, __func__);
```

Let's simplify the code:
subscribe logic:
```
modinfo_lock()
// load data
modinfo_unlock()

// * If other thread exec apply_change() here, application will lost data, because it has been loaded data but not subscribe yet. *

shm_lock()
// subscribe 
shm_unlock()
```

apply_change logic:
```
shm_lock()
modinfo_lock()
// apply change stuff
modinfo_unlock()
shm_unlock()
```

So there is chance that application lost data here.

It is easy to fix that put `shm_lock` before `modinfo_lock` in subscribe logic:
```
shm_lock()
modinfo_lock()
// load data
modinfo_unlock()
shm_unlock()
```

This is my solution, is it correct?

Then I checkout the source code in master branch, I find `sr_shmmain_lock_remap` is removed, I wonder whether it causes data lost or not. In my opinion, It will lost the data in my sense.

**Comment by michalvasko** [comment]
The locks were completely rewritten so I cannot help you with any changes of the version you are using. But the use-case is valid even in the current version and the problem could easily occur so I fixed it, with a test included.

**Comment by ryanking8215** [comment]
I ported the unit test to v1.4.66, and modified the sysrepo.c as I mentioned above. I confirmed that it passes the unit test if modified and failed with original code.
