### ISSUE TITLE
sr_delete_item() does no delete list

### ISSUE THREAD

**Issue by iljatab** [sysrepo/sysrepo#2339]
$ yanglint --version
yanglint SO 1.10.1
$ sysrepoctl --version
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.100 (SO v5.6.16)
$ netopeer2-server -V
netopeer2-server 1.1.52

Hi Michal,

It looks like there is possible regression, AFAIR this worked in our application tests earlier.

Say, we have openconfig-interfaces.yang model.

We have a "dummy9" interface with some IPv4 addresses configured on it:

```
> get-config --filter-xpath=/openconfig-interfaces:interfaces/interface[name='dummy9']/subinterfaces/subinterface[index='0']/openconfig-if-ip:ipv4/addresses --source running
DATA
<interfaces xmlns="http://openconfig.net/yang/interfaces">
  <interface>
    <name>dummy9</name>
    <subinterfaces>
      <subinterface>
        <index>0</index>
        <ipv4 xmlns="http://openconfig.net/yang/interfaces/ip">
          <addresses>
            <address>
              <ip>192.168.1.1</ip>
              <config>
                <ip>192.168.1.1</ip>
                <prefix-length>24</prefix-length>
              </config>
            </address>
            <address>
              <ip>192.168.3.1</ip>
              <config>
                <ip>192.168.3.1</ip>
                <prefix-length>24</prefix-length>
              </config>
            </address>
          </addresses>
        </ipv4>
      </subinterface>
    </subinterfaces>
  </interface>
</interfaces>
```

Then, from application, we do `sr_delete_item(sess, xpath, opts);`, where xpath == "/openconfig-interfaces:interfaces/interface[name='dummy9']/subinterfaces/subinterface[index='0']/openconfig-if-ip:ipv4/addresses" and opts == 0.

There's no error returned but nothing is deleted, the datastore content remains as is.
I definitely remember this working :-(
Could you please check?

BRGDS,
Ilja.

**Comment by iljatab** [comment]
Looks like we figured it out finally.

Our sequence is:

```
# delete whole container xpath = /openconfig-interfaces:interfaces/interface[name='dummy9']/subinterfaces/subinterface[index='0']/openconfig-if-ip:ipv4/addresses
sr_delete_item(sess, xpath, SR_EDIT_DEFAULT);

# configure another IP address under xpath
sr_set_item(sess, xpath + "/address/ip/..., val1, SR_EDIT_DEFAULT);
sr_set_item(sess, xpath + "/address/ip/..., val2, SR_EDIT_DEFAULT);
```
It looks like sr_set_item() kind of "recovers" the previously deleted datastore content, therefore the net result is like sr_delete_item() didn't happen at all.

The solution is to use SR_EDIT_ISOLATE for datastore edits.

So I will close the ticket, sorry for confusion.

However, it would be better to get an error in such case, instead of silently discarding some edits.

Ilja.

**Comment by michalvasko** [comment]
> Looks like we figured it out finally.

Great.

> However, it would be better to get an error in such case, instead of silently discarding some edits.

Other people would argue otherwise. They are not silently, but merged. How else would you merge a delete and then create? The later operations take precedence.

**Comment by iljatab** [comment]
Thanks for reply!

With sr_delete_item(() we delete the container ".../addresses", together with ".../addresses/address" list of IP addresses.
Say, in our example above we deleted list elements 192.168.1.1 and 192.168.3.1.
With sr_set_item(() we add completely different ".../addresses/address" list elements, IP address(es), say 192.168.100.1.
And in the resulting data set we have all three addresses - old two and the new one.
Hmmm... to me it doesn't look like an intuitive merge :-)

Ilja.

**Comment by iljatab** [comment]
Thanks!
