### ISSUE TITLE
 Resolving XPath expression failed error 

### ISSUE THREAD

**Issue by rajkumar1028** [sysrepo/sysrepo#2343]
hello,
I'm using **sr_get_items** to get data from **o-ran-interfaces** xml,but that data is a **leafref** to **ietf-interfaces**

**the snippet code is:**
```C
rc = sr_get_items(session, "/ietf-interfaces:interfaces/interface/interfaces:port-reference/port-number/..//.",0, 0, &trans.object_id,&trans.val_count2);
         if (rc != SR_ERR_OK) {
                goto cleanup;
        }
```
**and the error im getting is :**
```
[ERR]: Resolving XPath expression "/ietf-interfaces:interfaces/interface/interfaces:port-reference/port-number/..//." failed. (path: /ietf-interfaces:interfaces)
[ERR]: SR: Resolving XPath expression "/ietf-interfaces:interfaces/interface/interfaces:port-reference/port-number/..//." failed.
```
**The xml is:**
![image](https://user-images.githubusercontent.com/67410119/109289103-b9cc8200-784b-11eb-98a2-deb18ee124e3.png)

please help me out, i just need the correct path i tried different paths but i'm either getting **segmentation core dumped** or the **resolving xpath expression failed** error

**Comment by michalvasko** [comment]
Firstly, please provide the XPaths that are causing segmentation faults, that should never happen so I would like to fix it. If some YANG modules/data are needed to reproduce it, please provide those, too.

Regarding the issue, the message could definitely be better as it does not include any details but my guess is a problem with the `interfaces` prefix. Is the module with namespace `urn:o-ran:interfaces:1.0` really called `interfaces`?

**Comment by rajkumar1028** [comment]
> Firstly, please provide the XPaths that are causing segmentation faults, that should never happen so I would like to fix it. If some YANG modules/data are needed to reproduce it, please provide those, too.
> 
> Regarding the issue, the message could definitely be better as it does not include any details but my guess is a problem with the `interfaces` prefix. Is the module with namespace `urn:o-ran:interfaces:1.0` really called `interfaces`?

Hello michal,

1)Firstly we are using **o-ran-performance-management yang** module

2)**Is the module with namespace `urn:o-ran:interfaces:1.0` really called `interfaces`?** yeah, it is called `interfaces` only and its working.

3)After seeing your comment, I tried with this path **/ietf-interfaces:interfaces/interface/o-ran-interfaces:port-reference/port-number/..//.**
 Its actually **fetching the value without any error,** but **its fetching port-name value** instead of **port number**

**The snippet:**
rc = sr_get_items(session, "/ietf-interfaces:interfaces/interface/o-ran-interfaces:port-reference/port-number/..//.",0, 0, &trans.object_id,&trans.val_count2);
        VRB("THE TRANSCEIVER OBJECT ID IS %s",trans.object_unit_id);
        if (rc != SR_ERR_OK) {
                goto cleanup;
        }
**The output is:**
![image](https://user-images.githubusercontent.com/67410119/109380993-aaa60c80-78fd-11eb-80af-c7945ae2ebf7.png)
**The o-ran-interfaces xml file pic:**
![image](https://user-images.githubusercontent.com/67410119/109381192-cbbb2d00-78fe-11eb-8f9e-9f3a327da428.png)

**I also tried giving paths like:** 
1)**/ietf-interfaces:interfaces/interface/o-ran-interfaces:port-reference/port-name/port-number/..//.**

2)**/ietf-interfaces:interfaces/interface/o-ran-interfaces:port-reference/o-ran-interfaces:port-number/..//.**

its giving the same port name as the output.

I have attached the performance management yang model and the o-ran-interfaces file below
[original pm yang file.txt](https://github.com/sysrepo/sysrepo/files/6053855/original.pm.yang.file.txt)
[o-ran-interfaces.txt](https://github.com/sysrepo/sysrepo/files/6053922/o-ran-interfaces.txt)

**Comment by rajkumar1028** [comment]
Hello Michal,
Thanks to your insights i have figure out the xpath now i am getting the correct values,so I'm closing this issue
Thank you,
