### ISSUE TITLE
enabling feature in imported module

### ISSUE THREAD

**Issue by gabilm** [sysrepo/sysrepo#2344]
Hi.

I'm testing the sysrepo/sysrepo-netopeer2:latest docker image.
I want to enable a feature in the ietf-tls-common module, for example, tls-1_2 from the command line (sysrepoctl)
The ietf-tls-common is an "imported" module, not an "installed" one.

If I try:
sysrepoctl -c ietf-tls-common -e tls-1_1 -e tls-1_2 -a
I get the following message:
[ERR]: Module "ietf-tls-common" was not found in sysrepo.
sysrepoctl error: Failed to enable feature "tls-1_1" (Item not found)

I'm able to enable features in installed module, but having problems with the imported.

Is there any way to that?

Thanks and best regards, Gabi.

**Comment by michalvasko** [comment]
You cannot enable features in imported-only modules, this restriction is in YANG.

**Comment by gabilm** [comment]
Ok, I see.

Thank you for your quick response.

Then, my question is how to enable these features. I mean, I have a yang model  importing the currently installed ietf-tls-server. 
I want to upload a sample xml with the following content:

	<hello-params 
		xmlns:tlscmn="urn:ietf:params:xml:ns:yang:ietf-tls-common">
		<tls-versions>
			<tls-version>tlscmn:tls-1.1</tls-version>
			<tls-version>tlscmn:tls-1.2</tls-version>
		</tls-versions>
		<cipher-suites>
			<cipher-suite>tlscmn:dhe-rsa-with-aes-256-cbc-sha256</cipher-suite>
			<cipher-suite>tlscmn:rsa-with-aes-256-cbc-sha256</cipher-suite>
		</cipher-suites>
	</hello-params>

But, when importing I get the following text:

sysrepocfg --import=examples/client-rsa.xml -m my-module -d running
sysrepocfg error: libyang: Invalid value "tls-1.1" in "tls-version" element.
sysrepocfg error: libyang: Identity "tls-1.1" is disabled by its 0. if-feature condition.
sysrepocfg error: Data parsing failed

Sorry, probably is something obvious I can not see now.
Thanks in avance, Gabi.

**Comment by michalvasko** [comment]
You just need to install the module explicitly first, the same way you installed the other module.

**Comment by gabilm** [comment]
ok.

I get the point.

Thank you!
