### ISSUE TITLE
SYSREPO API for callhome

### ISSUE THREAD

**Issue by biranchi1186** [sysrepo/sysrepo#2345]
HI Michal,
Does SYSREPO provides any API for callhome connection.
I am currently aware that to start callhome to NETCONF clients, one way is to import ssh_callhome.xml to netopeer2 server.
CONFD also supports API like "maapi_netconf_ssh_call_home" for initiating callhome.

Does SYSREPO support something like CONFD supports.

Thanks in advance !!!

**Comment by michalvasko** [comment]
Certainly not because *sysrepo* does not even really connect to anything, it is just a local system library, so it would make no sense. There is no NETCONF support in *sysrepo*, strictly speaking. If you want to use NETCONF, you must use it with *netopeer2-server*.

**Comment by biranchi1186** [comment]
Thanks Michal for your input.
using netopeer2-server, how my application will initiate callhome connection to its client. 
Any input please.

**Comment by michalvasko** [comment]
You must simply configure it to do so. Meaning, set some data for [ietf-netconf-server](https://github.com/CESNET/netopeer2/blob/master/modules/ietf-netconf-server%402019-07-02.yang). There are many imports and grouping so to actually see the configuration structure, it is good to use `tree` output of *libyang*, for example. Also, you can simply import the example configuration that you mentioned, what exactly is the problem? It can easily be modified, of course, before importing, so you can adjust it to your use-case.
