### ISSUE TITLE
how to  set operational data 

### ISSUE THREAD

**Issue by shishirpandey29** [sysrepo/sysrepo#2346]
Hi Michal,

I am trying to update config false data "ru-instance-id" from app, but not able to see  config false data "ru-instance-id" value in get/get-data command.
```
get/get-data command output : get --filter-xpath /o-ran-operations:operational-info/declarations/ru-instance-id
DATA
```
```yang
module o-ran-operations {
grouping operational-group {
container declarations {
    config false;
    leaf ru-instance-id {
       type string;
    }
}
}
}
 container operational-info{
    description
      "a collection of operational infor for the O-RU";
    uses operational-group;
  }
```
Program  output: 
```
[root@romulus examples]# ./sr_set_item_example /o-ran-operations:operational-info/declarations/ru-instance-id 30
Application will set "/o-ran-operations:operational-info/declarations/ru-instance-id" to "30".
```
I tried with  both sr_set_item_str and lyd_new_path APIS but still did not observe config false data "ru-instance-id" in get command output.

Attached program 
[sr_set_item_example.txt](https://github.com/sysrepo/sysrepo/files/6068561/sr_set_item_example.txt)

**Comment by zfvs** [comment]
Hi,

isn't the code attached by shishirpandey29 similar to the code in oper_pull_push_example.c? Cannot sr_set_item_str function be used to set state data?

**Comment by michalvasko** [comment]
The important difference is that operational data exist only as long as the connection used for setting them exists. So the important difference is that `oper_data_push_example` does not terminate immediately but waits for user input, unlike `sr_set_item_example`. The `oper_pull_push_example` only illustrates the use of both methods and includes getting the data so it quits right away, deleting the push data.
