### ISSUE TITLE
SR_EDIT_ISOLATE and sr_discard_changes()

### ISSUE THREAD

**Issue by iljatab** [sysrepo/sysrepo#2347]
$ yanglint --version
yanglint SO 1.10.1
$ sysrepoctl --version
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.100 (SO v5.6.16)
$ netopeer2-server -V
netopeer2-server 1.1.52

Hi Michal,

We recently started to use SR_EDIT_ISOLATE and encountered some issue.
Here's the most simple scenario:

```
sr_connect(SR_CONN_CACHE_RUNNING, ...);
...
sr_session_start(..., SR_DS_RUNNING, ...);
...
sr_set_item_str(..., "/xpath/to/leaf", val, NULL, SR_EDIT_ISOLATE);
sr_apply_changes(...);
#
# sr_apply_changes() fails because the callback,
# installed by sr_module_change_subscribe(), rejects the change.
#
sr_discard_changes(...); # returns SR_ERR_OK
```

However, the invalid change for "/xpath/to/leaf" element remains "stuck" in the datastore.
Changing any other elements and doing `sr_apply_changes()` repeatedly result in the same error - our callback still "sees" the change for "/xpath/to/leaf" like if `sr_discard_changes()` was not called at all.

When not using `SR_EDIT_ISOLATE` option the exactly same code works as expected.

Did I miss something, could you please advise?

Ilja.

**Comment by michalvasko** [comment]
There are some basic tests for this and looking through the code I do not see anything that could cause this. Are you calling `sr_discard_changes()` on the session with the same datastore you tried to apply the changes on? Because it discards changes only for the current datastore.

**Comment by iljatab** [comment]
Cannot reproduce the issue anymore.
