### ISSUE TITLE
how to get the "reset-at" and "name " value in the action call back function, at application

### ISSUE THREAD

**Issue by vshaker** [sysrepo/sysrepo#2349]
Hi , 

In the example yang file given below , How do i get the value "reset-at"  and "name "in the callback function .  

Call back function prototype found in the sysrepo :
```C
static int
rpc_action_cb(sr_session_ctx_t *session, const char *op_path, const struct lyd_node *input, sr_event_t event,
        uint32_t request_id, struct lyd_node *output, void *private_data)
```
Example yang format:

```yang
module example-server-farm {
       yang-version 1.1;
       namespace "urn:example:server-farm";
       prefix "sfarm";

       import ietf-yang-types {
         prefix "yang";
       }

       list server {
         key name;
         leaf name {
           type string;
         }
         action reset {
           input {
             leaf reset-at {
               type yang:date-and-time;
               mandatory true;
              }
            }
            output {
              leaf reset-finished-at {
                type yang:date-and-time;
                mandatory true;
              }
            }
          }
        }
      }
```

**Comment by michalvasko** [comment]
Well, `reset-at` should be the node `input->child` and name should be `input->parent->child`. You get a string leaf value of a `node` with `((struct lyd_node_leaf_list *)node)->value_str`.

**Comment by vshaker** [comment]
Thank you  , it worked

**Comment by vshaker** [comment]
From const char *op_path is there a way to extract the key value of the path received

**Comment by michalvasko** [comment]
Well, you can generate it from the `struct lyd_node` using `lyd_path()` or get the values identified directly as XPaths when subscribing using `sr_rpc_subscribe()`.
