### ISSUE TITLE
"implicit" changes of the operational DS are not reported

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#2352]
Hi, it seems that changes to the `operational` DS which are done "implicitly" as a result of a modification of the `running` DS are not delivered to callbacks (`module_change_subscribe`). In other words, I only get a change for ops data that someone actively pushes into the `operational` DS, not about those which are results of a modification of `running`.

Here's how the relevant part of my model looks like:
```
module: czechlight-roadm-device
  ...
  +--rw media-channels* [channel]
  |  +--rw channel        -> /channel-plan/channel/name
  |  +--rw description?   string
  |  +--rw add!
  |  |  +--rw port     device-dependent-port-type
  |  |  +--rw (mode)
  |  |     +--:(attenuation)
  |  |     |  +--rw attenuation    czechlight-roadm-common:attenuation-type
  |  |     +--:(power)
  |  |        +--rw power    opendevice-types:optical-power-dBm
  |  +--rw drop!
  |  |  +--rw port     device-dependent-port-type
  |  |  +--rw (mode)
  |  |     +--:(attenuation)
  |  |     |  +--rw attenuation    czechlight-roadm-common:attenuation-type
  |  |     +--:(power)
  |  |        +--rw power    opendevice-types:optical-power-dBm
  |  +--ro power
  |     +--ro common-in     opendevice-types:optical-power-dBm
  |     +--ro common-out    opendevice-types:optical-power-dBm
  |     +--ro leaf-in       opendevice-types:optical-power-dBm
  |     +--ro leaf-out      opendevice-types:optical-power-dBm
  ...
```
As a user, I'm dynamically creating and removing `media-channels[channel='31.5']`. Our application listens for changes in the `running` DS, and for each `/czechlight-roadm-device:meda-channel` that is present in `running`, the code fills in `/czechlight-roadm-device:media-channels[...]/power/common-in` and `common-out` leafs. Similarly, if the corresponding `meida-channel/add` container is present, we're pushing ops data into `media-channel[...]/power/leaf-in`, etc.

Another app listens for any modification of the `operational` DS. It never gets notified when a `media-channel` gets created or removed, and there's no event when `media-channel[...]/description` gets changed. Also, I only ever get a single event like this when a `media-channel` gets provisioned **for the first time**:
```json
{
  "czechlight-roadm-device:media-channels": [
    {
      "@": {
        "sysrepo:operation": "none",
        "ietf-origin:origin": "unknown"
      },
      "channel": "31.5",
      "power": {
        "@": {
          "sysrepo:operation": "none"
        },
        "leaf-in": "-38.1",
        "@leaf-in": {
          "ietf-netconf:operation": "create"
        }
      }
    }
  ]
}
```
When the corresponding `media-channel` gets removed, I get no event, and when it then gets added back after some time, I just get an `ietf-netconf-operation: replace`, and it seems that the old data my app pushed a long time ago is actually persisted somewhere and reported via the `sysrepo:orig-value` attribute.

Is it possible to get these events?

**Comment by michalvasko** [comment]
Right, I have simply missed this use-case and it should not be difficult but I really have no time right now for this anyway and I wanted to change this feature significantly so that `edit` is being stored instead of `diff`, which would solve this problem as well. I will see what I manage first.

**Comment by jktjkt** [comment]
It seems that the pushed values are not just persisted at some "shadow" location, they have also recently started to become visible via the `operational` DS as well. As an example:

- the `running` DS contains `/czechlight-roadm-device:media-channels[channel='X']`,
- our app pushes `/czechlight-roadm-device:media-channels[channel='X']/power/common-in` into the `operational` DS,
- someone deletes `/czechlight-roadm-device:media-channels[channel='X']` from `running`
- yet the `operational` DS still reports `/czechlight-roadm-device:media-channels[channel='X']/power/common-in`.

I'm pretty sure this was not the case when I first opened this issue, but I could be wrong. Would it be possible to fix this part of the problem (the content of the `operational` that's available via the usual "get data" APIs), or do you prefer to fix this only after the libyang2 thing lands?

**Comment by jktjkt** [comment]
@michalvasko , can you please take a look and advise on why the pushed ops data are not getting auto-deleted?

**Comment by michalvasko** [comment]
I am not sure why such a change would occur, there were some fixes in these parts of code but there are also tests for this, which are passing. Note that it is not enough that some data are in `running`, they must also be in `operational` (have some subscriptions on them). Otherwise you technically created the value with all the parents in the `operational` so changing `running` does not affect it.

**Comment by gotthardp** [comment]
Hello. With the latest sysrepo I am now facing the same issue. Just as said above: *Changes to the operational DS which are done "implicitly" as a result of a modification of the running DS are not delivered to callbacks (`module_change_subscribe`). In other words, I only get a change for ops data that someone actively pushes into the operational DS, not about those which are results of a modification of running.*

Is this the intended behaviour and I should design my application around that, or is that something that may be fixed/changed, please? It would help me to get a callback anytime the operational DS changes, no matter whether directly or via the running DS.

**Comment by jktjkt** [comment]
It feels like an intended change; apparently the idea is that the app can control the contents of the `operational` DS completely, and therefore this deletion in `running` won't necessary remove stuff from `operational`. (The root cause is that the `operational` DS is implemented as an edit, and if an app pushed an edit which set a particular leaf, then removal of its parents might not cause a removal of that leaf. My words, perhaps @michalvasko has a more accurate description.) Or are you getting a situation where the data in `operational` disappear, but there's no edit event for that?

Anyway, we ended up patching our application code so that we drop these additions to `operational` whenever the `running` is updated. In our case it was not hard to do. Thehere's a significant downside that this dropping cannot be done atomically with other changes via `sr_apply_changes`, but only via `sr_discard_oper_changes`.

**Comment by gotthardp** [comment]
Data that disappear from `operational` after being removed from `running` do not trigger callbacks of `module_change_subscribe` made on the `operational` DS. The similar is true for adding new entries.

Let's assume I have `ipv4/address[ip='1.1.1.1']` in the `running` DS.
Calling (pseudocode) `sr_module_change_subscribe(RUNNING, "ipv4//*", ENABLED | DONE_ONLY, fun1)` invokes `fun1` for `ip='1.1.1.1'` and creates the `ipv4/address[ip='1.1.1.1']` entry in the `running` DS.

Calling something similar on the `operational` DS i.e. `sr_module_change_subscribe(OPERATIONAL, "ipv4//*", ENABLED | DONE_ONLY, fun2)` invokes `fun2` for `ip='1.1.1.1'` as well. So far so good.

Now, adding a new `ipv4/address[ip='2.2.2.2']` to the `running` DS does invoke `fun1`, but it does **not** invoke `fun2` although the `ip='2.2.2.2'` entry appears in the `operational` DS as well and there is a subscription to the `operational`. The question I have is whether this is a bug or a feature. (The documentation does not say that the "implicit" additions do not invoke callbacks, moreover the `ENABLED` event is sent even for the "implicit" operational data.)

Adding `ipv4/address[ip='3.3.3.3']` to the `operational` DS **does** invoke `fun2` only as, expected. No trouble there.

**Comment by michalvasko** [comment]
It is a feature, for `operational` subscriptions you get notified only about `push` oper changes ([6th paragraph](https://netopeer.liberouter.org/doc/sysrepo/master/html/subs.html#change_subs), nothing else. The complexity (read inefficiency) of detecting all the changes was not deemed to be worth it.
