### ISSUE TITLE
Question: sysrepo python bindings

### ISSUE THREAD

**Issue by igortern** [sysrepo/sysrepo#2360]
Hello,
Could you advice where the python bindings matching the latest sysrepo release are?
The Python examples in https://github.com/sysrepo/sysrepo-python don't match the examples in this repo. For example,
python_application_changes_example.py in this repo uses the following subscription sequence:
```
    # connect to sysrepo
    conn = sr.Connection(sr.SR_CONN_DEFAULT)

    # start session
    sess = sr.Session(conn)

    # subscribe for changes in running config */
    subscribe = sr.Subscribe(sess)

    subscribe.module_change_subscribe(module_name, module_change_cb, None)

```
whereas similar example in sysrepo-python repo uses 
```
        with sysrepo.SysrepoConnection() as conn:
            with conn.start_session() as sess:
                logging.info("subscribing to module changes: sysrepo-example")
                sess.subscribe_module_change("sysrepo-example", None, module_change_cb)

```
There is no 'Connection' class in sysrepo-python, SysrepoSession doesn't have a 'Subscribe' attribute, etc.

Is there some alternative repo with up-to-date Python bindings?

Thank you and Best Regards,
Igor

**Comment by michalvasko** [comment]
There are 2 Python bindings currently, the SWIG bindings in the *sysrepo* repository and then the CFFI bindings in the separate repository *sysrepo-python*. Both should be usable but the CFFI ones should be preferred because they have a more user-friendly API and the SWIG ones will be deprecated.

**Comment by igortern** [comment]
Thanks
