### ISSUE TITLE
Leafref can not be found from another module

### ISSUE THREAD

**Issue by koala027** [sysrepo/sysrepo#2363]
Hi michalvasko,

Could you please allow me to raise one question? this issue confuse me in a long time. and i try to find the solution from the sysrepo [Main doc](https://netopeer.liberouter.org/doc/sysrepo/master/html/index.html#oper_ds) page, but still failed. so thanks in advance.

backgroud:  I have three yang modules, one is named ietf-hardware, another is ietf-interfaces(o-ran-interfaces),  there is one node in o-ran-interfaces leafref  ietf-hardware's node, attached the fragment of those yang modules

**module: o-ran-interfaces
```
augment /if:interfaces/if:interface:
+ rw port-reference
|   + -- rw port-name >  -> /hw:hardware/component/name
|   + -- rw port-number ?    unit8**
```
======================================================
In startup datastore, ietf-hardware module have three components created for initialization.  named in eth0, eth1, sfp1,DGRU
o-ran-interfaces module reference two of them which named eth1, sfp1 .

when send get rpc for ietf-interfaces module, we aways encounter failed output.
**netopeer2-server[3817]: There is no leafref "/ietf-hardware:hardware/ietf-hardware:component/ietf-hardware:name" with the value "sfp1", but it is not required.
netopeer2-server[3817]: There is no leafref "/ietf-hardware:hardware/ietf-hardware:component/ietf-hardware:name" with the value "eth1", but it is not required.**

Check those two components(eth1 and sfp1) of  ietf-hardware in startup,running and operational datastore. they all exist.

```
/home/dg:505 >sudo sysrepocfg --export --datastore operational --module ietf-hardware   
<hardware xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware">
  <component>
    <name>DGRU</name>
    <software-rev>CAT_A</software-rev>
    <product-code xmlns="urn:o-ran:hardware:1.0">3DG12345AAAA</product-code>
  </component>
  <component>
    <name>sfp1</name>
    <product-code xmlns="urn:o-ran:hardware:1.0">3DG12345AAAA</product-code>
  </component>
  <component>
    <name>eth1</name>
    <product-code xmlns="urn:o-ran:hardware:1.0">3DG12345AAAA</product-code>
  </component>
</hardware>
```

I remember in other topic, you mentioned, the leafref node MUST exist in operational datastore, so it confuse me. why this referenced leaf node not found even.

attached the yang module and the datastore content for more detail. thanks a lot.

[interface&hardware.zip](https://github.com/sysrepo/sysrepo/files/6122859/interface.hardware.zip)

**Comment by michalvasko** [comment]
Like the output says, the value is not required at that moment so you should simply ignore it if the RPC was successful.

**Comment by koala027** [comment]
OK, thanks michalvasko's mention, we just ignore it.
