### ISSUE TITLE
Question on sr_oper_get_items_subscribe api.

### ISSUE THREAD

**Issue by Neeraj0019** [sysrepo/sysrepo#2366]
Hi,
We have use case where we want to return an error to the netopeer-client if client tries to get some specific container values.

The container xpath which is used in sr_oper_get_items_subscribe() is having only config data, it doesn't have any state data.

And when we try get from client, we see that the callback registered is not getting called by sysrepo.

So is it that sr_oper_get_items_subscribe() api works only for containers having at least one state data?

Br,
Neeraj

**Comment by michalvasko** [comment]
> So is it that sr_oper_get_items_subscribe() api works only for containers having at least one state data?

No, it does not have anything to do with this. Look [here](https://netopeer.liberouter.org/doc/sysrepo/master/html/subs.html#oper_subs) for reasons why the callback may not have been called. If none of them fit, please post all the relevant details of the use-case.

**Comment by Neeraj0019** [comment]
Hi Michal,
Below are the three xpath which plugin is subscribing for:

#define MPLANE_INT_STATE_XPATH_interfaces "/o-ran-mplane-int:mplane-info/m-plane-interfaces/m-plane-sub-interfaces"
#define MPLANE_INT_STATE_XPATH_searchable_vlans "/o-ran-mplane-int:mplane-info/searchable-mplane-access-vlans-info"
#define MPLANE_INT_STATE_XPATH_configured_clients "/o-ran-mplane-int:mplane-info/configured-client-info"

and subscription is also done in the same order:

        rc = sr_oper_get_items_subscribe(session, MPLANE_INT_MODULE_NAME, MPLANE_INT_STATE_XPATH_interfaces, mplane_int_state_cb_ifaces,
                                        NULL, SR_SUBSCR_DEFAULT, &mplanesubscription);

        rc = sr_oper_get_items_subscribe(session, MPLANE_INT_MODULE_NAME, MPLANE_INT_STATE_XPATH_searchable_vlans, mplane_int_state_cb_vlans,
                                        NULL, SR_SUBSCR_CTX_REUSE, &mplanesubscription);

        rc = sr_oper_get_items_subscribe(session, MPLANE_INT_MODULE_NAME, MPLANE_INT_STATE_XPATH_configured_clients, mplane_int_state_cb_clients,
                                        NULL, SR_SUBSCR_CTX_REUSE, &mplanesubscription);

        rc = sr_module_change_subscribe(session, MPLANE_INT_MODULE_NAME, NULL, mplane_config_change_cb, NULL, 0,
                                        SR_SUBSCR_CTX_REUSE, &mplanesubscription);

But only first subscription gets hit.

Below is the yang model used:

`module o-ran-mplane-int {
  yang-version 1.1;
  namespace "urn:o-ran:mplane-interfaces:1.0";
  prefix "o-ran-mplane-int";

  import ietf-inet-types {
    prefix "inet";
  }

  import ietf-interfaces {
    prefix "if";
  }

  import o-ran-interfaces {
    prefix "o-ran-int";
  }

  organization "O-RAN Alliance";

  contact
    "www.o-ran.org";

  description
    "This module defines the YANG definitions for managng the O-RAN Radio Unit
     management plane interface.

     Copyright 2019 the O-RAN Alliance.

     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS'
     AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
     IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
     ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
     LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
     CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
     SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
     INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
     CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
     ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
     POSSIBILITY OF SUCH DAMAGE.

     Redistribution and use in source and binary forms, with or without
     modification, are permitted provided that the following conditions are met:

     * Redistributions of source code must retain the above copyright notice,
     this list of conditions and the above disclaimer.
     * Redistributions in binary form must reproduce the above copyright notice,
     this list of conditions and the above disclaimer in the documentation
     and/or other materials provided with the distribution.
     * Neither the Members of the O-RAN Alliance nor the names of its
     contributors may be used to endorse or promote products derived from
     this software without specific prior written permission.";

  revision "2019-07-03" {
       description
         "version 1.1.0

         1) enabling NETCONF clients to be configured.
         2) shifting new container to correct position
         3) backward compatible changes to introduce groupings";

       reference "ORAN-WG4.M.0-v01.00";
  }

  revision "2019-02-04" {
    description
      "version 1.0.0

      1) imported model from xRAN
      2) changed namespace and reference from xran to o-ran";

    reference "ORAN-WG4.M.0-v01.00";
  }


  typedef vlan-id {
    type uint16 {
      range 1..4094;
    }
    description
      "Type definition representing a single-tagged VLAN";
  }

  // Groupings

  grouping mplane-group {
    container searchable-mplane-access-vlans-info {
      description
        "These parameters shall be stored by the equipment in reset persistant memory
        to enable it to be re-used to optimize VALN discovery procerdures.";
      leaf-list searchable-access-vlans {
        type vlan-id;
        description
          "A list of access VLANs that may be operational on the transport
          network. Can be used by the equipment to optimize its VLAN searching - for
          M-plane operations.";
      }
      container vlan-range {
        description "the range of VLAN IDs that may be configured for M-Plane";
        leaf lowest-vlan-id {
          type vlan-id;
          description
            "Value of this parameter informs equipment about lowest VID to be used
            in VLAN scan procedure";
        }
        leaf highest-vlan-id {
          type vlan-id;
          description
            "Value of this parameter informs about highest VID to be used
            in VLAN scan procedure";
        }
      }
    }

    container m-plane-interfaces {
      description "information concerning m-plane interfaces";
      list m-plane-sub-interfaces {
        key "interface-name sub-interface";
        description "list of m-plane information";
        leaf interface-name {
          type leafref {
            path "/if:interfaces/if:interface/if:name";
          }
          description "the name of the interface";
        }
        leaf sub-interface {
          type leafref {
            path "/if:interfaces/if:interface[if:name = current()/../interface-name]/o-ran-int:vlan-id";
          }
          description
            "vlans used to communicate with management plane servers.";
        }
        container client-info {
          config false;
          description
            "the NETCONF client information, discovered by DHCP or manually
             configured during installation.";
          list mplane-ipv4-info {
            key mplane-ipv4;
            description "list of IPv4 NETCONF clients";
            leaf mplane-ipv4 {
              type inet:ipv4-address;
              description "The IPv4 address of M-Plane client discovered by the O-RU
              or manually configured.";
            }
            leaf port {
              type inet:port-number;
              description
                "The call home port number discovered or manually configured.";
            }
          }
          list mplane-ipv6-info {
            key mplane-ipv6;
            description "list of IPv6 NETCONF clients";
            leaf mplane-ipv6 {
              type inet:ipv6-address;
              description "The IPv6 address of M-Plane client discovered by the O-RU
              or manually configured.";
            }
            leaf port {
              type inet:port-number;
              description
                "The call home port number discovered or manually configured.";
            }
          }
          leaf-list mplane-fqdn {
            type inet:domain-name;
            description "The discovered FQDN(s) of M-Plane client(s).";
          }
        }
      }

      container m-plane-ssh-ports {
        description "leafs for managing SSH ports";
        leaf call-home-ssh-port {
          type inet:port-number;
          default 4334;
          description "The configured call home server port number";
        }
        leaf server-ssh-port {
          type inet:port-number;
          default 830;
          description "The configured SSH server port number";
        }
      }
    }
    container configured-client-info {
      description
        "the NETCONF client information that may be configured by another
        NETCONF client. These clients are reported independently from clients
        manually configured or discovered using DHCP.";
      list mplane-ipv4-info {
        key mplane-ipv4;
        description "list of IPv4 NETCONF clients";
        leaf mplane-ipv4 {
          type inet:ipv4-address;
          description "The IPv4 address of configured M-Plane client.";
        }
        leaf port {
          type inet:port-number;
          description
            "The configured call home port number.";
        }
      }
        leaf test {
        config false;
        type string;
        description
                " Used for testing.";
        }
      list mplane-ipv6-info {
        key mplane-ipv6;
        description "list of IPv6 NETCONF clients";
        leaf mplane-ipv6 {
          type inet:ipv6-address;
          description "The IPv6 address of configured M-Plane client..";
        }
        leaf port {
          type inet:port-number;
          description
            "The configured call home port number.";
        }
      }
      leaf-list mplane-fqdn {
        type inet:domain-name;
        description "The configured FQDN(s) of M-Plane client(s).";
      }
    }
  }


  // Top Level Container

  container mplane-info {
    description "top level container for management plane information";

    uses mplane-group;
  }
}
`
below data are already stored in sysrepo startup and running DS via sysrepocfg command.

> get --filter-xpath /o-ran-mplane-int:mplane-info/*
DATA
<mplane-info xmlns="urn:o-ran:mplane-interfaces:1.0">
  <m-plane-interfaces>
    <m-plane-sub-interfaces>
      <interface-name>mPlaneVlan295</interface-name>
      <sub-interface>295</sub-interface>
    </m-plane-sub-interfaces>
  </m-plane-interfaces>
</mplane-info>

Br,
Neeraj

**Comment by michalvasko** [comment]
What *netopeer2* version are you using? Have you tried executing `get-data --datastore operational --filter-xpath /o-ran-mplane-int:mplane-info/*` instead?

**Comment by Neeraj0019** [comment]
Hi,
We are using sysrepo Version 1.4.70 and planning to update to Version 1.4.104  in few weeks.

Below is the o/p of operational data.

 get-data --datastore operational --filter-xpath /o-ran-mplane-int:mplane-info/*
DATA
<mplane-info xmlns="urn:o-ran:mplane-interfaces:1.0">
  <m-plane-interfaces>
    <m-plane-sub-interfaces>
      <interface-name>mPlaneVlan295</interface-name>
      <sub-interface>295</sub-interface>
    </m-plane-sub-interfaces>
  </m-plane-interfaces>
</mplane-info>

Br,
Neeraj

**Comment by michalvasko** [comment]
Okay, update to 1.4.122 while you are at it but that is not the issue since `get-data` produces the same results. It should work so the last idea I have is you overwriting the data in the operational callbacks, can you share the code of each callback? If it is the case, you can simply stop this from happening by using `SR_SUBSCR_OPER_MERGE` when subscribing but you will probably still have some memory leaks, I am guessing.

**Comment by Neeraj0019** [comment]
Hi,
Below is the code we have, we have still not used the MERGE option as we don't have any such use case rpc/action/notification where data gets validated against operational data.

`#include <string.h>
#include <stdlib.h>
#include "o-ran-mplane-int-plugin.hpp"
#include <libyang/libyang.h>
#include <RedisDBInterface.hpp>
#include <RedisCommon.hpp>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>

#define MPLANE_INT_MODULE_NAME "o-ran-mplane-int"
//include top level container in xpath in below containers
#define MPLANE_INT_STATE_XPATH_interfaces "/o-ran-mplane-int:mplane-info/m-plane-interfaces/m-plane-sub-interfaces"
#define MPLANE_INT_STATE_XPATH_searchable_vlans "/o-ran-mplane-int:mplane-info/searchable-mplane-access-vlans-info"
#define MPLANE_INT_STATE_XPATH_configured_clients "/o-ran-mplane-int:mplane-info/configured-client-info"

sr_subscription_ctx_t *mplanesubscription;

static int mplane_int_state_cb_ifaces(sr_session_ctx_t *session, const char *module_name, const char *path, const char *request_xpath,
                uint32_t request_id, struct lyd_node **node, void *private_data)
{
        (void)private_data;
        (void)module_name;
        (void)request_xpath;
        (void)path;
        (void)request_id;
        std::string client_val = "";
        std::string port = "";

        try
        {
                DBIface::RedisDBInterface dbIface(DBIface::getRedisIP(), DBIface::getRedisPort(), DBIface::getRedisInstance());
                client_val = dbIface.hGetValue("oran-mplane-client-info", "client-ip");
                port = dbIface.hGetValue("oran-mplane-client-info", "port");
                if(client_val == "" || port == "")
                {
                        SRP_LOG_ERR("%s: DB reading failed for key oran-mplane-client-info client-ip/port.",MPLANE_INT_MODULE_NAME);
                }

                SRP_LOG_INF("module : %s, client_info: %s,port details: %s", MPLANE_INT_MODULE_NAME,client_val.c_str(),port.c_str());
                *node = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(session)), "/o-ran-mplane-int:mplane-info", NULL, LYD_ANYDATA_CONSTSTRING, 0);

                struct lyd_node* intfs = lyd_new(*node, NULL, "m-plane-interfaces");
                SRP_LOG_INF("%s: mplane-int m-plane-interfaces", MPLANE_INT_MODULE_NAME);

                struct lyd_node* list = lyd_new(intfs, NULL, "m-plane-sub-interfaces");
                SRP_LOG_INF("%s: mplane-int m-plane-sub-interfaces", MPLANE_INT_MODULE_NAME);

                lyd_new_leaf(list, NULL, "interface-name", "mPlaneVlan295");
                SRP_LOG_INF("%s: mplane-int interface-name", MPLANE_INT_MODULE_NAME);

                lyd_new_leaf(list, NULL, "sub-interface", "295");
                SRP_LOG_INF("%s: mplane-int sub-interface", MPLANE_INT_MODULE_NAME);

                struct lyd_node* cont1 = lyd_new(list, NULL, "client-info");
                SRP_LOG_INF("%s: mplane-int client-info", MPLANE_INT_MODULE_NAME);

                struct lyd_node* list1 = lyd_new(cont1, NULL,"mplane-ipv4-info");
                SRP_LOG_INF("%s: mplane-int mplane-ipv4-info", MPLANE_INT_MODULE_NAME);

                lyd_new_leaf(list1, NULL, "mplane-ipv4", client_val.c_str() );
                SRP_LOG_INF("%s: mplane-int mplane-ipv4", MPLANE_INT_MODULE_NAME);

                lyd_new_leaf(list1, NULL, "port", port.c_str());
                SRP_LOG_INF("%s:mplane-int port", MPLANE_INT_MODULE_NAME);

                //lyd_new_leaf(cont1, NULL, "mplane-fqdn", mp.client_info);
                return SR_ERR_OK;
        }
        catch(const std::exception& e)
        {
                SRP_LOG_ERR("%s: NULL data fetching from DB.", MPLANE_INT_MODULE_NAME);
                sr_set_error(session, NULL, "Failed to read db %s",e.what());
                return SR_ERR_INTERNAL;
        }
        catch(...)
        {
                SRP_LOG_ERR("%s: NULL data fetching from DB.", MPLANE_INT_MODULE_NAME);
                sr_set_error(session, NULL, "Failed to read db ");
                return SR_ERR_INTERNAL;
        }
}

static int mplane_config_change_cb(sr_session_ctx_t *session, const char *module_name, const char *path, sr_event_t event,
                                        uint32_t request_id, void *private_data)
{
        (void)module_name;
        (void)path;
        (void)request_id;
        (void)private_data;
        (void)session;
        (void)event;
        SRP_LOG_ERR("%s: Modification not supported", MPLANE_INT_MODULE_NAME);
        sr_set_error(session,nullptr,"%s","Modification not allowed for this model");
        return SR_ERR_UNSUPPORTED;
}

static int mplane_int_state_cb_clients(sr_session_ctx_t *session, const char *module_name, const char *path, const char *request_xpath,
                                       uint32_t request_id, struct lyd_node **node, void *private_data)
{
//      SRP_LOG_INF("Inside mplane_int_state_cb_clients func");
        SRP_LOG_ERR("%s: TEST Retrievel and Modification not supported for configured-client-info container", MPLANE_INT_MODULE_NAME);
        (void)module_name;
        (void)path;
        (void)request_xpath;
        (void)request_id;
        (void)private_data;
        (void)session;
        (void)node;
        SRP_LOG_ERR("%s: Retrievel and Modification not supported for configured-client-info container", MPLANE_INT_MODULE_NAME);
        sr_set_error(session,nullptr,"%s","Retrievel and Modification not supported for configured-client-info container");
        return SR_ERR_UNSUPPORTED;
}


static int mplane_int_state_cb_vlans(sr_session_ctx_t *session, const char *module_name, const char *path, const char *request_xpath,
                                        uint32_t request_id, struct lyd_node **node, void *private_data)
{
		(void)module_name;
        (void)path;
        (void)request_xpath;
        (void)request_id;
        (void)private_data;
        (void)session;
        (void)node;
        SRP_LOG_ERR("%s: Retrievel and Modification not supported for searchable-mplane-access-vlans-info container", MPLANE_INT_MODULE_NAME);
        sr_set_error(session,nullptr,"%s","Retrievel and Modification not supported for searchable-mplane-access-vlans-info container");
        return SR_ERR_UNSUPPORTED;
}

//main method
int sr_plugin_init_cb(sr_session_ctx_t *session, void **private_data)
{
        int rc;
        (void)private_data;

        rc = sr_oper_get_items_subscribe(session, MPLANE_INT_MODULE_NAME, MPLANE_INT_STATE_XPATH_interfaces, mplane_int_state_cb_ifaces,
                                        NULL, SR_SUBSCR_DEFAULT, &mplanesubscription);

        rc = sr_oper_get_items_subscribe(session, MPLANE_INT_MODULE_NAME, MPLANE_INT_STATE_XPATH_searchable_vlans, mplane_int_state_cb_vlans,
                                        NULL, SR_SUBSCR_CTX_REUSE, &mplanesubscription);

        rc = sr_oper_get_items_subscribe(session, MPLANE_INT_MODULE_NAME, MPLANE_INT_STATE_XPATH_configured_clients, mplane_int_state_cb_clients,
                                        NULL, SR_SUBSCR_CTX_REUSE, &mplanesubscription);

        rc = sr_module_change_subscribe(session, MPLANE_INT_MODULE_NAME, NULL, mplane_config_change_cb, NULL, 0,
                                        SR_SUBSCR_CTX_REUSE, &mplanesubscription);

        if (SR_ERR_OK != rc)
        {
                goto error;
        }
        SRP_LOG_DBG("%s: plugin initialized successfully.",MPLANE_INT_MODULE_NAME);
        return SR_ERR_OK;

error:
        SRP_LOG_ERR("%s: plugin initialization failed: %s.",MPLANE_INT_MODULE_NAME, sr_strerror(rc));
        if (mplanesubscription != NULL)
        {
                sr_unsubscribe(mplanesubscription);
        }
        return rc;

}

void sr_plugin_cleanup_cb(sr_session_ctx_t *session, void *private_data)
{
        (void)session;
        (void)private_data;

        sr_unsubscribe(mplanesubscription);
        SRP_LOG_INF("%s: mplane-int plugin cleanup finished.", MPLANE_INT_MODULE_NAME);
}

`
Note: below data are already stored in sysrepo startup and running DS using sysrepocfg.

below data are already stored in sysrepo startup and running DS via sysrepocfg command.

> get --filter-xpath /o-ran-mplane-int:mplane-info/*
DATA
<mplane-info xmlns="urn:o-ran:mplane-interfaces:1.0">
  <m-plane-interfaces>
    <m-plane-sub-interfaces>
      <interface-name>mPlaneVlan295</interface-name>
      <sub-interface>295</sub-interface>
    </m-plane-sub-interfaces>
  </m-plane-interfaces>
</mplane-info>
Br,
Neeraj

**Comment by michalvasko** [comment]
Hmm, that is a bit strange, do you even have `sysrepo-plugind` running with the plugin loaded and initialized successfully? Not sure why else it would not work.

**Comment by Neeraj0019** [comment]
Hi,
Yes sysreo-plugind is running and plugin is loaded successfully, as first callback works where we are fill some state data. The callback which just return error, doesn't get hit.

Br,
Neeraj

**Comment by michalvasko** [comment]
I see, that I am not able to more without reproducing the issue but may have one final idea. Try removing lines
```C
                *node = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(session)), "/o-ran-mplane-int:mplane-info", NULL, LYD_ANYDATA_CONSTSTRING, 0);

                struct lyd_node* intfs = lyd_new(*node, NULL, "m-plane-interfaces");
                SRP_LOG_INF("%s: mplane-int m-plane-interfaces", MPLANE_INT_MODULE_NAME);
```
because as written in the documentation, the parent of the subtree you are subscribing for is provided for you. Meaning the `node` you get in the callback is `m-plane-interfaces` so adjust the rest of the parents accordingly. You are effectively replacing the parents that are provided, which may possibly cause some problems, I am not sure.

**Comment by Neeraj0019** [comment]
Hi,
Ok i will try more things from my side first. Also i thing i had tried not having the lyd_new_path() part, but it was not working.

And here are you suspecting that because of one call back implementation issue, other call backs are not getting called?

Br,
Neeraj

**Comment by michalvasko** [comment]
> And here are you suspecting that because of one call back implementation issue, other call backs are not getting called?

It is not probable, but definitely possible.

**Comment by Neeraj0019** [comment]
Hi Michal,
I am trying to test with sysrepo version 104 now and have some doubts w.r.t operational data.

1. Based on my earlier ticket, you mentioned that if we use MERGE option while subscribing for operational data, config parameters defined with default values in the yang model will automatically come in the get response but same is not happening. In the yang model attached in previous comments we have below default parameter defined which i was expecting to come automatically in the response.
` container m-plane-ssh-ports {
        description "leafs for managing SSH ports";
        leaf call-home-ssh-port {
          type inet:port-number;
          default 4334;
          description "The configured call home server port number";
        }
        leaf server-ssh-port {
          type inet:port-number;
          default 830;
          description "The configured SSH server port number";
        }
      }
`

2. With new sysrepo version 104, when i am trying to get data from netopeer client , i get some error leafref logs, even though data is available in operational DB.

`Mar 22 12:08:17.802505 info ruproxy-1 netopeer[264]: [INF]: SR: Event "operational" with ID 2 succeeded.
Mar 22 12:08:17.802505 info ruproxy-1 netopeer[264]: [INF]: LY: Resolving unresolved data nodes and their constraints...
Mar 22 12:08:17.802560 info ruproxy-1 sysrepo[268]: [INF]: plugin: o-ran-mplane-int: mplane-int mplane-ipv4-info
Mar 22 12:08:17.802577 info ruproxy-1 netopeer[264]: [INF]: LY: There is no leafref "/ietf-interfaces:interfaces/ietf-interfaces:interface/ietf-interfaces:name" with the value "mPlaneVlan295", but it is not required.
Mar 22 12:08:17.802619 info ruproxy-1 sysrepo[268]: [INF]: plugin: o-ran-mplane-int: mplane-int mplane-ipv4
Mar 22 12:08:17.802635 info ruproxy-1 netopeer[264]: [INF]: LY: There is no leafref "/ietf-interfaces:interfaces/ietf-interfaces:interface[ietf-interfaces:name = current()/../interface-name]/o-ran-interfaces:vlan-id" with the value "295", but it is not required.
Mar 22 12:08:17.802685 info ruproxy-1 sysrepo[268]: [INF]: plugin: o-ran-mplane-int:mplane-int port
Mar 22 12:08:17.802706 info ruproxy-1 netopeer[264]: [INF]: LY: All data nodes and constraints resolved.
Mar 22 12:08:17.802740 info ruproxy-1 sysrepo[268]: [INF]: Successful processing of "operational" event with ID 2.
Mar 22 12:08:17.803319 info ruproxy-1 netopeer[264]: [INF]: SR: Successful processing of "rpc" event with ID 3 priority 0 (remaining 0 subscribers).
Mar 22 12:08:17.803319 info ruproxy-1 netopeer[264]: [INF]: SR: Event "rpc" with ID 3 priority 0 succeeded.
Mar 22 12:08:17.803425 info ruproxy-1 netopeer[264]: [INF]: LY: Resolving unresolved data nodes and their constraints...
Mar 22 12:08:17.803487 info ruproxy-1 netopeer[264]: [INF]: LY: All data nodes and constraints resolved.
Mar 22 12:08:17.803566 info ruproxy-1 netopeer[264]: [INF]: LY: Resolving unresolved data nodes and their constraints...
Mar 22 12:08:17.803613 info ruproxy-1 netopeer[264]: [INF]: LY: There is no leafref "/ietf-interfaces:interfaces/ietf-interfaces:interface/ietf-interfaces:name" with the value "mPlaneVlan295", but it is not required.
Mar 22 12:08:17.803668 info ruproxy-1 netopeer[264]: [INF]: LY: There is no leafref "/ietf-interfaces:interfaces/ietf-interfaces:interface[ietf-interfaces:name = current()/../interface-name]/o-ran-interfaces:vlan-id" with the value "295", but it is not required.
`

below is the operational data o/p for ietf-interfaces module  which has mPlaneVlan295 with vlan-id 295 in oper ds.

`> get-data --datastore operational --filter-xpath /ietf-interfaces:interfaces/interface[name="mPlaneVlan295"]
DATA
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interface>
    <name>mPlaneVlan295</name>
    <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:l2vlan</type>
    <ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip">
      <address>
        <ip>192.168.100.3</ip>
        <prefix-length>24</prefix-length>
      </address>
    </ipv4>
    <base-interface xmlns="urn:o-ran:interfaces:1.0">oraneth0</base-interface>
    <vlan-id xmlns="urn:o-ran:interfaces:1.0">295</vlan-id>
    <phys-address>0c:7c:28:23:33:a1</phys-address>
    <oper-status>up</oper-status>
    <lower-layer-if>oraneth0</lower-layer-if>
    <last-change>2021-03-22T12:07:06Z</last-change>
  </interface>
</interfaces>

>
`

Br,
Neeraj

**Comment by michalvasko** [comment]
> you mentioned that if we use MERGE option while subscribing for operational data, config parameters defined with default values in the yang model will automatically come in the get response

I have certainly not suggested this, in general, but it may have been true for your specific use-case. The actual functionality would be that any default data *existing* in `running` should be returned in `get` response if you either have no operational subscriptions that would overwrite the particular data or they have the MERGE option. And I am not able to verify this from the information you posted so I cannot help you.

> i get some error leafref logs

As you see, they are not errors (the log level) so you can safely ignore them.

**Comment by Neeraj0019** [comment]
ok, so you mean to say that even if yang model defines some default config data, we still need to put those defaults in running DS first and then only it will be returned back in get response?

As once i store these default values in running DS using sysrepocfg, i am able to get those.

**Comment by michalvasko** [comment]
> even if yang model defines some default config data, we still need to put those defaults in running DS first and then only it will be returned back in get response?

No, I am simply saying that there are some [conditions](https://tools.ietf.org/html/rfc7950#section-7.6.1) for default data to actually exist.

> As once i store these default values in running DS using sysrepocfg, i am able to get those.

In that case I believe they should appear in the `get` response (note that if using *netopeer2-cli*, you need to use a `with-defaults` parameter for `get` to actually see the default values). Unless some operational subscription overrides them, like I said.

**Comment by Neeraj0019** [comment]
Ok, able to get the details without storing it explicitly in sysrepo, using the **--defaults** option from client side.

> get --filter-xpath /o-ran-mplane-int:mplane-info/* --defaults report-all-tagged
DATA
<mplane-info xmlns="urn:o-ran:mplane-interfaces:1.0" xmlns:ncwd="urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults">
  <m-plane-interfaces>
    <m-plane-ssh-ports>
      **<call-home-ssh-port ncwd:default="true">4334</call-home-ssh-port>
      <server-ssh-port ncwd:default="true">830</server-ssh-port>**
    </m-plane-ssh-ports>
    <m-plane-sub-interfaces>
      <interface-name>mPlaneVlan295</interface-name>
      <sub-interface>295</sub-interface>
      <client-info>
        <mplane-ipv4-info>
          <mplane-ipv4>192.168.100.1</mplane-ipv4>
          <port>4334</port>
        </mplane-ipv4-info>
      </client-info>
    </m-plane-sub-interfaces>
  </m-plane-interfaces>
</mplane-info>

Br,
Neeraj
