### ISSUE TITLE
netopeer2-server process crash when switch callhome to ssh listen serval times

### ISSUE THREAD

**Issue by koala027** [sysrepo/sysrepo#2368]
Hi michalvasko,

So sorry to trouble you again. We use sysrepo and libnetconf2 for some netconf project.

Since we need to support both call home and SSH Listen connection mode in run-time.
When try to switch call home to ssh listen,  and then swithch ssh listen to call home serval times. then send a get rpc.
The netopeer2-server crashed. from the coredump stack. It seems have some problem in **sr_shmsub_rpc_notify**

![image](https://user-images.githubusercontent.com/41620079/111100741-5f3d6080-8583-11eb-90f0-4f50f172fc1d.png)

sudo sysrepocfg --import=callhome.xml --datastore running --module ietf-netconf-server
sudo sysrepocfg --import=ssh_listen.xml --datastore running --module ietf-netconf-server
.....
sudo sysrepocfg --import=ssh_listen.xml --datastore running --module ietf-netconf-server
serval times import. i attached the callhome.xml and ssh_listen.xml

[xml.tar.gz](https://github.com/sysrepo/sysrepo/files/6139134/xml.tar.gz)

Do you have any idea about this issue? thanks michalvasko again.

**Comment by michalvasko** [comment]
What *sysrepo* version are you using? Also, the screenshot is mostly useless because the file lines are cropped.

**Comment by koala027** [comment]
set(SYSREPO_MAJOR_VERSION 1)
set(SYSREPO_MINOR_VERSION 4)
set(SYSREPO_MICRO_VERSION 66)

Yes, i try to add some debug printf in source code, so the lines are cropped. but the function name is correctly. 
from the backtrace, there are some information can be found.   
  **sr_rpc_send_tree --> sr_shmsub_rpc_notify  .....**

**Comment by michalvasko** [comment]
No, I am afraid you will have to update *sysrepo* to the latest release, which will in all likelihood fix the problem. Even if not, I cannot be sure of that so I can help you only after you reproduce the problem with the latest release.
