### ISSUE TITLE
Getting internal Error while updating operational data.

### ISSUE THREAD

**Issue by Ritesh545** [sysrepo/sysrepo#2371]
Hi Michal,
My application is trying to update operational data by performing write in sysrepo, don't see any error messages from sysrepo while doing the write operation.
But when I try to get the data in netopeer2-CLI using the get command,  it through an internal error.

 **console output of netopeer2-cli** : 
 ------------------------------------
 
 _> get --filter-xpath /_3gpp_nr_nrm:ME/AlarmList[id='0']/numOfAlarmRecords
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	message:  Internal error (/home/ankit/sysrepo/src/edit_diff.c:2675)._

**console output of netopeer2-sever:**
--------------------------------------------
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" "/ietf-netconf:get" with ID 3 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:get" "rpc" event with ID 3 priority 0 (remaining 1 subscribers).
[ERR]: SR: Internal error (/home/ankit/sysrepo/src/edit_diff.c:2675).
[ERR]: NP: Getting data "/_3gpp_nr_nrm:*" from sysrepo failed (Internal error).
[INF]: SR: Failed processing of "rpc" event with ID 3 priority 0 (remaining 1 subscribers).
[ERR]: SR: Internal error (/home/ankit/sysrepo/src/edit_diff.c:2675).
[WRN]: SR: Event "rpc" with ID 3 priority 0 failed (Internal error).
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 2: thread 3 event new RPC.
[INF]: NP: Session 2: thread 3 event reply error.

Using set_get_item.c file provided in example module using that I can get all modified operational data which my application is updating, which specify write in sysrepo is working fine.

I have attached app_running.txt file . (In this i am able to get modified data done by application and the application is in running state).

_Another issue I am facing is that once my application binary disconnects,  data that the application has written in sysrepo db is deleted. So is there any way to persist changes done by application in sysrep db . (so if we disconnect  application then also  data is not deleted in sysrep db)_

for example :
/_3gpp_nr_nrm:ME/GNBDUFunction[id='0']/NRCellDU[id='0']/operationalState = Disabled
/_3gpp_nr_nrm:ME/GNBDUFunction[id='0']/NRCellDU[id='0']/cellState = Idle
The above data is not available once I disconnect my application.
I have attached app_disconnect.txt file .(After application is disconnected written data gets deleted)

Thanks
[app_disconnect.txt](https://github.com/sysrepo/sysrepo/files/6181646/app_disconnect.txt)
[app_running.txt.txt](https://github.com/sysrepo/sysrepo/files/6181647/app_running.txt.txt)

**Comment by michalvasko** [comment]
I would need a way to reproduce this to fix it and probably add to the tests, could you provide that? As for your second problem, it is a [feature](https://netopeer.liberouter.org/doc/sysrepo/devel/html/index.html#oper_data).

**Comment by Ritesh545** [comment]
Hi Michal,
Please find the attached 3gpp yang modules  :   [yang_modules.zip](https://github.com/sysrepo/sysrepo/files/6218639/yang_modules.zip)

Also  following is a code snippet that I used to update operational data:

        sr_conn_ctx_t *connection = NULL;
        sr_session_ctx_t *session = NULL;
        int rc = SR_ERR_OK;
        std::string path     = "/_3gpp_nr_nrm:ME";
        std::string mod_name = "_3gpp_nr_nrm";

        /* turn logging on */
        sr_log_stderr(SR_LL_DBG);

        /* connect to sysrepo */
        rc = sr_connect(0, &connection);
        if (rc != SR_ERR_OK) {
            std::cout<<"Err while sr_connect"<<std::endl;
        }

        /* start session in operational datastore */
        rc = sr_session_start(connection, SR_DS_OPERATIONAL, &session);
        if (rc != SR_ERR_OK) {
            std::cout<<"Err while sr_session_start"<<std::endl;
        }
        std::string alarm_id = "14081";
        std::string xpath = "/_3gpp_nr_nrm:ME/AlarmList[id='0']/AlarmRecordGrp[alarmId='" + alarm_id +"']/alarmId";
        std::string xpath2 = "/_3gpp_nr_nrm:ME/AlarmList[id='0']/AlarmRecordGrp[alarmId='"+ alarm_id +"']/alarmName";
        std::string xpath3 = "/_3gpp_nr_nrm:ME/AlarmList[id='0']/AlarmRecordGrp[alarmId='"+ alarm_id +"']/alarmRaisedTime";
        std::string xpath4 = "/_3gpp_nr_nrm:ME/AlarmList[id='0']/AlarmRecordGrp[alarmId='"+ alarm_id +"']/perceivedSeverity";
        std::string xpath5 = "/_3gpp_nr_nrm:ME/AlarmList[id='0']/AlarmRecordGrp[alarmId='"+ alarm_id +"']/alarmType";
        std::string xpath6 = "/_3gpp_nr_nrm:ME/AlarmList[id='0']/AlarmRecordGrp[alarmId='"+ alarm_id +"']/objectClass_objectInstance";

        rc = sr_set_item_str(session, xpath5.c_str() ,"COMMUNICATIONS_ALARM", NULL, 0);
        rc = sr_set_item_str(session, xpath6.c_str(), "F1C_0", NULL, 0);
        rc = sr_set_item_str(session,xpath.c_str() , alarm_id.c_str(), NULL, 0);
        rc = sr_set_item_str(session, xpath2.c_str(),"F1_C_ALARM_F1_C_COMM_DOWN", NULL, 0);
        rc = sr_set_item_str(session,xpath3.c_str(),"2021-03-26T12:39:14+0530", NULL, 0);
        rc = sr_set_item_str(session,xpath4.c_str(),"CRITICAL", NULL, 0);
        rc = sr_apply_changes(session, 0, 1);
        if (rc != SR_ERR_OK)
        {
            std::cout<<"Err while sr_apply_changes"<<std::endl;
        }   
        int i;
        i = sr_has_changes(session);
        std::cout << "sr_has_changes : " << i << "\n";
        rc = sr_session_stop(session);
        if (rc != SR_ERR_OK)
        {
            std::cout<<"Err while sr_session_stop"<<std::endl;
        }

**Comment by michalvasko** [comment]
Unfortunately, this is useless, I have tried having the data set and using the `get` with filter you mentioned before, I got no error. Also, what *sysrepo* version are you using?

**Comment by adrianlita** [comment]
Hi Michal,

I've put together a scenario where I always get the error.
In the attached zip file, you'll find a simple yang model, as well as the test.c code and XML files with data, data which the test code will load into both operational and running datastores (except for change.xml and rpc.xml).

Compiling the program: gcc -Wall -pedantic test.c -lyang -lsysrepo -otest

libyang/sysrepo versions tested on: v1.0.225 / v1.4.122

Scenario:
1. the provided module is installed; I also have netopeer2 started
2. run test program
	- this will automatically populate o-ran-sc-du-hello-world module with data on both running and operational (data from the XML files)
	- the program will then wait for the ENTER key to be pressed until disconnecting from SR and exiting (DO NOT PRESS YET) --- so basically the operational data will be available
3. run a get on the o-ran-sc-du-hello-world module; everything works and looks fine
4. edit one filed, for example, administrative-state of item O-RU-11221
	- I've tested editing via netconf: i've attached rpc.xml, you can use it to edit-config
	- I've also tested editing directly via sysrepocfg with the edit flag
	- I've also tested with sysrepocfg like this: sysrepocfg --import=change.xml -d running -f xml -m o-ran-sc-du-hello-world
	- in all cases it behaves the same
5. (optional) try to run a get-config on the list, and it WILL work
6. try to run a get on the list, it WILL NOT work
7. on the program window, press enter to turn off the program
8. now that there's no operational data, get WILL work

Kind regards,
Adrian
[test-scenario.zip](https://github.com/sysrepo/sysrepo/files/6552367/test-scenario.zip)

**Comment by michalvasko** [comment]
I am not able to reproduce on `devel`. I try not to insist on having every issue reproduced on `devel` by the author but you should always do that, in your own interest. And save some wasted time for me.

**Comment by adrianlita** [comment]
Can you please let me know briefly how can I do that ?

**Comment by michalvasko** [comment]
What do you mean? I assume you have cloned and installed the `master` branches of *libyang*/*sysrepo* projects. So just switch to `devel` branches.

**Comment by adrianlita** [comment]
Thank you for the clarification!
