### ISSUE TITLE
Question about mixing push ops data and pull ops callback in a single module

### ISSUE THREAD

**Issue by peckato1** [sysrepo/sysrepo#2375]
Hello,

I'm trying to implement [ietf-interfaces YANG model](https://tools.ietf.org/html/rfc8343). I was hoping to implement the `/ietf-interfaces:interfaces/interface/statistics" subtree via pull ops subscriptions while the rest of the leafs in the interface list would be implemented using push ops data.

In the [docs](https://netopeer.liberouter.org/doc/sysrepo/master/html/subs.html) you say that you should not mix pull ops data subscription with code that uses push ops data in the same module (#2285).

> **When using these pull operational data subscriptions**, the subscription must be actively handling events whenever operational datastore data of the module are requested (so these 2 operations cannot occur in a single thread, so they must have individual subscription structures) to avoid a time out. Note that operational datastore data are required not only when requested explicitly using a getter but also when validating operational datastore (all modules or the same module), **setting push operational data (for the same module)**, or sending an RPC/action or a notification (if the specific module data are required for validation).

I have tried to put up a simple program (see below) that mixes both pull ops data subscription and push ops data in the same module and I'm unable to obtain any timeout. 
If I correctly understand sysrepo's behaviour in the program below, the pull callback is invoked inside callback thread, but push ops data is invoked from main thread. Therefore, is it true, that the program is always "actively handling events" (see quote above). Or is this approach wrong? Are there any possible caveats in the threading model that I don't see?

The problem in #2285 was that both push ops and pull ops callback were executed from a single thread.

The sysrepo program:
```cpp
#include <map>
#include <spdlog/spdlog.h>
#include <sysrepo-cpp/Session.hpp>

void tree(const std::map<std::string, std::string>& values, std::shared_ptr<::sysrepo::Session> session, std::shared_ptr<libyang::Data_Node>& parent)
{
	for (const auto& [propertyName, value] : values) {
		if (!parent) {
			parent = std::make_shared<libyang::Data_Node>(
					session->get_context(),
					propertyName.c_str(),
					value.c_str(),
					LYD_ANYDATA_CONSTSTRING,
					LYD_PATH_OPT_OUTPUT);
		} else {
			parent->new_path(
					session->get_context(),
					propertyName.c_str(),
					value.c_str(),
					LYD_ANYDATA_CONSTSTRING,
					LYD_PATH_OPT_OUTPUT);
		}
	}
}

int main()
{
	auto srConn = std::make_shared<sysrepo::Connection>();
	auto srSess = std::make_shared<sysrepo::Session>(srConn);
	auto srSubs = std::make_shared<sysrepo::Subscribe>(srSess);

	const std::string yangPrefix = "/ietf-interfaces:interfaces/interface[name='lo']";

	srSubs->oper_get_items_subscribe(
			"ietf-interfaces", [&yangPrefix](auto session, auto, auto, auto, auto, auto& parent) {
				spdlog::info("pull");

				std::map<std::string, std::string> vals;
				vals[yangPrefix + "/statistics/discontinuity-time"] = "2021-03-01T00:00:00Z";
				vals[yangPrefix + "/statistics/in-octets"] = "42";
				vals[yangPrefix + "/statistics/out-octets"] = "42";

				tree(vals, session, parent);
				return SR_ERR_OK;
			},
			"/ietf-interfaces:interfaces/interface/statistics");

	srSess->session_switch_ds(SR_DS_OPERATIONAL);
	bool b = false;
	while(true) {
		spdlog::info("push");
		srSess->set_item_str((yangPrefix + "/phys-address").c_str(), b ? "00:00:00:00:00:00" : "11:11:11:11:11:11");
		srSess->set_item_str((yangPrefix + "/oper-status").c_str(), b ? "unknown" : "down");
		srSess->apply_changes();

		b = !b;
	}

	return 0;
}
```
and I'm periodically getting the data via 
```bash
while true; do ./sysrepocfg -d operational -X --xpath "/ietf-interfaces:interfaces/interface"; done
```

**Comment by michalvasko** [comment]
Right, as the documentation says, providing and requesting operational data cannot occur in a single thread. But you have subscribed for providing operational data without any flags (meaning a separate thread is created) and the callback being called does not request operational data (that is when you would get the timeout) so it is fine.

**Comment by peckato1** [comment]
Hello again,

thanks for your response. I thought it would be something like this.
However, the code (and its usage) is probably not safe. We have been able to reproduce the following on different machines. Usually it happens several seconds after start.
The files in SHM (`/dev/shm/sr*`) files were deleted prior to the run.

```
(...)

[11:09:01] [t 376450] push
[11:09:01] [t 376450] push
[11:09:01] [t 376450] push
[11:09:01] [t 376455] pull
terminate called after throwing an instance of 'sysrepo::sysrepo_exception'
  what():  Internal error

Thread 1 "a.out" received signal SIGABRT, Aborted.
0x00007ffff7962ef5 in raise () from /usr/lib/libc.so.6
```

```gdb
(gdb) t a a bt

Thread 2 (Thread 0x7ffff7146640 (LWP 376455) "a.out"):
#0  0x00007ffff7a1cad1 in select () from /usr/lib/libc.so.6
#1  0x00007ffff78fb87f in sr_shmsub_listen_thread (arg=0x55555561ff50) at ../src/shm_sub.c:3490
#2  0x00007ffff7770299 in start_thread () from /usr/lib/libpthread.so.0
#3  0x00007ffff7a25053 in clone () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7ffff76e9780 (LWP 376450) "a.out"):
#0  0x00007ffff7962ef5 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff794c862 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff7cea86a in __gnu_cxx::__verbose_terminate_handler () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff7cf6d3a in __cxxabiv1::__terminate (handler=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#4  0x00007ffff7cf6da7 in std::terminate () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#5  0x00007ffff7cf704e in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=0x7ffff7f9a7e8 <typeinfo for sysrepo::sysrepo_exception>, dest=0x7ffff7f706e0 <sysrepo::sysrepo_exception::~sysrepo_exception()>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:95
#6  0x00007ffff7f70789 in sysrepo::throw_exception (error=7) at ../bindings/cpp/src/Sysrepo.cpp:65
#7  0x00007ffff7f74712 in sysrepo::Session::apply_changes (this=0x5555556f3b80, timeout_ms=0, wait=0) at ../bindings/cpp/src/Session.cpp:263
#8  0x0000555555573e6b in main ()
>>> 
```

and the export request via `sysrepocfg` then ends up with this
```
sysrepocfg: ../src/common.c:3054: sr_rwlock: Assertion `!rwlock->upgr && !rwlock->writer' failed.
Neúspěšně ukončen (SIGABRT) (core dumped [obraz paměti uložen])
[ERR]: Locking a mutex failed (sr_shmmod_lock: State not recoverable).
sysrepocfg error: Getting data failed (Internal error)
[ERR]: Locking a mutex failed (sr_shmmod_lock: State not recoverable).
[ERR]: Locking a mutex failed (sr_shmmod_lock: State not recoverable).
syrepocfg error: Getting data failed (Internal error)

...
```


Used versions:
 * libyang `abc01b2a6d26e25cdb46f579f32e3f201b8f3fac`
 * sysrepo `95bb36e180d880c1921ed182f04be45585e00044`

**Comment by peckato1** [comment]
Thanks, now it seems fine.
