### ISSUE TITLE
Clarify SR_SUBSCR_ENABLED on SR_DS_STARTUP

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#2376]
The `SR_SUBSCR_ENABLED` currently doesn't say that it has no effect when subscribing to the `startup` datastore. Can you please either document this, or fix the code so that, e.g., subscribing to the `startup` DS will also result in the module change CB being immediately executed and receiving a copy of the initial data?

**Comment by michalvasko** [comment]
I am not sure anymore why was it restricted only for the running datastore (I guess nothing else made sense to me than, I have long given up on that) and not being able to find reasons why it should not work for all the datastores (which does not mean there are not), I have changed it.

**Comment by jktjkt** [comment]
Thanks, this makes our code a bit simpler.
