### ISSUE TITLE
Segmentation fault during operational data recovery

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2377]
Hi,

I'm facing the following issue:
I have two processes. These processes push operational data (same list but different instances). One of the  modules sometimes stops because of another issue (not related to Sysrepo).
When the process stops, the other one stops as well because of the following error:

[WRN]: Connection with CID 2 is dead.
[INF]: Recovering stored operational data of CID 2.
Thread 1 "set2" received signal SIGSEGV, Segmentation fault.
lyd_free_internal_r (top=1, node=0x8425970) at /opt/dev/libyang/src/tree_data.c:6236

I've attached 2 simple C applications which may help you in the reproduction of the issue:
[reprod.zip](https://github.com/sysrepo/sysrepo/files/6203998/reprod.zip)

set.c: sets  /ietf-interfaces:interfaces/interface[name='eth0']/oper-status periodically. 
set2.c subscribe for /ietf-interfaces:interfaces/interface and sets  /ietf-interfaces:interfaces/interface[name='eth1']/oper-status periodically.

Steps to reproduce:
1. Start  process #1 (set.c).
2. Start  process #2 (set2.c).
3. Stop process #1 (e.g. kill -SEGV <PID of process #1>

libyang version: 1.0.224
sysrepo version: 1.4.122

Thanks

**Comment by michalvasko** [comment]
Okay, should be fixed now.

**Comment by awesomenode** [comment]
The issue is gone, thanks!
