### ISSUE TITLE
sysrepoctl: Installation failure with very unhelpful error message

### ISSUE THREAD

**Issue by peckato1** [sysrepo/sysrepo#2384]
Hello,

yesterday I spent quite a time while trying to install an `ietf-routing` module via `sysrepoctl` but it almost always resulted into the following error message:

```sh
$ sysrepoctl -i ietf-routing@2018-03-13.yang -a
[ERR]: Applying scheduled changes failed.
sysrepoctl error: Failed to apply changes (Operation failed)
```

After quite a time I debugged that if i install only `ietf-interfaces` and `ietf-routing`, it installs fine. However, if I augment the `ietf-interfaces` model (deviation that removes `ietf-interfaces:interfaces-state` container) and try to install it in the order `ietf-interfaces`, `mod` (see below), `ietf-routing` I get the message above.
The "deviation model" is here:
```yang
module mod {
    yang-version 1.1;
	namespace "urn:bla:mod";
	prefix m;

    import ietf-interfaces {
        prefix if;
    }

    deviation /if:interfaces-state { deviate not-supported; }
}
```

This is indeed my fault, because `ietf-routing` references nodes inside the `if:interfaces-state` container. However for some time I couldn't find the error and sysrepo wasn't really helpful for me. I *think* this deserves a better error message than just "failure".

How to reproduce:
 * install [https://github.com/YangModels/yang/blob/master/standard/ietf/RFC/ietf-interfaces%402018-02-20.yang](ietf-interfaces@2018-02-20.yang)
 * install the module above
 * try to install [https://github.com/YangModels/yang/blob/master/standard/ietf/RFC/ietf-routing%402018-03-13.yang](ietf-routing@2018-03-13.yang) and see the error message.

**Comment by michalvasko** [comment]
I am quite sure you would get a better message if you have just increased *sysrepocfg* verbosity, `-v3`.

**Comment by michalvasko** [comment]
Okay, why not. But I was hoping the first thing to try when a tool is not providing enough information is to increase the verbosity, in general.

**Comment by jktjkt** [comment]
Thanks
