### ISSUE TITLE
Qestion : Does sysrepo support sending notifications to the specific NETCONF client ?

### ISSUE THREAD

**Issue by ezekieltsui** [sysrepo/sysrepo#2390]
Pre-condition : Two different `netopeer2-cli` ( `client_1` & `client_2` ) connect to the same `netopeer2-server`, they both subscribed to the same `notification`.

What I expected is : When `netopeer2-server` only send the `notification` to `client_1`, `client_1` should receive the `notification`, but `client_2` receive nothing. 

Does `sysrepo` support it ? Does `sysrepo` support sending `notifications` to the specific `NETCONF client` ?

<br/>

I saw `sr_event_notif_send (sr_session_ctx_t *session, const char *path, const sr_val_t *values, const size_t values_cnt)` and `sr_event_notif_send_tree (sr_session_ctx_t *session, struct lyd_node *notif)` only bind to a `sysrepo session`. So I have tried build `sysrepo session` for each `NETCONF Client` using `sr_session_start()` ( just called it sysrepo_session_1 & sysrepo_session_2 for now ) , and I have also used `sr_session_get_event_nc_id()` to get the `nc_id`, and set this `nc_id` for each `NETCONF Client`'s `sysrepo session` by using `sr_session_set_nc_id (sr_session_ctx_t *session, uint32_t nc_sid)`. At last I used `sr_event_notif_subscribe_tree ( sysrepo_session_1, ... )` to send the notification.
But the result is not as I expected. Is my understanding of the API wrong ?

**Comment by michalvasko** [comment]
No, you cannot send a notification to a specific subscriber, I dare say allowing this would go against general YANG principles. The point of *sysrepo* is that it is global (for a system) so no "internal" notifications or any kinds of messages are supported.

**Comment by ezekieltsui** [comment]
Got it, thank you.
