### ISSUE TITLE
NEW feature: Is that possible to provide different store methods for startup datastore, then it is can store the data to other database e.g redis than file

### ISSUE THREAD

**Issue by starx1000** [sysrepo/sysrepo#2391]
Hi,
  We are currently using kubernetes with netopeer2-server.
 
   Currently sysrepo stores the startup datastore as local file.
   Then in k8s POD the only way backup/restore the startup datastore is using persistent volume (PSV). 
   
   We want to save it to other existing db 

 I am wondering that whether sysrepo can implement a feature that save/load the startup datastore via plugin provided function.
 Then we could save/load it to redis db which could be more flexible..  

Or 
 sysrepo provides some alternatives directly (e.g redis) and config the storage methods with RUNTIME ENV or CMAKE options. 

Is it feasible?   Thanks!..  

Best Regards

**Comment by jktjkt** [comment]
What we've been doing on an embedded Linux box with read-only rootfs and a writable config partition is using `sysrepocfg` to backup and restore the contents of the `running` DS into a persistent location. Frankly, I don't think that a Redis backend would materialize anytime soon, but I would love to get a standard feature that runs once the `startup` DS changes, and which runs exactly once for each commit (that is, not on a per-module basis as a regular change subscription). We're using an `inotify` script as a workaround, like this:
```sh
while true; do
  inotifywait -e CLOSE_WRITE /etc/sysrepo/data/*.startup \
      && mkdir -p /cfg/sysrepo/ \
      && sysrepocfg -d startup -f json -X > /cfg/sysrepo/startup.json
done
```

**Comment by michalvasko** [comment]
This feature is planned to be implemented in Q3, specifically to support custom datastores and not only LYB files. The idea is that it will allow to set your own plugin for storing the data of specific module(s) so any kind of storage should be theoretically possible to use.

> standard feature that runs once the startup DS changes, and which runs exactly once for each commit (that is, not on a per-module basis as a regular change subscription)

Seems like quite a simple thing to implement and may even be required for the custom datastore, we will see.

**Comment by starx1000** [comment]
Thanks!  That is good news. 
Looking forward to it.
