### ISSUE TITLE
ly2: Internal error on big endian

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2392]
Hi,

I get internal error when an application tries to connect to sysrepo after yang module installation on a 32-bit PowerPC system:
 
```
sysrepoctl -i /opt/yang/ietf-interfaces\@2018-02-20.yang -s /opt/yang
bash-4.2# sysrepoctl -l                                                              
[ERR]: Internal error (/opt/dev/sysrepo/src/lyd_mods.c:2092).
sysrepoctl error: Failed to connect (Internal error)
For more details you may try to increase the verbosity up to "-v3".
```
 
I haven't seen this error on x86_64 and i386 architectures.
 
sysrepo version: 2dec6b2263dcca062a3eeca60a249b27da4021cb
libyang version: be51c94825ea2e35fe4312f36f22af641774c893

Thanks!

**Comment by michalvasko** [comment]
I can only guess what is wrong but the printing flags could definitely have caused this problem, so those should be fixed. If you still encounter this problem, I would need some more information.

**Comment by awesomenode** [comment]
I still encounter the internal error issue.
I have done some debugging and found that there is an issue with union in lyd_value:

At lyd_mods.c:2089 the content of `((struct lyd_node_term *)sr_mod)->value` is the following on x86_64:

```
(gdb) p ((struct lyd_node_term *)sr_mod)->value
$6 = {canonical = 0x55555579d2d0 "1", {boolean = 1 '\001', dec64 = 1, int8 = 1 '\001', int16 = 1, int32 = 1, int64 = 1, uint8 = 1 '\001', uint16 = 1, uint32 = 1, uint64 = 1, enum_item = 0x1, bits_items = 0x1, 
    ident = 0x1, target = 0x1, subvalue = 0x1, ptr = 0x1}, realtype = 0x55555579a640}
```

while on PowerPC it is the following:

```
(gdb) p ((struct lyd_node_term *)sr_mod)->value       
$7 = {canonical = 0x1003b408 "1", {boolean = 0 '\000', dec64 = 1, int8 = 0 '\000', int16 = 0, int32 = 0, int64 = 1, uint8 = 0 '\000', uint16 = 0, uint32 = 0, uint64 = 1, enum_item = 0x0, bits_items = 0x0, 
    ident = 0x0, target = 0x0, subvalue = 0x0, ptr = 0x0}, realtype = 0x10039750}
```

According to canonical and 64 bit integers its value is 1 in both cases, but on big endian it will be zero when reading it as uint32 from the union.

libyang version: 65591ab33ea3dba5edf32b4c346b7e2828187a8e
sysrepo version: 3471670aaa1e6470f34d955e0b831f112c03017b

**Comment by michalvasko** [comment]
That is quite interesting because the value is `uint32`. Can you please test [this patch](https://github.com/sysrepo/sysrepo/files/6297104/integer.patch.txt) for latest *libyang*?

**Comment by awesomenode** [comment]
Hi Michal,

I could not apply the patch on the latest libyang2 version because plugins_types_integer.c is missing on it.
But the patch solved the issue on the version I tested previously (65591ab33ea3dba5edf32b4c346b7e2828187a8e).

**Comment by michalvasko** [comment]
Yeah, sorry, the development is quite active currently. But I have committed the fix so it should work now.

**Comment by awesomenode** [comment]
It works on the latest libyang2 version. Thanks!
