### ISSUE TITLE
Cannot create duplicate leaf-list node on notifications

### ISSUE THREAD

**Issue by namphuonghoanges** [sysrepo/sysrepo#2393]
Hi,
I'm using sysrepo: 1.4.122 and libyang: 1.0.225. 
Yang model o-ran-performance-management.yang (v4)
which having leaf-list 
`
leaf-list frequeny-table {
        type uint32;
        description
          "frequency-table for the measurment-object are included per bin.
           The configuration parameters for this frequency-table are defined
           by bin-count, lower-bound and upper-bound";
      }
`
With this list when i using the callback to get the value, i can get it with duplicate value node but when i create a notification i cannot create node with duplicate value. How can i fix this? 
I'm using the lyd_new_path for both case. 
Fail with notification:
![image](https://user-images.githubusercontent.com/82130295/113959565-528fed80-984d-11eb-920d-fee6e360aebd.png)
Code snipping:
![image](https://user-images.githubusercontent.com/82130295/113959713-8b2fc700-984d-11eb-9b9b-f36367a90522.png)
![image](https://user-images.githubusercontent.com/82130295/113959863-c7fbbe00-984d-11eb-838e-9bca5276d01c.png)

**Comment by namphuonghoanges** [comment]
This is what i got when i using get
![image](https://user-images.githubusercontent.com/82130295/113967617-88d46980-985b-11eb-8710-5f11df4c20c3.png)
This is what i got in the notification: 
![image](https://user-images.githubusercontent.com/82130295/113967952-58d99600-985c-11eb-9231-a26025415807.png)
and the error:
![image](https://user-images.githubusercontent.com/82130295/113968094-9b9b6e00-985c-11eb-9f53-b5a9829b7f7d.png)

**Comment by michalvasko** [comment]
The problem was in *libyang* but there is no need to create duplicate issues. I have added a similar use-case to *sysrepo* tests, just in case.

**Comment by namphuonghoanges** [comment]
Thank you. I will waiting for libyang update. XD
