### ISSUE TITLE
Question about sr_get_items limits

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2394]
Hi,

I have a question about the sr_get_items limits. What is the intended maximum for the xpath parameter length?

I get this error from libyang: ‘XPath expression cannot be longer than 65535d characters’.

However I get this error even if the length is less.

Libyang version: 1.0.229
Sysrepo version: 1.4.126

Thanks

**Comment by michalvasko** [comment]
As you said, the limit is imposed by *libyang*, not *sysrepo*, so there is probably something appended internally. What exactly is the problem here?

**Comment by awesomenode** [comment]
The question is the guaranteed length which should work in the sysrepo API considering how the libyang is being used internally in the sysrepo now or later. Thanks

**Comment by michalvasko** [comment]
The only reason the limit is there so that there is not a crash it is exceeded, I cannot imagine a real use-case where you use expressions longer than a few hundred characters, at most. You can pick the actual limit by yourself, 60k for example.

**Comment by awesomenode** [comment]
I didn't narrow down but 45k failed as well with the same message. We would like to retrieve data for complex data visualization and found that if the xpaths are combined in a single expression (with union operator) then it boosts the performance.

**Comment by michalvasko** [comment]
Okay, I see... Could you at least provide the backtrace for the error? Because briefly looking at the code, I do not see any processing of the `xpath` and it should go directly to *libyang*, so there may be some bug somewhere. Also, the limit can be increased to UINT32_MAX without much trouble in *libyang* version 2 so if you really have a use-case for it, I suppose it can be changed.

**Comment by awesomenode** [comment]
The root cause seems to be that lyd_find_path converts the xpath before calling lyxp_eval. The elements are extended with additional namespace. So it is not how it is being used in sysrepo.

**Comment by michalvasko** [comment]
Hm, you are right. In any case, *libyang* version 2 does not do anything like that so with it should work reliably.
