### ISSUE TITLE
Once handling event timed out, it always gets "previous event "(null)" with ID 6 was not processed."

### ISSUE THREAD

**Issue by ryanking8215** [sysrepo/sysrepo#2396]
I meet an issue that the netopeer2-server says that "Callback event "rpc" with ID 6 processing timed out.", by the time our application restarts (I don't know it is before or after the error log, our application log is lost),  After our application starts run, it subscribes the module change, but netopeer2-server always says "Locking subscription of "/ietf-netconf:get" failed, previous event "(null)" with ID 6 was not processed." for each request and It is never recovered.

How can I do to recover the states?

**Comment by michalvasko** [comment]
What *sysrepo*/*netopeer2-server* version are you using? You should not have these kinds of problems with the latest release so I assume you are using something older.

**Comment by ryanking8215** [comment]
Yes, you are right, I use the old one that sysrepo is v1.4.66

**Comment by michalvasko** [comment]
Then like I said, update to the latest release to fix.

**Comment by ryanking8215** [comment]
Is it possible that backports to the 1.4.66 which runs on our production. 
I am afraid that there will be risks that update to the latest release.

Very appreciated that if you could provide some suggestion.

**Comment by michalvasko** [comment]
I do not think it is that easy, this was most likely fixed by a major lock refactoring that was released in 1.4.104, I do not think it is possible to cherry-pick such a big change.

**Comment by ryanking8215** [comment]
OK, thanks. 
I will consider that update to the latest version.

**Comment by ryanking8215** [comment]
Sorry, I reopen it because I found new condition that I am not sure whether it exists in the latest version or not.

It might be the system time changing causes event timed out. 
I found that the system was rebooted rather than application restarted. There is no RTC (hardware real time clock) on our device. It syncs the time depends on NTP after connecting to internet. 
According to the logs, system time was 2021-04-01 on very beginning and became to 2021-04-16 after got internet accessing, which might cause pthread_cond_timedwait being timed out, and there was always a pending event to process.

My question is this kind of issue still exists in latest version as my opinion, but I am not sure if it can recover or not in latest verion.

**Comment by ryanking8215** [comment]
Let me simplified the questions.
There are 2 issue here.
1. event might be timed out.
2. timed out event becomes a pending event.

The latest version solves issue 1 or 2, or both?

**Comment by michalvasko** [comment]
To my knowledge, there are no situations when any error condition would block further events and general functioning in the latest version. So to answer, it should solve both your issues.

**Comment by ryanking8215** [comment]
OK, thanks.
