### ISSUE TITLE
req_xpath argument in sr_oper_get_items_subscribe() callback

### ISSUE THREAD

**Issue by iljatab** [sysrepo/sysrepo#2398]
$ yanglint --version
yanglint SO 1.10.1

$ sysrepoctl --version
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.100 (SO v5.6.16)

$ netopeer2-server -V
netopeer2-server 1.1.52

Hello Michal,

We have some issue with operational state callback, namely with `req_xpath` argument.

Say, we use openconfig-interfaces.yang model and use `sr_oper_get_items_subscribe()` to subscribe for some path components:
```
/openconfig-interfaces:interfaces/interface/state
/openconfig-interfaces:interfaces/interface/state/counters
/openconfig-interfaces:interfaces/interface/subinterfaces/subinterface/state
...
```

Then, when running `get --filter-xpath=/openconfig-interfaces:interfaces/interface[name='eth0']` from netopeer2-cli the end result looks as expected.

However, our registered operational state callback is always called with `req_xpath == /openconfig-interfaces:*`, eventhough the request asked for just eth0.
This of course completely ruins all optimization attempts we implemented, based on `req_xpath` value.
The issue happens also with other models.
I remember it definitely working earlier...
Did I miss something, could you advise?

Ilja.

**Comment by michalvasko** [comment]
Yes, there was a fix implemented for incorrect `get` results that cause its performance to degrade because of the change you observed. The only advice I can give you is not to use `get`, it is an obsolete operation whose implementation is unnecessarily complex in the NMDA. You should be using `get-data` instead.

**Comment by iljatab** [comment]
Yes, with get-data it works.
However it is usually not under our control - it is client software which decides what operations to use.
But anyway thanks for clarification!
