### ISSUE TITLE
implementation in sysrepo for callback mechanism 

### ISSUE THREAD

**Issue by ashishsaxenahsc** [sysrepo/sysrepo#2399]
Hi Michal,

As per our observation in  sysrepo, callback mechanism for subscribing to changes in datastore with  sr_module_change_subscribe API is implemented in  in a sequential manner , i.e, the changes done are queued and then processed by sysrepo sequentially. Is our observation correct , and the callback changes are processed sequentially ? How will sysrepo behave when same callback is getting called from 2 different places at same time ?   

Thanks and Regards,
Ashish

**Comment by jktjkt** [comment]
This is explained in the [very first page of the documentation](https://netopeer.liberouter.org/doc/sysrepo/master/html/#threads).

**Comment by michalvasko** [comment]
Yes, the basic information is included in the documentation but some details can be added. *sysrepo* will never call a single module change callback concurrently because performing changes in data is a critical section. Unless, of course, you register one callback for changes of 2 modules.
