### ISSUE TITLE
ietf-system fails to parse in netopeer2

### ISSUE THREAD

**Issue by immibis** [sysrepo/sysrepo#240]
After installing the ietf-system module, it is not visible in netopeer2.

This is printed when starting netopeer2-server with `-d -v3`:

{code}
netopeer2-server[9843]: (cl_request_process:401) Sending get-schema request.
netopeer2-server[9843]: (cl_request_process:423) get-schema request sent, waiting for response.
netopeer2-server[9843]: (cl_request_process:445) get-schema response received, processing.
netopeer2-server[9843]: Invalid attribute definition, "=" expected.
netopeer2-server[9843]: Module parsing failed.
netopeer2-server[9843]: Getting ietf-system (2014-08-06) schema from sysrepo failed, data from this module won't be available.
{code}

**Comment by rastislavszabo** [comment]
Fixed in libyang (https://github.com/CESNET/libyang/commit/952a72592e0354e66962efb935fa21bac49e1495)
