### ISSUE TITLE
Feature Req: Clarity in syslog messages

### ISSUE THREAD

**Issue by esend7881** [sysrepo/sysrepo#2402]
When I run an install on a model that already exists, I get an error that looks like this:

```.sh
$ sysrepoctl --apply --install=/opt/yang/mymodel.yang --verbosity=4
[INF]: Scheduled changes not applied because of other existing connections.
[INF]: Connection 123 created.
[ERR]: Module "mymodel" not scheduled for deletion.
[ERR]: Module "mymodel" is already in sysrepo.
sysrepoctl error: Cannot apply changes because of existing connections
```

This is fine, but I was wondering if an additional statement could be added to this message:
```.sh
$ sysrepoctl --apply --install=/opt/yang/mymodel.yang --verbosity=4
[INF]: Scheduled changes not applied because of other existing connections.
[INF]: Connection 123 created.
[ERR]: Module "mymodel" not scheduled for deletion.
[ERR]: Module "mymodel" is already in sysrepo.
sysrepoctl error: Cannot apply changes because of existing connections
***[INF] The changes will be applied next time netopeer is restarted.***
```
or if the change won't be implemented:
```.sh
$ sysrepoctl --apply --install=/opt/yang/mymodel.yang --verbosity=4
[INF]: Scheduled changes not applied because of other existing connections.
[INF]: Connection 123 created.
[ERR]: Module "mymodel" not scheduled for deletion.
[ERR]: Module "mymodel" is already in sysrepo.
sysrepoctl error: Cannot apply changes because of existing connections
***[INF] No change related to this will be applied even at next netopeer restart.***
```

This will help bring some clarity as I update models while netopeer is online. 

Also, I added `***` around the messages here, but no need for that in the actual syslog. In short, could one of the following messages be logged, depending on the state of the system:

- [INF] The changes will be applied next time netopeer server is restarted, before connections are established.
- [INF] No change related to this will be applied, even at next netopeer server restart.
- [INF] The changes are now applied.

**Comment by michalvasko** [comment]
> [INF] The changes will be applied next time netopeer server is restarted, before connections are established.

I do not see the point of this message because it is always true. Also, *sysrepo* does not have anything to do with *netopeer2* (does not know about it, strictly speaking).

> [INF] No change related to this will be applied, even at next netopeer server restart.

I am not even sure what the meaning of this message is supposed to be. I think you are better off running `sysrepoctl -l` where it also shows you all the scheduled changes so you can determine for yourself whether something "related to this" is scheduled or not.

> [INF] The changes are now applied.

This message is already present, in 2 variants: `Scheduled changes applied.` and `No scheduled changes.`.

**Comment by esend7881** [comment]
Thanks for the clarification on that. I think just getting a message that definitively states the action would be helpful, however now that you revealed the top statement is always true, I feel a bit better now!
