### ISSUE TITLE
Not able to fill data for keyless list in sysrepo

### ISSUE THREAD

**Issue by sandhyak88** [sysrepo/sysrepo#2404]
Hello,

I am trying to fill data for keyless list(capabilities) to fill tx/rx-arrays in o-ran-uplane-conf.yang which is reference to o-ran-module-cap.yang. Data to be filled being fetched from json file.

https://github.com/visiontrail/pyang_parser/blob/0c1382971ebeec22ab8b338a8e179fe9d71c9ecf/oran_yang/RUSpecificModels/Operations/o-ran-uplane-conf.yang 
(Not able to get reference link for o-ran-module-cap.yang)

I tried referencing existing reference #2192  and using logic similar to below one.
```C++
for (auto& e : root.get_child("capabilities"))
{
    struct lyd_node *capList = lyd_new(uList, NULL, capName.c_str());
    lyd_new_leaf(capList, NULL, max-supported-frequency-dl, e.second.get<std::string>(max-supported-frequency-dl).c_str());
    lyd_new_leaf(capList, NULL, min-supported-frequency-dl, e.second.get<std::string>(min-supported-frequency-dl).c_str());
    lyd_new_leaf(capList, NULL, max-supported-bandwidth-dl, e.second.get<std::string>(max-supported-bandwidth-dl).c_str());
    lyd_new_leaf(capList, NULL, max-num-carriers-dl, e.second.get<std::string>(max-num-carriers-dl).c_str());
    lyd_new_leaf(capList, NULL, max-carrier-bandwidth-dl, e.second.get<std::string>(max-carrier-bandwidth-dl).c_str());
    lyd_new_leaf(capList, NULL, min-carrier-bandwidth-dl, e.second.get<std::string>(min-carrier-bandwidth-dl).c_str());
    lyd_new_leaf(capList, NULL, supported-technology-dl, e.second.get<std::string>(supported-technology-dl).c_str());
}
```
where capName would be updated as capabilities[1],capabilities[2]...

My get-config call doesnt throw any error but data displayed doesnt show "capabilities" at all.
Any idea on what could be going wrong ?

Thanks in advance!!!
Sandhya

**Comment by michalvasko** [comment]
Using this API (`lyd_new()`) you should always specify the node name, nothing else, it does not expect any XPath. So you should just be putting `capabilities` there, it will always create a new instance. But it should definitely throw an error meaning `capList` will be `NULL`, which you should be checking for.
