### ISSUE TITLE
Operational datastore not getting cleared on netopeer2-server restart

### ISSUE THREAD

**Issue by ashishsaxenahsc** [sysrepo/sysrepo#2405]
Hi Michal,

We are getting the following observation on sysrepo. Our application has made a connection with sysrepo and setting values into the datastore , without breaking the connection. When netopeer2-server is restarted, we can still find the values in the operational datastore . Can you please let us know why we are seeing this behavior ?  

Thanks and Regards,
Ashish

**Comment by michalvasko** [comment]
You are saying you have an application that connects to *sysrepo*, sets some data, and while it is continuously running, *netopeer2-server* is restarted and you are wondering why the operational data you have set by your application were not cleared? Well, why should they be cleared? It works as expected.

The configured data "belong" to your application so they will remain in *sysrepo* for as long as the connection to it is maintained. You must understand that *sysrepo* is the central point, the YANG datastore. *netopeer2-server* is just a remote NETCONF interface, it is no "master" in any sense in the architecture.
