### ISSUE TITLE
How to delete all key of a List in single trigger

### ISSUE THREAD

**Issue by pawanmishranitk** [sysrepo/sysrepo#2406]
I am trying to delete full list B using below xpath using  sr_delete_item  API:
/A[id='1']/B[id='*']
 Where B is a list

what should I pass in [ ] instead of * to delete full list.

**Comment by michalvasko** [comment]
You should use `/A[id='1']/B` to delete all instance of `B`.

**Comment by pawanmishranitk** [comment]
is there not a way or special char which we can pass inside [  ] to delete all instance ?

**Comment by michalvasko** [comment]
When deleting data in *sysrepo*, no, there is not. But speaking about generic XPath to select all the instances of `B`, there are many options, you just have to put something there that is true for all the instances. However, wildcards are not supported directly like this.

**Comment by pawanmishranitk** [comment]
ok, Thanks for you quick response.
