### ISSUE TITLE
create error after delete

### ISSUE THREAD

**Issue by xheke** [sysrepo/sysrepo#2409]
Hi Michal,

I found that after delete operation with below xml,   create operation can not perform again with "item already exists" error.

I checked the running DB and confirm the item is removed.

but  "merge" or “replace” operation is fine.

BTW, if  "delete"  the not-exists item, the behavior should be return "error", right? 
Currently,  seems it return OK after run "delete" again. 

```
<oven xmlns="urn:sysrepo:oven"  xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0"  xc:operation="delete"   >
    <turned-on>true</turned-on>
    <temperature>200</temperature>
</oven>
```

```
./sysrepocfg --edit=/mnt/nc.oven.turn.on.xml 
[ERR]: Node "turned-on" to be created already exists.
[ERR]: Applying operation "create" failed.
sysrepocfg error: Failed to merge edit data (Item already exists)
```

**Comment by michalvasko** [comment]
Yeah, this should be fixed now. Duplicate of cesnet/netopeer2#887.

**Comment by xheke** [comment]
Hi Michal, 

May I ask one more question,  netopeer2 currently not support commit. cancel-commit and discard-change,  right?

Thanks for you help  :)

**Comment by michalvasko** [comment]
It does support [commit](https://github.com/CESNET/netopeer2/blob/master/src/main.c#L771) and [discard-changes](https://github.com/CESNET/netopeer2/blob/master/src/main.c#L772) RPCs but not `cancel-commit` because the capability `confirmed-commit` is not supported.

**Comment by xheke** [comment]
I have some concern for "commit" concept. 
From my thought, I think "commit" is confirm "change" to DB, but seems here is just mean call "commit RPC"? 
So any change for sysrepo DB via netopeer2 is accepted immediately, right?

**Comment by michalvasko** [comment]
> From my thought, I think "commit" is confirm "change" to DB, but seems here is just mean call "commit RPC"?
So any change for sysrepo DB via netopeer2 is accepted immediately, right?

Yes, that is correct. Do not use `commit` in *sysrepo* context because it is confusing, that is why it was renamed to `sr_apply_changes()` in the current *sysrepo* and that is the term to use.

**Comment by xheke** [comment]
> But you can use the same concept in NETCONF as well, just change candidate datastore and then execute commit. It is the sysrepo functionality of preparing some changes in a session and then calling sr_apply_changes().

so, this commit is working for candidate datastore, but not for running datastore, right?
when execute commit on candidate datastore, the data will be changed and can be seen in another netopeer-cli session, right?

**Comment by michalvasko** [comment]
Commit works by copying the prepared data in `candidate` to `running`. Read about it in the [RFC](https://tools.ietf.org/html/rfc6241#section-8.3).

**Comment by xheke** [comment]
Thanks Michal, I got it. :)
