### ISSUE TITLE
Previous event "done" with ID was not processed.

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2410]
Hi,

I encountered a lot of similar errors:
`Waiting for subscription of "ietf-interfaces" failed, previous event "done" with ID 403 was not processed.`

They are followed by a done event timeout:
`Callback event "done" with ID 403 processing timed out.`

It seems that a done event was not handled in time due to an error on my side (events are handled on custom thread with SR_SUBSCR_NO_THREAD).
After it all change attempts will fail with the above error message.

I attached an application to reproduce similar error.
[reprod.zip](https://github.com/sysrepo/sysrepo/files/6432779/reprod.zip)

This example creates a done only subscription, while its events are not processed and it causes a done timeout.
After the subscription is deleted all further `sr_apply_chages()` fails:

```
$ ./main 
[INF]: Applying scheduled changes.
[INF]: Module "ietf-interfaces" was installed.
[INF]: Scheduled changes applied.
[INF]: Connection 3 created.
[INF]: Session 1 (user "dev", CID 3) created.
enable config data
done only subscribe
create eth0
[INF]: Published event "change" "ietf-interfaces" with ID 1 priority 0 for 1 subscribers.
[INF]: Processing "ietf-interfaces" "change" event with ID 1 priority 0 (remaining 1 subscribers).
[INF]: Successful processing of "change" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: Event "change" with ID 1 priority 0 succeeded.
[INF]: Published event "done" "ietf-interfaces" with ID 1 priority 0 for 2 subscribers.
[INF]: Processing "ietf-interfaces" "done" event with ID 1 priority 0 (remaining 2 subscribers).
[INF]: Successful processing of "done" event with ID 1 priority 0 (remaining 1 subscribers).
[ERR]: Callback event "done" with ID 1 processing timed out.
unsubscribe
create eth1
[INF]: Session 4 (user "dev", CID 3) created.
[ERR]: Waiting for subscription of "ietf-interfaces" failed, previous event "done" with ID 1 was not processed.
sr_apply_changes failed, rc=13
```

Installed YANG modules:

```
iana-if-type               | 2018-07-03
ietf-interfaces            | 2018-02-20    
```

sysrepo version: 1.4.133
libyang version: 1.0.232

Thanks!

**Comment by michalvasko** [comment]
Should work now. The added test also reproduced a more serious subscription locking issue that should be fixed as well.

**Comment by awesomenode** [comment]
I havent't met this error on fixed version, thanks!
