### ISSUE TITLE
Timeout error when get nodes in a list

### ISSUE THREAD

**Issue by namphuonghoanges** [sysrepo/sysrepo#2411]
Hi,
I'm using sysrepo 1.4.122, libyang 1.0.230. Now, I'm working with module ietf-hardware and there are a lot of RO nodes in lists and register callback by: 
![image](https://user-images.githubusercontent.com/82130295/117393741-fa690b80-af1e-11eb-88ae-d02446dffbe9.png)
when I try to run this I got this error:
![image](https://user-images.githubusercontent.com/82130295/117393822-27b5b980-af1f-11eb-9aa2-443a071b7334.png)
and the netopeer2-server have this log:
![image](https://user-images.githubusercontent.com/82130295/117399061-dc54d880-af29-11eb-90b4-4c8179a3b687.png)
![image](https://user-images.githubusercontent.com/82130295/117393883-44ea8800-af1f-11eb-8f06-5306f66e1d1e.png)
All callback return SR_ERR_OK and log return no error so I think this because of timeout value while getting value from operation callback, so how can I modify those timeout? 
I trying to modify the timeout in rpc get by --rpc-timeout but it still got this error

**Comment by namphuonghoanges** [comment]
I found that that is a limited timeout for processing RPC in sysrepo. This defined by this macro: SR_RPC_CB_TIMEOUT. I think this is a bug

**Comment by michalvasko** [comment]
Use the `-t` parameter to set a higher timeout.

**Comment by namphuonghoanges** [comment]
Thank you :D
