### ISSUE TITLE
sr_set_item is not working as expected . throwing path Error

### ISSUE THREAD

**Issue by HarminderSingh9995** [sysrepo/sysrepo#2412]
input.xpath = xpath;
    input.type = SR_ENUM_T ;
    input.dflt = 0;
    input.data.string_val = value;

    /* set the value */
    //rc = sr_set_item_str(session, xpath, value, NULL, 0);
    rc = sr_set_item(session, xpath, &input, 0);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }

    /* apply the change */
    rc = sr_apply_changes(session, 0, 1);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }
 Error

path /o-ran-sync:sync/ptp-config/ptp-profileaction value G_8275_1 type 10
VALUE :G_8275_1
[ERR]: Unexpected character(s) '⚌' (⚌\D). (path: /o-ran-sync:sync/ptp-config/ptp-profile)
[ERR]: Edit was discarded.

**Comment by michalvasko** [comment]
You would have to provide the actual `xpath` value before I could tell you what is wrong with it.

**Comment by HarminderSingh9995** [comment]
./sr_set_item_example /o-ran-sync:sync/ptp-config/ptp-profile G_8275_1

trying with this command .
