### ISSUE TITLE
What about RFC 8342 supports?

### ISSUE THREAD

**Issue by myonlystarWang** [sysrepo/sysrepo#2413]
Hi michal,
      I've been looking at the RFC8342[https://datatracker.ietf.org/doc/html/rfc8342](url)
      Have you seen these?
      Will the new datastores and arch be supported in _sysrepo_ in the future?

**Comment by michalvasko** [comment]
It is already.

**Comment by myonlystarWang** [comment]
Hi michal,
     I'm glad to hear that.But in my previous study of sysrepo's documentation, I only looked at three datastores: <startup> <running>  <candidate>.Which _sysrepo_ release version was implemented the other datastores which described by the RFC8342? Such as <intended> <dynamic> <learned> ,etc.
     If I have any misunderstanding of the RFC, please correct me in time.

**Comment by michalvasko** [comment]
I cannot tell you exactly when [`<operational>`](https://github.com/sysrepo/sysrepo/blob/master/src/sysrepo.h#L203) was added, but it was quite some time ago.

**Comment by myonlystarWang** [comment]
Hi michal,
     I read the NDMA architecture in the protocol，I also looked at the _sysrepo_ code(v1.4.58).
     As you said, this has been done.This issue can be closed now.
     Thanks again for your answer!
