### ISSUE TITLE
System function call failed with Connection with CID 2 is dead

### ISSUE THREAD

**Issue by vadim-platonov** [sysrepo/sysrepo#2414]
In our auto tests we sometimes catch strange issue.
Process B starts and opens sysrepo connection and almost simultaneously close sysrepo connection.
In that moment process A starts and opens sysrepo connection and failed with message:

process A [195]: [WRN]: Connection with CID 2 is dead.
process A [195]: [ERR]: unlink() failed (No such file or directory).
process A [195]: sysrepo exception: System function call failed error code: 3

I consider the problem is that CID 2 is closed from process B and almost simultaneously tested in Process A.

**Comment by michalvasko** [comment]
> I consider the problem is that CID 2 is closed from process B and almost simultaneously tested in Process A.

It seems that way, what *sysrepo* version are you using? It could have been fixed by e5c265f42f188875e59812730096e674fae15e61. I tried reproducing it with 2 processes but did not succeed.

**Comment by michalvasko** [comment]
So the data race should be harmless and just need to be handled, I think, which it is now.

**Comment by vadim-platonov** [comment]
Thanks, works.
