### ISSUE TITLE
Validation of xpath

### ISSUE THREAD

**Issue by ashishsaxenahsc** [sysrepo/sysrepo#2415]
Hi Michal,

Is there any API or method in sysrepo code which can be used to validate whether a particular xpath provided is valid or not.

Thanks and Regards,
Ashish

**Comment by michalvasko** [comment]
What XPath exactly do you want to validate? But I would suggest directly calling whatever *sysrepo* API function you want and handle errors. If the XPath is not meant to be used in *sysrepo* API, you can probably use `lyd_find_path()` in *libyang* for the best validation although it includes evaluation as well.
