### ISSUE TITLE
edit-config failed due to "missing required element" or "unknown element"

### ISSUE THREAD

**Issue by molisado** [sysrepo/sysrepo#2418]
# Background

Scenario: use **netopeer2-cli** to perform `edit-config` with *o-ran-uplane-conf* YANG data XML file.

The content below is the simplified *o-ran-uplane-conf.yang*:

```
module o-ran-uplane-conf {
  import o-ran-compression-factors {
    prefix "cf";
  }

  grouping uplane-conf-group {
    list low-level-tx-endpoints {
      key "name";
      leaf name {
        type leafref {
          path "/user-plane-configuration/static-low-level-tx-endpoints/name";
          require-instance false;
        }
        mandatory true;
      }
      leaf cp-type { ... }
      leaf cp-length { ... }
      leaf cp-length-other { ... }
      leaf offset-to-absolute-frequency-center { ... }
      container compression {
        presence "This container shall exists to avoid missaligned compression methods between devices";
        uses cf:compression-details;
      }
      container e-axcid { ... }
    }
  }

  container user-plane-configuration {
    uses uplane-conf-group;
  }
}
```

And the content below is the simplified *o-ran-compression-factors.yang*, which is referenced by *o-ran-uplane-conf*:

```
module o-ran-compression-factors {
  grouping compression-params {
    leaf compression-type {
      type enumeration {
        enum STATIC { ... }
        enum DYNAMIC { ... }
      }
      mandatory true;
    }
    ...
  }

  grouping compression-details {
    ...
    uses compression-params;
  }
}
```

The complete YANG module content can be found below:
[o-ran-uplane-conf.txt](https://github.com/sysrepo/sysrepo/files/6490939/o-ran-uplane-conf.txt)
[o-ran-compression-factors.txt](https://github.com/sysrepo/sysrepo/files/6490942/o-ran-compression-factors.txt)

# Test Case 1: w/o `compression` container, using `master` branch

The content below is the XML file used for edit-config `--content` parameter:
```
<user-plane-configuration xmlns="urn:o-ran:uplane-conf:1.0">
  <low-level-tx-endpoints>
    <name>tx-endpoint-1</name>
    <cp-length>10</cp-length>
    <cp-length-other>10</cp-length-other>
    <offset-to-absolute-frequency-center>10</offset-to-absolute-frequency-center>
    <e-axcid>
      <o-du-port-bitmask>1</o-du-port-bitmask>
      <band-sector-bitmask>1</band-sector-bitmask>
      <ccid-bitmask>1</ccid-bitmask>
      <ru-port-bitmask>1</ru-port-bitmask>
      <eaxc-id>1</eaxc-id>
    </e-axcid>
  </low-level-tx-endpoints>
</user-plane-configuration>
```

The messages of netopeer2-cli:
```
> edit-config --target running --config=[XML path]
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	path:     /o-ran-uplane-conf:user-plane-configuration/low-level-rx-endpoints[name='rx-endpoint-1']/compression
	message:  Missing required element "compression-type" in "compression".
```

The message of netopeer2-server:
```
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" "/ietf-netconf:edit-config" with ID 6 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 6 priority 0 (remaining 1 subscribers).
[INF]: NP: edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[ERR]: LY: Missing required element "compression-type" in "compression". (/o-ran-uplane-conf:user-plane-configuration/low-level-rx-endpoints[name='rx-endpoint-1']/compression)
[ERR]: SR: Missing required element "compression-type" in "compression".
[ERR]: SR: Validation failed.
[INF]: SR: Failed processing of "rpc" event with ID 6 priority 0 (remaining 1 subscribers).
[ERR]: SR: Missing required element "compression-type" in "compression".
[WRN]: SR: Event "rpc" with ID 6 priority 0 failed (Validation failed).
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 2: thread 4 event new RPC.
[INF]: NP: Session 2: thread 4 event reply error.
```

The git version of each Netopeer2 component is as followed:
Component | Commit ID
-------- | -----------------------------------------------------
libyang | 8e9f87949974c7b2c6dc5e830c0e78e4160fbc50
libnetconf2 | fa9e08da07daf5122c8a03501020463d18fec81c
sysrepo | 4bfd1f9236c2c6f0fe44fa01f471233e623aa7dc
Netopeer2 | 86910ada6b2b9d816bc7046888fcb6a130d46241

According to the definition in [YANG 1.1 spec. (RFC 7950)](https://datatracker.ietf.org/doc/html/rfc7950#section-3), page 14, "mandatory node", 
a container with a "presence" statement can never be a mandatory node, 
which is the case of the `"compression"` container in o-ran-uplane-conf.yang.
So why does this **missing required element "compression-type" in "compression"** error exist?

# Test Case 2: w/o `compression` container, using `devel` branch

After studying some previous issues, I guess it might be worth to try the devel branch:
Component | Commit ID
-------- | -----------------------------------------------------
libyang | 1cb7fa44e01c1caa79f63a7f7cca94f5ff587b57
libnetconf2 | 6efbb026311562f8e58e45a31604ca8970b2458e
sysrepo | d8ff93bdb8f9eecbfe5d2587c3d3ea7f7c3b029f
Netopeer2 | 732bc90b960bfa3f4d8dd7d6f072a0794cb3f063

And the error did disappear!
But that is not enough, so here comes the next test case.

# Test Case 3: w/ `compression` container, using `devel` branch

The git version of each Netopeer2 component is the same as test case 2.
The content below is the XML file used for edit-config `--content` parameter:
```
<user-plane-configuration xmlns="urn:o-ran:uplane-conf:1.0">
  <low-level-tx-endpoints>
    <name>tx-endpoint-1</name>
    <cp-length>10</cp-length>
    <cp-length-other>10</cp-length-other>
    <offset-to-absolute-frequency-center>10</offset-to-absolute-frequency-center>
    <compression>
      <cf:compression-type xmlns:cf="urn:o-ran:compression-factors:1.0">STATIC</cf:compression-type>
    </compression>
    <e-axcid>
      <o-du-port-bitmask>1</o-du-port-bitmask>
      <band-sector-bitmask>1</band-sector-bitmask>
      <ccid-bitmask>1</ccid-bitmask>
      <ru-port-bitmask>1</ru-port-bitmask>
      <eaxc-id>1</eaxc-id>
    </e-axcid>
  </low-level-tx-endpoints>
</user-plane-configuration>
```

The messages of netopeer2-cli:
```
> edit-config --target running --config=/home/k200/YANG/data/o-ran-uplane-conf_config_endpoint.xml
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	path:     /o-ran-uplane-conf:user-plane-configuration/low-level-tx-endpoints[name='tx-endpoint-1']/compression
	message:  Unknown element "compression-type".
```

The message of netopeer2-server:
```
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" "/ietf-netconf:edit-config" with ID 12 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 12 priority 0 (remaining 1 subscribers).
[INF]: NP: edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
[ERR]: LY: Unknown element "compression-type". (/o-ran-uplane-conf:user-plane-configuration/low-level-tx-endpoints[name='tx-endpoint-1']/compression)
[INF]: SR: Failed processing of "rpc" event with ID 12 priority 0 (remaining 1 subscribers).
[ERR]: SR: Unknown element "compression-type".
[WRN]: SR: Event "rpc" with ID 12 priority 0 failed (libyang error).
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 2: thread 0 event new RPC.
[INF]: NP: Session 2: thread 0 event reply error.
```

# Summary of the question

1. Missing required element
    - Is it really a bug of mandatory-node processing in the `master` branch and is solved in the `devel` branch? (which means my perception of "mandatory node" is correct)
    - Or is it just an coincidence and has nothing to do with mandatory-node processing? (which means my perception is incorrect) So what is the cause?
2. Unknown element
    - Why is libyang not able to identify compression/compression-type?

**Comment by michalvasko** [comment]
1. Yes, it would seem that way.
2. Because it is in incorrect namespace. The namespace of `compression-type` is the same as `compression`, nodes placed from groupings inherit the namespace of the `uses`.

**Comment by molisado** [comment]
> 2. Because it is in incorrect namespace. The namespace of `compression-type` is the same as `compression`, nodes placed from groupings inherit the namespace of the `uses`.

Thanks for your reply. It really solved my misunderstanding of the spec.
