### ISSUE TITLE
Shm file permissions gets invalid during module install

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2421]
Hi,

I ran into permission denied errors on YANG module installation.
I found that it is caued by `sr_shmmain_check_data_files()` at the following lines:

```
        if (perm == cur_perm) {
            cur_perm = 0;
        } else {
            cur_perm = perm;
        }
```

It occurs twice, for running and operational files.
When permissions are equal but owner or group is going to be changed, the permissions will be set to zero which will cause permission denied errors later.
Changing cur_perm to -1 instead of zero solves the issue.

libyang version: 1.0.233
sysrepo version: 1.4.134

Thanks!

**Comment by michalvasko** [comment]
Right, thanks, should be fixed.

**Comment by awesomenode** [comment]
It works now, thanks!
