### ISSUE TITLE
Licence change - contributor agreement

### ISSUE THREAD

**Issue by michalvasko** [sysrepo/sysrepo#2422]
Since its release, the Sysrepo project has used the Apache2.0 license. The Sysrepo project is dependent on, or often used with several other projects:

Netopeer2 (https://github.com/CESNET/Netopeer2)
Libyang (https://github.com/CESNET/libyang)
Libnetconf2 (https://github.com/CESNET/libnetconf2)

All of these are released using the BSD 3 Clause License and for simplicity, we would like to align the Sysrepo license. The proposal is that future releases of Sysrepo would be changed to the BSD 3 Clause license, and the Apache 2.0 license would no longer be used.

In order to do this, we require the approval of all contributors. There are still 4 who we have not managed to contact so please reply here, thank you.

@imiller0 @pfeige @sriramkandukuri @brchiu

**Comment by imiller0** [comment]
Changing to the BSD 3-clause license is fine with me.
Thanks!

**Comment by sriramkandukuri** [comment]
Its fine with me.

Thanks,
Sriram.K
