### ISSUE TITLE
libyang2: sr_session_get_orig_name() returns NULL in diff check callback

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2423]
Hi!

When using the libyang2 version of sysrepo I have an issue determining the original user
of the session from the diff check callback.

On the devel branch the sr_session_get_event_user() function correctly returns the
original user who initiated the session, but when I try to do it on the libyang2 version
using sr_session_set_orig_name(), sr_session_get_orig_name() will return NULL.

(Apparently for the orig data to be passed, a shared mem pointer should be passed to
_sr_session_start() in the sr_changes_notify_store() function, but that parameter is
NULL.)

My question is, how to achieve the same functionality of the sr_session_get_event_user()
function in the diff check callback function?

Thanks!

**Comment by michalvasko** [comment]
Right, that one callback was not working as it was supposed to, it should now. For more information about how this new feature (`orig` is meant to be short for originator) is used in *netopeer2-server*, look into [README](https://github.com/CESNET/netopeer2/tree/libyang2#sysrepo-callbacks).
