### ISSUE TITLE
List node with multiple keys in sr_oper_get_items_subscribe parameter "path" will cause assert error.

### ISSUE THREAD

**Issue by JLworkbook** [sysrepo/sysrepo#2424]
Hello,

When trying to register the path "_/openconfig-network-instance:network-instances/network-instance/protocols/protocol[identifier='OSPF']/state_" using sr_oper_get_items_subscribe, it will pop out an assert error.

The node "_protocol_" has two keys, "_identifier_" and "_name_".

Look at the code, the function "_sr_xpath_next_predicate_" in "_common.c_"
```
if (has_predicate) {
  *has_predicate = (ptr[0] && (ptr[0] + 1 == '[')) ? 1 : 0;
}
```

Should it be "`(ptr[1] == '[')`" rather than "`(ptr[0] + 1 == '[')`" ?

Please help to check it.
Thanks a lot.

Version: sysrepo 1.4.70

**Comment by michalvasko** [comment]
Of course, the current code does not make sense, thanks.

**Comment by JLworkbook** [comment]
Thanks.
