### ISSUE TITLE
Which path sr_get_* functions should be used, data path or schema path ?

### ISSUE THREAD

**Issue by JLworkbook** [sysrepo/sysrepo#2425]
Hello,

When using functions such as `sr_get_data` or `sr_get_items`, we pass the `"/module-name:container/container2/augment-module:aug-cont/aug-list[aug-list-key='value']"` as paremeter `"xpath"` or `"path"`, it pop out `'Schema node "ip" not found'`.

Look at the code, both functions call `sr_shmmod_modinfo_collect_xpath`, in which `lys_xpath_atomize` is be called.
It seems that `lys_xpath_atomize` should use schema path according to the document. 
So if `sr_get_*` use data path, it may pop out some unexpected error message.

But I may prefer use data path for `sr_get_*`, intuitively.

Should `sr_get_*` functions just use schema path ? 
Or before calling `lys_xpath_atomize`, does the parameter `"path"` have to be changed to schema path first ? 

Please help to clarify it.
Thanks a lot.

**Comment by michalvasko** [comment]
For all *sysrepo* functions you should always use data path so whatever the problem you have encountered, it has nothing to do with the format of the path. But I am not able to help you at all because you do not even have `ip` node in the path you are using. You must provide a way to reproduce it.

**Comment by JLworkbook** [comment]
The example YANG module are below three modules.
```
ietf-interfaces@2018-02-20.yang
ietf-ip@2018-02-22.yang
iana-if-type@2020-07-13.yang
```

The reproduce code is as follows.
```
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "libyang/libyang.h"
#include "sysrepo.h"

int main ()
{
  sr_conn_ctx_t *connection = NULL;
  sr_session_ctx_t *session = NULL;
  const char *features[1] = {"if-mib"};
  struct lyd_node *data = NULL;

  /* Install module */
  sr_connect(0, &connection);
  sr_session_start(connection, SR_DS_RUNNING, &session);
  sr_install_module(connection, "./ietf-interfaces.yang", ".", features, 1);
  sr_install_module(connection, "./ietf-ip.yang", ".", NULL, 0);
  sr_install_module(connection, "./iana-if-type.yang", ".", NULL, 0);
  sr_disconnect(connection);

  sr_connect(0, &connection);
  sr_session_start(connection, SR_DS_RUNNING, &session);

  /* Set basic data */
  sr_set_item_str(session, "/ietf-interfaces:interfaces/interface[name='0/1']", NULL, NULL, 0);
  sr_set_item_str(session, "/ietf-interfaces:interfaces/interface[name='0/1']/type", "iana-if-type:ethernetCsmacd", NULL, 0);
  sr_set_item_str(session, "/ietf-interfaces:interfaces/interface[name='0/1']/ietf-ip:ipv4/address[ip='1.1.1.1']", NULL, NULL, 0);
  sr_set_item_str(session, "/ietf-interfaces:interfaces/interface[name='0/1']/ietf-ip:ipv4/address[ip='1.1.1.1']/prefix-length", "24", NULL, 0);
  sr_apply_changes(session, 0, 0);

  // This line will pop out: Schema node 'ip' not found
  sr_get_data(session, "/ietf-interfaces:interfaces/interface[name='0/1']/ietf-ip:ipv4/address[ip='1.1.1.1']/ip", 0, 0, SR_OPER_DEFAULT, &data);

  // This line will not pop out any error message
  //sr_get_data(session, "/ietf-interfaces:interfaces/interface[name='0/1']/ietf-ip:ipv4/ietf-ip:address[ietf-ip:ip='1.1.1.1']/ietf-ip:ip", 0, 0, SR_OPER_DEFAULT, &data);

  sr_disconnect(connection);

  return 0;
}
```

Version:
libyang: devel (latest)
sysrepo: devel (latest)

**Comment by michalvasko** [comment]
Thanks for the nice example. And you were right about the root of the problem except I think it was intentional because for most XPaths it would still work except possibly print some errors, just like in your case. However, I have fixed it so that no errors should be printed and it should work for all common XPaths. Note that because of the transformation it can never work for all the XPaths. But it is no longer needed in the new version based on *libyang2* so there it should be completely fixed.

**Comment by JLworkbook** [comment]
Thanks a lot.
