### ISSUE TITLE
Error while compiling sysrepo from libyang2 branch

### ISSUE THREAD

**Issue by ankit7gup** [sysrepo/sysrepo#2427]
Getting below errors while compiling sysrepo from libyang2 branch.

[sysrepo_make.txt](https://github.com/sysrepo/sysrepo/files/6521527/sysrepo_make.txt)

P.S. Libyang and libnetconf compiled successfully

**Comment by michalvasko** [comment]
Okay, how about now.

**Comment by ankit7gup** [comment]
Getting these errors now..

[build_make_1.txt](https://github.com/sysrepo/sysrepo/files/6521761/build_make_1.txt)

**Comment by michalvasko** [comment]
Fine, is it fixed now finally?

**Comment by ankit7gup** [comment]
One last error now..


In file included from /home/ankit/libyang2/sysrepo/build/common.h:30:0,
                 from /home/ankit/libyang2/sysrepo/src/utils/xpath.c:27:
/home/ankit/libyang2/sysrepo/src/shm_types.h:83:25: error: field ‘ds_lock_ts’ has incomplete type
         struct timespec ds_lock_ts; /**< Timestamp of the datastore lock. */
                         ^
make[2]: *** [CMakeFiles/srobj.dir/src/utils/xpath.c.o] Error 1
make[1]: *** [CMakeFiles/srobj.dir/all] Error 2
make: *** [all] Error 2
[root@romulus build]#

**Comment by michalvasko** [comment]
Hm, seems the macro must go to every source after all. Now it must work.

**Comment by ankit7gup** [comment]
Yes it worked. Thanks for the quick fixes and response.
