### ISSUE TITLE
With libyang2 branch, got error for sysrepo while doing make install for netopeer

### ISSUE THREAD

**Issue by ankit7gup** [sysrepo/sysrepo#2428]
Got below error on doing "make install" for netopeer using libyang2 branch.

-- Installing missing sysrepo modules...
[ERR]: Internal error (/home/ankit/libyang2/sysrepo/src/modinfo.c:1703).
[ERR]: Invalid LYB format version "0x00", expected "0x10".
[ERR]: Failed to update data for the new context.
sysrepoctl error: Failed to apply changes (Operation failed)
For more details you may try to increase the verbosity up to "-v3".
CMake Error at cmake_install.cmake:86 (message):
   scripts/setup.sh failed: 1

**Comment by michalvasko** [comment]
Updating *sysrepo* and the other projects from using *libyang* version 1 to 2 is a major update. To make sure it goes smoothly, you should do `make sr_clean` for *sysrepo*, if nothing else. Other than that, it may be best to do `make uninstall` for all the old libraries but it should work fine even without that (I am switching between the versions regularly).

**Comment by ankit7gup** [comment]
Yes it worked, after make uninstall for older version and then make install for new sysrepo version again. Thanks!
