### ISSUE TITLE
Internal error when we do get-data on operdb after a edit-config on running db

### ISSUE THREAD

**Issue by vshaker** [sysrepo/sysrepo#2429]
Hi , 

I had added data in my operdb only for a  list named "aggregation" . One of the leaf under that list i had performed a edit-config on running db using netopeer2-cli . Edit-config was successful and data is reflecting in my running db but when a do get-data of operdb it is throwing "internal error "

Have pasted the snippet for your reference 

**Step1: get-data on operdb**
```
get-data --datastore operational --filter-xpath /o-ran-aggregation-base:aggregated-o-ru/aggregation
```
```xml
<aggregated-o-ru xmlns="urn:o-ran:agg-base:1.0">
  <aggregation>
    <ru-instance>ruId1</ru-instance>
   ..........
 </aggregation>
</aggregated-o-ru>
```
**Step2:edit-config on running db for the same aggregation list**
```
> edit-config --target running --config=/home/airvana/vimala/DateTime/usr/bin/action-edit.xml
OK
```
**Step3: get-data on operdb (Internal error)**
```
> get-data --datastore operational --filter-xpath /o-ran-aggregation-base:aggregated-o-ru/aggregation
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	message:  Internal error
```
**Step4:get-data on running db** 
```
> get-data --datastore running --filter-xpath /o-ran-aggregation-base:aggregated-o-ru/aggregation
```
```xml
DATA
<aggregated-o-ru xmlns="urn:o-ran:agg-base:1.0">
  <aggregation>
    <ru-instance>ruId1</ru-instance>
   ..........
 </aggregation>
</aggregated-o-ru>
```

Netopeer2-server logs :
```
| INFO | LY | netopeer2-server | All data nodes and constraints resolved. |
| ERROR | SR | netopeer2-server | Internal error (/home/vs1082/NETCONF_NEW/onecell5g/ran_3rdparty/open_source/netconf/sysrepo/src/edit_diff.c:2675). |
| ERROR | NP | netopeer2-server | Getting data "/o-ran-aggregation-base:aggregated-o-ru/aggregation" from sysrepo failed (Internal error). |
| INFO | SR | netopeer2-server | Failed processing of "rpc" event with ID 6 priority 0 (remaining 1 subscribers). |
| ERROR | SR | netopeer2-server | Internal error |
```

**Comment by michalvasko** [comment]
I have tried to reproduce it but I cannot, based just on the information you provided. So please be more specific with exact steps and data or, ideally, create a small example that reproduces the problem, it seems it is all related just to *sysrepo* and *netopeer2* does not have to be running. Also, what *sysrepo* version are you using?

**Comment by vshaker** [comment]
Hi @michalvasko ,
Sysrepo version:
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo **v1.4.108 (SO v5.6.24)**



**Step1: get-data of running and operational db** 

> get-data --datastore running  --filter-xpath /o-ran-aggregation-base:aggregated-o-ru/aggregation
DATA

> get-data --datastore operational --filter-xpath /o-ran-aggregation-base:aggregated-o-ru/aggregation
DATA
<aggregated-o-ru xmlns="urn:o-ran:agg-base:1.0">
  <aggregation>
    <ru-instance>ruId1</ru-instance>
    <cell-id>rucell1</cell-id>
    <X0005B9_ruConnectionStatus xmlns="urn:commscope:o-ran:ru:1.0">DISCONNECTED</X0005B9_ruConnectionStatus>
    <hardware-model xmlns="urn:o-ran:agg-hardware:1.0">
      <hardware>
        <component>
          <name>name1</name>
          <description/>
          <parent/>
          <parent-rel-pos>0</parent-rel-pos>
          <hardware-rev/>
          <firmware-rev/>
          <software-rev>2</software-rev>
          <serial-num>0005B9Abab01</serial-num>
          <mfg-name/>
          <model-name/>
          <alias/>
          <asset-id/>
          <is-fru>false</is-fru>
          <X0005B9_up-time>0</X0005B9_up-time>
          <product-code xmlns="urn:o-ran:hardware:1.0"/>
          <o-ran-name xmlns="urn:o-ran:hardware:1.0"/>
          <state>
            <admin-state>locked</admin-state>
            <alarm-state/>
            <availability-state xmlns="urn:o-ran:hardware:1.0">UNKNOWN</availability-state>
          </state>
        </component>
      </hardware>
    </hardware-model>
    <uplane-conf-model xmlns="urn:o-ran:agg-uplane-conf:1.0">
      <user-plane-configuration>
        <tx-array-carriers>
          <name>name1</name>
          <absolute-frequency-center>0</absolute-frequency-center>
          <center-of-channel-bandwidth>0</center-of-channel-bandwidth>
          <channel-bandwidth>0</channel-bandwidth>
          <active>INACTIVE</active>
          <state>READY</state>
          <type>NR</type>
          <duplex-scheme>TDD</duplex-scheme>
          <rw-duplex-scheme>TDD</rw-duplex-scheme>
          <rw-type>NR</rw-type>
          <gain>0.0</gain>
          <downlink-radio-frame-offset>0</downlink-radio-frame-offset>
          <downlink-sfn-offset>0</downlink-sfn-offset>
        </tx-array-carriers>
      </user-plane-configuration>
    </uplane-conf-model>
  </aggregation>
</aggregated-o-ru>



**2)edit-config on running db** 

> edit-config --target running --config=/home/airvana/vimala/DateTime/usr/bin/action-edit.xml
OK



**_netopeer2-server logs :_**
| INFO | LY | netopeer2-server | Resolving unresolved data nodes and their constraints... |
| INFO | LY | netopeer2-server | All data nodes and constraints resolved. |
| INFO | LY | netopeer2-server | Resolving unresolved data nodes and their constraints... |
| INFO | LY | netopeer2-server | All data nodes and constraints resolved. |
| INFO | SR | netopeer2-server | Published event "rpc" "/ietf-netconf:edit-config" with ID 1 priority 0 for 1 subscribers. |
| INFO | SR | netopeer2-server | Processing "/ietf-netconf:edit-config" "rpc" event with ID 1 priority 0 (remaining 1 subscribers). |
| INFO | NP | netopeer2-server | edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed. |
| INFO | LY | netopeer2-server | Resolving unresolved data nodes and their constraints... |
| INFO | LY | netopeer2-server | All data nodes and constraints resolved. |
| INFO | SR | netopeer2-server | Published event "change" "o-ran-aggregation-base" with ID 1 priority 0 for 1 subscribers. |
| INFO | SR | netopeer2-server | Event "change" with ID 1 priority 0 succeeded. |
| INFO | LY | netopeer2-server | Resolving unresolved data nodes and their constraints... |
| INFO | LY | netopeer2-server | There is no leafref "../../component/name" with the value "", but it is not required. |
| INFO | LY | netopeer2-server | There is no leafref "/o-ran-aggregation-base:aggregated-o-ru/o-ran-aggregation-base:aggregation/o-ran-agg-hardware:hardware-model/o-ran-agg-hardware:hardware/o-ran-agg-hardware:component/o-ran-agg-hardware:name" with the value "", but it is not required. |
| INFO | LY | netopeer2-server | All data nodes and constraints resolved. |
| INFO | SR | netopeer2-server | Published event "done" "o-ran-aggregation-base" with ID 1 priority 0 for 1 subscribers. |
| INFO | SR | netopeer2-server | Successful processing of "rpc" event with ID 1 priority 0 (remaining 0 subscribers). |
| INFO | SR | netopeer2-server | Event "rpc" with ID 1 priority 0 succeeded. |
| INFO | NP | netopeer2-server | Session 2: thread 3 event new RPC. |



**Content of action-edit.xml**

<aggregated-o-ru xmlns="urn:o-ran:agg-base:1.0" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
 <aggregation>
    <ru-instance>ruId1</ru-instance>
    <uplane-conf-model xmlns="urn:o-ran:agg-uplane-conf:1.0" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
	<user-plane-configuration>
	<tx-array-carriers>
	<name>name1</name>
	<active>INACTIVE</active>
	</tx-array-carriers>
	</user-plane-configuration>
	</uplane-conf-model>
  </aggregation>
</aggregated-o-ru>

**3)get-data of running and operdb**

> get-data --datastore running  --filter-xpath /o-ran-aggregation-base:aggregated-o-ru/aggregation
DATA
<aggregated-o-ru xmlns="urn:o-ran:agg-base:1.0">
  <aggregation>
    <ru-instance>ruId1</ru-instance>
    <uplane-conf-model xmlns="urn:o-ran:agg-uplane-conf:1.0">
      <user-plane-configuration>
        <tx-array-carriers>
          <name>name1</name>
          <active>INACTIVE</active>
        </tx-array-carriers>
      </user-plane-configuration>
    </uplane-conf-model>
  </aggregation>
</aggregated-o-ru>

> get-data --datastore operational --filter-xpath /o-ran-aggregation-base:aggregated-o-ru/aggregation
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	message:  Internal error

	
	
**Netopeer2-server logs :**
 INFO | LY | netopeer2-server | There is no leafref "/aggregated-o-ru/recovered-ru-instance-ids/ru-instance-id" with the value "ruId1", but it is not required. |
| INFO | LY | netopeer2-server | All data nodes and constraints resolved. |
| INFO | NP | netopeer2-server | Session 2: thread 4 event new RPC. |
| INFO | LY | netopeer2-server | Resolving unresolved data nodes and their constraints... |
| INFO | LY | netopeer2-server | All data nodes and constraints resolved. |
| INFO | LY | netopeer2-server | Resolving unresolved data nodes and their constraints... |
| INFO | LY | netopeer2-server | All data nodes and constraints resolved. |
| INFO | SR | netopeer2-server | Published event "rpc" "/ietf-netconf-nmda:get-data" with ID 6 priority 0 for 1 subscribers. |
| INFO | SR | netopeer2-server | Processing "/ietf-netconf-nmda:get-data" "rpc" event with ID 6 priority 0 (remaining 1 subscribers). |
| INFO | LY | netopeer2-server | Resolving unresolved data nodes and their constraints... |
| INFO | LY | netopeer2-server | There is no leafref "../../component/name" with the value "", but it is not required. |
| INFO | LY | netopeer2-server | There is no leafref "/o-ran-aggregation-base:aggregated-o-ru/o-ran-aggregation-base:aggregation/o-ran-agg-hardware:hardware-model/o-ran-agg-hardware:hardware/o-ran-agg-hardware:component/o-ran-agg-hardware:name" with the value "", but it is not required. |
| INFO | LY | netopeer2-server | All data nodes and constraints resolved. |
| ERROR | SR | netopeer2-server | Internal error (/home/vs1082/NETCONF_NEW/onecell5g/ran_3rdparty/open_source/netconf/sysrepo/src/edit_diff.c:2675). |
| ERROR | NP | netopeer2-server | Getting data "/o-ran-aggregation-base:aggregated-o-ru/aggregation" from sysrepo failed (Internal error). |
| INFO | SR | netopeer2-server | Failed processing of "rpc" event with ID 6 priority 0 (remaining 1 subscribers). |
| ERROR | SR | netopeer2-server | Internal error |
| WARNING | SR | netopeer2-server | Event "rpc" with ID 6 priority 0 failed (Internal error). |
| ERROR | NP | netopeer2-server | Failed to send an RPC (User callback failed). |
| INFO | NP | netopeer2-server | Session 2: thread 2 event new RPC. |
| INFO | NP | netopeer2-server | Session 2: thread 2 event reply error. |

**Comment by vshaker** [comment]
Attaching the files for your reference 
[Operdb_internal_error.txt](https://github.com/sysrepo/sysrepo/files/6530302/Operdb_internal_error.txt)

[edit-action.txt](https://github.com/sysrepo/sysrepo/files/6530307/edit-action.txt)

**Comment by michalvasko** [comment]
Okay, if you also attach the used YANGs, I should have everything needed for reproducing. Best to just attach your whole `sysrepo-repository/yang` directory.

**Comment by vshaker** [comment]
[yang.tar.gz](https://github.com/sysrepo/sysrepo/files/6530369/yang.tar.gz)
Please find the list of yang files installed

**Comment by vshaker** [comment]
[yang.tar.gz](https://github.com/sysrepo/sysrepo/files/6530547/yang.tar.gz)
Please find the list of yang files

**Comment by michalvasko** [comment]
Thanks, I could reproduce it and should now be fixed.

**Comment by vshaker** [comment]
Hi @michalvasko ,
What is the fix ?Ideally when edit-config on running is done, it copy values to oper db, so why in this case it was not done.

**Comment by michalvasko** [comment]
Well, in brief, the stored operational data are always a diff on the current enabled `running` data. The problem was that when `running` data changed, the new base data for stored operational diff were all `running` data instead of only enabled `running` data. Quite a serious problem but it seems most use-cases always subscribe to the `running` data (making it enabled) of a module that they are storing operational data for as well, so it did not manifest before.

This whole mechanism is overly complex and so new *sysrepo* in `libyang2` branch has a completely changed way of handling stored operational data.

**Comment by vshaker** [comment]
@michalvasko Thank you  . Can you please explain the fix in terms of the below 2 example which i tried executing with the fix . 

### **Example 1:**
**1)get-data of oper db and running db**

> get-data --datastore operational --filter-xpath /o-ran-aggregation-base:aggregated-o-ru/aggregation
DATA
<aggregated-o-ru xmlns="urn:o-ran:agg-base:1.0">
  <aggregation>
    <ru-instance>ruId1</ru-instance>
  </aggregation>
  <aggregation>

> get-data --datastore running  --filter-xpath /o-ran-aggregation-base:aggregated-o-ru/aggregation
DATA

**2)edit-config of running db :**
> edit-config --target running --config=/home/airvana/vimala/DateTime/usr/bin/action-edit.xml
OK


**action-edit.xml:**

<aggregated-o-ru xmlns="urn:o-ran:agg-base:1.0" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
    <aggregation>
       <ru-instance>4</ru-instance>
    </aggregation>
</aggregated-o-ru>

**3)get-data of oper db and running db**

> get-data --datastore running  --filter-xpath /o-ran-aggregation-base:aggregated-o-ru/aggregation
DATA
<aggregated-o-ru xmlns="urn:o-ran:agg-base:1.0">
  <aggregation>
    <ru-instance>4</ru-instance>
  </aggregation>
</aggregated-o-ru>


> get-data --datastore operational --filter-xpath /o-ran-aggregation-base:aggregated-o-ru/aggregation
DATA
<aggregated-o-ru xmlns="urn:o-ran:agg-base:1.0">
  <aggregation>
    <ru-instance>ruId1</ru-instance>
  </aggregation>
  <aggregation>


### **Example2 :**

**1) get-data of running and operdb**
> get-data --datastore operational --filter-xpath /o-ran-aggregation-base:aggregated-o-ru/aggregation
DATA
<aggregated-o-ru xmlns="urn:o-ran:agg-base:1.0">
  <aggregation>
    <ru-instance>ruId1</ru-instance>
    <uplane-conf-model xmlns="urn:o-ran:agg-uplane-conf:1.0">
      <user-plane-configuration>
        <tx-array-carriers>
          <name>name3</name>
          <active>INACTIVE</active>
        </tx-array-carriers>
        <tx-array-carriers>
          <name>name1</name>
          <active>INACTIVE</active>
        </tx-array-carriers>
      </user-plane-configuration>
    </uplane-conf-model>
    <cell-id>rucell1</cell-id>
  </aggregation>
</aggregated-o-ru>

> get-data --datastore running  --filter-xpath /o-ran-aggregation-base:aggregated-o-ru/aggregation
DATA
<aggregated-o-ru xmlns="urn:o-ran:agg-base:1.0">
  <aggregation>
    <ru-instance>4</ru-instance>
    <uplane-conf-model xmlns="urn:o-ran:agg-uplane-conf:1.0">
      <user-plane-configuration>
        <tx-array-carriers>
          <name>name1</name>
          <active>INACTIVE</active>
        </tx-array-carriers>
        <tx-array-carriers>
          <name>name3</name>
          <active>INACTIVE</active>
        </tx-array-carriers>
      </user-plane-configuration>
    </uplane-conf-model>
  </aggregation>
  <aggregation>
    <ru-instance>ruId1</ru-instance>
    <uplane-conf-model xmlns="urn:o-ran:agg-uplane-conf:1.0">
      <user-plane-configuration>
        <tx-array-carriers>
          <name>name3</name>
          <active>INACTIVE</active>
        </tx-array-carriers>
      </user-plane-configuration>
    </uplane-conf-model>
  </aggregation>
</aggregated-o-ru>

**2) edit-config of running db** 

> edit-config --target running --config=/home/airvana/vimala/DateTime/usr/bin/action-edit.xml
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	message:  Validation failed

	
action-edit.xml:

<aggregated-o-ru xmlns="urn:o-ran:agg-base:1.0" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
    <aggregation>
    <ru-instance>ruId1</ru-instance>
    <tx-array-carriers>
    <name>name3</name>
       <active>ACTIVE</active>
    </tx-array-carriers>
    </aggregation>
</aggregated-o-ru>

What do you mean by enabled data in sr_module_oper_data_dup_enabled() function .

**Comment by michalvasko** [comment]
I am not sure I understand what is happening in your examples so I probably cannot explain anything, without some more information. In any case, if you rely on stored operational data a lot, I suggest you update to *sysrepo* v2, the mechanism is completely reworked there and significantly simplified.

**Comment by vshaker** [comment]
I didn't understand what it meant by "enabled" running data . 
In example 2 , in running db i have both ru-instance 4 and ruID1 whereas only ruID1 in operdb when i do a edit-config on ruId1 I'm getting validation failed. 

**XML used** 

<aggregated-o-ru xmlns="urn:o-ran:agg-base:1.0" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
    <aggregation>
    <ru-instance>ruId1</ru-instance>
    <tx-array-carriers>
    <name>name3</name>
       <active>ACTIVE</active>
    </tx-array-carriers>
    </aggregation>
</aggregated-o-ru>

**Comment by michalvasko** [comment]
What I meant by `enabled` is simply `subscribed running data` [here](https://netopeer.liberouter.org/doc/sysrepo/master/html/index.html#oper_ds). And I am not sure what could be the cause of the validation error, what does *sysrepo* or *netopeer2* print?

**Comment by vshaker** [comment]
Please find the netopeer2-server error 


| INFO | NP | netopeer2-server | edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed. |
| INFO | LY | netopeer2-server | Resolving unresolved data nodes and their constraints... |
| INFO | LY | netopeer2-server | All data nodes and constraints resolved. |
| INFO | SR | netopeer2-server | Published event "change" "o-ran-aggregation-base" with ID 8 priority 0 for 1 subscribers. |
| ERROR | SR | netopeer2-server | Validation failed |
| WARNING | SR | netopeer2-server | Event "change" with ID 8 priority 0 failed (Validation failed). |
| INFO | SR | netopeer2-server | Failed processing of "rpc" event with ID 2 priority 0 (remaining 1 subscribers). |
| ERROR | SR | netopeer2-server | Validation failed |
| WARNING | SR | netopeer2-server | Event "rpc" with ID 2 priority 0 failed (User callback failed). |
| ERROR | NP | netopeer2-server | Failed to send an RPC (User callback failed). |

**Comment by michalvasko** [comment]
No more details, that is usually sign of an internal problem. I could try to reproduce this error but you would need to provide the exact steps, starting from a clean state after `make sr_clean`.

**Comment by vshaker** [comment]
Yeah sure will share the exact steps , meanwhile i encountered a scenario 
1) operdb Add -->added ruId1 (ru-instance)
2)Operdb add -->added ruIndex (ru-instance)
3)edit-config on running for ruId1(Modified some parameter)
4)get-data on running shows correct data
5)Whereas in operdb get-data ru-instance "ruIndex" entry is gone
From application side we aren't doing any deletion . Please let me know if it is expected behaviour . 

> get-data --datastore operational --filter-xpath /o-ran-aggregation-base:aggregated-o-ru/aggregation
DATA
<aggregated-o-ru xmlns="urn:o-ran:agg-base:1.0">
  <aggregation>
    <ru-instance>ruId1</ru-instance>
    <cell-id>rucell1</cell-id>
    <X0005B9_ruConnectionStatus xmlns="urn:commscope:o-ran:ru:1.0">DISCONNECTED</X0005B9_ruConnectionStatus>
    <hardware-model xmlns="urn:o-ran:agg-hardware:1.0">
      <hardware>
        <component>
          <name>name1</name>
          <description/>
          <parent/>
          <parent-rel-pos>0</parent-rel-pos>
          <hardware-rev/>
          <firmware-rev/>
          <software-rev>2</software-rev>
          <serial-num>0005B9Abab01</serial-num>
          <mfg-name/>
          <model-name/>
          <alias/>
          <asset-id/>
          <is-fru>false</is-fru>
          <X0005B9_up-time>0</X0005B9_up-time>
          <product-code xmlns="urn:o-ran:hardware:1.0"/>
          <o-ran-name xmlns="urn:o-ran:hardware:1.0"/>
          <state>
            <admin-state>locked</admin-state>
            <alarm-state/>
            <availability-state xmlns="urn:o-ran:hardware:1.0">UNKNOWN</availability-state>
          </state>
        </component>
      </hardware>
    </hardware-model>
    <uplane-conf-model xmlns="urn:o-ran:agg-uplane-conf:1.0">
      <user-plane-configuration>
        <tx-array-carriers>
          <name>name1</name>
          <absolute-frequency-center>0</absolute-frequency-center>
          <center-of-channel-bandwidth>0</center-of-channel-bandwidth>
          <channel-bandwidth>0</channel-bandwidth>
          <active>INACTIVE</active>
          <state>READY</state>
          <type>NR</type>
          <duplex-scheme>TDD</duplex-scheme>
          <rw-duplex-scheme>TDD</rw-duplex-scheme>
          <rw-type>NR</rw-type>
          <gain>0.0</gain>
          <downlink-radio-frame-offset>0</downlink-radio-frame-offset>
          <downlink-sfn-offset>0</downlink-sfn-offset>
        </tx-array-carriers>
      </user-plane-configuration>
    </uplane-conf-model>
  </aggregation>
</aggregated-o-ru>

> get-data --datastore operational --filter-xpath /o-ran-aggregation-base:aggregated-o-ru/aggregation
DATA
<aggregated-o-ru xmlns="urn:o-ran:agg-base:1.0">
  <aggregation>
    <ru-instance>ruId1</ru-instance>
    <cell-id>rucell1</cell-id>
    <X0005B9_ruConnectionStatus xmlns="urn:commscope:o-ran:ru:1.0">DISCONNECTED</X0005B9_ruConnectionStatus>
    <hardware-model xmlns="urn:o-ran:agg-hardware:1.0">
      <hardware>
        <component>
          <name>name1</name>
          <description/>
          <parent/>
          <parent-rel-pos>0</parent-rel-pos>
          <hardware-rev/>
          <firmware-rev/>
          <software-rev>2</software-rev>
          <serial-num>0005B9Abab01</serial-num>
          <mfg-name/>
          <model-name/>
          <alias/>
          <asset-id/>
          <is-fru>false</is-fru>
          <X0005B9_up-time>0</X0005B9_up-time>
          <product-code xmlns="urn:o-ran:hardware:1.0"/>
          <o-ran-name xmlns="urn:o-ran:hardware:1.0"/>
          <state>
            <admin-state>locked</admin-state>
            <alarm-state/>
            <availability-state xmlns="urn:o-ran:hardware:1.0">UNKNOWN</availability-state>
          </state>
        </component>
        <component>
          <name>name2</name>
          <parent>Har_Parent</parent>
        </component>
      </hardware>
    </hardware-model>
    <uplane-conf-model xmlns="urn:o-ran:agg-uplane-conf:1.0">
      <user-plane-configuration>
        <tx-array-carriers>
          <name>name1</name>
          <absolute-frequency-center>0</absolute-frequency-center>
          <center-of-channel-bandwidth>0</center-of-channel-bandwidth>
          <channel-bandwidth>0</channel-bandwidth>
          <active>INACTIVE</active>
          <state>READY</state>
          <type>NR</type>
          <duplex-scheme>TDD</duplex-scheme>
          <rw-duplex-scheme>TDD</rw-duplex-scheme>
          <rw-type>NR</rw-type>
          <gain>0.0</gain>
          <downlink-radio-frame-offset>0</downlink-radio-frame-offset>
          <downlink-sfn-offset>0</downlink-sfn-offset>
        </tx-array-carriers>
      </user-plane-configuration>
    </uplane-conf-model>
  </aggregation>
  <aggregation>
    <ru-instance>ruIndex</ru-instance>
  </aggregation>
</aggregated-o-ru>

> get-data --datastore running --filter-xpath /o-ran-aggregation-base:aggregated-o-ru/aggregation
DATA

> edit-config --target running --config=/home/airvana/vimala/DateTime/usr/bin/action-edit.xml
OK
> get-data --datastore running --filter-xpath /o-ran-aggregation-base:aggregated-o-ru/aggregation
DATA
<aggregated-o-ru xmlns="urn:o-ran:agg-base:1.0">
  <aggregation>
    <ru-instance>ruId1</ru-instance>
    <uplane-conf-model xmlns="urn:o-ran:agg-uplane-conf:1.0">
      <user-plane-configuration>
        <tx-array-carriers>
          <name>name3</name>
          <active>INACTIVE</active>
        </tx-array-carriers>
      </user-plane-configuration>
    </uplane-conf-model>
  </aggregation>
</aggregated-o-ru>

> get-data --datastore operational --filter-xpath /o-ran-aggregation-base:aggregated-o-ru/aggregation
DATA
<aggregated-o-ru xmlns="urn:o-ran:agg-base:1.0">
  <aggregation>
    <ru-instance>ruId1</ru-instance>
    <uplane-conf-model xmlns="urn:o-ran:agg-uplane-conf:1.0">
      <user-plane-configuration>
        <tx-array-carriers>
          <name>name3</name>
          <active>INACTIVE</active>
          <absolute-frequency-center>0</absolute-frequency-center>
          <center-of-channel-bandwidth>0</center-of-channel-bandwidth>
          <channel-bandwidth>0</channel-bandwidth>
          <state>DISABLED</state>
          <type>NR</type>
          <duplex-scheme>TDD</duplex-scheme>
          <rw-duplex-scheme>TDD</rw-duplex-scheme>
          <rw-type>NR</rw-type>
          <gain>0.0</gain>
          <downlink-radio-frame-offset>0</downlink-radio-frame-offset>
          <downlink-sfn-offset>0</downlink-sfn-offset>
        </tx-array-carriers>
      </user-plane-configuration>
    </uplane-conf-model>
    <cell-id/>
    <X0005B9_ruConnectionStatus xmlns="urn:commscope:o-ran:ru:1.0">DISCONNECTED</X0005B9_ruConnectionStatus>
  </aggregation>
</aggregated-o-ru>



**action-edit.xml:**
<aggregated-o-ru xmlns="urn:o-ran:agg-base:1.0" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
<aggregation>
<ru-instance>ruId1</ru-instance>
<uplane-conf-model xmlns="urn:o-ran:agg-uplane-conf:1.0" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
<user-plane-configuration>
<tx-array-carriers>
<name>name3</name>
<active>INACTIVE</active>
</tx-array-carriers>
</user-plane-configuration>
</uplane-conf-model>
</aggregation>
</aggregated-o-ru>

**Comment by michalvasko** [comment]
> Please let me know if it is expected behaviour .

I think so because in *sysrepo* v1 the stored operational data are strictly tied to `running` data so when they change, the operational data can also change. If you do not want this behavior, use *sysrepo* v2.

**Comment by vshaker** [comment]
But I haven't changed anything related to "ruIndex" instance . Why will that be deleted ?

**Comment by michalvasko** [comment]
I am not sure what exactly is happening and it is possible there is something wrong. However, like I said, operational data work completely differently in *sysrepo* v2 and it seems not to be worth it waste an hour at least debugging this in v1. If you really want this explained/fixed, you will have to provide all the required data, steps, and even the application that sets the stored operational data so that I can immediately reproduce it.
