### ISSUE TITLE
deprecated leaf recevied in config change set

### ISSUE THREAD

**Issue by iGovindY** [sysrepo/sysrepo#2430]
Hi

sysrepo is not handling deprecated leaf, as it should.

1. leaf b is somewhere under a list a, 
2. create an instance of list a using edit-config, this will also create and send leaf b in module_change callback with default value 0 even though it's marked as deprecated.

```
leaf b{
    type int16 {
      range -10000..10000;
    }
    default 0;
    status deprecated;
}
```

`sysrepo version: 1.4.89`

**Comment by michalvasko** [comment]
> sysrepo is not handling deprecated leaf, as it should.

I am wondering what makes you say this. All that we implemented is [this section](https://datatracker.ietf.org/doc/html/rfc7950#section-7.21.2). Specifically, the checking for older-status references. As for the bullets, those are probably up to the implementations, not sure how *libyang* or *sysrepo* can help with that. In any case, `deprecated` should be implemented normally, it is only `obsolete` that may perhaps work differently, I am not sure.
