### ISSUE TITLE
get --filter-xpath

### ISSUE THREAD

**Issue by som-1981** [sysrepo/sysrepo#2431]
Hello,

I see that the following command works for some of the yang modules but not for others
Example:
> get --filter-xpath /o-ran-software-management:*
ly VERBOSE: Resolving unresolved data nodes and their constraints...
ly VERBOSE: All data nodes and constraints resolved.
ly ERROR: Module name "o-ran-software-management" refers to an unknown module.
cli_send_recv: Failed to send the RPC.

I do agree that we are running older versions but for other yangs it works perfectly.

nc VERBOSE: Session 10: trying to use capabilities instead of ietf-yang-library data.
The yang are parsed successfully but gives an error when we get --filter-xpath on those.

Should we use ietf-yang-library data instead of capabilities?

Thanks

**Comment by michalvasko** [comment]
> I do agree that we are running older versions but for other yangs it works perfectly.

Then that will be the problem. For some reason, `ietf-yang-library` data cannot be retrieved meaning no YANG 1.1 modules are loaded (because they are not present in capabilities) and hence the filter is unable to recognize any YANG 1.1 modules, only YANG 1.0.

**Comment by som-1981** [comment]
Thanks.

The other modules which are working are also YANG 1.1.
For example:
module o-ran-module-cap {
  yang-version 1.1;
  namespace "urn:o-ran:module-cap:1.0";
  prefix "o-ran-module-cap";

Thanks,

**Comment by michalvasko** [comment]
That is interesting and I cannot explain it without knowing more details about what is going on during the `hello` handshake.
