### ISSUE TITLE
Operational data cache support

### ISSUE THREAD

**Issue by mkk-dev** [sysrepo/sysrepo#2434]
For scalability for `sr_oper_get_items_subscribe` it would be great if the operational data provider could provide cache control timeout / data validity timeout to rate limit callbacks and process context switches.

**Comment by michalvasko** [comment]
I suppose that makes sense. But in cases where this is a problem you may be better of using `push` operational data instead.

**Comment by mkk-dev** [comment]
I guess my use case is maybe rather unique as I have rather large set of operational data that is updating regularly but it is only queried occasionally (but then queries can come in a bursty manner). So to me it doesn't make sense to continually push data to DS. I could hack it by pushing data after first pull and do opposite of `sr_oper_get_items_subscribe`, which doesn't seem to exist, and then after the timeout resubscribe for future calls to get updated data.

**Comment by michalvasko** [comment]
Supported now.
