### ISSUE TITLE
Callback not call in daemon mode

### ISSUE THREAD

**Issue by namphuonghoanges** [sysrepo/sysrepo#2435]
Hi
I have a question about the callback when the application where having the callback (already subscribe) is run in the daemon mode, are those callback can call by sysrepo?
I'm facing a problem that when I using debug mode, my callback can called but when daemon, those callbacks not called anymore. To solve this problem, do you having any suggestions?

Thank you

**Comment by michalvasko** [comment]
Please mention your *sysrepo* version and more details such as how exactly you subscribe (what function) and what you do to make the callback be called in one case and not in the other.

**Comment by namphuonghoanges** [comment]
I think i found the errors. In my application, I run function daemon() after subscribe the callback, that why the callback cannot call. Thank you
