### ISSUE TITLE
In case session not closed gracefully(Ctrl^C) for application, further restarting of application misbehaves for operational data write and send notifications

### ISSUE THREAD

**Issue by ankit7gup** [sysrepo/sysrepo#2436]
Hi Michal,

I have taken the code changes from Libyang2 branch.
Now notification works fine. However one issue that I have observed is as follows.

1. In case the sessions are not closed gracefully i.e. application is killed using ctrl^c, In that case, when application is restarted, and all sessions are started again, configuration data works fine. operational data changes are applied using sr_apply_changes() with no error. But while sending notification for leafs with reference to same Operational data, errors are generated. The behavior is always reproducible. 

In oper_data_write_handler  xpath: /o-ran-uplane-conf:user-plane-configuration
```
Application will set xpath:/o-ran-uplane-conf:user-plane-configuration/tx-array-carriers[name='TX-Ca0']/name value:TX-Ca0
Application will set xpath:/o-ran-uplane-conf:user-plane-configuration/tx-array-carriers[name='TX-Ca0']/state value:BUSY
Application will set xpath:/o-ran-uplane-conf:user-plane-configuration/rx-array-carriers[name='RX-Ca0']/name value:RX-Ca0
Application will set xpath:/o-ran-uplane-conf:user-plane-configuration/rx-array-carriers[name='RX-Ca0']/state value:BUSY
[INF]: No datastore changes to apply.
```

path /o-ran-uplane-conf:rx-array-carriers-state-change/rx-array-carriers-notif[name='RX-Ca0']/nameaction value RX-Ca0 
path /o-ran-uplane-conf:rx-array-carriers-state-change/rx-array-carriers-notif[name='RX-Ca0']/stateaction value BUSY 

establish_sysrepo_notification_session
```
[INF]: Session 82 (user "root", CID 149) created.
[INF]: Recovering module "o-ran-uplane-conf" stored operational data of CID 145.
[ERR]: Invalid leafref value "BUSY" - no existing target instance "/user-plane-configuration/rx-array-carriers/state".
[ERR]: Notification validation failed.
```
In notification_send_handler(): sr_event_notif_send() returned Error

**Comment by michalvasko** [comment]
I am sorry but I am not able to track all the issues and it would be best to have all the relevant information here anyway. So please write the exact steps of reproducing the issue with all the YANG modules and data. Seems to be a complex use-case so I need to reproduce it and then will probably also add it to tests.

**Comment by ankit7gup** [comment]
The steps to reproduce the issue are as follows:
[yangs.zip](https://github.com/sysrepo/sysrepo/files/6544169/yangs.zip)

1. Load the mentioned modules using script oru_module_load.sh.
2. After loading the module, along with some default config(mentioned in oru_module_load.sh), open a session towards operational DB and write data to it. Keep the session open.
3. open new session towards running DB to send notifications. Using this send notification with leaf dependent on operational data. SUCCESS. 
[code_notification_operational_data.txt](https://github.com/sysrepo/sysrepo/files/6544163/code_notification_operational_data.txt)

 4. Close session towards running DB.
 5. Let session for operational data be open, and application running.
 6. Kill application.
 7. Restart application, this time Operational data write shall give no errors, but below message.
 
 **Application will set xpath:/o-ran-uplane-conf:user-plane-configuration/tx-array-carriers[name='TX-Ca0']/name value:TX-Ca0
Application will set xpath:/o-ran-uplane-conf:user-plane-configuration/tx-array-carriers[name='TX-Ca0']/state value:BUSY
Application will set xpath:/o-ran-uplane-conf:user-plane-configuration/rx-array-carriers[name='RX-Ca0']/name value:RX-Ca0
Application will set xpath:/o-ran-uplane-conf:user-plane-configuration/rx-array-carriers[name='RX-Ca0']/state value:BUSY
[INF]: No datastore changes to apply.**

8. On sending notification(s) now, gettign below error every time.

**[INF]: Session 82 (user "root", CID 149) created.
[INF]: Recovering module "o-ran-uplane-conf" stored operational data of CID 145.
[ERR]: Invalid leafref value "BUSY" - no existing target instance "/user-plane-configuration/rx-array-carriers/state".
[ERR]: Notification validation failed.**


Hope this info is enough. In case, more details required, kindly let me know.

Thanks!

**Comment by michalvasko** [comment]
Yes, I understood the problem exactly after you mentioned all the details and it is actually not related to your application crashing. The problem was that when you restarted your application and set the data again, the previous data were still stored so it was assumed you did no changes. However, once they were actually used, the previous data were recovered (removed) and you were left with no data. The bug was that when your restarted application was setting the same data, their owner needs to be updated to the new connection (it actually was, but the data were not stored because there were no changes).

**Comment by ankit7gup** [comment]
Thanks Michal for the quick fix. Will verify with these changes.

**Comment by gotthardp** [comment]
How did you solve this issue? What is the right way to update the operational data owner to the new connection, please? (I fail to see any suitable API call for this.)

**Comment by michalvasko** [comment]
I am not sure what you are trying to achieve. Normally, every `push` oper data have their owner the connection of the session that performed the edit. If a connection disconnects (for whatever reason), its data are all removed. So, you cannot "update their owner", you can only set them again with another connection.

**Comment by gotthardp** [comment]
The connection set an operational value (push) and then crashed, without terminating correctly. When the application starts again, the operational value cannot be stored ("No datastore changes to apply."), but when I try read the operational store the value is not there.
You responded earlier that:
> The problem was that when you restarted your application and set the data again, the previous data were still stored so it was assumed you did no changes. However, once they were actually used, the previous data were recovered (removed) and you were left with no data. The bug was that when your restarted application was setting the same data, their owner needs to be updated to the new connection (it actually was, but the data were not stored because there were no changes).

That makes sense, but I wonder what exactly should be done to recover from this situation.

**Comment by gotthardp** [comment]
I am using the latest `master` branch.

I am pretty sure the value is not there: I call `sr_set_item(SR_EDIT_DEFAULT)`, followed by `sr_apply_changes`, which succeeds, but writes "No datastore changes to apply." Then I call `sr_get_item` on the same xpath and I get "Item not found". Also `sysrepocfg --export --datastore operational` does not print it.
Note 1: When the value is requested I get log `[INF] Recovering module "..." stored operational data of CID X.` where `X` is the connection that crashed. Always. It feels as if the recovery was not permanent.
Note 2: This is only a temporary situation caused by the previous crash. When I reboot the system (to clear the memory), everything works fine again, so I assume the code is correct.

**Comment by michalvasko** [comment]
I could not reproduce it in a test, when `No datastore changes to apply.` was being printed the data owner was updated and it worked as expected. Here is the [test_oper.patch.txt](https://github.com/sysrepo/sysrepo/files/7969827/test_oper.patch.txt) so please try to modify it to make the problem appear.

**Comment by gotthardp** [comment]
Thanks a lot, @michalvasko. Here is a [failing-test.txt](https://github.com/sysrepo/sysrepo/files/7989098/failing-test.txt). The trouble occurs when the data are updated in multiple "commits": the first commit works fine, but the data from the subsequent commits fail to appear in the operational store.

**Comment by michalvasko** [comment]
Okay, thanks for the test, fixed.

**Comment by gotthardp** [comment]
Brilliant. This solved the issue for me. Thank you!
