### ISSUE TITLE
RPC input error for operational data leafref

### ISSUE THREAD

**Issue by ankit7gup** [sysrepo/sysrepo#2438]
Hi Michal,

With latest version sysrepo-netopeer2, trying one of the RPC having one input leaf as a leafref to an operational data.

From my application, first I am writing the operational data, and application keeps running. Same operational data, I am able to get in netopeer2-cli via get command. But on executing the RPC command with below rpc.xml input. getting error as mentioned below.

**rpc.xml:**
[rpc.txt](https://github.com/sysrepo/sysrepo/files/6553963/rpc.txt)

**netopeer-cli outputs**
<img width="437" alt="get" src="https://user-images.githubusercontent.com/61405352/119826051-4226f580-bf15-11eb-894e-1f1621145d1e.PNG">

> user-rpc --content rpc.xml
ly ERROR: Invalid leafref value "22" - no existing target instance "/ap:ald-ports-io/ap:ald-port/ap:port-id". (Schema location /o-ran-ald:ald-communication/input/port-id, data location /o-ran-ald:ald-communication/port-id.)
cli_send_recv: Failed to send the RPC.
>

[yangs.zip](https://github.com/sysrepo/sysrepo/files/6553909/yangs.zip)

**Comment by michalvasko** [comment]
Okay, should be fixed in latest `libnetconf2`.

**Comment by ankit7gup** [comment]
Yes Michal, It worked with the mentioned fix. Thanks!
