### ISSUE TITLE
Could I receive one subscription callback function call for multiple paths?

### ISSUE THREAD

**Issue by bobooboo** [sysrepo/sysrepo#2443]
For example, for the following data:
```xml
<ModuleA xmlns="urn:comp:module-a">
    <cont1>
        <attr>1</attr>
    </cont1>
    <cont2>
        <attr>1</attr>
        <attr2>1</attr2>
    </cont2>
</ModuleA>
```
and call edit-config,
```xml
<ModuleA xmlns="urn:comp:module-a">
    <cont1>
        <attr>2</attr>
    </cont1>
    <cont2>
        <attr>2</attr>
    </cont2>
</ModuleA>
```
I want to get 1 callback for the changes of cont1/attr and cont2/attr.

but, Now I am doing the subscription as follows.
```cpp
sr_module_change_subscribe(..., "module-a", "/module-a:ModuleA/cont1/attr", callback_func, ...);
sr_module_change_subscribe(..., "module-a", "/module-a:ModuleA/cont2/attr", callback_func, ...);
```
So the callback_func is called twice at the same time.

How can I solve this problem?

**Comment by michalvasko** [comment]
I am not sure I understand your question, but it seems to me you want to have the callback called only once for changes of both `attr`. That is quite a specific request but should be possible, using some XPath tricks. In this case you should be able to use this XPath:
```
/module-a:ModuleA/cont1/attr | /module-a:ModuleA/cont2/attr
```

**Comment by bobooboo** [comment]
Thanks for understanding my strange question correctly.
I solved the problem.

Thanks, michalvasko.
