### ISSUE TITLE
Configuration file export&import 

### ISSUE THREAD

**Issue by myonlystarWang** [sysrepo/sysrepo#2450]
Hi michal,
     I want to ask if there is a way to export the configuration in sysrepo which deploy in a mechine,then I put the configuration file on another machine(installed the same version sysrepo),in order to simplify the configuration process.Or do you have a better suggestion?
     Thanks in advice!

**Comment by michalvasko** [comment]
No, this is exactly what you should do with `sysrepocfg -X`, look into help for more options.

**Comment by myonlystarWang** [comment]
Oh,thank michal,your response is very usefull!
After the YANG modules installation in the new mechine, sysrepocfg -I works fine!
It is time to close this issue!
