### ISSUE TITLE
Where does ietf-netconf@2013-09-29.yang come from?

### ISSUE THREAD

**Issue by bobooboo** [sysrepo/sysrepo#2453]
sysrepo, netopeer ... have the YANG file `ietf-netconf@2013-09-29`. 
But I can't find this file in any RFC documentation. 
(It seems that this file is only used by the cesnet project.) 

Although `ietf-netconf@2013-09-29` is just `NACM` plus `ietf-netconf@2011-06-01`, I would like to know the exact source of this file.

Regards.

**Comment by michalvasko** [comment]
I did not manage to find out much more so I do not know who is the author of this revision and adding the NACM. In any case, it is how it was "intended" because some RPC are sensitive but NACM was not defined when original NETCONF was published.

**Comment by bobooboo** [comment]
Thanks. michalvasko
