### ISSUE TITLE
New 2.x APIs and support for 1.x ones

### ISSUE THREAD

**Issue by matkocc** [sysrepo/sysrepo#2454]
Hi,

I noticed that 2.x versions of sysrepo, netopeer2, libyang and libnetconf2 are out. 
I just wanted to ask for how long will you support 1.x versions (sysrepo 1.4.x, netopeer2 1.1.x , ... ) and  how big is difference between these new 2.x versions and 1.x ones? We are using functions from sysrepo and libyang APIs in our applications.

Thanks,
    Matko

**Comment by michalvasko** [comment]
We want to supports versions 1 at least until the end of the year, then we will see. As for the API difference, it is mostly refactoring for *libyang* (such as function returning a structure now has the structure as the last out parameter and returns `LY_ERR` for easier error checking) and you should not have much trouble migrating. As for *sysrepo*, the API changes there are mostly what I collected over time of supporting it, removed redundant parameters and things like that, there are not many changes.
