### ISSUE TITLE
error in executing subscribe command from netopeer2-cli in libyang2 branch

### ISSUE THREAD

**Issue by ashishsaxenahsc** [sysrepo/sysrepo#2456]
Hi Michal,

We are using libyang2 branch at our setup.  We are have a application that will send notification to NETCONF client that has subscribed to change in a particular model .
I am getting the following error logs at netopeer2-cli while connecting :

netopeer2-cli
connect netconf --port 830
Interactive SSH Authentication
Type your password:
Password:
ly WARNING: Missing explicit "obsolete" status that was already specified in parent, inheriting.

And when I am trying to subscribe from the netopper2-cli , I am getting the following error:

subscribe
ly ERROR: Inner node (not a list) "subscribe" not found.
cli_send_recv: Failed to receive a reply.

Can you please tell me how to resolve these issues ?

**Comment by michalvasko** [comment]
Update *libnetconf2*, latest `devel` branch, actually.
