### ISSUE TITLE
how to get *parent gracefully

### ISSUE THREAD

**Issue by xheke** [sysrepo/sysrepo#2457]
Currently, we get *parent from  `lyd_new_path`, then use this *parent add other elements one by one, like below:

 
 ```
  //*parent = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(sess)), "/openconfig-platform:components/component[name='abc']/power-supply/state/openconfig-platform-psu:enabled", "false", 0, 0);
    //lyd_new_path(*parent, NULL, "/openconfig-platform:components/component[name='abc']/state/name", "abc", 0, 0);

  ```

Can we get *parent without creation, then use this parent add all elements one by one?
something like below, (but not success:) 

```
//*parent = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(sess)), "/openconfig-platform:*", NULL, 0, 0);
    //lyd_new_path(*parent, NULL, "/openconfig-platform:components/component[name='abc']/state/name", "abc", 0, 0);
    //lyd_new_path(*parent, NULL, "/openconfig-platform:components/component[name='abc']/power-supply/state/openconfig-platform-psu:enabled", "false", 0, 0);


```

Thanks

**Comment by michalvasko** [comment]
I am sorry but I do not understand what you are trying to do. It seems you may want to use the `LYD_PATH_OPT_NOPARENTRET` flag or functions for getting a node from data tree such as `lyd_find_path()` or `lyd_find_path_hash_based()`.

**Comment by xheke** [comment]
Yeah.  I try to add operational data to DS. From example, seems it should use lyd_new_path create the first element and get the parent point at the same time. Then use this parent point to create left elements.

What I want is try to get the parent point in someway, but not through create the first element.
Then use this parent point create all elements one by one.

such as:
get the point
create a via the point
create b via the point
create c via the point
.... ...


currently behavior like below:
get the point via create a
create b via the point
create c via the point
... ...

**Comment by michalvasko** [comment]
> What I want is try to get the parent point in someway, but not through create the first element.

Okay, so you seem to be talking about the operational data callback. There, you are provided with the parent. For example, if you subscribe for providing `/model:cont1/cont2/leaf`, the `*parent` in the callback will always be `/model:cont1/cont2`. And you can then easily append to this parent, `lyd_new_path()` supports relative paths, too.

**Comment by xheke** [comment]
Hi Michal,

For my example, I want get *parent based on module, `/openconfig-platform`,  how to write the correct code?

below seems is not correct:

`*parent = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(sess)), "`/openconfig-platform:*`", NULL, 0, 0);
`
Thanks for your help.

**Comment by michalvasko** [comment]
> ... get *parent ... *parent = lyd_new_path( ...

This is nonsensical, why are you trying to get a data node with a function that is creating nodes? I have mentioned the functions for getting data nodes before. You must word your query correctly and precisely, otherwise I will just keep being confused and unable to help.

**Comment by xheke** [comment]
Sorry, Michal.

I just don't know how to describe my question exactly.

Do you mean use lyd_find_path() to get `*parent` ?

Such as `*parent = lyd_find_path("/openconfig-platform:*");`

Is that correct?

Sorry for any inconvenience  :(

**Comment by xheke** [comment]
Hi Michal,

I copy callback code here for details,
My question is how to get `*parent`  for module `/openconfig-platform` directly if not use  lyd_new_path?

Thanks for you help.



 

```
static int
dp_get_items_cb(sr_session_ctx_t *session, const char *module_name, const char *xpath, const char *request_xpath,
        uint32_t request_id, struct lyd_node **parent, void *private_data)
{
    (void)session;
    (void)request_xpath;
    (void)request_id;
    (void)private_data;

    *parent = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(sess)), "/openconfig-platform:components/component[name='abc']/power-supply/state/openconfig-platform-psu:enabled", "false", 0, 0);
    lyd_new_path(*parent, NULL, "/openconfig-platform:components/component[name='abc']/state/name", "abc", 0, 0);

```

**Comment by xheke** [comment]
add subscribe code below:

```
    rc = sr_oper_get_items_subscribe(session, "openconfig-platform", "/openconfig-platform:*", dp_get_items_cb, NULL, 0, &subscription);
    if (rc != SR_ERR_OK)
    {
      goto error;
    }
```

**Comment by michalvasko** [comment]
Okay, you are subscribing to `/openconfig-platform:*` so there is no parent that *sysrepo* can provide you, `*parent` in the callback must be `NULL`. That means you must start with
```C
*parent = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(sess)), "/openconfig-platform:components/component[name='abc']/power-supply/state/openconfig-platform-psu:enabled", "false", 0, 0);
```
to create the top-level node and all the descendants. You could theoretically use the flag `LYD_PATH_OPT_NOPARENTRET` (notice I have mentioned this in my first reply) but the problem here is that you must still return the first top-level parent and you could use both the first and last created nodes (which *libyang* v2 allows, just for information). Anyway, you are fine with having the parent and then you simply get `state` like this
```C
struct lyd_node *state_node = (*parent)->child->child->next->child->child;
```
and then you can call
```C
lyd_new_path(state_node, NULL, "name", "abc", 0, 0);
```
or even
```C
lyd_new_leaf(state_node, NULL, "name", "abc");
```

**Comment by xheke** [comment]
Thanks Michal.

I still have some confusion for this question. but seems it is more complex to go ahead.

I hope in the future, Sysrepo can provide some API function to retrieve all suitable state node/leaf which match the request path by iterate just like module_change_subscribe provided, then it will easy to get these data from out-side system.

**Comment by michalvasko** [comment]
Well, then I am also still confused because I do not understand what exactly is it you mind and what you miss. It is impossible to compare `sr_module_change_subscribe()` and `sr_oper_get_items_subscribe()`, these functions have completely different functionality.

**Comment by xheke** [comment]
Yeah. my requirement is with certain request path for operational DS,  in theoretically, sysrepo already know all possible state node/leaf which match the config instance in running DS, and actually, sysrepo will filter-out invalid path (include invalid keys) and not invoke callback function.

So I think, if sysrepo can provide the iterate to retrieve all possible/valid node/leaf with the path for the certain request path, then plug-in program can retrieve data from out-side system by this iterate. It will help third-party developer use sysrepo already existed filter to reduce develop work.

**Comment by michalvasko** [comment]
It seems to me you would like back the oper data mechanism implemented in *sysrepo* v0.7.x (which was really inefficient). You can easily emulate it yourself in the callback and note that it will never be added back because like I said, there was a good reason why it was removed.

**Comment by xheke** [comment]
Yeah, **really inefficient** is good enough reason. So it better do retrieve all data in the call back function. 

For the *parent, from my view, below code 

case A:
`lyd_new_path(*parent, NULL, "/openconfig-platform:components/component[name='abc']/state/name", "abc", 0, 0);`

is better than

case B:
`lyd_new_path(state_node, NULL, "name", "abc", 0, 0);`

the path can be handled by the script or easy to handled by outside program.


Excuse me, I don't know how to use below flag and *parent,
Can I use below *parent in Case A?
Could you give some example for the model level in sr_oper_get_items_subscribe and related callback function based on Case A?

```
LYD_PATH_OPT_NOPARENTRET
struct lyd_node *state_node = (*parent)->child->child->next->child->child;
```

Anyway, if there are no way to get *parent directly on the model level,  currently I can use  

```
*parent = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(sess)), "/openconfig-platform:components/component[name='abc']/power-supply/state/openconfig-platform-psu:enabled", "false", 0, 0);
lyd_new_path(*parent, NULL, "/openconfig-platform:components/component[name='abc']/state/name", "abc", 0, 0);
lyd_new_path(*parent, NULL,  ....  );
lyd_new_path(*parent, NULL,  ....  );
.... ....

```

It just need to handle the first node/leaf in the special way, is that right?

**Comment by xheke** [comment]
Hi Michal,

I upgrade libyang / sysrepo / netopeer2 to latest code today.

I found `lyd_new_path` is changed and old version as below cannot use anymore. 

`*parent = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(sess)), "/openconfig-platform:components/component[name='abc']/power-supply/state/openconfig-platform-psu:enabled", "false", 0, 0);`


but the critical issue is when I try to configure running DS as yesterday, netopeer2  crashed with unknow reason:

```
> edit-config --target running --config=/mnt/sysrepo.example/c.nc.platform.power.replace.xml
nc ERROR: Session 1: SSH channel poll error (Socket error: disconnected).
cli_send_recv: Failed to receive a reply.
```

```
netopeer2-server: /src/CESNET/libyang/src/parser_xml.c:377: lydxml_data_check_opaq: Assertion `xmlctx->status == LYXML_ELEM_CONTENT' failed.
Aborted (core dumped) 
```

```
c.nc.platform.power.replace.xml
<components xmlns="http://openconfig.net/yang/platform"
xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0"
xc:operation="replace">
<component>
<name>abc</name>
<config>
<name>abc</name>
</config>
<power-supply>
<config>
<enabled xmlns="http://openconfig.net/yang/platform/psu">false</enabled>
</config>
</power-supply>
</component>
</components>

```

How to resolve this crash issue?

libyang commit:  69d9fff65abb58beb0bb6aa9ecacd572ca1dfc56

thanks,

**Comment by xheke** [comment]
Hi Michal,

Could you help me on this crash issue, do you need me create another issue to track it?

Thanks for you help, as you know, it break my test now :(

**Comment by michalvasko** [comment]
> do you need me create another issue to track it?

Yes, you definitely should have created a new issue but it is too late for that. If you update *libyang*, it should work now.

As for the original issue, I have completely lost track of what it is we are still discussing as there does not seem to be any actual issue. I am sorry, but I have way too much work so I am done with this issue.
