### ISSUE TITLE
sr_get_items fails with expression in xpath

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2461]
Hi,

I have issues with sr_get_items after this commit:
https://github.com/sysrepo/sysrepo/commit/39b38e5ac69a7f3982679086137c70502ba4d717

For example with the following yang model and config:

```
module test {
  yang-version 1.1;
  namespace "urn:com:test";
  prefix t;

  revision 2021-06-03 {
    description
      "Initial version";
  }

  container c {
    list l {
      key "id1 id2";
      leaf id1 {
        type uint32;
      }
      leaf id2 {
        type uint32;
      }
    }
  }
}

<c xmlns="urn:com:test">
  <l>
    <id1>1</id1>
    <id2>100</id2>
  </l>
  <l>
    <id1>2</id1>
    <id2>200</id2>
  </l>
</c>
```

Trying to get the xpath `"/test:c/l[position()=count(/test:c/l)]/id1"` I get libyang error result:
`libyang error: Schema node not found.`

Without this commit the get operation returns the selected element successfully.

Thanks!

**Comment by michalvasko** [comment]
There is a reason there was a new version released. I have actually tried to fix this but I would have to reimplement XPath in the transform function to even larger extent, which is not worth it. So now there is a choice between what will not be working, it is not really possible for every XPath to work correct in this version. I will keep it the way it is to avoid changes with disputable benefit, sorry.
