### ISSUE TITLE
sysrepo plugin crashed when try to print module_name in callback of sr_oper_get_items_subscribe

### ISSUE THREAD

**Issue by xheke** [sysrepo/sysrepo#2463]
Hi Michal,

The plugind was crashed abnormally.
Seems the module_name address transferred to callback function is not correct.

Please see below code and related gdb information.

sysrepo commit (devel):  b823dbd355937204cfe4abb59c5dca3810113953
Fri Jun 4 11:58:49 2021 +0200

```
    rc = sr_oper_get_items_subscribe(session, "openconfig-platform", "/openconfig-platform:*", dp_get_items_cb, NULL, 0, &subscription);
    if (rc != SR_ERR_OK)
    {
      goto error;
    }
```

```
Thread 3 "sysrepo-plugind" hit Breakpoint 1, dp_get_items_cb (session=0x7ffff0000bd0, 
    module_name=0x42 <error: Cannot access memory at address 0x42>, 
    xpath=0x6d99b0 "openconfig-platform", request_xpath=0x75b750 "/openconfig-platform:*", 
    request_id=4026536928, parent=0x1, private_data=0x7ffff5a14ce0)
    at /src/CESNET/sysrepo/examples/plugin/sragent.c:223
```

Thanks and Regards,
He Ke

**Comment by michalvasko** [comment]
Can you provide any more information? What do you mean by saying that "sysrepo-plugind was crashed", before or after the callback was called?

**Comment by xheke** [comment]
Sorry, it crashed after callback,

Seems here :
`module_name=0x42` is not correct  and
`xpath=0x6d99b0 "openconfig-platform"`  is more like module_name, but it should be xpath, such as "/openconfig-platform:components"
`parent=0x1`   not sure it is correct or not




```
static int
dp_get_items_cb(sr_session_ctx_t *session, const char *module_name, const char *xpath, const char *request_xpath,
        uint32_t request_id, struct lyd_node **parent, void *private_data)
{
  SRP_LOG_DBG("sragent(op): (heke1)   module_name: %s", module_name);  << crash here
```

**Comment by xheke** [comment]
Sorry, I just see the API is changed,  I will try it again.

typedef int(* sr_oper_get_items_cb)(sr_session_ctx_t *session, uint32_t sub_id, const char *module_name, const char *path, const char *request_xpath, uint32_t request_id, struct lyd_node **parent, void *private_data)
