### ISSUE TITLE
Cannot delete item from stored config false list

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2465]
Hi,

I have the following yang model and startup config:
 
```
module test {
  yang-version 1.1;
  namespace "urn:com:test";
  prefix t;
 
  revision 2021-06-07 {
    description
      "Initial version";
  }
 
  container c {
    list l {
      key "name";
      leaf name {
        type string;
      }
 
      list l2 {
          config false;
          key "id";
          leaf id {
              type uint32;
          }
          leaf val {
              type string;
          }
      }
    }
  }
}
 
<c xmlns="urn:com:test">
  <l>
    <name>item1</name>
  </l>
</c>
```
 
When I try to delete item from l2 list, I get invalid argument error.
I attached an example application:
[test.zip](https://github.com/sysrepo/sysrepo/files/6610752/test.zip)
 
```
$ ./test 
[ERR]: Invalid arguments for function "sr_delete_item".
Failed to delete list item: Invalid argument
```
 
It works on libyang1 branch without any issues.
 
libyang version: 2.0.11
sysrepo version: 2.0.7

Thanks!

**Comment by michalvasko** [comment]
Read the documentation of the function, you want to use `sr_oper_delete_item_str()`.

**Comment by awesomenode** [comment]
I missed this new function, thanks!
