### ISSUE TITLE
sr_get_change_tree_next returns invalid change

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2466]
Hi,

I have the following yang model and startup config:
 
```
module test {
  yang-version 1.1;
  namespace "urn:com:test";
  prefix t;
 
  revision 2021-06-07 {
    description
      "Initial version";
  }
 
  container c {
    list l {
      key "name";
      leaf name {
        type string;
      }
 
      list l2 {
          config false;
          key "id";
          leaf id {
              type uint32;
          }
          leaf val {
              type string;
          }
      }
    }
  }
}
 
 
<c xmlns="urn:com:test">
  <l>
    <name>item1</name>
  </l>
</c>
```
 
 
When val is updated in l2, the `sr_get_change_tree_next` function returns SR_OP_CREATED instead of SR_OP_MODIFIED, and change node contains the old value.
I attached an example to reproduce it:
[reprod.zip](https://github.com/sysrepo/sysrepo/files/6610780/reprod.zip)

 
```
$ ./reprod 
oper_change_cb called ==================================
Change op: 0
  data: <l2 xmlns="urn:com:test" xmlns:or="urn:ietf:params:xml:ns:yang:ietf-origin" or:origin="or:unknown">
  <id>1</id>
  <val>1</val>
</l2>
 
Change op: 0
  data: <id xmlns="urn:com:test">1</id>
 
Change op: 0
  data: <val xmlns="urn:com:test">1</val>
 
oper_change_cb called ==================================
Change op: 0
  data: <val xmlns="urn:com:test" xmlns:yang="urn:ietf:params:xml:ns:yang:1" yang:operation="create">1</val>
```
 
 
On libyang1 branch it returns SR_OP_MODIFIED and the new value:
 
```
$ ./reprod 
oper_change_cb called ==================================
Change op: 0
  data: <l2 xmlns="urn:com:test" xmlns:or="urn:ietf:params:xml:ns:yang:ietf-origin" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="create" or:origin="unknown"><id>1</id><val nc:operation="create">1</val></l2>
Change op: 0
  data: <id xmlns="urn:com:test">1</id>
Change op: 0
  data: <val xmlns="urn:com:test" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="create">1</val>
oper_change_cb called ==================================
Change op: 1
  data: <val xmlns="urn:com:test" xmlns:sr="http://www.sysrepo.org/yang/sysrepo" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="replace" sr:orig-value="1">2</val>
```
 
libyang version: 2.0.11
sysrepo version: 2.0.7

Thanks!

**Comment by michalvasko** [comment]
Yes, this is a new feature. Without going into too many details, you are now notified about the "intentional" changes in the `operational` datastore. Because the actual change always depends on current `running` data and it may keep changing during the `operational` data lifetime. And since `operational` data are now independent of `running` (the actual stored data, not the full `operational` datastore), this change was only natural.

**Comment by awesomenode** [comment]
Thank you for the answer.
I probably understand why it is SR_OP_CREATED instead of SR_OP_MODIFIED, but I can't see why it returns always the old value.
I tried deleting the old data using sr_oper_delete_item_str() before I set the new value, but I still get the old value in the change iterator.
Is it also intentional?

**Comment by michalvasko** [comment]
Yep, this was a bug, should now be fixed with a test included.

**Comment by awesomenode** [comment]
Now it returns the new value with the latest version.
Thanks!
