### ISSUE TITLE
Sysrepo --datastore running has the same configuration as --startup after reboot

### ISSUE THREAD

**Issue by Abrahamma97** [sysrepo/sysrepo#2468]
Hi @michalvasko ,
Earlier It was observed that after we reboot our system, out  sysrepocfg running configurations got cleared and hence using our applications we copied everything from startup to running.

But when I tried with  a Sysrepo version released in march I could see that startup gets automatically copied to running and hence this will affect our call back functions for change in elements  of our apps as the apps subscribe after the running is updated.

Is this expected and if so can you suggest a possible solution for the same.

Thanks and Regards

**Comment by Abrahamma97** [comment]
Hi @michalvasko  can you help?
Thanks in advance

**Comment by michalvasko** [comment]
You are right, *sysrepo* v1 and v2 copy `startup` into `running` automatically when the first *sysrepo* application (such as *netopeer2*) start after reboot. Please look at [SR_SUBSCR_ENABLED](https://netopeer.liberouter.org/doc/sysrepo/libyang1/html/group__subs__api.html#ggac91898627ad5aeb589e6a3993a697d14ac5b782dfbbfe74c8ff2b1642a8bb0afe) flag that should basically get you the old functionality.

**Comment by Abrahamma97** [comment]
Hi @michalvasko,
When we used without SR_SUBSCR_ENABLED we had got  Event Change and Event Done.
After using SR_SUBSCR_ENABLED  we have seen  Event abort and Event done.

**Comment by Abrahamma97** [comment]
Hi @michalvasko ,
Can you help out when you are free as I see here a potential bug right?

**Comment by michalvasko** [comment]
I do not think this is really happening, you should be getting `SR_EV_ENABLED` and `SR_EV_DONE`.

**Comment by Abrahamma97** [comment]
Actually I am getting SR_EV_ABORT and SR_EV_DONE. 
Can you suggest a stable release in master branch for the same so that I can check that out?

**Comment by michalvasko** [comment]
By the way, this should have been a new issue since it is in no way related to the original one. In any case, the subscribe call seems fine except for `path of yang`, which should simply be the YANG module name but I am not sure what you meant exactly. Anyway, subscriptions with this flag are commonly used and even part of the tests so I really do not think there is such a basic bug.

**Comment by Abrahamma97** [comment]
Yes I got it working. It was a mistake from my end sorry. I mistook SR_EV_ENABLED to SR_EV_ABORT
