### ISSUE TITLE
Support options available

### ISSUE THREAD

**Issue by meghna-doshi** [sysrepo/sysrepo#2469]
Hi,
We wanted to know what kind of support options are available if we use sysrepo (mostly options available for paid support).

Regards,
Meghna

**Comment by michalvasko** [comment]
You can write me an email and we can discuss the options there are.

**Comment by meghna-doshi** [comment]
Mail id please.

**Comment by michalvasko** [comment]
It is in my profile, mvasko@cesnet.cz.
