### ISSUE TITLE
RPC out error,Invalid leafref value 

### ISSUE THREAD

**Issue by mx568549060** [sysrepo/sysrepo#2471]
```
libnetconf2-2.0.1
libyang-2.0.7
netopeer2-2.0.0
sysrepo-2.0.1
```

when I run the RPC, the out part error occur.It show  `Invalid leafref value "/1/1/1/1/1"` ,actually "/1/1/1/1/1" have created.

yang

```yang
rpc create-eth-connection {
...
output {
    container connection {
                    uses acc-con:connection;
                }
...
}
}
```

```
module acc-connection {
    prefix acc-con;
    grouping connection {
        ...
        leaf-list ctp {
            type leafref {
                path '/acc-devm:ctps/acc-devm:ctp/acc-devm:name';
            }
            min-elements 2;
            description " ";
        }
        ...
}
}
```

rpc C code 
```C
sr_val_set_xpath(&(*output)[i], "/acc-eth:create-eth-connection/connection/ctp");
```

error show in netopeer2 log
```
[ERR]: LY: Invalid leafref value "/1/1/1/1/1" - no existing target instance "/acc-devm:ctps/acc-devm:ctp/acc-devm:name". (Schema location /acc-eth:create-eth-connection/output/connection/ctp, data location /acc-eth:create-eth-connection/connection/ctp[2].)
[ERR]: SR: Invalid leafref value "/1/1/1/1/1" - no existing target instance "/acc-devm:ctps/acc-devm:ctp/acc-devm:name".
```

sysrepo data
```
/acc-devm:ctps/ctp[name='/1/1/1/1/1'] (list instance)
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/name = /1/1/1/1/1
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/state-pac (container)
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/state-pac/admin-state = enabled
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/layer-protocol-name = acc-eth:ETH
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/server-tp = /HC-OTN208_BOX_NETCONFIG/1/1/1/1
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/client-tp = /HC-OTN208_BOX_NETCONFIG/1/1/1/1
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/loop-back = non-loopback [default]
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/acc-eth:eth-ctp-pac (container)
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/acc-eth:eth-ctp-pac/vlan-spec (container)
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/acc-eth:eth-ctp-pac/vlan-spec/vlan-id = 0
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/acc-eth:eth-ctp-pac/vlan-spec/vlan-priority = 0
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/acc-eth:eth-ctp-pac/vlan-spec/access-action = keep
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/acc-eth:eth-ctp-pac/vlan-spec/vlan-type = c-tag
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/acc-eth:eth-ctp-pac/client-vlan-spec (container)
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/acc-eth:eth-ctp-pac/client-vlan-spec/vlan-id = 17
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/acc-eth:eth-ctp-pac/client-vlan-spec/vlan-priority = 3
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/acc-eth:eth-ctp-pac/client-vlan-spec/access-action = push_pop
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/acc-eth:eth-ctp-pac/client-vlan-spec/vlan-type = s-tag
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/acc-eth:eth-ctp-pac/oam-state-pac (container)
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/acc-eth:eth-ctp-pac/oam-state-pac/dm-state = true
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/acc-eth:eth-ctp-pac/oam-state-pac/tm-state = true
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/acc-eth:eth-ctp-pac/oam-state-pac/lm-state = true
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/acc-eth:eth-ctp-pac/oam-state-pac/cc-state = true
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/acc-eth:eth-ctp-pac/oam-config (container)
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/acc-eth:eth-ctp-pac/oam-config/mep-id = 21
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/acc-eth:eth-ctp-pac/oam-config/remote-mep-id = 22
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/acc-eth:eth-ctp-pac/oam-config/meg-id = meg-id
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/acc-eth:eth-ctp-pac/oam-config/mel = 5
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/acc-eth:eth-ctp-pac/oam-config/cc-interval = interval-3ms33
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/acc-eth:eth-ctp-pac/oam-config/lm-interval = interval-10s
/acc-devm:ctps/ctp[name='/1/1/1/1/1']/acc-eth:eth-ctp-pac/oam-config/dm-interval = interval-1s
```

**Comment by mx568549060** [comment]
when I change the yang file like this ,it works fine.

```
        leaf-list ctp {
            type string;
         
            description " ";
        }
```

**Comment by michalvasko** [comment]
How did you retrieve "sysrepo data"? As [documented](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__rpc__subs__api.html#ga31d0e43005f1bb9822b9e382d7c6c8fe), the RPC input/output must be valid with `operational` datastore.

**Comment by mx568549060** [comment]
> How did you retrieve "sysrepo data"? As [documented](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__rpc__subs__api.html#ga31d0e43005f1bb9822b9e382d7c6c8fe), the RPC input/output must be valid with `operational` datastore.

Sorry for not explain clear of "sysrepo data". I use `sr_get_items_example` to  retrieve "sysrepo data".
The "sysrepo data" is the RPC OUT data `/acc-eth:create-eth-connection/connection/ctp`  leafref  to.
By  use `sr_get_items_example`, the data  `/acc-devm:ctps/ctp[name='/1/1/1/1/1']` actually exist.
when I change `/acc-eth:create-eth-connection/connection/ctp`  property `leafref ` to `type string` ，the `Invalid leafref value "/1/1/1/1/1"` error not happen.

**Comment by mx568549060** [comment]
@michalvasko 
I write a simple case.
[rpc_subscribe_example_11.c.txt](https://github.com/sysrepo/sysrepo/files/6652547/rpc_subscribe_example_11.c.txt)
[rpc_send_example_11.c.txt](https://github.com/sysrepo/sysrepo/files/6652548/rpc_send_example_11.c.txt)

**Comment by mx568549060** [comment]
> [rpc_subscribe_example_11.c.txt](https://github.com/sysrepo/sysrepo/files/6652547/rpc_subscribe_example_11.c.txt)

the 11 case not suitable,the 12 case more suitable.

[rpc_send_example_12.c.txt](https://github.com/sysrepo/sysrepo/files/6654365/rpc_send_example_12.c.txt)
[rpc_subscribe_example_12.c.txt](https://github.com/sysrepo/sysrepo/files/6654366/rpc_subscribe_example_12.c.txt)
[ops-test.yang.txt](https://github.com/sysrepo/sysrepo/files/6654371/ops-test.yang.txt)
[ops-ref-test.yang.txt](https://github.com/sysrepo/sysrepo/files/6654372/ops-ref-test.yang.txt)

**Comment by michalvasko** [comment]
I can only repeat what I said, the data must exists in the **operational** datastore, you have them only in **running**.

**Comment by mx568549060** [comment]
> I can only repeat what I said, the data must exist in the **operational** datastore, you have them only in **running**.

Thank you for replay,I will study carefully what you say.
