### ISSUE TITLE
Error while loading an augmented module[Prefix not defined]

### ISSUE THREAD

**Issue by ankit7gup** [sysrepo/sysrepo#2473]
Hi Michal,

We are loading some augmented data models. While doing that getting below error.

 97 [ERR]: Invalid absolute-schema-nodeid nametest "hw:hardware" - prefix "hw" not defined in module "o-ran-hardware".^M
 98 sysrepoctl error: Failed to install module "/home/ankito-ran-hardware.yang" (libyang error)^M
 
 
Attached the yang files for reference. 

[o-ran-hardware-augment.txt.txt](https://github.com/sysrepo/sysrepo/files/6639236/o-ran-hardware-augment.txt.txt)
[o-ran-hardware.txt.txt](https://github.com/sysrepo/sysrepo/files/6639306/o-ran-hardware.txt.txt)

Thanks!

Regards,
Ankit

**Comment by michalvasko** [comment]
Right, should work now.
