### ISSUE TITLE
Query regarding core dump file location and multiple connection 

### ISSUE THREAD

**Issue by ChinmayaAgarwal** [sysrepo/sysrepo#2474]
Hi,

We have been observing crashes with netopeer2 server (with Sysrepo (v1.4.122) and Netopeer2 (v1.1.70) RELEASE builds). But we are not able to find the core dump file for the same. Where can we find the core dump file for netopeer2 server?

Also, does netopeer2 and sysrepo architecture support multiple connection on the same netopeer2 server with different IPs. If yes, is there a limit on the number of instances? Because, we have been observing netopeer2 crashes at random places with multiple instances.

Thanks and Regards,
Chinmaya Agarwal.

**Comment by michalvasko** [comment]
> Where can we find the core dump file for netopeer2 server?

This has nothing to do with *netopeer2* itself, it is based on some kernel options.

> does netopeer2 and sysrepo architecture support multiple connection on the same netopeer2 server with different IPs.

It should but yes, it seems there is a problem (#2459) that I have not yet got to look at.
