### ISSUE TITLE
Deadlock with concurrent get and edit

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2479]
Hi,

I encountered a deadlock issue with `sr_get_items()` and `sr_apply_changes()`:
- `sr_get_items()` operation is in progress with oper data provider callbacks in model B
- `sr_apply_changes()` tries to edit data in model A and B
- it write locks model A, then tries to lock B
- since B is read locked by `sr_get_items()`, it is waiting on it
- in the event handler thread (invoking oper data provider callback) the function `sr_shmmod_release_locks` (called from callback session's `sr_session_stop`) tries to read lock all modules
- since A is write locked it will time out
 
I attached an example application to reproduce it:
[reprod.zip](https://github.com/sysrepo/sysrepo/files/6655517/reprod.zip)
 
```
$ sysrepoctl -i ./yang/ietf-system@2014-08-06.yang -s./yang
$ sysrepoctl -i ./yang/ietf-interfaces@2018-02-20.yang -s./yang
$ sysrepoctl -i ./yang/iana-if-type@2018-07-03.yang -s./yang
 
$ ./subscribe & 
....
$ ./get & ./edit 
...
[ERR]: Callback event "operational" with ID 45 processing timed out.
[WRN]: Event "operational" with ID 45 failed (Timeout expired).
get error, rc=14
```
 
It is present both on libyang1 and libyang2 versions.
 
libyang1 version: 1.0.241
sysrepo1 version: 1.4.141
 
libyang2 version: 2.0.16
sysrepo2 version: 2.0.8

Thanks!

**Comment by michalvasko** [comment]
Okay, should now work in *sysrepo* v2 and if not critical, I would leave it the way it is in v1. But I have not looked at the relevant code there, if the same fix could be applied that it would not be a problem.

**Comment by awesomenode** [comment]
Thank you for the fast fix, the deadlock issue is gone on sysrepo2.
Currently I'm not able to switch to sysrepo2 therefore I tried to apply the patch on libyang1 branch, but I met several conflicts.
Can you please help me getting this patch working on v1 too?

**Comment by Reshad-Rahman** [comment]
Ack, it'd be great to get this fix on v1 too.

**Comment by michalvasko** [comment]
Fine, should be fixed for v1, too.

**Comment by awesomenode** [comment]
It works on libyang1 branch too. Thanks!
