### ISSUE TITLE
sysrepo v2.0.1: error when importing model into sysrepo DB

### ISSUE THREAD

**Issue by igortern** [sysrepo/sysrepo#2481]
Hi,
I've a problem after upgrading to 2.x libyang, sysrepo. Importing yang models into sysrepo using sysrepoctl fails. The same models can be imported in the same order by v1.x without any problem.

The error is:
[ERR]: Augment target node "/if:interfaces/if:interface/bbf-qos-tm:tm-root/bbf-qos-tm:children-type/bbf-qos-tm:queues/bbf-qos-tm:queue/bbf-qos-tm:queue-scheduling-cfg-type/bbf-qos-tm:inline" from module "bbf-qos-shaping" was not found.
[ERR]: Augment target node "/if:interfaces/if:interface/bbf-qos-tm:tm-root" from module "bbf-qos-shaping" was not found.

If I re-arrange modules so that bbf-qos-traffic-mgmt.yang is imported before bbf-qos-shaping.yang the import process progresses further and fails with another error which appears to be wrong.

[ERR]: Augment target node "/if:interfaces/if:interface" from module "bbf-qos-enhanced-scheduling" was not found.
sysrepoctl error: Failed to install module "/home/igort/Perforce/OLT/aspen/main/third_party/yang-models/OB-BAA-standard-olt-adapter/4.1/yang/bbf-interface-port-reference.yang" (libyang error)

Attached are:
- yang.tar.gz - YANG models
- sysrepoctl_commands.txt - sysrepoctl commands up to the point of failure
- yang_models_list.txt - a full list of models that have to be imported

Could you help?

Best Regards,
Igor

[yang.tar.gz](https://github.com/sysrepo/sysrepo/files/6660395/yang.tar.gz)
[yang_models_list.txt](https://github.com/sysrepo/sysrepo/files/6660396/yang_models_list.txt)
[sysrepoctl_commands.txt](https://github.com/sysrepo/sysrepo/files/6660400/sysrepoctl_commands.txt)

**Comment by michalvasko** [comment]
Please try the latest `devel` versions (you should always before creating an issue), I believe this has already been fixed, in *libyang*.

**Comment by igortern** [comment]
Thanks

**Comment by igortern** [comment]
i tried with devel and import still fails albeit in a different place. the same import sequence works with 1.x libyang & syrepo versions.
Attached are: 1) command sequence up to the point of failure 2) models

The error is
~/Perforce/OLT/aspen/main/third_party/yang-models/OB-BAA-standard-olt-adapter/2.0/yang
[ERR]: Not found node "access-point" in path.
sysrepoctl error: Failed to apply changes (libyang error)
For more details you may try to increase the verbosity up to "-v3".

Regards,
Igor
[syrepo-import-commands.txt](https://github.com/sysrepo/sysrepo/files/6697904/syrepo-import-commands.txt)
[ob-baa-models_2.0.tar.gz](https://github.com/sysrepo/sysrepo/files/6697887/ob-baa-models_2.0.tar.gz)

**Comment by michalvasko** [comment]
Right, should work now.

**Comment by igortern** [comment]
thanks.
it progressed further and failed with a different error
```
[ERR]: A current definition "g9982" is not allowed to reference deprecated definition "status".
sysrepoctl error: Failed to install module "/home/igort/Perforce/OLT/aspen/main/third_party/yang-models/OB-BAA-standard-olt-adapter/2.0/yang/bbf-gbond-state.yang" (libyang error)

```
The error looks  incorrect since it is legal to refer from "current" definition to "deprecated" in a different module.
the updated import script up to the point of failure and also a full module list in installation order are attached.

Note that the new version appears to be much slower than 1.x (I didn't measure it but subjectively based on the total run time it it 50-100% slower).

[sysrepo-import-commands.txt](https://github.com/sysrepo/sysrepo/files/6705572/sysrepo-import-commands.txt)
[obbaa_models.txt](https://github.com/sysrepo/sysrepo/files/6705581/obbaa_models.txt)

**Comment by michalvasko** [comment]
This was a regular bug, had nothing to do with different status states, should be fixed now.

**Comment by igortern** [comment]
it progressed further and now dies on assertion
`sysrepoctl: /home/igort/Perforce/OLT/aspen/main/build/host-sim/third_party/libyang/libyang-devel/src/xpath.c:3756: xpath_deref: Assertion `!rc' failed.
`
install script up to the point of failure is attached
[sysrepo-import-commands.txt](https://github.com/sysrepo/sysrepo/files/6707559/sysrepo-import-commands.txt)

**Comment by michalvasko** [comment]
Okay, fixed (forgot to reference this time). It would be best if you could provide the whole set of modules you are installing so that I can fix all the problems in one go. As for your slower performance observation, you are right, module compilation is slower but it is not really that important so we are focusing on other work. However, the optimization are already designed so they may be implemented fairly soon.

**Comment by igortern** [comment]
import works now. Thanks!
