### ISSUE TITLE
cpp binding are removed from sysrepo 2.0 version, 

### ISSUE THREAD

**Issue by iGovindY** [sysrepo/sysrepo#2482]
Hi, 
we are not able to find CPP bindings after rebasing to 2.0 version. 

is this permanently removed? 
if yes, why? 
if no, when can we expect them to be included in sysrepo?
or 
is there any separate repo with CPP bindings like for [Python](https://github.com/sysrepo/sysrepo-python)?

Thanks
Govind

**Comment by michalvasko** [comment]
Yes, there will be a separate repo and the bindings will be based on [libyang C++](https://github.com/CESNET/libyang/issues/1596) bindings, so it is going to take some time.

**Comment by iGovindY** [comment]
expected timeline for this?

might help us in deciding whether to wait for it or change our application code to use `  C `  APIs

**Comment by michalvasko** [comment]
That can only be answered by the author, @syyyr. But you can also wait with switching to v2 of the projects until the bindings are ready if you do not need any new features.

**Comment by syyyr** [comment]
Hi, I'm currently working on C++ bindings for libyang (https://github.com/cesnet/libyang-cpp). Right now, I'm focusing on adding feratures so that I can port https://github.com/cesnet/netconf-cli. I hope can port most of it this week.

**Comment by iGovindY** [comment]
Thanks @syyyr, do give us an update when sysrepo cpp binding are available for use.

**Comment by UndarkAido** [comment]
Looks like he forgot to update, I don't know what stage they're in though: https://github.com/sysrepo/sysrepo-cpp

**Comment by syyyr** [comment]
I am adding features as I'm porting our apps that use sysrepo. A lot of the basic stuff is implemented, not everything though. I have underestimated the time it would take to create the bindings.
