### ISSUE TITLE
Internal error when trying to change operDB readonly leaf of the list

### ISSUE THREAD

**Issue by maunangc** [sysrepo/sysrepo#2484]
I am initializing one of the read-only leaf of list for one of our Yang during the server initialization. 

Some of other rw leaf of the same list are edited by remote client through edit config. 

Post this when I am trying to change this same read only leaf of the list, using set_item() and then apply_changes(), this operation is failing with exception "Internal error". 

Please suggest the correct steps to change this read-only leaf on the run time. 
(Using Sysrepo version v1.4.70 and Netopeer server 1.1.39)

**Comment by michalvasko** [comment]
Firstly, you will have to update *sysrepo* to the latest v1 or v2 version. I think this was fixed.

**Comment by maunangc** [comment]
Thanks for the response. 

Do we have patch for this issue? Which we can port on top of the sysrepo version we are using?

**Comment by michalvasko** [comment]
You can search some old issues, I suppose. i am sorry, but I have no time to waste searching for the exact fix, you are using quite an old version so there are lots of new commits.
