### ISSUE TITLE
Failed to execute sr_apply_changes function after calling sr_set_item_str

### ISSUE THREAD

**Issue by itercheng** [sysrepo/sysrepo#2492]
Dear expert:

I'm encountering an problem with sr_apply_changes.  Details steps as follows:

firstly to configure  running data by executing function sr_set_item_str,
   
     Xpath： /YC_M:Gyc/LockLatitude                      Value: 34224572
     Xpath： /YC_M:Gyc/LockLongitude                    Value: 108880720
     Xpath： /YC_M:Gyc/NumberOfSatellites            Value: 8

these three commands could be executed successfully for  sr_set_item_str, the error is reported when executing sr_apply_changes that return a error-code (3) SR_ERR_SYS,  Could you please help me more in this issue ? if you need more logs or info please let me know.  thank you in advance.  Yang and data store can work well too so that ignore their issue.

**Comment by michalvasko** [comment]
So what is the error message? But the return value is strange.

**Comment by itercheng** [comment]
Thank you fast reply. we expect this result is "SR_ERR_OK" after calling sr_apply_changes function,  while the actual result is "SR_ERR_SYS". then i tried to execute "sysrepocfg -X" commands  in another terminal, the following messages was printed:

[ERR]: flock() failed(Resource temporarily unavailable).
sysrepocfg error: Failed to connect (System function call failed).

I don't know what those mean?

**Comment by michalvasko** [comment]
What platform are you on exactly?

**Comment by itercheng** [comment]
The software platform is  LInux (centos 7).  the hard platform is arm.  Today i also found a phenomenon in my environment that a session could  periodically write running sr successfully (while it didn't occupy the running sr all the time). but other session can't access it.   such as "sysrepocfg -X" reports previous error if execute.

sysrepo version : 5.6.38
libyang version: 1.10.17

**Comment by michalvasko** [comment]
This is what my `man` page says about `EAGAIN` for `fcntl()` (it is probably called with `F_GETLK`, possibly `F_SETLK`), which should be the error code you got:
```
       EACCES or EAGAIN
              Operation is prohibited by locks held by other processes.

       EAGAIN The operation is prohibited because the file has been memory-mapped by another process.
```
I am not sure what to do with this information, though. You are the first to report such an error and you are using an old distribution and on ARM, so there may be some differences compared to modern distributions on x86. So I would start by updating to the latest `libyang1` branch *sysrepo* and if the problem persists, looking into your manual whether there is not some more information.
