### ISSUE TITLE
High-frequency data in the operational datastore design issue

### ISSUE THREAD

**Issue by dumitrupaul** [sysrepo/sysrepo#2496]
Hello,
This will be more of a design question/issue than an actual bug, so let's start with an example module:

```
module sensor-notifications-example {
  namespace "example-namespace:sensor-notifications";
  yang-version 1.1;
  prefix sensor-notif;

  list sensor-component {
    key name;
    leaf name {
      type string;
      description "Sensor name";
    }

    leaf value {
      config false;
      type uint64;
      description "Sensor value";
    }

    container notifications {
      description "Configure threshold notifications for sensors values that are being
        monitored.";
      leaf poll-interval {
        type uint32 {
          range 1..max;
        }
        description "Interval between consecutive sensor data collection triggers";
        default 60;
        units "seconds";
      }

      leaf max-threshold-value {
        type uint32;
        description "Send notification when the sensor-value exceeds the
                configured threshold";
      }
    }
  }

  notification sensor-threshold-exceeded {
    description "Notifications to be sent when a sensor value crosses
                a configured threshold.";

    leaf name {
      type leafref {
        path "/sensor-component/name";
      }
      description
        "Name of the sensor-threshold.";
    }

    leaf threshold-value {
      type leafref {
        path "/sensor-component/notifications/max-threshold-value";
      }
    }

    leaf sensor-value {
      type leafref {
        path "/sensor-component/value";
      }
    }
  }
}
```

In this module consider I'm trying to obtain information about sensor values through operational callbacks while also having notifications when certain thresholds are exceeded. Let's say a sampling interval for the sensors is about 100ms.
Now imagine that we have configured a temperature sensor with a threshold of about 60 temperature units:
```
<sensor-component xmlns="example-namespace:sensor-notifications">
    <name>cpu-core/temp1</name>
    <notifications>
        <max-threshold-value>60</max-threshold-value>
    </notifications>
</sensor-component>
```

On the implementation side, based on the configured poll-interval, the sensor value is checked to not exceed the configured threshold. When the temperature sensor exceeds 'max-threshold-value' units the notification 'sensor-threshold-exceeded' is sent which internally (in sysrepo) triggers an operational callback to resolve the leafref paths. The problem here is that between the first sensor value (the one that triggered the notification) and the second sensor value (the one got in the callback) a time interval longer than the sampling interval is passed and thus the values could be different causing libyang to output the LYE_NOLEAFREF error.

From my point of view the YANG design looks intuitive so should this high-frequency data use case be treated with special care in the implementation? Is this a sysrepo/libyang limitation?

**Comment by michalvasko** [comment]
Yes, I would say this is currently a performance limitation, we plan to do some optimizations in the upcoming weeks or months. However, disregarding that, I would say always retrieving the data for notification validation is redundant. So my suggestion would be to make the leafrefs `require-instance false` and it should work as expected.

**Comment by dumitrupaul** [comment]
Thanks for the quick answer, will definetly use `require-instance false` for now.
