### ISSUE TITLE
Lock acquiring without releasing in the function sr_modinfo_module_srmon_locks_ds

### ISSUE THREAD

**Issue by ycaibb** [sysrepo/sysrepo#2497]
Hi, developers, I found the &rwlock->r_mutex may not be released when the condition of return met. Thank you for your checking.
https://github.com/sysrepo/sysrepo/blob/92e161a8c7f0daec95d8818c6e32796efd429747/src/modinfo.c#L1157

```
 if (ret) {
        SR_ERRINFO_INT(&err_info);
        return err_info;
    }
```

**Comment by ycaibb** [comment]
the same here

https://github.com/sysrepo/sysrepo/blob/92e161a8c7f0daec95d8818c6e32796efd429747/src/modinfo.c#L1227

**Comment by michalvasko** [comment]
Can you name a non-zero return value (error code) that acquires the lock?
