### ISSUE TITLE
Query about handling multiple YANG modules 

### ISSUE THREAD

**Issue by mrsugaranil** [sysrepo/sysrepo#2498]
Hi Michal,

I would like to ask about handling multiple YANG modules. I have an opinion how to do it but I would like to confirm it. As I understand from documents, sysrepo API's are thread safe so we can use them under one process. For example, I have multiple YANG modules in the sysrepo at NETCONF Server. 
1- Reset Watchdog YANG module
2- Read temp sensor YANG module
3- Download Software YANG module
4- so on....

Should I handle them in every different thread? Is it the way how work with sysrepo? My purpose is to write callbacks for each related YANG module in each thread. 

Best Regards,
Anil

**Comment by michalvasko** [comment]
If you want some events being handled concurrently, you must have their handling in separate threads, obviously. By default, there is a single thread for every subscription structure, so you can simply create separate ones for each event. But note that they will be executed concurrently only when using *sysrepo* applications and API calls, it will be serialized when communicating by NETCONF using *netopeer2*.

**Comment by mrsugaranil** [comment]
Thank you for quick response.
