### ISSUE TITLE
setting config-false list with config-true key using sysrepo 0.7.8

### ISSUE THREAD

**Issue by ormargol** [sysrepo/sysrepo#2502]
Hi,

I am using attached "example.yang" model, which has list with config-true key and config-false field.
I am also using attached "oper_data_example.c" to read-write to this model.

However, I see the screen paused for few seconds, and then execution is done without getting me the data.
If I am setting the entire list and the key to be config false, it works.

I am using sysrepo 0.7.8 and it's very complex to upgrade now, so I would appreciate if there is a solution for my version.

Thanks,
Orr Margaliot.
[srbug.zip](https://github.com/sysrepo/sysrepo/files/6759664/srbug.zip)

**Comment by michalvasko** [comment]
I am sorry but I am not able to help at all, we no longer support that version and I just have absolutely no spare time even if I wanted to fix it.
