### ISSUE TITLE
assertion in tree_schema_helpers.c when adding a model to sysrepo 

### ISSUE THREAD

**Issue by igortern** [sysrepo/sysrepo#2503]
Hi,
- libyang and sysrepo packages from devel, taken today (July 5)
- attempt to add a model to sysrepo fails with message 
`sysrepoctl: /home/igort/Perforce/OLT/aspen/main/build/host-sim/third_party/libyang/libyang-devel/src/tree_schema_helpers.c:814: lys_parse_load: Assertion `mod && new_mods' failed.`

The issue is easy to reproduce using the attached sysrepo database and YANG models:
`bin/sysrepoctl --install yang/bbf-l2-forwarding.yang -a --search-dirs yang`

[yang.tar.gz](https://github.com/sysrepo/sysrepo/files/6761047/yang.tar.gz)
[sysrepo.tar.gz](https://github.com/sysrepo/sysrepo/files/6761050/sysrepo.tar.gz)

**Comment by michalvasko** [comment]
Should be fixed, duplicate of https://github.com/CESNET/libyang/issues/1646.

**Comment by igortern** [comment]
this is fixed, thanks
