### ISSUE TITLE
Question about UNIX Sockets and Subscription

### ISSUE THREAD

**Issue by mrsugaranil** [sysrepo/sysrepo#2506]
Hi Michal,

I would like to ask about something about subscriptions and UNIX sockets. As you said, every sr_module_change_subscribe or other subscribes naturally start a new thread. So, for 10 YANG modules, there will be 10 different callback threads under one main process. If I handle my processes(get items or set items) in 10 different callback functions, it is OK. However, if I want to send or receive module configurations or state datas over UNIX domain sockets to another process in the callbacks, is it a good design concept for Sysrepo ? In other words, with 10 different client UNIX Sockets in each callback functions, can I handle IPC mechanism from Sysrepo to other process? If yes, is there any specific flags to use? As I understand from comments in here, I do not need to create threads to handle different processes ( using pthread_create). 

I plan to use one connection and one session for all subscriptions. Or should I open one connection and 10 sessions for each callback ?

Thank you very much
Best regards,
Anil

**Comment by michalvasko** [comment]
I cannot say I understand what your architecture is, what about the UNIX sockets? *sysrepo* does not use any. There may only be problems if a thread is handling some event that eventually triggers another event handled by the same thread, you get a deadlock that way. And you are free to divide your subscriptions into threads (subscription structures) whatever way you want, in your scenario you may have 1 or up to 10 threads.

**Comment by mrsugaranil** [comment]
My purpose is to transfer datas to another process using IPC method (UNIX domain sockets). Actually, I wonder that in subscription structures lets say 10 different threads for 10 different YANG models, I will transmit the data over UNIX socket which is set up in each subscription callbacks. In other word, each callback function will connect to another process with UNIX sockets (10 differents clients in callbacks of subscriptions to 1 server process). Is there any danger situation? I digged many issues in here but I havent met these kind of design methodology. Maybe it is not a convenient way for sysrepo APIs.

**Comment by michalvasko** [comment]
> My purpose is to transfer datas to another process using IPC method (UNIX domain sockets).

And how is that relevant for *sysrepo*? I still do not know so my guess is that it is not and you can communicate however you want. The only problem would be if you were, for example, reading some data from the socket in a callback and while waiting for them, the callback can easily time out.

**Comment by mrsugaranil** [comment]
Okey, I got it. Apparently, sysrepo callbacks are just threads so everything is same with thread design. Thank you very much Michal, by the way congratulation! You did a really great job with creating these APIs!

Best Regards,
Anil

**Comment by michalvasko** [comment]
Um, thanks, glad to hear it.
