### ISSUE TITLE
Can't retrieve container /oven:oven-state leaves

### ISSUE THREAD

**Issue by maciek-k1** [sysrepo/sysrepo#2509]
Hi Michal,
I'm currently on devel branch (incl. libyang). Trying to run example `./oper_data_pull_example `with _sr_oper_get_items_subscribe_ function modified to use option _sr_subscr_options_t_ as _SR_SUBSCR_OPER_MERGE_ rather than _0_ as it is by default, according to what you pointed out [here](https://github.com/sysrepo/sysrepo/issues/1937#issuecomment-621881477). For some reason I'm still not getting the /oven:oven-state leaves data. Running
`./sr_get_items_example /oven:*//. operational`
and getting 
`/oven:oven (container)
/oven:oven/turned-on = true
/oven:oven/temperature = 200
/oven:oven-state (container)`
I'm not sure what it is that I'm doing wrong. I've seen this issue pop up [earlier](https://github.com/sysrepo/sysrepo/issues/1716), but unsure whether this is what's causing it or something else I've missed. I've also tried following the [plugin](https://netopeer.liberouter.org/doc/sysrepo/devel/html/example.html) example, and for some reason I'm not seeing any notifications when I run `./notif_subscribe_example oven` in parallel with `sysrepocfg --edit=vim --datastore running
<oven xmlns="urn:sysrepo:oven">
    <turned-on>true</turned-on>
    <temperature>200</temperature>
</oven>` despite the fact that I can see the configuration changes in several ways. Any help would be appreciated, got stuck on this while still learning NETCONF and sysrepo :)
Thanks!

**Comment by michalvasko** [comment]
Seems you have 2 issues so I would try to fix them one-at-a-time. Regarding the first one, `oper_data_pull_example` does not provide any `oven` data by default, have you modified it? If so, please attach it.

**Comment by maciek-k1** [comment]
Thank you for your reply.
You brought my attention to something I've omitted (haven't realised _oper_data_pull_example_ is _example_ module-specific), fixed it now, but issue persists. I now generate another _oper_data_pull_oven_ apart from _oper_data_pull_example_, with following bits of code changed (and added - sub_options):

```
dp_get_items_cb(sr_session_ctx_t *session, uint32_t sub_id, const char *module_name, const char *xpath,
        const char *request_xpath, uint32_t request_id, struct lyd_node **parent, void *private_data)
{
    (void)session;
    (void)sub_id;
    (void)request_xpath;
    (void)request_id;
    (void)private_data;`

    printf("\n\n ========== DATA FOR \"%s\" \"%s\" REQUESTED =======================\n\n", module_name, xpath);

    if (!strcmp(module_name, "oven") && !strcmp(xpath, "/oven:oven-state")) {
        lyd_new_path(NULL, sr_get_context(sr_session_get_connection(session)), "/oven:oven-state/temperature", "221", 0, parent);
        lyd_new_path(*parent, NULL, "/oven:oven-state/food-inside", 1, 0, NULL);
    }

    return SR_ERR_OK;
}
(...)
sr_subscr_options_t sub_options = SR_SUBSCR_OPER_MERGE;
(...)
/* subscribe for providing the operational data */
    rc = sr_oper_get_items_subscribe(session, mod_name, path, dp_get_items_cb, NULL, sub_options, &subscription);
```

This is after running _oven_ plugin and calling _insert-food_ rpc. Still the output of (unchanged) `./sr_get_items_example /oven:*//. operational` is :

```
Application will get "/oven:*//." from "operational" datastore.

/oven:oven (container)
/oven:oven-state (container)
```

while for `./sr_get_items_example /examples:*//. operational` is :

```
Application will get "/examples:*//." from "operational" datastore.

/examples:cont (container)
/examples:stats (container)
/examples:stats/counter = 852
/examples:stats/counter2 = 1052
```

I must be missing something, but I can't figure out what it is.

**Comment by michalvasko** [comment]
Firstly, the line
```C
        lyd_new_path(*parent, NULL, "/oven:oven-state/food-inside", 1, 0, NULL);
```
is wrong because 1) the value should be string and 2) boolean values are `true` or `false`. So, correctly it is
```C
        lyd_new_path(*parent, NULL, "/oven:oven-state/food-inside", "true", 0, NULL);
```

But seeing that `./sr_get_items_example /examples:*//. operational` works fine tells me that you have run the example this way
```
oper_data_pull_example examples /examples:stats
```
Now you need to run the modified example for `oven` similarly
```
oper_data_pull_oven oven /oven:oven-state
```
I have tried to put providing both data in the example and based on what parameters I used it provided the correct data.

**Comment by maciek-k1** [comment]
Michal, thank you for your help with it, after the fix it did work as expected. I do still have a problem running sysrepo-plugind (which was the reason notifications weren't showing up), but I'll open a separate thread for that.
