### ISSUE TITLE
Validation Failed while set RO Node with push method

### ISSUE THREAD

**Issue by namphuonghoanges** [sysrepo/sysrepo#2510]
Hi Michal,
I'm running the sysrepo 1.4.140 and libyang 1.0.240.
When i trying to set with below xpath:
![image](https://user-images.githubusercontent.com/82130295/125050999-b932da80-e0cc-11eb-8d28-21607c98ec8e.png)
This xpath is correct and can run in pull method but when i try to switch to push method i got below error:
![image](https://user-images.githubusercontent.com/82130295/125051151-debfe400-e0cc-11eb-85d3-5779b1d5d962.png)
The yang data is:
![image](https://user-images.githubusercontent.com/82130295/125051530-3d855d80-e0cd-11eb-9896-fd9135b2cb4f.png)
hardware-sensor feature is enable in sysrepo. 
how can i fix this?

**Comment by michalvasko** [comment]
Did you switch the session to `SR_DS_OPERATIONAL` before setting the push oper data?

**Comment by namphuonghoanges** [comment]
Hi Michal,
Thanks for your reply, I check again and forgot to switch to SR_DS_OPERATIONAL. It's successful to run now
Thank you.
