### ISSUE TITLE
Notification on commit to startup configuration

### ISSUE THREAD

**Issue by andrisrudzitis** [sysrepo/sysrepo#2511]
Hello,

Is it possible to get a notification when `startup` configuration is updated?

Within a sysrepo plugin a subscription is created as follows:

    rc = sr_module_change_subscribe(session, "ietf-system", "/ietf-system:system/hostname",
            my_change_cb, NULL, 0,
            SR_SUBSCR_ENABLED | SR_SUBSCR_DONE_ONLY, &subscription); // or without SR_SUBSCR_DONE_ONLY

From netopeer2 cli I am trying to update the configuration

```
> edit-config --target candidate --config=./hostname.xml
> commit
```

At this point the plugin receives notification and gets to handle `running` configuration change.
My wish is to get a notification when `startup` configuration gets changed.

```
> copy-config --target startup --source running
> commit
```

With the subscription above plugin does not get any notification after these steps (probably as there is no change in config).
Is it possible (in this way or differently) for a sysrepo plugin to get notified when
startup configuration gets changed (if this makes sense)?

Best regards

**Comment by michalvasko** [comment]
You can subscribe for changes in all the datastores using `sr_module_change_subscribe()`, not just running. But note that `copy-config` to startup is a complete operation, the following `commit` does not do anything.

**Comment by andrisrudzitis** [comment]
Thanks for the reply.

I will create and use another session within sysrepo plugin for SR_DS_STARTUP datastore. With that I am getting the notification on `copy-config` operation.
