### ISSUE TITLE
/* subscribe as dummy state data provider, they should get deleted */

### ISSUE THREAD

**Issue by mx568549060** [sysrepo/sysrepo#2513]
Hey,@michalvasko 
In test_operational.c, test_yang_lib(),how do I understand the     `/* subscribe as dummy state data provider, they should get deleted */` ?

**Comment by michalvasko** [comment]
If you subscribe as state data provider for a subtree and do not provide any data in the callback (hence `dummy`), you will effectively remove that subtree from the operational datastore.

**Comment by mx568549060** [comment]
> If you subscribe as state data provider for a subtree and do not provide any data in the callback (hence `dummy`), you will effectively remove that subtree from the operational datastore.

Thank for quick replay.
