### ISSUE TITLE
'is not allowed to reference deprecated definition' bug is back

### ISSUE THREAD

**Issue by igortern** [sysrepo/sysrepo#2514]
Hi,
It seems that 'is not allowed to reference deprecated definition' bug that was fixed at earlier stage is now back. 
- libyang, sysrepo snapshot taken from devel on July 20
Error when importing a series of modules:
[ERR]: A current definition "port-number" is not allowed to reference deprecated definition "link".
sysrepoctl error: Failed to install module "/home/igort/Perforce/OLT/aspen/main/third_party/yang-models/OB-BAA-standard-olt-adapter/1.0/yang/bbf-ghn.yang" (libyang error)

Attached are:
- sysrepo-import.txt: install script up to the point of failure
- sysrepo at the point of failure. The last command in the script above applied to this sysrepo reproduces the problem.
- yang models
Could you have a look?
Best Regards,
Igor

[yang-models.zip](https://github.com/sysrepo/sysrepo/files/6844440/yang-models.zip)
[sysrepo.zip](https://github.com/sysrepo/sysrepo/files/6844441/sysrepo.zip)
[sysrepo-import.txt](https://github.com/sysrepo/sysrepo/files/6844443/sysrepo-import.txt)

**Comment by michalvasko** [comment]
> bug that was fixed at earlier stage is now back

I do not think this was a regression bug but I do seem to remember a similar bug where the problem was the status of `when`, in this case it was the status of a node with a `uses` parent. Should be fixed now, in any case.

**Comment by igortern** [comment]
thank you
