### ISSUE TITLE
RPMs on a YUM server too?

### ISSUE THREAD

**Issue by esend7881** [sysrepo/sysrepo#2515]
I know the RPMs are available for individual download here http://download.opensuse.org/repositories/home:/liberouter/Fedora_28/x86_64/

I am wondering if the RPMs are also posted to a YUM server as well? This way I can just run normal `yum install` and `yum update` commands instead of downloading the RPMs manually and running a `yum localinstall`

This is more of a convenience thing though it will help in maintenance when more of the IT team takes over maintenance instead of the developers.

**Comment by michalvasko** [comment]
Those packages (latest versions 1) will not get to any official repositories but note that you can simply add the address you posted as a repository and then you can do `yum install`. Versions 2 of the projects should gradually all be part of the official repositories for the most common distributions.
