### ISSUE TITLE
Performace and sr_apply_changes()

### ISSUE THREAD

**Issue by iljatab** [sysrepo/sysrepo#2516]
$ yanglint --version
yanglint SO 1.10.24
$ sysrepoctl --version
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.130 (SO v5.6.46)
$ netopeer2-server -V
netopeer2-server 1.1.73

Hi Michal,

Hopefully you could help with my question regarding sysrepo performance.

In some cases our application makes more than 10,000 changes with `sr_set_item()` and then does `sr_apply_changes()`.
This used to be several times faster than calling `sr_apply_changes()` after each database modification with `sr_set_item()`.
Most of the time was consumed in `sr_apply_changes()` for data validation (as I understand).
In these tests our data configuration callback is a no-op and just returns immediately.

We did capacity tests a while ago and upgraded sysrepo a couple of times since then.
Now I re-run the tests and it looks that there is a huge performance drop.
All the time is consumed by `sr_set_item()`. The `sr_apply_changes()` completes almost immediately.
And the total time is like as if we called `sr_apply_changes()` after each `sr_set_item()`.
However I am pretty confident that there are no unexpected `sr_apply_changes()` calls in our app - I am monitoring running database from the outside.

So could you clarify if this is expected, any suggestions?
I really hope there's some sysrepo misuse in our app and we can fix it.

Connection is done with `SR_CONN_CACHE_RUNNING` and `sr_set_item()` with SR_EDIT_ISOLATE.
However with SR_EDIT_DEFAULT it is the same.

BRGDS
Ilja.

**Comment by michalvasko** [comment]
The only help I can provide is a suggestion to migrate to the latest `devel` branches in all the projects (versions 2.x). If the performance is still bad, provide the exact use-case in a way I can benchrmark it myself and I will see what I can do.

**Comment by iljatab** [comment]
Thanks for reply.

Migration to 2.x is not an immediate option for us, however we definitely will do it later.

Still, could you please suggest in which version this performance degradation happened?
We could consider downgrade then.
The performance for sr_set_item() used to be very good but now it is maybe up to 10 times slower :-(

Ilja.

**Comment by michalvasko** [comment]
I am not aware of any performance degradation in `sr_set_item()`. And I do want to spend time looking for it so I am sorry, I cannot help you.

**Comment by iljatab** [comment]
Ok, thanks anyway.
Are there any performance improvements in 2.x that would help in larger scale?

**Comment by michalvasko** [comment]
You should have generally better performance, sometimes a bit, sometimes a lot. Cases when the performance is worse should be reported and should be possible to optimize.

**Comment by iljatab** [comment]
Ok, we'll migrate to 2.x when possible.

I have one more question, related to performance.
We have configurations, saved in internal (non-sysrepo) format.
These configurations are known to be correct from YANG model point of view - they were already validated by sysrepo.
On start-up a particular configuration is loaded by our application into an empty sysrepo database.
The configuration may be big and sr_apply_changes() takes really much time.
Is it possible to avoid internal validation against YANG models during sr_apply_changes() call?
Of course the caller is responsible for all database changes being are valid and consistent.
Sure, there's no such API currently but maybe you could point me to the relevant source code in 1.x tree?
I could then try to do it myself.

Thanks,
Ilja.

**Comment by michalvasko** [comment]
[This](https://github.com/sysrepo/sysrepo/blob/libyang1/src/sysrepo.c#L2000) is where the validation occurs, generally, but I am not sure you are free to remove it even if you know your data are valid. The problem is that during validation also default values are consolidated, among other things, and unless you are loading the data from LYB or as validated *libyang* data tree, you need to do that. But you are free to experiment.

**Comment by iljatab** [comment]
Thanks for suggestions!

First, we tried to switch to composing a full change tree and then use sr_edit_batch() instead of numerous sr_set_item_str() calls.
This helps a bit.

Then I followed you suggestion and removed sr_modinfo_validate() call.
Given that, things became lightning fast but of course default values were not added, as you warned.

As a next step I added a call to sr_modinfo_add_defaults() instead of removed sr_modinfo_validate().
And, after that, it turned out that the performance issue was not as much in validation but instead in adding default values, especially in sr_modinfo_ly_val_diff_merge().
Just adding "default" to a single leaf in YANG model increased processing in tens of times.
Same schema without any "default" works very fast.

Given the above, could you please clarify if in libyang 2.x there are any performance improvements in this area?
Or possibly you have in mind any additional hints for 1.x branch?

Thanks,
Ilja.

**Comment by michalvasko** [comment]
Yes, there are major performance problems for some use-cases when adding default values, which should be solved in v2. There was a specific [issue](#1981) resolved but whether it improved your specific use-case I have no way of being sure.

Just note that when switching to v2, you should use `devel` branches of all the projects, there are already lots of bugfixes compared to the released `master` versions.

**Comment by iljatab** [comment]
Thanks for suggestions!

First, we tried to switch to composing a full change tree and then use sr_edit_batch() instead of numerous sr_set_item_str() calls.
This helps a bit.

Then I followed you suggestion and removed sr_modinfo_validate() call.
Given that, things became lightning fast but of course default values were not added, as you warned.

As a next step I added a call to sr_modinfo_add_defaults() instead of removed sr_modinfo_validate().
And, after that, it turned out that the performance issue was not as much in validation but instead in adding default values, especially in sr_modinfo_ly_val_diff_merge().
Just adding "default" to a single leaf in YANG model increased processing in tens of times.
Same schema without any "default" works very fast.

Given the above, could you please clarify if in libyang 2.x there are any performance improvements in this area?
Or possibly you have in mind any additional hints for 1.x branch?

Thanks,
Ilja.
