### ISSUE TITLE
sysrepo-plugind problem with notifications

### ISSUE THREAD

**Issue by maciek-k1** [sysrepo/sysrepo#2517]
Hi Michal,
I'm trying to run example sysrepo-plugind oven.so and failing to see notifications. 
Tried both on current official sysrepo and sysrepo-devel. Running on aarch64 (not sure if relevant).
I placed _oven.so_ in a separate dir and set plugin path to this dir.
When running `sysrepo-plugind -d` it freezes without output to terminal. When I _Ctrl+C_ and rerun `sysrepo-plugind` it executes seemingly without errors, as after that I run `sysrepo-plugind -d` again and get:
```
[ERR]: Operational data provider subscription for "oven" on "/oven:oven-state" already exists.
[ERR]: plugin: OVEN: Oven plugin initialization failed: Invalid argument.
[ERR]: plugin: Plugin initialization failed (Invalid argument).
```
So I assume the plugin is loaded and ready (is it?). At this point I run `./notif_subscribe_example oven` as per [instructions](https://netopeer.liberouter.org/doc/sysrepo/master/html/example.html) and get
```
========== LISTENING FOR NOTIFICATIONS ==========
```
and then I do `sysrepocfg --rpc=vim` in a separate [screen](https://help.ubuntu.com/community/Screen) with 
```
<insert-food xmlns="urn:sysrepo:oven">
    <time>on-oven-ready</time>
</insert-food>
```
I'm not getting any notifications. I confirmed `./notif_subscribe_example` works correctly before by subscribing to _examples_ module's notifications and it worked as expected. Any help would be greatly appreciated, it's probably something minor that I'm missing, but I don't know where to start.

**Comment by michalvasko** [comment]
I cannot help you with all the problems at once, they must be solved one-at-a-time. So try running `sysrepo-plugind -d -v4` and you should see some output informing that `oven` was initialized successfully. Also, I assume you are using the current `devel` branch. Do so if not.

**Comment by maciek-k1** [comment]
Hi Michal,
Thank you for your answer. I've added the notification issue as that was the only way I could see if anything went wrong. I'm on sysrepo-devel. I've now ran the plugin with _-v4_ as you suggested and I can see the plugin does get initialised.
```
[DBG]: plugin: OVEN: Oven plugin initialized successfully.
```
So that's out of the way. Now I _insert-food_ and I can see
```
[INF]: Processing "/oven:insert-food" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[INF]: Successful processing of "rpc" event with ID 1 priority 0 (remaining 0 subscribers).
```
but get no notifications despite having `./notif_subscribe_example oven` run in the bg. Would you be able to help me with that?

**Comment by michalvasko** [comment]
So now that it seems you have it all working I have actually looked at the example and am wondering what notification exactly are you expecting after "inserting food"?

**Comment by maciek-k1** [comment]
Sorry, I meant the notification when oven is ready. It seems to have started working now, thanks a lot for your help! I must have been doing something wrong when running the plugin before, so that I wasn't getting the notifications correctly - I just couldn't see it because of too low _-v_ setting. Thanks again!
