### ISSUE TITLE
Query on module change callback function call

### ISSUE THREAD

**Issue by meghna-doshi** [sysrepo/sysrepo#2519]
Hi,
We are using following sysrepo version (2.x version)
sysrepoctl --version
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v2.0.24 (SO v6.1.18)

We noticed one change in behaviour from 1.x to 2.x.
In 2.x, we are observing that when we call **module_change_subscribe** , the callback function is called in the context of the same thread which is calling module_change_subscribe.
In 1.x, callback function was called in context of a new thread and not the same as the one calling module_change_subscribe.

Is our observation correct? 

1.x version which we used is:
sysrepocfg --version
sysrepocfg - sysrepo configuration manipulation tool, compiled with libsysrepo v1.4.144 (SO v5.6.60)

Regards,
Meghna

**Comment by michalvasko** [comment]
I do not think your observation is correct or at least there are no differences in this between version 1 and 2. The callback may be called by the same thread if the `SR_SUBSCR_ENABLED` flag, this single first event is then generated by the same thread, none others are.

**Comment by meghna-doshi** [comment]
Hi Michal,
Ok thanks, may be we have wrong impression regarding 1.x.

Regards,
Meghna.
