### ISSUE TITLE
XPath filtering problems

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2520]
Hi!

I've noticed, that it's possible that `sr_get_data()` is handling XPaths wrong.

For example (using sysrepocfg to demonstrate `sr_get_data()` behavior):

`sysrepocfg --export --xpath=/ietf-netconf-server:netconf-server/listen/.`
```

<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <listen>
    <endpoint>
      <name>default-ssh</name>
      <ssh>
        <tcp-server-parameters>
          <local-address>0.0.0.0</local-address>
          <keepalives>
            <idle-time>1</idle-time>
            <max-probes>10</max-probes>
            <probe-interval>5</probe-interval>
          </keepalives>
        </tcp-server-parameters>
        <ssh-server-parameters>
          <server-identity>
            <host-key>
              <name>default-key</name>
              <public-key>
                <keystore-reference>genkey</keystore-reference>
              </public-key>
            </host-key>
          </server-identity>
          <client-authentication>
            <supported-authentication-methods>
              <publickey/>
              <passsword/>
              <other>interactive</other>
            </supported-authentication-methods>
          </client-authentication>
        </ssh-server-parameters>
      </ssh>
    </endpoint>
  </listen>
</netconf-server>
```

Same result with:

`sysrepocfg --export --xpath=/ietf-netconf-server:netconf-server/listen/*`

It seems like `sr_get_data()` handles all XPaths as if they end with `//.`

Is this working as intended? Shouldn't `/.` only return the context node, and `/*` only return
the children? This behavior seems to work fine when using `sr_get_items()`.

I'm using the latest devel libyang/sysrepo.

Thanks!

**Comment by michalvasko** [comment]
I think it is quite well [documented](https://github.com/sysrepo/sysrepo/blob/devel/src/sysrepo.h#L671) and should be obvious that it is a feature. It makes little difference performance-wise so it works just like a NETCONF filter.

**Comment by awesomenode** [comment]
Thank you for your answer!
