### ISSUE TITLE
enable-features fails with new sysrepo. the same works with 1.x sysrepo/libyang

### ISSUE THREAD

**Issue by igortern** [sysrepo/sysrepo#2523]
Hi,

libyang, sysrepo taken from devel on July 29th
The following command fails. 
`bin/sysrepoctl --change ietf-netconf-server -a --enable-feature ssh-listen --enable-feature tls-listen --enable-feature ssh-call-home --enable-feature tls-call-home
`

The error is
`[ERR]: Not found node "public-key-bags" in path.`
`[ERR]: Target of leafref "truststore-reference" cannot be referenced because it is disabled.`
`sysrepoctl error: Failed to apply changes (libyang error)`

The same command with the same model set succeeds when using the latest sysrepoctl 1.x.
sysrepo repo is attached

Regards,
Igor
[sysrepo.zip](https://github.com/sysrepo/sysrepo/files/6898301/sysrepo.zip)

**Comment by michalvasko** [comment]
Not sure why *libyang* v1 does not report this but the following restriction ([ref](https://datatracker.ietf.org/doc/html/rfc7950#section-9.9))
```
   If the leaf that the leafref refers to is conditional based on one or
   more features (see Section 7.20.2), then the leaf with the leafref
   type MUST also be conditional based on at least the same set of
   features.
```
is broken. The leaf, which is `truststore-reference` in an instantiated grouping `local-or-truststore-public-keys-grouping` from `ietf-keystore` is conditional on **truststore-supported** and **public-keys** features. The target `/ietf-truststore:truststore/public-key-bags/public-key-bag/name` is conditional only on **public-keys**.

It seems it is the case in the latest draft revision of `ietf-truststore` as well so I am going to write to the mailing list and warn about this.

**Comment by michalvasko** [comment]
Okay, should now be fixed with the latest *libyang*.

**Comment by igortern** [comment]
It works now. Thanks
