### ISSUE TITLE
v2.0 sysrepoctl stucks during yang installation

### ISSUE THREAD

**Issue by iGovindY** [sysrepo/sysrepo#2525]
Hi 

sysrepoctl stucks with below prints with attached yang and script.

```
sh install_yang_modules.sh 
| INFO | SR stderr | sysrepoctl | Applying scheduled changes. |
| INFO | SR stderr | sysrepoctl | No scheduled changes. |
| INFO | SR stderr | sysrepoctl | Connection 46 created. |

```

### Steps:
```
tar -zxvf stuck_issue.tar.gz
cd myyangs3/
#clean /etc/sysrepo/*
sh install_yang_modules.sh
```
### Version
```
sysrepoctl --version
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v2.0.24 (SO v6.1.18)

yanglint --version
yanglint 2.0.57
```

[stuck_issue.tar.gz](https://github.com/sysrepo/sysrepo/files/6899774/stuck_issue.tar.gz)

**Comment by michalvasko** [comment]
It seems there is at least some `/usr/local/setup.sh` script being executed in the install script, but skipping that I installed the module fine. Try updating to the latest `devel` of *sysrepo* and *libyang* (we are focusing on maintenance now and there are usually several fixes committed every day) and then try again.

**Comment by iGovindY** [comment]
ohh, sorry forgot to mention.

setup.sh is same as included in `netopeer2` repo. [here](https://github.com/CESNET/netopeer2/blob/61161666230f5f1af51683089b55505424756f4a/scripts/setup.sh)

yeah without setup.sh this yang installs properly.

**Comment by iGovindY** [comment]
same issue with latest `devel` of all 4 projects,
```
sysrepoctl --version
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v2.0.28 (SO v6.2.1)

yanglint --version
yanglint 2.0.65

```

**Comment by michalvasko** [comment]
The infinite recursion was a serious problem in *libyang* that should be solved in the latest version. However, the actual problem (which you should see now) is that you are using your custom `ietf-interfaces` module but with the revision unchanged meaning *sysrepo* uses the already-installed `ietf-interfaces` revision, which is not what is expected. I have tried changing the custom model to a newer revision and got further but there are still errors in your modules.
