### ISSUE TITLE
libyang/sysrepo xml checker is stricter in 2.x than in 1.x

### ISSUE THREAD

**Issue by igortern** [sysrepo/sysrepo#2526]
Hi,

xml checker in 2.x appears complains about things that didn't trigger any problem in 1.x

`<if:type xmlns:bbf-xponift="urn:bbf:yang:bbf-xpon-if-type">bbf-xponift:channel-group</type>`
triggers error 
`Opening ("if:type") and closing ("type") elements tag mismatch`. 
While strictly speaking it is correct, it does cause backward compatibility problems with a plethora of configuration scripts.
Is it possible to relax this check?

Thanks,
Igor

**Comment by michalvasko** [comment]
I am sorry but invalid data should not be accepted regardless of whether they were accepted by *libyang* v1 or not.

**Comment by igortern** [comment]
Fair enough. Thanks
