### ISSUE TITLE
Assertion `shm_end == shm_main->addr + shm_main->size' failed

### ISSUE THREAD

**Issue by rydy** [sysrepo/sysrepo#2527]
Hi,
    The following error occurs when running sysrepo-plugnd. How to solve it?
`Assertion `shm_end == shm_main->addr + shm_main->size' failed`

thanks,
best regards.

**Comment by michalvasko** [comment]
You have included no information whatsoever so I cannot help you. To start with, include the version of *sysrepo* you are using and then the steps performed from a fresh install to the point of the failed assertion.

**Comment by rydy** [comment]
> You have included no information whatsoever so I cannot help you. To start with, include the version of _sysrepo_ you are using and then the steps performed from a fresh install to the point of the failed assertion.

versin(Version 1.4.122、libyang1.0.225), I tried deploying sysrepo on an ARM(armv7l GNU/Linux) environment，Sysrepo cross-compile successfully, I tried to install a [ietf-netconf-acm@2018-02-14.yang](https://github.com/CESNET/netopeer2/blob/master/modules/ietf-netconf-acm%402018-02-14.yang) Yang model for netopeer2,

The following error occurs during the 'ietf-netconf-acm@2018-02-14.yang' installation, but the 'sysrepoctl -l' query shows that the installation is successful.

```
#sysrepoctl -a -i /mnt/target_yang_path/ietf-netconf-acm@2018-02-14.yang -s /mnt/target_yang_path -p 666 -o root -g root -v2 
sysrepoctl: /home2/chailianghao/B4860_OLD_HUB_NC/QualCA/radisys/src/tenb_commonplatform/software/apps/fap/management/o-hub/sysrepo/src/shm_main.c:1040: sr_shmmain_add_module_notifs: Assertion `shm_end == shm_main->addr + shm_main->size' failed.

root@levelchip:/mnt/target_yang_path# sysrepoctl -l
Sysrepo repository: /home2/chailianghao/B4860_OLD_HUB_NC/QualCA/radisys/src/tenb_commonplatform/software/apps/fap/management/o-hub/sysrepo-devel/build/repository

Module Name                | Revision   | Flags | Owner     | Permissions | Submodules | Features
-------------------------------------------------------------------------------------------------
ietf-datastores            | 2018-02-14 | I     | root:root | 664         |            |         
ietf-inet-types            | 2013-07-15 | i     |           |             |            |         
ietf-netconf               | 2011-06-01 | I     | root:root | 664         |            |         
ietf-netconf-acm           | 2018-02-14 | I     | root:root | 600         |            |         
ietf-netconf-notifications | 2012-02-06 | I     | root:root | 664         |            |         
ietf-netconf-with-defaults | 2011-06-01 | I     | root:root | 664         |            |         
ietf-origin                | 2018-02-14 | I     | root:root | 664         |            |         
ietf-yang-library          | 2019-01-04 | I     | root:root | 664         |            |         
ietf-yang-metadata         | 2016-08-05 | i     |           |             |            |         
ietf-yang-types            | 2013-07-15 | i     |           |             |            |         
sysrepo-monitoring         | 2021-01-15 | I     | root:root | 600         |            |         
sysrepo-plugind            | 2020-12-10 | I     | root:root | 664         |            |         
yang                       | 2017-02-20 | I     | root:root | 664         |            |         

Flags meaning: I - Installed/i - Imported; R - Replay support; N - New/X - Removed/U - Updated; F - Feature changes
Features: ! - Means that the feature is effectively disabled because of its false if-feature(s)
```

**Comment by michalvasko** [comment]
It is not installed correctly even though you may see it in the module list. I would suggest updating to the latest `libyang1` branch versions, if possible. If you then still reproduce it, we can debug further.

**Comment by rydy** [comment]
> It is not installed correctly even though you may see it in the module list. I would suggest updating to the latest `libyang1` branch versions, if possible. If you then still reproduce it, we can debug further.

The [latest ](https://github.com/CESNET/libyang/releases/tag/v1.0.240) version, right?

**Comment by michalvasko** [comment]
That should be fine, too. But I meant really the latest version, not just the latest release, which is only in the respective branch.

**Comment by rydy** [comment]
> That should be fine, too. But I meant really the latest version, not just the latest release, which is only in the respective branch.

Releases
https://github.com/CESNET/libyang/releases/tag/v1.0.240
https://github.com/sysrepo/sysrepo/releases/tag/v1.4.140

Do you mean use the dev branch?

**Comment by michalvasko** [comment]
No, read exactly what I wrote, what is unclear about that? I mean the `libyang1` branch because that is the latest version 1. In `master` and `devel` branches there are new version 2 of the projects. I assumed you do not want to migrate yet to these but eventually you will have to. So, yes, ideally use the `devel` branch but note that *libyang* v2 significantly differs from v1.

**Comment by rydy** [comment]
> versions 2

Ok, I see, Will maintenance stop for version 1 later?

**Comment by michalvasko** [comment]
Yes, but it has not yet been decided when. But it will definitely not be sooner than the end of this year.

**Comment by rydy** [comment]
> Yes, but it has not yet been decided when. But it will definitely not be sooner than the end of this year.

Is version stable now? Will it change a lot later?

**Comment by michalvasko** [comment]
Yes, version 2 is stable and it is a good time to switch to it because we focused on maintenance for the past weeks and fixed lots of problems. That is, switch to the current `devel` versions, `master` (latest release) is the initial v2 release that turned out to be quite buggy. We plan to make a proper new release at the end of this month.

**Comment by rydy** [comment]
> Yes, version 2 is stable and it is a good time to switch to it because we focused on maintenance for the past weeks and fixed lots of problems. That is, switch to the current `devel` versions, `master` (latest release) is the initial v2 release that turned out to be quite buggy. We plan to make a proper new release at the end of this month.

I see,I plan to update it, Thank you for your suggestion.
