### ISSUE TITLE
Acessing supported RPCs through RESCONF APIs

### ISSUE THREAD

**Issue by ahendler** [sysrepo/sysrepo#2530]
Hi,

I am trying to use opendaylight RESTCONF API to send a RPC to which i am subscribed using the python bindings. It is a simple example module that i successfully tested using the `sysrepocfg -R` binary option. My problem arises when i try to use the RESTCONF API, i cannot find my RPC when i query the `{+restconf}/operations` subtree. Are there any listing/enabling steps i am missing before being able to send the RPC via the RESTCONF API?

Thanks!

Module:
```
module temperature{
	namespace "env:temperature";
	prefix "temp";
	container temperature{
		config true;
		leaf measurement{
			type int32;
		}
	}
	rpc rpc_test{
		input{
			leaf test_value{
				type int32;
			}
		}
	}
}
```
Python code portion:
``` 
try:
	with sysrepo.SysrepoConnection() as rpc_conn:
		with rpc_conn.start_session() as rpc_sess:
			logging.info("subscribing to rpc calls: /temperature:rpc_test")
			rpc_sess.subscribe_rpc_call("/temperature:rpc_test", devi.rpc_test)
			signal.sigwait({signal.SIGINT, signal.SIGTERM})
```
Request i am using and it's error message:
```
POST http://<odl controller ip>:<port>/rests/operations/<path to module>/temperature:rpc_test
```
```
"error-message": "Could not parse Instance Identifier 'temperature:rpc_test'. Offset: '20' : Reason: '(env:temperature)rpc_test' is not correct schema node identifier." 
```
(As expected given that it is not listed under operations subtree)

Versions:
netopeer2: 1.1.27
sysrepo: v1.4.58
sysrepo-python: 0.4.2
(Other dependencies are using matching versions)

**Comment by michalvasko** [comment]
Firstly, your *sysrepo* version and that of the other libraries is really old, you should upgrade. Additionally, I do not know what exactly does your problem has with out projects because we do not provide any RESTCONF API so I cannot help you there.

**Comment by ahendler** [comment]
It was a problem with a strange character in the module. I will upgrade the libraries, thanks.
