### ISSUE TITLE
Swig related errors building Sysrepo 1.4.140 RPM

### ISSUE THREAD

**Issue by esend7881** [sysrepo/sysrepo#2532]
### Problem:
I noticed that with the sysrepo spec file found in the [src rpm](https://download.opensuse.org/repositories/home:/liberouter/CentOS_7/src/sysrepo-1.4.140-5.1.src.rpm), I needed to change a line to allow it to work:

[gist for sysrepo.spec](https://gist.github.com/esend7881/4c15ff750c5deccb6309cac0727f5d1b) (See [revision 2](https://gist.github.com/esend7881/4c15ff750c5deccb6309cac0727f5d1b/revisions#diff-ee3a683e912de5a790bd6cde85e845b349d310d3c95805cb75b8084fa06c7cdc) with change noted)
```.spec
%if 0%{?centos_version}
BuildRequires:  swig3 >= 3.0.12
%else
BuildRequires:  swig >= 3.0.12
%endif
```
Changed to:
```.spec
%if 0%{?centos_version}
BuildRequires:  swig3 >= 3.0.12
%else
BuildRequires:  swig3 >= 3.0.12
%endif
```

Essentially, if I left that  `%else ... swig >= 3.0.12` I get an error that swig 3.0.12 is not installed, but it is. By adjusting this to `swig3 >= 3.0.12` the requirement condition is acknowledged and I move on. Note from the dockerfile, I am basing this image off of centos:7.

### Steps
In order to build Sysrepo, I first build libyang and then libnetconf2. I do this inside of a docker
- Clone https://github.com/sysrepo/sysrepo/tree/v1.4.140
- [Dockerfile gist](https://gist.github.com/esend7881/a6016f678dd58501bbb41e419fb79b47)
- [Build RPMs gist](https://gist.github.com/esend7881/862953c0f1193037c91e169140e03278)
  - Note: I am also buidling libyang, libnetconf2, and netopeer so there is a lot of extra stuff in there that isn't as relevant.

**Comment by michalvasko** [comment]
It seems `centos_version` has no value in your case, which is strange. Do you know any more about this? I would expect it to be defined on all CentOS versions.
