### ISSUE TITLE
direct approach appliaction crashes 

### ISSUE THREAD

**Issue by bkumarrr** [sysrepo/sysrepo#2535]
Hi All
I have created  a application using sysrepo direct approach ,I am able to compile it using -lsysrepo but when I run this application I am getting belows logs and then this used to crashes 
**Application will watch for changes in "my".
[ERR]: Shared memory version mismatch (7, expected 6), remove the SHM to fix.**

Please help

**Comment by bkumarrr** [comment]
Hi @michalvasko 
Can you please comment on this

**Comment by bkumarrr** [comment]
Hi @michalvasko 
Solved this issue but not my appliaction is not able to connect with sysrepo

**Comment by michalvasko** [comment]
The error
```
[ERR]: Shared memory version mismatch (7, expected 6), remove the SHM to fix.
```
means you were using older *sysrepo* version and have updated it. For that you need to remove the old *sysrepo* shared memory so that it can be updated, using `make shm_clean` in *sysrepo* build directory, for example.

**Comment by bkumarrr** [comment]
Hi @michalvasko 
Done This already but not resolved my issue 
When i use to do make shm_clean in sysrepo build directory ,then application through below error
**[ERR]: Invalid context for LYB data parsing, missing module "sysrepo@2021-03-31"**
But as soon as I run any sysrepo utility I get same error 
**[ERR]: Shared memory version mismatch (7, expected 6), remove the SHM to fix.**

**Comment by michalvasko** [comment]
That means you have more *sysrepo* versions installed and used in parallel, please remove **all** of them properly and reinstall.

**Comment by bkumarrr** [comment]
Hi @michalvasko 
I was checking libsysrepo v2.0.34 (SO v6.4.1) [IT was the only one) 
Please suggest me If there are more how to remove them

**Comment by michalvasko** [comment]
If you run `ldconfig -p | grep sysrepo`, you should see all the versions installed.

**Comment by bkumarrr** [comment]
Getting below output - 

	libsysrepo.so.6 (libc6,x86-64) => /usr/local/lib/libsysrepo.so.6
	libsysrepo.so.5 (libc6,x86-64) => /usr/local/lib/libsysrepo.so.5
	libsysrepo.so.5 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libsysrepo.so.5
	libsysrepo.so.0.7 (libc6,x86-64) => /usr/local/lib/libsysrepo.so.0.7
	libsysrepo.so (libc6,x86-64) => /usr/local/lib/libsysrepo.so
	libsysrepo.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libsysrepo.so

**Comment by michalvasko** [comment]
Right, that means you do not have 1 *sysrepo* version installed but 6. Please remove all the libraries and reinstall the one you want to be using. Note that will then have to recompile all the *sysrepo* applications so that they are all linked with the single *sysrepo* version.

**Comment by bkumarrr** [comment]
Should I do -
rm -rf /usr/local/lib/libsysrepo.so.6
rm -rf /usr/local/lib/libsysrepo.so.5
rm -rf /usr/lib/x86_64-linux-gnu/libsysrepo.so.5
rm -rf /usr/local/lib/libsysrepo.so.0.7
rm -rf /usr/local/lib/libsysrepo.so
rm -rf /usr/lib/x86_64-linux-gnu/libsysrepo.so

and then make in sysrepo build directory sir ?

**Comment by michalvasko** [comment]
Please try to be more self-sufficient, these are all basic problems of dynamic library management on Linux. But yes, removing all those files should at least cause linked applications to fail to be executed forcing you to recompile them and no outdated *sysrepo* to be used.

**Comment by bkumarrr** [comment]
Thanks @michalvasko 
Solved this issue
Thanks a lot for help
