### ISSUE TITLE
Sysrepo Installation Guide

### ISSUE THREAD

**Issue by AJR-Dev0015** [sysrepo/sysrepo#2536]
Hello Dear,

I am new with sysrepo.

I've been searching for a reference and installation guide on how to setup and install sysrepo.

Can someone help me or provide a link on how to setup a sysrepo?

Your fast reply will be appreciated.

**Comment by michalvasko** [comment]
Basic information is in the [README](https://github.com/sysrepo/sysrepo) and some more in the [docs](https://netopeer.liberouter.org/doc/sysrepo/master/html/). What exactly are you looking for? There is not much general setup, it all depends on your use-case (your YANG modules).

**Comment by AJR-Dev0015** [comment]
Thank you very much for the reference.

I am trying to create simple gNMI using sysrepo.

Can you give me reference? if you have?

I already searched other references but it seems I cant find other examples about gnmi with sysrepo..

**Comment by michalvasko** [comment]
I cannot help you there, we have implemented only NETCONF.

**Comment by AJR-Dev0015** [comment]
I understand.

Thank you very much though.

**Comment by AJR-Dev0015** [comment]
With regards to sysrepo, did you create your own Yang Model?

**Comment by michalvasko** [comment]
You are asking very general question so I can provide only general answers. For *sysrepo* internal data we have created our own YANG module and *sysrepo* can be used on anything behaving as a standard system including virtual machines.

**Comment by faezehabdolazimi** [comment]
I want to implement a simple ip capture project with sysrepo can someone help me with this?
