### ISSUE TITLE
Nodes missing from operational datastore after edit-config

### ISSUE THREAD

**Issue by meghna-doshi** [sysrepo/sysrepo#2537]
Hi,
Following is sequence of events:
1. edit-config --target running --config=mm_sample.xml
2. application does some updates on operational datastore, so operational datastore looks like:
get-data --datastore operational --filter-xpath /_3gpp-common-managed-element:* (o/p capture in file operbefore.txt)
3. edit-config --target running --config=modify.xml
4. get-data --datastore operational --filter-xpath /_3gpp-common-managed-element:* (o/p captured in file operafter.txt)

Observations: data in (2) and (4) is NOT matching (of course the edit-config node value will change but there are some more missing nodes in 4 compared to 2).

sysrepoctl --version
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.146 (SO v5.6.62)

PFA:
yangs and all the files mentioned above.

[operdb-issue.zip](https://github.com/sysrepo/sysrepo/files/6982217/operdb-issue.zip)

**Comment by meghna-doshi** [comment]
Hi,
Any information on this?

Regards,
Meghna

**Comment by meghna-doshi** [comment]
Hi,
In case this helps, i think this was working properly somewhere around sysrepo version 1.0.107.
Please let us know if any patch fix is also possible, we will try that.

Regards,
Meghna

**Comment by michalvasko** [comment]
I cannot reproduce it without the other operational-only data that you have there so I cannot determine why they get lost. You seem to be using the latest *sysrepo* v1 version so I can only suggest migrating to v2.

**Comment by meghna-doshi** [comment]
Hi Michal,
I didnt understand why you couldnt reproduce.
I think i have attached all yang and xml files.

Let me know if i missed anything.

Regards,
Meghna

**Comment by michalvasko** [comment]
Like I said in the other issue, you have some operational data that I do not know the origin of, how they got to the operational datastore.

**Comment by meghna-doshi** [comment]
Hi Michal,
For the other data in operational datastore, backend application has done operational datastore update using these APIs:

set_item_str
apply_changes

**Comment by michalvasko** [comment]
Okay and does the connection that was used for setting the data still exist after the edit? If not then the data are removed, it is a feature. Like I said, your use-case is too complex for me to debug it directly, there are lots of details that may matter.

**Comment by meghna-doshi** [comment]
Hi Michal,
Yes connection is open. You can add all your queries here, since this feature was working properly in 1.x some previous version, so it is very important for this feature to work properly.

Regards,
Meghna

**Comment by michalvasko** [comment]
> since this feature was working properly in 1.x some previous version, so it is very important for this feature to work properly.

The most important thing is for it to work in v2. So I am sorry but unless you can provide an example with all the required modules that I can compile, run, and reproduce the problem, I will not waste time trying to recreate your exact environment only to do something differently and fail to reproduce it.

**Comment by iGovindY** [comment]
Hi Michal,

Issue can be reproduced with below steps and attached patch of sr_set_item_example.c

Steps: 
1. unzip [yang and XML files](https://github.com/sysrepo/sysrepo/files/6982217/operdb-issue.zip)
2. install yangs under dir `operdb-issue/node-yang`
3. configure below config using `sysrepocfg`
```
<ManagedElement xmlns="urn:3gpp:sa5:_3gpp-common-managed-element" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" xc:operation="create">
    <id>1</id>
    <attributes>
	<userLabel>ABC</userLabel>
    	<dnPrefix>A=B</dnPrefix>
        <userDefinedState>INIT</userDefinedState>  
    </attributes>
  </ManagedElement>
```
4. start `netopeer2-server -dv2`
5. subscribe for module change using `application_changes_example`
`./application_changes_example _3gpp-common-managed-element`
6. edit-config --target running --config=mm_sample.xml
7. apply [Patch.txt](https://github.com/sysrepo/sysrepo/files/7046845/issue.txt) on sr_set_item_example.c
and compile & run it

`./sr_set_item_example`
8. get-data --datastore operational --filter-xpath /_3gpp-common-managed-element:*
9. edit-config --target running --config=modify.xml
10. get-data --datastore operational --filter-xpath /_3gpp-common-managed-element:* 

get-data form step 8 and 10 is different and many leaves are missing, not the one which is modified in step 9.

Some of the missing one are below, which were actually set by `sr_set_item_example` in step 7.
```
/_3gpp-common-managed-element:ManagedElement[id='1']/_3gpp-nr-nrm-gnbdufunction:GNBDUFunction[id='GNBDUFunction']/_3gpp-nr-nrm-nrcelldu:NRCellDU[id='cellindex_1']/attributes/commscope_3gpp-nr-nrm-nrcelldu:PowerControlParams/X0005B9_ULPathlossThreshold
/_3gpp-common-managed-element:ManagedElement[id='1']/_3gpp-nr-nrm-gnbdufunction:GNBDUFunction[id='GNBDUFunction']/_3gpp-nr-nrm-nrcelldu:NRCellDU[id='cellindex_1']/attributes/commscope_3gpp-nr-nrm-nrcelldu:PowerControlParams/X0005B9_p0Nominal
/_3gpp-common-managed-element:ManagedElement[id='1']/_3gpp-nr-nrm-gnbdufunction:GNBDUFunction[id='GNBDUFunction']/_3gpp-nr-nrm-nrcelldu:NRCellDU[id='cellindex_1']/attributes/commscope_3gpp-nr-nrm-nrcelldu:NrTimerConstants/X0005B9_T300
```
