### ISSUE TITLE
Subscribed running data is not copied into operational datastore if sr_oper_get_items_subscribe() is invoked

### ISSUE THREAD

**Issue by molisado** [sysrepo/sysrepo#2540]
I am working on a sysrepo plugin which deals with the operational data of ietf-interfaces YANG module.
[ietf-interfaces.txt](https://github.com/sysrepo/sysrepo/files/6990603/ietf-interfaces.txt)

The 1st version of my plugin is as followed (with some details omitted): 
```
#define MODEL "ietf-interfaces"
static sr_subscription_ctx_t   *sub_write;

int cb_cfg_change(sr_session_ctx_t *session, const char *module_name, ...)
{
    return SR_ERR_OK;
}

int sr_plugin_init_cb(sr_session_ctx_t *session, void **private_ctx)
{   
    int rc = sr_module_change_subscribe(session, MODEL, NULL, cb_cfg_change, NULL, 0, SR_SUBSCR_CTX_REUSE, &sub_write);
    if (SR_ERR_OK == rc) {
        printf("[%s] sr_module_change_subscribe() ok.\n", __func__);
    } else {
        printf("[%s] sr_module_change_subscribe() error: rc(%d).\n", __func__, rc);
    }
       
    return SR_ERR_OK;
}
```

The test environment is pre-imported with some ietf-interfaces **startup** data:
```
~$ sudo sysrepocfg -X -m ietf-interfaces -d startup
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interface>
    <name>eth0</name>
    <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
  </interface>
</interfaces>
```
After launching my plugin (*sudo sysrepo-plugind -d -v 2*), 
the above data exists in both the **running** & **operational** datastore as expected.

However, if my plugin includes subscription to providing operational data: 
```
#define MODEL "ietf-interfaces"
#define XPATH   "/" MODEL ":*"
static sr_subscription_ctx_t   *sub_read;
static sr_subscription_ctx_t   *sub_write;

int state_cb(sr_session_ctx_t *session, const char *module_name, ...)
{
    return SR_ERR_OK;
}

int cb_cfg_change(sr_session_ctx_t *session, const char *module_name, ...)
{
    return SR_ERR_OK;
}

int sr_plugin_init_cb(sr_session_ctx_t *session, void **private_ctx)
{   
    int rc = sr_oper_get_items_subscribe(session, MODEL, XPATH, state_cb, NULL, SR_SUBSCR_CTX_REUSE, &sub_read);
    if (SR_ERR_OK == rc) {
        printf("[%s] sr_oper_get_items_subscribe() ok.\n", __func__);
    } else {
        printf("[%s] sr_oper_get_items_subscribe() error: rc(%d).\n", __func__, rc);
    }

    rc = sr_module_change_subscribe(session, MODEL, NULL, cb_cfg_change, NULL, 0, SR_SUBSCR_CTX_REUSE, &sub_write);
    if (SR_ERR_OK == rc) {
        printf("[%s] sr_module_change_subscribe() ok.\n", __func__);
    } else {
        printf("[%s] sr_module_change_subscribe() error: rc(%d).\n", __func__, rc);
    }

    return SR_ERR_OK;
}
```

After launching my plugin (*sudo sysrepo-plugind -d -v 2*), 
the above data only exists in the **running** datastore, while the **operational** datastore is empty:
```
~$ sudo sysrepocfg -X -m ietf-interfaces -d running
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interface>
    <name>eth0</name>
    <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
  </interface>
</interfaces>
~$ 
~$ sudo sysrepocfg -X -m ietf-interfaces -d operational
~$ 
```

Refer to https://netopeer.liberouter.org/doc/sysrepo/master/html/index.html#oper_ds, the data of operation datastore is from:
> any subscribed running data (in-use concept) will appear in operational datastore;
> any operational data.

Are the 2 **sources** above mutual exclusive?
That is, if I subscribe to provide operational data (which is the 2nd source above), then no more data from the 1st source?

Or, does this has anything to do with the following paragraph from the above link:
> These methods can be combined and provided data can overlap. Later push data overwrite older stored push data and pull data always overwrite push data. There is an example oper_pull_push_example illustrating providing the same data using both methods.

The git version tag of each component in my environment:
Component | Git version tag
-------- | -----------------------------------------------------
libyang | v1.0.240
libnetconf2 | v1.1.46
sysrepo | v1.4.140
Netopeer2 | v1.1.76

**Comment by michalvasko** [comment]
By calling
```
int rc = sr_oper_get_items_subscribe(session, MODEL, XPATH, state_cb, NULL, SR_SUBSCR_CTX_REUSE, &sub_read);
```
you are saying that you will be providing **all** data of `/ietf-interfaces:*` in the callback, disregarding any previous data. Since in your `state_cb()` you are not generating any data, you effectively delete all `ietf-interfaces` data, hence the observed behavior. The quickest fix is using the [SR_SUBSCR_OPER_MERGE](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__subs__api.html#ggaa629478596b1e246553eac91a74b2b5bad8c77539582e1de78f57e256299ea138) flag, read its description for explanation.

**Comment by molisado** [comment]
Thanks for your reply. SR_SUBSCR_OPER_MERGE did solve my problem.
