### ISSUE TITLE
sr_get_lock() returns wrong timestamps

### ISSUE THREAD

**Issue by pfeige** [sysrepo/sysrepo#2542]
The function sr_get_lock() returns wrong (uninitialized) timestamps due to a wrong if condition 
https://github.com/sysrepo/sysrepo/blob/1b6466df61c51e265ff226a13d3725339e39f56c/src/sysrepo.c#L3036-L3045
The condition should be
if (ds_locked) 
without the negation. And ts should be initialized.

**Comment by michalvasko** [comment]
You are right, thanks, fixed.
