### ISSUE TITLE
Modifying existing key-less list

### ISSUE THREAD

**Issue by chendrashekarp** [sysrepo/sysrepo#2545]
Hello team ,

i am trying to delete a key-less list in operational-data using sr_delete_item.
the list entry is not deleting .

the path : /or-ran-fm:active-alarms-list/active-alarm[2].

reference modeul : o-ran-fm
adding the same here : 
[o-ran-fm@2019-02-04.txt](https://github.com/sysrepo/sysrepo/files/7031423/o-ran-fm%402019-02-04.txt)

**Comment by chendrashekarp** [comment]
@michalvasko

**Comment by michalvasko** [comment]
What *sysrepo* version are you using?

**Comment by chendrashekarp** [comment]
i am using -> v1.4.146 (SO v5.6.62)

**Comment by michalvasko** [comment]
If you want to use push operational data on key-less lists, you will have to use *sysrepo* v2. Version 1 has only some basic experimental support for this.

**Comment by chendrashekarp** [comment]
Hi @michalvasko ,
i am trying to set a value in key-less list using ,
sr_set_item_str(session,**"/o-ran-fm:active-alaram-list/active-alarms[1]/is-cleared","true",0,0);**
getting error as **[ERR]: Invalid datastore edit.**
using sysrepo version 2.

**Comment by michalvasko** [comment]
Okay, I have decided this will not be supported after all. Identifying the instance to modify is a really complex task internally and to implement properly would require a lot more time, which we just do not have. What you should be able to do is use `sr_discard_oper_changes()` to delete the whole list instance and then create it again with updated descendants. Or, of course, use pull operational data instead.

**Comment by chendrashekarp** [comment]
Hi @michalvasko ,
can you look into this once , #2551
