### ISSUE TITLE
Slow get for config false data

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2548]
Hi,

I encountered a performance regression with sysrepo2 when getting data from operational datastore when there are pushed oper data.
I attached an example application to reproduce it:
[reprod.zip](https://github.com/sysrepo/sysrepo/files/7040141/reprod.zip)

**libyang1:**

```
$ ./install.sh
$ sysrepocfg --import=config.xml -d startup
$ ./subscribe &
$ time ./test 3000
Repeating test 3000 times

real 0m11,853s
user 0m11,739s
sys 0m0,112s
```

**libyang2:**

```
$ ./install.sh
$ sysrepocfg --import=config.xml -d startup
$ ./subscribe &
$ time ./test 3000
Repeating test 3000 times

real 0m15,791s
user 0m15,635s
sys 0m0,156s
```

Note that the execution time is the same (14 sec) when `SR_CONN_CACHE_RUNNING` is not set on the connection.

sysrepo2 version: 2.0.34
libyang2 version: 2.0.71

sysrepo1 version: 1.4.144
libyang1 version: 1.0.242

Thanks!

**Comment by michalvasko** [comment]
Okay, again there were some redundant node order checks in *libyang*, which should now be skipped and the performance of *libyang* v1 similar to v2. Note that LYB performance (that I has mentioned before and is taking roughly half the time in this use-case) should improve soon (the PR is created but is being finalized) and then v2 should be faster than v1.
