### ISSUE TITLE
create presence empty container failure when the container has a leaf with default value

### ISSUE THREAD

**Issue by yanjunxi** [sysrepo/sysrepo#255]
create presence empty container failure(cli result is OK,but .running file is empty) when the container has a leaf with default value. if any leaf of the presence node has no default value, edit-config is successful.

edit-config file is:
```
<Mo xmlns="urn:ietf:params:xml:ns:yang:zte:subpubcreatetest" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
	<A3 xc:operation="create">
	</A3>
</Mo>
```
model file is:
```
module SubPubCreateTest{
	namespace "urn:ietf:params:xml:ns:yang:zte:subpubcreatetest";
	prefix SubPubCreateTest;
	
	revision 2016-05-10;
	
	container Mo{
		leaf ff{
			type int8;
			default 4;
		}
		
		container A3{
			presence "A3";
			leaf A3_a1{
				type int8;
				default 3;
			}
			
			leaf A3_a2{
				type int8;
			}
		}
	}
}
```

**Comment by milanlenco** [comment]
This seems to be a bug in libyang. I have reported it here: https://github.com/CESNET/libyang/issues/96
I will let you know and close this one once it is fixed.

**Comment by milanlenco** [comment]
OK, the bug was just fixed in libyang. I have verified it and it is indeed working correctly now.
Please try to update and rebuild libyang (from master) and re-try. Let me know in case you are still experiencing any issues with this specific yang model. Closing the issue for now.
