### ISSUE TITLE
C++ API - timeout during module_change_subscribe() for specific xpath callback registration

### ISSUE THREAD

**Issue by Selva-Senthilvelan** [sysrepo/sysrepo#2557]
We are currently using C++ bindings with Sysrepo v1.4.70. We use the module_change_subscribe() API to register callbacks for individual xpath and it works properly.

**Subscribe->module_change_subscribe**(yangModName, callbackClass, **xPath**, 0, SR_SUBSCR_ENABLED)
**Subscribe->module_change_subscribe**(yangModName, callbackClass, **nullptr**, 0, SR_SUBSCR_DONE_ONLY)

We are trying to update to the Sysrepo devel branch v1.4.146 and each call to the above module_change_subscribe() call for specific xpath items is taking considerable amount of time to register and timing out. However, the module_change_subscribe() for entire yang module (not specific xpath) returns normally. Parameter 2 has been modified to use Callback function pointer, instead of the Callback class in previous version. 

**Subscribe->module_change_subscribe**(yangModName, callback_fn, **xPath**, 0, SR_SUBSCR_ENABLED)
**Subscribe->module_change_subscribe**(yangModName, callback_fn, **nullptr**, 0, SR_SUBSCR_DONE_ONLY)

Are we missing something while using Sysrepo v1.4.146 to register callbacks for individual Xpath items? Please guide us on how to accomplish this.

**Comment by michalvasko** [comment]
Looking at the code, there were some locks added to prevent unexpected situations when the initial callback for `SR_SUBSCR_ENABLED` flag is called. Maybe you are doing something in the callback that requires these locks?

**Comment by Selva-Senthilvelan** [comment]
@michalvasko Thanks for responding to my query. 
I am posting sample code to show the framework and sysrepo APIs that we have used in the registration section and the callback function. This is working without any issues with the older Sysrepo v1.4.70 (using the callback class). Please let me know, if you find anything that conflicts with the latest changes/locks used in Sysrepo v1.4.146.

### Registration code: 
The try catch block is throwing "**_reason: Timeout expired_**" exception for every item that is being registered. If I comment out the **_return -1_** from the exception block and let it proceed, it takes about 15 minutes to register an array of 35 xpath items.

```
int numCallBacksToSubscribe = 35;
 
 for(i = 0; i < numCallBacksToSubscribe; i++)
  {
  	try{
		m_Subscribe->module_change_subscribe(subscribeItem[i].yangModName, subscribeItem[i].callback_fn, subscribeItem[i].xpath, 0, SR_SUBSCR_ENABLED);
	
	} catch( const std::exception& e ){
		std::cout << "module_change_subscribe failed for edit-config. reason:" << e.what());
		return -1;
	  }
  }
```


### Callback Function:
This callback function code remains the same as the original callback_class::modulechange() function that worked for the older sysrepo version. Just fixed the callback function parameters to align with the API change.

```
int callback_fn(sysrepo::S_Session sess, const char *module_name, const char *xpath, sr_event_t sr_event, uint32_t request_id)
{
    int ret = SR_ERR_OK;

    if(SR_EV_CHANGE != sr_event && SR_EV_DONE != sr_event && SR_EV_ENABLED != sr_event)
    {
	std::cout << "Skipping other sr_event types";
        return SR_ERR_OK;
    }
	
    if(SR_EV_ENABLED == sr_event)
    {
	std::cout << "Skipping - got SR_EV_ENABLED ";
        return SR_ERR_OK;
    }

    auto it = sess->get_changes_iter(xpath);
    std::string paramXpath = "";

    while (auto change = sess->get_change_next(it))
    {
        switch(change->oper())
        {
            case SR_OP_CREATED:
            case SR_OP_MODIFIED:
                    if (nullptr != change->new_val())
                    {                   
                       paramXpath = std::string(change->new_val()->xpath());
                       std::cout <<"\n CREATED/MODIFIED: Opertype ="<< change->oper()<<" xpath = " <<paramXpath;
                       std::cout << change->new_val()->to_string();
                       	                             
                       if(SR_EV_DONE == sr_event)
                        {
				std::cout << "SR_EV_DONE received";
			}
                    }
                    break;
            case SR_OP_DELETED:
                    if (nullptr != change->old_val())
                    {
                       std::cout << "DELETED!!! is this expected!!!";
                       std::cout << change->old_val()->to_string();
                    }
                    break;
            case SR_OP_MOVED:
                    std::cout << "MOVED!! is this expected!! ";
                    break;
        }
    }
    return ret;
}
```

**Comment by michalvasko** [comment]
The code seems okay, could you maybe try using the C API directly? Or help me debug and stop the application when it is waiting, to see the full backtrace of all the threads.

**Comment by Selva-Senthilvelan** [comment]
I tried to use the C API directly and I got SIGSEGV(11) crash. I enabled the sysrepo debug logs and captured the output to a file, which is linked below. The last errors reported in the sysrepo log are:

_**[ERR]: Locking a mutex failed (sr_module_oper_data_dup_enabled: Connection timed out).
[ERR]: unlink() failed (No such file or directory).**_ 

[Sysrepo_Debug_Logs_module_change_subscribe_with_xpath_SR_SUBSCR_ENABLED_09082021.txt](https://github.com/sysrepo/sysrepo/files/7126091/Sysrepo_Debug_Logs_module_change_subscribe_with_xpath_SR_SUBSCR_ENABLED_09082021.txt)


Log output from the first xpath (o-ran-operations:operational-info/leaf1) callback_fn is listed below. This was followed by the SEGV crash and it never reached the next xpath to be registered. 

_**Callback_fn - module_name: o-ran-operations, xpath: /o-ran-operations:operational-info/leaf1, sr_event: 4 [SR_EV_ENABLED]
Callback_fn - module_name: o-ran-operations, skipping SR_EV_ENABLED event                                                                                                           
Callback_fn - module_name: o-ran-operations, xpath: /o-ran-operations:operational-info/leaf1, sr_event: 2 [SR_EV_DONE] 
Callback_fn - module_name: o-ran-operations, xpath: /o-ran-operations:operational-info/leaf1, Exiting Callback_fn()**_


### C API Registration code:  
```
int numCallBacksToSubscribe = 5;
 
 for(i = 0; i < numCallBacksToSubscribe; i++)
  {  
    rc = sr_module_change_subscribe(rundb_session, subscribeItem[index].yangModName, subscribeItem[index].xpath, subscribeItem[index].callback, NULL, 0, SR_SUBSCR_ENABLED, &subscription);
    if(rc != SR_ERR_OK) 
     {
        goto cleanup;
     }
  }
```

Let me know if you need any additional information to review the issue.

**Comment by michalvasko** [comment]
Please start with running `# make sr_clean` in *sysrepo* to have clear state. Then try to run your app and if you still encounter problems, attach it so that I can reproduce it.

**Comment by Selva-Senthilvelan** [comment]
Just wanted update that I am able to get my application working now. My application had multiple interfaces(module_change, RPC, notifications, set_item, get_item, etc) to Sysrepo Operational and Running DB, which were all implemented using the  C++ API. When I converted just one of those(module_change_subscribe) from C++ to C, I saw a crash, which I reported above. Looking at it further, I was able to write a simple application do just do module_change_subscribe with C API and get it functional. 

Then I converted all my Sysrepo API in my main application from C++ to C. Again I hit the original issue:
 
**[ERR]: Locking a mutex failed (sr_module_oper_data_dup_enabled: Connection timed out).
[ERR]: unlink() failed (No such file or directory).**

My application was first initializing all the Operational DB parameters/values and then registering all the Running DB Xpath using module_change_subscribe API. In this scenario, I received the mutex lock failure error, irrespective of using sysrepo C++ or C API.

I was finally able to get my whole application to work by reordering the initialization sequence. Now I register all the Running DB Xpath using module_change_subscribe API first and then initialize all the Operational DB parameters/values. I converted my entire Sysrepo interface to C API and am currently use 2 different connection and session variables(Operation DB & Running DB). The application is stable and functioning as expected.

Thanks @michalvasko for your assistance. What would be the ideal way to initialize and use Operational and Running Sysrepo DBs in my application? Let me know your thoughts.

**Comment by michalvasko** [comment]
I would really like to reproduce the problem and fix it ideally, it should not behave this way. That is, the crash should definitely not occur and as for the time out, it is also an internal problem unless you registered callbacks that were called later and could not be handled for some reason (they were internally waiting for something or were not being handled by a separate subscription thread).
