### ISSUE TITLE
dm_commit_notify may cause memory access error when the model include leaf-list node

### ISSUE THREAD

**Issue by yanjunxi** [sysrepo/sysrepo#256]
Repetition of steps：
1. define a yang model(module.yang) with a leaflist and some other nodes.
2.use copy-config to initialize data using right.xml file is successful.
3.use edit-config to set data using modify.xml file result in memory access error.

Error happen position:
edit-config invoke dm_commit_notify, then invoke lyd_diff in line 2511 araise error because of first and second lyd_node include a leaflist node which have an invalid child node.
why leaflist node have an invalid child node?
when using dm_load_data_tree to load a lyd tree, invoke dm_load_data_tree_file-->lyd_parse_fd(data_manager.c 489)-->lyd_parse_(tree_data.c 160)-->lyd_parse_xml(tree_data.c 123)-->xml_parse_data(parser_xml.c 555)

when parse leaflist node, invoke xml_parse_data(in line 443), then invoke xml_get_value(parser_xml.c 340)
in function xml_get_value line 85,when we modify leaf->value_str, we modify the lyd_node *node's child member,because struct lyd_node_leaf_list's value_str member is the same as struct lyd_node's child member in the memory.
the follow struct explain the detail.

module.yang
```
module CopyConfigTest{
	namespace "urn:ietf:params:xml:ns:yang:zte:copyconfig";
	prefix CopyConfigTest;
	
	container Mo{
		leaf f1{
			type int8;
		}
		
			leaf-list f3{
				type string;
				max-elements 3;
			}
			
			list ListMo{
				key "name";
				leaf name{
					type string;
				}
				
				leaf value{
					type int8;
				}
			}
	}

}
```

right.xml
```
<Mo xmlns="urn:ietf:params:xml:ns:yang:zte:copyconfig" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" xc:operation="create">
	<f1>1</f1>
	
		<f3>111</f3>
		
		<ListMo>
			<name>list1</name>
		</ListMo>
		<ListMo>
			<name>list2</name>
			<value>88</value>
		</ListMo>
</Mo>
```

modify.xml
```
<Mo xmlns="urn:ietf:params:xml:ns:yang:zte:copyconfig" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" xc:operation="merge">
	<f1>127</f1>
</Mo>
```

**Comment by milanlenco** [comment]
Hi,
unfortunately I couldn't reproduce the issue following the same steps and using the exact same data. Based on the line numbers that you have mentioned it seems that you have an older version of sysrepo and libyang. Could you please try to update sysrepo, libyang and possibly also Netopeer2 (all from the master branch) and re-try if the issue still exists?

Thanks

**Comment by rastislavszabo** [comment]
Unable to reproduce using the current code.
