### ISSUE TITLE
lyd_print_mem() wrongly interpreting integer value as string

### ISSUE THREAD

**Issue by mbelgaum** [sysrepo/sysrepo#2561]
hi 
I m using below code snippet to read data from an yang module and convert to json.
  rc = sr_get_data(session, xpath, 0, 0, 0, &data);
    if (rc != SR_ERR_OK) {
        fprintf(stdout, "\nsr_get_data failed: %d\n", rc);
        return NULL;
    }

    if (data) {
        lyd_print_mem(&json_str, data, LYD_JSON, LYD_PRINT_WITHSIBLINGS);
    }

But lyd_print_mem() is returning json data with string values for integer fields also.
Like this variable 'rmr_port ' is declared as integer in yang file, but lyd_print_mem is returning it as string json value.
"rmr_port      \\\": \\\"5562\\\",\\n

 leaf rmr_port {
                    type uint64;
                    description
                        "rmr port";
                }

Will be grateful for any help to fix this .

**Comment by michalvasko** [comment]
Intentional, specified [here](https://datatracker.ietf.org/doc/html/rfc7951#section-6.1).

**Comment by mbelgaum** [comment]
Thanks for the clarification.
