### ISSUE TITLE
A question about Lock

### ISSUE THREAD

**Issue by myonlystarWang** [sysrepo/sysrepo#2564]
Hi Michal,
     I am using _libyang1_ branch for a long time, everything worked fine except for the occasional lock issues.
     When these problems occured, they should be caused by some wrong operation or bug(I'm just guessing).But I have two questions here:
    

1. If I switch to the _v2.0_ branch, will these lock problems be reduced?
2. Actually I don't really care why these issues happened, but I'd like it go back to work automatically.Unfortunately, when these issues do occur, I have to **reboot** them (can not exec ` make sr_clean` because it will erase a lot of models and data).

Would appreciate it if you could give me some advice.

**Comment by michalvasko** [comment]
Before I can tell you anything I would have to know what kind of "lock issues" are you talking about, I need much more details than that.

**Comment by myonlystarWang** [comment]
Thanks for you rapid response!
Sorry, I don't have any relevant logs at hand at present.
The lock issue I'm talking about is that when it does occur I can only `reboot `or `make sr_clean `to recover.It usually occurs when the _sysrepo_  crashes.
The versions I'm using are `1.4.58` and `1.4.73`(I know they're pretty old)

**Comment by michalvasko** [comment]
Okay, then in all likelihood the issue will be fixed in the latest v1 or v2 version of *sysrepo* because compared to the versions you are using, the locks were completely rewritten and recovery feature added (so you should never need to restart, ideally).

**Comment by myonlystarWang** [comment]
That's great. I‘m very glad to hear that!
I will switch to the latest v1 branch and hope everything works well.
Thank you so much for this excellent project!
