### ISSUE TITLE
mutex blocking problem on shared memory files in /dev/shm/sr*

### ISSUE THREAD

**Issue by vhuertas** [sysrepo/sysrepo#2568]
Dear all,

We are using sysrepo and netopeer2-server to implement an application that subscribes to multiple yang models (ietf-interfaces, ietf-access-control-lists, ietf-qos-policy, among others...).

Although it happens very sporadically, the mutex between our application (using sysrepo v1.4.70 and libyang 1.0.184) and the netopeer2-server gets blocked.
The only way to recover all the environment is, to stop netopeer2-server, stop our application and delete all files begining with 'sr' in /dev/shm/. Then we can restart all the stopped applications.

Have you experienced this before? Is an issue already detected and solved?

Regards,

**Comment by michalvasko** [comment]
Yes, there were several issues with locks, among other things in the version you are using (more than a year old). They should be fixed in the latest v1 or v2 version.

**Comment by vhuertas** [comment]
Thanks for your quick answer Michal,
BTW, is there a way to get in contact with one of your responsibles to talk about the possibility to contract a maintenance service for a period of time?

thanks a lot for your attention

**Comment by michalvasko** [comment]
Yes, I would be that person. You can mail me at mvasko@cesnet.cz and we can discuss details.
