### ISSUE TITLE
Question about STARTUP to RUNNING datastore 

### ISSUE THREAD

**Issue by chunlovemail** [sysrepo/sysrepo#2569]
### Question about STARTUP to RUNNING datastore
_libsysrepo v1.4.122 (SO v5.6.38)_

The following description is https://netopeer.liberouter.org/doc/sysrepo/libyang1/html/index.html
> Startup datastore is the only persistent datastore. It includes the configuration of devices at time of their boot. This configuration is copied into running when the first Sysrepo connection (shared memory) is created after system boot.

Using the sysrepo/examples/examples.yang to do the following test:

1. prepare the examples.xml with the following content

    `<cont xmlns="urn:examples"><l>value01</l></cont>`
2. install `examples.yang` with command `sysrepoctl -i examples.yang`
3. import the `examples.xml` with command `sysrepocfg --import=examples.xml --datastore startup --module examples`
4. setup the daemon process with command `./application_changes_example examples`
5. using the command `sysrepocfg -X -e report-all -m examples -d running -f json` to show the running data. But turns out to be`{ }`. There no config data in `running `datastore

The test result is NOT same as the descrpition:
`This configuration is copied into running when the first Sysrepo connection (shared memory) is created after system boot`.

Am I right understanding?

1. The first sysrepo connection is created by `sysrepocfg`, But now the `examples.startup` is empty. 
2. After import the `examples.xml`, the `examples.startup` has data. 
3. When the next time `sysrepocfg `or `sr_connect()`, the operation of copy `startup `to `running `won't be executed for it's not first time

**Comment by chunlovemail** [comment]
I had also read other issues such as #1811 `Question on when startup gets copied to running.` But still NOT understand:(
@michalvasko  could u please help me to understand this?

**Comment by michalvasko** [comment]
> Am I right understanding?

Yes, the bullets you wrote are correct.

**Comment by chunlovemail** [comment]
Hi Michal, thanks for your comment
