### ISSUE TITLE
sr_disconnect()  crash

### ISSUE THREAD

**Issue by wel2021** [sysrepo/sysrepo#2570]
After creating a new connection, use multiple times sr_ get_ Item(), which also obtains data successfully, and finally uses When sr_disconnect() disconnects, there is no print and the thread is stuck

**Comment by michalvasko** [comment]
You will have to provide much more details for me to help. For starters, what *sysrepo* version are you using?

**Comment by wel2021** [comment]
sysrepo devel:
  Commits on Aug 4, 2021
  VERSION bump to version 2.0.34
  commit ID:8a01c75f5a95dc33d5e1193d5b79f629c76c645e

There may be printed information when a problem occurs
[ERR]: unlink() failed (Is a directory).

**Comment by michalvasko** [comment]
I see, please try to update to 2.0.40 (current `devel`), which should not be a problem from the version you are using. If the problem persists, please mention the steps you are executing for the issue to manifest.
