### ISSUE TITLE
Cannot install openconfig-interfaces

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2571]
Hi,

I get error when trying to install standard openconfig-interfaces model:
[yang.zip](https://github.com/sysrepo/sysrepo/files/7144293/yang.zip)

```
$ sysrepoctl -i yang/openconfig-interfaces@2021-04-06.yang -s yang/
[ERR]: Invalid keyword "revision", it cannot appear after "extension instance".
[ERR]: Parsing module "openconfig-interfaces" failed.
sysrepoctl error: Failed to install module "yang/openconfig-interfaces@2021-04-06.yang" (libyang error)
For more details you may try to increase the verbosity up to "-v3".
```
 
libyang version: 2.0.84
sysrepo version: 2.0.40

Thanks!

**Comment by michalvasko** [comment]
The error is valid, in [module-stmt](https://datatracker.ietf.org/doc/html/rfc7950#page-184) there are, in this order, `revision-stmts` followed by `body-stmts` (which include `extension-stmt`).

**Comment by awesomenode** [comment]
Thank you for the support!

**Comment by wisotzky** [comment]
@michalvasko, could you reopen this issue?

Even I agree this is not a bug per se, it hinders interoperability with OpenConfig and some vendor models (like Nokia SR OS). As no other YANG parser including Cisco confD, PYANG, ... does really complain about this particular aspect of ordering, there should be some sort of relaxed mode (default) that does not complain against issues like this. Keep in mind, that even libyang1 does not complain about this issue above.

Applying strict enforcement might be an advanced option, people would enable who actually know what they are doing. However, I would believe that most people would use this option mainly for compliance checks.

**Comment by michalvasko** [comment]
Turns out I was too strict and wrongly assumed that `extension-stmt` includes an extension instance but it concerns only an extension definition. So, in latest *libyang* (for now only in `devel`) this restriction [was lifted](https://github.com/cesnet/libyang/issues/1753) (version 2.0.129).
