### ISSUE TITLE
Cannot set value with empty pattern in type

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2572]
Hi,

I have empty pattern in typedef which should accept all strings:

```
module test {
  yang-version 1.1;
  namespace "urn:com:test";
  prefix t;

  typedef test-type {
    type string {
      pattern "";
    }
  }

  container c {
            leaf value {
                type test-type;
        }
    }
}
```

When I try to set the value I get the following error:

```
$ sysrepocfg -v3 --edit=config.xml -d running
[INF]: Scheduled changes not applied because of other existing connections.
[INF]: Connection 6 created.
[INF]: Session 7 (user "devuser", CID 6) created.
libyang error: Unsatisfied pattern - "test_value" does not conform to "".
sysrepocfg error: Data parsing failed
[INF]: No datastore changes to apply.
```

Although using empty pattern makes no sense, I use standard model which contains it (ieee802-dot1q-types@2021-06-01.yang).

Content of config.xml:
```
<c xmlns="urn:com:test">
  <value>test_value</value>
</c>
```

libyang version: 2.0.84
sysrepo version: 2.0.40

Note that it works with sysrepo1/libyang1.

Thanks!

**Comment by michalvasko** [comment]
I could not find the module you mentioned but I believe pattern `""` should match only a single string being `""`, nothing else. How v1 behaved is irrelevant, the correct behavior needs to be decided. And I think the new behavior is correct, you disagree?

**Comment by awesomenode** [comment]
This is the module: https://github.com/YangModels/yang/blob/master/standard/ieee/draft/802.1/QRev/ieee802-types.yang
Likely this will be part of IEEE Std 802.1Q-2021.

**Comment by awesomenode** [comment]
In general the empty regex pattern matches everything, so this pattern should have not effect I think.

**Comment by michalvasko** [comment]
Based on the RFC 7950 `pattern` value definition ([XML regex](https://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#regexs)), I would actually say that empty regex is not valid at all so I am tempted to add explicit check for it. Other than that I have just tested it and it seems that PCRE2 matches only `""` to the pattern `""`, like I said.

**Comment by awesomenode** [comment]
Meanwhile I was informed that IEEE modules will address "" pattern, and those will be removed in the next iteration.
