### ISSUE TITLE
Issue regarding netconf-config-change

### ISSUE THREAD

**Issue by matkocc** [sysrepo/sysrepo#2576]
Hi,

In one of our applications we have module-change-callback where we are detecting if a leaf is set to ACTIVE or INACTIVE and depending of what is set by client (edit-config), we are sending some notifications back to client. We are building those notifications in module change callback and have separate thread that is checking if they need to be sent and sending them to client.

Problem is that those notifications are sometimes arrived to client before netconf-config-change is arrived.

We tried to fix this by setting sleep() before sending those notifications, but it seems it didn't help. We put sleep in separate thread that is sending notifications, not in the callback. We are subscribing to changes in model with SR_SUBSCR_DONE_ONLY option.

So this is a "sequence" of the problem:

1. client sends edit-config that is changing leaf to ACTIVE/INACTIVE
2. application is in her module change callback (SR_SUBSCR_DONE_ONLY option in subscribe) building notifications that will be sent to client
3. separate thread in application detects that there are notifications that needs to be sent and sends them 
4. notifications are delivered to the client before netconf-config-change notification (of this edit-config form (1.) )

Client expects that netconf-config-change arrive before those notification sent by application.

Do you have any suggestions how can we fix this?

We are using sysrepo 1.4.104

Thanks,
    Matko

**Comment by michalvasko** [comment]
This is a specific use-case and most I can do is provide some ideas, *sysrepo* does not support such level of synchronization, it would be redundant, anyway. So, I think the only reliable way of implementing this would be for the notification thread to also subscribe to `netconf-config-change` notification. Once it arrives, it knows it can send your custom notification. I do not think there is any other solution that would guarantee the order, it all works asynchronously.

**Comment by matkocc** [comment]
Thanks, I'll try to do that. 

I have a question regarding that.
Can we filter notifications with "xpath" parameter of sr_event_notif_subscribe_tree() function. 

E.g. can we subscribe something like this below?
rc = sr_event_notif_subscribe_tree(session,
                                       "ietf-netconf-notifications",
                                       "/ietf-netconf-notifications:netconf-config-change/edit[target="some string"]",
                                       (time_t)NULL,
                                       (time_t)NULL,
                                       netconf_config_change_cb,
                                       NULL,
                                       (int)SR_SUBSCR_DEFAULT,
                                       &netconf_config_change_subsctiption);
which will mean give me netconf-config-change notifs with target leaf="some string". If this is possible, how should xpath look like. This target leaf will be in form of "text1<something_configurable_by_client>text2" and we want get notifs that has target in that form , so xpath should look like this below ? 
"/ietf-netconf-notifications:netconf-config-change/edit["text1*text2"]".

If this is not possible, I assume that we need to subscribe to all netconf-config-change notifications and then in callback see if received notification has leaf that looks like "text1<something_configurable_by_client>text2" ?

It would be great if we can tell sysrepo through subscription function that we need netconf-config-change notif with speficific leaf(s).

Tnx,
   Matko

**Comment by michalvasko** [comment]
Yes, you are free to use any XPath filter to select specific notifications only.
