### ISSUE TITLE
Method/API to see all user inputed values of a full input  configuration instead of sequential.

### ISSUE THREAD

**Issue by Abrahamma97** [sysrepo/sysrepo#2577]
Hi @michalvasko ,
I had a query.Consider  I am subscribing the changes in leaf a and b. so a and b contains value a=2 and b=3. And b value  should never be 0(this is an example ok) . Suppose if I give a configuration with a = 1 and b = 0 then it should return failure. It actually does but the thing is it also changes the value of a=2 to a=1 (which should happen only if both a and b have correct input values.

So my question is if there is any way I can know in advance from the sysrepo server application the inputed value of a and b before giving returning success. If so I can give failure case right away before a is given success if value of b is wrong. I know it sounds a bit confusing but hope you get my point.

Thanks in advance.

**Comment by michalvasko** [comment]
It is confusing so I am not sure I will be able to help. Most importantly, if **any** of the callbacks fail for a set of changes, **all** the changes are reverted so what you are describing does not really make sense to me. Also, you can specify priorities for every callback and force a specific order this way.

**Comment by Abrahamma97** [comment]
The problem is consider the case
a = 0, b = 1,c=2, d=3   if but no two variables should be same
I gave input configuration as  a=1 b=1 c =2 d=3

So in such a scenario only a = 0->1 module change comes I cannot check the next config data that is coming at b, c, d. If I put my conditions to check equality and return SR_OP_Failed  the call back wont get triggered at a=1 b=1, c=2, d=3 and hence sysrepo will have the values a = 1, b =1, c =2 , d =3 which defeats my purpose



Hope you can understande what I meant @michalvasko

**Comment by michalvasko** [comment]
I may have understood now. So it seems to me the modules you are using should have expressed this constraint in their YANG modules using `must` or something similar, would save you all the problems. If they did not, you must check it yourself. You are free to call `sr_get_data()` (or similar functions) in the callback and retrieve any other values you need from *sysrepo*.

**Comment by Abrahamma97** [comment]
Yes sr_get_data() and get_items gets value of Sysrepo_Running right. Is it possible to get the data that is just pushed by configuration by netopeer client.
Consider me pushing configuration  a =1 b =1 c =1 d=1 in this order itself.
at EV_CHANGE of a = 0->1 am I able to get/read that  user input values of b=1 c =1 and d=1 before its respective EV_change comes. That would solve the problem.

**Comment by michalvasko** [comment]
Before, you said the previous configuration is `a = 0, b = 1, c = 2, d = 3` and you are setting it to ` a = 1, b = 1, c = 2, d = 3` meaning you only get notified about the change of `a`, that is what I reacted to. Now you are talking about some more changes, I do not think I can help you if you keep describing your use-case in such a confusing way.

**Comment by Abrahamma97** [comment]
Hi @michalvasko ,
Actually its the same thing you can take the previous example  a = 0, b = 1, c = 2, d = 3 and you are setting it to a = 1, b = 1, c = 2, d = 3,,,,, is there any way I can know the coming values of b,c,d before a=1 is accepted and SR_OK_SUCCESS is given?


Sorry for the confusion, it will be like sr_get_data() for the input config. Thanks

**Comment by michalvasko** [comment]
Instead of apologizing you need to ask for help properly, what you describing still does not really make sense and I will be completely repeating what I wrote before. Since you are changing only the value of `a`, there are no more "coming values" of any other nodes since they are not being changed. And you can get their value(s) in the callback using `sr_get_data()` or `sr_get_item()`, irrespective whether they are being changed or not (if they are, you will get the new values in the callback).
