### ISSUE TITLE
Default values from sr_get_subtree() result

### ISSUE THREAD

**Issue by iljatab** [sysrepo/sysrepo#2578]
$ yanglint --version
yanglint 2.0.71

$ sysrepoctl --version
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v2.0.34 (SO v6.4.1)

$ netopeer2-server -V
netopeer2-server 2.0.21

Hi,

I got a question regarding libnyang1 to libyang2 transition.

Our application populates sysrepo using `sr_set_item_str()` calls.
Then at some point the application calls `sr_get_subtree()` and traverses the resulting tree.
For leaf nodes it call `lyd_is_default(node)` to check if the value was explicitly set.

And it looks that `lyd_is_default()` returns `true` when the node value is equal to the default one - even if it was set explicitly earlier by `sr_set_item_str()`.
This is pretty different from behavior with libyang1 based software.

In my case it was with openconfig-interfaces.yang, leaf in question is `/openconfig-interfaces:interfaces/interface//subinterfaces/subinterface//config/index`.

Did I miss something for libyang transition or is it a bug?

Ilja.

**Comment by michalvasko** [comment]
Even from the documentation it is clear that the function `lyd_is_default()` does not check whether a node is a default one but rather whether its value equals to the default value, which is exactly the behavior you see. To check default nodes, simply check for `LYD_DEFAULT` flag in the data nodes. Also not sure how this is connected to *libyang* v1, I think it worked the same way there.

**Comment by iljatab** [comment]
Thanks!
