### ISSUE TITLE
oper data and counter get request callback

### ISSUE THREAD

**Issue by joanlandry** [sysrepo/sysrepo#258]
My understanding is that Netopeer2 will use sysrepo for both config data and pm/oper/counter data retrieval for a Netconf get request.

I have only seen the ability to register for a call back for config data changes. Is there a way to get a callback for a NETCONF get request on pm/oper / counter data using libnetconf2/netopeer2/sysrepo so that the device can fill in the data for these requests from the HW? This type of data is not config data, it is real time oper data and as such would not reside in the sysrepo data store as it is located in the device.

Also the plugin sample code appears to also be config data only as well.
Any info you can provide on how to do this would be very much appreciated.
thanks

**Comment by rastislavszabo** [comment]
Hi,

sure, we are just working on operational data support. You can have a look into the devel branch - some limited support of operational data is already there: https://github.com/sysrepo/sysrepo/blob/devel/inc/sysrepo.h#L1271-L1370

BTW: For general questions like these, you can also use sysrepo-devel mailing list: http://lists.sysrepo.org/listinfo

**Comment by joanlandry** [comment]
thanks for the reply - I am working on getting access to the mailing list.
Would you have an expected time frame/date of completion for oper data callback support to move to the main branch?

**Comment by rastislavszabo** [comment]
Hi,
very roughly, within the next 1 - 2 months. Maybe we will merge some partially working version into the master sooner.
