### ISSUE TITLE
Having a list element inside notification container

### ISSUE THREAD

**Issue by ChinmayaAgarwal** [sysrepo/sysrepo#2582]
Hi,

We want to have a list inside a notification container, like this: -

```yang
grouping prefixInfo {
		leaf peerId {
			type string;
			description "domain id";
		}
	
		container prefixList {
		  description
			"prefix information for terminal association";

		  leaf-list prefix {
			type inet:ip-address;
			description
			  "Prefixes value";
		  }
	
	}
	}


notification notif-terminal-association-info {
    description
      "This notification is sent when there is a change in the terminal association info.";
    leaf device-name {
      mandatory true;
      type leafref {
        path "/ta_yang_test:terminal-associations/"
            + "ta_yang_test:terminal-association/"
            + "ta_yang_test:device-name";
      }
      description
        "device name to identify a terminal association.";
    }
	
    container prefix-info-list{
	  list prefix-info{
	  container prefixesInfo {
		uses prefixInfo;
		}
	  }
    }
} 
```
Can we have such a definition for notification container? If yes, are there any sample application that generates notification for these kind of containers using sysrepo APIs?

Thanks and Regards,
Chinmaya Agarwal.

**Comment by michalvasko** [comment]
Yes, you can have such a notification. And the only application that may generate some example data of such a notification is `pyang` with its `sample-xml-skeleton` format but i have never tried it myself.

**Comment by ChinmayaAgarwal** [comment]
Thanks!

One thing, how can we generate this notification structure from our code using sysrepo API? All the example we saw for notification generation are writing to leaf elements. For ex: -

sr_val_t values[2];
values[0].xpath = "/ta_yang_test:terminal-association-info/device-name";
values[0].type = SR_STRING_T;
values[0].data.string_val = strdup("401");

rc = sr_event_notif_send(p_notif_session, "/ta_yang_test:terminal-association-info", values, 2, SR_EV_NOTIF_DEFAULT);

Can you point us to any code snippet for writing into the list elements?


Thanks and Regards,
Chinmaya Agarwal.

**Comment by michalvasko** [comment]
I would strongly advise against bothering with `sr_val_t` values, it is redundant. Try the [notif_send_example](https://github.com/sysrepo/sysrepo/blob/master/examples/notif_send_example.c) and you can basically just add to the code more `node_path`s to create as many nested nodes as you want.
