### ISSUE TITLE
operational data subscription facing issue with json format

### ISSUE THREAD

**Issue by chendrashekarp** [sysrepo/sysrepo#2583]
Hi @michalvasko ,

everything is working fine with .xml format (operational data subscription),
when i tried to use json format getting seg fault.

**json file content**

```
{
  "o-ran-fan:fan-tray": {
    "fan-state": [
      {   
        "name": "oran",
        "present-and-operating": true
      }   
    ]   
  }
}

```
**xml content for same data** 
```

<fan-tray xmlns="urn:o-ran:fan:1.0">
    <fan-state>
      <name>oran</name>
      <present-and-operating>true</present-and-operating>
    </fan-state>
  </fan-tray>
```

**call back function**

```
int subscribe_state_data_cb(sr_session_ctx_t *session,
                uint32_t sub_id,
                const char *module_name,
                const char *xpath,
                const char *request_xpath,
                uint32_t request_id,
                struct lyd_node **parent,
                void *private_data)
{
        char *buff = private_data;
     
        printf("in subscribe_state_data_cb\n"); 

        int rc=LY_SUCCESS;
        /*
         * @Populate operational data
        
        rc=lyd_parse_data_mem((struct ly_ctx *)sr_get_context(oran_srv.sr_conn),
                        buff,
                        0,
                        0,
                        LYD_VALIDATE_PRESENT,
                        parent);

        return rc;
}

```
adding yang model 
[o-ran-fan.txt](https://github.com/sysrepo/sysrepo/files/7211712/o-ran-fan.txt)

**Comment by michalvasko** [comment]
I have not managed to reproduce any problem because using `0` as `format` for `lyd_parse_data_mem()` always results in an invalid argument error.

**Comment by chendrashekarp** [comment]
Hi @michalvasko ,
then why xml format working fine.

**Comment by michalvasko** [comment]
Like I said, it did not work either when I tested it. I am on `devel` branches of both `sysrepo` and `libyang`.

**Comment by wxes9250310s** [comment]
You should set LYD_JSON for format parameter
It works for me, for your reference.
```
lyd_parse_data_mem(sr_get_context(sr_session_get_connection(session)), buffer, LYD_JSON, 0, LYD_VALIDATE_PRESENT, parent);
```

**Comment by michalvasko** [comment]
I am confused, what exactly is the problem? You are always supposed to correctly set the format of the input data. Automatic detection works only for files.

**Comment by chendrashekarp** [comment]
hi @michalvasko ,
this is the line i found in yang api doc  **Format of the input data to be parsed. Can be 0 to try to detect format from the input handler**
for format argument .
what exactly input handler is referring here ?(lyd_parse_data_mem)

Thanks .

**Comment by michalvasko** [comment]
Okay, I have clarified the comment. In any case, how exactly did you manage to get a crash? I could not reproduce that.

**Comment by chendrashekarp** [comment]
using sysrepo v2.0.37 & yang 2.0.81.
and using '0' as argument for format.
working fine for xml and getting crash when trying to give json file as input

**Comment by michalvasko** [comment]
Again, I have tried that but I always got invalid argument error. Can you maybe post output with `valgrind`?

**Comment by wxes9250310s** [comment]
In libyang document,
comment: Format of the input data to be parsed. Can be 0 to try to detect format from the input handler
is for (lyd_parse_data) instead of (lyd_parse_data_mem)

**Comment by chendrashekarp** [comment]
Working , using LYD_XML & LYD_JSON based on file format .
