### ISSUE TITLE
how to define XPath for oper data subscription to container under container

### ISSUE THREAD

**Issue by mrsugaranil** [sysrepo/sysrepo#2585]
Hello,

I am trying to subscribe to "operation data" at NETCONF server device. But, read-only(oper data) nodes are under configuration data container. I couldnt find that how I define **xpath for sr_oper_get_items_subscribe** API. My definition is;
**sr_oper_get_items_subscribe(session,"o-ran-mplane-int","/o-ran-mplane-int:mplane-info/m-plane-interfaces/m-plane-sub-interfaces/client-info", callback,NULL, SR_SUBSCR_CTX_REUSE, &subcription)**

When I try to get oper data with "get --filter-xpath=/o-ran-mplane-int:mplane-info/m-plane-interfaces/m-plane-sub-interfaces/client-info" from netopeer2-cli, I received error "nc ERROR: Session 1: SSH channel poll error(Socket error: disconnected). cli_send_recv: Failed to receive reply. Than, connection between server and client is breakdown. 

How can I solve this problem? Probably, I have mistake on defining XPath.
Related part of YANG model is shown below;
```yang
container m-plane-interfaces {
      description "information concerning m-plane interfaces";
      list m-plane-sub-interfaces {
        key "interface-name sub-interface";
        description "list of m-plane information";
        leaf interface-name {
          type leafref {
            path "/if:interfaces/if:interface/if:name";
          }
          description "the name of the interface";
        }
        leaf sub-interface {
          type leafref {
            path "/if:interfaces/if:interface[if:name = current()/../interface-name]/o-ran-int:vlan-id";
          }
          description
            "vlans used to communicate with management plane servers.";
        }
        container client-info {
          config false;
          description
            "the NETCONF client information, discovered by DHCP or manually
             configured during installation.";
          list mplane-ipv4-info {
            key mplane-ipv4;
            description "list of IPv4 NETCONF clients";
            leaf mplane-ipv4 {
              type inet:ipv4-address;
              description "The IPv4 address of M-Plane client discovered by the O-RU
              or manually configured.";
            }
            leaf port {
              type inet:port-number;
              description
                "The call home port number discovered or manually configured.";
            }
          }
          list mplane-ipv6-info {
            key mplane-ipv6;
            description "list of IPv6 NETCONF clients";
            leaf mplane-ipv6 {
              type inet:ipv6-address;
              description "The IPv6 address of M-Plane client discovered by the O-RU
              or manually configured.";
            }
            leaf port {
              type inet:port-number;
              description
                "The call home port number discovered or manually configured.";
            }
          }
          leaf-list mplane-fqdn {
            type inet:domain-name;
            description "The discovered FQDN(s) of M-Plane client(s).";
          }
        }
      }
```
Best Regards,
Anil

**Comment by michalvasko** [comment]
What versions are you using? Based on the error the server has crashed, that should never happen.

**Comment by mrsugaranil** [comment]
sysrepo 1.4.122
libyang 1.0.255
netopeer2 1.1.70

When I debug the code, the server crashes at the line of "*parent=lyd_new_path(NULL, **sr_get_context(sr_session_get_connection(sess)), "o-ran-mplane-int:mplane-info/m-plane-interfaces/m-plane-sub-interfaces/client-info/mplane-ipv4-info/mplane-ipv4", "192.168.1.1",0,0);** in the callback function. Otherwise, if only I printf something in the callback there is no problem.

**Comment by michalvasko** [comment]
Okay, I cannot really pinpoint the problem here, try using `valgrind` to get more information.
