### ISSUE TITLE
Backtrace in RPC subscribe example with latest master/devel builds

### ISSUE THREAD

**Issue by ankit7gup** [sysrepo/sysrepo#2586]
Hi Michal, 
I have tried using the latest master and devel branch builds for some RPC tests. RPC subscription callback is giving back trace. Same thing was working fine in older releases.
 Post this tested with RPC subscribe and send examples also, same behaviour.

Attaching the backtrace details.
[screenlog.txt](https://github.com/sysrepo/sysrepo/files/7241327/screenlog.txt)

 
 Kindly suggest. Thanks!
 
 Regards,
 Ankit

**Comment by michalvasko** [comment]
It is just a coincidence it did not crash before, the bug was there (in the example) for a long time, should now be fixed.

**Comment by ankit7gup** [comment]
Yes it worked fine with this fix now. Thanks!
