### ISSUE TITLE
Actual location of the file where sysrepo running/startup data stored 

### ISSUE THREAD

**Issue by bkumarrr** [sysrepo/sysrepo#2589]
Hi All
Can anyone please let me know the location of the sysrepo running/startup data store in filesystem ?
Thanks

**Comment by michalvasko** [comment]
When running `cmake`, look at `Startup data path` for the path with the startup files. Running is actually stored in SHM files, which are found in `/dev/shm`.

**Comment by bkumarrr** [comment]
Hi @michalvasko 
As I am cross compiling sysrepo,libyang,libnetconf2,netopeer2 using Yocto recipes. I am able to find running data in `/dev/shm`.But Not able to find startup data

**Comment by michalvasko** [comment]
Then like I wrote, look at the output of `cmake`. The exact value may depend on the [build type](https://github.com/sysrepo/sysrepo/blob/master/CMakeLists.txt#L127).
