### ISSUE TITLE
How actual transactions happens when a specific RPC is sent from netopeer2-cli to netopeer2-server

### ISSUE THREAD

**Issue by bkumarrr** [sysrepo/sysrepo#2590]
Hi All
Please anyone can explain or provide a block diagram of how a RPC from netopeer2-cli is handled and processed by netopeer2-server ?
Thanks in advance !

**Comment by michalvasko** [comment]
There is no such diagram and it is actually quite complex with regard to *sysrepo* but I suppose one could be made. What exactly are you interested in knowing?

**Comment by bkumarrr** [comment]
Hi @michalvasko 
Thanks for your reply.
I am interested in how to simple RPC from netopeer2-cli is handled by netopeer2-server .Just want a overview of this

**Comment by michalvasko** [comment]
So I have quickly drawn [something](https://github.com/CESNET/netopeer2/blob/devel/np2_arch.png), not sure if you can learn from that what you were interested in since you have not provided any more details.

**Comment by bkumarrr** [comment]
Hi @michalvasko 
Thanks for this :+1:
