### ISSUE TITLE
Internal error on change callback

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2591]
Hi,

I experience internal error when trying to commit data.
I attached the files needed for reproduction.
[reprod.zip](https://github.com/sysrepo/sysrepo/files/7260492/reprod.zip)

```
$ ./install.sh
$ ./application_changes_example ietf-interfaces &
Application will watch for changes in "ietf-interfaces".

 ========== READING RUNNING CONFIG: ==========

/ietf-interfaces:interfaces (container)


 ========== LISTENING FOR CHANGES ==========

$ sysrepocfg --import=config.xml -d running
```

At this point the application_changes_example will throw the internal error:
```
[ERR]: Unsatisfied range - value "-99" is out of the allowed range.
[ERR]: Internal error (/opt/dev/sysrepo/src/shm_sub.c:2510).
```

After that it is not possible to commit into the yang module, all attempts will result in timeout.

libyang version: 2.0.90
sysrepo version: 2.0.43

Thanks!

**Comment by michalvasko** [comment]
Still problems with the integers in *libyang*, hopefully the last one fixed now.

**Comment by awesomenode** [comment]
The error is gone with latest version, thanks!
