### ISSUE TITLE
sr_get_data() not returning default yang values

### ISSUE THREAD

**Issue by mbelgaum** [sysrepo/sysrepo#2594]
Hi
I have defined some default values for some leaf elements of yang module configuration file.
I m expecting that when sr_get_data() is called the default values will also be returned so that a it can be converted to json.
But sr_get_data() is returning only configured values provided by netconf client.

Expectation is that default value items may not be configured in netconf client and default values will be used.

Yang & function usage is as below, please help if I m missing something.
```yang
            leaf contents {
                           type string;
                           default "newrt";
                             description
                                   "The contents of rmr";
               }
```
```C
  {
  rc = sr_get_data(session, xpath, 0, 0, 0, &data);
      if (rc != SR_ERR_OK) {
          fprintf(stdout, "\nsr_get_data failed: %d\n", rc);
          return NULL;
      }
  
      if (data) {
          lyd_print_mem(&json_str, data, LYD_JSON, LYD_PRINT_WITHSIBLINGS);
      }
  }
```

Thanks

**Comment by michalvasko** [comment]
Try instead
```C
lyd_print_mem(&json_str, data, LYD_JSON, LYD_PRINT_WD_ALL | LYD_PRINT_WITHSIBLINGS);
```

**Comment by mbelgaum** [comment]
thanks. this suggestion worked for me.
Thanks a lot
