### ISSUE TITLE
Basic sysrepo functionality broken when deleting /dev/shm/*

### ISSUE THREAD

**Issue by syyyr** [sysrepo/sysrepo#2598]
Hi, since 820a661d31d019424730f2accc0d99ac14412bdb, basic functionality like installing modules doesn't work for me:
```
20: + /opt/cesnet-au//sysrepo/bin/sysrepoctl --search-dirs /home/vk/git/netconf-cli/tests --install /home/vk/git/netconf-cli/tests/example-schema.yang -a -v3
20: [INF] Applying scheduled changes.
20: [INF] No scheduled changes.
20: [INF] Datastore copied from <startup> to <running>.
20: [INF] Connection 1 created.
20: [INF] Module "example-schema" scheduled for installation.
20: [INF] File "other-module.yang" was installed.
20: [ERR] PLG: LYB DS file: Eaccess of "/dev/shm/netconf-cli_test_datastore_access_netconf_ietf-yang-library.operational" failed (No such file or directory).
20: [ERR] Callback "access_check" of plugin "LYB DS file" for module "ietf-yang-library" failed.
20: sysrepoctl error: Cannot apply changes because of existing connections
```
I am using sysrepo as non-root and also using a custom shm prefix and a custom repo location, I think that may be connected to this issue, because of the "No such file" error.

**Comment by syyyr** [comment]
Actually it seems that the error only comes up if one deletes /dev/shm/* files. This is what I use to start with clean sysrepo when running my tests. Is this not supported anymore?
In other words: sysrepo does work right after installation but stops working after purging /dev/shm

**Comment by michalvasko** [comment]
Right, I have tried to be more exact and strict when consolidating all the DS functionality into the plugin but it was too much in case of operational as the file will not exist even after reboot- Should be fixed now.

**Comment by syyyr** [comment]
That helped, thanks.
