### ISSUE TITLE
sr_commit() thread safe

### ISSUE THREAD

**Issue by ChinmayaAgarwal** [sysrepo/sysrepo#2600]
Hi,

Is sr_commit() thread safe? Can we call this method from multiple threads modifying the same or different subtree without implementing internal locking?

Thanks and Regards,
Chinmaya Agarwal.

**Comment by michalvasko** [comment]
Yes, it is thread-safe based on what is written in the [docs](https://netopeer.liberouter.org/doc/sysrepo/master/html/index.html#threads).
