### ISSUE TITLE
All notification subscribe request are sent as "/notifications:create-subscription"

### ISSUE THREAD

**Issue by sugar-dread** [sysrepo/sysrepo#2603]
Hi Michal,

I work on notification subscription to sysrepo. What I observed, whatever I send notif subscription over netopeer-cli2 with the --filter-xpath, it is sent as "/notifications:create-subscription". For example, if the first subscription is "subscribe --filter-xpath /o-ran-file-management:file-download-event" it is replied as OK. And this notification is successfully worked related to its plugin. After that, when I subscribe "subscribe  --stream o-ran-supervision" , I got error "session already subscribed." And I do not get notification from o-ran-supervision:supervision-notification. Moreover, I try vice versa first o-ran-supervision second o-ran-file-management, this time o-ran-supervision is successfully worked and other one does not work.

How can I subscribe notifications one by one from netopeer-cli2? 

Best regards,
Anil

**Comment by michalvasko** [comment]
This works per the [specification](https://datatracker.ietf.org/doc/html/rfc5277#section-6.5). If you want multiple subscriptions on a session, you will have to use the [new subscriptions](https://www.rfc-editor.org/rfc/rfc8639.html).
