### ISSUE TITLE
Getting sysrepoctl error with latest sysrepo

### ISSUE THREAD

**Issue by mbelgaum** [sysrepo/sysrepo#2608]
Hi
I m getting below sysrepoctl  error during yang data module install with latest version of sysrepo, libyang and netopeer2.
The same yang file used to work fine previously.

Step 39/72 : RUN /usr/local/bin/sysrepoctl -v3 -i /go/src/ws/agent/yang/ueec-config-v1.yang
 ---> Running in bd0a001bab7d
[INF] Applying scheduled changes.
[ERR] Internal error (/opt/dev/sysrepo/src/lyd_mods.c:1239).
[ERR] Failed to update data for the new context.
sysrepoctl error: Failed to connect (Operation failed)
The command '/bin/sh -c /usr/local/bin/sysrepoctl -v3 -i /go/src/ws/agent/yang/ueec-config-v1.yang' returned a non-zero code: 1

**Comment by michalvasko** [comment]
That is quite strange, could you please provide the steps and modules to reproduce it? Starting with `make sr_clean`.

**Comment by svlsr2000** [comment]
@michalvasko ,
I faced same issue. After executing make sr_clean issue vanished. I did 

- cmake ..
- make
- sudo make install

This didn't copy / make symbolic link for libsysrepo.so.6 in standard path. So when i tried executing sysrepoctl as root it was throwing error. So i copied libsysrepo.6.4.19 manually to /usr/local/lib/ and created symbolic link.
After this i was able to do sysrepoctl but ended up getting same error as @mbelgaum. 
I did make sr_clean, now magically issue vanished. 
I can try to reproduce issue again. Let me know if any logs needs to be enabled during any of the step. 

Regards,
Srinivasa Raghavan

**Comment by michalvasko** [comment]
> This didn't copy / make symbolic link for libsysrepo.so.6 in standard path.

with

> So i copied libsysrepo.6.4.19 manually to /usr/local/lib/ and created symbolic link.

does not make sense, `/usr/local/lib` should be the default prefix. But if you want the library to be installed to a specific path, you should have specified the prefix `cmake -DCMAKE_INSTALL_PREFIX=/usr/local/lib ..`.

The whole scenario sounds strange (it always does if you need to perform some unexpected manual steps) so I do not think it was caused by anything wrong in *sysrepo*.
