### ISSUE TITLE
Order of callback execution for different module subscription

### ISSUE THREAD

**Issue by ChinmayaAgarwal** [sysrepo/sysrepo#2611]
Hi,

I have two independent modules say X and Y. Using same sr_session_ctx_t object I created two subscriptions object for both the modules say subscription_x and subscription_y having respective callbacks callback_x and callback_y. As per our understanding since these callbacks are for independent modules, when we execute the below commands parallelly : -

sysrepocfg --import=config_x.xml --format=xml X
sysrepocfg --import=config_y.xml --format=xml Y

We should see the two callbacks being executed in parallel. But this is not the case, they are executed in sequential manner. 
How can we achieve parallelism in execution of these two callbacks using "sysrepocfg" as well as "edit-config"?

Thanks and Regards,
Chinmaya Agarwal

**Comment by michalvasko** [comment]
Firstly, what *sysrepo* version are you using? Based on your `sysrepocfg` command it seems to be *legacy* (0.7.8), is that right?
