### ISSUE TITLE
sysrepoctl error while installing yang models 6.0

### ISSUE THREAD

**Issue by adi33kumar** [sysrepo/sysrepo#2616]
With latest sysrepo, libyang, and libnetconf2. while installing yang models following error is coming.
sysrepoctl: ..../libyang/src/parser_json.c:1302: lydjson_subtree_r: Assertion `status == LYJSON_OBJECT' failed.

**Comment by michalvasko** [comment]
Latest means current `master` (latest release)? Please provide the modules and steps to reproduce.

**Comment by wel2021** [comment]
> Sorry, its ordering issue while installing the yang module. We can close this issue.

Hello，adi33kumar
May I ask how you solved this problem, because I also encountered it, but it didn't solve it

Regards！
