### ISSUE TITLE
Support for writing multiple values in datastore

### ISSUE THREAD

**Issue by ashishsaxenahsc** [sysrepo/sysrepo#2625]
Hi sysrepo devs,
sysrepo provides sr_set_item()  and sr_set_item_str()  APIs for writing single values in sysrepo . Is there any similar API that support writing multiple values in the datastore ?

Thanks and Regards,
Ashish

**Comment by jktjkt** [comment]
This is explained in the [docs about the data editing API](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__edit__data__api.html); you probably want to use the `sr_edit_batch()` function.
