### ISSUE TITLE
cant load new YANG Moduels

### ISSUE THREAD

**Issue by AdianComits** [sysrepo/sysrepo#2626]
Hello there , 
am facing an issue when trying to install new data models into sysrepo:
sudo sysrepoctl -v3 --install ieee802-dot1q-qci-augment.yang 
[INF]: Scheduled changes not applied because of other existing connections.
[INF]: Connection 33 created.
[ERR]: Data model "ieee802-dot1q-bridge" not found in local searchdirs.
[ERR]: Importing "ieee802-dot1q-bridge" module failed.
sysrepoctl error: Failed to install module "ieee802-dot1q-qci-augment.yang" (libyang error)
[INF]: No datastore changes to apply.
 can you please help ?

**Comment by michalvasko** [comment]
It prints the error exactly but fine, I guess. The module you are trying to install (`ieee802-dot1q-qci-augment`) imports another module (`ieee802-dot1q-bridge`) and you cannot install the module with all of its imports. So *sysrepo*/*libyang* tries to find this module (it does not search in many places by default intentionally) but fails in this case. You need to tell `sysrepoctl` where the imports are located, generally by specifying the directory with `-s`.

**Comment by AdianComits** [comment]
sudo sysrepoctl -v3 -s ~/Downloads/sysrepo-tsn-master/modules/ieee802-dot1q-qci-augment.yang 
[INF]: Scheduled changes not applied because of other existing connections.
[INF]: Connection 37 created.
sysrepoctl error: No operation specified
[INF]: No datastore changes to apply.
same issue

**Comment by michalvasko** [comment]
Look, I cannot help you with basic Linux shell literacy and you will keep encountering all kinds of problems unless you learn it. This is the last time I am helping you, you are not having problem with our tools. Try
```
sudo sysrepoctl -v3 -s ~/Downloads/sysrepo-tsn-master/modules/ -i ~/Downloads/sysrepo-tsn-master/modules/ieee802-dot1q-qci-augment.yang
```

**Comment by AdianComits** [comment]
Thanks for your support but its not working 
sudo sysrepoctl -v3 -s ~/Downloads/sysrepo-tsn-master/modules/ -i ~/Downloads/sysrepo-tsn-master/modules/ieee802-dot1q-qci-augment.yang
[sudo] password for adian: 
[INF]: Scheduled changes not applied because of other existing connections.
[INF]: Connection 38 created.
[ERR]: Data model "ieee802-dot1q-bridge" not found in local searchdirs.
[ERR]: Importing "ieee802-dot1q-bridge" module failed.
sysrepoctl error: Failed to install module "/home/adian/Downloads/sysrepo-tsn-master/modules/ieee802-dot1q-qci-augment.yang" (libyang error)
[INF]: No datastore changes to apply.
 
Best Regards,
Adian

**Comment by michalvasko** [comment]
Well, is `ieee802-dot1q-bridge.yang` file present in `~/Downloads/sysrepo-tsn-master/modules/`? If not, then you are simply missing the module file, you cannot load the other module without it.
