### ISSUE TITLE
Feature not working ?

### ISSUE THREAD

**Issue by Lionelrt** [sysrepo/sysrepo#2632]
With the following IEEE module imported in sysrepo https://github.com/YangModels/yang/blob/master/standard/ieee/draft/802.1/Qcw/ieee802-dot1q-sched.yang and the scheduled-traffic feature disabled, we still get warnings in the admin-control-list check.
Module and dataset import were working fine in 1.4

**Comment by michalvasko** [comment]
Is the warning valid or not? The whole schema is checked irrespective of features because even if there are problems in disabled nodes, the schema is still not valid.

**Comment by Lionelrt** [comment]
The yang schema is valid, it is properly imported in sysrepo. With the featue enabled, I can import relevant dataset. But with the feature disabled, I get errors with a dataset not containing feature related information.

**Comment by michalvasko** [comment]
With latest *libyang* (2.0.113) I got a lot of warnings but not the ones you mentioned, whether I enable the feature or not.
