### ISSUE TITLE
[QUESTION] Query on Union Datatype for config data

### ISSUE THREAD

**Issue by ankit7gup** [sysrepo/sysrepo#2636]
Hi Michal,

I have a query regarding the Union datatype usage in sysrepo. 

**Below is the use case:**
```yang
typedef new_str {
  type string {
    max length 10;
    pattern(<some pattern>);
  }
}

container cont {
  leaf l {
    type union {
      type string;
      type new_str;
    }
  }
}
```
The xpath is this case shall be: /cont/l
And the Type of data shall be SR_STRING_T, Now the question is, Is there any way to deduce which type has been used for the union, within sysrepo.

Thanks!

Regards,
Ankit

**Comment by michalvasko** [comment]
Well, what do you mean within *sysrepo*? If you retrieve this data using `sr_get_data()`, for example, you can find this information if you dig into the node. But you will not learn this from the `sr_val_t` structure.
