### ISSUE TITLE
sysrepoctl -l error

### ISSUE THREAD

**Issue by wel2021** [sysrepo/sysrepo#2640]
Hi，

version：
sysrepo devel:
Commits on Aug 4, 2021
VERSION bump to version 2.0.34
commit ID:8a01c75f5a95dc33d5e1193d5b79f629c76c645e

libyang devel:
VERSION bump to version 2.0.71

root@ubuntu:/mnt/project/sysrepo/build# sysrepoctl -l
sysrepoctl: /mnt/project/libyang/src/parser_json.c:1273: lydjson_subtree_r: Assertion `status == LYJSON_OBJECT' failed.
Aborted

Before that, a Yang file was installed. After that, it is useless to reinstall libyang and sysrepo

Regards,

**Comment by wel2021** [comment]
Supply info:
root@ubuntu:~# sysrepoctl -l -v3
[WRN]: Recovered a lock with a dead owner (sr_lydmods_conn_ctx_update).
[INF]: Applying scheduled changes.
sysrepoctl: /mnt/project/libyang/src/parser_json.c:1273: lydjson_subtree_r: Assertion `status == LYJSON_OBJECT' failed.
Aborted (core dumped)

**Comment by wel2021** [comment]
Supply info:
root@ubuntu:~# sysrepoctl -l -v3
[WRN]: Recovered a lock with a dead owner (sr_lydmods_conn_ctx_update).
[INF]: Applying scheduled changes.
sysrepoctl: /mnt/project/libyang/src/parser_json.c:1273: lydjson_subtree_r: Assertion `status == LYJSON_OBJECT' failed.
Aborted (core dumped)

**Comment by michalvasko** [comment]
Try to use the latest *libyang*, at least the latest release v2.0.112. Should be fixed there.

**Comment by wel2021** [comment]
> 
Excuse me, do you mean to update the version and solve this assert?

**Comment by michalvasko** [comment]
Yes, I am saying if you update your *libyang*, you should no longer encounter the failed assert.

**Comment by wel2021** [comment]
Libyang was updated to 2.0.114, but the following error occurred

> Yes, I am saying if you update your _libyang_, you should no longer encounter the failed assert.
sysrepo version 2.0.34
Libyang was updated to 2.0.114, but the following error occurred，

**Comment by michalvasko** [comment]
Yes, the LYB file format was updated so you must remove all previous sysrepo LYB files (and it would be safest to update not just libyang but all the projects, sysrepo, libnetconf2, and netopeer2). Just run `make sr_clean` for *sysrepo* but then you will have to install all your YANG modules and set their data again.

**Comment by wel2021** [comment]
Yes，make sr_clean is valid，thank you for your support！
