### ISSUE TITLE
Dependency to old revision of the module updated

### ISSUE THREAD

**Issue by mblacksee** [sysrepo/sysrepo#2646]
Hi,
When I try to update a YANG module (my-device@2021-11-01) with a newer version (my-device@2021-11-02), process is completed w/o any error and I'm able to see new revison of the module (my-device@2021-11-02) from the output of `sysrepoctl -l`.
But If I try to get data from another module it complains as below. Somehow, old revison of the module is requested by the system.

```
sysrepocfg -X -x /ietf-system:system/hostname -f json -v3
[INF] Connection 21 created.
[INF] Session 17 (user "root", CID 21) created.
[ERR] LYB DS file: Invalid context for LYB data parsing, missing module "my-device@2021-11-01".
[ERR] Callback "load" of plugin "LYB DS file" for module "ietf-system" failed.
sysrepocfg error: Getting data failed (libyang error)
[INF] No datastore changes to apply.
```

sysrepo version in the system is 2.1.1 (cfa7959)
libyang version in the system is 2.0.117 (5f20141)
(They are at the top of devel branches by the moment)

What might be the problem?
Thanks in advance, BR.

**Comment by michalvasko** [comment]
Please provide the used YANG modules, I have tried it with a simple augment and it worked fine so the dependency in your case will be different.

**Comment by mblacksee** [comment]
Hi Michal,
Modules are as below;
iana-crypt-hash.yang
iana-if-type.yang
ietf-interfaces.yang
ietf-system.yang
mimosa-device.yang
mimosa-wifi-types.yang
mimosa-wifi.yang

The problem is raised when the revision of `mimosa-device.yang` is changed and updated then.
Thanks, BR.

[iana-crypt-hash.yang.txt](https://github.com/sysrepo/sysrepo/files/7618079/iana-crypt-hash.yang.txt)
[ietf-system.yang.txt](https://github.com/sysrepo/sysrepo/files/7618080/ietf-system.yang.txt)
[ietf-interfaces.yang.txt](https://github.com/sysrepo/sysrepo/files/7618081/ietf-interfaces.yang.txt)
[iana-if-type.yang.txt](https://github.com/sysrepo/sysrepo/files/7618082/iana-if-type.yang.txt)
[mimosa-wifi-types.yang.txt](https://github.com/sysrepo/sysrepo/files/7618083/mimosa-wifi-types.yang.txt)
[mimosa-device.yang.txt](https://github.com/sysrepo/sysrepo/files/7618084/mimosa-device.yang.txt)
[mimosa-wifi.yang.txt](https://github.com/sysrepo/sysrepo/files/7618085/mimosa-wifi.yang.txt)

**Comment by michalvasko** [comment]
Thanks, should be fixed in the latest `devel`.

**Comment by mblacksee** [comment]
Thanks Michal, It is fixed!
BR.
