### ISSUE TITLE
copy-config complete notification

### ISSUE THREAD

**Issue by matth65** [sysrepo/sysrepo#2648]
Hello,

Is it possible to setup a subscription to be notified when a copy-config operation completes? This would allow the backend application to log the fact that 'replace' config operation took place, as well as perform some additional processing after applying the 'replaced' configuration.

Regards,
Matt

**Comment by michalvasko** [comment]
If you are talking about `sr_copy_config()` then it internally works exactly as `sr_apply_changes()` (for example) so you cannot be notified about the whole operation, only about the changes the operation caused.

**Comment by matth65** [comment]
Yes, assuming that the Netconf <copy-config> operation translates into the sr_copy_config() API. In looking at the Netopeer2 code, it looks like <copy-config> can result in sr_copy_config() when copying one datastore to another, and sr_replace_config() when a file is specified.

Is there a way to tell what kind of operation is being performed (copy vs. replace vs. edit) from the change subscription callback (sr_module_change_cb)?

**Comment by michalvasko** [comment]
No, it is not. Like I said, they all internally behave as a data edit.

**Comment by matth65** [comment]
ok, thank you for the information.
