### ISSUE TITLE
sr_session_get_orig_name returns non-null stuff even when originator not set

### ISSUE THREAD

**Issue by syyyr** [sysrepo/sysrepo#2649]
Hi, I have some questions about sr_session_get_orig_name. The documentation says that it return NULL if there's no originator set. However, it seems to me that when it's not set, it actually returns an empty string.
```cpp
#include <iostream>
#include <sysrepo.h>
#include <string>

int operGetItemsCb(sr_session_ctx_t* session, uint32_t subscriptionId, const char* moduleName, const char* subXPath, const char* requestXPath, uint32_t requestId, lyd_node** parent, void* privateData)
{
    auto name = sr_session_get_orig_name(session);
    std::cerr << "name from oper = " << (name ? name : "nullptr") << "\n";
    return SR_ERR_OK;
}

void notif_suspend_cb(sr_session_ctx_t *session, uint32_t sub_id, const sr_ev_notif_type_t notif_type, const char *xpath,
        const sr_val_t *values, const size_t values_cnt, struct timespec *timestamp, void *private_data)
{
    auto name = sr_session_get_orig_name(session);
    std::cerr << "name from notif = " << (name ? name : "nullptr") << "\n";
}

int main(int argc, char* argv[])
{
    sr_conn_ctx_t* conn = nullptr;
    sr_connect(0, &conn);
    sr_session_ctx_t* sess = nullptr;
    sr_session_start(conn, SR_DS_RUNNING, &sess);
    sr_subscription_ctx_t* sub = nullptr;
    sr_oper_get_subscribe(sess, "test_module", "/test_module:stateLeaf", operGetItemsCb, nullptr, 0, &sub);
    sr_notif_subscribe(sess, "test_module", "/test_module:myNotif", nullptr, nullptr, notif_suspend_cb, nullptr, 0, &sub);

    sr_session_ctx_t* sess2 = nullptr;
    sr_session_start(conn, SR_DS_RUNNING, &sess2);
    lyd_node* notifNode;
    lyd_new_path(nullptr, sr_session_acquire_context(sess2), "/test_module:myNotif", nullptr, 0, &notifNode);
    sr_notif_send_tree(sess2, notifNode, 0, 1);
    lyd_free_all(notifNode);

    sr_session_switch_ds(sess2, SR_DS_OPERATIONAL);
    sr_data_t* data;
    sr_get_data(sess2, "/test_module:stateLeaf", 0, 0, 0, &data);
    sr_release_data(data);

    sr_disconnect(conn);

    return 0;
}
```
This kind of code returns this for me:
```
$ ./a.out 
name from oper = 
name from notif = 
name from notif = nullptr
```
The operational callback says that it's an empty string. First call of the notif callback also says empty string, the second (I think that's the terminate callback) says nullptr. If I actually do use the sr_session_set_orig_name, then all the callbacks get the correct orig_name, so the only real problem is when it's not set. I find this kind of weird, because I can see that there some tests that check for NULL, so maybe I'm doing something incorrectly?

**Comment by michalvasko** [comment]
I see. It seems this is a bit of a mess like you observed. In the callback I believe no getters should return `NULL` but an empty string instead. This is caused by the SHM communication where it is not possible to store `NULL` and an empty string is stored and then loaded instead. The `NULL` you see is most likely read from some temporary session that has not loaded its originator information from a SHM.

So I should probably fix that last `NULL` and update the documentation, what do you think?

**Comment by syyyr** [comment]
>So I should probably fix that last NULL and update the documentation, what do you think?

Yup, I think that's a good idea.

**Comment by syyyr** [comment]
Also, I think this should be an error:
```
sr_session_set_orig_name(sess2, nullptr);
```
That is, setting the originator name to NULL.

**Comment by syyyr** [comment]
And also I think that calling `sr_session_get_orig_name` outside of the callback (in my main function) should also return an empty string and not NULL.
```cpp
    sr_session_start(conn, SR_DS_RUNNING, &sess2);
    auto orig = sr_session_get_orig_name(sess2);
    if (orig) {
        std::cerr << "Got orig name\n";
    } else {
        std::cerr << "Got nullptr\n";
    }
```
So basically, I would like orig_name to be initialized to an empty string when the session is created.

**Comment by michalvasko** [comment]
> Also, I think this should be an error:
sr_session_set_orig_name(sess2, nullptr);
That is, setting the originator name to NULL.

I see no reason for that, it does not matter. Other than that, it should be fixed (forgot tot reference the issue).

**Comment by syyyr** [comment]
Thanks.
