### ISSUE TITLE
Dockerfile ENV line

### ISSUE THREAD

**Issue by kobi-ca** [sysrepo/sysrepo#2653]
Hello,

Should this:
https://github.com/sysrepo/sysrepo/blob/master/deploy/docker/sysrepo-netopeer2/latest/Dockerfile#L92
be:
```
ENV EDITOR=vim
```
instead ?

**Comment by michalvasko** [comment]
Not sure, but you may be right. In any case, I have not written these scripts and am not maintaining them, they are far from "latest" so I have removed them. The images are still present on dockerhub but I am afraid they are not really maintained either.
