### ISSUE TITLE
Milestone 1 (YANG Push, RFC 8641) status

### ISSUE THREAD

**Issue by gotthardp** [sysrepo/sysrepo#2656]
Hello, what is the status of the milestone 1 https://github.com/sysrepo/sysrepo/milestone/1 and related issue https://github.com/sysrepo/sysrepo/issues/2276, please?

I see similar issues https://github.com/CESNET/netopeer2/issues/792, https://github.com/CESNET/netopeer2/issues/794 and https://github.com/CESNET/netopeer2/issues/797 were closed, the support for RFC 8641 is even listed in the Netopeer2 README, but not in Sysrepo. This is quite confusing as Netopeer2 is said to use Sysrepo as a datastore.

**Comment by michalvasko** [comment]
I have missed that one issue, it has all been implemented some time ago.

**Comment by gotthardp** [comment]
Thanks for the clarification!
