### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by rydy** [sysrepo/sysrepo#2666]
Hi,
	I have a few questions for Netconf kits.
	1, Will V1 continue to be maintained and developed ?
	2, Does the latest version not support C++ (The 'bindings' directory was not found) ?
Best regards.
thanks

**Comment by michalvasko** [comment]
1. Version 1 will probably continue to be supported the way it was this year meaning some simple fixes will be implemented. But no time costly improvements and definitely no actual development will be done.
2. It is being worked on by an external team, all the bindings now have separate projects. The C++ bindings can be found [here](https://github.com/sysrepo/sysrepo-cpp/) but are still work-in-progress.

**Comment by rydy** [comment]
> 1. Version 1 will probably continue to be supported the way it was this year meaning some simple fixes will be implemented. But no time costly improvements and definitely no actual development will be done.
> 2. It is being worked on by an external team, all the bindings now have separate projects. The C++ bindings can be found [here](https://github.com/sysrepo/sysrepo-cpp/) but are still work-in-progress.

When will sysrepo-CPP be released?  Is master available now?

**Comment by michalvasko** [comment]
Like I said, it is developed externally, there is a reason it is a separate project. If you have any questions about it, you need to put your question in that project, I do not know much details.

**Comment by rydy** [comment]
> Like I said, it is developed externally, there is a reason it is a separate project. If you have any questions about it, you need to put your question in that project, I do not know much details.

I see. Thank you
