### ISSUE TITLE
Unable to get data  using sysrepo API

### ISSUE THREAD

**Issue by Abrahamma97** [sysrepo/sysrepo#2669]
Hi @michalvasko ,
I use
```
sr_val_t *llrx_ep_val_eaxc_id;
sr_get_item(session, "/o-ran-uplane-conf:user-plane-configuration/low-level-rx-endpoints[name='sllrx-endpoint0']/e-axcid/eaxc-id", 0, &llrx_ep_val_eaxc_id);
```
and I get error
```
[ERR]: No data found for "/o-ran-uplane-conf:user-plane-configuration/low-level-rx-endpoints[name='sllrx-endpoint0']/e-axcid/eaxc-id".
```
But when I try the same with netopeer2 client I am able to get the following:
```
get --filter-xpath /o-ran-uplane-conf:user-plane-configuration/low-level-rx-endpoints[name='sllrx-endpoint0']/e-axcid/eaxc-id
DATA
<user-plane-configuration xmlns="urn:o-ran:uplane-conf:1.0">
  <low-level-rx-endpoints>
    <name>sllrx-endpoint0</name>
    <e-axcid>
      <eaxc-id>2</eaxc-id>
    </e-axcid>
  </low-level-rx-endpoints>
</user-plane-configuration>
```

**Comment by michalvasko** [comment]
Executing `sr_get_item()` and RPC `<get>` are not equivalent. I am not sure why the former fails but you may want to check the datastore you are getting the data from, the data in `running` are different than in `operational`, `<get>` reads the data from both these datastores.

**Comment by Abrahamma97** [comment]
@michalvasko may I know the difference between operational and running. Or if a link is available that will suffice. Just to get more idea.

**Comment by michalvasko** [comment]
You can learn everything about the NMDA in the (quite complex) [RFC](https://datatracker.ietf.org/doc/html/rfc8342). All the supported datastores are implemented based on their definition in this architecture.
