### ISSUE TITLE
stale subscription sockets

### ISSUE THREAD

**Issue by jjin62** [sysrepo/sysrepo#267]
Sometimes, not always, if sysrepod is restarted, the following error message shows:

[ERR] (cm_subscr_conn_create:1249) Unable to connect to subscriber socket=/tmp/sysrepo-subscriptions/com-att-device/25210.Qckquw.sock: Connection refused

The only way to recover is to remove /tmp/sysrepo-subscriptions manually and restart sysrepod.

**Comment by rastislavszabo** [comment]
Hi,

please add some more details:

the application that subscribes to com-att-device is a sysrepo plugin? Is it still running when you restart the sysrepod? Or has it been somehow restarted/killed before?

The error message is expected in case that subscriber was killed and did not have chance to properly call sr_unsubscribe. In that case, the socket will be retained in the socket directory and sysrepod will try to connect to it, but when it discovers that it is not able to connect to that socket, it automatically removes the subscription from the list of susbscribers. The error message above is a side effect of this sanity check.

**Comment by jjin62** [comment]
Thanks for explaining.
The application is independent process using sysrepo client APIs to subscribe data store change.  If it is as your described, we can change the message from error to warning?

**Comment by rastislavszabo** [comment]
Yes, I'll make a warning out of this.
