### ISSUE TITLE
Unable to get leaf value during CHANGE event that is previously set during UPDATE event.

### ISSUE THREAD

**Issue by AleksandarV1** [sysrepo/sysrepo#2670]
Hi,

I have the following setup:

1. yang module:
```
 module my-module {
    namespace "urn:sysrepo:my-module";
    prefix my;
    revision 2018-01-19 {
        description "Initial revision.";
    }
    
    container my-container{
    	leaf val
    	{
    		type uint32;
    	}
    }
}
```
2. Callback subscribed to **leaf val**  with SR_SUBSCR_UPDATE flag:
```
static int
val_change_cb(sr_session_ctx_t *session, const char *module_name, const char *xpath, sr_event_t event,
        uint32_t request_id, void *private_data)
{

    (void)module_name;
    (void)xpath;
    (void)event;
    (void)request_id;
    (void)private_data;
    sr_val_t* srval = NULL;
    int rc = 0;
	
    if(SR_EV_DONE == event)
    {
        SRP_LOG_ERR("DONE EVENT");
        return SR_ERR_OK;
    }
    else if(SR_EV_UPDATE == event)
    {
        SRP_LOG_ERR("UPDATE EVENT");
        sr_set_item_str(session, "/my-module:my-container/val", "10", NULL, 0);
        return SR_ERR_OK;
    }
    else if(SR_EV_CHANGE == event)
    {
        SRP_LOG_ERR("CHANGE_EVENT");
        if(SR_ERR_OK != (rc = sr_get_item(session, "/my-module:my-container/val", 0, &srval)))
        {
            SRP_LOG_ERR("GET ERROR");
            return SR_ERR_OPERATION_FAILED;
        }

        SRP_LOG_ERR("VAL %d", srval->data.uint32_val);

        sr_free_val(srval);
    }

    return SR_ERR_OK;
}
```
What I'm trying to accomplish is to change leaf val value during UPDATE event and to get that value during CHANGE event, but it fails with the following error:
**Internal error (/.../sysrepo/src/edit_diff.c:2753).**

Question: Is this a valid use case and if so what could be the potential error? 
Versions of the libs that I'm using:
1. libyang 1.0.240
2. libnetconf2 1.1.43
3. libssh 0.9.5
4. sysrepo 1.4.122
5. netopeer2 1.1.70

BR,
Aleksandar

**Comment by michalvasko** [comment]
Those are fairly old versions you are using, it may be enough to update to 1.4.150 but best is to use *sysrepo* v2. I am pretty sure it is fixed either in both of them or in v2.

**Comment by AleksandarV1** [comment]
_it may be enough to update to 1.4.150_ - It works fine with 1.4.150. 

Regards,
Aleksandar.
