### ISSUE TITLE
[Question] subscribing for any configuration change across modules

### ISSUE THREAD

**Issue by iGovindY** [sysrepo/sysrepo#2671]
Hi,

we want to have a utility to log any configuration change in any module installed on system.

Is there a way with current APIs to subscribe for all modules installed in sysrepo, without getting the names of modules installed with ` sysrepoctl -l ` and subscribing one by one?

similarly for RPC subscription.

**Comment by michalvasko** [comment]
There is still the obsolete `ietf-netconf-notifications:netconf-config-change` notification that *sysrepo* generates so for data changes it should be enough to subscribe to it. But nothing like that is possible for RPCs.
