### ISSUE TITLE
sr_get_module_info() substitute

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2674]
Hi!

sysrepo 2.1 removed the `sr_get_module_info()` function, according to the
documentation it was redundant.

I used this function to determine module dependencies from the internal
sysrepo module.

As a new solution I tried:
`rc = sr_get_subtree(sr_session, "/sysrepo:sysrepo-modules/module", 0, &sr_modules);`

But `sr_modules` always returns empty.

Should this work, or `sr_get_subtree()` is unable to retrieve data from
internal modules? Is there perhaps another way to access the module
dependencies?

Thanks!

**Comment by michalvasko** [comment]
I see, the dependencies were made public mostly accidentally (other information from these data was needed) and that information is meant for internal use only. But, if you really need this information, providing it in standard data retrieval functions (`sr_get_data`, `sr_get_subtree`, ...) can be supported. Except I am mostly finished with work for this year so you will have to wait a few weeks for the next.

**Comment by awesomenode** [comment]
Yes, thank you, that would help me a lot!

I need the dependencies for some high-level functionalities.

**Comment by michalvasko** [comment]
I have added the function back, after all, because this module is just too specific to be handled like all the others.
