### ISSUE TITLE
How to quickly  get a large amount of data in running db?

### ISSUE THREAD

**Issue by itercheng** [sysrepo/sysrepo#2681]
Hi

environment: Centos 7. version: libyang-1.0.240  sysrepo-1.4.140
 
There is a large amount of data in my running db, at least 3000 parameters, it will take a lot of time when use sr_get_items API to get all parameters. what i do now is to assemble each one specific xpath from root node, And then get value by xpath. Some have 6 levels of depth, and some have lists that i need to go through one by one. The whole reading operation took about three minutes. Could this be improved on speed? Or is there a better way to read  each one parameter?
 
Thank you in advance.

**Comment by michalvasko** [comment]
Reading all the data is actually simple and should be efficient. Just call `sr_get_data()` with XPath matching all the data you are interested in and you can then iterate over the returned data tree with all the nodes, not interacting with *sysrepo* anymore.
