### ISSUE TITLE
custom datastore plugin exmaple

### ISSUE THREAD

**Issue by yajing111** [sysrepo/sysrepo#2683]
hi, michalvasko

Like 'oven' plugin, is there an example about how to write a datastore plugin? Or could you please give some guide for it?

Thanks a lot!

**Comment by michalvasko** [comment]
No, there is no example nor a guide for DS plugins. Generally, you should be able to do so if you look at the [default plugin](https://github.com/sysrepo/sysrepo/blob/devel/src/plugins/ds_lyb.c) code and the [API docs](https://github.com/sysrepo/sysrepo/blob/devel/src/plugins_datastore.h). Implementing your own datastore is not trivial so you may be missing some information that is expected for you to have before attempting this.

**Comment by yajing111** [comment]
Thanks for your reply. As you said in https://github.com/sysrepo/sysrepo/issues/2609#, this custom DS feature has not really been tested much. When have you own your DS plugin for our reference?

**Comment by michalvasko** [comment]
The best reference custom DS implementation is the default one I linked in my previous reply. I am also currently working on another, which is, however, quite unique and hence would not serve as a good reference. Other than that, there are currently no plans for more custom DS plugins.

> this custom DS feature has not really been tested much

Back then I meant that no custom DS plugin whas actually been written except for the default datastore being rewritten to be a plugin. When working on this another DS plugin, I have not encountered any significant problems and the API itself is fairly simple, it is the plugin code that may be complicated, depends on the kind of the datastore. So II think that the API is perfectly usable and I expect only minor improvements in near future.

**Comment by yajing111** [comment]
hi, michalvasko

How to make my DS plugin running?  Is it the correct that call API sr_install_module_custom_ds in my program?

**Comment by michalvasko** [comment]
Yes, after you have installed the plugin, you use that function to actually set the plugin for a new module. You can also use `sysrepoctl` for installing a module with custom DS.

**Comment by yajing111** [comment]
hi, michalvasko

Thanks for your quick reply.


Now when installing my test yang model, I have another ploblem: sysrepoctl giving core dump



> [root@ba8c58b40586 plugin]# sysrepoctl -P /rcphome/yajshan/OPSW/sysrepo-master/build/trsds.so  -v3
[root@ba8c58b40586 plugin]# sysrepoctl -L
Datastore plugins:
        LYB DS file
        nestrsds

Notification plugins:
        LYB notif
[root@ba8c58b40586 plugin]#
[root@ba8c58b40586 plugin]#
[root@ba8c58b40586 plugin]# sysrepoctl -i oven.yang -m startup:nestrsds -v3
[INF] DS plugin "nestrsds" loaded.
[INF] Connection 5 created.
[INF] Module "oven" was installed.
Segmentation fault (core dumped)


and for sysrepoctl -l

getting this :

> 
[root@ba8c58b40586 plugin]# sysrepoctl -l -v3
[INF] DS plugin "nestrsds" loaded.
[WRN] Connection with CID 5 is dead.
Segmentation fault (core dumped)

**Comment by michalvasko** [comment]
Run it with `valgrind`, almost certainly it is crashing in one of the callbacks.

**Comment by yajing111** [comment]
hi, michalvasko

I have a question about install my yang module with specifying datastore plugin named nestrsds.

If my yang module import some other modules, for example:

> module my-iprouting {
  yang-version "1.1";
  namespace "urn:rdns:nokia:rcp:my-iprouting";
  prefix iprt;
  import ietf-inet-types { prefix inet; }
  import ietf-routing { prefix "rt"; }
  import ietf-ipv4-unicast-routing { prefix "v4ur"; }
  import ietf-ipv6-unicast-routing { prefix "v6ur"; }  
  ...
    }
  typedef table-id {
    type uint32 {
      range "1..249";
    }
    description
     "Route table index value, range 1..249.";
  } 
  augment "/rt:routing/rt:control-plane-protocols/rt:control-plane-protocol" {
    description
      "This leaf augments the 'control-plane-protocol' case of routing";
    leaf owner {
      type string;
      description
        "The name of a node or a Pod.";
    }
    leaf table {
      type table-id;
      description
        "Route table index, identifies a table entry of routes.";
    }
  }
}

My question is : I install my yang module **my-iprouting.yang** with specifying datastore plugin, is it necessary to set the same plugin for these imported modules(**ietf-routing, ietf-ipv4-unicast-routing, ietf-ipv6-unicast-routing**) when installation?

like below:

`sysrepoctl -i /tmp/ietf-routing@2018-03-13.yang -m startup:nestrsds`
`sysrepoctl -i /tmp/ietf-ipv4-unicast-routing@2018-03-13.yang -m startup:nestrsds`
`sysrepoctl -i /tmp/my-iprouting.yang -m startup:nestrsds`

**Comment by michalvasko** [comment]
I have mentioned this in the docs now, all new installed dependency modules will also use the same plugins as the explicitly installed module.
