### ISSUE TITLE
Sysrepocfg enters an unusable state after importing a NACM rule with a list predicate in its path.

### ISSUE THREAD

**Issue by nullromo** [sysrepo/sysrepo#2686]
## Summary

I tried to import some rules into the NACM using `sysrepocfg`, and now I can no longer export the NACM using sysrepocfg. Instead, I get the following error message:

```
[ERR] PLG: LYB DS file: Invalid LYB unsigned integer value size 1 (expected 2).
[ERR] PLG: LYB DS file: Invalid instance-identifier "/test:test-list[id='1']" value - semantic error.
```

## Steps to reproduce

0. Update libyang, sysrepo, libnetconf, and netopeer2 to all the latest versions on all master branches.
1. Install **`test.yang`** (see below) using `sysrepoctl --install=test.yang`.
1. Import **`initial-test.xml`** (see below) using `sysrepocfg --import=initial-test.xml --module test`
1. Verify that `sysrepocfg --export --module test` and `sysrepocfg --export --module ietf-netconf-acm` both work properly.
1. Import **`test-nacm.xml`** (see below) into the NACM using `sysrepocfg --import=test-nacm.xml --module ietf-netconf-acm`.
1. Try to run `sysrepocfg --export --module ietf-netconf-acm` and get the error message.

### `test.yang`
```yang
module test {
    yang-version 1.1;
    namespace 'urn:test';
    prefix test;
    organization '';
    contact '';
    description '';
    revision 2022-01-04 {
        description 'Test revision';
    }

    list test-list {
        key id;
        leaf id {
            type uint16;
        }
        leaf name {
            type string;
        }
    }
}
```

### `initial-test.xml`
```xml
<test-list xmlns="urn:test">
    <id>1</id>
    <name>kyle</name>
</test-list>
```
 
### `test-nacm.xml`
```xml
<?xml version="1.0"?>
<nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
  <enable-nacm>true</enable-nacm>
  <groups>
    <group>
      <name>default</name>
    </group>
  </groups>
  <rule-list>
    <name>test-rule-list</name>
    <group>default</group>
    <rule>
      <name>test-rule</name>
      <path xmlns:n="urn:test">
          /n:test-list[n:id='1']
      </path>
      <access-operations>*</access-operations>
      <action>permit</action>
    </rule>
  </rule-list>
</nacm>
```

## More details

If I change the `<path />` element's value to `/n:test-list`, then everything works normally. If I put in an invalid path, then I get an error when trying to import the data (which is expected). However, with the path as shown in the file above, the import succeeds and then I am in an irreversible problematic state where I can no longer use sysrepocfg. The only way I know of to recover from this state is rebooting.

From what I can tell, the NACM data I have provided should be valid, so I'm not sure what it is that is causing the issue.

## Expected behavior

If invalid data is being imported, sysrepocfg should not let me import it. If valid data is imported, sysrepocfg should not leave the datastore in an unusable state. If the datastore is in a usable state, then sysrepocfg should export the data without issue.

## Full error output

```
$ sysrepocfg --export --module ietf-netconf-acm -v3
[INF] Applying scheduled changes.
[INF] No scheduled changes.
[INF] Connection 5 created.
[INF] Session 5 (user "kkovacs", CID 5) created.
[ERR] PLG: LYB DS file: Invalid LYB unsigned integer value size 1 (expected 2).
[ERR] PLG: LYB DS file: Invalid instance-identifier "/test:test-list[id='1']" value - semantic error.
[ERR] Callback "load" of plugin "LYB DS file" for module "ietf-netconf-acm" failed.
sysrepocfg error: Getting data failed (libyang error)
[INF] No datastore changes to apply.
```

**Comment by michalvasko** [comment]
Right, thanks for the nice report (although only the steps to reproduce were really needed) and if you use latest *libyang* (`devel`), it should work (problem only in the parsing, so the last step should simply work now).

**Comment by nullromo** [comment]
I verified that it works on my system on libyang/devel. Thanks 🎉
