### ISSUE TITLE
Macro SRPLG_DATASTORE will not work with  g++ compiler

### ISSUE THREAD

**Issue by berstrob** [sysrepo/sysrepo#2687]
Hi,
while testing if i could use c++ for the Custom datastore lib (some parts of my backend is in c++)  ,  i encounter a problem with this macro the `srpds__ ` was still mangled and so not usable .

It does seem to be caused by the `const` implying internal linkage , so either removing  `struct srplg_ds_s srpds__ {`  or adding extern  ` extern const struct srplg_ds_s srpds__ {` does do the trick, both seem to work fine with my limited test.

Regards Bernd

**Comment by michalvasko** [comment]
Fine, no problem.
