### ISSUE TITLE
How to install newer version of a yang file

### ISSUE THREAD

**Issue by meghna-doshi** [sysrepo/sysrepo#2689]
Hi,
We have a yang sample.yang
revision 2021-02-08

which we updated by adding some leafs so we added new revision to the file

revision 2022-01-01

1. We have a system already running with revision 2021 installed.
2. Now when we upgrade the build, the new revision 2022 is not getting installed, mostly since 2021 is already installed.
we use sysrepoctl -I sample.yang in our scripts to install any yang.

So what command we should use if we want sysrepo to take the new version of yang and overwrite the existing yang installation with new one?

Version:
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.147 (SO v5.6.63)

**Comment by michalvasko** [comment]
Look at `sysrepoctl` `-U` parameter.

**Comment by hi-Mr-ye** [comment]
>
> Look at `sysrepoctl` `-U` parameter.
I have a question. When the sysRepoctl -I /u/ u operation is executed, Whether to kill Netopeer2-serve  ?

**Comment by michalvasko** [comment]
Until you restart *netopeer2-server*, the update will not take place and remain only scheduled. You can check the current state with `sysrepoctl -l`. This limitation was lifted in *sysrepo* v2.1 (currently in `devel` branch) where the module update would be performed immediately even with *netopeer2-server* running.
