### ISSUE TITLE
Deleting node from input xml (from netopeer2-cli ) does not satisfing oper == SR_OP_DELETED

### ISSUE THREAD

**Issue by bkumarrr** [sysrepo/sysrepo#2691]
Hi 
i have one application that subscribed to o-ran-operations.yang model using 
` sr_module_change_subscribe(session, "o-ran-operations", NULL,module_change_cb, NULL, 0, 0, &subscription);`

 and Inside module_change_cb function i have handled deleted node using condition like oper == SR_OP_DELETED but even after deleting node from input xml this condition is not satisfying.below is my xml
 
**Initial xml triggered from netopeer2-cli**
 ```
<operational-info xmlns="urn:o-ran:operations:1.0">
    <clock>
        <timezone-name>Madrid/Spain</timezone-name>
        <timezone-utc-offset>+0100</timezone-utc-offset>
    </clock>
    <re-call-home-no-ssh-timer>60</re-call-home-no-ssh-timer>
</operational-info>
```

**xml after deleting one node** 
```
<operational-info xmlns="urn:o-ran:operations:1.0">
    <clock>
        <timezone-name>Madrid/Spain</timezone-name>
    </clock>
    <re-call-home-no-ssh-timer>60</re-call-home-no-ssh-timer>
</operational-info>
```

please give your valuable update

**Comment by michalvasko** [comment]
Hard to guess what exactly is happening based on this information but `operational-info` sounds like some state (`config` `false`) subtree. In case it is , you cannot edit it this way directly, you can do so only for configuration data.

**Comment by bkumarrr** [comment]
I am using o-ran-operations.yang module,in which some read-write parameters are there like `timezone-name,re-call-home-no-ssh-timer and timezone-utc-offset` etc and these parameter are part of container named `operational-info` which is read/write .

i have one application that subscribed to o-ran-operations.yang model using
`sr_module_change_subscribe(session, "o-ran-operations", NULL,module_change_cb, NULL, 0, 0, &subscription);`

Callback is triggering when some of parameters values get updated from netopeer2-cli but one issue i am facing when handling delete operation 
I have written logic for handling deleted node using `oper == SR_OP_DELETED` inside callback function .but after deleting node from netopeer2-cli callback not going inside `oper == SR_OP_DELETED `

But when i am restarting this application condition `oper == SR_OP_DELETED` is getting true.

**Comment by michalvasko** [comment]
Okay, if the nodes are configuration, then it should be fine. But it seems you are not aware of how exactly [edit-config](https://datatracker.ietf.org/doc/html/rfc6241#section-7.2) works. The data you put into `config` do not automatically replace the previous data, the `default-operation` is `merge`. So to delete a node, either change the default operation to `replace` or change the operation of that single node to `delete`. Details can be found in the RFC.

**Comment by bkumarrr** [comment]
Right @michalvasko below command will be used for that
`edit-config --target running --defop replace --config`
Thanks for help !!
