### ISSUE TITLE
config change callback did not trigger

### ISSUE THREAD

**Issue by lqlucky** [sysrepo/sysrepo#2692]
Hi,

There is a question about that : 
I use `sr_module_change_subscribe` subsribed the `/_3gpp-common-managed-element:ManagedElement/id` and `/_3gpp-common-managed-element:ManagedElement/_3gpp-nr-nrm-gnbcucpfunction:GNBCUCPFunction/id`, when use command `copy-config --target running --src-config=/root/me_config.xml --rpc-timeout 30` to replace the ManagedElement id and GNBCUCPFunction id but only the callback of ManagedElement id triggered. Is this normal behavior?

**Comment by michalvasko** [comment]
It depends on what was in the `running` datastore before and what is in `me_config.xml`, your callback will be called only if there are any configuration **changes**.

**Comment by lqlucky** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by lqlucky** [comment]
The scenario as follow:
I use command "sysrepocfg -d running -m _3gpp-common-managed-element --export=/root/me_config.xml" export the config data then edit the value of  ManagedElement/id and GNBCUCPFunction/id. Finally, replace running database with the above command. So I'm sure the configuration has changed

**Comment by michalvasko** [comment]
Try to perform the export again and check that the changes you made were applied. If they were, I am pretty sure the callback would be called.

**Comment by lqlucky** [comment]
I did it all as your said, the changes were applied but callback still not trigger.
The detailed steps as follow:
1. sysrepocfg -d running -m _3gpp-common-managed-element --export=./me_config.xml
2. vi me_config.xml
3. modify the ManagedElement/id and and GNBCUCPFunction/id and save
4. copy-config --target running --src-config=/root/me_config.xml --rpc-timeout 30
5. check log only "/_3gpp-common-managed-element:ManagedElement/id" callback called
6. sysrepocfg -d running -m _3gpp-common-managed-element -X to check changes were applied

Note:
All callbacks would be called when connected to sysrepo first time
sysrepo version: libsysrepo v2.0.34 (SO v6.4.1)

**Comment by michalvasko** [comment]
Well, it seems you will have to provide **all** the YANG modules (with imports and everything), attach the initial exported `me_config.xml`, mention what exactly are you changing in step 3. and I will try it myself.
