### ISSUE TITLE
kill-session --sid seeion-id

### ISSUE THREAD

**Issue by hi-Mr-ye** [sysrepo/sysrepo#2694]
Hi @michalvasko ,
How do I know the session ID of the server connection when netopeer2-server -d& is executed.
and session-id are between netopeer2 and sysrepo, or between netopeer2 and the NETCONF client.

**Comment by michalvasko** [comment]
Firstly, `<kill-session>` is a NETCONF RPC so the SID is of the NETCONF session (between NETCONF server - *netopeer2-server* and NETCONF client). When you create a new session, it gets its SID assigned and in *netopeer2-cli* you can see it in the output of `status` command. Also, it is printed by the server if you use `-v3` when starting it. Finally, you can see all the sessions and their SIDs in the `ietf-netconf-monitoring` state data, which can be retrieved from the server.

**Comment by hi-Mr-ye** [comment]
thanks! I disconnect the session connection , and netopeer2-cli printf:
![image](https://user-images.githubusercontent.com/90752673/149902463-97760be5-eb86-4d6f-a09a-ebfcd4ac1912.png)
![image](https://user-images.githubusercontent.com/90752673/149902530-63a08a14-4d89-4bb7-b2f8-be43af873045.png)
![image](https://user-images.githubusercontent.com/90752673/149902602-921c0e02-1826-4583-9fba-f118b761c993.png)
What is the difference between these abortion-reasons? and Which abortion-reasons is safer?

**Comment by michalvasko** [comment]
Look at the [YANG module](https://github.com/sysrepo/sysrepo/blob/master/modules/ietf-netconf-notifications.yang#L197) where these values are defined to understand them. From those descriptions it should be obvious that `closed` is the termination reason of a session that properly terminated on its own by sending `<close-session>`.
