### ISSUE TITLE
sr_lock in latest sysrepo

### ISSUE THREAD

**Issue by meghna-doshi** [sysrepo/sysrepo#2697]
Hi,
We upgraded to sysrepo version as below:
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v2.1.15 (SO v7.1.3)

We see that there is extra argument sr_lock API i.e timeout. So the understanding is that for how much sysrepo to wait for lock before returning failure (in case lock is already acquired by some other thread)

But in file src/sysrepo.c we see the following code i.e lock API is calling unlock. Is this some bug? Can you please check.

```
API int
sr_lock(sr_session_ctx_t *session, const char *module_name, uint32_t timeout_ms)
{
    return _sr_un_lock(session, module_name, 1, timeout_ms);
}
```

**Comment by irfanHaslanded** [comment]
> return _sr_un_lock(session, module_name, 1, timeout_ms);

/**
 * @brief (Un)lock a specific or all modules datastore locks.
 *
 * @param[in] session Session to use.
 * @param[in] module_name Optional specific module.
 * @param[in] lock Whether to lock or unlock.
 * @param[in] timeout_ms Timeout for waiting to get DS lock, only if @p lock is set.
 * @return err_code (SR_ERR_OK on success).
 */
static int
_sr_un_lock(sr_session_ctx_t *session, const char *module_name, int lock, uint32_t timeout_ms)

**Comment by meghna-doshi** [comment]
Ok got it "int lock" parameter in _sr_un_lock decides whether it is called for lock or unlock. Ok thanks.
