### ISSUE TITLE
Yang installation failure with validation failed error

### ISSUE THREAD

**Issue by VarshithaKumarGowda** [sysrepo/sysrepo#2699]
Hi, 
 
Yang installation is failing while trying to install the yang "custom_3gpp-nr-nrm-nrcelldu.yang" using the below command. 
`sysrepoctl -i custom_3gpp-nr-nrm-nrcelldu.yang -s . -v4`

It is giving the below error
```
sysrepoctl|ERROR "SR stderr" Too few "ManagedElement" instances.
sysrepoctl error: Failed to install module "/usr/local/cuduyang/custom_3gpp-nr-nrm-nrcelldu.yang" (Validation failed)
sysrepoctl|INFO "SR stderr" No datastore changes to apply.

```
Also observed that this error is not found and installation works if the "min-elements" is commented from the file contents: 
```
deviation "/me3gpp:ManagedElement" {
        deviate add {
            min-elements 1;
            max-elements 1;
        }
    }
```

This functionality works fine without commenting min-elements on the libsysrepo v2.0.38 (SO v6.4.5) and is currently not working on the **"libsysrepo v2.1.15 (SO v7.1.3)"** 

PFA:
yangs and all the files mentioned above.

[installyangs.zip](https://github.com/sysrepo/sysrepo/files/7902936/installyangs.zip)

**Comment by michalvasko** [comment]
[This](https://github.com/sysrepo/sysrepo/blob/devel/src/executables/sysrepoctl.c#L112) option may be handy. And it most likely worked in v2.0.38 because of a bug in the previous libyang version when the deviation was not correctly applied.

**Comment by meghna-doshi** [comment]
Hi Michal,
Yes "-I" option worked :
sysrepoctl -i <yang name> -I /tmp/start.xml -s <dir name>

One query, so when we install yang as above, will the data input via start.xml get entered into startup datastore and then into running?

**Comment by michalvasko** [comment]
Well, to both `startup` and `running`, just as the module is installed.
