### ISSUE TITLE
The running segment of netopeer2-server is incorrect

### ISSUE THREAD

**Issue by hi-Mr-ye** [sysrepo/sysrepo#2700]
Hi @michalvasko ,
When I run netopeer2-server-v3-d, a segment error occurs.
rm -rf /dev/shm/* and netopeer2-server-v3 -d runs fine
The log shows:

 netopeer2-server -v3 -d
[INF]: LY: Searching for "ietf-yang-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-yang-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-datastores" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-datastores@2018-02-14.yang" file.
[INF]: LY: Searching for "ietf-yang-library" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-yang-library@2019-01-04.yang" file.
[INF]: LY: Searching for "ietf-yang-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-inet-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-inet-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "sysrepo-monitoring" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/sysrepo-monitoring@2021-07-29.yang" file.
[INF]: LY: Searching for "ietf-yang-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Implemented module "ietf-datastores@2018-02-14" is not used for import, revision "2018-02-14" is imported instead.
[INF]: LY: Searching for "sysrepo-plugind" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/sysrepo-plugind@2020-12-10.yang" file.
[INF]: LY: Searching for "ietf-netconf" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-netconf@2013-09-29.yang" file.
[INF]: LY: Searching for "ietf-inet-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-inet-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-netconf-acm" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-netconf-acm@2018-02-14.yang" file.
[INF]: LY: Searching for "ietf-yang-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-yang-metadata" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-yang-metadata@2016-08-05" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-yang-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-netconf-with-defaults" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-netconf-with-defaults@2011-06-01.yang" file.
[INF]: LY: Searching for "ietf-yang-metadata" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-yang-metadata@2016-08-05" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-netconf-notifications" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-netconf-notifications@2012-02-06.yang" file.
[INF]: LY: Searching for "ietf-inet-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-inet-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Implemented module "ietf-netconf@2013-09-29" is not used for import, revision "2013-09-29" is imported instead.
[INF]: LY: Searching for "ietf-origin" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-origin@2018-02-14.yang" file.
[INF]: LY: Searching for "ietf-yang-metadata" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-yang-metadata@2016-08-05" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-netconf-monitoring" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-netconf-monitoring@2010-10-04.yang" file.
[INF]: LY: Searching for "ietf-yang-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-inet-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-inet-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-netconf-nmda" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-netconf-nmda@2019-01-07.yang" file.
[INF]: LY: Searching for "ietf-yang-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-inet-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-inet-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Implemented module "ietf-datastores@2018-02-14" is not used for import, revision "2018-02-14" is imported instead.
[INF]: LY: Implemented module "ietf-netconf@2013-09-29" is not used for import, revision "2013-09-29" is imported instead.
[INF]: LY: Searching for "nc-notifications" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/nc-notifications@2008-07-14.yang" file.
[INF]: LY: Searching for "ietf-yang-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "notifications" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/notifications@2008-07-14.yang" file.
[INF]: LY: Searching for "ietf-yang-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-x509-cert-to-name" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-x509-cert-to-name@2014-12-10.yang" file.
[INF]: LY: Searching for "ietf-yang-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-crypto-types" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-crypto-types@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-yang-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Implemented module "ietf-netconf-acm@2018-02-14" is not used for import, revision "2018-02-14" is imported instead.
[INF]: LY: Searching for "ietf-keystore" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-keystore@2019-07-02.yang" file.
[INF]: LY: Implemented module "ietf-netconf-acm@2018-02-14" is not used for import, revision "2018-02-14" is imported instead.
[INF]: LY: Searching for "ietf-truststore" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-truststore@2019-07-02.yang" file.
[INF]: LY: Implemented module "ietf-netconf-acm@2018-02-14" is not used for import, revision "2018-02-14" is imported instead.
[INF]: LY: Implemented module "ietf-crypto-types@2019-07-02" is not used for import, revision "2019-07-02" is imported instead.
[INF]: LY: Searching for "ietf-tcp-common" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-tcp-common@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-ssh-server" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-ssh-server@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-ssh-common" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-ssh-common@2019-07-02.yang" file.
[INF]: LY: Searching for "iana-crypt-hash" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/iana-crypt-hash@2014-08-06.yang" file.
[INF]: LY: Implemented module "ietf-netconf-acm@2018-02-14" is not used for import, revision "2018-02-14" is imported instead.
[INF]: LY: Searching for "ietf-tls-server" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-tls-server@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-tls-common" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-tls-common@2019-07-02.yang" file.
[INF]: LY: Implemented module "ietf-keystore@2019-07-02" is not used for import, revision "2019-07-02" is imported instead.
[INF]: LY: Implemented module "ietf-netconf-acm@2018-02-14" is not used for import, revision "2018-02-14" is imported instead.
[INF]: LY: Searching for "ietf-netconf-server" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-netconf-server@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-yang-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-tcp-client" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-tcp-client@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-inet-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-inet-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-tcp-server" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-tcp-server@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-inet-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-inet-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Implemented module "ietf-tcp-common@2019-07-02" is not used for import, revision "2019-07-02" is imported instead.
[INF]: LY: Searching for "ietf-interfaces" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-interfaces@2018-02-20.yang" file.
[INF]: LY: Searching for "ietf-yang-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-ip" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-ip@2018-02-22.yang" file.
[INF]: LY: Searching for "ietf-inet-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-inet-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-yang-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-network-instance" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-network-instance@2019-01-21.yang" file.
[INF]: LY: Implemented module "ietf-interfaces@2018-02-20" is not used for import, revision "2018-02-20" is imported instead.
[INF]: LY: Searching for "ietf-yang-schema-mount" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-yang-schema-mount@2019-01-14.yang" file.
[INF]: LY: Searching for "ietf-inet-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-inet-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-yang-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-subscribed-notifications" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-subscribed-notifications@2019-09-09.yang" file.
[INF]: LY: Searching for "ietf-inet-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-inet-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Implemented module "ietf-interfaces@2018-02-20" is not used for import, revision "2018-02-20" is imported instead.
[INF]: LY: Implemented module "ietf-netconf-acm@2018-02-14" is not used for import, revision "2018-02-14" is imported instead.
[INF]: LY: Searching for "ietf-restconf" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-restconf@2017-01-26.yang" file.
[INF]: LY: Searching for "ietf-yang-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-yang-push" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-yang-push@2019-09-09.yang" file.
[INF]: LY: Searching for "ietf-yang-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Implemented module "ietf-datastores@2018-02-14" is not used for import, revision "2018-02-14" is imported instead.
[INF]: LY: Searching for "ietf-restconf" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-restconf@2017-01-26.yang" file.
[INF]: LY: Newer revision than "ietf-restconf@2017-01-26" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-yang-patch" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-yang-patch@2017-02-22.yang" file.
[INF]: LY: Searching for "ietf-restconf" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-restconf@2017-01-26.yang" file.
[INF]: LY: Newer revision than "ietf-restconf@2017-01-26" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-otn-types" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/ietf-otn-types@2019-01-15.yang" file.
[INF]: LY: Searching for "wdm-yang-types" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/wdm-yang-types@2019-02-13.yang" file.
[INF]: LY: Searching for "wdm-alarms" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/wdm-alarms@2019-02-13.yang" file.
[INF]: LY: Searching for "ietf-yang-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "wdm-devm" in "/etc/sysrepo/yang".
[INF]: LY: Loading schema from "/etc/sysrepo/yang/wdm-devm@2019-02-13.yang" file.
[INF]: LY: Searching for "ietf-yang-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Implemented module "wdm-yang-types@2019-02-13" is not used for import, revision "2019-02-13" is imported instead.
[INF]: LY: Searching for "ietf-inet-types" in "/etc/sysrepo/yang".
[INF]: LY: Newer revision than "ietf-inet-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Use of anydata to define configuration data is not recommended. /ietf-yang-push:{augment='/sn:filters'}/ietf-yang-push:selection-filter/{uses='selection-filter-types'}/filter-spec/datastore-subtree-filter/datastore-subtree-filter
[INF]: LY: Use of anydata to define configuration data is not recommended. /ietf-subscribed-notifications:filters/stream-filter/{uses='stream-filter-elements'}/filter-spec/stream-subtree-filter/stream-subtree-filter
[INF]: LY: Use of anydata to define configuration data is not recommended. /ietf-yang-push:{augment='/sn:subscriptions/sn:subscription/sn:target'}/ietf-yang-push:datastore/{uses='datastore-criteria'}/{uses='selection-filter-objects'}/selection-filter/within-subscription/{uses='selection-filter-types'}/filter-spec/datastore-subtree-filter/datastore-subtree-filter
[INF]: LY: Use of anydata to define configuration data is not recommended. /ietf-subscribed-notifications:subscriptions/subscription/{uses='subscription-policy'}/{uses='subscription-policy-dynamic'}/{uses='subscription-policy-modifiable'}/target/stream/stream-filter/within-subscription/{uses='stream-filter-elements'}/filter-spec/stream-subtree-filter/stream-subtree-filter
[INF]: LY: Missing explicit "deprecated" status specified in parent "subnet", inheriting for "prefix-length".
[INF]: LY: Missing explicit "deprecated" status specified in parent "subnet", inheriting for "netmask".
[INF]: LY: The ordered-by statement is ignored in lists representing notification content (/ietf-yang-push:push-change-update/datastore-changes/{uses='ypatch:yang-patch'}/yang-patch/edit).
[INF]: SR: Connection 11 created.
[INF]: SR: Session 331 (user "administrator", CID 11) created.
[WRN]: SR: Connection with CID 10 is dead.
[WRN]: SR: Recovered a write-lock of CID 10 (sr_shmext_rpc_sub_add).
[WRN]: SR: Recovered a lock with a dead owner (sr_shmext_rpc_sub_add).
[WRN]: SR: Recovering RPC/action "/ietf-netconf:get-config" subscription of CID 7.
Segmentation fault
#

**Comment by michalvasko** [comment]
Try to run *netopeer2-server* with `valgrind` or `gdb`, they may provide more information allowing me to fix it. But you are using *sysrepo* v1 so unless you can provide more information, I will not bother wasting time.

**Comment by hi-Mr-ye** [comment]
Am I using sysrepo V1? How do I query this? I thought I was using sysrepo V2

**Comment by michalvasko** [comment]
Uh, sorry, you should be using some *sysrepo* v2, I confused your issue with another one. You can see the exact version when you run `sysrepoctl -V`, for example. But what I wrote is mostly true, I cannot help based on only the provided information.
