### ISSUE TITLE
Mutex lock failure on get

### ISSUE THREAD

**Issue by meghna-doshi** [sysrepo/sysrepo#2701]
Hi,
We are getting following failure on get call:

```
<?xml version="1.0" encoding="UTF-8"?><rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1642762801860">
   <get>
      <filter type="subtree">
         <ManagedElement xmlns="urn:3gpp:sa5:_3gpp-common-managed-element">
            <id>1</id>
            <attributes>
               <X0005B9_LastBootTime xmlns="urn:commscope:commscope_3gpp-nr-nrm-nrcelldu"/>
               <dnPrefix/>
               <swVersion/>
               <userDefinedState/>
            </attributes>
         </ManagedElement>
      </filter>
   </get>
</rpc>




<?xml version="1.0" encoding="UTF-8"?><rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1642762801860">
   <rpc-error>
      <error-type>application</error-type>
      <error-tag>operation-failed</error-tag>
      <error-severity>error</error-severity>
      <error-message xml:lang="en">Locking a mutex failed (sr_shmsub_notify_new_wrlock: Connection timed out).</error-message>
   </rpc-error>
</rpc-reply>
```

sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.147 (SO v5.6.63)

Not having much information on what caused this problem. Can you help if you know any reason why would sysrepo mutex lock fail?

**Comment by meghna-doshi** [comment]
Hi Michal,
Ok may be moving to latest libyang1 would help but do you know any use case when this can happen. We dont know exactly how system went in this state, so even after upgrading to latest libyang1, how would we verify if the issue is fixed indeed.

**Comment by michalvasko** [comment]
Look at the output of `netopeer2-server -d -v2`, it should print exactly what is happening, it is impossible to determine the scenario without that.
