### ISSUE TITLE
Internal error during operational datastore update

### ISSUE THREAD

**Issue by meghna-doshi** [sysrepo/sysrepo#2707]
Hi, 
We are getting following internal error while doing operational datastore update from the application:

`ERROR ""SR Syslog"" Internal error (/workspace/agent/PRG-Builds/OTA/6.0.1.150/ran_3rdparty/open_source/netconf/sysrepo/src/edit_diff.c:2776).`

Any information, what does this error mean. The same operational datastore update worked earlier but now getting error.
Dont have much information as of now to share, about use case or when does this happen.

sysrepo version : 1.4.144

**Comment by michalvasko** [comment]
It is possible this is fixed in the latest `devel` branch but hard to say without having the exact use-case.

**Comment by meghna-doshi** [comment]
Hi,
You mean it might be fixed in latest libyang1 since this is sysrepo 1.x version code.

**Comment by michalvasko** [comment]
> You mean it might be fixed in latest libyang1 branch since this is sysrepo 1.x version code.

No, I mean in the latest `devel`. I know it is v1 code but it is deprecated and I do not think there were any relevant fixes in the `libyang1` branch. You will keep hitting these problem unless and until you decide to migrate to v2.

> Also what is this error? What does it indicate?

Somehow, non-existing node is supposed to be deleted, that is all I can say based on the error.
