### ISSUE TITLE
Use of sample application to send notification notif_send_example

### ISSUE THREAD

**Issue by meghna-doshi** [sysrepo/sysrepo#2709]
Hi,
Trying to use the sample notif_send_example binary to send notification.
Run it like this:

`notif_send_example  /o-ran-agg-sync:ru-sync-notify /o-ran-agg-sync:ru-sync-notify/ru-sync-notification[ru-instance='ruid1']/synchronization-state-change/sync-change FREERUN
`
But i am getting error:

```
Application will send notification "/o-ran-agg-sync:ru-sync-notify".

Creating value "/o-ran-agg-sync:ru-sync-notify/ru-sync-notification[ru-instance=ruid1]/synchronization-state-change/sync-change" failed.
```

Any idea what is wrong in the input given.
Attaching only the yang which has this notification.
sysrepoctl --version
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.147 (SO v5.6.63)

[o-ran-agg-sync.zip](https://github.com/sysrepo/sysrepo/files/7981716/o-ran-agg-sync.zip)

**Comment by meghna-doshi** [comment]
Any help with this please?

**Comment by michalvasko** [comment]
Look at the output, your problem is actually the main reason it was added
```
Creating value "/o-ran-agg-sync:ru-sync-notify/ru-sync-notification[ru-instance=ruid1]/synchronization-state-change/sync-change" failed.
```
The predicate is wrong, the value is missing `'`. fix by instead executing
```
notif_send_example "/o-ran-agg-sync:ru-sync-notify /o-ran-agg-sync:ru-sync-notify/ru-sync-notification[ru-instance='ruid1']/synchronization-state-change/sync-change" FREERUN 
```

**Comment by meghna-doshi** [comment]
Oh yes right, i missed giving input with " ". Thanks a lot.
