### ISSUE TITLE
Error returned from sr_get_items when filtering on a specific leaf-list value

### ISSUE THREAD

**Issue by matth65** [sysrepo/sysrepo#2710]
Hello,

I'm having an issue with using sr_get_items and filtering on a specific leaf-list value. Please see below the nacm example below. 

I'm using the sr_get_items_example provided with sysrepo along with the ietf-netconf-acm YANG model to reproduce the issue.
Note: I'm using following version from the libyang1 branch: libyang-1.0.249, sysrepo-1.4.149 

The following request is successful and returns all users in a nacm group.
```
$ ./sr_get_items_example "/ietf-netconf-acm:nacm/groups/group/user-name" running
Application will get "/ietf-netconf-acm:nacm/groups/group/user-name" from "running" datastore.

/ietf-netconf-acm:nacm/groups/group[name='admin']/user-name[.='my_user'] = my_user
```

The following request filtering on a specific user fails with an 'Invalid path' error.
```
$ ./sr_get_items_example "/ietf-netconf-acm:nacm/groups/group/user-name[.='my_user']" running
Application will get "/ietf-netconf-acm:nacm/groups/group/user-name[.='my_user']" from "running" datastore.

[ERR]: Invalid path used ((null) in a subexpression).
```

Are you able to reproduce this issue?

Regards,
Matt

**Comment by michalvasko** [comment]
Seems this was simply not supported but it is now because it was quite simple to improve. However, you are likely to encounter more similar problems so it is best to switch to v2 if at all possible.

**Comment by irfanHaslanded** [comment]
Is there a v2 migration guide :). I would like to scope the effort needed

**Comment by michalvasko** [comment]
Sadly, [there](https://github.com/sysrepo/sysrepo/tree/devel/compatibility) is not, the only one that is missing :) If interested, I suppose I can write some just like I did for SO v6 to v7.

**Comment by matth65** [comment]
I would very much like to upgrade to V2, but I'm currently using the Python API. Unfortunately, the Python API does not support V2 yet.

**Comment by matth65** [comment]
This issue was a bit strange to me, because performing the query actually worked via Netopeer2. From the code it looks like Netopeer2 doesn't necessarily apply the filter to the sr_get_data() call directly. Instead, it looks like it collects data at a module level (maybe more than it needs) and then filters after sr_get_data() is called.

```
<?xml version="1.0" encoding="utf-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="12">
  <get>
    <filter xmlns:nacm="urn:ietf:params:xml:ns:yang:ietf-netconf-acm" type="xpath"
            select="/nacm:nacm/groups/group/user-name[.='my_user']"/>
  </get>
</rpc>

<?xml version="1.0" encoding="utf-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="12">
  <data>
    <nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
      <groups>
        <group>
          <name>admin</name>
          <user-name>my_user</user-name>
        </group>
      </groups>
    </nacm>
  </data>
</rpc-reply>
```

Also just FYI, I'm pretty sure this worked with older versions of sysrepo/libyang1 because this was existing code started to fail after upgrading to the latest libyang1. Previously, I was using sysrepo-1.4.122 and libyang-1.0.225. I did try diff'ing that area of the code and I didn't see any major differences in that section of the code.

**Comment by michalvasko** [comment]
> I'm pretty sure this worked with older versions of sysrepo/libyang1

Possible, but it seems there was another problem that required to use a function that could not handle the XPath you were using.

**Comment by matth65** [comment]
I've verified that this patch resolves the issue. Thank you very much.
