### ISSUE TITLE
Failure in set_item_str during operational datastore update

### ISSUE THREAD

**Issue by meghna-doshi** [sysrepo/sysrepo#2711]
Hi,
We are seeing following logs when set_item_str is called with following arguments : 
```
/_3gpp-common-managed-element:ManagedElement[id='1']/_3gpp-nr-nrm-gnbdufunction:GNBDUFunction[id='1']/_3gpp-nr-nrm-ep:EP_F1C[id='1']/attributes/localAddress[ipAddress='2001:4000:aa:52::b'][vlanId='9999']/ipAddress
0.0.0.0
```

Error in logs:
```
ERROR ""SR Syslog"" Node already exists."
ERROR ""SR Syslog"" Invalid datastore edit."
```

Normally we observe that if we try to do operational datastore update with same values, we get something like "No datastore changes to apply" logs. Not sure why here there is failure.

Sysrepo version: 1.4.144

**Comment by meghna-doshi** [comment]
Hi,
On checking closely, we realized that the value of "ipAddress" in xpath is 2001:4000:aa:52::b but the leaf value is 0.0.0.0
Is this creating issue?

**Comment by jktjkt** [comment]
What are you trying to achieve by setting a list's key to a different value?

**Comment by meghna-doshi** [comment]
Hi @jktjkt ,
Actually setting list key to different value was not intentional.
Looks there is some bug in our code due to which this discrepancy happened.
So i am assuming that due to this, we saw the above error.

**Comment by michalvasko** [comment]
Yes, the key is attempted to be created a second time.
