### ISSUE TITLE
replace operation not working for leaf-list yang model

### ISSUE THREAD

**Issue by mbelgaum** [sysrepo/sysrepo#2714]
Hi
I have a leaf-list 'requestor-id' yang model as below
```yang
    grouping trace-config {
        leaf level {
            type trace-level-type;
            description
                "trace level config";
        }
        leaf-list requestor-id {
            type uint32;
            max-elements 3;                       
            description
                "The requestor identifier for tracing";
        }
        description
            "trace level configuration";
    }
```

After adding 3 values to 'requestor-id' , I want to replace one of the values with never value.
( I have values 111, 222, 333 stored in requestor-id list)

I m using below netconf command for replacing one of the values.
I want to replace 333 with 444.

```xml
<edit-config>
  <target>
    <running/>
  </target>
  <config>
    <ric xmlns="urn:pw:ric:pw-ho-config:1.0">
      <config>        
          <trace>
             <requestor-id operation="replace" value="333">444
            </requestor-id>
          </trace>        
      </config>
    </ric>
  </config>
</edit-config>
```
The replace operation seems to be failing with message 'Too many "requestor-id" instances"

Please guide if this is an issue or my netconf command is wrong.

**Comment by michalvasko** [comment]
What you have tried is not possible, [here](https://datatracker.ietf.org/doc/html/rfc7950#section-7.7.9) are the specs defining what you can do with a leaf-list. To "replace" it, you must delete and create it.

**Comment by mbelgaum** [comment]
Thanks for the response, but delete operation is leading to segmentation fault in netopeer2/sysrepo.

I tried with below delete commands

<edit-config>
  <target>
    <running/>
  </target>
  <config>
    <ric xmlns="urn:pw:ric:pw-ho-config:1.0">
      <config>        
          <trace>            
            **<requestor-id operation="delete" value="333"/>**
          </trace>     
      </config>
    </ric>
  </config>
</edit-config>


<edit-config>
  <target>
    <running/>
  </target>
  <config>
    <ric xmlns="urn:pw:ric:pw-ho-config:1.0">
      <config>        
          <trace>            
            **<requestor-id operation="delete" />**
          </trace>     
      </config>
    </ric>
  </config>
</edit-config>


Crash logs:
{"log":"2022-02-02 15:25:05,217 DEBG fd 10 closed, stopped monitoring \u003cPOutputDispatcher at 139688401004496 for \u003cSubprocess at 139688403446672 with name netopeer2-server in state RUNNING\u003e (stdout)\u003e\n","stream":"stdout","time":"2022-02-02T15:25:05.217764356Z"}
{"log":"2022-02-02 15:25:05,221 INFO exited: netopeer2-server (terminated by SIGSEGV (core dumped); not expected)\n","stream":"stdout","time":"2022-02-02T15:25:05.222195356Z"}
{"log":"2022-02-02 15:25:05,221 DEBG received SIGCLD indicating a child quit\n","stream":"stdout","time":"2022-02-02T15:25:05.224151799Z"}
{"log":"2022-02-02 15:25:06,227 DEBG event 15 sent to listener process-state\n","stream":"stdout","time":"2022-02-02T15:25:06.237704801Z"}
{"log":"2022-02-02 15:25:06,229 INFO spawned: 'netopeer2-server' with pid 90\n","stream":"stdout","time":"2022-02-02T15:25:06.237743262Z"}

**Comment by michalvasko** [comment]
You have not mentioned what versions are you using but it is not crashing on the most recent one. In any case, all the metadata need their namespace and operation is in the default one. Also, `value` has meaning only for user-ordered lists, which is written in the specs I have referenced. So the XML you want to use is
```xml
<edit-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <target>
    <running/>
  </target>
  <config>
    <ric xmlns="urn:pw:ric:pw-ho-config:1.0">
      <config>        
          <trace>            
            <requestor-id nc:operation="delete">333</requestor-id>
          </trace>     
      </config>
    </ric>
  </config>
</edit-config>
```

**Comment by mbelgaum** [comment]
thanks for the reply,  the above command you suggested doesn't throw any error, but the value is not deleted from db.
(get-config still returns unchanged values).

I m using below versions
sysrepoctl -  v2.0.1 (SO v6.0.1)
netopeer2-server 2.0.0
libyang.so.2.1.4

**Comment by michalvasko** [comment]
As the first thing I would definitely advise to update, the first v2 release of *sysrepo* included lots of bugs. Other than that I cannot help you because it works just fine for me. You can post your YANG module to check whether the XML you are sending is correct.

**Comment by mbelgaum** [comment]
Hi 
Upgrading would be difficult for me, please suggest correct xml for existing release, below is my yang model.
I want to delete requestor-id, or deleting whole tracing config is also fine.

Below is my yang model, please suggest xml command.

    typedef trace-level-type {
        type enumeration {
            enum not-specified {
                description
                    "None";
            }
            enum interface {
                description
                    "interface level tracing";
            }
            enum subscriber {
                description
                    "subscriber level tracing";
            }
        }
        description
            "trace level or severity Value ";
    }

    grouping trace-config {
        leaf level {
            type trace-level-type;
            description
                "trace level config";
        }
        leaf-list requestor-id {
            type uint32;
            max-element 3;
            description
                "The requestor identifier for tracing";
        }
        leaf-list subscription-id {
            type uint32;
            max-element 3;
            description
                "The subscription identifier for tracing";
        }
        description
            "trace level configuration";
    }

    container ric {
        container config {
            leaf name {
                type string;
                description
                    "The name of xApp";
            }
            leaf namespace {
                type string;
                description
                    "The namespace";
            }          
           container control {
                    leaf active {
                            type boolean;
                            description
                                    "Subscription status: active or deactive";
                    }
                    leaf version {
                            type string;
                            default "1.0.0";
                            description
                                    "The version of xApp";
                    }
                                    
                    container trace {
                            uses trace-config;
                            description
                                    "The trace config of pw ho xapp pod";
                    }                    
                    
                    description
                            "The control object";
            }

            description
                "The container for configuration data";
        }
        description
            "Root object for ric";
    }
}

**Comment by michalvasko** [comment]
I have posted the correct XML, there is no other. If it does not work, there is a problem that was later fixed, so the only possibility of fixing this problem is to update so I do not understand what exactly are you expecting of me.

**Comment by mbelgaum** [comment]
Sure, let me try with latest version.
Thanks for the support.

**Comment by michalvasko** [comment]
Okay, after another look, the XML you posted before (hence even the one I posted) is wrong but such mistakes are up to you to check. You have missed the `control` container.
```xml
<edit-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <target>
    <running/>
  </target>
  <config>
    <ric xmlns="urn:pw:ric:pw-ho-config:1.0">
      <config>        
          <control>
            <trace>           
              <requestor-id nc:operation="delete">333</requestor-id>
            </trace>
          </control>     
      </config>
    </ric>
  </config>
</edit-config>
```
