### ISSUE TITLE
query: how to set error-app-tag in action error reply?

### ISSUE THREAD

**Issue by igortern** [sysrepo/sysrepo#2718]
Hi,
Could you advise how to set an error-app-tag element in error reply returned by action handler?
Thanks,
Igor

**Comment by michalvasko** [comment]
Look into *netopeer2* [README](https://github.com/CESNET/netopeer2/#sysrepo-callbacks).

**Comment by jktjkt** [comment]
I think that you're looking for `sr_session_set_netconf_error()`. The docs for that do not appear to be online yet for some reason -- perhpas the periodic Doxygen jobs are not running?

**Comment by igortern** [comment]
I tried sr_session_set_error_message() (and README). sr_session_set_error_message() sets error-message. What I'm after is setting error-app-tag. Is there a way to set it? Apologies in advance if this info is hidden in some README somewhere and I missed it.

**Comment by jktjkt** [comment]
As I said before, look for the [`sr_session_set_netconf_error()`](https://github.com/sysrepo/sysrepo/blob/devel/src/utils/error_format.h) function which will do what you're looking for. It is not in the docs snapshot that's online, and it is also not in the `master` branch, but it's in the `devel`.

**Comment by igortern** [comment]
Ah, see it now thanks. Is there a way to set error-app-tag in released versions?
Thanks,
Igor

**Comment by michalvasko** [comment]
I was hoping the README would be enough but [here](https://github.com/CESNET/netopeer2/blob/master/src/err_netconf.c#L268) is code that sets `error-app-tag` for reference.

**Comment by igortern** [comment]
It works. Thank you
