### ISSUE TITLE
Concurrent reader limit 10 reached! error 

### ISSUE THREAD

**Issue by mrsugaranil** [sysrepo/sysrepo#2719]
Hello ,

I am getting internal error from common.c file. It says "Concurrent reader limit 10 reached!". I observed that getting this error after a few run of my application. So, my application has 1 module change and 2 RPC subcription. Does anybody knows why this error occured? I am using devel branch and I built my application on sysrepo-cpp wrapper libraries. 

Sincerely,
Anil

**Comment by michalvasko** [comment]
You should look at the whole output, you should also see what lock exactly fails to be locked. Most likely, you are not unlocking some held locks but that problem may also be in some API function, hard to say without more information.

**Comment by chunlovemail** [comment]
@mrsugaranil do U fixed the issue?  I also find the "Concurrent reader limit 10 reached!" in the sysrepo v2.1.64?

**Comment by AeroFlorian** [comment]
Hi @chunlovemail,
I had the same issue, and as written by @michalvasko I had a sr_get_subtree without sr_release_data in a loop
That resulted in the lock not being freed

Check if all your data has been released
