### ISSUE TITLE
Memory failure when importing larger file from stdin

### ISSUE THREAD

**Issue by gotthardp** [sysrepo/sysrepo#2721]
For me the following fails when the `test.xml` file is larger than 512:
```
sysrepocfg --import --format=xml --datastore running < test.xml
```
I believe `>>=` should be `<<=` in the code bellow, shouldn't it?
https://github.com/sysrepo/sysrepo/blob/b17e69266e3c10d6412b703af8e187740f3d667f/src/executables/sysrepocfg.c#L186-L189

**Comment by irfanHaslanded** [comment]
This seems applicable to libyang1 as well?

**Comment by michalvasko** [comment]
Seems so, ported over.
