### ISSUE TITLE
cross compile: undefined reference to `pcre_compile'

### ISSUE THREAD

**Issue by LoveCPro** [sysrepo/sysrepo#2722]
cross compile target：ARM:
1.cmake:
CFLAGS="-Os -pipe -mcpu=generic -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap xxx/build_dir/target-aarch64_generic_musl/sysrepo-1.4.2:sysrepo-1.4.2 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CXXFLAGS="-Os -pipe -mcpu=generic -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremapXXX/build_dir/target-aarch64_generic_musl/sysrepo-1.4.2:sysrepo-1.4.2 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " LDFLAGS="-LXXX/staging_dir/target-aarch64_generic_musl/usr/lib -LXXX/staging_dir/target-aarch64_generic_musl/lib -LXXX/staging_dir/toolchain-aarch64_generic_gcc-7.5.0_musl/usr/lib -LXXX/staging_dir/toolchain-aarch64_generic_gcc-7.5.0_musl/lib -znow -zrelro " cmake -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_VERSION=1 -DCMAKE_SYSTEM_PROCESSOR=aarch64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS_RELEASE="-DNDEBUG" -DCMAKE_CXX_FLAGS_RELEASE="-DNDEBUG" -DCMAKE_C_COMPILER="XXX/staging_dir/toolchain-aarch64_generic_gcc-7.5.0_musl/bin/aarch64-openwrt-linux-musl-gcc" -DCMAKE_C_COMPILER_ARG1="" -DCMAKE_CXX_COMPILER="XXX/staging_dir/toolchain-aarch64_generic_gcc-7.5.0_musl/bin/aarch64-openwrt-linux-musl-g++" -DCMAKE_CXX_COMPILER_ARG1="" -DCMAKE_ASM_COMPILER="XXX/staging_dir/toolchain-aarch64_generic_gcc-7.5.0_musl/bin/aarch64-openwrt-linux-musl-gcc" -DCMAKE_ASM_COMPILER_ARG1="" -DCMAKE_EXE_LINKER_FLAGS:STRING="-LXXX/staging_dir/target-aarch64_generic_musl/usr/lib -LXXX/staging_dir/target-aarch64_generic_musl/lib" -DCMAKE_MODULE_LINKER_FLAGS:STRING="-LXXX/staging_dir/target-aarch64_generic_musl/usr/lib -LXXX/staging_dir/target-aarch64_generic_musl/lib -LXXX/staging_dir/toolchain-aarch64_generic_gXXcc-7.5.0_musl/usr/lib -LXXX/staging_dir/toolchain-aarch64_generic_gcc-7.5.0_musl/lib -znow -zrelro -Wl,-Bsymbolic-functions"   -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=BOTH -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_STRIP=: -DCMAKE_INSTALL_PREFIX=/usr -DDL_LIBRARY=XXX/staging_dir/target-aarch64_generic_musl -DCMAKE_PREFIX_PATH=XXX/staging_dir/target-aarch64_generic_musl -DCMAKE_SKIP_RPATH=TRUE -DCMAKE_BUILD_TYPE:STRING=Release -DUSE_AVL_LIB:BOOL=FALSE -DENABLE_TESTS:BOOL=FALSE -DBUILD_EXAMPLES:BOOL=FALSE -DCMAKE_DISABLE_FIND_PACKAGE_SWIG=TRUE -DGEN_LANGUAGE_BINDINGS:BOOL=FALSE -DGEN_PYTHON_BINDINGS=0 -DGEN_LUA_BINDINGS=0 -DREPOSITORY_LOC:PATH=/etc/sysrepo -DCMAKE_INSTALL_PREFIX:PATH=/usr -DENABLE_NACM:BOOL=FALSE -DREQUEST_TIMEOUT=30 -DLONG_REQUEST_TIMEOUT=50 -DCOMMIT_VERIFY_TIMEOUT=30 -DOPER_DATA_PROVIDE_TIMEOUT=10 -DNOTIF_AGE_TIMEOUT=120 -DNOTIF_TIME_WINDOW=20 -DUSE_SR_MEM_MGMT=0 -DGET_ITEMS_FETCH_LIMIT=50 -DFILE_FORMAT_EXT:STRING=xml XXX/build_dir/target-aarch64_generic_musl/sysrepo-1.4.2

2.MAKE: 
make  -C XXX/sysrepo-1.4.2/.
error info:

[ 73%] Linking C executable sysrepoctl
XXX/staging_dir/toolchain-aarch64_generic_gcc-7.5.0_musl/lib/gcc/aarch64-openwrt-linux-musl/7.5.0/../../../../aarch64-openwrt-linux-musl/bin/ld: warning: libpcre.so.1, needed by XXX/staging_dir/target-aarch64_generic_musl/usr/lib/libyang.so, not found (try using -rpath or -rpath-link)
XXX/staging_dir/toolchain-aarch64_generic_gcc-7.5.0_musl/lib/gcc/aarch64-openwrt-linux-musl/7.5.0/../../../../aarch64-openwrt-linux-musl/bin/ld: XXX/staging_dir/target-aarch64_generic_musl/usr/lib/libyang.so: undefined reference to `pcre_compile'
XXX/staging_dir/toolchain-aarch64_generic_gcc-7.5.0_musl/lib/gcc/aarch64-openwrt-linux-musl/7.5.0/../../../../aarch64-openwrt-linux-musl/bin/ld: XXX/staging_dir/target-aarch64_generic_musl/usr/lib/libyang.so: undefined reference to `pcre_free_study'
XXX/staging_dir/toolchain-aarch64_generic_gcc-7.5.0_musl/lib/gcc/aarch64-openwrt-linux-musl/7.5.0/../../../../aarch64-openwrt-linux-musl/bin/ld:XXX/staging_dir/target-aarch64_generic_musl/usr/lib/libyang.so: undefined reference to `pcre_study'
XXX/staging_dir/toolchain-aarch64_generic_gcc-7.5.0_musl/lib/gcc/aarch64-openwrt-linux-musl/7.5.0/../../../../aarch64-openwrt-linux-musl/bin/ld: /XXX/staging_dir/target-aarch64_generic_musl/usr/lib/libyang.so: undefined reference to `pcre_free'
XXX/staging_dir/toolchain-aarch64_generic_gcc-7.5.0_musl/lib/gcc/aarch64-openwrt-linux-musl/7.5.0/../../../../aarch64-openwrt-linux-musl/bin/ld:XXX/staging_dir/target-aarch64_generic_musl/usr/lib/libyang.so: undefined reference to `pcre_exec'
collect2: error: ld returned 1 exit status
CMakeFiles/sysrepoctl.dir/build.make:96: recipe for target 'sysrepoctl' failed
make[2]: *** [sysrepoctl] Error 1
CMakeFiles/Makefile2:269: recipe for target 'CMakeFiles/sysrepoctl.dir/all' failed
make[1]: *** [CMakeFiles/sysrepoctl.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by michalvasko** [comment]
It seems you are not linking the required [`libpcre`](https://github.com/CESNET/libyang/tree/libyang1#build-requirements) library.

**Comment by LoveCPro** [comment]
>

**Comment by LoveCPro** [comment]
my libpcre and libyang have installed.this is a openwrt project,when I exec make package/sysrepo/compile is ok, When I manually execute cmake and make it gives an error。

**Comment by michalvasko** [comment]
I have told you what the problem is, to solve it is up to you. I have no experience with cross-compilation.

**Comment by LoveCPro** [comment]
I have set LDFLAGS="-L/${LIBPCRESODIR}",it still gives an error

**Comment by michalvasko** [comment]
I believe that just adds additional directory to search for dynamic libraries, does not actually link any. Flags `-l<lib-name` link dynamic libraries.
