### ISSUE TITLE
skip suspended loop missing ++i?

### ISSUE THREAD

**Issue by irfanHaslanded** [sysrepo/sysrepo#2723]
In various places in shm_sub.c, I see the skip suspended logic inside a while loop that is not correct.
shouldn't this be 
```c
        /* skip suspended subscriptions */
        if (ATOMIC_LOAD_RELAXED(shm_sub[i].suspended)) {
            ++i;
            continue;
        }
```

```c
    i = 0;
    while (i < shm_rpc->sub_count) {
        /* check subscription aliveness */
        if (!sr_conn_is_alive(shm_sub[i].cid)) {
            /* recover the subscription */
            if ((err_info = sr_shmext_rpc_sub_stop(conn, shm_rpc, i, 1, SR_LOCK_READ, 1))) {
                sr_errinfo_free(&err_info);
            }
            continue;
        }

        /* skip suspended subscriptions */
        if (ATOMIC_LOAD_RELAXED(shm_sub[i].suspended)) {
            continue;
        }

        /* valid subscription */
        if (sr_shmsub_rpc_listen_filter_is_valid(input, conn->ext_shm.addr + shm_sub[i].xpath)) {
            has_sub = 1;
            if (shm_sub[i].priority > *max_priority_p) {
                *max_priority_p = shm_sub[i].priority;
            }
        }

        ++i;
    }
```

P.S I have not tested this, just looked a bit strange while reading..

**Comment by michalvasko** [comment]
Yes, I do believe you are right. Suspension was supported initially only for notification subscriptions where the loop is a bit different and I have written tests only for that. Later, when I added the support for all other kinds of subscriptions I made this mistake. Thanks, should be fixed.

**Comment by irfanHaslanded** [comment]
the change in common.c is not applicable to libyang1, as the code change is functionally equivalent, I think. So this issue does not impact libyang1 branch

**Comment by michalvasko** [comment]
Yes, you cannot suspend subscriptions there.
