### ISSUE TITLE
Runtime error when pulling data

### ISSUE THREAD

**Issue by jorgensigvardsson** [sysrepo/sysrepo#2731]
I have a subscription for data using the "pull method", using `sr_oper_get_items_subscribe`. I'm using netopeer2 (server and client), and sysrepo-plugind.

What I'm trying to accomplish: I want to subscribe to all non-config data under `/ietf-system:system/clock`. When I subscribe to the data, I do this `sr_oper_get_items_subscribe(session, "ietf-system", "/ietf-system:system/clock//*", state_cb, 0, &sub);`. The subscription does not fail, and all seems good. This subscription is done in the initialization callback of a sysrepo-plugind plugin.

From netopeer2-cli, I then connect and run `get --filter-xpath /ietf-system:system-state/clock/current-datetime`, I get this error in the client:
```
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  Unexpected XPath expression end.

        type:     application
        tag:      operation-failed
        severity: error
        message:  User callback failed.
```

On the server end I get this error:
```
[ERR]: LY: Unexpected XPath expression end.
[ERR]: NP: Getting data "/ietf-system:*" from sysrepo failed (libyang error).
```

I'm a bit stumped here. I've searched for similar problems, but the closest I got was issue #2358 (the error message `Unexpected XPath expression end` is present in that issue). I don't think I'm having the same issue.

I fully expect that I'm doing something wrong, but I cannot understand _what_ I'm doing wrong.

If I narrow the subscription filter down to a single leaf, like this: `sr_oper_get_items_subscribe(session, "ietf-system", "/ietf-system:system/clock/current-datetime", state_cb, 0, &sub);` all is fine (no errors, and data is returned to client).

My ambition is to have different callbacks for different subtrees. Is that not possible?

The version I'm using is `2.0.53`.

**Comment by jorgensigvardsson** [comment]
I think I understand what I'm doing wrong. According to the function documentation, `sr_oper_get_items_subscribe` only accepts a path to a subtree: "_identifying the subtree (not strictly required, all list/leaf-list instances are also valid, for example) which the provider is able to provide. Predicates can be used to provide only specific instances of nodes._"

So, if I have understood this right, in order to subscribe to anything beneath `/ietf-system:system-state/clock`, I simply specify that path, and sort out the leaves myself in the callback.

**Comment by jorgensigvardsson** [comment]
It seems that my current thesis is correct: the subscription function accepts subtree paths only. It would be nice if the subscription function could reject the faulty path when called, instead of causing netconf queries to fail long after the subscription was made.

**Comment by michalvasko** [comment]
You have correctly discovered the problem and yes, it would be best if the faulty XPath produce a nicer error. I will take a look once I find some time.

**Comment by michalvasko** [comment]
In `devel` your XPath should now work fine, the same way as if you did not put `//*` at the end.
