### ISSUE TITLE
sr_copy_config triggers an Alignment trap

### ISSUE THREAD

**Issue by mblacksee** [sysrepo/sysrepo#2733]
Hi,
I've faced a problem while copying all running DS to startup DS right after an insert operation to a list ordered by user.
Sequence is as below in the code;
1- Calling sr_move_item()
2- Calling sr_apply_changes()
3- Calling sr_session_switch_ds() for SR_DS_STARTUP
4- Calling sr_copy_config(session, NULL, SR_DS_RUNNING, 0)
5- Calling sr_session_switch_ds() for SR_DS_RUNNING

In the 4th step, application crashes w/ alignement trap and gdb debugging session gives that lysp_main_pmod_get_submodule() function in libyang tries misaligned memory access at the second line as below;
`struct lysp_module *main_pmod = PARSER_CUR_PMOD(pctx)->mod->parsed;`

libyang version is 9464f42 (devel branch)
sysrepo version is a8a9d9b (devel branch)
(They are at the top of devel branches by the moment)

Not sure %100 but problem seems to be raised after insertion into user ordered list. Above sequence seems to work for other node types.

Thanks in advance, BR.

**Comment by michalvasko** [comment]
Hard to guess the problem based on this information. It would be best if you could provide a way to reproduce it, otherwise I do not think I will be able to fix it.

**Comment by jktjkt** [comment]
What platform are you on? Can you share a full backtrace as well as the actual pointer values that are being dereferenced?

**Comment by mblacksee** [comment]
Hi Guys,
The platform is embedded ARC and I wasn't able to reproduce the same case on PC at first. After some progress on the debuggin of the problem, I think that I'm able to reproduce the same case in a different way on the PC with below outcomes;

`sysrepocfg: /home/abc/def/sysrepo_workspace/libyang-2.0.156/src/diff.c:328: lyd_diff_userord_attrs: Assertion first_pos < LY_ARRAY_COUNT(userord_item->inst) failed.`

This happens when I added (`sysrepocfg --edit=vi -m example-jukebox -f json -d running`) second element to `example-jukebox:jukebox/playlist/song` list as a first element (above to existing element of the list). I think that same problem happens in the senario that I mentioned in first comment. (If I call  sr_move_item() API w/ `after` multiple times, no problem occurs)


BR.

[example-jukebox.yang.txt](https://github.com/sysrepo/sysrepo/files/8131418/example-jukebox.yang.txt)

**Comment by michalvasko** [comment]
Okay, I managed to reproduce it and it should now be fixed, in latest *libyang* in `devel`.

**Comment by mblacksee** [comment]
Thanks Michal, It works now!
