### ISSUE TITLE
sr_event_notif_send no longer in devel branch ?

### ISSUE THREAD

**Issue by th-buchner** [sysrepo/sysrepo#2735]
Hi,
I have switched to devel branch, there is no `sr_event_notif_send_tree`  any more.
In master it is not marked as "deprecated".

Shall I use `sr_notif_send_tree` instead ?

Regards Thomas

**Comment by michalvasko** [comment]
Yes, `sr_notif_send_tree` is essentially the same function but renamed to unify naming with other functions.
