### ISSUE TITLE
Enable Feature Issue

### ISSUE THREAD

**Issue by pranaysahay** [sysrepo/sysrepo#2738]
Hello, I am not able to  use "--enable-feature" in sysrepoctl command. Each time it says, 'Scheduled Changes not applied.....'. I am using the latest sysrepo/sysrepo-netopeer2 docker image. I am able to successfully install the yang.

Here is the output
root@5e42884924cf:/# sysrepoctl -v 3 --enable-feature O-RU-COORDINATED-ANT-CAL -c o-ran-antenna-calibration
[INF]: Scheduled changes not applied because of other existing connections.
[INF]: Connection 3 created.
[INF]: Module "o-ran-antenna-calibration" feature "O-RU-COORDINATED-ANT-CAL" enabling scheduled.

I tried to restart the docker but there is no difference. Here is the output of sysrepoctl -l (Its says I F but doesnt show the enabled feature)
o-ran-antenna-calibration  | 2021-07-26 | I F   | root:root | 600         |            |                              

Any pointers/suggestions would be of great help.

Thanks
Pranay

**Comment by michalvasko** [comment]
```
[INF]: Scheduled changes not applied because of other existing connections.
```
means you need to stop all *sysrepo* applications such as `netopeer2-server`, which is probably started automatically in this image.

**Comment by pranaysahay** [comment]
Thanks for the quick response,but when I checked the running processes and tried to kill netopeer2-server, its restarted automatically. I guess there is a watchdog which is restarting it. Here is the output of ps -ef:
root@73aaa7738575:/# ps -ef
UID          PID    PPID  C STIME TTY          TIME CMD
root           1       0  0 16:27 ?        00:00:00 /usr/bin/python /usr/bin/supervisord -c /etc/supervisord.conf
root          16       0  0 16:31 pts/0    00:00:00 /bin/bash
root          40       1  0 16:35 ?        00:00:00 /usr/bin/netopeer2-server -d
root          61      16  0 16:37 pts/0    00:00:00 ps -ef

I tried stopping the supervisor daemon but its getting started again.

Not sure if I am using the correct docker image. This is how I am starting the docker:
docker run --mount source=oran,target=/oran -p 830:830 sysrepo/sysrepo-netopeer2

Am I missing anything here?? Let me know if you need any other specific details.

Thanks again
Pranay

**Comment by michalvasko** [comment]
It is up to you to fight with Docker, we are not directly maintaining the image. The only suggestion I can give you is not to use it because it is rarely up-to-date and may cause unnecessary problems such as the one you are having.

**Comment by pranaysahay** [comment]
Sure Michal..Thanks. compiled and able to run it successfully
