### ISSUE TITLE
Although max-element is define for list in yang file but able to create more entries for that list then what is define.

### ISSUE THREAD

**Issue by Sumit1270135** [sysrepo/sysrepo#2746]
Hi Team,

i am able to write more entries for alarm-list in sysrepo DB then what define in yang module.

leaf event-time {
      type yang:date-and-time;
      mandatory true;
      description
        "Timestamp to indicate the time when the fault is detected/cleared.";
    }
  }

  container active-alarm-list {
    config false;
    description
      "List of currently active alarms. An alarm is removed from this table when the state transitions to clear.";
    list active-alarms {
      max-elements 3;
      description
        "List of currently active alarms";
      uses alarm;
    }
  }

But we can able to write 4 alarms in sysrepo DB.

sysrepoctl --version
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v2.0.42 (SO v6.4.8)

Regards
Sumit

**Comment by jktjkt** [comment]
In the `operational` DS the validity checks are not automatically enforced.That's for several reasons, one of them is [the way the operational data work](https://netopeer.liberouter.org/doc/sysrepo/devel/html/index.html#oper_data). This behavior is [allowed by the NMDA RFC](https://datatracker.ietf.org/doc/html/rfc8342#page-15):

> `<operational>` SHOULD conform to any constraints specified in the data model, but given the principal aim of returning "in use" values, it is possible that constraints MAY be violated under some circumstances (e.g., an abnormal value is "in use", the structure of a list is being modified, or remnant configuration (see [Section 5.3.1](https://datatracker.ietf.org/doc/html/rfc8342#section-5.3.1)) still exists).  Note that deviations SHOULD be used when it is known in advance that a device does not fully conform to the <operational> schema.
>
> Only semantic constraints MAY be violated.  These are the YANG `when`, `must`, `mandatory`, `unique`, `min-elements`, and `max-elements` statements; and the uniqueness of key values.
>
> Syntactic constraints MUST NOT be violated, including hierarchical organization, identifiers, and type-based constraints.  If a node in `<operational>` does not meet the syntactic constraints, then it MUST NOT be returned, and some other mechanism should be used to flag the error.

**Comment by Sumit1270135** [comment]
got it.
