### ISSUE TITLE
[ERR] Internal error (sysrepo/src/edit_diff.c:2463).

### ISSUE THREAD

**Issue by berstrob** [sysrepo/sysrepo#2747]
Hello,

so implemented more of my customdatastore-plugin for the config data and it works as expected and for my tests with like 1000 components it is like 2 sec instead of 13  ( have not tried to optimize it yet) .  I first wanted to try it for the operational too , until now i just do it with `sr_oper_get_items_subscribe()` but i thought i can just add it there like i do the config in my plugin `lyd_new_path()`, but i guess not : i got `[ERR] Internal error (sysrepo/src/edit_diff.c:2463)`. Even with the simplest test case (after i removed most of the config (and real database stuff) ,and test it locally with the newest version from today morning) .  If i return nothing, (and i subscribe with the change callback) i get the config data as expected but , i seem to be unable to add something with the ds_plugin. (i only use `  sr_module_ds_t mod_ds = {{"LYB DS file", "DS TEST", "LYB DS file", "DS TEST", "LYB notif"}};` )

I attached the ouput and can if need probably cut my test program even more so it does compile with out the added stuff.
The added output in the files (other then the line /function debugs)  are just a for loop over the values i added to the tree  (  i just print them after adding them in the load callback, after getting the values via ` sr_tree_to_values(root,"//*",&vals,&val_count);`  and then print those) .

I hope i am just doing something wrong, or did miss understand it , but i can use the old method , even if  that would mean having to fetch the data in two places  
[operdatatest2.zip](https://github.com/sysrepo/sysrepo/files/8204560/operdatatest2.zip)

Regards Bernd

**Comment by michalvasko** [comment]
From what you said I understand that you are using `lyd_new_path()` in the custom oper DS callbacks. The datastore should only store data, the function implies creating some data, hence the error.

**Comment by berstrob** [comment]
Sorry for being not clear,

i use it in my datastore plugin (not the oper_callbacks) in the log there is only the "stored data" . I just build the return tree like that and it works fine for the config, how else should i get a tree for the load function? It fails while merging  the stored "running" and "operational" datastore 


```
int openconfig_platform_set_comp_name_ds(const char *name,sr_datastore_t ds,const struct lys_module *mod, struct lyd_node **mod_data) {
    int rc=SR_ERR_OK;
    char path[buffersize];
    LY_ERR test;
    snprintf(path, sizeof(path), OC_COMP_NAME_CONFIG, name);
    if (ds==SR_DS_RUNNING) {
        if ( *mod_data ==NULL)
            lyd_new_path(NULL, mod->ctx,path, name, 0, mod_data);
        else
            lyd_new_path(*mod_data, mod->ctx,path, name, 0, NULL);
        {
            for (int i=0;i<OC_XPATH_DEFAUTS_SUB;i++) {
                snprintf(path, sizeof(path), get_xpath_port_str_from_int(OC_XPATH_PORT_DEFAUTS+i), name);
                test=lyd_new_path(*mod_data, mod->ctx,path, "", 0, NULL);
                if (test) {
                    ERR(" openconfig_platform_set_comp_name_ds(%d):  %s",get_xpath_port_str_from_int(OC_XPATH_PORT_DEFAUTS+i));
                }
                
            }   
        }
    }
    
    if (ds==SR_DS_OPERATIONAL) {
        snprintf(path, sizeof(path), OC_COMP_NAME_STATE, name);
        if ( *mod_data ==NULL)
            lyd_new_path(NULL, mod->ctx,path, name, 0, mod_data);
        else
            lyd_new_path(*mod_data, mod->ctx,path, name, 0, NULL);
    }
    return rc;
}



static int
test_lyb_load(const struct lys_module *mod, sr_datastore_t ds, const char **xpaths, uint32_t xpath_count,
        struct lyd_node **mod_data)
{
    int rc = SR_ERR_OK;
    for (int i = 0; i < xpath_count; ++i) {
        printf("xpath  (%d ) = %s  \n",i, xpaths[i]);
    }
    DBGPRINTLINEDS
   *mod_data = NULL;
     printf("mod name '%s'\n",mod->name);
     if (strcmp(mod->name,"openconfig-platform")==0 ) {
        openconfig_platform_set_comp_name_ds("TEST",ds,mod,mod_data);
         if (DBG || ds==SR_DS_OPERATIONAL || ds==SR_DS_RUNNING) test_print_data_models(*mod_data);
         return rc;
     }
 DBGPRINTLINEDS
    return rc;
}
```

**Comment by michalvasko** [comment]
You were clear enough. The datastore is meant to manage all the data and provide a way of storing them, nothing else. Meaning if the store callback is called, the callback should store the data is received. If load is called, just returned the previously stored data.

You are skipping the first step of storing some data from *sysrepo* and just returning some specific data in the load callback. I repeat, this is not the intentional use and is effectively making changing these data by standard *sysrepo* API impossible thus breaking it. But, you are free to use *sysrepo* as you see fit just do not expect much support. This particular problem should be possible to solve simply by making the returned data an `edit` by adding `merge` operation on the top-level node in the returned data. You are missing the detail that operational DS is stored differently than the other datastores. But it is transparent if the callbacks do what is expected of them.

**Comment by berstrob** [comment]
Oh i see,
 i did test it with the config/running ds (and there will be a/is a store as well, at least for config, but i wanted to store the vaules in my db in the format they already are not some lib yang nodes :) ) , just did not expect the  operational store to be stored differently , my bad . I just need it for two models with more then a few 1000 list entrys which take to long to validate every time someone changes anything on that outside sysrepo, like 5-6 seconds.

I did not store anything in operational before (only did the subscribe part and loaded the values out of the db) , so i had no test case to send me some data (and did not plan to store anything in the operational , which i know is not the intended way, but i thought why store it first if i can load it once directly and be faster, the data will be the same, there is only one way were this data will be coming from on my system for those models, so i spend no efforts implementing/testing it , my mistake i now know) .

And you already told me that i have to be careful, and add notifications my self for example (one of those possible operation generates a change notification of over 40000 lines in one go). 

Thanks for your help, and the great work you do.
Regard Bernd
