### ISSUE TITLE
Advantages over using Netopeer Client even if we are able to use sysrepocfg --edit/import commandlines

### ISSUE THREAD

**Issue by Abrahamma97** [sysrepo/sysrepo#2749]
Hi,
This is a query on what could be the advantages over using Netopeer Client even if we are able to use sysrepocfg --edit/import commandlines. Basically if all read write operation as well as configuring using sysrepocfg we would be able to completely revo netopeer2 client right?

**Comment by michalvasko** [comment]
There is one major difference, `sysrepocfg` only allows you to manage data **locally** on the system while `netopeer2-cli` (or NETCONF in general) provides **remote** network access to all the data.
