### ISSUE TITLE
doc confusion about enabled event on an operational datastore

### ISSUE THREAD

**Issue by gotthardp** [sysrepo/sysrepo#2751]
The documentation says that *a subscription can request enabled event on SR_DS_RUNNING datastore*, but it seems to work correctly also for the operational datastore. Why is the SR_DS_RUNNING datastore mentioned explicitly, please?
https://github.com/sysrepo/sysrepo/blob/6c2c385720633ad3c618df49af20806d05a2d455/doc/subs.dox#L47-L50

If it is OK to subscribe the operational datastore with `SR_SUBSCR_ENABLED`, shouldn't the sentence just say *a subscription can request enabled event on a datastore*? Just to avoid any confusion.

**Comment by michalvasko** [comment]
Right, just a forgotten info that is likely not true for quite some time, fixed.
