### ISSUE TITLE
sr_module_change_subscribe does not notify after sr_oper_delete_item_str

### ISSUE THREAD

**Issue by gotthardp** [sysrepo/sysrepo#2752]
I am subscribed via `sr_module_change_subscribe` to changes to my OPERATIONAL store. How, when I make a change to that store:
* The callback **is** called upon `sr_set_item_str`
* The callback **is** even called upon `sr_discard_oper_changes`
* However, the callback is **not** called upon `sr_oper_delete_item_str` (although the deletion is successful)

Am I doing something wrong, or is there a bug somewhere?

I made a sysrepo test that reproduces this behaviour: [error.patch.txt](https://github.com/sysrepo/sysrepo/files/8234092/error.patch.txt)

**Comment by michalvasko** [comment]
Okay, the complexity of these use-cases internally is starting to become unbearable so I will have to rewrite it. But I have fixed it for now and committed your test with additional checks so it should be working even in future.
