### ISSUE TITLE
How to know a particular notification is subscribed?

### ISSUE THREAD

**Issue by Nofun111** [sysrepo/sysrepo#2754]
Hi.
Mentioned in issue #2256, 
> If you really need this information, it can be found in the operational data of sysrepo-monitoring module but root access is required by default to get them (since they include information about all the sysrepo connections and subscriptions).

This can only know who subscribes to a certain module, a module name. How to know a particular notification in Module is subscribed?

Thanks.

**Comment by michalvasko** [comment]
Strictly speaking, whether a particular notification is really subscribed only the subscriber knows because any filter used is applied only by it. So this information is not available.

**Comment by Nofun111** [comment]
Does this indicate that as long as someone subscribes to one of the notifications in the module, such as notification A. Sysrepo send another notification in the module, like notification B. Notification B is also sent to subscribers.

**Comment by michalvasko** [comment]
If I understand correctly, yes. The subscribers filter out the interesting notifications and the originator is always able to publish every notification to all the subscribers in a single SHM segment.

**Comment by Nofun111** [comment]
This solved my problem, thanks
