### ISSUE TITLE
Access datastore during RPC callback

### ISSUE THREAD

**Issue by nullromo** [sysrepo/sysrepo#2758]
How are we meant to access data from the datastore during the handling of an RPC? I have a module like this:

```yang
container {
    leaf some-data {
        ...
    }
}
rpc some-rpc {
    ...
}
```

and during my callback for the `some-rpc` RPC, I get error code 5 (Item not found) when trying to get the `some-data` leaf. Are implicit sessions provided in RPC callbacks not given access to other parts of the datastore? I didn't see anything about this in the documentation pages. If so, what is the proper way to get that data during an RPC callback?

**Comment by michalvasko** [comment]
You should be able to access data normally even in the callback. Make sure you have the correct datastore set on the session you want to read the data from. Other than that, if the data are not found, they do not exist.

**Comment by nullromo** [comment]
Ahh, thank you. I did not realize that RPC callbacks occur in `SR_DS_OPERATIONAL` contexts. Switching to the correct datastore allows me to read the data.

However, I have a follow-up question. Now that I am in my RPC handler and I have read data from the datastore, I would like to insert data into another part of the datastore. Up until now, I have been using `SR_EV_UPDATE` to modify changes during a callback like this. However, the event for RPC callbacks is `SR_EV_RPC`.

Is there any way to *modify* data in a datastore during an RPC callback?

**Comment by michalvasko** [comment]
Just modify the data in the callback normally, should work just fine. Except data of the same module of the RPC being executed, which will most likely result in a dead lock and a timeout.

**Comment by nullromo** [comment]
Thank you again. Based on your feedback, I was able to create a minimal example and it worked that time. That led me to discover the source of the problem, which I will explain below for anyone coming across this thread. The tl;dr is that I needed 2 separate `sr_subscription_ctx_t`s.

I originally had something like this:

```cpp
// subscription context
static sr_subscription_ctx_t* subscription = NULL;

int sr_plugin_init_cb(sr_session_ctx_t* session, void** privateData) {
    // subscribe to module 1 for some data changes
    int rc = sr_module_change_subscribe(session, MODULE_1, ..., SR_SUBSCR_DEFAULT, &subscription);
    if(rc != SR_ERR_OK) {
        return rc;
    }
    // subscribe to module 2 for an RPC
    rc = sr_rpc_subscribe(session, MODULE_2, ..., SR_SUBSCR_DEFAULT | SR_SUBSCR_CTX_REUSE, &subscription);
    return rc;
}

void sr_plugin_cleanup_cb(sr_session_ctx_t* session, void* privateData) {
    sr_unsubscribe(subscription);
}
```

My original thinking was that the callback registered with the first `sr_*_subscribe` call would be subscribed to module 1, and the second callback registered with the second `sr_*_subscribe` call would be subscribed to module 2. However, that is not the case. The subscription context (`sr_subscription_ctx_t`) "remembers" all the modules that is has been subscribed to. This means that both callbacks are considered to be subscribed to both modules. Therefore, both modules become locked during the callbacks. In order to fit my use case, I changed the code as follows:

```cpp
// two entirely separate subscription contexts
static sr_subscription_ctx_t* module1Subscription = NULL;
static sr_subscription_ctx_t* module2Subscription = NULL;

int sr_plugin_init_cb(sr_session_ctx_t* session, void** privateData) {
    // subscribe to module 1 using one of the subscription contexts
    int rc = sr_module_change_subscribe(session, MODULE_1, ..., SR_SUBSCR_DEFAULT, &module1Subscription );
    if(rc != SR_ERR_OK) {
        return rc;
    }
    // subscribe to module 2 using the other subscription context
    rc = sr_rpc_subscribe(session, MODULE_2, ..., SR_SUBSCR_DEFAULT, &module2Subscription );
    return rc;
}

void sr_plugin_cleanup_cb(sr_session_ctx_t* session, void* privateData) {
    sr_unsubscribe(module1Subscription );
    sr_unsubscribe(module2Subscription );
}
```

Now that the RPC callback is registered inside a subscription context that only ever subscribes to module 2, the callback is allowed to modify module 1.

**NOTE**: *Unlike with `SR_EV_UPDATE` handlers, it **is** necessary to call `sr_apply_changes` in this case.*

**Comment by michalvasko** [comment]
> The subscription context (sr_subscription_ctx_t) "remembers" all the modules that is has been subscribed to. This means that both callbacks are considered to be subscribed to both modules.

You deduced the correct solution but based on wrong assumptions because this is not true. The problem is that in the RPC callback you were in all likelihood modify data you subscribed for in the change callback. So, your subscription was being polled, the RPC event being processed, which changed some data, which in turn generated module change event that was supposed to be handled by your subscription. However, it was still handling the RPC event so what you got was a dead lock.

The solution, as you discovered, is for such 2 subscriptions to be handled in separate threads by using 2 subscription structures with their own threads, for example.
