### ISSUE TITLE
when i delete a leaf-list element with special value, the whole leaf list elements was deleted

### ISSUE THREAD

**Issue by ZhaoGuangYue** [sysrepo/sysrepo#276]
when i delete a leaf-list element with special value, the whole leaf list elements was deleted, is this a bug?

as an example ,when i use edit-config xml to delete "EFGH" element ,the "ABCD" also be deleted.

 data like follow:
`<ManagedElement xmlns="urn:fox:params:xml:ns:yang:ran:ManagedElement" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" >
  <RUNRADIOMODE xc:operation="create">ABCD</RUNRADIOMODE>
  <RUNRADIOMODE xc:operation="create">EFGH</RUNRADIOMODE>
</ManagedElement>`

edit-config xml like the follow:

`<ManagedElement xmlns="urn:fox:params:xml:ns:yang:ran:ManagedElement" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <RUNRADIOMODE xc:operation="delete">EFGH</RUNRADIOMODE>
</ManagedElement>`

**Comment by lukasmacko** [comment]
Hi, 

this seems to be Netopeer issue I have reported it https://github.com/CESNET/Netopeer2/issues/15

Regards,
Lukas

**Comment by rastislavszabo** [comment]
Fixed in https://github.com/CESNET/Netopeer2/issues/15
