### ISSUE TITLE
Error while open sysrepoctl -l 

### ISSUE THREAD

**Issue by NTUGY** [sysrepo/sysrepo#2760]
root@ax_peta:/usr/bin# sysrepoctl -l
[ERR]: Failed to create a new libyang context.
sysrepoctl error: Failed to connect (Internal error)

**Comment by michalvasko** [comment]
This will be caused by some library incompatibility on your system, the simplest solution is completely remove all libraries (libyang, sysrepo, libnetconf2) and data (`make sr_clean` for sysrepo) and reinstall it all.
