### ISSUE TITLE
On returning SR_ERR_OPERATION_FAILED the data still gets commited to the sysrepo running datastore.

### ISSUE THREAD

**Issue by Abrahamma97** [sysrepo/sysrepo#2761]
Hi,
On returning SR_ERR_OPERATION_FAILED the data still gets commited to the sysrepo running datastore. Ideally this should not be the case right? If the functionality is like this what should I be returning so that the data will we rejected and not run in the datastore?

**Comment by michalvasko** [comment]
What event callback are you returning the error from? It must be `SR_EV_CHANGE`, return value of `SR_EV_DONE` is ignored.

**Comment by Abrahamma97** [comment]
Yes @michalvasko ,
It is event SR_EV_CHANGE  still when returning  SR_ERR_OPERATION_FAILED the change is committed to running datastore.

**Comment by michalvasko** [comment]
That seems extremely unlikely for such a bug to be present but if you can describe/attach the use-case and I can reproduce it I should be able to help you fix the problem.
