### ISSUE TITLE
sysrepo option to install newer version of existing yang

### ISSUE THREAD

**Issue by meghna-doshi** [sysrepo/sysrepo#2763]
Hi,
We have a requirement where 
1. system is already running with say x revision of one yang file.
```
  revision 2020-10-08 {
    description "Initial revision, Defined by Junila";
  }
```
3. Then there are some changes in this yang, so we add another revision in the yang file:
```
  revision 2022-03-22 {
    description "Next revision, Defined by Junila";
  }
```
4.  Now we try to install the new yang (in 2), using option -U i.e 
```
sysrepoctl -U $MODDIR/junila_3gpp-nr-nrm-nrcelldu.yang -s $MODDIR -v4
```

We are getting following error:
```
sysrepoctl|ERROR "SR stderr" Module "junila_3gpp-nr-nrm-nrcelldu@2022-03-22" is present in the context in other implemented revision (2020-10-08).
sysrepoctl error: Failed to update module "/usr/local/cuduyang//junila_3gpp-nr-nrm-nrcelldu.yang" (libyang error)

```

We tried using "sysrepoctl -i" option also but then the old yang remains, newer one doesnt get installed.

So the intention is that if a schema upgrade happens, where only some additions are happening in yang files, we should be able to install new yangs so that old edit-config values which are persisted in the startup datastore, can be used. We dont want to reset sysrepo for this use case.

**Comment by michalvasko** [comment]
The update should succeed so I will need all the modules you have installed and the updated one to reproduce it and see what the problem is.

**Comment by siprab** [comment]
Hi, 
With respect to the previous comment (https://github.com/sysrepo/sysrepo/issues/2763#issue-1177322515), below are the detailed steps we followed: 
1. Installed all the yang modules as below:  (pls refer the attached .zip file)                                                                                                                   
                                                                                              
     $SYSREPOCTL -i $MODDIR/junila_3gpp-nr-nrm-nrcelldu.yang -I $TMPFILE -s $MODDIR -v4
     $SYSREPOCTL -i $MODDIR/_3gpp-common-managed-element.yang -s $MODDIR -e 
     MeasurementsUnderManagedElement -v4
    $SYSREPOCTL -i $MODDIR/_3gpp-common-subnetwork.yang -s $MODDIR -v4
    $SYSREPOCTL -i $MODDIR/_3gpp-nr-nrm-nrcelldu.yang -s $MODDIR -v4
    $SYSRE
[modules.zip](https://github.com/sysrepo/sysrepo/files/8424587/modules.zip)
POCTL -i $MODDIR/_3gpp-nr-nrm-nrsectorcarrier.yang -s $MODDIR -v4
    $SYSREPOCTL -i $MODDIR/_3gpp-nr-nrm-bwp.yang -s $MODDIR -v4
    $SYSREPOCTL -i $MODDIR/_3gpp-nr-nrm-ep.yang -s $MODDIR -v4
    $SYSREPOCTL -i $MODDIR/_3gpp-nr-nrm-commonbeamformingfunction.yang -s $MODDIR -v4
    $SYSREPOCTL -i $MODDIR/o-ran-heartbeat-management.yang -s $MODDIR -v4
    $SYSREPOCTL -i $MODDIR/ietf-hardware.yang -s $MODDIR -e hardware-state -v4
    $SYSREPOCTL -i $MODDIR/o-ran-aggregation-base.yang -s $MODDIR -v4

2. The value of the $TMPFILE is as following:                                                                                                    
    <ManagedElement xmlns="urn:3gpp:sa5:_3gpp-common-managed-element" 
     xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" xc:operation="create">
    <id>1</id>
    <attributes>
        <userLabel>DU_ME</userLabel>
        <dnPrefix>VnfId=cs-gnb-1-du-1</dnPrefix>
        <userDefinedState>INIT</userDefinedState>  
   <!-- <priorityLabel>0</priorityLabel> -->
    </attributes>
  </ManagedElement>
3.  Then ran the processes (netopeer2-server, netopeer2-cli and application), performed edit-config and stopped all processes & cleaned the subscriptions. 
4. Changed the yang "junila_3gpp-nr-nrm-nrcelldu.yang" and added the revision header with the change description. When tried to update the same by:  $SYSREPOCTL -U $MODDIR/junila_3gpp-nr-nrm-nrcelldu.yang -s $MODDIR -v4 
  it produced below error:
 
   sysrepoctl|ERROR "SR stderr" Module "junila_3gpp-nr-nrm-nrcelldu@2020-10-08" already installed.
   sysrepoctl error: Failed to update module "/usr/local/cuduyang/junila_3gpp-nr-nrm-nrcelldu.yang" (Item already exists)

**Comment by michalvasko** [comment]
*sysrepo* says that the revision is the same, so it probably is. Did you actually put new `revision` statement into the module and updated its name or only the latter?

**Comment by michalvasko** [comment]
I have tested it and have updated the module just fine. What *sysrepo* version are you using?

**Comment by siprab** [comment]
Hi, 
I tried once more and the update works fine now. 

Thanks

**Comment by siprab** [comment]
Hi, 

Is there any operation other that -l or --list for sysrepoctl where we can find a single yang is installed or not in sysrepo.

**Comment by michalvasko** [comment]
No, in `sysrepoctl` there is no such command (although it would trivial to implement). You just need to connect to *sysrepo*, get the created context, and check whether the particular module is implemented in the context or not.

**Comment by myonlystarWang** [comment]
> 
Hi @siprab 
Why not use `sysrepoctl -l | grep xxx`?

**Comment by meghna-doshi** [comment]
@michalvasko we tried the following and we think the behavior is not proper:

1. install x.yang (version 1) : x.yang is dependent on say y.yang (version 1)
2. do some edit-config on attributes of x.yang and y.yang.
3. copy-config data from running to startup datastore.
4. now change x.yang (version 1) -> x.yang (version 2), though y.yang remains same at version 1 as no change required in y.yang.
5. so now here our observation is that to install x.yang with -U option we have to first uninstall all dependent yangs like in this case y.yang has to be uninstalled and then re installed.
6. Step (5) would have bee fine but after uninstall and reinstall of y.yang, we are not getting the data of y.yang given to application from the startup datastore, which was stored earlier in step (2).

Since this seems to be a easily reproducible problem, i have not attached any sample yang. But in case you need any sample for this, let us know.

**Comment by meghna-doshi** [comment]
Hi Michal,
Anything on above ?? (https://github.com/sysrepo/sysrepo/issues/2763#issuecomment-1099547773)

**Comment by michalvasko** [comment]
Please include specific example files for all the steps so that I can reproduce it, it worked fine for me with some simple module with a dependency that I updated.

**Comment by siprab** [comment]
Hi Michal,  
We have followed the below steps: 
1. installed all the yangs in attached zip [module1.zip](https://github.com/sysrepo/sysrepo/files/8528867/module1.zip). In this junila_3gpp-nr-nrm-gnbdufunction.yang is dependent on junila_3gpp-nr-nrm-nrcelldu.yang. 

2. Started the processes (Netconf server and client) and done the edit-config and copy-config for leaf X0005B9_F1-State in  junila_3gpp-nr-nrm-gnbdufunction.yang. 

3. Then modified the junila_3gpp-nr-nrm-nrcelldu.yang file by adding a leaf transmitPower [junila_3gpp-nr-nrm-nrcelldu.zip](https://github.com/sysrepo/sysrepo/files/8529214/junila_3gpp-nr-nrm-nrcelldu.zip), to update the same in sysrepo using the below commands: 
         $SYSREPOCTL -u junila_3gpp-nr-nrm-gnbdufunction
         $SYSREPOCTL -U $MODDIR/junila_3gpp-nr-nrm-nrcelldu.yang -s $MODDIR -v4
         $SYSREPOCTL -i $MODDIR/junila_3gpp-nr-nrm-gnbdufunction.yang -s $MODDIR -v4

4. However uninstall and reinstall of junila_3gpp-nr-nrm-gnbdufunction.yang, we are not getting the data of junila_3gpp-nr-nrm-gnbdufunction.yang given to application from the startup datastore, which was stored earlier in step (2).

**Comment by michalvasko** [comment]
Great, with these examples I have reproduced it and hopefully fixed it, with a modified test as well.
