### ISSUE TITLE
oper == SR_OP_DELETED and we use sr_get_items will we get the old values already in sysrepo or new coming values

### ISSUE THREAD

**Issue by Abrahamma97** [sysrepo/sysrepo#2766]
Hi @michalvasko ,
 I had a question regarding the same,
if oper == SR_OP_DELETED and we use sr_get_items(pvt_data->session, "/o-ran-usermgmt:users/user/name", 0, 0, &user_vals, &user_val_count); will we get the old values already in sysrepo or the new values we are going to push. If it is the old values I wanted to know how we could get the new coming values?

**Comment by Abrahamma97** [comment]
Actually I am getting the old values. I shall show below consider the below XML in running data store
`<users xmlns="urn:o-ran:user-mgmt:1.0">
  <user>
    <name>oranuser</name>
    <account-type>PASSWORD</account-type>
    <password>oranuser</password>
    <enabled>true</enabled>
  </user>
  <user>
    <name>operator</name>
    <account-type>PASSWORD</account-type>
    <password>admin123</password>
    <enabled>true</enabled>
  </user>
  <user>
    <name>observer</name>
    <account-type>PASSWORD</account-type>
    <password>admin123</password>
    <enabled>true</enabled>
  </user>
  <user>
    <name>sssssssssss</name>
    <account-type>PASSWORD</account-type>
    <password>admin123</password>
    <enabled>true</enabled>
  </user>
</users>`

After which I am replacing the same configuration with the below XML
`<users xmlns="urn:o-ran:user-mgmt:1.0">
  <user>
    <name>oranuser</name>
    <account-type>PASSWORD</account-type>
    <password>oranuser</password>
    <enabled>true</enabled>
  </user>
  <user>
    <name>operator</name>
    <account-type>PASSWORD</account-type>
    <password>admin123</password>
    <enabled>true</enabled>
  </user>
  <user>
    <name>observer</name>
    <account-type>PASSWORD</account-type>
    <password>admin123</password>
    <enabled>true</enabled>
  </user>
  <user>
    <name>Sssssssssss</name>
    <account-type>PASSWORD</account-type>
    <password>admin123</password>
    <enabled>true</enabled>
  </user>
</users>`

so instead of sssssssss I am giving Sssssssss so ideally a SR_OP_CREATED and SR_OP_DELETED might be occurring.
But when SR_OP_DELETED is considered and I am using sr_get_items(pvt_data->session, "/o-ran-usermgmt:users/user/name", 0, 0, &user_vals, &user_val_count); I am getting sssssssssss instead of Sssssssss as seen below

ERR (USERMGMT): Operation used2
ERR (USERMGMT): Abey USER0 : oranuser
ERR (USERMGMT): Abey USER : oranuser
ERR (USERMGMT): Abey USER0 : operator
ERR (USERMGMT): Abey USER : operator
ERR (USERMGMT): Abey USER0 : observer
ERR (USERMGMT): Abey USER : observer
ERR (USERMGMT): Abey USER0 : sssssssssss
ERR (USERMGMT): Abey USER : sssssssssss

Here ideally the result should have been as per your last comment like below
ERR (USERMGMT): Operation used2
ERR (USERMGMT): Abey USER0 : oranuser
ERR (USERMGMT): Abey USER : oranuser
ERR (USERMGMT): Abey USER0 : operator
ERR (USERMGMT): Abey USER : operator
ERR (USERMGMT): Abey USER0 : observer
ERR (USERMGMT): Abey USER : observer
ERR (USERMGMT): Abey USER0 : Sssssssssss
ERR (USERMGMT): Abey USER : Sssssssssss

Can you please provide an explanation why this is happening and how I could get the new values i.e the Sssssss

**Comment by michalvasko** [comment]
What *sysrepo* version are you using? I have looked at the code and briefly tested it and it works just like I said, you always get the new values. Actually, what is `pvt_data->session` you have mentioned? You are supposed to use the session provided in the callback, all others will return the old data.

**Comment by Abrahamma97** [comment]
Hi @michalvasko 
I am using v1.4.122 of sysrepo. I shall check the pvt_data->session and revert back. We should be using the session from the call back
