### ISSUE TITLE
Question about mutex recovery

### ISSUE THREAD

**Issue by irfanHaslanded** [sysrepo/sysrepo#2768]
I was wondering if there was a reason why mutex are not attempted to be made `pthread_mutex_consistent` in `sr_rwrelock` and `sr_rwunlock`, but only from `_sr_rwlock`.

If an application discovers a EOWNERDEAD, mutex while attempting unlock/relock, it could make the mutex unrecoverable?

**Comment by michalvasko** [comment]
The idea likely was that in almost all cases the mutex will be abandoned while it is write-locked because for all the other operations it is being held for just a very short time. I suppose it can be added to all the locks but passing the recovery parameters to `sr_rwunlock` will be a pain.

**Comment by michalvasko** [comment]
Was simpler than I though, done.

**Comment by irfanHaslanded** [comment]
Request you to apply on libyang1 as well.

**Comment by michalvasko** [comment]
Fine.
