### ISSUE TITLE
sysrepo compilation with libatomic

### ISSUE THREAD

**Issue by meghna-doshi** [sysrepo/sysrepo#2769]
Hi,
We are observing that after rebasing sysrepo to 2.1.44 version, it is getting compiled with libatomic.so.

Mostly it is due to the following lines added in CMakeLists:

```
check_library_exists(atomic __atomic_fetch_add_4 "" LIBATOMIC)
if(LIBATOMIC)
    target_link_libraries(sysrepo atomic)
endif()

```

The query which we have here is that, due to the inclusion of libatomic, what functional/operational changes would happen in sysrepo compared to previous releases where libatomic was not getting used. 
We might have to run test cases around that area, on our software, to check that nothing is broken.

**Comment by meghna-doshi** [comment]
> it seems to be relevant only for specific architectures that would fail the build otherwise.

Yes this is what happened with us. The server on which we compiled this version, has libatomic installed, so the compilation included libatomic library. So while running the binaries (which we run on another server), we had to copy the libatomic lib also.

So is there some way to disable it, even though libatomic is present on the build server? Is that fine?

**Comment by michalvasko** [comment]
So you are talking about cross-compilation, when on the host platform there is `libatomic` but on the target platform is not? I would expect the host not to link it then but I do not know how it should behave in this situation, I am not able to help you.

**Comment by meghna-doshi** [comment]
Hi Michal,
Just tell me what is clean way of not using libatomic during cross compilation.
Or can we just comment the following from sysrepo/CMakeLists.txt
`
check_library_exists(atomic __atomic_fetch_add_4 "" LIBATOMIC)`

**Comment by meghna-doshi** [comment]
> If your target platform has libatomic, chances are that it contains the full implementation of atomics, and as such, it's a good idea to use that. What is your build host, and what is your target platform? Also, the fact that you're worried about "copying a library manually" sounds strange to me; surely you're using a system which tracks library dependencies (i.e., native packages) or a system which provisions the cross-built binaries (buildroot, yocto, etc), right? Not doing so is, in my professional opinion, a recipe for trouble.

"Copying a library manually" you can ignore this step. Since i was trying some short cut method, i had to copy the library manually. Otherwise build system will take care of packaging the libatomic along with the binaries.

The real concern which we have is, what does libatomic change functionality wise? We havent used much of libatomic operations so wanted to check if you could give some brief on it.

@michalvasko / @jktjkt  can anyone of you help us with this information.

**Comment by michalvasko** [comment]
> The real concern which we have is, what does libatomic change functionality wise?

What do you mean? Atomic operations are used on *sysrepo* quite a lot and that functionality is implemented in `libatomic`, on some systems. It will not work without it (the linking error).

**Comment by meghna-doshi** [comment]
Hi Michal,
Let me try to explain a bit more.
1. Compilation done on Linux redhat server (say server x) On this server libatomic is enabled.
2. Finally s/w is run on a virtual environment, inside Kubernetes containers. 

So now my query is, should we enable libatomic for the sysrepo library or not, since the target platform is not really the same as the server where we compile the software (though both have similar OS).

I think we shouldnt enable libatomic in our s/w but before that wanted to know what would happen to sysrepo code runtime, if atomic operations are not used. 
From your earlier replies appears like sysrepo would work fine without libatomic enabled.

**Comment by michalvasko** [comment]
> So now my query is, should we enable libatomic for the sysrepo library or not, since the target platform is not really the same as the server where we compile the software (though both have similar OS).

I do not know so I have no advice for you. I have no practical experience with cross-compilation.

> From your earlier replies appears like sysrepo would work fine without libatomic enabled.

Not sure how you interpreted it this way but correct functioning of atomic operations is definitely required. But like I said, I am not able to help you.

**Comment by meghna-doshi** [comment]
Ok let me ask in a different way. So what happens to sysrepo functionality if the code is compiled and run on a server which doesnt have libatomic installed?
Does any functionality get impacted due to this?

**Comment by michalvasko** [comment]
> So what happens to sysrepo functionality if the code is compiled and run on a server which doesnt have libatomic installed?

I keep repeating the same thing, I have no idea. In general, when running such a binary, the system should look for all the linked dynamic libraries to solve the references to them and if some is not found, an error is printed (I have seen that many times). But if you successfully run the binary on system that does not have this library, I suppose it gets resolved some other way. I really do not know more.

**Comment by meghna-doshi** [comment]
Hi Michal,
One more query on this. We are observing that in sysrepo build/CMakeCache.txt:
LIBATOMIC:INTERNAL=

even though we see that the libatomic is present on the server: 
-rwxr-xr-x 1 root root 27K Sep 30  2020 /usr/lib64/libatomic.so.1.0.0
lrwxrwxrwx 1 root root  18 Mar 17 16:52 /usr/lib64/libatomic.so.1 -> libatomic.so.1.0.0

Any idea what exactly does the following look for to decide whether libatomic to be included or not:
check_library_exists(atomic __atomic_fetch_add_4 "" LIBATOMIC)
if(LIBATOMIC)
target_link_libraries(sysrepo atomic)
endif()

**Comment by michalvasko** [comment]
You are asking about details of `cmake` functions, look into their documentation. Also, I am missing any actual problem you would need solving.

**Comment by sjd-xlnx** [comment]
@meghna-doshi I came across similar problem with libatomic, and I think I found a solution. See https://github.com/sysrepo/sysrepo/issues/2938.
