### ISSUE TITLE
Create and delete operations on edit-config

### ISSUE THREAD

**Issue by hi-Mr-ye** [sysrepo/sysrepo#2770]
Hi @michalvasko
I performed the create and delete operations on edit-config. How do I know what was done in the function
This is the create message :
![image](https://user-images.githubusercontent.com/90752673/160571753-d21043b0-ad91-48fb-b951-af357e4153b8.png)
This is the delete message:
![image](https://user-images.githubusercontent.com/90752673/160572749-ed878b48-1ed4-4185-9892-9d01a2d854b6.png)
This is the function:
![image](https://user-images.githubusercontent.com/90752673/160573000-51aac283-d2c0-44ee-b6f0-6d04b8df6439.png)

**Comment by michalvasko** [comment]
You can look at this [example](https://github.com/sysrepo/sysrepo/blob/master/examples/application_changes_example.c), all the changes are always printed.
