### ISSUE TITLE
Not able to update  the leaf of uplane through api sr_set_item nor able to fetch leaf value of uplane throgh sr_get item

### ISSUE THREAD

**Issue by abhishekkashyap13114** [sysrepo/sysrepo#2771]
Hi

I am Not able to update  the leaf value for uplane configuration through sr_set_item nor able to fetch leaf value of uplane.conf.yang throgh sr_get item.  But i am able to fetch and set the value of leaf of other yang models like sync.yang etc. through same api.

**Comment by michalvasko** [comment]
Did you check the error and message of the non-working functions?

**Comment by abhishekkashyap13114** [comment]
libyang[0]: Invalid arguments - list without keys (lyd_find_sibling()). I am getting this error while i am doing sr_set_item

**Comment by michalvasko** [comment]
There is a [brief description](https://netopeer.liberouter.org/doc/sysrepo/master/html/index.html#paths) referenced for the `path` parameter, you basically want to use a YANG JSON instance-identifier, lists having all their keys defined.
