### ISSUE TITLE
Question: Does sysrepo supports the file callbacks?

### ISSUE THREAD

**Issue by maksimvuleta** [sysrepo/sysrepo#2772]
At the old Netopeer there was a file callbacks mechanism like this:

  _Structure transapi_file_callbacks provides mapping between specific files
  (e.g. configuration file in /etc/) and the callback function executed when
  the file is modified.
  The structure is empty by default. Add items, as in example, as you need.
 
  Example:
  int example_callback(const char *filepath, xmlDocPtr *edit_config, int *exec) {
      // do the job with changed file content
      // if needed, set edit_config parameter to the edit-config data to be applied
      // if needed, set exec to 1 to perform consequent transapi callbacks
      return 0;
  }
 
  struct transapi_file_callbacks file_clbks = {
      .callbacks_count = 1,
      .callbacks = {
          {.path = "/etc/my_cfg_file", .func = example_callback}
      }
  }_

Is there a similar mechanism at sysrepo?
If yes, how to use it? Where the user manual can be found?

**Comment by michalvasko** [comment]
Yes, there is and the manual can be found, unsurprisingly, in the *sysrepo* project, [here](https://netopeer.liberouter.org/doc/sysrepo/master/html/).

**Comment by maksimvuleta** [comment]
Yes, I know about that user manual. 

It is not clear to me how to subscribe to the file changes? 
Which part of the manual is about it? 
I want my callback triggers when some system file is changed.

**Comment by michalvasko** [comment]
Oh, right, sorry. These callback are not supported but instead there is the option of having a custom datastore plugin that allows you to use the configuration files directly by *sysrepo* and not have the configuration duplicated.

**Comment by maksimvuleta** [comment]
I am not sure I understand you. 

This is what I need.
I have the leaf in the yang defined like this:
     _leaf example {
        config true;
        type boolean;
        ...
       }_
I set that leaf to the _true_ in my NETCONF configuration and do the edit-config. 
This value represents the data defined at the device in the file _/etc/exmple_tool/example_. 
I connected to the device and checked if my value was set to _true_ and got something like this:
_user@ubuntu:~$ cat /etc/exmple_tool/example
true_ 

Then someone changes (without NETCONF) the example value to _false_ and the file is like this:
_user@ubuntu:~$ cat /etc/exmple_tool/example
false_ 

So, in my NETCONF configuration, it will still be the _true_ value, and on the device it is _false_

My idea was to have a file callback subscribed to the _/etc/exmple_tool/example_ so I can somehow update this value in the NETCONF configuration.

**Comment by jktjkt** [comment]
No, you got to write code which implements this.
