### ISSUE TITLE
Possible to add our own *.yang models and perform edit-config operations

### ISSUE THREAD

**Issue by mpet** [sysrepo/sysrepo#2773]
Hi,

I wonder if it is possible to install our models into sysrepo and perform operations on the model.
What do I need to do to be able to do that? Is there any documentation to read about this?
br.
//mike

**Comment by michalvasko** [comment]
That is the very first thing you probably want to do, of course it is possible. Read through the [docs](https://netopeer.liberouter.org/doc/sysrepo/master/html/), linked in the README.

**Comment by mpet** [comment]
Great info!
