### ISSUE TITLE
Retrieving uncomitted data

### ISSUE THREAD

**Issue by syyyr** [sysrepo/sysrepo#2774]
Hi,

one can retrieve if there are some changes prepared via the `sr_has_changes` function. If there are some changes prepared, is there an API to retrieve info about those changes these changes?

Thanks

**Comment by michalvasko** [comment]
No, there is no function for retrieval of these changes. But if you read any data using such a session, all the changes are applied on them.

**Comment by syyyr** [comment]
My usecase is this: in netconf-cli, there is the "get" command. This command is able to retrieve data from various datastores. By default it retrieves them from the operational datastore, so that state data appear in the output. However, this also means that I don't see the uncomitted changes. I would like the user to see both the state and uncomitted data.

**Comment by syyyr** [comment]
As a workaround, I tried reworking my sysrepo accessing to only use editBatch (and save the edits), but then I got stopped by not being able to use multiple sr_edit_batches. :( So, it seems that to be able to get the uncomitted data, I'll a function that retrieves them. I'm fine with making a PR, but I'm not sure whether should copied, or returned to the user as a const lyd_node*. What do you think?

**Comment by michalvasko** [comment]
Alright, I was thinking of adding such a function a long time ago but could not think of a use-case. `const lyd_node *` should probably be returned to avoid redundant copying, it is trivial to then make your own copy.
