### ISSUE TITLE
Efficiency of reading sysrepo-monitoring module

### ISSUE THREAD

**Issue by irfanHaslanded** [sysrepo/sysrepo#2778]
I notice that, when we want to request even a single leaf from sysrepo-monitoring module, it pretty much reads all possible data for this module, and then filters out based on input xpath.

Is it possible to some how lower the burden on the system, by only fetching required data.

For instance, if we only want to monitor pids of change-sub of ietf-interfaces through sysrepo-monitoring, we still end up collecting info for the entirety of this module.

Do you have any ideas how we can optimize this get operation?

**Comment by michalvasko** [comment]
Yes, the data are always completely generated. It should not be too difficult to optimize, could you provide examples of the filters you are using?

**Comment by irfanHaslanded** [comment]
Specifically, fetching info about change_subs of a specific module such as, `/sysrepo-monitoring:sysrepo-state/module[name="ietf-interfaces"]/subscriptions/change-sub//.`, or getting just connection info `/sysrepo-monitoring:sysrepo-state/connection`

**Comment by michalvasko** [comment]
Okay, update *sysrepo* and try again. It was slightly faster even with the default state so the more data were to be generated, the faster it should now be in comparison.

**Comment by irfanHaslanded** [comment]
Request you to patch it to libyang1 as well.

**Comment by michalvasko** [comment]
Fine, although porting over optimizations seems completely pointless.
