### ISSUE TITLE
QUESTION | How libyang communicates with sysrepo

### ISSUE THREAD

**Issue by Abrahamma97** [sysrepo/sysrepo#2779]
Hi @michalvasko,
I wanted some information on how libyang  communicate with the sysrepo?

**Comment by Abrahamma97** [comment]
oh I had meant libyang plugins communicating with sysrepo modules. So if they are not communicating while we use Netopeer2 client and server may I know how a connection is formed between libyang, sysrepo  and libnetconf and netopeer2

**Comment by michalvasko** [comment]
> oh I had meant libyang plugins communicating with sysrepo modules.

That still does not make sense.

> how a connection is formed between libyang, sysrepo and libnetconf and netopeer2

Well, *libyang*, *sysrepo*, and *libnetconf2* are dynamically linked to *netopeer2*. Please ask the question in more detail, I am not able to guess what it is exactly that you want to know.
