### ISSUE TITLE
Sysrepo permissions incorrect after reboot for ietf-netconf-monitoring

### ISSUE THREAD

**Issue by iljatab** [sysrepo/sysrepo#2781]
$ yanglint --version
yanglint 2.0.136
$ sysrepoctl --version
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v2.0.53 (SO v6.4.19)
$ netopeer2-server -V
netopeer2-server 2.0.35
$

Hi Michal,

We are having some issue with sysrepo permissions across sytem restarts.

At a first boot of the device we install `ietf-netconf-monitoring` as:
```
sysrepoctl -i .../ietf-netconf-monitoring@2010-10-04.yang -s ...
sysrepoctl -c ietf-netconf-monitoring -o root -g admin -p 0640
```
It looks installed with correct group and permissions:
```
$ sysrepoctl -l | grep ietf-netconf-monitoring
ietf-netconf-monitoring           | 2010-10-04 | I     | root:admin | 640         |

$ ls -l /etc/sysrepo/data/ietf-netconf-monitoring* /dev/shm/sr_ietf-netconf-monitoring*
-rw-r----- 1 root admin 11 Apr 12 06:48 /dev/shm/sr_ietf-netconf-monitoring.operational
-rw-r----- 1 root admin 11 Apr 12 06:49 /dev/shm/sr_ietf-netconf-monitoring.running
-rw-r----- 1 root admin 11 Apr 12 06:48 /etc/sysrepo/data/ietf-netconf-monitoring.startup
```
And the actual access to operational data works ok for `admin` user:
```
$ id
uid=1000(admin) gid=1000(admin) groups=1000(admin)
$ sysrepocfg -X -m ietf-netconf-monitoring -d operational
... <works just fine> ...
$
```

However after system reboot something goes wrong.

This is still ok:

```
$ sysrepoctl -l | grep ietf-netconf-monitoring
ietf-netconf-monitoring           | 2010-10-04 | I     | root:admin | 640         |
```
And here `running` has incorrect permissions and `operational` disappeared:
```
$ ls -l /etc/sysrepo/data/ietf-netconf-monitoring* /dev/shm/sr_ietf-netconf-monitoring*
-rw------- 1 root root  11 Apr 12 07:24 /dev/shm/sr_ietf-netconf-monitoring.running
-rw-r----- 1 root admin 11 Apr 12 06:48 /etc/sysrepo/data/ietf-netconf-monitoring.startup
```
Data access is not working:
```
$ sysrepocfg -X -m ietf-netconf-monitoring -d operational
[ERR] PLG: LYB DS file: Opening "/dev/shm/sr_ietf-netconf-monitoring.running" failed (Permission denied).
[ERR] Callback "load" of plugin "LYB DS file" for module "ietf-netconf-monitoring" failed.
sysrepocfg error: Getting data failed (System function call failed)
For more details you may try to increase the verbosity up to "-v3".
$ 
```

In the system we are running `netopeer2-server` and also our application to handle sysrepo database changes.
After first reboot we do not install or change installed modules, not calling `sysrepoctl` at all.

Could you please advise, sis we miss something?

Ilja.

**Comment by michalvasko** [comment]
Yes, permissions for non-persistent datastores were not persistent either. Should now be fixed.
