### ISSUE TITLE
List in grouping requires key

### ISSUE THREAD

**Issue by William-Sudletsky** [sysrepo/sysrepo#2783]
Given the follow example yang module:
```
module example2 {
yang-version 1.1;
namespace "urn:exam:ple2";
prefix "ex2";

grouping example-list {
list a-list {
leaf value {
type string;
}
}
}
}
```

sysrepoctrl will give the following error:
```
sysrepoctl -i example2.yang -v3
[INF] Connection 313 created.
[ERR] Missing key in list representing configuration data.
sysrepoctl error: Failed to install module "example2.yang" (libyang error)
[INF] No datastore changes to apply.
```

The grouping in this case is assumed to be configurational data, but that is not necessarily true. The module could be imported by a second and then used in a non-configuration data section. This yang module was able to be installed in Version 2.0.53, but cannot be installed with the latest version.

**Comment by michalvasko** [comment]
It works fine with the latest *libyang* from the `devel` branch.
