### ISSUE TITLE
SYSREPO_REPOSITORY_PATH doesn't work

### ISSUE THREAD

**Issue by bozhiz** [sysrepo/sysrepo#2784]
Version:
the latest devel libyang, libnetconf2, sysrepo, netopeer2 
or
the latest released version libyang (v2.0.164), libnetconf2 (v2.1.7), sysrepo (v2.1.42), netopeer2(v2.1.16),

Compiling:
All with "cmake -DCMAKE_INSTALL_PREFIX:PATH=/tmp/nc-yang .."
sysrepo with additional "-DREPO_PATH=/tmp/nc-yang/sysrepo"

The netopeer2 could run setup.sh successfully and startup data under /tmp/nc-yang/sysrepo/data
Also could add new yang file by sysrepoctl --install ietf-interfaces.yang --search-dirs /tmp/nc-yang/yang

Issue:
When try to install the modules to other place with environment variable SYSREPO_REPOSITORY_PATH, sysrepoctl failed with below error, but ietf-datastores.yang in the search directory.

/tmp/nc-yang/yang $ SYSREPO_REPOSITORY_PATH=/tmp/a /tmp/nc-yang/bin/sysrepoctl --install ietf-interfaces.yang -v3 --search-dirs ./
[ERR] Data model "ietf-datastores@2018-02-14" not found in local searchdirs.
[ERR] Loading "ietf-datastores" module failed.
sysrepoctl error: Failed to connect (libyang error)

**Comment by michalvasko** [comment]
This is quite expected because the SHM files and repository together make the *sysrepo* state. If you change one (repository in this case), the state becomes corrupted, basically, resulting in errors such as the one you see. The idea was to change both `SYSREPO_REPOSITORY_PATH` and `SYSREPO_SHM_PREFIX` to make the whole state consistent again. Even if I wanted to change the behavior somehow, I honestly do not know how.

**Comment by bozhiz** [comment]
Thanks, it works after set SYSREPO_SHM_PREFIX at the same time

**Comment by michalvasko** [comment]
Anything, it is just a unique prefix to differentiate the *sysrepo* instances. You can use `inst1_`, `inst2_` and so on, for example.

**Comment by sukrugorgulu** [comment]
> Anything, it is just a unique prefix to differentiate the _sysrepo_ instances. You can use `inst1_`, `inst2_` and so on, for example.

Sorry for late reply, I couldn't understand what you meant. I don't know where to write SYSREPO_SHM_PREFIX='inst1_'. However I used docker for clean installation, and I have running container now.

**Comment by michalvasko** [comment]
> I don't know where to write SYSREPO_SHM_PREFIX='inst1_'. 

`cmake -DSYSREPO_SHM_PREFIX=inst1_ ..`
