### ISSUE TITLE
time format is +00:00

### ISSUE THREAD

**Issue by hi-Mr-ye** [sysrepo/sysrepo#2788]
Hi @michalvasko
Why is there + 00:00 in the time format.and How do I modify this format
![image](https://user-images.githubusercontent.com/90752673/163795238-a47c5255-f819-4c7a-a401-a3cfcab6d4dc.png)
Change the time format to 2022-04-18T17:00:11Z

**Comment by michalvasko** [comment]
Conforms to the [exact definition](https://datatracker.ietf.org/doc/html/rfc6991#page-11) of `date-and-time`, you cannot modify it.
