### ISSUE TITLE
Data model not found in local searchdirs

### ISSUE THREAD

**Issue by marchest** [sysrepo/sysrepo#2790]
Hi,

I am trying to install my yang files therefore I've used Cmake option as follows **-DREPO_PATH=/etc/sysrepo/yang**

After recompiling and running project I am getting below error

```
[ERR] Data model "ietf-datastores@2018-02-14" not found in local searchdirs. 
[ERR] Loading "ietf-datastores" module failed.
sysrepo-plugind error: Failed to connect (libyang error)
```

Btw I can work with the examples.yang.

Whats the problem here ?

Thanks

**Comment by michalvasko** [comment]
A new message should now tell you, there are old SHM files that expect the repository to contain something but it does not because you have changed it. Simple `make shm_clean` or a reboot should fix it.

**Comment by nanfengnan1** [comment]
> A new message should now tell you, there are old SHM files that expect the repository to contain something but it does not because you have changed it. Simple `make shm_clean` or a reboot should fix it.

what's matter? what's reason?

**Comment by michalvasko** [comment]
You were using a different repository path when the SHM was created than you are using now (it can be changed by an environment variable or simply by reinstalling *sysrepo* with changed repository).

**Comment by nanfengnan1** [comment]
in fact, i build sysrepo source and install in ubuntu docker.
