### ISSUE TITLE
Validation Callback && Transaction Callback

### ISSUE THREAD

**Issue by marchest** [sysrepo/sysrepo#2794]
Hi,

1- I could not see any validation callback mechanism for yang leaf ? Is there any way to achieve that ?

2- Is it possible to make 2 phase commit in sysrepo?

Thanks.

**Comment by michalvasko** [comment]
1. Standard YANG validation is always performed for all the data, but you can also add yours and check changes on `SR_EV_CHANGE` event in a module_change callback.
2. Yes, that is the default behavior, event `SR_EV_CHANGE` followed by `SR_EV_DONE`.

These seems like really basic questions so I would advise you to carefully read through *sysrepo* docs first, information about commit is [here](https://netopeer.liberouter.org/doc/sysrepo/master/html/subs.html#change_subs).
