### ISSUE TITLE
Undefined reference to sr_nacm_apply_changes

### ISSUE THREAD

**Issue by daliang20** [sysrepo/sysrepo#2795]
Hi michalvasko,

The latest released version of the documentation references `sr_nacm_apply_changes`; however, I could not compile while calling `sr_nacm_apply_changes` as there is no such function in the current codebase.  

Below is a code snippet with the problematic function.

```c
#include <sysrepo.h>
#include <sysrepo/netconf_acm.h>

int main() {
    sr_conn_ctx_t* connection = NULL;
    sr_session_ctx_t* session = NULL;
    
    // create sysrepo connection/session & initialize nacm
    sr_connect(0, &connection);
    sr_session_start(connection, SR_DS_RUNNING, &session);
    sr_nacm_init(session, 0, NULL);

    // main.c:(.text+0x61): undefined reference to `sr_nacm_apply_changes'
    // sr_nacm_apply_changes(session, 0);

    // cleanup everything else
    sr_nacm_destroy();
    sr_session_stop(session);
    sr_disconnect(connection);
    return 0;
}
```

**Comment by jktjkt** [comment]
That looks like a leftover after the recent refactoring; there's a function prototype in `.h.`, but the implementation got removed. In the current `devel`, the NACM checking is a per-session opt-in feature. Once you've called `sr_nacm_set_user` on a particular session, all subsequent operations on that session are subject to NACM checks.

**Comment by michalvasko** [comment]
Sorry, completely missed that, I have removed the functions declarations.
