### ISSUE TITLE
how to cleanup all datastore (running, operational, etc)

### ISSUE THREAD

**Issue by fchn289** [sysrepo/sysrepo#2796]
Hi,

is there a simple & fast way to cleanup all data in all datastore?

In UT, when a testcase finished, datastores need to be cleanup so to run next case from scratch.

I found a way - uninstall all yang models & re-install them. It seems works but slow, and in fact it's a workaround.

BR

**Comment by michalvasko** [comment]
In *sysrepo* tests, there are test-exclusive repositories and SHM prefixes used so that the tests are independent of each other. But if I knew what you mean by "cleanup datastores" I think I could help you. Do you just want to set an empty configuration for them?

**Comment by fchn289** [comment]
"cleanup datastores" means to empty datastore (no data but all yang modules still exist).

**Comment by michalvasko** [comment]
So you simply want to set empty configuration. Several ways how to achieve that, `sr_replace_config()` with `src_config` `NULL` should be one of the simplest.

**Comment by myonlystarWang** [comment]
> So you simply want to set empty configuration. Several ways how to achieve that, `sr_replace_config()` with `src_config` `NULL` should be one of the simplest.

Hi michal,
     I get this function now but I wonder if there is a command can be executed in linux command line?

**Comment by michalvasko** [comment]
Yes, you should achieve the same thing with `sysrepocfg -C <file>` with `file` being an empty file.

**Comment by myonlystarWang** [comment]
@michalvasko Thank you so much!

**Comment by michalvasko** [comment]
It can be called at any time but it can 1) time out if another similar operation is being executed preventing getting some locks or 2) crash, which should not happen and should be reported so that I can fix it. Generally, it is similar to `sr_apply_changes()` and needs data locks for the affected datastore/modules.

**Comment by fchn289** [comment]
get it

issue closed

**Comment by gmk-456** [comment]
> Yes, you should achieve the same thing with `sysrepocfg -C <file>` with `file` being an empty file.

Hi Michal,

I was trying to delete the data from sysrepo by using this command sysrepocfg -C _3gpp-common-managed-element.yang -v3
But, it shows sysrepocfg error: Unknown datastore "_3gpp-common-managed-element"

**Comment by michalvasko** [comment]
It is like I said, the `<file>` is supposed to be an **empty file** not a YANG module. If you want to limit the copy to a single module, use another parameter `-m _3gpp-common-managed-element` (and use module name, not the YANG module file).
