### ISSUE TITLE
How can I add a new item to a list with 'leafref' key? 

### ISSUE THREAD

**Issue by woosonchan** [sysrepo/sysrepo#2797]
I have a yang like this: 

```
container my-cont {
    list my-ls {
        key "name";
        leaf name {
            type leafref {
                path "../config/name";
            }
        }
        container config {
            leaf name {
                type string;
            }
        }
    }
}
```

And now there are some items in the list **my-ls**, their names are "a", "b", "c".
Now I want to add a new item with the key "d" into **my-ls**, how to write the `xpath` and which API should I use plz?

I tried to make the xpath like ".../my-cont/my-ls[name='d']" and call `sr_set_item_str(session, xpath, value, NULL, 0)`,
but it return an error:
`libyang[0]: Leafref "../config/name" of value "d" points to a non-existing leaf.`

Can anybody help me? @michalvasko

**Comment by woosonchan** [comment]
Thanks for your reply, Michal

1. The version that I am using is 1.4.70, but I tested the same situation with 2.1.42, they all cause error.
The 2.1.42 outputs:
[ERR] Invalid leafref value "d" - no existing target instance "../config/name".
[ERR] Validation failed.

2. I saw my outputs after the statement of `sr_set_item_str()`, so I think the errors were printed by `sr_apply_changes()`

**Comment by michalvasko** [comment]
Okay, then it seems correct, did the leafref target exist? Do you understand how [leafref](https://www.rfc-editor.org/rfc/rfc7950.html#section-9.9) works?

**Comment by woosonchan** [comment]
I think the leafref is a reference, like the concept of pointer in C language.
I know the leafref target doesn't exist, because it is part of my new item. For the list, is there any solutions to append a new item with the leafref in it?

**Comment by michalvasko** [comment]
Yes, you should be able to call `sr_set_item_str()` several times until you create valid data where for every leafref its target also exists. When you then call `sr_apply_changes()`, it should successfully validate.

**Comment by woosonchan** [comment]
It works!!! Thank you Michal~
