### ISSUE TITLE
`sr_nacm_init` with multiple sessions

### ISSUE THREAD

**Issue by daliang20** [sysrepo/sysrepo#2799]
I am trying to initialize the the nacm for multiple sessions, but the second call to `sr_nacm_init` returns error code 1.

Question: **Is it possible to have multiple sessions with the nacm initialized?**

I also have tried this in a separate process (another sysrepo plugin) and the second call to `sr_nacm_init` returns an error code. I have tried this on both the `master` and `devel` branch.

Note: I've also noticed that `sr_nacm_destroy` does not take any session arguments. Is this intentional? 

Below is a code snippet that I have tried.
```c
#include <stdio.h>
#include <sysrepo.h>
#include <sysrepo/netconf_acm.h>

int main() {
    sr_conn_ctx_t* connection = NULL;
    sr_connect(0, &connection);

    // create sysrepo connection/session & initialize nacm
    sr_session_ctx_t* session1 = NULL;
    sr_subscription_ctx_t* subscription1 = NULL;
    sr_session_start(connection, SR_DS_RUNNING, &session1);
    int rc = sr_nacm_init(session1, 0, &subscription1);

    if (rc != SR_ERR_OK) {
        printf("Failed to intialize nacm for session 1\n");
    }
    
    // NOTE: unsubscribing from subscription 1 allowed the nacm to be initialized again
    // sr_unsubscribe(subscription1);

    sr_session_ctx_t* session2 = NULL;
    sr_subscription_ctx_t* subscription2 = NULL;
    sr_session_start(connection, SR_DS_RUNNING, &session2);
    rc = sr_nacm_init(session2, 0, &subscription2);

    if (rc != SR_ERR_OK) {
        printf("Failed to intialize nacm for session 2\n");
    }

    // cleanup everything else
    sr_nacm_destroy();
    sr_session_stop(session1);
    sr_session_stop(session2);
    sr_disconnect(connection);
    return 0;
}
```

**Comment by michalvasko** [comment]
Right, there was some missing information in the documentation of the functions, please look at it now and let me know if there is still something unclear.

**Comment by daliang20** [comment]
The documentation look good to me. I think they make sense
