### ISSUE TITLE
get operation with subtree-filter

### ISSUE THREAD

**Issue by siprab** [sysrepo/sysrepo#2801]
Hi, 

For a yang module edit-config for an attribute is done and then while doing get operation with subtree filter the value of the attribute is not reflecting back. However the value returns back with xpath filter.

**Comment by michalvasko** [comment]
That sounds rather strange, could you provide the exact data with the attribute and the requests with their replies?

**Comment by siprab** [comment]
Hi Michal, 

We tried the below steps: 
1. Installed the yang modules ([modules.zip](https://github.com/sysrepo/sysrepo/files/8588630/modules.zip)) and started the netconf-server and application. 

2. performed the edit-config for the attribute "bSChannelBwDL" in _3gpp-nr-nrm-nrcelldu.yang

3. We tried get and get-data with both xpath filter and subtree filter. 

4. For get with xpath and subtree below are the outputs, in which the value of attribute bSChannelBwDL is reflecting properly 
  
  `> get --filter-xpath /_3gpp-common-managed-element:ManagedElement[id]/_3gpp-nr-nrm-gnbdufunction:GNBDUFunction[id]/_3gpp-nr-nrm-nrcelldu:NRCellDU
DATA
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <ManagedElement xmlns="urn:3gpp:sa5:_3gpp-common-managed-element" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="create">
    <id>1</id>
    <GNBDUFunction xmlns="urn:3gpp:sa5:_3gpp-nr-nrm-gnbdufunction">
      <id>GNBDUFunction</id>
      <NRCellDU xmlns="urn:3gpp:sa5:_3gpp-nr-nrm-nrcelldu">
        <id>cellindex_1</id>
        <attributes>
          <bSChannelBwDL>20</bSChannelBwDL>
        </attributes>
      </NRCellDU>
    </GNBDUFunction>
  </ManagedElement>
</data>

> get --filter-subtree=GPV.xml
DATA
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <ManagedElement xmlns="urn:3gpp:sa5:_3gpp-common-managed-element" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="create">
    <id>1</id>
    <GNBDUFunction xmlns="urn:3gpp:sa5:_3gpp-nr-nrm-gnbdufunction">
      <id>GNBDUFunction</id>
      <NRCellDU xmlns="urn:3gpp:sa5:_3gpp-nr-nrm-nrcelldu">
        <id>cellindex_1</id>
        <attributes>
          <bSChannelBwDL>20</bSChannelBwDL>
        </attributes>
      </NRCellDU>
    </GNBDUFunction>
  </ManagedElement>
</data>`

5. For get-data with xpath below is the output and it also reflects the value of attribute bSChannelBwDL.                                         

`> get-data --datastore=running --filter-xpath /_3gpp-common-managed-element:ManagedElement[id]/_3gpp-nr-nrm-gnbdufunction:GNBDUFunction[id]/_3gpp
DATA
<data xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-nmda">
  <ManagedElement xmlns="urn:3gpp:sa5:_3gpp-common-managed-element" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="create">
    <id>1</id>
    <GNBDUFunction xmlns="urn:3gpp:sa5:_3gpp-nr-nrm-gnbdufunction">
      <id>GNBDUFunction</id>
      <NRCellDU xmlns="urn:3gpp:sa5:_3gpp-nr-nrm-nrcelldu">
        <id>cellindex_1</id>
        <attributes>
          <bSChannelBwDL>20</bSChannelBwDL>
        </attributes>
      </NRCellDU>
    </GNBDUFunction>
  </ManagedElement>
</data>`

6. However for get-data with subtree filter for both running and operational datastore the value of attribute "bSChannelBwDL" is not reflecting back. 

`> get-data --datastore=running --filter-subtree=GPV.xml
DATA
<data xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-nmda">
  <ManagedElement xmlns="urn:3gpp:sa5:_3gpp-common-managed-element" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="create">
    <id>1</id>
    <GNBDUFunction xmlns="urn:3gpp:sa5:_3gpp-nr-nrm-gnbdufunction">
      <id>GNBDUFunction</id>
      <NRCellDU xmlns="urn:3gpp:sa5:_3gpp-nr-nrm-nrcelldu">
        <id>cellindex_1</id>
      </NRCellDU>
    </GNBDUFunction>
  </ManagedElement>
</data>`

please find the zip for xml file ([GPV.zip(https://github.com/sysrepo/sysrepo/files/8588772/GPV.zip)) used for subtree filter. 

Thanks!

**Comment by michalvasko** [comment]
Alright, seems some redundant filtering was being done and after it was removed it seems to work.
