### ISSUE TITLE
Segmentation Fault during SNMP operation

### ISSUE THREAD

**Issue by nullromo** [sysrepo/sysrepo#2803]
We use [Agent++](https://agentpp.com/) to build an SNMP server and we integrate that with sysrepo. This way, users can have their choice of SNMP and NETCONF.

Most parts are working, but getting data out of the operational datastore during an Agent++ callback fails with a segmentation fault that we are unable to diagnose.

**[This repository](https://github.com/nullromo/sysrepo-snmp-segfault-example)** contains a minimal example that demonstrates the bug.

If you follow the steps in the README and take a look at the code, you will see that the SNMP server first calls the `fullLifecycleDataGet()` function, and it works. This function connects to sysrepo, creates a session, gets data, and cleans up the session and connection. After testing that function, the SNMP server goes into a loop and waits for requests. When a request is received, it tries to run the `fullLifecycleDataGet()` function again, only this time it fails with a segfault.

As far as I can tell, the usage of the sysrepo library is correct in the code, so I believe this may be a bug with sysrepo itself. The only thing that I can see that is different between the working call and the failing call is that they may run in different threads. However, this should be okay due to the fact that no `sr_session_ctx_t` or `sr_conn_ctx_t` objects are being shared between the threads.

I understand that requesting help when using a third party library is asking a lot. However, I would venture a guess that we are not the only sysrepo users who are also using Agent++. If you could take a look at this, it would help us greatly and it may lead to a bigfix in sysrepo.

**Comment by daliang20** [comment]
> . I have not looked into Agent++ code for any explanation and cannot really think of any unless some process magic is happening in that library.

This got me thinking about the Agent++ source code. After some digging, I found out that Agent++ set a hardcoded stack size for each thread. Our thread went over the stack size causing an inexplicable segmentation fault during a sysrepo/libyang function call. This made us believe it may have been an issue with sysrepo.

I recreated a scenario in the example code but it only calls `fullLifecycleDataGet()` once during the main code and once during each thread. Running `./build/example-just-threading -s 0x12000` with the plugin running prints out the operational data inside the thread while running `./build/example-just-threading` causes a segmentation fault.  

Overall, this was not a bug with sysrepo. 
Thanks for pushing us in the right direction.
