### ISSUE TITLE
Oper callback called when retrieving config true sibling

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2804]
Hi!

I have a question regarding the oper callback behavior in sysrepo.

Using the `sr_get_subtree()` function to retrieve a leaf will trigger the
oper callback of a config false sibling.

Granted, this only appears when I add the `//.` to the end of the `path`
parameter. Sysrepo doesn't return with the sibling oper data, but still
invokes the callback.

I have a simple example:
Console 1:
`./application_changes_example test`

Console 2:
`./oper_data_pull_example test /test:basics/fraction`

Console3:
```
./get_subtree /test:basics/scalar//.
buf:
<scalar xmlns="urn:com:test">233</scalar>
```

Console 2 after get:
 ```
========== DATA FOR "test" "/test:basics/fraction" REQUESTED =======================

Request xpath: /test:basics/scalar//.
buf:
<basics xmlns="urn:com:test">
  <fraction>22.3</fraction>
</basics>
```

Why does the fraction oper callback get called? Seems unnecessary.
I attached the example source.
[oper_cb.tar.gz](https://github.com/sysrepo/sysrepo/files/8589991/oper_cb.tar.gz)

I'm using the latest devel versions of libyang and sysrepo.

Thanks!

**Comment by michalvasko** [comment]
Yes, the text-based processor in *sysrepo* is not able to handle any XPath expression and if it encounters something unknown, it gives up and all the operational data for the module are retrieved. This particular case could be supported without that much trouble, I think, but I do not really see the point. If for `sr_get_subtree()` an expression is used that selects subtrees, I would say making the retrieval inefficient is perfectly fine. Only reasonable and most common expressions are currently optimized.
