### ISSUE TITLE
Is there a way to be notified by someone subscribing to notifications from module?

### ISSUE THREAD

**Issue by AeroFlorian** [sysrepo/sysrepo#2807]
I have a supervision module, and I would like to be able to see if someone is subscribed to notifications coming from this module.
I checked the documentation and could not find if I could be able to.
Is there a way to "subscribe" to subscription on some module with sysrepo?

Thanks

**Comment by michalvasko** [comment]
> Is there a way to "subscribe" to subscription on some module with sysrepo?

Um, no. But you can see the current state and all the subscriptions in `operational` data of `sysrepo-monitoring` module.

**Comment by AeroFlorian** [comment]
Thanks a lot! Will create a watcher on this data
