### ISSUE TITLE
operational datastore initialization

### ISSUE THREAD

**Issue by fbergamelli** [sysrepo/sysrepo#2809]
Hello guys ! I'm pretty new to sysrepo. As far as I've understood I can provide an xml file to be used as startup configuration for the running datastore.

Is it possible to accomplish the same thing also for the operational datastore ? I have some leafs that are read only and their values are really static (they never changes and they can't be changed). So I would like to set them up with a xml file instead of using callbacks.

thanks

F

**Comment by michalvasko** [comment]
You cannot directly set it the same way but something similar is possible. Read the [docs](https://netopeer.liberouter.org/doc/sysrepo/devel/html/index.html#oper_data) for details.

**Comment by fbergamelli** [comment]
thanks !
