### ISSUE TITLE
When application sub a module only with argument parameters ,it failed at first time of the application start up ,when the application start again it success.

### ISSUE THREAD

**Issue by ZhaoGuangYue** [sysrepo/sysrepo#281]
When application sub a module only with argument parameters ,it failed at first time of the application start up ,when the application start again it success.

**the reason of this issue may be:**
when we use sysrepoctl to install a module only with argument parameters, it does not generate ".startup" file. And when application sub this module, we will create the module socket ,before we create it we will  check if the module's subscriptions socket dir can be access( subscriptions dir path like: "/tmp/sysrepo-subscriptions/ModuleManagedElement/").  if it can't, we will make the dir and  set the dir permission by module's data ".startup" file permission, as the "startup" file does not exist, we failed to get the data file permission, so we create the module socket failed, and the sub failed.

**some questions**
1. the data ".startup" file of the module only with argument parameters should be create when install?
2. as the application does not know the reason of the module can not be sub  is cause by argument or other problem, so if we should offer a way for app to judge?
3. i think if we use "sr_set_socket_dir_permissions" failed , we should remove the dir.in the function "cl_sm_get_server_socket_filename" 
`    if (-1 == access(path, F_OK)) {
        old_umask = umask(0);
        ret = mkdir(path, S_IRWXU | S_IRWXG | S_IRWXO);
        umask(old_umask);
        CHECK_ZERO_LOG_RETURN(ret, SR_ERR_INTERNAL, "Unable to create the directory '%s': %s", path, sr_strerror_safe(errno));
        rc = sr_set_socket_dir_permissions(path, module_name, false);
        CHECK_RC_LOG_RETURN(rc, "Unable to set socket directory permissions for '%s'.", path);
    }`

example module of this issue
```
module Root {
  namespace "urn:ietf:params:xml:ns:yang:zte:Root";
  prefix Root;

  container Root {
    presence "real Me";
    leaf RootId {
      type int32;
    }
  }
}
```

```
module ArgumentModule {
  namespace "urn:ietf:params:xml:ns:yang:fox:ArgumentModule";
  prefix ArgumentModule;
  import Root{
    prefix Root;
  }
  
  augment "/Root:Root"{
    container ArgumentModule {
	  presence "ArgumentModule";
      leaf Id {
        type int32;
      }
    }
  } 
}
```

**Comment by lukasmacko** [comment]
Hi,

- .startup file is created only for models that contain a data (container, list, leaf-list, leaf nodes). If a model contains only augments or typedef statement .startup is not created. Since data of augment is stored in target module  .startup file is not needed for module containing only augments.

- in this particular example ArgumentModule data is stored in Root.startup

- if you want to subscribe for notification in ArgumentModule you should use xpath like this:
`/Root:Root/ArgumentModule:ArgumentModule`

Regards,
Lukas

**Comment by ZhaoGuangYue** [comment]
And 
1. how can we check if the module can be directly subed?

2. if we use "sr_set_socket_dir_permissions" failed , we should remove the dir in the function "cl_sm_get_server_socket_filename" .as it will cause the first time fail,the second time successs.

**Comment by ZhaoGuangYue** [comment]
And 
1. how can we check if the module can be directly subed?
2. if we use "sr_set_socket_dir_permissions" failed , we should remove the dir in the function "cl_sm_get_server_socket_filename" .as it will cause the first time fail,the second time successs.

**Comment by rastislavszabo** [comment]
Hi,

1. you can subscribe to the module only if it contains some data to be subscribed for - container, list, leaf-list or leaf nodes that are not in an augment.

2. Probably yes, it does not have any side effects, but it is not consistent (it should always fail).

**Comment by ZhaoGuangYue** [comment]
in my opinion , the application and sysrepoctl should depend on  common interface,and it is better to  decouple their relationship, so it is not a good idea to let the application to use "sysrepoctl -l" to query the permissions
thanks

**Comment by rastislavszabo** [comment]
The application should be aware of their YANG model, so there is definitely no need for the application to query sysrepoctl. sysrepoctl is just a tool for administrators and one can use it to check whether the model contains some data or not if they are too lazy to look into the YANG model.

**Comment by ZhaoGuangYue** [comment]
1.there is more than one module to sub. 
2.the people who define  modules and  the application coder are in different teams, so it is not clever to let coder to know all module contents.
