### ISSUE TITLE
Storing empty string xpath = "" for change subscription

### ISSUE THREAD

**Issue by irfanHaslanded** [sysrepo/sysrepo#2811]
I have a question about storing an empty xpath = "".

In `sr_shmext_change_sub_add`, Is it okay to store an empty string "", as NULL, and not have to store it in the shm?

```c

    /* allocate new subscription and its xpath, if any */
    if ((err_info = sr_shmrealloc_add(&conn->ext_shm, &shm_mod->change_sub[ds].subs, &shm_mod->change_sub[ds].sub_count,
            0, sizeof *shm_sub, -1, (void **)&shm_sub, xpath ? sr_strshmlen(xpath) : 0, &xpath_off))) {
        goto cleanup_changesub_ext_unlock;
    }

    /* fill new subscription */
    if (xpath) {
        strcpy(conn->ext_shm.addr + xpath_off, xpath);
        shm_sub->xpath = xpath_off;
    } else {
        shm_sub->xpath = 0;
    }
```

**Comment by michalvasko** [comment]
I do not think `xpath` can be `""` in `sr_shmext_change_sub_add`, do you have a use-case for it? Are you maybe talking about `libyang1` version? I have not checked that one.

**Comment by irfanHaslanded** [comment]
I was under the impression that `xpath = ""`, `xpath = NULL`, `xpath = "/"` are all equivalent for libyang/sysrepo. I didn't know if there's a difference between libyang1 vs libyang2. My question is specific to libyang1.

So, `xpath = ""` should never be passed to sysrepo as it is an invalid xpath?

**Comment by michalvasko** [comment]
`""` is considered invalid and should print an unexpected EOF error, `NULL` is valid - no xpath, and `"/"` should select the virtual XPath root. The last one should also be valid and perhaps even work the way you described but I would be extra careful and not use it.
