### ISSUE TITLE
ly_cxt_new: Can't set LY_CTX_SET_PRIV_PARSED option

### ISSUE THREAD

**Issue by jeanseb6wind** [sysrepo/sysrepo#2812]
Hello, I'm working on the `sysrepo-python` wrapper with libyang2 support.
The `libyang-python` wrapper has been updated and now supports libyang2. However, the `libyang-python` wrapper waits for the option `LY_CTX_SET_PRIV_PARSED` to be passed to `ly_ctx_new`.

It's mandatory for this wrapper because lot of features use the parsed schema internally.

Would you be able to add an option when creating the connection which allows to pass the `LY_CTX_SET_PRIV_PARSED` option ?

Thanks,

**Comment by jeanseb6wind** [comment]
Hello @michalvasko, a polite ping because the sysrepo-python wrapper PR is locked because of this currently.
https://github.com/sysrepo/sysrepo-python/pull/28

**Comment by michalvasko** [comment]
I had been already looking at this but I first had to solve other issues. Option added, should not cause any problems.

**Comment by jeanseb6wind** [comment]
Amazing, thanks a lot !
