### ISSUE TITLE
No data is returned from the get operation

### ISSUE THREAD

**Issue by hi-Mr-ye** [sysrepo/sysrepo#2815]
Hi @michalvasko
I use netopeer2 - cli to perform the get operation ,but no data is returned.
![image](https://user-images.githubusercontent.com/90752673/168205078-59a1e021-09ca-48ba-9628-c01c26cfcde6.png)

I use sysrepocfg to query, and data was returned
![image](https://user-images.githubusercontent.com/90752673/168205108-84876ea1-bca0-48c7-adda-1a5f0edd36a4.png)

but why?

**Comment by michalvasko** [comment]
Try XPath filter `/stu-test:test-points`.

**Comment by hi-Mr-ye** [comment]
![image](https://user-images.githubusercontent.com/90752673/168234311-f5e2680c-de4d-4e69-8698-21da09a75639.png)

Thank you for your reply. But the situation is the same.

**Comment by michalvasko** [comment]
That is quite strange, what *netopeer2*/*sysrepo* versions are you using? Can you try `get-data --datastore operational --filter-xpath /stu-test:test-points`?

**Comment by hi-Mr-ye** [comment]
How do I view netopeer2/ sysrepo versions?
![image](https://user-images.githubusercontent.com/90752673/168237308-8070628e-b8fe-41dd-a077-41261e3485c0.png)

get-data is ok. but Why can't get?What's the difference?

**Comment by michalvasko** [comment]
> How do I view netopeer2/ sysrepo versions?

`netopeer2-server -V` and `sysrepoctl -V`.

> get-data is ok. but Why can't get?What's the difference?

In this case there should be no difference, I just wanted to check. There seems to be a problem but in case you are using old versions, it is expected.

**Comment by hi-Mr-ye** [comment]
This is the version I use
![image](https://user-images.githubusercontent.com/90752673/168240853-89f912a5-33aa-4066-9807-8bb9c903b77a.png)
What is the latest version?

**Comment by hi-Mr-ye** [comment]
thanks! But Why can others get data? such as:
![image](https://user-images.githubusercontent.com/90752673/168251871-867e04f9-8574-48a0-92be-f473eff9be33.png)

no data is returned:
![image](https://user-images.githubusercontent.com/90752673/168253638-3b848e7b-7a3a-4073-89f1-a58f5b34f86c.png)

Why are there two different situations?

**Comment by michalvasko** [comment]
An important question, `point` is a `config` `true` or `false` node? And what do you mean different situations, it all depends on the data of the particular module, all situations are different.

**Comment by hi-Mr-ye** [comment]
point is a config false mode. 

The same sysrepo version, the same get operation. Why do some return null data, while others can query data?
Is it the Yang node?
> And what do you mean different situations

**Comment by michalvasko** [comment]
> point is a config false mode.

Okay, then I really think the problem is caused by some bug in the unfinished version you are using. Not sure what to answer to your other question since I still do not really understand them. But if you use a recent version, your problems should be gone.

**Comment by hi-Mr-ye** [comment]
Hi @michalvasko
This is the version I use for netopeer2/sysrepo. Is it up to date?
![image](https://user-images.githubusercontent.com/90752673/169810923-232829f2-aa42-4d8e-b9f5-8c6003238e3f.png)

**Comment by michalvasko** [comment]
Yes, these version are current.

**Comment by michalvasko** [comment]
To reproduce it I will need much more details. Can you attach the YANG `stu-test`? How exactly are you setting the operational data that you retrieve with `get-data` or by `sysrepocfg`?
