### ISSUE TITLE
sysrepoctl --change --permissions does not modify filesystem permissions

### ISSUE THREAD

**Issue by peckato1** [sysrepo/sysrepo#2819]
Hi,

I am using sysrepo configured with `SYSREPO_UMASK=0007` and `SYSREPO_GROUP=sysrepo`. When I install a yang model, sysrepoctl reports `600` permissions which is consistent with file permissions of the file in shm. However, when I change the permissions to `644` via `sysrepoctl --change --permissions 0644`, sysrepo states the permissions are 644 but the filesystem permissions seem to be unaffected.

```
$ LC_ALL="C" id
uid=1000(tomas) gid=1000(tomas) groups=(...),1001(sysrepo)

$ sysrepoctl -i velia/yang/ietf-interfaces@2018-02-20.yang

$ sysrepoctl -l
Module Name                | Revision   | Flags | Owner         | Startup Perms | Submodules | Features
-------------------------------------------------------------------------------------------------------
(...)
ietf-interfaces            | 2018-02-20 | I     | tomas:sysrepo | 600           |            |         
(...)

$ ls -la /dev/shm/*ietf-interfaces*
-rw------- 1 tomas sysrepo 60 18. kvě 19.22 /dev/shm/sr_ietf-interfaces.running

$ sysrepoctl -c ietf-interfaces --permissions 0644

$ ls -la /dev/shm/*ietf-interfaces*
-rw------- 1 tomas sysrepo 60 18. kvě 19.22 /dev/shm/sr_ietf-interfaces.running

$ sysrepoctl -l
Module Name                | Revision   | Flags | Owner         | Startup Perms | Submodules | Features
-------------------------------------------------------------------------------------------------------
ietf-interfaces            | 2018-02-20 | I     | tomas:sysrepo | 644           |            |         
(...)

$ ls -la /dev/shm/*ietf-interfaces*
-rw------- 1 tomas sysrepo 60 18. kvě 19.22 /dev/shm/sr_ietf-interfaces.running
```

If `--permissions` is passed to `sysrepoctl --install` then the file permissions seem to in sync:

```
$ sysrepoctl -i velia/yang/ietf-interfaces@2018-02-20.yang --permissions 0644

$ sysrepoctl -l
(...)
ietf-interfaces            | 2018-02-20 | I     | tomas:sysrepo | 640           |            |         
(...)

$ ls -la /dev/shm/*ietf-interfaces*
-rw-r----- 1 tomas sysrepo 60 18. kvě 19.24 /dev/shm/sr_ietf-interfaces.running
```

sysrepo commit `8842da410798e44e554c981e029a17c03b0cfae7`

**Comment by michalvasko** [comment]
Technically, `sysrepoctl` output is correct because it prints the `startup` permissions, which were the only ones being correctly changed. Fixed for the volatile datastores, caused by some recent changes.

**Comment by peckato1** [comment]
Hi, thanks, I can confirm that file permissions after running `sysrepoctl --change --permission` are now correct.

However, I have noticed that for the model we are installing with 664 permissions the permissions for operational and running datastore differ. When I push something to operational datastore then the lyb file is created with the default permissions 660. Is this expected behaviour? Shouldn't new files follow permissions stated by `sysrepoctl --change`?

```
ROADM-LINE-SDN-ID210516 ~ # ls -la /run/sysrepo/sr_*roadm*
-rw-rw----    1 root     sysrepo      40132 May 19 07:53 /run/sysrepo/sr_czechlight-roadm-device.operational
-rw-rw-r--    1 root     sysrepo       9078 May 19 07:34 /run/sysrepo/sr_czechlight-roadm-device.running
```

**Comment by michalvasko** [comment]
I think this is mostly working correctly and the confusion will probably be caused by your `SYSREPO_UMASK=0007`, which is preventing `o` permissions on the `operational` file. I am not sure what the desired behavior should be but I suppose to ignore `SYSREPO_UMASK` for datastore files, right? In that case I will have to modify the docs a bit, too.

**Comment by peckato1** [comment]
I was discussing this with @jktjkt  and it turns out it works as indented for our use-case. I had made an error while adapting to new changes.

However, we were discussing whether sysrepo should prevent (or at least warn) user when changing permissions/group of the module that go against defined values in `SYSREPO_GROUP`/`SYSREPO_UMASK` like I did in the example above where I compiled with `SYSREPO_UMASK=0007` and tried to change permissions of the module to `0664` which go against the defined umask. Then stuff happened and we saw that newly created files are again created with 0660 which can be misleading a bit.

**Comment by michalvasko** [comment]
So what was your conclusion? I would say now that preventing to set access disabled by `SYSREPO_UMASK` is reasonable. Either an error could be returned or a warning while `SYSREPO_UMASK` overrides the explicit permissions so they do not set the forbidden bits.

**Comment by peckato1** [comment]
Well we kind-of agreed that preventing such action would be reasonable, if you agree.

**Comment by jktjkt** [comment]
Can you please also have the `--group` option to `sysrepoctl` trigger a warning if used along with `SYSREPO_GROUP` (or if the resulting UIDs are different)?
