### ISSUE TITLE
Operational data updation using sr_set_item_str failing if i try more than once

### ISSUE THREAD

**Issue by chendrashekarp** [sysrepo/sysrepo#2825]
Hi @michalvasko , if i am subscribing for operational data of a module using sr_oper_get_items_subscribe with      SR_SUBSCR_CTX_REUSE .
and try to set ro data using sr_set_item_str (operational data-store) is working only once , if i am trying to update the value more than once with different different values it is not working.

tried to use all the flags for 
sr_oper_get_items_subscribe this API. if i am not using sr_oper_get_items_subscribe on that particular module , then the updation is working fine .

Could you please help me with this

**Comment by michalvasko** [comment]
> ...it is not working

That is a really bad description of a problem.

What exactly are you doing, calling `sr_set_item_str()` in the callback set by `sr_oper_get_items_subscribe()`?

**Comment by chendrashekarp** [comment]
No , **sr_set_item_str** is completely independent (**i am trying to update data based on some run time operations** using **sr_set_item_str**). in call back of (**sr_oper_get_items_subscribe()**) i am doing this 
lyd_parse_data_mem((struct ly_ctx *)sr_get_context(oran_srv.sr_conn),buff,LYD_XML,0,LYD_VALIDATE_PRESENT,parent);

**Comment by michalvasko** [comment]
Okay, so please describe what exactly is happening and what do you think should happen instead. Saying it is not working does not help me.

**Comment by chendrashekarp** [comment]
Hi @michalvasko , if i am doing **sr_oper_get_items_subscribe()**  on a particular module , and i am trying to update a ro filed of the same yang module using sr_set_item_str , the updation is happening only once, if i am trying to update the same filed with another value , this new updation is not reflecting in sysrepo but i am not getting any error too

**Comment by michalvasko** [comment]
Still not detailed enough. Include the exact call of `sr_oper_get_items_subscribe()` and `sr_set_item_str()`. The data you see, both correct and incorrect, may also be helpful.

**Comment by michalvasko** [comment]
Either you will start mentioning some details or I will not help you because I cannot. What is `path_container` and `xpath-ro`? A bunch of variable names are really useless.

**Comment by chendrashekarp** [comment]
Hi @michalvasko ,
**path_container:** /o-ran-fan:fan-tray 
**module->name:** o-ran-fan 
**buff:** 
```
<fan-tray xmlns="urn:o-ran:fan:1.0">
    <fan-state>
      <name>oran</name>
      <present-and-operating>false</present-and-operating>
    </fan-state>
  </fan-tray>
```

xpath-ro : /o-ran-fan:fan-tray/fan-state[name='oran']/present-and-operating

and i am trying to change this value to true using sr_set_item , which is not happening

**Comment by michalvasko** [comment]
Okay, we are slowly getting somewhere. Now please describe the behavior exactly. You set the callback, you get the expected data. Then you set `push` oper data and you still get the expected value. Then you do something else and no longer get the expected value?

**Comment by chendrashekarp** [comment]
Hi @michalvasko  , 
After  `push` operation , i am  trying to update the value using sr_set_item_str , this update is not reflecting in sysrepo.
sysrepo still contains the old data.

**Comment by michalvasko** [comment]
Okay, so you first do `sr_set_item_str()` on `/o-ran-fan:fan-tray/fan-state[name='oran']/present-and-operating` with value `true` and even read it back. Then, you call the function with the same path but `false` but you read back data where the value is `true`? I assume the datastore of the session you are using for these calls is `SR_DS_OPERATIONAL`.

**Comment by chendrashekarp** [comment]
cam to conclusion what i am doing
