### ISSUE TITLE
Sending notification triggers operational get callback

### ISSUE THREAD

**Issue by pwang111** [sysrepo/sysrepo#2826]
Michal:

We are using the following latest netopeer2 SDK versions:

Netopeer2: 2.1.16
libyang: 2.0.164
libnetconf2: 2.1.7
sysrepo: 2.1.42

We have a CLI triggered event to call sr_notif_send_tree() to send notification. This triggers an operational get callback which is subscribed to a close-related xpath. Here are the details:

```
sr_notif_send_tree() notif:

xpath: /ietf-interfaces:interfaces-state/interface[name='CT-1']/bbf-xpon:channel-termination/bbf-xpon-onu-state:onu-presence-state-change
```
The following operational get callback is subscribed through sr_oper_get_subscribe():

```
module: ietf-interfaces
xpath: /ietf-interfaces:interfaces-state/interface
```

The callback basically sets xpath=/ietf-interfaces:interfaces-state/interface[name='CT-1']/ subtree values with nc_ly_sub_value_add(), such as 'admin-status', 'oper-status', etc.

Not sure why sending a notification would trigger the operational get callback just because their xpath is closely related, as these two operations are very different.

In addition, we are hitting the following errors when the number of notifications reaches to around 23:

[3850901: I SYSREPO             ] Processing "ietf-interfaces" "operational" event with ID 62.
[3850902: E SYSREPO             ] Recursive reader limit 255 reached!
[3850902: E SYSREPO             ] Recursive reader limit 255 reached!
[3850902: E SYSREPO             ] Recursive reader limit 255 reached!
[3850902: E SYSREPO             ] Recursive reader limit 255 reached!
[3850902: E SYSREPO             ] Recursive reader limit 255 reached!
[3850902: E SYSREPO             ] Recursive reader limit 255 reached!
[3850902: E SYSREPO             ] Recursive reader limit 255 reached!
[3850902: E SYSREPO             ] Recursive reader limit 255 reached!
[3850902: E SYSREPO             ] Recursive reader limit 255 reached!
[3850902: E SYSREPO             ] Recursive reader limit 255 reached!
[3850902: E SYSREPO             ] Recursive reader limit 255 reached!
[3850902: E SYSREPO             ] Recursive reader limit 255 reached!
[3850902: E SYSREPO             ] Recursive reader limit 255 reached!
[3850902: E SYSREPO             ] Recursive reader limit 255 reached!
[3850902: E SYSREPO             ] Recursive reader limit 255 reached!
[3850902: E SYSREPO             ] Recursive reader limit 255 reached!
[3850902: I SYSREPO             ] Successful processing of "operational" event with ID 62.

Seems this does not affect sending additional notifications and triggering oper gets. Note that we use the same sr_session_ctx_t for send notifications and oper get callbacks.

**Comment by jktjkt** [comment]
When an application generates a notification, the notification is validated against the content of the `operational` DS. For that, you need the content of that DS, and that means invoking the pull operational callbacks.

**Comment by michalvasko** [comment]
The reader limit will most likely be caused by some missing unlock because of invalid use of a session or something like that. I would need to see the source code to tell you exactly but implicit sessions (the ones provided in callbacks) should not be used outside the callback, for example.

**Comment by pwang111** [comment]
I list the code snippets that are relevant:

Getting the session and libyang context during app init:
```
static sr_conn_ctx_t *sr_conn;
static sr_session_ctx_t *sr_sess;
static struct ly_ctx *ly_ctx;         /**< libyang's context */
...
/* Connect with sysrepo */
    sr_rc = sr_connect(SR_CONN_DEFAULT, &sr_conn);
    if (sr_rc != SR_ERR_OK)
    {
        bcmos_printf("Can't connect with sysrepo. Error %s\n", sr_strerror(sr_rc));
        return -1;
    }

    sr_rc = sr_session_start(sr_conn, SR_DS_RUNNING, &sr_sess);
    if (sr_rc != SR_ERR_OK)
    {
        bcmos_printf("Unable to create Netopeer session with sysrepod (%s).", sr_strerror(sr_rc));
        return -1;
    }

   ly_ctx_new("sysrepo/yang", LY_CTX_ALL_IMPLEMENTED, &ly_ctx);
   if (!ly_ctx)
    {
        bcmos_printf("Unable to create libyang context.");
        return -1;
    }
   
```

The same session handle is used in sending notification, and it does acquire the libyang context also:
```
const struct ly_ctx *ctx = sr_acquire_context(sr_session_get_connection(sr_sess));
struct lyd_node *notif = NULL;
...
string notif_xpath = "/ietf-interfaces:interfaces-state/interface[name='CT_1']/bbf-xpon:channel-termination/bbf-xpon-onu-state:onu-presence-state-change"
lyd_new_path(NULL, ctx, notif_xpath, NULL,LYD_NEW_PATH_CANON_VALUE, &notif);
sr_rc = sr_notif_send_tree(srs, notif , 0, 0);
```

Also the same session handle is used in oper get subscribe:
```
    sr_subscription_ctx_t *sr_ctx;
    string if_module = "ietf-interfaces"
    string if_xpath = "/ietf-interfaces:interfaces-state/interface"

    sr_rc = sr_oper_get_subscribe(srs, if_module, if_xpath,
        xpon_interface_state_get_cb, NULL, SR_SUBSCR_DEFAULT, &sr_ctx);
    if (SR_ERR_OK != sr_rc) {
        NC_LOG_ERR("Failed to subscribe to %s subtree operation data retrieval (%s).",
            if_xpath, sr_strerror(sr_rc));
    }
```

And the get oper callback:
```
static int xpon_interface_state_get_cb(sr_session_ctx_t *session,  uint32_t sub_id,
    const char *module_name, const char *xpath, const char *request_path, uint32_t request_id,
    struct lyd_node **parent, void *private_data) {
    ...
   struct lyd_node *result = NULL;
   ...
   const struct ly_ctx *ctx = sr_acquire_context(sr_session_get_connection(session));
   lyd_new_path(*parent, ctx, if_xpath + "/admin-status", "up", LYD_NEW_PATH_CANON_VALUE, &result);
   ...
   return SR_ERR_OK;
}
```
Looking at the sysrepo doc, appears that sr_release_context() must be paired with sr_acquire_context(), is this the cause?

**Comment by pwang111** [comment]
P.S., I added sr_release_context() pairing with the acquire and the errors are gone. So it seems to be the root cause.

Back to the triggering of oper get callback by sending notification, if this cannot be avoided, we need to find a way to differentiate this from the real get from client. currently we have two subscriptions to the same module and xpath (xpath is slightly different as Machel mentioned before they have to be different):

```
module: ietf-interfaces
xpath: /ietf-interfaces:interfaces-state/interface
```
and

```
module: ietf-interfaces
xpath: /ietf-interfaces:interfaces-state/interface[name='ONU']
```
When the notification is sent, 
The former callback in-param xpath="/ietf-interfaces:interfaces-state/interface"
The latter callback in-param xpath="derived-from-or-self(/ietf-interfaces:interfaces/interface[name=current()/../name]/bbf-xpon:channel-termination/location,'bbf-xpon-types:inside-olt')"

But when a real get-data is sent from nc client, when using wildcard in subtree:
```xml
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="151">
  <get-data xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-nmda" xmlns:ds="urn:ietf:params:xml:ns:yang:ietf-datastores">
    <datastore>ds:operational</datastore>
    <subtree-filter>
      <interfaces-state xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">  
      </interfaces-state>
    </subtree-filter>
  </get-data>
</rpc>
```
We get xpath="/ietf-interfaces:interfaces-state"

Are there any rules that we can differentiate the trigger source?

**Comment by michalvasko** [comment]
> Are there any rules that we can differentiate the trigger source?

No and I do not understand why should it matter. You are simply supposed to provide the data because they are needed.

**Comment by pwang111** [comment]
Sorry I did not bring up a context. In our design when we receive an oper get, the callback will go through a gRPC BBF NBI channel connecting to a remote process (docker container), which is capable of collecting relevant stats of the YANG and feed them back to the callback, which will return data back to client, merging with what's in sysrepo. We don't want this to happen for notifications as this will cause performance issues in our system.

On the sr_release_context() pairing with the acquire issue, although this appears to fix the problem, but in my tests even if the error happened, everything is still going well, no apparent failures. is this just because the lock is only for read? what harm it will do eventually?

**Comment by jktjkt** [comment]
Consider using the push approach for operational data, then. You (somehow) monitor the underlying physical value, and once it changes, you push the result to sysrepo. Perhaps you backend can do that via gNMI?

**Comment by michalvasko** [comment]
Also, I believe in this case you should be getting a list of XPaths in the callback that should allow you to avoid collecting and returning most of the data.

**Comment by pwang111** [comment]
Yeah, this is what we are doing now, by looking at the specific string patterns as 'false trigger' and returning empty data in those cases, but thought this is somewhat kludge and would have a better solution.

On the topic of lock issue, just curious about my question previously posted: On the sr_release_context() pairing with the acquire issue, although this appears to fix the problem, but in my tests even if the error happened, everything is still going well, no apparent failures. is this just because the lock is only for read? what harm it will do eventually?

**Comment by michalvasko** [comment]
The errors mean that you are not holding the read lock when you should. In this case it is the context lock so what could happen is that someone changes the context (adds a new YANG module, for example), which recompiles it, while you are using the context. That will lead to accessing freed memory and your program crashing.
