### ISSUE TITLE
sr_rpc_subscribe is not trigerring when i try to push value "1" in o-ran-ald-communication

### ISSUE THREAD

**Issue by sowmi18** [sysrepo/sysrepo#2828]
@michalvasko We are sending the below RPC and also attached the result

> user-rpc --rpc-timeout 10

```
<ald-communication xmlns="urn:o-ran:ald:1.0">
    <port-id>1</port-id>
    <ald-req-msg>aGVsbG8gd29ybGQ=</ald-req-msg>
</ald-communication>
```

```
ERROR
    type:     application
    tag:      operation-failed
    severity: error
    path:     /o-ran-ald:ald-communication/port-id
    message:  Leafref "/o-ran-ald-port:ald-ports-io/o-ran-ald-port:ald-port/o-ran-ald-port:port-id" of value "1" points to a non-existing leaf.

    type:     application
    tag:      operation-failed
    severity: error
    message:  RPC input validation failed.

```
 I have two doubts on this
1. why i got two errors at a time?
2. Also when i try to push the port-id value as '0' it succeeds but when i try with value '1' it fails. when i give value '1' the callback itself not getting triggered. I am attaching the logs 
[ald-port.docx](https://github.com/sysrepo/sysrepo/files/8797608/ald-port.docx)

3. port-id in ald communication is a leafref to port-id in ald-port which is mentioned as config false in yang file. But in ald-communication port-id is in a write(w) mode. Will config false of the ald-port/port-id will be applied to the ald-communication/port-id?

rpc for ald-communication:
```
+---x ald-communication
+---w input
| +---w port-id            -> /ap:ald-ports-io/ald-port/port-id       //it is a leafref to ald-port/port-id
| +---w ald-req-msg?     binary

grouping ald-input {                                                          
    leaf port-id {                                                              
      type leafref {                                                            
        path "/ap:ald-ports-io/ap:ald-port/ap:port-id";                         
      }                                                                         
      mandatory true;                  
    }
```
rpc for ald-port:
```
+--rw ald-ports-io
+--ro over-current-supported?   boolean
+--ro ald-port* [name]    
| +--ro name    string
| +--ro port-id   uint8         // it is written as config false in yang


leaf port-id {                                                            
        type uint8;                                                             
            config false;                                                       
            mandatory true;                                                            
      }
```
Can you please help on his issue?

**Comment by michalvasko** [comment]
1. The first error is the specific error, the second one is the more generic error. But they are not 2 errors, the first one is causing the second one.
2. I do not understand why would this be surprising unless you do not know how `leafref`s work. In the `operational` datastore (config false) you have value `0` so you can use only that in the RPC for the leafref (that is how leafref works).
3. Again, shows that you do not understand basic YANG concepts. One is a leafref, the other one a leafref target, they are separate nodes. [Here](https://www.rfc-editor.org/rfc/rfc7950.html#section-9.9) is the definition.

**Comment by sowmi18** [comment]
Thank you for clearing my doubts!!
Another doubt I have
![Screenshot from 2022-06-01 16-01-37](https://user-images.githubusercontent.com/98811895/171395529-c93c87a8-3d1f-44b3-9fb8-3467e5194f63.png)
Under Test case 6 point 2( from O-RAN.WG4.CONF.0-v02.00) can't be implemented as per my understanding. Because before validating the port-id value inside callback, it is getting rejected by the sysrepo. Correct me if I am wrong.

**Comment by michalvasko** [comment]
Yes, you cannot handle invalid YANG data yourself, it is processed internally.
