### ISSUE TITLE
Wrong RPC message crashes the server

### ISSUE THREAD

**Issue by qing8717** [sysrepo/sysrepo#2829]
hi,
By accident，I input a double “rpc” label‘s rpc request，and then I got a  crash server like this:
requst:
```xml
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="7"><rpc message-id="2"xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<get-managed-element-time xmlns="urn:ccsa:yang:acc-devm"/>
</rpc></rpc>
```
The crash trace:
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f338c67b700 (LWP 14944)]
0x00007f3390dae7cc in lyd_path (node=0x7f3380001eb0, pathtype=LYD_PATH_STD, buffer=0x7f3380000b70 "/rpc", buflen=5) at /workbench/soft_protocol/netconf/libyang/src/tree_data.c:4019
4019                if (iter->schema && (!iter->parent || (iter->schema->module != iter->parent->schema->module))) {
(gdb) bt 
#0  0x00007f3390dae7cc in lyd_path (node=0x7f3380001eb0, pathtype=LYD_PATH_STD, buffer=0x7f3380000b70 "/rpc", buflen=5) at /workbench/soft_protocol/netconf/libyang/src/tree_data.c:4019
#1  0x00007f3390b0d9d1 in sr_rpc_send_tree (session=0x7f337c0054f0, input=0x7f3380001eb0, timeout_ms=50000, output=0x7f338c67abe0) at /workbench/soft_protocol/netconf/sysrepo/src/sysrepo.c:4678
#2  0x0000000000409210 in np2srv_rpc_cb (rpc=0x7f3380001eb0, ncs=0x7f337c000a10) at /workbench/soft_protocol/netconf/netopeer2/src/main.c:395
#3  0x00007f33908c94a9 in nc_server_send_reply_io (session=0x7f337c000a10, io_timeout=10, rpc=0x7f3380000b50) at /workbench/soft_protocol/netconf/libnetconf2/src/session_server.c:1434
#4  0x00007f33908ca1ce in nc_ps_poll (ps=0x18dac30, timeout=10, session=0x7f338c67ae48) at /workbench/soft_protocol/netconf/libnetconf2/src/session_server.c:1790
#5  0x000000000040b8d0 in worker_thread (arg=0x18d5b70) at /workbench/soft_protocol/netconf/netopeer2/src/main.c:1028
#6  0x00007f3390486e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#7  0x00007f33901b42ed in clone () from /lib/x86_64-linux-gnu/libc.so.6
#8  0x0000000000000000 in ?? ()
```

**Comment by qing8717** [comment]
The requst:
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="7"><rpc message-id="2"xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<get-managed-element-time xmlns="urn:ccsa:yang:acc-devm"/>
</rpc></rpc>

**Comment by qing8717** [comment]
@michalvasko  Thanks very much!

**Comment by qing8717** [comment]
It works well ,thanks!

**Comment by qing8717** [comment]
Hi，michalvasko，
    I find out that the commit CESNET/libyang@12eb622 can work well,But a get request which can work before the modification
can not work now. The request and error are following. Has any other modification？
Request：
<get xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <filter type="subtree">
    <acc-devm:me xmlns:acc-devm="urn:ccsa:yang:acc-devm"/>
  </filter>
</get>
Reply：
<?xml version="1.0" encoding="utf-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="9">
  <rpc-error>
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-message xml:lang="en">Internal error</error-message>
  </rpc-error>
  <rpc-error>
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-message xml:lang="en">User callback failed.</error-message>
  </rpc-error>
</rpc-reply>

**Comment by qing8717** [comment]
Request：
<get xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <filter type="subtree">
    <acc-devm:me xmlns:acc-devm="urn:ccsa:yang:acc-devm"/>
  </filter>
</get>
Reply：
<?xml version="1.0" encoding="utf-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="9">
  <rpc-error>
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-message xml:lang="en">Internal error</error-message>
  </rpc-error>
  <rpc-error>
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-message xml:lang="en">User callback failed.</error-message>
  </rpc-error>
</rpc-reply>

**Comment by qing8717** [comment]
Request：
'''
<get xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <filter type="subtree">
    <acc-devm:me xmlns:acc-devm="urn:ccsa:yang:acc-devm"/>
  </filter>
</get>
'''
Reply：
'''
<?xml version="1.0" encoding="utf-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="9">
  <rpc-error>
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-message xml:lang="en">Internal error</error-message>
  </rpc-error>
  <rpc-error>
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-message xml:lang="en">User callback failed.</error-message>
  </rpc-error>
</rpc-reply>

'''

**Comment by michalvasko** [comment]
Could you provide a way to reproduce this? Can you provide the the YANG module whose data you are trying to filter?

**Comment by qing8717** [comment]
Hi，michalvasko
I'm sorry to reply so late!  The error I encountered was a mistake made by myself：I gave the wrong data to the callback function.
Thanks very much.
The issue can be closed now!
