### ISSUE TITLE
Sysrepo Engine should not allow to be stopped while there is an ongoing commit

### ISSUE THREAD

**Issue by rastislavszabo** [sysrepo/sysrepo#283]
Sysrepo Engine should not allow to be stopped while there is an ongoing commit (there is a  not released commit context in DM). Instead, if stop was requested, it should be just marked for stopping while the commit is still in progress, and automatically stopped just after the commit has finished.

Steps to reproduce: Do not start sysrepo daemon. Run examples/application_example. Try to make some changes in running datastore using sysrepocfg. After few attempts (8th worked form me), you'll get an error:

 ========== CONFIG HAS CHANGED, CURRENT RUNNING CONFIG: ==========

Error by sr_get_items: The peer disconnected 

The issue affects users only if the Sysrepo Engine is running in library mode, therefore tracking this as an enhancement.

**Comment by lukasmacko** [comment]
Fixed in devel branch
