### ISSUE TITLE
Segmentation fault when importing a duplicate instance

### ISSUE THREAD

**Issue by gotthardp** [sysrepo/sysrepo#2833]
Hello. Importing a tree with duplicate elements causes segmentation fault. On some trees it works though: duplicate interface works fine, but a duplicate `ace` causes a crash. (I use latest sysrepo and libyang and a fresh repository.)

Script to reproduce (once you import the `ietf-access-control-list`, e.g. from https://github.com/CESNET/velia/)
```bash
cat << EOF > test.xml
<acls xmlns="urn:ietf:params:xml:ns:yang:ietf-access-control-list">
  <acl>
    <name>sample-ipv4-acl</name>
    <aces>
      <ace>
        <name>ssh</name>
        <actions>
          <forwarding xmlns:acl="urn:ietf:params:xml:ns:yang:ietf-access-control-list">acl:accept</forwarding>
        </actions>
      </ace>
      <ace>
        <name>ssh</name>
        <actions>
          <forwarding xmlns:acl="urn:ietf:params:xml:ns:yang:ietf-access-control-list">acl:accept</forwarding>
        </actions>
      </ace>
    </aces>
  </acl>
</acls>
EOF

sysrepocfg --import=test.xml
```

**Comment by michalvasko** [comment]
Using current `devel` of *sysrepo* and *libyang* with [`ietf-access-control-list`](https://github.com/YangModels/yang/blob/main/standard/ietf/RFC/ietf-access-control-list%402019-03-04.yang) produced the correct error and no memory problems.

**Comment by gotthardp** [comment]
It still fails for me though. (Now) it seems to fail only when there is already an ACE in the datastore. With an empty datastore it shows a correct error as you say. Could you please import a valid ACL (see the following script) **and then** invoke the above erroneous ACL? That combination fails (for me) with a SIGSEGV even with latest (devel) libyang and sysrepo.

```bash
cat << EOF > test.xml
<acls xmlns="urn:ietf:params:xml:ns:yang:ietf-access-control-list">
  <acl>
    <name>sample-ipv4-acl</name>
    <aces>
      <ace>
        <name>ssh</name>
        <actions>
          <forwarding xmlns:acl="urn:ietf:params:xml:ns:yang:ietf-access-control-list">acl:accept</forwarding>
        </actions>
      </ace>
    </aces>
  </acl>
</acls>
EOF

sysrepocfg --import=test.xml
```

**Comment by gotthardp** [comment]
It does not crash anymore. Thank you.
