### ISSUE TITLE
set value for operational data inside a configurable list

### ISSUE THREAD

**Issue by renithas** [sysrepo/sysrepo#2836]
Hi Michal,
I am using https://gerrit.o-ran-sc.org/r/c/scp/oam/modeling/+/5706/3/data-model/yang/published/o-ran/ru-fh/o-ran-uplane-conf%25402020-12-10.yang
To set the config data under tx-array-carriers list, I use an xml and sysrepocfg . 
Inside this list there is an operational data 'state' . After setting config data,  To configure this state data , I am using 
 rc = sr_oper_get_subscribe(session, "o-ran-uplane-conf",
            "/o-ran-uplane-conf:user-plane-configuration/tx-array-carriers/state",
                oran_uplane_conf_txarraycarriers_state_cb, NULL, 0, &subscription)
and inside the call back
lyd_new_path(NULL, ly_ctx, "/o-ran-uplane-conf:user-plane-configuration/tx-array-carriers[name='tac']/state, "READY", 0, parent);

But this call back is never called , and not able to set the value for 'state'.

Also tried to set the value with 
rc=sr_set_item_str(session, 
        "/o-ran-uplane-conf:user-plane-configuration/tx-array-carriers[name='tac']/state",
            "READY", NULL, 0);
    
Yang tree:
 +--rw tx-array-carriers* [name]
     |  +--rw name                           string
     |  x--rw absolute-frequency-center?     uint32
     |  +--rw center-of-channel-bandwidth    uint64
     |  +--rw channel-bandwidth              uint64
     |  +--rw active?                        enumeration
     |  +--ro state                          enumeration
     |  +--rw type?                          enumeration
     |  +--ro duplex-scheme?                 enumeration

**Comment by jktjkt** [comment]
I've migrated to push ops data for various reasons, but let's go through a few quick questions anyway:
- Is your callback getting invoked at all when someone asks for the `operational` DS?
-  Is `/o-ran-uplane-conf:user-plane-configuration/tx-array-carriers[name='tac']` present in the `running` DS?
-  How does that work when you subscribe with `SR_SUBSCR_OPER_MERGE`?

**Comment by michalvasko** [comment]
I would point you to [this section](https://netopeer.liberouter.org/doc/sysrepo/devel/html/subs.html#oper_subs) in the docs.

**Comment by renithas** [comment]
> @jktjkt Hi,
Thanks for your quick response
Here is my answers to your queries,
1. Callback not getting invoked in this particular case where the xpath is operational data inside a configuration node.
2. Yes , it is confirmed that  /o-ran-uplane-conf:user-plane-configuration/tx-array-carriers[name='tac'] is present.
3. I haven't tried with SR_SUBSCR_OPER_MERGE. Will give a try

**Comment by renithas** [comment]
Hi @michalvasko ,

Thanks to your quick response. 
Let me read and understand this part thoroughly , if it is helpful in this case

**Comment by michalvasko** [comment]
Actually, my main point is one of the bullets @jktjkt mentioned except it needs to be clarified, the question being

 - Is `/o-ran-uplane-conf:user-plane-configuration/tx-array-carriers[name='tac']` present in the **operational** DS?

**Comment by renithas** [comment]
@michalvasko 
Using   sysrepocfg --edit=uplane-config.xml  --datastore running
tx-array-carriers[name='tac'] element is inserted. since this parent node is config node.
So, do i have to use operational DS in the case of tx-array-carriers[name='tac'] ???

**Comment by michalvasko** [comment]
Yes, state data exist **only** in the operational datastore. In this case all you have to do is subscribe to the running data, which makes them enabled and automatically copied into the operational DS.

**Comment by renithas** [comment]
ok thank you @michalvasko . I got your point. Let me try that.
Closing this question

**Comment by guoqi78** [comment]
## Hello, I've encountered a similar issue. Here is the structure of my code:

rc = sr_connect(0, &stOmSrv.srConn);
    if (rc != SR_ERR_OK)
	{
		ERR("sysrepo connect failed");
       return OM_ERR_SYSREPO_INIT;
    }

## DS：OPERATIONAL 
rc = sr_session_start(stOmSrv.srConn, SR_DS_OPERATIONAL, &stOmSrv.operationalSess);
    if (rc != SR_ERR_OK)
	{
		ERR("sysrepo operationalSess start failed");
		return OM_ERR_SYSREPO_INIT;
    }


mod_name = "o-ran-uplane-conf-option8";
xpath = "/o-ran-uplane-conf-option8:user-plane-configuration/tx-array-carriers";
rc = sr_oper_get_items_subscribe(stOmSrv.operationalSess, mod_name, xpath, ruOmUplaneCarriersStateDataCb, NULL, SR_SUBSCR_OPER_MERGE, &stOmSrv.srDataSub);

root = lyd_new_path(NULL, ly_ctx, "/o-ran-uplane-conf-option8:user-plane-configuration/tx-array-carriers[name='TXA0P00C00']", NULL, 0, 0);
rc = lyd_new_leaf(root,   NULL, "state", "READY");

##No errors occurred after executing the code above, and the execution of lyd_new_leaf also indicated success, 
   but the value of ‘state’ still cannot be obtained through the netopeer2-cli get method. I would like to ask which step might have gone wrong. Thank you very much.

##############netopeer2-cli ，get
> edit-config --target running --config=/log/uplane4.xml
OK
> get --filter-xpath /o-ran-uplane-conf-option8:user-plane-configuration/tx-array-carriers
DATA
<user-plane-configuration xmlns="urn:o-ran:uplane-conf-option8:1.0">
  <tx-array-carriers>
    <name>TXA0P00C00</name>
    <active>INACTIVE</active>
    <downlink-radio-frame-offset>0</downlink-radio-frame-offset>
    <downlink-sfn-offset>0</downlink-sfn-offset>
    <absolute-frequency-center>513000</absolute-frequency-center>
    <center-of-channel-bandwidth>2565000000</center-of-channel-bandwidth>
    <channel-bandwidth>100000000</channel-bandwidth>
    <type>NR</type>
    <gain>0.0</gain>
    <rw-type>NR</rw-type>
    <rw-duplex-scheme>TDD</rw-duplex-scheme>
    <nr-tdd-frame xmlns="urn:nts:yang:nr-tdd-frame">
      <tdd-pattern>
        <name>pattern1</name>
        <transmissionPeriod>ms5</transmissionPeriod>
        <downlinkSlot>7</downlinkSlot>
        <downlinkSymbol>6</downlinkSymbol>
        <uplinkSlot>2</uplinkSlot>
        <uplinkSymbol>4</uplinkSymbol>
      </tdd-pattern>
    </nr-tdd-frame>
  </tx-array-carriers>

**Comment by guoqi78** [comment]
##############netopeer2-cli ，get
> get --filter-xpath /o-ran-uplane-conf-option8:user-plane-configuration/tx-array-carriers
DATA
<user-plane-configuration xmlns="urn:o-ran:uplane-conf-option8:1.0">
  <tx-array-carriers>
    <name>TXA0P00C00</name>
    <active>INACTIVE</active>
    <downlink-radio-frame-offset>0</downlink-radio-frame-offset>
    <downlink-sfn-offset>0</downlink-sfn-offset>
    <absolute-frequency-center>513000</absolute-frequency-center>
    <center-of-channel-bandwidth>2565000000</center-of-channel-bandwidth>
    <channel-bandwidth>100000000</channel-bandwidth>
    <type>NR</type>
    <gain>0.0</gain>
    <rw-type>NR</rw-type>
    <rw-duplex-scheme>TDD</rw-duplex-scheme>
    <nr-tdd-frame xmlns="urn:nts:yang:nr-tdd-frame">
      <tdd-pattern>
        <name>pattern1</name>
        <transmissionPeriod>ms5</transmissionPeriod>
        <downlinkSlot>7</downlinkSlot>
        <downlinkSymbol>6</downlinkSymbol>
        <uplinkSlot>2</uplinkSlot>
        <uplinkSymbol>4</uplinkSymbol>
      </tdd-pattern>
    </nr-tdd-frame>
  </tx-array-carriers>

**Comment by guoqi78** [comment]
[state_update_failed.txt](https://github.com/user-attachments/files/17321528/state_update_failed.txt)

**Comment by michalvasko** [comment]
I can only reference you to the [example](https://github.com/sysrepo/sysrepo/blob/master/examples/oper_data_pull_example.c), which should help you understand what exactly to do. In short, you cannot just randomly create some data, you need to do so in the callback you subscribed and actually return the created data in a parameter.
