### ISSUE TITLE
Question: ignore internal error

### ISSUE THREAD

**Issue by jeanseb6wind** [sysrepo/sysrepo#2837]
Hello @michalvasko,
On my prod environment, I encounter a sysrepo internal error.
Here: [link](https://github.com/sysrepo/sysrepo/blob/v2.1.64/src/sysrepo.c#L5127)

I don't manage to reproduce this issue in my test env with a minimal yang and minimal command so I can't tell you how to reproduce it.
Is this error can be ignored ? Is this a big error ? And did you already encounter this error ?

Thanks
Jean-Sébastien

**Comment by michalvasko** [comment]
I would appreciate if you could provide a way to reproduce, it should be just a rare use-case but a use-case nonetheless. The problem would seem to be with some changes that are not correctly annotated with all the expected metadata, here in particular a user-ordered instance. If you can use `gdb` to stop at this error, you should be able to print the `diff` in the `session`, which should output the problematic data tree.

**Comment by jeanseb6wind** [comment]
Ok I will try. A things to note: this error is only with libyang2, not with libyang1

**Comment by michalvasko** [comment]
Thanks, I have discovered additional problems while trying to fix this one so it took a while. With the latest *libyang* it should all work correctly, tests added.

**Comment by jeanseb6wind** [comment]
Thanks @michalvasko, it works !
