### ISSUE TITLE
sr_module_change_subscribe function ,The callback is executed twice

### ISSUE THREAD

**Issue by hi-Mr-ye** [sysrepo/sysrepo#2838]
Hi @michalvasko
I run edit-config --target running --config=/root/edit.xml --def merge.
but callback is executed twice, why?
![image](https://user-images.githubusercontent.com/90752673/172984440-c0bfc56b-ef44-4e4d-987b-00ed965aa5ed.png)

**Comment by michalvasko** [comment]
Read through the [docs](https://netopeer.liberouter.org/doc/sysrepo/devel/html/subs.html#change_subs).

**Comment by michalvasko** [comment]
Yes, you can use `SR_SUBSCR_DONE_ONLY` flag to get only the `SR_EV_DONE` event.
