### ISSUE TITLE
Locking a mutex failed (sr_connect: Operation timed out)

### ISSUE THREAD

**Issue by hideonshadowX** [sysrepo/sysrepo#2840]
When the netopeer server inited, it called sr_connect() to connect to sysrepo. This error occurred.
I readed libsysrepo src code, and found this error from here:

    if ((err_info = sr_mlock(&main_shm->lydmods_lock, SR_MAIN_LOCK_TIMEOUT * 1000, __func__))) {
        goto cleanup_unlock;
    }

netopeer2 version: v1.1.34
libsysrepo version: v1.4.66

Why ? And, what I can do to solve it ?
Thanks！

**Comment by michalvasko** [comment]
You are using a 2-year old *sysrepo* version, which is long obsolete, I cannot help you.
