### ISSUE TITLE
When sysrepo v2.1.42 link to libyang v2.0.164 . sysrepocfg "crash" happened!

### ISSUE THREAD

**Issue by m12wang** [sysrepo/sysrepo#2841]
sysrepocfg -X
[ERR] Regular expression "\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(.\d+)?(Z|[+-]\d{2}:\d{2})" is not valid ("\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(.\d+)?(Z|[+-]\d{2}:\d{2})": unrecognised compile-time option bit(s)).
[ERR] Internal error (/usr/src/debug/libyang/2.0.164-1/git/src/tree_schema.c:1154).
sysrepocfg error: Failed to connect (libyang error)
For more details you may try to increase the verbosity up to "-v3".

**Comment by michalvasko** [comment]
The first time I am seeing this but it seems your `pcre2` library does not know some pattern compilation options used. What `pcre2` version are you using? At least 10.21 is required, which should be checked before *libyang* compilation.
