### ISSUE TITLE
how to get username from the RPC call , when it is triggered from client

### ISSUE THREAD

**Issue by chendrashekarp** [sysrepo/sysrepo#2844]
hi @michalvasko  , how to know which client has triggered the RPC ?

**Comment by vinayhb012114** [comment]
@michalvasko,
We want to know which user has trigeered rpc from client side,so which sysrepo api will give user-name.?

**Comment by chendrashekarp** [comment]
hi @jktjkt  , I want to know which user has triggered that RPC , my RPC is for changing the password , where i will get only password , so i need a way to find which user has triggered that RPC

**Comment by jktjkt** [comment]
@chendrashekarp sysrepo has API functions for these, read the documentation to find out more. But keep in mind that sysrepo is essentially a collaborative library with limited access checks, and that in case of NETCONF access in particular, this is actually handled by Netopeer2, which [indeed passes this information to sysrepo](https://github.com/CESNET/Netopeer2/#sysrepo-callbacks).

**Comment by chendrashekarp** [comment]
thanks @jktjkt , sr_session_get_orig_data , this API serves my purpose.
