### ISSUE TITLE
sr_oper_get_subscribe callback not invoked when wildcard was used in sr_module_change_subscribe

### ISSUE THREAD

**Issue by gotthardp** [sysrepo/sysrepo#2846]
When `sr_module_change_subscribe` is called with a `//*` wildcard, the operational tree is correctly populated, but subsequent `sr_oper_get_subscribe` callbacks for an operational subtree are **not** invoked. Is it a bug or did I misunderstood some feature?

The behaviour can be reproduced using the following Python code, the latest devel libyang/sysrepo and the `ietf-keystore` model (it seems to be not reproducible with `ietf-interfaces`):
```python
import sysrepo
import asyncio
import signal

loop = asyncio.get_event_loop()
stop_event = asyncio.Event()
loop.add_signal_handler(signal.SIGINT, stop_event.set)

with sysrepo.SysrepoConnection() as conn:
    with conn.start_session() as sess:
        sess.subscribe_module_change("ietf-keystore",
##          "/ietf-keystore:keystore/asymmetric-keys/asymmetric-key",
            "/ietf-keystore:keystore//*",
            lambda event, req_id, changes, private_data: None,
            asyncio_register=True)

        sess.subscribe_oper_data_request("ietf-keystore",
            "/ietf-keystore:keystore/asymmetric-keys/asymmetric-key/public-key",
            lambda xpath, private_data: print("CALLED"),
            asyncio_register=True)

        loop.run_until_complete(stop_event.wait())
```
Put some key into the running datastore. Now:
 * When you start the above and then call `sysrepocfg --export --datastore operational` you get the operational data, but the oper callback is not invoked (nothing gets printed from the Python).
 * When you use the commented-out path (without wildcard) instead, the `CALLED` gets printed as expected.

Shall it be like that, please? It seems to me as if some xpath comparison was not working correctly.

**Comment by michalvasko** [comment]
Right, there was quite a nasty bug ultimately leading to this problem, should be fixed now.
