### ISSUE TITLE
how to know a features is enabled or not

### ISSUE THREAD

**Issue by chendrashekarp** [sysrepo/sysrepo#2850]
hi @michalvasko/ @jktjkt  , is there any API to know if a feature is enabled or not

**Comment by farshid-cloudly** [comment]
Has it been answered somewhere? I was also looking for something to check if a specific feature for a module is enabled or not.

**Comment by FAR5HID** [comment]
Has it been answered somewhere? I was also looking for something to check if a specific feature for a module is enabled or not.

**Comment by michalvasko** [comment]
Get the context from a connection (`sr_acquire_context()`), get the module (`ly_ctx_get_module_implemented()`) and then check the feature state (`lys_feature_value()`).

**Comment by FAR5HID** [comment]
Thanks @michalvasko for your fast response that I was too slow to react to. You seem to be around everywhere in the netconf application stack, that's something to really appreciate. Btw, regarding the previous query, the application I'm working on uses an [older version](https://github.com/CESNET/libyang/tree/v1.0.167) of libyang which doesn't have lys_feature_value(). However, following your lead, found feature_state() that basically returns [lys_features_state()](https://github.com/CESNET/libyang/blob/v1.0.167/src/tree_schema.c#L4005). The issue with this one is that, it returns 0 (disabled) even after a feature is enabled using enable_module_feature(), but keeps returning 1 (enabled) after netopeer server restart. I'm trying the following steps:
```
  libyang::S_Context lyContext(mSrConnection->get_context());
  libyang::S_Module module(lyContext->get_module(name.c_str(), nullptr, 0));
  int state = module->feature_state(feature.c_str());
```
I can understand if you're unable to make comments as this is very old implementation of libyang, and unrelated to this repo, but asking just in case you can leave any remarks which would be very helpful. Thanks.

**Comment by michalvasko** [comment]
> You seem to be around everywhere in the netconf application stack, that's something to really appreciate.

If you mean the projects *libyang*, *libnetconf2*, *sysrepo*, and *netopeer2* then yes since I was/am the main developer of them all.

Regarding the issue, based on what I remember, this old *sysrepo* version did not support context changes when there were *sysrepo* applications running so all the changes are only stored and applied once no application is running. That would explain your observations.

**Comment by FAR5HID** [comment]
Glad to meet you, Michal. And thanks for the heads up with the scenario.
