### ISSUE TITLE
Unsatisfied pattern when push data in operational db

### ISSUE THREAD

**Issue by helijia21** [sysrepo/sysrepo#2856]
here is the leaf def
typedef date-and-time {
    type string {
      pattern
        '^[0-9]{4}\-[0-9]{2}\-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}' +
        '(\.[0-9]+)?Z[+-][0-9]{2}:[0-9]{2}$';
    }
    description
      "A date and time, expressed in the format described in RFC3339.
      That is to say:

      YYYY-MM-DDTHH:MM:SSZ+-hh:mm

      where YYYY is the year, MM is the month expressed as a two-digit
      month (zero padding if required), DD is the day of the month,
      expressed as a two digit value. T is the literal character 'T',
      HH is the hour of the day expressed as a two digit number, using
      the 24-hour clock, MM is the minute of the hour expressed as a
      two digit number. Z is the literal character 'Z', followed by a
      timezone offset expressed in hours (hh) and minutes (mm), both
      expressed as two digit numbers. The time offset is specified as
      a positive or negative offset to UTC using the '+' or '-'
      character preceding the offset.

      Optionally, fractional seconds can be expressed after the minute
      of the hour as a decimal number of unspecified precision
      reflecting fractions of a second.";
    reference
      "RFC3339 - Date and Time on the Internet: Timestamps";
  }

input:
oper_data_push_example /openconfig-system:system/state/current-datetime 2022-06-30T23:38:43Z+08:00
return:
[ERR] Unsatisfied pattern - "2022-06-30T23:38:43Z+08:00" does not conform to "^[0-9]{4}\-[0-9]{2}\-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]+)?Z[+-][0-9]{2}:[0-9]{2}$". (Schema location /openconfig-system:system/state/current-datetime.)
[ERR] Invalid datastore edit.

**Comment by helijia21** [comment]
it seems that the pattern match the input string

**Comment by jktjkt** [comment]
The OpenConfig YANG models do not conform to RFC 7950. The YANG standard defines that these patterns are implicitly anchored, whereas OpenConfig wantes to have these explicit `^` and `$` in the pattern, and that means that a YANG-compliant software wants these strings to actually contain a literal `^` at the beginning, and `$` at the end.

- https://github.com/CESNET/libyang/issues/422
- https://github.com/openconfig/public/issues/44

**Comment by helijia21** [comment]
thanks a lot! add '^' and '$' make it pass!

**Comment by jktjkt** [comment]
> thanks a lot! add '^' and '$' make it pass!

That's quite likely a wrong fix, nobody really wants their actual timestamps prefixed by `^` and suffixed by `$`. A clean fix would involve an `augment` that replaces hat wrong regex `pattern` with a reasonable one (and some pestering of OpenConfig to actually fix this at the root source).
