### ISSUE TITLE
Question: Can't two modules subscribe to the same data (xpath)

### ISSUE THREAD

**Issue by mikajuvonen67** [sysrepo/sysrepo#2857]
Hi,

We have two sysrepo plugins for, ietf-interfaces and ieee802-dot1q-sched-bridge. The ieee802-dot1q-sched-bridge augments the ietf-interfaces module. Setting up sr_module_change_subscribe for the two plugins only generate callbacks to the "parent" module i.e ietf-interfaces.
The call to sr_module_change_subscribe returns no error in both cases. Changing the XPATH doesn't change the behaviour nor what data in the datastores we change.

Sysrepo 2.0.53 libyang  2.0.112

Example:

```
#define MODEL1 "ietf-interfaces"
#define MODEL2 "ieee802-dot1q-sched-bridge"
#define XPATH   "/" MODEL1 ":interfaces//*"
static sr_subscription_ctx_t   *sub;

int cb_cfg_change(sr_session_ctx_t *session, const char *module_name, ...)
{
    printf("module %s called\n", module_name);
    return SR_ERR_OK;
}

int sr_plugin_init_cb(sr_session_ctx_t *session, void **private_ctx)
{   
    int rc = sr_module_change_subscribe(session, MODEL1, XPATH, cb_cfg_change, NULL, 0, SR_SUBSCR_CTX_REUSE, &sub);
    if (SR_ERR_OK == rc) {
        printf("sr_module_change_subscribe() ok for module %s.\n", MODEL1);
    } else {
        printf("sr_module_change_subscribe() error: rc(%d) for module. %s\n", rc, MODEL1);
    }

    rc = sr_module_change_subscribe(session, MODEL2, XPATH, cb_cfg_change, NULL, 0, SR_SUBSCR_CTX_REUSE, &sub);
    if (SR_ERR_OK == rc) {
        printf("sr_module_change_subscribe() ok for module %s.\n", MODEL2);
    } else {
        printf("sr_module_change_subscribe() error: rc(%d) for module %s.\n", rc, MODEL2);
    }

    return SR_ERR_OK;
}
```
Is this the expected/Intended behaviour?

**Comment by jktjkt** [comment]
It looks like there are no data nodes which belong "directly" to `ieee802-dot1q-sched-bridge`. Because that data model only augments `ietf-interfaces`, you'll have to subscribe to changes in `ietf-interfaces` instead. And for multiple subscriptions to a single YANG model, ensure that correct priorities are set to control the order of callbacks.

**Comment by mikajuvonen67** [comment]
Sorry for being a bit unclear. There are actually four yang models (plus imports) involved here. ietf-interfaces and then ieee802-dot1q-bridge which augments the ietf-interfaces with bridge-port. Then we have ieee802-dot1q-sched-bridge which augment the bridge-port with sched:sched-parameters from ieee802-dot1q-sched. So the actual data is in the ieee802-dot1q-sched module.
But it doesn't  matter if we set up the sr_module_change_subscribe with ieee802-dot1q-sched-bridge or ieee802-dot1q-sched. All callbacks are received by the ietf-interfaces plugin. Isn't the priority only within a module? These are different(?) modules.

**Comment by mikajuvonen67** [comment]
Thank you I will try that.
