### ISSUE TITLE
Question: is there any way to be notified that a module has been installed or removed

### ISSUE THREAD

**Issue by bbergquist0930** [sysrepo/sysrepo#2859]
I would like to have a piece of code invoked (a callback for example) when a YANG module has been installed or removed.  I see the `sysrepo-monitoring` modle and I can query that, but I would like the system to notify my code on YANG module changes.  

Is this possible?

**Comment by michalvasko** [comment]
No, currently there is no such callback available and the only way to learn that is probably by watching the `sysrepo-monitoring` data as you have correctly found out.
