### ISSUE TITLE
Using sysrepo v2.1.42 ;On one sr session, we subscribe 2 modules, but set nodes of module 2 failed!

### ISSUE THREAD

**Issue by m12wang** [sysrepo/sysrepo#2860]
On one sr session, we subscribe 2 modules, module 1 and module 2 w/ sr_module_change_subscribe(SR_SUBSCR_DEFAULT), v2.1.42
when trigger module 1 callback, in this callback, it will set some nodes of module 2
but seems that set nodes of module 2 failed

[ERR] Callback event "change" with ID 1 processing timed out.
[WRN] Event "change" with ID 1 priority 0 failed (Timeout expired).
[ERR] User callback failed.

Is there anything wrong w/ the usage?

**Comment by michalvasko** [comment]
If I understand it correctly, you have a deadlock there. Without any details, if you use 2 different subscription structures for the 2 `sr_module_change_subscribe()` calls, it should work.
