### ISSUE TITLE
sysrepocfg gets segfault with malformed xpath

### ISSUE THREAD

**Issue by hthiery** [sysrepo/sysrepo#2864]
```
# sysrepocfg -f json -d operational -X -x /ietf-interfaces:interfaces*/
Segmentation fault
```

When using the malformed xpath in netopeer2-cli the netopeer2-server also does a segfault:

This command in the CLI:
`get --filter-xpath /ietf-interfaces:interfaces*/`

Leads to this output of the server:
```
[INF]: SR: Published event "rpc" "/ietf-netconf:get" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:get" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[INF]: SR: Published event "operational" "/ietf-interfaces:interfaces/*" with ID 4.
[INF]: SR: Event "operational" with ID 4 succeeded.
Segmentation fault

```

**Comment by michalvasko** [comment]
Who would have guessed, `/ietf-interfaces:interfaces*/` is a valid XPath, which means `/ietf-interfaces:interfaces *(multiply) /`. However, root node string conversion has not reflected all the changes done before and was probably still the same as in *libyang* v1. Updated and should no longer crash.
