### ISSUE TITLE
Process2 call sr_module_change_subscribe during edit-data causes 'Callback event "done" with ID 7 processing timed out' 

### ISSUE THREAD

**Issue by starx1000** [sysrepo/sysrepo#2869]
Hi,
    All of the related modules, latest version in master used. sysrepo 2.1.64, netopeer2-server 2.1.23

The use scenario is like below:
using netopeer2-cli, call edit-data with module "ietf-interfaces", and netopeer2-server is processing.
Already some configuration changes subscribers exists.

During the time,  another process call sr_module_change_subscribe  to subscribe configuration changes.

`Call sr_module_change_subscribe with module "ietf-interfaces", priority 0, flag: SR_SUBSCR_DEFAULT|SR_SUBSCR_DONE_ONLY`

Netopeer2-server will be held after
Print the log
 "Published event "done" "ietf-interfaces" with ID 7 priority 0 for 34 subscribers." 
-- Until timeout( here the timeout is 5 seconds)

The sr_module_change_subscribe  is also not returned until the netopeer2-server prints "Callback event "done" with ID 7 processing timed out."

```
<30>1 2022-07-13T02:28:13.652737+00:00 netopeer2-server 15 - - Published event "rpc" "/ietf-netconf-nmda:edit-data" with ID 50 priority 0 for 1 subscribers.
<30>1 2022-07-13T02:28:13.699632+00:00 netopeer2-server 15 - - Processing "/ietf-netconf-nmda:edit-data" "rpc" event with ID 50 priority 0 (remaining 1 subscribers).
<15>1 2022-07-13T02:28:14.793253+00:00 test-process-1 1 - - Call sr_module_change_subscribe with module "ietf-interfaces", priority 0, flag: SR_SUBSCR_DEFAULT|SR_SUBSCR_DONE_ONLY
<30>1 2022-07-13T02:28:14.941605+00:00 netopeer2-server 15 - - Published event "done" "ietf-interfaces" with ID 7 priority 0 for 34 subscribers.
<27>1 2022-07-13T02:28:19.942073+00:00 netopeer2-server 15 - - Callback event "done" with ID 7 processing timed out.
<15>1 2022-07-13T02:28:19.942729+00:00 test-process-1 1 - - Call sr_module_change_subscribe finished with return code 0.
```

Looks like 
netopeer2-server is already hold  LOCK-1 and wait for LOCK-2.
The test-process-1 call sr_module_change_subscribe hold LOCK-2 and wait for LOCK-1.

test-process-1 can proceed after netopeer2-server timeout and released the LOCK-1.

Can you please have a look for this? 

Is this similar to the issue https://github.com/sysrepo/sysrepo/issues/2821 ?

**Comment by michalvasko** [comment]
My guess would rather be a deadlock caused by your code. What exactly is the architecture? What process/thread creates the first subscription?

**Comment by starx1000** [comment]
The application has event loop, and calls the sr_module_change_subscribe with " SR_SUBSCR_DEFAULT | SR_SUBSCR_DONE_ONLY "  with different module mutiple times.( with the same connection and the same session and the same subscription)

The application only have one connection, serveral sessions. 

"Sysrepo and it will by default create a separate thread that will wait for events on the subscription and process them"

Then the sysrepo thread will call the callback "sr_module_change_cb" because edit-data happens in netopeer2-server?
while the application main thread will call "sr_module_change_subscribe" with " SR_SUBSCR_DEFAULT | SR_SUBSCR_DONE_ONLY" with the same sesssion1, the same subscription at the same time.
```c++
 int rc = sr_module_change_subscribe(session1, 
                                        module, path, callback, this, 0,
                                        SR_SUBSCR_DEFAULT | SR_SUBSCR_DONE_ONLY, 
                                       sub_handler1);
```

This mechanism is applied to "Operational Subscriptions" also.  ( Main thread call the  sr_oper_get_subscribe 
with  SR_SUBSCR_DEFAULT, the same connection, session2 (another one) , subscription2( created using session2).

```c++
    int rc = sr_oper_get_subscribe(session2, 
                                   module,  path, callback, this,
                                   SR_SUBSCR_DEFAULT, sub_handler2);
```

main -  Conn,   call sr_module_change_subscribe( session1,SR_SUBSCR_DEFAULT ) call sr_oper_get_subscribe ( session2 )

Is this workable?  

Do I need to create extra 2 threads using "SR_SUBSCR_NO_THREAD" & "sr_subscription_process_events"? e.g : 
main - create sysrepo-connection.
thread1 -  call sr_module_change_subscribe(session1, SR_SUBSCR_NO_THREAD) & sr_subscription_process_events
thread2 - call sr_oper_get_subscribe(session2, SR_SUBSCR_NO_THREAD)  & sr_subscription_process_events

Thanks very much for your help.

**Comment by michalvasko** [comment]
What exactly are you doing in the callback for `sr_module_change_subscribe()`, are you calling some other subscribe function? If not, it may be an actual timeout, I have not noticed before that you have 34 subscribers for these changes and if all of those are handled by a single thread, it may take some time.

**Comment by starx1000** [comment]
in the callback for sr_module_change_subscribe() I just using unix domain socket( no other user) send notifications to the remote side. No other subscribe function called. 

`have 34 subscribers`  but the log shows that the callback is not triggered. 
(there is a log print when the callback called but in this case I do not see it.)

In this code I think the fix :[shm sub BUGFIX process events after timeout](https://github.com/sysrepo/sysrepo/commit/ddeb925a7735c8d2f46ad94d28ae0f1a12102a38)
is not there. 
So when timeout happens the process will aborted?
Do you think will the fix `shm sub BUGFIX process events after timeout` will help for this use case?

**Comment by michalvasko** [comment]
Are you maybe subscribed to the particular notification sent in the callback of `sr_module_change_subscribe()`?

**Comment by starx1000** [comment]
In the callback I do not do anything special(no sysrepo api called inside the callback).
when timeout happens, I see the callback is not even triggered. 

`Are you maybe subscribed to the particular notification sent in the callback of sr_module_change_subscribe()?

the callback to be called and sr_module_change_subscribe is for the same module `ietf-interfaces`.
and priority 0 is always used.
the use case is:
  use netopeer2-cli, edit-data, configure the ietf-interfaces with large data list (1000).
at the same time
  the application keeps subscribe to ietf-interfaces with different interface name prefix.

**Comment by michalvasko** [comment]
It still seems to me like a normal timeout, now you mention 1000 instances of a list. Try running the server with an increased timeout (`netopeer2-server -t 100`).

**Comment by starx1000** [comment]
OK, I will have a try and let you know the result. thanks.

**Comment by starx1000** [comment]
@michalvasko  in `sr_subscription_process_events` 
it call lock like this way
   1. /* SUBS READ LOCK */
    2. /* CONTEXT LOCK */
https://github.com/sysrepo/sysrepo/blob/df89fc02e301cc8f2e6b30ec37b990f52ca1d5c4/src/sysrepo.c#L4060

But in `sr_module_change_subscribe`
it call the same locks in a reverse way: 
  1.  /* CONTEXT LOCK */
  2.  /* SUBS WRITE LOCK */
 https://github.com/sysrepo/sysrepo/blob/df89fc02e301cc8f2e6b30ec37b990f52ca1d5c4/src/sysrepo.c#L4694

Should we change the `sr_subscription_process_events` 's locking order? e.g 
   1. /* CONTEXT LOCK */
   2. /* SUBS READ LOCK */

```c
API int
sr_subscription_process_events(sr_subscription_ctx_t *subscription, sr_session_ctx_t *session, struct timespec *stop_time_in)
{
    sr_error_info_t *err_info = NULL;
    int ret, mod_finished;
    char buf[1];
    uint32_t i;
    sr_lock_mode_t ctx_mode = SR_LOCK_NONE;

    /* session does not have to be set */
    SR_CHECK_ARG_APIRET(!subscription, session, err_info);

    if (stop_time_in) {
        memset(stop_time_in, 0, sizeof *stop_time_in);
    }

    /* Move Context LOCK here */
    /* CONTEXT LOCK */
    if ((err_info = sr_lycc_lock(subscription->conn, SR_LOCK_READ, 0, __func__))) {
        goto cleanup_unlock;
    }
    ctx_mode = SR_LOCK_READ;

    /* get only READ lock to allow event processing even during unsubscribe */

    /* SUBS READ LOCK */
    if ((err_info = sr_rwlock(&subscription->subs_lock, SR_SUBSCR_LOCK_TIMEOUT, SR_LOCK_READ, subscription->conn->cid,
            __func__, NULL, NULL))) {
        return sr_api_ret(session, err_info);
    }

    /* read all bytes from the pipe, there can be several events by now */
    do {
        ret = read(subscription->evpipe, buf, 1);
    } while (ret == 1);
    if ((ret == -1) && (errno != EAGAIN)) {
        SR_ERRINFO_SYSERRNO(&err_info, "read");
        sr_errinfo_new(&err_info, SR_ERR_INTERNAL, "Failed to read from an event pipe.");
        goto cleanup_unlock;
    }
```

**Comment by michalvasko** [comment]
Context lock is only `READ` in both cases, which can be held simultaneously.

**Comment by starx1000** [comment]
Recently do not focus this item and then let close this ticket and if something happens later in new release I will raise new one.

Thank you for your help.

**Comment by MH-F** [comment]
Hi Starx1000,

Do you have examples about sr_oper_get_subscribe and sr_module_change_subscribe?

Do I need to create extra 2 threads using "SR_SUBSCR_NO_THREAD" & "sr_subscription_process_events"? e.g :
main - create sysrepo-connection.
thread1 - call sr_module_change_subscribe(session1, SR_SUBSCR_NO_THREAD) & sr_subscription_process_events
thread2 - call sr_oper_get_subscribe(session2, SR_SUBSCR_NO_THREAD) & sr_subscription_process_events

Thanks very much for your help.

**Comment by starx1000** [comment]
I  use `SR_SUBSCR_DEFAULT` so 2 threads created.

1 for sr_module_change_subscribe's callback and 1 for sr_oper_get_subscribe 's callback.

I do not use` sr_subscription_process_events` currently.
