### ISSUE TITLE
YANG model update/upgrade procedure

### ISSUE THREAD

**Issue by rastislavszabo** [sysrepo/sysrepo#287]
Implement the YANG model update/upgrade procedure: When there is a new version of a YANG model (with the same revision date or with a newer revision date), the datastore should allow to switch to the new model while preserving existing startup (or even running?) datastore data - if possible. If it is not possible, the incompatible data leaves should be either removed, or whole operation should be skipped.

For this we should implement a new operation of sysrepoctl, e.g. `sysrepoctl --upgrade`.

In the simplest case, it should do the equivalent of:

```
sysrepocfg --export
sysrepoctl --uninstall
sysrepoctl --install
sysrepocfg --import
```

**Comment by liuaifinch** [comment]
@rkrejci 

Hi rkrejci,

Does this feature have been implemented?

**Comment by michalvasko** [comment]
Hi,
no, it has not yet been implemented.

Regards,
Michal

**Comment by michalvasko** [comment]
Latest *sysrepo* supports this.
