### ISSUE TITLE
NACM filter for existing lyd_node 

### ISSUE THREAD

**Issue by daliang20** [sysrepo/sysrepo#2871]
I have an unfiltered `lyd_node* tree` parsed from string input and a `char* username` provided from a user. 
I want to filter this particular tree based on the nacm user. 

Is there a native way to do this in sysrepo? I know there is `sr_nacm_check_data_read_filter`, but this code is private to sysrepo and the visibility is hidden in the shared object.

**Comment by michalvasko** [comment]
No, this functionality is not publicly available.

**Comment by michalvasko** [comment]
> Was there a specific reason why the data filtering is not publicly available?

I suppose, the encapsulation of the whole NACM implementation and having no use-case for explicit NACM filtering.
