### ISSUE TITLE
Error building notification defined inside augment when using schema-mount

### ISSUE THREAD

**Issue by cristina-defran** [sysrepo/sysrepo#2872]
Hello,

I am working with the schema-mount extension and I have not been able to reference a node defined as an _augment_ when it's inside a mountpoint. My full use case here is sending the `onu-presence-state-change` notification defined in the [`bbf-xpon-onu-state.yang` module](https://github.com/BroadbandForum/yang/blob/TR-385-v2.0.0/standard/interface/bbf-xpon-onu-state.yang), inside the _augment_ `/ietf-interfaces:interfaces-state/ietf-interfaces:interface/bbf-xpon:channel-termination`. The [`ietf-interfaces` module](https://github.com/YangModels/yang/blob/main/standard/ietf/RFC/ietf-interfaces%402018-02-20.yang) would be the schema mounted inside the mountpoint defined as a child of the `data` container in the [`bbf-device-aggregation` model](https://github.com/opencord/voltha-northbound-bbf-adapter/blob/master/build/yang-files/bbf-device-aggregation.yang).

When trying to build the notification, I do the following:
```
err = lyd_new_path(NULL, ctx, "/bbf-device-aggregation:devices/device[name='testdevice']/data/ietf-interfaces:interfaces-state/interface[name='channeltermination.1']", NULL, 0, &interfaceNode);
err = lyd_new_path(interfaceNode, NULL, "/bbf-device-aggregation:devices/device[name='testdevice']/data/ietf-interfaces:interfaces-state/interface[name='channeltermination.1']/type", "bbf-xpon-if-type:channel-termination", 0, NULL);
err = lyd_new_path(interfaceNode, NULL, "/bbf-device-aggregation:devices/device[name='testdevice']/data/ietf-interfaces:interfaces-state/interface[name='channeltermination.1']/bbf-xpon:channel-termination/bbf-xpon-onu-state:onu-presence-state-change", NULL, 0, NULL);
...
```

I omitted the last part of the path building code for the notification, because I get the relevant error on that last `lyd_new_path()` call:
```
libyang[0]: Different contexts mixed in a single function call.
libyang[0]: Not found node "channel-termination" in path.
```

Also, the _augment_ has a `when `condition that applies to `/ietf-interfaces:interfaces/ietf-interface:interface/bbf-xpon:channel-termination/bbf-xpon:location`, so I am subscribing as an operational data provider for the correct validation of the notification. When I try to create the node that would satisfy that condition, I get the same error. That makes me think it could be a problem with how augments are treated inside a mounted schema.

I tried to send the notification without using the schema-mount extension to check my xpaths were ok and everything works fine. To help clarify the use case, this is the notification I have been able to build and send (without schema mount):

```
<notification xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
  <eventTime>2022-07-13T15:31:26.103253708+00:00</eventTime>
  <interfaces-state xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
    <interface>
      <name>channeltermination.1</name>
      <type xmlns:bbf-xponift="urn:bbf:yang:bbf-xpon-if-type">bbf-xponift:channel-termination</type>
      <channel-termination xmlns="urn:bbf:yang:bbf-xpon">
        <onu-presence-state-change xmlns="urn:bbf:yang:bbf-xpon-onu-state">
          <detected-serial-number>ABCD12345678</detected-serial-number>
          <last-change>2012-07-13T08:43:00+00:00</last-change>
          <onu-presence-state xmlns:bbf-xpon-onu-types="urn:bbf:yang:bbf-xpon-onu-types">bbf-xpon-onu-types:onu-present</onu-presence-state>
          <onu-id>333</onu-id>
          <detected-registration-id>555</detected-registration-id>
        </onu-presence-state-change>
      </channel-termination>
    </interface>
  </interfaces-state>
</notification>
```

In this case, the `channel-termination/onu-presence-state-change` node is built correctly using the xpath `/ietf-interfaces:interfaces-state/interface[name='channeltermination.1']/bbf-xpon:channel-termination/bbf-xpon-onu-state:onu-presence-state-change`.

I don't know if this could be related in any way with #2870, as it's also an "advanced" construction inside a mountpoint.

Thank you in advance.

**Comment by michalvasko** [comment]
Please try it with the latest code, *schema-mount* support was greatly improved so it may work now.

**Comment by michalvasko** [comment]
Please try the latest *libyang*, this was a completely different problem and at least the data creation should now work.

**Comment by cristina-defran** [comment]
It is now working. Thank you so much!
