### ISSUE TITLE
Where to install a user plugin

### ISSUE THREAD

**Issue by hthiery** [sysrepo/sysrepo#2874]
Hi,

I have a user specific plugin and would like to get it loaded by sysrepo. I installed the plugin into SR_PLUGINS_PATH but it will not be automatically be loaded when launching netopeer2-server. Only when I install it after SRPD_PLUGINS_PATH and also start sysrepo-plugind it is loaded. This is to be expected?

**Comment by michalvasko** [comment]
There may be some confusion in this but it seems you have written a `sysrepo-plugind` plugin, which you can also install using it and the parameter `-P`. There are also *sysrepo* `datastore` and `notification` plugins, which `SR_PLUGINS_PATH` is for, which are something completely different.

**Comment by hthiery** [comment]
Yes it is a `sysrepo-plugind` plugin. Can it be that the definition was changed in the course of development. So I have to install it to the `SRPD_PLUGINS_PATH` and start the `sysrepo-plugind`.

**Comment by michalvasko** [comment]
What you said and it is not that much that the definition has changed but there were no *sysrepo* plugins before so now they have to be distinguished between *sysrepo-plugind* plugins.

**Comment by hthiery** [comment]
Do you have an easy way to get the right location of the `SRPD_PLUGINS_PATH` from the sysrepo.pc file to use it in my CMakeLists.txt file?

**Comment by michalvasko** [comment]
Like I said, you can use `sysrepo-plugind -P <path-to-plugin>` to install them. But I could also add it into the *.pc, if that helps.

**Comment by hthiery** [comment]
Ok thanks. I will try to use pkg-config to get the location for installing my plugin during cross-compilation to the right target. 

Due to the cross compilation `sysrepo-plugind -P <path-to-plugin>` would be not that good.

**Comment by hthiery** [comment]
Just to let you know how I get the right path for installing the plugin:

`execute_process(COMMAND pkg-config "--variable=SRPD_PLUGINS_PATH" "sysrepo" OUTPUT_VARIABLE SRPD_PLUGINS_PATH OUTPUT_STRIP_TRAILING_WHITESPACE)`
