### ISSUE TITLE
whether this SR_IS_LISTEN_EVENT is better to judge outside of sr_shmsub_change_listen_is_new_event

### ISSUE THREAD

**Issue by itercheng** [sysrepo/sysrepo#2878]
Hello

For change or rpc subscription, one module subscription or one rpc subscription has only one corresponding multi_sub_shm. so whether  it is more efficient and available to call SR_IS_LISTEN_EVENT under the module or father rpc, rather than  in each submodule (subrpc) subscription.  example:

shm_sub.c

    /* not a listener event */
    if (!SR_IS_LISTEN_EVENT(multi_sub_shm->event)) {
        return 0;
    }

    for (i = 0; i < change_subs->sub_count; ++i) {
        if (sr_shmsub_change_listen_is_new_event(multi_sub_shm, &change_subs->subs[i])) {
            break;
        }
    }

  I am not sure my proposal is feasible or you have more fully considerations for your design

**Comment by michalvasko** [comment]
I do not fully understand what you are proposing but I am quite sure it now works correctly and optimizations without measurements backing them are generally useless and make no difference.
