### ISSUE TITLE
An RPC subscription can only get the same lowest priority reply

### ISSUE THREAD

**Issue by itercheng** [sysrepo/sysrepo#2879]
Hello

  If there are multiple subscriptions of different priorities for the same one rpc. we will get a replay from the lowest priority when trigger subscription by sr_rpc_send_tree. because the output reply is overwrite.

        /* parse returned reply, overwrite any previous ones */
        lyd_free_withsiblings(*output);
        ly_errno = 0;
        *output = lyd_parse_mem(lyd_node_module(input)->ctx, shm_data_sub.addr, LYD_LYB,
                LYD_OPT_RPCREPLY | LYD_OPT_NOEXTDEPS | LYD_OPT_STRICT, input, NULL);
        if (ly_errno) {
            sr_errinfo_new_ly(&err_info, lyd_node_module(input)->ctx);
            sr_errinfo_new(&err_info, SR_ERR_VALIDATION_FAILED, NULL, "Failed to parse returned \"RPC\" data.");
            goto cleanup_wrunlock;
        }

in this case. why are we not limited to registering only one subscription for a RPC like sr_oper_get_items_subscribe ?

**Comment by michalvasko** [comment]
> why are we not limited to registering only one subscription for a RPC like sr_oper_get_items_subscribe ?

Because you have the option for more subscribers to be notified about an RPC even though only the last one provides the output. It is still useful and there are use-cases for it, which is why it is supported.
