### ISSUE TITLE
Call kill-session RPC via sysrepo API

### ISSUE THREAD

**Issue by jabilmplane** [sysrepo/sysrepo#2881]
Hi,

Could you, please, help me with described issue.

I'm updating libyang/libnetconf/sysrepo/netopeer2 to latest stable version. After update I noticed that software is not able to kill clients session. It used to work, but now is not working.

I use latest "stable" versions of all repos:
- libyang: https://github.com/CESNET/libyang/commit/87375f15159545a87a1e0de200f5d9d67e9091d7 (tag: v2.0.194, origin/master, origin/HEAD, master)
- libnetconf2: c21986efedaa948fb9ab8764c332a3d17d5c468b (tag: v2.1.11, origin/master, origin/devel, origin/HEAD, master)
- sysrepo: 84ca8d6aacab2fc435b7332c4d26012115bc8509 (tag: v2.1.64, origin/master, origin/HEAD, master)
- netopeer2: ea020962ea02ea1a03b48c978d2b2575fc86d075 (tag: v2.1.23, origin/master, origin/HEAD, master)

Below is a simple application to trigger the RPC. It takes session-id as parameter and sends kill-session RPC. After app is called, session is not terminated. If I call `kill-session --sid X` from the netopeer2-cli, it works fine.

```
/**
 * @file rpc_send_example.c
 * @author Michal Vasko <mvasko@cesnet.cz>
 * @brief example of an application that sends an RPC
 *
 * @copyright
 * Copyright (c) 2019 CESNET, z.s.p.o.
 *
 * This source code is licensed under BSD 3-Clause License (the "License").
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://opensource.org/licenses/BSD-3-Clause
 */
#define _GNU_SOURCE

#include <inttypes.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include <libyang/libyang.h>

#include "sysrepo.h"

static void
print_val(const sr_val_t *value)
{
    if (NULL == value) {
        return;
    }

    printf("%s ", value->xpath);

    switch (value->type) {
    case SR_CONTAINER_T:
    case SR_CONTAINER_PRESENCE_T:
        printf("(container)");
        break;
    case SR_LIST_T:
        printf("(list instance)");
        break;
    case SR_STRING_T:
        printf("= %s", value->data.string_val);
        break;
    case SR_BOOL_T:
        printf("= %s", value->data.bool_val ? "true" : "false");
        break;
    case SR_DECIMAL64_T:
        printf("= %g", value->data.decimal64_val);
        break;
    case SR_INT8_T:
        printf("= %" PRId8, value->data.int8_val);
        break;
    case SR_INT16_T:
        printf("= %" PRId16, value->data.int16_val);
        break;
    case SR_INT32_T:
        printf("= %" PRId32, value->data.int32_val);
        break;
    case SR_INT64_T:
        printf("= %" PRId64, value->data.int64_val);
        break;
    case SR_UINT8_T:
        printf("= %" PRIu8, value->data.uint8_val);
        break;
    case SR_UINT16_T:
        printf("= %" PRIu16, value->data.uint16_val);
        break;
    case SR_UINT32_T:
        printf("= %" PRIu32, value->data.uint32_val);
        break;
    case SR_UINT64_T:
        printf("= %" PRIu64, value->data.uint64_val);
        break;
    case SR_IDENTITYREF_T:
        printf("= %s", value->data.identityref_val);
        break;
    case SR_INSTANCEID_T:
        printf("= %s", value->data.instanceid_val);
        break;
    case SR_BITS_T:
        printf("= %s", value->data.bits_val);
        break;
    case SR_BINARY_T:
        printf("= %s", value->data.binary_val);
        break;
    case SR_ENUM_T:
        printf("= %s", value->data.enum_val);
        break;
    case SR_LEAF_EMPTY_T:
        printf("(empty leaf)");
        break;
    default:
        printf("(unprintable)");
        break;
    }

    switch (value->type) {
    case SR_UNKNOWN_T:
    case SR_CONTAINER_T:
    case SR_CONTAINER_PRESENCE_T:
    case SR_LIST_T:
    case SR_LEAF_EMPTY_T:
        printf("\n");
        break;
    default:
        printf("%s\n", value->dflt ? " [default]" : "");
        break;
    }
}

int
main(int argc, char **argv)
{
    sr_conn_ctx_t *connection = NULL;
    sr_session_ctx_t *session = NULL;
    int rc = SR_ERR_OK;
    sr_val_t *output = NULL;
    size_t i, output_count = 0;
    int session_id;

    if (argc != 2) {
        printf("%s <session-id>\n", argv[0]);
        return EXIT_FAILURE;
    }
    session_id = atoi(argv[1]);
    printf("Sending kill-session RPC with session-id %d\n", session_id);

    /* turn logging on */
    sr_log_stderr(SR_LL_WRN);

    /* connect to sysrepo */
    rc = sr_connect(0, &connection);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }

    /* start session */
    rc = sr_session_start(connection, SR_DS_RUNNING, &session);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }
    
    sr_val_t input;
    input.xpath = "/ietf-netconf:kill-session/session-id";
    input.type = SR_UINT32_T;
    input.data.uint32_val = session_id;
    input.dflt = 0;

    /* send the RPC */
    rc = sr_rpc_send(session, "/ietf-netconf:kill-session", &input, 1, 0, &output, &output_count);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }

    /* print output */
    printf("\n ========== RECEIVED OUTPUT: ==========\n\n");
    for (i = 0; i < output_count; ++i) {
        print_val(&output[i]);
    }

cleanup:
    sr_free_values(output, output_count);
    sr_disconnect(connection);
    return rc ? EXIT_FAILURE : EXIT_SUCCESS;
}
```

**Comment by michalvasko** [comment]
*netopeer2* [ignores](https://github.com/CESNET/netopeer2/blob/devel/src/common.h#L39) NETCONF RPCs not received on a NETCONF session. Not sure if that should change, I would say it makes sense.

**Comment by jabilmplane** [comment]
But why API for calling a RPC still exists? I mean `sr_rpc_send`. If it is ignored, there is no need to keep it in the API and in examples provided in the repo.

Is there alternative way to terminate session from the application?

**Comment by michalvasko** [comment]
Only NETCONF RPCs (those subscribed to by *netopeer2-server*) are ignored this way, otherwise applications can subscribe and send whatever RPCs they want. And no, you cannot kill a NETCONF session from any *sysrepo* application, which seems correct to me.

**Comment by mustafatayf** [comment]
Hi Michal,

Is there an alternative way to terminate/kill netconf session within a sysrepo plugin thread?

Here are some possible ways we considered but could not able to implement.
- If somehow we get the netconf session process id (pid), then we can send `kill(pid, SIGKILL)` command via C signalling (#include <signal.h>).
- If somehow we can get netconf session (struct nc_session *) data inside a thread which works as a part of sysrepo-plugin, then will it work to send `nc_send_rpc()` with `kill-session` payload via `/ietf-netconf:kill-session/session-id` for a given `session-id` of netconf session?
- Inside a thread created from a sysrepo-plugind callback, is it possible to access **np2srv** which stores contents of netconf sessions?  (you already mentioned such usage in [here](https://github.com/CESNET/netopeer2/issues/107#issuecomment-288060819).)

Note that we already know the netconf session-id which we want to kill, but neither connection nor session info are available.

Thanks in advance.

**Comment by michalvasko** [comment]
> If somehow we get the netconf session process id (pid), then we can send kill(pid, SIGKILL) command via C signalling (#include <signal.h>).

Only the NETCONF server has a PID and you probably do not want to kill the whole process so best avoid this.

> If somehow we can get netconf session (struct nc_session *) data inside a thread which works as a part of sysrepo-plugin, then will it work to send nc_send_rpc() with kill-session payload via /ietf-netconf:kill-session/session-id for a given session-id of netconf session?

You cannot get the NETCONF session structure in any *sysrepo* plugin.

> Inside a thread created from a sysrepo-plugind callback, is it possible to access np2srv which stores contents of netconf sessions? (you already mentioned such usage in here)

No, you cannot access internal *netopeer2* data outside its code, I was talking about modify the server code directly in that issue.

The only way to implement this is to create a standard NETCONF session in the *sysrepo* application (normally connect to *netopeer2* as a client) and then send `kill-session` on that new session. As long as you have all the required access, it will work.

**Comment by mustafatayf** [comment]
Thank you,

by using the `-U` option of `netopeer2-server`, **netopeer2-server.sock** is activated. Then, the following worked;

```
struct lyd_node * input = NULL;
uint64_t _msgid;
struct nc_session * _session;
struct nc_rpc *_rpc;

_session = nc_connect_unix("/var/run/netopeer2-server.sock", ly_ctx);

lyd_new_path(NULL, ly_ctx, "/ietf-netconf:kill-session/session-id", str_id, 0,	&input);

_rpc = nc_rpc_act_generic(input, 0);
nc_send_rpc(_session, _rpc, 0, &_msgid);

nc_session_free(_session, NULL);
nc_client_destroy();
```
