### ISSUE TITLE
Unable to throw error while performing edit-config with custom validation

### ISSUE THREAD

**Issue by bvirmani2022** [sysrepo/sysrepo#2883]
Hi,
I am using below api for sending error to cli from the netconf server application.
I am trying to add more validations in the application, for which I need to return an error so that the edit-config operation gets failed and the data is not set on the server side. (These validations are custom validations and are not part of the yang)
sr_session_set_error_message(session, "Custom message");
 return SR_ERR_OPERATION_FAILED;

Observation:
When the edit-config operation is performed, even though the validation check fails, still the values get set.
So, there can be two ways to handle this:
First, throw an error and set is failed (I am unable to achieve this approach as sr_session_set_error_message does not throw any error or prevent any values to set)
Second, if the first approach is not feasible, then I shall have to read old value and reset it back in case of validation fails.

Please help!!

**Comment by michalvasko** [comment]
What exactly is the problem? This is a basic feature of *sysrepo*. Every change is applied in a 2-step commit when your module change callback receives `SR_EV_CHANGE` event first and then `SR_EV_DONE`. If you return non-zero return value from the callback for the former event, all the changes are rolled back and the edit fails.

**Comment by bvirmani2022** [comment]
Hi, I have subscribed module with sr_module_change_subscribe
I am able to retrieve the new and old value in SR_EV_DONE
sr_get_change_next -> is used for the number of value changed

My question is : How can I throw an error for single xpath (for eg: range is failed) in a subscribed module before the changes are commited.

As per your comment above, if any validation added in SR_EV_CHANGE, then it should reflect in edit-config operation and the changes shall be rolled back ?

**Comment by michalvasko** [comment]
Yes, like I said, you must return the error on `SR_EV_CHANGE`.

**Comment by bvirmani2022** [comment]
So, to return custom error, api sr_session_set_error_message can be used as well ?

**Comment by michalvasko** [comment]
Yes, if you just want to set a custom error message. If you want to provide a full NETCONF error, use [this](https://github.com/sysrepo/sysrepo/blob/master/src/utils/error_format.h#L64) function.

**Comment by bvirmani2022** [comment]
Ok, thanks.
Will try it out !!

**Comment by bvirmani2022** [comment]
Thanks, this is resolved. Hence, closing the issue.
