### ISSUE TITLE
Restrict the connection request  from netconf server for a particular user 

### ISSUE THREAD

**Issue by bvirmani2022** [sysrepo/sysrepo#2885]
Hi,
Please help me with the below use case:

I have created a netconf user (Eg: sampleuser). It is both updated in the sysrepo as well as the system.
In the sysrepo, it may look like below:
![image](https://user-images.githubusercontent.com/103240451/182099341-3c5e439e-cfff-434f-8c74-19e759f5aa07.png)

My query, if the user is disabled (that is, "enabled" leaf is false), is it possible to directly throw "Authentication Failed" error from netconf server and netconf client is unable to perform connection.
For eg, if we can directly throw some error from ssh server file.

**Comment by michalvasko** [comment]
> It is both updated in the sysrepo as well as the system.

What exactly are you talking about, data for the module `ietf-system`? It is not enough to just install the YANG, you would have to actually implement its functionality. Currently, the users for SSH authentication are read from the system configuration.

**Comment by bvirmani2022** [comment]
My query is that can we get sysrepo data inside libnetconf or is there a way to read sysrepo data during the connection of client and server.
(In file: session_server_ssh.c)

**Comment by michalvasko** [comment]
I am confused by the wording of your question. *libnetconf2* implements just the NETCONF communication, the datastore is not included so no data. *netopeer2* in particular reads the data from *sysrepo*, but that has nothing to do with *libnetconf2*.

**Comment by bvirmani2022** [comment]
Ok,
I will put the query in a different way:

Is it not possible to retrieve any xpath value inside libnetconf2?

**Comment by michalvasko** [comment]
Why do you keep asking about *libnetconf2*? No, there are no data, unless there are callbacks implementing the relevant RPCs (`get` or `get-config`), which is what *netopeer2* does.

**Comment by bvirmani2022** [comment]
Relevant rpcs are fine in netopeer2.

But, if I want to restrict the connection of some user, that can be done only in libnetconf2? Correct

**Comment by michalvasko** [comment]
Then you can modify the `password` authentication callback to refuse specific users. *netopeer2* uses its own callback so you can modify that, if you are using it.

**Comment by bvirmani2022** [comment]
So the restriction can be performed inside netopeer2 as well.
Can you please share the function, where I can restrict user connection.?
Is it present inside Netconf_server_ssh.c file

**Comment by michalvasko** [comment]
Sorry, only the `publickey` callback is [being set](https://github.com/CESNET/netopeer2/blob/devel/src/main.c#L593). But you can call [nc_server_ssh_set_passwd_auth_clb()](https://netopeer.liberouter.org/doc/libnetconf2/devel/html/group__server__ssh.html#gafa6fefe02e56b3b881b75f0388fc95f9) with your own callback right after.
