### ISSUE TITLE
Multiple netconf client support in sysrepo

### ISSUE THREAD

**Issue by bvirmani2022** [sysrepo/sysrepo#2886]
Hi,
Is it possible to handle data for different netconf clients separately in sysrepo provided only one instance of netconf server is running?

For eg: 
Client1 has xyz configuration and Client2 has abc configuration

So, if Client1 retrieve information, it should only get xyz configuration and similar for Client2 should retrieve abc configuration.

Currently, if two client are connected to the netconf server, then the latest configuration set is retrieved by both the clients.

Is it possible to retrieve exclusive information for each client?
Can NACM be considered for handling clients? or It needs to be handled as part of sysrepo?

**Comment by michalvasko** [comment]
> Is it possible to handle data for different netconf clients separately in sysrepo provided only one instance of netconf server is running?

No, it would go against the principle of a central datastore.

**Comment by bvirmani2022** [comment]
So, how would we handle the above scenario ?

**Comment by michalvasko** [comment]
If you really want to have several separate instances of *sysrepo*/*netopeer2* on a single machine, you can achieve it using [environment variables](https://github.com/sysrepo/sysrepo/#used-run-time-enviromental-variables).

**Comment by bvirmani2022** [comment]
Ok Thanks!
Will try that

**Comment by bvirmani2022** [comment]
Hi,
Can more env variables be created for sysrepo instances
SYSREPO_REPOSITORY_PATH_1
SYSREPO_REPOSITORY_PATH_2

or using only one SYSREPO_REPOSITORY_PATH env variable, can we have multiple instances of sysrepo

**Comment by michalvasko** [comment]
More env variables would be useless. The point is to set the variable to a different value for each separate instance.

**Comment by bvirmani2022** [comment]
Ok, so can 3 or 4 clients have access to separate instances at same time with one env

**Comment by bvirmani2022** [comment]
For eg: if I have 3 clients connected:
client1, client2, client3
client1, client2 and client3 performs one edit-config request at the same time, how shall the netopeer-server be able handle this scenario

**Comment by michalvasko** [comment]
You do not understand, the instances will be completely separate. Example with 3 clients using repos `/etc/sysrepo1,2,3`:

You run (also need to change the PID file path for more instances to run simultaneously):
```
SYSREPO_REPOSITORY_PATH=/etc/sysrepo1 netopeer2-server
SYSREPO_REPOSITORY_PATH=/etc/sysrepo2 netopeer2-server
SYSREPO_REPOSITORY_PATH=/etc/sysrepo3 netopeer2-server
```
then if you connect with a client to server1, you access the first *sysrepo* instance, if to server2, you access the second and so on.

**Comment by bvirmani2022** [comment]
I clearly got the point and Actually, I am following the similar approach:
For client1 : <installer_dir>/sysrepo1
and so on.

But my query is, even the netopeer-server shall be running in separate instances.

Can we not have one instance of netopeer server and multiple instances of sysrepo ?

**Comment by michalvasko** [comment]
> Can we not have one instance of netopeer server and multiple instances of sysrepo ?

In short, no. How should *netopeer2-server* know with which *sysrepo* instance to communicate? There can only be one.

**Comment by bvirmani2022** [comment]
Thanks Michal.
I think I got the major points.

I was trying a total different approach through an application only with single netopeer-server instance but looks like "n clients" shall have "n netopeer-server" instances

Will try to implement in similar way.

**Comment by bvirmani2022** [comment]
Hi,
After the creation of multiple netopeer/sysrepo instanaces and creating separate pid file for each netopeer-server, still I am facing issue related to client1 connecting to sysrepo1/netopeer instance.

Is it because the default port in which netconf server is listening is 830.

So, do I need to listen netopeer-server on different ports as well?

**Comment by michalvasko** [comment]
Naturally, 2 processes cannot listen on a single port on one machine.

**Comment by bvirmani2022** [comment]
So, then my understanding is correct, that I need to have 4 multiple ports for each process and try connecting with the individual ports

**Comment by jktjkt** [comment]
Just wondering what your use case for all that is, @bvirmani2022 . I cannot think of any, except development testing, automated builds, etc. In that case it's also possible to not listen on *any* TCP port at all, and rely on Unix sockets. What is your use case?

**Comment by bvirmani2022** [comment]
Hi,
Since I am running multiple netopeer2-server instances, each netopeer-server should run as a separate process and a different port
We are doing some development testing based on the below use:
Each client connected to the netconf server should have separate set of configuration.
For eg, 4 devices are connected to the server, but each device can have separate configuration set.

So to achieve this, I am having multiple sysrepo/netopeer instances

**Comment by jktjkt** [comment]
Why do you need each client to have a completely different view of YANG modules and all the data? I'm asking that because that's not the way how the IETF defined NETCONF to be deployed. I can think of one use case like that, and that is creating a NETCONF proxy which represents a legacy device that doesn't speak NETCONF on its own. That way I can imagine deploying *n* separate NETCONF servers on one underlying OS. Is that what you're doing, or is your use case something else?
