### ISSUE TITLE
Sysrepo plugin daemon should not rely on the plugin extension *.so

### ISSUE THREAD

**Issue by rastislavszabo** [sysrepo/sysrepo#289]
When sysrepo plugin daemon loads plugins, it scans for *.so files in the plugin directory. On some platforms (e.g. Mac OS X), shared libraries can also have different extensions. Instead, sysrepo daemon should load all binary files in the plugins directory that implement the function `sr_plugin_init_cb`.

**Comment by jktjkt** [comment]
Wouldn't it be better and easier to simply change the extension on MacOS? I don't recall other program which uses non-.so suffixes for plugins on Linux.

But anyway, this is largely a bikeshedding topic for me, so... :).

**Comment by rastislavszabo** [comment]
Yes, I think that the current behavior is good enough. It looks for dynamic libraries with required symbols, no matter what is the filename. To only drawback may be some warnings produced in case that you have some other files than plugins in the plugins directory, but it would not cause any other issues.
