### ISSUE TITLE
Notification messages include validation data

### ISSUE THREAD

**Issue by cristina-defran** [sysrepo/sysrepo#2890]
Hello,

I've noticed that with the updates made to the repos in the last couple of weeks, the notification messages received in the `netopeer2-cli` include the data requested for validation of the notification when sending it. Is this the expected behaviour or could it be a bug?

I attach below an example of the messages I see in the `netopeer2-cli`, verbose 3 mode.

This is what I receive with previous versions of the repos (versions from ~15 days ago):
```
<notification xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
  <eventTime>2022-08-03T09:26:43.177999142+00:00</eventTime>
  <devices xmlns="urn:bbf:yang:bbf-device-aggregation">
    <device>
      <name>testdevice</name>
      <data>
        <hardware-state-change xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware"/>
      </data>
    </device>
  </devices>
</notification>
```

And this is what I'm receiving now:
```
<notification xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
  <eventTime>2022-08-03T09:10:06.364996577+00:00</eventTime>
  <devices xmlns="urn:bbf:yang:bbf-device-aggregation">
    <device>
      <name>testdevice</name>
      <data>
        <hardware-state-change xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware"/>
        <hardware xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware">
          <component>
            <name>testdevice</name>
            <mfg-name>VENDOR</mfg-name>
            <model-name>MODEL</model-name>
          </component>
        </hardware>
      </data>
    </device>
  </devices>
</notification>
```

The contents of the `<hardware>` node correspond to what it is requested in the validation process. I've tested with other notifications and the same thing happens.

Thanks in advance for the help.

**Comment by michalvasko** [comment]
Right, should be fixed in the latest `devel`.

**Comment by cristina-defran** [comment]
Thanks!
