### ISSUE TITLE
[ERR] Mandatory node "name" instance does not exist. (Schema location "/engineer:engineer/name".)

### ISSUE THREAD

**Issue by sunnycalsoft** [sysrepo/sysrepo#2898]
I am trying to install following modules : 
```yang
module engineer {
    yang-version 1.1;
    namespace "urn:nokia.com:srexperts:engineer";
    prefix "engineer";
    import engineer_types {
      prefix "types";
    }
    revision 2019-05-06;
    container engineer {
        description "Its me";
        leaf name {
            type string;
            mandatory true;
        }
        leaf age {
            type types:age_type;
        }
        leaf commute {
            type types:transportation_type;
        }
    }
}
```
But getting error :
```
[INF] Connection 119 created.
[ERR] Mandatory node "name" instance does not exist. (Schema location "/engineer:engineer/name".)
sysrepoctl error: Failed to install module "engineer.yang" (Validation failed)
[INF] No datastore changes to apply.
```

But if am using list instead of container it is getting installed.

**Comment by sunnycalsoft** [comment]
And also if i remove mandatory true from leaf then it gets installed without any issue even with container.

**Comment by michalvasko** [comment]
Yes, *sysrepo* will not allow you to install a module with top-level mandatory data, it would result in an invalid datastore. You can set these data when installing the YANG with `--init-data <path>`, look at `sysrepoctl -h` for explanation.

**Comment by sunnycalsoft** [comment]
Tried this sysrepoctl -i engineer.yang -I /engineer:engineer/name
[ERR] Unknown libyang error.
sysrepoctl error: Failed to install module "engineer.yang" (libyang error)
For more details you may try to increase the verbosity up to "-v3".

WHat should be the command for the above yang example?

**Comment by michalvasko** [comment]
Look at my previous reply, I have said everything relevant there already.

**Comment by sunnycalsoft** [comment]
Thanks @michalvasko It is working now.
