### ISSUE TITLE
Remove disabled nodes by disabling of YANG features

### ISSUE THREAD

**Issue by rastislavszabo** [sysrepo/sysrepo#290]
By disabling YANG features, remove disabled nodes from the affected data trees in all datastores.

**Comment by michalvasko** [comment]
Similar principle could be applied for removing modules using `sysrepoctl`. If there is a bidirectional dependency of 2 modules (module A augments module B, both are installed), it is not possible to remove either of them. So, allow removing module A with the condition that the data tree (of module B) will be also removed (which may require an explicit flag for the user to know that this will happen).

**Comment by michalvasko** [comment]
Not relevant anymore.
