### ISSUE TITLE
sr_lock API is not working inside the rpc callback function

### ISSUE THREAD

**Issue by surabhi-Siemens** [sysrepo/sysrepo#2901]
We are using NetOpeer2 server as a netconf frontend and sysrepo as a backend.  
We are trying to execute a test case where multiple NetConf clients are connected to Netconf server, and we are executing RPC call(user-rpc) from all the clients simultaneously(Almost).
Actual implemntation of RPC call is via sysrepo code base using sysrepo APIs.
What we observed is that these RPC calls are serialized(They are getting executed one after the other in sequence).

Now we wanted to update candidate datastore using RPC calls, so we did some changes in the RPC implementation(callback function rpc_cb) of sysrepo script as shown below.

```C
rpc_cb(sr_session_ctx_t *session, uint32_t sub_id, const char *path, const sr_val_t *input, const size_t input_cnt,
        sr_event_t event, uint32_t request_id, sr_val_t **output, size_t *output_cnt, void *private_data)
{


    rc = sr_lock(session, NULL, 0);
    if (rc != SR_ERR_OK) {
            printf("\n locking is failed");
    }
    rc = sr_set_item_str(session, "/examples:stats/counter", "500", NULL, 0);
    if (rc != SR_ERR_OK) {
            printf("\n setting value is failed");
    }
    rc = sr_apply_changes(session, 0);
    if (rc != SR_ERR_OK) {
        printf("\n applying changes is failed");
    }

    rc = sr_get_data(session, pathh, 0, 0, 0, &data);
    if (rc != SR_ERR_OK) {
        printf("\n getting data is failed");
    }


    if (data) {
        lyd_print_file(stdout, data->tree, LYD_XML, LYD_PRINT_WITHSIBLINGS);
    }

    sr_release_data(data);
    rc = sr_unlock(session, NULL);
     if (rc != SR_ERR_OK) {
            printf("\n unlocking is failed");
    }


}
```

Now when we are executing user-rpc from client, we are getting error as below:
```
[ERR] Invalid arguments for function "_sr_un_lock".
```
Now when we tried to put this lock in  the main function, it is not throwing this error. Our purpose of putting this lock in callback function is to provide exclusive write access to the candidate datastore.

Now following are my questions:
1. Is it not allowed to call sr_lock/sr_unlock apis inside the rpc callback function?
2. There is any relation between lock command provided by NetOpeer2 client and sysrepo sr_lock?

**Comment by michalvasko** [comment]
1. You say you want to lock `candidate` but are using the implicit callback session, whose default datastore is `operational` hence the error. Just switch the datastore and it will work.
2. [Yes](https://github.com/CESNET/netopeer2/blob/master/src/netconf.c#L599).

**Comment by surabhi-Siemens** [comment]
1. In the main function i changed from RUNNING to CANDIDATE in the function sr_session_start(connection, SR_DS_CANDIDATE, &session), still it didn't work.
2. How lock command provided by NetOpeer2 client is related to sysrepo sr_lock?

**Comment by michalvasko** [comment]
1. I do not know what you did exactly but all I said you should change the datastore of the session (`sr_session_swicth_ds()`), you do not have to create a new session.
2. Okay, to explain the link I have sent, when you send `<lock>` RPC from a NETCONF client, *netopeer2* calls `sr_lock()` for all the modules so it is the same lock.

**Comment by surabhi-Siemens** [comment]
Thank you Michal for your quick reply, I changed datastore from running to candidate using API sr_session_swicth_ds in the main function of file rpc_subscribe_example as below:

 /* start session */
    rc = sr_session_start(connection, SR_DS_RUNNING, &session);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }

    rc = sr_session_switch_ds(session, SR_DS_CANDIDATE);
    if (rc != SR_ERR_OK) {
            printf("\n switching datastore is failed");
    }



    /*subscribe for the RPC */
    rc = sr_rpc_subscribe(session, path, rpc_cb, NULL, 0, 0, &subscription);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }
--------------------------------------------------------------------------

In the rpc_cb, i am putting sr_lock and then trying to modify datastore and then unlocking as below:

rc = sr_lock(session, NULL, 0);
    if (rc != SR_ERR_OK) {
            printf("\n locking is failed");
    }
    rc = sr_set_item_str(session, "/examples:stats/counter", "500", NULL, 0);
    if (rc != SR_ERR_OK) {
            printf("\n setting value is failed");
    }
    rc = sr_apply_changes(session, 0);
    if (rc != SR_ERR_OK) {
        printf("\n applying changes is failed");
    }

    rc = sr_get_data(session, pathh, 0, 0, 0, &data);
    if (rc != SR_ERR_OK) {
        printf("\n getting data is failed");
    }


    if (data) {
        lyd_print_file(stdout, data->tree, LYD_XML, LYD_PRINT_WITHSIBLINGS);
    }


    rc = sr_unlock(session, NULL);
     if (rc != SR_ERR_OK) {
            printf("\n unlocking is failed");
    }

    sr_release_data(data);
--------------------------------------------------------------------

Now when from the client side i am invoking user-rpc --content file.xml, In the server side i am getting error as below:

[ERR] Invalid arguments for function "_sr_un_lock".


Please let me know, if i am doing something wrong here.

**Comment by michalvasko** [comment]
**In** rpc_cb **before** sr_lock() you need to put `sr_session_switch_ds(session, SR_DS_CANDIDATE)`. The `session` in the callback **is not the same** as the `session` you are calling `sr_rpc_subscribe()` with.

**Comment by michalvasko** [comment]
So which datastore do you want to modify? This code locks and modifies only `candidate`.

**Comment by surabhi-Siemens** [comment]
candidate datastore only...

lyd_print_file(stdout, data->tree, LYD_XML, LYD_PRINT_WITHSIBLINGS); line should print tthe updated tree, right ??

**Comment by michalvasko** [comment]
Yes, I believe so, if `pathh` selects the changed leaf.

**Comment by surabhi-Siemens** [comment]
If i am not switching the datastore, in that case value is getting set and it is printing the complete tree too

**Comment by michalvasko** [comment]
Oh, you are most likely configuring `state` data in the candidate datastore, which is not supported by NETCONF and will not work.

**Comment by surabhi-Siemens** [comment]
What is this state data?
If i am changing the datastore from running to candidate , in that case i am am not getting any locking error but value is also not getting updated, but if i am changing from running to operational, i am able to set the data but i am getting locking error too.

[ERR] Invalid arguments for function "_sr_un_lock".

 locking is failed<stats xmlns="urn:examples">
  <counter>500</counter>
</stats>
[ERR] Invalid arguments for function "_sr_un_lock".

**Comment by michalvasko** [comment]
I have written everything relevant but you now need to piece it all together. I will try to help.

1
Regarding *sysrepo* API, most operations on sessions can be performed on several datastores and it is chosen based on which is set in the `session`. Example:
```
rpc_cb()
{
    /* when session is created for the RPC callback, it is using the OPERATIONAL datastore */
    
    /* because the datastore was switched, you are now locking CANDIDATE */
    rc = sr_session_switch_ds(session, SR_DS_CANDIDATE);
    rc = sr_lock(session, NULL, 0);
    
    /* datastore was switched again, so you are performing changes in the OPERATIONAL datastore */
    rc = sr_session_switch_ds(session, SR_DS_OPERATIONAL);
    rc = sr_set_item_str(session, "/examples:stats/counter", "500", NULL, 0);
    rc = sr_apply_changes(session, 0);
    
    /* datastore was kept, so you are reading data from the OPERATIONAL datastore */
    rc = sr_get_data(session, pathh, 0, 0, 0, &data);
    
    /* datastore was switched back, so you are unlocking CANDIDATE */
    rc = sr_session_switch_ds(session, SR_DS_CANDIDATE);
    rc = sr_unlock(session, NULL);
}
```

2
The path `/examples:stats/counter` identifies a [state](https://www.rfc-editor.org/rfc/rfc7950.html#section-7.21.1) node. State data are not part of the [`candidate`](https://datatracker.ietf.org/doc/html/rfc8342#page-13) datastore so you cannot configure them for it and so it seems your use-case is invalid.

**Comment by surabhi-Siemens** [comment]
Thank you michal, now i am trying to modify candidate datastore and getting the error :
[ERR] Module "ietf-netconf-acm" is DS-locked by session 220.

What does it mean?

**Comment by michalvasko** [comment]
Please try to be self-sufficient and come up with solutions to your problems yourself. It obviously means that there is another session holding the lock on the module you want to edit. I cannot tell you anything more.

**Comment by surabhi-Siemens** [comment]
Hi Michal, 
Sorry to bother you again, my lock and updating the candidate datastore is working inside the callback function, i am not getting the error, but when i am trying to check it via command get-config --source candidate , it is not showing the value.

Below is my code:

rc = sr_session_switch_ds(session, SR_DS_CANDIDATE);
    if (rc != SR_ERR_OK) {
            printf("\n switching datastore is failed");
    }

    rc = sr_lock(session, NULL, 0);
    if (rc != SR_ERR_OK) {
            printf("\n locking is failed");
    }
    rc = sr_set_item_str(session, "/ieee802-dot1q-tsn-config-uni:tsn-uni/domain[domain-id='domainid']/cuc[cuc-id='cucid']/stream[stream-id='a6-17-b9-86-2c-04:2A-17']/stream-status", "scheduled", NULL, SR_EDIT_STRICT);
    if (rc != SR_ERR_OK) {
            printf("\n setting value is failed");
    }
    rc = sr_apply_changes(session, 0);
    if (rc != SR_ERR_OK) {
        printf("\n applying changes is failed");
    }

    rc = sr_get_data(session, pathh, 0, 0, 0, &data);
    if (rc != SR_ERR_OK) {
        printf("\n getting data is failed");
    }


    if (data) {
        lyd_print_file(stdout, data->tree, LYD_XML, LYD_PRINT_WITHSIBLINGS);
    }

    rc = sr_session_switch_ds(session, SR_DS_CANDIDATE);

    if(rc != SR_ERR_OK) {
            printf("\n switching datastore back is failed");
    }

    rc = sr_unlock(session, NULL);

I will be very thankful if you can help me in this regards.

**Comment by surabhi-Siemens** [comment]
Looks like unlock is resetting the value from candidate datastore, so i am trying to copy it to running. I tried with both the methods: sr_copy_config and sr_session_switch_ds. In this case i am getting error [ERR] Node "stream-status" to be created already exists.
[ERR] Applying operation "create" failed.

My question is , it is not possible to copy data to running from candiidate datastore.
