### ISSUE TITLE
Finding error while sending notification from app.

### ISSUE THREAD

**Issue by vinayhb012114** [sysrepo/sysrepo#2903]
@michalvasko : I have upgraded netopeer2,sysrepo,libyang, libnetconf2 to latest code. From our application while sending notification, after 10 to 15  notification I am finding below error:
[ERR] Recursive reader limit 255 reached!
[ERR] Recursive reader limit 255 reached!
[ERR] Recursive reader limit 255 reached!
[ERR] Recursive reader limit 255 reached!

Can you please help me in resolving this??

**Comment by michalvasko** [comment]
In all likelihood you have not upgraded properly and are missing some `sr_release_context()` and/or `sr_release_data()` calls when calling corresponding `acquire` functions (that you had to change manually, which was intentional).

**Comment by vinayhb012114** [comment]
issue resolved..
Thanks
