### ISSUE TITLE
sysrepo skipping anydata YANG node when sending notification

### ISSUE THREAD

**Issue by pwang111** [sysrepo/sysrepo#2904]
We are using the following netopeer2 SDK versions:

netopeer2: 2.1.23
libyang: 2.0.231
libnetconf2: 2.1.11
sysrepo: 2.1.84

and the python-sysrepo to call APIs using Python. 

We are trying to send a notification containing anydata node:

```
notification untranslated-omci-notification {
    description
      "The vOMC Message function cannot translate an
       OMCI Alarm or AVC message into a specific YANG
       notification.";
    leaf event-time {
      type yang:date-and-time;
      description
        "The date and time of the notification event";
    }
    leaf onu-name {
      type bbf-vomcit:onu-name;
      description
        "The name of the ONU that is the target of the
         alignment result.";
    }
    anydata untranslated-data {
      type string;
      description
        "The data received by the vOMCI function that
         could not be translated.";
    }
  }
```
Note this is from the bbf-vomci-function.yang. 

The Python API is a wrapper around the sr_notif_send_tree():

```
def notification_send(
        self, xpath: str, notification: Dict, strict: bool = False
    ) -> None:
```

We provided xpath = '/bbf-vomci-function:untranslated-omci-notification', notification = '''{
    "event-time": "2022-08-30T18:05:51+00:00",
    "onu-name": "ontsim8",
    "untranslated-data": {..}'''

Sysrepo accepts the event_time and onu_name nodes but skips the untranslated-data node. Here is the NETCONF stream subscription result from a netconf client:

```
<notification xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
    <eventTime>2022-08-30T18:05:51.498527517+00:00</eventTime>
    <untranslated-omci-notification xmlns="urn:bbf:yang:bbf-vomci-function">
      <event-time>2022-08-30T18:05:51+00:00</event-time>
      <onu-name>ontsim8</onu-name>
    </untranslated-omci-notification>
  </notification>
```
Here is the log from sysrepo: 

```
2022-08-30T18:05:51.503+0000 - WARNING - libyang.data - [data.py:1111 in _to_dnode] - /bbf-vomci-function:untranslated-omci-notification: skipping unknown element 'untranslated-data'
```

If we changed the yang's anydata to something more basic, such as string leaf, sysrepo would not skip the node:

```
notification untranslated-omci-notification {
    description
      "The vOMC Message function cannot translate an
       OMCI Alarm or AVC message into a specific YANG
       notification.";
    leaf event-time {
      type yang:date-and-time;
      description
        "The date and time of the notification event";
    }
    leaf onu-name {
      type bbf-vomcit:onu-name;
      description
        "The name of the ONU that is the target of the
         alignment result.";
    }
    leaf untranslated-data {
      type string;
      description
        "The data received by the vOMCI function that
         could not be translated.";
    }
  }
```

Is this a known issue, or some of our setups are not quite correct?

**Comment by michalvasko** [comment]
The warning means that the node is not known (not defined) for some reason so the YANG actually loaded is probably not the one you posted (it has no `type` substatement, for instance). Other than that, make sure the actual anydata value is [the correct one](https://www.rfc-editor.org/rfc/rfc7951.html#section-5.5).

**Comment by michalvasko** [comment]
I have tested it and it all worked just fine. I have installed `mod` from [files](https://github.com/sysrepo/sysrepo/files/9505767/files.tar.gz) into *sysrepo*, started the server, and then connected with *netopeer2-cli*. After subscribing, sent the notification using
```
sysrepocfg -N../notif.json
```
CLI output
```xml
notification (2022-09-07T13:33:09.332162250+02:00)
<untranslated-omci-notification xmlns="urn:mod">
  <event-time>2022-09-06T15:38:35+00:00</event-time>
  <onu-name>ontsim8</onu-name>
  <untranslated-data>
    <notification>
      <eventTime>2014-07-29T13:43:01Z</eventTime>
      <event>
        <event-class>fault</event-class>
        <reporting-entity>
          <card>Ethernet0</card>
        </reporting-entity>
        <severity>major</severity>
      </event>
    </notification>
  </untranslated-data>
</untranslated-omci-notification>
```

The error you are getting points to the fact that the installed module is different from the one you presented here and does not have any schema node called `untranslated-data`.

**Comment by pwang111** [comment]
I tried your way using sysrepocfg and it worked in my system. So looks like maybe the problem is from https://github.com/sysrepo/sysrepo-python which we are using? Do you know this python wrapper of sysrepo C APIs? It appears not well maintained. Is it part of the official SDK, or unrelated to all of SDK that you manage?

BTW, the command 'sysrepocfg -N../notif.json' is not similar to what the sysrepocfg --help says: 
```
-N, --notification[=<path>/<editor>]
                               Send a notification in a file or using a text editor.
```
When I tried 
```
sysrepocfg -N=notif.json
```
or
```
sysrepocfg -N=./notif.json
```
I all got 
```
libyang error: Missing the operation node. (Line number 1.)
sysrepocfg error: Data parsing failed
```
I understand maybe something missing about the module in the notif.json:
```
{
    "bbf-vomci-function:untranslated-omci-notification": {
        "event-time": "2022-09-06T15:38:35+00:00",
        "onu-name": "ontsim8",
        "untranslated-data": {
            "ietf-notification:notification": {
                "eventTime": "2014-07-29T13:43:01Z",
                "example-event:event": {
                    "event-class": "fault",
                    "reporting-entity": {
                        "card": "Ethernet0"
                    },
                    "severity": "major"
                }
            }
        }
    }
}
```
So seems that the N../notif.json did the magic, can you explain this a bit? Thank you.

**Comment by michalvasko** [comment]
When there is an optional parameter, you must not put the `=` in the short form and you must use it in the long form. Meaning, if specifying the argument, you can use `-N<path>` or `--notification=<path>` but not `-N=<path>` nor `--notification <path>`.
