### ISSUE TITLE
Question: Reading data from running storage

### ISSUE THREAD

**Issue by kobi-ca** [sysrepo/sysrepo#2905]
Hello,

I have a requirement where when my application is starting, I'd like to read all the data that resides in the `running` datastore.
Right now, I have a way to receive notification of config data change, but is there a way to read from the DB on demand?

thank you in advance,
Kobi

**Comment by jktjkt** [comment]
Use the [`SR_SUBSCR_ENABLED`](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__subs__api.html#ggaa629478596b1e246553eac91a74b2b5bac5b782dfbbfe74c8ff2b1642a8bb0afe) flag when subscribing.

**Comment by michalvasko** [comment]
You can always use the *sysrepo* API or `sysrepocfg` to read any stored data.
