### ISSUE TITLE
Question: populating data in startup time

### ISSUE THREAD

**Issue by kobi-ca** [sysrepo/sysrepo#2906]
Hello,

Is there a way to populate data during startup time?
For example - can I provide an init XML that is conforming to a specific YANG model, and SR is reading it and populating the `running` DB with the provided data in the init XML file?
I would like to know if there is such a way, or if the only way would be running `edit-config` on the northbound NC interface.

many thanks,
Kobi

**Comment by jktjkt** [comment]
You can use the `--init-data` option to `sysrepoctl` at module installation time. At any other time, you can use any sysrepo API for data manipulation as well, including the `sysrepocfg` CLI utility.
