### ISSUE TITLE
user-rpc call is serialized?

### ISSUE THREAD

**Issue by surabhi-Siemens** [sysrepo/sysrepo#2907]
Question:
What happens if the locking and releasing of the datastore is also done withing the RPC? 

1.	Clients1..4 run the RPC almost simultaneously
2.	RPC uses the candidate. It locks the candidate, writes data to it, commits to running, unlocks the candidate (plus some sleep time to make the test more convenient to analyze).

Observation: user-rpc call is serialized, when one of the client is returning then only other is getting chance to call it, irrespective of locks .
If this is the case , please let us know, if this is standardized, If yes the in which RFC it is mentioned.

**Comment by michalvasko** [comment]
Yes, it is [standardized](https://datatracker.ietf.org/doc/html/rfc6241#section-4.5).
