### ISSUE TITLE
Getting error as open file /sysrepo/sr_evpipe for writing  failed (Too many open files)

### ISSUE THREAD

**Issue by chendrashekarp** [sysrepo/sysrepo#2909]
Hi @michalvasko , could you please give some hint about this error , observing this error while running application continuously for more than 40mins. Attaching the error screen shot 
![image](https://user-images.githubusercontent.com/86454044/188153362-30d386d5-3b3e-46e5-be70-fa56abfa6f24.png)

**Comment by michalvasko** [comment]
I would say you are not cleaning something properly because otherwise you would hardly reach the limit for opened file descriptors. You will have to debug this yourself. For example, using `/proc` and examining all the opened FDs of the process.
