### ISSUE TITLE
Implement blocking connect in the Connection Manager

### ISSUE THREAD

**Issue by rastislavszabo** [sysrepo/sysrepo#291]
If connect() to the socket cannot be completed immediately without blocking, Sysrepo returns error. This code path is not yet implemented. Note that it should not be needed for unix-domain sockets on Linux, but we should have it implemented just in case.

Marked with following TODO in `connection_manager.c`:

```
// TODO: monitor socket for writing and send message later
```

**Comment by michalvasko** [comment]
Not relevant anymore.
