### ISSUE TITLE
How to set meta?

### ISSUE THREAD

**Issue by pkun** [sysrepo/sysrepo#2913]
Hello
I need to set a metadata (attributes in XML data representation) to statements. For testing I took a junos-configuration-metadata.yang from Junos site. This yang file defines:
```
    md:annotation active {
        type boolean;
        description
            "This annotation can be used in configuration XML/JSON to
...
```
And I can't find the way to set 'active' meta to candidate (or any other) datastore's statements.

Firstly I tried to use sr_set_item_str() from sysrepo's example with Xpath like this:
```
./sr_set_item_example "/ttt:test/iface[name='eth1']/@junos-configuration-metadata:active" "false"
```
It doesn't work:
```
[ERR] Unexpected XPath token "@" ("@junos-configur"), expected "NameTest".
```
Engine doesn't understand @ for attributes.

Then I used code like this:
```
	if (sr_get_subtree(sess, expr->xpath, 0, &data) != SR_ERR_OK) {
		fprintf(stderr, "Can't get specified subtree\n");
		goto err;
	}
	if (lyd_new_meta(LYD_CTX(data->tree), data->tree, NULL,
		"junos-configuration-metadata:active", "false", 0, NULL)) {
		fprintf(stderr, "Can't deactivate\n");
		goto err;
	}
```
After that I see my meta in `lyd_print_tree()`. But probably sr_get_subtree() gets a temporary copy of lyd_node and after sr_release_data() I don't see meta any more.

Then I used sysrepocfg utility with -E option and add `<iface xmlns="urn:ttt" xmlns:jcmd="http://yang.juniper.net/junos/jcmd" jcmd:active="false">` to editing config. I think utility uses sr_edit_batch() for this operation. It doesn't work too.

What is the right way to set meta to statements?
Thanks.

**Comment by michalvasko** [comment]
Storing metadata in *sysrepo* datastore is not supported. Main reason being that NETCONF does not define any way of working with them so we would have to define our own way of creating/removing/modifying the metadata.

**Comment by pkun** [comment]
NETCONF RFC doesn't say "we must drop element's metadata" while edit-config. So engine can just replace element with new element including specified metadata. Such behavior will not break the standard. Juniper do it to annotate, activate/deactivate elements using NETCONF. https://www.juniper.net/documentation/us/en/software/junos/netconf/topics/topic-map/yang-module-junos-configuration-metadata.html They advertise the correspondent NETCONF capabilities.

**Comment by michalvasko** [comment]
I have already asked about this quite some time ago on the mailing list and the person that replied (developer of some commercial YANG SW, not sure if Juniper or not) described their proprietary use of the metadata and it was further acknowledged that no standard specifies how to do it. So I know there are implementations that use metadata but there is no standardized way of doing so and we do not have a use-case for the effort to come up with our own way to be worth it.

**Comment by michalvasko** [comment]
> Who loses/drops meta while sysrepocfg -E edit-config? Sysrepo or libyang?

*sysrepo* because it expects some metadata (edit-config and diff operations) and drops all when actually storing the data. Adding the support for custom metadata would be no simple task and it would put additional requirements on custom datastore plugins that would need to be able to work with metadata, too.

> I'm writing a opensource CLI to manage YANG-based configurations.

Are you aware of [this](https://github.com/CESNET/netconf-cli) project of another team of CESNET? Sounds like the same thing.

**Comment by pkun** [comment]
Thanks for answer and link to netconf-cli. I did't see netconf-cli before. Great tool but ooh... that build dependencies... :) 

The netconf-cli and my klish-plugin-sysrepo are similar tools but not interchangeable. IMHO netconf-cli is ideal tool for developers. My tool is oriented to end-user. For example I use 'plain line' as a path but not Xpath. Path "interfaces interface eth0 type" is equivalent of Xpath "/ietf-interfaces:interfaces/interface[name='eth0']/type". End-user will not switch datastores but only commit from candidate to running-config etc. Besides configure mode device like a router has a operational/enable mode commands. The klish allows to integrate operational mode and configure modes. I have run/do prefix to execute operational mode commands from configure mode and can change CLI modes. Probably netconf-cli can use RPC call for this purpose. So tools really do the same thing but looks different.

And thanks for the great Sysrepo project.
