### ISSUE TITLE
Config Synchronization between sysrepo and (legacy) application

### ISSUE THREAD

**Issue by hthiery** [sysrepo/sysrepo#2914]
I have a comprehension problem and could not find a public answer.

The following problem:
I am writing a sysrepo plugin for a switch implementation. We get the switch software from a supplier. I have the possibility to get the required data of the switch management system into the plugin. Now it is so that there is the possibility both over the Webinterfaace and over the CLI to make settings. Both runtime and startup settings are kept there if they were made there. But now I have no synchronization between the netconf view (sysrepo) and the switch management view. When starting the plugin I can retrieve the data and store it in sysrepo. But this works only at startup.  But at runtime it doesn't work.

Is such a scenario foreseen? Or is it assumed that the complete configuration is always kept in sysrepo.

**Comment by michalvasko** [comment]
> Is such a scenario foreseen?

Yes and it was one of the main reasons why we designed a custom datastore API for *sysrepo* that allows to read the configuration from any source including configuration files or even CLI tools. So that is probably what you want to do, implement your own plugin and the configuration consistency should then be guaranteed.

**Comment by hthiery** [comment]
> > Is such a scenario foreseen?
> 
> Yes and it was one of the main reasons why we designed a custom datastore API for _sysrepo_ that allows to read the configuration from any source including configuration files or even CLI tools. So that is probably what you want to do, implement your own plugin and the configuration consistency should then be guaranteed.

Ah ok, I was not aware of custom datastores. I will take a look on that.

Thanks

**Comment by michalvasko** [comment]
> I was not aware of custom datastores.

Seems that was not your fault. Except for the headers being installed, they were not mentioned anywhere. Their API should not be part of the doxygen docs and I have added a [separate page](https://netopeer.liberouter.org/doc/sysrepo/devel/html/sr_plugins.html) to introduce them in the Developer Guide.
