### ISSUE TITLE
sr_module_is_internal() is not exported

### ISSUE THREAD

**Issue by pkun** [sysrepo/sysrepo#2915]
Function sr_module_is_internal() is not exported.
Is it an intentional decision?
I need it to filter internal modules while iteration. Now I copy-paste this function to my code but it's not good because set of internal modules can be changed later.

**Comment by michalvasko** [comment]
Which internal modules do you want to filter exactly? *libyang* has a function for that (`ly_ctx_internal_modules_count()`) and I did not think *sysrepo* needs it.

**Comment by pkun** [comment]
I want to filter modules that sysrepo considers as "internal".
sysrepo/src/common.c contains sr_module_is_internal() and sr_ly_module_is_internal() functions.

Modules are:
```
ietf-yang-schema-mount
ietf-yang-library
ietf-netconf
ietf-netconf-with-defaults
ietf-origin
ietf-netconf-notifications
sysrepo
sysrepo-monitoring
sysrepo-plugind
ietf-netconf-acm
ietf-yang-metadata
yang
ietf-inet-types
ietf-yang-types
```

**Comment by michalvasko** [comment]
Fine, the function is public now.

**Comment by pkun** [comment]
Thanks!
