### ISSUE TITLE
Xpath with "../../" for sr_get_items() is not working

### ISSUE THREAD

**Issue by pkun** [sysrepo/sysrepo#2917]
Xpath with double "../" for sr_get_items() is not working.
I use sr_get_items_example utility from sysrepo sourcecode for tests.

Single "../":
```
$ work/sysrepo/build/examples/sr_get_items_example '/acl[name="sss"]/../test/iface/name' candidate
Application will get "/acl[name="sss"]/../test/iface/name" from "candidate" datastore.

/ttt:test/iface[name='eth8']/name = eth8
/ttt:test/iface[name='eth9']/name = eth9
```

But double "../" i.e. "../../":
```
$ work/sysrepo/build/examples/sr_get_items_example '/acl[name="sss"]/iflink/../../test/iface/name' candidate
Application will get "/acl[name="sss"]/iflink/../../test/iface/name" from "candidate" datastore.
```
Empty output.

My yang:
```
module ttt {
  namespace "urn:ttt";
  prefix ttt;

  container test {
    list iface {
      key "name";

      leaf name {
        type string;
      }

    }
  }

  list acl {
    ordered-by user;
    key "name";

    leaf name {
      type string;
    }

    leaf iflink {
      type leafref {
        path "../../test/iface/name";
      }
    }
  }

}

```

**Comment by michalvasko** [comment]
Current `devel` versions of all the projects:
```
> examples/sr_get_items_example '/acl[name="sss"]/../test/iface/name' candidate
Application will get "/acl[name="sss"]/../test/iface/name" from "candidate" datastore.

/ttt:test/iface[name='eth8']/name = eth8
/ttt:test/iface[name='eth9']/name = eth9
> examples/sr_get_items_example '/acl[name="sss"]/iflink/../../test/iface/name' candidate
Application will get "/acl[name="sss"]/iflink/../../test/iface/name" from "candidate" datastore.

/ttt:test/iface[name='eth8']/name = eth8
/ttt:test/iface[name='eth9']/name = eth9
> sysrepocfg -X -d candidate -m ttt
<test xmlns="urn:ttt">
  <iface>
    <name>eth8</name>
  </iface>
  <iface>
    <name>eth9</name>
  </iface>
</test>
<acl xmlns="urn:ttt">
  <name>sss</name>
  <iflink>eth9</iflink>
</acl>
```

**Comment by pkun** [comment]
Now I see the problem. The leaf 'iflink' is not existing in my data. So '../' works only for existing data nodes.

It's problem for me. I'm trying to implement autocompletion for leafref type. So I need Xpath (leafref referenced to) to get possible completions from active datastore. All I can is to get original path defined within yang file using lyxp_get_expr() from opaque structure. There is no way to get absolute path if the relative path is defined within yang.

**Comment by michalvasko** [comment]
Well, `sr_get_items()` operates on data so the nodes you are traversing must exist, naturally. I do not fully understand what you are trying to achieve but if you do not want to depend on data, just use schema nodes, *libyang* has quite good support for evaluating XPath on schema only.

**Comment by pkun** [comment]
Yang:
```
      type leafref {
        path "../../test/iface/name";
      }
```
I want to get data items using leafref's relative path.

Thanks
