### ISSUE TITLE
Wrong subscription is called

### ISSUE THREAD

**Issue by hthiery** [sysrepo/sysrepo#2919]
I have a plugin that has several `sr_module_change_subscribe`:

for example:
```
#define BASE_INTF_YANG_MODEL "ietf-interfaces"                                   

/* Interface callbacks */                                                    
rc = sr_module_change_subscribe(session,                                     
             BASE_INTF_YANG_MODEL, "/" BASE_INTF_YANG_MODEL ":interfaces/*",                  
              interfaces_module_change_cb, *private_ctx, 100,                          
              SR_SUBSCR_ENABLED, &ctx->sr_subscription);
```
and
```
#define BASE_BRIDGE_YANG_MODEL "ieee802-dot1q-bridge"
/* Bridge callbacks */                                                           
rc = sr_module_change_subscribe(session,                                         
             BASE_BRIDGE_YANG_MODEL, "/" BASE_BRIDGE_YANG_MODEL ":bridges/*",         
              bridge_module_change_cb, *private_ctx, 100,                              
              SR_SUBSCR_ENABLED, &ctx->sr_subscription); 
```

When trying to apply a configuration I see that for: `/ietf-interfaces:interfaces/interface[name='Gi 1/3']/ieee802-dot1q-sched:gate-parameters/admin-control-list[index='0']/sgs-params/gate-states-value` the subsciption for the bridge is called.

`cat /tmp/config.json | sysrepocfg  -d running -f json -I -t 30 -v3`

```
{
  "ietf-interfaces:interfaces": {
    "interface": [
      {
        "name": "Gi 1/3",
        "type": "iana-if-type:ethernetCsmacd",
        "ieee802-dot1q-sched:gate-parameters": {
          "gate-enabled": true,
          "admin-control-list-length": 3,
          "admin-control-list": [
            {
              "index": 0,
              "operation-name": "ieee802-dot1q-sched:set-gate-states",
              "sgs-params": {
                "gate-states-value": 3,
                "time-interval-value": 10000
              }
            }
          ]
        }
      }
    ]
  }
}

```

Is there something a do wrong?

**Comment by michalvasko** [comment]
It seems quite a simple use-case so it seems unlikely such a serious problem would suddenly occur. Can you provide more information, are you sure the other callback is called?

**Comment by hthiery** [comment]
Yes I'm sure. Here is an excerpt of the debug outputs of my sysrepod-plugin.

```
[DBG] IETF-INTF: bridge_module_change_cb: xpath: /ietf-interfaces:interfaces/interface[name='Gi 1/3']/ieee802-dot1q-sched:gate-parameters/admin-control-list[index='0']/sgs-params/gate-states-value; prev_val: 255; node_val: 3; operation: 1
[ERR] IETF-INTF: sr_xpath_key_value error for bridge/name
[ERR] IETF-INTF: set_bridge_config_value error (14)
```

**Comment by michalvasko** [comment]
Like I said, seems weird and so I would have to reproduce it to learn anything more.

**Comment by hthiery** [comment]
One question about the xpath: what is the correct xpath value to get all nodes of a module? It seems that the used one:

`/ietf-interfaces:interfaces/*`

is not correct. or?

**Comment by michalvasko** [comment]
Depends on the context, specifically whether `nodes` are being selected or `subtrees`. If you are talking about getting a change iterator in a module change callback, then nodes are being selected so you need to use `/ietf-interfaces:interfaces//*`.

**Comment by hthiery** [comment]
Ok. I used `/ietf-interfaces:interfaces/*` instead of `/ietf-interfaces:interfaces//*`. But after changing that the behavior is the same.

**Comment by michalvasko** [comment]
I did not expect this to be the problem. Like I said, I have nothing to go on without a reproducer.

**Comment by hthiery** [comment]
I reduced the code and included it into a github repo: https://github.com/hthiery/sysrepo-plugin-example

The plugin is started as stand-alone executable. In the examples folder are the configs that I tried to import with sysrepocfg. Is this what you need for reproduction?

**Comment by michalvasko** [comment]
Yes, thanks you, that was enough. Now, there are 2 issues.

When changing configuration, you are using `sysrepocfg` import operation. What it does (with the parameters you have used) is take the config file and **replace** the whole *sysrepo* configuration with it, effectively deleting all data for modules that have no data in the config file. I assume this is not what you want to do and to limit the operation to a single module, you can simply use `-m <module>` parameter. Or, the operation can still be global but use merge (`-E<file>`) instead of import.

Secondly, on `ietf-interfaces-plugin.c:305` you are calling
```C
error = sr_get_changes_iter(session, "//.", &change_iter);
```
which select all the changes of the commit, including ones that are not being subscribed to by the particular callback. This may not be expected but has several advantages as long as the user is aware of it. In any case, you should generally call `sr_get_changes()` with `<xpath>//.` to get only the watched changes.

If you fix either of the problems, the callbacks will succeed.

**Comment by hthiery** [comment]
When importing it was clear to me that it changes everything. It was just one way to reproduce the "error" easily.

With the wrong use of `sr_get_changes_iter` i simply overlooked it. Thanks a lot for the help. I would never have found this so quickly!"
