### ISSUE TITLE
LYB DS error when modifying and reading data simultaneously

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2921]
Hi!

While trying to reproduce #2916  I ran into the following error message, and I was wondering what this means, is this working as intended.

> ./underflow
> [INF] Connection 23 created.
> [INF] Session 34 (user "user", CID 23) created.
> val1: test7626
> val2: test7627
> [INF] Session 35 (user "user", CID 23) created.
> get OK, val=test7626
> [INF] There are no subscribers for changes of the module "ietf- hardware" in running DS.
> get OK, val=test7626
> get OK, val=test7626
> [ERR] LYB DS file: arg1 0x55610e5246e0, arg2 0x55610e524730, arg3 80

The #2916  scenario is similar to this one, and that error might also be related to the LYB DS plugin, that's why I'm interested in the nature of this error.

I attached the source code and config.
I'm using the latest devel versions.
[underflow.tar.gz](https://github.com/sysrepo/sysrepo/files/9624942/underflow.tar.gz)

Thanks!

**Comment by michalvasko** [comment]
No worries, it is just a forgotten debug message :) Removed.

**Comment by awesomenode** [comment]
Thank you!
