### ISSUE TITLE
Updating module in batch

### ISSUE THREAD

**Issue by jeanseb6wind** [sysrepo/sysrepo#2922]
Hello @michalvasko,
Thanks for the new added function `sr_install_modules` and `sr_remove_modules`.
Would it be possible to add `sr_update_modules` too ?

Thanks

**Comment by michalvasko** [comment]
Fine but I did not think one would want to update that many modules in batch.

**Comment by jeanseb6wind** [comment]
Hello @michalvasko, thanks a lot.
Here our usecase: we install all our modules with install_modules, and if we ask a second time to install our module, we'll get an error because module already exists. In that case, we'll call update modules.
