### ISSUE TITLE
netopeer2-server crash SR: mkfifo() failed (Operation not permitted).

### ISSUE THREAD

**Issue by samuele-az** [sysrepo/sysrepo#2924]
I tried to run netopeer2-server on ubuntu 22.04 ARM (Virtual machine in mac M1) but it crash with this log.

> root@ubuntu-linux-22-04-desktop:/etc/sysctl.d# netopeer2-server -d -v 3
[INF]: LY: Searching for "ietf-inet-types" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-inet-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-yang-types" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-inet-types" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-inet-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-yang-types" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-datastores" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/ietf-datastores@2018-02-14.yang" file.
[INF]: LY: Searching for "ietf-yang-library" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/ietf-yang-library@2019-01-04.yang" file.
[INF]: LY: Searching for "ietf-netconf-acm" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/ietf-netconf-acm@2018-02-14.yang" file.
[INF]: LY: Searching for "sysrepo-monitoring" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/sysrepo-monitoring@2022-04-08.yang" file.
[INF]: LY: Implemented module "ietf-datastores@2018-02-14" is not used for import, revision "2018-02-14" is imported instead.
[INF]: LY: Searching for "sysrepo-plugind" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/sysrepo-plugind@2022-03-10.yang" file.
[INF]: LY: Searching for "ietf-netconf" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/ietf-netconf@2013-09-29.yang" file.
[INF]: LY: Searching for "ietf-yang-metadata" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-yang-metadata@2016-08-05" not found, using this as the latest revision.
[INF]: LY: Searching for "ietf-netconf-with-defaults" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/ietf-netconf-with-defaults@2011-06-01.yang" file.
[INF]: LY: Searching for "ietf-netconf-notifications" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/ietf-netconf-notifications@2012-02-06.yang" file.
[INF]: LY: Implemented module "ietf-netconf@2013-09-29" is not used for import, revision "2013-09-29" is imported instead.
[INF]: LY: Searching for "ietf-origin" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/ietf-origin@2018-02-14.yang" file.
[INF]: LY: Searching for "ietf-netconf-monitoring" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/ietf-netconf-monitoring@2010-10-04.yang" file.
[INF]: LY: Searching for "ietf-netconf-nmda" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/ietf-netconf-nmda@2019-01-07.yang" file.
[INF]: LY: Implemented module "ietf-datastores@2018-02-14" is not used for import, revision "2018-02-14" is imported instead.
[INF]: LY: Implemented module "ietf-netconf@2013-09-29" is not used for import, revision "2013-09-29" is imported instead.
[INF]: LY: Searching for "nc-notifications" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/nc-notifications@2008-07-14.yang" file.
[INF]: LY: Searching for "notifications" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/notifications@2008-07-14.yang" file.
[INF]: LY: Searching for "ietf-x509-cert-to-name" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/ietf-x509-cert-to-name@2014-12-10.yang" file.
[INF]: LY: Searching for "ietf-crypto-types" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/ietf-crypto-types@2019-07-02.yang" file.
[INF]: LY: Implemented module "ietf-netconf-acm@2018-02-14" is not used for import, revision "2018-02-14" is imported instead.
[INF]: LY: Searching for "ietf-keystore" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/ietf-keystore@2019-07-02.yang" file.
[INF]: LY: Implemented module "ietf-netconf-acm@2018-02-14" is not used for import, revision "2018-02-14" is imported instead.
[INF]: LY: Searching for "ietf-truststore" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/ietf-truststore@2019-07-02.yang" file.
[INF]: LY: Implemented module "ietf-netconf-acm@2018-02-14" is not used for import, revision "2018-02-14" is imported instead.
[INF]: LY: Implemented module "ietf-crypto-types@2019-07-02" is not used for import, revision "2019-07-02" is imported instead.
[INF]: LY: Searching for "ietf-tcp-common" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/ietf-tcp-common@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-ssh-server" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/ietf-ssh-server@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-ssh-common" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/ietf-ssh-common@2019-07-02.yang" file.
[INF]: LY: Searching for "iana-crypt-hash" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/iana-crypt-hash@2014-08-06.yang" file.
[INF]: LY: Implemented module "ietf-netconf-acm@2018-02-14" is not used for import, revision "2018-02-14" is imported instead.
[INF]: LY: Searching for "ietf-tls-server" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/ietf-tls-server@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-tls-common" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/ietf-tls-common@2019-07-02.yang" file.
[INF]: LY: Implemented module "ietf-keystore@2019-07-02" is not used for import, revision "2019-07-02" is imported instead.
[INF]: LY: Implemented module "ietf-netconf-acm@2018-02-14" is not used for import, revision "2018-02-14" is imported instead.
[INF]: LY: Searching for "ietf-netconf-server" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/ietf-netconf-server@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-tcp-client" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/ietf-tcp-client@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-tcp-server" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/ietf-tcp-server@2019-07-02.yang" file.
[INF]: LY: Implemented module "ietf-tcp-common@2019-07-02" is not used for import, revision "2019-07-02" is imported instead.
[INF]: LY: Searching for "ietf-interfaces" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/ietf-interfaces@2018-02-20.yang" file.
[INF]: LY: Searching for "ietf-ip" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/ietf-ip@2018-02-22.yang" file.
[INF]: LY: Searching for "ietf-network-instance" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/ietf-network-instance@2019-01-21.yang" file.
[INF]: LY: Implemented module "ietf-interfaces@2018-02-20" is not used for import, revision "2018-02-20" is imported instead.
[INF]: LY: Searching for "ietf-subscribed-notifications" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/ietf-subscribed-notifications@2019-09-09.yang" file.
[INF]: LY: Implemented module "ietf-interfaces@2018-02-20" is not used for import, revision "2018-02-20" is imported instead.
[INF]: LY: Implemented module "ietf-netconf-acm@2018-02-14" is not used for import, revision "2018-02-14" is imported instead.
[INF]: LY: Searching for "ietf-restconf" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/ietf-restconf@2017-01-26.yang" file.
[INF]: LY: Searching for "ietf-yang-push" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/ietf-yang-push@2019-09-09.yang" file.
[INF]: LY: Implemented module "ietf-datastores@2018-02-14" is not used for import, revision "2018-02-14" is imported instead.
[INF]: LY: Searching for "ietf-yang-patch" in "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang".
[INF]: LY: Loading schema from "/media/psf/m-plane/develop/az-m-plane-5g/sysrepo/build/repository/yang/ietf-yang-patch@2017-02-22.yang" file.
[INF]: LY: Use of anydata to define configuration data is not recommended. /ietf-subscribed-notifications:filters/stream-filter/{uses='stream-filter-elements'}/filter-spec/stream-subtree-filter/stream-subtree-filter
[INF]: LY: Use of anydata to define configuration data is not recommended. /ietf-yang-push:{augment='/sn:filters'}/ietf-yang-push:selection-filter/{uses='selection-filter-types'}/filter-spec/datastore-subtree-filter/datastore-subtree-filter
[INF]: LY: Use of anydata to define configuration data is not recommended. /ietf-subscribed-notifications:subscriptions/subscription/{uses='subscription-policy'}/{uses='subscription-policy-dynamic'}/{uses='subscription-policy-modifiable'}/target/stream/stream-filter/within-subscription/{uses='stream-filter-elements'}/filter-spec/stream-subtree-filter/stream-subtree-filter
[INF]: LY: Use of anydata to define configuration data is not recommended. /ietf-yang-push:{augment='/sn:subscriptions/sn:subscription/sn:target'}/ietf-yang-push:datastore/{uses='datastore-criteria'}/{uses='selection-filter-objects'}/selection-filter/within-subscription/{uses='selection-filter-types'}/filter-spec/datastore-subtree-filter/datastore-subtree-filter
[INF]: LY: Missing explicit "deprecated" status specified in parent "subnet", inheriting for "prefix-length".
[INF]: LY: Missing explicit "deprecated" status specified in parent "subnet", inheriting for "netmask".
[INF]: LY: The ordered-by statement is ignored in lists representing notification content (/ietf-yang-push:push-change-update/datastore-changes/{uses='ypatch:yang-patch'}/yang-patch/edit).
[INF]: SR: Connection 4 created.
[INF]: SR: Session 4 (user "root", CID 4) created.
[ERR]: SR: mkfifo() failed (Operation not permitted).
[ERR]: NP: Subscribing for "/ietf-netconf:get-config" RPC failed (System function call failed).
[ERR]: NP: Server RPC subscribe failed.
[INF]: NP: Server terminated.
[ERR]: LY: Invalid argument ctx (ly_ctx_get_module_implemented()).
netopeer2-server: /media/psf/m-plane/develop/az-m-plane-5g/sysrepo/src/shm_mod.c:1122: sr_shmmod_recover_cb: Assertion `ly_mod' failed.
Aborted (core dumped)

Can anyone help me understand what happened?

Update:
- netopeer2-server version: 2.1.36
- libsysrepo version: 2.2.84 (7.8.10)
- libyang version: 2.22.4

I tried to change this 3 PATH, but nothing happened.
 -p PATH    Path to pidfile (default path is "/var/run/netopeer2-server.pid").
 -f PATH    Path to netopeer2 server files directory (default path is "/root/.netopeer2-server")
 -U[PATH]   Listen on a local UNIX socket (default path is "/var/run/netopeer2-server.sock").

**Comment by samuele-az** [comment]
Solved, I don't know why but the sysrepo process couldn't write to the sysrepo/repository folder. I changed it and the problem disappeared.

**Comment by michalvasko** [comment]
Yes, that was the cause of the problem but it still should not crash. However, I think this was fixed quite some time ago so you are not using the latest version.

**Comment by samuele-az** [comment]
I don't know, I am using this version of the software.

- netopeer2-server version: 2.1.36
- libsysrepo version: 2.2.84 (7.8.10)
- libyang version: 2.22.4

**Comment by michalvasko** [comment]
There is no *sysrepo* version 2.2.84 so you must mean 2.1.84. However, you are not using that either because from your output there should be assert on [shm_mod.c:1122](https://github.com/sysrepo/sysrepo/blob/master/src/shm_mod.c#L1122) but there is not. So, you are actually using some older version.

**Comment by michalvasko** [comment]
Right, that was a different problem with `ly_mod` not being set. I will try to fix this one as well.
