### ISSUE TITLE
sysrepoctl error: Failed to connect (libyang error)

### ISSUE THREAD

**Issue by adamzyg** [sysrepo/sysrepo#2925]
libyang:  2.0.231
sysrepo: 2.1.84

```
[root@sc source]# sysrepoctl -l -v3
[ERR] Regular expression "\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[\+\-]\d{2}:\d{2})" is not valid ("\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[\+\-]\d{2}:\d{2})": unrecognised compile-time option bit(s)). (/sysrepo:sysrepo-modules/module/replay-support)
[ERR] Internal error (/root/source/libyang-master/src/tree_schema.c:1175).
sysrepoctl error: Failed to connect (libyang error)
```

**Comment by michalvasko** [comment]
In all likelihood, the PCRE2 you are using was not [compiled properly](https://github.com/CESNET/libyang/tree/devel#unix-build-requirements) and the Unicode support is missing.

**Comment by adamzyg** [comment]
> In all likelihood, the PCRE2 you are using was not [compiled properly](https://github.com/CESNET/libyang/tree/devel#unix-build-requirements) and the Unicode support is missing.

OK, I will try, many thanks.
