### ISSUE TITLE
Internal error in subscriber after inserting leaf-list items to the operational store

### ISSUE THREAD

**Issue by gotthardp** [sysrepo/sysrepo#2926]
Hello,
I upgraded to the latest libyang/sysrepo, cleared the repository and shared memory, but still...

I am getting an **Internal error** from here:
https://github.com/sysrepo/sysrepo/blob/69970d91f271cc6ffc595c8d7301d2ba8e0f6409/src/sysrepo.c#L5498

It happens when a subscribed thread B is iterating through changes that a thread A have pushed to the operational repository. The (simplified) code that created the change looks like this:
```c++
auto xpath = "/ietf-interfaces:interfaces/interface[name='wwan0']/kamaji-cellular:bearer/ip4config";

session.setItem(xpath + "/ip", "1.1.1.1");
session.setItem(xpath + "/domain-server[1]", "dns1.example.com");
session.setItem(xpath + "/domain-server[2]", "dns2.example.com");
session.setItem(xpath + "/prefix-length", "24");
session.applyChanges();
```
The error disappears and everything works fine when I remove the two `/domain-server[x]` lines, which is a `leaf-list`.

Does this ring a bell? Could the leaf-list processing be broken, please?

**Comment by michalvasko** [comment]
Please provide `kamaji-cellular.yang` so I can reproduce it. There are similar use-cases in the tests that work fine so I do not know what is the problem in this case.

**Comment by gotthardp** [comment]
Oh, here it is: [kamaji-cellular@2022-04-04.yang.txt](https://github.com/sysrepo/sysrepo/files/9674539/kamaji-cellular%402022-04-04.yang.txt)

**Comment by michalvasko** [comment]
Thanks but I could not reproduce it. What function exactly fails, what parameters does it have, and what is the exact error? Also, the `domain-server` values are invalid, they are defined as `ipv4-address-no-zone`, it cannot be a host name.
