### ISSUE TITLE
LTE TDD frame Deprecated - Fix Required in Sysrepo

### ISSUE THREAD

**Issue by DamodarD** [sysrepo/sysrepo#2927]
With O-RAN M Plane v6, lte-tdd-frame is deprecated. Sysrepo code rejects today if it is not sent by O-DU as part of edit configuration. We need to fix the sysrepo solution to modify the code to return success. 
 Libyang/src/common.h
```C
#define LY_VCODE_NOMAND         LYVE_DATA, "Mandatory node \"%s\" instance does not exist."
```

Libyang/src/validation.c
```C
static LY_ERR
lyd_validate_mandatory(const struct lyd_node *first, const struct lyd_node *parent, const struct lysc_node *snode)
{
    const struct lysc_when *disabled;

    if (snode->nodetype == LYS_CHOICE) {
        /* some data of a choice case exist */
        if (lys_getnext_data(NULL, first, NULL, snode, NULL)) {
            return LY_SUCCESS;
        }
    } else {
        assert(snode->nodetype & (LYS_LEAF | LYS_CONTAINER | LYD_NODE_ANY));

        if (!lyd_find_sibling_val(first, snode, NULL, 0, NULL)) {
            /* data instance found */
            return LY_SUCCESS;
        }
    }

    disabled = NULL;
    if (lysc_has_when(snode)) {
        /* if there are any when conditions, they must be true for a validation error */
        LY_CHECK_RET(lyd_validate_dummy_when(first, parent, snode, &disabled));
    }

    if (!disabled) {
        /* node instance not found */
        if (snode->nodetype == LYS_CHOICE) {
            LOGVAL_APPTAG(snode->module->ctx, "missing-choice", LY_VCODE_NOMAND_CHOIC, snode->name);
        } else {
            LOGVAL(snode->module->ctx, LY_VCODE_NOMAND, snode->name); 
        }
        return LY_EVALID;
    }

    return LY_SUCCESS;
}
```

**Comment by michalvasko** [comment]
It seems reasonable to expect that missing `deprecated`/`obsolete` data nodes do not cause any validation errors and yet it is not directly specified anywhere. At least I could not find anything right now, can you back up your request with some spec? If not, I will ask on the `netmod` mailing list what to do about this situation.

**Comment by DamodarD** [comment]
Sure Michal vasko, I will try to look at some back up specification. Meantime, I think it make sense to email netmod mailing list about this situation.

**Comment by DamodarD** [comment]
Michal, we need to keep this going and potential fix available from sysrepo. Let me know if you are happy to consider this enhancement and potential fix release.

**Comment by michalvasko** [comment]
I have asked yesterday on the mailing list about this and got no responses yet. Those will determine what to do about this situation.

**Comment by DamodarD** [comment]
Many thanks for the follow up Michal. Sure, if you dont mind could you please put me in the loop as well? My email ID is: damodar.d@mavenir.com

**Comment by michalvasko** [comment]
You must subscribe to the *netmod* mailing list to get the emails, or look into the [archive](https://mailarchive.ietf.org/arch/msg/netmod/f7rNs9kGb5Eaijdjac0-VHK6N6k/).

**Comment by DamodarD** [comment]
@michalvasko  Good morning. Please let me know shall we agree to modify the sysrepo code to handle the "deprecated" elements.
