### ISSUE TITLE
Crash while sending notification

### ISSUE THREAD

**Issue by meghna-doshi** [sysrepo/sysrepo#2930]
Hi,
We have upgraded to newer version and we see following assertion in notification path (which was not seen in earlier version):

libyang/src/plugins_types.c:1009: lyplg_type_resolve_leafref: Assertion `!set.used || (set.used == 1)' failed.

#1  0x00007f5afe864a78 in abort () from /usr/lib64/libc.so.6
#2  0x00007f5afe85c1a6 in __assert_fail_base () from /usr/lib64/libc.so.6
#3  0x00007f5afe85c252 in __assert_fail () from /usr/lib64/libc.so.6
#4  0x00007f5b005ce1c2 in lyplg_type_resolve_leafref (lref=0x1107860, node=0x7f5aec00a410, value=0x7f5aec00a448, tree=0x7f5aec001e10, target=0x0, errmsg=0x7f5af5070670)
    at /home/sb1209/Onecell-lfs-sb1209-Aug22-swupgrade-2022/onecell5g/ran_3rdparty/open_source/netconf/libyang/src/plugins_types.c:1009
#5  0x00007f5b005fad81 in lyplg_type_validate_leafref (UNUSED_ctx=0xf43360, type=0x1107860, ctx_node=0x7f5aec00a410, tree=0x7f5aec001e10, storage=0x7f5aec00a448, err=0x7f5af50706e0)
    at /home/sb1209/Onecell-lfs-sb1209-Aug22-swupgrade-2022/onecell5g/ran_3rdparty/open_source/netconf/libyang/src/plugins_types/leafref.c:81
#6  0x00007f5b0051cdac in lyd_value_validate_incomplete (ctx=0xf43360, type=0x1107860, val=0x7f5aec00a448, ctx_node=0x7f5aec00a410, tree=0x7f5aec001e10)
    at /home/sb1209/Onecell-lfs-sb1209-Aug22-swupgrade-2022/onecell5g/ran_3rdparty/open_source/netconf/libyang/src/tree_data_common.c:437
#7  0x00007f5b005f0905 in lyd_validate_unres (tree=0x7f5af50707e8, mod=0x0, data_type=LYD_TYPE_NOTIF_YANG, node_when=0x7f5af5070820, when_xp_opts=1, node_types=0x7f5af5070840, meta_types=0x7f5af5070830, 
    ext_node=0x7f5af5070810, ext_val=0x7f5af5070800, val_opts=0, diff=0x0) at /home/sb1209/Onecell-lfs-sb1209-Aug22-swupgrade-2022/onecell5g/ran_3rdparty/open_source/netconf/libyang/src/validation.c:332
#8  0x00007f5b005f48eb in _lyd_validate_op (op_tree=0x7f5aec013160, op_node=0x7f5aec013160, dep_tree=0x7f5aec001e10, data_type=LYD_TYPE_NOTIF_YANG, int_opts=8, validate_subtree=1 '\001', node_when_p=0x7f5af5070820, 
    node_types_p=0x7f5af5070840, meta_types_p=0x7f5af5070830, ext_node_p=0x7f5af5070810, ext_val_p=0x7f5af5070800, diff=0x0)
    at /home/sb1209/Onecell-lfs-sb1209-Aug22-swupgrade-2022/onecell5g/ran_3rdparty/open_source/netconf/libyang/src/validation.c:1833
#9  0x00007f5b005f4ec3 in lyd_validate_op (op_tree=0x7f5aec013160, dep_tree=0x7f5aec001e10, data_type=LYD_TYPE_NOTIF_YANG, diff=0x0)
    at /home/sb1209/Onecell-lfs-sb1209-Aug22-swupgrade-2022/onecell5g/ran_3rdparty/open_source/netconf/libyang/src/validation.c:1932
#10 0x00007f5b00878efd in sr_modinfo_op_validate (mod_info=0x7f5af5070a30, op=0x7f5aec013160, output=0)
    at /home/sb1209/Onecell-lfs-sb1209-Aug22-swupgrade-2022/onecell5g/ran_3rdparty/open_source/netconf/sysrepo/src/modinfo.c:2644
#11 0x00007f5b0085e704 in sr_notif_send_tree (session=0x112b6b0, notif=0x7f5aec013160, timeout_ms=2000, wait=0)
    at /home/sb1209/Onecell-lfs-sb1209-Aug22-swupgrade-2022/onecell5g/ran_3rdparty/open_source/netconf/sysrepo/src/sysrepo.c:6232
#12 0x0000000000427529 in ConfigMgrSysrepoInterface::event_notif_send_tree (this=0x7f5af990bd80, notif=0x7f5aec013160) at ./src/ConfigMgrSysrepoInterface.cpp:268

sysrepo version : libsysrepo v2.2.3 (SO v7.11.0)
libyang version : 2.0.253

Can you please point out what could be wrong here.
Will try to reproduce and send yang files, but in the meanwhile if anything you can point out here, please let us know.

**Comment by michalvasko** [comment]
Yes, finding leafref targets was optimized and now works differently compared to previous versions. In this case it seems there were several matching targets found, which is not expected. Reading through the YANG specs, this situation may be valid in which case the assert can simply be removed but I would like to reproduce this first to make sure it really is okay.

**Comment by meghna-doshi** [comment]
Hi Michal,
Sure please verify and let us what is the fix (for now i understand that removing the assert is enough).
But just wanted to add, this assumption that a leafref will point to only one unique node is not valid in case of list.
Like the issue where we noticed this crash was:

```
/junila_3gpp-nr-nrm-nrcelldu:nrcell-paraminuse-info/paraminuse-info[cell-id]/X0005B9_nRPCI  which is leafref to:
/_3gpp-common-managed-element:ManagedElement[id]/_3gpp-nr-nrm-gnbdufunction:GNBDUFunction[id]/_3gpp-nr-nrm-nrcelldu:NRCellDU[id]/attributes/nRPCI

```

So if you notice, in case of list, multiple nodes would come in the leafref result set. 
So is this problem only in notification path or in case of edit-config also we will see this?

**Comment by michalvasko** [comment]
Okay, so I have removed the assert. Usually, you would specify some predicates that would limit the valid list instances but it seems it is not mandatory. The problem would appear in any leafref target search but if you update *libyang*, it will no longer.
