### ISSUE TITLE
The count function cannot be used to obtain statistics when filtering

### ISSUE THREAD

**Issue by lilililizheng** [sysrepo/sysrepo#2931]
get-config --source running --filter-xpath count(/interfaces/interface/ipv4/address/ip)
 
When I used this directive on the netopeer2 side, it always returned the following result, and it didn't get the statistics I was hoping for. For example, I want to know how many pieces of data there are in the database:

![image](https://user-images.githubusercontent.com/106649263/194819291-b1a47c68-9749-46b6-abff-03e6a8b66bf0.png)
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="35"><data/></rpc-reply>
DATA
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"/>

**Comment by michalvasko** [comment]
The XPath filter can only return data nodes ([ref](https://datatracker.ietf.org/doc/html/rfc6241#section-8.9)). Also, this should return an error, which I will fix later.

**Comment by michalvasko** [comment]
I do not think any NETCONF operation would get you this information. But you could get all the relevant nodes from the server and then count them on the client.

**Comment by lilililizheng** [comment]
Thank you! Is it unreasonable for sysrepo, as a database, not to be able to return statistics directly? If I had 100,000 pieces of data, and I wanted to show them on the page, it would be very slow to get them all. If I knew what the total was, it would be perfect to get a few dozen pieces of data per page

**Comment by michalvasko** [comment]
*sysrepo* mostly just enables all NETCONF operations to be performed. Your use-case is known and [being addressed](https://www.ietf.org/archive/id/draft-ietf-netconf-list-pagination-00.html). It definitely makes sense to support this once it is standardized.

**Comment by lilililizheng** [comment]
thankes
