### ISSUE TITLE
Invalid Base64 character 0xa.

### ISSUE THREAD

**Issue by lilililizheng** [sysrepo/sysrepo#2934]
I tried to transfer the local file over rpc, but an error was reported.
![image](https://user-images.githubusercontent.com/106649263/195504560-600fd180-09b3-4244-81c7-e91a251ebe3b.png)
![image](https://user-images.githubusercontent.com/106649263/195504616-cc1e472e-ba20-49ab-b01f-41df071bf39d.png)

**Comment by lilililizheng** [comment]
I'm defining rpc to look like this
![image](https://user-images.githubusercontent.com/106649263/195504831-64730e87-d862-4c8a-8ae4-e1169700c366.png)

**Comment by michalvasko** [comment]
You need to show the actual `binary` value, there is something invalid in it.

**Comment by lilililizheng** [comment]
I see why. linux's base64 encoding command adds a newline to the file
