### ISSUE TITLE
Building without "stdatomic" / "libatomic"

### ISSUE THREAD

**Issue by sjd-xlnx** [sysrepo/sysrepo#2938]
Hi,

I'm updating to latest versions of sysrepo, netopeer2, etc. I've hit another issue ... which I think is the last one (fingers crossed).

So, I managed to build sysrepo ok, but when I try to "make install" netopeer2 it complains about sysrepoctl...

```sysrepoctl: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory```

And going back to sysrepo, I can see that despite being build successfully, it couldn't locate the libatomic library.

```
$ ldd libsysrepo.so.7.8.10
        linux-vdso.so.1 =>  (0x00007ffc57922000)
        libatomic.so.1 => not found
        librt.so.1 => /lib64/librt.so.1 (0x00007f574ff41000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f574fd3d000)
        libyang.so.2 => /lib64/libyang.so.2 (0x00007f57501a4000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f574fb21000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f574f754000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5750149000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f574f452000)
        libpcre2-8.so.0 => /lib/libpcre2-8.so.0 (0x00007f574f1f9000)
```

Unfortunately, my build server doesn't appear to have libatomic or stdatomic.h, and I don't think I can add it easily.

I noticed in the code (build/compat.h) there is some conditional compilation around the HAVE_STDATOMIC #define. If it is not defined then the "ATOMIC" macros use __sync_fetch_and_add() rather than atomic_fetch_add_explicit() for example. I guess these are GNU proprietary extensions rather than the standard ones.

I configured cmake with the following additions...

```cmake -DHAVE_STDATOMIC=0 -DLIBATOMIC=0```

This now builds, and appears to work ok. No "missing" libraries reported by ldd, and sysrepoctl runs, etc.

```
$ ldd libsysrepo.so.7.8.10
        linux-vdso.so.1 =>  (0x00007fff3716b000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f2dd2de4000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f2dd2be0000)
        libyang.so.2 => /lib64/libyang.so.2 (0x00007f2dd3049000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f2dd29c4000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f2dd25f7000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f2dd2fec000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f2dd22f5000)
        libpcre2-8.so.0 => /lib/libpcre2-8.so.0 (0x00007f2dd209c000)
```

So, I think with the above cmake arguments I'm good to go. However, a few questions...

1. I guess using standard atomic library is preferable, but is _not_ using it going to be a problem? (e.g. known bugs with the GNU proprietary).
2. Until recently I was using older version of sysrepo (because the Python bindings where limited to specific version), and with this version ([Version 1.4.140](https://github.com/sysrepo/sysrepo/releases/tag/v1.4.140)) I never had the problem with libatomic / stdatomic.h. Actually, that's more of a statement than a question. My point is that I assume that the reliance on libatomic came in somewhere after 1.4.140. ?
3. Not sure if you want to add some kind of test into sysrepo, as I said it apparently builds without any errors or warnings when the libatomic / stdatomic did not exist.

PS: This issue is related to https://github.com/sysrepo/sysrepo/issues/2769, but I posted here since that one is closed already.

Thanks for your time.

**Comment by michalvasko** [comment]
1. No idea, but I would think the extensions work just fine, they were just supported even before there were any C11 atomics specified.
2. Possible, the atomics were used only later but they are required (and were required even before).
3. CMake looks for stdatomic and based on that decides whether to use the library or not. Your problem should be caused by the fact that it is present on your local machine but not on the host machine. If you have a solution for this, let us know.

**Comment by sjd-xlnx** [comment]
Thanks for quick answer. Although, I am rather confused where cmake thinks the libatomic is, as it is not on our system (local or host).

I'm not cmake expert but I guess the following is supposed to detect it...

```check_library_exists(atomic __atomic_fetch_add_4 "" LIBATOMIC)```

So, assuming the above works, cmake somehow thinks it exists, even though the package is not installed.

I'll investigate further, but in any case, I have workaround for now, and I'll see if I can get libatomic added anyway.

Thanks for your help.
