### ISSUE TITLE
Confirmation on Sysrepo's sequential behavior

### ISSUE THREAD

**Issue by PravalliSure** [sysrepo/sysrepo#2939]
Hi Mikhal, I need confirmation on the observations I made on sysrepo's sequential commit behavior.

Sysrepo is not creating any threads or is managing event listening for us. We are retrieving file descriptors and we are handling event listening/callback invocation in user space.

**Scenario:**
Yang module A and yang module Bs changes are committed in the same edit-config RPC

**Expected:**
As the subscriber for A and B are in different threads, I expect callbacks are called in parallel

**Observed:**
Sysrepo calls back A first with SR_EV_CHANGE and only once SR_ERR_OK is responded, B's callback is called. Once both are returned with SR_ERR_OK, SR_EV_DONE is called for A first and then to B.

**Comment by michalvasko** [comment]
Yes, this is how it works currently but I suppose it could be changed the way you described. Except such changes tend to cause lots of other problems and the callbacks themselves would need to be aware of this, too.

**Comment by michalvasko** [comment]
> This means that, in a hypothetical case, A has some leaves B is referring to, and if client wants to edit leafref leaves in A and leaves referring to it in B, then first A should be committed and then only B should be committed?

No, you can perform all the changes together, the final configuration is being validated, it is just that the callbacks for different modules are called one after the other, not concurrently.

> Are there any plans to make sysrepo callback calling asynchronous?

I will note it as an enhancement and will try to implement it later when I have some spare time.

> And also why do callbacks need to be aware of this?

Depending on what the callback do, they may cause some data races. It should not be a problem in *sysrepo* itself.

**Comment by PravalliSure** [comment]
What I see currently is, if I commit more than one yang modules at a time, sysrepo calls back in alphabetical order of yang modules. Meaning, if I commit changes for o-ran-ecpri-delay and o-ran-processing-element, I receive callback for o-ran-ecpri-delay and then for the other.

> > This means that, in a hypothetical case, A has some leaves B is referring to, and if client wants to edit leafref leaves in A and leaves referring to it in B, then first A should be committed and then only B should be committed?
> 
> No, you can perform all the changes together, the final configuration is being validated, it is just that the callbacks for different modules are called one after the other, not concurrently.
I see an issue with this. Lets take the same example of editing o-ran-ecpri-delay and o-ran-processing-element in the same commit. 
**Snippet of o-ran-ecpri-delay where it is referring to processing element's leaf**
        +--rw session-parameters* [session-id]
           +--rw session-id                 uint32
           +--rw processing-element-name?   -> /element:processing-elements/ru-elements/name

If my commit has added a new processing element name and it also has changes to ecpri using that new name in processing element

**Requirement:**
Ideal scenario is, I receive callback on both those yang modules and I validate it as a bunch. But based on current behavior one callback is called at a time. First processing element changes are received and once validated, I receive ecpri changes and I validate them together.

**Behavior seen**
First ecpri changes are sent as it is first in alphabetical order, I see that it is referring to non-existent processing element name and I reject it. Then I receive processing elements change, even though I send SR_ERR_OK, overall configuration fails for the commit.

**Comment by michalvasko** [comment]
> I see that it is referring to non-existent processing element name and I reject it.

Why would you do this? YANG validation is performed automatically by *sysrepo*, why do you want to duplicate it? Also, when getting data in the callbacks, you should always get them with the current changes applied so you should see the target element as well. What *sysrepo* version are you using?

**Comment by PravalliSure** [comment]
@michalvasko Great to see these changes on devel. When can we expect these changes merged to master? A rough estimation should work.
