### ISSUE TITLE
Controls the sequence of plug-in execution

### ISSUE THREAD

**Issue by lilililizheng** [sysrepo/sysrepo#2942]
![image](https://user-images.githubusercontent.com/106649263/197457553-f896fb66-1ae7-4d1a-b9be-4f69fb5ef099.png)
How do you control the order in which plug-ins are executed? When I restart the device, if the startup ds has 10000 pieces of data, it may take 2 minutes to deliver the 10000 pieces of data. But I need access to data that is readily available on the home page.

sysrepocfg -X -d operational -f json -m zdxlz-device-state

I find that I can only use this command to obtain the status data of the home page after the startup ds data is executed

**Comment by michalvasko** [comment]
To set the order in which plugins are initialized set the correct configuration in [sysrepo-plugind](https://github.com/sysrepo/sysrepo/blob/master/modules/sysrepo-plugind.yang) YANG.

**Comment by lilililizheng** [comment]
thanks
