### ISSUE TITLE
Docker config file/deploy folder not present in sysrepo repository

### ISSUE THREAD

**Issue by ankit7gup** [sysrepo/sysrepo#2946]
Hi Michal,

I have just noticed; the Docker config file/deploy folder is not present in sysrepo repository. Can you please let me know the reason behind it, is there any other path/location where the file is present. 

Thanks!

Regards,
Ankit

**Comment by michalvasko** [comment]
The scripts were not maintained so I have decided to remove them from the repository. There are some online images but they are not being maintained either. I have quite bad experiences with docker so I am sorry, but it is unlikely there will be an official script or image available.
