### ISSUE TITLE
"Timeout for receiving a reply expired" when call a user-rpc.

### ISSUE THREAD

**Issue by sally8989** [sysrepo/sysrepo#2947]
Hi,
I defined a user-rpc in my "aircon.c", which I tried to do a similar sample like "oven" in sysrepo. The issue is that I can not make a function output sucessfully, and my netopeer2-cli show something like that:

> user-rpc --content /root/control_switch.xml
cli_send_recv: Timeout for receiving a reply expired.

I want to output something successful, and it's my first time to know sysrepo's things. I attach some information, and if something lost that I can upload again.

_Attach  some codes & logs :_

**- rpc code (aircon.c) :**
( The main idea is to switch the air-conditioner, and if finish switching, there will be a output.  )
```C
static int
aircon_control_switch_cb(sr_session_ctx_t* session, uint32_t sub_id, const char* path, const sr_val_t* input,const size_t input_cnt, sr_event_t event, uint32_t request_id, sr_val_t** output, size_t* output_cnt,void* private_data)
{
	(void)session;
	(void)sub_id;
	(void)path;
	(void)input_cnt;
	(void)event;
	(void)request_id;
	(void)private_data;
	
	if (strcmp(input[0].data.enum_val, "switch") == 0) { 

		if (turned_on){
			turned_on = 0;
			SRP_LOG_DBG("AIRCON: [OFF] You turn off the air-conditioner.");
		}
		else {
			turned_on = 1;
			SRP_LOG_DBG("AIRCON: [ON] You turn on the air-conditioner.");
		}

		*output = malloc(sizeof **output);
		*output_cnt = 1;

		(*output)[0].xpath = strdup("/aircon:control-switch/back");
		(*output)[0].type = SR_INT64_T;
		(*output)[0].dflt = 0;
		(*output)[0].data.int64_val = -123456;

		SRP_LOG_DBG("AIRCON: why??.");

		return SR_ERR_OK;
	}

	else {
		SRP_LOG_ERR("AIRCON: Try again...");
		return SR_ERR_OPERATION_FAILED;
	}
}
```
- **yang module (aircon.yang) :**
( Here is only a point in my leaf )
```yang
rpc control-switch{
		description "Operation to control the air-conditioner's switch.";

		input{
			leaf controller{
				description "Parameter determining which state of air-conditioner will be changed.";
				type enumeration{

				enum switch{
					description "Turn on or off the air-conditioner.(Determined by turned-on state then)";
				}
			}
		}
	}
		output{
			leaf back{
				description "Setting the air-conditioner successfully";
				type int64;
			}
		}
	}
```
- **rpc-triggered content (control_switch.xml) :** 

```xml
<control-switch xmlns="urn:sysrepo:aircon">
    <controller>switch</controller>
</control-switch>
```

- **sysrepo-plugin daemon log :**
( The "why" log just let me know did it run to output place )
```
[INF]: Processing "/aircon:control-switch" "rpc" event with ID 1 priority 0 (rem
[DBG]: plugin: AIRCON: [ON] You turn on the air-conditioner.
[DBG]: plugin: AIRCON: why??.
Segmentation fault (core dumped)
```
Above contents may be some unclear statement, sorry that English is not my native language, and I am able to reply comment below.
Feel free to give any ideas, thanks.

Best regards,
Sally

**Comment by michalvasko** [comment]
The only problem I could find is that you are using `malloc` but not initializing all the members so once *sysrepo* tries to access `origin` in the `output`, it may crash. Just set it to NULL and it should work.

**Comment by sally8989** [comment]
I got the same problem just now, did I write it false? 
partial rpc-code below : 

        *output = malloc(sizeof **output);
	*output = NULL;
	*output_cnt = 1;

**Comment by michalvasko** [comment]
No, that is certainly not correct. I said set **origin** (meaning `(*output)[0].origin = NULL;`) to NULL, not the whole `output`.

**Comment by sally8989** [comment]
I am not familiar with malloc's usage, so I tried :

*output = NULL;
*output = malloc(sizeof **output);
*output_cnt = 1;

**and also**

*output = malloc(NULL);
*output_cnt = 1;

there are same isuues with timeout problem :/

**Comment by sally8989** [comment]
I am sorry that not familiar with malloc's usage.
Then I change my rpc-dode to that : 

*output = malloc(sizeof * *output);
*output_cnt = 1;
(*output)[0].origin = NULL;
(*output)[0].xpath = strdup("/aircon:control-switch/back");
(*output)[0].type = SR_INT64_T;
(*output)[0].dflt = 0;
(*output)[0].data.int64_val = -123456;

But there still Timeout problem  : /

**Comment by michalvasko** [comment]
Then I am not sure what the problem may be.

> I am sorry that not familiar with malloc's usage.

In that case please first get familiar with it and with programming in C in general. Writing *sysrepo* plugins is not a good way of learning C.

**Comment by sally8989** [comment]
Okay, I'll practice using malloc, and keep on checking bugs. 
Thanks for your help, really aprreciate it.

**Comment by sally8989** [comment]
Hi, I find my problem, that is header file, which I include soo many header file, but did not **define _GNU_SOURCE.**
