### ISSUE TITLE
sysrepocfg should allow to display state data

### ISSUE THREAD

**Issue by rastislavszabo** [sysrepo/sysrepo#295]
sysrepocfg should support some way of displaying state data.

**Comment by fanchanghu** [comment]
Hi,
I want to known why we need this feature in sysrepocfg, it seems we can do this by using 'get' command in netconf client, such as netopeer.

**Comment by rastislavszabo** [comment]
Yes, it is true. Similarly as you can do almost everything what `sysrepocfg` does currently with netopeer (e.g. get/set config data, import / export data etc.). `sysrepocfg` is a tool for accessing the datastore directly, without the need of having netopeer running or even installed.
