### ISSUE TITLE
How to push entire json data at once in oper_get_subscription?

### ISSUE THREAD

**Issue by amitnagraj** [sysrepo/sysrepo#2955]
Hi Michal,

I m using sysrepo 2.0.47

By using lyd_new_path() we can push the data one by one using the xpath. Is there a way to push data for all the subscribed leaf nodes to operation datastore using json formatted string/ json file.

Thanks,

**Comment by michalvasko** [comment]
You can use `lyd_parse_mem()` to parse the file into a data tree. Then just connect it to the `parent` (or simply assign if in top-level) and it should work.
