### ISSUE TITLE
Internal error when calling sr_get_change_tree_next

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#2956]
Hi,

I met an internal error when calling `sr_get_change_tree_next` for operational data change callback.
I attached an application to reproduce it:
[reprod.zip](https://github.com/sysrepo/sysrepo/files/10085693/reprod.zip)

```
$ ./reprod
[ERR] Internal error (/opt/dev/sysrepo/src/sysrepo.c:5477). 
sr_get_change_tree_next error: Internal error 
[ERR] Internal error (/opt/dev/sysrepo/src/sysrepo.c:5477). 
sr_get_change_tree_next error: Internal error
```

sysrepo version: 2.2.15
libyang version: 2.1.11

Thanks!

**Comment by michalvasko** [comment]
Fixed now in `devel`.

**Comment by awesomenode** [comment]
Thank you!
