### ISSUE TITLE
Query regarding order of sysrepo callback API

### ISSUE THREAD

**Issue by balaji07s** [sysrepo/sysrepo#2959]
Hi,

We are registering five different XPath using the API sr_module_change_subscribe by passing the following arguments sr_session_ctx_t , module_name, xpath, callback, NULL (private_data), 0 (priority), SR_SUBSCR_ENABLED (sr_subscr_options_t opts), and sr_subscription_ctx_t.

When we are pushing a single script containing the five different XPath configurations then the order of the callbacks is not in the order that we've subscribed.

```
**Example:

Xpaths:**
/bbf-l2-dhcpv4-relay:l2-dhcpv4-relay-profiles/l2-dhcpv4-relay-profile
/bbf-pppoe-intermediate-agent:pppoe-profiles/pppoe-profile
/bbf-subscriber-profiles:subscriber-profiles/subscriber-profile
/bbf-qos-policing:policing-profiles/policing-profile
/bbf-qos-classifiers:classifiers/classifier-entry

**Module names and subscribing order:**
1. bbf-l2-dhcpv4-relay
2. bbf-pppoe-intermediate-agent
3. bbf-subscriber-profiles
4. bbf-qos-policing
5. bbf-qos-classifiers
```

Could you please tell us on what basis the above-mentioned callbacks get invoked when we push a single XML script containing all the above-mentioned XPath configurations?

sysrepo version: v2.2.12

**Comment by michalvasko** [comment]
Order of callbacks for different modules is determined by the order of the data nodes. *libyang* orders the data based on the module name, alphabetically. Nevertheless, an improvement is planned when all the modules will be notified simultaneously but not sure when exactly will that be implemented.

**Comment by balaji07s** [comment]
Thanks for the quick response.
I have a question here. If I want to change the callback order of the above-mentioned modules, what do I have to do, and is there a way to do that? I have tried passing a priority of 4 for one of the modules mentioned above, but it is not working. Please share if there are any other ways to manipulate the callback execution order instead of using the alphabetical order.

**Comment by michalvasko** [comment]
> If I want to change the callback order of the above-mentioned modules, what do I have to do, and is there a way to do that?

There is no way to change it, which is why I have not mentioned it. In general, the YANG modules should not depend on each other.

**Comment by balaji07s** [comment]
Thanks, Michal Vasko for your quick responses.
