### ISSUE TITLE
retrying `sr_unsubscribe_sub` in case of an error

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#2963]
The docs for `sr_unsubscribe_sub()` [say](https://netopeer.liberouter.org/doc/sysrepo/devel/html/group__subs__api.html#ga369f62715baed57ad5aabbd92e315347):
> **Note**
>    On error the function should be retried and must eventually succeed.

Can you please extend the docs with information about which error codes should cause a retry, and which error codes are considered a hard failure where retrying won't help? I would like to follow the docs, but also do something smarter than an endless loop in case of, say, an internal error or lock corruption that just happens to be detected from this context. Thanks!

**Comment by michalvasko** [comment]
Okay, I seem to have find only a single error like that.

**Comment by jktjkt** [comment]
thanks
