### ISSUE TITLE
Path problem of get operation

### ISSUE THREAD

**Issue by hi-Mr-ye** [sysrepo/sysrepo#2965]
Hi
I did two get operations,but the printed information on the left is the same
![image](https://user-images.githubusercontent.com/90752673/207538822-306e0d98-a166-48d0-b3bf-7682564d3f64.png)

 printf function is added to the callback function:
![image](https://user-images.githubusercontent.com/90752673/207538916-e1820eda-c284-41fe-bbec-21655f26a469.png)
![image](https://user-images.githubusercontent.com/90752673/207539001-4d865483-8139-43fb-a778-acb38e8f07f3.png)
but why?
How do I get the value of the path is /och-info:ochs/och[name='port-1']?

**Comment by michalvasko** [comment]
What *netopeer2-server* version are you using?

**Comment by hi-Mr-ye** [comment]
![image](https://user-images.githubusercontent.com/90752673/207555269-4f2a56f7-0e99-4731-bf76-f50ee783f50b.png)
the  netopeer2-server version is 2.1.24

**Comment by michalvasko** [comment]
The way how `get` retrieves data had been changed in version 2.1.27, please update it to the current release.

**Comment by hi-Mr-ye** [comment]
okay, thanks!
