### ISSUE TITLE
Notification received for both sr_oper_get_items_subscribe and sr_rpc_subscribe registered call back functions

### ISSUE THREAD

**Issue by balaji07s** [sysrepo/sysrepo#2966]
Sysrepo version: 2.2.12

I have registered for a call-back notification for the following two Xpaths with the following subscription APIs.

**Xpaths:**
> 1. "/ietf-hardware:hardware/component/bbf-hardware:reset"
> 2. "/ietf-hardware:hardware/component"

**Subscription APIs:**
> 1. sr_rpc_subscribe(srs, "/ietf-hardware:hardware/component/bbf-hardware:reset",
>                 hardware_component_reset_cb, NULL, 0, SR_SUBSCR_CTX_REUSE, &sr_ctx);
> 
> 2. sr_oper_get_items_subscribe(srs, "ietf-hardware", "/ietf-hardware:hardware/component",
>             _hardware_state_get_cb, NULL, SR_SUBSCR_OPER_MERGE, &sr_ctx_state)

Then if I push the following action/RPC XML script from netconf client then both the registered callback functions are getting invoked.

**XML script:**
```
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="3013">
<action xmlns:bbf-hw="urn:bbf:yang:bbf-hardware" xmlns="urn:ietf:params:xml:ns:yang:1">
     <hardware xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware">
      <component>
        <name>ontComponent_1_1</name>
      <bbf-hw:reset>
        <bbf-hw:reset-type>bbf-hw:hardware-reset</bbf-hw:reset-type>
      </bbf-hw:reset>
      </component>
    </hardware>
</action>
</rpc>
```
I have used the below-mentioned yang files.

> 1. bbf-hardware.yang
> 2. ietf-hardware.yang

**Comment by michalvasko** [comment]
`_hardware_state_get_cb` is being called because the data it provides are needed for validating the notification `reset` ([ref](https://datatracker.ietf.org/doc/html/rfc8342#section-6.2)).

**Comment by michalvasko** [comment]
Not really. If you want to avoid returning unnecessary data, split the callback into several and in this case only the ones for `component` or `name` should be called.
