### ISSUE TITLE
Callback for two operation getting invoked when updated a value for choice data structure in yang

### ISSUE THREAD

**Issue by amitnagraj** [sysrepo/sysrepo#2967]
Hi Michal,

I m using sysrepo v2.0.47

Yang sinppet:
```
grouping ethernet-interface-storm-control {
    description
      "Configuration items for ethernet-interface storm control setting.";

    container storm-control {
      description
        "Configure storm control settings.";

      container config {
        description
          "Enclosing data for storm Control.";

        choice  storm-ctl {
          leaf disabled {
            type boolean;
            description
              "Disables the storm control.";
          }
          leaf rate {
            type uint8 {
              range 1..90;
            }
            default 50;
            description
              "Sets the storm-control rate in switch-asic for ingress
              broadcast/unknown-unicast packets. Value 0 disables the
              strom-control. The rate is specified as a value between
              1 to 90 percent of the port speed.";
          }
          leaf speed {
            type uint32 {
              range 200..1000000;
            }
            description
              "Limits traffic as kilo bps, this provide a more precise limitation
              with smaller granularity.";
          }
        }
      }
    }
  }
```

When trying to update a value (for example from "rate" to "speed") for the above yang data structure, callback for two operations that is, "SR_OP_CREATED" for the item that is being set and "SR_OP_DELETED" for the item which was stored previously is getting invoked.

Is this the expected behavior? If yes, is there a way to stimulate this to avoid this "SR_OP_DELETED" operation that is being invoked during this callback.

Thanks,

**Comment by michalvasko** [comment]
> Is this the expected behavior? If yes, is there a way to stimulate this to avoid...

Yes, it is and not sure I can help with any changes to this behavior, the node is really being (auto)deleted so a change is reported. You should be able to ignore the other change when you, for example, detect a creation of a node from another case.

**Comment by amitnagraj** [comment]
Thanks for the info.
