### ISSUE TITLE
When statement seems to be ineffective 

### ISSUE THREAD

**Issue by PravalliSure** [sysrepo/sysrepo#2968]
Hi,

I have a subscription for operational pull data in ietf-hardware/component/sensor-data container.
This sensor-data has a condition 
      when 'derived-from-or-self(../class, "ianahw:sensor")' {
        description
          "Sensor data nodes present for any component of type
           'sensor'";
      }

And I pushed data for 3 components and I have entered class as ianahw:sensor for one of them and chose different classes for the other two.

And my subscription xpath is "/ietf-hardware:hardware/component/sensor-data"

When I call a get on hardware yang module, I am getting three callbacks even though only one of them belongs to ianahw:sensor class.

**Question:**
Based on when condition description, I should not get callback for all the three right? 
Is the xpath used for subscription need to mention this specialization?

**Comment by michalvasko** [comment]
> Based on when condition description, I should not get callback for all the three right?

Ideally, yes, but the `operational` datastore does not have to be [valid](https://datatracker.ietf.org/doc/html/rfc8342#section-5.3.1) and so the data are not being validated. That is why the `when` condition is not evaluated.
