### ISSUE TITLE
How to delete  the read node with pattern checking in operational datastore?

### ISSUE THREAD

**Issue by guangjung** [sysrepo/sysrepo#2969]
I tried to delete  the read node with pattern checking in operational datastore , but failed.  How to delete the node correctly?
1.  manufacture-date is an example node , 
1) yang tree is as following:
```
module: org-openroadm-device
  +--rw org-openroadm-device
     +--rw circuit-packs* [circuit-pack-name]
     |  +--rw circuit-pack-type            string
     |  +--rw circuit-pack-product-code?   string
     |  +--rw circuit-pack-name            string
     |  +--rw lifecycle-state?             org-openroadm-common-state-types:lifecycle-state
     |  +--rw administrative-state         org-openroadm-equipment-states-types:admin-states
     |  +--ro vendor                       string
     |  +--ro model                        string
     |  +--ro serial-id                    string
     |  +--ro type?                        string
     |  +--ro product-code?                string
     |  +--ro manufacture-date?            yang:date-and-time
     |  +--ro clei?                        string
     |  +--ro hardware-version?            string
```
2)  yang node define
```yang
    leaf manufacture-date {
      type yang:date-and-time;
      config false;
      description
        "Manufacture date of physical resource";
    }

  typedef date-and-time {
    type string {
      pattern '\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?'
            + '(Z|[\+\-]\d{2}:\d{2})';
    }
```
2.  I found  that manufacture-date node was existed in operational datastore.
   /usr/local/bin/sysrepocfg --export --datastore operational --module openconfig-platform , the output content is the following
```xml
    <circuit-packs>
    <circuit-pack-name>cp-scc</circuit-pack-name>
    <vendor>DEF_vendor</vendor>
    <model>R-control-board</model>
    <serial-id>ZH17600006</serial-id>
    <product-code>RADMPAM4SAOPL01</product-code>
    <manufacture-date>2020-08-01T14:41:00+00:00</manufacture-date>
    <clei>N/A</clei>
    <hardware-version>1.01</hardware-version>
    <operational-state>inService</operational-state>
```
3.  when I called sr_oper_delete_item_str for deleting  manufacture-date node ,  the return value is failed.    I used sysrepo v2.1.84.
```C
  rc = sr_oper_delete_item_str(pstSess, acXpath, NULL, SR_EDIT_DEFAULT); 
     pstSess: operational session
     acXpath:  /org-openroadm-device:org-openroadm-device/circuit-packs[circuit-pack-name='cp-scc']/manufacture-date
```
error log info:
```
libyang[0]: Unsatisfied pattern - "" does not conform to "\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[\+\-]\d{2}:\d{2})". (path: Schema location "/org-openroadm-device:org-openroadm-device/circuit-packs/manufacture-date".)
```
rc : Invalid argument

  NOTE: I  tried to modifying  the  manufacture-date node  in operational datastore with valid value, it was modified successful.

**Comment by michalvasko** [comment]
Yes, in *sysrepo* v 2.1.84 you must specify the exact value to delete as the 3rd arguments of `sr_oper_delete_item_str()`, you cannot just use `NULL`. In *sysrepo* v2.x.x you can use `sr_delete_item()` that does not require any value.

**Comment by guangjung** [comment]
Hi michal,
      Thank you for your replay. I still don't understand.
Question1:
the node product-code/hardware-version  could be deleted by the same sr_oper_delete_item_str (the 3rd argument is NULL), why?  the yang define are as follows (the manufacture-date has pattern checking，  but product-code/hardware-version do not.)
    leaf product-code {
      type string;
      config false;
      description
        "Product Code for this physical resource";
    }
    leaf hardware-version {
      type string;
      config false;
      description
        "The version of the hardware.";
    }
Question2:
  For _In sysrepo v2.x.x you can use sr_delete_item() that does not require any value._   ，Does v2.x.x  not include v2.1.84? 
   I also noted that sr_oper_delete_item_str  was deprecated in v2.2.12.

**Comment by michalvasko** [comment]
> the node product-code/hardware-version could be deleted by the same sr_oper_delete_item_str (the 3rd argument is NULL), why?

`NULL` got "normalized" into `""`, which is a valid value for these nodes, it is not for `manufacture-date`.

> Does v2.x.x not include v2.1.84?

Sorry, I meant v2.2.x.
