### ISSUE TITLE
Bootstrap configuration generator

### ISSUE THREAD

**Issue by rastislavszabo** [sysrepo/sysrepo#297]
`sysrepocfg` could allow to generate some meaningless bootstrap configuration for the specified YANG model, so that the user who is adding some new configuration into an empty datastore does not need to write so much of XML/JSON on their own. The generated configuration could be placed inside of a comment in the editor opened by sysrepocfg. Generated leaves can contain random or zeroed values, but the values should be still valid according to the YANG model.

**Comment by michalvasko** [comment]
Not a feature for *sysrepo*.
