### ISSUE TITLE
Opening "/etc/sysrepo/sr_evpipe" for writing failed

### ISSUE THREAD

**Issue by nhathaway** [sysrepo/sysrepo#2972]
I appreciate that this error has occurred in the past, but this is probably a different use case.

Software version: the collection released in November 2022

$ sysrepocfg -V
sysrepocfg - sysrepo configuration manipulation tool, compiled with libsysrepo v2.2.12 (SO v7.11.8)

C Code:

~~~
    rc = sr_rpc_subscribe(session, "/ietf-keystore:keystore/asymmetric-keys/asymmetric-key/generate-certificate-signing-request",
                          gen_csr_cb, data, 0, SR_SUBSCR_NO_THREAD, &data->subscription);
~~~

Test code (bash script fragment):

~~~
cat >$TEMPFILE <<EOF
<keystore xmlns="urn:ietf:params:xml:ns:yang:ietf-keystore">
  <asymmetric-keys>
    <asymmetric-key>
      <name>genkey</name>
      <generate-certificate-signing-request>
        <subject>SGVsbG8gd29ybGQ=</subject>
        <attributes>R29vZGJ5ZSB3b3JsZA==</attributes>
      </generate-certificate-signing-request>
    </asymmetric-key>
  </asymmetric-keys>
</keystore>
EOF
sysrepocfg --rpc=$TEMPFILE -f xml -v3
~~~

Console output:

~~~
[INF] Published event "rpc" "/ietf-keystore:keystore/asymmetric-keys/asymmetric-key/generate-certificate-signing-request" with ID 1 priority 0 for 1 subscribers.
[ERR] Opening "/etc/sysrepo/sr_evpipe50" for writing failed (No such device or address).
sysrepocfg error: Sending RPC/action failed (System function call failed)
~~~

I can confirm that the pipe file does indeed exist when the rpc (actually 'action') is invoked.

Under previous versions (the last in the 2.0 series) this bug did not occur, so it has been more recently introduced.

**Comment by michalvasko** [comment]
I am fairly sure there is no problem in *sysrepo* causing this, some leftover information from the previous version is probably the issue. Please try to stop all *sysrepo* processes, execute `make sr_clean` (will remove all the *sysrepo* repository data), and try again. Let me know if the problem persists.

**Comment by nhathaway** [comment]
I've done as you described, and the problem still persists.

**Comment by michalvasko** [comment]
Then I would blame the system permissions although I am not sure why the error is not `EPERM` (but as you say, the pipe exists so what else could it be). Try running the program that sends the RPC as `root`.

In general, permission problems are expected when using `/etc/sysrepo` as the repository directory. You can try configuring a `SYSREPO_GROUP` and then adding all the users running *sysrepo* processes into it. In that case you should never have problems with permissions.

**Comment by nhathaway** [comment]
Running as root makes no difference.

~~~
[INF] Connection 85 created.
[INF] Session 64 (user "root", CID 85) created.
[INF] Published event "rpc" "/ietf-keystore:keystore/asymmetric-keys/asymmetric-key/generate-certificate-signing-request" with ID 1 priority 0 for 1 subscribers.
[ERR] Opening "/etc/sysrepo/sr_evpipe5" for writing failed (No such device or address).
sysrepocfg error: Sending RPC/action failed (System function call failed)
~~~

**Comment by michalvasko** [comment]
I see, then I will probably need to reproduce it to help you. As expected, when I tried to reproduce it with the examples, `oper_data_push_example` to set the `asymmetric-key` instance, `rpc_subscribe_example` for RPC subscription, and `rpc_send_example` for sending the RPC, it worked as expected.

So, please provide the output of `ls -ld /etc/sysrepo` and `ls -l /etc/sysrepo`. Then, try to use as much of the examples as you can and provide the steps you did when the problem manifested.

**Comment by nhathaway** [comment]
~~~
$ ls -ld /etc/sysrepo
drwxrwxrwx 5 root root 4096 Dec 22 14:19 /etc/sysrepo
~~~

~~~
ls -l /etc/sysrepo
drwxrwxrwx 2 root root  4096 Dec 22 14:19 conn
drwxrwxrwx 2 root root 12288 Dec 22 14:16 data
prw--w--w- 1 root root     0 Dec 22 14:16 sr_evpipe1
prw--w--w- 1 root root     0 Dec 22 14:19 sr_evpipe2
prw--w--w- 1 root root     0 Dec 22 14:16 sr_evpipe3
-rw-rw-rw- 1 root root     0 Dec 22 13:59 sr_main_lock
drwxrwxrwx 2 root root  4096 Dec 22 14:16 yang
~~~

**Comment by nhathaway** [comment]
The problem seems to relate to the fact that I fork/exec subprocess which does an update to the datastore (a script runs sysreopcfg in the subprocess) . Commenting out the fork/exec stops the problem. I'm suspecting it may have something to do with close-on-exec (or lack of it) on open shared memory devices.

Any ideas on how to work around this?

**Comment by nhathaway** [comment]
The problem goes away if you suspend the parent process (which hosts the RPC callback) while the sub-process runs to completion. It's not a locking/contention issue, since the subprocess has completed before the RPC is called.

A mystery...

**Comment by jktjkt** [comment]
How do both the parent and the child look like when `strace`d?

**Comment by michalvasko** [comment]
I can only think of one problem, mentioned in the [docs](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__conn__sess__api.html#ga822c82f228f5772907fb70ffa9c9ffce).

**Comment by nhathaway** [comment]
It says do not fork as you will have 2 processes with the same ID. However, we are talking about fork/exec. Exec wipes the memory image of the forked process so the ID etc will not be available to the new exec'd process. Exec also unmaps any shared memory, as well as closing any fd's with close-on-exec set.

To say that you can't fork/exec (which I don't believe it does) would be a crippling restriction for any program, as this is Linux's means of running another program from the original program.

**Comment by michalvasko** [comment]
> However, we are talking about fork/exec.

Yes, sorry, this should be fine. I have checked and all the file descriptors should have the O_CLOEXEC flag set.

Then I have no idea what the problem may be and would probably go back to
> Under previous versions (the last in the 2.0 series) this bug did not occur, so it has been more recently introduced.

meaning isolate the commit that causes the issue. I am really not aware of any recent changes that could cause this.
