### ISSUE TITLE
LYB DS file: Changing owner of "<yangname>.startup.bck" failed (Operation not permitted)

### ISSUE THREAD

**Issue by nhathaway** [sysrepo/sysrepo#2973]
Software version: the collection released in November 2022

$ sysrepocfg -V
sysrepocfg - sysrepo configuration manipulation tool, compiled with libsysrepo v2.2.12 (SO v7.11.8)

C code

~~~
                sr_session_switch_ds (data->session, SR_DS_STARTUP);
                rc = sr_copy_config(data->session, "o-ran-usermgmt", SR_DS_RUNNING , 0);
                sr_session_switch_ds (data->session, SR_DS_RUNNING);
~~~

Console log:

~~~
[ERR] LYB DS file: Changing owner of "/etc/sysrepo/data/o-ran-usermgmt.startup.bck" failed (Operation not permitted).
[ERR] Callback "store" of plugin "LYB DS file" for module "o-ran-usermgmt" failed.
~~~

The test user is an ordinary user and not a member of the netconf group. However the permissions are world r/w.

~~~
$ ls -al /etc/sysrepo/data/o-ran-usermgmt.*
-rw-rw-rw- 1 root netconf   0 Dec 22 10:57 /etc/sysrepo/data/o-ran-usermgmt.candidate.perm
-rw-rw-rw- 1 root netconf   0 Dec 22 10:57 /etc/sysrepo/data/o-ran-usermgmt.operational.perm
-rw-rw-rw- 1 root netconf   0 Dec 22 10:57 /etc/sysrepo/data/o-ran-usermgmt.running.perm
-rw-rw-rw- 1 root netconf 137 Dec 22 10:57 /etc/sysrepo/data/o-ran-usermgmt.startup
~~~

Under previous versions (the last in the 2.0 series) this issue did not occur, so it has been more recently introduced.

**Comment by michalvasko** [comment]
Same reply as in #2972.

**Comment by nhathaway** [comment]
I've done as you described, and the problem still persists.

**Comment by michalvasko** [comment]
Okay, I have then reproduced it and fixed it. I wanted to be extra safe when performing a back up of `startup` and use the same owner/group for the backup but having the same permissions should be good enough.

**Comment by nhathaway** [comment]
If you can put the link to the update/patch here, I will apply it to my build and verify it.

**Comment by michalvasko** [comment]
I referenced it, the link is a few posts above.

**Comment by nhathaway** [comment]
Sorry, I missed that.

A quick observation: the patch is to src/plugins/ds_json.c in the devel branch. The master has this in src/plugins/ds_lyb.c . The change is the same there.

[sysrepo.patch](https://github.com/sysrepo/sysrepo/files/10294145/sysrepo.patch)

Patch applied and verified as working.

**Comment by michalvasko** [comment]
Yes, `master` will not be changed until the next release, it never is.
