### ISSUE TITLE
Changing owner of "/dev/shm/sr_xxxxxx.operational" failed

### ISSUE THREAD

**Issue by nhathaway** [sysrepo/sysrepo#2974]
Software version: the collection released in November 2022

$ sysrepocfg -V
sysrepocfg - sysrepo configuration manipulation tool, compiled with libsysrepo v2.2.12 (SO v7.11.8)

We see the following:

~~~
[ERR] LYB DS file: Changing owner of "/dev/shm/sr_xxxxxx.operational" failed (Operation not permitted).
[ERR] Callback "store" of plugin "LYB DS file" for module "xxxxxx" failed.
~~~

(xxxxxx is our own yang)

The executable is running as the test user (which is not root or a member of the netconf group) and the permissions on the yang are 666. The yang is owned by root/netconf.

The key difference between this and other yangs is that it only has non-config data. The issue seems to occur on the first setting of operational data.

Under previous versions (the last in the 2.0 series) this issue did not occur, so it has been more recently introduced.

**Comment by nhathaway** [comment]
I added sum dummy config data to the yang, and it made no difference. So the fact that it is non-config only does not seem to be the issue.

**Comment by michalvasko** [comment]
I would need some more details to reproduce. Please include the steps starting with no data (after `make sr_clean`).

**Comment by nhathaway** [comment]
A yang file that demonstrates the issue:

~~~
module abcd-e-widget-control {
  yang-version 1.1;
  namespace "urn:abcd-e-widget-control:1.0";
  prefix "abcd-e-widget-control";

  import ietf-yang-types {
    prefix yang;
  }

  import ietf-netconf-acm {
    prefix nacm;
    reference
      "RFC 8341: Network Configuration Access Control Model";
  }

  container widget {
    config false;

    container control {
      leaf sequence {
        type uint32;
      }
    }
  }
}
~~~

XML loaded as operational data:

~~~
<widget xmlns="urn:abcd-e-widget-control:1.0">
  <control>
    <sequence>1</sequence>
  </control>
</widget>
~~~

Or via the command line:

~~~
$ oper_data_push_example /abcd-e-widget-control:widget/control/sequence 1
Application will set "/abcd-e-widget-control:widget/control/sequence" to value "1".

[ERR] LYB DS file: Changing owner of "/dev/shm/sr_abcd-e-widget-control.operational" failed (Operation not permitted).
[ERR] Callback "store" of plugin "LYB DS file" for module "abcd-e-widget-control" failed.
[ERR] LYB DS file: Unknown libyang error.
[ERR] Callback "load" of plugin "LYB DS file" for module "abcd-e-widget-control" failed.
~~~

I would be nice to think there is something subtle wrong with my yang that can just be fixed...

**Comment by nhathaway** [comment]
~~~
$ ls -l /etc/sysrepo/yang/abcd-e-widget-control.yang 
-rw-r--r-- 1 root root 429 Dec 23 12:59 /etc/sysrepo/yang/abcd-e-widget-control.yang

$ ls -l /etc/sysrepo/data/abcd-e-widget-control.*
-rw-rw-rw- 1 root netconf  0 Dec 23 12:59 /etc/sysrepo/data/abcd-e-widget-control.candidate.perm
-rw-rw-rw- 1 root netconf  0 Dec 23 12:59 /etc/sysrepo/data/abcd-e-widget-control.operational.perm
-rw-rw-rw- 1 root netconf  0 Dec 23 12:59 /etc/sysrepo/data/abcd-e-widget-control.running.perm
-rw-rw-rw- 1 root netconf 11 Dec 23 12:59 /etc/sysrepo/data/abcd-e-widget-control.startup

$ ls -l /dev/shm/sr_abcd-e-widget-control.*
-rw-rw-rw- 1 nigel nigel 0 Dec 23 13:02 /dev/shm/sr_abcd-e-widget-control.operational
~~~

**Comment by michalvasko** [comment]
Okay, should be fixed with no adverse effects, I think.

**Comment by nhathaway** [comment]
Confirmed as working.

Patch file for this and #2973 :

[sysrepo.patch](https://github.com/sysrepo/sysrepo/files/10295800/sysrepo.patch)
