### ISSUE TITLE
sr_module_change_subscribe  callback wrong issue

### ISSUE THREAD

**Issue by fujun1979** [sysrepo/sysrepo#2975]
we use bbf-olt-vomci yang model, the model is from "https://github.com/BroadbandForum/yang/tree/d22053b5473cabf7b712310fc8f9e87fe46fc129/standard/application"
 we subscribed the nf-client and nf-server , the code as below:

#define BBF_POLT_VOMCI_MODULE_NAME          "bbf-olt-vomci"
#define BBF_NF_ENDPOINT_FILTER_MODULE_NAME  "bbf-nf-endpoint-filter"
#define BBF_POLT_VOMCI_SERVER_PATH          "/bbf-olt-vomci:remote-network-function/nf-server"
#define BBF_POLT_VOMCI_CLIENT_PATH          "/bbf-olt-vomci:remote-network-function/nf-client"
#define BBF_POLT_VOMCI_FILTER_PATH          "/bbf-olt-vomci:remote-network-function/nf-endpoint-filter"

    sr_rc = sr_module_change_subscribe(srs, BBF_POLT_VOMCI_MODULE_NAME, BBF_POLT_VOMCI_SERVER_PATH,
            bbf_polt_vomci_server_change_cb, NULL, 0, SR_SUBSCR_ENABLED | SR_SUBSCR_CTX_REUSE,
            &sr_ctx);

    sr_rc = sr_module_change_subscribe(srs, BBF_POLT_VOMCI_MODULE_NAME, BBF_POLT_VOMCI_CLIENT_PATH,
            bbf_polt_vomci_client_change_cb, NULL, 0, SR_SUBSCR_ENABLED | SR_SUBSCR_CTX_REUSE,
            &sr_ctx);

But when there is only nf-client data add, nf-server callback function also is trigged.

**Comment by michalvasko** [comment]
> But when there is only nf-client data add, nf-server callback function also is trigged.

So look at the changes in the server callback, that should give you an idea about what is happening exactly.
