### ISSUE TITLE
crash in sr_conn_is_alive()/sr_shmmain_conn_check() since v2.2.30

### ISSUE THREAD

**Issue by Haititi** [sysrepo/sysrepo#2976]
Hi,

I have an assert failure that appears only in v2.2.30 (all good in v2.2.29).
this crash is due to the `cid` value which is equal to `0`, hence the `assert(cid && conn_alive);` failing in `sr_shmmain_conn_check()`.

After some tests, this error is introduced by the following commit : https://github.com/sysrepo/sysrepo/commit/bb8cfc748379fca3e4286367c0780057d946b897.

I see in the commit description that the removed code should not be necessary.
Maybe there is a case where it is indeed necessary?

my crash always happens at the first startup of my service. When i restart my service, there is no more crash but i get a lot of warnings in my logs :
> Jan 05 16:47:25 ubuntu2004 @[30836]: [WRN] Connection with CID 17 is dead.
> Jan 05 16:47:25 ubuntu2004 @[30836]: [WRN] Recovering module "ietf-alarms" operational get subscription of CID 17.
> Jan 05 16:47:25 ubuntu2004 @[30836]: [WRN] Recovering module "ietf-alarms" operational get subscription of CID 17.
> Jan 05 16:47:25 ubuntu2004 @[30836]: [WRN] Recovering module "ietf-alarms" operational get subscription of CID 17.
> Jan 05 16:47:25 ubuntu2004 @[30836]: [WRN] Recovering RPC/action "/ietf-alarms:alarms/alarm-list/purge-alarms" subscription of CID 17.
> Jan 05 16:47:25 ubuntu2004 @[30836]: [WRN] Recovering RPC/action "/ietf-alarms:alarms/alarm-list/compress-alarms" subscription of CID 17.
> Jan 05 16:47:27 ubuntu2004 @[30836]: [WRN] Recovering module "MyModule" operational get subscription of CID 17.
> Jan 05 16:47:27 ubuntu2004 @[30836]: [WRN] Recovering RPC/action "/MyModule:rpc1" subscription of CID 17.
> Jan 05 16:47:27 ubuntu2004 @[30836]: [WRN] Recovering RPC/action "/MyModule:rpc2" subscription of CID 17.
> ...

Thanks for your help.

**Comment by michalvasko** [comment]
Can you please provide the backtrace of all the threads at the moment of the failed assert?

**Comment by Haititi** [comment]
Well, i can share you the backtrace of all thread, but I'm using sysrepo-python bindings over sysrepo APIs.
I don't know if this will help.

> (gdb) thread apply all bt
> Thread 3 (Thread 0x7f9191142700 (LWP 42660)):
> #0  futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x26f41e0) at ../sysdeps/nptl/futex-internal.h:320
> #1  do_futex_wait (sem=sem@entry=0x26f41e0, abstime=0x0, clockid=0) at sem_waitcommon.c:112
> #2  0x00007f91959a5548 in __new_sem_wait_slow (sem=0x26f41e0, abstime=0x0, clockid=0) at sem_waitcommon.c:184
> #3  0x0000000000544ac3 in PyThread_acquire_lock_timed ()
> #4  0x00007f9195131bb1 in  () at /usr/lib/python3.8/lib-dynload/_queue.cpython-38-x86_64-linux-gnu.so
> #5  0x00000000005c4677 in  ()
> #6  0x000000000056cc92 in _PyEval_EvalFrameDefault ()
> #7  0x00000000005f5ee6 in _PyFunction_Vectorcall ()
> #8  0x00000000005f52b2 in PyObject_Call ()
> #9  0x000000000056d2bc in _PyEval_EvalFrameDefault ()
> #10 0x00000000005f5ee6 in _PyFunction_Vectorcall ()
> #11 0x000000000056bbe1 in _PyEval_EvalFrameDefault ()
> #12 0x00000000005f5ee6 in _PyFunction_Vectorcall ()
> #13 0x000000000056bbe1 in _PyEval_EvalFrameDefault ()
> #14 0x00000000005f5ee6 in _PyFunction_Vectorcall ()
> #15 0x000000000050b32c in  ()
> #16 0x00000000005f52b2 in PyObject_Call ()
> #17 0x00000000006568ec in  ()
> #18 0x0000000000677e08 in  ()
> #19 0x00007f919599b609 in start_thread (arg=<optimized out>) at pthread_create.c:477
> #20 0x00007f9195ad5133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
> 
> Thread 2 (Thread 0x7f9191a40700 (LWP 42518)):
> #0  futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x3b784a0) at ../sysdeps/nptl/futex-internal.h:320
> #1  do_futex_wait (sem=sem@entry=0x3b784a0, abstime=0x0, clockid=0) at sem_waitcommon.c:112
> #2  0x00007f91959a5548 in __new_sem_wait_slow (sem=0x3b784a0, abstime=0x0, clockid=0) at sem_waitcommon.c:184
> #3  0x0000000000544ac3 in PyThread_acquire_lock_timed ()
> #4  0x00007f9195131bb1 in  () at /usr/lib/python3.8/lib-dynload/_queue.cpython-38-x86_64-linux-gnu.so
> #5  0x00000000005c4677 in  ()
> #6  0x000000000056cc92 in _PyEval_EvalFrameDefault ()
> #7  0x00000000005f5ee6 in _PyFunction_Vectorcall ()
> #8  0x00000000005f52b2 in PyObject_Call ()
> #9  0x000000000056d2bc in _PyEval_EvalFrameDefault ()
> #10 0x00000000005f5ee6 in _PyFunction_Vectorcall ()
> #11 0x000000000056bbe1 in _PyEval_EvalFrameDefault ()
> #12 0x00000000005f5ee6 in _PyFunction_Vectorcall ()
> #13 0x000000000056bbe1 in _PyEval_EvalFrameDefault ()
> #14 0x00000000005f5ee6 in _PyFunction_Vectorcall ()
> #15 0x000000000050b32c in  ()
> #16 0x00000000005f52b2 in PyObject_Call ()
> #17 0x00000000006568ec in  ()
> #18 0x0000000000677e08 in  ()
> #19 0x00007f919599b609 in start_thread (arg=<optimized out>) at pthread_create.c:477
> #20 0x00007f9195ad5133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
> 
> Thread 1 (Thread 0x7f91957ea740 (LWP 42452)):
> #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
> #1  0x00007f91959d8859 in __GI_abort () at abort.c:79
> #2  0x00007f91959d8729 in __assert_fail_base (fmt=0x7f9195b6e588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7f9193f38d60 "cid && conn_alive", file=0x7f9193f38d10 "/root/sshfs_root/sysrepo/src/shm_main.c", line=187, function=<optimized out>) at assert.c:92
> #3  0x00007f91959e9fd6 in __GI___assert_fail (assertion=0x7f9193f38d60 "cid && conn_alive", file=0x7f9193f38d10 "/root/sshfs_root/sysrepo/src/shm_main.c", line=187, function=0x7f9193f38eb0 <__PRETTY_FUNCTION__.10963> "sr_shmmain_conn_check") at assert.c:101
> #4  0x00007f9193f0833c in sr_shmmain_conn_check (cid=0, conn_alive=0x7fff6f6d38fc, pid=0x0) at /root/sshfs_root/sysrepo/src/shm_main.c:187
> #5  0x00007f9193ee73aa in sr_conn_is_alive (cid=0) at /root/sshfs_root/sysrepo/src/common.c:4792
> #6  0x00007f9193f17abd in sr_shmsub_change_notify_has_subscription (conn=0x2cd0a10, mod=0x239ccb0, ds=SR_DS_RUNNING, ev=SR_SUB_EV_UPDATE, max_priority_p=0x7fff6f6d39b8) at /root/sshfs_root/sysrepo/src/shm_sub.c:923
> #7  0x00007f9193f185a0 in sr_shmsub_change_notify_update (mod_info=0x7fff6f6d3b80, orig_name=0x0, orig_data=0x0, timeout_ms=5000, update_edit=0x7fff6f6d3aa8, cb_err_info=0x7fff6f6d3b78) at /root/sshfs_root/sysrepo/src/shm_sub.c:1179
> #8  0x00007f9193ef7c8c in sr_modinfo_change_notify_update (mod_info=0x7fff6f6d3b80, session=0x3b1ae90, timeout_ms=5000, change_sub_lock=0x7fff6f6d3b10, cb_err_info=0x7fff6f6d3b78) at /root/sshfs_root/sysrepo/src/modinfo.c:2991
> #9  0x00007f9193ed1dca in sr_changes_notify_store (mod_info=0x7fff6f6d3b80, session=0x3b1ae90, timeout_ms=5000, cb_err_info=0x7fff6f6d3b78) at /root/sshfs_root/sysrepo/src/sysrepo.c:3527
> #10 0x00007f9193ed25c2 in _sr_replace_config (session=0x3b1ae90, ly_mod=0x2d780a0, src_config=0x7fff6f6d3bd8, timeout_ms=5000) at /root/sshfs_root/sysrepo/src/sysrepo.c:3727
> #11 0x00007f9193ed2842 in sr_replace_config (session=0x3b1ae90, module_name=0x3124fc0 "ietf-netconf-server", src_config=0x0, timeout_ms=5000) at /root/sshfs_root/sysrepo/src/sysrepo.c:3780
> #12 0x00007f9193f6ab9e in _cffi_f_sr_replace_config (self=<optimized out>, args=<optimized out>) at build/temp.linux-x86_64-cpython-38/_sysrepo.c:3698
> #13 0x00000000005f5bda in PyCFunction_Call ()
> #14 0x00000000005717f5 in _PyEval_EvalFrameDefault ()
> #15 0x0000000000569d8a in _PyEval_EvalCodeWithName ()
> #16 0x00000000005f60c3 in _PyFunction_Vectorcall ()
> #17 0x000000000056bab6 in _PyEval_EvalFrameDefault ()
> #18 0x0000000000569d8a in _PyEval_EvalCodeWithName ()
> #19 0x000000000050b3a0 in  ()
> #20 0x000000000056cc92 in _PyEval_EvalFrameDefault ()
> #21 0x0000000000569d8a in _PyEval_EvalCodeWithName ()
> #22 0x00000000005f60c3 in _PyFunction_Vectorcall ()
> #23 0x000000000056bbe1 in _PyEval_EvalFrameDefault ()
> #24 0x0000000000500c48 in  ()
> #25 0x00007f919511fef9 in  () at /usr/lib/python3.8/lib-dynload/_asyncio.cpython-38-x86_64-linux-gnu.so
> #26 0x00007f9195121083 in  () at /usr/lib/python3.8/lib-dynload/_asyncio.cpython-38-x86_64-linux-gnu.so
> #27 0x00000000005f6706 in _PyObject_MakeTpCall ()
> #28 0x00000000005ff2a3 in  ()
> #29 0x00000000005c4677 in  ()
> #30 0x00000000005f5878 in PyVectorcall_Call ()
> #31 0x00000000005717f5 in _PyEval_EvalFrameDefault ()
> #32 0x00000000005f5ee6 in _PyFunction_Vectorcall ()
> #33 0x000000000056bbe1 in _PyEval_EvalFrameDefault ()
> #34 0x00000000005f5ee6 in _PyFunction_Vectorcall ()
> #35 0x000000000056bbe1 in _PyEval_EvalFrameDefault ()
> #36 0x00000000005f5ee6 in _PyFunction_Vectorcall ()
> #37 0x000000000056bbe1 in _PyEval_EvalFrameDefault ()
> #38 0x00000000005f5ee6 in _PyFunction_Vectorcall ()
> #39 0x000000000056bbe1 in _PyEval_EvalFrameDefault ()
> #40 0x0000000000569d8a in _PyEval_EvalCodeWithName ()
> #41 0x00000000005f60c3 in _PyFunction_Vectorcall ()
> #42 0x0000000000570b82 in _PyEval_EvalFrameDefault ()
> #43 0x0000000000569d8a in _PyEval_EvalCodeWithName ()
> #44 0x000000000068e267 in PyEval_EvalCode ()
> #45 0x0000000000600704 in  ()
> #46 0x00000000005c4790 in  ()
> #47 0x000000000056bab6 in _PyEval_EvalFrameDefault ()
> #48 0x0000000000569d8a in _PyEval_EvalCodeWithName ()
> #49 0x000000000068e267 in PyEval_EvalCode ()
> #50 0x000000000067d9b1 in  ()
> #51 0x000000000067da2f in  ()
> #52 0x000000000067dad1 in  ()
> #53 0x000000000067fbf7 in PyRun_SimpleFileExFlags ()
> #54 0x00000000006b8082 in Py_RunMain ()
> #55 0x00000000006b840d in Py_BytesMain ()
> #56 0x00007f91959da083 in __libc_start_main (main=0x4ef3b0 < main>, argc=2, argv=0x7fff6f6d5928, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff6f6d5918) at ../csu/libc-start.c:308
> #57 0x00000000005faa2e in _start ()
> (gdb)

**Comment by michalvasko** [comment]
Please try the latest *sysrepo*, the problematic change has been reverted.
