### ISSUE TITLE
netopeer2-server Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by hi-Mr-ye** [sysrepo/sysrepo#2977]
Hi!
netopeer2-server Segmentation fault (core dumped)
This is the printed information:
![image](https://user-images.githubusercontent.com/90752673/210911643-b0b0be27-fc4a-4433-a8be-7f4c3adfbfc6.png)
and gdb debug information:
![image](https://user-images.githubusercontent.com/90752673/210911792-a751bb33-c706-4bf4-a97c-bf6e8b92f3b4.png)
but why?
netopeer2-server version :
![image](https://user-images.githubusercontent.com/90752673/210912056-dc50a51f-88f4-4af8-b849-015cea7b1524.png)

**Comment by michalvasko** [comment]
Try it with the latest *libyang*, you should get some actual error but I have no idea what causes that.
