### ISSUE TITLE
Send notification with choices item inside config false container

### ISSUE THREAD

**Issue by satomhxl** [sysrepo/sysrepo#2978]
Hello, I have a question of sending notification.

I called
`sr_notif_send(session, "/o-ran-performance-management:measurement-result-stats", notif_val, notif_cnt, 0, 0);`
to send a notification, but it returns
`[ERR] Mandatory node "count" instance does not exist. (Schema location "/o-ran-performance-management:measurement-result-stats/rx-window-stats/multiple-rx-window-measurement-result/object-unit-id/RU/count", data location "/o-ran-performance-management:measurement-result-stats".)`
`[ERR] Notification validation failed.`

Then I print the data inside **notif_val** using `sr_print_val`, there are several items:
`/o-ran-performance-management:measurement-result-stats/rx-window-stats[measurement-object='RX_ON_TIME']/measurement-object = RX_ON_TIME`
`/o-ran-performance-management:measurement-result-stats/rx-window-stats[measurement-object='RX_ON_TIME']/multiple-rx-window-measurement-result[3]/start-time = 2023-01-09T17:31:00+08:00`
`/o-ran-performance-management:measurement-result-stats/rx-window-stats[measurement-object='RX_ON_TIME']/multiple-rx-window-measurement-result[3]/end-time = 2023-01-09T17:31:10+08:00`
`/o-ran-performance-management:measurement-result-stats/rx-window-stats[measurement-object='RX_ON_TIME']/multiple-rx-window-measurement-result[3]/name = RU`
`/o-ran-performance-management:measurement-result-stats/rx-window-stats[measurement-object='RX_ON_TIME']/multiple-rx-window-measurement-result[3]/count = 0`
which in my opinion meets the requirement **Mandatory node "count" instance**.

So why this error happens, can you give me some hints？
The sysrepo version I'm using is `2.1.84`
The `session` in `sr_notif_send` call is connected to operational datastore.
Part content of `multiple-rx-window-measurement-result`:
```
  list multiple-rx-window-measurement-result {
    config false;

    leaf start-time {
      type yang-types:date-and-time;
      description
        "Start time for measurement of object stats";
    }
    leaf end-time {
      type yang-types:date-and-time;
      description
        "End time for measurement of object stats";
    }
    choice object-unit-id {
      config false;
      case RU {
        leaf name{
          type leafref {
            path "/hw:hardware/hw:component/hw:name";
          }

          description
            "the name of O-RU module or one of its child ports
            in ietf-hardware/component is used when O-RU is selected as
            object-unit for the reception window stats.";
        }
        leaf count {
          type uint64;
          mandatory true;

          description
            "the number of data packet are counted for the reception
             window stats per O-RU.";
        }
      }
    }
  }
```
The full yang model: 
[o-ran-performance-management.yang.txt](https://github.com/sysrepo/sysrepo/files/10373008/o-ran-performance-management.yang.txt)
My test function to send notification:
[test_func.c.txt](https://github.com/sysrepo/sysrepo/files/10378567/test_func.c.txt)

If you need other information, please let me know, many thanks.

**Comment by satomhxl** [comment]
I tried to remove the "mandatory true" of the "count" instance in yang model, and see if notification can be sent.

Then I see the notification generated by the test function above:
```
notification (2023-01-11T16:07:03.017901369+08:00)
<measurement-result-stats xmlns="urn:o-ran:performance-management:1.0">
  <rx-window-stats>
    <measurement-object>RX_ON_TIME</measurement-object>
    <start-time>2023-01-09T17:31:10+08:00</start-time>
    <end-time>2023-01-09T17:31:20+08:00</end-time>
    <name>RU</name>
    <count>0</count>
    <multiple-rx-window-measurement-result>
      <start-time>2023-01-09T17:31:10+08:00</start-time>
    </multiple-rx-window-measurement-result>
    <multiple-rx-window-measurement-result>
      <end-time>2023-01-09T17:31:20+08:00</end-time>
    </multiple-rx-window-measurement-result>
    <multiple-rx-window-measurement-result>
      <name>RU</name>
    </multiple-rx-window-measurement-result>
    <multiple-rx-window-measurement-result>
      <count>0</count>
    </multiple-rx-window-measurement-result>
  </rx-window-stats>
</measurement-result-stats>
```

We can see that many tags are split to individual <multiple-rx-window-measurement-result> tag, but I think they should be in one <multiple-rx-window-measurement-result> tag, how can I achieve that?

**Comment by satomhxl** [comment]
Seems when the index starts from 1, and increases one by one continuously, the notification works fine.

**Comment by michalvasko** [comment]
I believe this is caused by problematic handing of key-less lists. I would advise to use `sr_notif_send_tree()` for control over what data are actually created, which should solve the original problem as well, when you are able to create a single instance of `multiple-rx-window-measurement-result`.

**Comment by satomhxl** [comment]
Is this a bug in sysrepo, would this be fixed in the future?
I also want to know, according to YANG specification, does the index of key-less list should be started from 1?

**Comment by michalvasko** [comment]
> Is this a bug in sysrepo, would this be fixed in the future?

It is impossible to know whether a new instance is supposed to be created or an existing one modified (no way to identify the instance) so it is not really a bug and it will not be fixed.

> I also want to know, according to YANG specification, does the index of key-less list should be started from 1?

YANG specification does not say much about key-less lists because they are `config false` and there is no need to address them. It needs to be done in *sysrepo* but it is strictly implementation-dependent. We have decided to address them starting from 1 because that is how XPath addressing (position) works.

**Comment by satomhxl** [comment]
OK, thank you.
