### ISSUE TITLE
netopeer2-server log printing

### ISSUE THREAD

**Issue by fancy-fx** [sysrepo/sysrepo#2981]
Hi
use sr_log_stderr to turn logging on, and The file to which the log information is saved?
Can I save log information to a specified file?

**Comment by michalvasko** [comment]
From the function name itself, `sr_log_stderr` meaning it will log to `stderr`. If you want to store the log into a file, use `sr_log_set_cb` and store the messages into a file in the callback yourself.

**Comment by fancy-fx** [comment]
Command output using netopeer2-server d-v3.
How can I save the log information printed by netopeer2-server to a file in a specified directory?
The default directory is /var/log.Can it be modified?

**Comment by michalvasko** [comment]
> The default directory is /var/log.Can it be modified?

I do not know what you are talking about, there is no direct way of printing the output to a file and hence no default directory. You can always use `netopeer2-server -d -v2 > /path/to/the/file` to redirect the output to a file.

**Comment by hi-Mr-ye** [comment]
Hi
I use netopeer2-server -d -v2 > ./test.log. but test.log is empty. why?

**Comment by michalvasko** [comment]
Okay, the server prints everything to `stderr` instead of `stdout, so use `netopeer2-server -d -v2 2> /path/to/the/file`.

**Comment by hi-Mr-ye** [comment]
Thank you very much!
