### ISSUE TITLE
Netopeer2 data retrieval often fails with `Error: Path "data-lock[cid='55'][datastore='ietf-datastores:operational']/mode" already exists (Data location "/sysrepo-monitoring:sysrepo-state/module[name='MY-MODULE']/data-lock[cid='55'][datastore='ietf-datastores:operational']/mode".)`

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#2984]
We're updating sysrepo from sysrepo/sysrepo@f46ea7bc5a9cb13b9f0d8221d1f08bdc2d5b703c to sysrepo/sysrepo@15f8d9d64a4266576d0547f3426f4ad78aab5689 and Netopeer2 from CESNET/netopeer2@92f47fd547d0ab7b2afc59175c8f56ff360591b6 to CESNET/netopeer2@9d3c74948a44e361ad91187b609ddcfceb60e8f8 (along with the rest of the stack of course). Our HW has an application with a continuously running loop that pushes some stuff into the operational DS, over and over again, roughly once or twice a second. When asked for a simple data retrieval (`<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="53"><get-data xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-nmda"><datastore xmlns:ds="urn:ietf:params:xml:ns:yang:ietf-datastores">ds:operational</datastore><with-defaults>report-all</with-defaults></get-data></rpc>`), the NETCONF server sometimes replies with the following error:
```
Path "data-lock[cid='55'][datastore='ietf-datastores:operational']/mode" already exists (Data location "/sysrepo-monitoring:sysrepo-state/module[name='czechlight-roadm-device']/data-lock[cid='55'][datastore='ietf-datastores:operational']/mode".)
```
The `czechlight-roadm-device` is the module which is being fed in the operational DS via that periodic, continuously running thread. When this happens, the following gets logged into syslog:
```
2023-01-13T21:52:11.040943+0000 line-qr79 netopeer2-server[544]: Getting data "/*" from sysrepo failed (libyang error).
2023-01-13T21:52:11.042303+0000 line-qr79 netopeer2-server[544]: Failed to send an RPC (User callback failed).
```
I've never seen that with previous versions of sysrepo which have always returned data without errors, as far as I can remember. Why is this happening, and what can I do to mitigate that?

**Comment by michalvasko** [comment]
I assume it was caused by the new write urge lock, so that should be handled now. Please test that it is fixed, thanks.

**Comment by jktjkt** [comment]
Thanks, I no longer see the original error. I got at least one execution which took a notable large time (7s+), but I don't have nay details (nor specific performance trace).

**Comment by michalvasko** [comment]
I see, would be nice to learn what that is about but I believe it is a completely separate issue, nothing to do with this one.
