### ISSUE TITLE
Implement Oven Plugin in sysrepo

### ISSUE THREAD

**Issue by anavajasc** [sysrepo/sysrepo#2986]
Hi, I am trying to implement the oven application in my sysrepo. I have the required repositories cloned correctly in my VM: (libnetconf2  libssh-0.9.0  libyang  netopeer2  sysrepo). But I am new using Netopeer2 and I do not have much idea how to implement this oven application, this is the URL of the oven example: https://github.com/sysrepo/sysrepo/tree/master/examples/plugin

Can you give me some suggestions.

Regards,
Alvaro.

**Comment by michalvasko** [comment]
Look into the docs for a proper [guide](https://netopeer.liberouter.org/doc/sysrepo/master/html/srpd_example.html).

**Comment by anavajasc** [comment]
I have being looking into the docs and I have installed the application in the sysrepo with the command syrepoctl -v3 -i oven.yang. But I am stuck in the first step in the Trying it out paragraph: 

  1.As the very first step, subscribe to oven notifications using notif_subscribe_example
     notif_subscribe_example oven

In my VM I tried to run the command but I found this:

**Comment by anavajasc** [comment]
I have installed the first the model in VM as the documentation say with:

1. Model installation: root@ubuntu:~/netconf/sysrepo/build/examples# sysrepoctl -i oven.yang

Then I made the plugin installation

2. Plugin installation using: root@ubuntu:~/netconf/sysrepo/build/examples# sysrepo-plugind -d -P oven.so 
                                            root@ubuntu:~/netconf/sysrepo/build/examples#

After that I should see that the oven plugin was successfully initialized. But I have not seen anything.

And then when I execute the RPC to insert food, I got an error like this:

3. RPC insert-food: root@ubuntu:~/netconf/sysrepo/build/examples# sysrepocfg --rpc=vim
                              sysrepocfg error: Exec failed (No such file or directory)
                              For more details you may try to increase the verbosity up to "-v3".
                              libyang error: Missing the operation node. (Line number 1.)
                              sysrepocfg error: Data parsing failed
                              For more details you may try to increase the verbosity up to "-v3".
                              
Please, can you give me some suggestions?
Thank you.
Alvaro.

**Comment by michalvasko** [comment]
> After that I should see that the oven plugin was successfully initialized. But I have not seen anything.

You need to start `sysrepo-plugind`, which actually loads and initialized the plugin to see that.

**Comment by anavajasc** [comment]
And how I can start sysrepo-plugind, I am a bit confused about that. I mean, Where are the steps in the documentation to start sysrepo-plugind?

Thanks in advance.

**Comment by michalvasko** [comment]
This is really basic Linux stuff and I cannot keep helping you with such things, you will get stuck on every single step unless you have some experience with Linux systems. The binary is part of the *sysrepo* project and is installed when *sysrepo* is installed. Then you should be able to run it in a terminal.

**Comment by michalvasko** [comment]
Do you even have `vim` installed, does the command `vim` work?
