### ISSUE TITLE
Call to sr_module_change_subscribe() returns "Item not found"

### ISSUE THREAD

**Issue by TeSwen** [sysrepo/sysrepo#2988]
An application I'm working with, the Free Range Router, has developed a plugin for sysrepo.   Upon starting the application the Sysrepo module fails to get initialized because of the subscription error in the title.   Using strace I can see the below errors.   Is Sysrepo expected to have created these files at some point?  (I do start netopeer2-server before starting the FRR application.) All of the below referenced yang models exist in the yang repository and are rw-rw-rw so there should be no permission problems.  

openat(AT_FDCWD, "/dev/shm/sr_ietf-yang-schema-mount.operational", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/shm/sr_ietf-yang-library.operational", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/shm/sr_ietf-netconf-acm.operational", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/shm/sr_sysrepo-monitoring.operational", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/shm/sr_sysrepo-plugind.operational", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/shm/sr_ietf-netconf-monitoring.operational", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/shm/sr_nc-notifications.operational", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/shm/sr_ietf-keystore.operational", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/shm/sr_ietf-truststore.operational", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/shm/sr_ietf-netconf-server.operational", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/shm/sr_ietf-interfaces.operational", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/shm/sr_ietf-network-instance.operational", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/shm/sr_ietf-subscribed-notifications.operational", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/shm/sr_frr-interface.operational", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/shm/sr_frr-vrf.operational", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/shm/sr_frr-routing.operational", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/shm/sr_frr-route-map.operational", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/shm/sr_frr-nexthop.operational", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/shm/sr_frr-ripd.operational", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/shm/sr_frr-ripngd.operational", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/shm/sr_frr-isisd.operational", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/shm/sr_frr-zebra.operational", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/shm/sr_frr-pathd.operational", O_RDONLY|O_NOFOLLOW|O_CLOEXEC) = -1 ENOENT (No such file or directory)

**Comment by michalvasko** [comment]
What *sysrepo* version are you using? In past there were some problems like this that should now all be fixed.

**Comment by TeSwen** [comment]
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v2.2.12 (SO v7.11.8)

**Comment by michalvasko** [comment]
Okay, I think that should be fine. So I would need to reproduce it to have a chance of fixing it. Can you start with `make sr_clean` in *sysrepo* until you encounter the error? Post the exact steps here.

**Comment by TeSwen** [comment]
It turns out that the application subscribes to a yang module that I hadn't imported into the Sysrepo datastore.   So this I believe was causing the problems.    Once I imported the yang module, the application went on to initialize the sysrepo module successfully.   Things are still not working perfectly but its not likely in the Sysrepo court anymore.    If anyone's following along, the Yang module it needed was frr-filter.yang.     Thanks for the help.
