### ISSUE TITLE
Crash when edit-config with both add/delete on same list entry

### ISSUE THREAD

**Issue by meghna-doshi** [sysrepo/sysrepo#2989]
Hi,
We are observing crash when we tried (though by mistake but still s/w shouldnt crash!!) delete and add of the same entry in the xml given for edit-config.
Steps to reproduce:
1. install my-yang.yang  (complete yang folder attached with all dependent yangs)
2. run netopeer2-cli and server
3. edit-config --target running --config=/tmp/crash.xml   ------> this works fine.
4. edit-config --target running --config=/tmp/crash1.xml  --------> netopeer2-server crashes with following error from sysrepo:

netopeer2-server: /open_source/netconf/sysrepo/src/edit_diff.c:1730: sr_edit_diff_add: Assertion `op == EDIT_DELETE' failed.
Aborted (core dumped)

[cucp-yang-7.2.61.zip](https://github.com/sysrepo/sysrepo/files/10463688/cucp-yang-7.2.61.zip)

**Comment by michalvasko** [comment]
Failed to reproduce in the current version (latest release).
