### ISSUE TITLE
Does anyone get any idea on the feature "notification for verifier and validate"

### ISSUE THREAD

**Issue by qmm161** [sysrepo/sysrepo#299]
I need this feature: "(TODO) ability to subscribe to notifications as a verifier and validate the changes before they are committed" and it seems difficult to implement. Does anyone get an idea about how to start?

**Comment by rastislavszabo** [comment]
Hi,
it is a quite complex task that needs to be properly designed and coded. We planned to look at that in September. If you can wait a month (and possibly few extra weeks), wait until we do that.

If you want to contribute, I'd recommend to start with smaller tasks, e.g. with enhancements reported on GitHub.

P.S. [sysrepo-dev mailing list](http://lists.sysrepo.org/listinfo) is generally a better place for asking questions like these, more team members are reading it.

**Comment by rastislavszabo** [comment]
Hi,
the feature is now implemented in the devel branch, will be merged to master branch in the next few days.
