### ISSUE TITLE
Creating operational state data inside sr_module_change_subscribe

### ISSUE THREAD

**Issue by gauresh10** [sysrepo/sysrepo#2992]
Sysrepo version v2.0.41

I am using https://github.com/sysrepo/sysrepo/blob/v2.0.41/examples/application_changes_example.c for just examples.yang module.

My code snippet:

```
static int
module_change_cb(sr_session_ctx_t *session, uint32_t sub_id, const char *module_name, const char *xpath, sr_event_t event,
        uint32_t request_id, void *private_data)
{
    sr_change_iter_t *it = NULL;
    int rc = SR_ERR_OK;
    char path[512];
    sr_change_oper_t oper;
    sr_val_t *old_value = NULL;
    sr_val_t *new_value = NULL;

    (void)sub_id;
    (void)request_id;
    (void)private_data;

    if (event == SR_EV_CHANGE){
        struct lyd_node *ly_ntf = NULL;
        rc = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(session)),
                        "/examples:stats/counter", "87", 0, &ly_ntf);
        if (rc != LY_SUCCESS){
            MY_LOG_INFO(" #########   Not Applied! ");
        }
        MY_LOG_INFO(" #########   Applied! %ld ", rc);
    }

    // Do the rest of the print functions
 ... 
}
```

It returns `LY_SUCCESS`. But state data is not present in the operational/running store

On netopeer netconf client:
```
get-data --datasource operational
```
I have even tried `get` command but no luck

**Comment by michalvasko** [comment]
The code you provided is not setting any operational data. Also, you are using a year and a half old *sysrepo* version, it is time to update if you want our support.

**Comment by gauresh10** [comment]
Hi @michalvasko ,

Can you please help me with an example of how to set leaf/node which has `config false` above?

Thanks! I will update the sysrepo :)

**Comment by michalvasko** [comment]
The easiest is to use `sr_set_item_str()` followed by `sr_apply_changes()` but you must first switch the datastore of `session` to `SR_DS_OPERATIONAL`. I think you can do this in the module change callback but I am not positive.

**Comment by gauresh10** [comment]
Thanks @michalvasko, that worked :)
