### ISSUE TITLE
Getting error on make 

### ISSUE THREAD

**Issue by rajnkamr** [sysrepo/sysrepo#300]
My gcc version
gcc (GCC) 4.4.4 20100630 (Red Hat 4.4.4-10)

& g++ version is 
g++ (GCC) 4.4.4 20100630 (Red Hat 4.4.4-10)

I ma getting error on make as below:-
cc1: error: unrecognized command line option "-Wpedantic"
cc1: error: unrecognized command line option "-std=gnu11"

Any response is greatly appreciated

**Comment by rastislavszabo** [comment]
Hi,
try to change CMakeLists.txt as follows:

replace this:
```
set(CMAKE_C_FLAGS         "${CMAKE_C_FLAGS} -Wall -Wpedantic -std=gnu11")
```
with this:
```
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall -pedantic -std=gnu99")
```

**Comment by rajnkamr** [comment]
I tried to use as below
set(CMAKE_C_FLAGS         "${CMAKE_C_FLAGS} -Wall -pedantic -Dstd=gnu11 -std=gnu99")

it worked fine to get rid of above errors but i think due to gnu99 , other errors resurfaced

sysrepo/sysrepo/src/access_control.h:57: error: redefinition of typedef âac_ucred_tâ
sysrepo/sysrepo/src/notification_processor.h:27: note: previous declaration of âac_ucred_t

EFC-16.2-dev/3rdparty/sysrepo/sysrepo/src/common/sr_utils.c:36:
sysrepo/sysrepo/src/data_manager.h:59: error: redefinition of typedef âdm_data_info_tâ
sysrepo/sysrepo/src/common/sr_utils.h:38: note: previous declaration of âdm_data_info_tâ w

**Comment by rastislavszabo** [comment]
Try to remove  `-pedantic directive`

**Comment by rajnkamr** [comment]
removing pedantic does not help it gives same error

**Comment by rastislavszabo** [comment]
`set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall -std=gnu99")`

works without issues on my system (but with GCC 5). What for do you have `-Dstd=gnu11` there?

Your issue is that GCC 4.4. does not support gnu11 standard, but should support gnu99 which should be enough to build sysrepo.

If you'll be still seeing errors, I'd recommend you to install a little bit newer compiler.

**Comment by rajnkamr** [comment]
I Installed 4.8 and compilation seems to be happening until i got another error on cent os
Linking C static library libsysrepo-engine.a
[ 33%] Built target sysrepo-engine_a
Scanning dependencies of target sysrepo-plugind
[ 34%] Building C object src/CMakeFiles/sysrepo-plugind.dir/executables/sysrepo-plugind.c.o

**Comment by rajnkamr** [comment]
I Added -lrt to the end of g++it worked fine 
thanks
