### ISSUE TITLE
Which database is referenced by the path 'type leafref' in YANG model ?

### ISSUE THREAD

**Issue by rydy** [sysrepo/sysrepo#3001]
Hi, 

I have a qusetion about [`leafref`](https://www.rfc-editor.org/rfc/rfc6020.html#section-9.9), Which leaf of the database(running or operations) is referenced by the path 'type leafref' in YANG?

Best regards,
thanks.

**Comment by michalvasko** [comment]
It is all defined, the relevant sections are [-1-](https://www.rfc-editor.org/rfc/rfc7950.html#section-9.9.2), [-2-](https://www.rfc-editor.org/rfc/rfc7950.html#section-6.4.1), and [-3-](https://datatracker.ietf.org/doc/html/rfc8342#section-6.2).

**Comment by rydy** [comment]
> It is all defined, the relevant sections are [-1-](https://www.rfc-editor.org/rfc/rfc7950.html#section-9.9.2), [-2-](https://www.rfc-editor.org/rfc/rfc7950.html#section-6.4.1), and [-3-](https://datatracker.ietf.org/doc/html/rfc8342#section-6.2).

I got it, thanks.
