### ISSUE TITLE
Error/Warning logs seen on netopeer2-cli login

### ISSUE THREAD

**Issue by ChinmayaAgarwal** [sysrepo/sysrepo#3003]
Hi,

We are working on netopeer2 (0.7-r2) and sysrepo (0.7.9) and we see below error/warning logs whenever we login through netopeer2-cli:-

Feb  7 21:52:46 testdevmgmt sysrepod[1881]: [WRN] Unable to connect to subscriber socket=/var/run/sysrepo-subscriptions/ietf-netconf-notifications/1835.3Urx3W.sock:
Feb  7 21:52:46 testdevmgmt sysrepod[1881]: [ERR] Value with xpath /ietf-yang-library:yang-library/content-id received from provider doesn't correspond to any schema node
Feb  7 21:52:46 testdevmgmt sysrepod[1881]: [ERR] Data validation failed.
Feb  7 21:52:46 testdevmgmt sysrepod[1881]: [WRN] Error by processing of the message: Invalid argument.

Also, we have a custom yang model installed in sysrepo, for that we see below warning log continuously:-
[WRN] Unable to connect to subscriber socket=/var/run/sysrepo-subscriptions/hns-j3-devices/2260.eroMK3.sock:

What does these logs mean? Although we don't have any impact from functionality point of view but just wanted to understand the reason behind these logs.

Thanks and Regards,
Chinmaya Agarwal.

**Comment by michalvasko** [comment]
I cannot help you with this, you are using an ancient version of our software so some undesirable behavior is expected. We no longer support these versions.
