### ISSUE TITLE
How to debug subscription issue due to timeout / user rpc callback error

### ISSUE THREAD

**Issue by Krisscut** [sysrepo/sysrepo#3007]
Hi !

I'm still a newcomer when it comes to using netopeer along sysrepo, and I'm having a hard time solving an issue regarding a subscription to the "ietf-netconf-notifications" path, error log is as follow, and it happens after an edit-config is done through netopeer2-cli / edit-config.

![image](https://user-images.githubusercontent.com/8125922/218811743-21c2da80-ac13-4b6a-84d4-6e6fd89e49aa.png)

The references to the ID8 are as follow:
![image](https://user-images.githubusercontent.com/8125922/218812381-8b93bcc7-867d-4c08-994d-5d822bd70e92.png)
And for the ID 7 they are seen after the ID 8 mentions and are as follow:
![image](https://user-images.githubusercontent.com/8125922/218812677-f1ea68b7-a6ae-461c-8ddf-e25f087a66d6.png)

Regarding the error message reported on the first screenshot,  it looks like message ID 8 wasn't processed, because the message with 7 failed, right ? And because one callback didn't answer in time (timeout expired) or failed (user callback failed). But it is weird because the message ID 8 was before the 7 in the traces. 

How do you recommend investigating which user call back didn't answer in time or failed ? Is there a way to list the subscriptions by ID or name (it would be nice to have an option to register the callback with a specific name so that in the error log it reports it to help with the debugging).
In my traces I don't see any processing error during a callback so I'm not sure how to solve the issue.

**Comment by michalvasko** [comment]
> But it is weird because the message ID 8 was before the 7 in the traces.

Every subscription type (`rpc`, `notif`, ...) has its own ID counter.

I suppose you can add messages to be printed at various lines of the callback or directly use `gdb` and stop the process when it seems stuck to look at the stack trace. Not sure what else to suggest.

**Comment by Krisscut** [comment]
Oh yes good point !
But regarding the error message, should I focus on the user callback failed with "rpc" ID 7 or the others errors message regarding the "notif" ID 8.

Also, is there a way to know the list of current subscriptions ? Or a command to dump them ? Because it seems I have a dangling connection of some sort which cause the rpc 7 to fail.

Do you think it could be possible to add a name or some identifier during the subscription so that whenever that kind of error occurs it can help debugging by printing the subscription(s) which didn't answer or answered with an error (if applicable)

**Comment by Krisscut** [comment]
Thanks for the example command to retrieve sysrepo-monitoring !

> The actual problem is in a message you have not included in the output, the very first event fail. Also note that, depending on the actual scenario, the event should not remain unprocessed forever. At least no so in current sysrepo version, so update it if you are not using it.

Regarding this, no I don't see any error messages displayed in the traces prior to the errors displayed at the end.
But maybe there is something that is dangling or stuck without any error being seen.

I attached the full log but it is quite huge, and I can understand if you don't take a look since you must have other things to do as well ! (it includes the monitoring extract)
[extract_log.log](https://github.com/sysrepo/sysrepo/files/10744821/extract_log.log)

> Every subscription has a unique subscription ID, which is always passed to the callback. So I do not think anything else should be added.

Yes indeed, until know we never used it indeed. 
I just noticed that after the call to sr_module_change_subscribe, we should be able to find the sub_id in the last_sub_id of the subscription context, so I will try to log that as well.

Anyway, my idea would be to print that subscription ID in the error message, for instance at the moment it is something like:

[INF]: SR: Failed processing of "rpc" event with ID 10 priority 0 (remaining 1 subscribers).
It could be something like: 
[INF]: SR: Failed processing of "rpc" event with ID 10 priority 0 (remaining 1 subscribers, **[list of subscribers with sub ID, and even PID]]**).
--> [INF]: SR: Failed processing of "rpc" event with ID 10 priority 0 (remaining 1 subscribers, **[(SUB ID 63, PID 1425) ]**).

Same for the other instances of message where it says (Remaining x subscribers)

**Comment by michalvasko** [comment]
Looking at the log, starting at these lines
```
[INF]: SR: Published event "notif" "ietf-netconf-notifications" with ID 11 priority 0 for 3 subscribers.
orusw:INF/UE_APP-OAM/sysrepo, Processing "notif" "ietf-netconf-notifications" event with ID 11.
orusw:INF/UE_APP-OAM/sysrepo, Successful processing of "notif" event with ID 11 priority 0 (remaining 1 subscribers).
[INF]: SR: Processing "notif" "ietf-netconf-notifications" event with ID 11.
```
that last subscriber seems stuck because the next output mentioning notif event ID 11 is
```
[ERR]: SR: Waiting for subscription of "ietf-netconf-notifications" failed, previous event "notif" with ID 11 was not processed.
[ERR]: SR: Failed to generate netconf-config-change notification, but changes were applied.
```

**Comment by Krisscut** [comment]
I added a few prefix and timestamp to the traces, and enabled the debug mode of the message on netopeer2.
Looks like the app that is hanging is netopeer2 itself:

![image](https://user-images.githubusercontent.com/8125922/219322678-330332f0-1a34-4278-aa8d-c1981cf4374e.png)
[extract_log_prefix_netopeer_debug.log](https://github.com/sysrepo/sysrepo/files/10754187/extract_log_prefix_netopeer_debug.log)

But from what I understood, ietf-netconf-notifications is actually sent and processed when a change is detected in the datastores. 
Is it possible that this change triggered others changes that are hanging themselves 🤔

**Comment by michalvasko** [comment]
> Looks like the app that is hanging is netopeer2 itself:

*netopeer2* has no callback for `ietf-netconf-notifications` notifications so it must be your callback that is called and gets stuck.

> Is it possible that this change triggered others changes that are hanging themselves

Depending on what exactly is your callback doing, but it is definitely possible in general.

**Comment by Krisscut** [comment]
In our app we had 2 callback on it (hence the 3 subscribers on the log above), but on my latest run I removed them.

Before there was this in the monitoring: (cid 110 being our app, 109 the netopeer server)
![image](https://user-images.githubusercontent.com/8125922/219349621-7195090a-35e6-4d6c-88bc-384bac85c42c.png)
![image](https://user-images.githubusercontent.com/8125922/219350222-57ada55e-f270-4021-93ac-232a549ac790.png)
![image](https://user-images.githubusercontent.com/8125922/219350262-421da2b8-80df-4c98-bbae-be3836304797.png)

Then after the change to remove our subscriptions it becomes:
![image](https://user-images.githubusercontent.com/8125922/219350787-47323ab9-6cbe-44f1-ba24-95939cba83fe.png)
![image](https://user-images.githubusercontent.com/8125922/219350610-dd5f174e-ef43-41d9-9068-6fd80b41d2aa.png)
![image](https://user-images.githubusercontent.com/8125922/219350516-1c946b9c-0a93-481c-ba7c-762548fbd4d2.png)

That's why I though it was hanging in netopeer2 itself. (based on what I understand with the connection/sub handling).

**Comment by michalvasko** [comment]
Fair enough, in that case *netopeer2* must have created it based on a NETCONF client RPC such as `create-subscription` or `establish-subscription`. It does **not** have any notification subscriptions by default.

**Comment by Krisscut** [comment]
Thank you very much, you put me on the right track !

In our test framework, we had 2 netopeer2-cli session opened, one for sending the rpc, the other for the notifications.
The notification one used the command "subscribe" which I guess created the subscription we previously discussed.

I'm not quite sure why there wasn't any issue with the previous notification and on this one it became stuck, but I will investigate further on my side. Maybe the connection was broken at some point or something.
Anyway, without that notification session, I don't have the issue anymore, so at least the main cause is found now. ! 

Regarding that part, what do you think about it ? I think it could help with the debugging to have those information directly when errors are raised. Maybe along the Connection ID as well.

> Anyway, my idea would be to print that subscription ID in the error message, for instance at the moment it is something like:
>
> 
> [INF]: SR: Failed processing of "rpc" event with ID 10 priority 0 (remaining 1 subscribers).
> It could be something like:
> [INF]: SR: Failed processing of "rpc" event with ID 10 priority 0 (remaining 1 subscribers, [list of subscribers with sub ID, and even PID]]).
> --> [INF]: SR: Failed processing of "rpc" event with ID 10 priority 0 (remaining 1 subscribers, [(SUB ID 63, PID 1425) ]).
> 
> Same for the other instances of message where it says (Remaining x subscribers)

**Comment by michalvasko** [comment]
The messages are quite verbose as they are so we definitely will not be adding any more details. Note that they have been a bit improved in the current `devel` of sysrepo so you may want to try using that version. In any case, there is no reason whatsoever for a standard notification subscription via NETCONF to cause any problems.

**Comment by Krisscut** [comment]
Fair enough !
Thanks for the quick and efficient answers 😃

I will close the issue.
