### ISSUE TITLE
libyang error while installing yang modules

### ISSUE THREAD

**Issue by diljithka** [sysrepo/sysrepo#3010]
Getting the error while installing the yang modules.

- netopeer2 version 2.0.35
- libyang v2.0.112
- libnetconf2 v2.0.24
- sysrepo v2.0.53.
Error log is attached below. 

[ERR] Module "ietf-interfaces" not scheduled for deletion.
[ERR] Module "ietf-interfaces" is already in sysrepo.
[ERR] Module "ietf-ip" not scheduled for deletion.
[ERR] Module "ietf-ip" is already in sysrepo.
libyang error: Schema node "transport" for parent "/ietf-subscribed-notifications:subscriptions/subscription" not found; in expr "not(../transport" w.
libyang error: Schema node "transport" for parent "/ietf-subscribed-notifications:subscriptions/subscription" not found; in expr "not(../transport) o.
libyang error: Schema node "transport" for parent "/ietf-subscribed-notifications:subscription-modified" not found; in expr "not(../transport" with c.
libyang error: Schema node "transport" for parent "/ietf-subscribed-notifications:subscription-modified" not found; in expr "not(../transport) or der.
libyang error: Schema node "status" for parent "/o-ran-file-management:file-upload" not found; in expr "../status" with context node "/o-ran-file-man.
libyang error: Schema node "status" for parent "/o-ran-file-management:retrieve-file-list" not found; in expr "../status" with context node "/o-ran-f.
libyang error: Schema node "status" for parent "/o-ran-file-management:retrieve-file-list" not found; in expr "../status" with context node "/o-ran-f.
libyang error: Schema node "status" for parent "/o-ran-file-management:file-download" not found; in expr "../status" with context node "/o-ran-file-m.
libyang error: Schema node "status" for parent "/o-ran-software-management:software-download" not found; in expr "../status" with context node "/o-ra.
libyang error: Schema node "status" for parent "/o-ran-software-management:software-install" not found; in expr "../status" with context node "/o-ran.
libyang error: Schema node "status" for parent "/o-ran-software-management:software-activate" not found; in expr "../status" with context node "/o-ra.
libyang error: Schema node "status" for parent "/o-ran-trace:start-trace-logs" not found; in expr "../status" with context node "/o-ran-trace:start-t.
libyang error: Schema node "status" for parent "/o-ran-trace:stop-trace-logs" not found; in expr "../status" with context node "/o-ran-trace:stop-tra.
libyang error: Schema node "status" for parent "/o-ran-troubleshooting:start-troubleshooting-logs" not found; in expr "../status" with context node ".
libyang error: Schema node "status" for parent "/o-ran-troubleshooting:stop-troubleshooting-logs" not found; in expr "../status" with context node "/.

**Comment by michalvasko** [comment]
I suppose you will have to update your versions because these problems should be reported as warnings only.
