### ISSUE TITLE
enable yang feature failed with sysrepoctl

### ISSUE THREAD

**Issue by colindove** [sysrepo/sysrepo#3011]
Hi Team,
    i met a issue when i try to enable resync-subscription feature in yang module, Could u kindly help to check? Thanks a lot！

**Comment by colindove** [comment]
attach fail log and yang module

**Comment by colindove** [comment]
1

**Comment by colindove** [comment]
i don't know how to add attachment...

**Comment by michalvasko** [comment]
I do not understand what you are trying to do, there is no `resync-subscription` feature in `ietf-yang-push` YANG.

**Comment by colindove** [comment]
as u see in picture, i try to enable netopeer2 server but it failed and said "LY:Not found node resync-subscription"

**Comment by michalvasko** [comment]
You have cut the output, I have no idea what you are doing, in general. You asked about the not-found feature, I have explained why it was not found.

**Comment by colindove** [comment]
Thanks for the quick feedback...and yes, u're right, but i'm new man about this part, Could u kindly tell me which yang module i can use for resync-subscription feature?

**Comment by michalvasko** [comment]
I am not aware of any module with `resync-subscription` feature. There is only an RPC with this name in `ietf-yang-push`. You being new to YANG is okay but do not expect me to explain the basics to you. Start by reading and understanding the [RFC](https://www.rfc-editor.org/rfc/rfc7950.html).

**Comment by colindove** [comment]
Okay. thanks again.
