### ISSUE TITLE
Confirmed commit not reverted on timeout when datastores are locked

### ISSUE THREAD

**Issue by pfeige** [sysrepo/sysrepo#3014]
Hi Michal,

a confirmed commit is not reverted on timeout expiry when the datastores are locked.

Install the following YANG module via sysrepoctl:
~~~
module test-module {
  namespace "urn:test:module";
  prefix "tst-mod";

  container test-container {
    leaf test-string {
      type string;
    }
  }
}
~~~
Open a netconf session via netopeer2-cli:
~~~
> connect --login user
  ...
> lock --target running
OK
> edit-config --target running --config
  
  <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
      <test-container xmlns="urn:test:module">
          <test-string>RUNNING</test-string>
      </test-container>
  </config>
   
OK
> lock --target candidate
OK
> edit-config --target candidate --config
  
  <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
      <test-container xmlns="urn:test:module">
          <test-string>CANDIDATE</test-string>
      </test-container>
  </config>
   
OK
> get-config --source running
DATA
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  ...
  <test-container xmlns="urn:test:module">
      <test-string>RUNNING</test-string>
  </test-container>
</data>

> get-config --source candidate
DATA
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  ...
  <test-container xmlns="urn:test:module">
      <test-string>CANDIDATE</test-string>
  </test-container>
</data>

> commit --confirmed --confirm-timeout 1
> get-config --source running
DATA
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  ...
  <test-container xmlns="urn:test:module">
      <test-string>CANDIDATE</test-string>   ### should be reverted to RUNNING ###
  </test-container>
</data>

>
~~~
The following lines can be found in the netopeer2 log for all modules:
~~~
[INF]: NP: Rolling back module "test-confirmed-commit"...
[ERR]: SR: Module "test-confirmed-commit" is DS-locked by session 56.
[ERR]: NP: Failed restoring backup for module "test-confirmed-commit".
~~~
Can you have a look at this?

BR,
Peter

**Comment by pfeige** [comment]
After some code reading I guess I know why the reverting is not possible. The "external" lock/unlock uses the same mechanism as the "internal" module/data management. If a module is locked by a session it may be changed at any time (multithreaded). Ignoring this in case of reverting on timeout would/could in general lead to corrupt data stores. Am I right? If yes then please close the issue.

**Comment by michalvasko** [comment]
You are right, I think, but I am currently working on using the same SR session for the rollback so its locks are used and this use-case should then work. It just needs proper thread synchronization (rollback is async) so that is what I am implementing.

**Comment by michalvasko** [comment]
I started rewriting the code with that assumption, remains to be seen.

**Comment by michalvasko** [comment]
Seems to be working with a test passing, thanks for reporting all these use-cases.

**Comment by pfeige** [comment]
Yes, it works!
Great, thanks a lot!
