### ISSUE TITLE
How to identify end of startupDB read?

### ISSUE THREAD

**Issue by rakichinni** [sysrepo/sysrepo#3015]
Hi,
As part of the system bring-up, sysrepo reads persisted configurations from StartupDB and currently, no end of StartupDB read is sent to subscribers. We want to know in case if there is any procedure to notify the end of StartupDB to subscribed applications.

Asking this because we want to take some action on the config data from StartupDB that is loaded.

Thanks

**Comment by michalvasko** [comment]
> sysrepo reads persisted configurations from StartupDB

Are you talking about your subscriptions getting notified when `startup` is being copied to `running`? If so, then they will normally get 2 events, `SR_EV_CHANGE` and `SR_EV_DONE`. You can perform all the actions needed on the former event and then do "some action" on the latter event when all the changes have already been applied.
