### ISSUE TITLE
Commit timed out when candidate DS is locked by another session

### ISSUE THREAD

**Issue by pfeige** [sysrepo/sysrepo#3017]
Hi Michal,

when a session A locks the candidate DS and changes some data there and a session B tries to commit this a timeout occurs. According to RFC-6241:8.3.4.1 the commit should be rejected.

Install the following YANG module via sysrepoctl:
~~~
module test-module {
  namespace "urn:test:module";
  prefix "tst-mod";

  container test-container {
    leaf test-string {
      type string;
    }
  }
}
~~~
Open a first netconf session A via netopeer2-cli:
~~~
> connect --login user
  ...
> lock --target candidate
OK
> edit-config --target candidate --config
  
  <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
      <test-container xmlns="urn:test:module">
          <test-string>whatever</test-string>
      </test-container>
  </config>
   
OK
>
~~~
In a separate shell open a second parallel netconf session B via netopeer2-cli:
~~~
> connect --login user
  ...
> commit
cli_send_recv: Timeout for receiving a reply expired.   ### expected error reply ###
>
~~~
Can you have a look at this?

BR,
Peter

**Comment by michalvasko** [comment]
Fixed with a test.

**Comment by pfeige** [comment]
OK, thanks!
