### ISSUE TITLE
sysrepo rwlock policy to prioritize the writers?

### ISSUE THREAD

**Issue by barbarost** [sysrepo/sysrepo#3018]
Hi,

It looks like the rwlock implementation in sysrepo prioritizes readers (maybe due to the assumption that read operations will be much more in count compared to the write operations) however this causes a writer to be always timed out if there is a reader acquired the lock and then new readers come in and acquire the lock. I wonder if you do have a plan to change the rwlock policy to prioritize writers instead of readers?

**Comment by michalvasko** [comment]
What *sysrepo* are you using? Fairly recently a WRITE URGE lock was added, which has the highest priority. However, it is not used everywhere because that would cause other issues. If you have a specific use-case that  starves the writer, describe it.

**Comment by barbarost** [comment]
Thanks Michal, I will try again with the latest version.
