### ISSUE TITLE
XPath "node()" doesn't work for another augmented modules

### ISSUE THREAD

**Issue by pkun** [sysrepo/sysrepo#3023]
Hello.

I have two lists (on the same level) with the leaf "name" in each. I need this "name" to be unique among  two lists. The "must" statement is used to implement this.

d.yang:

```
module d {
  yang-version "1";
  prefix "d";
  namespace "ddd";

  grouping d-common {
    leaf name {
      must 'not(/d:cont/node()[name=current()][2])';
      type string;
    }
  }

  container cont {
    list a {
      key "name";
      uses d-common;
    }
    list b {
      key "name";
      uses d-common;
    }
  }
}
```

When I add entries with the same name to "a" and "b" list and then check configuration, I get the following message:

libyang[0]: Must condition "not(/d:cont/node()[name=current()][2])" not satisfied. (path: Data location "/d:cont/a[name='name1']/name".)

It's the right behaviour.

Then I move lists to different modules and augment them to central module.

c.yang (central module):

```
module c {
  yang-version "1";
  prefix "c";
  namespace "ccc";

  grouping c-common {
    leaf name {
      must 'not(/c:cont2/node()[name=current()][2])';
      type string;
    }
  }

  container cont2 {
  }
}
```

a.yang:

```
module a {
  yang-version "1";
  namespace "aaa";
  prefix "a";

  import c { prefix c; }

  augment "/c:cont2" {
    list a {
      key "name";
      uses c:c-common;
    }
  }
}
```

The b.yang file is the same as a.yang but declares "b" module and "b" list.

Now "must" statement is not working. I can add entry to "a" and "b" with the same name.

I have tried many variants of XPath and find out that "node()" (or "*") can find specified name only within its own module. It doesn't see nodes from another augmented module.

If I execute sysrepocfg this the similar XPath I see the following:

```
$ sysrepocfg -X -d candidate -x "/c:cont2/node()[name='name1'][2]"
<cont2 xmlns="ccc">
  <b xmlns="bbb">
    <name>name1</name>
  </b>
</cont2>
```

So the XPath works with sysrepocfg but not works for "must" statement.

**Comment by michalvasko** [comment]
I do not know how exactly did you test in the second case because if you create 2 instances of `a` with the same `name`, you do not have unique keys anymore and the validation fails on that. I have added the second list into `a` just like you have in the first example, then tested with some data and it worked as expected.
```yang
module c {
  yang-version "1";
  prefix "c";
  namespace "ccc";

  grouping c-common {
    leaf name {
      must 'not(/c:cont2/node()[name=current()][2])';
      type string;
    }
  }

  container cont2 {
  }
}
```
```yang
module a {
  yang-version "1";
  namespace "aaa";
  prefix "a";

  import c { prefix c; }

  augment "/c:cont2" {
    list a {
      key "name";
      uses c:c-common;
    }
    list b {
      key "name";
      uses c:c-common;
    }
  }
}
```
```xml
<cont2 xmlns="ccc">
    <a xmlns="aaa">
        <name>name</name>
    </a>
    <b xmlns="aaa">
        <name>name</name>
    </b>
</cont2>
```
```
> yanglint a.yang data.xml 
libyang err : Must condition "not(/c:cont2/node()[name=current()][2])" not satisfied. (Data location "/c:cont2/a:a[name='name']/name".)
libyang err : Must condition "not(/c:cont2/node()[name=current()][2])" not satisfied. (Data location "/c:cont2/a:b[name='name']/name".)
YANGLINT[E]: Failed to parse input data file "data.xml".
```
Note that I have used the current `devel` branch of *libyang* so if you are using some old version it may not work properly.

**Comment by pkun** [comment]
The "a" and "b" lists are in different modules.

```
module a {
  yang-version "1";
  namespace "aaa";
  prefix "a";

  import c { prefix c; }

  augment "/c:cont2" {
    list a {
      key "name";
      uses c:c-common;
    }
  }
}
```

```
module b {

  yang-version "1";
  namespace "bbb";
  prefix "b";

  import c { prefix c; }

  augment "/c:cont2" {
    list b {
      key "name";
      uses c:c-common;
    }
  }
}
```

**Comment by michalvasko** [comment]
Right, then it behaves as you described but it is correct even though it took me a moment to figure out. Try using
```
must 'not(/c:cont2/node()[node()[local-name()="name"]=current()][2])';
```
(as an example, the condition can probably be much simpler) instead. The problem is with the unqualified `name` identifier, which according to [specs](https://www.rfc-editor.org/rfc/rfc7950.html#section-6.4.1) (second bullet), translates to `c:name`. But since you only have lists with `a:name` and `b:name`, it does not match either.

**Comment by pkun** [comment]
Thanks a lot!
