### ISSUE TITLE
Is there any option to set the rollback-order? 

### ISSUE THREAD

**Issue by MoshikaKarthesan** [sysrepo/sysrepo#3026]
Is there any option to set the rollback-order?  What is the default order (oper order) in sysrepo?

**Comment by michalvasko** [comment]
What order are you talking about? If you mean rollback after some `SR_EV_CHANGE` event fails, `SR_EV_ABORT` event is generated for all the previous callbacks called, in the same order. Relative order of callbacks within a module can be set and also the order of modules in case the commit includes the changes of several modules.
