### ISSUE TITLE
missing leaves in running configuration if date changes before configuring

### ISSUE THREAD

**Issue by samuel-gauthier** [sysrepo/sysrepo#3029]
Hi,

I have updated our sysrepo version to v2.2.60. Since I did, our internal NTP test is not working anymore.
Basically, this test puts a date in the past (something like date --set "2000-03-22"), configures a NTP client via netconf, and verifies that the date is updated.

The callbacks for those leaves are called and the system is configured properly.
But when we ask for the running configuration via netconf (using netopeer2-cli), the leaves we configured after changing the date are absent. But those leaves are here if we ask for the running configuration via sysrepocfg.

The commit responsible for this behavior seems to be this one: https://github.com/sysrepo/sysrepo/commit/d3e31cc0f 

Do you have any idea of what might happen?

**Comment by michalvasko** [comment]
Yes, I suppose it makes sense. The change I made is that `last_modif` datastore callback is used for checking cached data validity. In the default plugin, it is the modified time of the file, which is a `CLOCK_REALTIME` timestamp. Meaning if there is an NTP change moving the time back and then some data are stored, these will be considered older than what is cached and hence the cache will not be updated. That is definitely a critical problem so please try this patch to see whether it fixes the issue.
```patch
diff --git a/src/common.c b/src/common.c
index 232808dd..deaaaea1 100644
--- a/src/common.c
+++ b/src/common.c
@@ -3196,9 +3196,9 @@ sr_conn_run_cache_update(sr_conn_ctx_t *conn, const struct sr_mod_info_s *mod_in
         }
 
         /* check whether the data are current */
-        if (sr_time_cmp(&cmod->ts, &mtime) >= 0) {
+        if (!sr_time_cmp(&cmod->ts, &mtime)) {
             continue;
-        }
+        } /* older mtime can only mean an NTP change followed by data change */
 
         if (has_lock != SR_LOCK_WRITE) {
             /* CACHE READ UNLOCK */
```

**Comment by samuel-gauthier** [comment]
Yes, this patch fixes the problem.

**Comment by michalvasko** [comment]
Fine, committed.

**Comment by samuel-gauthier** [comment]
Thanks!
