### ISSUE TITLE
Installing many modules is too slow

### ISSUE THREAD

**Issue by Maksymiv96** [sysrepo/sysrepo#3030]
hi, 
with the latest sysrepo version we've facing one issue, maybe you can have some suggestion.
when we upgrading sysrepo version from time to time we facing Invalid LYB format version "0x03", expected "0x04 error. 
as recommended in other ticket, to proceed with it , usually we clean all the data and shm folder , then proceed with installation and importing data back.
usually it works fine.
but with the latest sysrepo version after removing shr folder, each operation to install next model (sysrepoctl -i/-l) takes too much time. all our models (~60) are installed in 40minutes. could it be related somehow to factory_default feature? 

btw, if upgrading from sysrepo 2.0.53 we also get next error
[ERR] JSON DS file: Invalid character sequence "lyb", expected a JSON value.
[ERR] Loading "sysrepo" data failed.
sysrepoctl error: Failed to connect (libyang error)
can you give some advice how should we proceed ?

**Comment by Maksymiv96** [comment]
with grouping all the parameters into one command we managed to reduce installation time to 7min. 
thanks for support.

**Comment by Maksymiv96** [comment]
not one, but was tried to group it as much as can. for example some models are already present , so all features for specific module was enabled with separated command.

> But it is possible if those modules are huge.
ORAN modules

**Comment by michalvasko** [comment]
Yes, if you need to change features of existing modules, you can do so only one-by-one.
