### ISSUE TITLE
Error during module and subtree subscription methods

### ISSUE THREAD

**Issue by ChinmayaAgarwal** [sysrepo/sysrepo#3031]
Hi,

I am trying to subscribe to sysrepo data tree using my application. I am using two methods for that i.e "sr_module_change_subscribe" and "sr_subtree_change_subscribe". But when I reboot my machine and run the application for the first time, "sr_module_change_subscribe" methods throws error "The item already exists" and "sr_subtree_change_subscribe" throws error "The operation failed". Also, when I restart my application, I don't see these errors anymore and everything works fine.

What could be the reason for this kind of a behaviour?

Thanks and Regards,
Chinmaya Agarwal.

**Comment by michalvasko** [comment]
Um, what is `sr_subtree_change_subscribe`? You are using *sysrepo* version 0.7.9? In that case I am not able to help, it is way past the time you should have updated it.
