### ISSUE TITLE
Unable to remove item from the leaf-list in operational datastore

### ISSUE THREAD

**Issue by mblacksee** [sysrepo/sysrepo#3035]
Hi Michal,
I'm not able to remove an item from a leaf-list in the operational datastore with `sr_delete_item` API. In order to reproduce the case, I've prepared a dirty patch attached.
[0001-Debug-leaf-list-remove-w-predicate.txt](https://github.com/sysrepo/sysrepo/files/11096046/0001-Debug-leaf-list-remove-w-predicate.txt)
As a result of this patch, output is as below;
```
[ RUN      ] test_oper_ll                                                                                                                                           
DATA: {"test:ll9":[25,26,27]}                                                     
DATA: {"test:ll9":[25,26,27]}                                                     
742.997796 [351793][139695866649344][INF]: No datastore changes to apply.         
742.998012 [351793][139695866649344][INF]: No datastore changes to apply.         
[       OK ] test_oper_ll
```
I expected that item `[.=26]` would be removed from the leaf-list.

Revisions;
libyang: 2.1.61
sysrepo: 2.2.66

BR.

**Comment by michalvasko** [comment]
Someone always gets this wrong no matter what I do so I have at least added a reference to the correct function you should have used. Also, these are state leaf-lists you are working with so the value does not uniquely identify an instance (there can be duplicate values), you should use positional predicate instead.
