### ISSUE TITLE
sr_set_item_str function and sr_module_change_subscribe function

### ISSUE THREAD

**Issue by hi-Mr-ye** [sysrepo/sysrepo#3036]
Hi Michal:
the sr_module_change_subscribe function:
![image](https://user-images.githubusercontent.com/90752673/229268720-eb431e5f-9eec-403b-a9db-c7f5fd683ed6.png)
When I use the sr_set_item_str function, Why are callback(coh_config) functions executed?
![image](https://user-images.githubusercontent.com/90752673/229269032-a167de21-bbe1-419f-8e3c-4be9a32caa5c.png)

**Comment by jktjkt** [comment]
I'm confused by the question because that's the whole point of "module changed" callbacks -- to be notified when someone performs a change. What behavior do you expect here?

**Comment by hi-Mr-ye** [comment]
Is it possible to execute the sr_set_item_str function without firing the callback function?

**Comment by michalvasko** [comment]
No, that would defeat the whole *sysrepo* mechanism.
