### ISSUE TITLE
writing data in o-ran-software-management

### ISSUE THREAD

**Issue by vancouversun** [sysrepo/sysrepo#3037]
Hello,
I am trying to write some data in o-ran-software-management for the test purpose.
I have checked that o-ran-software-management is installed using sysrepoctl -l.

FIrst :
I was trying to write it in netopeer2-cli using edit-conig. But it is not writable.
I think it's because of "config false".

Second :
So I coded it like below. But it returned "libyang[0]: Unexpected data state node "software-inventory" found. (path: Data location "/o-ran-software-management:software-inventory".)".
```C
#define NAME_TEST test
status_value.type = SR_ENUM_T;
status_value.data.enum_val = "EMPTY";

    rc = sr_set_item(m_srRunSession, "/o-ran-software-management:software-inventory/software-slot[name='" NAME_TEST "']/status", &status_value, SR_EDIT_DEFAULT);
    if (rc != SR_ERR_OK) {
         sr_strerror(rc);
    }
    rc = sr_apply_changes(m_srRunSession, 0);
    if (rc != SR_ERR_OK) {
         sr_strerror(rc);
    }
    rc = sr_get_item(m_srRunSession, "/o-ran-software-management:software-inventory/software-slot[name='" NAME_TEST"']/status", 0, &get_slot_1_value);
    if (rc != SR_ERR_OK) {
         sr_strerror(rc);;
    }
```
Last :
I have called ly_ctx_load_module API.
I coded it like below. There is no error. But data is not saved.
```C
    struct ly_ctx *ctx = NULL;
    const struct lys_module *mod;
    struct lyd_node *root = NULL;
    struct lyd_node *node = NULL;
	
    err = ly_ctx_new("/.../sysrepo-2.2.12/build/repository/yang/", 0, &ctx);
    if (err != LY_SUCCESS) {
        sr_strerror(err);
    }

    mod = ly_ctx_load_module(ctx, "o-ran-software-management", "2019-07-03", NULL);
    if (mod == NULL) {
        sr_strerror(err);
    }

    err = lyd_new_inner(NULL, mod, "software-inventory", 0, &root);
    if (err != LY_SUCCESS) {
        sr_strerror(err);
    }

    err = lyd_new_list(root, NULL, "software-slot", 0, &node); 
    if (err != LY_SUCCESS) {
        sr_strerror(err);
    }

    err = lyd_new_term(node, NULL, "name", "test-1", 0, NULL);
    if (err != LY_SUCCESS) {
        sr_strerror(err);
    }

    err = lyd_new_term(node, NULL, "name", "test-2", 0, NULL);
    if (err != LY_SUCCESS) {
        sr_strerror(err);
    }
```
Is there an API to save it?
I attached o-ran-software-management.yang.
[o-ran-software-management.zip](https://github.com/sysrepo/sysrepo/files/11153873/o-ran-software-management.zip)

**Comment by michalvasko** [comment]
Read the [docs](https://netopeer.liberouter.org/doc/sysrepo/master/html/index.html#oper_data) to learn more about *operational* data, which `config false` data are.

**Comment by vancouversun** [comment]
Thanks for the answer.
I can modify the data in operational datastore. 
Is there any way that this config false data is transferred from operational to running datastore?

**Comment by jktjkt** [comment]
There cannot ever be any `config: false` data in the `running` datastore; this is all explained in [RFC 8342](https://datatracker.ietf.org/doc/html/rfc8342).

**Comment by vancouversun** [comment]
Thanks for the answer again.
I see. But I have still a question. 
Who and How can write config false data at the very first time?

**Comment by jktjkt** [comment]
I suggest to familiarize yourself with the relevant RFCs and sysrepo's documentation; that should get you going in the right direction.

**Comment by vancouversun** [comment]
Thanks.
