### ISSUE TITLE
Unable to trigger notification 

### ISSUE THREAD

**Issue by SudarkodiSundaramoorthy** [sysrepo/sysrepo#3039]
Hi @michalvasko , I am unable to trigger notification in libsysrepo v2.2.36 (SO v7.13.13) and finding the below logs,

[ERR] Invalid datastore edit.
[ERR] Callback event "operational get" with ID 1 processing timed out.
[WRN] Event "operational get" with ID 1 failed (Timeout expired).
[ERR] User callback failed.

Please find the notification needs to be triggered below, 
```
notifications:
+---n tx-array-carriers-state-change
|   +--ro tx-array-carriers* [name]
|     +--ro name -> /user-plane-configuration/tx-array-carriers/name
|     +--ro state? -> /user-plane-configuration/tx-array-carriers/state
+---n rx-array-carriers-state-change
  +--ro rx-array-carriers* [name]
      +--ro name -> /user-plane-configuration/rx-array-carriers/name
      +--ro state? -> /user-plane-configuration/rx-array-carriers/state
```   
Here the state is the RO parameter and name is the RW parameter. I am unable to fetch state(RO) parameter.

**Comment by michalvasko** [comment]
Those are all the errors you got? There is obviously some problem in your application but it is impossible to determine what.
