### ISSUE TITLE
event resource path changed in notify and create-subscription

### ISSUE THREAD

**Issue by bozhiz** [sysrepo/sysrepo#3040]
When application report event, it fill the resouce as xpath(module name included), but when receive create-subscription, the resouce is reported as path, yang module prefix included.

application report event in netconf message

```
<?xml version="1.0" encoding="UTF-8"?>
<notification xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
   <eventTime>2023-04-06T11:59:20.089824695-04:00</eventTime>
   <alarm-notification xmlns="urn:ietf:params:xml:ns:yang:ietf-alarms">
      <resource>/ietf-interfaces:interfaces/interface[name='uplink-4']</resource>
      <alarm-type-id xmlns:bbf-communication-alt="urn:bbf:yang:bbf-communication-alarm-types">bbf-communication-alt:loss-of-signal</alarm-type-id>
      <alarm-type-qualifier />
      <time>2023-04-06T15:43:40Z</time>
      <perceived-severity>major</perceived-severity>
      <alarm-text>Interface uplink-4 is DOWN</alarm-text>
   </alarm-notification>
</notification>
```

The cached files in /tmp/ietf-alarms.notif.1680810220-1680810220:
```
{"ietf-alarms:alarm-notification":{"resource":"/ietf-interfaces:interfaces/interface[name='uplink-4']","alarm-type-id":"bbf-communication-alarm-types:loss-of-signal","alarm-type-qualifier":"","time":"2023-04-06T15:43:40Z","perceived-severity":"major","alarm-text":"Interface uplink-4 is DOWN"}}
```

When receive create-subscription, netopeer2 will replay events, the notification in netconf message is like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<notification xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
   <eventTime>2023-04-06T12:01:53.132929019-04:00</eventTime>
   <alarm-notification xmlns="urn:ietf:params:xml:ns:yang:ietf-alarms">
      <resource xmlns:if="urn:ietf:params:xml:ns:yang:ietf-interfaces">/if:interfaces/if:interface[if:name='uplink-4']</resource>
      <alarm-type-id xmlns:bbf-communication-alt="urn:bbf:yang:bbf-communication-alarm-types">bbf-communication-alt:loss-of-signal</alarm-type-id>
      <alarm-type-qualifier />
      <time>2023-04-06T15:43:40Z</time>
      <perceived-severity>major</perceived-severity>
      <alarm-text>Interface uplink-4 is DOWN</alarm-text>
   </alarm-notification>
</notification>
```

I found the <resource> value in two messages are different, why are they different?
One workaround is fill the <resource> as "/if:interfaces/if:interface[if:name='uplink-4']", the <resource> in two messages are the same

libyang: 2.1.30
sysrepo: 2.2.36
libnetconf2: 2.1.28
netopeer2: 2.1.49

**Comment by michalvasko** [comment]
Interesting use-case, the type of `resource` is a rather complex one
```yang
    type union {
      type instance-identifier {
        require-instance false;
      }
      type yang:object-identifier;
      type string;
      type yang:uuid;
    }
```
and I would argue incorrect one because it can never be of type `uuid`, every value will match `string` if it did not match the types before. But that should not cause the behavior you observed, which seems to be due to the matching type changes. Initially it is probably stored as `string` but when being replayed, it is interpreted as an `instance-identifier`.

This behavior is not ideal but correct if the node `/ietf-interfaces:interfaces/interface[name='uplink-4']` does not exist originally and is created before the notification is replayed. If the data are not changed then the value should not change either. If you provide this information, I will try to reproduce it and fix it if there is anything to fix.

**Comment by bozhiz** [comment]
I just check how to create the notification lyn_node in the code, it set the options to LYD_NEW_PATH_CANON_VALUE in lyd_new_path().

If I set the option to 0, then <resource> in notify/replay two messages are identical, like
```
<resource xmlns:if="urn:ietf:params:xml:ns:yang:ietf-interfaces">/if:interfaces/if:interface[if:name='uplink-4']</resource>
```

**Comment by michalvasko** [comment]
You were using the option? You were definitely not supposed to be using it. But your problem is solved then.
