### ISSUE TITLE
get-config with filter return empty data, use API sr_get_data 

### ISSUE THREAD

**Issue by ttlily** [sysrepo/sysrepo#3042]
hi,
I'm not able to get the config true data with sr_get_data API.

When I use the cmd "get-config --source running --filter-xpath /_common-managed:test/attributes", can get the attributes data, but **when use cmd "get-config --source running --filter-xpath /_common-managed:test/HW", get  empty data.** 

I track the API sr_get_data , when the xpath is "/_common-managed:test/attributes",  mod_info name in the API is  "ManagedElement", the set->count is "1", but when the xpath is "/_common-managed:test/HW", mod_info name is the same,
but set->count is "0".

so,   I guess the difference between these two is “HW” has the key "id". 
but the parent node "test" also has the key, use cmd "get-config --source running --filter-xpath /_common-managed:test" can get the completed data.

so, **The above issue with the API sr_get_data ,  how can I modify the cmd to get the data?**

**Here's the input data :** 
```xml
<test xmlns="urn:sa5:_common-managed">
 <id>1</id>
 <attributes>
    <act></act>
  </attributes>
  <HW xmlns="urn:ran:ns:yang:hw">
    <id>1</id>
    <HWTOP>
    </HWTOP>
  </HW>
```

**Comment by michalvasko** [comment]
From your data it is obvious the `HW` node has a different namespace than `test`. Just use `/_common-managed:test/o-ran-hardware:HW` (or whatever the augment module name is) and you should get the data.

**Comment by billykinggym** [comment]
@michalvasko , for get we can get the data, but get-config can't .   the reason is that get operation will retrieve all data ,and filter in netopeer2-server. but get-config, is filter by sysrepo.  in sysrepo there is nacm check, but in netopeer2-server there is no such nacm check. i mean at aleast , filter in sysrepo and filter in netopeer2-server is not equivalence fron nacm perspective.

**Comment by michalvasko** [comment]
> for get we can get the data, but get-config can't

That is not what @ttlily described so please do not mix issues.

> the reason is that get operation will retrieve all data ,and filter in netopeer2-server. but get-config, is filter by sysrepo

That is no longer true since several *netopeer2* releases so just update it.

> in sysrepo there is nacm check, but in netopeer2-server there is no such nacm check

That is not true and I do not really understand what exactly you mean. In any case, it is most likely not relevant.
