### ISSUE TITLE
Sysrepo not able to detect that subscribing application is not running

### ISSUE THREAD

**Issue by ChinmayaAgarwal** [sysrepo/sysrepo#3045]
Hi,

In sysrepo we have observed that when the subscribing application goes down and then execute edit-config, sysrepo is not returning failure for the edit-config and writes it in running data tree. This use to work for us earlier and give the error that "The node is not enabled in running data tree". One difference that we have observed is earlier we were having module level subscription but now we have changed it to subtree level subscription. Could this be the reason for this issue? If not, then what could be the reason for this behaviour?

Thanks and Regards,
Chinmaya Agarwal.

**Comment by michalvasko** [comment]
> what could be the reason for this behaviour?

It has simply been changed in *sysrepo* v2, you can now write `running` configuration data even if there are no subscribers for them.
