### ISSUE TITLE
time format

### ISSUE THREAD

**Issue by hi-Mr-ye** [sysrepo/sysrepo#3050]
Hi
I encountered a strange phenomenon:
I run the user-rpc command, and xml file:
![image](https://user-images.githubusercontent.com/90752673/233835527-4894ced6-a317-40e3-a2f0-ced9011edd43.png)
I print in the callback function
![image](https://user-images.githubusercontent.com/90752673/233835560-1abb64f0-0b59-4006-93c2-b52e077e031f.png)
The other case:
Modifying xml files:
![image](https://user-images.githubusercontent.com/90752673/233835618-c2fd7daa-5283-4228-a931-ae3c4c1c7905.png)
Print the callback function
![image](https://user-images.githubusercontent.com/90752673/233835654-28662f47-c29a-4054-9df3-71fd37c708ab.png)
why?
system time:
![image](https://user-images.githubusercontent.com/90752673/233835700-246be933-c706-4378-a723-2e96dbb95d07.png)
netopeer2-server version:
![image](https://user-images.githubusercontent.com/90752673/233835747-6ff63477-2395-46e1-8974-c72ab036d588.png)
My computer time:
![image](https://user-images.githubusercontent.com/90752673/233835856-cb7540cd-a827-44e2-9983-eb8b471bcb5d.png)

**Comment by michalvasko** [comment]
What *libyang* version are you using? There were some changes and you should be using at least 2.1.62 (SO 2.34.4). Also, what type are nodes `start-time` and `end-time`?

**Comment by hi-Mr-ye** [comment]
How to view the libyang version？
![image](https://user-images.githubusercontent.com/90752673/233951118-925cea0c-cebe-4351-9aa2-a25fcb13b513.png)
![image](https://user-images.githubusercontent.com/90752673/233951365-e4c04e83-9aa1-480c-a1cf-24675c4407a0.png)

**Comment by michalvasko** [comment]
`yanglint -v` should suffice.

**Comment by hi-Mr-ye** [comment]
libyang version:
![image](https://user-images.githubusercontent.com/90752673/233954000-0b9ed0cd-1e2a-4b7f-98a7-33dea6e21f2c.png)

**Comment by michalvasko** [comment]
Okay, I have discovered the problem but I am unsure what is the solution. Using timestamp `2023-02-23T10:28:29.52+12:00` and you currently using NZST, which would you expect to see
1. `2023-02-23T10:28:29.52+12:00` because you are in NZST;
2. `2023-02-23T11:28:29.52+13:00` because at the timestamp you would be at NZDT?

Currently, *libyang* mixes these 2. I am also going to ask on the NETMOD mailing list.

**Comment by michalvasko** [comment]
Try the latest *libyang* `devel`, it should now behave consistently and according to 2.

**Comment by hi-Mr-ye** [comment]
> which would you expect to see



> which would you expect to see
I expect the first one.



> Try the latest _libyang_ `devel`

Okay, I‘ll try.

**Comment by hi-Mr-ye** [comment]
Hi
The libyang I use is devel. 
What is the latest version of libyang?

> 2\. `2023-02-23T11:28:29.52+13:00` because at the timestamp you would be at NZDT?
no, The NZST I using all the time

**Comment by hi-Mr-ye** [comment]
Hi @michalvasko
I updated the libyang version to 2.1.73.
but I run the user-rpc command, and xml file:
![image](https://user-images.githubusercontent.com/90752673/234200822-3692bccd-a93a-4269-be6b-771b19eef9d8.png)
Time received:
![image](https://user-images.githubusercontent.com/90752673/234201098-84b742c1-0cfa-4429-b47e-79ef2343fa7b.png)
but My system time and time zone:

![image](https://user-images.githubusercontent.com/90752673/234201231-39b6c2a0-6b09-4a84-b394-9f68b6868284.png)
why not "2023-02-23T10:28:29.52+12:00" "2023-02-23T11:44:29.52+12:00"?

**Comment by michalvasko** [comment]
Discussed in the [netmod mailing list](https://mailarchive.ietf.org/arch/msg/netmod/vP_cVVKkWSHJpUwZbDnm_jc0O5k/) and the conclusion was that this is the correct behavior.

**Comment by hi-Mr-ye** [comment]
Thanks!
but But I still don't understand when start-time nodal value is 2023-04-23T10:28:29.52+12:00, The result of the print is 2023-04-23T10:28:29.52+12:00

**Comment by michalvasko** [comment]
I was hoping I have explained it in my reply 2 days ago and it should also be clear from the mailing list, but the point is that you see `2023-04-23T10:28:29.52+12:00` because **at the moment** of the timestamp your system was in the timezone +12:00. You see `2023-02-23T11:28:29.52+13:00` because **at the moment** of the timestamp your system was in the timezone +13:00 (daylight saving).

**Comment by hi-Mr-ye** [comment]
I understand. Thank you very much for your answer.
