### ISSUE TITLE
Query: How to retain a single callback design for operational data if no filtering list key options is specified.

### ISSUE THREAD

**Issue by RashmiEva** [sysrepo/sysrepo#3053]
Hi,

I see that in latest versions of Sysrepo(example: libsysrepo-v2.2.12), with GET RPC invocation, operational callbacks are called recursively with leaf name value for the list to fetch the state data from the registered subscribers.

Example : 
1) get with filter option /interfaces/interface/mactable/state
2) get with filter option /interfaces/interface[name='intf1']/mactable/state

Registered operational callback for the xpath: "/interfaces/interface/mactable/state"

For option(1),  callbacks will be invoked multiple times depending on the number of interface list instances in the running datastore.
For option(2),  callbacks will be invoked once with list key value.

Since earlier Sysrepo version has a single callbacks mechanism for option(1), 
I would like to know if any options are available in current Sysrepo version, to choose whether we can get recursive callbacks OR just a single callbacks w.r.t option(1).

Thanks
Eva

**Comment by michalvasko** [comment]
You cannot choose explicitly any behavior, it depends on the subscribed path. In case there are nodes with many instances allowed (lists), the callback will be called for each instance. If you want to provide all the instances in a single callback call, just subscribe to the list parent. (`/interface` in this case, I think).

**Comment by RashmiEva** [comment]
What happens incase of nested lists or containers presence and we register a operational callback for the xpath "/interfaces"?

Considering below Xpath yang definitions,
1) /interfaces/interface/ifcounters(list)/state
2) /interfaces/interface/mactable(container)/state
3) /interfaces/interface/ingressinfo(list)/state

GET options:
1) get filter-xpath=/interfaces/interface/mactable
2) get filter-xpath=/interfaces/interface[name='intf1']/ingressinfo/state

Would you please confirm what would happen in above cases? is it that we will be getting a single callbacks in both the options? Also, incase of option(2) will we get key value as part of callbacks so that we can update only a particular interface data instead of all the data.?

Thanks 
Eva

**Comment by michalvasko** [comment]
You have 2 options, either register oper get callback for a parent container (you are then supposed to provide all the nested data) and then it will always be called only once but without any nested nodes (list instances). Or subscribe to a descendant of a list and then the callback will be called for every existing list instance but you will have access to the list instance key values.
