### ISSUE TITLE
Callback "load" of plugin "LYB DS file" for module "xxxx-interfaces" failed.

### ISSUE THREAD

**Issue by MoshikaKarthesan** [sysrepo/sysrepo#3054]
I'm getting this error while doing a get-config after pushing a payload of 750 interface configs(including ethernet and vlan) via netopeer-cli. 

Errors observed in server:
LYB DS file: Invalid Interface name pattern
Callback "load" of plugin "LYB DS file" for module "xxxx-interfaces" failed.
Getting data "/*" from sysrepo failed (libyang error).

Is this any existing issue or is there any fix for this?

Library versions used:

libyang version v2.1.4
libsysrepo version v2.2.12
libssh version v0.9.0
Libnetconf2 version v2.1.25
netopeer2 version v2.1.42

**Comment by michalvasko** [comment]
I do not understand the error message and I have never seen it before. So my advice is to update the whole stack, there were 2 more new releases and I think it will fix your problem, the LYB format is no longer used.
