### ISSUE TITLE
Sending notif with sr_notif_send_tree fails on 5th notif.

### ISSUE THREAD

**Issue by mblacksee** [sysrepo/sysrepo#3055]
Hi Michal,
In case of sending notif repeatedly, `sr_notif_send_tree` API complains on the 5th retry.  `Replay` for the corresponding module was enabled. One of the daemons that each one has its own sysrepo connection/session (`sr_session_notif_buffer` API is called on the sender) sends notifications and another daemon (which is started little bit later than the daemon which sends notifs) which subscribes to this notif for processing them. 

Error message is as below;
[ERR] Waiting for subscription of "module-name" failed, previous event "notif" ID 4 was not processed.
sr_notif_send_tree failed as Timeout expired.

What might be the problem?

Versions;
libyang: 2.1.64
sysrepo: 2.2.66

Thankls in advance.
BR.

**Comment by michalvasko** [comment]
I would have to see the INF output of all the applications but the error says only that whatever daemon(s) is subscriber to the notification is stuck in the callback processing the 4th notification, I cannot tell you the reason.

**Comment by barbarost** [comment]
Hi Michal,
In case of there is a notification callback is running (even the notification is sent asynchronously) and a new notification is sent during that time this timeout problem occurs on the sender. In case to overcome to problem what would you suggest? Enabling the replay feature for the module and use `sr_session_notif_buffer`?
