### ISSUE TITLE
How to get the value of an element from a nested key-less list?

### ISSUE THREAD

**Issue by ecerci-atilim** [sysrepo/sysrepo#3056]
Hi,

I am working on acquiring changed data. I have a working program that creates a key-less list instance on operational datastore, and this change is followed by calling a callback function. In the function, I am iterating through all the changes in the list (with `sr_get_changes_iter()` and `sr_get_change_tree_next()`) to get the name-value pairs to be printed. I am assigning the value with `lyd_get_value(node)`, and the name with `node->schema->name`. At every iteration, I am replacing a temporary node with the current node's `next` member. Everything was working fine until I hit a nested key-less list element inside the main list.

Here is the structure of the list:

```
  +--ro active-alarm-list
  |  +--ro active-alarms* []
  |     +--ro fault-id                   uint16
  |     +--ro fault-source               string
  |     +--ro affected-objects* []
  |     |  +--ro name          string
  |     |  +--ro identifier?   yang:xpath1.0
  |     +--ro fault-severity             enumeration
  |     +--ro is-cleared                 boolean
  |     +--ro fault-text?                string
  |     +--ro probable-cause?            string
  |     +--ro specific-problem?          string
  |     +--ro proposed-repair-actions?   string
  |     +--ro event-time                 yang:date-and-time
  |     +--ro additional-information* [identifier]
  |     |  +--ro identifier     string
  |     |  +--ro information?   string
  |     +--ro alarm-type?                enumeration

```

When I try to get the value I previously assigned to `name` in the `affected-objects` list inside the parent `active-alarms`, `node->schema->name` returns to an empty string.

Is there any way to get the value of `.../active-alarm-list/active-alarms[#]/affected-objects[#]/name` for this case? I am also open to changing what I have already done.

Thanks in advance.

**Comment by michalvasko** [comment]
I do not understand what you are trying to do, could you maybe post a code snippet?

**Comment by michalvasko** [comment]
Yes, if you want to iterate only through all the changed `/o-ran-fm:active-alarm-list/active-alarms/affected-objects/name`, you can call
```C
rc = sr_get_changes_iter(session, "/o-ran-fm:active-alarm-list/active-alarms/affected-objects/name", &iter);
```
If you want to iterate over all the changes, you should be using
```C
rc = sr_get_changes_iter(session, "/o-ran-fm:active-alarm-list/active-alarms//*", &iter);
```

**Comment by ecerci-atilim** [comment]
Thank you, Michal!
