### ISSUE TITLE
sysrepoctl: '-l' option not working out of the box anymore

### ISSUE THREAD

**Issue by Wexiwa** [sysrepo/sysrepo#3058]
Hi,

I upgraded my _sysrepo_ version from v**2.1.84** to v**2.2.60** (alongside _libyang_ from v**2.0.23**1 to v**2.1.55**).

After that, I tried running a fresh install of my modules, but it appears that the command `sysrepoctl -l` has new prerequisites, as I get the following error:

```
[ERR] Module "yang" was not found in sysrepo.
sysrepoctl error: Failed to list modules (Item not found)
[INF] No datastore changes to apply.
```

My installation process is inspired by the one shipped with [_netopeer2_ v**2.1.59**](https://github.com/CESNET/netopeer2/blob/v2.1.59/scripts/setup.sh#L95), which calls the same command prior to installing its modules.

Supplying the `--search-dirs` option does not change the outcome.

AFAIK this error did not happen with the previous version, is this an unexpected side effect/regression from recent changes ?

**Comment by michalvasko** [comment]
Not sure what exactly is the problem but the version is difference is fairly large so I suppose there could have been some changes incompatible with the previous version. The safest fix is to run `make sr_clean`, which will completely reset all the installed YANG modules and remove all their data but after that everything should work normally again.

**Comment by Wexiwa** [comment]
Hi michalvasko,

I cleaned the _shm_  and the _datastore_ files, then I got the following errors:

```
[ERR] JSON DS file: File "/etc/sysrepo/data/yang.factory-default" already exists.
[ERR] Callback "install" of plugin "JSON DS file" for module "yang" failed.
sysrepoctl error: Failed to connect (Item already exists)
For more details you may try to increase the verbosity up to "-v3".
```

After removing the file, I got


However I got some different error messages depending on

**Comment by Wexiwa** [comment]
Yes, that's kinda what I mean, as I do not have the `Makefile` on my system where _sysrepo_ is deployed, I manually execute the `rm` commands from the `make sr_clean` custom target, i.e.:

```
rm -rf ${SHM_DIR}/sr_*
rm -rf ${SHM_DIR}/srsub_*
rm -rf ${REPO_PATH}
```

Usually, I do not install the `yang` module, as it is preinstalled by the first _libyang_ / _sysrepo_ context I presume ? 
it was just a test to try resolve the issue as one of the error message seemed to indicate that it wasn't installed.

**Comment by michalvasko** [comment]
> it is preinstalled by the first libyang / sysrepo context I presume ?

Yes, it is an internal module that is always installed. When I tested locally, I could normally "install" `yang` meaning it succeeded (even repeatedly) but did no changes to *sysrepo*. Seems I have added an exception for this and installing internal modules is silently accepted.

**Comment by Wexiwa** [comment]
I ran into another `segfault` error, when trying to install a module after I got `sysrepoctl -l` to work properly.

After investigating and trying to clean everything again, I noticed that they were remaining artifacts from previous attempts in the `factory-default` data directory, thus I cleaned everything there, i.e.: 

```
rm ${FACTORY_DEFAULT_DATA_PATH}/*.factory-default
```

After that, no more `segfault` error and the module installation was successful.

**Comment by michalvasko** [comment]
Yes, if you used a separate path for factory-default files, you need to reset that, too. Sorry for the problems but it is not always possible to keep full compatibility between all the updates.

**Comment by Wexiwa** [comment]
No problem, I know upgrading versions doesn't usually go smoothly.

Maybe this needs a small patch to the `sr_clean` target to explicitly clean the `${FACTORY_DEFAULT_DATA_PATH}` path, thus everything is properly cleaned if this was explicitly set during configuration.
