### ISSUE TITLE
sr_shmsub_listen_thread exits due to internal error in sr_shmsub_notif_listen_process_module_events

### ISSUE THREAD

**Issue by barbarost** [sysrepo/sysrepo#3060]
Hi Michal,
If I have a notification callback running for a notification and the same notification is sent during time, `sr_shmsub_listen_thread` exits with an internal error in `sr_shmsub_notif_listen_process_module_events` for following check:
```
    /* no error/timeout should be possible */
    if ((ATOMIC_LOAD_RELAXED(multi_sub_shm->event) != SR_SUB_EV_NOTIF) ||
            (ATOMIC_LOAD_RELAXED(multi_sub_shm->request_id) != ATOMIC_LOAD_RELAXED(notif_subs->request_id))) {
        SR_ERRINFO_INT(&err_info);
        goto cleanup_wrunlock;
    }
```
Basically `notif_subs->request_id` has the request ID for the notification callback already running and `multi_sub_shm->request_id` has the request ID for the new notification to be sent (which times out).

**Comment by michalvasko** [comment]
Could you please provide *sysrepo* output with log level 3? That should make it obvious what is happening and maybe even allow me to reproduce it.
