### ISSUE TITLE
Operational and running data store

### ISSUE THREAD

**Issue by alexeimerk** [sysrepo/sysrepo#3068]
Hello Michael,
I've been using sysrrepo for a few years and now I'm going to change version 0.7.8 to 2.2.60. I'm using the examples from the package and trying to get the regular data (config true) from the operationa data store. I modified the YANG example file a bit and added two false configuration options:
```yang
container cont {
        leaf l {
            type string;
        }
        leaf my_counter {
            type uint64;
            config false;
        }
        leaf my_str {
            type string;
            config false;
        }
    }
```
Next, I updated function from examples for subscribe new parameters:
```C
   if (!strcmp(module_name, "examples") && !strcmp(xpath, "/examples:cont")) {
        ly_ctx = sr_acquire_context(sr_session_get_connection(session));
        lyd_new_path(NULL, ly_ctx, "/examples:cont/my_counter", "987", 0, parent);
        lyd_new_path(*parent, NULL, "/examples:cont/my_str", "IWork", 0, NULL);
        sr_release_context(sr_session_get_connection(session));
    }
```
After that, I run the examples as described in the documentation:
```
> ./application_changes_example examples&
> ./sr_set_item_example /examples:cont/l secondTest
> ./oper_data_pull_example examples /examples:cont&
> ./oper_data_pull_example examples /examples:stats&
> ./sr_get_items_example /examples:*//. operational
```
My result is:
```
Application will get "/examples:*//." from "operational" datastore.
========== DATA FOR "examples" "/examples:cont" REQUESTED =======================
========== DATA FOR "examples" "/examples:stats" REQUESTED =======================
/examples:cont (container)
/examples:cont/my_counter = 987
/examples:cont/my_str = IWork
/examples:stats (container)
/examples:stats/counter = 852
/examples:stats/counter2 = 1052
```
Now the question: 
I don't see inside the response the **leaf "l"** which contains the string "secondTest" . What should I write in the query to get ALL  parameters together, from the operational data store. Please help me, it is very important for our project

**Comment by michalvasko** [comment]
The oper get subscription 
```
> ./oper_data_pull_example examples /examples:cont&
```
overwrites any previous data unless the `SR_SUBSCR_OPER_MERGE` flag is used for the subscription.

**Comment by alexeimerk** [comment]
Thank you a lot! It's work!
