### ISSUE TITLE
<intended> datastore support (or alternatives)

### ISSUE THREAD

**Issue by avazquezrd** [sysrepo/sysrepo#3071]
I would like to know if there is support for the **intended** datastore defined [here](https://datatracker.ietf.org/doc/html/rfc8342#section-5.1.4), as I have not found any information about it. I understand that this datastore has the same data as the **running** datastore, plus changes that has not yet been applied. This is useful when the plugin needs the new context when data is being processed, as changes do not exist in running datastore at that moment.

Until now, I have been retrieving these changes from data available in [sr_module_change_cb](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__change__subs__api.html#gae5634bf3204fc6ac2f7b7564546e3129), and I have merged them with data available in running datastore, building something similar to that intended datastore. However, when I receive changes from different modules in one RPC via NETCONF, changes are processed separatedly, generating one change event per module. And, in this case, I cannot access intended changes from other modules, which may be needed by the plugin.

Here is a simple example. Let's assume my plugin is subscribed to changes in `ietf-interfaces` module and during user callback it needs access to a leaf from the ietf-hardware module that has been defined in same RPC, as shown here:

```xml
<nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"
        xmlns:ds="urn:ietf:params:xml:ns:yang:ietf-datastores"
        xmlns:ncds="urn:ietf:params:xml:ns:yang:ietf-netconf-nmda"
        message-id="1">
  <ncds:edit-data>
    <ncds:datastore>ds:running</ncds:datastore>
    <ncds:config>
      <if:interfaces nc:operation="merge"
                     xmlns:if="urn:ietf:params:xml:ns:yang:ietf-interfaces"
                     xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type"
                     xmlns:bbf-hw="urn:bbf:yang:bbf-hardware">
        <if:interface>
          <if:name>uplink1</if:name>
          <if:type>ianaift:ethernetCsmacd</if:type>
          <bbf-hw:hardware-component>
            <bbf-hw:port-layer-if>eth1</bbf-hw:port-layer-if>
          </bbf-hw:hardware-component>
        </if:interface>
      </if:interfaces>
      <hw:hardware nc:operation="merge"
                   xmlns:hw="urn:ietf:params:xml:ns:yang:ietf-hardware"
                   xmlns:ianahw="urn:ietf:params:xml:ns:yang:iana-hardware">
        <hw:component>
          <hw:name>eth1</hw:name>
          <hw:class>ianahw:port</hw:class>
          <hw:parent>switch-name</hw:parent>
          <hw:parent-rel-pos>1</hw:parent-rel-pos>
        </hw:component>
      </hw:hardware>
    </ncds:config>
  </ncds:edit-data>
</nc:rpc>
```

The `bbf-hw:port-layer-if` leafref points to the `eth1` component we need to access (e.g., to retrieve the parent defined there), but when `ietf-interfaces` changes are being processed, this leaf does not yet exist in `ietf-hardware` module and we cannot retrieve it from changes list (as it belongs to a different module).

**Is there a way to access all changes from all modules that has not yet been applied to Sysrepo (during user callback)?**

**Comment by michalvasko** [comment]
I am not sure this is any way related to the `intended` datastore, there is no support for templates or anything like that in *sysrepo*. As for the problem itself, what makes you think you cannot access changes for other modules? I remembered correctly and the whole diff should actually be available to all the callbacks meaning if you retrieve any data (using `sr_get_data()`, for example) in the callback, they should have all the changes from the diff applied.

**Comment by avazquezrd** [comment]
Maybe it is related to the **sysrepo-python** bindings I am using, but the API directly provides a _changes_ list and there I only see changes from the module that has triggered the event (callback definition [here](https://github.com/sysrepo/sysrepo-python/blob/ab825a95ea59da41bdb4ab64b25737d4cb3efe39/sysrepo/session.py#L251)).

I have also tested it with two subscriptions (one per module), and I can see that I receive two different events, each one with a _changes_ list for data in each module.

**Comment by michalvasko** [comment]
Well, yes, if you are looking for **changes** of the other modules, it will be connected to the bindings in case they provide them themselves. However, you asked about **data** and that should work even with the bindings meaning you should get data with all the changes form the commit being applied. But you should not be needing the changes, you are in a callback for another module so I understand the reasoning for hiding a part of the C API and providing all the changes directly.

**Comment by michalvasko** [comment]
1. Okay, I really do not know how the bindings are designed but I am quite sure you can get data somehow, it does not matter how exactly. And I thought I was clear but these data will include changes from all the modules (from the whole commit).
2. Like I said, I can understand needing some related data from other modules but not sure why you would need them in the form of changes.
