### ISSUE TITLE
why sysrepo add default parameter when edit-config with <default-operation> is 'none' 

### ISSUE THREAD

**Issue by ttlily** [sysrepo/sysrepo#3075]
hi, 
I have a question about why sysrepo add default parameter when edit-config with <default-operation> is 'none'
**step 1:**  the data I got before edit-config operation is as follows:
```
<ManagedElement xmlns="urn:3gpp:sa5:_3gpp-common-managed-element">
  <id>MRBTS-6</id>
  <MNL xmlns="urn:ran:ns:yang:bts-mnl">
    <id>1</id>
    <attributes>
      <actNcYgMPlane>false</actNcYgMPlane>
    </attributes>
</ManagedElement>
```

**step 2:** do edit-config operation with rpc request cmd :  
edit-config --target running  --test test-then-set **--defop none** --config=test.xml, 
the node'actPassivePartSync' is not exist  in the target datastore, it is the optional default parameter in yang level.
data in test.xml is :
```
<ManagedElement xmlns="urn:3gpp:sa5:_3gpp-common-managed-element">
  <id>MRBTS-6</id>
  <MNL xmlns="urn:ran:ns:yang:bts-mnl">
    <id>1</id>
    <attributes>
      <actPassivePartSync>true</actPassivePartSync>
    </attributes>
    <CMD xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="delete">
      <id>1</id>
    </CMD>
  </MNL>
</ManagedElement>
```

**step 3:** I got the data as follows:
```
<ManagedElement xmlns="urn:3gpp:sa5:_3gpp-common-managed-element">
  <id>MRBTS-6</id>
  <MNL xmlns="urn:ran:ns:yang:bts-mnl">
    <id>1</id>
    <attributes>
      <actNcYgMPlane>false</actNcYgMPlane>
      <actPassivePartSync>false</actPassivePartSync>
    </attributes>
</ManagedElement>
```

**my question**:: the node 'attributes' is without sub-operation, the default-operation is 'none', so why add `<actPassivePartSync>false</actPassivePartSync>`

In rfc6241:
 none:  The target datastore is unaffected by the configuration in the 'config' parameter, unless and until the incoming 
 configuration data uses the "operation" attribute to request a different operation.  If the configuration in the 'config'
parameter contains data for which there is not a corresponding level in the target datastore, an 'rpc-error' is returned with an 'error-tag' value of data-missing. Using "none" allows operations like "delete" to avoid unintentionally creating the parent hierarchy of the element to be deleted.

My understanding of this paragraph：  for example,  if  input  A/B with A/C, the node of B sub-operation is "delete", node C  is exist in target datastore. if without "none", will create or update node C.  if with "none", only will delete node B,

**Comment by michalvasko** [comment]
You are right, the `none` operation was not expected on nodes without descendants so it was misinterpreted. Try the latest *sysrepo* `devel`, it should work there.

**Comment by ttlily** [comment]
@michalvasko , thank you for your reply,  I found it has undergone significant changes compared to the master,  so if I use the latest sysrepo devel, I need update the netopeer2 and libnetconf2 at the same time? need checkout to devel, too?

**Comment by michalvasko** [comment]
It is always best to use all the projects from the same branch but there should also be increased dependency versions in each project so you should fail to compile a project in case it requires some newer dependency.
