### ISSUE TITLE
pull method with "Nested operation 'commit' data parent does not exist in the operational datastore" error

### ISSUE THREAD

**Issue by simonwa1** [sysrepo/sysrepo#3078]
Hi,

At first, push method (sr_set_item_str() and sr_apply_changes()) is used to create the operational data. The rpc actions "download", "activate" and "commit" are OK.

Later, the pull method (lyd_new_path()) is used to create the operation data. The rpc action "download" is OK. However, the actions "activate" and "commit" are not OK. The error is "Nested operation "commit" data parent does not exist in the operational datastore."

The operational data is same format in both push and pull:

```html
> get-data --datastore operational --filter-xpath /ietf-hardware:hardware/component[name='onu-1/2/1/1/8']
DATA
<data xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-nmda">
  <hardware xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware">
    <component>
      <name>onu-1/2/1/1/8</name>
      <class xmlns:bbf-hwt="urn:bbf:yang:bbf-hardware-types">bbf-hwt:xpon-nt</class>
      <software xmlns="urn:bbf:yang:bbf-software-management">
        <software>
          <name>image</name>
          <capability xmlns:bbf-swm="urn:bbf:yang:bbf-software-management">bbf-swm:download-target-selection-by-system</capability>
          <capability xmlns:bbf-swm="urn:bbf:yang:bbf-software-management">bbf-swm:validate</capability>
          <capability xmlns:bbf-swm="urn:bbf:yang:bbf-software-management">bbf-swm:activate</capability>
          <capability xmlns:bbf-swm="urn:bbf:yang:bbf-software-management">bbf-swm:commit</capability>
          <revisions>
            <maximum-number-of-revisions>2</maximum-number-of-revisions>
            <revision>
              <id>0</id>
              <state>available</state>
              <last-changed>2023-06-12T02:05:50+00:00</last-changed>
              <version>V202204B239</version>
              <product-code/>
              <hash/>
              <is-valid>true</is-valid>
              <is-active>false</is-active>
              <is-committed>false</is-committed>
              <activate>
                <last-activated>2023-06-12T02:05:50+00:00</last-activated>
              </activate>
              <commit>
                <last-committed>2023-06-12T02:05:50+00:00</last-committed>
              </commit>
            </revision>
            <revision>
              <id>1</id>
              <state>in-use</state>
              <last-changed>2023-06-12T02:05:50+00:00</last-changed>
              <version>V202204B228</version>
              <product-code/>
              <hash/>
              <is-valid>true</is-valid>
              <is-active>true</is-active>
              <is-committed>true</is-committed>
              <activate>
                <last-activated>2023-06-12T02:05:50+00:00</last-activated>
              </activate>
              <commit>
                <last-committed>2023-06-12T02:05:50+00:00</last-committed>
              </commit>
            </revision>
          </revisions>
        </software>
      </software>
    </component>
  </hardware>
</data>
``` 

The rpc-request and rpc-reply in pull method are:
```html
<rpc mod-id="218" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="2">
	<action xmlns="urn:ietf:params:xml:ns:yang:1">
		<hw:hardware xmlns:hw="urn:ietf:params:xml:ns:yang:ietf-hardware">
			<hw:component>
				<hw:name>onu-1/2/1/1/8</hw:name>
				<bbf-swm:software xmlns:bbf-swm="urn:bbf:yang:bbf-software-management">
					<bbf-swm:software>
						<bbf-swm:name>image</bbf-swm:name>
						<bbf-swm:revisions>
							<bbf-swm:revision>
								<bbf-swm:id>1</bbf-swm:id>
								<bbf-swm:commit>
									<bbf-swm:commit/>
								</bbf-swm:commit>
							</bbf-swm:revision>
						</bbf-swm:revisions>
					</bbf-swm:software>
				</bbf-swm:software>
			</hw:component>
		</hw:hardware>
	</action>
</rpc>

<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" mod-id="218" message-id="2">
	<rpc-error>
		<error-type>application</error-type>
		<error-tag>operation-failed</error-tag>
		<error-severity>error</error-severity>
		<error-message xml:lang="en">Nested operation "commit" data parent does not exist in the operational datastore.</error-message>
	</rpc-error>
</rpc-reply>
``` 

If test with same rpc-request in push method, the rpc-reply is OK.

The question is: whether the rpc action can work with pull method? From [sysrepo document](https://netopeer.liberouter.org/doc/sysrepo/master/html/subs.html#oper_subs), the RPC/action also invoke [pull operational get data](https://netopeer.liberouter.org/doc/sysrepo/master/html/index.html#oper_data).

Following version are used:
- sysrepo "2.2.73"
- libyang "2.1.80"

Thanks.

SimonWa

**Comment by michalvasko** [comment]
It does make any difference what method you choose as long as the `operational` datastore includes the parent data. But why is there
```xml
              <activate>
                <last-activated>2023-06-12T02:05:50+00:00</last-activated>
              </activate>
              <commit>
                <last-committed>2023-06-12T02:05:50+00:00</last-committed>
              </commit>
```
if those are supposed to be actions? Those themselves are not part of any datastore.

**Comment by simonwa1** [comment]
In [bbf-software-management.yang](https://github.com/BroadbandForum/yang/blob/master/standard/equipment/bbf-software-management.yang), the "activate" and "commit" are container. Besides the action themselves, the containers also include the "last-activated" and "last-committed".

In push method, I do not use these two containers. Due to the leaves are optional in them.
In pull method, I do not use these two containers at first, too. During testing, there is "Nested operation 'commit' data parent does not exist in the operational datastore" error. So I added these two containers to operational datastore with fake time string. However, the error still exists.

**Comment by michalvasko** [comment]
I have tested it and successfully executed the action. To populate `operational` datastore I have simply take the data you provided and set them as the push oper data. Note that it should be fine to simply create the required containers without any descendants, operational data are fine with that. And do not forget to check the data in the operational datastore before executing the action.

**Comment by simonwa1** [comment]
The root cause is clear.

In my pull method callback function, only the request xpath "/ietf-hardware:hardware/component[name='onu-1/2/1/1/8']" is handled. If it is this one, the callback function will assemble the rpc-reply by lyd_new_path().

However, the commit rpc with request xpath "/ietf-hardware:hardware/component[name='onu-1/2/1/1/8']/bbf-software-management:software/software[name='image']/revisions/revision[id='0']/commit". The callback function will ignore this xpath.

After assembling the rpc-reply for "/ietf-hardware:hardware/component[name='onu-1/2/1/1/8']/bbf-software-management:software/software[name='image']/revisions/revision[id='0']/commit", the rpc action can be successfully executed.
