### ISSUE TITLE
How to change the NACM factory default?

### ISSUE THREAD

**Issue by troglobit** [sysrepo/sysrepo#3079]
Hi, this is a repost of CESNET/netopeer2#1417

I've been trying to change the factory default datastore for ietf-netconf-acm in sysrepo, but no matter what I try, I get "already loaded" or similar, and the init data is ignored.  All other models I've tried loading with `sysrepoctl` seem to get initialized properly.  Any pointers on how to do it?

The reason I'm even attempting this is that we want to set up a basic set of default groups in the system (guest/admin/limited, as defined in RFC8341) which the ietf-system default 'admin' user is member of.  So that on factory reset the system always returns to this defined state.  (The password is random per-device and scanned by the site admin so that they can manage devices remotely using NETCONF after a factory reset).

**Comment by troglobit** [comment]
I started playing around a bit to see if I could make something like this to work:

```bash
$ sysrepoctl -c ietf-netconf-acm -I data.json
```

Having no idea what I'm doing, I ended up with the following, which doesn't work.  But I'm curious if I'm on the right track, or if there are huge roadblocks or hidden traps further ahead ... :smile: 

```diff
diff --git a/src/executables/sysrepoctl.c b/src/executables/sysrepoctl.c
index 62dbdf7e..3441fb53 100644
--- a/src/executables/sysrepoctl.c
+++ b/src/executables/sysrepoctl.c
@@ -514,7 +514,7 @@ cleanup:
 }
 
 static int
-srctl_change(sr_conn_ctx_t *conn, struct change_item *citem)
+srctl_change(sr_conn_ctx_t *conn, struct change_item *citem, const char *data_path)
 {
     int r = 0, i;
 
@@ -528,6 +528,18 @@ srctl_change(sr_conn_ctx_t *conn, struct change_item *citem)
         citem->module_name = NULL;
     }
 
+    if (data_path) {
+        if (!citem->module_name) {
+            error_print(0, "Unsupported, can only update initial data by module name.");
+            goto cleanup;
+        }
+        if (r = sr_update_module_data(conn, citem->module_name, data_path)) {
+            error_print(r, "Failed updating \"%s\" with initial data from \"%s\"",
+                        citem->module_name, data_path);
+            goto cleanup;
+        }
+    }
+
     /* change owner, group, and/or permissions */
     if (citem->owner || citem->group || citem->perms) {
         if (citem->mod_ds == SR_MOD_DS_PLUGIN_COUNT) {
@@ -843,7 +855,7 @@ main(int argc, char **argv)
             break;
         case 'I':
             /* init-data */
-            if (operation == 'i') {
+            if (operation == 'i' || operation == 'c') {
                 data_path = optarg;
             } else {
                 error_operation(operation, opt);
@@ -926,7 +938,7 @@ main(int argc, char **argv)
         break;
     case 'c':
         /* change */
-        if ((r = srctl_change(conn, &citem))) {
+        if ((r = srctl_change(conn, &citem, data_path))) {
             goto cleanup;
         }
         break;
diff --git a/src/sysrepo.c b/src/sysrepo.c
index 2c0d61fd..87e23eb6 100644
--- a/src/sysrepo.c
+++ b/src/sysrepo.c
@@ -2400,14 +2400,15 @@ cleanup:
  * @return err_info, NULL on success.
  */
 static sr_error_info_t *
-sr_change_module_feature(sr_conn_ctx_t *conn, const char *module_name, const char *feature_name, int enable)
+sr_change_module_feature(sr_conn_ctx_t *conn, const char *module_name, const char *feature_name,
+       const char *data_path, int enable)
 {
     sr_error_info_t *err_info = NULL;
     struct ly_ctx *new_ctx = NULL, *old_ctx = NULL;
     struct ly_set mod_set = {0};
-    struct lyd_node *sr_mods = NULL;
+    struct lyd_node *mod_data = NULL, *sr_mods = NULL;
     struct sr_data_update_s data_info = {0};
-    const struct lys_module *ly_mod, *upd_ly_mod;
+    const struct lys_module *ly_mod, *upd_ly_mod = NULL;
     LY_ERR lyrc;
     sr_lock_mode_t ctx_mode = SR_LOCK_NONE;
 
@@ -2429,20 +2430,26 @@ sr_change_module_feature(sr_conn_ctx_t *conn, const char *module_name, const cha
         goto cleanup;
     }
 
-    /* check feature in the current context */
-    lyrc = lys_feature_value(ly_mod, feature_name);
-    if (lyrc == LY_ENOTFOUND) {
-        sr_errinfo_new(&err_info, SR_ERR_NOT_FOUND, "Feature \"%s\" was not found in module \"%s\".",
-                feature_name, module_name);
-        goto cleanup;
-    } else if ((lyrc == LY_SUCCESS) && enable) {
-        sr_errinfo_new(&err_info, SR_ERR_EXISTS, "Feature \"%s\" is already enabled in module \"%s\".",
-                feature_name, module_name);
-        goto cleanup;
-    } else if ((lyrc == LY_ENOT) && !enable) {
-        sr_errinfo_new(&err_info, SR_ERR_EXISTS, "Feature \"%s\" is already disabled in module \"%s\".",
-                feature_name, module_name);
-        goto cleanup;
+    if (feature_name) {
+        /* check feature in the current context */
+        lyrc = lys_feature_value(ly_mod, feature_name);
+        if (lyrc == LY_ENOTFOUND) {
+            sr_errinfo_new(&err_info, SR_ERR_NOT_FOUND, "Feature \"%s\" was not found in module \"%s\".",
+                           feature_name, module_name);
+            goto cleanup;
+        } else if ((lyrc == LY_SUCCESS) && enable) {
+            sr_errinfo_new(&err_info, SR_ERR_EXISTS, "Feature \"%s\" is already enabled in module \"%s\".",
+                           feature_name, module_name);
+            goto cleanup;
+        } else if ((lyrc == LY_ENOT) && !enable) {
+            sr_errinfo_new(&err_info, SR_ERR_EXISTS, "Feature \"%s\" is already disabled in module \"%s\".",
+                           feature_name, module_name);
+            goto cleanup;
+        }
+    } else {
+        if (!data_path) {
+            goto cleanup;
+        }
     }
 
     /* create new temporary context */
@@ -2459,16 +2466,23 @@ sr_change_module_feature(sr_conn_ctx_t *conn, const char *module_name, const cha
         goto cleanup;
     }
 
-    /* load the module with changed features */
-    if ((err_info = sr_load_module(new_ctx, ly_mod, feature_name, enable, &upd_ly_mod))) {
-        goto cleanup;
+    if (feature_name) {
+        /* load the module with changed features */
+        if ((err_info = sr_load_module(new_ctx, ly_mod, feature_name, enable, &upd_ly_mod))) {
+            goto cleanup;
+        }
+        /* check the new context can be used */
+        if ((err_info = sr_lycc_check_chng_feature(conn, new_ctx))) {
+            goto cleanup;
+        }
+    } else {
+        /* parse modules data, if any */
+        if ((err_info = sr_lyd_parse_module_data(new_ctx, NULL, data_path, 0, &mod_data))) {
+            goto cleanup;
+        }
     }
 
-    /* check the new context can be used */
-    if ((err_info = sr_lycc_check_chng_feature(conn, new_ctx))) {
-        goto cleanup;
-    }
-    if ((err_info = sr_lycc_update_data(conn, new_ctx, NULL, &data_info))) {
+    if ((err_info = sr_lycc_update_data(conn, new_ctx, mod_data, &data_info))) {
         goto cleanup;
     }
 
@@ -2479,8 +2493,14 @@ sr_change_module_feature(sr_conn_ctx_t *conn, const char *module_name, const cha
     ctx_mode = SR_LOCK_WRITE;
 
     /* update lydmods data */
-    if ((err_info = sr_lydmods_change_chng_feature(conn->ly_ctx, ly_mod, upd_ly_mod, feature_name, enable, &sr_mods))) {
-        goto cleanup;
+    if (feature_name) {
+        if ((err_info = sr_lydmods_change_chng_feature(conn->ly_ctx, ly_mod, upd_ly_mod, feature_name, enable, &sr_mods))) {
+            goto cleanup;
+        }
+    } else {
+        if ((err_info = sr_lydmods_change_upd_modules(conn->ly_ctx, &mod_set, &sr_mods))) {
+            goto cleanup;
+        }
     }
 
     /* update SHM modules */
@@ -2517,7 +2537,7 @@ sr_enable_module_feature(sr_conn_ctx_t *conn, const char *module_name, const cha
 
     SR_CHECK_ARG_APIRET(!conn || !module_name || !feature_name, NULL, err_info);
 
-    err_info = sr_change_module_feature(conn, module_name, feature_name, 1);
+    err_info = sr_change_module_feature(conn, module_name, feature_name, NULL, 1);
 
     return sr_api_ret(NULL, err_info);
 }
@@ -2529,7 +2549,19 @@ sr_disable_module_feature(sr_conn_ctx_t *conn, const char *module_name, const ch
 
     SR_CHECK_ARG_APIRET(!conn || !module_name || !feature_name, NULL, err_info);
 
-    err_info = sr_change_module_feature(conn, module_name, feature_name, 0);
+    err_info = sr_change_module_feature(conn, module_name, feature_name, NULL, 0);
+
+    return sr_api_ret(NULL, err_info);
+}
+
+API int
+sr_update_module_data(sr_conn_ctx_t *conn, const char *module_name, const char *data_path)
+{
+    sr_error_info_t *err_info;
+
+    SR_CHECK_ARG_APIRET(!conn || !module_name || !data_path, NULL, err_info);
+
+    err_info = sr_change_module_feature(conn, module_name, NULL, data_path, 1);
 
     return sr_api_ret(NULL, err_info);
 }
diff --git a/src/sysrepo.h b/src/sysrepo.h
index a5a65bdf..e0788459 100644
--- a/src/sysrepo.h
+++ b/src/sysrepo.h
@@ -665,6 +665,20 @@ int sr_enable_module_feature(sr_conn_ctx_t *conn, const char *module_name, const
  */
 int sr_disable_module_feature(sr_conn_ctx_t *conn, const char *module_name, const char *feature_name);
 
+/**
+ * @brief Update initial data of already loaded module.
+ *
+ * This function is primarily for initializing module data for modules
+ * loaded by sysrepo itself at bootstrap, e.g., ietf-netconf-acm, so
+ * that the factory-default for such modules is set properly.
+ *
+ * @param[in] conn Connection to use.
+ * @param[in] module_name Name of the module to change.
+ * @param[in] data_path Path to an initial data file of for the given module
+ * @return Error code (::SR_ERR_OK on success).
+ */
+int sr_update_module_data(sr_conn_ctx_t *conn, const char *module_name, const char *data_path);
+
 /**
  * @brief Get internal sysrepo data tree, which holds detailed information about installed modules. It should
  * not be needed except for some specific use-cases. These data are from the _sysrepo_ module found in
```

**Comment by michalvasko** [comment]
I started in a similar fashion, just wanting to adjust the `install` operation to be able to do this but there were lots of exceptions required and the code becoming messy. Following the principle of the `factory-default` datastore, I think I will just add a compile-time option to be able to set these data for the internal modules, should be enough.

**Comment by troglobit** [comment]
> I started in a similar fashion, just wanting to adjust the `install` operation to be able to do this but there were lots of exceptions required and the code becoming messy. Following the principle of the `factory-default` datastore, I think I will just add a compile-time option to be able to set these data for the internal modules, should be enough.

Yeah that would be awesome, thank you!

**Comment by michalvasko** [comment]
Alright, should be possible in the latest *sysrepo* `devel`.

**Comment by troglobit** [comment]
> Alright, should be possible in the latest _sysrepo_ `devel`.

Looks great, I'll have a go with it later today and let you know!

**Comment by michalvasko** [comment]
> I have to do some jq magic on a factory-default.json file that contains more configuration data/modules than what sysrepo has loaded modules for (e.g. Netopeer2). Would be neat if sysrepo could just skip ([WARN]) stuff it doesn't have instead of bailing out, then the same data could be used for all modules being loaded to slowly build up the factory-defaults for each module.

It is skipping unknown data (I have even tested just now) so I am wondering what exactly is the problem in your case, please mention details.

> Also, I made a local extension that uses lyd_parse_data_path() to load /etc/sysrepo/factory-default.[json,xml] if it exists. It's an attempt to handle initializing ietf-interfaces that I believe Netopeer2 has as a dependency (we have variable number of interfaces on devices using the same image). Don't know how you feel about such runtime support, but if you're interested I could post a draft PR?

You are right, it is implemented by the server even though not really used, unfortunately. However, that could be solved by installing it with some factory-default data before installing the server so no *sysrepo* changes should be required.

> Now I just have to figure out how to bootstrap netopeer2 instead of using the build-time generated data for ietf-keystore and ietf-netconf-server. We don't want our devices to revert to the same hostkey at factory-reset.

You can easily install it without the scripts and figure out what you want to do exactly then is up to you.

**Comment by troglobit** [comment]
> > I have to do some jq magic on a factory-default.json file that contains more configuration data/modules than what sysrepo has loaded modules for (e.g. Netopeer2). Would be neat if sysrepo could just skip ([WARN]) stuff it doesn't have instead of bailing out, then the same data could be used for all modules being loaded to slowly build up the factory-defaults for each module.
> It is skipping unknown data (I have even tested just now) so I am wondering what exactly is the problem in your case, please mention details.

Huh, then I must've done something else wrong.  Thank you, I'll retest and get back to you on this!

> > Also, I made a local extension that uses lyd_parse_data_path() to load /etc/sysrepo/factory-default.[json,xml] if it exists. It's an attempt to handle initializing ietf-interfaces that I believe Netopeer2 has as a dependency (we have variable number of interfaces on devices using the same image). Don't know how you feel about such runtime support, but if you're interested I could post a draft PR?
> You are right, it is implemented by the server even though not really used, unfortunately. However, that could be solved by installing it with some factory-default data before installing the server so no _sysrepo_ changes should be required.

Great then I'm on the right track. Thanks!

> > Now I just have to figure out how to bootstrap netopeer2 instead of using the build-time generated data for ietf-keystore and ietf-netconf-server. We don't want our devices to revert to the same hostkey at factory-reset.
> 
> You can easily install it without the scripts and figure out what you want to do exactly then is up to you.

That's great, thanks again, you have been extremely helpful! <3

**Comment by troglobit** [comment]
You were right, obviously.  The sysrepoctl line to set it all up became:

```
sysrepoctl -s $SEARCH							\
	   -i ietf-system@2014-08-06.yang				\
           	-e authentication					\
		-e local-users						\
		-e ntp							\
		-e ntp-udp-port						\
		-e timezone-name					\
	   -i nc-notifications@2008-07-14.yang				\
	   -i notifications@2008-07-14.yang				\
	   -i ietf-keystore@2019-07-02.yang				\
	   	-e keystore-supported					\
	   	-e local-definitions-supported				\
	   	-e key-generation					\
	   -i ietf-truststore@2019-07-02.yang				\
		-e truststore-supported					\
		-e x509-certificates					\
	   -i ietf-tcp-common@2019-07-02.yang				\
		-e keepalives-supported					\
	   -i ietf-ssh-server@2019-07-02.yang				\
		-e local-client-auth-supported				\
	   -i ietf-tls-server@2019-07-02.yang				\
		-e local-client-auth-supported				\
 	   -i ietf-netconf-server@2019-07-02.yang			\
	   	-e ssh-listen						\
		-e tls-listen						\
		-e ssh-call-home					\
		-e tls-call-home					\
	   -i ietf-interfaces@2018-02-20.yang    -e if-mib		\
	   -i ietf-ip@2018-02-22.yang					\
	   -i ietf-network-instance@2019-01-21.yang			\
	   -i ietf-netconf-monitoring@2010-10-04.yang			\
	   -i ietf-netconf-nmda@2019-01-07.yang				\
		-e origin						\
		-e with-defaults					\
	   -i ietf-subscribed-notifications@2019-09-09.yang		\
		-e encode-xml						\
		-e replay						\
		-e subtree						\
		-e xpath						\
	   -i ietf-yang-push@2019-09-09.yang     -e on-change		\
	   -i iana-if-type@2023-01-26.yang				\
	   -i ietf-if-extensions@2023-01-26.yang -e sub-interfaces	\
	   -i ieee802-dot1q-types@2022-10-29.yang			\
	   -i ietf-if-vlan-encapsulation@2023-01-26.yang		\
	   -i infix-ip@2023-04-24.yang					\
	   -i infix-if-type@2023-06-09.yang				\
	   -i infix-interfaces@2023-06-05.yang   -e vlan-filtering	\
	   -i infix-system@2023-04-11.yang				\
	   -I /etc/sysrepo/factory-default.json
```

To make everything work though I needed the runtime support I mentioned previously.  So I'll make a draft PR for that separately.  With this all now in place, I've also added support for `sysrepoctl -Cfactory -d running`, which is sort of useful to "reset" to factory defaults without having to wipe our the entire persistent storage.  I'll send that too as a separate PR.

Thanks again for your kind help and patient support!

**Comment by michalvasko** [comment]
Not sure what PRs you are talking about. Regarding the first, the command you posted should properly initialize factory-default of all the modules including `ietf-interfaces`. As for the second one, you are not supposed to be able to copy the data from factory-default anywhere, directly, so it is forbidden on purpose. You are supposed to use `ietf-factory-default:factory-reset` RPC.

**Comment by troglobit** [comment]
> Not sure what PRs you are talking about.

Sorry, I've been dragging my feet this weekend so I didn't have time to prepare any pull requests yet.

> Regarding the first, the command you posted should properly initialize factory-default of all the modules including `ietf-interfaces`.

Yeah, except the defaults differ between products so we need to generate defaults dynamically based on product type/model and other parameters.  So a compile-time default would not be sufficient for us.

> As for the second one, you are not supposed to be able to copy the data from factory-default anywhere, directly, so it is forbidden on purpose. You are supposed to use `ietf-factory-default:factory-reset` RPC.

I see, I was not aware of this.  I guess we can keep that patch locally.

**Comment by michalvasko** [comment]
> Yeah, except the defaults differ between products so we need to generate defaults dynamically based on product type/model and other parameters. So a compile-time default would not be sufficient for us.

Alright, so run the scripts after you generate and prepare the defaults. Factory-default is supposed to behave according to the name, once the device is deployed, the datastore contents do not change.

> I see, I was not aware of this. I guess we can keep that patch locally.

Yes, naturally, you can make whatever adjustments you want. My point is that you have not mentioned a problem/feature that I think should be merged into our repo.

**Comment by troglobit** [comment]
> > Yeah, except the defaults differ between products so we need to generate defaults dynamically based on product type/model and other parameters. So a compile-time default would not be sufficient for us.
> Alright, so run the scripts after you generate and prepare the defaults. Factory-default is supposed to behave according to the name, once the device is deployed, the datastore contents do not change.

Yes, the factory-default datastore must of course not change after the first bootup of the device, the order is:
 1. Generate hostname + hostkeys + ietf-interfaces-defaults for the given type/model
 2. Call sysrepoctl to install all models

With the current sysrepo support for default data (1), which you added, the config data is built-in at compile-time.  I've made a small patch to extend that so sysrepo first checks if the user has an `/etc/sysrepo/factory-default.json` (or `.xml`), if not your code runs.

> > I see, I was not aware of this. I guess we can keep that patch locally.
> Yes, naturally, you can make whatever adjustments you want. My point is that you have not mentioned a problem/feature that I think should be merged into our repo.

OK. Just thought it easier to show that in a PR, but here's the use-case; with a `copy factory running` feature, like Cisco/Juniper, one can revert to the defaults without wiping the persistent store.  Thus keeping any previous configurations on the device as reference or for other product use-cases (modes).  The factory-reset RPC on the other hand, and from what I understand, is required to wipe all persistent storage.  So, nothing big but useful for some users that want that type of workflow.  Also, I really don't see the harm in supporting copy-from factory, but we don't mind maintaining such patches out-of-tree.

**Comment by michalvasko** [comment]
> With the current sysrepo support for default data (1), which you added, the config data is built-in at compile-time.

This restriction is only for the internal modules.

> So, nothing big but useful for some users that want that type of workflow. Also, I really don't see the harm in supporting copy-from factory, but we don't mind maintaining such patches out-of-tree.

I generally agree and it seems to make sense. However, based on the specification, *sysrepo* allows to set other listeners for `factory-reset` RPC that can perform additional tasks for a full factory settings restore and you would bypass all those by executing the `copy-config`. However, I would have no problem with augmenting the `factory-reset` RPC (we are already doing that) with another optional (or with a default value) leaf that would allow to keep the `startup` datastore intact.

**Comment by troglobit** [comment]
That's fine, we'll maintain our out-of-tree patches for these features.  Thank you for all your time and invaluable help!
