### ISSUE TITLE
Get RPC not throwing access denied.

### ISSUE THREAD

**Issue by Meghna-5g** [sysrepo/sysrepo#3080]
As a NACM user if I am ttrying to perform get on yangs which are not supported for this particular user I am not getting any data which is ok but why i am not getting "access - denied" like for edit rpc and user rpc.

> get --filter-xpath /o-ran-dhcp:*
DATA
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"/>

> get --filter-xpath /o-ran-laa:*
DATA
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"/>

> get --filter-xpath /o-ran-lbm:*
DATA
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"/>

**Comment by michalvasko** [comment]
That is how the behavior is [specified](https://www.rfc-editor.org/rfc/rfc8341.html#section-3.2.4).

**Comment by Meghna-5g** [comment]
shall I share my rules too ?

**Comment by Meghna-5g** [comment]
Thanks a lot.
