### ISSUE TITLE
Adding an item to a leaf-list in a specific list item creates a new list item instead of modifying the existing

### ISSUE THREAD

**Issue by nhathaway** [sysrepo/sysrepo#3081]
{
      list myList {
      config false;
        leaf-list myLeafListA {
          type string;
        }
        leaf-list myLeafListB {
          type string;
        }
      }
    }

If I create /myList[1]/myLeafListA items, apply it, and then later create /myList[1]/myLeafListB items, it creates /myList[2]/myLeafListB items instead. I am using sr_set_item_str().

What is the work-around for this, since I want everything to be in the first item of myList?

**Comment by michalvasko** [comment]
Unfortunately, this is not currently possible because there is no way to distinguish between creating a new instance and addressing an existing one. But you should be able to call `sr_discard_items()` to remove the original instance followed by `sr_set_item_str()` to create it modified.

**Comment by nhathaway** [comment]
Surely the predicate [1] or [2] indicates whether you want to modify an existing list item or create a new one?

For example, if I wanted to modify the existing list item, I would create /myList[1]/myLeafListB, but if I wanted to create it in a new list item, I would create /myList[2]/myLeafListB.

**Comment by michalvasko** [comment]
Well, that is the theory but it used to be too complex to support. But with some recent changes it became manageable so it should now work the way you described it in *sysrepo* `devel`.
