### ISSUE TITLE
User with group level write permission to module is not able to write to datastore

### ISSUE THREAD

**Issue by mchwalisz** [sysrepo/sysrepo#3085]
Consider the permission model for a module being root owner, admin group and perms `660`. Meaning that the non-root user (let's call him admin) that belongs to admin group has full read write permissions.

```
sysrepoctl -l
Sysrepo repository: /etc/sysrepo

Module Name                   | Revision   | Flags | Owner       | Startup Perms | Submodules | Features                                                                                
---------------------------------------------------------------------------------------------------------
ietf-interfaces               | 2018-02-20 | I     | root:admin  | 660           |            |           
```

libsysrepo v2.2.73 (SO v7.14.32)

## What I expect should happen

`admin` user should to be allowed to modify the datastores with out problems.

## What happens
 I experience following error after writing to the datastore:

```
sysrepocfg -Evim -f json -mietf-interfaces
[ERR] JSON DS file: Failed to update file "/dev/shm/sr_ietf-interfaces.running" modification time (Operation not permitted).
```

The changes are actually applied to the datastore! Which IMHO is even more confusing as I'm presented with an error message and a changed system (no rollback).

## What circumstances lead to this error?

- default permissions to yang modules root:admin
- sysrepo tries to manually modify modification time
- https://man7.org/linux/man-pages/man2/utimensat.2.html
    Permissions requirements:
    To set both file timestamps to the current time (i.e., times is  NULL, or both tv_nsec fields specify UTIME_NOW), either:

    - the caller must have write access to the file;
    - the caller's effective user ID must match the owner of the file; or
    - the caller must have appropriate privileges.

## Source for the problem

https://github.com/sysrepo/sysrepo/blob/54c1b01537ca9909f18de202e0682a5be06f836b/src/plugins/ds_json.c#L148-L156

## Resolution

I do not know reasoning behind manually changing the modification time.

**Comment by michalvasko** [comment]
I have changed it to only a warning as it should generally be fine. The reason the modification time is updated manually is because it is used when caching the data to decide whether they were modified or not and on too frequent updates the modification time is not normally changed, the timestamp is being cached by the system and is too coarse.
