### ISSUE TITLE
operation db callback is called when trigger an action

### ISSUE THREAD

**Issue by follow612** [sysrepo/sysrepo#3086]
Hi experts,

I have subscribed one rpc action callback '_swm_download_rpc_cb' and one operation db callback '_hardware_state_get_cb'.

  `sr_oper_get_items_subscribe(srs, "ietf-hardware", "/ietf-hardware:hardware/component",
            _hardware_state_get_cb, NULL, SR_SUBSCR_OPER_MERGE, &sr_ctx);
`

`    sr_rc = sr_rpc_subscribe(srs, "/ietf-hardware:hardware/component/bbf-software-management:software/software/revisions/download/download, _swm_download_rpc_cb, NULL, 0, SR_SUBSCR_DEFAULT, &sr_ctx_swm_state);
`

When I trigged an rpc action for download, the operation callback '_hardware_state_get_cb' was also called. Is it an correct behavior? Could you take a look? Thanks a lot.
I'm expecting only rpc callback '_swm_download_rpc_cb' is called.

sysrepo 2.2.73

```html
<action xmlns="urn:ietf:params:xml:ns:yang:1">
    <hardware xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware">
        <component>
            <name>board</name>
            <software xmlns="urn:bbf:yang:bbf-software-management">
                <software>
                    <name>app</name>
                    <revisions>
                        <download>
                            <download>
                                <source>
                                    <url>http://192.168.1.2/test.bin</url>
                                </source>
                                <target>
                                    <selected-by-system>
                                        <operation>replace</operation>
                                        <replace>
                                            <not-available-only>false</not-available-only>
                                            <oldest-only>false</oldest-only>
                                        </replace>
                                    </selected-by-system>
                                </target>
                            </download>
                        </download>
                    </revisions>
                </software>
            </software>
        </component>
    </hardware>
</action>
```

**Comment by michalvasko** [comment]
When executing an action, it needs to be validated against the `operational` datastore and so when it is being generated, all required callbacks providing some relevant data are also called.

**Comment by follow612** [comment]
Sounds reasonable, thanks Michal.
 
Additional questions: 
Do we support subscribe operational db xpath with name like "/ietf-hardware:hardware/component[name='s*']"?
As rpc subscribe xpath with different component name, it may bypass calling operational callback function?

**Comment by follow612** [comment]
I mean rpc subscribe xpath may with "/ietf-hardware:hardware/component[name='board']"

**Comment by michalvasko** [comment]
> Do we support subscribe operational db xpath with name like "/ietf-hardware:hardware/component[name='s*']"?

You have not used any predicate when you were subscribing so yes, whatever the `name`, the callback will be called and expected to provide all the `component` instances.

> As rpc subscribe xpath with different component name, it may bypass calling operational callback function?

As I said, you would have to subscribe with a predicate for that to happen.
