### ISSUE TITLE
Seeking Suggestions for Sequential Behavior and Invocation of Registered Callbacks in Sysrepo

### ISSUE THREAD

**Issue by sujatapammar** [sysrepo/sysrepo#3089]
Hi Team,

I would like to seek a suggestion regarding the sequential behavior and invocation of registered callbacks in Sysrepo. I have successfully pushed all the configurations (module names mentioned below) to Sysrepo's candidate datastore. Upon confirmation using the "get-config" command, I observed that the configurations are stored in alphabetical yang module name order. Subsequently, when I push the commit, the callbacks are invoked in the same alphabetical yang module name order as well.

```
configuration order in module name:
==================================
ietf-hardware
bbf-qos-classifiers
bbf-qos-policies
ietf-interfaces
bbf-qos-traffic-mngt
bbf-xpongemtcont
bbf-link-table
bbf-l2-forwarding
```
My question pertains to the possibility of changing the default alphabetical storage order of configurations in Sysrepo. Since many of the leaf attributes are referenced by leaf-ref attributes in the YANG models, I am interested in exploring alternative methods to influence the sequential processing behavior during storage.

Could you kindly provide any suggestions or recommendations to achieve this objective?
[get-config-output.zip](https://github.com/sysrepo/sysrepo/files/11805204/get-config-output.zip)

**Comment by michalvasko** [comment]
[Adjust the order](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__change__subs__api.html#ga021d92cadf1121e5f64982f0f8d6bd61) the way you want.
