### ISSUE TITLE
Occasional sr_shmmod_lock: Connection timed out errors

### ISSUE THREAD

**Issue by pwang111** [sysrepo/sysrepo#3092]
We are running with the following sysrepo components:

sysrepo: 2.2.12
netopeer2: 2.1.42
libyang: 2.1.4
libnetconf2: 2.1.25

From time to time, we are hit by the following errors:

Waiting on a conditional variable failed (sr_shmmod_lock: Connection timed out).: Timeout expired

This always happened when around either or both of the following sysrepo API calls:

calling  sr_edit_batch() and then an immediate sr_apply_changes() with default_operation being merge, to push yang data into config store.
calling sr_notif_send_tree() to send a notification with wait = false. There are no notification callbacks registered for all the notifications sent through this API call.

We try to understand under what situations would cause the shmmod_lock to time out?

Thanks
Peng

**Comment by michalvasko** [comment]
The first thing I would suggest is to update all the projects to their current `devel` branches, there were some stability improvements made even since the last release.
