### ISSUE TITLE
sysrepocfg get/set operations

### ISSUE THREAD

**Issue by gotthardp** [sysrepo/sysrepo#3094]
Hello, have you ever considered having `get` and `set` operations for the `sysrepocfg` tool?

I am missing an easy way to set binary values. The problem is most obvious with `ietf-truststore` and `ietf-keystore`: with the existing standard tooling it is not easy to get/set X.509 keys and certificates. I was thinking about having a `sysrepocfg --set=<path>` that could be used to set a binary value based on a file or stdin, e.g. to set a certificate:
```
openssl x509 -in my.cert -outform DER | sysrepocfg --set=/ietf-truststore:truststore/certificates[name='a']/certificate[name='a']/cert
```
And similarly a `sysrepocfg --get=<path>` as way to retrieve a binary value, e.g. the certificate and place it to a file or stdout
```
sysrepocfg --get=/ietf-truststore:truststore/certificates[name='a']/certificate[name='a']/cert | openssl x509 -out my.cert
```

Another use-case (or a side-effect) would be a possibility to have bash scripts with sysrepo-based conditions, such as:
```bash
var="$(sysrepocfg --get=/path/to/value)"
if [[ $var == "yes" ]]; then
    ...
fi
```

But my primary use-case is export/import of keys and certificates to/from `.pem` files. The pem/der conversion is nicely handled by openssl, so all what is missing is a generic get/set.

Do you think the `sysrepocfg` could/should provide such operations, or these should be better provided by some other, more high-level tool, such as https://github.com/CESNET/netconf-cli (which does not provide operations suitable for binary values either)?

**Comment by michalvasko** [comment]
Okay, I have added the new operations.
