### ISSUE TITLE
Questions about subscription

### ISSUE THREAD

**Issue by naziaC** [sysrepo/sysrepo#3095]
Hi!

When subscribing to operational data (with sr_oper_get_subscribe) or changes made in the specified module (with sr_module_change_subscribe), if our application unexpectedly terminates, how should we go about with unsubscribing? 

Also, in  "/etc/sysrepo/conn", this is the flash of an embedded system so it's not good to keep on writing to it. Can we simply delete these files? Is it possible to issue commands to sysrepo that clears theses files?

Thanks!

**Comment by michalvasko** [comment]
> When subscribing to operational data (with sr_oper_get_subscribe) or changes made in the specified module (with sr_module_change_subscribe), if our application unexpectedly terminates, how should we go about with unsubscribing?

Well, you cannot anymore, obviously. But it will be detected later and properly unsubscribed if it is learned that the original subscriber connection is dead.

> Also, in "/etc/sysrepo/conn", this is the flash of an embedded system so it's not good to keep on writing to it. Can we simply delete these files? Is it possible to issue commands to sysrepo that clears theses files?

No, the files are important, you cannot simply delete them. Change your repository path to something that can normally be written to.

**Comment by naziaC** [comment]
Thank you! 

Just had another question, when two applications are accessing the same data in sysrepo, does sysrepo take care of protecting concurrent access or the applications need to create a semaphore to avoid critical section problems? 

Thank you again :)

**Comment by michalvasko** [comment]
The threading model is described in the [documentation](https://netopeer.liberouter.org/doc/sysrepo/devel/html/index.html#threads).

**Comment by naziaC** [comment]
Thanks for answering my questions :) I'll close the issue.

**Comment by naziaC** [comment]
Hi! 

So we have an application where we're subscribing to several different  lists (all config false) with `sr_oper_get_subscribe`. You mentioned before that connections will be detected later and properly unsubscribed if it is learned that the original subscriber connection is dead. 

For example, my application is subscribing to a list at the beginning of the program. Them, I kill the application and run it again. It subscribe again to he list without clearing the previous subscription. So now, I can no longer uninstall my yang module and I get the following error message:

How can we fix this?

```
> sysrepoctl  -u  nem
[ERR] Concurrent reader limit 10 reached!
[ERR] Internal error (/usr/src/debug/sysrepo/2.1.42+gitAUTOINC+2af422e1ae-r0/git/src/common.c:3826).
[ERR] Concurrent reader limit 10 reached!
[ERR] Oper subscription(s) to module "nem" no longer valid.
[ERR] Internal error (/usr/src/debug/sysrepo/2.1.42+gitAUTOINC+2af422e1ae-r0/git/src/common.c:3826).
sysrepoctl error: Failed to uninstall module "nem" (Operation failed)
For more details you may try to increase the verbosity up to "-v3".
[ERR] Concurrent reader limit 10 reached!
[ERR] Internal error (/usr/src/debug/sysrepo/2.1.42+gitAUTOINC+2af422e1ae-r0/git/src/common.c:3826).
```

**Comment by michalvasko** [comment]
And you have no other *sysrepo* application running? The locks should get recovered but maybe not in this particular case because of the old version of *sysrepo* you are using. So my advice is to update the code.

**Comment by naziaC** [comment]
Yup, you were right. Another sysrepo application was running. Sorry for the trouble :) and thanks!!
