### ISSUE TITLE
sr_module_change_subscribe priority among modules

### ISSUE THREAD

**Issue by follow612** [sysrepo/sysrepo#3097]
Hello experts,

I have subscribed the module changes for two modules and each module has two callback functions.
Callback function for module "bbf-l2-forwarding": **cb_forwarding_priority20** and **cb_forwarding_priority13**
Callback function for module "ietf-interfaces": **cb_interfaces_priority10** and **cb_interfaces_priority2**

When change the two modules in one rpc, I see the callback order as below:
  1. cb_forwarding_priority20
  2. cb_interfaces_priority10
  3. cb_forwarding_priority13
  4. cb_interfaces_priority2

```
Jun 26 14:47:55 netopeer2-server: EV ORIGIN: "bbf-l2-forwarding" "change" ID 1 priority 20 for 1 subscribers published.
Jun 26 14:47:55 netopeer2-server: EV ORIGIN: "ietf-interfaces" "change" ID 2 priority 10 for 1 subscribers published.
Jun 26 14:47:55 netopeer2-server: EV ORIGIN: "bbf-l2-forwarding" "change" ID 1 priority 20 succeeded.
Jun 26 14:47:55 netopeer2-server: EV ORIGIN: "ietf-interfaces" "change" ID 2 priority 10 succeeded.
Jun 26 14:47:55 netopeer2-server: EV ORIGIN: "bbf-l2-forwarding" "change" ID 1 priority 13 for 1 subscribers published.
Jun 26 14:47:55 netopeer2-server: EV ORIGIN: "ietf-interfaces" "change" ID 2 priority 2 for 1 subscribers published.
Jun 26 14:47:55 netopeer2-server: EV ORIGIN: "bbf-l2-forwarding" "change" ID 1 priority 13 succeeded.
Jun 26 14:47:55 netopeer2-server: EV ORIGIN: "ietf-interfaces" "change" ID 2 priority 2 succeeded.
```

But I'm expecting the callback order just based on the priority regardless of the modules, so that it can be the global priority for all callbacks among modules.
The expected order for this case can be:
  1. cb_forwarding_priority20
  2. cb_forwarding_priority13
  3. cb_interfaces_priority10
  4. cb_interfaces_priority2

Is it possible to do that? Thanks a lot.

**Comment by michalvasko** [comment]
It is quite clearly documented, the callback priorities are used only for a single module callbacks. Moudles themselves have their own order, which you can [change](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__change__subs__api.html#ga021d92cadf1121e5f64982f0f8d6bd61) as well.
