### ISSUE TITLE
 sysrepoctl -C  Cannot be used

### ISSUE THREAD

**Issue by Karl-ZhangBD** [sysrepo/sysrepo#3099]
When I execute this command, I get the following situation, how should I fix it?

root@ubuntu:/home/karl/work/sysrepo/build/examples# sysrepoctl -C
sysrepoctl error: Invalid option or missing argument: -C
For more details you may try to increase the verbosity up to "-v3".
root@ubuntu:/home/karl/work/sysrepo/build/examples# sysrepoctl -C -v3
sysrepoctl error: Invalid option or missing argument: -C
For more details you may try to increase the verbosity up to "-v3".

**Comment by Karl-ZhangBD** [comment]
and this command also has errors.

root@ubuntu:/home/karl/work/sysrepo/build/examples# sysrepo-plugind -d -v3 &
[1] 2646
root@ubuntu:/home/karl/work/sysrepo/build/examples# [INF] Connection 14 created.
[INF] Session 45 (user "root", CID 14) created.
[INF] Triggering "sysrepo-plugind" "done" event on enabled data.
[ERR] Operational get subscription for XPath "/sysrepo-plugind:sysrepo-plugind/notif-datastore/rotation/rotated-files-count" already exists and SR_SUBSCR_OPER_MERGE not used.
[ERR] srpd_rotation: Failed to subscribe (Invalid argument)
[ERR] sysrepo-plugind: Plugin "srpd_rotation" initialization failed (Invalid argument).
[INF] Triggering "sysrepo-plugind" "enabled" event on enabled data.
[INF] Triggering "sysrepo-plugind" "done" event on enabled data.
[INF] sysrepo-plugind: Plugin "srpd_oper_poll_diff" initialized.

**Comment by precla** [comment]
There is no `-C`, check available commands with `sysrepoctl -h`

and the other issue sounds like you have a plugin already running "already exists":
`[ERR] Operational get subscription for XPath "/sysrepo-plugind:sysrepo-plugind/notif-datastore/rotation/rotated-files-count" already exists and SR_SUBSCR_OPER_MERGE not used.`

**Comment by Karl-ZhangBD** [comment]
I followed the example and would like to know where the configuration is stored?
I went to sysrepo/build/repository/data/oven.running.perm and found that the file was empty.

root@ubuntu:/home/karl# sysrepocfg --edit=vim --datastore running
root@ubuntu:/home/karl# sysrepocfg --export --xpath /oven:*
<oven xmlns="urn:sysrepo:oven">
  <turned-on>true</turned-on>
  <temperature>200</temperature>
</oven>

**Comment by michalvasko** [comment]
The repository is meant for storing persistent data, which are the contents of `startup` and `factory-default` datastores and permissions for the other datastores. But their data are stored in memory-mapped volatile files in `/dev/shm`.
