### ISSUE TITLE
Making subscribing application mandatory

### ISSUE THREAD

**Issue by ChinmayaAgarwal** [sysrepo/sysrepo#3100]
Hi,

In the latest sysrepo/netopeer2 versions, it is not mandatory to have a subscribing application listening to sysrepo's running data tree changes. But, is there a way, through some configuration may be, for making the subscribing application mandatory like it was in some old release candidate versions?

Thanks and Regards,
Chinmaya Agarwal.

**Comment by michalvasko** [comment]
> But, is there a way, through some configuration may be, for making the subscribing application mandatory like it was in some old release candidate versions?

What should be the effect of mandatory subscription? Not allowing to edit `running` data without one? There should be some rather cumbersome ways of implementing such behavior if you really needed it but in general the functionality changed so it would be best if you adjusted your application accordingly.

**Comment by ChinmayaAgarwal** [comment]
Yes, basically we want that if there is no subscribing application running, an RPC error must be returned to the client. It use to be like this in old release candidate versions where it use to return RPC error stating "The node is not enabled in running datastore.". We would like to have something exactly like that because our complete use case depends on this validation. 
If there are ways to implement such behavior, what would that be?

Thanks and Regards,
Chinmaya Agarwal.

**Comment by michalvasko** [comment]
In `sysrepo-monitoring` there is information about all the subscriptions so based on that you should be able to decide whether some data are subscribed or not but I am not sure it is a good idea. You can also learn what `running` data are subscribed by comparing `running` and `operational` datastores, data not subscribed to will not appear in `operational` datastore (unless they are provided by other sources).
