### ISSUE TITLE
Delete an item using NETCONF operation delete.

### ISSUE THREAD

**Issue by alessiocnit** [sysrepo/sysrepo#3104]
I'm trying to delete an item in a list using the following xml:

```xml
<?xml version="1.0"?>
<edit-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <target>
    <running/>
  </target>
  <config>
    <qkd_node xmlns="urn:etsi:qkd:yang:etsi-qkd-node">
      <qkd_links>
        <qkd_link operation="delete">
          <qkdl_id>f81d4fae-aaaa-aaaa-aaaa-00a0c91e6bf6</qkdl_id>
        </qkd_link>
      </qkd_links>
    </qkd_node>
  </config>
</edit-config>
```

The server replies `<ok/>`

But the item is not deleted from the datastore. Can you see an issue in the xml code?

**Comment by michalvasko** [comment]
The operation is missing its namespace, change it similarly to an [example](https://datatracker.ietf.org/doc/html/rfc6241#page-41) in the RFC.
