### ISSUE TITLE
Query: separate instance of configuration data (DS) per sysrepo connection/session

### ISSUE THREAD

**Issue by manomugdha** [sysrepo/sysrepo#3105]
Hi,
I have an application which can simulate many netconf servers in a single process (linux). So many netconf clients can connect to these servers and these connections are independent of each other. All netconf client/server are using exactly same yang modules/schemas but their configuration/operational data, notification/subscription can be different.
I was going through the documention of sysrepo whether i can use sysrepo as my database management system. It seems that I can not use sysrepo to maintain separate instance of configuration data (DS) for each netconf connection (which would be tied to a sysrep connection) in a system but I am not very clear! can you please share your thoughts?

**Comment by michalvasko** [comment]
Well, you can use some [env variables](https://github.com/sysrepo/sysrepo/#used-run-time-enviromental-variables) to "run" multiple instances of *sysrepo*, each with a separate *netopeer2-server*. But it is not really advised to do this. Also, you cannot have multiple instances of *sysrepo* with a single *netopeer2-server*.

**Comment by manomugdha** [comment]
Thank you @michalvasko for this input.
I tried this and it seems that now I can run multiple instances of NP servers (tried with 2 instances) without any error. but i am seeing one issue while trying to connect NP client to these NP servers. It is saying "Connection refused" and then I see that NP server is not listening on the configured port. Following is the code i added in server_init() before sr_connect().

    /* setup environment */
    char tst_name[50];
    sprintf(tst_name, "%d", getpid());
    rc = np_glob_setup_env(tst_name);

    /* setup netopeer2 server */
    if (setenv("NP2_MODULE_DIR", NP_ROOT_DIR "/modules", 1)) {
        goto error;
    }
    if (setenv("NP2_MODULE_PERMS", "600", 1)) {
        goto error;
    }
    if (system(NP_ROOT_DIR "/scripts/setup.sh")) {
        goto error;
    }
    if (system(NP_ROOT_DIR "/scripts/merge_hostkey.sh")) {
        goto error;
    }
    if (system(NP_ROOT_DIR "/scripts/merge_config.sh")) {
        goto error;
    }
    //if (unsetenv("NP2_MODULE_DIR")) {
    //    goto error;
    //}
    //if (unsetenv("NP2_MODULE_PERMS")) {
    //    goto error;
    //}

    // Definition of np_glob_setup_env()
    #define NP_SR_REPOS_DIR_2 "/home/mbiswas/netopeer2/build/test"
    #define NP_SR_SHM_PREFIX_2 "_check_np_"
    static int
    np_glob_setup_env(const char *test_name)
    {
        int ret = 1;
        char *sr_repo_path = NULL, *sr_shm_prefix = NULL;
        sr_repo_path = malloc(strlen(NP_SR_REPOS_DIR_2) + 1 + strlen(test_name) + 1);
        if (!sr_repo_path) {
             goto cleanup;
        }
        /* set sysrepo environment variables */
        sprintf(sr_repo_path, "%s/%s", NP_SR_REPOS_DIR_2, test_name);
        if (setenv("SYSREPO_REPOSITORY_PATH", sr_repo_path, 1)) {
            goto cleanup;
        }
        sr_shm_prefix = malloc(strlen(NP_SR_SHM_PREFIX_2) + strlen(test_name) + 1);
        if (!sr_shm_prefix) {
            goto cleanup;
        }
        sprintf(sr_shm_prefix, "%s%s", NP_SR_SHM_PREFIX_2, test_name);
        if (setenv("SYSREPO_SHM_PREFIX", sr_shm_prefix, 1)) {
            goto cleanup;
        }
        ret = 0;

        cleanup:
            free(sr_repo_path);
            free(sr_shm_prefix);
            return ret;
    }

most probably merge_config.sh is causing the problem. but it is getting executed without any error.
All callbacks like `np2srv_endpt_ssh_cb()`, `np2srv_endpt_tcp_params_cb()` are getting called but `sr_get_change_tree_next()` is returning `SR_ERR_NOT_FOUND`. 
I tried to check available tests but not able to figure out what i am missing!
please note that before this code change i could connect NP client to server with its functionalities.
I tried rebuilding `libyang`, `sysrepo`, `libnetconf` and `netopeer2` in this order but did not work.

**Comment by manomugdha** [comment]
I have tried it again after few hours in same setup/terminals and it is working now.
thank you.
