### ISSUE TITLE
nc_ps_poll Connection timed out

### ISSUE THREAD

**Issue by hi-Mr-ye** [sysrepo/sysrepo#3107]
Hi
When I use the user-rpc command, netopeerr2-server return ok, but netopeerr2-server keeps printing timeout until I disconnect
![image](https://github.com/sysrepo/sysrepo/assets/90752673/b55e8cd5-2f0f-488f-ae4f-21173ff02dea)
xml info:
![image](https://github.com/sysrepo/sysrepo/assets/90752673/92934487-0e2d-4b96-a37e-2a581e0f7283)
I connect netopeer2-server again, netopeer2-server prints:
![image](https://github.com/sysrepo/sysrepo/assets/90752673/cd51afc1-6f95-49e5-8923-f374e461aa33)

This is the log:
[netopeer2-server.log](https://github.com/sysrepo/sysrepo/files/11944067/netopeer2-server.log)

netopeer2-server version:
netopeer2-server 2.1.62

yang version:
yanglint 2.1.73

**Comment by michalvasko** [comment]
So what you did was change the system time with the RPC? Could you post the output of running `cmake` for *netopeer2* with an empty `build` directory?

**Comment by hi-Mr-ye** [comment]
yes
> So what you did was change the system time with the RPC
![image](https://github.com/sysrepo/sysrepo/assets/90752673/c2794422-d58b-4979-8768-dcf61ff8d524)

and cmake log:
[netopeer2.log](https://github.com/sysrepo/sysrepo/files/11945999/netopeer2.log)

**Comment by michalvasko** [comment]
I am not sure I have reproduced it but I got the same behavior when *libnetconf2* and *sysrepo* were compiled with `CLOCK_MONOTONIC` and *netopeer2* without it, with `CLOCK_REALTIME`. Then some weird linking caused the 2 clocks to mix.

However, this should never normally happen and all the projects are expected to be using the same clock. The platform you are on seems to be using old `glibc` that is missing `pthread_mutex_clocklock()` and similar functions so `CLOCK_REALTIME` is used. When you change system time, this clock time is changed and it messes with the timeouts used throughout the projects. But after some elapsed timeouts it should still continue to work so I am not sure what exactly is happening. My advice is, use a platform with a recent enough `glibc` and you should have no problems whatsoever.
