### ISSUE TITLE
[ERR] Failed to create input handler for "xxx.yang"

### ISSUE THREAD

**Issue by Karl-ZhangBD** [sysrepo/sysrepo#3108]
I was installing the YANG model and had this problem pop up.
root@ubuntu:/home/karl/work/sysrepo/build/repository/data# sysrepoctl -i ieee802-dot1q-types.yang -v3
[INF] Connection 37 created.
[ERR] Failed to create input handler for "ieee802-dot1q-types.yang".
sysrepoctl error: Failed to install modules (Invalid argument)

**Comment by Karl-ZhangBD** [comment]
root@ubuntu:/home/karl/work/YANG/AS# sysrepoctl -i ieee1588-ptp.yang
[ERR] JSON DS file: Opening "/dev/shm/sr_ietf-netconf-acm.running" failed (File exists).
[ERR] Callback "init" of plugin "JSON DS file" for module "ietf-netconf-acm" failed.
sysrepoctl error: Failed to connect (System function call failed)
For more details you may try to increase the verbosity up to "-v3".

**Comment by michalvasko** [comment]
Most likely the file you are trying to install is empty and not sure how you got to the second error. What *sysrepo* version are you using?

**Comment by michalvasko** [comment]
You just keep posting different problems without any details and whether you have fixed the previous ones or not. In any case, the last one is trivial, the order of the parameters matters to some extent because the module file is an argument of the `-u` parameter so you must use
```
root@ubuntu:/home/karl/work/sysrepo/build/repository/yang# sysrepoctl -u ieee802-dot1q-preemption.yang -v3
```

**Comment by Karl-ZhangBD** [comment]
> I was installing the YANG model and had this problem pop up.
> root@ubuntu:/home/karl/work/sysrepo/build/repository/data# sysrepoctl -i ieee802-dot1q-types.yang -v3
> [INF] Connection 37 created.
> [ERR] Failed to create input handler for "ieee802-dot1q-types.yang".
> sysrepoctl error: Failed to install modules (Invalid argument)

All the YANG models in question are the ones I downloaded from this link：
https://github.com/YangModels/yang/blob/main/standard/ieee/draft/802.1/Qcw/ieee802-dot1q-types.yang
I made another attempt at this problem above, from the error message, it is because I installed ieee802-types.yang, but the contents of these two files are not the same, you can also see the contents of this YANG model through the above link.

root@ubuntu:/home/karl/work/YANG# sysrepoctl -i ieee802-dot1q-types.yang -v3
[INF] Connection 2 created.
[INF] Module "ieee802-types" was installed.
[ERR] JSON DS file: File "/home/karl/work/sysrepo/build/repository/data/ieee802-types.startup" already exists.
[ERR] Callback "install" of plugin "JSON DS file" for module "ieee802-types" failed.
sysrepoctl error: Failed to install modules (Item already exists)

**Comment by michalvasko** [comment]
Sorry, I have not noticed you have used the module file name. When uninstalling, only the YANG module name is expected, so
```
root@ubuntu:/home/karl/work/YANG/Qbu# sysrepoctl -u ieee802-dot1q-preemption -v3
```

**Comment by Karl-ZhangBD** [comment]
> > I was installing the YANG model and had this problem pop up.
> > root@ubuntu:/home/karl/work/sysrepo/build/repository/data# sysrepoctl -i ieee802-dot1q-types.yang -v3
> > [INF] Connection 37 created.
> > [ERR] Failed to create input handler for "ieee802-dot1q-types.yang".
> > sysrepoctl error: Failed to install modules (Invalid argument)
> 
> All the YANG models in question are the ones I downloaded from this link： https://github.com/YangModels/yang/blob/main/standard/ieee/draft/802.1/Qcw/ieee802-dot1q-types.yang I made another attempt at this problem above, from the error message, it is because I installed ieee802-types.yang, but the contents of these two files are not the same, you can also see the contents of this YANG model through the above link.
> 
> root@ubuntu:/home/karl/work/YANG# sysrepoctl -i ieee802-dot1q-types.yang -v3 [INF] Connection 2 created. [INF] Module "ieee802-types" was installed. [ERR] JSON DS file: File "/home/karl/work/sysrepo/build/repository/data/ieee802-types.startup" already exists. [ERR] Callback "install" of plugin "JSON DS file" for module "ieee802-types" failed. sysrepoctl error: Failed to install modules (Item already exists)

Can you take a look at this? Thank you very much.

**Comment by michalvasko** [comment]
Please include all the steps to reproduce this starting with `make sr_clean`.
