### ISSUE TITLE
After install an extend module with deviation, it will append default value

### ISSUE THREAD

**Issue by Pengwei-Chen-1** [sysrepo/sysrepo#3110]
### Then environment:
```
[root@netconf-main-debug-jelf-job-vq5hp log]# uname -srv
Linux 4.15.0-147-generic #151-Ubuntu SMP Fri Jun 18 19:21:19 UTC 2021
[root@netconf-main-debug-jelf-job-vq5hp log]# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.4 (Ootpa)
[root@netconf-main-debug-jelf-job-vq5hp log]# sysrepoctl -V
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v2.2.73 (SO v7.14.32)
```

- libyang: v2.1.80
- libnetconf2: v2.1.34
- sysrepo: v2.2.73
- Netopeer2: v2.1.62

### Re-produce step:
1. Install the `ietf-netconf-acm@2018-02-14.yang` module and its dependency modules.
2. Install the extend yang module which include a `deviation`, the content as below
3. Check the data with `sysrepocfg --export --module ietf-netconf-acm` or by the `/usr/local/bin/netopeer2-cli`

```
module nacm-ext {
    yang-version 1.1;
    namespace urn:rdns:com:test:oammodel:nacm-ext;
    prefix nacmxe;

    import ietf-netconf-acm {
        prefix nacm;
    }

    organization
      "Test";
    contact
      "Test.";
    description
      "Just test extend nacm";

    revision "2023-05-24" {
        description
          "First version";
    }

    deviation /nacm:nacm/nacm:enable-nacm {
        description
          "NACM shall always be enabled.
           The user is not allowed to change it.";
        deviate add {
            config false;
        }
    }
}
```
After install the extend yang module, the data as below:
```
[root@netconf-main-debug-jelf-job-vq5hp modules]# sysrepocfg --export --module ietf-netconf-acm
<nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
  <enable-nacm>true</enable-nacm>
</nacm>
```

### Question:
Previous we use the sysrepo `v1.4.140` and the corresponding `libyang/libnetconf2/netopeer2` version. It should be no this problem.
Now we upgrade these repos to 2.x version, then we meet this problem.

1. So does this is a problem?
2. Why the `deviation` will append the default value to `ietf-netconf-acm` ?
3. If I don't want this default value, and also want to keep the `deviation` in the extend yang module, how can I do ?

**Comment by Pengwei-Chen-1** [comment]
I also do below test, and I know modify the `ietf-netconf-acm\@2018-02-14.yang` is not recommand.
![image](https://github.com/sysrepo/sysrepo/assets/8297191/07883ea5-8251-4c78-9e18-f080a503316d)

So after I install this `ietf-netconf-acm\@2018-02-14.yang` and not install the extend yang file, there is no data in the `ietf-netconf-acm` module.
Seems the `deviation` append the values during install the extend yang file?

**Comment by michalvasko** [comment]
There was a bug causing the old values to not be updated. But I am not sure everything will work correctly after you apply this deviation, *sysrepo* implements NACM itself and it expects the original module.

**Comment by Pengwei-Chen-1** [comment]
@michalvasko Thanks for your comments, and I test our business with your code commit, seems it works well.
It is no problem now, thanks again.

**Comment by Pengwei-Chen-1** [comment]
> I think that adding a new `must` statement which checks that the `enable-nacm` is always set to `true` is a bit cleaner than deviating to `config false`.

@jktjkt  thanks for your comments, actually we add 4 parameters `deviation` in the extend yang module, due to we want totally ignore the configure operation for them, also we manually set them default value.
I'm not very familier with the YANG module function, but still thank you for provide another choice, we will think about the `must`
