### ISSUE TITLE
Duplicate instance of 

### ISSUE THREAD

**Issue by hi-Mr-ye** [sysrepo/sysrepo#3111]
Hi
I used the user-rpc command, but netopeer2-server print:
![image](https://github.com/sysrepo/sysrepo/assets/90752673/54ca0bb0-4a91-4a1e-b9ed-c1201bc2f951)

I printed out the relevant information of the program, there is no duplication
![image](https://github.com/sysrepo/sysrepo/assets/90752673/b45bda99-af1b-423e-bee9-43167341dc2b)

xml file:
![image](https://github.com/sysrepo/sysrepo/assets/90752673/29af6190-8a87-4435-9d5f-75b3c5c04cce)

but why?
This is the yang file:
[port-performance.zip](https://github.com/sysrepo/sysrepo/files/11965347/port-performance.zip)

**Comment by michalvasko** [comment]
Can you post the code of the callback handling the RPC, which is creating the output nodes? Not sure what the problem may be if there really is no duplicate.

**Comment by hi-Mr-ye** [comment]
sample code:
[code-and-yang.zip](https://github.com/sysrepo/sysrepo/files/12010068/code-and-yang.zip)

and version information:
![image](https://github.com/sysrepo/sysrepo/assets/90752673/c1b3abfb-9a78-43ac-a988-6fa01dd373e7)

**Comment by michalvasko** [comment]
Thanks for the example, it worked perfectly when I tested on the current `devel` branches of all the projects, both when using just *sysrepo* and when executing the RPC using *netopeer2-cli*.

**Comment by hi-Mr-ye** [comment]
thank you! 
current devel is latest version? What is the version?
Could the problem be caused by files under /etc/sysrepo?

**Comment by hi-Mr-ye** [comment]
Hi
I have verified this problem under different linux,
it worked perfectly and This is the etc/sysrepo file:
[sysrepo-success.tar.gz](https://github.com/sysrepo/sysrepo/files/12013106/sysrepo-success.tar.gz)

linux version：
![image](https://github.com/sysrepo/sysrepo/assets/90752673/42d5535f-dad6-45be-9644-289adca68d35)

The other is a failure and etc/sysrepo file:
[sysrepo-fail.tar.gz](https://github.com/sysrepo/sysrepo/files/12013126/sysrepo-fail.tar.gz)

linux version:
![image](https://github.com/sysrepo/sysrepo/assets/90752673/d880eb7a-9c1b-400c-a1e2-7930138b1e1d)

They have the same version of netopeer2-server.

why？

**Comment by michalvasko** [comment]
When it succeeded you did not even have `port-performance` YANG module installed. Meaning you could not have executed the RPC so I am not sure what exactly you are doing.

**Comment by hi-Mr-ye** [comment]
I'm sorry
This is the right file:
[sysrepo-success.tar.gz](https://github.com/sysrepo/sysrepo/files/12014083/sysrepo-success.tar.gz)

**Comment by michalvasko** [comment]
The files are exactly the same on failure and success so like I said, they do not affect the issue.
