### ISSUE TITLE
Timeout issues with callbacks due to custom validation

### ISSUE THREAD

**Issue by naziaC** [sysrepo/sysrepo#3112]
Hi!

We have an application where we have callback functions associated with config data in sysrepo (i.e., we use `sr_module_change_subscribe` to subscribe to the changes). In these callback functions, we are doing some custom validation which is taking too much time and very often some of the callbacks are timing out (`Callback event "rpc" with ID 1 processing timed out`). 
Is there a way to increase the timeout or is there another approach we can use to avoid the timeout?

Thank you!

**Comment by michalvasko** [comment]
Yes, you will have to increase the timeout. If we are talking about *netopeer2-server*, just use `-t 60` for a minute-long timeout, for example.
