### ISSUE TITLE
Copy data from startup to running after module subscription

### ISSUE THREAD

**Issue by alexeimerk** [sysrepo/sysrepo#3114]
Hello Michael,
I have question: During our porting from old sysrepo version to last one, we found issue with copy data from startup data store to running when we call to sr_module_change _subscribe() function.
In old version this call copied data startup->running, and now, the function behavour is changed, we doen't observe copy operation.
For example: 
we import data from XML file to startup storage, for one of our installed modules, subscribe the module and got ALL data from startup storage inside running, for this module.
Now, it is not happened.
I see two option to copy data to running in our case:
a) import XML data to startup and running the same time
b) call to function sr_copy_config() after import XML file to startup storage

Question: Do we have other option for reach our target, like it was in old version, maybe we should change any flag?

**Comment by michalvasko** [comment]
There is a difference, the data are now automatically copied from `startup` to `running` only on system boot, which is closed to the specification. There is no flag to enforce the old behavior but you can always perform the copy yourself.

**Comment by alexeimerk** [comment]
Thank you Michael, I will add sr_copy_config() to my function for modules registration
