### ISSUE TITLE
Operational callback not invoked in nested config false container

### ISSUE THREAD

**Issue by rsoarespadtec** [sysrepo/sysrepo#3115]
Hello,
I am facing an issue when inserting a `sr_oper_get_subscribe` for a leaf in the `openconfig-system` model. I have been able to reproduce the same behavior in the `examples.yang` file.

When I run the `oper_data_pull_example` with the path `/examples:stats/counter`, everything works fine. Here are the commands and their respective outputs:
```
# ./sr_get_items_example  /examples:stats/counter operational                                                            
Application will get "/examples:stats/counter" from "operational" datastore.
```
```
# ./oper_data_pull_example examples /examples:stats/counter
Application will provide data "/examples:stats/counter" of "examples".



 ========== LISTENING FOR REQUESTS ==========



 ========== DATA FOR "examples" "/examples:stats/counter" REQUESTED =======================
```

However, if I wrap the `stats` and  `cont` container into another container, let's say `test`, the oper callback stops getting invoked. Here is the modified code snippet from the `examples.yang` file:
```
diff --git a/examples/examples.yang b/examples/examples.yang
index d768ecb0..3825a39f 100644
--- a/examples/examples.yang
+++ b/examples/examples.yang
@@ -2,6 +2,7 @@ module examples {
     namespace "urn:examples";
     prefix e;
 
+    container test {
     container cont {
         leaf l {
             type string;
@@ -18,6 +19,7 @@ module examples {
             type uint64;
         }
     }
+    }
 
     rpc oper {
         input {
```

Now, when I use `oper_data_pull_example` with the following path:
```
# ./oper_data_pull_example examples /examples:test/stats/counter
Application will provide data "/examples:test/stats/counter" of "examples".



 ========== LISTENING FOR REQUESTS ==========
```

The oper callback never gets invoked when I make the following call:
```
# ./sr_get_items_example  /examples:test/stats/counter operational
Application will get "/examples:test/stats/counter" from "operational" datastore.
```

However, if I put the subscription in the `stats` container, the callback does get invoked. Here are the commands and their outputs:
```
# ./oper_data_pull_example examples /examples:test/stats        
Application will provide data "/examples:test/stats" of "examples".



 ========== LISTENING FOR REQUESTS ==========



 ========== DATA FOR "examples" "/examples:test/stats" REQUESTED =======================
```
```
# ./sr_get_items_example  /examples:test/stats/counter operational
Application will get "/examples:test/stats/counter" from "operational" datastore.
```

In addition, I have observed that the subscription for the `l` leaf of the `cont` container, which is `config true`, works fine as well. Here are the commands and their outputs:

```
# ./oper_data_pull_example examples /examples:test/cont/l
Application will provide data "/examples:test/cont/l" of "examples".



 ========== LISTENING FOR REQUESTS ==========



 ========== DATA FOR "examples" "/examples:test/cont/l" REQUESTED =======================
```
```
./sr_get_items_example  /examples:test/cont/l operational
```

I wonder if this something related to a nested container with `config false`.

I'm using the latest `sysrepo` and `libyang` from the `devel` branch, with the following revisions:

-   sysrepo: c6613149
-   libyang: cd7e4adbf

I'm not sure if I'm doing something wrong or if this is indeed a bug. Thank you in advance for your help.

**Comment by michalvasko** [comment]
Try it with updated *libyang*, there was a problem that should be fixed.

**Comment by rsoarespadtec** [comment]
Hi Michal, 
I've tested the fix and it's working just fine now. Thank you so much!
