### ISSUE TITLE
Guidance regarding sysrepo

### ISSUE THREAD

**Issue by hrmnboparai** [sysrepo/sysrepo#3116]
I am new to his and  want to implement NetConf server over my device. Should I start my journey by learning from Sysrepo documentation or there is some other path?

**Comment by michalvasko** [comment]
Seems you have already read *sysrepo* documentation. After that I would suggest you try playing with the [example oven plugin](https://netopeer.liberouter.org/doc/sysrepo/devel/html/srpd_example.html). That way you should understand how to implement all the various callbacks in practice.

**Comment by hrmnboparai** [comment]
Hey michalvasko , I am able to initialise the plugin. Can you please tell me how can I exactly connect to it to play around a bit.  I have read that there are couple of ways like netopeer2-cli and sysrepocfg but I am not sure how to proceed.
![Oven](https://github.com/sysrepo/sysrepo/assets/60837282/352a191b-0070-483f-93c8-7002773e866c)

**Comment by michalvasko** [comment]
The easiest is to use `sysrepocfg`, just run `sysrepocfg -h` and you should see all the commands you may want to use.
