### ISSUE TITLE
sysrepoctl always failing after yang module install

### ISSUE THREAD

**Issue by tatyakadam** [sysrepo/sysrepo#3117]
Hi,

I have installed yang file:

root@cpa-5bfc9b8988-nc6bt:/sysrepo/examples/yang# sysrepoctl -i unicloud-config.yang -s . -v3
[INF] Connection 3 created.
[INF] Module "unicloud-config" was installed.
[INF] Dependency module "tailf-aaa" was installed.
[INF] File "unicloud-config@2016-01-22.yang" was installed.
[INF] File "unicloud-common@2012-09-20.yang" was installed.
[INF] File "tailf-common@2021-06-22.yang" was installed.
[INF] File "tailf-meta-extensions@2017-03-08.yang" was installed.
[INF] File "tailf-cli-extensions@2021-06-22.yang" was installed.
[INF] File "unicloud-latency-points-defs.yang" was installed.
[INF] File "unicloud-logmodules.yang" was installed.
[INF] File "unicloud-config-users@2015-01-30.yang" was installed.
[INF] File "tailf-aaa@2011-09-22.yang" was installed.
[INF] File "tailf-xsd-types@2017-11-20.yang" was installed.
[INF] File "unicloud-config-meshrouting@2012-09-20.yang" was installed.
[INF] File "unicloud-config-zone@2015-01-30.yang" was installed.
[INF] File "unicloud-config-profile@2015-01-30.yang" was installed.
[INF] File "unicloud-config-system@2012-09-20.yang" was installed.
[INF] File "unicloud-config-servergroup@2012-09-20.yang" was installed.
[INF] File "unicloud-config-ipam@2012-09-20.yang" was installed.
[INF] File "unicloud-ip-acl-packet-header-fields@2015-02-10.yang" was installed.
[INF] File "unicloud-config-ip-acl@2015-02-10.yang" was installed.
[INF] File "unicloud-config-vrf@2012-09-20.yang" was installed.
[INF] File "unicloud-config-cluster@2012-09-20.yang" was installed.
[INF] File "unicloud-config-x2gw@2012-09-20.yang" was installed.
[INF] File "unicloud-config-protocol@2012-09-20.yang" was installed.
[INF] File "unicloud-config-ric-oam@2020-04-28.yang" was installed.
[INF] File "unicloud-config-venb@2012-09-20.yang" was installed.
[INF] File "unicloud-config-vrnc@2012-09-20.yang" was installed.
[INF] File "unicloud-config-vbsc@2012-09-20.yang" was installed.
[INF] File "unicloud-config-vpcu@2012-09-20.yang" was installed.
[INF] File "unicloud-config-vepdg@2012-09-20.yang" was installed.
[INF] File "unicloud-config-vtwangw@2012-09-20.yang" was installed.
[INF] File "unicloud-config-vsaegw@2012-09-20.yang" was installed.
[INF] File "unicloud-config-vmme@2012-09-20.yang" was installed.
[INF] File "unicloud-config-ipsec@2018-04-20.yang" was installed.
[INF] File "unicloud-config-route@2012-09-20.yang" was installed.
[INF] File "unicloud-config-route-debug@2012-09-20.yang" was installed.
[INF] File "unicloud-config-network@2012-09-20.yang" was installed.
[INF] File "unicloud-config-lte@2012-09-20.yang" was installed.
[INF] File "unicloud-config-events@2015-01-30.yang" was installed.
[INF] File "unicloud-config-statistics@2015-01-30.yang" was installed.
[INF] File "unicloud-config-bandwidth-estimation@2012-09-20.yang" was installed.
[INF] File "unicloud-config-external-auth@2020-02-13.yang" was installed.
[INF] File "unicloud-config-audit@2020-02-11.yang" was installed.
[INF] File "unicloud-config-son@2012-09-20.yang" was installed.
[INF] File "unicloud-config-accessnode@2012-09-20.yang" was installed.
[INF] File "unicloud-config-son-cws@2012-09-20.yang" was installed.

After that sysrepoctl command is failing for every option, even yang uninstall also failing:
root@cpa-5bfc9b8988-nc6bt:/sysrepo/examples/yang# sysrepoctl -l -v3
[ERR] Invalid character sequence "input;", expected a keyword followed by a separator. (Line number 1301.)
[ERR] Parsing submodule failed.
[ERR] Including "unicloud-config-accessnode" submodule into "unicloud-config" failed.
[ERR] Parsing module "unicloud-config" failed.
[ERR] Loading "unicloud-config" module failed.
sysrepoctl error: Failed to connect (libyang error)

root@cpa-5bfc9b8988-nc6bt:/sysrepo/examples/yang# sysrepoctl -u unicloud-config -v3
[ERR] Invalid character sequence "input;", expected a keyword followed by a separator. (Line number 1301.)
[ERR] Parsing submodule failed.
[ERR] Including "unicloud-config-accessnode" submodule into "unicloud-config" failed.
[ERR] Parsing module "unicloud-config" failed.
[ERR] Loading "unicloud-config" module failed.
sysrepoctl error: Failed to connect (libyang error)

and only solution to recover from problem is reboot the system.

I check line 1301 in "unicloud-config-accessnode.yang". But this line has nothing special it has description of leaf.
If at all I delete some blank lines from the file (before 1301 lines), next time I get this issue on same line.
Does it mean datastore is crashed after sysrepoctl install?

**Comment by michalvasko** [comment]
What *sysrepo* version are you using? Also, what @jktjkt said, please provide the YANG files, if you can. Otherwise you can send them to me privately but I will not be able to fix this without the YANG modules.

> Does it mean datastore is crashed after sysrepoctl install?

I would not call it a "crash" but yes, it is not usable anymore, which is a critical problem.

**Comment by tatyakadam** [comment]
Thanks @michalvasko & @jktjkt for response.

- I am trying to use sysrepo for my product, and for that I need to install all already available yang modules. Some of them getting installed after reordering of include order. So, answer to your question yes, I am modifying these yang files in place, replacing/deleting/adding new yang files.
- Sysrepo version: libsysrepo v2.2.73 (SO v7.14.32) ataken from https://github.com/sysrepo/sysrepo.git
- About sharing the yang file, I am not able to share it as they are used for product. But schematic will share over mail.

**Comment by tatyakadam** [comment]
I think I got the issue.
Issue here is I have define input without as empty and its expected some keyword (may be description/type etc.).

Original:
                    tailf:action remove {
                        description "Remove all PKI certificate files.";
                        tailf:actionpoint cws-pki-remove;
                        tailf:hidden engg;

                        **input { }**

                        output {
                            leaf result {
                                tailf:cli-drop-node-name;
                                type string;
                            }
                        }
                    }

Fix:
                    tailf:action remove {
                        description "Remove all PKI certificate files.";
                        tailf:actionpoint cws-pki-remove;
                        tailf:hidden engg;

                        **input {description "i am input";}**

                        output {
                            leaf result {
                                tailf:cli-drop-node-name;
                                type string;
                            }
                        }
                    }

So my all yang are got installed except submodule 'unicloud-config-bandwidth-estimation'.
@michalvasko may be you can ignore previous errors as I am able to solve them. Can you please help me with below error:

**Comment by michalvasko** [comment]
So `input { }` actually was allowed by `input;` not, so I have fixed that. As for the next issue, I cannot help you because no relevant error is printed, can you provide just the submodule exactly as you are installing it? Also, I have managed to install the modules you have sent me so if you are modifying them after they are installed, you are on your own because you must not do that.

**Comment by tatyakadam** [comment]
Ok, for input { } fix do I need to use devel branch? And possibly when it will be available in master.

For next issue I have already provided that module over mail.
You just need to add 'include unicloud-config-bandwidth-estimation;' in unicloud-config.yang. Then while insalling this, I see get the error.

**Comment by michalvasko** [comment]
> Ok, for input { } fix do I need to use devel branch? And possibly when it will be available in master.

Yes, it is in `devel` only for now. Hard to say when the next release will be, most likely at the beginning of the next month.

> You just need to add 'include unicloud-config-bandwidth-estimation;' in unicloud-config.yang.

It is already there in the modules I have received.

**Comment by tatyakadam** [comment]
Sorry, my bad. 
I was twice including the same module that was this error.
Now I am ok.
Thanks for your support.
