### ISSUE TITLE
Use case of SR_ERR_CALLBACK_SHELVE

### ISSUE THREAD

**Issue by Vinay-Nayak-444** [sysrepo/sysrepo#3118]
In the documentation, it is mentioned that operational subscription callback can return SR_ERR_CALLBACK_SHELVE.
can you mention what is exact use case of this return value. How in future it can acknowledge to the corresponding sr_get_* api call ?

**Comment by michalvasko** [comment]
The return value will cause the callback not to return anything and the originator will keep waiting for it until its timout elapses. To prevent that you should ideally call `sr_subscription_process_events()` manually, which will execute the callback again giving it a chance to return `SR_ERR_OK` and the operational data in your case.
