### ISSUE TITLE
sysrepo on devel branch failing to build, whereas on masteer branch it works

### ISSUE THREAD

**Issue by tatyakadam** [sysrepo/sysrepo#3120]
sysrepo on devel branch failing to build, whereas on masteer branch it works

root@cpa-5bfc9b8988-txl4g:/sysrepo/build# cmake -DNACM_RECOVERY_USER=admin -DNACM_SRMON_DATA_PERM=777 -DCMAKE_CXX_COMPILER:PATH=/usr/bin/clang -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
-- ietf-yang-library revision: 2019-01-04
-- Conditional variable implementation: sr_cond_futex
-- Sysrepo repository: /sysrepo/build/repository
-- Startup data path:  /sysrepo/build/repository/data
-- Factory-default data path: /sysrepo/build/repository/data
-- Notification path:  /sysrepo/build/repository/data/notif
-- YANG module path:   /sysrepo/build/repository/yang
-- SR plugins path:    /usr/lib/x86_64-linux-gnu/sysrepo/plugins
-- SRPD plugins path:  /usr/lib/x86_64-linux-gnu/sysrepo-plugind/plugins
CMake Warning at CMakeLists.txt:299 (message):
  valgrind executable not found! Disabling memory leaks tests.

-- Could NOT find CMocka (missing: CMOCKA_LIBRARIES CMOCKA_INCLUDE_DIR) (Required is at least version "1.0.1")
-- Disabling tests because of missing CMocka
-- Could NOT find Uncrustify (missing: UNCRUSTIFY) (Required is at least version "0.77")
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find LibYANG: Found unsuitable version "2.36.1", but required is
  at least "2.37.5" (found /usr/local/lib/libyang.so)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:592 (_FPHSA_FAILURE_MESSAGE)
  CMakeModules/FindLibYANG.cmake:86 (find_package_handle_standard_args)
  CMakeLists.txt:392 (find_package)

-- Configuring incomplete, errors occurred!
See also "/sysrepo/build/CMakeFiles/CMakeOutput.log".
See also "/sysrepo/build/CMakeFiles/CMakeError.log".
root@cpa-5bfc9b8988-txl4g:/sysrepo/build# git branch
* devel
  master
root@cpa-5bfc9b8988-txl4g:/sysrepo/build#

I have taked libnag from 'https://github.com/CESNET/libyang' on master branch

**Comment by jktjkt** [comment]
At times, sysrepo's `devel` requires the `devel` branch of libyang as well. Now is one of these times :).
