### ISSUE TITLE
enum integer value is not getting in callback 

### ISSUE THREAD

**Issue by tatyakadam** [sysrepo/sysrepo#3123]
I am trying to get enum data using 'sr_get_change_next(session, it, &oper, &old_value, &new_value))'
But new_value here return enum name instead of integer value.

How can I get actual enum integer value with above API?

**Comment by jktjkt** [comment]
Call [`sr_get_change_tree_next`](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__change__subs__api.html#ga395d678bb45b1eca617b3b29e592015e) and use libyang API to get the numeric value. Also see #2003.
