### ISSUE TITLE
operational get is received twice during action "download" for bbf-software-management.yang

### ISSUE THREAD

**Issue by patilsoumya5** [sysrepo/sysrepo#3124]
Hi Team,

during software image "download" action rpc, operational_get is received twice.
We would like to understand why this is invoked twice and is there a way to avoid the second call as we understand during the first operational get, sysrepo tries to get the datastore details required for invoking action-rpc.

Thanks & Regards,

**Comment by michalvasko** [comment]
The first time for `input` validation, the second time for `output` validation. If the same data were used for both there could be data races in case the data changes. Moreover, different data may be required for validating input and output.

**Comment by patilsoumya5** [comment]
Thank you for the prompt response
