### ISSUE TITLE
Queries related to yang leafref modification or deletion

### ISSUE THREAD

**Issue by madhukarkumarpuresoftware** [sysrepo/sysrepo#3127]
Hi @michalvasko , @jktjkt,

If a yang module "A" has the has leafref, referring to yang module "B". How it will impact if we perform below two actions separately.

1. Changed the content of referred leaf of yang module "B".
    - Will this allowed to update new value? Is the Yang Module "A" will block this happen.
2. Delete the whole leaf of yang module "B".
    - Is this allowed. Any dependency on "instance-required".

**Comment by madhukarkumarpuresoftware** [comment]
Hi @jktjkt, please help with the above issues

**Comment by jktjkt** [comment]
Have you tried this, and what behavior did you see?

**Comment by madhukarkumarpuresoftware** [comment]
Observation:

1.    Changed the content of referred leaf of yang module "B".
        Yang Module "A" is block this to happen.
2.    Delete the whole leaf of yang module "B".
        Is fails complaining that it is used in yang module "A"

**Comment by madhukarkumarpuresoftware** [comment]
@jktjkt, Can you please help !!!

**Comment by michalvasko** [comment]
So what exactly is the problem? As long as the leafref is not mandatory, you should be free to simply remove it. But yes, you cannot remove just the leafref target, then the validation will fail, which is exactly how a leafref is supposed to work.
