### ISSUE TITLE
"no matching subtype found" with netcard name with "-" for ipv6

### ISSUE THREAD

**Issue by fei15115** [sysrepo/sysrepo#3128]
Hi ,
     When I try to push the xml like as below:
```xml
<tcp-client-parameters>
<remote-address>fe80::6a27:1aff:feb4:e86c%eth-oran</remote-address>
 <remote-port>4334</remote-port>
                            <keepalives>
                                <idle-time>1</idle-time>
                                <max-probes>10</max-probes>
                                <probe-interval>5</probe-interval>
                            </keepalives>
                        </tcp-client-parameters>
```
will get below error:
```
libyang error: Invalid union value "fe80::6a27:1aff:feb4:e86c%eth-oran" - no matching subtype found. (Data location "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='default-client']/endpoints/endpoint[name='default-ssh']/ssh/tcp-client-parameters/remote-address", line number 10.)
```

Here is some yang as below:
    
![image](https://github.com/sysrepo/sysrepo/assets/37013076/7b30792e-61f1-430a-81e5-fd0d4cfa2861)
![image](https://github.com/sysrepo/sysrepo/assets/37013076/997d0053-e3f0-4ea5-a0a8-e87f879e654a)
![image](https://github.com/sysrepo/sysrepo/assets/37013076/edebe2a2-3fc8-44ba-ab72-7bdd96720875)
![image](https://github.com/sysrepo/sysrepo/assets/37013076/d703ee09-980a-4e50-b60d-64ef81cbdf2d)

**Comment by michalvasko** [comment]
Not sure where you got the YANG from, the one used by libyang (`ietf-inet-types@2013-07-15.yang`) has the pattern end `(%[\p{N}\p{L}]+)?` which does not allow the character `-` there so there is not much I can do about it.
