### ISSUE TITLE
sr_validate() API fails when we trying to set a leaf from an augmented yang

### ISSUE THREAD

**Issue by alexeimerk** [sysrepo/sysrepo#3129]
Hello Michael,
As the title says, we are using the sr_validate() API and it fails when we try to set a leaf from **augmented** yang. (error: element not found, but applying changes works as expected). Do you have a solution for this case or do you know about it?
We noticed the following behavior: when we enter a specific module name for validating, we get an error: element not found, but if we enter NULL as the module name, the validation succeeds.

**Comment by jktjkt** [comment]
Please provide the YANG models that you're using, the initial data that have been already committed, the edit that you're trying to perform, and the module name that -- if passed to `sr_validate()` -- fails to validate.

**Comment by michalvasko** [comment]
Yes, I think you will have to provide all the information about the input because my simple tests based on your description worked fine.
