### ISSUE TITLE
[request] ignore unknown nodes during model downgrade

### ISSUE THREAD

**Issue by tbsuht** [sysrepo/sysrepo#3133]
My problem and possible request is similar to this issue: https://github.com/sysrepo/sysrepo/issues/1170

We need to provide a downdate mechanism in our software which also means we need to be able to downdate from one YANG model version to an older one.

After using `--export`, installing the old model again and using `--import` you will typically run into an error like this:
```
libyang error: Node "..." not found as a child of "..." node. (Data location "/...", line number X.)
sysrepocfg error: Data parsing failed
For more details you may try to increase the verbosity up to "-v3".
```

Now probably we can do the import ourselves and ignore unknown nodes, but it would be nicer if sysrepo can handle this for us. So my question: would it be possible to add this as an opt-in for using `--import` to ignore nodes for such a downdate scenario? Something like `--ignore-unknown-nodes`?

**Comment by michalvasko** [comment]
Use the `-n`, `--not-strict` option, description in the usage `sysrepocfg -h`.

**Comment by tbsuht** [comment]
Well, that was easy. :)

Thanks!
