### ISSUE TITLE
Error msg for callback registered in sr_module_change_subscribe()

### ISSUE THREAD

**Issue by grishina-olga** [sysrepo/sysrepo#3134]
Hi,

Is it opssible to set error msg for callback registered in sr_module_change_subscribe?
For example, I have a callback configChangeCb(), which on some case on event SR_EV_CHANGE returns SR_ERR_VALIDATION_FAILED. Is it posssible to add error msg together with error code? It is the better way to clarify for netconf-cli what exactluy went wrong during validaiton.

Thank you in advance!

BR, Olga
SW Engineer

**Comment by naziaC** [comment]
I believe you can use [sr_session_set_error_message()](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__utils__error__format.html#ga0ff87e057324746e72f7da6f6f639dc9) or [sr_session_set_netconf_error()](https://netopeer.liberouter.org/doc/sysrepo/devel/html/group__conn__sess__api.html#ga091e74235400197af14cd548df8d6fa8) for that.
