### ISSUE TITLE
Error during convert data notification from json to libyang format

### ISSUE THREAD

**Issue by Emilka1604** [sysrepo/sysrepo#3135]
Hi, Michal! I am trying convert notification data from json format to libyang format via libyang function lyd_parse_data_mem. As result I received the folowing error log:
```
            libyang[0]: Unexpected notification element "alarm-notif". (path: Schema location "/o-ran-fm:alarm-notif", line number 2.)
```
target json:
```json
             {"o-ran-fm:alarm-notif": 
	              { "fault-id": 1001,
	                "fault-source": "sda1",
	                "affected-objects": [ {  "name": "Firmware" } ], 
	                "fault-severity": "WARNING", 
	                "is-cleared": false,
                        "event-time": "2023-08-16T15:18:38Z", 
                        "fault-text": "Disk space limit"}
              }
```
target yang-module: https://gerrit.o-ran-sc.org/r/c/oam/+/2759/2/features/devicemanager/o-ran/ru-fh/provider/src/main/yang/o-ran-fm.yang

library versions: Sysrepo  v2.2.36
                          libnetconf2    v2.1.28
                          netopeer-2    v2.1.49
                          libyang    v2.1.30

Please, could you consider this issue and try to help with it.

**Comment by michalvasko** [comment]
Try using `lyd_parse_op()` instead.

**Comment by Emilka1604** [comment]
Thanks for your answer! I have several questions.

1) When I try to define ly_in struct I receive message that ly_in is incomplete type, may be there is some function which return ly_in object allocating on heap? Unfortunately I have not access to ly_in docs page. 

2) In documentation it is writen that LYD_TYPE_NOTIF_NETCONF maintain only xml input format, Do I truly understand that I should use LYD_TYPE_RPC_RESTCONF if I want json input format? When I try to use LYD_TYPE_RPC_RESTCONF I receive the folowing compile error: 'LYD_TYPE_NOTIF_RESTCONF' was not declared in this scope; did you mean 'LYD_TYPE_NOTIF_NETCONF'

3) Can LY_IN_TYPE::LY_IN_MEMORY be used for reading input from char buffer?

**Comment by michalvasko** [comment]
1. Naturally, there are `ly_in_new_filepath()`, `ly_in_new_memory()`, ...
2. Perhaps you are using an old *libyang* version? The type is defined in the current one.
3. Yes, that is what that particular input handler is for.

**Comment by Emilka1604** [comment]
Is LYD_TYPE_NOTIF_RESTCONF presence in libyang v2.1.30?

**Comment by michalvasko** [comment]
You could have learnt that yourself but it has been added in version 2.1.79.

**Comment by Emilka1604** [comment]
Thanks! Consequently, I should upgrade to this version to solve my issue?

**Comment by michalvasko** [comment]
Well, obviously. You can simply use the latest release, which is v2.1.80.

**Comment by Emilka1604** [comment]
Okey, Thanks for your advises one more time!
