### ISSUE TITLE
Increase in startup time due to sr_install_modules2

### ISSUE THREAD

**Issue by PravalliSure** [sysrepo/sysrepo#3138]
Hello Mikhal,
We have 35 yang modules in our system and we are installing them and enabling corresponding features during startup. We were working off of [v2.0.53](https://eos2git.cec.lab.emc.com/Mobile-Phoenix/sysrepo/releases/tag/v2.0.53) and it used to take 90sec to load all yang modules and enable features. We used sr_install_module and sr_enable_feature APIs in a loop.

We recently upgraded to Sysrepo [v2.2.60](https://eos2git.cec.lab.emc.com/Mobile-Phoenix/sysrepo/releases/tag/v2.2.60) and we are using sr_install_modules2 with all yang modules and features enabled in the same API. But startup time has increased to 3 minutes.

Any leads as to why this increase in startup time would be helpful.

**Comment by michalvasko** [comment]
The version jump is way too big for me to able to pinpoint the exact reason. In general, there most likely need to be performed more tasks that were in the old version so it takes longer. If you want to provide the YANG modules, I can look at your exact use-case but I do not think there is much to optimize.

**Comment by PravalliSure** [comment]
This is the list
ietf-netconf-monitoring.yang 
ietf-netconf-nmda.yang 
nc-notifications.yang
notifications.yang 
ietf-x509-cert-to-name.yang 
ietf-crypto-types.yang
ietf-keystore.yang 
ietf-truststore.yang 
ietf-tcp-common.yang 
ietf-ssh-server.yang 
ietf-tls-server.yang 
ietf-netconf-server.yang 
ietf-network-instance.yang 
ietf-subscribed-notifications.yang 
ietf-yang-push.yang
o-ran-compression-factors.yang 
o-ran-wg4-features.yang 
o-ran-module-cap.yang
ietf-inet-types.yang 
ietf-yang-types.yang 
iana-hardware.yang 
ietf-hardware.yang
o-ran-hardware.yang 
ietf-interfaces.yang 
iana-if-type.yang
ietf-ip.yang 
o-ran-interfaces.yang
o-ran-processing-element.yang
o-ran-uplane-conf.yang 
o-ran-ecpri-delay.yang
o-ran-lbm.yang 
o-ran-mplane-int.yang 
ietf-dhcpv6-types.yang 
o-ran-dhcp.yang
o-ran-transceiver.yang 
ietf-netconf-acm.yang 
o-ran-usermgmt.yang
o-ran-file-management.yang 
o-ran-software-management.yang 
o-ran-ald-port.yang
o-ran-ald.yang 
o-ran-operations.yang 
o-ran-sync.yang 
o-ran-fm.yang 
o-ran-supervision.yang
o-ran-performance-management.yang 
o-ran-delay-management.yang 
o-ran-trace.yang
o-ran-antenna-calibration.yang

**Comment by michalvasko** [comment]
Like I said, you would have to provide the actual YANG modules (ideally in an archive with a script that installs them all using `sysrepoctl` or your own small app) if you want me to look at this considering I doubt there is much to optimize.

**Comment by PravalliSure** [comment]
We are not seeing this anymore. I think previous observation was an aberration.
