### ISSUE TITLE
Get Error Message from Sysrepo Plugin

### ISSUE THREAD

**Issue by nullromo** [sysrepo/sysrepo#3140]
Sorry if this is a simple question, but is there a recommended method for propagating error messages out of a plugin?

### Background
For example, in my application code I have

```c
rc = sr_apply_changes(session, 0);
```

And then in the plugin

```c
int networkSettingsCallback(...) {
    if (/* IP address is not valid */) {
        // return an error message somehow
    } else if (/* IP address is already taken */) {
        // return an error message somehow
    } else if (/* some other error occurred */) {
        // return an error message somehow
    }
    return SR_ERR_OK;
}
```
```c
sr_module_change_subscribe(session, xpath, networkSettingsCallback, NULL, 0, SR_SUBSCR_DEFAULT, &subscription);
```

The best I'm going to get is an `int` back, but what I really want is a string so that I can tell what went wrong.

### Current workaround

I can define a bunch of custom codes and custom messages

```c
#define MY_ERROR_1   100
#define MY_MESSAGE_1 "Invalid IP address"
#define MY_ERROR_2   101
#define MY_MESSAGE_2 "IP address already in use"
#define MY_ERROR_3   102
#define MY_MESSAGE_3 "Something else"
```

But this is tedious and kind of difficult to maintain. So I was just wondering if there is a way to pass strings between a plugin and an application.

**Comment by michalvasko** [comment]
Use [sr_session_set_netconf_error()](https://github.com/sysrepo/sysrepo/blob/master/src/utils/error_format.h).

**Comment by nullromo** [comment]
Thank you, I hadn't seen this before. I had to update my sysrepo to the latest `master` version to get this feature.

However, when I tried to retrieve the error back, it was null. Do you know why this could occur?

### Example Code

```c
const sr_error_info_t* errorInfo;

printf("setting netconf error\n");
rc = sr_session_set_netconf_error(session, "application", "operation-failed", NULL, NULL, "my message", 0);
if (rc != SR_ERR_OK) {
    printf("could not set netconf error\n");
    return rc;
}
printf("set netconf error\n");

printf("getting netconf error\n");
rc = sr_session_get_error(session, &errorInfo);
if (rc != SR_ERR_OK) {
    printf("could not get netconf error\n");
    return rc;
}
printf("got netconf error\n");

if (errorInfo == NULL) {
    printf("null error :(\n");
}
printf("%d errors\n", errorInfo->err_count);
```

### Example Output

```
setting netconf error
set netconf error
getting netconf error
got netconf error
null error :(
Segmentation fault
```

**Comment by nullromo** [comment]
Update: it's working correctly when I try to read the error on the application side. I call `sr_apply_changes()`, which triggers the plugin code, then the plugin code calls `sr_session_set_netconf_error()` and returns an error code, then the application checks the error code, retrieves the error with `sr_session_get_error()` and prints out the data using `sr_err_get_netconf_error()`. So all is working properly in that regard. I just want to know now why the error doesn't get "applied" on the session until after the plugin is done.

**Comment by jktjkt** [comment]
>  I just want to know now why the error doesn't get "applied" on the session until after the plugin is done.

What do you mean by "applied" here? These errors are set by the "other end" of the connection when a session is requesting some action. If that action fails, that party which tried to "take care" of that action is supposed to set the error info. That way, the error is always reported to the originating session. Maybe I do not understand the use case (or your expectations). How do you expect this to work?

**Comment by nullromo** [comment]
It works properly. I just wrongly assumed that "set" followed by an immediate "get" on the same session object should return some data instead of null. I was just doing this as a sanity check. Instead, I needed to do the "get" part on the "other end" as you mentioned.

Thanks for the additional explanation.

**Comment by michalvasko** [comment]
It is documented what each function does and especially always mentioned what `session` is expected. To read back the error data you just set, you can use `sr_session_get_orig_data()` but that is a generic function expecting you to know the exact format of the pushed error data, which is not really public.
