### ISSUE TITLE
Sysrepo thinks there is no target for a leafref when there is

### ISSUE THREAD

**Issue by nullromo** [sysrepo/sysrepo#3141]
# Summary

I tried to install a YANG module with some initial data for a node that has a `leafref` restriction. The restriction is met, but sysrepo thinks it is not met and has an error.

# Versions

Latest `devel` branch version of libyng, libnetconf2, and sysrepo.

This process was working on an old version of sysrepo (2.1.84) and it started failing when I updated today.

# Steps to Reproduce

1. Create the example files below

#### my-test.yang

```yang
module my-test {
    yang-version 1.1;
    namespace 'urn:my-test';
    prefix my-test;

    import ietf-netconf-acm {
        prefix nacm;
    }

    organization '';
    contact '';
    description "";
    revision 2023-08-23 {
        description '';
    }

    container top {
        leaf my-node {
            description '';
            type leafref {
                path '/nacm:nacm/nacm:groups/nacm:group/nacm:name';
            }
            mandatory true;
        }
    }
}
```

#### initial.xml

```xml
<nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
    <groups>
        <group>
            <name>default</name>
        </group>
    </groups>
</nacm>
```

#### test.xml

```xml
<top xmlns="urn:my-test">
    <my-node>default</my-node>
</top>
```

2. Clean sysrepo: `sudo rm -rf /dev/shm/sr_*`, `sudo rm -rf /dev/shm/srsub_*`, `sudo rm -rf /etc/sysrepo/`
3. Import the initial nacm data: `sudo sysrepocfg --import=./initial.xml --module=ietf-netconf-acm --datastore=startup -v3`
4. Copy the data to the running datastore: `sudo sysrepocfg --copy-from startup`
5. Export the data to make sure it's there: `sudo sysrepocfg --export --xpath "/ietf-netconf-acm:nacm/groups/group[name='default']"`. It should show an entry in the `groups` list named `default`.
6. Attempt to install the test yang module: `sudo sysrepoctl --install ./my-test.yang --init-data=./test.xml -v3`. It fails with the following error:
```
[INF] Connection 7 created.
[ERR] Invalid leafref value "default" - no target instance "/nacm:nacm/nacm:groups/nacm:group/nacm:name" with the same value. (Data location "/my-test:top/my-node".)
sysrepoctl error: Failed to install modules (Validation failed)
```

It says there's no target instance for the xpath `/ietf-netconf-acm:nacm/groups/group[name='default']`, but there is.

**Comment by michalvasko** [comment]
I have update the error so that it is clear which is the affected datastore, the error is valid. The core of the problem is that the initial data are used for all the datastores including factory-default. But I do not really see any improvement here since its support is not optional. If you require installing such a module, set the factory-default data of `ietf-netconf-acm` as well.

**Comment by nullromo** [comment]
Hi Michal,
Thanks for the reply. The factory-default datastore is new since I last updated sysrepo, so I have been reading about it. It took me a while, but I finally found in #3079 that you need to bake in the factory-default data at compile time.

As always, I greatly appreciate your help!

_For anyone else that reads this:_
_1. Create `initial.xml`_
_2. Compile sysrepo with `-DINTERNAL_MODULE_DATA_PATH=<path/to/initial.xml>`_
_3. Now the data for the factory-default datastore will be set to whatever was in `initial.xml`, and you can't change it during runtime_

**Comment by michalvasko** [comment]
Glad you figured it out, I will just add that you need to specify the data in compile-time only for internal modules (which `ietf-netconf-acm` is).
