### ISSUE TITLE
Error while loading oven Yang Module using sysrpeoctl

### ISSUE THREAD

**Issue by hrmnboparai** [sysrepo/sysrepo#3142]
I tried to load the oven yang module but it is showing error blaming some another module that I installed earlier but removed it afterwards. That module is not present in sysrepoctl installed modules but still I see an error blaming that module
![errCtl](https://github.com/sysrepo/sysrepo/assets/60837282/78ea4523-438d-46af-a408-3e026175b49d)

**Comment by michalvasko** [comment]
Is it perhaps still an import of another installed module? Also, I assume you have modified it after installing because *sysrepo* should not allow you to install an invalid module.

**Comment by hrmnboparai** [comment]
Yes I installed a module named gigamesh earlier. I tried and it was running fine with edit-config and get operation. Then I created a sysrepo-plugin which used the operation sr_get_data() and sr_edit_batch. After that I am started seeing these two errors.
![err](https://github.com/sysrepo/sysrepo/assets/60837282/53490eb6-7b9f-42c1-92fd-6bbffd0ba37f)
![errCtl](https://github.com/sysrepo/sysrepo/assets/60837282/eeeb505f-e2cc-4147-9793-211093515711)

**Comment by hrmnboparai** [comment]
I figured it out. It was some mistake from my end. Oven module now installed correctly. Thanks
