### ISSUE TITLE
How to get unique identifiers for netopeer client subscriptions

### ISSUE THREAD

**Issue by mustafatayf** [sysrepo/sysrepo#3148]
Hi,

We are trying to manage subscriptions for `o-ran-supervision`  notification. Here what we do;

- A notification callback is used to create a new record for subscription and assign a **_unique identifier_**. 
- A watchdog-reset callback is used to search sessions through existing records based on the **_unique identifier_**.
- There is a global subscription variable in `sr_subscription_ctx_t` type.

Callback mechanism is working without error. However, when we want to use session ID from `sr_session_ctx_t`'s `sid` as our **_unique identifier_**, the `sid` sequentially increased with each rpc from any session. 

According to sysrepo documentation and variable naming, we assumed that `sid` value had to be fixed for each individual session. 
- `sr_session_get_id()` function is used to get `sid` value from the first argument of callback functions `sr_rpc_tree_cb`, and session defined as **sr_session_ctx_t *session**.

On the other hand, libnetconf2 has an `nc_session_get_id()` function and there is also a _**session id**_ in the `nc_session` structure. We are not able to get **session id** from `nc_session` because of session types mismatches between `sr_session_ctx_t` and `nc_session`.

Here are the questions;
- Is it expected to change `sid` everytime or is there a problem with implementation or our coding?
- How can a subscription be uniquely identifiable among several sessions and connections?
- Is the nc_session ID and sid refer to the same data or nc_session is just for the **server-client connection**?
- If the entire server-client connection closes and a new session opens for each rpc by `netopeer2-cli`. How can we identify the connection from a given user?

Thanks in advance.
Regards

**Comment by michalvasko** [comment]
> Is it expected to change sid everytime or is there a problem with implementation or our coding?

SID changes because callbacks get temporary sessions existing only for the duration of the callback.

> How can a subscription be uniquely identifiable among several sessions and connections?

Every subscription has a unique `sub_id`, which is also passed to the callbacks.

> Is the nc_session ID and sid refer to the same data or nc_session is just for the server-client connection?

Every NETCONF session has a dedicated *sysrepo* session but that is an internal implementation detail that can change (it was not always like this). You cannot get to the *sysrepo* session anyway.

> If the entire server-client connection closes and a new session opens for each rpc by netopeer2-cli. How can we identify the connection from a given user?

If the connection is terminated and restored, it is a new connection (session) and is not related to the previous one in any way so you cannot really match them. Or did I misunderstand your question?

**Comment by mustafatayf** [comment]
Thank you Michal,

To be more clear, we have a development environment on local computer, which includes;

- All required libraries installed (sysrepo "7.19.3", libyang "2.38.14", libnetconf2 "3.6.1", netopeer2 "2.1.71")
- A netopeer2-server running on console
- A netopeer2-cli running on console
- Developing sysrepo-plugin application on the C development IDE*

*`sub_id` values are observed from the IDE.

When we try to use `sub_id` as an identifier for **o-ran-supervision** subscription on the **supervision-notification** by using;
` subscribe --stream o-ran-supervision `
Client subscription request get `sub_id` of **61**. After a while, from the same client session on **netopeer2-cli**, following RPC is send;
`user-rpc --rpc-timeout 9999`
and callback function on the netopeer2-server side get `sub_id` of **62**.
![resim](https://github.com/sysrepo/sysrepo/assets/127930286/baa8bca4-b4a9-40e8-bb8f-c9c88a9f37c2)

Similarly, first client command (**subscribe**) has session ID of `sid=81` and the second command (**user-rpc**)  has a session ID of `sid=83`. So that each rpc has own session ID and `sub_id`, which are sequentially incremented by **1** or more if any further session or subscription appeared in the background. 

We are expecting each unique subscription to have the same `sub_id`, but what we see `sub_id` is changing for the same subscription.

We are trying to distinguish user-rpcs from each other so that we can manage counters for watchdog-reset timers belonging to different subscriptions.

Given identifiers (`session ID, sid` and `sub_id`) are changing, is there any other way to match incoming user-rpcs with their subscriptions on the netopeer2-server side?

Thank you,
mustafa

**Comment by michalvasko** [comment]
> We are expecting each unique subscription to have the same sub_id, but what we see sub_id is changing for the same subscription.

What is a **subscription**? You are using it in a really confusing way and I have no idea what you mean. What I assumed is that a subscription is a notification subscription created by a client, using `subscribe` command in the CLI, for example. If you then send a `user-rpc`, it has nothing to do with any subscription, you have simply sent another RPC on the NETCONF session. So you may want to clarify what you are trying to do, match all the **RPCs** of a NETCONF session?

**Comment by mustafatayf** [comment]
> What I assumed is that a subscription is a notification subscription created by a client, using subscribe command in the CLI

We are exactly doing this.

>  If you then send a user-rpc, it has nothing to do with any subscription, you have simply sent another RPC on the NETCONF session

We assumed that for a given NETCONF connection, which are created by;
```
$ netopeer2-cli
> connect 
> status
```
has an unique identifier in order to be used on the netopeer2-server side.
![resim](https://github.com/sysrepo/sysrepo/assets/127930286/1ede1174-da53-488a-9ce0-d946e0f008ab)

Now it is clear that each rpc has its own session and sub_id values. We need to distinguish multiple client and their user rpcs on the netopeer2-server side.

Each client its his own watchdog timers on the netopeer2-server side. Depending on the user rpcs coming from the clients, only the corresponding timers should be set/reset on the netopeer2-server.

Therefore, is there a way to identify the owner (client) of the user-rpcs on the netopeer2-server side?

**Comment by michalvasko** [comment]
Okay, I think I understand now although you are still using some ambiguous terms. Every NETCONF client has its own NETCONF session ID, you can read it in every [callback](https://github.com/CESNET/netopeer2/#sysrepo-callbacks) using `sr_session_get_orig_data()`.

**Comment by mustafatayf** [comment]
Thank you Michal, `sr_session_get_orig_data()` is worked for me.
