### ISSUE TITLE
Internal error (sysrepo/src/shm_sub.c:4532).

### ISSUE THREAD

**Issue by maksim3vium** [sysrepo/sysrepo#3151]
Hi Michal,

I have got an internal error in **sr_shmsub_notif_listen_process_module_events**  (sysrepo 2.2.73).
I added debug logs (DEBUG) to check values.
It seems there is a race condition:
sometimes **sr_shmsub_multi_notify_write_event** updates **multi_sub_shm->request_id** before **sr_shmsub_notif_listen_process_module_events** is completed.

EV ORIGIN: "ietf-netconf-notifications" "notif" ID 1 priority 0 for 1 subscribers published.
EV LISTEN: "ietf-netconf-notifications" "notif" ID 1 processing.
DEBUG: multi_sub_shm->event = 10
DEBUG: multi_sub_shm->request_id = 1, notif_subs->request_id = 1
....
EV LISTEN: "ietf-netconf-notifications" "notif" ID 2 processing.
DEBUG: multi_sub_shm->event = 10
DEBUG: multi_sub_shm->request_id = 2, notif_subs->request_id = 2
EV LISTEN: "ietf-netconf-notifications" "notif" ID 2 priority 0 success (remaining 0 subscribers).
EV LISTEN: "ietf-netconf-notifications" "notif" ID 3 processing.
....
EV ORIGIN: "ietf-netconf-notifications" "notif" ID 4 priority 0 for 1 subscribers published.
DEBUG: multi_sub_shm->event = 10
DEBUG: **multi_sub_shm->request_id = 4, notif_subs->request_id = 3**
Internal error (sysrepo/src/shm_sub.c:4532).

**Comment by michalvasko** [comment]
Can you reproduce the problem with the latest release or `devel` branch? I could have been fixed.

**Comment by amitdalodiya** [comment]
this issue resolved or reproduced @ [maksim3vium]. let me know if fixed with any version

**Comment by maksim3vium** [comment]
Hi @amitdalodiya ,

I have not checked it with the latest sysrepo.
Currently, I fixed it by replacing "multi_sub_shm->request_id" with local variable request_id:

~~~
@@ -4528,7 +4528,7 @@ sr_shmsub_notif_listen_process_module_events(struct modsub_notif_s *notif_subs,

     /* no error/timeout should be possible */
     if ((ATOMIC_LOAD_RELAXED(multi_sub_shm->event) != SR_SUB_EV_NOTIF) ||
-            (ATOMIC_LOAD_RELAXED(multi_sub_shm->request_id) != ATOMIC_LOAD_RELAXED(notif_subs->request_id))) {
+            (request_id != ATOMIC_LOAD_RELAXED(notif_subs->request_id))) {
         SR_ERRINFO_INT(&err_info);
         goto cleanup_wrunlock;
     }
~~~
