### ISSUE TITLE
Queries related to stable version

### ISSUE THREAD

**Issue by AllenWang19940726** [sysrepo/sysrepo#3152]
I am doing some research on the YANG database.
So I want to know which stable build version I should choose to download, including libyang and sysrepo?

**Comment by michalvasko** [comment]
The stable version can be downloaded as the latest [github release](https://github.com/sysrepo/sysrepo/releases) and should always be equal to the `master` branch. It goes for all our projects (libyang, sysrepo, libnetconf2, and netopeer2).

**Comment by AllenWang19940726** [comment]
Thanks a lot. I will play on it.
