### ISSUE TITLE
delete item on "operational" possibly corrupted the datastore

### ISSUE THREAD

**Issue by LeandreBl** [sysrepo/sysrepo#3156]
Hi,

see [53](https://github.com/sysrepo/sysrepo-python/issues/53)

This is an edition of the bug, but in C

I encountered this while trying to delete a leaf-list (track-interface), without success, leading me to delete the parent node.

So I have a datastore "operational" containing:
```xml
...
<vrrp xmlns="urn:dummy:vrouter/vrrp">
  <name>vrrp1</name>
  <version>3</version>
  <link-interface>dummyp1</link-interface>
  <vrid>7</vrid>
  <track-link-interface>true</track-link-interface>
  <track-interface>dummyp1</track-interface>
  <track-interface>dummyp4</track-interface>
  <unicast-peer>
    <ip>10.100.0.2</ip>
  </unicast-peer>
  <virtual-address>
    <ip>10.100.0.4/24</ip>
  </virtual-address>
</vrrp>
...
```
This vrrp is not the root of the datastore, it's path is: `/router-vrrp:vrrp[name='vrrp1']`

Here is my problem

I did:
```c
#define _GNU_SOUretE

#include <inttypes.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include <sysrepo.h>

int main(void)
{
    sr_conn_ctx_t *connection = NULL;
    sr_session_ctx_t *session = NULL;
    int ret = SR_ERR_OK;


    sr_log_stderr(SR_LL_WRN);

    ret = sr_connect(0, &connection);
    if (ret != SR_ERR_OK) {
        fprintf(stderr, "Connection failed\n");
        sr_disconnect(connection);
        return 1;
    }

    ret = sr_session_start(connection, SR_DS_OPERATIONAL, &session);
    if (ret != SR_ERR_OK) {
        fprintf(stderr, "Session creation failed\n");
        sr_disconnect(connection);
        return 1;
    }

    ret = sr_delete_item(session, "/router-vrrp:vrrp[name='vrrp1']", 0);
    if (ret != SR_ERR_OK) {
        fprintf(stderr, "Delete item of parent node failed\n");
        sr_disconnect(connection);
        return 1;
    }

    ret = sr_apply_changes(session, 0);
    if (ret != SR_ERR_OK) {
        fprintf(stderr, "Apply parent node deletion failed\n");
        sr_disconnect(connection);
        return 1;
    }

    ret = sr_delete_item(session, "/router-vrrp:vrrp[name='vrrp1']/track-interface[1]", 0);
    if (ret != SR_ERR_OK) {
        fprintf(stderr, "Delete item of parent node failed\n");
        sr_disconnect(connection);
        return 1;
    }

    ret = sr_apply_changes(session, 0);
    if (ret != SR_ERR_OK) {
        fprintf(stderr, "Apply parent node deletion failed\n");
        sr_disconnect(connection);
        return 1;
    }

    sr_disconnect(connection);
    return 0;
}

```
gives (this is the entire output, not a single fprintf was triggered, so it might come from the sr_disconnect)
```
[ERR] JSON DS file: Unexpected character ":" after JSON string.
[ERR] Callback "load" of plugin "JSON DS file" for module "vrouter" failed.
```

There is obviously more stuff into that datastore, and the path should be longer but I do not think it's useful to expose it.

Not only my C code, but `sysrepocfg` (from the python binding) too:
```sh
$ sysrepocfg --export --datastore operational -v3
```
gives
```
[INF] Connection 55 created.
[INF] Session 1410 (user "root", CID 55) created.
[INF] EV ORIGIN: "/ietf-netconf-acm:nacm/denied-operations" "oper get" index 0 ID 13 published.
[INF] EV ORIGIN: "/ietf-netconf-acm:nacm/denied-operations" "oper get" index 0 ID 13 succeeded.
[INF] EV ORIGIN: "/ietf-netconf-acm:nacm/denied-data-writes" "oper get" index 0 ID 13 published.
[INF] EV ORIGIN: "/ietf-netconf-acm:nacm/denied-data-writes" "oper get" index 0 ID 13 succeeded.
[INF] EV ORIGIN: "/ietf-netconf-acm:nacm/denied-notifications" "oper get" index 0 ID 13 published.
[INF] EV ORIGIN: "/ietf-netconf-acm:nacm/denied-notifications" "oper get" index 0 ID 13 succeeded.
[INF] EV ORIGIN: "/sysrepo-monitoring:sysrepo-state/connection[cid='6']/nacm-stats" "oper get" index 0 ID 52 published.
[INF] EV ORIGIN: "/sysrepo-monitoring:sysrepo-state/connection[cid='6']/nacm-stats" "oper get" index 0 ID 52 succeeded.
[INF] EV ORIGIN: "/ietf-netconf-monitoring:netconf-state" "oper get" index 0 ID 13 published.
[INF] EV ORIGIN: "/ietf-netconf-monitoring:netconf-state" "oper get" index 0 ID 13 succeeded.
[INF] EV ORIGIN: "/nc-notifications:netconf" "oper get" index 0 ID 13 published.
[INF] EV ORIGIN: "/nc-notifications:netconf" "oper get" index 0 ID 13 succeeded.
[INF] EV ORIGIN: "/ietf-subscribed-notifications:streams" "oper get" index 0 ID 13 published.
[INF] EV ORIGIN: "/ietf-subscribed-notifications:streams" "oper get" index 0 ID 13 succeeded.
[INF] EV ORIGIN: "/ietf-subscribed-notifications:subscriptions" "oper get" index 0 ID 13 published.
[INF] EV ORIGIN: "/ietf-subscribed-notifications:subscriptions" "oper get" index 0 ID 13 succeeded.
[ERR] JSON DS file: Unexpected character ":" after JSON string.
[ERR] Callback "load" of plugin "JSON DS file" for module "vrouter" failed.
sysrepocfg error: Getting data failed (libyang error)
[INF] No datastore changes to apply.
```

I think the datastore is corrupted, and I have no idea how I can revert it, it seems that is comes from that last delete_item.

sysrepo version: master (2.2.105)
libyang version: master (2.1.111)

**Comment by michalvasko** [comment]
To reproduce and fix it, I will need the YANG module (you seem to have some custom one), ideally the full operational datastore data of the module (not just the snippet if there is more), and the way it has been set there (pull, push oper data or something else?).

**Comment by LeandreBl** [comment]
> Hi there,
> 
> This is the first time I see this `JSON DS file` plugin. Is that a custom libyang plugin that you have in house?

@rjarry I don't think so, I literally just cloned libyang and sysrepo et and did a make install for both



> To reproduce and fix it, I will need the YANG module (you seem to have some custom one), ideally the full operational datastore data of the module (not just the snippet if there is more), and the way it has been set there (pull, push oper data or something else?).

@michalvasko  I'm trying to reproduce it on a very small dataset, is there an easy cli way to copy a node from running to operational ?

**Comment by michalvasko** [comment]
> This is the first time I see this JSON DS file plugin. Is that a custom libyang plugin that you have in house?

Is now fairly old, must be half a year at least.

> I'm trying to reproduce it on a very small dataset, is there an easy cli way to copy a node from running to operational ?

If you subscribe to module changes, all the data subscribed this way will appear in the operational datastore.

**Comment by LeandreBl** [comment]
@michalvasko little update, so i tried with a tiny little sub version of our work tree, and I can't reproduce it. I now have 2 options:
- Take our current tree and rename everything so it stays anonymous.
- Take our current tree and shrink it, little by little to reproduce

For your question far above, the data where placed in `running` with `sysrepocfg --import=vrrp.json` and copied to operational with a subscription.

**Comment by michalvasko** [comment]
If you are fine with it, you can send all the required YANGs and data files to me privately via email so that I can reproduce it.

**Comment by LeandreBl** [comment]
Seems solved on branch devel for libyang/sysrepo.

Thanks michalvasko
