### ISSUE TITLE
Question: Is it possible for multiple processes to access the same module in operational datastore at the same time?

### ISSUE THREAD

**Issue by chakobaby** [sysrepo/sysrepo#3157]
This is the problem I'm facing now: If a process has made the connection and session to a module in operational datastore, it seems that other processes executed later will somehow be blocked (not able to write data into that module). And if I kill the first process, the later one will work normally as I expected. I'm guessing that's because the first process has locked the module. Is it normal? Is there any way for multiple processes to access the same module in operational datastore at the same time.

**Comment by jktjkt** [comment]
What kind of "access" is the first application making?

**Comment by michalvasko** [comment]
Having a session will never block anything and subscriptions should neither. Can you post the exact *sysrepo* API calls or whole code snippets? Also, what are the other processes attempting to do, you say "write data" meaning push some operational changes using `sr_apply_changes()`? Finally, mention the version of *sysrepo* that you are using.

**Comment by jktjkt** [comment]
> It's just there waiting for events to trigger it to write some values into the operational datastore. More specifically, it's a fault management application. If any defined fault occurs, it will fill up the fault information into the operational datastore.

Does it mean that there are no sysrepo subscriptions and that the app will use the [push model for operational data](https://netopeer.liberouter.org/doc/sysrepo/devel/html/#oper_data)?

How does the output of `strace` look like, and what is the full backtrace of all of your threads (e.g., `thread apply all backtrace` within `gdb`) of *both* processes when the blockage occurs?

**Comment by chakobaby** [comment]
Hi @jktjkt, sorry for the late reply and thanks for your answer. I found may problem might caused by some other reason rather than a sysrepo issue. Anyway, thanks for your help!
