### ISSUE TITLE
netopeer2 does not see all yang modules in sysrepo

### ISSUE THREAD

**Issue by xuoguoto** [sysrepo/sysrepo#3158]
Hello,

I have installed sysrepo (libsysrepo v2.2.105) and netopeer2 (2.1.71) and both are working fine. To test I first installed the oven model from the documentation. I used the command `sysrepoctl -i oven.yang` to install the model and I am able to work with it using `netopeer2-cli`. 

Moving ahead I tried  to install `ietf-snmp` module again using the command `sysrepoctl -i yang/standard/ietf/RFC/ietf-snmp.yang  -s yang/standard/ietf/RFC/` When I do `sysrepoctl -l| grep snmp` I get the output

```
ietf-snmp                     | 2014-12-10 | I     | user:user | 600           | ietf-snmp-common ietf-snmp-engine ietf-snmp-target ietf-snmp-notification ietf-snmp-proxy ietf-snmp-community ietf-snmp-usm ietf-snmp-tsm ietf-snmp-vacm ietf-snmp-tls ietf-snmp-ssh |  
```

When I try `status` in `netopeer2-cli` I can see `urn:ietf:params:xml:ns:yang:ietf-snmp?module=ietf-snmp&revision=2014-12-10` as one of the entries. 

But in [ANX](https://github.com/cisco-ie/anx) I get an error 
```
ietf-snmp@2014-12-10.yang tries to imports missing model: ietf-snmp-tsm, ietf-snmp-tls, ietf-snmp-target, ietf-snmp-usm, ietf-snmp-vacm, ietf-snmp-community, ietf-snmp-ssh, ietf-snmp-engine, ietf-snmp-notification, ietf-snmp-common, ietf-snmp-proxy
```

and ietf-snmp is not listed as one of the modules. I am not sure if this is a problem with sysrepo, but this is one place to start. How can I ensure that everything is right with sysrepo before moving to netopeer2 and ANX?

**Comment by michalvasko** [comment]
> How can I ensure that everything is right with sysrepo before moving to netopeer2

You can try executing `get-schema` on all the submodules of `ietf-snmp` but I am pretty sure it will work. The problem, most likely, is that ANX does not support submodules, nothing we can do about that.

**Comment by xuoguoto** [comment]
Thank you!

In the mean time, is  there any other project similar to ANX that can be used to play around with netconf?

**Comment by michalvasko** [comment]
Not sure, try to search for some `NETCONF GUI client`, there should be some freely available.

**Comment by xuoguoto** [comment]
Thank you.

**Comment by jktjkt** [comment]
There's an [interactive CLI](https://github.com/CESNET/netconf-cli) that you can build and use to connect to a NETCONF server. It's not a GUI, but you can use the `Tab` key to explore the YANG data tree that's made available by the server.

Also, if you think that the root cause is within ANX, please be sure to file a bugreport upstream -- preferably with the full communication log so that their developers have a chance to debug this.

**Comment by xuoguoto** [comment]
> > How can I ensure that everything is right with sysrepo before moving to netopeer2
> 
> You can try executing `get-schema` on all the submodules of `ietf-snmp` but I am pretty sure it will work. The problem, most likely, is that ANX does not support submodules, nothing we can do about that.

Used a python program to pull one of the leaf submodule and it's working fine as you have mentioned.

```python
from ncclient import manager

m = manager.connect(host='localhost', port=830, username='user', password='pass')

schema = m.get_schema('ietf-snmp-engine')
print (schema)
```

I will take this up with ANX. Thank you for the assistance!
