### ISSUE TITLE
How to get (sr_session_ctx_t *) session from (sr_subscription_ctx_t * ) subscription?

### ISSUE THREAD

**Issue by mustafatayf** [sysrepo/sysrepo#3163]
Hi,

We are trying to get the session information for a subscription inside a thread of sysrepo-plugin function.

Our design is as follows;

- There is a sysrepo-plugin initialization via **sr_plugin_init_cb()** function, which includes **sr_rpc_subscribe_tree()** function where I am defining sr_rpc_tree_cb callback argument as **supervision_create_sub_cb()**.
- **supervision_create_sub_cb()**  starts a new thread **_supervision_thread()_** function by using the pthread_create() for each new subscription.
- My goal is to send a notification to the client, who subscribed to the notification, from the **_supervision_thread()_** thread, which does not know any information about sysrepo sessions and netconf connection.

sr_subscription_ctx_t * **subscription** variable is defined as a global variable inside the sysrepo-plugin source code and all subscriptions are stored inside this variable.
In order to send a notification to only a specific **subscribed client** with a specific **NETCONF session ID**, (not to the other subscribed clients), how can we get the **(sr_session_ctx_t *) session** data from the globally defined (sr_subscription_ctx_t * ) **subscription** variable? or are there any alternative ways?

Thanks in advance.
Regards

**Comment by michalvasko** [comment]
> In order to send a notification to only a specific subscribed client with a specific NETCONF session ID...

You cannot do this no matter what session you use. *sysrepo* is designed to be a centralized datastore and any sent notifications are received by all the subscribed clients.

**Comment by jktjkt** [comment]
And maybe to add some context -- this is all modeled after the NETCONF semantics of notifications. In standard NETCONF and RESTCONF, there's no way to achieve what you describe; all sessions are considered "equal" and can, in principle, obtain the exact same data. There's no support for application-level logic which would selectively send a notification to just some clients that are already subscribed to that notification.

There are, however, valid use cases such as notifications about some value changes (a.k.a push metrics, [telemetry](https://www.claise.be/model-driven-telemetry-ietf-yang-push-and-or-openconfig-streaming-telemetry/), etc). There are fully supported in Netopeer2, and there's some work to make these available over RESTCONF as well. Under these schemas the "notifications" are sent to just the matching clients.
