### ISSUE TITLE
How to extract stream argument of netopeer2-cli subscribe command?

### ISSUE THREAD

**Issue by mustafatayf** [sysrepo/sysrepo#3164]
Hi,

Is there a way to get  `netopeer2-cli` `subscribe` command's `--stream` argument inside callback function of the `sr_rpc_subscribe_tree()` function.

My implementation include a sysrepo-plugind initialization as;

```
sr_plugin_init_cb(sr_session_ctx_t *session, void **private_data){
...
    rc = sr_rpc_subscribe_tree(session, 
                                    "/notifications:create-subscription",  // xpath
                                    supervision_create_sub_cb,  // callback
                                    NULL, // private data
                                    1, // Priority
                                    SR_SUBSCR_DEFAULT, // options
                                    &subscription);
...
}
```
and I want to get `--stream` argument coming from the client's `subscribe` command, such as:
```
$ netopeer2-cli
> connect 
...
> subscribe --stream o-ran-supervision
```
For the server side, inside **_supervision_create_sub_cb()_** function how can I extract client's `--stream` filter?

Thanks in advance,
Best regards.

**Comment by michalvasko** [comment]
The `input` parameters is a *libyang* data tree of the RPC so yes, you can get all the input nodes if you traverse it.

**Comment by mustafatayf** [comment]
Thank you Michal, the code below worked;
```
if (strcmp("o-ran-supervision", lyd_get_value(lyd_child(input))) != 0){
    printf("Filter does not matched!\n");
   ...
};
```
