### ISSUE TITLE
Missing dependent libraries for rpm installation.

### ISSUE THREAD

**Issue by msoodan** [sysrepo/sysrepo#3165]
I am using centos 7.6, would like to setup netopeer client installation in local vm. 
kernel : 3.10.0-1160.90.1.rt56.1235.el7.x86_64
CentOS Linux release 7.9.2009 (Core)

Downloaded rpm pack and using sudo mode to install rpm packages

netopeer2-2.0.35.2-1.el7.x86_64.rpm
libyang-2.0.112.1-1.el7.x86_64.rpm
libnetconf2-2.0.24.1-1.el7.x86_64.rpm
sysrepo-2.0.53.1-1.el7.x86_64.rpm

intalled 3 components, but netopeer2 installation fails with below error.  I cant find sysrepo-tools rpm in website:
https://www.sysrepo.org/packages/centos/

yum install netopeer2-2.0.35.2-1.el7.x86_64.rpm
--> Processing Dependency: sysrepo-tools for package: netopeer2-2.0.35.2.gcb2503f-1.el7.x86_64
Loading mirror speeds from cached hostfile
 * base: mirror.netsite.dk
 * epel: mirror.netsite.dk
 * epel-debuginfo: mirror.netsite.dk
 * extras: mirror.netsite.dk
 * remi-php73: mirror.netsite.dk
 * remi-safe: mirror.netsite.dk
 * updates: mirror.netsite.dk
Skipping filters plugin, no data
92 packages excluded due to repository priority protections
0 packages excluded due to repository protections
Excluding 1 update due to versionlock (use "yum versionlock status" to show it)
--> Finished Dependency Resolution
Error: Package: netopeer2-2.0.35.2.gcb2503f-1.el7.x86_64 (/netopeer2-2.0.35.2-1.el7.x86_64)
           Requires: sysrepo-tools
 You could try using --skip-broken to work around the problem

 You could try running: rpm -Va --nofiles --nodigest

**Comment by michalvasko** [comment]
Well, you can find that missing package [here](https://github.com/sysrepo/sysrepo/releases/tag/v2.0.53) but these releases are quite old now. So it would be better if you compiled the latest released versions yourself. You can even build packages [locally with ease](https://github.com/sysrepo/sysrepo/tree/master/distro).
