### ISSUE TITLE
Wrong path imported for xpath reference

### ISSUE THREAD

**Issue by nullromo** [sysrepo/sysrepo#3167]
## Summary
I imported some data containing an xpath, but the data in the datastore now contains a different xpath.

## How to Reproduce
I started with a module that contained just a list with 2 keys:

<details>

<summary>my-module@2023-08-17.yang</summary>

```yang
module my-module {
    yang-version 1.1;
    namespace 'urn:my-module';
    prefix my-module;

    organization 'test';
    contact 'test';
    description "test";
    revision 2023-08-17 {
        description 'test';
    }

    container power-monitoring {
        list duplex {
            key 'bank port';
            leaf bank {
                type enumeration {
                    enum input;
                    enum output;
                }
            }
            leaf port {
                type uint16 {
                    range '1..384';
                }
            }
        }
    }
}
```

</details>

I wiped everything out of sysrepo and installed the module using this command:

```bash
sudo sysrepoctl --install ../yang/my-module@2023-08-17.yang -v3
```

Then I created the following data file:

<details>

<summary>initial-nacm.xml</summary>

```xml
<nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
    <enable-nacm>true</enable-nacm>
    <read-default>deny</read-default>
    <write-default>deny</write-default>
    <exec-default>deny</exec-default>
    <groups>
        <group>
            <name>default</name>
        </group>
    </groups>
    <rule-list>
        <name>duplex-output-1-view</name>
        <rule>
            <name>power-monitoring-access</name>
            <path xmlns:n="urn:my-module">/n:power-monitoring/n:duplex[n:bank='output'][n:port='1']</path>
            <access-operations>read</access-operations>
            <action>permit</action>
        </rule>
    </rule-list>
</nacm>
```

</details>

I imported the data file using this command:

```bash
sudo sysrepocfg --import=../yang/initial-nacm.xml --module=ietf-netconf-acm --datastore startup -v3
```

Then I exported the data using this command:

```bash
sudo sysrepocfg --export --xpath "/ietf-netconf-acm:nacm" --datastore startup
```

and here's what I got:

<details>

<summary>Output</summary>

```xml
<nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
  <enable-nacm>true</enable-nacm>
  <read-default>deny</read-default>
  <write-default>deny</write-default>
  <exec-default>deny</exec-default>
  <groups>
    <group>
      <name>default</name>
    </group>
  </groups>
  <rule-list>
    <name>duplex-output-1-view</name>
    <rule>
      <name>power-monitoring-access</name>
      <path xmlns:my-module="urn:dicon:my-module">/my-module:power-monitoring/my-module:duplex[my-module:bank='output'][my-module:bank='output']</path>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
  </rule-list>
</nacm>
```

</details>

Notice that the imported data has the path `...[bank='output'][port='1']` and the exported data has the path `...[bank='output'][bank='output']`.

I'm fairly certain this is a bug having to do with sysrepo handling an xpath with 2 keys.

## Expected Behavior

Sysrepo should not modify the xpath value of an imported data node when importing the data.

## Info

sysrepo version: latest `devel` @ `4cbcb5f5`
libnetconf version: latest `devel` @ `4514f16`
libyang version: latest `devel` @ `216c66f18`
system: WSL2 on Windows 11

**Comment by michalvasko** [comment]
Please use the latest *libyang* `devel`, should now be fixed.

**Comment by nullromo** [comment]
I have confirmed on my machine that based on the steps provided, the issue has been fixed with this latest update.

Thanks Michal, I really appreciate you.
