### ISSUE TITLE
netopeer2-server assert in sr_edit_find_match()

### ISSUE THREAD

**Issue by n-toshikazu** [sysrepo/sysrepo#3170]
Hi.

When I send edit-config with below XML, netopeer2-server get asserted.
Although this XML includes incorrect data schema about edit-config,
I think RPC error should be returned.

- XML
`<org-openroadm-device xmlns="http://org/openroadm/device">`
`  <degree>`
`    <degree-number>100</degree-number>`
`    <circuit-packs>`
`      <index>123</index>`
`      <circuit-pack-name>test</circuit-pack-name>`
`    </circuit-packs>`
`    <mc-capability-profile-name>test</mc-capability-profile-name>`
`  </degree>`
`</org-openroadm-device>`

- netopeer2-server log
[INF]: SR: EV ORIGIN: "/ietf-netconf:edit-config" "rpc" ID 1 priority 0 for 1 subscribers published.
[INF]: SR: EV LISTEN: "/ietf-netconf:edit-config" "rpc" ID 1 priority 0 processing (remaining 1 subscribers).
[INF]: NP: edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
netopeer2-server: /usr/src/debug/sysrepo/2.2.105-r0/src/edit_diff.c:1105: sr_edit_find_match: Assertion `m1' failed.
Aborted (core dumped)

XML includes mc-capability-profile-name schema which is config false leaflist(operational data)
although edit-config target datastore is running.
> [https://github.com/OpenROADM/OpenROADM_MSA_Public/blob/master/model/Device/org-openroadm-device.yang](url)

I assume that sr_edit_batch() allocate node->meta only if (session->ds == SR_DS_OPERATIONAL), however,
edit-config switched ds to SR_DS_RUNNING and lyd_find_meta(NULL, ...) return NULL, asserted.

I try to chage sr_edit_find_match() like below and send XML. RPC error is returned expectly.
> } else if (lysc_is_dup_inst_list(edit_node->schema)) {

>  } else if (lysc_is_dup_inst_list(edit_node->schema) && edit_node->meta) {

> dit-config --target running --config=test.xml
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  Unexpected data state node "mc-capability-profile-name" found. (Data location "/org-openroadm-device:org-openroadm-device/degree[degree-number='100']/mc-capability-profile-name[test]".)

        type:     application
        tag:      operation-failed
        severity: error
        message:  User callback failed.

**Comment by michalvasko** [comment]
Yes, it should not fail on an assert but with a proper error instead, fixed.

**Comment by n-toshikazu** [comment]
I apply your patch and it works fine!
Thank you.
