### ISSUE TITLE
sr_oper_get_subscribe callback not updating data in Parent node

### ISSUE THREAD

**Issue by raman-in** [sysrepo/sysrepo#3171]
Hi,
I have added the below callback to update o-ran-fm related data but it was coming as empty in the <rpc_reply>.

```C
int np2srv_get_fm_alarm_data_cb(sr_session_ctx_t* session, uint32_t sub_id, const char* module_name, const char* xpath,
    const char* request_xpath, uint32_t request_id, struct lyd_node** parent, void* private_data)
{
    const struct ly_ctx* ly_ctx;

    (void)session;
    (void)sub_id;
    (void)request_xpath;
    (void)request_id;
    (void)private_data;

    INFO("alarm values to be set");

    if (!strcmp(module_name, "o-ran-fm") && !strcmp(xpath, "/o-ran-fm:active-alarm-list")) {
        INFO("alarm values getting set");
        ly_ctx = sr_acquire_context(sr_session_get_connection(session));
        lyd_new_path(NULL, ly_ctx, "/o-ran-fm:active-alarm-list/active-alarms[0]/fault-id", "1", 0, parent);
        lyd_new_path(*parent, ly_ctx, "/o-ran-fm:active-alarm-list/active-alarms[0]/fault-source", "Network Element X", 0, NULL);
        lyd_new_path(*parent, ly_ctx, "/o-ran-fm:active-alarm-list/active-alarms[0]/affected-objects/name", "Radio Unit", 0, NULL);
        lyd_new_path(*parent, ly_ctx, "/o-ran-fm:active-alarm-list/active-alarms[0]/fault-severity", "MAJOR", 0, NULL);
        lyd_new_path(*parent, ly_ctx, "/o-ran-fm:active-alarm-list/active-alarms[0]/is-cleared", "true", 0, NULL);
        lyd_new_path(*parent, ly_ctx, "/o-ran-fm:active-alarm-list/active-alarms[0]/fault-text", "Equipment Power supply", 0, NULL);
        lyd_new_path(*parent, ly_ctx, "/o-ran-fm:active-alarm-list/active-alarms[0]/event-time", "2023-09-27T18:05:26Z", 0, NULL);
        sr_release_context(sr_session_get_connection(session));
        INFO("alarm values already set");
    }
    return SR_ERR_OK;
}
```

Netopeer server logs:
```
[INF]: NP: Session 1: thread 1 event new RPC.
[DBG]: LN: Session 1: Received message:

< rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="9"><get  
 xmlns= "urn:ietf:params:xml:ns:netconf:base:1.0" >< filter type="xpath" xmlns:o-ran-fm ="urn:o-ran:fm:1.0" select= "/o-ran-fm:active-alarm-list" />< with-defaults xmlns=" urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults ">report-all< /with-defaults>< /get >< /rpc >

[INF]: SR: EV ORIGIN: "/ietf-netconf:get" "rpc" ID 3 priority 0 for 1 subscribers published.
[INF]: SR: EV LISTEN: "/ietf-netconf:get" "rpc" ID 3 priority 0 processing (remaining 1 subscribers).
[INF]: SR: EV ORIGIN: "/o-ran-fm:active-alarm-list" "oper get" index 0 ID 1 published.
[INF]: SR: EV LISTEN: "/o-ran-fm:active-alarm-list" "oper get" ID 1 processing.
[INF]: NP: alarm values to be set
[INF: NP: alarm values getting set
[INF]: NP: alarm values already set
[INF]: SR: EV LISTEN: "/o-ran-fm:active-alarm-list" "oper get" ID 1 processing success.
[INF]: SR: EV ORIGIN: "/o-ran-fm:active-alarm-list" "oper get" index 0 ID 1 succeeded.
[INF]: SR: EV LISTEN: "/ietf-netconf:get" "rpc" ID 3 priority 0 success (remaining 0 subscribers).
[INF]: SR: EV ORIGIN: "/ietf-netconf:get" "rpc" ID 3 priority 0 succeeded.
[DBG]: LN: Session 1: Sending message:

#93
[DBG]: LN: Session 1: Sending message:

< rpc-reply xmlns= "urn:ietf:params:xml:ns:netconf:base:1.0" message-id="9" >< data/></ rpc-reply>
```

Can you please help me with this issue?

**Comment by michalvasko** [comment]
Check the return values/errors from all the `lyd_new_path()` functions, they have failed for some reason probably.

**Comment by raman-in** [comment]
I checked for the return error of the API lyd_new_path():

 LY_ERR er_id = lyd_new_path(NULL, ly_ctx, "/o-ran-fm:active-alarm-list/active-alarms[0]/fault-id", "1", 0, parent);
 if (er_id)
 {
     ERR("New path creation failed %d", er_id);
 }
 er_id = lyd_new_path(*parent, NULL, "/o-ran-fm:active-alarm-list/active-alarms[0]/fault-source", "Network Element X", 0, NULL);
 if (er_id)
 {
     ERR("New path2 creation failed %d", er_id);
 }

[ERR]: NP: New path creation failed 7   ->>  LY_EVALID,      /**< Validation failure */
[ERR]: NP: New path2 creation failed 3 ->>  LY_EINVAL,      /**< Invalid value */ 

Is it like the libyang context is not proper that we have to register the o-ran-fm while doing server init? Or is there a path issue[/o-ran-fm:active-alarm-list/active-alarms[0]/fault-id] that we need to correct it?

**Comment by raman-in** [comment]
When i print the error using ly_errmsg(ly_ctx) it returns Null for 'ly_ctx'. So do i need to explicitly create the libyang context from Netopeer2 server side, if so what API do i need to use? 
Because the 'conn' value is proper but i could see "[ERR]: NP: ly context error (null)" logs is getting printed.
///**///
conn = sr_session_get_connection(session);
if(!conn)
    ERR("conn value is null");
ly_ctx = (struct ly_ctx*)sr_acquire_context(conn);
ERR("ly context error %s", ly_errmsg(ly_ctx));
///**///

**Comment by michalvasko** [comment]
Positional predicates in XPath (which is used here) starts with `1`.

**Comment by michalvasko** [comment]
Look at the definition of `path`, every list instance needs a predicate with its key values, if it has any. In this case you need to use `/o-ran-software-management:software-inventory/software-slot[name='value']` and can directly create other non-key children of `software-slot`.

**Comment by raman-in** [comment]
ok since the container has the key as "name" we need to pass the key for filling the data to Sysrepo right.
With that it is updating the data to Sysrepo DB. Thanks
