### ISSUE TITLE
TLS callhome : Getting error as "server certificate not set"

### ISSUE THREAD

**Issue by RSowndarya** [sysrepo/sysrepo#3177]
Hi Team,

We are testing TLS callhome feature with netopeer2-server 2.1.42 & netopeer2-cli 2.0.68.
While pushing tls_listen we are facing issue as below

[INF]: LN: Listening on 0.0.0.0:6513 for TLS connections.
[ERR]: LN: nc_server_tls_endpt_set_server_cert: invalid argument (endpt_name).
[ERR]: LN: nc_server_tls_add_trusted_cert_list: invalid argument (name).
[INF]: SR: Successful processing of "done" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: SR: Successful processing of "rpc" event with ID 3 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 3 priority 0 succeeded.
[INF]: NP: Session 1: thread 2 event new RPC.

we are using yang 2.0 version and we have modified the example configurations of tls_listen configuration according to our yang.
we have added container "certificate" additionally. And configuration was successful

                <server-identity>
                  <certificate>
                        <keystore-reference>
                        <asymmetric-key>cgserverkey</asymmetric-key>
                        <certificate>cgservercert</certificate>
                    </keystore-reference>
                    </certificate>
                </server-identity>
In code, for subscription part xpath was coming with container as below:

xpath = "/ietf-netconf-server:netconf-server/listen/endpoint/tls/tls-server-parameters/server-identity/certificate/keystore-reference";
SR_CONFIG_SUBSCR(mod_name, xpath, np2srv_endpt_tls_servercert_cb);

But in callback function, xpath mentioned without container (certificate):

/* /ietf-netconf-server:netconf-server/listen/endpoint/tls/tls-server-parameters/server-identity/keystore-reference */
int
np2srv_endpt_tls_servercert_cb(sr_session_ctx_t *session, uint32_t UNUSED(sub_id), const char *UNUSED(module_name),
const char *xpath, sr_event_t UNUSED(event), uint32_t UNUSED(request_id), void *UNUSED(private_data))
{

we are suspecting that if additional container was added then the value of child will get changed and cannot fetch the endpoint name. Hence the error was observed as invalid argument for endpoint name.

code snippet:
/* find name */
endpt_name = lyd_get_value(node->parent->parent->parent->parent->parent->child);

could you please confirm how the code was handled, whether with container (certificate) or without that container?
Attached the configs for reference.
[tls_listen.odt](https://github.com/sysrepo/sysrepo/files/12877639/tls_listen.odt)

**Comment by michalvasko** [comment]
Duplicate cesnet/libnetconf2#440.
