### ISSUE TITLE
Change callback not invoked on operational data

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#3178]
Hi,

I ran into an issue with sr_module_change_subscribe, in some cases the change callback is not invoked
when data is deleted from operational datastore.
 
I attached an example application to reproduce it:
[reprod.zip](https://github.com/sysrepo/sysrepo/files/12884346/reprod.zip)
 
```
$ ./reprod "/test:c1/list1/c2" 
Removing oper data 
module_oper_change_cb called 
module_oper_change_cb called
 
$ ./reprod "/test:c1/list1/c2/list3/id" 
Removing oper data
```
 
In the first case, when registering for c2 container the callback was invoked as expected.
In the second case, when it is registered for data nodes under c2 container, the callback is not invoked.
 
libyang version: 2.1.128
sysrepo version: 2.2.120

Thank you in advance!

**Comment by michalvasko** [comment]
Right, should be fixed.

**Comment by awesomenode** [comment]
Now it is called, thank you for the quick fix!
