### ISSUE TITLE
Duplicate list items in sr_get_data() result

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#3179]
Hi,

I met an issue with sr_get_data, it returns duplicate list items.
I attached an example to reproduce it:
[reprod.zip](https://github.com/sysrepo/sysrepo/files/12884365/reprod.zip)

```
$ ./reprod  
get result: 
<c1 xmlns="urn:com::test"> 
 <list1> 
   <id>1</id> 
   <name>someone</name> 
   <list2> 
     <id>1</id> 
     <id2>0</id2> 
     <name>testdata</name> 
   </list2> 
   <list2> 
     <id>1</id> 
     <id2>1</id2> 
     <name>testdata</name> 
   </list2> 
   <list2> 
     <id>1</id> 
     <id2>1</id2> 
     <name>testdata</name> 
   </list2> 
 </list1> 
</c1>
```

Here the list item `"/test:c1/list1[id='1'][name='someone']/list2[id='1'][id2='1']"`  is present twice in the result.

libyang version: 2.1.128
sysrepo version: 2.2.120

Thank you in advance!

**Comment by michalvasko** [comment]
Fixed in latest `devel`, updated *libyang* is also required.

**Comment by awesomenode** [comment]
The duplicate is gone, thanks!
