### ISSUE TITLE
corrupted size vs. prev_size in fastbins

### ISSUE THREAD

**Issue by minhix** [sysrepo/sysrepo#3182]
Hi!

I am facing a problem as installing a model to sysrepo and hope some one could help to solve it.

The problem happens when I try to install my model to sysrepo. My model modifies the schema defined by ietf-system.yang.
```
sysrepoctl -i ietf-system-mods.yang 
[ERR] Schema node "/ietf-system:system/ietf-system-mods:feature-a" not found in the target context.
corrupted size vs. prev_size in fastbins
Aborted
```

The content of my model is as below:
```

  deviation "/ietf-system:system/ietf-system:dns-resolver" +
  "/ietf-system:options"
  {
    deviate not-supported;
  }

  augment "/ietf-system:system" {
    leaf feature-a {
      type boolean;
      default false;
    }
    leaf feature-b {
      type boolean;
      default false;
    }
  }
```

It works if there is either deviation or augment block there.

So it looks like a violation of memory access or alignment of memory blocks in glibc. So could any one say what the problem here?

Version: sysrepo v2.2.60

**Comment by michalvasko** [comment]
An interesting use-case and it should work now if you update *libyang* and *sysrepo* to their latest `devel` versions.

**Comment by minhix** [comment]
@michalvasko thank you very much! The problem could not be reproduced when using devel branches of sysrepo and libyang. Hope the fixes will be soon cut in the next release
