### ISSUE TITLE
Concurrent sr_get_item can result in SR_ERR_NOT_FOUND

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#3185]
Hi,

I found a race condition issue with `sr_get_item` function:
in case of concurrent function calls it can result in `SR_ERR_NOT_FOUND`  while the data exists in the datastore.

To reproduce it I attached a test application which executes concurrent `sr_get_item` operations for existing data.
After a short time the test aborts on `sr_get_item`:
[test.zip](https://github.com/sysrepo/sysrepo/files/13042954/test.zip)

```
$ ./test  
[ERR] No data found for "/ietf-interfaces:interfaces/interface[name='eth0']". 
sr_get_item error, rc=5 
Aborted
```

It seems to be running cache related, if I disable `SR_CONN_CACHE_RUNNING` then the issue is gone.

libyang version: 2.1.132
sysrepo version: 2.2.125

Thank you in advance!

**Comment by michalvasko** [comment]
It took me a long time to find the culprit but this should be fixed in the latest *libyang*, thanks for the report.

**Comment by awesomenode** [comment]
I cannot reproduce it with latest version, thank you!
