### ISSUE TITLE
python error during sysrepo build

### ISSUE THREAD

**Issue by rajnkamr** [sysrepo/sysrepo#319]
Getting issue due to python , do we really need python for sysrepo.
Python distribution generates static lib

 15%] Linking C shared library libsysrepo.so
[ 16%] Built target sysrepo
[ 16%] Swig source
Scanning dependencies of target _sysrepoPy
[ 17%] Building C object CMakeFiles/_sysrepoPy.dir/swig/python/sysrepoPyPYTHON_wrap.c.o
/mnt/local/rajnish.kumar/connector/FLOW_EFC-16.2-dev/MaestrOSCommon/mgmt-crd/ui/sysrepo/build/swig/python/sysrepoPyPYTHON_wrap.c: In function âSwigPyObject_reprâ:
/mnt/local/rajnish.kumar/connector/FLOW_EFC-16.2-dev/MaestrOSCommon/mgmt-crd/ui/sysrepo/build/swig/python/sysrepoPyPYTHON_wrap.c:1451:3: warning: format â%pâ expects argument of type âvoid *â, but argument 3 has type âstruct SwigPyObject *â [-Wformat=]
   PyObject *repr = SWIG_Python_str_FromFormat("<Swig Object of type '%s' at %p>", name, v);
   ^
[ 17%] Linking C shared module _sysrepoPy.so
/mnt/sweng/tools/sysroots/65vse/v3/sysroots/centos_7.0/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.2/../../../../x86_64-redhat-linux/bin/ld: error: /usr/local/lib/libpython2.7.a(abstract.o): requires dynamic R_X86_64_PC32 reloc against 'PyType_IsSubtype' which may overflow at runtime; recompile with -fPIC

**Comment by rajnkamr** [comment]
resolved by using python shared 64 bit library

**Comment by rastislavszabo** [comment]
Hi,

we will introduce a new CMake option allowing to turn off the build of language bindings if you don't need them.

Thanks,
Rastislav
