### ISSUE TITLE
To Identify Configuration restore is successful or not

### ISSUE THREAD

**Issue by AravindaSwamy** [sysrepo/sysrepo#3190]
Hi Team,

is there way for application to know that Sysrepo configuraiton restoration is completed?

Thank You.

Regards,
Aravind.

**Comment by michalvasko** [comment]
What exactly is "Sysrepo configuration restoration"?

**Comment by AravindaSwamy** [comment]
Hi Michal,

After configuring Image, We will do copy-config. So that all the configurations will be saved to startup db. If we are bringing down and bringing up image means whatever configurations there in startup db will be restored to running db. 

So, We want to know whether all the configurations are restored to running db is successful or not. Is there any way we can find out ?

**Comment by michalvasko** [comment]
Are you talking about the initial startup->running data copy when the SHM is being created (after a reboot)? That is always performed before the first application gets to access *sysrepo*. I am still not sure what you are asking exactly.

**Comment by AravindaSwamy** [comment]
we have an application that will register many callbacks from the sysrepo whenever the configurations are being pushed to the application. After Configuring the application we will do copy-config and will reload the application. During Reload all configurations will be restored to the application by registering callbacks. 

Query :- Can we know whether all configurations are restored to the application properly from sysrepo?

**Comment by michalvasko** [comment]
Okay, it should be clear now and no, there are no special copy-config callbacks you could register. But what you could do is, after the copy-config is finished, send a custom notification that any interested applications can register for and this way be notified about successful copy-config.
