### ISSUE TITLE
Factory Default Datastore support (RFC 8808)

### ISSUE THREAD

**Issue by robbynet** [sysrepo/sysrepo#3198]
Simple question : 
From RFC 8808, we can read the following _The datastore can be read using the standard NETCONF/RESTCONF protocol operations_
- Using CLI what cmd to be used : get or get-data ?
- How specified the datastore "factory-default" in those cmd above ?
Regards.
Christian.

**Comment by michalvasko** [comment]
Right, it was not supported in *netopeer2*, I have added it to `get-data` (`get` cannot support this as you cannot select the datastore).
