### ISSUE TITLE
Conditionally push notification

### ISSUE THREAD

**Issue by BillYJT** [sysrepo/sysrepo#3199]
Hi.

I am trying to find a way to conditionally push notification from NETCONF server to client. I am studying the notif_send_example but I can't figure out a good way to implement this.

Currently, I create and push notification from within a module change callback. A value is constantly monitored by the callback and whenever it drops below a threshold (the condition), a notification is created and pushed. However, I feel that the notification API isn't designed to be used this way, especially the notification context acquiring and release feel hacky.

Any suggestion?
Thank you.

**Comment by michalvasko** [comment]
I am not sure what the problem is, I would say you have implemented it exactly as you should (by monitoring the value the notification depends on).

**Comment by BillYJT** [comment]
Thank you, Michal.

Sorry for not being clear. I guess what I really want to know are the following two questions.

1. If my notification push is driven by value change, do I rely on module change subscription, or there is a way that directly links notification to value change (like a sysrepo or libnetconf API that I haven't learned)?
2. For conditional notification, do I implement it myself in the C code, or there are already mechanisms for inserting conditional check (I am thinking the YANG conditional statement and whether that plays a part here)?

Thanks!

**Comment by jktjkt** [comment]
If you're interested in NETCONF-level notifications about datastore changes, use the IETF's yang-push feature. That way you can configure what to be notified about.

If you're interested in writing some code that gets notified about "live changes" in some datastore, make a sysrpeo-level subscription to the relevant XPath(s), typically in the `operational` DS.

If you wanto to write code which generates a NETCONF-level or sysrepo-level notification about some application-defined condition, just write that code and generate a sysrepo-level notification. It will be distributed to all the subscribers. Keep in mind that this is conceptually a NETCONF-level notification, and that means that there's no per-client filtering. All clients which have asked to be notified about this notification, and who have NACM access to see it, will be notified.

**Comment by michalvasko** [comment]
1. Like I said, what you are doing is correct, there is no special generate-notification-on-value-change API.
2. There are no special mechanisms for generating notifications, you simply send it whenever you want, on conditions you check yourself.

**Comment by BillYJT** [comment]
Thank you for both of your answers, Michal and Jan.

My questions are answered.
