### ISSUE TITLE
cleanup_cb not called when using sysrepo-plugind with fatal option if other plugin has init_cb failure

### ISSUE THREAD

**Issue by karowski** [sysrepo/sysrepo#3200]
Hi,

assuming there are two plugins A and B started using sysrepo-plugind together with the `fatal` option. Now if the `init_cb` for A is successful, but `init_cb` for B fails, no `cleanup_cb` is called for A.

When using the `fatal` option a `goto cleanup` is executed when a plugin fails in `init_cb`. However, the `cleanup_cb` loop is before the jump label.

I would expect if a plugin is successfully initialized, that the `cleanup_cb`  will always be called, even if other plugins have problems.

**Comment by michalvasko** [comment]
You are right, the cleanup of `sysrepo-plugind` had some problems, should be fixed.
