### ISSUE TITLE
Wrong startup datastore contents for augmented Yang model

### ISSUE THREAD

**Issue by rbu9fe** [sysrepo/sysrepo#3201]
I have an issue of the startup datastore contents when augmenting a Yang model. To reproduce the issue I augmented [examples.yang](https://github.com/sysrepo/sysrepo/blob/master/examples/examples.yang) by:
```
module examples-augment {
    namespace "urn:examples-augment";
    prefix aug;

    import examples {
        prefix ex;
    }

    augment "/ex:cont" {
        leaf m {
            type string;
        }
    }
}
```
Now I store `myvalue` in the leaf `/examples:cont/examples-augment:m` to the startup datastore (e.g. via [sr_set_item_example](https://github.com/sysrepo/sysrepo/blob/master/examples/sr_set_item_example.c) after modifying the source file to write to the startup rather than to the running datastore). Then the startup datastores carry the following data:

```
# cat examples.startup:
{
   "examples:cont":{
      "examples-augment:m":"myvalue"
   }
}

# cat examples-augment.startup
{
}
```

As can be seen the augmented leaf's value is stored in the base Yang model's startup datastore and the augmented startup datastore remains empty. Then during the next sysrepo initialization the startup datastores are copied into running. However, it seems that first `examples.startup` is copied and afterwards `examples-augment.startup` is copied resetting `/examples:cont/examples-augment:m` again. In the end the initial running datastore remains empty, which is not expected.

Am I missing something or is this a sysrepo bug?
Btw. I'm using sysrepo from [devel 8482344](https://github.com/sysrepo/sysrepo/commit/8482344504c8776342ef18b75f70391edc793d9a).

**Comment by michalvasko** [comment]
Data from `augment` statements are supposed to be stored in their target modules but you are saying that you have no data for any module after `startup` is copied into `running`? I can only imagine some permission problems but, by default, it should be working normally (this not working would break all the tests).

**Comment by rbu9fe** [comment]
Thanks, at least we have the same understanding that the `augment` data should be stored in the datastore of the corresponding model. There is no permission problem, instead, the data just goes into the startup datastore of the wrong model (the one which is augmented rather than the one that augments). You should be able to reproduce it easily.

**Comment by michalvasko** [comment]
I am not sure we have the same understanding, what I meant is that in this case, all the data are supposed to be in `examples` and no in `examples-augment`.

**Comment by rbu9fe** [comment]
Ok got it. Looks like we have some issue with our persistent memory, thanks for your support.
