### ISSUE TITLE
Question regarding NACM related logging

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#3202]
Hi,

I have complex NACM rules installed in sysrepo.
During development I need to investigate NACM errors, but currently it is not easy to identify which rule caused it since there is only an "NACM access denied" message.
Is there a plan to improve NACM related logging?

Thank you in advance!

**Comment by michalvasko** [comment]
Just to answer, I plan to take a look at this because I think it may be possible but will not be trivial. So I want to finish the current tasks first but they may still take weeks.
