### ISSUE TITLE
Q: Is there any way to dump the current YANG tree?

### ISSUE THREAD

**Issue by troglobit** [sysrepo/sysrepo#3203]
Hi,

I'm debugging one of our sysrepo plugins and one of the questions that came up was how to dump the current schema.  Both what's currently loaded in sysrepo-plugind, but also from a given node in a callback to dump not just the data but also the schema.  Is there anything/API readily available, or do you recommend unpacking structs manually and using libyang?

(My problem atm. is an augment to ietf-system:system-state where we have added a 'software' container, which for some reason does not seem to be there when the operational callback runs, so lyd_new_inner() fails.)

BR
 /Joachim

**Comment by michalvasko** [comment]
I suggest using *libyang* but you do not have to unpack anything. You can use `lys_print_node()` to print only schema subtrees.
