### ISSUE TITLE
[ERR]: LN: Session 1899: Inactive read timeout elapsed.

### ISSUE THREAD

**Issue by sathishp85** [sysrepo/sysrepo#3204]
Sysrepo Version: sysrepo-2.2.73
Netconf Client : 0.6.15

While we are trying to perform get-config from netconf client to sysrepo server in a loop, after successfully fetching the configuration for multiple iterations, netconf client is throwing the error "ncclient timed out while waiting for an rpc reply."  and we observed the below error in sysrepo .

[ERR]: LN: Session 1899: Inactive read timeout elapsed.

Kindly provide the solution for this issue.

**Comment by michalvasko** [comment]
It means your NETCONF client is sending improperly formatted messages or simply some redundant characters and *libnetconf2* does not like that.

**Comment by sathishp85** [comment]
How can we verify this issue from sysrepo server perspective ?
Is there may be any deadlock condition in sysrepo server or netfconf client.? 

This issue is related to the below ticket ?
https://github.com/sysrepo/sysrepo/issues/2220

**Comment by michalvasko** [comment]
Run the server with `-c MSG` to see the received messages. You do not see an error because *libnetconf2* thinks a new message is being sent but it is not received within the timeout.
