### ISSUE TITLE
This error occurs when the client keeps sending get commands:［ERR］ Failed to gpen mod shared memory（2oo many cpen files）

### ISSUE THREAD

**Issue by Agao404** [sysrepo/sysrepo#3206]
This error occurs when the client sends the get command roughly 80 times in a row each time.
"/o-ran-delay-management delay-management" "oper get" in［ERR］ Failed to open mod shared memory（2oo many cpen files）
Is this as expected, please?

**Comment by michalvasko** [comment]
I think you are not closing something in the oper get callback, I have never encountered this error.
