### ISSUE TITLE
How to update specific path of a module from running DS to startup DS

### ISSUE THREAD

**Issue by satomhxl** [sysrepo/sysrepo#3207]
Hello, I want to ask a question: How to update data in specific path of a module from running DS to startup DS in a sysrepo plugin `<edit-config>` callback function, when the event is SR_EV_DONE?

It would be good to transform the info of changed data to XML, so I can use `sr_edit_batch(sess, data, "merge")` to write changed data to startup DS. But I don't know how to get the XML.

I'm using netopeer2-2.1.36 and sysrepo-2.1.84.
Many thanks.

**Comment by satomhxl** [comment]
Then what operation should I use in sr_edit_batch(), "merge" or "replace"?
If I use merge, seems I can't delete item.
If I use replace, seems the whole module will be replaced, that is not I want.

**Comment by michalvasko** [comment]
If you require specific operations, not just simple `merge`, then it will not be that simple. You can add operations on the specific paths in the retrieved data (`lyd_new_meta()`, [operation attribute](https://datatracker.ietf.org/doc/html/rfc6241#section-7.2)), for example.

**Comment by michalvasko** [comment]
Please skip step 2 and 3, they are completely redundant. Other than that, perhaps contrary to what one may expect, `sr_get_data()` always returns a tree starting at the top, not only the XPath you use. So the steps would roughly be:
1. sr_get_data(session, xpath, 0, 0, 0, &data)
2. lyd_find_path(data->tree, xpath, &node)
3. lyd_new_meta(NULL, node, NULL, "ietf-netconf:operation", "replace", 0, NULL)
4. sr_edit_batch(session, data->tree, "merge")
