### ISSUE TITLE
Error when setting a value multiple times

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#3211]
Hi,

I ran into an issue when `sr_set_item_str` was called multiple times for the same xpath.
On `sr_apply_changes` there will be an internal error when an other application is trying to iterate changes in change callback,
or fails on an assert when libyang/sysrepo is built with debug type.

I attached an application to reproduce with debug build:
[reprod.zip](https://github.com/sysrepo/sysrepo/files/13662874/reprod.zip)

```
$ ./reprod
reprod: /opt/dev/libyang/src/diff.c:1538: lyd_diff_merge_replace: Assertion `lysc_is_userordered(diff_match->schema) && (diff_match->schema->nodetype == LYS_LIST)' failed. 
Aborted
```

libyang version: 2.1.141
sysrepo version: 2.2.136

Thank you in advance!

**Comment by michalvasko** [comment]
Right, should be fixed.
