### ISSUE TITLE
Request for one last git tag on libyang1 branch

### ISSUE THREAD

**Issue by matth65** [sysrepo/sysrepo#3212]
Hello,

Would it be possible to create one last git tag for the libyang1/sysrepo1 branches for libyang, sysrepo, libnetconf2, and netopeer2? The official git tag allows static analysis tools like Black Duck to automatically scan and report on open source projects like Sysrepo.

Best Regards,
Matt

**Comment by michalvasko** [comment]
Fine, I have added the tags but did not make new releases.

**Comment by matth65** [comment]
Ok, great! Thank you very much.
