### ISSUE TITLE
[ERR] Datastore plugin "JSON notif" not found

### ISSUE THREAD

**Issue by DiepHieu99** [sysrepo/sysrepo#3213]
I trying to upgrade netopeer2 to version 2.1.71 with sysrepo v2.2.105, I check every depend lib, yang modules, files are exists. 
while install yang module, i see this error:
[ERR] Datastore plugin "JSON notif" not found
sysrepoctl error: Failed to connect (Item not found)
![Capture](https://github.com/sysrepo/sysrepo/assets/55122719/0b6ccb9e-930d-44c5-8346-c5dd6f962c6a)

**Comment by michalvasko** [comment]
Seems to be a compatibility problem. Please fully uninstall *netopeer2*, *sysrepo* with its repositories and *libyang* with *libnetconf2*. Once you perform a clean install, it should all work.

**Comment by bingbin12389** [comment]
> Seems to be a compatibility problem. Please fully uninstall _netopeer2_, _sysrepo_ with its repositories and _libyang_ with _libnetconf2_. Once you perform a clean install, it should all work.

I got it, will try to remove the old repo and test again.

**Comment by bingbin12389** [comment]
I trying to uninstall full netopeer2, sysrepo with command _sudo make uninstall_, _locate_ all old lib install in system and completely remove them. Then I build sysrepo and install it again with sudo make _shm_clean_, _sudo make sr_clean_, _sudo make_, _sudo make install_, run _sysrepoctl -l_ still get error (libyang, libnetconf2 and netopeer2 completely remove and install again). I tried to run _sysrepoctl -l -v4_ still got this error: 
![Uploading Capture.JPG…]()

**Comment by michalvasko** [comment]
What versions of the projects are you using? Latest release, `master`, `devel` branch, or something else?

**Comment by bingbin12389** [comment]
I used netopeer2 latest release version 2.1.71
sysrepo latest release v2.1.105
libyang latest release v2.1.111
libnetconf latest release v2.1.37
libssh latest release v0.10.6

When I build and install all of them in ubuntu 20.04 work fine, but when I build and install in redhat 8 (RHEL8) It's not working and end up with this error: 
[ERR] Datastore plugin "JSON notif" not found
sysrepoctl error: Failed to connect (Item not found)

I follow instruction step by step, removed all old conflict version, build & install libyang, clean sysrepo with make sr_clean and make shm_clean, build & install sysrepo, reinstall RHEL8 OS but remain the same issue.

**Comment by michalvasko** [comment]
Try using the `master` branches instead, there may be some incompatibility in the latest releases.

**Comment by koalo** [comment]
I had the same problem, also with the master branches. I fixed it by uninstalling everything, then removing the `/etc/sysrepo` directory manually, then installing everything again. Seems to be some migration issue with the contents of `/etc/sysrepo`?

**Comment by bingbin12389** [comment]
> I had the same problem, also with the master branches. I fixed it by uninstalling everything, then removing the `/etc/sysrepo` directory manually, then installing everything again. Seems to be some migration issue with the contents of `/etc/sysrepo`?

I uninstall everything and also remeving the /etc/sysrepo/ but still got this error: 
![Uploading image.png…]()

**Comment by DennyAgussy** [comment]
Hi @DiepHieu99 

This is because of the libyang version. I also faced the same issue. But when I upgraded libyang to v2.1.148 and sysrepo to v2.2.105 everything was working fine.

But if I try with the versions libyang(v2.1.128) and sysrepo(v2.2.105) even though I uninstalled sysrepo completely and tried again facing the same issue.

Thanks
