### ISSUE TITLE
Callback "load" of plugin "JSON DS file" for module "name of the module"

### ISSUE THREAD

**Issue by avaserman** [sysrepo/sysrepo#3222]
Hi
We have encountered the following error when trying to reach parameters in a specific module.
Callback "load" of plugin "JSON DS file" for module "name of the module" failed.
when I looked at the /dev/shm the files for the module for running and operational has been deleted
the process that opened them doesn't have this option. can the sysrepo delete them because of an error on netopeer requests?

how can I open the logs that will show who deleted the files from /dev/shm?

**Comment by michalvasko** [comment]
Files in `/dev/shm` are usually deleted automatically by system after every reboot. And that should be fine and expected, the reason for the fail will be different. Are any other messages printed before this one?

**Comment by avaserman** [comment]
There were no printouts,  eventually we found the problem.
it's not related to sysrepo , some other process in the system accidently deleted the files in /dev/shm for that specific module.
