### ISSUE TITLE
edit-config parameter xml file invalid.

### ISSUE THREAD

**Issue by Prajwal027** [sysrepo/sysrepo#3223]
Hi,
I have been working on validating the yang file using edit-config 
```
edit-config --target running --test test-only --config=interfaces.xml
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	message:  Invalid identityref "ianaift:ethernetCsmacd" value - unable to map prefix to YANG schema. (Data location "/ietf-interfaces:interfaces/interface[name='eth0']/type".)
 
	type:     application
	tag:      operation-failed
	severity: error
	message:  User callback failed.
```
This is the interface.xml
```
<config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
    <interface>
      <name>eth0</name>
      <description>Example interfaces</description>
      <type>ether</type>
    </interface>
  </interfaces>
</config>
```
Can anyone give suggestion on what I should use for type flag
Thanks!

**Comment by Prajwal027** [comment]
Hi,
But after using this type I am getting the same error.
client:
> edit-config --target running --test test-only --config=interfaces.xml
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	message:  Invalid identityref "ianaift:ethernetCsmacd" value - unable to map prefix to YANG schema. (Data location "/ietf-interfaces:interfaces/interface[name='eth0']/type".)
 
	type:     application
	tag:      operation-failed
	severity: error
	message:  User callback failed.

Server:
[ERR]: SR: Invalid identityref "ianaift:ethernetCsmacd" value - unable to map prefix to YANG schema. (Data location "/ietf-interfaces:interfaces/interface[name='eth0']/type".)
[ERR]: SR: Applying operation "merge" failed.
[INF]: SR: EV LISTEN: "/ietf-netconf:edit-config" "rpc" ID 9 priority 0 fail (remaining 1 subscribers).
[ERR]: SR: Invalid identityref "ianaift:ethernetCsmacd" value - unable to map prefix to YANG schema. (Data location "/ietf-interfaces:interfaces/interface[name='eth0']/type".)
[WRN]: SR: EV ORIGIN: "/ietf-netconf:edit-config" "rpc" ID 9 priority 0 failed (libyang error).
[ERR]: SR: User callback failed.
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 2: thread 1 event new RPC.
[INF]: NP: Session 2: thread 1 event reply error.

**Comment by michalvasko** [comment]
Okay, then you are missing the `iana-if-type` YANG module in *sysrepo* (and so in *netopeer2* as well). Just install the module using `sysrepoctl` and it should then work.
