### ISSUE TITLE
Merge functionality with sysrepocfg in devel

### ISSUE THREAD

**Issue by ChinmayaAgarwal** [sysrepo/sysrepo#3224]
Hi,

In older version of sysrepo, "sysrepocfg" command has a "--merge" parameter. However, in devel branch, sysrepocfg command does not have this parameter. How can we have merge functionality with sysrepocfg in devel versions.

Thanks and Regards,
Chinmaya Agarwal.

**Comment by michalvasko** [comment]
If you use `--edit` with a file, these data will be merged.
