### ISSUE TITLE
Recursive reader limit 255 reached

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#3225]
Hi,

I ran into a situation when an application started a lot of sessions with data edit and got the following internal error:

`[ERR] Recursive reader limit 255 reached, possibly because of missing unlocks.`

It caused further failures as a consequence.
It seems that sessions with data edit increments the read_count variable in lyctx lock, and it reaches the maximum 255 value.
Although the application should not keep so many sessions, to avoid internal errors is it possible to change the type of read_count variable from uint8_t to a larger type?

It can be easily reproduced with the following application:

```
#include <sysrepo.h>

void check_result(int rc) {
  if (rc != SR_ERR_OK) {
    abort();
  }
}

int main(int argc, char **argv) {
  sr_log_stderr(SR_LL_WRN);
  sr_conn_ctx_t *connection = NULL;
  int rc = sr_connect(SR_CONN_CACHE_RUNNING, &connection);
  check_result(rc);

  for (unsigned i = 0 ; i < 255 ; i++) {
    sr_session_ctx_t *session = NULL;
    rc = sr_session_start(connection, SR_DS_RUNNING, &session);
    check_result(rc);
    rc = sr_set_item_str(session, "/ietf-system:system/hostname", "test", NULL, 0);
    check_result(rc);
  }
  sr_disconnect(connection);
  return 0;
}
```

libyang version: 2.1.147
sysrepo version: 2.2.148

Thank you in advance!

**Comment by michalvasko** [comment]
The assumption was that 255 must be enough, not sure what use-case you have for having that many concurrent sessions on a connection. Increasing it would increase the size of every structure that uses the RW lock, which are almost all so I would prefer to keep it the way it is. One workaround would be to create another connection and use that to create additional sessions.

**Comment by awesomenode** [comment]
Thank you for the quick answer!
