### ISSUE TITLE
Detecting a close-session RPC

### ISSUE THREAD

**Issue by maxrossello** [sysrepo/sysrepo#3226]
Hi,
I am trying to write netconf session monitoring as per o-ran-supervision specs.

So far I am able to get the specific netconf session id via sr_session_get_orig_data(), register to /notifications:create-subscription and /o-ran-supervision:supervision-watchdog-reset, register to /ietf-netconf:kill-session.

Nevertheless, I have two residual problems:

1. I haven't found a way to send /o-ran-supervision:supervision-notification to a specific netconf session. As a workaround to this problem I am currently just calculating the shortest interval needed among all sessions and broadcasting the notification to all registered clients via sr_notif_send(). This is more or less still compliant to the specs. Any better chance?

2. I could not register to the close-session RPC. Looks like netopeer2 closes the session before any notification gets to the sysrepo plugin. As stated above, kill-session works properly instead. Any viable options here?

Thanks a lot!

**Comment by michalvasko** [comment]
1. This requirement is not supported by NETCONF, it treats all notifications globally and sends them to all the subscribers.
2. Yes, `close-session` is handled internally but you can subscribe to the notification `ietf-netconf-notifications:netconf-session-end`, which should be generated on `kill-session` as well.

**Comment by maxrossello** [comment]
Thanks Michal, this worked perfectly.

For the records, I also succeeded to kill a supervised connection administratively using sr_rpc_send().
