### ISSUE TITLE
Malformed data in operational module, a huge sequence of `{"sysrepo:dup-inst-list-position":[null],"ietf-netconf:operation":"merge"}`

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#3227]
We just got the following error on one of our boxes:
```
libyang[0]: Invalid character sequence "],"ietf-netconf:oper", expected a JSON value. (path: Data location "/ietf-alarms:alarms/alarm-inventory/alarm-type[alarm-type-id='velia-alarms:systemd-unit-failure'][alarm-type-qualifier='']/resource", line number 1.)
The following errors occured:
 Message: Callback "load" of plugin "JSON DS file" for module "ietf-alarms" failed.
```
Here's the [content of our `/run/sysrepo/sr_ietf-alarms.operational`](https://github.com/sysrepo/sysrepo/files/13908535/sr_ietf-alarms.operational.txt), it's indeed corrupted. `jq` reports it like this:
```
jq: parse error: Expected another array element at line 1, column 66362
```

Any idea what's going on? I recall seeing a similar error at least once in a unit test as well, but it definitely doesn't happen all the time.

**Comment by michalvasko** [comment]
Are you using the latest `devel` versions of all the projects (*libyang*)? If so, I would need to reproduce this to fix it. The JSON printer will likely be at fault, there were similar problems fixed recently.

**Comment by jktjkt** [comment]
- libyang is at `fc4dbd923`
- sysrepo is at `337a6758`

I do not have a reliable reproducer. I recall seeing that in the test runs of `velia` and/or `sysrpeo-ietf-alarms` a few times. The data that I attached came from one of the lab devices we have.

**Comment by michalvasko** [comment]
I made something [more readable](https://github.com/sysrepo/sysrepo/files/13919365/sr_ietf-alarms.operational.txt) out of it but it did not help much. I think I really need the data that were printed with this bug (in XML, for example, I think it would be printed correctly that way), not sure how else to fix this.

**Comment by jktjkt** [comment]
There are no external data that are being printed by libyang, it's an error that's reported from sysrepo as a result of a corruption of its SHM data. We're building with `SR_SHM_DIR` set to `"/run/sysrepo"`, and the file I attached is a verbatim copy from there.

Somehow, that file (which is only ever manipulated by sysrepo APIs) gets corrupted, our daemon terminates when a subsequent API call fails, and then the our automation which was supposed to remount the `tmpfs` at `/run/sysrepo` failed to remount, so that the subsequent restart of the daemons sees the same corruption.

**Comment by michalvasko** [comment]
I understand there are no external data, these are created push operational data being printed by the JSON printed into a file. And because of a bug the printer prints invalid data. All I am saying is that I will need that data (as libyang structures, parsed from an XML file, for example) so that I can print them and debug the problem.

**Comment by vpatodia** [comment]
[o-ran-perf-manag.operational.txt](https://github.com/user-attachments/files/18673892/o-ran-perf-manag.operational.txt)
Hi Michal, 
We are facing similar issue. We see that operational DB is getting corrupted when operdB update is happening and netconf session terminates. 
Following are the libs version we are using : 
o	Sysrepo V2.10.1 
o	Libnetconf2 :  V3.5.1
o	Netopeer2-server : 2.2.28
o	Libyang :  V3.1.0

**Comment by vpatodia** [comment]
[https://github.com/sysrepo/sysrepo/issues/3534](url)
Yes after upgrade this issue is resolve. 
Updated the libyang version from 3.1.0 to 3.7.8 and sysrepo from 2.10.1 to 3.3.10 and we have stopped facing JSON DB File Error issue.
Thanks Vasko.
