### ISSUE TITLE
Memory leak while fetching items from a multi key list when specified only one key is xpath

### ISSUE THREAD

**Issue by amitnagraj** [sysrepo/sysrepo#3232]
Hi, 

I'm using sysrepo v2.2.12.

I'm seeing `libyang[1]: String "ethernet1/1" not freed from the dictionary, refcount 8` warning when tried fetching values from a multi key list when specified only one key or giving '*' as input for a key.

I'm able to reproduce the logs when added `ly_log_options(LY_LOLOG | LY_LOSTORE);` in `sr_get_item_examples.c` code.

Yang tree:
```
root@debian10:/home/amit/latest/yangs# yanglint ibos-ip-route.yang -f tree
module: ibos-ip-route
  +--rw ip-route
     +--rw vrfs
     |  +--rw vrf* [name]
     |     +--rw name      -> ../config/name
     |     +--rw config
     |     |  +--rw name?   string
     |     +--rw routes
     |        +--rw route* [ip gateway]
     |           +--rw ip         -> ../config/ip
     |           +--rw gateway    -> ../config/gateway
     |           +--rw config
     |              +--rw ip?        ibos-inet:ipv4-prefix
     |              +--rw gateway?   union
     |              +--rw metric?    uint8
     +--rw routes
        +--rw route* [ip gateway]
           +--rw ip         -> ../config/ip
           +--rw gateway    -> ../config/gateway
           +--rw config
              +--rw ip?        ibos-inet:ipv4-prefix
              +--rw gateway?   union
              +--rw metric?    uint8
```

Running datastore:
```
root@debian10:/home/amit/latest/sysrepo/examples# sysrepocfg -X -m ibos-ip-route -f json
{
  "ibos-ip-route:ip-route": {
    "routes": {
      "route": [
        {
          "ip": "1.1.1.1/24",
          "gateway": "ethernet1/1",
          "config": {
            "ip": "1.1.1.1/24",
            "gateway": "ethernet1/1"
          }
        },
        {
          "ip": "2.2.2.2/23",
          "gateway": "ethernet1/1",
          "config": {
            "ip": "2.2.2.2/23",
            "gateway": "ethernet1/1"
          }
        },
        {
          "ip": "1.1.1.1/24",
          "gateway": "et1/4/vid1",
          "config": {
            "ip": "1.1.1.1/24",
            "gateway": "et1/4/vid1"
          }
        },
        {
          "ip": "2.2.2.2/23",
          "gateway": "et1/4/vid1",
          "config": {
            "ip": "2.2.2.2/23",
            "gateway": "et1/4/vid1"
          }
        }
      ]
    }
  }
}
```

Logs:
```
root@debian10:/home/amit/latest/sysrepo/examples# ./get /ibos-ip-route:ip-route/routes/route[gateway=\'ethernet1/1\']
Application will get "/ibos-ip-route:ip-route/routes/route[gateway='ethernet1/1']" from "running" datastore.

/ibos-ip-route:ip-route/routes/route[ip='1.1.1.1/24'][gateway='ethernet1/1'] (list instance)
/ibos-ip-route:ip-route/routes/route[ip='2.2.2.2/23'][gateway='ethernet1/1'] (list instance)
libyang[1]: String "ethernet1/1" not freed from the dictionary, refcount 8

root@debian10:/home/amit/latest/sysrepo/examples# ./get /ibos-ip-route:ip-route/routes/route[ip=*][gateway=\'ethernet1/7\']
Application will get "/ibos-ip-route:ip-route/routes/route[ip=*][gateway='ethernet1/7']" from "running" datastore.

libyang[1]: Node type container "config" used as operand.
libyang[1]: Previous warning generated by XPath subexpression[37] "ip=*][gateway='ether" with context node "/".
libyang[1]: String "ethernet1/7" not freed from the dictionary, refcount 8
```

The same is not visible when the datastore is empty.

Please let me know if I'm missing something.

Thanks,

**Comment by michalvasko** [comment]
Please provide at least the YANG so that it can be reproduced. But I would test it with the latest versions (the latest release at least) anyway, so I would suggest you do that first. The version you are using is really old so there is a good chance it has been fixed.

**Comment by amitnagraj** [comment]
I'm using sysrepo v2.2.12 and corresponding YANG(v2.1.4) version which is mentioned in release (https://github.com/sysrepo/sysrepo/releases/tag/v2.2.12)

**Comment by michalvasko** [comment]
Okay, I have tried to test it based on the provided information and could not, it worked fine. I seem to remember there were some problems like this in the past and really, the version you are using is just too old. So, my advice is to update *sysrepo* to the latest release v2.2.150 and if you can reproduce it there, let us know. Otherwise you are stuck with this leak.

**Comment by amitnagraj** [comment]
I'm still seeing the memory leak issue in latest sysrepo version (v2.2.150)

Please make sure that you have added `ly_log_options(LY_LOLOG | LY_LOSTORE);` in your `sr_get_item_example.c` file, which i mentioned in the description of this issue.

Logs:
```
root@debian10:/home/amit/latest/yangs# yanglint -v
yanglint 2.1.148
root@debian10:/home/amit/latest/yangs# sysrepoctl -V
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v2.2.150 (SO v7.23.1)

root@debian10:/home/amit/latest/yangs# ./get /ibos-ip-route:ip-route/routes/route[gateway=\'ethernet1/1\']
Application will get "/ibos-ip-route:ip-route/routes/route[gateway='ethernet1/1']" from "running" datastore.

/ibos-ip-route:ip-route/routes/route[ip='1.1.1.1/24'][gateway='ethernet1/1'] (list instance)
/ibos-ip-route:ip-route/routes/route[ip='2.2.2.2/23'][gateway='ethernet1/1'] (list instance)
libyang[1]: String "ethernet1/1" not freed from the dictionary, refcount 8
```

Please find the all the yang files, JSON payload and c file in below zip file to reproduce the same.
[memory_leak_issue.zip](https://github.com/sysrepo/sysrepo/files/14053126/memory_leak_issue.zip)

Steps to reproduce:
1. sysrepoctl -i ibos-interfaces.yang -s .
2. sysrepoctl -i ibos-ip-route.yang -s .
3. sysrepocfg --import=interfaces.json -m ibos-interfaces -f json
4. sysrepocfg --import=ip-route.json -m ibos-ip-route -f json
5. gcc -o get -lsysrepo -lyang sr_get_items_example.c
6. ./get /ibos-ip-route:ip-route/routes/route[gateway=\'ethernet1/1\']

Thanks,

**Comment by michalvasko** [comment]
You are right, and with these steps I had no problems reproducing and fixing it, thanks. If you miss it, the problem was in *libyang* so you need to use the latest `devel` for it to be fixed.
