### ISSUE TITLE
Subscribe for changes with different users

### ISSUE THREAD

**Issue by tbsuht** [sysrepo/sysrepo#3235]
Hi,

I have multiple modules which have the following ownership and permissions: `root:sysrepo-networking` and `664`.

A user like `www-data`, which is part of the `sysrepo-networking` group can read the modules without problems.
What do I need to configure in order to subscribe for changes with the same user? I currently get the error:
```
mkfifo() failed (Permission denied).: System function call failed
```

**Comment by michalvasko** [comment]
What *sysrepo* version are you using? Can you post the owner/group/permissions of your *sysrepo* repository and directories in it?

**Comment by tbsuht** [comment]
It's `2.2.148`.

```
# ls -al /etc/sysrepo
total 4
drwxr-xr-x 1 root root  240 Jan  1 00:00 .
drwxr-xr-x 1 root root   60 Jan  1 00:00 ..
drwxrwxrwx 1 root root  120 Jan  1 01:36 conn
drwxrwxrwx 1 root root   80 Jan  1 00:00 data
prw--w--w- 1 root root    0 Jan  1 00:00 sr_evpipe1
prw--w--w- 1 root root    0 Jan  1 00:00 sr_evpipe2
prw--w--w- 1 root root    0 Jan  1 00:00 sr_evpipe3
prw--w--w- 1 root root    0 Jan  1 00:00 sr_evpipe4
prw--w--w- 1 root root    0 Jan  1 00:00 sr_evpipe5
prw--w--w- 1 root root    0 Jan  1 00:00 sr_evpipe6
prw--w--w- 1 root root    0 Jan  1 00:00 sr_evpipe7
-rw-rw-rw- 1 root root    0 Jan 26  2024 sr_main_lock
drwxr-xr-x 3 root root 4096 Jan 26  2024 yang
```

**Comment by michalvasko** [comment]
Have you used (set) `SYSREPO_GROUP` compilation variable?

**Comment by tbsuht** [comment]
No, only `SRPD_PLUGINS_PATH` and `SYSTEMD_UNIT_DIR` are used during compilation.

**Comment by michalvasko** [comment]
Okay, then if you have set `SYSREPO_GROUP` to `sysrepo-networking`, it should have worked (but then all the *sysrepo* process owners should be a member of this group, which seems is the purpose of it in your case). You should be able to fix it manually by running
```
sudo chown root:sysrepo-networking /etc/sysrepo
sudo chown root:sysrepo-networking /etc/sysrepo/conn
sudo chown root:sysrepo-networking /etc/sysrepo/data
sudo chown root:sysrepo-networking /etc/sysrepo/yang
```

**Comment by tbsuht** [comment]
`chmod g+w /etc/sysrepo` was missing for testing it, now its working thanks! :)

I guess this is available if I compile it with `SYSREPO_GROUP=sysrepo-networking`?

**Comment by michalvasko** [comment]
Then all these directories should automatically be created with the specified group as owner so you always have access to them.

**Comment by tbsuht** [comment]
Perfect, thanks!

**Comment by tbsuht** [comment]
@michalvasko I need to reopen this.

After compiling sysrepo with `SYSREPO_GROUP=sysrepo-owner` it looks like this:
```
# ls -al /etc/sysrepo
total 4
drwxr-xr-x 1 root root           260 Jan  1 00:00 .
drwxr-xr-x 1 root root            80 Jan  1 00:00 ..
drwxrwxrwx 1 root sysrepo-owner  140 Jan  1 00:00 conn
drwxrwxrwx 1 root sysrepo-owner   60 Jan  1 00:00 data
prw--w--w- 1 root root             0 Jan  1 00:00 sr_evpipe10
prw--w--w- 1 root root             0 Jan  1 00:00 sr_evpipe11
prw--w--w- 1 root root             0 Jan  1 00:00 sr_evpipe12
prw--w--w- 1 root root             0 Jan  1 00:00 sr_evpipe13
prw--w--w- 1 root root             0 Jan  1 00:00 sr_evpipe2
prw--w--w- 1 root root             0 Jan  1 00:00 sr_evpipe7
prw--w--w- 1 root root             0 Jan  1 00:00 sr_evpipe8
prw--w--w- 1 root root             0 Jan  1 00:00 sr_evpipe9
-rw-rw-rw- 1 root sysrepo-owner    0 Jan 29  2024 sr_main_lock
drwxr-xr-x 3 root root          4096 Jan 29  2024 yang
```

Shouldn't `/etc/sysrepo` (REPO_PATH) also be owned by `root:sysrepo-owner` now?

**Comment by michalvasko** [comment]
I expect the repository existed before. *sysrepo* just check existence/access to the directories and if it is fine, it leaves them as they are. Only when creating them it sets all the correct permissions on them. It seemed like this less-intrusive behavior is desired because it avoids problems when the user wants to use different permissions for some reason.

**Comment by tbsuht** [comment]
You're right, thanks!
