### ISSUE TITLE
Config ipv4 address(openconfig-interface-ip.yang) failed Error "Unexpected valid opaque node list "address"

### ISSUE THREAD

**Issue by songlinglingpml** [sysrepo/sysrepo#3239]
Hi @michalvasko 

I want to config ipv4 address, use openconfig-interface-ip.yang. But when I send netconf xml, it failed with error  "Unexpected valid opaque node list "address".

we are using following sysrepo and dependent lib versions:
sysrepo v2.2.36
netopeer2-server 2.1.49
libyang 2_2.1.30

### netconf command xml
```

<edit-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <target>
    <running/>
  </target>
  <config>
    <interfaces xmlns="http://openconfig.net/yang/interfaces">
      <interface>
        <name>Ethernet4</name>
        <config>
          <name>Ethernet4</name>
          <type xmlns:iana-if-type="urn:ietf:params:xml:ns:yang:iana-if-type">iana-if-type:ethernetCsmacd</type>
        </config>
        <subinterfaces>
          <subinterface>
            <index>0</index>
            <config>
              <mtu>9100</mtu>
              <description>Ethernet4 name</description>
            </config>
            <ipv4 xmlns="http://openconfig.net/yang/interfaces/ip">
              <addresses>
                <address>
                  <ip>8.8.177.28</ip>
                  <config>
                    <ip>8.8.177.28</ip>
                    <prefix-length>24</prefix-length>
                  </config>
                </address>
              </addresses>
            </ipv4>
          </subinterface>
        </subinterfaces>
      </interface>
    </interfaces>
  </config>
</edit-config>
```

### relay

```
<?xml version="1.0" encoding="utf-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="9">
  <rpc-error>
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-message xml:lang="en">Unexpected valid opaque node list "address".</error-message>
  </rpc-error>
  <rpc-error>
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-message xml:lang="en">User callback failed.</error-message>
  </rpc-error>
</rpc-reply>
```

![1706858616693](https://github.com/sysrepo/sysrepo/assets/62629271/eb781aae-0e8f-4ebe-8648-3a7ef399fe35)

**Comment by songlinglingpml** [comment]
### netconf command xml

### relay info
![1706858859497](https://github.com/sysrepo/sysrepo/assets/62629271/5174eb2d-5cc3-4e44-8662-0f615facd247)

**Comment by michalvasko** [comment]
It all depends on the YANG modules you are using, I am guessing that `address` has a different key than `ip` or something like that.

**Comment by songlinglingpml** [comment]
> It all depends on the YANG modules you are using, I am guessing that `address` has a different key than `ip` or something like that.

The yang content like this, address only have one key: ip
`
    container ipv4 {
      description
        "Parameters for the IPv4 address family.";

      container addresses {
        description
          "Enclosing container for address list";

        list address {
          key "ip";
          description
           "The list of configured IPv4 addresses on the interface.";

          leaf ip {
            type leafref {
              path "../config/ip";
            }
            description "References the configured IP address";
          }

          container config {
            description "Configuration data for each configured IPv4
            address on the interface";

            uses ipv4-address-config;

          }

          container state {

            config false;
            description "Operational state data for each IPv4 address
            configured on the interface";

            uses ipv4-address-config;
            uses ipv4-address-state;
          }

        }
      }
`
And pyyang generate tree：
![1706866075989](https://github.com/sysrepo/sysrepo/assets/62629271/890159a8-a553-4592-b37d-4dd34c0e3825)

Is there any other possible reason？

**Comment by michalvasko** [comment]
If you provide the YANG modules (and all their imports) I can tell you exactly because I could not reproduce it (have tried it with some revisions that did not define `mtu` node).

**Comment by songlinglingpml** [comment]
[yang.zip](https://github.com/sysrepo/sysrepo/files/14138443/yang.zip)

My yang file is in the compressed file， thank you very much @michalvasko
Or you can delete mtu attribute

**Comment by michalvasko** [comment]
My version (current) prints the error
```
[ERR]: SR: Unsatisfied pattern - "8.8.177.28" does not conform to "^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$". (Data location "/openconfig-interfaces:interfaces/interface[name='Ethernet4']/subinterfaces/subinterface[index='0']/openconfig-if-ip:ipv4/addresses/address/ip".)
```
and the reason being discussed in https://github.com/openconfig/public/issues/44.

**Comment by songlinglingpml** [comment]
Can you tell me your current version(sysrep libyang and netopeer2), which tag?  I will download all of them and have a try. 
But other modules in my system that rely on libyang need to be the current version(libyang 2_2.1.30), I'm not sure if it's possible to upgrade.

**Comment by songlinglingpml** [comment]
Thansk for you replay!
 I cannot upgrade  to the latest version. When I upgrade, I have encountered issues, such as OpenSSL and libyang have already been used by other modules in the linux system.
Are there any other suggestions ? Which patch in sysrepo or libyang I merge to, maybe can solve this problem? @michalvasko

**Comment by michalvasko** [comment]
> When I upgrade, I have encountered issues, such as OpenSSL and libyang have already been used by other modules in the linux system.

I do not understand, why should a newer version cause problems, you have packages that depend on an exact *libyang* version instead of specifying a minimal supported version?

But, strictly speaking, an update will not solve your problem, the value will still fail to load because the `pattern` is in an unsupported format (described in the issue I have referenced, please read it).

**Comment by songlinglingpml** [comment]
I upgrade to this version tag: netopeer v2.1.71, sysrepo v2.2.105, libyang v2.1.111, and now prints the pattern error. For this issue you have referenced above, I will try some  methods mentioned in that issue.
Thanks for your help.
