### ISSUE TITLE
Getting error while running sysrepod

### ISSUE THREAD

**Issue by rajnkamr** [sysrepo/sysrepo#324]
I have cross compiled daemon on x86 arch and now trying to run on target box but getting below error
All required libs are copied to the box. 
./sysrepod
**Failure by initialization of sysrepo daemon**

Please let me know wht could be the cause.

**Comment by rajnkamr** [comment]
Only step i am not doing is make install since it is cross compiled.

**Comment by rastislavszabo** [comment]
Hi,
please run the daemon in debug mode and collect the logs:

`./sysrepod -d -l4`

Thanks,
Rastislav

**Comment by rajnkamr** [comment]
Thanks a lot.
It was giving below error
 libyang[1]: Unable to use search directory "/root/sysrepo/build/repository/yang/internal/" (No such file or directory)

So if we do not do "make install" we have to manually create this folder and copy yang file.
After that it worked.
