### ISSUE TITLE
Internal error while subscription to a notif and processing it at the same time

### ISSUE THREAD

**Issue by Krisscut** [sysrepo/sysrepo#3241]
Hello there,

_Versions:_
**Netopeer2-server:** netopeer2-2.1.71
**sysrepo:** sysrepo-2.2.105 
**libnetconf2:** libnetconf2-2.1.37
**libyang:** libyang-2.1.111

We noticed a sporadic issue in our environment where it seems there is some kind of concurrency issue where a software is trying to subscribe to a notification when that kind of notification is broadcasted, and it causes an internal error that later on cause all the notification to be blocked. (occurrence is something like 1 in 20 runs)

For some context, regarding the **ietf-netconf-notification**, we have 4 subs on it, 2 from orusw which is a C based application, and 1 from CallHomeManager and another one from UserManagement which are python based application. (Using sysrepo-python 1.5.0)
As you can see on the following image, while the python based services are starting, there is the message "**subscription created after the notification**" which is followed by an shm_sub internal error
![2024-02-05_20-02-58](https://github.com/sysrepo/sysrepo/assets/8125922/18c21eb4-1785-4c34-8495-cce694039fc8)
![2024-02-05_20-05-08](https://github.com/sysrepo/sysrepo/assets/8125922/9cb12dad-c769-4400-b500-4c8cbb34bf4b)

I attached an extract from the logs as well to have more context if necessary
[extract_sysrepo_issue.txt](https://github.com/sysrepo/sysrepo/files/14170875/extract_sysrepo.txt)

Note that I'm aware that this isn't the latest version, we are in the process of upgrading the stack to the latest software.

I just wanted to raise awareness on this specific issue if you think this is something that you modified since that version and updating would fix it or it is still relevant with latest version ?

**Comment by michalvasko** [comment]
There is a good chance it has been fixed in the latest version. In any case, notifications were significantly refactored so this issue is not relevant unless it is reproduced in the current version.

**Comment by Krisscut** [comment]
Ok thanks for confirming ! I will keep this open and close it if not reproduced on latest version.
