### ISSUE TITLE
Is it possible to have concurrent candidate datastore for each netconf session/ user?

### ISSUE THREAD

**Issue by MoshikaKarthesan** [sysrepo/sysrepo#3243]
Is it possible to have concurrent candidate DB for each netconf session/ user?
If "yes", What is the sysrepo version which supports the same?

**Comment by michalvasko** [comment]
No, we chose a shared candidate datastore implementation.

**Comment by MoshikaKarthesan** [comment]
Will it be possible to do customization for the same on top of existing sysrepo. Do you foresee any major issues which we will face?

**Comment by michalvasko** [comment]
No, I think it should not be difficult to implement with some internal *sysrepo* knowledge.
