### ISSUE TITLE
sr_get_node fails when pointing to a leaf-list path

### ISSUE THREAD

**Issue by amamory** [sysrepo/sysrepo#3245]
Let's say we have this YANG module where one path is a leaf-list and the 2nd one is a leaf

```
module test_examples {
    namespace "urn:test_examples";
    prefix e;

    container cont {
        leaf-list l {
            type string;
        }
    }

    container stats {
        config true;
        leaf counter {
            type uint64;
        }

    }
}
```

When i run *sr_get_node*  on the leaf, it works as expected. However, when i repeat the same operation on a leaf-list, I see 
**Invalid argument** (SR_ERR_INVAL_ARG) error. My understanding is that this function is very close to *sr_get_data*, which also works w leaf-list. So, i expect *sr_get_node* to work on any type of path.

I also notice that *sr_get_node* has no test, no examples. It doesn't seem to be a common function. So, i was wondering if this is a bug ....

best regards,

**Comment by michalvasko** [comment]
Print the actual error message to learn the reason for the error.

**Comment by amamory** [comment]
I updated the original description to make it clear that it refers to SR_ERR_INVAL_ARG error code.
Is that what you meant ?

**Comment by michalvasko** [comment]
No, I meant an actual error message. Unless you passed `NULL` as one of the parameters, there is also a detailed error, which is printed if you enable it using `sr_log_stderr()` or you can retrieve it in a structure from the `session` using `sr_session_get_error()`.

**Comment by amamory** [comment]
I am running with 
```
sr_log_stderr(SR_LL_DBG);
```

the piece of code is only this, that can be easily added to any existing examples

```
    printf("sr_get_node ...\n");
    rc = sr_get_node(session, xpath, 0, &node_data);
    if (rc != SR_ERR_OK)
    {
        printf("sr_get_node (running) error: %d - %s\n", rc, sr_strerror(rc));
    }
    printf("sr_get_node (running) done\n");
```

the session datastore doesnt matter. i tried several and the result is the same

and the printed result is :
```
sr_get_node ...
[ERR] More nodes match "/test_examples:cont/l".
sr_get_node (running) error: 1 - Invalid argument
sr_get_node (running) done
```

please, let me know if you need further info

**Comment by michalvasko** [comment]
I am not sure what is unclear about this then. There is the error:
```
[ERR] More nodes match "/test_examples:cont/l".
```
and there is even a clear documentation
https://github.com/sysrepo/sysrepo/blob/d57c49551fbc177bf07451f50461bf4319764692/src/sysrepo.h#L837-L840

**Comment by amamory** [comment]
I see, `sr_get_node` can only be used for leafs, is that it ?

If that so, The fact that it returns `sr_data_t ` instead of `sr_val_t ` might seen a bit misleading. 
I was also influenced by this part of the doc 
```
  *Compared to ::sr_get_data() or ::sr_get_subtree() this function is a bit more efficient because it returns*
```

Which made me believe that `sr_get_node` was equivalent to `sr_get_data`.  But perhaps, it's more similar to `sr_get_item` ?!?!

thank you for the clarification !
