### ISSUE TITLE
About sr_oper_get_subscribe: entering callback function multiple times

### ISSUE THREAD

**Issue by fandy-fandongyang** [sysrepo/sysrepo#3246]
Hello,
 I used sr_oper_get_subscribe function as follows.

Yang tree: 
module: openconfig-platform
  +--rw components
     +--rw component* [name]
        +--rw name                  -> ../config/name
        +--rw power-supply
        |  +--rw config
        |  +--ro state

```
    pcXpath = "/openconfig-platform:components/component/power-supply/state"
    rc = sr_oper_get_subscribe(m_pstRunningSess, module, pcXpath, fCallback,
                                     pvPrivateCtx, SR_SUBSCR_OPER_MERGE, &m_pstStateSubscription);


/* fCallback */
static int
__PsuDataProviderCb(sr_session_ctx_t *pstSession, uint32_t sub_id, const char *pcModuleName, const char *pcXpath,
                        const char *pcOriginalXpath, uint32_t ullRequestId, struct lyd_node **pstParent, void *pvPrivateCtx)
{
     return 0;
}
```

When list component has multiple elements,  the fCallback will be called mutiple times. But can't unable to identify through the _pcXpath_ or _pcOriginalXpath_, because the pcXpath always the same as "/openconfig-platform:components/component/power-supply/state", and the _pcOriginalXpath_ also not included the  commonent/name. So in the fCallback, every return _pstParent_ must contain all of the component/name's result. is very low efficiency.

Can you tell me how to identify the component/name from the xpath in the fCallback.
@michalvasko

**Comment by michalvasko** [comment]
You always get the **parent** data tree in `pstParent`, in your case. So, when called, `pst_parent` points to `/openconfig-platform:components/component/power-supply`. To get your `component` `name`, you can use
```C
struct lyd_node *component = lyd_parent(*pstParent);
const char *name = lyd_get_value(lyd_child(component)); // keys are always the first children
```

**Comment by fandy-fandongyang** [comment]
> You always get the **parent** data tree in `pstParent`, in your case. So, when called, `pst_parent` points to `/openconfig-platform:components/component/power-supply`. To get your `component` `name`, you can use
> 
> ```c
> struct lyd_node *component = lyd_parent(*pstParent);
> const char *name = lyd_get_value(lyd_child(component)); // keys are always the first children
> ```

Thank you very much! @michalvasko
