### ISSUE TITLE
Segmentation fault - Program terminated with signal 11, Segmentation fault.

### ISSUE THREAD

**Issue by MoshikaKarthesan** [sysrepo/sysrepo#3249]
Received segmentation fault

Core was generated by `sysapp'.
Program terminated with signal 11, Segmentation fault.
#0  0x0177a158 in pthread__mutex_spin (ptm=0x787db054, owner=0x7f000000) at /home/builder/tagbuild/xxx/lib/libpthread/pthread_mutex.c:202
202			if (thread->pt_lwpctl->lc_curcpu == LWPCTL_CPU_NONE ||
#1  0x0177a794 in pthread__mutex_lock_slow (ptm=0x787db054) at /home/builder/tagbuild/xxx/lib/libpthread/pthread_mutex.c:240
240			owner = pthread__mutex_spin(ptm, owner);
#2  0x017ce188 in sr_rwlock_reader_add (rwlock=0x787db020, cid=43) at /home/builder/tagbuild/xxx/dist/sysrepo/libsysrepo/src/common.c:4302
4302	    ret = pthread_mutex_lock(&rwlock->r_mutex);
#3  0x017cfd04 in _sr_rwlock (rwlock=0x787db020, timeout_ms=10000, mode=, cid=43, func=0x286c6d8 "sr_subscription_process_events", cb=0x17a3dcc , cb_data=0x7fff6e2c, has_mutex=0) at /home/builder/tagbuild/xxx/dist/sysrepo/libsysrepo/src/common.c:4593
4593	        sr_rwlock_reader_add(rwlock, cid);
#4  0x017cffe4 in sr_rwlock (rwlock=, timeout_ms=, mode=, cid=, func=0x286c6d8 "sr_subscription_process_events", cb=0x17a3dcc , cb_data=0x7fff6e2c) at /home/builder/xxx/dist/sysrepo/libsysrepo/src/common.c:4622
4622	    return _sr_rwlock(rwlock, timeout_ms, mode, cid, func, cb, cb_data, 0);
#5  0x017b92d4 in sr_lycc_lock (conn=, mode=SR_LOCK_READ, lydmods_lock=0, func=0x286c6d8 "sr_subscription_process_events") at /home/builder/tagbuild/xxx/dist/sysrepo/libsysrepo/src/context_change.c:58
58	    if ((err_info = sr_rwlock(&main_shm->context_lock, SR_CONTEXT_LOCK_TIMEOUT, mode, conn->cid, func,
#6  0x017905a8 in sr_subscription_process_events (subscription=0x78651100, session=0x78675140, wake_up_in=0x0) at /home/builder/xxx/dist/sysrepo/libsysrepo/src/sysrepo.c:4645
4645	    if ((err_info = sr_lycc_lock(subscription->conn, SR_LOCK_READ, 0, __func__))) {
#7  0x0072e6d4 in main (argc=, argv=) at /home/builder/tagbuild/xxx/sysapp/main.c:283
283	        sr_subscription_process_events(subs, sess, NULL);
#8  0x00400794 in __start ()

__mlassert_str: $1 = '\000' 
What could be the possible cause for this crash?
We have done customizations on top of sysrepo.

**Comment by MoshikaKarthesan** [comment]
libyang   - v2.1.4
sysrepo  - v2.2.12
libssh     - v0.9.0
Libnetconf2 - v2.1.25
netopeer2- v2.1.42

**Comment by michalvasko** [comment]
That is quite old so the only advice I have is to update it or make sure it is not caused by your changes, I have never encountered such a crash.
