### ISSUE TITLE
Module ietf-yang-instance-data caused sysrepo to fail

### ISSUE THREAD

**Issue by trentzhou** [sysrepo/sysrepo#3252]
I built libyang and sysrepo yesterday. I met this problem:

```
root@6225c3802a30:/code/standard/ietf/RFC# sysrepoctl -s. -i ietf-yang-instance-data.yang
root@6225c3802a30:/code/standard/ietf/RFC# sysrepoctl -l
[ERR] Invalid default - value does not fit the type (Unsatisfied pattern - "2022-01-20" does not conform to "\\d{4}-(1[0-2]|0[1-9])-(0[1-9]|[1|2][0-9]|3[0-1])".). (Schema location "/ietf-yang-instance-data:format-version".)
sysrepoctl error: Failed to connect (libyang error)
For more details you may try to increase the verbosity up to "-v3".
```

The yang code was fetched from https://github.com/YangModels/yang.

I had to remove the default value to make sysrepo work.

**Comment by trentzhou** [comment]
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v2.2.150 (SO v7.23.1)

**Comment by michalvasko** [comment]
Thanks for reporting this, there were quite significant problems with quoted string handling. If you use current *libyang* `devel`, it should work.

**Comment by michalvasko** [comment]
manually replace the `ietf-yang-instance-data` YANG module in *sysrepo* `repository/yang` with the original file, it was printed incorrectly (but use the exact same name it has, with the revision).
