### ISSUE TITLE
Getting delta of candidate and running datastores

### ISSUE THREAD

**Issue by MoshikaKarthesan** [sysrepo/sysrepo#3261]
Currently I could see that get-config of candidate db before/after commit displays data from running db too.
Is it possible to get only the diff of uncommitted changes in candidate db? Do we have any API to get the delta of 
candidate and running datastores?

**Comment by michalvasko** [comment]
The difference between `running` and `candidate` is not stored anywhere and there is no API. But if there were, *sysrepo* would simply get the diff between the contents of these 2 datastores, which you can do easily as well. Just get the YANG data of both and use `lyd_diff_siblings()` to get the diff.

**Comment by MoshikaKarthesan** [comment]
Thanks. It worked.
Is there any sysrepo API to convert the diff into data?
I want the difference to be saved as data not diff

**Comment by michalvasko** [comment]
I do not understand the intention and you cannot simply convert a `diff` into `data`. However, `diff` is only a special `data` instance with operation metadata and you can always manually remove all the metadata.

**Comment by MoshikaKarthesan** [comment]
I'm trying to write an API to display only the uncommitted changes for "show candidate-config" instead of displaying (uncommitted changes + running db) changes
