### ISSUE TITLE
API to validate XPATH

### ISSUE THREAD

**Issue by MoshikaKarthesan** [sysrepo/sysrepo#3264]
When I do sr_get_data with invalid or non-existing xpath system crashes. Is there any API to validate the xpath before 
calling sr_get_data?

**Comment by michalvasko** [comment]
Please mention the XPath you have used that caused the crash. Also mention what *sysrepo*/*libyang* versions are you using?

**Comment by MoshikaKarthesan** [comment]
libyang version v2.1.4
libsysrepo version v2.2.12

Instead of passing /igmp, I gave /ig

**Comment by michalvasko** [comment]
I see, I think has been fixed a long time ago so you would have to reproduce it with the latest release or `devel` for me to look at it. In any case, the simplest fix is to update. You could probably check the XPaths using `lys_find_xpath()` but it is completely redundant.
