### ISSUE TITLE
Does libsysrepo-API not support access to multiple YANG databases of sysrepo?

### ISSUE THREAD

**Issue by rydy** [sysrepo/sysrepo#3266]
Hi, 

I deployed two YANG databases for sysrepo, which need to be accessed through libsysrepoAPI in an application. Because libsysrepoAPI uses environment variables (SYSREPO_REPOSITORY_PATH and SYSREPO_SHM_PREFIX) to distinguish between different databases, libsysrepoAPI does not seem to support it, what should I do to support it?

Can I fix this if I reset the environment variables (SYSREPO_REPOSITORY_PATH and SYSREPO_SHM_PREFIX) before each database operation?

Thanks

**Comment by michalvasko** [comment]
The API functions will use those environment variables if you set them correctly, it is supported normally.

**Comment by rydy** [comment]
> The API functions will use those environment variables if you set them correctly, it is supported normally.

I see，Have you ever considered using API sessions/connections to differentiate between different database instances(sysrepo)?

**Comment by michalvasko** [comment]
No because the whole support of several *sysrepo* "instances" is meant only for testing and similar non-deployment use-cases.

**Comment by rydy** [comment]
> No because the whole support of several _sysrepo_ "instances" is meant only for testing and similar non-deployment use-cases.

Ok, thanks
