### ISSUE TITLE
Cannot change value using sr_apply_changes

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#3268]
Hi,

I met an issue when a value is stuck in running datastore and cannot change it anymore using `sr_apply_changes`.
I attached an example to reproduce it:
[reprod.zip](https://github.com/sysrepo/sysrepo/files/14959672/reprod.zip)

```
$ ./reprod    
setting leaf1 to true 
value: true 
setting leaf1 to false 
value: true
```

Here the  value of leaf1 remained true and changing to false has no effect.

libyang version: 2.2.10
sysrepo version: 2.2.171

Note that on older version (sysrepo v2.2.135/libyang v2.1.140) the issue was not present.

Thank you in advance!

**Comment by michalvasko** [comment]
Quite a serious bug after some optimizations, not sure how it slipped through the tests. Should be fixed, though.

**Comment by awesomenode** [comment]
Works as expected now, thank you for the quick fix!
