### ISSUE TITLE
sysrepoctl YANG parse issue

### ISSUE THREAD

**Issue by awesomenode** [sysrepo/sysrepo#3270]
Hi!

I've noticed when installing a YANG module with a specific pattern to
sysrepo, it broke the context. Any further sysrepoctl command failed
with:

>  [ERR] Invalid identifier first character '.' (0x002e). (path "/")
>  [ERR] Parsing module "test" failed.
>  [ERR] Loading "test" module failed. (path "/")
>  sysrepoctl error: Failed to connect (libyang error)

Although it seems like a libyang error, I've produced it with
sysrepoctl, that's why I opened the issue here.

I've attached the relevant module.
[test_yang.zip](https://github.com/sysrepo/sysrepo/files/14997538/test_yang.zip)

Thanks!

**Comment by michalvasko** [comment]
That is some pattern. Should work now but it will change the string formatting, NBC changes would be required to store the string exactly as it is in the input.
