### ISSUE TITLE
Not able to fetch value operational data 

### ISSUE THREAD

**Issue by biswajit84** [sysrepo/sysrepo#3272]
Hi,
I am trying to fetch the operational data .For that  I am following the steps provided in the exmple.
sysrepoctl -i examples.yang in one terminal and executed below command in another terminal.
```
#oper_data_pull_example examples /examples:stats
```
Bt after executing above,I am not getting any output.
```
Application will get "/examples" from "operational" datastore.


biswajit@netopeer:~/netopeer/sysrepo/build/examples$ 
```
But when I Execute below command I get some ouptut.
```
sudo sysrepocfg -X -d operational -x /examples:stats
<stats xmlns="urn:examples">
 <counter>852</counter>
  <counter2>1052</counter2>
</stats>
```
Let  me know if I am doing any mistake.

Regards,
Biswajit

**Comment by michalvasko** [comment]
It works correctly and you should learn more about `pull` and `push` oper data (see [docs](https://netopeer.liberouter.org/doc/sysrepo/master/html/index.html#oper_data)), you can get notified about changes in oper data only for `push` data.

**Comment by biswajit84** [comment]
Hi,
My objective is netconf-client shouldn't have permission to edit a node ,he can only read the values stored. If he tries to edit,it will throw an error. I have gone through the link. The  push operation is not fulfilling the requirement. 
Below is the output of pyang tree format. The ietf-hardware module has few rw(read write)fields which can be modified by the client and there are few ro(read only)fields which can't modified by the netconf-client only server  should have the option to change it .
 I was expecting oper_data_pull_example is supposed to fetch the values .

Any input in implementing the feature will be really helpful.


`module: ietf-hardware`
  `+--rw hardware`
     `+--ro last-change?   yang:date-and-time`
     `+--rw component* [name]`
        `+--rw name              string`
        `+--rw class             identityref`
        `+--ro physical-index?   int32 {entity-mib}?`
        `+--ro description?      string`
       ` +--rw parent?           -> ../../component/name`
        `+--rw parent-rel-pos?   int32`
        `+--ro contains-child*   -> ../../component/name`
        `+--ro hardware-rev?     string`
        `+--ro firmware-rev?     string`
        `+--ro software-rev?     string`
        `+--ro serial-num?       string`
        `+--ro mfg-name?         string`
        +--ro model-name?       string`
        `+--rw alias?            string`
        `+--rw asset-id?         string`
        +--ro is-fru?           boolean`
        `+--ro mfg-date?         yang:date-and-time`
        `+--rw uri*              inet:uri`
        `+--ro uuid?             yang:uuid`
        `+--rw state {hardware-state}?`
        `|  +--ro state-last-changed?   yang:date-and-time`
        `|  +--rw admin-state?          admin-state`
        `|  +--ro oper-state?           oper-state`
        `|  +--ro usage-state?          usage-state`
        `|  +--ro alarm-state?          alarm-state`
        `|  +--ro standby-state?        standby-state`
        `+--ro sensor-data {hardware-sensor}?`
         `  +--ro value?               sensor-value`
         `  +--ro value-type?          sensor-value-type`
         `  +--ro value-scale?         sensor-value-scale`
          ` +--ro value-precision?     sensor-value-precision`
           `+--ro oper-status?         sensor-status`
           `+--ro units-display?       string`
           `+--ro value-timestamp?     yang:date-and-time`
           `+--ro value-update-rate?   uint32`

Regards,
Biswajit

**Comment by michalvasko** [comment]
`oper_data_pull_example` is supposed to showcase how to provide some state (`ro`) data using the `pull` mechanism. As mentioned in the docs I [referenced](https://netopeer.liberouter.org/doc/sysrepo/master/html/index.html#oper_data), that is one way of doing what you want, provide some `ro` data. There is another way, which is the `push` mechanism.

If going for the `pull` callback (is simpler), then all you need to do is write a similar callback as is in the example, which will read whatever information you want from the system, create a *libyang* data tree from it, and return it.

**Comment by biswajit84** [comment]
Hi ,
I was trying the oper_data_pull_example without any modification. As per the README we need to execute  sysrepoctl -i ../repository/yang/examples.yang and then run "sudo ./oper_data_pull_example examples /examples:stats" in one terminal and then execute ./sr_get_items_example /examples:*//. operational in another terminal.
But there is no log present in oper_data_pull_example terminal and  "Application will get "/examples:*//." from "operational" datastore" only appears on execution of sr_get_items_example in other termianal.

Can you please help me what went wrong.

Regards,
Biswajit

**Comment by michalvasko** [comment]
I do not understand what you are doing exactly but here are the steps I have just tested and seem to work:
```
# start with a clean repository
make sr_clean

# install the module
sysrepoctl -i ../examples/examples.yang
```
term1
```
./examples/oper_data_pull_example examples /examples:stats
Application will provide data "/examples:stats" of "examples".



 ========== LISTENING FOR REQUESTS ==========


# printed only after sr_get_items_examples is run
 ========== DATA FOR "examples" "/examples:stats" REQUESTED =======================

```
term2
```
./examples/sr_get_items_example /examples:*//. operational
Application will get "/examples:*//." from "operational" datastore.

/examples:cont (container)
/examples:stats (container)
/examples:stats/counter = 852
/examples:stats/counter2 = 1052
```

**Comment by biswajit84** [comment]
Hi,
I am trying to execute the same way you did.
In may case I am getting only below log:
Term1:

 `  ./examples/oper_data_pull_example examples /examples:stats `

` Application will provide data "/examples:stats" of "examples". `

 ` ========== LISTENING FOR REQUESTS ========== `

Term2:
` ./examples/sr_get_items_example /examples:*//. operational
Application will get "/examples:*//." from "operational" datastore. `

Even though I am following the steps which you did.But I am not getting the same output.

Regards,
Biswajit

**Comment by biswajit84** [comment]
Hi,
I tried application_changes_example and it seems working. If its system issue, then I think none of the example should work. 
I tried uninstalling and installing again ,but its the same issue with oper_data_pull_example. Any pointer to debug the issue will be really helpful.

` Terminal 1:$ sudo ./application_changes_example examples `
` [sudo] password for biswajit: `
` Application will watch for "examples" changes in "running" datastore.`

 ` ========== READING RUNNING CONFIG: ========== `

` /examples:cont (container) `


 ` ========== LISTENING FOR CHANGES ========== ` 



 ` ========== EVENT change CHANGES: ==================================== `

` CREATED: /examples:cont/l = 24 `

 ` ========== END OF CHANGES ======================================= `

 ` ========== EVENT done CHANGES: ==================================== `

` CREATED: /examples:cont/l = 24 `

 ` ========== END OF CHANGES =======================================`

` ========== CONFIG HAS CHANGED, CURRENT RUNNING CONFIG: ==========  `

` /examples:cont (container) `
` /examples:cont/l = 24 `

Terminal 2:

` $ sudo ./sr_set_item_example /examples:cont/l 24 `
` [sudo] password for biswajit: `
` Application will set "/examples:cont/l" to "24". `

Regards,
Biswajit

**Comment by michalvasko** [comment]
I still do not understand why you are using the `root` user and I think that may the cause of the problem.

**Comment by biswajit84** [comment]
Hi ,
If I execute without sudo then it is giving write permission error as below:
./oper_data_pull_example examples /examples:stats
Application will provide data "/examples:stats" of "examples".

[ERR] Write permission "examples" check failed.

Regards,
Biswajit

**Comment by michalvasko** [comment]
You should not have installed `examples.yang` as `root` to begin with. Uninstall it (`# sysrepoctl -u examples`) and then install it again as a standard user.

**Comment by biswajit84** [comment]
Hi ,
I have installed all the packages in custom directory and sysrepo binaries are also being linked.Now its working as per expectation.

Regards,
Biswajit
