### ISSUE TITLE
factory-reset behavior

### ISSUE THREAD

**Issue by tbsuht** [sysrepo/sysrepo#3273]
Is there currently a way or could an addition be added (runtime or compile option) to customize the factory-default behavior?

> There is an internal subscription to the /ietf-factory-default:factory-reset RPC which performs the copying of factory-default data into all the other datastores.

For our use-case we don't want to copy the factory-default data into all other datastores but rather only `startup`.

**Comment by jktjkt** [comment]
Since that behavior is [described by the RFC](https://datatracker.ietf.org/doc/html/rfc8808#name-factory-reset-rpc), I wonder what exactly your use case is. Or is sysrepo maybe silently discarding, e.g., the pushed operational data from the `operational` DS?

**Comment by michalvasko** [comment]
It was implemented according to the definition of the RPC and the behavior should remain the default one. But I see no problem with adding an optional leaf-list (for example) of only those datastores that should be reset by modifying `sysrepo-factory-default@2023-02-23.yang` and then implementing the functionality. You are welcome to provide a PR.
