### ISSUE TITLE
Path is modified in ietf-netconf-acm module and it causes the nacm function to fail.

### ISSUE THREAD

**Issue by brandonwusc** [sysrepo/sysrepo#3277]
Hi All : 
I meet a problem，and i hope to receive some help，thanks。
When i import the data(ietf-netconf-acm.xml), and here is one rule for example :
```xml
<rule>
  <name>permit-ngu</name>
  <path xmlns:me3gpp="urn:3gpp:sa5:_3gpp-common-managed-element"
        xmlns:gnbcuup3gpp="urn:3gpp:sa5:_3gpp-nr-nrm-gnbcuupfunction"
        xmlns:nrnrmep="urn:3gpp:sa5:_3gpp-nr-nrm-ep">/me3gpp:ManagedElement[id='1']/gnbcuup3gpp:GNBCUUPFunction[id='1']/nrnrmep:EP_NgU[id='1']/attributes/remoteAddress</path>
  <access-operations>read update</access-operations>
  <action>permit</action>
  <comment>Allow the limited group read/update access to the NgU remote ip.</comment>
</rule>
```
and it seems import successfully, the data in sysrepocfg like this:
```xml
<rule>
  <name>permit-ngu</name>
  <path xmlns:me3gpp="urn:3gpp:sa5:_3gpp-common-managed-element" xmlns:gnbcuup3gpp="urn:3gpp:sa5:_3gpp-nr-nrm-gnbcuupfunction" xmlns:ep3gpp="urn:3gpp:sa5:_3gpp-nr-nrm-ep">/me3gpp:ManagedElement[me3gpp:id='1']/gnbcuup3gpp:GNBCUUPFunction[gnbcuup3gpp:id='1']/ep3gpp:EP_NgU[ep3gpp:id='1']/ep3gpp:attributes/ep3gpp:remoteAddress</path>
  <access-operations>read update</access-operations>
  <action>permit</action>
  <comment>Allow the limited group read/update access to the NgU remote ip.</comment>
</rule>
```
And the nacm function will works fine. And i export the rule to a new xml and it is the same with the data in sysrepocfg;
If i import the new xml again, the sysrepocfg will be the same, but when i read the rule through `lyd_tree_dump_from_node`, the path will be modified:
`/_3gpp-common-managed-element:ManagedElement[id='1']/_3gpp-nr-nrm-gnbcuupfunction:GNBCUUPFunction[id='1']/_3gpp-nr-nrm-ep:EP_NgU[id='1']/attributes/remoteAddress` 
will be modifed like: 
`/_3gpp-common-managed-element:ManagedElement[_3gpp-common-managed-element:id='1']/_3gpp-nr-nrm-gnbcuupfunction:GNBCUUPFunction[_3gpp-nr-nrm-gnbcuupfunction:id='1']/_3gpp-nr-nrm-ep:EP_NgU[_3gpp-nr-nrm-ep:id='1']/_3gpp-nr-nrm-ep:attributes/_3gpp-nr-nrm-ep:remoteAddress`
Besides ,the diff will like this:
```xml
<path yang:operation="replace" yang:orig-default="false" yang:orig-value="/_3gpp-common-managed-element:ManagedElement[id='1']/_3gpp-nr-nrm-gnbcuupfunction:GNBCUUPFunction[id='1']/_3gpp-nr-nrm-ep:EP_NgU[id='1']/attributes/remoteAddress" xmlns:me3gpp="urn:3gpp:sa5:_3gpp-common-managed-element" xmlns:gnbcuup3gpp="urn:3gpp:sa5:_3gpp-nr-nrm-gnbcuupfunction" xmlns:ep3gpp="urn:3gpp:sa5:_3gpp-nr-nrm-ep">/me3gpp:ManagedElement[me3gpp:id='1']/gnbcuup3gpp:GNBCUUPFunction[gnbcuup3gpp:id='1']/ep3gpp:EP_NgU[ep3gpp:id='1']/ep3gpp:attributes/ep3gpp:remoteAddress</path>
```
It seems all the attributes will be added the namespace, And the NACM function will be something wrong. 
Br
Brandonsc

**Comment by michalvasko** [comment]
All I see is the same path once in XML format (with all the nodes prefixed) and then in JSON format (with the same prefixes inherited and omitted). What exactly is the problem?

**Comment by brandonwusc** [comment]
Sorry for my delay, what i means you can see when we import the xml to our sysrepo, The xpath in nacm module is wrong, For example, the "attributes" will add the prefix. I'm not sure if this is normal, because when the path in sysrepo add the prefix, the nacm will have issue, it can not compare the path in our sysrepo.

**Comment by michalvasko** [comment]
Always look at what namespace is actually represented by a prefix. *libyang* does not preserver your prefixes but instead generates them based on YANG recommendations meaning it uses the YANG module prefixes they define themselves.

Also, I suggest you use a prefix for all the nodes because the default namespace may not be what you expect it is.

**Comment by brandonwusc** [comment]
I think every nodes can have a prefix, it is understandable. But if all the nodes have prefix ,the NACM function will not recognize the path, it is strange.

**Comment by michalvasko** [comment]
Unless you have used the wrong prefix, it definitely should work. Another thing maybe, what *sysrepo* version are you using?

**Comment by brandonwusc** [comment]
libsysrepo v2.0.1 (SO v6.0.1)

**Comment by michalvasko** [comment]
Okay, that is your problem, the version is ancient and there were lots of NACM improvements and fixes since then.

**Comment by brandonwusc** [comment]
Ok, Maybe i should update and try, or i will check the changlist to find when fix the issue.
