### ISSUE TITLE
sr_apply_changes function return value 

### ISSUE THREAD

**Issue by hi-Mr-ye** [sysrepo/sysrepo#3279]
Hi
I call the sr_apply_changes function to set the node value (port-power/max node), and the return value is 14. Then, when I call the sr-apply_changes function again to set the node value (enable node), it will trigger the callback function of the port dump node. At the same time, the return value of sr-apply_changes is 14.
but why?
sr-apply_changes function set port-power/max node
![image](https://github.com/sysrepo/sysrepo/assets/90752673/6616a429-0514-4918-a84e-375b853540d2)

Print using the sr-apply_changes function again：
![image](https://github.com/sysrepo/sysrepo/assets/90752673/24be84e3-0c94-4117-9e0d-f72f6df13046)

**Comment by michalvasko** [comment]
Read the function [docs](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__edit__data__api.html#gad893705de698d113d85fcc74acfccb8b). TLDR; Call `sr_discard_changes()` after the failed `sr_apply_changes()` call.

**Comment by hi-Mr-ye** [comment]
Okay, I have a question? Why does it trigger the callback function for setting nodes using sr_apply_changes again

**Comment by michalvasko** [comment]
Because the original change remains in the session and is applied again on the next `sr_apply_changes()` call, that is what the docs say.

**Comment by hi-Mr-ye** [comment]
Thank you for your answer. 
There seems to be no relevant examples in the documentation for using sr_discard_changes
Is sr_discard_changes and sr_session_switch_ds used together? When the return value of sr-apply_changes is not 0?

**Comment by michalvasko** [comment]
> There seems to be no relevant examples in the documentation for using sr_discard_changes

Well, the concept is really simple but mentioned only in the general [docs](https://netopeer.liberouter.org/doc/sysrepo/master/html/edit_data.html).

All the changes are only prepared and stored in the session, which are then applied by `sr_apply_changes()`. If it fails, the changes are **not** discarded on their own and you can do so with `sr_discard_changes()`. Naturally, whatever DS is set for the session, only changes for that DS are discarded.

**Comment by hi-Mr-ye** [comment]
Thank you for your answer.
