### ISSUE TITLE
question: can we parse and print edit-config or edit-data before pushing into the sysrepo database. 

### ISSUE THREAD

**Issue by samba2127** [sysrepo/sysrepo#3281]
Hi,

is it possible to write my validations check function ? if yes please let me know  where can i write my own validate function for each module to validate without using the default or range values.

Thanks
Samba

**Comment by michalvasko** [comment]
> validate without using the default or range values

It is not possible to avoid the standard YANG validation, you can only add your own.

> is it possible to write my validations check function ?

The direct approach is to write standard *sysrepo* module change callbacks when you have the option to validate and refuse the configuration changes on the `SR_EV_CHANGE` event.

**Comment by samba2127** [comment]
Hi Michal,
Can I achieve to revert back the configuration in case of validation failes?
Can I get any examples for this? Do in need to pass this in the function sr_module_change_subscribe

Thanks
Samba

**Comment by michalvasko** [comment]
Yes, the configuration is fully refused (not reverted because it is not applied yet), see the [docs](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__change__subs__api.html#gad007e862874bda7141c58ca72d8c1067). There are no specific examples of this because there is nothing to it. Just call `sr_module_change_subscribe()` with your callback (an example of that can be found [here](https://github.com/sysrepo/sysrepo/blob/master/examples/application_changes_example.c)) and return an error code (not `SR_ERR_OK`) from the callback in case your validation fails. The rest is handled by *sysrepo*.

**Comment by samba2127** [comment]
How to send a delete operation for humidity operation using following yang module

module example {
    namespace "urn:example";
    prefix ex;

    container exam {

    leaf humidity {
        type uint8 {
            range "0..100";
        }
        description "Relative humidity percentage";
    }

    leaf pressure {
        type uint16 {
            range "800..1200";
        }
        description "Atmospheric pressure in millibars";
    }
    leaf temperature {
         type uint16;
         description "termprature";
    }
    leaf day {
         type string;
         description "temperature of the day";
    }
  }
}
Thanks
Samba

**Comment by michalvasko** [comment]
I am not here to explain NETCONF or YANG, please read the [specs](https://datatracker.ietf.org/doc/html/rfc6241#section-7.2).

**Comment by samba2127** [comment]
Hi Michal,

User authentication is failing when I try to connect from Netconf cli. I am able to connect through root user and password . Do we need to enable anything for user authentications in the code?

Thanks,
Samba

**Comment by michalvasko** [comment]
If you are asking about connecting and authenticating to *netopeer2-server* they yes, you need to configure the authentication mechanisms in its YANG configuration stored in *sysrepo*. You can manually edit the configuration using `sysrepocfg -E vim -m ietf-netconf-server`, for example. You can find example segments of the supported configuration in `netopeer2/example_configuration/ssh_listen.xml`.

**Comment by samba2127** [comment]
Yes Michal. Thank you
Here can we use only one authentication or can we use multiple?

<users>
                <user>
                  <name>root</name>
                  <keyboard-interactive xmlns="urn:cesnet:libnetconf2-netconf-se
                    <use-system-auth/>
                  </keyboard-interactive>
                </user>
              </users>

Thanks,
Samba

**Comment by michalvasko** [comment]
In the current [SSH server YANG module](https://github.com/CESNET/libnetconf2/blob/master/modules/ietf-ssh-server%402023-12-28.yang#L232) a specific **single** authentication method must be configured for **each** user. Meaning you need to select only one method for a user but each user can have a different authentication method.

**Comment by samba2127** [comment]
I am not able to delete the list inside container. Could you please check and let me is anything error in my xml file.
Getting the success message but in server showing the following message

[INF]: SR: No "running" datastore changes to apply.
[INF]: SR: EV LISTEN: "/ietf-netconf:edit-config" "rpc" ID 6 priority 0 success (remaining 0 subscribers).
[INF]: SR: EV ORIGIN: "/ietf-netconf:edit-config" "rpc" ID 6 priority 0 succeeded.

Here is the yang and xml file:

module TEJASFPTEMPLATE-MIB {

  namespace "urn:TEJASFPTEMPLATE-MIB";
  prefix "tejasfptemplate-mib";



  import ietf-inet-types {
    prefix "inet";
  }

  import ietf-yang-types {
    prefix "yang";
  }

  typedef Fixed2 {
    type int32;
    description
     "Represents a fixed decimal as an integer that is one
      hundred times the float value.";
  }

  typedef String16 {
    type binary {
      length "16";
    }
    description
     "Represents an Octet String consisting of 16 octets.";
  }

  container tejasFPTemplateTable {

      list tejasFPTemplateEntry {
      key "cI sI sN fPTemplateID";
        description
         "An entry in the FPTemplate Table.";

        leaf cI {
          type int32;
          description
           "Chassis Index";
        }

        leaf sI {
         type int32;
          description
           "Slot Index";
        }

        leaf sN {
          type int32;
          description
           "Parent SN";
        }

        leaf fPTemplateID {
          type int32;
          description
           "The identifier for this FP template.";
        }

        leaf description {
          type string;
          description
           "The name associated with this FP template.";
        }
    }
  }
}

<tejasFPTemplateTable xmlns="urn:TEJASFPTEMPLATE-MIB" xc:operation="delete">
     <tejasFPTemplateEntry >
      <cI>100</cI>
      <sI>40</sI>
      <sN>50</sN>
      <fPTemplateID>60</fPTemplateID>
      <description>tejas</description>
    </tejasFPTemplateEntry>
</tejasFPTemplateTable>

Thanks,
Samba

**Comment by samba2127** [comment]
Hi,

I tried both xc: and without xc operation
<tejasFPTemplateTable xmlns="urn:TEJASFPTEMPLATE-MIB" operation="delete">
     <tejasFPTemplateEntry >
      <cI>100</cI>
      <sI>40</sI>
      <sN>50</sN>
      <fPTemplateID>60</fPTemplateID>
      <description>tejas</description>
    </tejasFPTemplateEntry>
</tejasFPTemplateTable>

Following message seeing in the server side
[INF]: SR: No "running" datastore changes to apply.
[INF]: SR: EV LISTEN: "/ietf-netconf:edit-config" "rpc" ID 6 priority 0 success (remaining 0 subscribers).
[INF]: SR: EV ORIGIN: "/ietf-netconf:edit-config" "rpc" ID 6 priority 0 succeeded.

Thanks,
Samba
From: Samba Siva Reddy
Sent: Thursday, May 23, 2024 3:21 PM
To: 'sysrepo/sysrepo' ***@***.***>; sysrepo/sysrepo ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [sysrepo/sysrepo] question: can we parse and print edit-config or edit-data before pushing into the sysrepo database. (Issue #3281)

I am not able to delete the list inside container. Could you please check and let me is anything error in my xml file.
Getting the success message but in server showing the following message

[INF]: SR: No "running" datastore changes to apply.
[INF]: SR: EV LISTEN: "/ietf-netconf:edit-config" "rpc" ID 6 priority 0 success (remaining 0 subscribers).
[INF]: SR: EV ORIGIN: "/ietf-netconf:edit-config" "rpc" ID 6 priority 0 succeeded.

Here is the yang and xml file:

module TEJASFPTEMPLATE-MIB {

  namespace "urn:TEJASFPTEMPLATE-MIB";
  prefix "tejasfptemplate-mib";



  import ietf-inet-types {
    prefix "inet";
  }

  import ietf-yang-types {
    prefix "yang";
  }

  typedef Fixed2 {
    type int32;
    description
     "Represents a fixed decimal as an integer that is one
      hundred times the float value.";
  }

  typedef String16 {
    type binary {
      length "16";
    }
    description
     "Represents an Octet String consisting of 16 octets.";
  }

  container tejasFPTemplateTable {

      list tejasFPTemplateEntry {
      key "cI sI sN fPTemplateID";
        description
         "An entry in the FPTemplate Table.";

        leaf cI {
          type int32;
          description
           "Chassis Index";
        }

        leaf sI {
         type int32;
          description
           "Slot Index";
        }

        leaf sN {
          type int32;
          description
           "Parent SN";
        }

        leaf fPTemplateID {
          type int32;
          description
           "The identifier for this FP template.";
        }

        leaf description {
          type string;
          description
           "The name associated with this FP template.";
        }
    }
  }
}

<tejasFPTemplateTable xmlns="urn:TEJASFPTEMPLATE-MIB" xc:operation="delete">
     <tejasFPTemplateEntry >
      <cI>100</cI>
      <sI>40</sI>
      <sN>50</sN>
      <fPTemplateID>60</fPTemplateID>
      <description>tejas</description>
    </tejasFPTemplateEntry>
</tejasFPTemplateTable>

Thanks,
Samba

**Comment by michalvasko** [comment]
You need to send a valid XML. The prefix is needed but it must also be **defined**. I am sorry but you really **must** know how XML works, look at a [tutorial](https://www.w3schools.com/xml/xml_namespaces.asp).

**Comment by samba2127** [comment]
Hi All,

I was tried with lock option to lock the running database. I was able to edit the running database even after the “lock” .  is that expected behavior?

>Lock –target running
Ok

Thanks,
Samba

**Comment by michalvasko** [comment]
Yes, that is expected and works as [sepcified](https://datatracker.ietf.org/doc/html/rfc6241#section-7.5). Please learn all these basics before asking anything.

**Comment by samba2127** [comment]
Hi All,


Getting the following issue while executing the merge_config.sh script. It was working earlier.

I followed the following steps
./setup.sh
./merge_hostkey.sh
./merge_config.sh

[ERR] Invalid leafref value "genkey" - no target instance "/ks:keystore/ks:asymmetric-keys/ks:asymmetric-key/ks:name" with the same value. (Data location "/ietf-netconf-server:netconf-server/listen/endpoints/endpoint[name='default-ssh']/ssh/ssh-server-parameters/server-identity/host-key[name='default-key']/public-key/central-keystore-reference".)
[ERR] Validation failed.
sysrepocfg error: Failed to merge edit data (Validation failed)

I am not able to understand why this issue is coming.

Thanks
Samba

**Comment by michalvasko** [comment]
Me neither, this is exactly the executed sequence of scripts during the installation. And it works fine there so I am not able to help.

**Comment by samba2127** [comment]
Hi Michal,

There is a one scenario  from side.
we have connected two clients  client ip1 = 192.168.55.45
                                                           client ip2 = 192.168.55.23
Customer want to know which client has pushed the configuration.
How do we know which client pushing the configuration?
is there any way to find client in the register call back function?

Thanks,
Smba

**Comment by michalvasko** [comment]
Yes, you can learn the NETCONF session ID in the [callbacks](https://github.com/CESNET/netopeer2/?tab=readme-ov-file#sysrepo-callbacks).
