### ISSUE TITLE
installing the yang files with sysrepo

### ISSUE THREAD

**Issue by biswajit84** [sysrepo/sysrepo#3282]
Hi,
We have several yang files to be installed with sysrepo.
So to install the yang files, is there any other method available other than executing `sysrepoctl -i <File-name>.yang`.
Or we have to load each yang file, only through sysrepoctl call only.
Is there any way if we keep all the yang files in sysrepo path, then it will get loaded automatically.

Regards,
Biswajit

**Comment by biswajit84** [comment]
Hi,
As I am new to this .can you please guide me how can sysrepoctl can install several yang files present in one directory at once.
Regards,
Biswajit

**Comment by michalvasko** [comment]
No, no matter what it should always be easily understandable based on a tool help how to use it. So just run `sysrepoctl -h` and find out on your own.
