### ISSUE TITLE
When will 'sr_get_changes' be applied?

### ISSUE THREAD

**Issue by rydy** [sysrepo/sysrepo#3284]
Hi,
When will 'sr_get_changes' be applied?
Thanks

**Comment by michalvasko** [comment]
When calling the function in a module change callback, on `SR_EV_CHANGE` the changes are not yet applied, on `SR_EV_DONE` they have already been applied. Generally, the return value is only valid until you return from the callback.

**Comment by michalvasko** [comment]
I do not understand the question, I cannot tell you exactly, it depends on several factors. It will be applied **after** `SR_EV_CHANGE` and **before** `SR_EV_DONE`, that is all I can tell you. You should not rely on anything else.

**Comment by rydy** [comment]
> I do not understand the question, I cannot tell you exactly, it depends on several factors. It will be applied **after** `SR_EV_CHANGE` and **before** `SR_EV_DONE`, that is all I can tell you. You should not rely on anything else.

I see. Thanks for the reply.
