### ISSUE TITLE
Callback Function Receives Original Configuration During Deletion Despite Field Modification

### ISSUE THREAD

**Issue by balaji07s** [sysrepo/sysrepo#3286]
Hi team,

During create time I have sent the below configuration to sysrepo.
```
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
     <interface>
        <name>vAni_ont1</name>
        <enabled>true</enabled>
        <type xmlns:bbf-xponift="urn:bbf:yang:bbf-xpon-if-type">bbf-xponift:v-ani</type>
        <v-ani xmlns="urn:bbf:yang:bbf-xponvani">
            <channel-partition>CG_1.CPart_1</channel-partition>
            <onu-id>0</onu-id>
            <expected-serial-number>ZYGB3a001001</expected-serial-number>
            <preferred-channel-pair>CG_1.CPart_1.CPair_gpon</preferred-channel-pair>
        </v-ani>
    </interface>
</interfaces>
```
During deletion time, I changed the **expected-serial-number** to some different value and sent it to sysrepo like below.

```
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
     <interface>
        <name>vAni_ont1</name>
        <enabled>true</enabled>
        <type xmlns:bbf-xponift="urn:bbf:yang:bbf-xpon-if-type">bbf-xponift:v-ani</type>
        <v-ani xmlns="urn:bbf:yang:bbf-xponvani">
            <channel-partition>CG_1.CPart_1</channel-partition>
            <onu-id>0</onu-id>
            <expected-serial-number>CIGG23400021</expected-serial-number>
            <preferred-channel-pair>CG_1.CPart_1.CPair_gpon</preferred-channel-pair>
        </v-ani>
    </interface>
</interfaces>
```

Is it expected that when I send a delete configuration to sysrepo, modifying the **expected-serial-number** field to a different value, only the original **expected-serial-number** sent during creation time is received in the registered callback function? I confirmed this by adding debug prints.

Thank you!

**Comment by michalvasko** [comment]
> During deletion time, I changed the expected-serial-number to some different value

I do not understand, did you change the value or deleted it? In callbacks you should always get the current configured value.

**Comment by balaji07s** [comment]
Is it normal that we are deleting v-ani entry with a different serial number in the "expected-serial-number" field, yet in the registered callback, we see the serial number configured during creation?

**Comment by michalvasko** [comment]
Like I said, I do not understand your exact use-case. When deleting leaves, the actual value in the edit of the leaf is ignored since there can only be one instance of the leaf. Please include exact operations that are processed with the reported values and what you find unexpected.

**Comment by balaji07s** [comment]
our expectation is that if a user deletes a list entry with incorrect leaf values, Sysrepo should generate an error. However, this is not occurring.

**Comment by michalvasko** [comment]
That is how it worked a really long time ago but I was convinced that the [specs](https://www.rfc-editor.org/rfc/rfc7950.html#section-7.6.7) do not actually require the value to match to identify the node and delete it.

**Comment by balaji07s** [comment]
Thanks, michalvasko for the quick responses!!
