### ISSUE TITLE
Suggest configurable timeout for getting operational state data

### ISSUE THREAD

**Issue by trentzhou** [sysrepo/sysrepo#3295]
In my test, if the callback takes more than 2 seconds, getting operational data will fail with error `EV ORIGIN: SHM event "rpc" ID 5 processing timed out`.

Can you please make this timeout value configurable either as a cmake flag or as a config item in `sysrepo-factory-default`?

**Comment by michalvasko** [comment]
What exactly is the use-case when your operational callbacks are being called? You should always be able to configure the timeout.

**Comment by trentzhou** [comment]
The function `sr_oper_get_subscribe` does not have a timeout parameter. Sometimes my callback runs slow, it may use more than 2 seconds.

In src/common.h:

```c
/** default timeout for operational subscription callback (ms) */
#define SR_OPER_CB_TIMEOUT 5000

/** default timeout for RPC/action subscription callback (ms) */
#define SR_RPC_CB_TIMEOUT 2000
```

I can manually change these two macros to larger values. But I wish this can be configurable.

**Comment by michalvasko** [comment]
The subscriber, meaning the process calling `sr_oper_get_subscribe()`, does not get to decide the timeout. It is the callers of the callback that set the timeout. The problem in this case is that there are many ways (operations) when this callback is called so I am asking about the specific use-case so that I can tell you how to increase the timeout.

**Comment by trentzhou** [comment]
I used netopeer2-server to provide a netconf server. Then I used simple ssh to act as a netconf client. The `<get>` operation meets timeout error.

**Comment by michalvasko** [comment]
Use `-t <timeout>` parameter when starting the server.

**Comment by trentzhou** [comment]
Thanks a lot! It works.
