### ISSUE TITLE
Question: Force triggering change callback

### ISSUE THREAD

**Issue by bensadi** [sysrepo/sysrepo#3296]
Hello all,
Is there a way to trigger change callback manually?

**Eg.** I have a change callback subscribed to a specific xpath, and I want to force this one to be triggered when an external event happens.

Doesn't look like the standard behavior but may there is trick to doing it.

**Comment by michalvasko** [comment]
No, you cannot do that. If nothing else, the callback always needs to report some changes.

**Comment by bensadi** [comment]
Thanks for the quick answer.
Is it possible to apply changes without triggering a callback?

**Comment by michalvasko** [comment]
No, that is also not possible because it defeats the basic purpose and assumptions of *sysrepo*.

**Comment by bensadi** [comment]
OK got it. Thanks for the support. Hope it can also help the others.
Regards,
Ben.
