### ISSUE TITLE
Function sr_apply_changes is too slow

### ISSUE THREAD

**Issue by trentzhou** [sysrepo/sysrepo#3297]
I tested with yang ietf-interfaces.yang. I created many fake interfaces under /interfaces, then saved them to the running store.

100 interfaces, sr_apply_changes could finish in about 0.1 second.
1000 interfaces, it finished in 14 seconds.
10000 interfaces, it took about 2500 seconds.

It seems this function complexity is O(n*n). Can it be optimized?

**Comment by michalvasko** [comment]
What *sysrepo* version are you using? Those numbers look rather extreme.

**Comment by trentzhou** [comment]
It's built from the master version yesterday.

**Comment by michalvasko** [comment]
Then please include more details. You are first calling `sr_set_item_str()` for all the interfaces and then `sr_apply_changes()`? What did you measure, only the `sr_apply_changes()` call? What nodes are created for each interface?

**Comment by michalvasko** [comment]
Meaning it is at least to some extent running in Python. Then is not relevant, Python is known to be slow. Please try measuring C code directly, otherwise I can never be sure the benchmark has accurate numbers.

**Comment by trentzhou** [comment]
I think it's not a python problem because the python function `sess.apply_changes()` is just a direct wrapper of `sr_apply_changes`. I'll test with a C program and check the results.

**Comment by trentzhou** [comment]
I created the same program in C and tested again. Here are my findings:

1. I removed all yang modules, and only install iana-if-type@2014-05-08.yang and ietf-interfaces@2018-02-20.yang. Both C and python programs run very fast. The time looks very linear. The function `sr_apply_changes` can finish in 6 seconds with 100k interfaces.
2. When I load our yang, the performance drops significantly. We use a lot of augment, leafref, and when conditions. I'm not sure which place caused the performance issue. I'll continue investigating.

**Comment by trentzhou** [comment]
I found time was spent in data validation. Our yang has augments like this:
```yang
  augment "/if:interfaces/if:interface" {
    when "if:type = 'eth-std:ethernetCsmacd'";
    container ethernet {
      leaf mtu {
        type eth-std:IF_MTU;
        default "2000";
        description
          "Ethernet port MTU";
      }
  // more stuff....
  }
```

Though my test program only sets `name` and `type`, sysrepo generates the missing leaf nodes with default values, then does the validation. My questions are:

1. Can we skip generating nodes with default values?
2. Can we skip validation?

**Comment by michalvasko** [comment]
1. No, they are required to be part of the datastore data for everything to work correctly.
2. No, the stored data are expected to and must be valid.

I am guessing you have added much more nodes and conditions because the ones posted should not cause any significant validation issues. I would suggest you optimize those conditions (and I can help with that if you can post it) or even validation can perhaps be optimized in case there are inefficiencies.

**Comment by trentzhou** [comment]
Thanks. My yang files are a bit chaotic. I think you can close this issue now. I'll try to clean up my yang modules.
