### ISSUE TITLE
inconsistent `location` leaf-list within the `ietf-yang-library`

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#3306]
(we talked about this on Slack earlier today, and I was asked to provide a bugreport)

When I fetch content of the `startup` DS, some modules below `/ietf-yang-library:yang-library/module-set` have their `location` leaf set, while some others do not provide this value. It would be awesome if the value was provided by all (sub)modules, imported, implemented -- all of them.

Why do we need it? We're [implementing YANG schema retrieval](https://gerrit.cesnet.cz/c/CzechLight/br2-external/+/7189) in our RESTCONF server. The RESTCONF protocol itself does not define how schemas are fetched, but it says that it's a good idea to make them available through an API endpoint, and to use the URL within this endpoint for all modules in the respective leaf below the `ietf-yang-library` data. Since RESTCONF is a HTTP protocol, and our server is designed to run behind a reverse proxy, we do not know the RESTCONF server's root URL at startup time. In fact, the URL might be different for each request. Since the standard was [not designed to allow relative URLs](https://mailarchive.ietf.org/arch/msg/netconf/BZ0ZG4qZ83pO4Xo0ON0wFHB9bFY/), we cannot really push our HTTP-based `location` leafs to sysrepo via the usual ops data mechanism, and we're instead adding the URLs on a libyang level, right before the content of `ietf-yang-library` is printed through native libyang APIs, with no changes to the data stored in sysrepo. So far so good.

For various reasons (schema confidentiality, but also vulnerability fingerprinting), we would like to give the end user a choice on whether this schema retrieval is allowed or not. Since the actual schema retrieval is not covered by any NACM rule (it's an ad-hoc operation which does *not* touch any datastore, after all), we thought that it's a good idea to tie this schema retrieval with the visibility of the `location` leaf within the `ietf-yang-library` model. The NACM *can* guard access to that leaf already, and from the RESTCONF client's perspective, it makes a lot of sense to assume that a reasonable server should only return working URLs. That way, if there's an NACM rule which blocks a model's `location`, then its actual YANG content won't be made available. Internally, the RESTCONF server would simply enable NACM, and try to send an internal request to sysrepo fetching the `location` leaf anytime it's asked for the YANG schema. If this internal request succeeds and returns some data, then the RESTCONF server can read the raw schema via libayng context and send it to the RESTCONF client; if the internal request fails, then the server rejects the schema request as well. As a bonus, the operator has no extra control knob to tweak, and the entire stack does the Right Thing™.

However, right now this check breaks for modules whose `location` is not present in sysrepo. For those modules, we cannot know whether a request for that leaf is NACM-blocked, or whether the data are missing by accident. Therefore making sure that sysrpeo always provides this `location` leaf for any module would be a great fix. Alternatively, a new public API which would return a boolean "can we fetch this data if it existed?" would be OK as well.

**Comment by michalvasko** [comment]
Added `location` or `schema` to all the modules. It was not created only for internal modules, which are **not** in the sysrepo repository (contrary to what I wrote before) so they always need to be printed from context when sending YANG schema to a client.
