### ISSUE TITLE
Question: Public API to use NACM to filter data?

### ISSUE THREAD

**Issue by nullromo** [sysrepo/sysrepo#3307]
Sysrepo uses functions like `sr_nacm_get_node_set_read_filter` and `sr_nacm_get_subtree_read_filter` to filter data based on the NACM. However, these are internal functions and not exposed to developers. The only way to use these is indirectly via `sr_get_item` & friends.

I have a use case where I catch an update from sysrepo using a subscription, and then I want to broadcast the new data to multiple users over connected websockets. The more efficient way would be to subscribe for the data, and then do something like this (pseudo code)

```
// method 1
subscriptionCallback(data) {
    // data is grabbed from the subscription only once

    for (user: connectedUsers) {
        // filter the data for the user
        filteredData = filter(data, user);

        // send filtered data to user
        sendToUser(user, filteredData);
    }
}
```

However, I don't have access to this kind of filter function. Instead, I need to call `sr_get_data` for every single user, like this:

```
// method 2
subscriptionCallback(data) {
    // data arg cannot be used

    for (user: connectedUsers) {
        // re-grab the data for every user, potentially expensive
        sr_nacm_set_user(user);
        data = sr_get_data();

        // send filtered data to user
        sendToUser(user, data);
    }
}
```

Method 2 is possible right now. Method 1 would require some kind of publicly-exposed NACM filter function. Is there any chance of having this in the future?

**Comment by michalvasko** [comment]
I quite like NACM being encapsulated in *sysrepo*, it prevents errors. In this specific case, if you cache the data (`sr_connect()` flag), it should be pretty much as efficient as it would be if the public API existed.

In any case, the whole issue occurs because you are misusing *sysrepo* API. You are essentially doing your own user management and even something akin to subscriptions so of course the exposed API will not be suitable. Naturally, I do not understand your whole design and there may not be any other way.

**Comment by jktjkt** [comment]
> I have a use case where I catch an update from sysrepo using a subscription, and then I want to broadcast the new data to multiple users over connected websockets.

Any reason why you do not use the IETF YANG push for this? We're working on a RESTCONF interface for this in https://github.com/CESNET/rousette. It will be HTTP, not websocket, so if your requirements prescribe websocket, you might have to implement that, but still, that sounds like a path of least resistance.

**Comment by nullromo** [comment]
Thanks for the advice. As always, I really appreciate your input.

---

@michalvasko

> if you cache the data (sr_connect() flag)

`SR_CONN_CACHE_RUNNING` seems like a good idea. I will try that.

> something akin to subscriptions

I suppose I could create a separate sysrepo session + subscription for each websocket. Right now I have one "socket controller" that starts 1 main session and has 1 sysrepo subscription. It accepts and tracks many socket connections. When data comes in on the subscription, I filter it per user and send over each socket. However, I could restructure the socket controller to create a new sysrepo session + subscription for every connected socket. That way each subscription callback would be invoked with filtered data. However, I would need to manage a lot more sessions and subscriptions. Not sure if that's worth the effort if `SR_CONN_CACHE_RUNNING` ends up working well.

---

@jktjkt

> Any reason why you do not use the IETF YANG push

I didn't know about it 🙃 Thanks for the idea. My use case for this is that if I have a user looking at the Web GUI of my system and a separate user modifying data over another interface like NETCONF for example, the Web GUI user should see the data update in real time in their browser. I use socket.io in the backend to push data updates to the Web GUI user(s). Technically socket.io is using HTTP long-polling instead of actual websockets.

So I'm not sure how YANG push would integrate into this exactly. The browser makes an HTTP call to subscribe to sysrepo directly via rousette?

---

All in all, I think just caching will be the solution for now. It seems the public NACM API is not in the cards, and likely not necessary here.

**Comment by jktjkt** [comment]
Yeah, with RESTCONF it's a long poll as well, see [RFC 8650](https://datatracker.ietf.org/doc/html/rfc8650). It's not implemented yet in Rousette; as an intermediate "fix" there's some code which simply keeps dumping module content over a long-lived `text/event-stream` whenever the DS changes (see [this](https://github.com/CESNET/rousette/blob/master/src/http/EventStream.cpp) and [this](https://github.com/CESNET/rousette/blob/master/src/sr/OpticalEvents.cpp) source files if you're interested). But we'll get there :).
