### ISSUE TITLE
[ERR] Data model "ietf-netconf-monitoring@2010-10-04" not found in local searchdirs.

### ISSUE THREAD

**Issue by DhirajKB** [sysrepo/sysrepo#3308]
Hello

While running in loop for more than 100 times successfully with sysrepo notification working fine , suddenly observe the below error :

[ERR] Data model "ietf-netconf-monitoring@2010-10-04" not found in local searchdirs.
[ERR] Loading "ietf-netconf-monitoring" module failed.
sysrepocfg error: Failed to connect (libyang error)

Any pointers please since this error is observed consistently while trying to run in loop for more than 100 times

Thanks

**Comment by michalvasko** [comment]
Please provide that app to reproduce this, I cannot help you otherwise.
