### ISSUE TITLE
`sr_module_change_subscribe` appears to provide config data in the operational datastore

### ISSUE THREAD

**Issue by nullromo** [sysrepo/sysrepo#3309]
## Summary

When I export data from the operational datastore with no plugin running, I get no data. When I export the data with a plugin running, I get `config true` nodes filled in.

## Example YANG Model

```yang
module simple {
    yang-version 1.1;
    namespace 'urn:simple';
    prefix simple;
    organization '';
    contact '';
    description '';
    revision 2024-05-30 {
        description '';
    }

    container top {
        leaf data {
            type string;
        }
    }
}
```

## Example Data

```xml
<top xmlns="urn:simple">
    <data>hello</data>
</top>
```

## Example Plugin Partial Code
```c
static sr_subscription_ctx_t* subscriptionContext = NULL;

static int callback(sr_session_ctx_t* session,
                    uint32_t subscriptionId,
                    const char* moduleName,
                    const char* xpath,
                    sr_event_t event,
                    uint32_t requestID,
                    void* privateData) {
    return SR_ERR_OK;
}

int rc = sr_module_change_subscribe(session, "simple", "/simple:*", callback, NULL, 1, SR_SUBSCR_DEFAULT, &subscriptionContext);
```

## Steps

1. Install the module.
```
$ sudo sysrepoctl --install simple@2024-05-30.yang
```
2. Import the data.
```
$ sudo sysrepocfg --import simple.xml --module simple
```
3. Look at the data in the running datastore. There is data.
```
$ sudo sysrepocfg --export --module simple
<top xmlns="urn:simple">
  <data>hello</data>
</top>
```
4. Look at the data in the operational datastore. There is nothing.
```
$ sudo sysrepocfg --export --module simple --datastore operational
$
```
5. Run the plugin.
6. Look at the data in the operational datastore. There is something there.
```
$ sudo sysrepocfg --export --module simple --datastore operational
<top xmlns="urn:simple">
  <data>hello</data>
</top>
```
Why?

**Comment by jktjkt** [comment]
This is [as per the docs](https://netopeer.liberouter.org/doc/sysrepo/devel/html/#oper_ds). The reasoning matches how the NMDA is designed: the `operational` DS should reflect config which "is in effect". If there's an active subscription, chances are that it's doing something in response to any changes, so they are "in effect", and therefore it makes sense to auto-propagate the `running` DS to `operational`.

**Comment by nullromo** [comment]
Thank you, I can see the reasoning. I was just surprised because I have a plugin that subscribes to some sub-tree of my module and the rest of the module was not showing up in the operational datastore output. To achieve what I want, I do need to add this "no-op subscription" that's just an empty function just to get sysrepo to output the data.

**Comment by michalvasko** [comment]
> Just because I didn't subscribe to a particular part of my datastore doesn't mean I'm not using it.

This is not normally the case and the expectation is that you will to adjust the behavior somehow if you are using a configuration subtree, which means you will have a subscription for it. But I suppose there may be some special use-cases when this is not the case.
