### ISSUE TITLE
How to provide factory default datastore for sysrepo-plugind module in order to configure the plugin order?

### ISSUE THREAD

**Issue by rbu9fe** [sysrepo/sysrepo#3310]
The module [sysrepo-plugind](https://github.com/sysrepo/sysrepo/blob/9536280a9f0e2cff8d0ed0f69081108f8e41b803/modules/sysrepo-plugind%402022-08-26.yang#L2) provides a neat way to configure the order in which the plugins are loaded. Everything works fine when writing the desired configuration into the startup datastore. But how can I store that into its factory default datastore?
Is there already a way to to that?
Options I can think of would be:
1. Provide factory default data when the module is installed (same as for other modules) - but where is the module installed?
2. Provide factory default datastore, that's specific to the `sysrepo-plugind` module, when the daemon is started using a command line parameter.

**Comment by michalvasko** [comment]
It is the option 1 but since it is an internal module, it requires a special way of setting `factory-default`. Look into the [README](https://github.com/sysrepo/sysrepo?tab=readme-ov-file#useful-cmake-sysrepo-options) or `CMakeLists`, variable `INTERNAL_MODULE_DATA_PATH`.

**Comment by rbu9fe** [comment]
Thanks a lot, somehow I missed that.
