### ISSUE TITLE
sysrepocfg issues Libyang errors when trying to import some config data

### ISSUE THREAD

**Issue by reshad-equinix** [sysrepo/sysrepo#3325]
1. Running https://hub.docker.com/r/sysrepo/sysrepo-netopeer2/
2. Install some models from a vendor via `sysrepoctl`
3. Import some config via `sysrepocfg --i=<configfile.xml>`

The import fails and I get lots of errors like this:
```
libyang error: Invalid value "IPV6_ADDRESS_INDEX" which does not fit the type (Invalid enumeration value "IPV6_ADDRESS_INDEX".).
libyang error: Previous warning generated by XPath subexpression[36] "type='IPV6_ADDRESS_INDEX'" with context node "/openconfig-bgp:bgp/rib/attr-sets/attr-set/tunnel-encapsulation/tunnels/tunnel/subtlvs/subtlv/segment-lists/segment-list/segments/segment/state/remote-ipv6-address".
```

The error in [openconfig-rib-bgp-attributes.yang](https://github.com/openconfig/public/blob/master/release/models/rib/openconfig-rib-bgp-attributes.yang#L949) seems valid in that IPV6_ADDRESS_INDEX doesn't seem to be defined anywhere.

My question is whether those errors would prevent the datastore edit/import or whether I should look at other causes (there's other errors I am looking into also).

Some of the other errors:

```
libyang error: Identityref "type" comparison with identity "DEFAULT_INSTANCE" without prefix, consider adding a prefix or best using "derived-from(-or-self)()" functions.
libyang error: Previous warning generated by XPath subexpression[10] "type != 'DEFAULT_INSTANCE'" with context node "/openconfig-network-instance:network-instances/network-instance/encapsula
tion".
libyang error: Identityref "type" comparison with identity "DEFAULT_INSTANCE" without prefix, consider adding a prefix or best using "derived-from(-or-self)()" functions.
libyang error: Previous warning generated by XPath subexpression[10] "type != 'DEFAULT_INSTANCE'" with context node "/openconfig-network-instance:network-instances/network-instance/encapsula
tion".
libyang error: Schema node "type" not found; in expr "oc-if:type" with context node "/openconfig-interfaces:interfaces/interface".
libyang error: Incompatible types of operands "name" and "interface" for comparison.
libyang error: Previous warning generated by XPath subexpression[50] "oc-if:name=current()" with context node "/ietf-ipfix-psamp:ipfix/observationPoint/arcos-ietf-ipfix-psamp-augments:interf
ace".
libyang error: Incompatible types of operands "name" and "interface" for comparison.
libyang error: Previous warning generated by XPath subexpression[50] "oc-if:name=current()" with context node "/ietf-ipfix-psamp:ipfix/observationPoint/arcos-ietf-ipfix-psamp-augments:interf
ace".
```

**Comment by michalvasko** [comment]
XPath problems should not result in errors but that may have worked differently in older versions. The docker image is not maintained by us and is old, my suggestion is not using it and rather building your own one with current versions.

**Comment by reshad-equinix** [comment]
> XPath problems should not result in errors but that may have worked differently in older versions. The docker image is not maintained by us and is old, my suggestion is not using it and rather building your own one with current versions.

Will do, thanks @michalvasko

**Comment by reshad-equinix** [comment]
> XPath problems should not result in errors but that may have worked differently in older versions. The docker image is not maintained by us and is old, my suggestion is not using it and rather building your own one with current versions.

And I assume you'd recommend latest on master i.e. 2.2.170?

**Comment by michalvasko** [comment]
Well, as it is I would recommend the current `devel` because there were some major issues in the latest release. There should be another one soon.
