### ISSUE TITLE
possiblity of closing callhome session from external application

### ISSUE THREAD

**Issue by biswajit84** [sysrepo/sysrepo#3331]
Hi ,
is it possible to close established callhonme netconf session  from an external application
currently netopeer2-server initiate a callhome request as soon as it starts. since I hv subscribed to netconf-start-session, the respected callback is getting invoked.
My doubt is :There is a requirement in ORAN that  if the server doesn't get the heart beat fom client until the expiry of guard period, then  the current session will get close .

Regards
Biswajit

**Comment by michalvasko** [comment]
I think you can achieve this only by calling `kill-session` from another session. We have implemented the standardized `ietf-netconf-server` modules and do not support any ORAN deviations from this behavior.
