### ISSUE TITLE
Storing annotations in datastores

### ISSUE THREAD

**Issue by tbsuht** [sysrepo/sysrepo#3335]
When applying an edit to a datastore (e.g. `startup`) via edit_batch() which contains an annotation like `"ietf-netconf:operation": "remove"`, I would like that this is not just being applied to the datastore itself, but also that the annotation ends up in the file itself.

So if the datastore is merged later into another datastore, the annotation is applied again.
Is this currently possible (I don't think so) or could this function be added?

**Comment by michalvasko** [comment]
No, `metadata` datastore support is not implemented. We would like to add this at some point but it does not have a high priority.
