### ISSUE TITLE
Live migrating from legacy model

### ISSUE THREAD

**Issue by troglobit** [sysrepo/sysrepo#3342]
Hi,

this is merely a question, not a bug report or feature request.

We have an [entire system](https://github.com/kernelkit/infix) managed with sysrepo (currently 2.2.170) and a question has come up regarding migrating configurations from a legacy model to a new modern one.  So as an experiment, in a plugin to sysrepo-plugind, I tried setting up two change subscriptions, one for the legacy model that has `SR_SUBSCR_UPDATE` so I can catch any old configuration for the legacy XPath, and a regular change subscription for the new model.  But when I call `sr_set_item(new_xpath, old_val)` (pruning the xpath from old_val) from the legacy callback the whole thing comes crashing down -- so I'm guessing this is not supposed to work?  I tried to no avail finding something about this in the documentation.

Our alternate approach, since we save the entire configuration as a JSON file, is to do migrations with jq before we load the configuration into sysrepo at boot.  This works, but I was curious if there were other avenues available to explore.  We can of course also continue supporting both models, but it would be nice to be able to migrate so that when a user compares the startup and running the diff would show the change.

**Comment by jktjkt** [comment]
I'm afraid that this has to be done outside of sysrepo.

I assume that you're trying to figure out what to do when your model changes in some, possibly incompatible, way. We're doing the same thing, and we've been bitten hard when trying to solve this on a sysrepo level. It works fine in the simple case ("we've added a bunch of leafs, let's initialize them with reasonable values"), but it just cannot be done in a generic case. A good example is the 2023 change of the `ietf-netconf-server` YANG model where Netopeer2 was ported to a newer version of that draft, and the model changed the layout of data in an incompatible manner.

Once you've installed the new YANG revision into sysrepo, you cannot load the previous data. Once you have the old YANG reversion, you cannot load the new data (and it is not possible to have both `modA@2020-01-01` and `modA@2024-07-01` implemented at the same time). Also, all datastores which are available on the server must implement the same set of YANG modules, which means that your idea of users diffing the `startup` (with the old YANG models) and `running` (with the current revisions of YANG models) won't work.

BTW, we're currently ditching our scripts which use some `sysrepocfg` logic for performing config schema migrations to some `jq` or Python logic. Fun.

**Comment by troglobit** [comment]
Actually, this case is a bit different from the big-ietf-netconf-server breakage of 2023 (we had to recommend customers to do a factory reset when rebooting after an upgrade ... :-)

Here I poorly tried to describe the case of company-legacy-model@2023-06-06.yang vs company-odern-model@2024-07-07.yang, where the differences were: 1) the name of the model, and 2) the removal of an outer container.  So both models basically have the same contents, but the modern one is collapsed, moving contained nodes to the top-level of the yang tree.

In this case I could reuse all callbacks, only with a different XPath

**Comment by troglobit** [comment]
I bring good news: with the latest releases of libyang + sysrepo the live migration I described above no longer crashes! :smiley: Amazing work on 2.10.1 @michalvasko et al! :clap:

**Comment by troglobit** [comment]
Closing, since I sort of answered the question myself ...
