### ISSUE TITLE
Build sysrepo with undeclared function 'strdup' issue [question]

### ISSUE THREAD

**Issue by zhenyunxie** [sysrepo/sysrepo#3343]
Hi,
I'm following the documentation to build sysrepo, but I've got the following issue:
![image](https://github.com/sysrepo/sysrepo/assets/98989264/2f65cc82-aecd-4f3c-a95c-9a7be97349ff)

It seems like it might be related to stricter compile standard settings, but I'm not sure how to resolve it.
Any guidance would be appreciated!

Thanks!

**Comment by irfanHaslanded** [comment]
May need `_DARWIN_C_SOURCE` in addition to `_GNU_SOURCE` as explained in https://www.gnu.org/software/autoconf/manual/autoconf-2.70/html_node/C-and-Posix-Variants.html

**Comment by zhenyunxie** [comment]
> May need `_DARWIN_C_SOURCE` in addition to `_GNU_SOURCE` as explained in https://www.gnu.org/software/autoconf/manual/autoconf-2.70/html_node/C-and-Posix-Variants.html

Thanks for your help. I followed your advice, but I'm still stuck in the build process.
![image](https://github.com/sysrepo/sysrepo/assets/98989264/ed81663d-c35e-4166-a839-5bcf6f690635)

I've checked several similar issues, but they haven't been very useful, seems that `pthread_mutex_*` functions are not supported by MacOS. <https://github.com/pinpoint-apm/pinpoint-c-agent/issues/17>.

I am wondering there is nobody uses sysrepo on the macOS platform hahah xD ??

**Comment by michalvasko** [comment]
Yes, *sysrepo* is not officially supported on macOS so these and similar problems are expected. You are welcome to solve them and provide patches.

**Comment by zhenyunxie** [comment]
> Yes, _sysrepo_ is not officially supported on macOS so these and similar problems are expected. You are welcome to solve them and provide patches.

For a quick workaround, I am using docker to create an Ubuntu image and build it with Sysrepo

![image](https://github.com/user-attachments/assets/d02426e3-478e-4691-8b09-f0665a51fe29)
