### ISSUE TITLE
sr_module_change_subscribe, callback not getting called for leaf

### ISSUE THREAD

**Issue by mpanwar-github** [sysrepo/sysrepo#3345]
Hi,

I have xpath subscribed using sr_module_change_subscribe as below.

xpath: /common:A/rnm:B/cell:C[key]/D

if module name used : common -->getting change notificaiton and call get triggered.
sr_module_change_subscribe(subs_session, "common",  "/A/B/C/D", subscription_change_callback,  NULL,  0, (SR_SUBSCR_NO_THREAD | SR_SUBSCR_DONE_ONLY), &sr_subs_data_ctx))

if module name used : cell -- > No change notification and call back not getting triggred. 
sr_module_change_subscribe(subs_session, "cell",  "/A/B/C/D", subscription_change_callback,  NULL,  0, (SR_SUBSCR_NO_THREAD | SR_SUBSCR_DONE_ONLY), &sr_subs_data_ctx))

I am not using "common" as it will notify for each change under that module, I want to update in case of leaf D change only.

What is the method to handle this.

Thanks .

**Comment by jktjkt** [comment]
Your description is a bit hard to read, but it seems that you have a YANG model called `cell` which [augments](https://datatracker.ietf.org/doc/html/rfc7950#section-4.2.8) a model called `common`, adding a `cell:C` below `/common:A/rnm:B` (which is added to the `common` module by an augment in module `rnm`), right? If that's the case, these data will still live in a datastore of the model `common`, and if you want to only listen for modifications for that particular subtree, you need to subscribe with an XPath of `/common:A/rnm:B/cell:C/D`.

**Comment by mpanwar-github** [comment]
Hi @jktjkt 

Thank you for your response. 

I was away from my pc below is exact path:

running change sub xpath ("/_3gpp-common-managed-element:ME/_3gpp-nr-nrm-gnbdufunction:GNBDUFunction/_3gpp-nr-nrm-nrcelldu:NRCellDU/administrativeState", mod "_3gpp-nr-nrm-nrcelldu")

case-1: working, i am able to see callback getting hit

         std::string gpp_module_name = "_3gpp-common-managed-element";

         if (SR_ERR_OK != sr_module_change_subscribe(sysrepo_subs_session, gpp_module_name.c_str(), root_path_nr_cell_odu_admin_state.c_str(),
                     subscription_change_callback, NULL, 0, (SR_SUBSCR_NO_THREAD | SR_SUBSCR_DONE_ONLY), &sr_subscription_config_data_ctx))


case2: Not working, no callback hit

         std::string gpp_module_name = "_3gpp-nr-nrm-nrcelldu";

         if (SR_ERR_OK != sr_module_change_subscribe(sysrepo_subs_session, gpp_module_name.c_str(), root_path_nr_cell_odu_admin_state.c_str(),
                     subscription_change_callback, NULL, 0, (SR_SUBSCR_NO_THREAD | SR_SUBSCR_DONE_ONLY), &sr_subscription_config_data_ctx))
                     
   
  I am considering case-2 to avoid non-required data callback hit.

Thanks

**Comment by mpanwar-github** [comment]
From further debugging and logs seems its has to be parent node (ME) to be subscribed with module name "_3gpp-common-managed-element".

In callback with api "sr_get_changes_iter" we can get change on specific xpath, this method worked for me. Hence closing. Though if you think there is incorrectness in method pls let know.

Thanks

**Comment by jktjkt** [comment]
You're posting incomplete snippets of code, and therefore we don't know how the XPath in `gpp_module_name` looks like. Anyway, as I [already replied](https://github.com/sysrepo/sysrepo/issues/3345#issuecomment-2214871789), yes, you have to subscribe for the module which is getting augmented, and you can use an XPath which only refers to the nodes which were added by your series of augments.

BTW, since you're using C++, you might be interested in the [C++ bindings for sysrepo](https://github.com/sysrepo/sysrepo-cpp).
