### ISSUE TITLE
Question: Deleted vs. explicitly written default value in datastore

### ISSUE THREAD

**Issue by rbu9fe** [sysrepo/sysrepo#3347]
I have a sysrepo plugin based on the Yang model [ieee802-ethernet-interface](https://github.com/YangModels/yang/blob/main/standard/ieee/published/802.3/ieee802-ethernet-interface.yang). Here the leaf [duplex](https://github.com/YangModels/yang/blob/6b60eabba1708a90df2034c4864b59bcb811f107/standard/ieee/published/802.3/ieee802-ethernet-interface.yang#L230) defaults to [full](https://github.com/YangModels/yang/blob/6b60eabba1708a90df2034c4864b59bcb811f107/standard/ieee/published/802.3/ieee802-ethernet-interface.yang#L70). Now the plugin needs to be able to distinguish these cases:
1. The duplex value has not explicitly been written into or was deleted from the datastore => Configure the default value only when auto negotiation is OFF.
2. The value has been written with some value to the datastore => Configure the written value even when auto negotiation is ON in order to use a static duplex mode during auto negotiation.

Now the plugin can't distinguish these cases if in 2. the default value is written into the datastore. There's not even a change callback triggered so we don't know what to do: Shall the duplex mode be static or shall it be auto-negotiated?

Is there a way to distinguish whether a value was deleted from a datastore or whether it was written with its default value?
Can a callback be triggered even when a leaf that defines a default value is deleted or when it's explicitly created with its default value?

**Comment by michalvasko** [comment]
You are asking for incorrect behavior. Based on the [RFC](https://datatracker.ietf.org/doc/html/rfc6243), having the default value and an explicit value equal to the default value should not make any functional difference. Otherwise the module design is wrong.

**Comment by rbu9fe** [comment]
Thanks for the reply, that's what I thought. I'm wondering why IEEE designed the Yang model that way. There is no means to distinguish auto-negotiation with explicit full-duplex only or arbitrary duplex (which defaults to full).
