### ISSUE TITLE
Installation of sysrepo for multiple user

### ISSUE THREAD

**Issue by biswajit84** [sysrepo/sysrepo#3351]
Hi ,
while I am trying to install the netopeer, before installing the netopeer, I am trying to execute make shm_clean in sysrepo.
But since already another user has installed it and because of that it has already  created entry in /dev/shm.
So while executing make shm_clean its giving error like "Operation not permitted". Is it possible to overcome from this problem. 
I think if it can create entry in /dev/shm/user-name then it will solve our problem.

Regards,
Biswajit

**Comment by jktjkt** [comment]
Why do you want to do this?

**Comment by biswajit84** [comment]
Hi,
Initially when I have installed netopeer and the dependent packages then I was able to use without any issue .Now when other  user did the same and tried to use then only the user who has created the /dev/shm entry is able to run. Because of this  the development time of the same increases due to Single user use case.

Regards,
Biswajit

**Comment by jktjkt** [comment]
My question is "why would you want multiple users to run sysrepo" in a single machine/VM/chroot/namespace/whatever. That's not how this software was designed to work.

**Comment by biswajit84** [comment]
In that case my doubt is  whether only single instance of sysrepo is allowed to  run in the system?

**Comment by irfanHaslanded** [comment]
from the README
```
### Used run-time enviromental variables

It is possible to change the repository path by setting `SYSREPO_REPOSITORY_PATH` variable.
Also, if `SYSREPO_SHM_PREFIX` is defined, it is used for all SHM files created. This way
everal *sysrepo* instances can effectively be run simultanously on one machine.

```

**Comment by biswajit84** [comment]
Thanks alot..So if I provide the custom path to SYSREPO_REPOSITORY_PATH while building the sysrepo then all the SHM files and all other files  are also get created in this path and then we can use SYSREPO_SHM_PREFIX environment variable for accessing these  SHM files.Is my understanding is correct

**Comment by irfanHaslanded** [comment]
Please see https://github.com/sysrepo/sysrepo/blob/master/CMakeLists.txt#L171
you will need to pass `SHM_DIR` and `SHM_DIR` env vars to cmake before building sysrepo for each user for development since you are using `make shm_clean`.

**Comment by jktjkt** [comment]
The SHM prefixes are very useful for things such as parallel test runs (and the CI of various other projects configures sysrepo just like that), but I still strongly advise against sharing a single OS image/namespace/container/... across multiple users.

**Comment by biswajit84** [comment]
Thanks alot ...for support..
