### ISSUE TITLE
server is restarting when i tried to delete the config using the xml file. 

### ISSUE THREAD

**Issue by samba2127** [sysrepo/sysrepo#3352]
I tried the following xml file to delete the configuration but server is restarting every time.

edit-config --target running --config=/tmp/deletevcconfig.xml

     <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <tejasEVCTable xmlns="urn:ietf:params:xml:ns:yang:smiv2:tejasevc-mib">
        <tejasEVCEntry nc:operation="delete" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
            <cI>0</cI>
            <sI>0</sI>
            <sN>99</sN>
            <eVCID>6</eVCID>
        </tejasEVCEntry>
    </tejasEVCTable>
   </config>

Am i doing any wrong in xml file. 
Any response would be help full to debug the issue.

**Comment by michalvasko** [comment]
What do you mean the server is restarting? When you apply this `edit-config`, the server restarts?

**Comment by samba2127** [comment]
There is a one function subscribed for changes  int tjasevc_change_cb(sr_session_ctx_t *session, uint32_t sub_id, const char *module_name, const char *xpath, sr_event_t event, uint32_t request_id, void *private_data) this function will responsible for push and delete the data when event occurs. 
 whenever reaches here server is restarting rc = sr_get_changes_iter(session, path, &it);
    if (rc != SR_ERR_OK) {
        //goto cleanup;
        sr_free_change_iter(it);
        return rc;
    }
Here i don't understand is there any issue with deletion of xml file? is there any way delete the configuration in  sysrepo datab base from netopeer2-cli. Please help me on this

**Comment by michalvasko** [comment]
I am sorry but I do not understand at all. The configuration is changed automatically, your callbacks are supposed to change the behavior of your system/device/whatever.

**Comment by samba2127** [comment]
I am asking is there any issue in my xml file ? if there is no issue in my xml file . I will debug further where the issue is.

Thanks,
samba

**Comment by michalvasko** [comment]
Well, the config element should not be there but you would have noticed if you were using exactly what you posted, I believe. In any case, this seems correct (impossible to decide without the YANG modules):
```xml
<tejasEVCTable xmlns="urn:ietf:params:xml:ns:yang:smiv2:tejasevc-mib">
    <tejasEVCEntry nc:operation="delete" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
        <cI>0</cI>
        <sI>0</sI>
        <sN>99</sN>
        <eVCID>6</eVCID>
    </tejasEVCEntry>
</tejasEVCTable>
```

**Comment by jktjkt** [comment]
There's no attachment; it seems that you cannot attach files to GitHub issues via e-mail replies.

Also, please provide the netopeer2-server's logs and system info about possible exceptions, segfaults, etc.

**Comment by samba2127** [comment]
[evc.txt](https://github.com/user-attachments/files/16247119/evc.txt)
Attaching one document for reference yang model which i used.

Thanks.
samba

**Comment by michalvasko** [comment]
Fine, the XML seems to match the YANG module and the list instance should be deleted.

**Comment by samba2127** [comment]
Thank you Michal

**Comment by samba2127** [comment]
Hi Michel
 rc = sr_get_changes_iter(session, path, &it);
    if (rc != SR_ERR_OK) {
        //goto cleanup;
        sr_free_change_iter(it);
        return rc;
    }
    
when i tried to delete the configuration using xml. But it is hanging in this function and it is not coming back. i don't see any crash, but device is rebooting because of this

**Comment by michalvasko** [comment]
You are providing very little and still confusing information so I am not able to help. The function has no reason to hang anything so I suggest you use `gdb` to learn more about what is happening.

**Comment by samba2127** [comment]
i am using the version 
sudo /user/sbin/netopeer2-server -V
netopeer2-server 2.2.13

which version can i use of this issue?

**Comment by michalvasko** [comment]
I have already mentioned that, [the latest release](https://github.com/CESNET/netopeer2/releases).

**Comment by samba2127** [comment]
Hi Michal,

I upgraded with the latest version of netopeer2-2.2.28. 

When i tried to delete getting the segmentation fault . 
[ERR] EV ORIGIN: SHM event "rpc" ID 2 processing timed out.
[ERR]: SR: EV ORIGIN: SHM event "rpc" ID 2 processing timed out.
[WRN] EV ORIGIN: "/ietf-netconf-nmda:edit-data" "rpc" ID 2 priority 0 failed (Timeout expired).
[WRN]: SR: EV ORIGIN: "/ietf-netconf-nmda:edit-data" "rpc" ID 2 priority 0 failed (Timeout expired).
[ERR] User callback failed.
[ERR]: SR: User callback failed.
[ERR]: NP: Failed to send an RPC (User callback failed).
[ERR] EV ORIGIN: SHM event "change" ID 2 processing timed out.
[ERR]: SR: EV ORIGIN: SHM event "change" ID 2 processing timed out.
[WRN] EV ORIGIN: "tejasevc-mib" "change" ID 2 priority 0 failed (Timeout expired).
[WRN]: SR: EV ORIGIN: "tejasevc-mib" "change" ID 2 priority 0 failed (Timeout expired).
[ERR] User callback failed.
[ERR]: SR: User callback failed.
[INF]: SR: EV LISTEN: "rpc" ID 2 priority 0 processing Failed (after timeout or earlier error).

please help me to debug further on this issue.

**Comment by michalvasko** [comment]
Have you updated all the projects to their latest release (libyang, sysrepo, libnetconf2, netopeer2)? Have you recompiled your *sysrepo* applications after the update?

**Comment by samba2127** [comment]
Yes. I updated all the packages and recompiled all the packages.

**Comment by michalvasko** [comment]
You then must have some library incompatibilities, old versions used instead of new ones or something like that. I have no other suggestion than to completely manually remove all the relevant libraries and start over. Ideally use a fresh VM to skip the removal and simply install and compile everything from scratch.

**Comment by samba2127** [comment]
This issue is coming on my box. I removed all old libraries , compiled and created with new libraries. 
For create and modify is works fine. I see issue only for deletion. Do you any pointers to debug?

**Comment by michalvasko** [comment]
I cannot help you any more.

**Comment by samba2127** [comment]
Hi Michal,

I have 400 yang files to load in sysrepo database. It’s taking almost one our to load all the modules using sysrepoctl command . Is there any way to optimize to reduce 10 mints or less?

Thanks,
Samba

**Comment by michalvasko** [comment]
Install all the YANG modules in a single command unless you are already doing that. But I do not think so because it should definitely not take that long.

**Comment by samba2127** [comment]
I am using the following script. Let me know this is the way or another way your saying.
# Define the directory containing the YANG files
YANG_DIR="/usr/sbin/tejas/sharedobj/share/yang_mib"

# Iterate over all .yang files in the directory
for yang_file in "$YANG_DIR"/*.yang; do
    if [ -f "$yang_file" ]; then
        echo "Installing $yang_file..."
        /usr/sbin/tejas/sharedobj/share/bin/sysrepoctl  -i "$yang_file"

    fi
done

Thanks,
Samba

**Comment by michalvasko** [comment]
That script installs all the YANG files one-by-one, you need to have a **single** `sysrepoctl` call with `-i <yang1> -i <yang2> -i <yang3> ...`. The script can first generate the command and then execute it at the end.

**Comment by samba2127** [comment]
Hi Michal,
Getting the following messages after every reboot the device. What is the issue and why are we getting?
Is it because of properly not handling in my code before going to reboot the device?
Please give me some pointers how to restrict it.
[WRN] Removing event pipe "sr_evpipe360" after a crashed subscription.
[WRN]: SR: Removing event pipe "sr_evpipe360" after a crashed subscription.
[WRN] Removing event pipe "sr_evpipe361" after a crashed subscription.
[WRN]: SR: Removing event pipe "sr_evpipe361" after a crashed subscription.
[WRN] Removing event pipe "sr_evpipe362" after a crashed subscription.
[WRN]: SR: Removing event pipe "sr_evpipe362" after a crashed subscription.
[WRN] Removing event pipe "sr_evpipe363" after a crashed subscription.
[WRN]: SR: Removing event pipe "sr_evpipe363" after a crashed subscription.
[WRN] Removing event pipe "sr_evpipe364" after a crashed subscription.
[WRN]: SR: Removing event pipe "sr_evpipe364" after a crashed subscription.
[WRN] Removing event pipe "sr_evpipe365" after a crashed subscription.
[WRN]: SR: Removing event pipe "sr_evpipe365" after a crashed subscription.

Thanks,
Samba

**Comment by michalvasko** [comment]
You are not terminating some subscriber applications properly.

**Comment by samba2127** [comment]
Hi Michal,

Can we delete the list using the following command ?
/usr/sbin/tejas/sharedobj/share/bin/sysrepocfg --import=/tmp/netconf.xml –module

xml file content is
<tejasVplsConfigTable xmlns="urn:ietf:params:xml:ns:yang:smiv2:tejasvplsconfig-mib">
    <tejasVplsConfigEntry nc:operation="delete" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
        <CI>0</CI>
        <SI>0</SI>
        <SN>99</SN>
        <vplsConfigIndex>3</vplsConfigIndex>
    </tejasVplsConfigEntry>
</tejasVplsConfigTable>

When I tried to delete using the above command getting success but key fields are exist.
After delete I tried to get. Getting the following inf even after delete

<tejasVplsConfigTable xmlns="urn:ietf:params:xml:ns:yang:smiv2:tejasvplsconfig-mib">
    <tejasVplsConfigEntry nc:operation="delete" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
        <CI>0</CI>
        <SI>0</SI>
        <SN>99</SN>
        <vplsConfigIndex>3</vplsConfigIndex>
    </tejasVplsConfigEntry>
</tejasVplsConfigTable>

Thanks
Samba

**Comment by michalvasko** [comment]
No, the `import` command does not interpret the operations, only the `edit` command does.

**Comment by samba2127** [comment]
Thanks,
Is there any way to delete using the sysrepocfg tool ?

Thanks,
Samba

**Comment by michalvasko** [comment]
Yes, I have already written that you can use the `edit` command.

**Comment by samba2127** [comment]
Hi All,

how to get the client ip and session id ?
In my audit log to show that session id and client ip address.

Could please tell me how to get these two parameters.

Thanks,
Samba

**Comment by michalvasko** [comment]
You can run the server with the parameters `-d -v2`, it should then print information about connected clients.

**Comment by michalvasko** [comment]
I do not understand, you want to modify *netopeer2* code? In that case just find where the prints are and you will see how the information is retrieved.

**Comment by samba2127** [comment]
I don’t want to modify netopeer2 code . is there any API to get the session id and client information

Thanks
Samba

**Comment by michalvasko** [comment]
The server is a binary, it has no API. But you should be able to find the session information in `ietf-netconf-monitoring` operational data. Run `sysrepocfg -X -d operational -m ietf-netconf-monitoring` to print them.

**Comment by samba2127** [comment]
Hi All

I am trying to modify the existing config using the following command .
sysrepocfg  --datastore running --edit=mplsTelink.xml

It is failing and saying that validation fail .
How can I change the existing configuration using the sysrepocfg command ?
and the same time I want to use same command for creating and modifying
Please suggest is there any options for this.

For example
existing configuration is
<tejasMplsTELinkTable xmlns="urn:ietf:params:xml:ns:yang:smiv2:tejasmplstelink-mib">
    <tejasMplsTELinkEntry>
        <CI>0</CI>
        <SI>0</SI>
        <SN>99</SN>
        <TE_LinkId>2</TE_LinkId>
        <RemoteRouterId>0.0.0.0</RemoteRouterId>
        <LocalIpAddress>22.22.22.1</LocalIpAddress>
        <RemoteIpAddress>22.22.22.2</RemoteIpAddress>
        <LocalUnnumIfIndex>0</LocalUnnumIfIndex>
        <RemoteUnnumIfIndex>0</RemoteUnnumIfIndex>
    </tejasMplsTELinkEntry>
</tejasMplsTELinkTable>

Modified configuration is :
<tejasMplsTELinkTable xmlns="urn:ietf:params:xml:ns:yang:smiv2:tejasmplstelink-mib">
    <tejasMplsTELinkEntry>
        <CI>0</CI>
        <SI>0</SI>
        <SN>99</SN>
        <TE_LinkId>2</TE_LinkId>
        <RemoteRouterId>66.66.66.66</RemoteRouterId>
        <LocalIpAddress>22.22.22.1</LocalIpAddress>
        <RemoteIpAddress>22.22.22.2</RemoteIpAddress>
        <LocalUnnumIfIndex>0</LocalUnnumIfIndex>
        <RemoteUnnumIfIndex>0</RemoteUnnumIfIndex>
    </tejasMplsTELinkEntry>
</tejasMplsTELinkTable>



_______________________________________________________________________________________________________________________


Tejas Networks Limited (Tejas Networks) is committed to safeguard your privacy. Read the appropriate Privacy Notice  (https://www.tejasnetworks.com/privacy-notice) applicable to you to know more about how Tejas Networks collects, uses and stores your personal data. Please visit our Privacy Policy (https://www.tejasnetworks.com/privacy-policy) available on our website www.tejasnetworks.com for more information about our commitment towards data privacy under applicable data protection laws. This email may contain confidential or privileged information for the intended recipient(s). If you are not the intended recipient, please do not use or disseminate the information, notify the sender and delete it from your system.

**Comment by michalvasko** [comment]
So what is the validation error? Use `-v3` to print it.

**Comment by samba2127** [comment]
User callback failed.
sysrepocfg error: Validation failed (Validation failed)
For more details you may try to increase the verbosity up to "-v3".
sysrepocfg error: User callback failed. (User callback failed)
For more details you may try to increase the verbosity up to "-v3".
sysrepocfg error: Failed to merge edit data (User callback failed)
For more details you may try to increase the verbosity up to "-v3"

Thanks,
Samba

**Comment by michalvasko** [comment]
You have clearly not used `-v3` because then `sysrepocfg` does not suggest to use it.

**Comment by michalvasko** [comment]
No changes in the repository are needed, just use `sysrepocfg` to edit the *netopeer2* configuration.

**Comment by samba2127** [comment]
We do not have a console login once image upgrade in the server. So that I need to use in one of the script. Is that possible?
 I can not execute sysrepocfg command, because device is in customer place.

Thanks,
Samba

**Comment by michalvasko** [comment]
Then supply your own script. The point is the scripts in the repository will not be changed so I cannot help you and you have to solve the problem yourself.
