### ISSUE TITLE
Locking a mutex failed (sr_shmext_change_sub_add: Connection timed out).: Timeout expired

### ISSUE THREAD

**Issue by Krisscut** [sysrepo/sysrepo#3357]
Hi !

**Versions:**
_sysrepo-2.2.150
libnetconf2-3.0.11.devel
libyang-2.1.148
sysrepo-python-1.5.0_

Since quite some time now, it seems there is some kind of concurrency issue with the subscription of multiple sysrepo connection to various module.
In the past to workaround that I staggered the service startup to avoid sub being done at the same time, but I wonder if this is a wrong usage of the lib or an issue in the underlying code ?

For context, there are multiples services that are running at the same time, some in C using directly sysrepo lib, and some in python using the python-sysrepo wrapper.

I had instances where the C code failed with that error:

(In this case, get sub with **sr_oper_get_subscribe**)
> 
> 2024-07-05 14:23:42,830 DEBG 'orusw' stdout output:
> [ERR] Locking a mutex failed (sr_shmext_oper_get_sub_add: Connection timed out).
> 2024-07-05 14:23:42/ERR:UE_APP-OAM/sysrepo[RU01]: UE_APP-OAM/sysrepo, Locking a mutex failed (sr_shmext_oper_get_sub_add: Connection timed out).
> 2024-07-05 14:23:42/ERR:UE_APP-OAM/orusw[RU01]: o-ran-main.c:593 - orusw_data_get_subscribe() - Subscribing for providing data for path  "/o-ran-transceiver:port-transceivers" of module  "o-ran-transceiver" state data failed (Timeout expired).
> 

And others where the python code fails to sub:
(In this case a module change subscribe)
> 2024-07-17 03:10:24,007 DEBG 'UserManagement' stdout output:
> 2024-07-17 03:10:24.007 INFO/UE_APP-OAM/UserManagement: Sysrepo.py:501 - setup_sysrepo_logging() - Setting up sysrepo logging for the first time.
> 
> 2024-07-17 03:10:24,008 DEBG 'UserManagement' stdout output:
> 2024-07-17 03:10:24.008 INFO/UE_APP-OAM/UserManagement: util.py:56 - log_callback() - Session 46 (user "root", CID 60) created.
> 
> 2024-07-17 03:10:24,009 DEBG 'UserManagement' stdout output:
> 2024-07-17 03:10:24.008 INFO/UE_APP-OAM/UserManagement: util.py:56 - log_callback() - Session 47 (user "root", CID 60) created.
> 
> 2024-07-17 03:10:24,009 DEBG 'UserManagement' stdout output:
> 2024-07-17 03:10:24.009 INFO/UE_APP-OAM/UserManagement: UserManagement.py:57 - __init__() - User Management Service started, subscribing to ietf-netconf-acm and o-ran-usermgmt
> 
> 2024-07-17 03:10:24,511 DEBG 'UserManagement' stdout output:
> 2024-07-17 03:10:24.509 ERROR/UE_APP-OAM/UserManagement: util.py:56 - log_callback() - Locking a mutex failed (sr_shmext_change_sub_add: Connection timed out).
> 
> 2024-07-17 03:10:24,512 DEBG 'UserManagement' stdout output:
> 2024-07-17 03:10:24.510 ERROR/UE_APP-OAM/UserManagement: UserManagement.py:360 - <module>() - main crashed. Error: Locking a mutex failed (sr_shmext_change_sub_add: Connection timed out).: Timeout expired
> Traceback (most recent call last):
>   File "/opt/UE_APP_OAM/service/UserManagement/UserManagement.py", line 358, in <module>
>     main()
>   File "/opt/UE_APP_OAM/service/UserManagement/UserManagement.py", line 352, in main
>     service = UserManagement()
>   File "/opt/UE_APP_OAM/service/UserManagement/UserManagement.py", line 58, in __init__
>     self.sysrepo.subscribe_module_change("ietf-netconf-acm", "/ietf-netconf-acm:nacm", self.callbackNacm)
>   File "/opt/UE_APP_OAM/python_lib/Sysrepo.py", line 658, in subscribe_module_change
>     self.sessionRunning.subscribe_module_change(module, xpath, hook, priority = priority, include_deleted_values=True)
>   File "/opt/UE_APP_OAM/lib/python3.9/site-packages/sysrepo/session.py", line 360, in subscribe_module_change
>     check_call(
>   File "/opt/UE_APP_OAM/lib/python3.9/site-packages/sysrepo/errors.py", line 175, in check_call
>     raise SysrepoError.new(msg, ret)
> sysrepo.errors.SysrepoTimeOutError: Locking a mutex failed (sr_shmext_change_sub_add: Connection timed out).: Timeout expired
> 
> 2024-07-17 03:10:24,517 DEBG 'LBMService' stdout output:
> 2024-07-17 03:10:24.517 INFO/UE_APP-OAM/LBMService: LBMService.py:45 - __init__() - LBM Service started, subscribed to o-ran-processing-element
> 
> 2024-07-17 03:10:24,519 DEBG 'LBMService' stdout output:
> READY=1
> 2024-07-17 03:10:24,519 DEBG 'LBMService' stdout emitted a comm event
> 2024-07-17 03:10:25,252 DEBG 'LinkManagerOru' stdout output:
> 2024-07-17 03:10:25.252 INFO/UE_APP-OAM/LinkManagerDockerOru: LinkManagerCommon.py:1666 - wait_process_state() - Waiting for SRV/CallHomeManager/State to be in 'Started' state (current_state is None)
> 
> 2024-07-17 03:10:25,380 DEBG 'CallHomeManager' stdout output:
> 2024-07-17 03:10:25.379 INFO/UE_APP-OAM/CallHomeManager: CallHomeManager.py:148 - __init__() - Waiting for SRV/UserManagement/State to be in state Started before proceeding with startup.
> 
> 2024-07-17 03:10:27,150 DEBG 'orusw' stdout output:
> 2024-07-17 03:10:27/INF:UE_APP-OAM/orusw[RU01]: o-ran-sync.c:147 - send_notif_synce_state_change() - <NC_NOTIF> /o-ran-sync:synce-state-change [synce-state=LOCKED] send
> [INF] EV ORIGIN: "/o-ran-sync:sync" "oper get" index 0 ID 1 published.
> 2024-07-17 03:10:27/INF:UE_APP-OAM/sysrepo[RU01]: UE_APP-OAM/sysrepo, EV ORIGIN: "/o-ran-sync:sync" "oper get" index 0 ID 1 published.
> [INF] EV LISTEN: "/o-ran-sync:sync" "oper get" ID 1 processing.
> 2024-07-17 03:10:27/INF:UE_APP-OAM/sysrepo[RU01]: UE_APP-OAM/sysrepo, EV LISTEN: "/o-ran-sync:sync" "oper get" ID 1 processing.

Or maybe for that kind of case where multiple applications are trying to sub at the same time, there is some kind of timeout that should be increased ?

Also I see new versions were released since the one that is used in my examples, do you know if they were any improvements regarding that ?

**Comment by michalvasko** [comment]
> Also I see new versions were released since the one that is used in my examples, do you know if they were any improvements regarding that ?

Yes, I think there were some changes that can definitely affect this. If you are creating too many subscriptions simultaneously, it is possible some of them time out. But, there can also be a deadlock and to fix that, I would need to reproduce the issue, which may not be simple.

**Comment by Krisscut** [comment]
>  If you are creating too many subscriptions simultaneously, it is possible some of them time out.

Correct me if i'm wrong but it seems we go through this code in my case:

https://github.com/sysrepo/sysrepo/blob/7a8ebf352316ec17846d728a3132e7dee2418a6c/src/shm_ext.c#L826

So calling this function withextlock to 1

https://github.com/sysrepo/sysrepo/blob/7a8ebf352316ec17846d728a3132e7dee2418a6c/src/shm_ext.c#L45

So meaning we go through this code:

https://github.com/sysrepo/sysrepo/blob/7a8ebf352316ec17846d728a3132e7dee2418a6c/src/shm_ext.c#L50-L55

And  the timeout seems to be 500 ms in this case.
https://github.com/sysrepo/sysrepo/blob/7a8ebf352316ec17846d728a3132e7dee2418a6c/src/common.h#L79

So it could be that at some point we have too many subs and it reaches the timeout.

Hum, is there some configuration regarding that timeout that could be tuned ?
Or we can patch the code before build to try with it increased a little bit. (Should not have side effect if we increase to 5000 for instance, right ?)

**Comment by michalvasko** [comment]
You can definitely try increasing this timeout and test how the behavior changes.

**Comment by Krisscut** [comment]
I increased the timer to 5000 and issue can't be reproduced, so this was indeed just a matter of too many subscribes done at once and causing other services to fail getting the lock due to the "queue"

Maybe these timeouts should be made configurable (or maybe they already are ?) to allow more flexibility to users. (And avoiding the need to patch 😀)

**Comment by michalvasko** [comment]
Some timeouts are configurable but there are so many of them that all cannot be customized. I suppose this timeout can be increased but 5 s seems too much, maybe 2 s would be enough?

**Comment by Krisscut** [comment]
Yes probably, but I was thinking that maybe we could have them configurable at build time, because it depends on user's situation and hardware.
In my situation it was running in an environment where there was quite a bit of load spike at startup with lot of applications doing things in a short amount of time, and it caused the timeouts to be reached.

Since it is a timeout, is there a reason why the timeouts are "low" ?
In my case when there is some kind of timeout usually it causes problems down the line, so I increased it a lot because if it becomes stuck for that long It means I have other issues.

**Comment by michalvasko** [comment]
> if it becomes stuck for that long It means I have other issues.

That was the rationale, why make the function wait for 5, 10 s when there is obviously a problem, a timeout error can be returned sooner. So I am not sure increasing the timeouts would be any improvement.

**Comment by Krisscut** [comment]
Yes I agree, but the defaults seems to be a bit low when there is some load on the hardware.
What I meant is that huge timers like 30 or 60 are a bit too much, but I think 2 or 5s  would be fine to quickly report an issue, while still allowing some room for "slowness"

I tested with 5s in my environment but I could try with 2s and see how it goes.

**Comment by michalvasko** [comment]
I would prefer to tune any small timeouts, so yes, please test 2s or a bit more if it is enough, 5s seems too much.

**Comment by Krisscut** [comment]
I confirm 2s is fine with our environment instead of the 5s proposed earlier.

**Comment by scalabeginner** [comment]
Hi @michalvasko!

```
libyang v3.4.2
sysrepo v2.11.7
libnetconf2 v3.5.1
netopeer2 v2.2.31
```

We can see same behaviour: sr_shmext_change_sub_add Connection timed out.: Timeout expired
I see that for this issue SR_EXT_LOCK_TIMEOUT was changed to 2s.
But I' ve checked out last version of sysrepo and found that this parameter is equal to 500ms again. Which is probably strange...
Can it be set to 2000ms? Or was there some reason that the value was reset to the old value?

**Comment by michalvasko** [comment]
The change is still only in the `devel` branch and will get into `master` on the next release, in a few weeks.

**Comment by scalabeginner** [comment]
Okay! Thanks for your fast answer!
