### ISSUE TITLE
Sysrepo DB replication across nodes

### ISSUE THREAD

**Issue by svashok** [sysrepo/sysrepo#3358]
Hi,

This is my requirement: I have an OAM agent which hosts a Netconf server and maintains the sysrepo datastore within the container. In order to achieve node-level-redundancy for OAM agent I will have a standby OAM agent running on a different worker node / server which hosts another Netconf server (upon becoming active) and corresponding sysrepo datastore. Every time a Netconf client or SMO updates the config in this Netconf server / sysrepo I need the same update to be replicated to the standby sysrepo on the other node. Client cannot send the data to both Netconf servers. Can someone please suggest what kind of plugins/tools I can use to achieve this datastore replication?

Thanks!

**Comment by svashok** [comment]
Thanks for the quick response Michal. I would prefer to notify standby sysrepo for all config change events. By basic backup mechanism I believe you meant a periodic sync, which I do not prefer. Do you have any simpler solution for this please?

**Comment by michalvasko** [comment]
Well, you could subscribe to all the configuration changes and then just send them to the other *sysrepo* in the callbacks. You will not come up with anything simpler, I think.

**Comment by svashok** [comment]
Thanks, this helps :)

**Comment by svashok** [comment]
Michal, a follow up question please. Client-server interaction can be on standard RPCs, but here we send the data from one server's db to another server's sysrepo db. It cannot be sent via Netconf RPC directly, do you suggest to send it via IPC through the underlying platform?

Another question: Apart from notifications, can a server anonymously send any data (edit-config RPC) to its clients? Or it has to be always a get-config from the clients?

**Comment by michalvasko** [comment]
> Client-server interaction can be on standard RPCs, but here we send the data from one server's db to another server's sysrepo db. It cannot be sent via Netconf RPC directly, do you suggest to send it via IPC through the underlying platform?

You mentioned the other *sysrepo* is on a different system and has a NETCONF server running so it can be sent via a NETCONF `edit-config`. You could use IPC only if both *sysrepo* instances were on a single machine.

> Apart from notifications, can a server anonymously send any data (edit-config RPC) to its clients?

The basic communications model used is RPC, which means the client **must** send a request and the server then sends a **response**. It can never simply send a response.
