### ISSUE TITLE
test_access_get and test_access_setandget fail with version 2.10.1

### ISSUE THREAD

**Issue by ankitsingh1712** [sysrepo/sysrepo#3361]
With sysrepo version 2.10.1, built with -DSYSREPO_UMASK=077, the following tests fail-

[  FAILED  ] test_access_get
[  FAILED  ] test_access_setandget
[  ERROR   ] --- perm == perm_out

Adding additional logs indicated the difference in perm and perm_out
perm (600) perm_out (604)[  FAILED  ] test_access_get
perm (400) perm_out (446)[  FAILED  ] test_access_setandget

Also some relevant warning log indicate the the difference in perm and perm_out is same as the ignored bits.
[WRN]: Ignoring permission bits 004 forbidden by Sysrepo umask.
[WRN]: Ignoring permission bits 046 forbidden by Sysrepo umask.

On removing  -DSYSREPO_UMASK=077, the tests pass.

Do the tests need some update to handle cases when SYSREPO_UMASK is defined ?

**Comment by michalvasko** [comment]
Yes, a custom umask affects the tests. Should now be accounted for and the tests simply skipped.
