### ISSUE TITLE
Augmented predicates in XPath

### ISSUE THREAD

**Issue by mitjarislakki** [sysrepo/sysrepo#3362]
Hello,

I'm playing around with `application_changes_example` prior to implementing my own plugin. Currently I have ietf-interfaces augmented by ieee802-dot1q-bridge & ieee802-dot1q-sched-bridge. I would like to filter interfaces to be those with supported-list-max>0, pertaining to XPath `/ietf-interfaces:interfaces/interface[ieee802-dot1q-bridge:bridge-port/ieee802-dot1q-sched-bridge:gate-parameter-table/supported-list-max>0]`.

In netopeer2-cli connected to netopeer2-server on the same machine, I am able to filter via the mentioned XPath in get-config, returning all interfaces fulfilling the predicate (e.g. br0). However, if I run `application_changes_example` as

`./application_changes_example ietf-interfaces "/ietf-interfaces:interfaces/interface[ieee802-dot1q-bridge:bridge-port/ieee802-dot1q-sched-bridge:gate-parameter-table/supported-list-max>0]"`

And send a simple change via netopeer2-cli  (gate-enabled was previously false)

`edit-config --target running --config=change.xml`

```XML
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interface>
    <name>br0</name>
    <bridge-port xmlns="urn:ieee:std:802.1Q:yang:ieee802-dot1q-bridge">
      <gate-parameter-table xmlns="urn:ieee:std:802.1Q:yang:ieee802-dot1q-sched-bridge">
        <gate-enabled>true</gate-enabled>
      </gate-parameter-table>
    </bridge-port>
  </interface>
</interfaces>
```
The changes are applied but the example does not print any information. With no XPath or as `ietf-interfaces:interfaces/interface[name='br0']` the example prints the changes as expected. Is this expected behavior in the XPath implementation of sysrepo? Is there documentation for supported XPath capabilities?

Using newest github releases: sysrepo 2.10.1, libyang 3.1.0, libnetconf2 3.3.3 and netopeer2 2.2.28.

**Comment by michalvasko** [comment]
The XPath you pass to `application_changes_example` is filtering the **changes** and in your case the change was only in the node `gate-enabled`. But if you filter based on the keys of any parent lists of the changes, that should also work. No other data are provided for filtering, only the changes with any parent nodes.

**Comment by mitjarislakki** [comment]
Hi Michal,
Apologies but I'm not sure I understand what you mean. The docs mention that in `sr_module_change_subscribe` XPath is used to filter the changes handled by the subscription. This does indeed work if the XPath predicate is a key of the node, e.g. `/ietf-interfaces:interfaces/interface[name='br0']` limits the subscription to changes within that node. However, if the XPath contains some other predicate, such as `/ietf-interfaces:interfaces/interface[enabled='true']`, it does not listen to any changes on the matched interfaces.

Since the latter is still a valid XPath, perhaps this should be mentioned somewhere in the documentation, assuming it's intended functionality?

**Comment by michalvasko** [comment]
I suppose it should be explained in detail somewhere since you have not understood what I have written even now. I am saying the XPath is used to filter **changes**. Changes are basically a standard *libyang* data tree with operations on its nodes (also called diff). In comparison with **data**, which are the whole stored *libyang* data, not just the changed nodes with their parents.

So what I am saying is that if there are nodes changed that fit the used filter, the subscription is notified. But if the relevant nodes are not found in the changes (despite being in the data, which is exactly your use-case), the filter does not match because it does not access all the stored data, only the changes.

**Comment by mitjarislakki** [comment]
I believe I get it now. Thank you for the clarification.
