### ISSUE TITLE
not able to update ietf-netconf-server

### ISSUE THREAD

**Issue by biswajit84** [sysrepo/sysrepo#3378]
Hi,
I am trying to create callhome entry in ietf-netconf-server programmatically using sr_set_item_str and sr_apply_changes API.
But after executation of the applicatication, when I try to check the content using sysrepocfg -E vim -m ietf-netconf-server,
I Need help in figuring out the mistake if any.
If its not right approach, then please share how I can achieve it. 

Regards,

**Comment by michalvasko** [comment]
You can do that but without more details I have no idea what the problem is.

**Comment by biswajit84** [comment]
Hi,
sysrepo version:sysrepo-2.2.170
I have created session as SR_DS_OPERATIONAL.
path: /ietf-netconf-server:netconf-server/call-home/netconf-client[name='SMO']/endpoints/endpoint[name='default-tls']/tls/tcp-client-parameters/remote-address 
value:localhost
sr_set_item_str(srData.session, path, value, NULL, 0);
sr_apply_changes(session, 0);
 I have checked return value of both sr_set_item_str and sr_apply_changes all worked.
But when I checked through sysrepocfg -E vim -m ietf-netconf-server 
its not updating. As of now, I am trying to only one leaf into ietf-netconf-server.
Let me know if you need any other info which can help in finding the issue.

**Comment by michalvasko** [comment]
The problem is with the operational datastore, why have you chosen this one? Just use running and it will work.

**Comment by biswajit84** [comment]
As suggested, I tried with SR_DS_RUNNING . But now, sr_apply_changes is giving error error code as  9(SR_ERR_VALIDATION_FAILED). Any idea for this error code.






</body>
</html>

**Comment by michalvasko** [comment]
Well, turn on logging (`sr_log_stderr(SR_LL_WRN)`) or look at the generated error yourself (`sr_session_get_error()`).

**Comment by biswajit84** [comment]
Adding sr_log_stderr(SR_LL_WRN) helped me in finding the issue. 
I was supposed to add tls-server-parameters and other required fields
