### ISSUE TITLE
Schema mount error for edit-config

### ISSUE THREAD

**Issue by msuryarao2011** [sysrepo/sysrepo#3381]
Hi ,

I am using libyang-3.1.10 and netopeer2-2.2.28 , sysrepo 2.10.1

I have loaded required yang files for 3GPP model and urn:3gpp:sa5:_3gpp-common-subnetwork.yang which uses ietf-yang-schema-mount as mount-point .
Prepared XML data having the mount-point with shared-schema in the single XML .
Tried performing edit-config operation using netopeer2-cli
edit-config --target candidate --config=/root/package/vinay/config-mount.xml
nc ERROR: Unable to parse mounted data, no operational schema-mounts data received from the server.
ERROR
type: application
tag: operation-failed
severity: error
message: Ext plugin "ly2 schema mount v1": Callback for getting ext data failed.

Prepared only mount point xml and tried edit-config using netopeer2-cli
edit-config --target candidate--config=/root/package/netopeer2-2.2.28/build/sample/xml/schema-mount.xml
ERROR
type: application
tag: operation-failed
severity: error
message: List "parent-reference" with duplicate instances allowed found without required metadata.

    type:     application
    tag:      operation-failed
    severity: error
    message:  User callback failed.

Tried adding the deviation to the mount-point using deviation "/yangmnt:schema-mounts" {
deviate not-supported;

connect with netopeer-cli 
ly ERROR: Not found node "schema-mounts" in path. (/ietf-yang-library:yang-library)

As per this https://github.com/sysrepo/sysrepo/issues/2842 there was fix added to support the same .
Can i perform edit-config operation for the same if not can i use the deviation to the schema mount to pass the XML in the edit config without using schema mount.
Can you please suggest

**Comment by jktjkt** [comment]
Please stop opening duplicate bugreports and see https://github.com/CESNET/libyang/issues/2277#issuecomment-2268857242 .

**Comment by msuryarao2011** [comment]
Thanks for your support
