### ISSUE TITLE
Question on extracting Xpath from edit-config on subscription for /ietf-netconf:edit-config

### ISSUE THREAD

**Issue by srikanths1** [sysrepo/sysrepo#3382]
Hi,

we are trying to work on a validation mechanism ( https://github.com/CESNET/netopeer2/issues/1616 )
1. when the management entity sends an edit-config operation to netconf server 
2. we would like to store the root Xpath locally on Agent which is connected to sysrepo on edit-config operation
3. when the clients (across different nodes ) receives push notification and send a rpc on server to update the delta config
4. the agent would like to check if validated Xpath is contained in the edit-config's ( root Xpath ) 

can we get details of any api , which could extract or store the config section's root Xpath with sr_rpc_subscribe for /ietf-netconf:edit-config on candidate data store.

Thanks,
Srikanth

**Comment by michalvasko** [comment]
I am not sure this will really work overall, but to answer you, if you call `sr_rpc_subscribe()` on the `<edit-config>`, you will have access to the full RPC data tree in the callback. So you can traverse it, find the top-level (root) node and generate its XPath (`lyd_path()`). You can also check this way for only the `candidate` datastore.
