### ISSUE TITLE
Can nacm deny rpc output specific field?

### ISSUE THREAD

**Issue by Balagogo0514** [sysrepo/sysrepo#3388]
```yang
module vrouter-users

rpc show-users {
  output {
    list admin-list {
      key "name";
      leaf name {
        type string;
      }
      leaf cookie {
        type string;
      }
    }
    ...
  }
}
```

```xml
<rule>
  <name>deny-user-cookie</name>
  <module-name>vrouter-users</module-name>
  <rpc-name>show-users</rpc-name>
  <path>/vrouter-user:show-users/admin-list/cookie</path>
  <access-operations>read</access-operations>
  <action>deny</action>
</rule>
```

==> Not found node "admin-list" in path.

**Comment by jktjkt** [comment]
What does `deny-user-cookie vrouter-users get-detailed-info /vrouter-user:show-users/admin-list/cookie read deny` mean? It's neither JSON nor XML encoding of an NACM rule. Are you maybe using some third-party software? In that case you might want to talk to its upstream developers for support.

The NACM standard says that the path should refer either to a "data node", or "action node", or "notification node". If I'm reading the wording correctly, nodes below an RPC's `input` are neither of these, but I might be wrong.

**Comment by Balagogo0514** [comment]
I have corrected the error in the post. I would like to confirm whether nacm cannot work on the rpc output field?

**Comment by michalvasko** [comment]
Try
```xml
<path>/vrouter-user:show-users/output/admin-list/cookie</path>
```

**Comment by Balagogo0514** [comment]
Hi michalvasko,

"sysrepo.errors.SysrepoInvalArgError: Not found node "output" in path.,"

**Comment by michalvasko** [comment]
Seems @jktjkt is right, the NACM is not even applied on RPC/action output so it is useless to specify it in the path.
