### ISSUE TITLE
Internal handling of sysrepo of yang files

### ISSUE THREAD

**Issue by capiman** [sysrepo/sysrepo#3393]
My question points not to how to install a new (user related) yang file, but to the already available *.yang files.
My question points to branch "devel", but I assume it is the same on "master".

There is a directory modules which contains a lot yang files.
There is also a script called generate_headers.sh, which converts found yang files into header files which are also committed to git.

Why are the header files committed to git and not just converted on the fly?

Even when adding a new yang file, it is not used. It does not occur when compiling and call "sysrepoctl -l".
Even when converting a yang file to a header file, it does not occur when compiling and call "sysrepoctl -l"

Is it needed to add the name of the variable, which is used in the header file, into some of the other (source and/or header) files?
Must certain yang file(s) reference the new yang file?
Or somewhere in CMakeLists.txt?

Is there perhaps some documentation which describes the internal mechanism, where I can just look this up?
Or only hard way to read through repo?

**Comment by capiman** [comment]
To answer my own question it seems to be this file/positions:

https://github.com/sysrepo/sysrepo/blob/7a8ebf352316ec17846d728a3132e7dee2418a6c/src/lyd_mods.c#L65

https://github.com/sysrepo/sysrepo/blob/7a8ebf352316ec17846d728a3132e7dee2418a6c/src/lyd_mods.c#L1001

**Comment by capiman** [comment]
The yang file are copied to the target only for having a copy there, but not used anymore by sysrepo?
When updating a yang file (on the fly on target/after installation), it has no effect on sysrepo, because recompiling of sysrepo would be needed?

**Comment by michalvasko** [comment]
The internal YANG files are compiled as headers to simplify distribution and efficiently load these YANG modules. You should be able to update even these internal modules. As for some information source, there is none for internal functioning, did not seem worth the effort.
