### ISSUE TITLE
Question regarding yang module installation order.

### ISSUE THREAD

**Issue by jeremie6wind** [sysrepo/sysrepo#3394]
Hello,

Let me explain my use case.
I have 2 modules:
file_with_feature.yang it has one feature and a container
file_import_other.yang , it imports file_with_feature.yang and augment the container.

Before I could install file_import_other.yang before file_with_feature.yang
Now I need to install file_with_feature.yang with its feature before file_import_other.yang

I added a sample in which the schema_paths contains file_import_other.yang and file_with_feature.yang in this order:

[0001-example-with-import-and-augmentation.patch.txt](https://github.com/user-attachments/files/16614951/0001-example-with-import-and-augmentation.patch.txt)

If I change the order of the modules in schema_paths  it works.

Is it expected?
Thx

**Comment by michalvasko** [comment]
It was a regression and an internal error is never expected. Should be fixed.
