### ISSUE TITLE
multithreading question

### ISSUE THREAD

**Issue by rydy** [sysrepo/sysrepo#3402]
Hi,

I'm using version [v2.2.170](https://github.com/sysrepo/sysrepo/releases/tag/v2.2.170), Multiple threads calling 'sr_xxx' with the same 'sr_session_ctx_t' are not supported, right?

thanks.

**Comment by jktjkt** [comment]
[Nope](https://netopeer.liberouter.org/doc/sysrepo/master/html/index.html#threads).

**Comment by rydy** [comment]
> [Nope](https://netopeer.liberouter.org/doc/sysrepo/master/html/index.html#threads).

Is there a problem if multiple threads share a session but don't call the API at the same time?

**Comment by jktjkt** [comment]
The docs are very clear:

> a session is not synchronized at all so it must not be shared among multiple threads. Each thread should always create its own session to ensure correct behavior.

Creating a session is rather cheap; what's the problem?

**Comment by rydy** [comment]
> The docs are very clear:
> 
> > a session is not synchronized at all so it must not be shared among multiple threads. Each thread should always create its own session to ensure correct behavior.
> 
> Creating a session is rather cheap; what's the problem?

I use [plugin](https://netopeer.liberouter.org/doc/sysrepo/master/html/srpd_example.html) development approach, `session` unification is created by `sysrepo-plugind`, The plugin I developed created threads frequently, So the `sysrepo-plugind`is not for me, right?

**Comment by michalvasko** [comment]
You can use `sysrepo-plugind`, just create a new session for each thread. You can get the connection from the one provided `session`.
