### ISSUE TITLE
How to set initial valid data before installing module?

### ISSUE THREAD

**Issue by rgarcin-airspan** [sysrepo/sysrepo#3405]
Hi,

I am trying to install a YANG module for o-ran using sysrepo 2.10.1 (latest) and am facing the same issue as #2320 (back in 2021), ie. installating fails because there is a constraint that at least one user must have been configured in datastore:

```
[INF] Datastore copied from <startup> to <running>.
[INF] Connection 1 created.
[INF] Module "o-ran-usermgmt" was installed.
[ERR] At least one account needs to be enabled. (path "/o-ran-usermgmt:users")
[ERR] Invalid startup datastore data.
[INF] Module "o-ran-usermgmt" removed.
sysrepoctl error: Failed to install modules (Validation failed)
```

According to #2320 the solution is: "_You must set some initial valid data for it before it can be installed (using **sysrepocfg -W <data-file> -m o-ran-usermgmt**, for example)_." (@michalvasko)

Now, the -W command apparently no longer exists on 2.10.1, and I haven't managed to install any initial data because sysrepocfg's error below.

```
$ sysrepocfg -v3 -W o-ran-usermgmt.xml  -m o-ran-usermgmt
sysrepocfg error: Invalid option or missing argument: -W
```

```
$ sysrepocfg -v3 -I ./o-ran-usermgmt.xml --datastore startup  -m o-ran-usermgmt
[INF] Connection 2 created.
[INF] Session 1 (user "root", CID 2) created.
libyang[0]: No module with namespace "urn:o-ran:user-mgmt:1.0" in the context. (line: 3)
libyang error: No module with namespace "urn:o-ran:user-mgmt:1.0" in the context.
sysrepocfg error: Data parsing failed
```

How to set initial valid data on sysrepo 2.10.1?

Thanks!

**Comment by michalvasko** [comment]
It is now part of `sysrepoctl` functionality, parameter `-I` (look at `sysrepoctl -h`).

**Comment by jktjkt** [comment]
The parameter is called `--init-data` (`-I`). You're using that flag in your last example (to `sysrepocfg`), but you're expected to pass it during the installation phase (`sysrepoctl --install ...`) already.

**Comment by rgarcin-airspan** [comment]
OK, I had missed that. Thank you very much, guys!

```
$ sysrepoctl --install o-ran-usermgmt.yang -I o-ran-usermgmt.xml
[INF] Connection 2 created.
[INF] Module "o-ran-usermgmt" was installed.
[INF] File "o-ran-usermgmt@2023-12-11.yang" was installed.
[INF] File "o-ran-wg4-features@2024-04-15.yang" was installed.
```
