### ISSUE TITLE
[Question] why the sr_val's xpath should not have the last predicate for leaflist.

### ISSUE THREAD

**Issue by Ali-aqrabawi** [sysrepo/sysrepo#3407]
this causes issues in `frr`'s northbound integration, as `frr` uses `sr_val_t->xpath` to fetch the node, but because the last predicate is missing it fail.

from the code i see the last predicate is intentionally not included:
https://github.com/sysrepo/sysrepo/blob/7a8ebf352316ec17846d728a3132e7dee2418a6c/src/sysrepo.c#L5642

any specific reason ?

**Comment by michalvasko** [comment]
The change was made a long time ago so I do not remember exactly but I can assure you there was a reason. The value is in the `sr_val_t` structure anyway so I am not sure what the problem is. Also, `sr_val_t` should not be used ideally and `struct lyd_node` should be retrieved instead.
