### ISSUE TITLE
CMakeLists.txt: duplicate version info (of LIBYANG_DEP_SOVERSION_MAJOR)?

### ISSUE THREAD

**Issue by capiman** [sysrepo/sysrepo#3408]
Around line 70 (in master as well as devel):

# Version of libyang library that this sysrepo depends on
set(LIBYANG_DEP_VERSION 3.0.18)
set(LIBYANG_DEP_SOVERSION 3.1.7)
set(LIBYANG_DEP_SOVERSION_MAJOR 3)

Is the 3 line needed? Or already set by second line? Perhaps some remaining from earlier,
when version was defined by 3 lines?

**Comment by michalvasko** [comment]
Well, you are right, the stand-alone major SO version is not being used currently. But it may be later, if no special *libyang* features are needed, only ABI compatibility so I would keep it there, it does not matter really.
