### ISSUE TITLE
Missing install action in CMakeLists.txt for examples and "oven"?

### ISSUE THREAD

**Issue by capiman** [sysrepo/sysrepo#3409]
I am using branch "devel".

I am using the sysrepo CMakeLists.txt in a Yocto recipe. sysrepo as well as sysrepoctl, ... is installed,
but even when I enable examples (via ENABLE_EXAMPLES), the example executables as well as "oven" seems to be missing in final image.

I am not sure yet, but could it be due to missing something like

```
if(ENABLE_SYSREPOCTL)
    install(TARGETS sysrepoctl DESTINATION ${CMAKE_INSTALL_BINDIR})
    install(FILES ${PROJECT_SOURCE_DIR}/src/executables/sysrepoctl.1
            DESTINATION ${CMAKE_INSTALL_MANDIR}/man1)
endif()
```

for each app in examples, as well as oven?

There is only:

```
foreach(app_name IN LISTS examples)
    add_executable(${app_name} ${app_name}.c)
    target_link_libraries(${app_name} sysrepo)
endforeach(app_name)

# oven plugin
add_library(oven MODULE plugin/oven.c)
set_target_properties(oven PROPERTIES PREFIX "")
target_link_libraries(oven sysrepo)
```

in

https://github.com/sysrepo/sysrepo/blob/devel/examples/CMakeLists.txt

**Comment by jktjkt** [comment]
I think that there's little point in *installing* these examples, even when they are built -- they are toy code which is not meant for "real use". If it bothers you, you can always adjust your Yocto recipe to install them temporarily.
