### ISSUE TITLE
Question: Callbacks and threading model

### ISSUE THREAD

**Issue by rbu9fe** [sysrepo/sysrepo#3410]
I have a question how in a sysrepo plugin oper-get or change callbacks are handled. 

When a client wants to modify a configuration then the corresponding change callback handler is triggered in the plugin. In the `Done` event I want to push corresponding state data into the operational datastore. 

- Is it thread-safe to do so in the context of the change callback? The commit to the operational datastore may trigger another callback (e.g. registered by some other client), will that be able to run in the currently processed change callback?
- Can I safely change the datastore of the callback session to operational in order to push the new state data?

Thanks for your support!

**Comment by michalvasko** [comment]
Yes, all that you mentioned is thread-safe and fine. If not, you will encounter a dead-lock, which will result in a time-out of some function. In this case it depends on what modules are you accessing, *sysrepo* locks the data for each module separately.

**Comment by rbu9fe** [comment]
Thanks! In fact I'm asking because we have a sporadic deadlock followed by a timeout on system boot when trying to commit changes to the operational datastore. I assume either somewhere we're using the same session in different threads concurrently, or some registered change callback hangs itself (on some external resource).
Are there any other reasons for sysrepo to be blocked indefinitely?

**Comment by michalvasko** [comment]
> I assume either somewhere we're using the same session in different threads concurrently

This results in undefined behavior, not strictly a deadlock.

> some registered change callback hangs itself

Like I said, callbacks triggering new events and callbacks can often result in a deadlock in case an event is generated, which is handled by a thread that is currently processing an event. Or it is simply accessing a module that is locked by another event.

> Are there any other reasons for sysrepo to be blocked indefinitely?

Only what I mentioned, nothing else to my knowledge.

**Comment by rbu9fe** [comment]
Now I have more logs and it looks like the sequence is as follows:
1. In the plugin an external callback is handled in some non-sysrepo thread. This commits changes into the operational datastore.
2. An external process registered for that change, hence, its sysrepo change callback runs. In that it reads more data from the operational datastore.
3. The read-access to the operational datastore should trigger the oper-get callback in the plugin, however, that's not reached. Instead, the external process receives a timeout.

Now that shouldn't be a problem since the threads (and sessions) in 1. and 3. are different, right?

**Comment by rbu9fe** [comment]
But then the deadlock should _always_ happen when the callback in 1. is triggered, right? Instead, the deadlock occurs only sporadically.

**Comment by michalvasko** [comment]
Then I do not know, the easiest thing to do is to use `gdb` to stop the process when it hangs and then look at the lock held by each thread.

**Comment by rbu9fe** [comment]
I have a trace with debug symbols of the plugin but not yet of the external process that registered an operational change callback. I'll try to get that as well.

**Comment by jktjkt** [comment]
My suggestion is to stop using pull operational callbacks, and always push data to operational instead. You cannot really mix these two approaches, and you appear to do that.

**Comment by rbu9fe** [comment]
Yes we're using both depending on the nature of the operational data leaf. 
I now have complete stack traces and I'd like to share a sequence diagram that describes what happens, however, I can't upload the png. It says it's uploading but then it just disappears again - tried with Edge and Firefox :-(
So that's what happens in my words:
1. External callback applies operational changes and waits for subscribers to finish. Stack trace:
    - sr_cond_clockwait
    - _sr_shmsub_notify_wait_wr
    - sr_shmsub_change_notify_change_done
    - sr_changes_notify_store
    - sr_apply_changes
2. Client's subscriber callback runs trying to get operational data (of the same module). Stack trace:
    - sr_cond_clockwait
    - sr_sub_rwlock
    - sr_rwlock
    - sr_shmmod_modinfo_loc
    - sr_shmmod_modinfo_rdlock
    - sr_modinfo_consolidate
    - sr_get_data
3. In parallel there's another application trying to update another leaf in the operational datastore (in the same module). Stack trace:
    - sr_cond_clockwait
    - sr_rwrelock
    - sr_shmmod_loc
    - sr_shmmod_modinfo_rdlock_upgrade
    - sr_changes_notify_store
    - sr_apply_changes

Is my understanding correct that:
- 1. holds the module's operational lock while both 2. and 3. try to acquire it.
- If 2. is modified to avoid getting additional operational data then the deadlock is avoided.

**Comment by michalvasko** [comment]
I have trouble understanding more complex use-cases without being able to reproduce them and the locks were changed a few times so I cannot really provide reliable feedback.

> The plugin in 1. holds the module's operational lock while both 2. and 3. try to acquire it.

If this were true, you would always get the deadlock since 2. would be blocked by 1. and vice-versa.

> If 2. is modified to avoid getting additional operational data then the deadlock is avoided.

Perhaps, not sure, you can try it.

**Comment by rbu9fe** [comment]
I wrote a small test project using [the example Yang model](https://github.com/sysrepo/sysrepo/blob/master/examples/examples.yang) that implements [this](https://github.com/rbu9fe/sysrepo-cpp/blob/debug/debug/timeout.png) behaviour described above using operational push data only. Key to reproduce the error is to let another unrelated thread (modelling an external application) apply another change while a change callback is already running, that is about to query additional data - which then blocks. This can be seen in the timing output of that program:
```
Counter1 - Start: ApplyChanges at 63ms
Counter2 - Start: ApplyChanges at 124ms
Counter1 - Done: ApplyChanges at 5064ms
Got counter1 = 15 at 5166ms
Counter2 - Done: ApplyChanges at 5167ms
```
So there's a timeout after 5 seconds, however, that timeout seems not to be considered an error! Normally there would be an exception on timeouts, but here success is reported.

Note that everything works fine when the unrelated thread is not running 
 
So why does now `getNode` block when there's a parallel pending request to apply other data? 
Also, why is there no error returned even though there's a timeout?

Here's the code:
```
#include <iostream>
#include <chrono>
#include <ctime>
#include <thread>

#include <sysrepo-cpp/Connection.hpp>
#include <sysrepo-cpp/Session.hpp>

using namespace std::chrono;

static const std::string module_name{ "examples" };
static const std::string counter1_path{ "/examples:stats/counter" };
static const std::string counter2_path{ "/examples:stats/counter2" };

static const uint32_t value{ 15 };
static const milliseconds timeout{ 5000 };

static void printElapsedTime( const auto &start, const std::string &msg )
{
    std::cout << msg << duration_cast<milliseconds>( system_clock::now() - start ) << std::endl;
}

int main()
{
    const auto start{ system_clock::now() };

    auto session{ sysrepo::Connection{}.sessionStart( sysrepo::Datastore::Operational ) };

    /* Operational change callback, querying the operational datastore while another unrelated thread calls applyChanges. */
    auto sub_oper_change{ session.onModuleChange(
        module_name,
        [&start](
            [[maybe_unused]] sysrepo::Session cb_session, uint32_t, std::string_view, std::optional<std::string_view>,
            sysrepo::Event, uint32_t )
        {
            /* Let another unrelated thread update another leaf (counter2) while our callback is running but before we're querying the operational data. */
            std::jthread async_writer{
                [start]()
                {
                    auto unrelated_session{ sysrepo::Connection{}.sessionStart( sysrepo::Datastore::Operational ) };

                    unrelated_session.setItem( counter2_path, std::to_string( value ) );

                    printElapsedTime( start, "Counter2 - Start: ApplyChanges at " );
                    unrelated_session.applyChanges( timeout );
                    printElapsedTime( start, "Counter2 - Done: ApplyChanges at " );
                } };

            /* Make sure that the other thread called applyChanges and on callback exit don't wait for thread object destruction. */
            std::this_thread::sleep_for( 100ms );
            async_writer.detach();

            /* Now get some data, this blocks. */
            const auto &data{ cb_session.getOneNode( counter1_path ) };

            printElapsedTime(
                start, "Got counter1 = " + std::to_string( std::get<uint64_t>( data.asTerm().value() ) ) + " at " );

            return sysrepo::ErrorCode::Ok;
        },
        counter1_path, 0, sysrepo::SubscribeOptions::Passive | sysrepo::SubscribeOptions::DoneOnly ) };

    /* Callback to update the operational push-data. */
    session.setItem( counter1_path, std::to_string( value ) );

    printElapsedTime( start, "Counter1 - Start: ApplyChanges at " );
    session.applyChanges( timeout );
    printElapsedTime( start, "Counter1 - Done: ApplyChanges at " );

    return 0;
}
```

**Comment by michalvasko** [comment]
> So why does now getNode block when there's a parallel pending request to apply other data?

First, `applyChanges()` on the line 67 keeps the module locked for reading. Then, `applyChanges()` on 45 is trying to get the module write lock but cannot so it waits while "urging" to get it. Last, `getOneNode()` on 54 wants module read lock but is made to wait for the write urge lock.

The write urge lock (which prevents new read locks to be obtained so that the write lock is satisfied sooner) was introduced to prevent write lock starvation but, naturally, while it helps in some cases, it causes problems in others (such as this one).

> Also, why is there no error returned even though there's a timeout?

When using `sysrepo::SubscribeOptions::DoneOnly`, only the `done` callback is called, which does not have the option to abort the changes so its return value is ignored.

**Comment by rbu9fe** [comment]
Thanks, that explains it. However, if it's not considered a but then once must never access the operational datastore from within an operational change callback since another client trying to write at the same time may block that.
I assume that this behaviour is not limited to the operational datastore but holds as well for others, right?
But is accessing a different module or datastore safe, e.g. access the operational datastore from within a running change callback?

**Comment by michalvasko** [comment]
> Thanks, that explains it. However, if it's not considered a but then once must never access the operational datastore from within an operational change callback since another client trying to write at the same time may block that.

Either not access the operational datastore or not write into it at the same time. In general, the oper push data are not meant to be updated too often. For such data the pull oper subscriptions are supposed to be used.

> I assume that this behaviour is not limited to the operational datastore but holds as well for others, right?

Yes, I think so, but the operational datastore is the most complex one so there should less restrictions for other, in general.

> But is accessing a different module or datastore safe, e.g. access the operational datastore from within a running change callback?

Yes, that should be fine except for one use-case, which is exactly this one. Running datastore is needed when generating operational datastore so it is also read-locked (when writing to operational datastore). Other than that, the datastore data are separate and each of them has its own lock, just like all the modules. But modules often depend on each other when they are locked together, in which case you may, again, encounter dead locks.

**Comment by rbu9fe** [comment]
Yes we don't update the operational datastore often but for some data it makes sense to push it rather than deriving it each time someone wants to read. Sysrepo gives you a lot of flexibility here to optimize performance for a given setup, which I highly appreciate.
I think the limitations that can cause deadlocks should be mentioned somewhere in the docs.
Thanks for your support!

**Comment by michalvasko** [comment]
> Sysrepo gives you a lot of flexibility here to optimize performance for a given setup, which I highly appreciate.

The consequence of this is that there are lots of use-cases, some of which will not work properly and result in timeouts. Documenting all of this would be a substantial effort of questionable worth because the documentation is visited less often than you may think.

**Comment by jktjkt** [comment]
> In general, the oper push data are not meant to be updated too often. For such data the pull oper subscriptions are supposed to be used.

How often is "too often", and where is this documented? See, the reasons why we switched to using push ops data almost everywhere are:

- solving potential deadlocks related to threading and locking,
- control over when stuff gets visible in a YANG datastore,
- consistence of all possible data "views",
- telemetry,
- control over the total CPU load.

The last thing in particular was a real problem for us. Of course we are not talking about propagating, say, every `in-octets` increment in the statistics for the `ietf-interfaces` YANG, that would be insane...

**Comment by michalvasko** [comment]
It is written in the [docs](https://netopeer.liberouter.org/doc/sysrepo/devel/html/index.html#oper_data) but the point is only that this was the intention and expected usage when the oper data were designed. If it works for you for other use-cases, fine, no problem.
