### ISSUE TITLE
Query Regarding Notification

### ISSUE THREAD

**Issue by biswajit84** [sysrepo/sysrepo#3411]
Hi,
When there  are two netconf clients got connected through netconf session, how can we  send a notification from the external application to a perticular client only.

Regards,

**Comment by michalvasko** [comment]
This is not a supported use-case in NETCONF. All the clients subscribed to a notification(s) must receive them as they are generated.

**Comment by biswajit84** [comment]
whether Even though both the client has subscribed to different stream they will receive the notification because we dont have option to provide the stream in sr_notif_send.

**Comment by michalvasko** [comment]
I do not understand. It is as you said, the **subscribers** choose the notifications they want to receive. The **senders** do not choose which subscribers will receive their notifications.

**Comment by biswajit84** [comment]
To clarify my doubt, Client1 & Client2 executed below commands respectively.
Client1: subscribe --stream NETCONF --filter-xpath /o-ran-supervision:supervision-notification
Client2: subscribe --stream supervision-notification --filter-xpath /o-ran-supervision:supervision-notification

so from exteranal application when we send a supervision-notification notification using sr_notif_send, then  as you said both clients will receive as we dont have netconf session id also the stream details to provide. Netopeer2-server  will handle internally.  Or we have some other alternative.

**Comment by michalvasko** [comment]
I repeat, **client1** has decided it wants to receive `/o-ran-supervision:supervision-notification` notifications and **client2** has also decided it wants to receive `/o-ran-supervision:supervision-notification` notifications. The external application then cannot simply decide it does **not** want client1, for example, to receive its `/o-ran-supervision:supervision-notification` notification despite the client subscribing to it. That is how it works and how it was designed.

**Comment by biswajit84** [comment]
Thanks a lot for clarifying .
