### ISSUE TITLE
Query regarding RPC Subscription API

### ISSUE THREAD

**Issue by biswajit84** [sysrepo/sysrepo#3412]
Hi,
when multiple client got connected through netconf session.
I have subscribed xpath: o-ran-supervision:supervision-watchdog-reset using sr_rpc_subscribe api in external application.
Is there any way when the call back  triggered, I can  identify which client has pushed the rpc

**Comment by michalvasko** [comment]
The event originator can send any additional data if it wants, including some identification information. Look at `sr_session_set_orig_name()` and `sr_session_push_orig_data()`. In the callback you read the data using `sr_session_get_orig_name()` and `sr_session_get_orig_data()`.

**Comment by biswajit84** [comment]
I meant if we get netconf session id as one of the parameters which we get during start-sesstion callback ,so that I can compare the same with one of the sr_rpc_subscribe callback and identify from which netconf client it originates.

**Comment by michalvasko** [comment]
Right, I have somehow missed you are talking about NETCONF sessions, `netopeer2-server` uses the functions I mentioned to send session ID and user name of the RPC originator. More in the [README](https://github.com/CESNET/netopeer2/?tab=readme-ov-file#sysrepo-callbacks).

**Comment by biswajit84** [comment]
Hi ,
In the README link which has Sysrepo callbacks has the NETCONF session id of type uint32_t 
Please  re-confirm, whether sid which is of type uint32_t present inside sr_session_ctx_t   will be holding the netconf session id or not.
as sr_session_ctx_t will be 1st argument of  sr_rpc_subscribe callback .
` 
 struct sr_session_ctx_s {
    sr_conn_ctx_t *conn;            /**< Connection used for creating this session. */
    sr_datastore_t ds;              /**< Datastore of the session. */ `
    uint32_t sid;                   /**< Session ID. */

Regards

**Comment by michalvasko** [comment]
I do not understand what that has to do with anything. I have referenced the README because what is written there is correct.

**Comment by biswajit84** [comment]
The reason for confusion is whether the  sid  of sr_session_ctx_t is the netconf session id or sysrepo session id .Because the description against the sid it has mentioned as only "session ID". Also the README mentioned that if "particular event will be generated by netopeer2, there will be the NETCONF session ID" where as the the callback subscibed during sr_rpc_subscribe is for sysrepo rpc subscribe .
I am looking for somehow to get the netconf session id during callback invoke of sr_rpc_subscribe.

Regards

**Comment by jktjkt** [comment]
@biswajit84 , the README talks about the [originator data](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__conn__sess__api.html#ga53f63e06cb28241955a5052a3b526641), not about the content of the `sr_session_ctx_s`. Before you ask any further questions, please re-read the *entire* documentation of sysrepo and Netopeer2, including the READMEs and the doc site, because that has answers to all the questions that were asked so far.

**Comment by michalvasko** [comment]
@biswajit84 Sysrepo sessions have their own SID, which is in no way related to NETCONF SID. But the README I referenced tells you how to get NETCONF SID in the callbacks, which is exactly what you asked for. That is why I do not understand what Sysrepo sessions and SIDs have to do with this.
