### ISSUE TITLE
A problem with sysrepo notification delivery blocking.

### ISSUE THREAD

**Issue by Mootong** [sysrepo/sysrepo#3414]
I'm encountering an issue with two applications, let's call them A and B. Application A might frequently sends notifications to Application B using sysrepo. For various reasons, Application B might restart during operation, either normally through being stopped and started again, or due to a program exception that leads to a core dump and is then restarted by a monitoring process.

Sometimes after Application B restarts, Application A encounters an error when trying to send notifications, and is no longer able to send notifications to B. Sysrepo displays an error message similar to the following:

"**Waiting for subscription of 'xxx' failed, previous event 'notif' ID xx was not processed**"

Once this issue is triggered, the only way to restore functionality is by deleting the sysrepo database shared memory between A and B.

I've searched for similar error messages and error information, but haven't found any useful solutions. I'm currently using sysrepo version 2.2.170. Regarding this issue, do you have any suggestions?
![1727062673145](https://github.com/user-attachments/assets/a8bdd387-feab-4de4-88ad-b3a4e56c2e17)
![1727062543779](https://github.com/user-attachments/assets/c6ad3d22-30e8-4362-832b-d787cbd07782)

**Comment by michalvasko** [comment]
First, I would try to update *sysrepo* to the latest release. Let me know if that does not help.

**Comment by Mootong** [comment]
This problem may not necessarily reappear stably. At present, I am unable to directly upgrade to the latest version. I can upgrade to the latest version at some time in the future and observe whether the problem still exists.
