### ISSUE TITLE
sysrepo dynamic configuration update

### ISSUE THREAD

**Issue by mpanwar-github** [sysrepo/sysrepo#3417]
Hi Team, 

Greetings !!!

I have one xml having 10 parameter, when i push same xml,  I get all 10 parameters in callback registered. Later say one parameter i do change and push it again i am again getting all 10 parameter instead one changed.

Is there method to get only changed parameter if other parameter remain same. Also if someone add more and change some of existing parameter it should only give changed and newly added parameter.

Best Regards

**Comment by michalvasko** [comment]
> Later say one parameter i do change and push it again i am again getting all 10 parameter instead one changed.

That is not how it works, you should always get only the changed parameters meaning you are doing something a bit different. Please include the steps or code you are running.

**Comment by mpanwar-github** [comment]
closing ticket. missed to clear local database corrected.
