### ISSUE TITLE
Cannot load an Openconfig model in Sysrepo

### ISSUE THREAD

**Issue by ekimarclenaour** [sysrepo/sysrepo#3420]
Hello

Sorry to bother you...

I am trying to load an openconfig model in sysrepo, using such command:
"sysrepoctl -i ./openconfig-4.4.0-models/system/openconfig-aaa-radius.yang -s ./openconfig-4.4.0-models -v3"

And I get some error : 
[ERR] Input data contains submodule which cannot be parsed directly without its main module.
sysrepoctl error: Failed to install modules (libyang error)

I do not understand because the main module was already loaded before ... 

Please could you help ?

Marc

**Comment by jktjkt** [comment]
You cannot install a *submodule* directly. Since [`openconfig-aaa-radius`](https://github.com/openconfig/public/blob/master/release/models/system/openconfig-aaa-radius.yang) is  [part of the `opconfig-aaa`](https://github.com/openconfig/public/blob/3a3018590be5f7c11a3ed8c3530b128c53633d7b/release/models/system/openconfig-aaa-radius.yang#L5-7) module, just instal `openconfig-aaa`.

**Comment by ekimarclenaour** [comment]
I did it before, but then openconfig-aaa-radius was not loaded with openconfig-aaa ...
Did I miss an option?

**Comment by ekimarclenaour** [comment]
FIRST STEP:
sudo sysrepoctl -i ./openconfig-4.4.0-models/system/openconfig-aaa.yang  -s ./openconfig-4.4.0-models -v3
[INF] Connection 21 created.
[INF] Module "openconfig-aaa" was installed.
[INF] File "openconfig-aaa@2022-07-29.yang" was installed.
[INF] File "openconfig-aaa-tacacs@2022-07-29.yang" was installed.
[INF] File "openconfig-inet-types@2024-01-05.yang" was installed.
[INF] File "openconfig-extensions@2022-10-05.yang" was installed.
[INF] File "openconfig-aaa-types@2018-11-21.yang" was installed.
[INF] File "openconfig-types@2024-01-31.yang" was installed.
[INF] File "openconfig-aaa-radius@2022-07-29.yang" was installed.
[INF] File "openconfig-yang-types@2024-05-30.yang" was installed.
[INF] Connection 21 destroyed.

BUT THEN WHEN Doing sysrepoctl -l  I do not see the radius submodule:
openconfig-aaa                | 2022-07-29 | I     | root:root     | 600           | 600           | openconfig-aaa-tacacs openconfig-aaa-radius |
openconfig-aaa-types          | 2018-11-21 | i     |               |               |               |                                             |
openconfig-extensions         | 2022-10-05 | i     |               |               |               |                                             |
openconfig-inet-types         | 2024-01-05 | i     |               |               |               |                                             |
openconfig-types              | 2024-01-31 | i     |               |               |               |                                             |
openconfig-yang-types         | 2024-05-30 | i     |               |               |               |                                             |

**Comment by michalvasko** [comment]
Yes, as you can see, they are mentioned after the main module.

**Comment by ekimarclenaour** [comment]
Thank you for the answers
