### ISSUE TITLE
Dynamic data update read recursive to get each node operation type

### ISSUE THREAD

**Issue by mpanwar-github** [sysrepo/sysrepo#3422]
Hi Team,

Greetings !!!

I have one xpath= a/b[id=0]/c[id=0]/d initial i have applied value to d and it was stored. Further I want to change value of 'd' which is leaf i am getting correct operation type MODIFY with leaf value. for me internal db need to know each node operation type. 
a -> modify
b[id=0] -> modify
c[id=0] -> modify
d -> modify

I am using "application_changes_example.c" to simulate this scenario. can you help to identify correct get api for this above expected outsome.

Thanks and Regards
Manohar

**Comment by michalvasko** [comment]
You will never get `replace` operation on container or list nodes, only on leaves. But you can easily simulate similar behavior yourself if you really need it.

**Comment by mpanwar-github** [comment]
handled internally
