### ISSUE TITLE
Bundle custom YANG modules within libyang/sysrepo

### ISSUE THREAD

**Issue by pedrothaines** [sysrepo/sysrepo#3429]
**Context:** I'm facing performance issues when installing some YANG modules in a not so performant device. The modules are not that big and they are taking several minutes to be installed through `sysrepoctl --install`. Even the modules needed by _netopeer2_ are taking a long time to be installed.

**As of today, I'm using the latest versions of all libraries (libyang, sysrepo and netopeer2).**

I'm trying to bundle YANG modules into _libyang/sysrepo_ at compile time to avoid installing them later using `sysrepoctl --install`. However, I'm unsure if this is feasible, as it seems _sysrepo_ performs some form of "installation" for libyang's internal modules (I've noticed multiple references to _datastore plugins_ and the use of `sr_shm*` functions, which likely handle data preloading for each installed YANG module).

I came across a similar question: https://github.com/sysrepo/sysrepo/issues/3393

I'm going through _libyang/sysrepo_ documentation and code trying to figure out a way to speed up YANG module installation.

Initially, I thought that just adding a new module to _libyang_ `internal_modules[]` would be sufficient (after converting it to a C header file), but it is not.

```c
/* src/context.c */

/* SOMETHING LIKE THIS */
#include "../models/example_yang.h"

static struct internal_modules_s {
    const char *name;
    const char *revision;
    const char *data;
    ly_bool implemented;
    LYS_INFORMAT format;
} internal_modules[] = {
    {"ietf-yang-metadata", "2016-08-05", (const char *)ietf_yang_metadata_2016_08_05_yang, 0, LYS_IN_YANG},
    {"yang", "2022-06-16", (const char *)yang_2022_06_16_yang, 1, LYS_IN_YANG},
    {"ietf-inet-types", "2013-07-15", (const char *)ietf_inet_types_2013_07_15_yang, 0, LYS_IN_YANG},
    {"ietf-yang-types", "2013-07-15", (const char *)ietf_yang_types_2013_07_15_yang, 0, LYS_IN_YANG},
    {"ietf-yang-schema-mount", "2019-01-14", (const char *)ietf_yang_schema_mount_2019_01_14_yang, 1, LYS_IN_YANG},
    {"ietf-yang-structure-ext", "2020-06-17", (const char *)ietf_yang_structure_ext_2020_06_17_yang, 0, LYS_IN_YANG},
    /* SOMETHING LIKE THIS */
    {"example", "2024-10-10", (const char *)example_yang, 1, LYS_IN_YANG},
    /* ietf-datastores and ietf-yang-library must be right here at the end of the list! */
    {"ietf-datastores", "2018-02-14", (const char *)ietf_datastores_2018_02_14_yang, 1, LYS_IN_YANG},
    {"ietf-yang-library", IETF_YANG_LIB_REV, (const char *)ietf_yang_library_2019_01_04_yang, 1, LYS_IN_YANG}
};
``` 

My experience with the _libyang_, _sysrepo_, and _netopeer2_ ecosystem is still somewhat limited, so I am looking for guided assistance.

**Edit:** maybe I should have asked this in _libyang_ repository, but it doesn't hurt to have it here.

**Comment by michalvasko** [comment]
Actually, we face similar problems in some of our deployments but have no specific solution. Even if you somehow make your modules internal, it only allows you to not have to install them manually. But they are still normally installed when the very first `connection` is created and the advantage is that they they are parsed from memory and not a file, which should be faster. But that is about it so it would not speed up the initialization process much.

The best thing you can do is to install all the modules in a single `sysrepoctl` command. If everything is then properly stored in a persistent storage, you do not have to install the modules again.

**Comment by michalvasko** [comment]
Especially if you have lots of YANG modules, installing them all together is usually comparably fast to installing a single module. And like I said, persistent `/etc/sysrepo` (the repository) is what is expected and prevents the need to reinstall all the modules after each boot. You could store even the SHM files in `/dev/shm` to speed up creating the first connection even more but that is not necessary and should not make such a big difference.
