### ISSUE TITLE
sysrepo db plugin not working

### ISSUE THREAD

**Issue by VishalGujela** [sysrepo/sysrepo#3430]
Hi 
I have successfully created the plugin for postgres for my own usage.
The code has compiled successfully but when im running sysrepoctl -l getting the following issue.

**[INF] Libyang internal module "yang" was installed.
[INF] Libyang internal module "ietf-yang-schema-mount" was installed.
[INF] Sysrepo internal module "ietf-datastores" was installed.
[INF] Sysrepo internal module "ietf-netconf-acm" was installed.
[INF] Sysrepo internal module "ietf-factory-default" was installed.
[INF] Sysrepo internal module "sysrepo-factory-default" was installed.
[INF] Sysrepo internal module "ietf-yang-library" was installed.
[INF] Sysrepo internal module "sysrepo-monitoring" was installed.
[INF] Sysrepo internal module "sysrepo-plugind" was installed.
[INF] Sysrepo internal dependency module "ietf-netconf" was installed.
[INF] Sysrepo internal module "ietf-netconf-with-defaults" was installed.
[INF] Sysrepo internal module "ietf-netconf-notifications" was installed.
[INF] Sysrepo internal module "ietf-origin" was installed.
[ERR] Datastore plugin "POSTGRES DS" not found.
sysrepoctl error: Failed to connect (Item not found)**

Can you please let me know how can i debug this issue.
Thanks

**Comment by michalvasko** [comment]
Run `sysrepoctl -L` to print all the usable plugins. If yours is not there, install it using `sysrepoctl -P`.

**Comment by VishalGujela** [comment]
Thanks for you quick support @michalvasko 
im facing the same issue while running the command to list down the supported datastores
sysrepoctl -L -v3
**[INF] Libyang internal module "yang" was installed.
[INF] Libyang internal module "ietf-yang-schema-mount" was installed.
[INF] Sysrepo internal module "ietf-datastores" was installed.
[INF] Sysrepo internal module "ietf-netconf-acm" was installed.
[INF] Sysrepo internal module "ietf-factory-default" was installed.
[INF] Sysrepo internal module "sysrepo-factory-default" was installed.
[INF] Sysrepo internal module "ietf-yang-library" was installed.
[INF] Sysrepo internal module "sysrepo-monitoring" was installed.
[INF] Sysrepo internal module "sysrepo-plugind" was installed.
[INF] Sysrepo internal dependency module "ietf-netconf" was installed.
[INF] Sysrepo internal module "ietf-netconf-with-defaults" was installed.
[INF] Sysrepo internal module "ietf-netconf-notifications" was installed.
[INF] Sysrepo internal module "ietf-origin" was installed.
[ERR] Datastore plugin "POSTGRES DS" not found.**

**Comment by michalvasko** [comment]
I see, how exactly did you get to this situation? Have you installed a module with that plugin before and then reinstalled *sysrepo* or something similar?

**Comment by VishalGujela** [comment]
Actually i have just added a plugin file for postgres with similar support like mongo and redis.
Later after changing few things in cmake i was able to run and build the codebase.
But i exactly don't know what all steps exactly i have to follow to configure sysrepo for extra db support like mongo.

**Comment by michalvasko** [comment]
Do not modify *sysrepo* code or its internal plugins. All you have to do is to compile your plugin as an SO and then install it using the command I mentioned before.

**Comment by VishalGujela** [comment]
Thanks for the support
I have successfully installed the SO.
Now how can i verify or use my plugin can you provide me any link for reference or anything.

**Comment by VishalGujela** [comment]
Hi @michalvasko 
After following your instructions i looked carefully at the build logs i found out 
**-- Looking for dlopen - not found
CMake Warning at CMakeLists.txt:388 (message):
  Function dlopen() is not supported, disabling plugin support and
  'sysrepo-plugind'.**

The libray to support sysrepo plugin is not present but even after installation and setup i cannot find any solution to enable the  plugin.
Full logs are mentioned below:
Thanks 
Vishal
**-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ietf-yang-library revision: 2019-01-04
-- Looking for linux/futex.h
-- Looking for linux/futex.h - found
-- Conditional variable implementation: sr_cond_futex
-- Sysrepo repository: /root/NetconfServer/sysrepo-2.10.1/build/repository
-- Startup data path:  /root/NetconfServer/sysrepo-2.10.1/build/repository/data
-- Factory-default data path: /root/NetconfServer/sysrepo-2.10.1/build/repository/data
-- Notification path:  /root/NetconfServer/sysrepo-2.10.1/build/repository/data/notif
-- YANG module path:   /root/NetconfServer/sysrepo-2.10.1/build/repository/yang
-- SR plugins path:    /usr/local/lib/sysrepo/plugins
-- SRPD plugins path:  /usr/local/lib/sysrepo-plugind/plugins
CMake Warning at CMakeLists.txt:326 (message):
  valgrind executable not found! Disabling memory leaks tests.


-- Found CMocka: /usr/lib/x86_64-linux-gnu/libcmocka.so (Required is at least version "1.0.1") 
-- Could NOT find Uncrustify: Found unsuitable version "0.69.0_f", but required is at least "0.77" (found /usr/bin/uncrustify)
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for pthread_mutex_timedlock
-- Looking for pthread_mutex_timedlock - found
-- Looking for pthread_mutex_clocklock
-- Looking for pthread_mutex_clocklock - found
-- Looking for pthread_rwlock_clockrdlock
-- Looking for pthread_rwlock_clockrdlock - found
-- Looking for pthread_rwlock_clockwrlock
-- Looking for pthread_rwlock_clockwrlock - found
-- Looking for pthread_cond_clockwait
-- Looking for pthread_cond_clockwait - found
-- Looking for CLOCK_MONOTONIC
-- Looking for CLOCK_MONOTONIC - found
-- Looking for vdprintf
-- Looking for vdprintf - found
-- Looking for asprintf
-- Looking for asprintf - found
-- Looking for vasprintf
-- Looking for vasprintf - found
-- Looking for getline
-- Looking for getline - found
-- Looking for strndup
-- Looking for strndup - found
-- Looking for strnstr
-- Looking for strnstr - not found
-- Looking for strdupa
-- Looking for strdupa - found
-- Looking for strchrnul
-- Looking for strchrnul - found
-- Looking for get_current_dir_name
-- Looking for get_current_dir_name - found
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for stdatomic.h
-- Looking for stdatomic.h - found
-- Looking for eaccess
-- Looking for eaccess - found
-- Looking for mkstemps
-- Looking for mkstemps - found
-- Looking for dlopen
-- Looking for dlopen - not found
CMake Warning at CMakeLists.txt:388 (message):
  Function dlopen() is not supported, disabling plugin support and
  'sysrepo-plugind'.


-- Could NOT find mongoc-1.0 (missing: mongoc-1.0_DIR)
-- Datastore plugin ds_mongo not supported.
-- Could NOT find LibHiredis (missing: LIBHIREDIS_LIBRARY LIBHIREDIS_INCLUDE_DIR) (Required is at least version "1.1.0")
-- Datastore plugin ds_redis not supported.
-- Looking for __atomic_fetch_add_4 in atomic
-- Looking for __atomic_fetch_add_4 in atomic - found
-- Found LibYANG: /usr/local/lib/libyang.so (found suitable version "3.2.0", minimum required is "3.1.7") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found LibSystemd: /usr/lib/x86_64-linux-gnu/libsystemd.so  
-- systemd system service unit path: /usr/local/lib/systemd/system
-- Looking for pthread_barrier_init
-- Looking for pthread_barrier_init - found
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.17") found components: doxygen missing components: dot
CMake Warning (dev) at CMakeModules/GenDoc.cmake:10 (message):
  Doxygen: to generate UML diagrams please install graphviz
Call Stack (most recent call first):
  CMakeLists.txt:615 (gen_doc)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /root/NetconfServer/sysrepo-2.10.1/build**

**Comment by michalvasko** [comment]
So what platform are you on, it really does not support `dlopen()` or is there only a problem with the check?

**Comment by VishalGujela** [comment]
Hi @michalvasko 
there was an error with the check but it's enabled now.
1. So, after creating plugin successfully i have tried installing that plugin but not getting anything in List.
2. Iam using the similar structure and approach present in the plugins : **sharing the plugin structure below**
just a snap of my code is shared

**#define plugin_name "POSTGRES DS"
srpds_postgres_access_check(const struct lys_module *mod, sr_datastore_t ds, void *plg_data, int *read, int *write)
{
        pg_plg_conn_data_t *pdata = (pg_plg_conn_data_t *)plg_data;  // Use PostgreSQL structure
        PGconn *conn = NULL;
        sr_error_info_t *err_info = NULL;
        int is_owner = 0, in_group = 0;
        char *username = NULL, *groupname = NULL,
             *owner = NULL, *group = NULL, *mod_ns = NULL;
        mode_t perm = 0;
        PGresult *res = NULL;

        assert(mod);

        // Initialize PostgreSQL connection
        if ((err_info = srpds_data_init(pdata, &conn))) {
                goto cleanup;
        }

        // Get the module namespace
        if ((err_info = srpds_get_mod_ns(ds, mod->name, &mod_ns))) {
                goto cleanup;
        }
        /* learn module access */
        if ((err_info = srpds_get_access(conn, mod_ns, &owner, &group, &perm))) {
                goto cleanup;
        }
        // Get access control data (owner, group, permissions) from PostgreSQL
        //res = PQexecParams(conn,
        //              "SELECT owner, group_name, permissions FROM module_access WHERE module_namespace = $1",
        //              1, NULL, (const char *const[]){mod_ns}, NULL, NULL, 0);

        // Check for query errors
        //if (PQresultStatus(res) != PGRES_TUPLES_OK) {
        //      ERRINFO(&err_info, SR_ERR_OPERATION_FAILED, "Getting module access data", PQerrorMessage(conn));
        //      goto cleanup;
        //}

        // Check if the query returned a result
        //if (PQntuples(res) > 0) {
        //      owner = strdup(PQgetvalue(res, 0, 0));  // Owner
        //      group = strdup(PQgetvalue(res, 0, 1));  // Group
        //      perm = (mode_t)atoi(PQgetvalue(res, 0, 2));  // Permissions
        //} else {
        // Handle case where module access data is not found 
        //      err_info = sr_errinfo_new(SR_ERR_NOT_FOUND, "Module access data not found.");
        //      goto cleanup;
        //}

        // Learn the current process username
        if ((err_info = srpds_uid2usr(getuid(), &username))) {
                goto cleanup;
        }

        // Learn the current process groupname
        if ((err_info = srpds_gid2grp(getgid(), &groupname))) {
                goto cleanup;
        }

        // Check whether the current user is the owner of the module and whether the user is in the same group
        is_owner = !strcmp(owner ? owner : "", username);
        in_group = !strcmp(group ? group : "", groupname);

        if (read) {
                // Clear read flag
                *read = 0;

                // Grant read privilege based on ownership
                if (is_owner && (perm & S_IRUSR)) {
                        *read = 1;
                }

                // Grant read privilege based on group
                if (in_group && (perm & S_IRGRP)) {
                        *read = 1;
                }

                // Grant read privilege for others
                if (!is_owner && !in_group && (perm & S_IROTH)) {
                        *read = 1;
                }
        }

        if (write) {
                // Clear write flag
                *write = 0;

                // Grant write privilege based on ownership
                if (is_owner && (perm & S_IWUSR)) {
                        *write = 1;
                }

                // Grant write privilege based on group
                if (in_group && (perm & S_IWGRP)) {
                        *write = 1;
                }

                // Grant write privilege for others
                if (!is_owner && !in_group && (perm & S_IWOTH)) {
                        *write = 1;
                }
        }

cleanup:
        free(username);
        free(groupname);
        free(owner);
        free(group);
        free(mod_ns);
        PQclear(res);  // Clear PostgreSQL result object
        return err_info;
}
const struct srplg_ds_s srpds_postgres = {
        .name = plugin_name,
        .install_cb = srpds_postgres_install,
        .uninstall_cb = srpds_postgres_uninstall,
        .init_cb = srpds_postgres_init,
        .conn_init_cb = srpds_postgres_conn_init,
        .conn_destroy_cb = srpds_postgres_conn_destroy,
        .store_cb = srpds_postgres_store,
        .recover_cb = srpds_postgres_recover,
        .load_cb = srpds_postgres_load,
        .copy_cb = srpds_postgres_copy,
        .candidate_modified_cb = srpds_postgres_candidate_modified,
        .candidate_reset_cb = srpds_postgres_candidate_reset,
        .access_set_cb = srpds_postgres_access_set,
        .access_get_cb = srpds_postgres_access_get,
        .access_check_cb = srpds_postgres_access_check,
        .last_modif_cb = srpds_postgres_last_modif,
        .data_version_cb = NULL,
};**


**root@vm88-04:~/NetconfServer/sysrepo-2.10.1# sysrepoctl -P src/plugins/libds_postgres.so 
root@vm88-04:~/NetconfServer/sysrepo-2.10.1# sysrepoctl -L
Datastore plugins:
        JSON DS file
        JSON DS file

Notification plugins:
        JSON notif
        JSON notif**

**Comment by michalvasko** [comment]
Try running `sysrepoctl -L -v3` instead, it should tell you why your plugin failed to load. But my guess is that you are missing the API version in the plugin, you are supposed to write
```C
SRPLG_DATASTORE = { ...
```
instead of
```C
const struct srplg_ds_s srpds_postgres = { ...
```
It is defined in `sysrepo/plugins_datastore.h`.

**Comment by VishalGujela** [comment]
1.I have tried running with -v3 option and im getting this output:

**sysrepoctl -L -v3
[INF] File "sysrepo@2023-06-16.yang" was installed.
[INF] File "ietf-datastores@2018-02-14.yang" was installed.
[INF] Libyang internal module "yang" was installed.
[INF] Libyang internal module "ietf-yang-schema-mount" was installed.
[INF] Sysrepo internal module "ietf-datastores" was installed.
[INF] Sysrepo internal module "ietf-netconf-acm" was installed.
[INF] Sysrepo internal module "ietf-factory-default" was installed.
[INF] Sysrepo internal module "sysrepo-factory-default" was installed.
[INF] Sysrepo internal module "ietf-yang-library" was installed.
[INF] Sysrepo internal module "sysrepo-monitoring" was installed.
[INF] Sysrepo internal module "sysrepo-plugind" was installed.
[INF] Sysrepo internal dependency module "ietf-netconf" was installed.
[INF] Sysrepo internal module "ietf-netconf-with-defaults" was installed.
[INF] Sysrepo internal module "ietf-netconf-notifications" was installed.
[INF] Sysrepo internal module "ietf-origin" was installed.
[INF] File "ietf-yang-schema-mount@2019-01-14.yang" was installed.
[INF] File "ietf-netconf-acm@2018-02-14.yang" was installed.
[INF] File "ietf-factory-default@2020-08-31.yang" was installed.
[INF] File "sysrepo-factory-default@2024-05-02.yang" was installed.
[INF] File "ietf-yang-library@2019-01-04.yang" was installed.
[INF] File "sysrepo-monitoring@2023-08-11.yang" was installed.
[INF] File "sysrepo-plugind@2022-08-26.yang" was installed.
[INF] File "ietf-netconf@2013-09-29.yang" was installed.
[INF] File "ietf-netconf-with-defaults@2011-06-01.yang" was installed.
[INF] File "ietf-netconf-notifications@2012-02-06.yang" was installed.
[INF] File "ietf-origin@2018-02-14.yang" was installed.
[INF] Datastore copied from <startup> to <running>.
[INF] Connection 1 created.
Datastore plugins:
        JSON DS file
        JSON DS file

Notification plugins:
        JSON notif
        JSON notif
root@vm88-04:~/NetconfServer/sysrepo-2.10.1/build# sysrepoctl -P ../src/plugins/libds_postgres.so 
root@vm88-04:~/NetconfServer/sysrepo-2.10.1/build# sysrepoctl -P ../src/plugins/libds_postgres.so -v3
root@vm88-04:~/NetconfServer/sysrepo-2.10.1/build# sysrepoctl -L -v3
[INF] Connection 2 created.
Datastore plugins:
        JSON DS file
        JSON DS file

Notification plugins:
        JSON notif
        JSON notif**

2. Also i have changed the structure with 
uint32_t srpds_apiver__ = SRPLG_DS_API_VERSION;
    const volatile struct srplg_ds_s srpds__ = {
        plugin_name,
        srpds_postgres_install,
        srpds_postgres_uninstall,
        srpds_postgres_init,
        srpds_postgres_conn_init,
        srpds_postgres_conn_destroy,
        srpds_postgres_store,
        srpds_postgres_recover,
        srpds_postgres_load,
        srpds_postgres_copy,
        srpds_postgres_candidate_modified,
        srpds_postgres_candidate_reset,
        srpds_postgres_access_set,
        srpds_postgres_access_get,
        srpds_postgres_access_check,
        srpds_postgres_last_modif,
        NULL,
};

**Comment by VishalGujela** [comment]
Hi @michalvasko 
Thank you so much for your support on latest version things are working fine but on the version i was using earlier 2.10.1 the db_plugin was not working.
Thanks 
Vishal
