### ISSUE TITLE
The callback of `subscribe_oper_data_request` is not being triggered.

### ISSUE THREAD

**Issue by zhenyunxie** [sysrepo/sysrepo#3437]
We found an unexpected behaviour in our implementation of netconf agent through using sysrepo, where the callback of `subscribe_oper_data_request`(`sr_oper_get_subscribe`) is **NOT** being invoked unless `sr_module_change_subscribe` is also used.

As a workaround, we need a subscription (even if dummy) to module change for the above subscription of operational data requests to work. **Is this a bug or a feature?**

The mentioned behavior can be reproduced by following snippet:

### yang model:

```
module mymod {
    yang-version "1.1";

    namespace "urn:mymod";

    prefix "mymod";

    list mylist {
        key mykey;
        leaf mykey {
            type string;
        }
        leaf myleaf {
            config false;
            type string;
        }
    }
}
```
### snippet

```
import signal
import sysrepo

def cb1(xpath, private_data) -> None:
    print("cb1")

def cb2(event, req_id, changes, private_data) -> None:
    return

def main() -> None:
    with sysrepo.SysrepoConnection() as conn, conn.start_session() as session:
        session.set_item(xpath="/mymod:mylist[mykey='k1']")
        session.validate()
        session.apply_changes()

        session.subscribe_oper_data_request("mymod", "/mymod:mylist/myleaf", cb1)

        session.subscribe_module_change("mymod", None, cb2)  # if commented out, cb1 is never called!

        signal.sigwait({signal.SIGINT, signal.SIGTERM})

if __name__ == "__main__":
    main()
```

##### 1. Active the netconf client and netconf server:

_output in netconf server:_

```
netconf-server  | --- [SYSREPO] install yang module including initial datastore...
netconf-server  | --- [NETOPEER2] starting netopeer2-server...
netconf-server  | --- [DEMO] starting application
```

##### 2. Get info of leaf node `myleaf` :

_output in netconf client:_

```
root@nc-client:/#  netconf-console2 --host netconf-server --port 830 --user=root --password=root --get -x "/mylist/myleaf"
<?xml version='1.0' encoding='UTF-8'?>
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"/>
```

_output in netconf server (empty, the callback is NOT triggered):_

```
netconf-server  | --- [SYSREPO] install yang module including initial datastore...
netconf-server  | --- [NETOPEER2] starting netopeer2-server...
netconf-server  | --- [DEMO] starting application
```

##### 1. Active the netconf client and netconf server:

_output in netconf server:_

```
netconf-server  | --- [SYSREPO] install yang module including initial datastore...
netconf-server  | --- [NETOPEER2] starting netopeer2-server...
netconf-server  | --- [DEMO] starting application
```

##### 2. Get info of data node `myleaf` :

_output in netconf client:_

```
root@nc-client:/#  netconf-console2 --host netconf-server --port 830 --user=root --password=root --get -x "/mylist/myleaf"
<?xml version='1.0' encoding='UTF-8'?>
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"/>
```

_output in netconf server (the callback is triggered):_

```
netconf-server  | --- [SYSREPO] install yang module including initial datastore...
netconf-server  | --- [NETOPEER2] starting netopeer2-server...
netconf-server  | --- [DEMO] starting application
netconf-server  | cb1
```

**Comment by michalvasko** [comment]
What *sysrepo* version are you using? I could not really reproduce this and I never managed to trigger the callback, which is what I would expect. The leaf `myleaf` can never exist if there are no `mylist` instances (explained in the [docs](https://netopeer.liberouter.org/doc/sysrepo/devel/html/subs.html#oper_subs)).

**Comment by cpascual** [comment]
@michalvasko Thanks for such prompt response!

AFAICT, there *is* an instance of mylist, created by the following line: 
`session.set_item(xpath="/mymod:mylist[mykey='k1']")`

**Comment by michalvasko** [comment]
Right, missed that, sorry about that. Then it makes sense, when you subscribe to the module, all the configuration data (in `running` DS) are also present in the `operational` DS meaning the leaf gets its parent. It should all be explained in the page I referenced before.

**Comment by cpascual** [comment]
Hi @michalvasko  thanks again for replying so fast.

Let's see if we got it right ( full disclosure: @zhenyunxie  and me work together)  ...


> when you subscribe to the module, all the configuration data (in running DS) are also present in the operational DS meaning the leaf gets its parent

Does this imply that before we subscribe to model data changes the `/mymod:mylist[mykey='k1']` instance is only available in the running DS and that by subscribing to the data model changes we are causing it to be copied to the operational DS (and therefore enabling the callbacks on `/mymod:mylist[mykey='k1']/myleaf`)?

If so, my question is: is there some better way (using sysrepo-python) to cause a similar copy that does not imply us doing a subscription that we do not need?

Note: in our real case we are dynamically populating  `/mymod:mylist` with instances *only at the beginning of the application*... so once they are created, the instances of `mylist` are "static" and only their leafs may be updated

Thanks your patience... we already had studied the docs as best as we could before asking here, but the implications of subscribing to model changes and having the data in the operational DS were not clear to us...

**Comment by michalvasko** [comment]
Okay, [here](https://netopeer.liberouter.org/doc/sysrepo/devel/html/index.html#oper_ds) it is clearly specified how the `operational` DS is populated. Meaning there are 3 ways data can appear in the `operational`:
- subscribed `running` data
- pull oper subscriptions
- push oper data

Based on what you said, you should be able to use push oper data and just store the list instances once.

The general idea is that only data "in-use" are show in the operational DS, hence their visibility if they are subscribed-to running data. So I am not sure what your use-case exactly is since you configure the data in running but are not even interested in them (no subscription). It would then seem they are not configuration data (they are not configuring anything) and you do not even have to set them in running at all and use just operational DS.

**Comment by cpascual** [comment]
Thanks a lot for the explanations and the pointers to the specific parts of the docs. It is much clearer now.

In our case we were just doing some quick test and were surprised about not getting the callback called, but in proper operation we will probably want to use the pull method on the leaf and therefore we should not have this problem.

Thanks again!
