### ISSUE TITLE
Waiting on a conditional variable failed (sr_shmext_notif_sub_add: Connection timed out)

### ISSUE THREAD

**Issue by hi-Mr-ye** [sysrepo/sysrepo#3440]
Hi
I found that an error message was printed while using the netopeer2-cli tool:
         
![image](https://github.com/user-attachments/assets/46efc572-faa5-4237-b8ad-b27a1b4232f3)

At the same time, the connection to Netopeer2 server was disconnected. When reconnecting to Netopeer2 server later, it was found that the connection could not be successful, and every time connecting to Netopeer2 server, [ERR] was printed: SR: Waiting on a conditional variable failed (sr_sthmext_notif_subadd: Connection timed out)
Run netopeer2 server again later to successfully connect again.
Why ? and Can we solve this problem without restarting the netopeer2 server program?

**Comment by michalvasko** [comment]
Seems like some synchronization issue. Please update your *netopeer2* version, it is likely to solve such issues. If you are already using a recent version, I would need much more information to ideally reproduce it or even attempt to fix it.

**Comment by hi-Mr-ye** [comment]
May I ask what is the latest version of Netopeer2?
May I ask what content is being synchronized？
> Seems like some synchronization issue
The following is the operating environment at that time：
1.Two hosts are running the netopeer2 server program separately (the program is the same).Assuming host 1 has an IP address of 16.5 and host 2 has no IP address.
2.Connect to host 1 using the netopeer2-cli tool and disconnect the network of host 1 during normal operation. Then, host 2's IP will automatically change to 16.5
3.Using netopeer2-cli to connect to host 2, the error message above appears
Will this environment affect synchronization？

**Comment by michalvasko** [comment]
The latest version is the latest github [release](https://github.com/CESNET/netopeer2/releases).

I do not understand your setup at all, why are their IP addresses being changed? I do not think you can expect *netopeer2* to continue listening after your IP address changes. But also, if you have 2 separate systems, they should not affect each other, the error is a *sysrepo* one, which runs only locally.

**Comment by hi-Mr-ye** [comment]
Thank you for your answer.
May I ask how long it takes for Netopeer2 server to clear disconnected or invalid sessions? Can the clearing time be set?

**Comment by michalvasko** [comment]
It polls all the sessions constantly (depends on the number of threads but in the default setup it does) so as soon as a session is invalid, it is freed, there is nothing to wait for.
