### ISSUE TITLE
Unexpected behavior of "remove" operation on list nodes, resulting in entire list removal instead of specific entry

### ISSUE THREAD

**Issue by pedrothaines** [sysrepo/sysrepo#3441]
**Disclaimer:** I'm using the latest tagged versions of all libraries (libnetconf2, libyang, sysrepo and netopeer2).

**Question:** is it expected behavior for sysrepo to remove an entire list when the _remove_ operation is specified within the list's parent tag, **even if a specific list entry key is provided**?

For example, consider the following data in the current _running_ datastore (where `<Name>` is the list key):
```xml
<top xmlns="http://www.test.com/netconf/config:1.0">
  <WLANClient>
    <ServiceTemplates>
      <Template>
        <Name>1</Name>
        <SSID>test1</SSID>
      </Template>
      <Template>
        <Name>2</Name>
        <SSID>test2</SSID>
      </Template>
    </ServiceTemplates>
  </WLANClient>
</top>
```

When a NETCONF `<edit-config>` RPC arrives with the following payload, sysrepo removes the entire `<ServiceTemplates>` list rather than just the `<Template>` entry with `<Name>` key `2`:

```xml
<edit-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"
    xmlns:web="urn:ietf:params:xml:ns:netconf:base:1.0">
    <target>
        <running />
    </target>
    <error-option>rollback-on-error</error-option>
    <config>
        <top xmlns="http://www.test.com/netconf/config:1.0">
            <WLANClient>
                <ServiceTemplates web:operation="remove">
                    <Template>
                        <Name>2</Name>
                    </Template>
                </ServiceTemplates>
            </WLANClient>
        </top>
    </config>
</edit-config>
```

**Comment by michalvasko** [comment]
If you want to remove a specific `Template` list entry, this is the correct XML:
```
        <top xmlns="http://www.test.com/netconf/config:1.0">
            <WLANClient>
                <ServiceTemplates>
                    <Template web:operation="remove">
                        <Name>2</Name>
                    </Template>
                </ServiceTemplates>
            </WLANClient>
        </top>
```
The element with the attribute is always removed with **all of its descendants**.

**Comment by pedrothaines** [comment]
So it is sysrepo expected behavior as of today.

@michalvasko, that is exactly what I had to do: move the _remove_ operation to the specific list element that I needed to remove. I ended up implementing a "middleware" in front of `netopeer2` so that we can manipulate the incoming RPC to deal with such behavior "incompatibilities".

Just to give you more context: we are integrating our devices with a NETCONF client (NMS) that we do not control. This NETCONF client sends the RPC the way I mentioned in the original question:

```xml
<edit-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"
    xmlns:web="urn:ietf:params:xml:ns:netconf:base:1.0">
    <target>
        <running />
    </target>
    <error-option>rollback-on-error</error-option>
    <config>
        <top xmlns="http://www.test.com/netconf/config:1.0">
            <WLANClient>
                <ServiceTemplates web:operation="remove">
                    <Template>
                        <Name>2</Name>
                    </Template>
                </ServiceTemplates>
            </WLANClient>
        </top>
    </config>
</edit-config>
```

Are there plans to support such removal of list entry using this method?

I did not check if there is anything related to such behavior in any RFC related to NETCONF yet.
