### ISSUE TITLE
Error: Module "sysrepo-factory-default@2023-02-23" is already implemented in revision "2024-05-02" after updating

### ISSUE THREAD

**Issue by qupfer** [sysrepo/sysrepo#3447]
Hi,

I want to upgrade sysrepo (and libyang/netopeer....). 
I use the included apkg tool to create RPMs and install them. 

After that, I got the following error:

```
[admin@sysrepo-test ~]$ sudo sysrepoctl -l -v4
[DBG] #SHM before (adding rpc sub)
[DBG] #SHM:
000000-000008 [     8]: ext structure

[DBG] #SHM after (adding rpc sub)
[DBG] #SHM:
000000-000008 [     8]: ext structure
000008-000048 [    40]: rpc subs (1, path "/ietf-factory-default:factory-reset")
000048-000088 [    40]: rpc sub xpath ("/ietf-factory-default:factory-reset", path "/ietf-factory-default:factory-reset")

[ERR] Module "sysrepo-factory-default@2023-02-23" is already implemented in revision "2024-05-02".
sysrepoctl error: Failed to connect (libyang error)
```

I could not even "uninstall" the module, as the command fails with the same error.
Obviously its related "sysrepo-factory-default" and the newer revision. 

Any Ideas how to fix that or how to update "correct".

**Comment by michalvasko** [comment]
The development of *sysrepo* and the related projects is fairly active and so an update is not always possible. If you reset the whole *sysrepo* repository (you will lose all the data and installed YANG modules) using `make sr_clean` in *sysrepo* `build` dir, installing the new version should succeed.
