### ISSUE TITLE
Undesired default values in factory default datastore

### ISSUE THREAD

**Issue by rbu9fe** [sysrepo/sysrepo#3453]
When installing a Yang module without initial (i.e. factory default) data then the factory-default (and thus also the initial startup) datastore is empty:
- `sysrepoctl -i ietf-interfaces@2018-02-20.yang`
- `cat /etc/sysrepo/data/ietf-interfaces.factory-default`
  ```json
  {
      "ietf-interfaces:interfaces":{   
      }
  }
  ```

However, when the Yang module is installed with some initial data, then the factory-default datastore also holds default values:
- Default data: `cat ietf-interfaces.json`
   ```json
   {
       "ietf-interfaces:interfaces":{
           "interface":[
               {
                   "name":"eno0",
                   "type":"iana-if-type:ethernetCsmacd"
               }
           ]
       }
   }
   ```
- `sysrepoctl -i ietf-interfaces@2018-02-20.yang -I ietf-interfaces.json`
- `cat /etc/sysrepo/data/ietf-interfaces.factory-default`
  ```json
  {
      "ietf-interfaces:interfaces":{
          "interface":[
              {
                  "name":"eno0",
                  "type":"iana-if-type:ethernetCsmacd",
                  "enabled":true,
                  "@enabled":{
                      "ietf-netconf-with-defaults:default":true
                  }
              }
          ]
      }
  }
  ```

First of all, why is the default data added to the datastore? Imo there's no loss of functionality when that is not stored therein.

In our use case this imposes a problem in the following scenario:
1. For a new firmware version augment an existing Yang model by a new leaf that defines a default value.
2. The (old and new) firmware installs that Yang model with some initial data not referring the augmented leaf above.
3. Delete the startup datastore => Now it will contain the default value of the new augmented leaf.
4. Now a downdate to the old firmware doesn't work anymore as the startup datastore contains unknown data.

Of course, the same error happens when the new leaf is actively written to the startup datastore (no matter whether it defines a default value), however, here it's part of startup already even when we don't actively store it therein.

**Comment by michalvasko** [comment]
Default nodes are stored so that the data do not have to be validated after being parsed. But could you please provide all the YANG modules, data, and the steps to reproduce this? When changing the YANG context, *sysrepo* should adjust all the stored data so that they do not contain unknown nodes.

**Comment by rbu9fe** [comment]
Thanks for your reply. I think all you need to reproduce that is already there, except the Yang model, which is [here](https://github.com/sysrepo/sysrepo/blob/a6f309eb9601b9ef28e95a74655d7e9eac3dcc7a/modules/subscribed_notifications/ietf-interfaces%402018-02-20.yang). With that you should be able to reproduce it by:
1. Prepare a file `ietf-interfaces.json` with the contents given above under `cat ietf-interfaces.json`.
2. Install the Yang model by `sysrepoctl -i ietf-interfaces@2018-02-20.yang -I ietf-interfaces.json`.
3. Check the contents of the resulting factory default datastore.

Please let me know when something is missing.

**Comment by rbu9fe** [comment]
The factory default datastore is only there to serve as initialization for the startup datastore. When there is no factory default and I write data to the startup then there are no default values but just the data I write is stored. Therefore, I thought the default values in the factory default datastore have no practical use and in our use case they prevent reverting to an old firmware (Yang context) while keeping the current startup datastore (based on the new factory default). Looks like that assumption was wrong so we have to deal with migration of startup datastores into different Yang contexts.

**Comment by michalvasko** [comment]
Your issue has nothing to do with default values, they are irrelevant. If they did not happen to be default values but explicit nodes that you set, you would get the same problem. You knowing not to set the values (or in this case not wanting the default values to be stored) is just a hack and it cannot influence how *sysrepo* works in general. But the same data are stored in `startup` as in `factory-default` so you should have the same problem in both datastores.

Also, like I said, when changing the context, the most basic data migration should be performed that just discards any nodes that are unknown in the new context (were removed). If you require anything more complex, you have to implement it yourself.

**Comment by rbu9fe** [comment]
Yes we'll have the same issue when we actually use the new Yang leaf but so war it was only defined and not used yet so we didn't expect it to be part of the startup datastore. And currently we don't import the startup datastore into a new Yang context, instead, we simply replace the startup file and reboot the device (as a reboot is required anyway). Instead, we should use some import/migration mechanism that we'll need anyway.
