### ISSUE TITLE
RPC Subscription already exists

### ISSUE THREAD

**Issue by small13999** [sysrepo/sysrepo#3463]
Hi,
I am developing a plugin using the sysrepo-netopeer2 docker image. I successfully installed the following yang module with sysrepoctl -i custom-ping.yang(uploaded as txt because of Github):
[custom-ping.txt](https://github.com/user-attachments/files/17946655/custom-ping.txt)

In the plugin init function, I am trying to subscribe to changes in ping-operations and to RPCs to execute-ping:
```c
    // register ping config handler
    rc = sr_module_change_subscribe(session, "custom-ping", "/custom-ping:ping-operations", ping_operations_change_cb, NULL, 0, SR_SUBSCR_DEFAULT, &subscription);
    if (rc != SR_ERR_OK)
    {
        printf("Failed to subscribe to ping change: %s\n", sr_strerror(rc));
        goto error;
    }

    // register execute ping RPC handler
    rc = sr_rpc_subscribe(session, "/custom-ping:execute-ping", execute_ping_cb, NULL, 0, 0, &subscription);
    if (rc != SR_ERR_OK)
    {
        printf("Failed to subscribe to ping RPC: %s\n", sr_strerror(rc));
        goto error;
    }
```

The callback functions:
```c
int ping_operations_change_cb(sr_session_ctx_t *session, uint32_t sub_id,
                              const char *module_name, const char *xpath,
                              sr_event_t event, uint32_t request_id, void *private_data)
{
    printf("In ping operations change cb!\n");
    return SR_ERR_OK;
}

int execute_ping_cb(sr_session_ctx_t *session, uint32_t sub_id,
                    const char *xpath, const sr_val_t *input,
                    const size_t input_cnt, sr_event_t event,
                    uint32_t request_id, sr_val_t **output,
                    size_t *output_cnt, void *private_data)
{
    printf("Executing ping!\n");
    return SR_ERR_OK;
}
```
The first subscription works properly, the callback is called when i send an edit-config message to ping-operations.
But the second subscription fails at the init stage:
**[ERR] RPC subscription for "/custom-ping:execute-ping" with priority 0 already exists.
Failed to subscribe to ping RPC: Invalid argument
[ERR] RPC subscription for "/custom-ping:execute-ping" with priority 10000 already exists.
Failed to subscribe to ping RPC: Invalid argument**

I tried with different priorities, and got the same error for all of them: subscription already exists. I am not subscribing to it anywhere else. Every time I change the plugin, I restart the container, so there shouldn't be any leftover subscriptions either. The issue shouldn't be in the rest of the code either, I already created multiple subscriptions to the ietf-interfaces module, all of which work properly.

I tried looking for similar issues, and looked at the documentation, but I couldn't find what I am doing wrong.

Thanks in advance!

**Comment by michalvasko** [comment]
I do not think there is a problem in *sysrepo*. My guess would be that the function that is subscribing is called twice or something like that. I have no other ideas or advice.

**Comment by michalvasko** [comment]
They allow multiple subscriptions with the same priority which are executed in parallel.
