### ISSUE TITLE
Some questions about the sr_notif_send function

### ISSUE THREAD

**Issue by hi-Mr-ye** [sysrepo/sysrepo#3477]
Hi
I have written a program that uses the sr_notif_send function to test subscription functionality.
The program code is in the test.zip file
[test.zip](https://github.com/user-attachments/files/18106142/test.zip)
Execute Command: ./send_notification_alarm 1000 and  while true; do date && ps aux | grep send_notification_alarm | grep 1000; echo ""; sleep 1; done
The RSS value of the process is continuously increasing:
![xuanxuan-image](https://github.com/user-attachments/assets/f46945f2-0932-4ca0-8908-7df6285dcf53)
Is this situation normal?
Thanks.

**Comment by michalvasko** [comment]
Only marginally and I would blame the system and some optimizations. In any case, I have no explanation for it.

**Comment by hi-Mr-ye** [comment]
Thank you for your answer.
In the same system, I repeated the above operation using the sr_notif_send_tree function and found that the RSS column values did not continue to increase.
Is there any difference between the sr_notif_send_tree function and the sr_notif_send function?

**Comment by michalvasko** [comment]
> Is there any difference between the sr_notif_send_tree function and the sr_notif_send function?

Well, one uses the `sr_val_t` API, the other the *libyang* API, nothing else.
