### ISSUE TITLE
Using the same sysrepo from several services (processes) - is this allowed?

### ISSUE THREAD

**Issue by RodionGork** [sysrepo/sysrepo#3479]
Hi Friends! 

This is not an issue, rather just clarification to documentation - could you please explain if this is allowed/valid to use single sysrepo storage by several services.

E.g. the project has a storage for configuration and say some tool uses sysrepo as a library linked into executable to access this storage and update configs - and at the same time another service uses netopeer2 to access the same storage (not limited to reading operations). There could be also other services with sysrepo in linked-into form accessing the same data. 

I'm a bit confused whether such usage handles any callbacks set in these services consistently etc.

Thanks in advance for any hints!

**Comment by RodionGork** [comment]
> Actually this is the preferred and expected usage.

just to re-check - we speak about accessing same data, not several unrelated config stored in one sysrepo - still reading-writing them from multiple services is ok, right?

if it's so, thanks, it's ok to close this ticket

**Comment by michalvasko** [comment]
Yes, it is all synchronized.
