### ISSUE TITLE
Does sysrepo support asynchronous operational data?

### ISSUE THREAD

**Issue by trentzhou** [sysrepo/sysrepo#3481]
I am using `sr_oper_get_subscribe` to register a callback for operational data. Some information will be returned through an RPC to another process, and it may take a few seconds.

I have two questions.

1. In my callback, if the code blocks and waits for the response, does it block netopeer2 for all other operational data requests?
2. Is it possible to return something similar to a future/promise?

**Comment by michalvasko** [comment]
1. No, but some locks may be held that can potentially block other requests.
2. Look into the [docs](https://netopeer.liberouter.org/doc/sysrepo/devel/html/subs.html) and read more about `SR_ERR_CALLBACK_SHELVE` to understand it properly. But it allows exactly that, interrupt callback processing to get back to it later.

**Comment by trentzhou** [comment]
Thanks @michalvasko. I checked the document and source code of sysrepo. In function `sr_shmsub_oper_get_listen_process_module_events`, when the callback returns SR_ERR_CALLBACK_SHELVE, the event is simply skipped.
In my understanding, the current behavior looks like this:

1. User sends a netconf `<get>` to netopeer2.
2. Netopeer2 sends an event to my app to request the operational data.
3. My app returns `SR_ERR_CALLBACK_SHELVE` to indicate it's busy.
4. What does netopeer2 do? Does it send the event again? Or does it simply return timeout?

I still feel confused. How does the application return data when the data is ready?

**Comment by michalvasko** [comment]
I thought it is all explained in the docs, did you even read them?

> On the events update and change, the callback can return a special [SR_ERR_CALLBACK_SHELVE](https://netopeer.liberouter.org/doc/sysrepo/devel/html/group__log__api.html#gga3541b16be4e12bd061b7e24d4be29c30aa297b02a06472aa8df2e971b9b1c77fe) value. This causes the event not to be processed and simply skipped (shelved). When all the events on the subscription are processed next time, this subscription callback with the same event is called again. This special return value can be returned several times but be careful for the timeout not to elapse! Typically, this whole mechanism is used only when the events are handled by the application, not by a Sysrepo thread ([SR_SUBSCR_NO_THREAD](https://netopeer.liberouter.org/doc/sysrepo/devel/html/group__subs__api.html#ggaa629478596b1e246553eac91a74b2b5ba950de919456aa8d277b9dd6d465ad2e0)). Otherwise the application does not have full control over calling the event processing function [sr_subscription_process_events()](https://netopeer.liberouter.org/doc/sysrepo/devel/html/group__subs__api.html#ga2345e433621ad3b9a8212fbbfc86dbc5) (strictly speaking, it can be called directly even if Sysrepo thread is handling this subscription, but there is likely no use-case).

For your other question
> I have another question: If my app returns SR_ERR_CALLBACK_SHELVE for one slow oper-get event, can other oper-get events be processed? I guess the answer is no because all events are waiting in the queue.

It all depends on the scenario. If one `<get>` request needs data from several subscribers, it naturally does not matter if there are some fast oper-get subscriptions, the reply cannot be sent back until all the oper-get subscriptions return their data.

**Comment by trentzhou** [comment]
Thanks. I think now I understand how `SR_ERR_CALLBACK_SHELVE` works. It does not meet my requirements.

For example, I have two netconf sessions.

Session A calls `get /status/firewall/stats`. This is a slow operation which may take a few seconds. The results is collected by a background task.
Session B calls `get /status/uptime`. This is a very quick operation which could be handled immediately.

Both xpaths are handled by the same subscription. While session A is waiting for the response, session B cannot be handled. Even if I use `SR_ERR_CALLBACK_SHELVE`, the two requests cannot interleave.

How can I make the two sessions work concurrently?

**Comment by michalvasko** [comment]
> Both xpaths are handled by the same subscription.

There is your problem, create separate subscriptions with individual threads for each subtree and then you should be fine.

**Comment by trentzhou** [comment]
@michalvasko Thank you for your response. This question can be closed.
