### ISSUE TITLE
Option for parallel processing of sysrepo notifications

### ISSUE THREAD

**Issue by darren-west** [sysrepo/sysrepo#349]
I want to have a callback that can spawn a new thread and do some operation. I am trying to do this with a subscription to a subtree change. I want to get the changes iterator on the new thread and do something. Unfortunately once the callback completes the commit notification is fired and the data session is closed which means i can no longer get an iterator. 

This is an issue as the event library will not call the next callback until the current callback has returned. If you do a long running progress all the callbacks get blocked.

**Comment by rastislavszabo** [comment]
Hi,
yes, currently all callbacks within a process are processed serially. This is desirable for most controlled applications which are updating their global context. The drawback is performance drop for operations that can be processed in parallel, mostly affecting sysrepo plugins.

A solution would be a new option for subscriptions, e.g. 'SR_SUBSCR_SPAWNED' which would spawn a new thread for the callback. Question is, whether it should be spawned for verify, apply, or both callback events?

Tracking this as an enhancement.

**Comment by michalvasko** [comment]
Commit should be processed serially, there are many threading options now that must be sufficient.
