### ISSUE TITLE
Out-of-source build touched files in the CMAKE_CURRENT_SOURCE_DIR

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#352]
When using CMake's out-of-tree builds (something like ``mkdir build; cd build; cmake ..``), some files within the top-level checkout are still created. One example is ``../src/common/sysrepo.pb-c.h`` (and in addition, a non-parallel ``ninja`` build fails due to a missing dependency; this is masked on my system by the build system defaulting to ``-j4``).

**Comment by milanlenco** [comment]
Fixed in devel branch. Will be merged to master already tomorrow as a part of the upcoming release.
Thanks for reporting!
