### ISSUE TITLE
Any plans to move to proto3 that describes complete set of APIs on the client library proto ?

### ISSUE THREAD

**Issue by ramukima** [sysrepo/sysrepo#360]
It would be good to specify the API contracts in the proto files, so that clients can use basic code generation techniques for client applications.

**Comment by rastislavszabo** [comment]
Sysrepo exposes full API via this proto file: https://github.com/sysrepo/sysrepo/blob/master/src/sysrepo.proto

It is proto2 - not proto3, since protobuf-c library does not support proto3 yet.
