### ISSUE TITLE
Subtree filtering option in sysrepocfg

### ISSUE THREAD

**Issue by fabioantonini** [sysrepo/sysrepo#378]
It would be nice to add --subtree=<sub tree name> to the sysrepocfg options
for example it should be possible to run the following command to export just one section of a wider configuration file

sysrepocfg --export --format=json --datastore=running --subtree=mickeymouse disney 

It would be a nice enhancement useful when there is a main yang file augmented by sibling yang files
thanks a lot
fabio

**Comment by fabioantonini** [comment]
Hi all
I have enhanced 'sysrepocfg' with a set of a new options to handle the import/export/cancel of XPATHs.
The new command sintax is the following:
**set**
`sysrepocfg -s "XPATH" -w "value-to-be-set"`
**get**
`sysrepocfg -g "XPATH" `
**remove**
`sysrepocfg -r "XPATH" `

Some examples:
A list entry creation
`sysrepocfg  --datastore=running -s "/tiesse-ethernet:ethernet/interfaces[name='eth0']"`

Some leaf setting
`sysrepocfg  --datastore=running -s "/tiesse-ethernet:ethernet/interfaces[name='eth0']/ipaddr" -w 1.1.1.8`
`sysrepocfg  --datastore=running -s "/tiesse-ethernet:ethernet/interfaces[name='eth0']/arp-timeout" -w 12`
`sysrepocfg -d running -s "/tiesse-dhcp-server:dhcp-server/server[name='eth0']/hostname" -w mickey`

A new leaf-list creation
`sysrepocfg -d running -s "/tiesse-dhcp-server:dhcp-server/server[name='fabio']timesrv" -w 7.8.9.2`
`sysrepocfg -d running -s "/tiesse-dhcp-server:dhcp-server/server[name='michal']/timesrv[.='1.2.3.5']"`

Let's remove a single leaf
`sysrepocfg -d running -r "/tiesse-dhcp-server:dhcp-server/server[name='pippo']/hostname"`

Now let's remove some leaf-list entry
`sysrepocfg -d running -s "/tiesse-dhcp-server:dhcp-server/server[name='pippo']/timesrv[.='1.2.3.5']"`

or all the leaf-list entries on one shot

`sysrepocfg -d running -r "/tiesse-dhcp-server:dhcp-server/server[name='pippo']/timesrv"`

As you can see the value to be set in the XPATH is passed under -w option.
Is there a more elegant way to pass the value to be written?
Is there any other useful operation to do using XPATHs?
Can I open a pull request or do you prefer to analyze the code before?
thanks
fabio

**Comment by jktjkt** [comment]
IMHO pull requests are fine.

**Comment by fabioantonini** [comment]
Ok it will be done

I'm looking forward to hear your feedback.

fabio

**Comment by rkrejci** [comment]
merged as #761
