### ISSUE TITLE
There is a not enabled node in X module, it can not be committed to the running

### ISSUE THREAD

**Issue by plajjan** [sysrepo/sysrepo#385]
I'm trying to commit some configuration and end getting an error message that reads `[ERR] (dm_commit_load_modified_models:2816) There is a not enabled node in ts-lw4o6 module, it can not be committed to the running`.

I might be doing something wrong here so it's not necessarily a bug but if nothing else I think I would like to have this log message improved since it's very difficult to understand what it's trying to tell me ;)

**Comment by rastislavszabo** [comment]
Hi, 
https://github.com/sysrepo/sysrepo/issues/387 contains the rationale for this. If you have any proposal for better wording of the message, please share it - we can definitely modify it.

**Comment by plajjan** [comment]
Subscriptions happen on a per YANG model basis, right? Or are they even more specific than that?

**Comment by lukasmacko** [comment]
There are two approaches how you can subscribe:
- whole module 
- subtree

It depedends on the application if the application covers the whole module it will subscribe for the changes in the whole module usually. However, there might be situation when the parts of yang model is covered by different applications. In that case [sr_subtree_change_subscribe](https://github.com/sysrepo/sysrepo/blob/master/inc/sysrepo.h#L1210) might be suitable. Another use case for subtree change is if you want to have separate callbacks for different parts of YANG model.
