### ISSUE TITLE
About sr_subscr_flag_t value SR_SUBSCR_APPLY_ONLY ,SR_SUBSCR_DEFAULT,SR_SUBSCR_VERIFIER 

### ISSUE THREAD

**Issue by ZhaoGuangYue** [sysrepo/sysrepo#396]
in the latest master branch we delete SR_SUBSCR_VERIFIER and add SR_SUBSCR_APPLY_ONLY.
According to this change ,there two questions i want to confirm,the question is like this:
1> According to the description ,if we sub change with SR_SUBSCR_DEFAULT the call back function  only called after the changes have been committed to the datastore;if we  use  SR_SUBSCR_APPLY_ONLY, the call back function after the changes has been applied in the datastore. I WONDER : Is these two values in same role?

2> after we delete the SR_SUBSCR_VERIFIER ,how can we  register verify call back function?

@rastislavszabo 

Thanks

```C
typedef enum sr_subscr_flag_e {
    SR_SUBSCR_DEFAULT = 0,    /**< Default behavior of the subscription. In case of ::sr_module_change_subscribe and
                                   ::sr_subtree_change_subscribe calls it (among other things) means that:
                                   - the subscriber is the "owner" of the subscribed data tree and and the data tree will be
                                   activated in the running datastore while this subcription is alive (can be changed with SR_SUBSCR_PASSIVE flag)
                                   - configuration data or the subscribed module or subtree is copied from startup to running datastore
                                   - the callback will be called just after the changes have been committed to the datastore
                                   (can be changed with SR_SUBSCR_VERIFIER flag). */
    SR_SUBSCR_CTX_REUSE = 1,  /**< This option enables the application to re-use an already existing subscription context
                                   previously returned from any sr_*_subscribe call instead of requesting the creation of a new one.
                                   In that case a single ::sr_unsubscribe call unsubscribes from all subscriptions filed within the context. */
    SR_SUBSCR_PASSIVE = 2,    /**< The subscriber is not the "owner" of the subscribed data tree, just a passive watcher for changes.
                                   When this option is passed in to ::sr_module_change_subscribe or ::sr_subtree_change_subscribe,
                                   the subscription will have no effect on the presence of the subtree in the running datastore. */
    SR_SUBSCR_APPLY_ONLY = 4, /**< The subscriber does not support verification of the changes and wants to be notified only
                                   after the changes has been applied in the datastore, without the possibility to deny them
                                   (it will receive only ::SR_EV_APPLY events). */
} sr_subscr_flag_t;
```

**Comment by ZhaoGuangYue** [comment]
use the latest master branch code ,I found when sub model change with flag  SR_SUBSCR_DEFAULT,the call back function will be call twice, the first call give the event number 0,the second call give the  
event number 1.

In this case ,i think we should update the description of  SR_SUBSCR_DEFAULT.

In my opinion, it is better to separate verify and apply model change subscription, in this way ,we can register different call back  function relate relevant to different notify event. 

what about your opinion @rastislavszabo

**Comment by rastislavszabo** [comment]
Hi,
this is a bug in the documentation, I will update it.

Default behavior is both verify and apply.
Another option is apply only.

Verify without apply does not make much sense, so we decided to not support this option.

**Comment by rastislavszabo** [comment]
Separating verify and apply subscription to allow registering different callback functions isn't a bad idea. It is just pity that v0.4.0 has been already released.. since this is a major change, we should not do it in this phase... maybe in the next version?
