### ISSUE TITLE
Sysrepo not handling multiple list entries in a single edit-config operation correctly

### ISSUE THREAD

**Issue by plajjan** [sysrepo/sysrepo#401]
I believe I found a sysrepo bug. I haven't had too much time looking into this but I guess it's in sysrepo or netopeer.

I'm trying to configure two entries in a YANG list;
```
admin@ncs% commit dry-run outformat native
device sysrepo {
  <rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"
       message-id="1">
    <edit-config xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
      <target>
        <candidate/>
      </target>
      <test-option>test-then-set</test-option>
      <error-option>rollback-on-error</error-option>
      <config>
        <lw-4o6 xmlns="http://terastrm.net/ns/yang/snabb-lw4o6">
          <prefixes>
            <prefix>1.2.1.1/32</prefix>
            <psid-length>4</psid-length>
          </prefixes>
          <prefixes>
            <prefix>1.2.1.2/32</prefix>
            <psid-length>4</psid-length>
          </prefixes>
        </lw-4o6>
      </config>
    </edit-config>
  </rpc>
}
[ok][2016-10-10 18:05:04]
```

and get this:
```
sysrepo-sysrepo-plugind[9]: [ERR] (rp_dt_set_item:323) Requested node is not valid /snabb-lw4o6:lw-4o6/prefixes[prefix='1.2.1.1/prefixes[prefix='1.2.1.2/32']
sysrepo-sysrepo-plugind[9]: [ERR] (rp_dt_set_item_wrapper:574) Set item failed
sysrepo-sysrepo-plugind[9]: [ERR] (rp_set_item_req_process:919) Set item failed for '/snabb-lw4o6:lw-4o6/prefixes[prefix='1.2.1.1/prefixes[prefix='1.2.1.2/32']', session id=1430478425.
```
That XPath looks completely corrupt...

if I only set a single list entry it works fine.

YANG:
```
module snabb-lw4o6 {

  namespace "http://terastrm.net/ns/yang/snabb-lw4o6";
  prefix slw4o6;

  import ietf-inet-types {
    prefix inet;
  }

  revision 2016-10-03 {
    description
      "Initial version";
  }

  container lw-4o6 {
    list prefixes {
      key "prefix";

      leaf prefix {
        type inet:ipv4-prefix;
      }
      leaf psid-length {
        mandatory true;
        type uint8 {
          range "1..16";
        }
      }
    }
```

**Comment by lukasmacko** [comment]
This seems to be a bug in Netopeer2. We'll see to it.

**Comment by plajjan** [comment]
Ok, I'm sorry I don't have enough knowledge on netopeer2 and sysrepo to differentiate where a bug is located so sysrepo kind of ends up as my "default route" ;)

I'd like to see these kinds of things being covered by Travis-CI too. Can we do that?

**Comment by rastislavszabo** [comment]
> I'd like to see these kinds of things being covered by Travis-CI too. 

Me too :) This is about writing unit-tests for Netopeer2, which hasn't been very well covered by unit-tests yet. Or about writing end-to-end NETCONF tests, that we don't have either. Sysrepo itself is covered quite well, but it's not enough.

**Comment by rkrejci** [comment]
Netopeer2 definitely needs more unit test, however I don't thing that this bug would be detected by the unit tests. The problem was caused by searching for `/` character in the path to move back to the previous level. It wasn't taken into account that character `/` can appear in a key value as in this case.

**Comment by plajjan** [comment]
@rkrejci aha I see, le funny :P 
Thanks for the fix!

Since the fix is on netopeer this hasn't triggered a rebuild of the sysrepo docker image. Do you think it would be possible to use the webhook triggers of docker hub to trigger builds of the sysrepo docker image when netopeer is updated?

**Comment by rastislavszabo** [comment]
> Do you think it would be possible to use the webhook triggers of docker hub to trigger builds of the sysrepo docker image when netopeer is updated?

Yes, this could work.

Actually a new sysrepo-netopeer2 docker image is just in build process due to a recent commit into sysrepo :)

**Comment by plajjan** [comment]
Hehe, that will fullfill my immediate needs too :P
