### ISSUE TITLE
Getting error while running sample application

### ISSUE THREAD

**Issue by rajnkamr** [sysrepo/sysrepo#419]
I am running one sample application to connect to sysrepo

Getting below error 
Error by sr_session_start: Malformed message

**Comment by rastislavszabo** [comment]
Hi, could you please add some more information? What is the code of the sample application? What yang models do you have installed in sysrepo? Any logs from sysrepo daemon?

**Comment by rajnkamr** [comment]
Here is the code area where it is failing to start session

 debugPrint("SR START SESSION\n");
 rc = sr_session_start(connection, SR_DS_RUNNING, SR_SESS_CONFIG_ONLY, &session);
 if (SR_ERR_OK != rc) {
     fprintf(stderr, "Error by sr_session_start: %s\n", sr_strerror(rc));
     goto cleanup;
 }

When daemon is killed and not running it works fine

Log from sysrepo daemon

[root@MaestrOS tmp]# [DBG] Setting log level for stderr logs to 4.
SR CONNECT 26696
[DBG] Connecting to Sysrepo Engine.
[DBG] Connecting to socket=/var/run/sysrepod.sock
[INF] Connected to daemon Sysrepo Engine at socket=/var/run/sysrepod.sock
SR START SESSION
[DBG] Sending session-start request.
[DBG] session-start request sent, waiting for response.
[ERR] Malformed message received.
[ERR] Unable to receive the message with response (session id=0, operation=session-start).
[ERR] Error by processing of the request.
Error by sr_session_start: Malformed message

**Comment by rastislavszabo** [comment]
Hi,
The logs you provided seem to be from the client, not sysrepo daemon.

> When daemon is killed and not running it works fine

From what you are writing, it seems to me that you have a version mismatch between the client library and the sysrepo daemon you are running. Can you please check? (`sysrepod -v`)

**Comment by rajnkamr** [comment]
sysrepod - sysrepo daemon, version 0.4.2

**Comment by milanlenco** [comment]
Hi Rajnish,
does this issue still exist or was it fixed together with #428 and can be closed now?

Thanks,
Milan

**Comment by rajnkamr** [comment]
Hi Milan,
this can be closed.

Regards,
Rajnish
