### ISSUE TITLE
Differentiate imported and implemented modules in sr_list_schemas()

### ISSUE THREAD

**Issue by rkrejci** [sysrepo/sysrepo#422]
To keep libyang context in sysrepo and northbound interface application (netopeer2-server in my case) synced, it is necessary to distinguish between just imported and implemented schemas (can be obtained from the `struct lys_module::implemented`. `sr_list_schemas()` can obtain only the implemented modules or a new flag can be added into the `struct sr_schema_s`.

**Comment by rkrejci** [comment]
Similarly, the difference between imported and implemented modules should be somehow reflected also when calling `sr_module_install_cb()`.

**Comment by milanlenco** [comment]
Hi Radek,
This feature is now implemented in devel: https://github.com/sysrepo/sysrepo/pull/454
Please check if it satisfies all the requirements.
Thanks,
Milan
