### ISSUE TITLE
Error during install of yang module

### ISSUE THREAD

**Issue by rajnkamr** [sysrepo/sysrepo#428]
Getting error when installing yang modules
error undefined symbol: md_init

[root@MaestrOS yang-models]# /usr/bin/sysrepoctl --install --yang=ietf-system@2014-08-06.yang
Installing a new module from file 'ietf-system@2014-08-06.yang'...
/usr/bin/sysrepoctl: symbol lookup error: /usr/bin/sysrepoctl: undefined symbol: md_init

**Comment by milanlenco** [comment]
Hi Rajnish,

we recommend you to completely reinstall sysrepo from scratch. From this issue as well as from #419 it is apparent that you have version mismatch between libraries and executables.

Regards,
Milan

**Comment by rajnkamr** [comment]
Thanks Milan, after installaing again it worked
