### ISSUE TITLE
sr_get_changes_iter need to exclude NP container if there is no default node

### ISSUE THREAD

**Issue by qmm161** [sysrepo/sysrepo#432]
libyang will create empty NP contianer even if there is no default node now.
see lyd_wd_add_subtree : 
            /\* always create empty NP container even if there is no default node,
             \* because accroding to RFC, the empty NP container is always part of
             \* accessible tree (e.g. for evaluating when and must conditions) */

but it is confusing when I call sr_get_changes_iter and get such a np container created change record. should this be a bug?

for example, sr_get_changes_iter will get container Child2 and Grandchild2 created record when i just create rootleaf under container Root.

```
module Demo{
    namespace "urn:ietf:params:xml:ns:yang:demo";
    prefix Demo;
    revision 2016-05-10;

    container Root{
        presence "root";
        leaf rootleaf{
            type int8;
        }

        container Child1{
            leaf child1leaf{
                type int8;
            }

            container Grandchild1{
                leaf grandchild1leaf{
                    type int8;
                    default 10;
                }
            }
        }

        container Child2{
            leaf child2leaf{
                type int8;
            }

            container Grandchild2{
                leaf grandchild2leaf{
                    type int8;
                }
            }
        }
  }
}
```

**Comment by milanlenco** [comment]
Hi,

I agree with you that it is confusing. I will make a patch to filter out the empty non-default containers.

Thanks,
Milan

**Comment by qmm161** [comment]
Thanks

**Comment by qmm161** [comment]
Hi,

I find the bug was fixed. The create operation of non-default containers were filtered.
But it is much more confusing that sysrepo give the change type SR_OP_MODIFIED when non-default container was really created next time. 

Thanks.

**Comment by milanlenco** [comment]
Hi,

actually I'm unable to re-produce this behaviour. A non-presence container cannot be created directly, only by creating at least one of its children. When I create a child, the container is not shown in the list of changes (this is actually a bug) as it was already considered as created, but that information was filtered out by the patch above. As for presence containers, they do not get automatically created and so when you create one yourselves, it will be shown as created according to the expectations. Could you please provide the list of commands that you issued and received a container shown as modified?

Thanks

**Comment by qmm161** [comment]
Hi,

I'm sorry I got something wrong when I test this issue above, let me take the Demo module above as an example.

User Action | Create Operation in Change List
------------- | -------------
1. Create Root  |  Root , Child1, Grandchild1, and grandchild1leaf
2. Then create child1leaf  |  child1leaf
3. Then create grandchild2leaf |  Child2, Grandchild2, and grandchild2leaf

**Comment by ostack** [comment]
I commit an issue to libyang to discuss should it create the non-presence  container if it does not have any default value node. as in my opinion it is confused for the user to config the data 
https://github.com/CESNET/libyang/issues/180
@milanlenco @qmm161

**Comment by milanlenco** [comment]
Hi @qmm161,
So I followed your steps and all the containers have been created, never modified, as you have listed in the second column. I would say that it is the correct outcome. Or is there still something unexpected about current behaviour that you would like us to change? If not, then I would close this issue.

Thanks
