### ISSUE TITLE
sr_module_change_subscribe will fail when the module contains no data

### ISSUE THREAD

**Issue by fanchanghu** [sysrepo/sysrepo#434]
Hi,
If a module contains just augment, grouping or other element that does not defined in data tree, `sr_module_change_subscribe` will fail, is this expected or a bug?  do I need using `sr_module_change_subscribe` to enable the module if it  contains no data?

**Comment by milanlenco** [comment]
Hi,
this is expected behaviour because data are stored in the module that is augmented / uses grouping.
Modules that contain only augments, groupings and typedefs do not contain any data (they do not even have data files created in the repository) and thus cannot be subscribed to for changes.
