### ISSUE TITLE
sysrepo-module-dependencies.xml not found

### ISSUE THREAD

**Issue by mkarthig** [sysrepo/sysrepo#442]
I installed sysrepo today and tried to start sysrepo daemon, but it says " Unable to open sysrepo-module-dependencies.xml data file :No such file or directory". Is it a default file in package or it will be install during make install. Thanks in advance.

**Comment by fabioantonini** [comment]
Hi
this file should be placed under 

/etc/sysrepo/data/internal/sysrepo-module-dependencies.xml
This file is populated by sysrepoctl command used to install your .yang files. 

Please verify that this file is present
regards
fabio

**Comment by frahmanu** [comment]
Hi  ,
I too faced the same issue. It looks sysrepo-module-dependencies.xml is not created during make. Do i need to explicitly create a .xml file with the list of modules ?

**Comment by fabioantonini** [comment]
It cannot be generated at compile time because it will be populated by the sysrepoctl --install command

please install some .yang file

for instance
sysrepoctl --install --yang=<your sysrepo dir>/examples/yang/turing-machine.yang --owner=root:root --permissions=644

**Comment by mkarthig** [comment]
Hi
 Just found that. Thanks

**Comment by milanlenco** [comment]
Hi,

It is strange though that the missing sysrepo-module-dependencies.xml will cause sysrepo daemon to fail to start, it shouldn't happen. Daemon should start even if no schema is installed. I will investigate further and make a patch. Please don't close this issue yet.

Thanks for reporting,
Milan

**Comment by frahmanu** [comment]
Hi @fabioantonini ,

Just found that. 
But sysrepoctl is expecting the .xml file should be present to install the module.
./sysrepoctl --install --yang=/employee-module.yang 
Installing a new module from file '/employee-module.yang'...
[ERR] (md_init:978) Unable to open sysrepo-module-dependencies.xml data file: No such file or directory.
Error: Failed to initialize module dependencies context.
Install operation failed.


I created a dummy file to make it work. 
I will be good if the file is created during install.

Thanks.

**Comment by milanlenco** [comment]
Hi,
So after investigating the issue I found out that sysrepo daemon v. 0.3.0 will fail to start if sysrepo-module-dependencies.xml is missing. In sysrepo version 0.4.0, however, it was fixed. So please update the sysrepo to the latest version if it is not already.
Alternatively, the problem could be that the layout of repository is not what sysrepo daemon expects.
Cmake should install these directories:
```
REPOSITORY
REPOSITORY/yang
REPOSITORY/yang/internal
REPOSITORY/data
REPOSITORY/data/internal
```
It may be that you are for example missing the `internal` directory inside `REPOSITORY/data` and sysrepod will fail to start. I have prepared patch that will cause sysrepod/sysrepoctl/sysrepocfg to create the internal directory if it doesn't exist yet as well as all missing parents. The patch will be merged today to master.
