### ISSUE TITLE
Unable to resolve dependency induced by an augment

### ISSUE THREAD

**Issue by mkarthig** [sysrepo/sysrepo#451]
Hi

..........
Installing data files for module 'bbf-fast'...
[ERR](md_insert_lys_module:1800) Unable to resolve dependency induced by an augment.
Error: Unable to insert the module into the dependency graph.
Reverting the install operation...
Deleted the data files for module 'bbf-fast'.
Deleted the schema file '/etc/sysrepo/yang/bbf-fast@2016-07-18.yang'.
Install operation failed.

I got the above error when i tried to install bbf yang files.
./sysrepoctl --install --yang=/home/mkarthig/yang/bbf-fa
st.yang. How can i fix this?.. Thanks in advance.

**Comment by rastislavszabo** [comment]
Hi,

could you please provide us the yang models you are trying to install so we can reproduce the issue?

Thanks,
Rastislav

**Comment by mkarthig** [comment]
Hi

please refer the following links. In the first link, i was used bbf-fast yang files. Also used some dependency yang files from 2nd link(IETF) . Thanks in advance.

https://github.com/BroadbandForum/yang/tree/master/standard

https://github.com/YangModels/yang/tree/master/standard/ietf/RFC

**Comment by mkarthig** [comment]
Hi  Milan

                Can you update the status of the issue. 

Regards,
mkarthig

**Comment by lukasmacko** [comment]
Hi,

this seems to be a libyang issue. Libyang is not able to load module. I'll report it.

pyang also complains about:
```
bbf-fast-rfi-profile-body.yang:191: error: the value "[]" does not match its base type at bbf-fast-rfi-profile-body.yang:110 - bit not defined for the default value
```

Regards,
Lukas

**Comment by mkarthig** [comment]
Hi
    Actually i was raised the same issue which you raised in libyang two weeks back. They modified the code in devel branch  and it is working fine. But now the issue is with newly added module dependencies file when try to resolve the augment dependency. Can you please check it.

Reference : https://github.com/CESNET/libyang/issues/160

Regards,
mkarthig

**Comment by lukasmacko** [comment]
I was testing it with master. I'll try the devel branch and I'll let you know.

**Comment by mkarthig** [comment]
ok. Thank you

**Comment by lukasmacko** [comment]
It should be fixed in master and in devel branch as well. 

Regards,
Lukas

**Comment by mkarthig** [comment]
Ok. Thank you.

Regards,
mkarthig
