### ISSUE TITLE
Want to check xpath is valid first when get-items, in order to tell the user the exactly errors

### ISSUE THREAD

**Issue by ostack** [sysrepo/sysrepo#452]
Want to check xpath is valid first when get-items, in order to tell the user the exactly errors

what about your opinion

**Comment by lukasmacko** [comment]
Hi,

we plan to do that. We'll use error codes SR_ERR_UNKNOWN_MODEL, SR_ERR_BAD_ELEMENT.

Regards,
Lukas

**Comment by lukasmacko** [comment]
Fixed in devel branch.
