### ISSUE TITLE
add a definition of private/public to make a distinction between inner use function or public use function in a file?

### ISSUE THREAD

**Issue by ostack** [sysrepo/sysrepo#453]
add a definition of private/public to make a distinction between inner use function or public use function in a file? i think if we use this definition we can easy let the new committer know the function's action scope
  
**the definition is like this**
#ifndef PRIVATE
#define PRIVATE
#endif

#ifndef PUBLIC
#define PUBLIC
#endif

#ifndef API
#define API
#endif

**Comment by lukasmacko** [comment]
Hi,
public API is under [sysrepo/inc](https://github.com/sysrepo/sysrepo/tree/master/inc). There are prototypes of functions (in general they have prefix `sr_*`) from [client-library.c](https://github.com/sysrepo/sysrepo/blob/master/src/clientlib/client_library.c) and [utils](https://github.com/sysrepo/sysrepo/tree/master/src/utils). 

The other functions are internal. Internal functions that are used only inside the module use `static` keyword. 

I don't see a benefit of having suggested empty macros right now.

Regards,
Lukas
