### ISSUE TITLE
Sysrepo change notification does not seem to be working.

### ISSUE THREAD

**Issue by darren-west** [sysrepo/sysrepo#456]
I have been trying to run the change notification example and have been unable to make a change that fires the notification. 

Upon running the example I have an issue that the node is not enabled in the running datastore. I have continued to look into this and have tried a change in the startup datastore and the notification still doesn't get fired.

Any ideas?

**Comment by lukasmacko** [comment]
Hi,

take a look into [this](https://github.com/sysrepo/sysrepo/wiki/Frequently-Asked-Questions-(FAQs)

just briefly:
- you can receive notification only about the changes made in running data store.
- to enable a node there must be a subscription

Regards,
Lukas

**Comment by darren-west** [comment]
Hi, 
Thanks for the quick response. Yes that was my mistake. 

But I am still getting an issue with running the example sr_get_change_iter_example 
The notification never seems to be triggered. I am looking through the debug statements at the moment and can see this statement:

Sending a notification to '/var/run/sysrepo-subscriptions/ietf-interfaces/46816.rzUA33.sock'.

I will carry on looking into this.

**Comment by darren-west** [comment]
Hi again,

I have looked into this issue it seems to be more with the example than with the code although I cannot see any changes and im fairly certain it was working a couple of weeks ago. 

The example uses a mutex to lock and it is unable to move onto the callback printing because it is already locked and tries to gain the lock in the list_changes_cb so hangs here. 

I can confirm that removing this attempt to gain the lock fixes the issue and the notification callbacks work.

Thanks
Darren

**Comment by lukasmacko** [comment]
Hi Darren,

yes, you're right there is an issue in the example I'll fix it.

For explanation see [this](https://github.com/sysrepo/sysrepo/blob/master/inc/sysrepo.h#L1084-L1091). A subscription that uses `SR_SUBSCR_DEFAULT` flag recevies two notifications. In the first `SR_EV_VERIFY` phase it is supposed to validate the changes, it has an opportunity to reject the changes by returning non zero return code. Next, it receives `SR_EV_APPLY` notification indicating that changes has been validated by all subscribers and can be applied. In case of failure it receives `SR_EV_ABORT` instead.

Quick workaround for you is to use `SR_SUBSCR_APPLY_ONLY` flag in subscription - you'll receive only notification.

Regards,
Lukas
