### ISSUE TITLE
Oper data subscription for new yang modules

### ISSUE THREAD

**Issue by rajnkamr** [sysrepo/sysrepo#468]
We have below hierarchy for yang model for oper data

<op-data-subtree>
      <xpath>/ietf-system:system-state/adva-ensemble-system-info:system-info/software/software-group</xpath>
      <orig-module-revision>2016-10-06</orig-module-revision>
      <orig-module-name>adva-ensemble-system-info</orig-module-name>
    </op-data-subtree>

when i try to register with above xpath it fails 

Here is the code which i use

     debugPrint("sr_dp_get_items subscribe system-system-info\n");
     rc = sr_dp_get_items_subscribe(session, "/ietf-system:system-state/adva-ensemble-system-info:system-info/software/software-group", data_provider_system_info_cb, NUL
 L,SR_SUBSCR_DEFAULT, &subscription);
     if (SR_ERR_OK != rc) {
     printf("sr_dp_get_items_subscribe system failed\n");
     goto cleanup;
     }
here is the log

sr_dp_get_items subscribe system-system-info
[DBG] Initializing sysrepo subscription server at socket=/var/run/sysrepo-subscriptions/ietf-system/3599.pbZOhR.sock
[DBG] Sending subscribe request.
[DBG] subscribe request sent, waiting for response.
[DBG] subscribe response received, processing.
[ERR] Error by processing of the subscribe request (session id=1390069997): Schema node "software-group" not found (/ietf-system:system-state/adva-ensemble-system-info:system-info/software/software-group)..
[ERR] Error by processing of the request.

**Comment by rastislavszabo** [comment]
Hi, please check this: https://github.com/sysrepo/sysrepo/wiki/Frequently-Asked-Questions-(FAQs)#2-error-by-processing-of-the-subscribe-request-schema-node-xyz-not-found

**Comment by rajnkamr** [comment]
After uninstall it started working
