### ISSUE TITLE
Docs: please explain threading model of callbacks

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#477]
Documentation doesn't say in which thread the callback are going to run. I see that ``cl_subscription_init`` calls ``cl_sm_init`` for a first connection which in turn calls ``pthread_create``, but I do not like to rely on implementation details.

If I register several callbacks form the same session and from the same thread, is there a guarantee that all these callbacks will get executed and serialized in a single thread which might be different from my main thread? It seems so.

Preferably, I would like the documentation to tell me:

- how and when sysrepo creates threads and how ``local_fd_watcher`` comes into play,
- the relation between sessions, threads and callbacks, and the guarantees that sysrepo provides (see my main question above),
- what is different when I do stuff from a plugin loaded by ``sysrepo-plugind`` as opposed to a standalone application.

**Comment by jktjkt** [comment]
A small TL;DR would be enough for me as a stopgap measure. I have some registered callbacks, one via ``module_change_subscribe``, the other one via ``dp_get_items_subscribe``. Do we have a guarantee that both will ever be only called from a single thread?

**Comment by rastislavszabo** [comment]
Hi,

> all these callbacks will get executed and serialized in a single thread which might be different from my main thread

Yes, that's true. The thread is different from the main one, but all the callbacks will be executed in the same thread. The `local_fd_watcher` can be used if you need to have them executed in the main thread.

**Comment by jktjkt** [comment]
Thanks.
