### ISSUE TITLE
Bitfield warnings when building sysrepo?

### ISSUE THREAD

**Issue by darren-west** [sysrepo/sysrepo#488]
Hi,

This is more of my problem as I see your build does not do this but I wondered if you could help. 

I am trying to build sysrepo using travis and am having an issue with warnings being fired out and example is below:

/home/travis/local/include/libyang/tree_schema.h:934:5: warning: type of bit-field ‘flags’ is a GCC extension [-Wpedantic]
     uint16_t flags:14;               /**< [schema node flags](@ref snodeflags) */

I know this is being caused because sysrepo makefile has the following:
 set(CMAKE_C_FLAGS         "${CMAKE_C_FLAGS} -Wall -Wpedantic -std=gnu11")
Wpedentic is set.

This does not seem to happen on your travis build I was wondering if you have any ideas?

Thanks in advance,
Darren

**Comment by rastislavszabo** [comment]
Hi,

https://github.com/CESNET/libyang/issues would be probably a better place to ask, since the reported error is in libyang, not sysrepo.

From what I can tell, we have no issues building libyang in Travis on Ubuntu 14.04 and Mac OS, nor by automated builds on Dockerhub..

**Comment by darren-west** [comment]
Hi,

This issue actually arises after I have successfully installed libyang with no warnings and am running make in sysrepo. 

I can also get it to build correctly in ubuntu 14.04 and 16.04 but when i try and run on a trusty image which seems to have all the same packages and versions I get these warnings. 

I have dumped more of the warnings below:



Scanning dependencies of target proto
[  1%] Running C protocol buffer compiler on /home/travis/sysrepo/src/sysrepo.proto
[  1%] Built target proto
Scanning dependencies of target COMMON
[  5%] [  5%] Building C object src/CMakeFiles/COMMON.dir/common/sr_common.c.o
Building C object src/CMakeFiles/COMMON.dir/common/sysrepo.pb-c.c.o
In file included from /home/travis/local/include/libyang/libyang.h:20:0,
                 from /home/travis/sysrepo/src/common/sr_utils.h:36,
                 from /home/travis/sysrepo/src/common/sr_common.h:44,
                 from /home/travis/sysrepo/src/common/sr_common.c:28:
/home/travis/local/include/libyang/tree_schema.h:241:5: warning: type of bit-field ‘type’ is a GCC extension [-Wpedantic]
     uint8_t type:1;                  /**< 0 - structure type used to distinguish structure from ::lys_submodule */
     ^
/home/travis/local/include/libyang/tree_schema.h:242:5: warning: type of bit-field ‘version’ is a GCC extension [-Wpedantic]
     uint8_t version:4;               /**< yang-version:
     ^
/home/travis/local/include/libyang/tree_schema.h:246:5: warning: type of bit-field ‘deviated’ is a GCC extension [-Wpedantic]
     uint8_t deviated:2;              /**< deviated flag:
     ^
/home/travis/local/include/libyang/tree_schema.h:250:5: warning: type of bit-field ‘implemented’ is a GCC extension [-Wpedantic]
     uint8_t implemented:1;           /**< flag if the module is implemented, not just imported */
     ^
/home/travis/local/include/libyang/tree_schema.h:294:5: warning: type of bit-field ‘type’ is a GCC extension [-Wpedantic]
     uint8_t type:1;                  /**< 1 - structure type used to distinguish structure from ::lys_module */
     ^
/home/travis/local/include/libyang/tree_schema.h:295:5: warning: type of bit-field ‘padding’ is a GCC extension [-Wpedantic]
     uint8_t padding:7;               /**< not used, kept for compatibility with ::lys_module */
     ^
/home/travis/local/include/libyang/tree_schema.h:696:5: warning: type of bit-field ‘flags’ is a GCC extension [-Wpedantic]
     uint16_t flags:14;               /**< [schema node flags](@ref snodeflags) */
     ^
/home/travis/local/include/libyang/tree_schema.h:697:5: warning: type of bit-field ‘nacm’ is a GCC extension [-Wpedantic]
     uint16_t nacm:2;                 /**< [NACM extension flags](@ref nacmflags) */
     ^
/home/travis/local/include/libyang/tree_schema.h:732:5: warning: type of bit-field ‘flags’ is a GCC extension [-Wpedantic]
     uint16_t flags:14;               /**< [schema node flags](@ref snodeflags) */
     ^
/home/travis/local/include/libyang/tree_schema.h:733:5: warning: type of bit-field ‘nacm’ is a GCC extension [-Wpedantic]
     uint16_t nacm:2;                 /**< [NACM extension flags](@ref nacmflags) */
     ^
/home/travis/local/include/libyang/tree_schema.h:780:5: warning: type of bit-field ‘flags’ is a GCC extension [-Wpedantic]
     uint16_t flags:14;               /**< [schema node flags](@ref snodeflags) */
     ^
/home/travis/local/include/libyang/tree_schema.h:781:5: warning: type of bit-field ‘nacm’ is a GCC extension [-Wpedantic]
     uint16_t nacm:2;                 /**< [NACM extension flags](@ref nacmflags) */
     ^
/home/travis/local/include/libyang/tree_schema.h:826:5: warning: type of bit-field ‘flags’ is a GCC extension [-Wpedantic]
     uint16_t flags:14;               /**< [schema node flags](@ref snodeflags) */
     ^
/home/travis/local/include/libyang/tree_schema.h:827:5: warning: type of bit-field ‘nacm’ is a GCC extension [-Wpedantic]
     uint16_t nacm:2;                 /**< [NACM extension flags](@ref nacmflags) */
     ^
/home/travis/local/include/libyang/tree_schema.h:880:5: warning: type of bit-field ‘flags’ is a GCC extension [-Wpedantic]
     uint16_t flags:14;               /**< [schema node flags](@ref snodeflags) */
     ^
/home/travis/local/include/libyang/tree_schema.h:881:5: warning: type of bit-field ‘nacm’ is a GCC extension [-Wpedantic]
     uint16_t nacm:2;                 /**< [NACM extension flags](@ref nacmflags) */
     ^
/home/travis/local/include/libyang/tree_schema.h:934:5: warning: type of bit-field ‘flags’ is a GCC extension [-Wpedantic]
     uint16_t flags:14;               /**< [schema node flags](@ref snodeflags) */
     ^
/home/travis/local/include/libyang/tree_schema.h:935:5: warning: type of bit-field ‘nacm’ is a GCC extension [-Wpedantic]
     uint16_t nacm:2;                 /**< [NACM extension flags](@ref nacmflags) */
     ^
/home/travis/local/include/libyang/tree_schema.h:989:5: warning: type of bit-field ‘flags’ is a GCC extension [-Wpedantic]
     uint16_t flags:14;               /**< [schema node flags](@ref snodeflags) */
     ^
/home/travis/local/include/libyang/tree_schema.h:990:5: warning: type of bit-field ‘nacm’ is a GCC extension [-Wpedantic]
     uint16_t nacm:2;                 /**< [NACM extension flags](@ref nacmflags) */
     ^

**Comment by jktjkt** [comment]
> I can also get it to build correctly in ubuntu 14.04 and 16.04 
> but when i try and run on a trusty image which seems to have all 
> the same packages and versions I get these warnings. 

Which compiler (and which version) do you use? Running your build as e.g. 
``make VERBOSE=1`` should display the actual CC invocations along with all 
flags.

**Comment by darren-west** [comment]
Hi,
thanks for your response. I am using the gcc compiler:
gcc version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

This is an example with VERBOSE enabled.

[  3%] Building C object src/CMakeFiles/COMMON.dir/common/sysrepo.pb-c.c.o
cd /home/travis/sysrepo/build/src && /usr/bin/gcc   -w -Wall -Wpedantic -std=gnu11 -Wno-strict-aliasing -DNDEBUG -O2 -I/home/travis/sysrepo/build -I/home/travis/sysrepo/inc -I/home/travis/local/include -I/home/travis/sysrepo/src -I/home/travis/sysrepo/src/clientlib -I/home/travis/sysrepo/src/common -I/home/travis/sysrepo/build/src/common -I/home/travis/sysrepo/src/executables -I/home/travis/sysrepo/src/utils    -fPIC -o CMakeFiles/COMMON.dir/common/sysrepo.pb-c.c.o   -c /home/travis/sysrepo/build/src/common/sysrepo.pb-c.c

**Comment by jktjkt** [comment]
So this is a bug in GCC, see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=57773 .
