### ISSUE TITLE
How can I subscribe for delivery of all of event notifications in sysrepo repository using sr_event_notif_subscribe

### ISSUE THREAD

**Issue by niuzhiquan** [sysrepo/sysrepo#498]
Hi
I want to subscribe for  delivery of all of event notifications in sysrepo repository. However, when I use the sr_event_notif_subscribe, I find it subscribes the only one event notification specified by xpath. How can I solve this problem?
thanks.

**Comment by lukasmacko** [comment]
Hi,

unfortunately there is not a way how to subscribe for all event notifications in the current implementation. You can reuse one (subscription context)[https://github.com/sysrepo/sysrepo/blob/master/inc/sysrepo.h#L1060-L1062] however you have to enumerate all notifications. 

Regards,
Lukas
