### ISSUE TITLE
callback on config lock 

### ISSUE THREAD

**Issue by vishalwc** [sysrepo/sysrepo#499]
In order to lock the external DB we need a callback on lock , do we have provision in sysrepo ?

Currently when we commit we get callback to update and verify the external DB .

**Comment by rastislavszabo** [comment]
Hi,
this kind of API is not yet implemented nor was planned to implement. We can track it as an enhancement request.

**Comment by michalvasko** [comment]
Supported for NETCONF `<lock>` and `<unlock>`.
