### ISSUE TITLE
Documentation for systemd setup and configuration

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#514]
As suggested post-review in #496, this should probably be documented (and made configurable).

**Comment by jktjkt** [comment]
(I wanted to assign this to myself, but apparently github only allows this for project owners, which makes sense. So this is just a reminder that yeah, I want to do this, so that it isn't tracked just in an closed pull request.)

**Comment by rastislavszabo** [comment]
Thanks!

**Comment by michalvasko** [comment]
Not relevant anymore.
