### ISSUE TITLE
Application subscribe for module changes failed

### ISSUE THREAD

**Issue by mkarthig** [sysrepo/sysrepo#518]
Hi
          I tried to run the example application named "application_example"  for subscribing the module changes in running datastore but it is failed. I have attached the logs. please look at it. Thanks in advance. 

Yangs used: 
please refer the following links. In the first link, i was used bbf-fast yang files. Also used some dependency yang files from 2nd link(IETF) .

https://github.com/BroadbandForum/yang/tree/master/standard

https://github.com/YangModels/yang/tree/master/standard/ietf/RFC

............# ./sysrepod -d -l3
[INF] (dm_init:1405) Initializing Data Manager, schema_search_dir=/etc/sysrepo/yang/, data_search_dir=/etc/sysrepo/data/
[INF] (main:135) Sysrepo daemon initialized successfully.

[INF] (sm_session_create:467) New session created successfully, real user=root, effective user=(null), session id=1856785308.
[INF] (rp_dt_get_values_wrapper:911) Get items request startup datastore, xpath: /bbf-fast:*//*
[INF] (dm_load_data_tree_file:693) Data file /etc/sysrepo/data/bbf-fast.startup is empty
[ERR] (rp_dt_validate_node_xpath_intrenal:387) Module bbf-fast-base not found in provided schema info
[ERR] (rp_dt_enable_xpath:561) Xpath validation failed /bbf-fast-base:fast
[ERR] (dm_enable_module_running:3560) Enable module bbf-fast running failed
[ERR] (np_notification_subscribe:452) Unable to enable the module in the running datastore.
[ERR] (pm_save_persistent_data:300) Unable to modify persist data tree.
[INF] (cm_conn_close:393) Closing the connection 0x10118748.
[INF] (dm_unlock_datastore:1021) Unlock datastore request
[INF] (sm_session_drop:484) Dropping session id=1856785308.
[INF] (cm_conn_close:393) Closing the connection 0x1008d4f0.
[ERR] (pm_save_persistent_data:300) Unable to modify persist data tree.
[ERR] (np_unsubscribe_destination:580) Unable to remove subscriptions for destination '/tmp/sysrepo-subscriptions/bbf-fast/25855.GoZTbe.sock' from 'bbf-fast'.
[WRN] (rp_msg_dispatch:2717) Error by processing of the message: The item expected to exist is missing.

................ # ./application_example bbf-fast

 ========== READING STARTUP CONFIG: ==========

Error by sr_module_change_subscribe: Requested schema model is not known
Error by sr_get_items: Item not found

**Comment by lukasmacko** [comment]
Hi,

it is fixed in devel branch. It will be merged to master soon.

Regards,
Lukas

**Comment by mkarthig** [comment]
Thank you.
