### ISSUE TITLE
Get-items failed

### ISSUE THREAD

**Issue by mkarthig** [sysrepo/sysrepo#524]
Hi
    I tried to run the example application "sr_get_items_example" by giving xpath as "/bbf-fast:fast//*" after done the edit-config but it is failed. I have attached the logs. please look at it. Thanks in advance

Yangs used:
please refer the following links. In the first link, i was used bbf-fast yang files. Also used some dependency yang files from 2nd link(IETF) .

https://github.com/BroadbandForum/yang/tree/master/standard

https://github.com/YangModels/yang/tree/master/standard/ietf/RFC

............# ./sysrepod -d -l3

[INF] (dm_init:1406) Initializing Data Manager, schema_search_dir=/etc/sysrepo/yang/, data_search_dir=/etc/sysrepo/data/
[INF] (main:135) Sysrepo daemon initialized successfully.

[INF] (sm_session_create:467) New session created successfully, real user=root, effective user=(null), session id=416827013.
[INF] (rp_dt_get_values_wrapper:911) Get items request running datastore, xpath: /bbf-fast:fast//*
[INF] (dm_load_data_tree_file:696) Data file /etc/sysrepo/data/bbf-fast.running loaded successfully
[WRN] (dm_load_module:561) An attempt to load submodule bbf-fast-base
[ERR] (dm_free_schema_info:201) NULL value detected for schema_info argument of dm_free_schema_info
[ERR] (rp_dt_find_nodes:48) Get schema info failed for bbf-fast-base
[ERR] (rp_dt_get_values:214) Get nodes for xpath /bbf-fast:fast//* failed (1)
[ERR] (rp_dt_get_values_wrapper:930) Get values failed for xpath '/bbf-fast:fast//*'
[ERR] (rp_get_items_req_process:517) Get items failed for '/bbf-fast:fast//*', session id=416827013.
[INF] (dm_unlock_datastore:1022) Unlock datastore request
[INF] (sm_session_drop:484) Dropping session id=416827013.
[INF] (cm_conn_close:393) Closing the connection 0x10336dc0.

Regards,
mkarthig

**Comment by mkarthig** [comment]
Can you update the status of the issue?

Regards,
mkarthig

**Comment by milanlenco** [comment]
Hi,

with empty datastore we are unable to reproduce the issue. Would it be possible for you to provide us a minimum configuration that when fully requests by sr_get_items triggers the bug?

Thanks

**Comment by mkarthig** [comment]
Hi
       I have attached the running datastore configuration below. Please look at it.

bbf-fast.running:

<fast xmlns="urn:bbf:yang:bbf-fast">
  <service>
    <time-division-duplexing-profile>
      <name>tdd_test1</name>
    </time-division-duplexing-profile>
  </service>
</fast>

**Comment by mkarthig** [comment]
Hi 
     I have attached the running datastore configuration below. Please look at it.

bbf-fast.running:

<fast xmlns="urn:bbf:yang:bbf-fast">
  <service>
    <time-division-duplexing-profile>
      <name>tdd_test1</name>
    </time-division-duplexing-profile>
  </service>
</fast>

**Comment by mkarthig** [comment]
Hi
      I have attached the running datastore configuration below. Please look at it.
[bbf-fast-running.txt](https://github.com/sysrepo/sysrepo/files/591227/bbf-fast-running.txt)

Regards,
mkarthig

**Comment by mkarthig** [comment]
Thank you
