### ISSUE TITLE
Get rpc ok reply on invalid when clause entered

### ISSUE THREAD

**Issue by joanlandry** [sysrepo/sysrepo#526]
I purposely put an invalid value for the when clause and issued an edit config. I expected to get an error reply but instead go OK. In the sysrepo log the error is detected by libyang - but that erro does not make it to the user.
```
The interface type should be int-ip not int-tun.
      container ip {
        when "../interface-type = 'int-ip'";
        uses `ensembleintip:ip-interface-group;`
      }
 
```

netopeer window:
[2016/11/08 09:49:22.303862, 3] ssh_packet_socket_callback:  packet: read type 94 [len=988,padding=18,comp=969,payload=969]
[2016/11/08 09:49:22.304360, 3] ssh_packet_process:  Dispatching handler for packet type 94
[2016/11/08 09:49:22.304392, 3] channel_rcv_data:  Channel receiving 960 bytes data in 0 (local win=1266297 remote win=39567851)
[2016/11/08 09:49:22.304416, 3] channel_default_bufferize:  placing 960 bytes into channel buffer (stderr=0)
[2016/11/08 09:49:22.304441, 3] channel_rcv_data:  Channel windows are now (local win=1265337 remote win=39567851)
[2016/11/08 09:49:22.304471, 3] ssh_channel_read_timeout:  Read (1) buffered : 960 bytes. Window: 1265337
[2016/11/08 09:49:22.304497, 3] ssh_channel_read_timeout:  Read (1) buffered : 959 bytes. Window: 1265337
[2016/11/08 09:49:22.304523, 3] ssh_channel_read_timeout:  Read (1) buffered : 958 bytes. Window: 1265337
[2016/11/08 09:49:22.304547, 3] ssh_channel_read_timeout:  Read (1) buffered : 957 bytes. Window: 1265337
[2016/11/08 09:49:22.304570, 3] ssh_channel_read_timeout:  Read (1) buffered : 956 bytes. Window: 1265337
[2016/11/08 09:49:22.304594, 3] ssh_channel_read_timeout:  Read (1) buffered : 955 bytes. Window: 1265337
[2016/11/08 09:49:22.304621, 3] ssh_channel_read_timeout:  Read (950) buffered : 954 bytes. Window: 1265337
[2016/11/08 09:49:22.304774, 3] ssh_channel_read_timeout:  Read (1) buffered : 4 bytes. Window: 1265337
[2016/11/08 09:49:22.304800, 3] ssh_channel_read_timeout:  Read (1) buffered : 3 bytes. Window: 1265337
[2016/11/08 09:49:22.304825, 3] ssh_channel_read_timeout:  Read (1) buffered : 2 bytes. Window: 1265337
[2016/11/08 09:49:22.304849, 3] ssh_channel_read_timeout:  Read (1) buffered : 1 bytes. Window: 1265337
netopeer2-server[19190]: Session 1: received message:
```
<?xml version="1.0" encoding="UTF-8"?>
<rpc message-id="34"
  xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <edit-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <target>
      <candidate/>
    </target>
    <config><if:interfaces xmlns:if="urn:ietf:params:xml:ns:yang:ietf-interfaces">
          <if:interface nc:operation="merge">
            <if:name>ip-2</if:name>
            <if:description>descr_ip-2-ip2222</if:description>
            <if:type>other</type>
            <interface-config xmlns="http://www.one.com/ns/one-ensemble-interfaces" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="merge">
             <interface-type>int-tun</interface-type>
             <owner-tag>bbb</owner-tag>
             <ip>
                 <ip-addr>10.3.4.5/24</ip-addr>
             </ip>
            </interface-config>
          </if:interface>
         </if:interfaces>
    </config>
  </edit-config>
</rpc>
```
netopeer2-server[19190]: DICT: inserting "rpc" with collision 
netopeer2-server[19190]: DICT: inserting "message-id" with collision 
netopeer2-server[19190]: DICT: inserting "34" with collision 
netopeer2-server[19190]: DICT: inserting (refcount) "urn:ietf:params:xml:ns:netconf:base:1.0"
netopeer2-server[19190]: DICT: inserting (refcount) "edit-config"
netopeer2-server[19190]: DICT: inserting (refcount) "urn:ietf:params:xml:ns:netconf:base:1.0"
netopeer2-server[19190]: DICT: inserting (refcount) "target"
netopeer2-server[19190]: DICT: inserting (refcount) "candidate"
netopeer2-server[19190]: DICT: inserting (refcount) ""
netopeer2-server[19190]: DICT: inserting (refcount) ""
netopeer2-server[19190]: DICT: inserting (refcount) "config"
netopeer2-server[19190]: DICT: inserting (refcount) "interfaces"
netopeer2-server[19190]: DICT: inserting (refcount) "if"
netopeer2-server[19190]: DICT: inserting (refcount) "urn:ietf:params:xml:ns:yang:ietf-interfaces"
netopeer2-server[19190]: DICT: inserting (refcount) "interface"
netopeer2-server[19190]: DICT: inserting "operation" with collision 
netopeer2-server[19190]: DICT: inserting (refcount) "merge"
netopeer2-server[19190]: DICT: inserting (refcount) "name"
netopeer2-server[19190]: DICT: inserting "ip-2" with collision 
netopeer2-server[19190]: DICT: inserting (refcount) "description"
netopeer2-server[19190]: DICT: inserting "descr_ip-2-ip2222" with collision 
netopeer2-server[19190]: DICT: inserting (refcount) "type"
netopeer2-server[19190]: DICT: inserting (refcount) "other"
netopeer2-server[19190]: DICT: inserting (refcount) "interface-config"
netopeer2-server[19190]: DICT: inserting (refcount) "http://www.one.com/ns/adva-ensemble-interfaces"
netopeer2-server[19190]: DICT: inserting (refcount) "nc"
netopeer2-server[19190]: DICT: inserting (refcount) "urn:ietf:params:xml:ns:netconf:base:1.0"
netopeer2-server[19190]: DICT: inserting (refcount) "operation"
netopeer2-server[19190]: DICT: inserting (refcount) "merge"
netopeer2-server[19190]: DICT: inserting (refcount) "interface-type"
netopeer2-server[19190]: DICT: inserting (refcount) "int-tun"
netopeer2-server[19190]: DICT: inserting (refcount) "owner-tag"
netopeer2-server[19190]: DICT: inserting "bbb" with collision 
netopeer2-server[19190]: DICT: inserting (refcount) "ip"
netopeer2-server[19190]: DICT: inserting (refcount) "ip-addr"
netopeer2-server[19190]: DICT: inserting "10.3.4.5/24" with collision 
netopeer2-server[19190]: DICT: inserting (refcount) ""
netopeer2-server[19190]: DICT: inserting (refcount) ""
netopeer2-server[19190]: DICT: inserting (refcount) ""
netopeer2-server[19190]: DICT: inserting (refcount) ""
netopeer2-server[19190]: DICT: inserting (refcount) ""
netopeer2-server[19190]: DICT: inserting (refcount) ""
netopeer2-server[19190]: DICT: inserting (refcount) ""
netopeer2-server[19190]: DICT: inserting (refcount) "merge"
netopeer2-server[19190]: DICT: inserting (refcount) "test-then-set"
netopeer2-server[19190]: DICT: inserting (refcount) "stop-on-error"
netopeer2-server[19190]: Resolving unresolved data nodes and their constraints...
netopeer2-server[19190]: All data nodes and constraints resolved.
netopeer2-server[19190]: XPATH: expression "/ietf-netconf:edit-config/target/*":
netopeer2-server[19190]: XPATH:	Token Operator(Path), in expression "/"
netopeer2-server[19190]: XPATH:	Token NameTest, in expression "ietf-netconf:edit-config"
netopeer2-server[19190]: XPATH:	Token Operator(Path), in expression "/"
netopeer2-server[19190]: XPATH:	Token NameTest, in expression "target"
netopeer2-server[19190]: XPATH:	Token Operator(Path), in expression "/"
netopeer2-server[19190]: XPATH:	Token NameTest, in expression "*"
netopeer2-server[19190]: XPATH: eval_absolute_location_path parsed Operator(Path)[0]
netopeer2-server[19190]: DICT: inserting (refcount) "edit-config"
netopeer2-server[19190]: XPATH: eval_node_test              parsed NameTest[1]
netopeer2-server[19190]: XPATH: eval_relative_location_path parsed Operator(Path)[25]
netopeer2-server[19190]: DICT: inserting (refcount) "target"
netopeer2-server[19190]: XPATH: eval_node_test              parsed NameTest[26]
netopeer2-server[19190]: XPATH: eval_relative_location_path parsed Operator(Path)[32]
netopeer2-server[19190]: DICT: inserting (refcount) "*"
netopeer2-server[19190]: XPATH: eval_node_test              parsed NameTest[33]
netopeer2-server[19190]: XPATH: expression "/ietf-netconf:edit-config/default-operation":
netopeer2-server[19190]: XPATH:	Token Operator(Path), in expression "/"
netopeer2-server[19190]: XPATH:	Token NameTest, in expression "ietf-netconf:edit-config"
netopeer2-server[19190]: XPATH:	Token Operator(Path), in expression "/"
netopeer2-server[19190]: XPATH:	Token NameTest, in expression "default-operation"
netopeer2-server[19190]: XPATH: eval_absolute_location_path parsed Operator(Path)[0]
netopeer2-server[19190]: DICT: inserting (refcount) "edit-config"
netopeer2-server[19190]: XPATH: eval_node_test              parsed NameTest[1]
netopeer2-server[19190]: XPATH: eval_relative_location_path parsed Operator(Path)[25]
netopeer2-server[19190]: DICT: inserting (refcount) "default-operation"
netopeer2-server[19190]: XPATH: eval_node_test              parsed NameTest[26]
netopeer2-server[19190]: XPATH: expression "/ietf-netconf:edit-config/test-option":
netopeer2-server[19190]: XPATH:	Token Operator(Path), in expression "/"
netopeer2-server[19190]: XPATH:	Token NameTest, in expression "ietf-netconf:edit-config"
netopeer2-server[19190]: XPATH:	Token Operator(Path), in expression "/"
netopeer2-server[19190]: XPATH:	Token NameTest, in expression "test-option"
netopeer2-server[19190]: XPATH: eval_absolute_location_path parsed Operator(Path)[0]
netopeer2-server[19190]: DICT: inserting (refcount) "edit-config"
netopeer2-server[19190]: XPATH: eval_node_test              parsed NameTest[1]
netopeer2-server[19190]: XPATH: eval_relative_location_path parsed Operator(Path)[25]
netopeer2-server[19190]: DICT: inserting (refcount) "test-option"
netopeer2-server[19190]: XPATH: eval_node_test              parsed NameTest[26]
netopeer2-server[19190]: XPATH: expression "/ietf-netconf:edit-config/error-option":
netopeer2-server[19190]: XPATH:	Token Operator(Path), in expression "/"
netopeer2-server[19190]: XPATH:	Token NameTest, in expression "ietf-netconf:edit-config"
netopeer2-server[19190]: XPATH:	Token Operator(Path), in expression "/"
netopeer2-server[19190]: XPATH:	Token NameTest, in expression "error-option"
netopeer2-server[19190]: XPATH: eval_absolute_location_path parsed Operator(Path)[0]
netopeer2-server[19190]: DICT: inserting (refcount) "edit-config"
netopeer2-server[19190]: XPATH: eval_node_test              parsed NameTest[1]
netopeer2-server[19190]: XPATH: eval_relative_location_path parsed Operator(Path)[25]
netopeer2-server[19190]: DICT: inserting (refcount) "error-option"
netopeer2-server[19190]: XPATH: eval_node_test              parsed NameTest[26]
netopeer2-server[19190]: XPATH: expression "/ietf-netconf:edit-config/config":
netopeer2-server[19190]: XPATH:	Token Operator(Path), in expression "/"
netopeer2-server[19190]: XPATH:	Token NameTest, in expression "ietf-netconf:edit-config"
netopeer2-server[19190]: XPATH:	Token Operator(Path), in expression "/"
netopeer2-server[19190]: XPATH:	Token NameTest, in expression "config"
netopeer2-server[19190]: XPATH: eval_absolute_location_path parsed Operator(Path)[0]
netopeer2-server[19190]: DICT: inserting (refcount) "edit-config"
netopeer2-server[19190]: XPATH: eval_node_test              parsed NameTest[1]
netopeer2-server[19190]: XPATH: eval_relative_location_path parsed Operator(Path)[25]
netopeer2-server[19190]: DICT: inserting (refcount) "config"
netopeer2-server[19190]: XPATH: eval_node_test              parsed NameTest[26]
netopeer2-server[19190]: Ignoring "operation" attribute in "interface" element.
netopeer2-server[19190]: DICT: inserting (refcount) "other"
netopeer2-server[19190]: DICT: inserting (refcount) "int-tun"
netopeer2-server[19190]: DICT: inserting (refcount) "other"
netopeer2-server[19190]: DICT: inserting (refcount) "int-tun"
netopeer2-server[19190]: EDIT_CONFIG: ds 8318240, defop 1, testopt 0, config:
```
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interface>
    <name>ip-2</name>
    <description>descr_ip-2-ip2222</description>
    <type>other</type>
    <interface-config xmlns="http://www.one.com/ns/one-ensemble-interfaces" nc:operation="merge">
      <interface-type>int-tun</interface-type>
      <owner-tag>bbb</owner-tag>
      <ip>
        <ip-addr>10.3.4.5/24</ip-addr>
      </ip>
    </interface-config>
  </interface>
</interfaces>
```
netopeer2-server[19190]: EDIT_CONFIG: list /ietf-interfaces:interfaces/interface[name='ip-2'], operation 1
netopeer2-server[19190]: (cl_request_process:416) Sending set-item request.
netopeer2-server[19190]: (cl_request_process:438) set-item request sent, waiting for response.
netopeer2-server[19190]: (cl_request_process:460) set-item response received, processing.
netopeer2-server[19190]: EDIT_CONFIG: success (/ietf-interfaces:interfaces/interface[name='ip-2']).
netopeer2-server[19190]: EDIT_CONFIG: leaf /ietf-interfaces:interfaces/interface[name='ip-2']/description, operation 1
netopeer2-server[19190]: (cl_request_process:416) Sending set-item request.
netopeer2-server[19190]: (cl_request_process:438) set-item request sent, waiting for response.
netopeer2-server[19190]: (cl_request_process:460) set-item response received, processing.
netopeer2-server[19190]: EDIT_CONFIG: success (/ietf-interfaces:interfaces/interface[name='ip-2']/description).
netopeer2-server[19190]: EDIT_CONFIG: leaf /ietf-interfaces:interfaces/interface[name='ip-2']/type, operation 1
netopeer2-server[19190]: (cl_request_process:416) Sending set-item request.
netopeer2-server[19190]: (cl_request_process:438) set-item request sent, waiting for response.
netopeer2-server[19190]: (cl_request_process:460) set-item response received, processing.
netopeer2-server[19190]: EDIT_CONFIG: success (/ietf-interfaces:interfaces/interface[name='ip-2']/type).
netopeer2-server[19190]: EDIT_CONFIG: leaf /ietf-interfaces:interfaces/interface[name='ip-2']/one-ensemble-interfaces:interface-config/interface-type, operation 1
netopeer2-server[19190]: (cl_request_process:416) Sending set-item request.
netopeer2-server[19190]: (cl_request_process:438) set-item request sent, waiting for response.
netopeer2-server[19190]: (cl_request_process:460) set-item response received, processing.
netopeer2-server[19190]: EDIT_CONFIG: success (/ietf-interfaces:interfaces/interface[name='ip-2']/one-ensemble-interfaces:interface-config/interface-type).
netopeer2-server[19190]: EDIT_CONFIG: leaf /ietf-interfaces:interfaces/interface[name='ip-2']/one-ensemble-interfaces:interface-config/owner-tag, operation 1
netopeer2-server[19190]: (cl_request_process:416) Sending set-item request.
netopeer2-server[19190]: (cl_request_process:438) set-item request sent, waiting for response.
netopeer2-server[19190]: (cl_request_process:460) set-item response received, processing.
netopeer2-server[19190]: EDIT_CONFIG: success (/ietf-interfaces:interfaces/interface[name='ip-2']/one-ensemble-interfaces:interface-config/owner-tag).
netopeer2-server[19190]: EDIT_CONFIG: leaf /ietf-interfaces:interfaces/interface[name='ip-2']/one-ensemble-interfaces:interface-config/ip/ip-addr, operation 1
netopeer2-server[19190]: (cl_request_process:416) Sending set-item request.
netopeer2-server[19190]: (cl_request_process:438) set-item request sent, waiting for response.
netopeer2-server[19190]: (cl_request_process:460) set-item response received, processing.
netopeer2-server[19190]: EDIT_CONFIG: success (/ietf-interfaces:interfaces/interface[name='ip-2']/one-ensemble-interfaces:interface-config/ip/ip-addr).
netopeer2-server[19190]: (cl_request_process:416) Sending validate request.
netopeer2-server[19190]: (cl_request_process:438) validate request sent, waiting for response.
netopeer2-server[19190]: (cl_request_process:460) validate response received, processing.
netopeer2-server[19190]: (sr_validate:1844) Validate operation failed with 1 error(s).
netopeer2-server[19190]: (cl_request_process:416) Sending discard-changes request.
netopeer2-server[19190]: (cl_request_process:438) discard-changes request sent, waiting for response.
netopeer2-server[19190]: (cl_request_process:460) discard-changes response received, processing.
netopeer2-server[19190]: EDIT_CONFIG: done.
netopeer2-server[19190]: Session 1: sending message:

#92

[2016/11/08 09:49:22.367581, 3] ssh_socket_unbuffered_write:  Enabling POLLOUT for socket
[2016/11/08 09:49:22.367624, 3] packet_send2:  packet: wrote [len=28,padding=13,comp=14,payload=14]
[2016/11/08 09:49:22.367649, 3] channel_write_common:  channel_write wrote 5 bytes
netopeer2-server[19190]: Session 1: sending message:
<rpc-reply message-id="34" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><ok/></rpc-reply>
[2016/11/08 09:49:22.367721, 3] packet_send2:  packet: wrote [len=108,padding=6,comp=101,payload=101]
[2016/11/08 09:49:22.367747, 3] channel_write_common:  channel_write wrote 92 bytes
[2016/11/08 09:49:22.367778, 3] ssh_socket_unbuffered_write:  Enabling POLLOUT for socket
netopeer2-server[19190]: Session 1: sending message:

##

[2016/11/08 09:49:22.367844, 3] packet_send2:  packet: wrote [len=28,padding=14,comp=13,payload=13]
[2016/11/08 09:49:22.367870, 3] channel_write_common:  channel_write wrote 4 bytes
[2016/11/08 09:49:22.367898, 3] ssh_socket_unbuffered_write:  Enabling POLLOUT for socket

-----------------------------------------------
syrepo window:

[DBG] (cm_conn_read_cb:1041) fd 6 readable
[DBG] (cm_conn_read_cb:1054) 84 bytes of data received on fd 6
[DBG] (cm_conn_read_cb:1064) fd 6 would block
[DBG] (cm_conn_in_buff_process:993) New message of size 80 bytes received.
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=2, current count=1.
[DBG] (rp_msg_process:3127) Threads: active=0/4, 1 requests in queue
[DBG] (rp_worker_thread_execute:2855) Thread id=140737299773184 signaled.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=3, count=0.
[DBG] (rp_set_item_req_process:888) Processing set_item request.
[INF] (rp_dt_set_item_wrapper:559) Set item request candidate datastore, xpath: /ietf-interfaces:interfaces/interface[name='ip-2']
[DBG] (dm_load_data_tree_file:659) Loaded module ietf-interfaces: mtime sec=1478520132 nsec=504425281
[DBG] (dm_load_data_tree_file:686) Usage count ietf-interfaces incremented (value=1)
[INF] (dm_load_data_tree_file:692) Data file /etc/sysrepo/data/ietf-interfaces.running loaded successfully
[DBG] (dm_get_data_info:1731) Module ietf-interfaces has been loaded
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=8, current count=1.
[DBG] (cm_msg_enqueue_cb:1650) New message enqueued into CM message queue.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=9, count=0.
[DBG] (cm_conn_out_buff_flush:487) Sending 27 bytes of data.
[DBG] (cm_conn_out_buff_flush:493) 27 bytes of data sent.
[DBG] (cm_conn_read_cb:1041) fd 6 readable
[DBG] (cm_conn_read_cb:1054) 116 bytes of data received on fd 6
[DBG] (cm_conn_read_cb:1064) fd 6 would block
[DBG] (cm_conn_in_buff_process:993) New message of size 112 bytes received.
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=3, current count=1.
[DBG] (rp_msg_process:3127) Threads: active=1/4, 1 requests in queue
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=4, count=0.
[DBG] (rp_set_item_req_process:888) Processing set_item request.
[INF] (rp_dt_set_item_wrapper:559) Set item request candidate datastore, xpath: /ietf-interfaces:interfaces/interface[name='ip-2']/description
[DBG] (dm_get_data_info:1703) Module ietf-interfaces already loaded
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=9, current count=1.
[DBG] (cm_msg_enqueue_cb:1650) New message enqueued into CM message queue.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=0, count=0.
[DBG] (cm_conn_out_buff_flush:487) Sending 27 bytes of data.
[DBG] (cm_conn_out_buff_flush:493) 27 bytes of data sent.
[DBG] (cm_conn_read_cb:1041) fd 6 readable
[DBG] (cm_conn_read_cb:1054) 109 bytes of data received on fd 6
[DBG] (cm_conn_read_cb:1064) fd 6 would block
[DBG] (cm_conn_in_buff_process:993) New message of size 105 bytes received.
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=4, current count=1.
[DBG] (rp_msg_process:3127) Threads: active=1/4, 1 requests in queue
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=5, count=0.
[DBG] (rp_set_item_req_process:888) Processing set_item request.
[INF] (rp_dt_set_item_wrapper:559) Set item request candidate datastore, xpath: /ietf-interfaces:interfaces/interface[name='ip-2']/type
[DBG] (dm_get_data_info:1703) Module ietf-interfaces already loaded
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=0, current count=1.
[DBG] (cm_msg_enqueue_cb:1650) New message enqueued into CM message queue.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=1, count=0.
[DBG] (cm_conn_out_buff_flush:487) Sending 27 bytes of data.
[DBG] (cm_conn_out_buff_flush:493) 27 bytes of data sent.
[DBG] (cm_conn_read_cb:1041) fd 6 readable
[DBG] (cm_conn_read_cb:1054) 152 bytes of data received on fd 6
[DBG] (cm_conn_read_cb:1064) fd 6 would block
[DBG] (cm_conn_in_buff_process:993) New message of size 148 bytes received.
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=5, current count=1.
[DBG] (rp_msg_process:3127) Threads: active=1/4, 1 requests in queue
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=6, count=0.
[DBG] (rp_set_item_req_process:888) Processing set_item request.
[INF] (rp_dt_set_item_wrapper:559) Set item request candidate datastore, xpath: /ietf-interfaces:interfaces/interface[name='ip-2']/adva-ensemble-interfaces:interface-config/interface-type
[DBG] (dm_get_data_info:1703) Module ietf-interfaces already loaded
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=1, current count=1.
[DBG] (cm_msg_enqueue_cb:1650) New message enqueued into CM message queue.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=2, count=0.
[DBG] (cm_conn_out_buff_flush:487) Sending 27 bytes of data.
[DBG] (cm_conn_out_buff_flush:493) 27 bytes of data sent.
[DBG] (cm_conn_read_cb:1041) fd 6 readable
[DBG] (cm_conn_read_cb:1054) 142 bytes of data received on fd 6
[DBG] (cm_conn_read_cb:1064) fd 6 would block
[DBG] (cm_conn_in_buff_process:993) New message of size 138 bytes received.
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=6, current count=1.
[DBG] (rp_msg_process:3127) Threads: active=1/4, 1 requests in queue
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=7, count=0.
[DBG] (rp_set_item_req_process:888) Processing set_item request.
[INF] (rp_dt_set_item_wrapper:559) Set item request candidate datastore, xpath: /ietf-interfaces:interfaces/interface[name='ip-2']/one-ensemble-interfaces:interface-config/owner-tag
[DBG] (dm_get_data_info:1703) Module ietf-interfaces already loaded
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=2, current count=1.
[DBG] (cm_msg_enqueue_cb:1650) New message enqueued into CM message queue.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=3, count=0.
[DBG] (cm_conn_out_buff_flush:487) Sending 30 bytes of data.
[DBG] (cm_conn_out_buff_flush:493) 30 bytes of data sent.
[DBG] (cm_conn_read_cb:1041) fd 6 readable
[DBG] (cm_conn_read_cb:1054) 153 bytes of data received on fd 6
[DBG] (cm_conn_read_cb:1064) fd 6 would block
[DBG] (cm_conn_in_buff_process:993) New message of size 149 bytes received.
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=7, current count=1.
[DBG] (rp_msg_process:3127) Threads: active=1/4, 1 requests in queue
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=8, count=0.
[DBG] (rp_set_item_req_process:888) Processing set_item request.
[INF] (rp_dt_set_item_wrapper:559) Set item request candidate datastore, xpath: /ietf-interfaces:interfaces/interface[name='ip-2']/one-ensemble-interfaces:interface-config/ip/ip-addr
[DBG] (dm_get_data_info:1703) Module ietf-interfaces already loaded
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=3, current count=1.
[DBG] (cm_msg_enqueue_cb:1650) New message enqueued into CM message queue.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=4, count=0.
[DBG] (cm_conn_out_buff_flush:487) Sending 30 bytes of data.
[DBG] (cm_conn_out_buff_flush:493) 30 bytes of data sent.
[DBG] (cm_conn_read_cb:1041) fd 6 readable
[DBG] (cm_conn_read_cb:1054) 28 bytes of data received on fd 6
[DBG] (cm_conn_read_cb:1064) fd 6 would block
[DBG] (cm_conn_in_buff_process:993) New message of size 24 bytes received.
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=8, current count=1.
[DBG] (rp_msg_process:3127) Threads: active=1/4, 1 requests in queue
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=9, count=0.
[DBG] (rp_validate_req_process:1042) Processing validate request.
**[DBG] (dm_ly_log_cb:815) libyang error: When condition "../interface-type = 'int-ip'" not satisfied. (path: /ietf-interfaces:interfaces/interface[name='ip-2']/one-ensemble-interfaces:interface-config/ip)**
[**DBG] (dm_validate_session_data_trees:2125) Validation failed for ietf-interfaces module**
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=4, current count=1.
[DBG] (cm_msg_enqueue_cb:1650) New message enqueued into CM message queue.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=5, count=0.
[DBG] (cm_conn_out_buff_flush:487) Sending 204 bytes of data.
[DBG] (cm_conn_out_buff_flush:493) 204 bytes of data sent.
[DBG] (cm_conn_read_cb:1041) fd 6 readable
[DBG] (cm_conn_read_cb:1054) 28 bytes of data received on fd 6
[DBG] (cm_conn_read_cb:1064) fd 6 would block
[DBG] (cm_conn_in_buff_process:993) New message of size 24 bytes received.
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=9, current count=1.
[DBG] (rp_msg_process:3127) Threads: active=1/4, 1 requests in queue
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=0, count=0.
[DBG] (rp_discard_changes_req_process:1165) Processing discard_changes request.
[DBG] (dm_data_info_free:224) Usage count ietf-interfaces decremented (value=0)
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=5, current count=1.
[DBG] (cm_msg_enqueue_cb:1650) New message enqueued into CM message queue.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=6, count=0.
[DBG] (cm_conn_out_buff_flush:487) Sending 30 bytes of data.
[DBG] (cm_conn_out_buff_flush:493) 30 bytes of data sent.
[DBG] (rp_worker_thread_execute:2843) Thread id=140737299773184 will wait.

**Comment by lukasmacko** [comment]
Hi,
this seems to be Netopeer2 issue. Sysrepo returns an error from sr_validate operation, however, it is not filled to netconf response created by Netopeer2.
I'll report it.

Regards,
Lukas

**Comment by lukasmacko** [comment]
Fixed in `devel-server` branch of Netopeer2
