### ISSUE TITLE
A strange issue：the log print rp_notification_ack_process receive an ack rlt 0，but sysrepo  enter commit timeout process

### ISSUE THREAD

**Issue by ostack** [sysrepo/sysrepo#530]
Hi
we meet A strange issue:the log print rp_notification_ack_process receive an ack rlt 0，but sysrepo enter commit timeout process, the log as follow
@milanlenco 

[DBG] (cm_conn_buffer_expand:459) Input buffer for fd=13 expanded to 1024 bytes.
[DBG] (cm_conn_read_cb:1054) 138 bytes of data received on fd 13
[DBG] (cm_conn_read_cb:1064) fd 13 would block
[DBG] (cm_conn_in_buff_process:993) New message of size 134 bytes received.
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=5, current count=1.
[DBG] (rp_msg_process:3031) Threads: active=0/4, 1 requests in queue
[DBG] (rp_worker_thread_execute:2759) Thread id=139742704199424 signaled.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=6, count=0.
**[DBG] (rp_notification_ack_process:2337) Notification ACK received with result = 0.**
[DBG] (rp_worker_thread_execute:2747) Thread id=139742704199424 will wait.
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=6, current count=1.
[DBG] (rp_msg_process:3031) Threads: active=0/4, 1 requests in queue
[DBG] (cm_delayed_request_cb:279) Delayed request sent to the Request Processor.
[DBG] (rp_worker_thread_execute:2759) Thread id=139742679021312 signaled.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=7, count=0.
**[DBG] (rp_commit_timeout_req_process:2157) Processing commit-timeout request.**
[DBG] (np_commit_notifications_complete:1048) Commit id=1450450093 notifications complete.
[ERR] (np_commit_notifications_complete:1051) Commit timeout for commit id=1450450093.
[DBG] (rp_resume_commit:3075) Commit context in state 6
[INF] (rp_resume_commit:3080) Resuming commit with id 1450450093 continue with abort
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=7, current count=1.
[DBG] (rp_msg_process:3031) Threads: active=1/4, 1 requests in queue
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=8, count=0.
[DBG] (rp_commit_req_process:1093) Processing commit request.
**[DBG] (dm_commit_notify:3046) Sending abort notifications about the changes made in running datastore...**
[DBG] (dm_commit_notify:3103) Deleted: /CopyConfigTest:Mo

**Comment by ostack** [comment]
another strange is : the client receive the failed commit result,but the error info get from response is empty.
wonder if we enter the commit timeout process,the errors set may be empty,as the before process may be without errors,is this will cause the front issue?
the code like : 
`        case DM_COMMIT_NOTIFY_ABORT:
            rc = dm_commit_notify(rp_ctx->dm_ctx, session->dm_session, SR_EV_ABORT, commit_ctx);
            session->state = RP_REQ_FINISHED;
            *errors = c_ctx->errors;    ///the process before may be all ok,there is no errors
            *err_cnt = c_ctx->err_cnt;
            c_ctx->errors = NULL;
            c_ctx->err_cnt = 0;
            pthread_mutex_unlock(&commit_ctx->mutex);
            SR_LOG_DBG_MSG("Commit (8/9): abort notifications sent");
            return SR_ERR_OPERATION_FAILED;`
the log is like
netopeer2-server[115]: **(sr_commit:1896) Commit operation failed with 0 error(s).**

**Comment by ostack** [comment]
I reviewed the log found sysrepo send two different notification to different sock, may be when the time is expired   ,one of the client not send ack to the sys-server. I checked our app code and reviewed the log only find one subscription of  CopyConfigTest model, i do not know why there two different sock to sub the CopyConfigTest  model  change .

**Comment by rastislavszabo** [comment]
Hi,
we would need to see some more information in order to help you. Either provide full sysrepo logs, so that we can see who subscribes for what subtrees, or explain the whole scenario, ideally illustrated with actual  code of your application.
