### ISSUE TITLE
Ops data and container indirection

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#537]
Given this YANG model:

```
module dummy-amp {

  namespace
    "http://example.org/cla-sysrepo/dummy-amp";

  prefix "dummy-amp";

  organization "CESNET";
  contact "photonic@cesnet.cz";
  description "Dummy testing module";

  revision 2016-11-10 {
    description "Testing";
  }

  typedef gain-dB {
    type decimal64 {
      fraction-digits 2;
    }
    description "Gain in dB";
  }

  typedef threshold-power-dBm {
    type union {
      type decimal64 {
        fraction-digits 2;
      }
      type enumeration {
        enum off {
          description "No threshold configured";
        }
      }
    }
    description "Power in dBm";
  }

  typedef temperature-celsius {
    type decimal64 {
      fraction-digits 2;
    }
    description "Teperature in centigrade";
  }

  container amplifier {

    container hwInfo {
      config false;

      leaf vendor {
        type string;
        mandatory true;
      }
    }

    container sensors {
      config false;

      leaf case-temperature {
        type temperature-celsius;
        mandatory true;
      }
      leaf pump-on {
        type boolean;
        mandatory true;
      }
    }

    leaf operation-mode {
      type enumeration {
        enum off {
          description "Off mode, switched off";
        }
        enum ACC {
          description "Constant current";
        }
        enum APC {
          description "Constant power output";
        }
        enum AGC {
          description "Automatic gain control";
        }
      }
      default off;
      description "Mode in which the amplifiers operate";
    }

    grouping amp-stage {
      leaf agc-gain {
        type gain-dB;
      }
      leaf automatic-laser-shutdown {
        type threshold-power-dBm;
      }

      container sensors {
        config false;

        leaf gain {
          type gain-dB;
          mandatory true;
        }

        leaf signal-loss {
          type boolean;
          mandatory true;
        }
      }
    }


    container stage-1 {
      uses amp-stage;
    }

    container stage-2 {
      uses amp-stage;
    }

  }

}
```

If I call ``Session::get_items`` for ``/dummy-amp:amplifier/stage-1//*`` (or ``/dummy-amp:amplifier/stage-1/*``), the resulting data set only contains ``/dummy-amp:amplifier/stage-1/agc-gain`` and nothing from the ``sensors`` subtree.

When the requested XPath is ``/dummy-amp:amplifier/stage-1/sensors/``, sysrepo throws an error:

```
[INF] (rp_dt_get_values_wrapper:916) Get items request running datastore, xpath: /dummy-amp:amplifier/stage-1/sensors/*
[INF] (dm_load_data_tree_file:727) Data file /home/jkt/work/prog/sysrepo/build/repository/data/dummy-amp.running loaded successfully
../tests/sysrepo-dummy-amp.cpp:71
*d.propertyNames() with.

[INF] (rp_dt_get_values_wrapper:916) Get items request running datastore, xpath: /dummy-amp:amplifier/stage-1/sensors/*
[ERR] (sr_get_items:870) Error by processing of the request.
```

This is with libyang and sysrepo from devel branch (CESNET/libyang@82f6877, sysrepo/sysrepo@ae43d20).

**Comment by jktjkt** [comment]
I suppose that this might be due to https://github.com/sysrepo/sysrepo/issues/509 ?

**Comment by milanlenco** [comment]
Hi,

I couldn't reproduce this issue with the latest version of sysrepo from devel. #509 is fixed in both master and devel.

I tried your model with this startup configuration:
```
<amplifier xmlns="http://example.org/cla-sysrepo/dummy-amp">
  <stage-1>
    <agc-gain>7.5</agc-gain>
  </stage-1>
</amplifier>
```

Modified oper_data_example.c to: https://github.com/milanlenco/sysrepo/blob/537/examples/oper_data_example.c

Run the subscriber:
```
 $ ./oper_data_example 
This application will be a data provider for state data of dummy-amp.
Run the same executable with one (any) argument to request some data.


 ========== SUBSCRIBED FOR PROVIDING OPER DATA ==========
Data for '/dummy-amp:amplifier/stage-1/sensors' requested.
```

And client:
```
$ ./oper_data_example c
Requesting state data of dummy-amp:
/dummy-amp:amplifier/stage-1/agc-gain = 7.5
/dummy-amp:amplifier/stage-1/sensors (container)
/dummy-amp:amplifier/stage-1/sensors/gain = 10.5
/dummy-amp:amplifier/stage-1/sensors/signal-loss = true
```

Also tried with `/dummy-amp:amplifier/stage-1/sensors/*` and experienced no issues.
Maybe you called the request against startup datastore (which doesn't contain state data)? Or maybe there is a bug in C++ bindings?

**Comment by jktjkt** [comment]
Thanks, I think I see where my problem (roughly) is. So far, my code has only provided a config-data CB registered for the top-level ``/dummy-amp:amplifier/``. This works, my CB gets called for both of these requests, and I can return the data:

- ``session->get_item("/dummy-amp:amplifier/sensors/pump-on")`` 
-  ``session->get_items("/dummy-amp:amplifier//*")``

Do I have to explicitly register a callback for each ``config: false`` subtree separately? If I have to register all of these callbacks, then it's probably a bug that sysrepo calls my CB right now.

BTW, my current schema doesn't make use of it, but is sysrepo ready for config data which are not stored in a separate subtree?

Also, it would have been easier for me to find this on my own if SR told me something like "hey, there's no CB for this XPath".

**Comment by milanlenco** [comment]
Sysrepo does support state data mixed with configuration data. During the installation of a module, sysrepo traverses the schema tree and identifies subtrees that contain only state data. If state data are really intertwined with configuration data, then these subtrees may end up being just leafs.

When you request some data, the following steps are executed:

- for each state-data subtree it is determined if it contains any node whose value should be loaded for the request to be satisfied, if not then it is skipped.

- it is checked if there is a subscription that _includes_ this subtree. In other words, you do not need to directly subscribe to an individual subtree. You may subscribe to some predecessor closer to top-level and include more state-data subtrees in one subscription.

- if a state-data subtree is not handled by any subscription than it is skipped and only a debug message is printed:

```
[DBG] (rp_dt_xpath_requests_state_data:696) No data provider found for subtree /dummy-amp:amplifier/stage-1/sensors
[DBG] (rp_dt_xpath_requests_state_data:696) No data provider found for subtree /dummy-amp:amplifier/hwInfo
[DBG] (rp_dt_xpath_requests_state_data:696) No data provider found for subtree /dummy-amp:amplifier/sensors
```

- if a state-data subtree is contained by some active subscriptions, then a request for data is sent to the first one in the list, which may be followed by more requests for nested state-data (xpaths of this requests will point directly to state data, skipping any configuration predecessors).

BTW, (doxygen-formatted) documentation for this topic was added just a week ago: doc/subscriptions.dox

**Comment by jktjkt** [comment]
Thanks, this turned to be a bug in my client code. Thanks for your clarification and for the docs. I try to follow SR's development, but I must have missed the added documentation -- this code of mine was a bit older.
