### ISSUE TITLE
Edit config (Sysrepo + Netopeer2) with grouping failed

### ISSUE THREAD

**Issue by mkarthig** [sysrepo/sysrepo#538]
Hi
      I used sysrepo and netopeer2.  when i tried to do edit config for leaf which is defined inside grouping it is failed. I have attached the logs. please look at it. Thanks in advance.

Yangs used:

please refer the following links. In the first link, i was used bbf-fast yang files. Also used some dependency yang files from 2nd link(IETF) .

https://github.com/BroadbandForum/yang/tree/master/standard

https://github.com/YangModels/yang/tree/master/standard/ietf/RFC

RPC message:
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <edit-config>
    <target>
      <running/>
    </target>
    <config>
      <fast xmlns="urn:bbf:yang:bbf-fast">
        <service>
          <time-division-duplexing-profile>
            <name>test_tdd_1</name>
            <total-symbol-periods>36</total-symbol-periods>
            <downstream-symbol-periods>10</downstream-symbol-periods>
          </time-division-duplexing-profile>
        </service>
      </fast>
    </config>
  </edit-config>
</rpc>

Sysrepod log:

[INF] (sm_session_create:467) New session created successfully, real user=root, effective user=root, session id=1820975578.
[INF] (rp_dt_refresh_session:837) Refresh session request running datastore
[INF] (rp_dt_refresh_session:849) No operation has been performed on this session so far
[INF] (rp_dt_set_item_wrapper:559) Set item request running datastore, xpath: /bbf-fast:fast/service/time-division-duplexing-profile[name='test_tdd_1']
[INF] (dm_load_data_tree_file:694) Data file /etc/sysrepo/data/bbf-fast.running is empty
[INF] (rp_dt_set_item_wrapper:559) Set item request running datastore, xpath: /bbf-fast:fast/service/time-division-duplexing-profile[name='test_tdd_1']/total-symbol-periods
[INF] (rp_dt_set_item_wrapper:559) Set item request running datastore, xpath: /bbf-fast:fast/service/time-division-duplexing-profile[name='test_tdd_1']/downstream-symbol-periods
[ERR] (rp_dt_commit:694) Data validation failed: Too many instances of "service" in "fast".

**Comment by lukasmacko** [comment]
Hi,

the root cause of the issue is in libyang. I've reported it.

Regards,
Lukas

**Comment by mkarthig** [comment]
ok. Thank you
