### ISSUE TITLE
Is there a way to abort a commit inside a change callback. If so how is this achieved? 

### ISSUE THREAD

**Issue by darren-west** [sysrepo/sysrepo#541]
What is the correct/proposed solution for the following example:
1) I have a subscriber to a module. That subscription callback goes off and attempts to configure some service.
2) The subscriber fails to provide the service for the new configuration.

My question is, does the subscriber hold the callback function from returning and somehow cancel the commit from the callback? (If so how?)

Or does the callback return and then the task fails and it unregisters which un-enables the running configuration store?

**Comment by jktjkt** [comment]
Sounds like you might be looking for the commit validation, see the [announcement](http://lists.sysrepo.org/archives/sysrepo-devel/2016-November/000152.html) and the [docs](http://www.sysrepo.org/static/doc/html/group__cl.html#gga94740180bfd5e1761cccc8e6485eee68acefd1079184ed6d5391264181f72c70e) .

**Comment by lukasmacko** [comment]
The notification callback is called twice. The first time `SR_EV_VERIFY` and subsequently `SR_EV_APPLY` or `SR_EV_ABORT`. If non-zero value is returned by a callback for verify event, the commit is canceled. 

I believe this is the solution you are looking for.

**Comment by darren-west** [comment]
Hi thanks this is.

If i am to return 1 in the SR_EV_VERIFY callback would I then expect that same callback to have an SR_EV_ABORT fired?

Will an SR_EV_ABORT only be fired to notifications created with different sessions?

**Comment by lukasmacko** [comment]
Hi,
by default you'll receive the `SR_EV_ABORT` even if you refused the changes in the callback. If you want `SR_EV_ABORT` only for cases where the config was refused by some other callback use [SR_SUBSCR_NO_ABORT_FOR_REFUSED_CFG](https://github.com/sysrepo/sysrepo/blob/master/inc/sysrepo.h#L1076) flag in subscribe call.

Regards,
Lukas

**Comment by darren-west** [comment]
Hi again,

Thanks. Im guessing there is no way for me to rollback a commit after it has completed?

Regards,
Darren

**Comment by rastislavszabo** [comment]
> Im guessing there is no way for me to rollback a commit after it has completed?

Not yet. This is what  NETCONF confirmed commit is about (https://tools.ietf.org/html/rfc6241#section-8.4), but this is not yet implemented in Sysrepo.
