### ISSUE TITLE
RP_OPER_DATA_REQ_TIMEOUT field should configurable via Cmake 

### ISSUE THREAD

**Issue by bhatkj** [sysrepo/sysrepo#550]
Given that their will be scenarios where in operational data provider callback (i.e.   registered via sr_dp_get_items_subscribe api ) takes longer time to process against  RP_OPER_DATA_REQ_TIMEOUT field which is currently 2 secs.
As Milan Lenčo confirmed that as of now we have only way to change the timeout value is by changing the MACRO.  I believe it would be worth if  RP_OPER_DATA_REQ_TIMEOUT field can be changed via Make options.

**Comment by rastislavszabo** [comment]
fixed in the devel branch
