### ISSUE TITLE
RFC: Daemon sandboxing

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#570]
(This is a question, a request for discussion, not a bug in Sysrepo.)

The ``systemd`` units I contributed earlier implement some rudimentary sandboxing (such as "don't let others mess with sysrepo's ``/tmp``", or "hey, sysrepod probably shouldn't touch the users' homes"). It was trivial to enable this with ``systemd``.

I realize that this is a partially slippery slope -- certain operations performed by (some of the) sysrepo plugins and/or applications (possibly future ones) that are connecting to SR require almost unfiltered root access. Examples of these might be changing the global timezone, rebooting, etc. At the same time, this probably doesn't apply to the main ``sysrepod`` because it "only" marshals access to the configuration store. Maybe it still has to run as root in order for some ACLs to work (does it, actually?), but there's no need for ``sysrepod`` to be able to access raw disk block devices, for example. So from my point of view, it makes sense.

However, I had an interesting problem when doing some local testing. ``sysrepod`` was running (managed by ``systemd`` with ``ProtectHome=yes``, ``ProtectSystem=yes`` etc). I wanted to build and install netopeer2 on that machine, working as in ``/root/blah`` because it was a throwaway VM. When the ``install`` target ran ``sysrepoctl --install blah blah``, ``sysrepod`` actually failed to access the YANG files in root's home because the sandbox provided by ``systemd`` prevented that, as configured.

In context of that, do you think that this sandboxing makes sense? I think so, but I would have a hard time debugging this if I wasn't aware of the security sandbox.

Am I correct in this analysis that ``sysrepoctl --install`` actually talks to ``sysrepod`` and that ``sysrepod`` copies these YANG files on its behalf?

**Comment by rastislavszabo** [comment]
> Maybe it still has to run as root in order for some ACLs to work (does it, actually?)

Yes, sysrepo needs root access for proper access control, uses `setfsuid` / `seteuid` for that. If not running under root, it is not capable of switching user context to the user provided from NETCONF server (`sr_session_start_user`) and the client may get incorrect "unauthorized" errors.

> but there's no need for sysrepod to be able to access raw disk block devices

That's correct.

> In context of that, do you think that this sandboxing makes sense?

It probably is, from filesystem POW it should need full access just to `SR_DATA_SEARCH_DIR` and `SR_SUBSCRIPTIONS_SOCKET_DIR`

> Am I correct in this analysis that sysrepoctl --install actually talks to sysrepod and that sysrepod copies these YANG files on its behalf?

No, `sysrepoctl` copies the files. It talks to `sysrepod` just to inform it about the changes.

**Comment by michalvasko** [comment]
Not relevant anymore.
