### ISSUE TITLE
Skip unit-tests that require daemon not to be running if it's running

### ISSUE THREAD

**Issue by ghost** [sysrepo/sysrepo#579]
I tried to install sysrepo in Ubuntu 14.04
after I entered ctest or sudo make install, I got these error messages:

47% tests passed, 18 tests failed out of 34

Total Test time (real) =   3.53 sec

The following tests FAILED:
         15 - md_test (Failed)
         16 - cm_test (Failed)
         18 - cl_test (Failed)
         19 - cl_notifications_test (Failed)
         20 - cl_state_data_test (Failed)
         21 - cl_fd_watcher_test (Failed)
         22 - concurr_test (OTHER_FAULT)
         23 - perf_test (Failed)
         25 - plugin_daemon_test (Failed)
         26 - sysrepoctl_test (Failed)
         27 - sysrepocfg_test (SEGFAULT)
         28 - python_SysrepoBasicTest (Failed)
         29 - python_SchemasManagementTest (Failed)
         30 - python_LockingTest (Failed)
         31 - python_CommitTest (Failed)
         32 - python_MoveTest (Failed)
         33 - python_SubscriptionTest (Failed)
         34 - python_NotificationTest (Failed)
Errors while running CTest

so I tried to run md_test directly, got the following error message

jxc@jxc-427:~/netconf/sysrepo/build/tests$ ./md_test                                                               [3/1272]
[==========] Running 5 test(s).
[ RUN      ] md_test_init_and_destroy
[       OK ] md_test_init_and_destroy
[ RUN      ] md_test_insert_module
libyang[0]: No resolvents found for leafref "/md_test_module-A:base-container/md_test_module-B:B-ext-leaf". (path: /md_tes$
_module-B:B-data-deps-on-A)
libyang[0]: No resolvents found for leafref "/md_test_module-A:base-container/md_test_module-B:B-ext-leaf". (path: /md_tes$
_module-B:B-data-deps-on-A)
libyang[0]: No resolvents found for leafref "/md_test_module-A:base-container/md_test_module-B:B-ext-leaf". (path: /md_tes$
_module-B:B-data-deps-on-A)
libyang[0]: Module "md_test_module-D" parsing failed.
0 != 0x4
/home/jxc/netconf/sysrepo/tests/md_test.c:1603: error: Failure!

[  FAILED  ] md_test_insert_module
[ RUN      ] md_test_remove_module
0 != 0x3
/home/jxc/netconf/sysrepo/tests/md_test.c:932: error: Failure!

[  FAILED  ] md_test_remove_module
[ RUN      ] md_test_grouping_and_uses
[       OK ] md_test_grouping_and_uses
[ RUN      ] md_test_has_data
[       OK ] md_test_has_data
[==========] 5 test(s) run.
[  PASSED  ] 3 test(s).
[  FAILED  ] 2 test(s), listed below:
[  FAILED  ] md_test_insert_module
[  FAILED  ] md_test_remove_module

 2 FAILED TEST(S)

Did I install some libraries of wrong version?

**Comment by rastislavszabo** [comment]
Hi,
are you sure you are using the newest version of libyang? We use Ubuntu 14.04 on daily basis in CI environment, without any issues.

**Comment by jxc6698** [comment]
I use libyang source code from github(https://github.com/CESNET/libyang).
installed these libs from source code as guide in INSTALL.md:
libssh.so.4.4.0
libnetconf2.so.0.7.35
libprotoc.so.11.0.0
libprotobuf-c.so.1.0.0
libredblack.so.0.2.3
libyang.so.0.11..79

**Comment by lukasmacko** [comment]
after fresh install `cd build; cmake ..; make` the yang models needed for tests should be copied into directory `build/repository/yang` 
could you verify that it contains files like this?
```
cross-module.yang                ietf-ip@2014-06-16.yang       info-module.yang 
module-b@2016-02-05.yang         sub-a-one@2016-02-02.yang     top-level-mandatory.yang
example-module.yang              referenced-data.yang          sub-a-one@2016-02-10.yang     turing-machine@2013-12-27.yang
iana-if-type@2014-05-08.yang     module-a@2016-02-02.yang      small-module.yang             sub-a-two@2016-02-02.yang
ietf-interfaces@2014-05-08.yang  module-a@2016-02-10.yang      state-module@2016-07-01.yang  test-module.yang

**Comment by jxc6698** [comment]
The following is my output  
`
jxc@jxc:~/netconf/sysrepo/build/repository/yang$ ls
cross-module.yang                referenced-data.yang
example-module.yang              small-module.yang
iana-if-type@2014-05-08.yang     state-module@2016-07-01.yang
ietf-interfaces@2014-05-08.yang  sub-a-one@2016-02-02.yang
info-module.yang                 sub-a-one@2016-02-10.yang
internal                         sub-a-two@2016-02-02.yang
module-a@2016-02-02.yang         test-module.yang
module-a@2016-02-10.yang         top-level-mandatory.yang
module-b@2016-02-05.yang         turing-machine@2013-12-27.yang
`
There is one different. You have  ietf-ip@2014-06-16.yang, however I have another directory internal

**Comment by rastislavszabo** [comment]
Hi,
are you still experiencing the issue? Could you please retry to wipe everything and retry with newest versions of all libraries?

**Comment by jxc6698** [comment]
I still have this problem.
I have tried to install sysrepo  in a newly-installed ubunntu 14.04 VM of vmware workstation. but got some other problem. Folloing are errors and  my steps of installation.

```
Errors:
Test project /home/jxc/netconf/sysrepo/build
      Start  1: common_test
 1/15 Test  #1: common_test ......................   Passed    0.09 sec
      Start  2: xpath_utils_test
 2/15 Test  #2: xpath_utils_test .................   Passed    0.03 sec
      Start  3: ac_test
 3/15 Test  #3: ac_test ..........................   Passed    0.03 sec
      Start  4: mem_mgmt_test
 4/15 Test  #4: mem_mgmt_test ....................   Passed    0.02 sec
      Start  5: values_test
 5/15 Test  #5: values_test ......................   Passed    0.02 sec
      Start  6: trees_test
 6/15 Test  #6: trees_test .......................   Passed    0.01 sec
      Start  7: cm_sm_test
 7/15 Test  #7: cm_sm_test .......................   Passed    0.02 sec
      Start  8: np_test
 8/15 Test  #8: np_test ..........................***Failed    0.06 sec
      Start  9: pm_test
 9/15 Test  #9: pm_test ..........................***Failed    0.03 sec
      Start 10: dm_test
10/15 Test #10: dm_test ..........................   Passed    0.16 sec
      Start 11: rp_dt_xpath_test
11/15 Test #11: rp_dt_xpath_test .................   Passed    0.04 sec
      Start 12: rp_datatree_test
12/15 Test #12: rp_datatree_test .................***Failed    0.07 sec
      Start 13: rp_dt_edit_test
13/15 Test #13: rp_dt_edit_test ..................***Failed    0.02 sec
      Start 14: rp_dt_running_test
14/15 Test #14: rp_dt_running_test ...............***Failed    0.04 sec
      Start 15: md_test
15/15 Test #15: md_test ..........................   Passed    0.09 sec

67% tests passed, 5 tests failed out of 15

Total Test time (real) =   0.79 sec

The following tests FAILED:
          8 - np_test (Failed)
          9 - pm_test (Failed)
         12 - rp_datatree_test (Failed)
         13 - rp_dt_edit_test (Failed)
         14 - rp_dt_running_test (Failed)
Errors while running CTest
Makefile:116: recipe for target 'test' failed
make: *** [test] Error 8

Steps:
  1. sudo apt-get install zlib1g-dev zlib1g                                                                              
  2. sudo apt-get install libpcre3 libpcre3-dev                                                                          
  3. sudo apt-get install libssl-dev                                                                                     
  4. sudo apt-get install flex bison                                                                                     
  5. sudo apt-get install cmake libev-dev libavl-dev protobuf-c-compiler                                                 
  6. sudo apt-get install autoconf libtool                                                                               
  7. sudo apt-get install swig python-dev lua5.1 liblua5.1.0-dev

then I installed these libs in git.
Doxygen
cmocka
libssh
libyang
libredblack
protobuf
protobuf-c
libnetconf2 

```

I haven't fixed the errors yet...

**Comment by rastislavszabo** [comment]
I see. you probably have built sysrepo in `Release`, not `Debug` mode, am I right?

**Comment by jxc6698** [comment]
Yes, I built sysrepo in Release.
Just now I tried to build in Debug by running ` cmake -DCMAKE_BUILD_TYPE=Debug ..  `

```
The following tests FAILED:
          8 - np_test (Failed)
          9 - pm_test (Failed)
         12 - rp_datatree_test (Failed)
         13 - rp_dt_edit_test (Failed)
         14 - rp_dt_running_test (Failed)
         16 - cm_test (Failed)
         18 - cl_test (Failed)
         19 - cl_notifications_test (Failed)
         20 - cl_state_data_test (Failed)
         21 - cl_fd_watcher_test (Failed)
         22 - concurr_test (OTHER_FAULT)
         23 - perf_test (Failed)
         27 - sysrepocfg_test (Failed)
         30 - python_LockingTest (Failed)
         31 - python_CommitTest (Failed)
         33 - python_SubscriptionTest (Failed)
         34 - python_NotificationTest (Failed)

```

**Comment by rastislavszabo** [comment]
When running tests, please make sure:
- `sysrepod` is not running
- if you switched from `release` to `debug`, delete the old `build` diretcory and rebuild

**Comment by jxc6698** [comment]
Yes! I get error messages by running `  sudo sysrepo -d ` , even though failed testcase number is up to 27.

```
[ERR] (md_get_module_info:1260) Module 'example-module@<latest>' is not present in the dependency graph.
[ERR] (dm_load_module:572) Module 'example-module:<latest>' is not installed.
[ERR] (dm_get_data_info:1738) Get module 'example-module' failed
[ERR] (rp_dt_prepare_data:802) Getting data tree failed (10) for xpath '/example-module:container/list[key1='key1'][key2='k
ey2']/leaf'
[ERR] (rp_dt_get_value_wrapper:885) rp_dt_prepare_data failed Requested schema model is not known
[ERR] (rp_dt_get_value_wrapper:906) Get value failed for xpath '/example-module:container/list[key1='key1'][key2='key2']/le
af'
[ERR] (rp_get_item_req_process:434) Get item failed for '/example-module:container/list[key1='key1'][key2='key2']/leaf', se
ssion id=337031421.
[ERR] (md_get_module_info:1260) Module 'example-module@<latest>' is not present in the dependency graph.
[ERR] (dm_load_module:572) Module 'example-module:<latest>' is not installed.
[ERR] (dm_get_data_info:1738) Get module 'example-module' failed
[ERR] (rp_dt_prepare_data:802) Getting data tree failed (10) for xpath '/example-module:container/list[key1='key1'][key2='k
ey2']/leaf'
```

**Comment by rastislavszabo** [comment]
OK, so when the daemon is not running, the test are passing, right?

**Comment by jxc6698** [comment]
Yes, I don't know why .......

**Comment by rastislavszabo** [comment]
Some of the tests simply cannot be run when the daemon is running, by their design. I'll track this issue as en enhancement and add a code into them so that they will be skipped in case that daemon is running. Also some of the other tests need to be skipped after building in release mode.

**Comment by jxc6698** [comment]
Er, How to fix my problem, I want to run Netconf2，but I even can not run sysrepo currectly.

**Comment by rastislavszabo** [comment]
You don't need to be executing tests when you want to run Netopeer2. You just need to run the daemon and then you can start Netopeer2. Unit test are aimed just for the development.

If you have trouble installing all libraries yourself, you can use the docker image: https://github.com/sysrepo/sysrepo/tree/master/deploy/docker/sysrepo-netopeer2

**Comment by jxc6698** [comment]
Thanks, I will have a try with that docker image.

**Comment by michalvasko** [comment]
Not relevant anymore.
