### ISSUE TITLE
Implemention of type instance-identifier in function sr_libyang_leaf_copy_value

### ISSUE THREAD

**Issue by zyinter2008** [sysrepo/sysrepo#582]
In function sr_libyang_leaf_copy_value, I note that type instance-identifier has not been implemented yet, code fragment bellow:
```
       case LY_TYPE_INST:
        /* NOT IMPLEMENTED yet*/
        if (NULL != leaf->schema && NULL != leaf->schema->name) {
            SR_LOG_ERR("Copy value failed for leaf '%s'", node_name);
        }
        return SR_ERR_INTERNAL;
```
While, in my opinion, value of type instance-identifier is just similar to string, so I intend to  implement this type as bellow:
```
    case LY_TYPE_INST:
        if (NULL != leaf->value_str) {
            value->type = SR_INSTANCEID_T;
            value->data.instanceid_val = strdup(leaf->value_str);
        }
        else{
            SR_LOG_ERR("Copy value failed for leaf '%s'", node_name);
            return SR_ERR_INTERNAL;
        }
        return SR_ERR_OK;
```
Are there something I have not considered?

**Comment by lukasmacko** [comment]
Hi, 
yes the basic implementation should be as straight-forward as you suggest. The complication is that instance id might point to another module and it requires some changes in validation process.

If you want you can go ahead and implement the basic functionality covered by a unit test that can be placed into [this function](https://github.com/sysrepo/sysrepo/blob/8a318c66599e3ee781875057c5d8515c3d217af2/tests/rp_dt_edit_test.c#L860) once it is done I'll add support for cross-module instance id validation.

Regards,
Lukas

**Comment by rastislavszabo** [comment]
fixed in devel
