### ISSUE TITLE
A socket connect issue：Unexpected error by accepting new connection: Socket operation on non-socket

### ISSUE THREAD

**Issue by ostack** [sysrepo/sysrepo#584]
[1;31m11:25:09:212517  sysrepo_data_repository.cpp:53 : (cl_sm_server_init:1445) Cannot generate server socket path. [0m
[1;31m11:25:09:212533  sysrepo_data_repository.cpp:53 : (cl_subscription_init:302) Cannot initialize Client Subscription Manager. [0m
[1;31m11:25:09:212548  sysrepo_data_repository.cpp:53 : (cl_sm_subscription_cleanup:1807) NULL value detected for subscription argument of cl_sm_subscription_cleanup [0m
[1;31m11:25:09:212563  sysrepo_data_repository.cpp:53 : (sr_module_change_subscribe:2332) Error by initialization of the subscription in the client library. [0m
[1;31m11:25:09:212577  sysrepo_data_repository.cpp:356: Failed to subscribe module 'ModuleTN' (Sysrepo-internal error). [0m
[1;36m11:25:09:212596  sysrepo_data_repository.cpp:403: Initializing ModuleENBFunctionTDD [0m
[1;35m11:25:09:212622  sysrepo_data_repository.cpp:62 : (cl_request_process:417) Sending get-schema request. [0m
[1;35m11:25:09:212646  sysrepo_data_repository.cpp:62 : (cl_request_process:439) get-schema request sent, waiting for response. [0m
[1;35m11:25:09:212969  sysrepo_data_repository.cpp:62 : (cl_request_process:461) get-schema response received, processing. [0m
[1;35m11:25:09:213176  sysrepo_data_repository.cpp:352: sr_module_change_subscribe MODULE[ModuleENBFunctionTDD] [0m
[1;31m11:25:09:213400  sysrepo_data_repository.cpp:53 : (sr_set_socket_dir_permissions:2009) Unable to stat data file for 'ModuleENBFunctionTDD': No such file or directory. [0m
[1;33m11:25:09:213457  sysrepo_data_repository.cpp:56 : (cl_sm_get_server_socket_filename:1394) Attempt to subscribe to unknown 'ModuleENBFunctionTDD' module probably [0m
[1;31m11:25:09:213476  sysrepo_data_repository.cpp:53 : (cl_sm_get_server_socket_filename:1396) Unable to set socket directory permissions for '/tmp/sysrepo-subscriptions/ModuleENBFunctionTDD/'. [0m
[1;31m11:25:09:213490  sysrepo_data_repository.cpp:53 : (cl_sm_server_init:1445) Cannot generate server socket path. [0m
[1;31m11:25:09:213505  sysrepo_data_repository.cpp:53 : (cl_subscription_init:302) Cannot initialize Client Subscription Manager. [0m
[1;31m11:25:09:213533  sysrepo_data_repository.cpp:53 : (cl_sm_subscription_cleanup:1807) NULL value detected for subscription argument of cl_sm_subscription_cleanup [0m
[1;31m11:25:09:213547  sysrepo_data_repository.cpp:53 : (sr_module_change_subscribe:2332) Error by initialization of the subscription in the client library. [0m
[1;31m11:25:09:213567  sysrepo_data_repository.cpp:356: Failed to subscribe module 'ModuleENBFunctionTDD' (Sysrepo-internal error). [0m

[1;35m11:25:24:287608  data_adu_dealer_impl.cpp:22 : config data ADU string is:{"requests":[{"xpath":"/ModuleManagedElement:ManagedElement","operation":"merge","data":{"ManagedElementId":1}}]}. [0m
[1;35m11:25:24:287788  sysrepo_data_repository.cpp:62 : (cl_request_process:417) Sending lock request. [0m
[1;35m11:25:24:287843  sysrepo_data_repository.cpp:62 : (cl_request_process:439) lock request sent, waiting for response. [0m
[1;31m11:25:24:290604  sysrepo_data_repository.cpp:53 : (cl_sm_accept_server_connections:1280) Unexpected error by accepting new connection: Socket operation on non-socket [0m
[1;35m11:25:24:290644  sysrepo_data_repository.cpp:62 : (cl_sm_fd_read_data:1113) fd 12 readable [0m
[1;35m11:25:24:290666  sysrepo_data_repository.cpp:62 : (cl_sm_fd_read_data:1127) 194 bytes of data received on fd 12 [0m
[1;35m11:25:24:290695  sysrepo_data_repository.cpp:62 : (cl_sm_fd_read_data:1137) fd 12 would block [0m
[1;35m11:25:24:290722  sysrepo_data_repository.cpp:62 : (cl_sm_conn_in_buff_process:1063) New message of size 93 bytes received. [0m
[1;35m11:25:24:290724  sysrepo_data_repository.cpp:62 : (cl_request_process:461) lock response received, processing. [0m
[1;35m11:25:24:290777  sysrepo_data_repository.cpp:62 : (cl_sm_notif_process:637) Received a notification for subscription id=1933996016 (source address='/tmp/sysrepod.sock'). [0m
[1;35m11:25:24:290827  sysrepo_data_repository.cpp:62 : (cl_sm_notif_process:706) HELLO notification received on subscription id=1933996016. [0m
[1;35m11:25:24:290851  sysrepo_data_repository.cpp:62 : (cl_sm_conn_in_buff_process:1063) New message of size 93 bytes received. [0m
[1;35m11:25:24:290862  data_adu_dealer_impl.cpp:118: exec config data, operation:merge, xpath:/ModuleManagedElement:ManagedElement, data:{"ManagedElementId":1}. [0m
[1;35m11:25:24:290929  sysrepo_data_repository.cpp:62 : (cl_sm_notif_process:637) Received a notification for subscription id=1933996016 (source address='/tmp/sysrepod.sock'). [0m
[1;35m11:25:24:290956  sysrepo_data_repository.cpp:62 : (cl_sm_notif_process:706) HELLO notification received on subscription id=1933996016. [0m
[1;35m11:25:24:290993  sysrepo_data_repository.cpp:62 : (cl_sm_fd_read_data:1113) fd 15 readable [0m
[1;35m11:25:24:291015  sysrepo_data_repository.cpp:62 : (cl_sm_fd_read_data:1127) 216 bytes of data received on fd 15 [0m
[1;35m11:25:24:291033  sysrepo_data_repository.cpp:62 : (cl_sm_fd_read_data:1137) fd 15 would block [0m
[1;35m11:25:24:291070  sysrepo_data_repository.cpp:62 : (cl_sm_conn_in_buff_process:1063) New message of size 104 bytes received. [0m
[1;35m11:25:24:291099  sysrepo_data_repository.cpp:62 : (cl_sm_notif_process:637) Received a notification for subscription id=1450147820 (source address='/tmp/sysrepod.sock'). [0m
[1;35m11:25:24:291115  sysrepo_data_repository.cpp:62 : (cl_sm_notif_process:706) HELLO notification received on subscription id=1450147820. [0m
[1;35m11:25:24:291134  sysrepo_data_repository.cpp:62 : (cl_sm_conn_in_buff_process:1063) New message of size 104 bytes received. [0m
[1;35m11:25:24:291163  sysrepo_data_repository.cpp:62 : (cl_sm_notif_process:637) Received a notification for subscription id=1450147820 (source address='/tmp/sysrepod.sock'). [0m
[1;35m11:25:24:291188  sysrepo_data_repository.cpp:62 : (cl_sm_notif_process:706) HELLO notification received on subscription id=1450147820. [0m
[1;31m11:25:24:291206  sysrepo_data_repository.cpp:53 : (cl_sm_accept_server_connections:1280) Unexpected error by accepting new connection: Socket operation on non-socket [0m
[1;35m11:25:24:291229  sysrepo_data_repository.cpp:62 : (cl_sm_fd_read_data:1113) fd 14 readable [0m
[1;35m11:25:24:291259  sysrepo_data_repository.cpp:62 : (cl_sm_fd_read_data:1127) 384 bytes of data received on fd 14 [0m
[1;35m11:25:24:291284  sysrepo_data_repository.cpp:62 : (cl_sm_fd_read_data:1137) fd 14 would block [0m
[1;35m11:25:24:291299  sysrepo_data_repository.cpp:62 : (cl_sm_conn_in_buff_process:1063) New message of size 92 bytes received. [0m
[1;35m11:25:24:291316  sysrepo_data_repository.cpp:62 : (cl_sm_notif_process:637) Received a notification for subscription id=1985872251 (source address='/tmp/sysrepod.sock'). [0m
[1;35m11:25:24:291342  sysrepo_data_repository.cpp:62 : (cl_sm_notif_process:706) HELLO notification received on subscription id=1985872251. [0m
[1;35m11:25:24:291365  sysrepo_data_repository.cpp:62 : (cl_sm_conn_in_buff_process:1063) New message of size 92 bytes received. [0m
[1;35m11:25:24:291381  sysrepo_data_repository.cpp:62 : (cl_sm_notif_process:637) Received a notification for subscription id=762721651 (source address='/tmp/sysrepod.sock'). [0m
[1;35m11:25:24:291397  sysrepo_data_repository.cpp:62 : (cl_sm_notif_process:706) HELLO notification received on subscription id=762721651. [0m
[1;35m11:25:24:291421  sysrepo_data_repository.cpp:62 : (cl_sm_conn_in_buff_process:1063) New message of size 92 bytes received. [0m
[1;35m11:25:24:291449  sysrepo_data_repository.cpp:62 : (cl_sm_notif_process:637) Received a notification for subscription id=1985872251 (source address='/tmp/sysrepod.sock'). [0m
[1;35m11:25:24:291472  sysrepo_data_repository.cpp:62 : (cl_sm_notif_process:706) HELLO notification received on subscription id=1985872251. [0m
[1;35m11:25:24:291493  sysrepo_data_repository.cpp:62 : (cl_sm_conn_in_buff_process:1063) New message of size 92 bytes received. [0m
[1;35m11:25:24:291515  sysrepo_data_repository.cpp:62 : (cl_sm_notif_process:637) Received a notification for subscription id=762721651 (source address='/tmp/sysrepod.sock'). [0m
[1;35m11:25:24:291542  sysrepo_data_repository.cpp:62 : (cl_sm_notif_process:706) HELLO notification received on subscription id=762721651. [0m
[1;31m11:25:24:291568  sysrepo_data_repository.cpp:53 : (cl_sm_accept_server_connections:1280) Unexpected error by accepting new connection: Socket operation on non-socket [0m
[1;31m11:25:24:291603  sysrepo_data_repository.cpp:53 : (cl_sm_accept_server_connections:1280) Unexpected error by accepting new connection: Socket operation on non-socket [0m
[1;31m11:25:24:291639  sysrepo_data_repository.cpp:53 : (cl_sm_accept_server_connections:1280) Unexpected error by accepting new connection: Socket operation on non-socket [0m
[1;31m11:25:24:291673  sysrepo_data_repository.cpp:53 : (cl_sm_accept_server_connections:1280) Unexpected error by accepting new connection: Socket operation on non-socket [0m
[1;31m11:25:24:291693  sysrepo_data_repository.cpp:53 : (cl_sm_accept_server_connections:1280) Unexpected error by accepting new connection: Socket operation on non-socket [0m
[1;31m11:25:24:291718  sysrepo_data_repository.cpp:53 : (cl_sm_accept_server_connections:1280) Unexpected error by accepting new connection: Socket operation on non-socket [0m
[1;31m11:25:24:291752  sysrepo_data_repository.cpp:53 : (cl_sm_accept_server_connections:1280) Unexpected error by accepting new connection: Socket operation on non-socket [0m
[1;31m11:25:24:291773  sysrepo_data_repository.cpp:53 : (cl_sm_accept_server_connections:1280) Unexpected error by accepting new connection: Socket operation on non-socket [0m
[1;31m11:25:24:291797  sysrepo_data_repository.cpp:53 : (cl_sm_accept_server_connections:1280) Unexpected error by accepting new connection: Socket operation on non-socket [0m

**Comment by rastislavszabo** [comment]
Hi,
the error itself is most probably a bug in your client code, it seems that you somehow managed to close the file descriptor used for incoming notifications from sysrepo datastore and it has been reused for some other purpose.

I will fix the infinite loop issue with this error.

**Comment by ostack** [comment]
thanks for your quickly replay. 
And  may i ask some questions to understand your explain clearly?
1. is "the file descriptor" indicate the "server_ctx->listen_socket_fd" , and which operation can close it?
2. is "incoming notifications from sysrepo" indicate the event notification call back from sysrepo?

In our code ,we use a session to set items value and we also use the same session in our event notify call back function to query the latest data (before query we use sr_session_refresh the session) ,is this will cause the problem?

thanks

**Comment by rastislavszabo** [comment]
Any `close` syscall in your code could do that. But from the logs that you have added recently to this report, it seems that you are using some older version of sysrepo where sysrepo itself was closing incorrect file descriptors in some cases (due to a recent bug). So please, after this issue gets closed, update to the newest code base and it most probably will be working. If the issue persist, please report it with new logs.

**Comment by ostack** [comment]
OK,thanks
