### ISSUE TITLE
How to launch a processes from a sysrepo-plugind

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#586]
I'm working on a plugin for ietf-system, and I would like to launch a one-shot process in response to a change within a given leaf. I do not want to use ``system(3)`` because I would have to implement escaping myself, so I'm using a ``fork`` and ``execlp``.

Here's some rough code which is executed from my callback:
```C
pid_t pid = fork();
if (pid == -1) {
  // error handling
} else if (pid == 0) {
  execlp(...);
} else {
  int wstatus;
  waitpid(pid, &wstatus, 0);
  // ...
}
```
However, when I ``strace`` this, I see that ``waitpid`` always errors out with en ``ECHILD``. When I instrument the forked child so that it prints out a parent PID, I see that it is not the PID of the thread which called ``fork`` -- for example, the ``sysrepo-plugind`` runs as PID 3237, my callback gets called in thread 3238, it forks a 3239, and 3239's ``getppid()`` returns 3237, *not* 3238.

My POSIX skills are pretty weak :(, so can you please suggest a correct approach here?

**Comment by jktjkt** [comment]
OK, the key was to call ``signal(SIGCHLD, SIG_DFL)`` just before ``fork()``. Is that expected, in other words, are we fine with having to call that function from sysrepo-plgind modules?

**Comment by rastislavszabo** [comment]
Hi,
yes, we are ignoring certain signals in daemons: https://github.com/sysrepo/sysrepo/blob/master/src/common/sr_utils.c#L1928-L1938

Actually, I would have nothing against removing `SIGCHLD` from this list, it shouldn't be harmful for our daemons - and as you write, it can be useful especially for plugins.
