### ISSUE TITLE
GET on container level for oper data reporting Schema node not found error 

### ISSUE THREAD

**Issue by bhatkj** [sysrepo/sysrepo#595]
As a extension to the system-state oper data added new container called system-info 

Sample yang   is as follows:- 
```
augment "/ietf-system:system-state" {
    container system-info {
      config false;
      description
        "System info.";
      uses mgmt-group;
      container software {
        uses  software-group;
      }
}
```

Registered the data provider oper callback for system-state via  sr_dp_get_items_subscribe api. 
For Example:- 
 ```C
sr_dp_get_items_subscribe(session, "/ietf-system:system-state", data_provider_system_cb, NULL,SR_SUBSCR_DEFAULT, &subscription)
```

Now when i am performing the GET via external client like Yangcli , seeing that GET for system-info container making libyang  to report error. However if i do GET at top level like system-state then required data is getting populated. 

For Example:- 
1. Output of GET request at Top level  i.e. service-state which working. 
```
rpc-reply {
  data {
    system-state {
      system-info {
        software {
          device-type Compute
          device-version 'dev161130, Built on Wed 30 Nov 2016 07:42:00 AM EST'
        }
      }
      platform
      platform {
        os-release 1.0
      }
      platform
      platform {
        os-release 1.0
      }
    }
  }
}
```
2. Output of GET request against container level i.e. service-info which reporting an error. 
RPC Data Reply 39 for session 2:

```
rpc-reply {
  data {
  }
}
````
```
[DBG] Thread id=140737300174592 signaled.
[DBG] Circular buffer dequeue, new buffer head=12, count=5.
[DBG] Data provide response received, waiting for 5 more data providers.
[DBG] Received value from data provider for xpath '/ietf-system:system-state/platform/os-release'.
[DBG] Thread id=140737308567296 signaled.
[DBG] Circular buffer dequeue, new buffer head=13, count=4.
[DBG] Module ietf-system already loaded
[DBG] Circular buffer dequeue, new buffer head=14, count=3.
[DBG] Data provide response received, waiting for 4 more data providers.
[DBG] libyang error: Schema node not found.
[ERR] **Schema node not found** for /ietf-system:system-state/system-info
[ERR] Data validation failed.
[WRN] Error by processing of the message: Invalid argument.
[DBG] Circular buffer dequeue, new buffer head=15, count=2.
[DBG] Data provide response received, waiting for 3 more data providers.
[DBG] Received value from data provider for xpath '/ietf-system:system-state/platform/os-release'.
[DBG] Module ietf-system already loaded
[DBG] Circular buffer dequeue, new buffer head=16, count=1.
[DBG] Data provide response received, waiting for 2 more data providers.
[DBG] Circular buffer dequeue, new buffer head=17, count=0.
[DBG] Data provide response received, waiting for 1 more data providers.
[DBG] libyang error: Schema node not found.
[ERR] Schema node not found for /ietf-system:system-state/system-info
[ERR] Data validation failed.
[WRN] Error by processing of the message: Invalid argument.
[DBG] Thread id=140737300174592 will wait.
[DBG] Data provide response received, waiting for 0 more data providers.
[DBG] All data from data providers has been received session id = 1016875259, reenque the request
[DBG] Circular buffer enqueue to position=17, current count=1.
[DBG] Threads: active=1/4, 1 requests in queue
[DBG] Circular buffer dequeue, new buffer head=18, count=0.
[DBG] Processing get_items request.
[INF] Get items request running datastore, xpath: /ietf-system:system-state/system-info
```

**Comment by lukasmacko** [comment]
Hi,

what version/branch of sysrepo do you use?

Could you paste the part of the file
`<your_repository_location>/data/internal/sysrepo-module-dependencies.xml` that contains informations about `ietf-system`

```XML
<module xmlns="urn:ietf:params:xml:ns:yang:sysrepo-module-dependencies">
  <name>ietf-system</name>
  ...
</module>
```

Regards,
Lukas

**Comment by bhatkj** [comment]
Hi,
 It was from Master branch which was pull prior to Nov 16. 
Just wondering do we need to manually edit this ```<your_repository_location>/data/internal/sysrepo-module-dependencies.xml```


```
</module>
<module xmlns="urn:ietf:params:xml:ns:yang:sysrepo-module-dependencies">
  <name>ietf-system</name>
  <revision>2014-08-06</revision>
  <prefix>sys</prefix>
  <namespace>urn:ietf:params:xml:ns:yang:ietf-system</namespace>
  <filepath>/etc/sysrepo/yang/ietf-system@2014-08-06.yang</filepath>
  <latest-revision>true</latest-revision>
  <submodule>false</submodule>
  <implemented>true</implemented>
  <has-data>true</has-data>
  <has-persist>true</has-persist>
  <dependencies>
    <dependency>
      <module-name>ietf-netconf-acm</module-name>
      <module-revision>2012-02-22</module-revision>
      <type>import</type>
    </dependency>
    <dependency>
      <module-name>iana-crypt-hash</module-name>
      <module-revision>2014-08-06</module-revision>
      <type>import</type>
    </dependency>
    <dependency>
      <module-name>company-system</module-name>
      <module-revision>2016-10-06</module-revision>
      <type>extension</type>
    </dependency>
    <dependency>
      <module-name>company-system-info</module-name>
      <module-revision>2016-10-06</module-revision>
      <type>extension</type>
    </dependency>
  </dependencies>
  <op-data-subtrees>
    <op-data-subtree>
      <xpath>/ietf-system:system-state</xpath>
      <orig-module-revision>2014-08-06</orig-module-revision>
      <orig-module-name>ietf-system</orig-module-name>
    </op-data-subtree>
    <op-data-subtree>
      <xpath>/ietf-system:system-state</xpath>
      <orig-module-revision>2016-10-06</orig-module-revision>
      <orig-module-name>company-system-info</orig-module-name>
    </op-data-subtree>
  </op-data-subtrees>
</module>
<module xmlns="urn:ietf:params:xml:ns:yang:sysrepo-module-dependencies">
  <name>company-system-info</name>
  <revision>2016-10-06</revision>
  <prefix>ensemblesysinfo</prefix>
  <namespace>http://www.company.com/ns/company-system-info</namespace>
  <filepath>/etc/sysrepo/yang/company-system-info@2016-10-06.yang</filepath>
  <latest-revision>true</latest-revision>
  <submodule>false</submodule>
  <implemented>true</implemented>
  <has-data>false</has-data>
  <has-persist>false</has-persist>
  <dependencies>
    <dependency>
      <module-name>ietf-system</module-name>
      <module-revision>2014-08-06</module-revision>
      <type>import</type>
    </dependency>
  </dependencies>
</module>
```

**Comment by lukasmacko** [comment]
Hi,

you are definitely not supposed to edit the sysrepo-module-dependencies.xml file manually all changes to this file are done by `sysrepoctl` behind the scenes. I just wanted to check its content since it is valuable for debugging issues like this.

I've idenitified the issue I'll prepare the fix.

regards,
Lukas

**Comment by bhatkj** [comment]
Hi,
 Ok. Thanks for the update. That's what I assuming but wanted to confirm the same.    
Approximately by when fix would be expected to be available ? 

On side note yesterday we have update sysrepo libraries upto below version from master branch
```
commit 6e6624a4c4c1f6530ff367b2e8384bdc923f7275
Merge: 8dbe846 d4d85af
Author: lukasmacko <lmacko1992@gmail.com>
Date:   Wed Nov 30 13:54:40 2016 +0100
    Merge pull request #589 from rastislavszabo/master
    sysrepod / sysrepo-plugind fixes
```
And Following are the few observations against updated libraries. 
1.  now longer system-info container is getting populated even by doing top level like system-state which earlier it use to work. 
2.  As shown in the example of description section, issue of duplicate entries of platform container seems to be resolved.

**Comment by bhatkj** [comment]
Validated the behavior against latest version of sysrepo and I see that no longer leaf are getting populated even though if i we fill the respective leafs within the container.  

Seeing following error message :- 

Dec 12 06:17:26 k_25_18 sysrepo.sh[24592]: [INF] Refresh session request running datastore
Dec 12 06:17:26 k_25_18 sysrepo.sh[24592]: [INF] No operation has been performed on this session so far
Dec 12 06:17:26 k_25_18 sysrepo.sh[24592]: [INF] Get items request running datastore, xpath: /ietf-system:system-state
Dec 12 06:17:26 k_25_18 sysrepo.sh[24592]: [INF] Data file /etc/sysrepo/data/ietf-system.running loaded successfully
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state/system-info/software' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'software'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state/system-info/kernel' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'kernel'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state/system-info/bios' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'bios'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state/system-info/memory' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'memory'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'fans'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state/system-info/temperature' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'temperature'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state/system-info/platform' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'platform'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for os-release
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state/system-info/openstack-services' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'openstack-services'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state/system-info/mac-pools' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'mac-pools'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state' requested-----
Dec 12 06:17:26 k_25_18 sysrepo.sh[24592]: [ERR] Unexpected value with xpath /ietf-system:system-state/platform/os-release received from provider
Dec 12 06:17:26 k_25_18 sysrepo.sh[24592]: [ERR] Data validation failed.
Dec 12 06:17:26 k_25_18 sysrepo.sh[24592]: [WRN] Error by processing of the message: Invalid argument.
Dec 12 06:17:26 k_25_18 sysrepo.sh[24592]: [ERR] Unexpected value with xpath /ietf-system:system-state/platform/os-release received from provider
Dec 12 06:17:26 k_25_18 sysrepo.sh[24592]: [ERR] Data validation failed.
Dec 12 06:17:26 k_25_18 sysrepo.sh[24592]: [WRN] Error by processing of the message: Invalid argument.
Dec 12 06:17:26 k_25_18 sysrepo.sh[24592]: [INF] Get items request running datastore, xpath: /ietf-system:system-state
Dec 12 06:17:26 k_25_18 sysrepo.sh[24592]: [INF] Get items request running datastore, xpath: /ietf-system:system-state//*, offset: 0, limit: 100
Dec 12 06:17:26 k_25_18 sysrepo.sh[24592]: [ERR] Unexpected value with xpath /ietf-system:system-state/platform/os-release received from provider
Dec 12 06:17:26 k_25_18 sysrepo.sh[24592]: [ERR] Data validation failed.
Dec 12 06:17:26 k_25_18 sysrepo.sh[24592]: [WRN] Error by processing of the message: Invalid argument.
Dec 12 06:17:26 k_25_18 sysrepo.sh[24592]: [ERR] Unexpected value with xpath /ietf-system:system-state/platform/os-release received from provider
Dec 12 06:17:26 k_25_18 sysrepo.sh[24592]: [ERR] Data validation failed.
Dec 12 06:17:26 k_25_18 sysrepo.sh[24592]: [WRN] Error by processing of the message: Invalid argument.
Dec 12 06:17:26 k_25_18 sysrepo.sh[24592]: [INF] Get items request running datastore, xpath: /ietf-system:system-state//*, offset: 0, limit: 100
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'bios'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state/system-info/memory' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'memory'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state/system-info/fans' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'fans'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state/system-info/temperature' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'temperature'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state/system-info/platform' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'platform'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for os-release
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state/system-info/openstack-services' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'openstack-services'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state/system-info/mac-pools' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'mac-pools'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'ietf-system:system-state'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'ietf-system:system-state'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state/platform' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'platform'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for os-release
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state/clock' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state/system-info/software' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'software'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state/system-info/kernel' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'kernel'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state/system-info/bios' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'bios'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state/system-info/memory' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'memory'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state/system-info/fans' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'fans'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state/system-info/temperature' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state/system-info/platform' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'platform'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for os-release
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state/system-info/openstack-services' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'openstack-services'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state/system-info/mac-pools' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'mac-pools'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'ietf-system:system-state'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'ietf-system:system-state'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state/system-info/fans' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'fans'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state/system-info/temperature' requested-----
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: callback for ietf-system 'temperature'
Dec 12 06:17:26 k_25_18 ovn_SysRepoSync[25101]: Data for '/ietf-system:system-state/system-info/platform' requested-----

**Comment by lukasmacko** [comment]
According to the logs, it seems that you've provided values for a different subtree. Sysrepo asks for each container/list in a separate call. Do you check xpath that is passed to the callback? https://github.com/sysrepo/sysrepo/blob/master/examples/oper_data_example.c#L44

**Comment by bhatkj** [comment]
Thats weird behavior.  Because I am doing GET on system-state which contains system-info container (i.e. we added) as well.
However in the client i am seeing os-release is getting populated as shown below but in logs reporting error
``` 
Dec 12 06:11:58 k_25_18 sysrepo.sh[24592]: [ERR] Unexpected value with xpath /ietf-system:system-state/platform/os-release received from provider
Dec 12 06:11:58 k_25_18 sysrepo.sh[24592]: [ERR] Data validation failed.
```
```
  rpc-reply {
  data {
    system-state {
      platform {
        os-release 1.0
      }
    }
  }
}
```

**Comment by lukasmacko** [comment]
That's probably because you've returned that value multiple times. It was correctly written when it was provided in callback for container `platform`. However, if it is provided for a different container, than you got an error.

**Comment by rastislavszabo** [comment]
`/ietf-system:system-state/platform/os-release` is an invalid xpath. It should be `/ietf-system:system-state/company-system-info:platform/os-release`

**Comment by bhatkj** [comment]
Ok.  Thanks for the update. Basically platform container exists in /ietf-system:system-state/platform/ and /ietf-system:system-state/company-system-info:system-info/platform. After removing /ietf-system:system-state/company-system-info:system-info/platform container from yang file followed by reloading it  and above error gone. 
**Question :-  So it is mandatory that we shouldn't have same name for the container eventhough each xpath is different?** 

Another cause is that for some reason device-type leaf which of ENUM type is reporting is reporting below error. For quick validation when I used another leaf and it working.

``` 
  [DBG] Received value from data provider for xpath '/ietf-system:system-state/company-system-info:system-info/software/device-type'.
[DBG] Module ietf-system already loaded
[DBG] libyang error: Invalid value "compute" in "device-type" element.
[DBG] libyang error: Failed to create node "connector-type" as a child of "software".
[ERR] Setting of item failed /ietf-system:system-state/company-system-info:system-info/software/device-type 41
[WRN] Failed to set operational data for xpath '/ietf-system:syste
```
