### ISSUE TITLE
Unauthorized errors by NC get, get-config, copy-config

### ISSUE THREAD

**Issue by rastislavszabo** [sysrepo/sysrepo#600]
Suppose a user does not have read access to a module installed in Sysrepo. When performing a `<get>` / `<get-config>` without filters, or `<copy-config>` via Netopeer2, it receives an `Operation not authorized` error.

- for `<get>` / `<get-config>`, data nodes to which the client does not have read access should be silently omitted from the <rpc-reply> message: https://tools.ietf.org/html/rfc6536#section-3.2.2
- for `<copy-config>`, there are some more specific rules: https://tools.ietf.org/html/rfc6536#section-3.2.4

**Comment by antonio-paunovic** [comment]
Solved by #620
