### ISSUE TITLE
`make install` fails with recent libyang

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#603]
Cc: @rkrejci 

libyang commit https://github.com/CESNET/libyang/commit/f32c5f6194923a89cebce99a848a2e9c6a4bbd0f breaks the installation of sysrepo's examples:

```
$ /home/jkt/work/prog/sysrepo/build/src/sysrepocfg --import=/home/jkt/work/prog/sysrepo/examples/yang/ietf-interfaces.data.xml --datastore=startup --format=xml --level=2 ietf-interfaces
[WRN] (sr_connect:423) Sysrepo daemon not detected. Connecting to local Sysrepo Engine.
[WRN] (srcfg_ly_log_cb:82) libyang: Failed to resolve identityref "ethernetCsmacd". (/ietf-interfaces:interfaces/interface[name='eth0']/type)
[ERR] (srcfg_import_datastore:682) Unable to parse the input data: Failed to resolve identityref "ethernetCsmacd". (/ietf-interfaces:interfaces/interface[name='eth0']/type)
```

This happens with the current tip of libyang's devel (https://github.com/CESNET/libyang/commit/f7da1d3f8546ff836ec69eb194be1dfdf366a56c).

**Comment by rastislavszabo** [comment]
Fix is current;y blocked by https://github.com/CESNET/libyang/issues/216 which breaks the Sysrepo functionality.
