### ISSUE TITLE
Free memory error after get  changeset by function sr_get_changes_iter and sr_get_change_next

### ISSUE THREAD

**Issue by zyinter2008** [sysrepo/sysrepo#605]
My code fragment like bellow:

```
    sr_change_iter_t *it = NULL;
    sr_change_oper_t oper;
    sr_val_t *old_value = NULL;
    sr_val_t *new_value = NULL;
    sr_get_changes_iter(session, "/AA:aa/BB:bb", &it);
    while (SR_ERR_OK == sr_get_change_next(session, it, &oper, &old_value, &new_value)) {
       //free memory
       sr_free_val(old_value);
       sr_free_val(new_value);
    }
    sr_free_change_iter(it);
```

When operation is SR_OP_DELETED, sometimes I will get a segment fault when free memory of new_value, when operation is SR_OP_CREATED, the same way with old_value. By gdb debuging, I find that  new_value is a pointer out of bounds. So I modify code in while loop, like bellow:
```
       if(oper == SR_OP_DELETED){
            sr_free_val(old_value);
        }else if(oper == SR_OP_CREATED){
            sr_free_val(new_value);
        }else{
            sr_free_val(old_value);
            sr_free_val(new_value);
        }
```
Is this modification correct?

There are still some points confuse me.
 First is when will I need to call both sr_free_val and sr_free_change_iter to free memory after get changeset, and when will I only need to call sr_free_change_iter? According to you tests in cl_notifications_test.c and cl_test.c files, they are not dealed same way.
Second is according to your code in rp_dt_difflist_to_changes, I know that when operation is SR_OP_DELETED, you only calloc memory for old_value, when operation is SR_OP_CREATE, you only calloc memory for new_value. So in my opinion, when opertion is SR_OP_DELETED and  I call sr_get_changes_iter and sr_get_change_next, I should get a NULL value of new_value, but actually it is a pointer out of bounds.

**Comment by rastislavszabo** [comment]
Hi,
it is a bug, `old_value` / `new_value` should be `NULL` in case it is not used. Your original code fragment should work after fixing this.

**Comment by zyinter2008** [comment]
I also try to modify the code the same way as you, but it not work, the bug still exist, because iter->count equals received_cnt. Then I try to memset like bellow,  it works:
```
            if (iter->count < received_cnt) {
            /* realloc the array for buffered values pointers */
            sr_val_t **tmp = NULL;
            tmp = realloc(iter->new_values, received_cnt * sizeof(*iter->new_values));
            CHECK_NULL_NOMEM_GOTO(tmp, rc, cleanup);
            iter->new_values = tmp;

            tmp = realloc(iter->old_values, received_cnt * sizeof(*iter->old_values));
            CHECK_NULL_NOMEM_GOTO(tmp, rc, cleanup);
            iter->old_values = tmp;

            sr_change_oper_t *oper_tmp = NULL;
            oper_tmp = realloc(iter->operations, received_cnt * sizeof(*iter->operations));
            CHECK_NULL_NOMEM_GOTO(oper_tmp, rc, cleanup);
            iter->operations = oper_tmp;

        }
        iter->index = 0;
        iter->count = received_cnt;

        memset(iter->new_values, 0, received_cnt*sizeof(*iter->new_values));
        memset(iter->old_values, 0, received_cnt*sizeof(*iter->old_values));
```

**Comment by ostack** [comment]
should we set the pointer to null after we free the content  in sr_free_val function?
