### ISSUE TITLE
question about the change of API lyd_dup of libyang

### ISSUE THREAD

**Issue by qmm161** [sysrepo/sysrepo#611]
Hi

libyang require call lyd_validate after calling lyd_dup to rebuid pointer of leafref node . 
https://github.com/CESNET/libyang/issues/212

I modified sysrepo code by add lyd_validate after lyd_dup and I get my bug fixed, but I don't sure if i should create a pull request about this, is sysrepo get other better idea about this?

**Comment by rastislavszabo** [comment]
Hi, please open a pull request so that we can see what you have changed and can discuss it there.

**Comment by qmm161** [comment]
OK
