### ISSUE TITLE
No Longer GET for oper data working against added containers/yang.  

### ISSUE THREAD

**Issue by bhatkj** [sysrepo/sysrepo#624]
Initial i have issue as mentioned in the #595 .  Against the latest version sysrepo (i.e. 5) seeing that now container does get called which is a good thing. However now no longer leafs values are getting populated with the same Data provider api which use to work. The only change which made is that replacement of depreciated api with new (i.e.  changed api **sr_val_set_string** from  **sr_val_set_str_data)** Basically on client side not receiving anything w.r.to against the added container like system-info.  This is the exact same example which is mentioned in the #595. 

Seeing following error message :- 
Dec 12 06:11:58 k_25_18 sysrepo.sh[24592]: [ERR] Unexpected value with xpath /ietf-system:system-state/platform/os-release received from provider
Dec 12 06:11:58 k_25_18 sysrepo.sh[24592]: [ERR] Data validation failed.
Dec 12 06:11:58 k_25_18 sysrepo.sh[24592]: [WRN] Error by processing of the message: Invalid argument.
Dec 12 06:11:58 k_25_18 sysrepo.sh[24592]: [ERR] Unexpected value with xpath /ietf-system:system-state/platform/os-release received from provider
Dec 12 06:11:58 k_25_18 sysrepo.sh[24592]: [ERR] Data validation failed.
Dec 12 06:11:58 k_25_18 sysrepo.sh[24592]: [WRN] Error by processing of the message: Invalid argument.

**Comment by rastislavszabo** [comment]
Hi,
the behavior is correct, according to your information in #595, the `platform` is not part of the `ietf-system` YANG, but `company-system-info` YANG. Therefore, the xpath `/ietf-system:system-state/platform/os-release` is invalid and not accepted by sysrepo.

**Comment by bhatkj** [comment]
Ok.  Thanks for the update. Basically platform container exists in /ietf-system:system-state/platform/ and /ietf-system:system-state/company-system-info:system-info/platform. After removing /ietf-system:system-state/company-system-info:system-info/platform container from yang file followed by reloading it  and above error gone. 
**Question :-  So it is mandatory that we shouldn't have same name for the container eventhough each xpath is different?** 

Another cause is that for some reason device-type leaf which of ENUM type is reporting is reporting below error. For quick validation when I used another leaf and it working.

``` 
  [DBG] Received value from data provider for xpath '/ietf-system:system-state/company-system-info:system-info/software/device-type'.
[DBG] Module ietf-system already loaded
[DBG] libyang error: Invalid value "compute" in "device-type" element.
[DBG] libyang error: Failed to create node "connector-type" as a child of "software".
[ERR] Setting of item failed /ietf-system:system-state/company-system-info:system-info/software/device-type 41
[WRN] Failed to set operational data for xpath '/ietf-system:system-state/company-system-info:system-info/software/device-type'.
```

**Comment by rastislavszabo** [comment]
> So it is mandatory that we shouldn't have same name for the container eventhough each xpath is different?

Yes, it is mandatory to use valid xpaths.

> device-type leaf which of ENUM type is reporting is reporting below error. 

We need to see the YANG model for that leaf.

**Comment by bhatkj** [comment]
True. That's what my understanding was.  Since beginning I want to fill for  /ietf-system:system-state/platform/os-release leaf only.  And it is working correctly.  

Basically os-release leaf belong to default platform container which exists in the default ietf-system/system-state but not to our platform container (i.e. system-info/platform ).

As mentioned earlier just removing the platform container which exists under system-info/platform, error gone.

**Comment by rastislavszabo** [comment]
> True. That's what my understanding was. Since beginning I want to fill for /ietf-system:system-state/platform/os-release leaf only. And it is working correctly.

Good.

> Basically os-release leaf belong to default platform container which exists in the default ietf-system/system-state but not to our platform container (i.e. system-info/platform ).

Yes, and therefore the xpath ` /ietf-system:system-state/platform/os-release` is correct.

> As mentioned earlier just removing the platform container which exists under system-info/platform, error gone.

What error? The error with `/ietf-system:system-state/company-system-info:system-info/software/device-type` enum?

**Comment by rastislavszabo** [comment]
Sorry, but we really need to see the YANG model you are using. Could you please upload it?

**Comment by bhatkj** [comment]
Hi,
 Thank you. Renaming of our platform container other than platform resolves the issue. 
So closing this ticket.
