### ISSUE TITLE
if we do not config data ,we can not get any data by get-config  with "report-all" operation?

### ISSUE THREAD

**Issue by ostack** [sysrepo/sysrepo#626]
if we do not config data ,we can not get any data by get-config with "report-all" operation?

**Comment by lukasmacko** [comment]
I am not sure what you meant exactely but it seems to me like https://github.com/sysrepo/sysrepo/issues/335

**Comment by ostack** [comment]
yes, my concern is same with the issue #335, if the model  has the mandatory leaf and the node data not config, and the query will return nothing

**Comment by rastislavszabo** [comment]
duplicate of #335
