### ISSUE TITLE
SWIG bindings failed to cross-compile

### ISSUE THREAD

**Issue by fabioantonini** [sysrepo/sysrepo#632]
Hi
I'm trying to cross-compile the SWIG bindings support under SYSREPO.
I have already cross-compiled and installed swig-3.0.10 and LUA 5.1.5 libraries.
Then I have enabled the GEN_LANGUAGE_BINDINGS and GEN_LUA_BINDINGS flags in the CMakeLists.txt file.
THis is the output I get during cmake configuration step:
....
**-- Command "/home/fabio/Projects/tiesse/nos/branch-5.4.6.netconf/sources/fusiv-vx185/../tiesse/src/netopeer2/swig-3.0.10/swig -swiglib" failed with output:
/home/fabio/Projects/tiesse/nos/branch-5.4.6.netconf/sources/fusiv-vx185/../tiesse/src/netopeer2/swig-3.0.10/swig: /home/fabio/Projects/tiesse/nos/branch-5.4.6.netconf/sources/fusiv-vx185/../tiesse/src/netopeer2/swig-3.0.10/swig: cannot execute binary file**

CMake Error at swig/CMakeLists.txt:13 (include):
  include called with wrong number of arguments.  include() only takes one
  file.

-- Lua version 5.1 was selected
CMake Error at swig/lua51/CMakeLists.txt:17 (include):
  include called with wrong number of arguments.  include() only takes one
  file.

CMake Error at swig/lua51/CMakeLists.txt:30 (swig_add_module):
  Unknown CMake command "swig_add_module".

The reason should be the following. The cmake file FindSWIG.cmake  (in my linux PC this file is under /usr/share/cmake) is trying to run the swig executable in order to get the swig version.
So it fails. 
Is there any modified version of FindSWIG.cmake to use for cross-compilation?
Is there any workaround to cross-compile SWIG bindings?
Did anyone else try to cross-compile the the swig support under SYSREPO?
Any help will be greatly appreciated
thanks
fabio
fabio

**Comment by rastislavszabo** [comment]
@mislavn Could you please take a look?

**Comment by mislavn** [comment]
OK.

**Comment by mislavn** [comment]
@fabioantonini what you can do for now is to comment out the line:
`find_package(SWIG)`
in the swig/CMakeLists.txt file.

Then you need to manually set the path for:
SWIG_FOUND - set to true if SWIG is found
SWIG_DIR - the directory where swig is installed
SWIG_EXECUTABLE - the path to the swig executable
SWIG_VERSION   - the version number of the swig executable
SWIG_USE_FILE - path to the cmake file.

from cmake. Something like:
cmake -DSWIG_FOUND=true -DSWIG_DIR=/usr/share/swig/3.0.8 -DSWIG_EXECUTABLE=/usr/share/swig -DSWIG_VERSION=3.0.8 -DSWIG_USE_FILE=/usr/local/share/cmake-3.6/Modules/UseSWIG.cmake ..

@fabioantonini if you can send me your setup I could test it myself, preferably via docker.

**Comment by fabioantonini** [comment]
Hi Mislav

Thanksa  lot

I'll get it a try soon

I'll keep you informed

fabio

**Comment by fabioantonini** [comment]
Hi Mislav

some improvement!

The configuration steps has been successfully passed

......

-- *Command 
"/home/fabio/Projects/tiesse/nos/branch-5.4.6.netconf/sources/fusiv-vx185/../tiesse/src/netopeer2/swig-3.0.10/swig 
-swiglib" failed with output:**
**/home/fabio/Projects/tiesse/nos/branch-5.4.6.netconf/sources/fusiv-vx185/../tiesse/src/netopeer2/swig-3.0.10/swig: 
/home/fabio/Projects/tiesse/nos/branch-5.4.6.netconf/sources/fusiv-vx185/../tiesse/src/netopeer2/swig-3.0.10/swig: 
cannot execute binary file*

-- Found SWIG: 
/home/fabio/Projects/tiesse/nos/branch-5.4.6.netconf/sources/fusiv-vx185/../tiesse/src/netopeer2/swig-3.0.10/swig 
(found version "3.0.10")
-- Lua version 5.1 was selected
-- Found Lua51: 
/home/fabio/Projects/tiesse/nos/branch-5.4.6.netconf/sources/fusiv-vx185/../tiesse/src/netopeer2/lua-5.1.5/src/liblua.so;/home/fabio/Projects/tiesse/nos/branch-5.4.6.netconf/sources/fusiv-vx185/../tiesse/src/netopeer2/lua-5.1.5/src/liblua.so 

-- Configuring done
-- Generating done
-- Build files have been written to: 
/home/fabio/Projects/tiesse/nos/branch-5.4.6.netconf/sources/tiesse/src/netopeer2/sysrepo/build

the warning in bold doesn't appear to be blocking

Anyway when I try to compile I get a problem like this

In file included from 
/home/fabio/Projects/tiesse/nos/branch-5.4.6.netconf/sources/tiesse/src/netopeer2/sysrepo/swig/cpp/src/Sysrepo.cpp:26:
/home/fabio/Projects/tiesse/nos/branch-5.4.6.netconf/sources/tiesse/src/netopeer2/sysrepo/swig/cpp/src/Struct.h:41: 
error: 'std::shared_ptr' has not been declared
/home/fabio/Projects/tiesse/nos/branch-5.4.6.netconf/sources/tiesse/src/netopeer2/sysrepo/swig/cpp/src/Struct.h:41: 
error: expected ',' or '...' before '<' token
/home/fabio/Projects/tiesse/nos/branch-5.4.6.netconf/sources/tiesse/src/netopeer2/sysrepo/swig/cpp/src/Struct.h:63: 
error: ISO C++ forbids declaration of 'shared_ptr' with no type
/home/fabio/Projects/tiesse/nos/branch-5.4.6.netconf/sources/tiesse/src/netopeer2/sysrepo/swig/cpp/src/Struct.h:63: 
error: invalid use of '::'
/home/fabio/Projects/tiesse/nos/branch-5.4.6.netconf/sources/tiesse/src/netopeer2/sysrepo/swig/cpp/src/Struct.h:63: 
error: expected ';' before '<' token
/home/fabio/Projects/tiesse/nos/branch-5.4.6.netconf/sources/tiesse/src/netopeer2/sysrepo/swig/cpp/src/Struct.h:71: 
error: 'std::shared_ptr' has not been declared
/home/fabio/Projects/tiesse/nos/branch-5.4.6.netconf/sources/tiesse/src/netopeer2/sysrepo/swig/cpp/src/Struct.h:71: 
error: expected ',' or '...' before '<' token
/home/fabio/Projects/tiesse/nos/branch-5.4.6.netconf/sources/tiesse/src/netopeer2/sysrepo/swig/cpp/src/Struct.h:100: 
error: ISO C++ forbids declaration of 'shared_ptr' with no type


I think that is caused by the limitation of my g++ cross-compiler 
(4.2.8) not supporting c++11 but just c++98. Of course this is not a 
problem of SYSREPO swig binding framework.

So I guess I have to give up

Do you have any advice to workaround the problem according to your 
experience?

Thanks a lot

fabio

**Comment by mislavn** [comment]
> I think that is caused by the limitation of my g++ cross-compiler
> (4.2.8) not supporting c++11 but just c++98. Of course this is not a
> problem of SYSREPO swig binding framework.
> 
> So I guess I have to give up
> 
> Do you have any advice to workaround the problem according to your
> experience?

I am afraid not. The C++ uses C++11 because of the shared pointers and I can't see any workaround for this in the C++ code. You will have to find a workaround with the compiler.

**Comment by fabioantonini** [comment]
Hi Mislav

Thanks a lot for your feedback

At the moment I prefer to give up about the swig support on my current 
platform. Anyway we are working on a new platform whose toolchain is 
more updated and supports the c++11 standard.

If you want I can close the opened issue even if some improvement could 
be done in order to cross compile the swig bindings in SYSREPO.

Please let me know if I can close the issue.

With regards

fabio

**Comment by mislavn** [comment]
Hi Fabio,

could you open a new issue with the proposed changes for the cross compile improvements and close this one.

Regards,
Mislav

**Comment by fabioantonini** [comment]
Hi Mislav

it will be done

thanks

fabio

**Comment by fabioantonini** [comment]
The issue can be closed.
A new ticket will be opened to track of the improvements on the cross compilation of the SWIG bindings in SYSREPO

**Comment by joanlandry** [comment]
I am not sure this is related but each time I make sysrepo I have to copy

cp liblibsysrepoLua51.so libsysrepoLua51.so

as the make install is looking for libsysrepoLua51.so but it does not exist, instead liblibsysrepoLua51.so exists.

So when I copy the file to the correct name – the make install works.

**Comment by mislavn** [comment]
> I am not sure this is related but each time I make sysrepo I have to copy
> 
> cp liblibsysrepoLua51.so libsysrepoLua51.so

This is fixed in the devel branch.
Now cmake does not add "lib" at the start of the target name with the command
`set_target_properties(${SWIG_MODULE_${LUA_SWIG_BINDING}_REAL_NAME} PROPERTIES PREFIX "") `

Cmake would not do this on my machine or on travis so that's why this was not fixed sooner. Also the project name is changed now.

**Comment by fabioantonini** [comment]
Hi Joan

thanks a lot for your advice

It shouldn't be related to the cross-compilation problem I'm facing.

I have closed the issue I opened before and I'm going to open a more 
detailed new one.

Thanks

fabio

**Comment by fabioantonini** [comment]
Hi Mislav

following up our previous discussion, is there any other way to run 
python2 scripts (as rpc_example.py) without swig support. We realized 
that python support as syrepo callback would be really useful

thanks a lot for the attention and best wishes for the new year 2017

with regards

fabio

**Comment by mislavn** [comment]
Hi Fabio

I am afraid it is not possible to use the python2 bindings without SWIG.

The only alternative I can think of is to use cython. At the last IETF hackaton David Lamparter made the cython bindings. Hes code is under the experimental git branch in the folder examples/cyplugin.

https://github.com/sysrepo/sysrepo/tree/experimental/examples/cyplugin

The code is old but you should be able to customize it to your needs.

Regards,
Mislav

**Comment by fabioantonini** [comment]
Hi Mislav

thanks a lot for your help

I'll take a look at this code. Unfortunately we are working with an old 
toolchain  and this is the origin of many limitations. We are developing 
a completely new board with a more update toolchain. So I hope to 
cross-complie swig shortly with a newer c++ compiler.

kind regards

fabio
