### ISSUE TITLE
'when' function parsing failed with namespace prefix

### ISSUE THREAD

**Issue by morganzhh** [sysrepo/sysrepo#636]
Hi,
I have been using libnetconf2+netopeer2+sysrepo to simulator a Network element, when I implement some of my yang files, I would a problem with the 'when' statement.

I have two yang file, one is a, the other is b

a.yang

```yang
module a {

    namespace "http://www.test.com/a";
    prefix "testa";

    identity whoami {
    }

    typedef typewho {
        type identityref {
            base whoami;
        }
    }

    leaf-list who {
        type typewho;
    }
    
    container test {
        leaf first {
            type string;
        }
    }
}
```

b.yang

```yang
module b {
    namespace "http://www.test.com/b";
    prefix "testb";

    import a {prefix "testa"}

    identity iamb {
        base testa:whoami;
    }

    augment "/testa:test" {
        when "count(../testa:who[normalize-space(test())='iamb']) >0" {
        }

        leaf second {
            type string;
        }
    }
}
```

If I use this xml to do the configuration, Sysrepo return failure, according to the log, it's because libyang validation failed:

``Data validation failed: When condition "count(../testa:who[normalize-space(test())='iamb']) >0" not satisfied.``

```xml
<testa:test xmlns:testa="http://www.test.com/a">
<second xmlns="http://www.test.com/b">abcd</second>
</testa:test>
<testa:who xmlns:testb="http://www.test.com/b">testb:iamb</testa:who>
```

And if I use remove namespace prefix, everything works fine

```xml
<testa:test xmlns:testa="http://www.test.com/a">
<second xmlns="http://www.test.com/b">abcd</second>
</testa:test>
<testa:who xmlns="http://www.test.com/b">iamb</testa:who>
```

I am not sure this is the 'yang' file 'when' statement define mistake or a libyang issue?

I also did another test, that I changed the yang file 'when' statement, add a namespace prefix inside when:

the 'when' statement changes from

```yang
when "count(../testa:who[normalize-space(test())='iamb']) >0" {
        }
```

to

```yang
when "count(../testa:who[normalize-space(test())='testb:iamb']) >0" {
        }
```

After doing this, the working case and the not-working case reversed:

This xml works,

```xml
<testa:test xmlns:testa="http://www.test.com/a">
<second xmlns="http://www.test.com/b">abcd</second>
</testa:test>
<testa:who xmlns:testb="http://www.test.com/b">testb:iamb</testa:who>
```
and this failed

```xml
<testa:test xmlns:testa="http://www.test.com/a">
<second xmlns="http://www.test.com/b">abcd</second>
</testa:test>
<testa:who xmlns="http://www.test.com/b">iamb</testa:who>
```

Should I change the yang file 'when' statement, please advise, seems some module should remove the namespace prefix, libyang or sysrepo, please advice, thanks a lot.

**Comment by rastislavszabo** [comment]
Hi,
it seems like a bug in libyang.

**Comment by morganzhh** [comment]
Thanks, I referenced this issue in libyang

**Comment by rastislavszabo** [comment]
fixed in libyang
