### ISSUE TITLE
It It would be very helpful to have callbacks for when a user connects and disconnects

### ISSUE THREAD

**Issue by joanlandry** [sysrepo/sysrepo#647]
From a system level perspective it is important to be able to show who is connected via netconf.

**Comment by rastislavszabo** [comment]
Netopeer2 exposes this information via NETCONF using `ietf-netconf-monitoring.yang`: https://github.com/CESNET/Netopeer2/blob/master/modules/ietf-netconf-monitoring.yang

I think that Sysrepo should expose this information same way - using state data of some YANG model, not via callbacks.

**Comment by vishalwc** [comment]
Does netconf client information ( eg user name etc ) is working via  ietf-netconf-monitoring.yang?

**Comment by michalvasko** [comment]
NETCONF statistics and created/terminated sessions are exposed, not a *sysrepo* issue anyway.
