### ISSUE TITLE
sr_val_to_str / sr_val_to_buff version for sr_node_t

### ISSUE THREAD

**Issue by rastislavszabo** [sysrepo/sysrepo#656]
As discussed in #650, functions similar to `sr_val_to_str` / `sr_val_to_buff` are demanded also for `sr_node_t` type. Since `sr_node_t` can be safely casted to `sr_val_t`, it would be just wrappers over existing functions.

`sr_val_to_str` may need to be changed to return proper error code (this is still an open question).

**Comment by michalvasko** [comment]
Not relevant anymore.
