### ISSUE TITLE
Event-notification problem

### ISSUE THREAD

**Issue by fabioantonini** [sysrepo/sysrepo#658]
Hi all
I have developed a simple application (subscriber) to subscribe some notifications (link-removed and link-discovered described in test-module.yang) and an application to send both of them (sender)

When I try to send the notification from the sender the event is properly sent to the subscriber and the registered callback is called. Anyway from the logs I see these error messages

May 30 13:44:35 sysrepo sysrepo-sysrepo-plugind[5983]: [ERR] (sr_subsciption_type_str_to_gpb:2049) **Unknown type event-notification can not be converted**
May 30 13:44:35 sysrepo last message repeated 2 times
May 30 13:44:35 sysrepo sysrepo-sysrepo-plugind[5984]: [ERR] (sr_subsciption_type_str_to_gpb:2049) **Unknown type event-notification can not be converted**

Is there any problem on the GPB? we are going to use extensively the notifications and I would be fine to be sure that there is no problem under the shell.
Any help will be appreciated
fabio

**Comment by rastislavszabo** [comment]
Hi Fabio,

it should not be harmful, it is already fixed in the devel branch. But I will fix it in master too.

**Comment by fabioantonini** [comment]
Thanks a lot

fabio

**Comment by fabioantonini** [comment]
Hi Rastislav

I have pulled your patch. Those traces disappered. Anyway I get the 
following message each time a call the sender. I have to remark that 
this application sends two notifications (not only one)

May 30 12:33:39 sysrepo sysrepo-sysrepo-plugind[2854]: [WRN] 
(rp_session_stop:3083) There are some (1) unprocessed messages for the 
session id=1398908466 when session stop has been requested, this can 
lead to unspecified behavior - check RP caller code!!!

Probably depends on my application but I would be happy to understand what?

Thanks a lot fot your contiuous support

fabio

**Comment by rastislavszabo** [comment]
Hi Fabio,
in order to debug that one I would need to see the code of your application.

Basically the warning is telling us that in the time of calling session_stop, there is still some unprocessed request for that session - which should not happen.

**Comment by fabioantonini** [comment]
Hi Rastislav

everything is clear now; the sender has to wait some ms before closing 
the session. Probably the second notifications has not been properly 
handled yet when the sender tried to close the session

thanks a lot

fabio

**Comment by fabioantonini** [comment]
I have replied just 10 seconds ago before reading your last mail
