### ISSUE TITLE
callhome feature enable in netconf server module is failing 

### ISSUE THREAD

**Issue by vishalwc** [sysrepo/sysrepo#672]
-bash-4.2$ sysrepoctl --feature-enable=ssh-call-home --module=ietf-netconf-server
Enabling feature 'ssh-call-home' in the module 'ietf-netconf-server'.
[ERR] Error by processing of the request.
Error: The operation failed

am I missing some parameters ?

**Comment by vishalwc** [comment]
I am using devel-server branch ,as the call home was not recognize by sysrepo I enable using the above 
sysrepoctl

-bash-4.2$ sysrepocfg --import=stock_key_config.xml --format=xml --datastore=startup ietf-keystore
The new configuration was successfully applied.
-bash-4.2$ sysrepocfg --import=callhome.xml --format=xml --datastore=startup ietf-netconf-server
[ERR] Data validation failed: Unknown element "call-home".
[ERR] Error by processing of commit request.
[ERR] Error returned from sr_commit: Validation of the changes failed.
[ERR] (null) : Validation of the changes failed
Errors were encountered during importing. Cancelling the operation.

=================callhome.xml file content ====================

<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <call-home>
    <netconf-client>
      <name>main</name>
      <ssh>
        <endpoints>
          <endpoint>
            <name>endpt_name</name>
            <address>127.0.0.1</address>
          </endpoint>
        </endpoints>
        <host-keys>
          <host-key>
          <name>rsa_key</name>
          <public-key>ssh_host_rsa_key</public-key>
          </host-key>
        </host-keys>
      </ssh>
      <connection-type>
        <persistent/>
      </connection-type>
    </netconf-client>
  </call-home>
</netconf-server>

**Comment by rastislavszabo** [comment]
Look at the logs from `sysrepod -d -l4`, they should tell you more.

**Comment by rastislavszabo** [comment]
Or, if daemon is not running, use `sysrepoctl -L4`

**Comment by vishalwc** [comment]
-bash-4.2$ sysrepoctl -L 4 --feature-enable=ssh-call-home  --module=ietf-netconf-server
[DBG] Setting log level for stderr logs to 4.
Enabling feature 'ssh-call-home' in the module 'ietf-netconf-server'.
[DBG] Connecting to Sysrepo Engine.
[DBG] Connecting to socket=/var/run/sysrepod.sock
[INF] Connected to daemon Sysrepo Engine at socket=/var/run/sysrepod.sock
[DBG] Sending session-start request.
[DBG] session-start request sent, waiting for response.
[DBG] session-start response received, processing.
[DBG] Sending feature-enable request.
[DBG] feature-enable request sent, waiting for response.
[DBG] feature-enable response received, processing.
[ERR] Error by processing of the request.
Error: The operation failed

**Comment by rastislavszabo** [comment]
[ERR] Module 'ietf-netconf-server:' is not installed.

**Comment by vishalwc** [comment]
my bad stopped the sysrepod,  yes I realized it and installing it fresh and debugging it

**Comment by vishalwc** [comment]
Now it works fine after cleaning the data file and installing the datastore

Feature 'ssh-call-home' successfully enabled in 'ietf-netconf-server' persist data tree.
[DBG] Capability changes notification for module ietf-netconf-server
[DBG] Generated notification /ietf-netconf-notifications:netconf-capability-change/modified-capability urn:ietf:params:xml:ns:yang:ietf-netconf-server?module=ietf-netconf-server&amp;revision=2016-11-02&amp;features=ssh-call-home
[DBG] Circular buffer enqueue to position=1, current count=1.
[DBG] Threads: active=1/4, 1 requests in queue
[DBG] Circular buffer enqueue to position=0, current count=1.
[DBG] Sending feature-enable notifications, module_name='ietf-netconf-server', feature_name='ssh-call-home', enabled=1.
