### ISSUE TITLE
Invalid order of callbacks for tree modifications

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#675]
The following code attempts to set a leaf of the double64 type:
```C++
session->set_item((modulePrefix + ":amplifier/stage-1/agc-gain").c_str(), std::make_shared<Val>(1234.0));
session->set_item((modulePrefix + ":amplifier/stage-1/agc-gain").c_str(), std::make_shared<Val>(5678.0));
session->set_item((modulePrefix + ":amplifier/stage-1/agc-gain").c_str(), std::make_shared<Val>(1111.0));
session->commit();
```
This now results in only one hit of my callback with value ``1111.0``, in other words, only the last value wins. That's different from how SR behaved before Christmas. Is it an intended change?

However, when my leaf is a union:
```
  typedef threshold-power-dBm {
    type union {
      type decimal64 {
        fraction-digits 2;
      }
      type enumeration {
        enum off {
          description "No threshold configured";
        }
      }
    }
    description "Power in dBm";
  }
```
the following code:
```c++
session->set_item((modulePrefix + ":amplifier/stage-2/automatic-laser-shutdown").c_str(), std::make_shared<Val>(-10.0));
session->set_item((modulePrefix + ":amplifier/stage-1/automatic-laser-shutdown").c_str(), std::make_shared<Val>("off", SR_ENUM_T));
```
...gets two callback events, one with the enum ``off`` followed by a double64 ``10.0``.

What is the intention here? If the last value should win, then the unions should be supported. However, I was under impression that this behavior would only happen if my session was created with a ``DS_CANDIDATE`` datastore. As far as I can tell, I'm using the ``DS_RUNNING`` because that's the behavior of the default ctor in the C++ bindings.

All of this is with CESNET/libyang@b3e69665ca8b6c4a220b400f233c4dd2238d8094 and sysrepo/sysrepo@07174c8f5d86de79ddd7f61d8e4740f86aa2660c .

**Comment by rastislavszabo** [comment]
Yeah, there might have been some change in the `lyd_diff()` function in libyang, which is being used to calculate the difference between the old and the new data tree. Anyway, the order is not important (and not guaranteed), since all the callbacks belong to the same commit operation. If you need some specific order, use `priority` parameter of the `_subscribe` calls.
