### ISSUE TITLE
Can sysrepo offer the non-presence container operation when app use sr_get_changes_iter to get change node?

### ISSUE THREAD

**Issue by ostack** [sysrepo/sysrepo#679]
In our app we want to know the non-presence container  node's operation (modify,create,delete or other), and i found when we use sr_get_changes_iter we only get the  non-presence container 's leaves change info,not contains the container node self change info.

**Comment by lukasmacko** [comment]
I am afraid it will not be possible. This is the difference between presence and non-presence container.

Non-presence container is automatically created if any node inside of it is created and delete once the last node inside of it is removed. In contrast, the presence container must be deleted explicitely even if there is node inside of it.
