### ISSUE TITLE
question：can sysrepo provide a  function to construct  a  sr_val_t  node with input parameter xpath and string value

### ISSUE THREAD

**Issue by ostack** [sysrepo/sysrepo#687]
question：
can sysrepo provide a  function to construct  a  sr_val_t  node with input parameter xpath and string value?

when we use  sysrepo interface to set items we found it is inconvenient to construct the struct sr_val_t, as it has so many type .

in order to give app a convenient function to  construct sr_val_t value , i wonder can sysrepo provide a  function to construct  a  sr_val_t  node with input parameter xpath and string value?

**Comment by milanlenco** [comment]
Hi ostack,

If you use the devel branch of sysrepo, then you can use recently added function `sr_set_item_str` which takes string instead of instance of `sr_val_t`.
As for master, this function will be available in the next release which should come in the late January or early February.

**Comment by ostack** [comment]
Thanks a lot

**Comment by ostack** [comment]
I think it is better to make it as a public function ,as construct sr_val_t it not used in set data, but rpc call back function.
