### ISSUE TITLE
Mandatory statement is not enforced inside an rpc

### ISSUE THREAD

**Issue by stefanopet91** [sysrepo/sysrepo#688]
Hi, I have defined the following rpc:
```
rpc ping {
	input {
		leaf address {
			type string;
			mandatory true;
		}
		leaf number-of-ping {
			type uint8 {
				range "1..3";
			}
			default "2";
		}
	}
	output {
		leaf result {
			type string;
		}
	}
}
```
If I send this rpc without input parameters the rpc is sent and the validation passes, but I would have expected an error message regarding the "address" leaf which is mandatory and it is not present in the request. The function call is:
`sr_rpc_send(session, "/tiesse:ping", NULL, 0,  &rpcoutput, &rpcoutput_cnt);`

If I send the same rpc (without input) with a Netconf client connected to Netopeer2 server, the latter correctly replies with the expected error message.
Thanks

**Comment by lukasmacko** [comment]
fixed/unreproducible with the latest devel branch
