### ISSUE TITLE
sr_get_submodule_schema API call

### ISSUE THREAD

**Issue by lukasmacko** [sysrepo/sysrepo#693]
The API call should be simillar to the sr_get_schema. It should return the content of the submodule. The main difference is that submodule will be identified by the name of the submodule and its(submodule's) revision. 

Currently a submodule different from the newest revision can be retrieved only using sr_get_schema only if the name and the revision of the main module is provided.

**Comment by michalvasko** [comment]
Hi,
we tried to really think the solution to our problem in **netopeer2-server** without this through and learned that it would require a quite complex mechanism compared to the change in **sysrepo**. If you don't have the capacity to implement this we can provide a patch, but we must at least agree on what the public API change will be. Specifically, whether you are fine with changing the prototype of `sr_get_schema()` or would prefer adding a new function `sr_get_submodule_schema()`. Based on the information in this issue I guess the latter, but I will rather ask.

Michal

**Comment by lukasmacko** [comment]
Hi Michal,

I would suggest public API `sr_get_submodule_schema`. (Internally you might be able to reuse some code that is handling `sr_get_schema`, but that's up to you.)
Ping me, if you need something.

Regards,
Lukas

**Comment by michalvasko** [comment]
Hi Lukas,
I have written something that seems to work except I was not able to use it in **netopeer2-server** because even though in the message request `module_name` is `NULL`, the received message has `module_name` set to `""` and I was not able to learn why. Can you please help, provide feedback? Thanks.

[sr_get_submodule_schema.txt](https://github.com/sysrepo/sysrepo/files/729300/sr_get_submodule_schema.txt)

Regards,
Michal

**Comment by lukasmacko** [comment]
Hi Michal,

it will be most probably caused by definition of proto message `required string module_name = 1;` Try to change module name to be optional. You might need to adjust NULL checks after that.

One more thing I've noticed: in the while loop where you are looking for the main_module you should break once you've found a module in the latest revision. Current implementation can potentially lead to the infinite loop.

Apart from that, it seems ok.

Regards,
Lukas

**Comment by michalvasko** [comment]
Hi Lukas,
thanks, that may just be it, I'll try it. Regarding the latest revision, I likely don't understand it well enough, but if they are standard YANG revisions, what do I care whether it is the latest? I am looking for a specific module in a specific revision, it doesn't have to be latest, does it?

Regards,
Michal

**Comment by lukasmacko** [comment]
ah, my bad. It should work as it is, once you reach module that has no inv_deps you should have the module you're looking for. Infinite loop should not be an issue since circular chain of imports is forbidden.

**Comment by michalvasko** [comment]
Hi Lukas,
so after fixing the `module_name` value and a bug in libyang I successfully used it in **netopeer2-server**. Please apply the patch and then I will commit the change into the server as well, thanks.

[patch.txt](https://github.com/sysrepo/sysrepo/files/731946/patch.txt)

Regards,
Michal

**Comment by lukasmacko** [comment]
patched into devel branch. Michal, thanks for your contribution!
