### ISSUE TITLE
can not find the instance identifier which is in the outside of the module.

### ISSUE THREAD

**Issue by WinterZheng** [sysrepo/sysrepo#697]
Refer to the test case " edit_instance_id_test" in edit_instance_id_test.c, it looks like sysrepo doesn't support an instance identifier which is in the outside module. Is it correct?
Sysrepo will raise error logs with "validation failed: Required instance of 'XXXX' does not exists." if I use the outside instance-id.

**Comment by lukasmacko** [comment]
Hi,
it should be already supported in the latest code in devel branch. (in master branch it doesn't work)

Regards,
Lukas

**Comment by WinterZheng** [comment]
Hi Lukas,

I did the test with the devel branch. pleases see my test-case in "edit_instance_id_test" as bellow.

 //TODO: node outside of the module
    value = calloc(1, sizeof(*value));
    assert_non_null(value);
    value->type = SR_INSTANCEID_T;
    value->data.instanceid_val = strdup("/servers:servers");
    assert_non_null(value->data.instanceid_val);

    rc = rp_dt_set_item_wrapper(ctx, session, "/test-module:main/instance_id", value, NULL, SR_EDIT_DEFAULT);
    assert_int_equal(SR_ERR_OK, rc);

    rc = rp_dt_commit(ctx, session, NULL, &errors, &e_cnt);
    assert_int_equal(SR_ERR_OK, rc);

    rc = rp_dt_refresh_session(ctx, session, &errors, &e_cnt);
    assert_int_equal(SR_ERR_OK, rc);

    session->state = RP_REQ_NEW;
    rc = rp_dt_get_value_wrapper(ctx, session, NULL, "/test-module:main/instance_id", &new_val);
    assert_int_equal(SR_ERR_OK, rc);

    assert_string_equal("/servers:servers", new_val->data.instanceid_val);
    sr_free_val(new_val);

I set the 'instance_id' in '/test-module:main" with an outside container node "/servers:servers". This test-case is failed with error logs:
[DBG] (dm_append_data_tree:1510) Dependant module referenced-data is empty
[DBG] (dm_load_dependant_data:1584) Data tree referenced-data appended because of validation
[DBG] (dm_ly_log_cb:971) libyang error: Required instance of "/servers:servers" does not exists.
[DBG] (dm_validate_session_data_trees:2339) Validation failed for test-module module
[ERR] (rp_dt_commit:787) Data validation failed: Required instance of "/servers:servers" does not exists.


Please review the test-case if I made some mistakes.  it looks like libyang doesn't support this case.
Thank you.

**Comment by lukasmacko** [comment]
Hi,

according to the function used in the snippet it seems like a internal unit test. The validation doesn't have to work at that level. Take a look [here](https://github.com/sysrepo/sysrepo/blob/9e78f26ebf46c94ae82f5cbed02a883be842cee0/tests/cl_test.c#L5700-L5767), where public API is used. 

Could you reproduce the issue by modification of the code using public API?

Regards,
Lukas

**Comment by lukasmacko** [comment]
@WinterZheng any update?

**Comment by WinterZheng** [comment]
I update sysrepo and libyang to the latest devel branch, but cannot pass all the cl_test. The cl_test exit without any errors. Can you pass these tests on your system? which libyang version you are using?

Another libyang bug i met after the upgrade. libyang failed parsing a yang file with 'pattern' syntax, such as:

  typedef matchall-string-type {
    type string {
      pattern "\*";
    }
  } 

   typedef Name {
     type string {
       pattern "((\w)+=(\d)+,)*(\w)+=(\d)+";
     }
 }

When I sysrepo install these yang files, libyang raise errors and exit.
[ERR] libyang: Invalid keyword "\*"".
[ERR] libyang: Invalid keyword "((\w)+=(\d)+,)*(\w)+=(\d)+"".

**Comment by michalvasko** [comment]
Hi,
firstly, please enclose code fragments in ```, otherwise what is displayed can be misleading (the first pattern was displayed as "\*" instead "\\*". Now, in both cases *libyang* behaves correctly because you are not encoding backslashes in double-quoted strings as you should ([RFC 6020](https://tools.ietf.org/html/rfc6020#section-6.1.3)). Recently, an errata were added that clarify this issue a bit ([errata](https://www.rfc-editor.org/errata_search.php?rfc=6020) ID 4911). Also, a general good practice is to put all patterns into single quoted strings, in which all the characters are interpreted as they are with no special meaning. So, if you just change the quotes, it should be parsed fine.

Regards,
Michal

**Comment by WinterZheng** [comment]
Thanks Michal. Good shot and suggestions. All my yang files are parsed fine again.

**Comment by WinterZheng** [comment]
It's verified and works fine with latest sysrepo and libyang dev branch. Thanks all.
