### ISSUE TITLE
NETCONF performance testing + documentation

### ISSUE THREAD

**Issue by milanlenco** [sysrepo/sysrepo#708]
It is desirable to analyze the overall performance of sysrepo after the support for NACM was introduced. While NACM was implemented with the performance in mind, it is still possible that some low-throughput points in the execution path may have been left unidentified. Similarly, the memory consumption associated with in-memory YANG schema storage may have increased, albeit only marginally (due to throughput optimizations).

As a part of this task, both usage and performance evaluation of sysrepo's NACM should be documented in doxygen.

**Comment by michalvasko** [comment]
Not relevant anymore.
