### ISSUE TITLE
dp_get_items_subscribe started complaining about trailing slash in an XPath /my-module:top-level-container/

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#709]
Somwhere between fe17fc9 and b20ceb2 ``dp_get_items_subscribe`` started failing if the XPath ends with a slash (or at least if it points to a top-level container within my model). I'm unable to bisect this properly because libyang and sysrepo have both changed their APIs which make ``git bisect`` impractical to use.

I can change our code to eat the trailing slash just fine, but is this intentional?

**Comment by lukasmacko** [comment]
Yes, it is. We have started to validate xpath that are used in subscribe call. It means the usage of xpath including trailing `/`, `/*` or list keys returns an error.

**Comment by jktjkt** [comment]
Thanks.
