### ISSUE TITLE
ModuleChange subscription. Is there a way to load a deleted subtree inside a verify event?

### ISSUE THREAD

**Issue by darren-west** [sysrepo/sysrepo#710]
Hi,

If I am registered to a module changing, when the Verify event fires is there a way to load what the modules configs subtree was before the commit took place?

Thanks in advance

**Comment by lukasmacko** [comment]
Hi,
yes, it is.
Session passed as argument to the callback allows to read the updated configuration. If you use a session different from it, you should be able to read the configuration before commit. You can pass "an auxiliary session" to the callback using private_ctx pointer. 

While testing this solution I have discovered an issue with timeout on reading data files, please wait until https://github.com/sysrepo/sysrepo/pull/714 is merged and then upgrade to the latest version.

Regards,
Lukas

**Comment by darren-west** [comment]
Ah yes, thank you that was the problem i was running into when using a different session.

Thanks alot,
Darren

**Comment by lukasmacko** [comment]
PR was merged, it should work, now.
