### ISSUE TITLE
action validation problem

### ISSUE THREAD

**Issue by michalvasko** [sysrepo/sysrepo#712]
Hi,
I have all the applications from devel branches and running **sysrepod**, **sysrepo-plugind** (with **keystored** installed), and **netopeer2-server** with **netopeer2-cli** connected. I have sent an action using `user-rpc` command with the content (its a valid but testing private key):

```xml
<action xmlns="urn:ietf:params:xml:ns:yang:1">
  <keystore xmlns="urn:ietf:params:xml:ns:yang:ietf-keystore">
    <private-keys>
      <load-private-key>
        <name>server_key</name>
        <private-key>MIIEowIBAAKCAQEAsdI1TBjzX1PgQXFuPCw5/kQwU7qkrhirMcFAXhI8EoXepPa9
fKAVuMjHW32P6nNzDpnhFe0YGdNloIEN3hJJ87cVOqj4o7zZMbq3zVG2L8As7MTA
8tYXm2fSC/0rIxxRRemcGUXM0q+4LEACjZj2pOKonaivF5VbhgNjPCO1Jj/TamUc
0aViE577C9L9EiObGM+bGbabWk/KWKLsvxUc+sKZXaJ7psTVgpggJAkUszlmwOQg
FiMSR53E9/CAkQYhzGVCmH44Vs6Hzs3RZjOTbce4wr4ongiA5LbPeSNSCFjy9loK
paE1rtOjkNBVdiNPCQTmLuODXUTKgkeL+9v/OwIDAQABAoIBAG/4MG1JbL4C/7vV
pBcpth7Aaznd1eJ2UB4VVOWnT8JOH2L6p1h5KRRhAP9AMkXsCnAQPyZiVAG3FlAZ
01SZaY2YJDr6uQ3JVW4155TWtgSdWux//Ass+lJ17lJ0SRxjsV13ez6CsDWeRjc+
2xy0S+KJgqk71XzhJG9fZLYyuddp3U/i3xFPUAcQM9xXKxcaD7g6LJf+a9pt6rim
Eqq/pjJxDgTsRLARsazYuxrlOB445mvnLiYhOf2/MvI80jIUKaj8BeAhg49UIg/k
mIh0xdevkcxBFer/BjBjscWaFjx14D6nkFMw7vtCum5KfalLN2edZKAzByOudGD4
5KnRp3ECgYEA6vnSoNGg9Do80JOpXRGYWhcR1lIDO5yRW5rVagncCcW5Pn/GMtNd
x2q6k1ks8mXKR9CxZrxZGqeYObZ9a/5SLih7ZkpiVWXG8ZiBIPhP6lnwm5OeIqLa
hr0BYWcRfrGg1phj5uySZgsVBE+D8jH42O9ccdvrWv1OiryAHfKIcwMCgYEAwbs+
HfQtvHOQXSYNhtOeA7IetkGy3cKVg2oILNcROvI96hS0MZKt1Rko0UAapx96eCIr
el7vfdT0eUzNqt2wTKp1zmiG+SnX3fMDJNzMwu/jb/b4wQ20IHWNDnqcqTUVRUnL
iksLFoHbTxsN5NpEQExcSt/zzP4qi1W2Bmo18WkCgYEAnhrk16LVux9ohiulHONW
8N9u+BeM51JtGAcxrDzgGo85Gs2czdwc0K6GxdiN/rfxCKtqgqcfCWlVaxfYgo7I
OxiwF17blXx7BVrJICcUlqpX1Ebac5HCmkCYqjJQuj/I6jv1lI7/3rt8M79RF+j5
+PXt7Qq97SZd78nwJrZni4MCgYAiPjZ8lOyAouyhilhZvI3xmUpUbMhw6jQDRnqr
clhZUvgeqAoxuPuA7zGHywzq/WVoVqHYv28Vjs6noiu4R/chlf+8vD0fTYYadRnZ
Ki4HRt+sqrrNZN6x3hVQudt3DSr1VFXl293Z3JonIWETUoE93EFz+qHdWg+rETtb
ZuqiAQKBgD+HI/syLECyO8UynuEaDD7qPl87PJ/CmZLMxa2/ZZUjhaXAW7CJMaS6
9PIzsLk33y3O4Qer0wx/tEdfnxMTBJrgGt/lFFdAKhSJroZ45l5apiavg1oZYp89
jSd0lVxWSmrBjBZLnqOl336gzaBVkBD5ND+XUPdR1UuVQExJlem4</private-key>
      </load-private-key>
    </private-keys>
  </keystore>
</action>
```

Sysrepo returns a validation error. When I tried debugging it I learned that the action is validated twice, the first time successfully, second time not. The reason is that the action is validated without any children. Specifically, `dm_validate_procedure_content` is called with `input` `false` (first time it was `true`) and `data_tree` goes from nodes `keystore` to `load-private-key`, which does not have any children so validation naturally fails.

Regards,
Michal

EDIT: Weren't you trying to validate the reply? It would make sense because there are no output parameters. But in that case you are supposed to just send `ok`, just like in other RPCs without output (`edit-config`, `commit`, whatever...).

**Comment by milanlenco** [comment]
First the request is validated with data that you have posted. Then the output from the callback is also validated (`input = false`). Action `load-private-key` doesn't define any output so the validation for `load-private-key` with no children should succeed in the reply mode (with `LYD_OPT_RPCREPLY`). However, that is not the case as I have reported here: https://github.com/CESNET/libyang/issues/253
