### ISSUE TITLE
SIGCHLD signal in sr_daemonize

### ISSUE THREAD

**Issue by stefanopet91** [sysrepo/sysrepo#723]
Hi,
I have encountered problems using the popen function inside a plugin. Whenever I call the popen the sysrepo-plugind exits and the problem occurs only when not in debug mode.
The problem seems related to the handling of the SIGCHLD signal in the sr_daemonize: https://github.com/sysrepo/sysrepo/blob/master/src/common/sr_utils.c#L2011.
This signal is needed in the parent process in order to handle the forked process but, in my opinion, it should be reset in the child process since it is not used anywhere and it could create issues like in the popen function. 
Thanks

**Comment by michalvasko** [comment]
Hi,
did the commit 623bb44d01bf788a4f8e5c9df51709b944e998b9 fix your issue?

Regards,
Michal

**Comment by antonio-paunovic** [comment]
Hi, 
I was looking at the same bug. For test I've built Release of devel with 623bb44, added popen command in plugin source (turing-machine example) and it worked fine.

**Comment by stefanopet91** [comment]
Yes, it works now. I close it.
Thanks
