### ISSUE TITLE
Priority of subscriptions across modules

### ISSUE THREAD

**Issue by darren-west** [sysrepo/sysrepo#727]
Hi,
I have the following scenario:

1) I have 1 module change subscription to a module say 'module-example-1' with a priority of 10 and i then have another subscription for module changes to a module say 'module-example-2' with a priority of 0.

2) Does the priority work across modules for instance will a single commit that includes changes on module-example-1 and module-example-2 guarantee call the callback for module-example-1 first?

Regards,
Darren

**Comment by rastislavszabo** [comment]
This is a good feature request. Currently priorities work only within a module. We should either make them cross-module, or introduce some priorities of the modules themselves.

**Comment by darren-west** [comment]
Thanks, yes either would be great! 
It will make it possible to have a single commit containing changes to two modules. One of the modules callbacks can then carry out a task that the second modules callback is reliant on.

**Comment by joanlandry** [comment]
Is this issue related to the priority option in sr_module_change_subscribe?
According to the documentation this should apply across modules as sr_module_change_subscribe is for different modules - although it does not work as documented.

What is the priority value suppose to be doing in sr_module_change_subscribe?

**Comment by michalvasko** [comment]
Hi,
based on the code it seems the priority is only used to determine the order of callbacks called in case there are more callbacks for one change.

Regards,
Michal

**Comment by joanlandry** [comment]
I am not sure I understand what you mean by one change. Why would there be multiple callbacks for one change? Isn't the priority a parameter per subscription for a specific module? Any idea what it would take to fix this? We have some ordering issues on different config and so for example would need to be able to receive the creation of an interface before it is used in a higher layer config. Thanks for any input on this.

**Comment by michalvasko** [comment]
There can be 2 daemons that both need to react to a certain configuration change, it does not have to be exact same subtree, but they can have an intersection. The order in which the callbacks are called is fairly strict, so if you have specific requirements, you will likely need to handle them yourself in the callbacks somehow. This issue is left open as an enhancement, which means it would be nice if the priorities are revised and made more useful, but we do not have capacities to implement ourselves, currently.

Regards,
Michal

**Comment by michalvasko** [comment]
Module changes are ordered based on the order in the edit-config.
