### ISSUE TITLE
Applying deleted configuration in a callback with a notification event of APPLY

### ISSUE THREAD

**Issue by darren-west** [sysrepo/sysrepo#728]
Are you able to help with the following scenario?

1) I have a subscription to a module change that receives both apply and verify  notifications stages. 
2) I delete a container tree in the module.
3) I verify the changes and return a SR_ERR_OK. 
4) I now want to get the deleted containers configuration so that I can apply this configuration. i.e. delete what ever was in the container?

Is it expected that I:
Can pull out the required deleted configuration from the change iterator?
Or do I get the required information in the verify stage and pass it to the apply callback?
Or is there some way to get the configuration of the deleted container in the apply stage?

Many thanks in advance!

**Comment by lukasmacko** [comment]
Hi Darren,

- you can read the changes using the change iterator in `SR_EV_APPLY` processing
- you can also do the preparation in the verify stage(in addition to validation of changes) then pass an information using `private_ctx`, afterwards in `SR_EV_APPLY` phase you do just the final step in applying changes

any or combination of both can be used it's up to you

Regards,
Lukas
