### ISSUE TITLE
edit config interfaces

### ISSUE THREAD

**Issue by betsyrosemanuel** [sysrepo/sysrepo#731]
hi, 
 I used sysrepo as my datastore and performed edit-config to the xml in the file attached and got the following error 
[xml_interfa_err.txt](https://github.com/sysrepo/sysrepo/files/759719/xml_interfa_err.txt)

log:[DBG] (rp_worker_thread_execute:2874) Thread id=1976382608 signaled.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=2, count=0.
[DBG] (rp_get_schema_req_process:225) Processing get_schema request.
[INF] (dm_get_schema:2086) Get schema 'ietf-netconf', revision: '(null)', submodule: '(null)'
[ERR] (md_get_module_info:1260) Module 'ietf-netconf@<latest>' is not present in the dependency graph.
[ERR] (dm_get_schema:2106) Module ietf-netconf in revision (null) not found
[DBG] (sr_cbuff_enqueue:461) Circular buffer enqueue to position=3, current count=1.
[DBG] (rp_worker_thread_execute:2862) Thread id=1976382608 will wait.
[DBG] (cm_msg_enqueue_cb:1668) New message enqueued into CM message queue.
[DBG] (sr_cbuff_dequeue:477) Circular buffer dequeue, new buffer head=4, count=0.
[DBG] (cm_conn_out_buff_flush:505) Sending 26 bytes of data.
[DBG] (cm_conn_out_buff_flush:511) 26 bytes of data sent.
[DBG] (cm_conn_read_cb:1059) fd 7 readable
[DBG] (cm_conn_read_cb:1072) 31 bytes of data received on fd 7
[DBG] (cm_conn_read_cb:1082) fd 7 would block
[DBG] (cm_conn_in_buff_process:1011) New message of size 27 bytes received.

**Comment by fabioantonini** [comment]
Hi 
may you check that ietf-netconf.yang has been properly installed by sysrepoctl command?
I need the output of the following command
# sysrepoctl -l

regards
fabio

**Comment by betsyrosemanuel** [comment]
hi,
  This is the log that u asked for

/mnt/nand-persistent/persistent/netconfserver # ./sysrepoctl -l
Sysrepo schema directory: /etc/sysrepo/yang/
Sysrepo data directory:   /etc/sysrepo/data/
(Do not alter contents of these directories manually)

Module Name                   | Revision   | Data Owner          | Permissions | Submodules                    | Enabled Features
---------------------------------------------------------------------------------------------------------------------------------
bbf-fast                      | 2016-09-23 | root:root           | 666         |  bbf-fast-base bbf-fast-data-rate-profile-body bbf-fast-service-profiles bbf-fast-line-spectrum-profile-body bbf-fast-upstream-power-back-off-profile-body bbf-fast-rfi-profile-body bbf-fast-spectrum-profiles bbf-fast-fast-rate-adaptation-profile-body bbf-fast-noise-margin-profile-body bbf-fast-fast-retrain-policy-profile-body bbf-fast-retransmission-profile-body bbf-fast-vectoring-profile-body bbf-fast-quality-profiles bbf-fast-tdd-profile-body bbf-fast-tdd-profiles bbf-fast-perf-types bbf-fast-line-threshold-profile-body bbf-fast-channel-threshold-profile-body bbf-fast-threshold-management bbf-fast-pointers bbf-fast-test-mode-body bbf-fast-update-test-body bbf-fast-link-state-body bbf-fast-line-status-body bbf-fast-read-test-body bbf-fast-test-diagnostics bbf-fast-line-performance-body bbf-fast-channel-performance-body bbf-fast-performance-management bbf-fast-channel-status-body bbf-fast-status-monitoring bbf-fast-ftu-inventory-body bbf-fast-inventory|
ietf-interfaces               | 2014-05-08 | root:root           | 666         |                               |
bbf-fastdsl                   | 2016-07-18 |                     |             |                               |
iana-if-type                  | 2016-06-09 |                     |             |                               |
bbf-yang-types                | 2016-06-08 |                     |             |                               |
ietf-entity                   | 2015-10-19 | root:root           | 666         |                               | entity-config entity-state
ietf-netconf-acm              | 2012-02-22 | root:root           | 666         |                               |
ietf-netconf                  | 2011-06-01 | root:root           | 666         |                               |

**Comment by fabioantonini** [comment]
The ietf-netconf.yang file has been properly installed
can you provide the sysrepod debug messages when it starts?

**Comment by betsyrosemanuel** [comment]
sorry i dont get your question. should i provide the debug messages that i get when the installation of ietf-netconf starts or the message that i get when the xml is sent???

**Comment by fabioantonini** [comment]
when sysrepod is started
# sysrepod -d -l4

**Comment by betsyrosemanuel** [comment]
hi, find below the log of the sysrepod 
[log_sysrepod.txt](https://github.com/sysrepo/sysrepo/files/835793/log_sysrepod.txt)
