### ISSUE TITLE
libyang's behavior change in handling of default values

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#736]
I filed this as a [libyang bug 262](https://github.com/CESNET/libyang/issues/262) originally, and the response there was that sysrepo should be changed. I saw no reaction from SR in there, so let's move the tracking to sysrepo's bugtracker.

Commit CESNET/libyang@e6ff428 introduced a behavior change to sysrepo (I'm at sysrepo/sysrepo@41b05f053bfe798d2a11f01f4d9577f6986450db). I have a registered callback which listens for any change in module ``dummy-amp`` (see below for a whole module). That module has a ``/dummy-amp:amplifier/operation-mode`` which defaults to ``off``. Historically, Sysrepo has been calling my CB when a default value was explicitly assigned to that node, but in sysrepo/sysrepo@6e473b97568dee75b35fd9755f80bbde16e95bda this got changed. When a client started explicitly assigning a default value, the callback was not being executed, which is IMHO quite reasonable. As of CESNET/libyang@e6ff428, though, the callback is firing once again even for changes from "no value, and therefore ``off`` by default" to an "explicit ``off``".

From my point of view, the expected behavior is that I should get no callback when a given leaf changes between an implicit default value and one set explicitly.

**Comment by jktjkt** [comment]
@michalvasko, @rkrejci, is there a chance of you writing a sysrepo patch which ensures that sysrepo won't generate callbacks for toggles between "explicit default" and "implicit default"?

**Comment by michalvasko** [comment]
Hi,
please try out my pull request and write a review in case it works, thanks.

Regards,
Michal

**Comment by rkrejci** [comment]
Fixed by e6a4db8
