### ISSUE TITLE
OpenWrt devel install - sysrepoctl

### ISSUE THREAD

**Issue by petonagy** [sysrepo/sysrepo#738]
Hi,
I got an error when trying to install sysrepo from devel branch for OpenWrt.

`Install the project...
-- Install configuration: "release"
-- Installing: /home/nagy/openWRT/chaos_calmer/openwrt/build_dir/target-i386_pentium4_musl-1.1.16/sysrepo-be8d146bc4c580e9a8914fa94ef1729d1467122b/ipkg-install/etc/sysrepo
-- Installing: /home/nagy/openWRT/chaos_calmer/openwrt/build_dir/target-i386_pentium4_musl-1.1.16/sysrepo-be8d146bc4c580e9a8914fa94ef1729d1467122b/ipkg-install/etc/sysrepo/yang/
-- Installing: /home/nagy/openWRT/chaos_calmer/openwrt/build_dir/target-i386_pentium4_musl-1.1.16/sysrepo-be8d146bc4c580e9a8914fa94ef1729d1467122b/ipkg-install/etc/sysrepo/data/
-- Installing: /home/nagy/openWRT/chaos_calmer/openwrt/build_dir/target-i386_pentium4_musl-1.1.16/sysrepo-be8d146bc4c580e9a8914fa94ef1729d1467122b/ipkg-install/etc/sysrepo/data/internal/
-- Installing: /home/nagy/openWRT/chaos_calmer/openwrt/build_dir/target-i386_pentium4_musl-1.1.16/sysrepo-be8d146bc4c580e9a8914fa94ef1729d1467122b/ipkg-install/var/run/sysrepo-subscriptions
-- Installing: /home/nagy/openWRT/chaos_calmer/openwrt/build_dir/target-i386_pentium4_musl-1.1.16/sysrepo-be8d146bc4c580e9a8914fa94ef1729d1467122b/ipkg-install/usr/lib/sysrepo/plugins
-- Installing: /home/nagy/openWRT/chaos_calmer/openwrt/build_dir/target-i386_pentium4_musl-1.1.16/sysrepo-be8d146bc4c580e9a8914fa94ef1729d1467122b/ipkg-install/etc/sysrepo/yang/internal/sysrepo-persistent-data.yang
-- Installing: /home/nagy/openWRT/chaos_calmer/openwrt/build_dir/target-i386_pentium4_musl-1.1.16/sysrepo-be8d146bc4c580e9a8914fa94ef1729d1467122b/ipkg-install/etc/sysrepo/yang/internal/sysrepo-module-dependencies.yang
-- Installing: /home/nagy/openWRT/chaos_calmer/openwrt/build_dir/target-i386_pentium4_musl-1.1.16/sysrepo-be8d146bc4c580e9a8914fa94ef1729d1467122b/ipkg-install/etc/sysrepo/yang/internal/sysrepo-notification-store.yang
-- Exec: /home/nagy/openWRT/chaos_calmer/openwrt/build_dir/target-i386_pentium4_musl-1.1.16/sysrepo-be8d146bc4c580e9a8914fa94ef1729d1467122b/src/sysrepoctl --install --yang=/home/nagy/openWRT/chaos_calmer/openwrt/build_dir/target-i386_pentium4_musl-1.1.16/sysrepo-be8d146bc4c580e9a8914fa94ef1729d1467122b/yang/ietf-netconf-acm@2012-02-22.yang --permissions=644
CMake Error at cmake_install.cmake:127 (message):
  Error: No such file or directory`

Is there any other solution how to do "sysrepoctl --install ..." functionality manually? I think "sysrepoctl" binary is compiled for OpenWrt and I can't run it on my machine.
Thanks.

Regards,
Peter

**Comment by jktjkt** [comment]
I can confirm that this is a problem for cross-compiling. Our use-case is producing DEBs for ARM on an x86_64 box.

I was thinking about how to fix this some time ago. Option one is to create some auxiliary ``install.cmake`` files and to have them executed by RPM's/DEB's ``postinstall`` phase. That would, however, require extra dependencies, and cmake is very heavy as it brings along a C++ compiler among other things.

Another option is to let cmake generate a trivial ``.sh`` file and to integrate this shell script into the package's ``postinstall`` phase during its build.

In order to make life of developers easier, this can be done by a CMake flag which disables this direct execution and instead produces a script to do it on the target system.

**Comment by mislavn** [comment]
On OpenWrt we moved the sysrepoctl logic to the uci-defaults files.

For on example you could do something like:
https://github.com/sysrepo/openwrt-sysrepo/blob/master/sysrepo-plugin-dt-network/files/network-plugin.default

**Comment by petonagy** [comment]
Thanks Mislav,

I already did it few days ago. I will post a pull request soon.

**Comment by antonio-paunovic** [comment]
Solved by #759.
