### ISSUE TITLE
copy configuration from candidate to running is not working 

### ISSUE THREAD

**Issue by vishalwc** [sysrepo/sysrepo#745]
Connection manager is sending NULL value (as msg argument) to the Request Processor as shown below.

Feb 23 13:47:10 sysrepo[569]: [INF] Switch datastore request candidate -> running
Feb 23 13:47:13 sysrepo[569]: [INF] Resuming commit with id 373832994 continue with write
Feb 23 13:47:13 sysrepo[569]: [ERR] NULL value detected for msg argument of rp_msg_process ----------------------------------------------------->>>> 
Feb 23 13:47:13 sysrepo[569]: [WRN] Error by processing of the message: Invalid argument.

we are on main branch last month updated on our device

**Comment by jktjkt** [comment]
Do you have an example code that can be used to reproduce this?

**Comment by rosy8** [comment]
Hi,
Steps to follow:-
1)edit-config on candidate data store
2)copy-config source=candidate target=running
Right now getting the following log :-1: 
Mar  9 09:40:49  sysrepo[11985]: [DBG] Commit (7/10): verify phase done 
Mar  9 09:40:49  sysrepo[11985]: [DBG] Commit 1302325263 processing paused waiting for replies from verifiers  
    ====>> func:rp_dt_commit ==>>case:-DM_COMMIT_WAIT_FOR_NOTIFICATIONS 
Mar  9 09:40:49  netopeer.sh[12029]: netopeer2-server[12039]: copy-config response received, processing.
Mar  9 09:40:49  netopeer.sh[12029]: netopeer2-server[12039]: Session 1: sending message:
Mar  9 09:40:49  netopeer.sh[12029]: #91
Mar  9 09:40:49  netopeer.sh[12029]: [2017/03/09 09:40:49.248994, 3] ssh_socket_unbuffered_write:  Enabling POLLOUT for socket
Mar  9 09:40:49  netopeer.sh[12029]: [2017/03/09 09:40:49.249026, 3] packet_send2:  packet: wrote [len=28,padding=13,comp=14,payload=14]
Mar  9 09:40:49  netopeer.sh[12029]: [2017/03/09 09:40:49.249048, 3] channel_write_common:  channel_write wrote 5 bytes
Mar  9 09:40:49  netopeer.sh[12029]: netopeer2-server[12039]: Session 1: sending message:
Mar  9 09:40:49  sysrepo[11985]: [DBG] 30 bytes of data sent.
Mar  9 09:40:49  sysrepo[11985]: [DBG] Thread id=140737314612992 will wait.
Mar  9 09:40:49  sysrepo[11985]: [DBG] fd 19 readable
Mar  9 09:40:49  sysrepo[11985]: [DBG] 73 bytes of data received on fd 19
Mar  9 09:40:49  sysrepo[11985]: [DBG] fd 19 would block
Mar  9 09:40:49  sysrepo[11985]: [DBG] New message of size 69 bytes received.
Mar  9 09:40:49  sysrepo[11985]: [DBG] Circular buffer enqueue to position=2, current count=1.
Mar  9 09:40:49  sysrepo[11985]: [DBG] Threads: active=0/4, 1 requests in queue
Mar  9 09:40:49  sysrepo[11985]: [DBG] Thread id=140737297827584 signaled.
Mar  9 09:40:49  sysrepo[11985]: [DBG] Circular buffer dequeue, new buffer head=3, count=0.
Mar  9 09:40:49  sysrepo[11985]: [DBG] Processing get changes request
Mar  9 09:40:49  sysrepo[11985]: [DBG] Get changes: /adva-ensemble-config:ensemble-config limit:100 offset:0 cache miss
Mar  9 09:40:49  sysrepo[11985]: [DBG] Circular buffer enqueue to position=1, current count=1.
Mar  9 09:40:49  sysrepo[11985]: [DBG] Thread id=140737297827584 will wait.
Mar  9 09:40:49  sysrepo[11985]: [DBG] New message enqueued into CM message queue.
Mar  9 09:40:49  sysrepo[11985]: [DBG] Circular buffer dequeue, new buffer head=2, count=0.
Mar  9 09:40:49  sysrepo[11985]: [DBG] Sending 789 bytes of data.
Mar  9 09:40:49  sysrepo[11985]: [DBG] 789 bytes of data sent.
Mar  9 09:40:49  sysrepo[11985]: [DBG] fd 19 readable
Mar  9 09:40:49  sysrepo[11985]: [DBG] 55 bytes of data received on fd 19
Mar  9 09:40:49  sysrepo[11985]: [DBG] fd 19 would block
Mar  9 09:40:49  sysrepo[11985]: [DBG] New message of size 51 bytes received.
Mar  9 09:40:49  sysrepo[11985]: [DBG] Circular buffer enqueue to position=3, current count=1.
Mar  9 09:40:49  sysrepo[11985]: [DBG] Threads: active=0/4, 1 requests in queue
Mar  9 09:40:49  sysrepo[11985]: [DBG] Thread id=140737306220288 signaled.
Mar  9 09:40:49  sysrepo[11985]: [DBG] Circular buffer dequeue, new buffer head=4, count=0.


Mar  9 09:40:49  sysrepo[11985]: [DBG] Processing get changes request.   
           =>>> get changes request ===>> func:-rp_get_changes_req_process
Mar  9 09:40:49  sysrepo[11985]: [ERR] NULL value detected for difflist argument of rp_dt_difflist_to_changes  
Mar  9 09:40:49  sysrepo[11985]: [ERR] Difflist to changes failed

**Comment by michalvasko** [comment]
Hi Rosy,
I tried to use the default configuration data (`ietf-interfaces`), first issued an *edit-config* that changed the description of interface `eth0`, then *copy-config* the candidate into running and it was all performed fine. Could you please provide an example with the `ietf-interfaces` default configuration (it gets installed during `make install` of *sysrepo*)? Thank you.

Regards,
Michal
