### ISSUE TITLE
exponential increase in response time

### ISSUE THREAD

**Issue by betsyrosemanuel** [sysrepo/sysrepo#751]
Hi,
     I tried creating the profiles by sending xml. The response time increases exponentially for every new profile creation while the response time of the confD for the same xml is comparitively low.. isnt the netconf server supposed to have greater response time than confD. ?????

**Comment by betsyrosemanuel** [comment]
For eg when i create a tdd profile the response time is 114ms and when i create two tdd profiles the response time is 228.

**Comment by jktjkt** [comment]
What YANG modules are you using, what XML data are you storing in there using which operations, and what protocol do you use for access? What is that "profile" that you mention? What software is deployed on the server side?

**Comment by betsyrosemanuel** [comment]
hi, the yang module that i used is bbf-fast.
I used the segue soft client and sent the following xml. it can be seen that the elapsed time is 329ms whereas when i send an xml that creates 8 downstream profile the elapsed time is  1581 ms which is comparitively greater than the response time of confD
 
2017-03-14 12:16:52,816 INFO Send request: <?xml version="1.0" encoding="UTF-8"?>
```
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <edit-config>
    <target>
      <running/>
    </target>
    <config>
<fast xmlns="urn:bbf:yang:bbf-fast" xmlns:ns0="urn:ietf:params:xml:ns:netconf:base:1.0" ns0:operation="merge"> 
<service>
<downstream-data-rate-profile>
      <name>test_dsrp_1</name>
      <maximum-net-data-rate>4294967295</maximum-net-data-rate>
      <minimum-expected-throughput>0</minimum-expected-throughput>
      <maximum-gamma-data-rate>4294967295</maximum-gamma-data-rate>
      <minimum-gamma-data-rate>0</minimum-gamma-data-rate>
    </downstream-data-rate-profile>
</service>
</fast>
</config>
</edit-config>
</rpc>
```
2017-03-14 12:16:53,145 INFO Received reply <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1"><ok/></rpc-reply>

**Comment by michalvasko** [comment]
Performance improved.
