### ISSUE TITLE
deletion of callhome container rejected

### ISSUE THREAD

**Issue by senrajib** [sysrepo/sysrepo#752]
Hi
I am trying to delete only call home container from sysrepo running DS as below
sr_delete_item(session, "/ietf-netconf-server:netconf-server/callhome", SR_EDIT_DEFAULT)

But its getting rejected with below warning
Mar 14 05:51:16 MaestrOS sysrepod[7897]: [WRN] Validation of xpath /ietf-netconf-server:netconf-server/callhome was not successful

-Rajib

**Comment by antonio-paunovic** [comment]
Hi, 
In yang version of ietf-netconf-server module I can't see container 'callhome'.
There is 'call-home' container and feature so that may be it.

Regards,
Antonio
