### ISSUE TITLE
XPath addressing

### ISSUE THREAD

**Issue by michalvasko** [sysrepo/sysrepo#76]
Hi,
I am referring to [this](http://www.sysrepo.org/static/doc/html/xp_page.html) document. In it you have defined what I would think is a subset of XPath, which was simplified for your needs. However, the XPath expression to get all top-level nodes from a model (`/model:`) is actually not a valid XPath. Valid XPath with exactly the same meaning would be `/model:*`. My question is, was this deviation from XPath intentional and if so, what was the reason for it?

Regards,
Michal

**Comment by lukasmacko** [comment]
Hi Michal,

yes you're right, the simplified "subset" of xpath is used. The idea was to enable easy addressing for the most common use cases. Basicly, we use trimmed xpath. If we added ```*``` in addressing of the whole model, it should be added in container addressing ```/model:container/*```  and list addressing ```/model:list[key1='a'][key2='b']/*``` as well to adress in a consistent way.

You can subscribe to the mailing list [mailing list](http://lists.sysrepo.org/listinfo/sysrepo-private) where we discuss design topic like this. I'll start the discussion about the issue you have described.

Regards,
Lukas

**Comment by rastislavszabo** [comment]
The correct mailing list for design questions like this is: http://lists.sysrepo.org/listinfo/sysrepo-devel

**Comment by michalvasko** [comment]
Hi,
I have just submitted a request to join that mailing list, so we will resolve the issue there.

Regards,
Michal
