### ISSUE TITLE
sysrepod daemon not starting

### ISSUE THREAD

**Issue by betsyrosemanuel** [sysrepo/sysrepo#763]
Hi,
    I used the new devel branch to build. when i start the sysrepod i get the following error also unable to install the module successfully using sysrepoctl. Find below the log for `sysrepod -d -l4` and ``sysrepoctl --install --yang= /....../bbf-fast.yang

/mnt/nand-persistent/persistent/netconfserver # ./sysrepod -d -l4
[DBG] (sr_log_stderr:141) Setting log level for stderr logs to 4.
[DBG] (cm_init:1831) Connection Manager init started.
[DBG] (sr_cbuff_init:457) Initiating circular buffer for 10 elements.
[DBG] (sm_init:287) Session Manager initialized successfully, ctx=0x10506138.
[DBG] (cm_server_init:154) Initializing sysrepo server at socket=/tmp/sysrepod.sock
[DBG] (rp_init:3784) Request Processor init started.
[DBG] (sr_cbuff_init:457) Initiating circular buffer for 10 elements.
libyang[0]: Invalid keyword "type" as a child to "annotation". (path: /)
libyang[0]: Module "yang" parsing failed.
[ERR] (np_init:762) libyang initialization failed: Module "yang" parsing failed.
[DBG] (np_cleanup:803) Notification Processor cleanup requested.
[ERR] (rp_init:3824) Notification Processor initialization failed.
[DBG] (np_cleanup:803) Notification Processor cleanup requested.
[ERR] (cm_init:1886) Cannot initialize Request Processor.
[DBG] (rp_cleanup:3883) Request Processor cleanup started, requesting cancel of each worker thread.
[DBG] (rp_cleanup:3919) Request Processor cleanup finished.
[DBG] (sm_cleanup:300) Session Manager cleanup requested, ctx=0x10506138.
[INF] (cm_cleanup:1940) Connection Manager successfully destroyed.
[ERR] (main:119) Unable to initialize Connection Manager: Initialization failed.
[INF] (cm_cleanup:1940) Connection Manager successfully destroyed.
[INF] (main:144) Sysrepo daemon terminated.

Installing a new module from file '/mnt/persistent/netconfserver/total_yang/bbf-fast.yang'...
[ERR] (srctl_ly_log_cb:479) libyang: Invalid keyword "type" as a child to "annotation".
[ERR] (srctl_ly_log_cb:479) libyang: Module "yang" parsing failed.
Error: Unable to initialize libyang context: Module "yang" parsing failed..
Install operation failed.

**Comment by fabioantonini** [comment]
Hi
did you configured your libyang with 
-DPLUGINS_DIR:PATH="/usr/lib/libyang/
Inside that directory you should place nacm.so and metadata.so compiled under libyang.
Just as confirm in my environment I have tried to remove both the plugins and now sysrepod claims about the same error you have.
So the problem should be addressed in this way.
regards
fabio

**Comment by rkrejci** [comment]
fabio is right, this error message appears when libyang is unable to find its extensions plugins, see [libyang's FAQ](https://github.com/CESNET/libyang/blob/master/FAQ.md)

**Comment by betsyrosemanuel** [comment]
Hi,
    It didnt work either. I got the same error message.
 
$LIBYANG_EXTENSIONS_PLUGINS_DIR=/usr/lib/libyang ./sysrepoctl --i
nstall --yang=/mnt/nand-persistent/persistent/netconfserver/total_yang/bbf-fast

Installing a new module from file '/mnt/nand-persistent/persistent/netconfserver/total_yang/bbf-fast'...
[ERR] (srctl_ly_log_cb:479) libyang: Opening file "/mnt/nand-persistent/persistent/netconfserver/total_yang/bbf-fast" failed (No such file or directory).
Error: Unable to load the module by libyang.
Install operation failed.

**Comment by betsyrosemanuel** [comment]
ya that worked. thank you
