### ISSUE TITLE
profile creation failed

### ISSUE THREAD

**Issue by betsyrosemanuel** [sysrepo/sysrepo#768]
Hi,
    I sent the xml to create a profile using Seguesoft client and got rpc error. I have used the devel branch  also installed the yang using sysrepoctl. Find below the xml and the rpc reply for the same.

`<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <edit-config>
    <target>
      <running/>
    </target>
    <config>
<fast xmlns="urn:bbf:yang:bbf-fast" xmlns:ns0="urn:ietf:params:xml:ns:netconf:base:1.0" ns0:operation="merge"> 
<service>
<downstream-data-rate-profile>
      <name>test_dsrp_1</name>
      <maximum-net-data-rate>4294967295</maximum-net-data-rate>
      <minimum-expected-throughput>0</minimum-expected-throughput>
      <maximum-gamma-data-rate>4294967295</maximum-gamma-data-rate>
      <minimum-gamma-data-rate>0</minimum-gamma-data-rate>
    </downstream-data-rate-profile>
</service>
</fast>
</config>
</edit-config>
</rpc>`

` ##### Error Reply or Operation Failed #####
<?xml version='1.0' encoding='UTF-8'?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <rpc-error>
    <error-type>protocol</error-type>
    <error-tag>unknown-element</error-tag>
    <error-severity>error</error-severity>
    <error-message xml:lang="en">Unknown element "fast".</error-message>
    <error-info>
      <bad-element/>
    </error-info>
  </rpc-error>
</rpc-reply>`

Thanks

**Comment by betsyrosemanuel** [comment]
hi,
    This is the server log
netopeer2-server[31058]: (sr_connect:445) Connected to daemon Sysrepo Engine at socket=/tmp/sysrepod.sock
netopeer2-server[31058]: Netopeer2 connected to sysrepod.
netopeer2-server[31058]: Extension plugin "/usr/lib/libyang/nacm.so" successfully loaded.
netopeer2-server[31058]: Extension plugin "/usr/lib/libyang/metadata.so" successfully loaded.
netopeer2-server[31058]: Reading module "ietf-yang-metadata".
netopeer2-server[31058]: Module "ietf-yang-metadata" successfully parsed.
netopeer2-server[31058]: Reading module "yang".
netopeer2-server[31058]: Resolving "yang" unresolved schema nodes and their constraints...
netopeer2-server[31058]: All "yang" schema nodes and constraints resolved.
netopeer2-server[31058]: Module "yang" successfully parsed.
netopeer2-server[31058]: Reading module "ietf-inet-types".
netopeer2-server[31058]: Resolving derived type "union" failed, it will be attempted later.
netopeer2-server[31058]: Resolving type default "" failed, it will be attempted later.
netopeer2-server[31058]: Resolving derived type "union" failed, it will be attempted later.
netopeer2-server[31058]: Resolving type default "" failed, it will be attempted later.
netopeer2-server[31058]: Resolving derived type "union" failed, it will be attempted later.
netopeer2-server[31058]: Resolving type default "" failed, it will be attempted later.
netopeer2-server[31058]: Resolving derived type "union" failed, it will be attempted later.
netopeer2-server[31058]: Resolving type default "" failed, it will be attempted later.
netopeer2-server[31058]: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
netopeer2-server[31058]: All "ietf-inet-types" schema nodes and constraints resolved.
netopeer2-server[31058]: Module "ietf-inet-types" successfully parsed.
netopeer2-server[31058]: Reading module "ietf-yang-types".
netopeer2-server[31058]: Module "ietf-yang-types" successfully parsed.
netopeer2-server[31058]: Reading module "ietf-yang-library".
netopeer2-server[31058]: Module "ietf-yang-library" successfully parsed.
netopeer2-server[31058]: Loading schema "bbf-fast@2016-09-23" from sysrepo.
netopeer2-server[31058]: Reading module "bbf-fast".
netopeer2-server[31058]: Reading submodule "bbf-fast-base".
netopeer2-server[31058]: Reading module "ietf-interfaces".
netopeer2-server[31058]: Module "ietf-interfaces" successfully parsed.
netopeer2-server[31058]: Reading module "bbf-fastdsl".
netopeer2-server[31058]: Reading module "ietf-interfaces".
netopeer2-server[31058]: Module "ietf-interfaces" already in context.
netopeer2-server[31058]: Module "ietf-interfaces" successfully parsed.
netopeer2-server[31058]: Reading module "iana-if-type".
netopeer2-server[31058]: Reading module "ietf-interfaces".
netopeer2-server[31058]: Module "ietf-interfaces" already in context.
netopeer2-server[31058]: Module "ietf-interfaces" successfully parsed.
netopeer2-server[31058]: Module "iana-if-type" successfully parsed.
netopeer2-server[31058]: Resolving XPath expressions of "supported-mode" failed, it will be attempted later.
netopeer2-server[31058]: Resolving "bbf-fastdsl" unresolved schema nodes and their constraints...
netopeer2-server[31058]: All "bbf-fastdsl" schema nodes and constraints resolved.
netopeer2-server[31058]: Module "bbf-fastdsl" successfully parsed.
netopeer2-server[31058]: Submodule "bbf-fast-base" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-pointers".
netopeer2-server[31058]: Reading module "ietf-interfaces".
netopeer2-server[31058]: Module "ietf-interfaces" already in context.
netopeer2-server[31058]: Module "ietf-interfaces" successfully parsed.
netopeer2-server[31058]: Reading module "bbf-fastdsl".
netopeer2-server[31058]: Module "bbf-fastdsl" already in context.
netopeer2-server[31058]: Module "bbf-fastdsl" successfully parsed.
netopeer2-server[31058]: Reading module "bbf-yang-types".
netopeer2-server[31058]: Module "bbf-yang-types" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-service-profiles".
netopeer2-server[31058]: Reading module "bbf-yang-types".
netopeer2-server[31058]: Module "bbf-yang-types" already in context.
netopeer2-server[31058]: Module "bbf-yang-types" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-data-rate-profile-body".
netopeer2-server[31058]: Reading module "bbf-yang-types".
netopeer2-server[31058]: Module "bbf-yang-types" already in context.
netopeer2-server[31058]: Module "bbf-yang-types" successfully parsed.
netopeer2-server[31058]: Submodule "bbf-fast-data-rate-profile-body" successfully parsed.
netopeer2-server[31058]: Submodule "bbf-fast-service-profiles" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-spectrum-profiles".
netopeer2-server[31058]: Reading module "bbf-yang-types".
netopeer2-server[31058]: Module "bbf-yang-types" already in context.
netopeer2-server[31058]: Module "bbf-yang-types" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-line-spectrum-profile-body".
netopeer2-server[31058]: Submodule "bbf-fast-line-spectrum-profile-body" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-upstream-power-back-off-profile-body".
netopeer2-server[31058]: Submodule "bbf-fast-upstream-power-back-off-profile-body" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-rfi-profile-body".
netopeer2-server[31058]: Submodule "bbf-fast-rfi-profile-body" successfully parsed.
netopeer2-server[31058]: Submodule "bbf-fast-spectrum-profiles" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-quality-profiles".
netopeer2-server[31058]: Reading module "bbf-yang-types".
netopeer2-server[31058]: Module "bbf-yang-types" already in context.
netopeer2-server[31058]: Module "bbf-yang-types" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-fast-rate-adaptation-profile-body".
netopeer2-server[31058]: Submodule "bbf-fast-fast-rate-adaptation-profile-body" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-noise-margin-profile-body".
netopeer2-server[31058]: Submodule "bbf-fast-noise-margin-profile-body" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-fast-retrain-policy-profile-body".
netopeer2-server[31058]: Submodule "bbf-fast-fast-retrain-policy-profile-body" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-retransmission-profile-body".
netopeer2-server[31058]: Submodule "bbf-fast-retransmission-profile-body" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-vectoring-profile-body".
netopeer2-server[31058]: Submodule "bbf-fast-vectoring-profile-body" successfully parsed.
netopeer2-server[31058]: Submodule "bbf-fast-quality-profiles" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-tdd-profiles".
netopeer2-server[31058]: Reading module "bbf-yang-types".
netopeer2-server[31058]: Module "bbf-yang-types" already in context.
netopeer2-server[31058]: Module "bbf-yang-types" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-tdd-profile-body".
netopeer2-server[31058]: Submodule "bbf-fast-tdd-profile-body" successfully parsed.
netopeer2-server[31058]: Submodule "bbf-fast-tdd-profiles" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-threshold-management".
netopeer2-server[31058]: Reading module "bbf-yang-types".
netopeer2-server[31058]: Module "bbf-yang-types" already in context.
netopeer2-server[31058]: Module "bbf-yang-types" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-perf-types".
netopeer2-server[31058]: Resolving derived type "performance-15min-interval" failed, it will be attempted later.
netopeer2-server[31058]: Resolving type default "" failed, it will be attempted later.
netopeer2-server[31058]: Resolving derived type "performance-24hr-interval" failed, it will be attempted later.
netopeer2-server[31058]: Resolving type default "" failed, it will be attempted later.
netopeer2-server[31058]: Submodule "bbf-fast-perf-types" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-line-threshold-profile-body".
netopeer2-server[31058]: Submodule "bbf-fast-line-threshold-profile-body" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-channel-threshold-profile-body".
netopeer2-server[31058]: Submodule "bbf-fast-channel-threshold-profile-body" successfully parsed.
netopeer2-server[31058]: Submodule "bbf-fast-threshold-management" successfully parsed.
netopeer2-server[31058]: Resolving if-feature "performance-24hr" failed, it will be attempted later.
netopeer2-server[31058]: Resolving if-feature "performance-24hr" failed, it will be attempted later.
netopeer2-server[31058]: Resolving if-feature "performance-24hr" failed, it will be attempted later.
netopeer2-server[31058]: Resolving if-feature "performance-24hr" failed, it will be attempted later.
netopeer2-server[31058]: Submodule "bbf-fast-pointers" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-test-diagnostics".
netopeer2-server[31058]: Reading module "ietf-interfaces".
netopeer2-server[31058]: Module "ietf-interfaces" already in context.
netopeer2-server[31058]: Module "ietf-interfaces" successfully parsed.
netopeer2-server[31058]: Reading module "bbf-fastdsl".
netopeer2-server[31058]: Module "bbf-fastdsl" already in context.
netopeer2-server[31058]: Module "bbf-fastdsl" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-test-mode-body".
netopeer2-server[31058]: Submodule "bbf-fast-test-mode-body" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-update-test-body".
netopeer2-server[31058]: Submodule "bbf-fast-update-test-body" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-link-state-body".
netopeer2-server[31058]: Submodule "bbf-fast-link-state-body" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-read-test-body".
netopeer2-server[31058]: Reading submodule "bbf-fast-line-status-body".
netopeer2-server[31058]: Reading module "bbf-yang-types".
netopeer2-server[31058]: Module "bbf-yang-types" already in context.
netopeer2-server[31058]: Module "bbf-yang-types" successfully parsed.
netopeer2-server[31058]: Submodule "bbf-fast-line-status-body" successfully parsed.
netopeer2-server[31058]: Submodule "bbf-fast-read-test-body" successfully parsed.
netopeer2-server[31058]: Submodule "bbf-fast-test-diagnostics" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-performance-management".
netopeer2-server[31058]: Reading module "ietf-interfaces".
netopeer2-server[31058]: Module "ietf-interfaces" already in context.
netopeer2-server[31058]: Module "ietf-interfaces" successfully parsed.
netopeer2-server[31058]: Reading module "bbf-fastdsl".
netopeer2-server[31058]: Module "bbf-fastdsl" already in context.
netopeer2-server[31058]: Module "bbf-fastdsl" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-line-performance-body".
netopeer2-server[31058]: Reading module "bbf-yang-types".
netopeer2-server[31058]: Module "bbf-yang-types" already in context.
netopeer2-server[31058]: Module "bbf-yang-types" successfully parsed.
netopeer2-server[31058]: Resolving derived type "performance-15min-history-interval" failed, it will be attempted later.
netopeer2-server[31058]: Resolving derived type "performance-24hr-history-interval" failed, it will be attempted later.
netopeer2-server[31058]: Submodule "bbf-fast-line-performance-body" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-channel-performance-body".
netopeer2-server[31058]: Reading module "bbf-yang-types".
netopeer2-server[31058]: Module "bbf-yang-types" already in context.
netopeer2-server[31058]: Module "bbf-yang-types" successfully parsed.
netopeer2-server[31058]: Resolving derived type "performance-15min-history-interval" failed, it will be attempted later.
netopeer2-server[31058]: Resolving derived type "performance-24hr-history-interval" failed, it will be attempted later.
netopeer2-server[31058]: Submodule "bbf-fast-channel-performance-body" successfully parsed.
netopeer2-server[31058]: Resolving uses "line-performance" failed, it will be attempted later.
netopeer2-server[31058]: Resolving uses "channel-performance" failed, it will be attempted later.
netopeer2-server[31058]: Submodule "bbf-fast-performance-management" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-status-monitoring".
netopeer2-server[31058]: Reading module "ietf-interfaces".
netopeer2-server[31058]: Module "ietf-interfaces" already in context.
netopeer2-server[31058]: Module "ietf-interfaces" successfully parsed.
netopeer2-server[31058]: Reading module "bbf-fastdsl".
netopeer2-server[31058]: Module "bbf-fastdsl" already in context.
netopeer2-server[31058]: Module "bbf-fastdsl" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-channel-status-body".
netopeer2-server[31058]: Reading module "bbf-yang-types".
netopeer2-server[31058]: Module "bbf-yang-types" already in context.
netopeer2-server[31058]: Module "bbf-yang-types" successfully parsed.
netopeer2-server[31058]: Submodule "bbf-fast-channel-status-body" successfully parsed.
netopeer2-server[31058]: Submodule "bbf-fast-status-monitoring" successfully parsed.
netopeer2-server[31058]: Reading submodule "bbf-fast-inventory".
netopeer2-server[31058]: Reading module "ietf-interfaces".
netopeer2-server[31058]: Module "ietf-interfaces" already in context.
netopeer2-server[31058]: Module "ietf-interfaces" successfully parsed.
netopeer2-server[31058]: Reading module "bbf-fastdsl".
netopeer2-server[31058]: Module "bbf-fastdsl" already in context.
netopeer2-server[31058]: Module "bbf-fastdsl" successfully parsed.
netopeer2-server[31058]: Invalid NameStartChar of the attribute.
netopeer2-server[31058]: Including "bbf-fast-ftu-inventory-body" module into "bbf-fast-inventory" failed.
netopeer2-server[31058]: Submodule "bbf-fast-inventory" parsing failed.
netopeer2-server[31058]: Including "bbf-fast-inventory" module into "bbf-fast" failed.
netopeer2-server[31058]: Module "bbf-fast" parsing failed.
**netopeer2-server[31058]: Getting bbf-fast@2016-09-23 schema from sysrepo failed, data from this module won't be available.**
netopeer2-server[31058]: Loading schema "ietf-interfaces@2014-05-08" from sysrepo.
netopeer2-server[31058]: Module ietf-interfaces@2014-05-08 already present in context.
netopeer2-server[31058]: Loading schema "bbf-fastdsl@2016-07-18" from sysrepo.
netopeer2-server[31058]: Module bbf-fastdsl@2016-07-18 already present in context.
netopeer2-server[31058]: Loading schema "iana-if-type@2016-06-09" from sysrepo.
netopeer2-server[31058]: Module iana-if-type@2016-06-09 already present in context.
netopeer2-server[31058]: Loading schema "bbf-yang-types@2016-06-08" from sysrepo.
netopeer2-server[31058]: Module bbf-yang-types@2016-06-08 already present in context.
netopeer2-server[31058]: Loading schema "ietf-entity@2015-10-19" from sysrepo.
netopeer2-server[31058]: Reading module "ietf-entity".
netopeer2-server[31058]: Module "ietf-entity" successfully parsed.
netopeer2-server[31058]: Loading schema "ietf-netconf-acm@2012-02-22" from sysrepo.
netopeer2-server[31058]: Reading module "ietf-netconf-acm".
netopeer2-server[31058]: Resolving "ietf-netconf-acm" unresolved schema nodes and their constraints...
netopeer2-server[31058]: All "ietf-netconf-acm" schema nodes and constraints resolved.
netopeer2-server[31058]: Module "ietf-netconf-acm" successfully parsed.
netopeer2-server[31058]: Loading schema "ietf-netconf-with-defaults@2011-06-01" from sysrepo.
netopeer2-server[31058]: Reading module "ietf-netconf-with-defaults".
netopeer2-server[31058]: Reading module "ietf-netconf".
netopeer2-server[31058]: Module "ietf-netconf" successfully parsed.
netopeer2-server[31058]: Module "ietf-netconf-with-defaults" successfully parsed.
netopeer2-server[31058]: Loading schema "ietf-netconf@2011-06-01" from sysrepo.
netopeer2-server[31058]: Module ietf-netconf@2011-06-01 already present in context.
netopeer2-server[31058]: Loading schema "ietf-netconf-server@2016-03-16" from sysrepo.
netopeer2-server[31058]: Reading module "ietf-netconf-server".
netopeer2-server[31058]: Reading module "ietf-x509-cert-to-name".
netopeer2-server[31058]: Module "ietf-x509-cert-to-name" successfully parsed.
netopeer2-server[31058]: Reading module "ietf-ssh-server".
netopeer2-server[31058]: Reading module "ietf-system-keychain".
netopeer2-server[31058]: Module "ietf-system-keychain" successfully parsed.
netopeer2-server[31058]: Module "ietf-ssh-server" successfully parsed.
netopeer2-server[31058]: Reading module "ietf-tls-server".
netopeer2-server[31058]: Module "ietf-tls-server" successfully parsed.
netopeer2-server[31058]: Resolving "ietf-netconf-server" unresolved schema nodes and their constraints...
netopeer2-server[31058]: All "ietf-netconf-server" schema nodes and constraints resolved.
netopeer2-server[31058]: Module "ietf-netconf-server" successfully parsed.
netopeer2-server[31058]: Loading schema "ietf-x509-cert-to-name@2014-12-10" from sysrepo.
netopeer2-server[31058]: Module ietf-x509-cert-to-name@2014-12-10 already present in context.
netopeer2-server[31058]: Loading schema "ietf-ssh-server@2016-03-16" from sysrepo.
netopeer2-server[31058]: Module ietf-ssh-server@2016-03-16 already present in context.
netopeer2-server[31058]: Loading schema "ietf-system-keychain@2016-03-16" from sysrepo.
netopeer2-server[31058]: Module ietf-system-keychain@2016-03-16 already present in context.
netopeer2-server[31058]: Loading schema "ietf-tls-server@2016-03-16" from sysrepo.
netopeer2-server[31058]: Module ietf-tls-server@2016-03-16 already present in context.
netopeer2-server[31058]: Reading module "ietf-netconf-monitoring".
netopeer2-server[31058]: Module "ietf-netconf-monitoring" successfully parsed.
netopeer2-server[31058]: Sysrepo does not have the "ietf-netconf-server" module or keystored keys dir unknown, using default NETCONF server options.
netopeer2-server[31058]: Listening on 0.0.0.0:6001 for SSH connections.

**Comment by rkrejci** [comment]
Should be fixed by the latest (0.12.146) libyang.

**Comment by betsyrosemanuel** [comment]
Hi,
    I got the same error message for the following xml as well. 
`<?xml version="1.0" encoding="UTF-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <edit-config>
    <target>
      <running/>
    </target>
    <config>
      <entity xmlns="urn:ietf:params:xml:ns:yang:ietf-entity">
<physical-entity>
          <name>test_port_1</name>
          <admin-state>unlocked</admin-state>
          <class xmlns:ianaent="urn:ietf:params:xml:ns:yang:iana-entity" xmlns="urn:broadband-forum-org:bbf-entity-extension">ianaent:port</class>
          <contained-in xmlns="urn:broadband-forum-org:bbf-entity-extension">module-srnt-h</contained-in>
          <parent-rel-pos xmlns="urn:broadband-forum-org:bbf-entity-extension">1</parent-rel-pos>
        </physical-entity>
        <physical-entity>
          <name>module-srnt-h</name>
          <admin-state>unlocked</admin-state>
          <class xmlns:ianaent="urn:ietf:params:xml:ns:yang:iana-entity" xmlns="urn:broadband-forum-org:bbf-entity-extension">ianaent:module</class>
          <contained-in xmlns="urn:broadband-forum-org:bbf-entity-extension">chasis-cfas-d</contained-in>
          <parent-rel-pos xmlns="urn:broadband-forum-org:bbf-entity-extension">1</parent-rel-pos>
          <mfg-name xmlns="urn:broadband-forum-org:bbf-entity-extension">ALCL</mfg-name>
          <model-name xmlns="urn:broadband-forum-org:bbf-entity-extension">SRNT-D</model-name>
          <serial-num/>
        </physical-entity>
<physical-entity>
          <name>chasis-cfas-d</name>
          <admin-state>unlocked</admin-state>
          <class xmlns:ianaent="urn:ietf:params:xml:ns:yang:iana-entity" xmlns="urn:broadband-forum-org:bbf-entity-extension">ianaent:chassis</class>
          <parent-rel-pos xmlns="urn:broadband-forum-org:bbf-entity-extension">1</parent-rel-pos>
          <mfg-name xmlns="urn:broadband-forum-org:bbf-entity-extension">ALCL</mfg-name>
          <model-name xmlns="urn:broadband-forum-org:bbf-entity-extension">CFAS-B</model-name>
          <serial-num/>
        </physical-entity>
</entity>
</config>
</edit-config>
</rpc>`



 ##### Error Reply or Operation Failed #####
<?xml version='1.0' encoding='UTF-8'?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <rpc-error>
    <error-type>protocol</error-type>
    <error-tag>unknown-element</error-tag>
    <error-severity>error</error-severity>
    <error-message xml:lang="en">Unknown element "class".</error-message>
    <error-info>
      <bad-element>/ietf-entity:entity/physical-entity[name='test_port_1']</bad-element>
    </error-info>
  </rpc-error>
</rpc-reply>

**Comment by rkrejci** [comment]
The message is not the same. From the server log i don't see you have loaded the `bbf-entity-extension` module where the `class` element is defined so you cannot use it in your edit-config requests.

**Comment by betsyrosemanuel** [comment]
when i installed the yang "bbf-extension-entity" using sysrepoctl i got the following error message.
/sysrepoctl --i
nstall --yang=/mnt/nand-persistent/persistent/netconfserver/total_yang/bbf-entity-extension.yang
Installing a new module from file '/mnt/nand-persistent/persistent/netconfserver/total_yang/bbf-entity-extension.yang'...
[ERR] (srctl_ly_log_cb:479) libyang: No resolvents found for leafref "../../ietf-entity:physical-entity/ietf-entity:name".
[ERR] (srctl_ly_log_cb:479) libyang: Leafref is not conditional based on "entity-config" feature as its target.
[ERR] (srctl_ly_log_cb:479) libyang: Module "bbf-entity-extension" parsing failed.
Error: Unable to load the module by libyang.
Install operation failed.

**Comment by rkrejci** [comment]
can you provide the module?

**Comment by betsyrosemanuel** [comment]
`module bbf-entity-extension {
 //  yang-version 1.1; Commented out since ConfD not compatible with yang v1.1

  namespace "urn:broadband-forum-org:bbf-entity-extension";

  prefix bbf-ent-ext;

  import ietf-entity {
    prefix ent;
  }
  
  organization
	    "Broadband Forum Common YANG Work Area";
  
  contact
    "bbf: http://www.broadband-forum.org
          help@broadband-forum.org 

    Editor: Jan Verbist, Nokia 

    Work Area Director: William Lupton, Broadband Forum 
                        Michael Shaffer, Nokia";

 description
    "A YANG Data model to augment the IETF-Entity model with configurational
    data";

  revision 2016-07-07 {
    description
        "Initial revision.";
    reference
        "BBF TR-301, Architecture and Requirements for Fiber to the Distribution
        Point";
  }

  augment "/ent:entity/ent:physical-entity" {
    description
      "Configurational nodes for entities, as counterpart for operational nodes";

    leaf class {
      type identityref {
        base ent:entity-physical-class;
      }
      description "An indication of the general hardware type of the physical entity.";
      reference "RFC 6933: entPhysicalClass";
    }

    leaf-list contained-in {
        type leafref {
          path "../../ent:physical-entity/ent:name";
	    }
	      description
	          "The name of the physical entity that 'contains' this physical entity.";
	      reference "RFC 6933: entPhysicalContainedIn";
	    }

	leaf parent-rel-pos {
      type int32 {
	    range "0 .. 2147483647";
	  }
	  description "An indication of the relative position of this child component among all
	      its sibling components. Sibling components are defined as physical entities
	      that share the same instance values of each of the contained-in and class
	      elements.";
	  reference "RFC 6933: entPhysicalParentRelPos";
	}
   
    leaf mfg-name {
      type string;
      description
        "The name of the manufacturer of this physical component. The preferred
        value is the manufacturer name string actually printed on the component
        itself (if present). Note that comparisons between instances of the model-name,
        firmware-rev, software-rev, and the serial-num nodes are only meaningful
        amongst physical entities with the same value of mfg-name. If the manufacturer
        name string associated with the physical component is unknown to the server,
        then this node will contain a zero-length string.";
      reference "RFC 6933: entPhysicalMfgName";
    }

    leaf model-name {
      type string;
      description "The vendor-specific model name identifier string associated with this physical
        component. The preferred value is the customer-visible part number, which
        may be printed on the component itself. If the model name string associated
        with the physical component is unknown to the server, then this node will
        contain a zero-length string.";
      reference "RFC 6933: entPhysicalModelName";
    }
  }
}
`

**Comment by betsyrosemanuel** [comment]
module bbf-entity-extension {


  namespace "urn:broadband-forum-org:bbf-entity-extension";

  prefix bbf-ent-ext;

  import ietf-entity {
    prefix ent;
  }
  
  organization
	    "Broadband Forum Common YANG Work Area";
 description
    "A YANG Data model to augment the IETF-Entity model with configurational
    data";

  revision 2016-07-07 {
    description
        "Initial revision.";
    reference
        "BBF TR-301, Architecture and Requirements for Fiber to the Distribution
        Point";
  }

  augment "/ent:entity/ent:physical-entity" {
    description
      "Configurational nodes for entities, as counterpart for operational nodes";

    leaf class {
      type identityref {
        base ent:entity-physical-class;
      }
      description "An indication of the general hardware type of the physical entity.";
      reference "RFC 6933: entPhysicalClass";
    }

    leaf-list contained-in {
        type leafref {
          path "../../ent:physical-entity/ent:name";
	    }
	      description
	          "The name of the physical entity that 'contains' this physical entity.";
	      reference "RFC 6933: entPhysicalContainedIn";
	    }

	leaf parent-rel-pos {
      type int32 {
	    range "0 .. 2147483647";
	  }
	  description "An indication of the relative position of this child component among all
	      its sibling components. Sibling components are defined as physical entities
	      that share the same instance values of each of the contained-in and class
	      elements.";
	  reference "RFC 6933: entPhysicalParentRelPos";
	}
   
    leaf mfg-name {
      type string;
      description
        "The name of the manufacturer of this physical component. The preferred
        value is the manufacturer name string actually printed on the component
        itself (if present). Note that comparisons between instances of the model-name,
        firmware-rev, software-rev, and the serial-num nodes are only meaningful
        amongst physical entities with the same value of mfg-name. If the manufacturer
        name string associated with the physical component is unknown to the server,
        then this node will contain a zero-length string.";
      reference "RFC 6933: entPhysicalMfgName";
    }

    leaf model-name {
      type string;
      description "The vendor-specific model name identifier string associated with this physical
        component. The preferred value is the customer-visible part number, which
        may be printed on the component itself. If the model name string associated
        with the physical component is unknown to the server, then this node will
        contain a zero-length string.";
      reference "RFC 6933: entPhysicalModelName";
    }
  }
}

**Comment by rkrejci** [comment]
please provide also the version of `ietf-entity` module you are using.

**Comment by betsyrosemanuel** [comment]
revision 2015-10-19
version:4

**Comment by rkrejci** [comment]
Can you provide me a link? Or the module itself (github allows you to attach files)? When I get version `2015-10-19` from [draft-entitydt-netmod-entity-00](https://tools.ietf.org/html/draft-entitydt-netmod-entity-00) it has invalid usage of XPath function `derived-from-or-self()`.

**Comment by betsyrosemanuel** [comment]
hii. this is the ietf-entity yang that i have used. 
[ietf-entity.docx](https://github.com/sysrepo/sysrepo/files/896126/ietf-entity.docx)

**Comment by rkrejci** [comment]
It is different issue, but it should be now fixed in libyang 0.12.147.
