### ISSUE TITLE
edit-config failed 

### ISSUE THREAD

**Issue by betsyrosemanuel** [sysrepo/sysrepo#769]
Hi, 
     I performed `edit-config` using the following xml and got error reply.
`<?xml version="1.0" encoding="UTF-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <edit-config>
    <target>
      <running/>
    </target>
    <config>
      <entity xmlns="urn:ietf:params:xml:ns:yang:ietf-entity">
<physical-entity>
          <name>test_port_1</name>
          <admin-state>unlocked</admin-state>
          <class xmlns:ianaent="urn:ietf:params:xml:ns:yang:iana-entity" xmlns="urn:broadband-forum-org:bbf-entity-extension">ianaent:port</class>
          <contained-in xmlns="urn:broadband-forum-org:bbf-entity-extension">module-srnt-h</contained-in>
          <parent-rel-pos xmlns="urn:broadband-forum-org:bbf-entity-extension">1</parent-rel-pos>
        </physical-entity>
        <physical-entity>
          <name>module-srnt-h</name>
          <admin-state>unlocked</admin-state>
          <class xmlns:ianaent="urn:ietf:params:xml:ns:yang:iana-entity" xmlns="urn:broadband-forum-org:bbf-entity-extension">ianaent:module</class>
          <contained-in xmlns="urn:broadband-forum-org:bbf-entity-extension">chasis-cfas-d</contained-in>
          <parent-rel-pos xmlns="urn:broadband-forum-org:bbf-entity-extension">1</parent-rel-pos>
          <mfg-name xmlns="urn:broadband-forum-org:bbf-entity-extension">ALCL</mfg-name>
          <model-name xmlns="urn:broadband-forum-org:bbf-entity-extension">SRNT-D</model-name>
          <serial-num/>
        </physical-entity>
<physical-entity>
          <name>chasis-cfas-d</name>
          <admin-state>unlocked</admin-state>
          <class xmlns:ianaent="urn:ietf:params:xml:ns:yang:iana-entity" xmlns="urn:broadband-forum-org:bbf-entity-extension">ianaent:chassis</class>
          <parent-rel-pos xmlns="urn:broadband-forum-org:bbf-entity-extension">1</parent-rel-pos>
          <mfg-name xmlns="urn:broadband-forum-org:bbf-entity-extension">ALCL</mfg-name>
          <model-name xmlns="urn:broadband-forum-org:bbf-entity-extension">CFAS-B</model-name>
          <serial-num/>
        </physical-entity>
</entity>
</config>
</edit-config>
</rpc>`

 ##### Error Reply or Operation Failed #####
<?xml version='1.0' encoding='UTF-8'?>
```
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <rpc-error>
    <error-type>protocol</error-type>
    <error-tag>unknown-element</error-tag>
    <error-severity>error</error-severity>
    <error-message xml:lang="en">Unknown element "class".</error-message>
    <error-info>
      <bad-element>/ietf-entity:entity/physical-entity[name='test_port_1']</bad-element>
    </error-info>
  </rpc-error>
</rpc-reply>
```

**Comment by rkrejci** [comment]
Please provide netopeer-server log

**Comment by betsyrosemanuel** [comment]
hi,
 this is the netopeer server log

**Comment by betsyrosemanuel** [comment]
netopeer2-server[13119]: Accepted a connection on 0.0.0.0:6001.
[1970/01/01 00:29:54.755011, 1] ssh_server_connection_callback:  SSH client banner: SSH-2.0-paramiko_1.16.0
[1970/01/01 00:29:54.755303, 1] ssh_analyze_banner:  Analyzing banner: SSH-2.0-paramiko_1.16.0
[1970/01/01 00:29:54.968477, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
netopeer2-server[13119]: Received an SSH message "request-service" of subtype "ssh-userauth".
netopeer2-server[13119]: Received an SSH message "request-auth" of subtype "password".
netopeer2-server[13119]: User "root" authenticated.
netopeer2-server[13119]: Received an SSH message "request-channel-open" of subtype "session".
netopeer2-server[13119]: Received an SSH message "request-channel" of subtype "subsystem".
[1970/01/01 00:29:55.031568, 2] grow_window:  growing window (channel 43:0) to 1280000 bytes
netopeer2-server[13119]: Resolving unresolved data nodes and their constraints...
netopeer2-server[13119]: All data nodes and constraints resolved.
netopeer2-server[13119]: Unknown element "class". (/ietf-entity:entity/physical-entity[name='test_port_1'])
netopeer2-server[13119]: Session 1: thread 3 event new RPC.
netopeer2-server[13119]: Session 1: thread 3 event reply error.

**Comment by rkrejci** [comment]
please provide log from the server start to get know which yang modules are supported

**Comment by betsyrosemanuel** [comment]
[1970/01/01 00:29:17.370717, 1] ssh_server_connection_callback:  SSH client banner: SSH-2.0-paramiko_1.16.0
[1970/01/01 00:29:17.371019, 1] ssh_analyze_banner:  Analyzing banner: SSH-2.0-paramiko_1.16.0
[1970/01/01 00:29:17.625496, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
netopeer2-server[13001]: Received an SSH message "request-service" of subtype "ssh-userauth".
netopeer2-server[13001]: Received an SSH message "request-auth" of subtype "password".
netopeer2-server[13001]: User "root" authenticated.
netopeer2-server[13001]: Received an SSH message "request-channel-open" of subtype "session".
netopeer2-server[13001]: Received an SSH message "request-channel" of subtype "subsystem".
[1970/01/01 00:29:17.686862, 2] grow_window:  growing window (channel 43:0) to 1280000 bytes
netopeer2-server[13001]: Resolving unresolved data nodes and their constraints...
netopeer2-server[13001]: All data nodes and constraints resolved.
netopeer2-server[13001]: Unknown element "class". (/ietf-entity:entity/physical-entity[name='test_port_1'])
netopeer2-server[13001]: Session 1: thread 0 event new RPC.
netopeer2-server[13001]: Session 1: thread 0 event reply error.
/mnt/nand-persistent/persistent/netconfserver # LIBYANG_EXTENSIONS_PLUGINS_DIR=/usr/lib/libyang ./netopeer2-serv
er -d -v4
netopeer2-server[13119]: (sr_connect:445) Connected to daemon Sysrepo Engine at socket=/tmp/sysrepod.sock
netopeer2-server[13119]: Netopeer2 connected to sysrepod.
netopeer2-server[13119]: Extension plugin "/usr/lib/libyang/nacm.so" successfully loaded.
netopeer2-server[13119]: Extension plugin "/usr/lib/libyang/metadata.so" successfully loaded.
netopeer2-server[13119]: Reading module "ietf-yang-metadata".
netopeer2-server[13119]: Module "ietf-yang-metadata" successfully parsed.
netopeer2-server[13119]: Reading module "yang".
netopeer2-server[13119]: Resolving "yang" unresolved schema nodes and their constraints...
netopeer2-server[13119]: All "yang" schema nodes and constraints resolved.
netopeer2-server[13119]: Module "yang" successfully parsed.
netopeer2-server[13119]: Reading module "ietf-inet-types".
netopeer2-server[13119]: Resolving derived type "union" failed, it will be attempted later.
netopeer2-server[13119]: Resolving type default "" failed, it will be attempted later.
netopeer2-server[13119]: Resolving derived type "union" failed, it will be attempted later.
netopeer2-server[13119]: Resolving type default "" failed, it will be attempted later.
netopeer2-server[13119]: Resolving derived type "union" failed, it will be attempted later.
netopeer2-server[13119]: Resolving type default "" failed, it will be attempted later.
netopeer2-server[13119]: Resolving derived type "union" failed, it will be attempted later.
netopeer2-server[13119]: Resolving type default "" failed, it will be attempted later.
netopeer2-server[13119]: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
netopeer2-server[13119]: All "ietf-inet-types" schema nodes and constraints resolved.
netopeer2-server[13119]: Module "ietf-inet-types" successfully parsed.
netopeer2-server[13119]: Reading module "ietf-yang-types".
netopeer2-server[13119]: Module "ietf-yang-types" successfully parsed.
netopeer2-server[13119]: Reading module "ietf-yang-library".
netopeer2-server[13119]: Module "ietf-yang-library" successfully parsed.
netopeer2-server[13119]: Loading schema "bbf-fast@2016-09-23" from sysrepo.
netopeer2-server[13119]: Reading module "bbf-fast".
netopeer2-server[13119]: Reading submodule "bbf-fast-base".
netopeer2-server[13119]: Reading module "ietf-interfaces".
netopeer2-server[13119]: Module "ietf-interfaces" successfully parsed.
netopeer2-server[13119]: Reading module "bbf-fastdsl".
netopeer2-server[13119]: Reading module "ietf-interfaces".
netopeer2-server[13119]: Module "ietf-interfaces" already in context.
netopeer2-server[13119]: Module "ietf-interfaces" successfully parsed.
netopeer2-server[13119]: Reading module "iana-if-type".
netopeer2-server[13119]: Reading module "ietf-interfaces".
netopeer2-server[13119]: Module "ietf-interfaces" already in context.
netopeer2-server[13119]: Module "ietf-interfaces" successfully parsed.
netopeer2-server[13119]: Module "iana-if-type" successfully parsed.
netopeer2-server[13119]: Resolving XPath expressions of "supported-mode" failed, it will be attempted later.
netopeer2-server[13119]: Resolving "bbf-fastdsl" unresolved schema nodes and their constraints...
netopeer2-server[13119]: All "bbf-fastdsl" schema nodes and constraints resolved.
netopeer2-server[13119]: Module "bbf-fastdsl" successfully parsed.
netopeer2-server[13119]: Submodule "bbf-fast-base" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-pointers".
netopeer2-server[13119]: Reading module "ietf-interfaces".
netopeer2-server[13119]: Module "ietf-interfaces" already in context.
netopeer2-server[13119]: Module "ietf-interfaces" successfully parsed.
netopeer2-server[13119]: Reading module "bbf-fastdsl".
netopeer2-server[13119]: Module "bbf-fastdsl" already in context.
netopeer2-server[13119]: Module "bbf-fastdsl" successfully parsed.
netopeer2-server[13119]: Reading module "bbf-yang-types".
netopeer2-server[13119]: Module "bbf-yang-types" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-service-profiles".
netopeer2-server[13119]: Reading module "bbf-yang-types".
netopeer2-server[13119]: Module "bbf-yang-types" already in context.
netopeer2-server[13119]: Module "bbf-yang-types" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-data-rate-profile-body".
netopeer2-server[13119]: Reading module "bbf-yang-types".
netopeer2-server[13119]: Module "bbf-yang-types" already in context.
netopeer2-server[13119]: Module "bbf-yang-types" successfully parsed.
netopeer2-server[13119]: Submodule "bbf-fast-data-rate-profile-body" successfully parsed.
netopeer2-server[13119]: Submodule "bbf-fast-service-profiles" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-spectrum-profiles".
netopeer2-server[13119]: Reading module "bbf-yang-types".
netopeer2-server[13119]: Module "bbf-yang-types" already in context.
netopeer2-server[13119]: Module "bbf-yang-types" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-line-spectrum-profile-body".
netopeer2-server[13119]: Submodule "bbf-fast-line-spectrum-profile-body" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-upstream-power-back-off-profile-body".
netopeer2-server[13119]: Submodule "bbf-fast-upstream-power-back-off-profile-body" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-rfi-profile-body".
netopeer2-server[13119]: Submodule "bbf-fast-rfi-profile-body" successfully parsed.
netopeer2-server[13119]: Submodule "bbf-fast-spectrum-profiles" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-quality-profiles".
netopeer2-server[13119]: Reading module "bbf-yang-types".
netopeer2-server[13119]: Module "bbf-yang-types" already in context.
netopeer2-server[13119]: Module "bbf-yang-types" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-fast-rate-adaptation-profile-body".
netopeer2-server[13119]: Submodule "bbf-fast-fast-rate-adaptation-profile-body" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-noise-margin-profile-body".
netopeer2-server[13119]: Submodule "bbf-fast-noise-margin-profile-body" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-fast-retrain-policy-profile-body".
netopeer2-server[13119]: Submodule "bbf-fast-fast-retrain-policy-profile-body" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-retransmission-profile-body".
netopeer2-server[13119]: Submodule "bbf-fast-retransmission-profile-body" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-vectoring-profile-body".
netopeer2-server[13119]: Submodule "bbf-fast-vectoring-profile-body" successfully parsed.
netopeer2-server[13119]: Submodule "bbf-fast-quality-profiles" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-tdd-profiles".
netopeer2-server[13119]: Reading module "bbf-yang-types".
netopeer2-server[13119]: Module "bbf-yang-types" already in context.
netopeer2-server[13119]: Module "bbf-yang-types" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-tdd-profile-body".
netopeer2-server[13119]: Submodule "bbf-fast-tdd-profile-body" successfully parsed.
netopeer2-server[13119]: Submodule "bbf-fast-tdd-profiles" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-threshold-management".
netopeer2-server[13119]: Reading module "bbf-yang-types".
netopeer2-server[13119]: Module "bbf-yang-types" already in context.
netopeer2-server[13119]: Module "bbf-yang-types" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-perf-types".
netopeer2-server[13119]: Resolving derived type "performance-15min-interval" failed, it will be attempted later.
netopeer2-server[13119]: Resolving type default "" failed, it will be attempted later.
netopeer2-server[13119]: Resolving derived type "performance-24hr-interval" failed, it will be attempted later.
netopeer2-server[13119]: Resolving type default "" failed, it will be attempted later.
netopeer2-server[13119]: Submodule "bbf-fast-perf-types" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-line-threshold-profile-body".
netopeer2-server[13119]: Submodule "bbf-fast-line-threshold-profile-body" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-channel-threshold-profile-body".
netopeer2-server[13119]: Submodule "bbf-fast-channel-threshold-profile-body" successfully parsed.
netopeer2-server[13119]: Submodule "bbf-fast-threshold-management" successfully parsed.
netopeer2-server[13119]: Resolving if-feature "performance-24hr" failed, it will be attempted later.
netopeer2-server[13119]: Resolving if-feature "performance-24hr" failed, it will be attempted later.
netopeer2-server[13119]: Resolving if-feature "performance-24hr" failed, it will be attempted later.
netopeer2-server[13119]: Resolving if-feature "performance-24hr" failed, it will be attempted later.
netopeer2-server[13119]: Submodule "bbf-fast-pointers" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-test-diagnostics".
netopeer2-server[13119]: Reading module "ietf-interfaces".
netopeer2-server[13119]: Module "ietf-interfaces" already in context.
netopeer2-server[13119]: Module "ietf-interfaces" successfully parsed.
netopeer2-server[13119]: Reading module "bbf-fastdsl".
netopeer2-server[13119]: Module "bbf-fastdsl" already in context.
netopeer2-server[13119]: Module "bbf-fastdsl" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-test-mode-body".
netopeer2-server[13119]: Submodule "bbf-fast-test-mode-body" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-update-test-body".
netopeer2-server[13119]: Submodule "bbf-fast-update-test-body" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-link-state-body".
netopeer2-server[13119]: Submodule "bbf-fast-link-state-body" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-read-test-body".
netopeer2-server[13119]: Reading submodule "bbf-fast-line-status-body".
netopeer2-server[13119]: Reading module "bbf-yang-types".
netopeer2-server[13119]: Module "bbf-yang-types" already in context.
netopeer2-server[13119]: Module "bbf-yang-types" successfully parsed.
netopeer2-server[13119]: Submodule "bbf-fast-line-status-body" successfully parsed.
netopeer2-server[13119]: Submodule "bbf-fast-read-test-body" successfully parsed.
netopeer2-server[13119]: Submodule "bbf-fast-test-diagnostics" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-performance-management".
netopeer2-server[13119]: Reading module "ietf-interfaces".
netopeer2-server[13119]: Module "ietf-interfaces" already in context.
netopeer2-server[13119]: Module "ietf-interfaces" successfully parsed.
netopeer2-server[13119]: Reading module "bbf-fastdsl".
netopeer2-server[13119]: Module "bbf-fastdsl" already in context.
netopeer2-server[13119]: Module "bbf-fastdsl" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-line-performance-body".
netopeer2-server[13119]: Reading module "bbf-yang-types".
netopeer2-server[13119]: Module "bbf-yang-types" already in context.
netopeer2-server[13119]: Module "bbf-yang-types" successfully parsed.
netopeer2-server[13119]: Resolving derived type "performance-15min-history-interval" failed, it will be attempted later.
netopeer2-server[13119]: Resolving derived type "performance-24hr-history-interval" failed, it will be attempted later.
netopeer2-server[13119]: Submodule "bbf-fast-line-performance-body" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-channel-performance-body".
netopeer2-server[13119]: Reading module "bbf-yang-types".
netopeer2-server[13119]: Module "bbf-yang-types" already in context.
netopeer2-server[13119]: Module "bbf-yang-types" successfully parsed.
netopeer2-server[13119]: Resolving derived type "performance-15min-history-interval" failed, it will be attempted later.
netopeer2-server[13119]: Resolving derived type "performance-24hr-history-interval" failed, it will be attempted later.
netopeer2-server[13119]: Submodule "bbf-fast-channel-performance-body" successfully parsed.
netopeer2-server[13119]: Resolving uses "line-performance" failed, it will be attempted later.
netopeer2-server[13119]: Resolving uses "channel-performance" failed, it will be attempted later.
netopeer2-server[13119]: Submodule "bbf-fast-performance-management" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-status-monitoring".
netopeer2-server[13119]: Reading module "ietf-interfaces".
netopeer2-server[13119]: Module "ietf-interfaces" already in context.
netopeer2-server[13119]: Module "ietf-interfaces" successfully parsed.
netopeer2-server[13119]: Reading module "bbf-fastdsl".
netopeer2-server[13119]: Module "bbf-fastdsl" already in context.
netopeer2-server[13119]: Module "bbf-fastdsl" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-channel-status-body".
netopeer2-server[13119]: Reading module "bbf-yang-types".
netopeer2-server[13119]: Module "bbf-yang-types" already in context.
netopeer2-server[13119]: Module "bbf-yang-types" successfully parsed.
netopeer2-server[13119]: Submodule "bbf-fast-channel-status-body" successfully parsed.
netopeer2-server[13119]: Submodule "bbf-fast-status-monitoring" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-inventory".
netopeer2-server[13119]: Reading module "ietf-interfaces".
netopeer2-server[13119]: Module "ietf-interfaces" already in context.
netopeer2-server[13119]: Module "ietf-interfaces" successfully parsed.
netopeer2-server[13119]: Reading module "bbf-fastdsl".
netopeer2-server[13119]: Module "bbf-fastdsl" already in context.
netopeer2-server[13119]: Module "bbf-fastdsl" successfully parsed.
netopeer2-server[13119]: Reading submodule "bbf-fast-ftu-inventory-body".
netopeer2-server[13119]: Submodule "bbf-fast-ftu-inventory-body" successfully parsed.
netopeer2-server[13119]: Submodule "bbf-fast-inventory" successfully parsed.
netopeer2-server[13119]: Resolving "bbf-fast" unresolved schema nodes and their constraints...
netopeer2-server[13119]: All "bbf-fast" schema nodes and constraints resolved.
netopeer2-server[13119]: Module "bbf-fast" successfully parsed.
netopeer2-server[13119]: Loading schema "ietf-interfaces@2014-05-08" from sysrepo.
netopeer2-server[13119]: Module ietf-interfaces@2014-05-08 already present in context.
netopeer2-server[13119]: Loading schema "bbf-fastdsl@2016-07-18" from sysrepo.
netopeer2-server[13119]: Module bbf-fastdsl@2016-07-18 already present in context.
netopeer2-server[13119]: Loading schema "iana-if-type@2016-06-09" from sysrepo.
netopeer2-server[13119]: Module iana-if-type@2016-06-09 already present in context.
netopeer2-server[13119]: Loading schema "bbf-yang-types@2016-06-08" from sysrepo.
netopeer2-server[13119]: Module bbf-yang-types@2016-06-08 already present in context.
netopeer2-server[13119]: Loading schema "ietf-entity@2015-10-19" from sysrepo.
netopeer2-server[13119]: Reading module "ietf-entity".
netopeer2-server[13119]: Module "ietf-entity" successfully parsed.
netopeer2-server[13119]: Loading schema "ietf-netconf-acm@2012-02-22" from sysrepo.
netopeer2-server[13119]: Reading module "ietf-netconf-acm".
netopeer2-server[13119]: Resolving "ietf-netconf-acm" unresolved schema nodes and their constraints...
netopeer2-server[13119]: All "ietf-netconf-acm" schema nodes and constraints resolved.
netopeer2-server[13119]: Module "ietf-netconf-acm" successfully parsed.
netopeer2-server[13119]: Loading schema "ietf-netconf@2011-06-01" from sysrepo.
netopeer2-server[13119]: Reading module "ietf-netconf".
netopeer2-server[13119]: Module "ietf-netconf" successfully parsed.
netopeer2-server[13119]: Loading schema "ietf-netconf-with-defaults@2011-06-01" from sysrepo.
netopeer2-server[13119]: Reading module "ietf-netconf-with-defaults".
netopeer2-server[13119]: Reading module "ietf-netconf".
netopeer2-server[13119]: Module "ietf-netconf" already in context.
netopeer2-server[13119]: Module "ietf-netconf" successfully parsed.
netopeer2-server[13119]: Module "ietf-netconf-with-defaults" successfully parsed.
netopeer2-server[13119]: Loading schema "ietf-netconf-notifications@2012-02-06" from sysrepo.
netopeer2-server[13119]: Reading module "ietf-netconf-notifications".
netopeer2-server[13119]: Reading module "ietf-netconf".
netopeer2-server[13119]: Module "ietf-netconf" already in context.
netopeer2-server[13119]: Module "ietf-netconf" successfully parsed.
netopeer2-server[13119]: Resolving XPath expressions of "killed-by" failed, it will be attempted later.
netopeer2-server[13119]: Resolving XPath expressions of "common-session-parms" failed, it will be attempted later.
netopeer2-server[13119]: Resolving "ietf-netconf-notifications" unresolved schema nodes and their constraints...
netopeer2-server[13119]: Schema node "confirm-event" not found (../confirm-event).
netopeer2-server[13119]: Invalid when condition "../confirm-event != 'timeout'". (/ietf-netconf-notifications:netconf-confirmed-commit/common-session-parms)
netopeer2-server[13119]: All "ietf-netconf-notifications" schema nodes and constraints resolved.
netopeer2-server[13119]: Module "ietf-netconf-notifications" successfully parsed.
netopeer2-server[13119]: Reading module "ietf-netconf-monitoring".
netopeer2-server[13119]: Module "ietf-netconf-monitoring" successfully parsed.
netopeer2-server[13119]: Sysrepo does not have the "ietf-netconf-server" module or keystored keys dir unknown, using default NETCONF server options.
netopeer2-server[13119]: Listening on 0.0.0.0:6001 for SSH connections.


netopeer2-server[13119]: Accepted a connection on 0.0.0.0:6001.
[1970/01/01 00:29:54.755011, 1] ssh_server_connection_callback: SSH client banner: SSH-2.0-paramiko_1.16.0
[1970/01/01 00:29:54.755303, 1] ssh_analyze_banner: Analyzing banner: SSH-2.0-paramiko_1.16.0
[1970/01/01 00:29:54.968477, 2] ssh_packet_newkeys: Received SSH_MSG_NEWKEYS
netopeer2-server[13119]: Received an SSH message "request-service" of subtype "ssh-userauth".
netopeer2-server[13119]: Received an SSH message "request-auth" of subtype "password".
netopeer2-server[13119]: User "root" authenticated.
netopeer2-server[13119]: Received an SSH message "request-channel-open" of subtype "session".
netopeer2-server[13119]: Received an SSH message "request-channel" of subtype "subsystem".
[1970/01/01 00:29:55.031568, 2] grow_window: growing window (channel 43:0) to 1280000 bytes
netopeer2-server[13119]: Resolving unresolved data nodes and their constraints...
netopeer2-server[13119]: All data nodes and constraints resolved.
netopeer2-server[13119]: Unknown element "class". (/ietf-entity:entity/physical-entity[name='test_port_1'])
netopeer2-server[13119]: Session 1: thread 3 event new RPC.
netopeer2-server[13119]: Session 1: thread 3 event reply error.

**Comment by rkrejci** [comment]
Do you have `bbf-entity-extension` in sysrepo context? Because netopeer-server does not have this module so it does not accept the data defined in this module. Please provide the output of 
```
# sysrepoctl --list
```

**Comment by betsyrosemanuel** [comment]
I was able to perform edit config with the same xml previously using the old master branch. I recall having done it successfully without installing the "bbf-entity-extension" using sysrepoctl.

**Comment by betsyrosemanuel** [comment]
the output of the command `sysrepoctl --list`
LIBYANG_EXTENSIONS_PLUGINS_DIR=/usr/lib/libyang ./sysrepoctl --l
ist
Sysrepo schema directory: /etc/sysrepo/yang/
Sysrepo data directory:   /etc/sysrepo/data/
(Do not alter contents of these directories manually)

Module Name                   | Revision   | Data Owner          | Permissions | Submodules                    | Enabled Features
---------------------------------------------------------------------------------------------------------------------------------
bbf-fast                      | 2016-09-23 | root:root           | 666         |  bbf-fast-base bbf-fast-data-rate-profile-body bbf-fast-service-profiles bbf-fast-line-spectrum-profile-body bbf-fast-upstream-power-back-off-profile-body bbf-fast-rfi-profile-body bbf-fast-spectrum-profiles bbf-fast-fast-rate-adaptation-profile-body bbf-fast-noise-margin-profile-body bbf-fast-fast-retrain-policy-profile-body bbf-fast-retransmission-profile-body bbf-fast-vectoring-profile-body bbf-fast-quality-profiles bbf-fast-tdd-profile-body bbf-fast-tdd-profiles bbf-fast-perf-types bbf-fast-line-threshold-profile-body bbf-fast-channel-threshold-profile-body bbf-fast-threshold-management bbf-fast-pointers bbf-fast-test-mode-body bbf-fast-update-test-body bbf-fast-link-state-body bbf-fast-line-status-body bbf-fast-read-test-body bbf-fast-test-diagnostics bbf-fast-line-performance-body bbf-fast-channel-performance-body bbf-fast-performance-management bbf-fast-channel-status-body bbf-fast-status-monitoring bbf-fast-ftu-inventory-body bbf-fast-inventory|
ietf-interfaces               | 2014-05-08 | root:root           | 666         |                               |
bbf-fastdsl                   | 2016-07-18 |                     |             |                               |
iana-if-type                  | 2016-06-09 |                     |             |                               |
bbf-yang-types                | 2016-06-08 |                     |             |                               |
ietf-entity                   | 2015-10-19 | root:root           | 666         |                               | entity-config entity-state
ietf-netconf-acm              | 2012-02-22 | root:root           | 666         |                               |
ietf-netconf                  | 2011-06-01 | root:root           | 666         |                               |
ietf-netconf-with-defaults    | 2011-06-01 |                     |             |                               |
ietf-netconf-notifications    | 2012-02-06 | root:root           | 666         |                               |
bbf-entity-extension          | 2016-07-07 |                     |             |                               |

**Comment by betsyrosemanuel** [comment]
hii. i installed iana-entity module as well. It worked. Thanks
