### ISSUE TITLE
cannot install module

### ISSUE THREAD

**Issue by betsyrosemanuel** [sysrepo/sysrepo#772]
Hi, 
    I was unable to install the module "bbf-interface-port-reference" and got the following error

No resolvents found for leafref "/ietf-entity:entity/ietf-entity:physical-entity/ietf-entity:name".
[ERR] (srctl_ly_log_cb:479) libyang: Leafref is not conditional based on "entity-config" feature as its target.
[ERR] (srctl_ly_log_cb:479) libyang: Module "bbf-interface-port-reference" parsing failed.
Error: Unable to load the module by libyang.
Install operation failed.

**Comment by michalvasko** [comment]
Hi,
please do not duplicate issues, also started in libyang as issue number 305.
