### ISSUE TITLE
About sysrepo data stored as xml files 

### ISSUE THREAD

**Issue by fanchanghu** [sysrepo/sysrepo#774]
Hi,
This is a question about reliability, we know that many devices need high reliability, especially in CT area. But sysrepo stored data as xml files, the files may break in some extreme situation, such as the power is off when we are writing files, this could make the device can not work normally in next power-on.
I suggest to store data in some reliable form, such as a database like sqlite, or just leave an interface or plugin mechanism to make users can implement this themselves.
Thanks.

**Comment by rkrejci** [comment]
This will need support in libyang, which expect this way of enahncement, but not directly in a form of plugins. It will still need some (small) changes in sysrepo code then, but the first step is definitely support for storing and loading data in such format in libyang.
