### ISSUE TITLE
cmake crashes on devel branch on arch liunx

### ISSUE THREAD

**Issue by mislavn** [sysrepo/sysrepo#780]
Cmake breaks when sysrepo devel branch is build on Arch liunx.
The error is:

CMake Error at examples/cmake_install.cmake:47 (message):
  Error: Segmentation fault
Call Stack (most recent call first):
  cmake_install.cmake:162 (include)

make: *** [Makefile:116: install] Error 1

It is build with the [dockerfile](https://github.com/sysrepo/sysrepo/blob/devel/deploy/docker/sysrepo-netopeer2/platforms/Dockerfile.arch.devel)

The build command is:
docker build -t sysrepo/sysrepo-netopeer2:arch_devel -f Dockerfile.arch.devel .

**Comment by mislavn** [comment]
The bug occurs only during the bulid of the dockerfile, inside a running docker container the command works.

**Comment by mislavn** [comment]
The problem is connected to the cmake command: execute_process

https://cmake.org/pipermail/cmake/2016-March/063074.html

This bug can be fixed if the command "make install" is run with "-j4".

I will make some changes to the cmake file.

**Comment by jktjkt** [comment]
If it is indeed cmake which segfaults, it's a bug within cmake. You should report that to your vendor (Arch in this case), and if the latest cmake from cmake.org segfaults as well, then also to cmake upstream.

Are you sure that the reported error is not about an executed program which happened to segfault, though?

**Comment by mislavn** [comment]
> Are you sure that the reported error is not about an executed program which happened to segfault, though?

Yes, if I run the command in the shell it works, also if I run "make install" with " -j4".

I think the problem is that in the macro INSTALL_EXAMPLE_YANG there are two EXEC_AT_INSTALL_TIME macro's which contain execute_process.

http://www.cmake.org/cmake/help/cmake2.6docs.html#command:execute_process

  "Runs the given sequence of one or more commands with the standard
   output of each process piped to the standard input of the next.  A
   single standard error pipe is used for all processes."

I will try to make the macro INSTALL_EXAMPLE_YANG sequential.

**Comment by mislavn** [comment]
I made a pull request to fix this https://github.com/sysrepo/sysrepo/pull/784.

The fix is that now the macro INSTALL_EXAMPLE_YANG does not run "sysrepoctl ..." then "sysrepocfg ..." but "sysrepoctl ...; sysrepocfg ...".

There is still one problem in the docker build of Arch linux, I am not sure is it connected to sysrepo.
