### ISSUE TITLE
About error-app-tag support in rpc-error

### ISSUE THREAD

**Issue by qmm161** [sysrepo/sysrepo#786]
error-app-tag is defined in RFC 6241 and can be used to return the data-model-specific or implementation-specific error by client in commit-verify or user-defined rpc.

i wondered if sysrepo has any plan to implement this tag.

**Comment by michalvasko** [comment]
Hi,
did you try it? *libyang* supports it, so the only question is ,when the error is generated whether it bubbles through *sysrepo* to *netopeer2-server*. I think it should.

Regards,
Michal

**Comment by qmm161** [comment]
Hi,
I don't know what did you mean "libyang supports it", maybe there are some understanding.

I tried to set _Sr__Error_ of _Sr__Response_ in _cl_sm_rpc_process_ when user-defined error generated and add some code to deal with _Sr_Error_ in _rp_rpc_resp_process_,  finally I got the error-message displayed in _netopeer2-cli_. 

However, when I discussed this with other guys we find the really thing we wanted to implement is **error-app-tag** not  **error-message**

**Comment by michalvasko** [comment]
Hi,
please try it yourself, it is fully handled by *libyang*, so you are not going to find anything about it in *sysrepo* or *netopeer2-server*. Just define an `error-app-tag` in some model and then try setting a configuration that would break it. You should see the app-tag in *netopeer2-cli*.

Regards,
Michal

**Comment by qmm161** [comment]
_error-app-tag_  is defined in [RFC 6241](https://tools.ietf.org/html/rfc6241#section-4.3), if I define an _error-app-tag_ in rpc output, when error generated I will get a _rpc-reply_  but what I wished is a  _rpc-error_

**Comment by rkrejci** [comment]
What do you mean by "define an error-app-tag in rpc output"? `error-app-tag` is YANG statement allowed as substatement to `must`, `range`, `length` and `pattern` statements. If you define a leaf in RPC's output, that is just a leaf named error-app-tag but it has nothing to do with the error-app-tag in RPC error reply.

**Comment by qmm161** [comment]
RFC 6241 says:
```
   error-app-tag:  Contains a string identifying the data-model-specific
      or implementation-specific error condition, if one exists.  This
      element will not be present if no appropriate application error-
      tag can be associated with a particular error condition.  If a
      data-model-specific and an implementation-specific error-app-tag
      both exist, then the data-model-specific value MUST be used by the
      server.
```  

And I want to get an `<rpc-error>` from netopeer server like this:
```
     <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
       <rpc-error>
         <error-type>rpc</error-type>
         <error-tag>operation-failed</error-tag>
		 **<error-app-tag>a custom error tag</error-app-tag>**
         <error-severity>error</error-severity>
       </rpc-error>
     </rpc-reply>
```

The `error-app-tag` can be `data-model-specific` or `implementation-specific`, and I want to set it not in yang modules but in my code for RPC output, however, it seems there is no interface to do so in sysrepo.

**Comment by michalvasko** [comment]
Hi,
you are right, it is currently not possible to reply to an RPC with any error. It would be a nice enhancement, but it is not a priority, so maybe later.

Regards,
Michal

**Comment by kpbarrett** [comment]
Putting in my vote for the ability to send an error in reply to a user RPC. :sunglasses:

**Comment by lin13051275755** [comment]
> Putting in my vote for the ability to send an error in reply to a user RPC. 😎
I have the same issues ;can you give a help;

**Comment by lin13051275755** [comment]
@kpbarrett I have the same issues ;can you give a help;

**Comment by michalvasko** [comment]
Hi,
the new *sysrepo* (found in `devel` branch) supports returning errors from RPCs including specific error messages. However, setting custom `error-app-tag` is not supported and I do not think it should be. It can be defined only for `range`, `length`, `pattern`, and `must` YANG statements and in these cases the error is generated by *libyang*, which uses the correct custom app tag.

Regards,
Michal
