### ISSUE TITLE
module implemented, latest_revision flags

### ISSUE THREAD

**Issue by michalvasko** [sysrepo/sysrepo#790]
Currently mean:
  - `implemented` - whether the module was explicitly installed or only imported by some other module (if 2 revisions of a module are explicitly installed, they both have implemented flag),
  - `latest_revision` - whether the module is in latest revision irrespective of implemented flag

`latest_revision` is used when subscribing to module changes. This leads to a problem, if there is module `A@1` and module `B` that imports `A@2`. The imported module will have the newest revision and therefore all subscriptions will incorrectly use it. Also, with their current meaning they cause problems for *netopeer2-server*.

We propose the following:
  - `implemented` will be set only for modules that are truly implemented, so, for instance, 2 revisions of one module cannot be both implemented. Also, this flag will be used when subscribing to module changes,
  - `latest_revision` keeps its meaning,
  - using *sysrepoctl* - if a module is already installed and another revision is installed - return error? replace the module?

**Comment by michalvasko** [comment]
The aforementioned changes are implemented and should be working except one enhancement:
  - add an option to replace the already-implemented module (keeping its meta-data and data) when installing another revision of an implemented module

**Comment by rkrejci** [comment]
The remaining feature duplicates #287
