### ISSUE TITLE
app_name needed in sysrepo's change callback

### ISSUE THREAD

**Issue by fanchanghu** [sysrepo/sysrepo#794]
Hi,
in some of my cases, part of config data can only be changed by the device itself, so I hope to get the app_name (defined as first parameter in `sr_connect`) where the change comes in sysrepo's change callback, then I can verify or apply the change according to it.

**Comment by michalvasko** [comment]
Hi,
all the *sysrepo* change callback setters have an option to pass arbitrary data (`private_ctx`) to the callback, can't you put your `app_name` there?

Regards,
Michal

**Comment by fanchanghu** [comment]
Hi,
I do not mean the `app_name` where the callback is set, I mean the `app_name` where the operation comes.
For example, I changed some data from netopeer-server, then, I need get  the `app_name` of  netopeer-server in my callback, I can't set it in the callback setter.

**Comment by rkrejci** [comment]
Hi, but if the data can be changed only by the device, then it is not configuration data (`config true;` according to YANG language), right? I think that then the data should be defined as `config false` and the device can change it on its own and just provide status value to sysrepo. Or am I missing something?

**Comment by rkrejci** [comment]
I'm afraid that you are not able to model this by YANG. But you example is like network interfaces (ietf-interfaces). The idea is that despite the network-interface (sub-device) can be created only by the system, user provides configuration and even configuration for non-existing (currently not present) interface can be provided, but it is simply ignored. So try to inspire yourself.

Improvement will probably come with the revised datastore concept currently being discussed in IETF, which specifies concept of applied and operational data, but it will take some time before it will be implemented in sysrepo.

**Comment by fanchanghu** [comment]
yes, it is something like ietf-interfaces, maybe I can model it like that, thanks for the suggestion.
