### ISSUE TITLE
Some questions regarding handling read-only parameters in yang model

### ISSUE THREAD

**Issue by anithacp** [sysrepo/sysrepo#829]
Our embedded system uses the BBF VDSL yang template. In the tree, bbf-vdsl-full.tree (attached)
module: ietf-interfaces
   +--rw interfaces
   +--ro interfaces-state

The 'interfaces' defines all the configuration parameters that can be modified from the netopeer client. I understand that we would have an application running on our system which would subscribe for change notifications to this module to get the notifications.

Some doubts:
1. Is it required to import the 'interfaces-state' (operating status data, not config data) information to the sysrepo startup datastore? If yes, how?
    Does sysrepo datastore only store config data (where does the operating status data get stored?).

I tried importing a configuration for interfaces-state to the startup datastore. Though it says its successful, when I export it to a file, there is nothing in the file.
```
<?xml version="1.0" encoding="utf-8"?>
<interfaces-state xmlns="urn:ietf:params:xml:ns:yang:interfaces-state"
xmlns:fastdsl="urn:bbf:yang:bbf-fastdsl"
xmlns:vdsl="urn:bbf:yang:bbf-vdsl">
    <interface>
        <name>UNI-1</name>
        <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:fastdsl</type>
        <admin-status>0</admin-status>
        <oper-status>0</oper-status>
        <fastdsl:line>
             <fastdsl:operational-mode>0</fastdsl:operational-mode>
             <vdsl:line>
                 <vdsl:channel>
                      <vdsl:status>
                          <vdsl:xtu-c>
                              <vdsl:upstream>
                                 <vdsl:actual-data-rate>40000</vdsl:actual-data-rate>
                              </vdsl:upstream>
                          </vdsl:xtu-c>
                          <vdsl:xtu-r>
                              <vdsl:downstream>
                                 <vdsl:actual-data-rate>1000000</vdsl:actual-data-rate>
                              </vdsl:downstream>
                          </vdsl:xtu-r>
                      </vdsl:status>
                 </vdsl:channel>
             </vdsl:line>
        </fastdsl:line>
    </interface>
</interfaces-state>

sudo sysrepocfg --import=/tmp/interface-state-startup-cfg.xml --datastore=startup --format=xml ietf-interfaces
[INF] (srcfg_ly_log_cb:89) libyang: Resolving unresolved data nodes and their constraints... ((null))
[INF] (srcfg_ly_log_cb:89) libyang: All data nodes and constraints resolved. ((null))
The new configuration was successfully applied.

sudo sysrepocfg --export=/tmp/backup.xml --format=xml --datastore=startup ietf-interfaces
The configuration was successfully exported.

ls -l /tmp/backup.xml
-rw-r--r-- 1 root root 0 Apr 28 13:56 /tmp/backup.xml
```

2. When a 'get' request is coming for " ietf-interfaces/interfaces-state" (operating status data, not config data), should it be provided by a data-provider application or is possible to get it from one of the sysrepo data stores.

3. In our system, we have DSL ports. If the DSL line goes down due to say loss of sync with the CPE, there is an alarm generated for the OMCI interface to the OLT. Is there any similar notification mechanism to the netopeer client? 
There are no 'notification' elements in the bbf-vdsl-full yang model. So how does the netopeer client get notified in these scenarios?

Thankyou.

[bbf-vdsl-full-tree.txt](https://github.com/sysrepo/sysrepo/files/967300/bbf-vdsl-full-tree.txt)

**Comment by michalvasko** [comment]
Hi,

1.) State data cannot be imported in *sysrepo* datastore, it stores only config data.

2.) Based on what I said, it is not possible to get it from a datastore, it must always be provided by an application before replying to a `get` RPC. The idea here is that it is useless to store this information and then update it when a change occurs, it is simply retrieved from the application, which knows its state information at all times.

3.) Yes, *netopeer2-cli* supports [NETCONF notifications](https://tools.ietf.org/html/rfc5277.html), but as you correctly observed, there are none defined in `bbf-vdsl` yang model, so no notifications will be generated. However, you can easily create a separate model with only notifications, which can be generated on any system event but you must implement them yourself.

Regards,
Michal

**Comment by anithacp** [comment]
Thanks a lot, Michal for the explanation. We would be having an application which will subscribe to changes to ietf-interfaces module as well as the bbf-vdsl module. This application would also be the data provider to provide the state data.

**Comment by michalvasko** [comment]
Hi,
I just want to make it clear that without adding any YANG model or notifications, you can still get *notified* in your application about a change the way you described (subscribing directly to changes in the model/configuration subtree) or subscribe to the `netconf-config-change` notification, which gets generated on any configuration change. The former is simpler, more straightforward, and likely more effective, but  just wanted to point this out.

Regards,
Michal

**Comment by RongfuQian** [comment]
Hi,
One more question: Where are these RO parameters are configured? For example:
ietf-interfaces.yang: (revision 2018-02-20)
 "higher-layer-if / lower-layer-if" are "config false" parameters which means we can not configure them in the ietf-interfaces datastore. 
But i think somewhere should configure both of these parameters together with the unique ietf-interface (key "name"). So that the relationship/mapping among: higher-layer-if, ietf-interface, lower-layer-if is build. 
If my thought is correct, then, how or where can i found the configuration of these RO parameters ("higher-layer-if / lower-layer-if" in above example);
If my thought is wrong, then, where these RO parameters' values come from?

Thank you.
Rongfu

**Comment by michalvasko** [comment]
Hi,
firstly, you should have created a new issue instead of replying to a 2 year old thread. But, state data work differently compared to configuration data, which is quite natural. The application is supposed to provide them using [these](http://www.sysrepo.org/static/doc/html/subscribtions.html#data_providers) callbacks.

Regards,
Michal

**Comment by RongfuQian** [comment]
Thank you very much, Michal. 
Sorry for didn't create a new issue. I'll keep it in my mind. 

B.R
Rongfu
