### ISSUE TITLE
Error when running sysrepo commands - libyang.so.12 not found

### ISSUE THREAD

**Issue by sankettandulwadkar** [sysrepo/sysrepo#841]
Hi,

I am trying to run the  sysrepo and I keep getting the libyang error saying it is not installed, even though it is.

sanket@sanket-HP-Compaq-8200-Elite-CMT-PC:~/sysrepo/build$ sysrepocfg 
sysrepocfg: error while loading shared libraries: libyang.so.0.12: cannot open shared object file: No such file or directory

Install the project...
-- Install configuration: "debug"
-- Installing: /usr/local/lib/libyang.so.0.12.170
-- Up-to-date: /usr/local/lib/libyang.so.0.12
-- Up-to-date: /usr/local/lib/libyang.so
-- Up-to-date: /usr/local/include/libyang/libyang.h
-- Up-to-date: /usr/local/include/libyang/tree_schema.h
-- Up-to-date: /usr/local/include/libyang/tree_data.h
-- Up-to-date: /usr/local/include/libyang/extensions.h
-- Up-to-date: /usr/local/include/libyang/xml.h
-- Up-to-date: /usr/local/include/libyang/dict.h
-- Installing: /usr/local/lib/pkgconfig/libyang.pc
-- Installing: /usr/local/bin/yanglint
-- Set runtime path of "/usr/local/bin/yanglint" to ""
-- Up-to-date: /usr/local/share/man/man1/yanglint.1
-- Installing: /usr/local/lib/libyang/nacm.so
-- Set runtime path of "/usr/local/lib/libyang/nacm.so" to ""
-- Installing: /usr/local/lib/libyang/metadata.so
-- Set runtime path of "/usr/local/lib/libyang/metadata.so" to ""

Do I have to somehow link this to the build? If so, could you please tell me the steps for the same.

Thanks,
Sanket

**Comment by michalvasko** [comment]
Hi Sanket,
try executing `# ldconfig` and then try again. If that does not help, you can check that *libyang* is properly installed using `# ldconfig -p | grep libyang`. If it does not print anything then it was installed in a location where it was not found. In that case you can either make `ldconfig` look for libraries in that additional path or install *libyang* to a path `ldconfig` already searches.

Regards,
Michal

**Comment by sankettandulwadkar** [comment]
Thanks! That worked. I was also wondering if there is any way I can link
sysrepo to a webserver like Apache or Lighty to use as a RESTconf server
middleman.

**Comment by rkrejci** [comment]
Hi, you can access sysrepo as NETCONF datastore from your RESTCONF server as [Netopeer2](https://github.com/CESNET/netopeer2) does (as NETCONF server).

**Comment by sankettandulwadkar** [comment]
I tried using the sysrepocfg command to get a yang model I added, but I get
an error saying no active subscriptions for it on the running datastore.
How do i  resolve this?

**Comment by michalvasko** [comment]
Hi,
the simple answer is, create some active subscriptions for it. If you had some basic knowledge about *sysrepo*, you would now what that means and how to do it. If you don't, then you cannot expect me to explain it to you, there is [documentation](http://www.sysrepo.org/static/doc/html/index.html) and [examples](https://github.com/sysrepo/sysrepo/tree/master/examples).

Regards,
Michal

**Comment by rkrejci** [comment]
Please do not mix different issues in a single thread.
