### ISSUE TITLE
quesion:is it necessary to provide a batch  set item interface to support big data modify

### ISSUE THREAD

**Issue by ostack** [sysrepo/sysrepo#843]
quesion:is it necessary to provide a batch  set item interface to support big data modify

**Comment by jktjkt** [comment]
I do not understand this question. What are you trying to do, what steps have you tried so far? What is the result that you're seeing, and what you hope to see?

**Comment by ostack** [comment]
the sysrepo provide a interface set-item ,and it must encode&decode the data at the client and server,  when there is few  of items  it may be OK ,but when it has lot of items to set ,we must think about the  efficiency of encode and decode ,so i wonder if it more efficient to provide an interface allow user to set batch items

**Comment by jktjkt** [comment]
If you are worried about performance, then measure how well your system performs and identify actual bottlenecks. It's possible that a lack of a batched-set-item API *is* one, but before you perform these measurements, we do not really know. It is not a good idea to optimize based on gut feeling.
