### ISSUE TITLE
Success story tracker for Sysrepo suite v0.6.x

### ISSUE THREAD

**Issue by mikaabra** [sysrepo/sysrepo#844]
This is to track success stories of using Sysrepo v0.6.x.

Please post in this issue if you have positive experience with Sysrepo and if you want to, what you managed to do using Sysrepo. It's great to know the software is useful and also if possible, what it's used for (or planned to be used for if you have successfully started managed to get started with Sysrepo and plan to extend it in some way).

**Comment by jktjkt** [comment]
We're currently using sysrepo for providing NETCONF access to our [DWDM Open Line System](https://czechlight.cesnet.cz/en/network-elements). We're very happy with the result so far, and we got involved in the upstream development as well.

**Comment by michalvasko** [comment]
Not relevant anymore.
