### ISSUE TITLE
How to construct sr_val_t for LY_TYPE_UNION ?

### ISSUE THREAD

**Issue by ostack** [sysrepo/sysrepo#848]
when i construct sr_val_t, i found there is no type union in **sr_type_t** and  **sr_data_t**   to match LY_TYPE_UNION ,so i want to know how to construct sr_val_t for LY_TYPE_UNION

**Comment by jktjkt** [comment]
In my code, I never instantiate the entire union directly. It's always an union of a set of some other types, so I construct one of these types directly.

**Comment by michalvasko** [comment]
Hi,
when you are creating data tree nodes, you should always know what is the actual type of the value, so there is no need to create ambiguous nodes with undefined types. If you notice, *libyang* does not allow to create union data nodes either, there is no real use.

Regards,
Michal

**Comment by ostack** [comment]
I see ,thanks
