### ISSUE TITLE
Namespace problem while filling in read only data in Data Provider

### ISSUE THREAD

**Issue by bharath154** [sysrepo/sysrepo#860]
### Things you may try first
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description
I am trying to implement data provider for processing read-only (operational) data for our embedded system with a DSL stack [bbf-vdsl-full.tree 
](https://github.com/sysrepo/sysrepo/files/967378/bbf-vdsl-full-tree.txt).

While implementing the data provider, I have noticed that after populating the relevant interfaces, I am getting callbacks for the entire tree, but without name spaces attached like "/ietf-interfaces:interfaces-state/interface[name='vdsl-1']/line/line/inventory/xtu-c".

But, for filling in values, I am forced to fill in the nodes with namespaces prefixed like 
"/ietf-interfaces:interfaces-state/interface[name='vdsl-1']/bbf-fastdsl:line/bbf-vdsl:line/bbf-vdsl:inventory/bbf-vdsl:xtu-c/bbf-vdsl:self-test-result".

Is this by design, or am I missing something?

### Steps to Reproduce
1. Populate the relevant interfaces as part of the data provider callback, 
sr_val_build_xpath(&v[i], "/ietf-interfaces:interfaces-state/interface[name='vdsl-1']");

2. While filling in values if I fill in the relevant nodes without namespaces I am getting an error in sysrepod,
[WRN] (rp_data_provide_resp_process:2508) Failed to set operational data for xpath '/ietf-interfaces:interfaces-state/interface[name='vdsl-1']/line/inventory/xtu-c/self-test-result 10'.
[ERR] (dm_ly_log_cb:1326) libyang error: Schema node not found

But, when I do the same with proper namespaces attached it works fine.
sr_val_build_xpath(&v[idx], "/ietf-interfaces:interfaces-state/interface[name='vdsl-1']/bbf-fastdsl:line/bbf-vdsl:line/bbf-vdsl:inventory/bbf-vdsl:xtu-c/bbf-vdsl:self-test-result");

**Expected behavior:**
Either it should get callback with the proper namespaces as part of xpath or shouldn't expect namespaces for setting the values.

**Actual behavior:**
When getting callback in the data provider for this module "ietf-interfaces/interfaces" the xpath does not have name spaces attached, but for setting values xpath expects the nodes with proper namespaces to be present.

### Versions
Please provide versions for software needed to reproduce the bug:
Sysrepo version: `sysrepod -v`.
libyang version: `yanglint -v`
netopeer2-server: `netopeer2-server -V` (optional)

### Attachments
sivak$ sysrepod -v
sysrepod - sysrepo daemon, version 0.6.0

sivak$ yanglint -v
yanglint 0.12.170

sivak$ netopeer2-server -V
netopeer2-server 0.3.64
compile time: May 15 2017, 10:52:37

sivak$ sysrepoctl -l
Sysrepo schema directory: /usr/local/etc/sysrepo/yang/
Sysrepo data directory:   /usr/local/etc/sysrepo/data/
(Do not alter contents of these directories manually)

Module Name                   | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
ietf-netconf-acm              | 2012-02-22 | Installed   | root:root           | 777         |                               |
ietf-netconf-notifications    | 2012-02-06 | Installed   | root:root           | 777         |                               |
ietf-netconf                  | 2011-06-01 | Imported    | root:root           | 777         |                               |
nc-notifications              | 2008-07-14 | Installed   | root:root           | 777         |                               |
notifications                 | 2008-07-14 | Installed   | root:root           | 777         |                               |
iana-if-type                  | 2017-03-30 | Installed   |                     |             |                               |
ietf-interfaces               | 2014-05-08 | Installed   | root:root           | 777         |                               |
ietf-yang-types               | 2013-07-15 | Installed   |                     |             |                               |
bbf-yang-types                | 2016-07-18 | Installed   |                     |             |                               |
bbf-fastdsl                   | 2017-03-13 | Installed   |                     |             |                               |
bbf-vdsl                      | 2017-03-13 | Installed   | root:root           | 777         |  bbf-vdsl-base-body bbf-vdsl-test-mode-body bbf-vdsl-channel-body bbf-vdsl-base bbf-vdsl-line bbf-vdsl-inventory-body bbf-vdsl-xtu bbf-vdsl-data-rate-profile-body bbf-vdsl-service-profiles bbf-vdsl-mode-specific-psd-profile-body bbf-vdsl-line-spectrum-profile-body bbf-vdsl-upstream-power-back-off-profile-body bbf-vdsl-downstream-power-back-off-profile-body bbf-vdsl-radio-frequency-interference-profile-body bbf-vdsl-spectrum-profiles bbf-vdsl-noise-margin-profile-body bbf-vdsl-impulse-noise-protection-delay-profile-body bbf-vdsl-virtual-noise-profile-body bbf-vdsl-sos-profile-body bbf-vdsl-impulse-noise-monitoring-profile-body bbf-vdsl-re-initialization-policy-profile-body bbf-vdsl-vectoring-profile-body bbf-vdsl-data-gathering-profile-body bbf-vdsl-quality-profiles bbf-vdsl-line-status-body bbf-vdsl-xtu-line-status-body bbf-vdsl-xtu-band-status-body bbf-vdsl-xtu-annex-c-status-body bbf-vdsl-xtu-channel-status-body bbf-vdsl-status-monitoring bbf-vdsl-xtu-line-performance-body bbf-vdsl-xtu-channel-performance-body bbf-vdsl-performance-management bbf-vdsl-xtu-line-threshold-profile-body bbf-vdsl-xtu-channel-threshold-profile-body bbf-vdsl-threshold-management bbf-vdsl-xtu-sub-carrier-status-body bbf-vdsl-xtu-data-gathering-report-body bbf-vdsl-test-diagnostics bbf-vdsl-pointers|

Thanks!

**Comment by michalvasko** [comment]
Hi,
please update *libyang* and try again, I think it may have already been fixed.

Regards,
Michal

**Comment by bharath154** [comment]
Hi Michal,

Thanks for the response. I have updated to the latest libyang i.e., libyang.so.0.12.180. But still I am facing the same problem.

Can you please let me know if this problem is fixed either by
1. Passing the namespaces as part of the xpath during callbacks or
2. Not expecting namespaces while filling in values.

Thanks for your help,
Siva

**Comment by michalvasko** [comment]
Hi Siva,
the pull request should help, but I also want to clarify what the correct XPath should be. This example:
```
/ietf-interfaces:interfaces-state/ietf-interfaces:interface[name='vdsl-1']/bbf-fastdsl:line/bbf-vdsl:line/bbf-vdsl:inventory/bbf-vdsl:xtu-c/bbf-vdsl:self-test-result
```
is fine, but *sysrepo* uses a shortened version when you omit the prefix in case it matches that of the parent:
```
/ietf-interfaces:interfaces-state/interface[name='vdsl-1']/bbf-fastdsl:line/bbf-vdsl:line/inventory/xtu-c/self-test-result
```
so you can use this, too.

Regards,
Michal

**Comment by bharath154** [comment]
Thanks Michal for the quick turn around. 
Issue is fixed now.

Regards
Siva
