### ISSUE TITLE
delete operation attribute deletes the complete leaf from datastore

### ISSUE THREAD

**Issue by anjansat** [sysrepo/sysrepo#862]
### Description

When the "operation" attribute is 'delete', the complete leaf is removed from data store. Instead it should have retained the leaf with 'no value'.

Example given below:

The following is the leaf  defined in yang.

    leaf object {
      type string;
	  default "";
      description
        "A sample object";
    }

	
After applying the 'delete' operation attribute	as below, the complete <object> leaf is removed from data store

\<object nc:operation="delete" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">DeleteMe\</object>

Instead it should have retained the leaf as  <\object>

The following is the sysrepo log during 'delete' operation.

May 23 00:55:30  sysrepod[3087]: [INF] Delete item request candidate datastore, xpath: /ietf-interfaces:interfaces/interface[name='0.4']/abcd:interface-config/object

### Steps to Reproduce
1. send rpc as below
\<object nc:operation="delete" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">DeleteMe\</object>

2. send commit

**Expected behavior:**
 The datastore should have retained the leaf as  <\object>

**Actual behavior:**
After applying the 'delete' operation attribute	as below, the complete \<object> leaf is removed from datastore
\<object nc:operation="delete" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">DeleteMe\</object>

### Versions

Sysrepo version:  0.5.11
libyang version: 0.12.119

note: Even the same behaviour is observed, in latest sysrepod, libyang versions.

### Logs
May 23 00:55:30  sysrepod[3087]: [INF] Delete item request candidate datastore, xpath: /ietf-interfaces:interfaces/interface[name='0.4']/abcd:interface-config/object

Thanks
Anjan

**Comment by michalvasko** [comment]
Hi Anjan,
how did you check the result? If by `get-config`/`get`, did you properly specify the option for displaying default values? By default they are not visible.

Regards,
Michal

**Comment by anjansat** [comment]
I have checked by both get and get-config. After delete operation, the datastore @ /etc/sysrepo/data/ietf-interfaces.running removes the \<object> tag from file

\<get>
  \<filter type="subtree">
    \<if:interfaces xmlns:if="urn:ietf:params:xml:ns:yang:ietf-interfaces">
      \<if:interface/>
    \</if:interfaces>
  \</filter>
\</get>


\<get-config>
  \<source>
    \<running/>
  \</source>
  \<filter type="subtree">
    \<if:interfaces xmlns:if="urn:ietf:params:xml:ns:yang:ietf-interfaces">
      \<if:interface/>
    \</if:interfaces>
  \</filter>
\</get-config>

**Comment by michalvasko** [comment]
Hi,
you want your `get-config` (for example) look like this:
```xml
<get-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <source>
    <running/>
  </source>
  <filter type="subtree">
    <if:interfaces xmlns:if="urn:ietf:params:xml:ns:yang:ietf-interfaces">
      <if:interface/>
    </if:interfaces>
  </filter>
  <with-defaults xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults">report-all</with-defaults>
</get-config>
```

You can easily use *netopeer2-cli* which has a simple argument for setting `with-defaults` value.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

Both nodes (max-wait and max-attempts have been set with default values) and I was trying to fetch both the nodes with default values as shown below.

<?xml version="1.0" encoding="utf-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="">
  <get-config>
    <source>
      <running/>
    </source>
    <filter type="subtree">
      <ncs:netconf-server xmlns:ncs="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
        <ncs:call-home>
          <ncs:netconf-client>
            <ncs:connection-type>
              <ncs:persistent>
                <ncs:keep-alives>
                  <ncs:max-wait></ncs:max-wait>
                  <ncs:max-attempts></ncs:max-attempts>
                </ncs:keep-alives>
              </ncs:persistent>
            </ncs:connection-type>
          </ncs:netconf-client>
        </ncs:call-home>
      </ncs:netconf-server>
    </filter>
  </get-config>
</rpc>


But It returns with the data of 1st nodes only as shown below..

<?xml version="1.0" encoding="utf-8"?>
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
    <call-home>
      <netconf-client>
        <connection-type>
          <persistent>
            <keep-alives>
              <max-wait>30</max-wait>
            </keep-alives>
          </persistent>
        </connection-type>
      </netconf-client>
    </call-home>
  </netconf-server>
</data>

As per my understanding, it shold return the values of both the nodes.

Please let me know if I am missing something here.
Thanks in advance.
Regards,
Rosy

**Comment by rosy8** [comment]
Hi Michal,

with-defaults,  is working when we the leaf node has a default value.
But for leaf-node with default value "", its not working.

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
you are right, the default flag was not properly set to `max-wait`, should work now.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

Thanks for the fix.

<with-defaults xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults">report-all</with-defaults>
was not working in case of default with below case..
leaf object {
  type string;
 <b>default ""; </b>
  description
    "A sample object";
}
Is this issue is also taken care of ?

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
I have just tried and it worked fine for me.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

Ok.
Thank you very much Michal.

Regards,
Rosy

**Comment by sksd509** [comment]
HI folks,

does this issue conclude as follows :

> Deleting the Boolean node will bring to the default value. Please set to False if you think the default is False, otherwise set to True.

?

**Comment by michalvasko** [comment]
Hi,
I am not sure I understand what you are asking and also why you have written into a 3 year old issue that was connected to some historic *sysrepo* version and is not relevant anymore.

Regards,
Michal

**Comment by sksd509** [comment]
I guessed this is talking about the behaviour of yang models when a leaf without a default value is getting deleted. hence, I popped in :)

**Comment by michalvasko** [comment]
Hi,
in that case I can summarize it as following. You can never delete a `leaf` with a default value directly, only by deleting its parent. Otherwise, instead of a delete, you will simply see a change to the default value (when deleting the leaf when it had an explicit value set).

Regards,
Michal
