### ISSUE TITLE
Repeated typedef in inc/sysrepo.h

### ISSUE THREAD

**Issue by tmarsh-rvbd** [sysrepo/sysrepo#866]
Hi,
I noticed that inc/sysrepo.h repeatedly typedefs sr_subscr_options_t, at lines 1188 and 1692.
This is causing me trouble with cgo calls, and the latter definition can safely be removed without side effects, so I think it should be.
Tom

**Comment by michalvasko** [comment]
Hi Tom,
you are right, will be fixed by the pull request.

Regards,
Michal
