### ISSUE TITLE
Leaf-list's default value handling

### ISSUE THREAD

**Issue by fabioantonini** [sysrepo/sysrepo#873]
### Things you may try first
(put "x" in "[]" if you already tried following)
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description
The leaf-list default values shouldn't be displayed by sysrepocfg and by NETCONF get-config transaction.

### Steps to Reproduce
1. [Add a leaf-list to yang module]
2. [Add a couple of default values to the leaf-list]
3. [Export the datastore by sysrepocfg]

**Expected behavior:**
sysrepocfg usually doesn't display the default values cause they are filtered by 
the following section of code
```
(        /* skip default values */
         if (schema->nodetype == LYS_LEAF && value->dflt) {
             goto next;
         }

....
```
The default values shouldn't be show by get-config transaction by NETCONF

**Actual behavior:**
I have defined a leaf-list
 ```
            leaf-list events {
                 type notifs:if-state-enum;
                 default up;
                 default down;
                 cli-types:group "1";
             }
```
I have installed the yang module of course.
When I try to  export the content of my datastore by sysrepocfg I read 
the default values for the 'events' leaf-list , but I don't read the 
default values of other leaves (as expected).

```
  <interface>
      <name>eth4</name>
      <type>ethernet</type>
     <events>up</events>
     <events>down</events>
      <mtu>1200</mtu>
    </interface>
```

I have tried to modify the condifion in order to include also leaf-lists
```
if (((schema->nodetype == LYS_LEAF) || (schema->nodetype == 
LYS_LEAFLIST)) && value->dflt) {
```
but anyway I continue to read the default values, so I can guess that 
value->dflt has not been set for the leaf-list.

This is confirmed by the NETCONF get-config reading that displays the default 
values for the 'events' leaf-list.
```
### Versions
Sysrepo version: sysrepod - sysrepo daemon, version 0.6.1.
libyang version: yanglint 0.13.4
netopeer2-server: # netopeer2-server 0.3.72
```
Thanks for your attention
fabio

**Comment by rkrejci** [comment]
Hi Fabio, please verify pull request #874 that it works fine for you.

**Comment by fabioantonini** [comment]
Hi Radek

sorry for the delayed reply but I was verifying more in depth.

The problem has been fixed from sysrepocfg. I cannot see any default 
values for leaf-list. Anyway a new (minor) problem occurs in the 
netopeer2-server in the file operations.c (line 823)

         /* propagate default flag */
         if (sr_val->dflt) {
             /* find the actual node supposed to be created */
             set = lyd_find_xpath(root, sr_val->xpath);
             if (!set || (*set->number != 1*)) {
                 EINT;
                 return -1;
             }

It fails now because of the bolded condition. I have set a couple of 
defaults for the leaf-list and it complains about that.

If I remove one default values from my yang it works fine. But I guess 
that for leaf-lists we can have more than just one default value. Do you 
agree?

regards

fabio


Il 30/05/2017 13:04, Radek Krejci ha scritto:

**Comment by rkrejci** [comment]
yes, good point, I'm going to fix the netopeer2-server

**Comment by rkrejci** [comment]
ok, please try the latest (0.3.73 in devel branch) netopeer2-server

**Comment by fabioantonini** [comment]
Hi Radek

It works fine now.

Thanks a lot

fabio


Il 30/05/2017 15:27, Radek Krejci ha scritto:
