### ISSUE TITLE
How to get the user who did change to data tree.

### ISSUE THREAD

**Issue by fanchanghu** [sysrepo/sysrepo#876]
Hi,
I want to log change records of the data tree in sysrepo data change callback, so I want to get  the user who did the change, but there are no such interface now, can sysrepo provide it, or do you have any other suggestion about such logs?

**Comment by rkrejci** [comment]
This information is part of the `/ietf-netconf-notifications:netconf-config-change` event notification, so it is logged by sysrepo and available via the event notifications (when using client library, you will get the username as part of the data in your `sr_event_notif_cb` callback set via `sr_event_notif_subscribe()`)
