### ISSUE TITLE
Request for adding timestamp to sysrepo log

### ISSUE THREAD

**Issue by fanchanghu** [sysrepo/sysrepo#877]
Hi,
When there are many logs, it is very helpful to have a timestamp for debug. The log after adding timestamp could be like this:
```
2017-06-14 13:06:19 [DBG] [140138223290112] (rp_dt_commit:813) Commit (1/10): process started
```

**Comment by rkrejci** [comment]
timestamps are part of the syslog messages, just do not run `sysrepod` with the debug option (-d) and get the messages from your syslog application.
