### ISSUE TITLE
How to query the type of a node in a YANG model? 

### ISSUE THREAD

**Issue by darren-west** [sysrepo/sysrepo#878]
### Description
Is there a way that I can get the type of a node in a YANG model.
What would be useful is if I could query with xpath to target a node and be returned its data type.

```C
int sr_get_node_type(sr_session_ctx_t *session, const char *xpath, sr_type_t *type);
```

For example if i called it like so 

```C
sr_conn_ctx_t *conn = NULL;
sr_session_ctx_t *sess = NULL;
sr_type_t type = 0;
int rc = SR_ERR_OK;

rc = sr_connect("example", SR_CONN_DEFAULT, &conn);
if (SR_ERR_OK != rc) {
  goto cleanup;
}

/* start session */
rc = sr_session_start(conn, SR_DS_STARTUP, SR_SESS_DEFAULT, &sess);
if (SR_ERR_OK != rc) {
  goto cleanup;
}

rc = sr_get_node_type(session, "/ietf-interfaces:interfaces/interface",&type);
// maybe it doesnt use a session because it isnt tied to a datastore but instead a connection?

if (SR_ERR_OK != rc) {
     goto cleanup;
}

if type != SR_LIST_T{ //Interfaces should be a type of list
   printf("Error expected the type to be SR_LIST_T \n");
}


cleanup:
    if (NULL != sess) {
        sr_session_stop(sess);
    }
    if (NULL != conn) {
        sr_disconnect(conn);
    }
    return rc;

```

I need this functionality, is there a way you can already do this?
Otherwise would it be hard to implement and could you give me some indication of where to look (im guessing I would need to use libyang)? 

Many thanks in advance,
Darren

**Comment by michalvasko** [comment]
Hi Darren,
this is quite a specific functionality you require, so I don't think such a function will be added to API. What you can do is to download the schema using `sr_get_schema()`, then parse it with `lys_parse_mem()`, get the node you want with `lys_find_xpath()`, and finally read the node type from the resulting set.

It is not exactly elegant or efficient, but *sysrepo* is not meant to provide any information about specific schemas it has, it only provides the schema itself on request. Once parsed using *libyang*, you know everything about it. Also, this is likely not the only information you will need, so it becomes efficient after having parsed the schema yourself and working with it without communication with *sysrepo*.

Regards,
Michal

**Comment by darren-west** [comment]
Hi Michal,

Thanks for getting back to me. Yes i thought something like that might be the case. 

One of the main drivers behind something like what I suggested was that I could potentially build some sort of REST interface for interacting the with the configuration data stored in sysrepo. 

* For example I post a JSON payload that contains a leaf node that has a data type of int8, this information is lost in JSON and is just a type of number. 
* Without being able to get the type ill be unable to know what type to set the value too.

The example is below:

```yang
module example-module {
  namespace "http://example.com/example-module";
  prefix module;

  description  "example yang module";

  revision "2016-11-24" {
    description "Initial revision.";
  }
  container example{
    leaf number{
      type uint8;
    }
  }
}

```

```json
{
  "example":{
    "number":10
  }
}

```

I guess you would suggest parsing the entire module in libyang as you have suggested? 

Regards,
Darren

**Comment by michalvasko** [comment]
Hi Darren,
the preferred way of implementing this would be to first parse the JSON into *libyang* data tree. However, if you really want to avoid this, there could be a new function added that will duplicate `sr_set_item()` except it will not read the value from a `sr_val_t`, but get `xpath` and `string value`. Then, the correct type will be learned in *sysrepo* based on the `xpath` so you (the application) does not have to.

Feel free to provide a patch adding this function, but it will not be trivial. You would have to add a new Google Buffers message (or incorporate this into the existing `set_item` message) and then implement proper type checking and conversion (it may be already somewhere in *sysrepo*, it definitely is in *libyang*, but not public). Otherwise we will likely add such a function as your use-case seems reasonable, but not anytime soon.

Regards,
Michal

**Comment by jktjkt** [comment]
Isn't that exactly what the ``sr_set_item_str`` is already doing?

**Comment by michalvasko** [comment]
Yes, it seems it is exactly what that function is doing. You learn something everyday...
