### ISSUE TITLE
Return Single list entry in data provider

### ISSUE THREAD

**Issue by jjin62** [sysrepo/sysrepo#887]
Hi
This may be related to #885 and #851 but slightly different, so I open a separate issue.

It seems that regardless what the xpath specified in the data_requester(), sysrepo always call the data_provider() multiple times with the same set of xpaths.

For example, in oper_data_example.c, data_request():
1)    rc = sr_get_items_iter(session, "/ietf-interfaces:interfaces-state/interface//*", &iter);
2)    rc = sr_get_items_iter(session, "/ietf-interfaces:interfaces-state/interface[name='eth0']", &iter);
3)    rc = sr_get_items_iter(session, "/ietf-interfaces:interfaces-state/interface[name='eth0']/oper-status", &iter);

The client results for above cases are correct:

1)    $ ./oper_data_example 1
    Requesting state data of ietf-inetrfaces:
    /ietf-interfaces:interfaces-state/interface[name='eth0']/name = eth0
    /ietf-interfaces:interfaces-state/interface[name='eth0']/oper-status = down
    /ietf-interfaces:interfaces-state/interface[name='eth0']/statistics (container)
    /ietf-interfaces:interfaces-state/interface[name='eth0']/statistics/discontinuity-time = 1987-08-31T17:00:30.44Z
    /ietf-interfaces:interfaces-state/interface[name='eth1']/name = eth1
    /ietf-interfaces:interfaces-state/interface[name='eth1']/type = iana-if-type:ethernetCsmacd
    /ietf-interfaces:interfaces-state/interface[name='eth1']/oper-status = up
    /ietf-interfaces:interfaces-state/interface[name='eth1']/statistics (container)
    /ietf-interfaces:interfaces-state/interface[name='eth1']/statistics/discontinuity-time = 2016-10-06T15:12:50.52Z

2)    $ ./oper_data_example 1
    Requesting state data of ietf-inetrfaces:
    /ietf-interfaces:interfaces-state/interface[name='eth0']/name = eth0
    /ietf-interfaces:interfaces-state/interface[name='eth0']/oper-status = down
    /ietf-interfaces:interfaces-state/interface[name='eth0']/statistics (container)
    /ietf-interfaces:interfaces-state/interface[name='eth0']/statistics/discontinuity-time = 1987-08-31T17:00:30.44Z

3)    $ ./oper_data_example 1
    Requesting state data of ietf-inetrfaces:
    /ietf-interfaces:interfaces-state/interface[name='eth0']/oper-status = down

**But data_provider() are called in the same way for above 3 cases:**
$ ./oper_data_example
This application will be a data provider for state data of ietf-interfaces.
Run the same executable with one (any) argument to request some data.

========== SUBSCRIBED FOR PROVIDING OPER DATA ==========

Data for '/ietf-interfaces:interfaces-state' requested.
Data for '/ietf-interfaces:interfaces-state/interface' requested.
Data for '/ietf-interfaces:interfaces-state/interface[name='eth0']/statistics' requested.
Data for '/ietf-interfaces:interfaces-state/interface[name='eth1']/statistics' requested.
Data for '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv4' requested.
Data for '/ietf-interfaces:interfaces-state/interface[name='eth1']/ietf-ip:ipv4' requested.
Data for '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6' requested.
Data for '/ietf-interfaces:interfaces-state/interface[name='eth1']/ietf-ip:ipv6' requested.
Data for '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv4/address' requested.
Data for '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv4/neighbor' requested.
Data for '/ietf-interfaces:interfaces-state/interface[name='eth1']/ietf-ip:ipv4/address' requested.
Data for '/ietf-interfaces:interfaces-state/interface[name='eth1']/ietf-ip:ipv4/neighbor' requested.
Data for '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6/address' requested.
Data for '/ietf-interfaces:interfaces-state/interface[name='eth0']/ietf-ip:ipv6/neighbor' requested.
Data for '/ietf-interfaces:interfaces-state/interface[name='eth1']/ietf-ip:ipv6/address' requested.
Data for '/ietf-interfaces:interfaces-state/interface[name='eth1']/ietf-ip:ipv6/neighbor' requested.

Is it possible for sysrepo to invoke callbacks more intelligently based on xpath in data_request? or just pass the exact xpath requested by data_requester() to data_provider()?

In our case, we have a lager list (>100 elements), So every time the data provider has to return the whole list (500k data), **even the client only request one entry.**

thanks,
Jimmy

**Comment by michalvasko** [comment]
Hi Jimmy,
I have nothing else to tell you except what I answered in #885. In short, we will concern ourselves with this, but not just yet.

Regards,
Michal
