### ISSUE TITLE
How to check if a node exists in the data tree

### ISSUE THREAD

**Issue by stefanopet91** [sysrepo/sysrepo#891]
In my application I need to know if a node conditioned by a when statement is writable (i.e., the when condition is satisfied).
Is there a way to ask Sysrepo if an xpath refers to an existing node? The only way I know is to write a value and then use the _sr_validate_ or _sr_commit_ function to trigger the validation. I tried with _sr_get_item_ but it always returns SR_ERR_NOT_FOUND regardless of the when condition.
Thanks for your help

**Comment by michalvasko** [comment]
Hi,
this is the obvious way, which should work fine even though is not efficient. Other ways I can think of would require a lot of additional code you would have to implement and the payoff is too small.

Regards,
Michal
