### ISSUE TITLE
build ERROR

### ISSUE THREAD

**Issue by zhoulinghua** [sysrepo/sysrepo#896]
$ git clone https://github.com/sysrepo/sysrepo.git
$ cd sysrepo
$ mkdir build; cd build
$ cmake ..
$ make

not find makefile

can you help me，thank you

**Comment by michalvasko** [comment]
Can you please provide the output of `cmake ..`?

Michal

**Comment by zhoulinghua** [comment]
yes,I just want it to compile properly.

**Comment by michalvasko** [comment]
Please, what do you see, what is displayed when executing `cmake ..`?

**Comment by zhoulinghua** [comment]
it output any error.
-- Found yang: /usr/local/lib/libyang.so  
-- Could NOT find protobuf-c (missing:  PROTOBUF-C_LIBRARY PROTOBUF-C_INCLUDE_DIR) 
-- Found avl: /usr/lib/libavl.so  
-- Could NOT find redblack (missing:  REDBLACK_LIBRARY REDBLACK_INCLUDE_DIR) 
-- libavl will be used for binary tree manipulations.
-- Looking for pthread_rwlockattr_setkind_np
-- Looking for pthread_rwlockattr_setkind_np - found
-- Looking for getpeereid
-- Looking for getpeereid - not found
-- Looking for getpeerucred
-- Looking for getpeerucred - not found
-- Looking for include file ucred.h
-- Looking for include file ucred.h - not found
-- Looking for pthread_mutex_timedlock
-- Looking for pthread_mutex_timedlock - found
-- Looking for setfsuid
-- Looking for setfsuid - found
-- Looking for fsetxattr
-- Looking for fsetxattr - found
-- Performing Test HAVE_STAT_ST_MTIM
-- Performing Test HAVE_STAT_ST_MTIM - Success
-- Example code and YANG models will be built and installed.
-- CMocka found, tests are enabled.
-- Looking for include file regex.h
-- Looking for include file regex.h - found
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Could NOT find SWIG (missing:  SWIG_EXECUTABLE SWIG_DIR) 
CMake Warning at swig/CMakeLists.txt:11 (message):
  SWIG library not found

**Comment by michalvasko** [comment]
Well, after not finding `protobuf-c` cmake should fail, so I am not sure why it did not. Anyway, you must fix that first before trying to compile it anyway, then try again and I think `Makefile` will be generated.

Regards,
Michal
