### ISSUE TITLE
client can not restore to normal state if one response received after its request timeout

### ISSUE THREAD

**Issue by fanchanghu** [sysrepo/sysrepo#901]
### Things you may try first
(put "x" in "[]" if you already tried following)
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description
Hi,
In my case, after a commit timeout, all the other messages after it will fail due to `Malformed message with response received`. It seems the client API received the previous response for current request.

the timeout message like:
```
netopeer2-server[2477]: [140624765044800] (cl_request_process:515) commit request sent, waiting for response.
netopeer2-server[2477]: [140624765044800] (cl_message_recv:204) While waiting for a response, timeout has expired.
```

the malformed message error like:
```
netopeer2-server[2477]: [140624581834496] (cl_request_process:538) session-refresh response received, processing.
netopeer2-server[2477]: [140624581834496] (cl_request_process:544) Malformed message with response received (session id=1494786715, operation=session-refresh).
netopeer2-server[2477]: [140624581834496] (sr_session_refresh:619) Error by processing of the request.
```

**Comment by michalvasko** [comment]
Hi,
yes, this is the current behavior. Maybe not optimal, but fixing it may require some bigger changes, so we will look at it later.

Regards,
Michal

**Comment by jjin62** [comment]
Will it help, if client stop and start the session after a request is timed out?

**Comment by michalvasko** [comment]
Hi,
that should definitely help.

Regards,
Michal
