### ISSUE TITLE
capabilities not support？

### ISSUE THREAD

**Issue by zhoulinghua** [sysrepo/sysrepo#905]
hi，
     I Installed netopper2 and sysrepo.
 it capabilities not support: ":confirmed-commit:1.1",":url",":partial-lock",":yang-push:1.0".
Can it support these?
I tried using kill-session. But it does not support .

<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="24">
  <rpc-error>
    <error-type>protocol</error-type>
    <error-tag>operation-not-supported</error-tag>
    <error-severity>error</error-severity>
    <error-message xml:lang="en">Request could not be completed because the requested operation is not supported by this implementation.</error-message>
  </rpc-error>
</rpc-reply>

**Comment by michalvasko** [comment]
Hi,
the capabilities you mentioned are really not supported at the moment, but may be supported in future. `kill-session` should be supported soon, but it was redundant without proper NACM support, so it depends on that. NACM will hopefully be implemented and finished in the upcoming weeks.

Regards,
Michal

**Comment by zhoulinghua** [comment]
ok,Thanks!
