### ISSUE TITLE
Does an RPC callback block other registered RPC callbacks until it is complete?

### ISSUE THREAD

**Issue by darren-west** [sysrepo/sysrepo#914]
If you have two separate rpc calls does the second rpc call get blocked waiting for the first to complete? i.e. do the callbacks run in the same thread?

```
     rpc say-hello {
         input {
             leaf name {
                 type string;
             }
         }
         output {
             leaf response {
                 type string;
             }
         }
     }
```
```
     rpc say-bye {
         input {
             leaf name {
                 type string;
             }
         }
         output {
             leaf response {
                 type string;
             }
         }
     }

```
Would the bye callback wait for the hello callback to complete.

Thanks in advance,
Darren West

**Comment by michalvasko** [comment]
Hi Darren,
I am fairly certain they are not executed in the same thread (executions are randomly distributed among several threads, so it can be one under some special circumstances).

Regards,
Michal

**Comment by fanchanghu** [comment]
Hi,
I occurred this problem too, there is no conflict only when the two rpc are subscribed in different sysrepo clients. However, if they are subscribed in one sysrepo client, the second one will be blocked. (it will be blocked in sysrepo client which only has 1 thread now)

**Comment by michalvasko** [comment]
Hi,
yep, as is written in the note [here](http://www.sysrepo.org/static/doc/html/subscribtions.html).

Regards,
Michal

**Comment by darren-west** [comment]
Hi,

If I am correct, if I am running one daemon and connecting using the client lib all subscriptions of all types are handled synchronously. i.e. my rpc callback (if triggered second) wont fire if I am blocking in a module changed callback. Or A second rpc call wont run until the first rpc callback has returned. 

I understand why this is necessary for change callbacks and being able to reject a commit but is it necessary for rpc or even APPLY only change events? 

My main concern is if I have a long running rpc call doing operation x returning some response then I need to block all other potential rpc calls that could be doing something unrelated?

Regards,
Darren

**Comment by michalvasko** [comment]
Hi Darren,
in the link I provided there is also a solution despite not being too elegant, perhaps. We may look into the threading model in future, but currently this is the way to go.

Regards,
Michal

**Comment by darren-west** [comment]
Hi, 
Do you mean that I should run a new daemon when I run `sr_connect("example", SR_CONN_DAEMON_START, &connection);`  for each event that i register?

This will give the same effect as running in a new thread?

Regards,
Darren

**Comment by michalvasko** [comment]
Hi Darren,
I believe it should meaning the callback will not block each other.

Regards,
Michal
