### ISSUE TITLE
segmentation fault on OpenWrt when linked with "-lubox"

### ISSUE THREAD

**Issue by mislavn** [sysrepo/sysrepo#915]
### Description
This is a bit specific bug, so on OpenWrt if a sysrepo application (binary) is linked with [libubox](https://git.openwrt.org/project/libubox.git) the application will get a segmentation fault when the application tries to execute any sysrepo subscribe API function (sr_module_change_subscribe()). But the same code modified to run as a plugin will behave as expected.

The sysrepo log generated when the binary is run:
```
[INF] (main:208) Plugin application mode initialized
[DBG] New client connection on fd 6
[DBG] New connection started successfully, fd=6, conn ctx=0x675a70.
[DBG] fd 6 readable
[DBG] Input buffer for fd=6 expanded to 1024 bytes.
[DBG] 25 bytes of data received on fd 6
[DBG] fd 6 would block
[DBG] New message of size 21 bytes received.
[DBG] Output buffer for fd=6 expanded to 1024 bytes.
[DBG] Sending 20 bytes of data.
[DBG] 20 bytes of data sent.
[DBG] fd 6 readable
[DBG] 23 bytes of data received on fd 6
[DBG] fd 6 would block
[DBG] New message of size 19 bytes received.
[DBG] Processing session_start request (conn=0x675a70).
[DBG] Starting a new session, options=0.
[INF] New session created successfully, real user=root, effective user=(null), session id=1452520020.
[DBG] Initiating circular buffer for 2 elements.
[DBG] RP session start, session id=1452520020.
[DBG] Sending 29 bytes of data.
[DBG] 29 bytes of data sent.
[DBG] fd 6 readable
[DBG] Peer on fd 6 disconnected.
[INF] Closing the connection 0x675a70.
[DBG] RP session stop, session id=1452520020.
[DBG] RP session cleanup, session id=1452520020.
[INF] Unlock datastore request
[INF] Dropping session id=1452520020.
[DBG] Connection stop requested, fd=6.
```

The sysrepo-plugin log generated when the plugin is loaded:
```
[DBG] Loading plugin from file 'sysrepo-plugin-dt-sip.so'.
[DBG] 113 bytes of data received on fd 10
[DBG] fd 10 would block
[DBG] New message of size 109 bytes received.
[DBG] Received a notification for subscription id=863391920 (source address='/var/run/sysrepod.sock').
[DBG] HELLO notification received on subscription id=863391920.
[DBG] Initializing sysrepo subscription server at socket=/var/run/sysrepo-subscriptions/sip/30525.AaFo6H.sock
[DBG] Sending subscribe request.
[DBG] Server context changed.
[DBG] subscribe request sent, waiting for response.
[DBG] subscribe response received, processing.
[DBG] Sending subscribe request.
[DBG] subscribe request sent, waiting for response.
[DBG] New connection on fd 12
[DBG] fd 12 readable
[DBG] Input buffer for fd=12 expanded to 1024 bytes.
[DBG] 102 bytes of data received on fd 12
[DBG] fd 12 would block
[DBG] New message of size 98 bytes received.
```

So the bug occurs without any header included, so linking the binary with "-lubox" is enough to trigger the bug without any libubox API used.

**Comment by mislavn** [comment]
@rkrejci, @michalvasko  do you have any ideas where the problem could be?

I must admit I am perplexed by this bug and out of ideas.

**Comment by darshana-jk** [comment]
Hi,
This is something I previously encountered in openwrt 14. Assuming you have built Sysrepo with  libavl.
ubox uses its own small avl tree implementation, which has the same function names as the libavl (avl_insert(), avl_delete etc). So when you link both of them together - there are two libraries with the same function names, this leads to crashes. I'm not 100% sure this is your cause but it will be worth a check.

**Comment by mislavn** [comment]
Hi,

thank you @darshana-jk for the hint, I will investigate it.

Regards,
Mislav

**Comment by mislavn** [comment]
Hi,

@darshana-jk you where right, I replaced the avl library with [libredblack](https://github.com/sysrepo/libredblack) and it worked.

I will add the libredblack package to OpenWrt/Lede and change the sysrepo package dependency.

Regards,
Mislav
