### ISSUE TITLE
Require concurrence support for multi clients (from netopeer2)

### ISSUE THREAD

**Issue by fanchanghu** [sysrepo/sysrepo#916]
Hi,
This issue is from CESNET/Netopeer2#167, it is suggested to be moved here.

This is a requirement about concurrence, this requirement may not be implemented in netopeer2, but the feature seems being provided by netopeer2, so I want to discuss it here.

This requirement is for avoiding the clients of netopeer2-server be blocked by each other, however, it is blocked in sysrepo client API such as sr_rpc_send now, because it gets a lock in sr_conn_ctx_t and unlocks it after the rpc response is received. If the rpc needs a long time to finish or timeout, all the other clients will be blocked.

**Comment by michalvasko** [comment]
Fixed.
