### ISSUE TITLE
Question - ssysrepoctl (libyang) --serach-dir for imported modules

### ISSUE THREAD

**Issue by jjin62** [sysrepo/sysrepo#919]
(put "x" in "[]" if you already tried following)
* [x] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

### Description
[Description]
I have two identical development linux servers with different behavior:

### Steps to Reproduce
1. [First one works]
~/shasta/yang-model/oplink/L2$ sysrepoctl --install --yang=org-openroadm-rstp.yang --search-dir=../../oplink
....
Notifying sysrepo about the change...
Install operation completed successfully.

2. [Second one is not working]
~/shasta/yang-model/oplink/L2$ sysrepoctl --install --yang=org-openroadm-rstp.yang --search-dir=../../oplink
Installing a new module from file 'org-openroadm-rstp.yang'...
[ERR] (srctl_ly_log_cb:500) libyang: Failed to resolve augment "/org-openroadm-device:open-optical-device/org-openroadm-device:protocols".
[ERR] (srctl_ly_log_cb:500) libyang: Module "org-openroadm-rstp" parsing failed.
Error: Unable to load the module by libyang.
Install operation failed.

3. [Additional info]
org-openroadm-rstp.yang import and augments the org-openroadm-device.yang:

`  augment "/org-openroadm-device:open-optical-device/org-openroadm-device:protocols" {
    uses rstp-container;
  }`

org-openroadm-device.yang is in ~/shasta/yang-model/oplink/device/edfa

**Expected behavior:**
 Why same command works on one server but not on the another? Additional to --serach-dir, Is there other environment variables are used for searching the import yang model?

Some hints would be much appreciated.

### Versions
Using latest libyang master branch and sysrepo devel branch

Thanks!

**Comment by michalvasko** [comment]
Hi,
there will be some difference, obviously. Can you provide the output of `sysrepoctl -l` on both servers before installing `org-openroadm-rstp`?

Regards,
Michal

**Comment by jjin62** [comment]
Hi Michal,
sysrepoctl --list shows that org-openroadm-device is installed on both servers:

jimmy@jimmy-VirtualBox:~$ sysrepoctl -l | grep org-openroadm-device
org-openroadm-device          | 2016-06-10 | Installed   | jimmy:jimmy         | 666         |                               | pam4

wei@jimmy-Vostro-230:~$ sysrepoctl -l  | grep org-openroadm-device
org-openroadm-device          | 2016-06-10 | Installed   | wei:wei             | 666         |                               | pam4

Is there a way of have multiple paths in --search-dir=?

**Comment by michalvasko** [comment]
Hi,
even though *libyang* supports it, *sysrepoctl* does not for now, do you think that would help you? It is difficult to guess what the problem may be but you can try uninstalling `org-openroadm-device` first and then install `org-openroadm-rstp`, for instance.

Regards,
Michal

**Comment by jjin62** [comment]
Hi Michal,
If libyang supports multiple search directories, can sysrepoctl support it as well? We put common yang modules in several directories. 
thanks,
Jimmy
