### ISSUE TITLE
netopeer2-server in dockerfiles not working by default

### ISSUE THREAD

**Issue by mislavn** [sysrepo/sysrepo#920]
### Description
The default docker files no longer work because Netopeer2 server settings have changed.
So when the docker container is build and run I get this error with Netopeer2 server:

```
netopeer2-server[21]: Module "ietf-netconf-with-defaults" successfully parsed.
netopeer2-server[21]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_ssh_listen_endpt']/name" created.
netopeer2-server[21]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_ssh_listen_endpt']/ssh" created.
netopeer2-server[21]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_ssh_listen_endpt']/ssh/address" created.
netopeer2-server[21]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_ssh_listen_endpt']/ssh/port" created.
netopeer2-server[21]: Listening on 0.0.0.0:830 for SSH connections.
netopeer2-server[21]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_ssh_listen_endpt']/ssh/host-keys" created.
netopeer2-server[21]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_ssh_listen_endpt']/ssh/host-keys/host-key[name='test_ssh_listen_key']/name" created.
netopeer2-server[21]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_ssh_listen_endpt']/ssh/host-keys/host-key[name='test_ssh_listen_key']/public-key" created.
sysrepod[16]: [ERR] Validation of xpath /ietf-netconf-server:netconf-server/listen/endpoint[ssh]//* failed.
sysrepod[16]: [ERR] Get items failed for '/ietf-netconf-server:netconf-server/listen/endpoint[ssh]//*', session id=1173292758.
netopeer2-server[21]: Error by processing of the get-items request (session id=1173292758): Invalid expression..
netopeer2-server[21]: Fetching more items failed '/ietf-netconf-server:netconf-server/listen/endpoint[ssh]//*'
netopeer2-server[21]: Failed to get the next value from sysrepo iterator (Request contains unknown element).
netopeer2-server[21]: Server init failed.
netopeer2-server[21]: Client Subscription Manager successfully destroyed.
```

What should be the default [dockerfile](https://github.com/sysrepo/sysrepo/blob/master/deploy/docker/sysrepo-netopeer2/Dockerfile) now, at the moment netopeer2 server is installed with the commands:

```
# keystore
RUN \
      cd /opt/dev && \
      git clone https://github.com/CESNET/Netopeer2.git && \
      cd Netopeer2 && \
      cd keystored && mkdir build && cd build && \
      cmake -DCMAKE_BUILD_TYPE:String="Release" .. && \
      make -j2 && \
      make install && \
      ldconfig

# netopeer2
RUN \
      cd /opt/dev && \
      cd Netopeer2/server && mkdir build && cd build && \
      cmake -DCMAKE_BUILD_TYPE:String="Release" .. && \
      make -j2 && \
      make install && \
      cd ../../cli && mkdir build && cd build && \
      cmake -DCMAKE_BUILD_TYPE:String="Release" .. && \
      make -j2 && \
      make install
```

@rkrejci  should I use -DENABLE_CONFIGURATION=OFF or implement ssh listen?

**Comment by mislavn** [comment]
@michalvasko can you give me an example of a configuration for ssh-listen?

**Comment by michalvasko** [comment]
Hi Mislav,
you can use the `stock_configuration.xml` in `netopeer2/server`, that is the one that fails to be applied in the log you posted. I am sorry, but I did not start with this issue, perhaps tomorrow.

Regards,
Michal

**Comment by mislavn** [comment]
Hi Michal,

it is not a problem and did you mean `stock_config.xml`, it is applied with cmake by default.

Also do you want me to implement ssh/tls listen/callhome functionality via docker, it can serve as an additional documentation.

Regards,
Mislav

**Comment by mislavn** [comment]
Hi Michal,

so the problem is that in netopeer2-server if a fetaure in ietf-netconf-server yang model is enabled than it has to be implemented.

By default the cmake file enables the features: listen ssh-listen tls-listen call-home ssh-call-home tls-call-home and implements the [configuration](https://github.com/CESNET/Netopeer2/blob/master/server/stock_config.xml).

Should we change the logic of the Netopeer2/server cmake file for a fresh install or make the netopeer2-server less strict?

Regards,
Mislav

**Comment by mislavn** [comment]
Hi,

also I need the patch https://github.com/CESNET/Netopeer2/pull/172 in Netopeer2 for this to work.

Regards,
Mislav
