### ISSUE TITLE
Unclear on how to listen for several notifications

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#922]
After the recent change which unified the XPath formats, I no longer know how to subscribe to any notifications from a module. None of the following formats appears to work:

* `/module:*//.` which used to work, but now raises an error message `libyang error: Unexpected character(s) '` at registration time
* `/module:*//` (same error message)
* `/module:*` which succeeds in registering for the notifications, but fails to actually receive them at runtime

This is with latest libyang devel and sysrepo #921. Stuff works with CESNET/libyang@441f134 and sysrepo/sysrepo@d9f6a9d.

**Comment by TrinityCoder** [comment]
I was trying to solve the same problem yesterday, and apart from these formats, I also tried simply using the module's name - `module` - about which I read somwhere in the docs, that it should subscribe to all notifications in the module. However, the result was the same as the last of yours - all seems OK, but at runtime, notification is never received.

**Comment by michalvasko** [comment]
Hi,
it was changed to what @TrinityCoder is saying, simply using the module name. I will test it again, it is possible I left some bug due to which it is not working correctly and I will also restrict all XPath expressions not identifying a specific notification.

Regards,
Michal

**Comment by jktjkt** [comment]
Hi @michalvasko , any news on this one?

**Comment by rkrejci** [comment]
@michalvasko is on vacation till 18th september

**Comment by jktjkt** [comment]
Thanks for a fix.
