### ISSUE TITLE
Memory leak while running example applications

### ISSUE THREAD

**Issue by zidekmat** [sysrepo/sysrepo#924]
### Description
When I build sysrepo and it's dependencies directly from git and run some test applications from examples/ directory through valgrind, it reports memory leaks. This behaviour remains even if I use sysrepo in my own program and seems to be in both sysrepo branches master and devel.

### Steps to Reproduce
Test case and logs i'm providing are only for sr_get_items_example.c though other example application have similar behaviour.
```bash
$ gcc -lsysrepo sr_get_items_example.c && valgrind --leak-check=full  ./a.out
==15653== Memcheck, a memory error detector
==15653== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==15653== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==15653== Command: ./a.out
==15653== 
/ietf-interfaces:interfaces/interface[name='eth0'] (list instance)
/ietf-interfaces:interfaces/interface[name='eth1'] (list instance)
==15653== 
==15653== HEAP SUMMARY:
==15653==     in use at exit: 2,400 bytes in 19 blocks
==15653==   total heap usage: 20,579 allocs, 20,560 frees, 2,126,144 bytes allocated
==15653== 
==15653== LEAK SUMMARY:
==15653==    definitely lost: 0 bytes in 0 blocks
==15653==    indirectly lost: 0 bytes in 0 blocks
==15653==      possibly lost: 0 bytes in 0 blocks
==15653==    still reachable: 2,400 bytes in 19 blocks
==15653==         suppressed: 0 bytes in 0 blocks
==15653== Reachable blocks (those to which a pointer was found) are not shown.
==15653== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==15653== 
==15653== For counts of detected and suppressed errors, rerun with: -v
==15653== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Expected behavior:**
No memory leaks

### Versions
Sysrepo version: sysrepod 0.7.0
libyang version: yanglint 0.13.49

### Attachments
1. Log from sysrepod -d -l 4 while running sr_get_items_example.c [here](https://github.com/sysrepo/sysrepo/files/1277444/daemon.log.txt)
2. Full log from valgrind --leak-check=full --show-leak-kinds=all [here](https://github.com/sysrepo/sysrepo/files/1277427/valgrind.log.txt)
3. Log from sr_get_items_example.c with added sr_log_stderr(SR_LL_DBG); [here](https://github.com/sysrepo/sysrepo/files/1277442/sr_get_items_example.debug.log.txt)

Installed modules: only the ones that come with installation

Thank you

**Comment by michalvasko** [comment]
Hi,
thanks for the report, but for next time report only if there is any `definitely lost` memory, `still reachable` cannot cause any real problems. These leaks should actually be caused by *libssl*, you can verify this by specifying additional *valgrind* arguments (`--show-leak-kinds=all`).

Regards,
Michal
