### ISSUE TITLE
leafref node validation in sr_check_value_conform_to_schema() seems to be incorrect

### ISSUE THREAD

**Issue by igortern** [sysrepo/sysrepo#925]
### Description
sr_check_value_conform_to_schema() function expects leafref value to be of the same type as the leafref target node's, according to the relevant schema.
It seems to be incorrect because leafref value is in fact always a string.
It makes it impossible to pass validation when setting leafref values for non-string target nodes.

### Steps to Reproduce
Example: attempting to generate ietf-hardware:hardware-state-oper-enabled notification.
```
    leaf admin-state {
      type leafref {
        path "/hardware-state/component/state/admin-state";
      }
      description
        "The administrative state for the component.";
    }
```
the target node is enum.
It results in the following errors
```
[ERR] (dm_ly_log_cb:1288) libyang error: Invalid value "/ietf-hardware:hardware-state/component[name='xpon-olt']/state/admin-state" in "admin-state" element.
[ERR] (dm_ly_log_cb:1288) libyang error: Invalid value "/ietf-hardware:hardware-state/component[name='xpon-olt']/state/admin-state" in "admin-state" element.
[ERR] (dm_ly_log_cb:1288) libyang error: Failed to create node "admin-state" as a child of "hardware-state-oper-enabled".
[ERR] (dm_sr_val_node_to_ly_datatree:5806) Unable to add new data tree node '/ietf-hardware:hardware-state-oper-enabled/admin-state': Failed to create node "admin-state" as a child of "hardware-state-oper-enabled"..
[ERR] (dm_validate_procedure:6184) Error by converting sysrepo values/trees to libyang data tree.
[ERR] (rp_event_notif_req_process:3056) Validation of an event notification (/ietf-hardware:hardware-state-oper-enabled) message failed.
```
**Actual behavior:**
 [What actually happened]

### Versions
yanglint 0.13.43
sysrepod - sysrepo daemon, version 0.7.0

### Attachments

[sysrepod.log.zip](https://github.com/sysrepo/sysrepo/files/1273600/sysrepod.log.zip)

**Comment by michalvasko** [comment]
Hi,
I think everything works fine, you have just probably misunderstood how `leafref` YANG type works. The value of a `leafref` is not supposed to be the path to the target node (this information is already included in the schema) but rather the exact same value of the target.

Let's say your `/ietf-hardware:hardware-state/component[name='xpon-olt']/state/admin-state` node has the `unlocked` value. In that case the node `/ietf-hardware:hardware-state-oper-enabled/admin-state` should also simply have the value `unlocked`.

Regards,
Michal
