### ISSUE TITLE
Validation failed while setting IPv6 prefix-length to the running datastore

### ISSUE THREAD

**Issue by swathins079** [sysrepo/sysrepo#929]
### Description
iPv6 related parameters giving a validation error by the sysrepo. I am using sysrepo 0.7 version(master).

One of the xpath which is throwing a validation error is "/ietf-interfaces:interfaces/interface[name='<interface-name>']/ietf-ip:ipv6/address[ip='<ipv6>']/prefix-length"

### Steps to Reproduce
1. Install the yangs ietf-interfaces and ietf-ip
2. start the sysrepod and sysrepo-plugind daemons.
3. Try to set the IPv6 prefix-length or IPv6 address or any other params.

**Expected behavior:**
 Shouldn't throw any error. As a result of this, no data is send in response to a get request.

**Actual behavior:**
 Should set the value without any errors.

### Versions
Please provide versions for software needed to reproduce the bug:
Sysrepo version: 0.7(master)
libyang version: latest(Date: sep13, branch master)
netopeer2-server: latest(branch master)

Thanks!
Swathin

**Comment by michalvasko** [comment]
Hi Swathin,
the problem is likely caused by `:` in the IPv6 address, it should be fixed by #931.

Regards,
Michal

**Comment by swathins079** [comment]
You are right, Michal. Tested with the fixed code and it is working fine now.

Thanks,
Swathin
