### ISSUE TITLE
Wiki: Remove "1) NACM" list item in "TODO List"

### ISSUE THREAD

**Issue by TrinityCoder** [sysrepo/sysrepo#940]
In sysrepo's wiki, specifically on the [TODO List page](https://github.com/sysrepo/sysrepo/wiki/TODO-List), the first TODO item is "_1. NACM (NETCONF Access Control Model)_".
However, the [sysrepo release 0.7.0](https://github.com/sysrepo/sysrepo/releases/tag/v0.7.0) implements, among other things, "_full NACM support_".
Therefore, if I am not mistaken, the entry in the wiki's TODO List should be removed to keep the list up-to-date.

**Comment by michalvasko** [comment]
Hi,
you are correct, I removed this item from the list.

Regards,
Michal
