### ISSUE TITLE
How to use xpath expressions such as starts-with, ends-with or wildcards in sysrepo?

### ISSUE THREAD

**Issue by swathins079** [sysrepo/sysrepo#942]
I want to delete all ip address nodes which starts with fe80. I was able to use contains without any issues but it deletes ip address such as 12:fe80:1 if present.

I tried the following but i am getting validation failed messages.

/ietf:interfaces/interface/inet-ip:ipv6/address[contains(.,'fe80')] ->not the thing i want.
/ietf:interfaces/interface/inet-ip:ipv6/address[starts-with(@ip, 'fe80')] ->not working
/ietf:interfaces/interface/inet-ip:ipv6/address[ip='fe80*']->not working

Regards,
Swathin

**Comment by michalvasko** [comment]
Hi Swathin,
for example, the expression
```
/ietf:interfaces/interface/inet-ip:ipv6/address[starts-with(ip, 'fe80')]
```
should do what you want, simple enough. The `ip` node gets implicitly converted to `string`. As long as it is a leaf/leaf-list, it is performed exactly as you would expect, its value is used. 

Generally, you can use patterns as well, the predicate would then look like this
```
[re-match(ip, 'fe80*')]
```
because this functions performs implicit anchoring of the beginning and also the end ([RFC ref](https://tools.ietf.org/html/rfc7950#section-10.2.1)).

Regards,
Michal

**Comment by swathins079** [comment]
Thanks Michal for the quick response. This is exactly what i want.

Regards,
Swathin

**Comment by michalvasko** [comment]
Also, `@ip` works with attributes, under normal circumstances you will never need to use this in YANG.

**Comment by swathins079** [comment]
Is there any way to supress the callback functions for an internal datastore operation? I tried usinh the session in the init callback function but it is making the changes in the startup datastore.

Regards,
Swathin

**Comment by swathins079** [comment]
I tried with @ as in normal xpath, but it was throwing validation failed error.

Regards,
Swathin

**Comment by michalvasko** [comment]
Hi Swathin,
firstly, you are not talking about the original issue anymore, please do not mix issues next time.

Secondly, normal XPath and YANG XPath differ minimally and `@` refers to attributes in both.

Finally, regarding your issue, I do not know what you mean by internal datastore or what callback you want to suppress. Please say what exactly you are doing, what behavior you see, and what would you like to happen instead (preferably in a new issue).

Regards,
Michal

**Comment by swathins079** [comment]
Hi Michal,

I will start a new issue/thread for the new issue that I am facing. Thanks for the quick response.

Regards,
Swathin
