### ISSUE TITLE
Query on the callback implementation of the sysrepo

### ISSUE THREAD

**Issue by swathins079** [sysrepo/sysrepo#943]
I am trying to disable/enable create-global-address ([ietf-address.yang module](https://github.com/CESNET/netopeer/blob/master/transAPI/cfginterfaces/model/ietf-interfaces%402014-05-08.yang)) attribute of an interface. Disabling of it results in the deletion of all the link-local addresses present in an interface[(iface_ipv6_creat_glob_addr)](https://github.com/CESNET/netopeer/blob/master/transAPI/cfginterfaces/iface_if.c#L2563). For making the running datastore in sync with the device configurations, I am deleting the IP addresses that start with fe80. As the deletion is performed on the running datastore, it results in the invoking of the callback registered. In the callback, I have written the following.

/* get the iface name*/
switch(op){
....
    case OP_DELETED:
        iface_ipv6_ip(iface_name, ip, prefix, op, &msg); // [link](https://github.com/CESNET/netopeer/blob/master/transAPI/cfginterfaces/iface_if.c#L2529)
         break;
....
}

So the deletion command is called twice. I want only one deletion call and suppress the other one. Is there any way to supress the second call for deletion as there is no link-local ip address to delete. Or is there any method other than mentioned above to do this?

Regards,
Swathin

PS: Is there any forum for discussing all the questions regarding sysrepo and how to implement plugins using client libraries?

**Comment by michalvasko** [comment]
Hi Swathin,
how did you register the callback exactly? Doesn't the callback have a parameter `sr_notif_event_t event`? It is possible it is called with one value the first time, another the second (`SR_EV_VERIFY` and `SR_EV_APPLY`, respectively). If so, you can change this behavior in the subscription call (flag `SR_SUBSCR_APPLY_ONLY`). I cannot really help you without knowing more. Also, all of this information is in the documentation of the functions and most of it in the [general documentation](http://www.sysrepo.org/static/doc/html/dev_guidelines.html). 

Regards,
Michal

**Comment by swathins079** [comment]
Hi Michal,

I am using sr_subtree_change_subscribe  with sr_subscr_flag_e flags SR_SUBSCR_DEFAULT or SR_SUBSCR_CTX_REUSE. In the callback function, I am looking for events other than SR_EV_APPLY.
(i am following this [implementation](https://github.com/sysrepo/vpp-sysrepo/blob/master/plugins/vpp-interfaces.c#L151)).

The main reason why I am deleting the data from the running datastore is to sync the running datastore with the device configurations. Is there any client API which does this purposes?

Regards,
Swathin

**Comment by michalvasko** [comment]
Hi,
I am still not sure I understand what is happening in your case. Do you disable `create-global-address` on the device itself and are then trying to make *sysrepo* datastore in sync? Please specify what exactly are you doing and what is happening, also include what performs each action, you have **the device**, **the daemon/plugin** (I don't know where your callback are, it does not really matter), and **sysrepo**. You have not mentioned **netopeer2-server** so I assume you did not use it.

Regards,
Michal

**Comment by swathins079** [comment]
Hi Michal,

I am disabling the create-global-address in the ietf-interfaces and in the callback function i am calling a [function](https://github.com/CESNET/netopeer/blob/master/transAPI/cfginterfaces/iface_if.c#L2563) which will do two things:
1. disable the autoconf
2. flushes all the link-local address present.

As a result of the above two operations, running datastore becomes out-of-sync with actual device configurations. So to make it in sync, I am calling the sr_delete_item on the running datastore with xpath "/ietf:interfaces/interface[name='<iface-name>']/inet-ip:ipv6/address[starts-with(ip, 'fe80')]", which does the following:

1. Deletes all the link-local addresses which start with fe80 from the running datastore for that interface.
2. Also invokes the callback function(which I have written for deleting ip addresses)registered, which will again try to delete the link-local address from the interface.(I want to avoid this.)

Could you please suggest a better method to sync the device configs with running datastore.

I am using sysrepo-plugind to load the plugin and netopeer2-server. The plugin is responsible for fetching the device data and store it in the sysrepo at plugin startup process(init_cb) and also responsible for configuring the device through callback functions.

Regards,
Swathin

**Comment by michalvasko** [comment]
Hi Swathin,
I hope I understand it now and it seems to me all you have to do as a reaction to disabling `create-global-address` is:

 - disable autoconf
 - call `sr_delete_item` with the xpath you mentioned

This way your callback will delete all link-local addresses from the interface based on them being removed from the configuration, it will remain synchronized. But be careful, you cannot directly call another `sr_*` function from *sysrepo* callback, it would create a deadlock. You must create a separate thread for `sr_delete_item` call.

Regards,
Michal

**Comment by swathins079** [comment]
Hi Michal,

I am calling `sr_delete_item` in a separate thread.  Currently, the thread does the following:
1. Creates a new connection.
2. Creates a new session with running datastore.
3. Deletes the link-local address nodes for that interface from the running datastore.
4. Commit the changes.

After the commit operation, the delete operation made in the running datastore invokes the callback written for ipv6 address delete. It is again trying to delete the link-local address and getting failed. I don't want this call to happen. Is there any way to restrict this call.

Thanks,
Swathin

**Comment by michalvasko** [comment]
Hi Swathin,
your problem is that the link-local addresses on the device are being deleted twice. You are trying to prevent the second deletion from happening. I am advising you to instead prevent the first deletion from happening, which to my understanding is simply because you simply remove it from your code (remove the flushing from the [function](https://github.com/CESNET/netopeer/blob/master/transAPI/cfginterfaces/iface_if.c#L2563)). Am I mistaken somewhere and is it not possible?

Regards,
Michal

**Comment by swathins079** [comment]
Hi Michal,

I thought there will be some apis that I can call for syncing the running datastore with the device configuration. The workaround you said will do the job but it would be better if there is an api which does the job of syncing.

Thanks,
Swathin

**Comment by michalvasko** [comment]
Hi,
the general principle is that all configuration changes go first through *sysrepo* and then to the device itself. There are at least two reasons, the change can this way be rejected without affecting the device and also, if there are several callbacks registered, all of them will be called. Keeping this in mind, I believe my suggestion is not a workaround but correct solution.

Regards,
Michal

**Comment by swathins079** [comment]
Thanks Michal for suggesting the best solution.

Regards,
Swathin
