### ISSUE TITLE
Is there any way to enable/disable or install/uninstall modules from a netconf-client(such as netopeer2-cli)?

### ISSUE THREAD

**Issue by swathins079** [sysrepo/sysrepo#952]
Can a module say ietf-interfaces be enabled/disabled or installed/uninstalled from a netconf-client through RPC calls? 
Or do we need to implement the same using any callback functions? If so, is there any client library that can be used? or do we need to execute the sysrepoctl command?

Thanks,
Swathin

**Comment by michalvasko** [comment]
Hi Swathin,
simple answer is no, a module can not be normally enabled/disabled from a NETCONF client. However, it should be possible to add this support.

Firstly, you must write your own YANG module with whatever RPCs you want (such as `enable-module` and `disable-module`). Then, you should write a *sysrepo* plugin or daemon that will handle these RPCs by calling `sysrepoctl` with correct parameters (unfortunately there is no `libsysrepo` call that would do this, you must use `sysrepoctl`). This way you should be able to do what you want even though it is not an elegant solution, I know no better.

Regards,
Michal

**Comment by swathins079** [comment]
Thanks Michal for the quick response. I am planning to take the code from sysrepoctl and implementing that in the callback function of my custom yang.

Regards,
Swathin
