### ISSUE TITLE
Why does the datastore need to be enabled to copy-config from startup to candidate

### ISSUE THREAD

**Issue by darren-west** [sysrepo/sysrepo#953]
Hi,

This is a question not an actual issue. I have looked at the documentation but am a bit confused.

I am unsure why the running datastore needs to be enabled for a modules startup configuration to be copied from startup to candidate?

for example I want to copy all the config from my example-module startup datastore to that sessions candidate store. When I try this I get an error about the datastore not being enabled.

Thanks in advance,
Darren

**Comment by michalvasko** [comment]
Hi Darren,
I was doing some changes in this some time ago so I don't remember all the details, but I think this feature emerged naturally from *sysrepo* design and I did not consider it a problem to make an effort to change it. The general principle is that you have to have a module enabled to work with it.

Regards,
Michal
