### ISSUE TITLE
leafref cannot be resolved, if the target is in an imported file (mixed includes/imports)

### ISSUE THREAD

**Issue by frimpler** [sysrepo/sysrepo#962]
Hi,
please have a look at this commit:
https://github.com/frimpler/sysrepo/commit/cc8a951e2b0659befe7ca836aa6ed28c6814490c
It contains a test case which triggers by installation of a set of schema files, that a target for a leafref (might also be affect other references) cannot be resolved. 

Problem Description:
---------------------------
The function md_insert_lys_module() parses recursively included submodules and imported modules (in this sequence). Additionally it traverses (in any depth of recursion) the schema tree and tries to resolve dependencies. This fails, if e.g. imports are not yet considered when descended down somewhere in submodules.

Please have a look at the schema files. The parse sequences is m1->m2->m3->s1->s2, but ignores m4 with is imported in m3.

Regards,
Frank

**Comment by michalvasko** [comment]
Hi Frank,
thanks for the test case, I finished it and included in the pull request, so it should work now.

Regards,
Michal

**Comment by frimpler** [comment]
Thanks Michal. I'm a bit afraid, that just swapping the order of import/include parsing brings other problems to the surface. But at the moment I have no proof for it :-)

**Comment by michalvasko** [comment]
Hi Frank,
I hope not, statements from included submodules can require imports to be resolved (as your test proved) but I cannot think of a situation when imported modules would require includes to be resolved, it does not even make sense.

Regards,
Michal
