### ISSUE TITLE
is there any efficient method  to query data ,if we query 800 times ,40 second will cost

### ISSUE THREAD

**Issue by ZhaoGuangYue1986** [sysrepo/sysrepo#963]
we found it cost 0.05s to get the data, i think it is very slow for us ,as we have more than one xpath  to query( may be   over 800 )  in each business process i think it is unacceptable. for example ,if we have 800 items to query ,it will cost :800*0.05=40s

---------------part log for query------------------
  
 2015/1/22 7:26:28 520003 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:492) Sending session-refresh request.     
 2015/1/22 7:26:28 520031 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) session-refresh request sent, waiting for response.  
 2015/1/22 7:26:28 522207 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) session-refresh response received, processing.         
 2015/1/22 7:26:28 522260 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) get-items request sent, waiting for response.  
 2015/1/22 7:26:28 585010 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) get-items response received, processing.    

 2015/1/22 7:26:28 585484 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:492) Sending session-refresh request.     
 2015/1/22 7:26:28 585517 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) session-refresh request sent, waiting for response.  
 2015/1/22 7:26:28 587880 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) session-refresh response received, processing.           
 2015/1/22 7:26:28 587934 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) get-items request sent, waiting for response.  
 2015/1/22 7:26:28 651594 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) get-items response received, processing.    

 2015/1/22 7:26:28 651752 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:492) Sending session-refresh request.     
 2015/1/22 7:26:28 651780 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) session-refresh request sent, waiting for response.  
 2015/1/22 7:26:28 654335 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) session-refresh response received, processing.          
 2015/1/22 7:26:28 654387 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) get-items request sent, waiting for response.  
 2015/1/22 7:26:28 718554 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) get-items response received, processing.    

 2015/1/22 7:26:28 719035 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:492) Sending session-refresh request.     
 2015/1/22 7:26:28 719062 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) session-refresh request sent, waiting for response.  
 2015/1/22 7:26:28 721594 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) session-refresh response received, processing.           
 2015/1/22 7:26:28 721647 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) get-items request sent, waiting for response.  
 2015/1/22 7:26:28 785663 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) get-items response received, processing.    

 2015/1/22 7:26:28 785857 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:492) Sending session-refresh request.     
 2015/1/22 7:26:28 785887 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) session-refresh request sent, waiting for response.  
 2015/1/22 7:26:28 788332 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) session-refresh response received, processing.        
 2015/1/22 7:26:28 788384 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) get-items request sent, waiting for response.  
 2015/1/22 7:26:28 851834 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) get-items response received, processing.    

 2015/1/22 7:26:28 852367 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:492) Sending session-refresh request.     
 2015/1/22 7:26:28 852397 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) session-refresh request sent, waiting for response.  
 2015/1/22 7:26:28 854690 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) session-refresh response received, processing.          
 2015/1/22 7:26:28 854742 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) get-items request sent, waiting for response.  
 2015/1/22 7:26:28 918620 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) get-items response received, processing.    

 2015/1/22 7:26:28 918788 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:492) Sending session-refresh request.     
 2015/1/22 7:26:28 918818 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) session-refresh request sent, waiting for response.  
 2015/1/22 7:26:28 921301 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) session-refresh response received, processing.           
 2015/1/22 7:26:28 921353 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) get-items request sent, waiting for response.  
 2015/1/22 7:26:28 986173 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) get-items response received, processing.    

 2015/1/22 7:26:28 986700 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:492) Sending session-refresh request.     
 2015/1/22 7:26:28 986727 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) session-refresh request sent, waiting for response.  
 2015/1/22 7:26:28 989251 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) session-refresh response received, processing.         
 2015/1/22 7:26:28 989302 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) get-items request sent, waiting for response.  
 2015/1/22 7:26:29 54041 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) get-items response received, processing.    

 2015/1/22 7:26:29 54202 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:492) Sending session-refresh request.     
 2015/1/22 7:26:29 54232 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) session-refresh request sent, waiting for response.  
 2015/1/22 7:26:29 56748 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) session-refresh response received, processing.        
 2015/1/22 7:26:29 56799 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) get-items request sent, waiting for response.  
 2015/1/22 7:26:29 119075 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) get-items response received, processing.    

 2015/1/22 7:26:29 119635 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:492) Sending session-refresh request.     
 2015/1/22 7:26:29 119666 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) session-refresh request sent, waiting for response.  
 2015/1/22 7:26:29 122757 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) session-refresh response received, processing.          
 2015/1/22 7:26:29 122809 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) get-items request sent, waiting for response.  
 2015/1/22 7:26:29 187675 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) get-items response received, processing.    

 2015/1/22 7:26:29 187855 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:492) Sending session-refresh request.     
 2015/1/22 7:26:29 187887 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) session-refresh request sent, waiting for response.  
 2015/1/22 7:26:29 191002 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) session-refresh response received, processing.          
 2015/1/22 7:26:29 191054 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) get-items request sent, waiting for response.  
 2015/1/22 7:26:29 254609 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) get-items response received, processing.    

 2015/1/22 7:26:29 255125 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:492) Sending session-refresh request.     
 2015/1/22 7:26:29 255153 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) session-refresh request sent, waiting for response.  
 2015/1/22 7:26:29 257577 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) session-refresh response received, processing.           
 2015/1/22 7:26:29 257628 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) get-items request sent, waiting for response.  
 2015/1/22 7:26:29 320424 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) get-items response received, processing.    

 2015/1/22 7:26:29 320592 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:492) Sending session-refresh request.     
 2015/1/22 7:26:29 320619 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) session-refresh request sent, waiting for response.  
 2015/1/22 7:26:29 323086 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) session-refresh response received, processing.          
 2015/1/22 7:26:29 323136 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) get-items request sent, waiting for response.  
 2015/1/22 7:26:29 384896 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) get-items response received, processing.   
 
 2015/1/22 7:26:29 385430 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:492) Sending session-refresh request.     
 2015/1/22 7:26:29 385460 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) session-refresh request sent, waiting for response.  
 2015/1/22 7:26:29 387721 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) session-refresh response received, processing.          
 2015/1/22 7:26:29 387773 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) get-items request sent, waiting for response.  
 2015/1/22 7:26:29 449820 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) get-items response received, processing. 
 
 2015/1/22 7:26:29 449971 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:492) Sending session-refresh request.     
 2015/1/22 7:26:29 450000 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) session-refresh request sent, waiting for response.  
 2015/1/22 7:26:29 452203 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) session-refresh response received, processing.         
 2015/1/22 7:26:29 452254 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) get-items request sent, waiting for response.  
 2015/1/22 7:26:29 513322 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) get-items response received, processing.   
 
 2015/1/22 7:26:29 513796 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:492) Sending session-refresh request.     
 2015/1/22 7:26:29 513825 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) session-refresh request sent, waiting for response.  
 2015/1/22 7:26:29 516185 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) session-refresh response received, processing.         
 2015/1/22 7:26:29 516236 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) get-items request sent, waiting for response.  
 2015/1/22 7:26:29 578244 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) get-items response received, processing.  
 
 2015/1/22 7:26:29 578411 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:492) Sending session-refresh request.     
 2015/1/22 7:26:29 578442 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) session-refresh request sent, waiting for response.  
 2015/1/22 7:26:29 581582 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) session-refresh response received, processing.         
 2015/1/22 7:26:29 581634 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) get-items request sent, waiting for response.  
 2015/1/22 7:26:29 643627 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) get-items response received, processing.   
 
 2015/1/22 7:26:29 644150 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:492) Sending session-refresh request.     
 2015/1/22 7:26:29 644179 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) session-refresh request sent, waiting for response.  
 2015/1/22 7:26:29 646695 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) session-refresh response received, processing.           
 2015/1/22 7:26:29 646748 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) get-items request sent, waiting for response.  
 2015/1/22 7:26:29 709087 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) get-items response received, processing.  
 
 2015/1/22 7:26:29 709233 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:492) Sending session-refresh request.     
 2015/1/22 7:26:29 709261 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) session-refresh request sent, waiting for response.  
 2015/1/22 7:26:29 711589 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) session-refresh response received, processing.            
 2015/1/22 7:26:29 711639 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) get-items request sent, waiting for response.  
 2015/1/22 7:26:29 775300 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) get-items response received, processing.   
 
 2015/1/22 7:26:29 775789 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:492) Sending session-refresh request.     
 2015/1/22 7:26:29 775816 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) session-refresh request sent, waiting for response.  
 2015/1/22 7:26:29 778204 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) session-refresh response received, processing.           
 2015/1/22 7:26:29 778266 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) get-items request sent, waiting for response.  
 2015/1/22 7:26:29 841698 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) get-items response received, processing.   
 
 2015/1/22 7:26:29 841860 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:492) Sending session-refresh request.     
 2015/1/22 7:26:29 841887 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) session-refresh request sent, waiting for response.  
 2015/1/22 7:26:29 844207 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) session-refresh response received, processing.          
 2015/1/22 7:26:29 844257 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) get-items request sent, waiting for response.  
 2015/1/22 7:26:29 907321 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) get-items response received, processing.   
 
 2015/1/22 7:26:29 907829 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:492) Sending session-refresh request.     
 2015/1/22 7:26:29 907858 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) session-refresh request sent, waiting for response.  
 2015/1/22 7:26:29 910951 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) session-refresh response received, processing.          
 2015/1/22 7:26:29 911003 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) get-items request sent, waiting for response.  
 2015/1/22 7:26:29 974465 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) get-items response received, processing.   
 
 2015/1/22 7:26:29 974652 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:492) Sending session-refresh request.     
 2015/1/22 7:26:29 974682 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) session-refresh request sent, waiting for response.  
 2015/1/22 7:26:29 977008 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) session-refresh response received, processing.          
 2015/1/22 7:26:29 977059 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) get-items request sent, waiting for response.  
 2015/1/22 7:26:30 41260 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) get-items response received, processing.  
 
 2015/1/22 7:26:30 42027 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:492) Sending session-refresh request.     
 2015/1/22 7:26:30 42058 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) session-refresh request sent, waiting for response.  
 2015/1/22 7:26:30 45488 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) session-refresh response received, processing.          
 2015/1/22 7:26:30 45540 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:515) get-items request sent, waiting for response.  
 2015/1/22 7:26:30 109646 [DEBUG] sysrepo_data_repository.cpp[85]:[140525032150784] (cl_request_process:538) get-items response received, processing.

**Comment by michalvasko** [comment]
Hi,
optimizing *sysrepo* is planned so I can take a look at it then. For now I can only suggest you retrieve as much data from *sysrepo* on one `sr_get_items`/`sr_get_items_iter` call as possible.

Regards,
Michal

**Comment by ostack** [comment]
optimizing sysrepo  sounds good，hope we can see more architecture Docs  and join it

**Comment by michalvasko** [comment]
Fixed.
