### ISSUE TITLE
new function sr_realloc_values

### ISSUE THREAD

**Issue by mislavn** [sysrepo/sysrepo#965]
One of the problems I encountered with the callback's of type:
`typedef int (*sr_dp_get_items_cb)(const char *xpath, sr_val_t **values, size_t *values_cnt, void *private_ctx);`

Is when I need to return a list and I don't know how big will it be, so I have to create a custom linked list, populate it with data and pass that data to `sr_val_t **` at the end of the callback.

Is it possible to implement a new function which can change the size of the array, example:

```
// start callback
size_t value_cnt = 2;
sr_val_t *values = NULL;
sr_new_values(value_cnt, &values);

/* working */

value_cnt = 4;
sr_realloc_values(value_cnt, &values);

/* working */

// end callback
```

This might be trick because of the custom sysrepo memory management, I'm not sure.

**Comment by michalvasko** [comment]
Hi Mislav,
after briefly looking at the custom memory management, it seems to me this should be possible to implement. Still, it is an enhancement and not a bugfix, so I think it can be kept for later. Until then I suggest to use standard `malloc` and `realloc`, only at the end move the data into a new memory obtained using `sr_new_values`.

Regards,
Michal

**Comment by mislavn** [comment]
Hi Michal,

yes I agree with you, we have a similar approach where we have a linked list with single value structs and at the end create the whole array with sr_new_values.

Regards,
Mislav

**Comment by michalvasko** [comment]
Hi Mislav,
I had a fairly thorough look at the *sysrepo* memory management and came to the conclusion that this is not possible to implement with the current structures. Reason being that the size of the allocated memory chunk is lost so it is impossible to decide whether there is some free memory following the already-allocated chunk or the data must be moved into a bigger new memory block.

I do not think we should add tracking of the chunk sizes of any kind into *sysrepo*. But, if you would not mind giving the current size of the memory block as a parameter (wrapped as the number of values in your case, naturally), then it would be possible and if used correctly (reallocating one memory chunk until its final size, not interleaving 2 reallocations) it should also be efficient.

Regards,
Michal

**Comment by mislavn** [comment]
Hi Michal,

I think this is a good approach. At the moment this is not a priority for us but generally it would be useful to have this function.

Regards,
Mislav
