### ISSUE TITLE
Which data files are needed for configuration persistence?

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#966]
Our systems have some built-in flash with limited write cycles. I've noticed that sysrepo stores a lot of information which appear to be transient to disk. For example, it is pretty happy to write to e.g. `/etc/sysrepo/data/somemodule.running`. Rather than fighting with this, and because we are using an overlay filesystem for `/etc` anyway, I would like to know what files are actually *needed* to persist across reboots. Is it OK to preserve just `/etc/sysrepo/data/*.startup`?

I was thinking about using something like this:
```sh
while true; do
  inotifywait -e CLOSE_WRITE /etc/sysrepo/data/*.startup && \
    mkdir -p /persistent-storage/etc/sysrepo/data/ && \
    cp -a /etc/sysrepo/data/*.startup /persistent-storage/etc/sysrepo/data/
done
```
Is that reasonable? Am I missing some critical pieces? From the documentation it seems that the `somemodule.persist` is used for bits like feature enabling which I think is something that cannot be done via NETCONF.

Will sysrepo run if it can only find a `mymodule.startup` and no other data file?

**Comment by michalvasko** [comment]
Hi,
you definitely do not need `.running` files. Regarding `.persist` files, except for features, they also store subscriptions to those modules. Also, there is the list of modules and their dependencies, `/etc/sysrepo/data/internal/sysrepo-module-dependencies.xml`. But, if you have installed *sysrepo* only once and then always communicate with it only using NETCONF, you should be fine preserving only `.startup` changes as long as you do not need notifications replay.

Regards,
Michal
