### ISSUE TITLE
Redefinition Error when compiled with i686-cm-linux-gcc v4.5.1

### ISSUE THREAD

**Issue by swathins079** [sysrepo/sysrepo#970]
I am trying to cross-compile the sysrepo for x86 arch with i686-cm-linux-gcc v4.5.1. Resolved all the dependencies, now i am facing lots and lots of redefinition errors. The flags -Wpedantic and -std=gnu11 are not supported by the compiler.

Thanks,
Swathin

**Comment by michalvasko** [comment]
Hi Swathin,
like I said previously, you will have to sort cross-compilation problems yourself. Maybe you can use some other flags that would result in the same functionality, it depends on the compiler.

Regards,
Michal

**Comment by swathins079** [comment]
Hi Michal,
I somehow resolved the redefinition errors.. Now I am facing some other issues :(

Thanks,
Swathin
