### ISSUE TITLE
Regression in ops data retrieval

### ISSUE THREAD

**Issue by jktjkt** [sysrepo/sysrepo#972]
Commit 7921d334fd2c3346d4afeb087983f6de0672240a introduced a regression with [this YANG model `dummy-amp.yang`](https://github.com/sysrepo/sysrepo/files/1431657/dummy-amp.yang.txt). This code used to work before (`REQUIRE` is an assert-like macro):
```c++
auto vals = session->get_items((modulePrefix + ":amplifier/stage-1/sensors/*").c_str());
REQUIRE(!!vals)
```
I added some debugging output to that commit. Previsouly, it used this XPath:
```
/dummy-amp:amplifier/stage-1/sensors/*
```
whereas it now gets transformed into:
```
/dummy-amp:amplifier/stage-1/amp-stage/sensors/*
```
It seems that an extra `amp-stage`, which is a name of a nested grouping, gets inserted to the middle of the XPath.

**Comment by michalvasko** [comment]
Hi,
thanks, should be fixed.

Regards,
Michal
