### ISSUE TITLE
sysrepo can't handle '/' in key values

### ISSUE THREAD

**Issue by mislavn** [sysrepo/sysrepo#973]
### Description
Can not add '/' to the key name in a list.

### Steps to Reproduce
1. sysrepocfg -f json -e vim -d startup ietf-interfaces
2. in name leaf add '/'.

**Expected behavior:**
 Sysrepo should be able to parse '/' and '\' signs.

**Actual behavior:**
[ERR] Requested node is not valid /ietf-interfaces:interfaces/interface[name='et/h1']
[ERR] Set item failed
[ERR] Set item failed for '/ietf-interfaces:interfaces/interface[name='et/h1']', session id=704348925.
[ERR] Error by processing of the set-item request (session id=704348925): Invalid expression..
[ERR] Error by processing of the request.
[ERR] Error returned from sr_set_item: Invalid argument.

The same thing happens if '//' or '\\/' is used.

Also if you add '\\' it will try to escape it but if you add '\\\\' it will show '..\\\\..' in the key name.

### Versions
Latest devel branches.

### Hint
The problem might be in the [xpath](https://github.com/sysrepo/sysrepo/blob/master/inc/sysrepo/xpath.h) header.

> /**
>  * @defgroup xpath_utils XPath Processing Utilities
>  * @{
>  *
>  *  @brief Set of helpers working on a subset of xpath expressions used of node identification
>  *  Functions modify inputs arguments by placing termination zero at appropriate places to save up
>  *  string duplication. The state of processing is stored in ::sr_xpath_ctx_t opaque for user.
>  *  It allows to continue in processing where the processing stopped or recover processed input.
>  *
>  *  Similarly to strtok function in all subsequent calls that is supposed to work with the same
>  *  input xpath must be NULL.
>  *
>  *  @note Functions expects that key values do not contain
>  *  characters like '[=/. If any yes it can lead to undefined behavior.
>  */

Regards,
Mislav

**Comment by michalvasko** [comment]
Hi Mislav,
you can test my pull request, I modified the code based on the test cases so some values may not be covered. If you encounter such values, let us know.

Regards,
Michal

**Comment by mislavn** [comment]
Thanks Michal, it fixed my problem.
