### ISSUE TITLE
Subscribe to a subtree as data provider

### ISSUE THREAD

**Issue by samuel-gauthier** [sysrepo/sysrepo#976]
### Description

When subscribing to subtrees as data provider in a plugin (using sr_dp_get_items_subscribe), get_items callbacks are called for data queries of the whole module, not of the subtree.
Having all the data provider callbacks of a module being called for each query leads to a lot of unnecessary calculations.

### Steps to Reproduce

1. Create a connection, a session, and subscribe to two different xpaths of the same module, with two different callbacks
* /module-A:A/subtree-A - cb_a
* /module-A:A/subtree-B - cb_b
2. Ask for the data for /module-A:A/subtree-A, for instance:
sysrepocfg -o --get /module-A:A/subtree-A/.

**Expected behavior:**
I expected only cb_a to be called.

**Actual behavior:**
Both callbacks cb_a and cb_b are called.
Note that the result contains only the data created by cb_a, for /module-A:A/subtree-A, which is correct.

### Versions

sysrepod - sysrepo daemon, version 0.7.1

**Comment by michalvasko** [comment]
Fixed.
