### ISSUE TITLE
netopeer2-server not able to connect to sysrepo - new version 

### ISSUE THREAD

**Issue by dileepravindran** [sysrepo/sysrepo#978]
Hi , netopeer2-server is not connecting to sysrepod . logs 

netopeer2-server[20413]: Sysrepo daemon has been started.
netopeer2-server[20413]: Unable to connect to sysrepod: The peer disconnected.
netopeer2-server[20413]: Unable to connect to sysrepod (The peer disconnected).
netopeer2-server[20413]: nc_ps_clear: invalid argument (ps).

**Comment by michalvasko** [comment]
Hi,
please try to reinstall all the dependencies (*libyang*, *libnetconf2*, *libsysrepo*), *sysrepo*, and *netopeer2-server*, it will most likely work. If it is not working after a fresh install, tell us at least what branch of sysrepo/netopeer/libyang/libnetconf2 are you using and the Linux distribution.

Regards,
Michal
