### ISSUE TITLE
devel branch compile error

### ISSUE THREAD

**Issue by jjin62** [sysrepo/sysrepo#979]
Latest devel:

### Steps to Reproduce
Scanning dependencies of target COMMON
[  1%] Building C object src/CMakeFiles/COMMON.dir/common/sysrepo.pb-c.c.o
[  1%] Building C object src/CMakeFiles/COMMON.dir/common/sr_common.c.o
[  2%] Building C object src/CMakeFiles/COMMON.dir/common/sr_utils.c.o
/home/jimmy/sysrepo/src/common/sr_utils.c: In function ‘sr_subtree_to_dt’:
/home/jimmy/sysrepo/src/common/sr_utils.c:1721:22: error: too many arguments to function ‘ly_ctx_get_module’
             module = ly_ctx_get_module(ly_ctx, sr_tree->module_name, NULL, 1);
                      ^
In file included from /home/jimmy/sysrepo/src/common/sr_utils.c:38:0:
/usr/local/include/libyang/libyang.h:1194:26: note: declared here
 const struct lys_module *ly_ctx_get_module(const struct ly_ctx *ctx, const char
                          ^
/home/jimmy/sysrepo/src/common/sr_utils.c:1729:18: error: too many arguments to function ‘ly_ctx_get_module’
         module = ly_ctx_get_module(ly_ctx, ns, NULL, 1);
                  ^
In file included from /home/jimmy/sysrepo/src/common/sr_utils.c:38:0:
/usr/local/include/libyang/libyang.h:1194:26: note: declared here
 const struct lys_module *ly_ctx_get_module(const struct ly_ctx *ctx, const char
                          ^
/home/jimmy/sysrepo/src/common/sr_utils.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-language-extension-token’
src/CMakeFiles/COMMON.dir/build.make:117: recipe for target 'src/CMakeFiles/COMMON.dir/common/sr_utils.c.o' failed
make[2]: *** [src/CMakeFiles/COMMON.dir/common/sr_utils.c.o] Error 1
CMakeFiles/Makefile2:170: recipe for target 'src/CMakeFiles/COMMON.dir/all' failed
make[1]: *** [src/CMakeFiles/COMMON.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

### Versions
sysrepo: latest devel branch
commit 58d97fbb065a5bb8e540152ede8a5497b423a643
Merge: 376079b d119b61
Author: Radek Krejci <rkrejci@cesnet.cz>
Date:   Tue Nov 7 15:53:58 2017 +0100

    Merge pull request #975 from michalvasko/sysctl_searchdirs
    
    sysrepoctl support for multiple search directories

libyang: latest master branch
commit 4b1d964e8ff1fc101131bdfb8ce0241e906d0709
Author: Michal Vasko <mvasko@cesnet.cz>
Date:   Mon Nov 6 15:59:54 2017 +0100

    VERSION bump o version 0.13.81

Thanks!

**Comment by mislavn** [comment]
Hi @jjin62,

you are using a libyang master branch on a sysrepo devel branch, that's not recommended.

We suggest using either master or devel branch for all projects: libyang,libnetconf2,sysrepo and Netopeer2 (Netopeer2 has devel-server).

Regards,
Mislav

**Comment by jjin62** [comment]
Mislav,

Seems latest libyang devel branch has the same error.
Scanning dependencies of target yangobj
[  0%] Building C object CMakeFiles/yangobj.dir/src/common.c.o
/home/jimmy/shasta/libs_pub/libyang/src/common.c: In function ‘_transform_json2xml’:
/home/jimmy/shasta/libs_pub/libyang/src/common.c:262:27: error: too many arguments to function ‘ly_ctx_get_module’
                     mod = ly_ctx_get_module(module->ctx, name, NULL, 1);
                           ^


 >git branch
* devel
  master
  master-sysrepo

>git log
commit 023086238351a7eff09fc0bd697fefb404829b96
Author: Michal Vasko <mvasko@cesnet.cz>
Date:   Tue Nov 7 15:48:06 2017 +0100

    VERSION bump to version 0.14.35

**Comment by michalvasko** [comment]
Hi,
all the software is always built after new commits so at least 95% of the time it can be compiled and if not, we already know and usually fix things in matter of minutes. So, clean your object files or clone the whole repository again, I guarantee you it can all be compiled.

Regards,
Michal
