### ISSUE TITLE
Cannot get data after clear non-existent node using remove

### ISSUE THREAD

**Issue by zzyyll2** [sysrepo/sysrepo#984]
### How to submit issue
Open two netopeer-cli,one names sess_1,the other names sess_2.
switch to sess_1,clear non-existent data using operation "remove"
like this,
edit-config --target running --config=clear.xml
switch to sess_2,add some data using edit-config or copy-config,
then get-config sysrepo will return corrected data back.
switch to sess_1 again, get-config or get will return empty data now.

### Things you may try first
(put "x" in "[]" if you already tried following)
* [] Did you check if this is a duplicate issue?
* [x] Did you test it on the latest sysrepo devel branch?

[Example]
YANG:
```yang
module STATE{
	namespace "urn:params:xml:ns:yang:state";
	prefix "state";	
	container C1{
	    presence "enable C1";
		leaf f1{
			type string;
		}		
	}
}
```
clear.xml:
```xml
<C1 xmlns="urn:params:xml:ns:yang:state" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" xc:operation="remove">
</C1>
```
add.xml:
```xml
<C1 xmlns="urn:params:xml:ns:yang:state">
<f1>name</f1>
</C1>
```
### Steps to Reproduce
1. [First Step]
Open one netopeer-cli,
edit-config --target running --config=clear.xml
2. [Second Step]
open another netopeer-cli.
edit-config --target running --config=all.xml
now,you can get some data using get-config --source running
3. [Third Step]
switch to the cli opened at First Step,
get-config --source running,
you will get nothing.

**Expected behavior:**
Maybe at rp_dt_commit@rp_dt_edit.c

**Actual behavior:**
 [What actually happened]

### Versions
Please provide versions for software needed to reproduce the bug:
Sysrepo version: 0.7.1
libyang version: 0.14.21
netopeer2-server: 0.4.6

Thanks!

**Comment by michalvasko** [comment]
Hi,
good catch, the pull request should fix it, thanks.

Regards,
Michal
