### ISSUE TITLE
Question about the function rp_dt_has_parent_list

### ISSUE THREAD

**Issue by ustcpxy** [sysrepo/sysrepo#993]
Hi,
there is a question about `lys_parent` usage in `rp_dt_has_parent_list`.
I think below code should use lys_parent to get n's parent, not directly use pointer.
`struct lys_node *n = node->parent;`

if the n's parent is an augement node.  the following code `n = lys_parent(n);` will get NULL. 
but actually we want get the augement's target node as its parent, not NULL.

in libyang, the API `lys_parent` was meant to be used when one does not want to work with augments at all. 

I also open an issue ( https://github.com/CESNET/libyang/pull/397 ) in libyang.

could you give your comments?  modify sysrepo or libyang?

**Comment by michalvasko** [comment]
Hi,
firstly, please, next time, proceed differently when you encounter an issue. Open an issue **in the project where you encountered the problem**, so this was supposed to be the first opened issue, not last. Of course, we welcome any suggestions as to what the specific problem and even the solution may be, but let the final decision as what the correct fix should be up to us.

So, what exactly is your use-case? From what you written it seems all that is needed is to change the assignment to `struct lys_node *n = lys_parent(node);`, am I right? No issue or pull request in *libyang*.

Regards,
Michal

**Comment by ustcpxy** [comment]
Hi Michal
sorry for the inconvenience. 
I will focus on my issue in sysrepo project. 
yes, to change the assignment can fix my issue.
