### ISSUE TITLE
sr_xpath_key_value is not parsing correctly if the key is mac-address or IP address

### ISSUE THREAD

**Issue by swathins079** [sysrepo/sysrepo#995]
I am using the latest version of all the libraries.
Parsed value i got is something like this "34:80:b3:dc:76:73']/block"

Regards,
Swathin

**Comment by michalvasko** [comment]
Hi Swathin,
please provide the function parameters that produce this result, how else am I to reproduce and fix this?

Regards,
Michal

**Comment by swathins079** [comment]
Hi Michal,

Thanks for quick reponse.

I am having the following yang loaded in the sysrepo.
```
module test {
    container filters {
         list filter {
             key mac-address;
             leaf mac-address {
                 type yang:mac-address;
             }
             leaf block {
                 type boolean;
            }
        }
   } 
}
```

In the callback function, I am trying to get the values of mac-address and block. Since mac-address is the key, I am using the following API to get its value.

`sr_xpath_key_value(new_val ? new_val->xpath : old_val->xpath, "filter", "mac-address", &xpath_ctx);`

But the return value that i am getting is "34:80:b3:dc:76:73']/block". 

In a different scenario, the same thing happened with IP address as well.

Regards,
Swathin

**Comment by michalvasko** [comment]
You said you are using the latest version, `master` or `devel`? Because in `devel` there were some enhancements in this regard, so it may have fixed this. Anyway, I cannot reproduce it in `devel`, my program
```C
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <sysrepo/xpath.h>

int
main()
{
    sr_xpath_ctx_t state;
    char *res, *xpath;

    xpath = strdup("/test/filters/filter[mac-address='34:80:b3:dc:76:73']/block");
    res = sr_xpath_key_value(xpath, "filter", "mac-address", &state);
    printf("%s\n", res);
    free(xpath);

    return 0;
}
```
prints out `34:80:b3:dc:76:73`.

Regards,
Michal

**Comment by swathins079** [comment]
Hi Michal,

I will switch to the devel branch.

Thanks,
Swathin

**Comment by swathins079** [comment]
Hi Michal

I am still getting the same result. updated libyang, sysrepo to the latest devel branch.
Every time I am getting "34:80:b3:dc:76:73']/block" as output.

Regards,
Swathin

**Comment by michalvasko** [comment]
Okay, so, for the last time, can you please provide the input parameters of `sr_xpath_key_value`? I posted my example program that worked, I honestly do not know how am I to reproduce this.

Regards,
Michal

**Comment by swathins079** [comment]
Hi Michal,

I am using the below code to get the mac-address.
`sr_xpath_key_value(new_val ? new_val->xpath : old_val->xpath, "filter", "mac-address", &xpath_ctx); `  

I am calling this inside the callback function as shown:

```
...declarations...
while ((SR_ERR_OK == op_rc || event == SR_EV_ABORT) &&
(SR_ERR_OK == (rc = sr_get_change_next(session, iter, &op, &old_val, &new_val)))) {

sr_xpath_key_value(new_val ? new_val->xpath : old_val->xpath,
 "filter", "mac-address", &xpath_ctx);
.....call someother function...
}
```
Below are the params passed.
xpath_ctx: sr_xpath_ctx_t xpath_ctx = { 0, };
new_val: got from sr_get_change_next api
"filter" : name of the list 
"mac-address": key

Thanks,
Swathin

**Comment by michalvasko** [comment]
Hi Swathin,
your specific code is in this case irrelevant and also that the first parameter of `sr_xpath_key_value` is some xpath retrieved from `sr_get_change_next`, I need you to provide the specific XPath that causes the problem. In other words, please fill `<string>` with a string, not a variable!

```C
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <sysrepo/xpath.h>

int
main()
{
    sr_xpath_ctx_t state;
    char *res, *xpath;

    xpath = strdup("<string>");
    res = sr_xpath_key_value(xpath, "filter", "mac-address", &state);
    printf("%s\n", res);
    free(xpath);

    return 0;
}
```

Regards,
Michal

**Comment by swathins079** [comment]
Hi Michal,

Hard coding the xpath didn't work. I am getting the same result.
I will check it in a fresh devel sysrepo + dependencies with a sample yang and let you know.

Thanks,
Swathin

**Comment by michalvasko** [comment]
Hi Swathin,
it is theoretically possible that the `state` is incorrectly reused from some previous iterations, so you can provide the changes that cause this problem (best in the form of the original config and then the content of edit-config). Either way, I need to reproduce it to fix it.

Regards,
Michal

**Comment by swathins079** [comment]
Using strdup(sr_xpath_key_value(new_val ? new_val->xpath : old_val->xpath, "filter", "mac-address", &xpath_ctx)) can solve this problem.

Regards,
Swathin

**Comment by michalvasko** [comment]
Hi Swathin,
so what did you need to change? You posted the same code that was in your application that was not working.

Regards,
Michal
