### ISSUE TITLE
Sysrepo is not functioning properly  after a unique constraint violation

### ISSUE THREAD

**Issue by ykumar-rb** [sysrepo/sysrepo#996]
[Ticket.zip](https://github.com/sysrepo/sysrepo/files/1498133/Ticket.zip)

### Description
[ Sysrepo is not functional after triggering edit -config which violates unique key contraints. After violation, get-config is not working. It gives an error "sysrepo-internal error"

> edit-config --target running --config=unique_org.xml
OK
> get-config --source running --filter-xpath  /debug-sample:org/*
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  Getting items (/debug-sample:org/*//.) from sysrepo failed (Sysrepo-internal error).

]
### Steps to Reproduce
1. [ Send edit-config command using attachment edit_org.xml file]
2. [ Send another edit-config command using unique_org.xml file which ofcourse violating unique key constraint]
3. [Trigger get-config command]

**Expected behavior:**
 [ The edit_config should fail saying if it violates unique key constraint and sysrepo should be functional as before. All subsequent operation should work fine]

**Actual behavior:**
 [On constrainst violation,  edit-config command is returning OK  and subsequent get-config is failing saying "sysrepo-internal error" ]

### Versions
root@Node:/home/yogi/Issue# sysrepod -v
sysrepod - sysrepo daemon, version 0.7.1
root@Node:/home/yogi/Issue# yanglint -v
yanglint 0.13.88
root@Node:/home/yogi/Issue# netopeer2-server -V
netopeer2-server 0.4.4
compile time: Nov 22 2017, 16:44:13

### Attachments
Logs are provided as attachment.

root@Node:/home/yogi/Issue# sysrepoctl -l
Sysrepo schema directory: /etc/sysrepo/yang/
Sysrepo data directory:   /etc/sysrepo/data/
(Do not alter contents of these directories manually)

Module Name                   | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
ietf-netconf-notifications    | 2012-02-06 | Installed   | root:root           | 666         |                               |
ietf-netconf                  | 2011-06-01 | Imported    |                     |             |                               |
ietf-netconf-acm              | 2012-02-22 | Imported    |                     |             |                               |
nc-notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |
notifications                 | 2008-07-14 | Installed   | root:root           | 666         |                               |
turing-machine                | 2013-12-27 | Installed   | root:root           | 666         |                               |
iana-if-type                  | 2014-05-08 | Installed   |                     |             |                               |
ietf-interfaces               | 2014-05-08 | Installed   | root:root           | 666         |                               |
ietf-ip                       | 2014-06-16 | Installed   |                     |             |                               |
ietf-x509-cert-to-name        | 2014-12-10 | Installed   |                     |             |                               |
ietf-keystore                 | 2016-10-31 | Installed   | root:root           | 666         |                               |
ietf-netconf-server           | 2016-11-02 | Installed   | root:root           | 666         |                               | listen ssh-listen tls-listen call-home ssh-call-home tls-call-home
ietf-ssh-server               | 2016-11-02 | Imported    |                     |             |                               |
ietf-tls-server               | 2016-11-02 | Imported    |                     |             |                               |
ietf-system                   | 2014-08-06 | Installed   | root:root           | 666         |                               | authentication local-users
iana-crypt-hash               | 2014-08-06 | Imported    |                     |             |                               |
debug-sample                  | 2017-09-19 | Installed   | root:root           | 666         |                               |

Please help me to fix this issue. Early thought on this issue will be appreciated.

Thanks!

cheers,
Yogesh

**Comment by michalvasko** [comment]
Hi Yogesh,
I did not manage to reproduce the issue in latest `devel` branch, so I guess it got fixed. Can you try it? Make sure the `devel` libraries are really used after installation, it is best to remove the old (`master`) ones.

Regards,
Michal

**Comment by ykumar-rb** [comment]
Hi Michal,

Thanks for quick reply. It may be possible, that it is fixed in devel . 
So, If i understood correctly , are you suggesting to checkout "devel" branch of sysrepo ?

Right now, I have installed master branch of sysrepo and netopeer codebase. I have attached my install script also as part of zipped file.

Can you confirm me , the working branch set for both repositories?

Thanks again!
Cheers,
Yogesh Kumar

**Comment by michalvasko** [comment]
Yeah, that is what I meant, if you are always installing it in some clean environment, using `devel` of *libyang*, *libnetconf2*, *sysrepo* and using `devel-server` of *netopeer2* should fix this. If not, then you perform some different steps than you described.

Regards,
Michal

**Comment by ykumar-rb** [comment]
Yeah ,  sounds good. I will try with suggested branch. If still an issue is reproduced , I will collected respective logs.
As you said, hopefully it is fixed in "devel"  branch.

Thanks!

cheers,
Yogesh

**Comment by ykumar-rb** [comment]
Hi Michal,

Yeah reported issue is already fixed in "devel" branch.

I triggered below commands using netopeer-cli and got expected output:
> edit-config --target running --config=edit_org.xml
OK
> 
> edit-config --target running --config=unique_org.xml
ERROR
                type:     application
                tag:      operation-failed
                severity: error
                path:     /debug-sample:org/organisation[name='Amazon']
                message:  Unique data leaf(s) "orgid" not satisfied in "/debug-sample:org/organisation[name='Avavya']" and "/debug-sample:org/organisation[name='Amazon']".


Thanks for helping me out with right / working branch set. We can close this ticket.

Cheers,
Yogesh Kumar
