### ISSUE TITLE
Query on subscribing to a particular notification from a stream

### ISSUE THREAD

**Issue by swathins079** [sysrepo/sysrepo#998]
I am having a yang file as below:

```
module test {
    notification event1 {
        leaf message {
            type string;
        }
    }
    notification event2 {
        leaf message {
            type string;
        }
    }
}
```

I want to subscribe only for event1 and I tried the following, but it didn't work. I got ok-reply from netopeer-server though.

```
<?xml version="1.0" encoding="UTF-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <create-subscription xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
    <stream>test</stream>
    <filter type="xpath" xmlns:abcd="urn:test:params:xml:ns:yang:abcd" select="/abcd:event1" />
  </create-subscription>
</rpc>
]]>]]>
```

Thanks,
Swathin

**Comment by michalvasko** [comment]
Hi Swathin,
firstly, I assume you are using `devel`, otherwise our results may differ. So, I tried your example and it worked as expected, I have received the notification when I generated it. Did you use `netopeer2-cli` as the client? If so, what command did you use exactly to perform the subscription?

Reagrds,
Michal

**Comment by swathins079** [comment]
Hi Michal,

Thanks for the quick response.
I am using netconf-console, a netconf client from tailf. I will check the same with netopeer2-cli.

Regards,
Swathin

**Comment by michalvasko** [comment]
Hi Swathin,
the main question is whether *netconf-console* supports notifications, *netopeer2-server* should not require for the client to also use *libnetconf2* for the notifications to work.

Regards,
Michal
