### ISSUE TITLE
Query on RPC Usage

### ISSUE THREAD

**Issue by swathins079** [sysrepo/sysrepo#999]
Is it possible to use RPC from a netconf client?
Something similar to the below code from a netconf client
`rc = sr_rpc_send(session, "/turing-machine:run-until", input, input_cnt, &output, &output_cnt);`

Regards,
Swathin

**Comment by michalvasko** [comment]
Hi Swathin,
sure, every RPC is supported if you use `user-rpc` command. The other specific RPC commands are simply a nicer interface for the user and the input parameters, you do not have to use them at all, strictly speaking (`get`, `get-config`, `edit-config`, ...). Well, except for `create-subscription`, because this command not just sends the RPC but also starts a separate thread that reads notifications.

Regards,
Michal

**Comment by swathins079** [comment]
Hi Michal,
 
Thanks for the quick reply. I am still unclear on the usage of rpc in a yang file. Could you give a simple example using a netconf-client such as netopeer2-cli.

Regards,
Swathin

**Comment by michalvasko** [comment]
Ho Swathin,
sure, this is what I used when testing your issue.

Module `test.yang`
```yang
module test {
    namespace "urn:test";
    prefix t;

    notification event1 {
        leaf message {
            type string;
        }
    }
}
```

RPC XML
```xml
<event1 xmlns="urn:test">
  <message>test-message</message>
</event1>
```

You either store the XML in a file and then pass it to `user-rpc` in the `content` parameter or do not use any parameter and then paste it into the editor when the command asks for the content.

Regards,
Michal

**Comment by swathins079** [comment]
hi Mishal,

Will this be similar if I use rpc instead?

If i am using the following yang,

```
module test {
    namespace "urn:test";
    prefix t;

    rpc event1 {
        leaf message {
            type string;
        }
    }
}
```
Then, i have to send the RPC as 
```
<event1 xmlns="urn:test">
  <message>test-message</message>
</event1>
```
Is it correct?

Thanks,
Swathin

**Comment by michalvasko** [comment]
Oh, sorry, I have not changed it to RPC, now it should be fine.

**Comment by swathins079** [comment]
Thanks, Michal. I am able to do it from a netconf client.

Regards,
Swathin
